### PR TITLE
Address ICEs running w/ incremental compilation and building glium

### LINKED ISSUE #32015: Clarify cross-crate dependency story
We're currently doing some wrong-ish things with respect to dep-graph tracking across crate boundaries. I think what I want to do is this:

- Create a `DepNode::MetaData(DefId)` variant that plays a role like `Hir`
  - it basically represents the metadata for some item
- Whenever we load from metadata for item `X`, we'll generate a read on `MetaData(X)`
- In the metadata, we'll include a hash for each item, either:
  - hashing the saved contents of the item
  - or hashing all the base input nodes that are deps of the things serialized into
  - basically some hash we can use to tell if the metadata for an item changed in some way
- When we save the dep-graph, we'll save the hash out of the crate metadata
- When we load, we'll reload the hash out of the current crate metadata and compare

For inlined items, I hope we will transition to MIR and not need to inline sooner or later, but in the meantime, I think we can basically translate reads to `Hir(X)` where `X` is an inlined def-id to `MetaData(Y)` where `Y` is the original def-id -- we may also just be able to ignore accesses to inlined def-ids, since we'll presumably add an appropriate edge from some other source.

### LINKED ISSUE #34991: ICEs with incremental compilation building glium
@jonas-schievink writes in https://github.com/rust-lang/rust/pull/34956:

> I just tried to build glium with this and I'm hitting multiple ICEs about local/foreign items:
> https://gist.github.com/jonas-schievink/536a1ad7aa065193e4954242c9885cbd
> (I've set RUSTFLAGS=-Zincremental=target/INCREMENTAL before running cargo)

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes for various ICEs I encountered trying to build glium with incremental compilation enabled. Building glium now works. Of the 4 ICEs, I have test cases for 3 of them -- I didn't isolate a test for the last commit and kind of want to go do other things -- most notably, figuring out why incremental isn't saving much _effort_.

But if it seems worthwhile and I can come back and try to narrow down the problem.

r? @michaelwoerister 

Fixes #34991 
Fixes #32015

### CODE REVIEW

File: src/librustc/hir/map/definitions.rs [hunk 1]
```diff
@@ -109,6 +111,28 @@ impl DefPath {
...
     }
+
+    pub fn to_string(&self, tcx: TyCtxt) -> String {
+        let mut s = String::with_capacity(self.data.len() * 16);
+
+        if self.krate == LOCAL_CRATE {
+            s.push_str(&tcx.crate_name(self.krate));
+        } else {
+            s.push_str(&tcx.sess.cstore.original_crate_name(self.krate));
+        }
```
Comment (michaelwoerister) [inline src/librustc/hir/map/definitions.rs]: `TyCtxt::crate_name()` should already take care of the local/extern crate switch.

File: src/librustc/hir/map/mod.rs [hunk 2]
```diff
@@ -196,9 +196,20 @@ pub struct Map<'ast> {
     map: RefCell<Vec<MapEntry<'ast>>>,
 
     definitions: RefCell<Definitions>,
+
+    num_noninlined_node_ids: usize,
```
Comment (michaelwoerister) [inline src/librustc/hir/map/mod.rs]: This should conflict with `local_node_id_watermark` from the recently merged #35114. We should make sure to merge this intelligently.

File: src/librustc/hir/map/mod.rs [hunk 3]
```diff
@@ -196,9 +196,20 @@ pub struct Map<'ast> {
...
+    num_noninlined_def_ids: usize,
 }
 
 impl<'ast> Map<'ast> {
+    pub fn is_inlined_def_id(&self, id: DefId) -> bool {
+        id.is_local() && id.index.as_usize() >= self.num_noninlined_def_ids
+    }
+
+    pub fn is_inlined_node_id(&self, id: NodeId) -> bool {
```
Comment (michaelwoerister) [inline src/librustc/hir/map/mod.rs]: Same as above.

**Comment by michaelwoerister** [comment]
I'm not sure that I like how the Hir/Metadata problem is solved here via the graph post-processing step. It means that during the current compilation session, we still have a graph missing edges, right? Shouldn't you run into the `def_id.is_local()` assertion `HirMap::hir_hash()` when computing the `Metadata` hash for exported things depending on inlined HIR? And if you don't, isn't that fishy?

**Comment by nikomatsakis** [comment]
> It means that during the current compilation session, we still have a graph missing edges, right?

As we said on IRC, I will investigate the alternate approach of "detecting" inlined ids and remapping more eagerly.

**Comment by nikomatsakis** [comment]
@michaelwoerister see last commit, which takes a different strategy that also seems to work.

File: src/librustc_incremental/persist/directory.rs [hunk 4]
```diff
@@ -31,17 +34,66 @@ pub struct DefPathIndex {
...
-    paths: Vec<DefPath>
+    paths: Vec<DefPath>,
+
+    // For each crate, saves the crate-name/disambiguator so that
+    // later we can match crate-numbers up again.
+    krates: Vec<KrateInfo>,
+}
+
+#[derive(Debug, RustcEncodable, RustcDecodable)]
+pub struct KrateInfo {
```
Comment (michaelwoerister) [inline src/librustc_incremental/persist/directory.rs]: Why KrateInfo instead of CrateInfo?

File: src/librustc_incremental/persist/directory.rs [hunk 5]
```diff
@@ -31,17 +34,66 @@ pub struct DefPathIndex {
...
+        DefIdDirectory { paths: vec![], krates: krates }
+    }
+
+    pub fn krate_still_valid(&self,
+                             tcx: TyCtxt,
+                             max_current_crate: ast::CrateNum,
+                             krate: ast::CrateNum) -> bool {
+        // Check that the crate-number still matches. For now, if it
+        // doesn't, just return None. We could do better, such as
+        // finding the new number.
```
Comment (michaelwoerister) [inline src/librustc_incremental/persist/directory.rs]: Is it worth opening an issue for this?

File: src/librustc/dep_graph/README.md [hunk 6]
```diff
@@ -387,3 +391,24 @@ RUST_DEP_GRAPH_FILTER='Hir&foo -> TypeckItemBody & bar'
...
+For the time being, at least, we still sometimes "inline" HIR nodes
+from other crates into the current HIR map. This creates a weird
+scenario where the same logical item (let's call it `X`) has two
+def-ids: the original def-id `X` and a new, inlined one `X'`. `X'` is
+in the current crate, but it's not like other HIR nodes: in
+particular, when we restart compilation, it will not be available to
+hash. Therefore, we do not want `Hir(X')` nodes appearing in our
+graph.  Instead, we want a "read" of `Hir(X')` to be represented as a
+read of `MetaData(X)`, since the metadata for `X` is where the inlined
+representation originated in the first place.
```
Comment (michaelwoerister) [inline src/librustc/dep_graph/README.md]: Good explanation.

File: src/librustc/hir/map/mod.rs [hunk 7]
```diff
@@ -226,60 +226,99 @@ impl<'ast> Map<'ast> {
...
+                                             led to `NotPresent` at `{}`",
+                                            id0, id)
+                                   }),
+                }
+            }
+        } else {
+            // reading from an inlined def-id is really a read out of
+            // the metadata from which we loaded the item.
+            loop {
+                match map[id as usize] {
```
Comment (michaelwoerister) [inline src/librustc/hir/map/mod.rs]: Imagine code like this without `match` exhaustiveness checks `:)`

**Comment by michaelwoerister** [comment]
Looks good to me now! I think the new metadata tracking strategy is a clear improvement over the graph post processing.

File: src/librustc_incremental/persist/directory.rs (hunk 5 above)
Comment (nikomatsakis) [inline src/librustc_incremental/persist/directory.rs]: @michaelwoerister 

> Is it worth opening an issue for this?

I did already: https://github.com/rust-lang/rust/issues/35123

File: src/librustc_incremental/persist/directory.rs (hunk 4 above)
Comment (nikomatsakis) [inline src/librustc_incremental/persist/directory.rs]: > Why KrateInfo instead of CrateInfo?

Because `crate` is a keyword... but yeah I realize now we often use `C` when we can (personally I would just always use `K`...).

**Comment by nikomatsakis** [comment]
@michaelwoerister do you want me to rename the uses of `KrateInfo` to `CrateInfo` (there are also some other cases, like `krate_info()`, in that file, so I guess I should do them all)?

(Also, I see travis failed, but I couldn't quite see why -- trying a full make check locally.)

**Comment by michaelwoerister** [comment]
> do you want me to rename the uses of KrateInfo to CrateInfo (there are also some other cases, like krate_info(), in that file, so I guess I should do them all)?

Yes, please.

**Comment by nikomatsakis** [comment]
@michaelwoerister ok, to fixup tests, I wound up fixing #34765 -- care to review last few commits :)

File: src/librustc_trans/context.rs [hunk 8]
```diff
@@ -538,8 +551,7 @@ impl<'b, 'tcx> SharedCrateContext<'b, 'tcx> {
 
     pub fn get_mir(&self, def_id: DefId) -> Option<CachedMir<'b, 'tcx>> {
```
Comment (michaelwoerister) [inline src/librustc_trans/context.rs]: This could probably use the `memoize` functions.
