### PR TITLE
rustc: correctly transform memory_index mappings for generators.

### LINKED ISSUE #61793: Codegen ICE/regression with 2019-06-12 nightly when using async fn<T: Fn()>(&self, T)
Unfortunately the error message is super thin and I can't provide the source of the project. Therefore it's also hard to provide a minimal reproducible example.

```
thread 'rustc' panicked at 'assertion failed: target_offset >= offset', src/librustc_codegen_llvm/type_of.rs:130:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
  ...
  36: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (2887008e0 2019-06-12) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

Some hints:
- Yesterdays nightly (nightly-2019-06-11-x86_64-apple-darwin) doesn't ICE
- The project makes heavy use of async/await. Therefore it might by related to that. I wondered whether it's about @tmandry's generator optimization from #60187. However I also checked that out locally from their branch 2 days ago and built it myself, and it didn't crash. At that point I had all commits up to "Extract generator_layout as a method" included, only the last commit which was added later was missing.

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #61793, closes #62011 (previous attempt at fixing #61793).

During #60187, I made the mistake of suggesting that the (re-)computation of `memory_index` in `ty::layout`, after generator-specific logic split/recombined fields, be done off of the `offsets` of those fields (which needed to be computed anyway), as opposed to the `memory_index`.

`memory_index` maps each field to its in-memory order index, which ranges over the same `0..n` values as the fields themselves, making it a bijective mapping, and more specifically a permutation (indeed, it's the permutation resulting from field reordering optimizations).

Each field has an unique "memory index", meaning a sort based on them, even an unstable one, will not put them in the wrong order. But offsets don't have that property, because of ZSTs (which do not increase the offset), so sorting based on the offset of fields alone can (and did) result in wrong orders.

Instead of going back to sorting based on (slices/subsets of) `memory_index`, or special-casing ZSTs to make sorting based on offsets produce the right results (presumably), as #62011 does, I opted to drop sorting altogether and focus on `O(n)` operations involving *permutations*:
* a permutation is easily inverted (see the `invert_mapping` `fn`)
  * an `inverse_memory_index` was already employed in other parts of the `ty::layout` code (that is, a mapping from memory order to field indices)
  * inverting twice produces the original permutation, so you can invert, modify, and invert again, if it's easier to modify the inverse mapping than the direct one
* you can modify/remove elements in a permutation, as long as the result remains dense (i.e. using every integer in `0..len`, without gaps)
  * for splitting a `0..n` permutation into disjoint `0..x` and `x..n` ranges, you can pick the elements based on a `i < x` / `i >= x` predicate, and for the latter, also subtract `x` to compact the range to `0..n-x`
  * in the general case, for taking an arbitrary subset of the permutation, you need a renumbering from that subset to a dense `0..subset.len()` - but notably, this is still `O(n)`!
* you can merge permutations, as long as the result remains disjoint (i.e. each element is unique)
  * for concatenating two `0..n` and `0..m` permutations, you can renumber the elements in the latter to `n..n+m`
* some of these operations can be combined, and an inverse mapping (be it a permutation or not) can still be used instead of a forward one by changing the "domain" of the loop performing the operation

I wish I had a nicer / more mathematical description of the recombinations involved, but my focus was to fix the bug (in a way which preserves information more directly than sorting would), so I may have missed potential changes in the surrounding generator layout code, that would make this all more straight-forward.

r? @tmandry

### CODE REVIEW

File: src/test/ui/async-await/issue-61793.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// compile-pass
```
Comment (Centril) [inline src/test/ui/async-await/issue-61793.rs]: Can you elaborate on the problem in the test also?

**Comment by eddyb** [comment]
Actual failure (missed because it's in `stage1`):
```rust
error: variable does not need to be mutable
   --> src/librustc/ty/layout.rs:374:13
    |
374 |         let mut memory_index;
    |             ----^^^^^^^^^^^^
    |             |
    |             help: remove this `mut`
```

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -1349,14 +1345,33 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
         // get included in each variant that requested them in
         // GeneratorLayout.
         debug!("prefix = {:#?}", prefix);
-        let (outer_fields, promoted_offsets) = match prefix.fields {
-            FieldPlacement::Arbitrary { mut offsets, .. } => {
-                let offsets_b = offsets.split_off(discr_index + 1);
+        let (outer_fields, promoted_offsets, promoted_memory_index) = match prefix.fields {
+            FieldPlacement::Arbitrary { mut offsets, memory_index } => {
+                let mut inverse_memory_index = invert_mapping(&memory_index);
```
Comment (tmandry) [inline src/librustc/ty/layout.rs]: To make all of the code dealing with indexes easier to follow, it would help to have a comment that says each memory_index is field_idx -> memory ordering, while each inverse_memory_index is the list of field indices in memory order. I still get these mixed up so I imagine other people reading will, too.

**Review by tmandry — APPROVED** [review]
r=me after my comment. 

Looks good, I knew there was a smarter way of doing it but sorting was so much easier ;) 

I think my original plan was to replace sorting of the combined memory indices with a merge sort, which would also be O(n). (Or maybe I hallucinated that after the fact, I can’t remember.) I think both ways would work. Regardless, I’m happy to get this back to linear time.

File: src/librustc/ty/layout.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc/ty/layout.rs]: There's something about that somewhere that `invert_mapping` is referring to, but I guess I can have a comment that's summarizing everything, copied into a couple places.

Comment (tmandry) [reply src/librustc/ty/layout.rs]: Yeah, there are some inner comments in `univariant_uninterned`. I don't consider them especially discoverable.. maybe it would be good to have an explanation on the `FieldPlacement::Arbitrary::memory_index` field itself and maybe also a summary on `invert_mapping` (since that gets called from both here and `univariant_uninterned`.)

Comment (tmandry) [reply src/librustc/ty/layout.rs]: Another thing I'm noticing is that [we invert the index again](https://github.com/rust-lang/rust/blob/1fc9365c8f04c121265b6b46f083e142baf44620/src/librustc_target/abi/mod.rs#L747) in codegen. It is possible it would be easier to keep it in its inverted form?

Comment (eddyb) [reply src/librustc/ty/layout.rs]: This is intentional, `index_by_increasing_offset` is relatively rarely called (only the LLVM backend needs it, and once per layout), whereas `memory_index` is used for every field access (arguably also only by the LLVM backend, but more frequently).
