### PR TITLE
tests: Fix duplicated-path-in-error fail with musl

### LINKED ISSUE #128474: tests/ui/codegen/duplicated-path-in-error: Fails on musl libc due to ldso error message difference
I tried this code:

```shell
python3 x.py test -j 64 tests/ui
```

I expected to see this happen: all tests passing

Instead, this happened:

```
failures:
    [ui] tests/ui/codegen/duplicated-path-in-error.rs
```

```
diff of stderr:

-	error: couldn't load codegen backend /non-existing-one.so: cannot open shared object file: No such file or directory
+	error: couldn't load codegen backend /non-existing-one.so: Error loading shared library /non-existing-one.so: No such file or directory
```

### Meta
`rustc --version --verbose`:
```
rustc 1.82.0-nightly (249cf71f1 2024-07-30) (Adélie 1.82.0 EXPERIMENTAL)
binary: rustc
commit-hash: 249cf71f11a29b3fb68e8a35969569d8bb7958ee
commit-date: 2024-07-30
host: powerpc64-foxkit-linux-musl
release: 1.82.0-nightly
LLVM version: 18.1.8
```

I'm not familiar enough yet with the machinery around Rust's test suites to know how to change this to a pattern match, but I think ensuring the output is `error: couldn't load codegen backend /non-existing-one.so: (.*): No such file or directory` would be sufficient.  It'd likely help other libcs like llvm-libc in the future, as well.

### PR DESCRIPTION
**Pull request by Gelbpunkt**
musl's dlopen returns a different error than glibc, which contains the name of the file. This would cause the test to fail, since the filename would appear twice in the output (once in the error from rustc, once in the error message from musl). Split the expected test outputs for the different libc implementations.

Fixes rust-lang/rust#128474

### CODE REVIEW

File: tests/ui/codegen/duplicated-path-in-error.rs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 //@ only-linux
 //@ compile-flags: -Zcodegen-backend=/non-existing-one.so
+//@ normalize-stderr: "Error loading shared library .+:" -> "cannot open shared object file:"
```
Comment (workingjubilee) [inline tests/ui/codegen/duplicated-path-in-error.rs]: This depends on the specifics of the libc, but different libcs can have different specifics. This may just make a problem for another libc that wants our support.

Instead introduce the following:
```suggestion
//@ revisions: musl gnu
//@ only-linux
//@ compile-flags: -Zcodegen-backend=/non-existing-one.so
//@[gnu] only-gnu
//@[musl] only-musl
```

...also, add `"only-musl",` to right after here in src/tools/compiletest/src/directive-list.rs and I think it should work automatically:
https://github.com/rust-lang/rust/blob/c6a955468b025dbe3d1de3e8f3e30496d1fb7f40/src/tools/compiletest/src/directive-list.rs#L207

File: tests/ui/codegen/duplicated-path-in-error.rs [hunk 2]
```diff
@@ -1,5 +1,6 @@
...
 
 // This test ensures that the error of the "not found dylib" doesn't duplicate
 // the path of the dylib.
```
Comment (workingjubilee) [inline tests/ui/codegen/duplicated-path-in-error.rs:9]: then on the ERROR down here we will prefix it. the current one will be `//[gnu]` and the new one will be `//[musl]`, containing the messages we are expecting, so like this:
```suggestion
// the path of the dylib.

// other stuff I can't comment on because GitHub reviews aren't great

//[gnu]~? ERROR couldn't load codegen backend /non-existing-one.so
//[musl]~? ERROR idk, you're the one making the PR
```

Comment (Gelbpunkt) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Nice, thanks for the hints! I think I got it working as intended now ~~(edit: woops forgot one change, sec)~~

**Comment by Gelbpunkt** [comment]
Hi @workingjubilee @wesleywiser, would you mind taking another look at this PR? :)

File: tests/ui/codegen/duplicated-path-in-error.rs (hunk 2 above)
Comment (fmease) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Still hasn't been resolved

Comment (Gelbpunkt) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: > Still hasn't been resolved

How exactly? It is resolved AFAICT

Comment (fmease) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Ah right, my bad, prefix match :facepalm:

Comment (jieyouxu) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: I think this is actually fine because the prefix message is the same re. `//~? ERROR couldn't load codegen backend /non-existing-one.so`, and now we're revisioning gnu vs musl error messages, but this needs a comment describing why there are `only-gnu` vs `only-musl` revisions in the first place.

**Comment by jieyouxu** [comment]
Sorry, can you please leave a test comment re. why we're revisioning in the first place? It's not super obvious on a cursory glance. Also r=me after comment nit.
@bors r-

File: tests/ui/codegen/duplicated-path-in-error.rs (hunk 2 above)
Comment (fmease) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Fair re. the comment. I mean it's not gnu vs. musl, it's `only-linux && (only-gnu || only-musl)` which is somewhat self-evident? idk

Comment (jieyouxu) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Right.

Comment (Gelbpunkt) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: There is a case to be made to make the entire test `only-linux && only-gnu` since, while it is testing the error output with a nonexistent backend, the description is rather that it tests for the path not to be duplicated, which it is on musl...

Comment (jieyouxu) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: The original test introduced in #121978 was an anti-regression test for glibc code path's duplicate path error message, so I'm fine with limiting it to gnu-only. But this is fine too.

Comment (Gelbpunkt) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Should I do that instead then or leave it as it is now?

Comment (Gelbpunkt) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Oh, hm. That original issue duplicated the path in the part that isn't the dlopen error, so I guess it should be fine to keep it as is

Comment (jieyouxu) [reply tests/ui/codegen/duplicated-path-in-error.rs:9]: Yeah, the current version is fine.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/143790#issuecomment-3063186682

**Comment by Gelbpunkt** [comment]
> @bors r- [#143790 (comment)](https://github.com/rust-lang/rust/pull/143790#issuecomment-3063186682)

That's a tricky one. The dlopen error comes from the -gnu host trying to compile for the -musl target. Do we have a way to limit the tests based on the flavor of the *host*, not the *target*?

**Comment by workingjubilee** [comment]
Huh, odd. I don't believe so.

**Comment by Gelbpunkt** [comment]
Would it be appropriate to use `//@ force-host` here or should I implement host target directives?

**Comment by jieyouxu** [comment]
If you want this test to be host only, it's `//@ ignore-cross-compile`.

**Comment by Gelbpunkt** [comment]
> If you want this test to be host only, it's `//@ ignore-cross-compile`.

No, not host only, but just compile for the *host triple*. That way the `only-gnu`/`only-musl` directives match that of the host. Since this is supposed to test the compiler's error message, the target is irrelevant anyways.

I think both directives would make the tests pass, but only would skip it, while the other one would still run it.

**Comment by jieyouxu** [comment]
> Since this is supposed to test the compiler's error message, the target is irrelevant anyways.

I'd probably just `//@ ignore-cross-compile`, if the target is irrelevant anyway. I'm open for some stronger/more specific `//@ force-host-arch: xxx`, but that seems overkill for this case.

**Comment by Gelbpunkt** [comment]
> > Since this is supposed to test the compiler's error message, the target is irrelevant anyways.
> 
> I'd probably just `//@ ignore-cross-compile`, if the target is irrelevant anyway. I'm open for some stronger/more specific `//@ force-host-arch: xxx`, but that seems overkill for this case.

Okay, I did that for now then
