### PR TITLE
Deny `async fn` in 2015 edition

### LINKED ISSUE #53714: `async fn` inside inherent impl produces generic parse error on 2015 edition
When compiling for the 2018 edition, rustc allows `async fn` both outside of an impl and within an inherent impl.

When compiling for the 2015 edition, `async fn` works outside of an impl, but putting one inside an inherent impl [produces this error:](
https://play.rust-lang.org/?gist=9d0ecff90e2883a72e7a293915ae2519&version=nightly&mode=debug&edition=2015)
```
error: missing `fn`, `type`, or `const` for impl-item declaration
 --> src/lib.rs:4:9
  |
4 | impl A { async fn inside_impl() {} }
  |         ^ missing `fn`, `type`, or `const`
```

Either this should be allowed, or it should result in a better error message that recommends switching to the 2018 edition.

### LINKED ISSUE #58652: async fn should be disallowed entirely on 2015 edition
As described in https://github.com/rust-lang/rust/issues/53714, we currently permit a small amount of `async` notation in 2015, but we can't extend that to the complete feature set (e.g., await keywords etc). This was done as part of a transitionary tactic (so people could move to Rust 2018) but by now that is not necessary. We should just prohibit `async fn` in Rust 2015 entirely at this point.

### PR DESCRIPTION
**Pull request by cofibrant**
This commit prevents code using `async fn` from being compiled in Rust 2015 edition.

Compiling code of the form:

```rust
async fn foo() {}
```

Will now result in the error:

```
error[E0670]: `async fn` is not permitted in the 2015 edition
 --> async.rs:1:1
  |
1 | async fn foo() {}
  | ^^^^^

error: aborting due to error

For more information about an error, try `rustc --explain E0670`.
```

This resolves #58652 and also resolves #53714.

r? @varkor

### CODE REVIEW

File: src/librustc_passes/ast_validation.rs [hunk 1]
```diff
@@ -702,6 +703,13 @@ impl<'a> Visitor<'a> for AstValidator<'a> {
             .span_bug(mac.span, "macro invocation missed in expansion; did you forget to override \
                                  the relevant `fold_*()` method in `PlaceholderExpander`?");
     }
+
+    fn visit_fn_header(&mut self, header: &'a FnHeader) {
+        if header.asyncness.node.is_async() && self.session.rust_2015() {
+            struct_span_err!(self.session, header.asyncness.span, E0670,
+                             "fns cannot be delcared `async` in 2015 edition").emit();
```
Comment (jonas-schievink) [inline src/librustc_passes/ast_validation.rs]: This says "delcared", should be "declared"

File: src/librustc_passes/diagnostics.rs [hunk 2]
```diff
@@ -310,6 +310,22 @@ loop {
...
+E0670: r##"
+Rust 2015 does not permit the use of `async fn`.
+
+Example of erroneous code:
+
+```compile_fail,E0670
+async fn foo() {}
+```
+
+You can remove the keyword `async`:
```
Comment (jonas-schievink) [inline src/librustc_passes/diagnostics.rs]: Perhaps a better suggestion would be to switch to the 2018 edition?

File: src/librustc_passes/ast_validation.rs (hunk 1 above)
Comment (doctorn) [reply src/librustc_passes/ast_validation.rs]: Oops!

**Comment by varkor** [comment]
> This resolves #58652 and also #53714.

Note that you need to prefix both issues with "resolves" for GitHub to recognise the pull request as closing those issues when merged.

File: src/librustc_passes/diagnostics.rs (hunk 2 above)
Comment (doctorn) [reply src/librustc_passes/diagnostics.rs]: I'll include that as well

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -2681,7 +2681,7 @@ impl<'a> Parser<'a> {
                     hi = path.span;
                     return Ok(self.mk_expr(lo.to(hi), ExprKind::Path(Some(qself), path), attrs));
                 }
-                if self.span.rust_2018() && self.check_keyword(keywords::Async)
+                if self.span.rust_2018() && self.check_keyword(keywords::Async)
```
Comment (varkor) [inline src/libsyntax/parse/parser.rs]: You have extra whitespace at the end of the line here.

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -3861,7 +3861,7 @@ impl<'a> Parser<'a> {
         let asyncness = if self.span.rust_2018() {
             self.parse_asyncness()
         } else {
-            IsAsync::NotAsync
+            IsAsync::NotAsync
```
Comment (varkor) [inline src/libsyntax/parse/parser.rs]: And here.

File: src/librustc_passes/ast_validation.rs (hunk 1 above)
Comment (varkor) [inline src/librustc_passes/ast_validation.rs]: To avoid the awkward spelling "fns", perhaps something like the following would sound read more naturally:
```rust
"`async fn` is not permitted in the 2015 edition"
```

**Comment by varkor** [comment]
Overall, this looks good! Just a couple of minor comments. Also, merge commits are avoided, so if you could rebase your changes instead, that would be great!

File: src/librustc_passes/diagnostics.rs [hunk 5]
```diff
@@ -310,6 +310,18 @@ loop {
...
+E0670: r##"
+Rust 2015 does not permit the use of `async fn`.
+
+Example of erroneous code:
+
+```compile_fail,E0670
+async fn foo() {}
+```
+
+You can switch to Rust 2018 edition (or you can remove the keyword `async`).
```
Comment (varkor) [inline src/librustc_passes/diagnostics.rs]:
```suggestion
Switch to the Rust 2018 edition to use `async fn`.
```
An imperative tone is more in keeping with the error code documentation. Also, I don't think removing the `async` keyword in general is a good suggestion, because if the user has actually used `async` features (i.e. it's not just an empty function), then removing the keyword isn't going to fix anything, because the signature is now incorrect and `await` won't work.

**Review by varkor — APPROVED** [review]
One last stylistic comment, then everything looks good!

If you could squash your changes into a single commit to keep the history cleaner, I'll approve as soon as Travis is happy!

File: src/test/ui/editions/edition-deny-async-fns-2015.rs [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+struct Foo {}
+
+impl Foo {
+    async fn foo() {} //~ ERROR `async fn` is not permitted in the 2015 edition
+}
+
+trait Bar {
+    async fn foo() {} //~ ERROR `async fn` is not permitted in the 2015 edition
+                      //~^ ERROR trait fns cannot be declared `async`
+}
```
Comment (Centril) [inline src/test/ui/editions/edition-deny-async-fns-2015.rs]: Can you add the following?

```rust
macro_rules! accept_item { ($x:item) => {} }

accept_item! {
   async fn foo() {}
}
```
This checks that async fns are not *syntactically valid* on 2015 (which they shouldn't be).

File: src/test/ui/editions/edition-deny-async-fns-2015.rs [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
```
Comment (Centril) [inline src/test/ui/editions/edition-deny-async-fns-2015.rs]: I'd also like to see tests:
```rust
async fn foo() { async fn bar() {} }
fn baz() { async fn bar() {} }

let inside_closure = || { async fn bar() {} };
```

**Review by Centril — DISMISSED** [review]

**Comment by doctorn** [comment]
I've added the extra tests, so this definitely also resolves #51933.

File: src/test/ui/editions/edition-deny-async-fns-2015.rs (hunk 6 above)
Comment (doctorn) [reply src/test/ui/editions/edition-deny-async-fns-2015.rs]: I've added this to the test, and it doesn't error... Is that the desired behaviour?

File: src/test/ui/editions/edition-deny-async-fns-2015.rs [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+
+
+fn main() {
+    macro_rules! accept_item { ($x:item) => {} }
+
+    accept_item! {
+        async fn foo() {}
```
Comment (Centril) [inline src/test/ui/editions/edition-deny-async-fns-2015.rs]: This should be an error; `async fn` shouldn't be a valid `item` at all and should be syntactically rejected on 2015.

Comment (doctorn) [reply src/test/ui/editions/edition-deny-async-fns-2015.rs]: Okay, I think I have a fix, I'm just testing it now

Comment (doctorn) [reply src/test/ui/editions/edition-deny-async-fns-2015.rs]: I've got the to error correctly now

**Comment by varkor** [comment]
Thanks, this looks great!

@bors r+
