### PR TITLE
Revert "Don't load all extern crates unconditionally"

### LINKED ISSUE #84738: Index out of bounds when running `cargo doc` in `rustc_metadata/src/creader.rs`
EDIT(camelid): This issue is now being used to track a different, but related, bug. The discussion starting [here](https://github.com/rust-lang/rust/issues/84738#issuecomment-950370740) is current.

### Steps

- Clone [`rust-gpu`](https://github.com/EmbarkStudios/rust-gpu/tree/2f451ee9939c021b54214d2aeb986ecb7a6d7382).
- `cargo doc -p spirv-std --no-deps`

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (42816d61e 2021-04-24)
binary: rustc
commit-hash: 42816d61ead7e46d462df997958ccfd514f8c21c
commit-date: 2021-04-24
host: x86_64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 8', compiler/rustc_metadata/src/creader.rs:137:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `spirv-std`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name spirv_std crates/spirv-std/src/lib.rs -o /Users/erin.power/src/rust-gpu2/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/Users/erin.power/src/rust-gpu2/target/debug/deps --extern bitflags=/Users/erin.power/src/rust-gpu2/target/debug/deps/libbitflags-7c13a8e06c86cae3.rmeta --extern num_traits=/Users/erin.power/src/rust-gpu2/target/debug/deps/libnum_traits-226168b7b64579d8.rmeta --extern spirv_std_macros=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_std_macros-63f1f4de237cb2bc.dylib --extern spirv_types=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_types-7559b6c8fd9bbf59.rmeta --crate-version 0.4.0-alpha.7` (exit status: 1)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::crate_name
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::force_query_with_job
   7: rustc_query_system::query::plumbing::get_query_impl
   8: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::crate_name
   9: rustdoc::clean::inline::record_extern_fqn
  10: rustdoc::clean::utils::register_res
  11: rustdoc::passes::collect_intra_doc_links::LinkCollector::resolve_link
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  13: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  14: rustdoc::fold::DocFolder::fold_inner_recur
  15: rustdoc::fold::DocFolder::fold_item_recur
  16: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  17: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  18: rustdoc::core::run_global_ctxt
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
  23: rustdoc::main_options
  24: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/84738.

This reverts https://github.com/rust-lang/rust/pull/83738.

For the "smart" load of external crates, we need to be able to access their items in order to check their doc comments, which seems, if not impossible, quite complicated using only the AST.

For some context, I first tried to extend the `IntraLinkCrateLoader` visitor by adding `visit_foreign_item`. Unfortunately, it never enters into this call, so definitely not the right place...

I then added `visit_use_tree` to then check all the imports outside with something like this:

```rust
let mut loader = crate::passes::collect_intra_doc_links::IntraLinkCrateLoader::new(resolver);
    ast::visit::walk_crate(&mut loader, krate);

    let mut items = Vec::new();
    for import in &loader.imports_to_check {
        if let Some(item) = krate.items.iter().find(|i| i.id == *import) {
            items.push(item);
        }
    }
    for item in items {
        ast::visit::walk_item(&mut item);
        for attr in &item.attrs {
            loader.check_attribute(attr);
        }
    }
```

This was, of course, a failure. We find the items without problems, but we still can't go into the external crate to check its items' attributes.

Finally, @jyn514 suggested to look into the [`CrateLoader`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/creader/struct.CrateLoader.html), but it only seems to provide metadata (I went through [`CStore`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/creader/struct.CStore.html) and [`CrateMetadata`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/rmeta/decoder/struct.CrateMetadata.html)).

I think we are too limited here (with AST only) to be able to determine the crates we actually need to import, but it's very likely that I missed something. Maybe @petrochenkov or @Aaron1011 have an idea?

So until we find a way to make it work completely, we need to revert it to fix the ICE. Once merged, we'll need to re-open #68427.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
Please remember to re-open https://github.com/rust-lang/rust/issues/68427 if this gets merged.

**Comment by jyn514** [comment]
I will not have time to review this for a while.

r? @petrochenkov

**Comment by GuillaumeGomez** [comment]
> Please remember to re-open #68427 if this gets merged.

It's in the first message already. ;)

**Comment by petrochenkov** [comment]
I'd prefer to actually fix https://github.com/rust-lang/rust/issues/84738 instead of reverting the PR and re-introducing other bugs.

Waiting on reproduction for #84738 - https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/crate.20loading.20during.20link.20resolution/near/240747900

**Comment by TheBlueMatt** [comment]
Does https://github.com/rust-bitcoin/rust-lightning/blob/main/lightning-background-processor/src/lib.rs qualify as a minimized reproduction? Its only a few method crate and tickles the bug.

**Comment by petrochenkov** [comment]
(I've returned from vacation and will look at this next weekend.)

**Comment by GuillaumeGomez** [comment]
\o/

**Comment by jyn514** [comment]
r=me, this has been causing lots of trouble and we can always do a more proper fix later. @GuillaumeGomez can you fix the conflict real quick?\

**Comment by GuillaumeGomez** [comment]
On it!

File: src/test/rustdoc/intra-doc/extern-crate-only-used-in-link.rs [hunk 1]
```diff
@@ -1,19 +0,0 @@
-// This test is just a little cursed.
```
Comment (jyn514) [inline src/test/rustdoc/intra-doc/extern-crate-only-used-in-link.rs:1]: Please add this test back, it should pass with and without unconditional loading.

File: src/tools/compiletest/src/header.rs [hunk 2]
```diff
@@ -502,8 +502,8 @@ impl Config {
         self.parse_name_value_directive(line, "aux-crate").map(|r| {
             let mut parts = r.trim().splitn(2, '=');
             (
-                parts.next().expect("missing aux-crate name (e.g. log=log.rs)").to_string(),
-                parts.next().expect("missing aux-crate value (e.g. log=log.rs)").to_string(),
+                parts.next().expect("aux-crate name").to_string(),
+                parts.next().expect("aux-crate value").to_string(),
```
Comment (jyn514) [inline src/tools/compiletest/src/header.rs:506]: Please don't revert this.

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by jyn514** [comment]
@rust-lang/rustdoc are you ok with backporting this? For context, this fixes a regression from 1.52 to 1.53 (an ICE on code when generating intra doc links). It does reintroduce the bug from https://github.com/rust-lang/rust/issues/68427, but that's a very narrow edge case I don't expect most people to run into.

**Comment by Manishearth** [comment]
I'm okay with the backport

**Comment by GuillaumeGomez** [comment]
I am as well. I think you can set the label. :)

**Comment by GuillaumeGomez** [comment]
I erroneously pushed on this branch from another PR so I need to re-approve it.

@bors: r=jyn514

**Comment by camelid** [comment]
It looks like #68427 is still closed?
