### PR TITLE
Fix rustdoc scrape examples crash

### LINKED ISSUE #144752: ICE: `only local crates should have sources emitted`
[rustc-ice-2025-07-31T21_03_32-3325.txt](https://github.com/user-attachments/files/21537667/rustc-ice-2025-07-31T21_03_32-3325.txt)

### Code

https://github.com/oold/daemonize/tree/ec717e7b6254d4acabecf8bb37e924b068e18d88

### Meta

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (3048886e5 2025-07-30)
binary: rustc
commit-hash: 3048886e59c94470e726ecaaf2add7242510ac11
commit-date: 2025-07-30
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8
```

### Error output

```
thread 'rustc' panicked at src/librustdoc/html/sources.rs:346:14:
only local crates should have sources emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <&core::fmt::builders::FromFn<rustdoc::html::sources::print_src<&mut core::fmt::Formatter>::{closure#0}> as core::fmt::Display>::fmt
   4: core::fmt::write
   5: <&askama::filters::escape::Safe<&core::fmt::builders::FromFn<rustdoc::html::sources::print_src<&mut core::fmt::Formatter>::{closure#0}>> as core::fmt::Display>::fmt
   6: core::fmt::write
   7: rustdoc::html::render::render_call_locations::<&mut core::fmt::Formatter>::{closure#2}
   8: <core::fmt::builders::FromFn<rustdoc::html::render::document_full_inner::{closure#0}> as core::fmt::Display>::fmt
   9: core::fmt::write
  10: rustdoc::html::render::render_impl::{closure#0}::doc_impl_item::<&mut alloc::string::String, &mut alloc::string::String>
  11: <core::fmt::builders::FromFn<rustdoc::html::render::render_impl::{closure#0}> as core::fmt::Display>::fmt
  12: core::fmt::write
  13: rustdoc::html::render::render_assoc_items_inner
  14: <core::fmt::builders::FromFn<rustdoc::html::render::render_assoc_items::{closure#0}> as core::fmt::Display>::fmt
  15: core::fmt::write
  16: <rustdoc::html::render::print_item::DisplayStruct>::render_into::<core::fmt::Formatter>
  17: <core::fmt::builders::FromFn<rustdoc::html::render::print_item::item_struct::{closure#0}> as core::fmt::Display>::fmt
  18: core::fmt::write
  19: <rustdoc::html::render::context::Context>::render_item
  20: <rustdoc::html::render::context::Context as rustdoc::formats::renderer::FormatRenderer>::item
  21: rustdoc::formats::renderer::run_format_inner::<rustdoc::html::render::context::Context>
  22: rustdoc::formats::renderer::run_format_inner::<rustdoc::html::render::context::Context>
  23: rustc_interface::passes::create_and_enter_global_ctxt::<(), rustdoc::main_args::{closure#2}::{closure#0}>::{closure#2}::{closure#0}
  24: rustc_interface::interface::run_compiler::<(), rustdoc::main_args::{closure#2}>::{closure#1}
```

</p>
</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#144752.

The regression was introduced in https://github.com/rust-lang/rust/pull/144600. Although I don't understand why it is an issue currently, this allows to bypass the failure for now until we can figure out what's wrong as it's currently blocking new `bevy`'s release.

cc @alice-i-cecile 
r? @fmease

### CODE REVIEW

File: tests/run-make/rustdoc-scrape-examples-paths/foo/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,7 @@
+pub struct X;
```
Comment (GuillaumeGomez) [inline tests/run-make/rustdoc-scrape-examples-paths/foo/src/lib.rs:1]: Btw, `tester.rs` must exist, without it, it doesn't crash.

**Review by fmease — APPROVED** [review]
Since I also don't have the time to investigate the root cause, a hotfix seems fine to me.

Regarding the test, I'd rather see a test that doesn't rely on Cargo. Let me see if I can cook sth. up. But otherwise r=me if I don't reply within the next hours.

**Comment by fmease** [comment]
Eh, r=me once CI green

**Comment by alice-i-cecile** [comment]
Thank you! We really appreciate it.
