### PR TITLE
Fix unset e_flags in ELF files generated for AVR targets

### LINKED ISSUE #106576: create_object_file doesn't set correct ELF header flags for AVR targets
(Downstream issue: Rahix/avr-hal#388)

A bug was introduced in #103240 (5642a751ecc76fff232351f5686d49475fb06a09) when compiling for AVR targets, causing errors in linking which look like:

```
error: linking with `avr-gcc` failed: exit status: 1
  |
  = note: "avr-gcc" "-mmcu=attiny404" "/tmp/rustcmivxhx/symbols.o" "/home/goose/dev/hwlife/life-cell/firmware/target/avr-attiny404/debug/deps/life_cell-6668cd99ba2eaeff.avrxmega_hal-cc404b4688795bef.avrxmega_hal.d6125529-cgu.0.rcgu.o.rcgu.o" "-Wl,--as-needed" "-L" "/home/goose/dev/hwlife/life-cell/firmware/target/avr-attiny404/debug/deps" "-L" "/home/goose/dev/hwlife/life-cell/firmware/target/debug/deps" "-L" "/home/goose/build/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/avr-attiny404/lib" "-Wl,-Bstatic" "/home/goose/dev/hwlife/life-cell/firmware/target/avr-attiny404/debug/deps/libcompiler_builtins-dfbc3c77452aecc4.rlib" "-Wl,-Bdynamic" "-lgcc" "-Wl,-znoexecstack" "-L" "/home/goose/build/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/avr-attiny404/lib" "-o" "/home/goose/dev/hwlife/life-cell/firmware/target/avr-attiny404/debug/deps/life_cell-6668cd99ba2eaeff.elf" "-Wl,--gc-sections" "-no-pie"
  = note: /usr/lib/arduino/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: avr architecture of input file `/tmp/rustcmivxhx/symbols.o' is incompatible with avr:103 output
          collect2: error: ld returned 1 exit status
```

The PR in question added support for AVR architecture in `create_object_file`, but it doesn't actually make the necessary changes to set the `e_flags` field, which is used to specify the AVR ISA revision. As a knock-on-effect, this causes [`add_linked_symbol_object`](https://github.com/BelovDV/rustc/blob/5642a751ecc76fff232351f5686d49475fb06a09/compiler/rustc_codegen_ssa/src/back/link.rs#L1729-L1741) to avoid an early return and succeed in creating a `symbols.o` file, but this object file doesn't have `e_flags` set correctly.

I believe that is the cause of this error; the AVR linker checks the `e_flags` field to make sure the ISA revision matches what is expected, and rustc is not setting that field correctly.

### PR DESCRIPTION
**Pull request by agausmann**
Closes #106576 

~~Sort-of blocked by gimli-rs/object#500~~ (merged)

I'm not sure whether the list of AVR CPU names is okay here. Maybe it could be moved out-of-line to improve the readability of the function.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 1]
```diff
@@ -172,6 +172,330 @@ pub(crate) fn create_object_file(sess: &Session) -> Option<write::Object<'static
             let e_flags = elf::EF_RISCV_RVC | elf::EF_RISCV_FLOAT_ABI_DOUBLE;
             e_flags
         }
+        Architecture::Avr => {
+            // Adapted from llvm-project/llvm/lib/target/AVR/AVRDevices.td
+            match sess.target.options.cpu.as_ref() {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: It looks like we only support atmega328 at the moment. For AVR we pass a hard-coded linker flag (`-mmcu=atmega328` for avr-unknown-gnu-atmega328) containing which AVR variant is used to the linker. I can imagine that it going out of sync with `-Ctarget-cpu` is a really bad idea. Instead it did probably need a separate target spec for each cpu. Especially if you can't mix a standard library compiled for one variant with one compiled for another variant. Maybe this `EF_AVR_MACH_*` constant could be specified to the target spec instead of using a giant match? Or maybe not? By the way, should we forbid `-Ctarget-cpu` for AVR?

Comment (agausmann) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: > It looks like we only support atmega328 at the moment

> Instead it did probably need a separate target spec for each cpu

Only atmega328 is in mainline rustc, but the Rust-AVR community supports many more using [custom target specs](https://github.com/Rahix/avr-hal/tree/main/avr-specs).

> For AVR we pass a hard-coded linker flag 

I am pretty sure that the `-mmcu` flag is not "hardcoded", it should be set based on the `cpu` target option, which is set in our target specs. In my experience, `-mmcu` does get set correctly for other CPUs.

> Maybe this `EF_AVR_MACH_*` constant could be specified to the target spec instead of using a giant match? 

Both AVR-GCC and LLVM accept the CPU name as a single flag (e.g. `-mmcu`) and use that to look up values like  `EF_AVR_MACH_*` internally (e.g. with the `AVRDevices.td` table that I mentioned in the comment).

That being said, being able to specify the ISA revision in the target spec is also a good idea. It would make maintenance in rustc a little easier, as rustc would only have to maintain the list of ISAs and not every CPU ever released.

(CC @Rahix - would it be acceptable to specify the ISA alongside the CPU in the target specs?)

>  should we forbid `-Ctarget-cpu` for AVR?

I do not see a reason for doing that.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: > I do not see a reason for doing that.

Does using say `-Ctarget-cpu=avr1` for one crate and `-Ctarget-cpu=avrtiny` for another crate work? If not, they have to be treated as separate targets without an overlapping set of allowed values for `-Ctarget-cpu`. The way that rustc checks for compatibility is by checking that the target name is identical. It assumes that linking crates with different `-Ctarget-cpu` values works fine and then runs on any cpu implementing the union of whatever features these `-Ctarget-cpu` values imply.

Comment (agausmann) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: For AVR specifically, the main usecase I can think of is picking a common-denominator ISA for building a "portable" library. I don't know whether that's actually useful or not. Probably not, since we currently specify each AVR CPU as its own target anyway.

And sure, if you misuse that, you may end up with a broken executable that doesn't work on your platform. That's true for any target. 

However, I don't think it would be productive to add more code to forbid it. It's not like it's a "footgun" that a developer would regularly encounter and accidentally set incorrectly without realizing.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: I was worried about say AVR2 cpu's not being able to run AVR1 code. That AVR1 cpu's can't run AVR2 code is obvious.

> It's not like it's a "footgun" that a developer would regularly encounter and accidentally set incorrectly without realizing.

You might not realize that the standard library is compiled for an incompatible cpu even if you set `-Ctarget-cpu` for your own crates.

In any case I guess it is fine to leave it as is.

Comment (Rahix) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:177]: > (CC @Rahix - would it be acceptable to specify the ISA alongside the CPU in the target specs?)

I certainly wouldn't mind at all.  However both gcc and llvm also seem to maintain the list of MCUs so I think it is just as reasonable to do the same in rustc.

File: Cargo.toml [hunk 2]
```diff
@@ -115,5 +115,7 @@ rustc-std-workspace-core = { path = 'library/rustc-std-workspace-core' }
 rustc-std-workspace-alloc = { path = 'library/rustc-std-workspace-alloc' }
 rustc-std-workspace-std = { path = 'library/rustc-std-workspace-std' }
 
+object = { git = "https://github.com/agausmann/object.git", branch = "0.29.0-avr-flags" }
```
Comment (Rahix) [inline Cargo.toml:118]: Seems your changes were released as `object` version [0.30.2](https://github.com/gimli-rs/object/blob/master/CHANGELOG.md#0302).

**Comment by agausmann** [comment]
> Maybe it could be moved out-of-line to improve the readability of the function.

Ultimately it's up to the reviewer, but personally I think it's a good idea to make this separate function. Maybe it would make sense to put it somewhere in `rustc_target`.

**Comment by petrochenkov** [comment]
>Maybe it would make sense to put it somewhere in `rustc_target`.

Yeah, that would make sense.
To `compiler\rustc_target\src\spec\avr_gnu_base.rs` specifically (with a reexport from some externally visible place).

**Comment by agausmann** [comment]
@petrochenkov I considered `rustc_target` but this mapping uses constants from the `object` crate, so `rustc_target` would also have to depend on `object`.

**Comment by workingjubilee** [comment]
Is that actually a problem? It has several external dependencies already.

**Comment by wesleywiser** [comment]
r? rust-lang/compiler

**Comment by agausmann** [comment]
> Is that actually a problem?
Probably not, just could shift the dependency graph slightly. I figured dependency changes were worth pointing out.

**Comment by workingjubilee** [comment]
`object` is already depended-on by `cg_clif` and `cg_llvm` so while it will move the dependence up the chain, to `rustc_target`, that crate should already have been built in-parallel in order to make it available to the codegen backend.

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 3]
```diff
@@ -190,6 +190,330 @@ pub(crate) fn create_object_file(sess: &Session) -> Option<write::Object<'static
...
+                "attiny1627" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega808" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega809" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega1608" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega1609" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega3208" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega3209" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega4808" => elf::EF_AVR_ARCH_XMEGA3,
+                "atmega4809" => elf::EF_AVR_ARCH_XMEGA3,
+                _ => 0,
```
Comment (nagisa) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:514]: Is this a reasonable fall-back value for an unknown CPU? That is, will the tooling continue working with the objects if this field stays zero?

If not, there are two alternatives to consider here – a compiler error or falling back to a common denominator that is (almost?) guaranteed to work whatever the CPU is specified.

**Comment by nagisa** [comment]
I think adding a `rustc_target ← object` dependency edge makes a fair bit of sense: object is a pretty lean crate and it does provide some very target-specific connstants that other targets might want to use but wouldn’t if the dependency wasn't already available.

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 3 above)
Comment (agausmann) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:514]: > Is this a reasonable fall-back value for an unknown CPU?

I believe zero is the value used for "generic" or "unspecified" in this case. It's also the value that `e_flags` has on AVR without this patch.

For example, in the error message in #106576 (``avr architecture of input file `/tmp/rustcmivxhx/symbols.o' is incompatible with avr:103 output``) , the `103` is the expected `e_flags` value. If the value is zero, then the linker just prints `avr`, like at the beginning of the error message, implying that it's "generic" AVR.

Another example of the same error, but different values: ``avr:51 architecture of input file `main.o' is incompatible with avr output`` ([source](https://stackoverflow.com/questions/51505057/avr-ld-avr51-architecture-of-input-file-main-o-is-incompatible-with-avr-outp))

**Comment by agausmann** [comment]
It's not clear where it should go in `rustc_target`. The `spec::avr_gnu_base` module is not public, so that would either have to change or it would have to be reexported publicly if it is in there.

**Comment by Dylan-DPC** [comment]
@agausmann any updates?

**Comment by agausmann** [comment]
Sorry for the delay, I'm not great at keeping track of my todos at home...

**Comment by agausmann** [comment]
Ah ok, thanks for the help @apiraino

**Comment by nagisa** [comment]
I haven’t reviewed the list of MCU-specific options too carefully, but the rest seems good to me.

@bors r+

**Comment by workingjubilee** [comment]
another instance of https://github.com/rust-lang/rust/issues/113065

@bors retry
