### PR TITLE
extend NLL checker to understand `'empty` combined with universes

### LINKED ISSUE #68550: Rustc bug:cannot convert `ReEmpty` to a region vid
When compiling my code, I saw cargo/rustc panicked.

I tried this code:

```
pub struct Data<A> {
    pub a: A,
}

impl<A> Data<A>
where
    A: 'static,
    &'static A: ,
{
    pub fn run() {
        let mut entries: Vec<A> = Vec::new();
        if !entries.is_empty() {}
    }
}

pub type DataA = Data<i32>;

fn main() {
    println!("Hello, world!");
}
```

The output is

```
 $ cargo build
   Compiling rustc-crash v0.1.0 (/Users/zhangzhuo/repos/personal/rustc-crash)
error: internal compiler error: src/librustc_mir/borrow_check/universal_regions.rs:729: cannot convert `ReEmpty` to a region vid

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:883:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (6d3f4e0aa 2020-01-25) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `rustc-crash`.

To learn more, run the command again with --verbose.
```

## Meta

`rustc --version --verbose`:

```
rustc 1.42.0-nightly (6d3f4e0aa 2020-01-25)
binary: rustc
commit-hash: 6d3f4e0aab3e36ceb8b83d1e9467514685f6b751
commit-date: 2020-01-25
host: x86_64-apple-darwin
release: 1.42.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
This PR extends the NLL region checker to understand `'empty` combined with universes. In particular, it means that the NLL region checker no longer considers `exists<R2> { forall<R1> { R1: R2 } }` to be provable. This is work towards https://github.com/rust-lang/rust/issues/59490, but we're not all the way there. One thing in particular it does not address is error messages.

The modifications to the NLL region inference code turned out to be simpler than expected. The main change is to require that if `R1: R2` then `universe(R1) <= universe(R2)`. 

This constraint follows from the region lattice (shown below), because we assume then that `R2` is "at least" `empty(Universe(R2))`, and hence if `R1: R2` (i.e., `R1 >= R2` on the lattice) then `R1` must be in some universe that can name `'empty(Universe(R2))`, which requires that `Universe(R1) <= Universe(R2)`.

```
static ----------+-----...------+       (greatest)
|                |              |
early-bound and  |              |
free regions     |              |
|                |              |
scope regions    |              |
|                |              |
empty(root)   placeholder(U1)   |
|            /                  |
|           /         placeholder(Un)
empty(U1) --         /
|                   /
...                /
|                 /
empty(Un) --------                      (smallest)
```

I also made what turned out to be a somewhat unrelated change to add a special region to represent `'empty(U0)`, which we use (somewhat hackily) to indicate well-formedness checks in some parts of the compiler. This fixes #68550.

I did some investigation into fixing the error message situation. That's a bit trickier: the existing "nice region error" code around placeholders relies on having better error tracing than NLL currently provides, so that it knows (e.g.) that the constraint arose from applying a trait impl and things like that. I feel like I was hoping *not* to do such fine-grained tracing in NLL, and it seems like we...largely...got away with that. I'm not sure yet if we'll have to add more tracing information or if there is some sort of alternative.

It's worth pointing out though that I've not kind of shifted my opinion on whose job it should be to enforce lifetimes: I tend to think we ought to be moving back towards *something like* the leak-check (just not the one we *had*). If we took that approach, it would actually resolve this aspect of the error message problem, because we would be resolving 'higher-ranked errors' in the trait solver itself, and hence we wouldn't have to thread as much causal information back to the region checker. I think it would also help us with removing the leak check while not breaking some of the existing crates out there.

Regardless, I think it's worth landing this change, because it was relatively simple and it aligns the set of programs that NLL accepts with those that are accepted by the main region checker, and hence should at least *help* us in migration (though I guess we still also have to resolve the existing crates that rely on leak check for coherence).

r? @matthewjasper

### CODE REVIEW

File: src/librustc_mir/borrow_check/region_infer/mod.rs [hunk 1]
```diff
@@ -321,10 +321,75 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+        // ```
+        //
+        // Here, we wish for R1 to be `'static`, because it
+        // cannot outlive `placeholder(U1)` and `empty(U0)` any other way.
+        //
+        // Thanks to this loop, what happens is that the `R1: R0`
+        // constraint lowers the universe of `R1` to `U0`, which in turn
+        // means that the `R1: !1` constraint will (later) cause
+        // `R1` to become `'static`.
+        for scc_a in constraints_scc.all_sccs() {
```
Comment (matthewjasper) [inline src/librustc_mir/borrow_check/region_infer/mod.rs:375]: Why isn't this iterating to a fixed point?

File: src/test/ui/nll/type-check-pointer-comparisons.rs [hunk 2]
```diff
@@ -21,13 +21,13 @@ fn compare_fn_ptr<'a, 'b, 'c>(f: fn(&'c mut &'a i32), g: fn(&'c mut &'b i32)) {
 }
 
 fn compare_hr_fn_ptr<'a>(f: fn(&'a i32), g: fn(&i32)) {
-    // Ideally this should compile with the operands swapped as well, but HIR
-    // type checking prevents it (and stops compilation) for now.
-    f == g; // OK
+    f == g;
+    //~^ ERROR higher-ranked subtype error
```
Comment (matthewjasper) [inline src/test/ui/nll/type-check-pointer-comparisons.rs:25]: Hmm, I guess the code here isn't doing what I thought it was
https://github.com/rust-lang/rust/blob/96d77f0e5f103612d62b85938aacfb33f5768433/src/librustc_mir/borrow_check/type_check/mod.rs#L2302-L2333

I think I was expecting this to implicitly do `self.infcx.resolve_vars_if_possible(common_ty)` in the second `sub_types` call.

File: src/librustc_mir/borrow_check/region_infer/mod.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:375]: Heh, good catch.

File: src/test/ui/nll/type-check-pointer-comparisons.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: I don't think that would have any effect. What happens in the first call is that we instantiate `common_ty` to a version of `ty_left`, but with distinct region variables (which are related to the regions in `ty_left`). It sounds like you were expecting `common_ty` and `ty_left` to get unified?

File: src/librustc_mir/borrow_check/region_infer/mod.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:375]: I'll have to whip up a test for that.

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:375]: Wait -- iteration isn't necessary, SCCs are acyclic, but we do have to do it 'bottom up'.

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:375]: So...I'm not sure how to make a test for this yet. =) I can fix the bug readily enough though. Maybe I'll just do that.

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs]: I opted to just fix the bug.

File: src/librustc_mir/borrow_check/region_infer/mod.rs [hunk 3]
```diff
@@ -67,6 +67,12 @@ pub struct RegionInferenceContext<'tcx> {
     /// compute the values of each region.
     constraint_sccs: Rc<Sccs<RegionVid, ConstraintSccIndex>>,
 
+    /// SCCs in "dependency order" (or "post order"), meaning that if S1 -> S2,
+    /// then S2 appears first. If you process the SCCs in this order, then you
+    /// are always ensured that when you proces a given SCC, all of its
```
Comment (lqd) [inline src/librustc_mir/borrow_check/region_infer/mod.rs:72]:
```suggestion
    /// are always ensured that when you process a given SCC, all of its
```

Comment (lqd) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:72]: (I haven't read this module in a while, or this PR in detail, so take this with a grain of salt -- it seems likely a lot of this commit could be simplified: Tarjan's algorithm already discovers SCCs in postorder, and it looks like you could compute a lot of the data, a TC of the SCC values, computing the representatives, while you do the single walk)

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:72]: Hmm, that's probably true.

Comment (lqd) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:72]: IIRC some of Nuutila's works describe straightforward Tarjan modifications to handle similar problems.

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:72]: I'm not inclined to do the larger potential refactorings here, but I can check whether we can trivially ensure that the `all_sccs` is always in dependency order or something like that.

**Comment by nikomatsakis** [comment]
I don't understand these mir-opt failures though -- I have run `./x.py test --bless`, and things pass locally, I guess maybe the output is inconsistent between platforms? cc @oli-obk, are there any known gotchas with the mir-opt tests here?

**Comment by oli-obk** [comment]
Since the CI failure is on 64 bit and I'm assuming you're on 64 bit, too, platform differences can't be the cause of it I think. We have a flag (https://github.com/rust-lang/rust/tree/master/src/test/mir-opt#--blessable-test-format) to emit one file per bit size, but you need to run with `--target=i686-unknown-linux-gnu` to generate the 32 bit variant in that case.

I can't tell with the inference variables, but the rest of the failures look like you added two lines at the top of the file and didn't rerun --bless.

File: src/test/mir-opt/nll/region-subtyping-basic.rs [hunk 4]
```diff
@@ -7,7 +7,9 @@
 
 #![allow(warnings)]
 
-fn use_x(_: usize) -> bool { true }
+fn use_x(_: usize) -> bool {
```
Comment (oli-obk) [inline src/test/mir-opt/nll/region-subtyping-basic.rs:10]: Maybe rustfmt ran after --bless?

Comment (oli-obk) [reply src/test/mir-opt/nll/region-subtyping-basic.rs:10]: hmm no, the mir dump below has this change in it

Comment (oli-obk) [reply src/test/mir-opt/nll/region-subtyping-basic.rs:10]: Ah I did misread the log

> [mir-opt] mir-opt/nll/region-subtyping-basic.rs' panicked at
> 'Actual MIR output differs from expected MIR output
> /checkout/src/test/mir-opt/nll/region-subtyping-basic/**32bit**/rustc.main.nll.0.mir'

it's indeed just 32 bit not having gotten updated

File: src/librustc_mir/borrow_check/region_infer/mod.rs (hunk 3 above)
Comment (lqd) [reply src/librustc_mir/borrow_check/region_infer/mod.rs:72]: Ok then I'll try to apply this idea here in the future

**Comment by nikomatsakis** [comment]
@oli-obk huh. But I did re-run bless.. ok, I'll investigate, thanks!

**Comment by nikomatsakis** [comment]
I wonder if it's just outdated stamp files...

**Comment by oli-obk** [comment]
Sorry, I hid the comment. You need to run once with `--target=i686-unknown-linux-gnu` and once without to get 32bit and 64bit mir dumps updated

File: src/test/ui/nll/type-check-pointer-comparisons.rs (hunk 2 above)
Comment (matthewjasper) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: No, I was expecting `common_ty` to be a generalized version of `ty_left`. I was then expecting the next call to relate the same generalized type to `ty_right`, but it is instead equating `common_ty` to a generalized version of `ty_right`.

In this specific case I was expecting `common_ty` to be instantiated as `fn(&'? i32)` and then be constrained to be a supertype of `fn(&'a i32)` and `fn(&i32)`. Instead it's instantiated as both `fn(&'? i32)` and `fn(&i32)`, which is an error.

**Comment by nikomatsakis** [comment]
So, I re-read our algorithm for SCCs, and I think @lqd is right that the `all_sccs` list is *already* in dependency order. I haven't thought much about it yet but it seems "probably true". So I might simplify that commit.

In terms of the reference files, I can't run the 32-bit tests locally yet, I get some weird errors, I am probably missing packages on my machine.

**Comment by nikomatsakis** [comment]
OK, I think I fixed the mir-opt test, and we now document (and take advantage) of the fact that `all_sccs` is already in dependency order (thanks @lqd).

File: src/test/ui/nll/type-check-pointer-comparisons.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: I can't tell if you're suggesting a change here or not =)

Comment (nikomatsakis) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: That said, I think I was expecting the same as you. Also, re-reading the code, I'm a bit.. surprised by it. It seems like there's a baked-in assumption about the sort of types that we'll apply the comparison operator to that probably ought to be checked (i.e., it seems like we're assuming that in all other cases, the values are trivially of the same type, I guess?).

Still, I'm not entirely sure how you are deriving your conclusions. I think I expected:

* `common_ty` gets instantiated to `fn(&'? i32)` (where `'a: '?`, unless I got something backward)
* we then require that `fn(&'? i32) <: fn(&i32)`, which yields a requirement that `for<'b> { 'b: '? }`, which we cannot satisfy (though, prior to this PR, we could)
* hence we get a higher-ranked error

In particular I don't really know what this means:

> Instead it's instantiated as both `fn(&'? i32)` and `fn(&i32)`, which is an error.

How can a single variable be instantiated as two types? Maybe we mean something different by 'instantiated'.

Comment (matthewjasper) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: Looking at the code again, I was wrong what the problem was. The types are being related the opposite way to they actually should be.

`common_ty` is the type that the comparison is being done at, so each of the operand should be a subtype of `common_ty`, that is `common_ty` should be a common *super*-type.

> It seems like there's a baked-in assumption about the sort of types that we'll apply the comparison operator to that probably ought to be checked (i.e., it seems like we're assuming that in all other cases, the values are trivially of the same type, I guess?).

Yes, this should probably be changed to match the remaining types where `BinOp::Eq` is allowed (ints, `bool`, `char`) and assert equality I guess this can be done separately.

Comment (nikomatsakis) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: @matthewjasper good point, I suppose we do want a common super-type, not a common sub-type! I'll push a commit making this change.

Comment (nikomatsakis) [reply src/test/ui/nll/type-check-pointer-comparisons.rs:25]: Update: it wasn't easy to change the order. This is because, I think, the `relate_tys` code still has some hard-coded assumptions that assume that the super-type is not an uninstantiated variable, or something like that. This may have been what led to the code being written this way in the first place.

**Comment by nikomatsakis** [comment]
@matthewjasper do you consider [this] a blocker? It seems kind of orthogonal from this PR to me.

[this]: https://github.com/rust-lang/rust/pull/70950#discussion_r406714796

**Comment by matthewjasper** [comment]
No, I'll try to fix it once this is merged.

@bors r+
