### PR TITLE
Fix ICE when applying test macro to crate root

### LINKED ISSUE #114920: ICE: `expected exactly one crate`
### Code

```Rust
#![core::prelude::v1::test]
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (0bdb00d55 2023-08-15)
binary: rustc
commit-hash: 0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 17.0.0
```

### Error output

```
error[E0658]: inner macro attributes are unstable
 --> 3FE4FE381370D3FE64AB5BA2621063FA00B3CE0B50A85AD17479D849AF1FCEF4.rs:1:4
  |
1 | #![core::prelude::v1::test]
  |    ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_expand/src/expand.rs:314:49:
expected exactly one crate
stack backtrace:
   0:     0x7fa6f77634dc - std::backtrace_rs::backtrace::libunwind::trace::h1a52aadab1e423ed
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fa6f77634dc - std::backtrace_rs::backtrace::trace_unsynchronized::h6ba22d133698223c
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa6f77634dc - std::sys_common::backtrace::_print_fmt::h109a934708356281
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fa6f77634dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h616cb33c77b3507c
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fa6f77c962c - core::fmt::rt::Argument::fmt::hc5b672822529f326
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/fmt/rt.rs:138:9
   5:     0x7fa6f77c962c - core::fmt::write::h65d66d3303e2b93b
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fa6f7755f6e - std::io::Write::write_fmt::h6c1f4b97f011d41f
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/io/mod.rs:1714:15
   7:     0x7fa6f77632c4 - std::sys_common::backtrace::_print::h8e31077e74457cbb
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fa6f77632c4 - std::sys_common::backtrace::print::hb32da5910a86799a
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fa6f77663ba - std::panicking::panic_hook_with_disk_dump::{{closure}}::h4239609dadb6dd4b
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/panicking.rs:278:22
  10:     0x7fa6f77660a7 - std::panicking::panic_hook_with_disk_dump::he7a9f97382268d96
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/panicking.rs:312:9
  11:     0x7fa6fa96bf59 - rustc_driver_impl[65938c695a923997]::install_ice_hook::{closure#0}
  12:     0x7fa6f7766c60 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf0c2c27361744f38
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/alloc/src/boxed.rs:2021:9
  13:     0x7fa6f7766c60 - std::panicking::rust_panic_with_hook::hb07817b642426395
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/panicking.rs:733:13
  14:     0x7fa6f77669e7 - std::panicking::begin_panic_handler::{{closure}}::h488a977f6d0b9662
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/panicking.rs:621:13
  15:     0x7fa6f7763a06 - std::sys_common::backtrace::__rust_end_short_backtrace::h795eed542b7fd71a
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fa6f7766732 - rust_begin_unwind
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/panicking.rs:617:5
  17:     0x7fa6f77c5a33 - core::panicking::panic_fmt::h6cea401c88668a39
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/panicking.rs:67:14
  18:     0x7fa6f77c578a - core::panicking::panic_display::h6d1f308294ef9349
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/panicking.rs:150:5
  19:     0x7fa6f77c578a - core::panicking::panic_str::h149afc02926435d9
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/panicking.rs:134:5
  20:     0x7fa6f77c578a - core::option::expect_failed::hb346f79aa4c2fdad
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/core/src/option.rs:1988:5
  21:     0x7fa6f9464f45 - <rustc_expand[a0c8bf28632e4702]::expand::AstFragmentKind>::expect_from_annotatables::<alloc[6066a680f2915695]::vec::Vec<rustc_expand[a0c8bf28632e4702]::base::Annotatable>>
  22:     0x7fa6f9449133 - <rustc_expand[a0c8bf28632e4702]::expand::MacroExpander>::fully_expand_fragment
  23:     0x7fa6f9aadc07 - <rustc_expand[a0c8bf28632e4702]::expand::MacroExpander>::expand_crate
  24:     0x7fa6f9aaceed - <rustc_session[584b13b7c15f5880]::session::Session>::time::<rustc_ast[7e47edba6e8f4f49]::ast::Crate, rustc_interface[9c67ccc1e80e5966]::passes::configure_and_expand::{closure#1}>
  25:     0x7fa6f9aa2851 - rustc_interface[9c67ccc1e80e5966]::passes::resolver_for_lowering
  26:     0x7fa6f9e7e3aa - rustc_query_impl[e7344d331a0cd74e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e7344d331a0cd74e]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e44605746681820e]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7fa6f9e7e399 - <rustc_query_impl[e7344d331a0cd74e]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[ac9b6779de401ae6]::ops::function::FnOnce<(rustc_middle[e44605746681820e]::ty::context::TyCtxt, ())>>::call_once
  28:     0x7fa6f9def3fc - rustc_query_system[f713a07e914ef80b]::query::plumbing::try_execute_query::<rustc_query_impl[e7344d331a0cd74e]::DynamicConfig<rustc_query_system[f713a07e914ef80b]::query::caches::SingleCache<rustc_middle[e44605746681820e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e7344d331a0cd74e]::plumbing::QueryCtxt, false>
  29:     0x7fa6fa2c3955 - rustc_query_impl[e7344d331a0cd74e]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7fa6f9c55825 - <rustc_middle[e44605746681820e]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[65938c695a923997]::run_compiler::{closure#1}::{closure#2}::{closure#4}, &rustc_data_structures[6b3501c1aa0d2423]::steal::Steal<(rustc_middle[e44605746681820e]::ty::ResolverAstLowering, alloc[6066a680f2915695]::rc::Rc<rustc_ast[7e47edba6e8f4f49]::ast::Crate>)>>
  31:     0x7fa6f9c54a44 - <rustc_interface[9c67ccc1e80e5966]::interface::Compiler>::enter::<rustc_driver_impl[65938c695a923997]::run_compiler::{closure#1}::{closure#2}, core[ac9b6779de401ae6]::result::Result<core[ac9b6779de401ae6]::option::Option<rustc_interface[9c67ccc1e80e5966]::queries::Linker>, rustc_span[96ddbb965edded7c]::ErrorGuaranteed>>
  32:     0x7fa6f9c51e28 - std[2290b8cd92984895]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9c67ccc1e80e5966]::util::run_in_thread_pool_with_globals<rustc_interface[9c67ccc1e80e5966]::interface::run_compiler<core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>, rustc_driver_impl[65938c695a923997]::run_compiler::{closure#1}>::{closure#0}, core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>>
  33:     0x7fa6fa1d7ae5 - <<std[2290b8cd92984895]::thread::Builder>::spawn_unchecked_<rustc_interface[9c67ccc1e80e5966]::util::run_in_thread_pool_with_globals<rustc_interface[9c67ccc1e80e5966]::interface::run_compiler<core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>, rustc_driver_impl[65938c695a923997]::run_compiler::{closure#1}>::{closure#0}, core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ac9b6779de401ae6]::result::Result<(), rustc_span[96ddbb965edded7c]::ErrorGuaranteed>>::{closure#1} as core[ac9b6779de401ae6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7fa6f7771455 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4cced11e3b719b0a
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/alloc/src/boxed.rs:2007:9
  35:     0x7fa6f7771455 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc891d0d7ae02d2bf
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/alloc/src/boxed.rs:2007:9
  36:     0x7fa6f7771455 - std::sys::unix::thread::Thread::new::thread_start::h868c01f62b62c119
                               at /rustc/0bdb00d55aa7d6aebe5a01bc6d3c5bf474a853ab/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7fa6f748c9eb - <unknown>
  38:     0x7fa6f7510ebc - <unknown>
  39:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/tmp/GGGGG/rustc-ice-2023-08-17T04:05:14.583689148Z-3820690.txt` to your bug report

note: compiler flags: --crate-type lib

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jdonszelmann**
This PR does a couple of things. First of all, I found [an ICE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=a733a7f3d223e1a9712e44b571f3e5cf) that happens when applying `#![core::prelude::v1::test]` to the crate root. This is caused by the test macro not expanding to an item when `--test` isn't applied. For the crate root, that means it deletes the crate....

The fix now first does target checking, and only if the target is valid discards the item when `--test` isn't applied. The discarding is, I think, important for perf. 

The problem with this PR is that it means that `#[test]` applied to structs previously would give no errors unless `--test` is applied! That sounds like a bug to me, but maybe we should crater run it just in case, since technically that's a breaking change. Errors in such items wouldn't be reported previously.

 Also fixed a smol diagnostics bug with `#[bench]`'s error messages refering to `#[test]` accidentally.

r? noratrieb (since I already explained you a bunch, feel free to re-assign)

Fixes https://github.com/rust-lang/rust/issues/114920

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/test.rs [hunk 1]
```diff
@@ -426,12 +427,16 @@ fn not_testable_error(cx: &ExtCtxt<'_>, attr_sp: Span, item: Option<&ast::Item>)
             ),
         );
     }
-    err.with_span_label(attr_sp, "the `#[test]` macro causes a function to be run as a test and has no effect on non-functions")
-        .with_span_suggestion(attr_sp,
+    err.span_label(attr_sp, format!("the `#[{name}]` macro causes a function to be run as a test and has no effect on non-functions"));
+
+    if !is_bench {
+        err.with_span_suggestion(attr_sp,
             "replace with conditional compilation to make the item only exist when tests are being run",
```
Comment (jdonszelmann) [inline compiler/rustc_builtin_macros/src/test.rs:434]: only give the suggestion of `cfg(test)` when we're dealing with test attrs

File: tests/ui/feature-gates/gating-of-test-attrs.rs [hunk 2]
```diff
@@ -0,0 +1,48 @@
+#![feature(test)]
+
+// test is a built-in macro, not a built-in attribute, but it kind of acts like both.
```
Comment (jdonszelmann) [inline tests/ui/feature-gates/gating-of-test-attrs.rs:3]: New test for test attributes. The previous tests simply asserted no errors would be given but that's not true anymore, and I think they should error!

File: tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs [hunk 3]
```diff
@@ -250,38 +250,6 @@ mod macro_export {
     //~| HELP remove the attribute
 }
 
-// At time of unit test authorship, if compiling without `--test` then
-// non-crate-level #[test] attributes seem to be ignored.
-
-#[test]
-mod test { mod inner { #![test] }
```
Comment (jdonszelmann) [inline tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs:257]: these were weird here anyway, `test` isn't a built-in attribute but a built-in macro!

File: tests/ui/macros/issue-111749.rs [hunk 4]
```diff
@@ -5,8 +5,8 @@ macro_rules! cbor_map {
 }
 
 fn main() {
-    cbor_map! { #[test(test)] 4};
-    //~^ ERROR removing an expression is not supported in this position
+    cbor_map! { #[test(test)] 4i32};
```
Comment (jdonszelmann) [inline tests/ui/macros/issue-111749.rs:8]: changed to an i32 cause signum wouldn't be valid on just `4`

File: tests/ui/macros/issue-111749.rs [hunk 5]
```diff
@@ -5,8 +5,8 @@ macro_rules! cbor_map {
...
+    //~^ ERROR the `#[test]` attribute may only be used on a non-associated function
```
Comment (jdonszelmann) [inline tests/ui/macros/issue-111749.rs]: I think this is the correct error here, not something about removing expressions. I think noting that the target is wrong is more important.

File: tests/ui/macros/test-on-crate-root.rs [hunk 6]
```diff
@@ -0,0 +1,8 @@
+// ICE when applying `#![test]` to the crate root,
+// though only when specified with a full path. `#![test]` is not enough.
+#![core::prelude::v1::test]
```
Comment (jdonszelmann) [inline tests/ui/macros/test-on-crate-root.rs:5]: tests the specific ICE from the PR description

File: tests/ui/macros/attr-empty-expr.stderr [hunk 7]
```diff
@@ -1,20 +0,0 @@
-error: removing an expression is not supported in this position
-  --> $DIR/attr-empty-expr.rs:8:13
-   |
-LL |     let _ = #[test] 0;
-   |             ^^^^^^^
-
-error: removing an expression is not supported in this position
```
Comment (jdonszelmann) [inline tests/ui/macros/attr-empty-expr.stderr:7]: this test was testing for "empty expressions". this is super niche, can only happen with ast-based attributes (only like 10 in the compiler) and none of the examples in this test should actually remove the expression, they should instead report that the target is wrong. I can't find any other examples of node-removing attributes so I think this test is simply superfluous now.

**Comment by jdonszelmann** [comment]
@bors try
@craterbot check

**Comment by jdonszelmann** [comment]
yea, that's actually exactly what it fixes. there was a crashtest for it I just notice but the fix is rather trivial in the end

**Comment by jdonszelmann** [comment]
@craterbot check

**Comment by jdonszelmann** [comment]
I'd say this isn't very significant

File: tests/ui/feature-gates/gating-of-test-attrs.rs [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+// check its target checking anyway here
+#[test]
+//~^ ERROR the `#[test]` attribute may only be used on a non-associated function
```
Comment (tmandry) [inline tests/ui/feature-gates/gating-of-test-attrs.rs]: This is inconsistent with the terminology we use in the reference and elsewhere.

```suggestion
//~^ ERROR the `#[test]` attribute may only be used on a free function
```

**Comment by traviscross** [comment]
Sounds right.  Thanks @jdonszelmann, @Noratrieb.

This brings us closer in line with what the Reference says in:

https://doc.rust-lang.org/1.90.0/reference/attributes/testing.html#r-attributes.testing.test.allowed-positions

@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: tests/ui/feature-gates/gating-of-test-attrs.rs (hunk 8 above)
Comment (jdonszelmann) [reply tests/ui/feature-gates/gating-of-test-attrs.rs]: I'm not sure I like that convention, but I do agree with wanting it to be consistent. Changed it :)

File: compiler/rustc_builtin_macros/src/test.rs
Comment (WaffleLapkin) [inline compiler/rustc_builtin_macros/src/test.rs:46]: drive-by: this could be simplified:
```suggestion
        Annotatable::Stmt(stmt) if let ast::StmtKind::Item(i) = stmt.kind => {
            (i, true)
        }
```

File: tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs
Comment (WaffleLapkin) [inline tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs]: This is probably not required anymore?

File: tests/ui/macros/test-on-crate-root.rs [hunk 9]
```diff
@@ -0,0 +1,9 @@
+// ICE when applying `#![test]` to the crate root,
+// though only when specified with a full path. `#![test]` is not enough.
+// Fixes #114920
```
Comment (WaffleLapkin) [inline tests/ui/macros/test-on-crate-root.rs]: A test doesn't really _fix_ anything itself...

```suggestion
// Regression test for <https://github.com/rust-lang/rust/issues/114920>
//
// Applying `#![test]` to the crate root used to ICE when referring to the attribute with full path specifically).
```

File: tests/ui/macros/test-on-crate-root.rs [hunk 10]
```diff
@@ -0,0 +1,9 @@
...
+#![core::prelude::v1::test]
+//~^ ERROR inner macro attributes are unstable
+//~| ERROR the `#[test]` attribute may only be used on a free function
+
+
+fn main() {} // not important to reproduce the issue
```
Comment (WaffleLapkin) [inline tests/ui/macros/test-on-crate-root.rs]:
```suggestion
fn main() {}
```

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]
nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147841/568b11762723b001bfa693d0f21c5dad01d4e813..1938841af6af299fc5d07142592434994ffa7f09)*

File: tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs
Comment (WaffleLapkin) [reply tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.rs]: ugh, github doesn't show the line :|

I was referring to `#![feature(test)]`

File: compiler/rustc_builtin_macros/src/test.rs
Comment (WaffleLapkin) [reply compiler/rustc_builtin_macros/src/test.rs:46]: (this doesn't work because you can't move out in an if let guard 😭 )

**Review by WaffleLapkin — APPROVED** [review]

**Comment by Kobzol** [comment]
@rust-timer build 9b9e0731889cba19bb3a7f778c12e6772cb6721a
