### PR TITLE
Put back zeroing; issues 29092, 30018, 30530, 30822

### LINKED ISSUE #29092: Segfault in a compiler-generated Drop impl
I've tried reducing this code in various ways, and unfortunately the original seems to already be the smallest that fails! Removing variants from `Term` causes it to not exhibit itself, as does removing cases from the outer `match` in `small_eval`. It reproduces on latest nightly *only* if debuginfo=2, but on older nightlies (@aatch reports a repro on 2015-09-22) or 1.3.0 it repros for debuginfo=1. On all versions, doing optimizations causes the issue to disappear.

```rust
use self::Term::*;

#[derive(Clone)]
pub enum Term {
    True,
    False,
    If(Box<Term>, Box<Term>, Box<Term>),
    Succ(Box<Term>),
    Pred(Box<Term>),
    IsZero(Box<Term>),
}

fn isnumeric(v: &Term) -> bool {
    match *v {
        Pred(ref f) | Succ(ref f) => isnumeric(f),
        _ => false
    }
}

// a small-step evaluator
pub fn small_eval(v: &Term) -> Term {
    match *v {
        If(ref con, ref the, ref els) => match **con {
            True => *the.clone(),
            False => *els.clone(),
            _ => If(Box::new(small_eval(con)), the.clone(), els.clone()),
        },
        Succ(ref s) => Succ(Box::new(small_eval(s))),
        Pred(ref s) => match **s {
            Succ(ref v) if isnumeric(v) => {
                *v.clone()
            },
            _ => Pred(Box::new(small_eval(s))),
        },
        IsZero(ref s) => match **s {
            Succ(ref s) if isnumeric(s) => False,
            _ => IsZero(Box::new(small_eval(s))),
        },
        _ => v.clone()
    }
}

fn main() {
    let t = If(Box::new(True), Box::new(True), Box::new(True));
    small_eval(&t);
}
```

I suspect that an alloca (forced by debuginfo) is getting trampled somewhere.

GDB backtrace (from rustc 1.5.0-nightly (eafe106ef 2015-10-15)):

```
(gdb) run
Starting program: /tmp/foo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555558b14 in Term::drop.3510::ha59bcdf39bbe7497 ()
(gdb) where
#0  0x0000555555558b14 in Term::drop.3510::ha59bcdf39bbe7497 ()
#1  0x0000555555558af2 in Box$LT$Term$GT$::drop.3508::h48a2557aadc5bcd2 ()
#2  0x00005555555592c1 in foo::small_eval (v=0x7fffffffdb08) at foo.rs:25
#3  0x0000555555559a06 in foo::main () at foo.rs:49
#4  0x000055555555f525 in sys_common::unwind::try::try_fn::h16668888951888304395 ()
#5  0x000055555555d1b9 in __rust_try ()
#6  0x000055555555f1c0 in rt::lang_start::ha93496369c7c61cfF5w ()
#7  0x0000555555559b1a in main ()
```

### LINKED ISSUE #30018: SIGTRAP in drop glue when slice literal initialization panics
```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {}
}

fn foo() -> Foo {
    panic!();
}

fn main() {
    let _ = &[foo()];
}
```

Backtrace:
```
* thread #1: tid = 0x9916e, 0x0000000100000deb test`Foo::drop.2547::ha10a92966c711a1c + 43, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
  * frame #0: 0x0000000100000deb test`Foo::drop.2547::ha10a92966c711a1c + 43
    frame #1: 0x0000000100000da1 test`_$u5b$Foo$u3b$$u20$1$u5d$::drop.2545::h30bf5c7af770ce1a + 49
    frame #2: 0x0000000100000d6c test`main::h49ea8f6746b41e81Raa + 92
    frame #3: 0x0000000100006493 test`sys_common::unwind::try::try_fn::h8880715059644542985 + 35
    frame #4: 0x00000001000040a9 test`__rust_try + 9
    frame #5: 0x000000010000631c test`rt::lang_start::hf0f318bf9acb9103hUw + 540
    frame #6: 0x0000000100000e7a test`main + 42
    frame #7: 0x00007fff8e9185ad libdyld.dylib`start + 1
```

### LINKED ISSUE #30530: Segfault in an unconditional drop call after a match
This code will segfault running drop glue for `Box<Box<Fn()>>`, even though a value of that type is not actually created.
```rust
enum Handler {
    Default,
    Custom(*mut Box<Fn()>),
}

fn main() {
    take();
}

fn take() -> Box<Fn()> {
    unsafe {
        match Handler::Default {
            Handler::Default => Box::new(main),
            Handler::Custom(ptr) => *Box::from_raw(ptr),
        }
    }
}
```

Interestingly, it exits successfully if the second match body is wrapped in a block.

### LINKED ISSUE #30822: Double-drops when control jumps out of borrow of slice literal construction
(this is related to #30018, but it is also a distinct problem in its own right.)

We appear to be creating copies of values that should be moved when doing slice literal construction.

The copies can be observed because double-drop (of the same abstract value) can occur when there is a break of control out of the slice literal during evaluation of one of the elements.

Here is an example ([playpen](https://play.rust-lang.org/?gist=247cbabeab40ad875a8f&version=stable)):

```rust
struct D(&'static str);

impl Drop for D {
    fn drop(&mut self) {
        println!("Dropping D({})", self.0);
    }
}

fn main() {
    println!("Start");
    loop {
        let _r = &[D("1"),
                   D("2"),
                   { let _tmp = D("3"); break; },
                   D("4")];
    }
    println!("Finis");
}
```

outputs (in release mode):

```
Start
Dropping D(3)
Dropping D(2)
Dropping D(1)
Dropping D(1)
Dropping D(2)
Finis
```

The crucial point is that we see double drops of `D(1)` and `D(2)` in the output above. This would correspond, at least in theory, to deallocating a backing buffer multiple times -- that is, it is wrong. (Types like `Vec` probably defend themselves against such an attack since they currently use `unsafe_no_drop_flag` and thus should have an embedded drop flag state that it is maintaining itself, but other types that implement `Drop` do not necessary take that tack.)

(In debug mode there is a sigtrap at the end of that example; that is due to #30018, but again, that is not this ticket.)

### PR DESCRIPTION
**Pull request by pnkfelix**
Put back alloca zeroing for issues #29092, #30018, #30530; inject zeroing for #30822.

---

Background context: `fn alloca_zeroed` was removed in PR #22969, so we haven't been "zero'ing" (*) the alloca's since at least that point, but the logic behind that PR seems sound, so its not entirely obvious how _long_ the underlying bug has actually been present.  In other words, I have not yet done a survey to see when the new `alloc_ty` and `lvalue_scratch_datum` calls were introduced that should have had "zero'ing" the alloca's.

---

I first fixed #30018, then decided to do a survey of `alloc_ty` calls to see if they needed similar treatment, which quickly led to a rediscovery of #30530.

While making the regression test for the latter, I discovered #30822, which is a slightly different bug (in terms of where the "zero'ing" needs to go), but still relevant.

I haven't finished the aforementioned survey of `fn alloc_ty` calls, but I decided I wanted to get this up for review in its current state (namely to see if my attempt to force developers to include a justification for passing `Uninit` can possibly fly, or if I should abandon that path of action).

---

(*): I am putting quotation marks around "zero'ing" because we no longer use zero as our "dropped" marker value.

Fix #29092 
Fix #30018 
Fix #30530 
Fix #30822

### CODE REVIEW

File: src/librustc_trans/trans/datum.rs [hunk 1]
```diff
@@ -496,8 +509,10 @@ impl<'tcx> Datum<'tcx, Rvalue> {
 
             ByValue => {
                 lvalue_scratch_datum(
-                    bcx, self.ty, name, scope, self,
+                    bcx, self.ty, name, InitAlloca::Dropped, scope, self,
                     |this, bcx, llval| {
+                        debug!("populate call for Datum::to_lvalue_datum_in_scope \
+                                self.ty={:?}", this.ty);
                         call_lifetime_start(bcx, llval);
```
Comment (dotdash) [inline src/librustc_trans/trans/datum.rs]: The call to `llvm.lifetime.start` will happen after the dropped initialization, so LLVM will see that as a dead store.

**Comment by dotdash** [comment]
Just wondering, did you do any testing how well LLVM can remove those inits in case they're not actually required? Since the initialization happens in the entry block, the memory dependencies will often cross basic blocks which in some cases breaks optimizations. Not a huge concern, since this will probably largely go away with MIR trans, but I'm still curious. 

Maybe we are able to move the initialization closer to the point where the alloca is needed? I wonder whether we actually already request allocas in such a way that if we just emitted the `memset` at the current insertion point, we would guarantee that it dominates the `drop` call.

**Comment by pnkfelix** [comment]
@dotdash no I did not do any performance / codegen quality analysis

**Comment by nikomatsakis** [comment]
Hmm, so this seems overall good to me. But @dotdash already found some issues I hadn't considered (the lifetime point). So I'm inclined to move the review to him, if he's ok with that. :)

**Comment by pnkfelix** [comment]
@dotdash (I will try to do some analysis; I am hoping that my checking for a destructor will be a sufficient filter in most cases)

File: src/librustc_trans/trans/datum.rs (hunk 1 above)
Comment (pnkfelix) [inline src/librustc_trans/trans/datum.rs]: Hmm it seems like in some cases the only option would be to inject the lifetime start into the start of the function itself then, right after the alloca.

Does LLVM react okay if there exist multiple lifetime start

Comment (dotdash) [inline src/librustc_trans/trans/datum.rs]: From a quick glance a the dataflow calculation in the stack coloring pass, it looks like that might cause it to think that the alloca is dead when entering the basic block that has the second lifetime start. I didn't verify that though, because even if that does not happen, the lifetime will be extended to the entry block, so we could as well remove the second lifetime start call. That will reduce the potential for stack slot sharing, but I can't even guess how much of an impact that would have.

**Comment by brson** [comment]
This looks like its important to land before the next beta branch.

File: src/librustc_trans/trans/datum.rs (hunk 1 above)
Comment (pnkfelix) [inline src/librustc_trans/trans/datum.rs]: Okay; I will take care not to introduce multiple lifetime starts on a given path. (This will complicate the PR a bit but so be it)

**Comment by pnkfelix** [comment]
@brson hmm, I am not sure; given that:

 1. This bug is not currently biting *too* many clients (AFAWK...)
 2. beta is the least tested (I think) of the three standard channels (nightly beta stable), and
 3. I think whatever form this fix takes, it is likely to have somewhat high risk of injecting new bugs of its own (be they performance bugs or correctness bugs), ...

those three factors to me add up to: I doubt we should rush this into nightly to try to make the beta cut. (I mean, if it happens to make it in in time, I won't complain; but I don't want to rush it.)

**Comment by nikomatsakis** [comment]
r? @dotdash 

(let me know if you don't have time)

File: src/librustc_trans/trans/tvec.rs [hunk 2]
```diff
@@ -109,9 +109,16 @@ pub fn trans_slice_vec<'blk, 'tcx>(bcx: Block<'blk, 'tcx>,
...
+        InitAlloca::Dropped
+    } else {
+        InitAlloca::Uninit("fcx says vt.unit_ty is non-drop")
+    };
+
     // Always create an alloca even if zero-sized, to preserve
     // the non-null invariant of the inner slice ptr
-    let llfixed = base::alloc_ty(bcx, fixed_ty, "");
+    let llfixed = base::alloc_ty_init(bcx, fixed_ty, init_alloca, "");
     call_lifetime_start(bcx, llfixed);
```
Comment (dotdash) [inline src/librustc_trans/trans/tvec.rs]: I think this also needs to be made conditional.

**Comment by dotdash** [comment]
r=me with the lifetime call made conditional.

Maybe #29092 could be added to the list of issues this fixes, because even though I can't reproduce that issue anymore, I believe it to have (had) the same root cause as #30530 and that it's just hidden by slightly different optimizations.

**Comment by dotdash** [comment]
And the Travis failure actually seems to be caused by the wrong lifetime call, the memset gets eliminated.

**Comment by dotdash** [comment]
Actually, no, it's a different bug, and one that I originally introduced. This fixes it:

```diff
diff --git a/src/librustc_trans/trans/tvec.rs b/src/librustc_trans/trans/tvec.rs
index e5ef3b0..ac638d6 100644
--- a/src/librustc_trans/trans/tvec.rs
+++ b/src/librustc_trans/trans/tvec.rs
@@ -219,7 +219,6 @@ fn write_content<'blk, 'tcx>(bcx: Block<'blk, 'tcx>,
                         bcx = expr::trans_into(bcx, &**element,
                                                SaveIn(lleltptr));
                         let scope = cleanup::CustomScope(temp_scope);
-                        fcx.schedule_lifetime_end(scope, lleltptr);
                         // Issue #30822: mark memory as dropped after running destructor
                         fcx.schedule_drop_and_fill_mem(scope, lleltptr, vt.unit_ty, None);
                     }
```

The thing is that the element's memory is not actually dead here, since the slice owns the memory.

**Comment by pnkfelix** [comment]
@dotdash ah great, I'll fold that into this PR.
