### PR TITLE
Clarified error note for usize range matching

### LINKED ISSUE #146476: Matching on `usize` requires half-open range
`usize` ranges in `match` statements are surprising:

```rust
fn test(i: usize) {
    match i {
        0..=usize::MAX => todo!(),
    }
}
```

I expected this to compile; instead, `rustc` returns an error:
```
error[E0004]: non-exhaustive patterns: `usize::MAX..` not covered
 --> src/lib.rs:2:11
  |
2 |     match i {
  |           ^ pattern `usize::MAX..` not covered
  |
  = note: the matched value is of type `usize`
  = note: `usize` does not have a fixed maximum value, so half-open ranges are necessary to match exhaustively
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
  |
3 ~         0..=usize::MAX => todo!(),
4 ~         usize::MAX.. => todo!(),
  |

For more information about this error, try `rustc --explain E0004`.
```

This is obviously a known edge case, given the custom error message (which is great!), but it's still a weird paper cut.  It's especially weird to declare "`usize` does not have a fixed maximum value" when `usize::MAX` is right there!

Doing a little digging, it looks like it dates back to at least https://github.com/rust-lang/rust/pull/118598

### Meta

`rustc --version --verbose`:
```
rustc 1.89.0 (29483883e 2025-08-04)
binary: rustc
commit-hash: 29483883eed69d5fb4db01964cdf2af4d86e9cb2
commit-date: 2025-08-04
host: aarch64-apple-darwin
release: 1.89.0
LLVM version: 20.1.7
```

### PR DESCRIPTION
**Pull request by helldawg**
Fixes rust-lang/rust#146476

This is kinda rough, but it gets the point across a little better and stays short.

r? @workingjubilee 
@rustbot label A-diagnostics A-exhaustiveness-checking A-patterns

### CODE REVIEW

**Comment by workingjubilee** [comment]
Need to also fix the tests which may just require an `./x.py test ./tests/ui --bless`

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 1]
```diff
@@ -1275,12 +1275,12 @@ fn report_non_exhaustive_match<'p, 'tcx>(
...
                 if ty.inner() == cx.tcx.types.usize {
                     err.note(format!(
-                        "`{ty}` does not have a fixed maximum value, so half-open ranges are \
+                        "`{ty}::MAX` is not accessible as a fixed value, so half-open ranges are \
                          necessary to match exhaustively",
                     ));
                 } else if ty.inner() == cx.tcx.types.isize {
                     err.note(format!(
-                        "`{ty}` does not have fixed minimum and maximum values, so half-open \
+                        "The minimum and maximum values of `{ty}` are not directly accessible, so half-open \
```
Comment (fmease) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs]:
```suggestion
                        "the minimum and maximum values of `{ty}` are not directly accessible, so half-open \
```

https://rustc-dev-guide.rust-lang.org/diagnostics.html#diagnostic-output-style-guide

**Comment by helldawg** [comment]
Not really sure how to fix this failing check. It's being compared to the old one, even with the updated stderr. Seems like it's checking for stdout?

**Comment by cyrgani** [comment]
You also need to update the error annotations within the test files themselves such as "NOTE `usize` does not have a fixed maximum value". (https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotations)

**Comment by helldawg** [comment]
> You also need to update the error annotations within the test files themselves such as "NOTE `usize` does not have a fixed maximum value". (https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotations)

Gotcha, thank you.

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 2]
```diff
@@ -1275,12 +1275,12 @@ fn report_non_exhaustive_match<'p, 'tcx>(
             if ty.is_ptr_sized_integral() {
                 if ty.inner() == cx.tcx.types.usize {
                     err.note(format!(
-                        "`{ty}` does not have a fixed maximum value, so half-open ranges are \
+                        "`{ty}::MAX` is not accessible as a fixed value, so half-open ranges are \
```
Comment (workingjubilee) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs]: Hmm. I'm not sure what "accessible" is intended to mean here, as in a sense of "the path to the item", it sure is accessible.

Comment (helldawg) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs]: > Hmm. I'm not sure what "accessible" is intended to mean here, as in a sense of "the path to the item", it sure is accessible.

I think "accessible" means I need to access more sleep, because it looks like I was not comprehending anything I read. 

Thinking of changing it to:
"`usize::MAX` is not treated as exhaustive, so half-open ranges are necessary to match exhaustively"
and
"`isize::MIN` and `isize::MAX` are not treated as exhaustive, so half-open ranges are necessary to match exhaustively"

Or "considered" instead of "treated as"

Comment (workingjubilee) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs]: Mm. Maybe it would be good to think about this example:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=07824b8c993d26743b4a371df42b106b

Notice how `usize::MAX` is... well, no longer "actually" `usize::MAX`.

`usize::MAX` is a library constant and remains so which also means shadowing it is fair game. It's a bit of a case of "I love it when I can implement the same things as the standard library does! ...No, wait, not like that :sob:"

So `usize` patterns do not consider any particular constant as forming the upper bound of the type. This also handles the case, as mentioned in the issue, of
```rust
const USIZE_MAX: usize = usize::MAX;
```

Which arguably should be treated as the exhaustive upper bound if we treat `usize::MAX` also, but at what cost of compiler complexity and code correctness? Should it differ if one copies the literal there?

Comment (workingjubilee) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs]: You don't need to present an elaborate justification about compiler implementation, mind, indeed I expect most are not interested in that, I'm just noting some things.

Comment (helldawg) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs]: I considered elaborating on why this doesn't work the way it intuitively should, but decided that it wouldn't add all that much value in the end. The rationale being that knowing about the exact compiler quirk won't make it compile any better than the suggested fix (which _might_ have some room for improvement here?) or, y'know, making work as it theoretically should on the compiler level.

**Comment by helldawg** [comment]
> @helldawg Remembered one last thing: squash commits?

Welp, that took a good 7 open tabs and 20 minutes. Good news is that the commits are squashed, and 700 other commits _aren't_ tacked on for good measure.

**Comment by workingjubilee** [comment]
sorry. ^^;

@bors r+ rollup
