### PR TITLE
Toggle-wrap items differently than top-doc.

### LINKED ISSUE #85167: rustdoc: toggles for trait methods are in wrong position
Nightly:

image

https://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read

Stable:

image

https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read

### PR DESCRIPTION
**Pull request by jsha**
This makes sure things like trait methods get wrapped at the
`<h3><code>` level rather than at the `.docblock` level. Also it ensures
that only the actual top documentation gets the `.top-doc` class.

Fixes #85167

Before:

image

https://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read

After:

image

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -509,7 +509,11 @@ fn document(w: &mut Buffer, cx: &Context<'_>, item: &clean::Item, parent: Option
         info!("Documenting {}", name);
     }
     document_item_info(w, cx, item, parent);
-    document_full_collapsible(w, item, cx);
+    if parent.is_none() {
+        document_full_collapsible(w, item, cx);
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:513]: In which case was it a problem? Could you add a regression test for it please?

File: src/librustdoc/html/render/print_item.rs [hunk 2]
```diff
@@ -578,12 +578,13 @@ fn item_trait(w: &mut Buffer, cx: &Context<'_>, it: &clean::Item, t: &clean::Tra
         info!("Documenting {} on {:?}", name, t.name);
         let item_type = m.type_();
         let id = cx.derive_id(format!("{}.{}", item_type, name));
+        write!(w, "<details class=\"rustdoc-toggle\" open><summary>");
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/print_item.rs:581]: Can you add a screenshot to show where this change adds a toggle please?

Comment (jsha) [reply src/librustdoc/html/render/print_item.rs:581]: Added a before/after screenshot to the PR description.

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (jsha) [reply src/librustdoc/html/render/mod.rs:513]: Added.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+
