### PR TITLE
Apply lint restrictions from renamed lints

### LINKED ISSUE #82615: Renamed lints not honored in attributes
I tried this code:

```rust
#![deny(single_use_lifetime)]
fn _foo<'a>(_x: &'a u32) {}
```

I expected to see this happen: Should generate an error due to the `deny` attribute.

Instead, this happened: Generates a warning about the renamed lint (`single_use_lifetime` -> `single_use_lifetimes`), but otherwise does not generate an error.

Note that lints passed on the command-line (like `-D single_use_lifetime`) do work as expected.

### History

It looks like this behavior was broken in #43522 (first released in 1.21).  It worked properly in 1.20.  I don't see any discussion there about renaming, so I am assuming this was unintended. At the time, there was only one renamed lint (`unknown_features` -> `unused_features`), so I suspect there just wasn't much attention to it.  

It looks like at various points there were attempts to add tests for these kinds of things (#30878 added the [`lint-renamed.rs`](https://github.com/rust-lang/rust/blob/94736c434ee154b30e2ec22ec112b79e3f6c5884/src/test/ui/lint/lint-renamed.rs) test, which doesn't actually validate that the renamed lint works, just that it emits a warning).

Tested up to latest  rustc 1.52.0-nightly (9c09c1f7c 2021-02-26)

### PR DESCRIPTION
**Pull request by jyn514**
Previously, if you denied the old name of a renamed lint, it would warn
about using the new name, but otherwise do nothing. Now, it will behave
the same as if you'd used the new name.

Fixes https://github.com/rust-lang/rust/issues/82615.

r? @ehuss

### CODE REVIEW

File: compiler/rustc_lint/src/levels.rs [hunk 1]
```diff
@@ -321,17 +321,18 @@ impl<'s> LintLevelsBuilder<'s> {
                     None
                 };
                 let name = meta_item.path.segments.last().expect("empty lint name").ident.name;
-                match store.check_lint_name(&name.as_str(), tool_name) {
+                let lint_result = store.check_lint_name(&name.as_str(), tool_name);
+                match &lint_result {
                     CheckLintNameResult::Ok(ids) => {
                         let src = LintLevelSource::Node(name, li.span(), reason);
-                        for &id in ids {
+                        for &id in *ids {
```
Comment (camelid) [inline compiler/rustc_lint/src/levels.rs:328]: Is this change necessary?

Comment (jyn514) [reply compiler/rustc_lint/src/levels.rs:328]: Yes, `&&[T]` is not an iterator.

**Review by ehuss — APPROVED** [review]
Seems good to me, but I don't feel comfortable approving it.  Can you request a review from someone on the compiler team?

**Comment by jyn514** [comment]
Hmm, maybe r? @Manishearth ?

**Review by Manishearth — APPROVED** [review]
