### PR TITLE
fix: modify the condition that `resolve_imports` stops

### LINKED ISSUE #97534: ICE with macros in macros and multiple `use ... as ...`  with `--edition=2021`
### Code

```Rust
macro_rules! m {
    () => {
        macro_rules! foo {
            () => {
                
            }
        }
        use foo as bar;
    }
}

m!{}

use bar as baz;

baz!{}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3f57988efa7eff6f34bc735db3e89559))

### Meta

```
note: rustc 1.63.0-nightly (1fede1753 2022-05-28) running on x86_64-unknown-linux-gnu
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: expansion entered force mode without producing any errors
  --> src/lib.rs:16:1
   |
16 | baz!{}
   | ^^^^^^
   |
   = note: delayed at compiler/rustc_expand/src/expand.rs:415:34

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1368:13
stack backtrace:
   0:     0x7f6f85cabfad - std::backtrace_rs::backtrace::libunwind::trace::h299cf2fa55cd18e9
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6f85cabfad - std::backtrace_rs::backtrace::trace_unsynchronized::h9c3e5e09cd2938a9
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6f85cabfad - std::sys_common::backtrace::_print_fmt::h2f4272fba2a84b08
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f6f85cabfad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cc2e6942da231a2
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f6f85d07e3c - core::fmt::write::h74a5682239bd79fa
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f6f85c9d741 - std::io::Write::write_fmt::hdfbb1a9b5737a83f
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/io/mod.rs:1654:15
   6:     0x7f6f85caec95 - std::sys_common::backtrace::_print::h50a7f15c42b03867
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f6f85caec95 - std::sys_common::backtrace::print::h02ebeceda33368d4
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f6f85caec95 - std::panicking::default_hook::{{closure}}::h0887a34b8cc3534d
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/panicking.rs:295:22
   9:     0x7f6f85cae9b6 - std::panicking::default_hook::h0c4795ddf5f68072
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/panicking.rs:314:9
  10:     0x7f6f8647ddc1 - rustc_driver[2fa83badea7f0cdf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f6f85caf36a - std::panicking::rust_panic_with_hook::h78546479954c9351
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/panicking.rs:702:17
  12:     0x7f6f87610241 - std[ffa8b9f11b03dc27]::panicking::begin_panic::<rustc_errors[4e2c3398779f3018]::ExplicitBug>::{closure#0}
  13:     0x7f6f8760fdb6 - std[ffa8b9f11b03dc27]::sys_common::backtrace::__rust_end_short_backtrace::<std[ffa8b9f11b03dc27]::panicking::begin_panic<rustc_errors[4e2c3398779f3018]::ExplicitBug>::{closure#0}, !>
  14:     0x7f6f8762a1a6 - std[ffa8b9f11b03dc27]::panicking::begin_panic::<rustc_errors[4e2c3398779f3018]::ExplicitBug>
  15:     0x7f6f8762e2c6 - std[ffa8b9f11b03dc27]::panic::panic_any::<rustc_errors[4e2c3398779f3018]::ExplicitBug>
  16:     0x7f6f88ea5b81 - <rustc_errors[4e2c3398779f3018]::HandlerInner as core[be5cd14476d8865]::ops::drop::Drop>::drop
  17:     0x7f6f88613ab8 - core[be5cd14476d8865]::ptr::drop_in_place::<rustc_session[df9bd80ce5aaf91e]::parse::ParseSess>
  18:     0x7f6f88616503 - <alloc[3d41ab90ce221d7c]::rc::Rc<rustc_session[df9bd80ce5aaf91e]::session::Session> as core[be5cd14476d8865]::ops::drop::Drop>::drop
  19:     0x7f6f8860dc3d - core[be5cd14476d8865]::ptr::drop_in_place::<rustc_interface[dd8e8ad2dcac8021]::interface::Compiler>
  20:     0x7f6f8860d675 - rustc_span[dae761737fa53508]::with_source_map::<core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>, rustc_interface[dd8e8ad2dcac8021]::interface::create_compiler_and_run<core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>, rustc_driver[2fa83badea7f0cdf]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7f6f885eb397 - <scoped_tls[6e45a7225ea89339]::ScopedKey<rustc_span[dae761737fa53508]::SessionGlobals>>::set::<rustc_interface[dd8e8ad2dcac8021]::interface::run_compiler<core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>, rustc_driver[2fa83badea7f0cdf]::run_compiler::{closure#1}>::{closure#0}, core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>>
  22:     0x7f6f8860039f - std[ffa8b9f11b03dc27]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[dd8e8ad2dcac8021]::util::run_in_thread_pool_with_globals<rustc_interface[dd8e8ad2dcac8021]::interface::run_compiler<core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>, rustc_driver[2fa83badea7f0cdf]::run_compiler::{closure#1}>::{closure#0}, core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>>::{closure#0}, core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>>
  23:     0x7f6f886004d9 - <<std[ffa8b9f11b03dc27]::thread::Builder>::spawn_unchecked_<rustc_interface[dd8e8ad2dcac8021]::util::run_in_thread_pool_with_globals<rustc_interface[dd8e8ad2dcac8021]::interface::run_compiler<core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>, rustc_driver[2fa83badea7f0cdf]::run_compiler::{closure#1}>::{closure#0}, core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>>::{closure#0}, core[be5cd14476d8865]::result::Result<(), rustc_errors[4e2c3398779f3018]::ErrorGuaranteed>>::{closure#1} as core[be5cd14476d8865]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f6f85cb9283 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecccfcb66db01976
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/alloc/src/boxed.rs:1872:9
  25:     0x7f6f85cb9283 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfb7a821851f8fe74
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/alloc/src/boxed.rs:1872:9
  26:     0x7f6f85cb9283 - std::sys::unix::thread::Thread::new::thread_start::h2ecf741a356f4523
                               at /rustc/1fede1753c33f4ce0660ad9b8edbd618d9733daf/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f6f85bdf609 - start_thread
  28:     0x7f6f85b02133 - clone
  29:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (1fede1753 2022-05-28) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: expansion entered force mode without producing any errors
  --> src/lib.rs:16:1
   |
16 | baz!{}
   | ^^^^^^
   |
   = note: delayed at compiler/rustc_expand/src/expand.rs:415:34

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1368:13
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   4: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   6: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   7: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (1fede1753 2022-05-28) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`
```

</p>
</details>

### PR DESCRIPTION
**Pull request by bvanjoi**
close #97534

### CODE REVIEW

**Comment by petrochenkov** [comment]
This assert is supposed to catch situations that shouldn't happen.
If it is triggered then something goes wrong, and compilation should never succeed in such case.

We need to figure out why it does happen with the example from https://github.com/rust-lang/rust/issues/97534 instead of simply removing the assert.
@rustbot author

**Comment by bvanjoi** [comment]
> We need to figure out why it does happen with the example from https://github.com/rust-lang/rust/issues/97534 instead of simply removing the assert.

Thank you for helping me to change my mind about the problem. After checking the logs, I found that the problem with 
#97534 was that the resolve process from `bar` to `foo` was failing, which in turn was causing problems with the value of `progress`.

The current PR avoids this problem by changing the timing of `resolve_importers` execution, and it may fix the issue correctly. 

Looking forward to your suggestions!

File: tests/ui/proc-macro/derive-helper-legacy-spurious.rs [hunk 1]
```diff
@@ -5,8 +5,8 @@
 #[macro_use]
 extern crate test_macros;
 
-#[derive(Empty)] //~ ERROR cannot determine resolution for the attribute macro `derive`
-#[empty_helper] //~ ERROR cannot find attribute `empty_helper` in this scope
```
Comment (bvanjoi) [inline tests/ui/proc-macro/derive-helper-legacy-spurious.rs:9]: I removed these two expected errors because they were expected to be resolved to

**Comment by bvanjoi** [comment]
cc @petrochenkov

File: tests/ui/macros/nested-use-as-2021.rs [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+}
+
+use n1 as c1;
+c1!{}
+use c2 as a2;
+a2!{}
+use c3 as a3;
+a3!{}
+use c4 as a4;
+a4!{}
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply tests/ui/macros/nested-use-as-2021.rs:67]: Its purpose is to check that the current logic can correctly nest macros under multiple layers of structures

File: compiler/rustc_expand/src/expand.rs [hunk 3]
```diff
@@ -427,8 +427,10 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
         let mut undetermined_invocations = Vec::new();
         let (mut progress, mut force) = (false, !self.monotonic);
         loop {
-            let Some((invoc, ext)) = invocations.pop() else {
+            if progress {
                 self.resolve_imports();
+            }
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/expand.rs:432]: Could you move this back into the `let Some((invoc, ext)) = invocations.pop() else { ... }` condition?
We don't need to resolve more imports if we still have invocations in the queue to process.

**Comment by bvanjoi** [comment]
> I'm still not sure how a failing import resolution may affect the value of `progress`.

To be precise, it is not the failure of resolve that affects the value of `progress`, but rather the fact that `progress` uses `true` from the last loop, and thus reports an error.

File: compiler/rustc_expand/src/expand.rs (hunk 3 above)
Comment (bvanjoi) [reply compiler/rustc_expand/src/expand.rs:432]: Perhaps not, it is intended to ensure that the maximum number of resolved macros are available in the loop

Comment (bvanjoi) [reply compiler/rustc_expand/src/expand.rs:432]: This is the reason for the existence of [multiple nested test](https://github.com/rust-lang/rust/pull/108729/files#diff-0d98fde7f8b0195e3ee9a54a83ee001ba6c1619d9314ff5ceae7b8fcad647cd3R39-R67) cases

Comment (bvanjoi) [reply compiler/rustc_expand/src/expand.rs:432]: So, the purpose of running `resolve_imports` multiple times is to make it skip steps like step3, stpe5

Comment (bvanjoi) [reply compiler/rustc_expand/src/expand.rs:432]: Or we can solve this problem by changing the value of `progress`

Comment (petrochenkov) [reply compiler/rustc_expand/src/expand.rs:432]: >4. expand `bar!{}` but `resolved_macro_invocations` return `Err`

This part looks like a wrong behavior.

The crate at this point looks like
```rust
macro_rules! foo {
    () => {};
}

use foo as bar;

use bar as baz;

baz! {}
```
(which compiles ok by itself - https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=40e0c18cbb94afeb4a0cf11efd7d112c), and both `use foo as bar;` and `use bar as baz;` should be successfully resolved because we have just run `resolve_imports` to exhaustion.

Why does `resolved_macro_invocations` returns indeterminacy in this case?

Comment (bvanjoi) [reply compiler/rustc_expand/src/expand.rs:432]: it caused by [lazy_resolutions](https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/lib.rs#L1603), which in your example `baz` corresponds to ` resulutions.binding` is `Some(xxx)` so it returns success in  [check_usable](https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/ident.rs#L938-L942) returned successfully.

But in #97534, `baz` corresponds to `resulutions.binding` which is `None`, and it skips this step down and eventually returns `Err(Undetermined)`

Comment (petrochenkov) [reply compiler/rustc_expand/src/expand.rs:432]: I suspect that the true root cause of the issue lies somewhere in this area.
There should be no difference in resolution results between https://github.com/rust-lang/rust/pull/108729#discussion_r1131657710 and https://github.com/rust-lang/rust/issues/97534.

**Comment by petrochenkov** [comment]
Need to go deeper.
@rustbot author

**Comment by bvanjoi** [comment]
The question is that:

For the following code, in `resolve_imports` it will resolve `bar` first, and then `baz` afterwards, so it says that the `binding` in both is correct.

```rust
macro_rules! foo {
     () => {}
}
use foo as bar;
use bar as baz;
```

However, for the #97534, when it expands `resolve_imports` once after `m!{}`, it resolves `baz` first, and then `bar`, so the `binding` for `bar` is `None`, and the `binding` for `bar` is correct. Therefore, the subsequent `resolve_macro_invocation` does not get the correct value.

In this change, I have sorted `indeterminate_imports` by `root_span` before `resolve_import`, which might be a better solution.

cc @petrochenkov

File: compiler/rustc_mir_transform/src/coverage/query.rs [hunk 4]
```diff
@@ -1,6 +1,5 @@
 use super::*;
 
-use rustc_middle::mir::coverage::*;
```
Comment (bvanjoi) [inline compiler/rustc_mir_transform/src/coverage/query.rs:3]: delete it because it resolved at https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_transform/src/coverage/mod.rs#L22

File: library/core/tests/iter/sources.rs [hunk 5]
```diff
@@ -1,5 +1,4 @@
 use super::*;
-use core::iter::*;
```
Comment (bvanjoi) [inline library/core/tests/iter/sources.rs:2]: delete it because it resolved at https://github.com/rust-lang/rust/blob/master/library/core/tests/iter/mod.rs#L25

**Comment by petrochenkov** [comment]
>However, for the #97534, when it expands `resolve_imports` once after `m!{}`, it resolves `baz` first, and then `bar`, so the `binding` for `bar` is `None`, and the `binding` for `bar` is correct. Therefore, the subsequent `resolve_macro_invocation` does not get the correct value.

Import resolution algorithm is supposed to be order-independent - it is iterative and we assume that no matter in which order imports are resolved or placed in source code the result will be the same.

For example both
```rust
macro_rules! foo {
    () => {};
}

use foo as bar;
use bar as baz;

baz! {}
```
and
```rust
macro_rules! foo {
    () => {};
}

use bar as baz;
use foo as bar;

baz! {}
```
resolve successfully.

Basically, if we cannot resolve some import in one iteration, we then should be able to resolve it in some next iteration, even if the source code order is "unfriendly".

If the binding for `bar` is `None` and remains `None` even when `bar` can clearly be resolved, then we are not performing the iterative resolution correctly, the binding for `bar` should be eventually updated to `Some`.

**Comment by petrochenkov** [comment]
As for sorting by span, it is not something that we can do, really.
Procedural macros, for example, can assign arbitrary spans to their produced code.
So, span order is a hint for diagnostics at best, but not something that can be relied upon in the compiler.

Apologies for making you go through many rounds of review, this is a tricky area of the compiler, and making some change that would hide the ICE instead of fixing the root issue would only make things worse.
@rustbot author

**Comment by bvanjoi** [comment]
> Basically, if we cannot resolve some import in one iteration, we then should be able to resolve it in some next iteration

In fact, there are some problems with the iterative judgment condition here, which does not strictly apply to the situation you describe, for example:

```rust
macro_rules! foo {
    () => {};
}

use baz as zaa;
use bar as baz;
use foo as bar;

zaa! {}
```

it will throw a panic: 

image

Perhaps we need to revisit the termination condition of the loop in `resolve_imports`.

> Apologies for making you go through many rounds of review.

Actually, it's me who should be sorry. I have tried to learn more about Rust and its implementation by resolving some issues, but often this has led to unnecessary communication due to a lack of understanding of the whole project and a lack of knowledge of the compiler, so I would appreciate your guidance.

**Comment by bvanjoi** [comment]
I have extended the `resolve_import` execution in the latest PR.

Perhaps a better option would be to treat each `namespace` separately and do different iterations for their `indeterminate`?

**Comment by petrochenkov** [comment]
> for example ... it will throw a panic:

Ah, it's great that there's a simplified reproduction that only involves import order, without imports coming from macro expansions.

**Comment by petrochenkov** [comment]
>Perhaps a better option would be to treat each `namespace` separately and do different iterations for their `indeterminate`?

So what happens is there's a progress in 1 or 2 namespaces of an unresolved import, but not in all 3, so `fn resolve_imports` doesn't recognize it as progress?
That's why up to 2 retries are needed?

In that case yes, it would be the right thing to measure progress with per-namespace granularity.

File: library/core/tests/iter/sources.rs (hunk 5 above)
Comment (petrochenkov) [reply library/core/tests/iter/sources.rs:2]: Sorry, I don't understand.
Is there an unused import warning if this line it's not removed, or what?

Comment (bvanjoi) [reply library/core/tests/iter/sources.rs:2]: In the previous implementation based on sorting to `root_span`, it does give an `unsed import` alert: https://github.com/rust-lang/rust/actions/runs/4450003658/jobs/7814921906#step:26:1943

**Comment by bvanjoi** [comment]
> So what happens is there's a progress in 1 or 2 namespaces of an unresolved import, but not in all 3, so fn resolve_imports doesn't recognize it as progress?

It caused by [Err(Undermined) => indeterminate = true](https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/imports.rs#L649).

Take the code in #97534 for example, when it expands `foo{}` and then needs to `resolve_imports`, it needs `resolve_import("baz")` and `resolve_import("bar")` respectively.

First iteration.
1. `resolve_import("baz")` will first return `false`.
2. `resolve_imports("bar")` gets its binding, but since the other namespace is None, it triggers `indeterminate = true`, which causes the function to return `false` as well.

After the first iteration, `interminate_imports` still has ["baz", "bar"] in it, which does not satisfy the condition `indeterminate_imports.len() < prev_num_indeterminates`, so the loop ends without updating `"baz"`'s binding.

I have used `retry` in my code to force it to do one more round to ensure that the binding is updated correctly, but I'm not too sure if this behaviour will have a serious performance impact.

File: library/core/tests/iter/sources.rs (hunk 5 above)
Comment (bvanjoi) [reply library/core/tests/iter/sources.rs:2]: I have since kept this change as it seems to make the code simpler

**Comment by bvanjoi** [comment]
> In that case yes, it would be the right thing to measure progress with per-namespace granularity.

I am a little confused to understand how to handle this step, my preconception is to rewrite `indeterminate_imports` into three `type_indeterminate_imports`, `value_indeterminate_imports`, `macro_indeterminate_imports`, and later rewrite `resolve_imports` as follows:

```rust
fn resolve_imports(&mut self) {
        let mut prev_num_indeterminates = self.type_indeterminate_imports.len() +1;
        while self.type_indeterminate_imports.len() < prev_num_indeterminates {
            prev_num_indeterminates = self.type_indeterminate_imports.len() + 0;
            for import in mem::take(&mut self.type_indeterminate_imports) {
                match self.resolve_import(&import) {
                    true => self.determined_imports.push(import),
                    false => self.type_indeterminate_imports.push(import)
                }
            }
        }
        
       prev_num_indeterminates = self.value_indeterminate_imports.len() + 1;
       // repeat while loop

       prev_num_indeterminates = self.macro_indeterminate_imports.len() + 1;
       // repeat while loop
}
```

But it doesn't seem to be a good solution, do you have any suggestions? @petrochenkov

**Comment by petrochenkov** [comment]
I cannot answer for sure until I try it myself, but both `determined_imports` an `undetermined_imports` contain `Import`s and each `Import` incapsulates all 3 namespaces, so splitting into three vectors is probably not a good idea.

I guess `fn resolve_import` could return two flags instead of one - 1) whether it turned the import into determined and 2) whether it made any progress at all.
Then we'd push the import based one the first flag, and continue iterating based on the second flag.

**Comment by petrochenkov** [comment]
This should be the correct fix 👍 

It's just slightly more complicated than necessary.
I think something like this should be enough.
```diff
--- a/compiler/rustc_resolve/src/imports.rs
+++ b/compiler/rustc_resolve/src/imports.rs
@@ -423,13 +423,17 @@ fn import_dummy_binding(&mut self, import: &'a Import<'a>) {
     /// Resolves all imports for the crate. This method performs the fixed-
     /// point iteration.
     pub(crate) fn resolve_imports(&mut self) {
-        let mut prev_num_indeterminates = self.indeterminate_imports.len() + 1;
-        while self.indeterminate_imports.len() < prev_num_indeterminates {
-            prev_num_indeterminates = self.indeterminate_imports.len();
+        let mut prev_indeterminate_count = usize::MAX;
+        let mut indeterminate_count = self.indeterminate_imports.len() * 3;
+        while indeterminate_count < prev_indeterminate_count {
+            prev_indeterminate_count = indeterminate_count;
+            indeterminate_count = 0;
             for import in mem::take(&mut self.indeterminate_imports) {
-                match self.resolve_import(&import) {
-                    true => self.determined_imports.push(import),
-                    false => self.indeterminate_imports.push(import),
+                let import_indeterminate_count = self.resolve_import(&import);
+                indeterminate_count += import_indeterminate_count;
+                match import_indeterminate_count {
+                    0 => self.determined_imports.push(import),
+                    _ => self.indeterminate_imports.push(import),
                 }
             }
         }
@@ -583,7 +587,7 @@ fn throw_unresolved_import_error(&self, errors: Vec<(&Import<'_>, UnresolvedImpo
 
     /// Attempts to resolve the given import, returning true if its resolution is determined.
     /// If successful, the resolved bindings are written into the module.
-    fn resolve_import(&mut self, import: &'a Import<'a>) -> bool {
+    fn resolve_import(&mut self, import: &'a Import<'a>) -> usize {
         debug!(
             "(resolving import for module) resolving import `{}::...` in `{}`",
             Segment::names_to_string(&import.module_path),
@@ -601,8 +605,8 @@ fn resolve_import(&mut self, import: &'a Import<'a>) -> bool {
 
             match path_res {
                 PathResult::Module(module) => module,
-                PathResult::Indeterminate => return false,
-                PathResult::NonModule(..) | PathResult::Failed { .. } => return true,
+                PathResult::Indeterminate => return 3,
+                PathResult::NonModule(..) | PathResult::Failed { .. } => return 0,
             }
         };
 
@@ -618,12 +622,12 @@ fn resolve_import(&mut self, import: &'a Import<'a>) -> bool {
             } => (source, target, source_bindings, target_bindings, type_ns_only),
             ImportKind::Glob { .. } => {
                 self.resolve_glob_import(import);
-                return true;
+                return 0;
             }
             _ => unreachable!(),
         };
 
-        let mut indeterminate = false;
+        let mut indeterminate_count = 0;
         self.per_ns(|this, ns| {
             if !type_ns_only || ns == TypeNS {
                 if let Err(Undetermined) = source_bindings[ns].get() {
@@ -646,7 +650,7 @@ fn resolve_import(&mut self, import: &'a Import<'a>) -> bool {
 
                 let parent = import.parent_scope.module;
                 match source_bindings[ns].get() {
-                    Err(Undetermined) => indeterminate = true,
+                    Err(Undetermined) => indeterminate_count += 1,
                     // Don't update the resolution, because it was never added.
                     Err(Determined) if target.name == kw::Underscore => {}
                     Ok(binding) if binding.is_importable() => {
@@ -670,7 +674,7 @@ fn resolve_import(&mut self, import: &'a Import<'a>) -> bool {
             }
         });
 
-        !indeterminate
+        indeterminate_count
     }
 
     /// Performs final import resolution, consistency checks and error reporting.

```

**Comment by bvanjoi** [comment]
@rustbot ready

It was an unforgettable PR, the first time I applied what I learned in class to a complex project, thanks to your tireless correction of my problems and your mentor-like help. @petrochenkov

File: compiler/rustc_resolve/src/imports.rs [hunk 6]
```diff
@@ -583,7 +587,7 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
 
     /// Attempts to resolve the given import, returning true if its resolution is determined.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:588]: Outdated comment.

File: library/core/tests/iter/sources.rs (hunk 5 above)
Comment (petrochenkov) [inline library/core/tests/iter/sources.rs:2]: Could you move all the import removals to a separate commit with a description saying that the removed imports are redundant?

**Comment by petrochenkov** [comment]
r=me after addressing remaining nits
@rustbot author

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
