### PR TITLE
Use `resolutions(()).effective_visiblities` to avoid cycle errors in `report_object_error`

### LINKED ISSUE #119346: query cycle: `cycle detected when checking effective visibilities`
### Code

```Rust
trait Marker {}
impl Marker for u32 {}

trait MyTrait {
    fn foo(&self) -> impl Marker;
}

struct Outer;

impl MyTrait for Outer {
    fn foo(&self) -> impl Marker {
        42
    }
}

impl dyn MyTrait {
    fn other(&self) -> impl Marker {
        MyTrait::foo(&self)
    }
}

fn main() {}
```

### Current output

```Shell
error[E0277]: the trait bound `&dyn MyTrait: MyTrait` is not satisfied
  --> 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:18:22
   |
18 |         MyTrait::foo(&self)
   |         ------------ ^^^^^ the trait `MyTrait` is not implemented for `&dyn MyTrait`
   |         |
   |         required by a bound introduced by this call
   |
   = help: the trait `MyTrait` is implemented for `Outer`

error[E0391]: cycle detected when checking effective visibilities
   |
note: ...which requires computing type of `<impl at 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:16:1: 16:17>::other::{opaque#0}`...
  --> 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:17:24
   |
17 |     fn other(&self) -> impl Marker {
   |                        ^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:16:1: 16:17>::other::{opaque#0}`...
  --> 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:17:24
   |
17 |     fn other(&self) -> impl Marker {
   |                        ^^^^^^^^^^^
note: ...which requires type-checking `<impl at 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:16:1: 16:17>::other`...
  --> 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:17:5
   |
17 |     fn other(&self) -> impl Marker {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...which again requires checking effective visibilities, completing the cycle
note: cycle used when checking that `<impl at 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:16:1: 16:17>` is well-formed
  --> 38261B4E22E3BC8FEAD23C85E4CAE47D3F2B59CC950435EE3E08426A57F8BBE3.rs:16:1
   |
16 | impl dyn MyTrait {
   | ^^^^^^^^^^^^^^^^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0391.
For more information about an error, try `rustc --explain E0277`
```

### Desired output

_No response_

### Rationale and extra context

cc https://github.com/rust-lang/rust/issues/119321

### Other cases

_No response_

### Anything else?

_No response_

### LINKED ISSUE #119502: `cycle detected when checking effective visibility` hides relevant diagnostics message
### Code

```Rust
trait Useless {}
impl Useless for () {}
trait Source {
    fn a_function(self) -> impl Useless;
}
struct ABot;

impl Source for ABot {
    fn a_function(self) -> impl Useless {}
}

trait Sink {
    fn run(self) -> impl Useless;
}

struct Bot {
    pub sources: Vec<Box<dyn Source>>,
}

impl Sink for Bot {
    fn run(self) -> impl Useless {
        let _ = self.sources.len();
    }
}

fn main() {}
```

### Current output

```Shell
error[E0391]: cycle detected when checking effective visibilities
   |
note: ...which requires computing type of `<impl at src/main.rs:20:1: 20:18>::run::{opaque#0}`...
  --> src/main.rs:21:21
   |
21 |     fn run(self) -> impl Useless {
   |                     ^^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at src/main.rs:20:1: 20:18>::run::{opaque#0}`...
  --> src/main.rs:21:21
   |
21 |     fn run(self) -> impl Useless {
   |                     ^^^^^^^^^^^^
note: ...which requires type-checking `<impl at src/main.rs:20:1: 20:18>::run`...
  --> src/main.rs:21:5
   |
21 |     fn run(self) -> impl Useless {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...which again requires checking effective visibilities, completing the cycle
note: cycle used when checking that `Bot` is well-formed
  --> src/main.rs:16:1
   |
16 | struct Bot {
   | ^^^^^^^^^^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

For more information about this error, try `rustc --explain E0391`.
```

### Desired output

```Shell
error[E0038]: the trait `Source` cannot be made into an object
  --> src/main.rs:17:26
   |
17 |     pub sources: Vec<Box<dyn Source>>,
   |                          ^^^^^^^^^^ `Source` cannot be made into an object
   |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  --> src/main.rs:4:29
   |
3  | trait Source {
   |       ------ this trait cannot be made into an object...
4  |     fn a_function(&self) -> impl Useless;
   |                             ^^^^^^^^^^^^ ...because method `a_function` references an `impl Trait` type in its return type
   = help: consider moving `a_function` to another trait
   = help: only type `ABot` implements the trait, consider using it directly instead

For more information about this error, try `rustc --explain E0038`.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

This code is originally extracted from a reduction of a problem found hit on a [friend's project](https://git.vulpinecitrus.info/oror/booru-mirror). I reduced the code down to something that, confusingly, provides an incorrect diagnostics message.
Originally, the `-> impl Useless` dynamic dispatch were `async fn`, I just substituted them. The nightly toolchain as of today behaves the same.

As a note, **the correct output is provided if the statement `let _ = self.sources.len();` is commented out**, which is why I think this is related to #119346 , but maybe not the same.

### PR DESCRIPTION
**Pull request by compiler-errors**
Inside of `report_object_error`, using the `effective_visibilities` query causes cycles since it calls `type_of`, which itself may call `typeck`, which may end up reporting its own object-safety errors.

Fixes #119346
Fixes #119502

### CODE REVIEW

File: compiler/rustc_infer/src/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -132,7 +132,7 @@ pub fn report_object_safety_error<'tcx>(
     };
     let externally_visible = if !impls.is_empty()
         && let Some(def_id) = trait_def_id.as_local()
-        && tcx.effective_visibilities(()).is_exported(def_id)
+        && tcx.resolutions(()).effective_visibilities.is_exported(def_id)
```
Comment (Nilstrieb) [inline compiler/rustc_infer/src/traits/error_reporting/mod.rs:135]: maybe add a comment?

**Comment by fmease** [comment]
This has failed in rollup #119611 since the ordering of diagnostics has changed due to #117213.
Needs rebase & reblessing.

@bors r-
