### PR TITLE
Enforce Copy bounds for repeat elements while considering lifetimes

### LINKED ISSUE #95477: repeat expression do not honor lt bounds of copy
```rust
#![feature(nll)]

#[derive(Clone)]
struct Foo<'a>(fn(&'a ()) -> &'a ());

impl Copy for Foo<'static> {}

fn mk_foo<'a>() -> Foo<'a> {
    println!("mk_foo");
    Foo(|x| x)
}

fn foo<'a>() -> [Foo<'a>; 100] {
    [mk_foo::<'a>(); 100]
}

fn main() {
    foo();
}
```
this compiles both with and without `feature(nll)`. Note that `mk_foo` creates a value of type `Foo<'a>` which may not be copied.

Moving `mk_foo::<'a>()` into a local errors as expected:
```rust
#![feature(nll)]

#[derive(Clone)]
struct Foo<'a>(fn(&'a ()) -> &'a ());

impl Copy for Foo<'static> {}

fn mk_foo<'a>() -> Foo<'a> {
    println!("mk_foo");
    Foo(|x| x)
}

fn foo<'a>() -> [Foo<'a>; 100] {
    let x = mk_foo::<'a>();
    [x; 100]
}
```
this results in
```
error: lifetime may not live long enough
  --> src/main.rs:15:6
   |
13 | fn foo<'a>() -> [Foo<'a>; 100] {
   |        -- lifetime `'a` defined here
14 |     let x = mk_foo::<'a>();
15 |     [x; 100]
   |      ^ copying this value requires that `'a` must outlive `'static`
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/rust/issues/95477

this is a breaking change in order to fix a soundness bug.

Before this PR we only checked whether the repeat element type had an `impl Copy`, but not whether that impl also had the appropriate lifetimes. E.g. if the impl was for `YourType<'static>` and not a general `'a`, then copying any type other than a `'static` one should have been rejected, but wasn't.

r? @lcnr

### CODE REVIEW

**Comment by compiler-errors** [comment]
Crater perhaps?

**Comment by oli-obk** [comment]
@bors try

Oh yea, I knew I had forgotten some step here, thanks!

**Comment by oli-obk** [comment]
@craterbot check

**Comment by scottmcm** [comment]
I think we're good to do this under the usual "it was a bug" exception.

Hopefully crater says we can just do this, without a future compat dance.

**Comment by lcnr** [comment]
I there something blocking you from using `self.cx.prove_trait_ref` here?

**Comment by oli-obk** [comment]
Yes, that function will ICE if the bound doesn't hold. Hmm.. I don't remember whether I tried it or not. I think I did, but i'll try again. Maybe I discarded it as a possibility just by looking at the code and misinterpreting the fact that it'll only ICE if there's no copy impl at all, which typeck should've already prevented

**Comment by oli-obk** [comment]
Ah yes, I remember these ICEs, I did try this before, but get lots of failures like

```
--- stderr -------------------------------
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:7 ~ repeat_to_run_dtor_twice[6a18]::main) (NoSolution): could not prove Binder(TraitPredicate(<Foo as std::marker::Copy>, polarity:Positive), [])
  --> /home/ubuntu/rust5/src/test/ui/repeat-to-run-dtor-twice.rs:17:13
   |
LL |     let _ = [ a; 5 ];
   |             ^^^^^^^^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/canonical.rs:149:13
```

Which is happening because we are trying to borrowck a function that tries to copy a value that is never copy, irrespective of the lifetimes. So... I guess we can use `prove_trait_ref` if we patch typeck to at least do a minimal check. 

This is going to get into MCP territory, but what if we just stopped trying to prove things in HIR typeck? Basically we do the bare minimum needed for building MIR. During MIR typeck/borrowck to do the real checks and can avoid any of the modulo-lifetimes checks.

I mean... we were already doing this right here, we just didn't check lifetimes

**Comment by lcnr** [comment]
> So... I guess we can use prove_trait_ref if we patch typeck to at least do a minimal check.

would really prefer that :+1: I assume that checking whether something is copy can influence type inference? :thinking: I am kind of wary of completely moving any checks to mir typeck

**Comment by lcnr** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9d20dd6e1989c761a16255a4f73ca78b

```rust
#[derive(Clone, Default)]
struct MaybeCopy<T>(T);

impl Copy for MaybeCopy<u8> {}

fn is_copy<T: Copy>(x: T) {
    println!("{}", std::any::type_name::<T>());
} 

fn main() {
    is_copy(MaybeCopy::default())
    // [MaybeCopy::default(); 13]
    // ^ doesn't work cause `Copy` is only checked in the mir here
}
```

**Review by lcnr — COMMENTED** [review]
impl r=me

I personally think this is strictly a bugfix and doesn't need t-lang or t-compiler signoff? :thinking:

**Comment by oli-obk** [comment]
Yea, once crater is clean i'll assign to a lang team member for language level review

**Comment by oli-obk** [comment]
All regressions are definitely spurious

r? @nikomatsakis as you commented on the issue

This only breaks user code that is already unsound, and crater found no cases of people relying on this. We were only checking if a type has a `Copy` impl, not if it actually applies for the given lifetimes. So if the `Copy` impl was only for `'static`, but we had a non-static lifetime, the code was accepted.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 1]
```diff
@@ -1283,6 +1283,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    ty::FnDef(def_id, _) => tcx.is_const_fn(def_id),
+                    _ => false,
+                },
+                _ => false,
+            };
+
+            if count.try_eval_usize(tcx, self.param_env).map_or(true, |len| len > 1) {
+                let lang_item = self.tcx.require_lang_item(LangItem::Copy, None);
+                let code = traits::ObligationCauseCode::RepeatElementCopy { is_const_fn };
+                self.require_type_meets(element_ty, element.span, code, lang_item);
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/expr.rs:1310]: I don't object to this code, but I'm a bit confused what's going on here -- it seems like, in the MIR type check, we enforce that `T: Copy` unless we can statically see that the length is either 0 or 1 (which makes sense). But here, we have this `if !is_const` check that says (iiuc) "if this is not a constant value being repeated, require `T: Copy`". Why doesn't the MIR check have a similar "if not a constant value" thing going on? Or does it, and I just missed it? Perhaps it gets lowered differently in that case?

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in our @rust-lang/lang meeting today and we all agree this is a bugfix. Opening FCP to record that for posterity, but we don't have to wait for the full 10 days.

**Comment by nikomatsakis** [comment]
@rfcbot fcp cancel -- sigh, wrong team

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

We discussed this in our https://github.com/orgs/rust-lang/teams/lang meeting today and we all agree this is a bugfix. Opening FCP to record that for posterity, but we don't have to wait for the full 10 days.

File: src/test/ui/array-slice-vec/repeat_empty_ok.stderr [hunk 2]
```diff
@@ -1,8 +1,8 @@
 error[E0277]: the trait bound `Header<'_>: Copy` is not satisfied
-  --> $DIR/repeat_empty_ok.rs:8:19
+  --> $DIR/repeat_empty_ok.rs:8:20
    |
 LL |     let headers = [Header{value: &[]}; 128];
-   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `Header<'_>`
+   |                    ^^^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `Header<'_>`
    |
    = note: the `Copy` trait is required because the repeated element will be copied
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/array-slice-vec/repeat_empty_ok.stderr:7]: Do you mean to change the note to mention that this expression will be copied because it is the repeat element of a repeat expression?

[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/array-slice-vec/repeat_empty_ok.stderr]: I did $something

File: src/test/ui/consts/const-blocks/trait-error.stderr [hunk 3]
```diff
@@ -1,11 +1,18 @@
...
    |
-   = help: the trait `Copy` is implemented for `Foo<T>`
-   = note: the `Copy` trait is required because the repeated element will be copied
+note: required because of the requirements on the impl of `Copy` for `Foo<String>`
+  --> $DIR/trait-error.rs:1:10
+   |
+LL | #[derive(Copy, Clone)]
+   |          ^^^^
+   = note: the `Copy` trait is required because this value will be copied for each element of the array
+   = help: consider creating a new `const` item and initializing it with the result of the function call to be used in the repeat position, like `const VAL: Type = const_fn();` and `let x = [VAL; 42];`
```
Comment (estebank) [inline src/test/ui/consts/const-blocks/trait-error.stderr:13]: This. This is the bar `rustc` has to meet. <3

File: src/test/ui/repeat-expr/infer.rs [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+struct MaybeCopy<T>(T);
+
+impl Copy for MaybeCopy<u8> {}
+
+fn is_copy<T: Copy>(x: T) {
+    println!("{}", std::any::type_name::<T>());
+}
+
+fn main() {
+    is_copy(MaybeCopy::default());
```
Comment (estebank) [inline src/test/ui/repeat-expr/infer.rs:13]: Wait, I'm confused as to why this works. Is `Default: Copy`?

File: compiler/rustc_typeck/src/check/expr.rs [hunk 5]
```diff
@@ -1283,6 +1283,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             return tcx.ty_error();
         }
 
+        let is_const = match &element.kind {
+            hir::ExprKind::ConstBlock(..) => true,
+            hir::ExprKind::Path(qpath) => {
+                let res = self.typeck_results.borrow().qpath_res(qpath, element.hir_id);
+                matches!(
+                    res,
+                    Res::Def(DefKind::Const | DefKind::AssocConst | DefKind::AnonConst, _)
```
[the remark this answers is not in the document]
Comment (estebank) [reply compiler/rustc_typeck/src/check/expr.rs:1301]: +1

File: compiler/rustc_typeck/src/check/expr.rs [hunk 6]
```diff
@@ -1292,6 +1292,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                },
+                _ => false,
+            };
+
+            if count.try_eval_usize(tcx, self.param_env).map_or(true, |len| len > 1) {
+                let lang_item = self.tcx.require_lang_item(LangItem::Copy, None);
+                let code = traits::ObligationCauseCode::RepeatElementCopy { is_const_fn };
+                self.require_type_meets(element_ty, element.span, code, lang_item);
+            }
+        }
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/expr.rs:1321]: Should we move that entire block to its own `maybe_require_copy_value` (or something) function? That might make skimming easier.

**Review by estebank — APPROVED** [review]
r=me with the nitpicks addressed

File: src/test/ui/array-slice-vec/repeat_empty_ok.stderr [hunk 7]
```diff
@@ -1,22 +1,22 @@
 error[E0277]: the trait bound `Header<'_>: Copy` is not satisfied
-  --> $DIR/repeat_empty_ok.rs:8:19
+  --> $DIR/repeat_empty_ok.rs:8:20
    |
 LL |     let headers = [Header{value: &[]}; 128];
-   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `Header<'_>`
+   |                    ^^^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `Header<'_>`
    |
-   = note: the `Copy` trait is required because the repeated element will be copied
+   = note: the `Copy` trait is required because this value will be copied for each element of the array
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/array-slice-vec/repeat_empty_ok.stderr:7]: We had this before. I could revert the spans to point at the entire array again, but I thought it was actually neat that we were just pointing to the repeat element now.

File: src/test/ui/repeat-expr/infer.rs (hunk 4 above)
Comment (estebank) [reply src/test/ui/repeat-expr/infer.rs:13]: Oh, wait. This is because `MabeCopy::default(): ~const`, right?

**Comment by oli-obk** [comment]
/me pets the rfcbot, you have :chefkissfingers: timing

File: src/test/ui/repeat-expr/infer.rs (hunk 4 above)
Comment (oli-obk) [reply src/test/ui/repeat-expr/infer.rs:13]: This worked because there was only one type `T` for which `MaybeCopy<T>` could be `Copy`. If we also had `impl Copy for MaybeCopy<i8> {}` then this would stop working: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a4fa25d4154048a62eca08aedcceb090

File: compiler/rustc_typeck/src/check/expr.rs (hunk 6 above)
Comment (oli-obk) [reply compiler/rustc_typeck/src/check/expr.rs:1321]: Damn I love rust analyzer. Just selected the code and clicked "extract into fn". Add some lifetimes to types and remove the generated `tcx` argument *done*

File: src/test/ui/repeat-expr/infer.rs (hunk 4 above)
Comment (estebank) [reply src/test/ui/repeat-expr/infer.rs:13]: Ah! Wow! Hadn't realized that that's how it works.

File: src/test/ui/array-slice-vec/repeat_empty_ok.stderr (hunk 7 above)
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/array-slice-vec/repeat_empty_ok.stderr:7]: Nono, what we have now it's good.

**Comment by oli-obk** [comment]
This does add new dependency edges from typeck to other queries, so I'm not surprised there's more being marked dirty in incremental. I'll Loki at the benchmark itself to see what it is, but likely simply the fact that we now evaluate an array length in typeck.
