### PR TITLE
Apple: Refactor deployment target version parsing

### LINKED ISSUE #107630: [MacCatalyst]: Can't determine the platform when creating an xcframework from rust libraries
Hello I'm using `aarch64-apple-ios-macabi` and `x86_64-apple-ios-macabi` as follow in my project:

```
CARGO_TARGET_DIR=$BUILD_FOLDER cargo +nightly build -Z build-std --target aarch64-apple-ios-macabi --release
CARGO_TARGET_DIR=$BUILD_FOLDER cargo +nightly build -Z build-std --target x86_64-apple-ios-macabi --release
lipo $BUILD_FOLDER/aarch64-apple-ios-macabi/release/$TARGET_NAME $BUILD_FOLDER/x86_64-apple-ios-macabi/release/$TARGET_NAME -create -output $BUILD_FOLDER/catalyst/$TARGET_NAME

xcodebuild -create-xcframework -library $BUILD_FOLDER/$TARGET_NAME -library $BUILD_FOLDER/darwin_universal/$TARGET_NAME -library $BUILD_FOLDER/aarch64-apple-ios/release/$TARGET_NAME -library $BUILD_FOLDER/catalyst/$TARGET_NAME -output $TARGET_XCFRAMEWORK_NAME
```

Was working fine until XCode 14.2 release which now produce:

```
error: unable to determine the platform for the given binary 'project/build/local/catalyst/libproject_rs.a'; check your deployment version settings
```

This is the json target spec for MacCatalyst (aarch64):

```
{
  "abi": "macabi",
  "abi-return-struct-as-int": true,
  "arch": "aarch64",
  "archive-format": "darwin",
  "bitcode-llvm-cmdline": "-triple\u0000arm64-apple-ios-macabi\u0000-emit-obj\u0000-disable-llvm-passes\u0000-Os\u0000",
  "cpu": "apple-a12",
  "data-layout": "e-m:o-i64:64-i128:128-n32:64-S128",
  "debuginfo-kind": "dwarf-dsym",
  "default-dwarf-version": 2,
  "dll-suffix": ".dylib",
  "dynamic-linking": true,
  "eh-frame-header": false,
  "emit-debug-gdb-scripts": false,
  "features": "+neon,+fp-armv8,+apple-a12",
  "forces-embed-bitcode": true,
  "frame-pointer": "non-leaf",
  "function-sections": false,
  "has-rpath": true,
  "is-builtin": true,
  "is-like-osx": true,
  "link-env": [
    "ZERO_AR_DATE=1"
  ],
  "link-env-remove": [
    "IPHONEOS_DEPLOYMENT_TARGET"
  ],
  "linker-is-gnu": false,
  "lld-flavor": "darwin",
  "llvm-target": "arm64-apple-ios-macabi",
  "max-atomic-width": 128,
  "os": "ios",
  "pre-link-args": {
    "gcc": [
      "-target",
      "arm64-apple-ios-macabi"
    ],
    "ld": [
      "-arch",
      "arm64",
      "-platform_version",
      "mac-catalyst",
      "7.0",
      "7.0"
    ],
    "ld64.lld": [
      "-arch",
      "arm64",
      "-platform_version",
      "mac-catalyst",
      "7.0",
      "7.0"
    ]
  },
  "split-debuginfo": "packed",
  "supported-split-debuginfo": [
    "packed",
    "unpacked",
    "off"
  ],
  "target-family": [
    "unix"
  ],
  "target-pointer-width": "64",
  "vendor": "apple"
}
```

Every other targets outside of catalyst seems to work

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (f3126500f 2023-02-02)
binary: rustc
commit-hash: f3126500f25114ba4e0ac3e76694dd45a22de56d
commit-date: 2023-02-02
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

Maybe XCode have new requirements that the targets doesn't respect correctly? and therefore xcodebuild can't create an xcframework from any catalyst library?

Simple repro:

```
rustup update
  rustup toolchain install nightly
  rustup default nightly
  rustup toolchain install nightly-x86_64-apple-darwin
  rustup toolchain install nightly-aarch64-apple-darwin
  rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
  rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
rustup target add aarch64-apple-darwin x86_64-apple-darwin
rustup target add x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios 
```

```
cargo build --target aarch64-apple-ios --release
cargo build --target aarch64-apple-ios-sim --release
 cargo build --target x86_64-apple-ios --release
 cargo build --target aarch64-apple-darwin --release
 cargo build --target x86_64-apple-darwin --release
 cargo +nightly build -Z build-std --target aarch64-apple-ios-macabi --release
 cargo +nightly build -Z build-std --target x86_64-apple-ios-macabi --release

lipo build_folder/x86_64-apple-ios/release/lib_name.a build_folder/aarch64-apple-ios-sim/release/libname.a -create -output build_folder/libname.a

 mkdir -p build_folder/darwin_universal
  lipo build_folder/x86_64-apple-darwin/release/libname.a build_folder/aarch64-apple-darwin/release/libname.a -create -output build_folder/darwin_universal/libname.a
  mkdir -p build_folder//catalyst
  lipo build_folder/aarch64-apple-ios-macabi/release/libname.a build_folder/x86_64-apple-ios-macabi/release/libname.a -create -output build_folder/catalyst/libname.a

## Will fail on catalyst with `error: unable to determine the platform for the given binary 'project/build/local/catalyst/libname.a'; check your deployment version settings`  
    xcodebuild -create-xcframework -library $BUILD_FOLDER/$TARGET_NAME -library $BUILD_FOLDER/darwin_universal/$TARGET_NAME -library $BUILD_FOLDER/aarch64-apple-ios/release/$TARGET_NAME -library $BUILD_FOLDER/catalyst/$TARGET_NAME -output $TARGET_XCFRAMEWORK_NAME

```

### LINKED ISSUE #123582: WatchOS Target: Unrecognized deployment version by xcodebuild
When compiling for aarch64-apple-watchos target, building is successful, but when trying to pipe the generated binaries into xcodebuild I get:

```
error: unable to determine the platform for the given binary 'librepetitiontracker.a'; check your deployment version settings
```

This issue does not occur oddly with aarch64-apple-watchos-sim target, which works perfectly. It does however happen with every non simulator target for apple watch at the moment

### PR DESCRIPTION
**Pull request by madsmtm**
Refactor deployment target parsing to make it easier to do https://github.com/rust-lang/rust/pull/129342 (I wanted to make sure of all the places that `std::env::var` is called).

Specifically, my goal was to minimize the amount of target-specific configuration, so to that end I renamed the `opts` function that generates the `TargetOptions` to `base`, and made it return the LLVM target and `target_arch` too. In the future, I would like to move even more out of the target files and into `spec::apple`, as it makes it easier for me to maintain.

For example, this fixed a bug in `aarch64-apple-watchos`, which wasn't passing the deployment target as part of the LLVM triple. This (probably) fixes https://github.com/rust-lang/rust/issues/123582 and fixes https://github.com/rust-lang/rust/issues/107630.

We also now parse the patch version of deployment targets, allowing the user to specify e.g. `MACOSX_DEPLOYMENT_TARGET=10.12.6`.

Finally, this fixes the LLVM target name for visionOS, it should be `*-apple-xros` and not `*-apple-visionos`.

Since I have changed all the Apple targets here, I smoke-tested my changes by running the following:
```console
# Build each target
./x build library --target="aarch64-apple-darwin,aarch64-apple-ios,aarch64-apple-ios-macabi,aarch64-apple-ios-sim,aarch64-apple-tvos,aarch64-apple-tvos-sim,aarch64-apple-visionos,aarch64-apple-visionos-sim,aarch64-apple-watchos,aarch64-apple-watchos-sim,arm64_32-apple-watchos,arm64e-apple-ios,armv7k-apple-watchos,armv7s-apple-ios,i386-apple-ios,x86_64-apple-darwin,x86_64-apple-ios,x86_64-apple-ios-macabi,x86_64-apple-tvos,x86_64-apple-watchos-sim,x86_64h-apple-darwin"

# Test that we can still at least link basic projects
cargo new foobar && cd foobar && cargo +stage1 build --target=aarch64-apple-darwin --target=aarch64-apple-ios --target=aarch64-apple-ios-macabi --target=aarch64-apple-ios-sim --target=aarch64-apple-tvos --target=aarch64-apple-tvos-sim --target=aarch64-apple-visionos --target=aarch64-apple-visionos-sim --target=aarch64-apple-watchos --target=aarch64-apple-watchos-sim --target=arm64_32-apple-watchos --target=armv7s-apple-ios --target=i386-apple-ios --target=x86_64-apple-darwin --target=x86_64-apple-ios --target=x86_64-apple-ios-macabi --target=x86_64-apple-tvos --target=x86_64-apple-watchos-sim --target=x86_64h-apple-darwin
```

I couldn't build for the `arm64e-apple-darwin` target, the `armv7k-apple-watchos` and `arm64e-apple-ios` targets failed to link, and I know that the `i686-apple-darwin` target requires a bit of setup, but all of this is as it was before this PR.

r? thomcc

CC @BlackHoleFox

I would recommend using `rollup=never` when merging this, in case we need to bisect this later.

### CODE REVIEW

**Comment by madsmtm** [comment]
@bors rollup=never

There are quite a few changes here, and we might need to bisect this later.

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 1]
```diff
@@ -230,58 +274,115 @@ pub fn platform(target: &Target) -> Option<u32> {
...
+        Arch::Arm64e
+    } else if target.arch == "aarch64" {
+        Arch::Arm64
+    } else {
+        // Dummy architecture, only used by `deployment_target` anyhow
+        Arch::X86_64
     };
-
-    Some((major, minor))
+    let abi = match &*target.abi {
```
Comment (thomcc) [inline compiler/rustc_target/src/spec/base/apple/mod.rs:287]: It bugs me that these are ABIs (and not envs, like they are in clang) but changing that isn't practical due to compatibility.

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 2]
```diff
@@ -230,58 +274,115 @@ pub fn platform(target: &Target) -> Option<u32> {
...
+    };
 
-    Some((major, minor))
-}
+    // On certain targets it makes sense to raise the minimum OS version.
+    let min = match (os, arch, abi) {
+        // Use 11.0 on Aarch64 as that's the earliest version with M1 support.
+        ("macos", Arch::Arm64 | Arch::Arm64e, _) => (11, 0, 0),
+        ("ios", Arch::Arm64e, _) => (14, 0, 0),
+        // Mac Catalyst defaults to 13.1 in Clang.
```
Comment (thomcc) [inline compiler/rustc_target/src/spec/base/apple/mod.rs:321]: This is a behavioral change, no? Not that this is a problem, just want to make sure.

**Review by thomcc — APPROVED** [review]
This looks fine to me. Was a hassle to verify all the targets match what they used to.

**Comment by thomcc** [comment]
I'm not a compiler-team or compiler-contributor so I'll roll to someone who is, but I'd have R+ed this if I were.
r? compiler

File: compiler/rustc_target/src/spec/base/apple/mod.rs (hunk 2 above)
Comment (madsmtm) [reply compiler/rustc_target/src/spec/base/apple/mod.rs:321]: No, we did this before too, see the previous `ios_deployment_target`

**Comment by madsmtm** [comment]
r? compiler

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 3]
```diff
@@ -97,53 +98,95 @@ impl TargetAbi {
...
+        Armv7s => "armv7s",
+        Arm64 => "arm64",
+        Arm64e => "arm64e",
+        Arm64_32 => "arm64_32",
+        // ld64 doesn't understand i686, so fall back to i386 instead
+        //
+        // Same story when linking with cc, since that ends up invoking ld64.
+        I386 | I686 => "i386",
+        X86_64 => "x86_64",
+        X86_64h => "x86_64h",
```
Comment (petrochenkov) [inline compiler/rustc_target/src/spec/base/apple/mod.rs:124]: Maybe factor out this into a function and put it next to `fn target_name` to highlight their similarities and differences?

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 4]
```diff
@@ -97,53 +98,95 @@ impl TargetAbi {
 }
 
 fn pre_link_args(os: &'static str, arch: Arch, abi: TargetAbi) -> LinkArgs {
+    let mut args = LinkArgs::new();
```
Comment (petrochenkov) [inline compiler/rustc_target/src/spec/base/apple/mod.rs:101]: I think `TargetOptions::link_args` can still be used here instead of `LinkArgs::new`.

File: compiler/rustc_target/src/spec/base/apple/mod.rs (hunk 3 above)
Comment (madsmtm) [reply compiler/rustc_target/src/spec/base/apple/mod.rs]: Yeah, kinda wanted to get rid of `target_name` too, and instead just inline it at the usage sites, I felt that was clearer. But anyhow, I've done as you've suggested.

**Comment by madsmtm** [comment]
Thanks for the review!

@rustbot ready

**Review by BlackHoleFox — APPROVED** [review]
Since this has been looked at someone on the compiler team, here's my lookover from the Apple perspective since I was CCed.

File: compiler/rustc_target/src/spec/base/apple/mod.rs [hunk 5]
```diff
@@ -230,58 +274,115 @@ pub fn platform(target: &Target) -> Option<u32> {
...
+    // Mach-O commands.
+    //
+    // Certain optimizations also depend on the deployment target.
+    //
+    // Modern iOS tooling extracts information about deployment target
+    // from LC_BUILD_VERSION. This load command will only be emitted when
+    // we build with a version specific `llvm_target`, with the version
+    // set high enough. Luckily one LC_BUILD_VERSION is enough, for Xcode
+    // to pick it up (since std and core are still built with the fallback
+    // of version 7.0 and hence emit the old LC_IPHONE_MIN_VERSION).
```
[the remark this answers is not in the document]
Comment (madsmtm) [reply compiler/rustc_target/src/spec/base/apple/mod.rs]: I've rewritten the comment and moved it to `compiler/rustc_codegen_ssa/src/back/metadata.rs` where I felt the information was more relevant.
