### PR TITLE
fix ICE when `asm_const` and `const_refs_to_static` are combined

### LINKED ISSUE #124164: ICE during validation of ill-typed static: assertion `left == right` failed at `rustc_const_eval/src/interpret/validity.rs`
### Code

(minimized)

```Rust
static S_COUNT: = std::sync::atomic::AtomicUsize::new(0);

fn main() {}
```

EDIT: `static S_COUNT = std::sync::atomic::AtomicUsize::new(0);` also causes ICE.

<details><summary><strong>Original Code</strong></summary>
<p>

```Rust
// Reject mixing cyclic structure and Drop when using trait
// objects to hide the cross-references.
//
// (Compare against ui/span/dropck_vec_cycle_checked.rs)

use std::cell::Cell;
use id::Id;

mod s {
    use std::sync::atomic::{AtomicUsize, Ordering};

    static S_COUNT:  = AtomicUsize::new(0);

    pub fn next_count() -> usize {
        S_COUNT.fetch_add(1, Ordering::SeqCst) + 1
    }
}

mod id {
    use s;
    #[derive(Debug)]
    pub struct Id {
        orig_count: usize,
        count: usize,
    }

    impl Id {
        pub fn new() -> Id {
            let c = s::next_count();
            println!("building Id {}", c);
            Id { orig_count: c, count: c }
        }
        pub fn count(&self) -> usize {
            println!("Id::count on {} returns {}", self.orig_count, self.count);
            self.count
        }
    }

    impl Drop for Id {
        fn drop(&mut self) {
            println!("dropping Id {}", self.count);
            self.count = 0;
        }
    }
}

trait HasId {
    fn count(&self) -> usize;
}

#[derive(Debug)]
struct CheckId<T:HasId> {
    v: T
}

#[allow(non_snake_case)]
fn CheckId<T:HasId>(t: T) -> CheckId<T> { CheckId{ v: t } }

impl<T:HasId> Drop for CheckId<T> {
    fn drop(&mut self) {
        assert!(self.v.count() > 0);
    }
}

trait Obj<'a> : HasId {
    fn set0(&self, b: &'a Box<dyn Obj<'a>>);
    fn set1(&self, b: &'a Box<dyn Obj<'a>>);
}

struct O<'a> {
    id: Id,
    obj0: CheckId<Cell<Option<&'a Box<dyn Obj<'a>>>>>,
    obj1: CheckId<Cell<Option<&'a Box<dyn Obj<'a>>>>>,
}

impl<'a> HasId for O<'a> {
    fn count(&self) -> usize { self.id.count() }
}

impl<'a> O<'a> {
    fn new() -> Box<O<'a>> {
        Box::new(O {
            id: Id::new(),
            obj0: CheckId(Cell::new(None)),
            obj1: CheckId(Cell::new(None)),
        })
    }
}

impl<'a> HasId for Cell<Option<&'a Box<dyn Obj<'a>>>> {
    fn count(&self) -> usize {
        match self.get() {
            None => 1,
            Some(c) => c.count(),
        }
    }
}

impl<'a> Obj<'a> for O<'a> {
    fn set0(&self, b: &'a Box<dyn Obj<'a>>) {
        self.obj0.v.set(Some(b))
    }
    fn set1(&self, b: &'a Box<dyn Obj<'a>>) {
        self.obj1.v.set(Some(b))
    }
}


fn f() {
    let (o1, o2, o3): (Box<dyn Obj>, Box<dyn Obj>, Box<dyn Obj>) = (O::new(), O::new(), O::new());
    o1.set0(&o2); //~ ERROR `o2` does not live long enough
    o1.set1(&o3); //~ ERROR `o3` does not live long enough
    o2.set0(&o2); //~ ERROR `o2` does not live long enough
    o2.set1(&o3); //~ ERROR `o3` does not live long enough
    o3.set0(&o1); //~ ERROR `o1` does not live long enough
    o3.set1(&o2); //~ ERROR `o2` does not live long enough
}

fn main() {
    f();
}
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (e3181b091 2024-04-18)
binary: rustc
commit-hash: e3181b091e88321f5ea149afed6db0edf0a4f37b
commit-date: 2024-04-18
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.4
```

### Command
`rustc`

### Error output

```
error: missing type for `static` item
 --> m_crushed_713540.rs:1:16
  |
1 | static S_COUNT: = std::sync::atomic::AtomicUsize::new(0);
  |                ^ help: provide a type for the static variable: `AtomicUsize`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/validity.rs:727:21:
assertion `left == right` failed
  left: Mut
 right: Not
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<rustc_ast_ir::Mutability, rustc_ast_ir::Mutability>
   4: rustc_const_eval::interpret::validity::mutability::<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>
   5: <rustc_const_eval::interpret::validity::ValidityVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter> as rustc_const_eval::interpret::visitor::ValueVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::visit_value
   6: <rustc_const_eval::interpret::validity::ValidityVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter> as rustc_const_eval::interpret::visitor::ValueVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::walk_value
   7: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::validate_operand_internal
   8: rustc_const_eval::const_eval::eval_queries::eval_static_initializer_provider
      [... omitted 2 frames ...]
   9: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_hir_analysis::check_crate::{closure#3}>::{closure#0}
  10: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_analysis::check_crate::{closure#3}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
  11: rustc_hir_analysis::check_crate
  12: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  13: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  14: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/jisukbyun/workspace/placeholder/240420_rustexec/rustc-ice-2024-04-19T15_57_00-86400.txt` to your bug report

query stack during panic:
#0 [eval_static_initializer] evaluating initializer of static `S_COUNT`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error
```

</p>
</details>

### Note

- ICE-loc: `compiler/rustc_const_eval/src/interpret/validity.rs:727:21`
https://github.com/rust-lang/rust/blob/e3181b091e88321f5ea149afed6db0edf0a4f37b/compiler/rustc_const_eval/src/interpret/validity.rs#L726-L728

- Original ICE-triggering code is mutated from test-file `dropck_trait_cycle_checked.rs`
   https://github.com/rust-lang/rust/blob/07d0d7ce3fd22e4fadd61206034af6fadcdb3e4f/tests/ui/dropck/dropck_trait_cycle_checked.rs#L12

### LINKED ISSUE #126896: ICE: `deref projection of non-dereferenceable ty` with `feature(type_alias_impl_trait)` and polymorphization
### Code

```Rust
#![feature(type_alias_impl_trait)]
type Two<'a, 'b> = impl std::fmt::Debug;

fn set(x: &mut isize) -> isize {
    *x
}

fn d(x: Two) {
    let c1 = || set(x);
    c1;
}

fn main() {
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (bcf94dec5 2024-06-23)
binary: rustc
commit-hash: bcf94dec5ba6838e435902120c0384c360126a26
commit-date: 2024-06-23
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

Command
`/home/user/.cargo/bin/rustc ./E7BC0.rs -Zpolymorphize=on -Zinline-mir=yes`

### Error output

```
error[E0792]: expected generic lifetime parameter, found `'_`
 --> ./E7BC0.rs:9:17
  |
2 | type Two<'a, 'b> = impl std::fmt::Debug;
  |          -- this generic parameter must be used with a generic lifetime parameter
...
9 |     let c1 = || set(x);
  |                 ^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/mir/tcx.rs:83:21: deref projection of non-dereferenceable ty PlaceTy { ty: {type error}, variant_index: None }

thread 'rustc' panicked at compiler/rustc_middle/src/mir/tcx.rs:83:21:
Box<dyn Any>
stack backtrace:
   0:        0x10bae6b43 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he71f7af0ddafc64d
   1:        0x10bb3225b - core::fmt::write::h30d0e266faff29b6
   2:        0x10badcace - std::io::Write::write_fmt::he666ca78eb4b8406
   3:        0x10bae6931 - std::sys::backtrace::print::h22721f9ab9a2749a
   4:        0x10bae9709 - std::panicking::default_hook::{{closure}}::h145e29ed875d8021
   5:        0x10bae948a - std::panicking::default_hook::h5d437c7e6bf0e3b5
   6:        0x114d8147c - std[8efa578c02603ef9]::panicking::update_hook::<alloc[135510a28be92df]::boxed::Box<rustc_driver_impl[63f2171535a6fe49]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x10baea326 - std::panicking::rust_panic_with_hook::h6889093a56e48d04
   8:        0x114df0337 - std[8efa578c02603ef9]::panicking::begin_panic::<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>::{closure#0}
   9:        0x114ddc949 - std[8efa578c02603ef9]::sys::backtrace::__rust_end_short_backtrace::<std[8efa578c02603ef9]::panicking::begin_panic<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>::{closure#0}, !>
  10:        0x1197e2f09 - std[8efa578c02603ef9]::panicking::begin_panic::<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>
  11:        0x114e02276 - <rustc_errors[8995f93e9c4bcc9a]::diagnostic::BugAbort as rustc_errors[8995f93e9c4bcc9a]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:        0x115a9c95e - rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt::<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}
  13:        0x115a522b7 - rustc_middle[4384e439927f71dd]::ty::context::tls::with_opt::<rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:        0x115a51d75 - rustc_middle[4384e439927f71dd]::ty::context::tls::with_context_opt::<rustc_middle[4384e439927f71dd]::ty::context::tls::with_opt<rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:        0x1198a57eb - rustc_middle[4384e439927f71dd]::util::bug::bug_fmt
  16:        0x115a118af - <rustc_middle[4384e439927f71dd]::mir::tcx::PlaceTy>::projection_ty
  17:        0x115dfe1b0 - <rustc_mir_transform[6fada3a7f62d9c6e]::remove_zsts::Replacer as rustc_middle[4384e439927f71dd]::mir::visit::MutVisitor>::visit_operand
  18:        0x115dfdbf1 - <rustc_mir_transform[6fada3a7f62d9c6e]::remove_zsts::RemoveZsts as rustc_middle[4384e439927f71dd]::mir::MirPass>::run_pass
  19:        0x115d76f44 - rustc_mir_transform[6fada3a7f62d9c6e]::pass_manager::run_passes_inner
  20:        0x115e2a633 - rustc_mir_transform[6fada3a7f62d9c6e]::optimized_mir
  21:        0x11641c908 - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 8usize]>>
  22:        0x1161f724f - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::DefIdCache<rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  23:        0x116435849 - rustc_query_impl[a24e9023943e74ab]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  24:        0x115e5faef - rustc_middle[4384e439927f71dd]::query::plumbing::query_get_at::<rustc_query_system[30bd0146b5104221]::query::caches::DefIdCache<rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 8usize]>>>
  25:        0x115e9bf18 - rustc_monomorphize[7e44dc73c1b07443]::polymorphize::unused_generic_params
  26:        0x116420333 - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::unused_generic_params::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 4usize]>>
  27:        0x1163d4c0f - <rustc_query_impl[a24e9023943e74ab]::query_impl::unused_generic_params::dynamic_query::{closure#2} as core[9412a59d758dca42]::ops::function::FnOnce<(rustc_middle[4384e439927f71dd]::ty::context::TyCtxt, rustc_middle[4384e439927f71dd]::ty::instance::InstanceKind)>>::call_once
  28:        0x11625c12c - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::DefaultCache<rustc_middle[4384e439927f71dd]::ty::instance::InstanceKind, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  29:        0x11647a486 - rustc_query_impl[a24e9023943e74ab]::query_impl::unused_generic_params::get_query_non_incr::__rust_end_short_backtrace
  30:        0x1156dac81 - rustc_interface[73216d77aad0c3a5]::passes::run_required_analyses
  31:        0x1156dccb3 - rustc_interface[73216d77aad0c3a5]::passes::analysis
  32:        0x116422dec - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 1usize]>>
  33:        0x11620249e - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::SingleCache<rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  34:        0x11642d307 - rustc_query_impl[a24e9023943e74ab]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:        0x114d258d7 - <rustc_interface[73216d77aad0c3a5]::queries::QueryResult<&rustc_middle[4384e439927f71dd]::ty::context::GlobalCtxt>>::enter::<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  36:        0x114d7fc94 - rustc_interface[73216d77aad0c3a5]::interface::run_compiler::<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}
  37:        0x114d6ec91 - std[8efa578c02603ef9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_with_globals<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_pool_with_globals<rustc_interface[73216d77aad0c3a5]::interface::run_compiler<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>
  38:        0x114d8a3a6 - <<std[8efa578c02603ef9]::thread::Builder>::spawn_unchecked_<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_with_globals<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_pool_with_globals<rustc_interface[73216d77aad0c3a5]::interface::run_compiler<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#2} as core[9412a59d758dca42]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:        0x10baf352b - std::sys::pal::unix::thread::Thread::new::thread_start::h68d49fa26efc1659
  40:     0x7ff801f5318b - __pthread_start

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/Documents/rustc-ice-27151.txt` to your bug report

note: compiler flags: -Z polymorphize=on -Z inline-mir=yes

query stack during panic:
#0 [optimized_mir] optimizing MIR for `d::{closure#0}`
#1 [unused_generic_params] determining which generic parameters are unused by `d::{closure#0}`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0792`.
```

</p>
</details>

### LINKED ISSUE #129462: ICE when combining `asm_const` and `const_refs_to_static`
I suspect the compiler continues in an inconsistent state for too long after emitting the (correct) error message.

related issues

- https://github.com/rust-lang/rust/issues/93332 (will be stable in 1.82.0)
- https://github.com/rust-lang/rust/issues/119618
- https://github.com/rust-lang/rust/issues/128183
- https://github.com/rust-lang/rust/issues/128464
- https://github.com/rust-lang/rust/pull/125558 implemented the `asm_const` error messages

### Code

Note that this code should not compile today. Pointer types are not allowed in the `asm!`  `const` expression, only integer types are.

```Rust
#![feature(const_refs_to_static)]
use std::arch::asm;
use std::ptr::addr_of;

extern "C" {
    static FOO: usize;
}

#[no_mangle]
fn my_asm_wrapper() {
    unsafe { asm!("mov {},eax", const addr_of!(FOO)) };
}
```
https://godbolt.org/z/3fv5E6E4v,

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.82.0-dev
LLVM version: 19.1.0
```

specifically commit b5723af3457b9cd3795eeb97e9af2d34964854f2

### Error output

```
error: invalid type for `const` operand
  --> src/lib.rs:11:33
   |
11 |     unsafe { asm!("mov {},eax", const addr_of!(FOO)) };
   |                                 ^^^^^^-------------
   |                                       |
   |                                       is a `*const usize`
   |
   = help: `const` operands must be of an integer type
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/type_check/mod.rs:388:75:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x75b6b631ac8a - trace
                               at /home/folkertdev/rust/rust/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x75b6b631ac8a - trace_unsynchronized<std::backtrace::{impl#4}::create::{closure_env#0}>
                               at /home/folkertdev/rust/rust/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x75b6b631ac8a - create
                               at /home/folkertdev/rust/rust/library/std/src/backtrace.rs:331:13
   3:     0x75b6b631abe5 - std::backtrace::Backtrace::force_capture::h55f1d030995ccfbc
                               at /home/folkertdev/rust/rust/library/std/src/backtrace.rs:312:9
   4:     0x75b6b6d7b22b - {closure#0}
                               at /home/folkertdev/rust/rust/compiler/rustc_driver_impl/src/lib.rs:1435:25
   5:     0x75b6b6d7b22b - call<(&(dyn core::ops::function::Fn<(&std::panic::PanicHookInfo), Output=()> + core::marker::Send + core::marker::Sync), &std::panic::PanicHookInfo), rustc_driver_impl::install_ice_hook::{closure_env#0}, alloc::alloc::Global>
                               at /home/folkertdev/rust/rust/library/alloc/src/boxed.rs:2164:9
   6:     0x75b6b62e78ec - rust_panic_with_hook
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:805:13
   7:     0x75b6b6316a60 - {closure#0}
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:664:13
   8:     0x75b6b63169e9 - std::sys::backtrace::__rust_end_short_backtrace::hacdcf7d91e673461
                               at /home/folkertdev/rust/rust/library/std/src/sys/backtrace.rs:170:18
   9:     0x75b6b62e735b - begin_panic_handler
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:662:5
  10:     0x75b6b62e3f73 - panic_fmt
                               at /home/folkertdev/rust/rust/library/core/src/panicking.rs:74:14
  11:     0x75b6b62e3ffc - panic
                               at /home/folkertdev/rust/rust/library/core/src/panicking.rs:148:5
  12:     0x75b6b62e3d89 - core::option::unwrap_failed::h093eca03bc597622
                               at /home/folkertdev/rust/rust/library/core/src/option.rs:2015:5
  13:     0x75b6b7d766cb - unwrap<rustc_middle::ty::Ty>
                               at /home/folkertdev/rust/rust/library/core/src/option.rs:965:21
  14:     0x75b6b7d766cb - visit_const_operand
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/type_check/mod.rs:388:34
  15:     0x75b6b7ec5e0f - super_terminator<rustc_borrowck::type_check::TypeVerifier>
  16:     0x75b6b7ec5e0f - visit_terminator<rustc_borrowck::type_check::TypeVerifier>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/mir/visit.rs:120:17
  17:     0x75b6b7ec5e0f - super_basic_block_data<rustc_borrowck::type_check::TypeVerifier>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/mir/visit.rs:313:21
  18:     0x75b6b7ec5e0f - visit_basic_block_data<rustc_borrowck::type_check::TypeVerifier>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/mir/visit.rs:88:17
  19:     0x75b6b7ec5e0f - super_body<rustc_borrowck::type_check::TypeVerifier>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/mir/visit.rs:1035:13
  20:     0x75b6b7d74176 - visit_body
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/type_check/mod.rs:470:9
  21:     0x75b6b7d74176 - type_check
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/type_check/mod.rs:180:5
  22:     0x75b6b7f153f9 - compute_regions
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/nll.rs:102:9
  23:     0x75b6b7eb8309 - do_mir_borrowck
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/lib.rs:215:9
  24:     0x75b6b7ea3872 - mir_borrowck
                               at /home/folkertdev/rust/rust/compiler/rustc_borrowck/src/lib.rs:125:27
  25:     0x75b6b86b2897 - {closure#0}
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/lib.rs:223:1
  26:     0x75b6b86b2897 - __rust_begin_short_backtrace<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure_env#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:548:18
  27:     0x75b6b86e335c - {closure#2}
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:620:25
  28:     0x75b6b86e335c - call_once<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure_env#2}, (rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>
                               at /home/folkertdev/rust/rust/library/core/src/ops/function.rs:250:5
  29:     0x75b6b8850f6f - {closure#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:360:64
  30:     0x75b6b8850f6f - {closure#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  31:     0x75b6b8850f6f - try_with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:283:12
  32:     0x75b6b8850f6f - with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:260:9
  33:     0x75b6b8947535 - enter_context<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  34:     0x75b6b8947535 - {closure#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/dep_graph/mod.rs:33:13
  35:     0x75b6b8947535 - {closure#0}<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:36
  36:     0x75b6b8947535 - with_context_opt<rustc_middle::ty::context::tls::with_context::{closure_env#0}<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:101:18
  37:     0x75b6b8947535 - with_context<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:5
  38:     0x75b6b8947535 - with_deps<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/dep_graph/mod.rs:30:9
  39:     0x75b6b88415c9 - {closure#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:360:37
  40:     0x75b6b88415c9 - with_task<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>), rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:371:14
  41:     0x75b6b88415c9 - {closure#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:537:13
  42:     0x75b6b88415c9 - {closure#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  43:     0x75b6b88415c9 - try_with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:283:12
  44:     0x75b6b88415c9 - with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:260:9
  45:     0x75b6b8924691 - enter_context<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  46:     0x75b6b8924691 - {closure#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:151:13
  47:     0x75b6b8924691 - {closure#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:134:9
  48:     0x75b6b8924691 - {closure#0}<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:36
  49:     0x75b6b8924691 - with_context_opt<rustc_middle::ty::context::tls::with_context::{closure_env#0}<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:101:18
  50:     0x75b6b8924691 - with_context<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:5
  51:     0x75b6b8924691 - with_related_context<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:125:5
  52:     0x75b6b8924691 - start_query<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:136:9
  53:     0x75b6b8924691 - execute_job_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:526:9
  54:     0x75b6b8924691 - execute_job<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:405:9
  55:     0x75b6b8924691 - try_execute_query<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:357:13
  56:     0x75b6b8632dfc - {closure#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:837:9
  57:     0x75b6b8632dfc - maybe_grow<(rustc_middle::query::erase::Erased<[u8; 8]>, core::option::Option<rustc_query_system::dep_graph::graph::DepNodeIndex>), rustc_query_system::query::plumbing::get_query_incr::{closure_env#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  58:     0x75b6b8632dfc - ensure_sufficient_stack<(rustc_middle::query::erase::Erased<[u8; 8]>, core::option::Option<rustc_query_system::dep_graph::graph::DepNodeIndex>), rustc_query_system::query::plumbing::get_query_incr::{closure_env#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  59:     0x75b6b8632dfc - get_query_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:836:36
  60:     0x75b6b8632dfc - __rust_end_short_backtrace
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:578:21
  61:     0x75b6b6f7ef7a - query_ensure<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/query/plumbing.rs:159:9
  62:     0x75b6b6f7ef7a - mir_borrowck<rustc_span::def_id::LocalDefId>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/query/plumbing.rs:194:9
  63:     0x75b6b6f7ef7a - {closure#0}
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/passes.rs:793:13
  64:     0x75b6b6f7ef7a - {closure#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/hir/map/mod.rs:352:82
  65:     0x75b6b6f7da8e - {closure#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:183:34
  66:     0x75b6b6f7da8e - call_once<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure#0}::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>
                               at /home/folkertdev/rust/rust/library/core/src/panic/unwind_safe.rs:272:9
  67:     0x75b6b6f7da8e - do_call<core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure#0}::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>, ()>
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:554:40
  68:     0x75b6b6f7da8e - try<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure#0}::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>>
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:518:19
  69:     0x75b6b6f7da8e - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure#0}::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>, ()>
                               at /home/folkertdev/rust/rust/library/std/src/panic.rs:345:14
  70:     0x75b6b6f7993c - run<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure#1}::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:29:9
  71:     0x75b6b6f7800e - {closure#1}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:187:21
  72:     0x75b6b6f7800e - for_each<rustc_span::def_id::LocalDefId, rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure#0}::{closure_env#1}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>
                               at /home/folkertdev/rust/rust/library/core/src/slice/iter/macros.rs:254:21
  73:     0x75b6b6f7800e - {closure#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:186:17
  74:     0x75b6b6f7800e - parallel_guard<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in::{closure_env#0}<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:45:15
  75:     0x75b6b6f7800e - par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], rustc_middle::hir::map::{impl#4}::par_body_owners::{closure_env#0}<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/sync/parallel.rs:179:9
  76:     0x75b6b6fd52d3 - par_body_owners<rustc_interface::passes::run_required_analyses::{closure#1}::{closure_env#0}>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/hir/map/mod.rs:352:9
  77:     0x75b6b6fd52d3 - {closure#1}
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/passes.rs:789:9
  78:     0x75b6b6fd52d3 - run<(), rustc_interface::passes::run_required_analyses::{closure_env#1}>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/profiling.rs:753:9
  79:     0x75b6b6fd52d3 - time<(), rustc_interface::passes::run_required_analyses::{closure_env#1}>
                               at /home/folkertdev/rust/rust/compiler/rustc_session/src/utils.rs:16:9
  80:     0x75b6b6f76ac3 - run_required_analyses
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/passes.rs:788:5
  81:     0x75b6b6f76ac3 - analysis
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/passes.rs:839:5
  82:     0x75b6b86cf9a5 - {closure#0}
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/lib.rs:223:1
  83:     0x75b6b86cf9a5 - __rust_begin_short_backtrace<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure_env#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:548:18
  84:     0x75b6b85f7b49 - {closure#2}
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:620:25
  85:     0x75b6b85f7b49 - call_once<rustc_query_impl::query_impl::analysis::dynamic_query::{closure_env#2}, (rustc_middle::ty::context::TyCtxt, ())>
                               at /home/folkertdev/rust/rust/library/core/src/ops/function.rs:250:5
  86:     0x75b6b884e269 - {closure#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:360:64
  87:     0x75b6b884e269 - {closure#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  88:     0x75b6b884e269 - try_with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:283:12
  89:     0x75b6b884e269 - with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:260:9
  90:     0x75b6b8944950 - enter_context<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  91:     0x75b6b8944950 - {closure#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/dep_graph/mod.rs:33:13
  92:     0x75b6b8944950 - {closure#0}<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:36
  93:     0x75b6b8944950 - with_context_opt<rustc_middle::ty::context::tls::with_context::{closure_env#0}<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:101:18
  94:     0x75b6b8944950 - with_context<rustc_middle::dep_graph::{impl#0}::with_deps::{closure_env#0}<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:5
  95:     0x75b6b8944950 - with_deps<rustc_query_system::dep_graph::graph::{impl#4}::with_task::{closure#0}::{closure_env#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>, rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/dep_graph/mod.rs:30:9
  96:     0x75b6b881cd3c - {closure#0}<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:360:37
  97:     0x75b6b881cd3c - with_task<rustc_middle::dep_graph::DepsType, (rustc_query_impl::plumbing::QueryCtxt, rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>), (), rustc_middle::query::erase::Erased<[u8; 1]>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:362:14
  98:     0x75b6b881cd3c - {closure#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:537:13
  99:     0x75b6b881cd3c - {closure#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
 100:     0x75b6b881cd3c - try_with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:283:12
 101:     0x75b6b881cd3c - with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:260:9
 102:     0x75b6b88c6a00 - enter_context<rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:5
 103:     0x75b6b88c6a00 - {closure#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:151:13
 104:     0x75b6b88c6a00 - {closure#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:134:9
 105:     0x75b6b88c6a00 - {closure#0}<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:36
 106:     0x75b6b88c6a00 - with_context_opt<rustc_middle::ty::context::tls::with_context::{closure_env#0}<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:101:18
 107:     0x75b6b88c6a00 - with_context<rustc_middle::ty::context::tls::with_related_context::{closure_env#0}<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:112:5
 108:     0x75b6b88c6a00 - with_related_context<rustc_query_impl::plumbing::{impl#3}::start_query::{closure_env#0}<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>, (rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:125:5
 109:     0x75b6b88c6a00 - start_query<(rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job_incr::{closure_env#2}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:136:9
 110:     0x75b6b88c6a00 - execute_job_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:526:9
 111:     0x75b6b88c6a00 - execute_job<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:405:9
 112:     0x75b6b88c6a00 - try_execute_query<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:357:13
 113:     0x75b6b85f7e14 - {closure#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:837:9
 114:     0x75b6b85f7e14 - maybe_grow<(rustc_middle::query::erase::Erased<[u8; 1]>, core::option::Option<rustc_query_system::dep_graph::graph::DepNodeIndex>), rustc_query_system::query::plumbing::get_query_incr::{closure_env#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 115:     0x75b6b85f7e14 - ensure_sufficient_stack<(rustc_middle::query::erase::Erased<[u8; 1]>, core::option::Option<rustc_query_system::dep_graph::graph::DepNodeIndex>), rustc_query_system::query::plumbing::get_query_incr::{closure_env#0}<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>>
                               at /home/folkertdev/rust/rust/compiler/rustc_data_structures/src/stack.rs:17:5
 116:     0x75b6b85f7e14 - get_query_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                               at /home/folkertdev/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:836:36
 117:     0x75b6b85f7e14 - __rust_end_short_backtrace
                               at /home/folkertdev/rust/rust/compiler/rustc_query_impl/src/plumbing.rs:578:21
 118:     0x75b6b6dbb350 - query_get_at<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/query/plumbing.rs:143:17
 119:     0x75b6b6dbb350 - analysis
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/query/plumbing.rs:421:31
 120:     0x75b6b6dbb350 - analysis
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/query/plumbing.rs:412:17
 121:     0x75b6b6dbb350 - {closure#5}
                               at /home/folkertdev/rust/rust/compiler/rustc_driver_impl/src/lib.rs:448:48
 122:     0x75b6b6dbb350 - {closure#1}<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context.rs:1322:37
 123:     0x75b6b6dbb350 - {closure#0}<rustc_middle::ty::context::{impl#19}::enter::{closure_env#1}<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
 124:     0x75b6b6dbb350 - try_with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_middle::ty::context::{impl#19}::enter::{closure_env#1}<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:283:12
 125:     0x75b6b6dbb350 - with<core::cell::Cell<*const ()>, rustc_middle::ty::context::tls::enter_context::{closure_env#0}<rustc_middle::ty::context::{impl#19}::enter::{closure_env#1}<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/local.rs:260:9
 126:     0x75b6b6dbc876 - enter_context<rustc_middle::ty::context::{impl#19}::enter::{closure_env#1}<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:5
 127:     0x75b6b6dbc876 - enter<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure_env#5}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_middle/src/ty/context.rs:1322:9
 128:     0x75b6b6d899cc - {closure#1}
                               at /home/folkertdev/rust/rust/compiler/rustc_driver_impl/src/lib.rs:448:13
 129:     0x75b6b6d899cc - enter<rustc_driver_impl::run_compiler::{closure#0}::{closure_env#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/queries.rs:210:19
 130:     0x75b6b6dbef3b - {closure#0}
                               at /home/folkertdev/rust/rust/compiler/rustc_driver_impl/src/lib.rs:392:22
 131:     0x75b6b6dbef3b - {closure#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/interface.rs:502:27
 132:     0x75b6b6dbef3b - {closure#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/util.rs:157:13
 133:     0x75b6b6dbef3b - {closure#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/util.rs:107:21
 134:     0x75b6b6dbef3b - set<rustc_span::SessionGlobals, rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
 135:     0x75b6b6d977c5 - create_session_globals_then<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>>
                               at /home/folkertdev/rust/rust/compiler/rustc_span/src/lib.rs:135:5
 136:     0x75b6b6daf216 - {closure#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/compiler/rustc_interface/src/util.rs:106:17
 137:     0x75b6b6daf216 - __rust_begin_short_backtrace<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/sys/backtrace.rs:154:18
 138:     0x75b6b6db5f90 - {closure#0}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/mod.rs:522:17
 139:     0x75b6b6db5f90 - call_once<core::result::Result<(), rustc_span::ErrorGuaranteed>, std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>>
                               at /home/folkertdev/rust/rust/library/core/src/panic/unwind_safe.rs:272:9
 140:     0x75b6b6db5f90 - do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:554:40
 141:     0x75b6b6db5f90 - try<core::result::Result<(), rustc_span::ErrorGuaranteed>, core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>>>
                               at /home/folkertdev/rust/rust/library/std/src/panicking.rs:518:19
 142:     0x75b6b6db5f90 - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/panic.rs:345:14
 143:     0x75b6b6db5f90 - {closure#1}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                               at /home/folkertdev/rust/rust/library/std/src/thread/mod.rs:521:30
 144:     0x75b6b6db5f90 - call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<rustc_interface::util::run_in_thread_with_globals::{closure#0}::{closure_env#0}<rustc_interface::util::run_in_thread_pool_with_globals::{closure_env#0}<rustc_interface::interface::run_compiler::{closure_env#1}<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure_env#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, core::result::Result<(), rustc_span::ErrorGuaranteed>>, ()>
                               at /home/folkertdev/rust/rust/library/core/src/ops/function.rs:250:5
 145:     0x75b6b63049cd - call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
                               at /home/folkertdev/rust/rust/library/alloc/src/boxed.rs:2150:9
 146:     0x75b6b63049cd - call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
                               at /home/folkertdev/rust/rust/library/alloc/src/boxed.rs:2150:9
 147:     0x75b6b62f085a - std::sys::pal::unix::thread::Thread::new::thread_start::hf5af2c4982942030
                               at /home/folkertdev/rust/rust/library/std/src/sys/pal/unix/thread.rs:105:17
 148:     0x75b6b609ca94 - start_thread
                               at ./nptl/pthread_create.c:447:8
 149:     0x75b6b6129c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
 150:                0x0 - <unknown>


rustc version: 1.82.0-dev
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `my_asm_wrapper`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by folkertdev**
fixes https://github.com/rust-lang/rust/issues/129462
fixes #126896
fixes #124164

I think this is a case that was missed in the fix for https://github.com/rust-lang/rust/pull/125558, which inserts a type error in the case of an invalid (that is, non-integer) type being passed to an asm `const` operand.

I'm not 100% sure that `span_mirbug_and_err` is the right macro here, but it is used earlier with `builtin_deref` and seems to do the trick.

r? @lcnr

### CODE REVIEW

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -385,7 +385,14 @@ impl<'a, 'b, 'tcx> Visitor<'tcx> for TypeVerifier<'a, 'b, 'tcx> {
             } else if let Some(static_def_id) = constant.check_static_ptr(tcx) {
                 let unnormalized_ty = tcx.type_of(static_def_id).instantiate_identity();
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs:386]: so the issue here is that `type_of(static_def_id)` is `ty::Error` here which does not have a `builtin_deref`? I would like to instead explicitly check for `unnormalized_ty.has_errors()` or whatever and bail in that case

Comment (folkertdev) [reply compiler/rustc_borrowck/src/type_check/mod.rs:386]: The problem is with `constant.const_.ty()`, not with `unnormalized_ty`

E.g. in the test below, `unnormalized_ty` is `u8`, which is perfectly fine. The type of the constant would be `*const u8`, but earlier logic from https://github.com/rust-lang/rust/pull/125558 turns that type into a type error because it is not an integer type. The error is inserted here https://github.com/Amanieu/rust/blob/eb726a50e65387c348ba56f2416fc3c0b649f95e/compiler/rustc_hir_analysis/src/collect/type_of.rs#L105

Comment (lcnr) [reply compiler/rustc_borrowck/src/type_check/mod.rs:386]: so the issue is that `constant` has type `<type error>` but its value is `ConstValue::Scalar`?

I think we should try to instead also taint the value of the const to be an error :thinking:

Comment (folkertdev) [reply compiler/rustc_borrowck/src/type_check/mod.rs:386]: How does that work? 

Also in the future we'll likely want to be able to use pointers in this position https://github.com/rust-lang/rust/issues/128464 it's just not implemented right now and trying it should not ICE.

Which is to say: changes made now may be reverted when using pointers as asm const operands is properly implemented.

Comment (lcnr) [reply compiler/rustc_borrowck/src/type_check/mod.rs:386]: At some point you create a constant whose type is `ty::Error` but which has an actual value. By also invalidating the value of the constant at this point `if let Some(static_def_id) = constant.check_static_ptr(tcx)` does not get triggered anymore.

Comment (folkertdev) [reply compiler/rustc_borrowck/src/type_check/mod.rs:386]: Sure, I meant more concretely, e.g. here https://github.com/Amanieu/rust/blob/eb726a50e65387c348ba56f2416fc3c0b649f95e/compiler/rustc_hir_analysis/src/collect/type_of.rs#L105 

how does one also invalidate the value? None of the other branches appear to do that

Comment (folkertdev) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: well, I gave this a go. Th current version turns the basic block into a `TerminatorKind::Unreachable`. 

This feels extremely hacky though? more so than catching an unsatisfied assumption in the borrow checker. But maybe I just misunderstand what you mean by "invalidate"? Is there some way to poison a `Const` that I'm missing?

Comment (lcnr) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: yes, the idea would be to use a `ty::ConstKind::Error` as the const value

Comment (folkertdev) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: cool, that looks a lot better!

File: compiler/rustc_mir_build/src/thir/cx/expr.rs [hunk 2]
```diff
@@ -624,12 +624,15 @@ impl<'tcx> Cx<'tcx> {
...
-                            .normalize(tcx, self.param_env);
+                            let def_id = anon_const.def_id.to_def_id();
+                            let const_type = tcx.type_of(def_id).skip_binder();
+                            let value = if let ty::Error(terr) = const_type.kind() {
+                                mir::Const::Ty(const_type, ty::Const::new_error(tcx, *terr))
+                            } else {
+                                mir::Const::identity_unevaluated(tcx, def_id)
+                                    .instantiate_identity()
+                                    .normalize(tcx, self.param_env)
+                            };
```
Comment (lcnr) [inline compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: looking at this I realized that there's something else going on here. The constant starts out as unevaluated and we are able to evaluate it successfully even though it uses a type error as the expected type. We tend to bail in const eval if typeck encountered a type error: https://github.com/rust-lang/rust/blob/9b82580c7347f800c2550e6719e4218a60a80b28/compiler/rustc_const_eval/src/interpret/eval_context.rs#L255-L266

So imo the actual issue is that we don't taint the MIR body even though its expected return type is a type error. We should eagerly taint the infcx using `set_tainted_by_errors` in `typeck_with_fallback` if the expected type is an error. cc @oli-obk as you may be aware of a more general approach to taint the MIR body here

Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: Any types written to the typecktables will taint the typeck result. Unfortunately this doesn't include the signature, as that is derived separately sometimes and may independently have errors. Not sure yet what the best way to solve this is, but finding any way and adding a FIXME and issue with the tainting project set is fine

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: followup questions

you talk about the signature and the expected type, but it looks like in the code of `typeck_with_fallback` only the `if` branch explicitly uses the signature, and the else branch has a variable called `expected_type`. 

https://github.com/rust-lang/rust/blob/d6c8169c186ab16a3404cd0d0866674018e8a19e/compiler/rustc_hir_typeck/src/lib.rs#L152-L183

So, in which of the two branches should what be tainted? E.g. is this in the else branch enough?

```rust
// FIXME: link to tainting issue
if let ty::Error(terr) = expected_type.kind() {
    fcx.infcx.set_tainted_by_errors(*terr);
}
```

Or is the `fn_sig` in the if branch really the expected type (it's the type of the definition, which gets checked against the type at the usage site)?

Also, there is no project or label named "tainting" at the moment? nor "taint", does it have a different name?

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: I don't think there's a proper project for it, correctly tainting the MIR body is necessary to avoid followup ICE when trying to evaluate malformed bodies and this is something @oli-obk has recently been spending some significant effort on.

The `fn_sig` is the expected type when type checking a function. For consts, statics, and enum discriminants the expected type is from the `else` branch. So yes, for this concrete issue only tainting in the else branch is enough. Please use `expected_type.error_reported()` instead of matching on `kind` to also handle e.g. references to `<type error>`

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: There is a github project for it https://github.com/orgs/rust-lang/projects/51

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 3]
```diff
@@ -167,6 +167,11 @@ fn typeck_with_fallback<'tcx>(
 
         let expected_type = fcx.normalize(body.value.span, expected_type);
 
+        // FIXME error tainting <https://github.com/rust-lang/rust/issues/129952>
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/lib.rs:170]:
```suggestion
        // FIXME(#129952): We probably want a more principled approach here.
```

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/lib.rs:170]: mostly just the `FIXME(#129952)` I don't care too much about the actual fixme :blush:

File: compiler/rustc_mir_build/src/thir/cx/expr.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: this should not be unnecessary?

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: you mean that the logic added in earlier commits of this PR can be removed here? If so, that does not work, and again triggers the original ICE

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/type_check/mod.rs:388:75:
called `Option::unwrap()` on a `None` value
```

**Comment by oli-obk** [comment]
I think this should be fixing a buch of known other ICEs, too. Try running the `crashes` test suite

**Comment by folkertdev** [comment]
no luck there 

```
> ./x test --keep-stage 1 tests/crashes/

running 232 tests
........................................................................................  88/232
........................................................................................ 176/232
........................................................

test result: ok. 232 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.63s
```

File: compiler/rustc_mir_build/src/thir/cx/expr.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: then we are still not tainting enough :thinking:

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: Ah no, we only error in `type_of`, which is computed by using `typeck`. So `typeck` succeeds with `&whatever` as the return type, and we then only replace it with a type error in `type_of` :thinking:

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: so we should do it in https://github.com/rust-lang/rust/blob/master/compiler/rustc_borrowck/src/universal_regions.rs#L583 instead, or after calling that function :thinking:

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: Well, I'm kind of lost there. There no longer is a type to check for "is it an error" at the call site of that function? and within it, it's not so obvious either in the `DefiningTy::Const(self.mir_def.to_def_id(), args)` case.

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: sorry, we only look at the actual type in `fn compute_inputs_and_output`

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: right, well this still does not taint enough

```rust
            DefiningTy::Const(def_id, _) => {
                // For a constant body, there are no inputs, and one
                // "output" (the type of the constant).
                assert_eq!(self.mir_def.to_def_id(), def_id);
                let ty = tcx.type_of(self.mir_def).instantiate_identity();

                // FIXME(#129952): We probably want a more principled approach here.
                if let Err(terr) = ty.error_reported() {
                    self.infcx.set_tainted_by_errors(terr);
                }

                let ty = indices.fold_to_region_vids(tcx, ty);

                ty::Binder::dummy(tcx.mk_type_list(&[ty]))
            }
```

I checked that this block is reached, but I still get that ICE mentioned earlier.

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: is `set_tainted_by_errors` triggered here?

Comment (lcnr) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: ah, we don't propagate the `tainted_by_errors` of the `infcx` in `MirBorrowckCtxt::emit_errors`.

https://github.com/rust-lang/rust/blob/842d6fc32e3d0d26bb11fbe6a2f6ae2afccc06cb/compiler/rustc_borrowck/src/lib.rs#L2525 this should start out with `self.infcx.tainted_by_errors()'

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: yes, e.g. if I add some debug prints

```rust
    // FIXME(#129952): We probably want a more principled approach here.
    if let Err(terr) = ty.error_reported() {
        dbg!("tainting the thing", def_id, &defining_ty);
        self.infcx.set_tainted_by_errors(terr);
    }
```

I get

```
error: invalid type for `const` operand
  --> /home/folkertdev/rust/rust/tests/ui/asm/const-refs-to-static.rs:12:19
   |
LL | global_asm!("{}", const addr_of!(FOO));
   |                   ^^^^^^-------------
   |                         |
   |                         is a `*const u8`
   |
   = help: `const` operands must be of an integer type

[compiler/rustc_borrowck/src/universal_regions.rs:802:21] "tainting the thing" = "tainting the thing"
[compiler/rustc_borrowck/src/universal_regions.rs:802:21] def_id = DefId(0:11 ~ const_refs_to_static[9a35]::{global_asm#0}::{constant#0})
[compiler/rustc_borrowck/src/universal_regions.rs:802:21] &defining_ty = Const(
    DefId(0:11 ~ const_refs_to_static[9a35]::{global_asm#0}::{constant#0}),
    [],
)
error: invalid type for `const` operand
  --> /home/folkertdev/rust/rust/tests/ui/asm/const-refs-to-static.rs:17:25
   |
LL |     unsafe { asm!("{}", const addr_of!(FOO)) };
   |                         ^^^^^^-------------
   |                               |
   |                               is a `*const u8`
   |
   = help: `const` operands must be of an integer type

[compiler/rustc_borrowck/src/universal_regions.rs:802:21] "tainting the thing" = "tainting the thing"
[compiler/rustc_borrowck/src/universal_regions.rs:802:21] def_id = DefId(0:12 ~ const_refs_to_static[9a35]::inline::{constant#0})
[compiler/rustc_borrowck/src/universal_regions.rs:802:21] &defining_ty = Const(
    DefId(0:12 ~ const_refs_to_static[9a35]::inline::{constant#0}),
    [],
)
thread 'rustc' panicked at compiler/rustc_borrowck/src/type_check/mod.rs:388:75:
called `Option::unwrap()` on a `None` value
```

Comment (folkertdev) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:635]: cool that works. Is the most recent location for the tain still the correct one then? or should it happen at one of the earlier places?

also this does now fix two crashes from `tests/crashes`

File: tests/ui/polymorphization/taint.rs [hunk 4]
```diff
@@ -1,6 +1,7 @@
-//@ known-bug: rust-lang/rust#126896
 //@ compile-flags: -Zvalidate-mir -Zinline-mir=yes
 
+// reported as rust-lang/rust#126896
```
Comment (lcnr) [inline tests/ui/polymorphization/taint.rs:3]: this doesn't belong in `polymorphization`, please put it into the `type_alias_impl_trait` folder

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 5]
```diff
@@ -798,6 +799,12 @@ impl<'cx, 'tcx> UniversalRegionsBuilder<'cx, 'tcx> {
                 // "output" (the type of the constant).
                 assert_eq!(self.mir_def.to_def_id(), def_id);
                 let ty = tcx.type_of(self.mir_def).instantiate_identity();
+
+                // FIXME(#129952): We probably want a more principled approach here.
+                if let Err(terr) = ty.error_reported() {
+                    self.infcx.set_tainted_by_errors(terr);
+                }
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/universal_regions.rs:806]: I think that maybe we want to do it for all signatures, i.e. assign this match to a variable and then check whether that variable has any `error_reported`. I expect that to fix even more issues 😁 

I am otherwise quite happy with this change

File: tests/ui/polymorphization/taint.rs (hunk 4 above)
Comment (folkertdev) [reply tests/ui/polymorphization/taint.rs:3]: Will do. I based that choice on https://github.com/rust-lang/rust/issues/126896#issuecomment-2186182800 saying that the `-Zpolymorphization` is the loadbearing part of that test.

Comment (lcnr) [reply tests/ui/polymorphization/taint.rs:3]: `-Zpolymorphization` isn't enabled in this test 😅 I am confused by @lqd's comment, maybe it's missing a 'not'? 😁

But alright, given that context I am actually happy that you've looked at the original issue to figure out wher to put this test. Thank you!

Comment (folkertdev) [reply tests/ui/polymorphization/taint.rs:3]: so, is there a more appropriate place for this test to live, or is it good where it is?

File: compiler/rustc_borrowck/src/universal_regions.rs (hunk 5 above)
Comment (folkertdev) [reply compiler/rustc_borrowck/src/universal_regions.rs]: no further crashes are fixed by that change. I did rename https://github.com/rust-lang/rust/issues/129952  to reflect that the tainting now occurs in a different place.

File: tests/ui/polymorphization/taint.rs (hunk 4 above)
Comment (lcnr) [reply tests/ui/polymorphization/taint.rs:3]: given that it triggers with `-Zvalidate-mir` it isn't related to polymorphization, just triggered by it. THe underlying bug is a TAIT one

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 6]
```diff
@@ -688,7 +689,8 @@ impl<'cx, 'tcx> UniversalRegionsBuilder<'cx, 'tcx> {
         defining_ty: DefiningTy<'tcx>,
     ) -> ty::Binder<'tcx, &'tcx ty::List<Ty<'tcx>>> {
         let tcx = self.infcx.tcx;
-        match defining_ty {
+
+        let bound_ty = match defining_ty {
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/universal_regions.rs:693]:
```suggestion
        let inputs_and_output = match defining_ty {
```
it's a list of types

File: tests/ui/polymorphization/taint.rs (hunk 4 above)
Comment (folkertdev) [reply tests/ui/polymorphization/taint.rs]: allright, moved to `tests/ui/type-alias-impl-trait/`

**Comment by lcnr** [comment]
thanks for your patience ❤️ 

@bors r+ rollup
