### PR TITLE
Remove -Zoom=panic

### LINKED ISSUE #43596: oom=panic knob
Several users who are invested in the "thread is a task" model that Rust was originally designed around have expressed a desire to unwind in the case of OOM. Specifically each task has large and unpredictable memory usage, and tearing down the first task that encounters OOM is considered a reasonable strategy.

Aborting on OOM is considered unacceptable because it would be expensive to discard all the work that the other tasks have managed to do.

We already (accidentally?) specified that all allocators can panic on OOM, including the global one, with the introduction of generic allocators on collections. So in theory no one "should" be relying on the default `oom=abort` semantics. This knob would only affect the default global allocator. Presumably there would just be a function somewhere in the stdlib which is cfg'd to be a panic or abort based on this flag?

This is not a replacement for proper fallible allocation handling routines requested in #29802 because most of the potential users of **that** API build with `panic=abort`. Also the requesters of **this** API are unwilling to go through the effort to ensure all their dependents are using fallible allocations everywhere.

I am dubious on this API but I'm filling an issue so that it's written down and everyone who wants it has a place to go and assert that it is in fact good and desirable.

### LINKED ISSUE #126683: `-Zoom=panic` double panic due to panicking allocating
We had an abort in production from `fn begin_panic_handler`, specifically `FormatStringPayload`, allocating during an OoM panic, triggering a second OoM panic and thus abort.

https://github.com/rust-lang/rust/blob/a07f3eb43acc5df851e15176c7081a900a30a4d7/library/std/src/panicking.rs#L593-L615

From that file it looks like there may be others also. Perhaps it's possible to avoid them on the OoM panic path.

cc:
* #43596
* #88098
* #115974
* https://github.com/rust-lang/unsafe-code-guidelines/issues/506

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (a07f3eb43 2024-04-11)
binary: rustc
commit-hash: a07f3eb43acc5df851e15176c7081a900a30a4d7
commit-date: 2024-04-11
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.3
```

<details><summary>Backtrace</summary>
<p>

```text
// target = wasm32-unknown-unknown

std::panicking::rust_panic_with_hook::he5ab6644a2777339
        at <unknown>
std::panicking::begin_panic_handler::{{closure}}::hbc8949711eb93f07
        at <unknown>
std::sys_common::backtrace::__rust_end_short_backtrace::h43c6e6030cfac424
        at src/sys_common/backtrace.rs
rust_begin_unwind
        at <unknown>
core::panicking::panic_fmt::hd059f920eb86b234
        at src/panicking.rs
std::alloc::default_alloc_error_hook::hf29909cb78062dee
        at <unknown>
__rg_oom
        at src/alloc.rs
__rust_alloc_error_handler
        at <unknown>
alloc::alloc::handle_alloc_error::h77f60f5703455990
        at src/alloc.rs
alloc::raw_vec::handle_error::h2651e03894002f2d
        at src/raw_vec.rs
alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle::h010686df1ee1f672
        at <unknown>
<alloc::string::String as core::fmt::Write>::write_str::h78dc7b49e79e749d.23038
        at lib/rustlib/src/rust/library/alloc/src/string.rs
core::fmt::write::hebf5ad877658ea5c
        at <unknown>
<std::panicking::begin_panic_handler::FormatStringPayload as core::panic::PanicPayload>::get::h8680c05bc1165a6c
        at <unknown>
std::panicking::rust_panic_with_hook::he5ab6644a2777339
        at <unknown>
std::panicking::begin_panic_handler::{{closure}}::hbc8949711eb93f07
        at <unknown>
std::sys_common::backtrace::__rust_end_short_backtrace::h43c6e6030cfac424
        at src/sys_common/backtrace.rs
rust_begin_unwind
        at <unknown>
core::panicking::panic_fmt::hd059f920eb86b234
        at src/panicking.rs
std::alloc::default_alloc_error_hook::hf29909cb78062dee
        at <unknown>
__rg_oom
        at src/alloc.rs
__rust_alloc_error_handler
        at <unknown>
alloc::alloc::handle_alloc_error::h77f60f5703455990
        at src/alloc.rs
<generic_btree::map::binding::Binding<K,V> as core::clone::Clone>::clone::h5d7cc23d7389cd6e
        at <unknown>

```

</p>
</details>

### PR DESCRIPTION
**Pull request by bjorn3**
There are major questions remaining about the reentrancy that this allows. It doesn't have any users on github outside of a single project that uses it in a panic=abort project to show backtraces. It can still be emulated through `#[alloc_error_handler]` or `set_alloc_error_hook` depending on if you use the standard library or not. And finally it makes it harder to do various improvements to the allocator shim.

With this PR the sole remaining symbol in the allocator shim that is not effectively emulating weak symbols is the symbol that prevents skipping the allocator shim on stable even when it would otherwise be empty because libstd + `#[global_allocator]` is used.

Closes https://github.com/rust-lang/rust/issues/43596
Fixes https://github.com/rust-lang/rust/issues/126683

### CODE REVIEW

File: library/std/src/alloc.rs [hunk 1]
```diff
@@ -344,38 +344,84 @@ pub fn take_alloc_error_hook() -> fn(Layout) {
...
+    // regular panic and thus can invoke a user-defined panic hook, executing arbitrary
+    // user-defined code.
+
+    static PREV_ALLOC_FAILURE: AtomicBool = AtomicBool::new(false);
+    if PREV_ALLOC_FAILURE.swap(true, Ordering::Relaxed) {
+        // Don't try to print a backtrace if a previous alloc error happened. This likely means
+        // there is not enough memory to print a backtrace, although it could also mean that two
+        // threads concurrently run out of memory.
+        rtprintpanic!(
+            "memory allocation of {} bytes failed while handling another memory allocation error\n",
```
Comment (RalfJung) [inline library/std/src/alloc.rs]: This would also be printed when two threads have an allocation error at the same time, right?

Comment (bjorn3) [reply library/std/src/alloc.rs]: True as stated in the comment above. Do you have a suggestion for a better message?

Comment (RalfJung) [reply library/std/src/alloc.rs]: We could just not guess and emit only the part we know for sure
```suggestion
            "memory allocation of {} bytes failed\n",
```

Comment (bjorn3) [reply library/std/src/alloc.rs]: If the second allocation failure happens right after the first allocation failure writes the atomic without the first thread getting scheduled further, only the message here would be printed. If the message is the same in both cases, that could be confusing why no backtrace gets printed.

Comment (bjorn3) [reply library/std/src/alloc.rs]: Maybe
```suggestion
            "memory allocation of {} bytes failed\nskipping backtrace printing to avoid potential recursion\n",
```
?

Comment (RalfJung) [reply library/std/src/alloc.rs]: That sounds good.

**Comment by bjorn3** [comment]
You can still panic in the alloc error hook you register with `std::alloc::set_alloc_error_hook` with this PR (or the `#[alloc_error_handler]` if you don't use libstd). Any stabilization of this is blocked on the same reentrancy soundness questions as `-Zoom=panic`. The only allocation errors that `set_alloc_error_hook` doesn't cover that `-Zoom=panic` does is for allocations in code running before user code runs, but panics there can't be recovered from anyway.

**Comment by bjorn3** [comment]
> You can still panic in the alloc error hook you register with std::alloc::set_alloc_error_hook with this PR

In fact I changed the existing `-Zoom=panic` test to test this behavior: tests/ui/panics/alloc_error_hook-unwind.rs
