### PR TITLE
rustdoc: avoid including impl blocks with filled-in generics

### LINKED ISSUE #94937: rustdoc shows auto impls for `[u8]`
https://doc.rust-lang.org/nightly/std/marker/trait.Send.html#impl-Send-80

this is pretty confusing as there also exists an auto impl for `[T]` https://doc.rust-lang.org/nightly/std/marker/trait.Send.html#impl-Send-429

I expect that rustdoc incorrectly treats the `impl [u8]` impl as a distinct type or something like this... not completely sure

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #94937

# Before

image

# After

image

### CODE REVIEW

File: src/librustdoc/passes/collect_trait_impls.rs [hunk 1]
```diff
@@ -81,8 +81,33 @@ crate fn collect_trait_impls(mut krate: Crate, cx: &mut DocContext<'_>) -> Crate
...
+                    // Rustdoc currently uses these `impl` block as a source of
+                    // the `Ty`, as well as the `ParamEnv`, `SubstsRef`, and
+                    // `Generics`. To avoid relying on the `impl` block, these
+                    // things would need to be created from wholecloth, in a
+                    // form that is valid for use in type inference.
+                    let ty = tcx.type_of(def_id);
+                    match ty.kind() {
+                        ty::Slice(ty) => matches!(ty.kind(), ty::Param(..)),
+                        ty::Ref(_region, ty, _mutbl) => matches!(ty.kind(), ty::Param(..)),
+                        ty::RawPtr(ty::TypeAndMut { ty, .. }) => matches!(ty.kind(), ty::Param(..)),
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_trait_impls.rs:106]: Couldn't it be rewritten as:

```suggestion
                        ty::Slice(ty)
                        | ty::Ref(_, ty, _)
                        | ty::RawPtr(ty::TypeAndMut { ty, .. }) => matches!(ty.kind(), ty::Param(..)),
```

?

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks! r=me once CI is green.
