### PR TITLE
Prefer regions with an `external_name` in `approx_universal_upper_bound`

### LINKED ISSUE #75785: Lifetime error points to wrong reference in async fn return
```rust
pub async fn async_fn(x: &mut i32) -> (&i32, &i32) {
    let y = &*x;
    *x += 1;
    (&32, y)
}
```

Output ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6c4944a18f49286c6eee7fc4e7322f1b)):

```
error[E0506]: cannot assign to `*x` because it is borrowed
 --> src/lib.rs:3:5
  |
2 |     let y = &*x;
  |             --- borrow of `*x` occurs here
3 |     *x += 1;
  |     ^^^^^^^ assignment to borrowed `*x` occurs here
4 |     (&32, y)
  |     -------- returning this value requires that `*x` is borrowed for `'1`
5 | }
  | - return type of generator is (&'1 i32, &i32)

```

The `'1` lifetime name should be given to the second reference in the tuple. 

@rustbot modify labels: C-bug A-async-await A-diagnostics A-lifetimes T-compiler

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #75785

When displaying a MIR borrowcheck error, we may need to find an upper
bound for a region, which gives us a region to point to in the error
message. However, a region might outlive multiple distinct universal
regions, in which case the only upper bound is 'static

To try to display a meaningful error message, we compute an
'approximate' upper bound by picking one of the universal regions.
Currently, we pick the region with the lowest index - however, this
caused us to produce a suboptimal error message in issue #75785

This PR `approx_universal_upper_bound` to prefer regions with an
`external_name`. This causes us to prefer regions from function
arguments/upvars, which seems to lead to a nicer error message in some
cases.

### CODE REVIEW

File: src/test/ui/async-await/issue-75785-confusing-named-region.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// edition:2018
+//
+// Regression test for issue #75785
+// Tests that we don't point to a confusing named
+// region when emitting a diagnostic
+
+pub fn async_fn(x: &mut i32) -> (&i32, &i32) {
```
Comment (SNCPlay42) [inline src/test/ui/async-await/issue-75785-confusing-named-region.rs:7]: This needs to be `async` to repro the issue, doesn't it? The output for this is unchanged from the current output.

Comment (Aaron1011) [reply src/test/ui/async-await/issue-75785-confusing-named-region.rs:7]: Oops, thanks!

**Comment by Aaron1011** [comment]
@estebank Are there any changes that you'd like me to make?

File: src/test/ui/async-await/issue-75785-confusing-named-region.stderr [hunk 2]
```diff
@@ -0,0 +1,15 @@
+error[E0506]: cannot assign to `*x` because it is borrowed
+  --> $DIR/issue-75785-confusing-named-region.rs:9:5
+   |
+LL | pub async fn async_fn(x: &mut i32) -> (&i32, &i32) {
+   |                          - let's call the lifetime of this reference `'1`
```
Comment (SNCPlay42) [inline src/test/ui/async-await/issue-75785-confusing-named-region.stderr:5]: Now that the highlight points at the argument instead of the return type, this fixes #74072.

This means this PR will change the output of the test I added in #76468, so it will need rebasing on top of that.

**Comment by Aaron1011** [comment]
ping @estebank for review or reassignment

**Comment by tmandry** [comment]
@bors r+

Thanks!
