### PR TITLE
Suggest that expressions that look like const generic arguments should be enclosed in brackets

### LINKED ISSUE #70753: const_generics: parsing fails with const expression in type parameter
I tried this code:

```rust
#![feature(const_generics)]

struct Foo<const N: usize>([(); N]);
type A = Foo<std::mem::size_of::<u8>()>;
```

It fails to parse with
```
error: expected one of `!`, `+`, `,`, `::`, or `>`, found `(`
  --> src/lib.rs:12:37
   |
 4 | type A = Foo<std::mem::size_of::<u8>()>;
   |                                     ^ expected one of `!`, `+`, `,`, `::`, or `>`
```

I assume that this _is_ supposed to work though, since this code is accepted:

```rust
const X: usize = std::mem::size_of::<u8>();
type A = Foo<X>;
```

### Meta

`rustc --version --verbose`:
```
1.44.0-nightly (2020-04-02 537ccdf3ac44c8c7a8d3)
```

### PR DESCRIPTION
**Pull request by varkor**
I pulled out the changes for const expressions from https://github.com/rust-lang/rust/pull/71592 (without the trait object diagnostic changes) and made some small changes; the implementation is @estebank's.

We're also going to want to make some changes separately to account for trait objects (they result in poor diagnostics, as is evident from one of the test cases here), such as an adaption of https://github.com/rust-lang/rust/pull/72273.

Fixes https://github.com/rust-lang/rust/issues/70753.

r? @petrochenkov

### CODE REVIEW

File: src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs [hunk 1]
```diff
@@ -0,0 +1,55 @@
+#![feature(min_const_generics)]
```
Comment (estebank) [inline src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:1]: I would like to see how this interacts now with the "invalid turbofish" recovery (just removing `::` from all cases) to make sure it doesn't break down.

**Review by estebank — COMMENTED** [review]
Thanks for picking this up @varkor!

File: src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+}
+fn b() {
+    // FIXME(const_generics): these diagnostics are awful, because trait objects without `dyn` were
+    // a terrible mistake.
+    foo::<BAR + BAR>();
+    //~^ ERROR expected trait, found constant `BAR`
+    //~| ERROR expected trait, found constant `BAR`
+    //~| ERROR wrong number of const arguments: expected 1, found 0
+    //~| ERROR wrong number of type arguments: expected 0, found 1
+    //~| WARN trait objects without an explicit `dyn` are deprecated
```
[the remark this answers is not in the document]
Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:18]: I was wondering whether to make a similar suggestion. It would be so much simpler if we didn't have to deal with implicit trait objects.

File: src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs (hunk 1 above)
Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:1]: Good point: I'll add some test cases.

Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:1]: At the moment turbofish takes priority and it simply suggests `::` be added. So it would take two attempts for a user to fix both problems, but I think that's okay.

Comment (estebank) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:1]: That's good to know.

**Comment by petrochenkov** [comment]
I'll get to this next weekend most likely.

File: compiler/rustc_parse/src/parser/path.rs [hunk 3]
```diff
@@ -397,12 +398,114 @@ impl<'a> Parser<'a> {
...
+                                continue;
+                            }
+                        }
+                        Err(mut err) => {
+                            args.push(arg);
+                            // We will emit a more generic error later.
+                            err.delay_as_bug();
+                        }
+                    }
+                }
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:432]: Could you move this code to `diagnostics.rs`?

File: compiler/rustc_parse/src/parser/path.rs [hunk 4]
```diff
@@ -397,12 +398,114 @@ impl<'a> Parser<'a> {
...
+                    return Ok(GenericArg::Const(AnonConst { id: ast::DUMMY_NODE_ID, value }));
+                }
+            }
+            Err(mut err) => {
+                err.cancel();
+            }
+        }
+        *self = snapshot;
+        Err(err)
+    }
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:507]: Could you move this code to `diagnostics.rs`?

File: compiler/rustc_parse/src/parser/path.rs [hunk 5]
```diff
@@ -479,38 +582,68 @@ impl<'a> Parser<'a> {
...
+                    )
+                    .multipart_suggestion(
+                        "enclose the `const` expression in braces",
+                        vec![
+                            (expr.span.shrink_to_lo(), "{ ".to_string()),
+                            (expr.span.shrink_to_hi(), " }".to_string()),
+                        ],
+                        Applicability::MachineApplicable,
+                    )
+                    .emit();
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/path.rs:633]: And this piece of code perhaps belongs to `diagnostics.rs` as well.

File: src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces-without-turbofish.rs [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+const BAR: usize = 42;
+
+fn a() {
+    foo<BAR + 3>(); //~ ERROR comparison operators cannot be chained
+}
+fn b() {
+    foo<BAR + BAR>(); //~ ERROR comparison operators cannot be chained
+}
+fn c() {
+    foo<3 + 3>(); //~ ERROR comparison operators cannot be chained
```
Comment (estebank) [inline src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces-without-turbofish.rs:14]: Is the missing closing brace here on purpose?

Comment (varkor) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces-without-turbofish.rs:14]: Nope, that was accidental. Thanks.

**Comment by varkor** [comment]
@petrochenkov: I've moved the functions to `diagnostics.rs`.

File: src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (lcnr) [reply src/test/ui/const-generics/min_const_generics/const-expression-suggest-missing-braces.rs:18]: There was a discussion on zulip about this: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/bare_trait_objects.202021

Afaict the weak consensus seems to be `deny` in edition 2021 and hard error in 2024. Looking at this error we might have a stronger case to already hard error in the 2021 edition

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 7]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+    /// almost certainly a const argument, so we always offer a suggestion.
+    pub fn handle_unambiguous_unbraced_const_arg(&mut self) -> PResult<'a, P<Expr>> {
+        // FIXME(const_generics): to distinguish between idents for types and consts,
+        // we should introduce a GenericArg::Ident in the AST and distinguish when
+        // lowering to the HIR. For now, idents for const args are not permitted.
+        let start = self.token.span;
+        let expr = self.parse_expr_res(Restrictions::CONST_EXPR, None).map_err(|mut err| {
+            err.span_label(
+                start.shrink_to_lo(),
+                "while parsing a `const` generic argument starting here",
```
Comment (camelid) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1828]: Perhaps remove the backticks around "const"? It doesn't seem to add much and it's inconsistent with this error: `wrong number of const arguments: expected 1, found 0`.

```suggestion
                "while parsing a const generic argument starting here",
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 8]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+            ast::ExprKind::Unary(ast::UnOp::Neg, expr) => match &expr.kind {
+                ast::ExprKind::Lit(_) => true,
+                _ => false,
+            },
+            _ => false,
+        };
+        if !valid_const {
+            self.struct_span_err(
+                expr.span,
+                "expressions must be enclosed in braces to be used as `const` generic \
```
Comment (camelid) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1843]: Same here.

```suggestion
                "expressions must be enclosed in braces to be used as const generic \
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 9]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+                    arguments",
+            )
+            .multipart_suggestion(
+                "enclose the `const` expression in braces",
```
Comment (camelid) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1847]:
```suggestion
                "enclose the const expression in braces",
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 10]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+            Ok(expr) => {
+                if token::Comma == self.token.kind || self.token.kind.should_end_const_arg() {
+                    // Avoid the following output by checking that we consumed a full const arg:
+                    // help: expressions must be enclosed in braces to be used as `const` generic
+                    //       arguments
+                    //    |
+                    // LL |     let sr: Vec<{ (u32, _, _) = vec![] };
+                    //    |                 ^                      ^
+                    err.multipart_suggestion(
+                        "expressions must be enclosed in braces to be used as `const` generic \
```
Comment (camelid) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1908]:
```suggestion
                        "expressions must be enclosed in braces to be used as const generic \
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 11]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+        return Ok(false); // Don't continue.
+    }
+
+    /// Handle a generic const argument that had not been enclosed in braces, and suggest enclosing
+    /// it braces. In this situation, unlike in `handle_ambiguous_unbraced_const_arg`, this is
+    /// almost certainly a const argument, so we always offer a suggestion.
+    pub fn handle_unambiguous_unbraced_const_arg(&mut self) -> PResult<'a, P<Expr>> {
+        // FIXME(const_generics): to distinguish between idents for types and consts,
+        // we should introduce a GenericArg::Ident in the AST and distinguish when
+        // lowering to the HIR. For now, idents for const args are not permitted.
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1823]: This FIXME is outdated.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 12]
```diff
@@ -1,13 +1,15 @@
 use super::ty::AllowPlus;
-use super::{BlockMode, Parser, PathStyle, SemiColonMode, SeqSep, TokenExpectType, TokenType};
+use super::{
+    BlockMode, Parser, PathStyle, Restrictions, SemiColonMode, SeqSep, TokenExpectType, TokenType,
+};
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/diagnostics.rs:4]: Nit: could you avoid multi-line imports here and below?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 13]
```diff
@@ -1774,4 +1776,153 @@ impl<'a> Parser<'a> {
...
+            err.span_label(
+                start.shrink_to_lo(),
+                "while parsing a `const` generic argument starting here",
+            );
+            err
+        })?;
+        let valid_const = match &expr.kind {
+            ast::ExprKind::Block(_, _) | ast::ExprKind::Lit(_) => true,
+            ast::ExprKind::Unary(ast::UnOp::Neg, expr) => match &expr.kind {
+                ast::ExprKind::Lit(_) => true,
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1835]: Ok, looks like this is a part of the reference parser logic, so it needs to be moved back from `diagnostics.rs`.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 14]
```diff
@@ -359,6 +359,18 @@ impl<'a> Parser<'a> {
     /// Also performs recovery for `and` / `or` which are mistaken for `&&` and `||` respectively.
     fn check_assoc_op(&self) -> Option<Spanned<AssocOp>> {
         let (op, span) = match (AssocOp::from_token(&self.token), self.token.ident()) {
+            // When parsing const expressions, stop parsing when encountering `>`.
+            (
+                Some(
+                    AssocOp::ShiftRight
+                    | AssocOp::Greater
+                    | AssocOp::GreaterEqual
+                    | AssocOp::AssignOp(token::BinOpToken::Shr),
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/expr.rs:368]: Could you add a test in which these tokens are encountered in a const arg expression?

**Comment by varkor** [comment]
@petrochenkov: I've added some more tests. The error messages in these cases are not ideal, but they're particularly difficult to handle well.

**Comment by estebank** [comment]
> The error messages in these cases are not ideal, but they're particularly difficult to handle well.

Handling `>>` will be hard but we _could_ potentially keep track of how many `<` we've seen to decide whether to detect it as bitshift or closing type param (we _already_ have recovery for too many closing `>` in type params so it would have to interact nicely with it), **but** I don't think it is necessary just yet as the suggestion does give you enough of a clue as to what to do.

**Comment by petrochenkov** [comment]
r=me with commits squashed.
