### PR TITLE
Code block invalid html tag lint

### LINKED ISSUE #79095: Invalid "unclosed HTML tag" lint
On this doc comment:

``````rust
//! ```no_run
//! extern crate gtk;
//! extern crate gio;
//!
//! // To import all needed traits.
//! use gtk::prelude::*;
//! use gio::prelude::*;
//!
//! use std::env;
//!
//! fn main() {
//!     let uiapp = gtk::Application::new(Some("org.gtkrsnotes.demo"),
//!                                       gio::ApplicationFlags::FLAGS_NONE)
//!                                  .expect("Application::new failed");
//!     uiapp.connect_activate(|app| {
//!         // We create the main window.
//!         let win = gtk::ApplicationWindow::new(app);
//!
//!         // Then we set its size and a title.
//!         win.set_default_size(320, 200);
//!         win.set_title("Basic example");
//!
//!         // Don't forget to make all widgets visible.
//!         win.show_all();
//!     });
//!     uiapp.run(&env::args().collect::<Vec<_>>());
//! }
//! ```
``````

We receive the warning:

```
warning: unclosed HTML tag `Vec`
  --> gtk/src/lib.rs:80:41
   |
80 | //!     uiapp.run(&env::args().collect::<Vec<_>>());
   |                                         ^^^^
   |
   = note: `-W invalid-html-tags` implied by `-W rustdoc`
```

Or it shouldn't because it's in a code block.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #79095

r? @jyn514

### CODE REVIEW

File: src/librustdoc/passes/html_tags.rs [hunk 1]
```diff
@@ -196,14 +196,17 @@ impl<'a, 'tcx> DocFolder for InvalidHtmlTagsLinter<'a, 'tcx> {
...
             let mut tags = Vec::new();
             let mut is_in_comment = None;
+            let mut in_code_block = false;
 
             let p = Parser::new_ext(&dox, opts()).into_offset_iter();
 
             for (event, range) in p {
                 match event {
-                    Event::Html(text) | Event::Text(text) => {
+                    Event::Start(Tag::CodeBlock(_)) => in_code_block = true,
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:205]: Can code blocks be nested? I'm imagining something like

````markdown
# Markdown syntax

```rust
// nested code block
uiapp.run(&env::args().collect::<Vec<_>>());
```
````

Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:205]: It's not supported by pulldown-cmark as it seems but I added the test just in case.

**Comment by jyn514** [comment]
@bors r+

Thanks for the quick fix!
