### PR TITLE
Fix closure migration suggestion when the body is a macro. 

### LINKED ISSUE #87955: rust_2021_incompatible_closure_captures suggestion expands macro
```rust
#![warn(rust_2021_incompatible_closure_captures)]

fn main() {
    let a = ("hey".to_string(), "123".to_string());
    let _ = || dbg!(a.0);
}
```
produces:
```
help: add a dummy let to cause `a` to be fully captured
  |
29~         { let _ = &a; match $val {
29+             tmp => {
29+                 $crate::eprintln!("[{}:{}] {} = {:#?}",
30+                     $crate::file!(), $crate::line!(), $crate::stringify!($val), &tmp);
30+                 tmp
30+             }
...
```

It expanded the `dbg!()` macro. This only happens when the macro invocation is the entire body of the closure.

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes https://github.com/rust-lang/rust/issues/87955

Before:
```
warning: changes to closure capture in Rust 2021 will affect drop order
 --> src/main.rs:5:13
  |
5 |     let _ = || panic!(a.0);
  |             ^^^^^^^^^^---^
  |                       |
  |                       in Rust 2018, closure captures all of `a`, but in Rust 2021, it only captures `a.0`
6 | }
  | - in Rust 2018, `a` would be dropped here, but in Rust 2021, only `a.0` would be dropped here alongside the closure
  |

help: add a dummy let to cause `a` to be fully captured
  |
20~     ($msg:expr $(,)?) => ({ let _ = &a; 
21+         $crate::rt::begin_panic($msg)
22~     }),
  |
```

After:
```
warning: changes to closure capture in Rust 2021 will affect drop order
 --> src/main.rs:5:13
  |
5 |     let _ = || panic!(a.0);
  |             ^^^^^^^^^^---^
  |                       |
  |                       in Rust 2018, closure captures all of `a`, but in Rust 2021, it only captures `a.0`
6 | }
  | - in Rust 2018, `a` would be dropped here, but in Rust 2021, only `a.0` would be dropped here alongside the closure
  |
help: add a dummy let to cause `a` to be fully captured
  |
5 |     let _ = || { let _ = &a; panic!(a.0) };
  |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 1]
```diff
@@ -644,7 +644,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+
+                    let mut closure_body_span = self.tcx.hir().span(body_id.hir_id);
+
+                    // If the body was entirely expanded from a macro
+                    // invocation, as the body is not contained inside the
+                    // closure span. In that case, we walk up the expansion
+                    // until we find the span before the expansion.
+                    while !closure_body_span.is_dummy() && !closure_span.contains(closure_body_span) {
+                        closure_body_span = closure_body_span.parent().unwrap_or(DUMMY_SP);
+                    }
```
[the remark this answers is not in the document]
Comment (m-ou-se) [reply compiler/rustc_typeck/src/check/upvar.rs:656]: That wouldn't work if the entire closure is expanded from a macro_rules. It'd expand too far, all the way to the root, instead of only until the place where the closure is.

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 2]
```diff
@@ -644,7 +644,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                     diagnostics_builder.note("for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/disjoint-capture-in-closures.html>");
-                    let closure_body_span = self.tcx.hir().span(body_id.hir_id);
+
+                    let mut closure_body_span = self.tcx.hir().span(body_id.hir_id);
+
+                    // If the body was entirely expanded from a macro
+                    // invocation, as the body is not contained inside the
+                    // closure span. In that case, we walk up the expansion
+                    // until we find the span before the expansion.
+                    while !closure_body_span.is_dummy() && !closure_span.contains(closure_body_span) {
```
Comment (Aaron1011) [inline compiler/rustc_typeck/src/check/upvar.rs:654]: If we end with a dummy span, then the overall diagnostic will end up worse than it currently is. Can you restore `closure_body_span` to its original value if the loop ends up setting it to `DUMMY_SP`?

Comment (m-ou-se) [reply compiler/rustc_typeck/src/check/upvar.rs:654]: I kept the dummy span for the suggestion part. Otherwise `.span_to_snippet` is going to return the wrong snippet and the suggestion will be wrong and confusing. The fallback span now uses the entire closure, which chas the highest chance of pointing to the place where modifications need to be made.

File: src/test/ui/closures/2229_closure_analysis/migrations/macro.stderr [hunk 3]
```diff
@@ -0,0 +1,24 @@
+error: changes to closure capture in Rust 2021 will affect drop order
+  --> $DIR/macro.rs:10:13
+   |
+LL |     let _ = || dbg!(a.0);
+   |             ^^^^^^^^---^
+   |                     |
+   |                     in Rust 2018, closure captures all of `a`, but in Rust 2021, it only captures `a.0`
+...
+LL | }
+   | - in Rust 2018, `a` would be dropped here, but in Rust 2021, only `a.0` would be dropped here alongside the closure
```
Comment (Aaron1011) [inline src/test/ui/closures/2229_closure_analysis/migrations/macro.stderr:10]: Pre-existing: I think saying 'as part as the closure' would make more sense than 'alongside the closure'.

**Comment by Aaron1011** [comment]
r=me, unless you want to change the note I mentioned in this PR as well.

File: src/test/ui/closures/2229_closure_analysis/migrations/macro.stderr (hunk 3 above)
Comment (m-ou-se) [reply src/test/ui/closures/2229_closure_analysis/migrations/macro.stderr:10]: https://github.com/rust-lang/rust/pull/87984
