### PR TITLE
Fix incorrect suggestion for uninitialized binding in pattern

### LINKED ISSUE #120634: Wrong suggestion for variable initialization
### Code

```Rust
struct Struct {
    e: i32
}

fn main() {
    let (a, b , c , d , e);

    let _f: i32;

    // (a, b) = (1, 2);
    // [c, .., d, _] = [1, 2, 3, 4, 5];
    // Struct { e, .. } = Struct { e: 5 };

    assert_eq!([1, 2, 1, 4, 5], [a, b, c, d, e]);
}
```

### Current output

```Shell
--> src/main.rs:14:34
   |
6  |     let (a , b , c , d , e);
   |          - binding declared here but left uninitialized
...
14 |     assert_eq!([1, 2, 1, 4, 5], [a, b, c, d, e]);
   |                                  ^ `a` used here but it isn't initialized
   |
help: consider assigning a value
   |
6  |     let (a = 0 , b , c , d , e);
   |            +++
```

### Desired output

```Shell
the suggestion: let (a = 0 , b , c , d , e); is contrary to Rust syntax.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: aarch64-apple-darwin
release: 1.74.1
LLVM version: 17.0.4
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #120634

### CODE REVIEW

File: tests/ui/borrowck/borrowck-uninit-binding-suggestion.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// regression test for #120634
```
Comment (Nilstrieb) [inline tests/ui/borrowck/borrowck-uninit-binding-suggestion.rs:1]: there's gotta be a test for this error already somewhere, right? could you try finding it and extending it instead of creating a new one?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -613,7 +613,12 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
                     if self.sugg_span.is_some() {
                         return;
                     }
-                    if let hir::StmtKind::Local(hir::Local { span, ty, init: None, .. }) = &ex.kind
+
+                    // FIXME: We make sure that this is a normal binding and not a destructuring assignment,
```
Comment (Nilstrieb) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:617]: this is not destructuring assignment, it's just a normal binding that's not at the top level

**Comment by michaelwoerister** [comment]
Sorry for the delay! I forgot about this PR.

It looks good to me. Thanks for the co-review, @Nilstrieb!

@bors r+ rollup
