### PR TITLE
Fix ICE with unsized type in const pattern

### LINKED ISSUE #87046: Strongly-typed str-wrapper const results in ICE in pattern match
### Code

```Rust
#![feature(const_fn_union)]

#[derive(PartialEq, Eq)]
#[repr(transparent)]
pub struct Username(str);

pub const ROOT_USER: &Username = Username::from_str("root");

impl Username {
    pub const fn from_str(raw: &str) -> &Self {
        union Transmute<'a> {
            raw: &'a str,
            typed: &'a Username,
        }
        
        unsafe { Transmute { raw }.typed }
    }
    
    pub const fn as_str(&self) -> &str {
        &self.0
    }
    
    pub fn is_root(&self) -> bool {
        match self {
            ROOT_USER => true,
            _ => false,
        }
    }
}
```

Changing `Username::is_root` and introducing `ROOT_USER_STR` compiles successfully:
```Rust
pub const ROOT_USER_STR: &str = ROOT_USER.as_str();

impl Username {
    …
    pub fn is_root(&self) -> bool {
        match self.as_str() {
            ROOT_USER_STR => true,
            _ => false,
        }
    }
}
```

### Meta

`rustc --version --verbose` (Was from the Rust Playground):
```
1.55.0-nightly (2021-07-08 8b87e85394aa583b01e5)
```

### Error output

```
error: internal compiler error: compiler/rustc_mir/src/const_eval/mod.rs:198:18: type Username should not have metadata, but had Meta(0x0000000000000004)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (8b87e8539 2021-07-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [deref_const] deref constant
#1 [check_match] match-checking `<impl at src/main.rs:9:1: 31:2>::is_root`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `playground`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1035:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_mir::const_eval::deref_const
   8: rustc_query_system::query::plumbing::get_query_impl
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::deref_const
  10: rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::recur
  11: rustc_infer::infer::InferCtxtBuilder::enter
  12: rustc_mir_build::thir::pattern::const_to_pat::<impl rustc_mir_build::thir::pattern::PatCtxt>::const_to_pat
  13: rustc_mir_build::thir::pattern::PatCtxt::lower_path
  14: rustc_mir_build::thir::pattern::PatCtxt::lower_pattern
  15: rustc_mir_build::thir::pattern::check_match::MatchVisitor::lower_pattern
  16: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  17: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  18: rustc_mir_build::thir::pattern::check_match::check_match
  19: rustc_query_system::query::plumbing::get_query_impl
  20: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_match
  21: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  22: rustc_session::utils::<impl rustc_session::session::Session>::time
  23: rustc_interface::passes::analysis
  24: rustc_query_system::query::plumbing::get_query_impl
  25: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: rustc_interface::interface::create_compiler_and_run
  29: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #87046. The `deref_const()` query currently contains the following check:
https://github.com/rust-lang/rust/blob/e9a387d6cf5961a7f2dcb671da3147bd413355c4/compiler/rustc_mir/src/const_eval/mod.rs#L191-L204

i.e. this will cause an ICE for every unsized type except slices. An error is reported with my changes if such a type is used as a const pattern (this should not be a breaking change, since so far, this has caused an ICE).

### CODE REVIEW

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 1]
```diff
@@ -490,17 +490,29 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
...
-                    // we fall back to a const pattern. If we do not do this, we may end up with
-                    // a !structural-match constant that is not of reference type, which makes it
-                    // very hard to invoke `PartialEq::eq` on it as a fallback.
-                    let val = match self.recur(tcx.deref_const(self.param_env.and(cv)), false) {
-                        Ok(subpattern) => PatKind::Deref { subpattern },
-                        Err(_) => PatKind::Constant { value: cv },
-                    };
-                    self.behind_reference.set(old);
-                    val
+                    if !pointee_ty.is_sized(tcx.at(span), param_env) {
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: that certainly avoids the ICE, but we could also make such patterns legal. I think we should. @rust-lang/wg-const-eval what do you think about these?

Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: This always does `span_err` or `delay_span_bug`...  how does this make anything legal?

Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: I said "we *could* ...", I'm fine doing this PR, it changes and ICE to an error, but why should the code in the new test not be permitted? It seems perfectly alright to me

Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: I'm not familiar enough with pattern matching code to comment on this.

But I'd prefer we port that code to valtrees first, then I will be a lot more confident that what that code does makes sense in my mental model of rustc. :)

Comment (kim) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: @oli-obk What would be a good way to direct attention to this? I would find it incredibly useful to be able to use newtypes around `str` as const patterns.

Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:493]: Valtrees are being worked on right now, once we have them, this becomes trivial to do and we can ask T-lang whether they think this should br supported, too
