### PR TITLE
Deny non-lifetime bound vars in `for<..> ||` closure binders

### LINKED ISSUE #108181: ICE: non_lifetime_binders `unexpected bound ty in binder: BoundTy {...}`
### Code

```Rust
#![feature(non_lifetime_binders)]

fn main()  {
    for<main> || -> & main  {};
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17)
binary: rustc
commit-hash: f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3
commit-date: 2023-02-17
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> 2f364877ae32a51855925609c897ffa9f739c835.rs:2:21
  |
2 |     for<main> || -> & main  {};
  |                     ^ explicit lifetime name needed here

error[E0658]: `for<...>` binders for closures are experimental
 --> 2f364877ae32a51855925609c897ffa9f739c835.rs:2:5
  |
2 |     for<main> || -> & main  {};
  |     ^^^^^^^^^
  |
  = note: see issue #97362 <https://github.com/rust-lang/rust/issues/97362> for more information
  = help: add `#![feature(closure_lifetime_binder)]` to the crate attributes to enable
  = help: consider removing `for<...>`

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(non_lifetime_binders)
  |         ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #1 <https://github.com/rust-lang/rust/issues/1> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: type parameter `main` should have an upper camel case name
 --> 2f364877ae32a51855925609c897ffa9f739c835.rs:2:9
  |
2 |     for<main> || -> & main  {};
  |         ^^^^ help: convert the identifier to upper camel case: `Main`
  |
  = note: `#[warn(non_camel_case_types)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

error: internal compiler error: /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/compiler/rustc_middle/src/ty/fold.rs:306:33: unexpected bound ty in binder: BoundTy { var: 0, kind: Param(DefId(0:5 ~ 2f364877ae32a51855925609c897ffa9f739c835[5b1e]::main::{closure#0}::main), "main") }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/compiler/rustc_errors/src/lib.rs:1642:9
stack backtrace:
   0:     0x7fe41bb6aa5a - std::backtrace_rs::backtrace::libunwind::trace::hebe09041f884c65d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe41bb6aa5a - std::backtrace_rs::backtrace::trace_unsynchronized::h546f6c63cbbce5a9
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe41bb6aa5a - std::sys_common::backtrace::_print_fmt::h2559cb0cfed7a617
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fe41bb6aa5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1fb4eaaaafa2d72a
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe41bbca9ae - core::fmt::write::hbaef4432b3c9d07b
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/core/src/fmt/mod.rs:1232:17
   5:     0x7fe41bb5ae05 - std::io::Write::write_fmt::h1f8dce362441faaa
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/io/mod.rs:1684:15
   6:     0x7fe41bb6a825 - std::sys_common::backtrace::_print::hc0e92ab849a4f4e1
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fe41bb6a825 - std::sys_common::backtrace::print::h878cd11684ebdec3
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fe41bb6d59f - std::panicking::default_hook::{{closure}}::h2ea8a6875aa6312d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:267:22
   9:     0x7fe41bb6d2db - std::panicking::default_hook::h9e42277a84072188
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:286:9
  10:     0x7fe41ee6e7b4 - <rustc_driver_impl[afa3c304d692170b]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[ebab21900c9c0a2]::ops::function::FnOnce<(&core[ebab21900c9c0a2]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fe41bb6dddd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2c34f129ed413128
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:2002:9
  12:     0x7fe41bb6dddd - std::panicking::rust_panic_with_hook::h4c799b8c4fc0a70b
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:692:13
  13:     0x7fe41f4274a1 - std[dc63ca99f82ce43d]::panicking::begin_panic::<rustc_errors[faa449d960b5ce55]::ExplicitBug>::{closure#0}
  14:     0x7fe41f41f116 - std[dc63ca99f82ce43d]::sys_common::backtrace::__rust_end_short_backtrace::<std[dc63ca99f82ce43d]::panicking::begin_panic<rustc_errors[faa449d960b5ce55]::ExplicitBug>::{closure#0}, !>
  15:     0x7fe41f379fe6 - std[dc63ca99f82ce43d]::panicking::begin_panic::<rustc_errors[faa449d960b5ce55]::ExplicitBug>
  16:     0x7fe41f41ed96 - std[dc63ca99f82ce43d]::panic::panic_any::<rustc_errors[faa449d960b5ce55]::ExplicitBug>
  17:     0x7fe41f41d906 - <rustc_errors[faa449d960b5ce55]::HandlerInner>::bug::<&alloc[d840872249f3dc84]::string::String>
  18:     0x7fe41f41d5d0 - <rustc_errors[faa449d960b5ce55]::Handler>::bug::<&alloc[d840872249f3dc84]::string::String>
  19:     0x7fe41f484b1b - rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt::<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}
  20:     0x7fe41f4842da - rustc_middle[6caff671bb338453]::ty::context::tls::with_opt::<rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fe41f4842a6 - rustc_middle[6caff671bb338453]::ty::context::tls::with_context_opt::<rustc_middle[6caff671bb338453]::ty::context::tls::with_opt<rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fe41f484a66 - rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt::<rustc_span[1010a352e5466fad]::span_encoding::Span>
  23:     0x7fe41d141083 - rustc_middle[6caff671bb338453]::util::bug::bug_fmt
  24:     0x7fe41f0d445c - <rustc_middle[6caff671bb338453]::ty::context::TyCtxt>::replace_late_bound_regions_uncached::<rustc_middle[6caff671bb338453]::ty::sty::FnSig, <rustc_middle[6caff671bb338453]::ty::context::TyCtxt>::replace_late_bound_regions<rustc_middle[6caff671bb338453]::ty::sty::FnSig, <rustc_middle[6caff671bb338453]::ty::context::TyCtxt>::erase_late_bound_regions<rustc_middle[6caff671bb338453]::ty::sty::FnSig>::{closure#0}>::{closure#0}>::{closure#0}
  25:     0x7fe41d292e90 - <rustc_middle[6caff671bb338453]::ty::fold::BoundVarReplacer<rustc_middle[6caff671bb338453]::ty::fold::FnMutDelegate> as rustc_type_ir[b1287c9e7106c79]::fold::FallibleTypeFolder<rustc_middle[6caff671bb338453]::ty::context::TyCtxt>>::try_fold_ty
  26:     0x7fe41d51c1a7 - <rustc_middle[6caff671bb338453]::ty::Ty as rustc_type_ir[b1287c9e7106c79]::fold::TypeSuperFoldable<rustc_middle[6caff671bb338453]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[6caff671bb338453]::ty::fold::BoundVarReplacer<rustc_middle[6caff671bb338453]::ty::fold::FnMutDelegate>>
  27:     0x7fe41d51b865 - <&rustc_middle[6caff671bb338453]::ty::list::List<rustc_middle[6caff671bb338453]::ty::Ty> as rustc_type_ir[b1287c9e7106c79]::fold::TypeFoldable<rustc_middle[6caff671bb338453]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[6caff671bb338453]::ty::fold::BoundVarReplacer<rustc_middle[6caff671bb338453]::ty::fold::FnMutDelegate>>
  28:     0x7fe41d28319b - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::closure_sigs
  29:     0x7fe41d2811c2 - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::check_expr_closure
  30:     0x7fe41d1fedce - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7fe41d224e45 - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::check_block_with_expected
  32:     0x7fe41d1fb52e - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  33:     0x7fe41d5b689b - <rustc_hir_typeck[59924f8822ff3497]::fn_ctxt::FnCtxt>::check_return_expr
  34:     0x7fe41d5aeb12 - rustc_hir_typeck[59924f8822ff3497]::check::check_fn
  35:     0x7fe41d598ef2 - <rustc_hir_typeck[59924f8822ff3497]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[59924f8822ff3497]::typeck_with_fallback<rustc_hir_typeck[59924f8822ff3497]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[6caff671bb338453]::ty::typeck_results::TypeckResults>
  36:     0x7fe41d58da16 - rustc_hir_typeck[59924f8822ff3497]::typeck
  37:     0x7fe41d58c113 - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::typeck, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  38:     0x7fe41e5f0f8b - rustc_data_structures[cd995ba5556f5758]::sync::par_for_each_in::<&[rustc_span[1010a352e5466fad]::def_id::LocalDefId], <rustc_middle[6caff671bb338453]::hir::map::Map>::par_body_owners<rustc_hir_typeck[59924f8822ff3497]::typeck_item_bodies::{closure#0}>::{closure#0}>
  39:     0x7fe41e5f0dcf - rustc_hir_typeck[59924f8822ff3497]::typeck_item_bodies
  40:     0x7fe41e46fca3 - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::typeck_item_bodies, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  41:     0x7fe41e86e59b - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::typeck_item_bodies
  42:     0x7fe41d3136a3 - <rustc_session[66793dd6b8780a4a]::session::Session>::time::<(), rustc_hir_analysis[257f64c795d1d076]::check_crate::{closure#7}>
  43:     0x7fe41d3106a2 - rustc_hir_analysis[257f64c795d1d076]::check_crate
  44:     0x7fe41d306062 - rustc_interface[686dab9608bc6033]::passes::analysis
  45:     0x7fe41e663d92 - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::analysis, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  46:     0x7fe41e867e2a - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::analysis
  47:     0x7fe41e080303 - <rustc_interface[686dab9608bc6033]::queries::QueryResult<&rustc_middle[6caff671bb338453]::ty::context::GlobalCtxt>>::enter::<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}::{closure#2}::{closure#3}>
  48:     0x7fe41e07f4d4 - <rustc_interface[686dab9608bc6033]::interface::Compiler>::enter::<rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}::{closure#2}, core[ebab21900c9c0a2]::result::Result<core[ebab21900c9c0a2]::option::Option<rustc_interface[686dab9608bc6033]::queries::Linker>, rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  49:     0x7fe41e07a6f4 - rustc_span[1010a352e5466fad]::with_source_map::<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  50:     0x7fe41e07a204 - <scoped_tls[d487b98c36b0d138]::ScopedKey<rustc_span[1010a352e5466fad]::SessionGlobals>>::set::<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  51:     0x7fe41e079902 - std[dc63ca99f82ce43d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[686dab9608bc6033]::util::run_in_thread_pool_with_globals<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  52:     0x7fe41e0796ac - <<std[dc63ca99f82ce43d]::thread::Builder>::spawn_unchecked_<rustc_interface[686dab9608bc6033]::util::run_in_thread_pool_with_globals<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#1} as core[ebab21900c9c0a2]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7fe41bb77c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9fd36c4a0ba5b15d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
  54:     0x7fe41bb77c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd37d267854c7434f
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
  55:     0x7fe41bb77c63 - std::sys::unix::thread::Thread::new::thread_start::h1ff24d5a09f2a8be
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7fe41b907bb5 - <unknown>
  57:     0x7fe41b989d90 - <unknown>
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(non_lifetime_binders)

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0637, E0658.
For more information about an error, try `rustc --explain E0637`.
```

</p>
</details>

### LINKED ISSUE #108184: ICE: `unexpected generic param: GenericParam`: `closure_lifetime_binder` + `non_lifetime_binders`
### Code

```Rust
#![feature(closure_lifetime_binder)]
#![feature(non_lifetime_binders)]
#![crate_type = "lib"]

fn T() {
    for<T> || -> () {};
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17)
binary: rustc
commit-hash: f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3
commit-date: 2023-02-17
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> a371a027afa2856063889cf433200478158d8c47.rs:2:12
  |
2 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #1 <https://github.com/rust-lang/rust/issues/1> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `T` is never used
 --> a371a027afa2856063889cf433200478158d8c47.rs:5:4
  |
5 | fn T() {
  |    ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function `T` should have a snake case name
 --> a371a027afa2856063889cf433200478158d8c47.rs:5:4
  |
5 | fn T() {
  |    ^ help: convert the identifier to snake case: `t`
  |
  = note: `#[warn(non_snake_case)]` on by default

warning: unused closure that must be used
 --> a371a027afa2856063889cf433200478158d8c47.rs:6:5
  |
6 |     for<T> || -> () {};
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: closures are lazy and do nothing unless called
  = note: `#[warn(unused_must_use)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: unexpected generic param: GenericParam { hir_id: HirId(DefId(0:3 ~ a371a027afa2856063889cf433200478158d8c47[2a77]::T).4), def_id: DefId(0:5 ~ a371a027afa2856063889cf433200478158d8c47[2a77]::T::{closure#0}::T), name: Plain(T#0), span: a371a027afa2856063889cf433200478158d8c47.rs:6:9: 6:10 (#0), pure_wrt_drop: false, kind: Type { default: None, synthetic: false }, colon_span: None }
 --> a371a027afa2856063889cf433200478158d8c47.rs:6:9
  |
6 |     for<T> || -> () {};
  |         ^
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
             2: <rustc_hir_typeck::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
             3: <rustc_hir_typeck::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
             4: <rustc_hir_typeck::fn_ctxt::FnCtxt>::resolve_type_vars_in_body
             5: <rustc_hir_typeck::inherited::InheritedBuilder>::enter::<rustc_hir_typeck::typeck_with_fallback<rustc_hir_typeck::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle::ty::typeck_results::TypeckResults>
             6: rustc_hir_typeck::typeck
             7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::typeck, rustc_query_impl::plumbing::QueryCtxt>
             8: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_typeck::typeck_item_bodies::{closure#0}>::{closure#0}>
             9: rustc_hir_typeck::typeck_item_bodies
            10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
            11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
            12: <rustc_session::session::Session>::time::<(), rustc_hir_analysis::check_crate::{closure#7}>
            13: rustc_hir_analysis::check_crate
            14: rustc_interface::passes::analysis
            15: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            17: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#3}>
            18: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            19: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            21: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            22: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
            24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
            25: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys/unix/thread.rs:108:17
            26: <unknown>
            27: <unknown>


note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors; 4 warnings emitted
```

</p>
</details>

### LINKED ISSUE #108192: ICE: `no type for node`, non_lifetime_binders + closure_lifetime_binder
### Code

```Rust
#![feature(closure_lifetime_binder)]
#![feature(non_lifetime_binders)]
#![crate_type = "lib"]

fn i32() {
    for<const N: i32> || -> () {};
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (9aa5c24b7 2023-02-17)
binary: rustc
commit-hash: 9aa5c24b7d763fb98d998819571128ff2eb8a3ca
commit-date: 2023-02-17
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> b4e3e6e357ce50d67ce4898edcd83ad3abd98189.rs:2:12
  |
2 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #1 <https://github.com/rust-lang/rust/issues/1> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `i32` is never used
 --> b4e3e6e357ce50d67ce4898edcd83ad3abd98189.rs:5:4
  |
5 | fn i32() {
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: unused closure that must be used
 --> b4e3e6e357ce50d67ce4898edcd83ad3abd98189.rs:6:5
  |
6 |     for<const N: i32> || -> () {};
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: closures are lazy and do nothing unless called
  = note: `#[warn(unused_must_use)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/typeck_results.rs:375:13: node_type: no type for node HirId(DefId(0:3 ~ b4e3e6e357ce50d67ce4898edcd83ad3abd98189[98c0]::i32).4) (type `i32`)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/compiler/rustc_errors/src/lib.rs:1642:9
stack backtrace:
   0:     0x7f0ad3b6aa5a - std::backtrace_rs::backtrace::libunwind::trace::hf4a48a91b677bc8d
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f0ad3b6aa5a - std::backtrace_rs::backtrace::trace_unsynchronized::h52302266f2c9e2af
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f0ad3b6aa5a - std::sys_common::backtrace::_print_fmt::h00aaca457620efb0
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f0ad3b6aa5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d9f10455e422cbd
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f0ad3bca9ae - core::fmt::write::h065585aa0e682316
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f0ad3b5ae05 - std::io::Write::write_fmt::h54937c0abd9a719d
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/io/mod.rs:1684:15
   6:     0x7f0ad3b6a825 - std::sys_common::backtrace::_print::h0141838be2b7fc59
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f0ad3b6a825 - std::sys_common::backtrace::print::h422705047959e0cf
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f0ad3b6d59f - std::panicking::default_hook::{{closure}}::h04c227824228bc2c
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:267:22
   9:     0x7f0ad3b6d2db - std::panicking::default_hook::h1a17cdb165515d8b
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:286:9
  10:     0x7f0ad6e60224 - rustc_driver_impl[9b756e32c0d38789]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f0ad3b6dddd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7593a5eec671dafe
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/alloc/src/boxed.rs:2002:9
  12:     0x7f0ad3b6dddd - std::panicking::rust_panic_with_hook::h815681ed9ae37db1
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:692:13
  13:     0x7f0ad741c361 - std[92d2792449a90a80]::panicking::begin_panic::<rustc_errors[c2c7aee1e156d1f6]::ExplicitBug>::{closure#0}
  14:     0x7f0ad7413fd6 - std[92d2792449a90a80]::sys_common::backtrace::__rust_end_short_backtrace::<std[92d2792449a90a80]::panicking::begin_panic<rustc_errors[c2c7aee1e156d1f6]::ExplicitBug>::{closure#0}, !>
  15:     0x7f0ad736d676 - std[92d2792449a90a80]::panicking::begin_panic::<rustc_errors[c2c7aee1e156d1f6]::ExplicitBug>
  16:     0x7f0ad74128d6 - std[92d2792449a90a80]::panic::panic_any::<rustc_errors[c2c7aee1e156d1f6]::ExplicitBug>
  17:     0x7f0ad74127c6 - <rustc_errors[c2c7aee1e156d1f6]::HandlerInner>::bug::<&alloc[77fdffdb8c1c6cb]::string::String>
  18:     0x7f0ad7412490 - <rustc_errors[c2c7aee1e156d1f6]::Handler>::bug::<&alloc[77fdffdb8c1c6cb]::string::String>
  19:     0x7f0ad747972b - rustc_middle[b5631d71f72482ee]::util::bug::opt_span_bug_fmt::<rustc_span[65551fbbac8b0f76]::span_encoding::Span>::{closure#0}
  20:     0x7f0ad7478eea - rustc_middle[b5631d71f72482ee]::ty::context::tls::with_opt::<rustc_middle[b5631d71f72482ee]::util::bug::opt_span_bug_fmt<rustc_span[65551fbbac8b0f76]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f0ad7478eb6 - rustc_middle[b5631d71f72482ee]::ty::context::tls::with_context_opt::<rustc_middle[b5631d71f72482ee]::ty::context::tls::with_opt<rustc_middle[b5631d71f72482ee]::util::bug::opt_span_bug_fmt<rustc_span[65551fbbac8b0f76]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f0ad7479676 - rustc_middle[b5631d71f72482ee]::util::bug::opt_span_bug_fmt::<rustc_span[65551fbbac8b0f76]::span_encoding::Span>
  23:     0x7f0ad5135973 - rustc_middle[b5631d71f72482ee]::util::bug::bug_fmt
  24:     0x7f0ad52e9668 - <rustc_middle[b5631d71f72482ee]::ty::typeck_results::TypeckResults>::node_type
  25:     0x7f0ad55ee564 - <rustc_privacy[e4ab76b639d1a822]::TypePrivacyVisitor as rustc_hir[c7d6b754e828c199]::intravisit::Visitor>::visit_ty
  26:     0x7f0ad4f202f7 - <rustc_privacy[e4ab76b639d1a822]::TypePrivacyVisitor as rustc_hir[c7d6b754e828c199]::intravisit::Visitor>::visit_expr
  27:     0x7f0ad4f1f89b - <rustc_privacy[e4ab76b639d1a822]::TypePrivacyVisitor as rustc_hir[c7d6b754e828c199]::intravisit::Visitor>::visit_expr
  28:     0x7f0ad55ed8ff - rustc_hir[c7d6b754e828c199]::intravisit::walk_item::<rustc_privacy[e4ab76b639d1a822]::TypePrivacyVisitor>
  29:     0x7f0ad4fbf4db - rustc_privacy[e4ab76b639d1a822]::check_mod_privacy
  30:     0x7f0ad641ffbf - rustc_query_system[2b3be6912aef78d5]::query::plumbing::try_execute_query::<rustc_query_impl[a3402ef8368c6710]::queries::check_mod_privacy, rustc_query_impl[a3402ef8368c6710]::plumbing::QueryCtxt>
  31:     0x7f0ad685b3fd - <rustc_query_impl[a3402ef8368c6710]::Queries as rustc_middle[b5631d71f72482ee]::ty::query::QueryEngine>::check_mod_privacy
  32:     0x7f0ad631d978 - rustc_data_structures[6722e53fadb3415d]::sync::par_for_each_in::<&[rustc_hir[c7d6b754e828c199]::hir_id::OwnerId], <rustc_middle[b5631d71f72482ee]::hir::map::Map>::par_for_each_module<rustc_interface[828b714f964ce1da]::passes::analysis::{closure#6}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}>
  33:     0x7f0ad631d70e - <rustc_session[1c603fdce436292a]::session::Session>::time::<(), rustc_interface[828b714f964ce1da]::passes::analysis::{closure#6}::{closure#2}::{closure#0}>
  34:     0x7f0ad52fc89a - <rustc_session[1c603fdce436292a]::session::Session>::time::<(), rustc_interface[828b714f964ce1da]::passes::analysis::{closure#6}>
  35:     0x7f0ad52fae3a - rustc_interface[828b714f964ce1da]::passes::analysis
  36:     0x7f0ad664d4f2 - rustc_query_system[2b3be6912aef78d5]::query::plumbing::try_execute_query::<rustc_query_impl[a3402ef8368c6710]::queries::analysis, rustc_query_impl[a3402ef8368c6710]::plumbing::QueryCtxt>
  37:     0x7f0ad68550fa - <rustc_query_impl[a3402ef8368c6710]::Queries as rustc_middle[b5631d71f72482ee]::ty::query::QueryEngine>::analysis
  38:     0x7f0ad6075a23 - <rustc_interface[828b714f964ce1da]::queries::QueryResult<&rustc_middle[b5631d71f72482ee]::ty::context::GlobalCtxt>>::enter::<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}::{closure#2}::{closure#3}>
  39:     0x7f0ad6074bf4 - <rustc_interface[828b714f964ce1da]::interface::Compiler>::enter::<rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}::{closure#2}, core[d0f7fc72c0be1fb4]::result::Result<core[d0f7fc72c0be1fb4]::option::Option<rustc_interface[828b714f964ce1da]::queries::Linker>, rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>
  40:     0x7f0ad606fe14 - rustc_span[65551fbbac8b0f76]::with_source_map::<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_interface[828b714f964ce1da]::interface::run_compiler<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  41:     0x7f0ad606f924 - <scoped_tls[18b6b4dd1216e2e8]::ScopedKey<rustc_span[65551fbbac8b0f76]::SessionGlobals>>::set::<rustc_interface[828b714f964ce1da]::interface::run_compiler<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}>::{closure#0}, core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>
  42:     0x7f0ad606f022 - std[92d2792449a90a80]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[828b714f964ce1da]::util::run_in_thread_pool_with_globals<rustc_interface[828b714f964ce1da]::interface::run_compiler<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}>::{closure#0}, core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>
  43:     0x7f0ad606edcc - <<std[92d2792449a90a80]::thread::Builder>::spawn_unchecked_<rustc_interface[828b714f964ce1da]::util::run_in_thread_pool_with_globals<rustc_interface[828b714f964ce1da]::interface::run_compiler<core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>, rustc_driver_impl[9b756e32c0d38789]::run_compiler::{closure#1}>::{closure#0}, core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d0f7fc72c0be1fb4]::result::Result<(), rustc_errors[c2c7aee1e156d1f6]::ErrorGuaranteed>>::{closure#1} as core[d0f7fc72c0be1fb4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f0ad3b77c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h24b1cedbd344db9f
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/alloc/src/boxed.rs:1988:9
  45:     0x7f0ad3b77c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb7ac28b0dfacf269
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/alloc/src/boxed.rs:1988:9
  46:     0x7f0ad3b77c63 - std::sys::unix::thread::Thread::new::thread_start::h67c8d237baa6ad51
                               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7f0ad38d0bb5 - <unknown>
  48:     0x7f0ad3952d90 - <unknown>
  49:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (9aa5c24b7 2023-02-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_mod_privacy] checking privacy in top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 3 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Moves the check for illegal bound var types from astconv to resolve_bound_vars. If a binder is defined to have a type or const late-bound var that's not allowed, we'll resolve any usages to ty error or const error values, so we shouldn't ever see late-bound types or consts in places they aren't expected.

Fixes #108184
Fixes #108181
Fixes #108192

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 1]
```diff
@@ -52,6 +52,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     ) -> Ty<'tcx> {
         trace!("decl = {:#?}", closure.fn_decl);
 
+        deny_non_region_late_bound(self.tcx, closure.bound_generic_params, "closure");
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/closure.rs:55]: All this checks should probably be in `rustc_hir_analysis::collect::lifetimes`.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs]: I attempted to implement something like that. If binder doesn't allow late-bound ty or consts, then it'll resolve to `ResolvedArg::Error` instead, so we never actually see these late-bound type or const variables showing up where they shouldn't be.

Not sure if this is what you were looking for.
