### PR TITLE
Fix rustdoc rendering of by-value mutable arguments in async fn

### LINKED ISSUE #76517: rustdoc renames parameters with `mut` in async fn
### Original:

```rust
pub struct Foo;

impl Foo {
    pub async fn good(self, first: usize, second: usize) {}
    pub async fn bad(mut self, mut first: usize, mut second: usize) {}
}
```

### Rendered:

rustdoc output screenshot

This example was tested on Rust 1.46.0, but it has been broken for quite a while. For example, see [`Server::serve()`](https://docs.rs/tower-lsp/0.7.0/tower_lsp/struct.Server.html#method.serve) in `tower-lsp` version 0.7.0 (built with Rust 1.43.0-nightly, see [docs.rs build info](https://docs.rs/crate/tower-lsp/0.7.0/builds)).

### PR DESCRIPTION
**Pull request by ebkalderon**
r? @jyn514 

Fixes #76517.

### CODE REVIEW

**Comment by ebkalderon** [comment]
Would you like me to prepare any tests for this fix?

**Comment by jyn514** [comment]
Yes please; add them to `src/test/rustdoc`. There are examples there and instructions at https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts.

**Comment by jyn514** [comment]
```
 error[E0596]: cannot borrow `vec` as mutable, as it is not declared as mutable
  --> /checkout/src/test/ui/async-await/argument-patterns.rs:12:20
   |
LL | async fn b(n: u32, ref mut vec: A) {
   |                    ^^^^^^^^^^^
   |                    |
   |                    cannot borrow as mutable
   |                    help: consider changing this to be mutable: `mut vec`

error: aborting due to previous error
```
Welp, looks like this broken something. Not sure why.

r? @ecstatic-morse for review or re-assignment

File: compiler/rustc_ast_lowering/src/item.rs [hunk 1]
```diff
@@ -1096,9 +1096,7 @@ impl<'hir> LoweringContext<'_, 'hir> {
                 // Check if this is a binding pattern, if so, we can optimize and avoid adding a
                 // `let <pat> = __argN;` statement. In this case, we do not rename the parameter.
                 let (ident, is_simple_parameter) = match parameter.pat.kind {
-                    hir::PatKind::Binding(hir::BindingAnnotation::Unannotated, _, ident, _) => {
-                        (ident, true)
-                    }
+                    hir::PatKind::Binding(_, _, ident, _) => (ident, true),
```
Comment (jyn514) [inline compiler/rustc_ast_lowering/src/item.rs:1099]: Actually, I wonder if this would work if you changed it to `Unannotated | Mutable` instead; that would avoid changing the logic for `ref mut` and I don't think that's valid in function parameters anyway.
```suggestion
                    hir::PatKind::Binding(hir::BindingAnnotation::Unannotated | hir::BindingAnnotation::Mutable, _, ident, _) => (ident, true),
```

Comment (jyn514) [reply compiler/rustc_ast_lowering/src/item.rs:1099]: > and I don't think that's valid in function parameters anyway

It clearly is, see the error message above. So yeah, I'm not sure how to fix this.

Comment (ebkalderon) [reply compiler/rustc_ast_lowering/src/item.rs]: The issue, it seems, is as described in the comments above:

```rust
// If `<pattern>` is a simple ident, then it is lowered to a single
// `let <pattern> = <pattern>;` statement as an optimization.
```

I don't think that this is considered valid:

```rust
let mut bad1 = mut bad1;
let ref mut bad2 = ref mut bad2;
```

Comment (ebkalderon) [reply compiler/rustc_ast_lowering/src/item.rs]: This comment a little further down the page elaborates on the reasoning:

https://github.com/rust-lang/rust/blob/c1011165e63480dabf1913e308da8b344dfa8f8a/compiler/rustc_ast_lowering/src/item.rs#L1129-L1132

It seems that not reusing the original argument's pattern will mean that the `HirId`s will no longer be densely assigned. I wonder if this is still a pressing concern that must be addressed before considering this PR for merging, the current CI failures aside.

Comment (ebkalderon) [reply compiler/rustc_ast_lowering/src/item.rs]: It seems that the tests now pass with the suggested change from @jyn514, but this is not yet ready to merge. I'm assuming that although, for example, `let ref mut foo = ref mut foo;` is invalid Rust, CI is passing because there are no tests in place to catch this. Once I add tests in place, we can check whether this change is safe or not.

Comment (jyn514) [reply compiler/rustc_ast_lowering/src/item.rs]: >  perhaps this change to the AST lowering logic would have other implications elsewhere in the compiler?

Right, this is why I asked for feedback from ecstatic-morse. Rustdoc doesn't really have a way to fix this on its end.

**Comment by ecstatic-morse** [comment]
r? @cramertj maybe? I don't know this code.

I would guess that there's no "quick fix" here. If that's correct, we would need to preserve a mapping from `async fn` parameters to their patterns for use by `rustdoc` to fix this.

**Comment by tmandry** [comment]
In the simple case we _aren't_ actually inserting `let <pat> = <pat>;` as the comment says. We're inserting the statement `let <pat> = <ident>;` where `ident` is the original identifier named in the function signature. That means we were effectively doing the following in the `ref mut` case:

```rust
fn foo(ref mut x: i32) {
    let ref mut y = x;
}
```

i.e. trying to take a mutable reference to `x`, which itself is a `&mut i32`. But `x` is _not_ a mutable binding, i.e. the integer `x` points to could be changed, but _which integer_ `x` points to cannot be changed. Taking a mutable reference to `x` would violate that, so this is a compiler error.

I think we don't want this `is_simple_parameter` behavior anytime `ref` is involved. Which means that changing to `hir::BindingAnnotation::Unannotated | hir::BindingAnnotation::Mutable` was partly right.

However, we _do_ actually want to preserve the original identifier for rustdoc to use, anytime the pattern is a binding. For `ref` cases, I don't see any harm in preserving the identifier and setting `is_simple_parameter` to false.

P.S. Keeping HirId's dense is just an optimization, not as important as correctness.

**Comment by jyn514** [comment]
Ok, that makes a lot of sense! So something like this would work:

```rust
                let (ident, is_simple_parameter) = match parameter.pat.kind {
                    hir::PatKind::Binding(
                        hir::BindingAnnotation::Unannotated | hir::BindingAnnotation::Mutable,
                        _,
                        ident,
                        _,
                    ) => (ident, true),
                    hir::PatKind::Binding(_, _, ident, _) => (ident, false),
```

@ebkalderon do you mind implementing that?

**Comment by jyn514** [comment]
Also, please add a test for both of these cases: `async fn f(ref mut x: i32)` and `async fn f(mut x: i32)`.

**Comment by ebkalderon** [comment]
Yep, I'm on it!

**Comment by tmandry** [comment]
Ping from triage. @ebkalderon, are you still working on this?

**Comment by jyn514** [comment]
@ebkalderon do you mind if I take over this PR? It's most of the way there, I'd hate for it to be lost in limbo.

**Comment by tmandry** [comment]
@bors r+ rollup 

Thanks all!

**Comment by GuillaumeGomez** [comment]
It failed CI: https://github.com/rust-lang-ci/rust/runs/1389783331

**Comment by jyn514** [comment]
Heh, the test @lcnr added for the wrong behavior in #78916 failed. Just needs a rebase.
