### PR TITLE
Collect occurrences of empty blocks for mismatched braces diagnostic

### LINKED ISSUE #63904: Collect occurrences of `{}` for mismatched braces diagnostic
Many editors _helpfully_ auto close delimiters when writing them down. It is not uncommon for this to cause the following to occur:
```
fn main() {}
    let _ = ();
}
```

It'd be a good idea for the parser or lexer to keep track of these empty blocks to provide an error closer to

```
error: unexpected close delimiter: `}`
 --> src/main.rs:3:1
  |
1 | fn main() {}
  |           -- this block is empty, you might have not meant to close it
2 |     let _ = ();
3 | }
  | ^ unexpected close delimiter
```

### PR DESCRIPTION
**Pull request by XiangQingW**
Fix #63904

### CODE REVIEW

**Comment by XiangQingW** [comment]
@estebank Would you mind reviewing this pr if you have free time.

File: src/libsyntax/parse/lexer/tokentrees.rs [hunk 1]
```diff
@@ -121,13 +124,20 @@ impl<'a> TokenTreesReader<'a> {
                     // Correct delimiter.
                     token::CloseDelim(d) if d == delim => {
                         let (open_brace, open_brace_span) = self.open_braces.pop().unwrap();
+                        let close_brace_span = self.token.span;
+
+                        if close_brace_span.lo() == open_brace_span.hi() {
```
Comment (estebank) [inline src/libsyntax/parse/lexer/tokentrees.rs]: It seems to me that it would make more sense to check whether `tts` is empty instead of comparing spans. That way we also catch cases like `{ }` and `{\n}`.

**Comment by estebank** [comment]
@XiangQingW love it! There's one minor change I'd like, but otherwise r=me.

File: src/libsyntax/parse/lexer/tokentrees.rs (hunk 1 above)
Comment (XiangQingW) [reply src/libsyntax/parse/lexer/tokentrees.rs]: Thanks for the advice and I'll to change it.

**Comment by lzutao** [comment]
r+ ?

File: src/libsyntax_ext/proc_macro_harness.rs [hunk 2]
```diff
@@ -404,6 +404,11 @@ fn mk_decls(
     ).map(|mut i| {
         let attr = cx.meta_word(span, sym::rustc_proc_macro_decls);
         i.attrs.push(cx.attribute(attr));
+
+        let deprecated_nested_attr = cx.meta_nested_word(span, sym::deprecated);
+        let allow_deprecated_attr = cx.meta_list(span, sym::allow, vec![deprecated_nested_attr]);
+        i.attrs.push(cx.attribute(allow_deprecated_attr));
```
Comment (estebank) [inline src/libsyntax_ext/proc_macro_harness.rs]: Did you mean to push these changes to this PR?

Comment (XiangQingW) [reply src/libsyntax_ext/proc_macro_harness.rs]: Sorry for the wrong commit. I have just reverted it and have created another pr #65484. Could you please r+ again for me?

**Comment by XiangQingW** [comment]
@ebarnard  Pinging again from triage. I have reverted unrelated commit. Thank you.

**Comment by ebarnard** [comment]
@XiangQingW I think you mean @estebank.

**Comment by estebank** [comment]
@XiangQingW can you use `git rebase -i` as requested by @lzutao to remove the last two commits from this branch and then `git push --force`?

Double check the log before and after the rebase before pushing to make sure what you expect to be there is there.

**Comment by XiangQingW** [comment]
> @XiangQingW can you use `git rebase -i` as requested by @lzutao to remove the last two commits from this branch and then `git push --force`?
> 
> Double check the log before and after the rebase before pushing to make sure what you expect to be there is there.

It's really helpful. Thank you very much.
