### PR TITLE
Suggest a positional formatting argument instead of a captured argument

### LINKED ISSUE #97311: Wrong suggestions for typos on variables that have the same name as struct fields
Given the following code: 

1.63.0-nightly (2022-05-22)

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bb6ee98b3c92917f9eab8607bf3f5deb

```rust
struct A {
    config: String,
}

impl A {
    fn do_something(self, cofig: String) {
        println!("{config}"); //~ Error cannot find value `config` in this scope
    }
}

fn main() {}

```

The current output is:

This suggestion can cause compiler errors.

```
Compiling playground v0.0.1 (/playground)
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `config` in this scope
 --> src/main.rs:7:20
  |
7 |         println!("{config}"); //~ Error cannot find value `config` in this scope
  |                    ^^^^^^ help: you might have meant to use the available field: `self.config`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

`help` shouldn't be emitted.

or should look like `println!("{}", self.config)`.

```
Compiling playground v0.0.1 (/playground)
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `config` in this scope
 --> src/main.rs:7:20
  |
7 |         println!("{config}"); //~ Error cannot find value `config` in this scope
  |                    ^^^^^^

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to previous error
```

### LINKED ISSUE #98241: invalid suggestion: self.field  cannot be used with format args capture
Given the following code: 

```rust
struct A {
    foo: u32
}

impl A {
    fn func(&self) -> String {
        format!("{foo}")
    }
}
```

The current output is:

```
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `foo` in this scope
 --> src/lib.rs:7:19
  |
7 |         format!("{foo}")
  |                   ^^^ help: you might have meant to use the available field: `self.foo`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

Note that `{self.foo}` is not accepted (yet..?) by the compiler, so we should suggest something like `format!("{}", self.foo)` I guess?

### PR DESCRIPTION
**Pull request by TaKO8Ki**
This patch fixes a part of #96999. 

fixes #98241
fixes #97311

r? @estebank

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you add tests for different format arg types, like Debug `{:?}` and `{:#?}`, and precision formatters like `{:.3}`?

**Comment by TaKO8Ki** [comment]
@compiler-errors I added them!

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -750,6 +761,29 @@ impl<'a> Parser<'a> {
...
         if found { Some(cur) } else { None }
     }
+
+    fn suggest_positional_arg_instead_of_captured_arg(&mut self, arg: Argument<'a>) {
+        if let Some(end) = self.consume_pos('.') {
+            let byte_pos = self.to_span_index(end);
+            let start = InnerOffset(byte_pos.0 + 1);
+            let field = self.argument(start);
+            if let ArgumentNamed(_) = arg.position {
+                if let ArgumentNamed(_) = field.position {
```
Comment (estebank) [inline compiler/rustc_parse_format/src/lib.rs:771]:
```suggestion
            if let ArgumentNamed(_) = arg.position
                && let ArgumentNamed(_) = field.position
            {
```

File: compiler/rustc_parse_format/src/lib.rs [hunk 2]
```diff
@@ -750,6 +761,29 @@ impl<'a> Parser<'a> {
...
+                    self.errors.insert(
+                        0,
+                        ParseError {
+                            description: "field access isn't supported".to_string(),
```
Comment (estebank) [inline compiler/rustc_parse_format/src/lib.rs:775]: Given the check above, this would also trigger if we had something like `"{foo.bar()}"`, right? It'd be interesting to explicitly look for a closing `}`, and if there isn't one, *not* emit a suggestion, just a message with "arbitrary expressions aren't supported" *or* potentially consuming every char until a `}` is found and use that inner span for the suggestion. 🤔 

I feel like the later change can be part of its own PR.

File: compiler/rustc_parse_format/src/lib.rs [hunk 3]
```diff
@@ -228,13 +229,19 @@ impl<'a> Iterator for Parser<'a> {
...
                     } else {
                         let arg = self.argument(lbrace_end);
-                        if let Some(rbrace_byte_idx) = self.must_consume('}') {
-                            let lbrace_inner_offset = self.to_span_index(pos);
-                            let rbrace_inner_offset = self.to_span_index(rbrace_byte_idx);
-                            if self.is_literal {
-                                self.arg_places.push(
-                                    lbrace_inner_offset.to(InnerOffset(rbrace_inner_offset.0 + 1)),
-                                );
+                        match self.must_consume('}') {
```
Comment (estebank) [inline compiler/rustc_parse_format/src/lib.rs:232]: This could have been an `if let/else`, to avoid one level of indentation, but I don't care too much either way.

File: compiler/rustc_builtin_macros/src/format.rs [hunk 4]
```diff
@@ -1270,6 +1275,24 @@ pub fn expand_preparsed_format_args(
                 e.span_label(fmt_span.from_inner(InnerSpan::new(span.start, span.end)), label);
             }
         }
+        if err.should_be_replaced_with_positional_argument {
+            let captured_arg_span =
+                fmt_span.from_inner(InnerSpan::new(err.span.start, err.span.end));
+            let positional_args = args.iter().filter(|arg| !arg.named).collect::<Vec<_>>();
+            let mut suggestions = vec![(captured_arg_span, positional_args.len().to_string())];
+            if let Ok(arg) = ecx.source_map().span_to_snippet(captured_arg_span) {
```
Comment (estebank) [inline compiler/rustc_builtin_macros/src/format.rs:1283]: Let's maybe keep this check enclose the whole suggestion? So if we fail to obtain the `captured_arg_span` snippet, we don't display the suggestion at all (instead of a partial suggestion).

File: compiler/rustc_parse_format/src/lib.rs [hunk 5]
```diff
@@ -750,6 +757,32 @@ impl<'a> Parser<'a> {
         }
         if found { Some(cur) } else { None }
     }
+
+    fn suggest_positional_arg_instead_of_captured_arg(&mut self, arg: Argument<'a>) {
+        if let Some(end) = self.consume_pos('.') {
+            let byte_pos = self.to_span_index(end);
+            let start = InnerOffset(byte_pos.0 + 1);
+            let field = self.argument(start);
+            if !self.consume('}') {
```
Comment (estebank) [inline compiler/rustc_parse_format/src/lib.rs:766]: Can we add a comment stating "We can only parse `foo.bar` field access, any deeper nesting, or another type of expression, like method calls, are not supported".

File: compiler/rustc_parse_format/src/lib.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse_format/src/lib.rs:770]: Please use let chains to reduce indentation.

**Review by estebank — APPROVED** [review]
Couple of nitpicks, r=me after addressing them.

File: compiler/rustc_parse_format/src/lib.rs (hunk 1 above)
Comment (TaKO8Ki) [reply compiler/rustc_parse_format/src/lib.rs:770]: `rustc_parse_format` does not have let_chains feature and It seems I should not add this feature due to the following comment.

https://github.com/rust-lang/rust/blob/2f2243c9b6686d2314515561a80898e746015231/compiler/rustc_parse_format/src/lib.rs#L12-L13

File: compiler/rustc_parse_format/src/lib.rs (hunk 2 above)
Comment (TaKO8Ki) [reply compiler/rustc_parse_format/src/lib.rs:774]: I will create an issue about that and work on it later.

File: compiler/rustc_parse_format/src/lib.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse_format/src/lib.rs:772]: ok, then it's fine :)
