### PR TITLE
Always set `RUSTC_BOOTSTRAP` with `x doc`

### LINKED ISSUE #100060: `./x.py doc` on a clean repo on master passes, but with warnings about feature gates
```rust
[...]
Documenting error index (x86_64-unknown-linux-gnu)
Building stage0 tool error_index_generator (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.18s
Generating lint docs (x86_64-unknown-linux-gnu)
Building stage0 tool lint-docs (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.15s
warning: the code example in lint `unfulfilled_lint_expectations` in /home/jess/src/rust/compiler/rustc_lint_defs/src/builtin.rs failed to generate the expected output: did not find lint `unfulfilled_lint_expectations` in output of example, got:

error[E0554]: `#![feature]` may not be used on the beta release channel
 --> lint_example.rs:1:1
  |
1 | #![feature(lint_reasons)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^


error: aborting due to previous error


For more information about this error, try `rustc --explain E0554`.

warning: the code example in lint `unused_allocation` in /home/jess/src/rust/compiler/rustc_lint/src/unused.rs failed to generate the expected output: did not find lint `unused_allocation` in output of example, got:

error[E0554]: `#![feature]` may not be used on the beta release channel
 --> lint_example.rs:1:1
  |
1 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^


error: aborting due to previous error


For more information about this error, try `rustc --explain E0554`.

Rustbook (x86_64-unknown-linux-gnu) - rustc
Documenting stage0 clippy (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.21s
Documenting stage0 miri (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.17s
Build completed successfully in 0:01:10
./x.py doc  63.71s user 11.62s system 105% cpu 1:11.48 total
```

This should probably fail docs, but also it shouldn't happen in the first place. Not entirely sure why the other lines in the file don't trigger this, but I'm just making a note of this.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #100060

Note that there is still a warning - the `unused_allocation` lint does not fire in stage 0, but that's just a matter of waiting for #104363 to land in beta

### CODE REVIEW

File: src/bootstrap/doc.rs [hunk 1]
```diff
@@ -1027,10 +1027,11 @@ impl Step for RustcBook {
         if self.validate {
             cmd.arg("--validate");
         }
-        if !builder.unstable_features() {
-            // We need to validate nightly features, even on the stable channel.
-            cmd.env("RUSTC_BOOTSTRAP", "1");
-        }
+        // We need to validate nightly features, even on the stable channel.
+        // Set this unconditionally as the stage0 compiler may be being used to
```
Comment (est31) [inline src/bootstrap/doc.rs:1031]:
```suggestion
        // Set this unconditionally as the stage0 compiler may be be used to
```

Comment (clubby789) [reply src/bootstrap/doc.rs:1031]: Isn't `may be being used` correct? I was trying to write in the present tense and I think `may be used` would be future tense

Comment (est31) [reply src/bootstrap/doc.rs:1031]: I'm not a native speaker. I've first made this comment because it sounded wrong to me, but according [to the internet](https://boards.straightdope.com/t/be-being-grammatically-correct/611322/6) it is [correct use](https://forum.wordreference.com/threads/may-be-being-3rd-form-of-verb.2986231/) although people do say that it's not very commonly used.

**Review by onur-ozkan — APPROVED** [review]
LGTM, thanks for the fix :)
