### PR TITLE
Do not build tools if user do not want them

### LINKED ISSUE #71307: failing to build individual tools via x.py
Running `./x.py build` results in all tools built, even though I asked for one, using the following `config.toml`:
```toml
[build]
compiler-docs = true
extended = true
tools = ["rustfmt"]
```

This issue has been assigned to @mati865 via [this comment](https://github.com/rust-lang/rust/issues/71307#issuecomment-616088232).

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/71307

### CODE REVIEW

File: src/bootstrap/tool.rs [hunk 1]
```diff
@@ -607,7 +607,14 @@ macro_rules! tool_extended {
...
             fn should_run(run: ShouldRun<'_>) -> ShouldRun<'_> {
                 let builder = run.builder;
-                run.path($path).default_condition(builder.config.extended)
+                run.path($path).default_condition(
+                    builder.config.extended
+                        && builder
+                            .config
+                            .tools
+                            .as_ref()
+                            .map_or(true, |tools| tools.iter().any(|tool| $tool_name.contains(tool))),
```
Comment (Mark-Simulacrum) [inline src/bootstrap/tool.rs:616]: Hm, I think we should be able to go for exact match over contains? Is there a reason you opted for contains?

Comment (mati865) [reply src/bootstrap/tool.rs:616]: It's because Clippy is called `clippy` in the config: https://github.com/rust-lang/rust/blob/4ca5fd2d7b6b1d75b6cb8f679e8523fb3e7b19e2/config.toml.example#L200
And `clippy-driver` in tools.rs: https://github.com/rust-lang/rust/blob/4ca5fd2d7b6b1d75b6cb8f679e8523fb3e7b19e2/src/bootstrap/tool.rs#L643

`tool_name` argument of `tool_extended` macro has to match binary name and Clippy is actually `clippy-driver`.
Changing `clippy` to `clippy-driver` in the config file doesn't seem right and it's unnecessary breaking change.

Comment (Mark-Simulacrum) [reply src/bootstrap/tool.rs:616]: I'd prefer to instead match specifically on clippy/clippy-driver and handle them separately.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Thanks!

**Comment by tshepang** [comment]
I see cargo is getting built, even though I asked only for `rustfmt`
```yaml
[build]
extended = true
tools = ["rustfmt"]
```

**Comment by tshepang** [comment]
Ok, I suppose that was because `cargo-fmt` also needed to get built

**Comment by mati865** [comment]
@tshepang I'm on my mobile right now but I think there was piece of code somewhere that always enables Cargo when `extended = true`.

**Comment by tshepang** [comment]
Is it this https://github.com/rust-lang/rust/blob/master/src/bootstrap/tool.rs#L560-L563

**Comment by mati865** [comment]
@tshepang exactly. I don't know whether it's fine to skip Cargo when bulidng other tools though.

**Comment by tshepang** [comment]
I would rather have a warning, or at least the behavior documented (in config.toml.example), than be surprised. Perhaps I should prepare a PR?

**Comment by mati865** [comment]
@tshepang sure. It could && config.tools.as_ref()
                    .map_or(true, |t| t.contains($path))

**Comment by mati865** [comment]
@tshepang sure but maybe this condition should be changed from 
https://github.com/rust-lang/rust/blob/4bfd62acb12a5e628d28950f9f94c3499216f10c/src/bootstrap/tool.rs#L562
to
```
run.path("src/tools/cargo").default_condition(
    builder.config.extended
    && builder.config.tools.as_ref().map_or(true, |t| t.contains("cargo")))
```
since Cargo won't be installed if it's not present in `tools` list?

**Comment by tshepang** [comment]
That makes me wonder why cargo is not made part of that `tools_extended` macro... code looks similar?

**Comment by mati865** [comment]
I have no idea, probably because of this line: https://github.com/rust-lang/rust/blob/9296d3ba8247ac292226ba19fefc6d577f2d5dfd/src/bootstrap/tool.rs#L584

**Comment by tshepang** [comment]
@Mark-Simulacrum why is cargo marked as a essential tool?
