### PR TITLE
save_analysis: fix some ICEs

### LINKED ISSUE #73020: ICE E0431.rs with -Zsave-analysis
### Code
code from `./src/test/ui/error-codes/E0431.rs`
```Rust
use {self}; //~ ERROR E0431

fn main () {
}
```

### Meta

repo is @ 219380d840877de97b0e17674be7212ebc929d51

### Error output
`build/x86_64-unknown-linux-gnu/stage2/bin/rustc ./src/test/ui/error-codes/E0431.rs  -Zsave-analysis`
```
thread 'rustc' panicked at 'index 18446744073709551615 out of range for slice of length 0', src/librustc_save_analysis/dump_visitor.rs:213:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0431]: `self` import can only appear in an import list with a non-empty prefix
 --> ./src/test/ui/error-codes/E0431.rs:1:6
  |
1 | use {self}; //~ ERROR E0431
  |      ^^^^ can only appear in an import list with a non-empty prefix

warning: unused import: `self`
 --> ./src/test/ui/error-codes/E0431.rs:1:6
  |
1 | use {self}; //~ ERROR E0431
  |      ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'index 18446744073709551615 out of range for slice of length 0', src/librustc_save_analysis/dump_visitor.rs:213:21
stack backtrace:
   0:     0x7f4ba27b0d57 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he2fbf5405bd3f46a
   1:     0x7f4ba27fda3d - core::fmt::write::h65255e7874586eb2
   2:     0x7f4ba2781b95 - std::io::Write::write_fmt::h3c49d63e356d89fe
   3:     0x7f4ba278d980 - std::panicking::default_hook::{{closure}}::h6b88f05100c9e449
   4:     0x7f4ba278d694 - std::panicking::default_hook::h57a663a807afe943
   5:     0x7f4ba41458a3 - rustc_driver::report_ice::h34c4499908ba0b29
   6:     0x7f4ba278e06c - std::panicking::rust_panic_with_hook::haef04471b94d420c
   7:     0x7f4ba278dc3b - rust_begin_unwind
   8:     0x7f4ba27fb7e1 - core::panicking::panic_fmt::h95ae6ee01add471a
   9:     0x7f4ba27f9f12 - core::slice::slice_index_len_fail::h0017b5f53e111206
  10:     0x7f4ba424f418 - rustc_save_analysis::dump_visitor::DumpVisitor::process_path::h64d45cc6b7fee451
  11:     0x7f4ba4251011 - rustc_save_analysis::dump_visitor::DumpVisitor::process_crate::h3af551472fa9ad7e
  12:     0x7f4ba4120f98 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h230cde404218eeb4
  13:     0x7f4ba41be03e - rustc_session::utils::<impl rustc_session::session::Session>::time::ha57d20269542213a
  14:     0x7f4ba41318eb - rustc_middle::ty::context::tls::enter_global::h5e4aceeb2c5d9074
  15:     0x7f4ba41538e7 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h46a369817e38d2d4
  16:     0x7f4ba41bd7ca - rustc_span::with_source_map::ha1e1d15982d868c1
  17:     0x7f4ba4155b49 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hfd5622ef3ce026be
  18:     0x7f4ba412f34e - scoped_tls::ScopedKey<T>::set::hd3c1397285b10bd3
  19:     0x7f4ba4156576 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3df4554cf04b61c9
  20:     0x7f4ba412317e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb0a109416f61afc2
  21:     0x7f4ba2795d7a - std::sys::unix::thread::Thread::new::thread_start::hb2effada6f868308
  22:     0x7f4ba24bc422 - start_thread
  23:     0x7f4ba25dabf3 - __GI___clone
  24:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

query stack during panic:
end of query stack
error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0431`.
```

</p>
</details>

### LINKED ISSUE #73022: ICE -Zsave-analysis  lint-dead-code-5.rs  impossible case reached
### Code
reduced from `./src/test/ui/lint/dead-code/lint-dead-code-5.rs`
```Rust
enum Enum2 {
    Variant8 { _field: bool },
}

impl Enum2 {
    fn new_variant8() -> Enum2 {
        Self::Variant8 { _field: true }
    }
}

fn main() {}
```

### Meta

repo @ 219380d840877de97b0e17674be7212ebc929d51
### Error output
`RUST_BACKTRACE=full build/x86_64-unknown-linux-gnu/stage2/bin/rustc ./src/test/ui/lint/dead-code/lint-dead-code-5.rs  -Zsave-analysis`
```
error: internal compiler error: src/librustc_save_analysis/lib.rs:583: impossible case reached

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: enum is never used: `Enum2`
 --> ./src/test/ui/lint/dead-code/lint-dead-code-5.rs:2:6
  |
2 | enum Enum2 {
  |      ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `new_variant8`
 --> ./src/test/ui/lint/dead-code/lint-dead-code-5.rs:8:8
  |
8 |     fn new_variant8() -> Enum2 {
  |        ^^^^^^^^^^^^

error: internal compiler error: src/librustc_save_analysis/lib.rs:583: impossible case reached

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
stack backtrace:
   0:     0x7f9c1fc5cd57 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he2fbf5405bd3f46a
   1:     0x7f9c1fca9a3d - core::fmt::write::h65255e7874586eb2
   2:     0x7f9c1fc2db95 - std::io::Write::write_fmt::h3c49d63e356d89fe
   3:     0x7f9c1fc39980 - std::panicking::default_hook::{{closure}}::h6b88f05100c9e449
   4:     0x7f9c1fc39694 - std::panicking::default_hook::h57a663a807afe943
   5:     0x7f9c215f18a3 - rustc_driver::report_ice::h34c4499908ba0b29
   6:     0x7f9c1fc3a06c - std::panicking::rust_panic_with_hook::haef04471b94d420c
   7:     0x7f9c25724763 - std::panicking::begin_panic::h864c0841f11b0cc5
   8:     0x7f9c257333b0 - rustc_errors::HandlerInner::bug::hf4b00747a8046e38
   9:     0x7f9c25731c80 - rustc_errors::Handler::bug::h1a265be085905310
  10:     0x7f9c252ca446 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::hc31214a436b0cba2
  11:     0x7f9c252c20e5 - rustc_middle::ty::context::tls::with_opt::{{closure}}::h8a5fa3e61707645c
  12:     0x7f9c252c204d - rustc_middle::ty::context::tls::with_opt::he95b2464f8e01c32
  13:     0x7f9c252ca355 - rustc_middle::util::bug::opt_span_bug_fmt::h89c1337accb0a963
  14:     0x7f9c252ca2c0 - rustc_middle::util::bug::bug_fmt::h394875dd81e62801
  15:     0x7f9c216bad44 - rustc_save_analysis::SaveContext::get_expr_data::hc00a9e9ea4e1de91
  16:     0x7f9c216fb49c - rustc_save_analysis::dump_visitor::DumpVisitor::process_struct_lit::h3b47a8c34330ad0c
  17:     0x7f9c2170486f - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h5917555fc95a2c93
  18:     0x7f9c216f9ee6 - rustc_save_analysis::dump_visitor::DumpVisitor::process_method::hbfe900f2f5b25c39
  19:     0x7f9c217007c6 - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_hir::intravisit::Visitor>::visit_item::h5b70e8094603aadd
  20:     0x7f9c216fd011 - rustc_save_analysis::dump_visitor::DumpVisitor::process_crate::h3af551472fa9ad7e
  21:     0x7f9c215ccf98 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h230cde404218eeb4
  22:     0x7f9c2166a03e - rustc_session::utils::<impl rustc_session::session::Session>::time::ha57d20269542213a
  23:     0x7f9c215dd8eb - rustc_middle::ty::context::tls::enter_global::h5e4aceeb2c5d9074
  24:     0x7f9c215ff8e7 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h46a369817e38d2d4
  25:     0x7f9c216697ca - rustc_span::with_source_map::ha1e1d15982d868c1
  26:     0x7f9c21601b49 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hfd5622ef3ce026be
  27:     0x7f9c215db34e - scoped_tls::ScopedKey<T>::set::hd3c1397285b10bd3
  28:     0x7f9c21602576 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3df4554cf04b61c9
  29:     0x7f9c215cf17e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb0a109416f61afc2
  30:     0x7f9c1fc41d7a - std::sys::unix::thread::Thread::new::thread_start::hb2effada6f868308
  31:     0x7f9c1f968422 - start_thread
  32:     0x7f9c1fa86bf3 - __GI___clone
  33:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

query stack during panic:
end of query stack
error: aborting due to previous error; 2 warnings emitted

```

</p>
</details>

### LINKED ISSUE #73041: "index 18446744073709551615 out of range for slice of length 0" at src/librustc_save_analysis/dump_visitor.rs:213:21
### Code

```
rustup update nightly
git clone https://github.com/mozilla/glean
cd glean
RUSTFLAGS="-Z save-analysis" cargo +nightly check --all
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (47c3158c3 2020-06-04)
binary: rustc
commit-hash: 47c3158c3d797f75f0f7b2b2a977179668919dab
commit-date: 2020-06-04
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

### Error output

```
thread 'rustc' panicked at 'index 18446744073709551615 out of range for slice of length 0', src/librustc_save_analysis/dump_visitor.rs:213:21
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7fa6814e68e5 - backtrace::backtrace::libunwind::trace::hdbb9dcedd5b14342
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7fa6814e68e5 - backtrace::backtrace::trace_unsynchronized::h5cb0c657a8aaefe5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7fa6814e68e5 - std::sys_common::backtrace::_print_fmt::hf3d2b27f4a1fea46
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7fa6814e68e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffe95416249239d3
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7fa681523e9c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7fa6814d9093 - std::io::Write::write_fmt::h707372d99b8d3ce8
                               at src/libstd/io/mod.rs:1537
   6:     0x7fa6814eb900 - std::sys_common::backtrace::_print::h97ba20d63ea7ee1f
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7fa6814eb900 - std::sys_common::backtrace::print::hcec5aeaa0e8a40b0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7fa6814eb900 - std::panicking::default_hook::{{closure}}::h8ce2bb1b48eaabb3
                               at src/libstd/panicking.rs:198
   9:     0x7fa6814eb64c - std::panicking::default_hook::hfd893b6e71292289
                               at src/libstd/panicking.rs:218
  10:     0x7fa681bfae13 - rustc_driver::report_ice::h33035c23c2a2abf3
  11:     0x7fa6814ebfac - std::panicking::rust_panic_with_hook::h71be6e32cc7c55db
                               at src/libstd/panicking.rs:490
  12:     0x7fa6814ebb8b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  13:     0x7fa681520a41 - core::panicking::panic_fmt::hd101a87121fa411f
                               at src/libcore/panicking.rs:101
  14:     0x7fa681525e32 - core::slice::slice_index_len_fail::hb5cd3744b833ae5f
                               at src/libcore/slice/mod.rs:2751
  15:     0x7fa681d0529f - rustc_save_analysis::dump_visitor::DumpVisitor::process_path::he5740622b66129c1
  16:     0x7fa681d0a401 - <rustc_save_analysis::dump_visitor::DumpVisitor as rustc_hir::intravisit::Visitor>::visit_item::h52a7b688fd99e79f
  17:     0x7fa681d06f11 - rustc_save_analysis::dump_visitor::DumpVisitor::process_crate::h98273bd5cb13693f
  18:     0x7fa681bd720a - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::he2f7ad7f79b69458
  19:     0x7fa681c73189 - rustc_session::utils::<impl rustc_session::session::Session>::time::hcef5d2e064d53f9f
  20:     0x7fa681be7c5a - rustc_middle::ty::context::tls::enter_global::h13104a1d9589ac96
  21:     0x7fa681c08f28 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hb67dc99907225910
  22:     0x7fa681c72163 - rustc_span::with_source_map::h03cf73a37b0e569f
  23:     0x7fa681c0b0e8 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h32891cdd002262b1
  24:     0x7fa681be59dd - scoped_tls::ScopedKey<T>::set::hdffe1e0e5fcf8041
  25:     0x7fa681c0bdb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbc1b962a56f96b05
  26:     0x7fa681bd918e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a64e0a1b67fbf90
  27:     0x7fa6814fb80a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf1df77fdbbc91b60
                               at /rustc/47c3158c3d797f75f0f7b2b2a977179668919dab/src/liballoc/boxed.rs:1076
  28:     0x7fa6814fb80a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0fb79cf50c369e84
                               at /rustc/47c3158c3d797f75f0f7b2b2a977179668919dab/src/liballoc/boxed.rs:1076
  29:     0x7fa6814fb80a - std::sys::unix::thread::Thread::new::thread_start::h5839aae79966bc57
                               at src/libstd/sys/unix/thread.rs:87
  30:     0x7fa6812606db - start_thread
                               at /build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c:463
  31:     0x7fa680b7d88f - __clone
  32:                0x0 - <unknown>
error: internal compiler error: unexpected panic
```

</p>
</details>

This is a recent regression, since we run this command every day in automation.

### PR DESCRIPTION
**Pull request by marmeladema**
Fixes #73020 
Fixes #73022
Fixes #73041

### CODE REVIEW

**Comment by Xanewok** [comment]
Good catch, thanks!

@bors r+ rollup

**Comment by marmeladema** [comment]
Sorry @Xanewok i've just added a fix for another issue.

**Comment by Xanewok** [comment]
Do you think there are going to be more issues with TypeRelative paths being not matched on?

**Comment by marmeladema** [comment]
Potentially yes, but i've tried adding it everywhere and it leads to other bugs later on in `librustc_middle` so it will take a bit of time to understand how to do it properly.

In the mean time, those 2 commits should fix some ices/panics.

**Comment by marmeladema** [comment]
> By the way you can try running the entire test suite with -Zsave-analysis passed to considerably increase the test set smile

That's what I am doing right now to find more crashes :+1: I hope to come back with some more patches in the next few days

**Comment by Xanewok** [comment]
That's good to hear! Let's try to land this, then:

@bors r+

File: src/librustc_save_analysis/dump_visitor.rs [hunk 1]
```diff
@@ -210,9 +210,11 @@ impl<'l, 'tcx> DumpVisitor<'l, 'tcx> {
...
     // will be processed elsewhere). See note on write_sub_paths about global.
     fn write_sub_paths_truncated(&mut self, path: &'tcx hir::Path<'tcx>) {
-        for seg in &path.segments[..path.segments.len() - 1] {
-            if let Some(data) = self.save_ctxt.get_path_segment_data(seg) {
-                self.dumper.dump_ref(data);
+        if path.segments.len() > 0 {
+            for seg in &path.segments[..path.segments.len() - 1] {
+                if let Some(data) = self.save_ctxt.get_path_segment_data(seg) {
+                    self.dumper.dump_ref(data);
+                }
```
Comment (lzutao) [inline src/librustc_save_analysis/dump_visitor.rs:217]:
```suggestion
        if let [prefix @ .., _] = path.segments {
            for seg in prefix {
                if let Some(data) = self.save_ctxt.get_path_segment_data(seg) {
                    self.dumper.dump_ref(data);
                }
```

**Comment by RalfJung** [comment]
3 rollups failed with the same error and all contained this PR:
https://github.com/rust-lang/rust/pull/73052, https://github.com/rust-lang/rust/pull/73053, https://github.com/rust-lang/rust/pull/73062
So, I think this is likely the culprit...
@bors r- rollup=never

**Comment by marmeladema** [comment]
Superseded by https://github.com/rust-lang/rust/pull/73071

**Comment by RalfJung** [comment]
(Looks like that's just more commits added to this one, so IMO it would make sense to keep using the same PR so that all discussion is in one place. But whatever.^^)

**Comment by marmeladema** [comment]
The hope is that those new commits will magically fix those weird failures :-D

**Comment by RalfJung** [comment]
I understand. Still no reason to open a new PR -- to the contrary, opening a new PR erases the prior discussion and thus the relation to the previous failures.

But also, another rollup saw the same failures again and didn't include this PR. I am at a total loss where the problem is coming from.

**Comment by marmeladema** [comment]
I understand and I don't mind to let this PR open as a matter of fact. I thought it would be confusing to have two that includes the same commits.

**Comment by RalfJung** [comment]
Yes that's confusing indeed. So why did you open a 2nd one in the first place?

**Comment by marmeladema** [comment]
So @RalfJung let's go as originally planned. Can this be approved again? Or is there still suspicions this PR is breaking CI?

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (Xanewok) [reply src/librustc_save_analysis/dump_visitor.rs:217]: I like this approach, it seems more readable and IIUC this only takes a prefix without the last item. @marmeladema could we apply this patch?

**Comment by Xanewok** [comment]
r=me with https://github.com/rust-lang/rust/pull/73046/files#r436305949 addressed

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (marmeladema) [reply src/librustc_save_analysis/dump_visitor.rs]: Done

**Comment by Xanewok** [comment]
Thanks a lot! Let's try to get this in again...

@bors r+
