### PR TITLE
Check tuple elements are `Sized` in `offset_of`

### LINKED ISSUE #112186: offset_of! accepts unsized tuple field
I tried this code:

```rust
#![feature(offset_of)]
use std::fmt::Debug;
fn main() {
    core::mem::offset_of!((u8, dyn Debug), 1);
}
```

I expected the compilation to fail since the offset cannot be statically determined. Instead, the compilation succeeds.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #112186

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 1]
```diff
@@ -3117,16 +3117,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 }
                 ty::Tuple(tys) => {
-                    let fstr = field.as_str();
-
-                    if let Ok(index) = fstr.parse::<usize>() {
-                        if fstr == index.to_string() {
-                            if let Some(&field_ty) = tys.get(index) {
-                                field_indices.push(index.into());
-                                current_container = field_ty;
+                    if let Ok(index) = field.as_str().parse::<usize>()
```
[the remark this answers is not in the document]
Comment (est31) [reply compiler/rustc_hir_typeck/src/expr.rs:3120]: This is currently rejected at the macro expansion level. I think adding the case you mention to one of the tests would make sense.

File: tests/ui/offset-of/offset-of-unsized.rs [hunk 2]
```diff
@@ -10,6 +9,8 @@ struct S<T: ?Sized> {
 trait Tr {}
 
 fn main() {
-    let _a = core::mem::offset_of!(S<dyn Tr>, a);
-    let _b = core::mem::offset_of!((u64, dyn Tr), 0);
+    let _a = core::mem::offset_of!(S<dyn Tr>, a); // ok
```
Comment (est31) [inline tests/ui/offset-of/offset-of-unsized.rs:12]: I think it should be better to edit `offset-of-dst-field.rs` instead, or create a completely new file from a copy of this file, because right now the test would probably not trigger the ICE from #112051 (not 100% sure but IIRC codegen is not ran when type checking fails) ...

Comment (clubby789) [reply tests/ui/offset-of/offset-of-unsized.rs]: Oops, thank you. Added a comment noting this too

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 3]
```diff
@@ -3117,16 +3117,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        && field.name == sym::integer(index)
+                    {
+                        for ty in tys.iter().take(index + 1) {
+                            self.require_type_is_sized(ty, expr.span, traits::MiscObligation);
+                        }
```
Comment (RalfJung) [inline compiler/rustc_hir_typeck/src/expr.rs:3125]: What is the reason for checking *all* fields of the tuple (that are before the indexed field)? For ADTs we only check the field we are indexing, and the same should be enough for tuples. So I don't see the point of this loop.

In https://github.com/rust-lang/rust/pull/126150 I am removing it.

Comment (clubby789) [reply compiler/rustc_hir_typeck/src/expr.rs:3125]: At this point I can't remember 🤔 I think all good if it's caught by code elsewhere
