### PR TITLE
Regression test for #56870

### LINKED ISSUE #56870: Internal compiler error (traits & associated consts)
Internal compiler error happens compiling weird code with traits and associated consts.

I tried this code:

```rust
use std::fmt::Debug;

pub trait Foo<T> {
  const FOO: *const u8;
}

impl <T: Debug> Foo<T> for Debug {
  const FOO: *const u8 = <T as Debug>::fmt as *const u8;
}

pub trait Bar {
  const BAR: *const u8;
}

pub trait Baz {
  type Data: Debug;
}

pub struct BarStruct<S: Baz>(S);

impl<S: Baz> Bar for BarStruct<S> {
  const BAR: *const u8 = <Debug as Foo<<S as Baz>::Data>>::FOO;
}

struct AnotherStruct;
#[derive(Debug)]
struct SomeStruct;

impl Baz for AnotherStruct {
  type Data = SomeStruct;
}

fn main() {
  let _x = <BarStruct<AnotherStruct> as Bar>::BAR;
}
```

I expected to see this happen: compiler not to crash

Instead, this happened: compiler crashed with:

```
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:53: could not fully normalize `for<'r, 's, 't0> fn(&'r <S as Baz>::Data, &'s mut std::fmt::Formatter<'t0>) -> std::result::Result<(), std::fmt::Error>`

thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
query stack during panic:
#0 [normalize_ty_after_erasing_regions] normalizing `ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: for<'r, 's, 't0> fn(&'r <S as Baz>::Data, &'s mut std::fmt::Formatter<'t0>) -> std::result::Result<(), std::fmt::Error> }`
#1 [const_eval_raw] const-evaluating `<(dyn std::fmt::Debug + 'static) as Foo<T>>::FOO`
  --> src/main.rs:22:26
   |
22 |   const BAR: *const u8 = <Debug as Foo<<S as Baz>::Data>>::FOO;
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#2 [optimized_mir] processing `<BarStruct<S> as Bar>::BAR`
#3 [const_eval_raw] const-evaluating `<BarStruct<S> as Bar>::BAR`
  --> src/main.rs:34:12
   |
34 |   let _x = <BarStruct<AnotherStruct> as Bar>::BAR;
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#4 [optimized_mir] processing `main`
#5 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error
```

## Meta

Playground nightly: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=59adf803ef87a6d4b1251408811542dd
Playground stable: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=59adf803ef87a6d4b1251408811542dd

### PR DESCRIPTION
**Pull request by adrian-budau**
Closes #56870.

### CODE REVIEW

File: src/test/ui/issues/issue-56870.rs [hunk 1]
```diff
@@ -0,0 +1,38 @@
+// run-pass
```
Comment (Centril) [inline src/test/ui/issues/issue-56870.rs]:
```suggestion
// build-pass
```

Comment (adrian-budau) [reply src/test/ui/issues/issue-56870.rs]: Sorry about that, fixed it! :-)

**Comment by Centril** [comment]
Thanks! r? @Centril @bors r+ rollup
