### PR TITLE
Silence `TooGeneric` error

### LINKED ISSUE #66962: Const generic ICE: constant in type had an ignored error: TooGeneric
Environment:
```
note: rustc 1.41.0-nightly (4007d4ef2 2019-12-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

The code:
```
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct Config {
    arr_size: usize
}

struct B<const CFG: Config> {
    arr: [u8; {CFG.arr_size}]
}

fn main() {
}
```
gives ICE:
```
error: internal compiler error: constant in type had an ignored error: TooGeneric
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=65de0456c6982ba362efa1fbc8b0446b)

### PR DESCRIPTION
**Pull request by varkor**
This error may be produced during intermediate failed attempts at evaluation of a generic const, which may nevertheless succeed later.

Fixes https://github.com/rust-lang/rust/issues/66962.

r? @eddyb

### CODE REVIEW

**Comment by djugei** [comment]
thank you @varkor ! a lot of my work was blocked on this :)

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -1086,6 +1087,11 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
 
             // already reported in the query
             ConstEvalFailure(err) => {
+                if let ErrorHandled::TooGeneric = err {
+                    // Silence this error, as it can be produced during intermediate steps
+                    // when a constant is not yet able to be evaluated (but will be later).
```
Comment (eddyb) [inline src/librustc/traits/error_reporting.rs]: So this is a bit like `assert_reported`, except `delay_span_bug`, and it's missing the exhaustive pattern-matching:
https://github.com/rust-lang/rust/blob/117ceeba400e69aa7b8ba5155acd1c8c0cdf7f7f/src/librustc/mir/interpret/error.rs#L30-L40

But also, I'm not sure `ConstEvalFailure` should exist anymore. Or maybe `ConstEvalFailure(ErrorHandled::TooGeneric)` should never be created (since it's not really an error).

In any case, nowadays the WF for constants is just a side-effect, as opposed to relying on error propagation, so we can probably get rid of `ConstEvalFailure`.

Comment (eddyb) [reply src/librustc/traits/error_reporting.rs]: Disregard previous comment, I'm very wrong.

**Comment by eddyb** [comment]
This PR needs to be reverted, and the ICE be replaced by a real error.

`TooGeneric` is not an error for normalization, which can keep the original form.

But for `ConstEvaluatable` WF predicates, that's what protects us from post-monomorphization errors! It forces the "burden of proof" to be bubbled up to the monomorphic users, where the constant can be evaluated during type-checking.

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/pull/68388 should fix this mistake.
