### PR TITLE
Fix suggestion for matching struct with `..` on both ends

### LINKED ISSUE #112188: Incorrect help message in matching structs with .. on both ends
### Code

```Rust
fn main() {
    struct Foo {
        x: i32,
    }

    let foo = Foo { x: 1 };
    match foo {
        Foo { .., x, .. } => (),
        _ => (),
    }
}
```

### Current output

```Shell
error: expected `}`, found `,`
 --> src\main.rs:8:17
  |
8 |         Foo { .., x, .. } => (),
  |               --^
  |               | |
  |               | expected `}`
  |               `..` must be at the end and cannot have a trailing comma
  |
help: move the `..` to the end of the field list
  |
8 -         Foo { .., x, .. } => (),
8 +         Foo { .., x,  , .. } => (),
  |
```

### Desired output
The part in `help`:
```Shell
8 -         Foo { .., x, .. } => (),
8 +         Foo { x, .. } => (),
```

### Rationale and extra context

A suggestion that can be compiled is better than the one that can't be compiled.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jieyouxu**
### Before This PR

```
error: expected `}`, found `,`
 --> src\main.rs:8:17
  |
8 |         Foo { .., x, .. } => (),
  |               --^
  |               | |
  |               | expected `}`
  |               `..` must be at the end and cannot have a trailing comma
  |
help: move the `..` to the end of the field list
  |
8 -         Foo { .., x, .. } => (),
8 +         Foo { .., x,  , .. } => (),
  |
```

### After This PR

```
error: expected `}`, found `,`
  --> tests/ui/parser/issue-112188.rs:11:17
   |
11 |     let Foo { .., x, .. } = f; //~ ERROR expected `}`, found `,`
   |               --^-
   |               | |
   |               | expected `}`
   |               `..` must be at the end and cannot have a trailing comma
   |               help: remove the starting `..`
```

Fixes #112188.

### CODE REVIEW

File: tests/ui/parser/issue-112188.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#![allow(unused)]
```
Comment (compiler-errors) [inline tests/ui/parser/issue-112188.rs:1]: Can you use `// run-rustfix` on this?

Comment (jieyouxu) [reply tests/ui/parser/issue-112188.rs:3]: I removed the `Foo { .., .. }` case since the suggestion diagnostics currently doesn't handle that.

**Review by compiler-errors — APPROVED** [review]
