### PR TITLE
Tweak obligation error output

### LINKED ISSUE #33375: Non trait object safe return diagnostic needs improvement
Here's some illegal code that generates a very reasonable error message:

```
trait Foo {
  fn apply() -> i64;
}

struct Baz{}
static BAZ: Baz = Baz{};
impl Foo for Baz {
    fn apply(&self) -> i64 { 4 }
}

// <anon>:8:5: 8:33 error: method `apply` has a `&self` declaration in the impl, but not in the trait [E0185]

```

Adding a function that references this broken trait changes the error message and is imho quite misleading:

```
fn lookup() -> Box<&'static Foo> {
    Box::new(&BAZ)
}

<anon>:11:1: 13:2 error: the trait `Foo` cannot be made into an object [E0038]
<anon>:11 fn lookup() -> Box<&'static Foo> {
<anon>:12     Box::new(&BAZ)
<anon>:13 }
<anon>:11:1: 13:2 help: see the detailed explanation for E0038
<anon>:11:1: 13:2 note: method `apply` has no receiver
```

The error code has changed from something that pinpoints exactly where I went wrong to something unrelated with advice that won't help me see my problem, and highlights the wrong place (the function that's returning this trait rather than the trait itself). Ideally the error message wouldn't change at all.

```
rustc 1.10.0-nightly (8da2bcac5 2016-04-28)
binary: rustc
commit-hash: 8da2bcac5db1e091b90cceb19d0496f0f7501c88
commit-date: 2016-04-28
host: x86_64-apple-darwin
release: 1.10.0-nightly
```

(happens on stable and beta too)

### LINKED ISSUE #38936: Suggest ?Sized on generics where applicable
I meet a compile error can be demonstrated by the following code, and think it's irrational:
```rust
trait Train {
    fn knots(&self) -> usize;
}

impl Train for str {
    fn knots(&self) -> usize {
        self.chars().count()
    }
}

fn train_length<T:Train>(text: &'static T) -> usize {
    text.knots()
}

fn str_length(text: &'static str) -> usize {
    text.knots()
}

fn main() {
    println!("{:?}", str_length("asdfas"));   // works
    println!("{:?}", train_length("asdfas")); // compile error
}
```

### LINKED ISSUE #46683: better error message when using `dyn` type
The error that you get when using a `dyn` type with a fn that expects a `Sized` type parameter is not particularly enlightening:

```rust
#![feature(dyn_trait)]

trait Something { }
impl Something for () { }

fn foo<T: Something>(_: &T) { }

fn main() {
    let x: &dyn Something = &();
    foo(x);
}
```

[yields](https://play.rust-lang.org/?gist=dabea2a82d773aad5ff7c8bb78c52eb5&version=nightly):

```
error[E0277]: the trait bound `Something: std::marker::Sized` is not satisfied
  --> src/main.rs:10:5
   |
10 |     foo(x);
   |     ^^^ `Something` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `Something`
   = note: required by `foo`
```

This came up when attempting to do some refactorings to use a `dyn Trait` where previously we had used a type parameter. I'm not exactly sure what sort of error we *should* report here -- but it seems like it'd be nice to talk about the definition site.

### LINKED ISSUE #47990: Providing a trait object as a type parameter to a function causes nonsense error
I had mistakenly written this code in crates.io: `conn.transaction::<_, CargoError, _>(...)` (note: `CargoError` is a trait). I should have written `Box<CargoError>`. That resulted in this compiler error, which makes absolutely no sense:

```
error: the `transaction` method cannot be invoked on a trait object
   --> src/user/mod.rs:546:10
    |
546 |     conn.transaction::<_, CargoError, _>(|| {
    |          ^^^^^^^^^^^
    |
    = note: another candidate was found in the following trait, perhaps add a `use` for it:
            candidate #1: `use diesel::Connection;`
```

I am not invoking the method on a trait object, nor would `use` have any effect as the `Connection` trait is already in scope. For reference, the signature of the method being called is:

```
fn transaction<T, E, F>(&self, f: F) -> Result<T, E>
where
    F: FnOnce() -> Result<T, E>,
    E: From<Error>,
```

### LINKED ISSUE #57744: Confusing error message when passing trait object to generic function
This could be the same issue as #23286 but I'm not sure.

The following code gives this error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a4b5b27510085fc74ef261ac7b66b1ca)):

```rust
use std::io::Write;

fn trait_obj(w: &dyn Write) {
    generic(w);
}

fn generic<W: Write>(_w: &W) {
}
```

```
error[E0277]: the size for values of type `dyn std::io::Write` cannot be known at compilation time
 --> src/lib.rs:4:5
  |
4 |     generic(w);
  |     ^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `dyn std::io::Write`
  = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
note: required by `generic`
 --> src/lib.rs:7:1
  |
7 | fn generic<W: Write>(_w: &W) {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

There's a couple reasons this is very confusing:

-------------------------
 ```
4 |     generic(w);
   |     ^^^^^^^ doesn't have a size known at compile-time
```

points to the function name not the parameter `w`. 

-----------------------------

```
the size for values of type `dyn std::io::Write` cannot be known at compilation time
```

`dyn Write` only appears behind a reference which means it should be sized. 

We should show a better error message when you pass a `&dyn T` value to a function expecting a generic `&T` value.

cc @munik

### LINKED ISSUE #66424: Suggest using Self in traits
I wrote the following trait: `trait Area : Sized { fn f(a : Area) -> Area; }`. What I meant (I've now discovered) was `trait Area : Sized { fn f(a : Self) -> Self; }`. However, it isn't easy to get "to that point".

Reading the pages linked to from the compiler warning, and the rust book, I didn't find anything which discussed what using the name of a trait inside the trait means -- in particular (and this was I believe the source of my confusion), it isn't like C++ where, while defining `template<typename T> vector { ... }`, we use `vector` to refer to the type we are currently defining.

I'm not suggesting a change of behaviour, but I wonder if this could be a common enough bug to say "did you mean Self?"

### PR DESCRIPTION
**Pull request by estebank**
- Point at arguments or output when fn obligations come from them, or ident when they don't
- Point at `Sized` bound (fix #47990)
- When object unsafe trait uses itself in associated item suggest using `Self` (fix #66424, fix #33375, partially address #38376, cc #61525)
-  Point at reason in object unsafe trait with `Self` in supertraits or `where`-clause (cc #40533, cc #68377)
- On implicit type parameter `Sized` obligations, suggest `?Sized` (fix #57744, fix #46683, fix #38936)

### CODE REVIEW

File: src/librustc_typeck/check/wfcheck.rs [hunk 1]
```diff
@@ -176,9 +176,74 @@ pub fn check_trait_item(tcx: TyCtxt<'_>, def_id: DefId) {
...
+                _ => false,
+            }
+        }
+        _ => false,
+    }
+}
+
+/// Detect when an object unsafe trait is referring to itself in one of its associated items.
+/// When this is done, suggest using `Self` instead.
+fn check_bare_self_trait_by_name(tcx: TyCtxt<'_>, item: &hir::TraitItem<'_>) {
```
Comment (Centril) [inline src/librustc_typeck/check/wfcheck.rs]: This presumably shouldn't be "bare".

File: src/librustc_typeck/check/wfcheck.rs [hunk 2]
```diff
@@ -176,9 +176,74 @@ pub fn check_trait_item(tcx: TyCtxt<'_>, def_id: DefId) {
...
+            return;
+        }
+        let sugg = trait_should_be_self.iter().map(|span| (*span, "Self".to_string())).collect();
+        let mut err = tcx.sess.struct_span_err(
+            trait_should_be_self,
+            "associated item referring to unboxed trait object for its own trait",
+        );
+        err.span_label(trait_name.span, "in this trait");
+        err.multipart_suggestion(
+            "you might have meant to use `Self` to refer to the materialized type",
```
Comment (Centril) [inline src/librustc_typeck/check/wfcheck.rs]: consider "implementing type" instead of "materialized type".

File: src/librustc_typeck/check/wfcheck.rs [hunk 3]
```diff
@@ -176,9 +176,74 @@ pub fn check_trait_item(tcx: TyCtxt<'_>, def_id: DefId) {
...
+            }
+        }
+        _ => {}
+    }
+    if !trait_should_be_self.is_empty() {
+        if rustc::traits::object_safety_violations(tcx, trait_def_id).is_empty() {
+            return;
+        }
+        let sugg = trait_should_be_self.iter().map(|span| (*span, "Self".to_string())).collect();
+        let mut err = tcx.sess.struct_span_err(
```
Comment (Centril) [inline src/librustc_typeck/check/wfcheck.rs]: Can be chained.

**Comment by estebank** [comment]
ping

**Comment by estebank** [comment]
cc @rust-lang/wg-diagnostics just because I'm stoked about the result :D

File: src/librustc/traits/object_safety.rs [hunk 4]
```diff
@@ -189,10 +190,14 @@ fn object_safety_violations_for_trait(
                         tcx.def_path_str(trait_def_id)
                     ),
                 );
-                match violation.span() {
-                    Some(span) => err.span_label(span, violation.error_msg()),
-                    None => err.note(&violation.error_msg()),
-                };
+                let spans = violation.spans();
```
Comment (oli-obk) [inline src/librustc/traits/object_safety.rs]: This code snippet seems to be a recurring thing, does it warrant its own method on `err`?

File: src/test/ui/issues/issue-20692.stderr [hunk 5]
```diff
@@ -1,24 +1,25 @@
 error[E0038]: the trait `Array` cannot be made into an object
   --> $DIR/issue-20692.rs:7:5
    |
-LL | trait Array: Sized {}
-   |              ----- the trait cannot require that `Self : Sized`
+LL | trait Array: Sized + Copy {}
+   |              -----   ---- the trait cannot require that `Self : Sized`
```
Comment (oli-obk) [inline src/test/ui/issues/issue-20692.stderr]: why is there a `Self : Sized` error on `Copy`?

File: src/test/ui/wf/wf-unsafe-trait-obj-match.stderr [hunk 6]
```diff
@@ -25,6 +28,9 @@ LL |         Some(()) => &S,
 error[E0038]: the trait `Trait` cannot be made into an object
   --> $DIR/wf-unsafe-trait-obj-match.rs:25:25
    |
+LL | trait Trait: Sized {}
+   |              ----- the trait cannot require that `Self : Sized`
```
Comment (oli-obk) [inline src/test/ui/wf/wf-unsafe-trait-obj-match.stderr]: so this is a bit confusing. A trait can very well require `Self: Sized`, but then you can't turn it into a `dyn Trait` anymore

**Comment by oli-obk** [comment]
The new spans are awesome!

File: src/test/ui/issues/issue-20692.stderr (hunk 5 above)
Comment (estebank) [reply src/test/ui/issues/issue-20692.stderr]: This change points at all the super traits that cause a `Sized` obligation and `Copy` is one of them. Removing `Self: Sized` would still cause the error to trigger, but it wouldn't provide a span if we didn't point at `Copy`.

File: src/test/ui/wf/wf-unsafe-trait-obj-match.stderr (hunk 6 above)
Comment (estebank) [reply src/test/ui/wf/wf-unsafe-trait-obj-match.stderr]: I didn't modify the pre-existing wording. Do you have some suggestions?

Comment (estebank) [reply src/test/ui/wf/wf-unsafe-trait-obj-match.stderr]: Changed it to

```
error[E0038]: the trait `Trait` cannot be made into an object
  --> $DIR/wf-unsafe-trait-obj-match.rs:25:25
   |
LL | trait Trait: Sized {}
   |              ----- traits that require `Self: Sized` cannot be made into an object
...
LL |     let t: &dyn Trait = match opt() {
   |                         ^^^^^^^^^^^ the trait `Trait` cannot be made into an object
   |
   = note: required because of the requirements on the impl of `std::ops::CoerceUnsized<&dyn Trait>` for `&R`
   = note: required by cast to type `&dyn Trait`
```

which is hopefully clearer.

File: src/librustc/traits/object_safety.rs (hunk 4 above)
Comment (estebank) [reply src/librustc/traits/object_safety.rs]: This comment made me realize that one of the two isn't needed.

File: src/librustc/traits/object_safety.rs [hunk 7]
```diff
@@ -75,17 +76,18 @@ impl ObjectSafetyViolation {
...
-        match *self {
+        match self {
+            ObjectSafetyViolation::SizedSelf(spans) => spans.clone(),
             ObjectSafetyViolation::AssocConst(_, span)
             | ObjectSafetyViolation::Method(_, _, span)
-                if span != DUMMY_SP =>
+                if *span != DUMMY_SP =>
             {
-                Some(span)
+                vec![*span].into()
```
Comment (matthewjasper) [inline src/librustc/traits/object_safety.rs]: There's a `smallvec::smallvec` macro for this.

File: src/librustc/traits/object_safety.rs [hunk 8]
```diff
@@ -75,17 +76,18 @@ impl ObjectSafetyViolation {
...
             }
-            _ => None,
+            _ => vec![].into(),
```
Comment (matthewjasper) [inline src/librustc/traits/object_safety.rs]:
```suggestion
            _ => smallvec![],
```
and so on.

File: src/librustc_typeck/check/wfcheck.rs [hunk 9]
```diff
@@ -176,9 +176,75 @@ pub fn check_trait_item(tcx: TyCtxt<'_>, def_id: DefId) {
...
         _ => None,
     };
+    check_object_unsafe_self_trait_by_name(tcx, &trait_item);
     check_associated_item(tcx, trait_item.hir_id, trait_item.span, method_sig);
 }
 
+fn could_be_self(trait_name: Ident, ty: &hir::Ty<'_>) -> bool {
+    match ty.kind {
+        hir::TyKind::TraitObject([trait_ref], ..) => {
+            let mut p = trait_ref.trait_ref.path.segments.iter().map(|s| s.ident);
```
Comment (matthewjasper) [inline src/librustc_typeck/check/wfcheck.rs]: This should be using `s.res.opt_def_id()`

File: src/librustc_typeck/check/wfcheck.rs [hunk 10]
```diff
@@ -176,9 +176,75 @@ pub fn check_trait_item(tcx: TyCtxt<'_>, def_id: DefId) {
...
+            match (p.next(), p.next()) {
```
Comment (matthewjasper) [inline src/librustc_typeck/check/wfcheck.rs]: Why not use `trait_ref.trait_ref.path.segments.last()`?

Comment (estebank) [reply src/librustc_typeck/check/wfcheck.rs]: Because I wanted to verify that there's a single element. It's the `Iterator` equivalent to `match slice { [ident] => {}, _ => {}}`.

File: src/librustc_typeck/check/wfcheck.rs (hunk 9 above)
Comment (estebank) [reply src/librustc_typeck/check/wfcheck.rs]: Addressed all comments.

**Comment by estebank** [comment]
Sorry for this PR becoming so big 😬, it's just addressing a bunch of intimately related issues. Each commit builds on the previous one.

**Review by oli-obk — APPROVED** [review]
Just a wording, then this lgtm

File: src/test/ui/associated-const/associated-const-in-trait.stderr [hunk 11]
```diff
@@ -1,11 +1,15 @@
 error[E0038]: the trait `Trait` cannot be made into an object
   --> $DIR/associated-const-in-trait.rs:9:6
    |
+LL | trait Trait {
+   |       ----- this trait cannot be made into an object...
 LL |     const N: usize;
-   |           - the trait cannot contain associated consts like `N`
+   |           - ...because it cannot contain associated consts like `N`
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/associated-const/associated-const-in-trait.stderr]: True. Changed.

**Comment by estebank** [comment]
> Just a wording, then this lgtm

Is that r=oli-obk? 😅

**Comment by oli-obk** [comment]
@bors r+

yes :D I'll communicate that more clearly next time
