### PR TITLE
Account for impossible bounds making seemingly unsatisfyable dyn-to-dyn casts

### LINKED ISSUE #141806: ICE:called `Result::unwrap()` on an `Err` value: NoSolution
_The code is generated by a fuzzer and reduced manually_
_I tried searching but couldn't find any related errors_

### Code

```Rust
trait Trait<T> {}
struct X;
fn func<T>(x: *const dyn Trait<X>)
where
    for<'a> T_1: Sized,
{
    let x: *const dyn Trait<T> = x as _;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.89.0-nightly (70b3f4666 2025-05-30)
binary: rustc
commit-hash: 70b3f4666e24ce22fc32f5e357dbcf85d3254e63
commit-date: 2025-05-30
host: x86_64-pc-windows-msvc
release: 1.89.0-nightly
LLVM version: 20.1.5
```

### Error output

```
error[E0412]: cannot find type `T_1` in this scope
 --> .\test.rs:5:13
  |
5 |     for<'a> T_1: Sized,
  |             ^^^ not found in this scope
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_borrowck\src\type_check\mod.rs:1546:38:
called `Result::unwrap()` on an `Err` value: NoSolution
stack backtrace:
   0:     0x7ffe27e06082 - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ffe27e06082 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe27e06082 - std::sys::backtrace::_print_fmt
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\sys\backtrace.rs:66
   3:     0x7ffe27e06082 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\sys\backtrace.rs:39
   4:     0x7ffe27e39beb - core::fmt::rt::Argument::fmt
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\core\src\fmt\rt.rs:173
   5:     0x7ffe27e39beb - core::fmt::write
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\core\src\fmt\mod.rs:1446
   6:     0x7ffe27dfb9f7 - std::io::default_write_fmt
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\io\mod.rs:639
   7:     0x7ffe27dfb9f7 - std::io::Write::write_fmt<std::sys::stdio::windows::Stderr>
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\io\mod.rs:1914
   8:     0x7ffe27e05ec5 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\sys\backtrace.rs:42
   9:     0x7ffe27e0bc5a - std::panicking::default_hook::closure$0
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\panicking.rs:300
  10:     0x7ffe27e0b9f0 - std::panicking::default_hook
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\panicking.rs:327
  11:     0x7ffe295e4939 - core[41883027321c69d]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[c6afabcd45b33dea]::Level, &str), usize), <((rustc_lint_defs[c6afabcd45b33dea]::Level, &str), usize) as core[41883027321c69d]::cmp::PartialOrd>::lt>
  12:     0x7ffe27e0c8de - std::panicking::rust_panic_with_hook
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\panicking.rs:841
  13:     0x7ffe27e0c639 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\panicking.rs:706
  14:     0x7ffe27e06e4f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\sys\backtrace.rs:168
  15:     0x7ffe27e0c23e - std::panicking::begin_panic_handler
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\panicking.rs:697
  16:     0x7ffe2b032461 - core::panicking::panic_fmt
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\core\src\panicking.rs:75
  17:     0x7ffe2b032a20 - core::result::unwrap_failed
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\core\src\result.rs:1762
  18:     0x7ffe28679067 - <rustc_borrowck[e7ef4d8e0c81bd89]::type_check::TypeChecker as rustc_middle[7d96dcf9592acf23]::mir::visit::Visitor>::visit_rvalue
  19:     0x7ffe2862b4d8 - <rustc_borrowck[e7ef4d8e0c81bd89]::type_check::TypeChecker as rustc_middle[7d96dcf9592acf23]::mir::visit::Visitor>::visit_body
  20:     0x7ffe286b7380 - <rustc_borrowck[e7ef4d8e0c81bd89]::type_check::TypeChecker as rustc_middle[7d96dcf9592acf23]::mir::visit::Visitor>::visit_const_operand
  21:     0x7ffe285d927d - rustc_borrowck[e7ef4d8e0c81bd89]::mir_borrowck
  22:     0x7ffe28d6ae4b - rustc_query_impl[678ad264131b9188]::plumbing::query_key_hash_verify_all
  23:     0x7ffe28cb05a4 - RINvNtNtCs41YRoa67ONq_18rustc_query_system5query8plumbing17try_execute_queryINtCs8T9uthRx4cC_16rustc_query_impl13DynamicConfigINtNtCs2IPh3W6Af3f_21rustc_data_structures9vec_cache8VecCacheNtNtCsCuiHuraXL5_10rustc_span6def_id10LocalDefIdINtNtNtCsaMvyobqvdvz_
  24:     0x7ffe28d745d2 - rustc_query_impl[678ad264131b9188]::plumbing::query_key_hash_verify_all
  25:     0x7ffe27e7b084 - <rustc_interface[d66ed646d922d3e3]::passes::LintStoreExpandImpl as rustc_expand[32f7ad9713d55b7b]::base::LintStoreExpand>::pre_expansion_lint
  26:     0x7ffe24443d47 - rustc_interface[d66ed646d922d3e3]::passes::analysis
  27:     0x7ffe279ce36a - <alloc[40671bb55bd7e7eb]::sync::Arc<rustc_session[1833ef01fbdfa47f]::config::OutputFilenames>>::drop_slow
  28:     0x7ffe278d3c6a - RINvNtNtCs41YRoa67ONq_18rustc_query_system5query8plumbing17try_execute_queryINtCs8T9uthRx4cC_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsaMvyobqvdvz_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  29:     0x7ffe279d4693 - rustc_query_impl[678ad264131b9188]::query_system
  30:     0x7ffe244091b4 - std[aa810135f6511839]::sys::backtrace::__rust_begin_short_backtrace::<<std[aa810135f6511839]::thread::Builder>::spawn_unchecked_<ctrlc[f2e6f1d10cfc7921]::set_handler_inner<rustc_driver_impl[e74b92f706932448]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  31:     0x7ffe24403465 - std[aa810135f6511839]::sys::backtrace::__rust_begin_short_backtrace::<<std[aa810135f6511839]::thread::Builder>::spawn_unchecked_<ctrlc[f2e6f1d10cfc7921]::set_handler_inner<rustc_driver_impl[e74b92f706932448]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  32:     0x7ffe243fed0f - RINvNtNtCseDAtLUMLJ79_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCsipq8CQmOuQ1_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCsjRb60sNhVyu_17rustc_driver_i
  33:     0x7ffe2440d53d - std[aa810135f6511839]::sys::backtrace::__rust_begin_short_backtrace::<<std[aa810135f6511839]::thread::Builder>::spawn_unchecked_<ctrlc[f2e6f1d10cfc7921]::set_handler_inner<rustc_driver_impl[e74b92f706932448]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  34:     0x7ffe27e10c3d - alloc::boxed::impl$28::call_once
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\alloc\src\boxed.rs:1966
  35:     0x7ffe27e10c3d - alloc::boxed::impl$28::call_once
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\alloc\src\boxed.rs:1966
  36:     0x7ffe27e10c3d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/70b3f4666e24ce22fc32f5e357dbcf85d3254e63/library\std\src\sys\pal\windows\thread.rs:56
  37:     0x7ffedfd37374 - BaseThreadInitThunk
  38:     0x7ffee13bcc91 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

query stack during panic:
#0 [mir_borrowck] borrow-checking `func`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes https://github.com/rust-lang/rust/issues/141806

When we have an impossible where clause like `dyn Trait<u8>: Sized`, this may make a dyn-to-dyn cast like `dyn Trait<()> -> dyn trait<u8>` to successfully type check as if it were a wide-to-thin ptr cast (discarding metadata):

https://github.com/rust-lang/rust/blob/16ad385579cebb6f7d53367c552661b6b51a4a02/compiler/rustc_hir_typeck/src/cast.rs#L862-L865

In borrowck, we are expecting that the only meaningful dyn-to-dyn cast to be a metadata-preserving wide-to-wide ptr cast, which requires that the principals of the dyn pointers are equal. Borrowck additionally assumes that these principals have already been proven equal *modulo regions*, and we thus ICE since `Trait<u8>` and `Trait<()>` do not unify:

https://github.com/rust-lang/rust/blob/16ad385579cebb6f7d53367c552661b6b51a4a02/compiler/rustc_borrowck/src/type_check/mod.rs#L1481-L1524

This PR fixes this ICE by checking whether the RHS of the cast is considered to be Sized in the environment of the MIR typeck, and if so then skipping over this dyn->dyn principal compatibility check.

r? @lcnr perhaps?

### CODE REVIEW

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -1473,22 +1474,32 @@ impl<'a, 'tcx> Visitor<'tcx> for TypeChecker<'a, 'tcx> {
...
-                                    && let ty::Dynamic(dst_tty, dst_lt, ty::Dyn) = *dst_tail.kind()
+                                if self
+                                    .infcx
+                                    .type_is_sized_modulo_regions(self.infcx.param_env, dst.ty)
+                                {
+                                    // Wide to thin ptr cast. This may even occur in an env with
+                                    // impossible predicates, such as `where dyn Trait: Sized`.
+                                    // In this case, we don't want to fall into the case below,
+                                    // since the types may not actually be equatable, but it's
+                                    // fine to perform this operation in an impossible env.
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/type_check/mod.rs]: I don't really care about enforcing that this `Sized` bound holds considering regions, since there's no meaningful way to make this do something bad.

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 2]
```diff
@@ -1473,22 +1474,32 @@ impl<'a, 'tcx> Visitor<'tcx> for TypeChecker<'a, 'tcx> {
                         let ty_from = op.ty(self.body, tcx);
                         let cast_ty_from = CastTy::from_ty(ty_from);
                         let cast_ty_to = CastTy::from_ty(*ty);
+
                         match (cast_ty_from, cast_ty_to) {
                             (Some(CastTy::Ptr(src)), Some(CastTy::Ptr(dst))) => {
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs]: while we're here, can you change this to `let Some(CastTy::Ptr(src)) = CastTy::from(ty_from) else { unreachable() };`

instead of matching on them? THis saves 2 levels of identation and it feels a bit hard to read rn

File: compiler/rustc_borrowck/src/type_check/mod.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: could slap a `prove_predicate` in this branch to check that, can't we?

I don't think it matters for soundness or anything but it feels weird to not do so here.

**Review by lcnr — COMMENTED** [review]
nit, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145620/16ad385579cebb6f7d53367c552661b6b51a4a02..3131f84bcc02b58a813fb495070ac6c5f3f03aec)*

**Comment by Zalathar** [comment]
Tracking down a failure in rollup #145833.

@bors try jobs=dist-various-2

**Comment by compiler-errors** [comment]
@bors try cancel

due to that other pr
