### PR TITLE
Suggest removing `;` for `;` within let-chains

### LINKED ISSUE #117720: let-chains parsing is not resilient to stray `;` between `let`s
### Code

```Rust
#![feature(let_chains)]
fn main() {
    if let () = ()
        && let () = ();
        && let () = ()
    {
    }
}
```

### Current output

```Shell
error: expected `{`, found `;`
 --> src/main.rs:4:23
  |
4 |         && let () = ();
  |                       ^ expected `{`
  |
note: the `if` expression is missing a block after this condition
 --> src/main.rs:3:8
  |
3 |       if let () = ()
  |  ________^
4 | |         && let () = ();
  | |______________________^
```

### Desired output

```Shell
error: expected `{`, found `;`
 --> src/main.rs:4:23
  |
4 |         && let () = ();
  |                       ^
  |                       |
  |                       expected `{`
  |                       help: remove it to parse the following `let` as part of the same chain
5 |         && let () = ()
  |         -------------- you likely meant to continue parsing the let-chain here
```

### Rationale and extra context

This is a common typo I make when hoisting an inconditional let binding into the let chain to merge two let-chains that could be one. The parser only needs to do look-ahead 1 and 2 to detect the case and recover.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sjwang05**
Fixes #117720

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2441,10 +2441,26 @@ impl<'a> Parser<'a> {
...
                     // Parse block, which will always fail, but we can add a nice note to the error
                     self.parse_block().map_err(|mut err| {
-                        err.span_note(
-                            cond_span,
-                            "the `if` expression is missing a block after this condition",
-                        );
+                        if self.prev_token == token::Semi
+                            && self.token == token::AndAnd
+                            && let maybe_let = self.look_ahead(1, |t| t.clone())
+                            && maybe_let.is_keyword(kw::Let)
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:2447]:
```suggestion
                            && self.look_ahead(1, |t| t.is_keyword(kw::Let))
```

**Review by estebank — APPROVED** [review]
r? @estebank

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (sjwang05) [reply compiler/rustc_parse/src/parser/expr.rs:2447]: I broke the check into two lines mainly to avoid doing something like this later when printing the `let` span (i.e., we can just reuse the `maybe_let`'s span):
```rust
err.span_note(
    self.token.span.to(self.look_ahead(1, |t| t.clone()),
    "you likely meant to continue parsing the let-chain starting here",
 );
```
Though I'm not sure which of the two would actually read better.

Comment (estebank) [reply compiler/rustc_parse/src/parser/expr.rs:2447]: Ah, I missed you were using the span in the label. That makes sense.
