### PR TITLE
Do not trigger `unused_{braces,parens}` lints with `yield`

### LINKED ISSUE #74883: unnecessary parentheses warning triggers for necessary parentheses around `yield` expression
I tried this code:

```rust
#![feature(generator_trait)]
#![feature(generators)]

use std::ops::Generator;

fn main() {
    let mut x = |_| {
        while let Some(val) = (yield) {
            dbg!(val);
        }
    };
    dbg!(std::pin::Pin::new(&mut x).resume(Some(5)));
    dbg!(std::pin::Pin::new(&mut x).resume(Some(6)));
    dbg!(std::pin::Pin::new(&mut x).resume(None));
}
```

I expected to see this happen: no warning

Instead, this happened:

```
warning: unnecessary parentheses around `let` scrutinee expression
 --> src/main.rs:8:31
  |
8 |         while let Some(val) = (yield) {
  |                               ^^^^^^^ help: remove these parentheses
  |
  = note: `#[warn(unused_parens)]` on by default
```

if I follow the suggestion, then compilation fails:

```
error: expected `{`, found `}`
  --> src/main.rs:11:5
   |
11 |     };
   |     ^ expected `{`
```

(`yield` takes an optional expression, not wrapping it in parentheses means the `while let` block becomes that expression, and the `while let` is then missing a block).

### Meta
- `clippy 0.0.212 (2020-07-27 76e8333)`
- `rustc 1.47.0-nightly (2020-07-27 76e83339bb619aba206e)

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #74883
r? @lcnr

### CODE REVIEW

File: src/librustc_lint/unused.rs [hunk 1]
```diff
@@ -425,6 +425,7 @@ trait UnusedDelimLint {
                     ExprKind::Ret(_) | ExprKind::Break(..) => true,
                     _ => parser::contains_exterior_struct_lit(&inner),
                 })
+            || if let ExprKind::Yield(..) = inner.kind { true } else { false }
```
Comment (lzutao) [inline src/librustc_lint/unused.rs:428]:
```suggestion
            || matches!(inner.kind, ExprKind::Yield(..))
```

Comment (lcnr) [inline src/librustc_lint/unused.rs:428]: Isn't this slightly overeager?

From what I can tell this does not warn for `foo((yield))`.

I think it should be fine to move `ExprKind::Yield` into the inner match :thinking:

Comment (JohnTitor) [reply src/librustc_lint/unused.rs]: My concern was that it emits duplicate warnings (in `BlockRetValue`?) and I haven't figured out ideal solution... But yeah it's better to warn needed cases than to reduce warnings in edge cases.
Addressed via 2e7ba78 and left some FIXME comments in the test.

**Comment by lcnr** [comment]
The duplicate errors on while are actually part of a bigger problem, the following should not warn:
```rust
fn main() {
    let mut a = Some(3);
    while let Some(ref mut v) = {a} {
        a.as_mut().map(|a| std::mem::swap(a, v));
    }
}
```
The way to fix this would be to pretty much copy what we are already doing for `If` in `check_expr` here.

If you want to do fix that as part of this PR, feel free, otherwise r=me

@bors delegate

**Comment by JohnTitor** [comment]
> The duplicate errors on while are actually part of a bigger problem

Ah, interesting! I didn't realize this case, yeah, we should fix then.

> If you want to fix that as part of this PR, feel free, otherwise r=me

I'm going to r=you as-is since I think the fix is out of context of `yield` but I'll follow-up it!
Btw, I already bors perms so you don't have to delegate me. :)

@bors r=lcnr
