### PR TITLE
Default `repr(C)` enums to `c_int` size

### LINKED ISSUE #77806: layout decided on a larger discriminant type (I32) than typeck (I16)
### Code

```Rust
#![no_std]
#![no_main]

extern crate panic_halt;

#[repr(C)]
enum Foo {
	Bar
}

#[arduino_uno::entry]
fn main() -> ! {
	loop {
	}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (38d911dfc 2020-10-09)
binary: rustc
commit-hash: 38d911dfc55a7a1eea1c80139113ed2ff0151087
commit-date: 2020-10-09
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/layout.rs:1076:21: layout decided on a larger discriminant type (I32) than typeck (I16)

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (38d911dfc 2020-10-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -C opt-level=s -C panic=abort -C lto -C debuginfo=2 -C debug-assertions=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [layout_raw] computing layout of `Foo`
#1 [lint_mod] linting top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 1 warning emitted

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
   9: rustc_middle::ty::layout::layout_raw
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::layout_raw>::compute
  11: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_query_system::query::plumbing::get_query_impl
  15: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  16: <rustc_lint::types::VariantSizeDifferences as rustc_lint::passes::LateLintPass>::check_item
  17: <rustc_lint::BuiltinCombinedModuleLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  18: rustc_hir::intravisit::Visitor::visit_nested_item
  19: rustc_lint::late::late_lint_mod
  20: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::lint_mod>::compute
  21: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::get_query_impl
  25: rustc_query_system::query::plumbing::ensure_query_impl
  26: rustc_data_structures::sync::join
  27: rustc_session::utils::<impl rustc_session::session::Session>::time
  28: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  29: rustc_session::utils::<impl rustc_session::session::Session>::time
  30: rustc_interface::passes::analysis
  31: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  32: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  33: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  34: rustc_data_structures::stack::ensure_sufficient_stack
  35: rustc_query_system::query::plumbing::get_query_impl
  36: rustc_interface::passes::QueryContext::enter
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  38: rustc_span::with_source_map
  39: rustc_interface::interface::create_compiler_and_run
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### LINKED ISSUE #107361: [AVR] 'layout decided on a larger discriminant type (I32) than typeck (I16)'
Compiling the below program:

```
#![no_std]

#[repr(C)]
pub enum A {
    MkA(B),
}

#[derive(Clone, Copy)]
#[repr(C)]
struct B {
    c: C,
}

#[derive(Clone, Copy)]
#[repr(C)]
struct C {
}
```

for an AVR target results in the following error message:

```
thread 'rustc' panicked at 'layout decided on a larger discriminant type (I32) than typeck (I16)', /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/compiler/rustc_abi/src/layout.rs:687:13
stack backtrace:
   0:     0x7fe68f7665aa - std::backtrace_rs::backtrace::libunwind::trace::hc4549fb01f77d87b
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe68f7665aa - std::backtrace_rs::backtrace::trace_unsynchronized::h05cb13333c68eb08
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe68f7665aa - std::sys_common::backtrace::_print_fmt::hb24673f184c0851c
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fe68f7665aa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hadea210d809498bd
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe68f7c83ce - core::fmt::write::hf9ad1be74a79073a
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/core/src/fmt/mod.rs:1213:17
   5:     0x7fe68f756bf5 - std::io::Write::write_fmt::had5ed065fbe61198
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/io/mod.rs:1682:15
   6:     0x7fe68f766375 - std::sys_common::backtrace::_print::hef3b235b241008f8
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fe68f766375 - std::sys_common::backtrace::print::hde0ad3d49d7fc96d
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fe68f76913f - std::panicking::default_hook::{{closure}}::h42b02c3de78aff65
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/panicking.rs:267:22
   9:     0x7fe68f768e7b - std::panicking::default_hook::h1bb8dbe2c450c437
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/panicking.rs:286:9
  10:     0x7fe692abd184 - <rustc_driver[95b46d23bf652bce]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[97748cd456f183ce]::ops::function::FnOnce<(&core[97748cd456f183ce]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fe68f76997a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf8cd3db51ac86633
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/alloc/src/boxed.rs:2002:9
  12:     0x7fe68f76997a - std::panicking::rust_panic_with_hook::hb7b7ecf2debe3baf
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/panicking.rs:692:13
  13:     0x7fe68f7696f9 - std::panicking::begin_panic_handler::{{closure}}::h9fd7ebbe2d13e884
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/panicking.rs:579:13
  14:     0x7fe68f766a5c - std::sys_common::backtrace::__rust_end_short_backtrace::h7e26d5e8c003487a
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7fe68f769402 - rust_begin_unwind
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/panicking.rs:575:5
  16:     0x7fe68f7c4d73 - core::panicking::panic_fmt::hfc11761ab6d92238
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/core/src/panicking.rs:64:14
  17:     0x7fe691400a56 - <rustc_middle[cf6fe6ed69f79de8]::ty::layout::LayoutCx<rustc_middle[cf6fe6ed69f79de8]::ty::context::TyCtxt> as rustc_abi[65244fdf3a651594]::layout::LayoutCalculator>::layout_of_struct_or_enum::<rustc_target[35f696ace4059eb1]::abi::VariantIdx, rustc_target[35f696ace4059eb1]::abi::TyAndLayout<rustc_middle[cf6fe6ed69f79de8]::ty::Ty>, rustc_ty_utils[d855c86f7954c581]::layout::layout_of_uncached::{closure#6}, core[97748cd456f183ce]::iter::adapters::flatten::Flatten<core[97748cd456f183ce]::option::IntoIter<core[97748cd456f183ce]::iter::adapters::map::Map<core[97748cd456f183ce]::iter::adapters::map::Map<core[97748cd456f183ce]::iter::adapters::map::Map<core[97748cd456f183ce]::iter::adapters::enumerate::Enumerate<core[97748cd456f183ce]::slice::iter::Iter<rustc_middle[cf6fe6ed69f79de8]::ty::VariantDef>>, <rustc_index[54eace26a57da77f]::vec::IndexVec<rustc_target[35f696ace4059eb1]::abi::VariantIdx, rustc_middle[cf6fe6ed69f79de8]::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle[cf6fe6ed69f79de8]::ty::adt::AdtDef>::discriminants::{closure#0}>, rustc_ty_utils[d855c86f7954c581]::layout::layout_of_uncached::{closure#7}::{closure#0}>>>>
  18:     0x7fe6913efc80 - rustc_ty_utils[d855c86f7954c581]::layout::layout_of
  19:     0x7fe6915767db - rustc_query_system[ba5eddfaa9110d24]::query::plumbing::get_query::<rustc_query_impl[8abc0e1465f25a18]::queries::layout_of, rustc_query_impl[8abc0e1465f25a18]::plumbing::QueryCtxt, rustc_middle[cf6fe6ed69f79de8]::dep_graph::dep_node::DepKind>
  20:     0x7fe691576363 - <rustc_query_impl[8abc0e1465f25a18]::Queries as rustc_middle[cf6fe6ed69f79de8]::ty::query::QueryEngine>::layout_of
  21:     0x7fe691af2b67 - <rustc_lint[a636c1caa3b09b71]::context::LateContext as rustc_middle[cf6fe6ed69f79de8]::ty::layout::LayoutOf>::spanned_layout_of
  22:     0x7fe691731433 - <rustc_lint[a636c1caa3b09b71]::BuiltinCombinedModuleLateLintPass as rustc_lint[a636c1caa3b09b71]::passes::LateLintPass>::check_item
  23:     0x7fe69172d2d5 - rustc_hir[2d870be94f3ae1aa]::intravisit::walk_mod::<rustc_lint[a636c1caa3b09b71]::late::LateContextAndPass<rustc_lint[a636c1caa3b09b71]::BuiltinCombinedModuleLateLintPass>>
  24:     0x7fe69172cabe - rustc_lint[a636c1caa3b09b71]::late::late_lint_mod::<rustc_lint[a636c1caa3b09b71]::BuiltinCombinedModuleLateLintPass>
  25:     0x7fe69172c7ec - rustc_lint[a636c1caa3b09b71]::lint_mod
  26:     0x7fe692020f01 - rustc_query_system[ba5eddfaa9110d24]::query::plumbing::try_execute_query::<rustc_query_impl[8abc0e1465f25a18]::queries::lint_mod, rustc_query_impl[8abc0e1465f25a18]::plumbing::QueryCtxt>
  27:     0x7fe6924760ad - <rustc_query_impl[8abc0e1465f25a18]::Queries as rustc_middle[cf6fe6ed69f79de8]::ty::query::QueryEngine>::lint_mod
  28:     0x7fe692066788 - rustc_data_structures[3bf82646017727ef]::sync::par_for_each_in::<&[rustc_hir[2d870be94f3ae1aa]::hir_id::OwnerId], <rustc_middle[cf6fe6ed69f79de8]::hir::map::Map>::par_for_each_module<rustc_lint[a636c1caa3b09b71]::late::check_crate<rustc_lint[a636c1caa3b09b71]::BuiltinCombinedLateLintPass, rustc_interface[f0071e0df2442917]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>
  29:     0x7fe692066482 - <rustc_session[7b43865df64c3c6e]::session::Session>::time::<(), rustc_lint[a636c1caa3b09b71]::late::check_crate<rustc_lint[a636c1caa3b09b71]::BuiltinCombinedLateLintPass, rustc_interface[f0071e0df2442917]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}>
  30:     0x7fe6920d405f - <rustc_session[7b43865df64c3c6e]::session::Session>::time::<(), rustc_interface[f0071e0df2442917]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  31:     0x7fe69214ec0f - <core[97748cd456f183ce]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[f0071e0df2442917]::passes::analysis::{closure#5}::{closure#1}> as core[97748cd456f183ce]::ops::function::FnOnce<()>>::call_once
  32:     0x7fe69105fce8 - <rustc_session[7b43865df64c3c6e]::session::Session>::time::<(), rustc_interface[f0071e0df2442917]::passes::analysis::{closure#5}>
  33:     0x7fe69105c746 - rustc_interface[f0071e0df2442917]::passes::analysis
  34:     0x7fe69224f15e - rustc_query_system[ba5eddfaa9110d24]::query::plumbing::try_execute_query::<rustc_query_impl[8abc0e1465f25a18]::queries::analysis, rustc_query_impl[8abc0e1465f25a18]::plumbing::QueryCtxt>
  35:     0x7fe69247358a - <rustc_query_impl[8abc0e1465f25a18]::Queries as rustc_middle[cf6fe6ed69f79de8]::ty::query::QueryEngine>::analysis
  36:     0x7fe691ce0210 - <rustc_interface[f0071e0df2442917]::passes::QueryContext>::enter::<rustc_driver[95b46d23bf652bce]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>
  37:     0x7fe691cddc84 - rustc_span[590d8702e08b269b]::with_source_map::<core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>, rustc_interface[f0071e0df2442917]::interface::run_compiler<core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>, rustc_driver[95b46d23bf652bce]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  38:     0x7fe691cd66a4 - <scoped_tls[f4bd44dfe0f30b85]::ScopedKey<rustc_span[590d8702e08b269b]::SessionGlobals>>::set::<rustc_interface[f0071e0df2442917]::interface::run_compiler<core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>, rustc_driver[95b46d23bf652bce]::run_compiler::{closure#1}>::{closure#0}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>
  39:     0x7fe691cd5da2 - std[3136dbe5650cc209]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f0071e0df2442917]::util::run_in_thread_pool_with_globals<rustc_interface[f0071e0df2442917]::interface::run_compiler<core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>, rustc_driver[95b46d23bf652bce]::run_compiler::{closure#1}>::{closure#0}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>
  40:     0x7fe691cd5b4a - <<std[3136dbe5650cc209]::thread::Builder>::spawn_unchecked_<rustc_interface[f0071e0df2442917]::util::run_in_thread_pool_with_globals<rustc_interface[f0071e0df2442917]::interface::run_compiler<core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>, rustc_driver[95b46d23bf652bce]::run_compiler::{closure#1}>::{closure#0}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[97748cd456f183ce]::result::Result<(), rustc_errors[780dd287a8056c57]::ErrorGuaranteed>>::{closure#1} as core[97748cd456f183ce]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fe68f773833 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3384d9be08768d2e
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/alloc/src/boxed.rs:1988:9
  42:     0x7fe68f773833 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfcd870ad56c96f75
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/alloc/src/boxed.rs:1988:9
  43:     0x7fe68f773833 - std::sys::unix::thread::Thread::new::thread_start::hb742e799f6e8b754
                               at /rustc/c8e6a9e8b6251bbc8276cb78cabe1998deecbed7/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7fe68f494b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  45:     0x7fe68f526a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  46:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (c8e6a9e8b 2023-01-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [layout_of] computing layout of `A`
#1 [lint_mod] linting top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
```

### PR DESCRIPTION
**Pull request by workingjubilee**
This is what ISO C strongly implies this is correct, and
many processor-specific ABIs imply or mandate this size, so
"everyone" (LLVM, gcc...) defaults to emitting enums this way.
However, this is by no means guaranteed by ISO C,
and the bare-metal Arm targets show it can be overridden,
which rustc supports via `c-enum-min-bits` in a target.json.

The override is a flag named `-fshort-enums` in clang and gcc,
but introducing a CLI flag is probably unnecessary for rustc.
This flag can be used by non-Arm microcontroller targets,
like AVR and MSP430, but it is not enabled for them by default.
Rust programmers who know the size of a target's enums
can use explicit reprs, which also lets them match C23 code.

This change is most relevant to 16-bit targets: AVR and MSP430.
Most of rustc's targets use 32-bit ints, but ILP64 does exist.
Regardless, rustc should now correctly handle enums for
both very small and very large targets.

Thanks to William for confirming MSP430 behavior,
and to Waffle for better style and no-core `size_of` asserts.

Fixes rust-lang/rust#107361
Fixes rust-lang/rust#77806

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler

**Comment by workingjubilee** [comment]
cc @Rahix re: vibe-checking this AVR-related PR since it will affect the pile of target-spec.jsons that you maintain in avr-hal.

**Comment by Rahix** [comment]
Change looks reasonable to me.  Re. target-specs, we derive ours from the upstream one using a small python script.  I'll just re-synchronize once we update to a more recent nightly.  But for now we are still blocked on #106619, anyway...

**Comment by jackh726** [comment]
Sorry, not my area of expertise...

r? compiler

**Comment by cjgillot** [comment]
I don't know anything about AVR either. @workingjubilee do you have somebody in mind for the review?
@jonas-schievink I saw you approved #76364, can you help?

**Comment by workingjubilee** [comment]
Jonas is an alumnus (and thank you).

I believe for one reason or another a lot of the people who are very active contributors regarding these targets (e.g. @dylanmckay, @cr1901, @Patryk27) are usually not formal Rust team members and of those who are more active with the Embedded WG they don't necessarily have a ton of active review cycles. Which is why I just tagged in Rahix.

File: compiler/rustc_target/src/spec/mod.rs [hunk 1]
```diff
@@ -2587,12 +2582,21 @@ impl Target {
...
         key!(supported_sanitizers, SanitizerSet)?;
         key!(default_adjusted_cabi, Option<Abi>)?;
-        key!(c_enum_min_bits, u64);
         key!(generate_arange_section, bool);
         key!(supports_stack_protector, bool);
         key!(entry_name);
         key!(entry_abi, Conv)?;
 
+        if let Some(s) = obj
+            .remove(&(stringify!(c_enum_min_bits)).replace("_", "-"))
```
Comment (WaffleLapkin) [inline compiler/rustc_target/src/spec/mod.rs:2591]: `stringify` and `replace` are probably unnecessary, wouldn't it be simpler to write `"c-enum-min-bits"` here directly?

File: compiler/rustc_target/src/spec/mod.rs [hunk 2]
```diff
@@ -1702,6 +1702,7 @@ pub struct TargetOptions {
     pub default_adjusted_cabi: Option<Abi>,
 
     /// Minimum number of bits in #[repr(C)] enum. Defaults to 32.
+    // Is it possible this should default to c_int_width?
```
Comment (WaffleLapkin) [inline compiler/rustc_target/src/spec/mod.rs:1705]: if I understood the code down below correctly, `c_int_width` is the actual default now, right?

File: tests/ui/repr/16-bit-repr-c-enum.rs [hunk 3]
```diff
@@ -0,0 +1,27 @@
+// build-pass
+// revisions: avr msp430
+//
+// [avr] needs-llvm-components: avr
+// [avr] compile-flags: --target=avr-unknown-gnu-atmega328 --crate-type=rlib
+// [msp430] needs-llvm-components: msp430
+// [msp430] compile-flags: --target=msp430-none-elf --crate-type=rlib
+#![feature(no_core, lang_items)]
+#![no_std]
+#![no_core]
```
Comment (WaffleLapkin) [inline tests/ui/repr/16-bit-repr-c-enum.rs:10]: Why do we need this? To prevent this test from failing when `core` can't be compiled for these targets?

File: tests/ui/repr/16-bit-repr-c-enum.rs [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+#![no_main]
```
Comment (WaffleLapkin) [inline tests/ui/repr/16-bit-repr-c-enum.rs:11]: A nitpick: imo `#![crate_type = "lib"]` would be better here...

File: compiler/rustc_target/src/spec/mod.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_target/src/spec/mod.rs:2591]: Also, pre-existing so not for this PR, but I'm surprised this just silently ignores deserialization failures...

**Review by WaffleLapkin — COMMENTED** [review]
I'm not entirely sure what are the implications here, but from what I could find this seems like a correct solution.

I think this will be good to go after a couple of nitpicks and doc fixes.

r? @WaffleLapkin

**Comment by cr1901** [comment]
>people who are very active contributors regarding these targets... are usually not formal Rust team members

I'm not aware of the process of becoming a formal team member for maintaining msp430. I just open bug reports and bisect when I notice the compiler pessimizes or otherwise breaks msp430 codegen. I also have little bandwidth to fix LLVM errors at present. Is this enough to be considered a maintainer if I [add](https://doc.rust-lang.org/rustc/platform-support/TEMPLATE.html) target-specific documentation?

Anyways, this PR looks fine to me. The below sample code compiles on `msp430-elf-gcc` (will test `clang` once I get past my build scripts getting a bit stale...)

## Makefile
```Makefile
include include.mk

all: enum.elf

elf-info: enum.elf
        msp430-elf-objdump -D enum.elf > enum.lst
        msp430-elf-readelf -a --wide enum.elf > enum.sym
        msp430-elf-size -A enum.elf

enum.S: enum.c
        $(CC) -c $(CFLAGS) -S -o enum.S -I$(MSPINC) enum.c

enum.o: enum.S
        $(CC) -c $(CFLAGS) -o enum.o -I$(MSPINC) enum.S

enum.elf: enum.o
        $(CC) $(LDFLAGS) -o enum.elf -L$(MSPINC) enum.o

prog: enum.elf
        mspdebug $(MSPDRV) "prog enum.elf"

clean:
        rm -rf enum.elf enum.o enum.lst enum.sym enum.S
```

## include.mk.sample
```
MSPINC=/path/to/include # https://github.com/pftbest/msp430_svd
MSPMCU=msp430g2211 # Define to desired micro to build on.
MSPDRV=rf2500 # tilib, etc. Input to mspdebug.

# GCC invocation
CC=msp430-elf-gcc
CFLAGS=-Os -mmcu=$(MSPMCU)
LDFLAGS=-mcpu=msp430 -Wl,-T$(MSPMCU).ld # Work around possible driver bug with -mcpu=msp430.
# -mmcu=$(MSPMCU) also works in place of both these options.

# Clang invocation- requires existing GCC.
# GCC_TOOLCHAIN=/path/to/gcc/toolchain # This can't be automated if not installing clang.
# CC=clang --target=msp430 --gcc-toolchain=$(GCC_TOOLCHAIN) # Or /path/to/clang if using clang's build directory.
# CFLAGS=-Os -mmcu=$(MSPMCU)
# LDFLAGS=-Wl,-T$(MSPMCU).ld # No such option -mcpu=msp430.
# -mmcu=$(MSPMCU) also works in place of providing a linker script.
```

## enum.c
```c
#include <assert.h>

enum foo
{
    BAR
};


int main(void)
{
    static_assert(sizeof(enum foo) == 2);
}
```

File: tests/ui/repr/16-bit-repr-c-enum.rs (hunk 3 above)
Comment (workingjubilee) [reply tests/ui/repr/16-bit-repr-c-enum.rs:10]: Honestly I was just getting mysterious compilation errors while trying to build `core`, yeah.

File: compiler/rustc_target/src/spec/mod.rs (hunk 2 above)
Comment (workingjubilee) [reply compiler/rustc_target/src/spec/mod.rs:1705]: For targets we take in via a `target-spec.json`, yes.

At the time I kept failing to parse out how to make it happen correctly for builtin targets as well and had initially resolved to fix it later since this only affects 2 builtin targets but if you want I can fix it Properly, I'll just have to take a second look at things, here.

**Comment by workingjubilee** [comment]
TODO: Fixup `c_enum_min_bits` to always work like that, not just when pulled from a target.json

File: compiler/rustc_target/src/spec/mod.rs (hunk 2 above)
Comment (workingjubilee) [reply compiler/rustc_target/src/spec/mod.rs]: I have had a proper look at things.

File: compiler/rustc_target/src/spec/mod.rs [hunk 5]
```diff
@@ -1344,8 +1344,19 @@ impl Target {
             });
         }
 
-        dl.c_enum_min_size = match Integer::from_size(Size::from_bits(self.c_enum_min_bits)) {
-            Ok(bits) => bits,
+        dl.c_enum_min_size = match self
```
Comment (WaffleLapkin) [inline compiler/rustc_target/src/spec/mod.rs:1347]: Can this `match` be replaced with `.map_err(|err| TargetDataLayoutErrors::InvalidBitsSize { err })?`?

File: compiler/rustc_target/src/spec/mod.rs [hunk 6]
```diff
@@ -1344,8 +1344,19 @@ impl Target {
...
+            .c_enum_min_bits
+            .map_or_else(
+                || {
+                    self.c_int_width
+                        .parse()
+                        .map_err(|_| String::from("failed to parse c_int_width"))
+                },
+                |o| Ok(o),
```
Comment (WaffleLapkin) [inline compiler/rustc_target/src/spec/mod.rs:1355]:
```suggestion
                Ok,
```

**Review by WaffleLapkin — COMMENTED** [review]
A couple of tiny nits and I think this is good to go, r=me when ready.

File: compiler/rustc_target/src/spec/mod.rs (hunk 5 above)
Comment (workingjubilee) [reply compiler/rustc_target/src/spec/mod.rs:1347]: Apparently yes. I had tried that several times but it didn't work before. I guess it decided working now is fine.
