### PR TITLE
Fix ret > 1 bound if shadowed by const

### LINKED ISSUE #93553: Associated const with supertrait associated type (named the same) causes ICE
### Code

```Rust
trait Foo {
    type Bar;
}

trait Baz: Foo {
    const Bar: Self::Bar;
}
```

### Meta

rust version:
```
1.60.0-nightly (2022-01-31 498eeb72f590e518e197)
```
(tried in the play.rust-lang.org playground)

This compiles successfully on the stable and beta channels.

### Error output

```

error[E0221]: ambiguous associated type `Bar` in bounds of `Self`
 --> src/lib.rs:6:16
  |
2 |     type Bar;
  |     --------- ambiguous `Bar` from `Foo`
...
6 |     const Bar: Self::Bar;
  |                ^^^^^^^^^ ambiguous associated type `Bar`
  |
  = note: associated type `Self` could derive from `Baz`
help: use fully qualified syntax to disambiguate
  |
6 |     const Bar: <Self as Foo>::Bar;
  |                ~~~~~~~~~~~~~~~

thread 'rustc' panicked at 'missing associated type', compiler/rustc_typeck/src/astconv/mod.rs:1886:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (498eeb72f 2022-01-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] computing type of `Baz::Bar`
#1 [collect_mod_item_types] collecting item types in top-level module
end of query stack
For more information about this error, try `rustc --explain E0221`.
error: could not compile `playground` due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'missing associated type', compiler/rustc_typeck/src/astconv/mod.rs:1886:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:135:14
   2: core::panicking::panic_display
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:65:5
   3: core::panicking::panic_str
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/option.rs:1840:5
   5: <dyn rustc_typeck::astconv::AstConv>::associated_path_to_ty
   6: <dyn rustc_typeck::astconv::AstConv>::ast_ty_to_ty_inner
   7: rustc_typeck::collect::type_of::type_of
   8: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
   9: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_trait_item
  10: <rustc_middle::hir::map::Map>::visit_item_likes_in_module::<rustc_hir::intravisit::DeepVisitor<rustc_typeck::collect::CollectItemTypesVisitor>>
  11: rustc_typeck::collect::collect_mod_item_types
  12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  13: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::collect_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
  14: <rustc_middle::hir::map::Map>::for_each_module::<rustc_typeck::check_crate::{closure#0}::{closure#0}::{closure#0}>
  15: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#0}, ()>
  16: rustc_typeck::check_crate
  17: rustc_interface::passes::analysis
  18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorReported>>>
  19: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  20: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorReported>>
  21: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JulianKnodt**
Prior to a change, it would only look at types in bounds. When it started looking for consts,
shadowing type variables with a const would cause an ICE, so now defer looking at consts only if
there are no types present.

cc @compiler-errors
Should Fix #93553

### CODE REVIEW

File: compiler/rustc_typeck/src/astconv/mod.rs [hunk 1]
```diff
@@ -1657,11 +1658,14 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
         let mut matching_candidates = all_candidates()
-            .filter(|r| self.trait_defines_associated_named(r.def_id(), assoc_name));
-
-        let bound = match matching_candidates.next() {
-            Some(bound) => bound,
-            None => {
+            .filter(|r| self.trait_defines_associated_type_named(r.def_id(), assoc_name));
+        let mut const_candidates = all_candidates()
+            .filter(|r| self.trait_defines_associated_const_named(r.def_id(), assoc_name));
+
```
Comment (JulianKnodt) [inline compiler/rustc_typeck/src/astconv/mod.rs:1664]: This is the main fix, the rest should make it more carefully stick to logic prior the change.

**Comment by compiler-errors** [comment]
Can you verify that the compiler doesn't ICE in situations like:

```rust
trait Baz {
  const Bar: usize;
  const Qux: Self::Bar;
}
```

**Comment by JulianKnodt** [comment]
I don't think it should ice in that case since there's no shadowing and no name overlaps, but will add a test in

**Comment by JulianKnodt** [comment]
oh it does ice, I'll look into it a bit further

**Comment by compiler-errors** [comment]
I think the stack trace points to an `.expect` so you can find where it ICEs. I think it's in a method that resolves a path to a ty, maybe you want to check if it resolves to a const instead and emit an error. Maybe something like this:

```rust
trait Baz {
  const Bar: usize;
  const Qux: Self::Bar;
//           ^ Expected type, found const
}
```

**Comment by JulianKnodt** [comment]
yuh, i'm not sure if the best way to fix it is to turn the expect into an actual error, or handle it earlier, for now I can just turn it into an error and if the reviewer knows better I'll update

File: compiler/rustc_typeck/src/astconv/mod.rs [hunk 2]
```diff
@@ -1893,14 +1906,17 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
-            })
-            .expect("missing associated type");
+        let item = tcx.associated_items(trait_did).in_definition_order().find(|i| {
+            i.kind.namespace() == Namespace::TypeNS
+                && i.ident(tcx).normalize_to_macros_2_0() == assoc_ident
+        });
+        // Assume that if it's not matched, there must be a const defined with the same name
+        // but it was used in a type position.
+        let Some(item) = item else {
+            let msg = format!("found associated const {assoc_ident} when type was expected");
```
Comment (oli-obk) [inline compiler/rustc_typeck/src/astconv/mod.rs:1916]:
```suggestion
            let msg = format!("found associated const `{assoc_ident}` when type was expected");
```

File: compiler/rustc_typeck/src/astconv/mod.rs [hunk 3]
```diff
@@ -1145,13 +1140,19 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
 
         // We have already adjusted the item name above, so compare with `ident.normalize_to_macros_2_0()` instead
         // of calling `filter_by_name_and_kind`.
-        let assoc_item = tcx
-            .associated_items(candidate.def_id())
-            .filter_by_name_unhygienic(assoc_ident.name)
+        let filtered_assoc_items =
+            || tcx.associated_items(candidate.def_id()).filter_by_name_unhygienic(assoc_ident.name);
```
Comment (oli-obk) [inline compiler/rustc_typeck/src/astconv/mod.rs:1144]: pass in the kind you're looking for as an argument and include the `find` part in the closure, too.

File: compiler/rustc_typeck/src/astconv/mod.rs [hunk 4]
```diff
@@ -1673,92 +1677,101 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
-                    .associated_items(bound_id)
-                    .find_by_name_and_kind(self.tcx(), assoc_name, ty::AssocKind::Type, bound_id)
-                    .and_then(|item| self.tcx().hir().span_if_local(item.def_id));
-
-                if let Some(bound_span) = bound_span {
-                    err.span_label(
-                        bound_span,
-                        format!(
-                            "ambiguous `{}` from `{}`",
+        let next_cand = if is_ty { matching_candidates.next() } else { const_candidates.next() };
```
Comment (oli-obk) [inline compiler/rustc_typeck/src/astconv/mod.rs:1680]: instead of having this `is_ty` variable, return `next_cand` directly from the match where you return `bound`.

File: compiler/rustc_typeck/src/astconv/mod.rs [hunk 5]
```diff
@@ -1673,92 +1677,101 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+        match next_cand {
+            None => (),
+            Some(bound2) => {
```
Comment (oli-obk) [inline compiler/rustc_typeck/src/astconv/mod.rs:1683]: please revert the `if let` -> `match` change and resulting indentation changes and squash them away.

**Review by oli-obk — CHANGES_REQUESTED** [review]
