### PR TITLE
rustc_typeck: enforce argument type is sized

### LINKED ISSUE #42312: ICE defining function taking raw trait object
The following code:

```rust
pub fn f(_: ToString) {}

fn main() {}
```

Produces the following in the [playground](https://play.rust-lang.org/?code=pub%20fn%20f(_%3A%20ToString)%20{}%0A%0Afn%20main()%20{}):

```
rustc 1.17.0 (56124baa9 2017-04-24)
Incorrect number of arguments passed to called function!
  invoke void @_ZN4drop17h87bc09ef66481f99E(i8* %3)
          to label %bb1 unwind label %cleanup, !dbg !18
LLVM ERROR: Broken function found, compilation aborted!
```

```
rustc 1.18.0-beta.4 (0308c9865 2017-05-27)
Segmentation fault (core dumped)
```

```
rustc 1.19.0-nightly (5de00925b 2017-05-29)
rustc: /checkout/src/llvm/include/llvm/Support/Casting.h:95: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::Constant; From = llvm::Value]: Assertion `Val && "isa<> used on a null pointer"' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by venkatagiri**
closes #42312 

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -995,16 +995,16 @@ fn check_fn<'a, 'gcx, 'tcx>(inherited: &'a Inherited<'a, 'gcx, 'tcx>,
...
-        // currently only results in warnings, so we issue an
-        // old-style WF obligation here so that we still get the
-        // errors that we used to get.
-        fcx.register_old_wf_obligation(arg_ty, arg.pat.span, traits::MiscObligation);
-
         // Check the pattern.
         fcx.check_pat_arg(&arg.pat, arg_ty, true);
+
+        // Check that argument is Sized.
+        // Hack to avoid duplicate warnings for simple cases like `fn foo(x: Trait)`, where we
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: Nit: can you modify this to say "the check for a non-trivial pattern is a hack to avoid..."? Otherwise, it seems like this whole test is a hack, which isn't quite right.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks good! just one minor nit.

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (venkatagiri) [inline src/librustc_typeck/check/mod.rs]: On it.

**Comment by venkatagiri** [comment]
@nikomatsakis I have fixed the comment.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

Nice!

**Comment by venkatagiri** [comment]
@nikomatsakis A run-pass test failed in CI.
The `Target` type in `Deref` trait is optionally `Sized`.
This feels like a genuine error which should be compiling.

```bash
[00:54:08] error[E0277]: the trait bound `<Self as std::ops::Deref>::Target: std::marker::Sized` is not satisfied
[00:54:08]   --> /checkout/src/test/run-pass/associated-types-sugar-path.rs:19:29
[00:54:08]    |
[00:54:08] 19 |     fn baz(_: Self::Target) where Self: Deref {}
[00:54:08]    |                             ^ `<Self as std::ops::Deref>::Target` does not have a constant size known at compile-time
[00:54:08]    |
[00:54:08]    = help: the trait `std::marker::Sized` is not implemented for `<Self as std::ops::Deref>::Target`
[00:54:08]    = help: consider adding a `where <Self as std::ops::Deref>::Target: std::marker::Sized` bound
[00:54:08] 
[00:54:08] error: aborting due to previous error(s)
```

**Comment by rkruppe** [comment]
I recall (but cannot find right now) discussion about the `Target: ?Sized` bound. IIRC it was decided to not remove the bound precisely because starting to require `Target: Sized` would allow code to rely on it and then we couldn't generalize `Deref` to accept unsized indices (if/once DSTs can be passed by value). Maybe that decision should be revised, or maybe that test should just be changed to require `Target: Sized` at the use site.

**Comment by nikomatsakis** [comment]
>  This feels like a genuine error which should be compiling.

I do not think this code should type-check. But I do think it's probably worth doing a crater run -- we may need a warning cycle here.

**Comment by nikomatsakis** [comment]
Commenced crater run:

- [ ] [Building toolchain](https://tools.taskcluster.net/task-inspector/#FxaVRsbKTESEjGoiF1yR5w/)
- [ ] [Building toolchain](https://tools.taskcluster.net/task-inspector/#7i0tq9cYR5i5BI1l06Gkiw/)
- [ ] Testing crates
- [ ] Testing crates
- [ ] Generate report

**Comment by nikomatsakis** [comment]
Crater report:


* From: 03abb1bd70ac56e4aba0684bab819892a0157843
* To: 589a377116d33dca515a8347842c808f96055bb9

## Coverage

* 9856 crates tested: 7595 working / 2148 broken / 17 regressed / 14 fixed / 82 unknown.

## Root regressions, sorted by rank:

* [phf-0.7.21](https://crates.io/crates/phf) ([before](https://tools.taskcluster.net/task-inspector/#GDa2_z2MQh2f9tgGrnwifQ)) ([after](https://tools.taskcluster.net/task-inspector/#Rln9skLIQR29hXdhNCYOHQ))
* [maplit-0.1.4](https://crates.io/crates/maplit) ([before](https://tools.taskcluster.net/task-inspector/#ZbGEFXfOS2GroUM4veeaMg)) ([after](https://tools.taskcluster.net/task-inspector/#hT1Ia7zhSMu5aB-tRpAb5w))
* [r2d2_redis-0.6.0](https://crates.io/crates/r2d2_redis) ([before](https://tools.taskcluster.net/task-inspector/#qLxsy3j8TmWh1dZlEiiaOg)) ([after](https://tools.taskcluster.net/task-inspector/#65AGEhsRTBmD-5JZe-eovg))
* [screenruster-saver-0.1.8](https://crates.io/crates/screenruster-saver) ([before](https://tools.taskcluster.net/task-inspector/#AmT4Ri_cSvWx4lGsdwxeZA)) ([after](https://tools.taskcluster.net/task-inspector/#WybxNp1lTfCdA6CFD1dg8A))
* [mitochondria-1.1.2](https://crates.io/crates/mitochondria) ([before](https://tools.taskcluster.net/task-inspector/#ssFtjDEFTWuvEJKPmrXQJQ)) ([after](https://tools.taskcluster.net/task-inspector/#c8LFvmSTSsiVpyxCU1Jh5Q))
* [k2hash-sys-0.0.1](https://crates.io/crates/k2hash-sys) ([before](https://tools.taskcluster.net/task-inspector/#Ly7arAJJRbyUjIavJ7Vh1w)) ([after](https://tools.taskcluster.net/task-inspector/#LEQZXLX_T36zI9Vl502F-A))
* [kbgpg-0.1.1](https://crates.io/crates/kbgpg) ([before](https://tools.taskcluster.net/task-inspector/#jcT4ehi1Tw6PJlPs53ohFw)) ([after](https://tools.taskcluster.net/task-inspector/#htlRWxdYR9qwcUCw0ybGSw))
* [accel-mma84-0.2.0](https://crates.io/crates/accel-mma84) ([before](https://tools.taskcluster.net/task-inspector/#FmdrQw-xRrCgz9Hl1g8XYQ)) ([after](https://tools.taskcluster.net/task-inspector/#4co7Rl6ATTC_zpJH66Mxyg))
* [ntree-0.1.0](https://crates.io/crates/ntree) ([before](https://tools.taskcluster.net/task-inspector/#H1KOtFRJTgqgrnKjk57ygQ)) ([after](https://tools.taskcluster.net/task-inspector/#HdM17szlRXaaJu9lr12tqw))
* [primapalooza-0.3.4](https://crates.io/crates/primapalooza) ([before](https://tools.taskcluster.net/task-inspector/#3HSs2LAxQp6DppQ_NNV96A)) ([after](https://tools.taskcluster.net/task-inspector/#j62V69_BRLq6E_0mDiiDLw))
* [rmp-rpc-0.0.5](https://crates.io/crates/rmp-rpc) ([before](https://tools.taskcluster.net/task-inspector/#M_JaFNTwSoGwiDul04xjkQ)) ([after](https://tools.taskcluster.net/task-inspector/#K2daJPCDTXOXbg3K6zjugw))
* [bmp085-0.1.1](https://crates.io/crates/bmp085) ([before](https://tools.taskcluster.net/task-inspector/#5s6LlcGaQ36LxGMCfiSAGg)) ([after](https://tools.taskcluster.net/task-inspector/#_5vBiRpcR1yueluzJYrPkA))
* [bondage-0.0.0](https://crates.io/crates/bondage) ([before](https://tools.taskcluster.net/task-inspector/#fw-MiYz9SZeztKJEtTqoZQ)) ([after](https://tools.taskcluster.net/task-inspector/#NRj6Av97Ro2YLV41ZmyxCw))
* [sqlpop-0.3.0](https://crates.io/crates/sqlpop) ([before](https://tools.taskcluster.net/task-inspector/#AxeHUv5HSJerv_4qxHO4sA)) ([after](https://tools.taskcluster.net/task-inspector/#d5eiXcIbT6i1UHhKoMZF8w))
* [tak-0.6.1](https://crates.io/crates/tak) ([before](https://tools.taskcluster.net/task-inspector/#-rvLAaErS7uXq0atyVKtmg)) ([after](https://tools.taskcluster.net/task-inspector/#_s8zyyAYS5Ku8vcOrzZWYA))
* [tokio-reserve-0.0.0](https://crates.io/crates/tokio-reserve) ([before](https://tools.taskcluster.net/task-inspector/#CbVBzBntT52VuSJEKHU7BA)) ([after](https://tools.taskcluster.net/task-inspector/#wc5PYma9SSOEPYmTaAnPwQ))

**Comment by nikomatsakis** [comment]
Everything appears to be false positives. @venkatagiri I think we're good to go, if you just want to adjust that failing test.

**Comment by venkatagiri** [comment]
@nikomatsakis An UI test is failing now. [src/test/ui/type-check/unknown_type_for_closure.rs](https://github.com/cengizIO/rust/blob/master/src/test/ui/type-check/unknown_type_for_closure.rs). Error difference is below. Should my PR be affecting this type error?

```bash
diff of stderr:

 error[E0282]: type annotations needed
-  --> $DIR/unknown_type_for_closure.rs:12:14
+  --> $DIR/unknown_type_for_closure.rs:12:17
    |
 12 |     let x = |_| {    };
-   |              ^ consider giving this closure parameter a type
+   |                 ^ cannot infer type for `_`

 error: aborting due to previous error(s)

```

**Comment by nikomatsakis** [comment]
@venkatagiri hmm. So I'm a bit surprised that this code would be affected, but it's certainly possible. What's going wrong in this particular case is that the type of this argument is an uninferred type variable (i.e., unconstrained). There is some logic [here](https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs#L928) that tries to special-case `?T: Sized` obligations, where `?T` is an unresolved type variable, and print them in a nice way. The first question to figure out is whether this logic is still triggering -- basically, is `need_type_info()` getting called? If so, then we would want to figure out why `need_type_info()` is not detect and printing the nicer error anymore.

**Comment by venkatagiri** [comment]
@nikomatsakis The `need_type_info` is indeed getting called. But, while it is doing [`visit_expr`](https://github.com/rust-lang/rust/blob/master/src/librustc/infer/error_reporting/need_type_info.rs#L109), it is supposed to reach [`visit_body`](https://github.com/rust-lang/rust/blob/master/src/librustc/infer/error_reporting/need_type_info.rs#L65), where `found_arg_pattern` should get updated but it is not reaching that. `visit_body` isn't even getting called(when earlier it used to). I couldn't quite understand all the `walk_`s happening.
Please let me know how I could move forward in debugging this one.

**Comment by nikomatsakis** [comment]
Ah, very interesting. Can you maybe add a `debug!` to extract the result of `self.tcx.hir.find(body_id.node_id)`?

**Comment by venkatagiri** [comment]
@nikomatsakis 
```
...
DEBUG:rustc::ty::maps: ty::queries::extern_crate::try_get_with(key=DefId { krate: CrateNum(1), node: DefIndex(0) => std/8dd0374 }, span=src/test/ui/type-check/unknown_type_for_closure.rs:1:1: 1:1)
DEBUG:rustc::traits::error_reporting: maybe_report_ambiguity(predicate=Binder(TraitPredicate(<_ as std::marker::Sized>)), obligation=Obligation(predicate=Binder(TraitPredicate(<_ as std::marker::Sized>)),depth=0))
DEBUG:rustc::infer: is_tainted_by_errors(err_count=0, err_count_on_creation=0, tainted_by_errors_flag=false)
DEBUG:rustc::ty::fold: HasTypeFlagsVisitor: t=_ t.flags=c04 self.flags=80
DEBUG:rustc::ty::fold: HasTypeFlagsVisitor: t=_ t.flags=c04 self.flags=c
DEBUG:rustc::ty::fold: HasTypeFlagsVisitor: t=_ t.flags=c04 self.flags=4
DEBUG:rustc::infer::error_reporting::need_type_info: self.tcx.hir.find >> Some(NodeExpr(expr(13: { })))
error[E0282]: type annotations needed
  --> src/test/ui/type-check/unknown_type_for_closure.rs:12:17
   |
12 |     let x = |_| {    };
   |                 ^ cannot infer type for `_`

DEBUG:rustc_typeck::check::regionck: regionck_fn(id=4)
...
```

**Comment by arielb1** [comment]
So the problem is that `need_type_info` is using the body-id of the closure instead of that of the outer function. How easy would it be to plumb the body of the function to it, through `report_fulfillment_errors` etc?

**Comment by venkatagiri** [comment]
@arielb1 Could you please provide some mentoring instructions on how I can go about plumbing the body of function through `report_fulfillment_errors`? I am new to working on compiler.

**Comment by arielb1** [comment]
@venkatagiri 

The "body of a function" - the "code" within a function's block - is represented by a [BodyId]. `need_type_info` uses the `BodyId` to [get the HIR of the function] and run over it to get the correct field. The problem here is that `need_type_info` gets the body of the closure instead of the body of the containing fn, so in your case:

```Rust
fn main()
{ // we want this body
    let x = |_|
    { // but currently we get this, which misses the _ arg
    };
}

```

We need to pass `need_type_info` the `BodyId` of the "type-checking item", so when it iterates it will find all the fields. An item-level function being type-checked is stored in the [Inherited] (the [FnCtxt] represents the *closure* being checked, which would bring us back to our current problem). 

`Inherited` does not store the `BodyId` right now, but its [constructor] does have access to the `BodyId` of it, so you'll need to store that in the `Inherited`.

Then you'll only need to pass that `BodyId` all the way to `need_type_info`. The call stack goes through these functions:
 * [infer::error_reporting::need_type_info::need_type_info]
 * [traits::error_reporting::maybe_report_ambiguity] (3 separate calls to `need_type_info`)
 * [traits::error_reporting::report_fulfillment_error]
 * [traits::error_reporting::report_fulfillment_errors]
 * [check::select_all_obligations_or_error] (and also [check::select_obligations_where_possible]) - here you can access the `Inherited`.

You can pass the `BodyId` through these functions as a parameter. There are actually other call sites to `report_fulfillment_errors`, but these don't seem to have anything to do with function bodies, so you'll actually want to pass an `Option<BodyId>`, pass `None` from these callsites, and don't look for anything in these cases (currently, we pass `BodyId`s that actually refer to non-bodies such as the fn item, so we have [this hack] to not visit anything in that case. That hack could be removed now).

[BodyId]: https://github.com/rust-lang/rust/blob/master/src/librustc/hir/mod.rs#L929
[get the HIR of the function]: https://github.com/rust-lang/rust/blob/master/src/librustc/infer/error_reporting/need_type_info.rs#L108
[FnCtxt]: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L483
[Inherited]: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L186
[constructor]: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L588
[infer::error_reporting::need_type_info::need_type_info]: https://github.com/rust-lang/rust/blob/master/src/librustc/infer/error_reporting/need_type_info.rs#L91
[traits::error_reporting::maybe_report_ambiguity]: https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs#L872
[traits::error_reporting::report_fulfillment_error]: https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs#L151
[traits::error_reporting::report_fulfillment_errors]: https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs#L47
[check::select_all_obligations_or_error]: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L2155
[check::select_obligations_where_possible]: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L2163
[this hack]: https://github.com/rust-lang/rust/blob/master/src/librustc/infer/error_reporting/need_type_info.rs#L106

**Comment by nikomatsakis** [comment]
@arielb1 

> So the problem is that need_type_info is using the body-id of the closure instead of that of the outer function

yeah that's sort of what I expected

> How easy would it be to plumb the body of the function to it, through report_fulfillment_errors etc?

Not very hard, I suppose. However, looking at the closure body-id should also be ok, I would think, since the body actually contains the patterns for the parameters; it might just be a matter of tweaking the visitor?

**Comment by nikomatsakis** [comment]
Still, I do eventually plan to remove the body-id from its current position, so threading the body-id down is probably a good idea.

**Comment by arielb1** [comment]
> Not very hard, I suppose. However, looking at the closure body-id should also be ok, I would think, since the body actually contains the patterns for the parameters; it might just be a matter of tweaking the visitor?

The body is just the expression and does not include the signature. In any case, there could be `Sized` requirements for locals in the base functions etc. that were added from the closure, so it's still probably the best to not rely on which obligation gets picked for error reporting.

**Comment by nikomatsakis** [comment]
@arielb1 yes, ok

**Comment by nikomatsakis** [comment]
@venkatagiri I see that @arielb1 [left some pretty good instructions here](https://github.com/rust-lang/rust/pull/42642#issuecomment-311326420) -- GH wasn't showing me those at first, or I failed to refresh anyway -- but I agree with the plan he laid out for how to fix it.

**Comment by venkatagiri** [comment]
@arielb1 Thanks for the detailed instructions. I have updated the PR with the changes. But, now, there is another [`compile-fail` test](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/issue-23046.rs)  failing. The `type annotations needed` error has moved from the inner closure(with y as arg) to outer closure(with x as arg).

```rust
fn main() {
    let ex = |x| { // Error is thrown for x and below error is missing.
        let_(add(x,x), |y| { //~ ERROR type annotations needed
            let_(add(x, x), |x|x)})};
}
```

**Comment by nikomatsakis** [comment]
@venkatagiri that seems fine; I think you can just update the test and move the `//~ ERROR` annotation around.

**Review by nikomatsakis — APPROVED** [review]
this looks nice :)

**Comment by Mark-Simulacrum** [comment]
@bors retry
 - #38618
