### PR TITLE
fix handling of ZST in win64 ABI on windows-msvc targets

### LINKED ISSUE #132893: ABI mismatch between rustc and clang for passing ZSTs using the win64 ABI.
I tried this code:
https://clang.godbolt.org/z/eT5xEz757
`rustc -O -C debuginfo=0 --target=x86_64-pc-windows-msvc`
```rust
use std::ffi::c_int;

#[repr(C)]
pub struct Z {
    v: [c_int; 0],
}

const _: () = assert!(std::mem::size_of::<Z>() == 0);

#[no_mangle]
extern "win64" fn f(a: Z, b: c_int) -> c_int {
    let _ = a;
    b + 1
}

#[no_mangle]
extern "win64" fn g(a: c_int) -> c_int {
    a
}
```
`clang -O -g0 --target=x86_64-pc-windows-gnu`
```C
struct Z {
    int v[0];
};

_Static_assert(sizeof(struct Z) == 0, "Z should be a ZST");

int __attribute__((ms_abi)) f(struct Z a, int b) {
    return b + 1;
}

int __attribute__((ms_abi)) g(int a) {
    return a;
}
```

I expected to see this happen:
the generated assembly reads from the same register no matter if using clang or rustc.

Instead, this happened: rustc's `f` reads from `rcx` whereas clang's `f` reads from `rdx`.

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```
It also does the exact same thing on:
```
rustc 1.84.0-nightly (b91a3a056 2024-11-07)
binary: rustc
commit-hash: b91a3a05609a46f73d23e0995ae7ebb4a4f429a5
commit-date: 2024-11-07
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

clang version: 19.1.0

<details><summary>Generated Assembly</summary>
<p>

clang's assembly:
```asm
f:
        lea     eax, [rdx + 1]
        ret

g:
        mov     eax, ecx
        ret
```
rustc's assembly
```asm
f:
        lea     eax, [rcx + 1]
        ret

g:
        mov     eax, ecx
        ret
```

</p>
</details>

### PR DESCRIPTION
**Pull request by RalfJung**
The Microsoft calling conventions do not really say anything about ZST since they do not seem to exist in MSVC. However, both GCC and clang allow passing ZST over  `__attribute__((ms_abi))` functions (which matches our `extern "win64" fn`) on `windows-gnu` targets, and therefore implicitly define a de-facto ABI for these types (and lucky enough they seem to define the same ABI). This ABI should be the same for windows-msvc and windows-gnu targets, so we use this as a hint for how to implement this ABI everywhere: we always pass ZST by-ref.

The best alternative would be to just reject compiling functions which cannot exist in MSVC, but that would be a breaking change.

Cc @programmerjake @ChrisDenton 
Fixes https://github.com/rust-lang/rust/issues/132893

### CODE REVIEW

**Comment by mati865** [comment]
I don't remember the details about win64 ABI but following what GCC does is the right approach.

File: compiler/rustc_target/src/callconv/x86_win64.rs [hunk 1]
```diff
@@ -41,10 +42,12 @@ pub(crate) fn compute_abi_info<Ty>(cx: &impl HasTargetSpec, fn_abi: &mut FnAbi<'
     }
     for arg in fn_abi.args.iter_mut() {
         if arg.is_ignore() {
-            // x86_64-pc-windows-gnu doesn't ignore ZSTs.
+            // x86_64-pc-windows-gnu doesn't ignore ZSTs -- except in `extern "win64"`
+            // functions which are supposed to match MSVC.
             if cx.target_spec().os == "windows"
                 && cx.target_spec().env == "gnu"
                 && arg.layout.is_zst()
+                && fn_abi.conv != Conv::X86_64Win64
```
Comment (programmerjake) [inline compiler/rustc_target/src/callconv/x86_win64.rs:50]: this needs to also cover at least fastcall and vectorcall which have basically the same issue: https://clang.godbolt.org/z/MjjfPo3rx

Comment (mati865) [reply compiler/rustc_target/src/callconv/x86_win64.rs:50]: Using fastcall and vectorcall with GCC causes the binaries to segfault, so GCC might be wrong here...

Comment (programmerjake) [reply compiler/rustc_target/src/callconv/x86_win64.rs:50]: hmm, at least gcc matches clang for the short functions i tested above...

File: compiler/rustc_abi/src/extern_abi/mod.rs [hunk 2]
```diff
@@ -192,6 +192,10 @@ pub fn is_enabled(
     s
 }
 
+/// Returns whether the ABI is stable to use.
+///
+/// Note that there is a separate check determining whether the ABI is even supported
+/// on the current target; see `fn is_abi_supported` in `rustc_target::spec`.
```
Comment (SparrowLii) [inline compiler/rustc_abi/src/extern_abi/mod.rs:198]: This comment doesn't related to the change?

**Review by SparrowLii — COMMENTED** [review]
This fix makes sense!

File: tests/codegen/abi-win64-zst.rs [hunk 3]
```diff
@@ -0,0 +1,33 @@
+//@ revisions: linux
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:1]: I think the test I have checks very directly and accurately what we care about. I don't see the point in duplicating that by also copying the example from https://github.com/rust-lang/rust/issues/132893.

File: compiler/rustc_abi/src/extern_abi/mod.rs (hunk 2 above)
Comment (RalfJung) [inline compiler/rustc_abi/src/extern_abi/mod.rs:198]: Yeah this comment is unrelated, it just did not seem worth its own PR.

File: compiler/rustc_target/src/callconv/x86_win64.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs:50]: Do we have anything matching `__attribute__((sysv_abi))`?

If the binaries segfault then maybe it's not so clear what fastcall and vectorcall should do?

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs]: Strangely, the test fails for fastcall on windows-gnu (i.e., we do pass the ZST argument there). I don't yet understand why.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs]: Ah, we currently have explicit logic in `adjust_abi` which says that on x86-64, "fastcall" should be like "C". This is obviously in contradiction with saying that "fastcall" should ignore ZST while "C" should pass them by-pointer.

I'm not a Windows expert so I don't know what is correct here.

File: tests/codegen/abi-win64-zst.rs [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+// CHECK: define x86_64_sysvcc void @pass_zst_sysv64()
+#[no_mangle]
+extern "sysv64" fn pass_zst_sysv64(_: ()) {}
+
+// CHECK: define x86_vectorcallcc void @pass_zst_vectorcall()
+#[no_mangle]
+extern "vectorcall" fn pass_zst_vectorcall(_: ()) {}
+
+// windows-gnu: define x86_fastcallcc void @pass_zst_fastcall()
+// windows-msvc: define x86_fastcallcc void @pass_zst_fastcall()
```
Comment (RalfJung) [inline tests/codegen/abi-win64-zst.rs:37]: Previously we didn't add the `x86_fastcallcc` here since we mapped this to the "C" calling convention. Is it a problem for LLVM to have `x86_fastcallcc` set on an x86-64 build?

File: tests/codegen/abi-win64-zst.rs [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+//@[windows-msvc] needs-llvm-components: x86
+
+#![feature(no_core, lang_items, rustc_attrs, abi_vectorcall)]
+#![no_core]
+#![crate_type = "lib"]
+
+#[lang = "sized"]
+trait Sized {}
+
+// Make sure the argument is always ignored when explicitly requesting "win64" or "sysv64" ABI.
```
Comment (programmerjake) [inline tests/codegen/abi-win64-zst.rs:22]: clang has the pointer to ZST argument for win64, fastcall, and vectorcall, but not for sysv64

File: tests/codegen/abi-win64-zst.rs (hunk 4 above)
Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs]: I managed to avoid changing the LLVM-level calling convention here.

File: compiler/rustc_target/src/callconv/x86_win64.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs]: > this needs to also cover at least fastcall and vectorcall which have basically the same issue: https://clang.godbolt.org/z/75fo4cbhn

Odd, so vectorcall was correct before this PR already? Not quite sure how that is happening.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs]: Anyway the latest version should handle vectorcall and fastcall, hopefully.

File: tests/codegen/abi-win64-zst.rs (hunk 5 above)
Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:22]: Wait, I thought the point of https://github.com/rust-lang/rust/issues/132893 was that ZST arguments get ignored for win64?

Can you translate "rustc's f reads from rcx whereas clang's f reads from rdx" into something understandable that does not involve register names?

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:22]: The test passes as-is on windows-msvc. So if "win64" on windows-gnu is wrong, then it must be the case that we should be *ignoring* ZST everywhere. Now you say ZST are *not* ignored by clang. Something does not make sense here.

Comment (programmerjake) [reply tests/codegen/abi-win64-zst.rs:22]: yeah, I'm saying both the test and rustc ABI lowering code are wrong aka. don't match clang.

> Can you translate "rustc's f reads from rcx whereas clang's f reads from rdx" into something understandable that does not involve register names?

that was mostly so I could show we generate wrong assembly, it's much easier to instead match the llvm-ir that is produced:
https://clang.godbolt.org/z/en55T7Tnj

Comment (programmerjake) [reply tests/codegen/abi-win64-zst.rs:22]: > The test passes as-is on windows-msvc. So if "win64" on windows-gnu is wrong

it's the handling on rustc's msvc target that's wrong. (gnu may also be wrong).

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:22]: > it's the handling on rustc's msvc target that's wrong. 

Oh, damn, I mixed everything up then.

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:22]: That is very strange though... so MSVC `extern "C"` and MSVC `extern "win64"` should not be the same?!?

Comment (programmerjake) [reply tests/codegen/abi-win64-zst.rs]: if you're referencing https://clang.godbolt.org/z/en55T7Tnj from above, it uses gnu as the clang target because I can't figure out how to get a ZST for the msvc target. so, gnu `extern "C"` and `extern "win64"` should be the same in this aspect...I expect msvc `extern "C"` to also match `extern "win64"` in this aspect, but can't test that on clang's side due to a lack of ZSTs.

according to [the GCC docs](https://gcc.gnu.org/onlinedocs/gcc/x86-Function-Attributes.html#index-ms_005fabi-function-attribute_002c-x86):
> On 32-bit and 64-bit x86 targets, you can use an ABI attribute to indicate which calling convention should be used for a function. The ms_abi attribute tells the compiler to use the Microsoft ABI, while the sysv_abi attribute tells the compiler to use the System V ELF ABI, which is used on GNU/Linux and other systems. The default is to use the Microsoft ABI when targeting Windows. On all other systems, the default is the System V ELF ABI.

Comment (ChrisDenton) [reply tests/codegen/abi-win64-zst.rs]: > I can't figure out how to get a ZST for the msvc target

Zero sized structs are not allowed by the C standard but GCC extends C to allow them whereas MSVC extends C to make them 1 byte. I think we have an issue about that somewhere.

Comment (ChrisDenton) [reply tests/codegen/abi-win64-zst.rs]: Hm, that doesn't seem right to me. I'm pretty sure `struct Z {}` should be 1 byte. And `struct Z { ty v[] }` should have the same layout as `struct Z { ty v[1] }`.

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs]: > if you're referencing https://clang.godbolt.org/z/en55T7Tnj from above,

No, I am talking about Rust targets.
The status quo is that `extern "C"` on windows-msvc skips ZST, but on windows-gnu it does not. I don't know where that comes from, but your bugreport is only about `extern "win64"` so I assume `extern "C"` is correct. If `extern "win64"` is meant to be the same cross-target then it should match either windows-gnu-C or windows-msvc-C. It seems you are saying that it should match windows-gnu-C, which seems rather surprising to me -- but that is what this PR does now.

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs]: The latest version of this PR always passes ZST by-ref, except for windows-msvc `extern "C"` functions. This makes no sense at all to me.

Should we just always use by-ref passing x86_win64? Does anyone know why we skip ZST on windows-msvc `extern "C"`?

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs]: I was able to track this back to https://github.com/rust-lang/rust/commit/e177207b3685de49301518e56add65494d828b51, which landed in https://github.com/rust-lang/rust/pull/32080 which is a huge PR and I can't tell if this is new logic or carried over from earlier. The PR description indicates that this PR is where we started skipping ZST arguments, and then an exception was added to *not* do that on 64bit-windows-gnu. Since then the ABI adjustment logic has been refactored many times and now it looks like windows-msvc is the exception, not windows-gnu... so it seems to me like we could just consistently do this for all windows targets.

File: compiler/rustc_target/src/callconv/x86_win64.rs (hunk 1 above)
Comment (mati865) [reply compiler/rustc_target/src/callconv/x86_win64.rs]: > perhaps, however I think it's at least worth matching clang where they do work.

Sure, just pointed out this is a mess with GCC.
A couple years ago I noticed some fastcall tests disabled on windows-gnu because they were failing when objects were built with GCC but worked fine when built with Clang. So yeah, while GCC de facto defines the standard, it's broken in many ways.

File: tests/codegen/abi-win64-zst.rs (hunk 5 above)
Comment (mati865) [reply tests/codegen/abi-win64-zst.rs]: When it comes to `windows-gnu*`, matching whatever Clang does when targeting `windows-gnu` is the best approach. Dunno about msvc.

File: compiler/rustc_abi/src/extern_abi/mod.rs (hunk 2 above)
Comment (SparrowLii) [reply compiler/rustc_abi/src/extern_abi/mod.rs:198]: That's OK

File: tests/codegen/abi-win64-zst.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (SparrowLii) [reply tests/codegen/abi-win64-zst.rs:3]: All right

**Review by programmerjake — APPROVED** [review]
lgtm assuming this matches clang. I'm just reviewing the test cases since i'm not that familiar with the compiler's internals.

**Comment by ChrisDenton** [comment]
Ok so to sum up because I was confused:

- this only affects MSVC
- this changes function argument passing:
  - previously ZSTs were simply ignored
  - now they're passed by pointer indirection
- passing ZSTs is not possible with MSVC so we're using the clang behaviour

This seems like it should be fine. It's the sort of situation where I'd love if we could do a crater run just in case but that's not an option. However, considering it's a portability hazard, I would doubt people are relying on the old behaviour. I've been wrong before though.

**Comment by RalfJung** [comment]
> lgtm assuming this matches clang

I hope it matches clang but I am relying on what others tell me about this.

File: tests/codegen/abi-win64-zst.rs [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+#![crate_type = "lib"]
+
+#[lang = "sized"]
+trait Sized {}
+
+// Make sure the argument is always passed when explicitly requesting a Windows ABI.
+
+// CHECK: define win64cc void @pass_zst_win64(ptr {{.*}})
+#[no_mangle]
+extern "win64" fn pass_zst_win64(_: ()) {}
```
Comment (programmerjake) [inline tests/codegen/abi-win64-zst.rs:26]: it just occurred to me, can you add some tests for returning ZSTs other than `()`? those may also need to be changed to match clang...
https://clang.godbolt.org/z/hKv74ThnE

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:26]: Oh, those are also returned by-ptr then? Wow what an odd ABI.

It seems a bit strange to special-case `()` for return types and not for argument types, though... also, it can't be just `()`. A `repr(transparent)` newtype around `()` is guaranteed to be ABI-compatible. In fact, we are saying

"Any two types with size 0 and alignment 1 are ABI-compatible."

So... I think we have a contradiction? It's not possible to satisfy all these constraints together. Windows never ceases to amaze, and this time it's not even Microsoft's fault...

Comment (RalfJung) [reply tests/codegen/abi-win64-zst.rs:26]: Opened https://github.com/rust-lang/unsafe-code-guidelines/issues/552 for this.
Maybe we can make this PR just about arguments? The issue around return types is pre-existing, and orthogonal to the issue around non-"C" ABIs.

Comment (programmerjake) [reply tests/codegen/abi-win64-zst.rs:26]: > Maybe we can make this PR just about arguments?

considering https://github.com/rust-lang/unsafe-code-guidelines/issues/552, I think just having this PR be about arguments is good enough for now, return types can be fixed later once UCG makes a decision.

File: compiler/rustc_target/src/callconv/mod.rs [hunk 7]
```diff
@@ -666,8 +663,10 @@ impl<'a, Ty> FnAbi<'a, Ty> {
                 x86::compute_abi_info(cx, self, opts);
             }
             "x86_64" => match abi {
-                spec::abi::Abi::SysV64 { .. } => x86_64::compute_abi_info(cx, self),
-                spec::abi::Abi::Win64 { .. } => x86_win64::compute_abi_info(cx, self),
+                ExternAbi::SysV64 { .. } => x86_64::compute_abi_info(cx, self),
+                ExternAbi::Win64 { .. } | ExternAbi::Vectorcall { .. } => {
```
Comment (RalfJung) [inline compiler/rustc_target/src/callconv/mod.rs:667]: This is the one actual change in this file: we treat `Vectorcall` as `x86_win64` even on non-windows targets.

**Comment by RalfJung** [comment]
Okay this should be ready then.

**Review by SparrowLii — APPROVED** [review]
LGTM. You can r=me if @programmerjake has no concerns

File: compiler/rustc_target/src/callconv/x86_win64.rs [hunk 8]
```diff
@@ -40,16 +40,18 @@ pub(crate) fn compute_abi_info<Ty>(cx: &impl HasTargetSpec, fn_abi: &mut FnAbi<'
...
+            // We try to match clang and gcc (which allow ZST is their windows-gnu targets), so we
+            // pass ZST via pointer indirection.
+            arg.make_indirect_from_ignore();
             continue;
         }
         fixup(arg);
     }
+    // FIXME: We should likely also do something about ZST return types, similar to above.
+    // However, that's non-trivial due to `()`.
+    // See <https://github.com/rust-lang/unsafe-code-guidelines/issues/552>.
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86_win64.rs:56]: No, it's just that we usually pass `cx` to these adjustment functions so it doesn't seem worth removing it now as there's a good chance we'll want to add it back later. The comment sits at the place where the code handling the return type would sit.

[the remark this answers is not in the document]
Comment (SparrowLii) [reply compiler/rustc_target/src/callconv/x86_win64.rs:56]: That's OK

**Comment by briansmith** [comment]
> Ok so to sum up because I was confused:
> 
> * this only affects MSVC
> * this changes function argument passing:
>   
>   * previously ZSTs were simply ignored
>   * now they're passed by pointer indirection
> * passing ZSTs is not possible with MSVC so we're using the clang behaviour
> 
> This seems like it should be fine. It's the sort of situation where I'd love if we could do a crater run just in case but that's not an option. However, considering it's a portability hazard, I would doubt people are relying on the old behaviour. I've been wrong before though.

Wow, this is really unfortunate that this shipped in a stable release already. It would have been much better for us to be able to guarantee that passing a ZSTs to any function by value results in the ZST argument being dropped, so that we can have ZST arguments as safety precondition witnesses for `extern "C"` functions. This is a major language design issue that should have had an RFC and discussoin.

In the issue, there is this example:
```
#[repr(C)]
pub struct Z {
    v: [c_int; 0],
}

const _: () = assert!(std::mem::size_of::<Z>() == 0);

#[unsafe(no_mangle)]
extern "win64" fn f(a: Z, b: c_int) -> c_int {
    let _ = a;
    b + 1
}

#[unsafe(no_mangle)]
extern "win64" fn g(a: c_int) -> c_int {
    a
}
```

It is still being decided whether this is even a ZST, because it is `#[repr(C)]`. My view is that it isn't a ZST and so no ZSTs are involved, and the `const _: () = assert!(std::mem::size_of::<Z>() == 0);` should fail at compile time.

Whereas, without the `#[repr(c)]`, `Z` is required to be a ZST. In this case, we should be able to pass a `Z` to an `extern "win64"` (in general any extern function) without it affecting the codegen. I understand this isn't agreed to yet, but this is the future we should be aiming for. But this seems to generate code that will be incompatible with such a resolution:

```
pub struct Z {
    v: [c_int; 0],
}

const _: () = assert!(std::mem::size_of::<Z>() == 0);

#[unsafe(no_mangle)]
extern "win64" fn f(a: Z, b: c_int) -> c_int {
    let _ = a;
    b + 1
}

#[unsafe(no_mangle)]
extern "win64" fn g(a: c_int) -> c_int {
    a
}
```

**Comment by RalfJung** [comment]
> Wow, this is really unfortunate that this shipped in a stable release already. It would have been much better for us to be able to guarantee that passing a ZSTs to any function by value results in the ZST argument being dropped, so that we can have ZST arguments as safety precondition witnesses for extern "C" functions. This is a major language design issue that should have had an RFC and discussoin.

The status quo is that we do not guarantee skipping of ZST arguments for any ABI on any target. So if there's an RFC required here, it would be an RFC saying "ZST do not matter for ABI-compatibility". The fact that for some ABIs we do skip ZST is an unstable implementation detail.

> My view is that it isn't a ZST

What's your definition of ZST? The usual definition is that `size_of` returns 0, and by that definition this is evidently a ZST.

Or do you mean it *should not* be a ZST since we should adjust the layout algorithm to give in non-zero size?
