### PR TITLE
Nest the `impl Trait` existential item inside the return type

### LINKED ISSUE #54045: Regression in #[allow(deprecated)] for `impl Trait` return type
The following code compiles on stable but fails to compile on beta and nightly with the warning "use of deprecated item `Deprecated`":

```rust
#![deny(warnings)]

#[deprecated]
trait Deprecated {}

#[deprecated]
struct DeprecatedTy;

#[allow(deprecated)]
impl Deprecated for DeprecatedTy {}

#[allow(deprecated)]
fn foo() -> impl Deprecated { DeprecatedTy }

fn main() {
    foo();
}
```

Error:
```
error: use of deprecated item 'Deprecated'
  --> src/main.rs:13:18
   |
13 | fn foo() -> impl Deprecated { DeprecatedTy }
   |                  ^^^^^^^^^^
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: #[deny(deprecated)] implied by #[deny(warnings)]

error: aborting due to previous error
```

Possibly related to @oli-obk 's refactoring of `impl Trait`?

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #54045

r? @cramertj

### CODE REVIEW

**Comment by cramertj** [comment]
Nice!

@bors r+

File: src/librustc/hir/mod.rs [hunk 1]
```diff
@@ -1723,6 +1723,12 @@ pub enum TyKind {
     ///
     /// Type parameters may be stored in each `PathSegment`.
     Path(QPath),
+    /// A type definition itself. This is currently only used for the `existential type`
+    /// item that `impl Trait` in return position desugars to.
+    ///
+    /// The generic arg list are the lifetimes (and in the future possibly parameters) that are
+    /// actually bound on the `impl Trait`.
+    Def(ItemId, HirVec<GenericArg>),
```
Comment (eddyb) [inline src/librustc/hir/mod.rs]: I want something like this in general, maybe `{...}` block syntax for types?
Then `-> impl Trait` would be `-> { existential type X: Trait; X }`.
cc @Centril @nikomatsakis

Comment (Centril) [reply src/librustc/hir/mod.rs]: In other words this would be legal?
```rust
type Foo = { u8 };
```
Not sure why it is useful tho...

Comment (oli-obk) [reply src/librustc/hir/mod.rs]: isn't that essentially generic modules? (but unnamed)

Comment (eddyb) [reply src/librustc/hir/mod.rs]: @oli-obk I guess only if you can depend on parameters in scope.

@Centril for the same reason we have it for expressions :P.

Comment (oli-obk) [reply src/librustc/hir/mod.rs]: > I guess only if you can depend on parameters in scope.

which impl trait always does

Comment (Centril) [reply src/librustc/hir/mod.rs]: @eddyb in exprs it exists for some sort of encapsulation purposes... I suppose you could do some sort of encapsulation of type aliases... but we should tread carefully here, there might be ambiguity in store.

PS: we should move this conversation elsewhere into a fresh issue / internals instead of comments on a merged PR (totally not discoverable...).

Comment (cramertj) [reply src/librustc/hir/mod.rs]: @Centril 
>  I suppose you could do some sort of encapsulation of type aliases

Module-based encapsulation is how `existential type X: Trait;` works today.

Comment (Centril) [reply src/librustc/hir/mod.rs]: @cramertj I meant something like this:

```rust
type Foo = {
    type ComplexType = Bar<Baz<u8>>;
    Vec<ComplexType>
};
```
