### PR TITLE
Move a const-prop-lint specific hack from mir interpret to const-prop-lint and make it fallible

### LINKED ISSUE #109743: regression: ICE failing to normalize
https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/jwiegley.motoko_parse/log.txt

```
[INFO] [stdout] error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:195:90: Failed to normalize fn() -> <impl combine::Parser<combine::easy::Stream<&str>, Output = std::string::String> as combine::Parser<combine::easy::Stream<&str>>>::PartialState {<<impl combine::Parser<combine::easy::Stream<&str>, Output = std::string::String> as combine::Parser<combine::easy::Stream<&str>>>::PartialState as std::default::Default>::default}, maybe try to call `try_normalize_erasing_regions` instead
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #109743

This hack didn't need to live in the mir interpreter. For const-prop-lint it is entirely correct to avoid doing any const prop if normalization fails at this stage. Most likely we couldn't const propagate anything anyway, and if revealing was needed (so opaque types were involved), we wouldn't want to be too smart and leak the hidden type anyway.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
ty, r=me

File: compiler/rustc_mir_transform/src/const_prop_lint.rs [hunk 1]
```diff
@@ -284,7 +284,15 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
         }
 
-        self.use_ecx(source_info, |this| this.ecx.eval_mir_constant(&c.literal, Some(c.span), None))
+        // Normalization needed b/c const prop lint runs in
+        // `mir_drops_elaborated_and_const_checked`, which happens before
+        // optimized MIR. Only after optimizing the MIR can we guarantee
+        // that the `RevealAll` pass has happened and that the body's consts
+        // are normalized, so any call to resolve before that needs to be
+        // manually normalized.
+        let val = self.tcx.try_normalize_erasing_regions(self.param_env, c.literal).ok()?;
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/const_prop_lint.rs:293]: Does this needs to be added to the equivalent method in the `ConstProp` opt too?

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-04-06/near/347429503)

@rustbot label +beta-accepted

**Comment by RalfJung** [comment]
Strange, why did the bot not ping wg-const-eval here?
(Just saw this because the bot did ping us in the rollup in https://github.com/rust-lang/rust/pull/110413.)

Though you also got the first-time contributor message, so clearly the bot was confused...

**Comment by saethlin** [comment]
Oli is special and (always?) usually gets the first-time contributor message.

**Comment by RalfJung** [comment]
Oh, fascinating. Seems worth a bug report for the bot though? Is there an issue tracking this?

**Comment by saethlin** [comment]
I'm not aware of one but also don't know where one would be reported.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/triagebot, I think.
