### PR TITLE
rustdoc: fix duplicate Re-exports sections

### LINKED ISSUE #150211: Duplicate Re-exports section in generated docs
I noticed when looking at the gfx-rs docs that there's a duplicate Re-exports section; it re-exports several different crates, some with renames, and for some reason some of them get rendered into a second Re-exports section: https://docs.rs/wgpu/latest/wgpu/

# Code

Unfortunately, I haven't been able to reduce it to a minimal standalone reproduction; here is some of the relevant code from https://github.com/gfx-rs/wgpu/blob/56c654b08d57127293ec785c11c64f3f5156f6d8/wgpu/src/lib.rs:

```rust
#[cfg(wgpu_core)]
pub extern crate wgpu_core as wgc;
#[cfg(wgpu_core)]
pub extern crate wgpu_hal as hal;
pub extern crate wgpu_types as wgt;

// ... snip various other module declarations etc ...

/// Re-export of our `naga` dependency.
///
#[cfg(wgpu_core)]
#[cfg_attr(docsrs, doc(cfg(any(wgpu_core, naga))))]
// We re-export wgpu-core's re-export of naga, as we may not have direct access to it.
pub use ::wgc::naga;
/// Re-export of our `naga` dependency.
///
#[cfg(all(not(wgpu_core), naga))]
#[cfg_attr(docsrs, doc(cfg(any(wgpu_core, naga))))]
// If that's not available, we re-export our own.
pub use naga;

/// Re-export of our `raw-window-handle` dependency.
///
pub use raw_window_handle as rwh;
```

# Reproduction Steps

Unfortunately no minimal repro, but you can reproduce by running `cargo +nightly doc` in the wgpu repo.

# Expected Outcome

I expect that there would only be one "Re-exports" section in the docs.

# Actual Output

Image

# Version

rustdoc 1.94.0-nightly (f794a0873 2025-12-17)

# Additional Details

### PR DESCRIPTION
**Pull request by heathdutton**
Fixes rust-lang/rust#150211

When a module contains both `pub extern crate` and `pub use` items, they were being rendered under two separate "Re-exports" section headers instead of one.

This fix tracks the current section and only renders a new header when the section actually changes, consolidating items that belong to the same section under a single header.

### CODE REVIEW

File: tests/rustdoc/extern/duplicate-reexports-section-150211.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//@ aux-build:pub-extern-crate.rs
+
+// Regression test for issue #150211.
+// When a module has both `pub extern crate` and `pub use` items,
+// they should both appear under a single "Re-exports" section,
+// not two separate sections.
+// https://github.com/rust-lang/rust/issues/150211
```
Comment (reddevilmidzy) [inline tests/rustdoc/extern/duplicate-reexports-section-150211.rs]:
```suggestion
// Regression test for issue <https://github.com/rust-lang/rust/issues/150211>.
// When a module has both `pub extern crate` and `pub use` items,
// they should both appear under a single "Re-exports" section,
// not two separate sections.
```

I don't think there's a need to duplicate issue numbers.

**Review by notriddle — APPROVED** [review]
