### PR TITLE
rustc_typeck: improve diagnostics for -> _ fn return type

### LINKED ISSUE #56132: Permit `-> _` return types for improved diagnostics
Consider (the invalid Rust code containing) a function that returns a value, but has no return type:
```rust
fn foo() {
    0u8
}

fn main() {
    let _: u8 = foo();
}
```
Currently, the compiler produces these errors:
```
error[E0308]: mismatched types
 --> src/main.rs:2:5
  |
1 | fn foo() {
  |          - help: try adding a return type: `-> u8`
2 |     0u8
  |     ^^^ expected (), found u8
  |
  = note: expected type `()`
             found type `u8`

error[E0308]: mismatched types
 --> src/main.rs:6:17
  |
6 |     let _: u8 = foo();
  |                 ^^^^^ expected u8, found ()
  |
  = note: expected type `u8`
             found type `()`

error: aborting due to 2 previous errors
```
In theory, the only problem is the missing return type, which, if provided, would cause the code to compile successfully.

The compiler knows what the return type should be here, and could potentially interpret the rest of the program as if the correct return type were given.

This issue proposes giving special treatment in the compiler for diagnostics only (note that this is *not* a language change) to the syntax `-> _` for return types. This would report a normal error for a missing return type (no extra code would compile after this change), but would otherwise treat the function as having the missing return type. A machine-applicable suggestion would be provided to replace `_` with the correct return type.

For example:
```rust
fn foo() -> _ {
    0u8
}

fn main() {
    let _: u8 = foo();
}
```
```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/main.rs:1:13
  |
1 | fn foo() -> _ {
  |             ^ not allowed in type signatures
  |             - help: replace `_` with the correct return type: `u8`
```

### PR DESCRIPTION
**Pull request by lundibundi**
This should implement IIUC the mentioned issue.

~~I'm not sure if there is a better way than `get_infer_ret_ty` to get/check the return type without code duplication.~~

~~Also, is this unwrap be okay `ty::Binder::bind(*tables.liberated_fn_sigs().get(hir_id).unwrap())`?~~

r? @eddyb 
Closes: https://github.com/rust-lang/rust/issues/56132

### CODE REVIEW

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -1682,28 +1682,65 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+    None
+}
+
 fn fn_sig(tcx: TyCtxt<'_>, def_id: DefId) -> ty::PolyFnSig<'_> {
     use rustc::hir::*;
     use rustc::hir::Node::*;
 
     let hir_id = tcx.hir().as_local_hir_id(def_id).unwrap();
 
-    let icx = ItemCtxt::new(tcx, def_id);
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: I don't see any need for moving this in.

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -1682,28 +1682,65 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+                diag.span_label(ty.span, "not allowed in type signatures");
+                if let Some(ret_ty) = tables.node_type_opt(body_id.hir_id) {
+                    diag.span_suggestion(
+                        ty.span,
+                        "replace `_` with the correct return type",
+                        format!("{}", ret_ty),
+                        Applicability::MaybeIncorrect,
+                    );
+                }
+                diag.emit();
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: cc @estebank is this use of diagnostics correct?

File: src/librustc_typeck/collect.rs [hunk 3]
```diff
@@ -1682,28 +1682,65 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+                    ty.span,
+                    "the type placeholder `_` is not allowed within types on item signatures",
+                    DiagnosticId::Error("E0121".into()),
+                );
+                diag.span_label(ty.span, "not allowed in type signatures");
+                if let Some(ret_ty) = tables.node_type_opt(body_id.hir_id) {
+                    diag.span_suggestion(
+                        ty.span,
+                        "replace `_` with the correct return type",
+                        format!("{}", ret_ty),
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: You can use `ret_ty.to_string()`.

File: src/test/ui/error-codes/E0121.stderr [hunk 4]
```diff
@@ -2,7 +2,10 @@ error[E0121]: the type placeholder `_` is not allowed within types on item signa
   --> $DIR/E0121.rs:1:13
    |
 LL | fn foo() -> _ { 5 }
-   |             ^ not allowed in type signatures
+   |             ^
+   |             |
+   |             not allowed in type signatures
+   |             help: replace `_` with the correct return type: `i32`
 
 error[E0121]: the type placeholder `_` is not allowed within types on item signatures
```
Comment (eddyb) [inline src/test/ui/error-codes/E0121.stderr]: Heh, you could also implement it for `const`/`static` with type `_`.

**Review by eddyb — CHANGES_REQUESTED** [review]
This looks great! I only had minor nits.

File: src/librustc_typeck/collect.rs [hunk 5]
```diff
@@ -1682,28 +1682,65 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+                        Applicability::MaybeIncorrect,
+                    );
+                }
+                diag.emit();
+                ty::Binder::bind(*tables.liberated_fn_sigs().get(hir_id).unwrap())
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: Hmm, you could also get the return type from here, instead of from the body. Not sure which is better, cc @matthewjasper @nikomatsakis

File: src/test/ui/error-codes/E0121.stderr (hunk 4 above)
Comment (Centril) [reply src/test/ui/error-codes/E0121.stderr]: We could also add parser recovery for when no type is provided syntactically, for example: `const FOO = 42;`. I think more people would attempt that

File: src/librustc_typeck/collect.rs (hunk 1 above)
Comment (lundibundi) [reply src/librustc_typeck/collect.rs]: Yeah, initially merged the two branches into one and therefore moved the value in, but ended up splitting them anyways, therefore, no need for this change.

File: src/librustc_typeck/collect.rs (hunk 5 above)
Comment (lundibundi) [reply src/librustc_typeck/collect.rs]: I think it would be at least more 'correct' since we are suggesting the return type of this function and not the 'body' and since we already have it might as well use it.

File: src/test/ui/error-codes/E0121.stderr (hunk 4 above)
Comment (lundibundi) [reply src/test/ui/error-codes/E0121.stderr]: Help for `const FOO = 42;` looks nice, that's how I usually forget about it in `const`'s, though I'm not sure what'd be the correct parser recovery, replacing the type with `Infer` and then failing here with proper help?

Comment (Centril) [reply src/test/ui/error-codes/E0121.stderr]: Yes, basically delegate to the AST representation of `const $name: _ = $expr;` and make sure to error in the parser.

File: src/librustc_typeck/collect.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/collect.rs]: It'd be nice if we could have `ty_infer` and this branch call the same code that would generate `E0121` to have a single point where the error is created. Just making a function with the following should be enough:

```
            fn bad_placeholder_type(&self, tcx: &TyCtxt<'_>) -> DiagnosticBuilder<'_> {
                let mut diag = tcx.sess.struct_span_err_with_code(
                    ty.span,
                    "the type placeholder `_` is not allowed within types on item signatures",
                    DiagnosticId::Error("E0121".into()),
                );
                diag.span_label(ty.span, "not allowed in type signatures");
                diag
            }
```

Then this fn can be called from both places.

Finally, I believe that this is missing a call to `resolve_type_vars_with_obligations`, in case the fn body's resolved type is something like `Option<T>`. I would like to see a test like:

```
fn foo() -> _ {
    let x = Some(42);
    x
}

fn main() {
    let _: Option<usize> = foo();
    let _: f64 = foo();
    let _: Option<i32> = foo();
}
```

Beyond that, I love this PR ❤️

File: src/librustc_typeck/collect.rs [hunk 6]
```diff
@@ -1692,18 +1701,51 @@ fn fn_sig(tcx: TyCtxt<'_>, def_id: DefId) -> ty::PolyFnSig<'_> {
...
-        }) => AstConv::ty_of_fn(&icx, sig.header.unsafety, sig.header.abi, &sig.decl),
-
-        Item(hir::Item {
+        })
+        | Item(hir::Item {
             node: ItemKind::Fn(decl, header, _, _),
             ..
-        }) => AstConv::ty_of_fn(&icx, header.unsafety, header.abi, decl),
+        }) => {
+            get_infer_ret_ty(&decl.output).and_then(|ty| {
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: I would pattern-match on `get_infer_ret_ty` and then handle the two cases separately, just so it's a bit clearer where the signatures flows from.

File: src/librustc_typeck/collect.rs [hunk 7]
```diff
@@ -1692,18 +1701,51 @@ fn fn_sig(tcx: TyCtxt<'_>, def_id: DefId) -> ty::PolyFnSig<'_> {
...
+                tcx.typeck_tables_of(def_id)
+                    .liberated_fn_sigs()
+                    .get(hir_id)
+                    .and_then(|fn_sig| Some((ty, *fn_sig)))
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: I think you can just do `.liberated_fn_sigs()[hir_id]` - it should be impossible for it to be missing (@nikomatsakis would know more - but if tests pass, it should be fine).

File: src/test/ui/error-codes/E0121.stderr (hunk 4 above)
Comment (lundibundi) [reply src/test/ui/error-codes/E0121.stderr]: @Centril But would we have the correct type to suggest in the parser? (I assume you implied the type of `self.parse_expr()` on the right side of const declaration)

Comment (Centril) [reply src/test/ui/error-codes/E0121.stderr]: The correct type in the parser would be `Infer`.

Comment (lundibundi) [reply src/test/ui/error-codes/E0121.stderr]: But then the suggestion for `const FOO = 42` would be the same as for `const FOO: _ = 42` - to *replace* the `_` even though the user hasn't written it, could we perhaps denote some sort of type-absence to handle that propely?

**Comment by lundibundi** [comment]
Merged fixups and rebased on master as there were quite many fixups! and GitHub displayed the commits in the wrong order anyway.

File: src/librustc_typeck/collect.rs (hunk 6 above)
Comment (lundibundi) [reply src/librustc_typeck/collect.rs]: Yep, changed.

File: src/test/ui/error-codes/E0121.stderr (hunk 4 above)
Comment (eddyb) [reply src/test/ui/error-codes/E0121.stderr]: We can skip this for now, tbh.

Comment (Centril) [reply src/test/ui/error-codes/E0121.stderr]: Yeah, let's follow up later.

@lundibundi We should take care not to suggest replacing `_` with something since the user did not write that. Instead we should indicate that the type is missing and that we think the type is so and so.

**Review by estebank — APPROVED** [review]

**Review by eddyb — APPROVED** [review]
