### PR TITLE
rustdoc: Strip imports of items which are `#[doc(hidden)]`

### LINKED ISSUE #106379: Rustdoc JSON Produces dangling ID's when `pub use`ing `#[doc(hidden)]` items.
```rust
#![feature(no_core)]
#![no_core]

mod repeat_n {
    #[doc(hidden)]
    pub struct RepeatN {}
}

pub use repeat_n::RepeatN;
```

Errors with

```
---- [rustdoc-json] src/test/rustdoc-json/reexport/pub_use_doc_hidden.rs stdout ----

error: jsondoclint failed!
status: exit status: 1
command: "/home/nixon/dev/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/jsondoclint" "/home/nixon/dev/rust/rust/build/x86_64-unknown-linux-gnu/test/rustdoc-json/reexport/pub_use_doc_hidden/pub_use_doc_hidden.json"
stdout: none
--- stderr -------------------------------
0:2:1571 not in index or paths, but refered to at '$.index["0:3"].inner.id'
Error: Errors validating json /home/nixon/dev/rust/rust/build/x86_64-unknown-linux-gnu/test/rustdoc-json/reexport/pub_use_doc_hidden/pub_use_doc_hidden.json
------------------------------------------
```

and produced

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 23,
  "includes_private": false,
  "index": {
    "0:0:1572": {
      "crate_id": 0,
      "docs": null,
      "id": "0:0:1572",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:3"]},
      "kind": "module",
      "links": {},
      "name": "pub_use_doc_hidden"
    },
    "0:3": {
      "crate_id": 0,
      "docs": null,
      "id": "0:3",
      "inner": {"glob": false, "id": "0:2:1571", "name": "RepeatN", "source": "repeat_n::RepeatN"},
      "kind": "import",
      "links": {},
      "name": null
    }
  },
  "paths": {"0:0:1572": {"crate_id": 0, "kind": "module", "path": ["pub_use_doc_hidden"]}},
  "root": "0:0:1572"
}
```

HTML gets this right and doesn't output anything:

image

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Closes #106379

### CODE REVIEW

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -2494,6 +2494,17 @@ impl Import {
     pub(crate) fn new_glob(source: ImportSource, should_be_displayed: bool) -> Self {
         Self { kind: ImportKind::Glob, source, should_be_displayed }
     }
+
+    pub(crate) fn imported_item_is_doc_hidden(&self, tcx: TyCtxt<'_>) -> bool {
+        match self.source.did {
+            Some(did) => tcx
+                .get_attrs(did, sym::doc)
```
Comment (aDotInTheVoid) [inline src/librustdoc/clean/types.rs:2501]: For some reason that I'm not sure of, using `.lists` here instead of open coding it causes panics. https://github.com/rust-lang/rust/pull/106538#issuecomment-1373996487

I think it's to do with the difference between `tcx.item_attrs` and `tcx.get_attrs`, as [this was the diff that fixed it.](https://github.com/rust-lang/rust/compare/98130d1b3af4e800bd6b1c5d5e09b525878c53f5..ff46d116c1fec1a1ceb988e0e31263c00a5d521b)
