### PR TITLE
Take into account negative impls in "trait item not found" suggestions

### LINKED ISSUE #79683: Take advantage of negative_impls in error messages
(Spotted in https://users.rust-lang.org/t/the-trait-clone-is-not-implemented-for-mut-t/51989?u=scottmcm)

I tried this code <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6c22f56bb7cfec1e8e04a79fc078cdd6>:
```rust
#![feature(negative_impls)]

trait Foo {
    fn foo(&self) {}
}

impl Foo for u64 {}
impl !Foo for i32 {}

fn main() {
    let x = 4_i32;
    x.foo();    
}

```

Which of course fails to compile.  And it gives the following:

```rust
error[E0599]: no method named `foo` found for type `i32` in the current scope
  --> src/main.rs:12:7
   |
12 |     x.foo();    
   |       ^^^ method not found in `i32`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `Foo` defines an item `foo`, perhaps you need to implement it
  --> src/main.rs:3:1
   |
3  | trait Foo {
   | ^^^^^^^^^
```

It would be nice to take advantage of the negative implementation to _not_ say "perhaps you need to implement it" and in fact to say that it explicitly is not implemented.  Other good similar cases would be things like `Foo::foo(&x)`.

(This is a follow-up issue to https://github.com/rust-lang/rust/issues/79458, as the bug part was fixed, so this is the lower-priority improvement part.)

cc https://github.com/rust-lang/rust/issues/68318

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
This removes the suggestion to implement a trait for a type when that type already has a negative implementation for the trait, and replaces it with a note to point out that the trait is explicitely unimplemented, as suggested by @scottmcm.

Helps with #79683.

r? @scottmcm do you want to review this?

### CODE REVIEW

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -1167,22 +1168,49 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                         }
                         _ => {}
                     }
                 }
             }
 
-            if !suggested {
+            let (potential_candidates, explicitly_negative) = if param_type.is_some() {
+                // Negative bounds are not supported
+                (candidates, Vec::new())
```
Comment (LeSeulArtichaut) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1180]: This is actually sort of a shortcut, consider the following code:

```rust
#![feature(negative_impls)]

trait Foo {
    fn foo(&self);
}

trait Bar {}

impl<T: Foo> !Bar for T {}

fn foo<T: Bar>(x: T) {
    x.foo()
}
```

Which gives the following error:

```
error[E0599]: no method named `foo` found for type parameter `T` in the current scope
  --> main.rs:12:7
   |
12 |     x.foo()
   |       ^^^ method not found in `T`
   |
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `foo`, perhaps you need to restrict type parameter `T` with it:
   |
11 | fn foo<T: Foo + Bar>(x: T) {
   |        ^^^^^^^^

error: aborting due to previous error
```

So I think this could be improved but I think it's reasonable to do it in a follow-up PR since this PR does not change the current diagnostic.

**Comment by LeSeulArtichaut** [comment]
My PR also doesn't work in:

```rust
#![feature(negative_impls)]

trait Bar {
    fn bar(&self);
}

impl<T: Copy> !Bar for T {}

fn foo(x: ()) {
    x.bar()
}

fn main() {}
```

```
error[E0599]: no method named `bar` found for unit type `()` in the current scope
  --> main.rs:10:7
   |
10 |     x.bar()
   |       ^^^ method not found in `()`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `Bar` defines an item `bar`, perhaps you need to implement it
  --> test.rs:3:1
   |
3  | trait Bar {
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 2]
```diff
@@ -1198,14 +1230,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                         ));
                     }
-                    err.note(&msg[..]);
+                    err.note(&msg);
+                }
+            }
+            if !explicitly_negative.is_empty() {
+                if let [trait_info] = &explicitly_negative[..] {
+                    let msg = format!(
+                        "`{}` defines an item `{}`, but is explicitely unimplemented",
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1246]:
```suggestion
                        "the trait `{}` defines an item `{}`, but is explicitely unimplemented",
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 3]
```diff
@@ -1167,22 +1168,53 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            return;
                         }
                         _ => {}
                     }
                 }
             }
 
-            if !suggested {
+            let (potential_candidates, explicitly_negative) = if param_type.is_some() {
+                // Negative bounds are not supported
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1179]: i don't feel like this comment as very helpful on its own, can you elaborate a bit here?

**Review by lcnr — APPROVED** [review]
lgtm

one additional small nit would be to use
```rust
match explicitly_negative/potential_candidates {
    [] => {},
    [trait_info] => ...
    slice => ...
}
```
instead of the current `if not_empty { if let ... { ... } }`

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 3 above)
Comment (LeSeulArtichaut) [reply compiler/rustc_typeck/src/check/method/suggest.rs:1179]: I'll leave a TODO instead

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 4]
```diff
@@ -1167,23 +1168,55 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        potential_candidates.push(candidate);
+                    }
+                }
+                (potential_candidates, explicitly_negative)
+            } else {
+                // We don't know enough about `recv_ty` to make proper suggestions.
+                (candidates, Vec::new())
+            };
+
+            if !potential_candidates.is_empty() {
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1210]: can you move that `if` into the match as well?

imo it's fine to define action outside even if it isn't used in the empty case

Comment (LeSeulArtichaut) [reply compiler/rustc_typeck/src/check/method/suggest.rs]: Done

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 5]
```diff
@@ -1167,45 +1168,96 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                            &format!(
-                                "`{}` defines an item `{}`, perhaps you need to {} it",
-                                self.tcx.def_path_str(trait_info.def_id),
-                                item_name,
-                                action
-                            ),
-                        );
-                        use_note = false
+            let (potential_candidates, explicitly_negative) = if param_type.is_some() {
+                // FIXME Even though negative bounds are not implemented, we could maybe handle
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1179]:
```suggestion
                // FIXME: Even though negative bounds are not implemented, we could maybe handle
```

**Comment by lcnr** [comment]
r=me

@bors delegate+

**Comment by LeSeulArtichaut** [comment]
Thanks for your review @lcnr!
@bors r=lcnr

**Comment by Dylan-DPC** [comment]
failed in [rollup log](https://github.com/rust-lang-ci/rust/runs/1564736172)

@bors r-

**Comment by LeSeulArtichaut** [comment]
@Dylan-DPC How is this PR causing that "could not parse code block as Rust code" error?

**Comment by LeSeulArtichaut** [comment]
I don't know where this try build comes from, but based on this I will take the liberty of accepting this again.
@bors r=lcnr

**Comment by Dylan-DPC** [comment]
I don't know but the error was tough to debug and this looked like t he closest PR :D

**Comment by LeSeulArtichaut** [comment]
I'd guess the failure comes from #79816 which IIUC creates this new lint?

**Comment by Dylan-DPC** [comment]
yeah the test failure now on that PR, confirms it. sorry about the mess :P
