### PR TITLE
File not found for module error

### LINKED ISSUE #39542: "file not found for module" compile error doesn't have an error number
"file not found for module" compile error does not have an [error number/code](https://doc.rust-lang.org/error-index.html), thus it cannot be easily identified/handled by external tools.

My use case is with Vim w0rp/ale plugin which does code checking as you type. It uses rustc to do "as-you-type" error checking and cargo check when a file is saved (see [ale-integration-rust](https://github.com/w0rp/ale/blob/a1458e9c072e1cfc425591b7616a291e99778753/doc/ale.txt#L897)). Since imports cannot be resolved with "as-you-type" checking it would make sense to ignore such errors and only show them if they're detected by cargo. But since "file not found for module" doesn't have an error code I can't ignore it.

Example code `src/main.rs`:
```
mod doesnotexist;

fn main() {
    println!("Hello world");
}

```
When compiling I expect to get an error with an error number, something like `error[E0123]: ...` but no error number is provided:
```
$ rustc src/main.rs
error: file not found for module `doesnotexist`
 --> src/main.rs:1:5
  |
1 | mod doesnotexist;
  |     ^^^^^^^^^^^^
  |
  = help: name the file either doesnotexist.rs or doesnotexist/mod.rs inside the directory "src"
```

```
$ rustc --verbose --version
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-apple-darwin
release: 1.15.0
LLVM version: 3.9
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #39542.

r? @jonathandturner 

Maybe you want to take a look @pnkfelix?

### CODE REVIEW

File: src/libsyntax/diagnostic_list.rs [hunk 1]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
 ```
 "##,
+
+E0583: r##"
+A file wasn't found for a module import.
+
+Erroneous code example:
+
+```compile_fail,E0583
+mod file_that_doesnt_exist; // error: ile not found for module
```
Comment (frewsxcv) [inline src/libsyntax/diagnostic_list.rs]: Typo: "ile not found for module"

File: src/libsyntax/diagnostic_list.rs [hunk 2]
```diff
@@ -224,4 +291,5 @@ register_diagnostics! {
     E0555, // malformed feature attribute, expected #![feature(...)]
     E0556, // malformed feature, expected just one word
     E0557, // feature has been removed
+    E0584, // file for module `..` found at both .. and ..
```
Comment (GuillaumeGomez) [inline src/libsyntax/diagnostic_list.rs]: Don't know how to trigger this one and not enough time to investigate. Someone will do it later on if I don't myself.

File: src/libsyntax/diagnostic_list.rs (hunk 1 above)
Comment (GuillaumeGomez) [inline src/libsyntax/diagnostic_list.rs]: Oups, thanks!

File: src/libsyntax/diagnostic_list.rs [hunk 3]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+
+```
+/// I'm documenting the following struct:
+struct Foo;
+
+/// I'm documenting the following function:
+fn foo() {}
+```
+"##,
+
```
Comment (durka) [inline src/libsyntax/diagnostic_list.rs]: Feature flags will be needed in these examples

**Comment by GuillaumeGomez** [comment]
@durka: I added the corresponding tests already. Take a look at the new files in `compile-fail` directory.

**Comment by durka** [comment]
Yeah but you are missing `#![feature(inclusive_range_syntax)]`.

**Comment by GuillaumeGomez** [comment]
It's not needed as far as I can tell... ? At least when I test, I have no missing feature issue.

**Comment by durka** [comment]
Huh... I guess since this error is generated in the parser it occurs before
the unstable feature check. So it's okay I guess.

**Comment by jonathandturner** [comment]
I'm cool with this change, but you probably want to ping someone on the compiler team to double-check the logic.  I haven't done much with the module system, yet.

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/compiler

File: src/libsyntax/diagnostic_list.rs [hunk 4]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
 pub fn something() {}
 ```
 "##,
+
+E0583: r##"
+A file wasn't found for a module import.
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: Do we want to call `mod foo;` a "module import"?
I've heard it called an "out-of-line module", but never heard "module import" except to refer to a `use` import of a module.

File: src/libsyntax/diagnostic_list.rs [hunk 5]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+
+Erroneous code example:
+
+```compile_fail,E0583
+mod file_that_doesnt_exist; // error: file not found for module
+
+fn main() {}
+```
+
+Please be sure that a file corresponding to the module really exist. So if you
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: nit: ~~really~~ exist**s**. ~~So~~

File: src/libsyntax/diagnostic_list.rs [hunk 6]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+want to import a `file_that_doesnt_exist` module, you need to have a
+`file_that_doesnt_exist.rs` file at the same level.
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: or `file_that_doesnt_exist/mod.rs`

File: src/libsyntax/diagnostic_list.rs [hunk 7]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+"##,
+
+E0585: r##"
+A documentation comment which doesn't comment anything was found.
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: nit: s/which/that/, s/comment/document/

File: src/libsyntax/diagnostic_list.rs [hunk 8]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+Erroneous code example:
+
+```compile_fail,E0585
+fn main() {
+    // The following doc comment will fail:
+    /// This is a useless doc comment!
+}
+```
+
+Documentation comments need to be used on items like functions, types,
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: nit: s/be used on/precede/, s/like/including/

File: src/libsyntax/parse/parser.rs [hunk 9]
```diff
@@ -233,6 +233,57 @@ pub struct ModulePathError {
     pub help_msg: String,
 }
 
+pub enum Errors {
+    FileNotFoundForModule { mod_name: String,
+                            default_path: String,
+                            secondary_path: String,
+                            dir_path: String },
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: block indenting is more idiomatic here

File: src/libsyntax/parse/parser.rs [hunk 10]
```diff
@@ -946,6 +994,10 @@ impl<'a> Parser<'a> {
     pub fn span_fatal(&self, sp: Span, m: &str) -> DiagnosticBuilder<'a> {
         self.sess.span_diagnostic.struct_span_fatal(sp, m)
     }
+    pub fn span_fatal_err(&self, sp: Span, err: Errors) -> DiagnosticBuilder<'a> {
+        let res = err.span_err(sp, self.diagnostic());
+        res
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: no need for local variable `res`. Also, I don't think we need this method.

File: src/libsyntax/parse/parser.rs [hunk 11]
```diff
@@ -5174,20 +5218,14 @@ impl<'a> Parser<'a> {
...
-                                 mod_name,
-                                 default_path_str,
-                                 secondary_path_str),
-                help_msg: "delete or rename one of them to remove the ambiguity".to_owned(),
-            }),
+            (false, false) => Err(Errors::FileNotFoundForModule {
+                mod_name: mod_name.clone(),
+                default_path: default_path_str,
+                secondary_path: secondary_path_str,
+                dir_path: format!("{}", dir_path.display()) }),
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: add a newline before the `}),`

File: src/libsyntax/parse/parser.rs [hunk 12]
```diff
@@ -5174,20 +5218,14 @@ impl<'a> Parser<'a> {
...
+            (true, true) => Err(Errors::DuplicatePaths { mod_name: mod_name.clone(),
+                                                         default_path: default_path_str,
+                                                         secondary_path: secondary_path_str }),
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: block indenting is more idiomatic here.

File: src/libsyntax/parse/parser.rs [hunk 13]
```diff
@@ -5245,15 +5283,15 @@ impl<'a> Parser<'a> {
...
-        match paths.result {
-            Ok(succ) => Ok(succ),
-            Err(err) => Err(self.span_fatal_help(id_sp, &err.err_msg, &err.help_msg)),
+                Err(err)
+            }
+        } else {
+            match paths.result {
+                Ok(succ) => Ok(succ),
+                Err(err) => Err(self.span_fatal_err(id_sp, err)),
+            }
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: we could use `map_err` here instead of `match`.

File: src/test/compile-fail/E0586.rs [hunk 14]
```diff
@@ -0,0 +1,14 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+fn main() {
+    let tmp = vec![0, 1, 2, 3, 4, 4, 3, 3, 2, 1];
+    let x = &tmp[1...]; //~ ERROR E0586
+}
```
Comment (jseyfried) [inline src/test/compile-fail/E0586.rs]: nit: no trailing new newline

File: src/libsyntax/parse/parser.rs [hunk 15]
```diff
@@ -233,6 +233,57 @@ pub struct ModulePathError {
...
 }
 
+pub enum Errors {
+    FileNotFoundForModule { mod_name: String,
+                            default_path: String,
+                            secondary_path: String,
+                            dir_path: String },
+    DuplicatePaths { mod_name: String, default_path: String, secondary_path: String },
+    UselessDocComment,
+    InclusiveRangeWithNoEnd,
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: Do we need this variant? I think it would be simpler to just emit the error directly in the relevant parsing function.

File: src/libsyntax/diagnostic_list.rs (hunk 4 above)
Comment (GuillaumeGomez) [inline src/libsyntax/diagnostic_list.rs]: How would you reword it then?

File: src/libsyntax/parse/parser.rs (hunk 15 above)
Comment (GuillaumeGomez) [inline src/libsyntax/parse/parser.rs]: I try to centralize the errors. Making them easier to spot and modify.

File: src/libsyntax/diagnostic_list.rs (hunk 4 above)
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: I would call it a "module item" or an "out-of-line module".

File: src/libsyntax/parse/parser.rs (hunk 15 above)
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: I think `UselessDocComment` and `InclusiveRangeWithNoEnd` would be more appropriate as methods on the `Parser`, since they don't have anything to do with with the first two variants (except that they are errors during parsing).

Then, the enum could be named `ModulePathError` -- clearer and more precise.

Comment (GuillaumeGomez) [inline src/libsyntax/parse/parser.rs]: The point isn't to group same kind of errors but to centralize them.

File: src/libsyntax/parse/parser.rs (hunk 10 above)
Comment (GuillaumeGomez) [inline src/libsyntax/parse/parser.rs]: It allows to reduce code and improve clarity so I definitely think we should keep it (but maybe not as public?).

File: src/test/compile-fail/E0586.rs (hunk 14 above)
Comment (GuillaumeGomez) [inline src/test/compile-fail/E0586.rs]: Done.

**Comment by GuillaumeGomez** [comment]
@jseyfried: Is it ok for you now? ;)

File: src/libsyntax/diagnostic_list.rs [hunk 16]
```diff
@@ -201,6 +201,73 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+
+```compile_fail,E0583
+mod file_that_doesnt_exist; // error: file not found for module
+
+fn main() {}
+```
+
+Please be sure that a file corresponding to the module exists. If you
+want to import a `file_that_doesnt_exist` module, you need to have a
+`file_that_doesnt_exist/mod.rs` file at the same level.
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: Also, I would say "in the same directory" instead of "at the same level".

File: src/libsyntax/parse/parser.rs [hunk 17]
```diff
@@ -3853,10 +3907,8 @@ impl<'a> Parser<'a> {
                     let unused_attrs = |attrs: &[_], s: &mut Self| {
                         if attrs.len() > 0 {
                             if s.prev_token_kind == PrevTokenKind::DocComment {
-                                s.span_err_help(s.prev_span,
-                                    "found a documentation comment that doesn't document anything",
-                                    "doc comments must come before what they document, maybe a \
-                                    comment was intended with `//`?");
+                                Errors::UselessDocComment.span_err(s.prev_span, s.diagnostic())
+                                                         .emit();
```
Comment (GuillaumeGomez) [inline src/libsyntax/parse/parser.rs]: Absolutely!

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/libsyntax/diagnostic_list.rs [hunk 18]
```diff
@@ -201,6 +201,74 @@ where appropriate is ongoing. Try using an unquoted name instead:
...
+
+```compile_fail,E0583
+mod file_that_doesnt_exist; // error: file not found for module
+
+fn main() {}
+```
+
+Please be sure that a file corresponding to the module exists. If you
+want to use a module named `file_that_doesnt_exist`, you need to have a
+`file_that_doesnt_exist.rs` or a `file_that_doesnt_exist/mod.rs` file in the
```
Comment (jseyfried) [inline src/libsyntax/diagnostic_list.rs]: nit: you need to have ~a~ `file_that_doesnt_exist.rs` or `file_that_doesnt_exist/mod.rs` ~file~ in the same directory.

or: you need to have a file named `file_that_doesnt_exist.rs` or `file_that_doesnt_exist/mod.rs` in the same directory.

File: src/libsyntax/parse/parser.rs [hunk 19]
```diff
@@ -233,6 +233,63 @@ pub struct ModulePathError {
     pub help_msg: String,
 }
 
+pub enum Errors {
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: optional nit: `Error` would be a more idiomatic name

**Review by jseyfried — COMMENTED** [review]
r=me modulo comments

**Comment by GuillaumeGomez** [comment]
Ok, I fixed the two last nits. If you find anything else, don't hesitate to r-!

@bors: r=jseyfried

File: src/libsyntax/parse/parser.rs [hunk 20]
```diff
@@ -233,6 +233,63 @@ pub struct ModulePathError {
...
+    DuplicatePaths {
+        mod_name: String,
+        default_path: String,
+        secondary_path: String,
+    },
+    UselessDocComment,
+    InclusiveRangeWithNoEnd,
+}
+
+impl Errors {
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: `Errors` -> `Error` (won't pass travis)

File: src/libsyntax/parse/parser.rs [hunk 21]
```diff
@@ -233,6 +233,63 @@ pub struct ModulePathError {
...
+    pub fn span_err<'a>(self, sp: Span, handler: &'a errors::Handler) -> DiagnosticBuilder<'a> {
+        match self {
+            Error::FileNotFoundForModule { ref mod_name,
+                                           ref default_path,
+                                           ref secondary_path,
+                                            ref dir_path } => {
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: indent (one extra space)

File: src/libsyntax/parse/parser.rs [hunk 22]
```diff
@@ -233,6 +233,63 @@ pub struct ModulePathError {
...
+                let mut err = struct_span_er!(handler, sp, E0583,
+                                               "file not found for module `{}`", mod_name);
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: indent (one extra space)

File: src/libsyntax/parse/parser.rs [hunk 23]
```diff
@@ -955,6 +1009,9 @@ impl<'a> Parser<'a> {
     pub fn span_fatal(&self, sp: Span, m: &str) -> DiagnosticBuilder<'a> {
         self.sess.span_diagnostic.struct_span_fatal(sp, m)
     }
+    pub fn span_fatal_err(&self, sp: Span, err: Errors) -> DiagnosticBuilder<'a> {
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: Also here (`Errors` -> `Error`), etc.

File: src/libsyntax/parse/parser.rs [hunk 24]
```diff
@@ -233,6 +233,63 @@ pub struct ModulePathError {
...
+}
+
+impl Errors {
+    pub fn span_err<'a>(self, sp: Span, handler: &'a errors::Handler) -> DiagnosticBuilder<'a> {
+        match self {
+            Error::FileNotFoundForModule { ref mod_name,
+                                           ref default_path,
+                                           ref secondary_path,
+                                            ref dir_path } => {
+                let mut err = struct_span_er!(handler, sp, E0583,
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: typo

**Comment by jseyfried** [comment]
@bors r-
I usually wait for Travis to pass before directing bors.

**Comment by GuillaumeGomez** [comment]
@jseyfried: Outch, my string replacement failed badly... Updated.

**Comment by GuillaumeGomez** [comment]
Tests seem ok this time so let's r+ it. Thanks @jseyfried!

@bors: r=jseyfried

File: src/libsyntax/diagnostic_list.rs (hunk 2 above)
Comment (durka) [inline src/libsyntax/diagnostic_list.rs]: This error occurs for `mod foo;` when both `foo.rs` and `foo/mod.rs` exist.

**Comment by alexcrichton** [comment]
@bors: retry

* network failure
