### PR TITLE
Define built-in macros through libcore

### LINKED ISSUE #61687: Imports/reexports of built-in macros are not supported
```rust
use column; // error: cannot import a built-in macro

fn main() {}
```

The reason behind this error is that if you import something with a `DefId`, that `DefId` should be supported by all stages of compilation (metadata emitting specifically), but built-in macros don't have such a `DefId`.

The crate ID in their `DefId` has special value `CrateNum::BuiltinMacros` that is supported only inside rustc_resolve and causes ICEs every time it leaves it.

### LINKED ISSUE #61804: ICE: rustdoc: Tried to get crate index of builtin macros crate
Running `cargo doc` on [rs-sync](https://github.com/remram44/rs-sync) runs into an ICE today ([CI log](https://travis-ci.org/remram44/rs-sync/jobs/545052449)).

* cargo 1.37.0-nightly (545f35425 2019-05-23)
* rustc 1.37.0-nightly (2887008e0 2019-06-12)
* rustdoc 1.37.0-nightly (2887008e0 2019-06-12)
* Linux amd64 using rustup

```
$ RUST_BACKTRACE=full cargo doc
 Documenting cfg-if v0.1.2
 Documenting adler32 v1.0.2
   Compiling kernel32-sys v0.2.2
    Checking memchr v0.1.11
    Checking memchr v2.0.1
    Checking unreachable v1.0.0
 Documenting memchr v2.0.1
    Checking log v0.4.0
 Documenting memchr v0.1.11
 Documenting unreachable v1.0.0
    Checking thread_local v0.3.5
    Checking aho-corasick v0.5.3
    Checking aho-corasick v0.6.4
    Checking log v0.3.9
 Documenting kernel32-sys v0.2.2
    Checking thread-id v2.0.0
    Checking regex v0.2.4
    Checking thread_local v0.2.7
error: internal compiler error: src/librustc/hir/def_id.rs:51: Tried to get crate index of builtin macros crate

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
stack backtrace:
    Checking regex v0.1.80
   0:     0x7fc38dd7f17b - backtrace::backtrace::libunwind::trace::h37e8a367d6921aa8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x7fc38dd7f17b - backtrace::backtrace::trace_unsynchronized::h248427898d35c0c6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x7fc38dd7f17b - std::sys_common::backtrace::_print::he196ebe73104e0d6
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7fc38dd7f17b - std::sys_common::backtrace::print::hea7e6b9f756deddc
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7fc38dd7f17b - std::panicking::default_hook::{{closure}}::hdb08e9c6d066c960
                               at src/libstd/panicking.rs:198
   5:     0x7fc38dd7ee7c - std::panicking::default_hook::h0cb542c8a02e7512
                               at src/libstd/panicking.rs:212
   6:     0x7fc38dd7f8f0 - std::panicking::rust_panic_with_hook::h48a72e8eabfd4099
                               at src/libstd/panicking.rs:475
   7:     0x7fc38e8e94dd - std::panicking::begin_panic::hc6a0004ee4956ade
   8:     0x7fc38e90959f - rustc_errors::Handler::bug::hcf07ca34a6805319
   9:     0x7fc38f9e2933 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h30e49872349e1b56
  10:     0x7fc38f9d48ca - rustc::ty::context::tls::with_opt::{{closure}}::hc208fb6746701e51
  11:     0x7fc38f9d47e5 - rustc::ty::context::tls::with_context_opt::h15cdcb1db35091b0
  12:     0x7fc38f9d4877 - rustc::ty::context::tls::with_opt::h891d00ecedec2006
  13:     0x7fc38f9e2848 - rustc::util::bug::opt_span_bug_fmt::h70b20b7323044267
  14:     0x7fc38f9e27b2 - rustc::util::bug::bug_fmt::had20fba359e6cb41
  15:     0x563306096ab3 - rustc::ty::query::__query_compute::crate_name::h8b43c1f26b00fb9c
  16:     0x5633060bbd09 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::crate_name>::compute::hff5eac7498ce3951
  17:     0x5633060a0352 - rustc::dep_graph::graph::DepGraph::with_task_impl::h5f8fa552d5e4edae
  18:     0x5633060cf681 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h553e4393c1761ee0
  19:     0x563305fd53b9 - rustdoc::clean::inline::record_extern_fqn::hc278d9460d71fbac
  20:     0x563305ff7544 - rustdoc::clean::register_res::he2e76e71c93a2a42
  21:     0x563305e67a3f - <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item::he61b0ea3b3aff64d
  22:     0x563305e6ab3c - <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_crate::heb139cd0d64723fb
  23:     0x563305e64938 - rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links::hd59b413f945905ea
  24:     0x563305f663e9 - rustc::ty::context::tls::enter_global::h67954f21b2bb08db
  25:     0x563305f945f5 - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::h130794a59f0212d7
  26:     0x7fc391436615 - rustc_interface::passes::create_global_ctxt::{{closure}}::h9455f3a1e30caa2a
  27:     0x563305f94dba - rustc_interface::interface::run_compiler_in_existing_thread_pool::h05ad216b805d92e6
  28:     0x5633060b43a5 - rustdoc::core::run_core::h107268107fd770cb
  29:     0x563305f497e9 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h671b84da37a2eeed
  30:     0x5633060839b4 - std::panicking::try::do_call::h2594efe39321f4f4
  31:     0x7fc38dd908ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  32:     0x563305e73b1f - rustdoc::main_options::h8151ccbbcb801724
  33:     0x563306077987 - std::thread::local::LocalKey<T>::with::h2858f3258f098c48
  34:     0x563305f92665 - scoped_tls::ScopedKey<T>::set::h987e033854ca136b
  35:     0x563305f68d62 - syntax::with_globals::h631ab6d18b38e093
  36:     0x563305fb7cb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h08deae4a6f64f6b0
  37:     0x7fc38dd908ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  38:     0x563305e3de69 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfca600189f1ae5f0
  39:     0x7fc38dd62edf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbbe4b50e56f896eb
                               at /rustc/2887008e0ce0824be4e0e9562c22ea397b165c97/src/liballoc/boxed.rs:746
  40:     0x7fc38dd8f5a0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7ab4448ee8ad917c
                               at /rustc/2887008e0ce0824be4e0e9562c22ea397b165c97/src/liballoc/boxed.rs:746
  41:     0x7fc38dd8f5a0 - std::sys_common::thread::start_thread::h0cd07c3bb37a8763
                               at src/libstd/sys_common/thread.rs:13
  42:     0x7fc38dd8f5a0 - std::sys::unix::thread::Thread::new::thread_start::h6a06e7fee86bebc7
                               at src/libstd/sys/unix/thread.rs:79
  43:     0x7fc38d8f76db - start_thread
  44:     0x7fc38d40888f - __clone
  45:                0x0 - <unknown>
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (2887008e0 2019-06-12) running on x86_64-unknown-linux-gnu

error: Could not document `cfg-if`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name cfg_if /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.2/src/lib.rs --cap-lints allow --color always -o /home/remram/Documents/programming/rs-sync/target/doc -L dependency=/home/remram/Documents/programming/rs-sync/target/debug/deps` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### PR DESCRIPTION
**Pull request by petrochenkov**
This PR defines built-in macros through libcore using a scheme similar to lang items (attribute `#[rustc_builtin_macro]`).
All the macro properties (stability, visibility, etc.) are taken from the source code in libcore, with exception of the expander function transforming input tokens/AST into output tokens/AST, which is still provided by the compiler.

The macros are made available to user code through the standard library prelude (`{core,std}::prelude::v1`), so they are still always in scope.
As a result **built-in macros now have stable absolute addresses in the library**, like `core::prelude::v1::line!()`, this is an insta-stable change.

Right now `prelude::v1` is the only publicly available absolute address for these macros, but eventually they can be moved into more appropriate locations with library team approval (e.g. `Clone` derive -> `core::clone::Clone`).

Now when built-in macros have canonical definitions they can be imported or reexported without issues (https://github.com/rust-lang/rust/issues/61687).

Other changes:
- You can now define a derive macro with a name matching one of the built-in derives (https://github.com/rust-lang/rust/issues/52269). This was an artificial restriction that could be worked around with import renaming anyway.

Known regressions:
- Empty library crate with a crate-level `#![test]` attribute no longer compiles without `--test`. Previously it didn't compile *with* `--test` or with the bin crate type.

Fixes https://github.com/rust-lang/rust/issues/61687
Fixes https://github.com/rust-lang/rust/issues/61804
r? @eddyb

### CODE REVIEW

File: src/libcore/macros.rs [hunk 1]
```diff
@@ -821,4 +823,43 @@ mod builtin {
         ($cond:expr,) => ({ /* compiler built-in */ });
         ($cond:expr, $($arg:tt)+) => ({ /* compiler built-in */ });
     }
+
+    macro_rules! doit {
+        ($($name:ident)*) => (
+            $(
+                /// Doc
+                #[rustc_doc_only_macro]
+                #[stable(feature = "rust1", since = "1.0.0")]
```
Comment (Centril) [inline src/libcore/macros.rs]: This could use some comments re. why e.g. asm! is stable...?

Comment (petrochenkov) [reply src/libcore/macros.rs]: Sure, I'll do it later, right now only the infrastructure is up, but the specific data is not filled in yet.

**Review by eddyb — APPROVED** [review]
r=me on the last commit, assuming we *do* want to expose those macros from the top of `core` and `std` (has @rust-lang/libs discussed that yet?)

**Comment by petrochenkov** [comment]
>assuming we do want to expose those macros from the top of `core` and `std`

That needs discussion, yes.
Right now the new macros follow the example of other macros defined in `libcore` and are defined as `#[macro_export] macro_rules! { ... }` which makes them available through `core::my_macro`.

The alternative is to introduce them through `pub macro() { ... }` in this case they could be available from inner modules only (e.g. `core::clone::Clone`, like mentioned in https://github.com/rust-lang/rust/issues/62050#issuecomment-505088071) and will need to be put into the prelude `core::prelude::v1` and injected through `#[prelude_import] use core::prelude::v1::*` rather than through `#[macro_use] extern crate core`.
This may create some pain for libcore itself though (`macro` macros are not available for the whole crate part below their definition, unlike `macro_rules` macros), I haven't tried it yet.
Also see https://github.com/rust-lang/rust/issues/53977 that aims to put all the macros into `prelude::v1` instead of using `#[macro_use]`.

**Comment by petrochenkov** [comment]
With `pub macro` and `prelude::v1` we can just put the new macros into some private module so that they are not available via module-relative paths.

This will decouple *this* PR from the library decisions.

Making the built-in macros available via module-relative paths is kind of the point of the whole enterprise though.

**Comment by QuietMisdreavus** [comment]
Does this PR fix https://github.com/rust-lang/rust/issues/61804? It looks like it will expose a proper macro location in libcore to the resolver, meaning that rustdoc would be able to link to builtin macros from intra-doc links properly.

**Comment by petrochenkov** [comment]
Maybe?
I'll add the test from https://github.com/rust-lang/rust/pull/61916 and check whether it works.

File: src/libcore/macros.rs [hunk 2]
```diff
@@ -644,181 +644,720 @@ macro_rules! uninitialized_array {
...
     #[stable(feature = "rust1", since = "1.0.0")]
-    #[rustc_doc_only_macro]
-    macro_rules! column { () => ({ /* compiler built-in */ }) }
+    #[rustc_builtin_macro] #[rustc_macro_transparency = "semitransparent"]
+    pub macro column { () => ({ /* compiler built-in */ }) }
 
-    /// Expands to the file name from which it was invoked.
+    /// Same as `column`, but less likely to be shadowed.
+    #[unstable(feature = "__rust_unstable_column", issue = "0",
+               reason = "internal implementation detail of the `column` macro")]
```
Comment (est31) [inline src/libcore/macros.rs]: It's not an implementation detail of the column macro, but of the `panic!` macro. `column!()` is builtin itself, as well. See #42938, #43057, #43735.

Comment (est31) [reply src/libcore/macros.rs]: Also, possibly it might not be needed in the future, as pointed out by @matklad: https://github.com/rust-lang/rust/issues/48781#issuecomment-493427139

Comment (petrochenkov) [reply src/libcore/macros.rs]: This PR is exactly the prerequisite for `$crate::column!` working.
Right now it doesn't work because `column` is a built-in macro rather than a standard library macro.

Once this PR lands, built-in macros will be available through stable paths in the standard library, and I'll submit the next PR hygienizing their use in the standard libary (similarly to https://github.com/rust-lang/rust/pull/61629) and removing `__rust_unstable_colum`.

**Comment by petrochenkov** [comment]
Now waiting on https://github.com/rust-lang/rust/pull/62476.

File: src/libcore/macros.rs (hunk 2 above)
Comment (est31) [reply src/libcore/macros.rs]: @petrochenkov you should still change the message though.

Comment (petrochenkov) [reply src/libcore/macros.rs]: Yeah, will do.

**Comment by petrochenkov** [comment]
The PR is updated and is now ready for review.
cc @rust-lang/compiler @rust-lang/libs

File: src/librustc/hir/def_id.rs [hunk 3]
```diff
@@ -13,10 +13,6 @@ newtype_index! {
 
 #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
 pub enum CrateNum {
-    /// Virtual crate for builtin macros
-    // FIXME(jseyfried): this is also used for custom derives until proc-macro crates get
-    // `CrateNum`s.
-    BuiltinMacros,
     /// A special CrateNum that we use for the tcx.rcache when decoding from
     /// the incr. comp. cache.
     ReservedForIncrCompCache,
```
Comment (eddyb) [inline src/librustc/hir/def_id.rs]: @Zoxc @michaelwoerister I really wish we could remove this, btw.

**Comment by petrochenkov** [comment]
I'm going to nominate this for the libs team since their approval is the primary blocker here.

**Comment by alexcrichton** [comment]
The libs team discussed this today and there was consensus that this is a great idea and helps resolve what's already a weird gap in the language (`std::format!` works but `std::format_args!` doesn't). This is a great first step and we can cover further stabilizations as they come up

**Comment by petrochenkov** [comment]
Great!
The PR is rebased.
ping @eddyb

**Comment by Centril** [comment]
Nominating this for the language meeting today as well since well, it's today (=P) and this includes language changes (the ability to import/re-export builtin macros and defining derive macros with names matching the built-in derives) as well though I don't expect anything but agreement.

> You can now define a derive macro with a name matching one of the built-in derives (#52269). This was an artificial restriction that could be worked around with import renaming anyway.

Hmm... This seems like it could cause issues with:

https://github.com/rust-lang/rust/blob/5c26b523686497a46d10104c7295f366099a298c/src/libsyntax/ext/derive.rs#L62-L71

My reading of this code is that:

a) You can define your own `PartialEq` + `Eq` derive macros, bring them into scope, and now you will get `#[structural_match]` on your type. This has soundness implications... I think.

b) Doing the same with `Copy` will add `#[rustc_copy_clone_marker]` to your type as well.

**Comment by eddyb** [comment]
@Centril That check should be changed to somehow use name resolution.

Alternatively, at least for `Copy`, that should be emitted by the `Copy` derive logic itself (is that possible?), and we *might* want to replace `#[structural_match]` with a deeper check in the compiler, that both `PartialEq` and `Eq` impls for a given type are derived (a similar technique could also work for `Copy`?).

cc @pnkfelix @varkor I think the disconnect between `#[structural_match]` and the actual `PartialEq`/`Eq` impls has caused bugs in the past.

**Review by eddyb — APPROVED** [review]
r=me assuming no libs/lang concerns

**Comment by petrochenkov** [comment]
@Centril 
Ugh, that function (`add_derived_markers`) is one of the most horrifying hacks in the whole frontend, for multiple reasons (it's inherited from the original Macros 1.1 implementation), before https://github.com/rust-lang/rust/pull/62476 it did *everything* wrong.
Removing it somehow is one of my primary goals in expansion refactorings.

I won't go into discussing the possible fixes, but the case you mentioned can already be triggered by defining a derive with any name and renaming it into `PartialEq` or `Copy` during importing.

**Comment by petrochenkov** [comment]
@Centril 
>language changes (the ability to import/re-export builtin macros and defining derive macros with names matching the built-in derives)

I'll wait for today's meeting, but I don't think this is a language change.
The first change is a bugfix under the general "uniform path imports" feature, and the second change doesn't allow to do anything new that wasn't already possible with imports.

**Comment by petrochenkov** [comment]
>Alternatively, at least for Copy, that should be emitted by the Copy derive logic itself (is that possible?), and we might want to replace #[structural_match] with a deeper check in the compiler, that both PartialEq and Eq impls for a given type are derived (a similar technique could also work for Copy?).

Ideally, the markers should be applied to the generated impls rather than to the item itself, but I didn't investigate what exactly changes in the later compiler passes it will require.

Fixes in expand are also possible, e.g. introducing a new macro kind "an attribute macro that can be called only using the derive syntax" and moving the marker injection logic from the expansion infra into specific built-in macros.
This is somewhat entangled with expansion order between attributes and derives though, which was defined incorrectly by Macros 1.1, IMO, and needs to be fixed.

**Comment by eddyb** [comment]
> Ideally, the markers should be applied to the generated impls rather than to the item itself, but I didn't investigate what exactly changes in the later compiler passes it will require.

I agree, anything else seems to be a bit of a nightmare. It should always be possible to look up the attributes of the `Copy`/`PartialEq`/`Eq` `impl` for a given type, but it could get somewhat involved.

As @nikomatsakis and @pnkfelix are on PTO, I'd ask one of @varkor @davidtwco @matthewjasper for help with that, at least the parts that involve MIR (e.g. match checking's use of `#[structural_match]`).

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/lang meeting. I believe our conclusion was:

- While this PR permits misusing structural-match, that was already possible, and the PR doesn't make it more likely. It seems ok to land it.
- We should ideally solve structural-match by trying to resolve the underlying question so that we just don't need the attribute anymore.
- In particular, @Centril suggested trying to 'not trust' the structural-match attribute by checking what the partial-eq/eq impls *do*, but that sounds very hard and troublesome.

**Comment by eddyb** [comment]
Do note that there is an attribute on derived impls, so we could check that in the meanwhile.

**Comment by petrochenkov** [comment]
So, I realized today that it's very easy to remove `#[structural_match]` from the expansion *infrastructure* and make it a specific macro's headache instead.
Built-in macros are still using the legacy syntactic plugin model, so they have write access to all the global context (like `Session`) and we can keep the `structural_match_items: HashSet<NodeId>` table in that global context.

The situation with `copy_clone_marker` is trickier.
If we want to implement it fully precisely, then we cannot expand any of the built-in derives until we definitely know whether one of the other derives on the same item is built-in `Copy`.
In cases when there's no `Copy`, this means we must resolve all derives on an item before expanding any of them.
This kind of logic can be added into the existing resolution indeterminacy infrastructure without many complications, I think, but it increases the chances of resolution being stuck, at least in theory.

**Comment by vlad20012** [comment]
Any ETA when these `#[cfg(bootstrap)]` will be removed from the std?

**Comment by petrochenkov** [comment]
@vlad20012 
After the upcoming release, somewhere around [August 15th](https://forge.rust-lang.org).

**Comment by vlad20012** [comment]
So these `cfg`s will remain in the upcoming release?

**Comment by est31** [comment]
@vlad20012 yes. This is a normal process btw, see the `cfg(bootstrap)` invocations that each compiler version update PR removes.
