### PR TITLE
error-msg: impl better suggestion for `E0532`

### LINKED ISSUE #106862: E0532 could perhaps chose better binding names?
Given the following code: 

```rust
use Foo::FooB;

enum Foo {
    FooB { x: i32, y: i32 }
}

fn main() {
    let f = FooB { x: 3, y: 4 };
    match f {
        FooB(a, b) => println!("{} {}", a, b),
        //~^ ERROR expected tuple struct or tuple variant, found variant `FooB`
    }
}
```

The current output is:

```
error[E0532]: expected tuple struct or tuple variant, found variant `FooB`
  --> src/main.rs:10:9
   |
4  |     FooB { x: i32, y: i32 }
   |     ----------------------- `FooB` defined here
...
10 |         FooB(a, b) => println!("{} {}", a, b),
   |         ^^^^^^^^^^ help: use struct pattern syntax instead: `FooB { x, y }`
```

Currently, this will fail to apply because we name the bindings x and y, but end up using a and b. I wonder if we can make the suggestion more clever to actually work around this so that this can be automatically applied.

### PR DESCRIPTION
**Pull request by Ezrashaw**
Fixes #106862

No test as there is already a test which is nearly identical to the example in the linked issue.

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1298,21 +1298,38 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                    let (tail, descr, applicability, old_fields) = match source {
+                        PathSource::Pat => ("", "pattern", Applicability::MachineApplicable, None),
+                        PathSource::TupleStruct(_, args) => (
+                            "",
+                            "pattern",
+                            Applicability::MachineApplicable,
+                            Some(
+                                args.iter()
+                                    .map(|a| {
+                                        self.r.tcx.sess.source_map().span_to_snippet(*a).unwrap()
```
Comment (WaffleLapkin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1310]: Adding a `span_to_snippet` to diagnostic logic doesn't sound like a good idea. Can you instead either
1. Leave field spans in place and add code around them (I think I'd prefer this), or
2. Save field names before hand

?

Comment (Ezrashaw) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1310]: Sorry, maybe I'm missing something but I thought the primary use of `SourceMap::span_to_snippet` was for diagnostic purposes.

I don't think we have access to the old fields, and even if we did that would require stringifying them which `span_to_snippet` already does.

**Comment by Ezrashaw** [comment]
@WaffleLapkin I've added a test with all your cases. One of the suggestions was poor (`Foo { x: x }`), it's been updated.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1310]: Yes, `SourceMap::span_to_snippet` is intended for diagnostics, but we generally try to not use it, leaving it as a last resort when you can't implement the diagnostic otherwise :)

> EDIT: A mere 50 lines above is another span_to_snippet used for error messages.

Yes, but as I said, we'd like to remove most of them, not adding them is still encouraged.

----

You can use [`multipart_suggestion`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic/struct.Diagnostic.html#method.multipart_suggestion) to add field aliases without replacing the whole pattern. I.e. instead of

```
- S(a)
+ S { a: x }
```
you would do
```
S(a)
 - -

S { a: x }
 +++ +++++
```

Spans for adding aliases are just `arg_span.shrink_to_hi()`, `{}` are a bit harder, but something like `path_span.between(first_arg_span)` and `last_arg_span.between(the_whole_thing_span.shrink_to_hi())` should probably work.

Although maybe this will need a slight refactor of the surrounding code, if it's too hard leave a `// FIXME` instead and I'll fix it after this PR is merged.

**Comment by WaffleLapkin** [comment]
Hm, I thought about another test case: what about the case, when the pattern and the struct have different number of fields? i.e. `struct S { x: u32, y: u32 }`/`S(a)`; `struct S { field: u32 }`/`S(x, y)`; `struct S {}`/`S(a)`; and `struct S { field: u32 }`/`S()`.

If the struct has more fields than the pattern, we could either suggest `..` or `excess_field0: _, excess_field1: _` (not sure what's better).

Also, is this code run on expressions too? If so, we should test it too (although it seems like expressions go in `PathSource::Expr`?... it's unclear from the docs and hard to guess while reviewing on gh)

**Comment by Ezrashaw** [comment]
Implemented "when the tuple is missing fields". Also rebased and updated tests.

I think that removing the `span_to_snippet` will be difficult because you have to compare the old and new field; you can't just suggest around the fields.

File: tests/ui/pattern/issue-106862.stderr [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+   |         ^^^^^^^^^^^^^ help: use struct pattern syntax instead: `FooB { x: a, y: _ }`
+
+error[E0532]: expected tuple struct or tuple variant, found variant `FooB`
+  --> $DIR/issue-106862.rs:36:9
+   |
+LL |     FooB { x: i32, y: i32 }
+   |     ----------------------- `FooB` defined here
+...
+LL |         FooB() => (),
+   |         ^^^^^^ help: use struct pattern syntax instead: `FooB {  }`
```
Comment (WaffleLapkin) [inline tests/ui/pattern/issue-106862.stderr:44]: > when the tuple is missing fields (eg `struct S { x: u32, y: u32 }`/`S(a)`) is to ignore extra struct fields, obviously this is bad. I'd suggest just putting them in as `S { field1: x, field2, field3 }`. People might want to use those fields and IMHO we shouldn't preemptively ignore them; worst case is a unused warning.

That sounds reasonable to me, can you implement it? Also, when you do, please add a `// run-rustfix` to the header of the file, so we know that after suggestions are applied the code compiles.

**Comment by WaffleLapkin** [comment]
> I think that removing the `span_to_snippet` will be difficult because you have to compare the old and new field; you can't just suggest around the fields.

Alright, I see. I won't block this PR on removing `span_to_snippet` then.

**Comment by Ezrashaw** [comment]
@WaffleLapkin Whoops, thought I had already done that but however.

@rustbot ready

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1289,25 +1289,43 @@ impl<'a: 'ast, 'ast, 'tcx> LateResolutionVisitor<'a, '_, 'ast, 'tcx> {
...
+                                    })
+                                    .collect::<Vec<String>>(),
+                            ),
```
Comment (WaffleLapkin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1305]: Last thing: can you remove the unwrap, falling back to the bad suggestion in case sources are not available?

Something like `args.iter().map(|&a| self.r.tcx.sess.source_map().span_to_snipper(a).ok()).collect::<Option<Vec<String>>>()` should work.

**Comment by Ezrashaw** [comment]
@WaffleLapkin Done. Thanks for all the feedback.

**Review by WaffleLapkin — APPROVED** [review]
