### PR TITLE
Fix variable name in E0502 double borrow error

### LINKED ISSUE #51268: NLL: Wrong variable name in E0502 (double borrow) error message
On nightly, the following code...

```rust
#![feature(nll)]

struct Bar;

impl Bar {
    fn bar(&mut self, _: impl Fn()) { }
}

struct Foo { thing: Bar, number: usize }

impl Foo {
    fn foo(&mut self) {
        self.thing.bar(|| {
            &self.number;
        });
    }
}
```

...yields this error message:

```none
error[E0502]: cannot borrow `self.thing` as mutable because it is also borrowed as immutable
  --> src/lib.rs:13:9
   |
13 |            self.thing.bar(|| {
   |            ^              -- immutable borrow occurs here
   |   _________|
   |  |_________|
   | ||
14 | ||             &self.number;
   | ||              ---- previous borrow occurs due to use of `self.thing` in closure
15 | ||         });
   | ||          ^
   | ||__________|
   | |___________mutable borrow occurs here
   |             borrow later used here
```

Since the closure actually borrows `self.number`, not `self.thing`, I feel like the error should say `self` instead of `self.thing`. It would also be nice if it weren't an error in the first place, but that's a separate issue (let me know if I should report it separately).

---

## Meta

`rustc --version --verbose`:
```none
rustc 1.28.0-nightly (1ffb32147 2018-05-31)
binary: rustc
commit-hash: 1ffb321477d85fb3c95a0be2a0cd89c04dff0d8d
commit-date: 2018-05-31
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

### PR DESCRIPTION
**Pull request by spastorino**
Closes #51268

r? @nikomatsakis

### CODE REVIEW

File: src/test/ui/nll/issue-51268.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+struct Foo {
+    thing: Bar,
+    number: usize,
+}
+
+impl Foo {
+    fn foo(&mut self) {
+        self.thing.bar(|| {
+        //~^ ERROR cannot borrow `self.thing` as mutable because it is also borrowed as immutable [E0502]
```
Comment (oli-obk) [inline src/test/ui/nll/issue-51268.rs]: You are still checking for `self.thing`, which is probably also why the tests are failing ;)

**Comment by nikomatsakis** [comment]
This is the relevent part of the log:

```
[00:43:35] ---- [ui] ui/nll/issue-51268.rs stdout ----
[00:43:35] diff of stderr:
[00:43:35] 
[00:43:35] 1	error[E0502]: cannot borrow `self.thing` as mutable because it is also borrowed as immutable
[00:43:35] -	  --> $DIR/issue-51268.rs:26:9
[00:43:35] +	  --> $DIR/issue-51268.rs:28:9
[00:43:35] 3	   |
[00:43:35] 4	LL |            self.thing.bar(|| {
[00:43:35] 5	   |            ^              -- immutable borrow occurs here
[00:43:35] 
[00:43:35] 
```

(cc @TimNN -- jfyi the bot failed to extract this particular error)

File: src/test/ui/nll/issue-51268.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/test/ui/nll/issue-51268.rs]: I think that part is correct -- the main error still walks about `self.thing`.
