### PR TITLE
Compiletest: Fix compare-output-by-lines directive

### LINKED ISSUE #148235: Parallel rustc + `compare-output-by-lines` + edition 2015 loses diagnostic file path / line number in stderr snapshot
https://github.com/rust-lang/rust/pull/147498#discussion_r2469278814

### PR DESCRIPTION
**Pull request by Ozzy1423**
Fixes: https://github.com/rust-lang/rust/issues/148235

This was checking that the blessed stderr was a subset of the stderr. Additionally, when re-blessing it would re-bless the subset that matched. So, when an extra line or comment was added and the line numbers changed, it would bless it without the line numbers.

I hope this is the intended behaviour now, my only concern is if the parallel frontend has cases where it sometimes emits less diagnostics than other times and so re-blessing the minimum was the intended behaviour? There used to be a flag called "compare-output-by-lines-subset" for this which used this logic.

r? @jieyouxu

### CODE REVIEW

File: src/tools/compiletest/src/runtest.rs [hunk 1]
```diff
@@ -2738,9 +2739,20 @@ impl<'test> TestCx<'test> {
...
             } else {
+                // this prints/blesses the subset, not the actual
                 tmp = (expected_lines.join("\n"), used.join("\n"));
                 (&tmp.0, &tmp.1)
             }
+        } else if compare_output_by_lines {
+            let mut actual_lines: Vec<&str> = actual.lines().collect();
+            let mut expected_lines: Vec<&str> = expected.lines().collect();
+            actual_lines.sort_unstable();
+            expected_lines.sort_unstable();
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest.rs:2750]: Question: wait, why are we using `sort_unstable()` here? Could this give non-deterministic sorting orders between different runs?

File: tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr [hunk 2]
```diff
@@ -41,7 +40,13 @@ help: consider `await`ing on the `Future`
 LL |     match tuple().await {
    |                  ++++++
 
+error[E0425]: cannot find function, tuple struct or tuple variant `Unstable2` in this scope
```
Comment (jieyouxu) [inline tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:43]: Question: do we know why these two diagnostics swapped orders?

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (teor2345) [reply src/tools/compiletest/src/runtest.rs:2750]: `sort_unstable` is deterministic, if elements that compare equal can be substituted for each other:
https://doc.rust-lang.org/std/primitive.slice.html#method.sort_unstable

Ignoring equal element order makes the sort faster.

`str` is ordered by byte value, so the only way to distinguish equal strings is by their memory address:
https://doc.rust-lang.org/std/primitive.str.html#impl-Ord-for-str

Which is totally irrelevant to this code, because the `Vec::partial_eq` below calls `str::partial_eq` on each of the strings.

File: tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr (hunk 2 above)
Comment (teor2345) [reply tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:43]: I don't see anything in the code changes that would specifically cause this. But there's also nothing (in those code changes) that would stop lines swapping around.

A different swap also happens in `ty-variance-issue-124423.stderr` above.

**Review by teor2345 — COMMENTED** [review]
I think the sorts are ok, but the 4 swapped diagnostics are weird.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153797/3102493c71626b5912d11d06c393b013569beb52..772e4560ed4a1c58c36288407df0eac6686e02ea)*

File: tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr (hunk 2 above)
Comment (jieyouxu) [reply tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:43]: Yeah. I wonder if we rerun/rebless this, that it will change again

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (jieyouxu) [reply src/tools/compiletest/src/runtest.rs:2750]: Of course, right. Cheers.

File: tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr (hunk 2 above)
Comment (Ozzy1423) [reply tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:43]: Yes, this is a known issue with -Zthreads, it causes diagnostics to be swapped around.
That does mean, when we re-bless in the future they could jump around again, that is the whole point of the compare-output-by-lines

**Comment by teor2345** [comment]
> Note they will only swap order if you re-bless when there is an actual change. If the diagnostics only change order (due to -Zthreads), they will match by lines and won't be re-blessed.

It seems like a stable process would be:
- bless without parallel, to make any changes in serial order
- bless with parallel, to make any parallel-only changes (which might swap around)

Can we add that to the tooling (or comments, or documentation)?

File: tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr [hunk 3]
```diff
@@ -41,7 +40,13 @@ help: consider `await`ing on the `Future`
...
+   |
+LL |     Unstable2(())
+   |     ^^^^^^^^^ not found in this scope
+
 error: aborting due to 5 previous errors
 
 Some errors have detailed explanations: E0308, E0425, E0670.
-For more information about an error, try `rustc --explain E0308`.
\ No newline at end of file
+For more information about an error, try `rustc --explain E0308`.
```
Comment (teor2345) [inline tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:52]: These lines look identical, any idea why there's a diff?

Comment (teor2345) [reply tests/ui/parallel-rustc/unexpected-type-issue-120601.stderr:52]: Aha, it looks like GitHub renders "no newline at end of file" on the PR page, but not on the diff page.

Feel free to resolve this.
