### PR TITLE
Fix span for closure return type when annotated.

### LINKED ISSUE #58053: NLL: closure return-type highlighting does not handle annotation right
Code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b31d74a1a2becbd4872eda330b840f0f)):

```rust
#![feature(nll)]

fn main() {
    let f = |x: &i32| -> &i32 { x };
    let i = &3;
    let j = f(i);
}
```

yields:

```
error: lifetime may not live long enough
 --> src/main.rs:4:33
  |
4 |     let f = |x: &i32| -> &i32 { x };
  |                 -           -   ^ returning this value requires that `'1` must outlive `'2`
  |                 |           |
  |                 |           return type of closure is &'2 i32
  |                 let's call the lifetime of this reference `'1`
```

but I would have expected it to use the span:

```
error: lifetime may not live long enough
 --> src/main.rs:4:33
  |
4 |     let f = |x: &i32| -> &i32 { x };
  |                 -        -      ^ returning this value requires that `'1` must outlive `'2`
  |                 |        |
  |                 |        return type of closure is &'2 i32
  |                 let's call the lifetime of this reference `'1`
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #58053.

This PR adjusts the span used to label closure return types so that
if the user specifies the return type, i.e. `|_| -> X {}` instead of
`|_| {}`, we correctly highlight all of it and not just the last
character.

r? @pnkfelix

### CODE REVIEW

File: src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs [hunk 1]
```diff
@@ -681,10 +681,13 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
             hir::Node::Expr(hir::Expr {
-                node: hir::ExprKind::Closure(_, _, _, span, gen_move),
+                node: hir::ExprKind::Closure(_, return_ty, _, span, gen_move),
                 ..
             }) => (
-                tcx.sess.source_map().end_point(*span),
+                match return_ty.output {
+                    hir::FunctionRetTy::DefaultReturn(_) => tcx.sess.source_map().end_point(*span),
+                    hir::FunctionRetTy::Return(_) => return_ty.output.span(),
+                },
```
Comment (estebank) [inline src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs]: Isn't `return_ty.output.span()` always correct?

File: src/test/ui/nll/issue-58053.rs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+#![allow(warnings)]
+#![feature(nll)]
+
+fn main() {
+    let f = |x: &i32| -> &i32 { x };
+    //~^ ERROR lifetime may not live long enough
+    let i = &3;
+    let j = f(i);
```
Comment (estebank) [inline src/test/ui/nll/issue-58053.rs]: Add a test for the no-return-type case as well.

File: src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/region_infer/error_reporting/region_name.rs]: It isn't, I tried that first. This would point to the character after the last `|` in the closure instead. For example:

```diff
2         --> $DIR/issue-53040.rs:5:8
3          |
4       LL |     || &mut v;
-          |      - ^^^^^^ returns a reference to a captured variable which escapes the closure body
-          |      |
-          |      inferred to be a `FnMut` closure
+          |        -^^^^^
+          |        |
+          |        returns a reference to a captured variable which escapes the closure body
+          |        inferred to be a `FnMut` closure
8          |
9          = note: `FnMut` closures only have access to their captured variables while they are executing...
10         = note: ...therefore, they cannot allow references to captured variables to escape
```

File: src/test/ui/nll/issue-58053.rs (hunk 2 above)
Comment (davidtwco) [reply src/test/ui/nll/issue-58053.rs]: Added.
