### PR TITLE
Display associated types of implementors

### LINKED ISSUE #86631: rustdoc: trait implementors don't have assoc. types shown
Live: https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html#impl-IntoIterator-30

Trait implementors don't have their assoc. types shown (stable -> nightly regression).

nightly:

image

stable:

image

```
rustdoc 1.55.0-nightly (7c3872e6b 2021-06-24)
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #86631.

Contrary to before, it doesn't display methods. I also had to "resurrect" the `auto-hide-trait-implementations` setting. :3

Only question at this point: should I move the `render_impl` boolean arguments into one struct? We're starting to have quite a lot of them...

cc @cynecx
r? @camelid

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed tidy...

**Comment by camelid** [comment]
> Only question at this point: should I move the `render_impl` boolean arguments into one struct? We're starting to have quite a lot of them...

Yes, please do. It'll make this change much easier to review :)

But maybe do it in a separate commit from adding the new flags?

**Comment by GuillaumeGomez** [comment]
> But maybe do it in a separate commit from adding the new flags?

Will do.

**Comment by GuillaumeGomez** [comment]
Cleaned up the arguments.

**Comment by camelid** [comment]
Unfortunately, I don't think I'm knowledgeable enough about this part of the code base to be able to review this PR. @Manishearth could you review this instead? r? @Manishearth

**Comment by camelid** [comment]
Also, should this be marked as beta-nominated?

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -453,6 +453,7 @@ fn settings(root_path: &str, suffix: &str, themes: &[StylePath]) -> Result<Strin
         ("auto-hide-method-docs", "Auto-hide item methods' documentation", false).into(),
         ("auto-hide-trait-implementations", "Auto-hide trait implementation documentation", false)
             .into(),
+        ("auto-collapse-implementors", "Auto-hide implementors of a trait", true).into(),
```
Comment (Manishearth) [inline src/librustdoc/html/render/mod.rs:456]: I don't think we should reintroduce this

File: src/librustdoc/html/render/mod.rs [hunk 2]
```diff
@@ -1248,23 +1252,26 @@ fn notable_traits_decl(decl: &clean::FnDecl, cx: &Context<'_>) -> String {
     out.into_inner()
 }
 
+#[derive(Clone, Copy, Debug)]
+struct ImplRenderingParameters {
+    show_def_docs: bool,
+    is_on_foreign_type: bool,
+    show_default_items: bool,
+    /// It'll exclude methods if set to `false`.
```
Comment (Manishearth) [inline src/librustdoc/html/render/mod.rs:1260]: "Whether or not to show methods and associated constants"

File: src/test/rustdoc/trait-impl-items-links-and-anchors.rs [hunk 3]
```diff
@@ -55,3 +57,10 @@ impl MyTrait for MyStruct {
 }
 
 pub struct MyStruct;
+
+// We check that associated items with default values aren't generated.
```
Comment (Manishearth) [inline src/test/rustdoc/trait-impl-items-links-and-anchors.rs:61]: ... in the implementors list

**Review by Manishearth — CHANGES_REQUESTED** [review]

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:456]: It's available for all other impl blocks, so should be weird to not be there, no?

File: src/librustdoc/html/render/mod.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1260]: The associated constants are included in any case. I'll reword it though, your wording is better.

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (Manishearth) [reply src/librustdoc/html/render/mod.rs:456]: No? The other settings are different. We removed this because we stopped showing methods, which is what made the impl section so big. The impl section is no longer that big.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:456]: Depends on how many associated items you have?

Comment (Manishearth) [reply src/librustdoc/html/render/mod.rs:456]: It's super unlikely to have that many. I don't want to add a setting to deal with an extremely rare edge case, and I don't think a regression fix is the place to do so _anyway_. Overall we've learned that these settings are confusing and we've been moving towards handing things sensibly in ways that don't need settings (e.g. the way we choose to collapse associated items _when there are tons of them_ so that the settings for those can be collapsed)

**Comment by camelid** [comment]
@rust-lang/rustdoc This fixes a stable-to-beta regression and is thus beta-nominated. Should we accept it for backport to beta (backport should happen soon)?

**Comment by Manishearth** [comment]
Yes, we should IMO

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:456]: Fine by me.

**Comment by Manishearth** [comment]
@bors p=1

since I think the backport window isn't large

**Comment by camelid** [comment]
Marking as beta-accepted; I asked and Joshua has no objections.
