### PR TITLE
Prevent UB in child process after calling libc::fork

### LINKED ISSUE #85261: Allocation after libc::fork on Android
I am trying to fix it so that Rust's stdlib prevents unwinding, or allocating, in the child, after a fork on Unix (including in `Command`).  That is #81858.  (Allocation after fork of a multithreaded program is UB in several libcs.)

I added a new test case, <strike>https://github.com/rust-lang/rust/blob/8220f2f2127b9aec972163ded97be7d8cff6b9a8/src/test/ui/process/process-panic-after-fork.rs</strike> https://github.com/rust-lang/rust/blob/6369637a192bbd0a2fbf8084345ddb7c099aa460/src/test/ui/process/process-panic-after-fork.rs  Unfortunately this test fails, but just on Android: https://github.com/rust-lang/rust/pull/81858#issuecomment-834717407

I have few good theories as to why.  I wrote some speculations: https://github.com/rust-lang/rust/pull/81858#issuecomment-835314612

I think this probably needs attention from an Android expert to try to repro and fix this issue.  I suspect it's a problem with the library rather than the tests.  The worst case is that it might be a general UB bug in Android Rust programs using `libc::fork` or `Command`.

I'm filing this issue here to try to ask for help again, since writing in #81858 doesn't seem like a particularly good way of getting the attention of Android folks.

If we can't get a resolution, reluctantly, I guess I will disable that test on Android so that my MR can go through.  The current situation is quite a hazard (see eg #79740 "panic! in Command child forked from non-main thread results in exit status 0")

### Technical discussion

I will try to explain what the test does and what the symptoms seem to mean:

The test file has a custom global allocator, whose purpose is to spot allocations in the child after fork.  That global allocator has an atomic variable which is supposed to contain either zero (initially, meaning it's not engaged yet) or the process's pid.  Whenever an allocator method is called, we read the atomic and, if it is not zero, we check it against `process::id()`.  If it doesn't match we `libc::raise(libc::`<strike>`SIGTRAP`</strike> `SIGUSR1)`. 

The test enters `main`, and engages the stunt allocator, recording the program's pid.  Each call to `expect_aborted` (which is called from `run` and therefore from `one`) produces output from `dbg!(status)`.  We see only one of these, so this must be the first test, `one(&|| panic!())`.

The test uses `libc::fork` to fork.  In the child, it calls `panic::always_abort()` (my new function to disable panic unwinding).  It then panics (using the provided closure).  This ought to result in the program dying with `SIGABRT` (or maybe `SIGILL` or `SIGTRAP`).

The parent collects the child's exit status.  For the first test case, we run `expect_aborted`.  This extracts the signal number from it and checks that it is as expected.  On other systems this works.

In the failing test, this test fails.  The assertion on `signal` fails.  Meaning, the child did die of a signal but the signal number wasn't the one expected.  The previous debug print shows that the raw wait status (confusingly described by Rust stdlib as an "exit status") is <strike>`5`</strike>`10`.  Usually, a bare number like that in a wait status is a signal number, and indeed that seems to be the case here since `status.signal()` is `Some(...)`.  On Linux (and most Unices), `5` is `SIGTRAP` and 10 is `SIGUSR1`.

Ie, it seems that the child tried to allocate memory, despite my efforts to make sure that panicking does not involve allocation.  Weirdly, a more-portable test case which uses `Command` and does not insist on specific signal numbers passes.

It's definitely my stunt allocator which is tripping here, because when I changed it to use `SIGUSR` instead of `SIGTRAP`, the failing test case signal number changed too.

### PR DESCRIPTION
**Pull request by flba-eb**
After calling libc::fork, the child process tried to access a TLS variable when processing a panic. This caused a memory allocation which is UB in the child.
To prevent this from happening, the panic handler will not access the TLS variable in case `panic::always_abort` was called before.

Fixes #85261 (not only on Android systems, but also on Linux/QNX with TLS disabled, see issue for more details)

Main drawbacks of this fix:
* Panic messages can incorrectly omit `core::panic::PanicInfo` struct in case several panics (of multiple threads) occur at the same time. The handler cannot distinguish between multiple panics in different threads or recursive ones in the same thread, but the message will contain a hint about the uncertainty.
* `panic_count::increase()` will be a bit slower as it has an additional `if`, but this should be irrelevant as it is only called in case of a panic.

### CODE REVIEW

File: library/std/src/panicking.rs [hunk 1]
```diff
@@ -644,7 +659,13 @@ fn rust_panic_with_hook(
         if panics > 2 {
             // Don't try to print the message in this case
             // - perhaps that is causing the recursive panics.
-            rtprintpanic!("thread panicked while processing panic. aborting.\n");
+            if must_abort {
```
Comment (thomcc) [inline library/std/src/panicking.rs:662]: What's the reason for adding this conditional?

File: library/std/src/panic.rs [hunk 2]
```diff
@@ -183,6 +183,10 @@ pub fn resume_unwind(payload: Box<dyn Any + Send>) -> ! {
 /// and if there is a panic, the abort will occur without allocating provided that the arguments to
 /// panic can be formatted without allocating.
 ///
+/// When using this function on a target which only supports thread local storage through the OS and
```
Comment (thomcc) [inline library/std/src/panic.rs:186]: I don't think we should document this behavior -- it's true, but it's really documenting a limitation we have in an extremely specific edge-case, and in principal the details of this limitation could change. It's hard to imagine how users would benefit from being able to rely on this anyway.

**Review by thomcc — CHANGES_REQUESTED** [review]
I'm mostly in favor here but there are a couple changes that I'd like.

File: library/std/src/panicking.rs (hunk 1 above)
Comment (flba-eb) [reply library/std/src/panicking.rs:662]: The only reason is to print out a different message so that the user is aware about the uncertainty. I thought it might be helpful but is not required.

File: library/std/src/panic.rs (hunk 2 above)
Comment (flba-eb) [reply library/std/src/panic.rs]: Agreed and removed. 👍

File: library/std/src/panicking.rs (hunk 1 above)
Comment (flba-eb) [reply library/std/src/panicking.rs]: Extra message is removed as it is not very helpful and only in very rare cases.

Comment (thomcc) [reply library/std/src/panicking.rs]: From zulip (talking about the case where this branch is hit)

> Thom Chiovoloni: there's a slight race where
>
> - T1 panics, calls increase
> - T2 forks, panics in child before exec
> - T1 (in parent) calls decrease
>
> Thom Chiovoloni: T2 can't look at the local panic count and only global, so it can't if this is different from
> - some thread panics
> - while unwinding, the same thread forks and the child panics before exec
>
> right?

I think this means that we *ideally* would handle this case the `must_abort` case in here the same as below (but without the panic info). In other words: `rtprintpanic!("panicked after panic::always_abort(), aborting.\n");`

Or is there some other case where this matters?

(All that said, I'm kind of fine leaving this with the existing message, since this is *suuuuch* an edge case. That said, giving a slightly better message can't hurt).

**Comment by thomcc** [comment]
Looks good to me.

@bors r+

**Review by thomcc — APPROVED** [review]

**Comment by thomcc** [comment]
@flba-eb reached out and wants to clean up the comments (which might be a little misleading).

@bors r-

**Comment by matthiaskrgr** [comment]
@bors r- rollup=iffy failed in a rollup
https://github.com/rust-lang-ci/rust/actions/runs/3153080316/jobs/5129114093#step:25:15835
https://github.com/rust-lang/rust/pull/102479

**Comment by thomcc** [comment]
Thanks, looks good.

@bors r+

**Comment by flba-eb** [comment]
There seem to be sporadic failures of this test case.
@bors r-

**Comment by flba-eb** [comment]
Improved Android test code is now again ready for review. I've let the arm-android/arm-linux-androideabi test suit run three times on my machine (for about 6 hours) without any issue.

**Comment by thomcc** [comment]
> error: couldn't create a temp dir: Read-only file system (os error 30) at path "/tmp/rustc8Kb1o1"

Seems to be a spurious failure.

@bors r+
