### PR TITLE
Fix method name in `TyCtxt::hir_crate()` documentation

### LINKED ISSUE #137745: TyCtxt::hir_crate references nonexistant function
### Location

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.hir_crate

### Summary

`tcx.visit_all_items_in_krate` does not exist.

### PR DESCRIPTION
**Pull request by samueltardieu**
Fix #137745

### CODE REVIEW

File: compiler/rustc_middle/src/query/mod.rs [hunk 1]
```diff
@@ -147,7 +147,7 @@ rustc_queries! {
     /// we will have to assume that any change means that you need to be recompiled.
     /// This is because the `hir_crate` query gives you access to all other items.
     /// To avoid this fate, do not call `tcx.hir().krate()`; instead,
```
Comment (lqd) [inline compiler/rustc_middle/src/query/mod.rs:149]: this one doesn't exist anymore either, right?

File: compiler/rustc_middle/src/query/mod.rs [hunk 2]
```diff
@@ -147,7 +147,7 @@ rustc_queries! {
...
-    /// prefer wrappers like `tcx.visit_all_items_in_krate()`.
+    /// prefer wrappers like `tcx.hir_visit_all_item_likes_in_crate()`.
```
Comment (lqd) [inline compiler/rustc_middle/src/query/mod.rs:150]: maybe use a rustdoc link instead so that this doesn't regress anymore if the function is renamed again (and it'll improve exploring this function's documentation)

Comment (samueltardieu) [reply compiler/rustc_middle/src/query/mod.rs]: Good idea. Done.

File: compiler/rustc_middle/src/query/mod.rs (hunk 1 above)
Comment (samueltardieu) [reply compiler/rustc_middle/src/query/mod.rs]: Yup, fixed also.

File: compiler/rustc_middle/src/query/mod.rs [hunk 3]
```diff
@@ -143,11 +143,11 @@ rustc_queries! {
...
     /// Represents crate as a whole (as distinct from the top-level crate module).
     ///
-    /// If you call `hir_crate` (e.g., indirectly by calling `tcx.hir().krate()`),
+    /// If you call `hir_crate` (e.g., indirectly by calling `tcx.hir_crate()`),
     /// we will have to assume that any change means that you need to be recompiled.
     /// This is because the `hir_crate` query gives you access to all other items.
-    /// To avoid this fate, do not call `tcx.hir().krate()`; instead,
-    /// prefer wrappers like `tcx.visit_all_items_in_krate()`.
+    /// To avoid this fate, do not call `tcx.hir_crate()`; instead,
+    /// prefer wrappers like [`tcx.hir_visit_all_item_likes_in_crate()`].
```
Comment (lqd) [inline compiler/rustc_middle/src/query/mod.rs:150]: This doesn't look like the correct syntax?

Comment (lolbinarycat) [reply compiler/rustc_middle/src/query/mod.rs:150]: rustdoc will strip the backticks, however, it will **not** strip the parenthesis, those need to be removed.

Comment (fmease) [reply compiler/rustc_middle/src/query/mod.rs:150]: It doesn't strip the parentheses because ``[`f()`]`` links to the same item as `[fn@f]`. However the `tcx.` prevents the link from resolving iinm as rustdoc doesn't perform method resolution for intra-doc links.

Comment (lolbinarycat) [reply compiler/rustc_middle/src/query/mod.rs:150]: oh, good catch! it needs to be formatted like an associated function, not like a method call.

Comment (samueltardieu) [reply compiler/rustc_middle/src/query/mod.rs]: Fixed, and `()` removed to look more like other doc links in the same file.

**Comment by lqd** [comment]
I feel we should do another pass to simplify, improve, and make the comments more consistent on many of these queries. This is good in the meantime.

Merci !

@bors r+ rollup
