### PR TITLE
Accurately portray raw identifiers in error messages

### LINKED ISSUE #65634: Incorrect compiler hints for traits with methods defined using raw identifiers
Code:
```rust
#![allow(non_camel_case_types)]

trait r#async {
    fn r#struct(&self) {
        println!("async");
    }
}

trait r#await {
    fn r#struct(&self) {
        println!("await");
    }
}

struct r#fn {}

impl r#async for r#fn {}
impl r#await for r#fn {}

fn main() {
    r#fn {}.r#struct();
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=78a4411a7fc24d3cd555b65b410ba095))

Error: 
```
error[E0034]: multiple applicable items in scope
  --> src/main.rs:22:13
   |
22 |     r#fn {}.r#struct();
   |             ^^^^^^^^ multiple `struct` found
   |
note: candidate #1 is defined in an impl of the trait `async` for the type `fn`
  --> src/main.rs:5:5
   |
5  |     fn r#struct(&self) {
   |     ^^^^^^^^^^^^^^^^^^
   = help: to disambiguate the method call, write `async::struct(r#fn {})` instead
note: candidate #2 is defined in an impl of the trait `await` for the type `fn`
  --> src/main.rs:11:5
   |
11 |     fn r#struct(&self) {
   |     ^^^^^^^^^^^^^^^^^^
   = help: to disambiguate the method call, write `await::struct(r#fn {})` instead
```
`async::struct(r#fn {})` should be `r#async::r#struct(&r#fn {})`and `await::struct(r#fn {})` should be `r#await::r#struct(&r#fn {})`. It also misses that function signatures require not `self` but `&self`, however this also happens when not using raw identifiers, so I will open another issue for this case.

### PR DESCRIPTION
**Pull request by estebank**
When refering to or suggesting raw identifiers, refer to them with `r#`.

Fix #65634.

### CODE REVIEW

File: src/test/ui/raw-ident-suggestion.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#![allow(non_camel_case_types)]
```
Comment (Centril) [inline src/test/ui/raw-ident-suggestion.rs]: Let's move this file to `ui/issues/issue-65634-raw-ident-suggestion.rs` to avoid cluttering `ui/`

**Comment by Centril** [comment]
r? Centril r=me rollup with ^-- fixed.

File: src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+   |
+LL |     r#fn {}.r#struct();
+   |             ^^^^^^^^ multiple `r#struct` found
+   |
+note: candidate #1 is defined in an impl of the trait `async` for the type `r#fn`
+  --> $DIR/issue-65634-raw-ident-suggestion.rs:4:5
+   |
+LL |     fn r#struct(&self) {
+   |     ^^^^^^^^^^^^^^^^^^
+   = help: to disambiguate the method call, write `async::r#struct(r#fn {})` instead
```
Comment (olegnn) [inline src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr]: I think this should be `r#async::r#struct(r#fn {})` instead of `async::r#struct(r#fn {})`

File: src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr [hunk 3]
```diff
@@ -0,0 +1,22 @@
+error[E0034]: multiple applicable items in scope
+  --> $DIR/issue-65634-raw-ident-suggestion.rs:21:13
+   |
+LL |     r#fn {}.r#struct();
+   |             ^^^^^^^^ multiple `r#struct` found
+   |
+note: candidate #1 is defined in an impl of the trait `async` for the type `r#fn`
```
Comment (olegnn) [inline src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr]: `r#async`

**Review by olegnn — COMMENTED** [review]
Some hints with raw identifiers are still incorrect.

File: src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+   |
+LL |     fn r#struct(&self) {
+   |     ^^^^^^^^^^^^^^^^^^
+   = help: to disambiguate the method call, write `async::r#struct(r#fn {})` instead
+note: candidate #2 is defined in an impl of the trait `await` for the type `r#fn`
+  --> $DIR/issue-65634-raw-ident-suggestion.rs:10:5
+   |
+LL |     fn r#struct(&self) {
+   |     ^^^^^^^^^^^^^^^^^^
+   = help: to disambiguate the method call, write `await::r#struct(r#fn {})` instead
```
Comment (olegnn) [inline src/test/ui/issues/issue-65634-raw-ident-suggestion.stderr]: `r#await::r#struct(r#fn {})`

**Comment by estebank** [comment]
@olegnn it isn't clear from the test (but tested locally, just forgot to add the test file) that this is because the test is running as edition 2015, where `await` is not a keyword, so this is correct. If the test had a header with `// edition:2018` the output would match what you expect.

**Comment by olegnn** [comment]
Sorry, I didn't notice that it's edition 2015. But anyway, if item is declared with `r#` prefix, shouldn't it be mentioned the same way?

**Comment by estebank** [comment]
We don't keep track of whether an identifier was raw or not, we currently infer it from the fact that they couldn't be written any other way (if we have a struct called `struct`, it could only be a raw ident). I think this is fine, we only want to make people aware of raw idents if there's no other option. Only people writing ffi or macros should even need to care about these :)
