### PR TITLE
[12/12] On-demand type-checking, const-evaluation, MIR building & const-qualification.

### LINKED ISSUE #39548: ICE in librustc_const_eval: bad ty_hint: TyBool, Int(1, Unsuffixed)
Playing with different ways to do `static_assert!`, I found an ICE.  Reduced testcase:
```
fn main() {
    let _ : [(); ((1 < 2) == false) as usize] = [];
}
```
Happens in stable and nightly; here's the nightly backtrace from play:
```
rustc 1.16.0-nightly (eedaa94e3 2017-02-02)
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_const_eval/eval.rs:1105: bad ty_hint: TyBool, Int(1, Unsuffixed)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:416
stack backtrace:
   1:     0x7f958019e45c - std::sys::imp::backtrace::tracing::imp::write::hf7294f5e24536b4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f95801ac90e - std::panicking::default_hook::{{closure}}::h9a07d0b00c43fbee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f95801ac4b3 - std::panicking::default_hook::hf25feff2d08bf39b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f95801acdab - std::panicking::rust_panic_with_hook::h4cb8c6fbb8386ccf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f95787bce37 - std::panicking::begin_panic::h133cfd00382ed92d
   6:     0x7f95787d251d - rustc_errors::Handler::bug::h0c95eedc3adddeaa
   7:     0x7f957d2cf10a - rustc::session::opt_span_bug_fmt::{{closure}}::hb77f1c2804eeb101
   8:     0x7f957d2cebc5 - rustc::session::opt_span_bug_fmt::h6020528146c503fb
   9:     0x7f957d2ce822 - rustc::session::bug_fmt::h80c5b006234b3146
  10:     0x7f957e0d3f36 - rustc_const_eval::eval::eval_const_expr_partial::h8d1162fa05e95e72
  11:     0x7f957e0cdad1 - rustc_const_eval::eval::eval_const_expr_partial::h8d1162fa05e95e72
  12:     0x7f957e0cdad1 - rustc_const_eval::eval::eval_const_expr_partial::h8d1162fa05e95e72
  13:     0x7f957e0cdd5e - rustc_const_eval::eval::eval_const_expr_partial::h8d1162fa05e95e72
  14:     0x7f957e0d64b3 - rustc_const_eval::eval::eval_length::h137b8f408aab940b
  15:     0x7f957ebdf58b - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty::hf1f13e8dab321530
  16:     0x7f957eba1553 - <rustc_typeck::check::GatherLocalsVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_local::h3eb6465c4518baea
  17:     0x7f957eb102d6 - rustc::hir::intravisit::walk_expr::h1fd71fafa6424277
  18:     0x7f957eba1cd5 - rustc_typeck::check::check_fn::hdcc283c26b22bc9e
  19:     0x7f957eba0f04 - rustc_typeck::check::check_bare_fn::hf15cf554a01d6e48
  20:     0x7f957eb9e0f5 - rustc_typeck::check::check_item_bodies::ha330650a58a36448
  21:     0x7f957ec0ba47 - rustc_typeck::check_crate::h06f4ceb61c7f6528
  22:     0x7f958054af27 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h074ad5edbf4a7db7
  23:     0x7f958053d356 - rustc_driver::driver::phase_3_run_analysis_passes::h380fa931cb354859
  24:     0x7f958052b160 - rustc_driver::driver::compile_input::hab977ae496b3a6f1
  25:     0x7f9580575a94 - rustc_driver::run_compiler::h81290683db66a63c
  26:     0x7f9580481ebb - std::panicking::try::do_call::h00942d7a5d04424f
  27:     0x7f95801b5bea - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  28:     0x7f95804aa122 - <F as alloc::boxed::FnBox<A>>::call_box::hd87f7ab2fccbd670
  29:     0x7f95801ab764 - std::sys::imp::thread::Thread::new::thread_start::hc16926852e47c008
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  30:     0x7f9577f676b9 - start_thread
  31:     0x7f957fe6182c - clone
  32:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by eddyb**
_This is the last of a series ([prev](https://github.com/rust-lang/rust/pull/38813)) of patches designed to rework rustc into an out-of-order on-demand pipeline model for both better feature support (e.g. [MIR-based](https://github.com/solson/miri) early constant evaluation) and incremental execution of compiler passes (e.g. type-checking), with beneficial consequences to IDE support as well.
If any motivation is unclear, please ask for additional PR description clarifications or code comments._

<hr>

As this contains all of the changes that didn't fit neatly into other PRs, I'll be elaborating a bit:

### User-facing changes
* when determining whether an `impl Trait` type implements an auto-trait (e.g. `Send` or `Sync`), the function the `impl Trait` came from has to be inferred and type-checking, disallowing cycles
  * this results from not having an obvious place to put the "deferred obligation" in on-demand atm
  * while we could model side-effects like that and "post-processing passes" better, it's still more limiting than being able to know the result in the original function (e.g. specialization) *and* there are serious problems around region-checking (if a `Send` impl required `'static`, it wasn't enforced)
* early const-eval requires type-checking and const-qualification to be performed first, which means:
  * you get the intended errors before (if any) constant evaluation error that is simply fallout
  * associated consts should always work now, and `const fn` type parameters are properly tracked
    * don't get too excited, array lengths still can't depend on type parameters
* #38864 works as intended now, with `Self` being allowed in `impl` bounds
* #32205 is largely improved, with associated types being limited to "exact match" `impl`s (as opposed to traversing the specialization graph to resolve unspecified type parameters to their defaults in another `impl` or in the `trait`) *while* checking for overlaps building the specialization graph for that trait - once all the trait impls' have been checked for coherence (including ahead-of-time/on-demand), it's uniform
* [crater report](https://gist.github.com/eddyb/bbb869072468c7e08d6d808e75938051) looks clean (aside from `clippy` which broke due to `rustc` internal changes)

### Compiler-internal changes
* `ty::Generics`
  * no longer contains the actual type parameter defaults, instead they're associated with the type parameter's `DefId`, like associated types in a trait definition
    * this allows computing `ty::Generics` as a leaf (reading only its own HIR)
  * holds a mapping from `DefIndex` of type parameters to their indices
* `ty::AdtDef`
  * only tracks `#[repr(simd)]` in its `ReprOptions` `repr` field
  * doesn't contain `enum` discriminant values, but instead each variant either refers to either an explicit value for its discriminant, or the distance from the last explicit discriminant, if any
    * the `.discriminants(tcx)` method produces an iterator of `ConstInt` values, looking up explicit discriminants in a separate map, if necessary
    * this allows computing `ty::AdtDef` as a leaf (reading only its own HIR)
* Small note: the two above (`Generics`, `AdtDef`), `TraitDef` and `AssociatedItem` should probably end up as part of the HIR, eventually, as they're trivially constructed from it
* `ty::FnSig`
  * now also holds ABI and unsafety, alongside argument types, return type and C variadicity
  * `&ty::BareFnTy` and `ty::ClosureTy` have been replaced with `PolyFnSig = Binder<FnSig>`
    * `BareFnTy` was interned and `ClosureTy` was treated as non-trivial to `Clone` because they had a `PolyFnSig` and so used to contain a `Vec<Ty>` (now `&[Ty]`)
* `ty::maps`
  * all the `DepTrackingMap`s have been grouped in a structure available at `tcx.maps`
  * when creating the `tcx`, a set of `Providers` (one `fn` pointer per map) is required for the local crate, and one for all other crates (i.e. metadata loading), `librustc_driver` plugging the various crates (e.g. `librustc_metadata`, `librustc_typeck`, `librustc_mir`) into it
  * when a map is queried and the value is missing, the appropriate `fn` pointer from the `Providers` of that crate is called with the `TyCtxt` and the key being queried, to produce the value on-demand
* `rustc_const_eval`
  * demands both `typeck_tables` and `mir_const_qualif` (in preparation for miri)
  * tracks `Substs` in `ConstVal::Function` for `const fn` calls
  * returns `TypeckError` if type-checking has failed (or cases that can only be reached if it had)
    * this error kind is never reported, resulting in less noisy/redundant diagnostics 
  * fixes #39548 (testcase by @larsluthman, taken from #39812, which this supersedes)
* on-demand has so far been hooked up to:
  * `rustc_metadata::cstore_impl`: `ty`, `generics`, `predicates`, `super_predicates`, `trait_def`, `adt_def`, `variances`, `associated_item_def_ids`, `associated_item`, `impl_trait_ref`, `custom_coerce_unsized_kind`, `mir`, `mir_const_qualif`, `typeck_tables`, `closure_kind`, `closure_type`
  * `rustc_typeck::collect`: `ty`, `generics`, `predicates`, `super_predicates`, `type_param_predicates`, `trait_def`, `adt_def`, `impl_trait_ref`
  * `rustc_typeck::coherence`: `coherent_trait`, `coherent_inherent_impls`
  * `rustc_typeck::check`: `typeck_tables`, `closure_type`, `closure_kind`
  * `rustc_mir::mir_map`: `mir`
  * `rustc_mir::transform::qualify_consts`: `mir_const_qualif`

### CODE REVIEW

File: src/librustc_mir/transform/qualify_consts.rs [hunk 1]
```diff
@@ -943,41 +931,64 @@ impl<'a, 'tcx> Visitor<'tcx> for Qualifier<'a, 'tcx, 'tcx> {
...
 
 impl Pass for QualifyAndPromoteConstants {}
 
-impl<'tcx> MirPass<'tcx> for QualifyAndPromoteConstants {
+impl<'tcx> MirMapPass<'tcx> for QualifyAndPromoteConstants {
+    fn run_pass<'a>(&mut self,
+                    tcx: TyCtxt<'a, 'tcx, 'tcx>,
+                    hooks: &mut [Box<for<'s> MirPassHook<'s>>])
+    {
+        let def_ids = tcx.maps.mir.borrow().keys();
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/qualify_consts.rs]: it is pretty dubious to iterate over keys -- seems like we should talk over this -- but it may make sense to land the PR and then do a follow-up

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks amazing as usual. My concern is mainly about the dependency graph management. The handling here is definitely dubious, but maybe we want to address it in follow-up PRs.

File: src/librustc/ty/mod.rs [hunk 2]
```diff
@@ -1578,12 +1579,36 @@ impl<'a, 'gcx, 'tcx> AdtDef {
         }
     }
 
-    pub fn destructor(&self) -> Option<DefId> {
-        self.destructor.get()
+    pub fn destructor(&self, tcx: TyCtxt<'a, 'gcx, 'tcx>) -> Option<DefId> {
+        if self.flags.get().intersects(AdtFlags::IS_DTOR_VALID) {
```
Comment (eddyb) [inline src/librustc/ty/mod.rs]: This is pre-existing though. The correct solution IMO is to query the trait system but fixing all the users is a bit tricky.

File: src/librustc_mir/transform/qualify_consts.rs (hunk 1 above)
Comment (eddyb) [inline src/librustc_mir/transform/qualify_consts.rs]: Yeah things like this should probably be switched to iterate over bodies instead.

File: src/librustc/ty/mod.rs (hunk 2 above)
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: ah, it's pre-existing? ok, I guess we can live with it then. I thought I closed up the cells in there, but I guess not.

**Comment by nikomatsakis** [comment]
@eddyb you seen the travis failures?

**Comment by nikomatsakis** [comment]
@eddyb ok, so to summarize what we said on IRC (and "for the record"):

- The wacky dep-graph stuff is pre-existing, I'll try to prioritize fixing it.
- The `Default` trait seems me as risky, but for now we'll bias towards "keep going with compilation, even if you get weird derived errors". We can either patch problems one by one, or try to remove the `Default` trait impl and then make the default cases abort if we don't have a good recovery for them.

So -- yeah, r=me, let's just land this thing already.

**Comment by eddyb** [comment]
Note to self: never use the GitHub conflict resolution UI, it makes merge commits.

**Comment by eddyb** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

😞 Is this my fault, making `rustc` too slow?

**Comment by eddyb** [comment]
@bors retry
* maybe the timeout was spurious

**Comment by eddyb** [comment]
@bors retry
* OSX... something. network error?

**Comment by eddyb** [comment]
Welp, it was me: I compared the log with a previous build and it went from `2:22:27` to `2:51:53`.
Worst of it AFAICT is `compile-fail`: `201.065` seconds to `661.318` seconds.

**Comment by eddyb** [comment]
I can't reproduce a slowdown locally, so I'm still confused.

**Comment by eddyb** [comment]
@bors retry
* it must be spurious, *riiight?*

**Comment by eddyb** [comment]
FWIW, investigation is ongoing in #40114.

**Comment by eddyb** [comment]
@bors r=nikomatsakis

Indeed, it appears those filemaps were adding `3MB` to `libstd`'s `3.5MB` - that's a lot of them!

As to what this PR does differently: when doing *any* request without an explicit `Span` (so all of the `tcx` methods, e.g. `tcx.item_generics(def_id)`, `tcx.item_type(def_id)`, etc.), the `Span` of the `DefId` was being computed for the "on-demand cycle-check stack", which would also happen for cross-crate `DefId`s.

Now, that may seem expensive, but *it's empirically unmeasurable* (except maybe this PR would speed other things up so what I'm seeing is speedup + slowdown => neutral), *unless* those cross-crate `Span`s require reading all the cross-crate filemaps *and* there were *a lot* of them (from save-analysis).
