### PR TITLE
fix is_disaligned logic for nested packed structs

### LINKED ISSUE #99838: Misaligned reference from drop field in packed struct
I tried this code:

```rust
struct U16(u16);

impl Drop for U16 {
    fn drop(&mut self) {
        println!("{:p}", self);
    }
}

struct HasDrop;

impl Drop for HasDrop {
    fn drop(&mut self) {}
}

#[repr(packed)]
struct Misalign(u8, Wrapper);

struct Wrapper {
    _a: U16,
    b: HasDrop,
}

fn main() {
    let m = Misalign(
        0,
        Wrapper {
            _a: U16(10),
            b: HasDrop,
        },
    );
    let _x = m.1.b;
}
```

I expected to see this happen: The reference is aligned

Instead, this happened:
```
$ rustc +nightly -Copt-level=3 test.rs
$ ./test
0x7ffc5e1dad79
```

### Meta
`rustc --version --verbose`:
```
rustc 1.64.0-nightly (2643b1646 2022-07-27)
binary: rustc
commit-hash: 2643b16468fda787470340890212591d8bc832b7
commit-date: 2022-07-27
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

@rustbot label I-unsound A-mir

### PR DESCRIPTION
**Pull request by RalfJung**
https://github.com/rust-lang/rust/pull/83605 broke the `is_disaligned` logic by bailing out of the loop in `is_within_packed` early. This PR fixes that problem and adds suitable tests.

Fixes https://github.com/rust-lang/rust/issues/99838

### CODE REVIEW

File: compiler/rustc_const_eval/src/util/alignment.rs [hunk 1]
```diff
@@ -48,20 +50,32 @@ fn is_within_packed<'tcx, L>(
...
-                    ty::Adt(def, _) => return def.repr().pack,
+                    ty::Adt(def, _) => {
+                        if let Some(pack) = def.repr().pack {
+                            // Merge this type's attribute with the ones we have seen so far.
+                            // The overall smallest alignment is what matters.
+                            min_packed = Some(match min_packed {
+                                Some(prev_min) => cmp::min(prev_min, pack),
+                                None => pack,
+                            })
+                        }
```
Comment (JakobDegen) [inline compiler/rustc_const_eval/src/util/alignment.rs:71]: This could be `.take_while().filter_map().min()` depending on how you feel

**Review by JakobDegen — APPROVED** [review]

**Comment by petrochenkov** [comment]
r=me after squashing commits.
@rustbot author

**Comment by RalfJung** [comment]
@bors r=petrochenkov p=1
let's get this soundness fix in before beta branches on Friday
