### PR TITLE
rustdoc: Filter more incorrect methods inherited through Deref

### LINKED ISSUE #35169: Rustdoc: Wrong documentation in case of types that only implement Deref, but not DerefMut
Wrong documentation is generated for types that only implement Deref, but not DerefMut. It inherits methods from both Deref and DerefMut.

Steps to reproduce:
`cargo new deref-doc-bug`

````
/// lib.rs
pub struct Foo;

impl std::ops::Deref for Foo {
    type Target = [char];
    fn deref(&self) -> &[char] { &[] }
}
````
`cargo doc --open`

Generated documentation has methods for both `&[char]` and `&mut [char]`, for example`fn get_mut`.

## Version
````
rustc 1.12.0-nightly (1225e122f 2016-07-30)
rustdoc 1.12.0-nightly (1225e122f 2016-07-30)
````

### PR DESCRIPTION
**Pull request by Sawyer47**
Old code filtered out only static methods. This code also excludes &mut self methods if there is no DerefMut implementation.

Fixes #35169

### CODE REVIEW

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -2707,22 +2719,39 @@ fn render_impl(w: &mut fmt::Formatter, cx: &Context, i: &Impl, link: AssocItemLi
...
+                    _ => None
+                };
+
+                if let Some(self_ty) = self_type_opt {
+                    match self_ty {
+                        SelfTy::SelfValue => true,
+                        SelfTy::SelfBorrowed(_lifetime, mutability) => {
+                            deref_mut_ || mutability == Mutability::Immutable
+                        },
+                        SelfTy::SelfExplicit(_) => false,
```
Comment (ollie27) [inline src/librustdoc/html/render.rs]: This also matches things like `self: &Self`, `self: &Foo`, `self: &mut Self`, `self: &mut Foo`, `self: Self` and `self: Foo` which we don't want to remove.

**Comment by GuillaumeGomez** [comment]
:+1: 

Waiting for @steveklabnik's confirmation.

**Comment by GuillaumeGomez** [comment]
cc @alexcrichton

**Comment by steveklabnik** [comment]
Seems like a good idea to me, I wonder what alex thinks.

**Comment by alexcrichton** [comment]
@bors: r+ 915bbdac580b26e2d47baa1ca3fd21349c4f4b0b

Thanks!
