### PR TITLE
Typo suggestion to change bindings with leading underscore

### LINKED ISSUE #60164: Suggest changing `_x` to `x` instead of a use of `x` to `_x`
Variables can be marked as unused by prepending with an underscore. If at some point such a variable is used again, the compiler suggests to name the use `_x`, even though every single time I have encountered this, what I wanted is to change the definition of `_x` to `x`.

```rust
fn main() {
    let _x = 42;
    let y = x;
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=048e1ff416fb850e7da08c31373b4433))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0465]: multiple rlib candidates for `debug_unreachable` found
  |
  = note: candidate #1: /playground/target/debug/deps/libdebug_unreachable-aa3385f4476cae47.rlib
  = note: candidate #2: /playground/target/debug/deps/libdebug_unreachable-661505f3db863158.rlib

error[E0425]: cannot find value `x` in this scope
 --> src/main.rs:3:13
  |
3 |     let y = x;
  |             ^ help: a local variable with a similar name exists: `_x`

error: aborting due to 2 previous errors

Some errors occurred: E0425, E0465.
For more information about an error, try `rustc --explain E0425`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by estebank**
When encountering a binding that isn't found but has a typo suggestion for a binding with a leading underscore, suggest changing the binding definition instead of the use place.

Fix #60164.

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1511,17 +1511,30 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                 ),
             );
         }
+
+        let (span, sugg, post) = if let SuggestionTarget::SimilarlyNamed = suggestion.target
+            && let Ok(snippet) = self.tcx.sess.source_map().span_to_snippet(span)
+            && let Some(span) = suggestion.span
+            && suggestion.candidate.as_str().starts_with("_")
+            && snippet == suggestion.candidate.as_str()[1..]
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/diagnostics.rs:1519]: can probably write this as

```suggestion
            && let Some(suggestion) = suggestion.candidate.as_str().strip_prefix("_")
            && snippet == suggestion
```

**Review by oli-obk — APPROVED** [review]
