### PR TITLE
rustdoc: fix attrs of locally reexported foreign items

### LINKED ISSUE #135092: Rustdoc does not combine documentation in re-exports of extern functions
With the code

```rust
mod native {
    extern "C" {
        /// bar.
        pub fn bar();
    }
}

/// foo
pub use native::bar;
```

I expected to have the documentation in the private module and the re-export to be combined

Instead, only the documentation in the private module in shown

Image

### Meta

`rustdoc --version --verbose`:
```
rustdoc 1.86.0-nightly (3f43b1a63 2025-01-03)
binary: rustdoc
commit-hash: 3f43b1a636738f41c48df073c5bcb97a97bf8459
commit-date: 2025-01-03
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.6
```

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes rust-lang/rust#135092

also tweaks a few outdated/misleading comments.

r? @GuillaumeGomez

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -115,16 +115,9 @@ pub(crate) fn clean_doc_module<'tcx>(doc: &DocModule<'tcx>, cx: &mut DocContext<
...
-                let path = hir::Path { segments, res: *res, span };
-                clean_use_statement_inner(
-                    import,
-                    Some(name),
-                    &path,
-                    kind,
-                    cx,
-                    &mut Default::default(),
-                )
+                //let hir::UsePath { segments, span, .. } = *path;
```
Comment (aDotInTheVoid) [inline src/librustdoc/clean/mod.rs]: Could you get rid of these?

Comment (lolbinarycat) [reply src/librustdoc/clean/mod.rs]: actually this whole change should be reverted, i made it in testing when i was trying to eliminate differences between code paths, but it's not actually required or correct.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup
