### PR TITLE
BTreeMap mutable iterators should not take any reference to visited nodes during iteration

### LINKED ISSUE #73915: Miri failure in btree::map::test_iter_min_max test
`btree::map::test_iter_min_max` recently started failing in Miri:
```
error: Undefined Behavior: not granting access to tag <untagged> because incompatible item is protected: [Unique for <26146034> (call 7514376)]

   --> /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/ptr/non_null.rs:121:9

    |

121 |         &*self.as_ptr()

    |         ^^^^^^^^^^^^^^^ not granting access to tag <untagged> because incompatible item is protected: [Unique for <26146034> (call 7514376)]

    |

    = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental

    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information

            

    = note: inside `std::ptr::NonNull::<alloc::collections::btree::node::LeafNode<i32, i32>>::as_ref` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/ptr/non_null.rs:121:9

    = note: inside `alloc::collections::btree::node::NodeRef::<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>::as_leaf` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/node.rs:321:18

    = note: inside `alloc::collections::btree::node::NodeRef::<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>::len` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/node.rs:293:9

    = note: inside `alloc::collections::btree::node::Handle::<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>, alloc::collections::btree::node::marker::Edge>::new_edge` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/node.rs:802:30

    = note: inside `alloc::collections::btree::node::Handle::<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>::forget_node_type` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/node.rs:1361:18

    = note: inside `alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>>::next_kv` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/navigate.rs:16:24

    = note: inside closure at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/navigate.rs:132:26

    = note: inside `alloc::collections::btree::navigate::replace::<alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>, alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>, alloc::collections::btree::node::marker::KV>, [closure@alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut<'a>, K, V, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>>::next_unchecked::{{closure}}#0]>` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/navigate.rs:88:28

    = note: inside `alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>>::next_unchecked` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/navigate.rs:131:22

    = note: inside `std::collections::btree_map::RangeMut::<i32, i32>::next_unchecked` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/map.rs:1904:18

    = note: inside `<std::collections::btree_map::IterMut<i32, i32> as std::iter::Iterator>::next` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/map.rs:1457:35

    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::next` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/liballoc/collections/btree/map.rs:1810:9

    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::fold::<&mut i32, [closure@std::iter::Iterator::min_by::fold::{{closure}}#0 0:for<'r, 's> fn(&'r &mut i32, &'s &mut i32) -> std::cmp::Ordering {<&mut i32 as std::cmp::Ord>::cmp}]>` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/iter/traits/iterator.rs:2021:29

    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::fold_first::<[closure@std::iter::Iterator::min_by::fold::{{closure}}#0 0:for<'r, 's> fn(&'r &mut i32, &'s &mut i32) -> std::cmp::Ordering {<&mut i32 as std::cmp::Ord>::cmp}]>` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/iter/traits/iterator.rs:2061:14

    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::min_by::<for<'r, 's> fn(&'r &mut i32, &'s &mut i32) -> std::cmp::Ordering {<&mut i32 as std::cmp::Ord>::cmp}>` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/iter/traits/iterator.rs:2627:9

    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::min` at /home/travis/build/RalfJung/miri-test-libstd/rust-src-patched/src/libcore/iter/traits/iterator.rs:2499:9

note: inside `btree::map::test_iter_min_max` at alloc_miri_test/../liballoc/tests/btree/map.rs:343:16

   --> alloc_miri_test/../liballoc/tests/btree/map.rs:343:16

    |

343 |     assert_eq!(a.values_mut().min(), Some(&mut 24));

    |                ^^^^^^^^^^^^^^^^^^^^

note: inside closure at alloc_miri_test/../liballoc/tests/btree/map.rs:313:1

   --> alloc_miri_test/../liballoc/tests/btree/map.rs:313:1

    |

313 | / fn test_iter_min_max() {

314 | |     let mut a = BTreeMap::new();

315 | |     assert_eq!(a.iter().min(), None);

316 | |     assert_eq!(a.iter().max(), None);

...   |

344 | |     assert_eq!(a.values_mut().max(), Some(&mut 42));

345 | | }

    | |_^
```
(Sorry for the bad spacing, Travis logs are like that...)

### PR DESCRIPTION
**Pull request by ssomers**
Fixes #73915, overlapping mutable references during BTreeMap iteration

r? @RalfJung

### CODE REVIEW

**Comment by ssomers** [comment]
benchcmp old newer --threshold 5
```
 name                                   old ns/iter  newer ns/iter  diff ns/iter   diff %  speedup
 btree::map::find_rand_100              17           18                        1    5.88%   x 0.94
 btree::map::find_seq_10_000            39           43                        4   10.26%   x 0.91
 btree::map::insert_rand_100            41           36                       -5  -12.20%   x 1.14
 btree::map::insert_rand_10_000         41           36                       -5  -12.20%   x 1.14
 btree::map::insert_seq_100             49           45                       -4   -8.16%   x 1.09
 btree::map::insert_seq_10_000          94           102                       8    8.51%   x 0.92
 btree::map::iter_0                     1,724        1,509                  -215  -12.47%   x 1.14
 btree::map::iter_100                   2,706        3,294                   588   21.73%   x 0.82
 btree::map::iteration_mut_1000         3,916        4,215                   299    7.64%   x 0.93
 btree::map::iteration_mut_100000       458,680      487,070              28,390    6.19%   x 0.94
 btree::map::range_included_excluded    390,220      410,035              19,815    5.08%   x 0.95
 btree::map::range_included_included    434,763      397,835             -36,928   -8.49%   x 1.09
 btree::map::range_unbounded_unbounded  28,255       36,724                8,469   29.97%   x 0.77
 btree::map::range_unbounded_vs_iter    28,810       34,102                5,292   18.37%   x 0.84
 btree::set::is_subset_100_vs_10k       1,269        1,394                   125    9.85%   x 0.91
```

File: src/liballoc/collections/btree/node.rs [hunk 1]
```diff
@@ -314,21 +316,26 @@ impl<BorrowType, K, V, Type> NodeRef<BorrowType, K, V, Type> {
...
         // it should be unique or shared.
-        unsafe { self.node.as_ref() }
+        self.node.as_ptr()
     }
 
-    /// Borrows a view into the keys stored in the node.
-    pub fn keys(&self) -> &[K] {
-        self.reborrow().into_key_slice()
+    /// Borrows a reference to one of the keys stored in the node.
+    /// SAFETY: the caller must ensure that the node has initialized more than `idx` elements.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:330]:
```suggestion
    /// SAFETY: the caller must ensure that the node has more than `idx` initialized elements.
```

File: src/liballoc/collections/btree/node.rs [hunk 2]
```diff
@@ -314,21 +316,26 @@ impl<BorrowType, K, V, Type> NodeRef<BorrowType, K, V, Type> {
...
+    pub unsafe fn key_at(&self, idx: usize) -> &K {
+        unsafe { self.reborrow().into_key(idx) }
     }
 
-    /// Borrows a view into the values stored in the node.
-    fn vals(&self) -> &[V] {
-        self.reborrow().into_val_slice()
+    /// Borrows a reference to one of the values stored in the node.
+    /// SAFETY: the caller must ensure that the node has initialized more than `idx` elements.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:336]:
```suggestion
    /// SAFETY: the caller must ensure that the node has more than `idx` initialized elements.
```

File: src/liballoc/collections/btree/node.rs [hunk 3]
```diff
@@ -463,13 +463,13 @@ impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Immut<'a>, K, V, Type> {
...
         debug_assert!(idx < self.len());
-        unsafe { &*MaybeUninit::first_ptr(&(*self.as_leaf()).keys).add(idx) }
+        unsafe { &MaybeUninit::get_ref(&(*self.as_leaf()).keys[idx]) }
     }
 
     /// SAFETY: the caller must ensure that the node has more than `idx` elements.
     unsafe fn into_val(self, idx: usize) -> &'a V {
         debug_assert!(idx < self.len());
-        unsafe { &*MaybeUninit::first_ptr(&(*self.as_leaf()).vals).add(idx) }
+        unsafe { &MaybeUninit::get_ref(&(*self.as_leaf()).vals[idx]) }
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs]: Nice!
Could you add a comment saying that we are only creating a reference to the one element we are interested in here, and thus avoid aliasing with outstanding references to other elements?

File: src/liballoc/collections/btree/node.rs [hunk 4]
```diff
@@ -460,19 +460,19 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
 }
 
 impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Immut<'a>, K, V, Type> {
-    /// SAFETY: the caller must ensure that the node has more than `idx` elements.
+    /// SAFETY: the caller must ensure that the node has initialized more than `idx` elements.
     unsafe fn into_key(self, idx: usize) -> &'a K {
         debug_assert!(idx < self.len());
-        unsafe { &MaybeUninit::get_ref(&(*self.as_leaf()).keys[idx]) }
+        unsafe { &MaybeUninit::get_ref(&(*self.as_leaf()).keys.get_unchecked(idx)) }
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:466]: Now this is surprising that this works... `get_unchecked` needs a reference to the entire slice, and only then performs indexing. Really what we want here is unchecked indexing on the raw slice.

I think the only way to do this currently is to do a cast of `&raw const (*self.as_leaf()).keys` to `*const K`, then do `add(idx)`.

Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:466]: I'm lost, but I'll try to feel my way out again. Beware that (what I thought is) this change from checked to unchecked indexing is for the immutable case which wasn't a problem. When I replace `[]` with `.get_unchecked_mut` in the third function `into_key_val_mut`,  the one where it matters for Miri and so that I had forgotten about already, the compiler says the thing resulting from `.get_unchecked_mut`  is a temporary that it can't return. Even adding enough parenthesis to hide my lack of knowledge of operator precedence. Though I can get the stuff compiled with `.get_unchecked_mut` but probably it's not the executing the one from slice because then Miri protests again on the new test case. Again, I confirm it does not protest with checked indexing, or whatever `[]` really is.

Also, surely the first `&` is smoke and mirrors? It compiles and works the same without. `get_ref` returns a reference already.

**Comment by ssomers** [comment]
Your "only way to do this currently" works too, and says basically no change in performance: benchcmp old newest --threshold 5
```
 name                                           old ns/iter  newest ns/iter  diff ns/iter   diff %  speedup
 btree::map::find_rand_100                      17           18                         1    5.88%   x 0.94
 btree::map::first_and_last_100                 47           42                        -5  -10.64%   x 1.12
 btree::map::first_and_last_10k                 64           74                        10   15.62%   x 0.86
 btree::map::insert_rand_100                    41           36                        -5  -12.20%   x 1.14
 btree::map::insert_rand_10_000                 41           36                        -5  -12.20%   x 1.14
 btree::map::insert_seq_100                     49           45                        -4   -8.16%   x 1.09
 btree::map::insert_seq_10_000                  94           99                         5    5.32%   x 0.95
 btree::map::range_included_excluded            390,220      410,650               20,430    5.24%   x 0.95
 btree::map::range_unbounded_unbounded          28,255       37,597                 9,342   33.06%   x 0.75
 btree::set::difference_random_100_vs_10k       2,521        2,745                    224    8.89%   x 0.92
 btree::set::intersection_random_100_vs_10k     2,322        2,581                    259   11.15%   x 0.90
 btree::set::intersection_random_10k_vs_100     2,305        2,649                    344   14.92%   x 0.87
 btree::set::intersection_staggered_100_vs_10k  2,125        2,233                    108    5.08%   x 0.95
```

Thanks to baby steps, I think I understand that code better than anything before, but I think you'll agree it's not great to have (more of) this sort of code written out in btree directly. But I couldn't even write a generic function reusable for keys and vals.

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: Your old code took a reference to `(*self.as_leaf()).keys[idx]`. That is just a reference to a single element, so all is good -- no aliasing with references to other elements.

Your new code creates a reference to `(*self.as_leaf()).keys`. This *does* always with other elements, hence I think we should not do it.

> for the immutable case which wasn't a problem

Ah I guess that explains why we are not seeing Miri failures.

File: src/liballoc/tests/btree/map.rs [hunk 5]
```diff
@@ -25,6 +26,20 @@ const MIN_INSERTS_HEIGHT_1: usize = NODE_CAPACITY + 1;
 // It's not the minimum size: removing an element from such a tree does not always reduce height.
 const MIN_INSERTS_HEIGHT_2: usize = NODE_CAPACITY + (NODE_CAPACITY + 1) * NODE_CAPACITY + 1;
 
+// Gather all references from a mutable iterator and make sure Miri notices if
+// using them is dangerous.
+fn test_all_refs<'a, T: 'a>(dummy: &mut T, iter: impl Iterator<Item = &'a mut T>) {
```
Comment (RalfJung) [inline src/liballoc/tests/btree/map.rs:31]: I added a `cfg_attr(miri, ignore)` to the min_max test, could you also remove that?

File: src/liballoc/tests/btree/map.rs [hunk 6]
```diff
@@ -269,6 +284,12 @@ fn test_iter_mut_mutation() {
 
 #[test]
 fn test_values_mut() {
+    let mut a: BTreeMap<_, _> = (0..2).map(|i| (i, i)).collect();
+    test_all_refs(&mut 13, a.values_mut());
```
Comment (RalfJung) [inline src/liballoc/tests/btree/map.rs:288]: Should we also test this is a 144-element tree (or whatever the threshold was for getting another layer of nodes)?

**Comment by RalfJung** [comment]
Btw, what are "alies" (in the PR title)? Probably you meant "allies" but even then I don't get it.^^

**Comment by RalfJung** [comment]
> Thanks to baby steps, I think I understand that code better than anything before, but I think you'll agree it's not great to have (more of) this sort of code written out in btree directly. But I couldn't even write a generic function reusable for keys and vals.

Indeed, what we should have is https://github.com/rust-lang/rust/issues/60639 so you can just index the raw slice directly. https://github.com/rust-lang/rust/issues/73987 makes that hard though.

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: So you're saying that (in C++ terms) operator[] is quite different from `get_unchecked` with a bouncer posted at the front door? Perhaps operator[] is not even the same as plain `get`? That's... unexpected.

>  that explains why we are not seeing Miri failures.

Because it's perfectly fine to refer to read-only slices all over the place... So why was I messing about in that code? I guess it was relevant when that branch started. Now it's still nice to keep passing the index for symmetry with the mutable API, but maybe revert these two implementations to MaybeUnit slice code?

File: src/liballoc/tests/btree/map.rs (hunk 5 above)
Comment (ssomers) [reply src/liballoc/tests/btree/map.rs:31]: During the next rebase... at which point, do I also squash your commit or keep that separate?

File: src/liballoc/tests/btree/map.rs (hunk 6 above)
Comment (ssomers) [reply src/liballoc/tests/btree/map.rs:288]: Definitely seems like a good idea to me (it's 12 to open up the second layer).

**Comment by ssomers** [comment]
Good question, who are these allies? I was thinking of `values_mut`, `range_mut` passes through the mutable `next_unchecked` too. So does `remove_kv_tracking` but it discards the result, so I think that's all.

Which takes us back to your comment "Doing the descend [...] invalidates the references returned by `into_kv_mut`" now residing in that mutable `next_unchecked`. I wonder if it's still relevant; in fact, I wonder if that ever was enough of a solution? If the result of `into_kv_mut` is wrecked by navigating the tree, how can you navigate the tree while the caller can cling onto the result of `into_kv_mut`? Except that there was no test case clinging on to the result. Back in #58431 you wrote that `len` was the culprit already, and now that `len` is trouble free. I tried reverting that special case and Miri says it's fine now.

**Comment by ssomers** [comment]
Sigh... I just checked if "Miri is too slow" to check 144 references, i.e. 3 levels. It is not. It is, in fact, very fast to point out that something is still broken.

**Comment by ssomers** [comment]
About the original code:
- `MaybeUninit::get_mut(&mut (*leaf).vals[idx])` is the code without raw pointers that keeps Miri happy on the new test (commit 5500b31b28e81b6e8f46ae19d4c50a8d2be10b86)
- `MaybeUninit::get_mut(&mut (((*leaf).vals)[idx]))` works like the above (I'm not sure it's the same though)
- `((*leaf).vals).get_unchecked_mut(idx).get_mut()` compiles & tests fine but fails under Miri (didn't manage to compile with an explicit `MaybeUninit::get_mut`)
- `((*leaf).vals).get_mut(idx).unwrap().get_mut()` works like the above

**Comment by ssomers** [comment]
The way I understand the issue now, it seems very likely this would fail for any other mutable iterator implementation that doesn't apply social distancing to its elements, so everything but linked lists. It's definitely [not hard to make Miri mad at VecDeque::iter_mut](https://play.rust-lang.org/?edition=2018&gist=a4554cb559927e74ce71f75af1ba1d45).

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: Yes. `[]` is a MIR built-in, which is very different from a method call.

I appreciate that from a surface-level perspective, that is rather surprising. Unfortunately I have no idea how to make this less surprising without breaking even more things.^^

> Now it's still nice to keep passing the index for symmetry with the mutable API

Yeah, I think it makes a lot of sense to just generally avoid creating these slices in the first place, just to avoid unnecessary aliasi8ng assumptions.

File: src/liballoc/tests/btree/map.rs (hunk 5 above)
Comment (RalfJung) [reply src/liballoc/tests/btree/map.rs:31]: IMO it makes sense to keep it separate, but I have no strong opinion either way.

**Comment by RalfJung** [comment]
> Except that there was no test case clinging on to the result. Back in #58431 you wrote that len was the culprit already, and now that len is trouble free. I tried reverting that special case and Miri says it's fine now.

Which special case? Fixing `len` just falls out of making `as_leaf` return a raw pointer instead of a reference, doesn't it?

> MaybeUninit::get_mut(&mut (*leaf).vals[idx]) is the code without raw pointers that keeps Miri happy on the new test (commit 5500b31)

The crucial part is that it is without references: the only reference being created here is to `(*leaf).vals[idx]`, which does not overlap with the other elements. That's why this is okay from an aliasing perspective.

> &mut (((*leaf).vals)[idx])

This is the same.

The other two create a reference to the entire `vals` array, which overlaps with the mutable reference that was handed out earlier. This I would indeed expect them to fail.

> It's definitely not hard to make Miri mad at VecDeque::iter_mut.

Uh-oh.^^ I was going to apply that mutable-iterator testcase to other collections, didn't expect issues to show up so quickly though. Do you want to open an issue for `VecDeque`?

**Comment by ssomers** [comment]
> Which special case?

The one I though I reverted by commit aa0681fef26beb812884de5f0a92b6f5aab4a006... but looking closer, this doesn't revert the order you set in in #58431, but merely stores the result of navigation later and obfuscates the important order. When I try to really swap the order, Miri complains again (on the 12 element test that's currently committed).

**Comment by ssomers** [comment]
> open an issue for `VecDeque`?

Sure, you'll soon get #74029 on your plate.

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: I've simplified the immutable implementations on MaybeUnit again.

File: src/liballoc/collections/btree/node.rs [hunk 7]
```diff
@@ -453,18 +460,25 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
 }
 
 impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Immut<'a>, K, V, Type> {
-    fn into_key_slice(self) -> &'a [K] {
-        unsafe { slice::from_raw_parts(MaybeUninit::first_ptr(&self.as_leaf().keys), self.len()) }
+    /// SAFETY: the caller must ensure that the node has more than `idx` initialized elements.
+    unsafe fn into_key(self, idx: usize) -> &'a K {
+        debug_assert!(idx < self.len());
+        let leaf = self.as_leaf();
+        unsafe { &*MaybeUninit::first_ptr(&(*leaf).keys).add(idx) }
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:467]: I assume this is what you mean by "simplified"?

But now this assumes that there is no outstanding mutable reference to *any* key of this node. Maybe that's okay, but the safety comment should at least say that.

**Comment by RalfJung** [comment]
So is `MIN_INSERTS_HEIGHT_2` still broken or did you latest changes fix that?

**Comment by ssomers** [comment]
It's still broken from 19 elements on. I only changed the code backing immutable iterators.

**Comment by RalfJung** [comment]
The original mutable iterator testcase failed for 2 elements, so something presumably also changed there?

Do you know what is the problem with 19 elements or do you want me to take a look?

**Comment by ssomers** [comment]
> so something presumably also changed there?

Well, what changed is most of this PR? You handled `len` and other code using `as_leaf`, `into_key_val_mut` is also completely using raw pointers, but it's still not enough for 19 or more elements (*). This PR also tweaks the API used by immutable iterators to keep it in line with the API for mutable iterators.

Np I have no idea what the problem is and I see [you write it's quite awful to debug](https://github.com/rust-lang/miri/issues/974) so definitely have a look.

(*) The threshold is 19 elements if inserted in ascending order, like the test case does. In addition, one can insert up to 5 more smaller (negative) keys (which should land in the first child node).

**Comment by ssomers** [comment]
I think I got there through reasoning: 19 elements is indeed the first tree with children and two elements at the root and the first tree where `next_kv` ascends back into the root, while there is an outstanding reference inside the root already. I bet it's actually `forget_node_type` that "refers to" the root node again.

File: src/liballoc/collections/btree/node.rs (hunk 7 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:467]: I mean "simplified" as not relying on raw pointer code.

I'm trying to make this more clear, in addition to a comment, using:
```
 let leaf = unsafe { &(*self.as_leaf()) };
```

**Comment by RalfJung** [comment]
> Well, what changed is most of this PR? 

You wrote "I only changed the code backing immutable iterators", that's why I was confused -- the PR looks like it changes much more than that. I probably misunderstood what you were referring to.

**Comment by ssomers** [comment]
> You wrote "I only changed the code backing immutable iterators", that's why I was confused -- the PR looks like it changes much more than that. I probably misunderstood what you were referring to.

Sorry, I was referring only to the latest changes, those after discovering the 19 element problem.

I'm trying to rewrite the code to get around `forget_node_type`, which I think would prove it was the remaining culprit. Or one of them...

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: I think the simplest approach would be to use the raw slice indexing I am adding in https://github.com/rust-lang/rust/pull/73986 -- maybe we can do that in a follow-up PR.

**Comment by RalfJung** [comment]
Here's the backtrace where the reference gets invalidated:
```
note: tracking was triggered
   --> /home/r/src/rust/rustc/src/liballoc/collections/btree/node.rs:276:18
    |
276 |         unsafe { &*(self.node.as_ptr() as *mut InternalNode<K, V>) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ popped tracked tag for item [Unique for <50139> (call 16054)]
    |
    = note: inside `alloc::collections::btree::node::NodeRef::<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Internal>::as_internal` at /home/r/src/rust/rustc/src/liballoc/collections/btree/node.rs:276:18
    = note: inside `alloc::collections::btree::node::Handle::<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Internal>, alloc::collections::btree::node::marker::Edge>::descend` at /home/r/src/rust/rustc/src/liballoc/collections/btree/node.rs:978:20
    = note: inside `alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>, alloc::collections::btree::node::marker::KV>>::next_leaf_edge` at /home/r/src/rust/rustc/src/liballoc/collections/btree/navigate.rs:242:17
    = note: inside closure at /home/r/src/rust/rustc/src/liballoc/collections/btree/navigate.rs:134:18
    = note: inside `alloc::collections::btree::navigate::replace::<alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>, alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::LeafOrInternal>, alloc::collections::btree::node::marker::KV>, [closure@alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut<'a>, K, V, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>>::next_unchecked::{{closure}}#0]>` at /home/r/src/rust/rustc/src/liballoc/collections/btree/navigate.rs:88:28
    = note: inside `alloc::collections::btree::navigate::<impl alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Leaf>, alloc::collections::btree::node::marker::Edge>>::next_unchecked` at /home/r/src/rust/rustc/src/liballoc/collections/btree/navigate.rs:131:22
    = note: inside `std::collections::btree_map::RangeMut::<i32, i32>::next_unchecked` at /home/r/src/rust/rustc/src/liballoc/collections/btree/map.rs:1904:18
    = note: inside `<std::collections::btree_map::IterMut<i32, i32> as std::iter::Iterator>::next` at /home/r/src/rust/rustc/src/liballoc/collections/btree/map.rs:1457:35
    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::next` at /home/r/src/rust/rustc/src/liballoc/collections/btree/map.rs:1810:9
    = note: inside `std::vec::Vec::<&mut i32>::extend_desugared::<std::collections::btree_map::ValuesMut<i32, i32>>` at /home/r/src/rust/rustc/src/liballoc/vec.rs:2217:35
    = note: inside `<std::vec::Vec<&mut i32> as std::vec::SpecExtend<&mut i32, std::collections::btree_map::ValuesMut<i32, i32>>>::spec_extend` at /home/r/src/rust/rustc/src/liballoc/vec.rs:2110:9
    = note: inside `<std::vec::Vec<&mut i32> as std::vec::SpecExtend<&mut i32, std::collections::btree_map::ValuesMut<i32, i32>>>::from_iter` at /home/r/src/rust/rustc/src/liballoc/vec.rs:2105:9
    = note: inside `<std::vec::Vec<&mut i32> as std::iter::FromIterator<&mut i32>>::from_iter::<std::collections::btree_map::ValuesMut<i32, i32>>` at /home/r/src/rust/rustc/src/liballoc/vec.rs:1995:9
    = note: inside `<std::collections::btree_map::ValuesMut<i32, i32> as std::iter::Iterator>::collect::<std::vec::Vec<&mut i32>>` at /home/r/src/rust/rustc/src/libcore/iter/traits/iterator.rs:1671:9
note: inside `test_all_refs::<i32, std::collections::btree_map::ValuesMut<i32, i32>>` at btree.rs:8:33
   --> btree.rs:8:33
    |
8   |     let mut refs: Vec<&mut T> = iter.collect();
    |                                 ^^^^^^^^^^^^^^
```

**Comment by RalfJung** [comment]
> No, I have no idea what the problem is and I see you write it's quite awful to debug so definitely have a look.

Btw, things got a bit better since then (and that is how I got the above backtrace): after seeing an error like
```
error: Undefined Behavior: trying to reborrow for SharedReadWrite, but parent tag <50139> does not have an appropriate item in the borrow stack
  --> btree.rs:11:26
   |
11 |         mem::swap(dummy, r);
   |                          ^ trying to reborrow for SharedReadWrite, but parent tag <50139> does not have an appropriate item in the borrow stack
   |
   = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
   = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```
*if* you are using Miri in deterministic mode (i.e., no enabling of external communication), then you can run Miri again with `-Zmiri-track-pointer-tag=50139` to learn when that tag got invalidated.

**Comment by RalfJung** [comment]
My guess is that `as_internal` needs to be made return a raw pointer just like `as_leaf`. It probably makes sense to do the same with `as_internal_mut`.

**Comment by ssomers** [comment]
Oh, that's really not hard at all to debug then. Even I can do that.

I'll work on as_internal. I struggled to make sense of the fact it already works with 12 to 18 elements, when there is also a descend into the 2nd child node with a reference to the root element around. But thanks to that old #58431, the descend happens right before extracting the reference from the kv handle. So the clash is postponed until we dive into the 3rd child node.

File: src/liballoc/collections/btree/node.rs (hunk 4 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: Definitely. I noticed that `get_unchecked` is used throughout to access an individual edge from the edges array, and `as_ptr` instead of `MaybeUninit::as_ptr`, so that's the pattern I copied this time, even though I dislike it (more so because they define `as_ptr` as a local method too).

**Comment by ssomers** [comment]
One step beyond `as_internal`, the next hurdle two lines lower baffles me again:
```
   --> /home/stein/rust/src/liballoc/collections/btree/node.rs:993:21
    |
993 |             height: self.node.height - 1,
    |                     ^^^^^^^^^^^^^^^^^^^^ popped tracked tag for item [Unique for <572285> (call 176070)]
```
This is not about the `self.node.node` of the handle, but merely a field in a `NodeRef` value, and both handles and `NodeRef`s are immutable values, so we can't ever have mutable references, right?

**Comment by RalfJung** [comment]
Is 572285 still the right pointer ID? Any time you change anything in the code, the problematic pointer ID will change, and you need to update your tracking command.

**Comment by ssomers** [comment]
Yes, it still reports the same in the UB later. I hadn't even noticed it's the same because I vary the test case with negative keys just to be sure it's reacting.

**Comment by ssomers** [comment]
Actually, there are mutable methods defined on `NodeRef`, such as `as_internal_mut` and `cast_unchecked`, but that's just for documentation. Those `mut` can be removed without changes in (Miri) test results.

**Comment by RalfJung** [comment]
Indeed I am seeing things being popped at the same line.

But that is not even in the same allocation as the values, to which the bad reference shows?
Maybe the actual problem is that the pointer never had permission to cover that locations in the first place, then we wouldn't see it be invalidated as it never was valid. That can happen when e.g. a `&mut T` to being cast to a raw pointer and then offset -- in general, when a pointer is used outside the memory range it was created for.

**Comment by RalfJung** [comment]
Ah no, the MIR scope is just wrong...
```
[INFO  rustc_mir::interpret::eval_context] LEAVING(24) alloc::collections::btree::node::NodeRef::<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker::Internal>::as_internal (unwinding = false)
[INFO  rustc_mir::interpret::eval_context] CONTINUING(23) alloc::collections::btree::node::Handle::<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut, i32, i32, alloc::collections::btree::node::marker:
:Internal>, alloc::collections::btree::node::marker::Edge>::descend (unwinding = false)
[INFO  rustc_mir::interpret::step] // executing bb1
[INFO  rustc_mir::interpret::step] StorageDead(_4)
[INFO  rustc_mir::interpret::step] _2 = &(*_3)
[INFO  rustc_mir::interpret::step] Retag(_2)
note: tracking was triggered
```
So actually this is reborrowing `internal_node`. That is still a safe reference which likely overlaps with the supposedly unique reference given out to the client -- which is no good.

**Comment by ssomers** [comment]
Oh boy, indeed I changed all the as_internal calls to explicit conversions to a reference, and already forgot that at least one of them had to stop doing that.

File: src/liballoc/collections/btree/navigate.rs [hunk 8]
```diff
@@ -161,15 +155,16 @@ impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Leaf>, marker::Edge
...
     /// - The caller must ensure that the leaf edge is not the last one in the tree
     ///   and is not a handle previously resulting from counterpart `next_back_unchecked`.
-    /// - If the leaf edge is the last edge of a node, that node and possibly ancestors
+    /// - Further use of the updated leaf edge handle is very dangerous. In particular,
+    ///   if the leaf edge is the last edge of a node, that node and possibly ancestors
     ///   will be deallocated, while the reference to those nodes in the surviving ancestor
-    ///   is left dangling; thus further use of the leaf edge handle is dangerous.
-    ///   It is, however, safe to call this method again on the updated handle.
-    ///   if the two preconditions above hold.
-    /// - Using the updated handle may well invalidate the returned references.
```
Comment (ssomers) [inline src/liballoc/collections/btree/navigate.rs:172]: This was unrelated copy-and-paste baloney. No references were returned.

**Comment by ssomers** [comment]
That as_internal was indeed the last hurdle. I tried reverting the order of navigation and `into_kv_mut` in #58431, and it works fine now. But then the performance is a little less, so I kept the implementation and changed the comments (in a separate commit).

No change in performance then:
```
benchcmp old new --threshold 5
 name                                           old ns/iter  new ns/iter  diff ns/iter   diff %  speedup
 btree::map::insert_rand_100                    41           36                     -5  -12.20%   x 1.14
 btree::map::insert_rand_10_000                 41           35                     -6  -14.63%   x 1.17
 btree::map::insert_seq_100                     50           45                     -5  -10.00%   x 1.11
 btree::map::iter_0                             1,263        1,760                 497   39.35%   x 0.72
 btree::map::range_included_included            404,113      455,713            51,600   12.77%   x 0.89
 btree::set::difference_staggered_100_vs_10k    2,309        2,527                 218    9.44%   x 0.91
 btree::set::intersection_staggered_100_vs_10k  2,171        2,343                 172    7.92%   x 0.93
 btree::set::is_subset_100_vs_10k               1,239        1,423                 184   14.85%   x 0.87
```

File: src/liballoc/collections/btree/navigate.rs (hunk 8 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:172]: The return type is `(&'a mut K, &'a mut V)` -- looks like returned references to me?

File: src/liballoc/collections/btree/node.rs [hunk 9]
```diff
@@ -554,7 +579,8 @@ impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::Internal> {
         unsafe {
             ptr::write(self.keys_mut().get_unchecked_mut(idx), key);
             ptr::write(self.vals_mut().get_unchecked_mut(idx), val);
-            self.as_internal_mut().edges.get_unchecked_mut(idx + 1).write(edge.node);
+            let internal_node = &mut *self.as_internal_mut();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:582]: Elsewhere you have a comment for why it is safe to create a reference to the entire node. Could you also add one here?

File: src/liballoc/collections/btree/node.rs [hunk 10]
```diff
@@ -585,9 +611,10 @@ impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::Internal> {
         unsafe {
             slice_insert(self.keys_mut(), 0, key);
             slice_insert(self.vals_mut(), 0, val);
+            let internal_node = &mut *self.as_internal_mut();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:614]: Elsewhere you have a comment for why it is safe to create a reference to the entire node. Could you also add one here?

File: src/liballoc/collections/btree/node.rs [hunk 11]
```diff
@@ -610,13 +637,13 @@ impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::LeafOrInternal> {
...
-            let key = ptr::read(self.keys().get_unchecked(idx));
-            let val = ptr::read(self.vals().get_unchecked(idx));
+            let key = ptr::read(self.key_at(idx));
+            let val = ptr::read(self.val_at(idx));
             let edge = match self.reborrow_mut().force() {
                 ForceResult::Leaf(_) => None,
                 ForceResult::Internal(internal) => {
-                    let edge =
-                        ptr::read(internal.as_internal().edges.get_unchecked(idx + 1).as_ptr());
+                    let internal_node = &*internal.as_internal();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:645]: Another reference-to-full-node.

File: src/liballoc/collections/btree/node.rs [hunk 12]
```diff
@@ -641,9 +668,10 @@ impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::LeafOrInternal> {
             let edge = match self.reborrow_mut().force() {
                 ForceResult::Leaf(_) => None,
                 ForceResult::Internal(mut internal) => {
+                    let internal_node = &mut *internal.as_internal_mut();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:671]: And another one.

File: src/liballoc/collections/btree/node.rs [hunk 13]
```diff
@@ -902,9 +930,10 @@ impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Internal>, marker::
             // This cast is a lie, but it allows us to reuse the key/value insertion logic.
             self.cast_unchecked::<marker::Leaf>().insert_fit(key, val);
 
+            let internal_node = &mut *self.node.as_internal_mut();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:933]: And another one (I am stopping here).

**Review by RalfJung — APPROVED** [review]
LGTM aside from a few comment nits.

However, I don't know the BTree enough to verify the libs side of this.

File: src/liballoc/collections/btree/navigate.rs (hunk 8 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:172]: It's not, it's `(K, V)`?? I would think you were right because I edited this a lot about this at the time, but then again, looking at the period behind "handle", even AI would have at least gotten the grammar right.

File: src/liballoc/collections/btree/node.rs (hunk 9 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:582]: I repeated: "SAFETY: we can access the entire node freely and do no need raw pointers, because we have exclusive access." But it really means: "we assume we have exclusive access, and once Miri rats us out, we'll drop that assumption".

More interesting is the one place (in `descend`) where we do need to use raw pointers: "SAFETY: we need to use raw pointers to and inside the node because we may be invoked during iteration, while the caller clings on to outstanding mutable reference to values."

File: src/liballoc/collections/btree/navigate.rs (hunk 8 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:172]: Ah right, it is `(K, V)` here. But it is a pair of references in some other place where you removed that comment.

File: src/liballoc/collections/btree/navigate.rs [hunk 14]
```diff
@@ -123,36 +123,30 @@ impl<'a, K, V> Handle<NodeRef<marker::Immut<'a>, K, V, marker::Leaf>, marker::Ed
...
+            // Doing this last is faster, according to benchmarks.
             kv.into_kv_mut()
         }
     }
 
     /// Moves the leaf edge handle to the previous leaf and returns references to the
     /// key and value in between.
-    /// Unsafe for two reasons:
-    /// - The caller must ensure that the leaf edge is not the first one in the tree.
-    /// - Using the updated handle may well invalidate the returned references.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/navigate.rs:146]: This does return references, so should the comment stay or is there some other reason for it to be wrong?

File: src/liballoc/collections/btree/navigate.rs [hunk 15]
```diff
@@ -123,36 +123,30 @@ impl<'a, K, V> Handle<NodeRef<marker::Immut<'a>, K, V, marker::Leaf>, marker::Ed
 impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Leaf>, marker::Edge> {
     /// Moves the leaf edge handle to the next leaf edge and returns references to the
     /// key and value in between.
-    /// Unsafe for two reasons:
-    /// - The caller must ensure that the leaf edge is not the last one in the tree.
-    /// - Using the updated handle may well invalidate the returned references.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/navigate.rs:128]: This does return references, so should the comment stay or is there some other reason for it to be wrong?

**Comment by RalfJung** [comment]
> I was expecting the call for safety comments in the back of my mind. 1 minute into it I know why I kept it there. What is the rule that brought us here? Who says that the caller of `iter_mut` can continue to use a previously returned reference, after calling `next` again? Probably you say: there's no rule that forbids it, so it's allowed and people do it. Well then, what rule says that the caller cannot continue to use those references after dropping the iterator? After all, [it works fine](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=374aaad644d66c3bee765abcd9e69d50) until Miri sticks its nose in.

I have no idea what you are respond to in this post. What is "it"? Which rule?

File: src/liballoc/collections/btree/node.rs (hunk 9 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:582]: > But it really means: "we assume we have exclusive access, and once Miri rats us out, we'll drop that assumption".

:joy: 

Is there some more solid argument we have? Like, there cannot possible be references into this code that have been handed out to users because this is `push` which requires exclusive access to the entire tree (cannot happen during iteration)?

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:146]: Well, this PR implies it is no longer a problem? The references stay valid while using the handle (and, I assume, until dropping it).

Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:146]: What does "using the updated handle" even mean? Use for what? Calling `next` again certainly must work, indeed. But are there other uses, ones that to not work, such as `push` or so?

**Comment by ssomers** [comment]
> What is "it"?

The act of writing the comments, in particular the one in `descend`.

> Which rule?

That's what I'm asking. I don't seen anything in the documentation about how long I can use a reference returned by `next()`. While Rust is usually very fussy about lifetimes. The lifetime identifier (or what's it called) for `iter_mut` and `values_mut` is just `'_'. So am I not allowed to use these for the lifetime of the map itself? I know this would be insane, but then why don't we assume that the actual lifetime is limited to the next call of `next()`? And that the default min/max algorithms are wrong in violating that precondition?

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:146]: I don't know. I think it's possible that all of the public and even private methods in the auxiliary modules would operate fine given updated handles and respect the invariants of node.rs (but, as always they, would very likely violate the much stricter invariants of map.rs). But they are extremely likely to trample on the previously returned references.

So I guess it should be a postcondition on the caller: only use the updated handle for next or next_back? But I feel like a lot of the auxiliary functions could be describing how they're supposed to be used, and that description will always turn out to be wrong later.

File: src/liballoc/collections/btree/node.rs (hunk 9 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:582]: We could put that/another comment in the documentation of those functions, saying that they take their `&mut self` seriously - exclusive access all the way. But it's really the other way around. `descend(self)`, and some methods using it, should not pretend to have exclusive access. They should not be `self` or `&mut self`.

Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:582]: That's probably nonsense. It can own a handle, the problem is with the tree it refers to. What I'm getting at is probably that there should be an alternative to `marker::Mut`, some `marker::MutNotReallyExclusive` used for iterators.

Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:582]: I think this is vastly superior. It allows rolling back many changes here, because `as_internal_mut` (i.e. the possibility to change edges) is in the exclusive access world, far away from the mutable iterator world. Hold on while I decorate the next dish.

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:146]: This "postcondition" instead becomes statically type information in the upcoming commit.

**Comment by RalfJung** [comment]
> >   What is "it"?
>
> The act of writing the comments, in particular the one in descend.

Sorry, I meant to ask for the "it" that you "kept".

> That's what I'm asking. I don't seen anything in the documentation about how long I can use a reference returned by next(). While Rust is usually very fussy about lifetimes. The lifetime identifier (or what's it called) for iter_mut and values_mut is just '_. So am I not allowed to use these for the lifetime of the map itself?

`'_` just means we use lifetime elision. In this case it means the lifetime is the same as that of the `self` reference. So the full type is
```rust
pub fn iter_mut<'a>(&'a mut self) -> IterMut<'a, K, V>
```

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:146]: I think all I am saying is, it seems better to keep this comment for functions that actually return (pairs of) references.

File: src/liballoc/collections/btree/node.rs [hunk 16]
```diff
@@ -240,9 +247,12 @@ impl<K, V> Root<K, V> {
 /// A reference to a node.
 ///
 /// This type has a number of parameters that controls how it acts:
-/// - `BorrowType`: This can be `Immut<'a>` or `Mut<'a>` for some `'a` or `Owned`.
+/// - `BorrowType`: This can be `Immut<'a>`, `Mut<'a>` or `ValMut<'a>' for some `'a`
+///    or `Owned`.
 ///    When this is `Immut<'a>`, the `NodeRef` acts roughly like `&'a Node`,
 ///    when this is `Mut<'a>`, the `NodeRef` acts roughly like `&'a mut Node`,
+///    when this is `ValMut<'a>`, the `NodeRef` acts as immutable with respect
+///    to keys and tree structure, but allows mutable references to values,
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:255]: Ah yes, that sounds like a very useful distinction to have indeed. :)

File: src/liballoc/collections/btree/map.rs [hunk 17]
```diff
@@ -2829,8 +2829,8 @@ enum UnderflowResult<'a, K, V> {
     Stole(bool),
 }
 
-fn handle_underfull_node<K, V>(
-    node: NodeRef<marker::Mut<'_>, K, V, marker::LeafOrInternal>,
+fn handle_underfull_node<'a, K: 'a, V: 'a>(
+    node: NodeRef<marker::Mut<'a>, K, V, marker::LeafOrInternal>,
```
Comment (RalfJung) [inline src/liballoc/collections/btree/map.rs:2833]: What is this change about?

File: src/liballoc/collections/btree/navigate.rs [hunk 18]
```diff
@@ -120,56 +120,61 @@ impl<'a, K, V> Handle<NodeRef<marker::Immut<'a>, K, V, marker::Leaf>, marker::Ed
...
+            // Doing this last is faster, according to benchmarks.
+            kv.into_kv_valmut()
         }
     }
 }
 
+impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Leaf>, marker::Edge> {
+    /// Moves the leaf edge handle to the next leaf edge.
+    /// Unsafe because the caller must ensure that the leaf edge is not the last one in the tree.
+    pub unsafe fn next_unchecked(&mut self) {
```
Comment (RalfJung) [inline src/liballoc/collections/btree/navigate.rs:158]: Hm, seems odd to have a `next` function that does not return anything?

File: src/liballoc/collections/btree/node.rs [hunk 19]
```diff
@@ -489,32 +527,42 @@ impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
-                MaybeUninit::first_ptr_mut(&mut (*self.as_leaf_mut()).vals),
+                MaybeUninit::first_ptr_mut(&mut self.as_leaf_mut().vals),
                 self.len(),
             )
         }
     }
 
-    fn into_slices_mut(mut self) -> (&'a mut [K], &'a mut [V]) {
-        // We cannot use the getters here, because calling the second one
-        // invalidates the reference returned by the first.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:500]: Might still be worth explaining why we do not call `into_key_mut_at` and then `into_val_mut_at`. That was the old implementation and I fear someone will revert it back to that if there is no comment explaining this.

File: src/liballoc/collections/btree/node.rs [hunk 20]
```diff
@@ -489,32 +527,42 @@ impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
+        let key0 = keys as *const K;
+        let val0 = vals as *mut V;
+        let key = unsafe { key0.add(idx) };
+        let val = unsafe { val0.add(idx) };
+        unsafe { (&*key, &mut *val) }
+    }
+}
+
+impl<'a, K: 'a, V: 'a> NodeRef<marker::Mut<'a>, K, V, marker::Leaf> {
     /// Adds a key/value pair the end of the node.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:566]: "to/at the end"? (while you are at it)

File: src/liballoc/collections/btree/node.rs [hunk 21]
```diff
@@ -432,9 +459,9 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
     /// If the node is an internal node, so not a leaf, it does have all the data a leaf has
     /// (header, keys and values), and this function exposes that.
     ///
-    /// Returns a raw ptr to avoid asserting exclusive access to the entire node.
-    fn as_leaf_mut(&mut self) -> *mut LeafNode<K, V> {
-        self.node.as_ptr()
+    /// We don't need to return a raw ptr because we have exclusive access to the entire node.
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:462]: This is bold, I would not have dared.^^ But if Miri doesn't complain I guess it is okay.

File: src/liballoc/collections/btree/map.rs (hunk 17 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/map.rs:2833]: You did similar things elsewhere. I assume this is important; could you add a comment explaining why?

**Comment by ssomers** [comment]
> Sorry, I meant to ask for the "it" that you "kept".

That was the same "it". I meant I kept the act of writing safety comments in the back of my mind, i.e. I postponed it.

> '_ just means we use lifetime elision

Sorry, I was looking at the wrong place. It's the lifetime of the result of `IterMut::next`I'm trying to talk about. ` Option<(&'a K, &'a mut V)>`, is as far as I understand and [the example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=374aaad644d66c3bee765abcd9e69d50) shows, that lifetime is the same: the lifetime of the map, not just the lifetime of the iterator. That's obviously a lie. We ran into #73915 thinking the actual intended lifetime of returned references is that of the iterator, but who says (in the documentation) it's not shorter than that?

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:146]: I don't understand why. I claim "Using the updated handle may well invalidate the returned references." is no longer possible, unless you invoke unsafe methods violating their preconditions, or worse unsafety. Unless you mean, "dropping the updated handle, will invalidate the returned references".

**Comment by RalfJung** [comment]
> It's the lifetime of the result of IterMut::nextI'm trying to talk about. The lifetime of Option<(&'a K, &'a mut V)>, is as far as I understand and the example shows, the same as the lifetime of the map, not just the lifetime of the iterator. 

Yes, that is expected. it is the lifetime of *the borrow of the map* that was used to create the iterator. This is how all mutable-reference iterators work. It means you can have mutable iterators to different elements in the collection at the same time, as your example shows.

This is not surprising, and I do not understand why you see a problem here. `BTreeMap` has some bugs in how it implements that iterator, that is all.

File: src/liballoc/collections/btree/map.rs (hunk 17 above)
Comment (ssomers) [reply src/liballoc/collections/btree/map.rs:2833]: I did it because the compiler told me to, when I turned raw pointer use into reference use, and then it trickled down throughout the code, next to places where the pattern existed already. I can't really comment because I still don't understand whether it means that keys and values have to live longer than `a, or the other way around, and even what either of those mean. I should understand, but there's a lot I should.

File: src/liballoc/collections/btree/navigate.rs (hunk 14 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:146]: I wrote that comment before seeing the `ValMut` matches. If the API now prevents the bad mutations, that's even better. :)

File: src/liballoc/collections/btree/map.rs (hunk 17 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/map.rs:2833]: > I did it because the compiler told me to, when I turned raw pointer use into reference use, and then it trickled down throughout the code, next to places where the pattern existed already.

Okay, fair.

> I can't really comment because I still don't understand whether it means that keys and values have to live longer than `a, or the other way around, and even what either of those mean. I should understand, but there's a lot I should.

It means that the types `K` and `V` must not contain any borrows that are shorter than `'a`. IOW, keys and values have to live longer than ("outlive") `'a`. But this is indeed a tricky notion to deal with -- what I explained only talks about the syntactic types; it is very hard to turn this into a statement about the values described by those types.

File: src/liballoc/collections/btree/navigate.rs (hunk 18 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:158]: Absolutely, that one is getting renamed. If I don't find anything similar in the libraries "advance_unchecked"? I hate that the other `next_unchecked` functions have the same name as in the map iterators, but that's what the reviewer at the time wanted. Elsewhere too Rusticians seem to love overloading names with subtly different meanings (like "node" in node.rs) and I shouldn't become complacent.

File: src/liballoc/collections/btree/node.rs (hunk 19 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:500]: Indeed, I began thinking all aliasing was resolved in the `Mut` case but it isn't.

File: src/liballoc/collections/btree/map.rs (hunk 17 above)
Comment (ssomers) [reply src/liballoc/collections/btree/map.rs:2833]: OK, that helps. Are the places (still) not listing those bounds being sloppy, because they circumvent the borrow checker but they really assume the same, or just nice and terse?

File: src/liballoc/collections/btree/node.rs (hunk 21 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:462]: Well, I believe it was Mark who reminded me in some review that `marker::Mut` stuff was supposed to have exclusive references. But now I realize it's a contradictory "Surely I have exclusive access. Here's a second reference; surely you know that you definitely can't call anyone else as arrogant as me".

**Comment by ssomers** [comment]
> you can have mutable iterators to different elements in the collection at the same time, as your example shows.

Yes that too, but the point of the example is that Rust does not care that you use those references after the iterator has died. [More explicitly in this variation of the example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cc9bd612ede6531ddbd4f3633c8ad89).

File: src/liballoc/collections/btree/map.rs (hunk 17 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/map.rs:2833]: These are certainly extra assumptions, otherwise you would not get errors when removing them.

I suspect they are meant to inform the borrow checker about requirements of the unsafe code, thus using the borrow checker to help avoid bugs here -- similar to the Imm/Mut distinction for handles.

File: src/liballoc/collections/btree/node.rs (hunk 21 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:462]: This method consumes the handle though, right? So the returned reference is still unique?

**Comment by RalfJung** [comment]
By "died" you mean "has been dropped"? That's fine (and expected, but admittedly subtle); the key is that this is all still confined by the lifetime of the borrow that was passed to `iter_mut`.

**Comment by RalfJung** [comment]
In other words, the key is that [this still gets rejected](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=45f9b061d3aa3a259a82c106ea02a498).

File: src/liballoc/collections/btree/node.rs (hunk 21 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:462]: Err whaat? `fn as_leaf_mut(&mut self)` consumes?

You mean that it should consume? It does seem like a lot of places could do that. Or they just need to adjust node length without accessing the whole leaf.

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:462]: Sorry, it doesn't consume, but it reborrows. As in the lifetime of the returned reference equals the lifetime of the argument reference, much like e.g. `Cell::get_mut`.

**Comment by ssomers** [comment]
Ooh, I finally got your point now. Too much C++ and RAII has fried my brain.

So [my example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cc9bd612ede6531ddbd4f3633c8ad89) is supposed to work, and the reason Miri complains is another manifestation of #74029, right?

**Comment by RalfJung** [comment]
Miri complains with that example, even though it passes in `test_all_refs`? That is truly odd, because `test_all_refs` also drops the iterator before using all the refs (`collect` consumes the iterator).

**Comment by ssomers** [comment]
> (I did not realize that you meant to say that Miri errors with that example.)

Yeah, sorry, I did not make that clear. I was convinced it couldn't be legal code anyway.

**Comment by RalfJung** [comment]
> Ooh, I finally got your point now. Too much C++ and RAII has fried my brain.

`&mut` iterators are arguably one of the most amazing and most tricky safe ways to use the Rust lifetime system. :)

File: src/liballoc/collections/btree/node.rs (hunk 21 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:462]: Right, and that's what is explicitly explained in `keys_mut` and `vals_mut`. Also, I guess "unique access" is more Rusticious than the "exclusive access" I put in comments.

File: src/liballoc/collections/btree/node.rs (hunk 19 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:500]: I was starting to doubt this point. I don't mean because `into_key_mut_at` and `into_val_mut_at`don't exist. One can argue they should exist, because each of the invocations of `into_kv_mut`in map.rs wants only the key or value, and I don't believe that this is all optimized away to a single array access. So I added them for performance alone.

I do mean because the borrowing rules I'm beginning to understand again, already guarantee that you can't invoke both. It says "cannot move out of `self` because it is borrowed" to this:

```
        let key = unsafe { self.reborrow_mut().into_key_mut_at(idx) };
        let val = unsafe { self.into_val_mut_at(idx) };
```

The slices were references too, so why didn't the borrow checker complain much earlier? I think it was because the old code didn't try to reborrow but bluntly copied the pointers:

```
   fn into_slices_mut(self) -> (&'a mut [K], &'a mut [V]) {
        let k = unsafe { ptr::read(&self) };
        (k.into_key_slice_mut(), self.into_val_slice_mut())
    }
```

Not that this is a reason to omit the comment, but rather to elaborate it.

**Comment by ssomers** [comment]
Since returned pointers fool the borrow checker, wouldn't it be better to let the methods that return raw pointers, i.e. `as_leaf` and `as_internal`, consume their `self`? Then callers are forced to explicitly reborrow, if there can be aliasing. I suppose it doesn't really matter for these const pointers, but I suspect `into_kv_pointers_mut` was declared as such for that reason.

File: src/liballoc/collections/btree/node.rs [hunk 22]
```diff
@@ -593,37 +660,42 @@ impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::Internal> {
...
             let edge = match self.reborrow_mut().force() {
                 ForceResult::Leaf(_) => None,
-                ForceResult::Internal(internal) => {
-                    let edge =
-                        ptr::read(internal.as_internal().edges.get_unchecked(idx + 1).as_ptr());
+                ForceResult::Internal(mut internal) => {
+                    // We do not need mutable access to the edges, but it's safer
+                    // to express that we have unique access. We are taking ownership
+                    // of an edge and will change length.
+                    let internal_node = internal.as_internal_mut();
```
Comment (ssomers) [inline src/liballoc/collections/btree/node.rs:690]: This now feels better than getting away with immutable access.

File: src/liballoc/collections/btree/node.rs [hunk 23]
```diff
@@ -1145,13 +1220,18 @@ impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Internal>, marker::
...
             let layout = if self.node.height > 1 {
+                // SAFETY: the height of the nodes being merged is one below the height
+                // of the node of this edge, thus above zero, and we can cast_unchecked
+                // both nodes to Internal.
+                // We do not need mutable access to the doomed right node, but it's safer
+                // to express that we have unique access.
                 ptr::copy_nonoverlapping(
-                    right_node.cast_unchecked().as_internal().edges.as_ptr(),
+                    right_node.cast_unchecked().as_internal_mut().edges.as_ptr(),
                     left_node
```
Comment (ssomers) [inline src/liballoc/collections/btree/node.rs:1235]: Same here

File: src/liballoc/collections/btree/node.rs [hunk 24]
```diff
@@ -453,18 +481,29 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
+        debug_assert!(idx < self.len());
+        // SAFETY: we can access the entire node freely and do no need raw pointers,
+        // because there can be no mutable references to this immutable tree.
+        let leaf = unsafe { &(*self.as_leaf()) };
+        unsafe { leaf.vals.get_unchecked(idx).get_ref() }
+    }
+
+    /// SAFETY: the caller must ensure that the node has more than `idx` initialized elements.
+    unsafe fn into_key_val_at(self, idx: usize) -> (&'a K, &'a V) {
         // SAFETY: equivalent to reborrow() except not requiring Type: 'a
```
Comment (ssomers) [inline src/liballoc/collections/btree/node.rs:504]: I finally understand the meaning of this (Mark's) comment. Not yet why rustc starts requires the `'a` all over the place. But I wonder if it isn't more clear to make `Type: 'static` everywhere regardless? It doesn't look great but it makes it more clear that this is not a genuine type but an enumeration in the narrowest sense of the word.

File: src/liballoc/collections/btree/node.rs (hunk 19 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:500]: > I think it was because the old code didn't try to reborrow but bluntly copied the pointers:

Indeed, it just duplicated `self` to be able to call these two methods.

**Comment by RalfJung** [comment]
> Since returned pointers fool the borrow checker, wouldn't it be better to let the methods that return raw pointers, i.e. as_leaf and as_internal, consume their self? Then callers are forced to explicitly reborrow, if there can be aliasing. I suppose it doesn't really matter for these const pointers, but I suspect into_kv_pointers_mut was declared as such for that reason.

That sounds plausible. I don't know these APIs well enough to judge how they are used. I didn't even know about the method to explicitly reborrow.

File: src/liballoc/collections/btree/node.rs (hunk 24 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:504]: Why would `'static` be reasonable? Keys and values can contain references.

**Comment by RalfJung** [comment]
I feel like I also lost track of the big picture here. This PR started wanting to fix some incorrect aliasing, and turned into a huge refactoring of the internal BTree API -- well beyond what I can review with my limited BTree knowledge. Where is this going, and when will you be ready and want it reviewed?

File: src/liballoc/collections/btree/node.rs (hunk 24 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:504]: I mean only for `Type` or in handle `NodeType`. Maybe also for `BorrowType`, but for some reason the borrow checker never ever complains about those.

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:504]: I have no idea what these are.^^ Better ask Mark about that.

**Comment by ssomers** [comment]
What can I say? I'm inspired by your review comments.

Shall I roll this back to the point where you approved and where everything worked, and do the `ValMut` and other refactoring in a separate PR? Or some other point since after that.

**Comment by RalfJung** [comment]
I'd anyway be more comfortable if someone else reviewed the BTree changes. So I'll wait until you are happy with this PR (I am not sure if you plan to do further changes currently, since long after this was marked as "ready for review" there were still plenty of changes), then I'll check the aliasing things I can check and hand over review to someone else (hopefully Mark can do it).

**Comment by ssomers** [comment]
I've been happy with this PR for a few days, and getting happier. The only concrete idea I have left that affects this PR is the fact that it makes `as_leaf` and `as_internal` return a raw pointer and I think that reduces the help from the borrow checker and I think making the methods consume `self` would make things safer. But I'm not at all sure that is true and even less that it matters, and I am sure it makes the current code harder to read for the layman. So not a change I plan, just a question/suggestion.

I am trying out some wilder ideas, but that's definitely not for this PR.

File: src/liballoc/collections/btree/navigate.rs [hunk 25]
```diff
@@ -120,56 +120,61 @@ impl<'a, K, V> Handle<NodeRef<marker::Immut<'a>, K, V, marker::Leaf>, marker::Ed
...
     }
 }
 
+impl<'a, K, V> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Leaf>, marker::Edge> {
+    /// Moves the leaf edge handle to the next leaf edge.
+    /// Unsafe because the caller must ensure that the leaf edge is not the last one in the tree.
+    pub unsafe fn move_next_unchecked(&mut self) {
+        let kv = unsafe { ptr::read(self).next_kv() };
+        let kv = unsafe { unwrap_unchecked(kv.ok()) };
+        *self = kv.next_leaf_edge();
```
Comment (RalfJung) [inline src/liballoc/collections/btree/navigate.rs:161]: This looks like the `take_mut` pattern. That pattern is safe only if the code can never panic between the `ptr::read` and the `*self`. Could you ad a comment saying that, and also make sure that indeed `next_kv`, `unwrap_unchecked` and `next_leaf_edge` never panic?

Also maybe use `ptr::write` instead of `*self` -- it's more symmetric and means I don't have to check that this does not have a destructor.

File: src/liballoc/collections/btree/node.rs [hunk 26]
```diff
@@ -489,33 +528,63 @@ impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
+        // to avoid aliasing with outstanding references to other elements,
+        // in particular, those returned to the caller in earlier iterations.
+        let leaf = self.node.as_ptr();
+        let keys = unsafe { &raw const (*leaf).keys };
+        let vals = unsafe { &raw mut (*leaf).vals };
+        let key0 = keys as *const K;
+        let val0 = vals as *mut V;
+        let key = unsafe { key0.add(idx) };
+        let val = unsafe { val0.add(idx) };
+        unsafe { (&*key, &mut *val) }
```
Comment (RalfJung) [inline src/liballoc/collections/btree/node.rs:582]: Now that https://github.com/rust-lang/rust/pull/73986 landed you can use those methods, which should make this code a lot simpler. :)
(Be sure to avoid https://github.com/rust-lang/rust/issues/73987 though.)

**Comment by RalfJung** [comment]
This LGTM from an aliasing perspective (the reason we even started this), and on a high level the `ValMut` distinction sounds like something we definitely need. But I do not know this code well enough in detail to review all the low-level changes here.

r? @Mark-Simulacrum for that.

File: src/liballoc/collections/btree/node.rs (hunk 24 above)
Comment (Mark-Simulacrum) [reply src/liballoc/collections/btree/node.rs:504]: I don't know why we don't bind Type with 'static, doing so if needed indeed seems like not a problem to me.

**Review by Mark-Simulacrum — COMMENTED** [review]
Generally looks good -- I think this didn't really contain any changes other than aliasing work?

There seemed to be one outstanding comments from prior review by @RalfJung though -- https://github.com/rust-lang/rust/pull/73971/commits/f0a2e787b27953addd270a9cdac0eedf905cb786#r454911837 -- amidst some others about potential cleanups.

**Comment by RalfJung** [comment]
That link doesn't go anywhere for me...

**Comment by ssomers** [comment]
> There seemed to be one outstanding comments from prior review

Not sure what you refer to: your link leads to nowhere for me (just like those View changes buttons most of the time). I found 2 unresolved conversations, that were addressed and that I closed now.

> I think this didn't really contain any changes other than aliasing work?

For a wide interpretation of aliasing, I think. I see 3 other topics:
- The `marker::ValMut` stuff doesn't help with the known aliasing problem, it just prevents others.
- Splitting `into_kv_mut` is really stretching it, it was just born to allow restoring the comment that there would be aliasing if you were to use them.
- Nearby but unrelated comments, but I already copied those along with more in #74295.

I don't mind making 2 separate PRs for the other two. But beware, I have 2 other btree PRs ready to launch as well...

File: src/liballoc/collections/btree/node.rs [hunk 27]
```diff
@@ -959,11 +1031,12 @@ impl<BorrowType, K, V> Handle<NodeRef<BorrowType, K, V, marker::Internal>, marke
...
     pub fn descend(self) -> NodeRef<BorrowType, K, V, marker::LeafOrInternal> {
+        // We need to use raw pointers to nodes because, if BorrowType is marker::ValMut,
+        // there might be outstanding mutable references to values that we must not invalidate.
+        let internal_node = self.node.as_internal();
         NodeRef {
             height: self.node.height - 1,
-            node: unsafe {
-                (&*self.node.as_internal().edges.get_unchecked(self.idx).as_ptr()).as_ptr()
-            },
+            node: unsafe { (&*(*internal_node).edges.get_unchecked(self.idx).as_ptr()).as_ptr() },
```
Comment (ssomers) [inline src/liballoc/collections/btree/node.rs:1039]: This `&*` of the pointer contained by MaybeUninit is something inspiring my comment in #73987 - as far as I understand, it causes the `BoxedNode` coming out to a stand-up citizen. I have no idea what for. I have previously read a post/article about the purpose of `&*` but can't find it back.

**Comment by Mark-Simulacrum** [comment]
I meant this comment: 
image

Yeah, I call all of that "aliasing work" or "close enough" :)

**Comment by ssomers** [comment]
That's one of the two recent refinements I'm working on, putting this PR on draft again.

File: src/liballoc/collections/btree/node.rs (hunk 27 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:1039]: The `&*` here applies to `(*internal_node).edges.get_unchecked(self.idx).as_ptr()`. So really this is just
```rust
(*internal_node).edges.get_unchecked(self.idx).as_ptr() as &_
```
except you cannot cast to a shard reference.

https://github.com/rust-lang/rust/issues/73987 is about the fact that your code really is short for
```rust
...::get_unchecked((*internal_node).edges as &_, self.idx).as_ptr() as &_
```
(again using my pseudo-casts). It is the first, inner "cast" I am worried about, not the second one.

File: src/liballoc/collections/btree/node.rs (hunk 26 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:582]: Hm, except that these are arrays of `MaybeUninit`, right? So we need another method to go from `*const/mut MaybeUninit<T>` to `*const/mut T`...

File: src/liballoc/collections/btree/node.rs (hunk 27 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:1039]: I didn't even think about the edge access brining up this line. You're saying that during `iter_mut`, a descend will still stake its claim on the entire edge array? But since we don't hand out references to edges, that's not actually a problem. Probably. Yet. It did inspire me for [another playground example of UB with a more subtle way of clinging on to references](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8319fe76c5ae23469f3f50564b4ef0ce), but that no longer fails with this PR.

Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:1039]: I think I understand the `&*` (that existed in the old code) now: it's mainly `*`, illustrating that a auto-ref is done for the call to `BoxedNode::as_ptr(&self)`, and if you try to figure this out with intermediate variable and types the wrong way, you can end up with a basically superfluous. `&*`.

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs:1039]: > You're saying that during iter_mut, a descend will still stake its claim on the entire edge array?

Yes. And yes that seems fine as the structure of the tree does not change (hence why `ValMut` is so important), but it is worth a comment.

> It did inspire me for another playground example of UB with a more subtle way of clinging on to references, but that no longer fails with this PR.

You are getting good at coming up with these examples. ;) Another one for the test suite!

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:161]: The `replace` function higher up, that a birdy whispered into my ear (I think it was Mark), seems to be an extended `take_mut` pattern. Originally in this `move_next_unchecked`, I reused `replace` with a void result, but that looked more complicated to me than writing it out with ptr::read/write. Now I put  in a `take` function very much like `take_mut::take`. But it has one disadvantage: the closure passed in doesn't and can't distinguish between safe code (like the `next_leaf_edge` above) and unsafe code (like `unwrap_unchecked`), because everything is already in an unsafe block.

But unlike `replace`, [`take_mut::take`](https://docs.rs/take_mut/0.2.2/take_mut/fn.take.html) is not marked unsafe. Some code shared in [RFC 1736](https://github.com/rust-lang/rfcs/pull/1736) is not marked unsafe either, and I seem to pick up that aborting the program because a closure panics is not undefined behaviour. I'm not even sure Mark or I slapped it on, so I'll be removing the unsafe unless you guys object.

Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:161]: The old code needed `unsafe` because it did *not* abort.

Adding a safe `take` has been requested a few times I think, but there was never enough of a push for it. Actually having a user in libstd might change the game. ;)

Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs:161]: Relevant links: https://github.com/rust-lang/rfcs/issues/1508, https://github.com/rust-lang/rfcs/pull/1736.

File: src/liballoc/collections/btree/navigate.rs [hunk 28]
```diff
@@ -83,7 +86,16 @@ def_next_kv_uncheched_dealloc! {unsafe fn next_back_kv_unchecked_dealloc: left_k
 ///
 /// Safety: The change closure must not panic.
 #[inline]
-unsafe fn replace<T, R>(v: &mut T, change: impl FnOnce(T) -> (T, R)) -> R {
+fn take_mut<T>(v: &mut T, change: impl FnOnce(T) -> T) {
```
Comment (RalfJung) [inline src/liballoc/collections/btree/navigate.rs:89]: Argh GitHub's annoying UI swallowed my comments as I attached them to the commit instead of the PR or so...

This and the next function should be `unsafe`, as they are clearly not safe to use -- they have a safety contract the caller needs to uphold.

File: src/liballoc/collections/btree/node.rs (hunk 27 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:1053]: Comment added (not pushed yet) and an example of easier UB than my first example added. I haven't investigated why simply moving a second (reverse) iterator invalidates key/value references in stable/nightly, but I guess it's reading the length of a node just to create a handle.

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: > The old code needed `unsafe` because it did _not_ abort.

Now I understand with "the old code" you mean the code in the current code, that is old. That is not currently the current code, because I removed the unsafe, but I'll put it back.

Regardless of whether it's unsafe or aborting, it is weird that Rust does not have something resembling `noexcept`. Unless this `take_mut` pattern is actually a bad idea. But I'm not going to try to touch it in btree right now.

Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs]: Ah yes I meant master, i.e., before your PR.

> Regardless of whether it's unsafe or aborting, it is weird that Rust does not have something resembling noexcept. Unless this take_mut pattern is actually a bad idea. But I'm not going to try to touch it in btree right now.

`noexcept` means we'd need an effect system -- because Rust is higher-order, adding a simple attribute is not enough, you have to be able to mark `fn` ptrs and methods in `trait` implementations as `noexcept`. It's a huge amount of compelxity for a niche usecase such as `take_mut`.

Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: Though I did manage to put detailed unsafe blocks in the closures passed to `replace`, by simply moving them out as a local variable.

File: src/liballoc/collections/btree/navigate.rs (hunk 28 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs:89]: Rest assured I got the previous one too, and it lingers in my notifications, but I have no idea how to find it if an innocent bystander visits the issue.

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: > Ah yes I meant master, i.e., before your PR.

Well, yes, but I didn't change that code, I just added and inlined one call of `replace`. So now I interpret your "The old code needed unsafe because it did not abort." as "The old code, that's still in there, needed and needs unsafe because it did not and does not abort".

Meanwhile I did "change that code" by removing the unsafe, but right now that's reverted.

**Comment by ssomers** [comment]
For those trying to make sense of progress: I think I addressed all remarks, and have not given Ralf enough time to come up with more, except the one about using #73986 but at least I understand #73987.

Meanwhile, something else that initially seemed daunting and unrelated, now seems obvious and very much related to me: #74437. I think the combination of that and this PR means that @gereeter's comment in `reborrow_mut` "consider adding yet another type parameter to `NodeRef` that restricts the use of `ascend` and `into_root_mut` on reborrowed pointers, preventing this unsafety." is implemented by marker::ValMut, except that `ascend` is required and needed to clean its act, and the methods modifying the tree structure were the ones that need restrictions.

File: src/liballoc/collections/btree/node.rs (hunk 26 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: I got it in but it doesn't make sense. For instance, before adding type annotation `*mut [_]` onto vals, rustc says "no method named `get_unchecked_mut` found for raw pointer `*mut [core::mem::MaybeUninit<V>; _]` in the current scope". That is the type I expected from a &raw mut. Tell it to be the type it already is, and suddenly rustc says all is well. Am I crazy or is rustc?

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: That sounds odd; do you have a small example demonstrating the problem?

Methods with raw pointer `self` are still fairly new; it is very possible that they have some strange quirks/bugs.

Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: That was surprisingly [easy to reproduce](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fcb75084044ed819f79b19b21d30fecb): omit the type annotation, game over.

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: > also make sure that indeed [...], `unwrap_unchecked` and [...] never panic?

So I added an `unwrap_unchecked_unpanicky` that never does. The old `unwrap_unchecked` seems meant not to prevent panic but to optimize it away in a release build. One would indeed think the code to panic wastes resources, but I've always wondered how many pennies we save this way. Time to measure!

```
benchcmp old plain_unwrap_1 --threshold 5
 name                                           old ns/iter  plain_unwrap_1 ns/iter  diff ns/iter   diff %  speedup
 btree::map::insert_rand_10_000                 33           35                                 2    6.06%   x 0.94
 btree::map::iteration_1000                     4,027        1,133                         -2,894  -71.86%   x 3.55
 btree::map::iteration_100000                   498,075      294,756                     -203,319  -40.82%   x 1.69
 btree::map::iteration_20                       80           21                               -59  -73.75%   x 3.81
 btree::map::iteration_mut_1000                 3,898        1,019                         -2,879  -73.86%   x 3.83
 btree::map::iteration_mut_100000               476,445      275,236                     -201,209  -42.23%   x 1.73
 btree::map::iteration_mut_20                   78           21                               -57  -73.08%   x 3.71
 btree::set::difference_random_100_vs_100       745          686                              -59   -7.92%   x 1.09
 btree::set::difference_random_10k_vs_10k       186,910      163,967                      -22,943  -12.27%   x 1.14
 btree::set::difference_staggered_100_vs_100    765          693                              -72   -9.41%   x 1.10
 btree::set::difference_staggered_10k_vs_10k    73,799       64,744                        -9,055  -12.27%   x 1.14
 btree::set::intersection_random_100_vs_100     643          347                             -296  -46.03%   x 1.85
 btree::set::intersection_random_10k_vs_10k     163,212      120,081                      -43,131  -26.43%   x 1.36
 btree::set::intersection_staggered_100_vs_100  624          373                             -251  -40.22%   x 1.67
 btree::set::intersection_staggered_10k_vs_10k  60,801       34,355                       -26,446  -43.50%   x 1.77
 btree::set::is_subset_100_vs_100               589          302                             -287  -48.73%   x 1.95
 btree::set::is_subset_10k_vs_10k               58,620       29,608                       -29,012  -49.49%   x 1.98
```
I'm not kidding, I cleaned config.toml and rebuilt with the same result. Replacing the body of `unwrap_unchecked` with `val.unwrap()` boosts iteration performance considerably. This is not related to the panic-safe changes for this PR in navigate.rs, but the iterator code higher up in map.rs also does a lot of `unwrap_unchecked`.

Also replacing the body of `unwrap_unchecked_unpanicky`, thus violating safety preconditions, does not help performance.

But wait... am I just wrongly assuming that in the release builds benchmarked, the `if cfg!(debug_assertions)` code gets compiled away? No, making `unwrap_unchecked` identical to the new `unwrap_unchecked_unpanicky` does not change performance.

I conclude that this topic is unrelated to this PR. This PR (or actually, the PR where we introduced `replace`) needs an unpanicky `unwrap_unchecked` but not all `unwrap_unchecked` should be like that.

Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: Actually, I changed my mind a little. It does mean that I shouldn't sing the praise of `unwrap_unchecked` by listing a 2nd version in a central location, when it's only used in one file anyway. So moving it.

File: src/liballoc/collections/btree/node.rs (hunk 26 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: Ah... we probably do not have implicit unsizing coercions for raw slice pointers.

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (RalfJung) [reply src/liballoc/collections/btree/navigate.rs]: Wait, the `unwrap` version is *faster* than the unsafe one that UBs on `None`? Wow, how on Earth...

Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: Well probably someone made sure `unwrap` generates excellent code, and this attempt at micro-optimization no longer pays off (if it ever did).

File: src/liballoc/collections/btree/node.rs (hunk 26 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs]: Oh... I didn't know `*const [_]` was more than a shorthand for `*const [i32; 2]` in that context. Would never have found this if I wasn't a lazy typist.

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: It's a shorthand for `*const [i32]` actually.

File: src/liballoc/collections/btree/node.rs (hunk 24 above)
Comment (ssomers) [reply src/liballoc/collections/btree/node.rs:518]: FYI, I think that the "requiring Type: 'a" is no more than a compiler artefact coming out before the real error about borrowing a from a temporary. There is no need for `reborrow` here, because we are a marker::Immut NodeRef, thus copyable. Without `reborrow`, I guess we are implicitly copied to a temporary, but then apparently the borrow checker has no problem returning a slice reference from that. Or it knows that both returned slice references stem from the same borrow or something. Anyway, over to another PR.

File: src/liballoc/collections/btree/navigate.rs (hunk 25 above)
Comment (ssomers) [reply src/liballoc/collections/btree/navigate.rs]: It looks more reasonable 'for a [standalone microbenchmark](https://github.com/ssomers/rust_bench_quickies): 
```
test option_unwrap::unwrap                               ... bench:         104 ns/iter (+/- 3)
test option_unwrap::unwrap_or_else_unreachable           ... bench:          70 ns/iter (+/- 1)
test option_unwrap::unwrap_or_else_unreachable_unchecked ... bench:          55 ns/iter (+/- 0)
```
Here it's only weird that the middle one (`unwrap_or_else(|| unreachable!()))`) appears faster than plain `unwrap`. That difference disappears if we make the option contents big (the option contents are a simple reference in the numbers above), while the `unreachable_unchecked` code stays twice as fast.

To be continued in another PR.

**Comment by ssomers** [comment]
Latest numbers covering all 4 commits:

```benchcmp old newer --threshold 5
 name                                        old ns/iter  newer ns/iter  diff ns/iter   diff %  speedup
 btree::map::clone_slim_100_and_remove_all   5,604        4,815                  -789  -14.08%   x 1.16
 btree::map::clone_slim_100_and_remove_half  3,818        3,535                  -283   -7.41%   x 1.08
 btree::map::clone_slim_10k_and_remove_all   592,330      497,400             -94,930  -16.03%   x 1.19
 btree::map::first_and_last_10k              66           74                        8   12.12%   x 0.89
 btree::map::insert_rand_100                 45           33                      -12  -26.67%   x 1.36
 btree::map::insert_rand_10_000              45           33                      -12  -26.67%   x 1.36
 btree::map::insert_seq_100                  52           41                      -11  -21.15%   x 1.27
 btree::map::insert_seq_10_000               98           93                       -5   -5.10%   x 1.05
 btree::map::iter_0                          1,259        1,563                   304   24.15%   x 0.81
 btree::map::iter_100                        3,333        3,514                   181    5.43%   x 0.95
 btree::map::iter_10k                        4,019        4,519                   500   12.44%   x 0.89
 btree::map::range_included_excluded         403,373      424,565              21,192    5.25%   x 0.95
 btree::map::range_included_included         450,577      402,005             -48,572  -10.78%   x 1.12
 btree::map::range_unbounded_unbounded       37,271       28,938               -8,333  -22.36%   x 1.29
 btree::map::range_unbounded_vs_iter         36,624       33,619               -3,005   -8.21%   x 1.09
 btree::set::clone_100_and_remove_all        4,480        3,631                  -849  -18.95%   x 1.23
 btree::set::clone_100_and_remove_half       2,872        2,487                  -385  -13.41%   x 1.15
 btree::set::clone_10k_and_remove_all        498,100      417,250             -80,850  -16.23%   x 1.19
 btree::set::is_subset_100_vs_10k            1,242        1,399                   157   12.64%   x 0.89
```

**Comment by crlf0710** [comment]
@ssomers Ping from triage. What's the current status on this? Is this ready for review again? (If so, you can use the rustbot to turn S-waiting-on-author to S-waiting-on-review)

**Comment by ssomers** [comment]
@crlf0710 It has been ready for review since Jul 23.

> you can use the rustbot to turn S-waiting-on-author to S-waiting-on-review

I have read such comments before and never found out how. It doesn't matter anymore because I lost interest.

**Comment by Mark-Simulacrum** [comment]
Rebased and reviewed locally -- this seems good to me. I didn't re-run tests or miri tests, though -- will wait on PR CI to pass, but r=me with that done.

**Comment by RalfJung** [comment]
Looks like this PR does not add the Miri testcase from https://github.com/rust-lang/rust/issues/73915, but I can do that in a follow-up PR (after verifying that it indeed works in Miri).

**Comment by RalfJung** [comment]
Oh never mind, this removes the `#[cfg_attr(miri, ignore)]`, so Miri will pick it up. (Though currently there's another test suite failure so I'll have to specifically check locally.)

**Comment by ssomers** [comment]
> I'll submit a test based on `test_all_refs`. I thought one of @ssomers's PRs added that

`test_values_mut` is still there, since #74666, and now Miri knows about it.

**Comment by RalfJung** [comment]
Oh, those tests already landed, great. :)

**Comment by Mark-Simulacrum** [comment]
This looks like it was a small performance [improvement](https://perf.rust-lang.org/compare.html?start=b4bdc07ff5a70175dbcdff7331c557245ddb012f&end=d92155bf6ae0b7d79fc83cbeeb0cc0c765353471) on token-stream-stress-check of around 1.2%. Not really expected but nice anyway :)
