### PR TITLE
Fix `-Zremap-path-scope` rmeta handling

### LINKED ISSUE #139217: `-Zremap-path-scope=macro` still remaps inlined ELF symbols
The unstable feature `-Zremap-path-scope` is supposed to constrain `--remap-path-prefix` to only a certain subset of remappings. However, it seems as though DWARF data still has paths remapped for functions that are inlined.

I tried this code:

```sh
cargo init a
cargo init --lib b
echo 'b = {path = "../b"}' >> a/Cargo.toml
echo '#[inline] pub fn get_some_value() -> i32 { 42 }' > b/src/lib.rs
echo 'fn main() { println!("{}", b::get_some_value()); }' > a/src/main.rs
cd a
RUSTFLAGS="--remap-path-prefix=/=foo -Zremap-path-scope=macro" cargo +nightly build
llvm-dwarfdump-15 --show-sources target/debug/a | grep -v ^/rust
```

I expected to see this happen: No DWARF symbols should contain `foo`, because only `file!()` macros should be remapped.

Instead, this happened: The inlined symbol got remapped:

```
user@ubuntu:/opt/Xous/simple-test/a$ llvm-dwarfdump-15 --show-sources target/debug/a | grep -v ^/rust
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/hint.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/process.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/process/unix/common.rs
/opt/Xous/simple-test/a/foo/opt/Xous/simple-test/b/src/lib.rs
/opt/Xous/simple-test/a/src/main.rs
user@ubuntu:/opt/Xous/simple-test/a$
```

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (fedf10752 2025-03-30)
binary: rustc
commit-hash: fedf10752b973d83f3f7c0f819b2659c21a634de
commit-date: 2025-03-30
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.1
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Urgau**
This PR fixes the conditional remapping (`-Zremap-path-scope`) of rmeta file paths ~~by using the `debuginfo` scope~~ by conditionally embedding the local path in addition to the remapped path.

Fixes https://github.com/rust-lang/rust/issues/139217

### CODE REVIEW

**Review by fmease — COMMENTED** [review]
Looks fine to me but I'm not an expert here and I'm wondering if it needs to be `DEBUGINFO | DIAGNOSTICS` over just `DEBUGINFO`.

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 1]
```diff
@@ -520,6 +520,9 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
         let source_map = self.tcx.sess.source_map();
         let all_source_files = source_map.files();
 
+        let filename_display_preference =
+            self.tcx.sess.filename_display_preference(RemapPathScopeComponents::DEBUGINFO);
```
[the remark this answers is not in the document]
Comment (Urgau) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:524]: Hum, right. I think I completely got this backwards.

The encoded table is used by downstream crates, which should respect the upstream crate preference, which can only be done if we encode the right information.

I'm back at the start again, who is unconditionally using a remapped path.

The wild thing is that there is nothing in the generated assembly, and when I do a `strings` on the generated binary the path is not even there (many others are, but not the remapped ones).

[the remark this answers is not in the document]
Comment (xobs) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:524]: If the path is relative, then it's appended to the path of the module. Most ELF tools don't show that they're doing this, so it can be difficult to detect where the relative path starts (see https://github.com/rust-lang/rust/issues/137016#issuecomment-2673872342 for slightly more information)

**Comment by Urgau** [comment]
After more investigation I was finally able to figure out the real issue, when we embed the paths in the `rmeta` files we call `PathMapping::to_embeddable_absolute_path`, that function does the necessary to create a remapped path when possible BUT when doing so that function does keep the original un-remapped path.

This was done before `-Zremap-path-scope` introduction and means that when we are in a subsequent crate we only have access to the remapped path even through we might want the un-remapped path (depending on the remap path scope), which lead to the issue described in #139217 where the path of the dependency was un-conditionaly the remapped one because that's all we got.

I've added to `PathMapping` and `PathMapping::to_embeddable_absolute_path` some logic to keep the local path when not all remap path scope are requested, as to keep rlib and rmeta free of local path when only `--remap-path-prefix` is passed (privacy reason and build reproducibility reason).

@rustbot labels -S-blocked -S-waiting-on-author +S-waiting-on-review

File: compiler/rustc_span/src/lib.rs [hunk 2]
```diff
@@ -369,6 +347,16 @@ impl From<PathBuf> for FileName {
     }
 }
 
+#[derive(Clone, Copy, Eq, PartialEq, Hash, Debug)]
+pub enum FileNameEmbeddablePreference {
+    /// If a remapped path is avalaible, only embed the `virtual_path` and omit the `local_path`.
+    ///
+    /// Otherwise embed the local-path into the `virtual_path`.
+    RemappedOnly,
+    /// Embed the original path as well as it's remapped `virtual_path` component if avalaible.
```
Comment (fmease) [inline compiler/rustc_span/src/lib.rs:356]:
```suggestion
    /// Embed the original path as well as its remapped `virtual_path` component if avalaible.
```

File: compiler/rustc_span/src/source_map.rs [hunk 3]
```diff
@@ -1218,10 +1228,13 @@ impl FilePathMapping {
         match file_path {
             // Anything that's already remapped we don't modify, except for erasing
             // the `local_path` portion.
-            RealFileName::Remapped { local_path: _, virtual_name } => {
+            RealFileName::Remapped { local_path, virtual_name } => {
                 RealFileName::Remapped {
                     // We do not want any local path to be exported into metadata
```
Comment (fmease) [inline compiler/rustc_span/src/source_map.rs:1233]: Comment outdated

**Comment by fmease** [comment]
I don't have the capacity to properly review this right now.
r? compiler

**Comment by fmease** [comment]
Esteban isn't that active rn afaik.
r? compiler

File: compiler/rustc_span/src/lib.rs [hunk 4]
```diff
@@ -368,6 +346,16 @@ impl From<PathBuf> for FileName {
     }
 }
 
+#[derive(Clone, Copy, Eq, PartialEq, Hash, Debug)]
+pub enum FileNameEmbeddablePreference {
+    /// If a remapped path is avalaible, only embed the `virtual_path` and omit the `local_path`.
+    ///
+    /// Otherwise embed the local-path into the `virtual_path`.
+    RemappedOnly,
+    /// Embed the original path as well as its remapped `virtual_path` component if avalaible.
```
Comment (nnethercote) [inline compiler/rustc_span/src/lib.rs:355]: ditto

**Comment by nnethercote** [comment]
I'm no expert on this stuff, but the code seems fine and you've added plenty of tests, which is great. r=me with the typos fixed.

@bors delegate=Urgau
