### PR TITLE
Ensure consistent drop for panicking drop in hint::select_unpredictable

### LINKED ISSUE #145148: `hint::select_unpredictable` forgets to drop one argument if dropping another panics.
I tried this code:

```rust
struct Thing {
    label: &'static str,
    panic_on_drop: bool,
}

impl Drop for Thing {
    fn drop(&mut self) {
        println!("Dropping: {}", self.label);
        if self.panic_on_drop {
            println!("Panicking...");
            panic!("Drop panicked");
        } else {
            println!("Not panicking.")
        }
    }
}

fn main() {
    let a = Thing {
        label: "a",
        panic_on_drop: false,
    };
    let b = Thing {
        label: "b",
        panic_on_drop: true,
    };
    let _ = std::hint::select_unpredictable(true, a, b);
}
```

I expected `b` to be dropped, at which point a panic occurs, then `a` is dropped. Instead, `a` is not dropped at all.

```
Dropping: b
Panicking...

thread 'main' (133912) panicked at src/main.rs:11:13:
Drop panicked
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0-nightly (de3efa79f 2025-08-08)
binary: rustc
commit-hash: de3efa79f95852c7427587f1d535bfea7c0d6779
commit-date: 2025-08-08
host: aarch64-apple-darwin
release: 1.91.0-nightly
LLVM version: 21.1.0
```

### PR DESCRIPTION
**Pull request by 197g**
There are a few alternatives to the implementation. The principal problem is that the selected value must be owned (in the sense of having a drop flag of sorts) when the unselected value is dropped, such that panic unwind goes through the drop of both. This ownership must then be passed on in return when the drop went smoothly. 

The basic way of achieving this is by extracting the selected value first, at the cost of relying on the optimizer a little more for detecting the copy as constructing the return value despite having a place in the body. Unfortunately, that causes LLVM to discard the !unpredictable annotation (for some reason that is beyond my comprehension of LLVM).

<details>
<summary>Extract from the build log showing an unannotated select being used</summary>

```
2025-08-09T16:51:06.8790764Z            39: define noundef i64 @test_int2(i1 noundef zeroext %p, i64 noundef %a, i64 noundef %b) unnamed_addr #0 personality ptr @rust_eh_personality { 
2025-08-09T16:51:06.8791368Z check:47'0                                  X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
2025-08-09T16:51:06.8791700Z            40: start: 
2025-08-09T16:51:06.8791858Z check:47'0     ~~~~~~~
2025-08-09T16:51:06.8792043Z            41:  %ret.i = select i1 %p, i64 %a, i64 %b 
2025-08-09T16:51:06.8792293Z check:47'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-08-09T16:51:06.8792686Z check:47'1               ?                             possible intended match
2025-08-09T16:51:06.8792946Z            42:  ret i64 %ret.i 
2025-08-09T16:51:06.8793127Z check:47'0     ~~~~~~~~~~~~~~~~
```

</details>

So instead, this PR includes a guard to drop the selected `MaybeUnit<T>` which is active only for the section where the unselected value is dropped. That leaves the code for selecting the result intact leading to the expected ir. That complicates the 'unselection' process a little bit since we require _both_ values as a result of that intrinsic call. Since the arguments alias, this portion as well as the drop guard uses raw pointers.

Closes: rust-lang/rust#145148
Prior: rust-lang/rust#139977

### CODE REVIEW

File: library/core/src/hint.rs [hunk 1]
```diff
@@ -786,12 +786,42 @@ pub fn select_unpredictable<T>(condition: bool, true_val: T, false_val: T) -> T
     // Change this to use ManuallyDrop instead.
     let mut true_val = MaybeUninit::new(true_val);
     let mut false_val = MaybeUninit::new(false_val);
+
+    struct DropOnPanic<T> {
+        inner: *mut MaybeUninit<T>,
```
Comment (joboet) [inline library/core/src/hint.rs]: References should be fine here, right?

```suggestion
        inner: &'a mut MaybeUninit<T>,
```

File: library/core/src/hint.rs [hunk 2]
```diff
@@ -786,12 +786,42 @@ pub fn select_unpredictable<T>(condition: bool, true_val: T, false_val: T) -> T
...
     unsafe {
-        crate::intrinsics::select_unpredictable(!condition, &mut true_val, &mut false_val)
-            .assume_init_drop();
+        // Extract the selected value first, ensure it is dropped as well if dropping the unselected
+        // value panics.
+        let (guard, drop) = crate::intrinsics::select_unpredictable(
+            condition,
+            (true_ptr, false_ptr),
+            (false_ptr, true_ptr),
+        );
```
Comment (joboet) [inline library/core/src/hint.rs]: I'd split this up into two `select_unpredictable`s – that probably yields simpler LLVM IR than the `insertvalue` and `extractvalue` calls of this version.

File: library/coretests/tests/hint.rs [hunk 3]
```diff
@@ -21,3 +21,40 @@ fn select_unpredictable_drop() {
...
+
+    // The correct drop order is:
+    //
+    // 1. `unselected` drops, writes 1, and panics as 0 != 0xff
+    // 2. `selected` drops during unwind, writes 0xdead and does not panic as 1 == 1
+    // 3. `armed` drops during unwind, writes 0 and does not panic as 0xdead == 0xdead
+    //
+    // If `selected` is not dropped, `armed` panics as 1 != 0xdead
+    let _unreachable =
+        core::hint::select_unpredictable(core::hint::black_box(true), selected, unselected);
```
Comment (joboet) [inline library/coretests/tests/hint.rs]: `black_box` is unnecessary here, this isn't testing the codegen nor the performance.
```suggestion
        core::hint::select_unpredictable(true, selected, unselected);
```

**Review by joboet — CHANGES_REQUESTED** [review]

File: library/core/src/hint.rs (hunk 1 above)
Comment (197g) [reply library/core/src/hint.rs]: We have the same two pointers in both arguments to the first `select_unpredictable`, each one duplicate. And I should add they have necessarily overlapping lifetimes, even if split then choosing the second one must still have the other alive.

Comment (joboet) [reply library/core/src/hint.rs]: Oh right, fair enough!

Comment (197g) [reply library/core/src/hint.rs]: Do you think it's simpler code to dereference the pointer as it gets constructed into a `Guard`? I thought since we're calling `MaybeUninit`'s proxy to `drop_in_place` it would just add one additional location of unsafe precondition. I'll document a little more.

File: library/coretests/tests/hint.rs [hunk 4]
```diff
@@ -21,3 +21,42 @@ fn select_unpredictable_drop() {
...
+    //
+    // 1. `unselected` drops, writes 1, and panics as 0 != 0xff
+    // 2. `selected` drops during unwind, writes 0xdead and does not panic as 1 == 1
+    // 3. `armed` drops during unwind, writes 0 and does not panic as 0xdead == 0xdead
+    //
+    // If `selected` is not dropped, `armed` panics as 1 != 0xdead
+    let _unreachable = core::hint::select_unpredictable(true, selected, unselected);
+
+    // If this panics we do not match the `should_panic` expectation.
+    unreachable!();
```
Comment (joboet) [inline library/coretests/tests/hint.rs]: A `#[should_panic]` test not panicking counts as a test failure, right? For me at least, this does not help make the test easier to read...

File: library/core/src/hint.rs (hunk 1 above)
Comment (197g) [reply library/core/src/hint.rs]: Another option would be to avoid the `MaybeUninit` entirely in the type and use just raw pointers with direct `drop_in_place` calls. The `assume_init_drop` is noise with an additional precondition that must be fulfilled anyways. And if the comment of moving to `ManuallyDrop` is eventually followed-up on those attributes would remain untouched.

Comment (joboet) [reply library/core/src/hint.rs]: > Another option would be to avoid the `MaybeUninit` entirely in the type and use just raw pointers with direct `drop_in_place` calls. The `assume_init_drop` is noise with an additional precondition that must be fulfilled anyways. And if the comment of moving to `ManuallyDrop` is eventually followed-up on those attributes would remain untouched.

Personally, I think this might be the cleanest option.

File: library/coretests/tests/hint.rs (hunk 4 above)
Comment (197g) [reply library/coretests/tests/hint.rs]: True, not-panicking is also a signal. I left the message comparison in place just to be sure it originates from the assertion, hopefully also connecting the dots that this assertion should trigger once for readers.
