### PR TITLE
Fix multi-cgu+debug builds using autodiff by delaying autodiff till lto

### LINKED ISSUE #152470: [autodiff] compiler error when differentiating functions (like powi)
Follow up of [#wg-autodiff > Simplify autodiff handling of dependencies (rlib) @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/390790-wg-autodiff/topic/Simplify.20autodiff.20handling.20of.20dependencies.20.28rlib.29/near/573014613) for @ZuseZ4 and @sgasho 

### Summary:

Generating the code to compute the derivatives of a function that calls other functions like `powi` results in a compiler error. Both `autodiff_forward` and `autodiff_reverse` are affected.

### Minimal working example:

```rust
#![feature(autodiff)]

use std::autodiff::*;

#[autodiff_forward(rb_fwd, Dual, Dual, Const, Const, Dual)]
#[autodiff_reverse(rb_rev, Active, Active, Const, Const, Active)]
fn rosenbrock(x: f64, y: f64, a: f64, b: f64) -> f64 {
    (a - x).powi(2) + b * (y - x.powi(2)).powi(2)
}

fn main() {
    let (x, y) = (3.0, 5.0);
    let (a, b) = (1.0, 100.0);

    let z = rosenbrock(x, y, a, b);
    let (_, vjp_x, vjp_y) = rb_rev(x, y, a, b, 1.0);

    println!("{}", z);
    println!("{} {}", vjp_x, vjp_y);
}

```
The code above should compile and print the following when ran:

```rust
1604
4804 -800
```

Instead, it results in a compiler error. Building with `-Z autodiff=Enable,PrintPasses` outputs:

```rust
error: examples/rosenbrock.rs:8:43: in function preprocess__RNvCsdrX0DD2DCiN_10rosenbrock10rosenbrockB1_ double (double, double, double, double): Enzyme: No reverse pass found for _RNvMNtCs4FJwUMN6RBB_3std3f64d4powiCsdrX0DD2DCiN_10rosenbrock
        at context:   %9 = call double @_RNvMNtCs4FJwUMN6RBB_3std3f64d4powiCsdrX0DD2DCiN_10rosenbrock(double %8, i32 2) #6, !dbg !24


function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
function(ee-instrument<>),always-inline,coro-cond(coro-early,cgscc(coro-split),coro-cleanup,globaldce),alloc-token,function(annotation-remarks),EnzymeNewPM
error: could not compile `enzyme-playground` (example "rosenbrock") due to 1 previous error
```

Removing the calls to `powi` in the function to differentiate overcomes the issue and produces the expected output:

```rust
#[autodiff_forward(rb_fwd, Dual, Dual, Const, Const, Dual)]
#[autodiff_reverse(rb_rev, Active, Active, Const, Const, Active)]
fn rosenbrock(x: f64, y: f64, a: f64, b: f64) -> f64 {
    let c = a - x;
    let d = y - x * x;
    (c * c) + b * (d * d)
}
```

### Meta

`rustc --version --verbose`:
```rust
rustc 1.95.0-nightly (f21b4c088 2026-02-10)
binary: rustc
commit-hash: f21b4c0888ca6a388fcf9365fc0044fa0642ab98
commit-date: 2026-02-10
host: aarch64-apple-darwin
release: 1.95.0-nightly
LLVM version: 22.1.0
```

Built following [these instructions](https://rustc-dev-guide.rust-lang.org/autodiff/installation.html).

### PR DESCRIPTION
**Pull request by ZuseZ4**
fixes: https://github.com/rust-lang/rust/issues/152470

r? @bjorn3

### CODE REVIEW

File: compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp [hunk 1]
```diff
@@ -908,7 +908,10 @@ extern "C" LLVMRustResult LLVMRustOptimize(
 
   // now load "-enzyme" pass:
   // With dlopen, ENZYME macro may not be defined, so check EnzymePtr directly
-  if (EnzymePtr) {
+  // In the case of debug builds with multiple codegen units, we might not
+  // have all function definitions available during the early compiler
+  // invocations. We therefore wait for the final lto step to run Enzyme.
+  if (EnzymePtr && IsLTO) {
```
Comment (ZuseZ4) [inline compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp:914]: I could have checked for fat-lto only, since that's what we require atm. But it seems to work atm. and every once in a while I experiment with lowering our requirements from fat to thin lto, so I think it's fine.
