### PR TITLE
rustc_metadata: Do not forget to encode inherent impls for foreign types

### LINKED ISSUE #46665: extern_types associated functions aren't visible from other crates
crate `foo`:
```Rust
#![feature(extern_types)]

extern "C" {
    pub type Foo;
}

impl Foo {
    pub fn new() -> FooBox {
        let raw = unimplemented!("Get through ffi");
        FooBox(raw)
    }
}

pub struct FooBox(*mut Foo);

impl Drop for FooBox {
    fn drop(&mut self) {
        unimplemented!("call ffi drop");
    }
}

```

crate `foouser`:
```Rust
extern crate foo;

fn main() {
    let foo = foo::Foo::new();
    println!("{:p}", &foo);
}

```

Error:
```
error[E0599]: no function or associated item named `new` found for type `foo::Foo` in the current scope
 --> foouser.rs:4:15
  |
4 |     let foo = foo::Foo::new();
  |               ^^^^^^^^^^^^^ function or associated item not found in `foo::Foo`
```

This error does not occur if `main` is located within the same crate.

### PR DESCRIPTION
**Pull request by petrochenkov**
So I tried to move FFI interface for LLVM from `rustc_codegen_llvm` to `rustc_llvm` and immediately encountered this fascinating issue.

Fixes https://github.com/rust-lang/rust/issues/46665.

### CODE REVIEW

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 1]
```diff
@@ -1753,6 +1753,7 @@ impl EncodeContext<'a, 'tcx> {
         self.encode_const_stability(def_id);
         self.encode_deprecation(def_id);
         self.encode_item_type(def_id);
+        self.encode_inherent_implementations(def_id);
```
Comment (oli-obk) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:1756]: we should probably deduplicate the extern item/regular item encoding logic (well, the parts that are shared between them). While I think this would be good to have, you can r=me this PR and just open an E-easy issue for it

Comment (petrochenkov) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:1756]: Made an issue - https://github.com/rust-lang/rust/issues/77393.
