### PR TITLE
fix Miri discriminant handling

### LINKED ISSUE #62138: Miri/CTFE discriminant computation happens at the wrong type
When loading discriminants of an enum that uses niche optimizations, Miri/CTFE has to do some arithmetic:
https://github.com/rust-lang/rust/blob/bdd4bda4d5fe7eb24a7209a6c0c968a54869d3b7/src/librustc_mir/interpret/operand.rs#L645-L646

Currently, this happens on type `u128`. That's probably wrong, it should happen on the type of the discriminant. That will result in different overflow behavior.

It's just addition and subtraction, so signed vs unsigned does not matter and we could just mask off the "too high" bits after each operation, as in:
https://github.com/rust-lang/rust/blob/bdd4bda4d5fe7eb24a7209a6c0c968a54869d3b7/src/librustc_target/abi/mod.rs#L664-L669

However, it might be more elegant to use our `binary_*op` methods in `operator.rs`.

Cc @oli-obk @eddyb

### PR DESCRIPTION
**Pull request by RalfJung**
This can be reviewed commit-by-commit fairly well.

The Miri side is at https://github.com/rust-lang/miri/pull/903.

Fixes https://github.com/rust-lang/rust/issues/62138

r? @eddyb @oli-obk

### CODE REVIEW

**Comment by eddyb** [comment]
I'd prefer to block this on #63450.

**Comment by RalfJung** [comment]
I factored out the parts that are *not* blocked into a separate PR: https://github.com/rust-lang/rust/pull/63658.

**Comment by JohnCSimon** [comment]
Ping from triage:
This PR has sat idle for over a week, can you please post your status? Thanks.
@RalfJung @eddyb

**Comment by RalfJung** [comment]
@eddyb is blocking this on https://github.com/rust-lang/rust/pull/63450. That's fine for me as long as that does not take too long.

**Comment by RalfJung** [comment]
@eddyb https://github.com/rust-lang/rust/pull/63450 does not seem to be moving anywhere. Could you explain why it is better to leave this Miri bug unfixed?

**Comment by JohnCSimon** [comment]
Ping from triage
@RalfJung @eddyb Still blocked on #63450 ...

**Comment by RalfJung** [comment]
@eddyb noticed that doing *all* arithmetic using machine operations at discriminant type is also not correct, so now this does the variant idx computations on the host (checked so they do not overflow).

**Comment by RalfJung** [comment]
@eddyb also agree to no longer block this on https://github.com/rust-lang/rust/pull/63450

**Comment by RalfJung** [comment]
I should also mention, [tests will be added to Miri](https://github.com/rust-lang/miri/pull/903). My [naive attempt](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9308e9bd0822734f5295423ee0208891) at turning that into CTFE tests failed. @oli-obk is it possible to test this with current CTFE so that we have an in-tree test?

**Comment by oli-obk** [comment]
> is it possible to test this with current CTFE so that we have an in-tree test?

Make it a `-Zunleash-the-miri-inside-of-you` test :smiling_imp:

**Comment by RalfJung** [comment]
> Make it a -Zunleash-the-miri-inside-of-you test 

I think that actually worked :D

File: src/librustc_mir/interpret/operand.rs [hunk 1]
```diff
@@ -682,16 +687,31 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+                            discr_val,
+                            niche_start_val,
+                        )?;
+                        let variant_index_relative = variant_index_relative_val
+                            .to_scalar()?
+                            .assert_bits(discr_val.layout.size);
+                        // Then computing the absolute variant idx should not overflow any more.
+                        let variant_index = variants_start
+                            .checked_add(variant_index_relative)
+                            .expect("oveflow computing absolute variant idx");
```
Comment (eddyb) [inline src/librustc_mir/interpret/operand.rs]: I wonder if this can overflow when it's the dataful variant. Still, ICE > silently doing the wrong thing.

File: src/librustc_mir/interpret/operand.rs [hunk 2]
```diff
@@ -682,16 +687,31 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+                        // Check if this is in the range that indicates an actual discriminant.
+                        if variants_start <= variant_index && variant_index <= variants_end {
```
Comment (eddyb) [inline src/librustc_mir/interpret/operand.rs]: Oh wait you can just compare `variant_index_relative` against `variants_end - variants_start`, and then you can move the addition inside the "niche" side of the `if` (and it can be just `+` since it can't possibly overflow given the condition).

File: src/librustc_mir/interpret/place.rs [hunk 3]
```diff
@@ -1050,22 +1052,31 @@ where
...
-                    let niche_value = variant_index.as_u32() - niche_variants.start().as_u32();
-                    let niche_value = (niche_value as u128)
-                        .wrapping_add(niche_start);
-                    self.write_scalar(
-                        Scalar::from_uint(niche_value, niche_dest.layout.size),
-                        niche_dest
+                    let variants_start = niche_variants.start().as_u32();
+                    let variant_index_relative = variant_index.as_u32()
+                        .checked_sub(variants_start)
+                        .expect("overflow computing relative variant idx");
```
Comment (eddyb) [inline src/librustc_mir/interpret/place.rs]: I think this is fine because this is a "niche" variant.

File: src/librustc_mir/interpret/place.rs [hunk 4]
```diff
@@ -1050,22 +1052,31 @@ where
...
+                    // We need to use machine arithmetic when taking into account `niche_start`.
+                    let discr_layout = self.layout_of(discr_layout.value.to_int_ty(*self.tcx))?;
+                    let niche_start_val = ImmTy::from_uint(niche_start, discr_layout);
+                    let variant_index_relative_val =
+                        ImmTy::from_uint(variant_index_relative, discr_layout);
+                    let discr_val = self.binary_op(
+                        mir::BinOp::Add,
+                        variant_index_relative_val,
+                        niche_start_val,
                     )?;
```
Comment (eddyb) [inline src/librustc_mir/interpret/place.rs]: I wonder how much this matters - you just need to truncate the result, I think? Either way, the symmetry with reading is probably fine.

File: src/librustc_mir/interpret/place.rs (hunk 3 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: Sure but is there any reason *not* to ICE if this overflows anyway?

File: src/librustc_mir/interpret/operand.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/operand.rs]: So the if should change to `variant_index_relative <= variants_end - variants_start` you say?

What is the "niche side of the if"?

**Comment by eddyb** [comment]
r=me with https://github.com/rust-lang/rust/pull/63448#discussion_r325624198 fixed.

File: src/librustc_mir/interpret/operand.rs [hunk 5]
```diff
@@ -682,16 +687,31 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
                         (dataful_variant.as_u32() as u128, dataful_variant)
                     },
                     Ok(raw_discr) => {
-                        let adjusted_discr = raw_discr.wrapping_sub(niche_start)
-                            .wrapping_add(variants_start);
-                        if variants_start <= adjusted_discr && adjusted_discr <= variants_end {
-                            let index = adjusted_discr as usize;
-                            assert_eq!(index as u128, adjusted_discr);
+                        // We need to use machine arithmetic to get the relative variant idx.
```
Comment (oli-obk) [inline src/librustc_mir/interpret/operand.rs]: Write out the formula in a comment

**Comment by RalfJung** [comment]
> r=me with #63448 (comment) fixed.

I think I did this -- and the tests are all passing.
@bors r=eddyb

**Comment by mati865** [comment]
cc @pietroalbini ^^ many jobs were stared very late and some still are waiting for the agent
