### PR TITLE
Automatically taint InferCtxt when errors are emitted

### LINKED ISSUE #126485: Error tainting in parallel compiler
Emitting diagnostics in one thread taints every infcx out there, but other threads don't expect their infcx to become tainted if they themselves aren't emitting anything. This leads to skipped diagnostics, early bailing out of queries that could've run to completion or painful to debug ICEs. For example, take #120601: snippet below run with `-Zthreads=3 --edition=2021` works, but crashes if you uncomment the last function.
```rust
struct Tuple(i32);

async fn tuple() -> Tuple {
    Tuple(1i32)
}

async fn xyz() {
    match tuple() {
        Tuple(_) => {},
    }
}

/* uncomment this function to observe crashes
async fn fail() {
    Fail(())
}
*/
```
In parallel compiler, code that does different things depending on the result of `InferCtxt::tainted_by_errors()` can introduce spurious failures or even replace previously resolved `Ty`'s with `Ty::new_error()`:
https://github.com/rust-lang/rust/blob/f9515fdd5aa132e27d9b580a35b27f4b453251c1/compiler/rustc_borrowck/src/nll.rs#L202
in `regioncx.infer_opaque_types`:
https://github.com/rust-lang/rust/blob/f9515fdd5aa132e27d9b580a35b27f4b453251c1/compiler/rustc_borrowck/src/region_infer/opaque_types.rs#L133-L134
https://github.com/rust-lang/rust/blob/f9515fdd5aa132e27d9b580a35b27f4b453251c1/compiler/rustc_borrowck/src/region_infer/opaque_types.rs#L278-L285
relevant part of `InferCtxt`:
https://github.com/rust-lang/rust/blob/f9515fdd5aa132e27d9b580a35b27f4b453251c1/compiler/rustc_infer/src/infer/mod.rs#L1219-L1239
```
rustc 1.81.0-nightly (f1586001a 2024-06-13)
binary: rustc
commit-hash: f1586001ace26df7cafeb6534eaf76fb2c5513e5
commit-date: 2024-06-13
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by oli-obk**
r? @nnethercote 

Basically `InferCtxt::dcx` now returns a `DiagCtxt` that refers back to the `Cell<Option<ErrorGuaranteed>>` of the `InferCtxt` and thus when invoking `Diag::emit`, and the diagnostic is an error, we taint the `InferCtxt` directly.

That change on its own has no effect at all, because `InferCtxt` already tracks whether errors have been emitted by recording the global error count when it gets opened, and checking at the end whether the count changed. So I removed that error count check, which had a bit of fallout that I immediately fixed by invoking `InferCtxt::dcx` instead of `TyCtxt::dcx` in a bunch of places.

The remaining new errors are because an error was reported in another query, and never bubbled up. I think they are minor enough for this to be ok, and sometimes it actually improves diagnostics, by not silencing useful diagnostics anymore.

fixes #126485 (cc @olafes)

There are more improvements we can do (like tainting in hir ty lowering), but I would rather do that in follow up PRs, because it requires some refactorings.

### CODE REVIEW

File: compiler/rustc_infer/src/infer/mod.rs [hunk 1]
```diff
@@ -1089,19 +1089,7 @@ impl<'tcx> InferCtxt<'tcx> {
...
-            // excluded to avoid some being swallowed in the presence of
-            // non-lint errors. (It's arguable whether or not this exclusion is
-            // important.)
-            let guar = self.dcx().has_errors().unwrap();
-            self.set_tainted_by_errors(guar);
-            Some(guar)
-        } else {
-            None
-        }
+        self.tainted_by_errors.get()
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/mod.rs:1092]: This is the core change that causes diagnostics changes

File: compiler/rustc_infer/src/infer/mod.rs [hunk 2]
```diff
@@ -684,8 +684,8 @@ impl<'tcx> InferOk<'tcx, ()> {
 }
 
 impl<'tcx> InferCtxt<'tcx> {
-    pub fn dcx(&self) -> DiagCtxtHandle<'tcx> {
-        self.tcx.dcx()
+    pub fn dcx(&self) -> DiagCtxtHandle<'_> {
+        self.tcx.dcx().taintable_handle(&self.tainted_by_errors)
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/mod.rs:688]: This is what enables the auto-tainting (as long as one goes through this `dcx`). I'm looking into writing a lint that detects when you invoke `dcx` on something that does not taint, while a tainting thing is available

File: compiler/rustc_mir_dataflow/src/impls/initialized.rs [hunk 3]
```diff
@@ -50,15 +50,19 @@ use crate::{lattice, AnalysisDomain, GenKill, GenKillAnalysis, MaybeReachable};
...
     tcx: TyCtxt<'tcx>,
-    body: &'a Body<'tcx>,
+    body: &'mir Body<'tcx>,
     mdpe: &'a MoveDataParamEnv<'tcx>,
     skip_unreachable_unwind: bool,
 }
 
-impl<'a, 'tcx> MaybeInitializedPlaces<'a, 'tcx> {
-    pub fn new(tcx: TyCtxt<'tcx>, body: &'a Body<'tcx>, mdpe: &'a MoveDataParamEnv<'tcx>) -> Self {
+impl<'a, 'mir, 'tcx> MaybeInitializedPlaces<'a, 'mir, 'tcx> {
```
Comment (nnethercote) [inline compiler/rustc_mir_dataflow/src/impls/initialized.rs:60]: I will make a plea for better lifetime names than `'a`. In a type with multiple lifetimes, I don't like when some of the names are useful (`'mir`) and some are not (`'a`).  `Elaborator<'a, 'b, 'mir, 'tcx>` is a good example.

I know some of the `'a` names are pre-existing but we can do better for the new ones. Would `'mdpe` be a good name here instead of `'a`? Or `'env`? Anything even slightly descriptive would be better than `'a`. And I think that would propagate to a lot of the other changes in this commit.

File: compiler/rustc_borrowck/src/borrowck_errors.rs [hunk 4]
```diff
@@ -6,8 +6,8 @@ use rustc_middle::span_bug;
 use rustc_middle::ty::{self, Ty, TyCtxt};
 use rustc_span::Span;
 
-impl<'tcx> crate::MirBorrowckCtxt<'_, '_, '_, 'tcx> {
-    pub fn dcx(&self) -> DiagCtxtHandle<'tcx> {
```
Comment (nnethercote) [inline compiler/rustc_borrowck/src/borrowck_errors.rs:10]: Would `'infcx` be a better lifetime name than `'cx` for this second commit?

I see now that `infcx` is used for both `InferCtxt` (the common case) and `BorrowckInferCtxt` (the less common case, but the relevant one here). I wonder if `binfcx` would be a better name to make that distinction clearer.

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 5]
```diff
@@ -144,7 +144,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
     }
 
-    pub(crate) fn dcx(&self) -> DiagCtxtHandle<'tcx> {
+    pub(crate) fn dcx(&self) -> DiagCtxtHandle<'a> {
```
Comment (nnethercote) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:147]: `'root_ctxt` (or `'rcx`) would be a better lifetime name than `'a` for `FnCtxt`.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 6]
```diff
@@ -139,7 +139,7 @@ pub struct TypeErrCtxt<'a, 'tcx> {
 }
 
 impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
```
Comment (nnethercote) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:141]: Hmm, hard to improve on `'a` for `TypeErrCtxt` due to it being used in multiple fields.

File: compiler/rustc_errors/src/lib.rs [hunk 7]
```diff
@@ -98,9 +99,9 @@ rustc_fluent_macro::fluent_messages! { "../messages.ftl" }
 
 // `PResult` is used a lot. Make sure it doesn't unintentionally get bigger.
 #[cfg(target_pointer_width = "64")]
-rustc_data_structures::static_assert_size!(PResult<'_, ()>, 16);
+rustc_data_structures::static_assert_size!(PResult<'_, ()>, 24);
 #[cfg(target_pointer_width = "64")]
-rustc_data_structures::static_assert_size!(PResult<'_, bool>, 16);
```
Comment (nnethercote) [inline compiler/rustc_errors/src/lib.rs:103]: This is a concern. We'll need a perf run.

Comment (nnethercote) [reply compiler/rustc_errors/src/lib.rs:103]: Oh, you already did one.

File: compiler/rustc_errors/src/lib.rs [hunk 8]
```diff
@@ -417,6 +418,7 @@ pub struct DiagCtxt {
 #[derive(Copy, Clone)]
 pub struct DiagCtxtHandle<'a> {
     dcx: &'a DiagCtxt,
+    tainted_with_errors: Option<&'a Cell<Option<ErrorGuaranteed>>>,
```
Comment (nnethercote) [inline compiler/rustc_errors/src/lib.rs:421]: Comments, please! This needs some explanation.

**Comment by nnethercote** [comment]
Will this change mean `set_tainted_by_errors` can be removed?

**Comment by nnethercote** [comment]
To play devil's advocate: why is this approach needed for `InferCtxt` when it's not needed for other parts of the compiler? Is it because it currently is messy and uses error counting and this PR at least improve things, even if it's not as clean as just propagating `ErrorGuaranteed` around like other parts of the compiler do?

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:147]: Preexisting and very verbose. I don't really think we should do it

**Comment by oli-obk** [comment]
> Will this change mean `set_tainted_by_errors` can be removed?

No, there are like 10 sites where we taint from a delayed bug, no clue what's up there, need to look at them. Also we sometimes taint when obtaining an ErrorGuaranteed from other queries.

**Comment by oli-obk** [comment]
> To play devil's advocate: why is this approach needed for `InferCtxt` when it's not needed for other parts of the compiler? Is it because it currently is messy and uses error counting and this PR at least improve things, even if it's not as clean as just propagating `ErrorGuaranteed` around like other parts of the compiler do?

Oh I def plan on doing that for other sites, too.

The alternative is to rely on everyone either tainting when they emit an error or producing an error type. It's not always desirable to emit an error type (e.g. there is no reason to make `x` in `let x: u32 = ();` have the error type, that just silences follow up errors, when we know it's `u32`) and it just doesn't scale having a social requirement to always taint when you emit an error. This PR automates that process.

**Comment by lcnr** [comment]
happy with the general approach 👍 I personally think the current approach of using `'a` for "boring" lifetimes is fine. imo using `'tcx` is meaningful because that's the lifetime you should return for interned stuff. THis is different from the `'a` in `&'a InferCtxt<'tcx>` where we never actually need stuff to live for that lifetime.

I think my general approach is something like: if we expect to be able to elide the lifetime in (nearly) all usages of the type, it can be non-descriptive.

**Comment by nnethercote** [comment]
ugh, whatever

@bors r+

**Comment by pnkfelix** [comment]
Visiting for weekly rustc-perf triage

* all regressions are to secondary match-stress benchmark, and were anticipated during a perf run during review
* marking as triaged.

@rustbot label: +perf-regression-triaged
