### PR TITLE
fix spurious test failure in `metadata_access_times`

### LINKED ISSUE #148408: Spurious test failure in metadata_access_times
On aarch64-gnu-llvm-20-1 ([here](https://github.com/rust-lang/rust/pull/148305#issuecomment-3478077364)):
```
	---- fs::tests::metadata_access_times stdout ----

thread 'fs::tests::metadata_access_times' (250955) panicked at library/std/src/fs/tests.rs:1737:33:
assertion failed: t1 <= t2
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---- fs::tests::metadata_access_times stdout end ----

failures:
    fs::tests::metadata_access_times
```

This test does not seem to have changed recently, so this might be pretty rare. I guess it can happen when the system clock moves backwards?

### PR DESCRIPTION
**Pull request by mattiapitossi**
Fixes rust-lang/rust#148408

The metadata_access_times test checks if the creation of a file occurs before another file, this check happens only on Linux. While on Win and Macos we check only that the created metadata is available. Given that the SystemTime is non monotonic as Instant this test could result in failures when the system clock changes.

### CODE REVIEW

File: library/std/src/fs/tests.rs [hunk 1]
```diff
@@ -1751,7 +1751,7 @@ fn metadata_access_times() {
     if cfg!(target_os = "linux") {
         // Not always available
         match (a.created(), b.created()) {
-            (Ok(t1), Ok(t2)) => assert!(t1 <= t2),
+            (Ok(_), Ok(_)) => {}
```
Comment (Mark-Simulacrum) [inline library/std/src/fs/tests.rs]: I think it would make sense to keep the check, instead querying the system time and if it has moved back skip the test? (Running it a few times could also work but moving back should hopefully be quite rare.)

Comment (mattiapitossi) [reply library/std/src/fs/tests.rs]: Thanks for the review (and sorry for the delay), I agree with the first solution and I've updated the PR. The idea is to save the system time when the test starts and then check the elapsed time against this variable before the assertion, if it throws an error then we know that a time change occurred. There is the probability that the time changes after we have created a and b and therefore the time change wouldn't be a real problem, so probably in that case the check could be also consider this, but eventually we could also skip those cases as they are more rare. What do you think?

Comment (Mark-Simulacrum) [reply library/std/src/fs/tests.rs]: I don't think it's worth trying to address that middle case of the system time rolling back but the files being in a still forward-running portion of the system clock. Ultimately this is just a test, we want it to exercise the condition most of the time -- hopefully clocks going back is very rare.
