### PR TITLE
Delegation: eliminate usage of AST from generics creation

### LINKED ISSUE #153433: [ICE]: duplicate copy of DefId in lctx.children
auto-reduced (treereduce-rust):
````rust
fn main() {
    fn foo<const N: dyn for<'a> Foo>() {}
    reuse foo;
}

````

original:
````rust
#![feature(fn_delegation)]
fn main() {
    trait Foo {}
    fn foo<const N:  dyn for<'a> Foo>() {}
    reuse foo;
}

````

Version information
````
rustc 1.96.0-nightly (b90dc1e59 2026-03-04)
binary: rustc
commit-hash: b90dc1e597db0bbc0cab0eccb39747b1a9d7e607
commit-date: 2026-03-04
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/b90dc1e597db0bbc0cab0eccb39747b1a9d7e607/compiler/rustc_ast_lowering/src/item.rs#L59-L71

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0428]: the name `foo` is defined multiple times
 --> /tmp/icemaker_global_tempdir.Ga6lCnolTuPb/rustc_testrunner_tmpdir_reporting.2qQadq94BiHG/mvce.rs:3:5
  |
2 |     fn foo<const N: dyn for<'a> Foo>() {}
  |     ---------------------------------- previous definition of the value `foo` here
3 |     reuse foo;
  |     ^^^^^^^^^^ `foo` redefined here
  |
  = note: `foo` must be defined only once in the value namespace of this block

error[E0405]: cannot find trait `Foo` in this scope
 --> /tmp/icemaker_global_tempdir.Ga6lCnolTuPb/rustc_testrunner_tmpdir_reporting.2qQadq94BiHG/mvce.rs:2:33
  |
2 |     fn foo<const N: dyn for<'a> Foo>() {}
  |                                 ^^^ not found in this scope

error[E0658]: functions delegation is not yet fully implemented
 --> /tmp/icemaker_global_tempdir.Ga6lCnolTuPb/rustc_testrunner_tmpdir_reporting.2qQadq94BiHG/mvce.rs:3:5
  |
3 |     reuse foo;
  |     ^^^^^^^^^^
  |
  = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
  = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
  = note: this compiler was built on 2026-03-04; consider upgrading it if it is out of date


thread 'rustc' (2500919) panicked at /rustc-dev/b90dc1e597db0bbc0cab0eccb39747b1a9d7e607/compiler/rustc_ast_lowering/src/item.rs:65:13:
duplicate copy of DefId(0:6 ~ mvce[50a2]::main::foo::'a) in lctx.children
stack backtrace:
   0:     0x7fd17c55b73b - <<std[82796cbe7e14e686]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[723ec164f49f73a3]::fmt::Display>::fmt
   1:     0x7fd17cc22948 - core[723ec164f49f73a3]::fmt::write
   2:     0x7fd17c572746 - <std[82796cbe7e14e686]::sys::stdio::unix::Stderr as std[82796cbe7e14e686]::io::Write>::write_fmt
   3:     0x7fd17c531818 - std[82796cbe7e14e686]::panicking::default_hook::{closure#0}
   4:     0x7fd17c54eba3 - std[82796cbe7e14e686]::panicking::default_hook
   5:     0x7fd17b53866c - std[82796cbe7e14e686]::panicking::update_hook::<alloc[774c2fc5b8157a70]::boxed::Box<rustc_driver_impl[cc40153740e5fbc5]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7fd17c54ee82 - std[82796cbe7e14e686]::panicking::panic_with_hook
   7:     0x7fd17c5318d8 - std[82796cbe7e14e686]::panicking::panic_handler::{closure#0}
   8:     0x7fd17c528609 - std[82796cbe7e14e686]::sys::backtrace::__rust_end_short_backtrace::<std[82796cbe7e14e686]::panicking::panic_handler::{closure#0}, !>
   9:     0x7fd17c53333d - __rustc[eda097aff079559a]::rust_begin_unwind
  10:     0x7fd17911c61c - core[723ec164f49f73a3]::panicking::panic_fmt
  11:     0x7fd17d3df342 - <rustc_ast_lowering[734997e02f9e6df7]::item::ItemLowerer>::lower_node
  12:     0x7fd17d3d63a7 - rustc_ast_lowering[734997e02f9e6df7]::lower_to_hir
  13:     0x7fd17de8a6e8 - rustc_query_impl[eb5d4e66a16195f6]::query_impl::hir_crate::invoke_provider_fn::__rust_begin_short_backtrace
  14:     0x7fd17de895c4 - rustc_query_impl[eb5d4e66a16195f6]::execution::try_execute_query::<rustc_middle[9b0503ad92008f82]::query::caches::SingleCache<rustc_middle[9b0503ad92008f82]::query::erase::ErasedData<[u8; 8usize]>>, false>
  15:     0x7fd17de8904f - rustc_query_impl[eb5d4e66a16195f6]::query_impl::hir_crate::execute_query_non_incr::__rust_end_short_backtrace
  16:     0x7fd17cd472c3 - rustc_query_impl[eb5d4e66a16195f6]::query_impl::opt_hir_owner_nodes::invoke_provider_fn::__rust_begin_short_backtrace
  17:     0x7fd17cd4648a - rustc_query_impl[eb5d4e66a16195f6]::execution::try_execute_query::<rustc_data_structures[b07b151140ce4279]::vec_cache::VecCache<rustc_span[da1975f195527d0f]::def_id::LocalDefId, rustc_middle[9b0503ad92008f82]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[9b0503ad92008f82]::dep_graph::graph::DepNodeIndex>, false>
  18:     0x7fd17cd46105 - rustc_query_impl[eb5d4e66a16195f6]::query_impl::opt_hir_owner_nodes::execute_query_non_incr::__rust_end_short_backtrace
  19:     0x7fd17d53ffe6 - <rustc_middle[9b0503ad92008f82]::ty::context::TyCtxt>::hir_owner_node
  20:     0x7fd17de8fc91 - rustc_middle[9b0503ad92008f82]::hir::map::hir_crate_items
  21:     0x7fd17de8b2b1 - rustc_query_impl[eb5d4e66a16195f6]::query_impl::hir_crate_items::invoke_provider_fn::__rust_begin_short_backtrace
  22:     0x7fd17de895c4 - rustc_query_impl[eb5d4e66a16195f6]::execution::try_execute_query::<rustc_middle[9b0503ad92008f82]::query::caches::SingleCache<rustc_middle[9b0503ad92008f82]::query::erase::ErasedData<[u8; 8usize]>>, false>
  23:     0x7fd17de88dcf - rustc_query_impl[eb5d4e66a16195f6]::query_impl::hir_crate_items::execute_query_non_incr::__rust_end_short_backtrace
  24:     0x7fd17cd42dd8 - rustc_interface[5358b22c06b9f13b]::passes::analysis
  25:     0x7fd17de8835c - rustc_query_impl[eb5d4e66a16195f6]::execution::try_execute_query::<rustc_middle[9b0503ad92008f82]::query::caches::SingleCache<rustc_middle[9b0503ad92008f82]::query::erase::ErasedData<[u8; 0usize]>>, false>
  26:     0x7fd17de880bb - rustc_query_impl[eb5d4e66a16195f6]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
  27:     0x7fd17de5bdad - rustc_interface[5358b22c06b9f13b]::interface::run_compiler::<(), rustc_driver_impl[cc40153740e5fbc5]::run_compiler::{closure#0}>::{closure#1}
  28:     0x7fd17de322be - std[82796cbe7e14e686]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5358b22c06b9f13b]::util::run_in_thread_with_globals<rustc_interface[5358b22c06b9f13b]::util::run_in_thread_pool_with_globals<rustc_interface[5358b22c06b9f13b]::interface::run_compiler<(), rustc_driver_impl[cc40153740e5fbc5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  29:     0x7fd17de32920 - <std[82796cbe7e14e686]::thread::lifecycle::spawn_unchecked<rustc_interface[5358b22c06b9f13b]::util::run_in_thread_with_globals<rustc_interface[5358b22c06b9f13b]::util::run_in_thread_pool_with_globals<rustc_interface[5358b22c06b9f13b]::interface::run_compiler<(), rustc_driver_impl[cc40153740e5fbc5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[723ec164f49f73a3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7fd17de337ac - <std[82796cbe7e14e686]::sys::thread::unix::Thread>::new::thread_start
  31:     0x7fd1778a098b - <unknown>
  32:     0x7fd177924a0c - <unknown>
  33:                0x0 - <unknown>

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (b90dc1e59 2026-03-04) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [opt_hir_owner_nodes] getting HIR owner items in ``
#2 [hir_crate_items] getting HIR crate items
#3 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0405, E0428, E0658.
For more information about an error, try `rustc --explain E0405`.

```

</p>
</details>

@rustbot label +F-fn_delegation

### LINKED ISSUE #153499: [ICE]: `adding a def'n for node-id NodeId(35) and def kind LifetimeParam but a previous def'n exists`
snippet:
````rust
trait Trait<'a, T, const F: fn(&CStr) -> usize> {
    fn foo<'x: 'x, A, B>(&self) {}
}

reuse Trait::foo;

````

Version information
````
rustc 1.96.0-nightly (f82485388 2026-03-06)
binary: rustc
commit-hash: f82485388963286763f8c8a9261ac227627f6a18
commit-date: 2026-03-06
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/f82485388963286763f8c8a9261ac227627f6a18/compiler/rustc_ast_lowering/src/lib.rs#L586-L598

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find type `CStr` in this scope
 --> /tmp/icemaker_global_tempdir.6SGfY0f9qCPf/rustc_testrunner_tmpdir_reporting.EEKipKas9tub/mvce.rs:1:33
  |
1 | trait Trait<'a, T, const F: fn(&CStr) -> usize> {
  |                                 ^^^^ not found in this scope
  |
help: consider importing this struct
  |
1 + use std::ffi::CStr;
  |

error[E0658]: functions delegation is not yet fully implemented
 --> /tmp/icemaker_global_tempdir.6SGfY0f9qCPf/rustc_testrunner_tmpdir_reporting.EEKipKas9tub/mvce.rs:5:1
  |
5 | reuse Trait::foo;
  | ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
  = help: add `#![feature(fn_delegation)]` to the crate attributes to enable
  = note: this compiler was built on 2026-03-06; consider upgrading it if it is out of date


thread 'rustc' (3547296) panicked at /rustc-dev/f82485388963286763f8c8a9261ac227627f6a18/compiler/rustc_ast_lowering/src/lib.rs:592:9:
adding a def'n for node-id NodeId(35) and def kind LifetimeParam but a previous def'n exists: DefKey { parent: Some(DefIndex(3)), disambiguated_data: DisambiguatedDefPathData { data: DesugaredAnonymousLifetime, disambiguator: 0 } }
stack backtrace:
   0:     0x7fb408f5df6b - <<std[1ac9ec7f151dc343]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[2185e438fa60127]::fmt::Display>::fmt
   1:     0x7fb409622a08 - core[2185e438fa60127]::fmt::write
   2:     0x7fb408f74f76 - <std[1ac9ec7f151dc343]::sys::stdio::unix::Stderr as std[1ac9ec7f151dc343]::io::Write>::write_fmt
   3:     0x7fb408f34058 - std[1ac9ec7f151dc343]::panicking::default_hook::{closure#0}
   4:     0x7fb408f513e3 - std[1ac9ec7f151dc343]::panicking::default_hook
   5:     0x7fb407f37e4c - std[1ac9ec7f151dc343]::panicking::update_hook::<alloc[1b3f84b8c09c25b1]::boxed::Box<rustc_driver_impl[6e789f234d303bfb]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7fb408f516c2 - std[1ac9ec7f151dc343]::panicking::panic_with_hook
   7:     0x7fb408f34118 - std[1ac9ec7f151dc343]::panicking::panic_handler::{closure#0}
   8:     0x7fb408f28669 - std[1ac9ec7f151dc343]::sys::backtrace::__rust_end_short_backtrace::<std[1ac9ec7f151dc343]::panicking::panic_handler::{closure#0}, !>
   9:     0x7fb408f35b7d - __rustc[3c4f6ba47a7fa14c]::rust_begin_unwind
  10:     0x7fb405b4543c - core[2185e438fa60127]::panicking::panic_fmt
  11:     0x7fb409e54aad - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lifetime_res_to_generic_param
  12:     0x7fb409e2a134 - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lower_lifetime_binder::{closure#0}
  13:     0x7fb40987c22f - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lower_ty
  14:     0x7fb409e21fd8 - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lower_generic_param
  15:     0x7fb407a5dfbe - <<rustc_ast_lowering[b95fdc7cdede6051]::delegation::generics::HirOrAstGenerics>::into_hir_generics::{closure#0} as core[2185e438fa60127]::ops::function::FnOnce<(&mut rustc_ast[f8ca33bbd9947925]::ast::Generics,)>>::call_once
  16:     0x7fb407a450bd - <rustc_ast_lowering[b95fdc7cdede6051]::delegation::generics::HirOrAstGenerics>::into_hir_generics
  17:     0x7fb407a400c1 - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lower_delegation
  18:     0x7fb409e35dd5 - <rustc_ast_lowering[b95fdc7cdede6051]::LoweringContext>::lower_item_kind
  19:     0x7fb409e43976 - <rustc_ast_lowering[b95fdc7cdede6051]::item::ItemLowerer>::lower_node
  20:     0x7fb409e42327 - rustc_ast_lowering[b95fdc7cdede6051]::lower_to_hir
  21:     0x7fb40a884a28 - rustc_query_impl[234cac1489f93c02]::query_impl::hir_crate::invoke_provider_fn::__rust_begin_short_backtrace
  22:     0x7fb40a883944 - rustc_query_impl[234cac1489f93c02]::execution::try_execute_query::<rustc_middle[6c1cd5853b8c3360]::query::caches::SingleCache<rustc_middle[6c1cd5853b8c3360]::query::erase::ErasedData<[u8; 8usize]>>, false>
  23:     0x7fb40a8833cf - rustc_query_impl[234cac1489f93c02]::query_impl::hir_crate::execute_query_non_incr::__rust_end_short_backtrace
  24:     0x7fb4096c0c83 - rustc_query_impl[234cac1489f93c02]::query_impl::opt_hir_owner_nodes::invoke_provider_fn::__rust_begin_short_backtrace
  25:     0x7fb4096bfe4a - rustc_query_impl[234cac1489f93c02]::execution::try_execute_query::<rustc_data_structures[b1d728af8bd319df]::vec_cache::VecCache<rustc_span[bde3ed91d4975fd3]::def_id::LocalDefId, rustc_middle[6c1cd5853b8c3360]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[6c1cd5853b8c3360]::dep_graph::graph::DepNodeIndex>, false>
  26:     0x7fb4096bfac5 - rustc_query_impl[234cac1489f93c02]::query_impl::opt_hir_owner_nodes::execute_query_non_incr::__rust_end_short_backtrace
  27:     0x7fb409f6fda6 - <rustc_middle[6c1cd5853b8c3360]::ty::context::TyCtxt>::hir_owner_node
  28:     0x7fb40a88a1d1 - rustc_middle[6c1cd5853b8c3360]::hir::map::hir_crate_items
  29:     0x7fb40a88589d - rustc_query_impl[234cac1489f93c02]::query_impl::hir_crate_items::invoke_provider_fn::__rust_begin_short_backtrace
  30:     0x7fb40a883944 - rustc_query_impl[234cac1489f93c02]::execution::try_execute_query::<rustc_middle[6c1cd5853b8c3360]::query::caches::SingleCache<rustc_middle[6c1cd5853b8c3360]::query::erase::ErasedData<[u8; 8usize]>>, false>
  31:     0x7fb40a88430b - rustc_query_impl[234cac1489f93c02]::query_impl::hir_crate_items::execute_query_non_incr::__rust_end_short_backtrace
  32:     0x7fb4096bc6e2 - rustc_interface[c926bcc183cff181]::passes::analysis
  33:     0x7fb40a882760 - rustc_query_impl[234cac1489f93c02]::execution::try_execute_query::<rustc_middle[6c1cd5853b8c3360]::query::caches::SingleCache<rustc_middle[6c1cd5853b8c3360]::query::erase::ErasedData<[u8; 0usize]>>, false>
  34:     0x7fb40a882447 - rustc_query_impl[234cac1489f93c02]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
  35:     0x7fb40a83da6d - rustc_interface[c926bcc183cff181]::interface::run_compiler::<(), rustc_driver_impl[6e789f234d303bfb]::run_compiler::{closure#0}>::{closure#1}
  36:     0x7fb40a86613e - std[1ac9ec7f151dc343]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[c926bcc183cff181]::util::run_in_thread_with_globals<rustc_interface[c926bcc183cff181]::util::run_in_thread_pool_with_globals<rustc_interface[c926bcc183cff181]::interface::run_compiler<(), rustc_driver_impl[6e789f234d303bfb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x7fb40a8669e0 - <std[1ac9ec7f151dc343]::thread::lifecycle::spawn_unchecked<rustc_interface[c926bcc183cff181]::util::run_in_thread_with_globals<rustc_interface[c926bcc183cff181]::util::run_in_thread_pool_with_globals<rustc_interface[c926bcc183cff181]::interface::run_compiler<(), rustc_driver_impl[6e789f234d303bfb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[2185e438fa60127]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7fb40a86786c - <std[1ac9ec7f151dc343]::sys::thread::unix::Thread>::new::thread_start
  39:     0x7fb4042a598b - <unknown>
  40:     0x7fb404329a0c - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (f82485388 2026-03-06) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [opt_hir_owner_nodes] getting HIR owner items in ``
#2 [hir_crate_items] getting HIR crate items
#3 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0425, E0658.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by aerooneqq**
This PR eliminates all interaction with AST during creation of generics, then it supports proper const param types propagation. Fixes rust-lang/rust#153433. Fixes rust-lang/rust#153499. Part of rust-lang/rust#118212.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -3765,12 +3765,18 @@ pub struct DelegationGenerics {
...
     Input(usize),
     // Place generics info here, as we always specify output type for delegations.
     Output(&'hir DelegationGenerics),
 }
 
+#[derive(Debug, Clone, Copy, PartialEq, Eq, HashStable_Generic)]
+pub enum InferDelegation<'hir> {
+    DefId(DefId),
+    Sig(DefId, InferDelegationSig<'hir>),
+}
```
Comment (petrochenkov) [inline compiler/rustc_hir/src/hir.rs:3774]: Need comments explaining what the variants mean / when they are used.

File: compiler/rustc_ast_lowering/src/delegation/generics.rs [hunk 2]
```diff
@@ -26,24 +24,23 @@ pub(super) enum DelegationGenerics<T> {
     TraitImpl(Option<T>, bool /* Has user-specified args */),
 }
 
-/// Used for storing either AST generics or their lowered HIR version. Firstly we obtain
-/// AST generics either from local function from AST index or from external function
-/// through `tcx`. Next, at some point of generics processing we need to lower those
-/// generics to HIR, for this purpose we use `into_hir_generics` that lowers AST generics
-/// and replaces Ast variant with Hir. Such approach is useful as we can call this method
+/// Used for storing either ty generics or their lowered HIR version. Firstly we obtain
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation/generics.rs]:
```suggestion
/// Used for storing either ty generics or their uplifted HIR version. First we obtain
```
(In other places too.)

- Getting from lower level IR to higher level IR is uplifting.
- https://www.merriam-webster.com/grammar/first-or-firstly

File: compiler/rustc_ast_lowering/src/delegation/generics.rs [hunk 3]
```diff
@@ -268,29 +248,28 @@ impl<'hir, R: ResolverAstLoweringExt<'hir>> LoweringContext<'_, 'hir, R> {
...
-                    DelegationGenerics::SelfAndUserSpecified(parent_generics_factory(self, true))
+                    // Take only first Self parameter, it is trait so Self must be present.
+                    let params = self.generic_params(sig_parent).map(|i| i.take(1).collect());
+                    DelegationGenerics::SelfAndUserSpecified(params)
                 } else {
                     DelegationGenerics::UserSpecified
                 }
             } else {
-                DelegationGenerics::Default(parent_generics_factory(self, false))
+                let skip_self = !generate_self as usize;
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation/generics.rs]:
```suggestion
                let skip_self = usize::from(!generate_self);
```

File: compiler/rustc_ast_lowering/src/delegation/generics.rs [hunk 4]
```diff
@@ -473,116 +462,8 @@ impl<'hir, R: ResolverAstLoweringExt<'hir>> LoweringContext<'_, 'hir, R> {
...
-                    kind: GenericParamKind::Type { default: None },
-                    colon_span: None,
-                },
-            );
-        }
-
-        generics
+    fn generic_params(&mut self, id: DefId) -> Option<impl Iterator<Item = ty::GenericParamDef>> {
+        let params = &self.tcx.generics_of(id).own_params;
+        (!params.is_empty()).then(|| params.iter().cloned())
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation/generics.rs]: Why do you need to clone and collect the parameters?
You could probably keep the `&'tcx [GenericParam]` or its sub-slices directly.

File: compiler/rustc_ast_lowering/src/delegation/generics.rs [hunk 5]
```diff
@@ -473,116 +457,8 @@ impl<'hir, R: ResolverAstLoweringExt<'hir>> LoweringContext<'_, 'hir, R> {
...
-                    bounds: vec![],
-                    is_placeholder: false,
-                    kind: GenericParamKind::Type { default: None },
-                    colon_span: None,
-                },
-            );
-        }
-
-        generics
+    fn generic_params(&mut self, id: DefId) -> Option<&'hir [ty::GenericParamDef]> {
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation/generics.rs]:
```suggestion
    fn generic_params(&mut self, id: DefId) -> &'hir [ty::GenericParamDef] {
```
I don't think the `Option` is needed here, the code processing the parameters should be able to process empty parameter lists inside `Some` correctly, so we can simply return the empty lists directly.
(After that the function can be inlined and removed.)

Comment (aerooneqq) [reply compiler/rustc_ast_lowering/src/delegation/generics.rs]: There were minor logic changes after Options removal, can create separate PR if needed.

Comment (petrochenkov) [reply compiler/rustc_ast_lowering/src/delegation/generics.rs]: Looks good as is, no need for a separate PR.

File: compiler/rustc_hir/src/hir.rs [hunk 6]
```diff
@@ -643,13 +638,15 @@ pub struct GenericArgs<'hir> {
 }
 
 impl<'hir> GenericArgs<'hir> {
-    pub const fn none() -> Self {
-        Self {
+    pub const fn none() -> &'hir GenericArgs<'hir> {
```
Comment (petrochenkov) [inline compiler/rustc_hir/src/hir.rs]:
```suggestion
    pub const NONE: &GenericArgs<'_> = ...
```
Can directly use an associated constant here.

File: compiler/rustc_ast_lowering/src/delegation/generics.rs [hunk 7]
```diff
@@ -268,38 +242,37 @@ impl<'hir, R: ResolverAstLoweringExt<'hir>> LoweringContext<'_, 'hir, R> {
...
                     DelegationGenerics::UserSpecified
                 }
             } else {
-                DelegationGenerics::Default(parent_generics_factory(self, false))
+                let skip_self = usize::from(!generate_self);
+                DelegationGenerics::Default(&sig_parent_params[skip_self..])
             }
         } else {
-            DelegationGenerics::Default(None)
+            DelegationGenerics::<&'hir [ty::GenericParamDef]>::Default(&[])
```
Comment (petrochenkov) [inline compiler/rustc_ast_lowering/src/delegation/generics.rs:269]:
```suggestion
            DelegationGenerics::Default(&[])
```
I'm surprised that type inference doesn't work here, considering that the other if-else branches provide the necessary type.
