### PR TITLE
Stabilize `let else`

### LINKED ISSUE #87335: Tracking Issue for RFC 3137: let-else statements
This is a tracking issue for [RFC 3137: let-else statements](https://github.com/rust-lang/rfcs/pull/3137).
The feature gate for the issue is `#![feature(let_else)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (https://github.com/rust-lang/rust/pull/87688)
- [ ] Adjust documentation: reference PR at https://github.com/rust-lang/reference/pull/1156
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/93628

[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Unresolved Questions

- [x] **Readability in practice**: Will `let ... else { ... };` be clear enough to humans in practical code, or will some introducer syntax be desirable?
- [x] **Conflicts with if-let-chains**: Does this conflict too much with the if-let-chains RFC or vice-versa? Neither this feature nor that feature should be stabilized without considering the other.
- [x] **Amount of special cases**: Are there too many special-case interactions with other features?
- [x] **Grammar clarity**: Does the grammar need to be clarified? This RFC has some slightly unusual grammar requirements.

### Implementation history

- https://github.com/rust-lang/rust/pull/87688 implemented let-else.
- https://github.com/rust-lang/rust/pull/89841 adds support for type annotations in let-else (`let x: Type = ... else { ... }`)

### PR DESCRIPTION
**Pull request by est31**
:tada:  **Stabilizes the `let else` feature, added by [RFC 3137](https://github.com/rust-lang/rfcs/pull/3137).** :tada: 

Reference PR: https://github.com/rust-lang/reference/pull/1156

closes #87335 (`let else` tracking issue)

FCP: https://github.com/rust-lang/rust/pull/93628#issuecomment-1029383585

----------
 
### Summary

The feature allows refutable patterns in `let` statements if the expression is
followed by a diverging `else`:

```Rust
fn get_count_item(s: &str) -> (u64, &str) {
    let mut it = s.split(' ');
    let (Some(count_str), Some(item)) = (it.next(), it.next()) else {
        panic!("Can't segment count item pair: '{s}'");
    };
    let Ok(count) = u64::from_str(count_str) else {
        panic!("Can't parse integer: '{count_str}'");
    };
    (count, item)
}
assert_eq!(get_count_item("3 chairs"), (3, "chairs"));
```

### Differences from the RFC / Desugaring

Outside of desugaring I'm not aware of any differences between the implementation and the RFC. The chosen desugaring has been changed from the RFC's [original](https://rust-lang.github.io/rfcs/3137-let-else.html#reference-level-explanations). You can read a detailed discussion of the implementation history of it in @cormacrelf 's [summary](https://github.com/rust-lang/rust/pull/93628#issuecomment-1041143670) in this thread, as well as the [followup](https://github.com/rust-lang/rust/pull/93628#issuecomment-1046598419). Since that followup, further changes have happened to the desugaring, in #98574, #99518, #99954. The later changes were mostly about the drop order: On match, temporaries drop in the same order as they would for a `let` declaration. On mismatch, temporaries drop before the `else` block.

### Test cases

In chronological order as they were merged.

Added by df9a2e0687895731e12f4a2651e8d70acd08872d (#87688):

* [`ui/pattern/usefulness/top-level-alternation.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/pattern/usefulness/top-level-alternation.rs) to ensure the unreachable pattern lint visits patterns inside `let else`.

Added by 5b95df4bdc330f34213812ad65cae86ced90d80c (#87688):

* [`ui/let-else/let-else-bool-binop-init.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-bool-binop-init.rs) to ensure that no lazy boolean expressions (using `&&` or `||`) are allowed in the expression, as the RFC mandates.
* [`ui/let-else/let-else-brace-before-else.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-brace-before-else.rs) to ensure that no `}` directly preceding the `else` is allowed in the expression, as the RFC mandates.
* [`ui/let-else/let-else-check.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-check.rs) to ensure that `#[allow(...)]` attributes added to the entire `let` statement apply for the `else` block.
* [`ui/let-else/let-else-irrefutable.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-irrefutable.rs) to ensure that the `irrefutable_let_patterns` lint fires.
* [`ui/let-else/let-else-missing-semicolon.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-missing-semicolon.rs) to ensure the presence of semicolons at the end of the `let` statement.
* [`ui/let-else/let-else-non-diverging.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-non-diverging.rs) to ensure the `else` block diverges.
* [`ui/let-else/let-else-run-pass.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-run-pass.rs) to ensure the feature works in some simple test case settings.
* [`ui/let-else/let-else-scope.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-scope.rs) to ensure the bindings created by the outer `let` expression are not available in the `else` block of it.

Added by bf7c32a4477a76bfd18fdcd8f45a939cbed82d34 (#89965):

* [`ui/let-else/issue-89960.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/issue-89960.rs) as a regression test for the ICE-on-error bug #89960 . Later in 102b9125e1cefbb8ed8408d2db3f9f7d5afddbf0 this got removed in favour of more comprehensive tests.

Added by 856541963ce95ef4f7d4a81784bb5002ccf63c93 (#89974):

* [`ui/let-else/let-else-if.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-if.rs) to test for the improved error message that points out that `let else if` is not possible.

Added by 9b45713b6c1775f0103a1ebee6ab7c6d9b781a21:

* [`ui/let-else/let-else-allow-unused.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-allow-unused.rs) as a regression test for #89807, to ensure that `#[allow(...)]` attributes added to the entire `let` statement apply for bindings created by the `let else` pattern.

Added by 61bcd8d3075471b3867428788c49f54fffe53f52 (#89841):

* [`ui/let-else/let-else-non-copy.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-non-copy.rs) to ensure that a copy is performed out of non-copy wrapper types. This mirrors `if let` behaviour. The test case bases on rustc internal changes originally meant for #89933 but then removed from the PR due to the error prior to the improvements of #89841.
* [`ui/let-else/let-else-source-expr-nomove-pass.rs `](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-source-expr-nomove-pass.rs) to ensure that while there is a move of the binding in the successful case, the `else` case can still access the non-matching value. This mirrors `if let` behaviour.

Added by 102b9125e1cefbb8ed8408d2db3f9f7d5afddbf0 (#89841):

* [`ui/let-else/let-else-ref-bindings.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-ref-bindings.rs) and [`ui/let-else/let-else-ref-bindings-pass.rs `](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-ref-bindings-pass.rs) to check `ref` and `ref mut` keywords in the pattern work correctly and error when needed.

Added by 2715c5f984fda7faa156d1c9cf91aa4934f0e00f (#89841):

* Match ergonomic tests adapted from the `rfc2005` test suite.

Added by fec8a507a27de1b08a0b95592dc8ec93bf0a321a (#89841):

* [`ui/let-else/let-else-deref-coercion-annotated.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-deref-coercion-annotated.rs) and [`ui/let-else/let-else-deref-coercion.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-deref-coercion.rs) to check deref coercions.

#### Added since this stabilization report was originally written (2022-02-09)

Added by 76ea56667703ac06689ff1d6fba5d170fa7392a7 (#94211):

* [`ui/let-else/let-else-destructuring.rs`](https://github.com/rust-lang/rust/blob/1.63.0/src/test/ui/let-else/let-else-destructuring.rs) to give a nice error message if an user tries to do an assignment with a (possibly refutable) pattern and an `else` block, like asked for in #93995.

Added by e7730dcb7eb29a10ee73f269f4dc6e9d606db0da (#94208):

* [`ui/let-else/let-else-allow-in-expr.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-allow-in-expr.rs) to test whether `#[allow(unused_variables)]` works in the expr, as well as its non presence, as well as putting it on the entire `let else` *affects* the expr, too. This was adding a missing test as pointed out by the stabilization report.
* Expansion of `ui/let-else/let-else-allow-unused.rs` and `ui/let-else/let-else-check.rs` to ensure that non-presence of `#[allow(unused)]` does issue the unused lint. This was adding a missing test case as pointed out by the stabilization report.

Added by 5bd71063b3810d977aa376d1e6dd7cec359330cc (#94208):

* [`ui/let-else/let-else-slicing-error.rs`](https://github.com/rust-lang/rust/blob/1.61.0/src/test/ui/let-else/let-else-slicing-error.rs), a regression test for #92069, which got fixed without addition of a regression test. This resolves a missing test as pointed out by the stabilization report.

Added by 5374688e1d8cbcff7d1d14bb34e38fe6fe7c233e (#98574):

* [`src/test/ui/async-await/async-await-let-else.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/async-await/async-await-let-else.rs) to test the interaction of async/await with `let else`

Added by 6c529ded8674b89c46052da92399227c3b764c6a (#98574):

* [`src/test/ui/let-else/let-else-temporary-lifetime.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-temporary-lifetime.rs) as a (partial) regression test for #98672

Added by 9b566401068cb8450912f6ab48f3d0e60f5cb482 (#99518):

* [`src/test/ui/let-else/let-else-temp-borrowck.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-temporary-lifetime.rs) as a regression test for #93951
* Extension of `src/test/ui/let-else/let-else-temporary-lifetime.rs` to include a partial regression test for #98672 (especially regarding `else` drop order)

Added by baf9a7cb57120ec1411196214fd0d1c33fb18bf6 (#99518):

* Extension of `src/test/ui/let-else/let-else-temporary-lifetime.rs` to include a partial regression test for #93951, similar to `let-else-temp-borrowck.rs`

Added by 60be2de8b7b8a1c4eee7e065b8cef38ea629a6a3 (#99518):

* Extension of `src/test/ui/let-else/let-else-temporary-lifetime.rs` to include a program that can now be compiled thanks to borrow checker implications of #99518

Added by 47a7a91c969ed2edd12c674ca05c1baf867f6f6f (#100132):

* [`src/test/ui/let-else/issue-100103.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/issue-100103.rs), as a regression test for #100103, to ensure that there is no ICE when doing `Err(...)?` inside else blocks.

Added by e3c5bd617d040b5ee0bc79e6e7f01772adce791b (#100443):

* [`src/test/ui/let-else/let-else-then-diverge.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-then-diverge.rs), to verify that there is no unreachable code error with the current desugaring.

Added by 981852677c531d52f701b870bb27b45668a44d52 (#100443):

* [`src/test/ui/let-else/issue-94176.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/issue-94176.rs), to make sure that a correct span is emitted for a missing trailing expression error. Regression test for #94176.

Added by e182d12a8493b40a557394325a3a713b6528de60 (#100434):

* [src/test/ui/unpretty/pretty-let-else.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/unpretty/pretty-let-else.rs), as a regression test to ensure pretty printing works for `let else` (this bug surfaced in many different ways)

Added by e26285603ca8b83b9d06e56f74e10e3d410553ff (#99954):

* [`src/test/ui/let-else/let-else-temporary-lifetime.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-temporary-lifetime.rs) extended to contain & borrows as well, as this was identified as an earlier issue with the desugaring: https://github.com/rust-lang/rust/issues/98672#issuecomment-1200196921

Added by 2d8460ef43d902f34ba2133fe38f66ee8d2fdafc (#99291):

* [`src/test/ui/let-else/let-else-drop-order.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-drop-order.rs) a matrix based test for various drop order behaviour of `let else`. Especially, it verifies equality of `let` and `let else` drop orders, [resolving](https://github.com/rust-lang/rust/pull/93628#issuecomment-1238498468) a [stabilization blocker](https://github.com/rust-lang/rust/pull/93628#issuecomment-1055738523).

Added by 1b87ce0d4092045728c1c68282769d555706f273 (#101410):

* Edit to `src/test/ui/let-else/let-else-temporary-lifetime.rs` to add the `-Zvalidate-mir` flag, as a regression test for #99228

Added by af591ebe4d0cf2097a5fdc0bb710442d0f2e7876 (#101410):

* [`src/test/ui/let-else/issue-99975.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/issue-99975.rs) as a regression test for the ICE #99975.

Added by this PR:

* `ui/let-else/let-else.rs`, a simple run-pass check, similar to `ui/let-else/let-else-run-pass.rs`.

### Things not currently tested

* ~~The `#[allow(...)]` tests check whether allow works, but they don't check whether the non-presence of allow causes a lint to fire.~~ → *test added by e7730dcb7eb29a10ee73f269f4dc6e9d606db0da*
* ~~There is no `#[allow(...)]` test for the expression, as there are tests for the pattern and the else block.~~ → *test added by e7730dcb7eb29a10ee73f269f4dc6e9d606db0da*
* ~~`let-else-brace-before-else.rs` forbids the `let ... = {} else {}` pattern and there is a rustfix to obtain `let ... = ({}) else {}`. I'm not sure whether the `.fixed` files are checked by the tooling that they compile. But if there is no such check, it would be neat to make sure that `let ... = ({}) else {}` compiles.~~ → *test added by e7730dcb7eb29a10ee73f269f4dc6e9d606db0da*
* ~~#92069 got closed as fixed, but no regression test was added. Not sure it's worth to add one.~~ → *test added by 5bd71063b3810d977aa376d1e6dd7cec359330cc*
* ~~consistency between `let else` and `if let` regarding lifetimes and drop order: https://github.com/rust-lang/rust/pull/93628#issuecomment-1055738523~~ → *test added by 2d8460ef43d902f34ba2133fe38f66ee8d2fdafc*

Edit: they are all tested now.

### Possible future work / Refutable destructuring assignments

[RFC 2909](https://rust-lang.github.io/rfcs/2909-destructuring-assignment.html) specifies destructuring assignment, allowing statements like `FooBar { a, b, c } = foo();`.
As it was stabilized, destructuring assignment only allows *irrefutable* patterns, which before the advent of `let else` were the only patterns that `let` supported.
So the combination of `let else` and destructuring assignments gives reason to think about extensions of the destructuring assignments feature that allow refutable patterns, discussed in #93995.

A naive mapping of `let else` to destructuring assignments in the form of `Some(v) = foo() else { ... };` might not be the ideal way. `let else` needs a diverging `else` clause as it introduces new bindings, while assignments have a default behaviour to fall back to if the pattern does not match, in the form of not performing the assignment. Thus, there is no good case to require divergence, or even an `else` clause at all, beyond the need for having *some* introducer syntax so that it is clear to readers that the assignment is not a given (enums and structs look similar). There are better candidates for introducer syntax however than an empty `else {}` clause, like `maybe` which could be added as a keyword on an edition boundary:

```Rust
let mut v = 0;
maybe Some(v) = foo(&v);
maybe Some(v) = foo(&v) else { bar() };
```

Further design discussion is left to an RFC, or the linked issue.

### CODE REVIEW

File: src/test/ui/pattern/usefulness/top-level-alternation.rs [hunk 1]
```diff
@@ -1,7 +1,7 @@
-#![feature(let_else)]
-
 #![deny(unreachable_patterns)]
 
+
+
```
Comment (joshtriplett) [inline src/test/ui/pattern/usefulness/top-level-alternation.rs:4]: I'm assuming the blank lines here and in various other tests are to avoid having to re-bless the tests?

That's fine for temporary purposes, but the final PR should go ahead and re-bless the tests rather than workign around it like this.

**Review by joshtriplett — CHANGES_REQUESTED** [review]

**Comment by joshtriplett** [comment]
This looks good to me; I'll start a T-lang FCP.

**Comment by joshtriplett** [comment]
Shall we stabilize `let else` syntax? We've had many demonstrated uses, including extensively throughout `rust-lang/rust`, we've seen the value of it, and there aren't any known issues with it.

@rfcot merge

**Comment by joshtriplett** [comment]
Shall we stabilize `let else` syntax? We've had many demonstrated uses, including extensively throughout `rust-lang/rust`, we've seen the value of it, and there aren't any known issues with it.

@rfcbot merge

**Comment by scottmcm** [comment]
@rfcbot concern not-while-rustfmt-breaks-on-it

I remembered it not formatting last I tried using it in rustc, and sure enough it still seems to fail when I try it in playground: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=350415c3adb74101bbdc002031976b70>

(There's enough people using rustfmt in CI that I think adding formatting support for it after stabilization would be impolite.)

File: src/test/ui/pattern/usefulness/top-level-alternation.rs (hunk 1 above)
Comment (est31) [reply src/test/ui/pattern/usefulness/top-level-alternation.rs:4]: > I'm assuming the blank lines here and in various other tests are to avoid having to re-bless the tests?

Yeah I didn't want to cause stderr churn. It's been suggested for an [earlier PR](https://github.com/rust-lang/rust/pull/88316#issuecomment-905796963) of mine that also touched the testsuite so I did the same here. If it's fine that I remove those lines, I'll do that instead.

**Comment by scottmcm** [comment]
> it's not modifying what was already there

I think that's my complaint.  I think it's clear that we'd *want* rustfmt to format it, but based on https://rust-lang.github.io/rfcs/2437-rustfmt-stability.html it'd need to be a new version to add formatting support for it if we did so after stabilization.  And I don't think that dance is worth it; it should just have formatting support in the release that stabilizes it.

**Comment by calebcartwright** [comment]
> it'd need to be a new version to add formatting support for it if we did so after stabilization. And I don't think that dance is worth it; it should just have formatting support in the release that stabilizes it

That's not the case actually.

rustfmt has always had leeway to make formatting changes for "new" syntax (we have to) until such time as the _formatting_ has actually been stabilized. We try very hard to only do this once, which is why the "first do no harm" pattern followed for syntax that's new to rustfmt.

I've never seen a case where stabilization of a feature was held up on rustfmt, and doing so would be a big mistake IMO. Throughout my time working on rustfmt it's often been an after thought where we weren't even aware of syntax changes until long after they'd been in use, and there's plenty of cases where rustfmt exhibits this same behavior on long-standing syntax (e.g. try adding comments between trait bounds).

I'd think that blocking feature stabilization on style guide + formatting stabilization would either greatly elongate the lead time for feature availability on stable, or create large amounts of friction on the rustfmt side between expediency (not wanting to block) and formatting stability + quality/correctness.

Also, and I say this as someone that spends a large chunk of my free time trying to maintain and improve rustfmt 😄, there's a non-zero subset of the Rust population that dislikes rustfmt and doesn't use it whatsoever. If I were one of those folks I think it would be extremely frustrating to not have access to a language feature on stable simply because of an optional tool I don't leverage.

**Comment by nikomatsakis** [comment]
On the topic of whether to block stability on rustfmt:

Ember has an interesting addition to their process. In their model, stabilization is not the "end point" for a feature, it's *one step* before the end. The final step is "recommended", and that stage is reached when the feature is documented and has good support for tooling. The goal is precisely to avoid the kind of "deadlock" that we've seen sometimes and that @calebcartwright is describing. Maybe we should consider adopting a similar strategy?

All of that said, when I used `let-else` on a project recently, it seemed to me that it was being formatted in the "expected" way. I didn't go through the effort to create torture tests. I really value how rustfmt takes whatever garbage I throw at it and makes something nice out of it -- I've gotten very used to just typing things without thinking about how it should look -- so I would definitely want let-else to continue in that tradition. 

(I almost wrote a 'recommended' stage into the initiative process, but I decided to simplify and avoid introducing too many new things at once.)

**Comment by nikomatsakis** [comment]
One thing I noticed from using let-else that I didn't expect:

At first, I was annoyed that I had to introduce a block in the "else" clause, since I wanted to basically write

```rust
let Some(foo) = bar else return;
```

and be very concise. But I found that actually I quite like the `{}` and the way that rustfmt puts that onto the next line:

```rust
let Some(foo) = bar else {
    return;
}
```

I found that this indentation made the else case stand out just a bit, which seemed good, because otherwise it would be easy to miss.

**Comment by nikomatsakis** [comment]
@rfcbot concern stabilization-report

Thanks for putting this PR together! I am generally favorable on stabilizing, but I would like to see a stabilization report (can't find the link just now...) In particular I would appreciate a write-up that summarizes the design ultimately implemented (especially if it changed since the RFC) and answers the [unresolved questions](https://github.com/rust-lang/rust/issues/87335#issuecomment-1029234347).

**Comment by calebcartwright** [comment]
> The final step is "recommended", and that stage is reached when the feature is documented and has good support for tooling. The goal is precisely to avoid the kind of "deadlock" that we've seen sometimes and that @calebcartwright is describing. Maybe we should consider adopting a similar strategy?

That type of progressive rollout/shades of grey approach would be helpful for rustfmt, but it's vastly different from the constraints we've been bounded by historically.

Once rustfmt starts rewriting some input `R` to some output `R1`, the formatting stability means that rustfmt is never supposed to subsequently start rewriting the previously formatted `R1` as some other `R2` (yes we've failed at this before, but that's a bug not a feature). Maddeningly, at least for me, this expectation gets applied across all channels including nightly since users developing on nightly, understandably, don't want to deal with formatting churn either. That's why we try to take a very conservative approach to adding the initial R->R1 reformatting because up until that point R has never been "correctly formatted".

So absent some such significant changing of process and/or constraints, incorporating rustfmt into the feature stabilization process would have significant, IMO undesirable, side effects and I suspect would be largely impractical.

We actually _are_ in a far better position than normal with `let else` because @camsteffen has been particularly helpful on the formatting side. However, I'd have grave concerns with this setting a precedent for gating feature stabilization on rustfmt moving forward.

**Comment by camsteffen** [comment]
@nikomatsakis FWIW I think rustfmt will allow ` else { .. };` on the same line if it fits. This would be consistent with if/else. See https://github.com/rust-dev-tools/fmt-rfcs/pull/165.

I feel I should note that in my usage I very often forget the required semicolon at the end (like @nikomatsakis did above). It seems inconsistent with `while`, `loop`, `if`/`else`.

**Comment by scottmcm** [comment]
Thanks for the extra context, @calebcartwright !  I was unaware of that, so will 

@rfcbot resolve not-while-rustfmt-breaks-on-it

(We had a helpful conversation in the lang team meeting about it to, and how the difference between "we leave whatever you wrote alone" and "we're actually formatting it" makes an important difference for a later change to "here's the official one".)

One additional question I have about it, then:

**Can we have the *body* of the block get formatted still?**

If I use a simpler example <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ccf2d2eae6c3c900055357ce0da94d05>, it would be nice to have the expressions inside the block get formatted as normal even if we have yet to decide on the official format for the `let`-`else` part and thus leave *that* layout alone.

**Comment by est31** [comment]
> I feel I should note that in my usage I very often forget the required semicolon at the end (like @nikomatsakis did above). It seems inconsistent with while, loop, if/else.

`let else` is closer to `let` than it is to those other patterns, probably closest to `let v = if let Pat(v) = expr { v } else { ...};`, which has a `;` at the end too.

**Comment by est31** [comment]
## Stabilization report

### Summary

The feature allows refutable patterns in `let` statements if the expression is
followed by a diverging `else`:

```Rust
fn get_count_item(s: &str) -> (u64, &str) {
    let mut it = s.split(' ');
    let (Some(count_str), Some(item)) = (it.next(), it.next()) else {
        panic!("Can't segment count item pair: '{s}'");
    };
    let Ok(count) = u64::from_str(count_str) else {
        panic!("Can't parse integer: '{count_str}'");
    };
    (count, item)
}
assert_eq!(get_count_item("3 chairs"), (3, "chairs"));
```

### Test cases

Added by df9a2e0687895731e12f4a2651e8d70acd08872d:

* [`ui/pattern/usefulness/top-level-alternation.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/pattern/usefulness/top-level-alternation.rs) to ensure the unreachable pattern lint visits patterns inside `let else`.

Added by 5b95df4bdc330f34213812ad65cae86ced90d80c:

* [`ui/let-else/let-else-bool-binop-init.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-bool-binop-init.rs) to ensure that no lazy boolean expressions (using `&&` or `||`) are allowed in the expression, as the RFC mandates.
* [`ui/let-else/let-else-brace-before-else.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-brace-before-else.rs) to ensure that no `}` directly preceding the `else` is allowed in the expression, as the RFC mandates.
* [`ui/let-else/let-else-check.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-check.rs) to ensure that `#[allow(...)]` attributes added to the entire `let` statement apply for the `else` block.
* [`ui/let-else/let-else-irrefutable.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-irrefutable.rs) to ensure that the `irrefutable_let_patterns` lint fires.
* [`ui/let-else/let-else-missing-semicolon.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-missing-semicolon.rs) to ensure the presence of semicolons at the end of the `let` statement.
* [`ui/let-else/let-else-non-diverging.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-non-diverging.rs) to ensure the `else` block diverges.
* [`ui/let-else/let-else-run-pass.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-run-pass.rs) to ensure the feature works in some simple test case settings.
* [`ui/let-else/let-else-scope.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-scope.rs) to ensure the bindings created by the outer `let` expression are not available in the `else` block of it.

Added by bf7c32a4477a76bfd18fdcd8f45a939cbed82d34:

* [`ui/let-else/issue-89960.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/issue-89960.rs) as a regression test for the ICE-on-error bug #89960 . Later in 102b9125e1cefbb8ed8408d2db3f9f7d5afddbf0 this got removed in favour of more comprehensive tests.

Added by 856541963ce95ef4f7d4a81784bb5002ccf63c93:

* [`ui/let-else/let-else-if.rs`](https://github.com/rust-lang/rust/blob/1.58.1/src/test/ui/let-else/let-else-if.rs) to test for the improved error message that points out that `let else if` is not possible.

Added by 9b45713b6c1775f0103a1ebee6ab7c6d9b781a21:

* [`ui/let-else/let-else-allow-unused.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-allow-unused.rs) as a regression test for #89807, to ensure that `#[allow(...)]` attributes added to the entire `let` statement apply for bindings created by the `let else` pattern.

Added by 61bcd8d3075471b3867428788c49f54fffe53f52:

* [`ui/let-else/let-else-non-copy.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-non-copy.rs) to ensure that a copy is performed out of non-copy wrapper types. This mirrors `if let` behaviour. The test case bases on rustc internal changes originally meant for #89933 but then removed from the PR due to the error prior to the improvements of #89841.
* [`ui/let-else/let-else-source-expr-nomove-pass.rs `](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-source-expr-nomove-pass.rs) to ensure that while there is a move of the binding in the successful case, the `else` case can still access the non-matching value. This mirrors `if let` behaviour.

Added by 102b9125e1cefbb8ed8408d2db3f9f7d5afddbf0:

* [`ui/let-else/let-else-ref-bindings.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-ref-bindings.rs) and [`ui/let-else/let-else-ref-bindings-pass.rs `](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-ref-bindings-pass.rs) to check `ref` and `ref mut` keywords in the pattern work correctly and error when needed.

Added by 2715c5f984fda7faa156d1c9cf91aa4934f0e00f:

* Match ergonomic tests adapted from the `rfc2005` test suite.

Added by fec8a507a27de1b08a0b95592dc8ec93bf0a321a:

* [`ui/let-else/let-else-deref-coercion-annotated.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-deref-coercion-annotated.rs) and [`ui/let-else/let-else-deref-coercion.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/let-else/let-else-deref-coercion.rs) to check deref coercions.

Added by this PR:

* `ui/let-else/let-else.rs`, a simple run-pass check, similar to `ui/let-else/let-else-run-pass.rs`.

### Things not currently tested

* The `#[allow(...)]` tests check whether allow works, but they don't check whether the non-presence of allow causes a lint to fire.
* There is no `#[allow(...)]` test for the expression, as there are tests for the pattern and the else block.
* `let-else-brace-before-else.rs` forbids the `let ... = {} else {}` pattern and there is a rustfix to obtain `let ... = ({}) else {}`. I'm not sure whether the `.fixed` files are checked by the tooling that they compile. But if there is no such check, it would be neat to make sure that `let ... = ({}) else {}` compiles.
* #92069 got closed as fixed, but no regression test was added. Not sure it's worth to add one.

Don't think these missing tests should block stabilization, they are rather details. But feel free to disagree.

**Comment by nikomatsakis** [comment]
@rfcbot resolve stabilization-report

Thanks @est31! Very excited for this to hit stable.

**Comment by nikomatsakis** [comment]
On the topic of stabilization phases:

I think we can separate that discussion out. I do believe it would be useful for us to distinguish *stabilized* from *recommended for use*, where the former means "code that uses this will keep compiling and retain its same meaning" and the latter means "it is documented in the reference; code that uses this is well formatted; no horrifying diagnostics". 

I'm not clear @calebcartwright on why this would be impractical: it seems to me to be formalizing and tweaking conventions that we already have, where stabilization is generally blocked on having an open PR to the reference (https://github.com/rust-lang/reference/pull/1156, in this case).

When it comes to rustfmt, we could conceptually follow that same rule: to stabilize, there must be a pending PR to rustfmt.

That said, I know that @joshtriplett has concerns, though I forget what they are. I do see the value in having a "forcing function" that encourages us to do the detailed work post stabilization. On that note, I think it would be reasonable to require a pending (but not merged) rustfmt PR before we stabilize a new feature. This would also help grow the rustfmt contributors, since people who are psyched to stabilize a feature might also be motivated to come and contribute to rustfmt.

**Comment by calebcartwright** [comment]
> Can we have the body of the block get formatted still?

Unfortunately no @scottmcm

Though technically I'm sure we could create artificial spans to capture the parts we want to format and the parts we won't, we still don't have any rules finalized for the `else` block either.

At the same time, any attempts to format the `else` block would be directly influened by the `pre`-else content (e.g. column position, whether to wrap, etc.). That would inevitably create a scenario where some users would experience multiple breaking formatting changes after updating toolchains, the first being the initial introduction of let-else support with else-block only changes, and the second would come later once rustfmt started handling the pre-`else` content because that impacts.

The actual rustfmt piece of the equation is the easy part. What we really need is for greater participation and feedback on the Style Guide that defines what the resultant formatting is supposed to look like.

**Comment by apiraino** [comment]
removing T-compiler from this FCP (as per [Zulip comment](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-02-10.20.2354818/near/271443831))

@rustbot label -T-compiler

**Comment by est31** [comment]
FTR the label is present because of tooling. It's been removed twice already, the first time rustbot has added it back when I updated the code. Rustbot will probably add it again if I should ever rebase or update the code or something. I think it's adding it because the PR is modifying compiler sources? Not sure.

**Comment by lcnr** [comment]
was there some discussion about the interaction with destructuring assignments, and if so, can the results of that discussion be mentioned in the stabilization report?

```rust
#[derive(Debug)]
enum Foo {
    Done,
    Nested(Option<Box<Foo>>),
}

fn walk(mut value: &Foo) {
    loop {
        println!("{:?}", value);
        Foo::Nested(value) = value else { break };
    }
}
```
cc #93995

**Comment by lcnr** [comment]
can you also add the used desugaring to the stabilization report? especially as it has some surprising results: (#93915)

I think it's important to state why this desugaring was chosen, esp as it is different from the one in the RFC.

**Comment by est31** [comment]
@lcnr I can't find anything about destructuring assignments. Note though that I wasn't involved in the RFC's discussions so maybe @Fishrock123 or someone else can tell more about this.

Destructuring assignments allow *irrefutable* patterns to be used in assignment position. Same goes for `let` which also allows irrefutable pattern usage. `let else` also allows refutable patterns, in fact warns if you use an `irrefutable` pattern with it. To me, the natural extension of destructuring assignments would not be some "destructuring assignment ... else" construct, but instead just making the destructuring assignment conditional. Or in other words, if the pattern does not match, then no assignment is conducted. I don't think it's a good idea to have refutable destructuring assignments without making it visible syntactically that the assignment does not neccessarily get performed, but the syntax to make this obvious doesn't need to be an `else` clause. Instead maybe `maybe` or something, so `maybe Some(foo) = bar.get(42)`.

As for the desugaring, with #93951 I think that it's a bug, but one that can be fixed after stabilization. That is, it is not a blocker, as IIRC borrow checker changes are allowed per rust's stability guarantees. Originally the RFC described the lowering in form of a match statement. I'm not sure why @cormacrelf chose the currently used desugaring in their PR. If they wrote up their reasooning I'd love to link it from the stabilization report.

**Comment by Fishrock123** [comment]
@lcnr That destructuring assignment is missing a `let` as a I have mentioned with a playground link in your issue: https://github.com/rust-lang/rust/issues/93995#issuecomment-1039503525

@est31 I am really not sure what you are meaning to say, `let <destructuring assignment> … else` works.

**Comment by cormacrelf** [comment]
I see. To restate the issue with the desugaring pointed out in #93951: if you desugar per the RFC's way, it was impossible to get that error, because the init expression would not be part of one big return expression. That is a bit of a problem. If-let and match are equivalent here, the actual deviation is that the trailing statements are now moved inside the if-branch.

I didn't personally choose that route, I only adapted existing work, but AFAICT it was done to avoid some complicated duplication of the identifiers introduced in the pattern (`let (a, b) = if let Ok([ref a, ref b]) = ... { (a, b) } else { return };`), that was required to get them into the outer scope. I can't comment on whether that was actually going to be infeasible. But the discussion was [on the original implementation PR](https://github.com/rust-lang/rust/pull/87688#discussion_r681278414) by @camsteffen with @cjgillot.

Now getting off the track in a stabilisation issue but it's possible there's a solution without reintroducing that complexity. If you make the desugaring `let retval = if let Ok(s) = foo(&x) { /* trailing stmts */ } else { return; }; retval` then you no longer have a temporary that borrowck worries will be dropped after `x`: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=819934ee99812c4674e27a078ba672d5). That is, if we can't think of any other borrowck issues.

**Comment by est31** [comment]
@lcnr @cormacrelf I've changed the stabilization report to include desugaring. I've included a mention of #94012 but didn't describe its desugaring because I wasn't entirely certain which one it chose. Was it the original one from the RFC? Also, I'm not sure whether there will be changes to the PR before it gets merged.

**Comment by cormacrelf** [comment]
To summarise it for the stabilisation report, I would put it like this:

* * *

The desugaring has gone through a number of revisions, mostly to express the RFC's intent through the type checker instead of in terms of existing syntax, and to avoid the edge cases that had exhibited. Both the else-block's divergence and the optional type annotation are now done in the type checker, and the whole thing is now an if-let instead of a match expression. The most consequential choice has been how to put the bindings in scope for the remainder of the statements in the function. The RFC envisioned this similarly to how many Rust programmers presently simulate let-else:

```rust
let (each, binding) = match expr { Ok(Ty { each, binding }) => (each, binding), _ => return };
trailing_statements(a);
// ...
```

To avoid the complexity of programmatically duplicating the bindings, the current desugaring simply slurps up all the trailing statements and puts them in the appropriate branch. In all, it looks like this.

```rust
// type annotation is HIR-only on if-let, not real syntax
if let Some(Ty { each, binding }): Option<Ty> = expr {
    trailing_statements(each, binding);
    // ...
} else {
    return;
}
```

Multiple let-elses in a row will desugar in a nested fashion, each appearing in the tail position of the then-branch of the one before it.

There is one known problem with this approach, relating to the lifetime of temporaries storing `expr` in the big implicit return expression it produces #93951, but it does have a simple and promising solution in #94012. In the event that there are further borrowck problems, the exact approach envisioned by the RFC was actually explored, did work, and remains available.[^1]

[^1]: @camsteffen thumbs up 👍 if you approve this statement.

* * *

<details>
<summary><i>If that's still unclear...</i></summary>

There have been a lot of desugarings. They are made up of the following choices in roughly "evaluation order":

1. Choice of _if-let_ or _match_ (almost completely inconsequential)
2. Implementing type annotation via a _temp_ variable vs via _typeck_
3. Forcing divergence of else block via `let nope: ! = ...` vs via _typeck_
4. Scoping of pattern match variables via ***extracting*** (via tuples + an outer let binding) into outer scope, vs. **_slurping_** up (à la [paredit slurp](http://danmidwood.com/content/2014/11/21/animated-paredit.html)) all of the statements after the let-else and putting them inside the "matched" / "then" branch of the matching mechanism. If so, then is the if-let/match in *tail position* or do we assign it to a *temporary* and then return that?

The history of choices is like so:
*  (_match_, _?_, _let nope: !_, _extract_, _) in the original RFC ([relevant section](https://github.com/rust-lang/rfcs/blob/master/text/3137-let-else.md#desugaring-example)) which didn't address either multiple bindings (ie tuples) or type annotations.
* (_match_, _temp_, _typeck_, _extract_) in Cam's initial run.
* (_if-let_, _temp_, _typeck_, _slurp/tail position_) in Cam's final #87688.
* (_if-let_, _typeck_, _typeck_, _slurp/tail position_) in my previous PR #89841.
* (_if-let_, _typeck_, _typeck_, _slurp/temporary_) in my proposed PR #94012.

The current desugaring and my proposed one have *no choices in common with the original RFC*.

</details>

**Comment by nikomatsakis** [comment]
> There is one known problem with this approach, relating to the lifetime of temporaries storing expr in the big implicit return expression it produces https://github.com/rust-lang/rust/issues/93951, but it does have a simple and promising solution in https://github.com/rust-lang/rust/pull/94012. In the event that there are further borrowck problems, the exact approach envisioned by the RFC was actually explored, did work, and remains available.[1](https://github.com/rust-lang/rust/pull/93628#user-content-fn-1-cb5418a6bccba2992af333e655628825)

This worries me a bit, I'd like to see the lifetime of temporaries better documented (pre-existing problem) and the interactions from this change in particular described. Hmm.

**Comment by joshtriplett** [comment]
@nikomatsakis Extending the writeup to incorporate discussion of desugaring does seem important, since that evolved over time. However, I don't think this needs to cover destructuring assignment; at most that just needs to be "possible future work".

**Comment by mark-i-m** [comment]
Is it too late to request (minor) design changes? I've just now come across this feature in the compiler while review a PR, and I find `let ... else ...` to be a disorienting because of the use of `else` -- I'm expecting a conditional somewhere, but all I get is a binding. I realize I'm a bit late to the dance, though...

**Comment by joshtriplett** [comment]
@mark-i-m That specific issue, along with other possible syntaxes, was discussed fairly extensively on the RFC thread. It's never too late as long as a feature hasn't been stabilized yet, but it would need a new angle not seen already on that thread.

**Comment by cormacrelf** [comment]
> @nikomatsakis: This worries me a bit, I'd like to see the lifetime of temporaries better documented (pre-existing problem) and the interactions from this change in particular described. Hmm.

I have a little more to add on the dropping of temporaries. There is one particular respect in which the nested desugaring expands pretty dramatically on the RFC's capabilities. It allows you to match against temporaries and pull references out of them, just like a regular `let` statement, whereas the RFC's tuple-threading method does not. You can presently do this:

```rust
let Some(x) = &mut Some(5) else { return };
*x += 5;
```

That's because when the `*x += 5;` is moved into the desugared if branch, the temporary `Some(5)` has not yet been dropped: `if let Some(x) = &mut Some(5) { *x += 5 } else { return }`.

I just did a rough reprise of the original straight-line re-binding method (just to see if it would work and alleviate #94176), and it fails to compile things like these, for the same reason that you can't do the tuple-threading equivalent with a temporary in stable rust today: [playground]

```rust
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:2:56  |
2 |     let (identifier,) = if let Some(identifier) = &mut Some(5) {
  |                                                        ^^^^^^^ creates a temporary which is freed while still in use
...
6 |     };
  |      - temporary value is freed at the end of this statement
7 |     *identifier = 10;
  |     ---------------- borrow later used here
  |
  = note: consider using a `let` binding to create a longer lived value
```

[playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9d317734fa768054dfa4a8a785402c1a

Allowing this is an improvement and better matches expectations. You can bind to parts of a temporary in a single let binding (`let (a, b) = &mut (5, 8);`) so I don't see why you should be unable to do so in a let-else binding. It should, in theory, be possible to get rustc to be a lot smarter about temporaries' lifetimes (extending them outside the expression they were born in), and to eliminate many more 'temporary freed while still in use' errors from other kinds of code, but that's for another day.

**Comment by camsteffen** [comment]
Hmm isn't it bad that temporaries are not dropped at the end of the let-else statement? That could be surprising for a temporary `MutexGuard` for example.

**Comment by joshtriplett** [comment]
The handling and lifetimes of temporaries should be exactly the same with let and with let else; any understanding or intuitions that people have about let should apply to let else.

**Comment by jackh726** [comment]
Implementation-wise, this looks fine to me. Going to change this to waiting-on-team for now; please change back to waiting-on-review when FCP is done for a final review from me

**Comment by camsteffen** [comment]
> The handling and lifetimes of temporaries should be exactly the same with let and with let else; any understanding or intuitions that people have about let should apply to let else.

I think we have a bug then. 😢  (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=97844d29f488fec5bb242e38d8635483))

**Comment by est31** [comment]
@camsteffen I think this is what #94012 is about. Not 100% sure your bug is fixed with that PR applied to.

**Comment by camsteffen** [comment]
> @camsteffen I think this is what #94012 is about. Not 100% sure your bug is fixed with that PR applied to.

I don't think so unfortunately, since the drop will still occur after the following statements.

**Comment by est31** [comment]
@nikomatsakis re your concerns, I have copied the stabilization report to the top. When it comes to the desugaring there is still a PR open about it, #94012. So the section can't be finalized yet. In fact, there is still [ongoing discussion](https://github.com/rust-lang/rust/pull/94012#discussion_r814617249) in that PR about the desugaring. I'd say progress is blocked on #94012 right now.

On the missing tests front, progress has happened by me adding a PR to add them: #94208 . Also, I've improved error messages for destructuring assignments with an else clause in #94211, as requested by @lcnr in #93995.

**Comment by pnkfelix** [comment]
> > The handling and lifetimes of temporaries should be exactly the same with let and with let else; any understanding or intuitions that people have about let should apply to let else.
> 
> I think we have a bug then. 😢 (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=97844d29f488fec5bb242e38d8635483))

@rfcbot concern need-consistency-rvalue-temporary-rules-between-let-and-let-else

We need to make sure that examples like the one given above, and variations like this:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4c8e1cd80f50ed3c41eb426ae80c350c

(which currently *is* consistent, but one can imagine buggy fixes to the previous playground that subsequently break this case)

are all made consistent and are exercised in the test suite.

**Comment by nikomatsakis** [comment]
Quick note on formatting:

I just encountered a case with a really long expression being matched. My usual rule was not very satisfactory:

```rust
let Some((fooooooo, baaaaaaaaaaaaaaaaaaaar, baaaaaaaaaaaaaaaaaaaaaaaaaaaz)) =
    something_that_creates_that() else {
    return Err(());
};
```

Hence I wrote what seemed natural for other cases where this happens:

```rust
let Some((fooooooo, baaaaaaaaaaaaaaaaaaaar, baaaaaaaaaaaaaaaaaaaaaaaaaaaz)) =
    something_that_creates_that()
else {
    return Err(());
};
```

and I realized, "Oh, although it seems less 'elegant', maybe having the `else` on the next line would just be clearer always". Food for thought when the style team takes this into consideration. (I guess that this is not news to most people, but I hadn't encountered the formatting edge cases yet.)

**Comment by nikomatsakis** [comment]
@rfcbot resolve summarize-concerns

Thanks for the edits to the report, everyone, and to @pnkfelix for filing a more precise concern about temporary rvalues.

**Comment by est31** [comment]
@nikomatsakis re your point on putting `else` onto a separate line, there has been a [similar](https://github.com/rust-lang/rustfmt/issues/4914#issuecomment-887104615) suggestion in the dedicated rustfmt thread, although that suggestion wants to put it onto a new line more often (basically always unless the entire statement doesn't fit into a single line, if the else body is just too large but the `else` fits onto the same line as `let`, I think it should be in the same line).

This PR needs a rebase but I'm waiting until it's closer to FCP as @c410-f3r 's PRs keep causing conflicts, and I don't want to spam people subscribed to this PR with rebase related notifications.

**Comment by c410-f3r** [comment]
Who?! Me?! 👀

Yesterday was introduced the last PR so you probably won't expect more future conflicts

**Comment by est31** [comment]
Thanks for the heads up! Yeah, your recent PRs have caused conflicts in the lib.rs files, but it's fine and only small disruption anyways, and very easy to fix. I just said I'm going to wait with rebasing because atm this PR is far away from being merged (blocked on FCP which is blocked on desugaring improvements), to let the triage people know.

**Comment by calebcartwright** [comment]
> there has been a https://github.com/rust-lang/rustfmt/issues/4914#issuecomment-887104615 suggestion in the dedicated rustfmt thread

minor correction: That rustfmt implementation tracking issue is actually not the right place.

Thoughts/perspectives/etc. on the style/formatting rules should be directed to the style guide in https://github.com/rust-dev-tools/fmt-rfcs/pull/165 and I'd encourage anyone/everyone interested to participate; the more feedback and input provided on the rules the more quickly we'll be able to start the implementation in rustfmt

**Comment by joshtriplett** [comment]
@rfcbot concern semicolon

Several people have independently made the point that most braced blocks of code in Rust don't require a trailing semicolon, and that people are likely to regularly forget this. I'm finding myself starting to agree with that opinion.

I'm filing this as a concern for us to discuss in the next lang team meeting.

**Comment by est31** [comment]
IDK, personally, I see the `;` to be consistent with traditional `let` which needs them too. Especially as let else is a replacement of this pattern:

```Rust
let foo = if let Some(foo) = bar {
    foo
} else {
    panic!()
};
```

For other places with `};`, one can often find stuff like this:

```Rust
let foo = {
    /* code that returns something */
};
```

Lastly, there are closures:

```Rust
let bar = || {
    // Do something
};
bar();
```

I don't think `let else` is much different from these `let IDENT = EXPR;` constructs, where the `}` is part of the expr. But the same time, there is no precedent for an `else` where a trailing `}` is required as part of the construct that gives rise to the `else`.

**Comment by camsteffen** [comment]
> IDK, personally, I see the ; to be consistent with traditional let which needs them too.

I want to make a small distinction here. In those examples, the brace at the end is part of an expression *within* the `<expr>` of a `let` statement. The closing brace is not part of the syntax of the outermost language construct that the statement consists of. let-else is the first whole-statement construct that ends with `};`. Comparing with if/else, while, loop. That's why I get tripped up. When writing a `loop` statement, I think "this closing brace ends the loop which is the whole statement, so I don't need a semicolon". I apply the same reasoning to let-else and...error.

**Comment by Fishrock123** [comment]
I think that making `let-else` less like other assignments would be a bad maneuver. Without the semicolon it looks like an expression which could possibly return a value, which is misleading.

Consider:

```rust
thing.map(|inner| let Some(a) = inner else { something })
```

Looks kinda like a construct which could return something.
Ah, but you say, “there’s a `let` there so that looks odd and kinda obvious and should easily warn from the compiler” - while true, consider that there has been discussion of extending `let-else` behavior to destructuring assignments, which would end you up with code that really looks like it could plausibly return something:

```rust
let a, b;

thing.map(|inner| (a, b) = inner else { something })
```

To me, without the semicolon this looks like it should plausibly work, like something could be returned from the `else`. I think this will be more confusing for beginners than requiring a semicolon, and maybe it could leave us with extra options for a potential fallback extension for destructuring assignment without the `let` in particular.
I suppose you could argue if this is about potential addition of this to destructuring assignments then `let-else` in specific does not need to abide by those but I think that would make consistency even worse.

Plus, as far as I know all other assignments require a semicolon at the end, which will probably also be confusing. On this note, [the RFC mentions it in the context of consistency with `let`](https://github.com/rust-lang/rfcs/blob/master/text/3137-let-else.md#rationale-and-alternatives).

tl;dr: RFC author thinks that not requiring semicolon will be a mistake

**Comment by joshtriplett** [comment]
@Fishrock123 Thank you for that detailed response!

While I don't think we're going to add destructuring-assignment-else (largely *because* it isn't as distinctly identified), even without that I agree with your assessment of the meaning and potential confusion of omitting the semicolon.

@rfcbot resolved semicolon

**Comment by Fishrock123** [comment]
As a small elaboration to that: let-else is a statement, not an expression.

**Comment by camsteffen** [comment]
> Consider:
> 
> ```rust
> thing.map(|inner| let Some(a) = inner else { something })
> ```

I wouldn't expect that to compile in the same way that you can't write `thing.map(|inner| struct X {})`.

**Comment by Fishrock123** [comment]
Me, knowing better, would not expect it to compile either. I think it would look at a glance more ambiguous to newcomers without the semicolon however, especially if this were ever added to the destructuring assignment.

**Comment by est31** [comment]
There hasn't been much progress lately, since #94012 was filed at least, unless I've been missing something. Especially, this is unfixed: https://github.com/rust-lang/rust/pull/93628#issuecomment-1050037021

**Comment by nikomatsakis** [comment]
@dingxiangfei2009,  @pnkfelix, and I got together to discuss alternatives around adjusting the desugaring. We concluded that there is no way to represent the desired temporary lifetimes if we desugar let-else in the existing HIR, and that we ought to extend the HIR with a specific let-else construct.  Here are our notes:

https://hackmd.io/@nikomatsakis/r1CpZqc8c

Personally, I think we desugar too much at the HIR level and make our lives harder than they have to be (e.g., I don't think we should desugar `for` either until MIR construction), but @pnkfelix felt a bit sad about the idea of adding let-else. =) Anyway, if people have other ideas for how to manage the desugaring, we're all ears! 

In the meantime, @dingxiangfei2009 is going to start exploring what it would like to extend HIR with let-else as a native construct -- we will see how cleanly it works out.

**Comment by pnkfelix** [comment]
> we ought to extend the HIR with a specific let-else construct.

Just so it isn't lost in the ether: the concrete idea is to add support for let-else on the existing HIR node for `Let`, by adding the expression as an `Option` field. (Rather than, say, adding a totally new and separate variant somewhere.

**Comment by est31** [comment]
Hmm this is a weird build failure:
```
error: unexpected `cfg` condition name
 --> compiler/rustc_macros/src/lib.rs:2:13
  |
2 | #![cfg_attr(bootstrap, feature(let_else))]
  |
  |
  = note: `-D unexpected-cfgs` implied by `-D warnings`
```

I can reproduce it locally if I do `./x.py test clippy -v`. `cargo` is invoked with `-Zcheck-cfg` and thus adds all the corresponding flags to rustc, including the ones to enable cfg checking. But somehow the additional flags added for the rustc custom cfg flags that are set in bootstrap are missing. I've filed #98080 to make the code emit nicer flags, but that PR does not fix the build issue. I feel that the rustflags are added (because that code is the only place that enables cargo's `-Zcheck-cfg` flag), and then later discarded... While that code is not the cause of the build issue, I think it's somewhere else in bootstrap.

**Comment by jplatte** [comment]
I recently came across `RUSTDOCFLAGS` (and `RUSTFLAGS`) not being passed along by cargo if a specific nightly feature is active: https://github.com/rust-lang/cargo/issues/10744

Maybe bootstrap also uses this, or some other nightly Cargo feature(s) that trigger the same bug?

**Comment by Urgau** [comment]
I investigated the build issue and contrary to what I though this is a legitimate build error.

The reason why is because when `cargo` compiles a proc-macro crate it doesn't forward the `RUSTFLAGS` if `--target` is also passed to `cargo` (which is always the case with `bootstrap`); this means that none of the `--check-cfg` arguments are passed to `rustc` except for the one explicitly set by `cargo -Zcheck-cfg` AND because of this `--cfg=bootstrap` is also not passed to `rustc` which means that `bootstrap` cfg key is not accessible when compiling a proc-macro crate which means that the build error is right.

**Comment by nikomatsakis** [comment]
Brief update: @dingxiangfei2009 and I have been working on a refactoring to fix the temporary scope issues [as discussed here](https://github.com/rust-lang/rust/pull/93628#issuecomment-1125066530). Progress is being made! Still working on it, though.

**Comment by Urgau** [comment]
> Thanks @jplatte and @Urgau for the help. I have allowed lint for that crate for now, which can go to master until a better approach is found.

No! If the `--check-cfg` arguments are not set that also means that the `--cfg` arguments aren't also. Allowing the lint is not right, this only hides the fact that you simply can't currently use `cfg(bootstrap)` in a proc-macro crate in the codebase.

For once the lint is working as expected, `bootstrap` IS unexpected because as I've noted in https://github.com/rust-lang/rust/pull/93628#issuecomment-1155042688 the `RUSTFLAGS` set by `bootstrap` aren't forwarded to the proc-macro crates, that includes `--cfg=bootstrap`.

**Comment by est31** [comment]
@Urgau try adding this to rustc_macros, and then do `x.py check`:

```rust
#[cfg(bootstrap)]
compile_error!("bootstrap was hit!");
```

You will get a compiler error (at least I do). Same goes for removing the line which is what you suggest. That it errors is weird though because when I add the `-v` parameter, no `--cfg=bootstrap` is part of the invocation (while it is for other compiler crates). How this works? No idea, I need to investigate.

**Comment by est31** [comment]
Ahh apparently it *is* a bug in bootstrap after all, namely the rustc shim, because here the `bootstrap` cfg flag is set even for proc macros: https://github.com/rust-lang/rust/blob/c3605f8c8020dbbe8f0d1961c7b33c4c4b78ad0d/src/bootstrap/bin/rustc.rs#L130-L135

Outside of that the argument of `cfg` in `RUSTFLAGS` not getting passed to proc macros either makes a lot of sense, so I think it's not an issue that should affect the `--check-cfg` feature.

I will send a separate PR for this.

**Comment by Urgau** [comment]
Hum... okay! I didn't see that coming. Sorry for the later comment and thanks for the future PR.

**Comment by camsteffen** [comment]
I opened #98672 for the temporaries issue.

**Comment by pnkfelix** [comment]
We can just wait a little while longer; once the next beta forks off from nightly, then a retry of the CI builder (or maybe opening+closing the PR, not sure) should get around the failures that are being signaled above for the miri dependency.

**Comment by est31** [comment]
I haven't tried confirming the theory yet, but according to [this](https://github.com/rust-lang/miri/pull/2374#issuecomment-1184768594), the error can safely be ignored.

Btw, current status for stabilization is that this is blocked on #99954 I'd say. #99291 can be merged before that PR but merging it after might be a good idea too as it would increase the diff of #99954 .

**Comment by est31** [comment]
Status update: #99954 has been merged now, as well as #99291, both fixing stabilization blockers. This resolves all the blockers that have existed up till the last update.

However, #99975 seems to be encountered quite often by users, if you check the thread. The reproducing examples also don't look very far fetched: The chance is high that you encounter them in real life. As the number of users who run into it will only *increase* once we stabilize it, I think that stabilizing `let else` with it open is not a good idea. Thankfully, a solution for it has been proposed already in #101410.

I don't think we'll make it into 1.65, as the cut is already in 10 days. But there are high chances for 1.66 :).

We are closer to stabilization than ever :tada:

**Comment by pnkfelix** [comment]
With https://github.com/rust-lang/rust/pull/99291, I am more confident that the temporary rvalue lifetime rules have been resolved.

@rfcbot resolve need-consistency-rvalue-temporary-rules-between-let-and-let-else

(however, while this will probably cause the FCP and the 10 day countdown to resume, please do not merge this PR before the remaining ICEs, such as #99975, are all resolved.)

**Comment by est31** [comment]
With #101410 merged, the last blocker is gone for stabilization. Now we only have to wait for the 10 day FCP to finish, which started a little over 9 days ago. So far it has been very peaceful, and as there has been a lot of scrutiny on the feature during the very long pre-fcp phase (over 6 months!), I doubt we will see a blocker come up in the last day.

Given that there is going to be a beta branch off event tomorrow, maybe this PR can be merged before the FCP is over, under the condition that it is being reverted if there is something to hold back stabilization, so that it maybe can get onto stable more quickly. It's up to the reviewers to decide. I'm marking this PR as ready for review now.

**Review by joshtriplett — APPROVED** [review]

**Comment by joshtriplett** [comment]
No objections since it's been being reviewed for far longer than 10 days.

**Comment by slanterns** [comment]
Maybe can give some priority if we want it to be merged before the branching.

**Comment by joshtriplett** [comment]
@slanterns I don't think we should get in the habit of skipping the queue; if it makes it it makes it.

**Comment by joshtriplett** [comment]
Looks like this failed in a rollup.

**Comment by est31** [comment]
Yeah, seems the problems from [earlier](https://github.com/rust-lang/rust/pull/93628#issuecomment-1154697627) are plaguing us again: https://github.com/rust-lang/rust/pull/101910#issuecomment-1249760497 , which is weird as I've thought that #98147 fixed the problem. Apparently doc-tests of the rustc_macros crate are affected now. I guess those don't get the right flags passed, but need to investigate how exactly we are hitting the bug.
Screenshot_20220916_224716

**Comment by est31** [comment]
I can reproduce it locally with `./x.py test compiler/rustc_macros/`. It seems that the rustdoc wrapper needs adjustments too, similar to how #98147 adjusted the rustc wrapper. Also, `./x.py test --stage 0 compiler/rustc_macros/` is broken as well. It complains about a missing `feature(let_else)`, which occurs when no `--cfg=bootstrap` is passed. This is probably because cargo doesn't pass `RUSTDOCFLAGS` to proc-macro crate rustdoc invocations similar to how it doesn't pass `RUSTFLAGS` to proc-macro rustc invocations for $reasons (the PR i linked links to the cargo issue for that). The rustc wrapper has code to deal with this for rustc, but probably the rustdoc wrapper needs similar logic.

**Comment by est31** [comment]
I've filed #101921 to fix the issue. I've locally applied that PR to this one, the issue is resolved.

**Comment by Fishrock123** [comment]
@est31 Big thanks for carrying this over the finish line!!

**Comment by est31** [comment]
🎉 **the stabilization PR has been merged** 🎉

Getting let else into the language was very much a team effort, and I would like to thank everyone who was involved in their introduction and stabilization. In particular I would like to thank:

Authors of the RFCs 1303 and 3137:

@Fishrock123 @mbrubeck

PR authors for the implementation in the compiler:

@camsteffen (lowering, tests) @compiler-errors (diagnostics, ICE fixes) @cormacrelf (initial implementation, lowering, tests) @dingxiangfei2009 (lowering, tests) @est31 (stabilization, diagnostics, tests) @JohnTitor (ICE fixes) 

Reviewers of those PRs:

@cjgillot @petrochenkov @nagisa @matthewjasper @oli-obk @Mark-Simulacrum @pnkfelix @joshtriplett @jackh726

Everyone who tested out let-else, filed issues/bug reports, provided guidance and feedback in the RFCs, PRs and issues, including team members who approved FCPs.
