### PR TITLE
Fix Vec::const_make_global for 0 capacity and ZST's

### LINKED ISSUE #153158: `Vec`'s const_make_global method erroring when `Vec` is empty
I tried this code:

```rust
#![feature(const_heap)]
fn main() {
    const {
        let mut inner_vec = Vec::<i32>::new();
        let inner_slice = inner_vec.const_make_global();
    }
}
```

I expected `const_make_global()` to just return an empty `'static` slice

Instead, it gave me this error:

```
error[E0080]: pointer not dereferenceable: pointer must point to some allocation, but got 0x4[noalloc] which is a dangling pointer (it has no provenance)
   --> src\main.rs:6:27
    |
  6 |         let inner_slice = inner_vec.const_make_global();
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `main::{constant#0}` failed inside this call
    |
note: inside `Vec::<i32>::const_make_global`
   --> C:\Users\theiz\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\src\vec\mod.rs:897:18
    |
897 |         unsafe { core::intrinsics::const_make_global(self.as_mut_ptr().cast()) };
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the failure occurred here
```

But this code:

```rust
#![feature(const_heap)]
#![feature(const_trait_impl)]
fn main() {
    const {
        let mut inner_vec = Vec::<i32>::new();
        inner_vec.push(4);
        let inner_slice = inner_vec.const_make_global();
    }
}
```

works just fine

### Meta

`rustc --version --verbose`:
```
rustc 1.95.0-nightly (859951e3c 2026-02-24)
binary: rustc
commit-hash: 859951e3c7c9d0322c39bad49221937455bdffcd
commit-date: 2026-02-24
host: x86_64-pc-windows-msvc
release: 1.95.0-nightly
LLVM version: 22.1.0
```

I am assuming it was because the `Vec` was empty

### PR DESCRIPTION
**Pull request by Lars-Schumann**
fixes https://github.com/rust-lang/rust/issues/153158

### CODE REVIEW

File: library/alloc/src/vec/mod.rs [hunk 1]
```diff
@@ -898,6 +898,20 @@ impl<T> Vec<T> {
...
+            _ = ManuallyDrop::new(self);
+            return &[];
+        }
+
+        // if `T::IS_ZST`, the pointer we give to `const_make_global` would again not
+        // point to the start of a heap allocation
+        if T::IS_ZST {
+            let me = ManuallyDrop::new(self);
+            return unsafe { slice::from_raw_parts(NonNull::<T>::dangling().as_ptr(), me.len) };
+        }
```
Comment (fee1-dead) [inline library/alloc/src/vec/mod.rs]: Doesn't seem to need duplication here? Could just do `self.capacity() == 0 || T::IS_ZST` here?

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: library/alloc/src/vec/mod.rs (hunk 1 above)
Comment (Lars-Schumann) [reply library/alloc/src/vec/mod.rs]: I wasn't sure how to return something that made sense for both cases when combining them, if theres something obvious that works for both then yeah it should be combined.

Comment (fee1-dead) [reply library/alloc/src/vec/mod.rs]: Well, a dangling pointer can be safely converted into a slice since it is well-aligned, so I think you can just keep `slice::from_raw_parts`?
