### PR TITLE
Avoid projection-only suggestions for inherent assoc types

### LINKED ISSUE #153539: [ICE]: assertion failed `Inherent == Projection`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Znext-solver=globally
#![feature(inherent_associated_types)]

struct S<'a>(&'a ());

impl<X> S<'_> {
    type P = ();
}

fn ret_ref_local<'e>() -> &'e i32 {
    let f: for<'a> fn(&'a i32) -> S<'a>::P = |x| _ = x;

    f(&1)
}

````

original:
````rust
//@compile-flags: -Znext-solver=globally
#![feature(inherent_associated_types)]

struct S<'a>(&'a ());

impl<X> S<'_> {
    type P = ();
}

fn ret_ref_local<'e>() -> &'e i32 {
    let f: for<'a> fn(&'a i32) -> S<'a>::P = |x| _ = x;

    f(&1)
}

fn main() {}

````

Version information
````
rustc 1.96.0-nightly (ea5573a6c 2026-03-07)
binary: rustc
commit-hash: ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d
commit-date: 2026-03-07
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_type_ir/src/ty_kind.rs#L496-L508

Command:
`/home/matthias/.rustup/toolchains/alt-master/bin/rustc -Znext-solver=globally`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `inherent_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.4hWlX5mQSkpo/rustc_testrunner_tmpdir_reporting.87LkD4H8sW90/mvce.rs:1:12
  |
1 | #![feature(inherent_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.4hWlX5mQSkpo/rustc_testrunner_tmpdir_reporting.87LkD4H8sW90/mvce.rs:13:2
   |
13 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.4hWlX5mQSkpo/rustc_testrunner_tmpdir_reporting.87LkD4H8sW90/mvce.rs`

error[E0207]: the type parameter `X` is not constrained by the impl trait, self type, or predicates
 --> /tmp/icemaker_global_tempdir.4hWlX5mQSkpo/rustc_testrunner_tmpdir_reporting.87LkD4H8sW90/mvce.rs:5:6
  |
5 | impl<X> S<'_> {
  |      ^ unconstrained type parameter


thread 'rustc' (2305101) panicked at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_type_ir/src/ty_kind.rs:502:9:
assertion `left == right` failed
  left: Inherent
 right: Projection
stack backtrace:
   0:     0x7f9661f143e0 - std[c06b0f5e9ce3dfcd]::backtrace_rs::backtrace::libunwind::trace
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x7f9661f143e0 - std[c06b0f5e9ce3dfcd]::backtrace_rs::backtrace::trace_unsynchronized::<std[c06b0f5e9ce3dfcd]::sys::backtrace::_print_fmt::{closure#1}>
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x7f9661f143e0 - std[c06b0f5e9ce3dfcd]::sys::backtrace::_print_fmt
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/backtrace.rs:74:9
   3:     0x7f9661f143e0 - <<std[c06b0f5e9ce3dfcd]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[1821190c7e0c726e]::fmt::Display>::fmt
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/backtrace.rs:44:26
   4:     0x7f965d4e9c8e - <core[1821190c7e0c726e]::fmt::rt::Argument>::fmt
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/fmt/rt.rs:152:76
   5:     0x7f965d4e9c8e - core[1821190c7e0c726e]::fmt::write
   6:     0x7f9661f2c50c - std[c06b0f5e9ce3dfcd]::io::default_write_fmt::<std[c06b0f5e9ce3dfcd]::sys::stdio::unix::Stderr>
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/io/mod.rs:639:11
   7:     0x7f9661f2c50c - <std[c06b0f5e9ce3dfcd]::sys::stdio::unix::Stderr as std[c06b0f5e9ce3dfcd]::io::Write>::write_fmt
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/io/mod.rs:1994:13
   8:     0x7f9661ed8ed6 - <std[c06b0f5e9ce3dfcd]::sys::backtrace::BacktraceLock>::print
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/backtrace.rs:47:9
   9:     0x7f9661ed8ed6 - std[c06b0f5e9ce3dfcd]::panicking::default_hook::{closure#0}
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:292:27
  10:     0x7f9661f030d1 - std[c06b0f5e9ce3dfcd]::panicking::default_hook
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:319:9
  11:     0x7f965e91f1c7 - <alloc[ef773830cf77dad2]::boxed::Box<dyn for<'a, 'b> core[1821190c7e0c726e]::ops::function::Fn<(&'a std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo<'b>,), Output = ()> + core[1821190c7e0c726e]::marker::Send + core[1821190c7e0c726e]::marker::Sync> as core[1821190c7e0c726e]::ops::function::Fn<(&std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo,)>>::call
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/alloc/src/boxed.rs:2254:9
  12:     0x7f965e91f1c7 - rustc_driver_impl[99f647836f16c82a]::install_ice_hook::{closure#1}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_driver_impl/src/lib.rs:1483:17
  13:     0x7f965e91f1c7 - <alloc[ef773830cf77dad2]::boxed::Box<rustc_driver_impl[99f647836f16c82a]::install_ice_hook::{closure#1}> as core[1821190c7e0c726e]::ops::function::Fn<(&dyn for<'a, 'b> core[1821190c7e0c726e]::ops::function::Fn<(&'a std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo<'b>,), Output = ()> + core[1821190c7e0c726e]::marker::Send + core[1821190c7e0c726e]::marker::Sync, &std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo)>>::call
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/alloc/src/boxed.rs:2254:9
  14:     0x7f965e91f1c7 - std[c06b0f5e9ce3dfcd]::panicking::update_hook::<alloc[ef773830cf77dad2]::boxed::Box<rustc_driver_impl[99f647836f16c82a]::install_ice_hook::{closure#1}>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:235:47
  15:     0x7f9661f0346a - <alloc[ef773830cf77dad2]::boxed::Box<dyn for<'a, 'b> core[1821190c7e0c726e]::ops::function::Fn<(&'a std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo<'b>,), Output = ()> + core[1821190c7e0c726e]::marker::Send + core[1821190c7e0c726e]::marker::Sync> as core[1821190c7e0c726e]::ops::function::Fn<(&std[c06b0f5e9ce3dfcd]::panic::PanicHookInfo,)>>::call
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/alloc/src/boxed.rs:2254:9
  16:     0x7f9661f0346a - std[c06b0f5e9ce3dfcd]::panicking::panic_with_hook
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:833:13
  17:     0x7f9661ed8f98 - std[c06b0f5e9ce3dfcd]::panicking::panic_handler::{closure#0}
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:698:13
  18:     0x7f9661ec7d49 - std[c06b0f5e9ce3dfcd]::sys::backtrace::__rust_end_short_backtrace::<std[c06b0f5e9ce3dfcd]::panicking::panic_handler::{closure#0}, !>
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/backtrace.rs:182:18
  19:     0x7f9661edaeed - __rustc[21f7ef2cffa0e85c]::rust_begin_unwind
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:689:5
  20:     0x7f965d4ea98c - core[1821190c7e0c726e]::panicking::panic_fmt
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panicking.rs:80:14
  21:     0x7f965d4ea813 - core[1821190c7e0c726e]::panicking::assert_failed_inner
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panicking.rs:439:17
  22:     0x7f965f5f4f83 - core[1821190c7e0c726e]::panicking::assert_failed::<rustc_type_ir[cb85bf62398c83a7]::ty_kind::AliasTyKind, rustc_type_ir[cb85bf62398c83a7]::ty_kind::AliasTyKind>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panicking.rs:394:5
  23:     0x7f96616906d9 - <rustc_type_ir[cb85bf62398c83a7]::ty_kind::AliasTy<rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>>::trait_ref_and_own_args
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_type_ir/src/ty_kind.rs:502:9
  24:     0x7f96616906d9 - <rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::suggest_constraint::<&<rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::note_and_explain_type_err::{closure#7}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_trait_selection/src/error_reporting/infer/note_and_explain.rs:555:47
  25:     0x7f96618cc4f3 - <rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::note_and_explain_type_err
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_trait_selection/src/error_reporting/infer/note_and_explain.rs:280:35
  26:     0x7f96618a5897 - <rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::note_type_err
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:1801:18
  27:     0x7f96618aea15 - <rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::report_and_explain_type_error
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:1995:14
  28:     0x7f96618aa37d - <rustc_trait_selection[f510003446db340b]::error_reporting::TypeErrCtxt>::report_mismatched_types
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_trait_selection/src/error_reporting/infer/mod.rs:157:29
  29:     0x7f965f38ab0d - <rustc_hir_typeck[dc53285c34242b25]::coercion::CoerceMany>::report_return_mismatched_types
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/coercion.rs:1821:28
  30:     0x7f965f31d030 - <rustc_hir_typeck[dc53285c34242b25]::coercion::CoerceMany>::coerce_inner::<<rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_block::{closure#0}::{closure#1}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/coercion.rs:1621:36
  31:     0x7f965f31d030 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_block::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1043:24
  32:     0x7f965f31d030 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_block::{closure#0}, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1560:22
  33:     0x7f965f31d030 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_block
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1020:31
  34:     0x7f965f27b896 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:387:46
  35:     0x7f965f2ac687 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:291:23
  36:     0x7f965f2ac687 - stacker[1d1c8a43f2803809]::maybe_grow::<rustc_middle[7526ec506fab00ca]::ty::Ty, <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  37:     0x7f965f2ac687 - rustc_data_structures[a1cca6a08c57096c]::stack::ensure_sufficient_stack::<rustc_middle[7526ec506fab00ca]::ty::Ty, <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/stack.rs:21:5
  38:     0x7f965f2ac687 - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:286:18
  39:     0x7f965f2a9d2c - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:231:14
  40:     0x7f965f2a964a - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_expr_with_hint
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:186:14
  41:     0x7f965f2a964a - <rustc_hir_typeck[dc53285c34242b25]::fn_ctxt::FnCtxt>::check_return_or_body_tail
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/expr.rs:968:35
  42:     0x7f965f4299fd - rustc_hir_typeck[dc53285c34242b25]::check::check_fn
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/check.rs:130:9
  43:     0x7f965f23f038 - rustc_hir_typeck[dc53285c34242b25]::typeck_with_inspect::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/lib.rs:178:9
  44:     0x7f965f26886c - rustc_hir_typeck[dc53285c34242b25]::typeck_with_inspect
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_typeck/src/lib.rs:103:1
  45:     0x7f9660f43acf - rustc_query_impl[bf642988832e2c3b]::query_impl::typeck::invoke_provider_fn::__rust_begin_short_backtrace
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:397:42
  46:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:421:59
  47:     0x7f9660c6da10 - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  48:     0x7f9660c6da10 - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::try_with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:513:12
  49:     0x7f9660c6da10 - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:477:20
  50:     0x7f9660c6da10 - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:53:9
  51:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::plumbing::start_query::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:88:9
  52:     0x7f9660c6da10 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context::<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:86:36
  53:     0x7f9660c6da10 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context_opt::<rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:75:18
  54:     0x7f9660c6da10 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context::<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:86:5
  55:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::plumbing::start_query::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:75:5
  56:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:421:17
  57:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>, false>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:364:9
  58:     0x7f9660c6da10 - rustc_query_impl[bf642988832e2c3b]::execution::try_execute_query::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>, false>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:317:13
  59:     0x7f9660f43e96 - rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:677:32
  60:     0x7f9660f43e96 - stacker[1d1c8a43f2803809]::maybe_grow::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  61:     0x7f9660f43e96 - rustc_data_structures[a1cca6a08c57096c]::stack::ensure_sufficient_stack::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/stack.rs:21:5
  62:     0x7f9660f43e96 - rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:677:5
  63:     0x7f9660f43e96 - rustc_query_impl[bf642988832e2c3b]::query_impl::typeck::execute_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:361:26
  64:     0x7f965ed46d00 - rustc_middle[7526ec506fab00ca]::query::inner::query_ensure::<rustc_data_structures[a1cca6a08c57096c]::vec_cache::VecCache<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[7526ec506fab00ca]::dep_graph::graph::DepNodeIndex>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/query/inner.rs:63:9
  65:     0x7f965ed46d00 - <rustc_middle[7526ec506fab00ca]::query::plumbing::TyCtxtEnsureOk>::typeck::<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/query/plumbing.rs:445:21
  66:     0x7f965ed46d00 - rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_analysis/src/lib.rs:248:29
  67:     0x7f965ed46d00 - <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/hir/map.rs:338:79
  68:     0x7f965ed8fe30 - rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in::<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:158:30
  69:     0x7f965ed8fe30 - <core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}> as core[1821190c7e0c726e]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panic/unwind_safe.rs:274:9
  70:     0x7f965ed8fe30 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::do_call::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:581:40
  71:     0x7f965ed8fe30 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::<(), core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:544:19
  72:     0x7f965ed8fe30 - std[c06b0f5e9ce3dfcd]::panic::catch_unwind::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panic.rs:359:14
  73:     0x7f965ed8fe30 - <rustc_data_structures[a1cca6a08c57096c]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:23:9
  74:     0x7f965ed8fe30 - rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in::<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:158:23
  75:     0x7f965ed8fe30 - <core[1821190c7e0c726e]::slice::iter::Iter<rustc_span[96b95645e4d1c03c]::def_id::LocalDefId> as core[1821190c7e0c726e]::iter::traits::iterator::Iterator>::for_each::<rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}::{closure#1}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/slice/iter/macros.rs:301:21
  76:     0x7f965ed8fe30 - rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in::<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:157:27
  77:     0x7f965ed8fe30 - rustc_data_structures[a1cca6a08c57096c]::sync::parallel::parallel_guard::<(), rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:39:15
  78:     0x7f965ed8fe30 - rustc_data_structures[a1cca6a08c57096c]::sync::parallel::par_for_each_in::<&rustc_span[96b95645e4d1c03c]::def_id::LocalDefId, &[rustc_span[96b95645e4d1c03c]::def_id::LocalDefId], <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/sync/parallel.rs:152:5
  79:     0x7f965ed8fe30 - <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[3a457be568a2e8d1]::check_crate::{closure#2}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/hir/map.rs:338:9
  80:     0x7f965ed8fe30 - rustc_hir_analysis[3a457be568a2e8d1]::check_crate
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_hir_analysis/src/lib.rs:223:9
  81:     0x7f965f84f426 - rustc_interface[8b1a49937cb7b5cc]::passes::run_required_analyses
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/passes.rs:1073:5
  82:     0x7f965f84f426 - rustc_interface[8b1a49937cb7b5cc]::passes::analysis
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/passes.rs:1125:5
  83:     0x7f9660f460e7 - rustc_query_impl[bf642988832e2c3b]::query_impl::analysis::invoke_provider_fn::__rust_begin_short_backtrace
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:397:42
  84:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:421:59
  85:     0x7f9660caa387 - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  86:     0x7f9660caa387 - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::try_with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:513:12
  87:     0x7f9660caa387 - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:477:20
  88:     0x7f9660caa387 - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:53:9
  89:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::plumbing::start_query::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:88:9
  90:     0x7f9660caa387 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context::<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:86:36
  91:     0x7f9660caa387 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context_opt::<rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:75:18
  92:     0x7f9660caa387 - rustc_middle[7526ec506fab00ca]::ty::context::tls::with_context::<rustc_query_impl[bf642988832e2c3b]::plumbing::start_query<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:86:5
  93:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::plumbing::start_query::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:75:5
  94:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job_non_incr::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:421:17
  95:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::execution::execute_job::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>, false>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:364:9
  96:     0x7f9660caa387 - rustc_query_impl[bf642988832e2c3b]::execution::try_execute_query::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>, false>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:317:13
  97:     0x7f9660f4648f - rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:677:32
  98:     0x7f9660f4648f - stacker[1d1c8a43f2803809]::maybe_grow::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  99:     0x7f9660f4648f - rustc_data_structures[a1cca6a08c57096c]::stack::ensure_sufficient_stack::<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_data_structures/src/stack.rs:21:5
 100:     0x7f9660f4648f - rustc_query_impl[bf642988832e2c3b]::execution::execute_query_non_incr_inner::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/execution.rs:677:5
 101:     0x7f9660f4648f - rustc_query_impl[bf642988832e2c3b]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_query_impl/src/plumbing.rs:361:26
 102:     0x7f965e90220e - rustc_middle[7526ec506fab00ca]::query::inner::query_ensure::<rustc_middle[7526ec506fab00ca]::query::caches::SingleCache<rustc_middle[7526ec506fab00ca]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/query/inner.rs:63:9
 103:     0x7f965e90220e - <rustc_middle[7526ec506fab00ca]::query::plumbing::TyCtxtEnsureOk>::analysis
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/query/plumbing.rs:445:21
 104:     0x7f965e90220e - rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_driver_impl/src/lib.rs:325:29
 105:     0x7f965e90220e - rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt::<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/passes.rs:1015:23
 106:     0x7f965e90220e - <rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter::<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#1}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context.rs:859:37
 107:     0x7f965e90220e - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<<rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#1}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:56:9
 108:     0x7f965e90220e - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::try_with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<<rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#1}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#0}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:513:12
 109:     0x7f965e90220e - <std[c06b0f5e9ce3dfcd]::thread::local::LocalKey<core[1821190c7e0c726e]::cell::Cell<*const ()>>>::with::<rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context<<rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#1}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#0}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/local.rs:477:20
 110:     0x7f965e90220e - rustc_middle[7526ec506fab00ca]::ty::context::tls::enter_context::<<rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>::{closure#1}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context/tls.rs:53:9
 111:     0x7f965e90220e - <rustc_middle[7526ec506fab00ca]::ty::context::GlobalCtxt>::enter::<rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context.rs:859:9
 112:     0x7f965e90220e - <rustc_middle[7526ec506fab00ca]::ty::context::TyCtxt>::create_global_ctxt::<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>::{closure#2}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_middle/src/ty/context.rs:1068:13
 113:     0x7f965e90220e - rustc_interface[8b1a49937cb7b5cc]::passes::create_and_enter_global_ctxt::<core[1821190c7e0c726e]::option::Option<rustc_interface[8b1a49937cb7b5cc]::queries::Linker>, rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}::{closure#2}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/passes.rs:982:5
 114:     0x7f965e91df33 - rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_driver_impl/src/lib.rs:298:22
 115:     0x7f965e91df33 - rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler::<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/interface.rs:500:80
 116:     0x7f965e91df33 - <core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}::{closure#0}> as core[1821190c7e0c726e]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panic/unwind_safe.rs:274:9
 117:     0x7f965e91df33 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::do_call::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:581:40
 118:     0x7f965e91df33 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::<(), core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:544:19
 119:     0x7f965e91df33 - std[c06b0f5e9ce3dfcd]::panic::catch_unwind::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panic.rs:359:14
 120:     0x7f965e91df33 - rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler::<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/interface.rs:500:23
 121:     0x7f965e90d655 - rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals::<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/util.rs:204:17
 122:     0x7f965e90d655 - rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/util.rs:159:24
 123:     0x7f965e90d655 - <scoped_tls[6075db748065b618]::ScopedKey<rustc_span[96b95645e4d1c03c]::SessionGlobals>>::set::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>
                               at /rust/deps/scoped-tls-1.0.1/src/lib.rs:137:9
 124:     0x7f965e90d655 - rustc_span[96b95645e4d1c03c]::create_session_globals_then::<(), rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_span/src/lib.rs:141:21
 125:     0x7f965e90d655 - rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/compiler/rustc_interface/src/util.rs:155:17
 126:     0x7f965e90d655 - std[c06b0f5e9ce3dfcd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/backtrace.rs:166:18
 127:     0x7f965e924b63 - std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/lifecycle.rs:91:13
 128:     0x7f965e924b63 - <core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}> as core[1821190c7e0c726e]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/panic/unwind_safe.rs:274:9
 129:     0x7f965e924b63 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::do_call::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:581:40
 130:     0x7f965e924b63 - std[c06b0f5e9ce3dfcd]::panicking::catch_unwind::<(), core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panicking.rs:544:19
 131:     0x7f965e924b63 - std[c06b0f5e9ce3dfcd]::panic::catch_unwind::<core[1821190c7e0c726e]::panic::unwind_safe::AssertUnwindSafe<std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/panic.rs:359:14
 132:     0x7f965e924b63 - std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked::<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/thread/lifecycle.rs:89:26
 133:     0x7f965e924b63 - <std[c06b0f5e9ce3dfcd]::thread::lifecycle::spawn_unchecked<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_with_globals<rustc_interface[8b1a49937cb7b5cc]::util::run_in_thread_pool_with_globals<rustc_interface[8b1a49937cb7b5cc]::interface::run_compiler<(), rustc_driver_impl[99f647836f16c82a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[1821190c7e0c726e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc-dev/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/core/src/ops/function.rs:250:5
 134:     0x7f9661f1126f - <alloc[ef773830cf77dad2]::boxed::Box<dyn core[1821190c7e0c726e]::ops::function::FnOnce<(), Output = ()> + core[1821190c7e0c726e]::marker::Send> as core[1821190c7e0c726e]::ops::function::FnOnce<()>>::call_once
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/alloc/src/boxed.rs:2240:9
 135:     0x7f9661f1126f - <std[c06b0f5e9ce3dfcd]::sys::thread::unix::Thread>::new::thread_start
                               at /rustc/ea5573a6c6e5e932f917ec4a8e6d8efdeb9f394d/library/std/src/sys/thread/unix.rs:118:17
 136:     0x7f965bca598b - <unknown>
 137:     0x7f965bd29a0c - <unknown>
 138:                0x0 - <unknown>

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (ea5573a6c 2026-03-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z next-solver=globally -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `ret_ref_local`
#1 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0207, E0601.
For more information about an error, try `rustc --explain E0207`.

```

</p>
</details>

@rustbot label +F-inherent_associated_types +WG-trait-system-refactor

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes rust-lang/rust#153539.

Type mismatch diagnostics in `note_and_explain_type_err` currently route both `ty::Projectio`n and `ty::Inherent`
through the same associated-type suggestion path. For inherent associated types, that path can reach helpers that
are only valid for trait projections.

### CODE REVIEW

File: tests/ui/associated-inherent-types/inherent-assoc-ty-mismatch-issue-153539.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
+//@ compile-flags: -Znext-solver=globally
+#![feature(inherent_associated_types)]
+//~^ WARN the feature `inherent_associated_types` is incomplete
```
Comment (Kivooeo) [inline tests/ui/associated-inherent-types/inherent-assoc-ty-mismatch-issue-153539.rs]:
```suggestion
#![expect(incomplete_features)]
```

**Review by Kivooeo — APPROVED** [review]
one nit

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153643/595f14b02216a127df89326d03a7f4e22cd4067f..a92006f5c99f551fe7367e35532b398aa462474a)*

File: tests/ui/associated-inherent-types/inherent-assoc-ty-mismatch-issue-153539.rs (hunk 1 above)
Comment (TaKO8Ki) [reply tests/ui/associated-inherent-types/inherent-assoc-ty-mismatch-issue-153539.rs]: Thanks. I applied your suggestion.
