### PR TITLE
Fix several asm! related issues

### LINKED ISSUE #85247: rustc is too strict about reserved registers on ARM
Recently, [this commit](https://github.com/rust-lang/rust/commit/e6a731eb90fe3d47d89416e199832af4248399f6#diff-8818a2f974f5c898a567797bb58287139c8a4256ba8344e1e63eb556ac06bc82) came to my attention, as it added r9 to the list of LLVM-reserved registers on ARM according to rustc, breaking existing inline asm. I decided to look into this further, and found [this page](https://developer.arm.com/documentation/101754/0615/armclang-Reference/Compiler-specific-Keywords-and-Operators/Global-named-register-variables) (section "Restrictions") which concisely states under what conditions certain registers are reserved in the ABI (with regards to armclang as described in the page, but it applies more generally). The relevant points are:

- If RWPI (read-write position independent) code is enabled, R9 is reserved.
- If needed, R7 is reserved for the frame pointer in T32 mode, and R11 is reserved in A32 mode.

However, rustc reserves these registers unconditionally. This seems incorrect, as both RWPI and frame pointers can be disabled via codegen options or a custom target. In our case, the custom target file (`armv4t-none-eabi.json`) has both `"eliminate-frame-pointer": true` and `"relocation-model": "static"` set, but rustc will reject uses of r9 and r11 with their respective error messages ("r9 is used internally by llvm" and "frame pointer (r11) cannot be used as an operand").

### LINKED ISSUE #92378: inline assembly register limits aren't correct when using instruction_set attribute
First discussed [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/216763-project-inline-asm/topic/register.20limitations.20do.20not.20respect.20instruction_set.20attri.2E.2E.2E).

Quick summary: the set of what registers are available for inline assembly is related to the current target arch. However, the `instruction_set` attribute lets a function be compiled for what's effectively an alternate arch. This *should* allow the other arch's registers to be used, but currently that's not the case.

* Specifically for ARM a32/t32, the `thumb-mode` target attribute is either not present (a32) or present (t32) in the target, and using the `instruction_set` attribute lets you have the opposite mode.
* Note: The actual assembly code is already compiled correctly on LLVM's side, it's just that rustc gives you the incorrect register class limits.

Quoting **Amanieu's** Zulip post on the probable fix for this:

> You'd need to somehow remove the thumb-mode target feature from the list passed to the asm handling code in ast_lowering and intrinsicck when the containing function uses the a32 ISA.

### PR DESCRIPTION
**Pull request by Amanieu**
This is a combination of several fixes, each split into a separate commit. Splitting these into PRs is not practical since they conflict with each other.

Fixes #92378
Fixes #85247

r? @nagisa

### CODE REVIEW

File: compiler/rustc_typeck/src/collect.rs [hunk 1]
```diff
@@ -3267,6 +3268,24 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
     codegen_fn_attrs
 }
 
+/// Computes the set of target features used in a function for the purposes of
+/// inline assembly.
+fn asm_target_features<'tcx>(tcx: TyCtxt<'tcx>, id: DefId) -> &'tcx FxHashSet<Symbol> {
+    let mut target_features = tcx.sess.target_features.clone();
+    let attrs = tcx.codegen_fn_attrs(id);
```
Comment (nagisa) [inline compiler/rustc_typeck/src/collect.rs:3275]: I think one problem that this has is that `-Ctarget-feature` flag attributes are not accounted for here, to the best of my knowledge. This is something we should eventually fix (at the very least because `#[cfg(target_feature=...)]` honour the global flags.) One of the commits in https://github.com/rust-lang/rust/pull/87402 gets us partway towards a solution there by exposing the globally enabled features as a query, but those are still backend-specific names so not applicable for assembly quite yet.

File: compiler/rustc_passes/src/intrinsicck.rs [hunk 2]
```diff
@@ -369,16 +369,29 @@ impl<'tcx> ExprVisitor<'tcx> {
             // Note that this is only possible for explicit register
             // operands, which cannot be used in the asm string.
             if let Some(reg) = op.reg() {
+                // Some explicit registers cannot be used depending on the
+                // target. Reject those here.
+                if let InlineAsmRegOrRegClass::Reg(reg) = reg {
+                    if let Err(msg) = reg.validate(
+                        asm_arch,
+                        self.tcx.sess.relocation_model(),
```
Comment (nagisa) [inline compiler/rustc_passes/src/intrinsicck.rs:377]: Would it make sense to somehow make register reservations be part of the `asm_target_features` calculation? As both are (always?) used together, might as well return a structure that bundles the target features with the relocation model and maybe some other frequently shared information (target?) too.

**Comment by nagisa** [comment]
Overall seems like an improvement. I'm happy to r+ this with or without the 2nd comment being addressed.

The 1st comment is mostly just an observation and something to keep in mind, as it is not necessarily something we can easily fix right now anyway.

File: compiler/rustc_passes/src/intrinsicck.rs (hunk 2 above)
Comment (Amanieu) [reply compiler/rustc_passes/src/intrinsicck.rs:377]: I tried implementing this but I'm having some trouble working with the query system. I added an `asm_target_info` query which returns this struct:
```rust
#[derive(Debug, Clone, HashStable_Generic)]
pub struct InlineAsmTargetInfo<'a> {
    pub reloc_model: RelocModel,
    pub target_features: FxHashSet<Symbol>,
    pub target: &'a Target,
}
```

Specifically, I can't manage to get the `HashStable` derive work with this struct. Perhaps I'm using the query system wrong?

Comment (nagisa) [reply compiler/rustc_passes/src/intrinsicck.rs:377]: Hm, okay, lets leave it as is for the time being.

Having thought about it further, I'm no longer sure duplicating `Target` and `RelocModel` in the query system outputs for a specific `DefId` is the correct model, anyway.

**Comment by Manishearth** [comment]
```
tidy error: /checkout/compiler/rustc_typeck/src/collect.rs: too many lines (3010) (add `// ignore-tidy-filelength` to the file to suppress this error)
```

https://github.com/rust-lang-ci/rust/runs/5267509172?check_suite_focus=true

**Comment by Amanieu** [comment]
I'm not sure how I should deal with this, should I just add `// ignore-tidy-filelength` to collect.rs?

**Comment by nagisa** [comment]
The alternative would be to move the query implementation to somewhere else (maybe `rustc_passes::intrinsicck` which also provides a query implementation?).

But yeah, adding the comment is something you can do. In fact this comment was present in this file before https://github.com/rust-lang/rust/commit/bb0a2f985cb6e980cc026ea952733d53bb868f87.
