### PR TITLE
Don't complain on a single non-exhaustive 1-ZST

### LINKED ISSUE #115922: Regression in lint for non-exhaustive ZST in `repr(Transparent)`
Lifted from #78586

---

I believe this future compatibility warning was badly affected by #115334. Minimal repro:

```rust
// src/lib.rs

#[non_exhaustive]
pub struct ZeroSizedNonExhaustive {}
```

```rust
// src/main.rs

#![deny(warnings)]

#[repr(transparent)]
pub struct Transparent(repro::ZeroSizedNonExhaustive);

fn main() {}
```

As far as I understand what this issue is about, this code should be 100% fine. This issue is about preventing a previously-accepted `repr(transparent)` struct from ending up with contents which a transparent struct is not allowed to have, after a permissible size increase of a non-exhaustive formerly-ZST from a different crate.

That's not possible in the code above. `Transparent` continues to be a valid `repr(transparent)` struct if `ZeroSizedNonExhaustive` increases in size.

Regression in nightly-2023-09-18:

```console
error: zero-sized fields in `repr(transparent)` cannot contain external non-exhaustive types
 --> src/main.rs:6:24
  |
6 | pub struct Transparent(repro::ZeroSizedNonExhaustive);
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #78586 <https://github.com/rust-lang/rust/issues/78586>
  = note: this struct contains `ZeroSizedNonExhaustive`, which is marked with `#[non_exhaustive]`, and makes it not a breaking change to become non-zero-sized in the future.
```

@RalfJung @compiler-errors

_Originally posted by @dtolnay in https://github.com/rust-lang/rust/issues/78586#issuecomment-1722680482_

### PR DESCRIPTION
**Pull request by compiler-errors**
r? RalfJung, though you mentioned being busy, so feel free to reassign.

This doesn't actually attempt to make the diagnostic better, so when we have two non-exhaustive 1-ZSTs in a struct, we still just point to one. 🤷

Fixes #115922

### CODE REVIEW

File: tests/ui/repr/repr-transparent-non-exhaustive.rs [hunk 1]
```diff
@@ -93,4 +93,31 @@ pub struct T16(Sized, ExternalIndirection<NonExhaustiveVariant>);
...
+pub struct T20(NonExhaustive);
+// Okay, since it's the only field.
+
+#[repr(transparent)]
+pub struct T21(NonExhaustive, InternalNonExhaustive);
+// Okay, since there's only 1 foreign non-exhaustive type.
+
+#[repr(transparent)]
+pub struct T22(NonExhaustive, InternalPrivate);
+// Okay, since there's only 1 foreign non-exhaustive type.
```
Comment (RalfJung) [inline tests/ui/repr/repr-transparent-non-exhaustive.rs:121]: Could you add tests where `NonExhaustive` is the 2nd field?

File: tests/ui/repr/repr-transparent-non-exhaustive.stderr [hunk 2]
```diff
@@ -123,5 +123,35 @@ LL | pub struct T16(Sized, ExternalIndirection<NonExhaustiveVariant>);
...
+   |
+   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+   = note: for more information, see issue #78586 <https://github.com/rust-lang/rust/issues/78586>
+   = note: this struct contains `NonExhaustive`, which is marked with `#[non_exhaustive]`, and makes it not a breaking change to become non-zero-sized in the future.
+
+error: zero-sized fields in `repr(transparent)` cannot contain external non-exhaustive types
+  --> $DIR/repr-transparent-non-exhaustive.rs:102:31
+   |
+LL | pub struct T18(NonExhaustive, NonExhaustive);
+   |                               ^^^^^^^^^^^^^
```
Comment (RalfJung) [inline tests/ui/repr/repr-transparent-non-exhaustive.stderr:140]: Seems fine to land this for now to fix the regression, but could you file a diagnostics issue about this? The error says "zero-sized fields [...] cannot contain external non-exhaustive types" but that's not really accurate, *some* zero-sized fields can in fact contain such non-exhaustive types.

Comment (compiler-errors) [reply tests/ui/repr/repr-transparent-non-exhaustive.stderr:140]: #115956

File: tests/ui/repr/repr-transparent-non-exhaustive.rs [hunk 3]
```diff
@@ -93,4 +93,44 @@ pub struct T16(Sized, ExternalIndirection<NonExhaustiveVariant>);
...
+#[repr(transparent)]
+pub struct T21Flipped(InternalNonExhaustive, NonExhaustive);
+// Okay, since there's only 1 foreign non-exhaustive type.
+
+#[repr(transparent)]
+pub struct T22(NonExhaustive, InternalPrivate);
+// Okay, since there's only 1 foreign non-exhaustive type.
+
+#[repr(transparent)]
+pub struct T22Flipped(NonExhaustive, InternalPrivate);
```
Comment (RalfJung) [inline tests/ui/repr/repr-transparent-non-exhaustive.rs:133]: This is identical to `T22`...?

Comment (compiler-errors) [reply tests/ui/repr/repr-transparent-non-exhaustive.rs:133]: Copy paste issue 🤦 

Should I just give these structs better names while we're at it? Like, the whole file?

**Comment by RalfJung** [comment]
r=me after fixing the test

File: tests/ui/repr/repr-transparent-non-exhaustive.rs (hunk 3 above)
Comment (RalfJung) [reply tests/ui/repr/repr-transparent-non-exhaustive.rs:133]: If you have good naming ideas, sure, why not.

Comment (compiler-errors) [reply tests/ui/repr/repr-transparent-non-exhaustive.rs:133]: Nothing comes to mind actually that isn't incredibly verbose. :sweat:
