### PR TITLE
Do not resolve associated const when there is no provided value

### LINKED ISSUE #98629: evaluation error hides "impl item missing" error
```rust
trait Trait {
    const N: usize;
}

impl Trait for i32 {}

fn f()
where
    [(); <i32 as Trait>::N]:,
{}

fn main() {}
```
results in
```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/main.rs:9:10
  |
9 |     [(); <i32 as Trait>::N]:,
  |          ^^^^^^^^^^^^^^^^^ referenced constant has errors
```
without showing that `N` is missing in the trait impl.

Taken from the comment by @carado in https://github.com/rust-lang/rust/issues/74713#issuecomment-882408859

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #98629, since now we just delay a bug when we're not able to evaluate a const item due to the value not actually being provided by anything. This means compilation proceeds forward to where the "missing item in impl" error is emitted.

----

The root issue here is that when we're looking for the defining `LeafDef` in `resolve_associated_item`, we end up getting the trait's AssocItem instead of the impl's AssocItem (which does not exist). This resolution "succeeds" even if the trait's item has no default value, and then since this item has no value to evaluate, it turns into a const eval error.

This root issue becomes problematic (as in #98629) when this const eval error happens in wfcheck (for example, due to normalizing the param-env of something that references this const). Since this happens sooner than the check that an impl actually provides all of the items that a trait requires (which happens during later typecheck), we end up aborting compilation early with only this un-informative message.

I'm not exactly sure _why_ this bug arises due to #96591 -- perhaps valtrees are evaluated more eagerly than in the old system?

r? @oli-obk or @lcnr since y'all are familiar with const eval and reviewed #96591, though feel free to reassign.

This is a regression from stable to beta, so I would be open to considering this for beta backport. It seems correct to me, especially given the improvements in the other UI tests this PR touches, but may have some side-effects that I'm unaware of...?

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 1]
```diff
@@ -185,14 +185,20 @@ pub fn is_const_evaluatable<'cx, 'tcx>(
         }
         let concrete = infcx.const_eval_resolve(param_env, uv.expand(), Some(span));
         match concrete {
-            Err(ErrorHandled::TooGeneric) => Err(if !uv.has_infer_types_or_consts() {
+            Err(ErrorHandled::TooGeneric) => Err(if uv.has_infer_types_or_consts() {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:188]: `TooGeneric` here is a bit of a misnomer, since it really should be "not concrete" or something.

File: compiler/rustc_ty_utils/src/instance.rs [hunk 2]
```diff
@@ -280,6 +280,11 @@ fn resolve_associated_item<'tcx>(
                 return Ok(None);
             }
 
+            // If the item does not have a value, then we cannot return an instance.
```
Comment (compiler-errors) [inline compiler/rustc_ty_utils/src/instance.rs:283]: The above note says:

```rust
// NOTE: This should be kept in sync with the similar code in
// `rustc_trait_selection::traits::project::assemble_candidates_from_impls()`.
```

but in this case, I think it's justified to keep these "out of sync". During typeck, we want to act like an item is there even if the impl is missing, so we don't get weird method probe and associated item resolution regressions. It's just that when we finally want to look for the `Instance` of that item, that should fail, since a concrete instance for it doesn't exist.

Comment (lcnr) [reply compiler/rustc_ty_utils/src/instance.rs:283]: this actually is consistent with project afaict

https://github.com/rust-lang/rust/blob/96c2df810b0b681fee63cae11ca63844792b6190/compiler/rustc_trait_selection/src/traits/project.rs#L1991-L2001

**Comment by lcnr** [comment]
r=me after dealing with the first comment

File: compiler/rustc_ty_utils/src/instance.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_ty_utils/src/instance.rs:283]: oh, that's great to find haha

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:188]: yeah, so `InferCtxt::const_eval_resolve` is not not doing what we need for this
https://github.com/rust-lang/rust/blob/03d488b48af9f66b91e9400387f781b82411fa82/compiler/rustc_infer/src/infer/mod.rs#L1664-L1671

I guess what we should do is:
match on `AbstractConst::new(self.tcx, unevaluated.shrink());`

`Ok(None)` is already correct.
`Err(emitted) ` -> `NotConstEvaluatable::Error(emitted)`
`Ok(Some(x))` -> the inference vars aren't used in the anon const, replace them with placeholders

feel free to do that in this PR, otherwise r=me

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:188]: @lcnr: I'm gonna do it in a follow-up PR, since this solution doesn't really _rely_ on that change, does it?

**Comment by pnkfelix** [comment]
Discussed in T-compiler meeting. Declining to backport, though if someone wants to make a strong argument for it, you can renominate.

(The heart of the discussion is that I was/am nervous about the change, while @oli-obk 's opinion is that "the fix is fairly simple and the problem is annoying to debug when hit". I'm mainly curious to know how @lcnr feels, since they had suggestions on follow-up changes that should be made to this code as well.)

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/pull/99590#issuecomment-1192204954) 

@bors r-
