### PR TITLE
[musl] use posix_spawn if a directory change was requested

### LINKED ISSUE #99740: posix_spawn_file_actions_addchdir_np lookup doesn't work on linux musl
I tried this code:

```rust
use std::process::Command;

let mut cmd = Command::new("ls");
cmd.current_dir(".");
cmd.output().unwrap();
```

(compiled under x86_64-unknown-linux-musl)

I expected to see this happen:

The `posix_spawn` fast path is used.

Instead, this happened:

Rust fell back to the fork/exec slow path. (Inspected this using gdb and strace).

This is presumably because https://github.com/rust-lang/rust/blob/6dbae3ad19309bb541d9e76638e6aa4b5449f29a/library/std/src/sys/unix/process/process_unix.rs#L442-L447 does a dynamic symbol lookup but musl causes binaries to be statically linked.

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
binary: rustc
commit-hash: 93ffde6f04d3d24327a4e17a2a2bf4f63c246235
commit-date: 2022-07-23
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by sunshowers**
Currently, not all libcs have the `posix_spawn_file_actions_addchdir_np` symbol available to them. So we attempt to do a weak symbol lookup for that function. But that only works if libc is a dynamic library -- with statically linked musl binaries the symbol lookup would never work, so we would never be able to use it even if the musl in use supported the symbol.

Now that Rust has a minimum musl version of 1.2.3, all supported musl versions now include this symbol, so we can unconditionally expect it to be there. This symbol was added to libc in https://github.com/rust-lang/libc/pull/3949 -- use it here.

I couldn't find any tests for whether the posix_spawn path is used, but I've verified with cargo-nextest that this change works. This is a substantial improvement to nextest's performance with musl. On my workstation with a Ryzen 7950x, against https://github.com/clap-rs/clap at
61f5ee514f8f60ed8f04c6494bdf36c19e7a8126:

Before:

```
     Summary [   1.071s] 879 tests run: 879 passed, 0 skipped
```

After:

```
     Summary [   0.392s] 879 tests run: 879 passed, 0 skipped
```

Fixes #99740.

try-job: dist-various-1
try-job: dist-various-2

### CODE REVIEW

**Comment by the8472** [comment]
> I couldn't find any tests for whether the posix_spawn path is used

Well, `posix_spawn` is an implementation detail, so there's no API that would let you distinguish that.

But you can do the opposite: Have a test that covers `command.current_dir()` (this test already exists) and hope that it uses posix_spawn (which can be manually verified via strace) and then write a second test that combines `current_dir` and `pre_exec` to make sure the fork path gets exercised too.

**Comment by workingjubilee** [comment]
Hm. I guess one can write internal unit-tests where the APIs are exposed? But doing that with multiprocess situations sounds... treacherous.

**Comment by sunshowers** [comment]
Yeah, a test attempting to exercise both paths sounds good. I'll work on that once #131823 lands.

> Hm. I guess one can write internal unit-tests where the APIs are exposed? But doing that with multiprocess situations sounds... treacherous.

What I would personally do is abstract the posix_spawn/fork decision into a function which returns an enum, and test that. I don't know how feasible that is, and I'd rather not block this relatively straightforward PR on that refactor :)

**Comment by workingjubilee** [comment]
Yeah, I don't wanna scope creep ya.

**Comment by sunshowers** [comment]
All right, rebased and added a test to exercise both paths.

File: library/std/src/process/tests.rs [hunk 1]
```diff
@@ -96,9 +96,23 @@ fn stdout_works() {
 #[test]
 #[cfg_attr(any(windows, target_os = "vxworks"), ignore)]
 fn set_current_dir_works() {
+    // On many Unix platforms this will use the posix_spawn path.
```
Comment (klensy) [inline library/std/src/process/tests.rs:99]: This test is `any(windows, target_os = "vxworks")`, is it right place to test musl :-)?

File: library/std/src/sys/pal/unix/process/process_unix.rs [hunk 2]
```diff
@@ -871,6 +865,42 @@ impl Command {
...
+    unsafe extern "C" fn(*mut libc::posix_spawn_file_actions_t, *const libc::c_char) -> libc::c_int;
+
+/// Get the function pointer for adding a chdir action to a
+/// `posix_spawn_file_actions_t`, if available, assuming a dynamic libc.
+///
+/// Some platforms can set a new working directory for a spawned process in the
+/// `posix_spawn` path. This function looks up the function pointer for adding
+/// such an action to a `posix_spawn_file_actions_t` struct.
+#[cfg(not(all(target_os = "linux", target_env = "musl")))]
+fn get_posix_spawn_addchdir() -> Option<PosixSpawnAddChdirFn> {
```
Comment (workingjubilee) [inline library/std/src/sys/pal/unix/process/process_unix.rs:878]: Unfortunately, you've moved this to the top of scope in a sensible-seeming fashion. Unfortunately, this is only called within `posix_spawn`, which not every platform calls to begin with. Indeed, many `cfg` it away! So this will not be called at all on platforms that don't match this cfg:
```rust
    #[cfg(any(
        target_os = "freebsd",
        all(target_os = "linux", target_env = "gnu"),
        all(target_os = "linux", target_env = "musl"),
        target_os = "nto",
        target_vendor = "apple",
    ))]
```

But it will still be defined for those. For those which aren't in the above set, but do use `process_unix.rs`, then they will see an unused function, and then libstd will not build.

Comment (sunshowers) [reply library/std/src/sys/pal/unix/process/process_unix.rs:878]: Ah, right...

I guess I could probably move the function item to be function-local.

**Comment by workingjubilee** [comment]
yep, goes kaput on the solaris build.

you may want to cross-compile for the illumos stdlib.

File: library/std/src/sys/pal/unix/process/process_unix.rs (hunk 2 above)
Comment (workingjubilee) [reply library/std/src/sys/pal/unix/process/process_unix.rs:878]: That's probably easiest, yeah.

Comment (sunshowers) [reply library/std/src/sys/pal/unix/process/process_unix.rs]: All right, updated, that seems to work.

**Comment by workingjubilee** [comment]
nice!
@bors r+ rollup
