### PR TITLE
Replace const eval limit by a lint and add an exponential backoff warning

### LINKED ISSUE #67217: Tracking issue for const_eval_limit: configurable, per-item instruction limit for CTFE
Currently, the const evaluator will continue forever if the program it is executing never terminates. There's a mechanism for detecting trivial infinite loops during const-eval, but this can't catch [every non-terminating program](https://en.wikipedia.org/wiki/Alan_Turing).

We should have a configurable instruction limit for CTFE that's set to a relatively low initial value. Furthermore, disabling the instruction limit should also disable the infinite loop detector, since the user has indicated that they expect their program to execute for a long time.

The existing [`#![recursion_limit]` and `#![type_length_limit]` attributes](https://doc.rust-lang.org/reference/attributes/limits.html) are somewhat related, but it would be ideal if the instruction limit could be applied per-item as well.

cc @rust-lang/wg-const-eval 

As of 2022-01-31, the default `const_eval_limit` is 1_000_000:
https://github.com/rust-lang/rust/blob/af46699f8104ba5257d0da56d3d817bf8fc751cf/compiler/rustc_middle/src/middle/limits.rs#L40

### LINKED ISSUE #93481: Long-running const-eval (loops) unusable in practice.
I've recently hit the problem of the hard error in the case when there is no infinite loop: [my code](https://github.com/kirillbobyrev/pabi/blob/c47d4ab5e4821a78e39f223577e6418f52ce4282/src/chess/attacks.rs) generates [PEXT Bitboards](https://www.chessprogramming.org/BMI2#PEXTBitboards) for a chess engine and it requires few seconds to finish but it's certainly not an infinite loop. The problem is that it forces me into either computing in the build time and going the code generation route (which is not pleasant) or having to only allow Rust Nightly which is maybe even less pleasant.

_Originally posted by @kirillbobyrev in https://github.com/rust-lang/rust/issues/71800#issuecomment-1025160363_

### LINKED ISSUE #103814: const eval interpreter step limit being hit on nightly for long-running while loop
I tried this code ([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=85f8150632aa71f6afd230706bbb86c8)):

```rust
const _DUMMY: u8 = {
    let mut data = [0; 131072];
    let mut idx = 0;
    while idx < data.len() {
        data[idx] = idx as u8;
        idx += 1;
    }
    5
};

#[test]
fn check() { }
```

I expected to see this happen: Code compiles, test runs and passes.

Instead, this happened: Code fails to compile, due to:

```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/lib.rs:6:9
  |
6 |         idx += 1;
  |         ^^^^^^^^ exceeded interpreter step limit (see `#[const_eval_limit]`)

For more information about this error, try `rustc --explain E0080`.
``` 

It does not occur on stable or beta.

(To be clear: I suspect this might be a const-eval implementation artifact that we cannot readily address. But we may need to figure out how to give better guidance, since the current diagnostic is telling people to muck with an attribute that is not available without opting into a feature gate.)

### Meta

`rustc --version --verbose`:
```
Nightly channel

Build using the Nightly version: 1.67.0-nightly

(2022-10-30 77e57db384aca99444c3)
```

### PR DESCRIPTION
**Pull request by oli-obk**
The lint triggers at the first power of 2 that comes after 1 million function calls or traversed back-edges (takes less than a second on usual programs). After the first emission, an unsilenceable warning is repeated at every following power of 2 terminators, causing it to get reported less and less the longer the evaluation runs.

cc @rust-lang/wg-const-eval 

fixes #93481
closes #67217

### CODE REVIEW

**Comment by fee1-dead** [comment]
Welcome to Rust, oli-obk!

**Comment by oli-obk** [comment]
Nominating for T-lang discussion. Are y'all on board with having no limit on the amount of time/steps constant evaluation can take, and instead just linting on long running evaluations to keep the users aware that the compiler is still busy doing things? It does mean `const FOO: () = loop {};` will just make the the compiler never finish (though emit a warning every now and then).

If the lint is `deny`d, the evaluation stops at the first time the warning is hit. We could also make the lint `deny` by default, to require users to opt-in to long running const eval on a per-crate, module or even constant level via the regular lint mechanics.

Note that if a dependency has an infinite loop, this lint will not be shown by cargo and the dependency will just be locked forever if it allowed/warned the lint.

**Comment by inquisitivecrystal** [comment]
> Note that if a dependency has an infinite loop, this lint will not be shown by cargo and the dependency will just be locked forever if it allowed/warned the lint.

Why don't we just write a program to figure out if the constant evaluation will eventually halt? It can't be *that* hard [(this is a joke).](https://en.wikipedia.org/wiki/Halting_problem)

A more serious comment: I'd find it a bit surprising as a user if the compiler kept on going forever. Would it be possible to set some sort of limit that's so ridiculously high we'd expect it to never be hit in a valid program (I'm thinking like, the equivalent of 30 seconds or one minute of execution time, but you could even go longer)? I know it's not as conceptually nice as this approach, but I don't think most people are prepared to wait ten minutes for the compiler to stop running. At least that would avoid CI continuing until it timed out, for instance. 

If we want to avoid hard limits, this could be a deny by default lint, but one with a higher threshold than the warn by default lint. I guess the point I'm gesturing at here is that the point at which we want to start warning people and the point at which we want to error out might not be the same: they might actually be quite far apart.

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 1]
```diff
@@ -429,14 +430,36 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
-
-        ecx.machine.steps_remaining -= 1;
-        if ecx.machine.steps_remaining == 0 {
-            throw_exhaust!(StepLimitReached)
+        if let Some(new_steps) = ecx.machine.num_evaluated_terminators.checked_add(1) {
+            ecx.machine.num_evaluated_terminators = new_steps;
+            // Only report after a certain number of terminators have been evaluated and the
+            // current number of evaluated terminators is a power of 2. The latter gives us a cheap
+            // way to implement exponential backoff.
+            if new_steps > 1_000_000 && new_steps.count_ones() == 1 {
```
Comment (Nilstrieb) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:438]:
```suggestion
            if new_steps > 1_000_000 && new_steps.is_power_of_two() {
```
That should be just as efficient and a little nicer

**Comment by RalfJung** [comment]
FWIW the `-Zmiri-report-progress` flag also uses 1_000_000 as default value for how many blocks to wait before reporting progress. So :+1: on that default value.

However the next power of two will be pretty close, won't it? So the second report comes rather quick after the first...

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 2]
```diff
@@ -429,14 +430,36 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
+                let hir_id = ecx.best_lint_scope();
+                let is_error = ecx
+                    .tcx
+                    .lint_level_at_node(
+                        rustc_session::lint::builtin::LONG_RUNNING_CONST_EVAL,
+                        hir_id,
+                    )
+                    .0
+                    .is_error();
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:447]: Is this a special hack to abort execution immediately if the lint is denied? Please add a comment explaining that.

File: compiler/rustc_const_eval/src/interpret/eval_context.rs [hunk 3]
```diff
@@ -421,6 +422,15 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
     }
 
+    #[inline(always)]
+    /// Find the first stack frame that is within the current crate, if any, otherwise return the crate's HirId
+    pub fn best_lint_scope(&self) -> hir::HirId {
+        self.stack()
+            .iter()
+            .find_map(|frame| frame.body.source.def_id().as_local())
+            .map_or(CRATE_HIR_ID, |def_id| self.tcx.hir().local_def_id_to_hir_id(def_id))
+    }
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: Miri has its own logic for this... so this is pretty const_eval specific I think, and should be in the const_eval folder, not the general interpreter.

File: src/tools/tidy/src/ui_tests.rs [hunk 4]
```diff
@@ -7,7 +7,7 @@ use std::path::Path;
 
 const ENTRY_LIMIT: usize = 1000;
 // FIXME: The following limits should be reduced eventually.
-const ROOT_ENTRY_LIMIT: usize = 948;
+const ROOT_ENTRY_LIMIT: usize = 949;
```
Comment (RalfJung) [inline src/tools/tidy/src/ui_tests.rs:10]: What is this?^^

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 5]
```diff
@@ -3271,9 +3271,36 @@ declare_lint_pass! {
...
+    ///     }
+    /// };
+    /// ```
+    ///
+    /// {{produces}}
+    ///
+    /// ### Explanation
+    ///
+    /// Loops allow const evaluation to compute arbitrary code, but may also
+    /// cause infinite loops.
```
Comment (RalfJung) [inline compiler/rustc_lint_defs/src/builtin.rs:3298]:
```suggestion
    /// Loops during const evaluation may continue indefinitely without output from the compiler.
```

**Comment by RalfJung** [comment]
> A more serious comment: I'd find it a bit surprising as a user if the compiler kept on going forever. Would it be possible to set some sort of limit that's so ridiculously high we'd expect it to never be hit in a valid program (I'm thinking like, the equivalent of 30 seconds or one minute of execution time, but you could even go longer)? I know it's not as conceptually nice as this approach, but I don't think most people are prepared to wait ten minutes for the compiler to stop running. At least that would avoid CI continuing until it timed out, for instance.

If we set it to 30_000_000, which might be around 30s, I guarantee someone will be like "but I need just 2 million steps beyond that".^^ So then we need to still let users increase the limit. And worse someone might be using 29_999_999 steps and then MIR building changes and that puts their code above the threshold -- making the MIR building change a breaking change which is quite bad.

File: src/tools/tidy/src/ui_tests.rs (hunk 4 above)
Comment (oli-obk) [reply src/tools/tidy/src/ui_tests.rs:10]: Tidy shouted at me

Comment (RalfJung) [reply src/tools/tidy/src/ui_tests.rs:10]: That constant really needs documentation for what it even means...

Comment (Nilstrieb) [reply src/tools/tidy/src/ui_tests.rs:10]: I think that's the amount of UI tests not in a subdirectory. A number that should be as low as possible :)

Comment (est31) [reply src/tools/tidy/src/ui_tests.rs:10]: Yeah @c410-f3r is regularly filing PRs to reduce that number, e.g. #102938

**Comment by marmeladema** [comment]
Should that limit be user configurable then?

**Comment by est31** [comment]
Some analysis, through experimentation I found that the change that caused #103814 decreased the highest compiling const eval limit from `166_665` to `124_999`. This corresponds to a 33% change in costs to the user on this particular benchmark (comparing nightlies `4b8f43199 2022-10-19` with `11ebe6512 2022-11-01`).

I think not having a limit, even if that limit is not perfect, removes control from users in a bad fashion. With this PR, if you allow the lint, because you do a lot of computation, you lose the protections from infinite loops that rustc gives you: It's an either-or descision without much flexibility. Furthermore, the limit is still there, it's just hardcoded, so you still can write code that skirts around the limit (like in the instance of #103814) and then it fails compilation down the line.

I'm also not sure about the UX impact of receiving 4 warnings for a const evaluation that runs for 10 seconds.

My proposal:

* Have two lints instead of exponential backoff, one which is warn by default (long_running_const_eval), and a second that is deny by default (very_long_running_const_eval).
* The second lint would trigger after 4 times the limit of the first lint was hit. That gives enough space for breaking changes to be noticed before they show up as errors. The second lint would exist so that CI jobs terminate. Personally I never really look at still-running CI, most times it's because of a limited number of github actions or something like that.
* The limit would still be configurable. It would be bound to MIR emitting changes, changes in how e.g. the `len` function on slices is implemented in std, or some other `const fn`'s are implemented in upstream crates. None of these changes alone should blow past the limit with a factor of 4. The limit would still be unstable, yes, but as we are talking about lints instead of errors now, this is less of a problem: lints are allowed to be unstable.
* The user-exposed limit might be given in multiples of thousands, and if there is some change in MIR generation that issues the lint for many people, that multiplier could be adjusted, e.g. to 1200, etc. Of course changes affect code snippets in hugely different ways, depending on which code they use.
* For further protection, if the lint is emitted, it would provide a suggested limit value that is 50% above what is actually needed.

One can also think about AST based cost systems which might be more robust, as AST changes less regularly than MIR, so you only have the noise from upstream crates that you need to worry about. The only problem is that it is probably a huge pain to move information on "how much does this operation cost" through the compiler. MIR optimizations are another issue.

File: compiler/rustc_const_eval/src/interpret/eval_context.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: Also, are we sure this is the lint scope we want?
For regular errors we always use the 'root' scope I think, from where the const was declared. Why use a different one here?

(Though also with that root scope I wonder about associated consts where 'declared' and 'instantiated' are separate spans... we are only showing one of them in the errors currently, I think, and caching will make it hard to take into account the 'instantiated' span.)

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: There is no root scope yet. I could add it, but it does fall fowl of associated/generic consts from other crates as you noted

**Comment by RalfJung** [comment]
I don't think user-defined limits are worth the complexity. These numbers have no absolute meaning and the relative scale changes over time. I think people just acknowledging "yes this const is slow please eval it anyway" is about all the flexibility we need. Crucially since this is a lint, MIR building changes can never break a dependency. I'm not even sure if we need the exponential back-off vs just a simple deny-by-default lint.

File: compiler/rustc_const_eval/src/interpret/eval_context.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: We have a root scope [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_const_eval/interpret/eval_context/struct.InterpCx.html#structfield.tcx).

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: The reason I walk the stack is that even using a root const from another crate, via generics onr of your own consts or const fns may show up in the stack, and you have control over that

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:432]: Yeah I get that, but it seems a bit random -- slight changes in MIR building might lead to a completely different stacktrace after N terminators. I think I'd prefer if we always only considered the root, I am just not sure if we can even do that properly for generics from other crates. Having to allow this on a per-crate level is not great either so a fallback to the entire local crate is suboptimal...

**Comment by pnkfelix** [comment]
The lang team [discussed this a bit yesterday](https://hackmd.io/YTNwrWjjT_a6krEbhQFRNA#%E2%80%9CRemove-const-eval-limit-and-implement-an-exponential-backoff-lint-instead%E2%80%9D-rust103877).

Executive summary:
 * In the long term, we would prefer a more stable metric to be employed here. 
   * @nikomatsakis has suggested sum of counting back-edges ("an edge in CFG where end dominates start") + procedure calls (where the counter is incremented even for mir-inlined calls).
   * @pnkfelix privately mused to @nikomatsakis whether counting ["mems"](https://en.wikipedia.org/wiki/Mem_(computing)) would be  more intuitive metric for end-users; but they agree that @nikomatsakis 's proposal of back-edges + calls should be more stable in the face of hypothetical future MIR optimizations.
   * (@nikomatsakis did privately note that even "back edges" is tricky, considering e.g. constructs like `.await` that expand into a loop)
* @nikomatsakis also expressed dismay over removing a supposed "guarantee" that every `rustc` invocation would terminate, but the team argued that we already lost that with proc-macros.
* We didn't make any decision about this specific PR, but the intutiion of @pnkfelix is that, even with the wrong metric, just moving to *some* lint is a step in the right direction toward making this *not* a hazard for people seeking to upgrade their copy of rustc.

**Comment by RalfJung** [comment]
> @nikomatsakis also expressed dismay over removing a supposed "guarantee" that every rustc invocation would terminate, but the team argued that we already lost that with proc-macros.

We can add an absolute limit of 2^48 steps or so if you want to still have that guarantee. ;)

**Comment by pnkfelix** [comment]
yes niko did make some side comment about heat death of universe while mulling over all of this

**Comment by jruderman** [comment]
Please keep some way to set a low limit, so that fuzzing (and regression tests for iloops) can continue to run quickly. It could be a `-Z` flag instead of a crate attribute, so programmers who aren't trying to test the compiler are less likely to create future-incompatible code.

**Comment by RalfJung** [comment]
Fuzzing of regular Rust code works with timeouts when executing the code. Fuzzing of const eval can do the same, can't it?

Anyway if you deny this lint you have basically the same limit as today.

**Comment by jruderman** [comment]
I'm trying to avoid timeout-kills because libfuzzer takes a long time to restart (at least the way I'm using it).

**Comment by pnkfelix** [comment]
Before this change, there was a hard error associated with hitting the internal const-eval limit. And thus there was a notion that every rust compilation is "always" guaranteed to terminate. (Note this was a flawed notion, since proc-macros do not currently have any such limit imposed on their execution.)

This PR changes that by turning this limit into a lint that can be allowed by the user.

I want lang team to sign off explicitly on the idea of introducing *some kind* of user-exposed limit that allows them 1. to change the limit on how long const-eval can proceed and 2. can introduce a new way for the compiler to infinite loop (i.e. by the user turning off the limit)

Things *not* in scope for the fcp discussion:
 * This PR also changes the underlying mechanism that drives the diagnostic machinery, namely by using exponential backoff, but I want to treat that as a detail associated with the lint=warn case; the lang team currently should focus solely on the question on whether we expose this as a user-controllable thing at all. In other words, the focus for this fcp should be on the fact that the lint can be set to `allow`.
 * The specific details of what metric is used is not under fcp. (@nikomatsakis and I agree that counting terminators executed is not a good metric to expose to users in the long term (it is too coupled to the internal details of MIR).)

@rfcbot fcp merge

**Comment by RalfJung** [comment]
FWIW, the (easy to implement) alternative here would be to still keep the lint a hard error with some limit that is picked very high (such that we expect compilation times on the order of tens of minutes at least before that case is hit). I'm thinking of at least 2^30 basic blocks, which would probably be around 15 minutes.

**Comment by joshtriplett** [comment]
@pnkfelix Are you proposing that the lint be warn-by-default (e.g. warn and keep going, so that the user knows that const evaluation is happening but taking a long time)? I'd be happy to support warn-by-default, but I don't think this should be deny-by-default.

**Comment by bjorn3** [comment]
Do we want `--cap-lints` to affect this lint? If it affects this lint, it will be silenced unconditionally for non-local dependencies. You wouldn't get as much as a warning.

**Comment by joshtriplett** [comment]
@bjorn3 That's a really good point. This is kinda abusing the lint machinery for what's effectively an optional progress indicator. I do think it's important that these show up even in dependencies (otherwise we don't get that progress indicator), but I don't think we should let them cause compilation failures that wouldn't otherwise have happened.

**Comment by pnkfelix** [comment]
@rfcbot concern dont-use-lints-for-this

lang team [discussed this](https://hackmd.io/KKdZGYuXSlakfo-vWdA5DA?view#%E2%80%9CRemove-const-eval-limit-and-implement-an-exponential-backoff-lint-instead%E2%80%9D-rust103877) in triage today.

main outcome was that the group was (eventually) in favor of removing the hard limit and putting some kind of progress indicator in place.

but the lang team was also opposed to using lint machinery to implement this, due to the point raised by @bjorn3 about interactions with `--cap-lints` and moreover the fact that we want these progress indicators to be reported for upstream crates that are being compiled.

So, we overall want to see something *like* this, but we do not want it to be based on lint machinery.

**Comment by oli-obk** [comment]
I changed it into an unsilencable warning after the first occurrence. In the changed test that means the first warning comes after 20s. The old hard limit was 2s, and we still emit the deny-by-default lint at that limit once.

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 6]
```diff
@@ -429,14 +430,44 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
-        if ecx.machine.steps_remaining == 0 {
-            return Ok(());
-        }
-
-        ecx.machine.steps_remaining -= 1;
-        if ecx.machine.steps_remaining == 0 {
-            throw_exhaust!(StepLimitReached)
+        if let Some(new_steps) = ecx.machine.num_evaluated_terminators.checked_add(1) {
+            ecx.machine.num_evaluated_terminators = new_steps;
+            if new_steps == 1_000_000 {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:435]: Please move this number into a `const`

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 7]
```diff
@@ -429,14 +430,44 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
+                    |diag| diag,
+                );
+                if is_error {
+                    let guard = ecx
+                        .tcx
+                        .sess
+                        .delay_span_bug(ecx.tcx.span, "The deny lint should have already errored");
+                    throw_inval!(AlreadyReported(guard));
+                }
+            } else if new_steps > 10_000_000 && new_steps.count_ones() == 1 {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:462]: Why not `is_power_of_two`?

Also, another number to please put into a `const`.

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 8]
```diff
@@ -429,14 +430,44 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
+                    .0
+                    .is_error();
+                ecx.tcx.struct_span_lint_hir(
+                    rustc_session::lint::builtin::LONG_RUNNING_CONST_EVAL,
+                    hir_id,
+                    ecx.tcx.span,
+                    "this constant is taking a long time to get evaluated",
+                    |diag| diag,
+                );
+                if is_error {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:455]:
```suggestion
                // If this was a hard error, don't bother continuing evaluation.
                if is_error {
```

**Comment by RalfJung** [comment]
Do we want a lint at all for this? Isn't the hard-coded warning enough? Maybe its threshold can be halved to be around 10s.

**Comment by oli-obk** [comment]
> Do we want a lint at all for this? Isn't the hard-coded warning enough? Maybe its threshold can be halved to be around 10s.

that's not the point to me. You'll usually not want evaluation to stop for `loop {}`, especially in CI or other places where you didn't think about rustc running forever and possibly only seeing its output when it's done.

**Comment by RalfJung** [comment]
Ah right, the point is that the lint is *deny* by default and hence actually stops execution.

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 9]
```diff
@@ -429,14 +438,45 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
-        if ecx.machine.steps_remaining == 0 {
-            return Ok(());
-        }
-
-        ecx.machine.steps_remaining -= 1;
-        if ecx.machine.steps_remaining == 0 {
-            throw_exhaust!(StepLimitReached)
+        if let Some(new_steps) = ecx.machine.num_evaluated_terminators.checked_add(1) {
+            ecx.machine.num_evaluated_terminators = new_steps;
+            if new_steps == LINT_TERMINATOR_LIMIT {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:443]:
```suggestion
            // By default, we have a *deny* lint kicking in after some time
            // to ensure `loop {}` doesn't just go forever.
            // In case that lint got reduced, in particular for `--cap-lint` situations, we also
            // have a hard warning shown every now and then for really long executions.
            if new_steps == LINT_TERMINATOR_LIMIT {
```

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 10]
```diff
@@ -299,19 +294,17 @@ pub fn eval_to_allocation_raw_provider<'tcx>(
     let cid = key.value;
     let def = cid.instance.def.with_opt_param();
     let is_static = tcx.is_static(def.did);
+    let mut interpreter = CompileTimeInterpreter::new();
+    // Statics (and promoteds inside statics) may access other statics, because unlike consts
+    // they do not have to behave "as if" they were evaluated at runtime.
+    if tcx.is_static(def.did) {
```
Comment (fee1-dead) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs:300]:
```suggestion
    let mut interpreter = CompileTimeInterpreter::new();
    // Statics (and promoteds inside statics) may access other statics, because unlike consts
    // they do not have to behave "as if" they were evaluated at runtime.
    if tcx.is_static(def.did) {
```

**Review by fee1-dead — APPROVED** [review]
impl looks ok.

**Comment by pnkfelix** [comment]
I'm beta-nominating this so that we actually have the conversation today about whether to back port this PR, or "just" pump up the previous limit in beta to unbreak people while this moves forward in nightly.

@rustbot label: beta-nominated

**Comment by pnkfelix** [comment]
Oh never mind, this doesn't affect the current beta. So we're okay as long as this lands in nightly relatively soon.

@rustbot label: -beta-nominated

**Comment by oli-obk** [comment]
The test in the first issue passes on stable and errors on beta/nightly: https://play.rust-lang.org/?version=beta&mode=debug&edition=2021

**Comment by RalfJung** [comment]
(bad playground link, doesn't actually contain particular code)

**Comment by fee1-dead** [comment]
> (bad playground link, doesn't actually contain particular code)

huh? Works fine for me.

**Comment by pnkfelix** [comment]
I'm going back to beta-nominating this, just to ensure that it gets discussed, but my suspicion is that we cannot jump directly to this in beta, as noted by @Mark-Simulacrum [here](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/decision.20on.20.22Remove.20const.20eval.20limit.22.20.23103877/near/310442264), and that instead for the immediate term, we need a totally different (trivial) PR that bumps up the hard-coded limit by 2x and beta-backport **that**

@oli-obk what do you think ^ ?

**Comment by pnkfelix** [comment]
@rfcbot resolve dont-use-lints-for-this 

based on [oli's change above](https://github.com/rust-lang/rust/pull/103877#issuecomment-1316556656), I believe the concerns about using lint machinery for this have been addressed.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I've been really worried about this but, given the fact that proc-macros exist today, I don't think we're crossing any new limits.

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs (hunk 10 above)
Comment (fee1-dead) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:303]: This suggestion got lost?

**Comment by fee1-dead** [comment]
r=me after resolving conflicts and fixing https://github.com/rust-lang/rust/pull/103877#discussion_r1045014473

**Comment by oli-obk** [comment]
@bryangarza is exploring a different (less flaky) metric than counting terminators: counting backedges taken. This should make sure we only count actual loops and thus be entirely stable. So I'm going to close this PR, as it's going to get replaced entirely

**Comment by oli-obk** [comment]
Sure, but even changing the algorithm, usually the number of loops (very generally, so any jump to a block that can end up in the current block again) stays the same unless you unroll. Even so, it will be stable across compiler changes.

**Comment by nikomatsakis** [comment]
There are effectively two concerns

* Can we make a metric that is stable across compiler changes.
* Can users update their code to use a new algorithm without hitting the limit.

@bryangarza's work on counting backedges is solving the first constraint, which is definitely desirable and needed regardless of what we do.

The second goal, from what I can see, can only possibly be achieved by moving to a warning. In other words, any attempt to impose a limit will mean that changes to const fns that ought not to affect clients might trip the limit. 

But even if we move to a warning ("this seems to be taking a long time..."), we want a stable metric to judge when to issue that warning, so that our behavior is independent from the machine we are running on and so forth.

**Comment by RalfJung** [comment]
Also what about recursion? Are all function calls counted or only "backedges" in the call graph?

**Comment by oli-obk** [comment]
Yea, function calls and back edges increment the counter, that should suffice in catching all issues and may even allow us to remove the existing recursion limit

**Comment by oli-obk** [comment]
Reopening now that we have said stable metric

**Review by lnicola — APPROVED** [review]
From the r-a side: these are a little easier to manage upstream, but shouldn't cause any problems.

File: src/tools/miri/tests/fail/const-ub-checks.stderr [hunk 11]
```diff
@@ -1,9 +1,24 @@
...
+<<<<<<< HEAD:src/tools/miri/tests/fail/const-ub-checks.stderr
 LL |     ptr.read();
    |     ^^^^^^^^^^ accessing memory with alignment ALIGN, but alignment ALIGN is required
+||||||| constructed merge base:src/test/ui/consts/const_limit/const_eval_limit_reached.stderr
+LL |     while x != 1000 {
+   |           ^^^^^^^^^ exceeded interpreter step limit (see `#[const_eval_limit]`)
+=======
+LL | const X: usize = {
+   | ^^^^^^^^^^^^^^
+>>>>>>> Remove const eval limit and implement an exponential backoff lint instead:src/test/ui/consts/const_limit/const_eval_limit_reached.stderr
```
Comment (fee1-dead) [inline src/tools/miri/tests/fail/const-ub-checks.stderr:21]: Is this a rebase artifact?

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 12]
```diff
@@ -569,13 +575,59 @@ impl<'mir, 'tcx> interpret::Machine<'mir, 'tcx> for CompileTimeInterpreter<'mir,
...
+                    .0
+                    .is_error();
+                let span = ecx.cur_span();
+                ecx.tcx.struct_span_lint_hir(
+                    rustc_session::lint::builtin::LONG_RUNNING_CONST_EVAL,
+                    hir_id,
+                    span,
+                    "constant evaluation is taking a long time",
+                    |diag| diag.span_label(ecx.tcx.span, "the constant being evaluated"),
+                );
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_const_eval/src/const_eval/machine.rs:611]: I tried... I have been having trouble with writing a lint with two spans in the structured diagnostics scheme. Will need to look at more examples.

File: src/tools/miri/tests/fail/const-ub-checks.stderr (hunk 11 above)
Comment (oli-obk) [reply src/tools/miri/tests/fail/const-ub-checks.stderr:21]: yea, miri testing was broken and just fixed in the last few hours, so tests didn't run at all.

File: compiler/rustc_const_eval/src/const_eval/machine.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (fee1-dead) [reply compiler/rustc_const_eval/src/const_eval/machine.rs:611]: I think you have to use `#[primary_span]` and `#[label]`

**Review by fee1-dead — APPROVED** [review]

**Comment by oli-obk** [comment]
🤔 seems like the low lint limit causes the ctfe stress benchmark to stop compiling

**Comment by RalfJung** [comment]
Shouldn't we consult t-lang about this?  This PR already [had an FCP](https://github.com/rust-lang/rust/pull/103877#issuecomment-1310223336) that [didn't go through](https://github.com/rust-lang/rust/pull/103877#issuecomment-1315785467). What changed since then?

**Comment by oli-obk** [comment]
The concern you linked was resolved and the FCP went through: https://github.com/rust-lang/rust/pull/103877#issuecomment-1344712562

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 13]
```diff
@@ -3377,9 +3377,36 @@ declare_lint_pass! {
...
+    ///
+    /// {{produces}}
+    ///
+    /// ### Explanation
+    ///
+    /// Loops allow const evaluation to compute arbitrary code, but may also
+    /// cause infinite loops or just very long running computations.
+    /// Without this lint, there is no output from the compiler indicating that
+    /// anything is happening.
+    /// Users can opt into long running computations by allowing the lint
```
Comment (est31) [inline compiler/rustc_lint_defs/src/builtin.rs:3403]: Given how there is an unsilenceable warning now a little bit after the lint fires, this comment should maybe be updated to not reccomend this to users any more?

**Comment by RalfJung** [comment]
> The concern you linked was resolved and the FCP went through: [#103877 (comment)](https://github.com/rust-lang/rust/pull/103877#issuecomment-1344712562)

Oh sorry, looks like I forgot half the discussion here.

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 13 above)
Comment (oli-obk) [reply compiler/rustc_lint_defs/src/builtin.rs:3403]: I don't understand. We should stop recommending to allow the lint? You need to allow the lint in order to get a long running const eval (and the warnings). If the lint is `deny`, const eval just stops before the first warning is emitted.

Comment (est31) [reply compiler/rustc_lint_defs/src/builtin.rs:3411]: Allowing the lint is neccessary, but it's not sufficient to get arbitrarily complex constant evaluation without warnings. There is no way to disable those warnings. Therefore I think it's creating false expectations if you advertise disabling the lint as opting in: when I have opted into something I don't want to be warned about it in addition.

The ability to disable the lint is more for temporary workarounds or something.

I'm not suggesting any functional changes here, the way this PR is implemented is good. I'm just saying that maybe this part of the docs should be adjusted as it might confuse readers about the intent (unless I misunderstood the reasoning behind why this PR is implemented in the way it is).

A proposal:

> Users can enable long running computations by allowing the lint on individual constants or for entire crates.
> #### Unconditional warnings
> Note that regardless of whether the lint is allowed or set to warn, the compiler will issue warnings if constant evaluation runs significantly longer than this lint's limit. These warnings are also shown to downstream users from crates.io or similar registries. If you are above the lint's limit, both you and downstream users might be exposed to these warnings. They might also appear on compiler updates, as the compiler makes minor changes about how complexity is measured: staying below the limit ensures that there is enough room, and given that the lint is disabled for people who use your dependency it means you will be the first to get the warning and can put out an update before it affects users.

Maybe it can be shortened a little but in general I think this information is very useful for users as it changes the meaning of the prior sentence a lot.

**Comment by oli-obk** [comment]
blocked on https://github.com/rust-lang/rustc-perf/pull/1598

**Comment by lqd** [comment]
Let's do a sanity check for the perf collector bump:

@bors try @rust-timer queue

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 13 above)
Comment (oli-obk) [reply compiler/rustc_lint_defs/src/builtin.rs]: I took most of your text and modified it a bit

**Review by fee1-dead — APPROVED** [review]
