### PR TITLE
Make lint missing-copy-implementations honor negative `Copy` impls

### LINKED ISSUE #101980: The allow-by-default lint `missing_copy_implementations` does not honor `!Copy` impls
I would expect the following code to compile successfully since we explicitly opt out of implementing `Copy`:

```rust
#![feature(negative_impls)]
#![deny(missing_copy_implementations)]
#![crate_type = "lib"]

pub struct Struct {
    pub field: i32,
}

impl !Copy for Struct {}
```

However, the code fails to compile with the following error message:

```
error: type could implement `Copy`; consider adding `impl Copy`
 --> src/lib.rs:5:1
  |
5 | / pub struct Struct {
6 | |     pub field: i32,
7 | | }
  | |_^
  |
note: the lint level is defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(missing_copy_implementations)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@rustbot label C-bug A-lint F-negative_impls

### PR DESCRIPTION
**Pull request by fmease**
Fixes #101980.

@rustbot label A-lint F-negative_impls

### CODE REVIEW

File: tests/ui/lint/missing-copy-implementations-negative-copy.rs
Comment (fmease) [inline tests/ui/lint/missing-copy-implementations-negative-copy.rs:1]: I haven't tested *conditional* negative `Copy` impls since those are broken anyway I think? See #79098.

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -745,6 +750,32 @@ impl<'tcx> LateLintPass<'tcx> for MissingCopyImplementations {
...
+    let obligation = traits::Obligation {
+        cause: traits::ObligationCause::dummy(),
+        param_env,
+        recursion_depth: 0,
+        predicate: ty::Binder::dummy(pred).to_predicate(tcx),
+    };
+
+    tcx.infer_ctxt()
+        .build()
+        .evaluate_obligation(&obligation)
```
Comment (b-naber) [inline compiler/rustc_lint/src/builtin.rs:774]: Can we use [`predicate_may_hold`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_trait_selection/infer/struct.InferCtxt.html#method.predicate_may_hold) here instead?

Comment (fmease) [reply compiler/rustc_lint/src/builtin.rs]: Now using `predicate_may_hold`. That's much shorter and legible, thanks for the suggestion!
However, I'm wondering if that could yield too many false positives since we're now considering *ambiguous* negative impls to apply (as well as ones that apply modulo opaque types).
Wouldn't `predicate_must_hold_modulo_regions` be a better fit?

Comment (b-naber) [reply compiler/rustc_lint/src/builtin.rs]: Yes, sorry about that. I think you're correct, `predicate_must_hold_modulo_regions` is the right method to use here I think.

Comment (fmease) [reply compiler/rustc_lint/src/builtin.rs]: Done

**Comment by spastorino** [comment]
> cc @spastorino for negative impls change

I'm working on different things related to negative impls but it makes sense to me that this lint honor negative `Copy` impls.
