### PR TITLE
Detect negative literal inferred to unsigned integer

### LINKED ISSUE #83413: Misleading error message with negative range
Given the following code: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=046e611931de232ad60923dac82f78b0)

```rust
fn main() {
  for x in -5..5 {
      do_something(x);
  }    
}

fn do_something(val: usize) {}
```

The current output is:

```
error[E0277]: the trait bound `usize: Neg` is not satisfied
 --> src/main.rs:2:12
  |
2 |   for x in -5..5 {
  |            ^^ the trait `Neg` is not implemented for `usize`

error: aborting due to previous error
```

This created confusion for a new Rust user on our team.

Ideally the range type would be inferred to be `i32`:

```
error[E0308]: mismatched types
 --> src/main.rs:3:20
  |
3 |       do_something(x);
  |                    ^ expected `usize`, found `i32`
  |
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
  |
3 |       do_something(x.try_into().unwrap());
  |                    ^^^^^^^^^^^^^^^^^^^^^
```

_Alternatively_ the output could mention why the type was inferred to be usize:

```
  |
2 |   for x in -5..5 {
  |            ^^ the trait `Neg` is not implemented for `usize`
  |
help: type `usize` was inferred due to call on line 3
  |
3 |      do_something(x);
  |                   ^
```

### PR DESCRIPTION
**Pull request by estebank**
```
error[E0277]: the trait bound `usize: Neg` is not satisfied
  --> $DIR/negative-literal-infered-to-unsigned.rs:2:14
   |
LL |     for x in -5..5 {
   |              ^^ the trait `Neg` is not implemented for `usize`
   |
help: consider specifying an integer type that can be negative
   |
LL |     for x in -5isize..5 {
   |                +++++
```

Applying this suggestion will always end up in another E0308 error at the point where the unsigned inference comes from, which should help with understanding what the actual problem is.

Fix rust-lang/rust#83413.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs [hunk 1]
```diff
@@ -950,6 +957,38 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
         Ok(())
     }
 
+    fn detect_negative_literal(
+        &self,
+        obligation: &PredicateObligation<'tcx>,
+        trait_pred: ty::PolyTraitPredicate<'tcx>,
+        err: &mut Diag<'_>,
+    ) -> bool {
+        if let ObligationCauseCode::BinOp { lhs_hir_id, .. } = obligation.cause.code()
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs]: while you're here, can you change `ObligationCauseCode` to not just be `BinOp` :sweat_smile: that's horribly confusing.

Looking at the way it's used I think it'd be better to just split it into `ObligationCauseCode::UnOp` and `ObligationCauseCode::BinOp`

**Review by lcnr — COMMENTED** [review]
r=me after handling my comment

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146042/523d3999dcd4bbd9a52661a29dbd7351a9c5fb03..18a36bccf5198dcc507d42e0daadcf2de4481741)*
