### PR TITLE
NLL: Fix bug in associated constant type annotations.

### LINKED ISSUE #57280: matching against an associated constant gives type error
Ever since #55937, the following program ([playground][]) gives an unexpected error from NLL:

[playground]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c864079c6a555e7960818b2fa82690cb

```rust
#![feature(nll)]

trait Foo {
    const Blah: &'static str;
}

struct Placeholder;

impl Foo for Placeholder {
    const Blah: &'static str = "hi";
}

fn foo(x: &str) {
    match x {
        <Placeholder as Foo>::Blah => { }
        _ => { }
    }
}
```

First reported by @Xanewok [in this comment](https://github.com/rust-lang/rust/pull/55937#issuecomment-450899521), because this broke the RLS.

cc @davidtwco

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #57280.

This PR reverses the variance used when relating types from the type
annotation of an associated constant - this matches the behaviour of the
lexical borrow checker and fixes a bug whereby matching a `&'a str`
against a `&'static str` would produce an error.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/build/matches/mod.rs [hunk 1]
```diff
@@ -308,11 +309,7 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                     block,
                     Statement {
                         source_info: ty_source_info,
-                        kind: StatementKind::AscribeUserType(
-                            place,
-                            ty::Variance::Invariant,
-                            user_ty,
-                        ),
+                        kind: StatementKind::AscribeUserType(place, variance, user_ty),
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_mir/build/matches/mod.rs]: I've updated the PR to have a `Option<ty::Variance>` so that - in every case other then associated constants - we can set this to `None` - I then use `.unwrap_or(..)` with `Invariant` or `Covariant` depending on what the code did previously. This means that we should be using the same variance as we did before, except for the associated constants case that this PR aims to fix where we override it.

File: src/librustc_mir/hair/cx/block.rs [hunk 2]
```diff
@@ -86,7 +87,8 @@ fn mirror_stmts<'a, 'gcx, 'tcx>(cx: &mut Cx<'a, 'gcx, 'tcx>,
                                     kind: Box::new(PatternKind::AscribeUserType {
                                         user_ty: PatternTypeProjection::from_user_type(user_ty),
                                         user_ty_span: ty.span,
-                                        subpattern: pattern
+                                        subpattern: pattern,
+                                        variance: ty::Variance::Invariant,
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/cx/block.rs]: I think this should be `Covariant`

File: src/librustc_mir/build/matches/mod.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc_mir/build/matches/mod.rs]: I think here we should write:

```rust
kind: StatementKind::AscribeUserType(place, ty::Invariant, user_ty),
```

and add a comment like this:

Note that we always use *invariant* as the variance here. This is because the `variance` field from the ascription refers to the variance to use when applying the type to the value being matched, but this ascription applies rather to the type of the binding. e.g., in this example:

```
let x: T = <expr>
```

we are creating an ascription that defines the type of `x` to be exactly `T` (i.e., with invariance). The `variance` field, in contrast, is intended to be used to relate `T` to the type of `<expr>`.

File: src/librustc_mir/hair/pattern/mod.rs [hunk 3]
```diff
@@ -91,6 +91,7 @@ pub enum PatternKind<'tcx> {
     AscribeUserType {
         user_ty: PatternTypeProjection<'tcx>,
         subpattern: Pattern<'tcx>,
+        variance: ty::Variance,
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/pattern/mod.rs]: Here we should add a comment:

Variance is to use when relating the type `user_ty` to the **type of the value being matched**. Typically, this is `Covariant`, since the value being matched must have a type that is some subtype of the ascribed type. 

Note that this variance does not apply for any bindings within `subpattern`. The type assigned to those bindings must be exactly equal to the `user_ty` given here.

The one place where this field is not `Covariant` is when matching constants, where we currently use `Contravariant` -- this is because the constant type just needs to be "comparable" to the type of the input value. So for example `match x { "foo" => .. }` requires that `&'static str <: T_x`, where `T_x` is the type of `x`. Really, we should probably be checking for a `PartialEq` impl instead, but this preserves the behavior of the old type-check for now. See #57280 for details.

File: src/librustc_mir/hair/pattern/mod.rs [hunk 4]
```diff
@@ -714,6 +715,7 @@ impl<'a, 'tcx> PatternContext<'a, 'tcx> {
                 },
                 user_ty: PatternTypeProjection::from_user_type(user_ty),
                 user_ty_span: span,
+                variance: ty::Variance::Invariant,
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/pattern/mod.rs]: Here we should use `Covariant` I believe

File: src/librustc_mir/hair/pattern/mod.rs [hunk 5]
```diff
@@ -763,6 +765,7 @@ impl<'a, 'tcx> PatternContext<'a, 'tcx> {
                                         kind: Box::new(
                                             PatternKind::AscribeUserType {
                                                 subpattern: pattern,
+                                                variance: ty::Variance::Contravariant,
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/pattern/mod.rs]: Here we should add a comment like 

"Note that use *Contravariant* here. See the `variance` field for details."

Or perhaps move that section of the `variance` field comment to here.

File: src/librustc_mir/build/matches/mod.rs [hunk 6]
```diff
@@ -541,7 +538,7 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
             PatternKind::Deref { ref subpattern } => {
                 self.visit_bindings(subpattern, pattern_user_ty.deref(), f);
             }
-            PatternKind::AscribeUserType { ref subpattern, ref user_ty, user_ty_span } => {
+            PatternKind::AscribeUserType { ref subpattern, ref user_ty, user_ty_span, .. } => {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/matches/mod.rs]: I would rather change `..` to `variance: _` and add a comment below:

---

Note that the variance doesn't apply here, as we are tracking the effect of `user_ty` on any bindings contained with `subpattern`.

File: src/librustc_mir/build/matches/simplify.rs [hunk 7]
```diff
@@ -56,11 +56,17 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
         let tcx = self.hir.tcx();
         match *match_pair.pattern.kind {
-            PatternKind::AscribeUserType { ref subpattern, ref user_ty, user_ty_span } => {
+            PatternKind::AscribeUserType {
+                ref subpattern,
+                variance,
+                ref user_ty,
+                user_ty_span
+            } => {
                 candidate.ascriptions.push(Ascription {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/matches/simplify.rs]: Here we could add a comment like:

Apply the type ascription to the value at `match_pair.place`, which is the value being matched, taking the variance field into account.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/build/matches/simplify.rs (hunk 7 above)
Comment (davidtwco) [reply src/librustc_mir/build/matches/simplify.rs]: Added.

File: src/librustc_mir/build/matches/mod.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_mir/build/matches/mod.rs]: Changed.

File: src/librustc_mir/hair/pattern/mod.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/hair/pattern/mod.rs]: Added.

File: src/librustc_mir/hair/pattern/mod.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_mir/hair/pattern/mod.rs]: Fixed.

File: src/librustc_mir/hair/pattern/mod.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/hair/pattern/mod.rs]: Added.

File: src/librustc_mir/build/matches/mod.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/build/matches/mod.rs]: Changed.

File: src/librustc_mir/hair/cx/block.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_mir/hair/cx/block.rs]: Changed.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
cc @rust-lang/infra -- this failure *looked* unrelated to the PR:
```
[01:48:24] test vec::test_splice_unbounded ... ok
[01:48:24] test vec::test_split_at_mut ... ok
[01:48:24] test vec::test_split_off ... ok
[01:48:24] test vec::test_swap_remove_empty ... ok
[01:48:25] died due to signal 11
```

**Comment by pietroalbini** [comment]
cc https://github.com/rust-lang/rust/issues/55861
