### PR TITLE
Fix `allow_internal_unstable` for `(min_)specialization`

### LINKED ISSUE #119950: `allow_internal_unstable` does not work for `min_specialization`
This also applies to proc macros
https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60SpecOptionPartialEq.60.20error

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=45d821a040bf825549fe07efa2c87572

```rs
#![allow(internal_features)]
#![feature(allow_internal_unstable)]

#[allow_internal_unstable(min_specialization)]
macro_rules! test {
    () => {
        struct T<U>(U);
        trait Tr {}
        impl<U> Tr for T<U> {}
        impl Tr for T<u8> {}
    }
}

test! {}
```
```rs
   Compiling playground v0.0.1 (/playground)
error[E0119]: conflicting implementations of trait `Tr` for type `T<u8>`
  --> src/lib.rs:10:9
   |
9  |         impl<U> Tr for T<U> {}
   |         ------------------- first implementation here
10 |         impl Tr for T<u8> {}
   |         ^^^^^^^^^^^^^^^^^ conflicting implementation for `T<u8>`
...
14 | test! {}
   | -------- in this macro invocation```

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #119950

Blocked on #119949 (comment doesn't make sense until that merges)

I'd like to follow this up and look for more instances of not properly checking spans for features but I wanted to fix the motivating issue.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/specialize/mod.rs [hunk 1]
```diff
@@ -144,8 +144,22 @@ pub(super) fn specializes(tcx: TyCtxt<'_>, (impl1_def_id, impl2_def_id): (DefId,
     // taking advantage of upstream ones.
     let features = tcx.features();
     let specialization_enabled = features.specialization || features.min_specialization;
-    if !specialization_enabled && (impl1_def_id.is_local() || impl2_def_id.is_local()) {
-        return false;
+    if !specialization_enabled && impl1_def_id.is_local() {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/specialize/mod.rs:147]: Could you leave a comment here explaining in prose what is being enforced? Just for clarity, for people scanning this in the future.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+
