### PR TITLE
Various changes to name resolution of anon consts

### LINKED ISSUE #111012: ICE for enum discriminant being a const generic
### Code

```Rust
pub enum E<const V: isize> {
    V = V,
}
```

### Meta

version from playground:
```
1.69.0 (84c898d65 2023-04-16)
```
also occurs on nightly, from playground:
```
rustc 1.71.0-nightly (87b1f891e 2023-04-29)
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: enum discriminant depends on generics
 --> src/lib.rs:2:9
  |
2 |     V = V,
  |         ^
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, &str>
             2: <rustc_hir_analysis::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
             3: <rustc_middle::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis::collect::CollectItemTypesVisitor>
             4: rustc_hir_analysis::collect::collect_mod_item_types
             5: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::collect_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
             6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_mod_item_types
             7: <rustc_middle::hir::map::Map>::for_each_module::<rustc_hir_analysis::check_crate::{closure#0}::{closure#0}::{closure#0}>
             8: <rustc_session::session::Session>::track_errors::<rustc_hir_analysis::check_crate::{closure#0}, ()>
             9: rustc_hir_analysis::check_crate
            10: rustc_interface::passes::analysis
            11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            13: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            14: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            15: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            16: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            17: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
            19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
            20: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys/unix/thread.rs:108:17
            21: start_thread
            22: clone
          

error: internal compiler error: enum discriminant depends on generics
 --> src/lib.rs:2:9
  |
2 |     V = V,
  |         ^
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, &str>
             2: <core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::VariantDef>>, <rustc_index::slice::IndexSlice<rustc_abi::VariantIdx, rustc_middle::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle::ty::adt::AdtDef>::discriminants::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(rustc_abi::VariantIdx, rustc_middle::ty::util::Discr), <alloc::vec::Vec<(rustc_abi::VariantIdx, rustc_middle::ty::util::Discr)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::VariantDef>>, <rustc_index::slice::IndexSlice<rustc_abi::VariantIdx, rustc_middle::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle::ty::adt::AdtDef>::discriminants::{closure#0}>>::{closure#0}>::{closure#0}>
             3: <alloc::vec::Vec<(rustc_abi::VariantIdx, rustc_middle::ty::util::Discr)> as alloc::vec::spec_from_iter::SpecFromIter<(rustc_abi::VariantIdx, rustc_middle::ty::util::Discr), core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::VariantDef>>, <rustc_index::slice::IndexSlice<rustc_abi::VariantIdx, rustc_middle::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle::ty::adt::AdtDef>::discriminants::{closure#0}>>>::from_iter
             4: rustc_hir_analysis::check::check::check_mod_item_types
             5: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
             6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
             7: <rustc_middle::hir::map::Map>::for_each_module::<rustc_hir_analysis::check_crate::{closure#6}::{closure#0}>
             8: <rustc_session::session::Session>::time::<(), rustc_hir_analysis::check_crate::{closure#6}>
             9: rustc_hir_analysis::check_crate
            10: rustc_interface::passes::analysis
            11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            13: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            14: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            15: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            16: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            17: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
            19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
            20: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys/unix/thread.rs:108:17
            21: start_thread
            22: clone
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (87b1f891e 2023-04-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground` (lib)
```

### PR DESCRIPTION
**Pull request by BoxyUwU**
Sorry this PR is kind of all over the place ^^'

Fixes #111012 

- Rewrites anon const nameres to all go through `fn resolve_anon_const` explicitly instead of `visit_anon_const` to ensure that we do not accidentally resolve anon consts as if they are allowed to use generics when they aren't. Also means that we dont have bits of code for resolving anon consts that will get out of sync (i.e. legacy const generics and resolving path consts that were parsed as type arguments)
- Renames two of the `LifetimeRibKind`, `AnonConst -> ConcreteAnonConst` and `ConstGeneric -> ConstParamTy`
- Noticed while doing this that under `generic_const_exprs` all lifetimes currently get resolved to errors without any error being emitted which was causing a bunch of tests to pass without their bugs having been fixed, incidentally fixed that in this PR and marked those tests as `// known-bug:`. I'm fine to break those since `generic_const_exprs` is a very unstable incomplete feature and this PR _does_ make generic_const_exprs "less broken" as a whole, also I can't be assed to figure out what the underlying causes of all of them are. This PR reopens #77357 #83993
- Changed `generics_of` to stop providing generics and predicates to enum variant discriminant anon consts since those are not allowed to use generic parameters
- Updated the error for non 'static lifetime in const arguments and the error for non 'static lifetime in const param tys to use `derive(Diagnostic)`

I have a vague idea why const-arg-in-const-arg.rs, in-closure.rs and simple.rs have started failing which is unfortunate since these were deliberately made to work, I think lifetime resolution being broken just means this regressed at some point and nobody noticed because the tests were not testing anything :( I'm fine breaking these too for the same reason as the tests for #77357 #83993. I couldn't get `// known-bug` to work for these ICEs and just kept getting different stderr between CI and local `--bless` so I just removed them and will create an issue to track re-adding (and fixing) the bugs if this PR lands.

r? @cjgillot cc @compiler-errors

### CODE REVIEW

File: tests/ui/const-generics/const-arg-in-const-arg.rs [hunk 1]
```diff
@@ -1,4 +1,20 @@
...
+// [full] normalize-stderr-test "DefId\([^)]*\)" -> "..."
+// [full] normalize-stderr-test "\nerror: internal compiler error.*\n\n" -> ""
+// [full] normalize-stderr-test "note:.*unexpectedly panicked.*\n\n" -> ""
+// [full] normalize-stderr-test "note: we would appreciate a bug report.*\n\n" -> ""
+// [full] normalize-stderr-test "note: compiler flags.*\n\n" -> ""
+// [full] normalize-stderr-test "note: rustc.*running on.*\n\n" -> ""
+// [full] normalize-stderr-test "thread.*panicked.*\n" -> ""
+// [full] normalize-stderr-test "stack backtrace:\n" -> ""
+// [full] normalize-stderr-test "\s\d{1,}: .*\n" -> ""
+// [full] normalize-stderr-test "\s at .*\n" -> ""
```
Comment (jyn514) [inline tests/ui/const-generics/const-arg-in-const-arg.rs:14]:
```suggestion
// [full] normalize-stderr-test "\s*\d{1,}: .*\n" -> ""
// [full] normalize-stderr-test "\s* at .*\n" -> ""
```

File: compiler/rustc_resolve/src/errors.rs [hunk 2]
```diff
@@ -326,6 +326,18 @@ pub(crate) struct ParamInTyOfConstParam {
     #[label]
     pub(crate) span: Span,
     pub(crate) name: Symbol,
+    #[subdiagnostic]
+    pub(crate) sub_is_type: Option<ParamInTyOfConstParamIsType>,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/errors.rs:330]: I don't understand this terminology. Is this the kind of the param that appears in type of const param?

File: compiler/rustc_resolve/src/errors.rs [hunk 3]
```diff
@@ -326,6 +326,18 @@ pub(crate) struct ParamInTyOfConstParam {
...
+}
+
+#[derive(Subdiagnostic)]
+pub(crate) enum ParamInTyOfConstParamIsType {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/errors.rs:334]: Ditto.

File: compiler/rustc_resolve/src/errors.rs [hunk 4]
```diff
@@ -539,3 +553,24 @@ pub(crate) struct CfgAccessibleUnsure {
...
+
+#[derive(Diagnostic)]
+#[diag(resolve_param_in_enum_discriminant)]
+pub(crate) struct ParamInEnumDiscriminant {
+    #[primary_span]
+    #[label]
+    pub(crate) span: Span,
+    pub(crate) name: Symbol,
+    #[subdiagnostic]
+    pub(crate) sub_is_type: ParamInEnumDiscriminantIsType,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/errors.rs:565]: Same question.

File: compiler/rustc_resolve/src/late.rs [hunk 5]
```diff
@@ -66,6 +66,15 @@ enum IsRepeatExpr {
     Yes,
 }
 
+#[derive(Copy, Clone, Debug, PartialEq, Eq)]
+/// Describes whether an `AnonConst` is a type level const arg or
+/// some other form of anon const (i.e. inline consts or enum discriminants)
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:71]: Nit: could you put the derive after the doc?

File: compiler/rustc_resolve/src/late.rs [hunk 6]
```diff
@@ -114,6 +123,12 @@ impl ConstantHasGenerics {
     }
 }
 
+#[derive(Copy, Clone, Debug, Eq, PartialEq)]
+pub(crate) enum NoConstantGenericsReason {
+    NonTrivialConstArg,
+    IsEnumDiscriminant,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:129]: Could you doc-comment those variants?

File: compiler/rustc_resolve/src/late.rs [hunk 7]
```diff
@@ -273,15 +288,17 @@ enum LifetimeRibKind {
     /// Signal we cannot find which should be the anonymous lifetime.
     ElisionFailure,
 
-    /// FIXME(const_generics): This patches over an ICE caused by non-'static lifetimes in const
-    /// generics. We are disallowing this until we can decide on how we want to handle non-'static
-    /// lifetimes in const generics. See issue #74052 for discussion.
-    ConstGeneric,
+    /// This rib forbids usage of generic parameters inside of const parameter types.
+    ///
+    /// See issue #74052 for discussion.
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:293]: Pre-existing: should that discussion be summarized here?

File: compiler/rustc_resolve/src/late.rs [hunk 8]
```diff
@@ -3920,27 +3945,60 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+        };
+
         self.with_constant_rib(
-            is_repeat,
-            if constant.value.is_potential_trivial_const_param() {
-                ConstantHasGenerics::Yes
-            } else {
-                ConstantHasGenerics::No
+            is_repeat_expr,
+            match anon_const_kind {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:3980]: Could you introduce a binding for this match?

File: compiler/rustc_resolve/src/late.rs [hunk 9]
```diff
@@ -66,6 +66,15 @@ enum IsRepeatExpr {
     Yes,
 }
 
+#[derive(Copy, Clone, Debug, PartialEq, Eq)]
+/// Describes whether an `AnonConst` is a type level const arg or
+/// some other form of anon const (i.e. inline consts or enum discriminants)
+enum AnonConstKind {
+    EnumDiscriminant,
+    InlineConst,
+    ConstArg(IsRepeatExpr),
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:75]: Should the repeat expr be a separate variant?

File: compiler/rustc_resolve/src/ident.rs [hunk 10]
```diff
@@ -1212,9 +1213,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                                     if let Some(span) = finalize {
                                         self.report_error(
                                             span,
-                                            ResolutionError::ParamInNonTrivialAnonConst {
-                                                name: rib_ident.name,
-                                                is_type: true,
+                                            match cause {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/ident.rs:1216]: Could make a binding for this match?

File: compiler/rustc_resolve/src/lib.rs [hunk 11]
```diff
@@ -223,11 +226,15 @@ enum ResolutionError<'a> {
...
+    ParamInTyOfConstParam { name: Symbol, is_type: Option<ParamInTyOfConstParamIsType> },
     /// generic parameters must not be used inside const evaluations.
     ///
     /// This error is only emitted when using `min_const_generics`.
-    ParamInNonTrivialAnonConst { name: Symbol, is_type: bool },
+    ParamInNonTrivialAnonConst { name: Symbol, is_type: ParamInNonTrivialAnonConstIsType },
+    /// generic parameters must not be used inside enum discriminants.
+    ///
+    /// This error is emitted even with `generic_const_exprs`.
+    ParamInEnumDiscriminant { name: Symbol, is_type: ParamInEnumDiscriminantIsType },
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/lib.rs:237]: Should NonTrivialConstArg take a NoConstantGenericsReason instead?

File: compiler/rustc_resolve/src/errors.rs [hunk 12]
```diff
@@ -539,3 +553,24 @@ pub(crate) struct CfgAccessibleUnsure {
     #[primary_span]
     pub(crate) span: Span,
 }
+
+#[derive(Diagnostic)]
+#[diag(resolve_param_in_enum_discriminant)]
+pub(crate) struct ParamInEnumDiscriminant {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/errors.rs:559]: Likewise, can this be merged with ParamInNonTrivialAnonConst?

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 13]
```diff
@@ -1190,13 +1190,15 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                     // parsing. We try to resolve that ambiguity by attempting resolution in both the
                     // type and value namespaces. If we resolved the path in the value namespace, we
                     // transform it into a generic const argument.
-                    TyKind::Path(qself, path) => {
+                    TyKind::Path(None, path) => {
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/lib.rs:1193]: Does this change deserve a test?

File: tests/ui/const-generics/late-bound-vars/in_closure.rs [hunk 14]
```diff
@@ -1,4 +1,21 @@
...
+// normalize-stderr-test "note: compiler flags.*\n\n" -> ""
+// normalize-stderr-test "note: rustc.*running on.*\n\n" -> ""
+// normalize-stderr-test "thread.*panicked.*\n" -> ""
+// normalize-stderr-test "stack backtrace:\n" -> ""
+// normalize-stderr-test "\s\d{1,}: .*\n" -> ""
+// normalize-stderr-test "\s at .*\n" -> ""
+// normalize-stderr-test ".*note: Some details.*\n" -> ""
+// normalize-stderr-test "\n\n[ ]*\n" -> ""
+// normalize-stderr-test "compiler/.*: projection" -> "projection"
+// this should run-pass
```
Comment (cjgillot) [inline tests/ui/const-generics/late-bound-vars/in_closure.rs:17]: Why does this ICE?

File: tests/ui/const-generics/late-bound-vars/in_closure.stderr [hunk 15]
```diff
@@ -0,0 +1,13 @@
+error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:882:36: cannot convert `ReFree(..., BrNamed(..., 'a))` to a region vidquery stack during panic:
```
Comment (cjgillot) [inline tests/ui/const-generics/late-bound-vars/in_closure.stderr:1]: We need to normalize the source path, to avoid meaningless changes.

File: tests/ui/const-generics/late-bound-vars/simple.rs [hunk 16]
```diff
@@ -1,4 +1,20 @@
...
+// normalize-stderr-test "note: we would appreciate a bug report.*\n\n" -> ""
+// normalize-stderr-test "note: compiler flags.*\n\n" -> ""
+// normalize-stderr-test "note: rustc.*running on.*\n\n" -> ""
+// normalize-stderr-test "thread.*panicked.*\n" -> ""
+// normalize-stderr-test "stack backtrace:\n" -> ""
+// normalize-stderr-test "\s\d{1,}: .*\n" -> ""
+// normalize-stderr-test "\s at .*\n" -> ""
+// normalize-stderr-test ".*note: Some details.*\n" -> ""
+// normalize-stderr-test "\n\n[ ]*\n" -> ""
+// normalize-stderr-test "compiler/.*: projection" -> "projection"
```
Comment (cjgillot) [inline tests/ui/const-generics/late-bound-vars/simple.rs:16]: Ditto, why does this ICE?

File: tests/ui/const-generics/const-arg-in-const-arg.rs [hunk 17]
```diff
@@ -1,4 +1,4 @@
-// revisions: full min
+// revisions: min
```
Comment (cjgillot) [inline tests/ui/const-generics/const-arg-in-const-arg.rs:1]: Why is the `full` revision gone?

File: tests/ui/const-generics/const-param-type-depends-on-const-param.full.stderr [hunk 18]
```diff
@@ -3,12 +3,16 @@ error[E0770]: the type of const parameters must not depend on other generic para
    |
 LL | pub struct Dependent<const N: usize, const X: [u8; N]>([(); N]);
    |                                                    ^ the type must not depend on the parameter `N`
+   |
+   = note: const parameters may not be used in the type of const parameters
```
Comment (cjgillot) [inline tests/ui/const-generics/const-param-type-depends-on-const-param.full.stderr:7]:
```suggestion
   = note: const parameters may not be used in the type of other const parameters
```
?

**Review by cjgillot — COMMENTED** [review]
Would it be possible to separate the changes to error types in their own commit, so they don't pollute semantic changes?

File: tests/ui/const-generics/const-param-type-depends-on-const-param.full.stderr (hunk 18 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/const-param-type-depends-on-const-param.full.stderr:7]: I think technically no because const parameters cannot be used in the type of themselves either- `const N: [(); N]` would error.

File: compiler/rustc_resolve/src/late.rs (hunk 7 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/late.rs:293]: I think the only really useful information in that issue is a link to rust-lang/project-const-generics#28 which cant be summarized very easily, I'll update this to directly point there instead.

File: compiler/rustc_resolve/src/late.rs (hunk 9 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/late.rs:75]: I think no, repeat expr counts are still const generic arguments except for their special case for back compat reasons (name res doesnt forbid type parameters, but evaluating them must be possible without providing a concrete value of the type parameter). We have a future compat lint currently for using type parameters in repeat expr counts that will hopefully become a hard error and this can just be `ConstArg,` and not have to track if its a repeat expr or not.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 13 above)
Comment (BoxyUwU) [reply compiler/rustc_ast_lowering/src/lib.rs:1193]: I have added `tests/ui/const-generics/assoc_const_as_type_argument.rs` which has the same behaviour as it does on stable and I think should exercise this codepath.

**Comment by BoxyUwU** [comment]
I think I've split the diagnostic changes out from the other changes, sorry I should have done that in the first place. I had thought it was going to be a lot harder to do retroactively, its not a perfect split but it should hopefully be much better now.

**Comment by BoxyUwU** [comment]
I tried to explain a bit in the PR description what is going on with the test/revision removals and things turning into ICEs but I think I didn't give enough information.

So for context (as i discovered while making this PR) right now on nightly lifetime resolution for anon consts under `feature(generic_const_exprs)` is really broken. Every lifetime you write that isnt `'_` or `'static` gets resolved to an error without an error actually having been emitted, this goes for when you do actually have a lifetime in scope (i.e. `fn foo<'a>() -> [(); { let _: &'a (); 10 }] {}`) or when you are writing lifetimes that haven't been declared (i.e. `fn foo() -> [(); { let _: &'a (); 10 }] {}`)

It hasn't always been like this and at some point it broke and started acting this way, this PR incidentally fixes this bug by not having the `LifetimeRibKind::ConcreteAnonConst` around anon consts. What was happening previously was `ConcreteAnonConst` was around every anon const, and when resolving a lifetime if we hit that rib kind we emit an error and store that the lifetime resolved to an error. With `feature(generic_const_exprs)` enabled we would silence the error caused by `ConcreteAnonConst` but still resolve the lifetime to an error.

As far as I can tell this is why 5 of the tests have started ICEing instead of passing, but this PR hasn't actually introduced any broken code. Generally all 5 of the tests started ICEing because the compiler cannot handle lifetimes in const args for one reason or another but it was being masked due to them always being resolved to errors.
- `const-arg-in-const-arg.rs`'s `full` revision, `late-bound-vars/simple.rs` and `late-bound-vars/in-closure.rs` are all ICEing because the logic to convert all regions to variables for borrowck doesn't work correctly for anon consts under `generic_const_exprs`. This definitely used to function correctly at one point and the tests were deliberately added because bugs were fixed. Then when lifetime resolution broke for `generic_const_exprs` these tests stopped actually testing anything because none of the lifetimes were resolved, and some PR (not entirely sure which) regressed these tests but it wasnt caught (until this PR made them start testing things again).
    - I removed `const-arg-in-const-arg.rs`'s `full` revision because I couldn't get stderr normalization to work correctly and give consistent results between CI and local for the ICE message :sweat_smile:
- `issue-77357.rs` and `issue-83993.rs` I do not believe have _ever_ functioned correctly, the tests were added because glacier stuff started passing. This was solely because lifetime resolution broke and masked the ICEs.
  - I removed these tests because I couldn't get stderr normalization to work correctly and give consistent results between CI and local for the ICE message :sweat_smile:

File: compiler/rustc_resolve/src/errors.rs (hunk 2 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/errors.rs]: I'm not completely sure what the naming scheme is tbh I just copied it. I think the `sub` is short for "subdiagnostic", the `is_type` is to determine what kind of generic parameter was found. I've renamed all this to be more clear since I found it rather confusing too and so did others I spoke to.

It's now `pub(crate) param_kind: Option<ParamKindInTyOfConstParam>`.

As far as I know none of these `ParamKindIn<blank>` can be merged into a single type as they all have different diagnostic messages with their `#[note]`/`#[help]`. It's definitely unfortunate because there's a lot of them :sweat_smile:

File: tests/ui/const-generics/const-arg-in-const-arg.rs (hunk 17 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/const-arg-in-const-arg.rs:1]: answered in a PR comment

File: tests/ui/const-generics/late-bound-vars/simple.rs (hunk 16 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/late-bound-vars/simple.rs:17]: answered in a PR comment

File: tests/ui/const-generics/late-bound-vars/in_closure.stderr (hunk 15 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/late-bound-vars/in_closure.stderr]: doneish

File: tests/ui/const-generics/late-bound-vars/in_closure.rs (hunk 14 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/late-bound-vars/in_closure.rs:18]: answered in a PR comment

File: compiler/rustc_resolve/src/lib.rs (hunk 11 above)
Comment (BoxyUwU) [reply compiler/rustc_resolve/src/lib.rs]: If we removed this variant and added the reason to `ParamInNonTrivialConstArg` (and I guess renamed it to `ParamInConcreteAnonConst`) I'd also have to introduce another `ParamKind` enum separate from the ones in the `errors.rs` file I think. I don't feel like that's worth it but if you feel strongly I can do that.

File: compiler/rustc_resolve/src/late.rs [hunk 19]
```diff
@@ -1495,17 +1528,17 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
                     self.record_lifetime_res(
                         lifetime.id,
                         LifetimeRes::Error,
                         LifetimeElisionCandidate::Ignore,
                     );
                     return;
                 }
-                LifetimeRibKind::AnonConst => {
-                    self.maybe_emit_forbidden_non_static_lifetime_error(lifetime);
+                LifetimeRibKind::ConcreteAnonConst(cause) => {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1540]: > Every lifetime you write that isnt '_ or 'static gets resolved to an error without an error actually having been emitted, this goes for when you do actually have a lifetime in scope (i.e. fn foo<'a>() -> [(); { let _: &'a (); 10 }] {}) or when you are writing lifetimes that haven't been declared (i.e. fn foo() -> [(); { let _: &'a (); 10 }] {}). 

The bug is here. We need the feature check for `generic_const_exprs` be done on this whole block, instead of only doing it in `emit_forbidden_non_static_lifetime_error`. This way, lifetime resolution will continue walking ribs, instead of returning a `LifetimeRes::Error` straight.

Comment (BoxyUwU) [reply compiler/rustc_resolve/src/late.rs:1540]: yeah, this PR accomplishes that by just not adding the `ConcreteAnonConst` rib if `generic_const_exprs` is enabled, so the only time we encounter `LifetimeRibKind::ConcreteAnonConst` should be when we need to error

**Comment by cjgillot** [comment]
Thanks for the explanations.
@bors r+
