### PR TITLE
O(log n) lookup of associated items by name

### LINKED ISSUE #68957: Using const fn constructor instead of struct expression with large number of constants causes compilation to fail because of large memory allocation.
I have:
- A struct `CodePoint` with a `const fn from(...) -> Self` constructor
- A large number of `CodePoint` constants (42.000+) using the constructor

```rust
#[repr(transparent)]
pub struct CodePoint {
    raw: u32
}

impl CodePoint {
    pub const fn from(raw: u32) -> Self {
        // debug_assert!(raw <= 0x10FFFF);
        CodePoint { raw }
    }
}

// include!(...)
// 42508 constants, 3.28MB file
impl CodePoint {
    pub const SPACE : CodePoint = CodePoint::from(32u32);
    ...
}
```

Building this leads to:
- Compiler busy for 2min+
- Compiler error trying to allocate 1.2GB:
  `memory allocation of 1207959552 bytes failed`
  even though I have 12GB of unused RAM

Using struct expressions instead of a `const fn` constructor:
```rust
impl CodePoint {
    pub const SPACE : CodePoint = CodePoint { raw: 32u32 };
    ...
}
```
- Compiler finishes within 5s.

Tested on `nightly` and `stable`, with `include!(...)` and copy-pasting: no differences.

Source file to reproduce: [reproduce.zip](https://github.com/rust-lang/rust/files/4174341/reproduce.zip)

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #68957, in which compile time is quadratic in the number of associated items. This PR makes name lookup use binary search instead of a linear scan to improve its asymptotic performance. As a result, the pathological case from that issue now runs in 8 seconds on my local machine, as opposed to many minutes on the current stable.

Currently, method resolution must do a linear scan through all associated items of a type to find one with a certain name. This PR changes the result of the `associated_items` query to a data structure that preserves the definition order of associated items (which is used, e.g., for the layout of trait object vtables) while adding an index of those items sorted by (unhygienic) name. When doing name lookup, we first find all items with the same `Symbol` using binary search, then run hygienic comparison to find the one we are looking for. Ideally, this would be implemented using an insertion-order preserving, hash-based multi-map, but one is not readily available.

Someone who is more familiar with identifier hygiene could probably make this better by auditing the uses of the `AssociatedItems` interface. My goal was to preserve the current behavior exactly, even if it seemed strange (I left at least one FIXME to this effect). For example, some places use comparison with `ident.modern()` and some places use `tcx.hygienic_eq` which requires the `DefId` of the containing `impl`. I don't know whether those approaches are equivalent or which one should be preferred.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by ecstatic-morse** [comment]
Hopefully the up-front cost of sorting the associated items by name is outweighed by more efficient lookup. If this is not the case, I'll need to switch to an adaptive data structure or consider an out-of-band index that is interned separately.

**Comment by ecstatic-morse** [comment]
I would try- this due to the failing test, but this has caused issues in the past.

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by mati865** [comment]
FYI syn-opt is nondeterministic right now: https://github.com/rust-lang/rust/issues/69060

**Comment by eddyb** [comment]
> Ideally, this would be implemented using an insertion-order preserving, hash-based multi-map, but one is not readily available.

It's not a multi-map, but `IndexMap<K, V>` is insertion-order preserving and I think we should use it more (see #60608).

**Comment by ecstatic-morse** [comment]
This does appear to cause a very slight regression in check builds. I think it is an acceptable one. 
I think we should merge this as is to fix #68957 

Those perf results suggest that name lookup is not a significant component of compile time for most crates, so I probably won't spend much time optimizing this PR. There are many improvements to be made if others are interested. Since the purpose of `in_definition_order` was to serve as a greppable marker of code that relied on associated item definition order and I don't plan to try to eliminate that code anytime soon, maybe I should replace `in_definition_order` and its documentation with an `iter` method?

**Comment by Mark-Simulacrum** [comment]
I would not replace in_definition_order (an incredibly useful name!) with iter at this point.

**Comment by estebank** [comment]
I'm +1 on the approach: there's trivial perf degradation but the behavior in pathological cases is much more sane than it is now. I'll review more in depth soon.

cc @rust-lang/compiler for visibility.

File: src/librustc/ty/mod.rs [hunk 1]
```diff
@@ -256,6 +263,141 @@ impl AssocItem {
...
+
+    /// Returns a slice of associated items in the order they were defined.
+    ///
+    /// New code should avoid relying on definition order. If you need a particular associated item
+    /// for a known trait, make that trait a lang item instead of indexing this array.
+    //
+    // FIXME(ecstaticmorse): Audit uses of this method to see if the definition order is actually
+    // significant in that context (perhaps we could replace them with calls to a newly defined
+    // `in_arbitrary_order`?). Once all uses have been removed, `AssociatedItems` won't have to
+    // keep a separate sorted list of indexes.
```
Comment (estebank) [inline src/librustc/ty/mod.rs]: Can this be accomplished by actually randomizing the order of `items_in_def_order` and see what breaks?

**Comment by ecstatic-morse** [comment]
So I added an `in_arbitrary_order` method but only use it in a few places, since preserving error message order is important. I would like for `in_arbitrary_order` to return things in a different order than `in_definition_order` while testing, but in the same order in release builds. That way, code that relies on the definition order only for emitting error messages in the right order could use `in_arbitrary_order` and `in_definition_order` would indicate places where the definition order is relied upon for *correctness*. 

Most places that would actually break if the definition order changed are looking up associated items on lang items. IMO, these associated items should themselves be lang items, but AFAICT we don't support that yet.

**Comment by Mark-Simulacrum** [comment]
We do have -Zui-testing I believe for the ability to change to "deterministic" mode.

> Most places that would actually break if the definition order changed are looking up associated items on lang items. IMO, these associated items should themselves be lang items, but AFAICT we don't support that yet.

cc @Centril -- this seems like something we could O(n) process in lang item collection and store HirIds or indices (whatever identified an associated item, I forget) like that for.

**Comment by Centril** [comment]
> cc @Centril -- this seems like something we could O(n) process in lang item collection and store HirIds or indices (whatever identified an associated item, I forget) like that for.

cc @matthewjasper who has taken over my work on lang items in lowering and might have this more in cache.

**Comment by ecstatic-morse** [comment]
Some unrelated changes have dramatically sped up the pathological case in #68957 on recent nightlies. A local build only takes 30 seconds, down from several minutes on 1.41.0. This PR is now just a [2x speedup](https://github.com/rust-lang/rust/issues/68957#issuecomment-586404761) instead of a 10x one.

**Comment by petrochenkov** [comment]
@ecstatic-morse 
>For example, some places use comparison with `ident.modern()` and some places use `tcx.hygienic_eq` which requires the `DefId` of the containing `impl`.

That should depend on whether it's path resolution and "adjustment" is performed (asymmetric, `bar` in `foo::bar` is adjusted to `foo` before comparing identifiers, if that makes sense), or just ident comparison (symmetric, e.g. checking for overlap in inherent associated items).

I don't have all the details in cache, but the last time I was trying to make this consistent in https://github.com/rust-lang/rust/pull/44818.
Now I'm not even entirely sure the idea of adjustments makes sense for *associated* (type-relative) names, as opposed to free (module-relative) names.

**Comment by eddyb** [comment]
> AFAICT, the current machinery does not support this.

>  this seems like something we could O(n) process in lang item collection and store HirIds or indices (whatever identified an associated item, I forget) like that for.

Don't understand this point. Associated items are identified by `DefId`s like everything else, and I'm pretty sure you can just stick `#[lang_item = "..."]` on a `trait` or `impl` method or associated `type` etc. (if not that's a bug in the lang item collector.

Doing all that is much easier than this PR (it's just adding a few attributes here and there, and entries in the list of lang items), which is *why* I suggested doing it first.

**Comment by petrochenkov** [comment]
This is certainly over-complicated for my taste.

Let me clarify one thing - is `in_definition_order` required for performance in any way?
E.g. due to faster iteration over vector than over some map with faster search.

If the answer is "no", then I'd prefer to keep only that map in `AssociatedItems` after making sure that it has the necessary iteration reproducibility properties (`BTreeMap`, `IndexMap`, whatever).
Visiting the items strictly in the definition order should never be necessary (modulo the lang item issue).

Since the perf issue is no longer super critical on the latest nightlies, then I'd prefer to block this PR until the lang item issue is resolved and this PR's design can be simplified.

File: src/librustc_typeck/astconv.rs [hunk 2]
```diff
@@ -1345,9 +1344,11 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
 
         let (assoc_ident, def_scope) =
             tcx.adjust_ident_and_get_scope(binding.item_name, candidate.def_id(), hir_ref_id);
+
+        // FIXME(ecstaticmorse): Can this use `find_by_name_and_kind` instead?
```
Comment (petrochenkov) [inline src/librustc_typeck/astconv.rs]: Yes, but that will do the adjustments calculations (which we already did in `adjust_ident_and_get_scope` above) for the second time.
If perf run says it's ok, then it can be done (here and next to other uses of `adjust_ident_and_get_scope`).

File: src/librustc_typeck/astconv.rs [hunk 3]
```diff
@@ -2199,10 +2198,12 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
         let trait_did = bound.def_id();
         let (assoc_ident, def_scope) =
             tcx.adjust_ident_and_get_scope(assoc_ident, trait_did, hir_ref_id);
+
+        // FIXME(ecstaticmorse): Can this use `find_by_name_and_namespace` instead?
```
Comment (petrochenkov) [inline src/librustc_typeck/astconv.rs]: Same answer as in https://github.com/rust-lang/rust/pull/69072#discussion_r379839906.

**Comment by ecstatic-morse** [comment]
If this is blocked on implementation complexity, I'd like to get a better idea of what people would sign off on before working on it more. Iteration in definition order makes error messages better (it also defines the layout of vtables, but we  can change that). Assuming that constraint, I see only two options: using a `IndexMap<SmallVec<[AssocItemByName; 1]>>` or keep a sorted index as this PR does. @petrochenkov if you have something else in mind, could you expound on it?

**Comment by petrochenkov** [comment]
>it also defines the layout of vtables

Hmm, this is interesting. Predictable ABI is a good reason to keep the original order.

I actually had some doubts about the original order being preserved during AST -> HIR lowering (if not, then it wouldn't make much sense to preserve it later), it it turned out it's indeed preserved (see https://github.com/rust-lang/rust/pull/68814#issuecomment-586698849).

**Comment by petrochenkov** [comment]
Using the `IndexMap`, providing a single iterator and getting rid of `in_(definition,arbitrary)_order` looks preferable.
(The size of `SmallVec` should indeed be `1` in 99.9% of cases.)

**Comment by ecstatic-morse** [comment]
Using an IndexMap in this way will change the order of vtables when there is a raw ident collision. Is this really preferable to binary search?

**Comment by petrochenkov** [comment]
Damn.
Do we have `IndexMultiMap` by chance?
Perhaps we can get one if you move your implementation into `rustc_data_structures` and make it slightly more generic?

**Comment by ecstatic-morse** [comment]
> Ideally, this would be implemented using an insertion-order preserving, hash-based multi-map, but one is not readily available.

No. I would be happy to turn this into a general purpose data structure. Not sure if anyone else will use it though XD.

**Comment by petrochenkov** [comment]
@ecstatic-morse 
To clarify, it's not necessary to implement the whole multimap interface for this, only the basic parts needed for this PR (other parts can be added later on demand), but I'd still prefer it to live as a separate data structure in `rustc_data_structures` instead of `rustc`.

File: src/librustc/ty/mod.rs [hunk 4]
```diff
@@ -257,6 +264,130 @@ impl AssocItem {
...
 
+/// A list of `ty::AssocItem`s in definition order that allows for efficient lookup by name.
+///
+/// When doing lookup by name, we try to postpone hygienic comparison for as long as possible since
+/// it is relatively expensive. Instead, items are indexed by `Symbol` and hygienic comparison is
+/// done only on items with the same name.
+#[derive(Debug, Clone, PartialEq, HashStable)]
+pub struct AssociatedItems {
+    items_in_def_order: Vec<ty::AssocItem>,
+    item_idx_in_name_order: Vec<usize>,
```
Comment (petrochenkov) [inline src/librustc/ty/mod.rs]: This commit contains a chunk of other removed commit.

File: src/librustc/ty/mod.rs [hunk 5]
```diff
@@ -264,42 +265,67 @@ impl AssocItem {
     }
 }
 
+#[repr(transparent)]
+#[derive(Debug, Clone, Copy, HashStable)]
+struct AssocItemByNameUnhygienic(ty::AssocItem);
```
Comment (petrochenkov) [inline src/librustc/ty/mod.rs]: It's somewhat weird to use a set with a comparator as a map, if we can use an actual map instead.
This should be an implementation detail of `OrderedIndexMultiMap`, IMO.
(Which can reuse all of the implementation of `OrderedIndexMultiSet` because they are pretty much equivalent `Map<Key, T>` ~ `Set<(Key, T)>`).
The extra space for the `Symbol` key shouldn't be a big deal.

**Comment by petrochenkov** [comment]
The second part of https://github.com/rust-lang/rust/pull/69072#issuecomment-586700971 still holds,  we have a single canonical iteration order now, so `in_(definition,arbitrary)_order` could be removed thus simplifying the interface.

File: src/librustc/ty/mod.rs (hunk 5 above)
Comment (ecstatic-morse) [reply src/librustc/ty/mod.rs]: How will `in_definition_order` return a slice then?

File: src/librustc/ty/mod.rs (hunk 4 above)
Comment (ecstatic-morse) [reply src/librustc/ty/mod.rs]: Whoops. My bad.

**Comment by ecstatic-morse** [comment]
> The second part of #69072 (comment) still holds, we have a single canonical iteration order now, so in_(definition,arbitrary)_order could be removed in favor of associated_items.iter() thus simplifying the interface.

I prefer `in_definition_order`. It's self-documenting. `in_arbitrary_order` can go away since I won't be changing the vtable order anytime soon.

File: src/librustc/ty/mod.rs (hunk 5 above)
Comment (petrochenkov) [reply src/librustc/ty/mod.rs]: Yeah, I meant, why is it necessary to use a slice specifically, as opposed to an opaque `impl Iterator`.

**Comment by ecstatic-morse** [comment]
@petrochenkov I switched to a map, but it's not quite ready for review, just running the tests while I context switch.

File: src/librustc_ty/ty.rs [hunk 6]
```diff
@@ -210,10 +210,10 @@ fn associated_item_def_ids(tcx: TyCtxt<'_>, def_id: DefId) -> &[DefId] {
     }
 }
 
-fn associated_items<'tcx>(tcx: TyCtxt<'tcx>, def_id: DefId) -> &'tcx [ty::AssocItem] {
-    tcx.arena.alloc_from_iter(
-        tcx.associated_item_def_ids(def_id).iter().map(|did| tcx.associated_item(*did)),
-    )
+fn associated_items<'tcx>(tcx: TyCtxt<'tcx>, def_id: DefId) -> &'tcx ty::AssociatedItems {
+    let items =
+        tcx.associated_item_def_ids(def_id).iter().map(|did| tcx.associated_item(*did)).collect();
```
Comment (petrochenkov) [inline src/librustc_ty/ty.rs]: The vector collected here is immediately turned into an iterator again inside `AssociatedItems::new`.
`AssociatedItems::new` could accept an iterator instead.

**Comment by petrochenkov** [comment]
>FWIW, I prefer `in_definition_order`, since it's self-documenting.

Ok, it's still a single method whether it's called `iter` or `in_definition_order`.

r=with the nit (https://github.com/rust-lang/rust/pull/69072#discussion_r381536578) addressed and green CI.
