### PR TITLE
GAT/const_generics: Allow with_opt_const_param to return GAT param def_id

### LINKED ISSUE #75415: [nightly] ICE when using GATs with const generics
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=af00f39dc4b303b0579133416d712db9)

### Code

```Rust
#![allow(incomplete_features)]
#![feature(generic_associated_types)]
#![feature(const_generics)]

pub trait Buffer<const T: usize> {}

pub trait Device {
    type Buffer<const T: usize>: Buffer<{ T }>;

    fn create_buffer<const T: usize>(&self) -> Option<Self::Buffer<{ T }>>;
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-apple-darwin
release: 1.47.0-nightly
LLVM version: 10.0
```

### Error output

```
error: internal compiler error: src/librustc_typeck/collect/type_of.rs:82:26: unexpected const parent path Ty(Ty { hir_id: HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 8 }, kind: Path(TypeRelative(Ty { hir_id: HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 10 }, kind: Path(Resolved(None, Path { span: src/main.rs:10:55: 10:74 (#0), res: SelfTy(Some(DefId(0:5 ~ playground[a09e]::Device[0])), None), segments: [PathSegment { ident: Self#0, hir_id: Some(HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 9 }), res: Some(SelfTy(Some(DefId(0:5 ~ playground[a09e]::Device[0])), None)), args: None, infer_args: false }] })), span: src/main.rs:10:55: 10:74 (#0) }, PathSegment { ident: Buffer#0, hir_id: Some(HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 16 }), res: Some(Err), args: Some(GenericArgs { args: [Const(ConstArg { value: AnonConst { hir_id: HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 11 }, body: BodyId { hir_id: HirId { owner: DefId(0:9 ~ playground[a09e]::Device[0]::create_buffer[0]), local_id: 15 } } }, span: src/main.rs:10:68: 10:73 (#0) })], bindings: [], parenthesized: false }), infer_args: false })), span: src/main.rs:10:55: 10:74 (#0) }
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_typeck/collect/type_of.rs:82:26: unexpected const parent path Ty(Ty { hir_id: HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 13 }, kind: Path(TypeRelative(Ty { hir_id: HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 15 }, kind: Path(Resolved(None, Path { span: gfx/src/device.rs:15:66: 15:91 (#0), res: SelfTy(Some(DefId(0:30 ~ gfx[85a5]::device[0]::Device[0])), None), segments: [PathSegment { ident: Self#0, hir_id: Some(HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 14 }), res: Some(SelfTy(Some(DefId(0:30 ~ gfx[85a5]::device[0]::Device[0])), None)), args: None, infer_args: false }] })), span: gfx/src/device.rs:15:66: 15:91 (#0) }, PathSegment { ident: Buffer#0, hir_id: Some(HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 23 }), res: Some(Err), args: Some(GenericArgs { args: [Type(Ty { hir_id: HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 16 }, kind: Path(Resolved(None, Path { span: gfx/src/device.rs:15:79: 15:80 (#0), res: Def(TyParam, DefId(0:38 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]::T[0])), segments: [PathSegment { ident: T#0, hir_id: Some(HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 17 }), res: Some(Def(TyParam, DefId(0:38 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]::T[0]))), args: None, infer_args: false }] })), span: gfx/src/device.rs:15:79: 15:80 (#0) }), Const(ConstArg { value: AnonConst { hir_id: HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 18 }, body: BodyId { hir_id: HirId { owner: DefId(0:37 ~ gfx[85a5]::device[0]::Device[0]::create_buffer[0]), local_id: 22 } } }, span: gfx/src/device.rs:15:82: 15:90 (#0) })], bindings: [], parenthesized: false }), infer_args: false })), span: gfx/src/device.rs:15:66: 15:91 (#0) })

thread 'rustc' panicked at 'Box<Any>', /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_errors::HandlerInner::span_bug
   9: rustc_errors::Handler::span_bug
  10: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc_middle::ty::context::tls::with_opt::{{closure}}
  12: rustc_middle::ty::context::tls::with_opt
  13: rustc_middle::util::bug::opt_span_bug_fmt
  14: rustc_middle::util::bug::span_bug_fmt
  15: rustc_typeck::collect::type_of::opt_const_param_of
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::opt_const_param_of>::compute
  17: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  19: rustc_data_structures::stack::ensure_sufficient_stack
  20: rustc_query_system::query::plumbing::get_query_impl
  21: rustc_typeck::check::typeck
  22: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  23: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_query_system::query::plumbing::ensure_query_impl
  28: rustc_typeck::check::typeck_item_bodies
  29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  30: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::get_query_impl
  34: rustc_typeck::check_crate
  35: rustc_interface::passes::analysis
  36: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  37: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_query_system::query::plumbing::get_query_impl
  40: rustc_middle::ty::context::tls::enter_global
  41: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  42: rustc_span::with_source_map
  43: rustc_interface::interface::create_compiler_and_run
  44: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (6c8927b0c 2020-07-26) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [opt_const_param_of] computing the optional const parameter of `device::Device::create_buffer::{{constant}}#0`
#1 [typeck] type-checking `device::Device::create_buffer::{{constant}}#0`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

### LINKED ISSUE #79666: ICE with const generics and GATs
### Code

```Rust
#![feature(const_generics)]
#![feature(generic_associated_types)]

trait A {
    type B<const N: usize>;
    
    fn foo<const N: usize>(&self) -> Self::B<{N}>;
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b9da5a6d412079faf1ecc54d755ef451)

### Meta
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
binary: rustc
commit-hash: 1c389ffeff814726dec325f0f2b0c99107df2673
commit-date: 2020-11-24
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information
  = help: consider using `min_const_generics` instead, which is more stable and complete

warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:2:12
  |
2 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

warning: Error finalizing incremental compilation session directory `/home/cynecx/dev/rust-ice/target/debug/incremental/rust_ice-2od6n63huil2c/s-ftn1ij8uum-1wj4523-working`: No such file or directory (os error 2)

warning: 3 warnings emitted

error: internal compiler error: unexpected const parent path Ty(Ty { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 7 }, kind: Path(TypeRelative(Ty { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 9 }, kind: Path(Resolved(None, Path { span: src/main.rs:7:38: 7:50 (#0), res: SelfTy(Some(DefId(0:3 ~ rust_ice[b006]::A)), None), segments: [PathSegment { ident: Self#0, hir_id: Some(HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 8 }), res: Some(SelfTy(Some(DefId(0:3 ~ rust_ice[b006]::A)), None)), args: None, infer_args: false }] })), span: src/main.rs:7:38: 7:50 (#0) }, PathSegment { ident: B#0, hir_id: Some(HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 15 }), res: Some(Err), args: Some(GenericArgs { args: [Const(ConstArg { value: AnonConst { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 10 }, body: BodyId { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 14 } } }, span: src/main.rs:7:46: 7:49 (#0) })], bindings: [], parenthesized: false }), infer_args: false })), span: src/main.rs:7:38: 7:50 (#0) })
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_typeck/src/collect/type_of.rs:83:34

error: internal compiler error: unexpected const parent in type_of_def_id(): Ty(Ty { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 7 }, kind: Path(TypeRelative(Ty { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 9 }, kind: Path(Resolved(None, Path { span: src/main.rs:7:38: 7:50 (#0), res: SelfTy(Some(DefId(0:3 ~ rust_ice[b006]::A)), None), segments: [PathSegment { ident: Self#0, hir_id: Some(HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 8 }), res: Some(SelfTy(Some(DefId(0:3 ~ rust_ice[b006]::A)), None)), args: None, infer_args: false }] })), span: src/main.rs:7:38: 7:50 (#0) }, PathSegment { ident: B#0, hir_id: Some(HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 15 }), res: Some(Err), args: Some(GenericArgs { args: [Const(ConstArg { value: AnonConst { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 10 }, body: BodyId { hir_id: HirId { owner: DefId(0:6 ~ rust_ice[b006]::A::foo), local_id: 14 } } }, span: src/main.rs:7:46: 7:49 (#0) })], bindings: [], parenthesized: false }), infer_args: false })), span: src/main.rs:7:38: 7:50 (#0) })
  |
  = note: delayed at compiler/rustc_typeck/src/collect/type_of.rs:334:26

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:1260:42

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:707:27

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:153:49

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:867:53

error: internal compiler error: cat_expr Errd
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_typeck/src/check/regionck.rs:405:31

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_mir_build/src/build/mod.rs:684:18

error: internal compiler error: mir_const_qualif: MIR had errors
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_mir/src/transform/mod.rs:229:18

error: internal compiler error: PromoteTemps: MIR had errors
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_mir/src/transform/promote_consts.rs:55:22

error: internal compiler error: broken MIR in DefId(0:8 ~ rust_ice[b006]::A::foo::{constant#0}) ("return type"): bad type [type error]
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:715:20

error: internal compiler error: broken MIR in DefId(0:8 ~ rust_ice[b006]::A::foo::{constant#0}) (LocalDecl { mutability: Mut, local_info: None, internal: false, is_block_tail: None, ty: [type error], user_ty: None, source_info: SourceInfo { span: src/main.rs:7:46: 7:49 (#0), scope: scope[0] } }): bad type [type error]
 --> src/main.rs:7:46
  |
7 |     fn foo<const N: usize>(&self) -> Self::B<{N}>;
  |                                              ^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (1c389ffef 2020-11-24) running on x86_64-unknown-linux-gnu


```

</p>
</details>

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #75415
Fixes #79666
cc @lcnr 

I've absolutely no idea who to r?  for this...

### CODE REVIEW

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 1]
```diff
@@ -29,6 +29,48 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
         let parent_node = tcx.hir().get(parent_node_id);
 
         match parent_node {
+            Node::Ty(hir_ty @ Ty { kind: TyKind::Path(QPath::TypeRelative(_, segment)), .. }) => {
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect/type_of.rs:32]: This is pre-existing to some extent, but I think this code could use a few more comments. It'd be nice to give an example of the Rust code you are matching against and explain what each variable represents in terms of that code.

I'm a bit confused, for example, what the `def_id` here refers to -- is it part of the impl? the trait? 

What is the `parent_node` -- the `type Foo<const C> = ...` in the impl? I... guess so? Can it also be in a trait (e.g., with a default value?)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Hi! Can you add some comments along the lines of what I asked for? That'd be really helpful.

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_typeck/src/collect/type_of.rs:42]: I added some comments that will hopefully remove some of the confusion, I'm not super confident in them because I'm still pretty new to rustc but I think they're correct haha

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:42]: Thanks!

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 2]
```diff
@@ -29,6 +29,64 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
         let parent_node = tcx.hir().get(parent_node_id);
 
         match parent_node {
+            // This matches on types who's paths couldn't be resolved without typeck'ing e.g.
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect/type_of.rs:32]: I was reading the [rustdoc for the `opt_const_param_of` query](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.opt_const_param_of) and I think this isn't *quite* right. 

This query would, I think, be invoked on the `3` in your example, and it would be returning the `const N1: usize` node.

It doesn't have much to do with `Self::Assoc` in particular, from what I can tell, except that this is the context in which the `3` appears.

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:32]: In other words, I think if you wrote `<Self as Foo>::Assoc<3>` the query could still be invoked

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:32]: OK, I'm wrong, I see your point. The *query* is invoked on `3`, but this **match arm** is specific to the case where the `3` appears as part of a `Self::Assoc<3>` type thing.

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:32]: (I am leaving my stream of consciousness to help guide you in how to improve the comment)

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 3]
```diff
@@ -29,6 +29,64 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
...
+            //   fn foo() -> Self::Assoc<3>;
+            //   // note: if the def_id argument is the 3 then in this example
+            //   // parent_node would be the node for Self::Assoc<_>
+            // }
+            // We didnt write <Self as Foo>::Assoc so the Self::Assoc<_> is lowered to QPath::TypeRelative.
+            // I believe this match arm is only needed for GAT but I am not 100% sure - BoxyUwU
+            Node::Ty(hir_ty @ Ty { kind: TyKind::Path(QPath::TypeRelative(_, segment)), .. }) => {
+                // Walk up from the parent_node to find an item so that
+                // we can resolve the relative path to an actual associated type.
+                // For the code example above, this item would be the Foo trait.
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect/type_of.rs:45]: I found this comment confusing. I think what's going on is this:

* Find the item I that contains the anonymous constant so that we can create the context for it
* Using that context, we will convert the HIR for  `Self::Assoc<3>` into a type, which will be a fully resolved projection like `<Self as Foo>::Assoc<3>`

File: compiler/rustc_typeck/src/collect/type_of.rs [hunk 4]
```diff
@@ -29,6 +29,64 @@ pub(super) fn opt_const_param_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<
...
+                let item_ctxt = &ItemCtxt::new(tcx, item_did) as &dyn crate::astconv::AstConv<'_>;
+
+                // This ty will be the actual associated type so that we can
+                // go through its generics to find which param our def_id corresponds to.
+                // For the code example above, this ty would be the Assoc<const N1: usize>.
+                let ty = item_ctxt.ast_ty_to_ty(hir_ty);
+                if let ty::Projection(projection) = ty.kind() {
+                    let generics = tcx.generics_of(projection.item_def_id);
+
+                    let arg_index = segment
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect/type_of.rs:63]: "Find the index where the `3` argument appears in the projection"

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:63]: Side note that I don't know why we are filtering to `is_const`

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:63]: It's not bad, just seems unnecessary

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
OK, those comments helped a lot, and I understand why the code works! I think they could be made better. Left some thoughts. Let me know what you think.

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_typeck/src/collect/type_of.rs:63]: I asked lcnr why we do this and it doesn't seem strictly necessary but was put there in case we're ever allowed to elide lifetimes in the segment. That isn't allowed atm though so the filter is more of a precaution ^^

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 3 above)
Comment (BoxyUwU) [reply compiler/rustc_typeck/src/collect/type_of.rs:45]: Yea I wasn't great at this comment as I'm not all that familiar with the exact details of this Item stuff. What you said sounds correct to me so I'll just uh take that and put it in the comment x]

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 2 above)
Comment (BoxyUwU) [reply compiler/rustc_typeck/src/collect/type_of.rs]: I rewrote that comment to put more emphasis on what some of the variables correspond to and what exactly the match arm matches on :)

File: compiler/rustc_typeck/src/collect/type_of.rs (hunk 4 above)
Comment (nikomatsakis) [reply compiler/rustc_typeck/src/collect/type_of.rs:72]: I see. OK. I would never want to allow that, but it's ok.

**Review by nikomatsakis — APPROVED** [review]
