### PR TITLE
Varargs support for system ABI

### LINKED ISSUE #110505: Variadic functions don't allow "system" on non-x86 Windows
While testing variadic function support with `raw-dylib` I discovered that Rust requires such functions to use either "C" or "cdecl" ABIs but `raw-dylib` requires the "system" ABI on non-x86 Windows. 

My undertstanding from discussing with @dpaoliello is that this is not an issue with `raw-dylib` itself but with Rust's insistence that such functions aren't allowed to use the "system" ABI. It's just that `raw-dylib` is very strict about calling convention so that's where the issue surfaced. 

```rust
#[link(name = "library", modifiers = "+verbatim")]
extern "system" {
    pub fn DbgPrint(format: *const u8, ...) -> u32;
}
```

On x64 I should be able to compile this but Rust says no:

```
error[E0045]: C-variadic function must have a compatible calling convention, like `C` or `cdecl`
 --> src\lib.rs:3:5
  |
3 |     pub fn DbgPrint(format: *const u8, ...) -> u32;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ C-variadic function must have a compatible calling convention
```

This example works if I change the ABI to "cdecl" but that's not meant to be a valid ABI on x64 and so when I try to compile this with `raw-dylib` it fails:

```rust
#[link(name = "library", kind = "raw-dylib", modifiers = "+verbatim")]
extern "cdecl" {
    pub fn DbgPrint(format: *const u8, ...) -> u32;
}
```

```
error: ABI not supported by `#[link(kind = "raw-dylib")]` on this architecture
 --> src\lib.rs:3:5
  |
3 |     pub fn DbgPrint(format: *const u8, ...) -> u32;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The practical result is that it is impossible to link this function with `raw-dylib` on non-x86.

### PR DESCRIPTION
**Pull request by beepster4096**
This PR allows functions with the `system` ABI to be variadic (under the `extended_varargs_abi_support` feature tracked in #100189). On x86 windows, the `system` ABI is equivalent to `C` for variadic functions. On other platforms, `system` is already equivalent to `C`.

Fixes #110505

### CODE REVIEW

File: compiler/rustc_target/src/spec/abi/mod.rs [hunk 1]
```diff
@@ -79,6 +79,7 @@ impl Abi {
         match self {
             Self::C { .. }
             | Self::Cdecl { .. }
+            | Self::System { .. }
```
Comment (RalfJung) [inline compiler/rustc_target/src/spec/abi/mod.rs:82]: Please also update the comment above, it is now contradicting the code.

Cc @Soveu @jackh726 who added this comment in https://github.com/rust-lang/rust/pull/97971
Cc @bjorn3 for another ABI expert

File: compiler/rustc_metadata/src/native_libs.rs [hunk 2]
```diff
@@ -523,8 +523,16 @@ impl<'tcx> Collector<'tcx> {
         let calling_convention = if self.tcx.sess.target.arch == "x86" {
             match abi {
                 Abi::C { .. } | Abi::Cdecl { .. } => DllCallingConvention::C,
-                Abi::Stdcall { .. } | Abi::System { .. } => {
-                    DllCallingConvention::Stdcall(self.i686_arg_list_size(item))
+                Abi::Stdcall { .. } => DllCallingConvention::Stdcall(self.i686_arg_list_size(item)),
+                Abi::System { .. } => {
```
Comment (RalfJung) [inline compiler/rustc_metadata/src/native_libs.rs:527]: Is this even reachable? This looks like it is duplicating the logic in adjust_abi.

File: compiler/rustc_target/src/spec/mod.rs [hunk 3]
```diff
@@ -2399,10 +2399,10 @@ impl DerefMut for Target {
 
 impl Target {
     /// Given a function ABI, turn it into the correct ABI for this target.
-    pub fn adjust_abi(&self, abi: Abi) -> Abi {
+    pub fn adjust_abi(&self, abi: Abi, c_variadic: bool) -> Abi {
         match abi {
             Abi::C { .. } => self.default_adjusted_cabi.unwrap_or(abi),
-            Abi::System { unwind } if self.is_like_windows && self.arch == "x86" => {
+            Abi::System { unwind } if self.is_like_windows && self.arch == "x86" && !c_variadic => {
```
Comment (RalfJung) [inline compiler/rustc_target/src/spec/mod.rs:2405]: Can you add a link to some reference that states authoritatively that on x86, "system" should mean "C" with varargs but "stdcall" without varargs?

**Comment by Soveu** [comment]
That makes me think, maybe we should first adjust the abi, then check if it is possible to use varargs?
This has an advantage, that the compiler will be more "flexible", at the cost of code being probably less portable - we could add some warnings for using `system` with varargs, but that will be it, just a warning.

**Comment by bjorn3** [comment]
Does windows have any function that both uses the system abi and is a vararg? How is the abi handled for that function on x86?

**Comment by beepster4096** [comment]
@Soveu
> maybe we should first adjust the abi, then check if it is possible to use varargs?

There's some edge cases where this would make the varargs error dependent on the target. For example, a variadic `stdcall` function on `i686-pc-windows-msvc` would fail to compile. The same function on `x86_64-pc-windows-msvc` would pass because `stdcall` would be adjusted into `C`. Right now, the check is independent of the target, it just relies on the ABI the function is declared with. I don't think changing that is a good idea.

@bjorn3 
> Does windows have any function that both uses the system abi and is a vararg?

The example from the issue, `DbgPrint`, actually appears to be defined with `__cdecl` explicitly, but I found a function `RtlInitializeSidEx` that is both variadic and uses `__stdcall`.
> How is the abi handled for that function on x86?

According to https://learn.microsoft.com/en-us/cpp/cpp/stdcall, variadic functions marked with `__stdcall` just use `__cdecl`. I am going to add that link in a comment to satisfy [this review comment](https://github.com/rust-lang/rust/pull/119587#discussion_r1443157777).

File: compiler/rustc_metadata/src/native_libs.rs (hunk 2 above)
Comment (beepster4096) [reply compiler/rustc_metadata/src/native_libs.rs:527]: It is reachable. The ABI being matched on comes from the HIR for the extern block, without going through `adjust_abi`. This match looks similar to the logic in `adjust_abi`, but I don't think it can be cleanly deduplicated because this function will emit errors for some ABIs that `adjust_abi` will turn into `C`.

File: compiler/rustc_target/src/spec/mod.rs [hunk 4]
```diff
@@ -2399,10 +2399,14 @@ impl DerefMut for Target {
...
     /// Given a function ABI, turn it into the correct ABI for this target.
-    pub fn adjust_abi(&self, abi: Abi) -> Abi {
+    pub fn adjust_abi(&self, abi: Abi, c_variadic: bool) -> Abi {
         match abi {
             Abi::C { .. } => self.default_adjusted_cabi.unwrap_or(abi),
-            Abi::System { unwind } if self.is_like_windows && self.arch == "x86" => {
+
+            // On Windows, `extern "system"` behaves like msvc's `__stdcall`
+            // `__stdcall` only applies on x86 and on non-variadic functions
+            // see https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170
```
Comment (RalfJung) [inline compiler/rustc_target/src/spec/mod.rs:2408]:
```suggestion
            // On Windows, `extern "system"` behaves like msvc's `__stdcall`.
            // `__stdcall` only applies on x86 and on non-variadic functions:
            // https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170
```
I first tried to parse this as a single sentence (as there's no `.`) and that went poorly.^^

File: compiler/rustc_metadata/src/native_libs.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_metadata/src/native_libs.rs:527]: That's unfortunate but I have no idea why this is happening or where these two functions are called. If the logic needs to be duplicated here then please add a reference to the other copy of the same logic.

**Comment by petrochenkov** [comment]
r=me after adding cross-link comments to different places that "normalize" calling conventions (https://github.com/rust-lang/rust/pull/119587#discussion_r1443728481) + squashing commits.
@rustbot author

**Comment by beepster4096** [comment]
I'm a little unsure of what exactly I am being asked to do here. It seems like the review (https://github.com/rust-lang/rust/pull/119587#discussion_r1443728481) says to add a comment in `build_dll_import`'s abi logic linking to `adjust_abi`. Meanwhile, the plurals in the r=me prerequisite lead me to believe it means to have both link to each other. To be clear, `adjust_abi` and `build_dll_import` are the only places that normalize calling conventions I could find.

I've done only the former change (and squished) for now.
@rustbot ready

**Comment by petrochenkov** [comment]
>I've done only the former change

Okay, that's good enough.
@bors r+

**Comment by workingjubilee** [comment]
> According to https://learn.microsoft.com/en-us/cpp/cpp/stdcall, variadic functions marked with __stdcall just use __cdecl. I am going to add that link in a comment to satisfy https://github.com/rust-lang/rust/pull/119587#discussion_r1443157777.

Yes, but this is inconsistent with our decision to add FCWs to all the various ABIs that MSVC silently accepts and downgrades to something else.

**Comment by RalfJung** [comment]
We didn't fully decide that though -- on Windows target we still silently accept `stdcall` on x86_64 and treat it like `C`; we error only on non-Windows targets.
