### PR TITLE
Lint against getting pointers from immediately dropped temporaries

### LINKED ISSUE #123613: Lint against instantly-dangling pointers like `String::with_capacity(MAX_PATH).as_mut_ptr()`
# Issue Description
The following Rust code:
```rust
const MAX_PATH: usize = 260;
fn main() {
    let str1 = String::with_capacity(MAX_PATH).as_mut_ptr();
    let str2 = String::from("TotototototototototototototototototoT").as_mut_ptr();
    unsafe {
        std::ptr::copy_nonoverlapping(str2, str1, 30);
        println!("{:?}", String::from_raw_parts(str1,30,30));
    }
}
```
uses the `String::with_capacity` function to create a string with a capacity of 260 characters. It then uses the `as_mut_ptr` method to get a raw pointer to the string.

However, this approach can lead to undefined behavior because:

The `String::with_capacity` function only guarantees to allocate enough memory to store the specified number of characters. It does not guarantee that the allocated memory is valid.
The `as_mut_ptr` method returns a raw pointer to the internal data of the string. This pointer may point to uninitialized memory or memory that has been invalidated by other operations.
Therefore, using the `String::with_capacity(MAX_PATH).as_mut_ptr()` method to create a raw pointer can lead to the following problems
-Program crashes
-Data corruption
-Security vulnerabilities

Expected Behavior
The `String::with_capacity` function should not allow the creation of a raw pointer to uninitialized memory.

Similar to String::from("x").as_mut_ptr(), such raw pointers should not be compiled successfully.

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
Fixes #123613

## Changes:
1. New lint: `dangling_pointers_from_temporaries`. Is a generalization of `temporary_cstring_as_ptr` for more types and more ways to get a temporary.
2. `temporary_cstring_as_ptr` is removed and marked as renamed to `dangling_pointers_from_temporaries`.
3. `clippy::temporary_cstring_as_ptr` is marked as renamed to `dangling_pointers_from_temporaries`.
4. Fixed a false positive[^fp] for when the pointer is not actually dangling because of lifetime extension for function/method call arguments.
5. `core::cell::Cell` is now `rustc_diagnostic_item = "Cell"`

## Questions:
- [ ]  Instead of manually checking for a list of known methods and diagnostic items, maybe add some sort of annotation to those methods in library and check for the presence of that annotation? https://github.com/rust-lang/rust/pull/128985#issuecomment-2318714312

### False negatives[^fn]:

See the comments in `compiler/rustc_lint/src/dangling.rs`

1. Method calls that are not checked for:
   - `temporary_unsafe_cell.get()`
   - `temporary_sync_unsafe_cell.get()`
2. Ways to get a temporary that are not recognized:
   - `owning_temporary.field`
   - `owning_temporary[index]`
3. No checks for ref-to-ptr conversions:
   - `&raw [mut] temporary`
   - `&temporary as *(const|mut) _`
    - `ptr::from_ref(&temporary)` and friends

[^fn]: lint **should** be emitted, but **is not**

[^fp]: lint **should not** be emitted, but **is**

### CODE REVIEW

**Comment by jieyouxu** [comment]
FYI this probably needs T-lang approval and a crater run

**Comment by GrigorenkoPV** [comment]
This probably needs a crater run. Check-only should suffice. However, the lint should probably be denied for the run, but I am not sure if crater has such an option. Maybe I will just temporary change the default level in code.

Anyways, neither do I have permissions for `bors try`, nor for a crater run.

File: compiler/rustc_lint/src/dangling.rs [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+    /// {{produces}}
+    ///
+    /// ### Explanation
+    ///
+    /// The inner pointer of a `CString` lives only as long as the `CString` it
+    /// points to. Getting the inner pointer of a *temporary* `CString` allows the `CString`
+    /// to be dropped at the end of the statement, as it is not being referenced as far as the
+    /// typesystem is concerned. This means outside of the statement the pointer will point to
+    /// freed memory, which causes undefined behavior if the pointer is later dereferenced.
+    pub TEMPORARY_CSTRING_AS_PTR,
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:30]: The `TEMPORARY_CSTRING_AS_PTR` lint should probably be removed completely in favour of the more general lint.

This can be done by removing by adding the lint to the [renamed lint list](https://github.com/rust-lang/rust/blob/4fe1e2bd5bf5a6f1cb245f161a5e9d315766f103/compiler/rustc_lint/src/lib.rs#L345) and removing the relevant code.

File: compiler/rustc_lint/src/dangling.rs [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+    /// as they are statically verified by the borrow-checker to never dangle.
+    ///
+    /// Note: This lint does **not** get triggered by methods & functions
+    /// that intentionally produce dangling pointers, such as:
+    ///
+    /// - `core::ptr::dangling` & `core::ptr::dangling_mut`
+    /// - `core::ptr::NonNull::dangling`
+    /// - `std::alloc::Layout::dangling`
+    ///
+    pub INSTANTLY_DANGLING_POINTER,
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:74]: Lint names should be plural and more generally follow the [guidelines](https://rustc-dev-guide.rust-lang.org/diagnostics.html#lint-naming).

Maybe something like this? Which read well IMO: "allow dangling pointers from temporaries".
```suggestion
    pub DANGLING_POINTERS_FROM_TEMPORARIES,
```

File: compiler/rustc_lint/src/dangling.rs [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+    /// If you need stronger guarantees, consider using references instead,
+    /// as they are statically verified by the borrow-checker to never dangle.
+    ///
+    /// Note: This lint does **not** get triggered by methods & functions
+    /// that intentionally produce dangling pointers, such as:
+    ///
+    /// - `core::ptr::dangling` & `core::ptr::dangling_mut`
+    /// - `core::ptr::NonNull::dangling`
+    /// - `std::alloc::Layout::dangling`
+    ///
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:73]: This part of the explanation doesn't sees useful or necessary to me, in particular if we change the lint name to `DANGLING_POINTERS_FROM_TEMPORARIES` which makes clear why those wouldn't lint.

```suggestion
```

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs [hunk 4]
```diff
@@ -0,0 +1,13 @@
+#![deny(instantly_dangling_pointer)]
+
+const MAX_PATH: usize = 260;
+fn main() {
+    let str1 = String::with_capacity(MAX_PATH).as_mut_ptr();
+    //~^ ERROR [instantly_dangling_pointer]
```
Comment (Urgau) [inline tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs:6]: Instead of just checking the lint name in those UI tests, could you instead check the actual primary message, that way we make sure that the message is correct and that the variables (the type here) are correctly displayed.

```suggestion
    //~^ ERROR getting a pointer from a temporary `String` will result in a dangling pointer
```

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs [hunk 5]
```diff
@@ -0,0 +1,13 @@
+#![deny(instantly_dangling_pointer)]
+
+const MAX_PATH: usize = 260;
+fn main() {
+    let str1 = String::with_capacity(MAX_PATH).as_mut_ptr();
```
Comment (Urgau) [inline tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs:5]: I wonder if it would make sense to suggest introducing a second binding in those simple `let` cases, aka.
```rust
    let str1 = String::with_capacity(MAX_PATH);
    let str1 = str1.as_mut_ptr();
```

File: compiler/rustc_lint/src/dangling.rs (hunk 1 above)
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs]: Done db4830a68cb3bed52137efd235745f9a19ed58c1

File: compiler/rustc_lint/src/dangling.rs (hunk 2 above)
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs]: Done 08f9947579dc15fae743f7fe2a8b43046d3c5ce3

File: compiler/rustc_lint/src/dangling.rs (hunk 3 above)
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs]: Done 08f9947579dc15fae743f7fe2a8b43046d3c5ce3

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 4 above)
Comment (GrigorenkoPV) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: The output is checked anyways in `.stderr` files

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 5 above)
Comment (GrigorenkoPV) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: Probably yes, but I would prefer to do this as a separate follow-up PR if possible

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 4 above)
Comment (Urgau) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: The output is checked but not enforced. There is nothing enforcing that the type displayed is the one we wanted.

> Although UI tests have a `.stderr` file which contains the entire compiler output, UI tests require that errors are also annotated within the source. This redundancy helps avoid mistakes since the `.stderr` files are usually auto-generated.

From ["UI - tests" in `rustc-dev-guide`](https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotations).

Btw, I don't think I have ever seen the syntax `ERROR [lint_name]` used anywhere in the test suite, except for error codes, so let's continue that way.

**Comment by GrigorenkoPV** [comment]
Looks like it caught an actual mistake in miri tests. However, this test was added after the PR had been opened, so I will have to rebase it now to be able to fix the tests.

**Comment by GrigorenkoPV** [comment]
Looks like this caught an actual mistake in miri tests. However, the test in question was added after this PR had been opened, so I will have to rebase now to be able to fix the test.

**Comment by GrigorenkoPV** [comment]
Rebased

File: src/tools/miri/tests/pass-dep/libc/libc-epoll.rs [hunk 6]
```diff
@@ -272,7 +272,8 @@ fn test_pointer() {
     assert_eq!(res, 0);
 
     // Register fd[1] with EPOLLIN|EPOLLOUT|EPOLLET
-    let data = MaybeUninit::<u64>::uninit().as_ptr();
+    let data = MaybeUninit::<u64>::uninit();
+    let data = data.as_ptr();
```
Comment (RalfJung) [inline src/tools/miri/tests/pass-dep/libc/libc-epoll.rs:276]: The fun thing is, this test is running in Miri, so it can't be UB. Obviously the temporary is not actually dropped immediately?

Comment (RalfJung) [reply src/tools/miri/tests/pass-dep/libc/libc-epoll.rs:276]: Ah never mind, we simply don't care about the pointer actually pointing to live data.

I'm not sure what is the point of this test -- we'll resolve this in Miri.

Comment (GrigorenkoPV) [reply src/tools/miri/tests/pass-dep/libc/libc-epoll.rs:276]: The problem is that here it gets passed to a libc function, which is probably a shim of some sorts.

I tried running this code under miri. It failed:

```rust
fn foo(x: *mut u8) {
    unsafe {
        *x = 123;
    }
}

fn main() {
    let x = core::mem::MaybeUninit::uninit().as_mut_ptr();
    foo(x);
}
```

So either the function does not use the pointer internally (thus not invoking UB), or there's some problem with shimming. Or I am wrong somewhere in my reasoning.

**Comment by RalfJung** [comment]
> Looks like this caught an actual mistake in miri tests. However, the test in question was added after this PR had been opened, so I will have to rebase now to be able to fix the test.

It did. That's a good demo for the lint being quite useful indeed. :)

File: library/core/src/ffi/c_str.rs [hunk 7]
```diff
@@ -463,7 +463,7 @@ impl CStr {
     /// behavior when `ptr` is used inside the `unsafe` block:
     ///
     /// ```no_run
-    /// # #![allow(unused_must_use)] #![allow(temporary_cstring_as_ptr)]
+    /// # #![allow(unused_must_use)] #![allow(dangling_pointers_from_temporaries)]
```
Comment (Urgau) [inline library/core/src/ffi/c_str.rs:466]: Due to bootstrapping we need to make the standard library build-able and test-able with the previous beta compiler. That can be achieved with the `bootstrap` config.
```suggestion
    /// # #![allow(unused_must_use)]
    /// # #![cfg_attr(bootstrap, allow(temporary_cstring_as_ptr))]
    /// # #![cfg_attr(not(bootstrap), allow(dangling_pointers_from_temporaries))]
```

Comment (GrigorenkoPV) [reply library/core/src/ffi/c_str.rs]: True, I forgot to mark it here. And forgot that cfg(bootstrap) exists in 25ee70b574cff3ea23e192b47a2bba9f144738e2. Thanks for the reminder.

**Comment by Urgau** [comment]
Let's prepare for a crater run...

@bors try

**Comment by Urgau** [comment]
Let's start the crater experiment.
Given the [current queue](https://crater.rust-lang.org/) it will probably take 1 or 2 weeks before the experiment starts.
To catch the places where the lint would fire, I've denied lint so crater can detected them as "regressions".

@craterbot check +rustflags=-Ddangling_pointers_from_temporaries

**Comment by Urgau** [comment]
(forgot that I need to manually specify the `start` and `end` to use `+rustflags`)

@craterbot run mode=check-only start=master#b5723af3457b9cd3795eeb97e9af2d34964854f2 end=try#217814b574c69492da200525b9df5f9ad1786800+rustflags=-Ddangling_pointers_from_temporaries

**Comment by GrigorenkoPV** [comment]
It seems like I will have to fix the false positive after all.

@rustbot author

**Comment by GrigorenkoPV** [comment]
This is just a rebase, I have not fixed anything yet

**Comment by Urgau** [comment]
@craterbot run mode=check-only start=master#9afe7136958edaa403f0b0eb00f0353c125b7352 end=try#9514db695be48b4781be4dd8dded5d4964057fb3+rustflags=-Ddangling_pointers_from_temporaries  crates=https://crater-reports.s3.amazonaws.com/pr-128985/retry-regressed-list.txt p=1

**Comment by GrigorenkoPV** [comment]
> 🎉 Experiment **`pr-128985-1`** is completed! 📊 63 regressed and 0 fixed (765 total) 📰 [Open the full report](https://crater-reports.s3.amazonaws.com/pr-128985-1/index.html).
> 
> ⚠️ If you notice any spurious failure [please add them to the blacklist](https://github.com/rust-lang/crater/blob/master/config.toml)! ℹ️ **Crater** is a tool to run experiments across parts of the Rust ecosystem. [Learn more](https://github.com/rust-lang/crater)

I have gone through every "regressed" crate manually. Almost all of them are genuine bugs caught by the lint.

Four exceptions:

- `compact_str-0.8.0`
  ```rust
  assert_eq!(String::new().as_ptr(), new_str_addr);
  ```
  should add `#[allow]`
- `mstr-0.1.4` checks that converting custom String to std's String does not reallocate. Should `allow`.
- `Aearnus/mefa` & `AeroNotix/emacs` needs further investigation. Looks like a false positive.

**Comment by GrigorenkoPV** [comment]
Okay, the fix was laughably simple

@rustbot ready

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 5 above)
Comment (GrigorenkoPV) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: > I wonder if it would make sense to suggest introducing a second binding in those simple `let` cases, aka.
> 
> ```rust
>     let str1 = String::with_capacity(MAX_PATH);
>     let str1 = str1.as_mut_ptr();
> ```

After looking at the "regressed" code from crater, I can say that a lot of the time this suggestion will not fix the problem, and will just result in code like
```rust
let vec = some_iter.collect();
let ptr = vec.as_ptr();
return ptr;
```
or similar where the pointer still dangles eventually, even though we binded the temporary for now.

Sometimes it would make sense to suggest things like `.into_raw_parts()` instead of `.as_ptr()`, but then the user has to remember to do `::from_raw_parts()` if they want to avoid leaking...

Most of the places where this lint fires are not trivial to fix and actually require the person writing the code to use their brains and be more knowledgeable about what they are doing, which can only be achieved through more experience of writing `unsafe`, as well as some punches from the compiler, miri, or sanitizers.

I think that not providing this suggestion in places where it would help is less bad than improperly providing it in places where it wouldn't help.

**Comment by Urgau** [comment]
I played a bit this new implementation and came to this interesting example (with extension traits), which I don't think is yet represented in any tests. It would be good to have a test for it.

<details>

```rust
use std::fmt::Debug;

trait Ext {
    fn dbg(self) -> Self
    where
        Self: Sized + Debug,
    {
        dbg!(&self);
        self
    }
}

impl<T> Ext for *const T {}

fn main() {
    let _ptr = Vec::<u32>::new().as_ptr().dbg();
}
```

</details>

**Comment by GrigorenkoPV** [comment]
I'm not sure, what is so special about this example? This is caught by the lint just fine
```console
warning: getting a pointer from a temporary `Vec<u32>` will result in a dangling pointer
  --> ./test.rs:16:34
   |
16 |     let _ptr = Vec::<u32>::new().as_ptr().dbg();
   |                ----------------- ^^^^^^ this pointer will immediately be invalid
   |                |
   |                this `Vec<u32>` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
   |
   = note: pointers do not have a lifetime; when calling `as_ptr` the `Vec<u32>` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
   = help: for more information, see https://doc.rust-lang.org/reference/destructors.html
   = note: `#[warn(dangling_pointers_from_temporaries)]` on by default

warning: 1 warning emitted
```

And there is a test that calling a method on the dangling pointer does not suppress the warning:
https://github.com/rust-lang/rust/pull/128985/files#diff-5531e44c59233e91ebb70e90bd08875f742235b99abc99be5a2a10481eb0d750R41

**Comment by GrigorenkoPV** [comment]
Ah, I guess you mean that something like
```rust
trait Ext {
    fn dbg(self) -> Self;
}

impl Ext for *const u32 {
    fn dbg(self) -> Self {
        dbg!(unsafe { self.read() });
        self
    }
}

fn main() {
    let _ptr = vec![0].as_ptr().dbg();
}
```
does not cause UB. That is true (at least according to miri).

But I don't think excluding cases like that is worth it. Making this lint 100% accurate is impossible (or at least infeasible), we have miri / sanitizers / borrowchecker for that instead. So some false positives or false negatives are unavoidable. The lint is warn-by-default, not an error, so I would lean on the side of false positives rather than false negatives.

I did fix the `foo(vec![0,1,2].as_ptr())` case, because otherwise the lint would be too annoying to exist, but this example feels too obscure and contrived (I do not think I saw it even once on crater) and a method to be called on a pointer will be `.cast()` most of the time, which does not use the pointer and just propagates it further.

TL;DR: probably not worth the effort; i'd rather we have this false positive than introduce false negatives while trying to support this odd use-case.

**Comment by Urgau** [comment]
I agree that it's not worth the effort and I wasn't advocating for either way (lint or not linting on it). I was however advocating to at-least have a test with the current output so that any change to this pattern is noticed and intentional.

**Comment by GrigorenkoPV** [comment]
Added the test and rebased

**Comment by GrigorenkoPV** [comment]
Rebased to adhere to the new formatting style.

File: compiler/rustc_lint/src/dangling.rs [hunk 8]
```diff
@@ -0,0 +1,227 @@
...
+    /// foo({ let ptr = CString::new("hello").unwrap().as_ptr(); ptr })
+    /// ```
+    ///
+    /// We have to deal with this situation somehow.
+    ///
+    /// If we were a visitor, we could just keep track of
+    /// when we enter and exit places where lifetime extension kicks in
+    /// during visiting/walking and update a boolean flag accordingly.
+    ///
+    /// But we are not a visitor. We are a LateLintPass.
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:80]: Nothing prevents us from implementing a visitor and calling it from the `LateLintPass`. Presumably we would kick a [`rustc_hir::intravisit::Visitor`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/intravisit/trait.Visitor.html) from the `LateLintPass::check_fn` impl.

Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs:80]: Good idea! I had been thinking of doing that, but completely forgot about `check_fn` and though we would be doomed to call this on every `check_expr`.

Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs:80]: Unfortunately this does not play along well with `#[allow]` & `#[deny]` on statements inside fn. They are just ignored.

I tried making the visitor buffer the info for lints so that they can be emitted later in `check_expr`, but it seems like `check_expr`s get called *before* the `check_fn` or `check_body`.

File: compiler/rustc_lint/src/dangling.rs [hunk 9]
```diff
@@ -0,0 +1,227 @@
...
+    /// ```ignore (example)
+    /// foo(CString::new("hello").unwrap().as_ptr())
+    /// ```
+    ///
+    /// But this does:
+    /// ```ignore (example)
+    /// foo({ let ptr = CString::new("hello").unwrap().as_ptr(); ptr })
+    /// ```
+    ///
+    /// We have to deal with this situation somehow.
```
[the remark this answers is not in the document]
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs]: You are most likely correct, I've been using this term in a very hand-wavy way.

File: compiler/rustc_lint/src/dangling.rs (hunk 8 above)
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs]: Done

File: compiler/rustc_lint/src/dangling.rs [hunk 10]
```diff
@@ -0,0 +1,252 @@
...
+    }
+
+    fn check_expr(&mut self, cx: &LateContext<'tcx>, expr: &'tcx Expr<'tcx>) {
+        if let Some(decorator) = self.buffered.remove(&expr.hir_id) {
+            // FIXME: use `emit_lint` when `#[primary_span]` is added.
+            cx.emit_span_lint(
+                DANGLING_POINTERS_FROM_TEMPORARIES,
+                decorator.primary_span(),
+                decorator,
+            )
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:92]: I think using [`TyCtxt::emit_node_span_lint`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.emit_node_span_lint), which directly takes a `HirId` should remove the need to buffer the decorator at all, as it will compute the lint level at the given `HirId`.

In the visitor, something like this should do it:
```rust
cx.tcx.emit_span_lint(
    DANGLING_POINTERS_FROM_TEMPORARIES,
    expr.hir_id,
    expr.span,
    decorator,
)
```
which I think would also remove the need for the `check_fn_post`.

File: compiler/rustc_lint/src/dangling.rs [hunk 11]
```diff
@@ -0,0 +1,223 @@
...
+        _: &'tcx FnDecl<'tcx>,
+        body: &'tcx Body<'tcx>,
+        _: Span,
+        _: LocalDefId,
+    ) {
+        Visitor::from(cx).visit_body(body)
+    }
+}
+
+struct Visitor<'lcx, 'tcx> {
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:76]: I think we use a more descriptive name, maybe `DanglingPointersVisitor`?

File: compiler/rustc_lint/src/dangling.rs [hunk 12]
```diff
@@ -0,0 +1,223 @@
...
+    cx: &'lcx LateContext<'tcx>,
+    suppress: bool,
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:78]: Can you add a doc-comment explaining what `suppress` represent.

File: compiler/rustc_lint/src/dangling.rs [hunk 13]
```diff
@@ -0,0 +1,223 @@
...
+}
+
+impl<'lcx, 'tcx> From<&'lcx LateContext<'tcx>> for Visitor<'lcx, 'tcx> {
+    fn from(cx: &'lcx LateContext<'tcx>) -> Self {
+        Self { cx, suppress: false }
+    }
+}
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:85]: I don't think this is necessary, we aren't going to re-use this visitor; using `DanglingPointersVisitor { cx, suppress: false }.visit_body(...)` is fine.

File: compiler/rustc_lint/src/dangling.rs [hunk 14]
```diff
@@ -0,0 +1,223 @@
...
+/// ```ignore (example)
+/// foo(CString::new("hello").unwrap().as_ptr())
+/// ```
+///
+/// But this does:
+/// ```ignore (example)
+/// foo({ let ptr = CString::new("hello").unwrap().as_ptr(); ptr })
+/// ```
+///
+/// We have to deal with this situation somehow.
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:105]: Instead of this generic sentence, could you a simple explanation of how we deal with this.

File: compiler/rustc_lint/src/dangling.rs [hunk 15]
```diff
@@ -0,0 +1,223 @@
...
+}
+
+impl<'lcx, 'tcx> From<&'lcx LateContext<'tcx>> for Visitor<'lcx, 'tcx> {
+    fn from(cx: &'lcx LateContext<'tcx>) -> Self {
+        Self { cx, suppress: false }
+    }
+}
+
+/// Trying to deal with argument lifetime extension.
+///
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:88]:
```suggestion
```

**Comment by Urgau** [comment]
Looks good to me on a high level. Let's see what T-lang thinks about it.

@rustbot labels -S-waiting-on-review +I-lang-nominated

**Comment by compiler-errors** [comment]
Hey, can you clean up this PR history? 30 commits is a bit excessive even for a new lint :)

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by GrigorenkoPV** [comment]
> Hey, can you clean up this PR history? 30 commits is a bit excessive even for a new lint :)

Sure, I was waiting until the work is finished.

Squashed just now.

File: compiler/rustc_lint/messages.ftl [hunk 16]
```diff
@@ -420,6 +414,12 @@ lint_incomplete_include =
 
 lint_inner_macro_attribute_unstable = inner macro attributes are unstable
 
+lint_instantly_dangling = getting a pointer from a temporary `{$ty}` will result in a dangling pointer
+    .label_ptr = this pointer will immediately be invalid
+    .label_temporary = this `{$ty}` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
+    .note = pointers do not have a lifetime; when calling `{$callee}` the `{$ty}` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
+    .help = for more information, see https://doc.rust-lang.org/reference/destructors.html
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:421]:
```suggestion
    .help = for more information, see <https://doc.rust-lang.org/reference/destructors.html>
```

File: compiler/rustc_lint/messages.ftl [hunk 17]
```diff
@@ -420,6 +414,12 @@ lint_incomplete_include =
 
 lint_inner_macro_attribute_unstable = inner macro attributes are unstable
 
+lint_instantly_dangling = getting a pointer from a temporary `{$ty}` will result in a dangling pointer
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:417]: I would prefer if we would have a message that followed the lint name, i.e. signalling the dangling pointer first and then the temporary, as the issue is first and foremost the dangling pointer.

Maybe something like this?
```suggestion
lint_instantly_dangling = pointer to an immediately dropped temporary result in a dangling pointer
```

File: compiler/rustc_lint/src/dangling.rs [hunk 18]
```diff
@@ -0,0 +1,219 @@
...
+/// ```
+///
+/// So we have to keep track of when we are inside of a function/method call argument.
+struct DanglingPointerSearcher<'lcx, 'tcx> {
+    cx: &'lcx LateContext<'tcx>,
+    /// Keeps track of whether we are inside of function/method call arguments,
+    /// where this lint should not be emitted.
+    ///
+    /// See [the main doc][`Self`] for examples.
+    suppress: bool,
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:99]:
```suggestion
    inside_call_args: bool,
```

File: compiler/rustc_lint/src/dangling.rs [hunk 19]
```diff
@@ -0,0 +1,219 @@
...
+        let old = core::mem::replace(&mut self.suppress, suppress);
+        let result = callback(self);
+        self.suppress = old;
+        result
+    }
+}
+
+fn lint_expr(cx: &LateContext<'_>, expr: &Expr<'_>) {
+    if let ExprKind::MethodCall(method, receiver, _args, _span) = expr.kind
+        && matches!(method.ident.name, sym::as_ptr | sym::as_mut_ptr)
```
Comment (Urgau) [inline compiler/rustc_lint/src/dangling.rs:132]: If you want to do it in this PR (otherwise in a follow-up), we could add an `rustc` attribute to those `as_ptr`/`as_mut_ptr` methods.

You can follow https://github.com/rust-lang/rust/pull/132146/commits/afcb09b8c765bf2c5b1362b433725f57af51aaad and https://github.com/rust-lang/rust/pull/132146/commits/2a930d3818d1f4dcaf7a06ed7fc12c102268755d (from a PR of mine) with `check_applied_to_fn_or_method` instead, and something similar to this to check the attribute https://github.com/rust-lang/rust/blob/e454c45f1397e382cfb59f0b8970445c8efa875f/compiler/rustc_lint/src/ptr_nulls.rs#L49-L50

File: compiler/rustc_lint/src/lib.rs [hunk 20]
```diff
@@ -39,13 +39,15 @@
 #![feature(rustc_attrs)]
 #![feature(rustdoc_internals)]
 #![feature(trait_upcasting)]
+#![feature(vec_pop_if)]
```
Comment (Urgau) [inline compiler/rustc_lint/src/lib.rs:42]: not required anymore, right?
```suggestion
```

File: compiler/rustc_lint/src/dangling.rs (hunk 19 above)
Comment (GrigorenkoPV) [reply compiler/rustc_lint/src/dangling.rs:132]: I would prefer to do this as a follow-up, just not to stall this one any longer

Comment (Urgau) [reply compiler/rustc_lint/src/dangling.rs:136]: I've created #132281 to track the use of a `rustc` attr for this lint.

Feel free to assign it to your-self (`@rustbot assign` I think).

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 5 above)
Comment (Urgau) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: I still feel like we should point users towards doing something, even if it's not a general solution, and not a a structured suggestion.

It's really a shame to tell users something but not how to fix it.

Opened #132283 to track this.

File: compiler/rustc_lint/messages.ftl [hunk 21]
```diff
@@ -203,14 +203,14 @@ lint_confusable_identifier_pair = found both `{$existing_sym}` and `{$sym}` as i
...
-    .note = pointers do not have a lifetime; when calling `as_ptr` the `CString` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
-    .help = for more information, see https://doc.rust-lang.org/reference/destructors.html
-
 lint_custom_inner_attribute_unstable = custom inner attributes are unstable
 
+lint_dangling_pointers_from_temporaries = a dangling pointer will be produced because the temporary `{$ty}` will be dropped
+    .label_ptr = this pointer will immediately be invalid
+    .label_temporary = this `{$ty}` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
+    .note = pointers do not have a lifetime; when calling `{$callee}` the `{$ty}` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
+    .help = for more information, see <https://doc.rust-lang.org/reference/destructors.html>
```
Comment (Urgau) [inline compiler/rustc_lint/messages.ftl:212]: It's too bad that we don't have place explaining what a "dangling pointer" is, we could have linked it here.

Opened #132286 about that.

**Review by Urgau — APPROVED** [review]

**Comment by Urgau** [comment]
It's clear that some improvements could be made (#132281, #132283, #132286), but IMO these improvements do not block merging this PR, *they are all pre-existing anyway*.

Therefore, @bors r+

File: tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs (hunk 5 above)
Comment (RalfJung) [reply tests/ui/lint/dangling-ptr/instantly-dangling-pointer-issue123613.rs]: > It's really a shame to tell users something but not how to fix it.

It's even worse to suggest something that is *no a fix*. So if you are *sure* you have a correct suggestion, then sure, please make it -- but never do this unless you are sure. People will trust the suggestion and then be worse off than before.
