### PR TITLE
Document why Any is not an unsafe trait

### LINKED ISSUE #62303: Any trait should be unsafe
## What is wrong?

Since `type_id()` is stable rust programs rely on `Any` to be implemented correctly for rust safety relevant thinks (like downcast).

Given the coding guide lines `Any` needs to be a `unsafe`-to-implement trait as implementing it wrongly causes unsafety.

## Is it a problem?

Luckily no on can (currently) implement `Any` per-hand as any implementation conflicts with it's wild card implementations this means:
1. All impl. of `Any` happen to be correct.
2. We can change it without causing breakage, at last as far as I can tell.

## Why should we change it?

The std is often used as an example for how thinks are done correctly in rust. If it is unsafe people looking at it would potentially think about why it needs to be unsafe and learn something from it. But if it isn't they might be surprised when there `Any` like trait is leads to unsafe behavior.

## What if we can't change it?

I think we can, as practically no one can implement any by hand. But if we can't we should at last document that it should be any in it's rust doc.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
The added documentation is not public (i.e., not in a doc comment) but that seems appropriate for this sort of low-level detail.

Fixes #62303

### CODE REVIEW

File: src/libcore/any.rs [hunk 1]
```diff
@@ -74,6 +74,16 @@ use crate::intrinsics;
 /// See the [module-level documentation][mod] for more details.
 ///
 /// [mod]: index.html
+// This trait is not unsafe, though we rely on the specifics of it's sole impl's
+// `type_id` function in unsafe code (e.g., `downcast`). Normally, that would be
+// a problem, but because the only impl of Any is a blanket implementation, no
```
Comment (Centril) [inline src/libcore/any.rs]:
```suggestion
// a problem, but because the only impl of `Any` is a blanket implementation, no
```

File: src/libcore/any.rs [hunk 2]
```diff
@@ -74,6 +74,16 @@ use crate::intrinsics;
...
+// other code can implement Any.
```
Comment (Centril) [inline src/libcore/any.rs]:
```suggestion
// other code can implement `Any`.
```

File: src/libcore/any.rs [hunk 3]
```diff
@@ -74,6 +74,16 @@ use crate::intrinsics;
...
+//
+// We could plausibly make this trait unsafe -- it would not cause breakage,
+// since we control all the implementations -- but we choose not to as that's
+// both not really necessary and may confuse users about the distinction of
+// unsafe traits and unsafe methods (i.e., type_id would still be safe to call,
```
Comment (Centril) [inline src/libcore/any.rs]:
```suggestion
// unsafe traits and unsafe methods (i.e., `type_id` would still be safe to call,
```

**Review by Centril — COMMENTED** [review]
r=me with nits

File: src/libcore/any.rs [hunk 4]
```diff
@@ -74,6 +74,16 @@ use crate::intrinsics;
...
+// This trait is not unsafe, though we rely on the specifics of it's sole impl's
+// `type_id` function in unsafe code (e.g., `downcast`). Normally, that would be
+// a problem, but because the only impl of `Any` is a blanket implementation, no
+// other code can implement `Any`.
+//
+// We could plausibly make this trait unsafe -- it would not cause breakage,
+// since we control all the implementations -- but we choose not to as that's
+// both not really necessary and may confuse users about the distinction of
+// unsafe traits and unsafe methods (i.e., `type_id` would still be safe to call,
+// but we would likely want to indicate as such in documentation).
```
Comment (RalfJung) [inline src/libcore/any.rs]: To the contrary, I think making this trait unsafe will *help* explain the difference between unsafe traits and unsafe methods as it gives a fairly simple example for such a combination. Anyone writing unsafe code should be comfortable with that distinction.

Not a big deal, though.

Comment (Centril) [reply src/libcore/any.rs]: Yeah, fwiw, I had the same thought while reading this, but ultimately kept quiet cause "not a big deal". ^^

Comment (Mark-Simulacrum) [reply src/libcore/any.rs]: I mostly just didn't want to wait for crater, but since people seem on board with unsafe here I might reconsider. I do think it's not a bad example.
