### PR TITLE
std: lazily allocate the main thread handle

### LINKED ISSUE #132619: `std::thread::Thread` grew from one to two pointer sizes
Caused by the changes in #123550 the size of `std::thread::Thread` grew from one to two pointer sizes.

The docs don't promise `Thread` to have a certain size so I'm not quite sure whether this would be considered a breaking change. It doesn't seem however like this was noticed/acknowledged in the PR, as having a larger thread handle might negate the benefits that PR brought with it.

### Code

I tried this code:

```rust
let pointer_size = size_of::<*const ()>();
let thread_size = size_of::<std::thread::Thread>();
assert_eq!(pointer_size, thread_size);
```

I expected to see this happen: *it to run successfully*

Instead, this happened: *the assert is unfulfilled and it panics*

### Version it worked on

It most recently worked on: Rust 1.82

### Version with regression

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b8c8287a2 2024-11-03)
binary: rustc
commit-hash: b8c8287a229cd79604aa84c25e1235fc78cd5f2e
commit-date: 2024-11-03
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

### PR DESCRIPTION
**Pull request by joboet**
https://github.com/rust-lang/rust/pull/123550 eliminated the allocation of the main thread handle, but at the cost of greatly increased complexity. This PR proposes another approach: Instead of creating the main thread handle itself, the runtime simply remembers the thread ID of the main thread. The main thread handle is then only allocated when it is used, using the same lazy-initialization mechanism as for non-runtime use of `thread::current`, and the `name` method uses the thread ID to identify the main thread handle and return the correct name ("main") for it.

Thereby, we also allow accessing `thread::current` before main: as the runtime no longer tries to install its own handle, this will no longer trigger an abort. Rather, the name returned from `name` will only be "main" after the runtime initialization code has run, but I think that is acceptable.

This new approach also requires some changes to the signal handling code, as calling `thread::current` would now allocate when called on the main thread, which is not acceptable. I fixed this by adding a new function (`with_current_name`) that performs all the naming logic without allocation or without initializing the thread ID (which could allocate on some platforms).

Reverts #123550, CC @GnomedDev

### CODE REVIEW

**Comment by workingjubilee** [comment]
> I've also moved the Thread code into its own module, the size of thread/mod.rs is just getting out of hand.

`std::thread::thread` here we come?

**Review by ChrisDenton — COMMENTED** [review]
I'd be happy with this approach but it would be nice to have some consensus on it to (hopefully) avoid further churn. I won't insist on it though.

**Comment by ChrisDenton** [comment]
Also could you separate the file move into a different commit? It's easier to diff that way.

File: library/std/src/thread/thread.rs [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+use crate::pin::Pin;
+use crate::sync::Arc;
+use crate::sys::sync::Parker;
+use crate::time::Duration;
+use crate::{fmt, str};
+
+/// The internal representation of a `Thread` handle
+struct Inner {
+    // INVARIANT: must be valid UTF-8
+    name: Option<CString>,
```
[the remark this answers is not in the document]
Comment (fbstj) [reply library/std/src/thread/thread.rs:14]: I also wondered if it made sense to have a new-type that held both invariants (UTF-8 & c-string \0 ending) ?

File: library/std/src/thread/mod.rs [hunk 2]
```diff
@@ -1211,7 +1207,7 @@ impl ThreadId {
         }
     }
 
-    #[cfg(not(target_thread_local))]
+    #[allow(unused)]
```
[the remark this answers is not in the document]
Comment (joboet) [reply library/std/src/thread/mod.rs:1210]: Because this is also used when 64-bit atomics are unavailable.

[the remark this answers is not in the document]
Comment (ChrisDenton) [reply library/std/src/thread/mod.rs:1210]: Is there any more specific `cfg` that can be used? `#[allow(unused)]`, while sometimes necessary, makes me nervous because it could silently become actual dead code in the future.

File: library/std/src/thread/thread.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (workingjubilee) [reply library/std/src/thread/thread.rs:14]: Utf8CStr is a fairly common type in the ecosystem, it would make sense for us to start tinkering with providing it.

**Comment by joboet** [comment]
Blocked on the efficiency fix in #132730, without that, we'd be creating a new `Thread` for every blocking `RwLock` call on macOS.

@rustbot label +S-blocked

**Comment by joboet** [comment]
I've undone the `Thread` move (that's probably worth another PR) and fixed some other things related to signal handling (`thread::current` now allocates on the main thread, so we mustn't call it in the signal handler).

@rustbot ready

**Comment by joboet** [comment]
Blocked on #133457. This PR times everything *just* right so that the `TlsFree` codepath is hit in the tests.

File: library/std/src/thread/mod.rs [hunk 3]
```diff
@@ -1257,112 +1252,113 @@ impl ThreadId {
...
 
-    fn into_raw(self) -> *const () {
-        match self {
-            // Just return the pointer to `MAIN_THREAD_INFO`.
-            Self::Main(ptr) => crate::ptr::from_ref(ptr).cast(),
-            Self::Other(arc) => {
-                // Safety: We only expose an opaque pointer, which maintains the `Pin` invariant.
-                let inner = unsafe { Pin::into_inner_unchecked(arc) };
-                Arc::into_raw(inner) as *const ()
+pub(crate) fn with_current_name<F, R>(f: F) -> R
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1330]: If this is called from signal handler context, I think there should be a doc comment here explicitly saying that the function may be called from signal handler context. It seems fairly easily to accidentally break this property in the future.

File: library/std/src/thread/mod.rs [hunk 4]
```diff
@@ -1257,112 +1252,113 @@ impl ThreadId {
...
 // This module ensures private fields are kept private, which is necessary to enforce the safety requirements.
 mod thread_name_string {
-    use core::str;
-
     use crate::ffi::{CStr, CString};
+    use crate::str;
 
     /// Like a `String` it's guaranteed UTF-8 and like a `CString` it's null terminated.
     pub(crate) struct ThreadNameString {
         inner: CString,
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1260]: If this was a `Cow<'static, CString>`, could the main thread reference a `"main\0"` string literal and thus avoid a few `else if main_thread::get() == Some(self.inner.id)`?

Comment (joboet) [reply library/std/src/thread/mod.rs:1260]: The thread ID method has the advantage of working inside TLS destructors, so e.g. panicking in a TLS destructor on main now prints the correct name. And since we need the infrastructure anyway to detect the main thread in the first place, I figured this was better.

File: library/std/src/thread/mod.rs [hunk 5]
```diff
@@ -1257,112 +1252,113 @@ impl ThreadId {
...
+            if let Some(name) = &thread.inner.name {
+                return f(Some(name.as_str()));
+            } else if Some(thread.inner.id) == main_thread::get() {
+                return f(Some("main"));
             }
+        } else if let Some(main) = main_thread::get()
+            && let Some(id) = current::id::get()
+            && id == main
+        {
+            return f(Some("main"));
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1345]: This seems worth some comments explaining why "main" has two separate cases.

File: library/std/src/thread/mod.rs (hunk 4 above)
Comment (joboet) [reply library/std/src/thread/mod.rs:1260]: > The thread ID method has the advantage of working inside TLS destructors, so e.g. panicking in a TLS destructor on main now prints the correct name. And since we need the infrastructure anyway to detect the main thread in the first place, I figured this was better.

Wait no, that's not related. I'll definitely undo the change from `ThreadName` then next time I update this PR.

Comment (joboet) [reply library/std/src/thread/mod.rs:1260]: > The thread ID method has the advantage of working inside TLS destructors, so e.g. panicking in a TLS destructor on main now prints the correct name. And since we need the infrastructure anyway to detect the main thread in the first place, I figured this was better.

Sorry, that scenario wasn't the issue. The actual reason why this mustn't change is that there is now nothing stopping `thread::current` from being called before main, which would lead to an incorrect name being stored. The ID-based detection doesn't have this issue, because the name will be correct as soon as the runtime has initialized the ID.

Comment (RalfJung) [reply library/std/src/thread/mod.rs:1260]: Ah, that is subtle. More comments would be good. :)

**Comment by joboet** [comment]
I've rebased this on top of #133457 and added some comments explaining everything.

File: tests/debuginfo/thread.rs [hunk 6]
```diff
@@ -12,15 +12,15 @@
...
-// cdb-check:    [...] __0              : Other [Type: enum2$<std::thread::Inner>]
-// cdb-check:         [...] __0              [Type: core::pin::Pin<alloc::sync::Arc<std::thread::OtherInner,[...]> >]
+// cdb-check:[...] inner [...][Type: core::pin::Pin<alloc::sync::Arc<std::thread::Inner,alloc::alloc::Global> >]
 
 use std::thread;
 
 #[allow(unused_variables)]
-fn main() {
+fn main()
+{
```
Comment (ChrisDenton) [inline tests/debuginfo/thread.rs:23]: That seems... weird. Is that intentional?

**Review by ChrisDenton — APPROVED** [review]
Thanks. This looks good to me. I do have one query but otherwise r=me.

File: tests/debuginfo/thread.rs (hunk 6 above)
Comment (joboet) [reply tests/debuginfo/thread.rs:23]: It is part of the revert of #123550. I can undo it if necessary.
