### PR TITLE
Fix `x.py setup` sets `changelog-seen`

### LINKED ISSUE #77572: `x.py setup` should set `changelog-seen`
New contributors haven't use `x.py` before, so there's no reason for them to read the changelog: nothing has changed.

```
$ x.py setup
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Welcome to the Rust project! What do you want to do with x.py?
a) Contribute to the standard library
b) Contribute to the compiler
c) Contribute to the compiler, and also modify LLVM or codegen
d) Install Rust from source
Please choose one (a/b/c/d): a
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
`x.py` will now use the configuration at /home/joshua/rustc2/src/bootstrap/defaults/config.toml.library
To get started, try one of the following commands:
- `x.py check`
- `x.py build`
- `x.py test library/std`
- `x.py doc`
For more suggestions, see https://rustc-dev-guide.rust-lang.org/building/suggested.html
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
note: this message was printed twice to make it more likely to be seen
$ x.py check
Updating only changed submodules
Submodules updated in 0.01 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
Checking std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
```

### PR DESCRIPTION
**Pull request by winnsterx**
Fixes #77572 by setting changelog-seen in setup.rs

### CODE REVIEW

File: src/bootstrap/bin/main.rs [hunk 1]
```diff
@@ -13,7 +13,11 @@ fn main() {
     let args = env::args().skip(1).collect::<Vec<_>>();
     let config = Config::parse(&args);
 
-    let changelog_suggestion = check_version(&config);
+    // check_version warnings are not printed during setup
+    let mut changelog_suggestion = None;
+    if !matches!(config.cmd, Subcommand::Setup {..}) {
+        changelog_suggestion = check_version(&config);
+    }
```
Comment (jyn514) [inline src/bootstrap/bin/main.rs:20]:
```suggestion
    None;
    let changelog_suggestion = if matches!(config.cmd, Subcommand::Setup {..}) {
        None
    } else {
        check_version(&config);
    };
```

File: src/bootstrap/setup.rs [hunk 2]
```diff
@@ -50,6 +50,7 @@ impl fmt::Display for Profile {
 }
 
 pub fn setup(src_path: &Path, profile: Profile) {
+    const VERSION: usize = 2;
```
Comment (jyn514) [inline src/bootstrap/setup.rs:53]: Can you remove `VERSION` from `bin/main.rs` and re-export this? That way they'll be kept in sync and you won't have to update it in two places.

**Comment by jyn514** [comment]
You need to run `x.py fmt`:
```
 If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
     let config = Config::parse(&args);
 
     // check_version warnings are not printed during setup
-    let changelog_suggestion = if matches!(config.cmd, Subcommand::Setup {..}) {
-        None
-    } else {
-        check_version(&config)
-    };
+    let changelog_suggestion =
+        if matches!(config.cmd, Subcommand::Setup {..}) { None } else { check_version(&config) };
```
r=me after that, thanks so much for working on this!

**Comment by jyn514** [comment]
also, if you could squash the commits, that would be great: https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing. I won't block on that though.

**Comment by jyn514** [comment]
@bors r+

Thanks for working on this!
