### PR TITLE
rustdoc: Render visibilities succinctly

### LINKED ISSUE #79139: regression: Rustdoc shows `pub(self)` as `pub(in a::b)`
This is a pre-emptive bug report for when https://github.com/rust-lang/rust/pull/77820 lands.

```rust
mod a {
  mod b {
        pub(self) struct FooInSelfSuperB;
  }
}
```

I expected to see this happen: Rustdoc displays the privacy as written: `pub(self) struct FooInSelfSuperB;`

Instead, this happened: Rustdoc displays an absolute path: `pub(in a::b) struct FooInSelfSuperB;`

A similar bug exists for `pub(super)`. The regressions for other paths (`pub(super::super)` -> `pub(crate)`, `pub(in crate::a::b)` -> `pub(in a::b)`, etc.) are explicitly not in scope and I don't plan to fix them.

Note that this always requires using `--document-private-items`.

### Implementation Notes

This is not trivial to fix because `html::render` does not have access to a `TyCtxt` and `impl Clean for ty::Visibility` does not have access to the original `DefId` of the item being documented. `impl Clean` need to be turned into a free function, and https://github.com/rust-lang/rust/pull/77820#discussion_r523764303 needs to be debugged. See https://github.com/jyn514/rust/commit/b997e4fe4e1af7294a8bc0144220b0a4a8ed4357 for partial progress on that; feel free to take over that branch if you're interested in fixing this.

### Meta

This version of rustdoc has not yet landed; see https://github.com/rust-lang/rust/pull/77820.

### PR DESCRIPTION
**Pull request by camelid**
Fixes #79139.

r? @jyn514

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -2299,14 +2299,14 @@ impl Clean<Item> for (&hir::MacroDef<'_>, Option<Symbol>) {
...
-                    vis.print_with_space(cx.tcx),
+                    vis.print_with_space(cx.tcx, item.hir_id.owner),
                     name,
                     matchers.iter().map(|span| span.to_src(cx)).collect::<String>(),
                 )
             } else {
                 format!(
                     "{}macro {} {{\n{}}}",
-                    vis.print_with_space(cx.tcx),
+                    vis.print_with_space(cx.tcx, item.hir_id.owner),
```
Comment (camelid) [inline src/librustdoc/clean/mod.rs:2309]: Are these two correct? I'm not sure if this is the correct LocalDefId to use.

**Comment by camelid** [comment]
Well, it looks like there's an issue somewhere because about 2/3 of the rustdoc tests are failing! It seems there's some ICEing, I assume from `expect_local()`.

**Comment by camelid** [comment]
So I guess I'll have to change the approach. I can't just use `tcx.parent_module_from_def_id` because that requires a `LocalDefId`, and we're not always documenting local items (e.g. when documenting impls of non-local traits on local types). How do I get the parent module of a non-local item then?

**Comment by jyn514** [comment]
>  How do I get the parent module of a non-local item then?

Can you refactor https://github.com/rust-lang/rust/blob/1832bdd7de93573464e1536e3ea17d5fd7d2888b/src/librustdoc/passes/collect_intra_doc_links.rs#L777-L795 into a function?

**Comment by jyn514** [comment]
(Ideally that would be part of rustc directly but there was some controversy about that: https://github.com/rust-lang/rust/pull/77984#issuecomment-709520174)

File: src/librustdoc/clean/mod.rs (hunk 1 above)
Comment (jyn514) [reply src/librustdoc/clean/mod.rs:2309]: This should be the ID of the item itself, not its owner ('owner' here is something like the containing scope). It should be `cx.tcx.hir().local_def_id(item.hir_id)` instead.

File: src/librustdoc/clean/mod.rs [hunk 2]
```diff
@@ -2299,14 +2299,14 @@ impl Clean<Item> for (&hir::MacroDef<'_>, Option<Symbol>) {
             if matchers.len() <= 1 {
                 format!(
                     "{}macro {}{} {{\n    ...\n}}",
-                    vis.print_with_space(cx.tcx),
+                    vis.print_with_space(cx.tcx, item.hir_id.owner),
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs:2302]: Same here, it should be the item's ID, not the owner.

File: src/librustdoc/html/format.rs [hunk 3]
```diff
@@ -1085,12 +1085,21 @@ impl Function<'_> {
 }
 
 impl clean::Visibility {
-    crate fn print_with_space<'tcx>(self, tcx: TyCtxt<'tcx>) -> impl fmt::Display + 'tcx {
+    crate fn print_with_space<'tcx>(
+        self,
+        tcx: TyCtxt<'tcx>,
+        item_did: LocalDefId,
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:1091]: As discussed, this is not necessarily local.
```suggestion
        item_did: DefId,
```

File: src/librustdoc/html/format.rs [hunk 4]
```diff
@@ -1085,12 +1085,21 @@ impl Function<'_> {
...
+    ) -> impl fmt::Display + 'tcx {
         use rustc_span::symbol::kw;
 
         display_fn(move |f| match self {
             clean::Public => f.write_str("pub "),
             clean::Inherited => Ok(()),
+            clean::Visibility::Restricted(did)
+                if did.index == tcx.parent_module_from_def_id(item_did).local_def_index =>
+            {
+                Ok(())
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:1101]:
```suggestion
                // `pub(self)` is the same as no visibility modifier
                Ok(())
```

File: src/librustdoc/html/format.rs [hunk 5]
```diff
@@ -1085,12 +1085,21 @@ impl Function<'_> {
...
+            }
             clean::Visibility::Restricted(did) if did.index == CRATE_DEF_INDEX => {
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:1103]: Can you also handle `pub(super)`?

nit: It might be worth making only a single match arm for `Restricted` and handling the special cases in there.

Comment (camelid) [reply src/librustdoc/html/format.rs:1103]: Yes, I was planning on handling it once I get the basics sorted out (i.e. fixing the ICEs). And yeah it probably makes sense to collapse the arms.

File: src/librustdoc/clean/mod.rs [hunk 6]
```diff
@@ -2299,14 +2299,14 @@ impl Clean<Item> for (&hir::MacroDef<'_>, Option<Symbol>) {
             if matchers.len() <= 1 {
                 format!(
                     "{}macro {}{} {{\n    ...\n}}",
-                    vis.print_with_space(cx.tcx),
+                    vis.print_with_space(cx.tcx, cx.tcx.hir().local_def_id(item.hir_id).to_def_id()),
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs]: nit: I would make this a local variable so it's not duplicated

File: src/librustdoc/clean/utils.rs [hunk 7]
```diff
@@ -624,3 +624,25 @@ where
...
+        } else {
+            debug!(
+                "{:?} has no parent (kind={:?}, original was {:?})",
+                current,
+                tcx.def_kind(current),
+                def_id
+            );
+            break None;
+        }
+    }
```
Comment (jyn514) [inline src/librustdoc/clean/utils.rs:647]: I think the debugging probably isn't necessary anymore.
```suggestion
    while let Some(parent) = tcx.parent(current) {
        if tcx.def_kind(parent) == DefKind::Mod {
            return Some(parent);
        }
        current = parent;
    }
    None
```

Comment (jyn514) [reply src/librustdoc/clean/utils.rs:647]: Also, I think this needs the whole if/else chain, not just the loop: https://github.com/rust-lang/rust/blob/bb178237c5539c75e1b85ab78a8ab902b1f333d5/src/librustdoc/passes/collect_intra_doc_links.rs#L770-L776

File: src/librustdoc/html/format.rs [hunk 8]
```diff
@@ -1085,32 +1085,43 @@ impl Function<'_> {
...
-                for seg in &path.data[..path.data.len() - 1] {
-                    write!(f, "{}::", seg.data.get_opt_name().unwrap())?;
+
+            clean::Visibility::Restricted(vis_did) => {
+                if find_closest_parent_module(tcx, item_did) == Some(vis_did) {
+                    // `pub(in foo)` where `foo` is the parent module
+                    // is the same as no visibility modifier
+                    Ok(())
+                } else if vis_did.index == CRATE_DEF_INDEX {
+                    write!(f, "pub(crate) ")
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:1105]: nit: the `CRATE_DEF_INDEX` check is faster, can you put it first?

File: src/librustdoc/html/format.rs [hunk 9]
```diff
@@ -1085,32 +1085,43 @@ impl Function<'_> {
...
-                // modified from `resolved_path()` to work with `DefPathData`
-                let last_name = path.data.last().unwrap().data.get_opt_name().unwrap();
-                for seg in &path.data[..path.data.len() - 1] {
-                    write!(f, "{}::", seg.data.get_opt_name().unwrap())?;
+
+            clean::Visibility::Restricted(vis_did) => {
+                if find_closest_parent_module(tcx, item_did) == Some(vis_did) {
+                    // `pub(in foo)` where `foo` is the parent module
+                    // is the same as no visibility modifier
+                    Ok(())
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:1103]: Hmm, I'm not sure how this will behave for modules - can you add a test case?

File: src/librustdoc/html/render/mod.rs [hunk 10]
```diff
@@ -3413,7 +3413,14 @@ fn render_struct(
...
                     clean::StructFieldItem(ref ty) => {
-                        write!(w, "{}{}", field.visibility.print_with_space(cx.tcx()), ty.print())
+                        write!(
+                            w,
+                            "{}{}",
+                            field
+                                .visibility
+                                .print_with_space(cx.tcx(), field.def_id),
+                            ty.print()
+                        )
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs]: nit: rustfmt really mangles this, can you use a local variable instead?
```suggestion
                        let vis = field.visibility.print_with_space(cx.tcx(), field.def_id);
                        write!(w, "{}{}", vis, ty.print());
```

File: src/test/rustdoc/decl_macro_priv.rs [hunk 11]
```diff
@@ -2,7 +2,7 @@
 
 #![feature(decl_macro)]
 
-// @has decl_macro_priv/macro.crate_macro.html //pre 'pub(crate) macro crate_macro() {'
+// @has decl_macro_priv/macro.crate_macro.html //pre 'macro crate_macro() {'
```
Comment (jyn514) [inline src/test/rustdoc/decl_macro_priv.rs:5]: This looks wrong. It would be fixed by checking `pub(crate)` before checking `pub(self)`.

File: src/test/rustdoc/visibility.rs [hunk 12]
```diff
@@ -0,0 +1,13 @@
...
+
+// @has 'foo/fn.foo.html' '//pre' 'fn foo'
+// !@has 'foo/fn.foo.html' '//pre' 'pub'
+fn foo() {}
+
+mod bar {
+    // @has 'foo/bar/fn.baz.html' '//pre' 'fn baz'
+    // !@has 'foo/bar/fn.baz.html' '//pre' 'pub'
+    fn baz() {}
+}
```
Comment (jyn514) [inline src/test/rustdoc/visibility.rs:13]: I would make this part of `pub(restricted)` instead.

File: src/librustdoc/html/format.rs (hunk 8 above)
Comment (camelid) [reply src/librustdoc/html/format.rs:1105]: That changes the behavior (top-level, non-pub items will be displayed as `pub(crate)` instead of no visibility modifier), but I'm doing that anyway.

Comment (camelid) [reply src/librustdoc/html/format.rs:1105]: Hmm, the behavior is the same for some reason.

File: src/librustdoc/html/format.rs (hunk 5 above)
Comment (camelid) [reply src/librustdoc/html/format.rs]: I now handle `pub(super)`.

File: src/librustdoc/html/format.rs (hunk 9 above)
Comment (camelid) [reply src/librustdoc/html/format.rs:1107]: What do you mean?

File: src/test/rustdoc/decl_macro_priv.rs (hunk 11 above)
Comment (camelid) [reply src/test/rustdoc/decl_macro_priv.rs:5]: Yep, fixed.

File: src/librustdoc/html/format.rs (hunk 8 above)
Comment (camelid) [reply src/librustdoc/html/format.rs]: I put the check first because we both agree that that behavior is better, but it's not going to be any faster: I extracted a local variable for the parent module because in `pub(super)` case it would compute it twice otherwise. Plus, it's easier to read and less error prone this way. Let me know if you have an idea to get the best of both worlds!

File: src/test/rustdoc/decl_macro_priv.rs (hunk 11 above)
Comment (camelid) [reply src/test/rustdoc/decl_macro_priv.rs]: I'm kind of surprised that the private macro isn't rendered as `pub(crate)` (which is what a private function in that position would do). Is that a quirk of declarative `macro`s?

File: src/test/rustdoc/visibility.rs (hunk 12 above)
Comment (camelid) [reply src/test/rustdoc/visibility.rs]: I merged the `pub-restricted` and `visibility` tests into just one named `visibility`.

File: src/librustdoc/html/render/mod.rs (hunk 10 above)
Comment (camelid) [reply src/librustdoc/html/render/mod.rs]: The current version looks like this:

```rust
                        write!(
                            w,
                            "{}{}",
                            field.visibility.print_with_space(cx.tcx(), field.def_id),
                            ty.print()
                        )
```

Is that okay?

File: src/librustdoc/clean/utils.rs (hunk 7 above)
Comment (camelid) [reply src/librustdoc/clean/utils.rs]: Done.

File: src/librustdoc/clean/mod.rs (hunk 6 above)
Comment (camelid) [reply src/librustdoc/clean/mod.rs]: Done.

**Comment by camelid** [comment]
Ready for another review!

@rustbot label +S-waiting-on-review -S-waiting-on-author

File: src/librustdoc/html/format.rs (hunk 9 above)
Comment (jyn514) [reply src/librustdoc/html/format.rs:1107]: If you have `mod x;`, `x` is public, but the parent will be the current module, not `x`. So it's actually public in the current module, not in `x`. I'm not sure how your code will behave in that case.

File: src/librustdoc/html/render/mod.rs (hunk 10 above)
Comment (jyn514) [reply src/librustdoc/html/render/mod.rs]: Not my preference but good enough not to worry about.

File: src/librustdoc/clean/mod.rs [hunk 13]
```diff
@@ -2295,18 +2295,20 @@ impl Clean<Item> for (&hir::MacroDef<'_>, Option<Symbol>) {
             )
         } else {
             let vis = item.vis.clean(cx);
+            let vis_printed_with_space =
+                vis.print_with_space(cx.tcx, cx.tcx.hir().local_def_id(item.hir_id).to_def_id());
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs:2299]: Oh I just meant the `local_def_id().to_def_id()` bit, but this works too.

File: src/librustdoc/clean/utils.rs [hunk 14]
```diff
@@ -624,3 +624,24 @@ where
     *cx.impl_trait_bounds.borrow_mut() = old_bounds;
     r
 }
+
+crate fn find_closest_parent_module(tcx: TyCtxt<'_>, def_id: DefId) -> Option<DefId> {
+    if item.is_fake() {
+        // FIXME: is this correct?
+        None
```
Comment (jyn514) [inline src/librustdoc/clean/utils.rs:631]: I think this is probably correct; at very least, there's no other reasonable behavior.
```suggestion
        None
```

File: src/librustdoc/clean/utils.rs [hunk 15]
```diff
@@ -624,3 +624,24 @@ where
...
+        // Find the first parent which is.
+        while let Some(parent) = tcx.parent(current) {
+            if tcx.def_kind(parent) == DefKind::Mod {
+                return Some(parent);
+            }
+            current = parent;
+        }
+        None
+    }
+}
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:647]: It seemed to work fine without these top-level conditionals (all the tests passed). I'm not sure to get this to work for all use cases, because sometimes we don't have an `Item` (e.g. with macros). Should we just remove this conditional logic (and leave it where it was, in the intra-doc link code)?

Comment (camelid) [reply src/librustdoc/clean/utils.rs:647]: Actually, `is_fake()`'s logic only needs a `DefId`, so I could still get this to work (if I extract out `is_fake()` so it operates on `DefId`s)
.

Comment (jyn514) [reply src/librustdoc/clean/utils.rs:647]: Oh, I realized why this isn't necessary: you can't give a visibility to either the crate root or blanket impls.

I don't feel strongly about whether you handle fake IDs here or in intra-doc-links, but if you remove it from here please leave a comment saying it will ICE if you use it on a fake id.

Comment (camelid) [reply src/librustdoc/clean/utils.rs:647]: Hmm, why will it panic on a fake ID?

Comment (jyn514) [reply src/librustdoc/clean/utils.rs]: It's used as an index into the crate metadata, it will panic with an index out of bounds error. Fake IDs weren't serialized to disk, so they aren't present in the metadata; really they should be a separate type that's only in rustdoc.

Comment (camelid) [reply src/librustdoc/clean/utils.rs]: Huh, okay. I'll add a comment.

Comment (camelid) [reply src/librustdoc/clean/utils.rs]: Done.

File: src/librustdoc/html/format.rs (hunk 9 above)
Comment (camelid) [reply src/librustdoc/html/format.rs:1107]: @jyn514 I don't think rustdoc even renders visibility for `mod`s though.

Comment (jyn514) [reply src/librustdoc/html/format.rs:1107]: Hmm, you're right: https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/passes/calculate_doc_coverage/index.html

It might want to in the future though - can you leave a `FIXME`? r=me with that done.

**Review by jyn514 — APPROVED** [review]

**Comment by jyn514** [comment]
@bors delegate=camelid

Make sure to use `r=jyn514`, not `r+` :P

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 16]
```diff
@@ -767,7 +767,12 @@ impl<'a, 'tcx> DocFolder for LinkCollector<'a, 'tcx> {
     fn fold_item(&mut self, mut item: Item) -> Option<Item> {
         use rustc_middle::ty::DefIdTree;
 
-        let parent_node = find_closest_parent_module(self.cx.tcx, item.def_id);
+        let parent_node = if item.is_fake() {
+            // FIXME: is this correct?
+            None
```
[the remark this answers is not in the document]
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Hmm, I think you were reviewing an old commit – this comment is no longer here.

File: src/librustdoc/html/format.rs (hunk 9 above)
Comment (camelid) [reply src/librustdoc/html/format.rs:1110]: Done.

**Comment by camelid** [comment]
I added some `@!has` checks as well.

**Comment by camelid** [comment]
Test passes locally.

@bors r=jyn514

**Comment by camelid** [comment]
Nominating for beta backport: this fixes a beta regression that makes visibilities shown in the output from `--document-private-items` verbose and confusing.

**Comment by jyn514** [comment]
I agree we should backport this, it fixes a regression introduced in 1.50, and happened to miss the cutoff and landed in 1.51 instead.

@rust-lang/rustdoc how do you feel about backporting this?

**Comment by camelid** [comment]
Also, beta was cut just a few days ago so it's not like beta's about to hit stable: We have time to catch any potential issues.

**Comment by GuillaumeGomez** [comment]
I think we should backport it as well.

**Comment by camelid** [comment]
Should this be marked as `beta-accepted` then?

**Comment by GuillaumeGomez** [comment]
I \*think\* it requires someone from the infra. cc @pietroalbini

**Comment by camelid** [comment]
My understanding (though I may be wrong) is that `beta-accepted` is used by the team responsible for the code (in this case, T-rustdoc) to say that it should be backported. Then someone (usually Mark-Simulacrum) goes through all the `beta-accepted` PRs and backports them.

**Comment by jyn514** [comment]
Oh, I was going to wait for @Manishearth to give an opinion. We as a team should probably come up with some policy for this.

**Comment by GuillaumeGomez** [comment]
For now, half the members agreed on it so let's add the label. But as many things, we'll need to formalize it.

**Comment by pietroalbini** [comment]
@GuillaumeGomez so, the policy for beta backports is the following:

1. Someone nominates the PR by adding the `beta-nominated` label and the relevant team label.
2. That team agrees to the nomination with whatever consensus mechanism they want, applies the `beta-accepted` label ***and keeps*** the `beta-nominated` label.
3. Someone from the release team looks through all the PRs with both the `beta-nominated` and `beta-accepted` labels, backports them and keeps just the `beta-accepted` label.

**Comment by GuillaumeGomez** [comment]
Thanks for the information! Is there a document available somewhere with the different processes? It would be very useful.

**Comment by pietroalbini** [comment]
The docs for backporting is <https://forge.rust-lang.org/release/beta-backporting.html>. I'm not sure if there is a document describing the processes of each team.

**Comment by Mark-Simulacrum** [comment]
@camelid just a minor note for the future - would be good to try to rebase before r+ing to squash out any minor fixup commits to try and keep commit history clean :)
