### PR TITLE
Separate MIR lints from validation

### LINKED ISSUE #104736: Out of storage use of local for temporary caused by label break
### Code

[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021). Needs release

```Rust
struct A;
struct B;

impl Drop for A {
    fn drop(&mut self) {}
}
impl Drop for B {
    fn drop(&mut self) {}
}

#[inline(always)]
fn no_unwind() {}

fn weird_temporary(a: A, b: B, nothing: ((), (), ()), x: bool) -> ((), (), ()) {
    'scope: {
        (
            {
                let _z = b;
                if x {
                    break 'scope nothing;
                }
            },
            match { a } {
                _ => (),
            },
            no_unwind(),
        )
    }
}

```

### Meta

Version: 0d5573e6daf99a5b98ace3dfcc4be2eb64867169 and all other recent versions

### Explanation

This causes an ICE in the MIR validator. The reason is an out of storage use of the local that is the temporary for `{ a }`. This local has a couple interesting properties. The most important of these is that MIR building thinks that it may need to be dropped while unwinding in two scenarios:

 1. If the drop of `_z` unwinds.
 2. If `no_unwind()` unwinds.

Neither of these are actually possible.

First, drop elaboration comes along, sees that only the second of these is possible. It reacts to this by inserting a drop flag for the local. Then, inlining comes along and inlines `no_unwind()`. The potential unwind edge is now gone.

The result is that the cleanup drop is actually completely unreachable, and this ends up causing an ICE.

Curiously, this does not reproduce if one replaces `break 'scope nothing;` with `return nothing;`. In the case of the return, MIR building correctly realizes that the temporary has not been created yet and hence does not need to be dropped. The best solution to this is likely to make the `break` do the same thing - I'm not sure how difficult that is.

### LINKED ISSUE #104843: Broken MIR ICE with let chains
Originally reported by @flip1995 in https://github.com/rust-lang/rust/issues/99938#issuecomment-1323700679 .

### Code

```Rust
#![feature(let_chains)]

struct F(Box<()>);

impl F {
    fn s(&self) -> Option<&str> {
        None
    }
}

fn cex() -> Option<F> {
    None
}

pub fn main() {
    if false
        && let Some(ce) = cex()
        && let Some(_ce) = ce.s()
    {
    }
}
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:9 ~ a[8fb6]::main), const_param_did: None }) (after phase change to runtime-optimized) at bb3[0]:
                                use of local _1, which has no storage here
  --> /tmp/a.rs:21:1
   |
21 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:88:36

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:9 ~ a[8fb6]::main), const_param_did: None }) (after phase change to runtime-optimized) at bb4[0]:
                                use of local _1, which has no storage here
  --> /tmp/a.rs:21:1
   |
21 | }
   | ^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:88:36

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1594:13

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0:     0x7f4776d010da - std::backtrace_rs::backtrace::libunwind::trace::h06e8f32b98d440be
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4776d010da - std::backtrace_rs::backtrace::trace_unsynchronized::h8a56795adafc3159
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4776d010da - std::sys_common::backtrace::_print_fmt::h7ba19acb3601abb5
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4776d010da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha37df576307c1a49
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4772c6fbae - core::fmt::write::hd3f2e7e755b45b01
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f4776cf53a5 - std::io::Write::write_fmt::hc1388e059aac0a41
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/io/mod.rs:1682:15
   6:     0x7f4776d00ea5 - std::sys_common::backtrace::_print::h429db1082d921ab8
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4776d00ea5 - std::sys_common::backtrace::print::h8d611e0005d3ccb9
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4776d0320f - std::panicking::default_hook::{{closure}}::h07380c607f829a79
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/panicking.rs:267:22
   9:     0x7f4776d02f4b - std::panicking::default_hook::h78998b3f3926502a
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/panicking.rs:286:9
  10:     0x7f4775f5b284 - <rustc_driver[153e38e44d5410f9]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[1d8afb50f4e7a45]::ops::function::FnOnce<(&core[1d8afb50f4e7a45]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4776d03a0d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbe7c77b7cbfe1f21
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/alloc/src/boxed.rs:2032:9
  12:     0x7f4776d03a0d - std::panicking::rust_panic_with_hook::hda16cab0ff009a11
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/panicking.rs:692:13
  13:     0x7f4775f93ab1 - std[2b5db76a972e300f]::panicking::begin_panic::<rustc_errors[6e875e03adfb8e66]::ExplicitBug>::{closure#0}
  14:     0x7f4775f923e6 - std[2b5db76a972e300f]::sys_common::backtrace::__rust_end_short_backtrace::<std[2b5db76a972e300f]::panicking::begin_panic<rustc_errors[6e875e03adfb8e66]::ExplicitBug>::{closure#0}, !>
  15:     0x7f4775f8ab76 - std[2b5db76a972e300f]::panicking::begin_panic::<rustc_errors[6e875e03adfb8e66]::ExplicitBug>
  16:     0x7f4775f8e306 - std[2b5db76a972e300f]::panic::panic_any::<rustc_errors[6e875e03adfb8e66]::ExplicitBug>
  17:     0x7f4775465556 - <rustc_errors[6e875e03adfb8e66]::HandlerInner>::flush_delayed::<alloc[eb468f42ab80a7c0]::vec::Vec<rustc_errors[6e875e03adfb8e66]::diagnostic::Diagnostic>, &str>
  18:     0x7f477546485b - <rustc_errors[6e875e03adfb8e66]::HandlerInner as core[1d8afb50f4e7a45]::ops::drop::Drop>::drop
  19:     0x7f477521271e - core[1d8afb50f4e7a45]::ptr::drop_in_place::<rustc_session[729ed7505232e216]::parse::ParseSess>
  20:     0x7f47751cb42f - core[1d8afb50f4e7a45]::ptr::drop_in_place::<rustc_session[729ed7505232e216]::session::Session>
  21:     0x7f47751cb160 - core[1d8afb50f4e7a45]::ptr::drop_in_place::<rustc_interface[d2ac3f3b3bfa4614]::interface::Compiler>
  22:     0x7f47751ca26e - rustc_span[cdf434c68ce75247]::with_source_map::<core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>, rustc_interface[d2ac3f3b3bfa4614]::interface::run_compiler<core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>, rustc_driver[153e38e44d5410f9]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  23:     0x7f47751c9ba5 - <scoped_tls[2ec6d95ce5fd8213]::ScopedKey<rustc_span[cdf434c68ce75247]::SessionGlobals>>::set::<rustc_interface[d2ac3f3b3bfa4614]::interface::run_compiler<core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>, rustc_driver[153e38e44d5410f9]::run_compiler::{closure#1}>::{closure#0}, core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>>
  24:     0x7f47751c9192 - std[2b5db76a972e300f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2ac3f3b3bfa4614]::util::run_in_thread_pool_with_globals<rustc_interface[d2ac3f3b3bfa4614]::interface::run_compiler<core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>, rustc_driver[153e38e44d5410f9]::run_compiler::{closure#1}>::{closure#0}, core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>>
  25:     0x7f47751c8ea8 - <<std[2b5db76a972e300f]::thread::Builder>::spawn_unchecked_<rustc_interface[d2ac3f3b3bfa4614]::util::run_in_thread_pool_with_globals<rustc_interface[d2ac3f3b3bfa4614]::interface::run_compiler<core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>, rustc_driver[153e38e44d5410f9]::run_compiler::{closure#1}>::{closure#0}, core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1d8afb50f4e7a45]::result::Result<(), rustc_errors[6e875e03adfb8e66]::ErrorGuaranteed>>::{closure#1} as core[1d8afb50f4e7a45]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f4776d0ac43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0c8cfd64ff347c2f
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/alloc/src/boxed.rs:2000:9
  27:     0x7f4776d0ac43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5243ef33e0bc55ac
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/alloc/src/boxed.rs:2000:9
  28:     0x7f4776d0ac43 - std::sys::unix::thread::Thread::new::thread_start::h248bc665ee6b9bda
                               at /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f4772985ff2 - start_thread
  30:     0x7f4772a08bfc - clone3
  31:                0x0 - <unknown>
```

</p>
</details>

The ICE requires `-O` to be passed to rustc, or `--release` be passed to cargo, the param to validate MIR is not enough. It's also a regression, on `nightly-2022-07-30` it does not reproduce.

cc #99938 and #99852 related issues with similar error messages, but they are fixed and this is reproducible.

@rustbot label E-needs-bisection

### LINKED ISSUE #116079: ICE: if_let_guard + mir drop tracking: broken mir
### Code
`rustc  -Zvalidate-mir -Zdrop-tracking-mir=yes --edition=2018`
```Rust
#![feature(if_let_guard)]

static mut A: [i32; 5] = [1, 2, 3, 4, 5];

async fn fun() {
    unsafe {
        match A {
            _ => (),
            i if let Some(1) = async { Some(1) }.await => (),
            _ => (),
        }
    }
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (b3aa8e716 2023-09-21)
binary: rustc
commit-hash: b3aa8e7168a3d940122db3561289ffbf3f587262
commit-date: 2023-09-21
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### Error output

```
<output>
```

### LINKED ISSUE #116736: broken mir while bootstrapping ra `hir-ty`
### Code

Code is inside the rustc repo from rust-analyzer `hir-ty`crate
` RUSTC_BOOTSTRAP=1 RUSTFLAGS="-Zvalidate-mir" ./x.py build`

### Meta

`rustc --version --verbose`:
```
495c5ddcf7c480da6d53d10ba02d2de2515ef155
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.03s
WARNING: The use of `changelog-seen` is deprecated. Please refer to `change-id` option in `config.example.toml` instead.
WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes made to the bootstrap configurations.
note: to silence this warning, add `change-id = 115898` at the top of `config.toml`
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.11s
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building stage1 library artifacts (x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.11s
Warning: no codegen-backends config matched the requested path to build a codegen backend. Help: add backend to codegen-backends in config.toml.
Building compiler artifacts (stage1 -> stage2, x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Building tool cargo (stage1 -> stage2, x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.14s
Building stage1 tool rls (x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.11s
Building stage1 tool rust-analyzer (x86_64-unknown-linux-gnu)
   Compiling hir-ty v0.0.0 (/home/matthias/vcs/github/rust/src/tools/rust-analyzer/crates/hir-ty)
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(DefId(0:4250 ~ hir_ty[34fe]::mir::lower::lower_to_mir)) (after pass Inline) at bb63[0]:
                                use of local _73, which has no storage here
    --> crates/hir-ty/src/mir/lower.rs:2132:6
     |
2132 |     };
     |      ^
     |
note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:310:22
         0: <rustc_errors::HandlerInner>::emit_diagnostic
                   at /home/matthias/vcs/github/rust/compiler/rustc_errors/src/lib.rs:1337:29
         1: <rustc_errors::HandlerInner>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
                   at /home/matthias/vcs/github/rust/compiler/rustc_errors/src/lib.rs:1621:9
         2: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
                   at /home/matthias/vcs/github/rust/compiler/rustc_errors/src/lib.rs:1007:9
         3: <rustc_const_eval::transform::validate::CfgChecker>::fail::<alloc::string::String>
                   at /home/matthias/vcs/github/rust/compiler/rustc_const_eval/src/transform/validate.rs:133:9
         4: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::visit_local
                   at /home/matthias/vcs/github/rust/compiler/rustc_const_eval/src/transform/validate.rs:310:17
         5: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::super_place
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:1160:13
         6: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::visit_place
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:182:17
         7: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::super_statement
         8: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::visit_statement
                   at /home/matthias/vcs/github/rust/compiler/rustc_const_eval/src/transform/validate.rs:391:9
         9: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::super_basic_block_data
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:309:21
        10: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::visit_basic_block_data
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:90:17
        11: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::super_body
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:294:17
        12: <rustc_const_eval::transform::validate::CfgChecker as rustc_middle::mir::visit::Visitor>::visit_body
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/mir/visit.rs:1205:1
        13: <rustc_const_eval::transform::validate::Validator as rustc_middle::mir::MirPass>::run_pass
                   at /home/matthias/vcs/github/rust/compiler/rustc_const_eval/src/transform/validate.rs:91:21
        14: rustc_mir_transform::pass_manager::validate_body
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/pass_manager.rs:164:5
        15: rustc_mir_transform::pass_manager::run_passes_inner
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/pass_manager.rs:139:17
        16: rustc_mir_transform::pass_manager::run_passes
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/pass_manager.rs:83:5
        17: rustc_mir_transform::run_optimization_passes
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/lib.rs:527:5
        18: rustc_mir_transform::inner_optimized_mir
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/lib.rs:623:5
        19: rustc_mir_transform::optimized_mir
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/lib.rs:585:21
        20: rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:585:47
        21: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:509:18
        22: rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:581:25
        23: <rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
                   at /home/matthias/vcs/github/rust/library/core/src/ops/function.rs:250:5
        24: <rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false> as rustc_query_system::query::config::QueryConfig<rustc_query_impl::plumbing::QueryCtxt>>::compute
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/lib.rs:119:9
        25: rustc_query_system::query::plumbing::execute_job_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:456:72
        26: rustc_middle::ty::context::tls::enter_context::<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
        27: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::try_with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:270:16
        28: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:246:9
        29: rustc_middle::ty::context::tls::enter_context::<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:9
        30: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:151:13
        31: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:133:9
        32: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:111:36
        33: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:100:18
        34: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:111:5
        35: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:124:5
        36: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:136:9
        37: rustc_query_system::query::plumbing::execute_job_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:456:18
        38: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:389:9
        39: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:332:13
        40: rustc_query_system::query::plumbing::get_query_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:786:32
        41: stacker::maybe_grow::<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::get_query_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
        42: rustc_data_structures::stack::ensure_sufficient_stack::<rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::query::plumbing::get_query_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/stack.rs:17:5
        43: rustc_query_system::query::plumbing::get_query_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:786:5
        44: rustc_query_impl::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:559:26
        45: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:156:17
        46: <rustc_middle::query::plumbing::TyCtxtAt>::optimized_mir::<rustc_span::def_id::LocalDefId>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:386:31
        47: <rustc_middle::ty::context::TyCtxt>::optimized_mir::<rustc_span::def_id::LocalDefId>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:377:17
        48: rustc_mir_transform::deduce_param_attrs::deduced_param_attrs
                   at /home/matthias/vcs/github/rust/compiler/rustc_mir_transform/src/deduce_param_attrs.rs:189:29
        49: rustc_query_impl::query_impl::deduced_param_attrs::dynamic_query::{closure#2}::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:585:47
        50: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::deduced_param_attrs::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:509:18
        51: rustc_query_impl::query_impl::deduced_param_attrs::dynamic_query::{closure#2}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:581:25
        52: <rustc_query_impl::query_impl::deduced_param_attrs::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
                   at /home/matthias/vcs/github/rust/library/core/src/ops/function.rs:250:5
        53: <rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false> as rustc_query_system::query::config::QueryConfig<rustc_query_impl::plumbing::QueryCtxt>>::compute
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/lib.rs:119:9
        54: rustc_query_system::query::plumbing::execute_job_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:456:72
        55: rustc_middle::ty::context::tls::enter_context::<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
        56: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::try_with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:270:16
        57: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:246:9
        58: rustc_middle::ty::context::tls::enter_context::<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:9
        59: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:151:13
        60: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:133:9
        61: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:111:36
        62: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:100:18
        63: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:111:5
        64: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:124:5
        65: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:136:9
        66: rustc_query_system::query::plumbing::execute_job_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:456:18
        67: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:389:9
        68: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:332:13
        69: rustc_query_system::query::plumbing::get_query_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:786:32
        70: stacker::maybe_grow::<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::get_query_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
        71: rustc_data_structures::stack::ensure_sufficient_stack::<rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::query::plumbing::get_query_non_incr<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/stack.rs:17:5
        72: rustc_query_system::query::plumbing::get_query_non_incr::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_system/src/query/plumbing.rs:786:5
        73: rustc_query_impl::query_impl::deduced_param_attrs::get_query_non_incr::__rust_end_short_backtrace
                   at /home/matthias/vcs/github/rust/compiler/rustc_query_impl/src/plumbing.rs:559:26
        74: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 16]>>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:156:17
        75: <rustc_middle::query::plumbing::TyCtxtAt>::deduced_param_attrs::<rustc_span::def_id::DefId>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:386:31
        76: <rustc_middle::ty::context::TyCtxt>::deduced_param_attrs::<rustc_span::def_id::DefId>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/query/plumbing.rs:377:17
        77: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_mir
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:1666:25
        78: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root::{closure#15}
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:614:29
        79: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:575:27
        80: rustc_metadata::rmeta::encoder::encode_metadata_impl
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:2235:16
        81: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}>, ()>
                   at /home/matthias/vcs/github/rust/library/std/src/panicking.rs:504:40
        82: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}>>
                   at /home/matthias/vcs/github/rust/library/std/src/panicking.rs:468:19
        83: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}>, ()>
                   at /home/matthias/vcs/github/rust/library/std/src/panic.rs:142:14
        84: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/sync/parallel.rs:26:9
        85: rustc_data_structures::sync::parallel::disabled::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/sync/parallel.rs:65:21
        86: rustc_data_structures::sync::parallel::parallel_guard::<(core::option::Option<()>, core::option::Option<()>), rustc_data_structures::sync::parallel::disabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/sync/parallel.rs:39:15
        87: rustc_data_structures::sync::parallel::disabled::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
                   at /home/matthias/vcs/github/rust/compiler/rustc_data_structures/src/sync/parallel.rs:64:22
        88: rustc_metadata::rmeta::encoder::encode_metadata
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:2184:5
        89: rustc_metadata::fs::encode_and_write_metadata
                   at /home/matthias/vcs/github/rust/compiler/rustc_metadata/src/fs.rs:65:13
        90: rustc_interface::passes::start_codegen
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/passes.rs:954:44
        91: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/queries.rs:205:16
        92: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context.rs:598:37
        93: rustc_middle::ty::context::tls::enter_context::<<rustc_middle::ty::context::GlobalCtxt>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:82:9
        94: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::try_with::<rustc_middle::ty::context::tls::enter_context<<rustc_middle::ty::context::GlobalCtxt>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:270:16
        95: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<<rustc_middle::ty::context::GlobalCtxt>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/library/std/src/thread/local.rs:246:9
        96: rustc_middle::ty::context::tls::enter_context::<<rustc_middle::ty::context::GlobalCtxt>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context/tls.rs:79:9
        97: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_middle/src/ty/context.rs:598:9
        98: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>, <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/queries.rs:68:9
        99: <rustc_interface::queries::Queries>::ongoing_codegen
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/queries.rs:194:9
       100: rustc_driver_impl::run_compiler::{closure#1}::{closure#2}
                   at /home/matthias/vcs/github/rust/compiler/rustc_driver_impl/src/lib.rs:455:35
       101: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/queries.rs:332:19
       102: rustc_driver_impl::run_compiler::{closure#1}
                   at /home/matthias/vcs/github/rust/compiler/rustc_driver_impl/src/lib.rs:390:22
       103: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/interface.rs:346:21
       104: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_span/src/lib.rs:1059:5
       105: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/interface.rs:340:13
       106: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                   at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
       107: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}>
                   at /home/matthias/vcs/github/rust/compiler/rustc_span/src/lib.rs:125:5
       108: rustc_interface::util::run_in_thread_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}
                   at /home/matthias/vcs/github/rust/compiler/rustc_interface/src/util.rs:163:38
       109: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/library/std/src/sys_common/backtrace.rs:154:18
       110: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/library/std/src/panicking.rs:504:40
       111: std::panicking::try::<core::result::Result<(), rustc_span::ErrorGuaranteed>, core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                   at /home/matthias/vcs/github/rust/library/std/src/panicking.rs:468:19
       112: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core::result::Result<(), rustc_span::ErrorGuaranteed>>
                   at /home/matthias/vcs/github/rust/library/std/src/panic.rs:142:14
       113: <std::thread::Builder>::spawn_unchecked_::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1}
                   at /home/matthias/vcs/github/rust/library/std/src/thread/mod.rs:528:30
       114: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                   at /home/matthias/vcs/github/rust/library/core/src/ops/function.rs:250:5
       115: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /home/matthias/vcs/github/rust/library/alloc/src/boxed.rs:2007:9
       116: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /home/matthias/vcs/github/rust/library/alloc/src/boxed.rs:2007:9
       117: std::sys::unix::thread::Thread::new::thread_start
                   at /home/matthias/vcs/github/rust/library/std/src/sys/unix/thread.rs:108:17
       118: <unknown>
       119: <unknown>
    --> crates/hir-ty/src/mir/lower.rs:2132:6
     |
2132 |     };
     |      ^

  <snip>
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/matthias/vcs/github/rust/src/tools/rust-analyzer/rustc-ice-2023-10-14T16:58:47.307861343Z-2158814.txt` to your bug report

note: compiler flags: --crate-type rlib -C opt-level=3 -C embed-bitcode=no -C codegen-units=16 -C debuginfo=2 -C overflow-checks=on -Z unstable-options -Z validate-mir -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -Z binary-dep-depinfo -Z tls-model=initial-exec -Z allow-features=binary-dep-depinfo,proc_macro_span,proc_macro_span_shrink,proc_macro_diagnostic,proc_macro_internals,proc_macro_diagnostic,proc_macro_span,proc_macro_span_shrink

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `hir-ty` (lib)
Build completed unsuccessfully in 0:01:11

```

</p>
</details>

### LINKED ISSUE #118990: MIR validation ICE: Use of local which has no storage
```rust
struct CompileError;

impl Drop for CompileError {
    fn drop(&mut self) {}
}

impl CompileError {
    fn throw(&self) {}
}

fn main() {
    'code: {
        break 'code;
        CompileError.throw()
    };
}
```
Build with
```
-Zvalidate-mir
```
```
error: internal compiler error: broken MIR in Item(DefId(0:9 ~ ice[5cf9]::main)) (before pass CheckPackedRef) at bb4[0]:
                                use of local _3, which has no storage here
  --> src/main.rs:15:6
   |
15 |     };
   |      ^

```
```
// MIR for `main` after built

fn main() -> () {
    let mut _0: ();
    let _1: ();
    let mut _2: &CompileError;
    let _3: CompileError;

    bb0: {
        StorageLive(_1);
        _1 = const ();
        goto -> bb3;
    }

    bb1: {
        StorageLive(_2);
        StorageLive(_3);
        _3 = CompileError;
        _2 = &_3;
        _1 = CompileError::throw(move _2) -> [return: bb2, unwind: bb6];
    }

    bb2: {
        StorageDead(_2);
        goto -> bb4;
    }

    bb3: {
        goto -> bb4;
    }

    bb4: {
        drop(_3) -> [return: bb5, unwind: bb7];
    }

    bb5: {
        StorageDead(_3);
        StorageDead(_1);
        _0 = const ();
        return;
    }

    bb6 (cleanup): {
        drop(_3) -> [return: bb7, unwind terminate(cleanup)];
    }

    bb7 (cleanup): {
        resume;
    }
}
```

### PR DESCRIPTION
**Pull request by tmiasko**
Add a MIR lint pass, enabled with -Zlint-mir, which identifies undefined or
likely erroneous behaviour.

The initial implementation mostly migrates existing checks of this nature from
MIR validator, where they did not belong (those checks have false positives and
there is nothing inherently invalid about MIR with undefined behaviour).

Fixes #104736
Fixes #104843
Fixes #116079
Fixes #116736
Fixes #118990

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Could you mention the new flag in the pr body somewhere so that `git log --grep Zlint-mir` finds it? :upside_down_face:

**Comment by saethlin** [comment]
> there is nothing inherently invalid about MIR with undefined behaviour

I can see this being true for dead code, but I don't understand how this is true in general. Can you explain?

File: compiler/rustc_mir_dataflow/src/impls/storage_liveness.rs [hunk 1]
```diff
@@ -81,17 +81,17 @@ impl<'tcx, 'a> crate::GenKillAnalysis<'tcx> for MaybeStorageLive<'a> {
 }
 
 #[derive(Clone)]
-pub struct MaybeStorageDead {
-    always_live_locals: BitSet<Local>,
+pub struct MaybeStorageDead<'a> {
+    always_live_locals: Cow<'a, BitSet<Local>>,
```
Comment (cjgillot) [inline compiler/rustc_mir_dataflow/src/impls/storage_liveness.rs:85]:
```suggestion
    always_live_locals: &'a BitSet<Local>,
```
?

**Review by cjgillot — COMMENTED** [review]
Should we enable this by default for miropt tests ? Eventually with an 'allow' attr if ub is expected ?

**Comment by matthiaskrgr** [comment]
````
Fixes https://github.com/rust-lang/rust/issues/104736
Fixes https://github.com/rust-lang/rust/issues/104843
Fixes https://github.com/rust-lang/rust/issues/116079
Fixes https://github.com/rust-lang/rust/issues/116736
Fixes https://github.com/rust-lang/rust/issues/118990
````

Hm, so I guess all of these still ICE with `-Zlint-mir`? 
What does this mean wrt the classification of such bugs?
Should they be reopened?

**Comment by est31** [comment]
I don't understand either why these issues were closed. Were they closed because they are false positives? Because I think that any case is a bug where you have safe Rust leading to UB in the generated MIR, whether there is an ICE about it or not. I think at least https://github.com/rust-lang/rust/issues/104736 and https://github.com/rust-lang/rust/issues/118990 fall under this. There is two more issues that don't have unsafe but use nightly features: those issues are also still important (unless they are false positives).

**Comment by saethlin** [comment]
In what sense are those false positives? Our documentation for the semantics of StorageLive/StorageDead clearly says such code is UB, and therefore it is a bug for MIR building to produce such code.

**Comment by saethlin** [comment]
That sounds to me like a rather specific issue with the use of storage check disagreeing with pre-drop-elaboration MIR. Why didn't you propose a targeted fix?

**Comment by RalfJung** [comment]
FWIW there are more UB checks in the validator, such as the check whether LHS and RHS overlap in assignment.

**Comment by RalfJung** [comment]
> we already had a false positive regarding memory overlap.

Do you have a link to that?
