### PR TITLE
rustc: Start moving toward "try_get is a bug" for incremental

### LINKED ISSUE #42633: incr.comp.: Clarify compatibility of red/green evaluation and recovering from cycle errors
I originally planned to describe the differences between the current query system and the future version that supports [red/green dependency tracking](https://github.com/rust-lang/rust/issues/42293) but while thinking about it, there's not too much of a difference when it comes to cycle errors:
* The in-memory caches of the query system will not change in the future.
* The [try_mark_green](https://gist.github.com/michaelwoerister/e278b4ad3eb88d61e19b7ab066c44b25#file-dep-graph-new-design-backup-rs-L196) step of red/green evaluation might `force` the evaluation of a query but that's no different from a regular query.
* There's been talk about having to prevent the caching of intermediate results if those intermediate results arise from a query that turns out to be cyclic, because those intermediate results are "tainted". However, I don't see how one would get ahold of such an intermediate result (both in the current system and the future one) in the first place: If a query `A` starts a sub-query `B` and `B` starts a sub-sub-query `C`, which would invoke `A` again, then we would have to make sure that neither the results of `B` or `C` are cached. But since we are still in the middle of computing `B` and `C`, we don't have any result to cache anyway.

The main difference I see between the current query system and the red/green one is dependency tracking (and there the current system behaves a bit strangely, actually): When a query is started, a new `DepNode` is allocated and reads to that `DepNode` are registered as they occur. E.g., we let's say we have the following "query trace":
```
Queries execute in the order of their label:

            1 <------------+
            |              |
    +-------+-------+      |
    |       |       |      |
    v       v       v      |
    2       4   +-- 5 --+  |
    |           |       |  |
    v           v       v  |
    3           6       7--+
```
The dependency graph would look exactly like that, cycle and all.

In the red/green system, a `DepNode` would only be allocated after the successful evaluation of a query. Consequently, we would not end up with the dep-graph shown above. But we still want to record dependencies to those sub-queries because their result influenced what `1` evaluated to after recovering from the cycle. I propose to just merge all reads into the parent query when encountering a cycle error, effectively merging all reads into the root of the cycle. The dep-graph from above would then look like this:

```
            1
            | 
    +-------+-------+
    |       |       |
    v       v       v
    2       4       6
    |
    v
    3
```
There are no `DepNodes` for `5` and `7` (they never completed) but we don't lose the information that `6` has been read, which is important, because the result of `6` might also have caused a trace without cycle.

I still think that recovering from cycle errors is dubious but at least the situation should not get worse with the new system.

Comments? @eddyb @nikomatsakis @rust-lang/compiler

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is an effort to burn down some of the work items on #42633. The basic change here was to leave the `try_get` function exposed but have it return a `DiagnosticBuilder` instead of a `CycleError`. This means that it should be a compiler bug to *not* handle the error as dropping a diagnostic should result in a complier panic.

After that change it was then necessary to update the compiler's callsites of `try_get` to handle the error coming out. These were handled as:

* The `sized_constraint` and `needs_drop_raw` checks take the diagnostic and defer it as a compiler bug. This was a new piece of functionality added to the error handling infrastructure, and the idea is that for both these checks a "real" compiler error should be emitted elsewhere, so it's only a bug if we don't actually emit the complier error elsewhere. 
* MIR inlining was updated to just ignore the diagnostic. This is being tracked by https://github.com/rust-lang/rust/issues/43542 which sounded like it either already had some work underway or was planning to change regardless.
* The final case, `item_path`, is still sort of up for debate. At the time of this writing this PR simply removes the invocations of `try_get` there, assuming that the query will always succeed. This turns out to be true for the test suite anyway! It sounds like, though, that this logic was intended to assist in "weird" situations like `RUST_LOG` where debug implementations can trigger at any time. This PR would therefore, however, break those implementations.

I'm unfortunately sort of out of ideas on how to handle `item_path`, but other thoughts would be welcome!

Closes #42633

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by eddyb** [comment]
> The `sized_constraint` and `needs_drop_raw` checks take the diagnostic and defer it as a compiler bug

Hadn't considered this, very nice solution! As for everything else, I'm fine with changing them for now.

File: src/librustc/ty/maps.rs [hunk 1]
```diff
@@ -205,7 +206,9 @@ pub struct CycleError<'a, 'tcx: 'a> {
 }
 
 impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
-    pub fn report_cycle(self, CycleError { span, cycle }: CycleError) {
+    pub fn report_cycle(self, CycleError { span, cycle }: CycleError)
```
Comment (eddyb) [inline src/librustc/ty/maps.rs]: Wait, can this and `CycleError` be private? The only reason they're public is for `try_get`, I think?
Also, `CycleError` can probably be decomposed into its fields now? Not sure though.

Comment (alexcrichton) [inline src/librustc/ty/maps.rs]: Sure yeah, I'll try to do this.

**Comment by aidanhs** [comment]
```

**Comment by aidanhs** [comment]
@bors r-

```
[00:06:36] [m[m[32m[1m   Compiling[m syntax_ext v0.0.0 (file:///checkout/src/libsyntax_ext)
[00:06:44] [1m[31merror[E0252](B[m[1m: the name `DiagnosticBuilder` is defined multiple times(B[m
[00:06:44]   (B[m[1m[34m--> (B[m/checkout/src/librustc/ty/maps.rs:13:26(B[m
[00:06:44]    (B[m[1m[34m|(B[m
[00:06:44] [1m[34m11(B[m (B[m[1m[34m| (B[muse errors::DiagnosticBuilder;(B[m
[00:06:44]    (B[m[1m[34m| (B[m    (B[m[1m[34m-------------------------(B[m (B[m[1m[34mprevious import of the type `DiagnosticBuilder` here(B[m
[00:06:44] [1m[34m12(B[m (B[m[1m[34m| (B[muse dep_graph::{DepConstructor, DepNode, DepNodeIndex};(B[m
[00:06:44] [1m[34m13(B[m (B[m[1m[34m| (B[muse errors::{Diagnostic, DiagnosticBuilder};(B[m
[00:06:44]    (B[m[1m[34m| (B[m                         (B[m[1m[31m^^^^^^^^^^^^^^^^^(B[m (B[m[1m[31m`DiagnosticBuilder` reimported here(B[m
[00:06:44]    (B[m[1m[34m|(B[m
[00:06:44]    (B[m[1m[34m= (B[m[1mnote(B[m: `DiagnosticBuilder` must be defined only once in the type namespace of this module(B[m
[00:06:44] 
[00:07:01] [1m[31merror(B[m[1m: aborting due to previous error(B[m
[00:07:01] 
[00:07:01] [m[m[31m[1merror:[m Could not compile `rustc`.
[00:07:01] 
```
