### PR TITLE
Remove const_in_array_repeat

### LINKED ISSUE #75682: thread 'rustc' panicked
### Code

```rust
struct InterruptSectorManager {
    field: &'static (),
}

static FOO: [InterruptSectorManager; 2] = [InterruptSectorManager { field: &() }; 2];
```

<details><summary><strong>Original</strong></summary>
<p>

```Rust
pub const TASK_NUM:        usize   = 10;
pub const INTERRUPT_NUM:   usize   = 14;

#[derive(Debug, Clone,Copy)]
pub struct Node
{
    pub(crate) elem:  fn(),
    pub(crate) next: *mut Node,
    pub(crate) prev: *mut Node,
}

pub struct InterruptManager
{
	pub(crate) interrupt_table: &'static[self::InterruptSectorManager;1 * desc::INTERRUPT_NUM],
}

pub struct InterruptSectorManager
{
	//pub(crate) interrupt_sector_table: &'static[Node; desc::TASK_NUMB],
	pub(crate) interrupt_sector_table: &'static [&'static [Node; desc::TASK_NUM]; desc::INTERRUPT_NUM],
}

pub static TASK_CONT: [Node; desc::TASK_NUM] =
	[Node{ elem: def_fn , next: 0 as *mut Node, prev: 0 as *mut Node }; desc::TASK_NUM];

static interrupt_sector_table: [interrupt_manager::InterruptSectorManager; desc::INTERRUPT_NUM] =
	[interrupt_manager::InterruptSectorManager{ interrupt_sector_table: &[&TASK_CONT; desc::INTERRUPT_NUM]}; desc::INTERRUPT_NUM];
pub static  interrupt_manager: interrupt_manager::InterruptManager = interrupt_manager::InterruptManager{ interrupt_table: &interrupt_sector_table };
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
<version>
note: rustc 1.45.2 (d3fb005a3 2020-07-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-Tlink.x --crate-type lib

```

### Error output

```
thread 'rustc' panicked at 'assertion failed: promoted.is_none()', src/librustc_mir/transform/check_consts/qualifs.rs:252:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### LINKED ISSUE #80371: Simple array of borrowing structs panics compiler
### Code

```Rust
pub struct Header<'a> {
    pub value: &'a [u8],
}

pub fn test() {
    let headers = [Header{value: &[]}; 128];
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-pc-windows-msvc
release: 1.48.0
LLVM version: 11.0

also seen in nightly:

rustc 1.50.0-nightly (0edce6f4b 2020-12-24)
binary: rustc
commit-hash: 0edce6f4bbb4514482537f569f0b8ef48e71e0a0
commit-date: 2020-12-24
host: x86_64-pc-windows-msvc
release: 1.50.0-nightly

```

### Error output

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0 (7eac88abb 2020-11-16) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=1 -C llvm-args=--x86-asm-syntax=intel -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 --crate-type rlib --crate-type lib

query stack during panic:
#0 [mir_borrowck] borrow-checking `test`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: promoted.is_none()', compiler\rustc_mir\src\transform\check_consts\qualifs.rs:248:9
stack backtrace:
   0:     0x7ff922a5a4a9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hba5f685a77e920dc
   1:     0x7ff922a8748b - core::fmt::write::h7e2938de326daa9d
   2:     0x7ff922a4b998 - <std::io::IoSlice as core::fmt::Debug>::fmt::h6db1280adf9c872d
   3:     0x7ff922a5f8d4 - std::panicking::take_hook::hfb0d507d25fcd861
   4:     0x7ff922a5f4b8 - std::panicking::take_hook::hfb0d507d25fcd861
   5:     0x7ff9188faa45 - rustc_driver::report_ice::he237f3b59ed412a9
   6:     0x7ff922a60330 - std::panicking::rust_panic_with_hook::h67dee359ed61e799
   7:     0x7ff91bb286f4 - <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt::hd5f962f5ee0af2ac
   8:     0x7ff91bb2858f - <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt::hd5f962f5ee0af2ac
   9:     0x7ff91bb285ed - <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt::hd5f962f5ee0af2ac
  10:     0x7ff91b82b49a - <rustc_mir::transform::check_consts::qualifs::CustomEq as rustc_mir::transform::check_consts::qualifs::Qualif>::in_adt_inherently::ha2a1515541536c41
  11:     0x7ff91b9ae5ce - rustc_mir::transform::promote_consts::collect_temps_and_candidates::h1bf2d5c6561d559e
  12:     0x7ff91b9af3fa - rustc_mir::transform::promote_consts::collect_temps_and_candidates::h1bf2d5c6561d559e
  13:     0x7ff91b9af3e2 - rustc_mir::transform::promote_consts::collect_temps_and_candidates::h1bf2d5c6561d559e
  14:     0x7ff91b9aeee7 - rustc_mir::transform::promote_consts::collect_temps_and_candidates::h1bf2d5c6561d559e
  15:     0x7ff91b9af075 - rustc_mir::transform::promote_consts::collect_temps_and_candidates::h1bf2d5c6561d559e
  16:     0x7ff91b9b4ed3 - rustc_mir::transform::promote_consts::promote_candidates::h98a0dd31ad25d6b2
  17:     0x7ff91b7b09bb - <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body::h5ea3273fde4f4bc1
  18:     0x7ff91b7b47e5 - <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body::h5ea3273fde4f4bc1
  19:     0x7ff91b7a7456 - <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt::h128e031426748928
  20:     0x7ff91ba0fd5a - <rustc_mir::borrow_check::invalidation::InvalidationGenerator as rustc_middle::mir::visit::Visitor>::visit_terminator::hfdaff8c21da2232f
  21:     0x7ff91bb848a7 - rustc_mir::borrow_check::provide::h7202fa8cdf50afb4
  22:     0x7ff91b6b56a4 - <rustc_mir_build::thir::pattern::_match::split_grouped_constructors::Border as core::fmt::Debug>::fmt::h9321f32f80e86e78
  23:     0x7ff91bb819c0 - rustc_mir::borrow_check::provide::h7202fa8cdf50afb4
  24:     0x7ff91bb513ff - <rustc_mir::util::storage::AlwaysLiveLocals as core::fmt::Debug>::fmt::h35f8a9f8cd51d351
  25:     0x7ff918b17f3e - rustc_interface::interface::parse_cfgspecs::h47201cf071ea3adb
  26:     0x7ff918ac4ad8 - <rls_span::OneIndexed as core::fmt::Debug>::fmt::hc2e3aeb3277dd105
  27:     0x7ff918b1845d - rustc_interface::interface::parse_cfgspecs::h47201cf071ea3adb
  28:     0x7ff918ab5e20 - <rls_span::OneIndexed as core::fmt::Debug>::fmt::hc2e3aeb3277dd105
  29:     0x7ff918ac18bf - <rls_span::OneIndexed as core::fmt::Debug>::fmt::hc2e3aeb3277dd105
  30:     0x7ff918afd454 - <rls_span::OneIndexed as core::fmt::Debug>::fmt::hc2e3aeb3277dd105
  31:     0x7ff918b39b9d - rustc_interface::passes::QueryContext::print_stats::h581fbf5f23b6b495
  32:     0x7ff918972c70 - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  33:     0x7ff918934eb7 - rustc_span::MultiSpan::primary_spans::h1017427bb4c1e209
  34:     0x7ff918945216 - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  35:     0x7ff9188da209 - <rustc_incremental::assert_dep_graph::GraphvizDepGraph as rustc_graphviz::GraphWalk>::source::ha7402f5059c5d3e9
  36:     0x7ff918972dfb - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  37:     0x7ff918941eaa - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  38:     0x7ff91891a6dc - rustc_span::MultiSpan::primary_spans::h1017427bb4c1e209
  39:     0x7ff91893d0b4 - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  40:     0x7ff918945d53 - <rustc_expand::mbe::macro_parser::MatcherPosHandle as core::ops::deref::DerefMut>::deref_mut::h5acc804ee7cddfed
  41:     0x7ff9188c8b53 - chalk_engine::TimeStamp::increment::h4493be1e979912d6
  42:     0x7ff922a70207 - std::sys::windows::thread::Thread::new::hb28370ce7bd0d890
  43:     0x7ff9af697034 - BaseThreadInitThunk
  44:     0x7ff9b159d0d1 - RtlUserThreadStart
```

</p>
</details>

### LINKED ISSUE #80767: Borrow Checker Paniced Upon Gifted Code
"Look Pal, it's either borrowed or taken.  No gifting or buying stuff here."

### Code

```Rust
type G<'a> = [(O, &'a [u8]); 64];
enum O {O1}
fn main() {let p: [G; 4]; let _g: G = [(O::O1, &[]); 64]; f(p);}
fn f(_p: [G; 4]) {}
```

### Meta

It reproduces on nightly and two other versions
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
RUST_BACKTRACE=1 cargo build
   Compiling edgesim v0.1.0 (/Users/tommy/projects/Rust/edgesim)
thread 'rustc' panicked at 'assertion failed: promoted.is_none()', compiler/rustc_mir/src/transform/check_consts/qualifs.rs:254:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustc_mir::transform::check_consts::qualifs::in_operand
   4: rustc_mir::transform::promote_consts::Validator::qualif_local
   5: rustc_mir::transform::promote_consts::Validator::validate_ref
   6: rustc_mir::transform::promote_consts::Validator::validate_local
   7: rustc_mir::transform::promote_consts::Validator::validate_local
   8: rustc_mir::transform::promote_consts::Validator::validate_local
   9: rustc_mir::transform::promote_consts::Validator::validate_local
  10: rustc_mir::transform::promote_consts::should_suggest_const_in_array_repeat_expressions_attribute
  11: rustc_mir::borrow_check::type_check::TypeChecker::check_rvalue
  12: rustc_mir::borrow_check::type_check::TypeChecker::typeck_mir
  13: rustc_mir::borrow_check::type_check::type_check
  14: rustc_mir::borrow_check::nll::compute_regions
  15: rustc_mir::borrow_check::do_mir_borrowck
  16: rustc_infer::infer::InferCtxtBuilder::enter
  17: rustc_mir::borrow_check::mir_borrowck
  18: core::ops::function::FnOnce::call_once
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  20: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  22: rustc_data_structures::stack::ensure_sufficient_stack
  23: rustc_query_system::query::plumbing::get_query_impl
  24: rustc_query_system::query::plumbing::ensure_query_impl
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
  26: rustc_interface::passes::analysis
  27: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  28: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  29: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  30: rustc_data_structures::stack::ensure_sufficient_stack
  31: rustc_query_system::query::plumbing::get_query_impl
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  33: rustc_span::with_source_map
  34: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (da305a2b0 2021-01-05) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #81315: thread 'rustc' panicked at 'assertion failed: promoted.is_none()', compiler/rustc_mir/src/transform/check_consts/qualifs.rs:250:9
Hi,

I detected this problem by coincidence and reporting it just because the error message asked to do so.

### Code

```Rust
struct A<'a> {
    data: &'a [u32],
}

impl<'a> A<'a> {
    const fn new(data: &'a [u32]) -> A<'a> {
        A { data }
    }
}

pub fn setup() {
    static mut aa_storage: [A; 32] = [A::new(&[]); 32];
}
```

The problem goes away if I add `#[derive(Clone, Copy)]` to `struct A`, as required for the array initialization inside `setup`.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (bb1fbbf84 2020-12-22)
binary: rustc
commit-hash: bb1fbbf84455fbad9afd26c17e0f725019322655
commit-date: 2020-12-22
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

I also verified that the problem exist after updating the toolchain in the version:

```
rustc 1.51.0-nightly (22ddcd1a1 2021-01-22)
binary: rustc
commit-hash: 22ddcd1a13082b7be0fc99b720677efd2b733816
commit-date: 2021-01-22
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: promoted.is_none()', compiler/rustc_mir/src/transform/check_consts/qualifs.rs:250:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (22ddcd1a1 2021-01-22) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type rlib

query stack during panic:
#0 [mir_borrowck] borrow-checking `setup::aa_storage`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: promoted.is_none()', compiler/rustc_mir/src/transform/check_consts/qualifs.rs:250:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/22ddcd1a13082b7be0fc99b720677efd2b733816/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/22ddcd1a13082b7be0fc99b720677efd2b733816/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/22ddcd1a13082b7be0fc99b720677efd2b733816/library/core/src/panicking.rs:50:5
   3: rustc_mir::transform::check_consts::qualifs::in_operand
   4: rustc_mir::transform::promote_consts::Validator::qualif_local
   5: rustc_mir::transform::promote_consts::Validator::validate_local
   6: rustc_mir::transform::promote_consts::Validator::validate_place
   7: rustc_mir::transform::promote_consts::Validator::validate_local
   8: rustc_mir::transform::promote_consts::Validator::validate_place
   9: rustc_mir::transform::promote_consts::Validator::validate_local
  10: rustc_mir::transform::promote_consts::Validator::validate_place
  11: rustc_mir::transform::promote_consts::Validator::validate_local
  12: rustc_mir::transform::promote_consts::Validator::validate_place
  13: rustc_mir::transform::promote_consts::should_suggest_const_in_array_repeat_expressions_attribute
  14: rustc_mir::borrow_check::type_check::TypeChecker::check_rvalue
  15: rustc_mir::borrow_check::type_check::TypeChecker::typeck_mir
  16: rustc_mir::borrow_check::type_check::type_check
  17: rustc_mir::borrow_check::nll::compute_regions
  18: rustc_mir::borrow_check::do_mir_borrowck
  19: rustc_infer::infer::InferCtxtBuilder::enter
  20: rustc_mir::borrow_check::mir_borrowck
  21: core::ops::function::FnOnce::call_once
  22: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  24: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
  25: rustc_query_system::query::plumbing::force_query_with_job
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_query_system::query::plumbing::ensure_query_impl
  28: rustc_session::utils::<impl rustc_session::session::Session>::time
  29: rustc_interface::passes::analysis
  30: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::force_query_with_job
  34: rustc_query_system::query::plumbing::get_query_impl
  35: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  36: rustc_span::with_source_map
  37: rustc_interface::interface::create_compiler_and_run
  38: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JulianKnodt**
Fixes #80371. Fixes #81315. Fixes #80767. Fixes #75682.

I thought there might be some issue with `Repeats(_, 0)`, but if you increase the items in the array it still ICEs. I'm not sure if this is the best fix but it does fix the given issue.

### CODE REVIEW

**Comment by lcnr** [comment]
this looks fine to me though I am kind of surprised that this error wasn't hit more frequently as borrowck uses `mir_promoted`. There seems to be another way to prevent borrowck from accessing promoteds or something I don't know about.

As I don't fully understand that I will leave the final review to someone else.

maybe r? @ecstatic-morse

**Comment by camelid** [comment]
I marked this PR as also fixing #81315, #80767, and #75682.

**Comment by tmiasko** [comment]
I also looked at this issue before noticing that it has PR opened already.

As far as I understand, when originally written this code was working only with MIR before promotion so assertion was always true. Subsequently the code was reused to check whether `const_in_array_repeat_expressions` feature would successfully promote the operand used in repeat expression and if so to provide that as a suggestion to fix a compilation error. In the latter case the code is running on a MIR after promotion and the assertion is no longer true.

My first impression regarding fixing it was to simply return false for promoteds, since they must have qualified already.

**Comment by oli-obk** [comment]
cc @RalfJung we could also just delete the `const_in_array_repeat_expressions` feature to fix this issue :laughing:

**Comment by RalfJung** [comment]
@oli-obk you mean together with [this problem](https://github.com/rust-lang/rust/issues/49147#issuecomment-766372999)? ;)

Fine for me. The assertion here could still be helpful to catch accidentally created nested promoteds.

**Comment by oli-obk** [comment]
> The assertion here could still be helpful to catch accidentally created nested promoteds.

yea, I don't want to remove the assertion, so let's go with removing `const_in_array_repeat_expressions`.

**Comment by JulianKnodt** [comment]
Should I change this PR or should I close this for someone else's implementation?

**Comment by oli-obk** [comment]
> Should I change this PR or should I close this for someone else's implementation?

If you have the time and motivation to do it, the job's all yours. Feel free to do it in this PR.

File: compiler/rustc_feature/src/active.rs [hunk 1]
```diff
@@ -485,9 +485,6 @@ declare_features! (
     /// Allows `async || body` closures.
     (active, async_closure, "1.37.0", Some(62290), None),
 
-    /// Allows `[x; N]` where `x` is a constant (RFC 2203).
-    (active, const_in_array_repeat_expressions, "1.37.0", Some(49147), None),
```
Comment (oli-obk) [inline compiler/rustc_feature/src/active.rs:489]: I think you need to put it into the https://github.com/rust-lang/rust/blob/e199123b4775efbe57f34c8765ba403a4d053b00/compiler/rustc_feature/src/removed.rs#L45 list of removed features

**Comment by oli-obk** [comment]
you need to move your new test into a test subfolder.

it's also very likey that you need to bless some tests and change or remove some tests that use the `const_in_array_repeat_expressions` feature gate

File: src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs [hunk 2]
```diff
@@ -1,7 +1,4 @@
-// run-pass
```
Comment (oli-obk) [inline src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs:1]: I think we should just delete this entire folder (or even better, rename it, and use `const { }` blocks everywhere, which should make all the run-pass tests work again and all the other test emit the same diagnostic that they were emitting with the feature.)

File: src/test/ui/unused/unused-closure.rs [hunk 3]
```diff
@@ -18,10 +17,6 @@ fn unused() {
 
     [Box::new([|| {}; 10]); 1]; //~ ERROR unused array of boxed arrays of closures that must be used
 
-    [|| { //~ ERROR unused array of generators that must be used
```
Comment (oli-obk) [inline src/test/ui/unused/unused-closure.rs:21]: you can put a `const {}` block around the expression, then it will work again.

File: src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs (hunk 2 above)
Comment (JulianKnodt) [reply src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs:1]: What's the feature for const-blocks? I can change it but I haven't been up to date with it

Comment (oli-obk) [reply src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs:1]: `inline_const` is the feature name

Comment (JulianKnodt) [reply src/test/ui/consts/rfc-2203-const-array-repeat-exprs/fn-call-in-const.rs:1]: Looking at it more closely, I think is the only file that is affected, but I've moved all of these into a folder under consts.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 4]
```diff
@@ -213,11 +213,6 @@ impl<'tcx> Visitor<'tcx> for Collector<'_, 'tcx> {
             Rvalue::Ref(..) => {
                 self.candidates.push(Candidate::Ref(location));
             }
-            Rvalue::Repeat(..) if self.ccx.tcx.features().const_in_array_repeat_expressions => {
-                // FIXME(#49147) only promote the element when it isn't `Copy`
-                // (so that code that can copy it at runtime is unaffected).
-                self.candidates.push(Candidate::Repeat(location));
```
Comment (RalfJung) [inline compiler/rustc_mir/src/transform/promote_consts.rs:219]: Can you entirely remove the `Candidate::Repeat` enum variant?

**Comment by RalfJung** [comment]
@bors r-
I left a comment

**Comment by RalfJung** [comment]
Thanks. :)
@bors r=oli-obk
