### PR TITLE
typeck: prohibit foreign statics w/ generics

### LINKED ISSUE #65025: type parameter `A/#0` (A/0) out of range when substituting (root type=Some(*const A)) substs=[]
Minimal example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=814876c654b0b3ad162d52ba64064b02

```
error: internal compiler error: src/librustc/ty/subst.rs:557: type parameter `A/#0` (A/0) out of range when substituting (root type=Some(*const A)) substs=[]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:579:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0 (625451e37 2019-09-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.
```

I'm on nightly but it also crashes on stable.

### LINKED ISSUE #65035: ICE: src/librustc_lint/types.rs:858: unexpected type in foreign function: T
```rust
fn _f<T>() {
    extern "C" {
        static _a: *const T;
    }
}
```

backtrace:
```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_lint/types.rs:858: unexpected type in foreign function: T

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_context_opt
  18: rustc::ty::context::tls::with_opt
  19: rustc::util::bug::opt_span_bug_fmt
  20: rustc::util::bug::bug_fmt
  21: rustc_lint::types::ImproperCTypesVisitor::check_type_for_ffi
  22: rustc_lint::types::ImproperCTypesVisitor::check_type_for_ffi
  23: rustc_lint::types::ImproperCTypesVisitor::check_type_for_ffi_and_report_errors
  24: <rustc_lint::types::ImproperCTypes as rustc::lint::LateLintPass>::check_foreign_item
  25: rustc::hir::intravisit::walk_item
  26: rustc::hir::intravisit::Visitor::visit_nested_item
  27: rustc::hir::intravisit::walk_block
  28: rustc::hir::intravisit::walk_body
  29: rustc::hir::intravisit::walk_fn
  30: rustc::hir::intravisit::walk_item
  31: rustc::hir::intravisit::Visitor::visit_nested_item
  32: rustc::lint::context::late_lint_mod
  33: rustc::ty::query::__query_compute::lint_mod
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::lint_mod>::compute
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  37: rustc::lint::context::check_crate::{{closure}}::{{closure}}
  38: rustc::util::common::time
  39: rustc::util::common::time
  40: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  43: rustc_interface::passes::analysis::{{closure}}
  44: rustc::util::common::time
  45: rustc_interface::passes::analysis
  46: rustc::ty::query::__query_compute::analysis
  47: rustc::dep_graph::graph::DepGraph::with_task_impl
  48: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  49: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  50: rustc_interface::passes::create_global_ctxt::{{closure}}
  51: rustc_interface::interface::run_compiler_in_existing_thread_pool
  52: std::thread::local::LocalKey<T>::with
  53: scoped_tls::ScopedKey<T>::set
  54: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (702b45e40 2019-10-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `playground`.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #65035 and fixes #65025.

This PR modifies resolve to disallow foreign statics that have
generics.

`improper_ctypes` is not written to support type parameters, as these
are normally disallowed before the lint is run. Thus, type parameters in
foreign statics must be prohibited before the lint.

The only other case where this *could* have occured is in functions,
but typeck prohibits this with a "foreign items may not have type
parameters" error - a similar error did not exist for statics, because
statics cannot have type parameters, but they can use any
type parameters that are in scope (which isn't the case for functions).

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -1622,8 +1622,37 @@ pub fn check_item_type<'tcx>(tcx: TyCtxt<'tcx>, it: &'tcx hir::Item) {
...
+                                }
+                            }
+
+                            let mut vis = HasTypeParameterVisitor { has_type_parameter: false };
+                            vis.visit_ty(ty);
+
+                            if vis.has_type_parameter {
+                                tcx.sess.span_err(
+                                    item.span,
+                                    "foreign statics can't use generic parameters",
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                    "foreign `static`s cannot use generic parameters",
```

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -1622,8 +1622,37 @@ pub fn check_item_type<'tcx>(tcx: TyCtxt<'tcx>, it: &'tcx hir::Item) {
...
+
+                            impl<'tcx> Visitor<'tcx> for HasTypeParameterVisitor {
+                                fn nested_visit_map<'this>(
+                                    &'this mut self,
+                                ) -> NestedVisitorMap<'this, 'tcx> {
+                                    NestedVisitorMap::None
+                                }
+
+                                fn visit_path(&mut self, path: &hir::Path, _: hir::HirId) {
+                                    if let Res::Def(DefKind::TyParam, _) = path.res {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Aside: I noticed that the following is allowed (no ICE, no error):
```rust
#![feature(const_generics)]

fn _f<const N: usize>() {
    extern "C" {
        static _a: [u8; N];
    }
}
```
cc @varkor

**Comment by Centril** [comment]
> statics cannot have type parameters, but they can use any
> type parameters that are in scope (which isn't the case for functions).

Odd... ISTM that `static` should not be able to reference type parameter from an other scope either and that the failure should happen in resolve.

cc @petrochenkov

**Comment by petrochenkov** [comment]
Yeah, this should be prevented by some barrier in resolve like `ItemRibKind` or something, at least for type parameters.

**Comment by davidtwco** [comment]
> 
> 
> Yeah, this should be prevented by some barrier in resolve like `ItemRibKind` or something, at least for type parameters.

I'll modify this PR to prohibit this in resolve instead.

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (varkor) [reply src/librustc_typeck/check/mod.rs]: @davidtwco: would it be possible to extend this to `HasNonLifetimeParameterVisitor` (or similar) and additionally check for `DefKind::ConstParam` (and add this test case)?

Comment (davidtwco) [reply src/librustc_typeck/check/mod.rs]: @varkor I [discussed this with Centril](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.2365133.20prohibit.20foreign.20statics/near/177478292) yesterday and decided that I'd aim to do this when I re-worked the PR to do this check for all statics in resolve.

**Comment by davidtwco** [comment]
@petrochenkov I've re-worked this PR to fix this in resolve instead. 

I've introduced a `StaticItemRibKind` but that was only so I could avoid the misleading diagnostic, the actual prohibition of generics from foreign statics worked with just an `ItemRibKind`, so if you have a alternative approach to improving that diagnostic, I'm happy to do that.

**Comment by petrochenkov** [comment]
>I've introduced a `StaticItemRibKind` but that was only so I could avoid the misleading diagnostic

I'd rather add a flag for this to `ItemRibKind`.

(`FnItemRibKind` is also very weird, all this stuff needs an audit (and the whole idea of conflating scopes with barriers is questionable), but that's for a different PR, I guess.)

File: src/librustc_resolve/late.rs [hunk 3]
```diff
@@ -48,6 +48,7 @@ struct BindingInfo {
 
 #[derive(Copy, Clone)]
 enum GenericParameters<'a, 'b> {
+    #[allow(dead_code)]
     NoGenericParams,
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_resolve/late.rs]: I've added a second commit which removes this enum now that there's only one variant that's used.

**Comment by davidtwco** [comment]
> I'd rather add a flag for this to `ItemRibKind`.

@petrochenkov I've updated the PR to add a flag to `ItemRibKind` instead of `StaticItemRibKind`.

File: src/librustc_resolve/late.rs [hunk 4]
```diff
@@ -841,91 +825,84 @@ impl<'a, 'b> LateResolutionVisitor<'a, '_> {
...
-                self.ribs[ValueNS].push(function_value_rib);
-                self.ribs[TypeNS].push(function_type_rib);
-            }
-
-            NoGenericParams => {
-                // Nothing to do.
             }
         }
 
+        self.ribs[ValueNS].push(function_value_rib);
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: Would be good to maintain the stack discipline here with:
```rust
         self.with_rib(ValueNS, function_value_rib, |this| {
             this.with_rib(TypeNS, function_type_rib, f);
         });
```

File: src/librustc_resolve/late.rs [hunk 5]
```diff
@@ -1041,9 +1018,8 @@ impl<'a, 'b> LateResolutionVisitor<'a, '_> {
                               impl_items: &[ImplItem]) {
         debug!("resolve_implementation");
         // If applicable, create a rib for the type parameters.
-        self.with_generic_param_rib(HasGenericParams(generics, ItemRibKind {
-            suggest_adding_parameter: true,
-        }), |this| {
+        self.with_generic_param_rib(generics, ItemRibKind { suggest_adding_parameter: true },
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: Consider moving `ItemRibKind { ... }` to a `let rib_kind` binding to make the `|this| {` look slightly less weird.

File: src/librustc_resolve/late.rs [hunk 6]
```diff
@@ -824,91 +825,84 @@ impl<'a, 'b> LateResolutionVisitor<'a, '_> {
...
+                        let err = ResolutionError::NameAlreadyUsedInParameterList(
+                            ident.name,
+                            *span,
+                        );
+                        self.r.report_error(param.ident.span, err);
                     }
+                    seen_bindings.entry(ident).or_insert(param.ident.span);
+
+                    let res = Res::Def(
+                        DefKind::ConstParam,
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: Aside from `DefKind::{TyParam, ConstParam}` these arms look identical... de-dup?

File: src/librustc_resolve/late.rs [hunk 7]
```diff
@@ -103,7 +92,11 @@ crate enum RibKind<'a> {
     FnItemRibKind,
 
     /// We passed through an item scope. Disallow upvars.
-    ItemRibKind,
+    ItemRibKind {
+        /// Should a "try adding a local generic parameter in this method instead" suggestion be
+        /// added to diagnostics?
+        suggest_adding_parameter: bool
```
Comment (petrochenkov) [inline src/librustc_resolve/late.rs]: Nit: can this use a tuple variant like
```rust
enum HasGenericParams { Yes, No }

ItemRibKind(HasGenericParams)
GenericParamsFromOuterFunction(Res, HasGenericParams),
```
I personally hate how ugly and noisy variants with curly braces look.
(Or just `bool` instead of the enum, it's private enough for a comment describing what it means to be good enough.)

Comment (davidtwco) [reply src/librustc_resolve/late.rs]: I've changed it to the suggested enum.

File: src/librustc_resolve/late.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_resolve/late.rs]: Fixed.

File: src/librustc_resolve/late.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_resolve/late.rs]: Fixed.

File: src/librustc_resolve/late.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_resolve/late.rs]: I haven't changed this because `with_rib` doesn't take a `Rib`, it takes a `RibKind`, and `function_{value,type}_rib` are `Rib`s, not `RibKind`s.

File: src/librustc_resolve/late.rs (hunk 7 above)
Comment (petrochenkov) [reply src/librustc_resolve/late.rs]: `ResolutionError::GenericParamsFromOuterFunction` is not changed.

Comment (davidtwco) [reply src/librustc_resolve/late.rs]: 🤦‍♂ Don't know how I managed that, fixed now.

File: src/librustc_resolve/late.rs (hunk 4 above)
Comment (Centril) [reply src/librustc_resolve/late.rs]: Oh right... 🤦‍♂  that's probably why I didn't change that bit of code in the first place.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
