### PR TITLE
export std::os::fd module on HermitOS

### LINKED ISSUE #126198: std::os::fd module missing on Hermit
I tried this code:

```rust
use std::os::fd::{AsFd, AsRawFd, BorrowedFd, FromRawFd, IntoRawFd, RawFd};
``` 

With `--target x86_64-unknown-hermit`.

I expected to see this happen: code to compile

Instead, this happened: failed to compile with

```
error[E0432]: unresolved import `std::os::fd`
   --> src/net/udp.rs:12:14
    |
12  | use std::os::fd::{AsFd, AsRawFd, BorrowedFd, FromRawFd, IntoRawFd, RawFd};
    |              ^^ could not find `fd` in `os`
```

Looking at the relevant code: https://github.com/rust-lang/rust/blob/212841e17cce13d1e29b00ad144300b687bfafdd/library/std/src/os/mod.rs#L163-L164

It seems `hermit` is imply missed from the `cfg`. Inside of the `fd` module there is already code for hermit: https://github.com/rust-lang/rust/blob/212841e17cce13d1e29b00ad144300b687bfafdd/library/std/src/os/fd/raw.rs#L18-L29

I think this is just an oversight, but I since I don't develop for Hermit I'm not sure. (I hit this while updating Mio)

/cc @stlankes

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (f21554f7f 2024-06-08)
binary: rustc
commit-hash: f21554f7f0ff447b803961c51acafde04553c1ed
commit-date: 2024-06-08
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by stlankes**
The HermitOS' IO interface is similiar to Unix. Consequently, this PR synchronize the FD implementation between both.

closes #126198

### CODE REVIEW

File: library/std/src/os/hermit/io/mod.rs [hunk 1]
```diff
@@ -1,13 +1,4 @@
...
-#[path = "../../fd/raw.rs"]
-mod raw;
-
-// Export the types and traits for the public API.
-#[stable(feature = "os_fd", since = "1.66.0")]
-pub use owned::*;
-#[stable(feature = "os_fd", since = "1.66.0")]
-pub use raw::*;
+#[stable(feature = "rust1", since = "1.0.0")]
+pub use crate::os::fd::*;
```
Comment (Thomasdezeeuw) [inline library/std/src/os/hermit/io/mod.rs:4]: I don't think this is right as `std::os::fd` only existings since 1.66.

Comment (Thomasdezeeuw) [reply library/std/src/os/hermit/io/mod.rs:4]: Actually never mind, this is `std::os::hermit`, so it's probably fine (?)

Comment (stlankes) [reply library/std/src/os/hermit/io/mod.rs:4]: I am not sure. I synchronized it with `std/src/os/unix/io/mod.rs`. But I don't know, if I used the correct version.
