### PR TITLE
syntax: recover trailing `|` in or-patterns

### LINKED ISSUE #64879: Detect match arm guard preceded by `|` in the parser
Detect and recover [the following incorrect code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=81fbc7b20fd10c78f5078956c0dcee50):

```rust
enum E {
    A,
    B,
}

fn main() {
    match E::A {
        E::A |
        E::B | // This pipe or operand shouldn't be here
        if true => {}
        _ => {}
    }
}
```

which currently emits

```
error: expected identifier, found keyword `if`
  --> src/main.rs:10:9
   |
10 |         if true => {}
   |         ^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
   |
10 |         r#if true => {}
   |         ^^^^

error: expected one of `=>`, `@`, `if`, or `|`, found `true`
  --> src/main.rs:10:12
   |
10 |         if true => {}
   |            ^^^^ expected one of `=>`, `@`, `if`, or `|` here
```

The parser should instead detect it is parsing a match arm guard.

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/64879.

For example (this also shows that we are sensitive to the typo `||`):

```
error: a trailing `|` is not allowed in an or-pattern
  --> $DIR/remove-leading-vert.rs:33:11
   |
LL |         A || => {}
   |         - ^^ help: remove the `||`
   |         |
   |         while parsing this or-pattern starting here
   |
   = note: alternatives in or-patterns are separated with `|`, not `||`
```

r? @estebank

### CODE REVIEW

File: src/libsyntax/parse/parser/pat.rs [hunk 1]
```diff
@@ -122,28 +125,64 @@ impl<'a> Parser<'a> {
...
+    /// is an illegal parse. However, the user's intent is less clear in that case.
+    fn recover_trailing_vert(&mut self, lo: Option<Span>) -> bool {
+        let is_end_ahead = self.look_ahead(1, |token| match &token.kind {
+            token::FatArrow // e.g. `a | => 0,`.
+            | token::Ident(kw::If, false) // e.g. `a | if expr`.
+            | token::Eq // e.g. `let a | = 0`.
+            | token::Semi // e.g. `let a |;`.
+            | token::Comma // e.g. `let (a |,)`.
+            | token::CloseDelim(token::Bracket) // e.g. `let [a | ]`.
+            | token::CloseDelim(token::Paren) // e.g. `let (a | )`.
```
Comment (estebank) [inline src/libsyntax/parse/parser/pat.rs]: This doesn't check for `A | B | if foo() => {}`, but I'm guessing this falls under the note above?

Comment (Centril) [reply src/libsyntax/parse/parser/pat.rs]:
```rust
             | token::Ident(kw::If, false) // e.g. `a | if expr`. 
```
does check for that (see regression test).

Comment (Centril) [reply src/libsyntax/parse/parser/pat.rs]: Oh I need to update the note above lol -- forgot to do that when I force-pushed last time.

Comment (Centril) [reply src/libsyntax/parse/parser/pat.rs]: (Done.)

**Comment by Centril** [comment]
Added `token::Colon` as well for type ascription and improved the test coverage.
