### PR TITLE
Fix ICE on recursively defined enum variant discriminant.

### LINKED ISSUE #23302: Infinite recursion for enum variant defined in terms of itself
```rust
enum X { A = X::A as isize }

fn main() {}
```
```
thread 'rustc' has overflowed its stack
Illegal instruction (core dumped)
```

### PR DESCRIPTION
**Pull request by quantheory**
Fixes #23302.

Note that there's an odd situation regarding the following, most likely due to some inadequacy in `const_eval`:

``` rust
enum Y {
    A = 1usize,
    B,
}
```

In this case, `Y::B as usize` might be considered a constant expression in some cases, but not others.  (See #23513, for a related problem where there is only one variant, with no discriminant, and it doesn't behave nicely as a constant expression either.)

Most of the complexity in this PR is basically future-proofing, to ensure that when `Y::B as usize` is fully made to be a constant expression, it can't be used to set `Y::A`, and thus indirectly itself.

### CODE REVIEW

**Comment by quantheory** [comment]
Two more things:

 1) I removed `E0266`, because it didn't look to me like it should be possible to trigger it, i.e. it should be `span_bug` and not `span_err!`.

 2) I guess that the broader issue of when an enum is a constant expression is now in #23898.

**Comment by huonw** [comment]
I... don't really know much about this.

r? @nrc (random selection from the compiler subteam)

File: src/test/compile-fail/issue-23302.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+enum X {
```
Comment (nrc) [inline src/test/compile-fail/issue-23302.rs]: Please add a comment explaining what is being tested

File: src/librustc/middle/check_static_recursion.rs [hunk 2]
```diff
@@ -13,68 +13,86 @@
...
-            ast::ItemStatic(_, _, ref expr) |
-            ast::ItemConst(_, ref expr) => {
+            ast::ItemStatic(..) |
+            ast::ItemConst(..) => {
                 let mut recursion_visitor =
                     CheckItemRecursionVisitor::new(self, &it.span);
                 recursion_visitor.visit_item(it);
-                visit::walk_expr(self, &*expr)
             },
-            _ => visit::walk_item(self, it)
```
Comment (nrc) [inline src/librustc/middle/check_static_recursion.rs]: Why is this change OK? It seems to me that if you have a const inside a function you'll miss it.

Comment (nrc) [inline src/librustc/middle/check_static_recursion.rs]: Oh nvm, it just moved outside the match

File: src/librustc/middle/check_static_recursion.rs [hunk 3]
```diff
@@ -85,23 +103,25 @@ struct CheckItemRecursionVisitor<'a, 'ast: 'a> {
     sess: &'a Session,
     ast_map: &'a ast_map::Map<'ast>,
     def_map: &'a DefMap,
-    idstack: Vec<ast::NodeId>
+    discriminant_map: &'a RefCell<NodeMap<Option<&'ast ast::Expr>>>,
```
Comment (nrc) [inline src/librustc/middle/check_static_recursion.rs]: comment please

**Comment by nrc** [comment]
r=me with a couple of comments added

**Comment by quantheory** [comment]
@nrc Is this better? (I commented the first `discriminant_map` definition, rather than the one you pointed out.)

**Comment by nrc** [comment]
yes, thanks!
