### PR TITLE
Fix suggestion for removing &mut from &mut macro!().

### LINKED ISSUE #85933: "consider removing the borrow" suggests to only remove `&` and not `mut`
In the following snippet, rustc suggests to remove just the `&` instead of removing the `&mut`, resulting in an invalid suggestion: `mut format!("")`.

```rust
fn main() {
    let _: String = &mut format!("");
}
```
```
error[E0308]: mismatched types
 --> src/main.rs:2:21
  |
2 |     let _: String = &mut format!("");
  |            ------   ^^^^^^^^^^^^^^^^
  |            |        |
  |            |        expected struct `String`, found `&mut String`
  |            |        help: consider removing the borrow: `mut format!("")`
  |            expected due to this
```

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #85933

Before: (Note the suggestions.)
```
error[E0308]: mismatched types
 --> src/main.rs:2:21
  |
2 |     let _: String = &mut format!("");
  |            ------   ^^^^^^^^^^^^^^^^
  |            |        |
  |            |        expected struct `String`, found `&mut String`
  |            |        help: consider removing the borrow: `mut format!("")`
  |            expected due to this

error[E0308]: mismatched types
 --> src/main.rs:3:21
  |
3 |     let _: String = &mut (format!(""));
  |            ------   ^^^^^^^^^^^^^^^^^^
  |            |        |
  |            |        expected struct `String`, found `&mut String`
  |            |        help: consider removing the borrow: `mut (format!(""))`
  |            expected due to this
```

After:
```
error[E0308]: mismatched types
 --> src/main.rs:2:21
  |
2 |     let _: String = &mut format!("");
  |            ------   ^^^^^^^^^^^^^^^^
  |            |        |
  |            |        expected struct `String`, found `&mut String`
  |            |        help: consider removing the borrow: `format!("")`
  |            expected due to this

error[E0308]: mismatched types
 --> src/main.rs:3:21
  |
3 |     let _: String = &mut (format!(""));
  |            ------   ^^^^^^^^^^^^^^^^^^
  |            |        |
  |            |        expected struct `String`, found `&mut String`
  |            |        help: consider removing the borrow: `format!("")`
  |            expected due to this
```

### CODE REVIEW

File: compiler/rustc_typeck/src/check/demand.rs [hunk 1]
```diff
@@ -577,12 +578,19 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 if sm.is_imported(expr.span) {
-                    if let Ok(src) = sm.span_to_snippet(sp) {
-                        if let Some(src) = src.strip_prefix('&') {
+                    // Go through the spans from which this span was expanded,
+                    // and find the one that's pointing inside `sp`.
+                    //
+                    // E.g. for `&format!("")`, where we want the span to the
+                    // `format!()` invocation instead of its expansion.
+                    if let Some(call_span) =
+                        iter::successors(Some(expr.span), |s| s.parent()).find(|&s| sp.contains(s))
```
Comment (m-ou-se) [inline compiler/rustc_typeck/src/check/demand.rs:587]: @estebank What do you think about adding as a function on `Span` (e.g. `span.find_parent_within(span)` or something)?

I have a feeling more diagnostics can/should use this, but I haven't written enough diagnostics yet to know if that's true.

File: compiler/rustc_typeck/src/check/demand.rs [hunk 2]
```diff
@@ -577,12 +578,19 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    {
+                        if let Ok(code) = sm.span_to_snippet(call_span) {
                             return Some((
                                 sp,
                                 "consider removing the borrow",
-                                src.to_string(),
+                                code,
```
Comment (m-ou-se) [inline compiler/rustc_typeck/src/check/demand.rs:593]: In another diagnostic, I emitted (potentially multiple) suggestions for removing the parts that need to be removed, instead of a single suggestion that contains a copy of (part of) the original source. Is there a guideline for which to prefer?

Basically:
A. "replace `&mut (format!(""))` by `format!("")`
B. "remove `&mut (` and remove `)`"

Most diagnostics seem to use A, which surprises me a bit. The suggestion for A can get quite large for large expressions.

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/demand.rs:587]: I agree with your assessment and we should have something like that (bikeshed notwithstanding).

File: compiler/rustc_typeck/src/check/demand.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/demand.rs:593]: The later didn't exist until "recently" (2019?), so there's a historical component. There's also a bug that needs to be fixed on rustc's side to allow rustfix apply multipart suggestions, which it can't today.

**Comment by m-ou-se** [comment]
> @bors r+, but feel free to change the suggestion to be multipart, if you so desire.

Might do that in another PR. :)

Hm, looks like bors didn't understand `r+,`

@bors r=estebank

File: compiler/rustc_typeck/src/check/demand.rs (hunk 2 above)
Comment (m-ou-se) [reply compiler/rustc_typeck/src/check/demand.rs:593]: Thanks!

> There's also a bug that needs to be fixed on rustc's side to allow rustfix apply multipart suggestions, which it can't today.

That should be fixed by https://github.com/rust-lang/rustfix/pull/195

Comment (estebank) [reply compiler/rustc_typeck/src/check/demand.rs:593]: Awesome! That should also allow us to add a `// run-rustfix` to a bunch of tests that don't have it today because of that 😄
