### PR TITLE
Don't include global asm in `mir_keys`, fix error body synthesis

### LINKED ISSUE #137470: ICE: `DefId(..) is not a body: GlobalAsm`
auto-reduced (treereduce-rust):
````rust
use std::arch::global_asm;

global_asm!("
.globl call_foobar
.type call_foobar,@function
.pushsection .text.call_foobar,\"ax\",@progbits
call_foobar: jmp {}
.size call_foobar, .-call_foobar
.popsection
", sym call_foobar);

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ build-pass
// Make sure rustc doesn't ICE on asm! for a foreign architecture.
//@ needs-asm-support
//@ only-x86_64
//@ only-linux

// regression test for #96797

use std::arch::global_asm;

#[no_mangle]
fn my_func() {}

global_asm!("
.globl call_foobar
.type call_foobar,@function
.pushsection .text.call_foobar,\"ax\",@progbits
call_foobar: jmp {}
.size call_foobar, .-call_foobar
.popsection
", sym call_foobar);

fn main() {
    unsafe {
        asm!("invalid_instruction");
        //~^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!("
            invalid_instruction
        ");
        //~^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(r#"
            invalid_instruction
        "#);
        //~^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!("
            mov eax, eax
            invalid_instruction
            mov eax, eax
        ");
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(r#"
            mov eax, eax
            invalid_instruction
            mov eax, eax
        "#);
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(concat!("invalid", "_", "instruction"));
        //~^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!("movaps %xmm3, (%esi, 2)", options(att_syntax));
        //~^ WARN: scale factor without index register is ignored

        asm!(
            "invalid_instruction",
        );
        //~^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(
            "mov eax, eax",
            "invalid_instruction",
            "mov eax, eax",
        );
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(
            "mov eax, eax\n",
            "invalid_instruction",
            "mov eax, eax",
        );
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(
            "mov eax, eax",
            concat!("invalid", "_", "instruction"),
            "mov eax, eax",
        );
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        asm!(
            concat!("mov eax", ", ", "eax"),
            concat!("invalid", "_", "instruction"),
            concat!("mov eax", ", ", "eax"),
        );
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction'

        // Make sure template strings get separated
        asm!(
            "invalid_instruction1",
            "invalid_instruction2",
        );
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction1'
        //~^^^ ERROR: invalid instruction mnemonic 'invalid_instruction2'

        asm!(
            concat!(
                "invalid", "_", "instruction1", "\n",
                "invalid", "_", "instruction2",
            ),
        );
        //~^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction1'
        //~^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction2'

        asm!(
            concat!(
                "invalid", "_", "instruction1", "\n",
                "invalid", "_", "instruction2",
            ),
            concat!(
                "invalid", "_", "instruction3", "\n",
                "invalid", "_", "instruction4",
            ),
        );
        //~^^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction1'
        //~^^^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction2'
        //~^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction3'
        //~^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction4'

        asm!(
            concat!(
                "invalid", "_", "instruction1", "\n",
                "invalid", "_", "instruction2", "\n",
            ),
            concat!(
                "invalid", "_", "instruction3", "\n",
                "invalid", "_", "instruction4", "\n",
            ),
        );
        //~^^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction1'
        //~^^^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction2'
        //~^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction3'
        //~^^^^^^^^ ERROR: invalid instruction mnemonic 'invalid_instruction4'

        asm!(
            "",
            "\n",
            "invalid_instruction"
        );
        //~^^ ERROR: invalid instruction mnemonic 'invalid_instruction'
    }
}

fn main() {
    extern "Rust" {
        fn call_foobar();
    }
    unsafe { call_foobar() };
}

````
</p>
</details>

Version information
````
rustc 1.87.0-nightly (bca5f37cb 2025-02-23)
binary: rustc
commit-hash: bca5f37cbded0db8d37414bb08c4b101a5f26d36
commit-date: 2025-02-23
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/bca5f37cbded0db8d37414bb08c4b101a5f26d36/compiler/rustc_mir_build/src/builder/mod.rs#L689-L701

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `call_foobar` in this scope
  --> /tmp/icemaker_global_tempdir.KHcxLMIG7czm/rustc_testrunner_tmpdir_reporting.2pIA33Z6GYlI/mvce.rs:10:8
   |
10 | ", sym call_foobar);
   |        ^^^^^^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.KHcxLMIG7czm/rustc_testrunner_tmpdir_reporting.2pIA33Z6GYlI/mvce.rs:10:21
   |
10 | ", sym call_foobar);
   |                     ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.KHcxLMIG7czm/rustc_testrunner_tmpdir_reporting.2pIA33Z6GYlI/mvce.rs`

error: internal compiler error: compiler/rustc_mir_build/src/builder/mod.rs:695:15: DefId(0:4 ~ mvce[6f8a]::{global_asm#0}) is not a body: GlobalAsm
  --> /tmp/icemaker_global_tempdir.KHcxLMIG7czm/rustc_testrunner_tmpdir_reporting.2pIA33Z6GYlI/mvce.rs:3:1
   |
3  | / global_asm!("
4  | | .globl call_foobar
5  | | .type call_foobar,@function
6  | | .pushsection .text.call_foobar,\"ax\",@progbits
...  |
9  | | .popsection
10 | | ", sym call_foobar);
   | |___________________^


thread 'rustc' panicked at compiler/rustc_mir_build/src/builder/mod.rs:695:15:
Box<dyn Any>
stack backtrace:
   0:     0x7622bb37d024 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb2766718346e8914
   1:     0x7622bba162ec - core::fmt::write::h9a1616cb06c0cb0c
   2:     0x7622bca69851 - std::io::Write::write_fmt::ha495c1f1db9a43ed
   3:     0x7622bb37ce82 - std::sys::backtrace::BacktraceLock::print::hfcfc21e91f78122e
   4:     0x7622bb37f68e - std::panicking::default_hook::{{closure}}::hdbc3741f9d3f7a84
   5:     0x7622bb37f264 - std::panicking::default_hook::hc24bc002e7741aa1
   6:     0x7622ba4de2d7 - std[aff040118bb958da]::panicking::update_hook::<alloc[67af6a9cecfd7ba8]::boxed::Box<rustc_driver_impl[301a9b8b79b48566]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7622bb37ff03 - std::panicking::rust_panic_with_hook::hcb6606e9e0388155
   8:     0x7622ba519bd1 - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}
   9:     0x7622ba50dfe6 - std[aff040118bb958da]::sys::backtrace::__rust_end_short_backtrace::<std[aff040118bb958da]::panicking::begin_panic<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}, !>
  10:     0x7622ba50dfcb - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>
  11:     0x7622ba5235d1 - <rustc_errors[ccf3a74766137fa5]::diagnostic::BugAbort as rustc_errors[ccf3a74766137fa5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7622baa736dc - <rustc_errors[ccf3a74766137fa5]::DiagCtxtHandle>::span_bug::<rustc_span[2a04d5a35653b919]::span_encoding::Span, alloc[67af6a9cecfd7ba8]::string::String>
  13:     0x7622baaf485a - rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt::<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}
  14:     0x7622baaddd2a - rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt::<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7622baaddb9b - rustc_middle[bff44984932adf4f]::ty::context::tls::with_context_opt::<rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7622b9326397 - rustc_middle[bff44984932adf4f]::util::bug::span_bug_fmt::<rustc_span[2a04d5a35653b919]::span_encoding::Span>
  17:     0x7622bab52bea - rustc_mir_build[5775ec9c077a699a]::builder::construct_error
  18:     0x7622bc3e4747 - rustc_mir_build[5775ec9c077a699a]::builder::build_mir
  19:     0x7622bba0656c - rustc_mir_transform[235952b1afe2fde9]::mir_built
  20:     0x7622bba06525 - rustc_query_impl[5384b6942a4aabb2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7622bbcfc4cc - rustc_query_system[5043f4129a32abe7]::query::plumbing::try_execute_query::<rustc_query_impl[5384b6942a4aabb2]::DynamicConfig<rustc_data_structures[27e03562bfbba71a]::vec_cache::VecCache<rustc_span[2a04d5a35653b919]::def_id::LocalDefId, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5043f4129a32abe7]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[5384b6942a4aabb2]::plumbing::QueryCtxt, false>
  22:     0x7622bbcfc08c - rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7622b94205a9 - rustc_mir_transform[235952b1afe2fde9]::mir_promoted
  24:     0x7622bbea6a12 - rustc_query_impl[5384b6942a4aabb2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 16usize]>>
  25:     0x7622bbea6ce2 - rustc_query_system[5043f4129a32abe7]::query::plumbing::try_execute_query::<rustc_query_impl[5384b6942a4aabb2]::DynamicConfig<rustc_data_structures[27e03562bfbba71a]::vec_cache::VecCache<rustc_span[2a04d5a35653b919]::def_id::LocalDefId, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[5043f4129a32abe7]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[5384b6942a4aabb2]::plumbing::QueryCtxt, false>
  26:     0x7622bbea691a - rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7622bcbb73ed - rustc_query_impl[5384b6942a4aabb2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7622bbcfc4cc - rustc_query_system[5043f4129a32abe7]::query::plumbing::try_execute_query::<rustc_query_impl[5384b6942a4aabb2]::DynamicConfig<rustc_data_structures[27e03562bfbba71a]::vec_cache::VecCache<rustc_span[2a04d5a35653b919]::def_id::LocalDefId, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5043f4129a32abe7]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[5384b6942a4aabb2]::plumbing::QueryCtxt, false>
  29:     0x7622bbcfbfcc - rustc_query_impl[5384b6942a4aabb2]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7622bbd8fcba - rustc_interface[a6a17d2a4de965ee]::passes::run_required_analyses
  31:     0x7622bca657fa - rustc_interface[a6a17d2a4de965ee]::passes::analysis
  32:     0x7622bca657d9 - rustc_query_impl[5384b6942a4aabb2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5384b6942a4aabb2]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 0usize]>>
  33:     0x7622bcac570b - rustc_query_system[5043f4129a32abe7]::query::plumbing::try_execute_query::<rustc_query_impl[5384b6942a4aabb2]::DynamicConfig<rustc_query_system[5043f4129a32abe7]::query::caches::SingleCache<rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[5384b6942a4aabb2]::plumbing::QueryCtxt, false>
  34:     0x7622bcac53f9 - rustc_query_impl[5384b6942a4aabb2]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7622bcb4e1bc - rustc_interface[a6a17d2a4de965ee]::passes::create_and_enter_global_ctxt::<core[25dd51937c36d244]::option::Option<rustc_interface[a6a17d2a4de965ee]::queries::Linker>, rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  36:     0x7622bcb41a60 - rustc_interface[a6a17d2a4de965ee]::interface::run_compiler::<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7622bc97eedc - std[aff040118bb958da]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  38:     0x7622bc97f300 - <<std[aff040118bb958da]::thread::Builder>::spawn_unchecked_<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[25dd51937c36d244]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7622bc97fceb - std::sys::pal::unix::thread::Thread::new::thread_start::h4bc285b173c402c8
  40:     0x7622b6ca370a - <unknown>
  41:     0x7622b6d27aac - <unknown>
  42:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (bca5f37cb 2025-02-23) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `{global_asm#0}`
#1 [mir_promoted] promoting constants in MIR for `{global_asm#0}`
#2 [mir_borrowck] borrow-checking `{global_asm#0}`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0425, E0601.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### LINKED ISSUE #137471: ICE: ` Unexpected def kind GlobalAsm`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --emit=mir
core::arch::global_asm!(
    r#"
    .global foo
    .global _foo
foo:
_foo:
    ret
"#
);

fn main() {}

#[cfg(not)]
fn main() {}

````

original:
````rust
//@ run-pass
//@ needs-asm-support

#![feature(naked_functions)]
#![allow(dead_code)]

#[cfg(any(target_arch = "x86_64", target_arch = "x86"))]
core::arch::global_asm!(
    r#"
    .global foo
    .global _foo
foo:
_foo:
    ret
"#
);

extern "C" {
    fn foo();
}

#[cfg(any(target_arch = "x86_64", target_arch = "x86"))]
fn main() {
    unsafe {
        foo();
    }
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "x86")))]
fn main() {}

````

This worked before https://github.com/rust-lang/rust/pull/137180 

Version information
````
rustc 1.87.0-nightly (bca5f37cb 2025-02-23)
binary: rustc
commit-hash: bca5f37cbded0db8d37414bb08c4b101a5f26d36
commit-date: 2025-02-23
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/bca5f37cbded0db8d37414bb08c4b101a5f26d36/compiler/rustc_middle/src/mir/pretty.rs#L650-L662

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --emit=mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/mir/pretty.rs:656:14: Unexpected def kind GlobalAsm


thread 'rustc' panicked at compiler/rustc_middle/src/mir/pretty.rs:656:14:
Box<dyn Any>
stack backtrace:
   0:     0x72dabd57d024 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb2766718346e8914
   1:     0x72dabdc162ec - core::fmt::write::h9a1616cb06c0cb0c
   2:     0x72dabec69851 - std::io::Write::write_fmt::ha495c1f1db9a43ed
   3:     0x72dabd57ce82 - std::sys::backtrace::BacktraceLock::print::hfcfc21e91f78122e
   4:     0x72dabd57f68e - std::panicking::default_hook::{{closure}}::hdbc3741f9d3f7a84
   5:     0x72dabd57f264 - std::panicking::default_hook::hc24bc002e7741aa1
   6:     0x72dabc6de2d7 - std[aff040118bb958da]::panicking::update_hook::<alloc[67af6a9cecfd7ba8]::boxed::Box<rustc_driver_impl[301a9b8b79b48566]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x72dabd57ff03 - std::panicking::rust_panic_with_hook::hcb6606e9e0388155
   8:     0x72dabc719bd1 - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}
   9:     0x72dabc70dfe6 - std[aff040118bb958da]::sys::backtrace::__rust_end_short_backtrace::<std[aff040118bb958da]::panicking::begin_panic<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}, !>
  10:     0x72dabc70dfcb - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>
  11:     0x72dabc7235d1 - <rustc_errors[ccf3a74766137fa5]::diagnostic::BugAbort as rustc_errors[ccf3a74766137fa5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x72dabccf4846 - rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt::<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}
  13:     0x72dabccddd2a - rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt::<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x72dabccddb9b - rustc_middle[bff44984932adf4f]::ty::context::tls::with_context_opt::<rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x72dabb0f9e20 - rustc_middle[bff44984932adf4f]::util::bug::bug_fmt
  16:     0x72dabccb5fc5 - rustc_middle[bff44984932adf4f]::mir::pretty::write_mir_intro
  17:     0x72dabccb1ace - rustc_middle[bff44984932adf4f]::mir::pretty::write_mir_pretty::{closure#0}
  18:     0x72dabccb0668 - rustc_middle[bff44984932adf4f]::mir::pretty::write_mir_pretty
  19:     0x72dabce9783c - rustc_mir_transform[235952b1afe2fde9]::dump_mir::emit_mir
  20:     0x72dabeabae05 - <rustc_interface[a6a17d2a4de965ee]::queries::Linker>::codegen_and_build_linker
  21:     0x72dabed4e1ef - rustc_interface[a6a17d2a4de965ee]::passes::create_and_enter_global_ctxt::<core[25dd51937c36d244]::option::Option<rustc_interface[a6a17d2a4de965ee]::queries::Linker>, rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  22:     0x72dabed41a60 - rustc_interface[a6a17d2a4de965ee]::interface::run_compiler::<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}
  23:     0x72dabeb7eedc - std[aff040118bb958da]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  24:     0x72dabeb7f300 - <<std[aff040118bb958da]::thread::Builder>::spawn_unchecked_<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[25dd51937c36d244]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x72dabeb7fceb - std::sys::pal::unix::thread::Thread::new::thread_start::h4bc285b173c402c8
  26:     0x72dab8ea370a - <unknown>
  27:     0x72dab8f27aac - <unknown>
  28:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (bca5f37cb 2025-02-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
end of query stack
error: aborting due to 1 previous error


```

</p>
</details>

@rustbot label +F-naked_functions

### LINKED ISSUE #137472: ICE: `symbol_names: unexpected DefPathData: GlobalAsm`
### Code

```Rust
//@compile-flags: -C instrument-coverage
fn foo<const N: usize>() {}

core::arch::global_asm!("/* {} */", sym foo::<{
    || {};
    0
}>);

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (bca5f37cb 2025-02-23)
binary: rustc
commit-hash: bca5f37cbded0db8d37414bb08c4b101a5f26d36
commit-date: 2025-02-23
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused closure that must be used
 --> a.rs:4:5
  |
4 |     || {};
  |     ^^^^^
  |
  = note: closures are lazy and do nothing unless called
  = note: `#[warn(unused_must_use)]` on by default

error: internal compiler error: compiler/rustc_symbol_mangling/src/v0.rs:814:17: symbol_names: unexpected DefPathData: GlobalAsm


thread 'rustc' panicked at compiler/rustc_symbol_mangling/src/v0.rs:814:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f505f17d024 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb2766718346e8914
   1:     0x7f505f8162ec - core::fmt::write::h9a1616cb06c0cb0c
   2:     0x7f5060869851 - std::io::Write::write_fmt::ha495c1f1db9a43ed
   3:     0x7f505f17ce82 - std::sys::backtrace::BacktraceLock::print::hfcfc21e91f78122e
   4:     0x7f505f17f68e - std::panicking::default_hook::{{closure}}::hdbc3741f9d3f7a84
   5:     0x7f505f17f264 - std::panicking::default_hook::hc24bc002e7741aa1
   6:     0x7f505e2de2d7 - std[aff040118bb958da]::panicking::update_hook::<alloc[67af6a9cecfd7ba8]::boxed::Box<rustc_driver_impl[301a9b8b79b48566]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f505f17ff03 - std::panicking::rust_panic_with_hook::hcb6606e9e0388155
   8:     0x7f505e319bd1 - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}
   9:     0x7f505e30dfe6 - std[aff040118bb958da]::sys::backtrace::__rust_end_short_backtrace::<std[aff040118bb958da]::panicking::begin_panic<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}, !>
  10:     0x7f505e30dfcb - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>
  11:     0x7f505e3235d1 - <rustc_errors[ccf3a74766137fa5]::diagnostic::BugAbort as rustc_errors[ccf3a74766137fa5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f505e8f4846 - rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt::<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}
  13:     0x7f505e8ddd2a - rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt::<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7f505e8ddb9b - rustc_middle[bff44984932adf4f]::ty::context::tls::with_context_opt::<rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7f505ccf9e20 - rustc_middle[bff44984932adf4f]::util::bug::bug_fmt
  16:     0x7f505ee352de - <rustc_symbol_mangling[4df9e5f33cffabe4]::v0::SymbolMangler as rustc_middle[bff44984932adf4f]::ty::print::Printer>::print_def_path
  17:     0x7f505ee35193 - <rustc_symbol_mangling[4df9e5f33cffabe4]::v0::SymbolMangler as rustc_middle[bff44984932adf4f]::ty::print::Printer>::print_def_path
  18:     0x7f505ee35193 - <rustc_symbol_mangling[4df9e5f33cffabe4]::v0::SymbolMangler as rustc_middle[bff44984932adf4f]::ty::print::Printer>::print_def_path
  19:     0x7f505ee3461c - rustc_symbol_mangling[4df9e5f33cffabe4]::v0::mangle
  20:     0x7f505ffca8c9 - rustc_symbol_mangling[4df9e5f33cffabe4]::symbol_name_provider
  21:     0x7f505ffc93ea - rustc_query_impl[5384b6942a4aabb2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5384b6942a4aabb2]::query_impl::symbol_name::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 16usize]>>
  22:     0x7f505ffc83c1 - rustc_query_system[5043f4129a32abe7]::query::plumbing::try_execute_query::<rustc_query_impl[5384b6942a4aabb2]::DynamicConfig<rustc_query_system[5043f4129a32abe7]::query::caches::DefaultCache<rustc_middle[bff44984932adf4f]::ty::instance::Instance, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[5384b6942a4aabb2]::plumbing::QueryCtxt, false>
  23:     0x7f505ffc801e - rustc_query_impl[5384b6942a4aabb2]::query_impl::symbol_name::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7f506067e784 - rustc_middle[bff44984932adf4f]::query::plumbing::query_get_at::<rustc_query_system[5043f4129a32abe7]::query::caches::DefaultCache<rustc_middle[bff44984932adf4f]::ty::instance::Instance, rustc_middle[bff44984932adf4f]::query::erase::Erased<[u8; 16usize]>>>
  25:     0x7f505e166dcf - rustc_codegen_llvm[c101bf8584bfcdb2]::coverageinfo::mapgen::covfun::prepare_covfun_record
  26:     0x7f5060726995 - rustc_codegen_llvm[c101bf8584bfcdb2]::base::compile_codegen_unit::module_codegen
  27:     0x7f50608eb750 - <rustc_codegen_llvm[c101bf8584bfcdb2]::LlvmCodegenBackend as rustc_codegen_ssa[9aaafa5d25c08f19]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  28:     0x7f50608e7951 - <rustc_codegen_llvm[c101bf8584bfcdb2]::LlvmCodegenBackend as rustc_codegen_ssa[9aaafa5d25c08f19]::traits::backend::CodegenBackend>::codegen_crate
  29:     0x7f50606ba9db - <rustc_interface[a6a17d2a4de965ee]::queries::Linker>::codegen_and_build_linker
  30:     0x7f506094e1ef - rustc_interface[a6a17d2a4de965ee]::passes::create_and_enter_global_ctxt::<core[25dd51937c36d244]::option::Option<rustc_interface[a6a17d2a4de965ee]::queries::Linker>, rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  31:     0x7f5060941a60 - rustc_interface[a6a17d2a4de965ee]::interface::run_compiler::<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}
  32:     0x7f506077eedc - std[aff040118bb958da]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  33:     0x7f506077f300 - <<std[aff040118bb958da]::thread::Builder>::spawn_unchecked_<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[25dd51937c36d244]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7f506077fceb - std::sys::pal::unix::thread::Thread::new::thread_start::h4bc285b173c402c8
  35:     0x7f505aaa370a - <unknown>
  36:     0x7f505ab27aac - <unknown>
  37:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im2/rustc-ice-2025-02-23T09_43_35-2986648.txt` to your bug report

note: compiler flags: -C instrument-coverage

query stack during panic:
#0 [symbol_name] computing the symbol for `{global_asm#0}::{constant#0}::{closure#0}`
end of query stack
error: aborting due to 1 previous error; 1 warning emitted
```

</p>
</details>

### LINKED ISSUE #137473: ICE: cfi: encode_ty_name: unexpected `GlobalAsm`
### Code

```Rust
//@compile-flags: -Zsanitizer=cfi -Ccodegen-units=1 -Clto -Clink-dead-code=true`
fn foo<const N: usize>() {}

core::arch::global_asm!("/* {} */", sym foo::<{
    || {};
    0
}>);

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (bca5f37cb 2025-02-23)
binary: rustc
commit-hash: bca5f37cbded0db8d37414bb08c4b101a5f26d36
commit-date: 2025-02-23
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused closure that must be used
 --> a.rs:4:5
  |
4 |     || {};
  |     ^^^^^
  |
  = note: closures are lazy and do nothing unless called
  = note: `#[warn(unused_must_use)]` on by default

error: internal compiler error: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:724:17: encode_ty_name: unexpected `GlobalAsm`


thread 'rustc' panicked at compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:724:17:
Box<dyn Any>
stack backtrace:
   0:     0x7df5c657d024 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb2766718346e8914
   1:     0x7df5c6c162ec - core::fmt::write::h9a1616cb06c0cb0c
   2:     0x7df5c7c69851 - std::io::Write::write_fmt::ha495c1f1db9a43ed
   3:     0x7df5c657ce82 - std::sys::backtrace::BacktraceLock::print::hfcfc21e91f78122e
   4:     0x7df5c657f68e - std::panicking::default_hook::{{closure}}::hdbc3741f9d3f7a84
   5:     0x7df5c657f264 - std::panicking::default_hook::hc24bc002e7741aa1
   6:     0x7df5c56de2d7 - std[aff040118bb958da]::panicking::update_hook::<alloc[67af6a9cecfd7ba8]::boxed::Box<rustc_driver_impl[301a9b8b79b48566]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7df5c657ff03 - std::panicking::rust_panic_with_hook::hcb6606e9e0388155
   8:     0x7df5c5719bd1 - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}
   9:     0x7df5c570dfe6 - std[aff040118bb958da]::sys::backtrace::__rust_end_short_backtrace::<std[aff040118bb958da]::panicking::begin_panic<rustc_errors[ccf3a74766137fa5]::ExplicitBug>::{closure#0}, !>
  10:     0x7df5c570dfcb - std[aff040118bb958da]::panicking::begin_panic::<rustc_errors[ccf3a74766137fa5]::ExplicitBug>
  11:     0x7df5c57235d1 - <rustc_errors[ccf3a74766137fa5]::diagnostic::BugAbort as rustc_errors[ccf3a74766137fa5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7df5c5cf4846 - rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt::<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}
  13:     0x7df5c5cddd2a - rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt::<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7df5c5cddb9b - rustc_middle[bff44984932adf4f]::ty::context::tls::with_context_opt::<rustc_middle[bff44984932adf4f]::ty::context::tls::with_opt<rustc_middle[bff44984932adf4f]::util::bug::opt_span_bug_fmt<rustc_span[2a04d5a35653b919]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7df5c40f9e20 - rustc_middle[bff44984932adf4f]::util::bug::bug_fmt
  16:     0x7df5c61a4a35 - rustc_sanitizers[13117c02c2809417]::cfi::typeid::itanium_cxx_abi::encode::encode_ty_name
  17:     0x7df5c61a5f9b - rustc_sanitizers[13117c02c2809417]::cfi::typeid::itanium_cxx_abi::encode::encode_ty
  18:     0x7df5c61a7204 - rustc_sanitizers[13117c02c2809417]::cfi::typeid::itanium_cxx_abi::encode::encode_ty
  19:     0x7df5c61a90df - rustc_sanitizers[13117c02c2809417]::cfi::typeid::itanium_cxx_abi::typeid_for_fnabi
  20:     0x7df5c61aa1e9 - rustc_sanitizers[13117c02c2809417]::cfi::typeid::itanium_cxx_abi::typeid_for_instance
  21:     0x7df5c7b2346f - <rustc_codegen_llvm[c101bf8584bfcdb2]::context::CodegenCx as rustc_codegen_ssa[9aaafa5d25c08f19]::traits::declare::PreDefineCodegenMethods>::predefine_fn
  22:     0x7df5c7b25193 - rustc_codegen_llvm[c101bf8584bfcdb2]::base::compile_codegen_unit::module_codegen
  23:     0x7df5c7ceb750 - <rustc_codegen_llvm[c101bf8584bfcdb2]::LlvmCodegenBackend as rustc_codegen_ssa[9aaafa5d25c08f19]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  24:     0x7df5c7ce7951 - <rustc_codegen_llvm[c101bf8584bfcdb2]::LlvmCodegenBackend as rustc_codegen_ssa[9aaafa5d25c08f19]::traits::backend::CodegenBackend>::codegen_crate
  25:     0x7df5c7aba9db - <rustc_interface[a6a17d2a4de965ee]::queries::Linker>::codegen_and_build_linker
  26:     0x7df5c7d4e1ef - rustc_interface[a6a17d2a4de965ee]::passes::create_and_enter_global_ctxt::<core[25dd51937c36d244]::option::Option<rustc_interface[a6a17d2a4de965ee]::queries::Linker>, rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  27:     0x7df5c7d41a60 - rustc_interface[a6a17d2a4de965ee]::interface::run_compiler::<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}
  28:     0x7df5c7b7eedc - std[aff040118bb958da]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  29:     0x7df5c7b7f300 - <<std[aff040118bb958da]::thread::Builder>::spawn_unchecked_<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_with_globals<rustc_interface[a6a17d2a4de965ee]::util::run_in_thread_pool_with_globals<rustc_interface[a6a17d2a4de965ee]::interface::run_compiler<(), rustc_driver_impl[301a9b8b79b48566]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[25dd51937c36d244]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7df5c7b7fceb - std::sys::pal::unix::thread::Thread::new::thread_start::h4bc285b173c402c8
  31:     0x7df5c1e9e70a - <unknown>
  32:     0x7df5c1f22aac - <unknown>
  33:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im2/rustc-ice-2025-02-23T09_54_57-2988209.txt` to your bug report

note: compiler flags: -Z sanitizer=cfi -C codegen-units=1 -C lto -C link-dead-code=true

query stack during panic:
end of query stack
error: aborting due to 1 previous error; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
r? oli-obk

Fixes #137470
Fixes #137471
Fixes #137472
Fixes #137473

try-job: test-various
try-job: x86_64-apple-2

### CODE REVIEW

File: compiler/rustc_mir_transform/src/lib.rs [hunk 1]
```diff
@@ -316,6 +316,9 @@ fn mir_keys(tcx: TyCtxt<'_>, (): ()) -> FxIndexSet<LocalDefId> {
     // All body-owners have MIR associated with them.
     let mut set: FxIndexSet<_> = tcx.hir_body_owners().collect();
 
+    // Remove the fake bodies for `global_asm!`, since they're useful to be emitted or encoded.
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/lib.rs:319]:
```suggestion
    // Remove the fake bodies for `global_asm!`, since they're not useful to be emitted or encoded.
```

**Review by oli-obk — APPROVED** [review]

**Comment by fmease** [comment]
`tests/ui/asm/global-asm-isnt-really-a-mir-body.rs#instrument` failed on **aarch64-apple** in rollup #137649 with:

```
---- [ui] tests/ui/asm/global-asm-isnt-really-a-mir-body.rs#instrument stdout ----
error in revision `instrument`: test compilation failed although it shouldn't!
status: exit status: 1
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/Users/runner/work/rust/rust/build/aarch64-apple-darwin/stage2/bin/rustc" "/Users/runner/work/rust/rust/tests/ui/asm/global-asm-isnt-really-a-mir-body.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/Users/runner/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/Users/runner/work/rust/rust/vendor" "--sysroot" "/Users/runner/work/rust/rust/build/aarch64-apple-darwin/stage2" "--target=aarch64-apple-darwin" "--cfg" "instrument" "--check-cfg" "cfg(test,FALSE,emit_mir,instrument,cfi)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/Users/runner/work/rust/rust/build/aarch64-apple-darwin/test/ui/asm/global-asm-isnt-really-a-mir-body.instrument" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/Users/runner/work/rust/rust/build/aarch64-apple-darwin/native/rust-test-helpers" "-Cinstrument-coverage" "-Zno-profiler-runtime"
--- stderr -------------------------------
error: linking with `cc` failed: exit status: 1
   |
   |
   = note:  "cc" "/var/folders/2s/h6hvv9ps03xgz_krkkstvq_r0000gn/T/rustchOsAJj/symbols.o" "<1 object files omitted>" "<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/libstd-d16fc3ab99251824.dylib" "<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/{libcompiler_builtins-*}.rlib" "-lSystem" "-lc" "-lm" "-arch" "arm64" "-mmacosx-version-min=11.0.0" "-L" "/Users/runner/work/rust/rust/build/aarch64-apple-darwin/native/rust-test-helpers" "-o" "/Users/runner/work/rust/rust/build/aarch64-apple-darwin/test/ui/asm/global-asm-isnt-really-a-mir-body.instrument/global-asm-isnt-really-a-mir-body" "-Wl,-dead_strip" "-nodefaultlibs" "-Wl,-rpath,@loader_path/../../../../stage2/lib/rustlib/aarch64-apple-darwin/lib"
   = note: Undefined symbols for architecture arm64:
   = note: Undefined symbols for architecture arm64:
             "___llvm_profile_raw_version", referenced from:
           ld: symbol(s) not found for architecture arm64
           ld: symbol(s) not found for architecture arm64
           clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to 1 previous error
------------------------------------------
```

https://github.com/rust-lang/rust/pull/137649#issuecomment-2683776560

@bors r-

**Comment by workingjubilee** [comment]
@bors r-

see https://github.com/rust-lang/rust/pull/138030#issuecomment-2700037072

run against test-various if you want to know what's wrong

File: tests/ui/asm/global-asm-isnt-really-a-mir-body.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+//@[instrument] only-linux
+
+// Make sure we don't try to CFI encode it.
+//@[cfi] compile-flags: -Zsanitizer=cfi -Ccodegen-units=1 -Clto -Clink-dead-code=true
+//@[cfi] needs-sanitizer-cfi
+//@[cfi] no-prefer-dynamic
+
+//@ build-pass
+
+use std::arch::global_asm;
```
Comment (workingjubilee) [inline tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:17]: this isn't stable for all architectures :upside_down_face:

Comment (compiler-errors) [reply tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:17]: hm, id there a needs-global-asm 🤔

Comment (compiler-errors) [reply tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:17]: or maybe needs-asm

Comment (workingjubilee) [reply tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:17]: I... thiiink so?

Comment (workingjubilee) [reply tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:17]: needs-asm-support

File: tests/ui/asm/global-asm-isnt-really-a-mir-body.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+// Make sure we don't try to instrument it.
+//@[instrument] compile-flags: -Cinstrument-coverage -Zno-profiler-runtime
+//@[instrument] only-linux
+
+// Make sure we don't try to CFI encode it.
+//@[cfi] compile-flags: -Zsanitizer=cfi -Ccodegen-units=1 -Clto -Clink-dead-code=true
+//@[cfi] needs-sanitizer-cfi
+//@[cfi] no-prefer-dynamic
+
+//@ build-pass
```
Comment (compiler-errors) [inline tests/ui/asm/global-asm-isnt-really-a-mir-body.rs:15]:
```suggestion
//@ build-pass
//@ needs-asm-support
```

**Comment by compiler-errors** [comment]
testing before i sleep, will squash when i wake up

@bors try

**Comment by workingjubilee** [comment]
network errors lol

**Comment by compiler-errors** [comment]
yay

@bors r=oli-obk

**Comment by compiler-errors** [comment]
Poorly written test is matching a hash ending with "f" lmao
