### PR TITLE
Parser will not suggest invalid expression when use public

### LINKED ISSUE #100165: Suggest invalid expression when use `public`
When writing `public let some = 3;` it will suggest `pub let some = 3;` and I think nothing should be suggested before it is validated.
> Note: 
The statement to be suggested must be checked if it is true or not, if true it is suggested and if not it is not.

The issue from: https://github.com/rust-lang/rust/pull/99903

[Given the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021):

```rust
fn main() {
    public let some = 3;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found keyword `let`
 --> src/main.rs:2:12
  |
2 |     public let some = 3;
  |            ^^^ expected one of 8 possible tokens
  |
help: write `pub` instead of `public` to make the item public
  |
2 |     pub let some = 3;
  |     ~~~

error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found keyword `let`
 --> src/main.rs:2:12
  |
2 |     public let some = 3;
  |            ^^^ expected one of 8 possible tokens

error: could not compile `playground` due to previous error
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #100165

### CODE REVIEW

File: compiler/rustc_ast/src/token.rs [hunk 1]
```diff
@@ -452,6 +452,8 @@ impl Token {
             || self.is_keyword(kw::Enum)
             || self.is_keyword(kw::Struct)
             || self.is_keyword(kw::Union)
+            || self.is_keyword(kw::Macro)
+            || self.is_keyword(kw::MacroRules)
```
Comment (gimbles) [inline compiler/rustc_ast/src/token.rs:456]: MacroRules shouldn't be here.

**Review by ghost — CHANGES_REQUESTED** [review]

File: compiler/rustc_ast/src/token.rs [hunk 2]
```diff
@@ -454,6 +454,7 @@ impl Token {
             || self.is_keyword(kw::Union)
             || self.is_keyword(kw::Macro)
             || self.is_keyword(kw::MacroRules)
+            || self == &OpenDelim(Delimiter::Parenthesis)
```
Comment (gimbles) [inline compiler/rustc_ast/src/token.rs:457]: What..exactly is this for?

File: compiler/rustc_ast/src/token.rs (hunk 1 above)
Comment (gimbles) [reply compiler/rustc_ast/src/token.rs:456]: [Just noticed, this probably shouldn't be a "Suggested changes", haha.]

**Comment by gimbles** [comment]
@chenyukang Remember to squash your commits 👏🏻

File: compiler/rustc_ast/src/token.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_ast/src/token.rs:457]: I was reading, found out there is a this kind of scenario:

```rust
 // This function is visible to the entire crate
        pub(crate) fn crate_visible_fn() {}

        // This function is visible within `outer_mod`
        pub(super) fn super_mod_visible_fn() {
            // This function is visible since we're in the same `mod`
            inner_mod_visible_fn();
        }

```

```rust
OpenDelim(Delimiter::Parenthesis)
```
is used for expecting an '(', I tested it.

https://doc.rust-lang.org/reference/visibility-and-privacy.html?highlight=pub#visibility-and-privacy

File: compiler/rustc_ast/src/token.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_ast/src/token.rs:456]: yes, should remove MacroRules.

**Comment by chenyukang** [comment]
> @chenyukang Remember to squash your commits 👏🏻
thanks for remind, done!

File: compiler/rustc_ast/src/token.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_ast/src/token.rs:456]: do you think we need to support this case? 
I just don't know `pub` could be used for so many kind of items and scenarios...😊

Comment (gimbles) [reply compiler/rustc_ast/src/token.rs:456]: Ohh, this is fine, then.

**Comment by estebank** [comment]
You'll have to rebase on top of a more recent version of the repo before we can merge.

**Comment by chenyukang** [comment]
ooo, seems pushed some extra changes, let me fix it.

**Comment by chenyukang** [comment]
> Some changes occurred in src/tools/cargo
> 
> cc @ehuss
> 
> The Miri submodule was changed
> 
> cc @rust-lang/miri

Please ignore it.
