### PR TITLE
rustdoc: treat query string `+` as space

### LINKED ISSUE #119219: `rustdoc` search with space giving "Unexpected +" error
`+` in a URL means space, just like `%20`. When I paste something with a space in my browser search box (like, e.g., a trailing space; not the omnibar; in Firefox), and search on doc.rust-lang.org, `test+` can be seen in the search box on the page, along with the error 'Query parser error: "Unexpected `+`".' The address bar shows [`https://doc.rust-lang.org/std/?search=test%2B`](https://doc.rust-lang.org/std/?search=test%2B) (literal `+` is U+002B).

When I manually visit [`https://doc.rust-lang.org/std/?search=test+`](https://doc.rust-lang.org/std/?search=test+), a redirect to [`https://doc.rust-lang.org/std/?search=test%2B`](https://doc.rust-lang.org/std/?search=test%2B) can briefly be seen happening in the address bar (same in Brave browser), whereas manually visiting [`https://www.google.com/search?q=foo+bar+`](https://www.google.com/search?q=foo+bar+) works as expected.

The same problem happens on other pages using `rustdoc`, like [`https://microsoft.github.io/windows-docs-rs/doc/windows/`](https://microsoft.github.io/windows-docs-rs/doc/windows/).

`+` should be treated as space - as usual - but it seems something related to `rustdoc` is erroneously treating it as a literal `+`.

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #119219

### CODE REVIEW

File: src/librustdoc/html/static/js/main.js [hunk 1]
```diff
@@ -279,7 +279,8 @@ function preLoadCss(cssUrl) {
             const params = {};
             window.location.search.substring(1).split("&").
                 map(s => {
-                    const pair = s.split("=");
+                    // https://github.com/rust-lang/rust/issues/119219
+                    const pair = s.split("=").map(x => x.replace(/\+/g, " "));
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/main.js:283]: Thanks to this, I discovered that it was okay to use `+` to replace a space in a query parameter but not in the path. So weird.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup
