### PR TITLE
Abort if check nightly options failed on stable

### LINKED ISSUE #115680: stable rustdoc accepts unstable nightly flags
`~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustdoc implied-bounds-unconstrained-2.rs "--document-private-items" "--document-hidden-items"  -Zunstable-options --edition=2021`

will print a bunch of errors but still generate docs it seems.

````
error: the option `document-hidden-items` is only accepted on the nightly compiler

note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

help: consider switching to a nightly toolchain: `rustup default nightly`

note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

error: the option `Z` is only accepted on the nightly compiler

note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

help: consider switching to a nightly toolchain: `rustup default nightly`

note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>
````

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #115680
Also, if there are multiple unstable options passing on stable compiler, printing multiple same `note` and `help` seems noisy.

### CODE REVIEW

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -2979,20 +2980,27 @@ pub mod nightly_options {
...
                 OptionStability::Stable => {}
             }
         }
+        if nightly_options_on_stable > 0 {
+            handler
+                .early_help("consider switching to a nightly toolchain: `rustup default nightly`");
+            handler.early_note("selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>");
+            handler.early_note("for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>");
+            handler.early_error(format!(
+                "{} nightly option{} passing to stable compiler",
```
Comment (compiler-errors) [inline compiler/rustc_session/src/config.rs:2999]: this isn't necessarily a stable compiler (might be beta)

```suggestion
                "{} nightly option{} were parsed",
```

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me with nit
