### PR TITLE
Elaborate trait obligations when typechecking impls

### LINKED ISSUE #43784: Supertrait loops are (still) unsound
First reported in https://users.rust-lang.org/t/unexpected-behaviors-of-trait-bounds/12286/3

## STR

```Rust
pub trait Partial: Copy {
}

pub trait Complete: Partial {
}

impl<T> Partial for T where T: Complete {}
impl<T> Complete for T {}

fn copy<P: Partial>(p: P) -> (P, P) {
    (p, p)
}

fn main() {
    let (p, q) = copy("hello".to_string());
    drop(p);
    println!("{}", q);
}
```

cc @nikomatsakis - let's discuss this when you are back from vacation (unless @aturon can come up with a solution?)

### PR DESCRIPTION
**Pull request by scalexm**
When typechecking trait impl declarations, we only checked that bounds explictly written on the trait declaration hold.

We now also check that bounds which would have been implied by the trait reference do hold.

Fixes #43784.

### CODE REVIEW

File: src/librustc/ty/wf.rs [hunk 1]
```diff
@@ -156,7 +175,7 @@ impl<'a, 'gcx, 'tcx> WfPredicates<'a, 'gcx, 'tcx> {
         // WF and (b) the trait-ref holds.  (It may also be
         // normalizable and be WF that way.)
         let trait_ref = data.trait_ref(self.infcx.tcx);
-        self.compute_trait_ref(&trait_ref);
+        self.compute_trait_ref(&trait_ref, Elaborate::All);
```
Comment (scalexm) [inline src/librustc/ty/wf.rs]: I guess we could just have `Elaborate::None` here, since the implied obligations are proved once and for all when typechecking the impl declaration.

**Comment by carols10cents** [comment]
friendly ping @aturon !

**Review by nikomatsakis — APPROVED** [review]
OK, I finally got over jet lag enough to understand https://github.com/rust-lang/rust/issues/43784 and to see why this will fix the problem. My one complaint with this PR, really, is that what is happening here is non-obvious. I'd like to see a comment on the `Elaborate` enum that links to https://github.com/rust-lang/rust/issues/43784 and explains the purpose of this enum.

**Comment by scalexm** [comment]
Ok, will do that soon.

**Comment by nikomatsakis** [comment]
@scalexm just did it =) maybe check over what I wrote and see if you agree

File: src/librustc/ty/wf.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc/ty/wf.rs]: Presumably .. yes ..? Should we change this then?

**Comment by nikomatsakis** [comment]
(I wanted to write out the argument to see if I really understood it ;)

File: src/librustc/ty/wf.rs (hunk 1 above)
Comment (scalexm) [inline src/librustc/ty/wf.rs]: Yes we should change this (I'll let you do that :) )

**Comment by scalexm** [comment]
Yes I think it's good :)

**Comment by nikomatsakis** [comment]
@scalexm should we change this do you think ? https://github.com/rust-lang/rust/pull/43786#discussion_r134891508

**Comment by scalexm** [comment]
@nikomatsakis yes I think [we should](https://github.com/rust-lang/rust/pull/43786#discussion_r134892011) change to `Elaborate::None`.

**Comment by nikomatsakis** [comment]
@scalexm ok, care to push a change? want me to do it?
