### PR TITLE
asm: Add a kreg0 register class on x86 which includes k0

### LINKED ISSUE #94977: Inline asm docs incorrectly state that k0 (x86 AVX-512) is hard-wired to zero
https://doc.rust-lang.org/nightly/reference/inline-assembly.html#register-names
says about  `k0`  "*This is a constant zero register which can't be modified.*"
That's the same phrasing as AArch64 `xzr`, so I assume the author thought it was architecturally hard-wired, rather than a software choice to keep it zeroed (like often done with AVR `r0`).  (Which I don't think would make much sense; most instructions with an all-zero mask are no-ops so you don't normally want one.)

`k0` is special in that it can't be used *as a mask*, because that register number means no-masking if used in an instruction like `vmovaps (%rdi), %xmm0{%k1}{z}`.  But it *can* be the destination of instructions like compare-into-mask or [`vptestmd %ymm0, %ymm0, %k0`](https://www.felixcloutier.com/x86/vptestmb:vptestmw:vptestmd:vptestmq), and then stored to memory or copied to a GP-integer reg with `kmovd %k0, %eax`, tested with `kortest`, combine with other masks with `kunpck` or `kadd` or whatever.

Leaving it unused prevents false dependencies when materializing an all-ones mask with `kxnord %k0, %k0, %k1` (e.g. before a gather), but otherwise there's no reason to avoid it if your uses for that mask don't include applying masking to other instructions.

You do definitely want there to be a constraint that can only pick k1..7, not k0, like GNU C inline asm's `Yk` (https://stackoverflow.com/questions/55946103/gnu-c-inline-asm-input-constraint-for-avx512-mask-registers-k1-k7), but there's no reason to disallow `k0` as an explicit choice.  If people don't want to know about details like k0 being special, they can use intrinsics.

Probably not much reason to invent a constraint like `Yk` but which can pick k0..7, though, but it's possible it could help register allocation of mask regs with surrounding code.  (But would be more documentation to wade through, and could end up wasting some people's time if they find the constraint which can pick k0 when they need one which can't.)

### PR DESCRIPTION
**Pull request by Amanieu**
Previously we only exposed a kreg register class which excludes the k0
register since it can't be used in many instructions. However k0 is a
valid register and we need to have a way of marking it as clobbered for
clobber_abi.

Fixes #94977

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
This looks correct to me but I'd like someone more familiar with this space to double check. 

r? @nagisa perhaps?

File: src/test/ui/asm/x86_64/bad-reg.rs [hunk 1]
```diff
@@ -29,8 +29,6 @@ fn main() {
         //~^ ERROR invalid register `rsp`: the stack pointer cannot be used as an operand
         asm!("", in("ip") foo);
         //~^ ERROR invalid register `ip`: the instruction pointer cannot be used as an operand
-        asm!("", in("k0") foo);
```
Comment (nagisa) [inline src/test/ui/asm/x86_64/bad-reg.rs:32]: Why is this being removed? It is still invalid to use `k0` as an input/output operand, right?

File: compiler/rustc_target/src/asm/x86.rs [hunk 2]
```diff
@@ -294,13 +295,14 @@ def_regs! {
...
-        k6: kreg = ["k6"],
-        k7: kreg = ["k7"],
+        k0: kreg0 = ["k0"],
+        k1: kreg, kreg0 = ["k1"],
+        k2: kreg, kreg0 = ["k2"],
+        k3: kreg, kreg0 = ["k3"],
+        k4: kreg, kreg0 = ["k4"],
+        k5: kreg, kreg0 = ["k5"],
+        k6: kreg, kreg0 = ["k6"],
+        k7: kreg, kreg0 = ["k7"],
```
Comment (nagisa) [inline compiler/rustc_target/src/asm/x86.rs:305]: I find the `kreg0` register group name quite surprising. Intuitively I expected this register class to include just the `k0` register, rather than being `kreg + k0`. In retrospective it makes sense, but I felt there was definitely a surprise factor of sorts. I wonder if there is a name which would have an obvious interpretation.

As a side note, preexisting, and probably half my fault, but isn't the naming of this group inconsistent with the other groups? We can't fix this now, can we?

Comment (Amanieu) [reply compiler/rustc_target/src/asm/x86.rs:305]: I don't have a better ideas for the register class name.

I don't think the naming is too inconsistent. `kreg` is what you usually want most of the time.

File: src/test/ui/asm/x86_64/bad-reg.rs (hunk 1 above)
Comment (Amanieu) [reply src/test/ui/asm/x86_64/bad-reg.rs:32]: No, it's now valid. I previously incorrectly thought `k0` wasn't a real register, like `xzr` on AArch64.

Comment (nagisa) [reply src/test/ui/asm/x86_64/bad-reg.rs:32]: I think in that case the description should be updated

> However k0 is a valid register and we need to have a way of marking it as clobbered for clobber_abi.

somewhat misleadingly led me to believe that `k0` was only being exposed for use as a clobber.

File: compiler/rustc_target/src/asm/x86.rs (hunk 2 above)
Comment (nagisa) [reply compiler/rustc_target/src/asm/x86.rs:305]: > I don't have a better ideas for the register class name.

Hmm… `kreg_full` or `kreg_all`, perhaps?

> I don't think the naming is too inconsistent. kreg is what you usually want most of the time.

Ah, I meant in relation to other classes like `abcd_reg`, `xmm_reg`, `ymm_reg` et al. If the convention of separating `reg` from types of register, `kreg` would be `k_reg`. Nothing we can do here anymore, though.

Comment (workingjubilee) [reply compiler/rustc_target/src/asm/x86.rs:305]: The rule is consistent but idiosyncratic: kreg, vreg, preg, then xmm_reg, x87_reg, etc.
Like
```rust
if class.len() <= 1 {
    format!("{class}reg")
else {
    format!("{class}_reg")
}
```

**Comment by Amanieu** [comment]
I think I'll just go with the most forward-compatible approach which is just to let `k0` be a clobber-only register for now.

**Comment by nagisa** [comment]
@bors r+

I guess the takeaway here I have is that we probably want a mechanism to feature-gate specific register classes so that we could introduce additional ones for stable inline-asm implementations without making them insta-stable too.
