### PR TITLE
Replace OffsetOf by an actual sum of calls to intrinsic.

### LINKED ISSUE #123959: generic_const_exprs and offset_of don't bode well
### Code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b3db1ea811f639fa4db8135f2b6bd338))

```rust
#![feature(generic_const_exprs)]
fn foo<T>(_: [(); std::mem::offset_of!((T,), 0)]) {}
```

Produces ICE:

<details>

```
error: internal compiler error: Missing value for constant, but no error reported?
 --> src/lib.rs:2:19
  |
2 | fn foo<T>(_: [(); std::mem::offset_of!((T,), 0)]) {}
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: delayed at compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:74:68
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxt>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: rustc_trait_selection::traits::const_evaluatable::is_const_evaluatable.cold
         4: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
         5: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
         6: <rustc_trait_selection::traits::engine::ObligationCtxt>::assumed_wf_types
         7: rustc_hir_analysis::check::wfcheck::check_item_fn
         8: rustc_hir_analysis::check::wfcheck::check_well_formed
         9: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_hir::hir_id::OwnerId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        11: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
        12: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        13: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_hir_analysis::check_crate
        17: rustc_interface::passes::analysis
        18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        20: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        21: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
        22: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        23: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#2} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/alloc/src/boxed.rs:2018:9
        25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/alloc/src/boxed.rs:2018:9
        26: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/0d8b3346a3992ab11ea35ff0fb95a6864b91f797/library/std/src/sys/pal/unix/thread.rs:108:17
        27: start_thread
        28: clone
 --> src/lib.rs:2:19
  |
2 | fn foo<T>(_: [(); std::mem::offset_of!((T,), 0)]) {}
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: this error: internal compiler error originates in the macro `std::mem::offset_of` (in Nightly builds, run with -Z macro-backtrace for more info)
```

</details>

Similar looking code [also ICEs on stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d8f12ce73159848a6c195ad5d34f4a7) with different error message and feature enabled:

```rust
#![feature(generic_const_exprs)]

struct Foo<T, const N: usize = { std::mem::size_of::<T>() }>(T) where [(); std::mem::size_of::<T>()]:;

struct Bar<T> {
    foo: Foo<T>,
}
```

### LINKED ISSUE #129425: ICE: `errors selecting obligation during MIR typeck: [TrueError]`
snippet:
````rust
#![feature(generic_const_exprs)]
fn foo<'a, T: 'a>(_: [(); std::mem::offset_of!((T,), 0)]) {}


````

Version information
````
rustc 1.82.0-nightly (5ad98b402 2024-08-22)
binary: rustc
commit-hash: 5ad98b4026d5172f27615b105658bc8bfd677be8
commit-date: 2024-08-22
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.tDpCHeI4R4t9/rustc_testrunner_tmpdir_reporting.Lo4fDYzUFauY/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `foo` is never used
 --> /tmp/icemaker_global_tempdir.tDpCHeI4R4t9/rustc_testrunner_tmpdir_reporting.Lo4fDYzUFauY/mvce.rs:2:4
  |
2 | fn foo<'a, T: 'a>(_: [(); std::mem::offset_of!((T,), 0)]) {}
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: Missing value for constant, but no error reported?
 --> /tmp/icemaker_global_tempdir.tDpCHeI4R4t9/rustc_testrunner_tmpdir_reporting.Lo4fDYzUFauY/mvce.rs:2:27
  |
2 | fn foo<'a, T: 'a>(_: [(); std::mem::offset_of!((T,), 0)]) {}
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: delayed at compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:74:68 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.tDpCHeI4R4t9/rustc_testrunner_tmpdir_reporting.Lo4fDYzUFauY/mvce.rs:2:27
  |
2 | fn foo<'a, T: 'a>(_: [(); std::mem::offset_of!((T,), 0)]) {}
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: this error: internal compiler error originates in the macro `std::mem::offset_of` (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: errors selecting obligation during MIR typeck: [TrueError]
  |
  = note: delayed at /rustc/5ad98b4026d5172f27615b105658bc8bfd677be8/compiler/rustc_trait_selection/src/traits/query/type_op/custom.rs:94:18 - disabled backtrace

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (5ad98b402 2024-08-22) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### LINKED ISSUE #136175: ICE: `offset of not-statically-aligned field .. cannot be computed statically`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024
#![feature(generic_const_exprs)]

use core::fmt::Debug;

struct Inline<T>
where
    [(); std::mem::offset_of!((T,), 0)]:,
{
    let foo: (),
    
}

fn main() {
    let dst = Inline::<dyn Debug>::new(0); // BANG!
}

````

original:
````rust
#![feature(generic_const_exprs)]

use core::fmt::Debug;

struct Inline<T>
where
    [(); std::mem::offset_of!((T,), 0)]:,
{
    let foo: (),
    //~^  ERROR expected identifier, found keyword `let`
}

fn main() {
    let dst = Inline::<dyn Debug>::new(0); // BANG!
}

````

Version information
````
rustc 1.86.0-nightly (2f348cb7c 2025-01-27)
binary: rustc
commit-hash: 2f348cb7ce4063fa4eb40038e6ada3c5214717bd
commit-date: 2025-01-27
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected identifier, found keyword `let`
 --> /tmp/icemaker_global_tempdir.ss1hYVHGdMgO/rustc_testrunner_tmpdir_reporting.pEd6k8w10N6f/mvce.rs:9:5
  |
9 |     let foo: (),
  |     ^^^-
  |     |
  |     expected identifier, found keyword
  |     help: remove this `let` keyword
  |
  = note: the `let` keyword is not allowed in `struct` fields
  = note: see <https://doc.rust-lang.org/book/ch05-01-defining-structs.html> for more information

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.ss1hYVHGdMgO/rustc_testrunner_tmpdir_reporting.pEd6k8w10N6f/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0392]: type parameter `T` is never used
 --> /tmp/icemaker_global_tempdir.ss1hYVHGdMgO/rustc_testrunner_tmpdir_reporting.pEd6k8w10N6f/mvce.rs:5:15
  |
5 | struct Inline<T>
  |               ^ unused type parameter
  |
  = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`
  = help: if you intended `T` to be a const parameter, use `const T: /* Type */` instead

error[E0599]: no function or associated item named `new` found for struct `Inline` in the current scope
  --> /tmp/icemaker_global_tempdir.ss1hYVHGdMgO/rustc_testrunner_tmpdir_reporting.pEd6k8w10N6f/mvce.rs:14:36
   |
5  | struct Inline<T>
   | ---------------- function or associated item `new` not found for this struct
...
14 |     let dst = Inline::<dyn Debug>::new(0); // BANG!
   |                                    ^^^ function or associated item not found in `Inline<dyn Debug>`

error: internal compiler error: /rustc/2f348cb7ce4063fa4eb40038e6ada3c5214717bd/compiler/rustc_middle/src/ty/layout.rs:1397:21: offset of not-statically-aligned field (type dyn [Binder { value: Trait(std::fmt::Debug), bound_vars: [] }] + '{erased}) cannot be computed statically


thread 'rustc' panicked at /rustc/2f348cb7ce4063fa4eb40038e6ada3c5214717bd/compiler/rustc_middle/src/ty/layout.rs:1397:21:
Box<dyn Any>
stack backtrace:
   0:     0x7e903a3aae40 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he98e11da2daa96a9
   1:     0x7e903ac14ee6 - core::fmt::write::had177877e89931fb
   2:     0x7e903bb50b51 - std::io::Write::write_fmt::hc355e6fef9c0a3ce
   3:     0x7e903a3aaca2 - std::sys::backtrace::BacktraceLock::print::h676c1f81be95e0b1
   4:     0x7e903a3ad122 - std::panicking::default_hook::{{closure}}::hd28d3669866dc126
   5:     0x7e903a3acfaa - std::panicking::default_hook::h039746809c2c5ae1
   6:     0x7e903955ff39 - std[644fad426ed526f7]::panicking::update_hook::<alloc[5097d557d6b96634]::boxed::Box<rustc_driver_impl[438371d8e84705cb]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7e903a3adc63 - std::panicking::rust_panic_with_hook::h88108df39d1d1441
   8:     0x7e903959b421 - std[644fad426ed526f7]::panicking::begin_panic::<rustc_errors[d6afe1f3c80315c7]::ExplicitBug>::{closure#0}
   9:     0x7e9039590326 - std[644fad426ed526f7]::sys::backtrace::__rust_end_short_backtrace::<std[644fad426ed526f7]::panicking::begin_panic<rustc_errors[d6afe1f3c80315c7]::ExplicitBug>::{closure#0}, !>
  10:     0x7e903958d05d - std[644fad426ed526f7]::panicking::begin_panic::<rustc_errors[d6afe1f3c80315c7]::ExplicitBug>
  11:     0x7e90395a5351 - <rustc_errors[d6afe1f3c80315c7]::diagnostic::BugAbort as rustc_errors[d6afe1f3c80315c7]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7e9039b867f3 - rustc_middle[dfbbc45bb841e134]::util::bug::opt_span_bug_fmt::<rustc_span[45d362c5296a3b7f]::span_encoding::Span>::{closure#0}
  13:     0x7e9039b6f7aa - rustc_middle[dfbbc45bb841e134]::ty::context::tls::with_opt::<rustc_middle[dfbbc45bb841e134]::util::bug::opt_span_bug_fmt<rustc_span[45d362c5296a3b7f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7e9039b6f63b - rustc_middle[dfbbc45bb841e134]::ty::context::tls::with_context_opt::<rustc_middle[dfbbc45bb841e134]::ty::context::tls::with_opt<rustc_middle[dfbbc45bb841e134]::util::bug::opt_span_bug_fmt<rustc_span[45d362c5296a3b7f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7e9037de19a0 - rustc_middle[dfbbc45bb841e134]::util::bug::bug_fmt
  16:     0x7e903b7a4bb5 - <rustc_const_eval[4c73f18587537670]::interpret::eval_context::InterpCx<rustc_const_eval[4c73f18587537670]::const_eval::machine::CompileTimeMachine>>::eval_rvalue_into_place
  17:     0x7e90385dce39 - rustc_const_eval[4c73f18587537670]::const_eval::eval_queries::eval_to_allocation_raw_provider
  18:     0x7e903b412e9c - rustc_query_impl[9923fb681be542d6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9923fb681be542d6]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 24usize]>>
  19:     0x7e903b41283a - rustc_query_system[ea81b1814f2bc579]::query::plumbing::try_execute_query::<rustc_query_impl[9923fb681be542d6]::DynamicConfig<rustc_query_system[ea81b1814f2bc579]::query::caches::DefaultCache<rustc_middle[dfbbc45bb841e134]::ty::PseudoCanonicalInput<rustc_middle[dfbbc45bb841e134]::mir::interpret::GlobalId>, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9923fb681be542d6]::plumbing::QueryCtxt, false>
  20:     0x7e903b4124bb - rustc_query_impl[9923fb681be542d6]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7e903b419d65 - rustc_const_eval[4c73f18587537670]::const_eval::valtrees::eval_to_valtree
  22:     0x7e903b419b1c - <rustc_const_eval[4c73f18587537670]::provide::{closure#0} as core[d2a938784d8f7dcb]::ops::function::FnOnce<(rustc_middle[dfbbc45bb841e134]::ty::context::TyCtxt, rustc_middle[dfbbc45bb841e134]::ty::PseudoCanonicalInput<rustc_middle[dfbbc45bb841e134]::mir::interpret::GlobalId>)>>::call_once
  23:     0x7e903b419ac6 - rustc_query_impl[9923fb681be542d6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9923fb681be542d6]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 24usize]>>
  24:     0x7e903b419a7f - <rustc_query_impl[9923fb681be542d6]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[d2a938784d8f7dcb]::ops::function::FnOnce<(rustc_middle[dfbbc45bb841e134]::ty::context::TyCtxt, rustc_middle[dfbbc45bb841e134]::ty::PseudoCanonicalInput<rustc_middle[dfbbc45bb841e134]::mir::interpret::GlobalId>)>>::call_once
  25:     0x7e903b412913 - rustc_query_system[ea81b1814f2bc579]::query::plumbing::try_execute_query::<rustc_query_impl[9923fb681be542d6]::DynamicConfig<rustc_query_system[ea81b1814f2bc579]::query::caches::DefaultCache<rustc_middle[dfbbc45bb841e134]::ty::PseudoCanonicalInput<rustc_middle[dfbbc45bb841e134]::mir::interpret::GlobalId>, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9923fb681be542d6]::plumbing::QueryCtxt, false>
  26:     0x7e903b41222d - rustc_query_impl[9923fb681be542d6]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7e903b7d390c - rustc_middle[dfbbc45bb841e134]::query::plumbing::query_get_at::<rustc_query_system[ea81b1814f2bc579]::query::caches::DefaultCache<rustc_middle[dfbbc45bb841e134]::ty::PseudoCanonicalInput<rustc_middle[dfbbc45bb841e134]::mir::interpret::GlobalId>, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 24usize]>>>
  28:     0x7e903b7d2f22 - <rustc_middle[dfbbc45bb841e134]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  29:     0x7e903b7d2db9 - <rustc_middle[dfbbc45bb841e134]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  30:     0x7e903b7d2af7 - rustc_trait_selection[a0c4a4c304b8efe3]::traits::try_evaluate_const
  31:     0x7e903c894ef8 - rustc_trait_selection[a0c4a4c304b8efe3]::traits::const_evaluatable::is_const_evaluatable.cold
  32:     0x7e903b4ee30f - <rustc_trait_selection[a0c4a4c304b8efe3]::traits::fulfill::FulfillProcessor as rustc_data_structures[702a32bac37c74a0]::obligation_forest::ObligationProcessor>::process_obligation
  33:     0x7e903ac10642 - <rustc_data_structures[702a32bac37c74a0]::obligation_forest::ObligationForest<rustc_trait_selection[a0c4a4c304b8efe3]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[a0c4a4c304b8efe3]::traits::fulfill::FulfillProcessor>
  34:     0x7e903ad69f6a - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::try_structurally_resolve_type
  35:     0x7e903b9899fd - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  36:     0x7e903ad7b371 - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::confirm_builtin_call
  37:     0x7e903b98b526 - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x7e903b9885e7 - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::check_decl
  39:     0x7e903b9856cd - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::check_expr_block
  40:     0x7e903b98c03e - <rustc_hir_typeck[711cb0c541d6273d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  41:     0x7e903b240d00 - rustc_hir_typeck[711cb0c541d6273d]::check::check_fn
  42:     0x7e903b249b7d - rustc_hir_typeck[711cb0c541d6273d]::typeck_with_inspect::{closure#0}
  43:     0x7e903b247b8c - rustc_query_impl[9923fb681be542d6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9923fb681be542d6]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 8usize]>>
  44:     0x7e903af996ce - rustc_query_system[ea81b1814f2bc579]::query::plumbing::try_execute_query::<rustc_query_impl[9923fb681be542d6]::DynamicConfig<rustc_data_structures[702a32bac37c74a0]::vec_cache::VecCache<rustc_span[45d362c5296a3b7f]::def_id::LocalDefId, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[ea81b1814f2bc579]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[9923fb681be542d6]::plumbing::QueryCtxt, false>
  45:     0x7e903af97bd1 - rustc_query_impl[9923fb681be542d6]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7e903af9788b - <rustc_middle[dfbbc45bb841e134]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[679b9e311f2f4bbc]::check_crate::{closure#4}>::{closure#0}
  47:     0x7e903af9593f - rustc_hir_analysis[679b9e311f2f4bbc]::check_crate
  48:     0x7e903af91f62 - rustc_interface[68fc4f7f4eaa26cf]::passes::run_required_analyses
  49:     0x7e903bb4c25e - rustc_interface[68fc4f7f4eaa26cf]::passes::analysis
  50:     0x7e903bb4c22f - rustc_query_impl[9923fb681be542d6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9923fb681be542d6]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 0usize]>>
  51:     0x7e903bb29855 - rustc_query_system[ea81b1814f2bc579]::query::plumbing::try_execute_query::<rustc_query_impl[9923fb681be542d6]::DynamicConfig<rustc_query_system[ea81b1814f2bc579]::query::caches::SingleCache<rustc_middle[dfbbc45bb841e134]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[9923fb681be542d6]::plumbing::QueryCtxt, false>
  52:     0x7e903bb2958e - rustc_query_impl[9923fb681be542d6]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  53:     0x7e903bb65169 - rustc_interface[68fc4f7f4eaa26cf]::passes::create_and_enter_global_ctxt::<core[d2a938784d8f7dcb]::option::Option<rustc_interface[68fc4f7f4eaa26cf]::queries::Linker>, rustc_driver_impl[438371d8e84705cb]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  54:     0x7e903bba250a - rustc_interface[68fc4f7f4eaa26cf]::interface::run_compiler::<(), rustc_driver_impl[438371d8e84705cb]::run_compiler::{closure#0}>::{closure#1}
  55:     0x7e903ba8a875 - std[644fad426ed526f7]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[68fc4f7f4eaa26cf]::util::run_in_thread_with_globals<rustc_interface[68fc4f7f4eaa26cf]::util::run_in_thread_pool_with_globals<rustc_interface[68fc4f7f4eaa26cf]::interface::run_compiler<(), rustc_driver_impl[438371d8e84705cb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  56:     0x7e903ba8a559 - <<std[644fad426ed526f7]::thread::Builder>::spawn_unchecked_<rustc_interface[68fc4f7f4eaa26cf]::util::run_in_thread_with_globals<rustc_interface[68fc4f7f4eaa26cf]::util::run_in_thread_pool_with_globals<rustc_interface[68fc4f7f4eaa26cf]::interface::run_compiler<(), rustc_driver_impl[438371d8e84705cb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[d2a938784d8f7dcb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  57:     0x7e903ba89ceb - std::sys::pal::unix::thread::Thread::new::thread_start::h6b29fca7c6a267b7
  58:     0x7e9035ca339d - <unknown>
  59:     0x7e9035d2849c - <unknown>
  60:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (2f348cb7c 2025-01-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `Inline::{constant#0}`
#1 [eval_to_valtree] evaluating type-level constant
#2 [typeck] type-checking `main`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors; 1 warning emitted

Some errors have detailed explanations: E0392, E0599.
For more information about an error, try `rustc --explain E0392`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### PR DESCRIPTION
**Pull request by cjgillot**
This PR changes the way we compute the value of the `offset_of!` macro in MIR. The current implementation uses a dedicated MIR rvalue.

This PR proposes to replace it by an inline constant which sums calls to a new intrinsic `offset_of(variant index, field index)`. The desugaring is done at THIR building time, easier that doing it on MIR.

The new intrinsic is only meant to be used by const-eval. LLVM codegen will refuse to generate code for it.

We replace:
```rust
a = offset_of!(T, Variant1.Field1.Variant2.Field2);
```

By:
```rust
a = const {constant#n};

{constant#n}: usize = {
    _1 = offset_of::<T>(index of Variant1, index of Field1);
    _2 = offset_of::<U>(index of Variant2, index of Field2); // Where T::Variant1::Field1 has type U
    _0 = _1 + _2
}
```

The second commit modifies intrinsic const checking to take `allow_internal_unstable` into account. The new intrinsic should only be called from stable `offset_of!` macro. The intrinsic itself is unstable, const-unstable, but `rustc_intrinsic_const_stable_indirect`.

Fixes rust-lang/rust#123959
Fixes rust-lang/rust#125680
Fixes rust-lang/rust#129425
Fixes rust-lang/rust#136175

r? @ghost

### CODE REVIEW

File: library/core/src/intrinsics/mod.rs [hunk 1]
```diff
@@ -2747,18 +2742,30 @@ pub const fn size_of<T>() -> usize;
...
 pub const fn align_of<T>() -> usize;
 
+/// The offset of a field inside a type.
+///
+/// Note that, unlike most intrinsics, this is safe to call;
+/// it does not require an `unsafe` block.
+/// Therefore, implementations must not require the user to uphold
+/// any safety invariants.
+///
+/// The stabilized version of this intrinsic is [`core::mem::align_of`].
```
Comment (cjgillot) [inline library/core/src/intrinsics/mod.rs]:
```suggestion
/// The stabilized version of this intrinsic is [`core::mem::offset_of`].
```

**Comment by cjgillot** [comment]
My justification is simplifying MIR. This feature was implemented as a specific MIR statement, but does not need to, an intrinsic is sufficient.

There should be no user-facing change because of the `offset_of` manipulation. Maybe some diagnostics, but not more.

However, there are 2 user-facing changes in this PR that t-lang may want to know:
- const-stability of intrinsics now takes `allow_internal_unstable` into account;
- we get an additional intrinsic with `rustc_intrinsic_const_stable_indirect`.

**Comment by WaffleLapkin** [comment]
> The new intrinsic is only meant to be used by const-eval. LLVM codegen will refuse to generate code for it.

Couldn't we encode this as a generic constant so that we don't need the intrinsic/ignore it in codegen?

**Comment by cjgillot** [comment]
> Couldn't we encode this as a generic constant so that we don't need the intrinsic/ignore it in codegen?

This is what is done yes.

**Comment by scottmcm** [comment]
(With my lang hat) This is moving the current magic macro to a magic intrinsic, so a new never-directly-stable intrinic generated by the magic macro seems entirely reasonable.

@rfcbot merge

cc @RalfJung again explicitly as the current expert, AFAIK, for how const stability works to ensure that the changes here aren't violating the expectations from how that's working.

---

(With my compiler hat) Big fan of getting the `&'tcx List` out of `NullOp`.  Expanding to multiple simpler things in MIR, while keeping the nice API in the public macro, sound good to me.

File: compiler/rustc_const_eval/src/interpret/intrinsics.rs [hunk 2]
```diff
@@ -174,6 +174,21 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
                 let val = layout.align.bytes();
                 self.write_scalar(Scalar::from_target_usize(val, self), dest)?;
             }
+            sym::offset_of => {
+                let tp_ty = instance.args.type_at(0);
+
+                let u32_layout = self.layout_of(self.tcx.types.u32)?;
+                let variant = self.read_scalar(&args[0])?.to_bits(u32_layout.size)? as u32;
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/intrinsics.rs]:
```suggestion
                let variant = self.read_scalar(&args[0])?.to_u32()?;
```

File: compiler/rustc_const_eval/src/interpret/intrinsics.rs [hunk 3]
```diff
@@ -174,6 +174,21 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
+                let field = self.read_scalar(&args[1])?.to_bits(u32_layout.size)? as usize;
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/intrinsics.rs]:
```suggestion
                let field = self.read_scalar(&args[1])?.to_u32()? as usize;
```

File: library/core/src/intrinsics/mod.rs [hunk 4]
```diff
@@ -2763,6 +2763,22 @@ pub const fn size_of<T>() -> usize;
...
 pub const fn align_of<T>() -> usize;
 
+/// The offset of a field inside a type.
+///
+/// Note that, unlike most intrinsics, this is safe to call;
+/// it does not require an `unsafe` block.
+/// Therefore, implementations must not require the user to uphold
+/// any safety invariants.
+///
+/// The stabilized version of this intrinsic is [`core::mem::offset_of`].
```
Comment (RalfJung) [inline library/core/src/intrinsics/mod.rs:2804]: This can also only be called at compile time, right? Please add that note to the comment.

Also, would be good to explain why this is a lang item, since that is very unusual for intrinsics.

**Review by RalfJung — COMMENTED** [review]
rustc_const_eval changes LGTM.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148151/fca2e941f86f51cd3c3254518f45e2145563f6be..9fd16d6cd4bfc3723655b8285a171083fb3c5491)*

File: library/core/src/intrinsics/mod.rs [hunk 5]
```diff
@@ -2781,6 +2781,26 @@ pub const fn size_of<T>() -> usize;
...
 
+/// The offset of a field inside a type.
+///
+/// Note that, unlike most intrinsics, this is safe to call;
+/// it does not require an `unsafe` block.
+/// Therefore, implementations must not require the user to uphold
+/// any safety invariants.
+///
+/// This intrinsic can only be evaluated at compile-time, and should appear
+/// constants or inline const blocks.
```
Comment (scottmcm) [inline library/core/src/intrinsics/mod.rs]: nit: I think this is missing a word?  Something like
```suggestion
/// This intrinsic can only be evaluated at compile-time, and should only appear in
/// constants or inline const blocks.
```

File: tests/mir-opt/building/offset_of.rs [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+// CHECK: concrete::[[const_y]]: usize
+// CHECK: _0 = offset_of::<Alpha>(const 0_u32, const 1_u32)
+
+// CHECK: concrete::[[const_h]]: usize
+// CHECK: _0 = offset_of::<Blah>(const 1_u32, const 1_u32)
+
+// CHECK: concrete::[[const_z0]]: usize
+// CHECK: [[z:_.*]] = offset_of::<Alpha>(const 0_u32, const 2_u32)
+// CHECK: [[z0:_.*]] = offset_of::<Beta>(const 0_u32, const 0_u32)
+// CHECK: [[sum:_.*]] = AddWithOverflow(copy [[z]], copy [[z0]]);
```
Comment (scottmcm) [inline tests/mir-opt/building/offset_of.rs:71]: pondering: Can this ever overflow?  Wouldn't the type have to be malformed for it to happen?  Since we're only ever running it in CTFE, could it be `AddUnchecked` instead, and if it ever *does* overflow it'll get trapped by the UB-in-CTFE checks?

(Aside: appreciate the test here -- I came looking for it as soon as I was reading the code in `mir_build`.)

File: compiler/rustc_mir_build/src/thir/cx/expr.rs [hunk 7]
```diff
@@ -818,11 +824,48 @@ impl<'tcx> ThirBuildCx<'tcx> {
...
+                    };
+
+                let indices = self.typeck_results.offset_of_data().get(expr.hir_id).unwrap();
+                let mut expr = None::<ExprKind<'tcx>>;
+
+                for &(container, variant, field) in indices.iter() {
+                    let next = mk_call(&mut self.thir, container, variant, field);
+                    expr = Some(match expr.take() {
+                        None => next,
+                        Some(last) => {
```
Comment (scottmcm) [inline compiler/rustc_mir_build/src/thir/cx/expr.rs:851]: ymmv: Consider phrasing this via [`Iterator::reduce`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.reduce), since if it's `indices.iter().map(…).reduce(…).unwrap_or(…)` it handles the "is this the first one" checks for you automatically, which might make it more directly visible what it's doing.

File: tests/mir-opt/building/offset_of.rs (hunk 6 above)
Comment (scottmcm) [reply tests/mir-opt/building/offset_of.rs:71]: Actually, I'm kinda confused how it's `AddWithOverflow` here -- at <https://github.com/rust-lang/rust/pull/148151/files#diff-ad5988b23007e07f23d5459907b7aa75c9dc6ae82623be8cd4bc6acc58cb3397R863> it's `BinOp::Add`, not `BinOp::AddWithOverflow`.

Is there a `TerminatorKind::Assert` in here too somehow?

File: library/core/src/intrinsics/mod.rs [hunk 8]
```diff
@@ -2781,6 +2781,26 @@ pub const fn size_of<T>() -> usize;
...
+///
+/// The stabilized version of this intrinsic is [`core::mem::offset_of`].
+/// This intrinsic is also a lang item so `offset_of!` can desugar to calls to it.
+#[rustc_nounwind]
+#[unstable(feature = "core_intrinsics", issue = "none")]
+#[rustc_const_unstable(feature = "core_intrinsics", issue = "none")]
+#[rustc_intrinsic_const_stable_indirect]
+#[rustc_intrinsic]
+#[lang = "offset_of"]
+pub const fn offset_of<T: PointeeSized>(variant: u32, field: u32) -> usize;
```
Comment (scottmcm) [inline library/core/src/intrinsics/mod.rs:2812]: Musing: Is there ever a need to pass *values* into this?  Why is it phrased this way as opposed to, say

```suggestion
pub const fn offset_of<T: PointeeSized, const Variant: u32, const Field: u32>() -> usize;
```

(Not that the way it is is *bad* -- I think it's fine -- just came to mind as I was reading through stuff.)

**Review by scottmcm — APPROVED** [review]
`r=me` with the trivial comment fix.  I left a bunch of other things on the way by that you can think about as well, but I don't think any of them are critical.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148151/86b95ebc24092acac75e205d95e84e6d4539601f..d65ccdd0cb5230ce74f4b01e9bf85643e1da12e3)*

File: tests/mir-opt/building/offset_of.rs (hunk 6 above)
Comment (cjgillot) [reply tests/mir-opt/building/offset_of.rs:71]: It cannot possibly overflow, but as I made the transform happen on THIR, removing the overflow checks would only make stuff more complex.

File: compiler/rustc_mir_build/src/thir/cx/expr.rs (hunk 7 above)
Comment (cjgillot) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:851]: Thanks for the suggestion, I did not know that method. However, both closures mutably borrow `self.thir.exprs`, so that's unpractical.

File: tests/mir-opt/building/offset_of.rs (hunk 6 above)
Comment (cjgillot) [reply tests/mir-opt/building/offset_of.rs:71]: I added a THIR-print test to show what the generated THIR looks like.
