### PR TITLE
bootstrap: fix clean's remove_dir_all implementation

### LINKED ISSUE #112544: Bootstrap cannot remove host symlink on Windows if created from WSL2
If I use `./x` in WSL2 it will create a host symlink in the build directory. If I then switch to the Windows host using the same build directory I get this error:

```text
thread 'main' panicked at 'fs::remove_dir(&host) failed with The directory name is invalid. (os error 267)', lib.rs:516:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The simplest solution here would be to detect `ERROR_DIRECTORY` (aka os error 267) and fallback to `fs::remove_file`.

### PR DESCRIPTION
**Pull request by jieyouxu**
It turns out bootstrap's `clean.rs`'s hand-rolled `rm_rf` (which probably comes before `std::fs::remove_dir_all` was stable) is very broken on native Windows around both read-only files/directories and especially symbolic links. So instead of rolling our own, just use `std::fs::remove_dir_all`.

This is a related to compiletest's own `rm_rf` implementation #129155 which happens to be also buggy, which in turn is a blocker for the rmake.rs test port #128562 that heavily exercises symlinks (I was reviewing #128562 and testing it on native Windows which is how I found out).

Fixes #112544 (because now we handle Windows symlinks properly).

try-job: x86_64-msvc
try-job: i686-mingw
try-job: test-various
try-job: armhf-gnu
try-job: aarch64-apple
try-job: aarch64-gnu

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/clean/tests.rs
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/clean/tests.rs:1]: Problem: I actually need to first check for symlink priviledges for Windows before trying to use it. It won't fail in CI where this priviledge is given, but it will fail locally if we don't have the priviledge.

File: src/bootstrap/src/core/config/tests.rs [hunk 1]
```diff
@@ -66,6 +66,9 @@ fn detect_src_and_out() {
 
         // test if build-dir was manually given in config.toml
         if let Some(custom_build_dir) = build_dir {
+            // FIXME(jieyouxu): this assertion fails on native Windows because if the rust checkout
+            // and build directory is on `E:\\` not `C:\\`, then it fails with e.g. `E:\\tmp !=
+            // C:\\tmp`.
             assert_eq!(&cfg.out, Path::new(custom_build_dir));
```
Comment (jieyouxu) [inline src/bootstrap/src/core/config/tests.rs:72]: This fails locally for me, thus I opened #129188. I should change this to `FIXME(#129188)` later.

**Comment by ChrisDenton** [comment]
I feel like the `std::fs::remove_dir_all` tests should be std tests rather than bootstrap tests.

**Comment by jieyouxu** [comment]
> I feel like the `std::fs::remove_dir_all` tests should be std tests rather than bootstrap tests.

I might actually remove the tests because std already has some for `remove_dir_all`.

File: src/bootstrap/src/core/build_steps/clean/tests.rs
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/clean/tests.rs:1]: We probably don't need this test, because it's testing std's `remove_dir_all` which already has its own set of tests.

File: src/bootstrap/src/core/build_steps/clean.rs [hunk 2]
```diff
@@ -166,78 +165,16 @@ fn clean_default(build: &Build) {
...
-                }
-                panic!("failed to {} {}: {}", desc, path.display(), e);
-            });
-        }
-        Err(e) => {
-            panic!("failed to {} {}: {}", desc, path.display(), e);
-        }
+/// Wrapper for [`std::fs::remove_dir_all`] that panics on failure and prints the `path` we failed
+/// on.
+fn remove_dir_all_wrapper<P: AsRef<Path>>(path: P) {
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/clean.rs:175]: The name sounds a bit complex. What about just `remove_dir`, `remove_directory` or `remove_dir_recursive`?

File: src/bootstrap/src/core/config/tests.rs [hunk 3]
```diff
@@ -66,6 +66,9 @@ fn detect_src_and_out() {
 
         // test if build-dir was manually given in config.toml
         if let Some(custom_build_dir) = build_dir {
+            // FIXME(#129188): this assertion fails on native Windows because if the rust checkout
```
Comment (Kobzol) [inline src/bootstrap/src/core/config/tests.rs:69]: Is the FIXME needed, since https://github.com/rust-lang/rust/issues/129188 is already up?

**Review by Kobzol — COMMENTED** [review]
Thanks! Always nice to remove old cruft from boostrap (hopefully the stdlib implementation is enough). Feel free to r=me with or without the two nits.

File: src/bootstrap/src/core/build_steps/clean.rs (hunk 2 above)
Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/clean.rs:175]: I'll change it ti remove_dir_recursive

File: src/bootstrap/src/core/config/tests.rs (hunk 3 above)
Comment (jieyouxu) [reply src/bootstrap/src/core/config/tests.rs:69]: No longer needed

Comment (jieyouxu) [reply src/bootstrap/src/core/config/tests.rs]: Removed.

File: src/bootstrap/src/core/build_steps/clean.rs (hunk 2 above)
Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/clean.rs]: Changed to `remove_dir_recursive`.

**Comment by Kobzol** [comment]
Thanks!

@bors r+

**Comment by jieyouxu** [comment]
Also unapproving this as I want to triple-check the read-only handling.
@bors r-

**Comment by jieyouxu** [comment]
Based on investigation in https://github.com/rust-lang/rust/pull/129302#issuecomment-2299532417, `std::fs::remove_dir_all` does handle both symlinks and read-only files and directories on Windows (10 RS1 and beyond) and Unix.

@rustbot ready

**Comment by krasimirgg** [comment]
For some reason, after this we're getting some failures with `x.py clean`. Initially I saw this in our rust+llvm@head build bot: https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/30548#01917a4a-a850-4dd1-9c7a-38da213bc8ea.

I tried it with a freshly-cloned version of rust and was able to reproduce as:
```
git clone https://github.com/rust-lang/rust
cd rust
git clean -fdx
python3 x.py clean --all
...
thread 'main' panicked at src/core/build_steps/clean.rs:178:9:
failed to `remove_dir_all` at `tmp`: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Creating a `tmp` directory under the checked out `rust` seems to fix it.

**Comment by jieyouxu** [comment]
Oh wait. I think I didn't consider the top-level directory missing but was ultrafocused on read-only/symlinks of nested directory entries.

I'm going to revert the two PRs then reland the PRs properly accounting for missing top-level directories.

**Comment by jieyouxu** [comment]
> For some reason, after this we're getting some failures with `x.py clean`. Initially I saw this in our rust+llvm@head build bot: [buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/30548#01917a4a-a850-4dd1-9c7a-38da213bc8ea](https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/30548#01917a4a-a850-4dd1-9c7a-38da213bc8ea).


Thanks for the heads up! This PR and the compiletest PR is indeed the culprit. My apologies for borking the buildsystem.

**Comment by jieyouxu** [comment]
> For some reason, after this we're getting some failures with `x.py clean`. 

Revert PR is up at https://github.com/rust-lang/rust/pull/129413.
