### PR TITLE
Reject integer suffix when tuple indexing

### LINKED ISSUE #59418: Syntax: ignoring tuple index with a suffix (a.1lolololol)
```rust
fn main() {
    let a = (1, 2, 3);
    println!("{}", a.1lolololol);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4280ded6698f9f9f3877ad0498769cb7

Expected:
```
ERROR: tuple index with a suffix is invalid
```

Got:
```
Output: 2\n
```

All thanks to: https://linuxrocks.online/@carl/101569506337640753

UPD:

The same error arises with tuple struct:

```rust
struct X(i32,i32,i32);

fn main() {
    let a = X(1, 2, 3);
    let b = a.1lolololol;
    println!("{}", b);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad7f39e8edad0d98f2919bd4fdfded30

Expected:
```
ERROR: tuple index with a suffix is invalid
```

Got:
```
Output: 2\n
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #59418.

r? @varkor

### CODE REVIEW

**Comment by estebank** [comment]
Fixed indenting in the block, you can ignore the whitespace changes with https://github.com/rust-lang/rust/pull/59421/files?w=1

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -3196,51 +3196,60 @@ impl<'a> Parser<'a> {
...
-                  }
-                  _ => {
-                    // FIXME Could factor this out into non_fatal_unexpected or something.
-                    let actual = self.this_token_to_string();
-                    self.span_err(self.span, &format!("unexpected token: `{}`", actual));
-                  }
+                        if let Some(suffix) = suffix {
+                            let mut err = self.diagnostic().struct_span_err(
+                                span,
+                                "tuple index with a suffix is invalid",
```
Comment (varkor) [inline src/libsyntax/parse/parser.rs]: While we're here, the old error message sounded a bit unnatural. Maybe something like:
```
tuple indices may not have suffixes
```
or:
```
suffixes on tuple indexes are invalid
```
sounds a bit better?

**Comment by varkor** [comment]
The message could probably be rephrased to sound less awkward, but r=me either way.

**Comment by varkor** [comment]
> Fixed indenting in the block

I had done exactly the same thing 😄

File: src/test/ui/parser/issue-59418.rs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+struct X(i32,i32,i32);
+
+fn main() {
+    let a = X(1, 2, 3);
+    let b = a.1suffix;
```
Comment (kpp) [inline src/test/ui/parser/issue-59418.rs]: How about a test for tuples too?

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -3196,51 +3196,60 @@ impl<'a> Parser<'a> {
...
-                    self.span_err(self.span, &format!("unexpected token: `{}`", actual));
-                  }
+                        if let Some(suffix) = suffix {
+                            let mut err = self.diagnostic().struct_span_err(
+                                span,
+                                "suffixes on tuple indexes are invalid",
+                            );
+                            err.span_label(span, format!("invalid suffix `{}`", suffix));
+                            err.emit();
+                        }
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]:
```
self.expect_no_suffix(span, "tuple index", suffix);
```

**Comment by petrochenkov** [comment]
I was going to blame beginner contributors and diagnostic improvements for this regression, but it turned out it was me - https://github.com/rust-lang/rust/pull/49718/commits/44acea4d880b646caa00a7237ea1a17031dd2116.

**Comment by petrochenkov** [comment]
@estebank 
Could you also add test cases for suffixed literals in fields in struct expressions and struct patterns.
```
let s = S { 0suffix: 0 };
match s {
    S { 0suffix: _ } => {}
}
```

**Comment by Centril** [comment]
@petrochenkov @estebank This is already r+ed, should we add the extra test cases in follow up PRs?

**Comment by estebank** [comment]
Added the requested changes. r? @petrochenkov, can you take a look to give final approval?

For the case you asked the output is

```
error: expected identifier, found `0suffix`
  --> src/main.rs:12:17
   |
12 |     let s = X { 0suffix: 0, 1: 1, 2: 2 };
   |             -   ^^^^^^^ expected identifier
   |             |
   |             while parsing this struct

error: expected identifier, found `0suffix`
  --> src/main.rs:15:13
   |
15 |         X { 0suffix: _, .. } => {}
   |             ^^^^^^^ expected identifier

error[E0063]: missing field `0` in initializer of `X`
  --> src/main.rs:12:13
   |
12 |     let s = X { 0suffix: 0, 1: 1, 2: 2 };
   |             ^ missing `0`

error[E0027]: pattern does not mention fields `0`, `1`, `2`
  --> src/main.rs:15:9
   |
15 |         X { 0suffix: _, .. } => {}
   |         ^^^^^^^^^^^^^^^^^^^^ missing fields `0`, `1`, `2`
   |
   = note: trying to match a tuple variant with a struct variant pattern
```

Which is why I think it shouldn't be added to the test, as it is not handled by this PR.

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -3205,14 +3205,7 @@ impl<'a> Parser<'a> {
...
 
-                        if let Some(suffix) = suffix {
-                            let mut err = self.diagnostic().struct_span_err(
-                                span,
-                                "suffixes on tuple indexes are invalid",
-                            );
-                            err.span_label(span, format!("invalid suffix `{}`", suffix));
-                            err.emit();
-                        }
+                        self.expect_no_suffix(span, "tuple index", suffix);
```
Comment (varkor) [inline src/libsyntax/parse/parser.rs]: I think we should change the `expect_no_suffix` text to align with the `"suffixes on tuple indexes are invalid"` text.

**Comment by petrochenkov** [comment]
@estebank 
>Which is why I think it shouldn't be added to the test, as it is not handled by this PR.

I think what this PR is doing (accept suffixed literal, report a non-fatal error, continue) is a better alternative than "expected identifier, found `0suffix`", so we can use it for struct expressions/patterns as well and unify the diagnostics.

File: src/libsyntax/parse/parser.rs (hunk 4 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: Done.

**Comment by estebank** [comment]
@petrochenkov

I see. Fixed.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

File: src/test/ui/parser/issue-59418.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+    //~^ ERROR suffixes on a tuple index are invalid
+    println!("{}", b);
+    let c = (1, 2, 3);
+    let d = c.1suffix;
+    //~^ ERROR suffixes on a tuple index are invalid
+    println!("{}", d);
+    let s = X { 0suffix: 0, 1: 1, 2: 2 };
```
Comment (kpp) [inline src/test/ui/parser/issue-59418.rs]: How about `X { 0usize: 0, 1: 1, 2: 2 };`?

Comment (Centril) [reply src/test/ui/parser/issue-59418.rs]: (don't r- the PR in either case since it's in a rollup now... if changes need to be made, do it in a follow up PR)
