### PR TITLE
Reduce the reliance on `PATH_MAX`

### LINKED ISSUE #27454: Rust assumes PATH_MAX is not a lie in a few places
See http://insanecoding.blogspot.ca/2007/11/pathmax-simply-isnt.html for some background.  Basically, `PATH_MAX` just doesn't work.

Currently. Rust uses `PATH_MAX` in a few important places.

./src/libstd/sys/unix/fs.rs:377:`           let mut buf = vec![0;libc::PATH_MAX as usize];`
./src/libstd/sys/unix/fs.rs:469:`        len = 1024; // FIXME: read PATH_MAX from C ffi?`
./src/rt/rust_builtin.c:337:`  char buf[2*PATH_MAX], exe[2*PATH_MAX];`
./src/rt/rust_builtin.c:380:`    snprintf(buf, 2*PATH_MAX, "%s/%s", paths[i], argv0);`

Generally, the best approach to work around this is to loop and double a buffer in size until it is big enough in size to fill with the path or to query the size of the path of the file using `fpathconf`.  I'm not sure if any filesystems on any modern OSes return -1 for the result of  `fpathconf`.  Letting things get too big opens up a DOS attack though so be careful I guess?

The `fpathconf` strategy or the doubling buffer strategy can be done with ./src/libstd/sys/unix/fs.rs:469 but I'm not sure how to handle the Rust cases that use `realpath` (unless `realpath` is reimplemented by hand).  The C code can just use the `NULL` argument but I forget if there's a way to martial allocated by C data to Rust.

### PR DESCRIPTION
**Pull request by barosl**
This PR rewrites the code that previously relied on `PATH_MAX`.

On my tests, even though the user gives the buffer length explicitly, both Linux's glibc and OS X's libc seems to obey the hard limit of `PATH_MAX` internally. So, to truly remove the limitation of `PATH_MAX`, the related system calls should be rewritten from scratch in Rust, which this PR does not try to do.

However, eliminating the need of `PATH_MAX` is still a good idea for various reasons, such as: (1) they might change the implementation in the future, and (2) some platforms don't have a hard-coded `PATH_MAX`, such as GNU Hurd.

More details are in the commit messages.

Fixes #27454.

r? @alexcrichton

### CODE REVIEW

File: src/libstd/sys/unix/fs.rs [hunk 1]
```diff
@@ -463,18 +468,24 @@ pub fn rmdir(p: &Path) -> io::Result<()> {
...
+                                                    buf.capacity() as libc::size_t) })) as usize;
+        if buf_read != buf.capacity() {
+            unsafe { buf.set_len(buf_read); }
+            buf.shrink_to_fit();
+
+            return Ok(PathBuf::from(OsString::from_vec(buf)));
+        }
+
+        let new_cap = buf.capacity() * 2;
+        buf.reserve(new_cap);
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: This is actually the extra space to reserve, so this may be growing a little more rapidly than anticipated. Like with [`read_to_end`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/io.rs#L38-L40) this can probably just call `buf.reserve(1)` after setting the length of the capacity to let the internal doubling logic take over

File: src/liblibc/lib.rs [hunk 2]
```diff
@@ -3955,6 +3962,10 @@ pub mod consts {
             pub const _SC_STREAM_MAX : c_int = 27;
             pub const _SC_TZNAME_MAX : c_int = 28;
             pub const _SC_PAGESIZE : c_int = 39;
+
+            // Android
```
Comment (alexcrichton) [inline src/liblibc/lib.rs]: It's ok to remove these comments as it's already implied by the location of the definition anyway

File: src/libstd/sys/unix/fs.rs [hunk 3]
```diff
@@ -373,6 +373,10 @@ impl fmt::Debug for File {
 
         #[cfg(target_os = "macos")]
         fn get_path(fd: c_int) -> Option<PathBuf> {
+            // FIXME: The use of PATH_MAX is generally not encouraged, but it is inevitable in this
+            // case because OS X defines `fcntl` with `F_GETPATH` in terms of `MAXPATHLEN`, and
+            // there are no alternatives. If a better method is invented, it should be used
+            // instead.
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Can you be sure to wrap this to 80 chars?

File: src/libstd/sys/unix/fs.rs [hunk 4]
```diff
@@ -463,18 +468,24 @@ pub fn rmdir(p: &Path) -> io::Result<()> {
...
-        }));
-        buf.set_len(n as usize);
+
+    let mut buf = Vec::with_capacity(256);
+
+    loop {
+        let buf_read = try!(cvt(unsafe { libc::readlink(
+                                                    p,
+                                                    buf.as_mut_ptr() as *mut libc::c_char,
+                                                    buf.capacity() as libc::size_t) })) as usize;
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: This formatting is a bit off, perhaps:

```
let amt = try!(cvt(unsafe {
    libc::readlink(...)
}));
// ...
```

File: src/libstd/sys/unix/fs.rs (hunk 1 above)
Comment (barosl) [inline src/libstd/sys/unix/fs.rs]: The length of `buf` remains 0 until the end, so I think `buf.reserve()` will work as expected in this case. The problem is, as you said, `Vec::reserve` has the internal doubling logic, so the capacity will grow as in `N, 4N, 16N, 64N, ...`.

The recently added [getcwd](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/os.rs#L101-L114) has a similar logic but it uses an external variable to track the desired capacity, so the capacity being four times each iteration will not happen. However, every one of two `Vec::reserve` calls will be no-op because the previously increased capacity will be sufficient to meet the new requirement. This also means every one of two system calls is wasted.

Correct me if I'm wrong, but the behavior of `read_to_end_uninitialized` seems to be a bit misleading too. What it will do is `N, 2(N+1), 2(2(N+1))+1, ...`, because the internal doubling is applied after the capacity is increased by one. Is this an expected behavior? I don't know much about the allocator, but I guess the capacity remaining `2^N` seems to be ideal. The behavior does not follow this.

There seems to be a more appropriate function for this purpose: `Vec::reserve_exact`. It has the almost identical behavior except it does not double the capacity internally, so it would be useful if the user is assured to provide an appropriate new capacity and also wants to prevent excessive memory allocation. What do you think of this?

File: src/libstd/sys/unix/fs.rs (hunk 3 above)
Comment (barosl) [inline src/libstd/sys/unix/fs.rs]: Do you mean comments should be wrapped in 80 column width?

File: src/libstd/sys/unix/fs.rs [hunk 5]
```diff
@@ -511,15 +522,15 @@ pub fn lstat(p: &Path) -> io::Result<FileAttr> {
...
-    let mut buf = vec![0u8; 16 * 1024];
+    let buf;
     unsafe {
-        let r = c::realpath(path.as_ptr(), buf.as_mut_ptr() as *mut _);
+        let r = c::realpath(path.as_ptr(), ptr::null_mut());
         if r.is_null() {
             return Err(io::Error::last_os_error())
         }
+        buf = CStr::from_ptr(r).to_bytes().to_vec();
+        libc::free(r as *mut _);
```
Comment (barosl) [inline src/libstd/sys/unix/fs.rs]: Do you think it might be a good idea to place an RAII guard on this? I believe `CStr::from_ptr(r).to_bytes().to_vec() will not panic currently, but if it changes the behavior in the future (e.g. `to_vec()` panics rather than aborting in case of OOM), the manually allocated memory will be leaked. Do we have to be concerned about this kind of situations? How much overhead an RAII guard incur?

File: src/liblibc/lib.rs (hunk 2 above)
Comment (barosl) [inline src/liblibc/lib.rs]: Yeah, it was purely for helping myself. :smile:

File: src/liblibc/lib.rs [hunk 6]
```diff
@@ -3912,6 +3912,9 @@ pub mod consts {
             pub const _SC_XBS5_ILP32_OFFBIG : c_int = 126;
             pub const _SC_XBS5_LPBIG_OFFBIG : c_int = 128;
 
+            // Linux
+            pub const _PC_NAME_MAX: c_int = 3;
+            pub const _PC_PATH_MAX: c_int = 4;
```
Comment (barosl) [inline src/liblibc/lib.rs]: Currently I placed the constants in the `sysconf` module, as `pathconf` seemed to be categorized as the same as `sysconf. Do you believe this is the right place?

After all, the entire structure of `libc` seems to need some refactoring, I guess...

File: src/libstd/sys/unix/fs.rs (hunk 3 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Yes

File: src/liblibc/lib.rs (hunk 6 above)
Comment (alexcrichton) [inline src/liblibc/lib.rs]: Ah yeah it doesn't matter too much to me where these go so long as they're accessible

File: src/libstd/sys/unix/fs.rs (hunk 5 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: An RAII guard shouldn't have much overhead, but it's not really necessary so it's fine to not worry about this.

File: src/libstd/sys/unix/fs.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Ah actually because the length of the buffer isn't changing here (nor in the `getcwd` case) it's actually working as anticipated. The `reserve` function reserves space for `n` extra elements, but because the length of the vector is 0 it works out that you're just specifying the capacity.

In `read_to_end_uninitialized` the request is always rounded up to the next power of two so it ends up just doubling the vector whenever it reallocates. So long as the `len` is updated to be the same as the capacity in this (and possibly `getcwd` too) then `reserve(1)` should be all you need.

Comment (barosl) [inline src/libstd/sys/unix/fs.rs]: > In `read_to_end_uninitialized` the request is always rounded up to the next power of two so it ends up just doubling the vector whenever it reallocates.

Actually, what I said above is that it does *not* work like that! For example, if I add `println!("{:?}", buf.capacity())` right after the `buf.reserve(1)` statement in the function, it outputs:

```
32
66
134
270
542
1086
2174
```

It *doesn't* produce the powers of 2, because 1 is added *before* doubling the capacity. And that's why I say it doesn't seem to be ideal. I believe the modern allocators tend to work well when the requested space is the powers of 2, so the new capacity should be adjusted to a power of 2 if possible, but `read_to_end_uninitialized` doesn't seem to follow that. Is my observation correct?

Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Ah yeah I guess that makes sense. In any case, however, these should all follow the same strategy instead of reinventing the wheel. Let's have them all take the `reserve(1)` route to punt to `Vec` as much as possible for figuring out its reallocation strategy

Comment (barosl) [inline src/libstd/sys/unix/fs.rs]: Uhm, sorry for asking this again, but there's still a remaining concern. As the length is not actually set to the capacity at each iteration currently, calling `buf.reserve(1)` will be a no-op in my code.

Do you think the length should be updated every time before calling `reserve`? Something like:

```rust
loop {
    let buf_read = try!(readlink(...));

    unsafe { buf.set_len(buf_read); } // This will be added

    if buf_read != buf.capacity() {
        unsafe { buf.set_len(buf_read); } // This should probably be removed
        buf.shrink_to_fit();

        return Ok(...);
    }

    buf.reserve(1);
}
```

That feels a bit odd to me because unlike `read_to_end_uninitialized`, we abandon the buffer immediately if `readlink` fails. But if you're OK with the code above, I'll follow that.

Plus, do you think [getcwd](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/os.rs#L101-L114) might also have to be modified to use `reserve(1)`? This may have to be another PR, but if you like it, I can add another commit to address this.

Sorry for the disturbance, this shall be my last review request!

Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Yeah that sort of loop is fine to do, and it's fine by me if you want to share an implementation between `getcwd` and `readlink`. Thanks!

**Comment by barosl** [comment]
I addressed all of the comments and added another commit to modify `getcwd`. Please review it!

File: src/libstd/sys/unix/os.rs [hunk 7]
```diff
@@ -30,7 +30,7 @@ use sys::c;
 use sys::fd;
 use vec;
 
-const GETCWD_BUF_BYTES: usize = 2048;
+const GETCWD_BUF_BYTES: usize = 512;
```
Comment (alexcrichton) [inline src/libstd/sys/unix/os.rs]: It's ok to just go ahead and delete this constant and inline its value, I'm not sure that it's necessarily buying us a whole lot up here

File: src/libstd/sys/unix/os.rs [hunk 8]
```diff
@@ -111,7 +109,10 @@ pub fn getcwd() -> io::Result<PathBuf> {
                     return Err(error);
                 }
             }
-            n *= 2;
+
+            let cap = buf.capacity();
+            buf.set_len(cap);
+            buf.reserve(1);
```
Comment (alexcrichton) [inline src/libstd/sys/unix/os.rs]: Could you add a comment here just saying we're letting the vector decide how to best resize itself?

File: src/libstd/sys/unix/fs.rs [hunk 9]
```diff
@@ -466,18 +472,24 @@ pub fn rmdir(p: &Path) -> io::Result<()> {
...
+
+        unsafe { buf.set_len(buf_read); }
+
+        if buf_read != buf.capacity() {
+            buf.shrink_to_fit();
+
+            return Ok(PathBuf::from(OsString::from_vec(buf)));
+        }
+
+        buf.reserve(1);
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Like below, could you add a comment here just saying that we're letting the vector decide how to resize itself?

**Comment by alexcrichton** [comment]
Looks good to me, thanks @barosl! r=me after a few small nits and a squash

**Comment by barosl** [comment]
Done. What commits do you think should be squashed? I feel a sense that the changes to `libc` may have to be separated, but what about others? For now, I rebased them onto the current HEAD.

**Comment by alexcrichton** [comment]
Yeah it's fine to leave libc separate but feel free to squash the other four, so long as the commit message makes sense when taken in isolation I'm fine with it. Thanks!

**Comment by barosl** [comment]
Done, squashed into three commits.

**Comment by alexcrichton** [comment]
@bors: r+ 6065678e627643cc3275c677408d11f48802595e

Thanks!
