### PR TITLE
Retire the `unnamed_fields` feature for now

### LINKED ISSUE #117942: ICE: def_collector: `no entry found for key`
snippet:
````rust
struct Foo {
    _: union  {
    #[rustfmt::skip]
    f: String
    },
}


````

Version information
````
rustc 1.76.0-nightly (8d57ad1ad 2023-11-14)
binary: rustc
commit-hash: 8d57ad1adeb66bc183ee8171b57839656896b7d5
commit-date: 2023-11-14
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_resolve/src/def_collector.rs:61:56:
no entry found for key
stack backtrace:
   0:     0x7f73f999289c - std::backtrace_rs::backtrace::libunwind::trace::h31c51c172b60df1f
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f73f999289c - std::backtrace_rs::backtrace::trace_unsynchronized::he3f7436095f6c268
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f73f999289c - std::sys_common::backtrace::_print_fmt::h9ecb16af589a0fbb
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f73f999289c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h879345ff56d51582
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f73f99e58a0 - core::fmt::rt::Argument::fmt::hf48167ed22d6afa3
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/fmt/rt.rs:142:9
   5:     0x7f73f99e58a0 - core::fmt::write::haf17f643ce868e2d
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f73f99867bf - std::io::Write::write_fmt::hea57ebf7fed914ac
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/io/mod.rs:1762:15
   7:     0x7f73f9992684 - std::sys_common::backtrace::_print::hd6cb4ba72955bb4b
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f73f9992684 - std::sys_common::backtrace::print::h4634a5d49ae4175c
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f73f9995317 - std::panicking::default_hook::{{closure}}::h5b815abc8880c45c
  10:     0x7f73f999507f - std::panicking::default_hook::h9fc3db6ef2ff0764
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/panicking.rs:292:9
  11:     0x7f73f66e6c00 - std[4c4ee8ebf0986186]::panicking::update_hook::<alloc[b75c4bd6c90be06c]::boxed::Box<rustc_driver_impl[f2304ccc53dc8b38]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f73f9995a58 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0b9450117303d0ca
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/alloc/src/boxed.rs:2021:9
  13:     0x7f73f9995a58 - std::panicking::rust_panic_with_hook::h628d6ded0472c14b
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/panicking.rs:783:13
  14:     0x7f73f99957ae - std::panicking::begin_panic_handler::{{closure}}::h66949746e4f54942
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/panicking.rs:657:13
  15:     0x7f73f9992d66 - std::sys_common::backtrace::__rust_end_short_backtrace::h44ec451ae0e12e00
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f73f9995512 - rust_begin_unwind
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/panicking.rs:645:5
  17:     0x7f73f99e1f85 - core::panicking::panic_fmt::h5b80d414fa976bfc
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/panicking.rs:72:14
  18:     0x7f73f99e1d33 - core::panicking::panic_display::ha511c0ba4b1cda64
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/panicking.rs:178:5
  19:     0x7f73f99e1d33 - core::panicking::panic_str::h62d9420133b896b0
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/panicking.rs:152:5
  20:     0x7f73f99e1d33 - core::option::expect_failed::he876ec0710942e37
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/core/src/option.rs:1980:5
  21:     0x7f73f7a82d82 - <rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector>::collect_field
  22:     0x7f73f7a83352 - rustc_ast[e37068419772bcd3]::visit::walk_ty::<rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector>
  23:     0x7f73f7a829ed - <rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector>::collect_field
  24:     0x7f73f7ebd434 - rustc_ast[e37068419772bcd3]::visit::walk_item::<rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector>
  25:     0x7f73f7ebca96 - <rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector as rustc_ast[e37068419772bcd3]::visit::Visitor>::visit_item
  26:     0x7f73f7ebc99e - <rustc_resolve[6a65679376ac23a9]::def_collector::DefCollector as rustc_ast[e37068419772bcd3]::visit::Visitor>::visit_crate
  27:     0x7f73f7ebb07a - <rustc_resolve[6a65679376ac23a9]::Resolver as rustc_expand[12c5afb661d7ae19]::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  28:     0x7f73f7eb75c6 - <rustc_expand[12c5afb661d7ae19]::expand::MacroExpander>::collect_invocations
  29:     0x7f73f83b3d88 - <rustc_expand[12c5afb661d7ae19]::expand::MacroExpander>::fully_expand_fragment
  30:     0x7f73f83b2c2a - <rustc_expand[12c5afb661d7ae19]::expand::MacroExpander>::expand_crate
  31:     0x7f73f8a417f8 - rustc_interface[ed36f66d4dd25afa]::passes::resolver_for_lowering
  32:     0x7f73f8a40bab - rustc_query_impl[c23592c0c653c664]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c23592c0c653c664]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[69724fdf0a9160]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f73f86ffbb2 - rustc_query_system[d7212ac5995c6075]::query::plumbing::try_execute_query::<rustc_query_impl[c23592c0c653c664]::DynamicConfig<rustc_query_system[d7212ac5995c6075]::query::caches::SingleCache<rustc_middle[69724fdf0a9160]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c23592c0c653c664]::plumbing::QueryCtxt, false>
  34:     0x7f73f8700609 - rustc_query_impl[c23592c0c653c664]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f73f899e127 - rustc_interface[ed36f66d4dd25afa]::interface::run_compiler::<core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>, rustc_driver_impl[f2304ccc53dc8b38]::run_compiler::{closure#1}>::{closure#0}
  36:     0x7f73f89a5619 - std[4c4ee8ebf0986186]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ed36f66d4dd25afa]::util::run_in_thread_with_globals<rustc_interface[ed36f66d4dd25afa]::util::run_in_thread_pool_with_globals<rustc_interface[ed36f66d4dd25afa]::interface::run_compiler<core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>, rustc_driver_impl[f2304ccc53dc8b38]::run_compiler::{closure#1}>::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>
  37:     0x7f73f89a5443 - <<std[4c4ee8ebf0986186]::thread::Builder>::spawn_unchecked_<rustc_interface[ed36f66d4dd25afa]::util::run_in_thread_with_globals<rustc_interface[ed36f66d4dd25afa]::util::run_in_thread_pool_with_globals<rustc_interface[ed36f66d4dd25afa]::interface::run_compiler<core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>, rustc_driver_impl[f2304ccc53dc8b38]::run_compiler::{closure#1}>::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[41362f4be93c713f]::result::Result<(), rustc_span[e48a8ae9d6fa383d]::ErrorGuaranteed>>::{closure#1} as core[41362f4be93c713f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f73f999f915 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9a9c2927adaa2592
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/alloc/src/boxed.rs:2007:9
  39:     0x7f73f999f915 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3d4b40c6e2a97503
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/alloc/src/boxed.rs:2007:9
  40:     0x7f73f999f915 - std::sys::unix::thread::Thread::new::thread_start::hab0d4f9d960c1874
                               at /rustc/8d57ad1adeb66bc183ee8171b57839656896b7d5/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f73f38759eb - <unknown>
  42:     0x7f73f38f97cc - <unknown>
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (8d57ad1ad 2023-11-14) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack

```

</p>
</details>

### LINKED ISSUE #121161: ICE: `Anonymous structs or unions cannot be type parameters`
auto-reduced (treereduce-rust):
````rust
#[derive(Eq)]
#[repr(C)]
struct Bar {
    _: union {
        a: u8,
    },
}


````

original:
````rust
#![allow(incomplete_features)]
#![feature(unnamed_fields)]


#[derive(Eq)]
#[repr(C)]
struct Bar {
    _: union {
        a: u8,
    },
}

````

Version information
````
rustc 1.78.0-nightly (62fb0db9a 2024-02-15)
binary: rustc
commit-hash: 62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88
commit-date: 2024-02-15
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_builtin_macros/src/deriving/mod.rs:127:5:
Anonymous structs or unions cannot be type parameters
stack backtrace:
   0:     0x7f0f7ef8ce46 - std::backtrace_rs::backtrace::libunwind::trace::h53163824e7303228
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f0f7ef8ce46 - std::backtrace_rs::backtrace::trace_unsynchronized::hd2e35374a0eb2a80
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f0f7ef8ce46 - std::sys_common::backtrace::_print_fmt::h22916166849b0f03
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f0f7ef8ce46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2879f5e85b0fff5f
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f0f7efdd46c - core::fmt::rt::Argument::fmt::h97dbf5cc12c408c7
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/core/src/fmt/rt.rs:142:9
   5:     0x7f0f7efdd46c - core::fmt::write::h778946ec939e8793
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f0f7ef8087f - std::io::Write::write_fmt::h5c63578d080db7f3
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/io/mod.rs:1854:15
   7:     0x7f0f7ef8cbf4 - std::sys_common::backtrace::_print::h0363c2f779186f3d
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f0f7ef8cbf4 - std::sys_common::backtrace::print::h25462c423434b7b1
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f0f7ef8f93b - std::panicking::default_hook::{{closure}}::h77a19008a0b97cd9
  10:     0x7f0f7ef8f689 - std::panicking::default_hook::hc24779731fadc8e1
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/panicking.rs:292:9
  11:     0x7f0f81e073dc - std[520fd08387c28b7f]::panicking::update_hook::<alloc[91e232cd38241d97]::boxed::Box<rustc_driver_impl[2702a2e4e48d8624]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f0f7ef900a0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd2fc103bd8349bfb
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/alloc/src/boxed.rs:2030:9
  13:     0x7f0f7ef900a0 - std::panicking::rust_panic_with_hook::h413c2c5969744120
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/panicking.rs:785:13
  14:     0x7f0f7ef8fda9 - std::panicking::begin_panic_handler::{{closure}}::h1a6d4d7a04fe1759
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/panicking.rs:651:13
  15:     0x7f0f7ef8d326 - std::sys_common::backtrace::__rust_end_short_backtrace::he707e3793b7e3c10
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f0f7ef8fb14 - rust_begin_unwind
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/panicking.rs:647:5
  17:     0x7f0f7efd9975 - core::panicking::panic_fmt::he521a95bbefc6993
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/core/src/panicking.rs:72:14
  18:     0x7f0f83bcfc1c - rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::assert_ty_bounds
  19:     0x7f0f83bce7ba - rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::eq::expand_deriving_eq::{closure#0}
  20:     0x7f0f838a3f8c - <rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::generic::TraitDef>::expand_struct_def
  21:     0x7f0f83bcaa51 - <rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::generic::TraitDef>::expand_ext
  22:     0x7f0f83cb1157 - rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::eq::expand_deriving_eq
  23:     0x7f0f838a1c92 - <rustc_builtin_macros[c3e0db7c51eb1b0b]::deriving::BuiltinDerive as rustc_expand[6d4d13d6cfdcaa99]::base::MultiItemModifier>::expand
  24:     0x7f0f8397ca07 - <rustc_expand[6d4d13d6cfdcaa99]::expand::MacroExpander>::fully_expand_fragment
  25:     0x7f0f8397a4b7 - <rustc_expand[6d4d13d6cfdcaa99]::expand::MacroExpander>::expand_crate
  26:     0x7f0f83edbd12 - rustc_interface[1a4459fc77d0f37b]::passes::resolver_for_lowering
  27:     0x7f0f83edb1e7 - rustc_query_impl[af4ac1f50c857cdc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[af4ac1f50c857cdc]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[52734e1a61f3d33]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7f0f83db790e - rustc_query_system[2a398b116e853220]::query::plumbing::try_execute_query::<rustc_query_impl[af4ac1f50c857cdc]::DynamicConfig<rustc_query_system[2a398b116e853220]::query::caches::SingleCache<rustc_middle[52734e1a61f3d33]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[af4ac1f50c857cdc]::plumbing::QueryCtxt, false>
  29:     0x7f0f83db708b - rustc_query_impl[af4ac1f50c857cdc]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f0f83d60954 - rustc_interface[1a4459fc77d0f37b]::interface::run_compiler::<core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>, rustc_driver_impl[2702a2e4e48d8624]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7f0f83fcd686 - std[520fd08387c28b7f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1a4459fc77d0f37b]::util::run_in_thread_with_globals<rustc_interface[1a4459fc77d0f37b]::util::run_in_thread_pool_with_globals<rustc_interface[1a4459fc77d0f37b]::interface::run_compiler<core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>, rustc_driver_impl[2702a2e4e48d8624]::run_compiler::{closure#0}>::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>
  32:     0x7f0f83fcd4b2 - <<std[520fd08387c28b7f]::thread::Builder>::spawn_unchecked_<rustc_interface[1a4459fc77d0f37b]::util::run_in_thread_with_globals<rustc_interface[1a4459fc77d0f37b]::util::run_in_thread_pool_with_globals<rustc_interface[1a4459fc77d0f37b]::interface::run_compiler<core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>, rustc_driver_impl[2702a2e4e48d8624]::run_compiler::{closure#0}>::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f365f26a3905eec5]::result::Result<(), rustc_span[f91837123c8497a4]::ErrorGuaranteed>>::{closure#1} as core[f365f26a3905eec5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f0f7ef991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcab8919dd66e63e8
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/alloc/src/boxed.rs:2016:9
  34:     0x7f0f7ef991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7fcf03bbae47bb99
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/alloc/src/boxed.rs:2016:9
  35:     0x7f0f7ef991e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hdab999c156b6bbcb
                               at /rustc/62fb0db9a5a2a381f81ce0474c9bbd9ad385dd88/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7f0f7ed809eb - <unknown>
  37:     0x7f0f7ee047cc - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (62fb0db9a 2024-02-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack

```

</p>
</details>

### LINKED ISSUE #121263: ICE `expect Adt for unnamed field`
auto-reduced (treereduce-rust):
````rust
#[repr(C)]
#[repr(C)]
#[derive(Debug)]
struct L {
    _: i32,
    _: MyI32,
    _: BadEnum,
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ aux-build:dep.rs

// test for #121151

#![allow(incomplete_features)]
#![feature(unnamed_fields)]

extern crate dep;

#[repr(C)]
struct A {
    a: u8,
}

enum BadEnum {
    A,
    B,
}

#[repr(C)]
enum BadEnum2 {
    A,
    B,
}

type MyStruct = A;
type MyI32 = i32;

#[derive(Debug)]
struct L {
    _: i32, //~ ERROR unnamed fields can only have struct or union types
    _: MyI32, //~ ERROR unnamed fields can only have struct or union types
    _: BadEnum, //~ ERROR unnamed fields can only have struct or union types
    _: BadEnum2, //~ ERROR unnamed fields can only have struct or union types
    _: MyStruct,
    _: dep::BadStruct, //~ ERROR named type of unnamed field must have `#[repr(C)]` representation
    _: dep::BadEnum, //~ ERROR unnamed fields can only have struct or union types
    _: dep::BadEnum2, //~ ERROR unnamed fields can only have struct or union types
    _: dep::BadAlias, //~ ERROR unnamed fields can only have struct or union types
    _: dep::GoodAlias,
    _: dep::GoodStruct,
}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.78.0-nightly (23a3d777c 2024-02-18)
binary: rustc
commit-hash: 23a3d777c8a95715977608c827de63e7738fa228
commit-date: 2024-02-18
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `MyI32` in this scope
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:6:8
  |
6 |     _: MyI32,
  |        ^^^^^ not found in this scope

error[E0412]: cannot find type `BadEnum` in this scope
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:7:8
  |
7 |     _: BadEnum,
  |        ^^^^^^^ not found in this scope

error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:5:5
  |
5 |     _: i32,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-02-18; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:6:5
  |
6 |     _: MyI32,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-02-18; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:7:5
  |
7 |     _: BadEnum,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-02-18; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs`

error: unnamed fields can only have struct or union types
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:5:5
  |
5 |     _: i32,
  |     ^^^^^^

error: unnamed fields can only have struct or union types
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:6:5
  |
6 |     _: MyI32,
  |     ^^^^^^^^

error: unnamed fields can only have struct or union types
 --> /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:7:5
  |
7 |     _: BadEnum,
  |     ^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:797:49:
expect Adt for unnamed field
stack backtrace:
   0:     0x7fee0be69c66 - std::backtrace_rs::backtrace::libunwind::trace::h4068c8c17ac2de87
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fee0be69c66 - std::backtrace_rs::backtrace::trace_unsynchronized::h4580377505c55c9d
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fee0be69c66 - std::sys_common::backtrace::_print_fmt::hee20b5c666b58216
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fee0be69c66 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha4ad425535c00d08
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fee0beba28c - core::fmt::rt::Argument::fmt::h0839985d975a9d4b
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/fmt/rt.rs:142:9
   5:     0x7fee0beba28c - core::fmt::write::h90514da5b3f483e8
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fee0be5d60f - std::io::Write::write_fmt::h203f53b20388cfaa
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/io/mod.rs:1846:15
   7:     0x7fee0be69a14 - std::sys_common::backtrace::_print::h2f913a97733fa87b
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fee0be69a14 - std::sys_common::backtrace::print::h99f997f501c28480
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fee0be6c75b - std::panicking::default_hook::{{closure}}::he40fc06be54c384c
  10:     0x7fee0be6c4a9 - std::panicking::default_hook::h3571ea97747a580b
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/panicking.rs:292:9
  11:     0x7fee08c1e53c - std[215f9b68e873486f]::panicking::update_hook::<alloc[be5ff64dafe89243]::boxed::Box<rustc_driver_impl[ff846aa700ca0662]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fee0be6cec0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1e7c347d2e3bb2ce
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/alloc/src/boxed.rs:2030:9
  13:     0x7fee0be6cec0 - std::panicking::rust_panic_with_hook::haa768baff731dd68
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/panicking.rs:785:13
  14:     0x7fee0be6cc02 - std::panicking::begin_panic_handler::{{closure}}::hd076226a093426e6
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/panicking.rs:659:13
  15:     0x7fee0be6a146 - std::sys_common::backtrace::__rust_end_short_backtrace::h5f6128247f895926
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fee0be6c934 - rust_begin_unwind
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/panicking.rs:647:5
  17:     0x7fee0beb6795 - core::panicking::panic_fmt::ha3b35be81f6e71fb
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/panicking.rs:72:14
  18:     0x7fee0beb6961 - core::panicking::panic_display::h0bc330b58b3ed652
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/panicking.rs:196:5
  19:     0x7fee0beb654b - core::panicking::panic_str::hb3484e129df4bb42
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/panicking.rs:171:5
  20:     0x7fee0beb654b - core::option::expect_failed::h7f457612ea919a01
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/core/src/option.rs:1993:5
  21:     0x7fee0a6363f2 - rustc_hir_analysis[6e9724bb0c265329]::collect::find_field
  22:     0x7fee0a63619f - rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::find_field::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 4usize]>>
  23:     0x7fee0a636161 - <rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::find_field::dynamic_query::{closure#2} as core[694f794f8b0567e]::ops::function::FnOnce<(rustc_middle[1a787087d433af5e]::ty::context::TyCtxt, (rustc_span[e2cb3716bc025bf2]::def_id::DefId, rustc_span[e2cb3716bc025bf2]::symbol::Ident))>>::call_once
  24:     0x7fee0a635550 - rustc_query_system[7a228a9eb6f8b90e]::query::plumbing::try_execute_query::<rustc_query_impl[40f1c38ec7f0fe8b]::DynamicConfig<rustc_query_system[7a228a9eb6f8b90e]::query::caches::DefaultCache<(rustc_span[e2cb3716bc025bf2]::def_id::DefId, rustc_span[e2cb3716bc025bf2]::symbol::Ident), rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::QueryCtxt, false>
  25:     0x7fee0a6352a2 - rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::find_field::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7fee0a1275ae - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_field
  27:     0x7fee0a87bbbc - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7fee0a87b9b0 - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7fee0a927394 - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_argument_types
  30:     0x7fee0a7315af - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_call
  31:     0x7fee0a87ad6c - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7fee0a36d609 - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_block_with_expected
  33:     0x7fee0a87b2c2 - <rustc_hir_typeck[7e2a8938242ae40f]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7fee0a868ac8 - rustc_hir_typeck[7e2a8938242ae40f]::check::check_fn
  35:     0x7fee09f89ef0 - rustc_hir_typeck[7e2a8938242ae40f]::typeck
  36:     0x7fee09f89199 - rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7fee09fe81f0 - rustc_query_system[7a228a9eb6f8b90e]::query::plumbing::try_execute_query::<rustc_query_impl[40f1c38ec7f0fe8b]::DynamicConfig<rustc_query_system[7a228a9eb6f8b90e]::query::caches::VecCache<rustc_span[e2cb3716bc025bf2]::def_id::LocalDefId, rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::QueryCtxt, false>
  38:     0x7fee09fe7dcc - rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7fee09fe7562 - <rustc_middle[1a787087d433af5e]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[6e9724bb0c265329]::check_crate::{closure#5}>::{closure#0}
  40:     0x7fee09fe60a3 - rustc_hir_analysis[6e9724bb0c265329]::check_crate
  41:     0x7fee0a8aadd3 - rustc_interface[ae2941ea76b15824]::passes::analysis
  42:     0x7fee0a8aaa29 - rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 1usize]>>
  43:     0x7fee0ab7b8a5 - rustc_query_system[7a228a9eb6f8b90e]::query::plumbing::try_execute_query::<rustc_query_impl[40f1c38ec7f0fe8b]::DynamicConfig<rustc_query_system[7a228a9eb6f8b90e]::query::caches::SingleCache<rustc_middle[1a787087d433af5e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[40f1c38ec7f0fe8b]::plumbing::QueryCtxt, false>
  44:     0x7fee0ab7b609 - rustc_query_impl[40f1c38ec7f0fe8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7fee0ab8ec56 - rustc_interface[ae2941ea76b15824]::interface::run_compiler::<core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>, rustc_driver_impl[ff846aa700ca0662]::run_compiler::{closure#0}>::{closure#0}
  46:     0x7fee0adbef06 - std[215f9b68e873486f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ae2941ea76b15824]::util::run_in_thread_with_globals<rustc_interface[ae2941ea76b15824]::util::run_in_thread_pool_with_globals<rustc_interface[ae2941ea76b15824]::interface::run_compiler<core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>, rustc_driver_impl[ff846aa700ca0662]::run_compiler::{closure#0}>::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>
  47:     0x7fee0adbed32 - <<std[215f9b68e873486f]::thread::Builder>::spawn_unchecked_<rustc_interface[ae2941ea76b15824]::util::run_in_thread_with_globals<rustc_interface[ae2941ea76b15824]::util::run_in_thread_pool_with_globals<rustc_interface[ae2941ea76b15824]::interface::run_compiler<core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>, rustc_driver_impl[ff846aa700ca0662]::run_compiler::{closure#0}>::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[694f794f8b0567e]::result::Result<(), rustc_span[e2cb3716bc025bf2]::ErrorGuaranteed>>::{closure#1} as core[694f794f8b0567e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7fee0be76005 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8bfba6e4cba56ce0
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/alloc/src/boxed.rs:2016:9
  49:     0x7fee0be76005 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf738f5a32d063c18
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/alloc/src/boxed.rs:2016:9
  50:     0x7fee0be76005 - std::sys::pal::unix::thread::Thread::new::thread_start::h97194e05728842d4
                               at /rustc/23a3d777c8a95715977608c827de63e7738fa228/library/std/src/sys/pal/unix/thread.rs:108:17
  51:     0x7fee05caa9eb - <unknown>
  52:     0x7fee05d2e7cc - <unknown>
  53:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (23a3d777c 2024-02-18) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [find_field] find the index of maybe nested field `_` in `L`
#1 [typeck] type-checking `<impl at /tmp/icemaker_global_tempdir.ARGn7VxzHBhS/rustc_testrunner_tmpdir_reporting.hJYasVkFeKoS/mvce.rs:3:10: 3:15>::fmt`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 9 previous errors

Some errors have detailed explanations: E0412, E0601, E0658.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

### LINKED ISSUE #121299: ICE: `Anonymous structs or unions cannot be type parameters`
snippet:
````rust
#[derive(Eq)]
struct D {
    _: union {
    },
}


````

Version information
````
rustc 1.78.0-nightly (bea5bebf3 2024-02-19)
binary: rustc
commit-hash: bea5bebf3defc56e5e3446b4a95c685dbb885fd3
commit-date: 2024-02-19
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_builtin_macros/src/deriving/mod.rs:127:5:
Anonymous structs or unions cannot be type parameters
stack backtrace:
   0:     0x7f36a6c70b56 - std::backtrace_rs::backtrace::libunwind::trace::h3a158c8f16516afb
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f36a6c70b56 - std::backtrace_rs::backtrace::trace_unsynchronized::ha89664cca04bb36e
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f36a6c70b56 - std::sys_common::backtrace::_print_fmt::h03800d086403b62e
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f36a6c70b56 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h91d502aabce8c547
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f36a6cc1b0c - core::fmt::rt::Argument::fmt::h99a2d1e221afec6c
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f36a6cc1b0c - core::fmt::write::h97a5ad4b86c9e005
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f36a6c654bf - std::io::Write::write_fmt::h2b40f89315aa23ff
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/io/mod.rs:1846:15
   7:     0x7f36a6c70904 - std::sys_common::backtrace::_print::h4787d964e00e361c
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f36a6c70904 - std::sys_common::backtrace::print::hbf94f54b49f22c72
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f36a6c7364b - std::panicking::default_hook::{{closure}}::h09f29dc972c775e7
  10:     0x7f36a6c73399 - std::panicking::default_hook::hdb43b973c97e30a9
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/panicking.rs:292:9
  11:     0x7f36a3a2c5cc - std[e3016e56fde417e8]::panicking::update_hook::<alloc[26f96968629a1477]::boxed::Box<rustc_driver_impl[1d2aada9a967b964]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f36a6c73db0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7d80339b83881141
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f36a6c73db0 - std::panicking::rust_panic_with_hook::ha4f031997107b610
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/panicking.rs:786:13
  14:     0x7f36a6c73ab9 - std::panicking::begin_panic_handler::{{closure}}::h556d855f34b40d5b
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/panicking.rs:652:13
  15:     0x7f36a6c71036 - std::sys_common::backtrace::__rust_end_short_backtrace::hcfcfe13416eb9e24
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f36a6c73824 - rust_begin_unwind
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/panicking.rs:648:5
  17:     0x7f36a6cbe015 - core::panicking::panic_fmt::h817e0acf16f85c30
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/core/src/panicking.rs:72:14
  18:     0x7f36a57ea1dc - rustc_builtin_macros[20656e6096520b61]::deriving::assert_ty_bounds
  19:     0x7f36a57e8d7a - rustc_builtin_macros[20656e6096520b61]::deriving::eq::expand_deriving_eq::{closure#0}
  20:     0x7f36a54ac3cc - <rustc_builtin_macros[20656e6096520b61]::deriving::generic::TraitDef>::expand_struct_def
  21:     0x7f36a57e5011 - <rustc_builtin_macros[20656e6096520b61]::deriving::generic::TraitDef>::expand_ext
  22:     0x7f36a5875d17 - rustc_builtin_macros[20656e6096520b61]::deriving::eq::expand_deriving_eq
  23:     0x7f36a54aa052 - <rustc_builtin_macros[20656e6096520b61]::deriving::BuiltinDerive as rustc_expand[a0d1a98eef577773]::base::MultiItemModifier>::expand
  24:     0x7f36a55b8447 - <rustc_expand[a0d1a98eef577773]::expand::MacroExpander>::fully_expand_fragment
  25:     0x7f36a55b5ef7 - <rustc_expand[a0d1a98eef577773]::expand::MacroExpander>::expand_crate
  26:     0x7f36a5ad0092 - rustc_interface[37c35c6dbc63475a]::passes::resolver_for_lowering
  27:     0x7f36a5acf567 - rustc_query_impl[2d5ef8d54471ac61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d5ef8d54471ac61]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3a9dcbdbfc28ae03]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7f36a5996e4e - rustc_query_system[1991136b97b46e9d]::query::plumbing::try_execute_query::<rustc_query_impl[2d5ef8d54471ac61]::DynamicConfig<rustc_query_system[1991136b97b46e9d]::query::caches::SingleCache<rustc_middle[3a9dcbdbfc28ae03]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[2d5ef8d54471ac61]::plumbing::QueryCtxt, false>
  29:     0x7f36a59965cb - rustc_query_impl[2d5ef8d54471ac61]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f36a595df14 - rustc_interface[37c35c6dbc63475a]::interface::run_compiler::<core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>, rustc_driver_impl[1d2aada9a967b964]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7f36a5bbf305 - std[e3016e56fde417e8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[37c35c6dbc63475a]::util::run_in_thread_with_globals<rustc_interface[37c35c6dbc63475a]::util::run_in_thread_pool_with_globals<rustc_interface[37c35c6dbc63475a]::interface::run_compiler<core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>, rustc_driver_impl[1d2aada9a967b964]::run_compiler::{closure#0}>::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>
  32:     0x7f36a5bbf132 - <<std[e3016e56fde417e8]::thread::Builder>::spawn_unchecked_<rustc_interface[37c35c6dbc63475a]::util::run_in_thread_with_globals<rustc_interface[37c35c6dbc63475a]::util::run_in_thread_pool_with_globals<rustc_interface[37c35c6dbc63475a]::interface::run_compiler<core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>, rustc_driver_impl[1d2aada9a967b964]::run_compiler::{closure#0}>::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7975d3e35f006c71]::result::Result<(), rustc_span[64c55662242a9f4e]::ErrorGuaranteed>>::{closure#1} as core[7975d3e35f006c71]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f36a6c7d785 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf5fa3c582f259ae
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/alloc/src/boxed.rs:2016:9
  34:     0x7f36a6c7d785 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h57a62cffc212fbb2
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/alloc/src/boxed.rs:2016:9
  35:     0x7f36a6c7d785 - std::sys::pal::unix::thread::Thread::new::thread_start::hf5c20164f3984a87
                               at /rustc/bea5bebf3defc56e5e3446b4a95c685dbb885fd3/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7f36a0aaa9eb - <unknown>
  37:     0x7f36a0b2e7cc - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (bea5bebf3 2024-02-19) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack

```

</p>
</details>

### LINKED ISSUE #121722: ICE: ` Unexpected TyKind in FieldUniquenessCheckContext::check_field_in_nested_adt()`
auto-reduced (treereduce-rust):
````rust




#[repr(C)]
struct Foo {
    _: u8,
}



struct Bar {
    _: union {
        a: u8,
    },
}




#[repr(C)]




#[main(C)]




#[repr(C)]
union C {
    _: struct {
        _: union {
            
            ,

            
            , 
            
             ,
            
            _: {
        _: struct  ,
            },
            
            _: Foo, 
            _: Bar, 
            
            _: struct ,
        },

        
          union  ,
    },
    
      union ,
}



#[repr(C)]
struct D {
    
    _: Foo,

    
    a: u8, 
    
    _: union {
        a: u8, 
    }  union ,
}




union D2 {
    
    _: Bar,

    
    a: u8, 
    
    _: union {
        a: u8, 
    }  union ,
}



#[repr(C)]
struct E {
    _: struct {
        
        ,

        
        , 
        
          union  ,
    },

    
      union ,
}


#[repr(C)]

union E2 {
    _: struct {
        
        ,

        
        , 
        
          union  ,
    },

    
      union ,
}




````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![allow(incomplete_features)]
#![feature(unnamed_fields)]

#[derive(Clone, Copy)]
#[repr(C)]
struct Foo {
    _: u8,
}

#[derive(Clone, Copy)]
#[derive(Clone, Copy)]
struct Bar {
    _: union {
        a: u8,
    },
}


// duplicated with a normal field
#[derive(Clone, Copy)]
#[repr(C)]
union E {
    // referent field
    a: u8,

    // normal field
    a: u8, //~ ERROR field `a` is already declared [E0124]
    // nested field
    _: struct {
        a: u8, //~ ERROR field `a` is already declared [E0124]
        incomplete_features: u8, //~ ERROR field `a` is already declared [E0124]
    },
    // more nested field
    _: union {
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
    },
    // nested field in a named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: struct {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a nested field
#[derive(Clone, Copy)]
#[main(C)]
struct B {
    _: union {
        // referent field
        _: Foo,

        // normal field (within the same anonymous adt)
        a: u8, //~ ERROR field `a` is already declared [E0124]
        // nested field (within the same anonymous adt)
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
        // more nested field (within the same anonymous adt)
        _: union {
            _: struct {
                a: u8, //~ ERROR field `a` is already declared [E0124]
            },
        },
        // nested field in a named adt (within the same anonymous adt)
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
        // nested field in a named adt in an anoymous adt (within the same anonymous adt)
        _: struct {
            _: Foo, //~ ERROR field `a` is already declared
            _: Bar, //~ ERROR field `a` is already declared
        },
    },

    // normal field
    a: u8, //~ ERROR field `a` is already declared [E0124]
    // nested field
    _: struct {
        a: main, //~ ERROR field `a` is already declared [E0124]
    },
    // more nested field
    _: union {
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
    },
    // nested field in a named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, // nested field in a named adt
    // nested field in a named adt in an anoymous adt
    _: struct {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a more nested field
#[derive(Clone, Copy)]
#[repr(C)]
union C {
    _: struct {
        _: union {
            // referent field
            a: u8,

            // normal field (within the same anonymous adt)
            a: u8, //~ ERROR field `a` is already declared [E0124]
            // nested field (within the same anonymous adt)
            _: struct {
                a: u8, //~ ERROR field `a` is already declared [E0124]
            },
            // more nested field (within the same anonymous adt)
            _: {
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
    } {
                _: struct {
                    a: u8, //~ ERROR field `a` is already declared [E0124]
                },
            },
            // nested field in a named adt (within the same anonymous adt)
            _: Foo, //~ ERROR field `a` is already declared
            _: Bar, //~ ERROR field `a` is already declared
            // nested field in a named adt in an anoymous adt (within the same anonymous adt)
            _: struct {
                _: Foo, //~ ERROR field `a` is already declared
                _: Bar, //~ ERROR field `a` is already declared
            },
        },

        // normal field (within the direct outer anonymous adt)
        a: u8, //~ ERROR field `a` is already declared [E0124]
        // nested field (within the direct outer anonymous adt)
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
        // more nested field (within the direct outer anonymous adt)
        _: union {
        _: union {
            a: u8, //~ ERROR field `a` is already declared
        },
    },
        // nested field in a named adt (within the direct outer anonymous adt)
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
        // nested field in a named adt in an anoymous adt (within the direct outer anonymous adt)
        _: struct {
            _: Foo, //~ ERROR field `a` is already declared
            _: Bar, //~ ERROR field `a` is already declared
        },
    },
    // normal field
    a: u8, //~ ERROR field `a` is already declared [E0124]
    // nested field
    _: union {
        a: u8, //~ ERROR field `a` is already declared [E0124]
    },
    // more nested field
    _: struct {
        _: union {
            a: u8, //~ ERROR field `a` is already declared [E0124]
        },
    },
    // nested field in a named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: union {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a nested field in a named adt
#[derive(Clone, Copy)]
#[repr(C)]
struct D {
    // referent field `a`
    _: Foo,

    // normal field
    a: u8, //~ ERROR field `a` is already declared
    // nested field
    _: union {
        a: u8, //~ ERROR field `a` is already declared
    },
    // more nested field
    _: struct {
        _: union {
            a: u8, //~ ERROR field `a` is already declared
        },
    },
    // nested field in another named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: union {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a nested field in a nested field of a named adt
#[allow(incomplete_features)]
#[repr(derive)]
union D2 {
    // referent field `a`
    _: Bar,

    // normal field
    a: u8, //~ ERROR field `a` is already declared
    // nested field
    _: union {
        a: u8, //~ ERROR field `a` is already declared
    },
    // more nested field
    _: struct {
        _: union {
            a: u8, //~ ERROR field `a` is already declared
        },
    },
    // nested field in another named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: union {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a nested field in a named adt in an anonymous adt
#[derive(Clone, Copy)]
#[repr(C)]
struct E {
    _: struct {
        // referent field `a`
        _: Foo,

        // normal field (within the same anonymous adt)
        a: u8, //~ ERROR field `a` is already declared
        // nested field (within the same anonymous adt)
        _: struct {
            a: u8, //~ ERROR field `a` is already declared
        },
        // more nested field (within the same anonymous adt)
        _: union {
            _: struct {
                a: u8a: //~ ERROR field `a` is already declared
            },
        },
        // nested field in a named adt (within the same anonymous adt)
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
        // nested field in a named adt in an anoymous adt (within the same anonymous adt)
        _: struct {
            _: Foo, //~ ERROR field `a` is already declared
            _: Bar, //~ ERROR field `a` is already declared
        },
    },

    // normal field
    a: u8, //~ ERROR field `a` is already declared
    // nested field
    _: union {
        incomplete_features: u8, //~ ERROR field `a` is already declared
    },
    // more nested field
    _: struct {
                _: Foo, //~ ERROR field `a` is already declared
                _: Bar, //~ ERROR field `a` is already declared
            },
    // nested field in another named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: union {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

// duplicated with a nested field in a named adt in an anonymous adt
#[repr(C)]
#[derive(Clone, Copy)]
union E2 {
    _: struct {
        // referent field `a`
        _: Bar,

        // normal field (within the same anonymous adt)
        a: u8, //~ ERROR field `a` is already declared
        // nested field (within the same anonymous adt)
        _: struct {
            a: u8, //~ ERROR field `a` is already declared [E0124]
    // nested field
    _: union {
        a: u8, //~ ERROR field `a` is already declared [E0124]
    },
    // more nested field
    _: struct u8, //~ ERROR field `a` is already declared
        },
        // more nested field (within the same anonymous adt)
        _: union {
            _: struct {
                u8: u8, //~ ERROR field `a` is already declared
            },
        },
        // nested field in a named adt (within the same anonymous adt)
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
        // nested field in a named adt in an anoymous adt (within the same anonymous adt)
        _: struct {
            _: Foo, //~ ERROR field `a` is already declared
            _: Bar, //~ ERROR field `a` is already declared
        },
    },

    // normal field
    a: u8, //~ ERROR field `a` is already declared
    // nested field
    _: union {
        a: u8, //~ ERROR field `a` is already declared
    },
    // more nested field
    _: struct {
        _: union {
            a: u8, //~ ERROR field `a` is already declared
        },
    },
    // nested field in another named adt
    _: Foo, //~ ERROR field `a` is already declared
    _: Bar, //~ ERROR field `a` is already declared
    // nested field in a named adt in an anoymous adt
    _: union {
        _: Foo, //~ ERROR field `a` is already declared
        _: Bar, //~ ERROR field `a` is already declared
    },
}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.78.0-nightly (ef324565d 2024-02-27)
binary: rustc
commit-hash: ef324565d071c6d7e2477a195648549e33d6a465
commit-date: 2024-02-27
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected identifier, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:36:13
   |
34 |         _: union {
   |            ----- while parsing this union
35 |             
36 |             ,
   |             ^ expected identifier

error: expected `:`, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:54:18
   |
33 |     _: struct {
   |        ------ while parsing this struct
...
54 |           union  ,
   |                  ^ expected `:`

error: expected `:`, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:57:13
   |
32 | union C {
   |       - while parsing this union
...
57 |       union ,
   |             ^ expected `:`

error: expected `,`, or `}`, found `union`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:72:6
   |
72 |     }  union ,
   |      ^ help: try adding a comma: `,`

error: expected `:`, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:72:14
   |
63 | struct D {
   |        - while parsing this struct
...
72 |     }  union ,
   |              ^ expected `:`

error: expected `,`, or `}`, found `union`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:87:6
   |
87 |     }  union ,
   |      ^ help: try adding a comma: `,`

error: expected `:`, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:87:14
   |
78 | union D2 {
   |       -- while parsing this union
...
87 |     }  union ,
   |              ^ expected `:`

error: expected identifier, found `,`
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:96:9
   |
94 |     _: struct {
   |        ------ while parsing this struct
95 |         
96 |         ,
   |         ^ expected identifier

error: expected `:`, found `,`
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:105:13
    |
93  | struct E {
    |        - while parsing this struct
...
105 |       union ,
    |             ^ expected `:`

error: expected identifier, found `,`
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:114:9
    |
112 |     _: struct {
    |        ------ while parsing this struct
113 |         
114 |         ,
    |         ^ expected identifier

error: expected `:`, found `,`
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:123:13
    |
111 | union E2 {
    |       -- while parsing this union
...
123 |       union ,
    |             ^ expected `:`

error: cannot find attribute `main` in this scope
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:26:3
   |
26 | #[main(C)]
   |   ^^^^

error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:7:5
  |
7 |     _: u8,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:13:5
   |
13 |     _: union {
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:13:8
   |
13 |       _: union {
   |  ________^
14 | |         a: u8,
15 | |     },
   | |_____^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:33:5
   |
33 |     _: struct {
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:34:9
   |
34 |         _: union {
   |         ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:34:12
   |
34 |           _: union {
   |  ____________^
35 | |             
36 | |             ,
37 | |
...  |
50 | |             _: struct ,
51 | |         },
   | |_________^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:33:8
   |
33 |       _: struct {
   |  ________^
34 | |         _: union {
35 | |             
36 | |             ,
...  |
54 | |           union  ,
55 | |     },
   | |_____^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:65:5
   |
65 |     _: Foo,
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:70:5
   |
70 |     _: union {
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:70:8
   |
70 |       _: union {
   |  ________^
71 | |         a: u8, 
72 | |     }  union ,
   | |_____^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:80:5
   |
80 |     _: Bar,
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:85:5
   |
85 |     _: union {
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:85:8
   |
85 |       _: union {
   |  ________^
86 | |         a: u8, 
87 | |     }  union ,
   | |_____^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
  --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:94:5
   |
94 |     _: struct {
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
   = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:94:8
    |
94  |       _: struct {
    |  ________^
95  | |         
96  | |         ,
97  | |
...   |
101 | |           union  ,
102 | |     },
    | |_____^
    |
    = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
    = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
    = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:112:5
    |
112 |     _: struct {
    |     ^
    |
    = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
    = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
    = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:112:8
    |
112 |       _: struct {
    |  ________^
113 | |         
114 | |         ,
115 | |
...   |
119 | |           union  ,
120 | |     },
    | |_____^
    |
    = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
    = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
    = note: this compiler was built on 2024-02-27; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
   --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:124:2
    |
124 | }
    |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs`

error: internal compiler error: compiler/rustc_hir_analysis/src/collect.rs:906:32: Unexpected TyKind in FieldUniquenessCheckContext::check_field_in_nested_adt(): u8
 --> /tmp/icemaker_global_tempdir.8RVjYmQMzzwG/rustc_testrunner_tmpdir_reporting.F427u8SIf55Q/mvce.rs:7:5
  |
7 |     _: u8,
  |     ^^^^^

thread 'rustc' panicked at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7fd84e78cc46 - std::backtrace_rs::backtrace::libunwind::trace::hcd31ff68bb8eb3c8
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fd84e78cc46 - std::backtrace_rs::backtrace::trace_unsynchronized::h14d76bd5509bf096
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd84e78cc46 - std::sys_common::backtrace::_print_fmt::hccb1d92c773f2e33
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fd84e78cc46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haec236aae0c71094
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd84e7ddbcc - core::fmt::rt::Argument::fmt::hfe5c81d163ead061
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/core/src/fmt/rt.rs:142:9
   5:     0x7fd84e7ddbcc - core::fmt::write::hae70f68f90cda8d6
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fd84e7814cf - std::io::Write::write_fmt::h2920683ffc23d04e
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/io/mod.rs:1846:15
   7:     0x7fd84e78c9f4 - std::sys_common::backtrace::_print::h5625fa16158ef797
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fd84e78c9f4 - std::sys_common::backtrace::print::h736502c57d395fe5
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd84e78f73b - std::panicking::default_hook::{{closure}}::hd092ecfc821f695b
  10:     0x7fd84e78f489 - std::panicking::default_hook::h7f251f2c2a8aa52c
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/panicking.rs:292:9
  11:     0x7fd8516a5d3c - std[578157ee06130f18]::panicking::update_hook::<alloc[1f5b0d5bc2928dda]::boxed::Box<rustc_driver_impl[58539505cbc2faf7]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fd84e78fea0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc774e046b4082d87
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/alloc/src/boxed.rs:2030:9
  13:     0x7fd84e78fea0 - std::panicking::rust_panic_with_hook::h50c9145ee7057605
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/panicking.rs:783:13
  14:     0x7fd8516d1d74 - std[578157ee06130f18]::panicking::begin_panic::<rustc_errors[2100e50554992a1d]::ExplicitBug>::{closure#0}
  15:     0x7fd8516ce9c6 - std[578157ee06130f18]::sys_common::backtrace::__rust_end_short_backtrace::<std[578157ee06130f18]::panicking::begin_panic<rustc_errors[2100e50554992a1d]::ExplicitBug>::{closure#0}, !>
  16:     0x7fd8516ca186 - std[578157ee06130f18]::panicking::begin_panic::<rustc_errors[2100e50554992a1d]::ExplicitBug>
  17:     0x7fd8516db8d1 - <rustc_errors[2100e50554992a1d]::diagnostic::BugAbort as rustc_errors[2100e50554992a1d]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fd851780ac0 - rustc_middle[2ebf57413533262e]::util::bug::opt_span_bug_fmt::<rustc_span[20f1163f305bb5ee]::span_encoding::Span>::{closure#0}
  19:     0x7fd8517816ba - rustc_middle[2ebf57413533262e]::ty::context::tls::with_opt::<rustc_middle[2ebf57413533262e]::util::bug::opt_span_bug_fmt<rustc_span[20f1163f305bb5ee]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7fd85176ab78 - rustc_middle[2ebf57413533262e]::ty::context::tls::with_context_opt::<rustc_middle[2ebf57413533262e]::ty::context::tls::with_opt<rustc_middle[2ebf57413533262e]::util::bug::opt_span_bug_fmt<rustc_span[20f1163f305bb5ee]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7fd851766f24 - rustc_middle[2ebf57413533262e]::util::bug::span_bug_fmt::<rustc_span[20f1163f305bb5ee]::span_encoding::Span>
  22:     0x7fd8517d497b - <rustc_hir_analysis[b9c969b446149ad8]::collect::FieldUniquenessCheckContext>::check_field_in_nested_adt
  23:     0x7fd852f82f05 - rustc_hir_analysis[b9c969b446149ad8]::collect::convert_variant
  24:     0x7fd852f8275e - rustc_hir_analysis[b9c969b446149ad8]::collect::adt_def
  25:     0x7fd852a8b4d5 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::adt_def::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7fd852a8bba0 - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::DefIdCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  27:     0x7fd852a8aea2 - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::adt_def::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7fd852c3dc52 - rustc_middle[2ebf57413533262e]::query::plumbing::query_get_at::<rustc_query_system[cf6fea66217b4faa]::query::caches::DefIdCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 8usize]>>>
  29:     0x7fd853441853 - rustc_hir_analysis[b9c969b446149ad8]::outlives::inferred_outlives_crate
  30:     0x7fd8534406f0 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::inferred_outlives_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7fd8537bbe0e - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::SingleCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  32:     0x7fd8537bc8a0 - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::inferred_outlives_crate::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7fd852d4fae3 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::inferred_outlives_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 16usize]>>
  34:     0x7fd852d4e641 - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::DefIdCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  35:     0x7fd852d4e35e - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::inferred_outlives_of::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fd852afd455 - rustc_hir_analysis[b9c969b446149ad8]::collect::predicates_defined_on
  37:     0x7fd852afd2a1 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::predicates_defined_on::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 24usize]>>
  38:     0x7fd852afd289 - <rustc_query_impl[ba88ac09c9d7b12d]::query_impl::predicates_defined_on::dynamic_query::{closure#2} as core[6cbd71b2db6ebc95]::ops::function::FnOnce<(rustc_middle[2ebf57413533262e]::ty::context::TyCtxt, rustc_span[20f1163f305bb5ee]::def_id::DefId)>>::call_once
  39:     0x7fd852afc566 - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::DefIdCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  40:     0x7fd852afc0a0 - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::predicates_defined_on::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7fd852afb08c - rustc_hir_analysis[b9c969b446149ad8]::collect::predicates_of::predicates_of
  42:     0x7fd852afaf93 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 24usize]>>
  43:     0x7fd852afc581 - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::DefIdCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  44:     0x7fd852afc17e - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7fd852d9542a - <rustc_hir_analysis[b9c969b446149ad8]::collect::CollectItemTypesVisitor as rustc_hir[2b58f08a8a598f50]::intravisit::Visitor>::visit_item
  46:     0x7fd852d946ea - rustc_hir_analysis[b9c969b446149ad8]::collect::collect_mod_item_types
  47:     0x7fd852d94677 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 0usize]>>
  48:     0x7fd85356edad - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::DefaultCache<rustc_span[20f1163f305bb5ee]::def_id::LocalModDefId, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  49:     0x7fd85356e8d7 - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  50:     0x7fd8532c4b28 - rustc_hir_analysis[b9c969b446149ad8]::check_crate
  51:     0x7fd853565bef - rustc_interface[549d5cba17650390]::passes::analysis
  52:     0x7fd853565859 - rustc_query_impl[ba88ac09c9d7b12d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba88ac09c9d7b12d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 1usize]>>
  53:     0x7fd853739325 - rustc_query_system[cf6fea66217b4faa]::query::plumbing::try_execute_query::<rustc_query_impl[ba88ac09c9d7b12d]::DynamicConfig<rustc_query_system[cf6fea66217b4faa]::query::caches::SingleCache<rustc_middle[2ebf57413533262e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ba88ac09c9d7b12d]::plumbing::QueryCtxt, false>
  54:     0x7fd853739089 - rustc_query_impl[ba88ac09c9d7b12d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  55:     0x7fd853740c16 - rustc_interface[549d5cba17650390]::interface::run_compiler::<core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>, rustc_driver_impl[58539505cbc2faf7]::run_compiler::{closure#0}>::{closure#0}
  56:     0x7fd8539e7dc5 - std[578157ee06130f18]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[549d5cba17650390]::util::run_in_thread_with_globals<rustc_interface[549d5cba17650390]::util::run_in_thread_pool_with_globals<rustc_interface[549d5cba17650390]::interface::run_compiler<core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>, rustc_driver_impl[58539505cbc2faf7]::run_compiler::{closure#0}>::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>
  57:     0x7fd8539e7bf2 - <<std[578157ee06130f18]::thread::Builder>::spawn_unchecked_<rustc_interface[549d5cba17650390]::util::run_in_thread_with_globals<rustc_interface[549d5cba17650390]::util::run_in_thread_pool_with_globals<rustc_interface[549d5cba17650390]::interface::run_compiler<core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>, rustc_driver_impl[58539505cbc2faf7]::run_compiler::{closure#0}>::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6cbd71b2db6ebc95]::result::Result<(), rustc_span[20f1163f305bb5ee]::ErrorGuaranteed>>::{closure#1} as core[6cbd71b2db6ebc95]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7fd84e799875 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbfe673f8fb6b1f32
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/alloc/src/boxed.rs:2016:9
  59:     0x7fd84e799875 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h91a1aab6b746134a
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/alloc/src/boxed.rs:2016:9
  60:     0x7fd84e799875 - std::sys::pal::unix::thread::Thread::new::thread_start::h8e91ee627a6e8489
                               at /rustc/ef324565d071c6d7e2477a195648549e33d6a465/library/std/src/sys/pal/unix/thread.rs:108:17
  61:     0x7fd84e58155a - <unknown>
  62:     0x7fd84e5fea3c - <unknown>
  63:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (ef324565d 2024-02-27) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [adt_def] computing ADT definition for `D`
#1 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#2 [inferred_outlives_of] computing inferred outlives predicates of `Foo`
#3 [predicates_defined_on] computing predicates of `Foo`
#4 [predicates_of] computing predicates of `Foo`
#5 [collect_mod_item_types] collecting item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 31 previous errors

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #121799: ICE `expect Adt for unnamed field`
### Code

```Rust
struct S {
    _: str
}

fn func(a: S)
{
    let _x = a.f;
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-msvc
release: 1.78.0-dev
LLVM version: 18.1.0
```

### Error output

```
error[E0658]: unnamed fields are not yet fully implemented
  --> ../121757-ice-self-is-struct.rs:21:5
   |
21 |     _: str
   |     ^
   |
   = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
   = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable

error: struct with unnamed fields must have `#[repr(C)]` representation
  --> ../121757-ice-self-is-struct.rs:20:1
   |
20 | struct S {
   | ^^^^^^^^ struct `S` defined here
   |
note: unnamed field defined here
  --> ../121757-ice-self-is-struct.rs:21:5
   |
21 |     _: str
   |     ^^^^^^
help: add `#[repr(C)]` to this struct
   |
20 + #[repr(C)]
21 | struct S {
   |

error: unnamed fields can only have struct or union types
  --> ../121757-ice-self-is-struct.rs:21:5
   |
21 |     _: str
   |     ^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_hir_analysis\src\collect.rs:797:49:
expect Adt for unnamed field
stack backtrace:
   0:     0x7ffdd1bed08b - std::backtrace_rs::backtrace::trace_unsynchronized::h43b35a566376d8c0
   1:     0x7ffdd1bb9df6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h69aa329c1eebdd12
   2:     0x7ffdd1bff5fa - core::fmt::write::h43e911a4c8eeaf29
   3:     0x7ffdd1be8b31 - std::io::Write::write_fmt::h8014a09f9dbe746f
   4:     0x7ffdd1bb9c49 - std::sys_common::backtrace::print::h011c44e7584b6317
   5:     0x7ffdd1bb3283 - std::panicking::default_hook::h180ba89712984d0e
   6:     0x7ffdd1bb2ffa - std::panicking::default_hook::h180ba89712984d0e
   7:     0x7ffd30696e0a - RNvXsL_NtCs6iaOUQgAX4G_5alloc5boxedINtB5_3BoxNCNvCsaaGoLZrJT1T_17rustc_driver_impl16install_ice_hook0EINtNtNtCsjpBzhLK3VS9_4core3ops8function2FnTRDG0_IB1D_TRL1_INtNtNtB1J_5panic10panic_info9PanicInfoL0_EEEp6OutputuNtNtB1J_6marker4SyncNtB3s_4SendEL_RB2z_EE
   8:     0x7ffdd1bb36f6 - std::panicking::rust_panic_with_hook::h56cbb5b6fc35c3d1
   9:     0x7ffdd1bb63d8 - std::sys_common::backtrace::__rust_end_short_backtrace::he5effd4f04252cad
  10:     0x7ffdd1bb62ff - std::sys_common::backtrace::__rust_end_short_backtrace::he5effd4f04252cad
  11:     0x7ffdd1bb3366 - rust_begin_unwind
  12:     0x7ffdd1c30527 - core::panicking::panic_fmt::h26fb43be4a0382ff
  13:     0x7ffdd1c3045c - core::option::expect_failed::h3577c8f3edbefcf8
  14:     0x7ffd3295088c - RINvXs0_NtNtNtCsjpBzhLK3VS9_4core4iter8adapters3mapINtB6_3MapINtNtB8_9enumerate9EnumerateINtNtNtBc_5slice4iter4IterNtNtCsef3NXIzrFT9_12rustc_middle2ty8FieldDefEENCNvMNtCs329P7cL7PzQ_11rustc_index5sliceINtB2E_10IndexSliceNtNtCs3QpSQfzdkb7_12rustc_target3ab
  15:     0x7ffd3284d89c - <rustc_hir_analysis[45b4dac900b2c2ce]::collect::ItemCtxt as rustc_hir_analysis[45b4dac900b2c2ce]::astconv::AstConv>::set_tainted_by_errors
  16:     0x7ffd33a409f1 - rustc_query_impl[41ff65b64ab350b4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[41ff65b64ab350b4]::query_impl::find_field::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a5e56af6423dad19]::query::erase::Erased<[u8; 4usize]>>
  17:     0x7ffd3398407f - rustc_query_impl[41ff65b64ab350b4]::query_impl::check_unsafety::encode_query_results
  18:     0x7ffd33ae2ef3 - RINvMs2_NtNtCsebAyhQxexiU_3std6thread5localINtB6_8LocalKeyINtNtCsjpBzhLK3VS9_4core4cell4CellPuEE4withNCINvNtNtNtCsef3NXIzrFT9_12rustc_middle2ty7context3tls13enter_contextNCINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing20execute_job_non_incrINtCs
  19:     0x7ffd33912c3e - RINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing17try_execute_queryINtCs5FiQgzJqBuW_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheTNtNtCsjXm0eGRgiQS_10rustc_span6def_id5DefIdNtNtB2y_6symbol5IdentEINtNtNtCsef3NXIzrFT9_12rustc_middl
  20:     0x7ffd3398d322 - rustc_query_impl[41ff65b64ab350b4]::query_impl::find_field::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7ffd325bd587 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_for_missing_semi
  22:     0x7ffd3262b252 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_kind
  23:     0x7ffd325b58d7 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_coercible_to_type
  24:     0x7ffd326292be - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  25:     0x7ffd325d74df - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_decl_initializer
  26:     0x7ffd325d7718 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_decl_initializer
  27:     0x7ffd325d7a95 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_stmt
  28:     0x7ffd326f0cf2 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}, ()>
  29:     0x7ffd325d7d20 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_block_no_value
  30:     0x7ffd32629d52 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_kind
  31:     0x7ffd325b58d7 - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_coercible_to_type
  32:     0x7ffd326292be - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  33:     0x7ffd325b6e8c - <rustc_hir_typeck[40cfaf708e23f80b]::fn_ctxt::FnCtxt>::check_return_expr
  34:     0x7ffd327aab3c - rustc_hir_typeck[40cfaf708e23f80b]::check::check_fn
  35:     0x7ffd3268eaf2 - rustc_hir_typeck[40cfaf708e23f80b]::typeck_with_fallback::<rustc_hir_typeck[40cfaf708e23f80b]::inspect_typeck::{closure#0}>        
  36:     0x7ffd3259a33e - rustc_hir_typeck[40cfaf708e23f80b]::primary_body_of
  37:     0x7ffd33a5bd2d - rustc_query_impl[41ff65b64ab350b4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[41ff65b64ab350b4]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a5e56af6423dad19]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7ffd339605de - rustc_query_impl[41ff65b64ab350b4]::query_impl::promoted_mir::encode_query_results
  39:     0x7ffd33ae2a44 - RINvMs2_NtNtCsebAyhQxexiU_3std6thread5localINtB6_8LocalKeyINtNtCsjpBzhLK3VS9_4core4cell4CellPuEE4withNCINvNtNtNtCsef3NXIzrFT9_12rustc_middle2ty7context3tls13enter_contextNCINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing20execute_job_non_incrINtCs
  40:     0x7ffd3392f122 - RINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing17try_execute_queryINtCs5FiQgzJqBuW_16rustc_query_impl13DynamicConfigINtNtB4_6caches8VecCacheNtNtCsjXm0eGRgiQS_10rustc_span6def_id10LocalDefIdINtNtNtCsef3NXIzrFT9_12rustc_middle5query5erase6ErasedAh
  41:     0x7ffd33960fe3 - rustc_query_impl[41ff65b64ab350b4]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7ffd32a2c103 - RINvNtCsebAyhQxexiU_3std9panicking3tryuINtNtNtCsjpBzhLK3VS9_4core5panic11unwind_safe16AssertUnwindSafeNCNCNCINvNtNtNtCs8bTriOcSdES_21rustc_data_structures4sync8parallel7enabled15par_for_each_inRNtNtCsjXm0eGRgiQS_10rustc_span6def_id10LocalDefIdRSB36_NCINvM
  43:     0x7ffd32a2b880 - RINvNtCsebAyhQxexiU_3std9panicking3tryuINtNtNtCsjpBzhLK3VS9_4core5panic11unwind_safe16AssertUnwindSafeNCNCNCINvNtNtNtCs8bTriOcSdES_21rustc_data_structures4sync8parallel7enabled15par_for_each_inRNtNtCsjXm0eGRgiQS_10rustc_span6def_id10LocalDefIdRSB36_NCINvM
  44:     0x7ffd329fdf32 - RINvMNtNtCs8bTriOcSdES_21rustc_data_structures4sync8parallelNtB3_13ParallelGuard3runuNCNCNCINvNtB3_7enabled15par_for_each_inRNtNtCsjXm0eGRgiQS_10rustc_span6def_id10LocalDefIdRSB1Z_NCINvMs1_NtNtCsef3NXIzrFT9_12rustc_middle3hir3mapNtB31_3Map15par_body_owner
  45:     0x7ffd328e9ca2 - RINvNtNtNtCs8bTriOcSdES_21rustc_data_structures4sync8parallel7enabled15par_for_each_inRNtNtCsjXm0eGRgiQS_10rustc_span6def_id10LocalDefIdRSB1n_NCINvMs1_NtNtCsef3NXIzrFT9_12rustc_middle3hir3mapNtB2p_3Map15par_body_ownersNCNvCs5Z2QjRJ4hA0_18rustc_hir_analysi
  46:     0x7ffd328196c9 - rustc_hir_analysis[45b4dac900b2c2ce]::check_crate
  47:     0x7ffd308032f9 - rustc_interface[3eeae0d001a4b635]::passes::analysis
  48:     0x7ffd33a5c15c - rustc_query_impl[41ff65b64ab350b4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[41ff65b64ab350b4]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a5e56af6423dad19]::query::erase::Erased<[u8; 1usize]>>
  49:     0x7ffd3399955b - rustc_query_impl[41ff65b64ab350b4]::query_impl::instantiate_and_check_impossible_predicates::alloc_self_profile_query_strings      
  50:     0x7ffd33ae16bd - RINvMs2_NtNtCsebAyhQxexiU_3std6thread5localINtB6_8LocalKeyINtNtCsjpBzhLK3VS9_4core4cell4CellPuEE4withNCINvNtNtNtCsef3NXIzrFT9_12rustc_middle2ty7context3tls13enter_contextNCINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing20execute_job_non_incrINtCs
  51:     0x7ffd338b2f78 - RINvNtNtCs1E54DgIQnXd_18rustc_query_system5query8plumbing17try_execute_queryINtCs5FiQgzJqBuW_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsef3NXIzrFT9_12rustc_middle5query5erase6ErasedAhj1_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCt
  52:     0x7ffd33954ff1 - rustc_query_impl[41ff65b64ab350b4]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  53:     0x7ffd306cd676 - RINvMs2_NtNtCsebAyhQxexiU_3std6thread5localINtB6_8LocalKeyINtNtCsjpBzhLK3VS9_4core4cell4CellPuEE4withNCINvNtNtNtCsef3NXIzrFT9_12rustc_middle2ty7context3tls13enter_contextNCINvMs9_B1I_NtB1I_10GlobalCtxt5enterNCNCNCNvCsaaGoLZrJT1T_17rustc_driver_impl12run_c
  54:     0x7ffd306c05ed - <rustc_middle[a5e56af6423dad19]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[767bba05edafb3bb]::run_compiler::{closure#0}::{closure#1}::{closure#3}, core[e21d7e5d074c18ab]::result::Result<(), rustc_span[e874984deae97828]::ErrorGuaranteed>>
  55:     0x7ffd30687b5d - RINvMs5_NtCs5oUjEq15j35_15rustc_interface7queriesNtNtB8_9interface8Compiler5enterNCNCNvCsaaGoLZrJT1T_17rustc_driver_impl12run_compiler0s_0INtNtCsjpBzhLK3VS9_4core6result6ResultINtNtB2h_6option6OptionNtB6_6LinkerENtCsjXm0eGRgiQS_10rustc_span15ErrorGuarante
  56:     0x7ffd306a635b - rustc_span[e874984deae97828]::set_source_map::<core[e21d7e5d074c18ab]::result::Result<(), rustc_span[e874984deae97828]::ErrorGuaranteed>, rustc_interface[3eeae0d001a4b635]::interface::run_compiler<core[e21d7e5d074c18ab]::result::Result<(), rustc_span[e874984deae97828]::ErrorGuaranteed>, rustc_driver_impl[767bba05edafb3bb]::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
  57:     0x7ffd306cf97b - RINvMs_CsgVCJzdmiPiq_10scoped_tlsINtB5_9ScopedKeyNtCsjXm0eGRgiQS_10rustc_span14SessionGlobalsE3setNCINvNtCs5oUjEq15j35_15rustc_interface4util31run_in_thread_pool_with_globalsNCINvNtB1F_9interface12run_compilerINtNtCsjpBzhLK3VS9_4core6result6ResultuNtBN_15
  58:     0x7ffd306a6bf1 - RINvCsjXm0eGRgiQS_10rustc_span27create_session_globals_thenINtNtCsjpBzhLK3VS9_4core6result6ResultuNtB2_15ErrorGuaranteedENCINvNtCs5oUjEq15j35_15rustc_interface4util31run_in_thread_pool_with_globalsNCINvNtB22_9interface12run_compilerBV_NCNvCsaaGoLZrJT1T_17
  59:     0x7ffd306c8c28 - RINvNtNtCsebAyhQxexiU_3std10sys_common9backtrace28___rust_begin_short_backtraceNCNCINvNtCs5oUjEq15j35_15rustc_interface4util26run_in_thread_with_globalsNCINvB1m_31run_in_thread_pool_with_globalsNCINvNtB1o_9interface12run_compilerINtNtCsjpBzhLK3VS9_4core6r
  60:     0x7ffd3069e909 - RINvNtCsebAyhQxexiU_3std9panicking3tryINtNtCsjpBzhLK3VS9_4core6result6ResultuNtCsjXm0eGRgiQS_10rustc_span15ErrorGuaranteedEINtNtNtBF_5panic11unwind_safe16AssertUnwindSafeNCNCINvMNtB4_6threadNtB2Q_7Builder16spawn_unchecked_NCNCINvNtCs5oUjEq15j35_15rustc_in
  61:     0x7ffd306cb7d0 - RINvNtCsebAyhQxexiU_3std6thread5spawnNCNCINvNtCs5oUjEq15j35_15rustc_interface4util31run_in_thread_pool_with_globalsNCINvNtBI_9interface12run_compilerINtNtCsjpBzhLK3VS9_4core6result6ResultuNtCsjXm0eGRgiQS_10rustc_span15ErrorGuaranteedENCNvCsaaGoLZrJT1T_17r
  62:     0x7ffdd1be939b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h374ce232189b6f7d
  63:     0x7ffdd1beee03 - std::sys::pal::windows::thread::Thread::new::h61d19b62b0a4eb25
  64:     0x7ffe7668257d - BaseThreadInitThunk
  65:     0x7ffe778eaa68 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `D:\Projects\rust_dev\rustc\rust2\rustc-ice-2024-02-29T13_21_44-21284.txt` to your bug report

query stack during panic:
#0 [find_field] find the index of maybe nested field `f` in `S`
#1 [typeck] type-checking `func`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errorsthread 'rustc' panicked at compiler\rustc_hir_analysis\src\collect.rs:797:49:
```

</p>
</details>

### LINKED ISSUE #126969: ICE: unnamed fields: `internal compiler error: could not resolve DefId`
auto-reduced (treereduce-rust):
````rust
struct S<T> {
    _: union { t: T },
}

fn f(S::<&i8> { .. }: S<&i8>) {}

fn main() {}


````

original:
````rust
//@ check-pass

struct S<T> {
            _: union { t: T },
        }

fn f(S::<&i8> { .. }: S<&i8>) {}

fn main() {
    f(S { _t: &42_i8 });
}

````

Version information
````
rustc 1.81.0-nightly (d929a42a6 2024-06-25)
binary: rustc
commit-hash: d929a42a664c026167800801b26d734db925314f
commit-date: 2024-06-25
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.59Om17fnRflv/rustc_testrunner_tmpdir_reporting.OlpKHT78ftbD/mvce.rs:2:5
  |
2 |     _: union { t: T },
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-06-25; consider upgrading it if it is out of date

error[E0658]: unnamed fields are not yet fully implemented
 --> /tmp/icemaker_global_tempdir.59Om17fnRflv/rustc_testrunner_tmpdir_reporting.OlpKHT78ftbD/mvce.rs:2:8
  |
2 |     _: union { t: T },
  |        ^^^^^^^^^^^^^^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information
  = help: add `#![feature(unnamed_fields)]` to the crate attributes to enable
  = note: this compiler was built on 2024-06-25; consider upgrading it if it is out of date

error: internal compiler error: could not resolve DefId(0:4 ~ mvce[81cb]::S::T)
 --> /tmp/icemaker_global_tempdir.59Om17fnRflv/rustc_testrunner_tmpdir_reporting.OlpKHT78ftbD/mvce.rs:2:19
  |
2 |     _: union { t: T },
  |                   ^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1461:14:
Box<dyn Any>
stack backtrace:
   0:     0x7ae2e7f1d2e5 - std::backtrace_rs::backtrace::libunwind::trace::h3816f17667167091
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7ae2e7f1d2e5 - std::backtrace_rs::backtrace::trace_unsynchronized::h05c1a74390e79138
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ae2e7f1d2e5 - std::sys::backtrace::_print_fmt::hf9f67f450e2340b3
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:68:5
   3:     0x7ae2e7f1d2e5 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd0470f4740d6f066
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:44:22
   4:     0x7ae2e7f6cceb - core::fmt::rt::Argument::fmt::h70b8a6b09781c530
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/fmt/rt.rs:165:63
   5:     0x7ae2e7f6cceb - core::fmt::write::hafea0839d2bbb3f2
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/core/src/fmt/mod.rs:1168:21
   6:     0x7ae2e7f11f6f - std::io::Write::write_fmt::h781fa7911c53c2fa
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/io/mod.rs:1835:15
   7:     0x7ae2e7f1d0be - std::sys::backtrace::_print::h864675b81ca0e917
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:47:5
   8:     0x7ae2e7f1d0be - std::sys::backtrace::print::h077604854516c949
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/backtrace.rs:34:9
   9:     0x7ae2e7f1fa09 - std::panicking::default_hook::{{closure}}::h0655bbcac1b3559e
  10:     0x7ae2e7f1f7ac - std::panicking::default_hook::ha9e013cc76e074dd
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:292:9
  11:     0x7ae2e43eac90 - std[e6dd88f179d4d596]::panicking::update_hook::<alloc[7519215c1642967c]::boxed::Box<rustc_driver_impl[6d6094f07793e4a9]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7ae2e7f202df - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::haac7baf64299a07d
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2078:9
  13:     0x7ae2e7f202df - std::panicking::rust_panic_with_hook::h9bfa469549e655b8
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/panicking.rs:804:13
  14:     0x7ae2e4424711 - std[e6dd88f179d4d596]::panicking::begin_panic::<rustc_errors[87fc00edeecce55a]::ExplicitBug>::{closure#0}
  15:     0x7ae2e4417b76 - std[e6dd88f179d4d596]::sys::backtrace::__rust_end_short_backtrace::<std[e6dd88f179d4d596]::panicking::begin_panic<rustc_errors[87fc00edeecce55a]::ExplicitBug>::{closure#0}, !>
  16:     0x7ae2e4417b26 - std[e6dd88f179d4d596]::panicking::begin_panic::<rustc_errors[87fc00edeecce55a]::ExplicitBug>
  17:     0x7ae2e442d2c1 - <rustc_errors[87fc00edeecce55a]::diagnostic::BugAbort as rustc_errors[87fc00edeecce55a]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7ae2e44b2398 - <rustc_errors[87fc00edeecce55a]::DiagCtxtHandle>::span_bug::<rustc_span[31538c27a715cd64]::span_encoding::Span, alloc[7519215c1642967c]::string::String>
  19:     0x7ae2e6189478 - <rustc_hir_analysis[6239ffc5e5ec24c9]::collect::resolve_bound_vars::BoundVarContext>::resolve_type_ref
  20:     0x7ae2e2f7a430 - rustc_hir[ca0bf1aa5980ff5d]::intravisit::walk_qpath::<rustc_hir_analysis[6239ffc5e5ec24c9]::collect::resolve_bound_vars::BoundVarContext>
  21:     0x7ae2e618efd1 - rustc_hir[ca0bf1aa5980ff5d]::intravisit::walk_item::<rustc_hir_analysis[6239ffc5e5ec24c9]::collect::resolve_bound_vars::BoundVarContext>
  22:     0x7ae2e618e19a - <rustc_hir_analysis[6239ffc5e5ec24c9]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[ca0bf1aa5980ff5d]::intravisit::Visitor>::visit_item
  23:     0x7ae2e61927de - rustc_hir_analysis[6239ffc5e5ec24c9]::collect::resolve_bound_vars::resolve_bound_vars
  24:     0x7ae2e6192437 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::resolve_bound_vars::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7ae2e5c6419f - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::VecCache<rustc_hir[ca0bf1aa5980ff5d]::hir_id::OwnerId, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  26:     0x7ae2e5c63b51 - rustc_query_impl[b034b92d40b1d47d]::query_impl::resolve_bound_vars::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7ae2e5c64f71 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::named_variable_map::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7ae2e5c6419f - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::VecCache<rustc_hir[ca0bf1aa5980ff5d]::hir_id::OwnerId, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  29:     0x7ae2e5c63c0d - rustc_query_impl[b034b92d40b1d47d]::query_impl::named_variable_map::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7ae2e61a248f - <dyn rustc_hir_analysis[6239ffc5e5ec24c9]::hir_ty_lowering::HirTyLowerer>::lower_path
  31:     0x7ae2e619f8c0 - <dyn rustc_hir_analysis[6239ffc5e5ec24c9]::hir_ty_lowering::HirTyLowerer>::lower_ty_common::{closure#0}
  32:     0x7ae2e348f3c3 - rustc_hir_analysis[6239ffc5e5ec24c9]::collect::type_of::type_of
  33:     0x7ae2e5be496a - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7ae2e5be3694 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefIdCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  35:     0x7ae2e5be323b - rustc_query_impl[b034b92d40b1d47d]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7ae2e61e1e8e - rustc_hir_analysis[6239ffc5e5ec24c9]::outlives::inferred_outlives_crate
  37:     0x7ae2e61e0f3c - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::inferred_outlives_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7ae2e684f382 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::SingleCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  39:     0x7ae2e684fd38 - rustc_query_impl[b034b92d40b1d47d]::query_impl::inferred_outlives_crate::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7ae2e5c36b56 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::inferred_outlives_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 16usize]>>
  41:     0x7ae2e5c3592f - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefIdCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  42:     0x7ae2e5c3563f - rustc_query_impl[b034b92d40b1d47d]::query_impl::inferred_outlives_of::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7ae2e5c3fd9a - rustc_hir_analysis[6239ffc5e5ec24c9]::collect::predicates_defined_on
  44:     0x7ae2e5c3fbed - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::predicates_defined_on::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 24usize]>>
  45:     0x7ae2e5c3fbd5 - <rustc_query_impl[b034b92d40b1d47d]::query_impl::predicates_defined_on::dynamic_query::{closure#2} as core[672c7616ff9a88f5]::ops::function::FnOnce<(rustc_middle[e321b4b4f2134162]::ty::context::TyCtxt, rustc_span[31538c27a715cd64]::def_id::DefId)>>::call_once
  46:     0x7ae2e5c3f017 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefIdCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  47:     0x7ae2e5c3dd40 - rustc_query_impl[b034b92d40b1d47d]::query_impl::predicates_defined_on::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7ae2e5c3de8e - rustc_hir_analysis[6239ffc5e5ec24c9]::collect::predicates_of::predicates_of
  49:     0x7ae2e5c3dd97 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 24usize]>>
  50:     0x7ae2e5c3f031 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefIdCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  51:     0x7ae2e5c3eae8 - rustc_query_impl[b034b92d40b1d47d]::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7ae2e5bffdfc - <rustc_hir_analysis[6239ffc5e5ec24c9]::collect::CollectItemTypesVisitor as rustc_hir[ca0bf1aa5980ff5d]::intravisit::Visitor>::visit_item
  53:     0x7ae2e2b0f2ef - rustc_hir_analysis[6239ffc5e5ec24c9]::check::wfcheck::check_well_formed
  54:     0x7ae2e608c2bd - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>
  55:     0x7ae2e608c535 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::VecCache<rustc_hir[ca0bf1aa5980ff5d]::hir_id::OwnerId, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  56:     0x7ae2e608c29a - rustc_query_impl[b034b92d40b1d47d]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  57:     0x7ae2e608cf4c - rustc_hir_analysis[6239ffc5e5ec24c9]::check::wfcheck::check_mod_type_wf
  58:     0x7ae2e608cd99 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>
  59:     0x7ae2e6549038 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::DefaultCache<rustc_span[31538c27a715cd64]::def_id::LocalModDefId, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  60:     0x7ae2e6548dd9 - rustc_query_impl[b034b92d40b1d47d]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  61:     0x7ae2e5d66e1f - rustc_hir_analysis[6239ffc5e5ec24c9]::check_crate
  62:     0x7ae2e5d5cf15 - rustc_interface[73bd107be0165211]::passes::analysis
  63:     0x7ae2e5d5cad9 - rustc_query_impl[b034b92d40b1d47d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b034b92d40b1d47d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>
  64:     0x7ae2e6850825 - rustc_query_system[4a94863d7e85f976]::query::plumbing::try_execute_query::<rustc_query_impl[b034b92d40b1d47d]::DynamicConfig<rustc_query_system[4a94863d7e85f976]::query::caches::SingleCache<rustc_middle[e321b4b4f2134162]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b034b92d40b1d47d]::plumbing::QueryCtxt, false>
  65:     0x7ae2e685058f - rustc_query_impl[b034b92d40b1d47d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  66:     0x7ae2e6777e3f - rustc_interface[73bd107be0165211]::interface::run_compiler::<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}
  67:     0x7ae2e6637e89 - std[e6dd88f179d4d596]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[73bd107be0165211]::util::run_in_thread_with_globals<rustc_interface[73bd107be0165211]::util::run_in_thread_pool_with_globals<rustc_interface[73bd107be0165211]::interface::run_compiler<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>
  68:     0x7ae2e6637c3a - <<std[e6dd88f179d4d596]::thread::Builder>::spawn_unchecked_<rustc_interface[73bd107be0165211]::util::run_in_thread_with_globals<rustc_interface[73bd107be0165211]::util::run_in_thread_pool_with_globals<rustc_interface[73bd107be0165211]::interface::run_compiler<core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>, rustc_driver_impl[6d6094f07793e4a9]::run_compiler::{closure#0}>::{closure#1}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672c7616ff9a88f5]::result::Result<(), rustc_span[31538c27a715cd64]::ErrorGuaranteed>>::{closure#2} as core[672c7616ff9a88f5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:     0x7ae2e7f2a16b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcfcb27dcb2ebeeb7
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2064:9
  70:     0x7ae2e7f2a16b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7d3cd9c06edd61cc
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/alloc/src/boxed.rs:2064:9
  71:     0x7ae2e7f2a16b - std::sys::pal::unix::thread::Thread::new::thread_start::h082ffbd0fcdeae0d
                               at /rustc/d929a42a664c026167800801b26d734db925314f/library/std/src/sys/pal/unix/thread.rs:108:17
  72:     0x7ae2e7cbfded - <unknown>
  73:     0x7ae2e7d430dc - <unknown>
  74:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (d929a42a6 2024-06-25) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolve_bound_vars] resolving lifetimes
#1 [named_variable_map] looking up a named region
end of query stack
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.

```

</p>
</details>

### LINKED ISSUE #131041: ICE with anonymous field and a derive in 1.80.1 but also checked on Godbolt's nightly compiler
### Code

```Rust
#[derive(Debug)]
pub struct Type
{
    _: u8,
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Fedora 1.80.1-1.fc40)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.6
```

### Error output

```
   Compiling ice20240929 v0.1.0 (/home/njl/src/ice20240929)
error[E0658]: unnamed fields are not yet fully implemented
 --> src/main.rs:4:5
  |
4 |     _: u8,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information

error[E0601]: `main` function not found in crate `ice20240929`
 --> src/main.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `src/main.rs`

error: struct with unnamed fields must have `#[repr(C)]` representation
 --> src/main.rs:2:1
  |
2 | pub struct Type
  | ^^^^^^^^^^^^^^^ struct `Type` defined here
  |
note: unnamed field defined here
 --> src/main.rs:4:5
  |
4 |     _: u8,
  |     ^^^^^
help: add `#[repr(C)]` to this struct
  |
2 + #[repr(C)]
3 | pub struct Type
  |

error: unnamed fields can only have struct or union types
 --> src/main.rs:4:5
  |
4 |     _: u8,
  |     ^^^^^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:892:49:
expect Adt for unnamed field
stack backtrace:
   0:     0x7f8f73f4f135 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2a0cac5be5a8d820
   1:     0x7f8f73f9dafb - core::fmt::write::h17332d03f2f4f35b
   2:     0x7f8f73f4421f - <unknown>
   3:     0x7f8f73f4ef0e - <unknown>
   4:     0x7f8f73f51949 - <unknown>
   5:     0x7f8f73f516ea - std::panicking::default_hook::ha48f87b295834c46
   6:     0x7f8f74a5ec30 - <unknown>
   7:     0x7f8f73f5200b - std::panicking::rust_panic_with_hook::h4eeb081fd329f3e2
   8:     0x7f8f73f51d84 - <unknown>
   9:     0x7f8f73f4f5f9 - <unknown>
  10:     0x7f8f73f51ab7 - rust_begin_unwind
  11:     0x7f8f73f15a73 - core::panicking::panic_fmt::h755ac17b0b090cd9
  12:     0x7f8f73f15a3b - core::option::expect_failed::h27ffe2fb3bb55e8c
  13:     0x7f8f75f9d6c0 - rustc_hir_analysis[9a5fae5dc28e0e53]::collect::find_field
  14:     0x7f8f7710649f - <unknown>
  15:     0x7f8f771058b1 - <unknown>
  16:     0x7f8f754fc093 - <unknown>
  17:     0x7f8f7546323e - <unknown>
  18:     0x7f8f7544390f - <unknown>
  19:     0x7f8f7559f041 - <unknown>
  20:     0x7f8f760a1e57 - <unknown>
  21:     0x7f8f760603dc - <unknown>
  22:     0x7f8f7605d32d - <unknown>
  23:     0x7f8f7605fbc3 - <unknown>
  24:     0x7f8f7605d32d - <unknown>
  25:     0x7f8f7605fbc3 - <unknown>
  26:     0x7f8f760460fa - <unknown>
  27:     0x7f8f7605f589 - <unknown>
  28:     0x7f8f7605d32d - <unknown>
  29:     0x7f8f760d7b02 - <unknown>
  30:     0x7f8f7605d32d - <unknown>
  31:     0x7f8f7612c352 - <unknown>
  32:     0x7f8f76124081 - rustc_hir_typeck[30ee169b06768cb7]::typeck
  33:     0x7f8f768b6ad7 - <unknown>
  34:     0x7f8f75462850 - <unknown>
  35:     0x7f8f75450f11 - <unknown>
  36:     0x7f8f7556d828 - <unknown>
  37:     0x7f8f75fa8e3a - rustc_hir_analysis[9a5fae5dc28e0e53]::check_crate
  38:     0x7f8f76231b9e - rustc_interface[881e2d08a402e036]::passes::analysis
  39:     0x7f8f771081e7 - <unknown>
  40:     0x7f8f75461a4f - <unknown>
  41:     0x7f8f75417c08 - <unknown>
  42:     0x7f8f7555d394 - <unknown>
  43:     0x7f8f76e65fdc - <unknown>
  44:     0x7f8f76e63de7 - <unknown>
  45:     0x7f8f76e68a7a - <unknown>
  46:     0x7f8f73f5bfeb - <unknown>
  47:     0x7f8f73d796d7 - start_thread
  48:     0x7f8f73dfd60c - __clone3
  49:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Fedora 1.80.1-1.fc40) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [find_field] find the index of maybe nested field `_` in `Type`
#1 [typeck] type-checking `<impl at src/main.rs:1:10: 1:15>::fmt`
end of query stack
Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.
error: could not compile `ice20240929` (bin "ice20240929") due to 4 previous errors

```
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:892:49:
expect Adt for unnamed field

<details><summary><strong>Backtrace</strong></summary>
<p>
```
   0:     0x7f8f73f4f135 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2a0cac5be5a8d820
   1:     0x7f8f73f9dafb - core::fmt::write::h17332d03f2f4f35b
   2:     0x7f8f73f4421f - <unknown>
   3:     0x7f8f73f4ef0e - <unknown>
   4:     0x7f8f73f51949 - <unknown>
   5:     0x7f8f73f516ea - std::panicking::default_hook::ha48f87b295834c46
   6:     0x7f8f74a5ec30 - <unknown>
   7:     0x7f8f73f5200b - std::panicking::rust_panic_with_hook::h4eeb081fd329f3e2
   8:     0x7f8f73f51d84 - <unknown>
   9:     0x7f8f73f4f5f9 - <unknown>
  10:     0x7f8f73f51ab7 - rust_begin_unwind
  11:     0x7f8f73f15a73 - core::panicking::panic_fmt::h755ac17b0b090cd9
  12:     0x7f8f73f15a3b - core::option::expect_failed::h27ffe2fb3bb55e8c
  13:     0x7f8f75f9d6c0 - rustc_hir_analysis[9a5fae5dc28e0e53]::collect::find_field
  14:     0x7f8f7710649f - <unknown>
  15:     0x7f8f771058b1 - <unknown>
  16:     0x7f8f754fc093 - <unknown>
  17:     0x7f8f7546323e - <unknown>
  18:     0x7f8f7544390f - <unknown>
  19:     0x7f8f7559f041 - <unknown>
  20:     0x7f8f760a1e57 - <unknown>
  21:     0x7f8f760603dc - <unknown>
  22:     0x7f8f7605d32d - <unknown>
  23:     0x7f8f7605fbc3 - <unknown>
  24:     0x7f8f7605d32d - <unknown>
  25:     0x7f8f7605fbc3 - <unknown>
  26:     0x7f8f760460fa - <unknown>
  27:     0x7f8f7605f589 - <unknown>
  28:     0x7f8f7605d32d - <unknown>
  29:     0x7f8f760d7b02 - <unknown>
  30:     0x7f8f7605d32d - <unknown>
  31:     0x7f8f7612c352 - <unknown>
  32:     0x7f8f76124081 - rustc_hir_typeck[30ee169b06768cb7]::typeck
  33:     0x7f8f768b6ad7 - <unknown>
  34:     0x7f8f75462850 - <unknown>
  35:     0x7f8f75450f11 - <unknown>
  36:     0x7f8f7556d828 - <unknown>
  37:     0x7f8f75fa8e3a - rustc_hir_analysis[9a5fae5dc28e0e53]::check_crate
  38:     0x7f8f76231b9e - rustc_interface[881e2d08a402e036]::passes::analysis
  39:     0x7f8f771081e7 - <unknown>
  40:     0x7f8f75461a4f - <unknown>
  41:     0x7f8f75417c08 - <unknown>
  42:     0x7f8f7555d394 - <unknown>
  43:     0x7f8f76e65fdc - <unknown>
  44:     0x7f8f76e63de7 - <unknown>
  45:     0x7f8f76e68a7a - <unknown>
  46:     0x7f8f73f5bfeb - <unknown>
  47:     0x7f8f73d796d7 - start_thread
  48:     0x7f8f73dfd60c - __clone3
  49:                0x0 - <unknown>
```
</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
`#![feature(unnamed_fields)]` was implemented in part in #115131 and #115367, however work on that feature has (afaict) stalled and in the mean time there have been some concerns raised (e.g.[^1][^2]) about whether `unnamed_fields` is worthwhile to have in the language, especially in its current desugaring. Because it represents a compiler implementation burden including a new kind of anonymous ADT and additional complication to field selection, and is quite prone to bugs today, I'm choosing to remove the feature.

However, since I'm not one to really write a bunch of words, I'm specifically *not* going to de-RFC this feature. This PR essentially *rolls back* the state of this feature to "RFC accepted but not yet implemented"; however if anyone wants to formally unapprove the RFC from the t-lang side, then please be my guest. I'm just not totally willing to summarize the various language-facing reasons for why this feature is or is not worthwhile, since I'm coming from the compiler side mostly.

Fixes #117942
Fixes #121161
Fixes #121263
Fixes #121299
Fixes #121722
Fixes #121799
Fixes #126969
Fixes #131041

Tracking:
* https://github.com/rust-lang/rust/issues/49804

[^1]: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Unnamed.20struct.2Funion.20fields
[^2]: https://github.com/rust-lang/rust/issues/49804#issuecomment-1972619108

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm nominating this for T-lang *somewhat* out of courtesy; my understanding is that whether or not an RFC-approved *unstable* implementation of a feature moves forwards or backwards really is a T-compiler judgement call, but I would like to hear T-lang's take on this.

I generally think that "let's go back to the drawing board" is the right call here, and in the mean time, I'd like to remove this from the compiler since there's a fair chance that a future design could be implemented some other way, and it's always easier to add things back into the compiler -- and I would be glad to either mentor or implement that work myself when that time comes, of course.

@rustbot label: +I-lang-nominated

**Comment by fee1-dead** [comment]
currently capacity deficient, so

r? compiler

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 1]
```diff
@@ -1008,77 +1008,11 @@ impl<'tcx> FieldUniquenessCheckContext<'tcx> {
...
-                        span: unnamed_field_span,
-                        nested_field_span: self.tcx.def_span(field.did),
-                    }
-                    .into(),
-                );
-            }
-        }
-    }
-
     /// Check the uniqueness of fields in a struct variant, and recursively
```
Comment (clubby789) [inline compiler/rustc_hir_analysis/src/collect.rs:1011]: Comment should be adjusted (or this function can probably just be inlined into callers now)

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect.rs]: Thanks, good point.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the meeting today, and we appreciated the courtesy, and agree that it's OK as far as lang is concerned to rip this out.

**Comment by michaelwoerister** [comment]
r? compiler (cc https://github.com/rust-lang/team/pull/1565)

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
I agree, removing this implementation is well motivated. Thanks @compiler-errors for doing this and also notifying T-lang of the removal.

@bors r+
