### PR TITLE
Fix incorrect warning about unused repr attributes.

### LINKED ISSUE #26646: #[repr(C)] #[repr(packed)] incorrectly warns about unused attribute
```rust
use std::mem::{size_of, align_of};

#[repr(C)] #[repr(packed)] 
struct Foo1(u32, u64);

#[repr(packed)] #[repr(C)] 
struct Foo2(u32, u64);

#[repr(C)] 
struct Foo3(u32, u64);

#[repr(packed)]
struct Foo4(u32, u64);

struct Foo5(u64, u32);


fn main() {
    println!("Foo1 s: {}, a: {}", size_of::<Foo1>(), align_of::<Foo1>());
    println!("Foo2 s: {}, a: {}", size_of::<Foo2>(), align_of::<Foo2>());
    println!("Foo2 s: {}, a: {}", size_of::<Foo3>(), align_of::<Foo3>());
    println!("Foo2 s: {}, a: {}", size_of::<Foo4>(), align_of::<Foo4>());
    println!("Foo2 s: {}, a: {}", size_of::<Foo5>(), align_of::<Foo5>());
}
```

```
<anon>:3:12: 3:27 warning: unused attribute, #[warn(unused_attributes)] on by default
<anon>:3 #[repr(C)] #[repr(packed)] 
                    ^~~~~~~~~~~~~~~

Foo1 s: 12, a: 8
Foo2 s: 12, a: 8
Foo2 s: 16, a: 8
Foo2 s: 12, a: 8
Foo2 s: 16, a: 8
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #26646.

Loops over all `#[repr(..)]` attributes instead of stopping at the first one to make sure they are all marked as used. Previously it stopped after the first `#[repr(C)]` was found causing all other attributes to be skipped by the linter.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could you also add a test for this as well?

File: src/test/run-pass/issue-26646.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+#[repr(C)]
+#[repr(packed)]
+pub struct Foo;
+
+#[repr(packed)]
+#[repr(C)]
+pub struct Bar;
+
+fn main() { }
```
Comment (eddyb) [inline src/test/run-pass/issue-26646.rs]: There should be a newline at the end of the file.
