### PR TITLE
Changed the error message to more clearly explain what is allowed

### LINKED ISSUE #61634: Incorrect error message for empty object types
When creating an empty trait object using the `dyn` syntax, the error message is misleading. Example:

```rust
fn main() {
    let _x: &dyn = &0;
}
```
This is rejected, with this message:
```
error[E0224]: at least one non-builtin trait is required for an object type
 --> src/main.rs:2:14
  |
2 |     let _x: &dyn = &0;
  |              ^^^
```
The error message here implies that at least one trait that is not an auto trait (`Send`/`Sync`) has to be specified. However, `&dyn Send` is accepted, and `&Send` has worked since 1.0.0, so the message is clearly wrong. Should be pretty easy to fix in the code below:

https://github.com/rust-lang/rust/blob/c8865d8e195813ade6b84434ac9f8850e7112d1a/src/librustc_typeck/astconv.rs#L1247-L1251

### PR DESCRIPTION
**Pull request by asfreitas**
This is in regard to #61634. I changed the language to make it more clear what is allowed. Closes #61634

### CODE REVIEW

File: src/librustc_typeck/astconv.rs [hunk 1]
```diff
@@ -1011,7 +1011,7 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx> + 'o {
 
         if regular_traits.is_empty() && auto_traits.is_empty() {
             span_err!(tcx.sess, span, E0224,
-                "at least one non-builtin trait is required for an object type");
+                "at least one non-builtin trait, outside of &send, is required for an object type");
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]:
```suggestion
                "at least one non-builtin trait, outside of `Send`, is required for an object type");
```

Comment (Centril) [inline src/librustc_typeck/astconv.rs]: `&dyn Sync` works fine also.

The check above makes sure that there's at least one [regular trait | auto trait].

I think it would be best to say:

```
at least one trait is required for an object type
```

**Comment by jonas-schievink** [comment]
@asfreitas Okay, the change looks good. Some tests are now failing because the compiler output changed, check [this guide](https://rust-lang.github.io/rustc-guide/tests/adding.html?highlight=bless#editing-and-updating-the-reference-files) for how to fix them :)

**Comment by jonas-schievink** [comment]
Oh and also, you can edit the PR description to say "Closes #61634", then GitHub will automatically close that issue as fixed once this is merged.

**Comment by estebank** [comment]
You'll need to run `./x.py test src/test/ui --stage 1 --bless` to update the following tests:

[00:59:32]     [ui] ui/traits/trait-alias/trait-alias-only-maybe-bound.rs
[00:59:32]     [ui] ui/traits/trait-object-macro-matcher.rs
[00:59:32]     [ui] ui/traits/trait-object-vs-lifetime-2.rs
[00:59:32]     [ui] ui/traits/trait-object-vs-lifetime.rs
[00:59:32]     [ui] ui/traits/wf-trait-object-only-maybe-bound.rs

https://travis-ci.com/rust-lang/rust/jobs/206567228#L2199

**Comment by jonas-schievink** [comment]
Triage: @asfreitas do you have time to update the tests?

**Comment by asfreitas** [comment]
Yes, sorry, I was finishing up exams. I'll look into it.

**Comment by jonas-schievink** [comment]
Sure, no worries :)
