### PR TITLE
dbg!() without parameters

### LINKED ISSUE #57845: dbg!() without parameters
Hello,
I found **dbg!(..)** is very useful, but, unfortunately it does not support **dbg!()** without expression, which could help to debug your program also.

I found that **println!()** did not work in first versions also, but later it was fixed, that is why I suppose **dbg!()** has the same story.

dbg!(()) is ok, but its just workaround.

Thank you,

### PR DESCRIPTION
**Pull request by clarfonthey**
Fixes #57845.

### CODE REVIEW

**Review by zackmdavis — DISMISSED** [review]
I argue that the new behavior should be exercised in the [expected-behavior test file](https://github.com/rust-lang/rust/blob/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2/src/test/ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior.rs).

File: src/libstd/macros.rs [hunk 1]
```diff
@@ -305,10 +305,16 @@ macro_rules! eprintln {
...
 ///
+/// You can also use `dbg!()` without a value to just print the
+/// file and line whenever it's reached.
+///
 /// [stderr]: https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)
 #[macro_export]
 #[stable(feature = "dbg_macro", since = "1.32.0")]
 macro_rules! dbg {
+    () => {
+        eprintln!("[{}:{}]", file!(), line!());
```
Comment (Centril) [inline src/libstd/macros.rs]: I would just let this call `dbg!(())` and make it a shorthand.

Comment (memoryruins) [reply src/libstd/macros.rs]: @Centril the commit with `dbg!()` prints
```rust
[src/main.rs:2]
```

If it called `dbg!(())`, it would print
```rust
[src/main.rs:2] () = ()
```
Is that preferred?

Comment (clarcharr) [reply src/libstd/macros.rs]: I feel like the noise would ruin the benefits of this. Separating out lines without the expression on them in the debug output with stuff like this might help make debugging visually easier. I think.

Comment (Centril) [reply src/libstd/macros.rs]: Hmm; I mainly thought of the benefits as typing convenience, not changes in output...
Anyways, I don't mind this the way it is now -- we can always change it if we want since the format is unstable. (but please add a test for `let _: () = dbg!();` to make sure it compiles)

**Comment by clarcharr** [comment]
Added test for this, so, it should be ready to merge.

**Comment by Dylan-DPC** [comment]
r? @zackmdavis 

ping from triage @clarcharr you have failing tests to resolve

**Comment by clarcharr** [comment]
@Dylan-DPC ...I resolved the tests. This is ready for merge.

File: src/libstd/macros.rs (hunk 1 above)
Comment (SimonSapin) [reply src/libstd/macros.rs]: I would prefer not to conflate “zero argument” with “one argument which has the unit type”, and printing `() = ()` seems noisy at best.

**Comment by SimonSapin** [comment]
This seems like an obvious improvement to me, but it adds a stable API:

@rfcbot fcp merge

**Comment by Dylan-DPC** [comment]
ping from triage @SimonPersson / @rust-lang/libs any updates on this?

**Comment by Centril** [comment]
Based on team approval...

r? @Centril  @bors r+ rollup
