### PR TITLE
Report the actual item that evaluation failed for

### LINKED ISSUE #142010: Const-eval failure in `const fn` does not print the path of what we evaluate
Consider this code:
```rust
struct S<T>(T);

const fn oopsie() -> ! {
    panic!();
}

impl<T> S<T> {
    const C1: i32 = panic!();
    const C2: i32 = oopsie();
}

fn main() {
    S::<i32>::C1; // or C2
}
```
If we use `C1`, we get the following:
```
error[E0080]: evaluation of `S::<i32>::C1` failed
 --> src/main.rs:8:21
  |
8 |     const C1: i32 = panic!();
  |                     ^^^^^^^^ evaluation panicked: explicit panic
```
But if we use `C2`, we get:
```
error[E0080]: evaluation of `oopsie` failed
 --> src/main.rs:9:21
  |
9 |     const C2: i32 = oopsie();
  |                     ^^^^^^^^ evaluation panicked: explicit panic
  |
note: inside `oopsie`
 --> src/main.rs:4:5
  |
4 |     panic!();
  |     ^^^^^^^^ the failure occurred here
```
Note that it says "evaluation of `oopsie` failed"; I would have expected "evaluation of `S::<i32>::C2` failed". That's where the span points at, too.

Cc @oli-obk

### PR DESCRIPTION
**Pull request by oli-obk**
instead of id of the last frame in the evaluation stack

r? @RalfJung 

fixes rust-lang/rust#142010

### CODE REVIEW

**Comment by RalfJung** [comment]
Oh wow... good find!

Can you add a test for this that has `//~NOTE` annotations ensuring this does not regress?

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 1]
```diff
@@ -454,11 +454,12 @@ fn report_eval_error<'tcx>(
             // FIXME(oli-obk): figure out how to use structured diagnostics again.
             diag.code(E0080);
             diag.span_label(span, crate::fluent_generated::const_eval_error);
-            diag.arg("instance", instance);
             diag.arg("error_kind", kind);
             for frame in frames {
                 diag.subdiagnostic(frame);
             }
+            // Add after the frame rendering above, as it adds its own `instance` args.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs:460]: Probably best to do this for all `arg`.

**Comment by RalfJung** [comment]
This would affect even automatically derived diagnostic types, wouldn't it? That's a pretty severe bug in the diagnostic infrastructure -- fields of separate diagnostic types shouldn't be mixed like that. Can you file an issue and reference it from the comment here?

**Comment by oli-obk** [comment]
> Can you add a test for this that has `//~NOTE` annotations ensuring this does not regress?

done

**Comment by RalfJung** [comment]
r=me when CI is green
