### PR TITLE
rustc: Fix wasm64 metadata object files

### LINKED ISSUE #121460: Compiling tests for `wasm64-unknown-unknown` on latest Nightly results in linking error
Compiling any crate with `cargo test --no-run -Z build-std=std,panic_abort --target=wasm64-unknown-unknown` results in the following error: `rust-lld: error: /home/dir/.cargo/target/wasm64-unknown-unknown/debug/deps/libtest-ed35d2d81ad088d3.rlib(lib.rmeta): wasm32 object file can't be linked in wasm64 mode`.  This is a regression introduced in one of the recent NIghtly versions.

Toolchain version: cargo 1.78.0-nightly (194a60b29 2024-02-21)

### PR DESCRIPTION
**Pull request by alexcrichton**
It looks like LLD will detect object files being either 32 or 64-bit depending on any memory present. LLD will additionally reject 32-bit objects during a 64-bit link. Previously metadata objects did not have any memories in them which led LLD to conclude they were 32-bit objects which broke 64-bit targets for wasm.

This commit fixes this by ensuring that for 64-bit targets there's a memory object present to get LLD to detect it's a 64-bit target. Additionally this commit moves away from a hand-crafted wasm encoder to the `wasm-encoder` crate on crates.io as the complexity grows for the generated object file.

Closes #121460

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'll also note that if the compiler would prefer to not depend on `wasm-encoder` I'm happy to do something more hand-coded instead. I figured at this point though with a new kind of section it was complicated enough to cross the threshold of "probably worth it to have a dependency".

**Comment by alexcrichton** [comment]
Rebased!

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 1]
```diff
@@ -624,51 +627,41 @@ pub fn create_compressed_metadata_file_for_xcoff(
...
+pub fn create_metadata_file_for_wasm(sess: &Session, data: &[u8], section_name: &str) -> Vec<u8> {
+    assert!(sess.target.is_like_wasm);
+    let mut module = wasm_encoder::Module::new();
+    let mut imports = wasm_encoder::ImportSection::new();
+
+    if sess.target.pointer_width == 64 {
+        imports.import(
+            "env",
+            "__linear_memory",
+            wasm_encoder::MemoryType { minimum: 0, maximum: None, memory64: true, shared: false },
```
Comment (wesleywiser) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:654]: Just curious, does the memory persist into the final wasm object or can it be dropped by the linker since it's unused?

**Review by wesleywiser — APPROVED** [review]

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 1 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:654]: Good question, but this is only here to assist with detection of what kind of object it is, I believe LLD has separate logic for omitting the memory if it's not needed (although practically all rust programs will need a linear memory)
