### PR TITLE
Better suggestion for unknown method

### LINKED ISSUE #42386: Better suggestion for unknown method
```rust
struct Foo;
fn main() {
    Foo::new();
}
```

([playpen](https://is.gd/Uy9u1s))

gives the error

``error: no associated item named `new` found for type `Foo` in the current scope``

It's within a function call, and really we should distinguish between "associated function" (or whatever they're called) and "associated item". I understand that all functions are associated items, but for newcomers this error message isn't really helpful because associated items are an intermediate concept. Error messages shouldn't hit intermediate concepts for beginner code.

*ideally* we would notice the difference between something being used within a call expression and something not being used that way, however that's a bit tricky since in the typechecking code by the time we reach this we only know that it's a path. The "are we checking the callee" info could be propagated, but I'm not sure if it's worth it.

A more straightforward bandaid fix would be to say "function or associated item" if the first character is lowercase, and "associated item" if the first character is uppercase.

### PR DESCRIPTION
**Pull request by photoszzt**
r? @Manishearth 

fixes #42386

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm going to wait for travis to complete -- there likely will be a bunch of tests that need updating.

(Grep for the error to find them beforehand)

File: src/librustc_typeck/check/method/suggest.rs [hunk 1]
```diff
@@ -173,7 +173,11 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                      if mode == Mode::MethodCall {
                                          "method"
                                      } else {
-                                         "associated item"
+                                         if item_name.as_str().chars().next().unwrap().is_lowercase() {
```
Comment (petrochenkov) [inline src/librustc_typeck/check/method/suggest.rs]: Could you avoid `unwrap`? It may break during error recovery, if the item name is dummy.
(I haven't looked if this error recovery is actually performed for associated items right now, but anyway.)

**Comment by Manishearth** [comment]
`[00:03:29] tidy error: /checkout/src/librustc_typeck/check/method/suggest.rs:176: line longer than 100 chars`

Probably should move the lowercase check into a variable and wrap it.

Though really if you replace the unwrap with an if let it should fit anyway

File: src/librustc_typeck/check/method/suggest.rs (hunk 1 above)
Comment (photoszzt) [inline src/librustc_typeck/check/method/suggest.rs]: Fixed. Just push the new version along with modified tests.

**Comment by Manishearth** [comment]
@bors r+

Thanks!

File: src/librustc_typeck/check/method/suggest.rs [hunk 2]
```diff
@@ -173,7 +173,18 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                      if mode == Mode::MethodCall {
                                          "method"
                                      } else {
-                                         "associated item"
+                                         match item_name.as_str().chars().next() {
+                                             Some(name) => {
+                                                 if name.is_lowercase() {
+                                                     "function or associated item"
```
Comment (steveklabnik) [inline src/librustc_typeck/check/method/suggest.rs]: I would have said "associated function or item", personally

Comment (oli-obk) [inline src/librustc_typeck/check/method/suggest.rs]: Isn't the rust nomenclature for associated function "method"? So "method or associated type" would be more precise, since it can't possibly be an associated const.

Comment (Manishearth) [inline src/librustc_typeck/check/method/suggest.rs]: Why can't it be a const?

I wasn't sure if we call these methods, opinions seem to vary.

I put "function" first because newbies don't know what "associated blah" means.

Comment (oli-obk) [inline src/librustc_typeck/check/method/suggest.rs]: I it were a const, you'd need to wrap it in parens to be able to do a function call, and the const must be a Fn* or fn type

Comment (Manishearth) [inline src/librustc_typeck/check/method/suggest.rs]: We don't know if it's a function call at this stage. This fix does not introduce that checking, though @photoszzt may work on that next if he has time.
