### PR TITLE
Avoid deleting temporary files on error

### LINKED ISSUE #75275: -Csave-temps=on doesn't actually save anything
#42864 doesn't work. I need it to debug a linker failure, to re-run the linker command. But the tempdir isn't there even when I pass `-Csave-temps=on`.

@slo1 @Mark-Simulacrum

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Previously if the compiler error'd, fatally, then temporary directories which
should be preserved by -Csave-temps would be deleted due to fatal compiler
errors being implemented as panics.

cc @infinity0 

(Hopefully) fixes #75275, but I haven't tested

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try

This'll generate linux artifacts which hopefully @infinity0 can test with

File: src/librustc_data_structures/temp_dir.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+use tempfile::TempDir as TempDirReal;
+
+/// This is used to avoid TempDir being dropped on error paths unintentionally.
+#[derive(Debug)]
+pub struct TempDir {
+    path: PathBuf,
+    // This is `None` if the directory should not be deleted; used for
+    // -Csave-temps. We don't just pass around a PathBuf to keep type safety
+    // (only creating files in temporary locations).
+    dir: Option<TempDirReal>,
```
Comment (ecstatic-morse) [inline src/librustc_data_structures/temp_dir.rs:11]: This is a tad convoluted. Why not `ManuallyDrop<TempDirReal>` alongside a boolean flag?

File: src/librustc_codegen_ssa/back/link.rs [hunk 2]
```diff
@@ -70,35 +71,29 @@ pub fn link_binary<'a, B: ArchiveBuilder<'a>>(
...
-            .prefix("rustc")
-            .tempdir()
-            .unwrap_or_else(|err| sess.fatal(&format!("couldn't create a temp dir: {}", err)));
-
         if outputs.outputs.should_codegen() {
+            let tmpdir = TempFileBuilder::new()
+                .prefix("rustc")
+                .tempdir()
+                .unwrap_or_else(|err| sess.fatal(&format!("couldn't create a temp dir: {}", err)));
+            let path = TempDir::new(tmpdir, sess.opts.cg.save_temps);
```
Comment (ecstatic-morse) [inline src/librustc_codegen_ssa/back/link.rs:79]: Can we use a different name for this? `MaybeTempDir` or something? The boolean argument to `new` is surprising if you're used to `tempfile::TempDir`.

**Review by ecstatic-morse — COMMENTED** [review]
r=me with nits fixed or alternatives suggested (an extension trait for `TempDir` with a `cleanup(bool)` method would be cool). It seems the other places where `save_temps` is checked don't use RAII to manage the temporary build artifacts.

**Comment by Mark-Simulacrum** [comment]
Yes, I also checked the other places where we use save_temps for potential problems with RAII. I would've liked a way to ensure that we don't add more, but I think that'll be hard.

Fixed both comments; I also filed an issue [upstream](https://github.com/Stebalien/tempfile/issues/122) asking if we can get this implemented in the tempfile crate itself.

@bors r=ecstatic-morse

File: src/librustc_data_structures/temp_dir.rs [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    dir: ManuallyDrop<TempDir>,
+    // Whether the TempDir should be deleted on drop.
+    keep: bool,
+}
+
+impl Drop for MaybeTempDir {
+    fn drop(&mut self) {
+        // Safety: We are in the destructor, and no further access will
+        // occur.
+        let dir = unsafe { ManuallyDrop::take(&mut self.dir) };
```
Comment (ecstatic-morse) [inline src/librustc_data_structures/temp_dir.rs:17]: No need for `unsafe`. Just `drop(self.dir.into_inner())` if `keep` is false.

**Review by ecstatic-morse — CHANGES_REQUESTED** [review]

File: src/librustc_data_structures/temp_dir.rs (hunk 3 above)
Comment (ecstatic-morse) [reply src/librustc_data_structures/temp_dir.rs:17]: Oh NVM, we can't move out of it in the destructor. I would probably have done this with `ManuallyDrop::drop`, but that's also unsafe.

Comment (Mark-Simulacrum) [reply src/librustc_data_structures/temp_dir.rs:17]: I considered that, but then we need to have two unsafe blocks I think - one for the into_path case, with take, the other with drop. Seems more complicated.

Comment (ecstatic-morse) [reply src/librustc_data_structures/temp_dir.rs:17]: ...otherwise we leak the `PathBuf` inside `TempDir`. Whoops. I'm all caught up now.
