### PR TITLE
Resurrect: rustc_target: Add alignment to indirectly-passed by-value types, correcting the alignment of byval on x86 in the process.

### LINKED ISSUE #80127: rustc has wrong signature for C function with 16-byte aligned stack argument in x86_64 Linux
We were writing some code which interacts with a C shared library, but when we were calling a function in the library from Rust, we found our program was crashing. Upon inspection in the debugger, it seems that some of the arguments were getting corrupted. The Rust function signature looked correct so it was surprising. I have managed to reduce the issue down to a minimal repro.

```rust
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct bar {
    pub a: ::std::os::raw::c_ulong,
    pub b: ::std::os::raw::c_ulong,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct baz {
    pub a: bool,
    pub b: ::std::os::raw::c_uint,
}

extern "C" {
    pub fn foo_func(
        a: *mut ::std::os::raw::c_void,
        b: *mut ::std::os::raw::c_void,
        c: *const ::std::os::raw::c_char,
        d: ::std::os::raw::c_ulong,
        e: bool,
        f: baz,
        g: *mut ::std::os::raw::c_void,
        h: bar,
        i: *mut ::std::os::raw::c_void,
        j: *mut ::std::os::raw::c_void,
        k: *mut ::std::os::raw::c_void,
        l: *mut ::std::os::raw::c_void,
        m: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}

fn main() {
    let f = baz { a: true, b: 67 };
    let h = bar { a: 0, b: 99 };
    let m = std::ffi::CString::new("Hello, world").unwrap();
    unsafe {
        foo_func(
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            12,
            true,
            f,
            std::ptr::null_mut(),
            h,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            m.as_ptr(),
        )
    };
}
```
foo.h
```c
#include <stdbool.h>

struct bar {
    unsigned long a;
    unsigned long b;
}  __attribute__((aligned(16)));

struct baz {
    bool a;
    unsigned b;
};

int
foo_func(
    void *a,
    void *b,
    const char *c,
    unsigned long d,
    bool e,
    struct baz f,
    void *g,
    struct bar h,
    void *i,
    void *j,
    void *k,
    void *l,
    const char *m);
```
foo.c
```c
#include <foo.h>
#include <stdio.h>

int
foo_func(
    void *a,
    void *b,
    const char *c,
    unsigned long d,
    bool e,
    struct baz f,
    void *g,
    struct bar h,
    void *i,
    void *j,
    void *k,
    void *l,
    const char *m)
{
    printf("m = %s", m);
    return 0;
}
```

I compiled the C code into a shared library using clang
`clang -shared foo.c -o libfoo.so -I. -g`

here is the version of clang
```
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

I compiled the Rust code using cargo and `rustc 1.46.0 (04488afe3 2020-08-24)`, but told it to link against `libfoo.so`
`cargo:rustc-link-lib=dylib=foo`

I set an `rpath` on the binary so it can find the library and when I run it, it crashes with a stack overflow
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
fish: “target/debug/bug_repro” terminated by signal SIGABRT (Abort)
```

Opening it up in the debugger we can see the argument corruption

In this case the stack overflow happens in `printf`
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7bf0d8e in __vfprintf_internal (s=0x7ffff7d5d760 <_IO_2_1_stdout_>, format=0x7ffff7dca5f5 "m = %s", ap=ap@entry=0x7fffffffe590, mode_flags=mode_flags@entry=0) at vfprintf-internal.c:1645
#2  0x00007ffff7bda8d8 in __printf (format=<optimized out>) at printf.c:33
#3  0x00007ffff7dca5d0 in foo_func (a=0x0, b=0x0, c=0x0, d=12, e=true, f=..., g=0x0, h=..., i=0x0, j=0x0, k=0x0, l=0x555555815b40, m=0x7fffff7fe000 <error: Cannot access memory at address 0x7fffff7fe000>) at foo.c:20
#4  0x00005555555597b9 in bug_repro::main () at src/main.rs:39
```

Comparing the local variables and arguments of the two frames
```
(gdb) info locals
m = std::ffi::c_str::CString {inner: alloc::boxed::Box<[u8]> {data_ptr: 0x555555815b40 "Hello, world\000", length: 13}}
h = bug_repro::bar {a: 0, b: 99}
f = bug_repro::baz {a: true, b: 67}
(gdb) frame 3
#3  0x00007ffff7dca5d0 in foo_func (a=0x0, b=0x0, c=0x0, d=12, e=true, f=..., g=0x0, h=..., i=0x0, j=0x0, k=0x0, l=0x555555815b40, m=0x7fffff7fe000 <error: Cannot access memory at address 0x7fffff7fe000>) at foo.c:20
20          printf("m = %s", m);
(gdb) info args
a = 0x0
b = 0x0
c = 0x0
d = 12
e = true
f = {a = true, b = 67}
g = 0x0
h = {a = 99, b = 0}
i = 0x0
j = 0x0
k = 0x0
l = 0x555555815b40
m = 0x7fffff7fe000 <error: Cannot access memory at address 0x7fffff7fe000>
(gdb)
```
You can see things start going off the rails starting with argument `h` which doesn't have the right value, and every argument after that is wrong. Including `m` which has some garbage stack data, so its no surprise the stack overflowed when `printf` was reading at `m`

If we take a look at the llvm-ir we can see the problem

The Rust declaration of the function looks like this
```
; Function Attrs: nounwind nonlazybind uwtable
declare i32 @foo_func(i8*, i8*, i8*, i64, i1 zeroext, i64, i8*, %bar* noalias nocapture byval(%bar) dereferenceable(16), i8*, i8*, i8*, i8*, i8*) unnamed_addr #3
```
and the C definition of the function looks like this
```
; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @foo_func(i8* %0, i8* %1, i8* %2, i64 %3, i1 zeroext %4, i64 %5, i8* %6, %struct.bar* byval(%struct.bar) align 16 %7, i8* %8, i8* %9, i8* %10, i8* %11, i8* %12) #0 {
```

In my limited understanding of this, the only difference is the `align 16` for the `byval` argument which Rust is missing. I can find this mentioned in the LLVM reference
```
The byval attribute also supports specifying an alignment with the align attribute. It indicates the alignment of the stack slot to form and the known alignment of the pointer specified to the call site. If the alignment is not specified, then the code generator makes a target-specific assumption.
```
So, since the argument is being passed via the stack, it seems that the alignment of the stack storage can be specified. I wasn't sure at first if this mattered but going back and looking at the assembly produced I was able to determine that it does.

On the C side of the function call we can see that `h` has this address
```
(gdb) print &h
$2 = (struct bar *) 0x7fffffffe720
```
if we subtract 8 from this address, we can see we then get the right value
```
(gdb) print *(struct bar *)(((void *)&h) - 8)
$5 = {a = 0, b = 99}
```
The function we are calling is expecting the argument to be at `$rbp + 0x20`, but the Rust call-site is putting it at `$rbp + 0x18` (which is not a 16-byte aligned address) So I assume this missing alignment is causing issues because the caller and callee don't agree where to look on the stack for the argument

This issue has been assigned to @pcwalton via [this comment](https://github.com/rust-lang/rust/issues/80127#issuecomment-1453761835).

### PR DESCRIPTION
**Pull request by erikdesjardins**
Same as #111551, which I [accidentally closed](https://github.com/rust-lang/rust/pull/111551#issuecomment-1571222612) :/

---

This resurrects PR #103830, which has sat idle for a while.

Beyond #103830, this also:
- fixes byval alignment for types containing vectors on Darwin (see `tests/codegen/align-byval-vector.rs`)
- fixes byval alignment for overaligned types on x86 Windows (see `tests/codegen/align-byval.rs`)
- fixes ABI for types with 128bit requested alignment on ARM64 Linux (see `tests/codegen/aarch64-struct-align-128.rs`)

r? @nikic

---

@pcwalton's original PR description is reproduced below:

Commit 88e4d2c from five years ago removed
support for alignment on indirectly-passed arguments because of problems with
the `i686-pc-windows-msvc` target. Unfortunately, the `memcpy` optimizations I
recently added to LLVM 16 depend on this to forward `memcpy`s. This commit
attempts to fix the problems with `byval` parameters on that target and now
correctly adds the `align` attribute.

The problem is summarized in [this comment] by @eddyb. Briefly, 32-bit x86 has
special alignment rules for `byval` parameters: for the most part, their
alignment is forced to 4. This is not well-documented anywhere but in the Clang
source. I looked at the logic in Clang `TargetInfo.cpp` and tried to replicate
it here. The relevant methods in that file are
`X86_32ABIInfo::getIndirectResult()` and
`X86_32ABIInfo::getTypeStackAlignInBytes()`. The `align` parameter attribute
for `byval` parameters in LLVM must match the platform ABI, or miscompilations
will occur. Note that this doesn't use the approach suggested by eddyb, because
I felt it was overkill to store the alignment in `on_stack` when special
handling is really only needed for 32-bit x86.

As a side effect, this should fix #80127, because it will make the `align`
parameter attribute for `byval` parameters match the platform ABI on LLVM
x86-64.

[this comment]: #80822 (comment)

### CODE REVIEW

**Comment by nikic** [comment]
Nominating this as an FYI: This introduces a semantic difference between a struct with explicit alignment `#[align(8)]` and a struct that just happens to be 8 byte aligned. This appears to be an ABI requirement for 32-bit MSVC, so I don't see how we could avoid it, but seems like something that could use wider attention.

File: compiler/rustc_target/src/abi/call/x86.rs [hunk 1]
```diff
@@ -53,8 +53,76 @@ where
...
+                            }
+                        }
+                        false
+                    }
+                }
+            }
+
+            let byval_align = if arg.layout.align.abi < align_4 {
+                // (1.)
+                align_4
```
Comment (nikic) [inline compiler/rustc_target/src/abi/call/x86.rs:116]: On further consideration, I'm a bit worried about the alignment mismatch with the source pointer here. LangRef says:
> The byval attribute also supports specifying an alignment with the align attribute. It indicates the alignment of the stack slot to form and the known alignment of the pointer specified to the call site. If the alignment is not specified, then the code generator makes a target-specific assumption.

If I'm understanding what is going to happen here correctly, then the pointer we're passing to the call may have alignment lower than 4, which would violate the "the known alignment of the pointer specified to the call site" part of this.

Clang does specify `align 4` on the byval argument, but it also uses `align 4` for the corresponding alloca: https://clang.godbolt.org/z/cW1cPrnsr However, Rust uses `align 4`  for the `alloca`: https://rust.godbolt.org/z/db7qor7es So I think we'll get a mismatch here.

Comment (nikic) [reply compiler/rustc_target/src/abi/call/x86.rs:116]: And this isn't working on accident, clang will also insert an explicit memcpy to a higher-aligned stack slot if necessary: https://clang.godbolt.org/z/5Yofxz3We

I believe this is handled by the code starting at https://github.com/llvm/llvm-project/blob/0e7cfa59ebe9d87029ebf75bb4a05316dd3c3d63/clang/lib/CodeGen/CGCall.cpp#L5060 (this is case 2).

I think we would need something like this as well.

Comment (erikdesjardins) [reply compiler/rustc_target/src/abi/call/x86.rs:116]: Yeah, we already have code to do this when passing packed struct fields. I'll extend it to this case as well.

I also plan to change `on_stack` to `Option<Align>` as eddyb originally suggested, since implicitly relying on `pointee_align` feels a bit more sketchy with this change.

File: tests/codegen/align-byval.rs [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+// on i686-windows, this should be passed on stack using `byval`
+#[repr(C)]
+pub struct NaturalAlign8 {
+    a: i64,
+    b: i64,
+    c: i64
+}
+
+// on i686-windows, this is passed by reference (because alignment is >4 and requested/forced),
+// even though it has the exact same layout as `NaturalAlign8` (!!!)
```
Comment (nikic) [inline tests/codegen/align-byval.rs:65]: Can you please also add a test for a `#[repr(transparent)]` struct around `ForceAlign8`?

Comment (erikdesjardins) [reply tests/codegen/align-byval.rs]: Added, and fixed `repr(transparent)` (which I'm assuming should be the same as `ForceAlign8`), and added some other test cases

File: tests/codegen/align-byval.rs [hunk 3]
```diff
@@ -0,0 +1,343 @@
...
+#[repr(C)]
+#[repr(align(8))]
+pub struct ForceAlign8 {
+    a: i64,
+    b: i64,
+    c: i64
+}
+
+// On i686-windows, this is passed by reference because alignment is requested,
+// even though the requested alignment is less than the natural alignment.
```
Comment (nikic) [inline tests/codegen/align-byval.rs:75]: Hm, I wonder whether this is a bug in clang. It looks like MSVC uses the byval ABI for `__declspec(align(1))`: https://clang.godbolt.org/z/EEGE7cGEe

Comment (erikdesjardins) [reply tests/codegen/align-byval.rs:75]: Ah, I was testing pack with MSVC too (and thankfully there's not another behavior change there, as your link shows), but I missed checking `align(1)`. I guess Clang has to be wrong here since MSVC basically dictates the Windows ABI, we just have to reverse engineer and replicate it...

I'll change it to only pass by ref if the requested alignment is >4, which seems to be MSVC behavior.

Opened https://github.com/llvm/llvm-project/issues/63257

**Comment by erikdesjardins** [comment]
Nice, more bugs.

For aarch64-gnu, there's your problem: https://godbolt.org/z/4fWdY764G

In
```rs
#[repr(C)]
#[repr(align(16))]
pub struct TwoU64s {
    pub a: u64,
    pub b: u64,
}

#[repr(C)]
pub struct WrappedU64s {
    pub a: TwoU64s
}
```

`WrappedU64s` is passed as `[u64 x 2]`, which does not, in fact, have align 16.

File: tests/run-make/extern-fn-explicit-align/test.rs [hunk 4]
```diff
@@ -34,6 +34,13 @@ pub struct LowerAlign {
     pub b: u64,
 }
 
+#[derive(Copy, Clone)]
+#[repr(C)]
+#[repr(packed)]
+pub struct Packed {
+    pub a: u128
+}
```
Comment (erikdesjardins) [inline tests/run-make/extern-fn-explicit-align/test.rs:42]: Any bets on which of our targets has the wrong ABI for this?

We've seen weird special cases from -msvc and -gnu already, so I think it's time for Apple to get in the ring.

**Comment by apiraino** [comment]
T-compiler discussed during the weekly triage meeting on Zulip ([notes](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-06-15/near/366527555)). Basically here applies the same reasoning as for #112480 ([comment](https://github.com/rust-lang/rust/issues/112480#issuecomment-1593256283))

@rustbot label -I-compiler-nominated

**Comment by erikdesjardins** [comment]
ping @nikic

**Comment by nikic** [comment]
r=me after a rebase

**Comment by erikdesjardins** [comment]
And here we go again...

Looks like MSVC's [special case](https://github.com/rust-lang/rust/pull/111551#issuecomment-1555502486) for requested alignment > 4 is actually transitive, and applies if any field of a struct has requested alignment > 4. For example, for the following definitions:

```c
__declspec(align(8))
struct Align
{
    uint64_t a;
    uint64_t b;
};

struct Wrap1Align
{
    struct Align a;
    int b;
};

struct Wrap2Align {
    struct Wrap1Align a;
    char b;
};
```

MSVC passes all three indirectly. Clang and rustc (in this current patch) pass `Align` indirectly, but the two wrapped structs on the stack. See https://godbolt.org/z/GW1P4YbT4.

Clang also gets this wrong. Opened https://github.com/llvm/llvm-project/issues/63874.

**Comment by jyn514** [comment]
@bors treeclosed-

master branch was force pushed to https://github.com/rust-lang/rust/commit/ad963232d9b987d66a6f8e6ec4141f672b8b9900

**Comment by pnkfelix** [comment]
Visiting for perf-triage.

The six primary regressions were all to variants of diesel (all of check/debug/opt) for variious full and incr-full scenarios. It isn't noise, there seems to be a clear cliff that starts with this PR when looking at the graph starting from 2023-0702.

**Comment by erikdesjardins** [comment]
cachegrind diff of `diesel-1.4.8-check-full` is all in the trait system:

```
--------------------------------------------------------------------------------
Ir          
--------------------------------------------------------------------------------
395,904,127  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir             file:function
--------------------------------------------------------------------------------
  315,004,916  ???:<rustc_infer::traits::Obligation<rustc_middle::ty::Predicate> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::fold_with::<rustc_infer::infer::resolve::OpportunisticVarResolver>
 -182,350,919  ???:<rustc_middle::ty::generic_args::ArgFolder as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_ty
 -103,793,312  ???:<alloc::vec::Vec<rustc_middle::ty::Clause> as alloc::vec::spec_extend::SpecExtend<rustc_middle::ty::Clause, core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_middle::ty::Clause, rustc_span::span_encoding::Span)>, <rustc_middle::ty::generics::GenericPredicates>::instantiate_into::{closure
   79,589,914  ???:<rustc_middle::ty::Ty as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle::ty::generic_args::ArgFolder>
   74,310,808  ???:<&rustc_middle::ty::list::List<rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_middle::ty::generic_args::ArgFolder>
   71,613,406  ???:<rustc_middle::ty::generics::GenericPredicates>::instantiate_into
   51,270,977  ???:<alloc::vec::Vec<rustc_middle::ty::Clause> as alloc::vec::spec_extend::SpecExtend<rustc_middle::ty::Clause, core::iter::adapters::filter::Filter<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<(rustc_middle::ty::Clause, rustc_span::span_encoding::Span)>>, <rustc_infer::traits::util::Elaborator<rustc_middle::ty::Clause>>::elaborate::{closure
   41,690,794  ???:<(rustc_middle::ty::Predicate, rustc_middle::ty::ParamEnv) as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_infer::infer::ShallowResolver>
  -34,018,300  ???:<rustc_middle::ty::Clause>::subst_supertrait
  -29,206,801  ???:<rustc_infer::traits::util::Elaborator<rustc_middle::ty::Clause> as core::iter::traits::iterator::Iterator>::next
   27,141,479  ???:rustc_middle::ty::util::fold_list::<rustc_infer::infer::canonical::canonicalizer::Canonicalizer, rustc_middle::ty::Clause, <&rustc_middle::ty::list::List<rustc_middle::ty::Clause> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with<rustc_infer::infer::canonical::canonicalizer::Canonicalizer>::{closure
   23,138,213  ???:<rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation_no_cache
   18,700,656  ???:<rustc_middle::ty::generic_args::GenericArg as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_middle::ty::generic_args::ArgFolder>
   14,608,136  ???:<rustc_infer::infer::InferCtxt>::commit_if_ok::<rustc_trait_selection::traits::project::ProjectAndUnifyResult, rustc_infer::traits::project::MismatchedProjectionTypes, rustc_trait_selection::traits::project::poly_project_and_unify_type::{closure
  -14,571,455  ???:<rustc_hir_typeck::fn_ctxt::FnCtxt>::check_argument_types
  -14,436,037  ???:rustc_trait_selection::traits::project::poly_project_and_unify_type
   13,002,031  ???:<rustc_hir_typeck::fn_ctxt::FnCtxt>::check_call
...
```

I suspect this change allowed a memcpy to be optimized out somewhere, changing the size of a function enough to perturb inlining, and this happened to be a bad move.

(I was actually expecting this to be caused by the cost of adding additional attributes, but that seems to be insignificant here.)
