### PR TITLE
Fix LLVM assert with write_volatile

### LINKED ISSUE #29663: `core::intrinsics::volatile_store` ignores platform calling conventions.
```rust
#![feature(core_intrinsics)]

struct A<T> {
    x: T,
    y: T,
    z: T,
    w: T,
}

fn f<T>(dummy: T) -> T {
    unsafe {
        let mut dest: T = std::mem::uninitialized();
        std::intrinsics::volatile_store(&mut dest as *mut T, dummy);
        std::intrinsics::volatile_load(&dest as *const T)
    }
}

pub fn main() {
    // Either
    let (_, _, _, _) = f((1i32, 2i32, 3i32, 4i32));
    // or
    let _ = f(A {
        x: 1i32,
        y: 2,
        z: 3,
        w: 4,
    });
}
```

Compiling with `rustc` (`rustc 1.6.0-dev (b14dc5bc1 2015-11-06)`) gets:
```
Stored value type does not match pointer operand type!
  store volatile { i32, i32, i32, i32 }* %arg, { i32, i32, i32, i32 }* %dest, align 4
 { i32, i32, i32, i32 }LLVM ERROR: Broken function found, compilation aborted!
```
Or:
```
Stored value type does not match pointer operand type!
  store volatile %"A<i32>"* %arg, %"A<i32>"* %dest, align 4
 %"A<i32>" = type { i32, i32, i32, i32 }LLVM ERROR: Broken function found, compilation aborted!
```

It looks to me that `volatile_store`'s second argument's value is used without looking at platform ABI requirements (ie using the load).

`volatile_load` might also be affected.

Also, LLVM error formatting weirdness.

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #29663

### CODE REVIEW

File: src/librustc_trans/trans/intrinsic.rs [hunk 1]
```diff
@@ -609,7 +609,11 @@ pub fn trans_intrinsic_call<'a, 'blk, 'tcx>(mut bcx: Block<'blk, 'tcx>,
         (_, "volatile_store") => {
             let tp_ty = *substs.types.get(FnSpace, 0);
             let ptr = to_arg_ty_ptr(bcx, llargs[0], tp_ty);
-            let val = from_arg_ty(bcx, llargs[1], tp_ty);
+            let val = if type_is_immediate(bcx.ccx(), tp_ty) {
+                from_arg_ty(bcx, llargs[1], tp_ty)
+            } else {
+                Load(bcx, from_arg_ty(bcx, llargs[1], tp_ty))
```
Comment (eddyb) [inline src/librustc_trans/trans/intrinsic.rs]: You don't need to transform `llargs[1]`, if it's not immediate then it's a pointer to the value you want (`Load` wouldn't work otherwise anyway).

Comment (Amanieu) [inline src/librustc_trans/trans/intrinsic.rs]: `llargs[1]` is the *value* that needs to be stored. `llargs[0]` is the pointer to the store destination.

Comment (eddyb) [inline src/librustc_trans/trans/intrinsic.rs]: If not immediate, then it's passed indirectly and `llargs[1]` is a pointer to the value that needs to be stored.

Comment (Amanieu) [inline src/librustc_trans/trans/intrinsic.rs]: Yes, which is why I first need to load it (using a non-volatile load). I then store that value using a volatile store.
