### PR TITLE
make error emitted on `impl &Trait` nicer

### LINKED ISSUE #106694: Recover from `impl &Trait` and `T: &Trait`
[The following two function definitions are not valid](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9bda53271ef3a8886793cf427b8cea91):
```rust
fn foo(_: impl &Trait) {}
fn bar<T: &Trait>(_: T) {}
```

They fail in the parser and it doesn't recover nicely.

```
error: expected one of `:`, `@`, or `|`, found `)`
 --> src/main.rs:2:22
  |
2 | fn foo(_: impl &Trait) {}
  |                      ^ expected one of `:`, `@`, or `|`
  |
  = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a parameter name, give it a type
  |
2 | fn foo(_: impl Trait: &TypeName) {}
  |                ~~~~~~~~~~~~~~~~
help: if this is a type, explicitly ignore the parameter name
  |
2 | fn foo(_: impl _: &Trait) {}
  |                ++

error: expected one of `!`, `(`, `)`, `,`, `?`, `for`, `~`, lifetime, or path, found `&`
 --> src/main.rs:2:16
  |
2 | fn foo(_: impl &Trait) {}
  |               -^ expected one of 9 possible tokens
  |               |
  |               help: missing `,`

error: expected one of `!`, `(`, `,`, `=`, `>`, `?`, `for`, `~`, lifetime, or path, found `&`
 --> src/main.rs:3:11
  |
3 | fn bar<T: &Trait>(_: T) {}
  |           ^ expected one of 10 possible tokens
```

It should produce an appropriate error message, closer to the output for `impl &Trait for () {}`:

```
error: expected a trait, found type
 --> src/main.rs:2:6
  |
2 | impl &Trait for () {}
  |      ^^^^^^
```

### PR DESCRIPTION
**Pull request by Ezrashaw**
Fixes #106694

Turned out to be simpler than I thought, also added UI test.

Before: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9bda53271ef3a8886793cf427b8cea91))
```text
error: expected one of `:`, `@`, or `|`, found `)`
 --> src/main.rs:2:22
  |
2 | fn foo(_: impl &Trait) {}
  |                      ^ expected one of `:`, `@`, or `|`
  |
  = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a parameter name, give it a type
  |
2 | fn foo(_: impl Trait: &TypeName) {}
  |                ~~~~~~~~~~~~~~~~
help: if this is a type, explicitly ignore the parameter name
  |
2 | fn foo(_: impl _: &Trait) {}
  |                ++

error: expected one of `!`, `(`, `)`, `,`, `?`, `for`, `~`, lifetime, or path, found `&`
 --> src/main.rs:2:16
  |
2 | fn foo(_: impl &Trait) {}
  |               -^ expected one of 9 possible tokens
  |               |
  |               help: missing `,`

error: expected one of `!`, `(`, `,`, `=`, `>`, `?`, `for`, `~`, lifetime, or path, found `&`
 --> src/main.rs:3:11
  |
3 | fn bar<T: &Trait>(_: T) {}
  |           ^ expected one of 10 possible tokens
```

After:
```text
error: expected a trait, found type
 --> <anon>:2:16
  |
2 | fn foo(_: impl &Trait) {}
  |                -^^^^^
  |                |
  |                help: consider removing the indirection

error: expected a trait, found type
 --> <anon>:3:11
  |
3 | fn bar<T: &Trait>(_: T) {}
  |           -^^^^^
  |           |
  |           help: consider removing the indirection
```

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -756,6 +756,46 @@ impl<'a> Parser<'a> {
             }
         }
 
+        // We could've continued to parse bounds but we found a type instead of a trait.
+        if !self.can_begin_bound() && self.check_type() {
+            let ty = self.parse_ty().unwrap();
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:761]: This can fail: `check_type` only checks if the current token can *begin* a type not that the upcoming type is valid. E.g. `T: &fn<>()` would crash the compiler in your current patch. Either bubble up the error with `?` or preferably (?) pattern match on the `Result` and only show the custom suggestion if `Ok(ty)`.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 2]
```diff
@@ -756,6 +756,46 @@ impl<'a> Parser<'a> {
...
+
+                err.span_suggestion(
+                    span,
+                    "consider removing the indirection",
+                    "",
+                    Applicability::MaybeIncorrect,
+                );
+
+                match &peeled.kind {
+                    TyKind::Path(_, path) => {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:778]: Minor nitpick regarding style: You could use `if`/`let` here which looks a bit nicer here in my opinion.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -756,6 +756,46 @@ impl<'a> Parser<'a> {
             }
         }
 
+        // We could've continued to parse bounds but we found a type instead of a trait.
+        if !self.can_begin_bound() && self.check_type() {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:760]:
```suggestion
        if !self.can_begin_bound() && self.token.can_begin_type() {
```

I recommend you to use `can_begin_type()` over `check_type` since the latter populates the list of *expected tokens* which is not correct strictly speaking (this is why you see the stderr changes in `src/test/ui/fn/fn-recover-return-sign2.rs` and `src/test/ui/parser/trait-object-delimiters.rs`).

**Comment by estebank** [comment]
Please address the comments above, but you'll have to rebase on top of a fresh master (we've moved tests from `src/test` to `tests`.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 1 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs]: Hmm, that example doesn't panic and I'm not sure why. In any case, I've made the change.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 2 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs]: Done. I was thinking that perhaps other cases could be added but on second thought none would work.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 3 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs]: I was wondering about those unrelated UI test changes. I've made the change, thanks!

**Comment by Ezrashaw** [comment]
@estebank I assume you just want me to address fmease's comments, you didn't have any? 

I think that this is blocked until the tests are moved.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 4]
```diff
@@ -756,6 +756,44 @@ impl<'a> Parser<'a> {
             }
         }
 
+        // We could've continued to parse bounds but we found a type instead of a trait.
+        if self.may_recover() && !self.token.can_begin_bound() && self.token.can_begin_type() {
+            if let Ok(ty) = self.parse_ty() {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:761]: Aren't you dropping a `Diagnostic` on the floor here? That's gonna cause an ICE. You can change this to either use `?` or `match`.

**Comment by estebank** [comment]
r=me after addressing the last comment (that I hadn't noticed earlier)

**Comment by Ezrashaw** [comment]
@estebank I don't quite understand? Also, the tests are failing, I have to rewrite my impl. It'll be a bit.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 4 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:761]: I don't quite understand?

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:761]: Right, since you use `match` which I suggested, you need to cancel the error, i.e. add `Err(err) => err.cancel()`.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs]: Ah, yeah my bad. `fn<>()` itself gets recovered. I guess the bound `T: &fn<const>()` would've actually panicked.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 4 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:761]: No, we still want to emit the error even if we can't recover. Better this error than some random "expected `!` but found `,`"; recovery is just to prevent another error later on (not the end of the world if it's emitted).

Comment (estebank) [reply compiler/rustc_parse/src/parser/ty.rs:761]:
```suggestion
            let ty = self.parse_ty()?;
```

**Comment by Ezrashaw** [comment]
@estebank @fmease I've rewritten this PR, it's a lot better now, we don't have those pesky "added to expected tokens" issues. Another review would be great :).

and I have no idea how the "re-request review" button works??

File: compiler/rustc_parse/src/parser/ty.rs [hunk 5]
```diff
@@ -938,6 +940,36 @@ impl<'a> Parser<'a> {
...
+            // if it fails then we get a parser error which we don't want (we're trying
+            // to recover from errors, not make more).
+            let path = if self.may_recover()
+                && let Ok(ty) = self.parse_ty_no_plus()
+                && matches!(ty.kind, TyKind::Ptr(..) | TyKind::Ref(..))
+                && let TyKind::Path(_, path) = &ty.peel_refs().kind {
+                // Just get the indirection part of the type.
+                let span = ty.span.until(path.span);
+
+                err.span_suggestion(
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:959]:
```suggestion
                err.span_suggestion_verbose(
```
and then re`--bless`.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 6]
```diff
@@ -938,6 +940,36 @@ impl<'a> Parser<'a> {
             && self.look_ahead(1, |tok| tok.kind == TokenKind::OpenDelim(Delimiter::Parenthesis))
             && let Some(path) = self.recover_path_from_fn()
         {
+            path
+        } else if !self.token.is_path_start() && self.token.can_begin_type() {
+            // Instead of finding a path (a trait), we found a type.
+            let mut err = self.struct_span_err(self.token.span, "expected a trait, found type");
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:946]:
```suggestion
            let mut err = self.struct_span_err(self.token.span, "expected a trait, found type start");
```
Specify "type start" because we *haven't* parsed a type yet, and the span points at `&` only, so it would be a "lie" (and potentially confusing) to talk about a type.

**Review by estebank — COMMENTED** [review]
One last nitpick before merging

File: compiler/rustc_parse/src/parser/ty.rs (hunk 6 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:946]: I've done this slightly differently. Instead we will only emit the nice error is there is a proper type, "found type start" seems a bit confusing to me.

File: compiler/rustc_parse/src/parser/ty.rs (hunk 5 above)
Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:959]: Done, thanks!

**Comment by Ezrashaw** [comment]
@estebank Can we merge this now? Also could you `r+` #106591? I don't have perms. Thanks!

File: compiler/rustc_parse/src/parser/ty.rs [hunk 7]
```diff
@@ -938,6 +940,35 @@ impl<'a> Parser<'a> {
             && self.look_ahead(1, |tok| tok.kind == TokenKind::OpenDelim(Delimiter::Parenthesis))
             && let Some(path) = self.recover_path_from_fn()
         {
+            path
+        } else if !self.token.is_path_start() && self.token.can_begin_type() && let Ok(ty) = self.parse_ty_no_plus() {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:944]: The issue I'm seeing is that `let Ok(ty) = self.parse_ty_no_plus()` can fail parsing the type and will be returning an `Err(Diagnostic)`, which gets discarded. If this happens, an ICE will occur. We need to either bubble it up (wich `self.parse_ty_no_plus()?`, which is fine if slightly misleading) or `err.delay_as_bug()` it (which isn't great without another mechanism to complain about the parse failure).

Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:944]: Hmm, what about matching on error and cancelling the diagnostic. I didn't properly realize that it returned a diagnostic, not just an error to be later turned into a diagnostic.

Comment (Ezrashaw) [reply compiler/rustc_parse/src/parser/ty.rs:944]: With my current code the following ICEs:
```rust
fn foo<T: &match>() {}
```
if we `?` the parse call then we get:
```text
error: expected type, found keyword `match`
 --> <anon>:1:12
  |
1 | fn foo<T: &match>() {}
  |            ^^^^^ expected type
```
I'm happy with this, I don't think it's confusing. We could however add a note, something along the lines of: `this error was encountered when trying to recover from a "expected a trait, found type" error` before bubbling it up.

Comment (estebank) [reply compiler/rustc_parse/src/parser/ty.rs]: You can do `map_err(|mut err| { err.note(..); err })?`, but I think even without the extra context this output would be fine.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 8]
```diff
@@ -938,6 +940,36 @@ impl<'a> Parser<'a> {
...
+            // Instead of finding a path (a trait), we found a type.
+            let mut err = self.struct_span_err(ty.span, "expected a trait, found type");
+
+            // If we can recover, try to extract a path from the type. Note
+            // that we do not use the try operator when parsing the type because
+            // if it fails then we get a parser error which we don't want (we're trying
+            // to recover from errors, not make more).
+            let path = if self.may_recover()
+                && matches!(ty.kind, TyKind::Ptr(..) | TyKind::Ref(..))
+                && let TyKind::Path(_, path) = &ty.peel_refs().kind {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:955]:
```suggestion
                && let TyKind::Path(_, path) = &ty.peel_refs().kind
            {
```
