### PR TITLE
Sign extend constants in range patterns

### LINKED ISSUE #49940: Regression in 1.26: lower range bound must be less than or equal to upper
The previous version of the `chrono-humanize` crate fails to compile with the `lower range bound must be less than or equal to upper` error (see the build log). No error nor warning was present in the 1.25 release.

```
error[E0030]: lower range bound must be less than or equal to upper
   --> src/humantime.rs:88:13
    |
 88 |             MIN...-1 => Tense::Past,
    |             ^^^ lower bound larger than upper bound
```

Since `MIN` is actually `std::i64::MIN`, the error is wrong and should be fixed.

* [chrono-humanize 0.0.10](https://crates.io/crates/chrono-humanize/0.0.10) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/chrono-humanize-0.0.10/log.txt)) cc @imp

### PR DESCRIPTION
**Pull request by oli-obk**
fixes  #49940

r? @Mark-Simulacrum

### CODE REVIEW

File: src/librustc_mir/hair/pattern/mod.rs [hunk 1]
```diff
@@ -1096,7 +1101,11 @@ pub fn compare_const_vals(a: &ConstVal, b: &ConstVal, ty: Ty) -> Option<Ordering
                     // FIXME(oli-obk): report cmp errors?
                     l.try_cmp(r).ok()
                 },
-                ty::TyInt(_) => Some((a as i128).cmp(&(b as i128))),
+                ty::TyInt(_) => {
+                    let a = interpret::sign_extend(tcx, a, ty).expect("layout error for TyInt");
```
Comment (oli-obk) [inline src/librustc_mir/hair/pattern/mod.rs]: this is the only actual change in this PR. Everything else is just moving things around.

The issue was that we represent constants in their native bit width, so casting to i128 didn't work out for e.g. `-1u8`, which is `0xFF`, and stays that when casting to `i128` (meaning it would be 255 instead of -1)

**Comment by Mark-Simulacrum** [comment]
These changes look good to me, but I'd like to r? @eddyb

File: src/test/ui/const-eval/const_signed_pat.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// must-compile-successfully
```
Comment (kennytm) [inline src/test/ui/const-eval/const_signed_pat.rs]: This has been renamed to `// compile-pass` on master (it is still `// must-compile-successfully` on beta).
