### PR TITLE
clarify resolve typo suggestion

### LINKED ISSUE #53445: did you mean `tar`? suggestion without any explanation where `tar` is from
On the playground (which has the `tar` crate available (or maybe this is rustc in general?))

```rust
fn main() {
    bar()
}
```

([Playground](https://play.rust-lang.org/?gist=91e3ae4506ef5b3f9858a707539aecd2&version=stable&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0425]: cannot find function `bar` in this scope
 --> src/main.rs:2:5
  |
2 |     bar()
  |     ^^^ did you mean `tar`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

Following the suggestion gives

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
 --> src/main.rs:2:5
  |
2 |     tar()
  |     ^^^

error[E0423]: expected function, found module `tar`
 --> src/main.rs:2:5
  |
2 |     tar()
  |     ^^^ not a function
```

I think we should be adding a note to the "did you mean" mentioning the kind of item, so "did you mean module `tar`?"

Also it looks to me like this is not a structured suggestion, we should make it one.

### PR DESCRIPTION
**Pull request by euclio**
Include the kind of the binding that we're suggesting, and use a
structured suggestion.

Fixes #53445.

### CODE REVIEW

**Comment by zackmdavis** [comment]
I'll review this tonight

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -3277,8 +3287,19 @@ impl<'a> Resolver<'a> {
             let mut levenshtein_worked = false;
 
             // Try Levenshtein algorithm.
-            if let Some(candidate) = this.lookup_typo_candidate(path, ns, is_expected, span) {
-                err.span_label(ident_span, format!("did you mean `{}`?", candidate));
+            let suggestion = this.lookup_typo_candidate(path, ns, is_expected, span);
+            if let Some(suggestion) = suggestion {
+                let msg = format!(
+                    "{} {} with a similar name exists",
```
Comment (zackmdavis) [inline src/librustc_resolve/lib.rs]: I like this wording! (I had been unhappy with "did you mean"—the [docs even say we don't want to phrase it as a question](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion)—but I wasn't sure what to replace it with.

**Review by zackmdavis — APPROVED** [review]

**Comment by zackmdavis** [comment]
> I'll review this tonight

That was slightly optimistic, but only by a day

@euclio thanks!! :sparkling_heart: :pencil2: 

@bors r+
