### PR TITLE
Disallow octal format in Ipv4 string

### LINKED ISSUE #83648: Ipv4Addr: Incorrect Parsing for Octal format IP string
This issue is inspired by [this blog](https://sick.codes/universal-netmask-npm-package-used-by-270000-projects-vulnerable-to-octal-input-data-server-side-request-forgery-remote-file-inclusion-local-file-inclusion-and-more-cve-2021-28918/).

Due to the specification, leading zero in IP string is interpreted as octal literals. So a IP address `0127.0.0.1` actually means `87.0.0.1`. As shown in the following example:

```
❯ ping 0127.0.0.1
PING 0127.0.0.1 (87.0.0.1): 56 data bytes
```

However, the `Ipv4Addr` from the std library will recognize it as `127.0.0.1` instead. A simple code to demo the situation ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a8982ed52005c4560bc695ab0fb1daed)):

```rust
use std::net::Ipv4Addr;

fn parse(input: &str) {
    let ip: Option<Ipv4Addr> = input.parse().ok();
    println!("{} -> {:?}", input, ip);
    
}

fn main() {
    parse("127.0.0.1");
    parse("0127.0.0.1");
}
```

I expected to see this happen: 
```
127.0.0.1 -> Some(127.0.0.1)
0127.0.0.1 -> Some(87.0.0.1)
```

Instead, this happened: 
```
127.0.0.1 -> Some(127.0.0.1)
0127.0.0.1 -> Some(127.0.0.1)
```

Noted this bug may cause security vulnerabilities in certain cases. For example, a Rust program uses `Ipv4Addr` doing some sanity check then passing the user string to other library or program.

Furthermore, the specification actually also allows hex format in IP string. 

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

### PR DESCRIPTION
**Pull request by xu-cheng**
In its original specification, leading zero in Ipv4 string is interpreted
as octal literals. So a IP address 0127.0.0.1 actually means 87.0.0.1.

This confusion can lead to many security vulnerabilities. Therefore, in
[IETF RFC 6943], it suggests to disallow octal/hexadecimal format in Ipv4
string all together.

Existing implementation already disallows hexadecimal numbers. This commit
makes Parser reject octal numbers.

Fixes #83648.

[IETF RFC 6943]: https://tools.ietf.org/html/rfc6943#section-3.1.1

### CODE REVIEW

**Comment by sfackler** [comment]
This seems like a reasonable change to me, but worth an FCP since it changes the behavior here.

@rfcbot fcp merge

File: library/std/src/net/parser/tests.rs [hunk 1]
```diff
@@ -8,11 +8,15 @@ const SCOPE_ID: u32 = 1337;
...
 const IPV4_STR: &str = "192.168.0.1";
 const IPV4_STR_PORT: &str = "192.168.0.1:8080";
+const IPV4_STR_WITH_OCTAL: &str = "0127.0.0.1";
+const IPV4_STR_WITH_HEX: &str = "0x10.0.0.1";
 
 const IPV6: Ipv6Addr = Ipv6Addr::new(0x2001, 0xdb8, 0, 0, 0, 0, 0xc0a8, 0x1);
 const IPV6_STR_FULL: &str = "2001:db8:0:0:0:0:c0a8:1";
 const IPV6_STR_COMPRESS: &str = "2001:db8::c0a8:1";
 const IPV6_STR_V4: &str = "2001:db8::192.168.0.1";
+const IPV6_STR_V4_WITH_OTCAL: &str = "2001:db8::0127.0.0.1";
```
Comment (cuviper) [inline library/std/src/net/parser/tests.rs:18]:
```suggestion
const IPV6_STR_V4_WITH_OCTAL: &str = "2001:db8::0127.0.0.1";
```

File: library/std/src/net/parser/tests.rs [hunk 2]
```diff
@@ -39,6 +45,8 @@ fn parse_ipv6() {
     let result: Ipv6Addr = IPV6_STR_V4.parse().unwrap();
     assert_eq!(result, IPV6);
 
+    assert!(Ipv6Addr::from_str(IPV6_STR_V4_WITH_OTCAL).is_err());
```
Comment (cuviper) [inline library/std/src/net/parser/tests.rs:48]:
```suggestion
    assert!(Ipv6Addr::from_str(IPV6_STR_V4_WITH_OCTAL).is_err());
```

File: library/std/src/net/parser/tests.rs (hunk 1 above)
Comment (xu-cheng) [reply library/std/src/net/parser/tests.rs]: Fixed

File: library/std/src/net/parser/tests.rs (hunk 2 above)
Comment (xu-cheng) [reply library/std/src/net/parser/tests.rs]: Fixed

**Comment by pthariensflame** [comment]
This will need compat-related `relnotes`, right?

**Comment by cuviper** [comment]
Sure, I've now added the `relnotes` label.

**Comment by huangjj27** [comment]
I think this is the  proper fix of 61186.
