### PR TITLE
Tweak binop errors

### LINKED ISSUE #73416: Suggest `PartialEq` bound for binary operation `==` error
Try this snippet: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=eeebdc19b025fc4b2af03c39fc8cdc76)
```rust
pub fn strip_prefix<'a, T>(s: &'a [T], prefix: &[T]) -> Option<&'a [T]>
// where 
//     T: PartialEq
{
    let n = prefix.len();
    if n <= s.len() {
        let (head, tail) = s.split_at(n);
        if head == prefix {
            return Some(tail);
        }
    }
    None
}
```

The compiler errors out:
```rust
error[E0369]: binary operation `==` cannot be applied to type `&[T]`
 --> src/lib.rs:8:17
  |
8 |         if head == prefix {
  |            ---- ^^ ------ &[T]
  |            |
  |            &[T]

error: aborting due to previous error

For more information about this error, try `rustc --explain E0369`.
```

It would be nice if the compiler could suggest adding `PartialEq` bound for `T`.

### PR DESCRIPTION
**Pull request by estebank**
* Suggest potentially missing binop trait bound (fix #73416)
* Use structured suggestion for dereference in binop

### CODE REVIEW

File: src/librustc_typeck/check/op.rs [hunk 1]
```diff
@@ -318,18 +330,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                            ty,
+                                            rhs_ty,
+                                            missing_trait,
+                                            p,
+                                            false,
+                                        );
+                                        sugg = true;
+                                    }
+                                }
+                                if !sugg && !suggested_deref {
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:359]: Is `sugg` necessary, couldn't this have remained `else if !suggested_deref`?

File: src/librustc_typeck/check/op.rs [hunk 2]
```diff
@@ -254,6 +256,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 if !lhs_ty.references_error() && !rhs_ty.references_error() {
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:256]: Pre-existing, but couldn't we make this into a match arm to avoid indenting the next 300 lines?

```rust
Err(()) if lhs_ty.references_error() || rhs_ty.references_error() => self.tcx.ty_error(),
Err(()) => {
 // as before..
}
```

File: src/librustc_typeck/check/op.rs [hunk 3]
```diff
@@ -478,18 +514,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                            ty,
+                                            rhs_ty,
+                                            missing_trait,
+                                            p,
+                                            use_output,
+                                        );
+                                        sugg = true;
+                                    }
+                                }
+                                if !sugg && !suggested_deref && !involves_fn {
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:543]: As above, couldn't this remain an `else if`?

File: src/librustc_typeck/check/op.rs [hunk 4]
```diff
@@ -458,18 +485,27 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                                 } {
                                     if let Ok(lstring) = source_map.span_to_snippet(lhs_expr.span) {
-                                        err.help(&format!(
-                                            "`{}` can be used on '{}', you can \
-                                            dereference `{2}`: `*{2}`",
-                                            op.node.as_str(),
-                                            rty.peel_refs(),
-                                            lstring
-                                        ));
+                                        err.span_suggestion_verbose(
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:488]: A lot of this error reporting seems duplicated between the `IsAssign::No` and `IsAssign::Yes` arms - is there something I'm missing or could we move some of this into a function and just call it from both arms?

File: src/librustc_typeck/check/op.rs [hunk 5]
```diff
@@ -478,18 +514,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                                        p,
-                                        use_output,
-                                    );
-                                } else if !suggested_deref && !involves_fn {
+                                    sugg = true;
+                                } else if let [ty] = &visitor.0[..] {
+                                    if let ty::Param(p) = ty.kind {
+                                        // FIXME: This *guesses* that constraining the type param
+                                        // will make the operation available, but this is only true
+                                        // when the corresponding trait has a blanked
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:522]:
```suggestion
                                        // when the corresponding trait has a blanket
```

File: src/librustc_typeck/check/op.rs [hunk 6]
```diff
@@ -318,18 +330,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                                        p,
-                                        false,
-                                    );
-                                } else if !suggested_deref {
+                                    sugg = true;
+                                } else if let [ty] = &visitor.0[..] {
+                                    if let ty::Param(p) = ty.kind {
+                                        // FIXME: This *guesses* that constraining the type param
+                                        // will make the operation available, but this is only true
+                                        // when the corresponding trait has a blanked
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:338]:
```suggestion
                                        // when the corresponding trait has a blanket
```

File: src/librustc_typeck/check/op.rs [hunk 7]
```diff
@@ -318,18 +330,33 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                        // implementation, like the following:
+                                        // `impl<'a> PartialEq for &'a [T] where T: PartialEq {}`
+                                        // The correct thing to do would be to verify this
+                                        // projection would hold.
```
Comment (davidtwco) [inline src/librustc_typeck/check/op.rs:342]: Is there a reason that we cannot construct a predicate here and check if it holds?

**Review by davidtwco — CHANGES_REQUESTED** [review]
Error improvements look good, handful of comments.

File: src/librustc_typeck/check/op.rs (hunk 7 above)
Comment (estebank) [reply src/librustc_typeck/check/op.rs:342]: Laziness? 😅

File: src/librustc_typeck/check/op.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/op.rs:359]: I was thinking that if the single type found by the visitor wasn't a type param we wouldn't show the suggestion, but I'm seeing that the visitor is only looking at type params so the if let would be irrefutable. Changing.

File: src/librustc_typeck/check/op.rs (hunk 7 above)
Comment (estebank) [reply src/librustc_typeck/check/op.rs]: Done.

File: src/librustc_typeck/check/op.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/check/op.rs]: Done

**Review by davidtwco — APPROVED** [review]
LGTM, thanks!
