### PR TITLE
make `compare_const_impl` a query and use it in `instance.rs`

### LINKED ISSUE #88365: Compiler panic when indexing associated, constant array of generic length in test
I tried to narrow it down as much as I could:

```rust
#[test]
fn some_test() {
    use core::ops::Index;

    trait MyTrait {
        type ArrayType: Index<usize, Output = u8>;

        const SIZE: usize;
        const ARRAY: Self::ArrayType;
    }

    struct MyStruct;

    // NOTE: When replacing `Self::SIZE` with `4` directly, no problem occurs.
    impl MyTrait for MyStruct {    
        type ArrayType = [u8; Self::SIZE];

        const SIZE: usize = 4;
        const ARRAY: [u8; Self::SIZE] = [1, 2, 3, 4];
    }

    let res = <MyStruct as MyTrait>::ARRAY[2]; // PANICS HERE
    assert_eq!(res, 3);
}
```

When executing `RUST_BACKTRACE=1 cargo test some_test`:

```
error: internal compiler error: /rustc/0035d9dcecee49d1f7349932bfa52c05a6f83641/compiler/rustc_codegen_ssa/src/mir/constant.rs:42:20: encountered bad ConstKind after monomorphizing: Error(DelaySpanBugEmitted(()))
  --> reed-solomon-novelpoly/src/field/traits.rs:28:15
   |
28 |     let res = <MyStruct as MyTrait>::ARRAY[2]; // PANICS HERE
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/0035d9dcecee49d1f7349932bfa52c05a6f83641/compiler/rustc_errors/src/lib.rs:1061:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::span_bug
   3: rustc_errors::Handler::span_bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::span_bug_fmt
   7: rustc_codegen_ssa::mir::constant::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::eval_mir_constant
   8: rustc_codegen_ssa::mir::codegen_mir
   9: rustc_codegen_ssa::base::codegen_instance
  10: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  11: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  13: rustc_codegen_llvm::base::compile_codegen_unit
  14: rustc_codegen_ssa::base::codegen_crate
  15: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  16: rustc_interface::queries::Queries::ongoing_codegen
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (0035d9dce 2021-08-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `reed-solomon-novelpoly` (lib test) generated 48 warnings
error: could not compile `reed-solomon-novelpoly`; 48 warnings emitted
```

***

~~**NOTE**: Weirdly enough, this does not happen when running `cargo build` or even `cargo run`.~~ (see https://github.com/rust-lang/rust/issues/88365#issuecomment-906783659)

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #88365

the bug in #88365 was caused by some `instance.rs` code using the `PartialEq` impl on `Ty` to check that the type of the associated const in an impl is the same as the type of the associated const in the trait definition. This was wrong for two reasons:
- the check typeck does is that the impl type is a subtype of the trait definition's type (see `mismatched_impl_ty_2.rs` which [was ICEing](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f6d60ebe6745011f0d52ab2bc712025d) before this PR on stable)
- it assumes that if two types are equal then the `PartialEq` impl will reflect that which isnt true for higher ranked types or type level constants when `feature(generic_const_exprs)` is enabled (see `mismatched_impl_ty_3.rs` for higher ranked types which was [ICEing on stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d7af131a655ed515b035624626c62c71))

r? @lcnr

### CODE REVIEW

File: compiler/rustc_middle/src/query/mod.rs [hunk 1]
```diff
@@ -2044,4 +2044,10 @@ rustc_queries! {
         desc { |tcx| "looking up generator diagnostic data of `{}`", tcx.def_path_str(key) }
         separate_provide_extern
     }
+
+    query compare_assoc_const_impl_item_with_trait_item(
+        key: (&'tcx ty::AssocItem, &'tcx ty::AssocItem, ty::TraitRef<'tcx>)
```
Comment (cjgillot) [inline compiler/rustc_middle/src/query/mod.rs:2049]: Can the query directly take 3 `DefId`s and call `associated_item` and `impl_trait_ref` on its own?

Comment (BoxyUwU) [reply compiler/rustc_middle/src/query/mod.rs:2049]: ah yea it could probably even take `(LocalDefId, DefId)`

**Comment by BoxyUwU** [comment]
Seems like none of the repro's for this PR ice anymore on master... I am not sure what PR changed this but I can only assume it was by accident since `error: erroneous constant encountered` with no other explanation is Not really any kind of error message at all. This PR now only gives good errors instead of fixing ICEs :sweat_smile:

**Review by lcnr — COMMENTED** [review]
small nits, then r=me

File: compiler/rustc_hir_analysis/src/check/compare_method.rs [hunk 2]
```diff
@@ -1346,68 +1349,66 @@ pub(crate) fn compare_const_impl<'tcx>(
 
         debug!("compare_const_impl: trait_ty={:?}", trait_ty);
 
-        let err = infcx
+        let maybe_error_reported = infcx
```
[the remark this answers is not in the document]
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/check/compare_method.rs]: not sure why I changed this from `if let` to `map_err` :thinking:
