### PR TITLE
typeck: always expose explicit enum discriminant `AnonConst`s' parent in `generics_of`.

### LINKED ISSUE #70453: Should enum discriminants have generics in scope?
### What are our options?
1. we teach name resolution (`rustc_resolve`) to hide `enum` generic parameters from the discriminant expression
    * this effectively enshrines that we don't want the parameterization to happen
    * I'm not sure this can be backwards-compatible with 2.
2. we keep the current name resolution support but error if we can't evaluate to concrete values
    * the concrete values are necessary to check, at the definition site, that discriminants don't overlap
      * there are special-cases (only the first variant having an explicit discriminant, while the rest keep counting up) where we could check w/o knowing the values
      * long-term we could let more examples compile via explicit `!=` bounds
    * note that expressions that use generics [can still evaluate to concrete values](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ba0ae8e0eb712b342a61a776ac52c62f)
    * we could make this work w/o `#![feature(const_generics)]` (see examples below) by using the same approach as in #70452, as `enum`s are in a similar situation that shouldn't cause query cycles
    * **EDIT**: opened #70825 for this

<hr/>

### Examples of current behavior:

**Note**: `#![feature(const_generics)]` is used below so that this special-case kicks in: https://github.com/rust-lang/rust/blob/62c6006450d8bd33a351673c1f969846d768aab4/src/librustc_typeck/collect.rs#L1183-L1185

Also, note that the reason for the uniform current treatment (which doesn't consider `enum` parameters as not in scope of discriminants), is because `rustc_resolve` treats surrounding generics as being in scope of `AnonConst`s, always - all the bugs later in compilation are due to the lack of lazy normalization (see #43408).

<hr/>

This ICEs currently ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=35f8107d83236450ee805be54af9c56b)):
```rust
#![feature(const_generics)]

#[repr(usize)]
enum Foo<T> {
    Zero = 0,
    SizeOf = std::mem::size_of::<T>(),
}
```
with
```
error: internal compiler error: src/librustc/ty/mod.rs:2538: enum discriminant depends on generic arguments
 --> src/lib.rs:6:14
  |
6 |     SizeOf = std::mem::size_of::<T>(),
  |              ^^^^^^^^^^^^^^^^^^^^^^^^
```

Same thing happens if a `const` parameter is used instead of `size_of::<T>()`.

If we choose option 2, this ICE will turn into a regular error.

<hr/>

**EDIT**: and this currently compiles on nightly ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1d143ce466dded9d7c6f5badc7438c7e)):
```rust
#![feature(const_generics, arbitrary_enum_discriminant)]

#[repr(usize)]
enum MyWeirdOption<T> {
    None = 0,
    Some(T) = std::mem::size_of::<*mut T>(),
}
```
And using `*mut *mut T` instead of `*mut T` would make it work even when `T: Sized` isn't known.
(If not for the substitution failure, you could remove `#![feature(const_generics)]`)

<hr/>

cc @rust-lang/compiler @rust-lang/lang

### PR DESCRIPTION
**Pull request by eddyb**
This is similar to #70452 but for explicit `enum` discriminant constant expressions.
However, unlike #70452, this PR should have no effect on stable code, as while it alleviates #43408 errors, there is no way to actually compile an `enum` with generic parameters *and* explicit discriminants, without `#![feature(arbitrary_enum_discriminant)]`, as explicit discriminant expression don't count as uses of parameters (if they did, they would count as invariant uses).

<hr/>

There's also 2 other commits here, both related to #70453:
* "ty: use `delay_span_bug` in `ty::AdtDef::eval_explicit_discr`." - hides the ICEs demonstrated on #70453, when there are other errors (which the next commit adds)
* "typeck/wfcheck: require that explicit enum discriminants const-evaluate succesfully." - closes #70453 by picking alternative "2", i.e. erroring when a discriminant doesn't fully const-evaluate from the perspective of the `enum` definition

In the future, it might be possible to allow `enum` discriminants to actually depend on parameters, but that will likely require #68436 + some way to restrict the values so no two variants can end up with overlapping discriminants.

As this PR would close #70453, it shouldn't be merged until a decision is reached there.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_typeck/check/wfcheck.rs [hunk 1]
```diff
@@ -411,6 +411,22 @@ fn check_type_defn<'tcx, F>(
                     ObligationCauseCode::MiscObligation,
                 )
             }
+
+            // Explicit `enum` discriminant values must const-evaluate successfully.
```
Comment (Centril) [inline src/librustc_typeck/check/wfcheck.rs:415]: Comment could use some elaboration regarding the "why" as well as a link towards https://github.com/rust-lang/rust/issues/70453.

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -1182,14 +1182,28 @@ fn generics_of(tcx: TyCtxt<'_>, def_id: DefId) -> &ty::Generics {
         }
         // FIXME(#43408) enable this always when we get lazy normalization.
         Node::AnonConst(_) => {
+            let parent_id = tcx.hir().get_parent_item(hir_id);
```
Comment (Centril) [inline src/librustc_typeck/collect.rs:1185]: Nit: bind `let hir = tcx.hir();` earlier in the function to reduce repetition.

**Review by Centril — CHANGES_REQUESTED** [review]

File: src/librustc_typeck/collect.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_typeck/collect.rs:1185]: What's funny is that I copy-pasted these two lines from #70452 - but also I'm not fond of binding `tcx.hir()` due to the ideal future in which we request the `tcx.hir(...)` for a given `LocalDefId` and then use that, binding it wouldn't help with that AFAICT.

Comment (Centril) [reply src/librustc_typeck/collect.rs:1185]: Well it's just a nit, but are there plans for that future though?

**Comment by nikomatsakis** [comment]
FYI: I'm planning to review this this week.

File: src/librustc_typeck/check/wfcheck.rs [hunk 3]
```diff
@@ -1277,6 +1293,7 @@ impl ParItemLikeVisitor<'tcx> for CheckTypeWellFormedVisitor<'tcx> {
 
 struct AdtVariant<'tcx> {
     fields: Vec<AdtField<'tcx>>,
+    explicit_discr: Option<DefId>,
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/wfcheck.rs:1296]: I think a doc-comment here would be nice, even though this is a local struct. Something like:

/// If there is an explicit discriminant on this variant (e.g., `A = 22`), then include the def-id of that expression, so that we can check it is well-formed.

File: src/librustc_typeck/check/wfcheck.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_typeck/check/wfcheck.rs:415]: Just to make sure I'm following along, this concept of "must be evaluatable" is going to ultimately be true for *any* const expression, right? I think this is the basic WF criteria we are working towards?

**Review by nikomatsakis — APPROVED** [review]
r=me, left a few nits

File: src/librustc_typeck/check/wfcheck.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_typeck/check/wfcheck.rs:415]: Yes, at the minimum any `ty::Const` used in the typesystem (array lengths and args to const params). While `enum` discrminants aren't that, they do require strict checks (no overlap), for which successful evaluatability is *a bare minimum*.

**Comment by eddyb** [comment]
Oops, I missed that FCP completed (https://github.com/rust-lang/rust/issues/70453#issuecomment-619608728).
