### PR TITLE
Clarify the usage of "hints" in const_eval.

### LINKED ISSUE #26210: Constant-folding error with negative constant on RHS of shift
```rust
fn main() {
    let a = -1+2isize;
    let _b = a<<(1isize-1);
    let _c = a<<(a+-1);
    let _d = a<<(1isize+-1);
}
```
Produces:
```
<anon>:5:25: 5:27 error: unary negation of unsigned integers may be removed in the future
<anon>:5     let _d = a<<(1isize+-1);
                                 ^~
error: aborting due to previous error
```
I would expect no error.

I think the error message is coming out of `eval_const_expr_with_substs`.

### PR DESCRIPTION
**Pull request by eefriedman**
The "hint" mechanism is essentially used as a workaround to compute
types for expressions which have not yet been type-checked. This
commit clarifies that usage, and limits the effects to the places
where it is currently necessary.

Fixes #26210.

### CODE REVIEW

File: src/librustc/middle/const_eval.rs [hunk 1]
```diff
@@ -913,12 +937,16 @@ pub fn eval_const_expr_with_substs<'tcx, S>(tcx: &ty::ctxt<'tcx>,
...
                               Some(ast_map::NodeTraitItem(ti)) => match ti.node {
                                   ast::ConstTraitItem(ref ty, _) => {
-                                      let substs = get_substs(e.id);
-                                      (resolve_trait_associated_const(tcx,
-                                                                      ti,
-                                                                      trait_id,
-                                                                      substs),
-                                       Some(&**ty))
+                                      if let ExprTypeChecked = ty_hint {
+                                          let substs = tcx.node_id_item_substs(e.id).substs;
```
Comment (pnkfelix) [inline src/librustc/middle/const_eval.rs]: (It took me a little while to convince myself that this ends up being equivalent to the effect we were getting before via the `get_substs` parameter, but I now believe the tables in the `tcx` should match even in the case where `check::_match::check_pat` was passing in a closure that calls `fcx.item_substs()`, so this should be okay.)

File: src/librustc/middle/const_eval.rs [hunk 2]
```diff
@@ -706,26 +717,30 @@ pub_fn_checked_op!{ const_uint_checked_shr_via_int(a: u64, b: i64,.. UintTy) {
...
-                                            ty_hint: Option<Ty<'tcx>>,
-                                            get_substs: S) -> EvalResult
-        where S: Fn(ast::NodeId) -> subst::Substs<'tcx> {
+                                     ty_hint: EvalHint<'tcx>) -> EvalResult {
     fn fromb(b: bool) -> ConstVal { Int(b as i64) }
 
-    let ety = ty_hint.or_else(|| tcx.expr_ty_opt(e));
+    let ety = match ty_hint {
+        ExprTypeChecked => {
+            // We have a type-checked expression; just grab the
```
Comment (pnkfelix) [inline src/librustc/middle/const_eval.rs]: my *personal* preference would be to put these three comments up with the definition for `EvalHint` itself; that provides a central reference point for people reading the code that either constructs or consumes these things.  But that's not a big deal (and I'm sure no one is following that sort of policy universally, probably including me).

File: src/librustc/diagnostics.rs [hunk 3]
```diff
@@ -335,6 +335,24 @@ This error indicates that an attempt was made to divide by zero (or take the
...
+When matching against a range, the compiler verifies that the range is
+non-empty.  Range patterns include both end-points, so this is equivalent to
+requiring the start of the range to be less than or equal to the end of the
+range.
+
+For example:
+
+```
+match 5u32 {
+    // This range is ok, albeit pointless.
```
Comment (pnkfelix) [inline src/librustc/diagnostics.rs]: when I first read this comment, I thought "pointless" was meant to mean "this pattern can never actually match."  But of course this is not what you meant.

Maybe phrase instead as "This range is okay, though it could be trivially replaced with just the single literal `1`" ?

Comment (pnkfelix) [inline src/librustc/diagnostics.rs]: oh I see, you're just migrating this explanation from another file; you didn't write it yourself. so never mind; I can change this myself later.

File: src/librustc/middle/const_eval.rs [hunk 4]
```diff
@@ -706,26 +717,30 @@ pub_fn_checked_op!{ const_uint_checked_shr_via_int(a: u64, b: i64,.. UintTy) {
            uint_shift_body overflowing_shr Uint ShiftRightWithOverflow
 }}
 
-// After type checking, `eval_const_expr_partial` should always suffice. The
-// reason for providing `eval_const_expr_with_substs` is to allow
-// trait-associated consts to be evaluated *during* type checking, when the
-// substs for each expression have not been written into `tcx` yet.
```
Comment (pnkfelix) [inline src/librustc/middle/const_eval.rs]: It might be useful to still include the heart of this comment somewhere.  I.e. having some idea why we need to support const-eval before type-checking is done, and where it arises, is likely to be useful for future people diving into the compiler source code.  The current comment above `EvalHint` doesn't have quite as much info as this comment did in that respect.

**Comment by pnkfelix** [comment]
@eefriedman I'm basically all in favor of this PR.  I've put some feedback up above but you can treat it as an r=me after a rebase.

**Comment by eefriedman** [comment]
Rebased.

**Comment by oli-obk** [comment]
ping @pnkfelix
