### PR TITLE
Split `run-make` into two {`run-make`,`run-make-cargo`} test suites

### LINKED ISSUE #134109: Split `run-make` into two test suites: fast-path that don't need to build cargo and a slow-path that builds cargo
Building stage 1 cargo and rustdoc takes quite a bit of time and is annoying if your run-make test doesn't even need cargo/rustdoc. Building stage 1 cargo for tests that do need cargo is actually necessary because beta cargo (the usual bootstrap cargo) might not have changes that are present in nightly cargo.

### LINKED ISSUE #135573: Cannot run any run-make test without checking out the cargo submodule
I generally want to have as few git submodule checked out as possible in the rustc repo, since all the checked out submodules need to be synced each time they change and I'd like to minimize the number of time I have to run `git submodule update --recursive`. Therefore, I do not have the cargo submodule checked out.

However, this means I cannot run `./x test run-make`. My understanding is that *some* run-make tests need cargo, but most do not, so it is unfortunate that I cannot run the non-cargo-using run-make tests without checking out cargo. Would be nice to check this in the test rather than blanket rejecting the entire test suite when cargo is missing.

(Also maybe one could use bootstrap cargo instead of the submodule? But I assume there's a reason the submodule is used so this probably does not work.)

Cc @jieyouxu

### PR DESCRIPTION
**Pull request by jieyouxu**
## Summary

Split `tests/run-make` into two test suites, to make it faster and more convenient for contributors to run run-make tests that do not need in-tree `cargo`.

| New test suites        | Explanation                                                                                                                                                                                                                              |
| ---------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `tests/run-make`       | The "fast path" test suite intended for run-make tests that do not need in-tree `cargo`. These tests may not use `cargo`.                                                                                                                |
| `tests/run-make-cargo` | The "slow path" test suite that requires checking out `cargo` submodule and building in-tree `cargo`, and thus will have access to in-tree `cargo`. In practice, these constitute a very small portion of the original `run-make` tests. |

This PR carries out [MCP 847: Split run-make test suite into slower-building test suite with suitably-staged cargo and faster-building test suite without cargo](https://github.com/rust-lang/compiler-team/issues/847).
Fixes rust-lang/rust#135573 (for the tests that do not need in-tree `cargo`).
Fixes rust-lang/rust#134109.

## Remarks

- I considered if we want to split by in-tree tools previously. However, as discussed rust-lang/rust#134109, in practice `rustdoc` is not very slow to build, but `cargo` takes a good few minutes. So, the partition boundary was determined to be along in-tree `cargo` availability.
- The `run-make` tests previously that wanted to use `cargo` cannot just use the bootstrap `cargo`, otherwise they would run into situations where bootstrap `cargo` can significantly diverge from in-tree `cargo` (see https://github.com/rust-lang/rust/pull/130642).

---

try-job: aarch64-msvc-1
try-job: test-various
try-job: x86_64-gnu-debug
try-job: aarch64-gnu-debug
try-job: aarch64-apple
try-job: dist-various-1

### CODE REVIEW

File: compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh
Comment (bjorn3) [inline compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh:1]: Can you make it run the run-make-cargo test suite at the bottom of this file?

Comment (jieyouxu) [reply compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh:1]: Oh hecc, good catch, I was so focused on making sure I didn't miss renamed tests, I forgot to also run the new test suite below 🤦

Comment (jieyouxu) [reply compiler/rustc_codegen_cranelift/scripts/test_rustc_tests.sh:1]: Which is also a good reminder -- I need to adjust cg_gcc's tests too

File: compiler/rustc_codegen_gcc/build_system/src/test.rs [hunk 1]
```diff
@@ -1083,27 +1083,36 @@ where
 
 fn test_rustc(env: &Env, args: &TestArg) -> Result<(), String> {
     test_rustc_inner(env, args, |_| Ok(false), false, "run-make")?;
+    test_rustc_inner(env, args, |_| Ok(false), false, "run-make-cargo")?;
```
Comment (jieyouxu) [inline compiler/rustc_codegen_gcc/build_system/src/test.rs:1086]: cc @antoyo @GuillaumeGomez: could you check if these changes look right?

File: compiler/rustc_codegen_gcc/build_system/src/test.rs [hunk 2]
```diff
@@ -1083,27 +1083,36 @@ where
...
         retain_files_callback("tests/failing-run-make-tests.txt", "run-make"),
         false,
         "run-make",
     );
 
-    let result2 = test_rustc_inner(
+    let run_make_cargo_result = test_rustc_inner(
+        env,
+        args,
+        retain_files_callback("tests/failing-run-make-tests.txt", "run-make-cargo"),
```
Comment (jieyouxu) [inline compiler/rustc_codegen_gcc/build_system/src/test.rs:1102]: Remark: I thought about splitting out `failing-run-make-cargo-tests.txt` but that seem like a lot of ceremony, and the ones that were moved into `run-make-cargo` weren't previously in the list anyway.

File: src/bootstrap/src/core/build_steps/test.rs [hunk 3]
```diff
@@ -1773,7 +1779,7 @@ NOTE: if you're sure you want to do this, please open an issue as to why. In the
                 target,
             });
         }
-        if suite == "run-make" {
+        if mode == "run-make" {
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/test.rs:1782]: Remark: I almost missed this until I noticed that the snapshot tests for `./x test run-make-cargo` didn't have a step for building `run-make-support`, and I was like "huh, how strange".

File: src/bootstrap/src/core/builder/mod.rs [hunk 4]
```diff
@@ -1127,8 +1128,8 @@ impl<'a> Builder<'a> {
                 test::RustInstaller,
                 test::TestFloatParse,
                 test::CollectLicenseMetadata,
-                // Run run-make last, since these won't pass without make on Windows
                 test::RunMake,
+                test::RunMakeCargo,
```
Comment (jieyouxu) [inline src/bootstrap/src/core/builder/mod.rs:1132]: Remark: `make` comment above was outdated.

File: src/ci/docker/host-x86_64/test-various/Dockerfile [hunk 5]
```diff
@@ -60,9 +60,10 @@ RUN curl -L https://github.com/bytecodealliance/wasmtime/releases/download/v19.0
   tar -xJ
 ENV PATH "$PATH:/wasmtime-v19.0.0-x86_64-linux"
 
-ENV WASM_WASIP_TARGET=wasm32-wasip1 
+ENV WASM_WASIP_TARGET=wasm32-wasip1
 ENV WASM_WASIP_SCRIPT python3 /checkout/x.py --stage 2 test --host='' --target $WASM_WASIP_TARGET \
   tests/run-make \
+  tests/run-make-cargo \
```
Comment (jieyouxu) [inline src/ci/docker/host-x86_64/test-various/Dockerfile:66]: Remark: these CI changes should not cause CI time to regress, because we should be doing approximately the same amount of work as before (i.e. still building in-tree `cargo`).

File: src/tools/run-make-support/src/external_deps/cargo.rs [hunk 6]
```diff
@@ -1,11 +1,17 @@
...
-use crate::env_var;
 use crate::util::set_host_compiler_dylib_path;
 
-/// Returns a command that can be used to invoke cargo. The cargo is provided by compiletest
-/// through the `CARGO` env var.
+/// Returns a command that can be used to invoke in-tree cargo. The cargo is provided by compiletest
+/// through the `CARGO` env var, and is **only** available for the `run-make-cargo` test suite.
 pub fn cargo() -> Command {
-    let mut cmd = Command::new(env_var("CARGO"));
+    let cargo_path = std::env::var("CARGO").unwrap_or_else(|e| {
```
Comment (jieyouxu) [inline src/tools/run-make-support/src/external_deps/cargo.rs:7]: Remark: in theory, I could gate `run_make_support::cargo` behind a cargo feature flag (`#[cfg(feature = "is_run_make_cargo_suite")]`) or sth, but that feels like overkill, and makes the `run_make_support` build logic more complicated.

Comment (Kobzol) [reply src/tools/run-make-support/src/external_deps/cargo.rs:7]: I don't think we need to use a feature, panic is enough.

**Comment by Kobzol** [comment]
Looks great, thank you!

@bors r+ rollup=never
