### PR TITLE
show macro backtrace with -Z flag

### LINKED ISSUE #39413: useless errors with macro in a separate crate
TL;DR: I'm annoyed about `note: this error originates in a macro outside of the current crate` and want a way to turn it off and get back the error backtrace that tells me where the problem is.

I separated some of my utility code and macros into a `utils` crate for faster compile times. In this error, I have a macro in there `rpc!`, which invokes another macro, `guilty!`. This requires the crate that invokes `rpc!` to also import the crate that defines `guilty!`, but I forgot to do that. However, the error message gives me no way to find that out because it doesn't show where the error actually occurs within the `rpc!` macro:

```
error: macro undefined: 'guilty!'
   --> crates/back/flow/src/lib.rs:374:17
    |
374 |                 assert!(rpc!(tx, CmdFrom::Start, service.clone(), data.clone()).unwrap());
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro outside of the current crate
```

In this case I wrote all the crates in question. But even if I didn't, and I were going to submit a bug to the author of `rpc!`, there's no useful information in this error message. Can there be a way to get back the error information, either by a compiler switch or using cargo's workspace feature or something?

cc @jonathandturner

### PR DESCRIPTION
**Pull request by durka**
Fixes #39413 by adding a facility to restore the "old school" macro expansion backtraces (previously removed in https://github.com/rust-lang/rust/commit/61865384b8fa6d79d2b36cbd7c899eaf15f4aeea).

The restored functionality is accessed through the flag `-Z external-macro-backtrace`. Errors showing the truncated backtraces will suggest this flag.

### Example

Code: <details>
`a/src/lib.rs`
```rust
#[macro_export]
macro_rules! a {
    () => { a!(@) };
    (@) => { a!(@@) };
    (@@) => {
        syntax error;
    }
}
```
`b/src/main.rs`
```rust
#[macro_use] extern crate a;

macro_rules! b {
    () => { b!(@) };
    (@) => { b!(@@) };
    (@@) => {
        syntax error;
    }
}

fn main() {
    a!();
    b!();
}
```
</details>

<br/><br/>
Running without env var (note: first error is from remote macro, second from local macro): 

<details>

```
$ cargo +custom run
   Compiling b v0.1.0
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
  --> src/main.rs:12:5
   |
12 |     a!();
   |     ^^^^^
   |     |
   |     expected one of 8 possible tokens here
   |     unexpected token
   |
   = note: this error originates in a macro outside of the current crate (run with RUST_MACRO_BACKTRACE=1 for more info)

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
  --> src/main.rs:7:16
   |
7  |         syntax error;
   |               -^^^^^ unexpected token
   |               |
   |               expected one of 8 possible tokens here
...
13 |     b!();
   |     ----- in this macro invocation

error: aborting due to 2 previous errors

error: Could not compile `b`.

To learn more, run the command again with --verbose.
```
</details>
The output is the same as today, except for an addition to the note which aids discoverability of the new environment variable.

<br/><br/>
Running _with_ env var:
<details>

```
$ RUST_MACRO_BACKTRACE=1 cargo +custom run
   Compiling b v0.1.0
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
 --> <a macros>:1:72
  |
1 | (  ) => { a ! ( @ ) } ; ( @ ) => { a ! ( @ @ ) } ; ( @ @ ) => { syntax error ;
  |                                                                       -^^^^^ unexpected token
  |                                                                       |
  |                                                                       expected one of 8 possible tokens here
src/main.rs:12:5: 12:10 note: in this expansion of a! (defined in <a macros>)
<a macros>:1:11: 1:20 note: in this expansion of a! (defined in <a macros>)
<a macros>:1:36: 1:47 note: in this expansion of a! (defined in <a macros>)

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
 --> src/main.rs:7:16
  |
7 |         syntax error;
  |               -^^^^^ unexpected token
  |               |
  |               expected one of 8 possible tokens here
src/main.rs:12:5: 12:10 note: in this expansion of a! (defined in <a macros>)
<a macros>:1:11: 1:20 note: in this expansion of a! (defined in <a macros>)
<a macros>:1:36: 1:47 note: in this expansion of a! (defined in <a macros>)

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
 --> src/main.rs:7:16
  |
7 |         syntax error;
  |               -^^^^^ unexpected token
  |               |
  |               expected one of 8 possible tokens here
src/main.rs:13:5: 13:10 note: in this expansion of b! (defined in src/main.rs)
src/main.rs:4:13: 4:18 note: in this expansion of b! (defined in src/main.rs)
src/main.rs:5:14: 5:20 note: in this expansion of b! (defined in src/main.rs)

error: aborting due to 2 previous errors

error: Could not compile `b`.

To learn more, run the command again with --verbose.
```
</details>

The output is hard to read, but better than nothing (and it's exactly what we used to have before the infamous `fix_multispans_in_std_macros`).

<br/><br/>
Wishlist:

- Save the actual source of macros in crate metadata, not just AST, so the output can be improved
    - Hopefully this would allow line numbers in the trace as well
- Show the actual macro invocations in the traces

r? @nrc

### CODE REVIEW

**Comment by oli-obk** [comment]
Can you add a ui test?

**Comment by durka** [comment]
Sure, though I expect the output to change as this facility is improved and modernized. In particular, the error for the non-local macro is emitted twice (once from `<a macros>` with the AST-ified formatting, and once from `src/main.rs`) and I wouldn't mind if _one_ of those was "fixed" to show the top-level macro invocation.

**Comment by durka** [comment]
Added test.

**Comment by kennytm** [comment]
I'm not convinced that this should be an environment variable instead of a `-Z` option (a `-Z` option can be feature-gated, the env var cannot).

**Comment by durka** [comment]
Well, we could just restrict the environment variable to only have an effect on nightly. (In general I think restricting useful tools for no reason is not helpful, especially since debugging macro expansion across compiler versions is a common occurrence, though I might feel differently if this were introducing new functionality instead of just restoring output that was removed.)

That being said, if `-Z` is the way to get this done then I'll do it. Initially it seemed to me like a large amount of plumbing to add. I guess the way to go is:

1. Add a debugging option [to the session](https://github.com/rust-lang/rust/blob/f0fe716dbcbf2363ab8f929325d32a17e51039d0/src/librustc/session/config.rs#L936)
2. ??? <--- this is the plumbing I can't figure out, how is the error emitter supposed to find out about the session options?
3. Add a `macro_backtraces: bool` flag to [`EmitterWriter`](https://github.com/rust-lang/rust/blob/f0fe716dbcbf2363ab8f929325d32a17e51039d0/src/librustc_errors/emitter.rs#L107) and [its constructor](https://github.com/rust-lang/rust/blob/f0fe716dbcbf2363ab8f929325d32a17e51039d0/src/librustc_errors/emitter.rs#L120) which is called [here](https://github.com/rust-lang/rust/blob/f0fe716dbcbf2363ab8f929325d32a17e51039d0/src/librustc_driver/lib.rs#L141)

**Comment by shepmaster** [comment]
ping @rust-lang/compiler — we haven't heard from @nrc in over 6 days, would you mind assigning a new reviewer?

**Comment by shepmaster** [comment]
Ok, @rust-lang/compiler — I'll roll a die for you:

r? @petrochenkov

**Comment by petrochenkov** [comment]
@durka 
>??? <--- this is the plumbing I can't figure out, how is the error emitter supposed to find out about the session options?

See https://github.com/rust-lang/rust/pull/45205 for an example.
An option is added into `src/librustc/session/config.rs` and then used through `session.opts.debugging_opts.my_option`.

**Comment by durka** [comment]
Thanks @petrochenkov I will follow that example!

**Comment by durka** [comment]
@petrochenkov 

So, the emitter seems to have no reference to any session or context. That's the problem. And there isn't a session to pass in when creating the `EmitterWriter` because `run_compiler` doesn't return one if it fails.

**Comment by durka** [comment]
Actually I think that call to `EmitterWriter::new` that I pinpointed is the wrong one, but I'm not sure where I should be looking. Searching for other places they are constructed, some have a session available and some do not.

**Comment by petrochenkov** [comment]
@durka 
Unfortunately, I'm no more familiar with that infrastructure than you.

**Comment by durka** [comment]
I found a way to do it, but it required making some fields public and coordinating with rustfmt now. Please review.

File: src/librustc_errors/emitter.rs [hunk 1]
```diff
@@ -1226,6 +1247,30 @@ impl EmitterWriter {
             }
         }
     }
+
+    fn render_macro_backtrace_old_school(&self,
```
Comment (nrc) [inline src/librustc_errors/emitter.rs]: `old_school` isn't very helpful here - what distinguishes it from a normal backtrace? `expanded` or `complete` or something might be better

File: src/librustc/session/config.rs [hunk 2]
```diff
@@ -1036,6 +1036,8 @@ options! {DebuggingOptions, DebuggingSetter, basic_debugging_options,
           "run all passes except translation; no output"),
     treat_err_as_bug: bool = (false, parse_bool, [TRACKED],
           "treat all errors that occur as bugs"),
+    macro_backtrace: bool = (false, parse_bool, [UNTRACKED],
```
Comment (nrc) [inline src/librustc/session/config.rs]: could you use `full_macro_backtrace` or something? The name is a bit confusing as is because we get a macro backtrace in any case.

File: src/librustc_errors/lib.rs [hunk 3]
```diff
@@ -251,21 +252,24 @@ impl Handler {
...
                             treat_err_as_bug: bool,
+                            macro_backtrace: bool,
                             cm: Option<Rc<CodeMapper>>)
                             -> Handler {
         let emitter = Box::new(EmitterWriter::stderr(color_config, cm, false));
-        Handler::with_emitter(can_emit_warnings, treat_err_as_bug, emitter)
+        Handler::with_emitter(can_emit_warnings, treat_err_as_bug, macro_backtrace, emitter)
     }
 
     pub fn with_emitter(can_emit_warnings: bool,
```
Comment (nrc) [inline src/librustc_errors/lib.rs]: Could you add another method rather than adding another bool flag to this one? That would be more self-documenting (bools tell the reader nothing), less susceptible to bugs (since it is easy enough to confuse the two bools here), and avoids a breaking change.

File: src/librustc/session/config.rs (hunk 2 above)
Comment (durka) [reply src/librustc/session/config.rs]: Sure. Or maybe `external_macro_backtrace` since you do get a full one for local macros?

File: src/librustc_errors/emitter.rs (hunk 1 above)
Comment (durka) [reply src/librustc_errors/emitter.rs]: Yeah, I just used the name from the commit I'm partially reverting. I think it [looks](https://github.com/rust-lang/rust/pull/45545/files#diff-09f53becd1a865c0fd757a5eb39fd746) and bit "old school" (it doesn't have fancy span notes or anything).

File: src/librustc_errors/lib.rs (hunk 3 above)
Comment (durka) [reply src/librustc_errors/lib.rs]: Do you mean a new method like `Handler::with_backtracing_emitter(...)`? We also thought of always initializing the flag to `false` and providing a setter. But that's kind of a weird mixture of constructor flags and setters which seems like it ought to be refactored into a settings struct anyway.

File: src/librustc/session/config.rs (hunk 2 above)
Comment (nrc) [reply src/librustc/session/config.rs]: sure, works for me

File: src/librustc_errors/lib.rs (hunk 3 above)
Comment (nrc) [reply src/librustc_errors/lib.rs]: Maybe `with_emitter_with_settings` and take a settings struct to allow adding more flags in the future which are similarly detailed.

Comment (durka) [reply src/librustc_errors/lib.rs]: I'm calling it `with_emitter_and_flags` and this should reduce the size of the patch / avoid breaking rustfmt. But we should still refactor users of `with_emitter`/`with_tty_emitter` and remove those at some point!

**Comment by durka** [comment]
Addressed comments.

**Comment by kennytm** [comment]
@durka That `(run with -Z external-macro-backtrace for more info)` message is going to show up in beta and stable channel?

**Comment by durka** [comment]
Argh. The gating causes one problem after another... Good point. Should I
add "on nightly" to the message?

**Comment by kennytm** [comment]
@durka Perhaps add a channel check (use `UnstableFeatures::from_environment().is_nightly_build()` or plumb through `sess.opts.unstable_features`) and don't emit it at all when in beta/stable. But then we need to figure out what to do with the UI tests after entering beta...

**Comment by durka** [comment]
It must be discoverable, that's the point of having a message. We've got users [asking](https://www.reddit.com/r/rust/comments/7edds1/how_does_a_stable_channel_pleb_debug_macros/) why there is nothing available on stable.

**Comment by RReverser** [comment]
Just wanted to say thanks for this - upgraded to nightly and it immediately helped me to debug an annoying error inside of nom macro. Hopefully this becomes stable someday.

File: src/librustc_errors/emitter.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_errors/emitter.rs]: @durka would you be against using the full span machinery for them or would you think it'd be too verbose?

Comment (durka) [reply src/librustc_errors/emitter.rs]: The more spans the better, probably. I'm afraid I'm not too familiar with the new span hardware. What would it look like?

Comment (estebank) [reply src/librustc_errors/emitter.rs]: Some changes will need to be made to the macro expansion machinery to avoid bogus spans (`<a macros>:1:36: 1:47 note: in this expansion of a! (defined in <a macros>)`), but I think it could be made to look something along the lines of:

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
  -->  a/src/lib.rs:6:16
3  |     () => { a!(@) };
   |             ----- in this expansion of `a!` (#2)
4  |     (@) => { a!(@@) };
   |              ------ in this expansion of `a!` (#3)
5  |     (@@) => {
6  |         syntax error;
   |                ^^^^^ expected one of 8 possible tokens here
  ::: src/main.rs
   |
12 |     a!();
   |     ----- in this expansion of `a!` (#1)

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `error`
  --> src/main.rs:7:16
   |
4  |     () => { b!(@) };
   |             ----- in this expansion of `b!` (#2)
5  |     (@) => { b!(@@) };
   |              ------ in this expansion of `b!` (#3)
6  |     (@@) => {
7  |         syntax error;
   |                ^^^^^ expected one of 8 possible tokens here
13 |     b!();
   |     ----- in this expansion of `b!` (#1)

error: aborting due to 2 previous errors

error: Could not compile `b`.
```

Comment (durka) [reply src/librustc_errors/emitter.rs]: Well that mockup looks really good to me! :)

Comment (estebank) [reply src/librustc_errors/emitter.rs]: @durka suggestion implemented in #46605. The output is not perfect as it is pointing at the pretty printed expanded macro code instead of the actual code, but it is close enough :)

**Comment by cramertj** [comment]
Is there a tracking issue for stabilizing this flag?

**Comment by durka** [comment]
Let's make one.

**Comment by durka** [comment]
In fact, should there be a tracking issue for *every* `-Z` flag?

**Comment by nikomatsakis** [comment]
@durka I don't think so. Many of them have no particular path to stabilization.

**Comment by Aaron1011** [comment]
Was a tracking issue ever filed?
