### PR TITLE
Improve and fix mpsc documentation

### LINKED ISSUE #37915: Documentation phrase about panics in mpsc channel may be obsolete
https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html#main

> As with asynchronous channels, all senders **will panic** in send if the Receiver has been destroyed.

https://doc.rust-lang.org/std/sync/mpsc/struct.SyncSender.html#send.v

> This function **will never panic**, but it may return Err if the Receiver has disconnected and is no longer able to receive information.

### PR DESCRIPTION
**Pull request by Cobrand**
Closes #37915

This commit enhances documentation with several links and
fixes an error in the `sync_channel` documentation as well:
`send` doesn't panic when the senders are all disconnected

r? @steveklabnik

### CODE REVIEW

**Comment by mfarrugi** [comment]
Are the references to 'runtime' also outdated? eg. L235

**Comment by Cobrand** [comment]
@mfarrugi I don't really get what you mean ... could you explain more in detail ?

**Comment by mfarrugi** [comment]
I'm not clear on what runtime refers to in 
`// A major goal of these channels is to work seamlessly on and off the runtime.`
But I think it refers to the [old rust runtime](https://doc.rust-lang.org/0.12.0/guide-runtime.html)

**Comment by Cobrand** [comment]
Indeed it looks like the mention of the runtime is part of the old documentation that was kept here.

A quick git blame told me that most the the comments in this file were from 2013 or 2014, so definitely way before the first release of Rust.

That might need another PR though ?

**Comment by Cobrand** [comment]
This has been opened for several days but I don't see any issue, I guess I'll try my luck with someone else ?
r? @GuillaumeGomez

File: src/libstd/sync/mpsc/mod.rs [hunk 1]
```diff
@@ -458,6 +458,13 @@ impl<T> UnsafeFlavor<T> for Receiver<T> {
 /// All data sent on the sender will become available on the receiver, and no
 /// send will block the calling thread (this channel has an "infinite buffer").
 ///
+/// If the [`Receiver`] is disconnected while trying to [`send`] with the
```
Comment (GuillaumeGomez) [inline src/libstd/sync/mpsc/mod.rs]: All functions/methods name should have `()` at the end.

File: src/libstd/sync/mpsc/mod.rs [hunk 2]
```diff
@@ -487,18 +494,23 @@ pub fn channel<T>() -> (Sender<T>, Receiver<T>) {
...
+/// Like asynchronous channels, the [`Receiver`] will block until a message
 /// becomes available. These channels differ greatly in the semantics of the
 /// sender from asynchronous channels, however.
 ///
 /// This channel has an internal buffer on which messages will be queued. `bound`
 /// specifies the buffer size. When the internal buffer becomes full, future sends
 /// will *block* waiting for the buffer to open up. Note that a buffer size of 0
-/// is valid, in which case this becomes  "rendezvous channel" where each send will
-/// not return until a recv is paired with it.
+/// is valid, in which case this becomes  "rendezvous channel" where each [`send`]
```
Comment (GuillaumeGomez) [inline src/libstd/sync/mpsc/mod.rs]: Extra whitespace before "rendezvous". By the way, shouldn't it be rendez-vous? French in english is so strange haha.

Comment (GuillaumeGomez) [inline src/libstd/sync/mpsc/mod.rs]: Oh and same comment for `send` in here.

File: src/libstd/sync/mpsc/mod.rs [hunk 3]
```diff
@@ -487,18 +494,23 @@ pub fn channel<T>() -> (Sender<T>, Receiver<T>) {
...
+/// will not return until a recv is paired with it.
+///
+/// Like asynchronous channels, if the [`Receiver`] is disconnected while trying
+/// to [`send`] with the [`SyncSender`], the [`send`] method will return an
```
Comment (GuillaumeGomez) [inline src/libstd/sync/mpsc/mod.rs]: Same comment for `send`.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]

File: src/libstd/sync/mpsc/mod.rs (hunk 2 above)
Comment (Cobrand) [inline src/libstd/sync/mpsc/mod.rs]: Being french myself I had my doubts about that but in English it's definitely rendezvous : 

https://fr.wikipedia.org/wiki/Rendez-vous
https://en.wikipedia.org/wiki/Rendezvous

For some unknown and I guess historical reasons the translators dropped the dash

File: src/libstd/sync/mpsc/mod.rs (hunk 1 above)
Comment (Cobrand) [inline src/libstd/sync/mpsc/mod.rs]: Done

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
All good, thanks!

@bors: r+ rollup
