### PR TITLE
Suggest casting on numeric type error

### LINKED ISSUE #47168: Expected u32 found usize error on array/slice gives unhelpful help text
```
fn main() {
    let array = [1, 2, 3];
    test(array.len());
}

fn test(length: u32) {
    println!("{}", length);
}
```

Gives the following compile time error on rustc 1.22.1 (stable):

```
Compiling playground v0.0.1 (file:///playground)
error[E0308]: mismatched types
 --> src/main.rs:3:10
  |
3 |     test(array.len());
  |          ^^^^^^^^^^^ expected u32, found usize
  |
  = help: here are some functions which might fulfill your needs:
          - .count_ones()
          - .count_zeros()
          - .leading_zeros()
          - .trailing_zeros()

error: aborting due to previous error

error: Could not compile `playground`.
```

I'm assuming there's a lot of nuance in the engine that gives suggestion so I don't know how I would personally codify the rules (and even if casting as a u32 is always appropriate since I guess it could overflow) but I do know that the suggestions definitely do not point me in the right direction.

### PR DESCRIPTION
**Pull request by estebank**
Re #47168.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Shouldn't we suggest to use `from` instead of casting?

**Comment by GuillaumeGomez** [comment]
More globally, I'm not sure talking about size fit/shortage is a good idea. Just talking about `from` should be enough for most cases, don't you think?

File: src/librustc_typeck/check/demand.rs [hunk 1]
```diff
@@ -306,12 +304,181 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                    }
+                    true
+                }
+                (&ty::TyFloat(ref exp), &ty::TyFloat(ref found)) => {
+                    if found.bit_width() > exp.bit_width() {
+                        err.span_suggestion(expr.span,
+                                            &format!("{}, producing the closest possible value",
+                                                     msg),
+                                            suggestion);
+                        err.warn("casting here will cause Undefined Behavior if the value is \
```
Comment (varkor) [inline src/librustc_typeck/check/demand.rs]: Should "undefined behaviour" be capitalised like this? [It doesn't seem to be](https://github.com/rust-lang/rust/blob/565907fefb2a69c279b59bffa84c6d30129cafe9/src/librustc_lint/builtin.rs#L1236) typical in error messages.

**Comment by estebank** [comment]
> More globally, I'm not sure talking about size fit/shortage is a good idea.

I find the possibility of using the compiler errors to teach the language appealing. Presenting some of the possible trade offs inline like this seems like a great opportunity, even though completely I agree with the problems presented by `as`.

> Just talking about from should be enough for most cases, don't you think?

Part of what gave me pause is that `From` is not implemented for all conversions, only for the ones that cannot fail, and `TryFrom` is confined to nightly behind a feature flag. Also, the suggestion becomes much more verbose in that case (and only applies to nightly):

```
fn foo<T>(x: T) {}
fn main() {
    foo::<u32>(3_i32);
}
```
after:
```
#![feature(try_from)]
use std::convert::TryFrom;

fn foo<T>(x: T) {}
fn main() {
    foo::<u32>(u32::try_from(3_i32).unwrap());
}
```

That being said, the way I wrote the code was to make it possible to only show a subset of these suggestions depending on the case. I could suggest `into()` when it is supported (growing an type, `u16` to `u32`), and remain silent in the other cases.

**Comment by estebank** [comment]
Updated the PR to only suggest `.into()` conversions. The code for suggesting casts is still there, just never triggered (it is gated on the type of expression, right now not enabled for any).

**Comment by GuillaumeGomez** [comment]
That's problematic that `TryFrom` is still nightly only... And where is `From` implementation missing?

**Comment by estebank** [comment]
@GuillaumeGomez in https://github.com/rust-lang/rust/pull/47247/files#diff-1743dc5c92f33d15fb1e903d7ad3ce58 (which is admittedly very verbose, as it has every single possible numeric type mismatch) you can see that the only suggestions provided are for the types that have a `From` implementation:

 - within the same numeric type, being signed or unsigned, there's a `From` implementation from the type with a lesser bit width to the wider type (`u16` -> `u32`, `i32` -> `i64`),
 - from `f32` to `f64`,
 - from 32 bit integers and lower to `f64`
 - from 16 bit integers and lower to `f32`.

File: src/librustc_typeck/check/demand.rs [hunk 2]
```diff
@@ -306,12 +304,251 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+        //
+        // We want to minimize the amount of casting operations that are suggested, as it can be a
+        // lossy operation with potentially bad side effects, so we only suggest when encountering
+        // an expression that indicates that the original type couldn't be directly changed.
+        //
+        // For now, don't suggest casting with `as`.
+        let can_cast = false;
+
+        let needs_paren = match expr.node {
+            hir::ExprBinary(..) => true,
```
Comment (petrochenkov) [inline src/librustc_typeck/check/demand.rs]: I think you can reuse `syntax::util::parser::expr_precedence` here and get more precise result.
See `fn print_expr_method_call` in `pprust.rs` for an example.

File: src/librustc_typeck/check/demand.rs [hunk 3]
```diff
@@ -306,12 +304,251 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                                     msg),
+                                            into_suggestion);
+                    } else if can_cast {
+                        err.span_suggestion(expr.span,
+                                            &format!("{}, producing the closest possible value",
+                                                     msg),
+                                            cast_suggestion);
+                        err.warn("casting here will cause undefined behavior if the value is \
+                                  finite but larger or smaller than the largest or smallest \
+                                  finite value representable by `f32` (this is a bug and will be \
```
Comment (petrochenkov) [inline src/librustc_typeck/check/demand.rs]: float <-> float conversions are buggy?
I don't think this is true. There's [`-Z saturating-float-casts`](https://github.com/rust-lang/rust/pull/45205) for correcting float -> int casts, but everything else is already correct, if I remember correctly.

File: src/librustc_typeck/check/demand.rs [hunk 4]
```diff
@@ -306,12 +304,251 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                  cannot be represented by the target integer type, including \
+                                  `Inf` and `NaN` (this is a bug and will be fixed)");
+                    }
+                    true
+                }
+                (&ty::TyFloat(ref exp), &ty::TyUint(ref found)) => {
+                    if exp.bit_width() > found.bit_width().unwrap_or(256) {
+                        err.span_suggestion(expr.span,
+                                            &format!("{}, producing the floating point \
+                                                      representation of the integer, rounded if \
```
Comment (petrochenkov) [inline src/librustc_typeck/check/demand.rs]: If `into` is available, then the conversion will be lossless and no rounding will happen.
Also `into` is not available for `i/usize` and floats.

File: src/librustc_typeck/check/demand.rs [hunk 5]
```diff
@@ -306,12 +304,251 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                                      msg),
+                                            cast_suggestion);
+                    }
+                    true
+                }
+                (&ty::TyFloat(ref exp), &ty::TyInt(ref found)) => {
+                    if exp.bit_width() > found.bit_width().unwrap_or(256) {
+                        err.span_suggestion(expr.span,
+                                            &format!("{}, producing the floating point \
+                                                      representation of the integer, rounded if \
```
Comment (petrochenkov) [inline src/librustc_typeck/check/demand.rs]: Same as https://github.com/rust-lang/rust/pull/47247/files#r160534951

**Comment by petrochenkov** [comment]
Looks pretty useful.
I'm also okay with dead code from `can_cast = false` because the implementation doesn't look "complete" without it, something can be done with it later.
I left some comments inline.

File: src/librustc_typeck/check/demand.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: This warning is taken from https://doc.rust-lang.org/book/first-edition/casting-between-types.html#numeric-casts. Is it out of date?

Comment (petrochenkov) [reply src/librustc_typeck/check/demand.rs]: Oh, indeed, https://github.com/rust-lang/rust/issues/15536 is still open.
Ping @rkruppe just in case.

Comment (rkruppe) [reply src/librustc_typeck/check/demand.rs]: The default behavior is indeed still UB, saturating casts are still opt-in.

File: src/librustc_typeck/check/demand.rs (hunk 4 above)
Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: Updated message.

The suggestion is not given for `isize`/`usize` (that's what the `unwrap(256)` is doing). Added comment to that effect.

File: src/librustc_typeck/check/demand.rs (hunk 5 above)
Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: Done.

File: src/librustc_typeck/check/demand.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: Updated.

File: src/librustc_typeck/check/demand.rs [hunk 6]
```diff
@@ -306,12 +305,248 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+        // mismatch.
+        //
+        // We want to minimize the amount of casting operations that are suggested, as it can be a
+        // lossy operation with potentially bad side effects, so we only suggest when encountering
+        // an expression that indicates that the original type couldn't be directly changed.
+        //
+        // For now, don't suggest casting with `as`.
+        let can_cast = false;
+
+        let needs_paren = expr_precedence(expr) < (AssocOp::As.precedence() as i8);
```
Comment (petrochenkov) [inline src/librustc_typeck/check/demand.rs]: Argh, this `expr_precedence` works on AST.
There's another one in `rustc::hir::print`.
Also, `AssocOp::As.precedence()` -> `PREC_POSTFIX`.

Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: I'm gonna add a commit to merge both into one place (new enum that only holds the type to precedence mapping, and an into impl for `{hir, ast}::Expr` so that there's only one source of truth for this. Started that yesterday but went to bed before I could complete it.

**Comment by estebank** [comment]
Fixed.

File: src/libsyntax/ast.rs [hunk 7]
```diff
@@ -903,6 +917,129 @@ pub struct Expr {
     pub attrs: ThinVec<Attribute>
 }
 
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub enum ExprPrecedence {
```
Comment (petrochenkov) [inline src/libsyntax/ast.rs]: Could you move all this stuff from `ast.rs` somewhere, e.g. into `util/parser.rs` where it was previously.
This is not a part of AST or HIR, really, it's a parsing-specific detail.

Comment (estebank) [reply src/libsyntax/ast.rs]: Done. Waiting for the tests to run to make sure nothing broke.
