### PR TITLE
explain doc comments in macros a bit

### LINKED ISSUE #92846: Commeting a macro branch throws a misleading diagnostic
Commenting a macro branch:

```rust
macro_rules! something {
    /// This macro branch expands to nottin'
    () => { }
}
```
(https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=425968561ccf8122bba35a7396e2d5dd)

... throws an error:

```
error: no rules expected the token `[`
 --> src/lib.rs:...:...
  |
  |     /// This macro branch expands to nottin'
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
```

Now, this error message makes sense if you think of `///` as a shorthand for `#[doc = "..."]`, but imho it'd be better to print something in terms of:

```
error: macro branches can't have outer-line doc comments
 --> src/lib.rs:...:...
  |
  |     /// This macro branch expands to nottin'
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `///` is an outer-doc comment

hint: either move the comment before the macro:

    /// This macro branch expands to nottin'
    macro_rules! something {
        () => { }
    }

hint: ... or replace `///` with `//`:

    macro_rules! something {
        // This macro branch expands to nottin'
        () => { }
    }
```

### LINKED ISSUE #97850: Misleading diagnostic when passing a doc comment to macro
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ef09a8b3babfcc78309404420421b477
```rust
macro_rules! foo {
    () => {};
}
foo!(
    ///
);
```

The current output is:

```
error: no rules expected the token `#`
 --> src/lib.rs:5:5
  |
1 | macro_rules! foo {
  | ---------------- when calling this macro
...
5 |     ///
  |     ^^^ no rules expected this token in macro call

error: could not compile `playground` due to previous error
```

Replacing the empty macro pattern with `#`, `#[]`, `#[doc]` or `#[doc=]` will result in near-identical error messages about the `[`, `doc`, `=` or string literal tokens, respectively. This is misleading, because these tokens do not exist in the original source code. If I didn't already know that doc comments get turned into doc attributes in the form `#[doc = "..."]`, I probably would have assumed this was a compiler bug. A possible solution would be to point this out in the diagnostic (formatting and contents very much up for debate):

```
error: no rules expected the token `#`
 --> src/lib.rs:5:5
  |
1 | macro_rules! foo {
  | ---------------- when calling this macro
...
5 |     ///
  |     ^^^ no rules expected `#` token in macro call
hint: `#` token appears because doc comments are transformed into doc attributes of the form `#[doc = "..."]`

error: could not compile `playground` due to previous error
```

This is related to (and possibly a generalization of) #92846.

### PR DESCRIPTION
**Pull request by compiler-errors**
Open to suggestions on improving this... macro parsing is very foreign to me.

Should we have a structured suggestion to turn them into their regular non-doc comments?

Fixes #92846
Fixes #97850

### CODE REVIEW

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 1]
```diff
@@ -590,6 +594,20 @@ pub fn compile_declarative_macro(
...
 }
 
+fn annotate_doc_comment(
+    err: &mut DiagnosticBuilder<'_, ErrorGuaranteed>,
+    sm: &SourceMap,
+    span: Span,
+) {
+    if let Ok(src) = sm.span_to_snippet(span) {
+        if src.starts_with("///") || src.starts_with("/**") {
+            err.span_label(span, "outer doc comments expand to `#[doc = \"...\"]`, which is what this macro attempted to match");
```
Comment (davidtwco) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:604]: nit: you could make these `SessionSubdiagnostic`s or otherwise translatable with typed identifiers

**Review by davidtwco — APPROVED** [review]
LGTM, r=me unless you want to address the comment first

File: src/test/ui/parser/macro/macro-doc-comments-1.stderr [hunk 2]
```diff
@@ -5,7 +5,10 @@ LL | macro_rules! outer {
    | ------------------ when calling this macro
 ...
 LL |     //! Inner
-   |     ^^^^^^^^^ no rules expected this token in macro call
+   |     ^^^^^^^^^
+   |     |
+   |     no rules expected this token in macro call
+   |     inner doc comments expand to `#![doc = "..."]`, which is what this macro attempted to match
```
Comment (jyn514) [inline src/test/ui/parser/macro/macro-doc-comments-1.stderr:11]: "which is what this macro attempted to match" seems confusing. It seems to be using "macro" to mean "the compiler's expansion of this macro". But I would normally expect it to mean "the matchers defined in the macro", which makes this confusing - if it matches, why didn't it compile?

I think just the first half (this is a doc comment) is clear enough, maybe keep only that?

Maybe say something like

File: compiler/rustc_expand/src/mbe/macro_rules.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:604]: can do!

File: src/test/ui/parser/macro/macro-doc-comments-1.stderr (hunk 2 above)
Comment (compiler-errors) [reply src/test/ui/parser/macro/macro-doc-comments-1.stderr:11]: @jyn514, I wanted to stress that the macro _sees_ the token stream `# ! [ doc =` and not `/// doc comment`, and that's why we get "unexpected `!` token". is there a clearer way to express this?

**Comment by compiler-errors** [comment]
re-requesting review for last commit

@rustbot ready

File: src/test/ui/parser/macro/macro-doc-comments-1.stderr (hunk 2 above)
Comment (davidtwco) [reply src/test/ui/parser/macro/macro-doc-comments-1.stderr:11]: I don't find this message confusing, so I'll approve and if we come up with something better then we change it to that in a follow up.

**Review by davidtwco — APPROVED** [review]
r=me after rebase
