### PR TITLE
normalize field projection ty to fix broken MIR issue

### LINKED ISSUE #71344: `broken MIR` `NoSolution` sized array initialiser with addition in generic tuple destructure
According to my CI this started 2020-04-16 (https://travis-ci.org/github/thepowersgang/rust_os/builds/675740673) - `nightly-x86_64-unknown-linux-gnu installed - rustc 1.44.0-nightly (d2230290f 2020-04-15)`

## Code

```Rust
fn main() {}
// NOTE: Lifetime param needed.
struct DirEnts<'a>
{
    _cluster: ::std::marker::PhantomData<&'a ()>,
}
impl<'a> DirEnts<'a>
{
    #[allow(dead_code)]
    fn next(&mut self) -> [u8; 12] {
        // NOTE: Tuple destructure needed
        // NOTE: Arithmatic needed
        let (outname,) = ([0u8; 12+0],);
        outname
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (52fa23add 2020-04-18)
binary: rustc
commit-hash: 52fa23add6fb0776b32cc591ac928618391bdf41
commit-date: 2020-04-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
[No write since last change]
error: internal compiler error: broken MIR in DefId(0:9 ~ 1[317d]::{{impl}}[0]::next[0]) ((_3.0: [u8; 12])): bad field access ([u8; _]: [u8; 12]): NoSolution
  --> /home/tpg/1.rs:15:8
   |
15 |         let (outname,) = ([0u8; 12+0],);
   |              ^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::drop_in_place
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  16: core::ptr::drop_in_place
  17: rustc_interface::interface::run_compiler_in_existing_thread_pool
  18: scoped_tls::ScopedKey<T>::set
  19: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (52fa23add 2020-04-18) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack

shell returned 101
```

### PR DESCRIPTION
**Pull request by spastorino**
Fixes #71344

r? @eddyb

### CODE REVIEW

File: src/librustc_mir/borrow_check/type_check/mod.rs [hunk 1]
```diff
@@ -686,6 +686,7 @@ impl<'a, 'b, 'tcx> TypeVerifier<'a, 'b, 'tcx> {
                 let fty = self.sanitize_type(place, fty);
                 match self.field_ty(place, base, field, location) {
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/type_check/mod.rs:687]: Is `field_ty` used in more places? Do those places normalize too? Maybe it would be good to normalize inside `field_ty` itself.

Comment (spastorino) [reply src/librustc_mir/borrow_check/type_check/mod.rs:687]: The other call to `field_ty` happens here https://github.com/spastorino/rust/blob/7bafb5704d9727b3897f086d9f159e62bc40ce42/src/librustc_mir/borrow_check/type_check/mod.rs#L1182-L1183. I can move the `normalize` call inside it but are just those two.

Comment (spastorino) [reply src/librustc_mir/borrow_check/type_check/mod.rs:687]: btw, I can move both `normalize` calls inside `field_ty` if you prefer.

**Comment by pnkfelix** [comment]
discussed at this weeks [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195844425).

at the time, we declined to accept for backport.

but further discussion with @estebank led me to rethink that outcome.

(We knew it was very low risk; we just didn't understand what the supposed gain was until estebank [pointed out](festehttps://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195844425) that the publicly posted docs would carry the incorrect number, which is not hidden by any part of our nightly/stability firewall.)

So I am going to unilaterally beta-accept based on that outcome. This will also serve as an example of a new policy going forward, where very low-risk beta-nominated issues can be unilaterally beta-accepted by a T-compiler lead (and we will just announce such beta-acceptances at the meeting, which I am now doing by marking this as I-nominated.)

**Comment by pnkfelix** [comment]
(OMG I posted on the wrong issue)

**Comment by pnkfelix** [comment]
discussed at this week's [T-compiler meeting](festehttps://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195844425)

beta-accepted
