### PR TITLE
Don't suggest inaccessible fields

### LINKED ISSUE #92999: Incorrect suggestion of private struct members
Lets consider the following code ([playground](https://play.rust-lang.org/?gist=cac56e673a4c9cbd3002b6f48ddb047b)) :
 ```rust
 pub struct S {
    pub val: String
}

pub fn test(s: S) {
    dbg!(s.cap)
}
 ```
 
 Here, we try to access a property `cap` on an object of type `struct S`.
 Up to the 1.50 version, the error message was the following : 
 ```rust
 rror[E0609]: no field `cap` on type `S`
 --> <source>:6:12
   |
6 |     dbg!(s.cap)
   |            ^^^ unknown field
   |
  = note: available fields are: `val`
  ```
  However, since Rust 1.51 and onward, the diagnostic message changed to this:
 ```rust
 rror[E0609]: no field `cap` on type `S`
 --> <source>:6:12
   |
6 |     dbg!(s.cap)
   |            ^^^ unknown field
   |
  = note: available fields are: `val`
help: one of the expressions' fields has a field of the same name
   |
6 |     dbg!(s.val.vec.buf.cap)
   |            ^^^^^^^^^^^^
```
While there is indead a `cap` property on the `RawVec` struct, this can't be accessed like that, applying the compiler suggestion implies  making the `buf` property of ` std::vec::Vec` public, which is not possible.

The compiler should not look at non-`pub` properties when searching for properties with a matching name for diagnostic purposes.

### PR DESCRIPTION
**Pull request by terrarier2111**
Fixes: https://github.com/rust-lang/rust/issues/92999

### CODE REVIEW

File: src/test/ui/suggestions/private-field.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// compile-flags: --crate-type lib
+pub struct S {
+    pub val: String
```
Comment (fmease) [inline src/test/ui/suggestions/private-field.rs:3]:
```suggestion
    pub val: MyString
```

What if the internal definition of `std::string::String` changes at some point and stops transitively containing a field named `cap`? Then the test will become useless. I suggest defining a custom type e.g. `MyString` to make it future-proof.

Comment (terrarier2111) [reply src/test/ui/suggestions/private-field.rs]: Done.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 2]
```diff
@@ -2257,6 +2258,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         candidate_field: &ty::FieldDef,
         subst: SubstsRef<'tcx>,
         mut field_path: Vec<Ident>,
+        id: HirId,
```
Comment (nagisa) [inline compiler/rustc_typeck/src/check/expr.rs:2261]: Rather than passing the `HirId` here, I think it probably makes more sense to directly pass through the `DefId` of the module, and produce this `DefId` back where `no_such_field_err` is called.

**Comment by nagisa** [comment]
I think the commit message/PR description could be improved to be more descriptive of change being made here as well before this is merged. Once that's done and the nit is fixed (or there's actually a good reason to do the things the way done right now) r=me.

File: compiler/rustc_typeck/src/check/expr.rs (hunk 2 above)
Comment (terrarier2111) [reply compiler/rustc_typeck/src/check/expr.rs]: Done.

**Comment by terrarier2111** [comment]
> I think the commit message/PR description could be improved to be more descriptive of change being made here, before this is merged. Once that's done and the nit is fixed (or there's actually a good reason to do the things the way done right now) r=me.

Done.
