### PR TITLE
Fix multiple `expect` attribs in impl block

### LINKED ISSUE #114416: Regression when using `#[expect(unused)]` more than once in an impl block
At some point between `rustc` `nightly-2023-03-05` (works) and `nightly-2023-07-01` (does not work) the following stopped compiling:

```rust
#![deny(warnings)]

struct X;
impl X {
    #[expect(unused)]
    fn unused();

    // This is failing with `warning: this lint expectation is unfulfilled`.
    // Only the first `#[expect(unused)]` in an impl block works as expected.
    #[expect(unused)]
    fn unused2();
}

fn main() {
    let _ = X;
}
```
```sh
RUSTFLAGS="-D warnings" cargo check
```

I have not bisected for the exact commit that broke this.

I have only tried to reproduce this error using `#[expect(unused)]`. It's possible that this is also broken for other lints.

PR: https://github.com/rust-lang/rust/pull/114417

### PR DESCRIPTION
**Pull request by chinedufn**
Closes #114416

### CODE REVIEW

**Comment by fmease** [comment]
Some rough mentoring instructions linking tying in with comment over at the issue:

* look into where & how `#[expect]` is implemented in the compiler (look through the PR(s) that are linked in the relevant tracking issue or ones that you can find by filtering the merged PRs or `grep` through `compiler/` (keyword `expect` or fragments of the diagnostic messages emitted by `#[expect]`))
* if it's the case that rustc only considers the first primary span, consider updating the lint code to respect *all* primary spans of a (buffered) lint diagnostic (see [`MultiSpan`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_error_messages/struct.MultiSpan.html))

If you have concrete questions, ask them on Zulip in the help stream (or PM me there as a last resort, though note that I've benn hacking on the compiler for one year only)

**Comment by fmease** [comment]
Some rough mentoring instructions linking tying in with comment over at the issue:

* look into where & how `#[expect]` is implemented in the compiler (look through the PR(s) that are linked in the relevant tracking issue or ones that you can find by filtering the merged PRs or `grep` through `compiler/` (keyword `expect` or fragments of the diagnostic messages emitted by `#[expect]`))
* if it's the case that rustc only considers the first primary span, consider updating the lint code to respect *all* primary spans of a (buffered) lint diagnostic (see [`MultiSpan`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_error_messages/struct.MultiSpan.html))

If you have concrete questions, ask them on Zulip in the help stream (or PM me there as a last resort, though note that I've benn hacking on the compiler for one year only)

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -1263,6 +1263,10 @@ impl Handler {
         std::mem::take(&mut self.inner.borrow_mut().fulfilled_expectations)
     }
 
+    pub fn insert_fulfilled_diagnostic(&self, expectation_id: LintExpectationId) {
+        self.inner.borrow_mut().fulfilled_expectations.insert(expectation_id);
+    }
```
Comment (chinedufn) [inline compiler/rustc_errors/src/lib.rs:1268]: Before this PR the only way to insert into the `fulfilled_expectations` was via the `emit_diagnostics` method https://github.com/rust-lang/rust/blob/81c650fd69886441d52c201681f639609de4640f/compiler/rustc_errors/src/lib.rs#L1351-L1354

I haven't yet poked around to try to figure out whether or not exposing a way to insert without emitting a diagnostic makes it possible to break some important invariant.

Tips appreciated.

**Review by chinedufn — COMMENTED** [review]
Thanks for the tips.

I started by just poking around and figuring out the simplest (but potentially naive) way to get the test passing.

I can try to take a look at the tips about the expect PRs and `MultiSpan` to see if I can figure out a better way to solve the problem.

Or if this way is good then I'm happy to rebase into a single commit and land as is.

File: compiler/rustc_passes/src/dead.rs [hunk 2]
```diff
@@ -814,6 +814,13 @@ impl<'tcx> DeadVisitor<'tcx> {
             }
         };
 
+        for id in &dead_codes[1..] {
+            let hir = self.tcx.hir().local_def_id_to_hir_id(*id);
+            let lint_level = self.tcx.lint_level_at_node(lint::builtin::DEAD_CODE, hir).0;
+            if let Some(expectation_id) = lint_level.get_expectation_id() {
+                self.tcx.sess.diagnostic().insert_fulfilled_expectation(expectation_id);
+            }
+        }
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:823]: I suggest to refactor the code the other way around.
We should assert that all ids in `dead_codes` have the same lint level.
And callers should group calls by level, like `warn_dead_fields_and_variants`.
The branch of `check_mod_deathness` for impl items may use `warn_dead_fields_and_variants` instead of `warn_multiple_dead_codes` directly.

File: tests/ui/lint/rfc-2383-lint-reason/expect_unused_inside_impl_block.rs [hunk 3]
```diff
@@ -0,0 +1,25 @@
+// check-pass
```
Comment (cjgillot) [inline tests/ui/lint/rfc-2383-lint-reason/expect_unused_inside_impl_block.rs:1]: Could you make this an incremental test too? To check that all sessions emit the same diagnostic.

Comment (chinedufn) [reply tests/ui/lint/rfc-2383-lint-reason/expect_unused_inside_impl_block.rs:1]: The rustc dev guide mentions an "incremental" mode where the compiler is run multiple times in order to confirm that incremental compilation works.

When I grep for "incremental" in `tests/ui` I only see the `// incremental` (i.e. `-C incremental`) header being used, but I don't see anything that looks like its enabling this "incremental mode" (I can't quite tell how to enable that).

My understanding is that the `// incremental` header runs the test once, but your recommendation is that we should run the test once with a clean incremental
cache dir and once with the populated cache.

So, my question is, how do I make sure that the test runs once with an empty incremental cache and then again with the now populated cache?

---

https://rustc-dev-guide.rust-lang.org/tests/headers.html?highlight=incremental%20mode#miscellaneous-headers

> incremental runs the test with the -C incremental flag and an empty incremental directory. This should be avoided when possible; you should use an incremental mode test instead. Incremental mode tests support running the compiler multiple times and verifying that it can load the generated incremental cache. This flag is for specialized circumstances, like checking the interaction of codegen unit partitioning with generating an incremental cache.

File: compiler/rustc_errors/src/lib.rs [hunk 4]
```diff
@@ -1263,6 +1263,10 @@ impl Handler {
         std::mem::take(&mut self.inner.borrow_mut().fulfilled_expectations)
     }
 
+    pub fn insert_fulfilled_expectation(&self, expectation_id: LintExpectationId) {
+        self.inner.borrow_mut().fulfilled_expectations.insert(expectation_id);
+    }
```
[the remark this answers is not in the document]
Comment (chinedufn) [reply compiler/rustc_errors/src/lib.rs]: My understanding is that I'll need access to all of the `LocalDefId` (or their corresponding `HirId`s) in order to insert the dead code ids into `fulfilled_expectations`.

So, to handle this in `emit_diagnostic` I would need access to all of the dead code ids for the diagnostic.

So, it seems like the `Diagnostic` struct needs to store all of the dead code ids.

```rust
Diagnostic.dead_code: Vec<LocalDefId>
```

Then from there I can insert into `fulfilled_expectations` during the `emit_diagnostic` method.

---

Is that correct? It doesn't sound very elegant, but I'm not sure if there is better way to accomplish this?

File: tests/ui/lint/rfc-2383-lint-reason/expect_unused_inside_impl_block.rs (hunk 3 above)
Comment (cjgillot) [reply tests/ui/lint/rfc-2383-lint-reason/expect_unused_inside_impl_block.rs:1]: Incremental tests are in tests/incremental . There are several examples in there.

File: compiler/rustc_errors/src/lib.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (cjgillot) [reply compiler/rustc_errors/src/lib.rs]: The problem is that we issue a single diagnostic where we have multiple lint levels. 
See my suggestion about using warn_dead_fields_and_variants.

**Comment by cjgillot** [comment]
You patch does not compile. Could you fix it and push again?

**Comment by chinedufn** [comment]
I haven't worked on your feedback yet. I was planning to work on this within the next week or to.
If this is more urgent I can get back to work on this tonight or tomorrow?

This is my first contribution so please let me know if this delay is a problem or if you have any other feedback around how I should approach this patch.

File: compiler/rustc_errors/src/lib.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (chinedufn) [reply compiler/rustc_errors/src/lib.rs]: > The problem is that we issue a single diagnostic where we have multiple lint levels.

I'll have to read through the flow a bit to better understand your suggestion. 
I don't yet have a good understanding of what exactly `Diagnostic` is responsible for, so I don't yet know why a "single diagnostic with multiple lint levels" is a problem.

I'll read through some diagnostic related code paths / docs then apply your feedback.

**Comment by cjgillot** [comment]
There is no rush. I was just getting on this PR. I saw some good progress, but I did not know what to do of it as CI fails.
Please issue `@rustbot ready` once you get to it.

**Comment by chinedufn** [comment]
Update:

I have the ui test passing locally. Just need to add an incremental test. Then I'll push and use `@rustbot ready`.

File: tests/incremental/issue-114416-expect-unused-inside-impl-block.rs [hunk 5]
```diff
@@ -0,0 +1,32 @@
+// revisions: rpass1
```
Comment (chinedufn) [inline tests/incremental/issue-114416-expect-unused-inside-impl-block.rs:1]: Seems like it would be nice if it was possible to add `revisions: rpass1` to a UI test so that we don't have to duplicate tests like this one across `tests/incremetal` and `tests/ui`.

First, is there already a good way to avoid this duplication?

If not, would being able to drive an incremental test from a UI test be undesirable for some reason?

If desirable, I'd be interesting in adding support for using the `revisions: rpass1` annotation in a UI test. Do you have any tips on how I might best explore that (in a separate PR)?

File: compiler/rustc_passes/src/dead.rs [hunk 6]
```diff
@@ -734,6 +740,15 @@ impl<'tcx> DeadVisitor<'tcx> {
...
         };
         let tcx = self.tcx;
+
+        let first_hir_id = tcx.hir().local_def_id_to_hir_id(first_id);
+        let first_lint_level = tcx.lint_level_at_node(lint::builtin::DEAD_CODE, first_hir_id).0;
+        assert!(dead_codes.iter().skip(1).all(|id| {
+            let hir_id = tcx.hir().local_def_id_to_hir_id(*id);
+            let level = tcx.lint_level_at_node(lint::builtin::DEAD_CODE, hir_id).0;
+            level == first_lint_level
+        }));
```
Comment (chinedufn) [inline compiler/rustc_passes/src/dead.rs:750]: This `warn_multiple_dead_codes` method seems like it would be a fairly cold code path (as in, you'd have to have a project with a lot of dead code to hit this method a lot), so it seemed fine to add another loop here.

**Comment by chinedufn** [comment]
All feedback addressed. Thank you for the guidance.

The PR guide doesn't mention anything about rebasing my commits https://rustc-dev-guide.rust-lang.org/contributing.html#opening-a-pr. I was planning to rebase into a single commit after this PR was approved. Let me know if that's unnecessary.

@rustbot ready

File: compiler/rustc_passes/src/dead.rs [hunk 7]
```diff
@@ -723,6 +723,12 @@ impl<'tcx> DeadVisitor<'tcx> {
         ShouldWarnAboutField::Yes(is_positional)
     }
 
+    // # Panics
+    // All `dead_codes` must have the same lint level, otherwise we will intentionally ICE.
+    // This is because we emit a multi-spanned lint using the lint level of the `dead_codes`'s
+    // first local def id.
+    // Prefer calling `Self.warn_dead_code` or `Self.warn_dead_code_grouped_by_lint_level`
+    // since those methods group by lint level before calling this method.
     fn warn_multiple_dead_codes(
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:732]: This method needs to be renamed, so it's not used again. `lint_at_single_level`?

File: compiler/rustc_passes/src/dead.rs [hunk 8]
```diff
@@ -814,15 +829,10 @@ impl<'tcx> DeadVisitor<'tcx> {
...
-            lint,
-            tcx.hir().local_def_id_to_hir_id(first_id),
-            MultiSpan::from_spans(spans),
-            diag,
-        );
+        self.tcx.emit_spanned_lint(lint, first_hir_id, MultiSpan::from_spans(spans), diag);
     }
 
-    fn warn_dead_fields_and_variants(
+    fn warn_dead_code_grouped_by_lint_level(
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:835]: And this one can be named `warn_multiple`.

File: compiler/rustc_passes/src/dead.rs [hunk 9]
```diff
@@ -894,15 +904,19 @@ fn check_mod_deathness(tcx: TyCtxt<'_>, module: LocalDefId) {
...
-                let did = item.id.owner_id.def_id;
-                if !visitor.is_live_code(did) {
-                    dead_items.push(did)
+                let def_id = item.id.owner_id.def_id;
+                if !visitor.is_live_code(def_id) {
+                    let name = tcx.item_name(def_id.to_def_id());
+                    let hir = tcx.hir().local_def_id_to_hir_id(def_id);
+                    let level = tcx.lint_level_at_node(lint::builtin::DEAD_CODE, hir).0;
+
+                    dead_items.push(DeadVariant { def_id, name, level })
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:913]: `DeadVariant` needs to be renamed.

File: compiler/rustc_passes/src/dead.rs [hunk 10]
```diff
@@ -894,15 +904,19 @@ fn check_mod_deathness(tcx: TyCtxt<'_>, module: LocalDefId) {
...
             let mut dead_items = Vec::new();
             for item in impl_item.items {
-                let did = item.id.owner_id.def_id;
-                if !visitor.is_live_code(did) {
-                    dead_items.push(did)
+                let def_id = item.id.owner_id.def_id;
+                if !visitor.is_live_code(def_id) {
+                    let name = tcx.item_name(def_id.to_def_id());
+                    let hir = tcx.hir().local_def_id_to_hir_id(def_id);
+                    let level = tcx.lint_level_at_node(lint::builtin::DEAD_CODE, hir).0;
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:911]:
```suggestion
                    let hir_id = tcx.hir().local_def_id_to_hir_id(def_id);
                    let level = tcx.lint_level_at_node(lint::builtin::DEAD_CODE, hir_id).0;
```

File: tests/incremental/issue-114416-expect-unused-inside-impl-block.rs (hunk 5 above)
Comment (cjgillot) [reply tests/incremental/issue-114416-expect-unused-inside-impl-block.rs:1]: See what `tests/ui/dep-graph` files do. They have an `// incremental` directive for this.

File: compiler/rustc_passes/src/dead.rs (hunk 9 above)
Comment (chinedufn) [reply compiler/rustc_passes/src/dead.rs]: Not sure what the right name would be for this. I renamed it to `DeadItem`.
