### PR TITLE
Replace in-tree `rustc_apfloat` with the new version of the crate

### LINKED ISSUE #55993: Factor out rustc_apfloat into a standalone crate
[librustc_apfloat](https://github.com/rust-lang/rust/tree/master/src/librustc_apfloat) is a Rust translation of [LLVM's APFloat library](https://github.com/llvm-mirror/llvm/blob/master/lib/Support/APFloat.cpp), written in C++, and provides software implementations of `f32`, `f64`, and other floating-point types, which are useful for performing host-independent floating-point computation. We made a standalone crate of this for use in Cranelift, however other compiler projects could make use of such a library as well, and in general it'd be good to have only one copy of this code.

Where's the best place for the code live?
 - Create a new repository under [the rust-lang organization](https://github.com/rust-lang/).
 - Use the repository that Cranelift is currently using [here](https://github.com/CraneStation/rustc_apfloat).

What should the crate be called?
 - `rustc_apfloat` -- the current name. "apfloat" isn't very descriptive, except that it's the name of the upstream code this crate is based on. And the crate isn't specific to rustc :-).
 - `software_float` -- a more descriptive name, and not yet claimed on crates.io
 - other ideas?

cc @eddyb @lachlansneff

### LINKED ISSUE #93224: rustc_apfloat: Panic in Double::mul_add_r
I tried this code and get a panic:

```rust
#[test]
fn issue_93224() {
    let r1 = Double::from_bits(0x000000000000002D as u128);
    let r2 = Double::from_bits(0xC2D6C16C166666DE as u128);
    let r3 = Double::from_bits(0x0000000000000055 as u128);

    let _ = r1.mul_add_r(r2, r3, Round::NearestTiesToEven);
}
```

### Meta

Commit: master 17d29dcdce9b9e838635eb0adefd9b8b1588410b

<details><summary>Backtrace</summary>
<p>

```
thread 'issue_93224' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', compiler/rustc_apfloat/src/ieee.rs:2545:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/core/src/panicking.rs:110:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: rustc_apfloat::ieee::sig::add_or_sub
   5: <rustc_apfloat::ieee::IeeeFloat<S> as rustc_apfloat::Float>::mul_add_r
   6: ieee::issue_93224
   7: ieee::issue_93224::{{closure}}
   8: core::ops::function::FnOnce::call_once
   9: core::ops::function::FnOnce::call_once
             at /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb/library/core/src/ops/function.rs:227:5

```

</p>
</details>

### LINKED ISSUE #100233: apfloat bug: incorrect handling of infinities in FMA
The Rust port of LLVM's apfloat has a bug in its FMA (fused-multiply-add) implementation. See https://github.com/rust-lang/miri/issues/2468#issuecomment-1207310464 for details, but basically it fails this assertion:
```rust
    let neg_inf: f32 = f32::NEG_INFINITY;
    assert_eq!((-3.2f32).mul_add(2.4, neg_inf), neg_inf);
```

AFAIK we don't use apfloat FMA anywhere (Miri stopped using them to work around this bug), but this should still be tracked, and will need to be fixed before we can allow FMA in `const`.

### LINKED ISSUE #102403: Sign of zero from differs between CTFE and normal execution (float % float)
With this code:

```rust
#![feature(const_fn_floating_point_arithmetic)]

const fn f(one: f64) -> f64 {
    (-1.0) % one
}

const RESULT_CT : f64 = f(1.0);

fn main() {
    let black_box_one = (std::env::args().len()) as f64;
    let result_rt = f(black_box_one);
    assert_eq!(RESULT_CT.is_sign_negative(), result_rt.is_sign_negative());
}
```

The assertion fails: compile-time evaluation gives 0.0 while runtime evaluation gives -0.0.

This is probably relevant to tracking issue #57241.

### LINKED ISSUE #113407: Subnormal f64 to f32 cast is incorrect in CTFE
```rust
pub fn main() {
    let f = f64::from_bits(0x19873cc2) as f32;
    println!("{:x}", f.to_bits());
    println!("{}", f == 0.);
}
```

```console
$ rustc -Zmir-opt-level=2 -Copt-level=3 repro.rs && ./repro
1
false
$ ../miri/miri run repro.rs 2> /dev/null
1
false
$ rustc -Zmir-opt-level=1 -Copt-level=3 repro.rs && ./repro
0
true
```

It should print `0` and `true`, according to the equivalent C program: https://godbolt.org/z/7Gq51a1Yh

This is probably another apfloat bug

```console
$ rustc --version -v 
rustc 1.72.0-nightly (d9c13cd45 2023-07-05)
binary: rustc
commit-hash: d9c13cd4531649c2028a8384cb4d4e54f985380e
commit-date: 2023-07-05
host: aarch64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```
(reproducible on x86 as well)

cc @eddyb @wesleywiser @RalfJung

### LINKED ISSUE #113409: Collection of issues blocked on apfloat situation
apfloat is in a [bit of a situation](https://github.com/rust-lang/rust/issues/55993) and has been for a long time. I'd like to have a central list of things to get back to and fix once that situation is resolved; that is the purpose of this issue.

- https://github.com/rust-lang/rust/issues/100233
- https://github.com/rust-lang/rust/issues/102403
- https://github.com/rust-lang/rust/issues/113407

### PR DESCRIPTION
**Pull request by wesleywiser**
Replace the in-tree version of `rustc_apfloat` with the new version of the crate which has been correctly licensed. The new crate incorporates upstream changes from LLVM since the original port was done including many correctness fixes and has been extensively fuzz tested to validate correctness. 

Fixes #100233
Fixes #102403
Fixes #113407 
Fixes #113409 
Fixes #55993
Fixes #93224 
Closes #93225
Closes #109573

### CODE REVIEW

File: src/tools/tidy/src/extdeps.rs [hunk 1]
```diff
@@ -4,7 +4,11 @@ use std::fs;
 use std::path::Path;
 
 /// List of allowed sources for packages.
-const ALLOWED_SOURCES: &[&str] = &["\"registry+https://github.com/rust-lang/crates.io-index\""];
+const ALLOWED_SOURCES: &[&str] = &[
+    "\"registry+https://github.com/rust-lang/crates.io-index\"",
+    // FIXME: DO NOT CHECK THIS IN
+    "\"git+https://github.com/rust-lang/rustc_apfloat.git#34c967f65a59f613e9998251d173bbe28d2464ac\"",
```
Comment (wesleywiser) [inline src/tools/tidy/src/extdeps.rs:10]: Reminding myself to back this out later

**Comment by wesleywiser** [comment]
@craterbot run start=master#d3515155216e98c23440ea92c3f49c6a0d7101fc end=try#d724b5ab2f4ac098ff483349a80b6a3799a5177b mode=build-and-test

**Comment by eddyb** [comment]
> Would be great if you could also change Miri back to using apfloat for FMA. :) That would be basically undoing the functional part of https://github.com/rust-lang/miri/commit/5a4ac1ebf0e30b415b90a57904e4c2cb32f35068. Then Miri tests will already check that some FMA bugs have been fixed.

@RalfJung that may be premature, given how many holes in the FMA fix I'm finding - initially I thought it was more sub-cases of the assertion failing:
* https://github.com/llvm/llvm-project/issues/63895

But now I'm starting to suspect the FMA fix (https://github.com/llvm/llvm-project/commit/e62555c129d535d524354351791c5474c9929582) actually made things worse, introducing subtle rounding errors because of how it computes the direction of subtraction, and the original bug should be analyzed from scratch and fixed correctly this time.

(I may attempt this myself once I have collected enough samples from bruteforcing `f32` FMA - a sentence I never imagined uttering, but so far it's sitting strong at `0.15 trillion` input combinations tested, of which 16 differ from hardware due to the rounding error, and 13 hit the assertion check)

---

Something I did miss, however, is that we don't seem to have any issue about the assertion itself?

* https://github.com/rust-lang/rust/issues/100233

is the only issue I know related to the FMA, and is about a different behavior (related to infinities) - I only mention the assertion in comments on that issue because I hit it while checking that the issue itself was fixed.

**Comment by RalfJung** [comment]
rustc_apfloat FMA is currently unused in rustc and Miri. It used to be used by Miri but I switched it to using host floats instead to fix https://github.com/rust-lang/miri/issues/2468. CTFE doesn't support FMA. That's why we have no open issue for that.

**Comment by eddyb** [comment]
> CTFE doesn't support FMA. That's why we have no open issue for that.

Small caveat: we're still affected by LLVM constant-folding, so we would still get the results wrong (or trigger a LLVM assertion if they're enabled) in all of those cases, just like Clang, as long as LLVM can constant-fold the FMA.

**Comment by RalfJung** [comment]
@craterbot run mode=build-and-test crates=https://crater-reports.s3.amazonaws.com/pr-113843/retry-regressed-list.txt

**Comment by wesleywiser** [comment]
I looked over the regressions and locally retested ones that seemed like they could be APFloat related. I found a few tests that seemed to fail/pass inconsistently and no other tests failed. 

I think we can interpret the crater results as showing no regressions from this change.

**Comment by eddyb** [comment]
For `perf`, just remembered I had a local commit laying around, maybe try with it as well?
* https://github.com/rust-lang/rustc_apfloat/pull/7

(I'm not sure if it will help much, the perf result may just be noise - the other thing I've noticed btw, is that using `u64` instead of `u128`, as the "bigint limb" backing type, like LLVM does, brings an even bigger perf improvement - not that surprising, just annoying to account for, without outright disabling `x87` and `f128` support with a Cargo package feature)

**Comment by wesleywiser** [comment]
@chenyukang I took the liberty of including the test you wrote for #109573. 

@RalfJung I did the same for the tests you wrote for #113416 and I also added an annotation to require LLVM 16 to skip the test on older LLVM versions which have various APFloat bugs.

**Comment by wesleywiser** [comment]
`ripgrep check incr-unchanged` results:

<details>

```
  -3,353,625    <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle::ty::context::TyCtxt>
   3,263,696    <rustc_middle::query::on_disk_cache::OnDiskCache>::drop_serialized_data
  -2,298,458    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<&rustc_middle::ty::typeck_results::TypeckResults>
  -2,265,223    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::typeck_results::TypeckResults>
   1,744,248    <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::def_path_hash
  -1,470,714    rustc_expand::mbe::transcribe::transcribe
  -1,390,598    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
   1,213,904    <rustc_expand::mbe::macro_rules::MacroRulesMacroExpander as rustc_expand::base::TTMacroExpander>::expand
   1,154,276    rustc_middle::ty::codec::encode_with_shorthand::<rustc_middle::query::on_disk_cache::CacheEncoder, rustc_middle::ty::Ty, <rustc_middle::query::on_disk_cache::CacheEncoder as rustc_type_ir::codec::TyEncoder>::type_shorthands>
   1,112,683    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
  -1,069,158    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
   1,068,987    <indexmap::map::IndexMap<rustc_middle::ty::fast_reject::SimplifiedType, alloc::vec::Vec<rustc_span::def_id::DefId>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
     923,611    <indexmap::map::IndexMap<rustc_middle::ty::fast_reject::SimplifiedType, alloc::vec::Vec<rustc_span::def_id::DefId>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    -842,230    <std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
     549,531    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, alloc::vec::Vec<rustc_middle::ty::adjustment::Adjustment>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
     497,603    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    -464,974    <rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 24]>)>>::call_once
     404,938    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::GenericPredicates>
     398,187    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, alloc::vec::Vec<rustc_middle::ty::adjustment::Adjustment>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    -388,491    rustc_query_system::dep_graph::graph::hash_result::<core::option::Option<rustc_middle::hir::Owner>>
     381,599    <rustc_query_impl::query_impl::hir_owner::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 16]>)>>::call_once
     363,055    <rustc_middle::ty::generic_args::GenericArgKind as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
...
```

</details>

`bitmaps opt incr-unchanged` results:

<details>

```
  -10,577,536    rustc_expand::mbe::transcribe::transcribe
    9,382,846    <rustc_expand::mbe::macro_rules::MacroRulesMacroExpander as rustc_expand::base::TTMacroExpander>::expand
   -8,768,145    <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle::ty::context::TyCtxt>
    8,535,202    <rustc_middle::query::on_disk_cache::OnDiskCache>::drop_serialized_data
   -2,639,527    <rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 24]>)>>::call_once
   -2,483,917    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::typeck_results::TypeckResults>
    2,353,419    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::GenericPredicates>
   -1,947,284    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<&rustc_middle::ty::typeck_results::TypeckResults>
    1,726,673    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::Generics>
   -1,627,947    rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   -1,605,749    rustc_query_system::dep_graph::graph::hash_result::<core::option::Option<rustc_middle::hir::Owner>>
    1,579,890    <rustc_query_impl::query_impl::hir_owner::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 16]>)>>::call_once
    1,282,824    rustc_ast::mut_visit::visit_delim_span::<rustc_expand::mbe::transcribe::Marker>
    1,185,576    <rustc_parse::parser::Parser>::check_fn_front_matter
   -1,114,990    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    1,031,069    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::generics::Generics>
    1,015,462    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generic_args::EarlyBinder<rustc_middle::ty::Ty>>
      998,071    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
      987,506    <[rustc_middle::metadata::ModChild] as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
     -896,909    <rustc_middle::ty::generics::Generics as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
     -876,019    <rustc_trait_selection::traits::select::SelectionContext>::in_task::<<rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}, core::result::Result<core::option::Option<rustc_middle::traits::select::SelectionCandidate>, rustc_middle::traits::SelectionError>>::{closure#0}
      867,729    <rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation_no_cache
      854,340    <rustc_type_ir::sty::TyKind<rustc_middle::ty::context::TyCtxt> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
     -847,307    <rustc_middle::ty::generics::GenericPredicates as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
     -816,733    <rustc_parse::parser::Parser>::parse_ty_common
     -748,748    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
      748,442    <indexmap::map::IndexMap<rustc_middle::ty::fast_reject::SimplifiedType, alloc::vec::Vec<rustc_span::def_id::DefId>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
      732,548    rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
      722,094    <indexmap::map::IndexMap<rustc_middle::ty::fast_reject::SimplifiedType, alloc::vec::Vec<rustc_span::def_id::DefId>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
     -707,531    <std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
...
```

</details>

`image check incr-unchanged` results:

<details>

```
  -14,210,692    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::typeck_results::TypeckResults>
  -13,363,792    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<&rustc_middle::ty::typeck_results::TypeckResults>
  -12,229,371    <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle::ty::context::TyCtxt>
   11,902,033    <rustc_middle::query::on_disk_cache::OnDiskCache>::drop_serialized_data
    7,322,694    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    7,317,551    rustc_middle::ty::codec::encode_with_shorthand::<rustc_middle::query::on_disk_cache::CacheEncoder, rustc_middle::ty::Ty, <rustc_middle::query::on_disk_cache::CacheEncoder as rustc_type_ir::codec::TyEncoder>::type_shorthands>
   -4,976,407    rustc_expand::mbe::transcribe::transcribe
    4,096,682    <rustc_expand::mbe::macro_rules::MacroRulesMacroExpander as rustc_expand::base::TTMacroExpander>::expand
    3,293,765    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    3,004,652    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::GenericPredicates>
   -2,989,542    <rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 24]>)>>::call_once
    2,925,891    <rustc_type_ir::sty::TyKind<rustc_middle::ty::context::TyCtxt> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    2,648,104    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, alloc::vec::Vec<rustc_middle::ty::adjustment::Adjustment>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    2,395,651    <rustc_middle::ty::generic_args::GenericArgKind as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    2,358,319    <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::def_path_hash
    2,255,841    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::Generics>
    1,864,322    <rustc_parse::parser::Parser>::check_fn_front_matter
   -1,864,021    rustc_query_system::dep_graph::graph::hash_result::<core::option::Option<rustc_middle::hir::Owner>>
    1,830,882    <rustc_query_impl::query_impl::hir_owner::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 16]>)>>::call_once
    1,825,706    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, alloc::vec::Vec<rustc_middle::ty::adjustment::Adjustment>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
   -1,765,357    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
   -1,629,935    rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   -1,452,369    <[rustc_middle::ty::adjustment::Adjustment] as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    1,401,790    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::generics::Generics>
   -1,381,302    <rustc_middle::ty::generics::GenericPredicates as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
   -1,372,984    <rustc_middle::traits::specialization_graph::Children as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    1,372,426    <indexmap::map::IndexMap<rustc_middle::ty::fast_reject::SimplifiedType, alloc::vec::Vec<rustc_span::def_id::DefId>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
   -1,299,567    <rustc_parse::parser::Parser>::parse_ty_common
    1,274,693    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, rustc_middle::ty::generics::GenericPredicates>
...
```

</details>

`serde check incr-patched` results:

<details>

```
  -78,649,002    rustc_expand::mbe::transcribe::transcribe
   67,255,328    <rustc_expand::mbe::macro_rules::MacroRulesMacroExpander as rustc_expand::base::TTMacroExpander>::expand
  -13,427,056    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::typeck_results::TypeckResults>
  -12,227,523    <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle::ty::context::TyCtxt>
   12,111,674    rustc_ast::mut_visit::visit_delim_span::<rustc_expand::mbe::transcribe::Marker>
   11,901,634    <rustc_middle::query::on_disk_cache::OnDiskCache>::drop_serialized_data
  -11,189,045    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<&rustc_middle::ty::typeck_results::TypeckResults>
    6,384,479    rustc_middle::ty::codec::encode_with_shorthand::<rustc_middle::query::on_disk_cache::CacheEncoder, rustc_middle::ty::Ty, <rustc_middle::query::on_disk_cache::CacheEncoder as rustc_type_ir::codec::TyEncoder>::type_shorthands>
    6,038,453    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    5,877,435    <rustc_middle::ty::generic_args::GenericArgKind as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    5,064,876    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::GenericPredicates>
    4,530,435    <rustc_parse::parser::Parser>::check_fn_front_matter
   -3,947,848    <rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 24]>)>>::call_once
    3,750,621    <rustc_middle::query::on_disk_cache::OnDiskCache>::load_indexed::<rustc_middle::ty::generics::Generics>
    3,255,828    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, rustc_middle::ty::generics::GenericPredicates>
   -3,169,739    <rustc_parse::parser::Parser>::parse_ty_common
   -3,119,383    <rustc_middle::ty::generics::GenericPredicates as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    2,824,559    <[rustc_middle::ty::generic_args::GenericArg] as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    2,723,915    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, rustc_middle::ty::Ty, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
    2,425,410    <rustc_middle::query::on_disk_cache::CacheEncoder>::encode_tagged::<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, &rustc_middle::ty::generics::Generics>
   -2,373,103    <rustc_middle::query::on_disk_cache::CacheDecoder as rustc_type_ir::codec::TyDecoder>::cached_ty_for_shorthand::<<rustc_middle::ty::Ty as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
   -2,241,215    <rustc_middle::ty::sty::Binder<rustc_middle::ty::PredicateKind> as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
   -2,152,566    <rustc_middle::ty::generics::Generics as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
   -2,074,686    rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   -2,025,386    rustc_query_system::dep_graph::graph::hash_result::<core::option::Option<rustc_middle::hir::Owner>>
    2,022,692    <rustc_query_impl::query_impl::hir_owner::dynamic_query::{closure#7} as core::ops::function::FnOnce<(&mut rustc_query_system::ich::hcx::StableHashingContext, &rustc_middle::query::erase::Erased<[u8; 16]>)>>::call_once
   -1,915,142    <&mut <&rustc_middle::ty::list::List<rustc_middle::ty::generic_args::GenericArg> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode::{closure#0} as core::ops::function::FnOnce<(usize,)>>::call_once
   -1,873,279    <&rustc_middle::ty::generics::Generics as rustc_serialize::serialize::Encodable<rustc_middle::query::on_disk_cache::CacheEncoder>>::encode
   -1,804,137    <rustc_middle::ty::generic_args::GenericArg as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
    1,800,030    <std::collections::hash::map::HashMap<rustc_hir::hir_id::ItemLocalId, alloc::vec::Vec<rustc_middle::ty::adjustment::Adjustment>, core::hash::BuildHasherDefault<rustc_hash::FxHasher>> as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
...
```

</details>

I don't see anything relevant to changing APFloat here, seems to perhaps be just different inlining decisions being made. I'm going to go ahead and mark as perf-regression-triaged.

File: src/tools/miri/src/shims/foreign_items.rs [hunk 2]
```diff
@@ -914,16 +914,6 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriInterpCxExt<'mir, 'tcx> {
                 let x = this.read_scalar(x)?.to_f64()?;
                 let exp = this.read_scalar(exp)?.to_i32()?;
 
-                // Saturating cast to i16. Even those are outside the valid exponent range so
```
Comment (pnkfelix) [inline src/tools/miri/src/shims/foreign_items.rs:917]: I am trying to figure out why this was originally here so that I can justify why its being removed now.

I got to this commit: https://github.com/rust-lang/rust/commit/0743ed631efe63ae2de96847df7b7fce629127b6 
and now I'm stuck. Why were we clamping ldexp exponent to i16, and why don't we need to keep doing so now? I'm assuming its a weakness in the old APFloat API that has since been addressed in the new rustc_apfloat, but can you confirm that @wesleywiser ?

Comment (cbeuw) [reply src/tools/miri/src/shims/foreign_items.rs:917]: FYI this is from Miri PR https://github.com/rust-lang/miri/pull/902

Comment (wesleywiser) [reply src/tools/miri/src/shims/foreign_items.rs:917]: > I'm assuming its a weakness in the old APFloat API that has since been addressed in the new rustc_apfloat, but can you confirm that @wesleywiser ?

Yes, exactly. The old APFloat API took ldexp as an `i16` but the new crate takes `i32` which matches what the code originally did before calling into APFloat. There's additional discussion why `i16` is sufficient for this parameter in the discussion here https://github.com/rust-lang/miri/pull/902#discussion_r312587825.

Comment (pnkfelix) [reply src/tools/miri/src/shims/foreign_items.rs:917]: I see. So in theory this could have stayed as-is, but since it was an artifact of a prior limitation, we're removing it. RIght?

Comment (wesleywiser) [reply src/tools/miri/src/shims/foreign_items.rs:917]: Yes, I could have just added an `.into()` to do the `i16 -> i32` conversion but since we're actually doing a `i32 -> i16 -> i32` conversion, it seemed cleaner to just remove the conversions entirely.

File: tests/ui/const_prop/apfloat-f64-roundtrip.rs [hunk 3]
```diff
@@ -0,0 +1,9 @@
+// run-pass
+// compile-flags: -O -Zmir-opt-level=3 -Cno-prepopulate-passes
+// min-llvm-version: 16.0 (requires APFloat fixes in LLVM)
```
Comment (RalfJung) [inline tests/ui/const_prop/apfloat-f64-roundtrip.rs:3]: It is still a mystery to me why with `-Cno-prepopulate-passes` this require apfloat fixes. :shrug:

File: tests/ui/numbers-arithmetic/apfloat-modulo-wrong.rs [hunk 4]
```diff
@@ -0,0 +1,15 @@
+// run-pass
+// check-run-results
+// regression test for issue #109567
+
+fn f() -> f64 {
+    std::hint::black_box(-1.0) % std::hint::black_box(-1.0)
+}
```
Comment (RalfJung) [inline tests/ui/numbers-arithmetic/apfloat-modulo-wrong.rs:7]: This seems to be basically the same as tests/ui/const_prop/apfloat-remainder-regression.rs? Is it worth having both?

File: src/tools/miri/src/shims/foreign_items.rs (hunk 2 above)
Comment (RalfJung) [reply src/tools/miri/src/shims/foreign_items.rs:917]: Indeed, thanks for the nice cleanup. :)

File: tests/ui/numbers-arithmetic/apfloat-modulo-wrong.rs (hunk 4 above)
Comment (wesleywiser) [reply tests/ui/numbers-arithmetic/apfloat-modulo-wrong.rs:7]: I figured since there are two different issues, it was probably worth having two tests, but I really don't feel strongly either way.

File: tests/ui/const_prop/apfloat-f64-roundtrip.rs (hunk 3 above)
Comment (wesleywiser) [reply tests/ui/const_prop/apfloat-f64-roundtrip.rs:3]: Yeah, I'm not sure either. Investigating more into LLVM at this point didn't seem worthwhile to me if it's been fixed in LLVM 16 but I could be convinced otherwise 🙂 

Perhaps the issue is that LLVM 14's bitcode reader fails to roundtrip the float?

**Comment by klensy** [comment]
Let's see if it fails on CI: https://github.com/rust-lang/rustc_apfloat/issues/10

File: src/tools/miri/src/shims/foreign_items.rs (hunk 2 above)
Comment (eddyb) [reply src/tools/miri/src/shims/foreign_items.rs:917]: I can explain this one, it's https://github.com/llvm/llvm-project/commit/8606d013983d2098ba0d9ea9c2129a0b32a93e33 `[APFloat] Enlarge ExponentType to 32bit integer` from late 2019 - previously, miri was stuck with an `i32` and `rustc_apfloat` wanted `i16`, but they now both agree on `i32`.

File: tests/ui/const_prop/apfloat-f64-roundtrip.rs (hunk 3 above)
Comment (eddyb) [reply tests/ui/const_prop/apfloat-f64-roundtrip.rs:3]: LLVM constant-folding is not a pass, but rather happens when instructions are attempted to be created.

There are passes, however, that do non-trivial simplifications, and propagate constants from e.g. loads of constant globals (though that might be in constant-folding, too? unsure), which re-triggers the constant-folding logic that first happened when the instructions were built, to account for their new inputs (you can almost think of it as "replace all uses of X with Y" simply rebuilding all instructions using X, and then the constructors of those instructions see Y now, which lets them try constant-folding again, and maybe get farther this time).

In fewer words: attempting to add a runtime LLVM `Instruction` to a `BasicBlock` may result in a `Constant` being produced instead (I don't know if there's a way to bypass this).

Comment (eddyb) [reply tests/ui/const_prop/apfloat-f64-roundtrip.rs:3]: Small addendum: you may see something different when testing *calls* (of either LLVM intrinsics or `libm` functions it knows about): IIRC, those *are* handled by a pass, it's only the native LLVM IR operations that get constant-folded as they're built.
