### PR TITLE
Modify error message of importing inherent associated items when `#[feature(import_trait_associated_functions)]` is enabled

### LINKED ISSUE #148009: `use`ing inherent method/const gives misleading error
### Code

```Rust
#![feature(import_trait_associated_functions)]

pub struct Test;
 
impl Test {
    pub fn method() {}
    pub const CONST: usize = 0;
}

pub use self::Test::{method, CONST};
```

### Current output

```Shell
error[E0432]: unresolved import `self::Test`
  --> src/lib.rs:10:15
   |
10 | pub use self::Test::{method, CONST};
   |               ^^^^ `Test` is a struct, not a module

For more information about this error, try `rustc --explain E0432`.
```

### Desired output

```Shell
cannot export inherent associated items, only trait associated items

(import *is* resolved, just the wrong type)
```

### Rationale and extra context

Previously, only module items could be re-exported, so, this error made sense from that perspective. However, with #134691, this no longer makes sense and is a little misleading. With the feature enabled, it should mention that this is possible with trait associated items, but not inherent associated items.

*or*, alternatively, it should be implemented for inherent associated items too.

### Rust Version

```Shell
rustc 1.92.0-nightly (57ef8d642 2025-10-15)
```

### PR DESCRIPTION
**Pull request by CoCo-Japan-pan**
Fixes rust-lang/rust#148009

This PR improves the diagnostic for importing inherent associated items from a struct or union when 
`#[feature(import_trait_associated_functions)]` (rust-lang/rust#134691) is enabled.

Previously, this would result in a "not a module" error. This change provides a more specific error message clarifying that only trait associated items can be imported, while inherent associated items remain ineligible for import.

Enums are currently excluded from this change because their variants are valid import targets and require distinct handling.

### CODE REVIEW

File: tests/ui/imports/import-inherent-148009.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
+//! Check that when the feature `import_trait_associated_functions` is enabled,
+//! and one trys to import inherent associated items, the error message is
+//! updated to reflect that only trait associated items can be imported.
+//!
+//! Regression test for <https://github.com/rust-lang/rust/issues/148009>.
```
Comment (madsmtm) [inline tests/ui/imports/import-inherent-148009.rs:5]: I think you have to add further annotations to actually test the label? Something like `//~| NOTE cannot import inherent associated items, only trait associated items` IIRC?

File: compiler/rustc_resolve/src/ident.rs [hunk 2]
```diff
@@ -1943,11 +1943,23 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
                             module_had_parse_errors,
                             module,
                             || {
-                                let label = format!(
-                                    "`{ident}` is {} {}, not a module",
-                                    res.article(),
-                                    res.descr()
-                                );
+                                // Excluding enums since their variants are valid import targets.
```
Comment (madsmtm) [inline compiler/rustc_resolve/src/ident.rs]: Could you add a test case for enums too? I'm not suuper convinced that we don't want a different error message there too, but perhaps I'm missing something?

File: compiler/rustc_resolve/src/ident.rs [hunk 3]
```diff
@@ -1943,11 +1943,23 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
+                                    Res::Def(DefKind::Struct | DefKind::Union, _,)
+                                ) && self
+                                    .tcx
+                                    .features()
+                                    .import_trait_associated_functions()
+                                {
+                                    "cannot import inherent associated items, only trait associated items".to_string()
+                                } else {
+                                    format!(
+                                        "`{ident}` is {} {}, not a module",
```
Comment (madsmtm) [inline compiler/rustc_resolve/src/ident.rs]: We should really be saying "not a module or trait" (or enum) when `import_trait_associated_functions` is enabled, shouldn't we?

**Review by madsmtm — COMMENTED** [review]
Sorry for the delay!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152611/3f808f29e6f5efa56b6e2270e8715a38dfc34b4d..804233ca16c6ce9c594c5a1298f6cc564f22faa5)*

File: compiler/rustc_resolve/src/ident.rs (hunk 2 above)
Comment (CoCo-Japan-pan) [reply compiler/rustc_resolve/src/ident.rs]: For structs or unions, I think the `::` syntax basically leads to associated items, while for enums, it will basically mean enum variants, and the current error for enums says that "there are no such variants", rather than "this is not a module".
Modifying here will overwrite "there are no such variants" errors, so I excluded it here. Maybe I should make it show both?

Comment (madsmtm) [reply compiler/rustc_resolve/src/ident.rs]: Right, enums are treated as-if they're modules, and you'll get a "no `VariantName` in `EnumName`" error pointing to the variant instead.

Which means I don't actually think that matching on `DefKind::Enum` would change anything? This diagnostic is never shown for enums?

But semantically, I think it makes sense to include `DefKind::Enum` (and `DefKind::ForeignTy`) in here, and change the comment to something like:
```suggestion
                                // Show a different error message for items that can have associated items.
```

Comment (CoCo-Japan-pan) [reply compiler/rustc_resolve/src/ident.rs]: Import errors for enums seem to be handled in `rustc_resolve/src/imports.rs`, so I added a note there 4d5ce5ddab2780f0dc38a450f91e12b309b230c6

File: tests/ui/imports/import-inherent-148009.rs (hunk 1 above)
Comment (CoCo-Japan-pan) [reply tests/ui/imports/import-inherent-148009.rs:5]: Added a note `NOTE cannot import inherent associated items, only trait associated items` in  fae6a311e7cbcc8cb393e7a37f7f57c616e4dd2d

File: compiler/rustc_resolve/src/ident.rs (hunk 3 above)
Comment (CoCo-Japan-pan) [reply compiler/rustc_resolve/src/ident.rs]: Modified the error message to `..., not a module or a trait` in 58374d7a9ed625b1b2e92f29fd293e7215819dc7

File: compiler/rustc_resolve/src/ident.rs [hunk 4]
```diff
@@ -2000,10 +2001,28 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
+                                        );
+                                // Show a different error message for items that can have associated items.
                                 let label = format!(
-                                    "`{ident}` is {} {}, not a module",
+                                    "`{ident}` is {} {}, not a module{}",
                                     res.article(),
-                                    res.descr()
+                                    res.descr(),
+                                    if import_inherent_item_error_flag {
+                                        " nor traits"
```
Comment (fmease) [inline compiler/rustc_resolve/src/ident.rs]:
```suggestion
                                        " or a trait"
```

$ident *is* -> singular

(disclaimer: I'm L2) *nor* in this context (i.e., outside *neither* … *nor* …) is fine in colloquial speech but *or* is more correct. The *not* covers both nouns here, so it's "not {a module or a trait}" -(De Morgan)-> "{not a module} and {not a trait}".

Comment (CoCo-Japan-pan) [reply compiler/rustc_resolve/src/ident.rs]: Oops, my mistake. I'll push a fix shortly.

**Comment by madsmtm** [comment]
Haven't found the time for reviewing `rustc` PRs lately:
@rustbot reroll
