### PR TITLE
Provide hint when cast needs a dereference

### LINKED ISSUE #37338: Help is not helpful for error
If you try to compile the code ([play link](https://play.rust-lang.org/?code=fn%20main%28%29%20%7B%0A%20%20%20%20vec!%5B0.0%5D.iter%28%29.map%28%7Cs%7C%20s%20as%20i16%29.collect%3A%3A%3CVec%3Ci16%3E%3E%28%29%3B%0A%7D&version=nightly&backtrace=0)):

``` rust
vec![0.0].iter().map(|s| s as i16).collect::<Vec<i16>>();
```

You get the error

```
rustc 1.14.0-nightly (6e8f92f11 2016-10-07)
error: casting `&f64` as `i16` is invalid
 --> <anon>:2:30
  |
2 |     vec![0.0].iter().map(|s| s as i16).collect();
  |                              ^^^^^^^^
  |
  = help: cast through a raw pointer first

error: aborting due to previous error
```

But casting through a raw pointer (`s as *const f64 as *const i16 as i16`) is not the idiomatic way IMO. Instead it should be fixed by simply dereferencing:

``` rust
vec![0.0].iter().map(|s| *s as i16).collect();
```

### PR DESCRIPTION
**Pull request by estebank**
For a given code:

``` rust
vec![0.0].iter().map(|s| s as i16).collect::<Vec<i16>>();
```

display:

``` nocode
error: casting `&f64` as `i16` is invalid
 --> file3.rs:2:35
  |
2 |     vec![0.0].iter().map(|s| s as i16).collect::<Vec<i16>>();
  |                              -    ^^^
  |                              |
  |                              did you mean `*s`?
```

instead of:

``` nocode
error: casting `&f64` as `i16` is invalid
 --> <anon>:2:30
  |
2 |     vec![0.0].iter().map(|s| s as i16).collect();
  |                              ^^^^^^^^
  |
  = help: cast through a raw pointer first
```

Fixes #37338.

### CODE REVIEW

File: src/librustc_typeck/check/cast.rs [hunk 1]
```diff
@@ -139,6 +140,21 @@ impl<'a, 'gcx, 'tcx> CastCheck<'tcx> {
 
     fn report_cast_error(&self, fcx: &FnCtxt<'a, 'gcx, 'tcx>, e: CastError) {
         match e {
+            CastError::NeedDeref => {
+                let cast_ty = fcx.ty_to_string(self.cast_ty);
+                let mut err = fcx.type_error_struct(self.cast_span,
```
Comment (estebank) [inline src/librustc_typeck/check/cast.rs]: Pointing at the `self.cast_span` instead of `self.span` (`i16` instead of `s as i16` in the example) because when trying to apply the secondary label on just `self.expr.span` (`s` in the example) the actual output looks like this:

```nocode
error: casting `&f64` as `i16` is invalid
 --> file3.rs:2:30
  |
2 |     vec![0.0].iter().map(|s| s as i16).collect::<Vec<i16>>();
  |                              ^^^^^^^^
  |                              |
  |                              casting `&f64` as `i16` is invalid      // <<< this in red
  |                              try dereferencing for the cast to work  // <<< this in blue
```

losing the fact that the secondary label's hint should only apply to the `s` only.

File: src/librustc_typeck/check/cast.rs [hunk 2]
```diff
@@ -139,6 +140,21 @@ impl<'a, 'gcx, 'tcx> CastCheck<'tcx> {
...
+                                       |actual| {
+                                           format!("casting `{}` as `{}` is invalid",
+                                                   actual,
+                                                   cast_ty)
+                                       },
+                                       self.expr_ty);
+                err.span_label(self.cast_span,
+                               &format!("casting `{}` as `{}` is invalid", self.expr_ty, cast_ty));
+                err.span_label(self.expr.span,
```
Comment (nagisa) [inline src/librustc_typeck/check/cast.rs]: This shouldn’t be a span_label, but rather `span_help` instead.

File: src/librustc_typeck/check/cast.rs [hunk 3]
```diff
@@ -375,8 +393,28 @@ impl<'a, 'gcx, 'tcx> CastCheck<'tcx> {
...
+                            ty::InferTy::FloatVar(_) |
+                            ty::InferTy::FreshIntTy(_) |
+                            ty::InferTy::FreshFloatTy(_) => {
+                                Err(CastError::NeedDeref)
+                            }
+                            _ => Err(CastError::NeedViaPtr),
+                        }
+                    }
+                    _ => Err(CastError::NeedViaPtr),
+                }
```
Comment (nagisa) [inline src/librustc_typeck/check/cast.rs]:
```rust
struct A;
&A as A;
```

stays without a note/help. I’m fine with it personally, but that’s something that could use such a help message.

File: src/librustc_typeck/check/cast.rs (hunk 2 above)
Comment (nagisa) [inline src/librustc_typeck/check/cast.rs]: cc @jonathandturner

Comment (jonathandturner) [inline src/librustc_typeck/check/cast.rs]: If we show the deref, it should be `span_help`.

Another way would be to change the label to, for example, "did you mean *{}?"

**Comment by jonathandturner** [comment]
@estebank - I like it!  Can we do one small tweak while you're at it?

```nocode
error: casting `&f64` as `i16` is invalid
 --> foo.rs:2:35
  |
2 |     vec![0.0].iter().map(|s| s as i16).collect::<Vec<i16>>();
  |                              -    ^^^ cannot cast `&f64` as `i64`
  |                              |
  |                              did you mean `*s`?
```

**Comment by estebank** [comment]
@jonathandturner done!

**Comment by jonathandturner** [comment]
Great!

@bors r+ rollup

**Comment by estebank** [comment]
@jonathandturner fixed merge conflict.
