### PR TITLE
Drop `./x suggest`

### LINKED ISSUE #109933: Tracking Issue for `x suggest`
Tracking issue for `x suggest` subcommand and implementation of recommendations. Note that this isn't a traditional tracking issue for a feature but just a place to keep track of implementation. 

See the [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/tool.20to.20suggest.20subset.20of.20tests) and the [initial issue](https://github.com/rust-lang/rust/issues/97339) for more information and rationale about this change.

- [x] Initial PR (#106249)
- [x] `rustc-dev-guide` (rust-lang/rustc-dev-guide#1660)
- [ ] `tidy` lint for suggestion tests, do we want this?
- [ ] Further suggestions

cc @albertlarsan68 @jyn514

### LINKED ISSUE #143569: `./x suggest --run` produces incorrect test failure
### Summary

When using `./x suggest --run`, it seems that a test was run in the incorrect configuration so that it failed in a nonsensical way.

### Command used

```sh
./x suggest --run
```

### Expected behaviour

Tests pass. (Note that the github CI for my PR (https://github.com/rust-lang/rust/pull/138217) had its tests pass.)

### Actual behaviour

Tests fail, in parts of the compiler that I haven't touched.

<details>
<summary>Test output</summary>

```
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.09s
Building stage0 tool suggest-tests (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.10s
==== SUGGESTIONS ====
x check
x test compiler/rustc_mir_transform
x test library/alloc
x test library/alloctests
x test --stage 1 mir-opt
x test --stage 1 tests/ui tests/run-make
=====================
Checking stage0 compiler artifacts {rustc-main, rustc_abi, rustc_arena, rustc_ast, rustc_ast_ir, rustc_ast_lowering, rustc_ast_passes, rustc_ast_pretty, rustc_attr_data_structures, rustc_attr_parsing, rustc_baked_icu_data, rustc_borrowck, rustc_builtin_macros, rustc_codegen_llvm, rustc_codegen_ssa, rustc_const_eval, rustc_data_structures, rustc_driver, rustc_driver_impl, rustc_error_codes, rustc_error_messages, rustc_errors, rustc_expand, rustc_feature, rustc_fluent_macro, rustc_fs_util, rustc_graphviz, rustc_hashes, rustc_hir, rustc_hir_analysis, rustc_hir_pretty, rustc_hir_typeck, rustc_incremental, rustc_index, rustc_index_macros, rustc_infer, rustc_interface, rustc_lexer, rustc_lint, rustc_lint_defs, rustc_llvm, rustc_log, rustc_macros, rustc_metadata, rustc_middle, rustc_mir_build, rustc_mir_dataflow, rustc_mir_transform, rustc_monomorphize, rustc_next_trait_solver, rustc_parse, rustc_parse_format, rustc_passes, rustc_pattern_analysis, rustc_privacy, rustc_proc_macro, rustc_query_impl, rustc_query_system, rustc_resolve, rustc_sanitizers, rustc_serialize, rustc_session, rustc_smir, rustc_span, rustc_symbol_mangling, rustc_target, rustc_thread_pool, rustc_trait_selection, rustc_traits, rustc_transmute, rustc_ty_utils, rustc_type_ir, rustc_type_ir_macros, stable_mir} (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.24s
Checking stage0 rustdoc artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.08s
Checking stage0 cranelift (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.04s
Checking stage0 gcc (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.02s
Checking stage0 clippy artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.15s
Checking stage0 miri artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.10s
Checking stage0 cargo-miri artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.06s
Checking stage0 miropt-test-tools artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.04s
Checking stage0 rustfmt artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.07s
Checking stage0 rust-analyzer artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.24s
Checking stage0 test-float-parse artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.05s
Checking stage0 features-status-dump artifacts (aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.06s
Testing  {rustc_mir_transform} (stage0 -> stage1, aarch64-apple-darwin)
    Finished `release` profile [optimized] target(s) in 0.14s
     Running unittests src/lib.rs (build/aarch64-apple-darwin/stage0-rustc/aarch64-apple-darwin/release/deps/rustc_mir_transform-f7a238eeb5ecee81)

running 15 tests
...............

test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 942.75µs

   Doc-tests rustc_mir_transform

running 18 tests
iiiiiiiiiiii......

test result: ok. 6 passed; 0 failed; 12 ignored; 0 measured; 0 filtered out; finished in 18.50ms


running 7 tests
iiiiiii

test result: ok. 0 passed; 0 failed; 7 ignored; 0 measured; 0 filtered out; finished in 642.21µs

	finished in 3.283 seconds
Testing  {alloc} (stage0 -> stage1, aarch64-apple-darwin)
   Compiling core v0.0.0 (/Users/timch/rust/library/core)
error[E0522]: definition of an unknown lang item: `panic_invalid_enum_construction`
   --> library/core/src/panicking.rs:320:1
    |
320 | #[lang = "panic_invalid_enum_construction"] // needed by codegen for panic on invalid enum construction.
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ definition of unknown lang item `panic_invalid_enum_construction`

error[E0093]: unrecognized intrinsic function: `simd_funnel_shl`
   --> library/core/src/intrinsics/simd.rs:144:15
    |
144 | pub unsafe fn simd_funnel_shl<T>(a: T, b: T, shift: T) -> T;
    |               ^^^^^^^^^^^^^^^ unrecognized intrinsic
    |
    = help: if you're adding an intrinsic, be sure to update `check_intrinsic_type`

error[E0093]: unrecognized intrinsic function: `simd_funnel_shr`
   --> library/core/src/intrinsics/simd.rs:161:15
    |
161 | pub unsafe fn simd_funnel_shr<T>(a: T, b: T, shift: T) -> T;
    |               ^^^^^^^^^^^^^^^ unrecognized intrinsic
    |
    = help: if you're adding an intrinsic, be sure to update `check_intrinsic_type`

error[E0093]: unrecognized intrinsic function: `simd_round_ties_even`
   --> library/core/src/intrinsics/simd.rs:721:15
    |
721 | pub unsafe fn simd_round_ties_even<T>(x: T) -> T;
    |               ^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic
    |
    = help: if you're adding an intrinsic, be sure to update `check_intrinsic_type`

Some errors have detailed explanations: E0093, E0522.
For more information about an error, try `rustc --explain E0093`.
error: could not compile `core` (lib) due to 4 previous errors
	finished in 4.347 seconds

1 command(s) did not execute successfully:

  - cd "/Users/timch/rust" && env -u MAKEFLAGS -u MFLAGS AR_aarch64_apple_darwin="ar" CARGO_INCREMENTAL="1" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="false" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="false" CARGO_PROFILE_RELEASE_STRIP="false" CARGO_TARGET_DIR="/Users/timch/rust/build/aarch64-apple-darwin/stage0-std" CC_aarch64_apple_darwin="cc" CFG_COMPILER_BUILD_TRIPLE="aarch64-apple-darwin" CFG_COMPILER_HOST_TRIPLE="aarch64-apple-darwin" CFG_RELEASE_CHANNEL="dev" CFLAGS_aarch64_apple_darwin="" CXXFLAGS_aarch64_apple_darwin="-stdlib=libc++" CXX_aarch64_apple_darwin="c++" DYLD_LIBRARY_PATH="/Users/timch/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/aarch64-apple-darwin/lib:/Users/timch/rust/build/aarch64-apple-darwin/ci-llvm/lib:/Users/timch/rust/build/aarch64-apple-darwin/stage0/lib" LIBC_CHECK_CFG="1" MACOSX_DEPLOYMENT_TARGET="11.0" RANLIB_aarch64_apple_darwin="ar s" REAL_LIBRARY_PATH_VAR="DYLD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/Users/timch/rust/build/aarch64-apple-darwin/native" RUSTC="/Users/timch/rust/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_ERROR_METADATA_DST="/Users/timch/rust/build/tmp/extended-error-metadata" RUSTC_FORCE_UNSTABLE="1" RUSTC_HOST_FLAGS="--cfg=bootstrap" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/Users/timch/rust/build/aarch64-apple-darwin/stage0/lib" RUSTC_LINK_STD_INTO_RUSTC_DRIVER="1" RUSTC_LINT_FLAGS="-Wrust_2018_idioms -Wunused_lifetimes -Dwarnings" RUSTC_REAL="/Users/timch/rust/build/aarch64-apple-darwin/stage0/bin/rustc" RUSTC_SNAPSHOT="/Users/timch/rust/build/aarch64-apple-darwin/stage0/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/Users/timch/rust/build/aarch64-apple-darwin/stage0/lib" RUSTC_STAGE="0" RUSTC_SYSROOT="/Users/timch/rust/build/aarch64-apple-darwin/stage0-sysroot" RUSTC_VERBOSE="0" RUSTC_WRAPPER="/Users/timch/rust/build/bootstrap/debug/rustc" RUSTDOC="/Users/timch/rust/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="--cfg=bootstrap -Csymbol-mangling-version=legacy --check-cfg=cfg(feature,values(any())) -Zunstable-options -Dwarnings -Wrustdoc::invalid_codeblock_attributes --crate-version 1.90.0-dev -Zcrate-attr=doc(html_root_url=\"https://doc.rust-lang.org/nightly/\") -Zcrate-attr=warn(rust_2018_idioms)" RUSTDOC_LIBDIR="/Users/timch/rust/build/aarch64-apple-darwin/stage0/lib" RUSTDOC_REAL="/Users/timch/rust/build/aarch64-apple-darwin/stage0/bin/rustdoc" RUSTFLAGS="--cfg=bootstrap -Csymbol-mangling-version=legacy --check-cfg=cfg(feature,values(any())) -Zunstable-options -Zmacro-backtrace -Csplit-debuginfo=unpacked -Cprefer-dynamic -Cllvm-args=-import-instr-limit=10 -Zinline-mir -Zinline-mir-preserve-debug -Zmir_strip_debuginfo=locals-in-tiny-functions -Zosx-rpath-install-name -Clink-args=-Wl,-rpath,@loader_path/../lib -Alinker-messages -Clto=off -Zunstable-options -Cforce-frame-pointers=non-leaf -Zcrate-attr=doc(html_root_url=\"https://doc.rust-lang.org/nightly/\")" RUST_TEST_THREADS="10" WINAPI_NO_BUNDLED_LIBRARIES="1" __CARGO_DEFAULT_LIB_METADATA="bootstrapstd1.90.0" "/Users/timch/rust/build/aarch64-apple-darwin/stage0/bin/cargo" "test" "--target" "aarch64-apple-darwin" "-Zbinary-dep-depinfo" "-j" "10" "-Zroot-dir=/Users/timch/rust" "--release" "--features" "backtrace panic-unwind" "--manifest-path" "/Users/timch/rust/library/sysroot/Cargo.toml" "--no-fail-fast" "-p" "alloc" "-p" "alloctests" "--" "--quiet" "-Z" "unstable-options" "--format" "json" (failure_mode=Exit)
Build completed unsuccessfully in 0:00:17
```

</details>

### Bootstrap configuration (bootstrap.toml)
```toml
# See bootstrap.example.toml for documentation of available options
#
profile = "library"  # Includes one of the default files in src/bootstrap/defaults
change-id = 143493
```

### Operating system

MacOS Sequoia 15.5

### HEAD

b33505687b97322ff4f5ee0e65b62a10623f0072

### Additional context

Command for complete build log: `RUST_BACKTRACE=1 ./x suggest --run -v &> log`

Complete build log: https://pastebin.com/cpHMFGvY

### PR DESCRIPTION
**Pull request by jieyouxu**
This PR removes the current `./x suggest` implementation (rust-lang/rust#109933, rust-lang/rust#106249) and associated docs for several reasons:

1. Primarily, `./x suggest` is another "flow" in bootstrap that incurs extra complexity and more invariants that bootstrap has to maintain. This causes more friction when trying to investigate and fix staging problems. As far as I know, this flow has not been actively maintained in quite a while, and I'm not aware of interest in maintaining it. Bootstrap really could use less implementation complexity with a very limited maintenance bandwidth.
2. The current `./x suggest` implementation "bypasses" the usual stage defaults for the various check/build/test/etc. flows, and it's not really possible to have a stage default because `./x suggest --run` produces a *sequence* of suggestions like [`./x check`, `./x test library/std`, ..] and then tries to run all of them in sequence, based on which files are modified.
3. We've not seen a lot of interest both in using it or extending static/dynamic test suggestions. Last extensions were rust-lang/rust#117961 and rust-lang/rust#120763. I'm not convinced the extra implementation complexity is worth it. This was discussed in:
    - [#t-infra/bootstrap > Dropping the current &#96;./x suggest&#96; flow implementation](https://rust-lang.zulipchat.com/#narrow/channel/326414-t-infra.2Fbootstrap/topic/Dropping.20the.20current.20.60.2E.2Fx.20suggest.60.20flow.20implementation/with/527456699)
    - [#t-compiler > Dropping current &#96;./x suggest&#96; implementation](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Dropping.20current.20.60.2E.2Fx.20suggest.60.20implementation/with/527528696)

Closes rust-lang/rust#109933 (the current implementation is being removed).
Closes rust-lang/rust#143569 (by removing `./x suggest` altogether).

### CODE REVIEW

File: src/bootstrap/src/utils/metrics.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ pub(crate) struct BuildMetrics {
     state: RefCell<MetricsState>,
 }
 
-/// NOTE: this isn't really cloning anything, but `x suggest` doesn't need metrics so this is probably ok.
+// NOTE: this isn't really cloning anything, but necessarily for `Build: Clone`.
```
Comment (tshepang) [inline src/bootstrap/src/utils/metrics.rs]: is this what is intended
> but is necessary for `Build: clone`

Comment (jieyouxu) [reply src/bootstrap/src/utils/metrics.rs]: Yes.

Comment (jieyouxu) [reply src/bootstrap/src/utils/metrics.rs]: Fixed.

**Comment by jieyouxu** [comment]
Rebased to fix merge conflict in change tracker, and regenerated completions.

@bors r=Mark-Simulacrum

**Comment by jieyouxu** [comment]
Rebased to fix change tracker merge conflict.

@bors r=Mark-Simulacrum
