### PR TITLE
Modify the ExprUseVisitor to walk each part of an AutoRef

### LINKED ISSUE #20791: Can cast an unusable value to a raw pointer
```rust
fn main() {
    let x: &i32;
    //x; // error: use of possibly uninitialized variable: `x`
    println!("{:?}", x as *const _);
}
```
This is accepted and prints `0x0` everywhere I've tested (rustc 0.13.0-dev (496dc4eae) and the playpen).  A similar access is allowed to moved values and mutably borrowed values.

I assume I should not be able to access uninitialized values without some unsafe code, although I am new to the language and might be missing something.

### PR DESCRIPTION
**Pull request by nikomatsakis**
Modify the ExprUseVisitor to walk each part of an AutoRef, and in
particular to treat an AutoUnsize as as kind of "instantaneous" borrow
of the value being unsized. This prevents us from feeding uninitialized
data.

This caused a problem for the eager reborrow of comparison traits,
because that wound up introducing a "double AutoRef", which was not
being thoroughly checked before but turned out not to type check.
Fortunately, we can just remove that "eager reborrow" as it is no longer
needed now that `PartialEq` doesn't force both LHS and RHS to have the
same type (and even if we did have this problem, the better way would be
to lean on introducing a common supertype).

Fixes #20791.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
Reassigning to @pnkfelix - I really don't know ExprUseVisitor as well as I should, sorry.

File: src/test/run-pass/borrowck-use-uninitialized-in-cast-trait.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+// Variation on `borrowck-use-uninitialized-in-cast` in which we do a
+// trait cast from an uninitialized source. Issue #20791.
+
+trait Foo { fn dummy(&self) { } }
+impl Foo for i32 { }
+
+fn main() {
+    let x: &i32;
+    let y = x as *const Foo; //~ ERROR use of possibly uninitialized variable: `*x`
```
Comment (pnkfelix) [inline src/test/run-pass/borrowck-use-uninitialized-in-cast-trait.rs]: This file should not be in `test/run-pass`

File: src/test/run-pass/borrowck-use-uninitialized-in-cast.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+// Check that we detect unused values that are cast to other things.
+// The problem was specified to casting to `*`, as creating unsafe
+// pointers was not being fully checked. Issue #20791.
+
+// pretty-expanded FIXME #23616
+
+fn main() {
+    let x: &i32;
+    let y = x as *const i32; //~ ERROR use of possibly uninitialized variable: `*x`
```
Comment (pnkfelix) [inline src/test/run-pass/borrowck-use-uninitialized-in-cast.rs]: This file should not be in `test/run-pass`

File: src/librustc/middle/expr_use_visitor.rs [hunk 3]
```diff
@@ -852,39 +843,171 @@ impl<'d,'t,'tcx,TYPER:mc::Typer<'tcx>> ExprUseVisitor<'d,'t,'tcx,TYPER> {
...
                                      AutoRef);
             }
-            ty::AutoUnsize(_) |
+
+            ty::AutoUnsize(_) => {
+                // Converting a `[T; N]` to `[T]` or `T` to `Trait`
+                // isn't really a borrow, move, etc, in and of itself.
+                // Also, no recursive step here, this is a base case.
+
+                // FIXME. It's a bit of a hack to just return `cmt_derefd` here,
```
Comment (pnkfelix) [inline src/librustc/middle/expr_use_visitor.rs]: If you're going to write a comment this long, surely you can file a ticket and copy-and-paste the comment into the ticket?

**Comment by pnkfelix** [comment]
@nikomatsakis r=me when above issues are addressed.

File: src/librustc/middle/expr_use_visitor.rs (hunk 3 above)
Comment (nikomatsakis) [inline src/librustc/middle/expr_use_visitor.rs]: I did not write a ticket because...I think it's a nonsense ticket. That is, there is no real *bug* here, and the code cleanup will probably come over time.

Comment (nikomatsakis) [inline src/librustc/middle/expr_use_visitor.rs]: (But I don't mind writing it. Mainly I try to reserve writing tickets for things that actually cause observable bugs.)

Comment (nikomatsakis) [inline src/librustc/middle/expr_use_visitor.rs]: PS *nonsense ticket* was kind of a poor choice of words. Didn't really mean to imply judgement.

Comment (pnkfelix) [inline src/librustc/middle/expr_use_visitor.rs]: I agree that this is a borderline case at best.  (I usually prefer to err on the side on making a ticket in a case like this, to enable a paper-trail, and/or cross-referencing here on github issues, and/or future developers chiming in with their comments/questions upon encountering the fixme in the code base.)
