### PR TITLE
Fix backtraces with `-C panic=abort` on linux; emit unwind tables by default

### LINKED ISSUE #81902: RUST_BACKTRACE truncated with -Cpanic=abort
When using `-Cpanic=abort`, the resulting panic backtrace is being truncated.

Interestingly, when wrapping with a custom panic hook, this problem is even worse.

```rust
fn main() {
    let next = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| next(info)));

    panic!("oh no! anyway...");
}
```

Tested on nightly and stable. Only seems to be a problem on mac and linux, windows does not seem to be effected.

<details><summary>RUST_BACKTRACE=full with -Cpanic=unwind</summary>
<p>

```
thread 'main' panicked at 'oh no! anyway...', panic-backtrace.rs:5:5
stack backtrace:
   0:     0x5641e75c2937 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5641e75c2937 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5641e75c2937 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5641e75c2937 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5641e75d94dc - core::fmt::write::h3868db8542c90941
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/core/src/fmt/mod.rs:1096:17
   5:     0x5641e75c0b22 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/io/mod.rs:1568:15
   6:     0x5641e75c47f5 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5641e75c47f5 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5641e75c47f5 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:208:50
   9:     0x5641e75c4353 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:225:9
  10:     0x5641e75ac41f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h96c2c6718f794857
  11:     0x5641e75abc34 - panic_backtrace::main::{{closure}}::hce20eff12a892edc
  12:     0x5641e75c4fb6 - std::panicking::rust_panic_with_hook::ha936eb00e51bc4d9
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:595:17
  13:     0x5641e75ac0da - std::panicking::begin_panic::{{closure}}::h7a9154edebf9ece3
  14:     0x5641e75abc85 - std::sys_common::backtrace::__rust_end_short_backtrace::h1e2014397c41a685
  15:     0x5641e75ac026 - std::panicking::begin_panic::h53c35f27b097d4f4
  16:     0x5641e75abc16 - panic_backtrace::main::h5ef5bf96a2375ff6
  17:     0x5641e75abeb6 - core::ops::function::FnOnce::call_once::hc2eccc5827063ab0
  18:     0x5641e75abcb9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e49d68cd7dda505
  19:     0x5641e75ac91c - std::rt::lang_start::{{closure}}::he479198adea7d32d
  20:     0x5641e75c53b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7c92107c3c98a949
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/core/src/ops/function.rs:259:13
  21:     0x5641e75c53b7 - std::panicking::try::do_call::h7454c57e8fbf0cc1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:379:40
  22:     0x5641e75c53b7 - std::panicking::try::he71cdc15ed83b5ec
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:343:19
  23:     0x5641e75c53b7 - std::panic::catch_unwind::hfc08ddb043e6e18c
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panic.rs:410:14
  24:     0x5641e75c53b7 - std::rt::lang_start_internal::he4958117ec6901fd
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/rt.rs:51:25
  25:     0x5641e75ac8f8 - std::rt::lang_start::hdc838a40e951ed3a
  26:     0x5641e75abc5b - main
  27:     0x7f1653f01152 - __libc_start_main
  28:     0x5641e75ab09e - _start
  29:                0x0 - <unknown>
```

</p>
</details>

<details><summary>RUST_BACKTRACE=full with -Cpanic=abort</summary>
<p>

```
thread 'main' panicked at 'oh no! anyway...', panic-backtrace.rs:5:5
stack backtrace:
   0:     0x55bf3d3dc5a7 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55bf3d3dc5a7 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bf3d3dc5a7 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55bf3d3dc5a7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55bf3d3f2a3c - core::fmt::write::h3868db8542c90941
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/core/src/fmt/mod.rs:1096:17
   5:     0x55bf3d3da792 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/io/mod.rs:1568:15
   6:     0x55bf3d3de3c5 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55bf3d3de3c5 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55bf3d3de3c5 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:208:50
   9:     0x55bf3d3ddf23 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:225:9
  10:     0x55bf3d3c610f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h96c2c6718f794857
[1]    488156 abort (core dumped)  RUST_BACKTRACE=full ./panic-backtrace
```

</p>
</details>

Using only `RUST_BACKTRACE=1` in that case will not print any backtrace at all.

### LINKED ISSUE #94815: Please default "force-unwind-tables" to "yes" on Linux, so that unwind tables are present even if panic = "abort"
On Linux, binaries need to contain unwind tables if one wants to get useful and accurate stack traces in profilers, debuggers and crash reports,. This requirement is mostly due to the fact that the Rust compiler, by default, does not use frame pointers on Linux.

When `panic` is set to `"unwind"` (the default), the Rust compiler emits unwind tables for all functions. This is good.

However, when building with `panic = "abort"`, the Rust compiler currently does not emit unwind tables for many functions. For example, a Linux x86_64 build of [dump_syms](https://github.com/mozilla/dump_syms/) with `panic = "abort"` has unwind tables for 5017 functions with the default settings, and for 9204 functions with `-C force-unwind-tables=yes`. The generated code for both builds is identical.

I think `force-unwind-tables=yes` would be a better default. It does not make the generated code any less efficient; it only generates extra information on the side. People who are concerned about binary size and who do not need useful stack traces can still make the trade-off and set `-C force-unwind-tables=no`.

This problem was also encountered in https://github.com/rust-lang/backtrace-rs/issues/397 and in https://github.com/rust-lang/rust/issues/81902.

### PR DESCRIPTION
**Pull request by Enselic**
The linux backtrace unwinder relies on unwind tables to work properly, and generating and printing a backtrace is done by for example the default panic hook.

Begin emitting unwind tables by default again with `-C panic=abort` (see history below) so that backtraces work.

Closes https://github.com/rust-lang/rust/issues/81902 which is **regression-from-stable-to-stable**
Closes https://github.com/rust-lang/rust/issues/94815

### History

Backtraces with `-C panic=abort` used to work in Rust 1.22 but broke in Rust 1.23, because in 1.23 we stopped emitting unwind tables with `-C panic=abort` (see https://github.com/rust-lang/rust/pull/45031 and https://github.com/rust-lang/rust/issues/81902#issuecomment-3046487084).

In 1.45 a workaround in the form of `-C force-unwind-tables=yes` was added (see https://github.com/rust-lang/rust/pull/69984).

`-C panic=abort` was added in [Rust 1.10](https://blog.rust-lang.org/2016/07/07/Rust-1.10/#what-s-in-1-10-stable) and the motivation was binary size and compile time. But given how confusing that behavior has turned out to be, it is better to make binary size optimization opt-in with `-C force-unwind-tables=no` rather than default since the current default breaks backtraces.

Besides, if binary size is a primary concern, there are many other tricks that can be used that has a higher impact.

# Release Note Entry Draft:

## Compatibility Notes

* [Fix backtraces with `-C panic=abort` on Linux by generating unwind tables by default](https://github.com/rust-lang/rust/pull/143613). Build with `-C force-unwind-tables=no` to keep omitting unwind tables.

try-job: aarch64-apple
try-job: armhf-gnu
try-job: aarch64-msvc-1

### CODE REVIEW

File: compiler/rustc_session/src/session.rs [hunk 1]
```diff
@@ -802,10 +802,10 @@ impl Session {
         // If a target requires unwind tables, then they must be emitted.
         // Otherwise, we can defer to the `-C force-unwind-tables=<yes/no>`
         // value, if it is provided, or disable them, if not.
+        //
+        // FIXME: Update the above comment
         self.target.requires_uwtable
-            || self.opts.cg.force_unwind_tables.unwrap_or(
-                self.panic_strategy() == PanicStrategy::Unwind || self.target.default_uwtable,
-            )
+            || self.opts.cg.force_unwind_tables.unwrap_or(self.target.default_uwtable)
```
Comment (bjorn3) [inline compiler/rustc_session/src/session.rs]: Why did you remove the panic=unwind check? This will cause unwind tables to be disabled on some targets where they were previously enabled.

Comment (Enselic) [reply compiler/rustc_session/src/session.rs]: Good catch, leftover from early prototyping and I didn't realize earlier it now is the wrong thing to do, will fix in the next iteration, thank you.

**Comment by hanna-kruppe** [comment]
Note that it’s currently pretty tricky to change this setting from whatever the default is on a given target, since there’s no Cargo profile setting for it (unlike the panic strategy), cc https://github.com/rust-lang/cargo/issues/15333

This observation can probably be used as argument for or against this change.

**Comment by bjorn3** [comment]
If you don't want unwind tables to save space you probably want to strip it out after linking anyway. `-Cpanic=abort` still gives unwind tables for the standard library on targets supporting panic=unwind unless `-Zbuild-std` is used. Would be a good idea to document this stripping in the min-sized-rust guide. You have to strip `.eh_frame`, `.eh_frame_hdr` and `.gcc_except_table`. One complication however is that we do have to keep unwind tables for functions that call `extern "C-unwind"` functions for soundness though.

**Comment by hanna-kruppe** [comment]
If there's a way to drop all unwind tables that can safely be dropped but no more, then that would be a nice new feature (`-Cstrip` variant?) or addition to min-sized-rust. But if you're going all out on minimizing binary size, then you'll already want `-Zbuild-std` for a dozen other reasons anyway. I mostly brought it up from the POV of: if the default is changed, how easily can an ordinary user of stable Rust get back to the current behavior?

**Comment by Enselic** [comment]
Changes since the initial version d113be91b91:
* Add a regression test specifically for backtrace with `-C panic=abort`.
* Adjust `tests/run-make/panic-abort-eh_frame/rmake.rs`. I will also ping the people that added it in https://github.com/rust-lang/rust/pull/112403 for review. Edit: [Done](https://github.com/rust-lang/rust/pull/112403#issuecomment-3049289968).
* I added a draft release note entry to the PR description.

> if the default is changed, how easily can an ordinary user of stable Rust get back to the current behavior?

I don't think ordinary users want to go back to the regression introduced in Rust 1.23, because I expect ordinary users to want backtraces to work.

For advanced users I don't think it's too much to ask to require building with `-C force-unwind-tables=no` to opt back in to the current (arguably broken) behavior.

File: compiler/rustc_session/src/session.rs (hunk 1 above)
Comment (Enselic) [reply compiler/rustc_session/src/session.rs]: Done.

**Comment by nbdd0121** [comment]
> If you don't want unwind tables to save space you probably want to strip it out after linking anyway.

Stripping unwind tables is going to change the behaviour if you link in some foreign static library (e.g. a C++ library) that depends on unwinding.

> One complication however is that we do have to keep unwind tables for functions that call `extern "C-unwind"` functions for soundness though.

I think there is no soundness concern, it's just correctness? Unwinding will stop with error if it cannot find unwind tables.

File: tests/run-make/panic-abort-eh_frame/rmake.rs
Comment (nbdd0121) [inline tests/run-make/panic-abort-eh_frame/rmake.rs:1]: This change looks correct to me.

**Comment by bjorn3** [comment]
> I think there is no soundness concern, it's just correctness? Unwinding will stop with error if it cannot find unwind tables.

Right, only keeping `.eh_frame` without the LSDA would cause soundness issues I think.

**Comment by petrochenkov** [comment]
The implementation LGTM, but is there some consensus about doing this?
I haven't heard from the "we should keep minimizing size" camp yet.

**Comment by petrochenkov** [comment]
Let's start a compiler FCP, see the PR description for what is changed.
@rfcbot merge

**Comment by nagisa** [comment]
I'm +1 on this change if for no other reason that my personal use-cases generally tend to prefer `-Cpanic=abort` for perf/compile time reasons, but I also almost always care a bunch about keeping unwind tables for stack traces for profiling and just generally.

AT least my experience suggests it to be a more common use-case to want these working out of the box which is a good argument to making it work by default. Another is that people pursuing minimum binary size tend to have to apply modifications to how they build anyway, so another flag/step doesn't sound like too onerous a problem (so long as we figure out how to strip only those uwtables that don't affect soundness.)

**Comment by Noratrieb** [comment]
@rfcbot reviewed

Not a blocking concern, but it would be nice if the documentation was made more precise about which targets have which behavior: https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html?highlight=unwind-tables#force-unwind-tables

**Comment by Mark-Simulacrum** [comment]
@rfcbot resolve testing-rfcbot-ignore

**Comment by Enselic** [comment]
@petrochenkov Is there anything I can help with in order to get this merged now that the FCP is complete?

**Comment by petrochenkov** [comment]
The bot should set the label to `S-waiting-on-team` when FCP is complete, but it does not currently.
@bors r+

**Comment by Zalathar** [comment]
Yielding to enclosing rollup.

@bors retry

**Comment by Enselic** [comment]
@petrochenkov Can you (or someone else) do 

```
@bors2 try jobs=aarch64-apple
```

please? Or maybe even `@bors2 delegate=try`.

**Comment by Enselic** [comment]
@petrochenkov If [this](https://github.com/rust-lang/rust/compare/826aa6066c7988374f67104d60d72622d3cf42cd..142fd676d67e7ed37c98057a0940266b96c2094e) diff compared to what you [already](https://github.com/rust-lang/rust/pull/143613#issuecomment-3295967533) approved [looks ok](https://github.com/rust-lang/rust/pull/143613#issuecomment-3299876864), this is ready to be `r+`:ed again.

**Comment by Enselic** [comment]
@petrochenkov Can you run `@bors2 try jobs=armhf-gnu` again please?

This is probably not the last round of try jobs so I do think that delegating try job capabilities to me in the scope of this PR would be appropriate.

You can do it by saying `@bors2 delegate=try`.

**Comment by petrochenkov** [comment]
@bors2 try jobs=armhf-gnu
@bors2 delegate=try

**Comment by Enselic** [comment]
I expect more jobs to fail, but we might as well find those by trying to merge.

@petrochenkov Can you `r+` please? The diff what from you already approved is [this](https://triagebot.infra.rust-lang.org/gh-range-diff/rust-lang/rust/1b0bc594a75dfc1cdedc6c17052cf44de101e632..142fd676d67e7ed37c98057a0940266b96c2094e/15283f6fe95e5b604273d13a428bab5fc0788f5a..2a55a15eecc102f1d9d8ecc5bdcb98c15a30e4d8).

The `armhf-gnu` job failure was caused by an [old LLVM bug](https://github.com/llvm/llvm-project/issues/69020) that so we need a workaround on `arm-unknown-linux-gnueabihf` in the form of the diff you see above. See https://github.com/rust-lang/rust/issues/146996 for more info.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/147158#issuecomment-3348763751

**Comment by Enselic** [comment]
@bors2 try

**Comment by Enselic** [comment]
@bors2 try

**Comment by Enselic** [comment]
@petrochenkov Ready for r+ if [this diff](https://github.com/rust-lang/rust/compare/2a55a15..fe66eaa67acc47525db6f13cf97d54780d87b805) looks ok.

@rustbot ready
