### PR TITLE
change an instance of span_bug() to struct_span_err() to avoid ICE

### LINKED ISSUE #68890: internal compiler error: unexpected lifetime bound
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```
$ echo "enum e{A((?'a a+?+l))}" > main.rs
$ rustc main.rs
error: `?` may only modify trait bounds, not lifetime bounds
 --> main.rs:1:11
  |
1 | enum e{A((?'a a+?+l))}
  |           ^

error: expected one of `)`, `+`, or `,`, found `a`
 --> main.rs:1:15
  |
1 | enum e{A((?'a a+?+l))}
  |               ^ expected one of `)`, `+`, or `,`

error: internal compiler error: unexpected lifetime bound
 --> main.rs:1:11
  |
1 | enum e{A((?'a a+?+l))}
  |           ^^^

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (58b834344 2020-02-05) running on x86_64-unknown-linux-gnu

error: aborting due to 3 previous errors
```

The error happens on `nightly` and `beta` but not on `stable`.

### PR DESCRIPTION
**Pull request by dwrensha**
After #67148, the `span_bug()` in `parse_ty_tuple_or_parens()` is reachable because `parse_paren_comma_seq()` can return an `Ok()` even in cases where it encounters an error.
This pull request prevents an ICE in such cases by replacing the `span_bug()` with `struct_span_error()`.

Fixes #68890.

### CODE REVIEW

File: src/test/ui/parser/issue-68890.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+enum e{A((?'a a+?+l))}
```
Comment (Centril) [inline src/test/ui/parser/issue-68890.rs]: A slightly simpler reproducer btw, `type X = (?'a ?+l);`.

Comment (dwrensha) [reply src/test/ui/parser/issue-68890.rs]: OK, I'll update this.

Comment (Centril) [reply src/test/ui/parser/issue-68890.rs]: Not necessary, yours is sufficiently minimal. ;)
