### PR TITLE
Pretty-print parenthesis around binary in postfix match

### LINKED ISSUE #124206: AST pretty-printer produces invalid syntax for postfix match
```rust
// main.rs

#![feature(postfix_match)]

macro_rules! repro {
    ($e:expr) => {
        $e.match { _ => {} }
    };
}

fn main() {
    repro!({ 1 } + 1);
}
```

As of current nightly, `rustc -Zunpretty=expanded main.rs` produces this:

```console
#![feature(prelude_import)]
#![no_std]
// main.rs

#![feature(postfix_match)]
#[prelude_import]
use ::std::prelude::rust_2015::*;
#[macro_use]
extern crate std;

macro_rules! repro { ($e:expr) => { $e.match { _ => {} } }; }

fn main() { { 1 } + 1.match { _ => {} }; }
```

which is not valid Rust syntax.

```console
error: leading `+` is not supported
  --> <anon>:13:19
   |
13 | fn main() { { 1 } + 1.match { _ => {} }; }
   |                   ^ unexpected `+`
   |
help: parentheses are required to parse this as an expression
   |
13 | fn main() { ({ 1 }) + 1.match { _ => {} }; }
   |             +     +
```

The correct output would contain `({ 1 } + 1).match { _ => {} }`.

https://github.com/rust-lang/rust/labels/F-postfix_match tracking issue: https://github.com/rust-lang/rust/issues/121618

### PR DESCRIPTION
**Pull request by scrabsha**
Fixes #124206.

### CODE REVIEW

File: compiler/rustc_ast_pretty/src/pprust/state/expr.rs [hunk 1]
```diff
@@ -488,7 +488,18 @@ impl<'a> State<'a> {
                         self.space();
                     }
                     MatchKind::Postfix => {
+                        let need_par = matches!(expr.kind, ast::ExprKind::Binary(_, _, _));
```
Comment (scrabsha) [inline compiler/rustc_ast_pretty/src/pprust/state/expr.rs:491]: I looked at the [Expression precedence][1] table of the Reference and found nothing else to wrap in parentheses.

Please comment if I missed something!

[1]: https://doc.rust-lang.org/reference/expressions.html#expression-precedence

**Comment by RossSmyth** [comment]
Could you please either give the test name something descriptive about what the test tests (idk pfix-match-paren or something) or make a new directory for postfix match within the pretty directory. Adding tests with issue numbers, while common, makes maintenance frustrating.

**Comment by scrabsha** [comment]
> Could you please either give the test name something descriptive about what the test tests (idk pfix-match-paren or something) or make a new directory for postfix match within the pretty directory. Adding tests with issue numbers, while common, makes maintenance frustrating.

I `mkdir`ed `tests/pretty/postfix-match` and moved every postfix-match-related test in it. Thanks for the suggestion!

File: compiler/rustc_ast_pretty/src/pprust/state/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_ast_pretty/src/pprust/state/expr.rs:491]: It's probably best to use https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/struct.Expr.html#method.precedence instead of matching exhaustively on `ExprKind`

like `.precedence() <= PREC_SOMETHING` or `<` or something (idk which predecence to choose)

Comment (scrabsha) [reply compiler/rustc_ast_pretty/src/pprust/state/expr.rs]: Thanks for your comment. This allowed me to fix a few other instances of the bug reported by #124206!

File: tests/pretty/postfix-match/precedence.pp [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+//@ pp-exact:precedence.pp
+
+macro_rules! repro { ($e:expr) => { $e.match { _ => {} } }; }
+
+pub fn main() {
+    let a;
+    (
+        { 1 } + 1).match {
+        _ => {}
+    };
```
Comment (scrabsha) [inline tests/pretty/postfix-match/precedence.pp:19]: This looks incorrect. Is it an issue in my code or in the pretty printer?

**Review by dtolnay — CHANGES_REQUESTED** [review]
This is going to cause double parens to be put around cases like `repro!(1 + Struct {})`. `((1 + Struct {})).match { _ => {} }`

In general `print_expr_as_cond` is not a correct thing to be using here. That is for syntactic positions where a `{` is ambiguous between being a part of the matched expression / if condition / while condition, vs being the body for the match/if/while. It isn't applicable to postfix match.

Postfix match needs to be printed like very other expression kind containing `.`, such as field accesses and method call expressions and postfix await.

**Comment by scrabsha** [comment]
@dtolnay I modified my changes according to your comment and added your example in the test suite. Thanks!

@rustbot label -S-waiting-on-author +S-waiting-on-review

**Review by dtolnay — APPROVED** [review]
Thanks!
