### PR TITLE
Make closure capturing have consistent and correct behaviour around patterns

### LINKED ISSUE #137467: internal compiler error: two identical projections
### Code

I dont really want to make a MRE right now, so this is the entire project
https://github.com/HomelikeBrick42/4dStuff/tree/rustc_bug

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: x86_64-pc-windows-msvc
release: 1.85.0
LLVM version: 19.1.7
```

### Error output

```
thread 'rustc' panicked at compiler\rustc_mir_build\src\builder\matches\mod.rs:2087:44:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ffbef3001c1 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffbef3001c1 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffbef3001c1 - std::sys::backtrace::_print_fmt
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\backtrace.rs:66
   3:     0x7ffbef3001c1 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\backtrace.rs:39
   4:     0x7ffbef332cca - core::fmt::rt::Argument::fmt
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\fmt\rt.rs:177
   5:     0x7ffbef332cca - core::fmt::write
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\fmt\mod.rs:1440
   6:     0x7ffbef2f5b07 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\io\mod.rs:1887
   7:     0x7ffbef300005 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\backtrace.rs:42
   8:     0x7ffbef302fad - std::panicking::default_hook::closure$1
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:295
   9:     0x7ffbef302d10 - std::panicking::default_hook
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:322
  10:     0x7ffbf08f533a - core[13dd8dac7b8322e0]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[84e5be47eb57ee2d]::Level, &str), usize), <((rustc_lint_defs[84e5be47eb57ee2d]::Level, &str), usize) as core[13dd8dac7b8322e0]::cmp::PartialOrd>::lt>
  11:     0x7ffbef30389e - alloc::boxed::impl$30::call
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\alloc\src\boxed.rs:2007
  12:     0x7ffbef30389e - std::panicking::rust_panic_with_hook
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:836
  13:     0x7ffbef3035c2 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:694
  14:     0x7ffbef300c9f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\backtrace.rs:168
  15:     0x7ffbef3031fe - std::panicking::begin_panic_handler
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\panicking.rs:692
  16:     0x7ffbf21b2e41 - core::panicking::panic_fmt
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\panicking.rs:75
  17:     0x7ffbf21b2efd - core::panicking::panic
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\panicking.rs:145
  18:     0x7ffbf21b2dbe - core::option::unwrap_failed
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\core\src\option.rs:2015
  19:     0x7ffbef8b443d - rustc_mir_build[74ebac55960bf4f1]::builder::mir_build
  20:     0x7ffbef8f4195 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  21:     0x7ffbef8f4792 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  22:     0x7ffbef8b1b6f - rustc_mir_build[74ebac55960bf4f1]::builder::mir_build
  23:     0x7ffbeec6ff45 - <alloc[f42caee64323a5c9]::raw_vec::RawVec<rustc_data_structures[b27a1c9e0d2e22bf]::graph::iterate::Event<rustc_middle[76d8ed0cc97ff880]::mir::BasicBlock>>>::grow_one
  24:     0x7ffbef8965e5 - rustc_mir_build[74ebac55960bf4f1]::builder::mir_build
  25:     0x7ffbef8e772c - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  26:     0x7ffbef8e6fb4 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  27:     0x7ffbef8e95b1 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  28:     0x7ffbef8e6fb4 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  29:     0x7ffbef895f07 - rustc_mir_build[74ebac55960bf4f1]::builder::mir_build
  30:     0x7ffbef8e772c - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  31:     0x7ffbef8e6fb4 - rustc_mir_build[74ebac55960bf4f1]::thir::pattern::check_match::check_match
  32:     0x7ffbef86cfa3 - rustc_mir_build[74ebac55960bf4f1]::builder::mir_build
  33:     0x7ffbef74c43b - rustc_mir_transform[5978154a3d28926b]::mir_built
  34:     0x7ffbf009b9eb - rustc_query_impl[cd955f68236d2689]::plumbing::query_key_hash_verify_all
  35:     0x7ffbeffe0a4b - RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtCsfk1N0zTQ1Ep_21rustc_data_structures9vec_cache8VecCacheNtNtCs8yPNJtyUAIM_10rustc_span6def_id10LocalDefIdINtNtNtCsacCxZy8tNDM
  36:     0x7ffbeeeee56e - rustc_query_impl[cd955f68236d2689]::query_system
  37:     0x7ffbeec7444e - <alloc[f42caee64323a5c9]::raw_vec::RawVec<rustc_data_structures[b27a1c9e0d2e22bf]::graph::iterate::Event<rustc_middle[76d8ed0cc97ff880]::mir::BasicBlock>>>::grow_one
  38:     0x7ffbef8ca332 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_expr
  39:     0x7ffbef8cb846 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_expr
  40:     0x7ffbef8ca332 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_expr
  41:     0x7ffbef8c9362 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_block
  42:     0x7ffbef8cb873 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_expr
  43:     0x7ffbef8ca332 - <rustc_mir_build[74ebac55960bf4f1]::check_unsafety::UnsafetyVisitor as rustc_middle[76d8ed0cc97ff880]::thir::visit::Visitor>::visit_expr
  44:     0x7ffbef8cc53d - rustc_mir_build[74ebac55960bf4f1]::check_unsafety::check_unsafety
  45:     0x7ffbf0099c3a - rustc_query_impl[cd955f68236d2689]::plumbing::query_key_hash_verify_all
  46:     0x7ffbeffd4bce - RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtCsfk1N0zTQ1Ep_21rustc_data_structures9vec_cache8VecCacheNtNtCs8yPNJtyUAIM_10rustc_span6def_id10LocalDefIdINtNtNtCsacCxZy8tNDM
  47:     0x7ffbf00a344b - rustc_query_impl[cd955f68236d2689]::plumbing::query_key_hash_verify_all
  48:     0x7ffbef37b86e - rustc_interface[891a09a0cea1e8ed]::passes::resolver_for_lowering_raw
  49:     0x7ffbec337dde - rustc_interface[891a09a0cea1e8ed]::passes::analysis
  50:     0x7ffbeeee509a - <alloc[f42caee64323a5c9]::sync::Arc<rustc_session[a1380b7e7bd1e9c4]::cstore::CrateSource>>::drop_slow
  51:     0x7ffbeede9ca6 - RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsacCxZy8tNDM_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  52:     0x7ffbeeeeac44 - rustc_query_impl[cd955f68236d2689]::query_system
  53:     0x7ffbec2fe3c9 - RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
  54:     0x7ffbec2f6d9e - RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
  55:     0x7ffbec2efe09 - RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCsbLMVCc8CHyP_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCs13KITJ2Zc2G_17rustc_driver_i
  56:     0x7ffbec302ea5 - RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
  57:     0x7ffbef3157cd - alloc::boxed::impl$28::call_once
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\alloc\src\boxed.rs:1993
  58:     0x7ffbef3157cd - alloc::boxed::impl$28::call_once
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\alloc\src\boxed.rs:1993
  59:     0x7ffbef3157cd - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\pal\windows\thread.rs:56
  60:     0x7ffcb58c259d - BaseThreadInitThunk
  61:     0x7ffcb620af38 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.85.0 (4d91de4e4 2025-02-17) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `<impl at src\lib.rs:68:1: 68:23>::draw_ui::{closure#0}`
#1 [check_unsafety] unsafety-checking `<impl at src\lib.rs:68:1: 68:23>::draw_ui`
end of query stack
note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: two identical projections: ([Projection { ty: Camera, kind: Deref }, Projection { ty: transform::Transform, kind: Field(0, 1) }], [Projection { ty: Camera, kind: Deref }, Projection { ty: transform::Transform, kind: Field(0, 0) }])
  --> src\lib.rs:75:23
   |
75 |           ui.horizontal(|ui| {
   |  _______________________^
76 | |             ui.label("Position: ");
77 | |             if position.draw_ui(ui) {
78 | |                 let difference = position - old_position;
...  |
87 | |         });
   | |_________^
   |
note: delayed at compiler\rustc_hir_typeck\src\upvar.rs:931:28 - disabled backtrace
  --> src\lib.rs:75:23
   |
75 |           ui.horizontal(|ui| {
   |  _______________________^
76 | |             ui.label("Position: ");
77 | |             if position.draw_ui(ui) {
78 | |                 let difference = position - old_position;
...  |
87 | |         });
   | |_________^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.85.0 (4d91de4e4 2025-02-17) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `ray_tracer` (lib) generated 1 warning
error: could not compile `ray_tracer` (lib); 1 warning emitted
```

### LINKED ISSUE #137553: Closure captures are inconsistent between `x` and `x @ _` irrefutable patterns
Background: apart from paths, another way to make use of the precise capture of variables by closures is with irrefutable patterns: 

```rust
fn main() {
    let mut a = (21, 37);
    // only captures a.0, example compiles fine
    let mut f = || {
        let (ref mut x, _) = a;
        *x = 42;
    };
    a.1 = 69;
    f();
}
```

One would expect this to be equivalent to an `if let` or `match` that happens to be irrefutable. However, this isn't the case:

```rust
fn main() {
    let mut a = (21, 37);
    // captures the entirety of a, example doesn't pass borrow check
    let mut f = || {
        match a {
            (ref mut x, _) => *x = 42,
        }
    };
    a.1 = 69;
    f();
}
```

However, one can get the code to compile again by introducing a no-op `@`-pattern:

```rust
fn main() {
    let mut a = (21, 37);
    // captures only a.0 again, and against all odds, the example compiles
    let mut f = || {
        match a {
            (ref mut x @ _, _) => *x = 42,
        }
    };
    a.1 = 69;
    f();
}
```

This suggests that the inconsistency is definitely a bug.

I have discovered this while investigating #137467, and I am working on resolving both issues. I am creating this issue to make it easy to keep track of the bug.

@rustbot claim

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (f280acf4c 2025-02-19)
binary: rustc
commit-hash: f280acf4c743806abbbbcfe65050ac52ec4bdec0
commit-date: 2025-02-19
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

(git blame suggests that this behavior got introduced 3 years ago or so)

### LINKED ISSUE #138973: ICE: called `Option::unwrap()` on a `None` value with refutable patterns
This was found while investigating #138958, but unlike that issue, this code is already an ICE on stable and not a recent regression.

### Code

```Rust
pub fn match_const(x: u32) {
    let _ = || {
        let (0 | _) = x;
    };
}
```

### Meta

`rustc --version --verbose`:
```
stable 1.85.1, nightly 1.87.0-nightly (2025-03-25 43f0014ef0f242418674)
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/builder/matches/mod.rs:2087:44:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7081242dfb8a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfc616348d9ad0abc
   1:     0x708124a14d26 - core::fmt::write::h7ca648217bc79799
   2:     0x708125918711 - std::io::Write::write_fmt::h7960c58bfa5ccbcb
   3:     0x7081242df9e2 - std::sys::backtrace::BacktraceLock::print::h3fb349e80cbe0423
   4:     0x7081242e1f87 - std::panicking::default_hook::{{closure}}::h3366e5842cba645d
   5:     0x7081242e1d70 - std::panicking::default_hook::hd7573a5d4879884b
   6:     0x708123451c48 - std[26cf95b4f122e720]::panicking::update_hook::<alloc[653926f6abfe8a8a]::boxed::Box<rustc_driver_impl[bcf7efa42268b866]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7081242e2813 - std::panicking::rust_panic_with_hook::h66e909d048c263a9
   8:     0x7081242e24d6 - std::panicking::begin_panic_handler::{{closure}}::h8d9aa8be7e8634cf
   9:     0x7081242e0069 - std::sys::backtrace::__rust_end_short_backtrace::h7d7e47ef99abf6aa
  10:     0x7081242e21cd - rust_begin_unwind
  11:     0x708120fa0ef0 - core::panicking::panic_fmt::hf8ffc7c15bfb58a0
  12:     0x7081211a958c - core::panicking::panic::h209220e15dcf6e53
  13:     0x70812256d319 - core::option::unwrap_failed::h12717cc50f158ee2
  14:     0x708125a19268 - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::test_candidates
  15:     0x7081253fc60f - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::match_candidates
  16:     0x7081253fc6ec - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::match_candidates
  17:     0x708125402d3b - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::lower_match_tree
  18:     0x708124c48c91 - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::place_into_pattern
  19:     0x7081212e1f8e - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::ast_block_stmts
  20:     0x708124c5a6e6 - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::expr_into_dest
  21:     0x708124c5c3ba - <rustc_mir_build[b1f93083d90156e8]::builder::Builder>::expr_into_dest
  22:     0x7081253f48ca - rustc_mir_build[b1f93083d90156e8]::builder::mir_build
  23:     0x708124a07304 - rustc_mir_transform[db6cedf3c7b9f288]::mir_built
  24:     0x708124a072c7 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  25:     0x708124d0b817 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  26:     0x708124d0b3cd - rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  27:     0x708125418751 - <rustc_mir_build[b1f93083d90156e8]::check_unsafety::UnsafetyVisitor>::visit_inner_body
  28:     0x708125419898 - <rustc_mir_build[b1f93083d90156e8]::check_unsafety::UnsafetyVisitor as rustc_middle[9ee9ea6fc8845c53]::thir::visit::Visitor>::visit_expr
  29:     0x7081254193ac - <rustc_mir_build[b1f93083d90156e8]::check_unsafety::UnsafetyVisitor as rustc_middle[9ee9ea6fc8845c53]::thir::visit::Visitor>::visit_block
  30:     0x70812541ac1f - <rustc_mir_build[b1f93083d90156e8]::check_unsafety::UnsafetyVisitor as rustc_middle[9ee9ea6fc8845c53]::thir::visit::Visitor>::visit_expr
  31:     0x708125419898 - <rustc_mir_build[b1f93083d90156e8]::check_unsafety::UnsafetyVisitor as rustc_middle[9ee9ea6fc8845c53]::thir::visit::Visitor>::visit_expr
  32:     0x708121b05b51 - rustc_mir_build[b1f93083d90156e8]::check_unsafety::check_unsafety
  33:     0x708125222dbd - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>>
  34:     0x708125223070 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  35:     0x708125222d01 - rustc_query_impl[291ba1fcadd92b61]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  36:     0x708124df91fe - rustc_interface[ad5173bb1fff4f1]::passes::run_required_analyses
  37:     0x70812591c59e - rustc_interface[ad5173bb1fff4f1]::passes::analysis
  38:     0x70812591c56f - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>>
  39:     0x7081259c0415 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_query_system[397df17712590249]::query::caches::SingleCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  40:     0x7081259c014e - rustc_query_impl[291ba1fcadd92b61]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x70812595ad9e - rustc_interface[ad5173bb1fff4f1]::passes::create_and_enter_global_ctxt::<core[1d264cc251a564c0]::option::Option<rustc_interface[ad5173bb1fff4f1]::queries::Linker>, rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  42:     0x708125999516 - rustc_interface[ad5173bb1fff4f1]::interface::run_compiler::<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}
  43:     0x708125883511 - std[26cf95b4f122e720]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_with_globals<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_pool_with_globals<rustc_interface[ad5173bb1fff4f1]::interface::run_compiler<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  44:     0x7081258839c8 - <<std[26cf95b4f122e720]::thread::Builder>::spawn_unchecked_<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_with_globals<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_pool_with_globals<rustc_interface[ad5173bb1fff4f1]::interface::run_compiler<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[1d264cc251a564c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x708125884f81 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1bbaaa2227026bb
  46:     0x70812707ca94 - <unknown>
  47:     0x708127109a34 - clone
  48:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.85.1 (4eb161250 2025-03-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `match_const::{closure#0}`
#1 [check_unsafety] unsafety-checking `match_const`
end of query stack
error: could not compile `playground` (lib)
```

</p>
</details>

### LINKED ISSUE #140011: ICE: upvar: assertion failed: `1 == 2`  `-Wrust-2021-incompatible-closure-captures`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Wrust-2021-incompatible-closure-captures
enum Either {
    One(XorShiftRng),
    Two(X),
}

struct X;

fn move_into_fnmut() {
    let x = Either::One(X);
    let y = || {
        let Either::Two(a) = x;
    };
}

````

original:
````rust
enum Either {
    One(XorShiftRng),
    Two(X),
}

struct X;

fn move_into_fnmut() {
    let x = Either::One(X);
    let y = || {
        let Either::Two(a) = x;
    };
}

fn main() { }

````

Version information
````
rustc 1.88.0-nightly (1f76d219c 2025-04-17)
binary: rustc
commit-hash: 1f76d219c906f0112bb1872f33aa977164c53fa6
commit-date: 2025-04-17
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/1f76d219c906f0112bb1872f33aa977164c53fa6/compiler/rustc_hir_typeck/src/upvar.rs#L1610-L1622

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Wrust-2021-incompatible-closure-captures`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `XorShiftRng` in this scope
 --> /tmp/icemaker_global_tempdir.mjs3HhQOcIiO/rustc_testrunner_tmpdir_reporting.JVHxPnPMCvzx/mvce.rs:2:9
  |
2 |     One(XorShiftRng),
  |         ^^^^^^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.mjs3HhQOcIiO/rustc_testrunner_tmpdir_reporting.JVHxPnPMCvzx/mvce.rs:13:2
   |
13 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.mjs3HhQOcIiO/rustc_testrunner_tmpdir_reporting.JVHxPnPMCvzx/mvce.rs`


thread 'rustc' panicked at compiler/rustc_hir_typeck/src/upvar.rs:1616:17:
assertion `left == right` failed
  left: 2
 right: 1
stack backtrace:
   0:     0x74c9c96c4bf3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h72d2f767860f01c8
   1:     0x74c9c9e05b07 - core::fmt::write::ha0040902920efb26
   2:     0x74c9cb297351 - std::io::Write::write_fmt::h92d425739cf7f0f8
   3:     0x74c9c96c4a52 - std::sys::backtrace::BacktraceLock::print::h60480fc7af7284f9
   4:     0x74c9c96c83ca - std::panicking::default_hook::{{closure}}::h0210b2339a694596
   5:     0x74c9c96c7f4f - std::panicking::default_hook::h26e462c1b992a8d3
   6:     0x74c9c8745753 - std[5360fa45f3745eb7]::panicking::update_hook::<alloc[3e73228144efd5c3]::boxed::Box<rustc_driver_impl[9f43b67c13dcf142]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x74c9c96c8c43 - std::panicking::rust_panic_with_hook::h9046e71ecea68928
   8:     0x74c9c96c893a - std::panicking::begin_panic_handler::{{closure}}::hb8579fcd3517556a
   9:     0x74c9c96c50c9 - std::sys::backtrace::__rust_end_short_backtrace::h7c2200761e8b2677
  10:     0x74c9c96c85fd - __rustc[5b4c3b5a2bd13629]::rust_begin_unwind
  11:     0x74c9c60863c0 - core::panicking::panic_fmt::h39077f0ed79e3d52
  12:     0x74c9c80c3eca - core::panicking::assert_failed_inner::hd76d8c96d70011e6
  13:     0x74c9c80c3df9 - core::panicking::assert_failed::he4657e61c1bba572
  14:     0x74c9c8af5f9a - <rustc_hir_typeck[19dd2fb0ef174692]::fn_ctxt::FnCtxt>::has_significant_drop_outside_of_captures
  15:     0x74c9c8af1fc4 - <rustc_hir_typeck[19dd2fb0ef174692]::fn_ctxt::FnCtxt>::perform_2229_migration_analysis
  16:     0x74c9ca6e0807 - <rustc_hir_typeck[19dd2fb0ef174692]::fn_ctxt::FnCtxt>::analyze_closure
  17:     0x74c9ca6b0052 - <rustc_hir_typeck[19dd2fb0ef174692]::upvar::InferBorrowKindVisitor as rustc_hir[5929cbe382679e99]::intravisit::Visitor>::visit_expr
  18:     0x74c9ca6aff58 - <rustc_hir_typeck[19dd2fb0ef174692]::upvar::InferBorrowKindVisitor as rustc_hir[5929cbe382679e99]::intravisit::Visitor>::visit_block
  19:     0x74c9ca6b332a - rustc_hir_typeck[19dd2fb0ef174692]::typeck_with_inspect::{closure#0}
  20:     0x74c9ca6b19b6 - rustc_query_impl[5554cc5a49e13358]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5554cc5a49e13358]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[be3fd842b5d62089]::query::erase::Erased<[u8; 8usize]>>
  21:     0x74c9ca071e6c - rustc_query_system[6a51e1997cb665e8]::query::plumbing::try_execute_query::<rustc_query_impl[5554cc5a49e13358]::DynamicConfig<rustc_data_structures[c6be5df131b5adc5]::vec_cache::VecCache<rustc_span[34967910c7e58b20]::def_id::LocalDefId, rustc_middle[be3fd842b5d62089]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6a51e1997cb665e8]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[5554cc5a49e13358]::plumbing::QueryCtxt, false>
  22:     0x74c9ca0718cb - rustc_query_impl[5554cc5a49e13358]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  23:     0x74c9ca070348 - rustc_hir_analysis[4ccd349711354d63]::check_crate
  24:     0x74c9ca1fc074 - rustc_interface[ea4bb220888d6441]::passes::run_required_analyses
  25:     0x74c9cacc229e - rustc_interface[ea4bb220888d6441]::passes::analysis
  26:     0x74c9cacc2273 - rustc_query_impl[5554cc5a49e13358]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5554cc5a49e13358]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[be3fd842b5d62089]::query::erase::Erased<[u8; 0usize]>>
  27:     0x74c9cacc7d3d - rustc_query_system[6a51e1997cb665e8]::query::plumbing::try_execute_query::<rustc_query_impl[5554cc5a49e13358]::DynamicConfig<rustc_query_system[6a51e1997cb665e8]::query::caches::SingleCache<rustc_middle[be3fd842b5d62089]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[5554cc5a49e13358]::plumbing::QueryCtxt, false>
  28:     0x74c9cacc7a38 - rustc_query_impl[5554cc5a49e13358]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  29:     0x74c9caf4e0fe - rustc_interface[ea4bb220888d6441]::passes::create_and_enter_global_ctxt::<core[6a8fd511579d4332]::option::Option<rustc_interface[ea4bb220888d6441]::queries::Linker>, rustc_driver_impl[9f43b67c13dcf142]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  30:     0x74c9caf3c484 - rustc_interface[ea4bb220888d6441]::interface::run_compiler::<(), rustc_driver_impl[9f43b67c13dcf142]::run_compiler::{closure#0}>::{closure#1}
  31:     0x74c9caf2cab4 - std[5360fa45f3745eb7]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ea4bb220888d6441]::util::run_in_thread_with_globals<rustc_interface[ea4bb220888d6441]::util::run_in_thread_pool_with_globals<rustc_interface[ea4bb220888d6441]::interface::run_compiler<(), rustc_driver_impl[9f43b67c13dcf142]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  32:     0x74c9caf2cef4 - <<std[5360fa45f3745eb7]::thread::Builder>::spawn_unchecked_<rustc_interface[ea4bb220888d6441]::util::run_in_thread_with_globals<rustc_interface[ea4bb220888d6441]::util::run_in_thread_pool_with_globals<rustc_interface[ea4bb220888d6441]::interface::run_compiler<(), rustc_driver_impl[9f43b67c13dcf142]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[6a8fd511579d4332]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x74c9caf2e2eb - std::sys::pal::unix::thread::Thread::new::thread_start::h7e071d267c3a6526
  34:     0x74c9c4ca370a - <unknown>
  35:     0x74c9c4d27aac - <unknown>
  36:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (1f76d219c 2025-04-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `move_into_fnmut`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0601.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by meithecatte**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/138961)*

Reference PR:

- https://github.com/rust-lang/reference/pull/1837

This PR has two goals:
- firstly, it fixes rust-lang/rust#137467. In order to do so, it needs to introduce a small, mostly theoretical breaking change surrounding the interaction of closure captures with matching against enums with uninhabited variants. Yes – to fix an ICE!
    - this also fixes rust-lang/rust#138973, a slightly different case with the same root cause.
    - likewise, fixes rust-lang/rust#140011.
- secondly, it fixes rust-lang/rust#137553, making the closure capturing rules consistent between `let` patterns and `match` patterns. This is new insta-stable behavior; crater has also picked up two instances of new borrowck errors being caused.

## Background

This change concerns how precise closure captures interact with patterns. As a little known feature, patterns that require inspecting only part of a value will only cause that part of the value to get captured:

```rust
fn main() {
    let mut a = (21, 37);
    // only captures a.0, writing to a.1 does not invalidate the closure
    let mut f = || {
        let (ref mut x, _) = a;
        *x = 42;
    };
    a.1 = 69;
    f();
}
```

I was not able to find any discussion of this behavior being introduced, or discussion of its edge-cases, but it is [documented in the Rust reference](https://doc.rust-lang.org/reference/types/closure.html#r-type.closure.capture.precision.wildcard).

The currently stable behavior is as follows:
- if any pattern contains a binding, the place it binds gets captured (implemented in current `walk_pat`)
- patterns in refutable positions (`match`, `if let`, `let ... else`, but not destructuring `let` or destructuring function parameters) get processed as follows (`maybe_read_scrutinee`):
    - if matching against the pattern will at any point require inspecting a discriminant, or it includes a variable binding not followed by an `@`-pattern, capture *the entire scrutinee* by reference

You will note that this behavior is quite weird and it's hard to imagine a sensible rationale for at least some of its aspects. It has the following issues:
- firstly, it assumes that matching against an irrefutable pattern cannot possibly require inspecting any discriminants. With or-patterns, this isn't true, and it is the cause of the rust-lang/rust#137467 ICE.
- secondly, the presence of an `@`-pattern doesn't really have any semantics by itself. This is the weird behavior tracked as rust-lang/rust#137553.
- thirdly, the behavior is different between pattern-matching done through `let` and pattern-matching done through `match` – which is a superficial syntactic difference

This PR aims to address all of the above issues. The new behavior is as follows:
- like before, if a pattern contains a binding, the place it binds gets captured as required by the binding mode
- if matching against the pattern requires inspecting a disciminant, the place whose discriminant needs to be inspected gets captured by reference

"requires inspecting a discriminant" is also used here to mean "compare something with a constant" and other such decisions. For types other than ADTs, the details are not interesting and aren't changing.

## The breaking change

During closure capture analysis, matching an `enum` against a constructor is considered to require inspecting a discriminant if the `enum` has more than one variant. Notably, this is the case even if all the other variants happen to be uninhabited. This is motivated by implementation difficulties involved in querying whether types are inhabited before we're done with type inference – without moving mountains to make it happen, you hit this assert: https://github.com/rust-lang/rust/blob/43f0014ef0f242418674f49052ed39b70f73bc1c/compiler/rustc_middle/src/ty/inhabitedness/mod.rs#L121

> Note from the future: there are also good language design reasons for this change, see #146803, #147722, and `feature(never_patterns)`

Now, because the previous implementation did not concern itself with capturing the discriminants for irrefutable patterns at all (even ones with refutable sub-patterns!), this is a breaking change – the following example, adapted from the testsuite, compiles on current stable, but will not compile once this PR gets merged:

```rust
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Void {}

pub fn main() {
    let mut r = Result::<Void, (u32, u32)>::Err((0, 0));
    let mut f = || {
        let Err((ref mut a, _)) = r;
        *a = 1;
    };
    let mut g = || {
    //~^ ERROR: cannot borrow `r` as mutable more than once at a time
        let Err((_, ref mut b)) = r;
        *b = 2;
    };
    f();
    g();
    assert_eq!(r, Err((1, 2)));
}
```

## Is the breaking change necessary?

One other option would be to double down, and introduce a set of syntactic rules for determining whether a sub-pattern is in an irrefutable position, instead of querying the types and checking how many variants there are.

This option is very much not ideal, because there just isn't a good operational semantics model for something like that – at the very least, it's the kind of thing that would lead to hard, uncomfortable T-lang/T-opsem concerns popping up down the road.

Moreover, **this would not eliminate the breaking change,** and merely limit it to more contrived examples, such as

```rust
let ((true, Err((ref mut a, _, _))) | (false, Err((_, ref mut a, _)))) = x;
```

In this example, the `Err`s would not be considered in an irrefutable position, because they are part of an or-pattern. However, current stable would treat this just like a tuple `(bool, (T, U, _))`.

## The new insta-stable behavior

If a pattern in a `match` expression or similar has parts it will never read, this part will not be captured anymore:

```rust
fn main() {
    let mut a = (21, 37);
    // now only captures a.0, instead of the whole a
    let mut f = || {
        match a {
            (ref mut x, _) => *x = 42,
        }
    };
    a.1 = 69;
    f();
}
```

Note that this behavior was pretty much already present, but only accessible with this One Weird Trick™:

```rust
fn main() {
    let mut a = (21, 37);
    // both stable and this PR only capture a.0, because of the no-op @-pattern
    let mut f = || {
        match a {
            (ref mut x @ _, _) => *x = 42,
        }
    };
    a.1 = 69;
    f();
}
```

## The second, more practically-relevant breaking change

After running crater, we have discovered that the aforementioned insta-stable behavior, where sometimes closures will now capture less, can also manifest as a breaking change. This is because it is possible that previously a closure would capture an entire struct by-move, and now it'll start capturing only part of it – some by move, and some by reference. This then causes the closure to have a more restrictive lifetime than it did previously.

See:
- https://github.com/rust-lang/rust/pull/138961#issuecomment-2761888557
- https://github.com/EC-labs/cec-assignment/pull/1
- https://github.com/tryandromeda/andromeda/pull/43

> Another note from the future: such changes in what part of a value get captured can also lead to `Drop` getting run at a different point in the lifecycle of the program, see https://github.com/rust-lang/rust/issues/147722#issuecomment-3675790923

## Implementation notes

The PR has two main commits:
- "ExprUseVisitor: properly report discriminant reads" makes `walk_pat` perform all necessary capturing. This is the part that fixes rust-lang/rust#137467.
- "ExprUseVisitor: remove maybe_read_scrutinee" removes the unnecessary "capture the entire scrutinee" behavior, fixing rust-lang/rust#137553.

The new logic stops making the distinction between one particular example that used to work, and another ICE, tracked as rust-lang/rust#119786. As this requires an unstable feature, I am leaving this as future work.

### CODE REVIEW

**Comment by meithecatte** [comment]
Nadrieril suggested that this should be resolved through a breaking change – updated the PR description accordingly.

@rustbot label +needs-crater

r? @Nadrieril

**Comment by meithecatte** [comment]
@compiler-errors You've requested that the fix for #137553 land in a separate PR. However, ironically, the breaking changes are actually required by #137467 and not #137553. Do you think the removal of the now-obsolete `maybe_read_scrutinee` should happen in a separate PR, or should I do it here so that it also benefits from the crater run?

**Comment by compiler-errors** [comment]
We can crater both together if you think they're not worth separating. I was just trying to accelerate landing the parts that are obviously-not-breaking but it's up to you if you think that effort is worth it or if you're willing to be patient about waiting for the breaking parts (and FCP, etc).

@bors try

**Comment by meithecatte** [comment]
> We can crater both together if you think they're not worth separating. I was just trying to accelerate landing the parts that are obviously-not-breaking but it's up to you if you think that effort is worth it or if you're willing to be patient about waiting for the breaking parts (and FCP, etc).

That's the thing – one part is a breaking change, the other introduces insta-stable new behavior. There's no easily mergeable part to this.

**Comment by compiler-errors** [comment]
could we give this a less weird pr title pls 💀

@bors try

**Comment by meithecatte** [comment]
> could we give this a less weird pr title pls 💀

Sure thing. I also updated the PR description to describe both changes. I want to add a section on what exactly the insta-stable behavior will be, but I realized that I haven't added a test for that. Should I hold off on pushing that to not break the bors try and crater?

**Comment by compiler-errors** [comment]
Once bors is done with the try build then you can push, no need to wait until crater is done.

**Comment by meithecatte** [comment]
@compiler-errors Looks like I have to re-bless the MIR output for a test you added in #138514. It seems fine to me but you might want to take a look as well.

**Comment by compiler-errors** [comment]
next time please wait until bors is done building the try build artifacts, lol

tests do not affect try builds

**Comment by compiler-errors** [comment]
to avoid needing to wait 2 more hours for *another* try build, i'm just going to rip out the commit hashes from the last try build to manually invoke crater. for later:

```
craterbot run mode=check-only start=master#19cab6b878ab18dce4816d85ac52b317214c485f end=try#630b4e873619ba7f396880337285be042468cd7f
```

**Comment by meithecatte** [comment]
> next time please wait until bors is done building the try build artifacts, lol

ah okay. that's... somewhat surprising. lost cause by now I assume? or should I forcepush the previous commit back in? :see_no_evil:

**Comment by compiler-errors** [comment]
i'll manually invoke crater since it won't be able to pick up that the existing try build (https://github.com/rust-lang-ci/rust/actions/runs/14092448811/job/39472281414) is still running.

**Comment by meithecatte** [comment]
@compiler-errors the build has finished btw

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only start=master#19cab6b878ab18dce4816d85ac52b317214c485f end=try#630b4e873619ba7f396880337285be042468cd7f

**Comment by compiler-errors** [comment]
@craterbot retry-report

**Comment by meithecatte** [comment]
Looking at the crater failures, we have random C code failing to compile, some kind of chess program that already ICEs on current nightly but OOMed on the last crater run, and an instance where matches capturing less actually introduce a breaking change:

```rust
// minimized example
enum Enum {
    Variant {
        a: u32,
        b: String,
    }
}

fn f(x: Enum) -> impl FnOnce() {
    || {
        match x {
            Enum::Variant { a, b } => {},
        }
    }
}
```

this used to capture `borrow_imm(x)`, `copy(x.a)`, `consume(x.b)`, which got merged by `compute_min_captures` into `consume(x)`.

but now it only does `copy(x.a)` and `consume(x.b)`, and since `copy(x.a)` is treated as `borrow_imm(x.a)`, this breaks the lifetimes.

I would argue that this counts as a bugfix: it only captures the entire thing by move because the compiler decided that the bindings actually constitute a discriminant read.

However, this does suggest that we might want to split the "remove `maybe_read_scrutinee` entirely" part into a separate PR... thoughts?

> Also, here's a link to the Zulip thread where we've been discussing this PR: [#t-compiler/help > upvar inference for patterns and InhabitedPredicate](https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp/topic/upvar.20inference.20for.20patterns.20and.20InhabitedPredicate)

**Comment by Nadrieril** [comment]
Dear @rust-lang/lang, this PR proposes a breaking change to the language to fix some bizarre edge cases around precise closure captures. Crater found a single breakage, in a GitHub project. WDYT?

**Comment by traviscross** [comment]
If we were to OK this, we'd end up asking for a PR to be made to the [affected project](https://github.com/tryandromeda/andromeda), particularly as it seems to be maintained.  Probably you'll want to go ahead and do this now in any case, as it will make the story a bit simpler when we pick this up.

**Comment by traviscross** [comment]
Fortunately also, the regression is in the `main.rs` file of a bin crate, so there won't be any dependent crates affected.

**Comment by lino-levan** [comment]
PR merged on our end. Thanks for letting us know.

File: tests/ui/closures/2229_closure_analysis/only-inhabited-variant-stable.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    };
+    let mut g = || {
+    //~^ ERROR: cannot borrow `r` as mutable more than once at a time
+        let Err((_, ref mut b)) = r;
+        *b = 2;
+    };
+    f();
+    g();
+    assert_eq!(r, Err((1, 2)));
+}
```
Comment (traviscross) [inline tests/ui/closures/2229_closure_analysis/only-inhabited-variant-stable.rs:23]: Maybe?:

```suggestion
enum Void {}

pub fn main() {
    let mut r = Result::<Void, (u32, u32)>::Err((0, 0));
    let mut f = || {
        let Err((ref mut a, _)) = r;
        *a = 1;
    };
    let mut g = || {
    //~^ ERROR: cannot borrow `r` as mutable more than once at a time
        let Err((_, ref mut b)) = r;
        *b = 2;
    };
    f();
    g();
    assert!(matches!(r, Err((1, 2))));
}
```

I like doing away with those derives if they're not part of the demonstration.

**Comment by traviscross** [comment]
> During closure capture analysis, matching an `enum` against a constructor is considered to require inspecting a discriminant if the `enum` has more than one variant. Notably, this is the case even if all the other variants happen to be uninhabited. This is motivated by implementation difficulties involved in querying whether types are inhabited before we're done with type inference...

I.e.:

```rust
enum Void {}

pub fn main() {
    let mut r = Result::<Void, (u32, u32)>::Err((0, 0));
    let mut f = || {
        let Err((ref mut a, _)) = r;
        *a = 1;
    };
    let mut g = || {
    //[stable]~^ OK
    //[post-pr]~^ ERROR: cannot borrow `r` as mutable more than once at a time
        let Err((_, ref mut b)) = r;
        *b = 2;
    };
    f();
    g();
    assert!(matches!(r, Err((1, 2))));
}
```

This is my only reservation about this, as this is a bit of a strange and unfortunate outcome as a language matter.  The story we want to tell about uninhabited types is that `Result<!, (u32, u32)>` should basically work like `(u32, u32)`, and it wouldn't in this case.

I believe you about the implementation difficulties.  It is a bit surprising, though, given that we need to know that `Void` is uninhabited to allow those irrefutable pattern matches.  Do we defer that check somehow to after type checking?  I'm curious if you could say more about that.

If it weren't for the fact that this kind of accidentally worked for other reasons, it'd be easy to say, "it's OK; we could always make this work later."  But it feels less ideal to say that when we're incurring breakage.

Other than this reservation, this all seems right to me.

**Comment by meithecatte** [comment]
> It is a bit surprising, though, given that we need to know that Void is uninhabited to allow those irrefutable pattern matches. Do we defer that check somehow to after type checking?

Well, as far as closure capture goes, we don't check this at all – we tacitly assume that matching against any pattern accepted for a `let` will not require matching the discriminant. And when this assumption gets invalidated, we ICE. Essentially, the pattern capture behavior for `let` was always broken – and the equivalent `match` never worked in this manner.

> (Is it possible to defer the check needed for this capture?)

I believe this is the only instance where we would need to inspect whether a type is uninhabited before type inference is done. The only way we could properly delay it would be to do minimal capture analysis as the very last step of type inference – and make sure that we still properly handle cases where this leads to a cycle.

> This is my only reservation about this, as this is a bit of a strange and unfortunate outcome as a language matter. The story we want to tell about uninhabited types is that `Result<!, (u32, u32)>` should basically work like `(u32, u32)`, and it wouldn't in this case.

Well, there's already the difference that you can't use the `x.0` syntax to access the fields of a `Result<!, (u32, u32)>`. I'd say that the never type here should affect layout and exhaustiveness checks, but otherwise behave like any other `Result<T, E>` – which is the direction this PR is going.

This is consistent with the interpretation that `feature(never_patterns)` is going for: that matching against a `Result<!, (u32, u32)>` like this is syntax sugar for a match with an `Ok(!)` pattern, which would semantically read the discriminant, and a field of type `!` in one of the branches, only at which point does the uninhabited branch evaporate in a puff of smoke.

> If it weren't for the fact that this kind of accidentally worked for other reasons, it'd be easy to say, "it's OK; we could always make this work later." But it feels less ideal to say that when we're incurring breakage.

Technically, this is true, but the fact that pattern-matching is included in precise captures isn't a very well-known feature in the first place, and Crater didn't find any concrete instance of this breakage. Currently, we let this through, at the cost of ICE-ing on perfectly reasonable code like in #137467.

**Comment by traviscross** [comment]
> This is consistent with the interpretation that `feature(never_patterns)` is going for: that matching against a `Result<!, (u32, u32)>` like this is syntax sugar for a match with an `Ok(!)` pattern, which would semantically read the discriminant, and a field of type `!` in one of the branches, only at which point does the uninhabited branch evaporate in a puff of smoke.

OK, I buy that.  Looks good to me then.  I propose we take the breakage and the new behavior as described.

@rfcbot fcp merge

**Comment by RalfJung** [comment]
This all makes sense to me at first sight, in particular the part about uninhabited variants in the last 2 comments. From a Miri perspective, we'll want to see a discriminant read at that point in the closure so that we can report UB as appropriate; this can't even work if the discriminant does not get captured in the first place. I'd definitely like to hear from @Nadrieril before we land this. :)

Would it be possible to have a Miri test like this? I'm thinking of a `repr(C)` enum with 2 inhabited and an uninhabited variant, and then capturing `&Enum` that points to something invalid (i.e., the uninhabited variant), and then a `let` pattern like `let (Var1 | Var2) = x;` or so... IIUC, this so far would not have captured (since it's a `let`). Now with this PR, calling the closure should cause UB due to the invalid enum (but there should be no UB before since Miri does not enforce validity behind references).

**Comment by meithecatte** [comment]
> Would it be possible to have a Miri test like this? I'm thinking of a `repr(C)` enum with 2 inhabited and an uninhabited variant, and then capturing `&Enum` that points to something invalid (i.e., the uninhabited variant), and then a `let` pattern like `let (Var1 | Var2) = x;` or so... IIUC, this so far would not have captured (since it's a `let`). Now with this PR, calling the closure should cause UB due to the invalid enum (but there should be no UB before since Miri does not enforce validity behind references).

This should pass, and I'll investigate creating a test like that. But do note that currently, the lowering actual MIR lowering code *does* check for inhabitedness, so a test with one inhabited variant, and one uninhabited one, would not pass, because the read of the discriminant would be skipped. To do this in an "honest" manner, we would want to also break compat outside of closures as well, and make the actual lowering perform a read in that case, bringing the semantics into a consistent state between the two.

**Comment by RalfJung** [comment]
Hm, I think we only skip the read in cases where it cannot fail since the place is by-val, or were there still some gaps in that? Though if let only does this for by-val cases we will not be able to do it in a closure either.

I though there should be a test here that is UB with this PR but was accepted before. But maybe not.

**Comment by meithecatte** [comment]
> Hm, I think we only skip the read in cases where it cannot fail since the place is by-val, or were there still some gaps in that? Though if let only does this for by-val cases we will not be able to do it in a closure either.

I think we're talking about a different check. See this part of the code, where if we're matching the only inhabited variant, we don't emit the `TestCase` that would read its discriminant into the decision tree.

https://github.com/rust-lang/rust/blob/7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad/compiler/rustc_mir_build/src/builder/matches/match_pair.rs#L269-L282

**Comment by RalfJung** [comment]
That's deep in the guts of pattern elaboration, I cannot follow that code or relate it to the MIR we generate.^^ I am entirely talking about what it looks like in MIR.

Though maybe I am entirely on the wrong train here. This PR does not change the MIR in the closure, does it? But it does mean more things get captured in some cases which should leave a trace in the MIR where the closure is constructed?

**Comment by meithecatte** [comment]
> This PR does not change the MIR in the closure, does it?

Pretty much. It only changes what gets captured into the closure, and by extension the exact place expressions MIR later uses to access these upvars.

> But it does mean more things get captured in some cases which should leave a trace in the MIR where the closure is constructed?

Yes, more things in some cases (#137467), less things in others (#137553).

> Though if let only does this for by-val cases we will not be able to do it in a closure either.

To the best of my knowledge, this PR makes `let` and `match` equivalent in terms of closure capture behavior.

> Hm, I think we only skip the read in cases where it cannot fail since the place is by-val, or were there still some gaps in that?

Okay, looks like I was not aware of some of the behavior here.

<details>
<summary>As it turns out, exhaustiveness only allows omitting the uninhabited branch when matching by value.</summary> 
I tried this test case:

```rust
enum Void {}

enum Foo {
    A(u32),
    B(Void),
}

fn check_foo(x: &Foo) {
    match x {
        Foo::A(x) => {},
    }
}
```

and got this error, which I haven't seen before:

```
error[E0004]: non-exhaustive patterns: `&Foo::B(_)` not covered
 --> patlowering.rs:9:11
  |
9 |     match x {
  |           ^ pattern `&Foo::B(_)` not covered
  |
note: `Foo` defined here
 --> patlowering.rs:3:6
  |
3 | enum Foo {
  |      ^^^
4 |     A(u32),
5 |     B(Void),
  |     - not covered
  = note: the matched value is of type `&Foo`
  = note: `Void` is uninhabited but is not being matched by value, so a wildcard `_` is required
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
  |
10~         Foo::A(x) => {},
11~         &Foo::B(_) => todo!(),
  |
```

</details>

This means that we only get to the code I linked when the uninhabitedness doesn't require reading through any references.

In this case, I will try to add a testcase like you described. Off the top of your head, are you aware of any similar tests that create enum values with invalid discriminants? I'm not sure how I'd go about doing that, I must admit unsafe code is not my strong suit.

**Comment by RalfJung** [comment]
> To the best of my knowledge, this PR makes let and match equivalent in terms of closure capture behavior.

Right, but are they equivalent in terms of the MIR that is generated for the pattern?

> In this case, I will try to add a testcase like you described. Off the top of your head, are you aware of any similar tests that create enum values with invalid discriminants? I'm not sure how I'd go about doing that, I must admit unsafe code is not my strong suit.

For this case I'd do something like:
```rust
#![feature(never_type)]
#[repr(C)]
enum E {
  V1, // discrminant: 0
  V2, // 1
  V3(!), // 2
}

fn main() {
    assert_eq!(std::mem::size_of::<E>(), 4);
    
    let val = 2u32;
    let ptr = (&raw const val).cast::<E>();
    // This is invalid:
    unsafe { ptr.read() };
}
```

**Comment by meithecatte** [comment]
BTW, playing around with this, I've realized that due to the very nature of the PR, it changes when some dereferences happen, and because of that, this passes Miri on nightly but not on my branch:

```rust
use std::ptr;

fn f(x: &&(u32, u32)) {
    || match x {
        (y, _) => {},
    };
}

fn main() {
    let r = unsafe {
        let x: (u32, u32) = (1, 2);
        &* &raw const x
    };

    f(&r);
}
```

I assume that this is not an actually important difference, because the UB was there either way, and just wasn't detected by Miri before.

**Comment by meithecatte** [comment]
(rebased onto latest `master`, now that #139086 got merged)

**Comment by RalfJung** [comment]
That's a nice testcase, please add that.

> I assume that this is not an actually important difference, because the UB was there either way, and just wasn't detected by Miri before.

On which basis was there UB before?
The closure never gets executed, so it's not at all clear to me that this code should be UB. I guess it is due to the reference that is created when building the closure environment?

**Comment by meithecatte** [comment]
> On which basis was there UB before?

My mental model is that merely touching a reference, in any way, such as moving it into a closure, must mean that the memory it points to is valid. Is that not an accurate mental model?

**Comment by RalfJung** [comment]
That's generally correct, but references likely are not required to be recursively valid (the docs just forbid this so that we have time to make up our minds). An `&&(u32, u32)` where the inner reference is dangling is hence okay to touch and move around.

**Comment by Nadrieril** [comment]
> It is a bit surprising, though, given that we need to know that Void is uninhabited to allow those irrefutable pattern matches. Do we defer that check somehow to after type checking?

Yep, match exhaustiveness runs after type checking and is the one running the `is_unihabited` queries. Type checking itself doesn't know about inhabitedness; it's a property we only compute on fully-inferred types.

> As it turns out, exhaustiveness only allows omitting the uninhabited branch when matching by value.

Yep, for more power, activate the `exhaustive_patterns` feature. I have on my TODO list to RFC something sensible in that direction (along with never patterns).

> > To the best of my knowledge, this PR makes let and match equivalent in terms of closure capture behavior.

> Right, but are they equivalent in terms of the MIR that is generated for the pattern?

We call the same pattern-lowering code for both, so if the upvars are the same the MIR should be the same. I'm not totally confident tho.

> Hm, I think we only skip the read in cases where it cannot fail since the place is by-val, or were there still some gaps in that? 

There are gaps because MIR lowering does not emit discriminant reads for single-nonempty-variant-enums. That's the bit of code that @meithecatte linked to. See point below.

> I'd definitely like to hear from @Nadrieril before we land this. :)

I think this boils down to: does matching on a single-nonempty-variant enums need a discriminant read? In both closure capture (what this PR is about) and borrow-checking (see example below), today's Rust seems to say "no". 
```rust
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Void {}

pub fn main() {
    let mut r = Result::<Void, (u32, u32)>::Err((0, 0));

    // This is allowed by the borrow-checker. If `Result<Void, (bool, bool)>` had a discriminant and stored it in a niche
    // then reading the discriminant while one of the fields is mutably borrowed would be UB. Hence this being
    // accepted (plus the fact that we reserve the option to use niches) implies that this pattern-match does not
    // do a discriminant read.
    let Err((ref mut a, _)) = r;
    let Err((_, ref mut b)) = r;
    *a = 1;
    *b = 2;

    assert_eq!(r, Err((1, 2)));
}
```

I don't believe that fact was ever decided explicitly. See [a relevant t-opsem discussion](https://github.com/rust-lang/unsafe-code-guidelines/issues/443).

Of note is that truly-single-variant enums do skip the discriminant read:
```rust
enum Foo {
    Single(u32, u32),
}
pub fn main() {
    let mut r = Foo::Single(0, 0);
    let Foo::Single(ref mut a, _) = r;
    let Foo::Single(_, ref mut b) = r;
    *a = 1;
    *b = 2;
}
```
This is likely what motivated implementors of the `exhaustive_patterns` feature to do the same for single-nonempty-variant enums.

However, MIR is polymorphic: `Option::is_none` for unknown `T` has a discriminant read, so I'd want it to still be there if `T` is `Void`. That just seems to make everything easier. I am in favor of deciding that matching on an enum with !=1 variants causes a discriminant read.

As Ralf said, this implies the closure should capture the discriminant so we can read it, i.e. what this here PR does. The alternative would be an implicit discriminant read when we construct the closure, which goes against the desire for patterns to be explicit about accesses.

This also implies that the borrow-checking example above should error. I'm ok with this but we'd need a second crater run for that one.

**Comment by meithecatte** [comment]
> Hm, I think we only skip the read in cases where it cannot fail since the place is by-val, or were there still some gaps in that?

I have performed some more testing, and this isn't actually the case. For example, this code passes miri on current master (as well as on top of #139042, FWIW):

```rust
#![feature(never_type)]

#[repr(C)]
#[allow(dead_code)]
enum E {
  V1, // discriminant: 0
  V2(!), // 1
}

fn main() {
    assert_eq!(std::mem::size_of::<E>(), 4);

    let val = 1u32;
    let ptr = (&raw const val).cast::<E>();
    let r = unsafe { &*ptr };
    match r { //~ we'd probably want ERROR: read discriminant of an uninhabited enum variant
        E::V1 => {}
        E::V2(_) => {}
    }
}
```

This is due to the code within `match_pair.rs` I linked above, which means that the match tree construction and MIR lowering considers the first arm to always match regardless of the discriminant, i.e.

```rust
    match r {
        _ => {}
        E::V2(_) => {} // dead arm, only false edges lead to it (for borrowck)
    }
```

This means that swapping the order of the arms means that the UB is again detected.

This relates to the same semantics question of "does matching against the only inhabited variant of an enum involve reading its discriminant". Looks like the answer we want to be going for is "yes". From the way you're talking about it, it kinda feels like there may have been prior discussion of this, specifically considering the by-value details you're mentioning? If so, could you link me to it?

Certainly, this PR means that the closure capture code will consider the answer to be "yes". Do we want to make sure that the match lowering code also does that? If so, should that be part of the same PR & FCP, or a separate one? Seems to me like it'd be useful to get consensus on both parts of the issue at the same time, and perhaps double-check the crater, but OTOH not sure if it makes sense as part of the same PR.

**Comment by Nadrieril** [comment]
Great minds think alike, we reached basically the same conclusion :D

**Comment by meithecatte** [comment]
> In both closure capture (what this PR is about) and borrow-checking (see example below), today's Rust seems to say "no".

Not exactly. `match`ing within a closure will consider the discriminant read to be happening even today, it is only `let` destructuring that is weird due to its current ICE-prone implementation.

**Comment by Nadrieril** [comment]
> Not exactly. matching within a closure will consider the discriminant read to be happening even today, it is only let destructuring that is weird due to its current ICE-prone implementation.

Yeah I agree impl-wise; I meant that in terms of code accepted, the `let` behavior can only be sound if there isn't a discriminant read. Which suggests that whoever implemented the `exhaustive_patterns` feature intended for that to be true.

**Comment by traviscross** [comment]
> Do we want to make sure that the match lowering code also does that? If so, should that be part of the same PR & FCP, or a separate one? Seems to me like it'd be useful to get consensus on both parts of the issue at the same time...

We have a meeting coming up today where we might get to this, so if you're able to write it up for us with respect to the various implications here, we can consider it together.

**Comment by meithecatte** [comment]
> We have a meeting coming up today where we might get to this, so if you're able to write it up for us with respect to the various implications here, we can consider it together.

Sure thing. Let me know if you'd like me to also join the meeting to clarify things if necessary – I do have a lot of the context paged in already.

Pretty sure the main points were all mentioned already, but to summarize, there are three related language changes with various degrees of "necessary":
1. The first part of this PR, which fixes #137467. See the "breaking change" section of the PR description, this comment: https://github.com/rust-lang/rust/pull/138961#issuecomment-2764891804 and my response: https://github.com/rust-lang/rust/pull/138961#issuecomment-2765174836
    - Since this fixes a pretty important ICE, I'm assuming this is desirable no matter what.
    - Crater picked up no instances of this actually breaking anything.
2. Then, we have the second part of this PR, which fixes #137553. This means that the semantics for `let $pat = $expr` and `match $expr { $pat => ... }` will become the same w.r.t. closure captures, and that `match` will go from "most real-life patterns capture the entire scrutinee" to "most real-life patterns will capture only the relevant part". This is described in the "insta-stable behavior" section of the PR description, but as it turns out, can also be a breaking change as discovered by crater and described in https://github.com/rust-lang/rust/pull/138961#issuecomment-2761888557
    - Crater picked up one instance of this actually breaking someone's project, a PR fixing this has already been merged.
    - Not doing this change would leave some technical debt in the closure capture analysis, warts in the semantics and the weird behavior where `x` and `x @ _` do different things.
3. Now, the third change, which hasn't been implemented yet but should be straight-forward, is when you go from asking "do we need to capture the discriminant when in a closure", to the more general "is the discriminant being read". For consistency, we might want to make sure that matching against an `enum { A, B(!) }` requires reading its discriminant. As far as I know, this also goes in the direction of the interpretation that `feature(never_patterns)` is going for. Changing this affects borrowck, as in https://github.com/rust-lang/rust/pull/138961#issuecomment-2770913923, as well as the presence of UB, as in https://github.com/rust-lang/rust/pull/138961#issuecomment-2770914863.
    - This is asking questions about things that probably barely anybody would write, so I feel safe conjecturing that Crater will likely not pick up many instances of this being a breaking change.
    - In my opinion, making this change makes perfect sense, and will be necessitated by other attempts to clean up the semantics, sooner or later.
    - However, to me it does feel like much more of an edgecase than the other two things.

Once we agree on whether it's a desired change, I could also use some feedback on whether this should all be one PR.

**Comment by RalfJung** [comment]
> I am in favor of deciding that matching on an enum with !=1 variants causes a discriminant read.

Yeah, agreed.

(I wonder if we should just always do this even for enums that have exactly one variant, but don't have a set opinion on that case currently.)

**Comment by RalfJung** [comment]
> Certainly, this PR means that the closure capture code will consider the answer to be "yes". Do we want to make sure that the match lowering code also does that?

Is it necessary for closure capturing to reimplement the same logic here? That seems like a hazard. Or am I misunderstanding something?

**Comment by meithecatte** [comment]
> Is it necessary for closure capturing to reimplement the same logic here? That seems like a hazard. Or am I misunderstanding something?

Yes, I'm not particularly happy with the way this logic is duplicated between upvar inference and MIR lowering. Not only are they two separate implementations, they work on different IRs: upvar inference does its work on HIR, while MIR lowering and exhaustiveness checking work on THIR.

Unfortunately I don't see a good way of unifying this, because upvar inference is part of type inference, and THIR requires typechecking to be finished.

The best way I see is having a comment going "be careful! these two things need to have matching behavior!"...

**Comment by RalfJung** [comment]
> The best way I see is having a comment going "be careful! these two things need to have matching behavior!"...

Let's do at least that then. :)

If you have a good idea of what the risks are when they diverge, that might be good to document as well. I assume one direction is "fine" but the other is "bad" (the two directions being which check accepts more than the other).

**Comment by Nadrieril** [comment]
My understanding is: if MIR lowering uses more precise places than upvar capture all is good, and if it uses less precise places then we get ICEs (but not unsoundness).

**Comment by meithecatte** [comment]
> My understanding is: if MIR lowering uses more precise places than upvar capture all is good, and if it uses less precise places then we get ICEs (but not unsoundness).

That is also my understanding.

> > The best way I see is having a comment going "be careful! these two things need to have matching behavior!"...
> 
> Let's do at least that then. :)

I already added such a comment to upvar capture: https://github.com/rust-lang/rust/pull/138961/files#diff-945cde608e29cea98a59d63e87bcac74d84a2390a1cfa71b1c89d08007789850R817-R829

I could add one to MIR lowering, but I'm not sure where the best place to put it would be, since it's quite a big chunk of code. Maybe rustc-dev-guide?

**Comment by Nadrieril** [comment]
The correct place to add a comment in MIR lowering is here: https://github.com/rust-lang/rust/blob/f5c510260bef89f7799d0b8e1aa70d7d7925cd99/compiler/rustc_mir_build/src/builder/matches/match_pair.rs?plain=1#L322

If closure capture is correct, then `place` should always be `Some` unless `pattern.kind` is `Or`.

**Comment by Nadrieril** [comment]
In fact the other calls to `{try_}to_place` in match MIR lowering are potential places where we mess things up. E.g. [here](https://github.com/rust-lang/rust/blob/f5c510260bef89f7799d0b8e1aa70d7d7925cd99/compiler/rustc_mir_build/src/builder/matches/mod.rs?plain=1#L415), we want to add a `PlaceMention` to the scrutinee which we can't do if it's not captured, could that have weird consequences maybe?

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by meithecatte** [comment]
> In fact the other calls to `{try_}to_place` in match MIR lowering are potential places where we mess things up. E.g. [here](https://github.com/rust-lang/rust/blob/f5c510260bef89f7799d0b8e1aa70d7d7925cd99/compiler/rustc_mir_build/src/builder/matches/mod.rs?plain=1#L415), we want to add a `PlaceMention` to the scrutinee which we can't do if it's not captured, could that have weird consequences maybe?

Ask and ye shall receive ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=37f349c94108e2df7b019559386eef11)):

```rust
use std::mem::transmute;

fn main() {
    let r: &&u32 = unsafe {
        let x = 42;
        transmute(&&x)
    };

    // no UB detected
    let f = || { let _ = **r; };
    f();
    
    // UB due to the inner deref
    let _ = **r;
}
```

(behavior is the same between nightly and this PR)

**Comment by RalfJung** [comment]
Nice example. :D  Could you file an issue in the Miri repo?

**Comment by meithecatte** [comment]
Filed https://github.com/rust-lang/miri/issues/4258

**Comment by traviscross** [comment]
FCP is complete, and there are conflicts to resolve.

@rustbot author

**Comment by meithecatte** [comment]
I've resolved the conflicts. The Miri tests requested above are still pending.

**Comment by jackh726** [comment]
cc @rust-lang/types

I'm not sure if we own closure capture analyses or not (one could also argue it's more @rust-lang/opsem), but it's sufficiently grey that I think a ping here is enough.

**Comment by meithecatte** [comment]
@RalfJung I've added the tests you suggested, could you take a look?

@rustbot ready

File: src/tools/miri/tests/fail/upvars/deref-in-pattern.rs
Comment (RalfJung) [inline src/tools/miri/tests/fail/upvars/deref-in-pattern.rs:1]: Please rename the folder to `closures` or so, "upvars" is a very much rustc-internal jargon.

File: src/tools/miri/tests/fail/upvars/deref-in-pattern.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// This test serves to document the change in semantics introduced by #138961.
+//
+// A corollary of partial-pattern.rs: while the tuple access showcases the
+// utility, it is actually the dereference performed by the pattern that
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/upvars/deref-in-pattern.rs:4]: The utility of what?

File: src/tools/miri/tests/fail/upvars/partial-pattern.rs [hunk 3]
```diff
@@ -0,0 +1,27 @@
+// This test serves to document the change in semantics introduced by #138961.
+//
+// Previously, the closure would capture the entirety of x, and access *(*x).0
+// when called. Now, the closure only captures *(*x).0, which means that
+// a &*(*x).0 reborrow happens when the closure is constructed.
+//
+// Hence, if one of the references is dangling, this constitutes newly introduced UB
+// in the case where the closure doesn't get called. This isn't a big deal,
+// because why opsem only now considers this to be UB, the unsafe code
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/upvars/partial-pattern.rs:9]:
```suggestion
// because while opsem only now considers this to be UB, the unsafe code
```

File: src/tools/miri/tests/fail/upvars/uninhabited-variant.rs [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+}
+
+fn main() {
+    assert_eq!(std::mem::size_of::<E>(), 4);
+
+    let val = 2u32;
+    let ptr = (&raw const val).cast::<E>();
+    let r = unsafe { &*ptr };
+    let f = || {
+        // After #138961, constructing the closure performs a reborrow of r.
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/upvars/uninhabited-variant.rs:20]: Since these are issue numbers in the rustc repo, but these tests will be mirrored to the Miri repo, please use full URLs instead of just issue numbers to avoid any ambiguity.

**Review by RalfJung — COMMENTED** [review]
Miri tests LGTM, I just have minor nits.

I don't have a full picture of what the intended semantics are here though, I just checked the tests for internal consistency. Is there someone tracking the bigger picture here? @Nadrieril ? @compiler-errors ?

File: src/tools/miri/tests/fail/upvars/deref-in-pattern.rs (hunk 2 above)
Comment (meithecatte) [reply src/tools/miri/tests/fail/upvars/deref-in-pattern.rs:4]: The utility of the semantics, i.e. why the closure might want to capture the deref'ed value.

**Comment by lcnr** [comment]
> cc @rust-lang/types
> 
> I'm not sure if we own closure capture analyses or not (one could also argue it's more @rust-lang/opsem), but it's sufficiently grey that I think a ping here is enough.

Agree, I want to get pinged in changes to closure captures and pattern handling, but don't think it's Types-y enough to require us to also sign off the FCP :+1:

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 5]
```diff
@@ -1011,13 +1025,71 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
...
+                }
+                PatKind::Expr(_) | PatKind::Range(..) => {
+                    // When matching against a literal or range, we need to
+                    // borrow the place to compare it against the pattern.
+                    //
+                    // FIXME: What if the type being matched only has one
+                    // possible value?
+                    // FIXME: What if the range is the full range of the type
+                    // and doesn't actually require a discriminant read?
+                    read_discriminant();
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs:933]: FWIW I personally consider `..` patterns like if they were `0|1|2|...`, in other words I agree theyre morally a read. Maybe this will get specified precisely one day.

Comment (theemathas) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs:933]: `..` patterns don't exist. I assume this is talking about stuff like  `0u8..=255u8`

**Comment by traviscross** [comment]
@rustbot labels +S-waiting-on-documentation

The Reference has a fairly detailed section on [closure capturing](https://doc.rust-lang.org/nightly/reference/types/closure.html#capture-precision), and the PR description mentions the relevant behavior is documented there.  @meithecatte, what do we need to add or change in the Reference?  You'll probably want to put up the PR for this.

We'll want to hold off merging this until the Reference update is ready and reviewed, if one is needed.

cc @ehuss

**Review by Nadrieril — APPROVED** [review]
I approve impl-wise and intent-wise. There are pending test suggestions and docs, did I miss anything else?

**Comment by Nadrieril** [comment]
> I don't have a full picture of what the intended semantics are here though, I just checked the tests for internal consistency. Is there someone tracking the bigger picture here?

To the best of my capacity, I am. This is aligned with my working model for pattern opsem, including the never patterns discussion.

**Comment by RalfJung** [comment]
Great, thanks for confirming :)

**Comment by meithecatte** [comment]
- Rebased onto current master and resolved conflicts.
- Applied suggestions from review.
- Opened a corresponding PR to the Rust Reference: rust-lang/reference#1837

One unresolved question remains, which is when exactly a slice pattern should constitute a discriminant read. The currently implemented semantics are also documented in the Reference PR — @Nadrieril thoughts on how this looks?

Is there something I've missed?

@rustbot ready

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs (hunk 5 above)
Comment (meithecatte) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs]: I've replaced the FIXME by a comment explaining that this case should read the discriminant regardless.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 6]
```diff
@@ -921,28 +814,20 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
...
+    ///
+    /// However, it is okay to approximate it here by doing *more* accesses than
+    /// the actual MIR builder will, which is useful when some checks are too
+    /// cumbersome to perform here. For example, if after typeck it becomes
+    /// clear that only one variant of an enum is inhabited, and therefore a
+    /// read of the discriminant is not necessary, `walk_pat` will have
+    /// over-approximated the necessary upvar capture granularity.
+    ///
+    /// Do note that discrepancies like these do still create obscure corners
+    /// in the semantics of the language, and should be avoided if possible.
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs:830]: I don't necessarily agree. The rust specification should say what discriminant reads happen or not, which determines what's being captured. The fact that we skip discriminant reads for e.g. an enum with only one non-empty variant can be seen as an optimization that should be 1. justified by the spec, 2. invisible semantically.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 7]
```diff
@@ -1888,6 +1834,15 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
...
     }
 
+    /// Checks whether a type has multiple variants, and therefore, whether a
+    /// read of the discriminant might be necessary. Note that the actual MIR
+    /// builder code does a more specific check, filtering out variants that
+    /// happen to be uninhabited.
+    ///
+    /// Here, we cannot perform such an accurate checks, because querying
+    /// whether a type is inhabited requires that it has been fully inferred,
+    /// which cannot be guaranteed at this point.
```
Comment (Nadrieril) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs:1844]: I think this is misleadingly framed: it is a language decision not to do this check, which while informed by the technical difficulty of being accurate is not only because of that.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 8]
```diff
@@ -1014,13 +900,73 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
...
+                PatKind::Expr(_) | PatKind::Range(..) => {
+                    // When matching against a literal or range, we need to
+                    // borrow the place to compare it against the pattern.
+                    //
+                    // Note that we do this read even if the range matches all
+                    // possible values, such as 0..=u8::MAX. This is because
+                    // we don't want to depend on consteval here.
+                    //
+                    // FIXME: What if the type being matched only has one
+                    // possible value?
```
[the remark this answers is not in the document]
Comment (meithecatte) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs:937]: My understanding is that a pattern like `UNIT`, with `const UNIT: () = ();` would trigger this case, though I haven't tested this.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 9]
```diff
@@ -1011,13 +1025,71 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
...
+                    }
+                }
+                PatKind::Slice(lhs, wild, rhs) => {
+                    // We don't need to test the length if the pattern is `[..]`
+                    if matches!((lhs, wild, rhs), (&[], Some(_), &[]))
+                        // Arrays have a statically known size, so
+                        // there is no need to read their length
+                        || place.place.ty().peel_refs().is_array()
+                    {
+                        // No read necessary
```
[the remark this answers is not in the document]
Comment (meithecatte) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs:952]: I have created #141825.

**Comment by meithecatte** [comment]
So, is this blocked on the reference PR getting merged?

**Comment by traviscross** [comment]
You'll probably want to reply to the other review comments from @Nadrieril above.  Other than that, and @Nadrieril confirming this is good to go, the approval on the Reference PR would be the final gate.  That's on our radar, and we'll get that done.  The Reference PR you submitted is really high quality, by the way.  Thanks for that.

**Comment by meithecatte** [comment]
Yes, I'll get to the review comments, I just want to reduce the number of times I page in all the context of this PR again.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs (hunk 6 above)
Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs:830]: It is however not invisible semantically, not even statically (https://github.com/rust-lang/rust/issues/146590), so in that case you're right.

**Comment by Nadrieril** [comment]
Re-reading them they're all nits, I'm ok with the PR as it is. I've pinged ppl on the Reference side so we can get this moving.

**Comment by traviscross** [comment]
In reviewing the Reference PR https://github.com/rust-lang/reference/pull/1837, @ehuss and I found that this PR seems to change whether the pointee or the pointer is captured in the following program that matches a slice against a slice pattern:

```rust
#![feature(rustc_attrs, stmt_expr_attributes)]
#![allow(internal_features)]

fn main() {
    let x: &mut [u8] = &mut [];
    let c = #[rustc_capture_analysis] || match x {
        [] => (),
        _ => (),
    };
    c();
}
```

On nightly, the analysis returned is:

```
error: First Pass analysis includes:
 --> src/main.rs:6:39
  |
6 |       let c = #[rustc_capture_analysis] || match x {
  |  _______________________________________^
7 | |         [] => (),
8 | |         _ => (),
9 | |     };
  | |_____^
  |
note: Capturing x[] -> Immutable
 --> src/main.rs:6:48
  |
6 |     let c = #[rustc_capture_analysis] || match x {
  |                                                ^

error: Min Capture analysis includes:
 --> src/main.rs:6:39
  |
6 |       let c = #[rustc_capture_analysis] || match x {
  |  _______________________________________^
7 | |         [] => (),
8 | |         _ => (),
9 | |     };
  | |_____^
  |
note: Min Capture x[] -> Immutable
 --> src/main.rs:6:48
  |
6 |     let c = #[rustc_capture_analysis] || match x {
  |                                                ^
```

That is, it seems to capture the *pointer* (analysis of the produce MIR also confirms this).

On the PR branch (rebased to master), the analysis returned is:

```
error: First Pass analysis includes:
 --> src/main.rs:6:39
  |
6 |       let c = #[rustc_capture_analysis] || match x {
  |  _______________________________________^
7 | |         [] => (),
8 | |         _ => (),
9 | |     };
  | |_____^
  |
note: Capturing x[Deref] -> Immutable
 --> src/main.rs:6:48
  |
6 |     let c = #[rustc_capture_analysis] || match x {
  |                                                ^

error: Min Capture analysis includes:
 --> src/main.rs:6:39
  |
6 |       let c = #[rustc_capture_analysis] || match x {
  |  _______________________________________^
7 | |         [] => (),
8 | |         _ => (),
9 | |     };
  | |_____^
  |
note: Min Capture x[Deref] -> Immutable
 --> src/main.rs:6:48
  |
6 |     let c = #[rustc_capture_analysis] || match x {
  |                                                ^
```

That is, it seems to capture the *pointee* (again, this is also seen in the MIR).

Over on https://github.com/rust-lang/reference/pull/1837, it was mentioned that this might have something to do with [`truncate_capture_for_optimization`](https://doc.rust-lang.org/1.90.0/nightly-rustc/rustc_hir_typeck/upvar/fn.truncate_capture_for_optimization.html), but in building rustc with logging, @ehuss reports not seeing that function hit in this case (either on nightly or on the branch).

What's the story on this?  (And, e.g., what code in the diff affects this?)

From a language perspective, it seems maybe a bit more intuitive to capture the wide pointer rather than the pointee, as that's where the read is happening to get the length.  Is this difference observable in any way in the language?

**Comment by traviscross** [comment]
This branch rebases cleanly.  Pushed the rebase.  It's been awhile; let's recheck the crater run to be sure we won't be surprised in the beta crater runs.

@bors2 try

**Comment by traviscross** [comment]
The problem with clippy here seems real.  On the branch, for this program,

```rust
fn issue15102() {
    let values = [None, Some(3)];
    let has_even = values.iter().find(|v| matches!(v, Some(x) if x % 2 == 0)).is_some();
}

fn main() {}
```

clippy produces:

```
warning: called `is_some()` after searching an `Iterator` with `find`
 --> src/main.rs:3:34
  |
3 |     let has_even = values.iter().find(|v| matches!(v, Some(x) if x % 2 == 0)).is_some();
  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `any(|v| matches!(v, *v if x % 2 == 0))`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some
  = note: `#[warn(clippy::search_is_some)]` on by default
```

(Scroll right and look at the suggestion.)

**Comment by meithecatte** [comment]
To expand on the above, the change in how slice lengths get captured is consistent with the entire premise of the PR:
 - current nightly handles the pattern matching in such a way, that any discriminant-like things being inspected result in *the whole scrutinee of the match expression* being captured.
 - to make things work in a sensible way, and to fix the edgecases that are definitely bugs, this PR introduces more precision (into `match`es. for `let`s, the precision is already there, in a way. this weird distinction between `match`es and `lets` is, IIRC, going away as well)

To illustrate, consider the following example:

```rust
#![feature(rustc_attrs, stmt_expr_attributes)]
#![allow(internal_features)]

fn main() {
    let x: (&mut [u8], u32) = (&mut [], 0);
    let c = #[rustc_capture_analysis] || match x {
        ([], _) => (),
        _ => (),
    };
    c();
}
```

On nightly, this results in:

```
error: First Pass analysis includes:
note: Capturing x[] -> Immutable
error: Min Capture analysis includes:
note: Min Capture x[] -> Immutable
```

while on this PR's branch, the result is:

```
error: First Pass analysis includes:
note: Capturing x[(0, 0),Deref] -> Immutable
error: Min Capture analysis includes:
note: Min Capture x[(0, 0),Deref] -> Immutable
```

Thus, the change is not in how this particular pattern gets understood by the capture analysis, but in how the already documented changes in the common codepaths handle the results.

The question, then, is whether the length part of the slice should be captured as `x`, or `x[Deref]`. I'm definitely not an expert on this. I'd even say it's not really my department. As I remarked in my previous comment, observing the current compiler behavior suggests it's semantically part of the value behind the pointer, even though, at the ABI level, it's part of the pointer metadata.

After thinking about it for a while, this makes sense – after all, consider the `unsized_locals` case, when there is no pointer to speak of.

> Is this difference observable in any way in the language?

I was able to come up with the following example, where it does:

```rust
#![allow(unused_assignments)]
#![allow(dead_code)]

fn f(mut x: &mut [u8]) -> impl FnOnce() + '_ {
    let g = || {
        match x {
            [] => (),
            _ => (),
        }
    };
    x = &mut [];
    g
}
```

Nightly rejects this, my branch accepts it. I'll try to also find a similar case that doesn't involve slice patterns, and add both as a testcase.

I don't think the interactions of this PR with dereferencing were discussed much so far, should we have T-lang at least take a look at this?

**Comment by traviscross** [comment]
Thanks for those details and that analysis.  In particular, it leads me to consider this variant of the example,

```rust
fn f<'l: 's, 's>(x: &'s mut &'l [u8]) -> impl Fn() + 'l {
    || match *x {
        &[] => (),
        _ => (),
    }
}
```

which is an error on nightly but works with this PR.  That makes it more clear to me why capturing `**x` -- i.e. treating the read of the length semantically as a read of the pointee -- is likely correct.  Notably, e.g., this works today:

```rust
fn f<'l: 's, 's>(x: &'s mut &'l [u8]) -> impl Fn() + 'l {
    || match **x {
        [] => (),
        _ => (),
    }
}
```

It's rather surprising these would be different.  It's good that this PR, then, will make these consistent.

> I don't think the interactions of this PR with dereferencing were discussed much so far, should we have T-lang at least take a look at this?

This is why I was asking, was to see whether there was an aspect to this stabilization that we hadn't reviewed.  Though I think it'll be an easy call for us, this is indeed such an aspect, so we'll discuss for visibility.

@rustbot labels +I-lang-nominated +P-lang-drag-1 +I-lang-easy-decision

I'll be curious to hear from @nikomatsakis, in particular, more about the history on this.

**Comment by meithecatte** [comment]
The clippy CI failure is due to the fact that the code in question (`clippy_utils::sugg::DerefDelegate`) is assuming that the `PlaceWithHirId` provided by the `ExprUseVisitor` will always refer to the `HirId` of an expression. However, in this particular case, it is a pattern.

A similar issue can already be reproduced on nightly:

```rust
fn main() {
    let values = [None, Some(3)];
    let has_even = values.iter().find(|v| { let &&v = v; true }).is_some();
    println!("{has_even}");
}
```

(with clippy suggesting the malformed `any(|v| { let &*v = v; true })`)

**Comment by traviscross** [comment]
See the build failure in:

- https://github.com/rust-lang/rust/pull/138961#issuecomment-3419070979

@meithecatte gives an initial analysis in,

- https://github.com/rust-lang/rust/pull/138961#issuecomment-3419826354

and a further analysis in:

- https://github.com/rust-lang/rust/pull/138961#issuecomment-3468774826

**Comment by traviscross** [comment]
> Since the issue is caused by how patterns are now handled and that's more than just a single edge case that breaks I would suggest just moving the lint into the nursery and commenting out that test case with a note.

@Jarcho, do you want @meithecatte to put up a separate PR for that, or how would that best be handled?

**Comment by Manishearth** [comment]
> It is just the suggestion being broken, specifically for the search_is_some lint (as it seems that it's the only one that needs to do this sort of ref-stripping?). 

Thanks. That's less problematic to break.

We already have a path forward here so you don't need to but for future reference it is additionally helpful to describe what the cases are for a broken suggestion. It's not always easy to predict that from the code.

**Comment by traviscross** [comment]
@craterbot check

**Comment by theemathas** [comment]
These assertions pass both in nightly and with this PR. Is this intended?

```rust
fn main() {
    let array = [0i32, 0i32];
    let array_closure = move || {
        let [_a, _] = array;
    };
    let tuple = (0i32, 0i32);
    let tuple_closure = move || {
        let (_a, _) = tuple;
    };
    assert_eq!(8, size_of_val(&array_closure));
    assert_eq!(4, size_of_val(&tuple_closure));
}
```

**Comment by traviscross** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-138961-1/retry-regressed-list.txt

**Comment by traviscross** [comment]
Looking at it, the build OOMed in the baseline run, which is why it wasn't reported.

If we could, let's please make a PR to the [affected project](https://github.com/EC-labs/cec-assignment) before merging this.

When we originally FCPed this, we had accepted a one-crate breakage, so this one-crate breakage seems in line with that.

**Comment by ehuss** [comment]
I think it got confused because the concern was added after the FCP completed (https://github.com/rust-lang/rfcbot-rs/issues/302).

**Comment by meithecatte** [comment]
Commented out the rust-analyzer tests as per https://github.com/rust-lang/rust-analyzer/issues/21274. Also rebased the branch again, so the CI on the PR branch should run the rust-analyzer tests as well (turns out the CI changes to start testing rust-analyzer on rustc CI landed exactly one day after I last rebased :P).

**Review by ChayimFriedman2 — APPROVED** [review]
LGTM for the rust-analyzer changes

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/138961/68f11a11b666b36137374b6e54fc0d013a3b26cf..011c5ed7ba0d20dec130609abafa7537d5ea199e)*

File: src/tools/clippy/clippy_lints/src/methods/mod.rs [hunk 10]
```diff
@@ -889,7 +889,7 @@ declare_clippy_lint! {
     /// ```
     #[clippy::version = "pre 1.29.0"]
     pub SEARCH_IS_SOME,
-    complexity,
+    nursery,
     "using an iterator or string search followed by `is_some()` or `is_none()`, which is more succinctly expressed as a call to `any()` or `contains()` (with negation in case of `is_none()`)"
 }
```
Comment (matthiaskrgr) [inline src/tools/clippy/clippy_lints/src/methods/mod.rs:895]: huh, was this signed off by the clippy team? 
cc  @rust-lang/clippy 

I grepped through the comments and didn't find any discussion around this

Comment (traviscross) [reply src/tools/clippy/clippy_lints/src/methods/mod.rs:895]: It was.  See https://github.com/rust-lang/rust/pull/138961#issuecomment-3481998039 and https://github.com/rust-lang/rust-clippy/issues/16086.

Comment (matthiaskrgr) [reply src/tools/clippy/clippy_lints/src/methods/mod.rs:895]: ah good, thanks!

File: src/tools/miri/tests/fail/closures/uninhabited-variant.rs
Comment (RalfJung) [inline src/tools/miri/tests/fail/closures/uninhabited-variant.rs:1]: The PR description sounds like "enums with multiple variants where only one of them is inhabited" are an especially interesting case. But that is not the case covered by this test. Is that deliberate?

Comment (meithecatte) [reply src/tools/miri/tests/fail/closures/uninhabited-variant.rs:1]: This is likely because I discovered this weird behavior: https://github.com/rust-lang/rust/pull/138961#issuecomment-2770914863

Somehow that particular test case doesn't seem to have made it into the repo. I suppose my thinking might've been that if the test was added, it be asserting something like "yes this is not what we want it to do, but right now it does this"... I could still add a test like that, though

Comment (RalfJung) [reply src/tools/miri/tests/fail/closures/uninhabited-variant.rs:1]: Ah... yeah [the test that I expected](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=7cf876ec5352da127f9c0af02df5a8a3) doesn't actually work, we don't raise any UB.^^ And as you say that's not even about the closure, it's the same with a regular `match`.

We should have an issue for that somewhere... I made one at https://github.com/rust-lang/miri/issues/4778. But maybe there already is one in the rustc repo?
