### PR TITLE
AsyncDrop trait without sync Drop generates an error

### LINKED ISSUE #140696: async drop not work without sync drop
I tried this code:

```rust
#![feature(async_drop)]

use std::future::AsyncDrop;
use std::pin::Pin;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let _st = St;
}

struct St;

impl AsyncDrop for St {
    async fn drop(self: Pin<&mut Self>) {
        println!("123");
    }
}
```

I expected to see this happen:

should print `123`

Instead, this happened:

nothing

if try this codes

```rust
#![feature(async_drop)]

use std::future::AsyncDrop;
use std::pin::Pin;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let _st = St;
}

struct St;

impl Drop for St {
    fn drop(&mut self) {
        println!("456")
    }
}

impl AsyncDrop for St {
    async fn drop(self: Pin<&mut Self>) {
        println!("123");
    }
}
```

it print `123`

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (2e6882ac5 2025-05-05)
```

### PR DESCRIPTION
**Pull request by azhogin**
When type implements `AsyncDrop` trait, it must also implement sync `Drop` trait to be used in sync context and unwinds.
This PR adds error generation in such a case.

Fixes: rust-lang/rust#140696

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 1]
```diff
@@ -113,7 +113,17 @@ pub fn provide(providers: &mut Providers) {
 }
 
 fn adt_destructor(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Option<ty::Destructor> {
-    tcx.calculate_dtor(def_id, always_applicable::check_drop_impl)
+    let dtor = tcx.calculate_dtor(def_id, always_applicable::check_drop_impl);
+    if dtor.is_none() && tcx.features().async_drop() {
+        if let Some(async_dtor) = adt_async_destructor(tcx, def_id) {
+            // When type has AsyncDrop impl, but doesn't have Drop impl, generate error
+            let span = tcx.def_span(def_id.to_def_id());
+            let impl_span = tcx.def_span(async_dtor.impl_did);
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/check/mod.rs]: Make this the main span. Unsure if pointing to the type is useful, we could just leave it off entirely

File: compiler/rustc_hir_analysis/messages.ftl [hunk 2]
```diff
@@ -46,6 +46,10 @@ hir_analysis_associated_type_trait_uninferred_generic_params = cannot use the {$
 
 hir_analysis_associated_type_trait_uninferred_generic_params_multipart_suggestion = use a fully qualified path with explicit lifetimes
 
+hir_analysis_async_drop_without_sync_drop = `AsyncDrop` impl without `Drop` impl
+    .help = type implementing `AsyncDrop` trait must also implement `Drop` trait to be used in sync context and unwinds
```
Comment (petrochenkov) [inline compiler/rustc_hir_analysis/messages.ftl:50]: Which "sync contexts" are currently remaining besides unwinds?
Ideally async drop should just always be called, but while it's not it would be good to list the unimplemented cases somewhere.

Comment (azhogin) [reply compiler/rustc_hir_analysis/messages.ftl:50]: `Sync context` - any sync function, where `AsyncDrop` type is dropped inside.
`fn foo() { _ = Dropee::new(); }`, where `Dropee` has only `AsyncDrop` trait without `Drop` trait.

Comment (petrochenkov) [reply compiler/rustc_hir_analysis/messages.ftl:50]: Ah, I thought cases like this are already reported as errors (they should be).

Comment (oli-obk) [reply compiler/rustc_hir_analysis/messages.ftl:50]: Yea that's an alternative to this PR (or that allows reverting this PR): error at use sites of sync drop of types that have no `Drop` impl but an `AsyncDrop` impl. This has some fun implications though, as we'd need to make sure that `Copy` and `AsyncDrop` also need to be mutually exclusive, just like `Copy` and `Drop` are. Or more generally: any logic checking for `Drop` needs to also check for `AsyncDrop` and handle that.

So it may be better long term to merge various things like `adt_destructor` and `adt_async_destructor` to only return a single `Option` with an enum inside for either an async or a sync variant, making it easier not to forget to check both together. There are probably many other functions that need similar treatment.

Comment (azhogin) [reply compiler/rustc_hir_analysis/messages.ftl:50]: Well, error at use sites of sync drop may help only after implementing async-drop support for unwinds. Otherwise, we still need both traits.
