### PR TITLE
Fix the start/end byte positions in the compiler JSON output

### LINKED ISSUE #65029: libsyntax JSON output bytes counts ignore CRLF normalization
Recently there was a change in rustc to normalize newlines (CRLF -> LF) early during processing (#62948). This caused a change in the JSON output offsets. While the line/column values were unaffected (since they do not include the newlines in the counts), the `byte_start`/`byte_end` values were affected as they are calculated from the spans that use post-normalization positions.

As a result, the `byte_start`/`byte_end` values cannot be used to index the actual bytes of the original file, if the original file content was affected by the CRLF normalization. This is most evident in rustfix on Windows.

The original discussion is in the rustfix issue at rust-lang-nursery/rustfix#176

### PR DESCRIPTION
**Pull request by Rantanen**
Track the changes made during normalization in the `SourceFile` and use this information to correct the `start_byte` and `end_byte` fields in the JSON output.

This should ensure the start/end byte fields can be used to index the original file, even if Rust normalized the source code for parsing purposes. Both CRLF to LF and BOM removal are handled with this one.

The rough plan was discussed with @matklad in rust-lang-nursery/rustfix#176 - although I ended up going with `u32` offset tracking so I wouldn't need to deal with `u32 + i32` arithmetics when applying the offset to the span byte positions.

Fixes #65029

### CODE REVIEW

**Comment by Rantanen** [comment]
I added the `normalized_pos` field in `SourceFile` next to the existing position based bits (`multibyte_chars` and `non_narrow_chars`) as it felt conceptually similar to those fields. Not sure if I should have added it as the last field for chronological reasons.

This got a bit more confusing when implementing `encode`/`decode` for the type as there I didn't want to change the existing field indices (not sure if there's some compatibility requirements with those functions), so there I added the `normalized_pos` as the last field in field id order.

(I also managed to sneak in a typo with my last refactoring that fails the build, I'll be rebasing this in a moment once my build goes through.)

**Comment by Rantanen** [comment]
Fixed couple of naming issues and one spaces-within-parens violation. I _think_ those were all of them. As far as I'm concerned, I think the code could be good to go. The compiler might disagree, my test run is still in progress - wanted to get the style issues pushed early so they wouldn't distract too much in the review.

File: src/libsyntax_pos/lib.rs [hunk 1]
```diff
@@ -1224,18 +1241,27 @@ impl SourceFile {
...
+    normalize_newlines(src, &mut normalized_pos);
+    normalized_pos
+}
+
 /// Removes UTF-8 BOM, if any.
-fn remove_bom(src: &mut String) {
+fn remove_bom(src: &mut String, normalized_pos: &mut Vec<NormalizedPos>) {
     if src.starts_with("\u{feff}") {
         src.drain(..3);
+        normalized_pos.push(NormalizedPos { pos: BytePos(0), diff: 2 });
```
Comment (matklad) [inline src/libsyntax_pos/lib.rs]: Hm, we drain 3 bytes, so this should be `diff: 3`?

File: src/libsyntax_pos/lib.rs [hunk 2]
```diff
@@ -1258,6 +1286,12 @@ fn normalize_newlines(src: &mut String) {
         if tail.len() == gap_len {
             break;
         }
+        last_diff += 1;
+        cursor += idx - gap_len;
+        normalized_pos.push(NormalizedPos {
+            pos: BytePos::from_usize(cursor),
+            diff: last_diff
```
Comment (matklad) [inline src/libsyntax_pos/lib.rs]: `last_diff` and `gap_len` vary exactly the same, so let's do `diff: gap_len + original_diff` instead of maintaining an extra induction variable

File: src/libsyntax/json.rs [hunk 3]
```diff
@@ -330,10 +333,24 @@ impl DiagnosticSpan {
             })
         });
 
+        let file_np = &start.file.normalized_pos;
+        let np_start_diff = match file_np.binary_search_by(
+                            |np| np.pos.cmp(&span.lo())) {
+            Ok(i) => file_np[i].diff,
+            Err(i) if i == 0 => 0,
+            Err(i) => file_np[i-1].diff,
+        };
```
Comment (matklad) [inline src/libsyntax/json.rs]: Let's move this binary search to the `SourceFile`:

```rust
fn original_relative_byte_pos(&self, pos: BytePos) -> BytePos
```

And lets also move `- self.start_pos` bit in there, as normalized absolute positions do not make sense.

File: src/libsyntax/json/tests.rs [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+        SpanTestData {
+            byte_start: 8,
+            byte_end: 16,
+            line_start: 2,
+            column_start: 5,
+            line_end: 3,
+            column_end: 3,
+        }
+    )
+}
```
Comment (matklad) [inline src/libsyntax/json/tests.rs]: I am not sure, but my gut feeling is that unit-tests that require context setup like `with_default_globals` are a liability long term, as they depend too much on the current architecture. For this reason, I think it's best to write an integration ui test here, like `ui/json-short.stderr`, but with some actual error and a file which starts with a BOM and contains `\r\n`.

Comment (Rantanen) [reply src/libsyntax/json/tests.rs]: `src/libsyntax/tests.rs` already have a pile of tests with `with_default_globals` so I just adapted it from there. Personally I'd love to avoid it - but it seemed like `Arc` and/or `Mutex` did not work without it.

What I wanted to really avoid was relying on CRLFs being maintained in the files, but I just noted that there's already precedent for this in the form of `lexer-crlf-line-endings-string-literal-doc-comment.rs` that includes CRLF and gets special handling in `.gitattributes` to mark it as non-text to avoid git from normalizing the linebreaks.

I'll see if I can remove the `with_default_globals` from these tests _and_ I'll add an integration ui test. I felt that with these libsyntax unit tests it was easier to test for strict offsets (ie. spans right before, right at and right after the linebreak).

**Comment by Rantanen** [comment]
I'll also try to remember run the libsyntax_pos unit tests this time. Unfortunately UDP tests are failing on my machine so running the full test suite is not possible for me. :|

File: src/libsyntax/json/tests.rs (hunk 4 above)
Comment (Rantanen) [reply src/libsyntax/json/tests.rs]: No idea why I got the impression the default globals had something to do with Arc/Mutex. The tests are panicking within syntax_pos that.

I'd still leave these in for now since the same `with_default_globals` is already used in `libsyntax/tests.rs` and I still feel they assert in more controlled manner. I've added a ui test for them as well though.

Just to confirm, the byte positions should be start inclusive, end exclusive? As in...

```
     v <- span 0..1, bytes 3..4
<BOM>foo bar baz
         ^^^ <- span 4..7, bytes 7..10
```

**Comment by Rantanen** [comment]
Also found a way to run the tidy tests. All the relevant tests passed on my machine, so I think this is good to go now from my end as long as I didn't screw things over in rebase and it's okay to leave the `with_default_globals` unit tests in for now.

File: src/libsyntax/json/tests.rs [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+            false
+        );
+
+        let span = Span::with_root_ctxt(BytePos(span.0), BytePos(span.1));
+        let handler = Handler::with_emitter(true, None, Box::new(je));
+        handler.span_err(span, "foo");
+
+        let bytes = output.lock().unwrap();
+        let actual_output = str::from_utf8(&bytes).unwrap();
+        let actual_output : TestData = decode(actual_output).unwrap();
```
Comment (matklad) [inline src/libsyntax/json/tests.rs]:
```suggestion
        let actual_output: TestData = decode(actual_output).unwrap();
```

In general, feel free to just run rustfmt on the new files, we have rustfmt.toml in the root of the repo

File: src/libsyntax/json/tests.rs [hunk 6]
```diff
@@ -0,0 +1,190 @@
...
+
+        println!("expected output:\n------\n{:#?}------", expected_output);
+        println!("actual output:\n------\n{:#?}------", actual_output);
```
Comment (matklad) [inline src/libsyntax/json/tests.rs]: I am not sure if it's considered good to leave `println`s in the tests. Perhaps this can be moved into the `assert!` call?

```
assert_eq!(expected_output, actual_output, 
"expected output:\n------\n{:#?}------
actual output:\n------\n{:#?}------",
expected_output, actual_output
)
```

File: src/libsyntax/json/tests.rs (hunk 4 above)
Comment (matklad) [reply src/libsyntax/json/tests.rs]: >Just to confirm, the byte positions should be start inclusive, end exclusive?

Yes

File: src/librustc/ich/impls_syntax.rs [hunk 7]
```diff
@@ -481,6 +488,18 @@ fn stable_non_narrow_char(swc: ::syntax_pos::NonNarrowChar,
...
 
+fn stable_normalized_pos(np: ::syntax_pos::NormalizedPos,
+                         source_file_start: ::syntax_pos::BytePos)
+                         -> (u32, u32) {
+    let ::syntax_pos::NormalizedPos {
+        pos,
+        diff
+    } = np;
+
+    (pos.0 - source_file_start.0, diff as u32)
```
Comment (matklad) [inline src/librustc/ich/impls_syntax.rs]:
```suggestion
    (pos.0 - source_file_start.0, diff)
```

**Review by matklad — COMMENTED** [review]
LGTM, just a couple of nits left

File: src/libsyntax/json/tests.rs (hunk 6 above)
Comment (Rantanen) [reply src/libsyntax/json/tests.rs]: Shouldn't `assert_eq!` alone do the expected vs actual printout? The current implementation is adapted from `libsyntax/tests.rs` - where `assert!` is used over `assert_eq!`. I'm guessing this might have something to do with `assert_eq!`'s handling of multi-line text.

... although I have no idea where the `{:#?}` format string came from.

I'll move the output to the assert macro, but I'll experiment a bit with `assert!` vs `assert_eq!` to and `{}` vs `{:?}` to see what gives the best output.

**Comment by matklad** [comment]
@bors r+

Thanks!

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65199#issuecomment-539518997, @bors r-

**Comment by Rantanen** [comment]
How can I reproduce that build on my own? The normal `./x.py build` didn't do it and given the issue wasn't caught in the PR build, I'm guessing the `-aux` has something special going on with it.

On the other hand, I might have found the root cause: The `normalized_pos` in the `SourceFile` holds indexes relative to the file - not relative to the `start_pos`, which probably results in the `imported_source_files` overflowing the subtraction (the only place where I've introduced `BytePos - BytePos`):

https://github.com/rust-lang/rust/blob/bbf262d9fcf6e54a26268214ed2c967d4218d3a4/src/librustc_metadata/decoder.rs#L1353-L1355

I managed to write a test that failed due to this root cause, but the failure was due to wrong byte positions. I haven't figured out how to exercise the `imported_source_files` function in the unit tests. I believe I'd need to make that function process a `SourceFile` that has `start_pos > 0` and the first `normalized_pos.pos == 0`.

Also I didn't see a backtrace in that build log. Is there one visible somewhere?

**Comment by matklad** [comment]
Ah, so `original_relative_byte_pos` is also super wrong, because it binary searches in a relative array using absolute positions? And we haven't noticed this, because we only test with one file?

I think a good test would be just extending that json test to more than one file. 

As for the fix, I suggest switching to absolute offsets, to match other tables. 

I also wonder if it makes sense, in another PR, switch all tables to relative indexing, to simplify the save/restore thing...

**Comment by Rantanen** [comment]
Yeah. I added the multifile test to try pinning down the crash and that exposed the issue in `original_relative_byte_pos`. I fixed this by turning the positions absolute.

I've been trying to verify that this also fixes the crash, but for that I'd need a way to reproduce that crash first, which is what I've been struggling with.

**Comment by Rantanen** [comment]
I pushed the fix to the offsets based on `start_pos`. Still couldn't reproduce the original issue so can't guarantee this fixes that one.

Also since I couldn't `mod json-bom-and-crlf-multifile-aux` in the new UI test, I had to deviate from the usual JSON-test naming and I used underscores in the aux file (`json_bom_and_crlf_multifile_aux`) - if there's a better option, I'll gladly change that.

(Also rebased on master while trying to reproduce the original so I left it there.)

Also I'm getting really confused by the tests now. The above build failure is due to compiletest not stripping BOM and only reading lines that start with `//`. This (kind of) makes sense. However now that I tried to ensure the multifile variant succeeds, I have huge trouble running those tests without them being ignored...

**Comment by Rantanen** [comment]
I guess the ignored tests are a caching issue. Compiletest ignores tests that it figures haven't changed and tests that have multiple files only consider the timestamps (I guess) of the primary file so that changes to the secondary files do not trigger a re-test.

In any case, while checking if Compiletest has some sort of directive to inform it about other files, I encountered the `#[path = "..."] mod ...` syntax so I put that into use in the multifile test, allowing the conventional `json-...-...-...rs` hyphenated file names over the `json_..._..._...rs` underscored ones.

(What does the `// build-fail` directive do? I stole that off some existing JSON tests without really understanding it - but given the BOM-issue, it should have been ignored as well, but I didn't encounter any related issues back then.)

**Comment by matklad** [comment]
Let's squash the commits so that git history is not confusing about relative/absolute offsets?

r=me with a squash

**Comment by pnkfelix** [comment]
T-compiler discussed. General consensus was that this is a long-standing problem, the fix here is largish, and therefore we'd prefer it to ride-the-trains.

declined for beta-backport.

**Comment by pnkfelix** [comment]
further discussion at T-compiler meeting led to conclusion that #65029 *is* serious (since rustfix is essentially broken on windows), but our preferred fix for the beta is to *revert* PR #62948 on the **beta branch alone**

**Comment by joelpalmer** [comment]
Ping from Triage: Hi @Rantanen, any updates?

**Comment by Rantanen** [comment]
Oh, sorry. I was under the impression this was good to go and people were just busy with other stuff that the review was taking a while.

> Let's squash the commits so that git history is not confusing about relative/absolute offsets?

I squashed the "Fix implementation" commits into the "Fix the start/end byte positions in the compiler JSON output", but still left the logically separate "Add unit tests" commits alone. Didn't know if the wish was to squash them all into one.

I've now done so. Do let me know if there's still something missing.

**Comment by matklad** [comment]
Sorry @Rantanen , I've missed force push, changes look good to me now!

bors r+

**Comment by Rantanen** [comment]
> iwr : The remote name could not be resolved: 'rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com'

I'm assuming this is a transient error. If it isn't and I need to do something about it, I'll need a bit more information than that. :)

**Comment by matklad** [comment]
hm, indeed seems spurious

@bors retry
