### PR TITLE
Fix handling of malicious Readers in read_to_end

### LINKED ISSUE #80894: Heap buffer overflow in `read_to_end_with_reservation()`
https://github.com/rust-lang/rust/blob/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/io/mod.rs#L358-L403

At line 393, the guard object's `.len` field is incremented by the value returned from a read implementation. If a questionable `Read` returns a value larger than the buffer size, it will take that value and set the length of the vector over the boundary.

This bug is reachable from `Read::read_to_end()` and `Read::read_to_string()`.

Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c0ea390522bda958c9d60ad47a42e296) that demonstrates the bug. It segfaults with `double free or corruption (out)`.

### PR DESCRIPTION
**Pull request by sfackler**
A malicious `Read` impl could return overly large values from `read`, which would result in the guard's drop impl setting the buffer's length to greater than its capacity! ~~To fix this, the drop impl now uses the safe `truncate` function instead of `set_len` which ensures that this will not happen. The result of calling the function will be nonsensical, but that's fine given the contract violation of the `Read` impl.~~

~~The `Guard` type is also used by `append_to_string` which does not pass untrusted values into the length field, so I've copied the guard type into each function and only modified the one used by `read_to_end`. We could just keep a single one and modify it, but it seems a bit cleaner to keep the guard code close to the functions and related specifically to them.~~

To fix this, we now assert that the returned length is not larger than the buffer passed to the method.

For reference, this bug has been present for ~2.5 years since 1.20: https://github.com/rust-lang/rust/commit/ecbb896b9eb2acadefde57be493e4298c1aa04a3.

Closes #80894.

### CODE REVIEW

File: library/std/src/io/mod.rs [hunk 1]
```diff
@@ -386,20 +398,12 @@ where
         }
 
         match r.read(&mut g.buf[g.len..]) {
-            Ok(0) => {
-                ret = Ok(g.len - start_len);
-                break;
-            }
+            Ok(0) => return Ok(g.len - start_len),
```
Comment (sfackler) [inline library/std/src/io/mod.rs:401]: This bit down here is just a drive-by cleanup to some weird control flow left after the commit mentioned in the PR description.

File: library/std/src/io/mod.rs [hunk 2]
```diff
@@ -386,20 +397,12 @@ where
...
             Ok(n) => g.len += n,
```
Comment (Qwaz) [inline library/std/src/io/mod.rs:401]: Could we check for an overflow here?

Comment (sfackler) [reply library/std/src/io/mod.rs:401]: We could, but I would rather keep the codepath oriented as much as possible towards non-malicious implementations. Overflow can only be caused by bogus return values, and just means that a nonsensical result will be returned.

Comment (Qwaz) [reply library/std/src/io/mod.rs:401]: Otherwise, malicious `Read` can shrink `g.len`, which can lead to a violation of `append_to_string()`'s second requirement. (and `append_to_string()` should probably be marked as an unsafe function)

https://github.com/rust-lang/rust/blob/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/io/mod.rs#L320-L329

Comment (Qwaz) [reply library/std/src/io/mod.rs:401]: This is the context:
https://github.com/rust-lang/rust/blob/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/io/mod.rs#L707-L718

Comment (sfackler) [reply library/std/src/io/mod.rs:401]: Ah right. We'll need to replace that with a checked_add then.

This kind of mess is one of the things that the ReadBuf proposal is designed to avoid, so things should get less janky when that's implemented.

**Comment by sfackler** [comment]
Updated to assert that the returned length is actually valid for the input buffer.

File: library/std/src/io/mod.rs [hunk 3]
```diff
@@ -386,20 +385,19 @@ where
...
-            Ok(0) => {
-                ret = Ok(g.len - start_len);
-                break;
+            Ok(0) => return Ok(g.len - start_len),
+            Ok(n) => {
+                // We can't let g.len overflow which would result in the vec shrinking when the function returns. In
+                // particular, that could break read_to_string if the shortened buffer doesn't end on a UTF-8 boundary.
+                // The minimal check would just be a checked_add, but this assert is a bit more precise and should be
+                // just about the same cost.
+                assert!(n <= g.buf.len() - g.len);
```
Comment (nagisa) [inline library/std/src/io/mod.rs:394]: Would it make sense to slice the slice that's been passed into the `read` call in the first place and then take its length? As in:

```rust
let buffer = &mut g.buf[g.len..];
match r.read(buffer) { 
    // ...
    Ok(n) => g.len += buffer[..n].len(),
}
```

or something along those lines? It has an added benefit of also detecting when returned `n` is greater than the length of the length of the buffer provided, and may result in slightly less code generated overall.

Comment (sfackler) [reply library/std/src/io/mod.rs:394]: This check already is looking for n being greater than the length of the buffer, but agreed that structuring it like that is a bit more clear. Will update later today.

**Comment by sfackler** [comment]
cc @Mark-Simulacrum not sure if you think we should to backport to beta?

**Comment by Mark-Simulacrum** [comment]
I think that seems fine - it's not really necessary IMO given this has been like this for a long time now, but giving it's a soundness fix seems appropriate. I'm going to unilaterally beta-accept but will wait till it lands on master before backporting.

**Comment by sfackler** [comment]
Yeah, makes sense to me, particularly since the patch is so small.
