### PR TITLE
Resolve long compile times when evaluating always valid constants

### LINKED ISSUE #67539: rustc endless loop on some constant casts
I bisected nightlies to figure out when my [pull request's tests](https://github.com/antifuchs/nonzero_ext/pull/7) started breaking on nightly. The following is the template `cargo-bisect-rustc` gave me.

# Regression found in the compiler

searched nightlies: from nightly-2019-10-01 to nightly-2019-12-22
regressed nightly: nightly-2019-11-20
searched commits: from https://github.com/rust-lang/rust/commit/3e525e3f6d9e85d54fa4c49b52df85aa0c990100 to https://github.com/rust-lang/rust/commit/618b01f9fa0a6b4e7e2ce5b3409abe104b80c4a8
regressed commit: https://github.com/rust-lang/rust/commit/d1da8023dafd3e277b5a4c5475aa2cb199a176b9
source code: https://github.com/antifuchs/nonzero_ext/pull/7

## Instructions

I tried the following on macOS and linux (in CI):

1. Check out the repo & branch of that pull request
2. Run `cargo +nightly test --test=compiletest` with a nightly version later than d1da8023dafd3e277b5a4c5475aa2cb199a176b9, that is >= `nightly-2019-11-20`

## Error

The compile test (provided by trybuild) does not terminate - rustc seems to be running forever, consuming 99% of my CPU all the while.

Since the instructions to repro are a bit convoluted (and massive), I'll try and boil down the repro case a little bit.

### PR DESCRIPTION
**Pull request by wesleywiser**
This extends the existing logic which skips validating every integer or
floating point number type to also skip validating empty structs because
they are also trivially valid.

Fixes #67539

r? @oli-obk 
cc @RalfJung @spastorino

### CODE REVIEW

File: src/librustc_mir/interpret/validity.rs [hunk 1]
```diff
@@ -580,10 +580,13 @@ impl<'rt, 'mir, 'tcx, M: Machine<'mir, 'tcx>> ValueVisitor<'mir, 'tcx, M>
             }
             ty::Array(tys, ..) | ty::Slice(tys)
                 if {
-                    // This optimization applies only for integer and floating point types
-                    // (i.e., types that can hold arbitrary bytes).
+                    // This optimization applies for types that can hold arbitrary bytes (such as
+                    // integer and floating point types) or for types that are empty (such as the
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs]: These types are not empty. `!` is an empty type, it has no inhabitants. We can certainly not skip validating those.

The types you are skipping here are inhabited ZST -- they are all equivalent to `()`, the unit type.

Comment (wesleywiser) [reply src/librustc_mir/interpret/validity.rs]: Yes, that's a much more accurate way of describing this. Thank you!

**Comment by wesleywiser** [comment]
Force pushed

File: src/librustc_mir/interpret/validity.rs [hunk 2]
```diff
@@ -580,10 +580,21 @@ impl<'rt, 'mir, 'tcx, M: Machine<'mir, 'tcx>> ValueVisitor<'mir, 'tcx, M>
...
             ty::Array(tys, ..) | ty::Slice(tys)
                 if {
-                    // This optimization applies only for integer and floating point types
-                    // (i.e., types that can hold arbitrary bytes).
+                    // This optimization applies for types that can hold arbitrary bytes (such as
+                    // integer and floating point types) or for inhabited Zero Sized Types (such as
+                    // the unit type and empty struct types).
                     match tys.kind {
                         ty::Int(..) | ty::Uint(..) | ty::Float(..) => true,
+                        ty::Tuple(t)
```
Comment (lzutao) [inline src/librustc_mir/interpret/validity.rs]:
```suggestion
                        ty::Tuple(t) => t.len() == 0 || self.ecx.layout_of(tys)?.size == Size::ZERO,
```

File: src/librustc_mir/interpret/validity.rs [hunk 3]
```diff
@@ -580,10 +580,21 @@ impl<'rt, 'mir, 'tcx, M: Machine<'mir, 'tcx>> ValueVisitor<'mir, 'tcx, M>
...
+                            if t.len() == 0 || self.ecx.layout_of(tys)?.size == Size::ZERO =>
+                        {
+                            true
+                        }
+                        ty::Adt(adt, _)
```
Comment (lzutao) [inline src/librustc_mir/interpret/validity.rs]:
```suggestion
                        ty::Adt(adt, _) => adt.is_struct() && self.ecx.layout_of(tys)?.size == Size::ZERO,
```

**Review by spastorino — APPROVED** [review]

File: src/librustc_mir/interpret/validity.rs (hunk 2 above)
Comment (wesleywiser) [reply src/librustc_mir/interpret/validity.rs]: Unfortunately, these will push the line over 100 characters.

File: src/librustc_mir/interpret/validity.rs [hunk 4]
```diff
@@ -580,10 +580,21 @@ impl<'rt, 'mir, 'tcx, M: Machine<'mir, 'tcx>> ValueVisitor<'mir, 'tcx, M>
...
                 if {
-                    // This optimization applies only for integer and floating point types
-                    // (i.e., types that can hold arbitrary bytes).
+                    // This optimization applies for types that can hold arbitrary bytes (such as
+                    // integer and floating point types) or for inhabited Zero Sized Types (such as
+                    // the unit type and empty struct types).
                     match tys.kind {
                         ty::Int(..) | ty::Uint(..) | ty::Float(..) => true,
+                        ty::Tuple(t)
+                            if t.len() == 0 || self.ecx.layout_of(tys)?.size == Size::ZERO =>
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs]: The `|| self.ecx.layout_of(tys)?.size == Size::ZERO` part is new, isn't it? And it is wrong: imagine `(!, !)`.

File: src/librustc_mir/interpret/validity.rs [hunk 5]
```diff
@@ -580,10 +580,21 @@ impl<'rt, 'mir, 'tcx, M: Machine<'mir, 'tcx>> ValueVisitor<'mir, 'tcx, M>
...
+                        {
+                            true
+                        }
+                        ty::Adt(adt, _)
+                            if adt.is_struct() && self.ecx.layout_of(tys)?.size == Size::ZERO =>
```
Comment (RalfJung) [inline src/librustc_mir/interpret/validity.rs]: Same, this is wrong. Please go back to what you did before.

Also please add a test making sure that we correctly validate things like `(!, !)` and `struct Empty(!);`.

File: src/librustc_mir/interpret/validity.rs (hunk 4 above)
Comment (wesleywiser) [reply src/librustc_mir/interpret/validity.rs]: Yes, @oli-obk wanted us to try to catch more complex cases that the prior code did not like `struct Foo(());`

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs]: I think what would work is

```rust
_ => {
    let layout = self.ecx.layout_of(tys)?;
    layout.size == Size::ZERO && !layout.is_uninhabited()
},
```

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs]: This will also work for any other kind of type, not just structs and tuples, but also

```rust
enum Foo {
   Bar
}
```

or `[T; 0]` or....

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs]: I am opposed to using `!layout.is_uninhabited()` as indicator for anything. `is_uninhabited` so far can conservatively return `false`, and I don't trust it to serve as a witness for inhabitedness.

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs]: While I do not think `is_uninhabited` is any kind of conservative, we can also use [is_ty_uninhabited_from_any_module](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.is_ty_uninhabited_from_any_module) which definitely is not conservative.

Comment (oli-obk) [reply src/librustc_mir/interpret/validity.rs]: Ok new idea that I think should alleviate your concerns:

Always validate at least one value, even for zsts. Then, if it's a zst, don't validate the other values. Since validating a zst array validates all zsts at the same location and a zst can never have a different value, we'd either error on *all* elements of the array or none. So checking one element for validity checks *all* elements.

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs]: I have not the slightest idea what `is_ty_uninhabited_from_any_module` does, it talks about forests...

It shouldn't be too hard to write a function that tests `is_inhabited`.

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs]: Also given that you seem to want to overdesign this, I think "inhabited ZST" is the wrong property. What would still not cover arrays of `(i32, ())`, for example. The right property is "accepts any initialized bit pattern", and we should probably just do a recursive descent over the layout to test for exactly that.

Comment (RalfJung) [reply src/librustc_mir/interpret/validity.rs]: Ah, but that's harder than I though due to padding... for `(u32, u16)` we don't want to check if the entire thing is initialized. So maybe that's not the right approach either.

**Comment by wesleywiser** [comment]
Force pushed. We're back to the original version with an added `//FIXME` to document that we could eventually handle more cases with a more complete analysis.

File: src/test/ui/consts/const-eval/validate_uninhabited_zsts.rs [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+}
+
+#[derive(Clone, Copy)]
+enum Empty { }
+
+#[warn(const_err)]
+const FOO: [Empty; 3] = [foo(); 3];
+
+#[warn(const_err)]
+const BAR: [Empty; 3] = [unsafe { std::mem::transmute(()) }; 3];
```
Comment (oli-obk) [inline src/test/ui/consts/const-eval/validate_uninhabited_zsts.rs]: side note: if you remove this constant and its use, you do get a hard error on the use of `FOO`, but `BAR` is what we are actually interested in testing here, because it causes validation to error instead of const eval.

**Comment by JohnTitor** [comment]
Seems failed in https://github.com/rust-lang/rust/pull/67704#issuecomment-569519337
@bors r-

**Comment by wesleywiser** [comment]
Ignored 32-bit platforms in the `huge-values` test I added. 

@bors r=oli-obk

**Comment by Mark-Simulacrum** [comment]
Stable nominating per https://github.com/rust-lang/rust/issues/68873.

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. stable-accepted.
