### PR TITLE
Suppress suggestions in derive macro

### LINKED ISSUE #118809: Compiler suggests invalid syntax for derive attribute
### Code

```Rust
#[derive(Debug, Deserialize)]
pub struct Build {
    #[serde(deserialize_with = "as_u64")]
    build: u32,
    product: Product,
    release: String,
    status: String,
    version: String,
}
```

### Current output

```Shell
error[E0308]: `?` operator has incompatible types
   --> downloader-api\src\lib.rs:140:17
    |
140 | #[derive(Debug, Deserialize)]
    |                 ^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note: `?` operator cannot convert from `u64` to `u32`
    = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
    |
140 | #[derive(Debug, Deserialize.try_into().unwrap())]
    |                            ++++++++++++++++++++
```

### Desired output

```Shell
Not sure what the correct output should be, but the current one suggests using an invalid syntax: `#[derive(Debug, Deserialize.try_into().unwrap())]`
If no useful "help" message can be provided in this context, the compiler should not suggest an invalid syntax in the "help" section.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

`rustc 1.76.0-nightly (9a66e4471 2023-11-19)`

### PR DESCRIPTION
**Pull request by long-long-float**
close #118809

I suppress warnings inside derive macros.

For example, the compiler emits following error by a program described in https://github.com/rust-lang/rust/issues/118809#issuecomment-1852256687 with a suggestion that indicates invalid syntax.

```
error[E0308]: `?` operator has incompatible types
 --> src/main.rs:3:17
  |
3 | #[derive(Debug, Deserialize)]
  |                 ^^^^^^^^^^^ expected `u32`, found `u64`
  |
  = note: `?` operator cannot convert from `u64` to `u32`
  = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
  |
3 | #[derive(Debug, Deserialize.try_into().unwrap())]
  |                            ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `serde_test` (bin "serde_test") due to 2 previous errors
```

In this PR, suggestions to cast are suppressed.

```
error[E0308]: `?` operator has incompatible types
 --> src/main.rs:3:17
  |
3 | #[derive(Debug, Deserialize)]
  |                 ^^^^^^^^^^^ expected `u32`, found `u64`
  |
  = note: `?` operator cannot convert from `u64` to `u32`
  = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `serde_test` (bin "serde_test") due to 2 previous errors
```

### CODE REVIEW

**Comment by Teapot4195** [comment]
LGTM (please don't take my word for it, I've only messed with this section of the compiler twice :D ).

I am qualified enough to ask for a squash though.

**Comment by long-long-float** [comment]
@Teapot4195 Thank you for comment. I squashed my commits.

**Comment by oli-obk** [comment]
I think we could check this directly in `push_suggestion`, so that no suggestions at all get reported on expansions of derives. Can you try that out and see if it works for you?

Adding a test for this is rather involved I'd presume, so manually testing it seems ok to me. But if you wanna try adding a test, we do have tests like [/home/ubuntu/rustc/rust10/tests/ui/proc-macro/derive-b.rs](https://github.com/rust-lang/rust/blob/master/tests/ui/proc-macro/derive-b.rs) so you can probably just copy one of these tests and their derive and create a derive that will always emit your diagnostic.

**Comment by long-long-float** [comment]
@oli-obk 
Thank you for your suggestion. I fixed to check in `push_suggestion`. 
I will try to add a test tomorrow.

**Comment by oli-obk** [comment]
Looks like rustc has tests 😆 try running `./x.py test --bless`, that should do it. Though potentially clippy is also affected, so you'd need to bless that, too

**Comment by oli-obk** [comment]
I think it's ok to lose this suggestion if it is still reported in another error in the same test. If that is not the case, then we need to figure out why this code is marked as expanded by a derive.

**Comment by oli-obk** [comment]
some tests are still failing

**Comment by oli-obk** [comment]
Ah yea, that makes sense :/ Not sure what the best way forward is.

I guess ideally we'd make the expansion somehow signal that it is referring to code copied from non-expanded code (in contrast to fully generated code, which is what the original issue was about).

That would require modifying our derives, and would not help for proc macro derives, for which I don't know how we can address it at this point.

**Comment by long-long-float** [comment]
@oli-obk 
If the suggest position(Span) is within the original code's `derive(...)` in the original code, it can be suppressed. However it is possible that there is a correct suggestion even within the `derive(...)`.

I think the essence of this problem is that it is necessary to determine whether a suggestion is grammatically correct or not. It would be impossible to determine that using only `in_derive_expansion`. Even the simple method of judging in the first `suggest_cast` may suppress a correct suggestion.

As a different approach, I have an idea to check if the code to which the suggestion is applied is grammatically correct, and suppress it if it is not. I would like to implement a PoC if I can afford it.

**Comment by oli-obk** [comment]
> As a different approach, I have an idea to check if the code to which the suggestion is applied is grammatically correct, and suppress it if it is not. I would like to implement a PoC if I can afford it.

that sound scary. I don't think we should go down that route (if I understand correctly what you're trying to do)



> I think the essence of this problem is that it is necessary to determine whether a suggestion is grammatically correct or not. It would be impossible to determine that using only `in_derive_expansion`. Even the simple method of judging in the first `suggest_cast` may suppress a correct suggestion.

that sounds doable. we store information about the derive's span in the expansion info. So we could check if it overlaps with that.

**Comment by long-long-float** [comment]
@oli-obk 
On second thought, your suggested method seems to solve the issue.
However, let me confirm that I did not fully understand how to implement it.

1. In derive exapantion, we store information about the derive's span in the expansion info `ExpnData` .
    
    ```rust
    // in ExpnData
    /// Whether this ExpnData is between an attribute `derive(...)`
    bool in_derive_attribute,
    ```
    
2. In `push_suggestion` , we check whether spans are in `derive(...)` using the information, not using `in_derive_expansion`
    - We just check `in_derive_attribute`
  
I don't (can't) take care about proc-macro now.

**Comment by oli-obk** [comment]
That sounds good to me. We can figure out proc macros later, doesn't have to be in this PR

**Comment by long-long-float** [comment]
Thank you! I will implement by this method.

**Comment by long-long-float** [comment]
@oli-obk 
I fixed `push_suggestion` and all tests are passed (no test results are changed). I solved the problem by simpler method using `ExpnData.call_site`. I noticed that `call_site` points inside `derive(...)` when `in_derive_expansion` is true.

BTW I want to add a UI test about this issue from [this code](https://github.com/rust-lang/rust/issues/118809#issuecomment-1852256687). However the code depends on `serde` crate. It may be difficult to add a test about the issue.

**Comment by oli-obk** [comment]
yea we can't use crates.io crates in tests. the only way a test can be added right now is via the following:

> we do have tests like [/home/ubuntu/rustc/rust10/tests/ui/proc-macro/derive-b.rs](https://github.com/rust-lang/rust/blob/master/tests/ui/proc-macro/derive-b.rs) so you can probably just copy one of these tests and their derive and create a derive that will always emit your diagnostic.

File: compiler/rustc_errors/src/diagnostic.rs [hunk 1]
```diff
@@ -519,6 +519,18 @@ impl Diagnostic {
...
+            subst.parts.iter().any(|part| {
+                let span = part.span;
+                let call_site = span.ctxt().outer_expn_data().call_site;
+                span.in_derive_expansion() && span.overlaps_or_adjacent(call_site)
+            })
+        });
+        if in_derive {
+            // Ignore if spans is from derive macro.
+            return;
+        }
```
Comment (oli-obk) [inline compiler/rustc_errors/src/diagnostic.rs:532]: I think this would be easier to read as two nested for loops and just returning directly if the condition applies.

**Comment by long-long-float** [comment]
Thank you for your review. I added a test for the issue and fix to use for-loop.

**Comment by oli-obk** [comment]
@bors r-

I've been told about a possible perf impact that previous attempts have had
