### PR TITLE
Fix wrong suggestion for adding where clauses

### LINKED ISSUE #97576: Compiler suggests adding illegal `where` bounds
Hi! :wave:

Given the following code:

```rust
struct Foo {
    bar: String,
}

impl Foo {
    pub fn new(bar: impl ToString) -> Self {
        Self {
            bar: bar.into(),
        }
    }
}
```
(https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=248f8c6fd510d2abf74cb29e90ad8588)

The current output (stable / beta / nightly) is:

```
error[E0277]: the trait bound `String: From<impl ToString>` is not satisfied
 --> src/lib.rs:8:22
  |
8 |             bar: bar.into(),
  |                      ^^^^ the trait `From<impl ToString>` is not implemented for `String`
  |
  = note: required because of the requirements on the impl of `Into<String>` for `impl ToString`
help: consider introducing a `where` bound, but there might be an alternative better way to express this requirement
  |
5 | impl Foo where String: From<impl ToString> {
  |          +++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
```

The issue is that I've used `bar.into()` instead of `bar.to_string()` -- and while the compiler suggesting to replace `.into()` with `.to_string()` would be pretty cool, at the very least I think it shouldn't propose adding `where String: From<impl ToString>` (which is both illegal & pretty pointless).

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #97576

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -591,8 +591,7 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                 }) if !param_ty => {
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:591]: can you instead move that check to here?

**Comment by lcnr** [comment]
@bors r+ rollup

:sweat_smile:
