### PR TITLE
Fix ICE for repr simd on non struct

### LINKED ISSUE #148634: ICE: `assertion failed: self.is_struct() || self.is_union()`
### Code

```Rust
#![feature(repr_simd)]

use std::arch::asm;

#[repr(simd)]
enum Es {}
static CLs: Es;

pub fn main() {
    let mut b = 4i32;
    unsafe {
        asm!("{}", out(reg) CLs);
    }
}
```

A mutant of [`tests/pretty/asm.rs`](https://github.com/rust-lang/rust/blob/c90bcb9571b7aab0d8beaa2ce8a998ffaf079d38/tests/pretty/asm.rs)

### Meta

`rustc --version --verbose`:
```
rustc 1.93.0-nightly (c90bcb957 2025-11-06)
binary: rustc
commit-hash: c90bcb9571b7aab0d8beaa2ce8a998ffaf079d38
commit-date: 2025-11-06
host: x86_64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.3
```

### Error output

Command: `rustc`

```
error: free static item without body
 --> 14.rs:7:1
  |
7 | static CLs: Es;
  | ^^^^^^^^^^^^^^-
  |               |
  |               help: provide a definition for the static: `= <expr>;`

error[E0517]: attribute should be applied to a struct
 --> 14.rs:5:8
  |
5 | #[repr(simd)]
  |        ^^^^
6 | enum Es {}
  | ---------- not a struct

error[E0084]: unsupported representation for zero-variant enum
 --> 14.rs:5:8
  |
5 | #[repr(simd)]
  |        ^^^^
6 | enum Es {}
  | ------- zero-variant enum


thread 'rustc' (6698172) panicked at compiler/rustc_middle/src/ty/adt.rs:462:9:
assertion failed: self.is_struct() || self.is_union()
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' (6698172) panicked at compiler/rustc_middle/src/ty/adt.rs:462:9:
assertion failed: self.is_struct() || self.is_union()
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_hir_typeck::inline_asm::InlineAsmCtxt>::check_asm_operand_type
   4: rustc_hir_typeck::typeck_with_inspect::{closure#0}
   5: rustc_hir_typeck::typeck
      [... omitted 1 frame ...]
   6: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis::check_crate::{closure#2}>::{closure#0}
   7: rustc_hir_analysis::check_crate
   8: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
   9: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>
  10: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/jb/Library/CloudStorage/Dropbox/Desk/2503_rustc_ice/20251106 ice 보고용/rustc-ice-2025-11-07T07_18_16-4837.txt` to your bug report

query stack during panic:
#0 [typeck] type-checking `main`
#1 [analysis] running analysis passes on crate `14`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0084, E0517.
For more information about an error, try `rustc --explain E0084`.
```

</p>
</details>

### Notes
- ICE location: `compiler/rustc_middle/src/ty/adt.rs Line-462`
https://github.com/rust-lang/rust/blob/c90bcb9571b7aab0d8beaa2ce8a998ffaf079d38/compiler/rustc_middle/src/ty/adt.rs#L460-L464
  - In my guess, the `non_enum_variant` call comes from here:
https://github.com/rust-lang/rust/blob/c90bcb9571b7aab0d8beaa2ce8a998ffaf079d38/compiler/rustc_hir_typeck/src/inline_asm.rs#L168-L189

- Duplication Check
  - I searched "self.is_struct()" ICE ([Github issue page with query](https://github.com/rust-lang/rust/issues?q=is%3Aissue%20state%3Aclosed%20label%3AI-ICE%20%22self.is_struct()%22)), and there are no opened issues there.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#148634

The ICE happened because 
https://github.com/rust-lang/rust/blob/995c11894fdabe1c630694254de756f82389c6cf/compiler/rustc_middle/src/ty/mod.rs#L1531

will always set `IS_SIMD` according to `get_all_attrs`, and since we already report error `attribute should be applied to a struct`, it's OK to bypass here.

### CODE REVIEW

**Review by Kivooeo — APPROVED** [review]

**Comment by Kivooeo** [comment]
r=me when ci is green

**Comment by lcnr** [comment]
hmm, would it be possible to instead filter the `ReprOptions` so that we don't end up with unsupported ones? It feels brittle to simply handle incorrect info by ignoring it, e.g. it adds an implicit assumption that `repr(simd)` is only ever used for structs, and if we were to idk, extend support to unions at some point (even if unlikely) this code would suddenly be incorrect

alternatively, accept all `Adt`s, but then match on the kind and skip + span_delay_bug if it's not a struct

**Comment by chenyukang** [comment]
@lcnr 
I updated the code in commit: 
https://github.com/rust-lang/rust/compare/995c11894fdabe1c630694254de756f82389c6cf..112d833ea5c72f89078069ffc5d10da5b1adf2ca

I'm thinking do we need to delay_as_bug, since if we already returned `Err(NonAsmTypeReason::Invalid(ty))`, there will always an error reported `error[E0084]: unsupported representation for ...`

**Comment by chenyukang** [comment]
Ok, `span_delay_bug` seems checking the whether there is already an error before this point.

File: compiler/rustc_hir_typeck/src/inline_asm.rs [hunk 1]
```diff
@@ -93,6 +93,14 @@ impl<'a, 'tcx> InlineAsmCtxt<'a, 'tcx> {
                 }
             }
             ty::Adt(adt, args) if adt.repr().simd() => {
+                if !adt.is_struct() {
+                    self.fcx.dcx().span_delayed_bug(
+                        span,
+                        format!("repr(simd) should only be used on structs, got {}", adt.descr()),
+                    );
+                    return Err(NonAsmTypeReason::Invalid(ty));
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/inline_asm.rs]: can you add `NonAsmTypeReason::Tainted(ErrorGuaranteed)` and return that here. This avoids the unnecessary inline asm error

File: compiler/rustc_hir_typeck/src/inline_asm.rs [hunk 2]
```diff
@@ -94,11 +95,11 @@ impl<'a, 'tcx> InlineAsmCtxt<'a, 'tcx> {
             }
             ty::Adt(adt, args) if adt.repr().simd() => {
                 if !adt.is_struct() {
-                    self.fcx.dcx().span_delayed_bug(
+                    let error_guard = self.fcx.dcx().span_delayed_bug(
                         span,
                         format!("repr(simd) should only be used on structs, got {}", adt.descr()),
                     );
-                    return Err(NonAsmTypeReason::Invalid(ty));
+                    return Err(NonAsmTypeReason::Tainted(error_guard));
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/inline_asm.rs]:
```suggestion
                    let guar = self.fcx.dcx().span_delayed_bug(
span,
format!("repr(simd) should only be used on structs, got {}", adt.descr()),
);
                    return Err(NonAsmTypeReason::Tainted(guar));
```
style nit

**Comment by Kivooeo** [comment]
Maybe like this then

@bors try test-various

**Comment by Kivooeo** [comment]
Ok maybeee

@bors try jobs=test-various

**Comment by chenyukang** [comment]
finally it's passed, I added `//@ needs-asm-support` in the testcase.
@bors r=Kivooeo,lcnr
