### PR TITLE
Avoid repetition on “use of unstable library feature 'rustc_private'”

### LINKED ISSUE #44953: The “use of unstable library feature 'rustc_private'” error is very repetitive
`rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)`

Compiling this:
```rust
#[macro_use] extern crate log;

pub fn main() {
    info!("This is a log message.");
}
```

while not including `log` as a dependency in `Cargo.toml`, produces the following output:
```
error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:1:14
  |
1 | #[macro_use] extern crate log;
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: aborting due to 10 previous errors
```

### PR DESCRIPTION
**Pull request by virgil-palanciuc**
This PR fixes the error by only emitting it when the span contains a real file (is not inside a macro) - and making sure it's emitted only once per span. 
The first check was needed because spans-within-macros seem to differ a lot and "fixing" them to the real location is not trivial (and the method that does this is private to another module). It also feels like there always will be an error on import, with the real file name, so not sure there's a point to re-emit the same error at macro use.

Fix #44953.

### CODE REVIEW

**Comment by oli-obk** [comment]
`compile-fail/internal-unstable-noallow.rs` needs adjusting

**Comment by virgil-palanciuc** [comment]
Yes, I've seen it now, sorry for that; I didn't have time to look at it/ fix it yet.

File: src/librustc/middle/stability.rs [hunk 1]
```diff
@@ -597,8 +597,31 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
                                            feature.as_str(), &r),
                     None => format!("use of unstable library feature '{}'", &feature)
                 };
-                emit_feature_err(&self.sess.parse_sess, &feature.as_str(), span,
-                                 GateIssue::Library(Some(issue)), &msg);
+
+
+                let msp: MultiSpan = span.into();
+                let cm = &self.sess.parse_sess.codemap();
+                let span_key =
```
Comment (estebank) [inline src/librustc/middle/stability.rs]: You can probably fit the following line on this one.

File: src/librustc/middle/stability.rs [hunk 2]
```diff
@@ -597,8 +597,31 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
...
+                    msp.primary_span().and_then(|sp:Span|
+                        if sp != DUMMY_SP {
```
Comment (estebank) [inline src/librustc/middle/stability.rs]: Clean up the formatting for this entire block to avoid as having as much left padding.

File: src/librustc/middle/stability.rs [hunk 3]
```diff
@@ -597,8 +597,31 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
...
+                                None
+                            } else {
+                                Some(span)
+                            }
+                        } else {
+                            None
+                        }
+                    );
+
+                let tuple = (None, span_key, msg.clone());
```
Comment (estebank) [inline src/librustc/middle/stability.rs]: Try to give `tuple` a more descriptive name. You can also get around that by just inserting the tuple inline ;)

File: src/librustc/middle/stability.rs [hunk 4]
```diff
@@ -597,8 +597,31 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
...
-                                 GateIssue::Library(Some(issue)), &msg);
+
+
+                let msp: MultiSpan = span.into();
+                let cm = &self.sess.parse_sess.codemap();
+                let span_key =
+                    msp.primary_span().and_then(|sp:Span|
+                        if sp != DUMMY_SP {
+                            let fname = cm.lookup_char_pos(sp.lo()).file.as_ref().name.clone();
+                            if fname.starts_with("<") && fname.ends_with(" macros>") {
```
Comment (estebank) [inline src/librustc/middle/stability.rs]: This piece of code could be better as a method of `cm.lookup_char_pos(sp.lo()).file`.

File: src/librustc/session/mod.rs [hunk 5]
```diff
@@ -78,7 +78,7 @@ pub struct Session {
     /// Set of (LintId, Option<Span>, message) tuples tracking lint
     /// (sub)diagnostics that have been set once, but should not be set again,
     /// in order to avoid redundantly verbose output (Issue #24690).
-    pub one_time_diagnostics: RefCell<FxHashSet<(lint::LintId, Option<Span>, String)>>,
+    pub one_time_diagnostics: RefCell<FxHashSet<(Option<lint::LintId>, Option<Span>, String)>>,
```
Comment (estebank) [inline src/librustc/session/mod.rs]: <rant>Normally, instead of making the first tuple field an option, I would suggest making the `FxHashSet` accept a new struct with three fields `diagnostic_id`, `span` and `message`, with `diagnostic_id` being a new enum that takes either a `LintId` or a `GateIssue`. This way we can keep expanding `one_time_diagnostics` without the risk of having multiple different diagnostics with the same span message and no lint_id, but being different errors, from being incorrectly stopped, but because of the `message` being there, what you're doing is correct and unlikely to be made incorrect with a subsequent change.</rant>

**Review by estebank — APPROVED** [review]
Overall looks great to me! Please fix the formatting nitpicks and I'll merge.

File: src/librustc/middle/stability.rs (hunk 4 above)
Comment (virgil-palanciuc) [reply src/librustc/middle/stability.rs]: Not sure what you meant. Hopefully the way it's written now is better (well, it _is_ better, I don't exactly know why I felt I needed to make it so complicated... )

File: src/librustc/session/mod.rs [hunk 6]
```diff
@@ -361,7 +368,7 @@ impl Session {
             },
             _ => {
                 let lint_id = lint::LintId::of(lint);
-                let id_span_message = (lint_id, span, message.to_owned());
+                let id_span_message = (DiagnosticMessageId::LintId(lint_id), span, message.to_owned());
```
Comment (kennytm) [inline src/librustc/session/mod.rs]: Please shorten this line to ≤100 chars.

```
[00:02:54] tidy error: /checkout/src/librustc/session/mod.rs:371: line longer than 100 chars
```

**Comment by JakubAdamWieczorek** [comment]
May be worth adding a test?
