### PR TITLE
Fix the assertion crash from rustdoc document indent widths

### LINKED ISSUE #124363: ICE: rustdoc: `line.len() >= frag.indent`
### Code

```Rust
// Ensure that empty doc comments don't panic.

/*!
*/

///
///
pub struct Foo;

#[doc = "
"]
pub mod Mod {
   //!
   //!
}

/**
*/
pub mod Another {
   #![doc = "{
        a: WithDestructor { x: 10, y: 20 },
        guard: -1
    }"]
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_resolve/src/rustdoc.rs:179:13:
assertion failed: line.len() >= frag.indent
stack backtrace:
   0:     0x7fe48623f145 - std::backtrace_rs::backtrace::libunwind::trace::h1236582651c1a511
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7fe48623f145 - std::backtrace_rs::backtrace::trace_unsynchronized::hc94959f693b9403b
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe48623f145 - std::sys_common::backtrace::_print_fmt::hb8d72834ec4dcd8b
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fe48623f145 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbe8a0147626b5a9d
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe48628e21b - core::fmt::rt::Argument::fmt::h2ca4c56a63bde201
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/core/src/fmt/rt.rs:165:63
   5:     0x7fe48628e21b - core::fmt::write::h62b5a48a83f1e30e
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/core/src/fmt/mod.rs:1157:21
   6:     0x7fe486233ccf - std::io::Write::write_fmt::hc1a208285775c61d
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/io/mod.rs:1832:15
   7:     0x7fe48623ef1e - std::sys_common::backtrace::_print::h7317b4cdba0d65ec
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fe48623ef1e - std::sys_common::backtrace::print::h3afe172db76376cd
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fe486241889 - std::panicking::default_hook::{{closure}}::h2a1c71509062b8d1
  10:     0x7fe4862415cd - std::panicking::default_hook::h699d55a2e7d63ba8
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/panicking.rs:298:9
  11:     0x7fe482c55d1c - std[d6a83134d699b09b]::panicking::update_hook::<alloc[a24983a8da22b0cb]::boxed::Box<rustc_driver_impl[6dafe5a6b3d364]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fe486241f86 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h29bd797fcd684d04
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/alloc/src/boxed.rs:2036:9
  13:     0x7fe486241f86 - std::panicking::rust_panic_with_hook::hee79f0d367b3d9ff
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/panicking.rs:799:13
  14:     0x7fe486241cfb - std::panicking::begin_panic_handler::{{closure}}::hd1a7e1efe9b201c3
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/panicking.rs:656:13
  15:     0x7fe48623f609 - std::sys_common::backtrace::__rust_end_short_backtrace::ha2bd5d6292632b08
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fe486241a67 - rust_begin_unwind
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/panicking.rs:652:5
  17:     0x7fe48628a6e3 - core::panicking::panic_fmt::hfa43f6250d1829bc
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/core/src/panicking.rs:72:14
  18:     0x7fe48628a78c - core::panicking::panic::h61b6698fe18c120b
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/core/src/panicking.rs:146:5
  19:     0x7fe4835738b7 - rustc_resolve[191f6aae1c2aef4c]::rustdoc::add_doc_fragment
  20:     0x55ec846c16e3 - <rustdoc[dc05c746aa88fd7]::clean::types::Attributes>::opt_doc_value
  21:     0x55ec847ed9d7 - <rustdoc[dc05c746aa88fd7]::passes::check_custom_code_classes::CustomCodeClassLinter as rustdoc[dc05c746aa88fd7]::fold::DocFolder>::fold_item
  22:     0x55ec84712a3c - <rustdoc[dc05c746aa88fd7]::passes::check_custom_code_classes::CustomCodeClassLinter as rustdoc[dc05c746aa88fd7]::fold::DocFolder>::fold_inner_recur
  23:     0x55ec847eee66 - <rustdoc[dc05c746aa88fd7]::passes::check_custom_code_classes::CustomCodeClassLinter as rustdoc[dc05c746aa88fd7]::fold::DocFolder>::fold_item
  24:     0x55ec847ed2a6 - rustdoc[dc05c746aa88fd7]::passes::check_custom_code_classes::check_custom_code_classes
  25:     0x55ec846f72ff - rustdoc[dc05c746aa88fd7]::core::run_global_ctxt
  26:     0x55ec84600aff - <rustc_middle[f8afccddd91f4f43]::ty::context::GlobalCtxt>::enter::<rustdoc[dc05c746aa88fd7]::main_args::{closure#1}::{closure#0}::{closure#0}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#1}
  27:     0x55ec8460a062 - rustc_interface[15bac81e1f7feb64]::interface::run_compiler::<core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>, rustdoc[dc05c746aa88fd7]::main_args::{closure#1}>::{closure#1}
  28:     0x55ec845d3dd5 - std[d6a83134d699b09b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[15bac81e1f7feb64]::util::run_in_thread_with_globals<rustc_interface[15bac81e1f7feb64]::util::run_in_thread_pool_with_globals<rustc_interface[15bac81e1f7feb64]::interface::run_compiler<core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>, rustdoc[dc05c746aa88fd7]::main_args::{closure#1}>::{closure#1}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#0}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>
  29:     0x55ec84613787 - <<std[d6a83134d699b09b]::thread::Builder>::spawn_unchecked_<rustc_interface[15bac81e1f7feb64]::util::run_in_thread_with_globals<rustc_interface[15bac81e1f7feb64]::util::run_in_thread_pool_with_globals<rustc_interface[15bac81e1f7feb64]::interface::run_compiler<core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>, rustdoc[dc05c746aa88fd7]::main_args::{closure#1}>::{closure#1}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#0}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[212b32ecf022bd7b]::result::Result<(), rustc_span[80fb5c55c22d081e]::ErrorGuaranteed>>::{closure#2} as core[212b32ecf022bd7b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7fe48624be1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h51760a968aa5c7f1
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/alloc/src/boxed.rs:2022:9
  31:     0x7fe48624be1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h851c49059e3d99c3
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/alloc/src/boxed.rs:2022:9
  32:     0x7fe48624be1b - std::sys::pal::unix::thread::Thread::new::thread_start::h1ff3ffc2b6bfc536
                               at /rustc/ef8b9dcf23700f2e2265317611460d3a65c19eff/library/std/src/sys/pal/unix/thread.rs:108:17
  33:     0x7fe47f894ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  34:     0x7fe47f926850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  35:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/gh-matthiaskrgr/vcs/github/rust_misc_stuff/rustc-ice-2024-04-25T05_26_17-1643588.txt` to your bug report

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #124363

### CODE REVIEW

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 1]
```diff
@@ -136,8 +136,11 @@ pub fn unindent_doc_fragments(docs: &mut [DocFragment]) {
...
                     let whitespace = line.chars().take_while(|c| *c == ' ' || *c == '\t').count();
-                    cmp::min(min_indent, whitespace)
-                        + if fragment.kind == DocFragmentKind::SugaredDoc { 0 } else { add }
+                    cmp::min(
+                        min_indent,
+                        whitespace
+                            + (if fragment.kind == DocFragmentKind::SugaredDoc { 0 } else { add }),
+                    )
                 }
             })
```
Comment (Nadrieril) [inline compiler/rustc_resolve/src/rustdoc.rs:145]: This looks good to me. Could you turn the `fold()` into something like `.filter(is_all_whitespace).map(count_whitespace+add).min()` now that that's possible?

Comment (chenyukang) [reply compiler/rustc_resolve/src/rustdoc.rs]: Fixed.

**Comment by Nadrieril** [comment]
Thank you!

@bors r+
