### PR TITLE
Prefer raw::c_char or libc::c_char and fix arm

### LINKED ISSUE #29774: libc types exposed by libstd
The libc merge was a breaking change: `c_char` on ARM Linux [was i8](https://github.com/rust-lang/rust/blob/00aa3cbecc6723898a04467050891c26a7fdb758/src/liblibc/lib.rs#L463) but [is now u8](https://github.com/rust-lang-nursery/libc/blob/b1a043feeae3a67f45e75eaf10aa900a1f6832f9/src/unix/notbsd/linux/other/b32/arm.rs#L1). This is a bugfix, which is fair, it was wrong before. This type is exposed via [CStr::as_ptr()](https://github.com/rust-lang/rust/blob/master/src/libstd/ffi/c_str.rs#L459) however, and there was no obvious way to refer to it, so users would depend on and use the crates.io `libc::c_char`, which only corresponds if using (old rustc + libc 0.1) or (new rustc + libc 0.2).

Note that [os::raw::c_char](https://github.com/rust-lang/rust/blob/master/src/libstd/os/raw.rs#L18) is still wrong/old, so even using that would break.

cc @alexcrichton

### PR DESCRIPTION
**Pull request by arcnmx**
It's a bit strange to expect users of `libstd` to require the use of an external crates.io crate to work with standard types. This commit encourages the use `os::raw::c_char` instead, although users are certainly free to use `libc::c_char` if they wish; the test still exists to ensure the two types are identical (though the reported bug only exists on platforms that are not officially tested).

Fixes #29774

### CODE REVIEW

File: src/libstd/os/raw.rs [hunk 1]
```diff
@@ -12,9 +12,13 @@
...
 
-#[cfg(any(target_arch = "aarch64", target_os = "android"))]
+#[cfg(all(not(target_os = "ios"), not(target_os = "macos"),
+          any(target_arch = "aarch64", target_arch = "arm",
+              target_os = "android")))]
 #[stable(feature = "raw_os", since = "1.1.0")] pub type c_char = u8;
-#[cfg(not(any(target_arch = "aarch64", target_os = "android")))]
+#[cfg(any(target_os = "ios", target_os = "macos",
+          not(any(target_arch = "aarch64", target_arch = "arm",
+                  target_os = "android"))))]
```
Comment (arcnmx) [inline src/libstd/os/raw.rs]: I hope all this is correct... ugh.

Comment (alexcrichton) [inline src/libstd/os/raw.rs]: At least going by the current definition of liblibc, the type is unsigned for linux arm, linux aarch64, and android everywhere. Perhaps the ios/macos clause could be turned into a linux-specific clause?

File: src/libstd/ffi/c_str.rs [hunk 2]
```diff
@@ -36,8 +37,8 @@ use vec::Vec;
 ///
 /// A `CString` is created from either a byte slice or a byte vector. After
 /// being created, a `CString` predominately inherits all of its methods from
-/// the `Deref` implementation to `[libc::c_char]`. Note that the underlying
-/// array is represented as an array of `libc::c_char` as opposed to `u8`. A
+/// the `Deref` implementation to `[os::raw::c_char]`. Note that the underlying
+/// array is represented as an array of `os::raw::c_char` as opposed to `u8`. A
```
Comment (alexcrichton) [inline src/libstd/ffi/c_str.rs]: It's probably fine to omit the `os::raw::` in these two and just mention `c_char`.

**Comment by alexcrichton** [comment]
Looks good to me, thanks @arcnmx!

I wouldn't necessarily go so far as to say we should all stop using `libc::c_char` just yet, but it's certainly true that the standard library shouldn't be reexporting APIs exposing the underlying unstable `libc` library!

File: src/libstd/os/raw.rs (hunk 1 above)
Comment (arcnmx) [inline src/libstd/os/raw.rs]: Hm, k, so if I have the logic right... everything is signed, exceptions are: linux aarch64 and arm, and android? The main thing I wasn't sure about were ARM BSDs.

Comment (alexcrichton) [inline src/libstd/os/raw.rs]: Yeah I'm not entirely sure about BSDs, but they can always be fixed once we gain support!

**Comment by arcnmx** [comment]
There that should be better I think? When can we just start using cfg-if in libstd :(

**Comment by alexcrichton** [comment]
I wouldn't have a problem just vendoring the macro like libc does, it'd probably definitely pull its weight by this point!

**Comment by liigo** [comment]
Maybe need a breaking-change mark?

**Comment by SimonSapin** [comment]
I’m pretty sure this is a breaking change to stable APIs. Code that used to work cross-platform now fails to build with errors like ``expected `*const i8`, found `*const u8` `` on ARM targets (but not Intel targets): https://github.com/servo/servo/pull/8446#issuecomment-156470211

This seems like a violation of the stability promise with no apparent justification.

**Comment by larsbergstrom** [comment]
cc: @alexcrichton @brson

**Comment by arcnmx** [comment]
@SimonSapin 

True, it's a breaking change specifically on ARM Linux targets. I wasn't aware the stability promise applied to third tier platforms. The reasoning was that #29546 was a breaking change on that platform for the same reason, and also broke tests (the assertion that `os::raw::c_char == libc::c_char`).

This was to bring std back in line - the other alternative is to revert libc's change. Considering that the original API was wrong, ARM Linux isn't officially supported, and liblibc 0.2 was already deployed to crates.io, it seemed like we'd may as well just fix the issue and deal with the breakage.

**Comment by SimonSapin** [comment]
For what it’s worth we’re seeing breakage on ARM Android. I don’t know if that’s more supported than ARM Linux.

**Comment by arcnmx** [comment]
@SimonSapin hm, that'd be a bug then. Also note that the errors you linked to were broken by #29546 and not this commit (see #29774).

**Comment by SimonSapin** [comment]
Ah, sorry if I got the wrong culprit. I guessed at what changes seemed relevant in https://github.com/rust-lang/rust/commits/master/src/libstd/os/raw.rs

**Comment by arcnmx** [comment]
@SimonSapin yup the old libc was wrong on android too. From what I can tell x86 Android would've broke too? Android is also tier 3 so same argument applies :/

Solution for the most part is to update your dependencies that use libc to 0.2

**Comment by SimonSapin** [comment]
(I don’t think we have CI for Servo on x86 Android.)

**Comment by arcnmx** [comment]
@SimonSapin though it was breaking regardless, the crux of the issue really is that we've all been depending on a crates.io dependency as part of the type signature of a std method, and when one changes without the other, things go boom~!

I still suggest everyone move away from libc::c_char, but I guess `os::raw` is 3 whole characters longer :(

**Comment by SimonSapin** [comment]
I think it’s less about the number characters than the amount of existing code (that may have been written before `std::os::raw` existed) where we apply the easiest fix whenever things break.

**Comment by SimonSapin** [comment]
It looks like updating libc from 0.1 fixes at least some of the build errors. I’ll report back when we’ve updated everything. (Looks like we have 67 `Cargo.toml` files to update in a number of git repositories.)

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/issues/29867 to help track this.
