### PR TITLE
Depth limit const eval query

### LINKED ISSUE #114192: generic const items: polymorphically recursive consts lead to compiler stack overflow
I expected the following code to lead to an error (overflow, const eval, or cycle):

```rs
#![feature(generic_const_items)]

const RECUR<T>: () = RECUR::<(T,)>;

fn main() {}
```

Instead, the memory & CPU usage of the compiler quickly grew until the OOM killer terminated the process (I presume this to be a stack overflow turned into an OOM situation due to the use of `ensure_sufficient_stack` somewhere which causes stacks to be allocated on the heap).

Debug builds of the compiler crash immediately with a segmentation fault.
Running rustc with GDB yields (which merely looks like a symptom):

```
Thread 2 "rustc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe8bff6c0 (LWP 433325)]
rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_type<rustc_middle::ty::print::pretty::FmtPrinter> (self=..., ty=...) at compiler/rustc_middle/src/ty/print/pretty.rs:909
909             ty::Slice(ty) => p!("[", print(ty), "]"),
```

(14,000 line backtrace not included in this issue ^^)

Corresponding UI test: `tests/ui/generic-const-items/recursive.rs` (`known-bug`, `ignore-test`).

### Meta

<details><summary><code>rustc -Vv</code></summary>

```
rustc 1.73.0-nightly (04abc370b 2023-07-28)
binary: rustc
commit-hash: 04abc370b9f3855b28172b65a7f7d5a433f41412
commit-date: 2023-07-28
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

</details>

@rustbot label C-bug T-compiler I-crash requires-incomplete-features F-generic_const_items
@rustbot claim

### LINKED ISSUE #125718: const blocks don't have a recursion limit, causing the compiler to freeze in an infinite loop
```rust
const fn foo<T>() {
    const { foo::<&T>() }
}

const X: () = foo::<i32>();
```

The above code causes the compiler to hang, apparently in an infinite loop. I expected it to report an error due to a recursion limit or a timeout.

Note that removing the const block causes the compiler to correctly report an error.
<details>
<summary>Code without the const block</summary>

```rust
const fn foo<T>() {
    foo::<&T>()
}

const X: () = foo::<i32>();
```
This code results in the following error:
```
   Compiling playground v0.0.1 (/playground)
warning: function cannot return without recursing
 --> src/lib.rs:1:1
  |
1 | const fn foo<T>() {
  | ^^^^^^^^^^^^^^^^^ cannot return without recursing
2 |     foo::<&T>()
  |     ----------- recursive call site
  |
  = help: a `loop` may express intention better if this is on purpose
  = note: `#[warn(unconditional_recursion)]` on by default

error[E0080]: evaluation of constant value failed
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^ reached the configured maximum number of stack frames
  |
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<&i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `foo::<i32>`
 --> src/lib.rs:2:5
  |
2 |     foo::<&T>()
  |     ^^^^^^^^^^^
note: inside `X`
 --> src/lib.rs:5:15
  |
5 | const X: () = foo::<i32>();
  |               ^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
warning: `playground` (lib) generated 1 warning
error: could not compile `playground` (lib) due to 1 previous error; 1 warning emitted
```
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (da159eb33 2024-05-28)
binary: rustc
commit-hash: da159eb331b27df528185c616b394bb0e1d2a4bd
commit-date: 2024-05-28
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.6```

### PR DESCRIPTION
**Pull request by mzacho**
Currently the const-eval query doesn't have a recursion limit or timeout, causing the complier to freeze in an infinite loop, see #125718. This PR depth limits the `eval_to_const_value_raw` query (with the [`recursion_limit`](https://doc.rust-lang.org/reference/attributes/limits.html) attribute) and improves the diagnostics for query overflow errors, so spans are reported for other dep kinds than `layout_of` (e.g. `eval_to_const_value_raw`).

fixes #125718
fixes #114192

### CODE REVIEW

File: compiler/rustc_query_system/src/query/job.rs [hunk 1]
```diff
@@ -136,18 +136,16 @@ impl QueryJobId {
...
     #[inline(never)]
-    pub fn try_find_layout_root(
-        &self,
-        query_map: QueryMap,
-        layout_of_kind: DepKind,
-    ) -> Option<(QueryJobInfo, usize)> {
-        let mut last_layout = None;
-        let mut current_id = Some(*self);
-        let mut depth = 0;
+    pub fn try_find_dep_kind_root(&self, query_map: QueryMap) -> Option<(QueryJobInfo, usize)> {
```
Comment (oli-obk) [inline compiler/rustc_query_system/src/query/job.rs:139]: This is now always Some

```suggestion
    pub fn try_find_dep_kind_root(&self, query_map: QueryMap) -> (QueryJobInfo, usize) {
```

File: tests/ui/generic-const-items/recursive.stderr [hunk 2]
```diff
@@ -0,0 +1,11 @@
+error: queries overflow the depth limit!
+  --> $DIR/recursive.rs:10:13
+   |
+LL |     let _ = RECUR::<()>;
+   |             ^^^^^^^^^^^
+   |
+   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "30"]` attribute to your crate (`recursive`)
+   = note: query depth increased by 17 when simplifying constant for the type system `RECUR`
```
Comment (oli-obk) [inline tests/ui/generic-const-items/recursive.stderr:8]: Would be neat if we could report the query backtrace before that recursion

Comment (oli-obk) [reply tests/ui/generic-const-items/recursive.stderr:8]: (Similar to cycle errors)

Comment (mzacho) [reply tests/ui/generic-const-items/recursive.stderr:8]: I'm not exactly sure how this should work since the `job.id` never repeats in this case. I guess we could determine when the cycle is complete by finding the first parent query with `job.dep_kind == eval_to_const_value_raw` and a span that matches the one of the current query. What do you think about this?

**Comment by oli-obk** [comment]
Gonna run crater to see if the default limit is fine

**Comment by theemathas** [comment]
Should the code in https://github.com/rust-lang/rust/issues/114192#issuecomment-2547433420 also be included as a test?

**Comment by fmease** [comment]
Yes, that would great imo!

**Comment by oli-obk** [comment]
@craterbot check

**Comment by mzacho** [comment]
Don't think the job got enqueued? @oli-obk

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
No regressions, just some disk failures 

@bors r+

**Comment by uael** [comment]
I was actually quite relying on inline const to avoid the recursion limit, I prefer to not force my crate users to manually override it.
Is it possible to account for depth only for a function with the same generics parameters instead? Or is there a workaround?

**Comment by oli-obk** [comment]
Maybe start a Zulip or internals thread with your use case? There may be alternatives, but mostly we can't change anything here but pick a higher default in case the current one could be higher without risking stack overflows
