### PR TITLE
Change entry point to 🛡️ against 💥 💥-payloads

### LINKED ISSUE #86030: `lang_start` in std/src/rt.rs is unsound in presence of panic payload that panics on drop
See https://github.com/rust-lang/rust/issues/86027 for an example of the problem.

```
fn main() {
    std::panic::panic_any(Bomb);
}
```

```
thread 'main' panicked at 'Box<Any>', src/main.rs:12:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'explicit panic', src/main.rs:7:9
fatal runtime error: failed to initiate panic, error 5
abort (core dumped)
```

Here we panic without any landing pads available upstack, because we are already the top-most(-ish) frame in the first place. This is UB.

### PR DESCRIPTION
**Pull request by nagisa**
Guard against panic payloads panicking within entrypoints, where it is
UB to do so.

Note that there are a number of tradeoffs to consider. For instance, I
considered guarding against accidental panics inside the `rt::init` and
`rt::cleanup` code as well, as it is not all that obvious these may not
panic, but doing so would mean that we initialize certain thread-local
slots unconditionally, which has its own problems.

Fixes #86030 
r? @m-ou-se

### CODE REVIEW

File: library/std/src/rt.rs [hunk 1]
```diff
@@ -28,14 +28,31 @@ fn lang_start_internal(
...
+            // This user code has the freedom to (attempt to) panic again. On the other hand,
+            // unwinding out of this function is UB. This is a requirement imposed by a combination
+            // of how the `#[lang="start"]` attribute is implemented as well as the implementation
+            // of the panicking mechanism.
+            //
+            // Since the only way to reach this branch is by panicking in the first place, we take
+            // a liberty of running the drop in an environment that looks as if a panic is already
+            // in progress. This way any panics in the user code that we will run shortly will
+            // become double-panic aborts.
+            panic_count::increase();
```
Comment (bjorn3) [inline library/std/src/rt.rs:51]: Maybe it would be safer to add a drop bomb that aborts the process when unwinding above the `catch_unwind(main)` call? That would also ensure an abort when C++ unwinds into rust code. We define that as UB anyway, but just in case.

Comment (nagisa) [reply library/std/src/rt.rs:51]: There are multiple implementation approaches that could be taken here, indeed. Each has their own considerations.

I don't think the choice should be made based on behaviour in case UB is invoked, however. This code handling a super niche corner-case in the first place I think the simplicity of the implementation is probably outweighs in benefit the better UB resiliency.

That said, a drop-guard would allow to guard against panics in `rt::init` and `rt::cleanup`, which is quite desirable IME.

Comment (nagisa) [reply library/std/src/rt.rs]: Alas, the drop guard approach does _not_ work. That's because there isn't any catch pads the unwinding implementation could find, and thus you get the same old UB as if we did nothing at all.

I did adjust the implementation to use another `catch_unwind`, however, which should handle the issues with user code and certain runtime functions panicking.

File: library/std/src/rt.rs [hunk 2]
```diff
@@ -25,17 +25,35 @@ fn lang_start_internal(
...
-    unsafe { sys_common::rt::init(argc, argv) };
+        let exit_code = panic::catch_unwind(main);
 
-    let exit_code = panic::catch_unwind(main);
-
-    sys_common::rt::cleanup();
-
-    exit_code.unwrap_or(101) as isize
+        sys_common::rt::cleanup();
+        exit_code.unwrap_or(101) as isize
```
Comment (nagisa) [inline library/std/src/rt.rs:46]: :thought_balloon: at this location we invoke user code after the runtime cleanup has been executed. Is moving the drop here to above the cleanup something we want to do?

Comment (bjorn3) [reply library/std/src/rt.rs:46]: I would guess so.

Comment (m-ou-se) [reply library/std/src/rt.rs:46]: Yes, that'd be good.

**Comment by m-ou-se** [comment]
This PR guards against two things: 1. panics from rt::init/rt::cleanup, 2. panics from dropping a user-defined panic payload.

Maybe it's good to separate how those are handled.

For 1, we don't need to worry about dropping the payload, since we don't throw non-string payloads in the standard library (`panic_any` isn't used anywhere).

For 2, we should make sure the drop happens before `cleanup` because it executes user code. And we might want to show a different message, like `"panic payload panicked"` or something.

Regardless, this PR is already a big improvement over the current situation. So `r=me` either way.

**Comment by nagisa** [comment]
> For 1, we don't need to worry about dropping the payload

I think this already holds true – we don't particularly worry much about the runtime panics, as they are bugs in libstd's implementation and the fix would be to not panic in the first place.

> For 2, we should make sure the drop happens before cleanup because it executes user code. And we might want to show a different message, like "panic payload panicked" or something.

I adjusted the abort message to focus more on the panic-payload panics and less on the runtime side of the things. Ideally in absence of bugs in the libstd's implementation the only ways users will end up seeing the message is by panicking in the payload.

File: library/std/src/rt.rs [hunk 3]
```diff
@@ -25,17 +25,33 @@ fn lang_start_internal(
...
+        let exit_code = panic::catch_unwind(main).unwrap_or(101);
+        sys_common::rt::cleanup();
+        exit_code as isize
+    });
+    match result {
+        Ok(exit_code) => exit_code,
+        Err(e) => {
+            mem::forget(e);
+            panic_count::increase(); // guard against rtprintpanic! panicking.
+            rtprintpanic!("drop of the panic payload panicked"); // or a runtime bug has occurred!
```
[the remark this answers is not in the document]
Comment (nagisa) [reply library/std/src/rt.rs]: Well, IMO a backtrace would have revealed the problem regardless, but adjusted this anyway. That said, `lang_start_internal` has become a big pile of yucky assembly with this :(

**Comment by nagisa** [comment]
This is ready for a re-review.

File: library/std/src/rt.rs [hunk 4]
```diff
@@ -45,9 +59,12 @@ fn lang_start<T: crate::process::Termination + 'static>(
...
     argv: *const *const u8,
 ) -> isize {
-    lang_start_internal(
-        &move || crate::sys_common::backtrace::__rust_begin_short_backtrace(main).report(),
-        argc,
-        argv,
-    )
+    unsafe {
+        // SAFETY: Err variant can't exist by definition.
+        Result::<_, !>::unwrap_unchecked(lang_start_internal(
```
Comment (m-ou-se) [inline library/std/src/rt.rs:64]: There is a `Result::into_ok` for this: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#method.into_ok

(I suppose you could also use that directly instead of the `?`s above, to avoid changing the return type to Result.)

File: library/std/src/lib.rs [hunk 5]
```diff
@@ -219,22 +219,22 @@
 // std is implemented with unstable features, many of which are internal
 // compiler details that will never be stable
 // NB: the following list is sorted to minimize merge conflicts.
-#![feature(alloc_error_handler)]
-#![feature(alloc_layout_extra)]
 #![feature(allocator_api)]
 #![feature(allocator_internals)]
+#![feature(alloc_error_handler)]
+#![feature(alloc_layout_extra)]
```
Comment (m-ou-se) [inline library/std/src/lib.rs:225]: I don't necessarily mind sorting the features here (though it might cause unnecessary merge conflicts), but these ones specifically were already sorted correctly. The `_` comes before `a`.

Comment (m-ou-se) [reply library/std/src/lib.rs:225]: Ah, probably a locale thing:

```
$ LANG=C sort thing
#![feature(alloc_error_handler)]
#![feature(alloc_layout_extra)]
#![feature(allocator_api)]
#![feature(allocator_internals)]
```
```
$ LANG=en_GB.UTF-8 sort thing
#![feature(allocator_api)]
#![feature(allocator_internals)]
#![feature(alloc_error_handler)]
#![feature(alloc_layout_extra)]
```

`rustfmt` uses the first one for imports though, so let's follow that one.

Comment (nagisa) [reply library/std/src/lib.rs:225]: :pensive:

**Comment by m-ou-se** [comment]
Some platforms the CI runs the tests on don't support unwinding. So your test probably needs something like 
```
// ignore-wasm
// ignore-emscripten
```

**Comment by nagisa** [comment]
Looks like a timeout in communication with the builders.

@bors retry

**Comment by pnkfelix** [comment]
While doing performance triage, I noticed a number of rustc benchmarks [regressing their max-rss](https://perf.rust-lang.org/compare.html?start=29cd70d40722930e66a8b726fe58a7bd1d64a22b&end=6b354a13820a444f834a33365ae4a8d97d7d27ce&stat=max-rss) immediately after this PR: token-stream-stress by up to 10%, and many others in the 4% to 6% range.

@nagisa , Was this an expected outcome here? Do you have a hypothesis as to what might have caused it?

**Comment by nagisa** [comment]
I can't say it was expected. If I were to guess, it'd be because of different codegen unit distribution, perhaps.

**Comment by Mark-Simulacrum** [comment]
Yes, looking at the self profile results for the regressed benchmarks all have 1-2 additional LLVM modules being codegen'd. A simple `fn main() {}` generates some additional LLVM IR after this PR: https://gist.github.com/Mark-Simulacrum/896dfbf040073b9bffdffedc77a221b3 (generated without optimization, just `--emit=llvm-ir`).

Put up https://github.com/rust-lang/rust/pull/88988 with a potential fix.

**Comment by Mark-Simulacrum** [comment]
Per results in https://github.com/rust-lang/rust/pull/88988, that indeed seems to be sufficient to resolve the extra work this added. Spot checking a few benchmarks it removes the extra LLVM modules getting codegen'd so seems like mostly avoids the extra work introduced by this PR.

There's potential followup work here around removing some other extra bits that end up getting codegen'd into "empty main" binaries (e.g., the re-throwing of panics in __rust_begin_short_backtrace around the black_box), but those seem likely to have somewhat diminishing returns and are further work rather than direct fixes for a regression.

In the mean time, marking this as triaged. @rustbot label +perf-regression-triaged
