### PR TITLE
Correct detection of elided lifetimes in impl-trait.

### LINKED ISSUE #106338: regression: anonymous lifetimes now unstable in impl trait
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/hltas-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/monch-0.4.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/hltas-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/gh/shff.paq/log.txt

cc https://github.com/rust-lang/rust/pull/104048 as possible root cause, @cjgillot

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/106338

r? @compiler-errors 
cc @pnkfelix

### CODE REVIEW

**Comment by compiler-errors** [comment]
Makes sense. 

@bors r+

File: compiler/rustc_hir_analysis/src/collect/lifetimes.rs [hunk 1]
```diff
@@ -1195,8 +1195,10 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
                     // Fresh lifetimes in APIT used to be allowed in async fns and forbidden in
                     // regular fns.
                     if let Some(hir::PredicateOrigin::ImplTrait) = where_bound_origin
-                        && let hir::LifetimeName::Param(_) = lifetime_ref.res
-                        && lifetime_ref.is_anonymous()
+                        && let hir::LifetimeName::Param(param_id) = lifetime_ref.res
+                        && let Some(generics) = self.tcx.hir().get_generics(self.tcx.local_parent(param_id))
+                        && let Some(param) = generics.params.iter().find(|p| p.def_id == param_id)
+                        && param.is_elided_lifetime()
```
Comment (pnkfelix) [inline compiler/rustc_hir_analysis/src/collect/lifetimes.rs:1201]: With this PR, the error message still reads as ""anonymous lifetimes in `impl Trait` are unstable"

should it change to "elided lifetimes" instead of "anonymous lifetimes"?

Comment (pnkfelix) [reply compiler/rustc_hir_analysis/src/collect/lifetimes.rs:1201]: (this feedback need not block the landing of this PR. It was just something I noticed while looking it over)

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-01-12/near/320960519)

@rustbot label +beta-accepted
