### PR TITLE
Try to recover from path sep error in type parsing

### LINKED ISSUE #129273: E0050 emitted unexpectedly on missing `:`
### Code

```Rust
use std::fmt;

struct Hello;

impl fmt::Display for Hello {
    fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
        write!(f, "hello")
    }
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error: expected parameter name, found `:`
 --> src/lib.rs:6:26
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                          ^ expected parameter name

error: expected one of `!`, `(`, `)`, `,`, `::`, or `<`, found `:`
 --> src/lib.rs:6:26
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                          ^
  |                          |
  |                          expected one of `!`, `(`, `)`, `,`, `::`, or `<`
  |                          help: missing `,`

error[E0573]: expected type, found module `fmt`
 --> src/lib.rs:6:23
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                       ^^^ not a type

error[E0050]: method `fmt` has 3 parameters but the declaration in trait `std::fmt::Display::fmt` has 2
 --> src/lib.rs:6:12
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |            ^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters, found 3
  |
  = note: `fmt` from trait: `fn(&Self, &mut Formatter<'_>) -> Result<(), std::fmt::Error>`

Some errors have detailed explanations: E0050, E0573.
For more information about an error, try `rustc --explain E0050`.
error: could not compile `playground` (lib) due to 4 previous errors
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error: expected parameter name, found `:`
 --> src/lib.rs:6:26
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                          ^ expected parameter name

error: expected one of `!`, `(`, `)`, `,`, `::`, or `<`, found `:`
 --> src/lib.rs:6:26
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                          ^
  |                          |
  |                          expected one of `!`, `(`, `)`, `,`, `::`, or `<`
  |                          help: missing `,`

error[E0573]: expected type, found module `fmt`
 --> src/lib.rs:6:23
  |
6 |     fn fmt(&self, f: &fmt:Formatter) -> fmt::Result {
  |                       ^^^ not a type

Some errors have detailed explanations: E0050, E0573.
For more information about an error, try `rustc --explain E0050`.
error: could not compile `playground` (lib) due to 4 previous errors
```

### Rationale and extra context

When looking at rust-analyzer output or when just looking at the last few error messages, it's easy to see only the "too many arguments" error, and not the syntax error that points at the exact problem.

### Other cases

_No response_

### Rust Version

```Shell
1.80.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #129273

Error using `:` in the argument list may mess up the parser.

case `tests/ui/suggestions/struct-field-type-including-single-colon` also changed, seems it's  the same meaning, should be OK.

r? @estebank

### CODE REVIEW

File: compiler/rustc_parse/src/parser/path.rs [hunk 1]
```diff
@@ -247,8 +247,24 @@ impl<'a> Parser<'a> {
...
+                                    && self.token.span.lo() == self.prev_token.span.hi()
+                                    && self.look_ahead(1, |token| {
+                                        self.token.span.hi() == token.span.lo()
+                                    })
+                            } else {
+                                false
+                            }
+                    }
+                    _ => false,
+                };
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs:266]:
```suggestion
                let ok_for_recovery = self.may_recover() && match style {
                    PathStyle::Expr => true,
                    PathStyle::Type if let Some((ident, _)) = self.prev_token.ident()
                                    && self.token == token::Colon
                                    && self.token.span.lo() == self.prev_token.span.hi()
                                    && self.look_ahead(1, |token| {
                                        self.token.span.hi() == token.span.lo()
                                    })
                    }
                    _ => false,
                };
```

- Moving `self.may_recover()` out of the match & using an if-let guard for conciseness
-  Getting rid of the letter case check since I'd be nice to recover from `Self:AssocTy`, `TyParam:AssocTy`, too

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/path.rs]: it's hard to exclude this test case:

https://github.com/chenyukang/rust/blob/293514c34acd62fd71b3fee5889b414d466a3f64/tests/ui/array-slice-vec/vec-matching-fold.rs#L9

the `T:Debug` actually misses a whitespace, after formatting it's `T: Debug`.

Comment (chenyukang) [reply compiler/rustc_parse/src/parser/path.rs]: maybe we can ignore this scenario? since most of the time we are parsing formatted code ...

**Comment by workingjubilee** [comment]
Requires rebase
@bors r-

**Comment by workingjubilee** [comment]
thanks bors, very timely.
