### PR TITLE
Fix ICE: inject bitcast if types mismatch for invokes/calls/stores

### LINKED ISSUE #36744: LLVM error: Call parameter type does not match function signature
I get the error
```
Call parameter type does not match function signature!
  %vec = alloca %"3.std::vec::Vec<fn(&B<'_>)>"
 %"3.std::vec::Vec<fn(&B)>"*  invoke void @_ZN5error4call17h314c247b38f70641E(i8* %15, %"3.std::vec::Vec<fn(&B<'_>)>"* noalias readonly dereferenceable(24) %vec)
          to label %normal-return unwind label %unwind_ast_73_, !dbg !407
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `error`.
```
on this code (which I reduced as much as possible while still getting the error)
```rust
struct A<'a> {
    a: &'a i32,
}

fn call<T>(s: T, functions: &Vec<fn(&T)>) {
    for function in functions {
        function(&s);
    }
}

fn f(a: &A) { }

fn main() {
    let a = A { a: &10 };

    let vec: Vec<fn(&A)> = vec![f];
    call(a, &vec);
}
```
This is on Rust 1.11.0, on Linux 64.

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix ICE: inject bitcast if types mismatch for invokes/calls

Partial fix for #36744

### CODE REVIEW

**Comment by pnkfelix** [comment]
(oh I forgot a regression test; will put into followup commit.)

**Comment by pnkfelix** [comment]
So I just realized that this fix only handles the case of calls, which does fix the specific report of #36744 but does not address the other cases that @arielb1 pointed out here: https://github.com/rust-lang/rust/issues/36744#issuecomment-251718289

I'm looking into generalizing it slightly now to deal with more of those. 

 * I'm also considering taking a different tack of extending MIR with an explicit upcast operator so that trans can remain simple. But I would be less inclined to back port a PR that takes that route.

**Comment by pnkfelix** [comment]
While working on this PR, I realized that one flaw in this strategy is that you can not apply the LLVM `bitcast` instruction to aggregates. This may mean that we have other cases to handle that simply cannot be dealt with via the means used here.

**Comment by pnkfelix** [comment]
FYI @arielb1 mentioned over IRC discussion that he would prefer a more targeted fix oriented around changes to MIR-trans.

**Comment by pnkfelix** [comment]
@nikomatsakis @arielb1 : 

We should decide whether we are going to land this patch or not.

my opinion is that we should put this PR in. It solves the bulk of the occurrences of this problem (see [above comment](https://github.com/rust-lang/rust/pull/37112#issuecomment-253248245)), and guards against adding the bitcast when it is unneeded by first checking if the types already match.

**Comment by arielb1** [comment]
Sure. My patch is more complicated than it seems, but that's a hack.

@bors r+

File: src/librustc_trans/builder.rs [hunk 1]
```diff
@@ -1100,10 +1099,11 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
             llvm::LLVMRustBuildAtomicFence(self.llbuilder, order, scope);
         }
     }
-}
 
-fn check_call(typ: &str, llfn: ValueRef, args: &[ValueRef]) {
-    if cfg!(debug_assertions) {
+    fn check_call<'b>(&self,
```
Comment (nikomatsakis) [inline src/librustc_trans/builder.rs]: I think a comment here would be nice-- what is this `Cow` that is being returned?

**Review by nikomatsakis — APPROVED** [review]
r=me modulo nit

**Comment by nikomatsakis** [comment]
(Oh, I see @arielb1 already r+'d. Seems fine.)

**Comment by nikomatsakis** [comment]
Accepting for beta. Low risk patch, regression.

cc @rust-lang/compiler
