### PR TITLE
NLL should identify and respect the lifetime annotations that the user wrote 

### LINKED ISSUE #47184: NLL should identify and respect the lifetime annotations that the user wrote
We have made some progress on this issue.

Here's a list of everywhere within function bodies where we annotate types, with check boxes on the ones that are currently getting checked by the MIR-borrowck / NLL.

- [ ] Let bindings
  - [x] Simple local variable declarations, eg. `let x: u32 = 3;`
  - [x] More complicated let bindings. eg. `let (x, y): (u32, u32) = (33, 54);`
    - [x] https://github.com/rust-lang/rust/pull/53873 made these *mostly* work, but there are some edge cases where we still have problems. See the FIXME in the `patterns.rs` UI test.
    - [x] remainder is broken out into https://github.com/rust-lang/rust/issues/54570
  - [x] "Ignored" bindings, eg. `let _: Foo<'long> = c_is_short_oops;` (https://github.com/rust-lang/rust/pull/53873)
  - [x] Simple bindings with no initializer, e.g., `let x: T;` (https://github.com/rust-lang/rust/pull/53873)
  - [x] Complex bindings with no initializer, e.g., `let (x, y): (u32, u32);`
    - broken out into https://github.com/rust-lang/rust/issues/54570
  - [ ] `ref` bindings: e.g. `let ref x: u32 = 3;`, broken out into #55401
- [ ] Turbofish
  - [x] Function calls. eg. `"2048".parse::<u32>()` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Fully qualified paths. eg. `<T as Trait<_>>::method` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Fully qualified paths. eg. `<_ as Trait<T>>::method` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Fully qualified paths. eg. `<_ as Trait<_>>::method<T>` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Multi-segment paths. e.g. `Foo::<X>::method` -- broken out into https://github.com/rust-lang/rust/issues/54574
  - [x] Value references. eg. `let x = foo::<...>;` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Struct names. eg. `let x = SomeStruct::<'static> { field: u32 };` -- https://github.com/rust-lang/rust/pull/53225
  - [x] Associated constants in expressions: `<T as Foo>::BAR` ? (broken out to https://github.com/rust-lang/rust/issues/54571)
  - [ ] Associated constants in patterns: `<T as Foo>::BAR` ? (https://github.com/rust-lang/rust/issues/55511)
  - [x] Lifetimes in patterns: `let A::<'static>(r) = ...` ? -- broken out into https://github.com/rust-lang/rust/issues/54573
  - [x] Calls to enum variants / struct ctors: `Enum::Variant::<...>(...)`  -- https://github.com/rust-lang/rust/pull/53225
  - [x] Reference to nullary structs / variants: `None::<&'static u32>` -- https://github.com/rust-lang/rust/pull/53225
- [x] Casts: `x as T` (broken out into https://github.com/rust-lang/rust/issues/54332)
- [x] Type ascription: `x: &'static u32` (broken out into https://github.com/rust-lang/rust/issues/54331)
- [x] Method call disambiguation. eg. `<Type as Trait>::method(args);` -- https://github.com/rust-lang/rust/pull/53225
- [x] Lifetimes defined but not used, this currently only occurs in the `yield-subtype.rs` test but that will also need resolved.
- [ ] Normalization code is probably wrong (the user types need, I suspect, to be normalized? Not sure, have to look.)

(We should update this list as we think of more.)

Original bug report follows:

----

This code compiles with 1.24.0-nightly (2018-01-03 0a3761e63e5961ddd6ae5b9923e7a3c0725541f8):

```rust
#![feature(nll)]

fn main() {
    let vec: Vec<&'static String> = vec![&String::new()];

    // fn only_static(_: Vec<&'static String>) {}
    // only_static(vec);
}
```

This is confusing as the `Vec` almost certainly cannot contain a reference of a `'static` lifetime. If you uncomment the call to `only_static`, you get the expected error that the `String` does not live long enough.

@nikomatsakis said:

> NLL currently ignores hand-written type annotations, in particular, those that appear in local variables.

### PR DESCRIPTION
**Pull request by davidtwco**
Part of #47184.

r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
As of writing, this PR is not complete. It doesn't actually solve the issue yet, it just contains what I've got so far. 

It adds the majority of what was included in the mentoring instructions (I have not yet added the special case in the renumbering code as I wasn't sure about that).

**Comment by nikomatsakis** [comment]
@davidtwco nice! will look soon

File: src/librustc_mir/build/block.rs [hunk 1]
```diff
@@ -121,12 +122,15 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
                                 this.in_scope(scope, lint_level, block, move |this| {
                                     // FIXME #30046                             ^~~~
-                                    this.expr_into_pattern(block, pattern, init)
+                                    this.expr_into_pattern(block, ty, pattern, init)
                                 })
                             }));
                     } else {
                         this.visit_bindings(&pattern, &mut |this, _, _, node, span, _| {
                             this.storage_live_binding(block, node, span);
+                            if let Some(ty) = ty {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/block.rs]: So, this won't work for something like `let (a, b): (u32, u32) = (22, 44);` -- it will assert that both `a` and `b` have type `(u32, u32)`, I believe.

Comment (nikomatsakis) [reply src/librustc_mir/build/block.rs]: I'm not sure how most elegantly to handle this case right now -- one way would be to track the `ty` as we visit the bindings, so that we can destructure it appropriately. Another would be to "build back up" the value from the types of the bindings. I don't like either one, unfortunately :(

File: src/librustc_mir/build/matches/mod.rs [hunk 2]
```diff
@@ -145,8 +145,18 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
         end_block.unit()
     }
 
+    pub fn user_assert_ty(&mut self, block: BasicBlock, ty: Ty<'tcx>, var: NodeId, span: Span) {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/matches/mod.rs]: I've been debating whether my idea to make this a statement was good or not -- but I do see some advantages. For example, it neatly addresses the question of *where* this subtyping needs to be enforced.

File: src/librustc_mir/build/block.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/build/block.rs]: (I wonder if we can push the problem to typeck, actually, since it already has to do "destructure" the type hint, I think?)

File: src/librustc_mir/transform/cleanup_post_borrowck.rs [hunk 3]
```diff
@@ -98,3 +103,15 @@ impl<'a, 'tcx> MutVisitor<'tcx> for DeleteTrivialEndRegions<'a> {
...
     }
 }
+
+impl<'tcx> MutVisitor<'tcx> for DeleteUserAssertTy {
+    fn visit_statement(&mut self,
+                       block: BasicBlock,
+                       statement: &mut Statement<'tcx>,
+                       location: Location) {
+        if let StatementKind::UserAssertTy(..) = statement.kind {
+            statement.kind = StatementKind::Nop;
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/cleanup_post_borrowck.rs]: Nit: `statement.make_nop();`

File: src/librustc/session/config.rs [hunk 4]
```diff
@@ -1117,6 +1117,8 @@ options! {DebuggingOptions, DebuggingSetter, basic_debugging_options,
         "make unnamed regions display as '# (where # is some non-ident unique id)"),
     emit_end_regions: bool = (false, parse_bool, [UNTRACKED],
         "emit EndRegion as part of MIR; enable transforms that solely process EndRegion"),
+    include_user_assert_ty: bool = (false, parse_bool, [UNTRACKED],
+        "include UserAssertTy as part of MIR dumps"),
```
Comment (nikomatsakis) [inline src/librustc/session/config.rs]: I think we should just *always* include it...?

File: src/librustc_mir/transform/cleanup_post_borrowck.rs [hunk 5]
```diff
@@ -54,8 +54,10 @@ impl MirPass for CleanupPostBorrowck {
             delete.visit_mir(mir);
         }
 
-        let mut delete = DeleteUserAssertTy;
-        delete.visit_mir(mir);
+        if !tcx.sess.opts.debugging_opts.include_user_assert_ty {
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/cleanup_post_borrowck.rs]: Also, it seems like this flag isn't quite what it suggests -- that is, it doesn't "include it" in the dump, it "stops deleting it". Can't you just use `-Ζdump-mir` and inspect the results from earlier passes? For example, I generally do `-Zdump-mir=nll`

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 6]
```diff
@@ -776,6 +776,7 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
             | StatementKind::InlineAsm { .. }
             | StatementKind::EndRegion(_)
             | StatementKind::Validate(..)
+            | StatementKind::UserAssertTy(..)
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I think we want to do a check here -- something pretty similar to what `Assign` does. i.e., get the type of the `place` whose type is being asserted and invoke `self.sub_types()` (or actually `eq_type` perhaps).

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc/session/config.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc/session/config.rs]: Will remove this flag in a future commit.

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: I completely forgot I could view the MIR from earlier passes, so yeah, I'll remove this flag.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I intended to add a check here in a future commit, I initially included the variant here just so I could see if being included in the MIR without it doing anything.

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: seems fine

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: Fixed this.

File: src/librustc/session/config.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc/session/config.rs]: Removed this.

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: Removed this.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Added something that uses `eq_type`, not sure it's doing 100% of what it needs to though.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 7]
```diff
@@ -771,6 +771,22 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
                     );
                 };
             }
+            StatementKind::UserAssertTy(ref ty, ref local) => {
+                let local_ty = mir.local_decls()[*local].ty;
+                debug!("check_stmt: user_assert_ty ty={:?} local_ty={:?}", ty, local_ty);
+                if let Err(terr) =
+                    self.eq_types(ty, local_ty, location.at_successor_within_block())
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I think this should be `at_self_within_block`, though it probably doesn't matter. But this basically means that the type must be equal "on entry" to the statement, which feels "intuitively" right to me.

**Comment by davidtwco** [comment]
So, with everything that is implemented at current, I'm not seeing the error from `UserAssertTy` being produced.

Currently, [the eq_type call](https://github.com/davidtwco/rust/blob/b09c2384b9028b1c1075e75838a42e1ba898840a/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L774-L789) is comparing the following:

```
DEBUG:<unknown>: check_stmt: user_assert_ty ty=std::vec::Vec<&'static std::string::String> local_ty=std::vec::Vec<&'static std::string::String>
```

I've experimented with ways to support the `let (a, b): (u32, u32) = (22, 44); ` case mentioned in the previous review regarding this, but also couldn't find a particularly elegant way to handle this in the parts of the code that are currently being changed.

I'm uncertain what the next steps for this PR are? @nikomatsakis

File: src/librustc_mir/transform/cleanup_post_borrowck.rs [hunk 8]
```diff
@@ -42,15 +42,15 @@ impl MirPass for CleanEndRegions {
                           tcx: TyCtxt<'a, 'tcx, 'tcx>,
                           _source: MirSource,
                           mir: &mut Mir<'tcx>) {
-        if !tcx.emit_end_regions() { return; }
+        if tcx.emit_end_regions() {
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/cleanup_post_borrowck.rs]: any particular reason for this hunk, or just cleanup? (I sort of prefer the "return early" variant)

File: src/librustc/mir/visit.rs [hunk 9]
```diff
@@ -619,6 +629,11 @@ macro_rules! make_mir_visitor {
                 }
             }
 
+            fn super_user_assert_ty(&mut self,
+                                    _ty: & $($mutability)* Ty<'tcx>,
+                                    _local: & $($mutability)* Local) {
```
Comment (nikomatsakis) [inline src/librustc/mir/visit.rs]: You are missing some things here:

```
self.visit_ty(ty);
self.visit_local(local);
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
You are also missing changes to [the renumberer](https://github.com/rust-lang/rust/blob/257ec08e1004a44f4eaf6c30a5dfa2069f8fd877/src/librustc_mir/borrow_check/nll/renumber.rs).  In particular, I think we want to override `visit_user_assert_ty` in that impl to do nothing, so that we preserve the user's types.

I *think* this should fix your test case!

Sorry for the super delayed feedback.

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 8 above)
Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: So do I actually, this was just left-over from when I had `CleanEndRegions` and `CleanUserAssertTy` combined as a single pass and I didn't want an early return to stop the deletion of the `UserAssertTy`. I can change it back.

**Comment by davidtwco** [comment]
It's now causing an error as we would expect (though, almost certainly not the error we want in the end). If I'm not mistaken, we still need to handle the `let (a, b): (u32, u32) = (22, 44);` case and where `let x: &u32 = ...;` needs to be distinguished from `let x: &'static u32 = ...;` (as per the original instructions).

Normally I'd copy the error from the AST borrowck, but I notice that [on nightly with the AST borrowck](https://play.rust-lang.org/?gist=0e36d5fd6d4049e654cba92267a72b66&version=nightly) the error is an ICE while [on stable with the AST borrowck](https://play.rust-lang.org/?gist=0e36d5fd6d4049e654cba92267a72b66&version=stable) it is a normal error. Just noticed this while writing, so until now I wasn't sure what error it should have been.

File: src/test/ui/issue-47184.rs [hunk 10]
```diff
@@ -0,0 +1,16 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![feature(nll)]
+
+fn main() {
+    let vec: Vec<&'static String> = vec![&String::new()];
+    //~^ ERROR
```
Comment (nikomatsakis) [inline src/test/ui/issue-47184.rs]: What error do we get now?

File: src/librustc_mir/transform/cleanup_post_borrowck.rs [hunk 11]
```diff
@@ -93,7 +93,33 @@ impl<'a, 'tcx> MutVisitor<'tcx> for DeleteTrivialEndRegions<'a> {
...
 
         if delete_it {
-            statement.kind = StatementKind::Nop;
+            statement.make_nop();
+        }
+        self.super_statement(block, statement, location);
+    }
+}
+
+pub struct CleanUserAssertTy;
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/cleanup_post_borrowck.rs]: why are these two distinct things?

File: src/librustc_mir/borrow_check/nll/renumber.rs [hunk 12]
```diff
@@ -118,6 +118,11 @@ impl<'a, 'gcx, 'tcx> MutVisitor<'tcx> for NLLVisitor<'a, 'gcx, 'tcx> {
         debug!("visit_closure_substs: substs={:?}", substs);
     }
 
+    fn visit_user_assert_ty(&mut self, _ty: &mut Ty<'tcx>, _local: &mut Local,
+                            _location: Location) {
+        debug!("visit_user_assert_ty: skipping renumber");
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/renumber.rs]: It'd be nice to have a comment here. Something like:

---

User-assert-ty statements represent types that the user added explicitly.
We don't want to erase the regions from these types: rather, we want to
add them as constraints at type-check time.

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 11 above)
Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: If you are referring to the separation of the passes, in my experimentation locally, I found that the passes had to happen at different times otherwise the `UserAssertTy` statement wouldn't be in the MIR when the NLL type check code gets it (since the type check pass doesn't run when `#![feature(nll)]` was used - as far as I could tell - ordering it relative to that wasn't viable). Therefore they had to be separate. If this doesn't sound right, I can take another look.

File: src/librustc_mir/borrow_check/nll/renumber.rs (hunk 12 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/renumber.rs]: Will add this as soon as I get a chance.

File: src/test/ui/issue-47184.rs (hunk 10 above)
Comment (davidtwco) [reply src/test/ui/issue-47184.rs]: As far as I can remember (not able to run this at the moment), we got an ICE produced by [this section of the code](https://github.com/davidtwco/rust/blob/e66fa1b3acf4470d0906a413d0b8e0f0abf42a1b/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L768-L775).

Though, strangely, Travis isn't showing this. Perhaps I got mixed up and saw something else.

**Comment by davidtwco** [comment]
I've updated the test in this PR with the expected error that we see in the AST borrowck. What was happening is the following:

We were seeing an ICE occuring in the `to_region_vid` call from [this section of the code](https://github.com/davidtwco/rust/blob/e66fa1b3acf4470d0906a413d0b8e0f0abf42a1b/src/librustc_mir/borrow_check/nll/constraint_generation.rs#L112-L132). This was what I mistakenly thought was the expected error from above - oops!

This is just because it is visiting the type that didn't get renumbered, which we don't want, so I've overridden the `visit_user_assert_ty` fn here in the newest commits. It might be the case that those statements should have been removed by our pass by the time it got to this point.

I'm not entirely sure where our `DeleteUserAssertTy` pass should happen, if I put it at the same place the `CleanEndRegions` pass happens then the statement is removed before the [user type assertion check](https://github.com/davidtwco/rust/blob/e66fa1b3acf4470d0906a413d0b8e0f0abf42a1b/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L768-L775). That's why those two passes are separate and for now, I've just put the `DeleteUserAssertTy` pass somewhere that I found it worked.

Upon doing this, I expected to see no error be reported - as I previously wasn't seeing the ICE that I thought would be thrown [where our user type assertion is performed](https://github.com/davidtwco/rust/blob/e66fa1b3acf4470d0906a413d0b8e0f0abf42a1b/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L768-L775). Digging in a little, it seems I made a bad assumption regarding all that `eq_types` actually does (from a cursory glance, I assumed that when it returned `Err(..)` then the types didn't match and that's where we'd handle error throwing, that evidently is not the case). Given that, it seems like we're actually seeing this do what it is supposed to now - yay!

Looking over initial instructions and previous comments, this still doesn't handle the `let (a, b): (u32, u32) = (22, 44);` case and the case where `let x: &u32 = ...;` needs to be distinguished from `let x: &'static u32 = ...;`.

**Comment by davidtwco** [comment]
After chatting with @nikomatsakis [on Gitter](https://gitter.im/rust-lang/WG-traits?at=5aa7e7cc012ff2bf681d701c), here's a list of everywhere within function bodies where we annotate types:

- [x] Let bindings. eg. `let x: u32 = 3;`
  - [ ] More complicated let bindings. eg. `let (x, y): (u32, u32) = (33, 54);`
- [ ] Turbofish. eg. `"2048".parse::<u32>()`

I'll update this list as I think of more.

**Comment by davidtwco** [comment]
@nikomatsakis alright, moved that list to the issue. Will add those to the list.

**Comment by davidtwco** [comment]
I've noticed the errors on Travis. Not sure what is different, but I'm struggling to re-produce them. Here's [what I'm seeing locally](https://gist.github.com/davidtwco/10c01b88403a943f9620d6635ddbb258), will keep looking into it. Might just need to do a clean rebuild.

File: src/librustc_mir/transform/cleanup_post_borrowck.rs (hunk 11 above)
Comment (nikomatsakis) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: Hmm. I didn't realize that these passes were running at distinct times. At minimum, could use a comment clarifying what is happening here =)

Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: I'll add one with my next push.

Comment (davidtwco) [reply src/librustc_mir/transform/cleanup_post_borrowck.rs]: This discussion should be resolved - I updated the comment on the module to mention this. It doesn't affect these lines specifically so this isn't marked as "outdated".

**Comment by davidtwco** [comment]
I've just pushed a commit that implements the change described [in the issue](https://github.com/rust-lang/rust/issues/47184#issuecomment-372831647) to handle inference variables. This solves the issue that was plauging the `drop-may-dangle.rs` and `drop-may-not-dangle.rs` tests, _however_ it no longer passes our original `issue-47184` test case.

When we create our canonicalized type and store it in the `TypeckTables`, we see the following (where `o_ty` is the original type and `c_ty` is the canonicalized types):

```
DEBUG 2018-03-15T18:52:49Z: rustc_typeck::check: visit_local: ty.hir_id=HirId { owner: DefIndex(0:3), local_id: ItemLocalId(2) } o_ty=std::vec::Vec<&'static std::string::String> c_ty=Canonical { variables: Slice([CanonicalVarInfo { kind: Region }]), value: std::vec::Vec<&'_ std::string::String> }
```

In the above, we notice that after canonicalizing the type, we lose the `'static` lifetime. Continuing, when creating the `UserAssertTy` statement, we see what we would expect, the same canonicalized type being fetched from the `TypeckTable` for the statement:

```
DEBUG 2018-03-15T18:52:49Z: rustc_mir::build::matches: user_assert_ty: local_id=ItemLocalId(2)
DEBUG 2018-03-15T18:52:49Z: rustc_mir::build::matches: user_assert_ty: c_ty=Canonical { variables: Slice([CanonicalVarInfo { kind: Region }]), value: std::vec::Vec<&'_ std::string::String> }
```

Finally, when processing the statement and performing our type check, we see the following:

```
DEBUG 2018-03-15T18:55:41Z: rustc_mir::borrow_check::nll::type_check: check_stmt: UserAssertTy(Canonical { variables: Slice([CanonicalVarInfo { kind: Region }]), value: std::vec::Vec<&'_ std::string::String> }, _1)
DEBUG 2018-03-15T18:55:41Z: rustc_mir::borrow_check::nll::type_check: check_stmt: user_assert_ty ty=std::vec::Vec<&std::string::String> local_ty=std::vec::Vec<&std::string::String>
```

We see that the canonical type (`Canonical { variables: Slice([CanonicalVarInfo { kind: Region }]), value: std::vec::Vec<&'_ std::string::String> }`) is the same as when we created the statement - great! However, we see that when we instantiate the canonical with the fresh inference variables, we get the type `std::vec::Vec<&std::string::String>` which is being compared with our local `std::vec::Vec<&std::string::String>` - and as such, no error will be produced.

Previously, this would compare our type `std::vec::Vec<&'static std::string::String>` with `std::vec::Vec<&std::string::String>` and that would correctly cause our error to be produced. This seems to be an issue with `canonicalize_query` (or my usage of it).

File: src/librustc_typeck/check/mod.rs [hunk 13]
```diff
@@ -944,10 +944,19 @@ impl<'a, 'gcx, 'tcx> Visitor<'gcx> for GatherLocalsVisitor<'a, 'gcx, 'tcx> {
     // Add explicitly-declared locals.
     fn visit_local(&mut self, local: &'gcx hir::Local) {
         let o_ty = match local.ty {
-            Some(ref ty) => Some(self.fcx.to_ty(&ty)),
-            None => None
+            Some(ref ty) => {
+                let o_ty = self.fcx.to_ty(&ty);
+
+                let (c_ty, _orig_values) = self.fcx.inh.infcx.canonicalize_query(&o_ty);
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: So, I realize I guided you wrongly. I think you want to use `canonicalize_response`. These two functions differ in how they treat lifetimes -- in particular, `canonicalize_query` is designed for trait queries, and it replaces **all lifetimes** with variables -- including `'static`! That however is the opposite of what we want here. `canonicalize_response`, in contrast, will only replace lifetime *variables*, which is exactly what we want.

Comment (davidtwco) [reply src/librustc_typeck/check/mod.rs]: Fixed this and it the test is passing again locally!

**Review by nikomatsakis — APPROVED** [review]

File: src/librustc/mir/mod.rs [hunk 14]
```diff
@@ -1253,6 +1253,15 @@ pub enum StatementKind<'tcx> {
     /// (The starting point(s) arise implicitly from borrows.)
     EndRegion(region::Scope),
 
+    /// Encodes a user's type assertion. These need to be preserved intact so that NLL can respect
+    /// them. For example:
+    ///
+    ///     let (a, b): (T, U) = y;
+    ///
+    /// Here we would insert a `UserAssertTy<(T, U)>(y)` instruction to check that the type of `y`
+    /// is the right thing.
```
Comment (nikomatsakis) [inline src/librustc/mir/mod.rs]: It is worth adding to the docs that the `Canonical` is used to capture "inference variables" from user's types.

For example:

```
let x: Vec<_> = ...;
let y: &u32 = ...;
```

would result in `Vec<?0>` and `&'?0 u32` respectively (where `?0` is a canonicalized variable).

File: src/librustc/ty/context.rs [hunk 15]
```diff
@@ -344,6 +345,9 @@ pub struct TypeckTables<'tcx> {
     /// method calls, including those of overloaded operators.
     type_dependent_defs: ItemLocalMap<Def>,
 
+    /// Stores the canonicalized types provided by the user.
+    user_provided_tys: ItemLocalMap<CanonicalTy<'tcx>>,
```
Comment (nikomatsakis) [inline src/librustc/ty/context.rs]: Maybe add a "see also: the `UserAssertTy` statement in MIR" or something like that?

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 16]
```diff
@@ -761,6 +761,22 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
                     );
                 };
             }
+            StatementKind::UserAssertTy(ref c_ty, ref local) => {
+                let local_ty = mir.local_decls()[*local].ty;
+                let (ty, _) = self.infcx.instantiate_canonical_with_fresh_inference_vars(
+                    stmt.source_info.span, c_ty);
+                debug!("check_stmt: user_assert_ty ty={:?} local_ty={:?}", ty, local_ty);
+                if let Err(terr) = self.eq_types(ty, local_ty, location.at_self()) {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: 👍

File: src/librustc_mir/build/block.rs [hunk 17]
```diff
@@ -120,10 +121,19 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                             opt_destruction_scope.map(|de|(de, source_info)), block, |this| {
                                 let scope = (init_scope, source_info);
                                 this.in_scope(scope, lint_level, block, |this| {
-                                    this.expr_into_pattern(block, pattern, init)
+                                    this.expr_into_pattern(block, ty, pattern, init)
                                 })
                             }));
                     } else {
+                        // FIXME: We currently only insert `UserAssertTy` statements for patterns
```
Comment (nikomatsakis) [inline src/librustc_mir/build/block.rs]: Can we say `FIXME(#47184)`? We no longer mandate it, but I still prefer to have issue labels where we can.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Awesome. Left a few nits but this is basically good to go.

File: src/librustc/mir/mod.rs (hunk 14 above)
Comment (davidtwco) [reply src/librustc/mir/mod.rs]: This has been added but it is slightly below the reviewed line so GitHub hasn't noticed.

**Review by nikomatsakis — APPROVED** [review]
