### PR TITLE
Fix #[linkage] propagation though generic functions

### LINKED ISSUE #18804: #[linkage] does not propagate through generic functions
For example:

``` rust
// lib.rs
#![feature(linkage)]

pub fn foo<T>() -> *const () {
    extern {
        #[linkage = "extern_weak"]
        static FOO: *const ();
    }
    FOO
}
```

``` rust
// main.rs
extern crate lib;

fn main() {
    lib::foo::<int>();
}
```

```
$ rustc lib.rs --crate-type rlib
$ rustc main.rs -L .
error: linking with `cc` failed: exit code: 1
note: cc '-Wl,--as-needed' '-m64' '-L' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-o' 'main' 'main.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-fno-lto' '-Wl,--gc-sections' '-pie' '-nodefaultlibs' '/home/alex/liblib.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libnative-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsync-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustrt-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-4e7c5e5c.rlib' '/home/alex/code/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4e7c5e5c.rlib' '-L' '.' '-L' '/home/alex/.rust' '-L' '/home/alex' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-ldl' '-lpthread' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
note: main.o:main.0.rs:function foo::h6978205699166201756: error: undefined reference to 'FOO'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
```

This can be a little more clearly seen with the IR generated for main:

```
; ModuleID = 'main.0.rs'
target datalayout = "e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@FOO = external global {}*

...
```

Note the lack of `extern_weak` anywhere on `FOO`.

### PR DESCRIPTION
**Pull request by yodaldevoid**
Fixes #18804

In the non-local branch of `get_static` (where the fix was implemented) `span_fatal` had to be replaced with `bug!` as we have no span in that case.

### CODE REVIEW

File: src/librustc_codegen_llvm/consts.rs [hunk 1]
```diff
@@ -197,19 +203,60 @@ pub fn get_static(cx: &CodegenCx, def_id: DefId) -> ValueRef {
         g
     } else {
         // FIXME(nagisa): perhaps the map of externs could be offloaded to llvm somehow?
-        // FIXME(nagisa): investigate whether it can be changed into define_global
-        let g = declare::declare_global(cx, &sym, cx.layout_of(ty).llvm_type(cx));
+        debug!("get_static: sym={} item_attr={:?}", sym, cx.tcx.item_attrs(def_id));
+
+        let codegen_fn_attrs = cx.tcx.codegen_fn_attrs(def_id);
+        let llty = cx.layout_of(ty).llvm_type(cx);
+        let g = if let Some(linkage) = codegen_fn_attrs.linkage {
```
Comment (oli-obk) [inline src/librustc_codegen_llvm/consts.rs]: can you pull this code out into a function so it isn't duplicated?

**Comment by oli-obk** [comment]
@bors r+

thanks!

**Comment by yodaldevoid** [comment]
After doing some digging, it looks like Emscripten doesn't "currently support nuances like weak symbols". [reference](https://github.com/kripken/emscripten/wiki/Linking#overview-of-dynamic-linking)

Should I simply disable this test for Emscripten?

**Comment by oli-obk** [comment]
> Should I simply disable this test for Emscripten?

yes. Maybe also disable for wasm? Not sure if that can cope with it?

**Comment by yodaldevoid** [comment]
> Maybe also disable for wasm?

Looking at the homu log it seems wasm succeeded which I was not expecting when seeing this failure. Looking at it closer it seems that might be because it is building with `wasm-unknown-unknown` rather than `wasm-unknown-emscripten`.

**Comment by yodaldevoid** [comment]
@oli-obk Everything is rebased to be able to merge and should be ready to go.

File: src/test/run-pass/issue-18804/main.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// Test for issue #18804, #[linkage] does not propagate thorugh generic
+// functions. Failure results in a linker error.
+
+// aux-build:lib.rs
```
Comment (oli-obk) [inline src/test/run-pass/issue-18804/main.rs]: doesn't this file also need the `//ignore-*` comments? Or is compiletest smart enough to figure out that if an aux-build isn't built we also shouldn't run the test depending on it?

r=me with that question resolved

Comment (yodaldevoid) [reply src/test/run-pass/issue-18804/main.rs]: You are correct. I put the comments in the wrong file while not thinking. The main test file needs the comments while the auxiliary file does not.

**Comment by oli-obk** [comment]
Thanks! I didn't know the aux files don't need the comments, but it kinda makes sense. They are only compiled if a file referencing them is compiled.
