### PR TITLE
Utilize -Zbinary-dep-depinfo in rustbuild

### LINKED ISSUE #49979: "found possibly newer version of crate `std` which `cc` depends on" while building rustc
While working on std lately, I semi-regularly end up with an error like below. Unfortunately I don’t know the exact conditions to reproduce this. It possibly involves re-using a build directory after starting a new branch from a new position of git `upstream/master`.

This looks similar to https://github.com/rust-lang/rust/issues/44739, which was fixed in https://github.com/rust-lang/rust/pull/44792. Maybe something there regressed? CC @Mark-Simulacrum 

```rust
Building stage1 codegen artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu, llvm)
   Compiling rustc_llvm v0.0.0 (file:///home/simon/rust1/src/librustc_llvm)
error[E0460]: found possibly newer version of crate `std` which `cc` depends on
  --> librustc_llvm/build.rs:11:1
   |
11 | extern crate cc;
   | ^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: the following crate versions were found:
           crate `std`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bde80a95b5831673.rlib
           crate `std`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bde80a95b5831673.so
           crate `cc`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/libcc-5e2a255eead634fb.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0460`.
error: Could not compile `rustc_llvm`.
```

### LINKED ISSUE #50481: Rustbuild: changing and testing libcore results in "found possibly newer version of crate `std` which `rand` depends on"
I tried testing `libcore` with the changes of #50466, which enables way faster testing of libcore and libstd.

When I execute `./x.py test --stage 0 --no-doc src/libcore` the first time, everything works fine. If I then change test-code in `libcore/tests`, only the tests are rebuild and everything works (awesome!). But if I change `libcore` directly, it tries to rebuild a few things and then has a problem with the crate `rand`:

```
$ ./x.py test --stage 0 --no-doc src/libcore --test-args time
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized] target(s) in 0.0 secs
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling core v0.0.0 (file:///home/lukas/dev/rust/src/libcore)
   Compiling compiler_builtins v0.0.0 (file:///home/lukas/dev/rust/src/rustc/compiler_builtins_shim)
   Compiling libc v0.0.0 (file:///home/lukas/dev/rust/src/rustc/libc_shim)
   Compiling alloc v0.0.0 (file:///home/lukas/dev/rust/src/liballoc)
   Compiling std_unicode v0.0.0 (file:///home/lukas/dev/rust/src/libstd_unicode)
   Compiling unwind v0.0.0 (file:///home/lukas/dev/rust/src/libunwind)
   Compiling alloc_system v0.0.0 (file:///home/lukas/dev/rust/src/liballoc_system)
   Compiling panic_abort v0.0.0 (file:///home/lukas/dev/rust/src/libpanic_abort)
   Compiling alloc_jemalloc v0.0.0 (file:///home/lukas/dev/rust/src/liballoc_jemalloc)
   Compiling rustc_lsan v0.0.0 (file:///home/lukas/dev/rust/src/librustc_lsan)
   Compiling panic_unwind v0.0.0 (file:///home/lukas/dev/rust/src/libpanic_unwind)
   Compiling rustc_asan v0.0.0 (file:///home/lukas/dev/rust/src/librustc_asan)
   Compiling rustc_msan v0.0.0 (file:///home/lukas/dev/rust/src/librustc_msan)
   Compiling rustc_tsan v0.0.0 (file:///home/lukas/dev/rust/src/librustc_tsan)
   Compiling std v0.0.0 (file:///home/lukas/dev/rust/src/libstd)
    Finished release [optimized] target(s) in 30.15 secs
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling term v0.0.0 (file:///home/lukas/dev/rust/src/libterm)
   Compiling getopts v0.2.17
   Compiling test v0.0.0 (file:///home/lukas/dev/rust/src/libtest)
    Finished release [optimized] target(s) in 6.58 secs
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Testing core stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling core v0.0.0 (file:///home/lukas/dev/rust/src/libcore)
error[E0460]: found possibly newer version of crate `std` which `rand` depends on
  --> libcore/../libcore/tests/lib.rs:53:1
   |
53 | extern crate rand;
   | ^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: the following crate versions were found:
           crate `std`: /home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libstd-5f3a747b9ee6cbda.rlib
           crate `std`: /home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5f3a747b9ee6cbda.rlib
           crate `std`: /home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5f3a747b9ee6cbda.so
           crate `std`: /home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libstd-5f3a747b9ee6cbda.so
           crate `rand`: /home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/librand-89787ed220814c67.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0460`.
error: Could not compile `core`.
warning: build failed, waiting for other jobs to finish...
error: build failed


command did not execute successfully: "/home/lukas/dev/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/home/lukas/dev/rust/src/libstd/Cargo.toml" "--lib" "--bins" "--examples" "--tests" "--benches" "-p" "core" "--" "time"
expected success, got: exit code: 101


failed to run: /home/lukas/dev/rust/build/bootstrap/debug/bootstrap test --stage 0 --no-doc src/libcore --test-args time
Build completed unsuccessfully in 0:00:44
```

Note that I can simply run `x.py clean && x.py test --stage 0 --no-doc src/libcore` and everything works again (and it doesn't even takes that much longer). But I guess this `rand` problem shouldn't occur anyway? The problem always occurs when performing the steps as described above.

CC @kennytm

### LINKED ISSUE #52719: Tests are not rebuilt when codegen is rebuilt
I was in the middle of bisecting on system llvm and running `x.py test src/libstd --stage 1` when I noticed that, in fact, while each step was rebuilding the compiler with the changed llvm correctly, the test that was being run was never recompiled, such that the same one was always running, and my bisect was guided by wrong results.

STR:
- Run `x.py test src/libstd --stage 1` once
- Touch anything that is part of e.g. librustc_codegen_llvm.so, e.g. `src/librustc_llvm/lib.rs`
- Run `x.py test src/libstd --stage 1` again

Expected result:
- Both librustc_codegen_llvm.so and the test are rebuilt, and the rebuilt test executed.

Actual result:
- librustc_codegen_llvm.so is rebuilt, the test is not, and the test built before the codegen changes is executed.

### LINKED ISSUE #53284: Changing rustc_codegen_llvm only will not rerun the tests
Running the tests with

> python x.py test --stage=1

changing the rustc_codegen_llvm and running the tests again with

> python x.py test --stage=1

will ignore all the tests that have passed during the first run.

### LINKED ISSUE #54008: rustbuild: rustc_codegen_llvm is recompiled when any rustc crate is changed
## STR

```
$ ../x.py test --incremental src/test/{compile-fail,ui,run-pass}
Updating only changed submodules
Submodules updated in 0.03 seconds
    Finished dev [unoptimized] target(s) in 0.24s                                                                                                                                                  
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.25s                                                                                                                                                
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.23s                                                                                                                                                
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_typeck v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_typeck)                                                                                                         
   Compiling rustc_save_analysis v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_save_analysis)
   Compiling rustc_privacy v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_privacy)
   Compiling rustc_driver v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_driver)
   Compiling rustc-main v0.0.0 (file:///home/ariel/Rust/rust-master/src/rustc)
    Finished release [optimized] target(s) in 24.95s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 codegen artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu, llvm)
   Compiling libc v0.2.43                                                                                                                                                                          
   Compiling rustc-demangle v0.1.9
   Compiling cc v1.0.22
   Compiling rustc_codegen_llvm v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_codegen_llvm)
   Compiling rustc_llvm v0.0.0 (file:///home/ariel/Rust/rust-master/src/librustc_llvm)
warning: In file included from /home/ariel/Rust/rust-master/src/llvm/include/llvm/CodeGen/TargetSubtargetInfo.h:22,
warning:                  from ../rustllvm/PassWrapper.cpp:29:
warning: /home/ariel/Rust/rust-master/src/llvm/include/llvm/CodeGen/SchedulerRegistry.h: In constructor ‘llvm::RegisterScheduler::RegisterScheduler(const char*, const char*, llvm::RegisterScheduler::FunctionPassCtor)’:
warning: /home/ariel/Rust/rust-master/src/llvm/include/llvm/CodeGen/SchedulerRegistry.h:40:52: warning: cast between incompatible function types from ‘llvm::RegisterScheduler::FunctionPassCtor’ {aka ‘llvm::ScheduleDAGSDNodes* (*)(llvm::SelectionDAGISel*, llvm::CodeGenOpt::Level)’} to ‘llvm::MachinePassCtor’ {aka ‘void* (*)()’} [-Wcast-function-type]
warning:    : MachinePassRegistryNode(N, D, (MachinePassCtor)C)
warning:                                                     ^
   Compiling num_cpus v1.8.0
    Finished release [optimized] target(s) in 1m 02s
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
...
```

This also occurs with `keep-stage0` etc.

## Expected result

Changing `librustc_typeck` requires only the reverse dependencies of `librustc_typeck` to be recompiled.

## Actual result

`librustc_codegen_llvm` is also recompiled. As you can see, this takes twice as much as compiling the reverse dependencies of `librustc_typeck` alone, leading to compilation being 3x slower.

### LINKED ISSUE #54712: x.py in incremental mode still rebuilds stage0-rustc if stage0-std changed.
That is, `stage0-rustc` appears to lose incremental artifacts.
cc @alexcrichton @Mark-Simulacrum

### LINKED ISSUE #59105: Incremental compilation error building rustc (`-i --keep-stage 0`)
I manage to successfully build the latest master revision of rustc, but then when I try to build it incrementally as `./x.py build -i --keep-stage 0`, I get the following error. Apparently, this is broken for others as well, as has been for a while.

```
$ ./x.py build -i --keep-stage 0
Updating only changed submodules
Submodules updated in 0.08 seconds
    Finished dev [unoptimized] target(s) in 0.45s
Warning: Using a potentially old libstd. This may not behave well.
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old libtest. This may not behave well.
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old codegen backend. This may not behave well.
Assembling stage1 compiler (x86_64-apple-darwin)
Building stage1 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling cc v1.0.28
   Compiling libc v0.2.46
   Compiling core v0.0.0 (/Users/alex/Software/rust-devel/src/libcore)
   Compiling unwind v0.0.0 (/Users/alex/Software/rust-devel/src/libunwind)
   Compiling build_helper v0.1.0 (/Users/alex/Software/rust-devel/src/build_helper)
   Compiling compiler_builtins v0.1.5
   Compiling cmake v0.1.33
   Compiling backtrace-sys v0.1.27
   Compiling std v0.0.0 (/Users/alex/Software/rust-devel/src/libstd)
   Compiling rustc_asan v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_asan)
   Compiling rustc_tsan v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_tsan)
   Compiling rustc-std-workspace-core v1.0.0 (/Users/alex/Software/rust-devel/src/tools/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/Users/alex/Software/rust-devel/src/liballoc)
   Compiling panic_abort v0.0.0 (/Users/alex/Software/rust-devel/src/libpanic_abort)
   Compiling rustc-demangle v0.1.10
   Compiling panic_unwind v0.0.0 (/Users/alex/Software/rust-devel/src/libpanic_unwind)
    Finished release [optimized] target(s) in 1m 12s
Copying stage1 std from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage1 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling getopts v0.2.17
   Compiling proc_macro v0.0.0 (/Users/alex/Software/rust-devel/src/libproc_macro)
   Compiling term v0.0.0 (/Users/alex/Software/rust-devel/src/libterm)
   Compiling test v0.0.0 (/Users/alex/Software/rust-devel/src/libtest)
    Finished release [optimized] target(s) in 21.00s
Copying stage1 test from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage1 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.6
   Compiling rand_core v0.3.0
   Compiling memoffset v0.2.1
   Compiling scopeguard v0.3.3
   Compiling lazy_static v1.2.0
   Compiling void v1.0.2
   Compiling stable_deref_trait v1.1.0
   Compiling either v1.5.0
   Compiling unicode-width v0.1.5
   Compiling byteorder v1.2.7
   Compiling bitflags v1.0.4
   Compiling graphviz v0.0.0 (/Users/alex/Software/rust-devel/src/libgraphviz)
   Compiling scoped-tls v1.0.0
   Compiling lazy_static v0.2.11
   Compiling termcolor v1.0.4
   Compiling rustc-demangle v0.1.10
   Compiling datafrog v2.0.1
   Compiling remove_dir_all v0.5.1
   Compiling fmt_macros v0.0.0 (/Users/alex/Software/rust-devel/src/libfmt_macros)
   Compiling rustc_fs_util v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_fs_util)
   Compiling rustc-serialize v0.3.24
   Compiling quick-error v1.2.2
   Compiling scoped-tls v0.1.2
   Compiling cc v1.0.28
   Compiling libc v0.2.46
   Compiling rustc-rayon-core v0.1.2
   Compiling rustc-rayon v0.1.2
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.6
   Compiling rustc_target v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_target)
   Compiling crc32fast v1.1.2
   Compiling syntax v0.0.0 (/Users/alex/Software/rust-devel/src/libsyntax)
   Compiling arrayvec v0.4.7
   Compiling owning_ref v0.3.3
   Compiling unreachable v1.0.0
   Compiling rustc v0.0.0 (/Users/alex/Software/rust-devel/src/librustc)
   Compiling log_settings v0.1.2
   Compiling rustc_incremental v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_incremental)
   Compiling rustc_metadata v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_metadata)
   Compiling chalk-macros v0.1.0
   Compiling humantime v1.2.0
   Compiling rustc_driver v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_driver)
   Compiling rand_xorshift v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_core v0.2.2
   Compiling miniz-sys v0.1.11
   Compiling rustc-hash v1.0.1
   Compiling smallvec v0.6.7
   Compiling ena v0.11.0
   Compiling rustc_cratesio_shim v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_cratesio_shim)
   Compiling lock_api v0.1.3
   Compiling polonius-engine v0.6.2
   Compiling crossbeam-epoch v0.3.1
   Compiling chalk-engine v0.9.0
   Compiling num_cpus v1.8.0
   Compiling jobserver v0.1.12
   Compiling atty v0.2.11
   Compiling backtrace v0.3.11
   Compiling memmap v0.6.2
   Compiling rand v0.5.5
   Compiling serialize v0.0.0 (/Users/alex/Software/rust-devel/src/libserialize)
   Compiling rand_chacha v0.1.0
   Compiling rand_pcg v0.1.1
   Compiling rand v0.6.1
   Compiling parking_lot_core v0.4.0
   Compiling rustc_apfloat v0.0.0 (/Users/alex/Software/rust-devel/src/librustc_apfloat)
   Compiling env_logger v0.5.13
   Compiling flate2 v1.0.6
   Compiling crossbeam-deque v0.2.0
   Compiling rustc_macros v0.1.0 (/Users/alex/Software/rust-devel/src/librustc_macros)
error[E0460]: found possibly newer version of crate `std` which `synstructure` depends onialize...
 --> src/librustc_macros/src/lib.rs:4:5
  |
4 | use synstructure::decl_derive;
  |     ^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `std`: /Users/alex/Software/rust-devel/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libstd-082537f2f194063c.rlib
          crate `std`: /Users/alex/Software/rust-devel/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libstd-082537f2f194063c.dylib
          crate `synstructure`: /Users/alex/Software/rust-devel/build/x86_64-apple-darwin/stage1-rustc/release/deps/libsynstructure-923fcb34d21ecfbf.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0460`.
error: Could not compile `rustc_macros`.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/Users/alex/Software/rust-devel/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-j" "12" "--release" "--features" "" "--manifest-path" "/Users/alex/Software/rust-devel/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
failed to run: /Users/alex/Software/rust-devel/build/bootstrap/debug/bootstrap build -i --keep-stage 0
Build completed unsuccessfully in 0:01:59
```

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
We no longer utilize stamp-file mtimes at all inside rustbuild, and a future PR may be able to entirely eliminate them by eagerly copying to the appropriate sysroot. The only mtime-based dependency tracking left is for documentation because we lie to Cargo about the rustdoc binary, so Cargo does not track changes to the real binary, and codegen-backends because binary-dep-depinfo does not emit that information into the depfiles.

Both of these are fixable in the longer term but this existing patch gives us the following benefits:
 * We no longer delete Cargo target directories manually within a stage. Cross-stage, changes to codegen backends will still clear out target directories. This means that incremental state persists across individual steps (e.g., rebuilding libstd does not clear out librustc incremental state). Fixes #54712.
 * Dependency tracking across steps within a given stage is now fully precise. We will not clear out all codegen backend dependencies due to changes in librustc_driver, for example, only deleting the final librustc_codegen_llvm crate. Fixes #54008, fixes #50481.
 * We properly track codegen backends as a dependency (equivalent to rustc) across changes. Fixes #53284, and fixes #52719.
 * Cross-stage dependency tracking of crates is also much more accurate and reliable. Most likely fixes #49979 (but no reproduction steps in that issue). Fixes #59105.

cc #63012

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
To be clear this is not intended to land as-is since it a) won't actually work as-is since the rustc needs to be overridden -- the currently nightly can't bootstrap successfully I believe due to MaybeUninit changes -- I'm using 2b78e10ac1454d2d4190c575f6ece03f484ac398 as the base commit via rustup-toolchain-install-master locally.

File: src/bootstrap/bin/rustc.rs [hunk 1]
```diff
@@ -315,6 +315,8 @@ fn main() {
         cmd.arg("-Z").arg("force-unstable-if-unmarked");
     }
 
+    cmd.arg("-Z").arg("binary-dep-depinfo");
```
Comment (alexcrichton) [inline src/bootstrap/bin/rustc.rs]: Could this include a comment indicating why it's doing this?

Comment (alexcrichton) [reply src/bootstrap/bin/rustc.rs]: Also, is it possible to use the Cargo feature for this instead of manually editing the `rustc.rs` wrapper here?

File: src/bootstrap/compile.rs [hunk 2]
```diff
@@ -1206,41 +1206,13 @@ pub fn run_cargo(builder: &Builder<'_>,
         deps.push((path_to_add.into(), false));
     }
 
-    // Now we want to update the contents of the stamp file, if necessary. First
```
Comment (alexcrichton) [inline src/bootstrap/compile.rs]: I'm actually sort of surprised that more of this method wasn't deleted. We're still executing Cargo in JSON mode and dealing with all that jazz, but is that to track more esoteric aspects? Could we perhaps prune most of the infrastructure here to avoid calling Cargo in JSON mode?

**Review by alexcrichton — COMMENTED** [review]
That's an impressive list of fixed issues!

This may also want to apply https://gist.github.com/alexcrichton/e0840447982f93cb22bbd98878d2c205 to get colors back in error messages and fix the progress bar with pipelining

File: src/bootstrap/bin/rustc.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/bin/rustc.rs]: Ah, sure, I didn't know we had threaded this out from Cargo, I'll definitely prefer to do that!

File: src/bootstrap/compile.rs (hunk 2 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/compile.rs]: We need to know where the artifacts rustc has emitted are to copy them into the sysroot (and some other things); I'm not sure there's a way to do that without Cargo running in JSON mode?

Comment (alexcrichton) [reply src/bootstrap/compile.rs]: 👍

**Review by alexcrichton — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Just force pushed what should hopefully be a fix for the cfg(bootstrap) bit; with stage0.txt modified to the beta scheduled to be released Tuesday we can likely land this PR in one go to avoid wasting two cycles.

**Comment by Mark-Simulacrum** [comment]
(This PR has dropped the necessary bootstrap update, by splitting it into https://github.com/rust-lang/rust/pull/63534).

**Comment by Centril** [comment]
Want to find out if this was a cause of a failure; @bors p=4

**Comment by Mark-Simulacrum** [comment]
@bors retry

Pretty sure literally every builder passed and homu just didn't get the notification (cc @pietroalbini - does that look similar to https://github.com/rust-lang/rust/issues/63513?)

**Comment by pietroalbini** [comment]
No, GitHub was correctly updated. Let me see if there are any errors on homu's side.

**Comment by pietroalbini** [comment]
Oh this is a legit timeout: the build took 4h0m6s, which is more than the 4 hour timeout...

**Comment by Mark-Simulacrum** [comment]
Longest builder took just under 4 hours (https://dev.azure.com/rust-lang/rust/_build/results?buildId=6037&view=logs) AFAICT, and it looks like that builder is taking 3h45m or so in other auto builds so presumably this is not unexpected. We should try and move some things around as the partner i686-mingw-1 builder is only taking 3 hours (so we have an hour or so to split across two builders, in theory).

**Comment by pietroalbini** [comment]
> Longest builder took just under 4 hours

Yeah, but in the summary the recorded build time was 4 hours and 6 seconds, which is when the final check suite was updated.

> We should try and move some things around as the partner i686-mingw-1 builder is only taking 3 hours (so we have an hour or so to split across two builders, in theory).

I'll look into this.

**Comment by RalfJung** [comment]
Some of the text in the OP still sounds like it comes from an alternative universe where this landed before the beta cutoff?

**Comment by Mark-Simulacrum** [comment]
Thanks for the reminder, I had forgotten to remove that text. Should be all down to just this PR now.

**Comment by LukasKalbertodt** [comment]
Thank you a ton! 

PRs like these are *huge* but are not the ones getting all the attention, for obvious reasons. This PR will make the lives of almost all people working on this repo a lot better! While the fixed issues sound like minor inconveniences, they made working on the compiler very annoying at times. I almost gave up on compiler-hacking twice just for annoyances like these! Reducing frustrations with the build-system goes a long way in attracting and keeping more people hacking on this repo. 

Please excuse my ramblings, but I just had to express my gratitude for PRs like this. Thanks again!
