### PR TITLE
Fix ICE on format string of macro with secondary-label

### LINKED ISSUE #91556: Unmatched brace in a format string crashes the compiler
Reproducer:
~~~
pub fn test(i: i32) -> String {
  format!(concat!("{0}𝖳𝖾𝗌𝗍{"), i)
}
~~~

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8b3a4c8413cd9d296706c9da0ac6e0c0

### PR DESCRIPTION
**Pull request by compiler-errors**
This generalizes the fix #86104 to also correctly skip `Span::from_inner` for the `secondary_label` of a format macro parsing error as well.

We can alternatively skip the `span_label` diagnostic call for the secondary label as well, since that label probably only makes sense when the _proper_ span is computed.

Fixes #91556

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/format.rs [hunk 1]
```diff
@@ -995,8 +995,9 @@ pub fn expand_preparsed_format_args(
             e.note(&note);
         }
         if let Some((label, span)) = err.secondary_label {
-            let sp = fmt_span.from_inner(span);
-            e.span_label(sp, label);
+            // FIXME(compiler-errors): Should we just suppress this secondary_label?
+            let sp2 = if efmt_kind_is_lit { fmt_span.from_inner(span) } else { fmt_span };
+            e.span_label(sp2, label);
```
Comment (hkmatsumoto) [inline compiler/rustc_builtin_macros/src/format.rs:1000]: `sp2` looks like a leftover temporary change. If so:
```suggestion
            let sp = if efmt_kind_is_lit { fmt_span.from_inner(span) } else { fmt_span };
            e.span_label(sp, label);
```

File: compiler/rustc_builtin_macros/src/format.rs [hunk 2]
```diff
@@ -995,8 +995,9 @@ pub fn expand_preparsed_format_args(
             e.note(&note);
         }
         if let Some((label, span)) = err.secondary_label {
-            let sp = fmt_span.from_inner(span);
-            e.span_label(sp, label);
+            // FIXME(compiler-errors): Should we just suppress this secondary_label?
```
Comment (cjgillot) [inline compiler/rustc_builtin_macros/src/format.rs:998]: I agree we should just suppress the secondary label. Its purpose is to point to the opening brace, which can't happen if we have to replace the span with `fmt_span`.
