### PR TITLE
Suggest relaxing implicit `type Assoc: Sized;` bound

### LINKED ISSUE #85378: E0277: suggest `?Sized` to relax implicit `Sized` bound on associated types
Given the following code: [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9e10548141bcdd05e57230114dabdc54)

```rust
trait TraitWithAType {
    type Item;
}
trait Trait {}
struct A {}
impl TraitWithAType for A {
    type Item = dyn Trait;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `(dyn Trait + 'static)` cannot be known at compilation time
 --> src/lib.rs:7:5
  |
2 |     type Item;
  |     ---------- required by this bound in `TraitWithAType::Item`
...
7 |     type Item = dyn Trait;
  |     ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Trait + 'static)`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Ideally the output should look like:

```
  |
2 |     type Item;
  |     ---------- required by this bound in `TraitWithAType::Item`
...
7 |     type Item = dyn Trait;
  |     ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Trait + 'static)`
help: consider relaxing the implicit `Sized` restriction
  |
2 |     type Item: ?Sized
  |              ^^^^^^^^
```

A similar error message with an unsized generic type argument _does_ mention the implicit `Sized` bound. [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=764e262216d72078b210315931fd1851) Unfortunately, it also doesn't explain the implicit bound up front in the "required by this bound" text. (It mentions it when suggesting to relax the implicit bound, but I think it would be better to mention it up front as well.)

Both error messages could benefit from changing the "required by this bound" text to "required by an implicit `Sized` bound".

### PR DESCRIPTION
**Pull request by estebank**
Fix #85378.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -2652,6 +2652,29 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
+                                .any(|tr| tr.trait_def_id() == self.tcx.lang_items().sized_trait())
+                        {
+                            let (span, separator) = if let [.., last] = bounds {
+                                (last.span().shrink_to_hi(), " +")
+                            } else {
+                                (ident.span.shrink_to_hi(), ":")
+                            };
+                            err.span_suggestion_verbose(
+                                span,
+                                "consider relaxing the implicit `Sized` obligation",
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2673]:
```suggestion
                                "consider relaxing the implicit `Sized` bound",
```

*Obligation* is compiler dev speak :D

Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:2673]: Good catch. Changed to "restriction" to match other messages.
