### PR TITLE
rustc: Fix a number of stability lint holes

### LINKED ISSUE #8962: Detect stability attributes on modules and crates
```rust
// some_crate.rs
#[experimental];

#[deprecated]
pub mod some_mod {
    pub fn foo() {}
} 
```

```rust
extern mod some_crate; // warning: use of experimental item

use some_crate::some_mod; // warning: use of deprecated item

fn main() {
    some_crate::some_mod::foo(); // warning: use of deprecated item
}
```

It seems unlikely that this should flag crates and modules without annotations, but I'm not really sure.

(Part of #6875, continuation of #8921.)

### LINKED ISSUE #16360: Compiler warnings are not raised for code enclosed in macros
When deprecated API usage is enclosed in a macro like `try!`, no warning is raised. However, using it directly in `match` does.

Below is an example using the deprecated `url` crate from rust nightly distribution. A warning is raised only in the `use_match` function.

```
extern crate url;

use url::Url;

fn main() {
    println!("Host: {}", use_try("http://localhost").unwrap())
    println!("Host: {}", use_match("http://localhost").unwrap())
}

fn use_try(s: &str) -> Result<String, String> {
    let u = try!(Url::parse(s));
    Ok(u.host)
}

fn use_match(s: &str) -> Result<String, String> {
    return match Url::parse(s) {
        Ok(u) => Ok(u.host),
        Err(e) => Err(e)
    }
}
```

### LINKED ISSUE #20327: Use of deprecated item not propagated to macro expansion
When the `spawn` function was deprecated in favour of `std::thread::Thread::spawn`, the following program will produce a warning
```rust
fn main() {
    spawn(move|| ());
}
```
Output:
```
<anon>:11:5: 11:10 warning: use of deprecated item: use std::thread::Thread::spawn and detach instead, #[warn(deprecated)] on by default
<anon>:11     spawn(move|| ());
              ^~~~~
```
But if the same call is wrapped in a macro the warning is not emitted, as follows:
```rust
#![feature(macro_rules)]
// Short-hand macro for spawn(move|| expr)
macro_rules! go( ($e:expr) => (spawn(move|| $e)) );

fn main() {
    go!{ () };
}
```
Here it is on the [playpen](http://is.gd/Nl8hMp)

Not sure if this is a bug or not, or if the warning should be emitted, but I would have expected the same warning when the macro is "unwrapped".

### PR DESCRIPTION
**Pull request by alexcrichton**
There are a number of holes that the stability lint did not previously cover,
including:
- Types
- Bounds on type parameters on functions and impls
- Where clauses
- Imports
- Patterns (structs and enums)

These holes have all been fixed by overriding the `visit_path` function on the
AST visitor instead of a few specialized cases. This change also necessitated a
few stability changes:
- The `collections::fmt` module is now stable (it was already supposed to be).
- The `thread_local::imp::Key` type is now stable (it was already supposed to
  be).
- The `std::rt::{begin_unwind, begin_unwind_fmt}` functions are now stable.
  These are required via the `panic!` macro.
- The `std::old_io::stdio::{println, println_args}` functions are now stable.
  These are required by the `print!` and `println!` macros.
- The `ops::{FnOnce, FnMut, Fn}` traits are now `#[stable]`. This is required to
  make bounds with these traits stable. Note that manual implementations of
  these traits are still gated by default, this stability only allows bounds
  such as `F: FnOnce()`.

Closes #8962
Closes #16360
Closes #20327

### CODE REVIEW

File: src/libcore/ops.rs [hunk 1]
```diff
@@ -1119,8 +1119,7 @@ impl<'a, T: ?Sized> DerefMut for &'a mut T {
 
 /// A version of the call operator that takes an immutable receiver.
 #[lang="fn"]
-#[unstable(feature = "core",
-           reason = "uncertain about variadic generics, input versus associated types")]
+#[stable(feature = "rust1", since = "1.0.0")]
```
Comment (aturon) [inline src/libcore/ops.rs]: Uhoh. These are supposed to stay unstable, and only be usable via the `->` sugar.

File: src/librustc/middle/stability.rs [hunk 2]
```diff
@@ -304,18 +316,6 @@ pub fn check_item(tcx: &ty::ctxt, item: &ast::Item,
             let id = ast::DefId { krate: cnum, node: ast::CRATE_NODE_ID };
             maybe_do_stability_check(tcx, id, item.span, cb);
         }
-        ast::ItemTrait(_, _, ref supertraits, _) => {
```
Comment (aturon) [inline src/librustc/middle/stability.rs]: I no longer know exactly how this code is split up, but why is this being removed?

**Comment by aturon** [comment]
Nice! @alexcrichton answered my questions on IRC.

@bors: r+ 9bc0d47

**Comment by brson** [comment]
Amazing.
