### PR TITLE
Only generate closure def id for async fns with body

### LINKED ISSUE #102219: ICE with async trait in lib crate
### Code

```Rust
#![crate_type = "lib"]
#![feature(async_fn_in_trait)]
trait T {
    async fn foo();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.66.0-dev
LLVM version: 15.0.0
```

built from 4a14677239bbd9a3892d165ee24513c1a05820e4

### Error output

```
$ rustc --edition 2018 --crate-type=lib test.rs
warning: the feature `async_fn_in_trait` is incomplete and may not be safe to use and/or cause compiler crashes
 --> test.rs:2:12
  |
2 | #![feature(async_fn_in_trait)]
  |            ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

error: internal compiler error: compiler/rustc_middle/src/hir/mod.rs:127:36: No HirId for DefId(0:6 ~ test[86f1]::T::foo::{closure#0})

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
thread 'rustc' panicked at 'already borrowed: BorrowMutError', /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_data_structures/src/sync.rs:424:16

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
Aborted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ rustc --edition 2018 --crate-type=lib test.rs
warning: the feature `async_fn_in_trait` is incomplete and may not be safe to use and/or cause compiler crashes
 --> test.rs:2:12
  |
2 | #![feature(async_fn_in_trait)]
  |            ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

error: internal compiler error: compiler/rustc_middle/src/hir/mod.rs:127:36: No HirId for DefId(0:6 ~ test[86f1]::T::foo::{closure#0})

thread 'rustc' panicked at 'Box<dyn Any>', /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_errors/src/lib.rs:1496:9
stack backtrace:
   0:     0x7f5e6cba2684 - std::backtrace_rs::backtrace::libunwind::trace::h08bc92cb1ee676e7
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5e6cba2684 - std::backtrace_rs::backtrace::trace_unsynchronized::hfe4cd235bd09b0a0
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5e6cba2684 - std::sys_common::backtrace::_print_fmt::h464b5ff3b53c7357
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5e6cba2684 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc99327839ecbda74
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5e6cc48b6a - core::fmt::write::hecdcee6f8e8ab396
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f5e6cbd7731 - std::io::Write::write_fmt::hf3bf2d0ee388f134
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/io/mod.rs:1679:15
   6:     0x7f5e6cba24e9 - std::sys_common::backtrace::_print::hec2bbf6a20ac2b17
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5e6cba24e9 - std::sys_common::backtrace::print::h8deeea2b678f5da2
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5e6cb9fcb4 - std::panicking::default_hook::{{closure}}::h1f99c8e5677c70be
   9:     0x7f5e6cb9fa77 - std::panicking::default_hook::heb7289eca07b7ac0
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:286:9
  10:     0x7f5e6d5c1454 - <alloc[5e650b7de4e3e224]::boxed::Box<dyn for<'a, 'b> core[e79409e51a7a6e84]::ops::function::Fn<(&'a core[e79409e51a7a6e84]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[e79409e51a7a6e84]::marker::Send + core[e79409e51a7a6e84]::marker::Sync> as core[e79409e51a7a6e84]::ops::function::Fn<(&core[e79409e51a7a6e84]::panic::panic_info::PanicInfo,)>>::call
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/alloc/src/boxed.rs:1954:9
  11:     0x7f5e6d5c1454 - rustc_driver[4b6a05c32c788988]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_driver/src/lib.rs:1196:13
  12:     0x7f5e6cba00dd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h89daeb260a411653
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/alloc/src/boxed.rs:1954:9
  13:     0x7f5e6cba00dd - std::panicking::rust_panic_with_hook::h089d0b6f7a09daac
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:673:13
  14:     0x7f5e700ff7c3 - std[a1414b9615a53351]::panicking::begin_panic::<rustc_errors[8ca0f245d4de8edc]::ExplicitBug>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:589:9
  15:     0x7f5e700ff756 - std[a1414b9615a53351]::sys_common::backtrace::__rust_end_short_backtrace::<std[a1414b9615a53351]::panicking::begin_panic<rustc_errors[8ca0f245d4de8edc]::ExplicitBug>::{closure#0}, !>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7f5e6d57af06 - std[a1414b9615a53351]::panicking::begin_panic::<rustc_errors[8ca0f245d4de8edc]::ExplicitBug>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:588:12
  17:     0x7f5e7000ead6 - std[a1414b9615a53351]::panic::panic_any::<rustc_errors[8ca0f245d4de8edc]::ExplicitBug>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panic.rs:61:5
  18:     0x7f5e7000ea09 - <rustc_errors[8ca0f245d4de8edc]::HandlerInner>::bug::<&alloc[5e650b7de4e3e224]::string::String>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_errors/src/lib.rs:1496:9
  19:     0x7f5e7000e50a - <rustc_errors[8ca0f245d4de8edc]::Handler>::bug::<&alloc[5e650b7de4e3e224]::string::String>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_errors/src/lib.rs:981:9
  20:     0x7f5e7009578e - rustc_middle[f7f6f7926f38b54c]::util::bug::opt_span_bug_fmt::<rustc_span[753067dfc861ab74]::span_encoding::Span>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/util/bug.rs:35:34
  21:     0x7f5e7009578e - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_opt::<rustc_middle[f7f6f7926f38b54c]::util::bug::opt_span_bug_fmt<rustc_span[753067dfc861ab74]::span_encoding::Span>::{closure#0}, ()>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1996:40
  22:     0x7f5e7009578e - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context_opt::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_opt<rustc_middle[f7f6f7926f38b54c]::util::bug::opt_span_bug_fmt<rustc_span[753067dfc861ab74]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1948:22
  23:     0x7f5e7009578e - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_opt::<rustc_middle[f7f6f7926f38b54c]::util::bug::opt_span_bug_fmt<rustc_span[753067dfc861ab74]::span_encoding::Span>::{closure#0}, ()>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1996:9
  24:     0x7f5e70095869 - rustc_middle[f7f6f7926f38b54c]::util::bug::opt_span_bug_fmt::<rustc_span[753067dfc861ab74]::span_encoding::Span>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/util/bug.rs:31:5
  25:     0x7f5e6d57aef8 - rustc_middle[f7f6f7926f38b54c]::util::bug::bug_fmt
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/util/bug.rs:15:5
  26:     0x7f5e7008c4ff - rustc_middle[f7f6f7926f38b54c]::hir::provide::{closure#2}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/hir/mod.rs:127:36
  27:     0x7f5e7008c4ff - <rustc_middle[f7f6f7926f38b54c]::hir::provide::{closure#2} as core[e79409e51a7a6e84]::ops::function::FnOnce<(rustc_middle[f7f6f7926f38b54c]::ty::context::TyCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId)>>::call_once
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/core/src/ops/function.rs:251:5
  28:     0x7f5e6efb4e64 - <rustc_query_system[f89faef1a58533c3]::query::config::QueryVTable<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>>::compute
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/config.rs:45:9
  29:     0x7f5e6efb4e64 - rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:415:13
  30:     0x7f5e6efb4e64 - stacker[e8937564e9e70a52]::maybe_grow::<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>
                               at /usr/local/google/home/computerdruid/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  31:     0x7f5e6efb4e64 - rustc_data_structures[d5144205f7c5aa80]::stack::ensure_sufficient_stack::<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  32:     0x7f5e6efb4e64 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:128:17
  33:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:50
  34:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::set_tlv::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1915:9
  35:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:9
  36:     0x7f5e6efb4e64 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:127:13
  37:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1975:13
  38:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1959:40
  39:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context_opt::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1948:22
  40:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1959:9
  41:     0x7f5e6efb4e64 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>::{closure#0}, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1972:9
  42:     0x7f5e6efb4e64 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:112:9
  43:     0x7f5e6efb4e64 - rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:414:22
  44:     0x7f5e6efb4e64 - rustc_query_system[f89faef1a58533c3]::query::plumbing::try_execute_query::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_query_system[f89faef1a58533c3]::query::caches::DefaultCache<rustc_span[753067dfc861ab74]::def_id::LocalDefId, rustc_hir[cca3f2cba2ebe3ef]::hir_id::HirId>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:373:44
  45:     0x7f5e6f0b1944 - rustc_query_system[f89faef1a58533c3]::query::plumbing::get_query::<rustc_query_impl[911456358a4e6111]::queries::local_def_id_to_hir_id, rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  46:     0x7f5e6f20d3f1 - <rustc_query_impl[911456358a4e6111]::Queries as rustc_middle[f7f6f7926f38b54c]::ty::query::QueryEngine>::local_def_id_to_hir_id::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:642:17
  47:     0x7f5e6f20d3f1 - <rustc_query_impl[911456358a4e6111]::Queries as rustc_middle[f7f6f7926f38b54c]::ty::query::QueryEngine>::local_def_id_to_hir_id
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/lib.rs:54:1
  48:     0x7f5e6ff785f8 - <rustc_middle[f7f6f7926f38b54c]::ty::query::TyCtxtAt>::local_def_id_to_hir_id
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/query.rs:261:17
  49:     0x7f5e6ff785f8 - <rustc_middle[f7f6f7926f38b54c]::ty::context::TyCtxt>::local_def_id_to_hir_id
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/query.rs:242:17
  50:     0x7f5e6ff785f8 - <rustc_middle[f7f6f7926f38b54c]::hir::map::Map>::local_def_id_to_hir_id
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/hir/map/mod.rs:199:9
  51:     0x7f5e6ff785f8 - <rustc_middle[f7f6f7926f38b54c]::hir::map::Map>::opt_def_kind
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/hir/map/mod.rs:204:22
  52:     0x7f5e6efc0754 - <rustc_query_system[f89faef1a58533c3]::query::config::QueryVTable<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>>::compute
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/config.rs:45:9
  53:     0x7f5e6efc0754 - rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:415:13
  54:     0x7f5e6efc0754 - stacker[e8937564e9e70a52]::maybe_grow::<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>
                               at /usr/local/google/home/computerdruid/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  55:     0x7f5e6efc0754 - rustc_data_structures[d5144205f7c5aa80]::stack::ensure_sufficient_stack::<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  56:     0x7f5e6efc0754 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:128:17
  57:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:50
  58:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::set_tlv::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1915:9
  59:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:9
  60:     0x7f5e6efc0754 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:127:13
  61:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1975:13
  62:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1959:40
  63:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context_opt::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1948:22
  64:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_context::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1959:9
  65:     0x7f5e6efc0754 - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::with_related_context::<<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>::{closure#0}, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1972:9
  66:     0x7f5e6efc0754 - <rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt as rustc_query_system[f89faef1a58533c3]::query::QueryContext>::start_query::<core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>, rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:112:9
  67:     0x7f5e6efc0754 - rustc_query_system[f89faef1a58533c3]::query::plumbing::execute_job::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:414:22
  68:     0x7f5e6efc0754 - rustc_query_system[f89faef1a58533c3]::query::plumbing::try_execute_query::<rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt, rustc_query_system[f89faef1a58533c3]::query::caches::DefaultCache<rustc_span[753067dfc861ab74]::def_id::DefId, core[e79409e51a7a6e84]::option::Option<rustc_hir[cca3f2cba2ebe3ef]::def::DefKind>>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:373:44
  69:     0x7f5e6f08b089 - rustc_query_system[f89faef1a58533c3]::query::plumbing::get_query::<rustc_query_impl[911456358a4e6111]::queries::opt_def_kind, rustc_query_impl[911456358a4e6111]::plumbing::QueryCtxt>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  70:     0x7f5e6f244e73 - <rustc_query_impl[911456358a4e6111]::Queries as rustc_middle[f7f6f7926f38b54c]::ty::query::QueryEngine>::opt_def_kind::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/plumbing.rs:642:17
  71:     0x7f5e6f244e73 - <rustc_query_impl[911456358a4e6111]::Queries as rustc_middle[f7f6f7926f38b54c]::ty::query::QueryEngine>::opt_def_kind
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_query_impl/src/lib.rs:54:1
  72:     0x7f5e6f714b91 - <rustc_middle[f7f6f7926f38b54c]::ty::query::TyCtxtAt>::opt_def_kind::<rustc_span[753067dfc861ab74]::def_id::LocalDefId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/query.rs:261:17
  73:     0x7f5e6f714b91 - <rustc_middle[f7f6f7926f38b54c]::ty::context::TyCtxt>::opt_def_kind::<rustc_span[753067dfc861ab74]::def_id::LocalDefId>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/query.rs:242:17
  74:     0x7f5e6f714b91 - <rustc_metadata[5288cfe7de089828]::rmeta::encoder::EncodeContext>::encode_def_ids
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:1084:28
  75:     0x7f5e6f714b91 - <rustc_metadata[5288cfe7de089828]::rmeta::encoder::EncodeContext>::encode_crate_root::{closure#15}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:603:13
  76:     0x7f5e6f714b91 - <rustc_metadata[5288cfe7de089828]::rmeta::encoder::EncodeContext>::encode_crate_root
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:602:13
  77:     0x7f5e6f725750 - rustc_metadata[5288cfe7de089828]::rmeta::encoder::encode_metadata_impl
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:2184:16
  78:     0x7f5e6f7543a0 - rustc_metadata[5288cfe7de089828]::rmeta::encoder::encode_metadata::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:2135:12
  79:     0x7f5e6f7543a0 - rustc_data_structures[d5144205f7c5aa80]::sync::join::<rustc_metadata[5288cfe7de089828]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[5288cfe7de089828]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_data_structures/src/sync.rs:117:14
  80:     0x7f5e6f724d25 - rustc_metadata[5288cfe7de089828]::rmeta::encoder::encode_metadata
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/rmeta/encoder.rs:2134:5
  81:     0x7f5e6f754a3a - rustc_metadata[5288cfe7de089828]::fs::encode_and_write_metadata
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_metadata/src/fs.rs:84:13
  82:     0x7f5e6d6d68ca - rustc_interface[78e4e26cf3902cb5]::passes::start_codegen
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/passes.rs:985:9
  83:     0x7f5e6d6d970d - <rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/queries.rs:252:20
  84:     0x7f5e6d6d970d - <rustc_interface[78e4e26cf3902cb5]::passes::QueryContext>::enter::<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/passes.rs:770:42
  85:     0x7f5e6d6d970d - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_interface[78e4e26cf3902cb5]::passes::QueryContext>::enter<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:50
  86:     0x7f5e6d6d970d - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::set_tlv::<rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context<<rustc_interface[78e4e26cf3902cb5]::passes::QueryContext>::enter<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1915:9
  87:     0x7f5e6d6d970d - rustc_middle[f7f6f7926f38b54c]::ty::context::tls::enter_context::<<rustc_interface[78e4e26cf3902cb5]::passes::QueryContext>::enter<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_middle/src/ty/context.rs:1931:9
  88:     0x7f5e6d6d970d - <rustc_interface[78e4e26cf3902cb5]::passes::QueryContext>::enter::<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e79409e51a7a6e84]::result::Result<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/passes.rs:770:9
  89:     0x7f5e6d770e5e - <rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/queries.rs:243:13
  90:     0x7f5e6d770e5e - <rustc_interface[78e4e26cf3902cb5]::queries::Query<alloc[5e650b7de4e3e224]::boxed::Box<dyn core[e79409e51a7a6e84]::any::Any>>>::compute::<<rustc_interface[78e4e26cf3902cb5]::queries::Queries>::ongoing_codegen::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/queries.rs:38:28
  91:     0x7f5e6d6515e7 - rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}::{closure#2}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_driver/src/lib.rs:409:13
  92:     0x7f5e6d6515e7 - <rustc_interface[78e4e26cf3902cb5]::interface::Compiler>::enter::<rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}::{closure#2}, core[e79409e51a7a6e84]::result::Result<core[e79409e51a7a6e84]::option::Option<rustc_interface[78e4e26cf3902cb5]::queries::Linker>, rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/queries.rs:377:19
  93:     0x7f5e6d5d8297 - rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_driver/src/lib.rs:317:22
  94:     0x7f5e6d5d8297 - rustc_interface[78e4e26cf3902cb5]::interface::create_compiler_and_run::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#1}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/interface.rs:323:13
  95:     0x7f5e6d5d8297 - rustc_span[753067dfc861ab74]::with_source_map::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_interface[78e4e26cf3902cb5]::interface::create_compiler_and_run<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#1}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_span/src/lib.rs:1000:5
  96:     0x7f5e6d652352 - rustc_interface[78e4e26cf3902cb5]::interface::create_compiler_and_run::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/interface.rs:317:5
  97:     0x7f5e6d6323cf - rustc_interface[78e4e26cf3902cb5]::interface::run_compiler::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/interface.rs:339:12
  98:     0x7f5e6d6323cf - <scoped_tls[e75645493ea96cd]::ScopedKey<rustc_span[753067dfc861ab74]::SessionGlobals>>::set::<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  99:     0x7f5e6d637859 - rustc_span[753067dfc861ab74]::create_session_globals_then::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_span/src/lib.rs:112:5
 100:     0x7f5e6d637859 - rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals::<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/compiler/rustc_interface/src/util.rs:159:32
 101:     0x7f5e6d637859 - std[a1414b9615a53351]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys_common/backtrace.rs:122:18
 102:     0x7f5e6d5b5511 - <std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_::<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/thread/mod.rs:514:17
 103:     0x7f5e6d5b5511 - <core[e79409e51a7a6e84]::panic::unwind_safe::AssertUnwindSafe<<std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[e79409e51a7a6e84]::ops::function::FnOnce<()>>::call_once
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/core/src/panic/unwind_safe.rs:271:9
 104:     0x7f5e6d5b5511 - std[a1414b9615a53351]::panicking::try::do_call::<core[e79409e51a7a6e84]::panic::unwind_safe::AssertUnwindSafe<<std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:464:40
 105:     0x7f5e6d5b5511 - std[a1414b9615a53351]::panicking::try::<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, core[e79409e51a7a6e84]::panic::unwind_safe::AssertUnwindSafe<<std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panicking.rs:428:19
 106:     0x7f5e6d5af11e - std[a1414b9615a53351]::panic::catch_unwind::<core[e79409e51a7a6e84]::panic::unwind_safe::AssertUnwindSafe<<std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/panic.rs:137:14
 107:     0x7f5e6d5af11e - <std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_::<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/thread/mod.rs:513:30
 108:     0x7f5e6d5af11e - <<std[a1414b9615a53351]::thread::Builder>::spawn_unchecked_<rustc_interface[78e4e26cf3902cb5]::util::run_in_thread_pool_with_globals<rustc_interface[78e4e26cf3902cb5]::interface::run_compiler<core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>, rustc_driver[4b6a05c32c788988]::run_compiler::{closure#1}>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#0}, core[e79409e51a7a6e84]::result::Result<(), rustc_errors[8ca0f245d4de8edc]::ErrorGuaranteed>>::{closure#1} as core[e79409e51a7a6e84]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/core/src/ops/function.rs:251:5
 109:     0x7f5e6cbe0fb8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h980b2d98c4c8d894
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/alloc/src/boxed.rs:1940:9
 110:     0x7f5e6cbe0fb8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h089a8c90b0dbdb8e
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/alloc/src/boxed.rs:1940:9
 111:     0x7f5e6cb93137 - std::sys::unix::thread::Thread::new::thread_start::h9161e73d418528e8
                               at /usr/local/google/home/computerdruid/extra_data/rust/afit_ctii/rust/library/std/src/sys/unix/thread.rs:108:17
 112:     0x7f5e675efd80 - start_thread
                               at ./nptl/./nptl/pthread_create.c:481:8
 113:     0x7f5e6ca11baf - __GI___clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 114:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
[snipped: too long and probably boring]

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
Aborted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #102219

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/item.rs [hunk 1]
```diff
@@ -1050,9 +1050,9 @@ impl<'hir> LoweringContext<'_, 'hir> {
         asyncness: Async,
         body: Option<&Block>,
     ) -> hir::BodyId {
-        let closure_id = match asyncness {
-            Async::Yes { closure_id, .. } => closure_id,
-            Async::No => return self.lower_fn_body_block(span, decl, body),
+        let (closure_id, body) = match (asyncness, body) {
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/item.rs:1053]: This means that when a (non-trait) fn is lacking a body, we lower it to `<ExprKind::Err>` instead of like... ```async { <ExprKind::Err> }```

File: compiler/rustc_resolve/src/def_collector.rs [hunk 2]
```diff
@@ -148,8 +148,13 @@ impl<'a, 'b> visit::Visitor<'a> for DefCollector<'a, 'b> {
...
                     this.visit_fn_ret_ty(&sig.decl.output)
                 });
-                let closure_def = self.create_def(closure_id, DefPathData::ClosureExpr, span);
-                self.with_parent(closure_def, |this| walk_list!(this, visit_block, body));
+                // If this async fn has no body (i.e. it's an async fn signature in a trait)
+                // then the closure_def will never be used, and we should avoid generating a
+                // def-id for it.
+                if body.is_some() {
+                    let closure_def = self.create_def(closure_id, DefPathData::ClosureExpr, span);
+                    self.with_parent(closure_def, |this| walk_list!(this, visit_block, body));
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/def_collector.rs:156]: Could you use an `if let Some` and avoid the `walk_list` here?

**Review by cjgillot — COMMENTED** [review]
One nit and r=me.
