### PR TITLE
don't show the full linker args unless `--verbose` is passed

### LINKED ISSUE #109979: Hide .o files in linker errors by default
### Code

```diff
diff --git a/src/bootstrap/builder.rs b/src/bootstrap/builder.rs
index 4d528a767e4..0833418a91e 100644
--- a/src/bootstrap/builder.rs
+++ b/src/bootstrap/builder.rs
@@ -1629,6 +1636,11 @@ pub fn cargo(
             SplitDebuginfo::Off => rustflags.arg("-Csplit-debuginfo=off"),
         };
 
+        // Decrease the size of the debuginfo we generate. zlib has incomplete support on some
+        // platforms, but that's ok because `thorin` can read it and we don't ship debuginfo to
+        // users.
+        rustflags.arg("-Clink-args=-Wl,--compress-debug-sections=zlib");
+
         if self.config.cmd.bless() {
             // Bless `expect!` tests.
             cargo.env("UPDATE_EXPECT", "1");
```

### Current output

```Shell
; x b
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.16s
Building stage0 library artifacts (aarch64-apple-darwin) 
   Compiling std v0.0.0 (/Users/jyn/src/rust/library/std)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/aarch64-apple-darwin/bin:/opt/homebrew/opt/llvm/bin:/Users/jyn/.local/bin:/Users/jyn/.local/lib/cargo/bin:/Users/jyn/src/dotfiles/bin:/Users/jyn/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/munki:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/opt/llvm/bin:/Users/jyn/.local/bin:/Users/jyn/.local/lib/cargo/bin:/Users/jyn/src/dotfiles/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-Wl,-exported_symbols_list,/var/folders/0c/cvw1ywdj5c3b73kt13g4svyw0000gr/T/rustcmSzQgQ/list" "-arch" "arm64" "/var/folders/0c/cvw1ywdj5c3b73kt13g4svyw0000gr/T/rustcmSzQgQ/symbols.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.10txvr9rcuz3kaqm.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.10wr2b3718zvsr7t.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.13j7f8dnmka8ni41.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.13v7tl2dv3qdrwkt.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.14yee3zy8o9bn84j.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.15dnb45f1xc1j4fs.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.15kevokol0k8v9qh.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.15okjf6p15cf7h8i.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.16g8kkbl9brhojw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.16hbhj2ti9183z97.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.17gs5l82a34ocm0l.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.189dlqlvnpnm6y3n.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.18amxug9fhkf286e.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1a9j3679zjc9dx90.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1abscviyi22z0w99.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1adgooziyz9ksxmy.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1b4xtgpgqitluh2t.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1dnsa9nbfh2ma5vi.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1dr56wwx4x3wqe1u.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1e6utjyp0x7z6jxx.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1f2p3wsrhws34qti.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1f73kwxreosqw3sx.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1f9hcmotuzwm21fe.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1hobr2bu244m7b16.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1i9uc1edo4tytbxw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1jam2zsj5q2nlpcr.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1jyms3gmxws62hgb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1k1hbfwtb55fauwe.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1kkbc7uqyz8pi1jl.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1kqprrjlceetk30w.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1l87lccvptgow2yz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1lcluq4p4uteb1y9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1lkynayrq1n1xxvd.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1ln1uk30eg6yfnb7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1mxokc3xbw4cnv8f.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1nl30j85f9oryok0.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1oxcw89yff6k61li.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1p58nr8qqbyvw004.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1pfcwaxw1jmo4ypw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1pki2jwfijqpnjsn.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1qqtpy0efdxtbxd9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1qwcpforon0sjaop.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1rjya15qludv5m07.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1rkbd7oraffqdzxa.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1s2quk5zxaglfa3o.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1scajmxmarymp0sl.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1vszn6r7sbkya88x.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1wbjzyciyoz0v22l.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1wmc67a20xtri9fn.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1xbeghb22qdgg9bd.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1yay3awvetbol23y.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1yldxeylz1bh089c.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.1yrdnwe98xbrrs79.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.20veq3xn4dctwl1z.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2267km76uot6m0mu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.227xprm27y74qrzg.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.22e9d7j6hnq5xs2d.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.22hkst4xqtpjd6kp.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.22sp26hq8imjs10n.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.23b6otxkgzguq19g.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.248bs2kqa9ln5at1.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.24a5d1dqem3jpdvb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.24feslj86zortaa2.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2612uxbk46rjurnp.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.28ojuavfpf1o53yk.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.291z9un0fknyjfpe.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2avgezulzoyjd9e2.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2e24qg8kcdqx8etw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2eec5p159ty7556c.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2em4dti4vea9ha41.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2g2vxp8c6i2oxdz6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2gf4dfrjstcgcyc7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2gwlxfkl6f2ezpj8.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2hzond9iuulpv5bt.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2idaf6t4cszyfl25.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2iqv9zgss48uaem8.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2kp1hiohth77dap4.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2lb19ou1p3pi32z9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2lybw0y4o1tyjls1.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2m540am8ekggr9ik.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2on5srverf3ewwg9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2q7pu8zxg1ust73g.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2qa2nc4rjlnfpesr.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2s3kx9ojawuig43t.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2thohofouocbwls1.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2v49gk7v65pdbiwu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2x4v62yekncgigre.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2xl9ehvg8md0rj2q.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2yf73ax4ce0lx1vi.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.2yftsqqjeabye1eo.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.30hh3351he2pupxc.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.31j2m964m7sr6s5p.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.31kjfz2t64mf8oxv.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.321mmp1nbfqgjeuc.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.33n251lcgx8asak2.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.33uzyctd7vns7sjs.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.34w8rswutv1f3v3b.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.35e7ugp2pift597q.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.35ni8m84dbpax6w.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.367ezpripypo5ic4.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.36iw5mpkrg1618gf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.36r9rgwd7gttyw4b.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3767bb1ur35xoayu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.37h837qt7gtyunmz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.38i5l8j81kamjf3a.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.39ippc1amiokobc9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3a12ab2d1nq9so2f.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3b0pyiegddvb0f1w.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3dbhk0cecimhzq8v.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3dlghr1ql6bd5sdu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3f4wrjtc36bq1rnf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3fom5jou7g0visvh.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3fuzvr2i5r1un9nn.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3g3y6z9213l1ad43.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3g96bw9jt2flrvuu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3gjla5y83wfu10uf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3hr1s4t0f9sbi9iz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3hwvx1ydnjp12ema.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3ic8it3d5n11qmp3.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3jf67g1ru9mumz9w.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3jmlx16eeo98i4d6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3k7alljhhjw56n2v.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3kq2ebd6ky6jesu8.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3ksc9ptk2v09xjyp.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3kv1vop0zr24q3ep.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3l61j3hyomtynbme.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3lwbluldcvo14ipe.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3m01me0174x0czjx.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3npho1xt7ve92k08.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3ojqpxs90blfrqqv.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3ptqah06zrrwg1hu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3qw0olje31aaf8ts.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3sga9zpb6bqxcmo5.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3spmngmcnf8u2nof.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3tje1pv6r2vzlg6s.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3tuyn6zhjrncnewb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3uyxkdkt8udmytmc.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3vet77wx4xp4hvjj.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3wt6d3c54yqtwfkk.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3xcw8awh3645ftvy.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3y4tkleixe0l7fgz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3zlf6wk5myrbwu1h.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.401hfu9mjq0m0q92.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.416z94w01n6zd3ad.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.42yjt0lmdziw6or.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4301pdksxjwop9df.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.44xxy6c42secrn41.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.458vg7yfd5hhbdmj.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.45fz9fi7d0383g7g.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.47cqocaqlyjcu469.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.48pmfvxz8yy5q8it.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.49n4rl7lx6uezb2h.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.49viwlv5hxeq5fpe.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4ampvg97jy0bmvj7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4an2fxlua06b5c6h.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4c2il7hqov9idyxm.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4ca7hhawglzq4pfw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4cd8mjmnpfqvdn1i.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4cx0642bbkb4k3wm.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4dmo7xebwi9by075.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4e0xv02xfnw2p436.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4gqy29a41o1eixxb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4ixtfxgdqg8hr5fn.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4jwp8o890juoo3fz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4k0xm0flex7ks4nf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4kb08n2dqbj584q0.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4kpegb11384ogjr7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4kvof5exwevh7zn7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4mvuw7miiukvqcjx.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4nmup70czb7i09xb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4p2mbqqdupmt5wxp.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4p6wgojkgusz6kwo.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4p7vv0giae8sg4sa.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4pe4a33mo2m1c7mj.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4ptl95xj5svjp68r.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4pzowf51w2kad1m.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4qgutg75eeswshev.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4rdyrvjfpqo30as3.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4sv534jbvgco9o1t.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4t5es8e01py5218x.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4t7r53gdwduy408h.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4u5knuz6rfqi3jno.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4ugvbb0pvjpicy5t.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4w3puxsd93wlpvr3.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4yb17uslax51avf0.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4yn3dpsl1a762yv7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.50fw51e4c30z68zy.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.50nxm8lly0orn26s.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.511wewgqyj7h712n.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.512a36qprzakqh95.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.51b3xm5xx2ua5kcr.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.51ncf8xg3d4ha3q6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.52ndyv2a44qin4w7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.53iv1n5x0d8qzgl2.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.53pfbtlupkvn02by.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.54yfndmnxdvl2kjn.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.559tchldnypd8n70.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.56afxpu2vo9zzowa.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.56q0vuc9ovs25yu6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.57yj31b4u1suieo7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.58wxlqajtaluu2gb.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5928rgoqd4vdexio.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.59i6l17os96grxyd.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5bbwif44ma3tom7e.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5bqpp9vdhf830itq.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5d13jipaa53eook5.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5deo5la7eqiosk18.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5dl5k5hxjsqfly2c.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5f52vvumua71wbw2.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5ftjiky69a6tusqf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5gjau6xemib38x4f.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5gs8poz300qxylkp.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5w58jfa9sbpqme9.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5x8c4avyw3femok.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.5xrh8r267mlxloq.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.6gsygeqppyemu6i.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.6hbmt7tkyy7qtal.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.7u53qkmv87lfb3h.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.94v9074ma7l7ndy.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.9quw1fhs44s8ng4.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.9u9yn3vsekzd6ku.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.9wgbz3vp2yov6f6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.9xs1nzx9wgwoobz.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.akuf18ll7884cbf.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.b64byvgjwlrafu1.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.bxgwz3v2g7vdbhv.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.cdalol3epyu19ra.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.cmbhflodj58s2v6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.d2m3ohg8tituth8.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.epmlbtab8a7aik6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.eqsl28eswoid3vy.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.g399ewawxqp4kv6.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.h4i8pljn8ulmqqu.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.h8f2j4z6ime3tbt.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.hq7w3nj51866bbw.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.i2wieh12dtii10d.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.i8pkcfxtnf97t6i.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.n0zcqjopd4q1fyq.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.ngafyc5expxpo5r.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.nmu9qcjri8oof44.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.o7orti0vligig3n.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.oufi6xweyt6qxdx.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.oy3wxjfqy6jy571.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.q0j7p175f1jy73m.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.q9yflgf97wr6k03.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.qtnxuiwtrrt3nys.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.ufp24v4btqpwtzj.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.ulrsvhssno73l7w.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.v0fso98kjwimypj.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.vg652s8dkzb6zlc.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.z6nvq1uo6qmwaa7.rcgu.o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.4kr4mmlwvy6ne8bn.rcgu.rmeta" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/std-53552890d169e062.3oepu8z6j3lt27qr.rcgu.o" "-L" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps" "-L" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/release/deps" "-L" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/build/compiler_builtins-1bf5aed12986a8b0/out" "-L" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/aarch64-apple-darwin/lib" "-lSystem" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libpanic_unwind-95266ce3fdfb3785.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libobject-41164df430139472.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libmemchr-9867f6855a548535.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libaddr2line-9cbbff6f398afddf.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libgimli-0f0ae58b9990c06b.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/librustc_demangle-73c7e3fda35028ee.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libstd_detect-d4f7a26fe562f8b5.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libhashbrown-0f15e95245352c4d.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libminiz_oxide-68ee8b28523fca87.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libadler-3fb9067b8569954f.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/librustc_std_workspace_alloc-932b460b3eb7ab2b.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libunwind-0d8354083d31352e.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libcfg_if-869bcd29e1598010.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/liblibc-958a1db99e630773.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/liballoc-a625814a3e4ebeb6.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/librustc_std_workspace_core-4f7623180a9a790d.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libcore-1dc383b6cde1e4a6.rlib" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libcompiler_builtins-7f4c976204452ce6.rlib" "-lc" "-lm" "-L" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libstd-53552890d169e062.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-Wl,-install_name,@rpath/libstd-53552890d169e062.dylib" "-nodefaultlibs" "-Wl,-rpath,@loader_path/../lib" "-Wl,--compress-debug-sections=zlib"
  = note: ld: unknown option: --compress-debug-sections=zlib
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `std` due to previous error
```

### Desired output

```Shell
; x b
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.16s
Building stage0 library artifacts (aarch64-apple-darwin) 
   Compiling std v0.0.0 (/Users/jyn/src/rust/library/std)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,-exported_symbols_list,/var/folders/0c/cvw1ywdj5c3b73kt13g4svyw0000gr/T/rustcmSzQgQ/list" "-arch" "arm64" "-lSystem" "-lc" "-lm" "-o" "/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-std/aarch64-apple-darwin/release/deps/libstd-53552890d169e062.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-Wl,-install_name,@rpath/libstd-53552890d169e062.dylib" "-nodefaultlibs" "-Wl,-rpath,@loader_path/../lib" "-Wl,--compress-debug-sections=zlib" # ...
  = note: 300 object files or directories omitted; run with -v to show all
  = note: some env variables omitted; run with -v to show all
  = note: ld: unknown option: --compress-debug-sections=zlib
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `std` due to previous error
```

### Rationale and extra context

Showing so many .o files is overwhelming and unhelpful. In the vast majority of cases, the exact object files and directories don't matter and showing the options passed to the linker is enough. It would be nice to hide them by default and only show them if the user explicitly opts-in.

### Other cases

_No response_

### Anything else?

HEAD is branched from 90a9f69c80812c8694959c1f2d5c336e3300d1e2.

### PR DESCRIPTION
**Pull request by jyn514**
the linker arguments can be *very* long, especially for crates with many dependencies. often they are not useful. omit them unless the user specifically requests them.

split out from https://github.com/rust-lang/rust/pull/119286. fixes https://github.com/rust-lang/rust/issues/109979.

r? @bjorn3

try-build: i686-mingw

### CODE REVIEW

**Comment by jyn514** [comment]
hmm. i have just remembered response files exist (https://github.com/rust-lang/rust/issues/109979#issuecomment-1958353504). maybe that would be better, so that the linker options are always still shown? and —verbose would print the contents of the response file but otherwise have no effect?

**Comment by bjorn3** [comment]
Aren't the response files deleted even after a failed link?

**Comment by jyn514** [comment]
possibly! also using a response file for some arguments but not others seems complicated lol

**Comment by jyn514** [comment]
> Aren't the response files deleted even after a failed link?

yes, you are correct. they use a tempdir that's autoremoved unless you use -C save-temps. https://github.com/rust-lang/rust/blob/fe9f2722a04346c1aa7cba8ca49169242393fdc1/compiler/rustc_codegen_ssa/src/back/link.rs#L105

we're the compiler though, so we have access to that file before it's deleted.

**Comment by jyn514** [comment]
> using a response file for some arguments but not others seems complicated lol

oh god ok so i looked into how much work this would be and the answer is. a lot. we do not store the linker arguments in a Vec, we put them directly into a Command, and the order of the arguments is extremely important. so either we would need a separate fake Command that we pass into all the Linker implementations, or we'd need to refactor the trait so it only gives a Vec<String> instead of a command. both of those sound annoying and i would rather not do that here, i do not think in practice it will be common to need to see the linker arguments *and* be unable to pass --verbose.

**Comment by bjorn3** [comment]
Looks like the following is enough to avoid object files from showing up while printing the rest. It is easy to extend this to rlibs too. I'm going to try to see if I can adapt it to get a good balance between compactness and showing useful information.

```diff
diff --git a/compiler/rustc_codegen_ssa/src/back/link.rs b/compiler/rustc_codegen_ssa/src/back/link.rs
index 487ef3f88a8..45fafd2321a 100644
--- a/compiler/rustc_codegen_ssa/src/back/link.rs
+++ b/compiler/rustc_codegen_ssa/src/back/link.rs
@@ -1001,7 +1001,7 @@ fn is_illegal_instruction(_status: &ExitStatus) -> bool {
                 let err = errors::LinkingFailed {
                     linker_path: &linker_path,
                     exit_status: prog.status,
-                    command: &cmd,
+                    command: cmd,
                     escaped_output,
                     verbose: sess.opts.verbose,
                 };
diff --git a/compiler/rustc_codegen_ssa/src/errors.rs b/compiler/rustc_codegen_ssa/src/errors.rs
index 2dfebf3e8f0..1469e0413e7 100644
--- a/compiler/rustc_codegen_ssa/src/errors.rs
+++ b/compiler/rustc_codegen_ssa/src/errors.rs
@@ -347,13 +347,13 @@ fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
 pub(crate) struct LinkingFailed<'a> {
     pub linker_path: &'a PathBuf,
     pub exit_status: ExitStatus,
-    pub command: &'a Command,
+    pub command: Command,
     pub escaped_output: String,
     pub verbose: bool,
 }
 
 impl<G: EmissionGuarantee> Diagnostic<'_, G> for LinkingFailed<'_> {
-    fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
+    fn into_diag(mut self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
         let mut diag = Diag::new(dcx, level, fluent::codegen_ssa_linking_failed);
         diag.arg("linker_path", format!("{}", self.linker_path.display()));
         diag.arg("exit_status", format!("{}", self.exit_status));
@@ -363,7 +363,15 @@ fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
         if self.verbose {
             diag.note(format!("{:?}", self.command));
         } else {
-            diag.note("use `--verbose` to show all linker arguments");
+            // Omit rust object files in the error by default to make linker errors a bit less
+            // verbose.
+            let mut args = self.command.take_args();
+            args.retain(|arg| !arg.as_encoded_bytes().ends_with(b".rcgu.o"));
+            self.command.args(args);
+            self.command.arg("<some object files omitted>");
+
+            diag.note(format!("{:?}", self.command));
+            diag.note("some arguments are omitted. use `--verbose` to show all linker arguments");
         }
 
         diag.note(self.escaped_output);
```

**Comment by bjorn3** [comment]
The following also folds rlib arguments to omit the common paths:

error: linking with `/bin/false` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/gh-bjorn3/rust/build/aarch64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/bin:/home/gh-bjorn3/.local/bin:/home/gh-bjorn3/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "/bin/false" "/tmp/rustcqUWvwy/symbols.o" "<2 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/home/gh-bjorn3/rust/build/aarch64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib/{libstd-c298d88188ee915f.rlib,libpanic_unwind-a10c1edfcf7c40ad.rlib,libobject-670602f4a4a0700b.rlib,libmemchr-002d5b70217fdab9.rlib,libaddr2line-b10ed1ee0775d1a7.rlib,libgimli-8ec0a4584c0db3e8.rlib,librustc_demangle-fdbaf6b5c23ed63d.rlib,libstd_detect-c886b7c11c6f80e0.rlib,libhashbrown-d682722822e656f5.rlib,librustc_std_workspace_alloc-ed5742d84e315598.rlib,libminiz_oxide-7d81ee9b8a4ad220.rlib,libadler-8dd7f69390baefd4.rlib,libunwind-90a9a4da96723235.rlib,libcfg_if-3fa0aef5e1654966.rlib,liblibc-644549e6e4fc9b45.rlib,liballoc-6c3106e0de272f45.rlib,librustc_std_workspace_core-c603386b60e50955.rlib,libcore-f28b39bac25306f7.rlib,libcompiler_builtins-2b4a04f0fe654523.rlib}" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/gh-bjorn3/rust/build/aarch64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "rust_out" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: 

<details><summary>The diff</summary>

```diff
diff --git a/compiler/rustc_codegen_ssa/src/back/link.rs b/compiler/rustc_codegen_ssa/src/back/link.rs
index 487ef3f88a8..45fafd2321a 100644
--- a/compiler/rustc_codegen_ssa/src/back/link.rs
+++ b/compiler/rustc_codegen_ssa/src/back/link.rs
@@ -1001,7 +1001,7 @@ fn is_illegal_instruction(_status: &ExitStatus) -> bool {
                 let err = errors::LinkingFailed {
                     linker_path: &linker_path,
                     exit_status: prog.status,
-                    command: &cmd,
+                    command: cmd,
                     escaped_output,
                     verbose: sess.opts.verbose,
                 };
diff --git a/compiler/rustc_codegen_ssa/src/errors.rs b/compiler/rustc_codegen_ssa/src/errors.rs
index 2dfebf3e8f0..c1f104e1010 100644
--- a/compiler/rustc_codegen_ssa/src/errors.rs
+++ b/compiler/rustc_codegen_ssa/src/errors.rs
@@ -1,6 +1,7 @@
 //! Errors emitted by codegen_ssa
 
 use std::borrow::Cow;
+use std::ffi::OsString;
 use std::io::Error;
 use std::num::ParseIntError;
 use std::path::{Path, PathBuf};
@@ -345,15 +346,15 @@ fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
 }
 
 pub(crate) struct LinkingFailed<'a> {
-    pub linker_path: &'a PathBuf,
+    pub linker_path: &'a Path,
     pub exit_status: ExitStatus,
-    pub command: &'a Command,
+    pub command: Command,
     pub escaped_output: String,
     pub verbose: bool,
 }
 
 impl<G: EmissionGuarantee> Diagnostic<'_, G> for LinkingFailed<'_> {
-    fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
+    fn into_diag(mut self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
         let mut diag = Diag::new(dcx, level, fluent::codegen_ssa_linking_failed);
         diag.arg("linker_path", format!("{}", self.linker_path.display()));
         diag.arg("exit_status", format!("{}", self.exit_status));
@@ -363,7 +364,61 @@ fn into_diag(self, dcx: DiagCtxtHandle<'_>, level: Level) -> Diag<'_, G> {
         if self.verbose {
             diag.note(format!("{:?}", self.command));
         } else {
-            diag.note("use `--verbose` to show all linker arguments");
+            enum ArgGroup {
+                Regular(OsString),
+                Objects(usize),
+                Rlibs(PathBuf, Vec<OsString>),
+            }
+
+            // Omit rust object files and fold rlibs in the error by default to make linker errors a
+            // bit less verbose.
+            let orig_args = self.command.take_args();
+            let mut args: Vec<ArgGroup> = vec![];
+            for arg in orig_args {
+                if arg.as_encoded_bytes().ends_with(b".rcgu.o") {
+                    if let Some(ArgGroup::Objects(n)) = args.last_mut() {
+                        *n += 1;
+                    } else {
+                        args.push(ArgGroup::Objects(1));
+                    }
+                } else if arg.as_encoded_bytes().ends_with(b".rlib") {
+                    let rlib_path = Path::new(&arg);
+                    let dir = rlib_path.parent().unwrap();
+                    let filename = rlib_path.file_name().unwrap().to_owned();
+                    if let Some(ArgGroup::Rlibs(parent, rlibs)) = args.last_mut() {
+                        if parent == dir {
+                            rlibs.push(filename);
+                        } else {
+                            args.push(ArgGroup::Rlibs(dir.to_owned(), vec![filename]));
+                        }
+                    } else {
+                        args.push(ArgGroup::Rlibs(dir.to_owned(), vec![filename]));
+                    }
+                } else {
+                    args.push(ArgGroup::Regular(arg));
+                }
+            }
+            self.command.args(args.into_iter().map(|arg_group| match arg_group {
+                ArgGroup::Regular(arg) => arg,
+                ArgGroup::Objects(n) => OsString::from(format!("<{n} object files omitted>")),
+                ArgGroup::Rlibs(dir, rlibs) => {
+                    let mut arg = dir.into_os_string();
+                    arg.push("/{");
+                    let mut first = true;
+                    for rlib in rlibs {
+                        if !first {
+                            arg.push(",");
+                        }
+                        first = false;
+                        arg.push(rlib);
+                    }
+                    arg.push("}");
+                    arg
+                }
+            }));
+
+            diag.note(format!("{:?}", self.command));
+            diag.note("some arguments are omitted. use `--verbose` to show all linker arguments");
         }
 
         diag.note(self.escaped_output);
```

</details>

File: compiler/rustc_codegen_ssa/src/errors.rs [hunk 1]
```diff
@@ -345,21 +346,82 @@ impl<G: EmissionGuarantee> Diagnostic<'_, G> for ThorinErrorWrapper {
...
+                        first = false;
+                        arg.push(rlib);
+                    }
+                    arg.push("}");
+                    arg
+                }
+            }));
+
+            diag.note(format!("{:?}", self.command));
+            diag.note("some arguments are omitted. use `--verbose` to show all linker arguments");
```
Comment (jyn514) [inline compiler/rustc_codegen_ssa/src/errors.rs:421]: (note that bjorn wrote this part of the code, not me)

LGTM :) seems extensible if we want to change it in the future, and this is diagnostic code only so it's low risk.

**Comment by matthiaskrgr** [comment]
@bors r- https://github.com/rust-lang/rust/pull/134282#issuecomment-2542736732
:melting_face:

**Comment by jyn514** [comment]
oh lol it has two backslashes, not one

**Comment by jyn514** [comment]
:(

**Comment by jyn514** [comment]
@bors r=bjorn3,jyn514

(i only made changes to the tests, not the compiler.)
