### PR TITLE
rustbuild: Automatically enable Ninja on MSVC

### LINKED ISSUE #43767: Enable `ninja` by default on MSVC
When working locally dmajor has found that apparently disabling LLVM assertions *doesn't work* on MSVC when compiling LLVM. Despite `-DLLVM_ASSERTIONS=OFF` apparently they're still compiled in!

This isn't the first time IIRC of LLVM definitions and such not actually getting communicated to the msbuild build system. My guess is that this is a bug in LLVM's build system or something like that. In any case I think we should at least start using `ninja` by default if we detect ninja in PATH, and otherwise we may want to print warnings on "known bad" cases saying that msbuild isn't reading configuration options correctly, recommending a download of ninja

### PR DESCRIPTION
**Pull request by alexcrichton**
Discovered in #43767 it turns out the default MSBuild generator in CMake for
whatever reason isn't supporting many of the configuration options we give to
LLVM. To improve the contributor experience automatically enable Ninja if we
find it to ensure that "flavorful" configurations of LLVM work by default in
more situations.

Closes #43767

### CODE REVIEW

File: src/bootstrap/sanity.rs [hunk 1]
```diff
@@ -93,10 +93,27 @@ pub fn check(build: &mut Build) {
...
+        // If ninja isn't enabled but we're building for MSVC then we try
+        // doubly hard to enable it. It was realized in #43767 that the msbuild
+        // CMake generator for MSVC doesn't respect configuration options like
+        // disabling LLVM assertions, which can often be quite important!
+        //
+        // In these cases we automatically enable Ninja if we find it in the
+        // environment.
+        if !build.config.ninja && build.config.build.contains("msvc") {
+            if cmd_finder.maybe_have("ninja").is_some() {
+                build.config.ninja = true;
```
Comment (Mark-Simulacrum) [inline src/bootstrap/sanity.rs]: This means that there's no way to disable ninja on MSVC without editing bootstrap code. I'm not sure if there's any nice way of fixing that, though... or if it's even all that important to fix. What do you think?

Comment (alexcrichton) [reply src/bootstrap/sanity.rs]: That's correct, yes, but I'd consider it "if anyone runs into this then they have bigger problems" situations

Comment (Mark-Simulacrum) [reply src/bootstrap/sanity.rs]: True.
