### PR TITLE
Make const/fn return params more suggestable

### LINKED ISSUE #106843: E0121 only machineapplicable for functions but not items?
Given the following code: 

```rust
fn foo() -> _ { 5 } //~ ERROR E0121

static BAR: _ = "test"; //~ ERROR E0121

fn main() {}

```

The current output is:

```
error[E0121]: the placeholder `_` is not allowed within types on item signatures for return types
 --> src/main.rs:1:13
  |
1 | fn foo() -> _ { 5 } //~ ERROR E0121
  |             ^
  |             |
  |             not allowed in type signatures
  |             help: replace with the correct return type: `i32`

error[E0121]: the placeholder `_` is not allowed within types on item signatures for static variables
 --> src/main.rs:3:13
  |
3 | static BAR: _ = "test"; //~ ERROR E0121
  |             ^
  |             |
  |             not allowed in type signatures
  |             help: replace with the correct type: `&str`

For more information about this error, try `rustc --explain E0121`.
```

Both suggestions are valid here, but when I run `cargo fix --broken-code`, only the function will be fixed, and the `static` item will be left untouched for some reason :thinking: 
Looks like an oversight to me.

### PR DESCRIPTION
**Pull request by compiler-errors**
Bumps const item type suggestions to MachineApplicable (fixes #106843), also replaces FnDef with FnPtr items in return type suggestions to make more things suggestable.

r? diagnostics

### CODE REVIEW

File: compiler/rustc_middle/src/ty/fold.rs [hunk 1]
```diff
@@ -105,7 +105,7 @@ pub trait TypeSuperFoldable<'tcx>: TypeFoldable<'tcx> {
 /// the infallible methods of this trait to ensure that the two APIs
 /// are coherent.
 pub trait TypeFolder<'tcx>: FallibleTypeFolder<'tcx, Error = !> {
-    fn tcx<'a>(&'a self) -> TyCtxt<'tcx>;
+    fn tcx(&self) -> TyCtxt<'tcx>;
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/fold.rs:108]: this has always annoyed me

File: tests/ui/suggestions/suggest-type-for-const.stderr [hunk 2]
```diff
@@ -0,0 +1,12 @@
+error[E0121]: the placeholder `_` is not allowed within types on item signatures for constants
+  --> $DIR/suggest-type-for-const.rs:7:10
+   |
+LL | const C: _ = Wrapper(foo);
+   |          ^
+   |          |
+   |          not allowed in type signatures
+   |          help: replace with the correct type: `Wrapper<fn()>`
```
Comment (oli-obk) [inline tests/ui/suggestions/suggest-type-for-const.stderr:8]: This test doesn't actually test new behaviour, as the output on stable, beta and nightly is already the same:

```
error[E0121]: the placeholder `_` is not allowed within types on item signatures for constants
 --> src/main.rs:5:10
  |
5 | const C: _ = Wrapper(foo);
  |          ^
  |          |
  |          not allowed in type signatures
  |          help: replace with the correct type: `Wrapper<fn()>`
```

**Comment by oli-obk** [comment]
r=me with CI happy
