### PR TITLE
PassWrapper: disable UseOdrIndicator for Asan Win32

### LINKED ISSUE #124390: Unable to link use of hyper_util with -Zsanitizer=address on msvc
I tried this code:

```rust
// Cargo.toml
// [package]
// name = "conflicting_weak_bug"
// version = "0.1.0"
// edition = "2021"

// [dependencies]
// hyper-util = { version = "0.1.3", features = ["client-legacy"] }

fn main() {
    hyper_util::client::legacy::connect::Connected::new();
}
```

With `RUSTFLAGS=-Zsanitizer=address`, I run `cargo +nightly build --target=x86_64-pc-windows-msvc`

I expected to see this happen: build succeeds

Instead, this happened: Build fails:

```
note: libtokio-b91778b05568f23f.rlib(tokio-b91778b05568f23f.tokio.1a77ed8b4a2c54db-cgu.0.rcgu.o) : fatal error LNK1227: conflicting weak extern definition for '__odr_asan_gen___rust_panic_type_info'.  New default '.weak.__odr_asan_gen___rust_panic_type_info.default._ZN100_$LT$core..iter..adapters..take..Take$LT$I$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$8try_fold17h072bc292ea794e70E' conflicts with old default '.weak.__odr_asan_gen___rust_panic_type_info.default._ZN102_$LT$core..iter..adapters..map..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h028b213dc72dac34E' in libtracing_core-a6cff17f7c0ffd01.rlib(tracing_core-a6cff17f7c0ffd01.tracing_core.3abebefd05f70947-cgu.0.rcgu.o)
```

Seems somwhat similar to https://github.com/rust-lang/rust/issues/85461, however setting `-Ccodegen-units=1` does not workaround the issue.

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (ef8b9dcf2 2024-04-24)
binary: rustc
commit-hash: ef8b9dcf23700f2e2265317611460d3a65c19eff
commit-date: 2024-04-24
host: x86_64-pc-windows-msvc
release: 1.79.0-nightly
LLVM version: 18.1.4
```

MSVC version 14.39.33519

### PR DESCRIPTION
**Pull request by jakos-sec**
As described in https://reviews.llvm.org/D137227 UseOdrIndicator should be disabled on Windows since link.exe does not support duplicate weak definitions.

Fixes https://github.com/rust-lang/rust/issues/124390.

Credits also belong to @1c3t3a  who worked with me on this.
We are currently testing this on a Windows machine.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Is there a test that this would affect?

**Comment by rcvalle** [comment]
Thank you very much for helping me out with pushing #123617 through the last mile, @1c3t3a and @jakos-sec! It has been much appreciated.

**Comment by 1c3t3a** [comment]
I just verified that this indeed fixes #124390.

**Comment by rcvalle** [comment]
Thank you for verifying it, @1c3t3a! Much appreciated. As @workingjubilee mentioned, would you mind also adding a build-pass ui regression test for it?

**Comment by workingjubilee** [comment]
Yeah. It's not clear to me what this needs for testing, right now. If you need to do a somewhat baroque custom build of Rust code, we can walk you through setting that up. But this really should land with a regression test.

**Comment by jakos-sec** [comment]
We just added the ui regression test and tested it on Windows. Let me know what you think.

(I forgot to rebase on the first force push, sorry if this triggered some cc's).

File: tests/ui/asan-odr-win/asan_odr_windows.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+//@ run-pass
+//@ compile-flags:-Zsanitizer=address
+//@ aux-build:asan_odr_win-2.rs
```
Comment (jieyouxu) [inline tests/ui/asan-odr-win/asan_odr_windows.rs:3]: Suggestion: you can use `//@ aux-crate: othercrate=asan_odr_win-2.rs` to specify the crate name, and then you can drop `#![crate_name = "othercrate"]` in the auxiliary (so it's more obvious).

**Review by jieyouxu — APPROVED** [review]
Thanks, this LGTM with one minor nit.

File: tests/ui/asan-odr-win/asan_odr_windows.rs (hunk 1 above)
Comment (jakos-sec) [reply tests/ui/asan-odr-win/asan_odr_windows.rs]: Should be fixed now, thanks for the input!

**Comment by jieyouxu** [comment]
Thanks

r? jieyouxu
@bors r+ rollup=iffy (not really checked in PR CI AFAIK)
