### PR TITLE
Fix `cargo run tidy`

### LINKED ISSUE #94797: `cargo run -p bootstrap -- test tidy` fails because it can't find the sysroot
I tried this:

```sh
cargo run -p bootstrap -- test tidy
```

I expected to see this happen: Tidy runs fine, just as if I'd run `x test tidy`.

Instead, this happened:
```
Building stage0 tool tidy (x86_64-unknown-linux-gnu(x86_64-unknown-linux-gnu))
   Compiling itoa v0.4.6
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.25
   Compiling same-file v1.0.6
   Compiling cfg-if v1.0.0
   Compiling memchr v2.4.1
   Compiling ryu v1.0.5
   Compiling serde v1.0.125
error[E0463]: can't find crate for `core`

error[E0463]: can't find crate for `compiler_builtins`

error[E0463]: can't find crate for `core`
 --> /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:8:1
  |
8 | extern crate core;
  | ^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `std`
 --> /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:9:1
  |
9 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
```

The problem is that `src/bootstrap/build.rs` is setting `RUSTC` to `~/.cargo/bin/rustc`, not `~/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/bin/rustc`, which breaks because rustbuild then can't find the appropriate sysroot.

cc https://github.com/rust-lang/rust/pull/92260

@rustbot label: +A-bootstrap

### PR DESCRIPTION
**Pull request by jyn514**
When I implemented rust-only bootstrapping in https://github.com/rust-lang/rust/pull/92260,
I neglected to test stage0 tools - it turns out they were broken because
they couldn't find the sysroot of the initial bootstrap compiler.

This fixes stage0 tools by using `rustc --print sysroot` instead of assuming rustc is already in a
sysroot and hard-coding the relative directory.

Fixes https://github.com/rust-lang/rust/issues/94797 (properly, without having to change rustup).

### CODE REVIEW

File: src/bootstrap/lib.rs [hunk 1]
```diff
@@ -892,7 +893,12 @@ impl Build {
 
     /// Returns the sysroot of the snapshot compiler.
     fn rustc_snapshot_sysroot(&self) -> &Path {
-        self.initial_rustc.parent().unwrap().parent().unwrap()
+        static SYSROOT_CACHE: OnceCell<PathBuf> = once_cell::sync::OnceCell::new();
+        SYSROOT_CACHE.get_or_init(|| {
+            let mut rustc = Command::new(&self.initial_rustc);
+            rustc.args(&["--print", "sysroot"]);
+            output(&mut rustc).into()
```
Comment (Mark-Simulacrum) [inline src/bootstrap/lib.rs:900]: I think we need a .trim() here -- at least for me, it looks like --print sysroot has a trailing newline at the end:

```
$ rustc --print sysroot | xxd
00000000: 2f68 6f6d 652f 6d61 726b 2f2e 7275 7374  /home/mark/.rust
00000010: 7570 2f74 6f6f 6c63 6861 696e 732f 6e69  up/toolchains/ni
00000020: 6768 746c 792d 7838 365f 3634 2d75 6e6b  ghtly-x86_64-unk
00000030: 6e6f 776e 2d6c 696e 7578 2d67 6e75 0a    nown-linux-gnu.
```

**Review by Mark-Simulacrum — COMMENTED** [review]
The rustfmt initialization (for x.py fmt) may also need similar-ish treatment in config.rs -- I suspect the current logic there will just replace ~/.cargo/bin/rustc with ~/.cargo/bin/rustfmt which will be similarly ineffective.

**Comment by Mark-Simulacrum** [comment]
But I'm a little confused: does this actually work? ~/.cargo/bin/rustc --print sysroot would give you the *default* toolchains sysroot, not the one that you were actually running in the parent process, no? Or is that somehow magically being handled already?

**Comment by jyn514** [comment]
> Or is that somehow magically being handled already?

It's magically handled by the rustup proxy - it sets `RUSTUP_TOOLCHAIN` in the environment to make sure `rustc` does the right thing when cargo calls it. See around https://github.com/rust-lang/rustup/blob/d080411224dca896dbff18b02feabea16a95d9ed/src/toolchain.rs#L402.

**Comment by jyn514** [comment]
> I suspect the current logic there will just replace ~/.cargo/bin/rustc with ~/.cargo/bin/rustfmt which will be similarly ineffective.

This should be ok I think - it's just the sysroot detection that was broken, using the rustup proxy instead of rustfmt itself should work fine.

**Comment by jyn514** [comment]
Yup, looks fine:
```
$ cargo run -q fmt src/bootstrap
skip untracked path config.toml.bak during rustfmt invocations
skip untracked path empty.rs during rustfmt invocations
skip untracked path fds-local-no-requests.txt during rustfmt invocations
skip untracked path fds-local.txt during rustfmt invocations
skip untracked path src/build/ during rustfmt invocations
skip untracked path src/test/rustdoc/intra-doc/private-macro.rs during rustfmt invocations
```

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
Presumably that will not work with RUSTUP_TOOLCHAIN, since while Cargo and rustc are sourced from the same sysroot (beta) rustfmt needs to be from a different one presumably (nightly-XXXX) - doesn't necessarily need to block this PR, but I would like to understand if this will be a problem down the line or not.

**Comment by jyn514** [comment]
> while Cargo and rustc are sourced from the same sysroot (beta) rustfmt needs to be from a different one presumably (nightly-XXXX) - doesn't necessarily need to block this PR, but I would like to understand if this will be a problem down the line or not.

Yes, this popped up in another PR, it's an existing issue: https://github.com/rust-lang/rust/pull/94830#issuecomment-1066703562

Do you mind if I leave it for later? I think the logic for fixing this will be very similar to what's needed for `download-rustc` (i.e. fairly involved, using curl and such to download/unpack things) so I would rather wait until that infrastructure is in place.

**Comment by Mark-Simulacrum** [comment]
Sure, that works for me.

@bors r+
