### PR TITLE
Fixes #63962. Hint about missing tuple parentheses in patterns

### LINKED ISSUE #63962: Hint on missing tuple parens in pattern
It'd be nice to smartly hint about missing tuple parentheses in patterns, especially in positions where parentheses nesting is required.

Example of incorrect code:

```rust
fn main() {
    match Some((1, 2)) {
        Some(x, y) => {}
        None => {}
    }
}
```
The error:
```rust
error[E0023]: this pattern has 2 fields, but the corresponding tuple variant has 1 field
 --> src/main.rs:3:9
  |
3 |         Some(x, y) => {}
  |         ^^^^^^^^^^ expected 1 field, found 2
```

This error is confusing, especially since `Some` is a "tuple pattern" which is confusable with its tuple field. An error that suggests missing tuple parentheses would be helpful.

This issue has been assigned to @sam09 via [this comment](https://github.com/rust-lang/rust/issues/63962#issuecomment-526869836).

### PR DESCRIPTION
**Pull request by sam09**

### CODE REVIEW

File: src/librustc_typeck/check/pat.rs [hunk 1]
```diff
@@ -676,16 +676,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             // Pattern has wrong number of fields.
-            self.e0023(pat.span, res, &subpats, &variant.fields);
+            let missing_paranthesis = match expected.sty {
+                ty::Adt(_, substs) => {
+                    let mut a = false;
+                    if variant.fields.len() == 1 {
+                        let field_ty = variant.fields[0].ty(self.tcx, substs);
+                        match field_ty.sty {
+                            ty::Tuple(_) => {
+                                let mut index = 0;
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
                                field_ty.tuple_fields().count() == subpats.len()
```

File: src/librustc_typeck/check/pat.rs [hunk 2]
```diff
@@ -705,6 +734,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 subpats.len(),
             ))
             .span_label(res_span, format!("{} defined here", res.descr()))
+            .span_label(pat_span, format!("{}", missing_paranthesis_error))
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: Two points here:
- We should use https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.DiagnosticBuilder.html#method.span_suggestion instead of `.span_label` to add a `MachineApplicable` suggestion `(pat0, pat1, ...)`

   - You can use `let mut err = ...;` since chaining won't work well in this case anymore sadly.
   - The `suggestion: String` will need to be built out of the stringified patterns (use https://doc.rust-lang.org/nightly/nightly-rustc/syntax/print/pprust/fn.pat_to_string.html), interspersed with `,` and then surrounded with `(` and `)`.

- The `pat_span` here could be replaced with `subpats[0].span.to(subpats.last().unwrap().span)` to give a more targeted `Span`. This will be useful for the suggestion aforementioned.

cc @estebank in case he has thoughts.

**Review by Centril — CHANGES_REQUESTED** [review]
Thanks! Here are some ways to improve things.

File: src/librustc_typeck/check/pat.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/check/pat.rs]: `Span`s have `shrink_to_lo`/`shrink_to_hi` methods that point at the space right before the first span and right after the last span, respectively. You can then make a `multispan_suggestion` with little logic:

```rust
err.multispan_suggestion(
    vec![(pat_span.shrink_to_lo(), "(".to_string()), (pat_span.shrink_to_hi(), ")".to_string())],
    &missing_parenthesis_error,
    Applicability::MachineApplicable,
);
```

Comment (sam09) [reply src/librustc_typeck/check/pat.rs]: @estebank There is a `multipart suggestion` module. I think you mean that?

Comment (estebank) [reply src/librustc_typeck/check/pat.rs]: Yes, that's the correct name :)

File: src/librustc_typeck/check/pat.rs [hunk 3]
```diff
@@ -676,16 +676,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             }
         } else {
             // Pattern has wrong number of fields.
-            self.e0023(pat.span, res, &subpats, &variant.fields);
+            let missing_paranthesis = match expected.sty {
+                ty::Adt(_, substs) => {
```
[the remark this answers is not in the document]
Comment (sam09) [reply src/librustc_typeck/check/pat.rs]: Done

**Comment by sam09** [comment]
@estebank @Centril Updated the commit.

Also thanks a lot for the review 😄

File: src/librustc_typeck/check/pat.rs [hunk 4]
```diff
@@ -697,15 +714,25 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 fields_ending,
                 subpats.len(),
             ))
-            .span_label(res_span, format!("{} defined here", res.descr()))
-            .emit();
+            .span_label(res_span, format!("{} defined here", res.descr()));
+
+        if missing_parenthesis {
+            err.multipart_suggestion(
+                &missing_parenthesis_error_msg,
```
Comment (estebank) [inline src/librustc_typeck/check/pat.rs]: Given that `missing_parenthesis_error_msg` is not used anywhere else, I would just write the literal here. Also, I do not use title capitalization, use leading lowercase: `"missing parenthesis"`

**Review by estebank — APPROVED** [review]

File: src/test/ui/error-codes/E0023.stderr [hunk 5]
```diff
@@ -17,14 +17,27 @@ LL |         Fruit::Apple(a, b, c) => {},
...
+  --> $DIR/E0023.rs:14:9
+   |
+LL |     Orange((String, String)),
+   |     ------------------------ tuple variant defined here
+...
+LL |         Fruit::Orange(a, b) => {},
+   |         ^^^^^^^^^^^^^^^^^^^ expected 1 field, found 2
+help: Missing parenthesis
+   |
+LL |         (Fruit::Orange(a, b)) => {},
```
Comment (estebank) [inline src/test/ui/error-codes/E0023.stderr]: Wait, I just realized that the span for the parentheses is incorrect, it should be `Fruit::Orange((a, b))` here. You will need to fiddle with the sub pattern spans to get the right ones :-/

File: src/librustc_typeck/check/pat.rs (hunk 4 above)
Comment (sam09) [reply src/librustc_typeck/check/pat.rs]: Done

File: src/test/ui/error-codes/E0023.stderr (hunk 5 above)
Comment (sam09) [reply src/test/ui/error-codes/E0023.stderr]: Fixed it.

File: src/librustc_typeck/check/pat.rs [hunk 6]
```diff
@@ -676,18 +676,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
     }
 
-    fn e0023(&self, pat_span: Span, res: Res, subpats: &'tcx [P<Pat>], fields: &[ty::FieldDef]) {
+    fn e0023(
+        &self,
+        pat_span: Span,
+        res: Res,
+        subpats: &'tcx [P<Pat>],
+        fields: &[ty::FieldDef],
+        expected: Ty<'tcx>) {
```
Comment (estebank) [inline src/librustc_typeck/check/pat.rs]: Nitpick: The style for this would be

```
fn foo(
    arg: Type,
) {
```

**Comment by estebank** [comment]
r=me once green

**Comment by Centril** [comment]
Thanks! @bors r=Centril,estebank

**Comment by Centril** [comment]
@sam09 Can you please fixup the second commit into the first?

**Comment by sam09** [comment]
> @sam09 Can you please fixup the second commit into the first?

Done
