### PR TITLE
Don't ICE on placeholder consts in deep reject

### LINKED ISSUE #10: ICE: Placeholder const in deep rejection
```rust
struct Wrapper<T, const N: usize>([T; N]);

trait Foo {}
fn needs_foo<F: Foo>() {}

impl<T> Foo for [T; 1] {}

fn test<T, const N: usize>() {
    needs_foo::<[T; N]>();
}
```

```
error: internal compiler error: compiler/rustc_middle/src/ty/fast_reject.rs:375:17: unexpected obl const: Const { ty: usize, kind: Placeholder(Placeholder { universe: U0, name: 0 }) }
```

We shouldn't ICE for placeholder consts here since we canonicalize parameters

### PR DESCRIPTION
**Pull request by compiler-errors**
Since we canonicalize const params into placeholder consts, we need to be able to handle them during deep reject.

r? @lcnr (though maybe @oli-obk can look at this one too, if he wants 😸)

Fixes compiler-errors/next-solver-hir-issues#10

### CODE REVIEW

File: compiler/rustc_middle/src/ty/fast_reject.rs [hunk 1]
```diff
@@ -312,6 +312,7 @@ impl DeepRejectCtxt {
             // Impls cannot contain these types as these cannot be named directly.
             ty::FnDef(..) | ty::Closure(..) | ty::Generator(..) => false,
 
+            // Placeholder types don't unify with anything on their own
             ty::Placeholder(..) | ty::Bound(..) => false,
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/fast_reject.rs:316]: weird that we allow `ty::Bound` but not `ConstKind::Bound` :shrug: both should be unreachable (or well, reachable with ty/const binders)
