### PR TITLE
Ensure that Rustdoc discovers all necessary auto trait bounds

### LINKED ISSUE #50159: rustdoc panic when trying to build docs
When I tried to build docs for [my signals library](https://github.com/Pauan/rust-signals), I got a panic.

Here is the reduced test case:

```rust
pub trait IntoSignal {
    type Signal: Signal<Item = Self::Item>;
    type Item;
}

impl<A> IntoSignal for A where A: Signal {
    type Signal = Self;
    type Item = A::Item;
}

pub trait Signal {
    type Item;
}

pub struct Map<A, B> {
    signal: A,
    callback: B,
}

impl<A, B, C> Signal for Map<A, B>
    where A: Signal,
          B: FnMut(A::Item) -> C {
    type Item = C;
}

pub struct Flatten<A: Signal> where A::Item: IntoSignal {
    signal: Option<A>,
    inner: Option<<A::Item as IntoSignal>::Signal>,
}

impl<A> Signal for Flatten<A>
    where A: Signal,
          A::Item: IntoSignal {
    type Item = <<A as Signal>::Item as IntoSignal>::Item;
}

pub struct Switch<A, B, C>
    where A: Signal,
          B: IntoSignal,
          C: FnMut(A::Item) -> B {
    inner: Flatten<Map<A, C>>,
}

impl<A, B, C> Signal for Switch<A, B, C>
    where A: Signal,
          B: IntoSignal,
          C: FnMut(A::Item) -> B {
    type Item = <B::Signal as Signal>::Item;
}
```

With the above code, when I run `cargo doc --release` I get this panic:

```
thread '<unnamed>' panicked at 'Unable to fulfill trait DefId(2/0:887 ~ core[accb]::marker[0]::Send[0]) for 'Switch<A, B, C>': [FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<<B as IntoSignal>::Signal as std::marker::Send>)),depth=3),Unimplemented)]', librustdoc\clean\auto_trait.rs:401:17
stack backtrace:
   0: <std::collections::hash::map::DefaultHasher as core::fmt::Debug>::fmt
   1: std::stdsimd::arch::detect::os::check_for
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: _rust_maybe_catch_panic
  30: <unknown>
  31: <<std::sys_common::remutex::ReentrantMutex<T> as core::fmt::Debug>::fmt::LockedPlaceholder as core::fmt::Debug>::fmt
  32: std::sys::windows::thread::Thread::new
  33: BaseThreadInitThunk
  34: RtlUserThreadStart
error: Could not document `reduced-test`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name reduced_test src\lib.rs -o C:\Users\Pauan\Shared Folders\NixOS\reduced-test\target\doc -L dependency=C:\Users\Pauan\Shared Folders\NixOS\reduced-test\target\release\deps` (exit code: 101)
```

## Meta

rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
binary: rustc
commit-hash: ac3c2288f9f9d977acb46406ba60033d65165a7b
commit-date: 2018-04-18
host: x86_64-pc-windows-msvc
release: 1.27.0-nightly
LLVM version: 6.0

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #50159

This commit makes several improvements to AutoTraitFinder:

* Call infcx.resolve_type_vars_if_possible before processing new
predicates. This ensures that we eliminate inference variables wherever
possible.
* Process all nested obligations we get from a vtable, not just ones
with depth=1.
  * The 'depth=1' check was a hack to work around issues processing
certain predicates. The other changes in this commit allow us to
properly process all predicates that we encounter, so the check is no
longer necessary,
* Ensure that we only display predicates *without* inference variables
to the user, and only attempt to unify predicates that *have* an
inference variable as their type.

Additionally, the internal helper method is_of_param now operates
directly on a type, rather than taking a Substs. This allows us to use
the 'self_ty' method, rather than directly dealing with Substs.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks a lot! However, considering that it changes things in librustc, I'll let someone from the @rust-lang/compiler team review it.

**Comment by nikomatsakis** [comment]
Sorry for being slow-ish, will get on this this week =)

**Review by nikomatsakis — APPROVED** [review]

File: src/librustc/traits/auto_trait.rs [hunk 1]
```diff
@@ -622,28 +623,61 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
...
+            // an internal compiler detail without a defined visual representation
+            //
+            // We check this by calling is_of_param on the relevant types
+            // from the various possible predicates
             match &predicate {
                 &ty::Predicate::Trait(ref p) => {
-                    let substs = &p.skip_binder().trait_ref.substs;
+                    if self.is_of_param(p.skip_binder().self_ty())
+                        && !only_projections
+                        && is_new_pred {
```
Comment (nikomatsakis) [inline src/librustc/traits/auto_trait.rs]: Why don't we check for inference variables for the other parts of `p`?

File: src/librustc/traits/auto_trait.rs [hunk 2]
```diff
@@ -622,28 +623,61 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
...
 
-                    if self.is_of_param(substs) && !only_projections && is_new_pred {
                         self.add_user_pred(computed_preds, predicate);
                     }
                     predicates.push_back(p.clone());
```
Comment (nikomatsakis) [inline src/librustc/traits/auto_trait.rs]: Pre-existing, but can you explain to me why this adds a user-predicate (above) and then *still* pushes `p` back onto the list to be selected again?

**Review by nikomatsakis — COMMENTED** [review]
Changes all seem good. I'm game to r+ but I have a few questions about the underlying logic.

File: src/librustc/traits/auto_trait.rs (hunk 2 above)
Comment (Aaron1011) [reply src/librustc/traits/auto_trait.rs]: Selecting `p` might result in other predicates (e.g. `TypeOutlives` or `RegionOutlives`) that are necessary for `FulfillmentContext.select_all_or_error` to succeed.

In general, `AutoTraitFinder` always tries to drive `select` all the way to the end. A subset of the predicates that it finds along the way are suitable for displaying to a user (e.g. rendering in docs), which we track separately.

File: src/librustc/traits/auto_trait.rs (hunk 1 above)
Comment (Aaron1011) [reply src/librustc/traits/auto_trait.rs]: That was an oversight on my part - I intended to check all of the parameters in `substs`, but forgot to change it. I've pushed a new commit fixing it.

**Comment by Aaron1011** [comment]
Once https://github.com/rust-lang-nursery/crater/pull/366 is deployed, it might be useful to do a Crater `rustdoc` run with this PR.

**Comment by Aaron1011** [comment]
@nikomatsakis: Are there any other changes that you'd like me to make?

**Review by nikomatsakis — APPROVED** [review]
I'm happy but if you want to do a crater run, that sounds fine to me. I'm not sure if you can do rustdoc crater runs, I guess @pietroalbini would know

**Comment by pietroalbini** [comment]
Yeah, it's possible, just use `mode=rustdoc`.

**Comment by Aaron1011** [comment]
@nikomatsakis @pietroalbini: I don't have permission to start a crater run - can one of you start one?

**Comment by Mark-Simulacrum** [comment]
Since I didn't see a try build here yet... @bors try for crater

**Comment by pietroalbini** [comment]
@craterbot run start=master#6bfb46e4ac9a2704f06de1a2ff7a4612cd70c8cb end=try#f5a0bd723553ea4b7556bd7087b9f0919cafb483 mode=rustdoc

**Comment by Aaron1011** [comment]
I've pushed a new commit fixing the regression. However, given how unexpected the regression was in the first place, it might be worthwhile to do another rustdoc Crater run to ensure that I haven't accidentally introduced *another* regression.

**Comment by Aaron1011** [comment]
@pietroalbini Could you start a rustdoc crater rub?

**Comment by pietroalbini** [comment]
@craterbot run start=master#147e60c5f89cfa2d3ffc247413956a37582c98e7 end=try#f86f76f89ea2b1ccbfb3741962ec2029d878a389 mode=rustdoc

**Comment by Aaron1011** [comment]
The one 'regression' appears spurious.

@nikomatsakis: I believe this is ready to merge.

**Comment by pietroalbini** [comment]
Ping @rust-lang/rustdoc, this PR is a prerequisite for backporting https://github.com/rust-lang/rust/pull/56838, do you want to accept it for backport on beta?

**Comment by QuietMisdreavus** [comment]
Accepting beta nomination for the same reasons as https://github.com/rust-lang/rust/pull/56838.
