### PR TITLE
Hide cross-crate `#[doc(hidden)]` associated items in trait impls

### LINKED ISSUE #95717: rustdoc: `#[doc(hidden)]` associated items of traits re-exported from external crates are not hidden in certain `impl` blocks
Minimal reproducible example (on stable and nightly):

```rust
// in crate `alpha`

pub trait Tr {
    #[doc(hidden)]
    type Assoc;
}

pub struct Ty;

impl Tr for Ty {
    type Assoc = ();
}
```

```rust
// in crate `beta` (which depends on `alpha`)

pub use alpha::{Tr, Ty};    // glob would also work
```

Document crate `beta` and take a look at the generated pages of `Tr` and `Ty`:
You should be able to actually **see** the associated type `Assoc` in the `impl` block despite being **marked as hidden**. You probably need to click `[+]` (_expand_) first.
The `impl` block I refer to is in section

* _Implementors_ on the trait page and in section
* _Trait Implementations_ on the implementor's page.

It should be noted that even though `Assoc` wrongly shows up in those `impl` blocks, it is indeed not shown in the code block at the start of the trait page – at the “definition site” if you will (compared to the “use sites” – the `impl` blocks).

It is **crucial** that the trait and the type are defined inside of an external crate. If they were defined in the “current” crate, this bug would not occur: The hidden associated items would not be shown.
You can check this for yourself by

* documenting `alpha` on its own and viewing its documentation separately, or by
* re-exporting the crate `alpha` from `beta` (e.g. with `pub use alpha;`) and then documenting `beta`:
  * On the page for `alpha::Tr`, the associated item is hidden
  * On the page for the re-export `beta::Tr`, however, the associated item is displayed

---

[I've discovered this bug in a PR of mine](https://github.com/rust-lang/rust/pull/95316#issuecomment-1079737208 ) after a CI job failed because the linkchecker complained about broken links in the standard library when documenting it with a modified rustdoc. The broken links are not relevant for this bug, they are mere symptoms of it: If everything was properly hidden, no broken links would ever be generated.

This bug currently **affects the standard library documentation** (for stable and nightly) as mentioned in the linked comment.
In this case,

* the trait is [`SupportedLaneCount`](https://doc.rust-lang.org/stable/std/simd/trait.SupportedLaneCount.html)
* the type is [`LaneCount`](https://doc.rust-lang.org/stable/std/simd/struct.LaneCount.html)
* the associated type that shouldn't be shown is `BitMask`
* crate “alpha” is `core`
* crate “beta” is `std`

---

@rustbot label T-rustdoc A-cross-crate-reexports

### PR DESCRIPTION
**Pull request by fmease**
Fixes #95717.

r? @GuillaumeGomez
This is the bug I ran into in #95316.

@rustbot label T-rustdoc A-cross-crate-reexports

### CODE REVIEW

File: src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+#![crate_name = "dependent"]
+// edition:2021
+// aux-crate:dependency=cross-crate-hidden-assoc-trait-items.rs
+
+// @has dependent/struct.Ty.html
+// @!has - '//*[@id="associatedtype.Assoc"]' 'type Assoc = ()'
+// @!has - '//*[@id="associatedconstant.ASSOC"]' 'const ASSOC: ()'
+// @has dependent/trait.Tr.html
+// @!has - '//*[@id="associatedtype.Assoc"]' 'type Assoc = ()'
+// @!has - '//*[@id="associatedconstant.ASSOC"]' 'const ASSOC: ()'
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs:12]: Two things on this test:

1. Please add both an associated type and an associated const which are not doc hidden.
2. Use `matches` to check the whole block, not just that they're not present.

Providing some explanations on why I ask you this: in case we change the formatting of the IDs for associated items, this test will still pass but the items might be displayed. It's because `@!has` isn't that great and which is why we added `@matches` for such cases.

**Comment by GuillaumeGomez** [comment]
Other than the test, it looks good to me, thanks!

cc @camelid to double check the code changes.

File: src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+// Regression test for issue #95717: Hide cross-crate doc(hidden) associated items in trait impls.
+
+#![crate_name = "dependent"]
+// edition:2021
+// aux-crate:dependency=cross-crate-hidden-assoc-trait-items.rs
+
```
Comment (fmease) [inline src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs:6]: I'd like to improve this test, it's not really robust. The thing is, I don't really know where to read up on the syntax of this UI test suite (`@has`, …). I've already searched the rustc-dev-guide to no avail.

Not robust in the sense that if someone changes for example how associated types are rendered like printing its bounds , I think the `@!has` rule will succeed even though it shouldn't. But when I only check if `!has` `id`, leaving out the second test string of each line, then the test passes not only for this PR but also for nightly rust w/o my changes!
But I can't move the test strings like `type Assoc = ()` down one line to a separate `@!has` rule: The tests starts passing no matter what.

File: src/test/rustdoc/auxiliary/cross-crate-hidden-assoc-trait-items.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
+#![crate_name = "cross_crate_hidden_assoc_trait_items"]
```
Comment (fmease) [inline src/test/rustdoc/auxiliary/cross-crate-hidden-assoc-trait-items.rs:1]: Oops, that's left over from experimenting with stuff. I'm gonna remove it after the CI passes.

File: src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/cross-crate-hidden-assoc-trait-items.rs:6]: I would have suggested to look at other `@matches` example to see how they're done but that works too. ;)

**Comment by camelid** [comment]
@GuillaumeGomez Sorry, I don't have time to review this, but nothing stood out when I glanced at the diff. I'll leave it to you :)

**Review by GuillaumeGomez — APPROVED** [review]
