### PR TITLE
Avoid miri error in `slice::sort` under Stacked Borrows

### LINKED ISSUE #151728: Sorting Boxes causes Miri to report UB
This issue was discovered by @orxfun on [zulip](https://rust-lang.zulipchat.com/#narrow/channel/269128-miri/topic/miri.20fails.20when.20sorting.20slice.20of.20boxed.20integers/with/570245641).

The following code causes Miri to report UB:

```rust
fn main() {
    // passes when input is already sorted, for instance when: elem = |i| Box::new(i)
    let len = 100;
    let elem = |i: usize| {
        Box::new(match i.is_multiple_of(2) {
            true => i,
            false => len + i,
        })
    };
    let mut input: Vec<_> = (0..len).map(elem).collect();
    input.sort()
}
```

<details>
<summary>Miri error</summary>

```
error: Undefined Behavior: trying to retag from <12657> for SharedReadOnly permission at alloc3398[0x0], but that tag does not exist in the borrow stack for this location
    --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2069:24
     |
2069 |         PartialOrd::lt(&**self, &**other)
     |                        ^^^^^^^ this error occurs as part of retag at alloc3398[0x0..0x8]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <12657> was created by a Unique retag at offsets [0x0..0x8]
    --> src/main.rs:11:5
     |
  11 |     input.sort()
     |     ^^^^^^^^^^^^
help: <12657> was later invalidated at offsets [0x0..0x8] by a SharedReadOnly retag
    --> src/main.rs:11:5
     |
  11 |     input.sort()
     |     ^^^^^^^^^^^^
     = note: stack backtrace:
             0: <std::boxed::Box<usize> as std::cmp::PartialOrd>::lt
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2069:24: 2069:31
             1: <for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt} as std::ops::FnMut<(&std::boxed::Box<usize>, &std::boxed::Box<usize>)>>::call_mut - shim(for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt})
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:166:5: 166:75
             2: core::slice::sort::stable::quicksort::quicksort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/quicksort.rs:57:40: 57:72
             3: core::slice::sort::stable::quicksort::quicksort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/quicksort.rs:75:9: 75:61
             4: core::slice::sort::stable::drift::stable_quicksort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/drift.rs:270:5: 270:48
             5: core::slice::sort::stable::drift::sort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/drift.rs:118:9: 118:46
             6: core::slice::sort::stable::driftsort_main::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}, std::vec::Vec<std::boxed::Box<usize>>>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/mod.rs:135:5: 135:77
             7: core::slice::sort::stable::sort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}, std::vec::Vec<std::boxed::Box<usize>>>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/sort/stable/mod.rs:83:13: 83:53
             8: std::slice::stable_sort::<std::boxed::Box<usize>, for<'a, 'b> fn(&'a std::boxed::Box<usize>, &'b std::boxed::Box<usize>) -> bool {<std::boxed::Box<usize> as std::cmp::PartialOrd>::lt}>
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/slice.rs:861:5: 861:56
             9: std::slice::<impl [std::boxed::Box<usize>]>::sort
                 at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/slice.rs:135:9: 135:33
             10: main
                 at src/main.rs:11:5: 11:17

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```

</details>

### Meta

Reproducible on the playground with Miri version `0.1.0 (2026-01-26 474276961f)`

### PR DESCRIPTION
**Pull request by Voultapher**
See comment in code.

Fixes: https://github.com/rust-lang/rust/issues/151728

### CODE REVIEW

**Comment by Noratrieb** [comment]
Yeah I think MaybeUninit should work just fine (or MaybeDangling if that already exists?). I would really prefer to avoid adding `cfg!(miri)` for SB UB. Note that TB will not become the standard as it is insufficiently permissive for optimizations, the final model will likely be between TB and SB in terms of permissiveness. That's why SB is the default and why we should follow SB when possible.
cc @RalfJung

**Comment by theemathas** [comment]
Maybe just the `ptr::read()` is sufficient to invalidate the `Box`? What about something similar to this:

```rust
let pivot_copy = unsafe { ptr::read((&raw const v[pivot_pos]).cast::<MaybeUninit<T>>()) };
```

File: library/core/src/slice/sort/stable/quicksort.rs [hunk 1]
```diff
@@ -41,8 +41,10 @@ pub fn quicksort<T, F: FnMut(&T, &T) -> bool>(
         // SAFETY: We only access the temporary copy for Freeze types, otherwise
         // self-modifications via `is_less` would not be observed and this would
         // be unsound. Our temporary copy does not escape this scope.
-        let pivot_copy = unsafe { ManuallyDrop::new(ptr::read(&v[pivot_pos])) };
-        let pivot_ref = (!has_direct_interior_mutability::<T>()).then_some(&*pivot_copy);
+        let pivot_copy = unsafe { ptr::read((&raw const v[pivot_pos]).cast::<MaybeUninit<T>>()) };
```
Comment (RalfJung) [inline library/core/src/slice/sort/stable/quicksort.rs:45]: Please add a comment explaining why `MaybeUninit` is necessary here.

Also, once https://github.com/rust-lang/rust/pull/151365 lands using `MaybeDangling` instead should work. Maybe add a FIXME indicating that.

**Comment by Voultapher** [comment]
> Temporarily creating a child box that then disappears immediately should be fine. So for this to be a problem, there have to be overlapping (non-nested) lifetimes of the boxes here... is that's what is going on?

I'm not sure. I'll try to explain a simplified algorithm:
- Recursion depth 0: `left_ancestor_pivot == None`, partitions, creates stack copy of `pivot`
- Recursion depth 1: `left_ancestor_pivot == &pivot from level 0`, partitions which can swap around the location that `v[pivot]` is in `v`, reads `left_ancestor_pivot` <- miri complains

**Comment by Voultapher** [comment]
Not sure what you mean, the swapping - it's more complicated than that since it's first written to an auxiliary buffer - all happens via `ptr::copy_nonoverlapping` isn't that a bytewise operation? The thing that might be re-tagging it is creating a reference when passing it to the user-provided `is_less` which for API reasons we can't get around.
