### PR TITLE
Fix misleading `cannot infer type for type parameter` error

### LINKED ISSUE #93198: Misleading `cannot infer type for type parameter`
Given the following code: 

```rust
use std::collections::HashMap;

trait Store<K, V> {
    fn get_raw(&self, key: &K) -> Option<()>;
}

struct InMemoryStore;

impl<K> Store<String, HashMap<K, String>> for InMemoryStore {
    fn get_raw(&self, key: &String) -> Option<()> {
        None
    }
}

fn main() {
    InMemoryStore.get_raw(&String::default());
}
```

([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4c1b9ccf80b5ae9efc24b081a1242c5f))

... the current output is:

```
error[E0282]: type annotations needed
  --> src/main.rs:16:19
   |
16 |     InMemoryStore.get_raw(&String::default());
   |                   ^^^^^^^ cannot infer type for type parameter `K`
```

This error message is a bit misleading in that it refers _not_ to `K` from `trait Store<K, V>`, but `K` from the `impl<K> Store<...>` (the compiler is not sure which kind of `HashMap<K, String>` user wants).

Maybe we could print something like this?

```
error[E0282]: type annotations needed
  --> src/main.rs:16:19
   |
16 |     InMemoryStore.get_raw(&String::default());
   |                   ^^^^^^^ cannot infer type for type parameter `K`...
   |
  ::: src/main.rs:9
   |
 9 | impl<K> Store<String, HashMap<K, String>> for InMemoryStore {
          ^ ... from this impl
```

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #93198

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 1]
```diff
@@ -933,6 +934,27 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+            let ty_vars = &inner.type_variables();
+            let var_origin = ty_vars.var_origin(ty_vid);
+            if let TypeVariableOriginKind::TypeParameterDefinition(name, Some(def_id)) =
+                var_origin.kind
+                && let Some(parent_def_id) = self.tcx.parent(def_id).as_local()
+                && let Some(hir::Node::Item(item)) = self.tcx.hir().find_by_def_id(parent_def_id)
+                && let hir::ItemKind::Impl(impl_item) = item.kind
+                && let Some(trait_ref) = &impl_item.of_trait
+                && let Some(did) = trait_ref.trait_def_id()
+                && self.tcx.generics_of(did).params.iter().any(|param| param.name == name)
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:951]: Do we need these checks? Will the diagnostic be too noisy if we just always report the `help` on the `def_id`?

Comment (oli-obk) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:951]: While for `Option` it is a bit redundant, I'd hope that for user defined types this will be helpful.

Maybe not emitting it on type declarations, but on any function, method or impl could remove those weird cases?

Comment (TaKO8Ki) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:951]: Ok. I'm going to fix it.

**Comment by oli-obk** [comment]
Looks like there are more tests that need blessing. If they aren't available locally, maybe you need to rebase

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 2]
```diff
@@ -933,6 +934,24 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+    fn report_ambiguous_type_parameter(&self, err: &mut Diagnostic, arg: GenericArg<'tcx>) {
+        if let GenericArgKind::Type(ty) = arg.unpack()
+            && let ty::Infer(ty::TyVar(ty_vid)) = *ty.kind()
+        {
+            let mut inner = self.inner.borrow_mut();
+            let ty_vars = &inner.type_variables();
+            let var_origin = ty_vars.var_origin(ty_vid);
+            if let TypeVariableOriginKind::TypeParameterDefinition(_, Some(def_id)) =
+                var_origin.kind
+                && let Some(parent_def_id) = self.tcx.parent(def_id).as_local()
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:946]: Doesn't have to happen in.this PR, but we could extend this to Node::ImplItem, too, so that we'd show it for associated functions

**Comment by oli-obk** [comment]
@bors r+ rollup

Thanks for doing all these changes!
