### PR TITLE
layout computation: gracefully handle unsized types in unexpected locations

### LINKED ISSUE #123134: univariant: field #2 comes after unsized field
### Code

I'm not sure what exactly causes the ICE, but it happened in commit [0bb2479](https://github.com/lylythechosenone/wgpu/commit/0bb247973d9dfa4e7587a78113c1ab9d41d60b59) on my fork of wgpu ([lylythechosenone/wgpu](https://github.com/lylythechosenone/wgpu)).

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```

### Error output

```
error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: univariant: field #2 comes after unsized field
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: univariant: field #2 comes after unsized field
|
= note: delayed at compiler/rustc_middle/src/ty/layout.rs:286:23
           0: std::backtrace::Backtrace::create
           1: <rustc_errors::DiagCtxtInner>::emit_diagnostic_without_consuming
           2: <rustc_errors::DiagCtxtInner>::emit_diagnostic
           3: <rustc_errors::DiagCtxt>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
           4: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_abi::layout::LayoutCalculator>::delayed_bug
           5: rustc_abi::layout::univariant::<rustc_target::abi::FieldIdx, rustc_target::abi::VariantIdx, rustc_target::abi::Layout, rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>>
           6: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_abi::layout::LayoutCalculator>::univariant::<rustc_target::abi::FieldIdx, rustc_target::abi::VariantIdx, rustc_target::abi::Layout>
           7: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_abi::layout::LayoutCalculator>::layout_of_struct_or_enum::<rustc_target::abi::FieldIdx, rustc_target::abi::VariantIdx, rustc_target::abi::Layout, rustc_ty_utils::layout::layout_of_uncached::{closure#10}, core::iter::adapters::flatten::Flatten<core::option::IntoIter<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::VariantDef>>, <rustc_index::slice::IndexSlice<rustc_target::abi::VariantIdx, rustc_middle::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle::ty::adt::AdtDef>::discriminants::{closure#0}>, rustc_ty_utils::layout::layout_of_uncached::{closure#11}::{closure#0}::{closure#0}>>>>
           8: rustc_ty_utils::layout::layout_of_uncached
           9: rustc_ty_utils::layout::layout_of
          10: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
          11: <rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>)>>::call_once
          12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 16]>>, false, true, false>, rustc_query_impl::plumbing::QueryCtxt, true>
          13: rustc_query_impl::query_impl::layout_of::get_query_incr::__rust_end_short_backtrace
          14: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_middle::ty::layout::LayoutOf>::spanned_layout_of
          15: core::iter::adapters::try_process::<core::iter::adapters::by_ref_sized::ByRefSized<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::FieldDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#8}::{closure#0}>>, rustc_target::abi::Layout, core::result::Result<core::convert::Infallible, &rustc_middle::ty::layout::LayoutError>, <core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::FieldDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#8}::{closure#0}> as core::iter::traits::iterator::Iterator>::try_collect<rustc_index::vec::IndexVec<rustc_target::abi::FieldIdx, rustc_target::abi::Layout>>::{closure#0}, rustc_index::vec::IndexVec<rustc_target::abi::FieldIdx, rustc_target::abi::Layout>>
          16: core::iter::adapters::try_process::<core::iter::adapters::by_ref_sized::ByRefSized<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::VariantDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#8}>>, rustc_index::vec::IndexVec<rustc_target::abi::FieldIdx, rustc_target::abi::Layout>, core::result::Result<core::convert::Infallible, &rustc_middle::ty::layout::LayoutError>, <core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::VariantDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#8}> as core::iter::traits::iterator::Iterator>::try_collect<rustc_index::vec::IndexVec<rustc_target::abi::VariantIdx, rustc_index::vec::IndexVec<rustc_target::abi::FieldIdx, rustc_target::abi::Layout>>>::{closure#0}, rustc_index::vec::IndexVec<rustc_target::abi::VariantIdx, rustc_index::vec::IndexVec<rustc_target::abi::FieldIdx, rustc_target::abi::Layout>>>
          17: rustc_ty_utils::layout::layout_of_uncached
          18: rustc_ty_utils::layout::layout_of
          19: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
          20: <rustc_query_impl::query_impl::layout_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>)>>::call_once
          21: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 16]>>, false, true, false>, rustc_query_impl::plumbing::QueryCtxt, true>
          22: rustc_query_impl::query_impl::layout_of::get_query_incr::__rust_end_short_backtrace
          23: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 16]>>>
          24: <rustc_mir_transform::const_prop::CanConstProp>::check
          25: <rustc_mir_transform::const_prop_lint::ConstPropLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
          26: rustc_mir_transform::pass_manager::run_passes_inner
          27: rustc_mir_transform::run_analysis_to_runtime_passes
          28: rustc_mir_transform::mir_drops_elaborated_and_const_checked
          29: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
          30: <rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
          31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
          32: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::get_query_incr::__rust_end_short_backtrace
          33: rustc_mir_transform::optimized_mir
          34: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
          35: <rustc_query_impl::query_impl::optimized_mir::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
          36: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
          37: rustc_query_impl::query_impl::optimized_mir::get_query_incr::__rust_end_short_backtrace
          38: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
          39: <clippy_lints::redundant_clone::RedundantClone as rustc_lint::passes::LateLintPass>::check_fn
          40: rustc_hir::intravisit::walk_impl_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass>>
          41: <rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass> as rustc_hir::intravisit::Visitor>::visit_nested_impl_item
          42: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass>>
          43: <rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass> as rustc_hir::intravisit::Visitor>::visit_nested_item
          44: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass>>
          45: <rustc_lint::late::LateContextAndPass<rustc_lint::late::RuntimeCombinedLateLintPass> as rustc_hir::intravisit::Visitor>::visit_nested_item
          46: rustc_lint::late::late_lint_crate
          47: <rustc_session::session::Session>::time::<(), rustc_lint::late::check_crate::{closure#0}::{closure#0}>
          48: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_lint::late::check_crate::{closure#0}>
          49: rustc_data_structures::sync::parallel::disabled::join::<rustc_lint::late::check_crate::{closure#0}, rustc_lint::late::check_crate::{closure#1}, (), ()>
          50: rustc_lint::late::check_crate
          51: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0}::{closure#2}::{closure#0}>
          52: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_interface::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0}::{closure#2}>
          53: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#6}::{closure#1}::{closure#0}>>
          54: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_interface::passes::analysis::{closure#6}::{closure#1}::{closure#0}>
          55: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#6}>
          56: rustc_interface::passes::analysis
          57: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
          58: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
          59: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
          60: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
          61: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}::{closure#3}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
          62: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
          63: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}>
          64: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
          65: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
          66: std::sys::unix::thread::Thread::new::thread_start
          67: __pthread_joiner_wake
        

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.76.0 (07dca489a 2024-02-04) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: Clippy version: clippy 0.1.76 (07dca489 2024-02-04)

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: rustc 1.76.0 (07dca489a 2024-02-04) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: Clippy version: clippy 0.1.76 (07dca489 2024-02-04)
```

</p>
</details>

### LINKED ISSUE #124182: ICE: `assertion failed: layout.is_sized()`
### Code

```Rust
struct LazyLock<T> {
    data: (Copy, fn() -> T),
}

impl<T> LazyLock<T> {
    pub const fn new(f: fn() -> T) -> LazyLock<T> {
        LazyLock { data: (None, f) }
    }
}

struct A<T = i32>(Option<T>);

impl<T> Default for A<T> {
    fn default() -> Self {
        A(None)
    }
}

static EMPTY_SET: LazyLock<A<i32>> = LazyLock::new(A::default);

fn main() {}
```

I couldn't simplify the code without making it harder to understand.

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (e3181b091 2024-04-18)
binary: rustc
commit-hash: e3181b091e88321f5ea149afed6db0edf0a4f37b
commit-date: 2024-04-18
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.4
```

### Command
`rustc`

### Error output

```
warning: trait objects without an explicit `dyn` are deprecated
 --> r_crushed_473555.rs:2:12
  |
2 |     data: (Copy, fn() -> T),
  |            ^^^^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
  = note: `#[warn(bare_trait_objects)]` on by default
help: if this is an object-safe trait, use `dyn`
  |
2 |     data: (dyn Copy, fn() -> T),
  |            +++

error[E0038]: the trait `Copy` cannot be made into an object
 --> r_crushed_473555.rs:2:12
  |
2 |     data: (Copy, fn() -> T),
  |            ^^^^ `Copy` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>

error[E0277]: the size for values of type `(dyn Copy + 'static)` cannot be known at compilation time
 --> r_crushed_473555.rs:2:11
  |
2 |     data: (Copy, fn() -> T),
  |           ^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Copy + 'static)`
  = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: `(dyn Copy + 'static)` cannot be shared between threads safely
  --> r_crushed_473555.rs:19:19
   |
19 | static EMPTY_SET: LazyLock<A<i32>> = LazyLock::new(A::default);
   |                   ^^^^^^^^^^^^^^^^ `(dyn Copy + 'static)` cannot be shared between threads safely
   |
   = help: within `LazyLock<A>`, the trait `Sync` is not implemented for `(dyn Copy + 'static)`, which is required by `LazyLock<A>: Sync`
   = note: required because it appears within the type `((dyn Copy + 'static), fn() -> A)`
note: required because it appears within the type `LazyLock<A>`
  --> r_crushed_473555.rs:1:8
   |
1  | struct LazyLock<T> {
   |        ^^^^^^^^
   = note: shared static variables must have a type that implements `Sync`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_const_eval/src/const_eval/eval_queries.rs:54:5:
assertion failed: layout.is_sized()
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustc_const_eval::const_eval::eval_queries::eval_static_initializer_provider
      [... omitted 2 frames ...]
   4: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_hir_analysis::check_crate::{closure#3}>::{closure#0}
   5: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_analysis::check_crate::{closure#3}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
   6: rustc_hir_analysis::check_crate
   7: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
   8: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
   9: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/jisukbyun/workspace/placeholder/240420_rustexec/rustc-ice-2024-04-20T00_36_22-48540.txt` to your bug report

query stack during panic:
#0 [eval_static_initializer] evaluating initializer of static `EMPTY_SET`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0038, E0277.
For more information about an error, try `rustc --explain E0038`.
```

</p>
</details>

### Note

- ICE-loc: `compiler/rustc_const_eval/src/const_eval/eval_queries.rs:54:5`
https://github.com/rust-lang/rust/blob/e3181b091e88321f5ea149afed6db0edf0a4f37b/compiler/rustc_const_eval/src/const_eval/eval_queries.rs#L53-L54

  - Two closed issues points this ICE-loc; #123154 and #121443. But at first glance I cannot understand why they triggers same ICE location.

- Original ICE-triggering code is mutated from test-file `trait-method-ptr-in-consts-ice.rs`
https://github.com/rust-lang/rust/blob/f9b16149208c8a8a349c32813312716f6603eb6f/tests/ui/rfcs/rfc-2632-const-trait-impl/trait-method-ptr-in-consts-ice.rs#L3-L5

### LINKED ISSUE #126939: ICE: `AlignOf MIR operator called for unsized type`for struct without features
### Code

```Rust
struct MySlice<T: Copy>(bool, T);
type MySliceBool = MySlice<[bool]>;

use std::mem;

struct P2<T> {
    a: T,
    b: MySliceBool,
}

macro_rules! check {
    ($t:ty, $align:expr) => ({
        assert_eq!(mem::align_of::<$t>(), $align);
    });
}

pub fn main() {
    check!(P2<u8>, 1);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (bcf94dec5 2024-06-23)
binary: rustc
commit-hash: bcf94dec5ba6838e435902120c0384c360126a26
commit-date: 2024-06-23
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Error output

```
error[E0277]: the trait bound `[bool]: Copy` is not satisfied
 --> ./F4E30.rs:8:8
  |
8 |     b: MySliceBool,
  |        ^^^^^^^^^^^ the trait `Copy` is not implemented for `[bool]`
  |
  = help: the trait `Copy` is implemented for `[T; N]`
note: required by a bound in `MySlice`
 --> ./F4E30.rs:1:19
  |
1 | struct MySlice<T: Copy>(bool, T);
  |                   ^^^^ required by this bound in `MySlice`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/step.rs:241:21: AlignOf MIR operator called for unsized type P2<u8>
   --> /Users/sal/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:466:5
    |
466 |     intrinsics::min_align_of::<T>()
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/step.rs:241:21:
Box<dyn Any>
stack backtrace:
   0:        0x1016e6b43 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he71f7af0ddafc64d
   1:        0x10173225b - core::fmt::write::h30d0e266faff29b6
   2:        0x1016dcace - std::io::Write::write_fmt::he666ca78eb4b8406
   3:        0x1016e6931 - std::sys::backtrace::print::h22721f9ab9a2749a
   4:        0x1016e9709 - std::panicking::default_hook::{{closure}}::h145e29ed875d8021
   5:        0x1016e948a - std::panicking::default_hook::h5d437c7e6bf0e3b5
   6:        0x10a98147c - std[8efa578c02603ef9]::panicking::update_hook::<alloc[135510a28be92df]::boxed::Box<rustc_driver_impl[63f2171535a6fe49]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x1016ea326 - std::panicking::rust_panic_with_hook::h6889093a56e48d04
   8:        0x10a9f0337 - std[8efa578c02603ef9]::panicking::begin_panic::<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>::{closure#0}
   9:        0x10a9dc949 - std[8efa578c02603ef9]::sys::backtrace::__rust_end_short_backtrace::<std[8efa578c02603ef9]::panicking::begin_panic<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>::{closure#0}, !>
  10:        0x10f3e2f09 - std[8efa578c02603ef9]::panicking::begin_panic::<rustc_errors[8995f93e9c4bcc9a]::ExplicitBug>
  11:        0x10aa02276 - <rustc_errors[8995f93e9c4bcc9a]::diagnostic::BugAbort as rustc_errors[8995f93e9c4bcc9a]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:        0x10a817adc - <rustc_errors[8995f93e9c4bcc9a]::DiagCtxtHandle>::span_bug::<rustc_span[aed5394308446158]::span_encoding::Span, alloc[135510a28be92df]::string::String>
  13:        0x10a847cce - rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt::<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}
  14:        0x10a847d07 - rustc_middle[4384e439927f71dd]::ty::context::tls::with_opt::<rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:        0x10a833f05 - rustc_middle[4384e439927f71dd]::ty::context::tls::with_context_opt::<rustc_middle[4384e439927f71dd]::ty::context::tls::with_opt<rustc_middle[4384e439927f71dd]::util::bug::opt_span_bug_fmt<rustc_span[aed5394308446158]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:        0x10f3d11b2 - rustc_middle[4384e439927f71dd]::util::bug::span_bug_fmt::<rustc_span[aed5394308446158]::span_encoding::Span>
  17:        0x10a8e74ce - <rustc_const_eval[e6f1030e4695f1ae]::interpret::eval_context::InterpCx<rustc_const_eval[e6f1030e4695f1ae]::const_eval::machine::CompileTimeMachine>>::statement
  18:        0x10a9022c5 - rustc_const_eval[e6f1030e4695f1ae]::const_eval::eval_queries::eval_to_allocation_raw_provider
  19:        0x10c0204fc - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>
  20:        0x10bfd61fe - <rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2} as core[9412a59d758dca42]::ops::function::FnOnce<(rustc_middle[4384e439927f71dd]::ty::context::TyCtxt, rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>)>>::call_once
  21:        0x10be11bbd - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::DefaultCache<rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  22:        0x10c04aaac - rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  23:        0x10a830f92 - rustc_middle[4384e439927f71dd]::query::plumbing::query_get_at::<rustc_query_system[30bd0146b5104221]::query::caches::DefaultCache<rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>>
  24:        0x10a8febb0 - rustc_const_eval[e6f1030e4695f1ae]::const_eval::eval_queries::eval_to_const_value_raw_provider
  25:        0x10c020e9c - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>
  26:        0x10bfdb5ee - <rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2} as core[9412a59d758dca42]::ops::function::FnOnce<(rustc_middle[4384e439927f71dd]::ty::context::TyCtxt, rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>)>>::call_once
  27:        0x10be11bbd - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::DefaultCache<rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  28:        0x10c04b35c - rustc_query_impl[a24e9023943e74ab]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  29:        0x10b6b3ea6 - rustc_middle[4384e439927f71dd]::query::plumbing::query_get_at::<rustc_query_system[30bd0146b5104221]::query::caches::DefaultCache<rustc_middle[4384e439927f71dd]::ty::ParamEnvAnd<rustc_middle[4384e439927f71dd]::mir::interpret::GlobalId>, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 24usize]>>>
  30:        0x10b6b7fae - <rustc_middle[4384e439927f71dd]::ty::context::TyCtxt>::const_eval_global_id
  31:        0x10b6b78fd - <rustc_middle[4384e439927f71dd]::ty::context::TyCtxt>::const_eval_resolve
  32:        0x10b90558d - <rustc_const_eval[e6f1030e4695f1ae]::interpret::eval_context::InterpCx<rustc_const_eval[e6f1030e4695f1ae]::const_eval::dummy_machine::DummyMachine>>::eval_mir_constant::{closure#0}
  33:        0x10b9d7be5 - <rustc_mir_transform[6fada3a7f62d9c6e]::known_panics_lint::ConstPropagator>::eval_constant
  34:        0x10b9d8c35 - <rustc_mir_transform[6fada3a7f62d9c6e]::known_panics_lint::ConstPropagator as rustc_middle[4384e439927f71dd]::mir::visit::Visitor>::visit_assign
  35:        0x10b9de682 - <rustc_mir_transform[6fada3a7f62d9c6e]::known_panics_lint::ConstPropagator as rustc_middle[4384e439927f71dd]::mir::visit::Visitor>::visit_basic_block_data
  36:        0x10b9d869d - <rustc_mir_transform[6fada3a7f62d9c6e]::known_panics_lint::ConstPropagator as rustc_middle[4384e439927f71dd]::mir::visit::Visitor>::visit_body
  37:        0x10b9d500a - <rustc_mir_transform[6fada3a7f62d9c6e]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[6fada3a7f62d9c6e]::pass_manager::MirLint>::run_lint
  38:        0x10b976f44 - rustc_mir_transform[6fada3a7f62d9c6e]::pass_manager::run_passes_inner
  39:        0x10ba29e04 - rustc_mir_transform[6fada3a7f62d9c6e]::run_analysis_to_runtime_passes
  40:        0x10ba29957 - rustc_mir_transform[6fada3a7f62d9c6e]::mir_drops_elaborated_and_const_checked
  41:        0x10c0226ec - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 8usize]>>
  42:        0x10be9939e - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::VecCache<rustc_hir[ae2456c39d7f6170]::hir_id::OwnerId, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  43:        0x10c0338eb - rustc_query_impl[a24e9023943e74ab]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  44:        0x10b2daf1a - rustc_interface[73216d77aad0c3a5]::passes::run_required_analyses
  45:        0x10b2dccb3 - rustc_interface[73216d77aad0c3a5]::passes::analysis
  46:        0x10c022dec - rustc_query_impl[a24e9023943e74ab]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a24e9023943e74ab]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 1usize]>>
  47:        0x10be0249e - rustc_query_system[30bd0146b5104221]::query::plumbing::try_execute_query::<rustc_query_impl[a24e9023943e74ab]::DynamicConfig<rustc_query_system[30bd0146b5104221]::query::caches::SingleCache<rustc_middle[4384e439927f71dd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a24e9023943e74ab]::plumbing::QueryCtxt, false>
  48:        0x10c02d307 - rustc_query_impl[a24e9023943e74ab]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  49:        0x10a9258d7 - <rustc_interface[73216d77aad0c3a5]::queries::QueryResult<&rustc_middle[4384e439927f71dd]::ty::context::GlobalCtxt>>::enter::<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  50:        0x10a97fc94 - rustc_interface[73216d77aad0c3a5]::interface::run_compiler::<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}
  51:        0x10a96ec91 - std[8efa578c02603ef9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_with_globals<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_pool_with_globals<rustc_interface[73216d77aad0c3a5]::interface::run_compiler<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>
  52:        0x10a98a3a6 - <<std[8efa578c02603ef9]::thread::Builder>::spawn_unchecked_<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_with_globals<rustc_interface[73216d77aad0c3a5]::util::run_in_thread_pool_with_globals<rustc_interface[73216d77aad0c3a5]::interface::run_compiler<core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>, rustc_driver_impl[63f2171535a6fe49]::run_compiler::{closure#0}>::{closure#1}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9412a59d758dca42]::result::Result<(), rustc_span[aed5394308446158]::ErrorGuaranteed>>::{closure#2} as core[9412a59d758dca42]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:        0x1016f352b - std::sys::pal::unix::thread::Thread::new::thread_start::h68d49fa26efc1659
  54:     0x7ff801f5318b - __pthread_start

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/Documents/240624-57102.txt` to your bug report

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `main::promoted[1]`
#1 [eval_to_const_value_raw] simplifying constant for the type system `main::promoted[1]`  |  = note: this failure-note originates in the macro `assert_eq` which comes from the expansion of the macro `check` (in Nightly builds, run with -Z macro-backtrace for more info)

end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
```

</p>
</details>

### LINKED ISSUE #127737: ICE. `!base.layout().is_sized()`
auto-reduced (treereduce-rust):
````rust
pub trait TestTrait {
    type MyType;
    fn func() -> Option<Self>
    where
        Self: Sized;
}

impl<T> dyn TestTrait<MyType = T>
where
    Self: Sized,
{
    pub fn other_func() -> Option<Self> {
        match Self::func() {
            Some(me) => Some(me),
            None => None,
        }
    }
}


````

original:
````rust
//@ compile-flags: --crate-type=lib -Zmir-opt-level=2
//@ build-pass
// ^-- Must be build-pass, because check-pass will not run const prop.

pub trait TestTrait {
    type MyType;
    fn func() -> Option<Self>
    where
        Self: Sized;
}

impl<T> dyn TestTrait<MyType = T>
where
    Self: Sized,
{
    pub fn other_func() -> Option<Self> {
        match Self::func() {
            Some(me) => Some(me),
            None => None,
        }
    }
}

````

Version information
````
rustc 1.81.0-nightly (f8e4ac076 2024-07-14)
binary: rustc
commit-hash: f8e4ac0760216724f69b1ebc369bf03da56a7520
commit-date: 2024-07-14
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/compiler/rustc_const_eval/src/interpret/projection.rs:166:13:
assertion failed: !base.layout().is_sized()
stack backtrace:
   0:     0x723ebf105865 - std::backtrace_rs::backtrace::libunwind::trace::hd38d957c3cc252d2
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x723ebf105865 - std::backtrace_rs::backtrace::trace_unsynchronized::h1872a55102afa6eb
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x723ebf105865 - std::sys::backtrace::_print_fmt::h20dc7ce96546708c
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/sys/backtrace.rs:65:5
   3:     0x723ebf105865 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hc05f0077a6d9d85d
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/sys/backtrace.rs:40:26
   4:     0x723ebf1550eb - core::fmt::rt::Argument::fmt::hc83d8497f7eca888
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/core/src/fmt/rt.rs:173:76
   5:     0x723ebf1550eb - core::fmt::write::h018b5020a31eaee4
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/core/src/fmt/mod.rs:1182:21
   6:     0x723ebf0fa3cf - std::io::Write::write_fmt::ha03f1960d314b86c
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/io/mod.rs:1827:15
   7:     0x723ebf108051 - std::sys::backtrace::BacktraceLock::print::hb613464fb9731709
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/sys/backtrace.rs:43:9
   8:     0x723ebf108051 - std::panicking::default_hook::{{closure}}::h535fcea069b87644
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/panicking.rs:269:22
   9:     0x723ebf107d2c - std::panicking::default_hook::h8a985a1bbf049349
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/panicking.rs:296:9
  10:     0x723ebb5ec589 - std[7a47f84281342453]::panicking::update_hook::<alloc[b164795f67c102d1]::boxed::Box<rustc_driver_impl[a19efe568a6a6683]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x723ebf108a1f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0580c9dd81c802de
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/alloc/src/boxed.rs:2084:9
  12:     0x723ebf108a1f - std::panicking::rust_panic_with_hook::hdb4c410c90ba309a
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/panicking.rs:808:13
  13:     0x723ebf108613 - std::panicking::begin_panic_handler::{{closure}}::hd6b26adc9172d33b
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/panicking.rs:667:13
  14:     0x723ebf105d29 - std::sys::backtrace::__rust_end_short_backtrace::h3a27e3f65f32503b
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/sys/backtrace.rs:168:18
  15:     0x723ebf1082d4 - rust_begin_unwind
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/panicking.rs:665:5
  16:     0x723ebf1516a3 - core::panicking::panic_fmt::ha0ad70cf2f26aad8
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/core/src/panicking.rs:74:14
  17:     0x723ebf15172c - core::panicking::panic::h6e669894f5b53db5
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/core/src/panicking.rs:148:5
  18:     0x723ebe4411b7 - <rustc_const_eval[fd17e0cfdd0bd9e3]::interpret::eval_context::InterpCx<rustc_const_eval[fd17e0cfdd0bd9e3]::const_eval::dummy_machine::DummyMachine>>::project_field::<rustc_const_eval[fd17e0cfdd0bd9e3]::interpret::operand::OpTy>.cold
  19:     0x723ebbe1e851 - <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant::{closure#0}
  20:     0x723ebbd479eb - <rustc_mir_dataflow[538483daff6f33a9]::value_analysis::Map>::for_each_projection_value::<rustc_const_eval[fd17e0cfdd0bd9e3]::interpret::operand::OpTy, <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant::{closure#0}, <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant::{closure#1}>
  21:     0x723ebbd47a6c - <rustc_mir_dataflow[538483daff6f33a9]::value_analysis::Map>::for_each_projection_value::<rustc_const_eval[fd17e0cfdd0bd9e3]::interpret::operand::OpTy, <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant::{closure#0}, <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant::{closure#1}>
  22:     0x723ebbe1e806 - <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_constant
  23:     0x723ebbdd6ba0 - <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::ConstAnalysis>::assign_operand
  24:     0x723ebbe1cc4d - <rustc_mir_transform[a9e991cd80486376]::dataflow_const_prop::DataflowConstProp as rustc_middle[b63224948423896b]::mir::MirPass>::run_pass
  25:     0x723ebcc01cbb - rustc_mir_transform[a9e991cd80486376]::pass_manager::run_passes_inner
  26:     0x723ebd15eed6 - rustc_mir_transform[a9e991cd80486376]::optimized_mir
  27:     0x723ebdaab21b - rustc_query_impl[a0d93f3a76d1e236]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a0d93f3a76d1e236]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b63224948423896b]::query::erase::Erased<[u8; 8usize]>>
  28:     0x723ebced50e3 - rustc_query_system[967e3c5480e09d8a]::query::plumbing::try_execute_query::<rustc_query_impl[a0d93f3a76d1e236]::DynamicConfig<rustc_query_system[967e3c5480e09d8a]::query::caches::DefIdCache<rustc_middle[b63224948423896b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a0d93f3a76d1e236]::plumbing::QueryCtxt, false>
  29:     0x723ebced48e0 - rustc_query_impl[a0d93f3a76d1e236]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  30:     0x723ebd3f4023 - rustc_middle[b63224948423896b]::query::plumbing::query_get_at::<rustc_query_system[967e3c5480e09d8a]::query::caches::DefIdCache<rustc_middle[b63224948423896b]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x723ebd3f9aa1 - <rustc_metadata[e0a5a3ee2c4f394f]::rmeta::encoder::EncodeContext>::encode_crate_root
  32:     0x723ebdc7e31e - rustc_metadata[e0a5a3ee2c4f394f]::rmeta::encoder::encode_metadata
  33:     0x723ebdc7c3f4 - rustc_metadata[e0a5a3ee2c4f394f]::fs::encode_and_write_metadata
  34:     0x723ebdc7b083 - <rustc_interface[f891d35c33df0120]::queries::Linker>::codegen_and_build_linker
  35:     0x723ebd9c0676 - rustc_interface[f891d35c33df0120]::interface::run_compiler::<core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>, rustc_driver_impl[a19efe568a6a6683]::run_compiler::{closure#0}>::{closure#1}
  36:     0x723ebd99cc09 - std[7a47f84281342453]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f891d35c33df0120]::util::run_in_thread_with_globals<rustc_interface[f891d35c33df0120]::util::run_in_thread_pool_with_globals<rustc_interface[f891d35c33df0120]::interface::run_compiler<core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>, rustc_driver_impl[a19efe568a6a6683]::run_compiler::{closure#0}>::{closure#1}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>::{closure#0}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>
  37:     0x723ebd99c9ba - <<std[7a47f84281342453]::thread::Builder>::spawn_unchecked_<rustc_interface[f891d35c33df0120]::util::run_in_thread_with_globals<rustc_interface[f891d35c33df0120]::util::run_in_thread_pool_with_globals<rustc_interface[f891d35c33df0120]::interface::run_compiler<core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>, rustc_driver_impl[a19efe568a6a6683]::run_compiler::{closure#0}>::{closure#1}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>::{closure#0}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c27b473aec29ed1]::result::Result<(), rustc_span[8a5224f023f17529]::ErrorGuaranteed>>::{closure#2} as core[5c27b473aec29ed1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x723ebf1128cb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf9b8e00cff207f55
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/alloc/src/boxed.rs:2070:9
  39:     0x723ebf1128cb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd33bea353aae3a46
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/alloc/src/boxed.rs:2070:9
  40:     0x723ebf1128cb - std::sys::pal::unix::thread::Thread::new::thread_start::hb95383f957b5020b
                               at /rustc/f8e4ac0760216724f69b1ebc369bf03da56a7520/library/std/src/sys/pal/unix/thread.rs:108:17
  41:     0x723eb80a6ded - <unknown>
  42:     0x723eb812a0dc - <unknown>
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (f8e4ac076 2024-07-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<impl at /tmp/icemaker_global_tempdir.4HXXv5pAmPjZ/rustc_testrunner_tmpdir_reporting.8X4UesCacdRf/mvce.rs:8:1: 10:17>::other_func`
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by lukas-code**
This PR reworks the layout computation to eagerly return an error when encountering an unsized field where a sized field was expected, rather than delaying a bug and attempting to recover a layout. This is required, because with trivially false where clauses like `[T]: Sized`, any field can possible be an unsized type, without causing a compile error.

Since this PR removes the `delayed_bug` method from the `LayoutCalculator` trait, it essentially becomes the same as the `HasDataLayout` trait, so I've also refactored the `LayoutCalculator` to be a simple wrapper struct around a type that implements `HasDataLayout`.

The majority of the diff is whitespace changes, so viewing with whitespace ignored is advised.

implements https://github.com/rust-lang/rust/pull/123169#issuecomment-2025788480

r? @compiler-errors or compiler

fixes https://github.com/rust-lang/rust/issues/123134
fixes https://github.com/rust-lang/rust/issues/124182
fixes https://github.com/rust-lang/rust/issues/126939
fixes https://github.com/rust-lang/rust/issues/127737

### CODE REVIEW

**Review by Veykril — APPROVED** [review]
r-a side

File: compiler/rustc_ty_utils/src/layout.rs [hunk 1]
```diff
@@ -80,7 +80,36 @@ fn layout_of<'tcx>(
...
+            LayoutError::SizeOverflow(ty)
+        }
+        LayoutCalculatorError::UnexpectedUnsized => {
+            // This is sometimes not a compile error if there are trivially false where
+            // clauses, but it is always a compiler error in the empty environment.
+            if cx.param_env.caller_bounds().is_empty() {
+                cx.tcx().dcx().delayed_bug(format!(
+                    "encountered unexpected unsized field in layout of {ty:?}"
+                ));
+            }
```
Comment (compiler-errors) [inline compiler/rustc_ty_utils/src/layout.rs:103]: We could perhaps attempt to prove that the type is sized here.

Comment (compiler-errors) [reply compiler/rustc_ty_utils/src/layout.rs:103]: Also would be useful to point to an example.

Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout.rs:103]: > We could perhaps attempt to prove that the type is sized here.

The final type is not always guaranteed to be `Sized` (in the type system way), for example given
```rust
#![feature(trivial_bounds)]
struct Foo
where
    [u8]: Sized,
{
    a: [u8],
    b: [u16],
}
```

the trait bound `Foo: Sized` will not hold, but attempting to compute the layout of `Foo` will error with `UnexpectedUnsized`.

Comment (compiler-errors) [reply compiler/rustc_ty_utils/src/layout.rs:103]: Right, but shouldn't we be able to prove that the type is sized within the param-env we're computing the layout? Or otherwise, why would we care that the param-env has no clauses?

Comment (compiler-errors) [reply compiler/rustc_ty_utils/src/layout.rs:103]: Like, I'd want to double check that the param-env in fact does contain `[u8]: Sized` rather than just checking that the param-env is non-empty.

Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout.rs:103]: Right, makes sense to check for the field itself. I'll try to add this check.

File: compiler/rustc_ty_utils/src/layout.rs [hunk 2]
```diff
@@ -80,7 +80,36 @@ fn layout_of<'tcx>(
...
+}
+
+fn map_error<'tcx>(
+    cx: &LayoutCx<'tcx>,
+    ty: Ty<'tcx>,
+    err: LayoutCalculatorError,
+) -> &'tcx LayoutError<'tcx> {
+    let err = match err {
+        LayoutCalculatorError::SizeOverflow => {
+            // This is sometimes not a compile error in `check` builds.
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_ty_utils/src/layout.rs:93]: Yeah, it wouldn't hurt.

File: compiler/rustc_ty_utils/src/layout.rs (hunk 1 above)
Comment (lukas-code) [reply compiler/rustc_ty_utils/src/layout.rs]: Ok, I've replaced the check for an empty param-env with a check that the layout-unsized field is type-system-sized now.

Also, looking at the code again, I found that an old hack could now be replaced, so I did that in another commit.

File: compiler/rustc_abi/src/layout.rs [hunk 3]
```diff
@@ -97,16 +99,17 @@ impl<Cx: HasDataLayout> LayoutCalculator<Cx> {
     }
 
     pub fn univariant<
-        'a,
+        'fields,
```
Comment (compiler-errors) [inline compiler/rustc_abi/src/layout.rs:102]: Huh... is it possible for us to just require `F: Copy` rather than passing around `&'fields F` everywhere? It seems a bit redundant.

File: compiler/rustc_index/src/slice.rs [hunk 4]
```diff
@@ -20,7 +20,7 @@ pub struct IndexSlice<I: Idx, T> {
 
 impl<I: Idx, T> IndexSlice<I, T> {
     #[inline]
-    pub const fn empty() -> &'static Self {
+    pub const fn empty<'a>() -> &'a Self {
```
Comment (compiler-errors) [inline compiler/rustc_index/src/slice.rs:23]: Is this because of invariance or what?

File: compiler/rustc_ty_utils/src/layout.rs [hunk 5]
```diff
@@ -79,31 +78,58 @@ fn layout_of<'tcx>(
...
+            // See `tests/ui/limits/huge-enum.rs` for an example.
+            LayoutError::SizeOverflow(ty)
+        }
+        LayoutCalculatorError::UnexpectedUnsized(field) => {
+            // This is sometimes not a compile error if there are trivially false where clauses.
+            // See `tests/ui/layout/trivial-bounds-sized.rs` for an example.
+            assert!(field.layout.is_unsized(), "invalid layout error {err:#?}");
+            if !field.ty.is_sized(cx.tcx(), cx.param_env) {
```
Comment (compiler-errors) [inline compiler/rustc_ty_utils/src/layout.rs:100]: 👍

File: compiler/rustc_index/src/slice.rs (hunk 4 above)
Comment (lukas-code) [reply compiler/rustc_index/src/slice.rs:23]: Yeah this function is used here https://github.com/rust-lang/rust/blob/4edbd9320b39592a2af26ca5cb68018fadebc3fa/compiler/rustc_ty_utils/src/layout.rs#L374-L380

And changing the lifetime from `'_` to `'tcx` here https://github.com/rust-lang/rust/blob/4edbd9320b39592a2af26ca5cb68018fadebc3fa/compiler/rustc_ty_utils/src/layout.rs#L119

means that we would now create a `&'static &'tcx Something` which would require `'tcx: 'static`,

File: compiler/rustc_abi/src/layout.rs (hunk 3 above)
Comment (lukas-code) [reply compiler/rustc_abi/src/layout.rs:102]: Yes that's possible and much cleaner. Idk why I tried so hard to make lifetimes happen here :upside_down_face:

File: compiler/rustc_index/src/slice.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_index/src/slice.rs:23]: Ah, ok. Yeah, that makes sense 👍

**Review by compiler-errors — APPROVED** [review]
Great work!

**Comment by compiler-errors** [comment]
r=me when green
