### PR TITLE
Do not mention private types from other crates as impl candidates

### LINKED ISSUE #99080: "The following types implement trait..." suggets crate private items, if inside macro.
There are two crates here, `library` and `consumer` (which depends on `library`).

library:
```rust
#![feature(decl_macro)]

pub macro global_meow($item:expr) {
    const _: () = { 
        fn foo() {
            Meow::meow(&$item);
        }
    };
}

#[macro_export]
macro_rules! global_meow_rules {
    ($item:expr) => {
        const _: () = { 
            fn foo() {
                $crate::Meow::meow(&$item);
            }
        };
    }
}

pub trait Meow {
    fn meow(&self) {}
}

pub struct GlobalMeow;

impl Meow for GlobalMeow { }

pub(crate) struct PrivateMeow;

impl Meow for PrivateMeow { }
```

consumer:
```rust
static NOT_MEOW: usize = 0;

library::global_meow!(NOT_MEOW);

library::global_meow_rules!(NOT_MEOW);

fn main() {}
```

The current output is (when running `cargo check` on `consumer`):

```rust
# cargo check
    Checking consumer v0.1.0 (/tmp/scratcho2FpPeJDq/consumer)
error[E0277]: the trait bound `usize: Meow` is not satisfied
 --> src/main.rs:2:1
  |
2 | library::global_meow!(NOT_MEOW);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Meow` is not implemented for `usize`
  |
  = help: the following other types implement trait `Meow`:
            GlobalMeow
            library::PrivateMeow
  = note: this error originates in the macro `library::global_meow` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `usize: Meow` is not satisfied
 --> src/main.rs:4:1
  |
4 | library::global_meow_rules!(NOT_MEOW);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Meow` is not implemented for `usize`
  |
  = help: the following other types implement trait `Meow`:
            GlobalMeow
            library::PrivateMeow
  = note: this error originates in the macro `library::global_meow_rules` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Ideally the output should look like:

```
# cargo check
    Checking consumer v0.1.0 (/tmp/scratcho2FpPeJDq/consumer)
error[E0277]: the trait bound `usize: Meow` is not satisfied
 --> src/main.rs:2:1
  |
2 | library::global_meow!(NOT_MEOW);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Meow` is not implemented for `usize`
  |
  = help: the following other types implement trait `Meow`:
            GlobalMeow
  = note: this error originates in the macro `library::global_meow` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `usize: Meow` is not satisfied
 --> src/main.rs:4:1
  |
4 | library::global_meow_rules!(NOT_MEOW);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Meow` is not implemented for `usize`
  |
  = help: the following other types implement trait `Meow`:
            GlobalMeow
  = note: this error originates in the macro `library::global_meow_rules` (in Nightly builds, run with -Z macro-backtrace for more info)
```

We should not be suggesting private types to users, since macro hygiene *does* mean they can't write `library::PrivateMeow`

This is on the latest nightly, `rustc 1.64.0-nightly (06754d885 2022-07-08)`

This was ran into in https://github.com/rust-lang/rust/pull/99074

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #99080

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -1805,8 +1805,27 @@ impl<'a, 'tcx> InferCtxtPrivExt<'a, 'tcx> for InferCtxt<'a, 'tcx> {
                         || self.tcx.is_builtin_derive(def_id)
                 })
                 .filter_map(|def_id| self.tcx.impl_trait_ref(def_id))
-                // Avoid mentioning type parameters.
-                .filter(|trait_ref| !matches!(trait_ref.self_ty().kind(), ty::Param(_)))
+                .filter(|trait_ref| {
+                    // Avoid mentioning type parameters.
```
Comment (5225225) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1809]: Was it intentional to have this comment twice?

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1809]: No, lol
