### PR TITLE
Fix linker failure on windows

### LINKED ISSUE #38933: ICE on unwrap on windows
Here is the full output:

```bash
D:\process-viewer> cargo build
   Compiling process_viewer v0.0.4 (file:///D:/process-viewer)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with 'RUST_BACKTRACE=1' for a backtrace

thread 'rustc' panicked at 'called 'Result::unwrap()' on an 'Err' value: JoinPathsError { inner: JoinPathsError }', C:\bot\slave\nightly-dist-rustc-win-gnu-64\build\src\libcore\result.rs:845
stack backtrace:
   0:         0x6eab09f2 - <unknown>
   1:         0x6eab01d1 - <unknown>
   2:         0x6eab1bba - <unknown>
   3:         0x6eab1a56 - <unknown>
   4:         0x6eab1979 - <unknown>
   5:         0x6eab18fb - <unknown>
   6:         0x6eac1a55 - <unknown>
   7:         0x6cf0d86f - <unknown>
   8:         0x6cfc95e5 - <unknown>
   9:         0x6cfbfbd3 - <unknown>
  10:         0x6cfb7806 - <unknown>
  11:         0x6d006e56 - <unknown>
  12:         0x6cf0ae35 - <unknown>
  13:         0x6eab4fb8 - <unknown>
  14:         0x6cf29054 - <unknown>
  15:         0x6eaae482 - <unknown>
  16:     0x7ffa36618363 - <unknown>

error: Could not compile 'process_viewer'.

To learn more, run the command again with --verbose.
```

I'm running on windows with the following version:

```bash
D:\process-viewer>rustc --version
rustc 1.16.0-nightly (4ecc85beb 2016-12-28)
```

And here is the "problematic" code:

```rust
#[cfg(target_os = "windows")]
extern crate pkg_config;

#[cfg(target_os = "windows")]
fn main() {
    use std::env;
    let libs_to_find = ["glib-2.0", "gobject-2.0", "pango-1.0", "gio-2.0", "atk-1.0",
                        "gdk-pixbuf-2.0", "cairo", "gdk-3", "gtk-3"];
    if let Ok(lib_dir) = env::var("GTK_LIB_DIR") {
        for lib_ in libs_to_find.iter() {
            println!("cargo:rustc-link-lib=dylib={}", lib_);
        }
        println!("cargo:rustc-link-search=native={}", lib_dir);
    } else {
        for lib in libs_to_find.iter() {
            pkg_config::probe_library(lib).unwrap();
        }
    }
}

#[cfg(not(target_os = "windows"))]
fn main() {}
```

I have put the problematic branch/PR [here](https://github.com/GuillaumeGomez/process-viewer/pull/51).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #38933.

r? @ollie27

### CODE REVIEW

File: src/librustc_driver/driver.rs [hunk 1]
```diff
@@ -667,7 +667,9 @@ pub fn phase_2_configure_and_expand<F>(sess: &Session,
                     new_path.push(path);
                 }
             }
-            env::set_var("PATH", &env::join_paths(new_path).unwrap());
+            if let Ok(p) = env::join_paths(new_path) {
```
Comment (nagisa) [inline src/librustc_driver/driver.rs]: Instead of not setting `PATH` altogether, we should just ignore the components that make construction of the `PATH` to fail.

Comment (GuillaumeGomez) [inline src/librustc_driver/driver.rs]: It would give an invalid PATH. Not sure this is what we want... At least, the current change doesn't set the variable at all if any path is not valid.

Comment (nagisa) [inline src/librustc_driver/driver.rs]: > It would give an invalid PATH.

What? Of course it would become a valid `PATH` once you filter out all the parts that can’t be put into `PATH`. Maybe it would not be complete, but certainly valid.

What your current patch does, on the other hand, is making whatever function this code had not come into effect whenever there’s any path from *any* source that cannot be put into `PATH`.

Comment (GuillaumeGomez) [inline src/librustc_driver/driver.rs]: I think I missed something then. In here, we just join 2 paths, if one is invalid, we should only keep the other one, right? I'll try to update in this way then.

**Comment by GuillaumeGomez** [comment]
@nagisa: Better?

**Comment by nagisa** [comment]
Remembering that `$PATH` and `sess.host_filesearch(PathKind::All).get_dylib_search_paths()` both are collection of pathes (i.e. `vec![p1, p2, p3, ...]` and vec![dsp1, dsp2, dsp3, ...]`) and we want to merge them into a single `$PATH`… pathes from `$PATH` cannot be invalid as they are parsed from the same `$PATH`, but the `dsp1..` could be. Even then you still want to join them as they have some purpose – not merging any of the `dsp*` in when only `dsp42` is invalid seems lazy.

So here’s some implementation strategies I had in mind:

```
// validate pathes by joining them one by one:
env::join_paths(new_paths.filter(|p| env::join_paths(iter::once(path)).is_ok()));
``` 

or

```
// write an iterator such that
struct Iter<E: Clone> { last_yielded: E, other: ... }

loop {
let i = Iter { ... };
let r = env::join_paths(i);
if r.is_ok() { break; }
// i.last_yielded is the invalid component, remove and retry.
}
``` 

does it make what I meant any clearer?

**Comment by GuillaumeGomez** [comment]
Indeed. I'll just take your first example then.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
Any news @nagisa?

**Comment by nagisa** [comment]
This approach LGTM to me.
