### PR TITLE
Clarify iterator by_ref docs

### LINKED ISSUE #95143: Unclear doc on iterator.by_ref()
Today, I just got a huge problem internally in one of my crate. The bug is that the call to `iterator.by_ref` mutates/advances the iterator itself internally and that caused one of my software dependent on that carate to fail with an internal weird panic. 

On the following documentation link: https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.by_ref the behavior of the function is not very clear.

The doc currently reads:

```
Borrows an iterator, rather than consuming it.

This is useful to allow applying iterator adapters while still retaining ownership of the original iterator.
```

From this text it's not clear that using this function still mutates/advances the internal iterator, so calling count for example is still gonna put the iterator to the end and will break all subsequent calls, essentially ending in weird cases where somehow the number of items is 1 but the later call to `last().unwrap()` panics!

### PR DESCRIPTION
**Pull request by hkBst**
fixes #95143

### CODE REVIEW

File: library/core/src/iter/traits/iterator.rs [hunk 1]
```diff
@@ -1825,10 +1825,16 @@ pub trait Iterator {
...
     }
 
-    /// Borrows an iterator, rather than consuming it.
+    /// If you use a consuming method on an iterator,
+    /// the iterator is consumed by the method and cannot be used afterwards.
+    /// This method allows you to mutably borrow an iterator,
+    /// such that consuming methods don't consume the original.
     ///
-    /// This is useful to allow applying iterator adapters while still
-    /// retaining ownership of the original iterator.
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:1831]: I don't think this part of the diff is necessary. The one-liner at the top and the explanation seems sufficient, maybe just adding a disclaimer that the original iterator is still mutated is enough.

File: library/core/src/iter/traits/iterator.rs [hunk 2]
```diff
@@ -1825,10 +1825,16 @@ pub trait Iterator {
...
+    /// This turns an iterator into its mutably-borrowed iterator via
+    /// [impl<I: Iterator + ?Sized> Iterator for &mut I { type Item = I::Item; ...}](trait.Iterator.html#impl-Iterator-for-&mut I).
+    /// This allows using consuming methods on the mutable borrow,
+    /// which then consume the mutable borrow instead of the original,
+    /// such that you can continue to use the original iterator afterwards.
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:1837]:
```suggestion
    /// This method returns a mutable borrow of the iterator, which also
    /// implements the [`Iterator`] trait. This allows you to use iterator adapters
    /// through the reference, which will mutate but still retain ownership of
    /// the original iterator.
```

**Review by ibraheemdev — CHANGES_REQUESTED** [review]

File: library/core/src/iter/traits/iterator.rs (hunk 1 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1831]: "Borrows an iterator, rather than consuming it." is quite poorly phrased, as it is subsequent methods applied to the borrow, that will be prevented from consuming the original iterator.
"This is useful to allow applying iterator adapters while still retaining ownership of the original iterator." is also quite opaque, as it is already possible to do just that with the original iterator, except if the method happens to take self, but that crucial detail is not mentioned.

In addition to this, it is not obvious how the mutable borrow of an iterator turns into an iterator. It wasn't until I started writing this PR that I thought to myself: "wait a minute, there is no reason a mutable borrow of an iterator should be an iterator, unless there is an impl block that says so." Before that, I think I thought something like this: "I must be missing something about how mutable references work, because I don't see how this method works..." It is just like the `chars` method on Strings giving a Chars struct which impls iterator, except that there is no `&mut impl Iterator` struct to point to, therefore I think it makes sense to link to the relevant impl directly, to show that there is no magic here.

File: library/core/src/iter/traits/iterator.rs (hunk 2 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1837]: I agree that it is important to say that the original iterator is mutated when the &mut is used.

**Comment by hkBst** [comment]
@ibraheemdev I've tried to reformulate. Let me know if it is better.

File: library/core/src/iter/traits/iterator.rs (hunk 1 above)
Comment (ibraheemdev) [reply library/core/src/iter/traits/iterator.rs:1831]: I see what you are getting at, but I feel that this is a bit wordy. Let me try rewording it.

File: library/core/src/iter/traits/iterator.rs [hunk 3]
```diff
@@ -1825,10 +1825,24 @@ pub trait Iterator {
...
+    /// except that all consuming methods behave like mutating methods,
+    /// which mutate the original iterator, without taking ownership of it.
+    ///
+    /// This works, because the mutable reference that this method returns,
+    /// implements the `Iterator` trait in its own right via:
+    /// [impl<I: Iterator + ?Sized> Iterator for &mut I { type Item = I::Item; ...}](trait.Iterator.html#impl-Iterator-for-%26mut I).
+    /// This implementation simply passes all method calls on to the original iterator,
+    /// allowing you to call a consuming iterator method on the mutable reference,
+    /// which will mutate the original,
+    /// without giving up ownership of the original iterator.
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:1845]:
```suggestion
    /// Creates a "by reference" adapter for this instance of `Iterator`.
    ///
    /// The returned adapter also implements `Iterator` and will simply borrow
    /// this current iterator. Any iteration performed through the reference
    /// will mutate the original iterator.
    ///
    /// Most `Iterator` methods are consuming methods, returning adapters
    /// that take ownership of the iterator. This method allows you to mutate
    /// the original iterator without giving up ownership of it, consuming the
    /// reference instead of the iterator itself.
```

**Review by ibraheemdev — CHANGES_REQUESTED** [review]

File: library/core/src/iter/traits/iterator.rs [hunk 4]
```diff
@@ -4019,6 +4033,7 @@ where
     }
 }
 
+/// Implements Iterator for mutable references to Iterator, such as those produced by [Iterator::by_ref]
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:4036]:
```suggestion
/// Implements `Iterator` for mutable references to iterators, such as those produced by [`Iterator::by_ref`].
```

File: library/core/src/iter/traits/iterator.rs (hunk 1 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1831]: Alright, there should be a short one sentence summary at the top, can do.

File: library/core/src/iter/traits/iterator.rs (hunk 3 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1845]: Oh, consuming methods is not very good, since the book says: [Methods that call next are called consuming adapters, because calling them uses up the iterator.](https://doc.rust-lang.org/book/ch13-02-iterators.html#methods-that-consume-the-iterator) The original text already talks about consuming the iterator, which is also no good.

And, [Iterator adapters are methods defined on the Iterator trait that don’t consume the iterator. Instead, they produce different iterators by changing some aspect of the original iterator.](https://doc.rust-lang.org/book/ch13-02-iterators.html#methods-that-produce-other-iterators). You're using the term adapter for the return value of a method here instead of for the method itself.

File: library/core/src/iter/traits/iterator.rs (hunk 4 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:4036]: Done.

File: library/core/src/iter/traits/iterator.rs (hunk 3 above)
Comment (ibraheemdev) [reply library/core/src/iter/traits/iterator.rs:1845]: > Oh, consuming methods is not very good, since the book says: [Methods that call next are called consuming adapters, because calling them uses up the iterator.](https://doc.rust-lang.org/book/ch13-02-iterators.html#methods-that-consume-the-iterator) The original text already talks about consuming the iterator, which is also no good.

That part is from your version :) Maybe we can just say "most `Iterator` methods return adapters that take ownership of the original iterator" instead?

> And, [Iterator adapters are methods defined on the Iterator trait that don’t consume the iterator. Instead, they produce different iterators by changing some aspect of the original iterator.](https://doc.rust-lang.org/book/ch13-02-iterators.html#methods-that-produce-other-iterators). You're using the term adapter for the return value of a method here instead of for the method itself.

I think we use the two interchangeably. For example, the docs of `Iterator::for_each` say:
> In some cases for_each may also be faster than a loop, because it will use internal iteration on adapters like `Chain`.

We don't have to be too nitpicky with the terminology as long as it gets the point across, I don't want to have three paragraphs to explain that `by_ref` returns an iterator that mutates the original when it is used.

**Comment by hkBst** [comment]
Another attempt, less wordy and with a one-sentence summary. Also no more confusing uses of consuming. Let me know what you think.

File: library/core/src/iter/traits/iterator.rs [hunk 5]
```diff
@@ -1825,10 +1825,20 @@ pub trait Iterator {
...
+    /// This method retuns a mutable reference to the original iterator,
+    /// that acts like the original iterator in all respects,
+    /// except that ownership-taking methods take ownership of the reference instead of of the original.
+    /// All mutation by ownership-taking methods will still mutate the original iterator.
+    ///
+    /// # Technical details
+    ///
+    /// The mutable reference that this method returns, implements the `Iterator` trait via:
+    /// [impl<I: Iterator + ?Sized> Iterator for &mut I { type Item = I::Item; ...}](trait.Iterator.html#impl-Iterator-for-%26mut I).
+    /// This implementation simply passes all method calls on to the original iterator.
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:1841]:
```suggestion
    /// Most `Iterator` adapters take ownership (via a `self` parameter) of the iterator.
    /// This method returns a mutable reference to the original, which implements the
    /// iterator trait by delegating to the original iterator. This allows iterator adapters
    /// to take ownership of the reference, mutating the original iterator while retaining
    /// ownership.
```

- It's not true that only `next` doesn't take ownership, there are other methods like `nth` and `advance_by`.
- "and mutate it" isn't exactly true, because the methods themselves don't mutate the iterator. We can just omit this.
- "mutation by ownership-taking methods" is a little awkward, I updated the wording to use "adapters" to refer to the adapter methods explicitly.
- The hyperlink to the iterator implementation doesn't seem to work: https://github.com/rust-lang/rust/issues/105600. I added a written explanation instead.

Does that seem reasonable?

File: library/core/src/iter/traits/iterator.rs [hunk 6]
```diff
@@ -1825,10 +1825,20 @@ pub trait Iterator {
         Inspect::new(self, f)
     }
 
-    /// Borrows an iterator, rather than consuming it.
+    /// Iterator adapter that turns ownership-taking methods into mutating methods.
```
Comment (ibraheemdev) [inline library/core/src/iter/traits/iterator.rs:1828]:
```suggestion
    /// Creates a "by reference" adapter for this instance of `Iterator`.
```

I know this is a little vague, but the way you've written it reads awkwardly. The original seems fine as well with the new explanation. It's hard to fit exactly what we want to say into one sentence, so I think being general is fine.

File: library/core/src/iter/traits/iterator.rs (hunk 5 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs]: > * It's not true that only `next` doesn't take ownership, there are other methods like `nth` and `advance_by`.

That's why the text says "Most .. methods", but I thought it important to mention `next` as an exception because it is so fundamental. Of the [76 methods listed](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html) only 17 don't take `self`, so 59 methods do, which certainly counts as most, no? But I would also be happy with "many" instead of "most"... I see that your proposed replacement differs mostly by replacing "methods" with "adapters" but all of, and `advance_by` are adapters and `next` and `nth` arguably even "iterator adapters" (because Option impls Iterator). 

> * "and mutate it" isn't exactly true, because the methods themselves don't mutate the iterator. We can just omit this.

It is true! They take ownership and then you have no way of knowing what they do, but in fact they do mutate the iterator, which you can see if you use by_ref to prevent ownership-taking! I think it is important to mention this, because then it cannot be a surprise if after preventing ownership taking these methods still (!!!) mutate the original. They always mutate the original. The only difference is in whether ownership is transferred or not.

> * "mutation by ownership-taking methods" is a little awkward, I updated the wording to use "adapters" to refer to the adapter methods explicitly, which I explained take ownership.

The book calls `next` an adapter and it does not take ownership. The book names consuming adapters (next and other methods that call next), iterator adapters (methods whose return value impls iterator (next returns an Option which is an iterator, so arguably it is also an iterator adapter)), and other methods (only size_hint?).

> * The hyperlink to the iterator implementation doesn't seem to work:

Should work now... thanks for catching!

File: library/core/src/iter/traits/iterator.rs (hunk 6 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1828]: Alright, I agree that my phrasing is perhaps not good, and the other explanation is now better, so the summary can be simpler. Going off your "by reference" iterator, how about something like: "Iterator adapter that passes on method calls to the original iterator by mutable reference."?

Comment (ibraheemdev) [reply library/core/src/iter/traits/iterator.rs:1828]: How about we keep my suggestion for now to mirror `io::{Read, Write}::by_ref` and `Allocator::by_ref`, and you can open a separate PR to discuss changing it? I don't want to get too hung up on this.

File: library/core/src/iter/traits/iterator.rs (hunk 5 above)
Comment (ibraheemdev) [reply library/core/src/iter/traits/iterator.rs]: > That's why the text says "Most .. methods", but I thought it important to mention next as an exception because it is so fundamental.

My only concern was that "other than the `next` method (and this one)" seems to suggest that every other iterator method is consuming.

> It is true! They take ownership and then you have no way of knowing what they do, but in fact they do mutate the iterator, which you can see if you use by_ref to prevent ownership-taking

Right, but the methods themselves don't mutate it, they simply return a new iterator adapter/wrapper.

> The book calls next an adapter and it does not take ownership. The book names consuming adapters (next and other methods that call next), iterator adapters (methods whose return value impls iterator (next returns an Option which is an iterator, so arguably it is also an iterator adapter)), and other methods (only size_hint?).

Sure, but we already clarified that we are talking about adapters that consume `self` in the previous sentence.

File: library/core/src/iter/traits/iterator.rs (hunk 6 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs:1828]: Alright, done.

**Comment by hkBst** [comment]
Alright, going back to basics. I hope nothing here is controversial. We've both invested way too much time here.

**Comment by ibraheemdev** [comment]
I'd like someone with fresh eyes to take a look at this. Sorry if I'm being too nitpicky. r? libs

**Comment by hkBst** [comment]
> I'd like someone with fresh eyes to take a look at this. Sorry if was being too nitpicky. r? libs

It's important to get this stuff right, so being nitpicky is just a necessity... I'm sorry I couldn't find a formulation that was a clear enough improvement. Now if only I could remember that command to switch the author too... ;P 

Anyway, thanks for your input, effort, and persistence.

File: library/core/src/iter/traits/iterator.rs [hunk 7]
```diff
@@ -1825,10 +1825,18 @@ pub trait Iterator {
...
+    /// Creates a "by reference" adapter for this instance of `Iterator`.
     ///
-    /// This is useful to allow applying iterator adapters while still
-    /// retaining ownership of the original iterator.
+    /// Consuming method calls (direct or indirect calls to `next`)
+    /// on the "by reference" adapter will consume the original iterator,
+    /// but ownership-taking methods (those with a `self` parameter)
+    /// only take ownership of the "by reference" iterator.
+    ///
+    /// This is useful to allow applying ownership-taking methods,
```
Comment (joboet) [inline library/core/src/iter/traits/iterator.rs:1835]:
```suggestion
    /// This is useful to allow applying ownership-taking methods
```
:wink:

Comment (joboet) [reply library/core/src/iter/traits/iterator.rs:1835]: I'd also give an example for such a method (perhaps `count`?), so people have a really clear understanding of what this could be used for.

**Review by joboet — COMMENTED** [review]
I think this is a good improvement over the previous doc. One suggestion though:

File: library/core/src/iter/traits/iterator.rs (hunk 7 above)
Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs]: I've implemented your suggestion. Let me know if you think this is better.

Comment (hkBst) [reply library/core/src/iter/traits/iterator.rs]: @rustbot ready

**Comment by joboet** [comment]
Great, thank you!
@bors r+ rollup
