### PR TITLE
Specific error message for missplaced doc comments

### LINKED ISSUE #27429: Confusing Error Message When Doc Comment inside Array
Probably a few other places where it's also confusing.

Should probably state something like 'unexpected doc comment. A doc comment must precede an item`.

```rust
fn main() { let a = [1.0, 1.0 /** b */, 1.0]; }
```

```
<anon>:1:31: 1:39 error: expected one of `,`, `.`, or an operator, found `/** b */`
<anon>:1 fn main() { let a = [1.0, 1.0 /** b */, 1.0]; }
                                       ^~~~~~~~
playpen: application terminated with error code 101
```

### PR DESCRIPTION
**Pull request by estebank**
Identify when documetation comments have been missplaced in the following places:
- After a struct element:
  
  ``` rust
  // file.rs:
  struct X {
      a: u8 /** document a */,
  }
  ```
  
  ``` bash
  $ rustc file.rs
  file.rs:2:11: 2:28 error: found documentation comment that doesn't
  document anything
  file.rs:2     a: u8 /** document a */,
                      ^~~~~~~~~~~~~~~~~
  file.rs:2:11: 2:28 help: doc comments must come before what they document,
  maybe a comment was intended with `//`?
  ```
- As the last line of a struct:
  
  ``` rust
  // file.rs:
  struct X {
      a: u8,
      /// incorrect documentation
  }
  ```
  
  ``` bash
  $ rustc file.rs
  file.rs:3:5: 3:27 error: found a documentation comment that doesn't
  document anything
  file.rs:3     /// incorrect documentation
                ^~~~~~~~~~~~~~~~~~~~~~
  file.rs:3:5: 3:27 help: doc comments must come before what they document,
  maybe a comment was intended with `//`?
  ```
- As the last line of a `fn`:
  
  ``` rust
  // file.rs:
  fn main() {
      let x = 1;
      /// incorrect documentation
  }
  ```
  
  ``` bash
  $ rustc file.rs
  file.rs:3:5: 3:27 error: found a documentation comment that doesn't
  document anything
  file.rs:3     /// incorrect documentation
                ^~~~~~~~~~~~~~~~~~~~~~
  file.rs:3:5: 3:27 help: doc comments must come before what they document,
  maybe a comment was intended with `//`?
  ```

Fix #27429, #30322

### CODE REVIEW

File: src/test/parse-fail/doc-before-extern-rbrace.rs [hunk 1]
```diff
@@ -12,5 +12,6 @@
 
 extern {
     /// hi
+    //~^ ERROR expected item after doc comment
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/doc-before-extern-rbrace.rs]: "Maybe"

File: src/test/parse-fail/doc-before-rbrace.rs [hunk 2]
```diff
@@ -12,5 +12,6 @@
 
 fn main() {
     println!("Hi"); /// hi
+    //~^ ERROR found a documentation comment that doesn't document anything
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/doc-before-rbrace.rs]: "Maybe"

File: src/test/parse-fail/doc-before-semi.rs [hunk 3]
```diff
@@ -12,6 +12,7 @@
 
 fn main() {
     /// hi
+    //~^ ERROR found a documentation comment that doesn't document anything
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/doc-before-semi.rs]: "Maybe"

File: src/test/parse-fail/issue-27429-2.rs [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// compile-flags: -Z continue-parse-after-error
+struct X {
+    a: u8,
+    /// document
+    //~^ ERROR found a documentation comment that doesn't document anything
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/issue-27429-2.rs]: "Maybe"

File: src/test/parse-fail/issue-27429-3.rs [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// compile-flags: -Z continue-parse-after-error
+fn main() {
+    /// document
+    //~^ ERROR found a documentation comment that doesn't document anything
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/issue-27429-3.rs]: "Maybe"

File: src/test/parse-fail/issue-27429.rs [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// compile-flags: -Z continue-parse-after-error
+struct X {
+    a: u8 /** document a */,
+    //~^ ERROR found a documentation comment that doesn't document anything
+    //~^^ HELP May be you wanted a comment
```
Comment (GuillaumeGomez) [inline src/test/parse-fail/issue-27429.rs]: "Maybe"

File: src/libsyntax/parse/parser.rs [hunk 7]
```diff
@@ -4017,8 +4032,16 @@ impl<'a> Parser<'a> {
...
                     let unused_attrs = |attrs: &[_], s: &mut Self| {
                         if attrs.len() > 0 {
-                            s.span_err(s.span,
-                                "expected statement after outer attribute");
+                            let unexpected_statement = s.span_to_snippet(s.last_span);
+                            if s.is_doc_comment(unexpected_statement) {
+                                s.span_err_help(s.last_span,
+                                    "found a documentation comment that doesn't document anything",
+                                    "The documentation string must be *before* the element being \
+                                    documented. May be you wanted a comment (starting with `//`)?")
```
Comment (GuillaumeGomez) [inline src/libsyntax/parse/parser.rs]: "Maybe"

**Comment by GuillaumeGomez** [comment]
Thanks for your PR! You need to update some tests which failed (like `src/test/parse-fail/doc-before-extern-rbrace.rs`).

**Comment by estebank** [comment]
@GuillaumeGomez I just pushed a new commit with the requested changes. The tests are running ATM.

**Comment by GuillaumeGomez** [comment]
Please squash your commits. Once done and travis says it's ok, I'll r+ it.

**Comment by estebank** [comment]
I'm away for the weekend, I'll do it on Monday night.

On Sat, 28 May 2016, 08:56 Guillaume Gomez, <notifications@github.com>
wrote:

> Please squash your commits. Once done and travis says it's ok, I'll r+ it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/33922#issuecomment-222315434>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABiDIioynLg5TdxA9BN5-xljewVmwuDWks5qGGXAgaJpZM4Io_dY>
> .
>
-- 

Esteban

**Comment by estebank** [comment]
@GuillaumeGomez I have rebased+push. Travis is running now, but I don't see why it'd fail :)

**Comment by GuillaumeGomez** [comment]
> Travis is running now, but I don't see why it'd fail :)

Better sure than sorry!

Thanks for this PR. :)

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

* #33844

**Comment by estebank** [comment]
>> Travis is running now, but I don't see why it'd fail :)

> Better sure than sorry!

Of course!

> Thanks for this PR. :)

My pleasure.

I see [the build failure in win](http://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1302/steps/test/logs/stdio), and I don't see how it was affected by my change. Do you have any ideas on what caused this?

```bash
---- sync::atomic::AtomicU8::new_0 stdout ----
	error: could not exec the linker `gcc`: The filename or extension is too long. (os error 206)
thread 'sync::atomic::AtomicU8::new_0' panicked at 'Box<Any>', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustc\session/mod.rs:171
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'sync::atomic::AtomicU8::new_0' panicked at 'couldn't compile the test', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:285

---- sync::atomic::AtomicUsize::compare_exchange_0 stdout ----
	thread 'sync::atomic::AtomicUsize::compare_exchange_0' panicked at 'couldn't run the test: The filename or extension is too long. (os error 206)', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:308

---- sync::atomic::AtomicUsize::compare_and_swap_0 stdout ----
	thread 'sync::atomic::AtomicUsize::compare_and_swap_0' panicked at 'couldn't run the test: The filename or extension is too long. (os error 206)', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:308

---- unimplemented!_0 stdout ----
	error: could not exec the linker `gcc`: The filename or extension is too long. (os error 206)
thread 'unimplemented!_0' panicked at 'Box<Any>', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustc\session/mod.rs:171
thread 'unimplemented!_0' panicked at 'couldn't compile the test', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:285


failures:
    sync::atomic::AtomicU8::new_0
    sync::atomic::AtomicUsize::compare_and_swap_0
    sync::atomic::AtomicUsize::compare_exchange_0
    unimplemented!_0

test result: FAILED. 944 passed; 4 failed; 9 ignored; 0 measured
```

**Comment by estebank** [comment]
@GuillaumeGomez @alexcrichton I fixed a typo in the commit description and repushed, which I believe will require a new r+, right? It didn't occur to me before I did it :-/

**Comment by alexcrichton** [comment]
No worries!

Taking a look at this I've got a few comments as well, but I'll leave them inline.

File: src/libsyntax/parse/parser.rs [hunk 8]
```diff
@@ -3520,8 +3534,9 @@ impl<'a> Parser<'a> {
                 self.bump();
                 if self.token != token::CloseDelim(token::Brace) {
                     let token_str = self.this_token_to_string();
-                    return Err(self.fatal(&format!("expected `{}`, found `{}`", "}",
-                                       token_str)))
+                    let err = self.fatal(&format!("expected `{}`, found `{}`", "}",
+                                       token_str));
+                    return Err(err);
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: This seems like no change happened here, right?

File: src/libsyntax/parse/parser.rs [hunk 9]
```diff
@@ -4017,8 +4032,16 @@ impl<'a> Parser<'a> {
...
+                            let unexpected_statement = s.span_to_snippet(s.last_span);
+                            if s.is_doc_comment(unexpected_statement) {
+                                s.span_err_help(s.last_span,
+                                    "found a documentation comment that doesn't document anything",
+                                    "The documentation string must be *before* the element being \
+                                    documented. Maybe you wanted a comment (starting with `//`)?")
+                            } else {
+                                s.span_err(s.span,
+                                    "expected statement after outer attribute");
+                            };
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Stylistically we prefer to avoid semicolons after if statements

File: src/libsyntax/parse/parser.rs [hunk 10]
```diff
@@ -4017,8 +4032,16 @@ impl<'a> Parser<'a> {
...
                     let unused_attrs = |attrs: &[_], s: &mut Self| {
                         if attrs.len() > 0 {
-                            s.span_err(s.span,
-                                "expected statement after outer attribute");
+                            let unexpected_statement = s.span_to_snippet(s.last_span);
+                            if s.is_doc_comment(unexpected_statement) {
+                                s.span_err_help(s.last_span,
+                                    "found a documentation comment that doesn't document anything",
+                                    "The documentation string must be *before* the element being \
+                                    documented. Maybe you wanted a comment (starting with `//`)?")
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Stylistically I believe that compiler messages start with lowercase letters and don't contain punctuation, for example this could perhaps be:

> doc comments must come before what they document, maybe a comment was intended with `//`?

File: src/libsyntax/parse/parser.rs (hunk 9 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Done.

File: src/libsyntax/parse/parser.rs (hunk 10 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Changed.

File: src/libsyntax/parse/parser.rs (hunk 8 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Reverted.

File: src/libsyntax/parse/parser.rs [hunk 11]
```diff
@@ -6161,4 +6189,15 @@ impl<'a> Parser<'a> {
...
     }
+
+    fn span_to_snippet(&self, span: Span) -> String {
+        match self.sess.codemap().span_to_snippet(span) {
+            Ok(s) => s.to_owned(),
+            Err(_) => String::new(),
+        }
+    }
+
+    fn is_doc_comment(&self, s: String) -> bool {
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Ah right sorry, forgot to comment about this, but perhaps this function could take a `Span` directly? The function above may be a bit confusing if called in other contexts because errors are translated to empty strings (which may not be expected). Here the error case could be handled directly by just returning `false` which makes more sense in the context of querying whether a span is a doc comment or not.

File: src/libsyntax/parse/parser.rs [hunk 12]
```diff
@@ -3521,7 +3535,7 @@ impl<'a> Parser<'a> {
                 if self.token != token::CloseDelim(token::Brace) {
                     let token_str = self.this_token_to_string();
                     return Err(self.fatal(&format!("expected `{}`, found `{}`", "}",
-                                       token_str)))
+                                       token_str)));
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: This semicolon addition can probably also be reverted

**Comment by alexcrichton** [comment]
Thanks @estebank! I wonder if we can perhaps get more targeted with the error messages here, though? It seems unfortunate that a blanket `parse_ident` will change errors here rather than just for having doc comments in the most common places. Perhaps just a few specific scenarios could be pattern matched to start off with, and then we could add more over time if necessary?

**Comment by estebank** [comment]
> It seems unfortunate that a blanket parse_ident will change errors here rather than just for having doc comments in the most common places. Perhaps just a few specific scenarios could be pattern matched to start off with, and then we could add more over time if necessary?

I'm not sure I follow, @alexcrichton. Are you proposing pushing the logic slightly earlier in the processing of the AST? Identifying doc comments and looking ahead to check wether they are the last element?

File: src/libsyntax/parse/parser.rs [hunk 13]
```diff
@@ -580,11 +580,19 @@ impl<'a> Parser<'a> {
...
+                    self.span_fatal_help(self.last_span,
+                        "found a documentation comment that doesn't document anything",
+                        "doc comments must come before what they document, maybe a comment was \
+                        intended with `//`?")
+                } else {
+                    let mut err = self.fatal(&format!("expected identifier, found `{}`",
+                                                      self.this_token_to_string()));
+                    if self.token == token::Underscore {
+                        err.note("`_` is a wildcard pattern, not an identifier");
+                    };
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Ah this semicolon can be left off

**Comment by alexcrichton** [comment]
Ah yeah sure, I'll elaborate. I think we've definitely got a few particular scenarios in mind of what we'd like to warn about here (e.g. the tests you've written). For example adding this clause to check `is_doc_comment` makes sense to me as part of `parse_single_struct_field` because it catches mistakes like:

```rust
struct Foo {
    foo: u32 /// dox
}
```

Another location, when an item isn't found but attributes are, also makes sense to me as we can lint against something like:

```rust
mod foo {
    /// dox
}
```

The other case, however, in `parse_ident`, seems like it may be a bit too general. For example we'd emit a custom message in cases like:

```rust
fn /// foo
foo() {}
```

Where the previous error message of "expected identifier, found comment" would perhaps make more sense. 

This is basically replacing the previous error message so we need to be sure that the error is **always** more informative than the previous one, or otherwise we're going to have regressions in some cases. Could you elaborate on which tests require the modification to `parse_ident`?

**Comment by estebank** [comment]
> Could you elaborate on which tests require the modification to parse_ident?

[parse-fail/issue-27429-2.rs](https://github.com/estebank/rust/blob/0e3c0aafdee087089fa656fac9321e44591f3e53/src/test/parse-fail/issue-27429-2.rs) fails if I remove the check in `parse_ident`:

```rust
struct X {
    a: u8,
    /// document
}
```

```bash
---- [parse-fail] parse-fail/issue-27429-2.rs stdout ----
error: /Users/ekuber/personal/rust/src/test/parse-fail/issue-27429-2.rs:14: unexpected "error": '14:5: 14:17: expected identifier, found `/// document`'
error: /Users/ekuber/personal/rust/src/test/parse-fail/issue-27429-2.rs:14: expected error not found: found a documentation comment that doesn't document anything
```

File: src/libsyntax/parse/parser.rs [hunk 14]
```diff
@@ -5187,11 +5207,16 @@ impl<'a> Parser<'a> {
             token::CloseDelim(token::Brace) => {}
             _ => {
                 let span = self.span;
-                let token_str = self.this_token_to_string();
-                return Err(self.span_fatal_help(span,
-                                     &format!("expected `,`, or `}}`, found `{}`",
-                                             token_str),
-                                     "struct fields should be separated by commas"))
+                if self.is_doc_comment(span) {
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Looking through the list of tokens again, we actually have `token::DocComment` which may be more applicable than adding a new method here

File: src/test/parse-fail/doc-before-identifier.rs [hunk 15]
```diff
@@ -0,0 +1,18 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// compile-flags: -Z continue-parse-after-error
+fn /// document
+foo() {}
+//~^^ ERROR expected identifier, found `/// document`
```
Comment (alexcrichton) [inline src/test/parse-fail/doc-before-identifier.rs]: Just to confirm, but this test passes for you? Reading the parser it looks like this may fail...

Comment (estebank) [inline src/test/parse-fail/doc-before-identifier.rs]: I added this test documenting the behaviour I was seeing in master on my machine, to change it later with extra info, but I thought it was explicit enough as it was. If you feel there's value in it, we might want to add a note recommending moving the doc to before the `fn`.

File: src/libsyntax/parse/parser.rs (hunk 14 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Pushing a new commit that removes `is_doc_comment` completely.

**Comment by GuillaumeGomez** [comment]
Good for me. I'll let @alexcrichton handles the r+ if you don't mind. :wink:

File: src/libsyntax/parse/parser.rs [hunk 16]
```diff
@@ -580,12 +580,21 @@ impl<'a> Parser<'a> {
...
             }
             _ => {
-                let mut err = self.fatal(&format!("expected identifier, found `{}`",
-                                                  self.this_token_to_string()));
-                if self.token == token::Underscore {
-                    err.note("`_` is a wildcard pattern, not an identifier");
-                }
-                Err(err)
+                let last_token = self.last_token.clone().map(|t| *t);
+                Err(match last_token {
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Isn't this the same as `self.token` which is being matched on?

File: src/libsyntax/parse/parser.rs [hunk 17]
```diff
@@ -4017,8 +4032,14 @@ impl<'a> Parser<'a> {
                 None => {
                     let unused_attrs = |attrs: &[_], s: &mut Self| {
                         if attrs.len() > 0 {
-                            s.span_err(s.span,
-                                "expected statement after outer attribute");
+                            let last_token = s.last_token.clone().map(|t| *t);
```
Comment (alexcrichton) [inline src/libsyntax/parse/parser.rs]: Is `last_token` needed here? Shouldn't that be what's in `self.token`?

File: src/test/parse-fail/doc-before-identifier.rs (hunk 15 above)
Comment (alexcrichton) [inline src/test/parse-fail/doc-before-identifier.rs]: Can you ensure that other constructs like:

```rust
use foo as /// bar
bar;
```

work as well?

File: src/libsyntax/parse/parser.rs (hunk 16 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: At this point `last_token` is the actual doc comment, but the failure is raised by the current `self.token` not being a valid element at this location, that's why we have to look back to check wether the failure is because the previous element was a doc comment or something else. This is also why we set error to `self.last_span` instead of `self.span`.

For example, with the following input `file.rs`:
```rust
fn foo(a: u8, b: u64) {
    /// document
}
```
The type of `self.last_token` is `Some(DocComment(/// document(61)))` while `self.token` is `CloseDelim(Brace)` and you get the following output with the current code:

```bash
% ./rustc file.rs
file.rs:2:5: 2:17 error: found a documentation comment that doesn't document anything
file.rs:2     /// document
              ^~~~~~~~~~~~
file.rs:2:5: 2:17 help: doc comments must come before what they document, maybe a comment was intended with `//`?
```

File: src/libsyntax/parse/parser.rs (hunk 17 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Same as previous inline comment.

**Comment by mrhota** [comment]
Ping @alexcrichton this seems to be ready for a final check

**Comment by alexcrichton** [comment]
@bors: r+ c8498cc2c27b699436c5f3d3759695926ee0c825

Oops! Sorry this fell under the radar...
