### PR TITLE
Be a bit more relaxed about not yet constrained infer vars in closure upvar analysis

### LINKED ISSUE #197: obfd: could not resolve upvar
https://github.com/The-Noah/obfd/tree/32ba2512d01b2e45b61cba55cd172450dd8aef0a

https://crater-reports.s3.amazonaws.com/pr-133502-9/try%232bef413807188d2b84cd7cc67c6e5bc4a5952d95/gh/The-Noah.obfd/log.txt

```rust
[INFO] [stdout] error: internal compiler error: compiler/rustc_mir_build/src/builder/expr/as_place.rs:260:67: could not resolve upvar: LocalVarId(HirId(DefId(0:17 ~ obfd[57aa]::walk_dir).9)) + [Deref]
[INFO] [stdout]   --> src/main.rs:72:39
[INFO] [stdout]    |
[INFO] [stdout] 72 | async fn walk_dir<'a, C>(path: &Path, cb: &C)
[INFO] [stdout]    |                                       ^^
[INFO] [stdout] 
```

### PR DESCRIPTION
**Pull request by compiler-errors**
See the writeup in `tests/ui/closures/opaque-upvar.rs`.

TL;DR is that this has to do with the fact that the recursive revealing uses, which have not yet been constrained from the defining use by the time that closure upvar inference is performed, remain as infer vars during upvar analysis. We don't really care, though, since anywhere we structurally match on a type in upvar analysis, we already call `structurally_resolve_type` right before `.kind()`, which would emit a true ambiguity error.

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/197

r? lcnr

### CODE REVIEW

File: tests/ui/unboxed-closures/arg-constrained-after-closure-inference.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+#![feature(unboxed_closures)]
+
```
Comment (compiler-errors) [inline tests/ui/unboxed-closures/arg-constrained-after-closure-inference.rs:2]:
```suggestion
//@ check-pass
```

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 2]
```diff
@@ -1185,12 +1185,7 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
             Some(ty) => {
                 let ty = self.cx.resolve_vars_if_possible(ty);
                 self.cx.error_reported_in_ty(ty)?;
-                if ty.is_ty_var() {
-                    debug!("resolve_type_vars_or_bug: infer var from {:?}", ty);
-                    Err(self.cx.report_bug(self.cx.tcx().hir_span(id), "encountered type variable"))
-                } else {
-                    Ok(ty)
-                }
+                Ok(ty)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs:1188]: this function is called `resolve_type_vars_or_bug`.  maybe `expect_and_resolve_type_var`?

Also, we could just emit a `ty::Error` if it fails instead of neednig a `Result`. We can still ICE if we don't expect `None`
