### PR TITLE
Show summary lines on cross-crate re-exports

### LINKED ISSUE #77783: Missing short summaries for reexported items in rustdoc
For example the current [nightly docs](https://doc.rust-lang.org/nightly/std/#modules) show: 
image

The summary lines for the reexported modules is missing. They're also missing from the search index and sidebar.

This is a regression from #77519. cc @jyn514 @GuillaumeGomez

### PR DESCRIPTION
**Pull request by jyn514**
See my write-up in https://github.com/rust-lang/rust/issues/77783#issuecomment-706551743 for what's going on here.

Fixes https://github.com/rust-lang/rust/issues/77783

r? @ollie27

### CODE REVIEW

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -324,17 +324,19 @@ fn merge_attrs(
...
     // when we render them.
     if let Some(inner) = new_attrs {
-        if let Some(new_id) = parent_module {
-            let diag = cx.sess().diagnostic();
-            Attributes::from_ast(diag, old_attrs, Some((inner, new_id)))
-        } else {
-            let mut both = inner.to_vec();
-            both.extend_from_slice(old_attrs);
-            both.clean(cx)
+        if !inner.is_empty() {
```
Comment (ollie27) [inline src/librustdoc/clean/inline.rs:327]: `inner` includes all attributes on the `pub use` statement not just doc comments. This means the `std` docs aren't fixed by this because all `pub use` statements have at least a stability attribute.

**Comment by jyn514** [comment]
I updated this with the approach you suggested in https://github.com/rust-lang/rust/issues/77783#issuecomment-706788854 and added some more tests.

**Comment by ollie27** [comment]
Looks good.

@bors r+ p=1
