### PR TITLE
Fix incorrect span when using byte-escaped rbrace

### LINKED ISSUE #103826: Incorrect span produced when using encoded `}`
The following code produces an incorrect span on nightly:

```rust
fn main() {
    format!("{\x7D");
}
```

Expected:

```
error: 1 positional argument in format string, but no arguments were given
 --> src/main.rs:2:14
  |
2 |     format!("{\x7D");
  |              ^^^^^

error: aborting due to previous error
```

Actual:

```
error: 1 positional argument in format string, but no arguments were given
 --> src/main.rs:2:14
  |
2 |     format!("{\x7D");
  |              ^^

error: aborting due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (95a3a7277 2022-10-31)
binary: rustc
commit-hash: 95a3a7277b44bbd2dd3485703d9a05f64652b60e
commit-date: 2022-10-31
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

This was knowingly introduced as part of #102214. I have already fixed this, and will open a PR shortly.

### PR DESCRIPTION
**Pull request by cassaundra**
Fix #103826, a format args span issue introduced in #102214.

The current solution for tracking skipped characters made it so that certain situations were ambiguous enough that the original span couldn't be worked out later. This PR improves on the original solution by keeping track of groups of skipped characters using a map, and fixes the previous bug. See an example of this ambiguity in the [previous PR's discussion](https://github.com/rust-lang/rust/pull/102214#issuecomment-1258711015).

### CODE REVIEW

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -809,94 +838,97 @@ impl<'a> Parser<'a> {
...
                 }
                 ('\\', Some((_, 'x'))) if !is_raw => {
+                    // consume `\xAB` literal
                     for _ in 0..3 {
-                        // consume `\xAB` literal
-                        if let Some((pos, _)) = s.next() {
-                            skips.push(pos);
-                        } else {
-                            break;
-                        }
```
Comment (cassaundra) [inline compiler/rustc_parse_format/src/lib.rs:852]: Note: a small check removed here. The lexer will raise "numeric character escape is too short" before we ever get to this code if there aren't three characters following the `\`.

File: compiler/rustc_parse_format/src/lib.rs [hunk 2]
```diff
@@ -809,94 +838,97 @@ impl<'a> Parser<'a> {
...
     str_style: Option<usize>,
-) -> (Vec<usize>, bool) {
+) -> (Vec<InnerWidthMapping>, bool) {
     let snippet = match snippet {
         Some(ref s) if s.starts_with('"') || s.starts_with("r\"") || s.starts_with("r#") => s,
         _ => return (vec![], false),
     };
 
-    fn find_skips(snippet: &str, is_raw: bool) -> Vec<usize> {
+    fn find_width_map(snippet: &str, is_raw: bool) -> Vec<InnerWidthMapping> {
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:850]: This will be changed by https://github.com/rust-lang/rust/pull/104193.
cc @TaKO8Ki

File: compiler/rustc_parse_format/src/lib.rs [hunk 3]
```diff
@@ -200,8 +213,8 @@ pub struct Parser<'a> {
     style: Option<usize>,
     /// Start and end byte offset of every successfully parsed argument
     pub arg_places: Vec<InnerSpan>,
-    /// Characters that need to be shifted
-    skips: Vec<usize>,
+    /// Inner span width of characters that need to be shifted
+    width_map: Vec<InnerWidthMapping>,
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:217]: Could you elaborate the comment? Notably: what is the index of the `Vec`?

File: compiler/rustc_parse_format/src/lib.rs [hunk 4]
```diff
@@ -38,6 +38,19 @@ impl InnerSpan {
     }
 }
 
+#[derive(Copy, Clone, PartialEq, Eq)]
+pub struct InnerWidthMapping {
+    pub position: usize,
+    pub before: usize,
+    pub after: usize,
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:45]: Could you comment the individual fields?
What  are they: positions? Starting at which point of reference?

File: compiler/rustc_parse_format/src/lib.rs [hunk 5]
```diff
@@ -224,7 +237,7 @@ impl<'a> Iterator for Parser<'a> {
                 '{' => {
                     let curr_last_brace = self.last_opening_brace;
                     let byte_pos = self.to_span_index(pos);
-                    let lbrace_end = self.to_span_index(pos + 1);
+                    let lbrace_end = InnerOffset(byte_pos.0 + self.to_span_width(pos));
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:240]: Could we wrap all creations of `InnerOffset`?

File: compiler/rustc_parse_format/src/lib.rs [hunk 6]
```diff
@@ -367,23 +383,36 @@ impl<'a> Parser<'a> {
...
-        let mut pos = pos;
-        // This handles the raw string case, the raw argument is the number of #
-        // in r###"..."### (we need to add one because of the `r`).
-        let raw = self.style.map_or(0, |raw| raw + 1);
-        for skip in &self.skips {
-            if pos > *skip {
-                pos += 1;
-            } else if pos == *skip && raw == 0 {
-                pos += 1;
+    fn remap_pos(&self, mut pos: usize) -> usize {
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:386]: Could you add a comment: what are the input and output `usize`s?
Should we introduce some type to differentiate "raw" from "remapped" positions?

File: compiler/rustc_parse_format/src/lib.rs (hunk 2 above)
Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs:850]: Given that there are conflicts from both #103651 and #104193, I'll go ahead and resolve the other issues before I try sort those out.

File: compiler/rustc_parse_format/src/lib.rs (hunk 5 above)
Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs:240]: Hmm, not exactly sure what you mean.

Maybe related: a function that gives you both position and width could clean this up

File: compiler/rustc_parse_format/src/lib.rs (hunk 6 above)
Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs]: Yes, that should be `InnerOffset`, my bad.

File: compiler/rustc_parse_format/src/lib.rs (hunk 4 above)
Comment (cassaundra) [reply compiler/rustc_parse_format/src/lib.rs:50]: Added some comments.

For what it's worth, I think this could also be refactored to instead have a `InnerSpan` and a `usize`, which might make some of the intent more clear.

**Comment by cassaundra** [comment]
Rebased against master.

**Comment by cjgillot** [comment]
Thanks @cassaundra. Sorry for the slow review.
@bors r+
