### PR TITLE
Remove `identity_future` indirection

### LINKED ISSUE #104826: Remove `identity_future` indirection/hack
While working on https://github.com/rust-lang/rust/pull/104321, creating an async generator directly lead to E0720 and E0700 errors.

The *"solution"* was to put the async generator through an identity function:

```rust
pub const fn identity_future<O, Fut: Future<Output = O>>(f: Fut) -> Fut { f }
```

This *"magically"* solves / hides those errors, but should ideally not be necessary.

<details>
<summary>Full Error output</summary>

```
---- [ui] src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit/auxiliary" "--edition=2021"
stdout: none
--- stderr -------------------------------
error: concrete type differs from previous defining opaque type use
   |
LL |         ""
LL |         ""
   |         ^^ expected `impl Debug`, got `&'static str`
note: previous use here
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:39
   |
   |
LL |       async fn baz(&self) -> impl Debug {
LL | |         ""
LL | |     }
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
   | |_____^
   | |_____^

error[E0720]: cannot resolve opaque type
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:28
   |
LL |     async fn baz(&self) -> impl Debug {
   |                            ^^^^^^^^^^ cannot resolve opaque type
   |
   = note: these returned values have a concrete "never" type
   = help: this error will resolve once the item's body returns a concrete type
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0720`.
------------------------------------------
------------------------------------------


---- [ui] src/test/ui/regions/issue-72051-member-region-hang.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/issue-72051-member-region-hang.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL | pub async fn query<'a>(_: &(), _: &(), _: (&(dyn std::any::Any + 'a),) ) {}
   |                    |
   |                    |
   |                    hidden type `impl Future<Output = ()>` captures the lifetime `'a` as defined here
error: aborting due to previous error

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
------------------------------------------


---- [ui] src/test/ui/self/self_lifetime-async.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/self/self_lifetime-async.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/self/self_lifetime-async" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/self/self_lifetime-async/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = &'a ()>` captures lifetime that does not appear in bounds
   |
   |
LL |     async fn bar<'a>(self: &Alias, arg: &'a ()) -> &() { arg }
   |
   |
   = note: hidden type `impl Future<Output = &'a ()>` captures lifetime '_#17r
error: aborting due to previous error

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
```
</details>

### PR DESCRIPTION
**Pull request by Swatinem**
This was previously needed because the indirection used to hide some unexplained lifetime errors, which it turned out were related to the `min_choice` algorithm.

Removing the indirection also solves a couple of cycle errors, large moves and makes async blocks support the `#[track_caller]`annotation.

Fixes https://github.com/rust-lang/rust/issues/104826.

### CODE REVIEW

**Comment by Swatinem** [comment]
Fun fact, now that I changed from `ResumeTy` to `&'static mut Context<'_>` in https://github.com/rust-lang/rust/pull/105250, the `identity_future` indirection seems to have been hiding lifetime errors related to the inferred lifetime of `Context<'_>` which is also considered to be captured. So I had to manually bend that to be a `'static` as well.

Though the three failing tests are still there. Though `src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs` has changed a bit now. The `impl Debug` can now be correctly inferred with recent improvements to rpitit, but it is now complaining about a hidden lifetime for `&'static str`. It can somehow not infer that `""` is indeed a `&'static str`?

**Comment by Swatinem** [comment]
The issue with HirId is an interesting one.
I believe the unused HirId is the one being allocated at the top of `lower_expr_mut` for the outer Expr.
For `async move {}`, I end up with something like `Expr(Expr { id: NodeId(28), kind: Async(Value, NodeId(29), ...`.
`NodeId(28)` is the one it is complaining about it seems. I’m now early-returning in `lower_expr_mut` because `make_async_expr` returns an `Expr` directly instead of an `ExprKind`.

I could just return the `ExprKind::Closure` directly, but then the compiler ICEs because I fail to lower one of the `NodeId`s completely.

I believe the problem is that I have two `NodeId` that I have to deal with, one for the `ast::Expr` itself, and one for the inner `ast::ExprKind::Async`.
Previously, the `identity_future()` call got a `HirId` corresponding to the `ast::Expr`, and the generator got one corresponding to the `ast::ExprKind::Async`.
But now the call does not exist anymore, and one of the Ids gets unused.

I will have to read up on how all these things interact with each other. If someone who knows these things better than me knows a quick solution, feel free to educate me :-)

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 1]
```diff
@@ -182,15 +182,17 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-                    *capture_clause,
-                    hir_id,
-                    *closure_node_id,
-                    None,
-                    e.span,
-                    hir::AsyncGeneratorKind::Block,
-                    |this| this.with_new_scopes(|this| this.lower_block_expr(block)),
-                ),
+                ExprKind::Async(capture_clause, closure_node_id, block) => {
+                    return self.make_async_expr(
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/expr.rs:186]: I think the ICE is because of this -- why don't you make `make_async_expr` return an `ExprKind` and go thru the regular codepaths? The unused HIR id is on line 69

**Comment by Swatinem** [comment]
In the meantime while I still struggle to properly understand HIR lowering…

@nbdd0121 as you added `#[track_caller]`: Is the intention that it works on async blocks or not?
Because now it does, as async blocks *are* (generator) closures, and the `tests/ui/async-await/track-caller/async-block.rs` test does not error anymore:

```
    let _ = #[track_caller] async {
        //~^ ERROR attribute should be applied to a function definition [E0739]
    };
```

**Comment by Swatinem** [comment]
After a short detour messing with HIR and Ids, we are back to the known issues:

```
    [ui] tests/ui/impl-trait/in-trait/default-body-with-rpit.rs
    [ui] tests/ui/regions/issue-72051-member-region-hang.rs
    [ui] tests/ui/self/self_lifetime-async.rs
```

**Comment by nbdd0121** [comment]
> @nbdd0121 as you added `#[track_caller]`: Is the intention that it works on async blocks or not? Because now it does, as async blocks _are_ (generator) closures, and the `tests/ui/async-await/track-caller/async-block.rs` test does not error anymore:
> 
> ```
>     let _ = #[track_caller] async {
>         //~^ ERROR attribute should be applied to a function definition [E0739]
>     };
> ```

I don't think it should work, because semantically `#[track_caller]` doesn't make much sense on an async block.

**Comment by Swatinem** [comment]
> I don't think it should work, because semantically `#[track_caller]` doesn't make much sense on an async block.

Hm, why wouldn’t it? The runtime behavior is consistent with how async fn and async closure works:
```rust
async fn foo_block() {
    let a = #[track_caller] async {
        panic!();
    };
    a.await // <- panic location points to the `await`
}
```

It is just that the feature gate and error message talk about "closure" which might be confusing, but the feature itself makes perfect sense to me 🤔 

Admittedly, it is accidental that this would suddenly work now with this PR, so I can surely find a way to keep the error intact :-)

**Comment by nbdd0121** [comment]
I meant that the name `#[track_caller]` doesn't make much sense here because there's no caller. Maybe should be something like `#[track_poller]`?

**Comment by nbdd0121** [comment]
Also to be clear, I wouldn't oppose making `#[track_caller]` usable on async blocks, as long as it's still properly gated. This discussion could be done when the feature is to be stabilised.

**Comment by Swatinem** [comment]
I rebased again, and now that https://github.com/rust-lang/rust/pull/105300 is fixed, this is down to one last error in `tests/ui/impl-trait/in-trait/default-body-with-rpit.rs`. I can hop on zulip later to discuss next steps, I believe @compiler-errors was open to help with that last problem.

**Comment by compiler-errors** [comment]
@Swatinem I can take a look at that last failure.

**Comment by compiler-errors** [comment]
This is blocked on me figuring out how to fix async-fn-in-trait with nested return-position-impl-trait-in-trait. @Swatinem, if I can't figure this out in 1.5 weeks, then we can probably land this while regressing that and I'll track it in a known-bug instead. Sound good?

**Comment by Swatinem** [comment]
Sounds good. I assume landing this with the regression is acceptable as both are still unstable feature flags? And the regression seems isolated just to these features, so it does not warrent a wider crater run?

**Comment by compiler-errors** [comment]
So #108142 removes the test that's failing.

> Sounds good. I assume landing this with the regression is acceptable as both are still unstable feature flags? And the regression seems isolated just to these features, so it does not warrent a wider crater run?

Actually, this may need a crater run. I can queue one up for you -- shouldn't matter if #108142 lands or not.

@bors try

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by Swatinem** [comment]
There is a bunch of ICEs:

> thread 'rustc' panicked at 'assertion failed: pos.get() <= self.position()', compiler/rustc_metadata/src/rmeta/encoder.rs:435:9

Looks unrelated, but who knows…? There is some other macro-related failures which also look unrelated.

This leaves us with one possibly real regression:

https://crater-reports.s3.amazonaws.com/pr-104833/try%23c604eb46cafa43c9ca3c819e7fb68196c4fc8643/reg/axum-starter-0.5.1/log.txt

```
[INFO] [stdout] error: concrete type differs from previous defining opaque type use
[INFO] [stdout]   --> examples/prepare_expand.rs:65:1
[INFO] [stdout]    |
[INFO] [stdout] 65 | #[prepare(EchoState)]
[INFO] [stdout]    | ^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]    | |
[INFO] [stdout]    | expected `impl PrepareStateEffect`, got `impl PrepareStateEffect`
[INFO] [stdout]    | this expression supplies two conflicting concrete types for the same opaque type
[INFO] [stdout]    |
[INFO] [stdout]    = note: this error originates in the attribute macro `prepare` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0720]: cannot resolve opaque type
[INFO] [stdout]   --> examples/prepare_expand.rs:66:20
[INFO] [stdout]    |
[INFO] [stdout] 66 | fn echo_count() -> impl PrepareStateEffect {
[INFO] [stdout]    |                    ^^^^^^^^^^^^^^^^^^^^^^^ cannot resolve opaque type
```

The code in question is hidden behind some macros, but after macro expansion, does involve some async fn.

So I believe your work to improve handling of this in the compiler will also fix this case.

**Comment by Swatinem** [comment]
I rebased, now that #108203 has landed, though `tests\ui\impl-trait\in-trait\default-body-with-rpit.rs` is still failing.

**Comment by compiler-errors** [comment]
Let me take another look at it again!

**Comment by compiler-errors** [comment]
So there isn't a clear way to fix `default-body-with-rpit.rs`, though it may be fixed by some refactorings that @spastorino is working on. 

You can turn that test into a `// known-bug` and file a bug in the repo if this PR lands. I'll claim that issue once it's filed and keep an eye on fixing it forward.

**Comment by Swatinem** [comment]
I filed https://github.com/rust-lang/rust/issues/108304 and referenced that from the newly blessed testcase.
Also did another rebase as well, and this should be good to go now.

**Comment by lcnr** [comment]
lgtm, but not 100% sure about all the interactions and about hir lowering, so

r? @compiler-errors

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 2]
```diff
@@ -63,6 +63,20 @@ impl<'hir> LoweringContext<'_, 'hir> {
                 ExprKind::ForLoop(pat, head, body, opt_label) => {
                     return self.lower_expr_for(e, pat, head, body, *opt_label);
                 }
+                // Similarly, async blocks do not use `e.id` but rather `closure_node_id`.
+                ExprKind::Async(capture_clause, closure_node_id, block) => {
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/expr.rs:67]: Should we just remove the `closure_node_id` from the AST, and keep the previous logic?

Comment (Swatinem) [reply compiler/rustc_ast_lowering/src/expr.rs:67]: I tried that here: https://github.com/Swatinem/rust/commit/f62aa02c1885b574f61740e0b909d63cc8a08d78
But I was struggling with some HIR errors related to that. I might revisit that idea at some point.

**Review by compiler-errors — COMMENTED** [review]
One nit, but I'll give this another look-over tomorrow orsoon.

File: tests/ui/async-await/track-caller/async-block.stderr [hunk 3]
```diff
@@ -1,12 +1,12 @@
...
-LL |       let _ = #[track_caller] async {
-   |  _____________^^^^^^^^^^^^^^^_-
-LL | |
-LL | |     };
-   | |_____- not a function definition
+LL |     let _ = #[track_caller] async {
+   |             ^^^^^^^^^^^^^^^
+   |
+   = note: see issue #87417 <https://github.com/rust-lang/rust/issues/87417> for more information
+   = help: add `#![feature(closure_track_caller)]` to the crate attributes to enable
```
Comment (compiler-errors) [inline tests/ui/async-await/track-caller/async-block.stderr:8]: This probably should be gated behind a different feature gate, like `async_block_track_caller`.

Comment (Swatinem) [reply tests/ui/async-await/track-caller/async-block.stderr:8]: I was taking a look at this, and I believe it might require some effort to actually split these two apart.

The original `closure_track_caller` feature was added to both closures and generators in https://github.com/rust-lang/rust/pull/87064, and the same feature gate is also being reused for async fn as well.

Internally everything boils down to generator closures. It should be possible to special case this somewhere, but TBH I would rather punt on this and defer the discussion to the broader scope when moving to stabilize the feature, as @nbdd0121 suggested up above: https://github.com/rust-lang/rust/pull/104833#issuecomment-1413809524

**Review by compiler-errors — APPROVED** [review]
