### PR TITLE
fix failure to detect a too-big-type after adding padding

### LINKED ISSUE #117265: Padding can create objects larger than isize::MAX bytes
rustc generally detects when a static type is larger than `isize::MAX` bytes, giving an error that ``values of the type `...` are too big for the current architecture``. However, if a type has fields at most `isize::MAX` bytes long, and additional padding that brings it to `isize::MAX + 1` bytes, then this error will not be generated. To illustrate, all four of these print `0x80000000` (i.e., `isize::MAX + 1`):

```rust
// cargo build --release --target i686-unknown-linux-gnu
// prlimit --stack=unlimited target/i686-unknown-linux-gnu/release/example

use std::{hint, mem::{self, MaybeUninit}, alloc::Layout};

#[repr(C, align(2))]
struct Example(MaybeUninit<[u8; 0x7fffffff]>);

fn main() {
    println!("{:#x}", mem::size_of::<Example>());
    println!("{:#x}", Layout::new::<Example>().size());

    let e = Example(MaybeUninit::uninit());
    hint::black_box(&e);
    println!("{:#x}", mem::size_of_val(&e));
    println!("{:#x}", Layout::for_value(&e).size());
}
```

(The `black_box()` is to ensure that an object of size `0x80000000` is actually created on the stack.)

This is clearly unsound, since it breaks the size invariant of `Layout`, and since third-party crates may depend on types being no larger than `isize::MAX` for soundness. However, it's nontrivial to observe unexpected behavior from this using only safe APIs in the standard library, since placing the overlarge type within any other type, even a `repr(transparent)` wrapper, will result in a compile error as expected, and the standard APIs tend to refer to `&[T; 1]` when creating a slice from a reference.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/117265

### CODE REVIEW

File: compiler/rustc_abi/src/layout.rs [hunk 1]
```diff
@@ -1103,6 +1103,9 @@ fn univariant<
         inverse_memory_index.into_iter().map(|it| it.index() as u32).collect()
     };
     let size = min_size.align_to(align.abi);
+    if size.bytes() >= dl.obj_size_bound() {
```
Comment (oli-obk) [inline compiler/rustc_abi/src/layout.rs:1106]: This feels like an arbitrary place. And now we have two of these checks. Can we instead do this in a single place before producing any `LayoutS`? Or maybe even making `align_to` and other size operations fallible?

Comment (RalfJung) [reply compiler/rustc_abi/src/layout.rs:1106]: I don't understand the structure of this code, so I'm afraid I don't know where else to put it. This is in `univeriant` which sounds reasonably canonical? The other one is somewhere in the enum code I think. :shrug:

If you can tell me another place to put it I am happy yo move it, but me picking one random place after the other until you are happy does not sound like a good strategy. ;)

> Or maybe even making align_to and other size operations fallible?

Currently Size has two kinds of operations -- some check the obj-size-bound and some don't. I don't know why, but maybe some part of the compiler needs to work with larger sizes? No idea.

I can make `align_to` take a `dl` so that it can do the check. But that makes little sense when Size implements `*` and `+` which can't do the check since they don't have a `dl`.

Comment (oli-obk) [reply compiler/rustc_abi/src/layout.rs:1106]: > Currently Size has two kinds of operations -- some check the obj-size-bound and some don't. I don't know why, but maybe some part of the compiler needs to work with larger sizes? No idea.

most of these are likely just ad-hoc



> If you can tell me another place to put it I am happy yo move it, but me picking one random place after the other until you are happy does not sound like a good strategy. ;)

😆 I'm not sure where to put it either, needs experimentation. So... just leave a `FIXME(oli-obk): deduplicate and harden these checks` on both checks 

r=me with fixme comment
