### PR TITLE
fix: correct the arg for 'suggest to use associated function syntax' diagnostic

### LINKED ISSUE #118469: suggest to use associated function syntax diagnostic take receiver as first arg mistakely
### Code

```Rust
struct A {}

impl A {
    fn hello(a: i32) {}
}

fn main() {
    let a = A {};
    a.hello(1);
}
```

### Current output

```Shell
error[E0599]: no method named `hello` found for struct `A` in the current scope
  --> src/main.rs:46:7
   |
38 | struct A {}
   | -------- method `hello` not found for this struct
...
46 |     a.hello(1);
   |     --^^^^^---
   |     | |
   |     | this is an associated function, not a method
   |     help: use associated function syntax instead: `A::hello(a, 1)`
   |
   = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in an impl for the type `A`
  --> src/main.rs:41:5
   |
41 |     fn hello(a: i32) {}
   |     ^^^^^^^^^^^^^^^^
```

### Desired output

```Shell
receiver shouldn't be treated as the first arg of the assoc function when the first arg of the assoc function isn't the same as the current impl type

46 |     a.hello(1);
   |     --^^^^^---
   |     | |
   |     | this is an associated function, not a method
   |     help: use associated function syntax instead: `A::hello(1)`
```

### Rationale and extra context

rustc --version
rustc 1.75.0-nightly (9d83ac217 2023-10-31)

### Other cases

```Rust
no
```

### Anything else?

no

### PR DESCRIPTION
**Pull request by Young-Flash**
close https://github.com/rust-lang/rust/issues/118469

### CODE REVIEW

**Comment by Young-Flash** [comment]
seems [b-naber](https://github.com/b-naber) has not time to review this, let's try @rustbot r?

**Comment by Young-Flash** [comment]
could @saethlin help review this?

**Comment by saethlin** [comment]
Did you pick me because you saw my name on the issue? I really don't know much of anything about this part of the compiler, so I wouldn't have picked me.

**Comment by Young-Flash** [comment]
> Did you pick me because you saw my name on the issue?

Oh yeah.

>  I really don't know much of anything about this part of the compiler, so I wouldn't have picked me.

Sorry for the interruption.

**Comment by saethlin** [comment]
No need to apologize. A lot of the compiler team tends to go on vacation around this time, and some of the contributors group (which I'm in) does get review requests.

r? compiler

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -1591,10 +1591,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             {
                 let sig = self.tcx.fn_sig(assoc.def_id).instantiate_identity();
                 sig.inputs().skip_binder().get(0).and_then(|first| {
-                    if first.peel_refs() == rcvr_ty.peel_refs() {
-                        None
-                    } else {
+                    let impl_ty = self.tcx.type_of(*impl_did).instantiate_identity();
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:1594]: I'm a bit suspicious of how this will behave with an impl that has generic args, but it's just diagnostics.

Comment (Young-Flash) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:1594]: it should works, will add a test case in next PR
