### PR TITLE
E0132 update

### LINKED ISSUE #35258: E0132 needs to be updated to new format
From: src/test/compile-fail/E0132.rs

Error E0132 needs a span_label, updating it from:

```
error[E0132]: start function is not allowed to have type parameters
  --> src/test/compile-fail/E0132.rs:14:1
   |
14 | fn f<T>() {} //~ ERROR E0132
   | ^^^^^^^^^^^^
```

To:

```
error[E0132]: start function is not allowed to have type parameters
  --> src/test/compile-fail/E0132.rs:14:1
   |
14 | fn f<T>() {} //~ ERROR E0132
   | ^^^^^^^^^^^^ start function cannot have type parameters
```

Bonus: Underline just the type parameters

```
error[E0132]: start function is not allowed to have type parameters
  --> src/test/compile-fail/E0132.rs:14:1
   |
14 | fn f<T>() {} //~ ERROR E0132
   |     ^^^ start function cannot have type parameters
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #35258.

r? @jonathandturner

### CODE REVIEW

File: src/librustc/hir/mod.rs [hunk 1]
```diff
@@ -326,6 +326,38 @@ impl Generics {
...
+                if let Some(ref mut span) = span {
+                    span.lo = if span.lo < ty_param.span.lo { span.lo } else { ty_param.span.lo };
+                    span.hi = if span.hi > ty_param.span.hi { span.hi } else { ty_param.span.hi };
+                } else {
+                    span = Some(ty_param.span.clone());
+                }
+            }
+            if let Some(ref mut span) = span {
+                span.lo = span.lo - BytePos(1);
+                span.hi = span.hi + BytePos(1);
```
Comment (Limeth) [inline src/librustc/hir/mod.rs]: Doesn't account for
```rust
fn f<  T  >() {}
      ^^^
```
I decided to omit this manual span expansion in my implementation of this method. #35257
