### PR TITLE
Lower constant patterns with ascribed types.

### LINKED ISSUE #57960: Associated-const ranges in patterns are miscompiled in beta
This code demonstrates the problem ([playpen](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=01a4d2541fd60a365b993cce0adea2fc)):
```rust
#![allow(dead_code)]

trait Range {
    const FIRST: u8;
    const LAST: u8;
}

struct OneDigit;
impl Range for OneDigit {
    const FIRST: u8 = 0;
    const LAST: u8 = 9;
}

struct TwoDigits;
impl Range for TwoDigits {
    const FIRST: u8 = 10;
    const LAST: u8 = 99;
}

struct ThreeDigits;
impl Range for ThreeDigits {
    const FIRST: u8 = 100;
    const LAST: u8 = 255;
}

fn digits(x: u8) -> u32 {
    match x {
        OneDigit::FIRST...OneDigit::LAST => 1,
        TwoDigits::FIRST...TwoDigits::LAST => 2,
        ThreeDigits::FIRST...ThreeDigits::LAST => 3,
        _ => unreachable!(),
    }
}

fn main() {
    println!("{}", digits(100));
}
```

With stable-1.32.0 it prints `3`. With beta-1.33.0 it wrongly prints `1`.

Beta also produces these wrong warnings:
```
warning: unreachable pattern
  --> src/main.rs:29:9
   |
29 |         TwoDigits::FIRST...TwoDigits::LAST => 2,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_patterns)] on by default

warning: unreachable pattern
  --> src/main.rs:30:9
   |
30 |         ThreeDigits::FIRST...ThreeDigits::LAST => 3,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It seems that Rustc decides, that the first arm covers the whole range of a
`u8` and optimizes out the other arms before they even reach MIR.

The code is very similar to this [testcase](https://github.com/rust-lang/rust/blob/d8a0dd7ae88023bd09fa4b86c9ca1f6ed8095b43/src/test/run-pass/associated-consts/associated-const-range-match-patterns.rs).
But the testcase does not test that the other arms can be reached.

I was able to bisect the regression to #55937.

(This issue seems similar to #57894, but the reduced testcase there does not
use any associated consts)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #57960.

This PR fixes a bug introduced by #55937 which started checking user
type annotations for associated type patterns. Where lowering a
associated constant expression would previously return a
`PatternKind::Constant`, it now returns a `PatternKind::AscribeUserType`
with a `PatternKind::Constant` inside, this PR unwraps that to
access the constant pattern inside and behaves as before.

r? @pnkfelix

### CODE REVIEW

File: src/librustc_mir/hair/pattern/mod.rs [hunk 1]
```diff
@@ -403,9 +414,11 @@ impl<'a, 'tcx> PatternContext<'a, 'tcx> {
             PatKind::Lit(ref value) => self.lower_lit(value),
 
             PatKind::Range(ref lo_expr, ref hi_expr, end) => {
-                match (self.lower_lit(lo_expr), self.lower_lit(hi_expr)) {
-                    (PatternKind::Constant { value: lo },
-                     PatternKind::Constant { value: hi }) => {
+                match (
```
Comment (arielb1) [inline src/librustc_mir/hair/pattern/mod.rs]: Do we want to maintain the user type annotations in this case?

Comment (arielb1) [reply src/librustc_mir/hair/pattern/mod.rs]: Or is there some reason why user type annotations are always irrelevant in ranges? In that case, could you put it in a comment?

Comment (arielb1) [reply src/librustc_mir/hair/pattern/mod.rs]: So the answer is "only char and numeric types are allowed in range patterns", which means we don't care about user types. You could still have this in a comment.

**Comment by arielb1** [comment]
r=me with comment in place

File: src/librustc_mir/hair/pattern/mod.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir/hair/pattern/mod.rs]: We still need them to check something like `Type<'a>::X` when we have `impl Type<'static> { const X: i32 = 0; ... }`

Comment (arielb1) [inline src/librustc_mir/hair/pattern/mod.rs]: To avoid miscompilations down the line, could you also replace the `_ => PatternKind::Wild` line with this?

```Rust
                    ref pats => {
                        self.tcx.delay_span_bug(
                            pat.span, format!("found bad range pattern `{:?}` \
                                               outside of error recovery", pats));

                        PatternKind::Wild
                    }
```

Comment (arielb1) [reply src/librustc_mir/hair/pattern/mod.rs]: So in that case, you need to move the `AscribeUserType` out.

Comment (davidtwco) [reply src/librustc_mir/hair/pattern/mod.rs]: Changed this.

Comment (davidtwco) [reply src/librustc_mir/hair/pattern/mod.rs]: Added a comment.

**Comment by arielb1** [comment]
So @matthewjasper had complained that the `AscribeUserType` was getting dropped. Could you add it back, along with a mir-opt test?

r=me with that

**Comment by arielb1** [comment]
It appears that fixing the `AscribeUserType` problem is more complicated than it appears at first glance - I have split it into #58299 - but we need to fix this PR for beta.

@bors r+ p=1

**Comment by arielb1** [comment]
beta-nominating because this fixes a regression in beta.

**Comment by arielb1** [comment]
> No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

@bors retry

**Comment by arielb1** [comment]
cc @kennytm looks spurious

**Comment by pnkfelix** [comment]
triage, beta-accepted.
