### PR TITLE
Detect multiple crate versions on method not found

### LINKED ISSUE #32611: Misleading message: "error: the trait `Foo` is not implemented for the type `Bar`"
Consider three crates High, Mid and Low, where:
- Mid depends on Low;
- High depends on both Mid and Low.

This is a quite common case.

Now, it sometimes happens that the dependency of Mid is bumped to a more recent version of Low. If, however, the developer fails to bump the dependency of High to a more recent version of Low, surprising error messages arise.

In particular,

```
"error: the trait `Foo` is not implemented for the type `Bar`"
```

may arise, without any change to the code of either `Foo` or `Bar`.

It would be great if the compiler could detect the error and somehow print something along the liens of

```
"error: using conflicting versions of the trait `Foo` for type `Bar`. You are probably using two distinct versions of the same library."
```

### LINKED ISSUE #51458: E0599 message could be improved for crate version mismatches.
I was working on a project where a dependency used a older version of `embedded-hal` and my project used a newer version. Because of this when I imported the trait `OutputPin` and tried to use it I got E0599 with the following message: 

```
 help: items from traits can only be used if the trait is in scope
 help: the following trait is implemented but not in scope, perhaps add a `use` for it
```
However, I had imported the trait the issue was down to the versions not matching up. I also heard some other people had encountered the same confusion with some futures code so it seems this could definitely stand to be made more helpful to users.

EDIT: Looks like after googling this is a known issue and there's been work to improve it i.e. #28300 so feel free to close this if there's already an issue for it I missed!

### LINKED ISSUE #81659: Confusing diagnostics when pulling the same crate from different sources
[Source thread in URLO](https://users.rust-lang.org/t/no-method-x-found-for-struct-and-compiler-bug/55026)

I was working with a library crate that I forked to modify locally in my project. In the `Cargo.toml` of the binary I referenced my local copy of the modified library, but the `Cargo.toml` of the modified library still referenced the `crates.io` version.

`cargo tree` output looks like this (truncated):

```
├── display-interface v0.4.0 (/Users/andresovela/dev/rust/embedded/my-app/crates/display-interface)
├── display-interface-parallel-gpio v0.4.1 (/Users/andresovela/dev/rust/embedded/my-app/crates/display-interface/parallel-gpio)
│   ├── byte-slice-cast v0.3.5
│   ├── display-interface v0.4.0
├── ili9486 v0.1.0 (/Users/andresovela/dev/rust/embedded/my-app/crates/ili9486-rs)
│   ├── display-interface v0.4.0 (/Users/andresovela/dev/rust/embedded/my-app/crates/display-interface)
│   ├── display-interface-parallel-gpio v0.4.1 (/Users/andresovela/dev/rust/embedded/my-app/crates/display-interface/parallel-gpio) (*)
```

The problem being that the `Cargo.toml` in `display-interface-parallel-gpio` was referencing the `crates.io` version of `display-interface` instead of my local copy.

This resulted in the compiler giving me the following error and warning:

```
error[E0599]: no method named `send_commands` found for struct `PGPIO8BitInterface<nrf52832_hal::gpio::Pin<Output<PushPull>>, P0_28<Output<PushPull>>, P0_04<Output<PushPull>>>` in the current scope
  --> src/main.rs:44:23
   |
44 |     ili9486_interface.send_commands(display_interface::DataFormat::U8(&data));
   |                       ^^^^^^^^^^^^^ method not found in `PGPIO8BitInterface<nrf52832_hal::gpio::Pin<Output<PushPull>>, P0_28<Output<PushPull>>, P0_04<Output<PushPull>>>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
4  | use display_interface::WriteOnlyDataCommand;
   |

warning: unused import: `display_interface::WriteOnlyDataCommand`
 --> src/main.rs:4:5
  |
4 | use display_interface::WriteOnlyDataCommand;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It would have been much much better if the compiler noticed that there is conflict in crate versions somehow. Maybe if it detects that the trait name exists but it comes from a different crate or something? Unfortunately I'm not well versed in the compiler internals, but I think this case could be definitely improved.

### LINKED ISSUE #109161: Using two version of the same crate gives confusing message
### Code

```Rust
// main.rs
use prio::codec::Decode;
 
use janus_messages::HpkeConfig;
 
fn main() {
    let foo = [0u8; 100];
    HpkeConfig::get_decoded(&foo);
}
 
// Cargo.toml
[package]
name = "dap-test"
version = "0.1.0"
edition = "2021"
 
[dependencies]
janus_messages = "0.3.1" # note this depends on prio 0.10!
prio = "0.9.1"
```

### Current output

```Shell
error[E0599]: no function or associated item named `get_decoded` found for struct `HpkeConfig` in the current scope
 --> src/main.rs:7:17
  |
7 |     HpkeConfig::get_decoded(&foo);
  |                 ^^^^^^^^^^^ function or associated item not found in `HpkeConfig`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
  |
1 | use prio::codec::Decode;
  |

warning: unused import: `prio::codec::Decode`
 --> src/main.rs:1:5
  |
1 | use prio::codec::Decode;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.
```

### Desired output

```Shell
error[E0599]: no function or associated item named `get_decoded` found for struct `HpkeConfig` in the current scope
 --> src/main.rs:7:17
  |
7 |     HpkeConfig::get_decoded(&foo);
  |                 ^^^^^^^^^^^ function or associated item not found in `HpkeConfig`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
  |
1 | use prio(0.10.0)::codec::Decode;
  |

warning: unused import: `prio::codec::Decode`
 --> src/main.rs:1:5
  |
1 | use prio(0.9.1)::codec::Decode;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.

(#IIUC: Include the version number that causes those two Decode objects to be different.)
```

### Rationale and extra context

Afaiu this is caused by a `impl TraitFoo for StructBar` in `CrateBar` which depends on `CrateFoo` (which has the trait) and then trying to use a function on `TraitFoo` on a `StructBar` from the main project which depends on a different version of `CrateFoo`. In that case it would help to add the version number.

### Other cases

_No response_

### Anything else?

_No response_

### LINKED ISSUE #110926: If two crates have the same name, distinguish them in rustc's output?
### Code

I'm writing code that uses the py-spy and remoteprocess crates. py-spy also uses remoteprocess internally. I tried to switch to using a different version of remoteprocess with some patches, but I foolishly did this by changing my top-level crate to *depend* on `remoteprocess = { git = ... }`, when what I really wanted was to use a `[patch.crates-io]` stanza. Anyway, the end result is that I had two different `remoteprocess` crates in my dependency tree without knowing it, and rustc gave me some spectacularly confusing errors. In particular, in a single message output, it suggested to try adding the line `use remoteprocess::SomeTrait`, and also suggested removing the line `use remoteprocess::SomeTrait` because it was unused.

### Current output

```Shell
error[E0599]: no method named `copy` found for struct `Process` in the current scope
   --> src/shmem.rs:273:22
    |
273 |                     .copy(current.metadata.name_ptr, current.metadata.name_len)?;
    |                      ^^^^ method not found in `Process`
    |
   ::: /Users/njs/.cargo/registry/src/github.com-1ecc6299db9ec823/remoteprocess-0.4.11/src/lib.rs:170:8
    |
170 |     fn copy(&self, addr: usize, length: usize) -> Result<Vec<u8>, Error> {
    |        ---- the method is available for `remoteprocess::osx::Process` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use remoteprocess::ProcessMemory;
    |

warning: unused import: `remoteprocess::ProcessMemory`
 --> src/shmem.rs:5:5
  |
5 | use remoteprocess::ProcessMemory;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

### Desired output

It'd be nice if rustc detected this case and printed something hinting at what's going on?

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### LINKED ISSUE #128569: Trait method cannot be imported from package when pulling dependency from git repository
I'm writing code for a programming language that uses two libraries: one for a (very simple) parser, and another for a lower level byte code, which also uses the same parser library.

The parser library (TSPL) defines the `Parser` trait, with the byte code library (HVM) defining a `CoreParser` that implements that trait through a macro from TSPL.

Then, a third library does something like this, where `index` is a method from that trait:
```rust
use TSPL::Parser;
use hvm::ast::CoreParser;

pub fn func(parser: &mut CoreParser) {
    *parser.index() = 1;
}
```

This works as expected if the dependencies in `Cargo.toml` are defined like this:
```toml
[dependencies]
TSPL = "0.0.12"
hvm = "2.0.21"
```

If we change `TSPL` to use the version from the latest git commit like this:
```toml
[dependencies]
TSPL = { git = "https://github.com/HigherOrderCO/TSPL.git" }
hvm = "2.0.21"
```

Then the code does not compile anymore, even though the version in the main branch in git has the exact same code as the published version `0.0.12`. We get an error and a warning:
```
warning: unused import: `TSPL::Parser`
 --> src/lib.rs:1:5
  |
1 | use TSPL::Parser;
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0599]: no method named `index` found for mutable reference `&mut CoreParser<'_>` in the current scope
 --> src/lib.rs:5:13
  |
5 |     *parser.index() = 1;
  |             ^^^^^ private field, not a method
  |
  = help: items from traits can only be used if the trait is in scope
help: trait `Parser` which provides `index` is implemented but not in scope; perhaps you want to import it
  |
1 + use TSPL::Parser;
```

Notice that the compiler error tells us the function `index` has been found from the `TSPL` package, and we do as the error message tells us (`use TSPL::Parser`), but the compiler does not recognize the trait is being used even so.

While writing this issue, I figured out the problem: `hvm` uses the version from crates-io and our library doesn't and, even though they have the exact same code, the two versions of `TSPL` clash and the compiler does not compile. If we do something like this it works as expected:
```toml
[dependencies]
TSPL = "0.0.12"
hvm = "2.0.21"

[patch.crates-io]
TSPL = { git = "https://github.com/HigherOrderCO/TSPL.git" }
```

I still want to open this issue because I believe the error message could be more descriptive: in other cases where dependencies have clashing versions of other dependencies, usually Rust specifies it as such. The current error message is not very descriptive - the solution it gives to the problem does not work at all and may push users into the wrong direction.

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: aarch64-apple-darwin
release: 1.80.0
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>

```
error[E0599]: no method named `index` found for mutable reference `&mut CoreParser<'_>` in the current scope
 --> src/lib.rs:5:13
  |
5 |     *parser.index() = 1;
  |             ^^^^^ private field, not a method
  |
  = help: items from traits can only be used if the trait is in scope
help: trait `Parser` which provides `index` is implemented but not in scope; perhaps you want to import it
  |
1 + use TSPL::Parser;
  |

warning: unused import: `TSPL::Parser`
 --> src/lib.rs:1:5
  |
1 | use TSPL::Parser;
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by estebank**
When a type comes indirectly from one crate version but the imported trait comes from a separate crate version, the called method won't be found. We now show additional context:

```
error[E0599]: no method named `foo` found for struct `dep_2_reexport::Type` in the current scope
 --> multiple-dep-versions.rs:8:10
  |
8 |     Type.foo();
  |          ^^^ method not found in `Type`
  |
note: there are multiple different versions of crate `dependency` in the dependency graph
 --> multiple-dep-versions.rs:4:32
  |
4 | use dependency::{do_something, Trait};
  |                                ^^^^^ `dependency` imported here doesn't correspond to the right crate version
  |
 ::: ~/rust/build/x86_64-unknown-linux-gnu/test/run-make/crate-loading/rmake_out/multiple-dep-versions-1.rs:4:1
  |
4 | pub trait Trait {
  | --------------- this is the trait that was imported
  |
 ::: ~/rust/build/x86_64-unknown-linux-gnu/test/run-make/crate-loading/rmake_out/multiple-dep-versions-2.rs:4:1
  |
4 | pub trait Trait {
  | --------------- this is the trait that is needed
5 |     fn foo(&self);
  |        --- the method is available for `dep_2_reexport::Type` here
```

Fix #128569, fix #110926, fix #109161, fix #81659, fix #51458, fix #32611. Follow up to #124944.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -4041,6 +4050,58 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        owner: hir::OwnerId,
+        rcvr_ty: Ty<'_>,
+    ) -> bool {
+        let pick_name = self.tcx.crate_name(item.def_id.krate);
+        if let Some(map) = self.tcx.in_scope_traits_map(owner) {
+            for trait_candidate in map.to_sorted_stable_ord().into_iter().flat_map(|v| v.1.iter()) {
+                let name = self.tcx.crate_name(trait_candidate.def_id.krate);
+                if trait_candidate.def_id.krate != item.def_id.krate && name == pick_name {
+                    let msg = format!(
+                        "you have multiple different versions of crate `{name}` in your \
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:4066]: I feel like saying "you" here makes this read weirdly

```suggestion
                        "there have multiple different versions of crate `{name}` in the \
```

Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:4066]: There are a couple of other strings in this module that use `you`, we should clean those up too, separately.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 2]
```diff
@@ -4041,6 +4050,58 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    fn detect_and_explain_multiple_crate_versions(
+        &self,
+        err: &mut Diag<'_>,
+        item: &ty::AssocItem,
+        owner: hir::OwnerId,
+        rcvr_ty: Ty<'_>,
+    ) -> bool {
+        let pick_name = self.tcx.crate_name(item.def_id.krate);
+        if let Some(map) = self.tcx.in_scope_traits_map(owner) {
+            for trait_candidate in map.to_sorted_stable_ord().into_iter().flat_map(|v| v.1.iter()) {
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:4062]: This is the thing I'm slightly uneasy about: for *every* error of a method not found that triggers the prior conditions, we'll be doing a linear scan of all traits in scope. Don't have a good sense of whether that will be a significant slow-down for compiles with errors (not a good way of testing that difference).

**Comment by estebank** [comment]
I think after landing this PR the only error that still needs to check for multiple crate versions is E0277. E0308 already has a check (even though it isn't great), and this addresses E0599 for every case I could get my hands on.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 3]
```diff
@@ -4041,6 +4075,61 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
     }
 
+    fn detect_and_explain_multiple_crate_versions(
+        &self,
+        err: &mut Diag<'_>,
+        item_def_id: DefId,
+        item_span: Span,
+        owner: hir::OwnerId,
+        rcvr_ty: Ty<'_>,
+    ) -> bool {
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:4085]: The bool returned here is very unconventional. Normally, we return `false` if we did not emit something and vice versa. this is a `detect_*` method, so I'd expect the boolean to be flipped. I'd recommend renaming the `suggest` var to something like `trait_in_other_version_found`, and making the return value for this correspond to the convention.

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 2 above)
Comment (fee1-dead) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:4090]: Please take some time to fuzz this. Would it be possible to trigger this in some normal session by removing some imports or upgrading a crate to a newer version (where the trait method is removed in the newer version and the older version is still imported by some transitive dependencies)?

It's very possible that some large project trying to refactor something will hit this if this is a significant slowdown.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 4]
```diff
@@ -3676,7 +3686,31 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            && let Some(def_id) = path.res.opt_def_id()
+            && let Some(assoc) = self
+                .tcx
+                .associated_items(valid_out_of_scope_traits[0])
+                .filter_by_name_unhygienic(item_name.name)
+                .next()
+        {
+            // See if the `Type::function(val)` where `function` wasn't found corresponds to a
+            // `Trait` that is imported directly, but `Type` came from a different version of the
+            // same crate.
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:3703]: Please also add a test for this.

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:4090]: I think putting this behind a query that allocates a `HashMap<crate name, Vec<trait DefId>>` and returns it would reduce the amortized cost significantly and eliminate the risk of causing trouble.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: Ok, I changed it to use `in_scope_traits` instead of `in_scope_traits_map`, which will be much cheaper (at the cost of only looking at traits in the current scope, which is fine).

Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: @fee1-dead given the current approach (where we're looking at in-scope traits for a *specific* scope), which is something we're already doing for every method resolution, I feel more comfortable with it. I'm also not quite sure how to synthesize a big enough corpus of "wrong crate" to properly stress this.

**Review by fee1-dead — APPROVED** [review]
Thanks!
