### PR TITLE
fs: Don't copy d_name from struct dirent

### LINKED ISSUE #93384: compiletest crashes on CI with: expected success, got: signal: 11 (core dumped)
runner: x86_64-gnu-llvm-12, ubuntu-20.04-xl
Occured in multiple pr across CI:
#93361: https://github.com/rust-lang/rust/runs/4969749566?check_suite_focus=true
#93381: https://github.com/rust-lang/rust/runs/4969258442?check_suite_focus=true
#93375: https://github.com/rust-lang/rust/runs/4967313356?check_suite_focus=true
#93239: https://github.com/rust-lang/rust/runs/4963643970?check_suite_focus=true
and others

### PR DESCRIPTION
**Pull request by tavianator**
The dirent returned from readdir() is only guaranteed to be valid for
d_reclen bytes on common platforms.  Since we copy the name separately
anyway, we can copy everything except d_name into DirEntry::entry.

Fixes #93384.

### CODE REVIEW

**Comment by tavianator** [comment]
I added a test, and was able to reproduce the failure with

```shell
$ RUSTFLAGS_BOOTSTRAP="-Z sanitizer=address" ./x.py test --stage 0 library/std --test-args read_large_dir
```

and confirmed that this PR fixes it.

File: library/std/src/sys/unix/fs.rs [hunk 1]
```diff
@@ -489,8 +489,18 @@ impl Iterator for ReadDir {
...
 
+                // Only d_reclen bytes of *entry_ptr are valid, so we can't just copy the
+                // whole thing (#93384).
+                let reclen = (*entry_ptr).d_reclen as usize;
+                let mut entry: dirent64 = mem::zeroed();
+                ptr::copy_nonoverlapping(
+                    entry_ptr as *const u8,
+                    &mut entry as *mut _ as *mut u8,
+                    reclen,
+                );
```
Comment (tmiasko) [inline library/std/src/sys/unix/fs.rs:500]: I don't think we can copy `d_reclen` bytes either, since it might exceed the size of dirent structure:

> Note that while the call `fpathconf(fd, _PC_NAME_MAX)` returns the value 255 for most filesystems, on some filesystems  (e.g., CIFS, Windows SMB servers), the null-terminated filename that is (correctly) returned in d_name can actually exceed this size. In such cases, the d_reclen field will contain a value that exceeds the size of the glibc dirent structure shown above.

Comment (cuviper) [reply library/std/src/sys/unix/fs.rs:500]: Good point -- we would be better of destructuring the individual fields we need. This code is already allocating a separate copy of the full name.

Comment (tavianator) [reply library/std/src/sys/unix/fs.rs:500]: @tmiasko Oh right yeah, that was the whole reason for my initial patch.

@cuviper I'm happy to do that but it's a larger change, thought you might like this one first to unbreak CI.

Comment (cuviper) [reply library/std/src/sys/unix/fs.rs:500]: Ok, then maybe use `ptr::addr_of((*entry_ptr).d_name)` to figure out the offset, and copy the bytes up to that point. Or just copy those individual fields manually into the zeroed `entry`.

Comment (tavianator) [reply library/std/src/sys/unix/fs.rs]: Done!

File: library/std/src/sys/unix/fs.rs [hunk 2]
```diff
@@ -489,10 +489,18 @@ impl Iterator for ReadDir {
                     };
                 }
 
+                // Only d_reclen bytes of *entry_ptr are valid, so we can't just copy the
+                // whole thing (#93384).  Instead, copy everything except the name.
+                let entry_bytes = entry_ptr as *const u8;
+                let entry_name = (*entry_ptr).d_name.as_ptr() as *const u8;
```
Comment (cuviper) [inline library/std/src/sys/unix/fs.rs:495]: The reason I suggested `ptr::addr_of!` is because things like `as_ptr()` require forming a reference `&self`, but our issue here is that `d_name` may not be fully dereferenceable. Keeping everything as pointers should be safer.

Comment (tavianator) [reply library/std/src/sys/unix/fs.rs:495]: Ah fair, I did it this way because the code below was already doing the same thing.  I'll change it.

**Comment by cuviper** [comment]
LGTM -- bumping priority since this helps everyone's CI.

@bors r+ p=1

**Comment by ehuss** [comment]
@bors retry

The build was canceled after 10 minutes, though it isn't clear why.

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (tavianator) [reply library/std/src/sys/unix/fs.rs]: Turns out `addr_of!()` isn't even enough: https://github.com/rust-lang/miri/pull/1981#issuecomment-1048278492

Comment (cuviper) [reply library/std/src/sys/unix/fs.rs]: Ugh, then what? Get the offset from a fully-sized local dummy, then ptr-add on the real thing?

Comment (tavianator) [reply library/std/src/sys/unix/fs.rs]: Yeah.  That's apparently what all the `offset_of!()` crates do.  Does libstd already have something like that or should I just open code it?

Comment (cuviper) [reply library/std/src/sys/unix/fs.rs]: My impression was that such use was the very *purpose* of `addr_of!` / `&raw`, and it seems I wasn't the only one from the discussion on #64490 and #73394. But that was left to the future in [RFC 2582](https://rust-lang.github.io/rfcs/2582-raw-reference-mir-operator.html#other).

It seems really unfortunate here since the pointer at hand is not entirely dangling, just _incomplete_ at the end, beyond the pointer we want to compute. A `MaybeUninit` local feels like such a waste, but should be optimized away. Maybe that can even be done in a true `const` these days?

I'm not aware of any existing `offset_of!`, so open-coding it seems fine, with a comment that it _could_ use `offset_of!` so we can find and update it later. :)

Comment (RalfJung) [reply library/std/src/sys/unix/fs.rs]: `addr_of!` is a weaker from of `&`, but it does nothing about `*`. The code here is UB due to the requirement of `*` to only be used on pointers that point to actual memory (with the required size and alignment given by its type).

It would love to just entirely remove that restriction, but then we would have to change our LLVM codegen to use `getelementptr` instead of `getelementptr inbounds` in some situations.

Comment (RalfJung) [reply library/std/src/sys/unix/fs.rs]: > Maybe that can even be done in a true const these days?

With some unstable features, it can -- see the https://github.com/Gilnaa/memoffset crate

Comment (thomcc) [reply library/std/src/sys/unix/fs.rs]: > I would love to just entirely remove that restriction, but then we would have to change our LLVM codegen to use getelementptr instead of getelementptr inbounds in some situations.

This is probably worth doing, honestly. I can't imagine the use of `gepi` over `gep` wins us almost anything on modern hardware (IIUC it mostly just allows folding the address arithmetic into a subsequent load), and even if it does, we still would be able to use it in all cases except for with addr_of.

Comment (RalfJung) [reply library/std/src/sys/unix/fs.rs]: Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/319
