### PR TITLE
Do not complain about missing crate named as a keyword

### LINKED ISSUE #57198: Wrong suggestion
```
error: expected identifier, found reserved keyword `unsized`
   --> src/common.rs:224:16
    |
224 |         crate::unsized::coerce_unsized_into(fx, self, dest);
    |                ^^^^^^^ expected identifier, found reserved keyword

error[E0433]: failed to resolve: maybe a missing `extern crate unsized;`?
   --> src/common.rs:224:16
    |
224 |         crate::unsized::coerce_unsized_into(fx, self, dest);
    |                ^^^^^^^ maybe a missing `extern crate unsized;`?
```

Its impossible to do `extern crate unsized` because it is a reserved keyword as concluded above.

### PR DESCRIPTION
**Pull request by estebank**
Fix #57198.

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -1034,6 +1034,8 @@ enum PathResult<'a> {
     NonModule(PathResolution),
     Indeterminate,
     Failed(Span, String, bool /* is the error from the last segment? */),
+    /// Encountered an error that is reported elsewhere
+    Ignore,
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: `NonModule(err_path_resolution())` is used for this in other places.

File: src/librustc_resolve/lib.rs [hunk 2]
```diff
@@ -3925,8 +3928,11 @@ impl<'a> Resolver<'a> {
                         });
                         if let Some(candidate) = candidates.get(0) {
                             format!("did you mean `{}`?", candidate.path)
-                        } else {
+                        } else if !ident.is_used_keyword() {
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: `ident.is_reserved()` would be more appropriate here.
