### PR TITLE
Fix float ICE

### LINKED ISSUE #90728: thread 'rustc' panicked at 'unexpected components in a float token
I'm seeing an internal compiler error on the following input, found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc):

### Code

```Rust
fn main() {
    a.5.2E+
}
```

### Error output

```
error: expected at least one digit in exponent
 --> src/main.rs:2:7
  |
2 |     a.5.2E+
  |       ^^^^^

thread 'rustc' panicked at 'unexpected components in a float token: [IdentLike("5"), Punct('.'), IdentLike("2E"), Punct('+')]', compiler/rustc_parse/src/parser/expr.rs:1041:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The ICE happens after correctly reporting a malformed float error, so low priority. Affected versions: probably all versions since that panic was introduced, I tried nightly 2021-11-07 and stable 1.56.1 and they both show the same ICE.

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'unexpected components in a float token: [IdentLike("5"), Punct('.'), IdentLike("2E"), Punct('+')]', compiler/rustc_parse/src/parser/expr.rs:1041:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/46b8e7488eae116722196e8390c1bd2ea2e396cf/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/46b8e7488eae116722196e8390c1bd2ea2e396cf/library/core/src/panicking.rs:106:14
   2: <rustc_parse::parser::Parser>::parse_dot_or_call_expr_with_
   3: <rustc_parse::parser::Parser>::parse_stmt_path_start
   4: <rustc_parse::parser::Parser>::parse_stmt_without_recovery
   5: <rustc_parse::parser::Parser>::parse_block_tail
   6: <rustc_parse::parser::Parser>::parse_fn_body
   7: <rustc_parse::parser::Parser>::parse_item_common
   8: <rustc_parse::parser::Parser>::parse_mod
   9: rustc_parse::parse_crate_from_file
  10: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::diagnostic_builder::DiagnosticBuilder>, rustc_interface::passes::parse::{closure#0}>
  11: rustc_interface::passes::parse
  12: <rustc_interface::queries::Queries>::parse
  13: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  14: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}>
  15: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

A quick inspection of the code shows that the similar case `1e+` is handled the same as `1e+2`:

https://github.com/rust-lang/rust/blob/87df4dd70f13f248a4d2d22cdd96ee59d161d741/compiler/rustc_parse/src/parser/expr.rs#L1031-L1041

So if I had to guess I would say that the match is missing this one case, so `1.2e+` should be handled the same as `1.2e+3`:

```rust
            // 1.2e+ | 1.2e- (recovered)
            [IdentLike(_), Punct('+' | '-'), IdentLike(_), Punct('+' | '-')] |
```

But no idea what does that code even do, it has a FIXME by @petrochenkov so maybe he knows better.

### PR DESCRIPTION
**Pull request by terrarier2111**
This fixes https://github.com/rust-lang/rust/issues/90728

### CODE REVIEW

**Comment by terrarier2111** [comment]
Should i create a sub-directory for my test, because the CI errors because there are 1001 files in the parser test directory but only 1000 files are allowed in a single directory?

**Comment by jackh726** [comment]
Maybe put it in `src/test/ui/parser/float-literals.rs`? I guess there's also a `src/ext/test-float-parse`, but I'm unsure what should go there vs `src/test/ui`. I think of #86761 when I see this, so maybe cc @estebank, who r+ed that PR

**Comment by terrarier2111** [comment]
@estebank what do you think is the best solution?

File: src/test/ui/parser/issue-90728.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+fn main() {
+    a.5.2E+
+    //~^ ERROR: unexpected token: `5.2E+`
+    //~^^ ERROR: expected one of `.`, `;`, `?`, `}`, or an operator, found `5.2E+`
+    //~^^^ ERROR: expected at least one digit in exponent
```
Comment (estebank) [inline src/test/ui/parser/issue-90728.rs:5]: I usually write these this way because it lets the `ERROR`s align :)
```suggestion
    //~^ ERROR: unexpected token: `5.2E+`
    //~| ERROR: expected one of `.`, `;`, `?`, `}`, or an operator, found `5.2E+`
    //~| ERROR: expected at least one digit in exponent
```

**Review by estebank — APPROVED** [review]
I'm ok with moving the test to `src/ext/test-float-parse`. After all, it *is* testing the parser.

File: src/test/ui/parser/issue-90728.stderr [hunk 2]
```diff
@@ -0,0 +1,20 @@
+error: expected at least one digit in exponent
+  --> $DIR/issue-90728.rs:2:7
+   |
+LL |     a.5.2E+
+   |       ^^^^^
```
Comment (estebank) [inline src/test/ui/parser/issue-90728.stderr:5]: This error in particular could likely be more actionable.

File: src/test/ui/parser/issue-90728.stderr [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+error: expected one of `.`, `;`, `?`, `}`, or an operator, found `5.2E+`
+  --> $DIR/issue-90728.rs:2:7
+   |
+LL |     a.5.2E+
+   |       ^^^^^ expected one of `.`, `;`, `?`, `}`, or an operator
```
Comment (estebank) [inline src/test/ui/parser/issue-90728.stderr:17]: And we could recover more gracefully after encountering it ^_^

File: src/test/ui/parser/issue-90728.stderr (hunk 2 above)
Comment (terrarier2111) [reply src/test/ui/parser/issue-90728.stderr:5]: Could you be a bit more precise about that?

File: src/test/ui/parser/issue-90728.stderr (hunk 3 above)
Comment (terrarier2111) [reply src/test/ui/parser/issue-90728.stderr:17]: Do you mean like spitting out no errors afterwards?

Comment (estebank) [reply src/test/ui/parser/issue-90728.stderr:17]: Correct, but that doesn't have to be addressed in this PR.

**Comment by terrarier2111** [comment]
For some reason the test doesn't work any more correctly after moving it to the suggested location (but it works locally). Do you guys have any idea what the issue is? @estebank @jackh726

**Comment by jackh726** [comment]
Looks like it's caused by tidy checking that file with stage0. Probably the easiest thing to do is to do a tidy ignore with a FIXME to remove it after bootstrap is updated.

**Comment by terrarier2111** [comment]
> Looks like it's caused by tidy checking that file with stage0. Probably the easiest thing to do is to do a tidy ignore with a FIXME to remove it after bootstrap is updated.

Okay, how would I do that?

**Comment by jackh726** [comment]
I think maybe `#[rustfmt::skip]` on `fn main()` will work?

**Comment by Mark-Simulacrum** [comment]
The test appears to be in src/etc which is why tidy complained - src/test is not fmt checked currently. I'm not sure we run tests in src/etc at all, so maybe it was accidentally moved into that directory?

Or, if not, the appropriate fix is to adjust rustfmt.toml at the root and ignore the right directory for this test.

**Comment by terrarier2111** [comment]
> The test appears to be in src/etc which is why tidy complained - src/test is not fmt checked currently. I'm not sure we run tests in src/etc at all, so maybe it was accidentally moved into that directory?
> 
> Or, if not, the appropriate fix is to adjust rustfmt.toml at the root and ignore the right directory for this test.

there was ```src/ext/test-float-parse``` suggested which doesn't exist, but i found out that ```src/etc/test-float-parse``` actually does exist that's why i moved it in there instead idk if that was wrong

**Comment by Mark-Simulacrum** [comment]
How was src/etc/test-float-parse/src/bin/issue-90728.stderr generated? As far as I can tell, CI does not run those tests...

It seems like this test probably belongs under the UI test directory (src/test/ui).

**Comment by terrarier2111** [comment]
> How was src/etc/test-float-parse/src/bin/issue-90728.stderr generated? As far as I can tell, CI does not run test-float-parse tests...
> 
> It seems like this test probably belongs under the UI test directory (src/test/ui).

I did put it into src/test/ui/parser/ but it errored because there were already 1000 tests inside the directory which is why i had to move it in the first place

**Comment by jackh726** [comment]
Okay, let's just move this as a test case in `src/test/ui/parser/float-literals.rs`. Can you also squash the commits?

**Comment by terrarier2111** [comment]
> Okay, let's just move this as a test case in `src/test/ui/parser/float-literals.rs`. Can you also squash the commits?

But my test is supposed to fail while the float literals stuff is supposed to compile. Also i will squash my commits once this test issue is resolved.

**Comment by jackh726** [comment]
Okay...so new plan. Let's make an `issues` directory in `parser` and move all the `issue-*` tests there...but can we do that in a separate PR? Sorry, it's a pain.

**Comment by Mark-Simulacrum** [comment]
You can just make an exception in tidy (or bump the limit) -- that'll temporarily resolve the problem to let this PR proceed.

`// check-pass` or `// check-fail` etc can work to adjust tests into pass/fail as needed.

**Comment by jackh726** [comment]
Yeah, I guess a tidy exception is fine.

**Comment by terrarier2111** [comment]
> You can just make an exception in tidy (or bump the limit) -- that'll temporarily resolve the problem to let this PR proceed.
> 
> `// check-pass` or `// check-fail` etc can work to adjust tests into pass/fail as needed.

Where can I bump that limit? and should i bump it to 1001 or to something else?

**Comment by jackh726** [comment]
That would be https://github.com/rust-lang/rust/blob/b6f580acc0ce233d5c4d1f9680d354fded88b824/src/tools/tidy/src/ui_tests.rs#L26

**Comment by terrarier2111** [comment]
> That would be
> 
> https://github.com/rust-lang/rust/blob/b6f580acc0ce233d5c4d1f9680d354fded88b824/src/tools/tidy/src/ui_tests.rs#L26

Which of these limits is the one relevant to this issue? There are like 4 different limits

**Comment by jackh726** [comment]
You would have to make a new one. And probably just use 1001 as a limit.

**Comment by jackh726** [comment]
Maybe try to `./x.py clean`?

We weren't *shouldn't* be increasing the test limit - the fact that we've hit it means that we're already past the point of the directory being "unwieldy". A proper solution would be either moving tests into subdirectories (like issues, but others maybe) or to combine related tests (this can be tricky and there hasn't really been a push for this).

Another thing to think about (not for this PR), would be to have tidy issue a *warning* at some lower threshold than the 1000 for errors. In theory, the noise might prompt a contributor to organize tests a bit.

File: src/test/ui/parser/issue-90728.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/parser/issue-90728.stderr:5]: I mean using a `span_suggestion_verbose` to produce something like the following (just a rough draft, doesn't have to look like this exactly):
```
error: expected at least one digit in exponent
  --> $DIR/issue-90728.rs:2:7
   |
LL |     a.5.2E+
   |       -----^ expected a number here
   |       |
   |       this numeric literal is incomplete
help: write a valid exponent
   |
LL |     a.5.2E+1
   |            +

**Comment by terrarier2111** [comment]
@jackh726 i think this should be ready to be merged.

**Comment by jackh726** [comment]
Its helpful that PRs prior to this had to handle the parser test limit 🤣

@bors r+ rollup
