### PR TITLE
[windows] Add testscase for self-contained executables and fix pthread linking

### LINKED ISSUE #71061: `i686-pc-windows-gnu` executables depend on additional DLL
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: Get portable executable depending only on `C:/Windows/System32` libraries.
Instead, this happened: Since `nightly-2020-03-15` (most likely https://github.com/rust-lang/rust/pull/67502) building with `i686-pc-windows-gnu` target results in executable that depends on `libwinpthread-1.dll` beside typical libraries.

### Meta
`rustc --version --verbose`:
```
rustc 1.44.0-nightly (94d346360 2020-04-09)
binary: rustc
commit-hash: 94d346360da50f159e0dc777dc9bc3c5b6b51a00
commit-date: 2020-04-09
host: x86_64-pc-windows-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/71061

### CODE REVIEW

File: src/librustc_codegen_ssa/back/link.rs [hunk 1]
```diff
@@ -1241,6 +1238,9 @@ fn add_late_link_args(
             cmd.args(args);
         }
     }
+    if let Some(args) = sess.target.target.options.late_link_args.get(&flavor) {
+        cmd.args(args);
+    }
```
Comment (petrochenkov) [inline src/librustc_codegen_ssa/back/link.rs:1243]: This is pretty fragile.
"More specific" options conventionally go after "less specific" options.
If some option lists in target specs share tails rather than starts and their order is important, then I guess they'll have to be written explicitly in target specs.

Comment (mati865) [reply src/librustc_codegen_ssa/back/link.rs]: 🏳️

**Comment by Dylan-DPC** [comment]
failing in rollup 

@bors r-

**Comment by mati865** [comment]
We have nightly regression where `i686-pc-windows-gnu` binaries depend on `libwinpthread-1.dll`. I'll open the issue and try to fix it soon.

**Comment by mati865** [comment]
This time tested on `i686-pc-windows-gnu` but not rolling up is probably good idea.

**Comment by mati865** [comment]
@bors r-
Last commit is not approved.

**Comment by Amanieu** [comment]
It looks fine. I seem to remember libgcc having a dependency on libpthread, but it seems that this is not the case.

@bors r+

**Comment by mati865** [comment]
@Amanieu it's convoluted...
IIRC `libgcc_{eh,s}` depend on `winpthreads` which in turn depend on `libgcc`.
I hope it can be replaced by `compilert-rt` + `libunwind` (no more `winpthreads`) one day.
