### PR TITLE
Move configuration 1 phase before crate metadata collection

### LINKED ISSUE #25347: #![cfg_attr] doesn't work for crate-level attributes
The `#[cfg_attr]` attribute doesn't work correctly for crate-level attributes. It seems to work in other cases as an inner attribute, but for crate-level attributes it yields the same warning that you'd see if you used the crate attribute on a non-root module:

```rust
#![cfg_attr(foo, crate_type="lib")]

fn main() {}
```

When compiled with `rustc --cfg foo`:

> ```
unnamed.rs:1:18: 1:35 warning: unused attribute, #[warn(unused_attributes)] on by default
unnamed.rs:1 #![cfg_attr(foo, crate_type="lib")]
                              ^~~~~~~~~~~~~~~~~
unnamed.rs:1:18: 1:35 warning: crate-level attribute should be in the root module, #[warn(unused_attributes)] on by default
unnamed.rs:1 #![cfg_attr(foo, crate_type="lib")]
                              ^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by lilyball**
Stripping unconfigured items prior to collecting crate metadata means we
can say things like `#![cfg_attr(foo, crate_type="lib")]`.

Fixes #25347.

### CODE REVIEW

File: src/test/run-make/crate-attributes-with-cfg_attr/lib.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![cfg_attr(foo, crate_type="lib")]
```
Comment (alexcrichton) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: Could this be included as a `run-pass` test instead? You could have an auxiliary file which uses conditional compilation to build a library and then also have a binary which uses conditional compilation to build itself as a binary instead (using `// compile-flags` to pass `--cfg` flags).

**Comment by alexcrichton** [comment]
Looks good to me, thanks! r=me with a switch to a run-pass instead of a run-make test.

File: src/test/run-make/crate-attributes-with-cfg_attr/lib.rs (hunk 1 above)
Comment (kballard) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: I wasn't quite sure how to make a `run-pass` test, but I've never actually looked at the `auxiliary` folder before so I wasn't really aware of how to do that. I'll try that now.

> and then also have a binary which uses conditional compilation to build itself as a binary instead

What do you mean? Doesn't rustc assume it's a binary by default if not otherwise specified? I don't see how I can specify a file that would build as a library by default and override it to a binary with an attribute (since `--crate-type` on the command-line overrides `#![crate_type]`).

Comment (alexcrichton) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: Ah I think an auxiliary file won't actually work due to the compiler passing `--crate-type`, but this should work as a run-pass test because the compiler only assumes a binary output if no other is specified:

```rust
// src/test/run-pass/foo.rs

// compile-flags: --cfg foo
#![crate_type = "lib"]
#![cfg_attr(foo, crate_type = "bin")]
extern crate bar;
fn main() {}
```

Comment (kballard) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: I checked compiletest and it skips `--crate-type` if the auxiliary file specifies `// no-prefer-dynamic` (although I don't know why it doesn't just fall back to lib in that case). I could use the duplicate `crate_type` attributes like that but it results in a warning about the first one being unused.

Comment (kballard) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: Still, I suppose the warning is benign. It would be simpler to not have an auxiliary file.

Comment (kballard) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: Oh huh, it's actually building both a binary and a library. I swear I tried this before and got a warning.

Comment (kballard) [inline src/test/run-make/crate-attributes-with-cfg_attr/lib.rs]: That said, it doesn't work as a run-pass, because building two files like that doesn't seem to work with the `-o` flag (based on the error message, it seems to always result in the specified output path being the library).

**Comment by sfackler** [comment]
This isn't a total fix since some attributes like `#[path]` are processed directly in the parser.

**Comment by kballard** [comment]
@sfackler Good point, though `#[path]` presumably isn't usable at the crate level.

**Comment by klutzy** [comment]
Filed #25544 for `#[path]` issue since it seems inherent to parser behavior.
