### PR TITLE
Fix line display for hoedown

### LINKED ISSUE #41401: [Hoedown comeback regression] Code in doc not tested with future warning, when it was always a test in the past
Test case:

```rust
// src/lib.rs

/// ```
/// assert!(true);
/// ```
///
/// ```
/// assert!(true);
/// ```
pub fn test() {}
```

**Expected:** when running `cargo test`, it will run two doctests (as in stable and beta).

```
running 2 tests
test src/lib.rs - test (line 1) ... ok
test src/lib.rs - test (line 5) ... ok
```

**Actual:** Only the first doctest is run, the second one is skipped, with this warning:

```
WARNING: src/lib.rs - test (line 5) Code block is not currently run as a test, but will in future versions of rustdoc. Please ensure this code block is a runnable test, or use the `ignore` directive.

running 1 test
test src/lib.rs - test (line 1) ... ok
```

Real life test case: 

* Code: https://github.com/iron/params/blob/8f9db17a4265264327f010fadb6e2231e0e53bde/src/lib.rs#L214-L237
* Doc: https://docs.rs/params/0.6.0/params/struct.Map.html#examples
* Travis: https://travis-ci.org/iron/params/jobs/223656157#L421-L429

(cc @GuillaumeGomez #41290)

----

No warnings in this version:

```
rustdoc 1.18.0-nightly (28a742997 2017-04-13)
binary: rustdoc
commit-hash: 28a74299778cdad4ea999e4ee8f8c1ef793338bd
commit-date: 2017-04-13
host: x86_64-apple-darwin
release: 1.18.0-nightly
LLVM version: 3.9
```

Have warnings in this version:

```
rustdoc 1.18.0-nightly (9f2abadca 2017-04-18)
binary: rustdoc
commit-hash: 9f2abadca2d065bf81772cb84981d0a22d8e98b3
commit-date: 2017-04-18
host: x86_64-apple-darwin
release: 1.18.0-nightly
LLVM version: 3.9
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #41401.

r? @rust-lang/docs

### CODE REVIEW

File: src/librustdoc/test.rs [hunk 1]
```diff
@@ -432,11 +432,38 @@ impl Collector {
...
+    if line > 1 {
+        for test in &self.old_tests {
+            if test.starts_with(&tmp_name) {
+                number += 1;
+            }
+        }
+    }
+    if number < line {
+        line -= number;
+    }
```
Comment (QuietMisdreavus) [inline src/librustdoc/test.rs]: What cases were you running into where the number of tests was more than the line number itself? Or is this a guard to prevent underflowing a usize?

**Comment by frewsxcv** [comment]
@bors delegate=quietmisdreavus

In case you feel confident enough to review this :)

**Comment by kennytm** [comment]
Sorry it may be hijacking, just inspecting the test result of this PR it seems to uncover additional false warnings not yet fixed.

1. https://github.com/rust-lang/book/blame/ad7de198/first-edition/src/conditional-compilation.md#L58-L62 ([Travis](https://travis-ci.org/rust-lang/rust/jobs/223750302#L5017);  [rendered book](https://doc.rust-lang.org/book/conditional-compilation.html))
2. https://github.com/rust-lang/book/blame/ad7de198/first-edition/src/concurrency.md#L132-L141
3. https://github.com/rust-lang/book/blame/ad7de198/first-edition/src/crates-and-modules.md#L76-L92 (additionally, a warning is placed on a ````` ```rust,ignore ````` code block 😕)
4. https://github.com/rust-lang/book/blame/ad7de198/first-edition/src/match.md#L48-L59<br>(... and a lot more from The Book. It seems most of these come after a ````` ```text ````` block)
5. https://github.com/rust-lang/book/blame/ad7de198/first-edition/src/primitive-types.md#L32-L35 (no ````` ```text ````` block before, maybe a different issue.)
6. https://github.com/rust-lang-nursery/reference/blame/6b0de90d/src/tokens.md#L92-L98 (the whole file is not tested)
7. https://github.com/rust-lang-nursery/reference/blame/6b0de90d/src/types.md#L194-L201

The [Travis log](https://travis-ci.org/rust-lang/rust/jobs/223750302) should provide more cases.

**Comment by GuillaumeGomez** [comment]
This is really hell...

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by steveklabnik** [comment]
@bors: r+

thanks @GuillaumeGomez ❤️  (and @kennytm for the extra cases)

**Comment by ollie27** [comment]
The latest travis log: https://travis-ci.org/rust-lang/rust/jobs/224065533 still has a lot of "Code block is not currently run as a test" warnings so this is clearly not yet fully fixed.

**Comment by GuillaumeGomez** [comment]
Just improving priority a bit.

@bors: p=1

**Comment by alexcrichton** [comment]
@bors: retry

* ar.exe error https://github.com/rust-lang/rust/issues/40546

**Comment by arielb1** [comment]
@bors retry
- mac builders not starting

**Comment by frewsxcv** [comment]
@bors retry

trying to kick homu

**Comment by frewsxcv** [comment]
This failed on Windows, but bors never picked it up. Going to retry this in a rollup

@bors retry
