### PR TITLE
Don't bail out before linting in generic contexts.

### LINKED ISSUE #69021: "exceeding_bitshifts" lint does not work in associated consts
The `exceeding_bitshifts` lint should fire on the following code, but it does not:
```rust
pub trait Foo {
    const N: i32;
}

impl<T: Foo> Foo for Vec<T> {
    const N: i32 = T::N << 42; // no warning here
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=11c45c0bd4b22ff997e69901b3bb0709)
(This testcase now exists in-tree as a FIXME in `ui/lint/lint-exceeding-bitshifts.rs`.)

Cc @oli-obk @wesleywiser 

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/69021#issuecomment-584603723).

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #69021.

cc #70017

r? @RalfJung

### CODE REVIEW

File: src/test/ui/associated-const/lints-used-unused.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// Tests that associated constants are checked whether they are used or not.
+//
+// revisions: used unused
+// compile-flags: -Copt-level=2 --emit link
+
+#![cfg_attr(unused, allow(dead_code))]
+#![deny(arithmetic_overflow)]
+
+pub trait Foo {
+    const N: i32;
```
Comment (Centril) [inline src/test/ui/associated-const/lints-used-unused.rs]:
```suggestion
    const N: i32 = 1 << 42; //~ ERROR this arithmetic operation will overflow
```

**Comment by Centril** [comment]
(Let's make sure we perf test this before landing.)

File: src/librustc_lint/builtin.rs [hunk 2]
```diff
@@ -1178,18 +1178,38 @@ fn check_const(cx: &LateContext<'_, '_>, body_id: hir::BodyId) {
     let _ = cx.tcx.const_eval_poly(def_id);
 }
 
+fn check_assoc_const(cx: &LateContext<'_, '_>, body_id: hir::BodyId) {
+    let tcx = cx.tcx;
+    let def_id = tcx.hir().body_owner_def_id(body_id);
+    // Force optimized mir to be loaded, so we get lints even if the associated const is unused.
+    let _mir = tcx.optimized_mir(def_id);
```
Comment (oli-obk) [inline src/librustc_lint/builtin.rs]: Huh... This should happen for all associated constants on `pub trait`s even without this PR. I'm not sure I understand how this isn't happening. https://github.com/rust-lang/rust/blob/9bba047c2e425fce03b039bcb8ccd60ddcbc80a0/src/librustc_metadata/rmeta/encoder.rs#L897 should also call this for all exported associated constants.

If it weren't already happening https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d3d29cd2ef2477c0372fb297b785de2d should fail to compile I think.

Maybe the metadata encoding is happening so late that error reporting is already not happening anymore? I remember we used to have some such problems, but I thought those were gone.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs]: My theories for why associated consts were not properly linted before involve these two lines, but I am not actually sure what they are doing or why:

https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L602

https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L850

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1185]: > Huh... This should happen for all associated constants on pub traits even without this PR. I'm not sure I understand how this isn't happening.

That entire pass doesn't execute for executables -- the `encode_metadata` query doesn't run for them:

https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/librustc_interface/passes.rs#L912-L930

And true enough, if I checkout to before this change and run my test case with `--crate-type=lib` or `--crate-type=dylib`, I get the lint, even with the associated const unused.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: By "this change", you mean https://github.com/rust-lang/rust/commit/faf5eac854f9099b54854145f2307cae3f3aa768 ?

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1185]: Sorry, I meant before the changes in this PR. Exact commit I went to was a7deedd2db9b65e293a4b7af5bd668f9efba5bfc, so I could run it on my used-unused test case

Comment (oli-obk) [reply src/librustc_lint/builtin.rs:1185]: oh... that's actually fairly reasonable then... Dead code isn't even properly type checked in some cases...

We should probably add tests that ensure we emit these lints in `--lib` mode

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1185]: > oh... that's actually fairly reasonable then

In that case, should we preserve the current behaviour of not linting unused associated consts?

> We should probably add tests that ensure we emit these lints in --lib mode

Sure thing. I'll add a new revision to the relevant tests.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: @oli-obk even as a library with a public crate, [we currently have an issue](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=11c45c0bd4b22ff997e69901b3bb0709).

Comment (oli-obk) [reply src/librustc_lint/builtin.rs:1185]: Then I don't understand how

> And true enough, if I checkout to before this change and run my test case with --crate-type=lib or --crate-type=dylib, I get the lint, even with the associated const unused.

can be true. I'm very confused now.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: @jumbatm on which exact test file did you do the test quoted above? It seems we cannot reproduce that on the playground.

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1185]: `lint-used-unused.rs`, introduced in this PR.(I'd link it but I'm on mobile right now)

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: Ah, that just tests arithmetic overflow. Bitshifts are special because we can lint them without knowing the LHS.
*That* part still does not work in associated consts.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: We [already have a test for other arithmetic operations](https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/issue-69020.rs).

What I don't understand is where that lint is coming from, given that we cannot actually evaluate those consts -- and why it then does not also work for bitshifts.
I think these errors must be coming from const_eval, not const_prop. But that only explains the "why not bitshifts" part, not the "why does it happen at all" part.

Comment (oli-obk) [reply src/librustc_lint/builtin.rs:1185]: Ok, so we're back at my question how, for libraries `optimized_mir` is not called for all (even associated) constants (or whether we just don't see the lints during metadata encoding)

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: Hm, looking at [the output](https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/test/ui/consts/issue-69020.noopt.stderr) though this the `arithmetic_overflow` lint, not a const_eval panic.

So, it's definitely const_prop. But const_prop bails out early in the case of the bitshift test.
Which brings me back to the two "bail out" lines that I keep mentioning as prime suspects:

https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L601-L603

https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L850

The bug *must* be something where const_prop runs (because we see it run on other, very similar associated consts) but fails to reach the problematic bitshift.

Comment (oli-obk) [reply src/librustc_lint/builtin.rs:1185]: some of these bailouts are just papering over interpreter issues, these are likely resolved by now. Or they are there for speedups, which we should benchmark before touching them.

But that still doesn't explain why just running `optimized_mir` creates more lints. Const prop runs as part of `optimized_mir` and not out of any other reason.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: > But that still doesn't explain why just running optimized_mir creates more lints. Const prop runs as part of optimized_mir and not out of any other reason.

Does it, though? @jumbatm did you confirm that specifically the bitshift testcase from https://github.com/rust-lang/rust/issues/69021 passes that way? (I think we got a lot of confusion because of other testcases, but as the bugreport says the only issue we currently know of is with bitshifts.)

File: src/test/ui/lint/lint-exceeding-bitshifts.rs [hunk 3]
```diff
@@ -15,7 +15,7 @@ pub trait Foo {
 }
 
 impl<T: Foo> Foo for Vec<T> {
-    const N: i32 = T::N << 42; // FIXME this should warn
+    const N: i32 = T::N << 42; // ERROR: arithmetic operation will overflow
```
Comment (RalfJung) [inline src/test/ui/lint/lint-exceeding-bitshifts.rs:18]: Why did the stderr file not change when there is a new error here?

Comment (RalfJung) [reply src/test/ui/lint/lint-exceeding-bitshifts.rs:18]: Ah, the comment is actually a NOP. You have to make it `//~ ERROR`.

So this PR definitely did not fix the original issue (or else PR CI would have complained that this test raises an error where none is expected).

File: src/librustc_lint/builtin.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1185]: See https://github.com/rust-lang/rust/pull/70566#discussion_r401718517: calling `optimized_mir` makes no difference at all, actually.

File: src/test/ui/lint/lint-exceeding-bitshifts.rs (hunk 3 above)
Comment (jumbatm) [reply src/test/ui/lint/lint-exceeding-bitshifts.rs]: Oh shoot, yeah. I've fixed the test case now, and yeah, I can confirm this doesn't fix the original test case.

**Comment by oli-obk** [comment]
@rust-timer build

File: src/test/ui/associated-const/lints-used-unused.rs [hunk 4]
```diff
@@ -0,0 +1,27 @@
+// Tests that associated constants are checked whether they are used or not.
```
Comment (RalfJung) [inline src/test/ui/associated-const/lints-used-unused.rs:1]: What is the benefit of adding a new test file for this, instead of using the existing one?

In particular, this test is less useful as it fails tot est both debug and release mode.
For the "used" and "unused" thing, just have two constants, one that is used and one that is not.

**Comment by RalfJung** [comment]
@jumbatm you used to have some new tests for arithmetic in associated consts in an earlier version of this PR. Those tests already pass, but having the order of operators swapped might still be interesting just in case their order in the MIR ever matters. Care to submit a separate PR that extends the existing `src/test/ui/consts/issue-69020.rs` with those cases?
You could also rename it to `src/test/ui/consts/issue-69020-assoc-const-arith-overflow.rs`. (@oli-obk is there another fodler this could move into?)

**Comment by oli-obk** [comment]
We could start a `const_prop` folder to separate out the const prop things from the const eval things

File: src/test/ui/associated-const/lints-used-unused.rs (hunk 4 above)
Comment (jumbatm) [reply src/test/ui/associated-const/lints-used-unused.rs:1]: > What is the benefit of adding a new test file for this, instead of using the existing one?

Compilation stops at this first error, otherwise -- is this something that should be addressed though compilation fails anyway?

> In particular, this test is less useful as it fails to test both debug and release mode.
For the "used" and "unused" thing, just have two constants, one that is used and one that is not.

Ah, true. I'll fix that up now.

**Comment by jumbatm** [comment]
> Care to submit a separate PR that extends the existing src/test/ui/consts/issue-69020.rs with those cases?

Sure thing!

> is there another folder this could move into?

>  We could start a const_prop folder to separate out the const prop things from the const eval things

In my opinion, a `const_prop` folder would imply testing the mir after propagation was correct (and indeed, we already have a const_prop folder for this in mir-opt). Additionally, if this lint's implementation was moved out of `const_prop` (which could happen to solve the issue of debug and release builds giving different lints), we'd have to move the test somewhere else.

I'd say because we're checking lints get emitted properly (ie, a ui test), it makes sense to me to put it under the existing `src/test/ui/associated-const`.

File: src/test/ui/associated-const/lints-used-unused.rs (hunk 4 above)
Comment (RalfJung) [reply src/test/ui/associated-const/lints-used-unused.rs:1]: > Compilation stops at this first error, otherwise -- is this something that should be addressed though compilation fails anyway?

No it does not? That test already contains multiple errors. Making it contain more of them should work just fine.

**Comment by oli-obk** [comment]
> I'd say because we're checking lints get emitted properly (ie, a ui test), it makes sense to me to put it under the existing src/test/ui/associated-const.

That's a good place indeed

File: src/test/ui/associated-const/lints-used-unused.rs (hunk 4 above)
Comment (oli-obk) [reply src/test/ui/associated-const/lints-used-unused.rs:1]: There may still be some `abort_if_errors` around, not sure. The lint could be turned into `warn` to work around any issues with that.

**Comment by RalfJung** [comment]
There's also `src/test/ui/lint`. We have too many folders.^^

File: src/test/ui/associated-const/lints-used-unused.rs (hunk 4 above)
Comment (jumbatm) [reply src/test/ui/associated-const/lints-used-unused.rs:1]: Yeah, it didn't when I ran stage1 rustc manually on the test case. 

Ended needing `--emit=link` + changing the lints to warn to get all lints.

**Comment by jumbatm** [comment]
This is good for a perf run if there's no further comments. Can someone run rust-timer for me? Thanks!

**Comment by oli-obk** [comment]
@rust-timer build

**Comment by oli-obk** [comment]
@rust-timer queue

File: src/librustc_lint/builtin.rs [hunk 5]
```diff
@@ -1168,18 +1168,38 @@ fn check_const(cx: &LateContext<'_, '_>, body_id: hir::BodyId) {
...
```
Comment (RalfJung) [inline src/librustc_lint/builtin.rs:1175]: Didn't we agree that this part makes no difference?

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1175]: It depends on whether or not we want to lint unused associated consts in executables, per the question I asked in  https://github.com/rust-lang/rust/pull/70566#discussion_r401605179. 

If not, I'll drop this change and convert lints-used-unused to test lib vs executable lints and assert we don't emit the lint for executables.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1175]: Doesn't https://github.com/rust-lang/rust/pull/70696 establish that we don't need this extra `optimized_mir` call to cover unused associated consts?

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1175]: It establishes it for libraries - - that test case is `#[crate_type = "lib"]`. That other `optimized_mir` call doesn't happen for executables.

Comment (RalfJung) [reply src/librustc_lint/builtin.rs:1175]: Oh I see.

However, given that (according to @oli-obk ), we don't even fully type-check dead code in binaries -- I am not sure if not linting there is truly a bug.

Comment (jumbatm) [reply src/librustc_lint/builtin.rs:1175]: Yeah, fair enough. I'll revert this change.

File: src/test/ui/lint/lint-exceeding-bitshifts.rs [hunk 6]
```diff
@@ -1,12 +1,12 @@
+// check-pass
 // revisions: noopt opt opt_with_overflow_checks
+// compile-flags: --emit=link
```
Comment (RalfJung) [inline src/test/ui/lint/lint-exceeding-bitshifts.rs:3]: I think this makes it equivalent to `build-pass`; what is the point of this flag?

**Comment by RalfJung** [comment]
Perf looks good except for noisy syn -- and that was before you got rid of `optimized_mir()` again, so I think we are good in that regard.

File: src/test/ui/lint/lint-exceeding-bitshifts.rs (hunk 6 above)
Comment (jumbatm) [reply src/test/ui/lint/lint-exceeding-bitshifts.rs]: Yeah, not sure what I needed it for. I've reverted the flags back to the way they were before.

**Review by oli-obk — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
@RalfJung this looks good to be merged? or is there anything pending?

**Comment by RalfJung** [comment]
I don't entirely understand why only some of the errors show up with `deny`, but overall this looks good. Sorry for the delay, I had not realized this was waiting for me.

@bors r+ rollup

**Comment by RalfJung** [comment]
This failed the rollup in https://github.com/rust-lang/rust/pull/71143#issuecomment-613637978. @bors r-

@jumbatm could you please rebase and re-bless? rustc output changed a bit to the reference files need updating.

**Comment by jumbatm** [comment]
This is good to go again.

**Comment by RalfJung** [comment]
@jumbatm thanks! Please always leave a message after a force-push as GitHub only unreliably sends email notifications for them.
