### PR TITLE
Provide a span if main function is not present in crate

### LINKED ISSUE #36561: Error without location
There're two known compiler errors that provide no location information:

```
error: main function not found
error: aborting due to previous error
```

It holds true for both the standard output and the JSON error format.

While the latter is a meta error and obviously is not related to a particular place in the source code, the former one could at least come with a file name. It would be of use to both humans and IDEs, particularly when there're several executables in a single project (in the `examples` or `src/bin` folders).

Since there's always a particular file in which `rustc` is looking for the `main()` function, this file name should be mentioned in the message either with the `1:1` position, or with no position at all. This would let the user or IDE to quickly jump directly to the file in which the problem must be fixed.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Unfortunately, the diagnostic machinery does not cope well with an empty
span which can happen if the crate is empty, in which case we merely set
a spanless note.

Tests are already updated for this change, so a dedicated test is not added.

Resolves #36561.

### CODE REVIEW

**Comment by ehuss** [comment]
> the diagnostic machinery does not cope well with an empty span

I'm curious what issues there are with this, can you say more?  

(For context, I wrote this note, and at the time [I noticed](https://github.com/rust-lang/cargo/issues/4948#issuecomment-358115715) there are a few other diagnostics that don't have spans.  I've also written editor integration where it has to handle these kinds of things, so I'm a bit surprised it causes issues.  Tools still need to handle diagnostics without filenames.)

FWIW, this seems like a good improvement. At the time I didn't know it was possible to generate a span like this.

**Comment by estebank** [comment]
r=me once green

**Comment by Mark-Simulacrum** [comment]
> I'm curious what issues there are with this, can you say more?

It's not completely clear exactly where the problems arise, but I was able to trigger an ICE or two, particularly with `--error-format=json`; I suspect the problem lies in that we expect all files to have at least one line such that `lines - 1 >= 0`, but if this is not the case, at least in a debug-assertion enabled compiler we will panic when lines is 0. It's quite possible this can be fixed, but I don't think it's worth even filing an issue (it seems relatively unimportant that we can emit errors in completely empty files, as that is rare).

**Comment by Mark-Simulacrum** [comment]
Ah, I also forgot to mention -- in some situations, I was unable to trigger an ICE with the normal machinery (though `--error-format=json` did, I believe); however, the span and associated label was still not emitted (as if they had not been set).

File: src/librustc/middle/entry.rs [hunk 1]
```diff
@@ -163,7 +163,14 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
             err.emit();
         } else {
             if let Some(ref filename) = tcx.sess.local_crate_source_file {
-                err.note(&format!("consider adding a `main` function to `{}`", filename.display()));
+                let sp = tcx.hir().krate().span;
+                let note = format!("consider adding a `main` function to `{}`", filename.display());
+                if let Ok(_) = tcx.sess.source_map().lookup_line(sp.lo()) {
+                    err.set_span(sp);
```
Comment (Centril) [inline src/librustc/middle/entry.rs]: I think this in particular, and the other stuff could use a comment.

File: src/librustc/middle/entry.rs [hunk 2]
```diff
@@ -163,7 +163,14 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
             err.emit();
         } else {
```
Comment (Centril) [inline src/librustc/middle/entry.rs]: I think the parent `} else { // There is no main function.` should be extracted to a separate function to disturb main flow less:

```rust
fn error_there_is_no_main_function(...)
```

**Review by Centril — DISMISSED** [review]

File: src/librustc/middle/entry.rs (hunk 2 above)
Comment (Mark-Simulacrum) [reply src/librustc/middle/entry.rs]: Since this is the trailing part of the function I don't think that'd be all that helpful (in particular, there is no error-handling code which precedes or follows this block).

Comment (Centril) [reply src/librustc/middle/entry.rs]: It is helpful in the sense that I can read `error_there_is_no_main_function(..);`, quickly understand that this is the errror case and ignore / focus on that branch. Plus, planning for growth is a good idea. Less importantly, it also helpful in the sense that `fn error_there_is_no_main_function(...)` is indented one time less.

Comment (Mark-Simulacrum) [reply src/librustc/middle/entry.rs]: I disagree, but will implement the requested changes to allow us to move forward.

File: src/librustc/middle/entry.rs [hunk 3]
```diff
@@ -148,31 +148,44 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
...
             }
-            err.emit();
         }
-
-        None
+        if tcx.sess.teach(&err.get_code().unwrap()) {
+            err.note("If you don't know the basics of Rust, you can go look to the Rust Book \
+                        to get started: https://doc.rust-lang.org/book/");
+        }
+        err.emit();
```
Comment (Centril) [inline src/librustc/middle/entry.rs]: btw, `err.emit();` is common to both branches

File: src/librustc/middle/entry.rs [hunk 4]
```diff
@@ -148,32 +148,44 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
...
+fn no_main_err(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) {
+    // There is no main function.
+    let mut err = struct_err!(tcx.sess, E0601,
+        "`main` function not found in crate `{}`", tcx.crate_name(LOCAL_CRATE));
+    if !visitor.non_main_fns.is_empty() {
+        // There were some functions named 'main' though. Try to give the user a hint.
+        err.note("the main function must be defined at the crate level \
+                    but you have one or more functions named 'main' that are not \
+                    defined at the crate level. Either move the definition or \
+                    attach the `#[main]` attribute to override this behavior.");
```
Comment (estebank) [inline src/librustc/middle/entry.rs]: Maybe we should have a span pointing at where the `main` function _should_ be, like we're doing below?

File: src/librustc/middle/entry.rs [hunk 5]
```diff
@@ -148,32 +148,44 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
...
+            } else {
+                err.note(&note);
             }
-            err.emit();
         }
-
-        None
+        if tcx.sess.teach(&err.get_code().unwrap()) {
+            err.note("If you don't know the basics of Rust, you can go look to the Rust Book \
+                        to get started: https://doc.rust-lang.org/book/");
```
Comment (estebank) [inline src/librustc/middle/entry.rs]: The indentation on both strings is off by two chars :)

**Comment by Mark-Simulacrum** [comment]
Alright, restructured the error quite a bit to try and always provide the filename in the note as well as point at the span.

**Comment by Mark-Simulacrum** [comment]
Okay, CI is (finally) green and this is ready for another round of review since the error messages changed.

File: src/librustc/middle/entry.rs [hunk 6]
```diff
@@ -148,34 +148,52 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
...
+    let mut err = struct_err!(tcx.sess, E0601,
+        "`main` function not found in crate `{}`", tcx.crate_name(LOCAL_CRATE));
+    let filename = &tcx.sess.local_crate_source_file;
+    let note = if !visitor.non_main_fns.is_empty() {
+        // There were some functions named 'main' though. Try to give the user a hint.
+        format!("the main function must be defined at the crate level{} \
+                 but you have one or more functions named 'main' that are not \
+                 defined at the crate level. Either move the definition or \
+                 attach the `#[main]` attribute to override this behavior.",
+                 if let Some(filename) = filename {
```
Comment (Centril) [inline src/librustc/middle/entry.rs]: This could be expressed more succinctly with:
```rust
filename.map(|f| format!(" (in `{}`)", f.display()).unwrap_or_default()
```

File: src/librustc/middle/entry.rs [hunk 7]
```diff
@@ -148,34 +148,52 @@ fn configure_main(tcx: TyCtxt<'_>, visitor: &EntryContext<'_, '_>) -> Option<(De
...
+    // note. This is a relatively simple way to detect that case and emit a span-less
+    // note instead.
+    if let Ok(_) = tcx.sess.source_map().lookup_line(sp.lo()) {
+        err.set_span(sp);
+        err.span_label(sp, &note);
+    } else {
+        err.note(&note);
+    }
+    for &(_, span) in &visitor.non_main_fns {
+        err.span_note(span, "here is a function named 'main'");
```
Comment (Centril) [inline src/librustc/middle/entry.rs]:
```suggestion
        err.span_note(span, "here is a function named `main`");
```

File: src/librustc/middle/entry.rs (hunk 6 above)
Comment (Mark-Simulacrum) [reply src/librustc/middle/entry.rs]: hm, that's.. quite dense, I think I'd prefer to leave it as is.

Comment (Centril) [reply src/librustc/middle/entry.rs]: How so? Seems like exactly the sort of situation `.map(...).unwrap_or_default()` is intended for.

File: src/test/ui/issues/issue-49040.stderr [hunk 8]
```diff
@@ -5,8 +5,12 @@ LL | #![allow(unused_variables)];
    |                            ^ help: remove this semicolon
 
 error[E0601]: `main` function not found in crate `issue_49040`
+  --> $DIR/issue-49040.rs:1:1
    |
-   = note: consider adding a `main` function to `$DIR/issue-49040.rs`
+LL | / #![allow(unused_variables)];
+LL | |
+LL | | fn foo() {}
+   | |__^ consider adding a `main` function to `$DIR/issue-49040.rs`
```
Comment (estebank) [inline src/test/ui/issues/issue-49040.stderr]: TODO: This looks like an off-by-one span error in the crate's span.

**Comment by estebank** [comment]
One thing that came to mind is that when an `fn main` is missing, editors like VSCode will highlight the entire file in red, which is not ideal. We could use one of the methods in `Span` to point only at the first or last char/span pos. This can be done in a follow up.

@bors r+

**Comment by Mark-Simulacrum** [comment]
FWIW, I ran into problems pointing at the first character as we sometimes try to lookup the previous line which then usually doesn't exist, and last character felt odd.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/64452, @bors r-

You need to `--bless --compare-mode=nll`.

**Comment by Mark-Simulacrum** [comment]
@bors r=estebank

Ran with compare-mode=nll; can't wait until we can remove it.
