### PR TITLE
[MIR] Add PointerCast for Unsize casts of fat pointers.

### LINKED ISSUE #33387: MIR related ICE: Title N/A
Continuing from https://github.com/rust-lang/rust/issues/33295#issuecomment-215999442 but using a newer rustc (`0eb575c70`):

```shell
$ cargo bench

Compiling ethcore-util v1.1.0 (file:///parity-master/util)
     Running `rustc src/lib.rs --crate-name ethcore_util --crate-type lib -C opt-level=3 --test --cfg feature=\"default\" -C metadata=d7bb43a68be26600 -C extra-filename=-d7bb43a68be26600 --out-dir /parity-master/util/target/release --emit=dep-info,link -L dependency=/parity-master/util/target/release -L dependency=/parity-master/util/target/release/deps --extern bigint=/parity-master/util/target/release/deps/libbigint-3af9bccf4cd0f92f.rlib --extern secp256k1=/parity-master/util/target/release/deps/libsecp256k1-86d36dad8b611fad.rlib --extern vergen=/parity-master/util/target/release/deps/libvergen-8849548184b2c7f0.rlib --extern sha3=/parity-master/util/target/release/deps/libsha3-1c705ec8c3fdae56.rlib --extern rustc_serialize=/parity-master/util/target/release/deps/librustc_serialize-fae78eec3acaace8.rlib --extern json_tests=/parity-master/util/target/release/deps/libjson_tests-b716cb4e63aac8b2.rlib --extern mio=/parity-master/util/target/release/deps/libmio-e45a6ae4d1161877.rlib --extern target_info=/parity-master/util/target/release/deps/libtarget_info-da75b3c3599c81c8.rlib --extern heapsize=/parity-master/util/target/release/deps/libheapsize-c012ad7d8237b492.rlib --extern ethcore_devtools=/parity-master/util/target/release/deps/libethcore_devtools-f57f591ef275f5ea.rlib --extern chrono=/parity-master/util/target/release/deps/libchrono-62ec1dcf7b159155.rlib --extern serde=/parity-master/util/target/release/deps/libserde-318c848ff88e32a6.rlib --extern rocksdb=/parity-master/util/target/release/deps/librocksdb-11162a88a6474d31.rlib --extern nix=/parity-master/util/target/release/deps/libnix-2c6b863dcb858f52.rlib --extern elastic_array=/parity-master/util/target/release/deps/libelastic_array-589122b7f1ef7c07.rlib --extern arrayvec=/parity-master/util/target/release/deps/libarrayvec-71b744037db98790.rlib --extern libc=/parity-master/util/target/release/deps/liblibc-5933dd204e100e52.rlib --extern itertools=/parity-master/util/target/release/deps/libitertools-94cd1086a826f04d.rlib --extern lazy_static=/parity-master/util/target/release/deps/liblazy_static-3abedd3a16ccd1da.rlib --extern env_logger=/parity-master/util/target/release/deps/libenv_logger-f94c1b2ff9566cda.rlib --extern slab=/parity-master/util/target/release/deps/libslab-db9531985f79ac28.rlib --extern crossbeam=/parity-master/util/target/release/deps/libcrossbeam-9ca62babdd3d1bee.rlib --extern crypto=/parity-master/util/target/release/deps/libcrypto-ac6c16f85009915d.rlib --extern tiny_keccak=/parity-master/util/target/release/deps/libtiny_keccak-cfb038c12975725b.rlib --extern log=/parity-master/util/target/release/deps/liblog-2b82a1c4336f2800.rlib --extern rand=/parity-master/util/target/release/deps/librand-5eeeaee7d2bbe2c4.rlib --extern igd=/parity-master/util/target/release/deps/libigd-b00c808cc940167e.rlib --extern time=/parity-master/util/target/release/deps/libtime-dd3c04dda4811bc8.rlib -L native=/parity-master/util/target/release/build/eth-secp256k1-7da4f57de38836b0/out -L native=/parity-master/util/target/release/build/sha3-faf8719ff3d3472e/out -L native=/parity-master/util/target/release/build/librocksdb-sys-47ecb6d53251ddb7/out/lib -L native=/parity-master/util/target/release/build/rust-crypto-727792a5f63543d1/out`
````

RUSTFLAGS = `-C target-cpu=cortex-a5 -C target-feature=+vfp4,+neon -C llvm-args=-force-target-max-vector-interleave=4 -C codegen-units=1 -C link-args=-s -Z orbit`

Error:

```rust
error: internal compiler error: src/librustc_trans/common.rs:1102: Encountered error `Unimplemented` selecting `Binder(<network::host::Host<network::tests::TestProtocolMessage> as io::IoHandler<network::host::NetworkIoMessage<Message>>>)` during trans

thread 'rustc' panicked at 'Box<Any>', src/libsyntax/errors/mod.rs:537
````

Any suggestions on how to narrow it down welcome.  Please edit the title to reflect the problem.

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #33387.

r? @eddyb

### CODE REVIEW

File: src/librustc_trans/type_.rs [hunk 1]
```diff
@@ -268,6 +269,20 @@ impl Type {
         }
     }
 
+    pub fn fat_ptr_data_type(&self) -> Type {
```
Comment (eddyb) [inline src/librustc_trans/type_.rs]: This is actually `type_of::in_memory_type_of`.

File: src/librustc_trans/type_.rs [hunk 2]
```diff
@@ -268,6 +269,20 @@ impl Type {
...
+        unsafe {
+            Type::from_ref(llvm::LLVMStructGetTypeAtIndex(self.to_ref(),
+                                                          abi::FAT_PTR_ADDR as u32))
+        }
+    }
+
+    pub fn fat_ptr_extra_type(&self) -> Type {
```
Comment (eddyb) [inline src/librustc_trans/type_.rs]: There should already be a function to get this from `Ty` in `type_of` - if it's not public, it should be.

**Comment by eddyb** [comment]
LGTM, except for using LLVM to get at information we already have.

File: src/librustc_trans/type_.rs (hunk 1 above)
Comment (luqmana) [inline src/librustc_trans/type_.rs]: Ah, I looked in `type_` but not `type_of` I guess.

File: src/librustc_trans/type_.rs (hunk 2 above)
Comment (luqmana) [inline src/librustc_trans/type_.rs]: `unsized_info_ty` it seems. Anyways, didn't actually use this. Just added it for completeness sake but looks like it's also unneeded.

File: src/librustc_trans/type_.rs (hunk 1 above)
Comment (luqmana) [inline src/librustc_trans/type_.rs]: Actually, `type_of::in_memory_type_of` isn't what I want. For `&Trait` it returns `{T*, (vtable)}` whereas I'm only trying to cast the base and thus want just `T*`.

Comment (eddyb) [inline src/librustc_trans/type_.rs]: You'd want to call it on the pointee type, which you can easy get, by changing the second `&ty::TyRawPtr(..)` pattern to `&ty::TyRawPtr(mt)` and using `mt.ty`.

Comment (luqmana) [inline src/librustc_trans/type_.rs]: Ok, just pulled that out into `type_of::fat_ptr_base_ty` since I need to call it from 2 different places and the second is not already within a match giving easy access to `mt.ty`.
