### PR TITLE
Simplify memory categorization

### LINKED ISSUE #66270: Destructuring of incorrectly defined struct produces ICE
Attempt to use destructuring on incorrectly defined struct produces ICE.
Code:
```rust
struct Bug {
    incorrect_field: 0,
}

struct Empty {}

fn main() {
    let Bug {
        any_field: Empty {},
    } = Bug {};
}
```

Output:
```
error: expected type, found `0`
 --> src/main.rs:2:22
  |
2 |     incorrect_field: 0,
  |                      ^ expected type

thread 'rustc' panicked at 'no index for a field', src/libcore/option.rs:1190:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f9444ac585e746128fc962ebd2c7bab)

### PR DESCRIPTION
**Pull request by matthewjasper**
With AST borrowck gone, mem_categorization can be simplified, a lot.

* `cmt_` is now called `Place`. Most local variable names have been updated to reflect this, but the `cat_*` methods retain their names.
* `MemCategorizationContext` no longer needs a `ScopeTree` and always needs an `InferCtxt`.
* `Place` now uses a similar representation to `mir::Place` with a `Vec` of projections.
* `Upvar` places don't include the implicit environment and capture derefs. These are now handled by `regionck` when needed.
* Various types, methods and variants only used by AST borrowck have been removed.
* `ExprUseVisitor` now lives in `rustc_typeck::expr_use_visitor`.
* `MemCategorizationContext` and `Place` live in `rustc_typeck::mem_categorization`.
* `Place` is re-exported in `rustc_typeck::expr_use_visitor` so that Clippy can access it.

The loss of an error in `issue-4335.rs` is due to a change in capture inference in ill-formed programs. If any projection from a variable is moved from then we capture that variable by move, whether or not the place being moved from allows this.

Closes #66270

### CODE REVIEW

File: src/librustc/middle/mem_categorization.rs [hunk 1]
```diff
@@ -184,7 +184,7 @@ pub enum Note {
 // dereference (`@T`). So use `cmt.ty` to find the type of the value in
 // a consistent fashion. For more details, see the method `cat_pattern`
 #[derive(Clone, Debug, PartialEq)]
-pub struct cmt_<'tcx> {
```
Comment (lzutao) [inline src/librustc/middle/mem_categorization.rs]: The doc comment `` `cmt`: "Category, Mutability, and Type".`` need to be changed.

Comment (lzutao) [reply src/librustc/middle/mem_categorization.rs]: Also change other comments contain `` `cmt` ``.

Comment (matthewjasper) [reply src/librustc/middle/mem_categorization.rs]: This is updated in the later commits

File: src/librustc/middle/mem_categorization.rs [hunk 2]
```diff
@@ -1115,138 +634,71 @@ impl<'a, 'tcx> MemCategorizationContext<'a, 'tcx> {
...
-                let context = InteriorOffsetKind::Pattern;
-                let elt_cmt = Rc::new(self.cat_index(pat, cmt, element_ty, context)?);
+                let elt_place = self.cat_projection(pat, place, element_ty);
                 for before_pat in before {
-                    self.cat_pattern_(elt_cmt.clone(), &before_pat, op)?;
+                    self.cat_pattern_(elt_place.clone(), &before_pat, op)?;
                 }
                 if let Some(ref slice_pat) = *slice {
-                    self.cat_pattern_(elt_cmt.clone(), &slice_pat, op)?;
+                    // FIXME the type here is wrong.
```
Comment (Centril) [inline src/librustc/middle/mem_categorization.rs]: Can you elaborate on this? Does it impact stabilizing slice_patterns in any way?

File: src/librustc/middle/mem_categorization.rs [hunk 3]
```diff
@@ -1115,138 +634,71 @@ impl<'a, 'tcx> MemCategorizationContext<'a, 'tcx> {
...
-                    }
-                };
-
-                for (i, subpat) in subpats.iter().enumerate_and_adjust(expected_len, ddpos) {
-                    let subpat_ty = self.pat_ty_adjusted(&subpat)?; // see (*2)
-                    let interior = InteriorField(FieldIndex(i, sym::integer(i)));
-                    let subcmt = Rc::new(
-                        self.cat_imm_interior(pat, cmt.clone(), subpat_ty, interior));
-                    self.cat_pattern_(subcmt, &subpat, op)?;
+            PatKind::TupleStruct(_, ref subpats, _) => {
```
Comment (Centril) [inline src/librustc/middle/mem_categorization.rs]: Same code for `PatKind::Tuple`; could merge the arms.

File: src/librustc/middle/mem_categorization.rs (hunk 2 above)
Comment (matthewjasper) [reply src/librustc/middle/mem_categorization.rs]: The type should be an array/slice type fpr slice patterns, not the element type. I've fixed this now, so no.

**Comment by JohnCSimon** [comment]
Ping from triage
@matthewjasper  - can you please address the merge conflicts?
Thank you!

File: src/librustc_typeck/check/regionck.rs [hunk 4]
```diff
@@ -899,10 +896,6 @@ impl<'a, 'tcx> RegionCtxt<'a, 'tcx> {
             }
 
             cmt = self.with_mc(|mc| mc.cat_expr_adjusted(expr, cmt, &adjustment))?;
-
-            if let Categorization::Deref(_, mc::BorrowedPtr(_, r_ptr)) = cmt.cat {
-                self.mk_subregion_due_to_dereference(expr.span, expr_region, r_ptr);
```
Comment (pnkfelix) [inline src/librustc_typeck/check/regionck.rs]: do you know what this was here for? I just want a note in this PR about why we don't need it, no need to add comments to the soruce code or anything.

File: src/librustc_typeck/check/regionck.rs [hunk 5]
```diff
@@ -1231,83 +1204,27 @@ impl<'a, 'tcx> RegionCtxt<'a, 'tcx> {
...
     ///
-    /// 2. There may in fact be more levels of reborrowing. In the
-    ///    example, I said the borrow was like `&'z *r`, but it might
-    ///    in fact be a borrow like `&'z **q` where `q` has type `&'a
-    ///    &'b mut T`. In that case, we want to ensure that `'z <= 'a`
-    ///    and `'z <= 'b`. This is explained more below.
-    ///
-    /// The return value of this function indicates whether we need to
-    /// recurse and process `ref_cmt` (see case 2 above).
+    /// This is explained more below.
```
Comment (pnkfelix) [inline src/librustc_typeck/check/regionck.rs]: What does the bool return value of this function indicate? (I initially guessed, based nothing at all, that `true` would mean we need to continue recursing. But then I looked at the call-site and decided that was incorrect.)

File: src/librustc_typeck/check/regionck.rs [hunk 6]
```diff
@@ -1231,83 +1204,27 @@ impl<'a, 'tcx> RegionCtxt<'a, 'tcx> {
     ///
     /// Here `bk` stands for some borrow-kind (e.g., `mut`, `uniq`, etc).
     ///
-    /// Unfortunately, there are some complications beyond the simple
-    /// scenario I just painted:
-    ///
-    /// 1. The reference `r` might in fact be a "by-ref" upvar. In that
```
Comment (pnkfelix) [inline src/librustc_typeck/check/regionck.rs]: You probably should transcribe this doc-comment for case (1.) into a doc comment for the currently un-doc-commented `fn link_upvar_region`.

File: src/librustc_typeck/check/regionck.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_typeck/check/regionck.rs]: (is this a case where mir-borrowck (and/or nll/type-check) is imposing the same constraint and so we do not need to impose it here?)

**Comment by pnkfelix** [comment]
This looks great! r=me once you have addressed the nits above.

File: src/librustc_typeck/check/regionck.rs (hunk 4 above)
Comment (matthewjasper) [reply src/librustc_typeck/check/regionck.rs]: That's the case for most of the constraints in this file. This check specifically is to ensure, in the language of NLL, that `'a` is live at the point marked:

```rust
let x: &'a (i32, i32) = ...;
let _ = x.0; //here
```

This is redundant because:
* There's no longer any check that makes use of ReScopes (except for the leak check, but that's hopefully going away soon).
* NLL does is own region liveness inference.
* I think that we're already adding this relation because all of the regions in the unadjusted expression are already marked live.

File: src/librustc_typeck/lib.rs [hunk 7]
```diff
@@ -83,6 +86,7 @@ mod collect;
 mod constrained_generic_params;
 mod structured_errors;
 mod impl_wf_check;
+mod mem_categorization;
```
Comment (Manishearth) [inline src/librustc_typeck/lib.rs]: Uh, this needs to be public too, Clippy can't use EUV without memcat

Comment (Manishearth) [reply src/librustc_typeck/lib.rs]: In general we should be very careful about marking existing things as private

Comment (Manishearth) [reply src/librustc_typeck/lib.rs]: Oh, I see, you want us to use Place from EUV, and Categorization isn't a thing anymore
