### PR TITLE
Don't crash on non-existent path in constant.

### LINKED ISSUE #28670: internal compiler error with a unknown value in a slice
struct with unknow value from enum in slice variable

I tried this code:

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub enum Ipc {
  CREAT = 0o0001000, // POSIX
  NOWAIT = 2048, // POSIX
}

pub struct MsgBuf {
  pub mtype: u32,
  pub mtext: [u8; Ipc::MSG_BUFF as usize], // <- The error is Ipc::MSG_BUFF, this variable not exist.
}

fn main() {
}
```
I expected to see this happen:
```shell
error: unresolved name `MSG_BUFF`
```
Instead, this happened:
```shell
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: 4 }Ipc, true), last_private: LastMod(AllPublic), depth: 1 }', ../src/librustc/middle/def.rs:80


playpen: application terminated with error code 101
```

### PR DESCRIPTION
**Pull request by eefriedman**
The behavior here isn't really ideal, but we can't really do much better
given the current state of constant evaluation.

The changes to ExprUseVisitor are to avoid a compile error; apparently
that bit of code is extremely sensitive to changes in other areas of the
compiler.

Fixes #28670, and probably a bunch of duplicates.

### CODE REVIEW

File: src/librustc/middle/const_eval.rs [hunk 1]
```diff
@@ -916,7 +916,16 @@ pub fn eval_const_expr_partial<'tcx>(tcx: &ty::ctxt<'tcx>,
         }
       }
       hir::ExprPath(..) => {
-          let opt_def = tcx.def_map.borrow().get(&e.id).map(|d| d.full_def());
+          let opt_def = if let Some(def) = tcx.def_map.borrow().get(&e.id) {
+              // FIXME: There's probably a better way to make sure we don't
+              // panic here.
+              if def.depth != 0 {
+                  signal!(e, NonConstPath);
```
Comment (oli-obk) [inline src/librustc/middle/const_eval.rs]: You could extend the error enum to have a specific variant for this situation, as `NonConstPath` signifies a valid but not constant path imo

**Comment by eefriedman** [comment]
Updated with a new error kind and better comments.
