### PR TITLE
Let CTFE to handle partially uninitialized unions without marking the entire value as uninitialized.

### LINKED ISSUE #69488: const-eval: load of partially initialized scalar produces entirely uninitialized result
The constant evaluation of a move of a union differs from the semantics of non-constant evaluation. The union instance is not regarded as a bag-of-bits as aluded to in the reference and also [this `unsafe-code-guidelines` issue](https://github.com/rust-lang/unsafe-code-guidelines/issues/73#issue-397775312). This occurs only if the unions has a single scalar *scalar* field and otherwise ZSTs, which is pretty specific but occurs for `MaybeUninit` if the type parameter is a scalar. If the field is of other types such as arrays (`[scalar; N]`) *or* if the other field is not a ZST then the semantics seem fine.

I tried this code:

```rust
#![feature(const_if_match)] // Only related to make_1u8_bag, all of them set by Miri
#![feature(const_fn)]
#![feature(const_mut_refs)]
#![feature(const_panic)]
#![feature(const_raw_ptr_deref)]

// Or, equivalently: `MaybeUninit`.
pub union BagOfBits<T: Copy> {
    uninit: (),
    _storage: T,
}

pub const fn make_1u8_bag<T: Copy>() -> BagOfBits<T> {
    assert!(core::mem::size_of::<T>() >= 1);
    let mut bag = BagOfBits { uninit: () };
    unsafe { (&mut bag as *mut _ as *mut u8).write(1); };
    bag
}

pub fn check_bag<T: Copy>(bag: &BagOfBits<T>) {
    let val = unsafe { (bag as *const _ as *const u8).read() };
    assert_eq!(val, 1);
}

fn main() {
    check_bag(&make_1u8_bag::<[usize; 1]>()); // Fine
    check_bag(&make_1u8_bag::<usize>()); // Fine

    const CONST_ARRAY_BAG: BagOfBits<[usize; 1]> = make_1u8_bag();
    check_bag(&CONST_ARRAY_BAG); // Fine.
    const CONST_USIZE_BAG: BagOfBits<usize> = make_1u8_bag();
    check_bag(&CONST_USIZE_BAG); // Panics
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=deecbf5c59706a37f7db16ea5f3ed30b)

I expected to see this happen: All assertions succeed.

Instead, this happened: The check where a union of type `BagOfBits<usize>` is *moved during constant evaluation*, panics. When putting everything through Miri it panics with the message of trying to read an uninitialized byte. The check where the union of type `BagOfBits<[usize; 1]>` is used instead runs fine in both cases.

```text
error: Miri evaluation error: attempted to read undefined bytes
  --> src/main.rs:21:5
   |
21 |     assert_eq!(val, 1);
   |     ^^^^^^^^^^^^^^^^^^^ attempted to read undefined bytes
```

As far as I am aware, when constant evaluation reads *scalars* then it propagates uninitialized bytes. If that were to happen then it would explain the observed behaviour but it seems weird why the union copy would use a scalar read.

cc @RalfJung

### LINKED ISSUE #94371: mem::swap behaves incorrectly in CTFE (and Miri)
Since https://github.com/rust-lang/rust/pull/94212, `mem::swap` behaves incorrectly during CTFE (where it is unstably accessible) and in Miri. This is demonstrated by the following code failing to build:
```rust
#![feature(const_swap)]
#![feature(const_mut_refs)]

use std::borrow::Cow;

pub enum NamePadding {
    PadNone,
    PadOnRight,
}

pub enum TestName {
    StaticTestName(&'static str),
    DynTestName(String),
    AlignedTestName(Cow<'static, str>, NamePadding),
}

pub enum ShouldPanic {
    No,
    Yes,
    YesWithMessage(&'static str),
}

pub enum TestType {
    UnitTest,
    IntegrationTest,
    DocTest,
    Unknown,
}

pub struct TestDesc {
    pub name: TestName,
    pub ignore: bool,
    pub should_panic: ShouldPanic,
    pub compile_fail: bool,
    pub no_run: bool,
    pub test_type: TestType,
}

pub struct Bencher;

pub enum TestFn {
    StaticTestFn(fn()),
    StaticBenchFn(fn(&mut Bencher)),
    DynTestFn(Box<dyn FnOnce() + Send>),
    DynBenchFn(Box<dyn Fn(&mut Bencher) + Send>),
}

pub struct TestDescAndFn {
    pub desc: TestDesc,
    pub testfn: TestFn,
}

pub struct TestId(pub usize);

type T = (TestId, TestDescAndFn);

const C: (T, T) = {
    let mut x = (
        TestId(0),
        TestDescAndFn {
            desc: TestDesc {
                name: TestName::StaticTestName("name"),
                ignore: true,
                should_panic: ShouldPanic::Yes,
                compile_fail: false,
                no_run: false,
                test_type: TestType::UnitTest,
            },
            testfn: TestFn::StaticTestFn(|| {}),
        },
    );
    let mut y = (
        TestId(0),
        TestDescAndFn {
            desc: TestDesc {
                name: TestName::StaticTestName("name"),
                ignore: true,
                should_panic: ShouldPanic::Yes,
                compile_fail: false,
                no_run: false,
                test_type: TestType::UnitTest,
            },
            testfn: TestFn::StaticTestFn(|| {}),
        },
    );
    std::mem::swap(&mut x, &mut y);
    (x, y)
};

fn main() {}
```
The error is:
```
error[E0080]: it is undefined behavior to use this value
  --> swap2.rs:57:1
   |
57 | / const C: (T, T) = {
58 | |   let mut x = (
59 | |             TestId(0),
60 | |             TestDescAndFn {
...  |
87 | |   (x, y)
88 | | };
   | |__^ type validation failed at .1.1.desc.name.<enum-tag>: encountered uninitialized bytes, but expected initialized plain (non-pointer) bytes
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
   = note: the raw bytes of the constant (size: 208, align: 8) {
               0x00 │ 00 00 00 00 00 00 00 00 00 __ __ __ __ __ __ __ │ .........░░░░░░░
               0x10 │ ╾───────alloc14───────╼ 04 00 00 00 00 00 00 00 │ ╾──────╼........
               0x20 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
               0x30 │ 01 00 00 00 00 00 00 00 __ __ __ __ __ __ __ __ │ ........░░░░░░░░
               0x40 │ __ __ __ __ __ __ __ __ 01 00 00 00 __ __ __ __ │ ░░░░░░░░....░░░░
               0x50 │ 00 00 00 00 00 00 00 00 ╾───────alloc18───────╼ │ ........╾──────╼
               0x60 │ __ __ __ __ __ __ __ __ 00 00 00 00 00 00 00 00 │ ░░░░░░░░........
               0x70 │ __ __ __ __ __ __ __ __ ╾───────alloc4────────╼ │ ░░░░░░░░╾──────╼
               0x80 │ 04 00 00 00 00 00 00 00 __ __ __ __ __ __ __ __ │ ........░░░░░░░░
               0x90 │ __ __ __ __ __ __ __ __ 01 00 00 00 00 00 00 00 │ ░░░░░░░░........
               0xa0 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
               0xb0 │ __ __ __ __ __ __ __ __ 00 00 00 00 00 00 00 00 │ ░░░░░░░░........
               0xc0 │ ╾───────alloc8────────╼ __ __ __ __ __ __ __ __ │ ╾──────╼░░░░░░░░
           }
```

The underlying reason for this is https://github.com/rust-lang/rust/issues/69488: the new `swap` copies the data in chunks of `MaybeUninit<usize>`, but this is implemented incorrectly in CTFE and Miri in the sense that if *any* of the bytes in the source of such a value is uninit, then the *entire value* becomes uninit after the copy.

This reproduces only with very particular types that hit certain code paths in `swap`; my attempts at writing a smaller example from scratch failed so instead I extracted this from the test harness where the problem originally occurred in Miri.

Also, even a fix https://github.com/rust-lang/rust/issues/69488 would not fully resolve the problem: if data contains pointers at *unaligned* positions, then the `usize` chunking might attempt to copy a *part* of a pointer, which CTFE and Miri do not support (that's https://github.com/rust-lang/rust/issues/87184, and it is a lot harder to fix than https://github.com/rust-lang/rust/issues/69488). This was in theory already a problem with the previous implementation of `swap`, but there the chunks were bigger so pointers were less likely to cross the chunk boundary. I don't know if this is ever a problem in practice though. Miri/CTFE will halt when such a partial pointer copy is attempted, so we should know if/when that happens.

### PR DESCRIPTION
**Pull request by oli-obk**
follow up to #94411

To fix https://github.com/rust-lang/rust/issues/69488 and by extension fix https://github.com/rust-lang/rust/issues/94371, we should stop treating types like `MaybeUninit<usize>` as something that the `Scalar` type in the interpreter engine can represent. So we add a new field to `abi::Primitive` that records whether the primitive is nested in a union

cc @RalfJung 

r? @ghost

### CODE REVIEW

File: compiler/rustc_target/src/abi/call/sparc64.rs [hunk 1]
```diff
@@ -79,17 +79,15 @@ where
     C: HasDataLayout,
 {
     data = arg_scalar(cx, &scalar1, offset, data);
-    if scalar1.value == abi::F32 {
-        offset += Reg::f32().size;
-    } else if scalar2.value == abi::F64 {
```
Comment (falaosu) [inline compiler/rustc_target/src/abi/call/sparc64.rs:84]: ?

Comment (oli-obk) [reply compiler/rustc_target/src/abi/call/sparc64.rs:84]: That was a whole if/else collection that could just as well have been a match

Comment (oli-obk) [reply compiler/rustc_target/src/abi/call/sparc64.rs:84]: Ah no

Comment (oli-obk) [reply compiler/rustc_target/src/abi/call/sparc64.rs:84]: Should've paid more attention, thanks! That's the bug I introduced

File: compiler/rustc_middle/src/ty/layout.rs [hunk 2]
```diff
@@ -877,12 +882,13 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
                         if optimize && !field.is_zst() {
                             // Normalize scalar_unit to the maximal valid range
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/layout.rs:883]:
```suggestion
                            // Normalize scalar_unit to the maximal valid range and allow undef
```

File: src/test/ui/layout/debug.stderr [hunk 3]
```diff
@@ -13,7 +13,9 @@ error: layout_of(E) = Layout {
                tag: Scalar {
                    value: Int(
                        I32,
-                       false,
+                       IntFlags(
+                           0,
+                       ),
```
Comment (RalfJung) [inline src/test/ui/layout/debug.stderr:18]: Looks like the debug rendering of these flags is not very useful?

**Comment by RalfJung** [comment]
Bors didn't seem to react?
@bors try

**Comment by RalfJung** [comment]
So from what I can tell this is entirely unconnected to the logic in https://github.com/rust-lang/rust/pull/93670? We might not want to emit `noundef` *everywhere* quite yet as this PR would, but not relating these two at all also seems odd.

**Comment by oli-obk** [comment]
First I want to see if it is feasible to go this route, then we can talk to the llvm people. I do believe we should be able to use it at some point, but it may very well be badly handled by llvm for now.

The linked PR works on types, where this PR encodes the information in the layout. So there may be unintended consequences. For now we should probably only use it in miri.

Maybe we should also flip the logic of the Boolean and search for a better name (`!noundef` checks are the worst, triple negation)

**Comment by RalfJung** [comment]
> Speaking of--I think it would make more sense for undef to be part of valid_range rather than Primitive as it is in this PR.

Agreed, I was thinking the same -- but that could be tricky to do without increasing the size of `abi::Scalar`.

**Comment by oli-obk** [comment]
I originally wanted to do the ValidRange thing, but yea, that doesn't work without increasing the size. We could make `Scalar` an enum over `Undef(Primitive), Def(Primitive, WrappingRange)`, i'll experiment if I can make that work

**Comment by oli-obk** [comment]
I force-pushed as the previous code and the new code have nothing to do with each other.

While this change required a bit more changes than the previous one, it is also much clearer imo.

@bors try @rust-timer queue

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 4]
```diff
@@ -119,7 +119,7 @@ pub(super) fn op_to_const<'tcx>(
     // the usual cases of extracting e.g. a `usize`, without there being a real use case for the
     // `Undef` situation.
     let try_as_immediate = match op.layout.abi {
-        Abi::Scalar(..) => true,
+        Abi::Scalar(abi::Scalar::Primitive { .. }) => true,
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:122]: In particular `scalar.primitive()` always works (even for unions), which muddles the idea that "Primitive implies noundef".

File: compiler/rustc_target/src/abi/mod.rs [hunk 5]
```diff
@@ -807,28 +811,85 @@ impl fmt::Debug for WrappingRange {
...
+            Scalar::Primitive {
+                value: Int(I8, false),
+                valid_range: WrappingRange { start: 0, end: 1 }
+            }
         )
     }
 
+    #[inline]
+    pub fn is_float(&self) -> bool {
+        matches!(self, Scalar::Primitive { value: F32 | F64, .. })
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_target/src/abi/mod.rs:845]: Oops

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:122]: I initially added the `primitive` function to make transitioning easier and change no codegen behaviour for now. I do wonder whether unions should have a primitive layout beyond size and align requirements.

Wrt naming, I didn't want to have a `NoUndef` variant due to the double negative, but... it may be the clearest due to people knowing what it means

[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:122]: I think we need the `Primitive` since we want to generate the appropriate LLVM type, and it might affect the call ABI.

> Wrt naming, I didn't want to have a NoUndef variant due to the double negative, but... it may be the clearest due to people knowing what it means

It could also be `InitializedPrimitive` or so. (IMO we should not use "undef" at all, and rather use "uninit", as that is the term we usually use in Rust.)

[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs]: Or just `Initialized`, I like it. :)

**Review by erikdesjardins — COMMENTED** [review]
r=me with nits fixed

(I assume you already realize this, but I feel obliged to mention that I'm not an "official" reviewer, if that matters for procedural reasons)

**Comment by oli-obk** [comment]
r? rust-lang/compiler

File: src/test/mir-opt/const_prop/invalid_constant.main.ConstProp.diff [hunk 6]
```diff
@@ -24,29 +24,19 @@
...
+                                           // + literal: Const { ty: InvalidChar, val: Unevaluated(main::{constant#0}, [main::InvalidChar], None) }
           StorageLive(_2);                 // scope 1 at $DIR/invalid_constant.rs:28:9: 28:21
           StorageLive(_3);                 // scope 1 at $DIR/invalid_constant.rs:28:25: 28:46
           (_3.0: u32) = const 4_u32;       // scope 1 at $DIR/invalid_constant.rs:28:25: 28:46
--         _2 = [move _3];                  // scope 1 at $DIR/invalid_constant.rs:28:24: 28:47
-+         _2 = [const InvalidTag { int: 4_u32, e: Scalar(0x00000004): E }]; // scope 1 at $DIR/invalid_constant.rs:28:24: 28:47
-+                                          // mir::Constant
-+                                          // + span: $DIR/invalid_constant.rs:28:24: 28:47
-+                                          // + literal: Const { ty: InvalidTag, val: Value(Scalar(0x00000004)) }
+          _2 = [move _3];                  // scope 1 at $DIR/invalid_constant.rs:28:24: 28:47
```
Comment (tmiasko) [inline src/test/mir-opt/const_prop/invalid_constant.main.ConstProp.diff:34]: This was testing pretty printing of invalid constants, but it looks like those are not evaluated any more. Is this intentional?

Could you update tests if possible? If not, there is probably little reason to keep those tests at all.

File: compiler/rustc_target/src/abi/mod.rs [hunk 7]
```diff
@@ -1334,7 +1394,7 @@ impl<'a, Ty> TyAndLayout<'a, Ty> {
         C: HasDataLayout,
     {
         match self.abi {
-            Abi::Scalar(scalar) => scalar.value.is_float(),
+            Abi::Scalar(scalar) => matches!(scalar.primitive(), F32 | F64),
```
Comment (nagisa) [inline compiler/rustc_target/src/abi/mod.rs:1397]: Nit: might as well add `is_float_primitive` to the `Scalar`. Seen this pattern a couple times already.

File: compiler/rustc_middle/src/ty/layout.rs [hunk 8]
```diff
@@ -567,7 +567,10 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
         let scalar_unit = |value: Primitive| {
             let size = value.size(dl);
             assert!(size.bits() <= 128);
-            Scalar { value, valid_range: WrappingRange { start: 0, end: size.unsigned_int_max() } }
+            Scalar::Initialized {
+                value,
+                valid_range: WrappingRange { start: 0, end: size.unsigned_int_max() },
```
Comment (nagisa) [inline compiler/rustc_middle/src/ty/layout.rs:572]: `WrappingRange::full`.

File: compiler/rustc_middle/src/ty/layout.rs [hunk 9]
```diff
@@ -889,14 +895,14 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
 
                         // If all non-ZST fields have the same ABI, forward this ABI
                         if optimize && !field.is_zst() {
-                            // Normalize scalar_unit to the maximal valid range
+                            // Normalize scalar_unit to the maximal valid range and allow undef
```
Comment (nagisa) [inline compiler/rustc_middle/src/ty/layout.rs:898]: Now that `Scalar::Union` doesn't carry valid range information at all, the original portion of this comment seems kinda bogus. Maybe:

> Discard valid range information and allow undef

File: compiler/rustc_codegen_llvm/src/consts.rs [hunk 10]
```diff
@@ -109,7 +109,10 @@ pub fn const_alloc_to_llvm<'ll>(cx: &CodegenCx<'ll, '_>, alloc: ConstAllocation<
                 Pointer::new(alloc_id, Size::from_bytes(ptr_offset)),
                 &cx.tcx,
             ),
-            Scalar { value: Primitive::Pointer, valid_range: WrappingRange { start: 0, end: !0 } },
+            Scalar::Initialized {
+                value: Primitive::Pointer,
+                valid_range: WrappingRange { start: 0, end: !0 },
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/consts.rs:114]: Would `WrappingRange::full` be applicable here? Also same in `rustc_codegen_gcc::consts` too.

**Review by nagisa — COMMENTED** [review]
Did the “official” review ^^

`r=me,erikdesjardin`, sans nits and pending squash of the “fix tests” commit.
