### PR TITLE
Fix failure note `to_str` implementation

### LINKED ISSUE #60425: FailureNote JSON value is not useful
Currently the `FailureNote` diagnostic level [serializes to the empty string](https://github.com/rust-lang/rust/blob/5b7baa53c91d7c33b925fc8aec553e3521548a07/src/librustc_errors/lib.rs#L837).  This results in JSON messages containing `level: ""`, which I'm not sure how to interpret.  

This was added in #48684, though reading that PR I can't really figure out why it was added and how it relates to compiletest changes.

An easy way to see this is to trigger a diagnostic that prints "For more information…", for example:

```rust
// E0005
let Some(_y) = Some(1);
```

will emit a JSON value like this:

```json
{
  "message": "For more information about this error, try `rustc --explain E0005`.",
  "code": null,
  "level": "",
  "spans": [],
  "children": [],
  "rendered": "For more information about this error, try `rustc --explain E0005`.\n"
}
```

The empty string is not very descriptive of how to handle the message.  I would suggest having it serialize to something more deliberate, such as "failure-note".  I can't really tell what the intent of `FailureNote` is, so it's hard to say what it should be.  

cc @GuillaumeGomez who might know more.

### PR DESCRIPTION
**Pull request by afnanenayet**
Serialize the level to something a little more useful for a failure note struct. This fixes #60425.

### CODE REVIEW

**Comment by afnanenayet** [comment]
I looked at the log output for the failing CI build...seems like a lot of errors that aren't related to my change, but I could be wrong. Does this normally happen?

**Comment by Mark-Simulacrum** [comment]
That's unexpected, but related to this change. We'll need to dig in why; I'll try to spend some time today on that.

**Comment by Mark-Simulacrum** [comment]
Oh, I see what's happening. The "For more information about this error" piece is being emitted as a failure note https://github.com/rust-lang/rust/blob/3287a65fc05028dce3b521765f4643384ebc4346/src/librustc_errors/lib.rs#L692-L701

I think adjusting the code [here](https://github.com/rust-lang/rust/blob/cf17e3387833473745d724312ba54bd4ceb81672/src/librustc_errors/emitter.rs#L1140-L1170) to not print the level_str if the level is FailureNote would work to fix CI here.

**Comment by afnanenayet** [comment]
@Mark-Simulacrum how can I re-run the CI? I saw the issue that references the build error that just happened for this PR

File: src/librustc_errors/emitter.rs [hunk 1]
```diff
@@ -1144,24 +1144,27 @@ impl EmitterWriter {
...
+                }
             }
             self.msg_to_buffer(&mut buffer, msg, max_line_num_len, "note", None);
         } else {
             let level_str = level.to_string();
-            if !level_str.is_empty() {
-                buffer.append(0, &level_str, Style::Level(level.clone()));
+            // The failure note level itself does not provide any useful diagnostic information
+            if *level != Level::FailureNote && !level_str.is_empty() {
+                    buffer.append(0, &level_str, Style::Level(level.clone()));
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/emitter.rs]: indentation is off by one here

**Review by Mark-Simulacrum — APPROVED** [review]
r=me with nit fixed

**Comment by Mark-Simulacrum** [comment]
Ah, and we'll also want to squash the commits into just one. Thanks!

**Comment by afnanenayet** [comment]
Awesome, I'll fix this up after work. Thanks so much for helping me out with this!

**Comment by Mark-Simulacrum** [comment]
Thanks!

@bors r+ rollup
