### PR TITLE
Give a better error when rustdoc tests fail

### LINKED ISSUE #78750: Add color diffs to htmldocck.py
Currently, test failures look like this:

```
---- [rustdoc] rustdoc/where.rs stdout ----

error: htmldocck failed!
status: exit code: 1
command: "/usr/bin/python" "/home/joshua/rustc/src/etc/htmldocck.py" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/where" "/home/joshua/rustc/src/test/rustdoc/where.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
7: @has check failed
	`XPATH PATTERN` did not match
	// @has foo/trait.Bravo.html '//pre' "pub trait Bravo<B> where B: MyTrait"

Encountered 1 errors
```

This tells you what test went wrong, but not where. Why didn't the pattern match? No idea.

Instead, htmldocck could tell you exactly what went wrong:

diff

I hacked this together with some scripts, I'll see about turning it into something maintainable. Giant thank you to @Nemo157 for the help!

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/77820#issuecomment-721974515_

### PR DESCRIPTION
**Pull request by jyn514**
- Run the default rustdoc against the current rustdoc
- Diff output recursively
- Colorize diff output

Closes https://github.com/rust-lang/rust/issues/78750.

## Resolved questions

- Should this be opt-in instead of on by default?
  + No
- Should this call through to `delta`? That's not a very common program to have installed, but I'm not sure how to do diffs after the fact. Maybe `compiletest` can take a `--syntax-highlighter` parameter or something?
  + I decided to use `delta` if available and `diff --color` otherwise. It prints a warning if delta isn't installed so you know you can get nicer diffs

## Open questions.

- What version of rustdoc would this compare against? Ideally it would compare against `$(git merge-base HEAD origin/master)` - maybe that's feasible if we install those artifacts from CI?
- Does it always make sense to compare the tests? Especially for new tests, I'm not sure how useful it would be ... but then again, one of the questions I want to know most as a reviewer is 'did it break before?'.

r? @GuillaumeGomez 
cc @Mark-Simulacrum

### CODE REVIEW

**Comment by jyn514** [comment]
Example output: diff2

**Comment by jyn514** [comment]
Oh another thing - this compares the output eagerly, as the tests are still running. Maybe it would be better to wait until the end?

**Comment by jyn514** [comment]
And it doesn't work for `aux-build` either :/
```
info: generating a diff against nightly rustdoc

error: failed to run nightly rustdoc
status: exit code: 1
command: "rustdoc" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-20646/auxiliary" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-20646.nightly" "/home/joshua/rustc/src/test/rustdoc/issue-20646.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0514]: found crate `issue_20646` compiled by an incompatible version of rustc
 --> /home/joshua/rustc/src/test/rustdoc/issue-20646.rs:6:1
  |
6 | extern crate issue_20646;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24))
  = note: the following crate versions were found:
          crate `issue_20646` compiled by rustc 1.49.0-dev: /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-20646/auxiliary/libissue_20646.so

error: aborting due to previous error
``

File: src/tools/compiletest/tidy-rustdoc.sh [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        >/dev/null \
+    || {
+      # tidy exits with code 1 if there were any warnings :facepalm:
+      status=$?
+      if [ $status != 0 ] && [ $status != 1 ]
+      then
+        echo "While tidying $1" >&2
+        exit 1
+      fi
+    }
```
Comment (pickfire) [inline src/tools/compiletest/tidy-rustdoc.sh:30]:
```suggestion
    || test $? -eq 1 \
    || { # ^ tidy exits with code 1 if there were any warnings, ignore it 🤦
      echo "While tidying $1" >&2
      exit 1
    }
```

I don't think we need to check `0` if it is on the `||` branch since `0` already indicates success.

Heh, and a real facepalm.

File: src/tools/compiletest/src/runtest.rs [hunk 2]
```diff
@@ -2325,15 +2331,72 @@ impl<'test> TestCx<'test> {
...
         }
     }
 
+    fn compare_to_default_rustdoc(&mut self, out_dir: &Path) {
+        println!("info: generating a diff against nightly rustdoc");
+
+        let suffix =
+            self.safe_revision().map_or("nightly".into(), |path| path.to_owned() + "-nightly");
+        let compare_dir = output_base_dir(self.config, self.testpaths, Some(&suffix));
+        let _ = fs::remove_dir_all(&compare_dir);
```
Comment (pickfire) [inline src/tools/compiletest/src/runtest.rs:2351]: What if this failed to remove directory even if it existed?

File: src/tools/compiletest/src/runtest.rs [hunk 3]
```diff
@@ -2325,15 +2331,72 @@ impl<'test> TestCx<'test> {
...
+        let tidy = concat!(env!("CARGO_MANIFEST_DIR"), "/tidy-rustdoc.sh");
+        // FIXME: this overwrites `out_dir` in place, maybe we should make a copy?
+        let status = Command::new(tidy)
+            .arg(out_dir)
+            .spawn()
+            .expect("tidy-rustdoc not found")
+            .wait()
+            .unwrap();
+        if !status.success() {
+            self.fatal("failed to run tidy - is installed?");
```
Comment (pickfire) [inline src/tools/compiletest/src/runtest.rs:2379]:
```suggestion
            self.fatal("failed to run tidy - is it installed?");
```

File: src/tools/compiletest/src/runtest.rs [hunk 4]
```diff
@@ -3590,7 +3653,7 @@ pub struct ProcRes {
 }
 
 impl ProcRes {
-    pub fn fatal(&self, err: Option<&str>) -> ! {
+    pub fn fatal(&self, err: Option<&str>, ctx: impl FnOnce()) -> ! {
```
Comment (pickfire) [inline src/tools/compiletest/src/runtest.rs:3656]: Isn't this some sort of callback on failure? It may not be so obvious `ctx` means that, I also didn't know `ctx` is a function.

File: src/tools/compiletest/src/runtest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/tools/compiletest/src/runtest.rs:2351]: A `expect` would be appreciated I guess. :)

File: src/tools/compiletest/tidy-rustdoc.sh [hunk 5]
```diff
@@ -0,0 +1,38 @@
+#!/usr/bin/env bash
```
Comment (GuillaumeGomez) [inline src/tools/compiletest/tidy-rustdoc.sh:1]: Won't this an issue to have a bash script on windows? Wouldn't a python or a rust one be better?

File: src/tools/compiletest/tidy-rustdoc.sh [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+    || {
+      # tidy exits with code 1 if there were any warnings :facepalm:
+      status=$?
+      if [ $status != 0 ] && [ $status != 1 ]
+      then
+        echo "While tidying $1" >&2
+        exit 1
+      fi
+    }
+  } | sed -E 's/#[0-9]+(-[0-9]+)?/#line/g'
```
Comment (Nemo157) [inline src/tools/compiletest/tidy-rustdoc.sh:31]: You don't need the line-number removal for this usecase, I needed it to be able to compare modified `std` without a bunch of noise from line numbers.

File: src/tools/compiletest/tidy-rustdoc.sh [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+    #   https://github.com/rust-lang/stdarch/issues/945
+    #   https://github.com/rust-lang/mdBook/issues/1372
+    command tidy \
+        --indent yes \
+        --indent-spaces 2 \
+        --wrap 0 \
+        --show-warnings no \
+        --markup yes \
+        --quiet yes \
+        --new-inline-tags 'c t' \
```
Comment (Nemo157) [inline src/tools/compiletest/tidy-rustdoc.sh:19]: Probably don't need these (and the comment) since you're not checking the book and `stdarch` docs.

File: src/tools/compiletest/src/runtest.rs (hunk 2 above)
Comment (jyn514) [reply src/tools/compiletest/src/runtest.rs:2351]: This is to match the previous behavior in `run_rustdoc_test`: https://github.com/rust-lang/rust/blob/5b1bd121f3e491548fe9c92a615a588328b9c3e0/src/tools/compiletest/src/runtest.rs#L685

I think this will give an error if `compare_dir` didn't already exist, so I don't think panicking on error is the right thing to do.

File: src/tools/compiletest/tidy-rustdoc.sh (hunk 5 above)
Comment (jyn514) [reply src/tools/compiletest/tidy-rustdoc.sh:1]: I guess so, but doing this IO in python is super annoying. I'll rewrite it after everything else is working.

**Comment by jyn514** [comment]
> Oh another thing - this compares the output eagerly, as the tests are still running. Maybe it would be better to wait until the end?

It turns out there's no way to do this, since all the tests are boxed and have no way to return anything. I don't think the giant refactor would be worth it, I made delta non-interactive instead (no pager).

File: src/tools/compiletest/src/runtest.rs [hunk 8]
```diff
@@ -2208,7 +2209,17 @@ impl<'test> TestCx<'test> {
 
     fn fatal_proc_rec(&self, err: &str, proc_res: &ProcRes) -> ! {
         self.error(err);
-        proc_res.fatal(None);
+        proc_res.fatal(None, || ());
+    }
+
+    fn fatal_proc_rec_with_ctx(
```
Comment (pickfire) [inline src/tools/compiletest/src/runtest.rs:2215]: Do we even need this as a function, I believe we could just inline this right since it is only used in one place?

Comment (jyn514) [reply src/tools/compiletest/src/runtest.rs:2215]: If this is inline, it's really annoying to work with:

- you have to use `this` instead of `self` to avoid borrowck errors
- all the code is indented like 4 levels

**Comment by pickfire** [comment]
> Should this call through to delta? That's not a very common program to have installed, but I'm not sure how to do diffs after the fact. Maybe compiletest can take a --syntax-highlighter parameter or something?

Way not take the options from `git`? Or just do `git diff`?

**Comment by jyn514** [comment]
> Way not take the options from git? Or just do git diff?

Git diff doesn't help because these files aren't tracked by git, they're created by rustdoc. Instead I fell back to `diff --color` if `delta` wasn't installed.

> Feels like a git bisect question? Maybe we need to allow users to do a bisect? Not sure, I never did one for rust due to compilation time.

Right, yeah I don't think it makes any sense to use bisect since it takes so long to compile things. The other rustdoc has to be pre-compiled from somewhere.

Another thing I found is that if you compare to beta rustdoc the diff is very noisy, because there are unrelated changes to the files in the meantime. Maybe I should only compare HTML files and not JS? Here's an example of what I mean:

<details>

```
comparing: /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/wrapping/theme.js ⟶   /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc/wrapping.nightly/theme.js
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
var themes=document.getElementById("theme-choices");var themePicker=document.getElementById("theme-picker");function showThemeButtonState(){themes.style.display="block";themePicker.style.borderBottomRightRadius="0";themePicker.style.borderBottomLeftRadius="0"}function hideThemeButtonState(){themes.style.display="none";themePicker.style.borderBottomRightRadius="3px";themePicker.style.borderBottomLeftRadius="3px"}function switchThemeButtonState(){if(themes.style.display==="block"){hideThemeButtonState()}els→
\ No newline at end of file
var themes=document.getElementById("theme-choices");var themePicker=document.getElementById("theme-picker");function showThemeButtonState(){themes.style.display="block";themePicker.style.borderBottomRightRadius="0";themePicker.style.borderBottomLeftRadius="0"}function hideThemeButtonState(){themes.style.display="none";themePicker.style.borderBottomRightRadius="3px";themePicker.style.borderBottomLeftRadius="3px"}function switchThemeButtonState(){if(themes.style.display==="block"){hideThemeButtonState()}els→
\ No newline at end of file
```

</details>

**Comment by jyn514** [comment]
> Oh another thing - this compares the output eagerly, as the tests are still running. Maybe it would be better to wait until the end?

Fixed in https://github.com/rust-lang/rust/pull/78752/commits/9c160eda6fb63eafa6a00a2b061b07547dfd959e.

**Comment by jyn514** [comment]
Ok, I think this is ready for review.

**Comment by pickfire** [comment]
> Git diff doesn't help because these files aren't tracked by git, they're created by rustdoc. Instead I fell back to diff --color if delta wasn't installed.

No, I wasn't saying if the files are tracked by git. I am just saying to use `git diff`, it could be used as a normal diff.

Screenshot_20201108_100728

**Comment by jyn514** [comment]
That doesn't look like any `git diff` I've ever seen.

```
$ echo test > f
$ echo test 1 | git diff f -
fatal: option '-' must come before non-option arguments
$ git diff f <(echo test 1)
diff --git a/f b/f
deleted file mode 100644
index 9daeafb9864..00000000000
--- a/f
+++ /dev/null
@@ -1 +0,0 @@
-test
diff --git a/dev/fd/63 b/dev/fd/63
new file mode 120000
index 00000000000..0b022da6c30
--- /dev/null
+++ b/dev/fd/63
@@ -0,0 +1 @@
+pipe:[2557594]
\ No newline at end of file
$ echo test 1 > g
$ git diff f g
$ cat f
test
$ cat g
test 1
```

File: src/tools/compiletest/src/runtest.rs (hunk 2 above)
Comment (pickfire) [reply src/tools/compiletest/src/runtest.rs:2361]: Should we keep a comment to explain why it doesn't handle error?

**Comment by GuillaumeGomez** [comment]
> Should this be opt-in instead of on by default?

Is there any reason it shouldn't? Personally I think we should so that if there is any issue, we'll know right away.

> Should this call through to `delta`? That's not a very common program to have installed, but I'm not sure how to do diffs after the fact. Maybe `compiletest` can take a `--syntax-highlighter` parameter or something?

I didn't even know about it. I think we should avoid relying on external tools if possible (or only provide it through an option).

> I decided to use `delta` if available and `diff --color` otherwise. It prints a warning if delta isn't installed so you know you can get nicer diffs.

:+1: 

> Does it always make sense to compare the tests? Especially for new tests, I'm not sure how useful it would be ... but then again, one of the questions I want to know most as a reviewer is 'did it break before?'.

Tests are mostly to prevent regressions. So unless there is one, I'm not sure if it'd useful... I'm waiting for others' opinion there too. :)

**Comment by Nemo157** [comment]
> That doesn't look like any `git diff` I've ever seen.

That's what it looks like with `core.pager = delta` configured (and the theming of such that @pickfire uses), seems like a pretty good way to implicitly detect any improved CLI diff viewer the user might use.

**Comment by jyn514** [comment]
How could I tell that the pager supported running with the same arguments as `diff`? That seems really fragile - if you set your pager to `bat` or something, it would break.

**Comment by pickfire** [comment]
> How could I tell that the pager supported running with the same arguments as diff? That seems really fragile - if you set your pager to bat or something, it would break.

I don't think that is the case. Maybe you can try breaking the behavior and show a case where it will break?

```
> echo test 1 | git diff f -
───────┬────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────
   1   │ diff --git a/f b/-
   2   │ index 9daeafb..0000000 100644
   3   │ --- a/f
   4   │ +++ b/-
   5   │ @@ -1 +1 @@
   6   │ -test
   7   │ +test 1
───────┴────────────────────────────────────────────────────────────────────────
```

**Comment by jyn514** [comment]
@pickfire I still can't replicate your output.

```
$ cat y.rs | GIT_PAGER=bat git diff x.rs -
fatal: option '-' must come before non-option arguments
```

**Comment by pickfire** [comment]
@jyn514 I was using `core.pager` in `~/.config/git/config`, I didn't know `GIT_PAGER` is an environment.

**Comment by jyn514** [comment]
@pickfire I _still_ can't replicate your output.

```
(-bash@build-server) ~/rustc ▶️ cat y.rs | GIT_PAGER=bat git diff x.rs -
fatal: option '-' must come before non-option arguments
(-bash@build-server) ~/rustc ▶️ git config --get core.pager
bat
```

I don't think this is worth switching to if it's so hard to configure.

**Comment by Nemo157** [comment]
Actually, my git doesn't like `-` as an argument either, but that's probably down to `git`, not the pager, it works fine using files

image

**Comment by jyn514** [comment]
@Nemo157 Is `--paging never` consistent across wrappers? I'm really hesistant to send CLI arguments when I don't know which program I'm running, and `PAGER=` isn't consistently respected.

**Comment by pickfire** [comment]
Weird, is it because we are using different git versions?
```
> git --version
git version 2.29.2
```
But git is the good way to know if someone is using `delta` as their pager. Maybe we could parse some environment variables or check `git config -l` for that but I don't think we should implicitly choose the pager for the users. What if the users have `delta` installed but they don't want to use `delta` such that they already removed it from the application? At the same time, we probably do not want to provide a default for this, since some users may prefer `delta` over plain `diff`.

So two solutions that I can think of, either we parse git configuration which delta will be defined or we default to `git diff` (weird that only I got it working). I wonder if there are any other solutions?

**Comment by jyn514** [comment]
Is it ok if we leave the GIT_PAGER improvements for a later PR? The fix to https://github.com/dandavison/delta/issues/386 hasn't been published yet.

**Comment by Nemo157** [comment]
Yeah, thinking about it more trying to use `git diff`'s pager for this when you don't want paging is sort of the wrong thing.

One other issue with auto-detecting `delta` is that `delta` is a POSIX utility too:

```console
> man delta
DELTA(1P)    POSIX Programmer's Manual
delta — make a delta (change) to an SCCS file (DEVELOPMENT)
```

It might make sense to instead have a `config.toml` option for which `diff` program to use (and it'd be nice if _other_ `compiletest` outputs used this too).

**Comment by pickfire** [comment]
Maybe it would be good to ask what the author of delta thinks?

@dandavison What do you think?

File: src/tools/compiletest/src/runtest.rs [hunk 9]
```diff
@@ -2325,15 +2341,100 @@ impl<'test> TestCx<'test> {
...
+        if !status.success() {
+            self.fatal("failed to run tidy - is it installed?");
+        }
+        let status = Command::new(tidy).arg(&compare_dir).spawn().unwrap().wait().unwrap();
+        if !status.success() {
+            self.fatal("failed to run tidy");
+        }
+
+        let has_delta = Command::new("delta")
+            .arg("--version")
```
Comment (dandavison) [inline src/tools/compiletest/src/runtest.rs:2410]: Regarding the possible confusion with other executables named "delta", would one possibility be to call delta with a command line argument that only delta would have, in addition to `--version`? I admit it might look a bit odd, but e.g. `delta --version --show-config` also just prints the version number but would be very likely to fail for anything that's not the intended delta.

**Comment by dandavison** [comment]
> @dandavison What do you think?

I don't have the full context here yet but in general I'm happy for delta to be used like this. It does seem like, in the absence of a Unix-ey standard for specifying ones preferred diff viewer, that the user's choice of git pager, if discernible, might be a reasonable choice. I'm happy for you to default to delta if it appears to be available.

In the longer term I'll just note that there is an open issue for delta to be refactored as a Rust crate, which would give you another option for a default without worrying about the user's environment. But I'm not sure yet when that will be done! https://github.com/dandavison/delta/issues/317

> But git is the good way to know if someone is using delta as their pager. Maybe we could parse some environment variables or check git config -l for that but I don't think we should implicitly choose the pager for the users. 

I didn't see this mentioned but just in case it helps there's also `git config --get core.pager`.

**Comment by jyn514** [comment]
Ok, I used this to use the default git pager instead of hardcoding `delta` or `diff --color`.

**Comment by jyn514** [comment]
@GuillaumeGomez is this waiting on something from me?

**Comment by GuillaumeGomez** [comment]
Well, I was wondering about the bash script. If you want, I can make the update in a follow-up PR? Otherwise it looks good to me so if it's ready for you, r=me.

File: src/tools/compiletest/tidy-rustdoc.sh (hunk 5 above)
Comment (jyn514) [reply src/tools/compiletest/tidy-rustdoc.sh]: I moved it to rust instead.

**Comment by jyn514** [comment]
I think this is ready to go; I moved the shell script to Rust and this uses `git config --get core.pager` to determine the pager.

**Review by GuillaumeGomez — APPROVED** [review]

File: src/tools/compiletest/src/runtest.rs [hunk 10]
```diff
@@ -2325,15 +2341,131 @@ impl<'test> TestCx<'test> {
...
+        let mut diff = Command::new("diff");
+        diff.args(&["-u", "-r"]).args(&[out_dir, &compare_dir]);
+
+        let output = if let Some(pager) = pager {
+            let diff_pid = diff.stdout(Stdio::piped()).spawn().expect("failed to run `diff`");
+            let pager = pager.trim();
+            if self.config.verbose {
+                eprintln!("using pager {}", pager);
+            }
+            let output = Command::new(pager)
```
Comment (pickfire) [inline src/tools/compiletest/src/runtest.rs:2446]: Can `pager` be like `diff -u` (contain arguments)?

Comment (jyn514) [reply src/tools/compiletest/src/runtest.rs:2446]: No, `Command::new` runs it as if it were in quotes.
