### PR TITLE
Fixes #79357 unstable or-pat suggestions

### LINKED ISSUE #79357: Compiler suggesting unstable or-pattern in for loop
When forgetting to include parenthesis around a tuple pattern in a for loop, the compiler gives a suggestion to use an or pattern. I would expect this, a. because it's not what most would expect if you use a comma to separate two values in a pattern, and b. because or patterns in for loops are still an unstable feature. 

I tried this code:

```rust
    let a = vec![1, 2, 3];
    let b = vec![3, 4, 5];
    
    for foo, bar in a.into_iter().zip(b) {    }
```
As expected, the compiler gives an `unexpected `,` in pattern` error, because I forgot the parenthesis around `(foo, bar)`. However, the compiler also suggests that I add a "vertical bar to match on multiple alternatives". 

```
error: unexpected `,` in pattern
 --> src/main.rs:5:13
  |
5 |     for foo, bar in a.into_iter().zip(b) {
  |             ^
  |
help: try adding parentheses to match on a tuple...
  |
5 |     for (foo, bar) in a.into_iter().zip(b) {
  |         ^^^^^^^^^^^
help: ...or a vertical bar to match on multiple alternatives
  |
5 |     for foo | bar in a.into_iter().zip(b) {
  |         ^^^^^^^^^^
```

[Playground Link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6afbf2156c50598a9a04f64f9e1bce8c)

While it does provide the correct answer (adding parenthesis), it also provides the vertical bar option, which is an unstable feature in this [RFC](https://github.com/rust-lang/rfcs/blob/master/text/2535-or-patterns.md). 

While the RFC does not explicitly single out for loops as a situation where this is necessary, I believe it does apply here, because in [this situation](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fe1b2f314c93af2c559cb4446d47d2db) (credit /u/ehuss for the example, which is a situation where the or pattern syntax is being used correctly, I get a `or-patterns syntax is experimental` error, as expected, and including `#![feature(or_patterns)]` resolves the error. 

### Meta

I tested this on stable, beta, and nightly in the rust playground. The output is identical for all 3 of them.

### PR DESCRIPTION
**Pull request by nico-abram**
Fixes #79357

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc @petrochenkov ?

**Comment by mark-i-m** [comment]
I guess if #79278 lands in the same cycle as this PR, this one would get undone, unless we backport this PR to beta...

**Comment by nico-abram** [comment]
I wouldn't expect a diagnostics change to be worth backporting (But I don't know what the policy is, if there is one)

Should this one be left open until near the end of the cycle, and only merged if or patterns don't get stabilized? (And closed if so)

**Comment by mark-i-m** [comment]
@nico-abram I actually don't know. It looks like a pretty harmless PR to backport, and it improves UX, so maybe it could be backported. If it's not backported, I guess the plan you outlined makes sense.

**Comment by camelid** [comment]
I wouldn't expect this to be backported since this diagnostic has suggested or-patterns for several releases, and it's not even an incorrect suggestion – it is just invalid on stable.

File: compiler/rustc_parse/src/parser/pat.rs [hunk 1]
```diff
@@ -214,13 +219,15 @@ impl<'a> Parser<'a> {
                 "try adding parentheses to match on a tuple...",
```
Comment (camelid) [inline compiler/rustc_parse/src/parser/pat.rs:219]: Ideally this would skip the `...` if the or-pattern suggestion is not there. Otherwise it leads to confusing errors like:

```
error: unexpected `,` in pattern
  --> $DIR/issue-48492-tuple-destructure-missing-parens.rs:84:14
   |
LL |     let women, men: (Vec<Genome>, Vec<Genome>) = genomes.iter().cloned()
   |         -----^---- help: try adding parentheses to match on a tuple...: `(women, men)`
```

which looks like there's something else coming. Or you could just skip the `...` in both cases for both the tuple and the or-pattern suggestion; I believe there's precedence in other errors.

Comment (nico-abram) [reply compiler/rustc_parse/src/parser/pat.rs:219]: Would something like this be acceptable?

```
            let msg = "try adding parentheses to match on a tuple...";
            err.span_suggestion(
                seq_span,
                if or_suggestion { msg } else { msg.split("...").next().unwrap() },
                format!("({})", seq_snippet),
                Applicability::MachineApplicable,
            );

```

I couldn't find a const way of slicing or splitting (Or concatenating with a variable name, unlike the concat! macro, and without an external dependency like https://github.com/Vurich/const-concat)

Comment (matthewjasper) [reply compiler/rustc_parse/src/parser/pat.rs:219]: Maybe use `msg.trim_end_matches('.')` instead? Either seems acceptable.

**Comment by mark-i-m** [comment]
You beat me after all :P
