### PR TITLE
Normalize closure instance before eagerly monomorphizing it

### LINKED ISSUE #137009: -Clink-dead-code and -Cinstrument-coverage causes symbol already defined compiler error in nightly
### Code

With just the following cargo.toml

```toml
[package]
name = "debug-tarp-issue"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
```

and a `main.rs` with the default contents. Running 

```
RUSTFLAGS="-Clink-dead-code -Cinstrument-coverage" cargo test
```

Results in:

```
error: symbol `_RNCNvNtNtNtNtCs6KohR1qTMkp_10hyper_util6client6legacy7connect4http7connect0Bb_` is already defined
   --> /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hyper-util-0.1.10/src/client/legacy/connect/http.rs:795:8
    |
795 |     Ok(async move {
    |        ^^^^^^^^^^

error: could not compile `hyper-util` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

I've done a bit of work to narrow this down. So either of the flags on their own is fine, it's just the combination that causes the issue.,

I also have a MRE reproduction repo here: https://github.com/xd009642/debug-tarp-issue 

### Version with regression

So because this happened in a CI job for tarpaulin and we have some flaky tests and I don't use a mac myself I don't have an exact version. But this first occurred in our CI January 13th 2025.  This is evident because the mac nightly builds have failed from that date until now. Mac stable and beta still work fine.

### PR DESCRIPTION
**Pull request by compiler-errors**
We were monomorphizing two versions of the closure (or in the original issue, coroutine) -- one with normalized captures and one with unnormalized captures. This led to a symbol collision.

Fixes #137009
 
r? @saethlin or reassign

### CODE REVIEW

**Comment by compiler-errors** [comment]
Not sure if we should backport this, since 1.86 branches today (afaict). We could also just disable this eager norm behavior on beta. Or just ignore it, bc `-Clink-dead-code` is cursed and this isn't actually unsound or anything.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 1]
```diff
@@ -1509,6 +1509,13 @@ impl<'v> RootCollector<'_, 'v> {
                         }
                         _ => unreachable!(),
                     };
+                    let Ok(instance) = self.tcx.try_normalize_erasing_regions(
```
Comment (compiler-errors) [inline compiler/rustc_monomorphize/src/collector.rs:1512]: this code is unnecessarily defensive but i'd rather not turn this into an ICE with an impossible-to-normalize opaque type or something.

File: tests/ui/closures/eager-mono-with-normalizable-upvars.stdout [hunk 2]
```diff
@@ -0,0 +1,12 @@
+MONO_ITEM fn <() as std::process::Termination>::report @@ eager_mono_with_normalizable_upvars.b15aab124d22de9b-cgu.0[Internal]
```
Comment (saethlin) [inline tests/ui/closures/eager-mono-with-normalizable-upvars.stdout:1]: This is going to be flaky. Can you make this test ignore stdout?

Comment (saethlin) [reply tests/ui/closures/eager-mono-with-normalizable-upvars.stdout:1]: Or well instead of flaky I guess I mean this test will need to be re-blessed when distant parts of the compiler/library change.

File: tests/ui/closures/eager-mono-with-normalizable-upvars.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
+//@ compile-flags: -Zprint-mono-items=eager -Csymbol-mangling-version=v0
```
[the remark this answers is not in the document]
Comment (saethlin) [reply tests/ui/closures/eager-mono-with-normalizable-upvars.rs:1]: Ah, we raced.
