### PR TITLE
Fix warnings about the `native` target-cpu

### LINKED ISSUE #53322: `target-cpu=native` is broken on latest nightly
Reproduce with by creating a crate with 'cargo init' with .cargo/config set to
```
[build]
rustflags = ["-C", "target-cpu=native"]
```
It produces the following errors:
```
tmp/test1 $ cargo build --release                                                                            
Compiling test1 v0.1.0 (file:///tmp/test1)                                                              
'native' is not a recognized processor for this target (ignoring processor)                                
'native' is not a recognized processor for this target (ignoring processor)                                
'native' is not a recognized processor for this target (ignoring processor)                                
'native' is not a recognized processor for this target (ignoring processor)
'native' is not a recognized processor for this target (ignoring processor)
'native' is not a recognized processor for this target (ignoring processor)                                
'native' is not a recognized processor for this target (ignoring processor)                                
'native' is not a recognized processor for this target (ignoring processor)                                    
Finished release [optimized] target(s) in 0.25s
```
It was working fine on  `nightly-2018-08-06-x86_64-unknown-linux-gnu`, but broke with 
`nightly-2018-08-14-x86_64-unknown-linux-gnu` (rustup doesn't show any nightlies available between those dates.

### PR DESCRIPTION
**Pull request by alexcrichton**
This fixes a regression from #53031 where specifying `-C target-cpu=native` is
printing a lot of warnings from LLVM about `native` being an unknown CPU. It
turns out that `native` is indeed an unknown CPU and we have to perform a
mapping to an actual CPU name, but this mapping is only performed in one
location rather than all locations we inform LLVM about the target CPU.

This commit centralizes the mapping of `native` to LLVM's value of the native
CPU, ensuring that all locations we inform LLVM about the `target-cpu` it's
never `native`.

Closes #53322

### CODE REVIEW

**Comment by arielb1** [comment]
Wait, this doesn't have a test

test please

@bors r-

File: src/librustc_codegen_llvm/llvm_util.rs [hunk 1]
```diff
@@ -262,3 +264,19 @@ pub(crate) fn print(req: PrintRequest, sess: &Session) {
...
+        None => &*sess.target.target.options.cpu
+    };
+    if name != "native" {
+        return name
+    }
+
+    unsafe {
+        let mut len = 0;
+        let ptr = llvm::LLVMRustGetHostCPUName(&mut len);
+        str::from_utf8_unchecked(slice::from_raw_parts(ptr as *const u8, len))
```
[the remark this answers is not in the document]
Comment (arielb1) [reply src/librustc_codegen_llvm/llvm_util.rs]: not that I think this failing is unlikely, except for API bugs

File: src/test/run-make-fulldeps/target-cpu-native/Makefile [hunk 2]
```diff
@@ -1,5 +1,7 @@
 -include ../tools.mk
 
 all:
-	$(RUSTC) foo.rs -C target-cpu=native
+	$(RUSTC) foo.rs -C target-cpu=native 2>&1 | tee $(TMPDIR)/out.log
 	$(call RUN,foo)
+	# Make sure no warnings about "unknown CPU `native`" were emitted
+	if grep 'is not a recognized processor' $(TMPDIR)/out.log; then exit 1; fi
```
Comment (arielb1) [inline src/test/run-make-fulldeps/target-cpu-native/Makefile]: I would prefer to check that no warnings at all are emitted (i.e. that `out.log` is empty), to avoid this recurring with a different error message.

I don't think the compiler should ever emit garbage when compiling an empty file.

**Comment by arielb1** [comment]
r=me with test changed.

File: src/test/run-make-fulldeps/target-cpu-native/Makefile (hunk 2 above)
Comment (arielb1) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]: Are there platforms where the compiler is always chatty? If then, I would check that the compiler is not chatty on all the other platforms.

Comment (alexcrichton) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]: I basically hate writing tests in bash, do you know how to test a file is empty?

Comment (matthiaskrgr) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]: Maybe use ````wc```` and count the number of characters?
````wc --chars file | cut -d' ' -f1```` should be 0.

Comment (alexcrichton) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]: How do you test against 0 though? (I'm really bad at bash...)

Comment (matthiaskrgr) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]:
````bash
#!/bin/bash
touch file

if [ $(wc --chars file | cut -d' ' -f1) == 0 ]; then
	echo "it's zero!"
else
	echo "it's not zero!"
fi
````
should work :)

Comment (TheIronBorn) [reply src/test/run-make-fulldeps/target-cpu-native/Makefile]: Wouldn't `-s FILE` work? "True if FILE exists and has a size greater than zero."

**Comment by alexcrichton** [comment]
And *that's* why I hate shell tests
