### PR TITLE
Suggest parentheses for possible range method calling

### LINKED ISSUE #102396: Missing parentheses for range leads to misleading help suggestion
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2fe5c3a4035324f34c4a3cbab7ca1179)

```rust
fn main() { 
    for i in 1..11.rev() {
        println!("{i}");
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0689]](https://doc.rust-lang.org/nightly/error-index.html#E0689): can't call method `rev` on ambiguous numeric type `{integer}`
 --> src/main.rs:2:20
  |
2 |     for i in 1..11.rev() {
  |                    ^^^
  |
help: you must specify a concrete type for this numeric value, like `i32`
  |
2 |     for i in 1..11_i32.rev() {
  |                 ~~~~~~

For more information about this error, try `rustc --explain E0689`.
error: could not compile `playground` due to previous error
```

Ideally the output should something like this:

```
Compiling playground v0.0.1 (/playground)
error[[E0689]](https://doc.rust-lang.org/nightly/error-index.html#E0689): can't call method `rev` on ambiguous numeric type `{integer}`
 --> src/main.rs:2:20
  |
2 |     for i in 1..11.rev() {
  |                    ^^^
  |
help: you must surround the range in parentheses to call the `rev` function
  |
2 |     for i in (1..11).rev() {
  |              +     +

For more information about this error, try `rustc --explain E0689`.
error: could not compile `playground` due to previous error
```

@rustbot label +D-confusing +D-invalid-suggestion

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #102396

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 1]
```diff
@@ -1201,6 +1203,68 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        tcx: TyCtxt<'tcx>,
+        source: SelfSource<'_>,
+        span: Span,
+        item_name: Ident,
+        ty_str: &str,
+    ) -> bool {
+        if let SelfSource::MethodCall(expr) = source {
+            // avoid suggesting when the method name is not implemented for a `range`
+            // FIXME: any better solution?
+            let valid_methods = [
```
Comment (chenyukang) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1217]: Any better solution for this? @lcnr

File: src/test/ui/methods/issues/issue-90315.rs [hunk 2]
```diff
@@ -1,7 +1,54 @@
...
+
+    for i in 1..(end + 1).rev() {
+        //~^ ERROR not an iterator
+        // Suggest add the missing parentheses for range
+        println!("{i}");
+    }
+
+    if 1..(end + 1).is_empty() {
+        //~^ ERROR not an iterator
+        //~^^ ERROR mismatched types [E0308]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:30]:
```suggestion
        //~| ERROR mismatched types [E0308]
```

I think this should work. Change all occurrence of this to the one with `|`.

File: src/test/ui/methods/issues/issue-90315.rs [hunk 3]
```diff
@@ -1,7 +1,54 @@
...
+        // Won't suggest
+    }
+
+    let _res: i32 = 3..6.take(1).sum();
+    //~^ ERROR `{integer}` is not an iterator [E0599]
+    //~^^ ERROR mismatched types [E0308]
+    let _sum: i32 = 3..6.sum();
+    //~^ ERROR `{integer}` is not an iterator [E0599]
+    //~^^ ERROR mismatched types [E0308]
 }
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:54]: Is it worth it to add more tests regarding inclusive range (`..=`) and where the beginning of the range is a variable which is not tested here? (Possibly where both are variables too). Not sure if that will be too much.

File: src/test/ui/methods/issues/issue-90315.rs [hunk 4]
```diff
@@ -1,7 +1,54 @@
...
+    let arr = &[0, 1, 2, 3];
+    for _i in 0..arr.len().rev() { //~ERROR not an iterator
+        // The above error used to say “the method `rev` exists for type `usize`”.
+        // This regression test ensures it doesn't say that any more.
+    }
+
+    // Test
+    for i in 1..11.rev() {
+        //~^ ERROR not an iterator
+        // Suggest add the missing parentheses for range
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:11]:
```suggestion
        //~| HELP surround the range in parentheses
```
Maybe this is better for all occurrences of this statement?

File: src/test/ui/methods/issues/issue-90315.rs [hunk 5]
```diff
@@ -1,7 +1,54 @@
 fn main() {
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:1]: Maybe add this `#![allow(unused)]` to not require anything inside the for loops.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1217]: yeah, that's obviously not great :thinking:

I guess what you can do is:

- first check if the integer is the second half of a range
- probe whether this method is found for ranges

lint in that case

I am not 100% sure how to best do that: probably just using `lookup_probe` :thinking: haven't used the method code too much

File: src/test/ui/methods/issues/issue-90315.rs (hunk 3 above)
Comment (chenyukang) [reply src/test/ui/methods/issues/issue-90315.rs:54]: Sounds great, will add one..

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 6]
```diff
@@ -1201,6 +1203,85 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    println!("item_name: {:?}", item_name);
+                    println!("expr: {:?}", expr);
+                    let pick =  self.lookup_probe(
+                        span,
+                        item_name,
+                        range_ty,
+                        expr,
+                        ProbeScope::TraitsInScope
+                    );
+                    println!("pick: {:?}", pick);
```
Comment (chenyukang) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1254]: I tried to `lookup_probe` method such as `rev` in `std::ops::Range<Idx>`, but it's failed.
The code for `lookup_probe` seems complicated, I'm still trying to understand it.

@compiler-errors do you know why it failed? I think `Range` implemented iterator, so it could find the `rev` method.

The log for this part of code is such as:

image

Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1254]: I try to suggest user to change 

```console
let _res = 1..10.rev();
```
to 
```console
let _res = (1..10).rev();
```

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 7]
```diff
@@ -1206,38 +1206,54 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            _ => false,
+                    };
+
+                    if !span_included {
+                        continue;
+                    }
+                    println!("parent_expr: {:?}", parent_expr);
+
+                    let range_def_id = self.tcx.lang_items().range_struct().unwrap();
+                    let range_ty = self.tcx.type_of(range_def_id);
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1238]: this is `Range<T>` which doesn't implement `Iterator`. You have to use `self.tcx.bound_type_of(range_def_id).subst(self.tcx, my_integer_type)`

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 6 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1254]: solved it, thanks @lcnr !

File: src/test/ui/methods/issues/issue-90315.rs [hunk 8]
```diff
@@ -1,7 +1,67 @@
+#![allow(unused)]
 fn main() {
-  let arr = &[0,1,2,3];
-  for _i in 0..arr.len().rev() { //~ERROR not an iterator
-     // The above error used to say “the method `rev` exists for type `usize`”.
-     // This regression test ensures it doesn't say that any more.
-  }
+    let arr = &[0, 1, 2, 3];
+    for _i in 0..arr.len().rev() { //~ERROR not an iterator
+        //~| surround the range in parentheses
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:5]:
```suggestion
    for _i in 0..arr.len().rev() {
        //~^ ERROR not an iterator
        //~| HELP surround the range in parentheses
```

File: src/test/ui/methods/issues/issue-90315.rs [hunk 9]
```diff
@@ -1,7 +1,67 @@
...
+    }
+
+    for i in 1..(end + 1).rev() {
+        //~^ ERROR not an iterator
+        //~| HELP surround the range in parentheses
+    }
+
+    if 1..(end + 1).is_empty() {
+        //~^ ERROR not an iterator
+        //~^^ ERROR mismatched types [E0308]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:29]:
```suggestion
        //~| ERROR mismatched types [E0308]
```

File: src/test/ui/methods/issues/issue-90315.rs [hunk 10]
```diff
@@ -1,7 +1,67 @@
...
+        //~| HELP surround the range in parentheses
+    }
+
+    if 1..(end + 1).is_sorted() {
+        //~^ ERROR mismatched types [E0308]
+        //~^^ ERROR `usize` is not an iterator [E0599]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:35]:
```suggestion
        //~| ERROR `usize` is not an iterator [E0599]
```

File: src/test/ui/methods/issues/issue-90315.rs [hunk 11]
```diff
@@ -1,7 +1,67 @@
...
+        //~| HELP surround the range in parentheses
+    }
+
+    let _res: i32 = 3..6.take(2).sum();
+    //~^ ERROR `{integer}` is not an iterator [E0599]
+    //~^^ ERROR mismatched types [E0308]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:41]:
```suggestion
    //~| ERROR mismatched types [E0308]
```

File: src/test/ui/methods/issues/issue-90315.rs [hunk 12]
```diff
@@ -1,7 +1,67 @@
...
+    //~| HELP surround the range in parentheses
+
+    let _sum: i32 = 3..6.sum();
+    //~^ ERROR `{integer}` is not an iterator [E0599]
+    //~^^ ERROR mismatched types [E0308]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:46]:
```suggestion
    //~| ERROR mismatched types [E0308]
```

File: src/test/ui/methods/issues/issue-90315.rs [hunk 13]
```diff
@@ -1,7 +1,67 @@
...
+        //~| HELP surround the range in parentheses
+    }
+
+    let _res = ..10.contains(3);
+    //~^ ERROR not an iterator
+    //~| HELP surround the range in parentheses
+
+    if 1..end.error_method() {
+        //~^ ERROR no method named `error_method`
+        //~^^ ERROR mismatched types [E0308]
```
Comment (Rageking8) [inline src/test/ui/methods/issues/issue-90315.rs:63]:
```suggestion
        //~| ERROR mismatched types [E0308]
```

File: src/test/ui/methods/issues/issue-90315.rs (hunk 8 above)
Comment (chenyukang) [reply src/test/ui/methods/issues/issue-90315.rs]: Updated, thanks.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 14]
```diff
@@ -1201,6 +1203,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        &self,
+        tcx: TyCtxt<'tcx>,
+        actual: Ty<'tcx>,
+        source: SelfSource<'tcx>,
+        span: Span,
+        item_name: Ident,
+        ty_str: &str,
+    ) -> bool {
+        if let SelfSource::MethodCall(expr) = source {
+            for (_, parent) in tcx.hir().parent_iter(expr.hir_id) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1216]: Is using `parent_iter` here necessary? Why do we care about more than one parent? Or should we only skip method call parents?

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 15]
```diff
@@ -1201,6 +1203,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    let pick =  self.lookup_probe(
+                        span,
+                        item_name,
+                        range_ty,
+                        call_expr,
+                        ProbeScope::AllTraits
+                    );
+
+                    if pick.is_ok() {
+                        let mut err = struct_span_err!(
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1243]: Can you make this into a structured diagnostic? https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 14 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1216]: For the case like this code:
```rust
let _res = a..b.take(1).sum();
```

`expr` is with span `b`, 
then expand parent to `b.take(1)`,
then expand parent to `b.take(1).sum()`,
then expand parent to `a..b.take(1).sum()`, this is our wanted expr.

Maybe we should add a search limit for the loop, for example 5?
since the possibility is less and less with the search number increasing.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 16]
```diff
@@ -1201,6 +1203,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        source: SelfSource<'tcx>,
+        span: Span,
+        item_name: Ident,
+        ty_str: &str,
+    ) -> bool {
+        if let SelfSource::MethodCall(expr) = source {
+            for (_, parent) in tcx.hir().parent_iter(expr.hir_id) {
+                if let Node::Expr(parent_expr) = parent && is_range_literal(parent_expr) {
+                    let span_included = match parent_expr.kind {
+                            hir::ExprKind::Struct(_, eps, _) => eps.iter().any(|ep| ep.expr.span.contains(span)),
```
Comment (chenyukang) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1219]: I think this `span_included` is no need, since parent must contains the sub-expr? @lcnr

Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1219]: emm, we need to check it's the right bound of a range.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 17]
```diff
@@ -1201,6 +1203,71 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            _ => false,
+                    };
+
+                    if !span_included {
+                        continue;
+                    }
+
+                    let range_def_id = self.tcx.lang_items().range_struct().unwrap();
+                    let range_ty = self.tcx.bound_type_of(range_def_id).subst(self.tcx, &[actual.into()]);
+                    let call_expr = self.tcx.hir().expect_expr(self.tcx.hir().get_parent_node(expr.hir_id));
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1231]: Why are we certain that `expr`'s parent is an expr?
Should we just exit the loop the first time we do not see an expr?

Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1231]: we are sure about this because this check: https://github.com/rust-lang/rust/blob/348d08282afc03c159cdf2adceacedf37ac13971/compiler/rustc_hir_analysis/src/check/method/suggest.rs#L1217

But, this `call_expr` is not necessary now, I have removed it in my local branch, will push it later.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 18]
```diff
@@ -1201,6 +1204,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        item_name: Ident,
+        ty_str: &str,
+    ) -> bool {
+        if let SelfSource::MethodCall(expr) = source {
+            let mut search_limit = 5;
+            for (_, parent) in tcx.hir().parent_iter(expr.hir_id) {
+                search_limit -= 1;
+                if search_limit == 0 {
+                    break;
+                }
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1222]: is this intended to only do 4 loops instead of 5?
```suggestion
                if search_limit == 0 {
                    break;
                } else {
                    search_limit -= 5;
                }
```
alternatively, `for (_, parent) in tcx.hir().parent_iter(expr.hir_id).take(5)`

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 19]
```diff
@@ -1201,6 +1204,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            // `..=` desugars into `::std::ops::RangeInclusive::new(...)`.
+                            hir::ExprKind::Call(ref func, ..) => func.span.contains(span),
+                            _ => false,
+                    };
+
+                    if !span_included {
+                        continue;
+                    }
+
+                    let range_def_id = self.tcx.lang_items().range_struct().unwrap();
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1237]: this always searches methods for `Range<T>` but the code above seems to also accept `RangeTo` and others (which implement different traits). Can you either change this code to use the correct range type or limit this help to range?

You should be able to get the type of the expr by using `typeck_results.opt_node_type` and then match on it, check that it's an `Adt` and then you can call `bound_type_of` on the `def_id` of the adt type

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 18 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1222]: Nice!

Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs]: > is this intended to only do 4 loops instead of 5?
not intended, 5 is also good I think.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 19 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs]: I tried to use `self.typeck_results.borrow().node_type_opt(parent_expr.hir_id)` and the return value is `None`.

I guess because we are at the point of error-handling part of type checking for the right bound of the ranges....

I use updated the code to get the right `lang-item` from `parent_expr.kind`, and add a testcase for it.

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 20]
```diff
@@ -1201,6 +1204,80 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        actual: Ty<'tcx>,
+        source: SelfSource<'tcx>,
+        span: Span,
+        item_name: Ident,
+        ty_str: &str,
+    ) -> bool {
+        if let SelfSource::MethodCall(expr) = source {
+            for (_, parent) in tcx.hir().parent_iter(expr.hir_id).take(5) {
+                if let Node::Expr(parent_expr) = parent {
+                    let lang_item = match parent_expr.kind {
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1219]: would be nice to only have this match once. Maybe change `is_range_expr` to call `get_range_expr_ty` which returns `Option<LangItem>` while using `get_range_expr_ty` directly for this

**Review by lcnr — APPROVED** [review]

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 20 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1219]: There is no `is_range_expr`, so I guess you mean `is_range_literal` ?
There is a trivial difference, here we can not handle the case for:
`RangeFrom` and `RangeFull`,
we only handle the scenarios which have a right boundry...

File: compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl [hunk 21]
```diff
@@ -133,3 +133,8 @@ hir_analysis_extern_crate_not_idiomatic =
     .suggestion = convert it to a `{$msg_code}`
 
 hir_analysis_expected_used_symbol = expected `used`, `used(compiler)` or `used(linker)`
+hir_analysis_expected_used_symbol = expected `used`, `used(compiler)` or `used(linker)`
```
Comment (lcnr) [inline compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:136]: duplicate?

File: compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl [hunk 22]
```diff
@@ -133,3 +133,8 @@ hir_analysis_extern_crate_not_idiomatic =
...
+
+hir_analysis_missing_parentheses_in_range = `{$ty_str}` is not an iterator
```
Comment (lcnr) [inline compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:138]: this feels wrong as your error also triggers for `0..7.contains(&3)`. Thinking about this: Instead of emitting a completely separate error, can you only add a note to the error created further down, ignoring all other attempts at adding help or notes?

File: compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl (hunk 21 above)
Comment (chenyukang) [reply compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl]: yes, resolved.

File: compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl (hunk 22 above)
Comment (chenyukang) [reply compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:137]: This is previous error message:
image

I changed it to like this:
image

Do you mean keep the `error[E0689]: can't call method `contains` on ambiguous numeric type `{integer}`` as before?

Comment (lcnr) [reply compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:137]: yes, `contains` is not a method on iterators

Comment (chenyukang) [reply compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:137]: I change it to:
> error[E0689]: can't call method `contains` on type `{integer}`
And then add the help message.

I won't want to mix the code with `suggest_constraining_numerical_ty`, which will make the code more complicated.

**Comment by chenyukang** [comment]
r? @lcnr 
Help me on merging it, afraid need to rebase with master again, 😁

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 23]
```diff
@@ -1201,6 +1204,81 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         false
     }
 
+    fn suggest_range_for_iter(
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1207]: this name doesn't feel completely right anymore, maybe
```suggestion
    fn suggest_wrapping_range_with_parens(
```

Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1207]: also please add a short comment explaining the purpose of this function, even just something like

```rust
/// When encountering `0..1.map(|i| i + 1)` suggest `(0..1).map(|i| i + 1)`.
```

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs [hunk 24]
```diff
@@ -1201,6 +1204,81 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        continue;
+                    }
+
+                    debug!("lang_item: {:?}", lang_item);
+                    let range_def_id = self.tcx.require_lang_item(lang_item.unwrap(), None);
+                    let range_ty =
+                        self.tcx.bound_type_of(range_def_id).subst(self.tcx, &[actual.into()]);
+
+                    let pick =
+                        self.lookup_probe(span, item_name, range_ty, expr, ProbeScope::AllTraits);
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/method/suggest.rs:1261]: can you emit a comment for why we're using `ProbeScope::AllTraits` here, I remember that you mentioned the reason for that before but I forgot that again :grin: 

also, i think ideally we would use `probe_for_name` directly here with `IsSuggestion(true)`. Not sure what `IsSuggestion` does but we are emitting a suggestion here, so setting that to true seems like it should be done :sweat_smile:

File: compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl [hunk 25]
```diff
@@ -133,3 +133,7 @@ hir_analysis_extern_crate_not_idiomatic =
     .suggestion = convert it to a `{$msg_code}`
 
 hir_analysis_expected_used_symbol = expected `used`, `used(compiler)` or `used(linker)`
+
+hir_analysis_missing_parentheses_in_range = can't call method `{$method_name}` on type `{$ty_str}`
+
+hir_analysis_add_missing_parentheses_in_range = you must surround the range in parentheses to call the `{$func_name}` function
```
Comment (lcnr) [inline compiler/rustc_error_messages/locales/en-US/hir_analysis.ftl:139]:
```suggestion
hir_analysis_add_missing_parentheses_in_range = you must surround the range in parentheses to call its `{$func_name}` function
```
personal opinion, but with this it's a bit clearer why wrapping the range is useful.

**Review by lcnr — COMMENTED** [review]
some small nits, then r=me

File: compiler/rustc_hir_analysis/src/check/method/suggest.rs (hunk 24 above)
Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1261]: Seems `IsSuggestion` only used at here:
https://github.com/rust-lang/rust/blob/1536ab1b383f21b38f8d49230a2aecc51daffa3d/compiler/rustc_hir_analysis/src/check/method/probe.rs#L1230

Use `ProbeScope::TraitsInScope` can not find the pick, but `ProbeScope::AllTraits` will find it.

Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs:1261]: it seems helpful to not emit `unstable_name_collision_hint`s while looking for diagnostics, so that should still be done.

`ProbeScope::TraitsInScope` that feels weird and shouldn't be the case as `Iterator` is in scope. Is this still the case with the current code?

Comment (chenyukang) [reply compiler/rustc_hir_analysis/src/check/method/suggest.rs]: updated the code to use `probe_for_name`.

`ProbeScope::TraitsInScope` means find with the scope of `expr`, 
https://github.com/rust-lang/rust/blob/1536ab1b383f21b38f8d49230a2aecc51daffa3d/compiler/rustc_hir_analysis/src/check/method/probe.rs#L456

othewise try to find methods in all traits.

At this function, we are at a point of error handling of range type checking, since error happened so the `Iterator` is not in the scope? it's only my guess😁
