### PR TITLE
std: Don't abort process when printing panics in tests

### LINKED ISSUE #69558: Display in test fails with SIGILL (illegal instruction)
I tried this code (using `cargo test`):

```rust
use std::fmt::{Display, Formatter};
use std::fmt;
 
pub struct A(Vec<u32>);
 
impl Display for A {
    fn fmt(&self, _f: &mut Formatter<'_>) -> fmt::Result {
       self.0[0];
       Ok(())
   }
}
 
#[test]
fn main() {
   let a = A(vec![]);
   eprintln!("{}", a);
}
```

I expected to see this happen:
The thread should've panicked with 'Index out of bounds: the len is 0 but the index is 0'

Instead, this happened:
Thread crashes with SIGILL (illegal instruction)

### Meta
This bug works in stable, beta and nightly.
It also does the same in [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d2cd0b4c6fbbae1455b5cd534693092).
Here is my [cpu info](https://pastebin.com/2VDnmMPR) (I figured that it might be useful given the nature of the bug).
The bug doesn't appear if run from main, nor if run directly (without passing from the Display impl).

`rustc --version --verbose`:
```
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

running 1 test
thread panicked while processing panic. aborting.
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/path/to/proj/target/debug/deps/proj-296b7cb53c6210d6` (signal: 4, SIGILL: illegal instruction)

</p>
</details>

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes an issue when using `set_print` and friends, notably
used by libtest, to avoid aborting the process if printing panics. This
previously panicked due to borrowing a mutable `RefCell` twice, and this
is worked around by borrowing these cells for less time, instead
taking out and removing contents temporarily.

Closes #69558

### CODE REVIEW

File: src/libstd/io/stdio.rs [hunk 1]
```diff
@@ -792,10 +792,14 @@ fn print_to<T>(
...
-                    return w.write_fmt(args);
-                }
+            // Note that we completely remove a local sink to write to in case
+            // our printing recursively panics/prints, so the recursive
+            // panic/print goes to the global sink instead of our local sink.
+            let prev = s.borrow_mut().take();
+            if let Some(mut w) = prev {
+                let result = w.write_fmt(args);
+                *s.borrow_mut() = Some(w);
+                return result;
```
Comment (Mark-Simulacrum) [inline src/libstd/io/stdio.rs]: Just to make sure I'm understanding correctly, the reason this does not need a try_borrow_mut anymore is because there's no possibility of a recursive lock, right? I believe the try_borrow was added in https://github.com/rust-lang/rust/commit/e2fd2dffde52a59f7d59d67460aeb2ebf33f77dd FWIW.

**Review by Mark-Simulacrum — APPROVED** [review]
r=me if my understanding is right

I guess this just adds another case where our thread-local set_error/set_print functions aren't a great fit but that seems largely fine.

File: src/libstd/io/stdio.rs (hunk 1 above)
Comment (alexcrichton) [reply src/libstd/io/stdio.rs]: Right yeah the scope of the borrow should always be one line of code which doesn't execute other arbitrary lines of code (e.g. an arbitrary `Write` implementation). As a result we should be guaranteed that it always succeeds.

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum

I agree! This is all probably great reasons why `set_print` and `set_panic` should never be stabilized :)

**Comment by Mark-Simulacrum** [comment]
@bors r-

Looks like some tests are passing now and are expected to fail?
 * ui/panic-while-printing.rs
 * ui/test-panic-while-printing.rs

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum

Oh just forgot the annotation to say they're expected to pass

**Comment by Dylan-DPC** [comment]
Failed in rollup https://github.com/rust-lang/rust/pull/70008
@bors r-

**Comment by ehuss** [comment]
@bors r- 
Failed in #70085 on wasm32-unknown-unknown
