### PR TITLE
Miri interning: replace ICEs by proper errors

### LINKED ISSUE #71316: ICE with unleash-miri: mutable allocation in constant
I tried this code with `-Zunleash-the-miri-inside-of-you`:

```rust
// compile-flags: -Zunleash-the-miri-inside-of-you

#![feature(const_raw_ptr_deref)]
#![feature(const_mut_refs)]
#![allow(const_err)]

use std::cell::UnsafeCell;

// make sure we do not just intern this as mutable
const MUTABLE_BEHIND_RAW: *mut i32 = &UnsafeCell::new(42) as *const _ as *mut _;

fn main() {
}
```
This is a variant of the `mutable_const` test.

I am getting an ICE:
```
error: internal compiler error: mutable allocation in constant
  --> ice.rs:10:1
   |
10 | const MUTABLE_BEHIND_RAW: *mut i32 = &UnsafeCell::new(42) as *const _ as *mut _;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
```
Cc @rust-lang/wg-const-eval

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/71316

I also did some refactoring, as I kept being confused by all the parameters to `intern_shallow`, some of which have invalid combinations (such as a mutable const). So instead `InternMode` now contains all the information that is needed and invalid combinations are ruled out by the type system.

Also I removed interpreter errors from interning. We already ignored almost all errors, and the `ValidationFailure` errors that we handled separately actually cannot ever happen here. The only interpreter failure that was actually reachable was the UB on dangling pointers -- and arguably, a dangling raw pointer is not UB, so the error was not even correct. It's just that the rest of the compiler does not like "dangling" `AllocId`.

It should be possible to review the 3 commits separately.

r? @oli-obk 
Cc @rust-lang/wg-const-eval

### CODE REVIEW

File: src/librustc_mir/interpret/eval_context.rs [hunk 1]
```diff
@@ -869,6 +869,9 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // Our result will later be validated anyway, and there seems no good reason
         // to have to fail early here.  This is also more consistent with
         // `Memory::get_static_alloc` which has to use `const_eval_raw` to avoid cycles.
+        // FIXME: We can hit delay_span_bug if this is an invalid const, interning finds
+        // that problem, but we never run validation to show an error. Can we ensure
+        // this does not happen?
```
Comment (RalfJung) [inline src/librustc_mir/interpret/eval_context.rs:874]: I still need to try and actually case the ICE here -- but my worry is that the `delay_span_bug` in interning all assume that validation will be run after interning is done, and this code here violates that assumption.

File: src/test/ui/consts/dangling-alloc-id-ice.rs [hunk 2]
```diff
@@ -1,11 +1,13 @@
...
+#![allow(const_err)]
 
 union Foo<'a> {
     y: &'a (),
     long_live_the_unit: &'static (),
 }
 
-const FOO: &() = { //~ ERROR any use of this value will cause an error
+const FOO: &() = { //~ ERROR it is undefined behavior to use this value
+//~^ ERROR encountered dangling pointer in final constant
```
Comment (RalfJung) [inline src/test/ui/consts/dangling-alloc-id-ice.rs:10]: I am not happy about the duplicate error here, but I am also not sure how to best avoid it.

File: src/librustc_mir/interpret/intern.rs [hunk 3]
```diff
@@ -352,23 +352,24 @@ where
...
-                    |mut diag| {
-                        diag.note(crate::const_eval::note_on_undefined_behavior_error());
-                        diag.emit();
-                    },
-                ) {
-                    ErrorHandled::TooGeneric
-                    | ErrorHandled::Reported(ErrorReported)
-                    | ErrorHandled::Linted => {}
-                }
+        // We deliberately *ignore* interpreter errors here.  When there is a problem, the remaining
```
Comment (oli-obk) [inline src/librustc_mir/interpret/intern.rs:361]: I'm not sure if we hit all the allocations. If this error is happening while looking at the first field of a struct, and that errors, the second field is never looked at. So if the second field contains a relocation, I'm guessing that we won't actually intern that relocation. Validation can handle that though, I think, so just the comment here that needs updating

File: src/librustc_mir/interpret/intern.rs [hunk 4]
```diff
@@ -304,12 +304,18 @@ pub enum InternKind {
     ConstProp,
 }
 
+/// Intern `ret` and everything it references.
+///
+/// This *cannot raise an interpreter error*.  Doing so is left to validation, which
+/// trakcs where in the value we are and thus can show much better error messages.
```
Comment (oli-obk) [inline src/librustc_mir/interpret/intern.rs:310]:
```suggestion
/// tracks where in the value we are and thus can show much better error messages.
```

File: src/librustc_mir/interpret/intern.rs [hunk 5]
```diff
@@ -422,13 +428,16 @@ where
                 }
             }
         } else if ecx.memory.dead_alloc_map.contains_key(&alloc_id) {
-            // dangling pointer
-            throw_ub_format!("encountered dangling pointer in final constant")
+            // Codegen does not like dangling pointers, and generally `tcx` assumes that
```
Comment (oli-obk) [inline src/librustc_mir/interpret/intern.rs:431]: In case of constants, we could just use `std::ptr::dangling` (not in this PR, just a general idea), and make this a lint

File: src/test/ui/consts/dangling-alloc-id-ice.rs (hunk 2 above)
Comment (oli-obk) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: The duplication is because validation also errors about dangling things if I'm reading the stderr file correctly. So, we could just not error in interning in case we encounter a dangling reference, and only error for dangling relocations in padding and such.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:423]: That makes inequal pointers equal -- not sure if that is a problem?
Also we have to be careful to preserve the original alignment of the now-dead allocation (and not use the alignment of the raw ptr type).

File: src/test/ui/consts/dangling-alloc-id-ice.rs (hunk 2 above)
Comment (RalfJung) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: > So, we could just not error in interning in case we encounter a dangling reference, and only error for dangling relocations in padding and such.

The error from interning here ("encountered dangling pointer in final constant") is the same one that the `dangling_raw_ptr` test checks for. I don't know how to remove that error from `dangling-alloc-id-ice` (a dangling reference) without also removing it from `dangling_raw_ptr`.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:423]: the addresses of constants are not something that the user can rely on in any way. We'll need to start normalizing them anyway to fix our type system unsoundness with const generics of reference type.

File: src/test/ui/consts/dangling-alloc-id-ice.rs (hunk 2 above)
Comment (oli-obk) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: oooh, these are already leftovers. I don't get how the above can cause the reference the be in the leftover set. Rereading the interner logic, will update once I know.

Comment (RalfJung) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: The interned just collects *everything* in the leftover set. Typed interning ignores dangling pointers. Thus, dangling references end up in the same bucket as dangling raw pointers.

To avoid this, we'd need to... maybe skip leftover interning in case we find a dangling reference during the typed phase? Or at least skip emitting that error.

File: src/librustc_mir/interpret/intern.rs (hunk 3 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:354]: > if the second field contains a relocation, I'm guessing that we won't actually intern that relocation.

We will, in the leftover phase.

File: src/librustc_mir/interpret/intern.rs [hunk 6]
```diff
@@ -396,13 +420,13 @@ where
...
+            // all allocations referenced anywhere actually exist. So, make sure we error here.
+            ecx.tcx.sess.span_err(ecx.tcx.span, "encountered dangling pointer in final constant");
```
Comment (oli-obk) [inline src/librustc_mir/interpret/intern.rs:425]: how about not reporting the error here, but instead reporting it in the None arm in intern_shallow, where we can easily decide not to report for references.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:423]: The concrete addresses, not. But whether addresses are equal, and whether they are aligned, is observable inside const-eval, so we have to preserve that.

File: src/librustc_mir/interpret/intern.rs (hunk 6 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:425]: We never even get to `intern_shallow` for raw pointers. So, that doesn't help to prevent codegen stumbling over dangling raw pointers.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:423]: I don't think it is observable on stable, so we can break that.

File: src/test/ui/consts/dangling-alloc-id-ice.rs (hunk 2 above)
Comment (oli-obk) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: seems an aweful lot of complexity just to remove a diagnostic duplication... Let's ignore it?

**Comment by oli-obk** [comment]
refactorings of the interning logic have historically led to regressions of some sort. While the changes look benign to me, I wonder if we should do a crater run.

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:423]: I don't think we should build in the assumption that pointer equality will *never* be observable on stable `const fn`. That's a *huge* commitment.

For example, I presume we do want to permit the following eventually:
```rust
unsafe const fn test_ptr_eq(ptr1: *mut i32, ptr2: *mut i32) -> bool {
  let old2 = *ptr2;
  let sentinel = (*ptr1).wrapping_add(1); // definitely inequal to what is currently in ptr1.
  *ptr2 = sentinel;
  let eq = (*ptr1 == sentinel);
  // Restore old value.
  *ptr2 = old2;
  return eq;
}
```
This doesn't work for dangling pointers, granted -- but I'm just saying, this is a complex topic, and I'd rather not commit to such a limitation prematurely.

File: src/test/ui/consts/dangling-alloc-id-ice.rs (hunk 2 above)
Comment (RalfJung) [reply src/test/ui/consts/dangling-alloc-id-ice.rs:10]: I'm okay with ignoring it for now.

**Comment by RalfJung** [comment]
And our test suite got better each time. ;)

But, sure... a check-only run should suffice, right?
@bors try

**Comment by RalfJung** [comment]
@craterbot check

File: src/librustc_mir/interpret/intern.rs (hunk 5 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:423]: All I mean is that we can *break* the behaviour today. We should not permanently limit us, I agree.

Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:423]: Well, let's discuss that when someone proposes a concrete change. ;)
For now, I think a hard error on dangling pointers anywhere during interning is fine.

File: src/librustc_mir/interpret/eval_context.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/eval_context.rs:876]: Turns out we can get that to ICE even without Miri:
```rust
#![feature(const_transmute)]
#![warn(const_err)]

use std::mem;

const X: &i32 = unsafe {
    let x = 0;
    mem::transmute(&x)
};
```

**Comment by oli-obk** [comment]
The only regression is a network failure :tada:

File: src/librustc_mir/interpret/eval_context.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/eval_context.rs:876]: Do you want to add a test for this in this PR or fix it in this PR?

Comment (RalfJung) [reply src/librustc_mir/interpret/eval_context.rs:876]: The PR [does contain a test for the ICE outside Miri](https://github.com/rust-lang/rust/pull/71665/files#diff-c27257d12985eefbccba2a933eca48f4) -- mostly accidentally, when I added `allow(const_err)` I did not realize I was testing an ICE. ;)

For whether this can ICE with Miri, I haven't done another attempt at triggering it.

File: src/librustc_mir/interpret/intern.rs [hunk 7]
```diff
@@ -89,14 +89,15 @@ fn intern_shallow<'rt, 'mir, 'tcx, M: CompileTimeMachine<'mir, 'tcx>>(
             // Pointer not found in local memory map. It is either a pointer to the global
             // map, or dangling.
             // If the pointer is dangling (neither in local nor global memory), we leave it
-            // to validation to error. The `delay_span_bug` ensures that we don't forget such
-            // a check in validation.
+            // to validation to error -- it has the much better error messages, pointing out where
+            // in the value the dangling reference lies.
+            // The `delay_span_bug` ensures that we don't forget such a check in validation.
             if tcx.get_global_alloc(alloc_id).is_none() {
                 tcx.sess.delay_span_bug(ecx.tcx.span, "tried to intern dangling pointer");
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs:96]: Re: ICEs, this one is fine because interning itself does `tcx.sess.span_err`, so validation does not even enter the picture. I should probably adjust the comment here.

File: src/librustc_mir/interpret/intern.rs [hunk 8]
```diff
@@ -281,71 +297,78 @@ pub enum InternKind {
...
-                    | ErrorHandled::Reported(ErrorReported)
-                    | ErrorHandled::Linted => {}
-                }
+        // We deliberately *ignore* interpreter errors here.  When there is a problem, the remaining
+        // references are "leftover"-interned, and later validation will show a proper error
+        // and point at the right part of the value causing the problem.
+        match res {
+            Ok(()) => {}
+            Err(error) => {
+                ecx.tcx.sess.delay_span_bug(
```
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs:360]: This and the vtable `delay_span_bug` are the ones I am worried about, in case validation does not run.

File: src/librustc_mir/interpret/intern.rs (hunk 6 above)
Comment (RalfJung) [inline src/librustc_mir/interpret/intern.rs:425]: I assume it is too late here to adjust the allocations containing the dangling pointer? Because one thing we could do is replace all pointers to it with a (dangling) integer pointer (taking the alignment of the allocation as its base address). That would maintain data structure consistency (no dangling `AllocId` in `tcx`) and avoid having to hard-error here.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:425]: We could pull the `remove` invocation upfront to where elements are added to `todo` and put `(AllocId, Allocation)` pairs into `todo`. Then we'll only have to figure out how to make the visitor allow mutating the value in place. Likely that will require a sort of `MutVisitor`/`Visitor` duplication like `mir::Visitor` has.

Simpler would probably be to do a first pass over an Allocation and replace all dangling `AllocId`s in its relocation with integer pointers, but then we have a hard time telling apart user's integer pointers from our synthetic ones.

So the only thing that I can think of is to make this site a `delay_span_bug` and to do the "replace all dangling AllocIds` pass just before invoking `intern_const_alloc`

Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:425]: I don't think we can make this a `delay_span_bug` here, dangling raw pointers would not be a "bug" if we have synthetic ones.

I guess the weirdest part about the synthetic pointers is that inequal pointers could become equal, which doesn't seem great. Maybe we should just synthesize 1-byte global allocations and make them point to that?

Anyway I think that is something which can be resolved later, after landing this PR.

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:425]: yes

Comment (oli-obk) [reply src/librustc_mir/interpret/intern.rs:425]: > I guess the weirdest part about the synthetic pointers is that inequal pointers could become equal, which doesn't seem great. Maybe we should just synthesize 1-byte global allocations and make them point to that?

I'd prefer to just use integer pointers. There's no way their identity is important (if they were pointing to a static, they wouldn't be dangling), so deduplication is totally permissible.

Comment (RalfJung) [reply src/librustc_mir/interpret/intern.rs:425]: Opened an issue for this: https://github.com/rust-lang/rust/issues/72215
