### PR TITLE
Check generic params after sigature for main-fn-ty

### LINKED ISSUE #118772: "`main` function is not allowed to have generic parameters" when the parameter is a reference
### Code

```Rust
fn main(hmm: &i32) {
  println!("Hello, world!");
}
```

### Current output

```Shell
error[E0131]: `main` function is not allowed to have generic parameters
  --> src\bin\8.rs:22:8
   |
22 | fn main(hmm: &i32) {
   |        ^ `main` cannot have generic parameters

For more information about this error, try `rustc --explain E0131`.
```

### Desired output

```Shell
error[E0580]: `main` function has wrong type
  --> src\bin\8.rs:22:1
   |
22 | fn main(hmm: i32) {
   | ^^^^^^^^^^^^^^^^^ incorrect number of function parameters
   |
   = note: expected signature `fn()`
              found signature `fn(i32)`

For more information about this error, try `rustc --explain E0580`.
```

### Rationale and extra context

It is less clear to display the E0131 message for the situation, because it it's about generic parameters. Eg to quote from `rustc --explain E0131`:

> fn main<T>() { // error: main function is not allowed to have generic parameters

Whereas `rustc --explain E0580` explains:

> The `main` function prototype should never take arguments.

### Other cases

_No response_

### Anything else?

Additionally, neither error is output when the command run is `cargo test`; which is probably erroneous behavior, as `check`, `clippy`, `build`, and `run`.

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #118772

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/entry.rs [hunk 1]
```diff
@@ -190,6 +168,23 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
         main_def_id,
         expected_sig,
     );
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/entry.rs:170]: Can you make `check_function_signature` (or better yet, `Result<(), ErrorGuaranteed>`, and then do an early-return if it had an error? We should only emit one error, ideally.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @mu001999!

@bors r+ rollup
