### PR TITLE
Suggest `if let` on `let` refutable binding

### LINKED ISSUE #58385: Reduce jargon in "refutable pattern in local binding" diagnostic
Although the following error is not _incorrect_, it is unnecessarily obtuse for newcomers:

```
error[E0005]: refutable pattern in local binding: `T(_, _)` not covered
  --> $DIR/empty-never-array.rs:10:9
   |
LL |     let Helper::U(u) = Helper::T(t, []);
   |         ^^^^^^^^^^^^ pattern `T(_, _)` not covered

error: aborting due to previous error
```

We should probably reword the error to have a better explanation of what is happening in terms that someone just starting in the language can understand it along the lines "Hey! You are trying to destructure (even more jargon) an enum variant, but you aren't handling other possible enum variants. You might have meant to use `if let`."

### PR DESCRIPTION
**Pull request by estebank**
Fix #58385.

### CODE REVIEW

File: src/librustc_mir/hair/pattern/check_match.rs [hunk 1]
```diff
@@ -266,18 +267,35 @@ impl<'tcx> MatchVisitor<'_, 'tcx> {
...
+                          an `enum` with only one variant");
+                if let Ok(snippet) = self.tcx.sess.source_map().span_to_snippet(span) {
+                    err.span_suggestion(
+                        span,
+                        "you might want to use `if let` to ignore the variant that isn't matched",
+                        format!("if {} {{ /* */ }}", &snippet[..snippet.len() - 1]),
+                        Applicability::HasPlaceholders,
+                    );
                 }
+                err.note("for more information, visit \
```
Comment (cramertj) [inline src/librustc_mir/hair/pattern/check_match.rs]: Should this note perhaps be in the `rustc --explain` rather than inline here? it seems like it's a lot of extra text

**Comment by cramertj** [comment]
r=me (fine either way WRT my comment above)

It's sort of unfortunate how much extra space these hints take up, but it seems like they provide useful additional information.

**Comment by estebank** [comment]
@cramertj I can turn the following

```
error[E0005]: refutable pattern in local binding: `std::i32::MIN..=-1i32` and `1i32..=std::i32::MAX` not covered
  --> $DIR/const-match-check.rs:31:24
   |
LL |     let x: [i32; { let 0 = 0; 0 }] = [];
   |                        ^ patterns `std::i32::MIN..=-1i32` and `1i32..=std::i32::MAX` not covered
   |
   = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
   = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
help: you might want to use `if let` to ignore the variant that isn't matched
   |
LL |     let x: [i32; { if let 0 = 0 { /* */ } 0 }] = [];
   |                    ^^^^^^^^^^^^^^^^^^^^^^
```

into

```
error[E0005]: refutable pattern in local binding: `std::i32::MIN..=-1i32` and `1i32..=std::i32::MAX` not covered
  --> $DIR/const-match-check.rs:31:24
   |
LL |     let x: [i32; { let 0 = 0; 0 }] = [];
   |                    ----^-----
   |                    |   |
   |                    |   patterns `std::i32::MIN..=-1i32` and `1i32..=std::i32::MAX` not covered
   |                    help: you might want to use `if let` instead: `if let 0 = 0 { /* */ }`
   |
   = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
   = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
```

but I fear that readability actually suffers.

**Comment by estebank** [comment]
> it seems like it's a lot of extra text

I kind of agree, but I fail to see what I can remove without compromising on onboarding experience. I think it makes sense merge this as is and after we have real life experience with it we can cut it back if it proves to be too annoying in real codebases.

@bors r=cramertj

**Comment by Centril** [comment]
> but I fear that readability actually suffers.

That could be fixed by having some vertical space between the two inline labels/notes.
