### PR TITLE
Do not display hidden types, fixes issue 23912

### LINKED ISSUE #23912: rustdoc links to private structs, causing 404s
See http://doc.rust-lang.org/std/primitive.char.html#method.into_searcher as an example, `CharEqPattern` goes nowhere

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #23912.

r? @QuietMisdreavus 

(It's the one I was talking about a few days ago, just close it if it's useless.)

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
It looks like would just hide the `[src]` link? The rest of the impl will still be visible if the item had no visibility set. [And the impl will not even get there in the first place if the `for_` type is in a `#[doc(masked)]` crate anyway.](https://github.com/GuillaumeGomez/rust/blob/38429a66225c1a80aa7823baac060e1f00f3ab4d/src/librustdoc/html/render.rs#L1180) The issue was actually fixed by https://github.com/rust-lang/rust/pull/44026, and i'll close it out. It seems the issue i actually referenced/closed in that PR was a duplicate of that one. `>_>`

On the other hand, the test you have here is useful, but i think it would be better if the trait that was `#[doc(hidden)]` were public as well, since it would be removed from docs anyway for being a private item.

File: src/test/rustdoc/hidden-trait-struct-impls.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+struct Hidden;
+
+// @!has foo/struct.Bar.html '//*[@id="impl-Bar"]' 'impl Foo for Bar'
+impl Foo for Bar {}
+// @!has foo/struct.Bar.html '//*[@id="impl-Dark"]' 'impl Dark for Bar'
+impl Dark for Bar {}
+// @has foo/struct.Bar.html '//*[@id="impl-Bam"]' 'impl Bam for Bar'
+// @has foo/trait.Bam.html '//*[@id="implementors-list"]' 'impl Bam for Bar'
+impl Bam for Bar {}
+// @!has foo/struct.Bar.html '//*[@id="iimplementors-list"]' 'impl Bam for Hidden'
```
Comment (ollie27) [inline src/test/rustdoc/hidden-trait-struct-impls.rs]: `struct.Bar.html` -> `trait.Bam.html`

`iimplementors-list` -> `implementors-list`

File: src/test/rustdoc/hidden-trait-struct-impls.rs [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+trait Dark {}
+
+pub trait Bam {}
+
+pub struct Bar;
+
+struct Hidden;
+
+// @!has foo/struct.Bar.html '//*[@id="impl-Bar"]' 'impl Foo for Bar'
```
Comment (ollie27) [inline src/test/rustdoc/hidden-trait-struct-impls.rs]: `impl-Bar` -> `impl-Foo`

**Review by ollie27 — COMMENTED** [review]
You have to be very careful when writing `@!has` tests because typos mean the test passes without testing anything 😉.

**Comment by GuillaumeGomez** [comment]
@ollie27: Arf, you're right! Thanks!

**Comment by kennytm** [comment]
@GuillaumeGomez @QuietMisdreavus Is this PR still needed? #23912 has been closed by #44026.

**Comment by QuietMisdreavus** [comment]
@kennytm I want it for the test test it adds. If @GuillaumeGomez can take out the change in `render.rs` and address the review comments on the test, i'll add it.

**Comment by carols10cents** [comment]
Friendly ping to keep this on your radar @GuillaumeGomez!

**Comment by GuillaumeGomez** [comment]
Going back on it this week-end.

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/test/rustdoc/hidden-trait-struct-impls.rs [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![crate_name = "foo"]
+
+#[doc(hidden)]
+trait Foo {}
```
Comment (QuietMisdreavus) [inline src/test/rustdoc/hidden-trait-struct-impls.rs]: Tagging a private item with `#[doc(hidden)]` has no effect when you're not changing which passes are run. Can you make this `pub trait Foo` instead?

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
r=me pending travis

This is... kinda unrelated to https://github.com/rust-lang/rust/issues/23912 now, but as i said, the test is still useful.
