### PR TITLE
Change prefetch to avoid deadlock

### LINKED ISSUE #117759: Deadlock detected with "-Z threads=8"
### Code
I have tried to measure #117755 on a 32 core machine and got this ice after several tries.
Steps to reproduce:
```
cd $(mktemp -d)
git clone https://github.com/rustsec/rustsec.git
cd rustsec/cargo-audit
git checkout b6baecc0ea4e2d115e4e10b10c2196b33d42c1da
RUSTFLAGS="-Z threads=8" cargo +nightly build --timings
```
I have got it 2 times in a row, so it should be reproducible. 

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```

### Error output

```
   Compiling winnow v0.5.14
thread '<unnamed>' panicked at compiler/rustc_query_system/src/query/job.rs:543:9:
   Compiling aho-corasick v1.0.2
deadlock detected
stack backtrace:
   0:     0x7f4d92d69c9c - std::backtrace_rs::backtrace::libunwind::trace::h8709aeb3a36f95da
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f4d92d69c9c - std::backtrace_rs::backtrace::trace_unsynchronized::heb9f0713a26f337c
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4d92d69c9c - std::sys_common::backtrace::_print_fmt::h1ed75bc02e1d9ee5
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f4d92d69c9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hddc1fcb1d86cbcd2
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4d92dcbec0 - core::fmt::rt::Argument::fmt::h19337aa9a2c9da83
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/core/src/fmt/rt.rs:142:9
   5:     0x7f4d92dcbec0 - core::fmt::write::h2d162b4d9dda182b
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f4d92d5dbbf - std::io::Write::write_fmt::hcca591aa27610910
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/io/mod.rs:1763:15
   7:     0x7f4d92d69a84 - std::sys_common::backtrace::_print::h90b2688e948a362e
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f4d92d69a84 - std::sys_common::backtrace::print::h75b0cf3671567509
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f4d92d6c717 - std::panicking::default_hook::{{closure}}::h6694607f9ccfc6ea
  10:     0x7f4d92d6c47f - std::panicking::default_hook::h4c80dc8b62887255
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/panicking.rs:292:9
  11:     0x7f4d95a8cee0 - std[d2e36247d228c058]::panicking::update_hook::<alloc[74ba046d4657710e]::boxed::Box<rustc_driver_impl[741ff592be011714]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f4d92d6ce58 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf3ff6ce13f580837
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/alloc/src/boxed.rs:2021:9
  13:     0x7f4d92d6ce58 - std::panicking::rust_panic_with_hook::h5ad0da38d014c68e
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/panicking.rs:783:13
  14:     0x7f4d92d6cb79 - std::panicking::begin_panic_handler::{{closure}}::hdc6d3bffdbbdcfdd
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/panicking.rs:649:13
  15:     0x7f4d92d6a166 - std::sys_common::backtrace::__rust_end_short_backtrace::h80bfdfe497702363
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f4d92d6c912 - rust_begin_unwind
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/panicking.rs:645:5
  17:     0x7f4d92dc85e5 - core::panicking::panic_fmt::hf6ef87080f7e8766
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/core/src/panicking.rs:72:14
  18:     0x7f4d962c0b35 - rustc_query_system[7526d12203c43316]::query::job::deadlock
  19:     0x7f4d95a87edc - std[d2e36247d228c058]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6c8618f6eb06e019]::util::run_in_thread_pool_with_globals<rustc_interface[6c8618f6eb06e019]::interface::run_compiler<core[916dc932853bc0a1]::result::Result<(), rustc_span[3b1f2782555e1c8c]::ErrorGuaranteed>, rustc_driver_impl[741ff592be011714]::run_compiler::{closure#1}>::{closure#0}, core[916dc932853bc0a1]::result::Result<(), rustc_span[3b1f2782555e1c8c]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>
  20:     0x7f4d95a8ed71 - <<std[d2e36247d228c058]::thread::Builder>::spawn_unchecked_<rustc_interface[6c8618f6eb06e019]::util::run_in_thread_pool_with_globals<rustc_interface[6c8618f6eb06e019]::interface::run_compiler<core[916dc932853bc0a1]::result::Result<(), rustc_span[3b1f2782555e1c8c]::ErrorGuaranteed>, rustc_driver_impl[741ff592be011714]::run_compiler::{closure#1}>::{closure#0}, core[916dc932853bc0a1]::result::Result<(), rustc_span[3b1f2782555e1c8c]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>::{closure#1} as core[916dc932853bc0a1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
   Compiling object v0.31.1
  21:     0x7f4d92d77bc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hee756f0d76156df1
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/alloc/src/boxed.rs:2007:9
  22:     0x7f4d92d77bc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc26ba9eda2105aea
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/alloc/src/boxed.rs:2007:9
  23:     0x7f4d92d77bc5 - std::sys::unix::thread::Thread::new::thread_start::h9f04a0ee42338ce0
                               at /rustc/fdaaaf9f923281ab98b865259aa40fbf93d72c7a/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7f4d92b43897 - start_thread
  25:     0x7f4d92bca6bc - clone3
  26:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/odm3n/.cargo/registry/src/index.crates.io-6f17d22bba15001f/canonical-path-2.0.2/rustc-ice-2023-11-09T16_59_40-696374.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C linker=/usr/bin/clang -Z threads=8

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
deadlock handler panicked, aborting process
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling ring v0.16.20
   Compiling uluru v3.0.0
   Compiling backtrace v0.3.68
   Compiling rustls-pemfile v1.0.3
   Compiling clap_lex v0.2.4
   Compiling unicode-normalization v0.1.22
   Compiling indexmap v2.0.0
   Compiling bstr v1.6.0
   Compiling crossbeam-channel v0.5.8
   Compiling rustls-native-certs v0.6.3
   Compiling tracing-log v0.1.3
error: could not compile `canonical-path` (lib)

Caused by:
  process didn't exit successfully: `/home/odm3n/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name canonical_path --edition=2018 /home/odm3n/.cargo/registry/src/index.crates.io-6f17d22bba15001f/canonical-path-2.0.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=198 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=0e29fdb8b83c99cf -C extra-filename=-0e29fdb8b83c99cf --out-dir /tmp/tmp.2hv7B581Tu/rustsec/target/debug/deps -C linker=/usr/bin/clang -L dependency=/tmp/tmp.2hv7B581Tu/rustsec/target/debug/deps --cap-lints allow -Z threads=8` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
      Timing report saved to /tmp/tmp.2hv7B581Tu/rustsec/target/cargo-timings/cargo-timing-20231109T165939Z.html

```

[rustc-ice-2023-11-09T17_04_29-702009.txt](https://github.com/rust-lang/rust/files/13310922/rustc-ice-2023-11-09T17_04_29-702009.txt)
[rustc-ice-2023-11-09T16_59_40-696374.txt](https://github.com/rust-lang/rust/files/13310927/rustc-ice-2023-11-09T16_59_40-696374.txt)

### LINKED ISSUE #117784: deadlock detected when using -Zthreads=8
I just tried out the new parallelization feature of the compiler and it randomly panicked because a deadlock was detected.
I tried a couple of times and could not reproduce it unfortunately.

### Meta
`rustc --version --verbose`:
```
cargo 1.75.0-nightly (7046d992f 2023-11-08)
```

### Error output

```
thread '<unnamed>' panicked at compiler/rustc_query_system/src/query/job.rs:543:9:
deadlock detected

<Backtrace>

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -Z threads=8

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
deadlock handler panicked, aborting process
error: could not compile `bigdecimal` (lib)

Caused by:
  process didn't exit successfully: `/Users/martin/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rustc --crate-name bigdecimal /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bigdecimal-0.3.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=128 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --cfg 'feature="serde"' -C metadata=36f9c58248b94912 -C extra-filename=-36f9c58248b94912 --out-dir /Users/martin/work/backend/side/target/debug/deps -L dependency=/Users/martin/work/backend/side/target/debug/deps --extern num_bigint=/Users/martin/work/backend/side/target/debug/deps/libnum_bigint-3d0a0c3120349810.rmeta --extern num_integer=/Users/martin/work/backend/side/target/debug/deps/libnum_integer-ed949aa408650e16.rmeta --extern num_traits=/Users/martin/work/backend/side/target/debug/deps/libnum_traits-a22352494166d956.rmeta --extern serde=/Users/martin/work/backend/side/target/debug/deps/libserde-2f69e42262cb5ef0.rmeta --cap-lints allow -Z threads=8` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x100ee12b8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h052d4a6449303d0c
   1:        0x100f23268 - core::fmt::write::hd7376fa11f842969
   2:        0x100ed79ec - std::io::Write::write_fmt::h8962cd07816e935b
   3:        0x100ee10f4 - std::sys_common::backtrace::print::h97fb0a8a4077c481
   4:        0x100ee3af4 - std::panicking::default_hook::{{closure}}::h3b4672ac61ca5355
   5:        0x100ee383c - std::panicking::default_hook::h609e6a125a90b4e7
   6:        0x10a2eabb8 - <alloc[e142c9bf9c63cfc4]::boxed::Box<rustc_driver_impl[1a98898d3f3a38ed]::install_ice_hook::{closure#0}> as core[4e0a19b8f4e7b450]::ops::function::Fn<(&dyn for<'a, 'b> core[4e0a19b8f4e7b450]::ops::function::Fn<(&'a core[4e0a19b8f4e7b450]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[4e0a19b8f4e7b450]::marker::Send + core[4e0a19b8f4e7b450]::marker::Sync, &core[4e0a19b8f4e7b450]::panic::panic_info::PanicInfo)>>::call
   7:        0x100ee416c - std::panicking::rust_panic_with_hook::h9625542414b348eb
   8:        0x100ee3f10 - std::panicking::begin_panic_handler::{{closure}}::hb4fa343c314105dc
   9:        0x100ee1720 - std::sys_common::backtrace::__rust_end_short_backtrace::he263cec7b035e782
  10:        0x100ee3cd0 - _rust_begin_unwind
  11:        0x100f3d0b8 - core::panicking::panic_fmt::h624e311b541e9a0d
  12:        0x10b6fac6c - rustc_query_system[2c5cf56d08163fd7]::query::job::deadlock
  13:        0x10a2fba58 - std[f37625d93cba7df1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6fd153b9b61224af]::util::run_in_thread_pool_with_globals<rustc_interface[6fd153b9b61224af]::interface::run_compiler<(), rustc_driver_impl[1a98898d3f3a38ed]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#2}::{closure#1}, ()>
  14:        0x10a2cccfc - <<std[f37625d93cba7df1]::thread::Builder>::spawn_unchecked_<rustc_interface[6fd153b9b61224af]::util::run_in_thread_pool_with_globals<rustc_interface[6fd153b9b61224af]::interface::run_compiler<core[4e0a19b8f4e7b450]::result::Result<(), rustc_span[7d3d88934d9d268]::ErrorGuaranteed>, rustc_driver_impl[1a98898d3f3a38ed]::run_compiler::{closure#1}>::{closure#0}, core[4e0a19b8f4e7b450]::result::Result<(), rustc_span[7d3d88934d9d268]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>::{closure#1} as core[4e0a19b8f4e7b450]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  15:        0x100eec368 - std::sys::unix::thread::Thread::new::thread_start::h6af77cae4d08b8df
  16:        0x18f69ffa8 - __pthread_joiner_wake
```

</p>
</details>

[rustc-ice-2023-11-10T12_41_14-4307.txt](https://github.com/rust-lang/rust/files/13319483/rustc-ice-2023-11-10T12_41_14-4307.txt)

### LINKED ISSUE #118205: deadlock detected
### Code
`rustc --edition=2021 -Zthreads=16`
```Rust
pub static global: isize = 3;

static global0: isize = 4;

pub static global2: &'static isize = &global0;

pub fn verify_same(a: &'static isize) {
    let a = a as *const isize as usize;
    let b = &global as *const isize as usize;
    assert_eq!(a, b);
}

pub fn verify_same2(a: &'static isize) {
    let a = a as *const isize as usize;
    let b = global2 as *const isize as usize;
    assert_eq!(a, b);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (fc13ca6d7 2023-11-23)
binary: rustc
commit-hash: fc13ca6d70f7381513c22443fc5aaee1d151ea45
commit-date: 2023-11-23
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: static variable `global` should have an upper case name
 --> /home/matthias/vcs/github/rust_misc_stuff/tests/ui/cross-crate/auxiliary/xcrate_static_addresses.rs:1:12
  |
1 | pub static global: isize = 3;
  |            ^^^^^^ help: convert the identifier to upper case: `GLOBAL`
  |
  = note: `#[warn(non_upper_case_globals)]` on by default

warning: static variable `global0` should have an upper case name
 --> /home/matthias/vcs/github/rust_misc_stuff/tests/ui/cross-crate/auxiliary/xcrate_static_addresses.rs:3:8
  |
3 | static global0: isize = 4;
  |        ^^^^^^^ help: convert the identifier to upper case: `GLOBAL0`

warning: static variable `global2` should have an upper case name
 --> /home/matthias/vcs/github/rust_misc_stuff/tests/ui/cross-crate/auxiliary/xcrate_static_addresses.rs:5:12
  |
5 | pub static global2: &'static isize = &global0;
  |            ^^^^^^^ help: convert the identifier to upper case: `GLOBAL2`

thread '<unnamed>' panicked at compiler/rustc_query_system/src/query/job.rs:548:13:
deadlock detected! current query map:
{
    QueryJobId(
        1229,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "collecting exported symbols for crate `0`",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_adt_id: None,
            dep_kind: DepKind {
                variant: 249,
            },
            hash: 12056485195163891650,
        },
        job: QueryJob {
            id: QueryJobId(
                1229,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: None,
            latch: Some(
                QueryLatch {
                    info: Mutex {
                        data: QueryLatchInfo {
                            complete: false,
                            waiters: [
                                QueryWaiter {
                                    query: None,
                                    condvar: Condvar { .. },
                                    span: Span {
                                        lo: BytePos(
                                            0,
                                        ),
                                        hi: BytePos(
                                            0,
                                        ),
                                        ctxt: #0,
                                    },
                                    cycle: Mutex {
                                        data: None,
                                    },
                                },
                            ],
                        },
                    },
                },
            ),
        },
    },
    QueryJobId(
        1242,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "collect_and_partition_mono_items",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_adt_id: None,
            dep_kind: DepKind {
                variant: 250,
            },
            hash: 15975767348252564715,
        },
        job: QueryJob {
            id: QueryJobId(
                1242,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    1229,
                ),
            ),
            latch: None,
        },
    },
}
stack backtrace:
   0:     0x7f757e1bcafc - std::backtrace_rs::backtrace::libunwind::trace::hb7874fdb876d6a33
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f757e1bcafc - std::backtrace_rs::backtrace::trace_unsynchronized::hfd16eb345705ed29
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f757e1bcafc - std::sys_common::backtrace::_print_fmt::h2ebfc309c7ba6d42
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f757e1bcafc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ac6e06a20b25c35
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f757e20fc80 - core::fmt::rt::Argument::fmt::ha07604edfcde1b50
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/core/src/fmt/rt.rs:142:9
   5:     0x7f757e20fc80 - core::fmt::write::h65e51514dc428ee4
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f757e1b09af - std::io::Write::write_fmt::hb5d4658f9e4e80c1
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/io/mod.rs:1762:15
   7:     0x7f757e1bc8e4 - std::sys_common::backtrace::_print::h6f720f26eadbfa0e
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f757e1bc8e4 - std::sys_common::backtrace::print::ha7cb1801514bf000
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f757e1bf577 - std::panicking::default_hook::{{closure}}::h50d9eeaa2c9ddf63
  10:     0x7f757e1bf2df - std::panicking::default_hook::h2f1a9064e2ffc577
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/panicking.rs:292:9
  11:     0x7f757aefd0c0 - std[76d2dc5da0aff713]::panicking::update_hook::<alloc[a973e296dfb5f4bc]::boxed::Box<rustc_driver_impl[1a4eb564e865739e]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f757e1bfcb8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h964f55efb97c9907
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/alloc/src/boxed.rs:2021:9
  13:     0x7f757e1bfcb8 - std::panicking::rust_panic_with_hook::h6d23d56c8d3cb044
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/panicking.rs:783:13
  14:     0x7f757e1bfa0e - std::panicking::begin_panic_handler::{{closure}}::ha4f11e3cfef36a87
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/panicking.rs:657:13
  15:     0x7f757e1bcfc6 - std::sys_common::backtrace::__rust_end_short_backtrace::hb092d8d5af117d8a
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f757e1bf772 - rust_begin_unwind
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/panicking.rs:645:5
  17:     0x7f757e20c365 - core::panicking::panic_fmt::h0aba5e5824ae1da8
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/core/src/panicking.rs:72:14
  18:     0x7f757b7cae66 - rustc_query_system[6f0d3dc7706fe901]::query::job::deadlock
  19:     0x7f757aef507c - std[76d2dc5da0aff713]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[19061b1bef701b58]::util::run_in_thread_pool_with_globals<rustc_interface[19061b1bef701b58]::interface::run_compiler<core[b166d8b927da802c]::result::Result<(), rustc_span[80f72817ab8f0e5f]::ErrorGuaranteed>, rustc_driver_impl[1a4eb564e865739e]::run_compiler::{closure#0}>::{closure#0}, core[b166d8b927da802c]::result::Result<(), rustc_span[80f72817ab8f0e5f]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>
  20:     0x7f757aefee81 - <<std[76d2dc5da0aff713]::thread::Builder>::spawn_unchecked_<rustc_interface[19061b1bef701b58]::util::run_in_thread_pool_with_globals<rustc_interface[19061b1bef701b58]::interface::run_compiler<core[b166d8b927da802c]::result::Result<(), rustc_span[80f72817ab8f0e5f]::ErrorGuaranteed>, rustc_driver_impl[1a4eb564e865739e]::run_compiler::{closure#0}>::{closure#0}, core[b166d8b927da802c]::result::Result<(), rustc_span[80f72817ab8f0e5f]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>::{closure#1} as core[b166d8b927da802c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:     0x7f757e1c9b75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf4a56211c07be68c
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/alloc/src/boxed.rs:2007:9
  22:     0x7f757e1c9b75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5116e2d8972832ea
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/alloc/src/boxed.rs:2007:9
  23:     0x7f757e1c9b75 - std::sys::unix::thread::Thread::new::thread_start::h1997c24c5b66ef90
                               at /rustc/fc13ca6d70f7381513c22443fc5aaee1d151ea45/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7f75780aa9eb - <unknown>
  25:     0x7f757812e7cc - <unknown>
  26:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (fc13ca6d7 2023-11-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=/tmp/icemaker_global_tempdir.R2B4br2BXDkO/rustc_testrunner_tmpdir.Lsl8OcR7icb3 -Z no-codegen --crate-type lib -Z threads=16

query stack during panic:
end of query stack
deadlock handler panicked, aborting process
```

</p>
</details>

### LINKED ISSUE #118529: Panic on parallel build (deadlock detected)
rustc 1.76.0-nightly (49b3924bd 2023-11-27)
cargo 1.76.0-nightly (9b13310ca 2023-11-24)

the file it asked to attach: [rust.txt](https://github.com/rust-lang/rust/files/13535944/rust.txt)

```
thread '<unnamed>' panicked at compiler/rustc_query_system/src/query/job.rs:548:13:
deadlock detected! current query map:
{
    QueryJobId(
        80729,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "collecting exported symbols for crate `0`",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_adt_id: None,
            dep_kind: DepKind {
                variant: 249,
            },
            hash: 9945948751586091424,
        },
        job: QueryJob {
            id: QueryJobId(
                80729,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: None,
            latch: Some(
                QueryLatch {
                    info: Mutex {
                        data: QueryLatchInfo {
                            complete: false,
                            waiters: [
                                QueryWaiter {
                                    query: None,
                                    condvar: Condvar { .. },
                                    span: Span {
                                        lo: BytePos(
                                            0,
                                        ),
                                        hi: BytePos(
                                            0,
                                        ),
                                        ctxt: #0,
                                    },
                                    cycle: Mutex {
                                        data: None,
                                    },
                                },
                            ],
                        },
                    },
                },
            ),
        },
    },
    QueryJobId(
        80867,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "collect_and_partition_mono_items",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_adt_id: None,
            dep_kind: DepKind {
                variant: 250,
            },
            hash: 15975767348252564715,
        },
        job: QueryJob {
            id: QueryJobId(
                80867,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    80729,
                ),
            ),
            latch: None,
        },
    },
}
stack backtrace:
   Compiling async-std v1.12.0
   0:     0x7fe6065b6a2c - std::backtrace_rs::backtrace::libunwind::trace::h9c27ae506976e536
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fe6065b6a2c - std::backtrace_rs::backtrace::trace_unsynchronized::h62e141e6a200e6c2
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe6065b6a2c - std::sys_common::backtrace::_print_fmt::hdf2b25da31f023ba
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fe6065b6a2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ac0b64ce6cfe863
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe606609a70 - core::fmt::rt::Argument::fmt::h6aa2292ec1903e39
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/core/src/fmt/rt.rs:142:9
   5:     0x7fe606609a70 - core::fmt::write::h41514bcd312dd51c
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fe6065aa8ef - std::io::Write::write_fmt::hdb1ddb32bea23dbe
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/io/mod.rs:1766:15
   7:     0x7fe6065b6814 - std::sys_common::backtrace::_print::hf685833faa7fe2a3
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fe6065b6814 - std::sys_common::backtrace::print::h447647edbf699f27
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fe6065b94a7 - std::panicking::default_hook::{{closure}}::h9689a15e5dae79ac
  10:     0x7fe6065b920f - std::panicking::default_hook::h2d38e881f9eda692
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/panicking.rs:292:9
  11:     0x7fe6032ed470 - std[23ee412b4092bb]::panicking::update_hook::<alloc[e1658fb7cef3bb05]::boxed::Box<rustc_driver_impl[891cbe23e357ec56]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fe6065b9be8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha93d8a0e59d3a881
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/alloc/src/boxed.rs:2021:9
  13:     0x7fe6065b9be8 - std::panicking::rust_panic_with_hook::hd1ee884b9495e206
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/panicking.rs:783:13
  14:     0x7fe6065b993e - std::panicking::begin_panic_handler::{{closure}}::h22fee33aab39e73c
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/panicking.rs:657:13
  15:     0x7fe6065b6ef6 - std::sys_common::backtrace::__rust_end_short_backtrace::h95b1d8aedb30bf62
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fe6065b96a2 - rust_begin_unwind
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/panicking.rs:645:5
  17:     0x7fe606606145 - core::panicking::panic_fmt::h89ea74967cf6ec7d
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/core/src/panicking.rs:72:14
  18:     0x7fe603bb0159 - rustc_query_system[98b1e30a43f9cb75]::query::job::deadlock
  19:     0x7fe6032e8a8c - std[23ee412b4092bb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8adf1ec4c1467232]::util::run_in_thread_pool_with_globals<rustc_interface[8adf1ec4c1467232]::interface::run_compiler<core[2fd1802afb11265b]::result::Result<(), rustc_span[8b5f317805ba237c]::ErrorGuaranteed>, rustc_driver_impl[891cbe23e357ec56]::run_compiler::{closure#0}>::{closure#0}, core[2fd1802afb11265b]::result::Result<(), rustc_span[8b5f317805ba237c]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>
  20:     0x7fe6032ef631 - <<std[23ee412b4092bb]::thread::Builder>::spawn_unchecked_<rustc_interface[8adf1ec4c1467232]::util::run_in_thread_pool_with_globals<rustc_interface[8adf1ec4c1467232]::interface::run_compiler<core[2fd1802afb11265b]::result::Result<(), rustc_span[8b5f317805ba237c]::ErrorGuaranteed>, rustc_driver_impl[891cbe23e357ec56]::run_compiler::{closure#0}>::{closure#0}, core[2fd1802afb11265b]::result::Result<(), rustc_span[8b5f317805ba237c]::ErrorGuaranteed>>::{closure#2}::{closure#1}, ()>::{closure#1} as core[2fd1802afb11265b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:     0x7fe6065c3a85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h56f9dbf676dc2949
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/alloc/src/boxed.rs:2007:9
  22:     0x7fe6065c3a85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0aeb3b2beefea16d
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/alloc/src/boxed.rs:2007:9
  23:     0x7fe6065c3a85 - std::sys::unix::thread::Thread::new::thread_start::hef5a9ef6142ee84b
                               at /rustc/49b3924bd4a34d3cf9c37b74120fba78d9712ab8/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7fe6004aa9eb - <unknown>
  25:     0x7fe60052e7cc - <unknown>
  26:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/slevin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-webpki-0.101.7/rustc-ice-2023-12-02T10_21_05-25044.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debug-assertions=off -C strip=symbols -Z threads=8

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
deadlock handler panicked, aborting process
   Compiling http-body-util v0.1.0
   Compiling tower-http v0.5.0
error: could not compile `rustls-webpki` (lib)

Caused by:
  process didn't exit successfully: `/home/slevin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name webpki --edition=2021 /home/slevin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-webpki-0.101.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=89 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=03ff1356f0cc9632 -C extra-filename=-03ff1356f0cc9632 --out-dir /home/slevin/code/rust/server/target/release/deps -C strip=symbols -L dependency=/home/slevin/code/rust/server/target/release/deps --extern ring=/home/slevin/code/rust/server/target/release/deps/libring-9b9bfce7b0f2df34.rmeta --extern untrusted=/home/slevin/code/rust/server/target/release/deps/libuntrusted-a7547fc5a9712d8f.rmeta --cap-lints allow -Z threads=8 -L native=/home/slevin/code/rust/server/target/release/build/ring-d881db683f677f0f/out` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
```

### PR DESCRIPTION
**Pull request by andjo403**
Was abled to reproduce the deadlock in #118205 and created a coredump when it happen. When looking at the backtraces  I noticed that the prefetch of exported_symbols (Thread 17 frame 4) started after the "actual" exported_symbols (Thread 2 frame 18) but it also is working on some of the collect_crate_mono_items (Thread 17 frame12 ) that Thread 2 is blocked on resulting in a deadlock.

This PR results in less parallell work that can be done at the same time but from what I can find we do not call the query exported_symbols from multiple places in the same join call any more.

```
Thread 17 (Thread 0x7f87b6299700 (LWP 11370)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f87be5166a9 in <parking_lot::condvar::Condvar>::wait_until_internal () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#2  0x00007f87be12d854 in <rustc_query_system::query::job::QueryLatch>::wait_on () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#3  0x00007f87bd27d16f in rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::CrateNum, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#4  0x00007f87bd0b5b6a in rustc_query_impl::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#5  0x00007f87bdaebb0a in rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}::{closure#1} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#6  0x00007f87bdae1509 in rayon_core::join::join_context::call_b::<core::option::Option<rustc_data_structures::marker::FromDyn<&[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>, rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<&[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}::{closure#1}, (), &[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>::{closure#0}::{closure#1}>::{closure#0}>::{closure#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#7  0x00007f87bdae32ff in <rayon_core::job::StackJob<rayon_core::latch::SpinLatch, rayon_core::join::join_context::call_b<core::option::Option<rustc_data_structures::marker::FromDyn<&[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>, rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<&[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}::{closure#1}, (), &[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}, core::option::Option<rustc_data_structures::marker::FromDyn<&[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>> as rayon_core::job::Job>::execute () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#8  0x00007f87b8338823 in <rayon_core::registry::WorkerThread>::wait_until_cold () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#9  0x00007f87bc2edbaf in rayon_core::join::join_context::<rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, (), ()>::{closure#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#10 0x00007f87bc2ed313 in rayon_core::registry::in_worker::<rayon_core::join::join_context<rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, (), ()>::{closure#0}, ((), ())> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#11 0x00007f87bc2db2a4 in rayon::iter::plumbing::bridge_producer_consumer::helper::<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#12 0x00007f87bc2eead2 in <rayon_core::job::StackJob<rayon_core::latch::SpinLatch, rayon_core::join::join_context::call_b<(), rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}>::{closure#0}, ()> as rayon_core::job::Job>::execute () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#13 0x00007f87b8338823 in <rayon_core::registry::WorkerThread>::wait_until_cold () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#14 0x00007f87be52d1f9 in <rayon_core::registry::ThreadBuilder>::run () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#15 0x00007f87b8461c57 in <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}::{closure#0}, ()> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#16 0x00007f87b846e465 in rustc_span::set_session_globals_then::<(), rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}::{closure#0}> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#17 0x00007f87b844f282 in <<crossbeam_utils::thread::ScopedThreadBuilder>::spawn<<rayon_core::ThreadPoolBuilder>::build_scoped<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}, rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#18 0x00007f87b846af58 in <<std::thread::Builder>::spawn_unchecked_<alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send>, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#19 0x00007f87b7898e85 in std::sys::unix::thread::Thread::new::thread_start () from /home/andjo403/.rustup/toolchains/stage1/lib/libstd-d570b0650d35d951.so
#20 0x00007f87b7615609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f87b7755133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f87b729b700 (LWP 11368)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f87b7887b51 in std::sys::unix::locks::futex_condvar::Condvar::wait () from /home/andjo403/.rustup/toolchains/stage1/lib/libstd-d570b0650d35d951.so
#2  0x00007f87b8339478 in <rayon_core::sleep::Sleep>::sleep () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#3  0x00007f87b83387c3 in <rayon_core::registry::WorkerThread>::wait_until_cold () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#4  0x00007f87bc2edbaf in rayon_core::join::join_context::<rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, (), ()>::{closure#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#5  0x00007f87bc2ed313 in rayon_core::registry::in_worker::<rayon_core::join::join_context<rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#0}, rayon::iter::plumbing::bridge_producer_consumer::helper<rayon::vec::DrainProducer<rustc_middle::mir::mono::MonoItem>, rayon::iter::for_each::ForEachConsumer<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>::{closure#1}, (), ()>::{closure#0}, ((), ())> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#6  0x00007f87bc2db50c in <rayon::vec::IntoIter<rustc_middle::mir::mono::MonoItem> as rayon::iter::ParallelIterator>::for_each::<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#7  0x00007f87bc2e8cd7 in <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#8  0x00007f87bc2b8f2c in rustc_monomorphize::collector::collect_crate_mono_items () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#9  0x00007f87bc2c30d9 in rustc_monomorphize::partitioning::collect_and_partition_mono_items () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#10 0x00007f87bcf2cde6 in rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#11 0x00007f87bd156a3c in <rustc_query_impl::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#12 0x00007f87bd1c6a7d in rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#13 0x00007f87bd15df40 in rustc_query_impl::query_impl::collect_and_partition_mono_items::get_query_non_incr::__rust_end_short_backtrace () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#14 0x00007f87bd7a0ad9 in rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#15 0x00007f87bcf29acb in rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#16 0x00007f87bcfdb350 in <rustc_query_impl::query_impl::exported_symbols::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::CrateNum)>>::call_once () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#17 0x00007f87bd27d64f in rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::CrateNum, rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#18 0x00007f87bd0b5b6a in rustc_query_impl::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#19 0x00007f87bda927ce in rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::CrateNum, rustc_middle::query::erase::Erased<[u8; 16]>>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#20 0x00007f87bda9c93f in <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#21 0x00007f87bdaa6ef7 in rustc_metadata::rmeta::encoder::encode_metadata_impl () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#22 0x00007f87bdae0b77 in rayon_core::join::join_context::<rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<()>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}::{closure#0}>::{closure#0}, rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<()>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}::{closure#1}>::{closure#0}, core::option::Option<rustc_data_structures::marker::FromDyn<()>>, core::option::Option<rustc_data_structures::marker::FromDyn<()>>>::{closure#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#23 0x00007f87bdaded2f in rayon_core::registry::in_worker::<rayon_core::join::join_context<rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<()>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}::{closure#0}>::{closure#0}, rayon_core::join::join::call<core::option::Option<rustc_data_structures::marker::FromDyn<()>>, rustc_data_structures::sync::parallel::enabled::join<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>::{closure#0}::{closure#1}>::{closure#0}, core::option::Option<rustc_data_structures::marker::FromDyn<()>>, core::option::Option<rustc_data_structures::marker::FromDyn<()>>>::{closure#0}, (core::option::Option<rustc_data_structures::marker::FromDyn<()>>, core::option::Option<rustc_data_structures::marker::FromDyn<()>>)> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#24 0x00007f87bdaa5a03 in rustc_metadata::rmeta::encoder::encode_metadata () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#25 0x00007f87bdaed628 in rustc_metadata::fs::encode_and_write_metadata () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#26 0x00007f87b86608be in rustc_interface::passes::start_codegen () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#27 0x00007f87b8664946 in <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::codegen_and_build_linker::{closure#0}, core::result::Result<rustc_interface::queries::Linker, rustc_span::ErrorGuaranteed>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#28 0x00007f87b864db00 in <rustc_interface::queries::Queries>::codegen_and_build_linker () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#29 0x00007f87b849400f in <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#30 0x00007f87b846e067 in rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}::{closure#0}> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#31 0x00007f87b844dc13 in <rayon_core::thread_pool::ThreadPool>::install::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#32 0x00007f87b84509a1 in <rayon_core::job::StackJob<rayon_core::latch::LatchRef<rayon_core::latch::LockLatch>, <rayon_core::registry::Registry>::in_worker_cold<<rayon_core::thread_pool::ThreadPool>::install<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>> as rayon_core::job::Job>::execute () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#33 0x00007f87b8338823 in <rayon_core::registry::WorkerThread>::wait_until_cold () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#34 0x00007f87be52d1f9 in <rayon_core::registry::ThreadBuilder>::run () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#35 0x00007f87b8461c57 in <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}::{closure#0}, ()> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#36 0x00007f87b846e465 in rustc_span::set_session_globals_then::<(), rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}::{closure#0}> () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#37 0x00007f87b844f282 in <<crossbeam_utils::thread::ScopedThreadBuilder>::spawn<<rayon_core::ThreadPoolBuilder>::build_scoped<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}, rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#38 0x00007f87b846af58 in <<std::thread::Builder>::spawn_unchecked_<alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send>, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} () from /home/andjo403/.rustup/toolchains/stage1/lib/librustc_driver-70ddb84e8f7ce707.so
#39 0x00007f87b7898e85 in std::sys::unix::thread::Thread::new::thread_start () from /home/andjo403/.rustup/toolchains/stage1/lib/libstd-d570b0650d35d951.so
#40 0x00007f87b7615609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#41 0x00007f87b7755133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

fixes #118205
fixes #117759 from the latest logs it is the same query map as in #118205
fixes #118529
fixes #117784
cc #118206

r? @SparrowLii

### CODE REVIEW

**Comment by SparrowLii** [comment]
Thanks! We can now know that the waiting on stolen work (`expert_symbols`) while holding the lock of `collect_and_partition_mono_items` cauing the deadlock

Could you change the threads option in `rustc_seesion::options.rs` to 8 so that we can have a perf test?
```
collect_and_partition_mono_items
```

**Comment by 0xdeafbeef** [comment]
I've tested #117759 for 1 hour, no issues. Previous version always deadlocked under 5 minutes

**Comment by SparrowLii** [comment]
@andjo403  Thanks!

**Comment by lnicola** [comment]
CC https://github.com/rust-lang/rust/pull/118597

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 1]
```diff
@@ -2193,21 +2192,13 @@ pub fn encode_metadata(tcx: TyCtxt<'_>, path: &Path) {
     // there's no need to do dep-graph tracking for any of it.
     tcx.dep_graph.assert_ignored();
 
-    join(
```
Comment (Zoxc) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:2196]: I would strongly prefer this be changed to use `disabled::join` so it could be easily reverted.
