### PR TITLE
On fmt string with unescaped `{` note how to escape

### LINKED ISSUE #34300: fmt family macros should report better error for "{"
During tutorial, a student wanted to print out a `{` in the std output.

Their intuitive way of doing this yielded a non-ideal error message:

``` rust
fn main() {
    println!("{");
}
```

Error message:

```
error: invalid format string: expected `'}'` but string was terminated
 --> <std macros>:1:33
1 |> ( $ fmt : expr ) => ( print ! ( concat ! ( $ fmt , "\n" ) ) ) ; (
  |>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
<std macros>:1:33: 1:58: note: in this expansion of concat!
<std macros>:1:33: 1:58: note: in this expansion of format_args!
<std macros>:1:33: 1:58: note: in this expansion of print! (defined in <std macros>)
<std macros>:1:33: 1:58: note: in this expansion of println! (defined in <std macros>)

error: aborting due to previous error
```

The student knew that they wanted _some_ kind of escape sequence, but did not know what to use (e.g. they tried e.g. `\{`, which does not work).

Ideally we would include a HELP output that would suggest that if an output `{` were desired, then one should instead write `{{`.

### PR DESCRIPTION
**Pull request by estebank**
On cases of malformed format strings where a `{` hasn't been properly escaped, like `println!("{");`, present a NOTE explaining how to escape the `{` char.

Fix #34300.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks!

Could you be sure to add a ui test for this case as well?

**Comment by estebank** [comment]
@alexcrichton added NOTE for `}` and a ui test for both cases.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

File: src/libfmt_macros/lib.rs [hunk 1]
```diff
@@ -165,7 +165,9 @@ impl<'a> Iterator for Parser<'a> {
                     if self.consume('}') {
                         Some(String(self.string(pos + 1)))
                     } else {
-                        self.err("unmatched `}` found");
+                        self.err_with_note("unmatched `}` found",
+                                           "if you intended to print `}`, \
+                                           can you escape it using `}}`");
```
Comment (brson) [inline src/libfmt_macros/lib.rs]: "can you" -> "you can"

File: src/libfmt_macros/lib.rs [hunk 2]
```diff
@@ -222,7 +231,13 @@ impl<'a> Parser<'a> {
                 self.err(&format!("expected `{:?}`, found `{:?}`", c, maybe));
             }
         } else {
-            self.err(&format!("expected `{:?}` but string was terminated", c));
+            let msg = &format!("expected `{:?}` but string was terminated", c);
+            if c == '}' {
+                self.err_with_note(msg,
+                                   "if you intended to print `{`, can you escape it using `{{`");
```
Comment (brson) [inline src/libfmt_macros/lib.rs]: Ditto. "can you" -> "you can"

**Comment by alexcrichton** [comment]
@bors: r-

(waiting for changes)

**Comment by estebank** [comment]
@brson @alexcrichton fixed.
