### PR TITLE
Fix `emit_unused_delims_expr` ICE

### LINKED ISSUE #104897: ICE: Found a `push` without a `pop` / Span must not be empty and have no suggestion
### Code

```Rust
// Tests that the compiler does not try to create a span
// which points in the middle of a multibyte character.

fn f(){(print!(á
```
note: no newline at end of code

### Meta

`rustc --version --verbose`:
```
8a75c5a9b5d9c48aa576b08faf735b926d0d9a71
```

### Error output

```
error: this file contains an unclosed delimiter
 --> ./icemaker_87924.rs:4:17
  |
4 | fn f(){(print!(á
  |       --      - ^
  |       ||      |
  |       ||      unclosed delimiter
  |       |unclosed delimiter
  |       unclosed delimiter

error: format argument must be a string literal
 --> ./icemaker_87924.rs:4:16
  |
4 | fn f(){(print!(á
  |                ^
  |
help: you might be missing a string literal to format with
  |
4 | fn f(){(print!("{}", á
  |                +++++
```

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #104897 

This is also related to #104433.

### CODE REVIEW

File: compiler/rustc_lint/src/unused.rs [hunk 1]
```diff
@@ -636,13 +636,26 @@ trait UnusedDelimLint {
...
+                if let ExprKind::Err = expr.kind {
+                    self.has_error = true;
+                    return;
+                }
+                walk_expr(self, expr)
+            }
+        }
+        let mut visitor = ErrExprVisitor { has_error: false };
+        visitor.visit_expr(value);
+        if visitor.has_error {
```
Comment (wesleywiser) [inline compiler/rustc_lint/src/unused.rs:654]: Can you leave a comment here explaining why we do this check?

Comment (TaKO8Ki) [reply compiler/rustc_lint/src/unused.rs:662]: I have left a comment.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @TaKO8Ki! 

@bors r+
