### PR TITLE
Don't crash when reporting nice region errors for generic const items

### LINKED ISSUE #114714: ICE: generic_const_items: error_reporting/nice_region_error/util.rs: called `Option::unwrap()` on a `None` value
The code below

```rs
#![feature(generic_const_items)]
#![allow(incomplete_features)]

struct S<'a>(&'a ());

impl<'a> S<'a> {
    const K<'b>: &'a &'b () = &&();
}

fn main() {}
```

leads to the following compiler panic

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs:67:51:
called `Option::unwrap()` on a `None` value
```

<details><summary>full stderr</summary>

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs:67:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f1f6076451c - std::backtrace_rs::backtrace::libunwind::trace::h5d46195f7fad7731
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f6076451c - std::backtrace_rs::backtrace::trace_unsynchronized::hf7e15a8e305d2b88
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f6076451c - std::sys_common::backtrace::_print_fmt::he632c2b35eb52a4a
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1f6076451c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff14b53c6a93074f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1f607c9bec - core::fmt::rt::Argument::fmt::hbc860881e8ce3346
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/rt.rs:138:9
   5:     0x7f1f607c9bec - core::fmt::write::hfb9fb4b4780237e3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f1f607570ce - std::io::Write::write_fmt::hfc672d2c941c8ed9
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/io/mod.rs:1714:15
   7:     0x7f1f60764304 - std::sys_common::backtrace::_print::h3b9e9081d432f6f4
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1f60764304 - std::sys_common::backtrace::print::he0d42604133364c3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1f607673fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::hc5b2fe53f8842f32
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:278:22
  10:     0x7f1f607670e7 - std::panicking::panic_hook_with_disk_dump::hfdace7e0175e956f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:312:9
  11:     0x7f1f63943579 - <rustc_driver_impl[4d4d356dddeac37d]::install_ice_hook::{closure#0} as core[96f202313c1833a4]::ops::function::FnOnce<(&core[96f202313c1833a4]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f1f60767ca0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h363634fa38d877e5
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2021:9
  13:     0x7f1f60767ca0 - std::panicking::rust_panic_with_hook::h424df369cae5917d
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:733:13
  14:     0x7f1f607679e1 - std::panicking::begin_panic_handler::{{closure}}::h4df25d449bdadcbb
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:619:13
  15:     0x7f1f60764a46 - std::sys_common::backtrace::__rust_end_short_backtrace::hcd5a9509c25bef98
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f1f60767772 - rust_begin_unwind
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:617:5
  17:     0x7f1f607c5ff3 - core::panicking::panic_fmt::h4951da84d1ce8795
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:67:14
  18:     0x7f1f607c6083 - core::panicking::panic::h6412d3e771bd807b
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:117:5
  19:     0x7f1f63cb6006 - rustc_infer[fadbb4b7a5f60298]::infer::error_reporting::nice_region_error::util::find_param_with_region
  20:     0x7f1f63c80b69 - <rustc_infer[fadbb4b7a5f60298]::infer::error_reporting::nice_region_error::NiceRegionError>::try_report_from_nll
  21:     0x7f1f63c81e8a - <rustc_infer[fadbb4b7a5f60298]::infer::error_reporting::nice_region_error::NiceRegionError>::try_report
  22:     0x7f1f63c2fd15 - <rustc_infer[fadbb4b7a5f60298]::infer::error_reporting::TypeErrCtxt>::try_report_nice_region_error
  23:     0x7f1f63c30cc6 - <rustc_infer[fadbb4b7a5f60298]::infer::error_reporting::TypeErrCtxt>::report_region_errors
  24:     0x7f1f61c41fe3 - <rustc_trait_selection[18a936dade2ae92e]::traits::engine::ObligationCtxt>::resolve_regions_and_report_errors
  25:     0x7f1f61c3e34a - rustc_hir_analysis[4937c6c3bdf3702e]::check::wfcheck::check_associated_item
  26:     0x7f1f61c35d83 - rustc_hir_analysis[4937c6c3bdf3702e]::check::wfcheck::check_well_formed
  27:     0x7f1f619f527c - rustc_query_impl[ee6657652100ef69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee6657652100ef69]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 0usize]>>
  28:     0x7f1f6233dd17 - rustc_query_system[4db594f5631945b9]::query::plumbing::try_execute_query::<rustc_query_impl[ee6657652100ef69]::DynamicConfig<rustc_query_system[4db594f5631945b9]::query::caches::VecCache<rustc_hir[d4644c4accaa6910]::hir_id::OwnerId, rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ee6657652100ef69]::plumbing::QueryCtxt, false>
  29:     0x7f1f6233da32 - rustc_query_impl[ee6657652100ef69]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f1f62d77ca0 - rustc_data_structures[8542b87e3ccd0577]::sync::par_for_each_in::<&[rustc_hir[d4644c4accaa6910]::hir::ItemId], <rustc_middle[e5f5d2644997b7cd]::hir::ModuleItems>::par_items<rustc_hir_analysis[4937c6c3bdf3702e]::check::wfcheck::check_mod_type_wf::{closure#0}>::{closure#0}>
  31:     0x7f1f62d77b4b - rustc_hir_analysis[4937c6c3bdf3702e]::check::wfcheck::check_mod_type_wf
  32:     0x7f1f625dde3c - rustc_query_impl[ee6657652100ef69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee6657652100ef69]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 0usize]>>
  33:     0x7f1f625dde1e - <rustc_query_impl[ee6657652100ef69]::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core[96f202313c1833a4]::ops::function::FnOnce<(rustc_middle[e5f5d2644997b7cd]::ty::context::TyCtxt, rustc_span[39b2b2176e7b96c]::def_id::LocalDefId)>>::call_once
  34:     0x7f1f6226c1ef - rustc_query_system[4db594f5631945b9]::query::plumbing::try_execute_query::<rustc_query_impl[ee6657652100ef69]::DynamicConfig<rustc_query_system[4db594f5631945b9]::query::caches::VecCache<rustc_span[39b2b2176e7b96c]::def_id::LocalDefId, rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ee6657652100ef69]::plumbing::QueryCtxt, false>
  35:     0x7f1f632bb242 - rustc_query_impl[ee6657652100ef69]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f1f62e18313 - rustc_data_structures[8542b87e3ccd0577]::sync::par_for_each_in::<&[rustc_hir[d4644c4accaa6910]::hir_id::OwnerId], <rustc_middle[e5f5d2644997b7cd]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[4937c6c3bdf3702e]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  37:     0x7f1f62e1751d - rustc_hir_analysis[4937c6c3bdf3702e]::check_crate
  38:     0x7f1f62e11c2a - rustc_interface[8444e632155de289]::passes::analysis
  39:     0x7f1f62e4677a - rustc_query_impl[ee6657652100ef69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ee6657652100ef69]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 1usize]>>
  40:     0x7f1f62e46769 - <rustc_query_impl[ee6657652100ef69]::query_impl::analysis::dynamic_query::{closure#2} as core[96f202313c1833a4]::ops::function::FnOnce<(rustc_middle[e5f5d2644997b7cd]::ty::context::TyCtxt, ())>>::call_once
  41:     0x7f1f62fe5108 - rustc_query_system[4db594f5631945b9]::query::plumbing::try_execute_query::<rustc_query_impl[ee6657652100ef69]::DynamicConfig<rustc_query_system[4db594f5631945b9]::query::caches::SingleCache<rustc_middle[e5f5d2644997b7cd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ee6657652100ef69]::plumbing::QueryCtxt, false>
  42:     0x7f1f62fe4e97 - rustc_query_impl[ee6657652100ef69]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7f1f62fb1cf6 - <rustc_middle[e5f5d2644997b7cd]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>
  44:     0x7f1f62bf31c1 - rustc_span[39b2b2176e7b96c]::set_source_map::<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  45:     0x7f1f62bed6b0 - std[74ebca3ea22cf768]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>
  46:     0x7f1f631b9c05 - <<std[74ebca3ea22cf768]::thread::Builder>::spawn_unchecked_<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#1} as core[96f202313c1833a4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8efd040eb8799637
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  48:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6dc930f82eaf8f03
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  49:     0x7f1f607722d5 - std::sys::unix::thread::Thread::new::thread_start::h431d431baf503985
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys/unix/thread.rs:108:17
  50:     0x7f1f60505bb5 - <unknown>
  51:     0x7f1f60587d90 - <unknown>
  52:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/fmease/programming/rust/playground/rustc-ice-2023-08-10T22:25:37.727601658Z-2659019.txt` to your bug report

query stack during panic:
#0 [check_well_formed] checking that `<impl at oh.rs:6:1: 6:15>::K` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at compiler/rustc_errors/src/lib.rs:1741:53:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f1f6076451c - std::backtrace_rs::backtrace::libunwind::trace::h5d46195f7fad7731
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f6076451c - std::backtrace_rs::backtrace::trace_unsynchronized::hf7e15a8e305d2b88
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f6076451c - std::sys_common::backtrace::_print_fmt::he632c2b35eb52a4a
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1f6076451c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff14b53c6a93074f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1f607c9bec - core::fmt::rt::Argument::fmt::hbc860881e8ce3346
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/rt.rs:138:9
   5:     0x7f1f607c9bec - core::fmt::write::hfb9fb4b4780237e3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f1f607570ce - std::io::Write::write_fmt::hfc672d2c941c8ed9
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/io/mod.rs:1714:15
   7:     0x7f1f60764304 - std::sys_common::backtrace::_print::h3b9e9081d432f6f4
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1f60764304 - std::sys_common::backtrace::print::he0d42604133364c3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1f607673fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::hc5b2fe53f8842f32
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:278:22
  10:     0x7f1f607670e7 - std::panicking::panic_hook_with_disk_dump::hfdace7e0175e956f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:312:9
  11:     0x7f1f63943579 - <rustc_driver_impl[4d4d356dddeac37d]::install_ice_hook::{closure#0} as core[96f202313c1833a4]::ops::function::FnOnce<(&core[96f202313c1833a4]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f1f60767ca0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h363634fa38d877e5
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2021:9
  13:     0x7f1f60767ca0 - std::panicking::rust_panic_with_hook::h424df369cae5917d
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:733:13
  14:     0x7f1f607679e1 - std::panicking::begin_panic_handler::{{closure}}::h4df25d449bdadcbb
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:619:13
  15:     0x7f1f60764a46 - std::sys_common::backtrace::__rust_end_short_backtrace::hcd5a9509c25bef98
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f1f60767772 - rust_begin_unwind
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:617:5
  17:     0x7f1f607c5ff3 - core::panicking::panic_fmt::h4951da84d1ce8795
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:67:14
  18:     0x7f1f607c6083 - core::panicking::panic::h6412d3e771bd807b
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:117:5
  19:     0x7f1f62f1fbc1 - <rustc_errors[8914fb86eeea6fa9]::HandlerInner>::flush_delayed::<alloc[70707fba2e9ef5ce]::vec::Vec<rustc_errors[8914fb86eeea6fa9]::DelayedDiagnostic>, &str>
  20:     0x7f1f62f1ea19 - <rustc_errors[8914fb86eeea6fa9]::HandlerInner as core[96f202313c1833a4]::ops::drop::Drop>::drop
  21:     0x7f1f62fab80b - core[96f202313c1833a4]::ptr::drop_in_place::<rustc_session[11d3db38886df5a0]::parse::ParseSess>
  22:     0x7f1f62fa8335 - core[96f202313c1833a4]::ptr::drop_in_place::<rustc_session[11d3db38886df5a0]::session::Session>
  23:     0x7f1f62bf463c - core[96f202313c1833a4]::ptr::drop_in_place::<rustc_interface[8444e632155de289]::interface::Compiler>
  24:     0x7f1f62bf3f11 - rustc_span[39b2b2176e7b96c]::set_source_map::<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  25:     0x7f1f62bed6b0 - std[74ebca3ea22cf768]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>
  26:     0x7f1f631b9c05 - <<std[74ebca3ea22cf768]::thread::Builder>::spawn_unchecked_<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#1} as core[96f202313c1833a4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8efd040eb8799637
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  28:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6dc930f82eaf8f03
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  29:     0x7f1f607722d5 - std::sys::unix::thread::Thread::new::thread_start::h431d431baf503985
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7f1f60505bb5 - <unknown>
  31:     0x7f1f60587d90 - <unknown>
  32:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/fmease/programming/rust/playground/rustc-ice-2023-08-10T22:25:37.727601658Z-2659019.txt` to your bug report

query stack during panic:
end of query stack
thread 'rustc' panicked at library/core/src/panicking.rs:126:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7f1f6076451c - std::backtrace_rs::backtrace::libunwind::trace::h5d46195f7fad7731
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f6076451c - std::backtrace_rs::backtrace::trace_unsynchronized::hf7e15a8e305d2b88
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f6076451c - std::sys_common::backtrace::_print_fmt::he632c2b35eb52a4a
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1f6076451c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff14b53c6a93074f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1f607c9bec - core::fmt::rt::Argument::fmt::hbc860881e8ce3346
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/rt.rs:138:9
   5:     0x7f1f607c9bec - core::fmt::write::hfb9fb4b4780237e3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f1f607570ce - std::io::Write::write_fmt::hfc672d2c941c8ed9
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/io/mod.rs:1714:15
   7:     0x7f1f60764304 - std::sys_common::backtrace::_print::h3b9e9081d432f6f4
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1f60764304 - std::sys_common::backtrace::print::he0d42604133364c3
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1f607673fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::hc5b2fe53f8842f32
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:278:22
  10:     0x7f1f607670e7 - std::panicking::panic_hook_with_disk_dump::hfdace7e0175e956f
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:312:9
  11:     0x7f1f63943579 - <rustc_driver_impl[4d4d356dddeac37d]::install_ice_hook::{closure#0} as core[96f202313c1833a4]::ops::function::FnOnce<(&core[96f202313c1833a4]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f1f60767ca0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h363634fa38d877e5
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2021:9
  13:     0x7f1f60767ca0 - std::panicking::rust_panic_with_hook::h424df369cae5917d
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:733:13
  14:     0x7f1f607679e1 - std::panicking::begin_panic_handler::{{closure}}::h4df25d449bdadcbb
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:619:13
  15:     0x7f1f60764a46 - std::sys_common::backtrace::__rust_end_short_backtrace::hcd5a9509c25bef98
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f1f60767772 - rust_begin_unwind
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/panicking.rs:617:5
  17:     0x7f1f607c6033 - core::panicking::panic_nounwind_fmt::h8ddccd1f521fab18
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:96:14
  18:     0x7f1f607c60d7 - core::panicking::panic_nounwind::h0c3fcbf1f3701a77
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:126:5
  19:     0x7f1f607c6253 - core::panicking::panic_cannot_unwind::hfe1ed8e826fb549b
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/core/src/panicking.rs:189:5
  20:     0x7f1f62bf3f50 - rustc_span[39b2b2176e7b96c]::set_source_map::<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  21:     0x7f1f62bed6b0 - std[74ebca3ea22cf768]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>
  22:     0x7f1f631b9c05 - <<std[74ebca3ea22cf768]::thread::Builder>::spawn_unchecked_<rustc_interface[8444e632155de289]::util::run_in_thread_pool_with_globals<rustc_interface[8444e632155de289]::interface::run_compiler<core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>, rustc_driver_impl[4d4d356dddeac37d]::run_compiler::{closure#1}>::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[96f202313c1833a4]::result::Result<(), rustc_span[39b2b2176e7b96c]::ErrorGuaranteed>>::{closure#1} as core[96f202313c1833a4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  23:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8efd040eb8799637
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  24:     0x7f1f607722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6dc930f82eaf8f03
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/alloc/src/boxed.rs:2007:9
  25:     0x7f1f607722d5 - std::sys::unix::thread::Thread::new::thread_start::h431d431baf503985
                               at /rustc/faee636ebfff793ea9dcff17960a611b580e3cd5/library/std/src/sys/unix/thread.rs:108:17
  26:     0x7f1f60505bb5 - <unknown>
  27:     0x7f1f60587d90 - <unknown>
  28:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/fmease/programming/rust/playground/rustc-ice-2023-08-10T22:25:37.727601658Z-2659019.txt` to your bug report

query stack during panic:
end of query stack
thread caused non-unwinding panic. aborting.
[1]    2659019 IOT instruction (core dumped)  rustc +faee636ebfff793ea9dcff17960a611b580e3cd5 oh.rs
```

</details>

<details><summary><code>rustc -Vv</code></summary>

```
rustc 1.73.0-nightly (faee636eb 2023-08-10)
binary: rustc
commit-hash: faee636ebfff793ea9dcff17960a611b580e3cd5
commit-date: 2023-08-10
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 17.0.0
```

</details>

@rustbot label -needs-triage C-bug I-ICE T-compiler F-generic_const_items requires-incomplete-features
@rustbot claim

### PR DESCRIPTION
**Pull request by fmease**
Fixes #114714.

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/named_anon_conflict.rs [hunk 1]
```diff
@@ -29,25 +29,15 @@ impl<'a, 'tcx> NiceRegionError<'a, 'tcx> {
...
+            && let Some(region_info) = self.tcx().is_suitable_region(sub)
+            && let Some(anon_param_info) = self.find_param_with_region(sub, sup)
         {
-            (
-                sup,
-                sub,
-                self.find_param_with_region(sub, sup).unwrap(),
-                self.tcx().is_suitable_region(sub).unwrap(),
-            )
+            (sup, sub, anon_param_info, region_info)
```
Comment (fmease) [inline compiler/rustc_infer/src/infer/error_reporting/nice_region_error/named_anon_conflict.rs:40]: This is just a refactoring to get rid of the `.unwrap()`s. Let-chains <3

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs [hunk 2]
```diff
@@ -64,7 +64,7 @@ pub fn find_param_with_region<'tcx>(
     let body_id = hir.maybe_body_owned_by(def_id)?;
 
     let owner_id = hir.body_owner(body_id);
-    let fn_decl = hir.fn_decl_by_hir_id(owner_id).unwrap();
+    let fn_decl = hir.fn_decl_by_hir_id(owner_id)?;
```
Comment (fmease) [inline compiler/rustc_infer/src/infer/error_reporting/nice_region_error/util.rs:67]: At this point in time we might also have parametrized const item, not just a function declaration. Thus, don't unwrap but just bail out (`find_param_with_region` is only applicable to functions).

**Comment by cjgillot** [comment]
Thanks.
@bors r+ rollup
