### PR TITLE
Pretty print `Fn<(..., ...)>` trait refs with parentheses (almost) always

### LINKED ISSUE #118225: Incorrect syntax when suggesting the use of `Fn*` traits as supertraits
### Code

```Rust
`
Box<dyn Fn(Vec<AstValueExpr>)->AstValueExpr + Clone>
`
```

### Current output

```Shell
The diagnosis suggests writing this code:
only auto traits can be used as additional traits in a trait object
consider creating a new trait with all of these as supertraits and using that trait here instead: `trait NewTrait: Fn<(Vec<AstValueExpr>, )>+ Clone {}`
```

### Desired output

```Shell
However, the use of `Fn*` series traits should be used as `Fn(Vec<AstValueExpr>)`, that is, the correct suggestion should be `trait NewTrait: Fn(Vec<AstValueExpr>)->AstValueExpr + Clone{}`
```

### Rationale and extra context

740b75e08f494fe8171bd7b920361a47

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compiler-errors**
It's almost always better, at least in diagnostics, to print `Fn(i32, u32)` instead of `Fn<(i32, u32)>`.

Related to but doesn't fix #118225. That needs a separate fix.

### CODE REVIEW

File: src/tools/clippy/clippy_lints/src/future_not_send.rs [hunk 1]
```diff
@@ -99,7 +99,7 @@ impl<'tcx> LateLintPass<'tcx> for FutureNotSend {
                                     db.note(format!(
                                         "`{}` doesn't implement `{}`",
                                         trait_pred.self_ty(),
-                                        trait_pred.trait_ref.print_only_trait_path(),
+                                        trait_pred.trait_ref.print_trait_sugared(),
```
Comment (compiler-errors) [inline src/tools/clippy/clippy_lints/src/future_not_send.rs:102]: I guess this doesn't matter -- can revert. I actually don't even know why this uses `print_only_trait_path`, given that it's always `Send`.

Comment (estebank) [reply src/tools/clippy/clippy_lints/src/future_not_send.rs:102]: It's likely copy-pasted from a more general rustc error.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 2]
```diff
@@ -1181,10 +1181,7 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
                 if let Some(bound_span) = bound_span {
                     err.span_label(
                         bound_span,
-                        format!(
-                            "ambiguous `{assoc_name}` from `{}`",
-                            bound.print_only_trait_path(),
-                        ),
+                        format!("ambiguous `{assoc_name}` from `{}`", bound.print_trait_sugared(),),
```
Comment (estebank) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:1184]:
```suggestion
                        format!("ambiguous `{assoc_name}` from `{}`", bound.print_trait_sugared()),
```

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:1184]: We have a lot of these :(

I ctrl+f'd for `,);` and `,),` yesterday and found like >50 instances.

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs [hunk 3]
```diff
@@ -184,14 +184,7 @@ impl<'tcx> TypeErrCtxtExt<'tcx> for TypeErrCtxt<'_, 'tcx> {
...
 
-        if let Some(kind) = self.tcx.fn_trait_kind_from_def_id(trait_ref.def_id)
-            && let ty::Tuple(args) = trait_ref.args.type_at(1).kind()
-        {
-            let args = args.iter().map(|ty| ty.to_string()).collect::<Vec<_>>().join(", ");
-            flags.push((sym::Trait, Some(format!("{}({args})", kind.as_str()))));
-        } else {
-            flags.push((sym::Trait, Some(trait_ref.print_only_trait_path().to_string())));
-        }
+        flags.push((sym::Trait, Some(trait_ref.print_trait_sugared().to_string())));
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:187]: Have you checked all the `rustc_on_unimplemented` that reference `Trait` in their filters? Probably just the ones in the definitions for `Fn`, `FnOnce` and `FnMut` in particular.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 4]
```diff
@@ -2844,6 +2870,24 @@ define_print_and_forward_display! {
...
+                if i > 0 {
+                    p!(", ");
+                }
+                p!(print(arg));
+            }
+            p!(")");
+        } else {
+            p!(print_def_path(self.0.def_id, self.0.args));
+        }
+    }
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/print/pretty.rs:2889]: This will never print the `Output`, is that ok?

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 5]
```diff
@@ -2844,6 +2870,24 @@ define_print_and_forward_display! {
         p!(print_def_path(self.0.def_id, self.0.args));
     }
 
+    TraitRefPrintSugared<'tcx> {
+        if !with_no_queries()
+            && let Some(kind) = cx.tcx().fn_trait_kind_from_def_id(self.0.def_id)
+            && let ty::Tuple(args) = self.0.args.type_at(1).kind()
+        {
+            p!(write("{}", kind.as_str()), "(");
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/print/pretty.rs:2878]: This interacts as expected with the `trim`/`dont_trim` macros, right? (Don't see why they wouldn't)

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:187]: Yes, this PR should be a no-op, since it just generalizes the behavior that I replaced here.

I'm also the one that introduced `sym::Trait`, so I know that it's probably not gonna affect anything.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 6]
```diff
@@ -2666,6 +2687,10 @@ impl<'tcx> ty::Binder<'tcx, ty::TraitRef<'tcx>> {
     pub fn print_only_trait_path(self) -> ty::Binder<'tcx, TraitRefPrintOnlyTraitPath<'tcx>> {
         self.map_bound(|tr| tr.print_only_trait_path())
     }
+
+    pub fn print_trait_sugared(self) -> ty::Binder<'tcx, TraitRefPrintSugared<'tcx>> {
+        self.map_bound(|tr| tr.print_trait_sugared())
+    }
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/print/pretty.rs:2693]: Should we not just have made this part of `print_only_trait_path`?

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/print/pretty.rs:2889]: There's no `Output` that we have access to, unfortunately :/

**Review by estebank — APPROVED** [review]

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 5 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/print/pretty.rs:2878]: It should, since those are global flags

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_middle/src/ty/print/pretty.rs:2889]: Didn't we hack something together for `Future::Output` somewhere?

File: compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/on_unimplemented.rs:187]: Ah, yeah, didn't realize that. Awesome.

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 6 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/print/pretty.rs:2693]: `print_only_trait_path` is used in other places where the suggestion would be misleading or syntactically incorrect. Basically any place where the printed trait ref would be used in a structured suggestion.

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_middle/src/ty/print/pretty.rs:2889]: If you manage it, great. If not, r=me.

**Comment by fmease** [comment]
Actually, I wonder if we shoul print `Fn<(…,)>` as `Fn(…,) -> _` instead of `Fn(…,)` since that's closer to its actual meaning. The latter (which this PR has implemented) looks like `Fn<(…,), Output = ()>` to me.
