### PR TITLE
Move various checks to typeck so them failing causes the typeck result to get tainted

### LINKED ISSUE #69487: ICE: The type checker should prevent reading from a never-written local
I tried this code:

```rust
#![feature(const_trait_impl)]
#![feature(fn_traits)]
#![feature(unboxed_closures)]

struct Closure;

impl const FnOnce<&usize> for Closure {
    type Output = usize;
    
    extern "rust-call" fn call_once(self, arg: &usize) -> Self::Output {
        *arg
    }
}

enum Bug<T = [(); Closure.call_once(&0) ]> {
    V(T),
}
```

I expected to see this happen: Maybe it should've compiled? Maybe it should've just emitted an error explaining I did something wrong?

Instead, this happened: It crashed!

### Meta

`rustc --version --verbose`:
```
1.43.0-nightly (6fd8798f4 2020-02-25)
```

<details><summary>Backtrace</summary>
<p>

```
error: internal compiler error: src/librustc_mir/interpret/eval_context.rs:143: The type checker should prevent reading from a never-written local

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:881:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::access_local
  21: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_place_to_op
  22: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_operand
  23: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
  24: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
  25: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  26: rustc::ty::query::__query_compute::const_eval_raw
  27: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval_raw>::compute
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  30: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  31: rustc::ty::query::__query_compute::const_eval_validated
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval_validated>::compute
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  36: rustc::ty::query::__query_compute::const_eval_validated
  37: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval_validated>::compute
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc::mir::interpret::queries::<impl rustc::ty::context::TyCtxt>::const_eval_resolve
  41: rustc::ty::sty::Const::eval::{{closure}}
  42: <rustc_infer::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_const
  43: <rustc_infer::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_ty
  44: rustc::ty::fold::TypeFoldable::fold_with
  45: rustc::ty::fold::TypeFoldable::fold_with
  46: rustc_infer::traits::project::normalize
  47: rustc_infer::infer::InferCtxt::partially_normalize_associated_types_in
  48: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  49: rustc_typeck::check::wfcheck::check_where_clauses
  50: rustc::ty::context::GlobalCtxt::enter_local
  51: rustc_typeck::check::wfcheck::check_item_well_formed
  52: rustc::ty::query::__query_compute::check_item_well_formed
  53: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::check_item_well_formed>::compute
  54: rustc::dep_graph::graph::DepGraph::with_task_impl
  55: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  56: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query
  57: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  58: rustc_data_structures::sync::par_for_each_in
  59: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  60: rustc_hir::hir::Crate::par_visit_all_item_likes
  61: rustc_typeck::check_crate
  62: rustc_interface::passes::analysis
  63: rustc::ty::query::__query_compute::analysis
  64: rustc::dep_graph::graph::DepGraph::with_task_impl
  65: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  66: rustc::ty::context::tls::enter_global
  67: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (6fd8798f4 2020-02-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [const_eval_raw] const-evaluating `Bug::{{constant}}#0`
#1 [const_eval_validated] const-evaluating + checking `Bug::{{constant}}#0`
#2 [const_eval_validated] const-evaluating + checking `Bug::{{constant}}#0`
#3 [check_item_well_formed] processing `Bug`
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

```

</p>
</details>

### LINKED ISSUE #79047: Constant gets evaluated even when it contains invalid `transmute`
Consider the following code:
```rust
const DST: &[u8] = unsafe { std::mem::transmute(1usize) };

fn main() {
    match &b""[..] {
        DST => {}
    }
}
```
This code hits a peculiar code path in the interpreter:

https://github.com/rust-lang/rust/blob/30e49a9ead550551e879af64ba91a0316da1c422/compiler/rustc_mir/src/interpret/place.rs#L916-L927

This code path *should* be unreachable: just like the interpreter can assume that code code it runs on is well-typed, it should be able to assume that the code it runs on has its transmutes checked. But something seems to be different about `transmute` when compared with "normal" type-checking.

`TransmuteSizeDiff` is a hack; we should instead arrange things in a way that failing the transmute check inhibits const-evaluation the same way that `true + 4` inhibitis const-evaluation.

### PR DESCRIPTION
**Pull request by oli-obk**
Fixes #69487
fixes #79047

cc @RalfJung this gets rid of the `Transmute` invalid program error variant

### CODE REVIEW

File: compiler/rustc_middle/src/mir/interpret/error.rs [hunk 1]
```diff
@@ -148,8 +148,6 @@ pub enum InvalidProgramInfo<'tcx> {
     /// (which unfortunately typeck does not reject).
     /// Not using `FnAbiError` as that contains a nested `LayoutError`.
     FnAbiAdjustForForeignAbi(call::AdjustForForeignAbiError),
-    /// An invalid transmute happened.
-    TransmuteSizeDiff(Ty<'tcx>, Ty<'tcx>),
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/error.rs:152]: That's great. :D So does this also fix https://github.com/rust-lang/rust/issues/79047 ?

What about `SizeOfUnsizedType`, which seems similar to me?

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 2]
```diff
@@ -911,12 +911,12 @@ where
             // array length computation, `typeck` may not have yet been run and errored out. In fact
             // most likely we *are* running `typeck` right now. Investigate whether we can bail out
             // on `typeck_results().has_errors` at all const eval entry points.
-            debug!("Size mismatch when transmuting!\nsrc: {:#?}\ndest: {:#?}", src, dest);
-            self.tcx.sess.delay_span_bug(
+            span_bug!(
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/place.rs:914]: I think the FIXME above can be removed now. :D

File: compiler/rustc_middle/src/mir/interpret/error.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/error.rs:152]: > That's great. :D So does this also fix #79047 ?

yes, the corresponding test has been updated

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/error.rs:152]: We might want to keep the issue open for `SizeOfUnsizedType` though.

**Comment by jackh726** [comment]
This looks fine to me, but I'm not really familiar with this code, so maybe @RalfJung wants to give the final say?

**Comment by RalfJung** [comment]
typeck is outside my purview, sorry -- I can't really help with this PR, other than that I like the end-to-end effect of turning that one check in the interpreter into an assertion.

**Comment by oli-obk** [comment]
Rerolling the reviewer dice

r? rust-lang/compiler

**Comment by nagisa** [comment]
r? rust-lang/compiler

I won't be able to get to reviewing things for the upcoming next couple weeks.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 3]
```diff
@@ -293,7 +294,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 self.check_lang_item_path(lang_item, expr, hir_id)
             }
             ExprKind::Path(ref qpath) => self.check_expr_path(qpath, expr, &[]),
-            ExprKind::InlineAsm(asm) => self.check_expr_asm(asm),
+            ExprKind::InlineAsm(asm) => {
+                self.deferred_asm_checks.borrow_mut().push((asm, expr.hir_id));
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/check/expr.rs:298]: Why defer and not check it directly?

File: compiler/rustc_typeck/src/check/expr.rs [hunk 4]
```diff
@@ -529,8 +533,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             _ => self.instantiate_value_path(segs, opt_ty, res, expr.span, expr.hir_id).0,
         };
 
-        if let ty::FnDef(..) = ty.kind() {
+        if let ty::FnDef(did, ..) = *ty.kind() {
             let fn_sig = ty.fn_sig(tcx);
+            if tcx.fn_sig(did).abi() == RustIntrinsic && tcx.item_name(did) == sym::transmute {
+                let from = fn_sig.inputs().skip_binder()[0];
+                let to = fn_sig.output().skip_binder();
+                self.deferred_transmute_checks.borrow_mut().push((from, to, expr.span));
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/check/expr.rs:541]: Again, why defer?

File: compiler/rustc_typeck/src/check/intrinsicck.rs [hunk 5]
```diff
@@ -360,6 +360,9 @@ impl<'tcx> ExprVisitor<'tcx> {
                 // Some explicit registers cannot be used depending on the
                 // target. Reject those here.
                 if let InlineAsmRegOrRegClass::Reg(reg) = reg {
+                    if let InlineAsmReg::Err = reg {
+                        return;
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/check/intrinsicck.rs:364]: Why not `continue` to the next operand?

File: compiler/rustc_typeck/src/check/intrinsicck.rs [hunk 6]
```diff
@@ -376,6 +379,9 @@ impl<'tcx> ExprVisitor<'tcx> {
                 if !op.is_clobber() {
                     let mut missing_required_features = vec![];
                     let reg_class = reg.reg_class();
+                    if let InlineAsmRegClass::Err = reg_class {
+                        return;
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/check/intrinsicck.rs:383]: Why not `continue` to the next operand?

File: compiler/rustc_typeck/src/check/mod.rs [hunk 7]
```diff
@@ -482,6 +483,12 @@ fn typeck_with_fallback<'tcx>(
 
         fcx.select_all_obligations_or_error();
 
+        if !fcx.infcx.is_tainted_by_errors() {
+            fcx.check_transmutes();
+        }
+
+        fcx.check_asms();
```
Comment (cjgillot) [inline compiler/rustc_typeck/src/check/mod.rs:490]: Why the difference between `check_transmutes` and `check_asms`?

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 8]
```diff
@@ -274,6 +274,7 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
         error: &SelectionError<'tcx>,
         fallback_has_occurred: bool,
     ) {
+        self.set_tainted_by_errors();
```
Comment (cjgillot) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:277]: Does this change anything?

**Review by cjgillot — COMMENTED** [review]
I can't really review the typeck algorithm, but left a few questions where comments could be appropriate.

File: compiler/rustc_typeck/src/check/expr.rs (hunk 3 above)
Comment (oli-obk) [reply compiler/rustc_typeck/src/check/expr.rs:298]: Because it may contain unresolved inference variables, especially in the output. We need to wait for fallback to resolve all inference variables in the input, too

File: compiler/rustc_typeck/src/check/expr.rs (hunk 4 above)
Comment (oli-obk) [reply compiler/rustc_typeck/src/check/expr.rs:541]: Don't remember, probably inference vars, too. Will check and leave comments

File: compiler/rustc_typeck/src/check/intrinsicck.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_typeck/src/check/intrinsicck.rs:364]: That was very noisy. Again, will check and leave comments

File: compiler/rustc_typeck/src/check/mod.rs (hunk 7 above)
Comment (oli-obk) [reply compiler/rustc_typeck/src/check/mod.rs:490]: I wanted to replicate the previous diagnostics. For transmute that meant not to check if there were other errors already happening, as that would just cause useless errors in the transmute checks

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 8 above)
Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:276]: yes. It avoids ICEs and bogus errors in CTFE.

File: compiler/rustc_middle/src/mir/interpret/error.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/error.rs:153]: > What about SizeOfUnsizedType, which seems similar to me?

I have opened https://github.com/rust-lang/rust/issues/97477 for this.
