### PR TITLE
diagnostics: regression test for `<usize as Iterator>::rev`

### LINKED ISSUE #90315: "the method rev() exists on usize" is misleading
Given the following code: 

```rust
  let arr = &[0,1,2,3];
  for i in 0..arr.len().rev() {
     // ...   
  }
```

The current output is:

```
error[E0599]: the method `rev` exists for type `usize`, but its trait bounds were not satisfied
 --> src/main.rs:5:25
  |
5 |   for i in 0..arr.len().rev() {
  |                         ^^^ method cannot be called on `usize` due to unsatisfied trait bounds
  |
  = note: the following trait bounds were not satisfied:
          `usize: Iterator`
          which is required by `&mut usize: Iterator
```

Ideally the output should look like:

```
// Minimal fix: remove misleading message:
Omit "the method rev exists for type usize." 

// Amazing fix:
  |
5 |   for i in 0..arr.len().rev() {
  |                         ^^^ method cannot be called on `usize` due to unsatisfied trait bounds
  |
  = note: the following trait bounds were not satisfied:
          `usize: Iterator`
          which is required by `&mut usize: Iterator
  = hint: (0..arr.len()) implements `Iterator`, perhaps you are missing parentheses? 

```

### PR DESCRIPTION
**Pull request by notriddle**
Closes #90315

### CODE REVIEW

File: src/test/ui/methods/issues/issue-90315.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+fn main() {
```
Comment (Mark-Simulacrum) [inline src/test/ui/methods/issues/issue-90315.rs:1]: I'm a little confused -- should this be perhaps marked as `known-bug` or something like that? Otherwise this seems to be a test case for an example that is currently *not* good, which seems like it should at least have a comment as to what is being tested (it is not at all clear from just this file without reading the issue, which seems suboptimal to me).

Comment (notriddle) [reply src/test/ui/methods/issues/issue-90315.rs:1]: It used to say “the method `rev` exists for type `usize`”, which is false. Now, it says that “usize is not an iterator”, which is true.

I’ll add a comment to the file when I’m in front of a computer again.

**Comment by JohnCSimon** [comment]
Triage

@notriddle  - It looks like I've set this as ready for review. 
I set it using `@rustbot ready`

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
Squashed the commits.

@bors r+
