### PR TITLE
Learn to parse `a as usize < b`

### LINKED ISSUE #22644: Unable to parse expression `a as usize < b`
It seems like the parser tries to read the type where it isn't:

``` rust
fn main() {
    let a : u32 = 0;
    let b : usize = 0;

    a as usize > b; // ok
    a as usize < b; // error: expected one of `(`, `+`, `,`, `::`, `<`, or `>`, found `;`
}
```

I think it's rather strange that the operator `>` works, but the operator `<` doesn't at the same place.

`rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)`

### PR DESCRIPTION
**Pull request by estebank**
Parsing `a as usize > b` always works, but `a as usize < b` was a
parsing error because the parser would think the `<` started a generic
type argument for `usize`. The parser now attempts to parse as before,
and if a DiagnosticError is returned, try to parse again as a type with
no generic arguments. If this fails, return the original
`DiagnosticError`.

Fix #22644.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -2798,8 +2823,38 @@ impl<'a> Parser<'a> {
...
+                            }
+                            Err(mut path_err) => {
+                                // Still couldn't parse, return the original error
+                                path_err.cancel();
+                                return Err(err);
+                            }
+                        };
+                        let path = TyKind::Path(None, path);
+                        let span = lo.to(self.prev_span);
+                        let rhs = P(Ty { node: path, span: span, id: ast::DUMMY_NODE_ID });
```
Comment (oli-obk) [inline src/libsyntax/parse/parser.rs]: Is it possible to use `mk _ty` here? Or is the  `DUMMY_NODE_ID` intentional?

**Comment by petrochenkov** [comment]
I'd be okay with this if the unbounded lookahead and parser state saving/restoring machinery were used only for reporting better diagnostics and fix-it suggestions, not for actually accepting the code.

**Comment by Mark-Simulacrum** [comment]
Looks like there are some test failures in Travis: https://travis-ci.org/rust-lang/rust/jobs/241424157#L1853, though addressing @petrochenkov's concern first seems like a good idea.

**Comment by estebank** [comment]
> I'd be okay with this if the unbounded lookahead and parser state saving/restoring machinery were used only for reporting better diagnostics, recovery and fix-it suggestions, not for actually accepting the code.

Should `a as usize < b` be accepted? I understand the concern, and would heavily lean towards your opinion on all other situations, but in this case in particular it is adding a very specific edge case to the grammar which IMO is a big ergonomic win.

Having said that, what would be your preferred output if this were used only for diagnostics? Something like this?

```
error: expected one of `!`, `(`, `+`, `,`, `::`, `<`, or `>`, found `;`
 --> <anon>:6:19
  |
6 |     a as usize < b;
  |                   ^ expected one of 7 possible tokens here
  help: may be you want to compare the casted value?
  |     (a as usize) < b;
```

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: `mk_ty` is part of `TyCtxt` which isn't available yet. This was extracted from `parse_ty_common` in order to see if this would work at all. I could modify `parse_ty_common` for this case, but I felt it would muddy the logic of that method.

**Comment by petrochenkov** [comment]
@estebank 
>Having said that, what would be your preferred output if this were used only for diagnostics?

A specially crafted error would be the best, IMO.
```
error: `<` is interpreted as a start of generic arguments for `usize`, not comparison
 --> <anon>:6:19
  |
6 |     a as usize < b;
  |                ^ <some label, not sure what to write here>
  help: if you want to compare the casted value then write
  |     (a as usize) < b;
```
After this is reported as a non-fatal error, AST is build as if `a as usize < b` were legal and meant `(a as usize) < b`, e.g. most likely error recovery is performed.

**Comment by petrochenkov** [comment]
@estebank 
>it is adding a very specific edge case to the grammar which IMO is a big ergonomic win.

It's an edge case, but it has large effect on properties of the grammar as a whole.
If syntactic disambiguation between types and expressions is going to be done, it should probably be done in more principled fashion, discussed properly and maybe modeled in something like https://github.com/nikomatsakis/rustypop
BTW, the [Const generics RFC](https://github.com/rust-lang/rfcs/pull/2000) is related, first it break the assumption this PR does that if `b` is not a type, then it's the rhs argument for comparison, second it creates more demand for general disambiguation between types and expressions.

**Comment by petrochenkov** [comment]
>`(a as usize) < b`

`a as (usize) < b` works too and is more "local", but arguably more surprising, maybe it can be recommended instead? (I'm not sure)

**Comment by estebank** [comment]
> It's an edge case, but it has large effect on properties of the grammar as a whole.  
> If syntactic disambiguation between types and expressions is going to be done, it should probably be done in more principled fashion, discussed properly and maybe modeled in something like https://github.com/nikomatsakis/rustypop

I understand and completely agree.

> a as (usize) < b works too and is more "local", but arguably more surprising, maybe it can be recommended instead? (I'm not sure)

I think I prefer the former, as it'd be less surprising for a newcomer.

I got something working which accepts the code as proposed but also emits a warning suggesting a correction.

I should probably change the code that emits the warning before we merge, as right now [I am modifying the existing error in place](https://github.com/rust-lang/rust/pull/42578/files#diff-da9d34ca1d0f6beee2838cf02e07345cR2853), which is probably not what we want.

This is how it looks like right now:

```
warning: `<` is interpreted as a start of generic arguments for `usize`, not comparison
  --> $DIR/issue-22644.rs:16:33
   |
16 |     println!("{}", a as usize < b);
   |                                 ^ expected one of `!`, `(`, `+`, `,`, `::`, or `>` here
   |
help: if you want to compare the casted value then write:
   |     println!("{}", (a as usize) < b);
```

It probably should be closer to:

```
warning: `<` is interpreted as a start of generic arguments for `usize`, not comparison
  --> $DIR/issue-22644.rs:16:33
   |
16 |     println!("{}", a as usize < b);
   |                               - ^ interpreted as generic argument
   |                               |
   |                               not interpreted as comparison
help: if you want to compare the casted value then write:
   |     println!("{}", (a as usize) < b);
```

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -438,6 +441,8 @@ fn dummy_arg(span: Span) -> Arg {
     Arg { ty: P(ty), pat: pat, id: ast::DUMMY_NODE_ID }
 }
 
+type RewindPoint = (token::Token, Span, Option<Span>, Span, TokenCursor, Vec<TokenType>);
```
Comment (bjorn3) [inline src/libsyntax/parse/parser.rs]: Could you make this a struct with field names?

**Review by bjorn3 — CHANGES_REQUESTED** [review]

**Comment by nikomatsakis** [comment]
As long as we're not changing the grammar, I'm happy if @petrochenkov is happy =)

**Comment by estebank** [comment]
@nikomatsakis just to be clear, the code as is _accepts_ it under the assumption that it is correct and only emits a `warn` diagnostic. If this is the _only_ error, it will generate a valid binary. Is it ok to accept this code relying on people to be annoyed enough by warnings to fix their code?

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -1819,7 +1850,8 @@ impl<'a> Parser<'a> {
             }
 
             // Parse types, optionally.
-            let parameters = if self.eat_lt() {
+            let parameters = if self.is_lt() && !dont_parse_generics {
```
Comment (bjorn3) [inline src/libsyntax/parse/parser.rs]: `if !dont_parse_generics && self.eat_lt() {`

`&&` doesnt run second arg when first arg is false.

**Review by bjorn3 — CHANGES_REQUESTED** [review]

**Comment by nikomatsakis** [comment]
@estebank 

> the code as is accepts it under the assumption that it is correct and only emits a warn diagnostic

Accepts what exactly? And what do you mean by "as is"? You mean, in the PR, or in master?

**Comment by estebank** [comment]
@nikomatsakis The PR accepts `a as b < c` as valid code if it can parse `b` as a type without type arguments, showing a warning, not an error to change the code.

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: 👍 
This also makes `fn is_lt` unnecessary.

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -1800,7 +1829,9 @@ impl<'a> Parser<'a> {
     /// - `a::b<T,U>::c<V,W>`
     /// - `a::b<T,U>::c(V) -> W`
     /// - `a::b<T,U>::c(V)`
-    pub fn parse_path_segments_without_colons(&mut self) -> PResult<'a, Vec<PathSegment>> {
+    pub fn parse_path_segments_without_colons(&mut self, dont_parse_generics: bool)
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Nit: `dont_parse_generics: bool` -> `parse_generics: bool`

File: src/libsyntax/parse/parser.rs [hunk 5]
```diff
@@ -2798,8 +2830,62 @@ impl<'a> Parser<'a> {
...
+                // Save the state of the parser before parsing type normally, in case there is a
+                // LessThan comparison after this cast.
+                let rp = self.get_rewind_point();
+                match self.parse_ty_no_plus() {
+                    Ok(rhs) => {
+                        lhs = self.mk_expr(lhs_span.to(rhs.span),
+                                           ExprKind::Cast(lhs, rhs), ThinVec::new());
+                    }
+                    Err(mut err) => {
+                        // Rewind to before attempting to parse the type with generics, to get
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Could you move the error handling logic into a separate function?

File: src/libsyntax/parse/parser.rs [hunk 6]
```diff
@@ -2798,8 +2830,62 @@ impl<'a> Parser<'a> {
...
+                                    _ => format!("(<expression>)")
+                                };
+                                let warn_message = match codemap.span_to_snippet(self.prev_span) {
+                                    Ok(lstring) => format!("`{}`", lstring),
+                                    _ => "a type".to_string(),
+                                };
+                                let msg = format!("`<` is interpreted as a start of generic \
+                                                   arguments for {}, not a comparison",
+                                                  warn_message);
+                                let mut warn = self.sess.span_diagnostic.struct_span_warn(sp, &msg);
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: `struct_span_err` please.

File: src/libsyntax/parse/parser.rs [hunk 7]
```diff
@@ -2798,8 +2830,62 @@ impl<'a> Parser<'a> {
...
+                                warn.span_label(sp, "interpreted as generic argument");
+                                warn.span_label(self.span, "not interpreted as comparison");
+                                warn.span_suggestion(suggestion_span,
+                                                    "if you want to compare the casted value \
+                                                     then write:",
+                                                    suggestion);
+                                warn.emit();
+                                path
+                            }
+                            Err(mut path_err) => {
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Could you add a test for this case as well?

**Comment by nikomatsakis** [comment]
> The PR accepts `a as b < c` as valid code if it can parse b as a type without type arguments, showing a warning, not an error to change the code.

Huh, I'm confused. After all, you can do `let x = foo as Box<Bar>`. How do we know that `b < c` should *not* be parsed as a type?

File: src/libsyntax/parse/parser.rs (hunk 6 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Done.

File: src/libsyntax/parse/parser.rs (hunk 5 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Done.

File: src/libsyntax/parse/parser.rs [hunk 8]
```diff
@@ -438,6 +441,15 @@ fn dummy_arg(span: Span) -> Arg {
     Arg { ty: P(ty), pat: pat, id: ast::DUMMY_NODE_ID }
 }
 
+struct RewindPoint {
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Removed. Using `Parser.clone()` and `mem::replace()` instead of `RewindPoint`.

File: src/libsyntax/parse/parser.rs (hunk 4 above)
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Done.

**Comment by petrochenkov** [comment]
r=me with [stray note](https://github.com/rust-lang/rust/pull/42578#commitcomment-22556289) removed.

**Comment by estebank** [comment]
@petrochenkov done

@bors r=petrochenkov

**Comment by nikomatsakis** [comment]
I'd like to know if this is changing the grammar that is accepted. I feel like I still don't understand quite what's happening here. =)

**Comment by nikomatsakis** [comment]
In particular, do we now compile more programs than we did before? If so, what set of programs?

**Comment by estebank** [comment]
@nikomatsakis The first commit of this PR changed the accepted grammar and only emitted a warning. I changed it back to *not* have any changes in the grammar and emit an error. The parser state changes slightly after finding this case in order to continue parsing successfully the rest of the file (before this PR the rest of the file would not get any diagnostics). No new set of programs will be accepted, the new behaviors are:

 - a more specific error for the case `a as b < c`
 - continued parsing of the rest of the file after encountering `a as b < c`

**Comment by nikomatsakis** [comment]
@estebank perfect =)

**Comment by hertz4** [comment]
One last thing: `<<` isn't covered here.
```rust
error: `<` is interpreted as a start of generic arguments for `u16`, not a comparison                                          
 --> /tmp/angle.rs:4:29                                                                                                        
  |                                                                                                                            
4 |     println!("{}", x as u16 << 4);                                                                                         
  |                    -------- ^^ - interpreted as generic arguments                                                          
  |                    |        |                                                                                              
  |                    |        not interpreted as comparison                                                                  
  |                    help: try comparing the casted value: `(x as u16)`       
```

**Comment by petrochenkov** [comment]
@hertz4 
`<<` is fixed on beta/nightly

```
error: `<` is interpreted as a start of generic arguments for `u16`, not a shift
 --> src/main.rs:2:29
  |
2 |     println!("{}", x as u16 << 4);
  |                    -------- ^^ - interpreted as generic arguments
  |                    |        |
  |                    |        not interpreted as shift
  |                    help: try shifting the casted value: `(x as u16)`
```
