### PR TITLE
Treat macros as HIR items

### LINKED ISSUE #59306: `allow(missing_docs)` does not work for macro definitions
It appears `deny(missing_docs)` will take macros into account since 1.33.0. So I tried to add `#[allow(missing_docs)]` for some of the macros I don't want to write docs, and it doesn't seem to be working. Minimal reproducible example:

```rust
//! Hello
#![deny(missing_docs)]

#[allow(missing_docs)]
#[macro_export]
macro_rules! hello {
    () => ()
}
```

It will fail with:

```
error: missing documentation for macro
 --> src/lib.rs:6:1
  |
6 | macro_rules! hello {
  | ^^^^^^^^^^^^^^^^^^
  |
note: lint level defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(missing_docs)]
  |         ^^^^^^^^^^^^
```

Rust playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cf5ab453ab982bea1b435676cf46f119

Tested on nightly.

### LINKED ISSUE #73754: [rustdoc] Private macros are not documented with `--document-private-items`
Rustdoc has `--document-private-items` and `--document-hidden-items`. It would be nice to have an option to document non-exported macros, which is currently not possible as far as I can tell.

### LINKED ISSUE #87257: Rustdoc: `pub use`ing and/or globbing a submodule containing a `pub macro` (Macros 2.0) does not document the macro
Rustdoc will properly generate the documentation for a Macros-2.0 macro when that macro is defined in a directly-exported submodule, e.g. `pub mod foo { pub macro bar()`. But if the module is not directly exported (`pub mod foo {`) but indirectly exported (`pub use foo;`) then the macro no longer exists in the documentation: the module documentation for `mod foo` will not mention it, and no page for the macro will be generated at all. The same problem occurs if a macro is exported via `pub use foo::*`.

Note that these are not problems with name resolution itself: Rust code will resolve the exported macro properly, the docs merely don't show it.

Example:

```rust
#![feature(decl_macro)]

mod outer {
    /// I am module documentation
    pub mod inner {
        /// I am macro documentation
        pub macro some_macro() {}

        /// I am struct documentation
        pub struct SomeStruct;
    }
}

// GOOD: this shows up properly in the top-level crate docs
pub use outer::inner::SomeStruct;

// GOOD: this shows up properly in the top-level crate docs
pub use outer::inner::some_macro;

// BAD: the `inner` module-level documentation shows the struct, but not the macro.
// If `outer` did not exist and `inner` were instead directly exported,
// then both items show up as expected.
pub use outer::inner;
```

(In the above example even though `some_macro` is not listed in the docs for `inner`, the docs page for `some_macro` will still be generated because of the explicit `pub use outer::inner::some_macro`; if this line is removed then that page will also vanish.)

Presumably this is a descendant of https://github.com/rust-lang/rust/issues/74355 , where Macros-2.0 were not being documented at the correct paths. The fix for that issue landed in https://github.com/rust-lang/rust/pull/77862 , although the fix itself appears to be regarded as a deplorable hack, and presumably the fix for this issue should not attempt to further hack the hack and instead make Macros 2.0 Just Work with Rustdoc.

### LINKED ISSUE #87406: Macro definitions should be regular HIR items
Macro definitions are currently handled separately from other item kinds in HIR, either as `MacroDef` nodes inside `hir::Crate::exported_macros` or as using the `hir::Crate::non_exported_macro_attrs`.

They should be transformed into additional variants in the `hir::ItemKind` enum, and iterated over like any other item.

Instructions:
- introduce two additional variants `hir::ItemKind::ExportedMacro { ast: ast::MacroDef }` and `hir::ItemKind::NonExportedMacro`;
- move the macro case in `rustc_ast_lowering::item::LoweringContext::lower_item` into `lower_item_kind`;
- remove `hir::OwnerNode::{MacroDef, NonExportedMacro}` variants.

I recomment waiting on https://github.com/rust-lang/rust/pull/83723 and https://github.com/rust-lang/rust/pull/87234 to be merged.

Original idea by @petrochenkov in https://github.com/rust-lang/rust/pull/83723#discussion_r674077466
Should help with https://github.com/rust-lang/rust/issues/73754

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
Macros have historically been treated differently from other items at the HIR level. This PR makes them just like normal items. There are a few special cases left over, which I've attempted to lay out below. By normalizing the treatment of macro items, this PR simplifies a fair bit of code and fixes some bugs at the same time. For more information, see #87406.

r? @cjgillot

## Backwards incompatibility

This is backwards incompatible in one small way. Due to a mistake, it was previously possible to apply stability attributes to an exported macro, even without enabling the `staged_api` feature. This never should have worked. After this PR, it will error, as it should. We could make it a warning instead, but that would require a special case for a feature that shouldn't ever have worked and is likely used by no or very few crates, so I'm not thrilled about the idea.

### Commit seperation

I'd recommend reviewing this PR commit by commit. The commit chunking wasn't perfect, but it's better than looking at the combined diff, which is quite overwhelming. The compiler and standard library build after each commit, although tests do not necessarily pass and tools do not necessarily build till the end of the series.

### Special cases
There are a few special cases that remain after this change. Here are the notable ones I remember:

1. Visibility works a bit differently for `macro_rules!` macros than other items, since they aren't generally marked with `pub` but instead with `#[macro_export]`.
2. Since `#[macro_export]` macros always have paths at the top level of the crate, some additional handling needs to be done on the reexport to top level.
### Performance impact

I don't know for sure, but theses changes may slightly hurt performance. They create more work for the compiler in a few places. For instance, some operations that were previously run only for exported macros are now run for all macros. A perf run is probably advisable. For all I know we'll see performance improvements instead. :)

## Issues resolved

This resolves #87406 (the tracking issue for this change). It also fixes several bugs:

Fixes #59306.
Fixes #73754.
Fixes #87257.

### CODE REVIEW

**Comment by inquisitivecrystal** [comment]
I'm consulting with the rustdoc team about the best way to solve this problem. [Link to the Zulip thread.](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Doctests.20on.20private.20macros)

**Comment by cjgillot** [comment]
Thanks @inquisitivecrystal. I will take a look when I get back. 
@bors try @rust-timer queue

**Comment by LeSeulArtichaut** [comment]
Looks like rust-timer didn't queue this PR: @rust-timer queue

**Comment by petrochenkov** [comment]
Two general comments:
- I'm not sure literally moving `#[macro_export]` macros to the root in def collector and AST lowering is the best alternative.
    For all purposes a `#[macro_export] macro_rules!` item exists at the point at which it's written in source code (for `#[allow]` attributes, for example) and behaves like non-exported `macro_rules!` items, *except* that it inserts some kind of "reexport" of itself to the root module during metadata encoding.
- The `is_exported` property as it is defined now doesn't really makes sense and shouldn't be kept as a flag in HIR (unless perhaps temporary, for preserving bug-compatibility). Visibility/reachability properties are already correctly provided for all macros with `visibility` and `privacy_access_levels` queries and otherwise exported `macro_rules` should be treated identically to non-exported `macro_rules` (modulo the metadata encoding bit mentioned above).

**Comment by petrochenkov** [comment]
>...and behaves like non-exported `macro_rules!` items, *except* that it inserts some kind of "reexport" of itself to the root module during metadata encoding.

This would be similar to AST-level treatment of `#[macro_export] macro_rules!` where it's treated as a regular `macro_rules!` item, except that it adds an additional `NameBinding` to the root (see `fn define_macro` in resolve).

**Comment by cjgillot** [comment]
@rust-timer build 2a825dbd5f82b9c9b0213aa4be81e09172d8122c

**Comment by inquisitivecrystal** [comment]
> Two general comments:
> 
> * I'm not sure literally moving `#[macro_export]` macros to the root in def collector and AST lowering is the best alternative.
>   For all purposes a `#[macro_export] macro_rules!` item exists at the point at which it's written in source code (for `#[allow]` attributes, for example) and behaves like non-exported `macro_rules!` items, _except_ that it inserts some kind of "reexport" of itself to the root module during metadata encoding.

It was your idea in the first place! :) Seriously though, I'd be thrilled if I could remove the code for hoisting `#[macro_export] macro_rules!` items to the top level. It's both the messiest and least maintainable part of my code.

That being said, I don't really know what to replace it with. The main reason this was necessary was that rustdoc needed to see exported macros at the top level rather than where they're defined. Rustdoc works solely from the HIR: it doesn't see anything we do to the metadata. How do I make rustdoc put `#[macro_export]` macros in the right place?

Also, I'm not sure that it's necessary to do anything during metadata encoding. As I recall, everything was building before I moved exported macros to the top level; the only reason I needed to move the items was to get rustdoc to work right. Am I missing something?

> * The `is_exported` property as it is defined now doesn't really makes sense and shouldn't be kept as a flag in HIR (unless perhaps temporary, for preserving bug-compatibility). Visibility/reachability properties are already correctly provided for all macros with `visibility` and `privacy_access_levels` queries and otherwise exported `macro_rules` should be treated identically to non-exported `macro_rules` (modulo the metadata encoding bit mentioned above).

HIR normally contains the visibility of an item, through `item.vis.node.is_pub()`. This doesn't work correctly for macros, because `#[macro_export]` macros are always public regardless of their `vis`. It feels a bit weird to have less information available in the HIR for macros than other items. In practical terms though, I guess I could have a go of replacing the places I use `is_exported` with the queries and let you know if I bump into problems?

**Comment by petrochenkov** [comment]
@inquisitivecrystal 
>As I recall, everything was building before I moved exported macros to the top level; the only reason I needed to move the items was to get rustdoc to work right. Am I missing something?

Macros are implemented through hacks in one more place - they are actually encoded to metadata as reexports and not as regular items.
You can see in `fn encode_info_for_mod` how `module_exports` are encoded, and those `module_exports` table is filled in `fn finalize_resolutions_in`, where it's called `export_map` and where macro bindings (`macro` items and `#[macro_export] macro_rules` root bindings) are added to it in addition to regular `use` imports.

If rustdoc can document reexports (and it can, probably through the `item_children` query), then it can document exported macros as well.
I suspect that rustdoc simply needs to skip `hir::Item` macros unless `--document-private-items` is enabled, and continue documenting them through reexports.

>In practical terms though, I guess I could have a go of replacing the places I use is_exported with the queries and let you know if I bump into problems?

Yeah, and if that ends up being non-trivial, it can be deferred to a separate PR.

**Comment by petrochenkov** [comment]
>except that it inserts some kind of "reexport" of itself to the root module during metadata encoding

I suspect that this is the only place where we want to *continue* encoding macros with reexports, otherwise it would be good to remove the aforementioned hack and stop adding macros to the `module_exports` list in resolve.

**Comment by petrochenkov** [comment]
>HIR normally contains the visibility of an item, through `item.vis.node.is_pub()`. This doesn't work correctly for macros, because `#[macro_export]` macros are always public regardless of their `vis`.

If the "syntactic" visibility is used for something after lowering to HIR instead of `tcx.visibility()`, then it's likely an unnoticed bug.

**Comment by inquisitivecrystal** [comment]
> > HIR normally contains the visibility of an item, through `item.vis.node.is_pub()`. This doesn't work correctly for macros, because `#[macro_export]` macros are always public regardless of their `vis`.
> 
> If the "syntactic" visibility is used for something after lowering to HIR instead of `tcx.visibility()`, then it's likely an unnoticed bug.

That's [interesting to hear](https://github.com/rust-lang/rust/pull/88019/files#diff-4b76d999d0f2e74f6df3724a36a6b96302b16968a2f7af48d2b4c08048f8f871L260-R217). Should that be switched to `tcx.visibility()`?

**Comment by inquisitivecrystal** [comment]
Well, that was worse than I was really expecting. I'm hoping that yanking out the hoisting to top level stuff should improve things some, though I don't know how much. I guess we'll have to see.

**Comment by petrochenkov** [comment]
>That's [interesting to hear](https://github.com/rust-lang/rust/pull/88019/files#diff-4b76d999d0f2e74f6df3724a36a6b96302b16968a2f7af48d2b4c08048f8f871L260-R217). Should that be switched to `tcx.visibility()`?

I don't know, the logic in rustdoc often remind [this thing](https://en.wikipedia.org/wiki/Celestial_Emporium_of_Benevolent_Knowledge) in its consistency, so the best bet is just to preserve the old behavior.
(An then perhaps overhaul that code, and see what breaks, and talk with rustdoc maintainers to figure out what the intentions were.)

File: src/librustdoc/visit_ast.rs [hunk 1]
```diff
@@ -257,7 +210,13 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
         debug!("visiting item {:?}", item);
         let name = renamed.unwrap_or(item.ident.name);
 
-        if item.vis.node.is_pub() {
+        let is_pub = if let hir::ItemKind::Macro { is_exported: true, .. } = item.kind {
```
Comment (cjgillot) [inline src/librustdoc/visit_ast.rs:213]: This line makes me wonder if we could replace `is_exported` by making `item.vis` public.

**Comment by inquisitivecrystal** [comment]
> > That's [interesting to hear](https://github.com/rust-lang/rust/pull/88019/files#diff-4b76d999d0f2e74f6df3724a36a6b96302b16968a2f7af48d2b4c08048f8f871L260-R217). Should that be switched to `tcx.visibility()`?
> 
> I don't know, the logic in rustdoc often remind [this thing](https://en.wikipedia.org/wiki/Celestial_Emporium_of_Benevolent_Knowledge) in its consistency, so the best bet is just to preserve the old behavior.
> (An then perhaps overhaul that code in a separate PR, and see what breaks, and talk with rustdoc maintainers to figure out what the intentions were.)

I changed it in my local copy and the tests are still passing, so... *shrug*

**Review by cjgillot — COMMENTED** [review]
Thank you for the work @inquisitivecrystal!
I agree with @petrochenkov that we should not attempt to move the exported macros to the crate root. I'll let you two discuss on the right path here.

I left a few comments on the current state of the PR. I will do a deeper pass once we figure out the top-level reexport story.

File: src/librustdoc/visit_ast.rs (hunk 1 above)
Comment (jyn514) [reply src/librustdoc/visit_ast.rs:213]: Isn't it already public? This used `item.vis.node.is_pub()` before - @inquisitivecrystal why did you change it?

Comment (inquisitivecrystal) [reply src/librustdoc/visit_ast.rs:213]: The problem is that a `#[macro_export] macro_rules!` item doesn't have a `vis.node` that shows it's public, but is anyway. petrochenkov suggested that I could replace situations like this with calls to `tcx.visibility()`, which seems work fine.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 2]
```diff
@@ -465,7 +442,26 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-            ItemKind::MacroDef(..) | ItemKind::MacCall(..) => {
+            ItemKind::MacroDef(MacroDef { ref body, macro_rules }) => {
+                let is_exported = !macro_rules
+                    || attrs.map_or(false, |a| self.sess.contains_name(a, sym::macro_export));
+
+                let body = P(self.lower_mac_args(body));
+
+                hir::ItemKind::Macro {
+                    // `is_exported` is duplicated, to make matching more convenient.
+                    is_exported,
```
[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/item.rs:466]: I would have argued with you on this, but petrochenkov told me it doesn't make sense for it to be there. Now it's gone from being there twice to being there zero times.

File: compiler/rustc_hir/src/stable_hash_impls.rs [hunk 3]
```diff
@@ -193,7 +193,7 @@ impl<HirCtx: crate::HashStableContext> HashStable<HirCtx> for Item<'_> {
 
 impl<HirCtx: crate::HashStableContext> HashStable<HirCtx> for MacroDef<'_> {
     fn hash_stable(&self, hcx: &mut HirCtx, hasher: &mut StableHasher) {
-        let MacroDef { ident, def_id: _, ref ast, ref vis, span } = *self;
+        let MacroDef { is_exported: _, ident, def_id: _, ref ast, ref vis, span } = *self;
```
[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_hir/src/stable_hash_impls.rs:196]: It no longer exists in my local version.

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 4]
```diff
@@ -597,6 +616,19 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
         id
     }
 
+    /// This checks if an item is a `#[macro_use]` macro, and thus always
+    /// defined at the top level. As a special case, if the macro is already
+    /// at the top level, it remains at its current level.
+    fn check_force_top_level(&self, item: &Item) -> bool {
+        if self.is_at_top_level {
```
[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/lib.rs:623]: I'm pretty sure it isn't. If you go look at the cases where I set `is_at_top_level`, I don't think all of them are covered by checking `self.current_hir_id_owner.0`. I think I tried that at some point and it didn't work. It's somewhat irrelevant though, because if we don't move the exported macros to the crate root all of this code disappears.

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 5]
```diff
@@ -1100,7 +1101,11 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
                     let vis = self.get_visibility(child_index);
                     let def_id = self.local_def_id(child_index);
                     let res = Res::Def(kind, def_id);
-                    callback(Export { res, ident, vis, span });
+
+                    if !kind.is_macro() {
```
[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1105]: I was going to mention this, and then I forgot. Serves me right for not leaving a comment. The truth of the matter is, I have absolutely no clue why I needed to skip macros here. If I don't do so, I get errors (which it took me five+ hours to debug :/). I think those may come from situations in which a macro is defined as a macro by example, but also defined as a builtin macro. Here's what the errors look like:

```
error[E0428]: the name `Clone` is defined multiple times
   --> /rust/library/core/src/clone.rs:139:1
    |
139 | pub macro Clone($item:item) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | `Clone` redefined here
    | previous definition of the macro `Clone` here
    |
    = note: `Clone` must be defined only once in the macro namespace of this module

error[E0428]: the name `Copy` is defined multiple times
   --> /rust/library/core/src/marker.rs:393:1
    |
393 | pub macro Copy($item:item) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | `Copy` redefined here
    | previous definition of the macro `Copy` here
    |
    = note: `Copy` must be defined only once in the macro namespace of this module
```

I tried to fix this by not encoding the macros, rather than by skipping decoding them, but I couldn't get that to work either. Any insight into what might be going on here would be helpful. Although this solution works, I have a strong feeling that it likely isn't the right solution.

File: src/librustdoc/visit_ast.rs [hunk 6]
```diff
@@ -257,7 +228,9 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
         debug!("visiting item {:?}", item);
         let name = renamed.unwrap_or(item.ident.name);
 
-        if item.vis.node.is_pub() {
+        let is_pub = self.cx.tcx.visibility(item.def_id) == Visibility::Public;
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:231]: Hmm, I think this behaves differently for Inherited visibility: In `pub enum E { A, B }`, A and B will have `ty::Visibility::Public` if you call `visibility()`, but `ast::VisibilityKind::Inherited` if you call `node.is_pub()`. So this is a change in behavior, and I'm a little nervous about it.

That said, this does seem more correct to me - this should be using the computed visibility, not the syntactic visibility. Can you add a test that this now inlines enum variants? Right now it doesn't:
```rust
pub mod x {
    pub enum E { A, B }
}

#[doc(inline)]
pub use x::E::A;

#[doc(inline)]
pub use x::E;
```
image

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:231]: Actually, I'm not sure what it means to inline variants :/ they don't get their own documentation page (and the same for trait methods, which also have inherited visibility). So please do add the test, I'm curious to see what it changes. We may need to keep the original behavior depending on what it does.

**Comment by jyn514** [comment]
> > That's [interesting to hear](https://github.com/rust-lang/rust/pull/88019/files#diff-4b76d999d0f2e74f6df3724a36a6b96302b16968a2f7af48d2b4c08048f8f871L260-R217). Should that be switched to `tcx.visibility()`?
> 
> I don't know, the logic in rustdoc often remind [this thing](https://en.wikipedia.org/wiki/Celestial_Emporium_of_Benevolent_Knowledge) in its consistency, so the best bet is just to preserve the old behavior.
> (An then perhaps overhaul that code in a separate PR, and see what breaks, and talk with rustdoc maintainers to figure out what the intentions were.)

See https://github.com/rust-lang/rust/pull/88019#discussion_r689221354.

File: src/librustdoc/visit_ast.rs (hunk 6 above)
Comment (inquisitivecrystal) [reply src/librustdoc/visit_ast.rs:231]: Tested locally. It doesn't seem to do anything. The inline attribute is silently ignored, the same way it is on stable. I'll add an actual test for it when I get a chance.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 7]
```diff
@@ -465,7 +442,18 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
             ),
-            ItemKind::MacroDef(..) | ItemKind::MacCall(..) => {
+            ItemKind::MacroDef(MacroDef { ref body, macro_rules }) => {
+                let body = P(self.lower_mac_args(body));
+
+                hir::ItemKind::Macro(hir::MacroDef {
+                    ident: *ident,
+                    vis: *vis,
+                    def_id: hir_id.expect_owner(),
+                    span,
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/item.rs:452]: `def_id`, `ident`, `vis` and `span` are already in the `hir::Item`. `hir::ItemKind::Macro` only needs to contain the `ast::MacroDef`.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 8]
```diff
@@ -212,28 +211,6 @@ impl<'hir> LoweringContext<'_, 'hir> {
     pub fn lower_item(&mut self, i: &Item) -> Option<hir::Item<'hir>> {
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/item.rs:211]: This function always returns `Some`.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 9]
```diff
@@ -212,28 +211,6 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-                    let a = self.lower_attr(a);
-                    self.non_exported_macro_attrs.push(a);
-                }
-            }
-            return None;
-        }
-
         let hir_id = self.lower_node_id(i.id);
         let attrs = self.lower_attrs(hir_id, &i.attrs);
         let kind = self.lower_item_kind(i.span, i.id, hir_id, &mut ident, attrs, &mut vis, &i.kind);
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/item.rs:216]: Can `lower_item` and `lower_item_kind` be merged? (This can be left to a follow-up PR).

File: compiler/rustc_metadata/src/rmeta/decoder.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (cjgillot) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1105]: I think I've got at least part of the story. This error is created by resolution code when it enumerates all the children of a given module. Formerly, the macro did not appear in the HIR module list of items (your change to lower_item_ref), so this code path never included any macro. Now, macros are listed in the module, so appear when resolution tries to construct the reduced graph. Except that the resolver already lists all macros as reexports (rustc_resolve::imports::finalize_resolutions_in, line 1396).
Does removing the `|| binding.is_macro_def()` there work?

[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1105]: Well, it changes the errors I get. Here's a sample of the new ones:

```
error[E0432]: unresolved import `core::format_args`
   --> library/alloc/src/lib.rs:197:13
    |
197 |     pub use core::format_args;
    |             ^^^^^^^^^^^^^^^^^ no `format_args` in the root

error: cannot find macro `panic` in this scope
   --> library/alloc/src/alloc.rs:387:9
    |
387 |         panic!("memory allocation of {} bytes failed", size)
    |         ^^^^^

error: cannot find macro `unreachable` in this scope
   --> library/alloc/src/borrow.rs:281:37
    |
281 |                     Borrowed(..) => unreachable!(),
    |                                     ^^^^^^^^^^^

error: cannot find macro `write` in this scope
   --> library/alloc/src/collections/btree/map/entry.rs:100:9
    |
100 |         write!(
    |         ^^^^^
```

File: compiler/rustc_ast_lowering/src/item.rs (hunk 8 above)
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/item.rs:211]: I know, but it's not my function and I'm no longer touching that part of the code.

File: compiler/rustc_ast_lowering/src/item.rs (hunk 9 above)
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/item.rs:216]: They could, yeah. I think this layout is cleaner though.

File: compiler/rustc_ast_lowering/src/item.rs (hunk 7 above)
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/item.rs:452]: I tried to do that, but I bumped into problems with intravisit::Visitor::visit_macro_def, which needs to receive a hir::MacroDef. I couldn't figure out how to make the lifetimes work for that if the MacroDef didn't already exist. Note that we also support, for instance, Visitor::visit_fn, so I'm not sure that Visitor::visit_macro_def should be considered redundant with Visitor::visit_item.

File: compiler/rustc_passes/src/stability.rs [hunk 10]
```diff
@@ -613,10 +613,11 @@ impl<'tcx> Visitor<'tcx> for MissingStabilityAnnotations<'tcx> {
...
     fn visit_item(&mut self, i: &'tcx Item<'tcx>) {
-        // Inherent impls and foreign modules serve only as containers for other items,
-        // they don't have their own stability. They still can be annotated as unstable
-        // and propagate this unstability to children, but this annotation is completely
-        // optional. They inherit stability from their parents when unannotated.
+        // Inherent impls, foreign modules, and non exported macros serve only as
+        // containers for other items, they don't have their own stability. They still can
+        // be annotated as unstable and propagate this unstability to children, but this
+        // annotation is completely optional. They inherit stability from their parents
+        // when unannotated.
```
Comment (inquisitivecrystal) [inline compiler/rustc_passes/src/stability.rs:620]: Note to self: roll back this documentation change.

File: compiler/rustc_lint/src/builtin.rs [hunk 11]
```diff
@@ -635,7 +617,8 @@ impl<'tcx> LateLintPass<'tcx> for MissingDoc {
                 return;
             }
 
-            hir::ItemKind::TyAlias(..)
+            hir::ItemKind::Macro { .. }
+            | hir::ItemKind::TyAlias(..)
```
Comment (inquisitivecrystal) [inline compiler/rustc_lint/src/builtin.rs:621]: Note to self: the ordering is a bit weird here.

File: src/librustdoc/visit_ast.rs (hunk 6 above)
Comment (inquisitivecrystal) [reply src/librustdoc/visit_ast.rs:231]: I think it might be better for me to separate the change over to `tcx.visibility` into a separate PR and do something more conservative here. It seems like this might cause a regression and we might end up having to revert. Thoughts?

File: compiler/rustc_ast_lowering/src/item.rs (hunk 7 above)
Comment (cjgillot) [reply compiler/rustc_ast_lowering/src/item.rs:452]: There are only two uses of `visit_macro_def` left: `rustc_passes::{hir_stats, stability}`. I think the function can be removed altogether.

File: compiler/rustc_ast_lowering/src/item.rs (hunk 8 above)
Comment (cjgillot) [reply compiler/rustc_ast_lowering/src/item.rs:211]: ok

File: src/librustdoc/visit_ast.rs (hunk 6 above)
Comment (cjgillot) [reply src/librustdoc/visit_ast.rs:231]: A separate PR is possible, yes.

File: compiler/rustc_ast_lowering/src/item.rs (hunk 7 above)
Comment (inquisitivecrystal) [reply compiler/rustc_ast_lowering/src/item.rs]: Done!

**Comment by inquisitivecrystal** [comment]
I just want to state, for the record, my request that this not be merged until I have a chance to clean up the commits. No point doing that till we're closer to being done though.

**Comment by cjgillot** [comment]
LGTM. I will approve once you get to cleanup commit history and PR message + add a comment in `rustc_metadata::rmeta::decoder` stating that resolve creates reexports for macros which create conflicts with the item themselves for downstream crates.

File: compiler/rustc_hir_pretty/src/lib.rs [hunk 12]
```diff
@@ -660,6 +660,28 @@ impl<'a> State<'a> {
...
+                    Some(item.ident),
+                    macro_def.body.delim(),
+                    &macro_def.body.inner_tokens(),
+                    true,
+                    item.span,
+                );
+
+                if macro_def.body.need_semicolon() {
+                    self.word(";");
+                }
```
Comment (petrochenkov) [inline compiler/rustc_hir_pretty/src/lib.rs:683]: Instead of copy-pasting this can be factored out into a method in `compiler\rustc_ast_pretty\src\pprust\state.rs`.

File: compiler/rustc_hir/src/def.rs [hunk 13]
```diff
@@ -218,6 +218,13 @@ impl DefKind {
             | DefKind::Impl => None,
         }
     }
+
+    pub fn is_macro(self) -> bool {
+        match self {
+            DefKind::Macro(..) => true,
+            _ => false,
+        }
+    }
```
Comment (petrochenkov) [inline compiler/rustc_hir/src/def.rs:227]: I don't think this method is necessary, it's trivial `matches!(kind, DefKind::Macro(..))` and it's not commonly used.

File: src/test/ui/lint/lint-level-macro-def.rs [hunk 14]
```diff
@@ -0,0 +1,17 @@
...
+
+
+#[deny(missing_docs)]
+mod module {
+    #[allow(missing_docs)]
+    #[macro_export]
+    macro_rules! hello {
+        () => ()
+    }
+}
```
Comment (petrochenkov) [inline src/test/ui/lint/lint-level-macro-def.rs:15]: Could you add a test case for this case
```rust
#[allow(missing_docs)]
mod module {
    #[macro_export]
    macro_rules! hello {
        () => ()
    }
}
```
, it'll make sure that macros exported from non-root modules still have those modules as parents from linting point of view.

File: compiler/rustc_privacy/src/lib.rs [hunk 15]
```diff
@@ -879,47 +931,6 @@ impl Visitor<'tcx> for EmbargoVisitor<'tcx> {
...
-        loop {
-            let changed_reachability =
-                self.update_macro_reachable(module_def_id, macro_module_def_id);
-            if changed_reachability || module_def_id == CRATE_DEF_ID {
-                break;
-            }
-            module_def_id =
-                ty::DefIdTree::parent(self.tcx, module_def_id.to_def_id()).unwrap().expect_local();
-        }
-    }
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:922]: Could you keep this logic in a separate function instead of inlining it to `EmbargoVisitor::visit_item`?

File: compiler/rustc_privacy/src/lib.rs [hunk 16]
```diff
@@ -642,6 +639,21 @@ impl Visitor<'tcx> for EmbargoVisitor<'tcx> {
             }
             // Foreign modules inherit level from parents.
             hir::ItemKind::ForeignMod { .. } => self.prev_level,
+            hir::ItemKind::Macro(ref macro_def) => {
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:642]:
```suggestion
            hir::ItemKind::Macro(MacroDef { macro_rules: true, .. }) => {
```
The non-`macro_rules` case is identical to other items below.

File: compiler/rustc_privacy/src/lib.rs [hunk 17]
```diff
@@ -507,11 +507,7 @@ impl EmbargoVisitor<'tcx> {
         }
         match def_kind {
             // No type privacy, so can be directly marked as reachable.
-            DefKind::Const
-            | DefKind::Macro(_)
-            | DefKind::Static
-            | DefKind::TraitAlias
-            | DefKind::TyAlias => {
+            DefKind::Const | DefKind::Static | DefKind::TraitAlias | DefKind::TyAlias => {
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:510]: Any specific reason for this change?
The old logic seemed correct to me.

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 18]
```diff
@@ -1036,6 +1036,7 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
                         self.local_def_id(def_index),
                     );
                     let ident = self.item_ident(def_index, sess);
+
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/rmeta/decoder.rs:1039]: Nit: random whitespace change.

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 19]
```diff
@@ -1100,7 +1101,11 @@ impl<'a, 'tcx> CrateMetadataRef<'a> {
                     let vis = self.get_visibility(child_index);
                     let def_id = self.local_def_id(child_index);
                     let res = Res::Def(kind, def_id);
-                    callback(Export { res, ident, vis, span });
+
+                    if !kind.is_macro() {
+                        callback(Export { res, ident, vis, span });
+                    }
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/rmeta/decoder.rs:1107]: Could you add a comment/FIXME explaining that macros are currently encoded twice as items and as reexports, so we are ignoring the items when decoding module children and only use the reexports.

File: src/librustdoc/visit_ast.rs [hunk 20]
```diff
@@ -79,50 +79,25 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
-                match cur_mod.mods.iter_mut().find(|child| child.name == path_segment_ty_ns) {
-                    Some(child_mod) => cur_mod = &mut *child_mod,
-                    None => continue 'exported_macros,
+
+        // `#[macro_export] macro_rules!` items are reexported at the top level of the
+        // crate, regardless of where they're defined. We want to document the
+        // top level rexport of the macro, not its original definition, since
+        // the rexport defines the path that a user will actually see. Accordingly,
+        // we add the rexport as an item here, and then skip over the original
+        // definition in `visit_item()` below.
```
Comment (petrochenkov) [inline src/librustdoc/visit_ast.rs:88]: So, if non-exported `macro_rules` are documented at their in-source definition point when `--document-private-items` is enabled, then why exported `macro_rules` are not? :)

It would be pretty reasonable/consistent to document exported macros twice in the doc-private mode - once as an item and once as the root "reexport" (especially if that would make rustdoc logic simpler).

**Comment by jyn514** [comment]
@rustbot label: +perf-regression-triaged

This fixes several long-standing bugs relating to macros, and the performance regression is quite minor.

File: compiler/rustc_hir/src/def.rs (hunk 13 above)
Comment (inquisitivecrystal) [reply compiler/rustc_hir/src/def.rs:227]: I personally think `!matches!()` looks atrocious. That said, fair enough.

File: compiler/rustc_metadata/src/rmeta/decoder.rs (hunk 19 above)
Comment (inquisitivecrystal) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1107]: Is there a reasonably simple way to fix it? This workaround feels very hacky to me.

File: src/librustdoc/visit_ast.rs (hunk 20 above)
Comment (inquisitivecrystal) [reply src/librustdoc/visit_ast.rs:88]: Documenting them twice feels weird to me, especially given that the only path they can be addressed at is the root path. Would it be worth asking the rustdoc team?

File: compiler/rustc_metadata/src/rmeta/decoder.rs (hunk 19 above)
Comment (petrochenkov) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1107]: Yes, something like https://github.com/cjgillot/rust/commit/c147d8fdf8c4428ac94216f9629816b357c05435.
I think it's ok to land this as is in this PR.

File: src/librustdoc/visit_ast.rs (hunk 20 above)
Comment (jyn514) [reply src/librustdoc/visit_ast.rs:88]: @petrochenkov I don't understand your suggestion. Why would rustdoc document macros at the definition if they're not accessible using that path? That seems actively misleading.

Comment (petrochenkov) [reply src/librustdoc/visit_ast.rs:88]: >given that the only path they can be addressed at is the root path

Non-exported macros cannot be addressed by any path, but they are still documented when `--document-private-items` is enabled.
This comment is certainly not a blocking one though.

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:88]: > Non-exported macros cannot be addressed by any path, but they are still documented when --document-private-items is enabled.

Can't they be addressed by that path by the module that defined them?

Comment (petrochenkov) [reply src/librustdoc/visit_ast.rs:88]: No, `macro_rules` macros are not "modularized" and cannot be addressed by a module-relative paths.
Moreover, there can be multiple `macro_rules` with the same name in the same module.

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:88]: > Moreover, there can be multiple macro_rules with the same name in the same module.

Oh fun ... Rustdoc almost certainly can't handle that. @inquisitivecrystal can you add a test for that case? I expect all the macro.name.html files will be overwritten by each other.

File: compiler/rustc_privacy/src/lib.rs (hunk 17 above)
Comment (inquisitivecrystal) [reply compiler/rustc_privacy/src/lib.rs:510]: Yeah, there was, although looking back this may not be the right fix. The problem is that otherwise you start getting "macro has missing stability attribute" errors for non-exported macros. It would be possible to work around that, but I thought it would require reconstructing macro expectedness in atom `compiler/rustc_passes/src/stability.rs`. A potential alternative would be to only skip marking the item reachable for nonexported macros (in other words, handle macro expectedness here). I'm not sure which one of these solutions is actually correct.

File: compiler/rustc_metadata/src/rmeta/decoder.rs (hunk 19 above)
Comment (inquisitivecrystal) [reply compiler/rustc_metadata/src/rmeta/decoder.rs:1107]: Alright, I'll leave it this way for now and do the comment.

File: compiler/rustc_hir_pretty/src/lib.rs (hunk 12 above)
Comment (inquisitivecrystal) [reply compiler/rustc_hir_pretty/src/lib.rs:683]: It can, but it's a bit less trivial than it may at first appear. In `rustc_ast_pretty`, the visibility is an `ast::Visibility`. By contrast, in `rustc_hir_pretty`, the visibility is an `hir::Visibility`. As far as I can tell, there's no way to interconvert between the two, though I'd be overjoyed if someone told me I'm wrong about that.

That means that we'd end up needing to make the function generic with respect to the the type of visibility. The first pass I did has a function signature that looks like this:

```rust
fn print_mac_def<V>(
        &mut self,
        macro_def: &ast::MacroDef,
        ident: &Ident,
        vis: &V,
        sp: &Span,
        print_visibility: impl FnOnce(&mut Self, &V),
    )
```

It would probably be cleaner to use traits somehow, though I'm not sure what the best way to go about that is. In any case, this approach does add some amount of complexity. The DRY principle may be enough to justify that though.

File: compiler/rustc_metadata/src/rmeta/decoder.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (inquisitivecrystal) [reply compiler/rustc_metadata/src/rmeta/decoder.rs]: This got resolved [down here](https://github.com/rust-lang/rust/pull/88019#discussion_r691626636). Not sure why that got started as a seperate thread.

**Comment by inquisitivecrystal** [comment]
This should be ready for further review and possible approval! 🎉

**Review by petrochenkov — APPROVED** [review]

**Comment by petrochenkov** [comment]
The `macro-document-private-duplicate.rs` test introduced in this PR causes issues - https://github.com/rust-lang/rust/issues/89228.
