### PR TITLE
properly handle fat pointers to uninhabitable types

### LINKED ISSUE #94149: debug assertion failed: debug_assert_eq!((thin_pointer_size, thin_pointer_align), cx.size_and_align_of(ptr_type));
### Code
glacier fixed/83764.rs
```Rust
#![allow(dead_code)]

pub fn main() {
    // Instantiating Foo with a concrete type will not fail
    let _ = Foo::<dyn FooTrait>::new();
}

pub struct Foo<T: FooTrait + ?Sized> {
    base: FooBase,
    value: T,
}

impl<T: FooTrait + ?Sized> Foo<T> {
    pub fn new() -> Box<Foo<T>> {
        todo!()
    }
}

pub trait FooTrait {}

pub struct FooBase {
    cls: Bar,
}

// Bar *must* be a fieldless enum
pub enum Bar {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.60.0-dev
LLVM version: 14.0.0


/ 
commit b8c56fa8c30821129b0960180f528d4a1a4f9316 (origin/master, origin/HEAD)
Merge: feac2ecf1ca 0da7adc8283
Author: bors <bors@rust-lang.org>
Date:   Fri Feb 18 10:26:45 2022 +0000

```

### Error output
`rustc ./83764.rs -Cdebuginfo=2`
Note: you need a build with rustc debug assertions enabled!

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `(Size { raw: 8 }, Align { pow2: 3 })`,
 right: `(Size { raw: 16 }, Align { pow2: 3 })`', compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:450:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `(Size { raw: 8 }, Align { pow2: 3 })`,
 right: `(Size { raw: 16 }, Align { pow2: 3 })`', compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:450:13
stack backtrace:
   0:     0x7f8ea3f7f3df - std::backtrace_rs::backtrace::libunwind::trace::h913912a04742634a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f8ea3f7f3df - std::backtrace_rs::backtrace::trace_unsynchronized::hba81e1c01b02595d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8ea3f7f3df - std::sys_common::backtrace::_print_fmt::h4cd35453e855ed5b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f8ea3f7f3df - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b1eb54ecb507b6b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f8ea402d70e - core::fmt::write::h804d2b24173a7413
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f8ea3facb0f - std::io::Write::write_fmt::h4fbd6cffee6ce721
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1657:15
   6:     0x7f8ea3f7f20b - std::sys_common::backtrace::_print::h6dc864c7772bebae
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f8ea3f7f20b - std::sys_common::backtrace::print::h8df49d2ca55329c7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f8ea3f65334 - std::panicking::default_hook::{{closure}}::h32873a067c6a5b7e
   9:     0x7f8ea3f64efe - std::panicking::default_hook::h0eff11b253e72033
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:314:9
  10:     0x7f8ea7c3554a - <alloc[687cd566c0cfd4ba]::boxed::Box<dyn for<'a, 'b> core[54fe93355658fbe8]::ops::function::Fn<(&'a core[54fe93355658fbe8]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[54fe93355658fbe8]::marker::Send + core[54fe93355658fbe8]::marker::Sync> as core[54fe93355658fbe8]::ops::function::Fn<(&core[54fe93355658fbe8]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1868:9
  11:     0x7f8ea7c3554a - rustc_driver[aa71810babc01d8e]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:1153:13
  12:     0x7f8ea3f659d0 - std::panicking::rust_panic_with_hook::h2c545b2a73afb1b7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:702:17
  13:     0x7f8ea3f7f9d7 - std::panicking::begin_panic_handler::{{closure}}::h0a54097f79f25177
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:588:13
  14:     0x7f8ea3f7f504 - std::sys_common::backtrace::__rust_end_short_backtrace::hb04ef19ffcce15ab
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7f8ea3f655a2 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:584:5
  16:     0x7f8ea4021713 - core::panicking::panic_fmt::h6da8f1caaf923cda
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:143:14
  17:     0x7f8ea40219d8 - core::panicking::assert_failed_inner::ha1ab690e83c9da88
  18:     0x7f8ea80e9519 - core[54fe93355658fbe8]::panicking::assert_failed::<(rustc_target[20a254b8e8437e8d]::abi::Size, rustc_target[20a254b8e8437e8d]::abi::Align), (rustc_target[20a254b8e8437e8d]::abi::Size, rustc_target[20a254b8e8437e8d]::abi::Align)>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:182:5
  19:     0x7f8ea80502ca - rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::pointer_or_reference_metadata
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:450:13
  20:     0x7f8ea8051006 - rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::type_metadata
  21:     0x7f8ea80dcb49 - <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:1294:36
  22:     0x7f8ea80dcb49 - core[54fe93355658fbe8]::iter::adapters::map::map_fold::<(usize, &rustc_middle[6c01273334a4e0ad]::ty::FieldDef), rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, (), <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/map.rs:84:28
  23:     0x7f8ea80dcb49 - <core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<_> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::enumerate::<&rustc_middle[6c01273334a4e0ad]::ty::FieldDef, (), core[54fe93355658fbe8]::iter::adapters::map::map_fold<(usize, &rustc_middle[6c01273334a4e0ad]::ty::FieldDef), rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, (), <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/enumerate.rs:106:27
  24:     0x7f8ea80dcb49 - <core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::<(), <core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<_> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::enumerate<&rustc_middle[6c01273334a4e0ad]::ty::FieldDef, (), core[54fe93355658fbe8]::iter::adapters::map::map_fold<(usize, &rustc_middle[6c01273334a4e0ad]::ty::FieldDef), rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, (), <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:2285:21
  25:     0x7f8ea80dcb49 - <core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::<(), core[54fe93355658fbe8]::iter::adapters::map::map_fold<(usize, &rustc_middle[6c01273334a4e0ad]::ty::FieldDef), rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, (), <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/enumerate.rs:112:9
  26:     0x7f8ea80dcb49 - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::<(), core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/map.rs:124:9
  27:     0x7f8ea7f579bd - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::for_each::<<alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:773:9
  28:     0x7f8ea7f579bd - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::spec_extend
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/spec_extend.rs:40:17
  29:     0x7f8ea7f579bd - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_from_iter_nested::SpecFromIterNested<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::from_iter
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  30:     0x7f8ea7f579bd - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as alloc[687cd566c0cfd4ba]::vec::spec_from_iter::SpecFromIter<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>>::from_iter
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/spec_from_iter.rs:33:9
  31:     0x7f8ea804ecf6 - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription> as core[54fe93355658fbe8]::iter::traits::collect::FromIterator<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription>>::from_iter::<core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/mod.rs:2547:9
  32:     0x7f8ea804ecf6 - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::slice::iter::Iter<rustc_middle[6c01273334a4e0ad]::ty::FieldDef>>, <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions::{closure#0}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::collect::<alloc[687cd566c0cfd4ba]::vec::Vec<rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescription>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:1778:9
  33:     0x7f8ea804ecf6 - <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::StructMemberDescriptionFactory>::create_member_descriptions
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:1281:9
  34:     0x7f8ea804ecf6 - <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::MemberDescriptionFactory>::create_member_descriptions
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:1256:36
  35:     0x7f8ea804ecf6 - <rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::RecursiveTypeDescription>::finalize
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:360:43
  36:     0x7f8ea8051713 - rustc_codegen_llvm[ae3224fe635e8616]::debuginfo::metadata::type_metadata
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:749:32
  37:     0x7f8ea7f4564c - <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/mod.rs:443:63
  38:     0x7f8ea7f4564c - core[54fe93355658fbe8]::iter::adapters::map::map_fold::<&rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>, core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, (), <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, <alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/map.rs:84:28
  39:     0x7f8ea7f4564c - <core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::<(), core[54fe93355658fbe8]::iter::adapters::map::map_fold<&rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>, core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, (), <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}, core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, <alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:2285:21
  40:     0x7f8ea7f4564c - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::fold::<(), core[54fe93355658fbe8]::iter::traits::iterator::Iterator::for_each::call<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, <alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>>::spec_extend::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/map.rs:124:9
  41:     0x7f8ea7f4564c - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::for_each::<<alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>>::spec_extend::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:773:9
  42:     0x7f8ea7f4564c - <alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>>::spec_extend
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/spec_extend.rs:40:17
  43:     0x7f8ea7f4564c - <alloc[687cd566c0cfd4ba]::vec::Vec<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>> as core[54fe93355658fbe8]::iter::traits::collect::Extend<core[54fe93355658fbe8]::option::Option<&rustc_codegen_llvm[ae3224fe635e8616]::llvm_::ffi::Metadata>>>::extend::<core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::slice::iter::Iter<rustc_target[20a254b8e8437e8d]::abi::call::ArgAbi<rustc_middle[6c01273334a4e0ad]::ty::Ty>>, <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature::{closure#1}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/mod.rs:2618:9
  44:     0x7f8ea7f4564c - <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/mod.rs:442:17
  45:     0x7f8ea80b445d - <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/mod.rs:330:32
  46:     0x7f8ea7fe31b3 - <rustc_codegen_llvm[ae3224fe635e8616]::context::CodegenCx as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::debuginfo::DebugInfoMethods>::create_function_debug_context
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/debuginfo/mod.rs:308:13
  47:     0x7f8ea7fe31b3 - rustc_codegen_ssa[94c8fe1d8ce6ed46]::mir::codegen_mir::<rustc_codegen_llvm[ae3224fe635e8616]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mir/mod.rs:147:25
  48:     0x7f8ea80a5cba - rustc_codegen_ssa[94c8fe1d8ce6ed46]::base::codegen_instance::<rustc_codegen_llvm[ae3224fe635e8616]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/base.rs:361:5
  49:     0x7f8ea7f46ab6 - <rustc_middle[6c01273334a4e0ad]::mir::mono::MonoItem as rustc_codegen_ssa[94c8fe1d8ce6ed46]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[ae3224fe635e8616]::builder::Builder>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/mono_item.rs:69:17
  50:     0x7f8ea80959ab - rustc_codegen_llvm[ae3224fe635e8616]::base::compile_codegen_unit::module_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/base.rs:92:17
  51:     0x7f8ea802f3cf - <rustc_query_system[eed0fda852e3a6e5]::dep_graph::graph::DepGraph<rustc_middle[6c01273334a4e0ad]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6c01273334a4e0ad]::ty::context::TyCtxt, rustc_span[c11b030d3e5eb8ab]::symbol::Symbol, rustc_codegen_ssa[94c8fe1d8ce6ed46]::ModuleCodegen<rustc_codegen_llvm[ae3224fe635e8616]::ModuleLlvm>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/dep_graph/graph.rs:280:14
  52:     0x7f8ea80cab76 - rustc_codegen_llvm[ae3224fe635e8616]::base::compile_codegen_unit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/base.rs:62:23
  53:     0x7f8ea80cab76 - <rustc_codegen_llvm[ae3224fe635e8616]::LlvmCodegenBackend as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/lib.rs:119:9
  54:     0x7f8ea80d463f - rustc_codegen_ssa[94c8fe1d8ce6ed46]::base::codegen_crate::<rustc_codegen_llvm[ae3224fe635e8616]::LlvmCodegenBackend>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_ssa/src/base.rs:684:38
  55:     0x7f8ea80d463f - <rustc_codegen_llvm[ae3224fe635e8616]::LlvmCodegenBackend as rustc_codegen_ssa[94c8fe1d8ce6ed46]::traits::backend::CodegenBackend>::codegen_crate
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_codegen_llvm/src/lib.rs:329:18
  56:     0x7f8ea7ea8065 - rustc_interface[43bbf4653d387080]::passes::start_codegen::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:1106:9
  57:     0x7f8ea7ea8065 - <rustc_data_structures[261e35101f56a30d]::profiling::VerboseTimingGuard>::run::<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_interface[43bbf4653d387080]::passes::start_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:644:9
  58:     0x7f8ea7ea8065 - <rustc_session[97b3af9af03706a6]::session::Session>::time::<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_interface[43bbf4653d387080]::passes::start_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:16:9
  59:     0x7f8ea7ea8065 - rustc_interface[43bbf4653d387080]::passes::start_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:1105:19
  60:     0x7f8ea7ea8065 - <rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:253:20
  61:     0x7f8ea7ea8065 - <rustc_interface[43bbf4653d387080]::passes::QueryContext>::enter::<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:833:42
  62:     0x7f8ea7ebdb47 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_interface[43bbf4653d387080]::passes::QueryContext>::enter<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:50
  63:     0x7f8ea7ebdb47 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::set_tlv::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context<<rustc_interface[43bbf4653d387080]::passes::QueryContext>::enter<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1794:9
  64:     0x7f8ea7ebdb47 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_interface[43bbf4653d387080]::passes::QueryContext>::enter<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:9
  65:     0x7f8ea7ebdb47 - <rustc_interface[43bbf4653d387080]::passes::QueryContext>::enter::<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[54fe93355658fbe8]::result::Result<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:833:9
  66:     0x7f8ea7ebdb47 - <rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:244:13
  67:     0x7f8ea7ebdb47 - <rustc_interface[43bbf4653d387080]::queries::Query<alloc[687cd566c0cfd4ba]::boxed::Box<dyn core[54fe93355658fbe8]::any::Any>>>::compute::<<rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:37:28
  68:     0x7f8ea7ebdb47 - <rustc_interface[43bbf4653d387080]::queries::Queries>::ongoing_codegen
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:242:9
  69:     0x7f8ea7cd7b68 - rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:406:13
  70:     0x7f8ea7cd7b68 - <rustc_interface[43bbf4653d387080]::interface::Compiler>::enter::<rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}::{closure#2}, core[54fe93355658fbe8]::result::Result<core[54fe93355658fbe8]::option::Option<rustc_interface[43bbf4653d387080]::queries::Linker>, rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:390:19
  71:     0x7f8ea7c3d2f9 - rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:311:22
  72:     0x7f8ea7c3d2f9 - rustc_interface[43bbf4653d387080]::interface::create_compiler_and_run::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:227:13
  73:     0x7f8ea7c3d2f9 - rustc_span[c11b030d3e5eb8ab]::with_source_map::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_interface[43bbf4653d387080]::interface::create_compiler_and_run<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#1}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1013:5
  74:     0x7f8ea7cd5ad0 - rustc_interface[43bbf4653d387080]::interface::create_compiler_and_run::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:221:5
  75:     0x7f8ea7ca3575 - rustc_interface[43bbf4653d387080]::interface::run_compiler::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:241:12
  76:     0x7f8ea7ca3575 - <scoped_tls[4f101a79c47c0796]::ScopedKey<rustc_span[c11b030d3e5eb8ab]::SessionGlobals>>::set::<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  77:     0x7f8ea7ca3575 - rustc_span[c11b030d3e5eb8ab]::create_session_globals_then::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:111:5
  78:     0x7f8ea7ca3575 - rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals::<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:140:32
  79:     0x7f8ea7ca3575 - std[4f6852ddc6f39c7c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:122:18
  80:     0x7f8ea7c734ca - <std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_::<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:498:17
  81:     0x7f8ea7c734ca - <core[54fe93355658fbe8]::panic::unwind_safe::AssertUnwindSafe<<std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}::{closure#0}> as core[54fe93355658fbe8]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  82:     0x7f8ea7c734ca - std[4f6852ddc6f39c7c]::panicking::try::do_call::<core[54fe93355658fbe8]::panic::unwind_safe::AssertUnwindSafe<<std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}::{closure#0}>, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:492:40
  83:     0x7f8ea7c734ca - std[4f6852ddc6f39c7c]::panicking::try::<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, core[54fe93355658fbe8]::panic::unwind_safe::AssertUnwindSafe<<std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:456:19
  84:     0x7f8ea7c734ca - std[4f6852ddc6f39c7c]::panic::catch_unwind::<core[54fe93355658fbe8]::panic::unwind_safe::AssertUnwindSafe<<std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}::{closure#0}>, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:137:14
  85:     0x7f8ea7c734ca - <std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_::<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:497:30
  86:     0x7f8ea7c734ca - <<std[4f6852ddc6f39c7c]::thread::Builder>::spawn_unchecked_<rustc_interface[43bbf4653d387080]::util::run_in_thread_pool_with_globals<rustc_interface[43bbf4653d387080]::interface::run_compiler<core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>, rustc_driver[aa71810babc01d8e]::run_compiler::{closure#1}>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#0}, core[54fe93355658fbe8]::result::Result<(), rustc_errors[4ddc4d29baec38b8]::ErrorReported>>::{closure#1} as core[54fe93355658fbe8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:227:5
  87:     0x7f8ea3fbf753 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7de603aeff0ccdcb
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1854:9
  88:     0x7f8ea3fbf753 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62ca261b13b2b6c1
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1854:9
  89:     0x7f8ea3fbf753 - std::sys::unix::thread::Thread::new::thread_start::h7f6d9114f3f345c2
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
  90:     0x7f8ea3c5e259 - start_thread
  91:     0x7f8ea3d7b5e3 - __GI___clone
  92:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Calculate the pointee metadata size by using `tcx.struct_tail_erasing_lifetimes` instead of duplicating the logic in `fat_pointer_kind`. Open to alternatively suggestions on how to fix this.

Fixes #94149

r? @michaelwoerister since you touched this code last, I think!

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs [hunk 1]
```diff
@@ -437,19 +438,23 @@ fn pointer_or_reference_metadata<'ll, 'tcx>(
     unique_type_id: UniqueTypeId,
 ) -> MetadataCreationResult<'ll> {
     let pointee_type_metadata = type_metadata(cx, pointee_type);
+    let pointee_tail_type = cx.tcx.struct_tail_erasing_lifetimes(pointee_type, cx.param_env());
```
Comment (michaelwoerister) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:441]: Can you move this into `fat_pointer_kind()`? Then users of that function don't have to know about `struct_tail_erasing_lifetimes()`.

File: src/test/ui/debuginfo/debuginfo_with_uninhabitable_field_and_unsized.rs [hunk 2]
```diff
@@ -0,0 +1,28 @@
+// check-pass
+// compile-flags: -Cdebuginfo=2
+
```
Comment (michaelwoerister) [inline src/test/ui/debuginfo/debuginfo_with_uninhabitable_field_and_unsized.rs:3]: Please add a comment that this fixes https://github.com/rust-lang/rust/issues/94149.

**Review by michaelwoerister — COMMENTED** [review]
Thanks for the PR, @compiler-errors! Looks great. I'll be happy to r+ with the comments below addressed.

**Comment by michaelwoerister** [comment]
Also, please squash the commits.

**Comment by michaelwoerister** [comment]
Thanks!
@bors r+
