### PR TITLE
Fix theme-checker failure

### LINKED ISSUE #61145: rustdoc --theme-checker panics when given an empty file
When I run the following commands:

```
touch empty-file.css
RUST_BACKTRACE=1 rustdoc -Z unstable-options --theme-checker empty-file.css
```

Rustdoc outputs the following:

```
rustdoc: [theme-checker] Starting tests!
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/librustdoc/theme.rs:114:15
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: rustdoc::theme::load_css_paths
  10: rustdoc::theme::test_theme_against
  11: rustdoc::config::Options::from_matches
  12: rustdoc::main_args
 - Checking "empty-file.css"...
```

I would have expected it to output a list of missing rules, without panicking.

## Meta

`rustc --version --verbose`:

```
rustc 1.36.0-nightly (dec4c5201 2019-05-24)
binary: rustc
commit-hash: dec4c5201f88efbc3020b04ba96a5ee2c3b6cfcd
commit-date: 2019-05-24
host: x86_64-unknown-linux-gnu
release: 1.36.0-nightly
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #61145.

I didn't find a way to check it without strongly depending on the output... Is there a way to check if a program fails without checking its output?

r? @QuietMisdreavus

### CODE REVIEW

**Comment by czipperz** [comment]
You should probably add a regression test here if possible

**Comment by GuillaumeGomez** [comment]
@czipperz:

> I didn't find a way to check it without strongly depending on the output... Is there a way to check if a program fails without checking its output?

**Comment by czipperz** [comment]
Try writing a test on this function?

**Comment by czipperz** [comment]
It doesn't even need to assert anything. TDD dictates you need a failing test case to change code. Panicking is failing the test

**Comment by czipperz** [comment]
Or `assert_eq!(load_css_events(Vec::new()), Vec::new());`

**Comment by czipperz** [comment]
Are you referring to a system level test here? That might be more difficult.

**Comment by GuillaumeGomez** [comment]
I was speaking at a system level, indeed. :) I'll add a function test instead.

**Comment by GuillaumeGomez** [comment]
I added a test but like I said, I don't think this is the best way. I guess it'll work for now...

**Comment by czipperz** [comment]
It seems the check `pos + 1 < v.len()` is duplicated multiple times in the while loop body.  What do you think about eliminating these?

**Comment by GuillaumeGomez** [comment]
I think it's a valid request so I'll remove them.

**Comment by GuillaumeGomez** [comment]
Removed them!

**Comment by Manishearth** [comment]
I don't really have time to review this rn.

**Comment by GuillaumeGomez** [comment]
Let's try someone else then!

cc @rust-lang/rustdoc

File: src/librustdoc/theme.rs [hunk 1]
```diff
@@ -103,16 +103,16 @@ fn is_line_comment(pos: usize, v: &[u8], events: &[Events]) -> bool {
     if let Some(&Events::StartComment(_)) = events.last() {
         return false;
     }
-    pos + 1 < v.len() && v[pos + 1] == b'/'
+    v[pos + 1] == b'/'
```
Comment (kinnison) [inline src/librustdoc/theme.rs]: This is going to panic if `is_line_comment()` is called with `pos +1 >= v.len()` - is the introduction of that panic intentional or is this fallout from fixing the tests in `load_css_events()` ?

Comment (kinnison) [reply src/librustdoc/theme.rs]: Would `v.get(pos+1) == Some(b'/')` be acceptable if you want to avoid the `pos + 1 < v.len()`?

File: src/librustdoc/theme.rs [hunk 2]
```diff
@@ -264,9 +264,11 @@ pub fn get_differences(against: &CssPath, other: &CssPath, v: &mut Vec<String>)
...
 }
 
-pub fn test_theme_against<P: AsRef<Path>>(f: &P, against: &CssPath, diag: &Handler)
-    -> (bool, Vec<String>)
-{
+pub fn test_theme_against<P: AsRef<Path>>(
+    f: &P,
+    against: &CssPath,
+    diag: &Handler,
+) -> (bool, Vec<String>) {
```
Comment (kinnison) [inline src/librustdoc/theme.rs]: This reflowing seems to be spurious in terms of this patch.  Is it a result of `rustfmt` being run and if so, should it be here?  I don't know the policy on unrelated changes in this codebase.

**Review by kinnison — COMMENTED** [review]
A few comments, but otherwise LGTM.  I'm not sure if I'm able to approve properly on this codebase but you have a :+1: from me modulo the query about panicing.

File: src/librustdoc/theme.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/theme.rs]: Normally it shouldn't be possible to be called with such an issue arising thanks to the change line 113:

```rust
while pos + 1 < v.len() {
```

However, this is a good point and I think I'll update the code to what you suggested.

File: src/librustdoc/theme.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/theme.rs]: No, just me when reading code. A bad habit. In small PRs such as this one, we generally just don't look at it.

**Comment by GuillaumeGomez** [comment]
@kinnison Updated!

File: src/librustdoc/theme.rs (hunk 1 above)
Comment (kinnison) [reply src/librustdoc/theme.rs]: Based on high-five, looks like my suggestion missed a borrow :-/

File: src/librustdoc/theme.rs (hunk 2 above)
Comment (kinnison) [reply src/librustdoc/theme.rs]: Okay, I'll consider this resolved.

**Review by kinnison — APPROVED** [review]
Modulo the need for a borrow in that rewritten test, which I've just realised is in a non-public function so your comment about the guard in the public function meaning it won't be necessary anyway holds, :+1:

**Comment by GuillaumeGomez** [comment]
Removed the last commit then. Thanks for your review!

@bors: r=kinnison
