### PR TITLE
Stop using `translate_args` in the new solver

### LINKED ISSUE #115: reimplement `translate_args` inside of the solver
It is used by the solver while using fulfillment. This means it may be broken in a bunch of ways, e.g. by resulting in unguarded recursion.

We should reimplemented this using the `EvalCtxt` itself

### PR DESCRIPTION
**Pull request by compiler-errors**
It was unnecessary and also sketchy, since it was doing an out-of-search-graph fulfillment loop. Added a test for the only really minor subtlety of translating args, though not sure if it was being tested before, though I wouldn't be surprised if it wasn't.

r? lcnr

### CODE REVIEW

File: tests/ui/specialization/source-impl-requires-constraining-predicates.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+}
+
+default impl<T, U> Spec for T where T: IntoIterator<Item = U> {
+    type Assoc = U;
+}
+
+impl<T> Spec for [T; 0] {}
+
+fn main() {
+    let x: <[u32; 0] as Spec>::Assoc = 1;
```
Comment (lcnr) [inline tests/ui/specialization/source-impl-requires-constraining-predicates.rs:21]: you're not testing the `[_; 0]` ice?

Comment (compiler-errors) [reply tests/ui/specialization/source-impl-requires-constraining-predicates.rs:23]: Added a test for the ambiguity case, and known-bug:unknown in the old solver

File: compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs [hunk 2]
```diff
@@ -235,14 +234,38 @@ impl<'tcx> assembly::GoalKind<'tcx> for NormalizesTo<'tcx> {
...
+                            GoalSource::Misc,
+                            tcx.predicates_of(target_impl_def_id)
+                                .instantiate(tcx, target_args)
+                                .into_iter()
+                                .map(|(pred, _)| goal.with(tcx, pred)),
+                        );
+                        impl_args_with_gat.rebase_onto(tcx, impl_def_id, target_args)
+                    }
+                }
+            };
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs:268]: can you move this into a seperate method? :thinking: it's fairly involved and feels like it's also conceptionally self-contained.

**Review by lcnr — COMMENTED** [review]
r=me after nit

File: compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs [hunk 3]
```diff
@@ -889,6 +882,43 @@ impl<'tcx> assembly::GoalKind<'tcx> for NormalizesTo<'tcx> {
     }
 }
 
+fn translate_args<'tcx>(
+    ecx: &mut EvalCtxt<'_, InferCtxt<'tcx>>,
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs:886]: why is that not a method on `EvalCtxt`? :sweat_smile:

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs:886]: 🤷 `fetch_eligible_assoc_item_def` isn't one either

Comment (lcnr) [reply compiler/rustc_trait_selection/src/solve/normalizes_to/mod.rs:886]: i feel like both should be, r=me with or without that change
