### PR TITLE
Tweak E0277 when predicate comes indirectly from ?

### LINKED ISSUE #137238: Provide more context on `?` where the error type can't be converted to the expected one
### Code

```Rust
struct E;

fn foo() -> Result<(), Box<dyn std::error::Error>> {
    Ok(bar()?)
}
fn bar() -> Result<(), E> {
    Err(E)
}
fn main() {}
```

### Current output

```Shell
error[E0277]: the trait bound `E: std::error::Error` is not satisfied
 --> bad.rs:4:13
  |
4 |     Ok(bar()?)
  |             ^ the trait `std::error::Error` is not implemented for `E`
  |
  = help: the trait `FromResidual<Result<Infallible, E>>` is implemented for `Result<T, F>`
  = note: required for `Box<dyn std::error::Error>` to implement `From<E>`
```

### Desired output

```Shell
error[E0277]: the trait bound `E: std::error::Error` is not satisfied
 --> bad.rs:4:13
  |
X | struct E;
  |        - doesn't implement trait `std::error::Error`
...
X | fn foo() -> Result<(), Box<dyn std::error::Error>> {
  |             -------------------------------------- requires that `Box<dyn std::error::Error>` implements `From<E>`
X |     Ok(bar()?)
  |             ^ the trait `From<E>` is not implemented for `Box<dyn std::error::Error>`
  |
  = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
```

### Rationale and extra context

As far as the (stable) end user is concerned, `?` is a little more than a compiler intrinsic. We shouldn't mention `FromResidual`. We also should provide extra context on where the obligation comes from, and we should point at the return type of the enclosing function, and ideally also point at the type that couldn't be converted which is missing a `From` or `Into` impl.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.86.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.86.0-dev
LLVM version: 19.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When a `?` operation requires an `Into` conversion with additional bounds (like having a concrete error but wanting to convert to a trait object), we handle it speficically and provide the same kind of information we give other `?` related errors.

```
error[E0277]: `?` couldn't convert the error: `E: std::error::Error` is not satisfied
  --> $DIR/bad-question-mark-on-trait-object.rs:7:13
   |
LL | fn foo() -> Result<(), Box<dyn std::error::Error>> {
   |             -------------------------------------- required `E: std::error::Error` because of this
LL |     Ok(bar()?)
   |        -----^ the trait `std::error::Error` is not implemented for `E`
   |        |
   |        this has type `Result<_, E>`
   |
note: `E` needs to implement `std::error::Error`
  --> $DIR/bad-question-mark-on-trait-object.rs:1:1
   |
LL | struct E;
   | ^^^^^^^^
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = note: required for `Box<dyn std::error::Error>` to implement `From<E>`
```

Avoid talking about `FromResidual` when other more relevant information is being given, particularly from `rust_on_unimplemented`.

Fix #137238.

-----

CC #137232, which was a smaller step related to this.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs [hunk 1]
```diff
@@ -966,6 +966,47 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                if let ty::Adt(def, _) = ty.kind()
+                    && def.did().is_local() =>
+            {
+                err.span_note(
+                    self.tcx.def_span(def.did()),
+                    format!("`{ty}` needs to implement `Into<{self_ty}>`"),
+                );
+            }
+            _ => {}
+        }
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs:1009]: pull into separate function

**Review by oli-obk — CHANGES_REQUESTED** [review]
just a nit, this is gonna be very useful!

File: compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/error_reporting/traits/fulfillment_errors.rs]: Done
