### PR TITLE
Don't warn about dead foreign items if the 'allow(dead_code)' attribute is present

### LINKED ISSUE #38780: allow(dead_code) does not work for static externs
The following Rust code:

```rust
extern "C" {
    #[allow(dead_code)]
    static Qt: u64;
}

fn main() {
    println!("hello world");
}
```

produces the warning:

```
warning: foreign static item is never used: `Qt`, #[warn(dead_code)] on by default
```
in spite of the `allow(dead_code)` annotation.

### PR DESCRIPTION
**Pull request by dylanmckay**
This functionality was missing, and should have existed previously.

Fixes #38780

### CODE REVIEW

File: src/librustc/middle/dead.rs [hunk 1]
```diff
@@ -445,6 +445,11 @@ impl<'a, 'tcx> DeadVisitor<'a, 'tcx> {
             && !has_allow_dead_code_or_lang_attr(&variant.attrs)
     }
 
+    fn should_warn_about_foreign_item(&mut self, fi: &hir::ForeignItem) -> bool {
+        !self.symbol_is_live(fi.id, None)
+            && !has_allow_dead_code_or_lang_attr(&fi.attrs)
```
Comment (eddyb) [inline src/librustc/middle/dead.rs]: Pre-existing but why do we snoop lint attributes instead of registering the lints and letting the lint pass track them? cc @rust-lang/compiler

**Review by eddyb — APPROVED** [review]
