### PR TITLE
avoid type-check body of DefId

### LINKED ISSUE #60049: ICE: can't type-check body of DefId
This short snippet crashes the nightly compiler:

    enum Foo {
        Bar(usize),
    }
    
    fn main() {
        let i = Foo::Bar;
        assert_eq!(Foo::Bar, i);
    }

Crashes with:

    error: internal compiler error: src/librustc_typeck/check/mod.rs:825: can't type-check body of DefId(0/1:10 ~ lib[317d]::Foo[0]::Bar[0]::{{constructor}}[0])
     --> src/lib.rs:2:3
      |
    2 |   Bar(usize),
      |   ^^^^^^^^^^
    
    thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:570:9

rustc 1.35.0-nightly (70f130954 2019-04-16) running on x86_64-apple-darwin
Seems to work on stable on the playground (don't have stable locally).

### PR DESCRIPTION
**Pull request by rchaser53**
fix: #60049
related: PR #59798

### CODE REVIEW

File: src/test/ui/issues/issue-59488.rs [hunk 1]
```diff
@@ -8,19 +8,30 @@ fn bar(a: i64) -> i64 {
...
 
+enum Foo {
+    Bar(usize),
+}
+
 fn main() {
     foo > 12;
-    //~^ ERROR 12:9: 12:10: binary operation `>` cannot be applied to type `fn() -> i32 {foo}` [E0369]
-    //~| ERROR 12:11: 12:13: mismatched types [E0308]
+    //~^ ERROR 16:9: 16:10: binary operation `>` cannot be applied to type `fn() -> i32 {foo}` [E0369]
```
Comment (hellow554) [inline src/test/ui/issues/issue-59488.rs]: You could have moved the definition of the enum to the bottom and therefore prevent changing all the linenumbers.

Comment (rchaser53) [reply src/test/ui/issues/issue-59488.rs]: I didn't know. Thank you!

Comment (hellow554) [reply src/test/ui/issues/issue-59488.rs]: I don't know if that works what you did (I don't have much experience with the test framework). I meant, that instead of writing `enum foo { ... } fn main() { ... }` you could've done `fn main() { ... } enum foo { ... }`.

Comment (rchaser53) [reply src/test/ui/issues/issue-59488.rs]: Maybe it works. I read this commit.
https://github.com/rust-lang/rust/commit/8f77a035a43158d6d997d6c71e36e4a2c7eb7336#diff-64ce4eb189ca06032c10f8fbc3a5a62aL13

Comment (hellow554) [reply src/test/ui/issues/issue-59488.rs]: Travis will tell us ;)

Comment (hellow554) [reply src/test/ui/issues/issue-59488.rs]: 🎉

**Comment by estebank** [comment]
Please remove the merge commit and rebase on top of master

**Review by estebank — APPROVED** [review]
After rebasing r=me

**Comment by rchaser53** [comment]
Sorry. I removed the merge commit and rebased on top of master.

**Comment by estebank** [comment]
@rchaser53 you'll have to rebase again :(

**Comment by rchaser53** [comment]
Oh! I rebased again.
