### PR TITLE
Fix some unsoundness with PassMode::Cast ABI

### LINKED ISSUE #122617: PassMode::Cast results in LLVM IR with out of bounds loads
I tried this code:

```rust
// On a target that uses cast ABI, e.g. --target=aarch64-unknown-linux-gnu

#![crate_type = "lib"]

#[repr(C)]
pub struct TwoU16s {
    one: u16,
    two: u16,
}

extern "C" {
    pub fn rust_dbg_extern_identity_TwoU16s(v: TwoU16s) -> TwoU16s;
}

#[no_mangle]
pub unsafe fn foo() {
    let x = TwoU16s { one: 0, two: 0 };
    rust_dbg_extern_identity_TwoU16s(x);
}

```

I expected to see this happen: No UB.

Instead, this happened: https://godbolt.org/z/bd8MT4bEM

```ll
define void @foo() {
start:
  %0 = alloca i64, align 8
  %1 = alloca { i16, i16 }, align 2
  %2 = alloca { i16, i16 }, align 2
  %3 = getelementptr inbounds { i16, i16 }, ptr %2, i32 0, i32 0
  store i16 0, ptr %3, align 2
  %4 = getelementptr inbounds { i16, i16 }, ptr %2, i32 0, i32 1
  store i16 0, ptr %4, align 2
  %5 = load i64, ptr %2, align 2
  %6 = call i64 @rust_dbg_extern_identity_TwoU16s(i64 %5)
  call void @llvm.lifetime.start.p0(i64 4, ptr %1)
  call void @llvm.lifetime.start.p0(i64 4, ptr %0)
  store i64 %6, ptr %0, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 2 %1, ptr align 8 %0, i64 4, i1 false)
  call void @llvm.lifetime.end.p0(i64 4, ptr %0)
  %7 = getelementptr inbounds { i16, i16 }, ptr %1, i32 0, i32 0
  %_1.0 = load i16, ptr %7, align 2, !noundef !2
  %8 = getelementptr inbounds { i16, i16 }, ptr %1, i32 0, i32 1
  %_1.1 = load i16, ptr %8, align 2, !noundef !2
  call void @llvm.lifetime.end.p0(i64 4, ptr %1)
  ret void
}
```

There are two problems here, first:

```ll
%2 = alloca { i16, i16 }, align 2
...
%5 = load i64, ptr %2, align 2
```
...we load 8 bytes from a 4 byte alloca. Alive2 believes this is UB: https://alive2.llvm.org/ce/z/eBaekz.

Second:
```ll
call void @llvm.lifetime.start.p0(i64 4, ptr %0)
store i64 %6, ptr %0, align 8
call void @llvm.lifetime.end.p0(i64 4, ptr %0)
```
...only 4 bytes of `%0` are marked live, but we access 8 bytes. The [langref](https://llvm.org/docs/LangRef.html#llvm-lifetime-start-intrinsic) is not clear about what the size arguments of lifetime intrinsics actually do, but this is probably UB. (Alive2 ignores the size arguments, so it can't detect this.)

@rustbot label I-unsound A-ffi

---

This was uncovered via https://github.com/rust-lang/rust/pull/122053#issuecomment-2002076888, where this issue is the root cause of a miscompilation. That comment contains a bit more context.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

(also reproducible on very recent master 766bdce744d531267d53ba2a3f9ffcda69fb9b17)

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #122617

Reviewable commit-by-commit. More info in each commit message.

### CODE REVIEW

File: tests/codegen/cast-target-abi.rs [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+
+    // powerpc64: [[RETVAL:%.+]] = alloca %DoubleFloat, align 8
+    // powerpc64: call void @returns_doublefloat(ptr {{.+}} [[RETVAL]])
+
+
+    // The other targets copy the cast ABI type to an alloca.
+
+    // aarch64:     [[ABI_ALLOCA:%.+]] = alloca [[ABI_TYPE:\[2 x i64\]]], align [[ABI_ALIGN:8]]
+    // loongarch64: [[ABI_ALLOCA:%.+]] = alloca [[ABI_TYPE:{ double, float }]], align [[ABI_ALIGN:8]]
+    // sparc64:     [[ABI_ALLOCA:%.+]] = alloca [[ABI_TYPE:{ double, float, i32, i64 }]], align [[ABI_ALIGN:8]]
```
Comment (erikdesjardins) [inline tests/codegen/cast-target-abi.rs:251]: `{ double, float, i32, i64 }` is almost certainly the wrong type.

But, if you try to use `struct DoubleFloat` on sparc64 on stable, it _crashes_ (https://godbolt.org/z/bKn6d5jeM), so this isn't a regression.

So, I don't think this needs to be fixed as part of this PR. Opened #122620 to track this issue.

File: compiler/rustc_target/src/abi/call/sparc64.rs [hunk 2]
```diff
@@ -35,12 +35,14 @@ where
...
-        data.last_offset = data.last_offset + Reg::i64().size;
+    if data.last_offset < offset {
+        for _ in 0..((offset - data.last_offset).bits() / 64)
+            .min((data.prefix.len() - data.prefix_index) as u64)
+        {
+            data.prefix[data.prefix_index] = Some(Reg::i64());
+            data.prefix_index += 1;
+            data.last_offset = data.last_offset + Reg::i64().size;
+        }
     }
```
Comment (erikdesjardins) [inline compiler/rustc_target/src/abi/call/sparc64.rs:46]: I believe this new `if` can never change behavior, except in cases which would panic before.

Going case-by-case:
- `data.last_offset < offset`: we enter the loop, as before
- `data.last_offset == offset`: after this change, we skip the loop; before this change, `offset - data.last_offset` is zero, so the loop iterates over `0..0`, so the loop executes zero iterations, which is equivalent
- `data.last_offset > offset`: after this change, we skip the loop; before this change `offset - data.last_offset` panics due to overflow

File: tests/codegen/cast-target-abi.rs (hunk 1 above)
Comment (erikdesjardins) [reply tests/codegen/cast-target-abi.rs]: Upon reflection, I think this would be a regression. It's better to ICE than to generate incorrect code.

Pushed some commits to remove the ICE fix and instead cfg out this test on sparc.

**Comment by TaKO8Ki** [comment]
reroll r? compiler

File: compiler/rustc_codegen_llvm/src/abi.rs [hunk 3]
```diff
@@ -211,47 +211,33 @@ impl<'ll, 'tcx> ArgAbiExt<'ll, 'tcx> for ArgAbi<'tcx, Ty<'tcx>> {
                 bug!("unsized `ArgAbi` must be handled through `store_fn_arg`");
             }
             PassMode::Cast { cast, pad_i32: _ } => {
-                // FIXME(eddyb): Figure out when the simpler Store is safe, clang
-                // uses it for i16 -> {i8, i8}, but not for i24 -> {i8, i8, i8}.
-                let can_store_through_cast_ptr = false;
```
Comment (compiler-errors) [inline compiler/rustc_codegen_llvm/src/abi.rs:220]: lol

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
Thanks @erikdesjardins.

@bors r+

**Comment by apiraino** [comment]
Beta backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-04-04/near/431322008): it's fine to let this ride the trains, the backport would be somehow complex.

@rustbot label -beta-nominated
