### PR TITLE
bootstrap/codegen_ssa: ship llvm-strip and use it for -Cstrip

### LINKED ISSUE #131206: Hard-coded `strip` path breaks Linux -> Darwin builds
I cross-compile code for Darwin from Linux, which now fails due to the `strip` path being hard-coded in latest nightly, which I believe is caused by this PR https://github.com/rust-lang/rust/pull/130781

I expected to see this happen: successful compilation

Instead, this happened:
```
error: unable to run `/usr/bin/strip`: No such file or directory (os error 2)
```

https://github.com/rvolosatovs/nixify/actions/runs/11163623704/job/31031050404?pr=265

I'm not sure why `/usr/bin/strip` was chosen as the `strip` to use, as an end user - that is surprising, in fact I would have expected the `strip` from the environment to be used by default. If the intention is to set a default to a hardcoded path, then it looks like a configuration option must be provided.

Alternatively, perhaps `cargo` could use `/usr/bin/strip` if found and otherwise use `strip` from environment?

### Version it worked on

It most recently worked on: 1.80.1

### Version with regression

`rustc --version --verbose`:
```
cargo 1.83.0-nightly (80d82ca22 2024-09-27)
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #131206.

- Includes `llvm-strip` (a symlink to `llvm-objcopy`) in the compiler dist artifact so that it can be used for `-Cstrip` instead of the system tooling.
- Uses `llvm-strip` instead of `/usr/bin/strip` for macOS. macOS needs a specific linker and the system one is preferred, hence #130781 but that doesn't work when cross-compiling, so use the `llvm-strip` utility instead.

cc #123151

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/dist.rs [hunk 1]
```diff
@@ -473,6 +473,14 @@ impl Step for Rustc {
                     );
                 }
             }
+
+            {
+                let src_dir = builder.sysroot_libdir(compiler, host).parent().unwrap().join("bin");
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/dist.rs:478]: Remark: this seems like it should be `sysroot_bindir` if it doesn't already exist

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 2]
```diff
@@ -1965,6 +1965,16 @@ impl Step for Assemble {
             }
         }
 
+        {
+            // `llvm-strip` is used by rustc, which is actually just a symlink to `llvm-objcopy`,
+            // so copy and rename `llvm-objcopy` and create link for `rust-strip`
+            let src_exe = exe("llvm-objcopy", target_compiler.host);
+            let dst_exe = exe("rust-objcopy", target_compiler.host);
+            builder.copy_link(&libdir_bin.join(src_exe), &libdir_bin.join(dst_exe));
+            let dst_exe = exe("rust-strip", target_compiler.host);
```
Comment (lqd) [inline src/bootstrap/src/core/build_steps/compile.rs:1974]: do you really need the symlink, since the strip command used in the compiler is `rust-objcopy`?

Comment (davidtwco) [reply src/bootstrap/src/core/build_steps/compile.rs]: Removed the symlink, this was a holdover from before I hit the "symlink can't be added to tarball" check.

File: src/bootstrap/src/core/build_steps/dist.rs (hunk 1 above)
Comment (davidtwco) [reply src/bootstrap/src/core/build_steps/dist.rs]: Makes sense, fixed.

File: src/bootstrap/src/core/builder.rs [hunk 3]
```diff
@@ -1151,6 +1151,11 @@ impl<'a> Builder<'a> {
         self.ensure(compile::Sysroot::new(compiler))
     }
 
+    /// Returns the bindir for a compiler's sysroot.
```
Comment (lqd) [inline src/bootstrap/src/core/builder.rs:1154]: Probably t-bootstrap will have opinions here, because there are 2 "bin" directories 😓

**Comment by workingjubilee** [comment]
Thank you for posting this. I tried twice and couldn't even figure out where to start.

**Comment by taiki-e** [comment]
> illumos 

AFAIK some change is needed for illumos too because using the default strip binary of Linux host causes a problem (https://github.com/oxidecomputer/helios/issues/147).
However, I have not actually tested to see if using LLVM strip would solve the problem. ([This comment](https://github.com/rust-lang/rust/blob/68e4d9654ea5bd3553c892a23f42b4f17b37e5f1/compiler/rustc_codegen_ssa/src/back/link.rs#L1107-L1109) may indicate that anything other than native strip utility would not work.)

cc @sunshowers

**Comment by jclulow** [comment]
> @jclulow (we have no target maintainers for the illumos targets in the documentation, but I've seen @jclulow in the issue tracker and I know is involved in illumos)

Hey, with my apologies, someone pointed this out to me recently and I owe a PR to fix the docs and list some maintainers there.

> We could make this same change to the illumos and AIX targets which also hardcode a path to a strip binary. Pinging relevant people for those targets to see if this would be desirable.

When we're running on an illumos host and compiling for an illumos target, we definitely want to use the system **strip** binary explicitly.  If we're cross compiling, either on an illumos host for a non-illumos target, or on a non-illumos host, I don't have a particular preference and we should do whatever is tested to work there.

Does that make sense?

**Comment by bzEq** [comment]
On AIX, we are still using `/usr/bin/strip`. `llvm-strip` is not compatible with AIX's system `strip` utility.

**Comment by davidtwco** [comment]
> Thanks for headsup. On AIX, we are still using `/usr/bin/strip`. `llvm-strip` is not compatible with AIX's system `strip` utility.

Okay, I've kept AIX's logic as it is, but I have added a warning when cross-compiling that whatever is in `/usr/bin/strip` may not work because it isn't AIX's system `strip`.

> When we're running on an illumos host and compiling for an illumos target, we definitely want to use the system **strip** binary explicitly. If we're cross compiling, either on an illumos host for a non-illumos target, or on a non-illumos host, I don't have a particular preference and we should do whatever is tested to work there.
> 
> Does that make sense?

That makes sense. I've kept `/usr/bin/strip` if not cross-compiling, and we'll now use `llvm-strip` instead of `/usr/bin/strip` when cross-compiling (that seems more likely to work reliably than relying on whatever `/usr/bin/strip` could be). I also changed the condition we used here from `target.os == "illumos"` to `target.is_like_solaris`, since that's why we have `is_like_solaris` in the first place. Let me know if that's not correct and there is some difference with stripping between illumos and solaris in general.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 4]
```diff
@@ -1147,6 +1148,13 @@ fn strip_symbols_with_external_utility(
     if let Some(option) = option {
         cmd.arg(option);
     }
+
+    let mut new_path = sess.get_tools_search_paths(false);
+    if let Some(path) = env::var_os("PATH") {
+        new_path.extend(env::split_paths(&path));
+    }
+    cmd.env("PATH", env::join_paths(new_path).unwrap());
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1163]: It probably is but we override the `PATH` for `rust-lld` so I'll keep it this way and we can change both together later.

**Review by albertlarsan68 — COMMENTED** [review]
LGTM for the technical side in bootstrap

**Comment by albertlarsan68** [comment]
r? t-compiler for the compiler side of things

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1162]: Ah, do we? I remember we set the linker search path to the lld wrappers in the sysroot without overriding the PATH (so they should execute `../rust-lld` without overrides), and that rustup ensures the PATH contains the bin and rustlib/bin folders, but didn’t remember rustc overrode it for rust-lld.

[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1162]: https://github.com/rust-lang/rust/blob/bca5fdebe0e539d123f33df5f2149d5976392e76/compiler/rustc_codegen_ssa/src/back/linker.rs#L130

I believe this is where it happens

[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1162]: Yeah that's indeed likely it for the targets involving the linker directly. We don't need/make use of that on the common linux/mac targets.

**Comment by cjgillot** [comment]
r? compiler

**Comment by jieyouxu** [comment]
r? jieyouxu

File: src/bootstrap/src/core/builder/mod.rs [hunk 5]
```diff
@@ -1161,6 +1161,11 @@ impl<'a> Builder<'a> {
         self.ensure(compile::Sysroot::new(compiler))
     }
 
+    /// Returns the bindir for a compiler's sysroot.
+    pub fn sysroot_bindir(&self, compiler: Compiler, target: TargetSelection) -> PathBuf {
+        self.sysroot_libdir(compiler, target).parent().unwrap().join("bin")
+    }
```
Comment (jieyouxu) [inline src/bootstrap/src/core/builder/mod.rs:1167]: Remark (for myself): send a follow-up to avoid this dance

**Review by jieyouxu — APPROVED** [review]
Thanks, this looks good to me (with compiler hat 🎩 on). Feel free to r=albertlarsan68 and me after a rebase.

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 6]
```diff
@@ -1977,6 +1976,14 @@ impl Step for Assemble {
             }
         }
 
+        {
+            // `llvm-strip` is used by rustc, which is actually just a symlink to `llvm-objcopy`,
+            // so copy and rename `llvm-objcopy`.
+            let src_exe = exe("llvm-objcopy", target_compiler.host);
+            let dst_exe = exe("rust-objcopy", target_compiler.host);
+            builder.copy_link(&libdir_bin.join(src_exe), &libdir_bin.join(dst_exe));
+        }
```
Comment (bjorn3) [inline src/bootstrap/src/core/build_steps/compile.rs:1985]: This breaks bootstrapping when the bootstrap compiler doesn't contain any LLVM tools as is the case when cg_clif bootstraps rustc:

```
Building stage0 tool lld-wrapper (x86_64-unknown-linux-gnu)
     Compiling lld-wrapper v0.1.0 (/home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/rust/src/tools/lld-wrapper)
      Finished `release` profile [optimized] target(s) in 0.43s
  thread 'main' panicked at src/lib.rs:1714:24:
src.symlink_metadata() failed with No such file or directory (os error 2) ("src = /home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objcopy")
```

It should probably check `builder.config.llvm_enabled(target_compiler.host) && builder.config.llvm_tools_enabled` before copying to ensure that `llvm-objcopy` exists in the first place.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/compile.rs:1985]: Thanks for the heads-up, I'll send a follow-up to fix that.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/compile.rs:1985]: Follow-up: https://github.com/rust-lang/rust/pull/132720

File: src/bootstrap/src/core/builder/mod.rs (hunk 5 above)
Comment (jieyouxu) [reply src/bootstrap/src/core/builder/mod.rs]: Follow-up PR: https://github.com/rust-lang/rust/pull/132723
