### PR TITLE
stabilize `array_windows`

### LINKED ISSUE #75027: Tracking Issue for slice::array_windows
The feature gate for the issue is `#![feature(array_windows)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Restrict `N` to values greater than 0 at compile time instead of using a runtime panic.
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

- implemented in #75026

### PR DESCRIPTION
**Pull request by bend-n**
Tracking issue: rust-lang/rust#75027
Closes: rust-lang/rust#75027
FCP completed: https://github.com/rust-lang/rust/issues/75027#issuecomment-3477510526

### CODE REVIEW

File: library/core/src/slice/iter.rs [hunk 1]
```diff
@@ -2200,20 +2198,23 @@ unsafe impl<T> Sync for ChunksExactMut<'_, T> where T: Sync {}
...
+#[stable(feature = "array_windows", since = "CURRENT_RUSTC_VERSION")]
 #[must_use = "iterators are lazy and do nothing unless consumed"]
 pub struct ArrayWindows<'a, T: 'a, const N: usize> {
     v: &'a [T],
 }
-
+#[stable(feature = "array_windows", since = "CURRENT_RUSTC_VERSION")]
+unsafe impl<'a, T: Send, const N: usize> Send for ArrayWindows<'a, T, N> {}
+#[stable(feature = "array_windows", since = "CURRENT_RUSTC_VERSION")]
+unsafe impl<'a, T: Sync, const N: usize> Sync for ArrayWindows<'a, T, N> {}
```
Comment (Kivooeo) [inline library/core/src/slice/iter.rs]: Hm, why this were added?

Comment (bend-n) [reply library/core/src/slice/iter.rs]: my bad, sorry.

File: library/core/src/slice/mod.rs [hunk 2]
```diff
@@ -1620,13 +1620,15 @@ impl<T> [T] {
     ///
     /// # Panics
     ///
-    /// Panics if `N` is zero. This check will most probably get changed to a compile time
```
Comment (GrigorenkoPV) [inline library/core/src/slice/mod.rs:1623]: Maybe the assertion should be wrapped in a `const` block to give the panic during the compilation instead?

Comment (bend-n) [reply library/core/src/slice/mod.rs:1623]: take it up with https://github.com/rust-lang/rust/issues/74985#issuecomment-2751861090
see also https://github.com/rust-lang/rust/issues/74985#issuecomment-2087722186 https://github.com/rust-lang/rust/issues/75027#issuecomment-3352814555

**Comment by scottmcm** [comment]
Thanks! 
@bors r+

---

Aside: while I wouldn't want more thing in the stabilization PR, I do wonder if this should also be `TrustedLen` and such.  Those can always be done later, though.
