### PR TITLE
vis note for no pub reexports glob import

### LINKED ISSUE #115966: False positive `#[warn(unused_imports)]` warning while glob importing macros defined in nested modules
I tried this code:

```rust
mod a {
    mod b {
        macro_rules! macro_b {
            () => {
                "Hello, world!"
            };
        }
        pub(crate) use macro_b;
    }
    pub use self::b::*;
}

fn main() {
    println!("{}", a::macro_b!());
}
```

I expected to see this happen: *No warning generated*

Instead, this happened: *`cargo check` generated such warning*

```
warning: glob import doesn't reexport anything because no candidate is public enough
  --> src/main.rs:10:13
   |
10 |     pub use self::b::*;
   |             ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

Though the warning says that glob import doesn't reexport anything, commenting out this line leads to error:
```
error[E0433]: failed to resolve: could not find `macro_b` in `a`
  --> src/main.rs:14:23
   |
14 |     println!("{}", a::macro_b!());
   |                       ^^^^^^^ could not find `macro_b` in `a`

warning: unused macro definition: `macro_b`
 --> src/main.rs:3:22
  |
3 |         macro_rules! macro_b {
  |                      ^^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default

warning: unused import: `macro_b`
 --> src/main.rs:8:24
  |
8 |         pub(crate) use macro_b;
  |                        ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
```

The warning will not be generated when any other pub functions are added into module b and exported. It happens when the module only exports macros.

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (65ea825f4 2023-09-18)
binary: rustc
commit-hash: 65ea825f4021eaf77f1b25139969712d65b435a4
commit-date: 2023-09-18
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #115966

Only trigger the ﻿`unused_import` lint when it's not being used.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/imports.rs [hunk 1]
```diff
@@ -992,7 +992,7 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                     && let Some(max_vis) = max_vis.get()
                     && !max_vis.is_at_least(import.expect_vis(), self.tcx)
                 {
-                    self.lint_buffer.buffer_lint(UNUSED_IMPORTS, id, import.span, fluent::resolve_glob_import_doesnt_reexport);
+                    self.no_reexports_imports.push(import);
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/imports.rs:995]: I delayed this process because the record of `a::﻿C` being used occurs at a 'late' stage.

**Comment by petrochenkov** [comment]
Minimized reproduction:
```rust
mod m {
    pub(crate) type A = u8;
}

pub use m::*; // warning: glob import doesn't reexport anything because no candidate is public enough

fn main() {
    let _: A;
}
```
This warning uses a wrong model of glob import's behavior.
It assumes that everything smaller than the glob's nominal visibility (`pub`) is filtered away, while it's not actually filtered, just lowered in visibility.

**Comment by petrochenkov** [comment]
>This warning uses a wrong model of glob import's behavior.
>It assumes that everything smaller than the glob's nominal visibility (pub) is filtered away, while it's not actually filtered, just lowered in visibility.

Sigh, turns out this *was* the right model of glob import's behavior, and for globs we produced the same error as for single imports in the same case.
But then it was changed into a lint in https://github.com/rust-lang/rust/pull/65539, I need to re-read that thread.

**Comment by petrochenkov** [comment]
On closer look, the lint currently works as expected, the change in this PR is not correct.

The only problem is that it is not really an unused imports lint.
The lint message can be extended to better reflect what this lint wants to say:
```
glob import doesn't reexport anything because no candidate is public enough
```
=>
```
glob import doesn't reexport anything with visibility `pub` because no imported item is public enough
NOTE: the most public import item is `pub(crate)`
SUGGESTION: reduce the glob import's visibility or increase visibility of imported items
```

Let me check if there's any more appropriate category for lint than `UNUSED_IMPORTS`.

**Comment by petrochenkov** [comment]
Yeah, besides introducing a new lint name, which I'm hesitant to do, the only plausible candidates are `UNUSED_IMPORTS` and maybe `HIDDEN_GLOB_REEXPORTS` and `UNREACHABLE_PUB`.

Let's keep it `UNREACHABLE_PUB` for now and just improve the message wording and suggestions.
@rustbot author

**Comment by bvanjoi** [comment]
> NOTE: the most public imported item is `pub(crate)`

We cannot obtain concrete information (such as `pub(crate)` or `pub(super)`) from ﻿`ty::Visibility::Restricted`, which implies that we need to store ﻿`ast::Visibility` into ﻿`vis` during the resolution process.

**Comment by petrochenkov** [comment]
Printing whatever is available from `﻿ty::Visibility` would be enogh.

**Comment by bvanjoi** [comment]
I have postponed this lint report until the privacy check in order to print the maximum visibility information.

File: tests/ui/imports/no-reexports-but-used.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// run-pass
```
Comment (bvanjoi) [inline tests/ui/imports/no-reexports-but-used.rs:1]: It's a bit confusing that only `﻿run-pass` triggers a warning message, while `﻿build-pass` and `﻿check-pass` do not.  It appears that the lint level is set to ﻿`allow` under ﻿`build-`pass or `﻿check-pass`.

And the changes observed in other test cases are due to this reason.

I'm not sure if this is the expected behavior, so I'm leaving this comment.

Comment (bvanjoi) [reply tests/ui/imports/no-reexports-but-used.rs:1]: I discovered the issue was due to the usage of [AllowUnused::Yes](https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/runtest.rs#L1899). As a resolution, I've incorporated the `﻿#[warn(unused_imports)]` attribute.

**Comment by bvanjoi** [comment]
ci is green. @rustbot ready

**Comment by petrochenkov** [comment]
I was trying to figure out why `vis_to_string` cannot work early in resolver, and as a result spent too much time making `def_kind` work there - https://github.com/rust-lang/rust/pull/118188.
I think I'm going to finish that work and this PR is not too urgent, so I'm going to block it for now (although, `vis_to_string` could be reimplemented in resolver by using something like `get_nearest_non_block_module`/`nearest_parent_mod` instead of `parent_module_from_def_id`).
@rustbot blocked

**Comment by petrochenkov** [comment]
@bvanjoi 
You could potentially also help with https://github.com/rust-lang/rust/pull/118188 by merging `DefKind::Coroutine` into `DefKind::Closure`, I won't have time for that until at least next week.

**Comment by bvanjoi** [comment]
> merging DefKind::Coroutine into DefKind::Closure

I will handle this tomorrow

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/118188 has landed, so `vis_to_string` should be usable in rustc_resolve now.
@rustbot author

**Comment by bvanjoi** [comment]
ci is green.

@rustbot ready

File: compiler/rustc_middle/src/ty/mod.rs [hunk 3]
```diff
@@ -296,6 +296,23 @@ pub enum Visibility<Id = LocalDefId> {
     Restricted(Id),
 }
 
+impl Visibility {
+    pub fn to_string<'tcx>(self, def_id: LocalDefId, tcx: TyCtxt<'tcx>) -> String {
```
Comment (petrochenkov) [inline compiler/rustc_middle/src/ty/mod.rs:300]:
```suggestion
    pub fn to_string(self, def_id: LocalDefId, tcx: TyCtxt<'_>) -> String {
```

File: tests/ui/privacy/private-variant-reexport.stderr [hunk 4]
```diff
@@ -36,6 +36,11 @@ error: glob import doesn't reexport anything because no candidate is public enou
 LL |     pub use ::E::*;
    |             ^^^^^^
    |
+note: the most public imported item is `pub(crate)`
```
Comment (petrochenkov) [inline tests/ui/privacy/private-variant-reexport.stderr:39]: Could you also update the main message and add a suggestion, as described in https://github.com/rust-lang/rust/pull/115993#issuecomment-1751723421?

File: compiler/rustc_privacy/src/lib.rs [hunk 5]
```diff
@@ -1589,8 +1574,8 @@ impl<'tcx> PrivateItemsInPublicInterfacesChecker<'tcx, '_> {
                     span,
                     kind: self.tcx.def_descr(def_id.to_def_id()),
                     descr: (&LazyDefPathStr { def_id: def_id.to_def_id(), tcx: self.tcx }).into(),
-                    reachable_vis: &vis_to_string(def_id, *reachable_at_vis, self.tcx),
-                    reexported_vis: &vis_to_string(def_id, *reexported_at_vis, self.tcx),
+                    reachable_vis: &*reachable_at_vis.to_string(def_id, self.tcx),
+                    reexported_vis: &*reexported_at_vis.to_string(def_id, self.tcx),
```
Comment (petrochenkov) [inline compiler/rustc_privacy/src/lib.rs:1578]:
```suggestion
                    reexported_vis: &reexported_at_vis.to_string(def_id, self.tcx),
```

File: compiler/rustc_lint_defs/src/lib.rs [hunk 6]
```diff
@@ -583,6 +583,10 @@ pub enum BuiltinLintDiagnostics {
         elided: bool,
         span: Span,
     },
+    InsufficientVisibility {
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/lib.rs:586]:
```suggestion
    RedundantImportVisibility {
```

File: compiler/rustc_resolve/src/imports.rs [hunk 7]
```diff
@@ -248,6 +248,19 @@ struct UnresolvedImportError {
     candidates: Option<Vec<ImportSuggestion>>,
 }
 
+struct RedundantImportVisibilityMsg {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:251]: I'm not sure why this structure is necessary.
Why cannot the message string be inlined at the use site?
The structure is not used by the internationalization system (`.ftl` stuff) either.
