### PR TITLE
MIR borrowck doesn't accept the example of iterating and updating a mutable reference

### LINKED ISSUE #46589: MIR borrowck doesn't accept the example of iterating and updating a mutable reference
I expected this example from the NLL RFC to pass the MIR borrow checker:

```rust
struct List<T> {
    value: T,
    next: Option<Box<List<T>>>,
}

fn to_refs<T>(mut list: &mut List<T>) -> Vec<&mut T> {
    let mut result = vec![];
    loop {
        result.push(&mut list.value);
        if let Some(n) = list.next.as_mut() {
            list = n;
        } else {
            return result;
        }
    }
}

fn main() {
}
```

The idea here is that assigning to `list` is supposed to clear the existing borrows of `list.{value,next}`. However, it still gets errors for me:

```
lunch-box. rustc --stage1 iterate-mut-ref.rs  -Zborrowck=mir
error[E0499]: cannot borrow `list.value` as mutable more than once at a time
  --> iterate-mut-ref.rs:9:21
   |
9  |         result.push(&mut list.value);
   |                     ^^^^^^^^^^^^^^^ mutable borrow starts here in previous iteration of loop
...
16 | }
   | - mutable borrow ends here

error[E0499]: cannot borrow `list.next` as mutable more than once at a time
  --> iterate-mut-ref.rs:10:26
   |
10 |         if let Some(n) = list.next.as_mut() {
   |                          ^^^^^^^^^ mutable borrow starts here in previous iteration of loop
...
16 | }
   | - mutable borrow ends here

error[E0506]: cannot assign to `list` because it is borrowed
  --> iterate-mut-ref.rs:11:13
   |
9  |         result.push(&mut list.value);
   |                     --------------- borrow of `list` occurs here
10 |         if let Some(n) = list.next.as_mut() {
11 |             list = n;
   |             ^^^^^^^^ assignment to borrowed `list` occurs here

error: aborting due to 3 previous errors
```

cc @pnkfelix @arielb1

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #46589.

r? @pnkfelix or @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
Going to revisit the approach taken on this, fairly sure it isn't correct.

**Comment by davidtwco** [comment]
This PR now takes a more reasonable approach, I expect it'll require some changes but it should be good to review now.

File: src/librustc_mir/borrow_check/places_conflict.rs [hunk 1]
```diff
@@ -17,17 +17,45 @@ use rustc::mir::{Projection, ProjectionElem};
 use rustc::ty::{self, TyCtxt};
 use std::cmp::max;
 
+#[derive(Copy, Clone, Debug, Eq, PartialEq)]
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/places_conflict.rs]: Documentation request: what does it mean to "bias" a place conflict? Unfortunately I don't find any answer to this question in the variant names. I'll see if I can infer something from reading the code, but a follow-up commit with docs on this enum might be useful.

Comment (davidtwco) [reply src/librustc_mir/borrow_check/places_conflict.rs]: Added a comment for this.

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 2]
```diff
@@ -231,21 +268,17 @@ impl<'a, 'gcx, 'tcx> BitDenotation for Borrows<'a, 'gcx, 'tcx> {
...
         match stmt.kind {
             mir::StatementKind::Assign(ref lhs, ref rhs) => {
                 // Make sure there are no remaining borrows for variables
                 // that are assigned over.
-                if let Place::Local(ref local) = *lhs {
-                    // FIXME: Handle the case in which we're assigning over
-                    // a projection (`foo.bar`).
-                    self.kill_borrows_on_local(sets, local);
-                }
+                self.kill_borrows_on_place(sets, location, lhs);
```
Comment (pnkfelix) [inline src/librustc_mir/dataflow/impls/borrows.rs]: There is a NOTE  in a comment below this line, and I always wonder whether the directive in this comment has been (or is being) followed... 

The local `assigned_place` has presumably been alpha-renamed, probably to `lhs` here)... but in any case, do we need to make modifications to `propagate_call_return`  to make the logic here match up with the logic there? Are the comments still relevant in the first place?

File: src/librustc_mir/borrow_check/places_conflict.rs [hunk 3]
```diff
@@ -17,17 +17,50 @@ use rustc::mir::{Projection, ProjectionElem};
 use rustc::ty::{self, TyCtxt};
 use std::cmp::max;
 
+/// When checking if a place conflicts with another place, this enum is used to influence decisions
+/// where a place might be equal or disjoint with another place, such as if `a[i] == a[j]`.
+/// `PlaceConflictBias::Overlap` would bias toward assuming that `i == j` and that these places
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/places_conflict.rs]: small nit: Would it not be more precise to say "`Overlap` would bias towards assuming that `i` *might* equal `j`, and thus that these place could overlap. `NoOverlap` assumes that `i != j` and that this places must be disjoint."

The key change being adding the word "might" up above. I don't know if it would ever be relevant, but its good when reading the code to understand that e.g. you should not provide diagnostics that assume nor assert that `i` and `j` *are* equal.

Comment (pnkfelix) [reply src/librustc_mir/borrow_check/places_conflict.rs]: On second thought, I'm not sure I'm right in claiming that `NoOverlap` is stating that the compared indices *must* be disjoint; rather, it is saying something like: "for the purposes of the predicate being run in the calling context, the conservative choice is to assume the compared indices are disjoint."

Right...? Anyway I'll have more comment on this on a use of `NoOverlap` below.

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 4]
```diff
@@ -191,12 +191,49 @@ impl<'a, 'gcx, 'tcx> Borrows<'a, 'gcx, 'tcx> {
...
+            debug!(
+                "kill_borrows_on_place: borrow_index={:?} borrow_data={:?}",
+                borrow_index, borrow_data,
+            );
+            if places_conflict::places_conflict(
+                self.tcx,
+                self.mir,
+                place,
+                &borrow_data.borrowed_place,
+                places_conflict::PlaceConflictBias::NoOverlap,
```
Comment (pnkfelix) [inline src/librustc_mir/dataflow/impls/borrows.rs]: I am still working through the overall logic here, bear with me. I think there is an underlying double-negative here that makes it all make sense, but it might warrant a comment or two.

Kill borrows on place itself does not take a `bias` argument. It just always passes `NoOverlap`, which I earlier thought was stating that any pair of indices being compared are not equal (but now am rethinking that interpretation, given how it is used here).

Of course we cannot know that the pair of indices being compared are not equal, because this function does not have enough context to determine that.

What we (maybe) can say is that when doing the recursion, the conservative option (as in the sound choice) is to assume they are unequal.

So maybe I'd add a note here, above this use of `NoOverlap`, saying something like "we conservatively assume any given pair of array indices are unequal, so that when `places_conflict` returns true, we will be assured that the two places being compared each definitely denote the same sets of locations."

Comment (pnkfelix) [reply src/librustc_mir/dataflow/impls/borrows.rs]: And now that I've written all that, I think I better understand why you chose the word "bias." The bias here reflects "how should I interpret the unknowable (when comparing runtime array indices)", and the answer is always derived from "what would my caller want me to do in order to make the conservative choice to ensure soundness."

File: src/librustc_mir/dataflow/impls/borrows.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_mir/dataflow/impls/borrows.rs]: Okay, after thinking the matter through, I think the PR as it stands is sound; it is just more conservative than it could be, because I *think* we could apply the same place-overwritten borrow-killing logic to `propagate_call_return`, since that represents an overwrite of the `dest_place` that is passed to that method.

It would be best to first come up with a separate example illustrating this, rather than blindly adding the code to the PR.
