### PR TITLE
MIR-borrowck: emit "`foo` does not live long enough" instead of borrow errors 

### LINKED ISSUE #45360: MIR-borrowck: emit "`foo` does not live long enough" instead of borrow errors
e.g. in the test `issue-36082.rs`:
https://github.com/rust-lang/rust/blob/f6d7514545cbe83e771a400d04049b96dfb210cd/src/test/compile-fail/issue-36082.rs#L1-L25

MIR borrowck currently emits the following errors:
```
$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc ../src/test/compile-fail/issue-36082.rs -Z borrowck-mir
error[E0597]: borrowed value does not live long enough (Ast)
  --> ../src/test/compile-fail/issue-36082.rs:18:31
   |
18 |     let val: &_ = x.borrow().0;
   |                   ----------  ^ temporary value dropped here while still borrowed
   |                   |
   |                   temporary value created here
...
24 | }
   | - temporary value needs to live until here
   |
   = note: consider using a `let` binding to increase its lifetime

error[E0505]: cannot move out of `_` because it is borrowed (Mir)
  --> ../src/test/compile-fail/issue-36082.rs:18:32
   |
18 |     let val: &_ = x.borrow().0;
   |                   ----------   ^ move out of `_` occurs here
   |                   |
   |                   borrow of `_` occurs here

error[E0505]: cannot move out of `_` because it is borrowed (Mir)
  --> ../src/test/compile-fail/issue-36082.rs:18:32
   |
18 |     let val: &_ = x.borrow().0;
   |                   ----------   ^ move out of `_` occurs here
   |                   |
   |                   borrow of `_` occurs here

error[E0506]: cannot assign to `_` because it is borrowed (Mir)
  --> ../src/test/compile-fail/issue-36082.rs:18:32
   |
18 |     let val: &_ = x.borrow().0;
   |                   ----------   ^ assignment to borrowed `_` occurs here
   |                   |
   |                   borrow of `_` occurs here

```

The MIR borrowck errors are correctly detected when the MIR storagedead and drop conflict with the pre-existing borrow.

That is the exact definition of a "does not live long enough" error, so we need to detect this case and instead of showing multiple borrow errors, show a single "does not live long enough" error.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #45360. As of writing, contains deduplication of existing errors.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@davidtwco Awesome!

I didn't get a chance to look closely, but I wanted to point you at this gist:

https://gist.github.com/nikomatsakis/a0d5dee0bd3c4d4f0442914a9abdf74c

It describes how to update the existing AST borrow check tests so that we can simultaneously test: (a) the current behavior on stable and (b) the behavior with MIR-borrowck enabled and compare the two. It'd be helpful if you update a test or two to show how the current PR behaves.

**Comment by davidtwco** [comment]
@nikomatsakis That's great. I tested it locally running the same demonstration test from the issue - I'll update some tests tomorrow based on that gist.

**Comment by davidtwco** [comment]
@nikomatsakis I updated the test given as an example in the issue to reflect the expected result once this PR is fully implemented. For now it demonstrates the deduplication. [This is the updated test.](https://github.com/davidtwco/rust/blob/e1462f26e1e0bb8bdbc80ebce85bd9b741ca4b91/src/test/compile-fail/issue-36082.rs#L21-L26)

I'd be happy to update any other tests that this PR would fix.

File: src/test/compile-fail/issue-36082.rs [hunk 1]
```diff
@@ -8,18 +8,23 @@
...
 fn main() {
     let mut r = 0;
     let s = 0;
     let x = RefCell::new((&mut r,s));
 
-    let val: &_ = x.borrow().0;
-    //~^ ERROR borrowed value does not live long enough
+    let val: &_ = x.borrow().0; //[ast]~ ERROR borrowed value does not live long enough [E0597]
+    //[mir]~^ ERROR borrowed value does not live long enough (Ast) [E0597]
+    //[mir]~^ ERROR borrowed value does not live long enough (Mir) [E0597]
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-36082.rs]: This needs to be `//[mir]~|`, I believe.

File: src/test/compile-fail/issue-36082.rs [hunk 2]
```diff
@@ -8,18 +8,23 @@
...
     //~| temporary value dropped here while still borrowed
     //~| temporary value created here
     //~| consider using a `let` binding to increase its lifetime
     println!("{}", val);
 }
-//~^ temporary value needs to live until here
+//[ast]~^ temporary value needs to live until here
+//[mir]~^ temporary value needs to live until here
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-36082.rs]: Same here.

File: src/librustc_mir/borrow_check.rs [hunk 3]
```diff
@@ -599,12 +607,24 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
-            // copy of lvalue: check if this is "copy of frozen path" (FIXME: see check_loans.rs)
-            self.access_lvalue(context, lvalue_span, (Deep, Read(ReadKind::Copy)), flow_state);
+
+        // Check if error has already been reported to stop duplicate reporting.
+        let has_storage_drop_or_dead_error_reported = match *lvalue {
+            Lvalue::Local(local) => self.storage_drop_or_dead_error_reported.insert(local),
+            _ => false,
+        };
+
+        if !has_storage_drop_or_dead_error_reported {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: So @arielb1 pointed out that there is a risk here. The calls to `access_lvalue` are not guaranteed to report an error -- and, in fact, DROP will report errors in a broader set of conditions than `StorageDead` (I think strictly broader). So it would be better to populate the map (and hence skip the latter check) only if an error was actually reported.

What @arielb1 suggested was issuing precisely the same error message in both cases, and letting rustc deduplicate (which it will do). That's an option, though I don't think it's the best path, since I think that the error messages should perhaps be different between the two cases.

Alternatively, we could make `access_lvalue` return a boolean or something, indicating whether an error was reported, and then do:

```
let has_storage_drop_or_dead_error_reported = self.storage_drop_or_dead_error_reported.contains_key(...);

let error_reported;
if has_storage_drop_or_dead_error_reported { error_reported = false; } else {
    if moves_by_default { error_reported = self.access_lvalue(..); } else { ... }
}
if error_reported { self.storage_drop_or_dead_error_reported.insert(local); }
```

It would also be good to comment about this. =)

It's hard to come up with a test case that would necesarily show off this problem though -- specifically, `Drop` will always come before `StorageDead`, and hence I imagine we'll visit it first, so the bug won't show itself. But I wouldn't want to rely on that.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/compile-fail/issue-36082.rs (hunk 2 above)
Comment (davidtwco) [reply src/test/compile-fail/issue-36082.rs]: Resolved this, my bad.

File: src/test/compile-fail/issue-36082.rs (hunk 1 above)
Comment (davidtwco) [reply src/test/compile-fail/issue-36082.rs]: Resolved this, my bad.

File: src/librustc_mir/borrow_check.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check.rs]: I've modified what was there based on this, should be fine now.

File: src/librustc_mir/borrow_check.rs [hunk 4]
```diff
@@ -444,13 +455,14 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
                      kind: (ShallowOrDeep, ReadOrWrite),
-                     flow_state: &InProgress<'b, 'gcx, 'tcx>) {
+                     flow_state: &InProgress<'b, 'gcx, 'tcx>) -> bool {
 
         let (sd, rw) = kind;
 
         // Check permissions
         self.check_access_permissions(lvalue_span, rw);
 
+        let mut has_storage_drop_or_dead_error_reported = false;
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Nit: we should probably just call this `error_reported`

File: src/librustc_mir/borrow_check.rs [hunk 5]
```diff
@@ -444,13 +455,14 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
                      context: Context,
                      lvalue_span: (&Lvalue<'tcx>, Span),
                      kind: (ShallowOrDeep, ReadOrWrite),
-                     flow_state: &InProgress<'b, 'gcx, 'tcx>) {
+                     flow_state: &InProgress<'b, 'gcx, 'tcx>) -> bool {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Can you add a comment to the function indicating what the return value means?

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: I see there is no existing comment, either! How about something like this:

Checks an access to the given lvalue to see if it is allowed. Examines the set of borrows that are in scope, as well as which paths have been initialized, to ensure that (a) the lvalue is initialized and (b) it is not borrowed in some way that would prevent this access.

Returns true if an error is reported, false otherwise.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks great! Left a few nits.

File: src/librustc_mir/borrow_check.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check.rs]: Resolved this, thanks.

File: src/librustc_mir/borrow_check.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check.rs]: Resolved this, thanks.

**Comment by nikomatsakis** [comment]
So, in terms of how to change the error message. The current error message arises from this call here:

https://github.com/davidtwco/rust/blob/d906a6e94dfaac3a1344db96237d59bb9285bf5b/src/librustc_mir/borrow_check.rs#L637-L638

Note that we pass `Write(WriteKind::Move)`. That seems bogus. Per @arielb1's suggestion, we should rename `WriteKind::StorageDead` to `WriteKind::StorageDeadOrDrop` and pass that here, I think.  (Note that we sometimes want `Move`, we'll have to look at the `consume_via_drop` argument to decide.)

That will then flow down to this case:

https://github.com/davidtwco/rust/blob/d906a6e94dfaac3a1344db96237d59bb9285bf5b/src/librustc_mir/borrow_check.rs#L492-L514

You can see that `WriteKind::StorageDead` (which we will have renamed) is treated the same as `Mutate`. We want to give it its own case. Then we want to invoke this helper function:

https://github.com/davidtwco/rust/blob/d906a6e94dfaac3a1344db96237d59bb9285bf5b/src/librustc_mir/util/borrowck_errors.rs#L375-L384

The other cases invoke similar helpers, but they use [shallow wrappers like `report_move_out_while_borrowed`](https://github.com/davidtwco/rust/blob/d906a6e94dfaac3a1344db96237d59bb9285bf5b/src/librustc_mir/borrow_check.rs#L1336-L1349) so we probably want to write one of those too.

**Comment by davidtwco** [comment]
Rebased and producing the correct error message now.

**Comment by davidtwco** [comment]
Rebased on top of the conflicting changes and to squash my own commits. Error message now looks more or less what we're seeing with the `Ast` version, only difference is the symbols used and I can't see a way around that. Other than that, I *think* this is done.

@bors r=nikomatsakis

**Review by nikomatsakis — APPROVED** [review]

**Comment by davidtwco** [comment]
Pushed a commit that fixes the error on the Travis build in an unrelated test. Should be good now, apologies.
