### PR TITLE
Suggest Replacing Comma with Semicolon in Incorrect Repeat Expressions

### LINKED ISSUE #80173: Detect `;` -> `,` typo on `vec!["_", 10]`
_Only_ when writing `vec!["_", 10]` we could suggest replacing the `,` with `;`.

### PR DESCRIPTION
**Pull request by veera-sivarajan**
Fixes #80173 

This PR detects typos in repeat expressions like `["_", 10]` and `vec![String::new(), 10]` and suggests replacing comma with semicolon.

Also, improves code in other place by adding doc comments and making use of a helper function to check if a type implements `Clone`.

References:
1. For `vec![T; N]`: https://doc.rust-lang.org/std/macro.vec.html
2. For `[T; N]`: https://doc.rust-lang.org/std/primitive.array.html

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? compiler

**Comment by veera-sivarajan** [comment]
@fmease friendly bump

**Comment by veera-sivarajan** [comment]
r? compiler

**Review by fmease — CHANGES_REQUESTED** [review]
Ah, let me post what I had pending

File: compiler/rustc_trait_selection/src/infer.rs [hunk 1]
```diff
@@ -42,6 +43,14 @@ impl<'tcx> InferCtxt<'tcx> {
...
     }
 
+    /// Check if `ty` implements the `Clone` trait.
+    fn type_is_clone_modulo_regions(&self, param_env: ty::ParamEnv<'tcx>, ty: Ty<'tcx>) -> bool {
+        let ty = self.resolve_vars_if_possible(ty);
+        let clone_def_id = self.tcx.require_lang_item(LangItem::Clone, None);
+        traits::type_known_to_meet_bound_modulo_regions(self, param_env, ty, clone_def_id)
+    }
+
+    /// Check if `ty` implements the `Sized` trait.
```
[the remark this answers is not in the document]
Comment (veera-sivarajan) [reply compiler/rustc_trait_selection/src/infer.rs:54]: Thanks for the feedback!

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -2183,6 +2176,79 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    _ => false,
+                };
+
+            // `array_expr` is from a macro `vec!["a", 10]` if
+            // 1. array expression's span is imported from a macro
+            // 2. first element of array implements `Clone` trait
+            // 3. second element is an integer literal or is an expression of `usize` like type
+            if self.tcx.sess.source_map().is_imported(array_expr.span)
+                && self.type_is_clone_modulo_regions(self.param_env, self.check_expr(first))
+                && (second.is_size_lit() || expr_ty.is_usize_like())
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2229]: Please only use `expr` or `second`, not a mix of both.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -2183,6 +2176,79 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    ) => self.tcx.is_const_fn(*fn_def_id),
+                    _ => false,
+                };
+
+            // `array_expr` is from a macro `vec!["a", 10]` if
+            // 1. array expression's span is imported from a macro
+            // 2. first element of array implements `Clone` trait
+            // 3. second element is an integer literal or is an expression of `usize` like type
+            if self.tcx.sess.source_map().is_imported(array_expr.span)
+                && self.type_is_clone_modulo_regions(self.param_env, self.check_expr(first))
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2228]: If we get here, hasn't `first` already be checked? Could we fetch its type from the results, instead of trying to re-check it?

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 4]
```diff
@@ -2183,6 +2176,79 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                && (second.is_size_lit() || expr_ty.is_usize_like())
+            {
+                err.subdiagnostic(errors::ReplaceCommaWithSemicolon {
+                    comma_span,
+                    descr: "a vector",
+                });
+                return true;
+            } else if self.type_is_copy_modulo_regions(self.param_env, self.check_expr(first))
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2236]: As you return, you can remove the `else` and have both blocks have their comment before the `if`.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 3 above)
Comment (veera-sivarajan) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Yes.

Thank you for the detailed feedback.

**Comment by cjgillot** [comment]
Thanks for your patience.
@bors r+ rollup
