### PR TITLE
Do not return incorrectly constrained opaques in `method_autoderef_steps`

### LINKED ISSUE #263: `method_autoderef_steps` returns all opaques, resulting in ICE if they are incorrectly constrained
```rust
use std::ops::Deref;
trait Trait {}
struct Inv<T>(*mut T);
impl Trait for i32 {}
impl Deref for Inv<u32> {
    type Target = u32;
    fn deref(&self) -> &Self::Target {
        todo!()
    }
}

fn mk<T>() -> T { todo!() }
fn foo() -> Inv<impl Trait> {
    let mut x: Inv<_> = mk();
    if false {
        return x;
    }

    x.count_ones();
    x
}
```
this one ICEs with
```
thread 'rustc' (3) panicked at /rustc-dev/5c49c4f7c8393c861b849441d27f5d40e0f1e33b/compiler/rustc_hir_typeck/src/method/probe.rs:1919:21:
internal error: entered unreachable code: unexpected autoderef error [FulfillmentError { obligation: Obligation(predicate=Binder { value: TraitPredicate(<u32 as Trait>, polarity:Positive), bound_vars: [] }, depth=2), code: Unimplemented, root_obligation: Obligation(predicate=Binder { value: AliasRelate(Term::Ty(Alias(Opaque, AliasTy { args: [], def_id: DefId(0:16 ~ example[c792]::foo::{opaque#0}), .. })), Equate, Term::Ty(u32)), bound_vars: [] }, depth=0) }]
```
the issue is in https://github.com/rust-lang/rust/blob/9283d592deb2887311b9fa95027fd78c2172e554/compiler/rustc_infer/src/infer/canonical/query_response.rs#L96-L101

This should only return the opaque types added in the current query. We should provide the length of the opaque type storage at the start of the query as an input to this function, and then only canonicalize new ones. This can be done using `fn opaque_types_added_since`

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/263

r? @lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/opaques/method_autoderef_constraints.rs [hunk 1]
```diff
@@ -0,0 +1,33 @@
+//@ compile-flags: -Znext-solver
+
+// Regression test for trait-system-refactor-initiative/issues/263
+// Previously we return all opaques in `method_auto_deref_steps` which normalizes the opaque
+// to `u32`, causing obligations to fail.
+// We shouldn't return incorrectly constrained opaques in this query.
```
Comment (lcnr) [inline tests/ui/traits/next-solver/opaques/method_autoderef_constraints.rs]:
```suggestion
// Previously `method_auto_deref_steps` would also return opaque
// types which have already been defined in the parent context.
//
// We then handled these opaque types by emitting `AliasRelate` goals
// when instantiating its result, assuming that operation to be infallible.
// By returning opaque type constraints from the parent context and
// constraining the hidden type without reproving the item bounds of
// the opaque, this ended up causing ICE.
```

**Review by lcnr — COMMENTED** [review]
r=me after comment nit

thanks ❤️
