### PR TITLE
Fix BTreeMap UB

### LINKED ISSUE #54957: BTreeSet causes UB my having (partially) dangling shared ref
The following code causes UB (found by a patched miri enforcing validity invariants):
```rust
    let mut b = std::collections::BTreeSet::new();
    b.insert(42);
```
What happens is that `BTreeSet::new` [sets the root node](https://github.com/rust-lang/rust/blob/4623d4889373702428251967d9bf6ff6d677ec1a/src/liballoc/collections/btree/map.rs#L535) to [a pointer to](https://github.com/rust-lang/rust/blob/4623d4889373702428251967d9bf6ff6d677ec1a/src/liballoc/collections/btree/node.rs#L197) a [static `EMPTY_ROOT_NODE` shared for this purpose by all B-trees](https://github.com/rust-lang/rust/blob/4623d4889373702428251967d9bf6ff6d677ec1a/src/liballoc/collections/btree/node.rs#L116) that has type `LeafNode<(), ()>`. That step is okay.

However, in the next step, `insert` calls [`ensure_root_is_owned`](https://github.com/rust-lang/rust/blob/4623d4889373702428251967d9bf6ff6d677ec1a/src/liballoc/collections/btree/map.rs#L1174) which indirectly [turns this ptr](https://github.com/rust-lang/rust/blob/4623d4889373702428251967d9bf6ff6d677ec1a/src/liballoc/collections/btree/node.rs#L388) into `&LeafNode<i32, ()>`. The trouble is that `LeafNode<i32, ()>` is bigger than `LeafNode<(), ()>`, so this reference is partially dangling: Its beginning points to allocated memory (the static `EMPTY_ROOT_NODE`), but that allocated memory ends "too early". The invariant that `&LeafNode<i32, ()>` be dereferencable *for `mem::size_of::<LeafNode<i32, ()>>()` bytes* is violated. Since we are passing `dereferencable(n)` to LLVM [with `n` set to the full size of the struct](https://play.rust-lang.org/?gist=8c9fecbcecd4896eaa7d2a97686714da&version=nightly&mode=debug&edition=2015), this means we have UB not just according to our own validity rules, but according to LLVM's rules.

### PR DESCRIPTION
**Pull request by RalfJung**
BTreeMap currently causes UB by created a shared reference to a too-small allocation.  This PR fixes that by introducing a `NodeHeader` type and using that until we really need access to the key/value arrays.  Avoiding run-time checks in `into_key_slice` was somewhat tricky, see the comments embedded in the code.

I also adjusted `as_leaf_mut` to return a raw pointer, because creating a mutable reference asserts that there are no aliases to the pointee, but that's not always correct: We use `as_leaf_mut` twice to create two mutable slices for keys and values; the second call overlaps with the first slice and hence is not a unique pointer.

Fixes https://github.com/rust-lang/rust/issues/54957

Cc @nikomatsakis @Gankro

### CODE REVIEW

**Comment by sfackler** [comment]
Would it be worth putting NodeHeader fields in the node types directly to avoid accidentally desynchronizing them?

The K2 shenanigans seem unfortunate but I'll defer to your expertise that they're necessary :)

**Comment by RalfJung** [comment]
> Would it be worth putting NodeHeader fields in the node types directly to avoid accidentally desynchronizing them?

Unfortunately that will increase their size, because there'll be padding after `len` inside `NodeHeader`.

**Comment by sfackler** [comment]
Ah right.

File: src/liballoc/collections/btree/node.rs [hunk 1]
```diff
@@ -551,28 +587,50 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
 impl<'a, K: 'a, V: 'a, Type> NodeRef<marker::Immut<'a>, K, V, Type> {
     fn into_key_slice(self) -> &'a [K] {
-        // When taking a pointer to the keys, if our key has a stricter
-        // alignment requirement than the shared root does, then the pointer
-        // would be out of bounds, which LLVM assumes will not happen. If the
-        // alignment is more strict, we need to make an empty slice that doesn't
-        // use an out of bounds pointer.
+        // We have to be careful here because we might be pointing to the shared root.
+        // In that case, we must not create an `&LeafNode`.  We could just return
+        // an empty slice whenever the lenght is 0 (this includes the shared root),
```
Comment (Gankro) [inline src/liballoc/collections/btree/node.rs]:
```suggestion
        // an empty slice whenever the length is 0 (this includes the shared root),
```

**Review by Gankra — APPROVED** [review]
*shrug* I guess

**Comment by RalfJung** [comment]
> shrug I guess

I'm always open for suggestions for better solutions ;)

File: src/liballoc/collections/btree/node.rs [hunk 2]
```diff
@@ -98,24 +123,25 @@ impl<K, V> LeafNode<K, V> {
...
+unsafe impl Sync for NodeHeader<(), ()> {}
 
 // An empty node used as a placeholder for the root node, to avoid allocations.
-// We use () in order to save space, since no operation on an empty tree will
+// We use just a header in order to save space, since no operation on an empty tree will
 // ever take a pointer past the first key.
-static EMPTY_ROOT_NODE: LeafNode<(), ()> = LeafNode {
+static EMPTY_ROOT_NODE: NodeHeader<(), ()> = NodeHeader {
     parent: ptr::null(),
     parent_idx: MaybeUninit::uninitialized(),
```
Comment (bluss) [inline src/liballoc/collections/btree/node.rs]: Uninitialized in a static is surprising, isn't it, it doesn't have much purpose other than if miri can potentially use it in analysis? Can't we easily just initialize this at no cost, since it's in a static?

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: The header is also used at run-time, and this data is not always initialized, so it needs to have type `MaybeUninit`.

I don't sere the point of trying to initialize this to anything else.

Comment (bluss) [reply src/liballoc/collections/btree/node.rs]: The only point would be to code defensively, sort of like the safe practices one learns to use in C. Requires saying that a bug with use of uninit value would be worse than a bug where we access an initialized but bogus value. (So this is where Miri comes in? It could diagnose the former better!?)

This is absolutely not a big deal, but I like to remember that we need to be defensive in Rust and not just have one line of defence.

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: If `MaybeUninit::zeroed()` was `const fn` I'd be happy to r+ a PR that uses that, but currently I don't see a good way to do anything more defensive. Do you have a concrete suggestion?

Comment (bluss) [reply src/liballoc/collections/btree/node.rs]: if Maybeuninit::new(0) would work, that would be it, but that's all. I think it works?

Comment (RalfJung) [reply src/liballoc/collections/btree/node.rs]: Do you want to try if it works?

Comment (bluss) [reply src/liballoc/collections/btree/node.rs]: I have only one project in rust-lang/rust right now, that's #56440, so I can try after that.
