### PR TITLE
Provide more context for `rustc +nightly -Zunstable-options` on stable

### LINKED ISSUE #110090: stable: Give a better error message for `rustc +nightly -Zunstable-options`
### Code

```Rust
$(rustup which rustc --toolchain 1.68) +nightly -Zunstable-options
```

### Current output

```Shell
error: the option `Z` is only accepted on the nightly compiler
```

### Desired output

```Shell
error: the option `Z` is only accepted on the nightly compiler
error: couldn't read +nightly: No such file or directory (os error 2)
|
= note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>
```

### Rationale and extra context

Distros often install rustc directly, without a rustup wrapper. In that case, people using the distro rustc may see suggestions on stack overflow or elsewhere that won't work with their toolchain. We should improve the error message for them.

Originally reported in https://github.com/rust-lang/rust/issues/104785.

### Other cases

_No response_

### Anything else?

Note that to test your change for this issue, you'll have to set `channel = "stable"` in config.toml; nightly reports a different error:
```
; $(rustup which rustc --toolchain nightly) +nightly -Zunstable-options
error: couldn't read +nightly: No such file or directory (os error 2)

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by jieyouxu**
Screenshot 2023-06-16 123456

Closes #110090.

### CODE REVIEW

File: src/tools/miri/src/bin/miri.rs [hunk 1]
```diff
@@ -67,7 +67,8 @@ impl rustc_driver::Callbacks for MiriCompilerCalls {
                 tcx.sess.fatal("miri cannot be run on programs that fail compilation");
             }
 
-            init_late_loggers(tcx);
+            let handler = EarlyErrorHandler::new(ErrorOutputType::default());
```
Comment (RalfJung) [inline src/tools/miri/src/bin/miri.rs:70]: Is it expected that a *second handler* gets created here? That seems odd and doesn't seem to happen with the other tools.

Comment (jieyouxu) [reply src/tools/miri/src/bin/miri.rs:70]: This is not intentional and I think it was just a leftover from me trying to change stuff.

File: src/tools/miri/src/bin/miri.rs [hunk 2]
```diff
@@ -59,15 +59,16 @@ impl rustc_driver::Callbacks for MiriCompilerCalls {
 
     fn after_analysis<'tcx>(
         &mut self,
+        handler: &EarlyErrorHandler,
```
Comment (RalfJung) [inline src/tools/miri/src/bin/miri.rs:62]: Instead of changing the signature of `after_analysis` for everyone, it would be better to just add the handler reference as a field in MiriCompilerCalls.

How does this even build currently? You haven't changed the call sites.

Comment (jieyouxu) [reply src/tools/miri/src/bin/miri.rs:62]: This is a bit awkward if I try to add it as a field to `MiriCompilerCalls` since the inner handle of `handler` isn't `Sync`.

File: compiler/rustc_session/src/session.rs [hunk 3]
```diff
@@ -1723,59 +1723,123 @@ pub enum IncrCompSession {
...
+        self.handler.abort_if_errors()
+    }
+
+    /// Swap out the underlying handler once we acquire the user's preference on error emission
+    /// format. Any errors prior to that will cause an abort and all stashed diagnostics of the
+    /// previous handler will be emitted.
+    pub fn abort_if_error_and_set_error_format(&mut self, output: ErrorOutputType) {
+        self.handler.abort_if_errors();
+
+        let fallback_bundle =
```
Comment (davidtwco) [inline compiler/rustc_session/src/session.rs:1780]: Is this part duplicated with `new`? If it is, could you extract the emitter creation into a function?

**Review by davidtwco — APPROVED** [review]
LGTM, r=me with the nit below

**Comment by Kobzol** [comment]
(probably) this PR has regressed coloring of warnings emitted by rustc, and it no longer prints the warning summary at the end.
`5ea66686467d3ec5f8c81570e7f0f16ad8dd8cc3` (previous master):
```bash
$ rm -rf target && RUSTFLAGS="-Cremark=foo" cargo +5ea66686467d3ec5f8c81570e7f0f16ad8dd8cc3 build --release
```
image

`6b46c996e1d3a07dd73beb2873d74a8a0458d05f` (merge containing this PR):
```bash
$ rm -rf target && RUSTFLAGS="-Cremark=foo" cargo +6b46c996e1d3a07dd73beb2873d74a8a0458d05f build --release
```
image

Both commands were executed on a `cargo new` hello world crate.

**Comment by jieyouxu** [comment]
The fix is trivial... I forgot to `handler.abort_if_error_and_set_error_format(error_format);` *as soon as* we have a usable error format in `build_session_options`. I set it *too late*.

**Comment by jieyouxu** [comment]
> (probably) this PR has regressed coloring of warnings emitted by rustc, and it no longer prints the warning summary at the end. `5ea66686467d3ec5f8c81570e7f0f16ad8dd8cc3` (previous master):

Opened #113127 to fix this.
