### PR TITLE
save-analysis: Nest typeck tables when processing functions/methods

### LINKED ISSUE #43982: Compiler panic compiling libcore
Last rebase was 11. Aug. Using rust-llvm-2017-07-20.

EDIT: First bad commit is 783ccc443b88884a10eed564e0fdc3c1e6f974a4

Compiling with:
```sh
	cd $(rust_src) && \
	./configure --enable-debug \
              --enable-extended \
	      --prefix=$(rust_dest) \
              --sysconfdir=$(rust_dest)/etc \
              --localstatedir=$(rust_dest)/var/lib \
              --datadir=$(rust_dest)/share \
              --infodir=$(rust_dest)/share/info \
              --default-linker=gcc \
              --llvm-root=$(llvm_dest) \
              --enable-llvm-link-shared
	cd $(rust_src) && make
	cd $(rust_src) && make install
```

```sh
error: internal compiler error: src/librustc/ty/context.rs:237: node unknown node (id=1) with HirId::owner DefId { krate: CrateNum(0), node: DefIndex(0) => core/a38a63e } cannot be placed in TypeckTables with local_id_root DefId { krate: CrateNum(0), node: DefIndex(1533) => core/a38a63e::panicking[0]::panic_fmt[0] }

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-dev (41193c16f 2017-08-18) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:486:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:60
   3: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:381
   4: std::panicking::default_hook
             at src/libstd/panicking.rs:391
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:611
   6: std::panicking::begin_panic
             at ./src/libstd/panicking.rs:572
   7: rustc_errors::Handler::bug
             at src/librustc_errors/lib.rs:486
   8: rustc::session::opt_span_bug_fmt::{{closure}}
             at src/librustc/session/mod.rs:852
   9: rustc::ty::context::tls::with_opt::{{closure}}
             at src/librustc/ty/context.rs:1289
  10: rustc::ty::context::tls::with::{{closure}}
             at src/librustc/ty/context.rs:1278
  11: <std::thread::local::LocalKey<T>>::try_with
             at ./src/libstd/thread/local.rs:365
  12: <std::thread::local::LocalKey<T>>::with
             at ./src/libstd/thread/local.rs:279
  13: rustc::ty::context::tls::with
             at src/librustc/ty/context.rs:1274
  14: rustc::ty::context::tls::with_opt
             at src/librustc/ty/context.rs:1289
  15: rustc::session::opt_span_bug_fmt
             at src/librustc/session/mod.rs:848
  16: rustc::session::bug_fmt
             at src/librustc/session/mod.rs:832
  17: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
             at src/librustc/ty/context.rs:237
  18: rustc::ty::context::tls::with::{{closure}}
             at src/librustc/ty/context.rs:1278
  19: <std::thread::local::LocalKey<T>>::try_with
             at ./src/libstd/thread/local.rs:365
  20: <std::thread::local::LocalKey<T>>::with
             at ./src/libstd/thread/local.rs:279
  21: rustc::ty::context::tls::with
             at src/librustc/ty/context.rs:1274
  22: rustc::ty::context::validate_hir_id_for_typeck_tables
             at src/librustc/ty/context.rs:232
  23: rustc::ty::context::TypeckTables::node_id_to_type_opt
             at src/librustc/ty/context.rs:448
  24: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_formals
             at src/librustc_save_analysis/dump_visitor.rs:322
  25: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item::{{closure}}
             at src/librustc_save_analysis/dump_visitor.rs:1518
  26: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_tables
             at src/librustc_save_analysis/dump_visitor.rs:115
  27: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item
             at src/librustc_save_analysis/dump_visitor.rs:1518
  28: syntax::visit::walk_item
             at ./src/libsyntax/visit.rs:146
  29: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at src/librustc_save_analysis/dump_visitor.rs:1254
  30: syntax::visit::walk_stmt
             at ./src/libsyntax/visit.rs:624
  31: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_stmt
             at src/librustc_save_analysis/dump_visitor.rs:1499
  32: syntax::visit::walk_block
             at ./src/libsyntax/visit.rs:146
  33: syntax::visit::Visitor::visit_block
             at ./src/libsyntax/visit.rs:66
  34: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn::{{closure}}::{{closure}}
             at src/librustc_save_analysis/dump_visitor.rs:464
  35: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at src/librustc_save_analysis/dump_visitor.rs:100
  36: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn::{{closure}}
             at src/librustc_save_analysis/dump_visitor.rs:464
  37: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_tables
             at src/librustc_save_analysis/dump_visitor.rs:112
  38: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn
             at src/librustc_save_analysis/dump_visitor.rs:464
  39: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at src/librustc_save_analysis/dump_visitor.rs:1206
  40: syntax::visit::walk_mod
             at ./src/libsyntax/visit.rs:146
  41: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item::{{closure}}
             at src/librustc_save_analysis/dump_visitor.rs:1224
  42: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at src/librustc_save_analysis/dump_visitor.rs:100
  43: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at src/librustc_save_analysis/dump_visitor.rs:1224
  44: syntax::visit::walk_mod
             at ./src/libsyntax/visit.rs:146
  45: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod::{{closure}}
             at src/librustc_save_analysis/dump_visitor.rs:1111
  46: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at src/librustc_save_analysis/dump_visitor.rs:100
  47: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod
             at src/librustc_save_analysis/dump_visitor.rs:1111
  48: syntax::visit::walk_crate
             at ./src/libsyntax/visit.rs:180
  49: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
             at src/librustc_save_analysis/lib.rs:939
  50: rustc_save_analysis::process_crate
             at ./src/librustc_save_analysis/lib.rs:986
  51: rustc_driver::enable_save_analysis::{{closure}}::{{closure}}
             at src/librustc_driver/lib.rs:697
  52: rustc::util::common::time
             at ./src/librustc/util/common.rs:48
  53: rustc_driver::enable_save_analysis::{{closure}}
             at src/librustc_driver/lib.rs:696
  54: rustc_driver::driver::compile_input::{{closure}}
             at src/librustc_driver/driver.rs:217
  55: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
             at src/librustc_driver/driver.rs:1101
  56: rustc::ty::context::tls::enter::{{closure}}
             at ./src/librustc/ty/context.rs:1262
  57: <std::thread::local::LocalKey<T>>::try_with
             at ./src/libstd/thread/local.rs:365
  58: <std::thread::local::LocalKey<T>>::with
             at ./src/libstd/thread/local.rs:279
  59: rustc::ty::context::tls::enter
             at ./src/librustc/ty/context.rs:1259
  60: rustc::ty::context::tls::enter_global::{{closure}}
             at ./src/librustc/ty/context.rs:1246
  61: <std::thread::local::LocalKey<T>>::try_with
             at ./src/libstd/thread/local.rs:365
  62: <std::thread::local::LocalKey<T>>::with
             at ./src/libstd/thread/local.rs:279
  63: rustc::ty::context::tls::enter_global
             at ./src/librustc/ty/context.rs:1243
  64: rustc::ty::context::TyCtxt::create_and_enter
             at ./src/librustc/ty/context.rs:1024
  65: rustc_driver::driver::phase_3_run_analysis_passes
             at src/librustc_driver/driver.rs:1014
  66: rustc_driver::driver::compile_input
             at src/librustc_driver/driver.rs:196
  67: rustc_driver::run_compiler
             at src/librustc_driver/lib.rs:316
  68: rustc_driver::main::{{closure}}
             at src/librustc_driver/lib.rs:1338
  69: rustc_driver::run::{{closure}}
             at src/librustc_driver/lib.rs:132
  70: rustc_driver::monitor::{{closure}}
             at src/librustc_driver/lib.rs:1255

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/home/dvc/repos/riscv-rust/rust/build/bootstrap/debug/rustc --crate-name core src/libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on -C metadata=0f4c6fa20e4370e3 -C extra-filename=-0f4c6fa20e4370e3 --out-dir /home/dvc/repos/riscv-rust/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/home/dvc/repos/riscv-rust/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/dvc/repos/riscv-rust/rust/build/x86_64-unknown-linux-gnu/stage1-std/debug/deps` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/home/dvc/repos/riscv-rust/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "4" "--target" "x86_64-unknown-linux-gnu" "--features" "panic-unwind debug-jemalloc jemalloc backtrace" "--manifest-path" "/home/dvc/repos/riscv-rust/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:869:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: bootstrap::compile::run_cargo
   8: <bootstrap::compile::Std as bootstrap::builder::Step>::run
   9: bootstrap::builder::Builder::ensure
  10: <bootstrap::compile::Test as bootstrap::builder::Step>::run
  11: bootstrap::builder::Builder::ensure
  12: <bootstrap::compile::Rustc as bootstrap::builder::Step>::run
  13: bootstrap::builder::Builder::ensure
  14: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
  15: bootstrap::builder::Builder::ensure
  16: bootstrap::builder::Builder::compiler
  17: <bootstrap::compile::Std as bootstrap::builder::Step>::make_run
  18: bootstrap::builder::StepDescription::maybe_run
  19: bootstrap::builder::StepDescription::run
  20: bootstrap::builder::Builder::run
  21: bootstrap::Build::build
  22: bootstrap::main
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  24: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  25: main
  26: __libc_start_main
  27: _start
failed to run: /home/dvc/repos/riscv-rust/rust/build/bootstrap/debug/bootstrap build
```

### LINKED ISSUE #50328: Does not build with `extended` on
I have `extended = true` set in `config.toml`, but this seems to be causing the build to fail (master HEAD at time of writing), where it wasn't before.

```
$ ./x.py -i build
Updating only changed submodules
Updating submodule src/tools/clippy
Submodule path 'src/tools/clippy': checked out 'c5b39a5917ffc0f1349b6e414fa3b874fdcf8429'
Submodules updated in 1.15 seconds
    Finished dev [unoptimized] target(s) in 0.0 secs
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling core v0.0.0 (file:///Users/alex/Software/rust/src/libcore)
   Compiling unwind v0.0.0 (file:///Users/alex/Software/rust/src/libunwind)
   Compiling build_helper v0.1.0 (file:///Users/alex/Software/rust/src/build_helper)
   Compiling compiler_builtins v0.0.0 (file:///Users/alex/Software/rust/src/rustc/compiler_builtins_shim)
   Compiling rustc_tsan v0.0.0 (file:///Users/alex/Software/rust/src/librustc_tsan)
   Compiling rustc_asan v0.0.0 (file:///Users/alex/Software/rust/src/librustc_asan)
   Compiling alloc_jemalloc v0.0.0 (file:///Users/alex/Software/rust/src/liballoc_jemalloc)
   Compiling std v0.0.0 (file:///Users/alex/Software/rust/src/libstd)
   Compiling libc v0.0.0 (file:///Users/alex/Software/rust/src/rustc/libc_shim)
   Compiling alloc v0.0.0 (file:///Users/alex/Software/rust/src/liballoc)
   Compiling std_unicode v0.0.0 (file:///Users/alex/Software/rust/src/libstd_unicode)
   Compiling alloc_system v0.0.0 (file:///Users/alex/Software/rust/src/liballoc_system)
   Compiling panic_abort v0.0.0 (file:///Users/alex/Software/rust/src/libpanic_abort)
   Compiling panic_unwind v0.0.0 (file:///Users/alex/Software/rust/src/libpanic_unwind)
    Finished release [optimized] target(s) in 50.30 secs
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling getopts v0.2.17
   Compiling term v0.0.0 (file:///Users/alex/Software/rust/src/libterm)
   Compiling test v0.0.0 (file:///Users/alex/Software/rust/src/libtest)
    Finished release [optimized] target(s) in 8.28 secs
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling libc v0.2.40
   Compiling stable_deref_trait v1.0.0
   Compiling smallvec v0.6.0
   Compiling cfg-if v0.1.2
   Compiling bitflags v1.0.1
   Compiling serialize v0.0.0 (file:///Users/alex/Software/rust/src/libserialize)
   Compiling rustc_target v0.0.0 (file:///Users/alex/Software/rust/src/librustc_target)
   Compiling unicode-width v0.1.4
   Compiling scoped-tls v0.1.1
   Compiling termcolor v0.3.6
   Compiling syntax v0.0.0 (file:///Users/alex/Software/rust/src/libsyntax)
   Compiling rustc v0.0.0 (file:///Users/alex/Software/rust/src/librustc)
   Compiling remove_dir_all v0.5.1
   Compiling rustc-demangle v0.1.7
   Compiling byteorder v1.2.2
   Compiling graphviz v0.0.0 (file:///Users/alex/Software/rust/src/libgraphviz)
   Compiling lazy_static v1.0.0
   Compiling rustc-serialize v0.3.24
   Compiling rustc_metadata v0.0.0 (file:///Users/alex/Software/rust/src/librustc_metadata)
   Compiling fmt_macros v0.0.0 (file:///Users/alex/Software/rust/src/libfmt_macros)
   Compiling lazy_static v0.2.11
   Compiling rustc_incremental v0.0.0 (file:///Users/alex/Software/rust/src/librustc_incremental)
   Compiling quick-error v1.2.1
   Compiling rustc_platform_intrinsics v0.0.0 (file:///Users/alex/Software/rust/src/librustc_platform_intrinsics)
   Compiling ar v0.3.1
   Compiling rustc_driver v0.0.0 (file:///Users/alex/Software/rust/src/librustc_driver)
   Compiling log v0.4.1
   Compiling owning_ref v0.3.3
   Compiling rand v0.4.2
   Compiling atty v0.2.8
   Compiling log_settings v0.1.1
   Compiling humantime v1.1.1
   Compiling backtrace v0.3.6
   Compiling miniz-sys v0.1.10
   Compiling ena v0.9.2
   Compiling rustc_cratesio_shim v0.0.0 (file:///Users/alex/Software/rust/src/librustc_cratesio_shim)
   Compiling jobserver v0.1.11
   Compiling env_logger v0.5.8
   Compiling rustc_apfloat v0.0.0 (file:///Users/alex/Software/rust/src/librustc_apfloat)
   Compiling parking_lot_core v0.2.14
   Compiling tempdir v0.3.7
   Compiling flate2 v1.0.1
   Compiling parking_lot v0.5.5
   Compiling rustc_data_structures v0.0.0 (file:///Users/alex/Software/rust/src/librustc_data_structures)
   Compiling rls-span v0.4.0
   Compiling rls-data v0.15.0
   Compiling syntax_pos v0.0.0 (file:///Users/alex/Software/rust/src/libsyntax_pos)
   Compiling arena v0.0.0 (file:///Users/alex/Software/rust/src/libarena)
   Compiling rustc_errors v0.0.0 (file:///Users/alex/Software/rust/src/librustc_errors)
   Compiling proc_macro v0.0.0 (file:///Users/alex/Software/rust/src/libproc_macro)
   Compiling rustc_const_math v0.0.0 (file:///Users/alex/Software/rust/src/librustc_const_math)
   Compiling syntax_ext v0.0.0 (file:///Users/alex/Software/rust/src/libsyntax_ext)
   Compiling rustc_typeck v0.0.0 (file:///Users/alex/Software/rust/src/librustc_typeck)
   Compiling rustc_mir v0.0.0 (file:///Users/alex/Software/rust/src/librustc_mir)
   Compiling rustc_allocator v0.0.0 (file:///Users/alex/Software/rust/src/librustc_allocator)
   Compiling rustc_traits v0.0.0 (file:///Users/alex/Software/rust/src/librustc_traits)
   Compiling rustc_resolve v0.0.0 (file:///Users/alex/Software/rust/src/librustc_resolve)
   Compiling rustc_plugin v0.0.0 (file:///Users/alex/Software/rust/src/librustc_plugin)
   Compiling rustc_privacy v0.0.0 (file:///Users/alex/Software/rust/src/librustc_privacy)
   Compiling rustc_save_analysis v0.0.0 (file:///Users/alex/Software/rust/src/librustc_save_analysis)
   Compiling rustc_lint v0.0.0 (file:///Users/alex/Software/rust/src/librustc_lint)
   Compiling rustc_trans_utils v0.0.0 (file:///Users/alex/Software/rust/src/librustc_trans_utils)
   Compiling rustc_borrowck v0.0.0 (file:///Users/alex/Software/rust/src/librustc_borrowck)
   Compiling rustc_passes v0.0.0 (file:///Users/alex/Software/rust/src/librustc_passes)
   Compiling rustc-main v0.0.0 (file:///Users/alex/Software/rust/src/rustc)
    Finished release [optimized] target(s) in 694.18 secs
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 codegen artifacts (x86_64-apple-darwin -> x86_64-apple-darwin, llvm)
   Compiling build_helper v0.1.0 (file:///Users/alex/Software/rust/src/build_helper)
   Compiling rustc_trans v0.0.0 (file:///Users/alex/Software/rust/src/librustc_trans)
   Compiling cc v1.0.10
   Compiling num_cpus v1.8.0
   Compiling rustc_llvm v0.0.0 (file:///Users/alex/Software/rust/src/librustc_llvm)
    Finished release [optimized] target(s) in 67.70 secs
Assembling stage1 compiler (x86_64-apple-darwin)
Building stage1 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling core v0.0.0 (file:///Users/alex/Software/rust/src/libcore)
   Compiling unwind v0.0.0 (file:///Users/alex/Software/rust/src/libunwind)
   Compiling compiler_builtins v0.0.0 (file:///Users/alex/Software/rust/src/rustc/compiler_builtins_shim)
   Compiling alloc_jemalloc v0.0.0 (file:///Users/alex/Software/rust/src/liballoc_jemalloc)
   Compiling rustc_asan v0.0.0 (file:///Users/alex/Software/rust/src/librustc_asan)
   Compiling rustc_tsan v0.0.0 (file:///Users/alex/Software/rust/src/librustc_tsan)
   Compiling std v0.0.0 (file:///Users/alex/Software/rust/src/libstd)
error: internal compiler error: librustc/ty/context.rs:275: node unknown node (id=1) with HirId::owner DefId(0/0:0 ~ core[7c27]) cannot be placed in TypeckTables with local_id_root DefId(0/0:1840 ~ core[7c27]::panicking[0]::panic_fmt[0])

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:546:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-dev running on x86_64-apple-darwin

note: compiler flags: -Z save-analysis -Z osx-rpath-install-name -Z force-unstable-if-unmarked -C opt-level=2 -C prefer-dynamic -C debug-assertions=y -C codegen-units=8 -C link-args=-Wl,-rpath,@loader_path/../lib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/Users/alex/Software/rust/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=be5db4a71f87466b -C extra-filename=-be5db4a71f87466b --out-dir /Users/alex/Software/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -L dependency=/Users/alex/Software/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps -L dependency=/Users/alex/Software/rust/build/x86_64-apple-darwin/stage1-std/release/deps` (exit code: 101)
command did not execute successfully: "/Users/alex/Software/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-j" "8" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/Users/alex/Software/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1091:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /Users/alex/Software/rust/build/bootstrap/debug/bootstrap -i build
Build completed unsuccessfully in 0:15:41
```

Is this a bug in the build process?

I'm on macOS 10.13.4, incidentally.

### LINKED ISSUE #63663: dist-x86_64-freebsd fails when building with debug assertions
Steps to reproduce:

1. Run `src/ci/docker/run.sh dist-x86_64-freebsd` (note that `DEPLOY=1` is *not* set, which is why we don't see this on Azure)
2. Observe the following ICE ([full log](https://gist.github.com/Aaron1011/244ec6c1126e433767e117b7d22186fe)):

```
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-freebsd)
   Compiling core v0.0.0 (/checkout/src/libcore)
error: internal compiler error: src/librustc/ty/context.rs:213: node type <T>::IntoIter (hir_id=HirId { owner: DefIndex(4038), local_id: 61 }) with HirId::owner DefId(0:4038 ~ core[db27]::iter[0]::adapters[0]::flatten[0]::{{impl}}[13]::try_fold[0]::flatten[0]) cannot be placed in TypeckTables with local_id_root DefId(0:4034 ~ core[db27]::iter[0]::adapters[0]::flatten[0]::{{impl}}[13]::try_fold[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: rustc::util::common::panic_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: rustc_errors::Handler::bug
   6: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   7: rustc::ty::context::tls::with_opt::{{closure}}
   8: rustc::ty::context::tls::with_context_opt
   9: rustc::ty::context::tls::with_opt
  10: rustc::util::bug::opt_span_bug_fmt
  11: rustc::util::bug::bug_fmt
  12: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
  13: rustc::ty::context::tls::with::{{closure}}
  14: rustc::ty::context::tls::with_context::{{closure}}
  15: rustc::ty::context::tls::with_context_opt
  16: rustc::ty::context::tls::with_context
  17: rustc::ty::context::tls::with
  18: rustc::ty::context::TypeckTables::qpath_res
  19: rustc_save_analysis::SaveContext::get_path_res
  20: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty
  21: syntax::visit::walk_generic_args
  22: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty
  23: syntax::visit::walk_ty
  24: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  25: rustc_save_analysis::dump_visitor::DumpVisitor::process_method
  26: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  27: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  28: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  29: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  30: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod
  31: syntax::visit::walk_crate
  32: rustc::dep_graph::graph::DepGraph::with_ignore
  33: rustc_save_analysis::process_crate
  34: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
  35: rustc::util::common::time
  36: rustc::ty::context::tls::enter_global
  37: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  38: rustc_interface::passes::create_global_ctxt::{{closure}}
  39: rustc_interface::interface::run_compiler_in_existing_thread_pool
  40: std::thread::local::LocalKey<T>::with
  41: scoped_tls::ScopedKey<T>::set
  42: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
end of query stack
error: aborting due to previous error
```

This appears to be a legimitate bug, which is normally not exposed due to the `if cfg!(debug_assertions)` block in `validate_hir_id_for_typeck_tables` not running on CI.

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes an issue where we did not nest tables correctly when resolving
associated types in formal argument/return type positions.

This was the minimized reproduction case that I tested the fix on:
```rust
pub trait Trait {
    type Assoc;
}

pub struct A;

pub fn func() {
    fn _inner1<U: Trait>(_: U::Assoc) {}
    fn _inner2<U: Trait>() -> U::Assoc { unimplemented!() }

    impl A {
        fn _inner1<U: Trait>(self, _: U::Assoc) {}
        fn _inner2<U: Trait>(self) -> U::Assoc { unimplemented!() }
    }
}
```
using `debug_assertions`-enabled rustc and by additionally passing `-Zsave-analysis`.

Unfortunately the original assertion fired is a *debug* one and from what I can tell we don't run the tests with these on, so I'm not adding a test here. If I missed it and there is a way to run tests with these on, I'd love to add a test case for this.

Closes #63663
Closes #50328 
Closes #43982

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We can probably change the assertion to be a non-debug assertion?

File: src/librustc_save_analysis/dump_visitor.rs [hunk 1]
```diff
@@ -377,26 +373,26 @@ impl<'l, 'tcx> DumpVisitor<'l, 'tcx> {
...
-            );
-            self.process_generic_params(ty_params, &fn_data.qualname, item.id);
-            let hir_id = self.tcx.hir().node_to_hir_id(item.id);
-            self.dumper.dump_def(&access_from!(self.save_ctxt, item, hir_id), fn_data);
-        }
+        let hir_id = self.tcx.hir().node_to_hir_id(item.id);
+        self.nest_tables(item.id, |v| {
+            if let Some(fn_data) = v.save_ctxt.get_item_data(item) {
+                down_cast_data!(fn_data, DefData, item.span);
+                v.process_formals(&decl.inputs, &fn_data.qualname);
```
Comment (Centril) [inline src/librustc_save_analysis/dump_visitor.rs]: Aside: `process_formals` probably need to be fixed to work like `process_var_decls` -- it probably works poorly with or-patterns now.

**Comment by Xanewok** [comment]
> We can probably change the assertion to be a non-debug assertion?

Started a try->perf run over at https://github.com/rust-lang/rust/pull/64262

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (Xanewok) [reply src/librustc_save_analysis/dump_visitor.rs]: Thanks for the heads up! Could you please give a simple minimized test case to help me verify the fix/revamp if we were to update the `process_formals` to account for the or-patterns?

Comment (Centril) [reply src/librustc_save_analysis/dump_visitor.rs]: I know very little about save-analysis so I don't think I can help out with test cases. Basically, I did some changes in https://github.com/rust-lang/rust/pull/64111/files#diff-426e1c382fc57abf697fdeee18e03dde to handle or-patterns in nested positions but I didn't test them. I mostly fused `process_var_decl` and `process_var_decl_multi`. Ideally, you should fuse `process_formals` with `process_var_decl`s as well and get some good code-reuse out of it.

The new thing you have to account for wrt. or-patterns is that users can write `fn foo((Ok(x) | Err(x)): Result<T, E>) { ... }` and such things.

Comment (Xanewok) [reply src/librustc_save_analysis/dump_visitor.rs]: I'm hitting an [unimplemented arm](https://github.com/rust-lang/rust/blob/1870537f2701e5aa47080a879b63a4d6b391553b/src/librustc_mir/hair/pattern/_match.rs#L1363) when trying to use an or-pattern in the argument position (where this SA bug has uncovered) so I'd like to come back after this feature has been more fleshed out, if you don't mind :+1:

**Comment by Xanewok** [comment]
Perf run turned out to be okay, so I dropped the conditional compilation on debug assertions and added a test case.

File: src/librustc_save_analysis/dump_visitor.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_save_analysis/dump_visitor.rs]: @Xanewok Oh definitely; the feature is totally WIP -- I would recommend filing a keep-sake issue for now and assigning yourself, myself, and @dlrobertson for now.

Comment (dlrobertson) [reply src/librustc_save_analysis/dump_visitor.rs]: Yeah, still working on that. When https://github.com/rust-lang/rust/pull/63688 is finished the ICE shouldn't happen any more.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/64366#issuecomment-530142014, @bors r-

**Comment by Xanewok** [comment]
That's unfortunate, thanks for the heads up; will look into it tomorrow

**Comment by Xanewok** [comment]
This is updated and ready for review again.

The last bug was uncovered when processing type paths in return type `impl Trait`s.

Specifically, this is because we try to resolve the qualified type path using the typeck tables but a debug assertion fires since the def id of the type path and that of the table don't share the same local id root.
That's because the `impl Trait` lowering creates a definition introducing a separate `{{opaque}}` def path segment with trait bounds as def children.

Unfortunately, the correct way under the current architecture would be to nest the tables further, however from what I can tell the newly lowered synthetic def path segment does not have typeck tables (probably rightly so? @nikomatsakis), so to prevent the underlying ICE and to enable the debug assertion for good now, I decided to only add explanatory comments and skip processing bounds in `impl Trait`s in return type position for now.

As a side note, the current save-analysis infrastructure is slowly becoming dated as we introduce more supporting infrastructure with time (e.g. cleaning up resolution, definition infra from incremental), so it might be worth thinking how to handle it in the medium-term (leverage HIR directly instead of AST? maybe use it as a way to somehow bridge/push for librarification of the frontend?).

**Comment by jonas-schievink** [comment]
This also fixes #57298 and https://github.com/rust-lang/rust/issues/55172

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/commit/b456c820ffe6f19d133f196d3e935071f326094e lets Clippy ICE, when calling `qpath_res` on the `HirId` of a struct field type.

Call stack:
```rust
LateLintPass::check_struct_field(.., cx, field);
cx.tables.qpath_res(field.ty.node -> qpath, field.ty.hir_id);
```

This seems weird to me, since we're checking the `QPath` of a HIR node with the `HirId` of the same node. @Xanewok is this related to https://github.com/rust-lang/rust/pull/64250#issuecomment-531521579?

**Comment by Xanewok** [comment]
Left some explanation on why the assertion fires and how to fix it at https://github.com/rust-lang/rust-clippy/pull/4545#issuecomment-532137544
