### PR TITLE
Fix ICE on offsetted ZST pointer

### LINKED ISSUE #147516: ICE compiler/rustc_codegen_llvm/src/common.rs 2 == 0
### Code

```Rust
use std::mem::size_of;
fn distance_between<T>(dest: *const T, origin: *const T) -> usize {
    match size_of::<T> {
        _ => origin as usize,
    }
}
struct S;
const X: [S; 4] = [S, S, S, S];
const Y: *const S = X.as_ptr();
const Z: *const S = (Y as *const u8).wrapping_add(2) as *const S;
pub fn main() {
    println!("{}", distance_between(Z, Y))
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (b6f0945e4 2025-10-08)
binary: rustc
commit-hash: b6f0945e4681bc4d2faa7c22c5f61dc36abf7dd2
commit-date: 2025-10-08
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.2
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused variable: `dest`
 --> /tmp/crash.rs:2:24
  |
2 | fn distance_between<T>(dest: *const T, origin: *const T) -> usize {
  |                        ^^^^ help: if this is intentional, prefix it with an underscore: `_dest`
  |
  = note: `#[warn(unused_variables)]` (part of `#[warn(unused)]`) on by default


thread 'rustc' (2735798) panicked at compiler/rustc_codegen_llvm/src/common.rs:284:29:
assertion `left == right` failed
  left: 2
 right: 0
stack backtrace:
   0:     0x7f13533d0013 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he87f93fe67261167
   1:     0x7f1353a01fbc - core::fmt::write::h0aa8549825819386
   2:     0x7f1353384b23 - std::io::Write::write_fmt::hd2151e08de10ff28
   3:     0x7f1353395fd2 - std::sys::backtrace::BacktraceLock::print::hf8464fe9ebf511be
   4:     0x7f135339c049 - std::panicking::default_hook::{{closure}}::hcd5485a5a088b562
   5:     0x7f135339bb73 - std::panicking::default_hook::hbece1839525cb3ec
   6:     0x7f13523b11c7 - std[abce4abe465e799c]::panicking::update_hook::<alloc[498c48ead57cdc4d]::boxed::Box<rustc_driver_impl[733c77d8475951ea]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f135339c46f - std::panicking::panic_with_hook::h660232911cf5a466
   8:     0x7f135339c22a - std::panicking::panic_handler::{{closure}}::ha66df24170df4402
   9:     0x7f1353396109 - std::sys::backtrace::__rust_end_short_backtrace::h8cf9a3411dc4e011
  10:     0x7f1353376c4d - __rustc[2820174ead26b8c1]::rust_begin_unwind
  11:     0x7f1350413ab0 - core::panicking::panic_fmt::h23b7ba79e91532e5
  12:     0x7f1351da3613 - core::panicking::assert_failed_inner::h410308ccf8fd7afe
  13:     0x7f1351da3417 - core::panicking::assert_failed::h2bf0e8c9a81b1395
  14:     0x7f1353a51259 - <rustc_codegen_ssa[19deb97213f21bba]::mir::FunctionCx<rustc_codegen_llvm[a55033960f7fe7e7]::builder::GenericBuilder<rustc_codegen_llvm[a55033960f7fe7e7]::context::FullCx>>>::eval_mir_constant_to_operand
  15:     0x7f135428f8bd - <rustc_codegen_ssa[19deb97213f21bba]::mir::FunctionCx<rustc_codegen_llvm[a55033960f7fe7e7]::builder::GenericBuilder<rustc_codegen_llvm[a55033960f7fe7e7]::context::FullCx>>>::codegen_operand
  16:     0x7f1354e05c3a - rustc_codegen_ssa[19deb97213f21bba]::mir::codegen_mir::<rustc_codegen_llvm[a55033960f7fe7e7]::builder::GenericBuilder<rustc_codegen_llvm[a55033960f7fe7e7]::context::FullCx>>
  17:     0x7f1353b34bab - rustc_codegen_llvm[a55033960f7fe7e7]::base::compile_codegen_unit::module_codegen
  18:     0x7f1354b3fb1f - <rustc_codegen_llvm[a55033960f7fe7e7]::LlvmCodegenBackend as rustc_codegen_ssa[19deb97213f21bba]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  19:     0x7f1354b3dace - <rustc_codegen_llvm[a55033960f7fe7e7]::LlvmCodegenBackend as rustc_codegen_ssa[19deb97213f21bba]::traits::backend::CodegenBackend>::codegen_crate
  20:     0x7f1354ca5130 - <rustc_interface[9f858680fc2dc059]::queries::Linker>::codegen_and_build_linker
  21:     0x7f1354ca2c70 - rustc_interface[9f858680fc2dc059]::passes::create_and_enter_global_ctxt::<core[4feb8f9d84ac7ee5]::option::Option<rustc_interface[9f858680fc2dc059]::queries::Linker>, rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  22:     0x7f1354c9a6c3 - <rustc_interface[9f858680fc2dc059]::passes::create_and_enter_global_ctxt<core[4feb8f9d84ac7ee5]::option::Option<rustc_interface[9f858680fc2dc059]::queries::Linker>, rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[4feb8f9d84ac7ee5]::ops::function::FnOnce<(&rustc_session[baee98d18babd558]::session::Session, rustc_middle[141878caf28dce8a]::ty::context::CurrentGcx, alloc[498c48ead57cdc4d]::sync::Arc<rustc_data_structures[65b165cb2c4fb825]::jobserver::Proxy>, &std[abce4abe465e799c]::sync::once_lock::OnceLock<rustc_middle[141878caf28dce8a]::ty::context::GlobalCtxt>, &rustc_data_structures[65b165cb2c4fb825]::sync::worker_local::WorkerLocal<rustc_middle[141878caf28dce8a]::arena::Arena>, &rustc_data_structures[65b165cb2c4fb825]::sync::worker_local::WorkerLocal<rustc_hir[8913ca6aecdf6079]::Arena>, rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  23:     0x7f1354c559fe - rustc_interface[9f858680fc2dc059]::interface::run_compiler::<(), rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}>::{closure#1}
  24:     0x7f1354b25f47 - std[abce4abe465e799c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[9f858680fc2dc059]::util::run_in_thread_with_globals<rustc_interface[9f858680fc2dc059]::util::run_in_thread_pool_with_globals<rustc_interface[9f858680fc2dc059]::interface::run_compiler<(), rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  25:     0x7f1354b25c28 - <<std[abce4abe465e799c]::thread::Builder>::spawn_unchecked_<rustc_interface[9f858680fc2dc059]::util::run_in_thread_with_globals<rustc_interface[9f858680fc2dc059]::util::run_in_thread_pool_with_globals<rustc_interface[9f858680fc2dc059]::interface::run_compiler<(), rustc_driver_impl[733c77d8475951ea]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[4feb8f9d84ac7ee5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f1354b2c3cd - std::sys::thread::unix::Thread::new::thread_start::h2b74411d58f20435
  27:     0x7f134e4969cb - <unknown>
  28:     0x7f134e51aa0c - <unknown>
  29:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/matthias/vcs/github/CRED/rustc-ice-2025-10-09T09_51_49-2735780.txt` to your bug report

query stack during panic:
end of query stack
warning: 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
I'm not sure this is the *right* fix, but it's simple enough and does roughly what I'd expect. Like with the previous optimization to codegen usize rather than a zero-sized static, there's no guarantee that we continue returning a particular value from the offsetting.

A grep for `const_usize.*align` found the same code copied to rustc_codegen_gcc and cranelift but a quick skim didn't find other cases of similar 'optimization'. That said, I'm not convinced I caught everything, it's not trivial to search for this.

Closes rust-lang/rust#147516

### CODE REVIEW

File: tests/ui/consts/zst_no_llvm_alloc.rs [hunk 1]
```diff
@@ -5,6 +5,11 @@ struct Foo;
 
 static FOO: Foo = Foo;
 
+// This tests for regression of https://github.com/rust-lang/rust/issues/147516
+const A: *const () = (&() as *const ()).wrapping_byte_add(2);
+const B: *const () = (&Foo as *const _ as *const ()).wrapping_byte_add(2);
+const C: *const () = (&Foo as *const _ as *const ()).wrapping_byte_add(usize::MAX);
+
```
Comment (nnethercote) [inline tests/ui/consts/zst_no_llvm_alloc.rs:18]: I don't understand this at all. Can you explain a little? Perhaps this test needs an explanatory comment at the top?

Comment (Mark-Simulacrum) [reply tests/ui/consts/zst_no_llvm_alloc.rs:18]: I extended with a longer comment, but without a bit more detail on what you're confused by it's hard to know whether it helps. Let me know.

Comment (nnethercote) [reply tests/ui/consts/zst_no_llvm_alloc.rs:18]: Thanks, that helps... but I still don't understand where the values of 3, 3, and 6 come from.

Comment (Mark-Simulacrum) [reply tests/ui/consts/zst_no_llvm_alloc.rs:18]: * A 1-aligned ZST (1-ZST) is placed at `0x1`. Then offsetting that by 2 results in 3.
* `Foo` is a 4-aligned ZST, so is placed at `0x4`. +2 = 6
* `Foo` is a 4-aligned ZST, so is placed at `0x4`. +usize::MAX = -1 (same bit pattern)  = 3

Comment (nnethercote) [reply tests/ui/consts/zst_no_llvm_alloc.rs:18]: Please add that to the comment! Also, why is `Foo` a 4-ZST? Add that information too, and then r=me, thanks.

Comment (Mark-Simulacrum) [reply tests/ui/consts/zst_no_llvm_alloc.rs:18]: I'll skip adding why Foo is a 4-ZST -- it's likely obvious if you saw the full file, it has a repr(align(4)) on it. If you mean *why* 4 (and not some other number), there's not a particular meaning behind 4. Documented that on Foo itself.

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 2]
```diff
@@ -367,4 +367,11 @@ impl Pointer<CtfeProvenance> {
     pub fn prov_and_relative_offset(self) -> (CtfeProvenance, Size) {
         (self.provenance, self.offset)
     }
+
+    /// Assuming that the pointer is to a ZST, this computes the appropriate value to use for the
+    /// result of properly aligning (essentially `ptr::dangling`) and offsetting the resulting
+    /// pointer.
+    pub fn zst_addr(self, align: Align, cx: &impl HasDataLayout) -> u64 {
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs]: I can't make any sense of this comment, unfortunately. If this pointer points to an actual allocation, it makes no logical sense to just add its offset to anything else except for the address of that allocation.

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs]: Oh, this is about pointers to zero-sized *allocations* -- not ZST pointers in general. `&()` can point inside a larger allocation and then this function **must not** be used.

And even then, the *only* time this function is correct to use if if the caller can guarantee that *all* pointers to this allocation are treated like this. I am not sure that should be such an easy-to-accidentally-misuse helper like this.

File: compiler/rustc_codegen_llvm/src/common.rs [hunk 3]
```diff
@@ -281,8 +281,8 @@ impl<'ll, 'tcx> ConstCodegenMethods for CodegenCx<'ll, 'tcx> {
                         // This avoids generating a zero-sized constant value and actually needing a
                         // real address at runtime.
                         if alloc.inner().len() == 0 {
-                            assert_eq!(offset.bytes(), 0);
-                            let llval = self.const_usize(alloc.inner().align.bytes());
+                            let llval =
+                                self.const_usize(ptr.zst_addr(alloc.inner().align, &self.tcx));
```
Comment (RalfJung) [inline compiler/rustc_codegen_llvm/src/common.rs]: You already have the `offset` in scope here. I'd rather see this compute `align + offset` directly. This operation doesn't make sense on the "aggregated" pointer, it is correct only because we are already "deaggregating" the pointer into its parts here.

Comment (Mark-Simulacrum) [reply compiler/rustc_codegen_llvm/src/common.rs]: I'm not particularly happy with the helper, happy to duplicate the code three times instead (or maybe we can move this into codegen_ssa or something, I'll poke at it).

Generally agreed that it seems like this is basically only useful in this codegen code (albeit we have three copies of it).

File: tests/ui/consts/zst_no_llvm_alloc.rs [hunk 4]
```diff
@@ -1,10 +1,21 @@
...
 
+// We need some non-1 alignment to test we use the alignment of the type in the compiler.
 #[repr(align(4))]
 struct Foo;
 
 static FOO: Foo = Foo;
 
+// This tests for regression of https://github.com/rust-lang/rust/issues/147516
+//
+// THe compiler will codegen `&Zst` without creating a real allocation, just a properly aligned
```
Comment (RalfJung) [inline tests/ui/consts/zst_no_llvm_alloc.rs]:
```suggestion
// The compiler will codegen `&Zst` without creating a real allocation, just a properly aligned
```

File: tests/ui/consts/zst_no_llvm_alloc.rs [hunk 5]
```diff
@@ -1,10 +1,21 @@
...
+// `usize` (i.e., ptr::dangling). However, code can add an arbitrary offset from that base
+// allocation. We confirm here that we correctly codegen that offset combined with the necessary
+// alignment of the base &() as a 1-ZST and &Foo as a 4-ZST.
+const A: *const () = (&() as *const ()).wrapping_byte_add(2);
+const B: *const () = (&Foo as *const _ as *const ()).wrapping_byte_add(usize::MAX);
+const C: *const () = (&Foo as *const _ as *const ()).wrapping_byte_add(2);
```
Comment (RalfJung) [inline tests/ui/consts/zst_no_llvm_alloc.rs:17]: Can you add a test using `wrapping_byte_sub(1)` or so to also cover the overflowing case?

Comment (RalfJung) [reply tests/ui/consts/zst_no_llvm_alloc.rs:17]: Oh, you are adding `usize::MAX` already which covers that, never mind.

File: compiler/rustc_codegen_cranelift/src/constant.rs [hunk 6]
```diff
@@ -138,8 +140,11 @@ pub(crate) fn codegen_const_value<'tcx>(
                 let base_addr = match fx.tcx.global_alloc(alloc_id) {
                     GlobalAlloc::Memory(alloc) => {
                         if alloc.inner().len() == 0 {
-                            assert_eq!(offset, Size::ZERO);
-                            fx.bcx.ins().iconst(fx.pointer_type, alloc.inner().align.bytes() as i64)
+                            let val = alloc.inner().align.bytes().wrapping_add(offset.bytes());
+                            fx.bcx.ins().iconst(
+                                fx.pointer_type,
+                                fx.tcx.truncate_to_target_usize(val) as i64,
+                            )
```
Comment (bjorn3) [inline compiler/rustc_codegen_cranelift/src/constant.rs:147]: The proper fix would have been to remove the `assert_eq!()` here and to do the `truncate_to_target_usize` at the `fx.bcx.ins().iadd_imm(base_addr, i64::try_from(offset.bytes()).unwrap())` below. As is this still ICEs. Will push a fix to the cg_clif repo.
Edit: https://github.com/rust-lang/rustc_codegen_cranelift/commit/ca23203edb4512047565297ce11784b11f427a50
