### PR TITLE
Fix unsoundness bug in functions input references

### LINKED ISSUE #48803: Converting "&'a &'b T" to "&'a T" in the presence of non-lexical lifetimes can be unsound
The following snippet should be rejected for allowing a value to be mutated while it is borrowed, but it is accepted on nightly when non-lexical lifetimes are enabled ([playground](https://play.rust-lang.org/?gist=270115299b6bbf2849930abe1e745f21&version=nightly)):

```rust
#![feature(nll)]

fn flatten<'a, 'b, T>(x: &'a &'b T) -> &'a T {
    x
}

fn main() {
    let mut x = "original";
    let y = &x;
    let z = &y;
    let w = flatten(z);
    x = "modified";
    println!("{}", w); // prints "modified"
}
```

### PR DESCRIPTION
**Pull request by spastorino**
Fixes #48803

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 1]
```diff
@@ -1511,28 +1511,35 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
...
+        &mut self,
+        predicates: impl IntoIterator<Item = ty::Predicate<'tcx>>,
+        location: Location,
+    ) {
+        let mut predicates_iter = predicates.into_iter();
+
         debug!(
             "prove_predicates(predicates={:?}, location={:?})",
-            predicates, location
+            predicates_iter.by_ref().collect::<Vec<_>>(),
```
Comment (tamird) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: won't this exhaust the iterator, so that this code no longer generates any obligations below when debug output is enabled?

Comment (spastorino) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Ooops, you're right. Going to fix this :).

Comment (spastorino) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Fixed, PR sent https://github.com/rust-lang/rust/pull/50076
