### PR TITLE
Don't trigger `unsafe_op_in_unsafe_fn` for deprecated safe fns

### LINKED ISSUE #125875: `std::env::remove_var()` becomes `unsafe` even in Rust 2021
I tried this code:

```rust
#![deny(unsafe_op_in_unsafe_fn)]

fn main() {
    unsafe { foo() };
}

unsafe fn foo() {
    std::env::remove_var("foo");
}
```

```toml
[package]
name = "remove_var_2021_reproduction"
version = "0.1.0"
edition = "2021"

[dependencies]
```

I expected to see this happen: 

`std::env::remove_var()` will become `unsafe` in Rust 2024, the above code is using Rust 2021, so this should compile with no issue. 

Instead, this happened: 

```sh
$ cargo +nightly b
   Compiling remove_var_2021_reproduction v0.1.0 (remove_var_2021_reproduction)
error[E0133]: call to unsafe function `std::env::remove_var` is unsafe and requires unsafe block
 --> src/main.rs:8:5
  |
8 |     std::env::remove_var("foo");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
  |
  = note: for more information, see issue #71668 <https://github.com/rust-lang/rust/issues/71668>
  = note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its body is safe by default
 --> src/main.rs:7:1
  |
7 | unsafe fn foo() {
  | ^^^^^^^^^^^^^^^
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(unsafe_op_in_unsafe_fn)]
  |         ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0133`.
error: could not compile `remove_var_2021_reproduction` (bin "remove_var_2021_reproduction") due to 1 previous error
```

### Meta

`rustc --version --verbose`:
```
$ rustc +nightly --version --verbose
rustc 1.80.0-nightly (ada5e2c7b 2024-05-31)
binary: rustc
commit-hash: ada5e2c7b5427a591e30baeeee2698a5eb6db0bd
commit-date: 2024-05-31
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

<details><summary>Backtrace</summary>
<p>

Not needed

</p>
</details>

### Possible root cause

I think the root cause is the lint `unsafe_op_in_unsafe_fn`, commenting it out would make the code compile:

```sh
$ rg unsafe_op src/main.rs
1:// #![deny(unsafe_op_in_unsafe_fn)]

$ cargo +nightly b
   Compiling remove_var_2021_reproduction v0.1.0 (remove_var_2021_reproduction)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
```

### PR DESCRIPTION
**Pull request by tbu-**
Fixes #125875.

Tracking:

- #124866

### CODE REVIEW

File: compiler/rustc_mir_build/src/check_unsafety.rs [hunk 1]
```diff
@@ -88,6 +88,33 @@ impl<'tcx> UnsafetyVisitor<'_, 'tcx> {
         }
     }
 
+    fn emit_deprecated_safe_fn_call(&self, span: Span, kind: &UnsafeOpKind) -> bool {
+        match kind {
+            // Allow calls to deprecated-safe unsafe functions if the caller is
+            // from an edition before 2024.
+            &UnsafeOpKind::CallToUnsafeFunction(Some(id))
+                if !span.at_least_rust_2024()
+                    && self.tcx.has_attr(id, sym::rustc_deprecated_safe_2024) =>
```
Comment (asquared31415) [inline compiler/rustc_mir_build/src/check_unsafety.rs:97]: While this PR should probably go through as-is to get the fix in as soon as possible, I feel like this system is somewhat brittle, relying on specifically the symbol `rustc_deprecated_safe_2024` and the edition being hard coded to check at least `2024`.  I wonder if it would be a good idea for a follow up PR to somehow make this general in that the attribute could specify an edition in which a function starts becoming unsafe, and check that edition?

However, such a followup assumes that we will make more functions `unsafe` in  the future due to oversight.  Ideally we don't have to do that, and I think that the current state of things is such that just about everything has been audited?  So perhaps it's not worth such a generalization, since it ideally doesn't happen again.

Comment (tbu-) [reply compiler/rustc_mir_build/src/check_unsafety.rs:97]: > While this PR should probably go through as-is to get the fix in as soon as possible, I feel like this system is somewhat brittle, relying on specifically the symbol `rustc_deprecated_safe_2024` and the edition being hard coded to check at least `2024`. I wonder if it would be a good idea for a follow up PR to somehow make this general in that the attribute could specify an edition in which a function starts becoming unsafe, and check that edition?

Such a more general has been proposed and can probably be implemented. `#[rustc_deprecated_safe_2024]` was intentionally limited in scope in order to make `std::env::{set_var, remove_var}` unsafe in Rust 2024.

File: compiler/rustc_mir_build/src/check_unsafety.rs [hunk 2]
```diff
@@ -100,6 +127,7 @@ impl<'tcx> UnsafetyVisitor<'_, 'tcx> {
                 *used = true;
             }
             SafetyContext::UnsafeFn if unsafe_op_in_unsafe_fn_allowed => {}
+            SafetyContext::UnsafeFn if self.emit_deprecated_safe_fn_call(span, &kind) => {}
```
Comment (Nadrieril) [inline compiler/rustc_mir_build/src/check_unsafety.rs:130]: Code-style-wise, a match guard like this suggests that the function has no side-effects. I initially read the like as "if we should emit a lint related to a call to a deprecated safe function". I'd find it clearer as e.g.:
```suggestion
            SafetyContext::UnsafeFn => {
                let deprecated_safe_fn = self.emit_deprecated_safe_fn_call(span, &kind);
                if !deprecated_safe_fn {
                    // unsafe_op_in_unsafe_fn is disallowed
                	kind.emit_unsafe_op_in_unsafe_fn_lint(
                	    ...
                	)
                }
            }
```

**Comment by Nadrieril** [comment]
I have one style comment, feel free to ignore it or fix it now or fix it in a later PR. r=me if you decide not to fix it now.

@bors delegate+

File: compiler/rustc_mir_build/src/check_unsafety.rs (hunk 2 above)
Comment (tbu-) [reply compiler/rustc_mir_build/src/check_unsafety.rs]: Applied your suggestion.
