### PR TITLE
Regression test for AVR `rjmp` offset

### LINKED ISSUE #129301: Incorrect relative jump (rjmp) code generation in latest nightly release for AVR toolchain
I've already asked this question on [stack exchange](https://arduino.stackexchange.com/questions/96691/finite-loop-runs-infinitely/) where you can see more details.

I tried the following code:
``` rust
#![no_std]
#![no_main]
#![feature(asm_experimental_arch)]

use core::{arch::asm, hint::black_box, panic::PanicInfo};

use avrd::atmega328p;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

#[inline(never)]
fn delay(x: u32) {
    for _ in 0..x {
        unsafe {
            asm!("nop");
        }
    }
}

unsafe fn write_reg(reg: *mut u8, val: u8, mask: u8) {
    let reg_val = reg.read_volatile();
    reg.write_volatile((reg_val & !mask) | (val & mask));
}

#[no_mangle]
extern "C" fn main() -> ! {
    const LED_BUILTIN: u8 = 5;
    unsafe {
        let portB_data_direction = atmega328p::DDRB;
        // set it to output mode
        write_reg(portB_data_direction, 1 << LED_BUILTIN, 1 << LED_BUILTIN);
        let portB = atmega328p::PORTB;
        // switch it on, hopefully..
        loop {
            write_reg(portB, 1 << LED_BUILTIN, 1 << LED_BUILTIN);
            delay(500_0000);
            write_reg(portB, 0, 1 << LED_BUILTIN);
            delay(500_0000);
        }
    }
}
```

The `RUSTFLAGS="--emit asm"` output is also correct, but the machine code generated is faulty.  For now I've switched to nightly-2023-12-11, which seems to work just fine.

For the disassembly of both the `--emit asm` and the final binary, you can refer to the stack exchange post.
Here's a minimal example that doesn't work on nightly (but works on nightly-2023-12-11):
``` rust
#![no_std]
#![no_main]

use core::{hint::black_box, panic::PanicInfo};

use avrd::atmega328p;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
extern "C" fn main() -> ! {
    const LED_BUILTIN: u8 = 5;
    unsafe {
        let portB_data_direction = atmega328p::DDRB;
        // set it to output mode
        *portB_data_direction |= 1 << LED_BUILTIN;
        let portB = atmega328p::PORTB;

        loop {
            *portB ^= 1 << LED_BUILTIN;
            for i in 0..500_000 {
                black_box(i);
            }
            *portB ^= 1 << LED_BUILTIN;
            for i in 0..500_000 {
                black_box(i);
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by jfrimmel**
This adds a regression test for #129301 by minimizing the code in the linked issue and putting it into a `#![no_core]`-compatible format, so that it can easily be used within an `rmake`-test. This needs to be a `rmake` test (opposed to a `tests/assembly` one), since the linked issue describes, that the problem only occurs if the code is directly compiled. Note, that `lld` is used instead of `avr-gcc`; see the [comments](https://github.com/rust-lang/rust/pull/131755#issuecomment-2416469675) [below](https://github.com/rust-lang/rust/pull/131755#issuecomment-2417160045).
Closes #129301.

To show, that the test actually catches the wrong behavior, this can be tested with a faulty rustc:
```bash
$ rustup install nightly-2024-08-19
$ rustc +nightly-2024-08-19 -C opt-level=s -C panic=abort --target avr-unknown-gnu-atmega328 -Clinker=build/x86_64-unknown-linux-gnu/ci-llvm/bin/lld -Clink-arg='--entry=main' -o compiled tests/run-make/avr-rjmp-offset/avr-rjmp-offsets.rs
$ llvm-objdump -d compiled | grep '<main>' -A 6
000110b4 <main>:
   110b4: 81 e0         ldi     r24, 0x1
   110b6: 92 e0         ldi     r25, 0x2
   110b8: 85 b9         out     0x5, r24
   110ba: 95 b9         out     0x5, r25
   110bc: fe cf         rjmp    .-4
```
One can see, that the wrong label offset (`4` instead of `6`) is produced, which would trigger an assertion in the test case.

This would be a good candidate for using the `minicore` proposed in #130693. Since this is not yet merged, there is a FIXME.

r? Patryk27
I think, you are the yet-to-be official target maintainer, hence I'll assign to you.

@rustbot label +O-AVR

### CODE REVIEW

File: tests/run-make/avr-rjmp-offset/avr-rjmp-offsets.rs [hunk 1]
```diff
@@ -0,0 +1,51 @@
+//! This test case is a `#![no_core]`-version of the MVCE presented in #129301.
+//!
+//! The function [`delay()`] is removed, as it is not necessary to trigger the
+//! wrong behavior and would require some additional lang items.
+#![feature(no_core, lang_items, intrinsics, rustc_attrs, asm_experimental_arch)]
+#![no_core]
+#![no_main]
+
+#[rustc_builtin_macro]
```
Comment (jfrimmel) [inline tests/run-make/avr-rjmp-offset/avr-rjmp-offsets.rs:9]: Ah, the test case doesn't use `asm!` anymore. Therefore this can be removed.

**Comment by jfrimmel** [comment]
Uh, that's bad:
```console
error: linker `avr-gcc` not found
  = note: No such file or directory (os error 2)
```

It should be possible to reduce the actual linking step, though, as there are no external calls (needed to be resolved by the linker) in the loop in question, so a normal rlib should work as well.

**Comment by tgross35** [comment]
r? compiler
cc @Patryk27

File: tests/run-make/avr-rjmp-offset/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+//!
+//! Some LLVM-versions had wrong offsets in the local labels, causing the first
+//! loop instruction to be missed. This test therefore contains a simple loop
+//! with trivial instructions in it, to see, where the label is placed.
+//!
+//! This must be a `rmake`-test and cannot be a `tests/assembly`-test, since the
+//! wrong output is only produced with direct assembly generation, but not when
+//! "emit-asm" is used, as described in the issue description of #129301:
+//! https://github.com/rust-lang/rust/issues/129301#issue-2475070770
+use run_make_support::{llvm_objdump, rustc};
```
Comment (jieyouxu) [inline tests/run-make/avr-rjmp-offset/rmake.rs:11]: Hm, this probably needs some flags like

```
//@ only-avr
//@ needs-llvm-components: avr (otherwise will not work if local llvm built without avr component)
```

Comment (jfrimmel) [reply tests/run-make/avr-rjmp-offset/rmake.rs:11]: Oh yes, this is missing. I'll add the "needs-llvm-components"-directive. The `only-avr` doesn't seem to work, though: if I add this line, the test always gets ignored.

**Comment by jfrimmel** [comment]
Hm, there's a problem: it works locally, but not in CI. CI reports either of two issues:
1. when trying to perform linking (the more correct approach), the CI job fails due to the linker being missing. AVR is kinda special here, because (presumably) it's the only target relying on the GCC as its linker. Is there a sane work around this for the test?
2. when not performing linking (by only building an `rlib`), the labe does not get resolved in CI (but on my machine?!), causing the `rjmp` to have an offset of 0, which renders the test unusable.

Has anyone an idea?

**Comment by jieyouxu** [comment]
What do you mean by suggested test flow?

**Comment by jfrimmel** [comment]
Even if not yet merged, PR #131651 [documents, that the `avr-gcc`-linker should be used](https://github.com/rust-lang/rust/pull/131651/files#diff-6e6c18c8207727aea608b230239b7ae09378109a613fb6a717568a96ae68c5e3R17-R20):

> Compiling for this target requires `avr-gcc`, because a couple of intrinsics  (like 32-bit multiplication) rely on [`libgcc`](https://github.com/gcc-mirror/gcc/blob/3269a722b7a03613e9c4e2862bc5088c4a17cc11/libgcc/config/avr/lib1funcs.S) and can't be provided through `compiler-builtins` yet; this is a limitation that we hope to lift in the future, see https://github.com/rust-lang/compiler-builtins/issues/711.

I called the fact, that one should use `avr-gcc` as the linker (for special calling conventions and `libgcc`), as "suggested tool-flow". Note, that the test itself neither calls special functions nor links to `libgcc` in any way (thanks to no arithmetic or similar being used at runtime), so this should not matter and `ldd` might be a viable option.

**Comment by jieyouxu** [comment]
> 1. when trying to perform linking (the more correct approach), the CI job fails due to the linker being missing. AVR is kinda special here, because (presumably) it's the only target relying on the GCC as its linker. Is there a sane work around this for the test?
> 2. when not performing linking (by only building an `rlib`), the labe does not get resolved in CI (but on my machine?!), causing the `rjmp` to have an offset of 0, which renders the test unusable.
> 
> I could force `-Clinker=lld`, which (locally) works, but I don't know, if diverging from the suggested tool-flow in tests is good practice. Has anyone an idea?

... I mean, kinda, if you add a linker detection directive in compiletest that conditionally runs the test if `avr-gcc` is available. However, that means this test will never get exercised in CI because AFAIK the only avr target we have is exactly the one proposed in the PR you linked, which is Tier 3, and we don't test tier 3 targets in CI.

And if we're not testing the "standard" recommended linker, it won't reflect the actual avr environment that users usually have, right?

If this test never gets exercised by CI, then it seems questionable to add it in the first place.

**Comment by jfrimmel** [comment]
Thank you for your feedback! Based on that I propose: we add the test with `lld` as the linker. While not the de-facto standard linker for that target, it clearly shows the behavior. Since no `libgcc` needs to be linked in, this will work for this test. It is good to have this test, so that we prevent having a compiler producing unsound code in the future.

**Review by jieyouxu — APPROVED** [review]
This seems like a reasonable compromise to me. I'll r+ when PR CI is green. Thanks.

**Comment by jieyouxu** [comment]
Ah you'll need to add a `#![allow(internal_features)]`

**Comment by jfrimmel** [comment]
Sorry for the noise, somehow plain `lld` works locally (with downloaded CI LLVM), but not in CI. I've tried to use the absolute path like the other tools (e.g. `llvm_objdump()`), but this didn't work as well. The newest code tries `rust-lld`, which also works locally, let's see...

**Comment by jieyouxu** [comment]
> I can add this line, but this seems like there is no rust-lld available in CI, hence this test (and others) will never be executed. Am I missing something?

I believe rust-lld is an alias to lld, but it should be available under *some* CI configurations.

**Comment by jfrimmel** [comment]
Thany very much for your support!
I've included the aforementioned directive, so it should be good to go (altough the PR CI won't run the test, therefore it might fail in rollup).

Again: Thank you!

**Comment by jieyouxu** [comment]
I don't see why this won't run in at least one CI, but maybe T-infra will tell me a few months later 😆 Anyway
@bors r+

**Comment by jieyouxu** [comment]
@jfrimmel hi, this test seems to have spuriously failed in https://github.com/rust-lang/rust/pull/131527#issuecomment-2439511330 with a heap corruption... does that look genunine to you?

**Comment by jieyouxu** [comment]
```
---- [run-make] tests\run-make\avr-rjmp-offset stdout ----

error: rmake recipe failed to complete
status: exit code: 1
command: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\test\\run-make\\avr-rjmp-offset\\rmake.exe"
--- stderr -------------------------------
command failed at line 29
command failed at line 29
Command { cmd: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\stage2\\bin\\rustc.exe" "-L" "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\test\\run-make\\avr-rjmp-offset\\rmake_out" "avr-rjmp-offsets.rs" "-Copt-level=s" "-Cpanic=abort" "--target=avr-unknown-gnu-atmega328" "-Clinker=rust-lld" "-Clink-arg=--entry=main" "-o" "compiled", stdin_buf: None, stdin: None, stdout: None, stderr: None, drop_bomb: DropBomb { command: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\stage2\\bin\\rustc.exe", defused: true, armed_location: Location { file: "C:\\a\\rust\\rust\\tests\\run-make\\avr-rjmp-offset\\rmake.rs", line: 16, col: 5 } }, already_executed: true }
output status: `exit code: 1`
=== STDOUT ===


=== STDERR ===
error: linking with `rust-lld` failed: exit code: 0xc0000374
error: linking with `rust-lld` failed: exit code: 0xc0000374
  |
  = note: "rust-lld" "-flavor" "gnu" "C:\\a\\_temp\\msys64\\tmp\\rustc4vG81h\\symbols.o" "compiled.avr_rjmp_offsets.ab053966543a1f9f-cgu.0.rcgu.o" "--as-needed" "-Bdynamic" "-z" "noexecstack" "-L" "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-gnu\\test\\run-make\\avr-rjmp-offset\\rmake_out" "-o" "compiled" "--gc-sections" "--entry=main"

error: aborting due to 1 previous error
------------------------------------------
```

**Comment by jfrimmel** [comment]
> @jfrimmel hi, this test seems to have spuriously failed in [#131527 (comment)](https://github.com/rust-lang/rust/pull/131527#issuecomment-2439511330) with a heap corruption... does that look genunine to you?

Puh, I don't thibk, this is really actionable by me. I don't have the CI environment here to try to reproduce it and the linked issue looks like this is spurious behavior. Of course, the underlying issue is not introduced by this PR but rather "just" unveiled.
If necessary, I can disable the test on Windows platforms, but this would only hide the issue (but would lead to potentially less spurious fails in unrelated PRs). If I should do so, feel free to request it.

**Comment by jieyouxu** [comment]
Yeah mb, I don't think it's the test itself, it looks like an underlying bug with rust-lld.

**Comment by ehuss** [comment]
This test seems to be failing somewhat often:

* 2024-11-25 Hang: https://github.com/rust-lang/rust/pull/133465#issuecomment-2499233485
* 2024-11-20 Error: https://github.com/rust-lang/rust/pull/132629#issuecomment-2490054965
* 2024-11-13 Error: https://github.com/rust-lang/rust/pull/132997
* 2024-11-08 Error: https://github.com/rust-lang/rust/pull/132757#issuecomment-2465793359
* 2024-10-26 Error: https://github.com/rust-lang/rust/pull/131527#issuecomment-2439511330
* 2024-10-23 Error: https://github.com/rust-lang/rust/pull/123550#issuecomment-2434164699

All on x86_64-mingw.

Can we maybe disable it on x86_64-mingw until it is fixed?

**Comment by jieyouxu** [comment]
I think the linker is crashing... Yeah let's disable it for x86-64-mingw.
