### PR TITLE
Suggest deriving traits if possible

### LINKED ISSUE #85851: Suggest missing Debug Impl when unwrapping
Hey all, here's another common pitfall our new Rust learners stumble into during our training. The diagnostics you get on `unwrap` when the `E: Debug` bound isn't met do tell you that it isn't possible, BUT it doesn't tell you how to fix this. I think in most cases, suggesting `#[derive(Debug)]` is a better option, though this might give false positives if the user doesn't control the Error type (I don't know if diagnostics can "see" whether a type is local or not, but maybe you can!)

Given the following code: [Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=290a3491a7e176d702a1ce51811a3f7d)

```rust
enum MyError {
    Oops,
    No,
    DebugImpl,
}

fn main() {
    let x: Result<(), MyError> = Ok(());
    let y = x.unwrap();
}
```

The current output is:

```
error[E0599]: the method `unwrap` exists for enum `Result<(), MyError>`, but its trait bounds were not satisfied
 --> src/main.rs:9:15
  |
1 | enum MyError {
  | ------------ doesn't satisfy `MyError: Debug`
...
9 |     let y = x.unwrap();
  |               ^^^^^^ method cannot be called on `Result<(), MyError>` due to unsatisfied trait bounds
  |
  = note: the following trait bounds were not satisfied:
          `MyError: Debug`

error: aborting due to previous error
```

I would hope for something that tells users more directly "When you use `unwrap()`, the `Err` variant must implement the `Debug` trait in case the unwrap fails and we need to display a panic message".

```
error[E0599]: the method `unwrap` exists for enum `Result<(), MyError>`, but its trait bounds were not satisfied
 --> src/main.rs:9:15
  |
1 | enum MyError {
  | ------------ doesn't satisfy `MyError: Debug`
...
9 |     let y = x.unwrap();
  |               ^^^^^^ method cannot be called on `Result<(), MyError>` due to unsatisfied trait bounds
  |
  = note: the following trait bounds were not satisfied:
          `MyError: Debug`
  = help: try implementing the `Debug` trait on `MyError`. When you use `unwrap()`, the `Err(MyError)`
          variant must implement the `Debug` trait in order to display a panic message if the unwrap fails

  | #[derive(Debug)]
  | ^^^^^^^^^^^^^^^^ add a derive Debug here
1 | enum MyError {
  | 

error: aborting due to previous error
```

Applies to Rust 1.51.1, and likely all other older versions of Rust.

### PR DESCRIPTION
**Pull request by ptrojahn**
This only applies to builtin derives as I don't think there is a
clean way to get the available derives in typeck.

Closes #85851

### CODE REVIEW

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -833,6 +833,72 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         err.note(&format!(
                             "the following trait bounds were not satisfied:\n{bound_list}"
                         ));
+
+                        let derivables = [
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:837]: Can we move the new block of code to a separate method?

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 2]
```diff
@@ -833,6 +833,72 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                            return derivables.iter().find_map(|trait_derivable| {
+                                                if let Some(item_def_id) =
+                                                    diagnostic_items.get(trait_derivable)
+                                                {
+                                                    if item_def_id == &trait_ref.def_id
+                                                        && !(adt_def.is_enum()
+                                                            && *trait_derivable == sym::Default)
+                                                    {
+                                                        return Some((
+                                                            format!("{}", self_ty),
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:869]: It'd be nice if we included here `self.tcx.def_span(adt_def.did)` so that instead of just text we provided a structured suggestion.

**Review by estebank — COMMENTED** [review]
Sorry for the delay, I had the review in pending and never "finished" the review.

I have some nitpicks. Do you think you could deal with them?

**Comment by ptrojahn** [comment]
Thanks for the great suggestions!

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 3]
```diff
@@ -975,6 +977,76 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                            format!("{}", trait_ref.print_only_trait_path()),
+                                        ));
+                                    }
+                                }
+                                None
+                            });
+                        }
+                    }
+                }
+                None
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1023]: This has quite a bit of rightwards drift. Could we instead use `let x = if let ... else { return; }` to early return the closure and make the contents look more linear?

**Review by estebank — COMMENTED** [review]
You will need to rebase on top of a recent master. I also left a nitpick.

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 3 above)
Comment (ptrojahn) [reply compiler/rustc_typeck/src/check/method/suggest.rs]: Like this?
