### PR TITLE
Wrapper for `-Z gcc-ld=lld` to invoke rust-lld with the correct flavor

### LINKED ISSUE #88869: Doublicated ld\ld64 executables added into rustc package, increasing it's size
Checked that on `x86_64-pc-windows-msvc` target,
found duplicates in versions:
```
rustc 1.56.0-beta.1 (e784c962e 2021-09-07)
rustc 1.57.0-nightly (b69fe5726 2021-09-10)
```
and no duplicates in stable `rustc 1.55.0 (c8dfcfe04 2021-09-06)`, `rustc 1.56.0-nightly (4e282795d 2021-07-31)`
(bisecting is kinda slow on my connection)

@rustbot label +regression-from-stable-to-beta

### PR DESCRIPTION
**Pull request by hkratz**
This PR adds an `lld-wrapper` tool which is installed as `ld` and `ld64` in `lib\rustlib\<host_target>\bin\gcc-ld` directory and whose sole purpose is to invoke `rust-lld` in the parent directory with the correct flavor. Lld decides which flavor to use from either the first two commandline arguments or from the name of the executable (`ld` for GNU/ld flavor, `ld64` for Darwin/Macos/ld64 flavor and so on). Symbolic links could not be used as they are not supported by rustup and on Windows.

The wrapper replaces full copies of rust-lld which added some significant bloat. On UNIXish operating systems it exec rust-lld, on Windows it spawns it as a child process.

Fixes #88869.

r? @Mark-Simulacrum
cc @nagisa @petrochenkov @1000teslas

### CODE REVIEW

**Comment by nagisa** [comment]
Out of curiosity, what's the size of this wrapper?

**Comment by hkratz** [comment]
> Out of curiosity, what's the size of this wrapper?

On Linux the wrapper is 548kb, on Macos 424kb, haven't checked Windows yet. 

The rust-lld distributed with the current bootstrap compiler is only about 6.5mb on Linux with libLLVM-13.so linked in dynamically. On Macos rust-lld as distributed with the current bootstrap compiler does apparently not link to the llvm library dynamically and weighs in at about 73mb, haven't checked if that is on purpose.

**Comment by est31** [comment]
I wonder if it can be reduced further with https://github.com/johnthagen/min-sized-rust or so.

File: src/bootstrap/tool.rs [hunk 1]
```diff
@@ -664,6 +664,44 @@ impl Step for Cargo {
...
+        });
+    }
+
+    fn run(self, builder: &Builder<'_>) -> PathBuf {
+        let src_exe = builder
+            .ensure(ToolBuild {
+                compiler: self.compiler,
+                target: self.target,
+                tool: "lld-wrapper",
+                mode: Mode::ToolRustc,
```
Comment (Mark-Simulacrum) [inline src/bootstrap/tool.rs:693]: ToolBootstrap should suffice here, I'd hope.

File: src/tools/lld-wrapper/src/main.rs [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    if cfg!(unix) {
+        use std::os::unix::prelude::CommandExt;
+        Result::<(), _>::Err(command.exec()).unwrap_or_exit_with("could not exec rust-lld");
+        unreachable!("lld-wrapper: after exec without error");
+    } else {
+        // Windows has no exec(), spawn a child process and wait for it
+        let mut child =
+            command.spawn().unwrap_or_exit_with("could not spawn rust-lld child process");
+        let exit_status =
+            child.wait().unwrap_or_exit_with("error waiting for rust-lld child process to finish");
```
Comment (Mark-Simulacrum) [inline src/tools/lld-wrapper/src/main.rs:123]: Why are we using spawn().wait() instead of just .status() on Command directly?

File: src/tools/lld-wrapper/src/main.rs [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+//!
+//! lld supports multiple command line interfaces. If `-flavor <flavor>` are passed as the first
+//! two arguments the `<flavor>` command line interface is used to process the remaining arguments.
+//! If no `-flavor` argument is present the flavor is determined by the executable name.
+//!
+//! In Rust with `-Z gcc-ld=lld` we have gcc or clang invoke rust-lld. Since there is no way to
+//! make gcc/clang pass `-flavor <flavor>` as the first two arguments in the linker invocation
+//! and since Windows does not support symbolic links for files this wrapper is used in place of a
+//! symblic link. It execs `../rust-lld -flavor ld` if its name is `ld` and `../rust-lld -flavor ld64`
+//! if it is named `ld64`. On Windows it spawns a `..\rust-lld.exe` child process.
```
Comment (Mark-Simulacrum) [inline src/tools/lld-wrapper/src/main.rs:11]: Instead of trying to use the name of the executable to detect this, can we just build it twice (e.g., with a cargo feature for each variant)? It seems like that would both be simpler and easier to understand.

**Comment by tschuett** [comment]
Could this be a Python script instead to save space?

**Comment by est31** [comment]
@tschuett then it'd require python to be installed on the system. Same goes for bash scripts. I wonder though whether one could build something smaller, like something with no_std that just calls execve on unixes and whatever windows has on windows. Half a megabyte is definitely a lot for a binary whose main job is to just call another binary.

File: src/bootstrap/tool.rs (hunk 1 above)
Comment (hkratz) [reply src/bootstrap/tool.rs]: Seems like it.

File: src/tools/lld-wrapper/src/main.rs (hunk 3 above)
Comment (hkratz) [reply src/tools/lld-wrapper/src/main.rs]: Indeed.

**Comment by Kobzol** [comment]
FWIW, just out of curiosity, I tried to build it with

```toml
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
```
and `build-std` (`cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release --features ld`).

On Linux, it got the executable size after stripping from ~250 KiB to 50 KiB.

**Comment by est31** [comment]
Stripping is probably non trivial but one could probably add `debug = false` to the profile.

**Comment by Kobzol** [comment]
I probably measured it wrong before, even without stripping it sits at 75 KiB (`debug = false` doesn't change anything, I suppose that it's the default value in release?).

**Comment by hkratz** [comment]
Tried the minimization on Windows, the binary went from 600kb to 300kb.

The installed size of the x86_64 Windows toolchains are:
```
$ du -sm .rustup/toolchains/*
1056    .rustup/toolchains/beta-x86_64-pc-windows-msvc
1083    .rustup/toolchains/nightly-x86_64-pc-windows-msvc
961     .rustup/toolchains/stable-x86_64-pc-windows-msvc
```
So while reduces the ld.exe + ld64.exe overhead from 120mb to 600kb has an impact, further reducing it from 600kb to 300kb or less is not really worth the build time increase of `-Z build-std` IMHO.

**Comment by Kobzol** [comment]
It might be a bit overkill, I agree.

Although, on Linux at least, `strip`ping the binary should be trivial, and could be done on a "best effort" basis (if `strip` is not available, just don't strip it).

**Comment by hkratz** [comment]
@Mark-Simulacrum If I use `ToolBootstrap` I have to always use the bootstrap compiler otherwise it asserts. Isn't that a problem when cross-compiling? I will do some testing with cross-compilation.

**Comment by Mark-Simulacrum** [comment]
I don't think we need to bother with trying to get these down to even smaller sizes; several hundred kilobytes is tiny compared to the rest of the rustc tarball, and so cutting that even a little ultimately doesn't matter that much IMO.

> @Mark-Simulacrum If I use ToolBootstrap I have to always use the bootstrap compiler otherwise it asserts. Isn't that a problem when cross-compiling? I will do some testing with cross-compilation.

I'm not sure I follow. Can you say what assertion you're seeing? The bootstrap compiler should be capable of cross-compiling to ~any architecture (unless it's been added within the last release cycle, but I don't think we need to worry about that -- targets don't jump to having host tools from the get go). You might need a `builder.ensure(compile::Std { compiler, target });` though.

**Comment by hkratz** [comment]
It only panics if the wrapper is built a ToolBootstrap with a stage 1 compiler. That is probably to be expected:
```
thread 'main' panicked at 'assertion failed: !use_snapshot || stage == 0 || self.local_rebuild', src/bootstrap/builder.rs:1077:9
s
```
With the latest commit it always uses the bootstrap compiler so the panic is gone. If using the bootstrap compiler is fine for cross-compiling the PR is ready for re-review.

**Comment by Mark-Simulacrum** [comment]
Yes, that's expected, but shouldn't happen with the latest changes as you indicated :)

OK, great, then I think we can likely go ahead with this. I'm not sure that current_exe() will work in all cases -- I know we've had problems with it in the past -- but I also don't see an easy alternative, so it seems OK for now. We can always iterate on this in the future.

Can you squash the commits? r=me with that done.

**Comment by tschuett** [comment]
You can't have `cc` pass `-flavor darwin` to the linker (rust-lld)?

**Comment by hkratz** [comment]
> You can't have `cc` pass `-flavor darwin` to the linker (rust-lld)?

With either `-Wl,<option>` or `-Xlinker <option>` clang adds `<option>` after other options. lld requires them to be the first two arguments.

**Comment by hkratz** [comment]
@Mark-Simulacrum Squashed. 

Is it too late to consider it for the beta?

**Comment by Mark-Simulacrum** [comment]
Yes, we don't generally backport anything except regression fixes (which this isn't, as it targets an unstable feature).

@bors r+

**Comment by hkratz** [comment]
@Mark-Simulacrum I think I was a bit unclear. The installed size increase of >100MB from stable to beta on Windows/Macos affects everyone and not just users of the unstable feature. That is why #88869 is marked as `regression-from-stable-to-beta` with medium priority. 

The risk of a backport is low as even if the wrapper has bugs it would not affect people using beta/stable.

**Comment by Mark-Simulacrum** [comment]
Ah, I see. I think a backport makes sense then. Thanks!

**Comment by Manishearth** [comment]
@bors r-

seems like this failed https://github.com/rust-lang/rust/pull/89540

File: src/bootstrap/compile.rs [hunk 4]
```diff
@@ -1136,14 +1136,15 @@ impl Step for Assemble {
...
-            builder.copy(
-                &lld_install.join("bin").join(&src_exe),
-                &gcc_ld_dir.join(exe("ld64", target_compiler.host)),
-            );
+            let bootstrap_compiler = builder.compiler(0, builder.config.build);
+            for flavor in ["ld", "ld64"] {
+                let lld_wrapper_exe = builder.ensure(crate::tool::LldWrapper {
+                    compiler: bootstrap_compiler,
+                    target: target_compiler.host,
+                    flavor_feature: flavor,
```
Comment (ehuss) [inline src/bootstrap/compile.rs:1144]: I don't think this will work when doing a cross-compilation.  The stage0 compiler does not have a `std` for the target platform.  

I think fixing this will be quite tricky, since you can't build tools here because that would result in a cyclic dependency (assemble > tool > assemble).   I'm wondering if maybe building the lld wrapper could be pushed to dist::Rustc?  IIRC, lld isn't actually used for building, it is only generated as an artifact for dist.

File: src/bootstrap/tool.rs [hunk 5]
```diff
@@ -664,6 +664,38 @@ impl Step for Cargo {
...
+        run.never()
+    }
+
+    fn run(self, builder: &Builder<'_>) -> PathBuf {
+        let src_exe = builder
+            .ensure(ToolBuild {
+                compiler: self.compiler,
+                target: self.target,
+                tool: "lld-wrapper",
+                mode: Mode::ToolBootstrap,
```
Comment (ehuss) [inline src/bootstrap/tool.rs:687]: I think this will also need to change, since this isn't a bootstrap tool.

```suggestion
                mode: Mode::ToolRustc,
```

File: src/bootstrap/compile.rs (hunk 4 above)
Comment (bjorn3) [reply src/bootstrap/compile.rs:1144]: > IIRC, lld isn't actually used for building, it is only generated as an artifact for dist.

It makes sense to me to change that in the future to allow for faster rustc compilation. Maybe push it to `build::Rustc` or even add it as extra binaries produced by the `rustc-binary` crate next to `rustc`?

Comment (hkratz) [reply src/bootstrap/compile.rs]: As far as I can see the target std is already built for the stage1 (cross) compiler at this point so using the (target stage - 1) `build_compiler` there should just work(tm).

Comment (ehuss) [reply src/bootstrap/compile.rs]: 👍  Yea, that should work.  It looks like it builds an extra copy for the *build* compiler, which isn't strictly necessary, but it only takes about a second to build and shouldn't be a problem.

**Comment by hkratz** [comment]
I have tested it again after my change with:
* `DEPLOY=1 ./src/ci/docker/run.sh dist-x86_64-freebsd` ✔️
* `DEPLOY=1 ./src/ci/docker/run.sh x86_64-gnu` ✔️
* `DEPLOY=1 ./src/ci/docker/run.sh dist-x86_64-linux` ✔️

@rustbot label  -S-waiting-on-author +S-waiting-on-review

**Comment by petrochenkov** [comment]
I missed this PR and only noticed the lld-wrapper tool later.

I strongly suspect that separate tool is an unproportionately large hammer and not the best solution, so I made https://github.com/rust-lang/rust/issues/97352.
