### PR TITLE
Limit the size of cgu names when using the `-Zhuman-readable-cgu-name…

### LINKED ISSUE #141547: -Zhuman-readable-cgu-names generates filenames that exceed the character limit on windows
I ran into this error while trying to determine which crates were contributing to bloated rlib sizes:

    error: could not write output to D:\Projects\platformed\rust\target\debug\deps\platformed.http.f916976a8c6a0cf4-in-platformed.f916976a8c6a0cf4-response.volatile--tracing_subscriber.f916976a8c6a0cf4-in-platformed.f916976a8c6a0cf4-registry-sharded--tracing_subscriber.f916976a8c6a0cf4-in-platformed.f916976a8c6a0cf4-registry-stack.0bt72is.rcgu.o: invalid argument

The filename is conspicuously just over 255/260 characters long which are limits on windows for filenames.

### PR DESCRIPTION
**Pull request by Diggsey**
…s` option

Prior to this change, cgu names could be generated which would result in filenames longer than the limit imposed by the OS.

Fixes rust-lang/rust#141547

### CODE REVIEW

File: compiler/rustc_middle/src/mir/mono.rs [hunk 1]
```diff
@@ -468,6 +469,20 @@ impl<'tcx> CodegenUnit<'tcx> {
         hash.as_u128().to_base_fixed_len(CASE_INSENSITIVE)
     }
 
+    pub fn shorten_name(human_readable_name: &str) -> Cow<'_, str> {
+        // Set a limit a somewhat below the common platform limits for file names.
+        const MAX_CGU_NAME_LENGTH: usize = 200;
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/mir/mono.rs:474]: Is this something we can query from the OS?

File: compiler/rustc_middle/src/mir/mono.rs [hunk 2]
```diff
@@ -468,6 +469,20 @@ impl<'tcx> CodegenUnit<'tcx> {
...
+        if human_readable_name.len() > MAX_CGU_NAME_LENGTH {
+            let mangled_name = Self::mangle_name(human_readable_name);
+            let truncate_to = human_readable_name
+                .floor_char_boundary(MAX_CGU_NAME_LENGTH - mangled_name.len() - 1);
+            format!("{}-{}", &human_readable_name[..truncate_to], mangled_name).into()
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/mir/mono.rs:479]: I fear that this can result in CGU collisions, right?

File: compiler/rustc_middle/src/mir/mono.rs
Comment (fmease) [inline compiler/rustc_middle/src/mir/mono.rs:1]: I'm not a Windows dev but wouldn't it make sense to "just" use extended-length paths (whose limit is 32,767) whose prefix is `\\?\`. [Docs](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)

Comment (wesleywiser) [reply compiler/rustc_middle/src/mir/mono.rs:1]: Extended paths seem like the better solution to me as well since that means the logic to name the file will be the same regardless of platform.

File: compiler/rustc_middle/src/mir/mono.rs (hunk 1 above)
Comment (Diggsey) [reply compiler/rustc_middle/src/mir/mono.rs:474]: This needs to be less than the actual filename limit, since the extension and other bits are added later.

Comment (ChrisDenton) [reply compiler/rustc_middle/src/mir/mono.rs:474]: Browsing the limits it looks like 255 is by far the most common amongst filesystems https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

File: compiler/rustc_middle/src/mir/mono.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Diggsey) [reply compiler/rustc_middle/src/mir/mono.rs]: I've updated the PR to add an indicator when the filename was truncated.
