### PR TITLE
Tail call diagnostics to include lifetime info

### LINKED ISSUE #144957: tail call diagnostics omit lifetimes
### Code

```Rust
#![feature(explicit_tail_calls)]
#![allow(incomplete_features)]

fn foo<'a>(_: fn(&'a ())) {
    become bar(dummy);
}

fn bar(_: fn(&())) {}

fn dummy(_: &()) {}

fn main() {}
```

### Current output

```Shell
error: mismatched signatures
 --> src/main.rs:5:5
  |
5 |     become bar(dummy);
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `become` requires caller and callee to have matching signatures
  = note: caller signature: `fn(fn(&()))`
  = note: callee signature: `fn(for<'a> fn(&'a ()))`
```

### Desired output

```Shell
error: mismatched signatures
 --> src/main.rs:5:5
  |
5 |     become bar(dummy);
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `become` requires caller and callee to have matching signatures
  = note: caller signature: `fn(fn(&'a ()))`
  = note: callee signature: `fn(for<'a> fn(&'a ()))`
```

### Rust Version

```Shell
1.91.0-nightly (2025-08-04 0060d5a2a8a86a31f629)
```

### PR DESCRIPTION
**Pull request by Kivooeo**
Fixes https://github.com/rust-lang/rust/issues/144957

r? @WaffleLapkin @compiler-errors

### CODE REVIEW

File: tests/ui/explicit-tail-calls/caller-lifetime-presence.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+//! Once upon a time, the compiler decided lifetimes weren’t important enough to show in diagnostics
+//! That decision did not go well. This test ensures we don’t repeat that mistake.
+//!
+//! Specifically: we’re checking that the `become` call produces an error
+//! **with** lifetimes preserved
+//! in both caller and callee signatures. Otherwise, good luck figuring out what went wrong.
+//!
+//! If this test fails:
+//! - Either lifetimes are being omitted from the diagnostic again (bad, fix it),
+//! - Or the message format changed (okay, update the test).
```
Comment (compiler-errors) [inline tests/ui/explicit-tail-calls/caller-lifetime-presence.rs]: This description is really verbose imo. It could probably be rewritten as a single line.

File: compiler/rustc_mir_build/src/check_tail_calls.rs [hunk 2]
```diff
@@ -132,7 +132,11 @@ impl<'tcx> TailCallCkVisitor<'_, 'tcx> {
 
         if caller_sig.inputs_and_output != callee_sig.inputs_and_output {
             if caller_sig.inputs() != callee_sig.inputs() {
-                self.report_arguments_mismatch(expr.span, caller_sig, callee_sig);
+                self.report_arguments_mismatch(
+                    expr.span,
+                    self.caller_ty.fn_sig(self.tcx).skip_binder(),
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/check_tail_calls.rs]:
```suggestion
                    self.caller_ty.fn_sig(self.tcx).instantiate_identity(),
```

**Review by compiler-errors — CHANGES_REQUESTED** [review]
This doesn't fix the issue in the other direction, like:

```
fn foo(_: fn(&())) {
    become bar(dummy);
}

fn bar<'a>(_: fn(&'a ())) {}

fn dummy(_: &()) {}
```

File: tests/ui/explicit-tail-calls/caller-lifetime-presence.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/explicit-tail-calls/caller-lifetime-presence.rs]:
```
// This test makes sure that we are giving a meaningful signature mismatch error when arguments disagree on late-bound lifetimes.
```

File: compiler/rustc_mir_build/src/check_tail_calls.rs (hunk 2 above)
Comment (Kivooeo) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: It does not work for me

```rust
error[E0599]: no method named `instantiate_identity` found for struct `Binder` in the current scope
   --> compiler/rustc_mir_build/src/check_tail_calls.rs:137:53
    |
137 |                     self.caller_ty.fn_sig(self.tcx).instantiate_identity(),
    |                                                     ^^^^^^^^^^^^^^^^^^^^ method not found in `Binder<TyCtxt<'_>, FnSig<TyCtxt<'_>>>`
```

**Comment by Kivooeo** [comment]
I fixed other direction, and make test description lesser (not want to shrink it to one liner tho)

If we have a better way to do so, I'm open for suggestions because it's literally first time me opening anything related to tail call

File: compiler/rustc_mir_build/src/check_tail_calls.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: oh, it's a binder, not an early binder. that should be liberated then probably, use `tcx.liberate_late_bound_regions` instead.

**Comment by compiler-errors** [comment]
You should probably check if this also mentions regions like `'static` since those may show up in the signature.

File: compiler/rustc_mir_build/src/check_tail_calls.rs (hunk 2 above)
Comment (Kivooeo) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: I'd love to hear why current approach is not best just to learn things

Also about `'static` yes it shows, should I include this in test?

```rust
4 |     become bar(dummy);
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: -Ztrack-diagnostics: created at compiler/rustc_mir_build/src/check_tail_calls.rs:368:14
  = note: `become` requires caller and callee to have matching signatures
  = note: caller signature: `fn(for<'a> fn(&'a ()))`
  = note: callee signature: `fn(fn(&'static ()))`
```

Comment (Kivooeo) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: I did `tcx.liberate_late_bound_regions` it works but I did not found a better way to obtain `DefId` rather than do this 

Update `TailCallCkVisitor` with adding a field that will contain def id

```rust
struct TailCallCkVisitor<'a, 'tcx> {
    ... // existed fields
    def: DefId,
}
```

And create it like this

```rust
    let mut visitor = TailCallCkVisitor {
        ... // eixsted fields
        def: def.to_def_id(),
    };
```

This might be a bad solution to pass `DefId` like this?

```rust
    self.report_arguments_mismatch(
        expr.span,
        self.tcx.liberate_late_bound_regions(self.def, self.caller_ty.fn_sig(self.tcx)),
        self.tcx.liberate_late_bound_regions(self.def, ty.fn_sig(self.tcx)),
    );
```

Comment (Kivooeo) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: Hey @compiler-errors, when you have a moment, could you take another look and let me know which approach you think works better?

**Comment by WaffleLapkin** [comment]
r? compiler-errors

File: compiler/rustc_mir_build/src/check_tail_calls.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: It doesn't actually matter what def id you pass. Can you just pass `CRATE_DEF_ID` for now?

Comment (Kivooeo) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: yeah, `CRATE_DEF_ID` works, didn't knew about this one

**Review by compiler-errors — APPROVED** [review]
