### PR TITLE
Treat generators as if they have an arbitrary destructor

### LINKED ISSUE #49918: [NLL] Dropck is too permissive for generators
Code shows a case where `y` doesn't stay borrowed for long enough allowing it to be mutated while a reference to it exists. I think treating generators as if they implement `Drop` would fix this, but I'm not sure if this will end up causing incorrect errors in other places.

```rust
#![feature(nll)]
#![feature(generators, generator_trait)]

use std::ops::{GeneratorState, Generator};

struct SetToNone<'a: 'b, 'b>(&'b mut Option<&'a i32>);

impl<'a, 'b> Drop for SetToNone<'a, 'b> {
    fn drop(&mut self) {
        *self.0 = None;
    }
}

fn drop_using_generator() -> i32 {
    let mut y = Some(&0);
    let z = &mut y;
    let r;
    {
        let mut g = move || { let _s = SetToNone(z); yield; };
        unsafe { g.resume() }; // documented as unsafe only because of unmovable closures.
        r = y.as_ref().unwrap();
    } // y is set to 'null' here
    **r // Segmentation fault
}

fn main() {
    println!("{}", drop_using_generator());
}
```

### PR DESCRIPTION
**Pull request by pnkfelix**
Conservatively assume dropping a generator touches its upvars, via locals' destructors.

Fix #49918

### CODE REVIEW

**Comment by pnkfelix** [comment]
(as noted in the comments in code, in principle we could do something smarter here, in terms of recursively analyzing the locals of the generator to see if we can prove that none of them have destructors. But that is complex and this is simple.)

**Comment by Zoxc** [comment]
This looks correct to me. We model generators as a struct of their upvars with a destructor which may access these upvars. The `ui/generator/dropck.rs` needs to be updated, and it would also like to see which errors it produces in this PR with NLL enabled.

I'd like someone who knows how dropck works to glance over it though. I'm just going to assume Niko is such a person.

r? @nikomatsakis

File: src/librustc_traits/dropck_outlives.rs [hunk 1]
```diff
@@ -193,14 +193,36 @@ fn dtorck_constraint_for_ty<'a, 'gcx, 'tcx>(
             .map(|ty| dtorck_constraint_for_ty(tcx, span, for_ty, depth + 1, ty))
             .collect(),
 
-        ty::TyGenerator(def_id, substs, _) => {
-            // Note that the interior types are ignored here.
-            // Any type reachable inside the interior must also be reachable
-            // through the upvars.
```
Comment (Zoxc) [inline src/librustc_traits/dropck_outlives.rs]: This comment should be kept in some form. It serves as justification for why we can get away with only reporting the upvars instead of actually calculating all the types which may get dropped inside.

Comment (pnkfelix) [reply src/librustc_traits/dropck_outlives.rs]: (okay, addressed this in followup commit)

**Comment by pnkfelix** [comment]
I think the request to see what the output looks like under NLL will be satisfied by the eventual (hopefully soon) landing of PR #49900, so I won't put that change into this PR.

File: src/librustc_traits/dropck_outlives.rs [hunk 2]
```diff
@@ -209,6 +209,12 @@ fn dtorck_constraint_for_ty<'a, 'gcx, 'tcx>(
             // traversed in such a manner. So instead, we will
             // simplify things for now by treating all generators as
             // if they were like ADT's with drop implementations.
+            //
+            // In particular, skipping over `_interior` is safe
+            // because any side-effects from dropping `_interior` can
+            // only take place through references with lifetimes
+            // derived from lifetimes attached to the upvars, and we
+            // *do* traverse the uvpars here.
```
Comment (Zoxc) [inline src/librustc_traits/dropck_outlives.rs]: Typo, uv-pars. Looks good otherwise.

**Comment by Zoxc** [comment]
@pnkfelix I'd just like you to run the test locally with NLL and post the errors in a comment here.

**Comment by pnkfelix** [comment]
@Zoxc oh okay I can certainly do that.

**Comment by pnkfelix** [comment]
@Zoxc here is the current behavior on `ui/generator/dropck.rs` with this PR under both AST-borrowck and NLL-borrowck:

### AST-borrowck:

```
% ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc ../src/test/ui/generator/dropck.rs
error[E0597]: `*cell` does not live long enough
  --> ../src/test/ui/generator/dropck.rs:19:40
   |
19 |     let ref_ = Box::leak(Box::new(Some(cell.borrow_mut())));
   |                                        ^^^^ borrowed value does not live long enough
...
29 | }
   | - `*cell` dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created

error[E0597]: `ref_` does not live long enough
  --> ../src/test/ui/generator/dropck.rs:24:18
   |
22 |     gen = || {
   |           -- capture occurs here
23 |         // but the generator can use it to drop a `Ref<'a, i32>`.
24 |         let _d = ref_.take(); //~ ERROR `ref_` does not live long enough
   |                  ^^^^ borrowed value does not live long enough
...
29 | }
   | - borrowed value dropped before borrower
   |
   = note: values in a scope are dropped in the opposite order they are created

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0597`.
```

### NLL (`-Z borrowck=mir`):

```
% ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc ../src/test/ui/generator/dropck.rs -Z borrowck=mir

error[E0597]: `ref_` does not live long enough
  --> ../src/test/ui/generator/dropck.rs:22:11
   |
22 |       gen = || {
   |  ___________^
23 | |         // but the generator can use it to drop a `Ref<'a, i32>`.
24 | |         let _d = ref_.take(); //~ ERROR `ref_` does not live long enough
25 | |         yield;
26 | |     };
   | |_____^ borrowed value does not live long enough
...
29 |   }
   |   -
   |   |
   |   borrowed value only lives until here
   |   borrow later used here, when `gen` is dropped

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

**Comment by arielb1** [comment]
There's already a test for this at https://github.com/rust-lang/rust/blob/master/src/test/ui/generator/dropck.rs, that was commented out for some reason.

File: src/librustc_traits/dropck_outlives.rs [hunk 3]
```diff
@@ -193,14 +193,42 @@ fn dtorck_constraint_for_ty<'a, 'gcx, 'tcx>(
...
+            // In particular, skipping over `_interior` is safe
+            // because any side-effects from dropping `_interior` can
+            // only take place through references with lifetimes
+            // derived from lifetimes attached to the upvars, and we
+            // *do* traverse the upvars here.
+
+            let new_constraints: Vec<ty::subst::Kind<'tcx>> =
+                substs.upvar_tys(def_id, tcx).map(|t| t.into()).collect();
+
+            let mut constraint = substs
```
Comment (arielb1) [inline src/librustc_traits/dropck_outlives.rs]: > https://github.com/rust-lang/rust/pull/45337/files#r145093242
> It might be a better idea to treat generators like trait object and have them always be dtorck. If generators are "supposed to be" captured by an `impl Trait` or trait object, this shouldn't be a problem in practice..

There's no reason to have both `outlives` and dtorck constraints together.

Comment (nikomatsakis) [reply src/librustc_traits/dropck_outlives.rs]: Are you saying @arielb1 that we only need to invoke `constraint.outlives.extend(new_contraints)`, and not also include `dtorck_constraint_for_ty`?

**Review by nikomatsakis — COMMENTED** [review]
r=me with [arielb1's comment fixed](https://github.com/rust-lang/rust/pull/49943/files#r183219144)

File: src/librustc_traits/dropck_outlives.rs (hunk 3 above)
Comment (arielb1) [reply src/librustc_traits/dropck_outlives.rs]: Sure just return `new_constraints` as outlives constrains, same as trait objects.

**Comment by shepmaster** [comment]
Ping from triage, @pnkfelix ! Will you have time to address the review feedback in the near future?

**Comment by pnkfelix** [comment]
@shepmaster yep, I'll do it either today or tomorrow. (I was out on PTO last week.)
