### PR TITLE
suggestion for attempted integer identifier in patterns

### LINKED ISSUE #106552: Confusing error with integer identifers
I tried this code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d53daa961c3b462df261d1e774a9329f

```rust
fn main() {
    let 6 = 5;
}
```

I expected to see an error explaining the limits on identifiers (identifiers can't start with digits).

Instead, I got a pattern-matching error:
```
error[E0005]: refutable pattern in local binding: `i32::MIN..=5_i32` and `7_i32..=i32::MAX` not covered
 --> src/main.rs:4:5
  |
4 | let 6 = 5;
  |     ^ patterns `i32::MIN..=5_i32` and `7_i32..=i32::MAX` not covered
  |
  = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
  = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
  = note: the matched value is of type `i32`
help: you might want to use `if let` to ignore the variants that aren't matched
  |
4 | if let 6 = 5 { todo!() }
  | ++           ~~~~~~~~~~~
```
While of course this error is correct, perhaps a note should be added explaining that you can't use a number as an identifier.

### Meta
Occurs on latest stable and nightly.

@rustbot claim

### PR DESCRIPTION
**Pull request by Ezrashaw**
Fixes #106552 

Implemented a suggestion on `E0005` that occurs when no bindings are present and the pattern is a literal integer.

### CODE REVIEW

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 1]
```diff
@@ -494,8 +497,23 @@ impl<'p, 'tcx> MatchVisitor<'_, 'p, 'tcx> {
...
+                    if let PatKind::Lit(expr) = pat.kind {
+                        if let ExprKind::Lit(Spanned { node: LitKind::Int(_, _), span }) = expr.kind
+                        {
+                            err.span_suggestion_verbose(
+                                span.shrink_to_lo(),
+                                "alternatively, prepend the pattern with an underscore to define \
+                                      a variable; identifiers cannot start with digits",
+                                "_",
+                                Applicability::MaybeIncorrect,
+                            );
```
Comment (Mark-Simulacrum) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs:511]: Open to this, but it seems to me that I haven't really wanted to define an integer-named variable ~ever. Maybe instead of a help: text with `_int` we can just `note: ` that identifiers cannot start with digits? I think in 99% of cases they probably wanted to use if let or similar, so adding a second suggestion may be more confusing.

At least to me if I see two suggestions I think I'd think "which is better?" before thinking "oh, I wanted an if, the second one is irrelevant".

Comment (Ezrashaw) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:511]: Obviously this is somewhat targeted at new developers but, personally, I've never pattern matched on a integer literal before. I'd use a match statement instead which allows better handling of the default case, etc. FWIW, I think that if a user tries to do this (again, IMO very uncommon) then really meant to assign a value instead.

Also I think PR will need a rebase because of #106458.

**Comment by Ezrashaw** [comment]
@Mark-Simulacrum I've rebased (moved the tests), depending on your review comment, it's good to go.

File: issue-106552.rs [hunk 2]
```diff
@@ -0,0 +1,5 @@
+fn main() {
```
Comment (albertlarsan68) [inline issue-106552.rs:1]: This file should not be in the root.
You should delete, it is also in the tests/ directory.

**Review by albertlarsan68 — CHANGES_REQUESTED** [review]

File: issue-106552.rs (hunk 2 above)
Comment (Ezrashaw) [reply issue-106552.rs]: Whoops, don't know how that got there :confused:

File: tests/ui/pattern/issue-106552.stderr [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+LL |     let x @ 5 = 6;
+   |         ^^^^^ patterns `i32::MIN..=4_i32` and `6_i32..=i32::MAX` not covered
+   |
+   = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
+   = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
+   = note: the matched value is of type `i32`
+help: you might want to use `let else` to handle the variants that aren't matched
+   |
+LL |     let x @ 5 = 6 else { todo!() };
+   |                   ++++++++++++++++
```
Comment (estebank) [inline tests/ui/pattern/issue-106552.stderr:31]: Looking at this with fresh eyes, shouldn't we be suggesting `if let` here? 🤔

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 4]
```diff
@@ -426,10 +428,18 @@ impl<'p, 'tcx> MatchVisitor<'_, 'p, 'tcx> {
                 let end_span = semi_span.shrink_to_lo();
                 let count = witnesses.len();
 
+                // If the pattern to match is an integer literal, perhaps the user meant to create a binding instead.
+                let int_suggestion = if let PatKind::Lit(expr) = &pat.kind && bindings.is_empty() {
+                    if let ExprKind::Lit(Spanned { node: LitKind::Int(_, _), span }) = expr.kind
+                    {
+                        Some(MiscPatternSuggestion::AttemptedIntegerLiteral { start_span: span.shrink_to_lo() })
+                    } else { None }
+                } else { None };
```
Comment (estebank) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs:437]: You can use let chains here (which you're already leveraging on the first line) for reducing the number of branches in the code:

```suggestion
                let int_suggestion = if let PatKind::Lit(expr) = &pat.kind
                    && bindings.is_empty()
                    && let ExprKind::Lit(Spanned { node: LitKind::Int(_, _), span }) = expr.kind
                {
                        Some(MiscPatternSuggestion::AttemptedIntegerLiteral { start_span: span.shrink_to_lo() })
                } else {
                    None
                };
```

File: compiler/rustc_error_messages/locales/en-US/mir_build.ftl [hunk 5]
```diff
@@ -364,3 +364,5 @@ mir_build_suggest_let_else = you might want to use `let else` to handle the {$co
         [one] variant that isn't
         *[other] variants that aren't
     } matched
+
+mir_build_suggest_attempted_int_lit = alternatively, prepend the pattern with an underscore to define a variable; identifiers cannot begin with digits
```
Comment (estebank) [inline compiler/rustc_error_messages/locales/en-US/mir_build.ftl:368]:
```suggestion
mir_build_suggest_attempted_int_lit = alternatively, you could prepend the pattern with an underscore to define a new named variable; identifiers cannot begin with digits
```

**Comment by estebank** [comment]
r? @estebank 

r=me after addressing the nit picks

File: tests/ui/pattern/issue-106552.stderr (hunk 3 above)
Comment (Ezrashaw) [reply tests/ui/pattern/issue-106552.stderr:31]: Firstly, I haven't touched the `if let` and `else` suggestion code. My understanding is that this situation is a bit like an alternative if let. You can bind the value, and if it doesn't match, the else branch is called (which must diverge).

Comment (estebank) [reply tests/ui/pattern/issue-106552.stderr:31]: I'm not asking you to fix it now necessarily, just leaving a paper trail of my thinking so we don't forget to fix it in the future :)
