### PR TITLE
Overhaul MSVC linker and Windows SDK detection code

### LINKED ISSUE #30229: Windows 10 SDK detection broken with new SDK
The new Windows 10 SDK changed some registry values slightly which broke the current Windows 10 SDK detection code.

This results in the linker error `note: LINK : fatal error LNK1181: cannot open input file 'ws2_32.lib'`

I am working on a PR to ~~fix this~~ completely overhaul the code for the better.

In the meantime you can work around this issue by manually invoking vcvars as done [here](https://github.com/libpnet/libpnet/pull/135).

### PR DESCRIPTION
**Pull request by retep998**
What I've done here is try to make the code match what vcvars does much more closely. It now chooses which SDK to find based on the version of MSVC that it found. It also bases the decision of whether to find all the things on whether `VCINSTALLDIR` has been set, which is more likely to have only been set by an invocation of vcvars, unlike previously where it would do some things only if `LIB` wasn't set even though there was a valid use case for libraries to add themselves to `LIB` without having invoked vcvars.

There are still some debug `println!`s so people can test the PR and make sure it works correctly on various setups.

It supports VS 2015, 2013, and 2012. People who want to use versions of VS older (or newer) than that will have to manually invoke the appropriate vcvars bat file to set the proper environment variables themselves.

Do not merge yet.

Fixes https://github.com/rust-lang/rust/issues/30229

### CODE REVIEW

**Comment by retep998** [comment]
cc @vadimcn

**Comment by retep998** [comment]
Testing by @DanielKeep confirms that this also works with the standalone Microsoft Visual C++ Build Tools 2015 Technical Preview, providing an option for users that want to use msvc but without installing the entire VS IDE.

File: src/librustc_trans/back/msvc/mod.rs [hunk 1]
```diff
@@ -46,283 +46,179 @@ pub fn link_exe_cmd(sess: &Session) -> Command {
...
+        LOCAL_MACHINE.open(r"SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0".as_ref()).ok()
+        .and_then(|key| {
+            key.query_str("InstallationFolder").ok()
+        }).and_then(|root| {
+            fs::read_dir(Path::new(&root).join("Lib")).ok()
+        }).and_then(|readdir| {
+            let mut dirs: Vec<_> = readdir.filter_map(|dir| dir.ok())
+                .map(|dir| dir.path()).collect();
+            dirs.sort();
+            dirs.reverse();
```
Comment (alexcrichton) [inline src/librustc_trans/back/msvc/mod.rs]: Instead of `reverse` here you should also be able to do `dirs.into_iter().rev().filter(...)` below

File: src/librustc_trans/back/msvc/mod.rs [hunk 2]
```diff
@@ -46,283 +46,179 @@ pub fn link_exe_cmd(sess: &Session) -> Command {
...
         }
     }
-
-    fn ucrt_install_dir(vs_install_dir: &Path) -> Option<(PathBuf, String)> {
-        let is_vs_14 = vs_install_dir.iter().filter_map(|p| p.to_str()).any(|s| {
-            s == "Microsoft Visual Studio 14.0"
-        });
-        if !is_vs_14 {
-            return None
+    // VC's x86 libraries are not in a subfolder
```
Comment (alexcrichton) [inline src/librustc_trans/back/msvc/mod.rs]: Out of curiosity, what's VC?

File: src/librustc_trans/back/msvc/mod.rs [hunk 3]
```diff
@@ -46,283 +46,179 @@ pub fn link_exe_cmd(sess: &Session) -> Command {
...
+            "x86_64" => Some("amd64"),
+            "arm" => Some("amd64_arm"),
+            _ => None,
         }
     }
-
-    fn windows_sdk_v10_subdir(sess: &Session) -> Option<&'static str> {
-        match &sess.target.target.arch[..] {
+    // The native x86 toolchain is not in a subfolder unlike the rest
+    #[cfg(target_arch = "x86")]
```
Comment (alexcrichton) [inline src/librustc_trans/back/msvc/mod.rs]: Can these matches be done with `if cfg!` instead of `#[cfg]`?

**Comment by alexcrichton** [comment]
I'm a little worried about this logic for a few reasons:

* This is basically an entirely new implementation, there's essentially no connection to what Clang does. This is generally a red flag, but I also never found a reason for why Clang does what it does, so it may not be that bad.
* It looks like the way this is written will force us to update the compiler each time a new SDK is released. That may not be able to ever avoid, however.
* It's very difficult to test this. I'd like to at least try to poke around a bit locally, but unfortunately my VM is offline.

I think that if this passes manual testing that we should land this, however, as fixing compatibility with the most recent VS is likely more important for now. It'd be great, however, to get a definitive answer on what this logic should be (or perhaps providing a better guarantee that it'll work), but I unfortunately don't know how to do that :(.

cc @vadimcn

File: src/librustc_trans/back/msvc/mod.rs [hunk 4]
```diff
@@ -46,283 +46,179 @@ pub fn link_exe_cmd(sess: &Session) -> Command {
...
     }
 
-    fn windows_sdk_v8_subdir(sess: &Session) -> Option<&'static str> {
-        match &sess.target.target.arch[..] {
-            "x86" => Some("x86"),
-            "x86_64" => Some("x64"),
-            "arm" => Some("arm"),
-            _ => return None,
+    // We choose the linker toolchain that has the same host as rustc.
+    // This allows cross compiling to actually work.
```
Comment (vadimcn) [inline src/librustc_trans/back/msvc/mod.rs]: Is this because of env vars, or just to avoid having to detect bitness of the host OS?

**Comment by vadimcn** [comment]
I don't know which approach is better off the top of my head.
@retep998, could expand a bit on why you've decided to re-write this logic from scratch?  Not that there's anything wrong with the new code (as far as I can tell).

> It looks like the way this is written will force us to update the compiler each time a new SDK is released

The VC's registry structure will likely stay the same for the next few releases, so we could try to extrapolate versions into the future and hope that it works. 
Also, maybe it'd be worth to introduce environment variable overrides (e.g. `RUST_MSVC_LINKER`, `RUST_MSVC_LIBS`) to allow users to fix things up without having  to rebuild the compiler from source?

File: src/librustc_trans/back/msvc/mod.rs (hunk 2 above)
Comment (retep998) [inline src/librustc_trans/back/msvc/mod.rs]: Visual C. Shorthand for MSVC.

File: src/librustc_trans/back/msvc/mod.rs (hunk 4 above)
Comment (retep998) [inline src/librustc_trans/back/msvc/mod.rs]: Mainly just to avoid having to detect bitness of the host OS. I'll add a FIXME comment saying this should probably detect the host OS bitness.

**Comment by retep998** [comment]
Currently you can already override the entire system by just executing the proper vcvars bat file causing this code to back off and just trust everything is setup correctly and it'll work. Since we never know what sort of changes will occur in new versions of VS (such as VS 2015 adding the UCRT and the Windows 10 SDK both of which required new logic), I think it's better to not try to guess and just add support for it once someone can actually test it out.

As for testing this, I have VS 2015 2013 and 2012, and by commenting out some of the versions in that VS version array I could test how it handles all three versions and it works perfectly. It falls back to the 8.1 SDK for 2015 when there's no 10 SDK, it uses the 8.1 SDK for 2013 and it uses the 8 SDK for 2012. It still would be nice to get people testing it on other setups though as I've done all my testing on 64-bit Windows 10 only.

This code should work fine for new releases of the Win10 SDK as I've borrowed the exact logic from vcvars to find the newest Win10 SDK. Considering Microsoft said that Windows 10 is their final version of Windows, this means we may be in the clear with regards to that. New versions of VS however are still a possibility although the user can always just execute vcvars to setup the environment themselves.

The reason I rewrote this was because I felt like it wasn't robust enough. This implementation should very closely mirror what vcvars does and I'm more willing to trust what Microsoft does than what clang does, at least with regards to Microsoft's own software.

**Comment by jasonwilliams200OK** [comment]
We can now also download the standalone / command-line [Build Tools 2015](https://www.microsoft.com/en-in/download/details.aspx?id=48159), without even installing full VS2015, which installs compilers+SDKs+other utilities to compile C/C++ code on Windows.

Although the package itself is a Technical Preview, but I have successfully compiled with it on Windows 7 (fresh install) to Windows 10 and build Windows XP+ compatible libs. The CL compiler version is same as the one shipped with VS2015 Update 1.

It seems like this CLI-base is in preparation for Server 2016 and Nano Server feature called "containers". Also Windows team is working to provide "docker containers" (to bridge with their "native containers") GUI/CLI, where installing VS won't be a viable option: https://github.com/docker/docker/pulls/jhowardmsft.

**Comment by jasonwilliams200OK** [comment]
> what clang does, 

I know at least detecting Windows 10 SDK (which is now at a new location the first time in a long time compared to its predecessors) hasn't done correctly by gyp, the build system favored by Chrome and node.js native modules projects. Initially gyp was developed because cmake was considered not meeting the requirement. Chrome guys are now moving away (or already) from their own gyp to another build system by Google called [gn](https://www.chromium.org/developers/gn-build-configuration) which seems to have fixed this SDK detection issue (but it is definitely in amateur hour to be fully trusted).

**Comment by retep998** [comment]
@vadimcn 
Really the reason I decided to overhaul this code was because it broke on the Windows 10 SDK code which was last touched by me so I felt somewhat responsible and also I was rather annoyed because the last time I touched it was to fix it being broken on the Windows 10 SDK stuff. So, I thought to myself, I will do this properly this time, threw out the old code, dug deep into `vcvarsqueryregistry.bat` and made this PR.

**Comment by alexcrichton** [comment]
I agree with @vadimcn that we should definitely have an escape hatch for future proofing, but I also agree with @retep998 that we should have the necessary detection in place that if you're in a VC shell then rustc won't be doing anything fancy. I also agree that mirroring what Microsoft does is likely better than Clang, and for now we claim we need VS 2013+ anyway so as long as we're compatible with those I'm happy.

Thanks again @retep998! r=me with the debugging prints and such removed

**Comment by alexcrichton** [comment]
Or better yet actually, feel free to just convert them all to logging

**Comment by retep998** [comment]
Switched it to use `debug!` logging and rebased while I was at it.

**Comment by retep998** [comment]
I'm getting somewhat annoyed at that mac buildbot and its spurious failures.

**Comment by brson** [comment]
Requested for backport in https://github.com/rust-lang/rust/issues/30229

**Comment by alexcrichton** [comment]
Accepted for a backport
