### PR TITLE
Suggest array indexing when tuple indexing on an array

### LINKED ISSUE #53712: Make the error generated by using tuple indexing on an array more specific.
Attempting to compile this:
```rust
let a = [100, 100];
a.0;
```
will give this error:
```
error[E0609]: no field `0` on type `[{integer}; 2]`
```
I was thinking that a clearer error could be something along the lines of:
```
error[E----]: attempting to use tuple indexing on an array.
```
and give this hint:
```
help: change this to `a[0]`
```

### PR DESCRIPTION
**Pull request by memoryruins**
Closes #53712

r? @varkor 
cc @estebank

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3344,6 +3344,12 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                 }
                             };
                     }
+                    ty::Array(ty, _) if ty.is_numeric() => {
```
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Is there any reason to limit this suggestion to only `[{integer}; _]` and `[{float}; _]`? I'm not against it, as being conservative in suggestions is not bad, I just want to hear what was _your_ reasoning.

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -3344,6 +3344,12 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                        let base = self.tcx.hir.node_to_pretty_string(base.id);
+                        let msg = format!("attempting to use tuple indexing on an array; try");
```
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Let's change the wording to something along the lines of `instead of using tuple indexing use array indexing`.

**Review by estebank — CHANGES_REQUESTED** [review]
I'm really happy to see this PR!

I left a couple of comments inline.

**Comment by memoryruins** [comment]
@estebank Limiting to only numeric types was definitely overly conservativ, and I should’ve been checking if the field was numeric instead :)

Good thinking on the array length and applicability levels. I’ll try it out!

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3344,12 +3344,24 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                            let base = self.tcx.hir.node_to_pretty_string(base.id);
+                            let help = "instead of using tuple indexing, use array indexing";
+                            let suggestion = format!("{}[{}]", base, field);
+                            let applicability = if len < user_index {
+                                Applicability::MachineApplicable
+                            } else {
+                                Applicability::MaybeIncorrect
+                            };
+                            err.span_suggestion_with_applicability(
+                                field.span, help, suggestion, applicability
```
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: You probably want to use `expr.span` here instead of `field.span`.

File: src/test/ui/issues/issue-53712.stderr [hunk 4]
```diff
@@ -2,7 +2,7 @@ error[E0609]: no field `0` on type `[{integer}; 5]`
   --> $DIR/issue-53712.rs:5:9
    |
 LL |     arr.0;
-   |         ^ help: attempting to use tuple indexing on an array; try: `arr[0]`
+   |         ^ help: instead of using tuple indexing, use array indexing: `arr[0]`
```
Comment (estebank) [inline src/test/ui/issues/issue-53712.stderr]: I just realized that the suggestion span is slightly incorrect. The suggestion span should cover the entire expression, otherwise when applying the suggestion with `rustfix`, for example, you'd end up with the following code

```
    arr.arr[0];
```

**Review by estebank — APPROVED** [review]
Other than one last fix needed, LGTM.

File: src/test/ui/issues/issue-53712.stderr (hunk 4 above)
Comment (memoryruins) [reply src/test/ui/issues/issue-53712.stderr]: Ah, right you are!
