### PR TITLE
Avoid lowering code under dead SwitchInt targets

### LINKED ISSUE #121552: Debug builds of compiler_builtins fail to link due to references to precondition_check in libcore
Likely caused by #120594. cc @saethlin 

CI for compiler_builtins is failing with:
```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustccNjGuE\\symbols.o" "D:\\a\\compiler-builtins\\compiler-builtins\\target\\x86_64-pc-windows-msvc\\debug\\examples\\intrinsics.intrinsics.94b4869361004a03-cgu.0.rcgu.o" "/LIBPATH:D:\\a\\compiler-builtins\\compiler-builtins\\target\\x86_64-pc-windows-msvc\\debug\\deps" "/LIBPATH:D:\\a\\compiler-builtins\\compiler-builtins\\target\\debug\\deps" "/LIBPATH:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "kernel32.lib" "msvcrt.lib" "D:\\a\\compiler-builtins\\compiler-builtins\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libcompiler_builtins-b84df12ffea9ddc5.rlib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:D:\\a\\compiler-builtins\\compiler-builtins\\target\\x86_64-pc-windows-msvc\\debug\\examples\\intrinsics.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\runneradmin\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: libcompiler_builtins-b84df12ffea9ddc5.rlib(compiler_builtins-b84df12ffea9ddc5.compiler_builtins.ca00aaabc6ad635b-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol _ZN4core3ptr13read_volatile18precondition_check17ha1e11d6217b519e2E referenced in function _ZN4core3ptr13read_volatile17h3fd78456f42a46ecE
          libcompiler_builtins-b84df12ffea9ddc5.rlib(compiler_builtins-b84df12ffea9ddc5.compiler_builtins.ca00aaabc6ad635b-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol _ZN4core10intrinsics19copy_nonoverlapping18precondition_check17h5ef2e74b4a074627E referenced in function _ZN4core3ptr14read_unaligned17h327557c7a8527effE
          D:\a\compiler-builtins\compiler-builtins\target\x86_64-pc-windows-msvc\debug\examples\intrinsics.exe : fatal error LNK1120: 2 unresolved externals
```

The cause seems to be from a combination of factors:
- compiler-builtins cannot reference any symbols in libcore. It can only call functions marked with `#[inline]`, since those are codegen'ed into compiler_builtins.rlib.
- `precondition_check` is marked as `#[inline(never)]`, which breaks this.
- The call is not eliminated because `core::intrinsics::debug_assertions` is resolved late in the codegen backend, after any MIR optimizations.
- This failure happens in debug builds, so LLVM isn't eliminating the `if` branch either.

### PR DESCRIPTION
**Pull request by saethlin**
The objective of this PR is to detect and eliminate code which is guarded by an `if false`, even if that `false` is a constant which is not known until monomorphization, or is `intrinsics::debug_assertions()`.

The effect of this is that we generate no LLVM IR the standard library's unsafe preconditions, when they are compiled in a build where they should be immediately optimized out. This mono-time optimization ensures that builds which disable debug assertions do not grow a linkage requirement against `core`, which compiler-builtins currently needs: https://github.com/rust-lang/rust/issues/121552

This revives the codegen side of https://github.com/rust-lang/rust/pull/91222 as planned in https://github.com/rust-lang/rust/issues/120848.

### CODE REVIEW

**Comment by saethlin** [comment]
r? compiler

**Comment by saethlin** [comment]
I reviewed the above perf report and I have no theories on why any of the builds got slower. The optimization added here leaves behind some blocks which are just an unreachable terminator, which perhaps may be inducing some extra work for LLVM. But those unreachable blocks are also trivially dead code, they're only reached by the not-taken target of a `br i1 false` terminator.

It is possible that those regressions will be recouped by https://github.com/rust-lang/rust/pull/120650 because that PR will turn those just-an-unreachable blocks into blocks without predecessors.

But I also don't think this miniscule regression is much worth thinking about. The transform here is pure code deletion, and eases development of compiler-builtins.

**Comment by saethlin** [comment]
Perf queue is quiet, and https://github.com/rust-lang/rust/pull/120650 landed. So let's go again!
@bors try @rust-timer queue

**Comment by RalfJung** [comment]
At least as far as the primary benchmark is concerned, opening the details shows that it has been fluctuating up and down by around .8% quite a lot recently, so this is probably just noise.

**Comment by RalfJung** [comment]
We could also land an emergency patch first, adding `#[cfg(debug_assertions)]` to the two checks that affect compiler-builtins (read_volatile and copy_nonoverlapping).

**Comment by RalfJung** [comment]
Ah the PR is actually marked as waiting-for-author, @saethlin is that deliberate?

**Comment by saethlin** [comment]
:facepalm: No

@rustbot ready

**Comment by DianQK** [comment]
Just want to correct my understanding here. From my understanding of this PR and [Lowering MIR to a Codegen IR](https://rustc-dev-guide.rust-lang.org/backend/lowering-mir.html), we actually have some extra passes after monomorphization?

Is it just these passes are put in codegen? I'm considering whether it would be better to split it into a post-opt phase that running some mir passes after monomorphization.

**Comment by saethlin** [comment]
Yeah, we have a number of optimizations baked into `rustc_codegen_ssa`. They're not well-organized into passes, because they can't mutate the MIR, because it's in a query result cache. The MIR optimization pipeline steals the pre-optimization MIR query result (making it a panic to try to do that query again) then return it from the `optimized_mir` query.

We definitely need something better for optimizations like this, but it can't work like `optimized_mir` does because we can't steal the MIR that post-mono optimizations start with, and cloning then re-optimizing the MIR for each new instantiation of a generic function seems too costly. We'd be paying for that clone just to have these tweaks in monomorphization organized differently which seems dubious.

We have this thing called `MirPatch` and I think it might be nice to have a system post-mono that does optimizations by computing `MirPatch`es then wraps those up with a reference to the original MIR to make accessing or traversing it return how the MIR looks with the patch applied. This is the kind of idea I'd have to implement to see if it works though, and there's other things I want to work on more than this. I'd be happy to see any kind of better organization for these MIR "passes" in `rustc_codegen_ssa`, and I suspect so would the other people writing them like @scottmcm.

**Comment by Amanieu** [comment]
> We could also land an emergency patch first, adding `#[cfg(debug_assertions)]` to the two checks that affect compiler-builtins (read_volatile and copy_nonoverlapping).
> 
> (Not sure when someone will have time to review this PR. Reviewing the emergency patch would be trivial.)

While this would fix compiler-builtins CI, it won't fix any users of `-Zbuild-std` who are building the standard library without `--release`.

**Comment by RalfJung** [comment]
I don't think this PR helps for those people either. The problematic code will not even be dead code for them.

**Comment by Amanieu** [comment]
This PR will optimize this `if` away even in debug builds, which will eliminate the reference to the `#[inline(never)]` function and avoid the link error:
https://github.com/rust-lang/rust/pull/120594/files#diff-7e8efe3110a5b74834b0a6e63768df9982c1599758a6634337ce356a0e22e0f4R2650-R2652

**Comment by RalfJung** [comment]
In debug builds, `debug_assertions` will return true. So why would it eliminate the reference...?

File: compiler/rustc_middle/src/mir/mod.rs [hunk 1]
```diff
@@ -642,6 +643,130 @@ impl<'tcx> Body<'tcx> {
...
+    ) {
+        if !set.insert(bb) {
+            return;
+        }
+
+        let data = &self.basic_blocks[bb];
+
+        if let Some((bits, targets)) = Self::try_const_mono_switchint(tcx, instance, data) {
+            let target = targets.target_for_value(bits);
+            return self.reachable_blocks_in_mono_from(tcx, instance, set, target);
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/mod.rs:684]: Put this and the other recursion behind a `ensure_sufficient_stack` call, otherwise matthias will open an issue within 3.7 minutes of this PR landing 😛

File: compiler/rustc_middle/src/mir/mod.rs [hunk 2]
```diff
@@ -642,6 +643,130 @@ impl<'tcx> Body<'tcx> {
...
+        // into the SwitchInt.
+
+        let last_stmt = block
+            .statements
+            .iter()
+            .rev()
+            .skip_while(|stmt| {
+                matches!(stmt.kind, StatementKind::StorageDead(_) | StatementKind::StorageLive(_))
+            })
+            .next()?;
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/mod.rs:749]:
```suggestion
            .find(|stmt| {
                !matches!(stmt.kind, StatementKind::StorageDead(_) | StatementKind::StorageLive(_))
            })?;
```

File: compiler/rustc_middle/src/mir/mod.rs [hunk 3]
```diff
@@ -642,6 +643,130 @@ impl<'tcx> Body<'tcx> {
...
+        let StatementKind::Assign(box (place, rvalue)) = &last_stmt.kind else {
+            return None;
+        };
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/mod.rs:752]: use `last_stmt.kind.as_assign()?`

**Review by oli-obk — APPROVED** [review]
r=me with some minor changes

**Comment by saethlin** [comment]
The problematic compiler-builtins CI is this: https://github.com/rust-lang/compiler-builtins/blob/351d48e4b95f1665cfd3360e3ba8f3dd4d3fb3c1/ci/run.sh#L88-L97

Not that I think this CI has any merit. It's "holding up development" (you could disable the test at any time!) even though compiler-builtins is already broken by the test's definition.

**Comment by RalfJung** [comment]
> While this would fix compiler-builtins CI, it won't fix any users of -Zbuild-std who are building the standard library without --release.

So, more specifically -- compiler-builtins CI checks that a build without `--release` *and with `-C debug-assertions=no`* works.

I don't think it is reasonably possible to support compiler-builtins with `-C debug-assertions=yes`. I imagine that must already be broken right now since it will insert overflow checks everywhere which will call into the panic machinery and not all of that is `#[inline]`. I have no idea how `-Zbuild-std` handles that.

**Comment by saethlin** [comment]
I swear I built this locally...
@bors r-

**Comment by saethlin** [comment]
I just checked to see if this PR optimizes out all the panic calls from a compiler-builtins build with debug assertions off and optimizations off, and it looks to me like since https://github.com/rust-lang/rust/pull/121662 landed, it does not. It isn't entirely clear to me how to fix this. I'll put up a PR in a bit with some suggestions, but I do not like them.

File: compiler/rustc_codegen_ssa/src/mir/mod.rs [hunk 4]
```diff
@@ -256,13 +256,22 @@ pub fn codegen_mir<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
...
     // So drop the builder of `start_llbb` to avoid having two at the same time.
     drop(start_bx);
 
     // Codegen the body of each block using reverse postorder
     for (bb, _) in traversal::reverse_postorder(mir) {
-        fx.codegen_block(bb);
+        if reachable_blocks.contains(bb) {
+            fx.codegen_block(bb);
+        } else {
+            // This may have references to things we didn't monomorphize, so we
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/mod.rs:270]: > This may have references to things we didn't monomorphize

How is that possible? The collector should ensure that we monomorphize everything referenced in the MIR, even in unreachable parts of the MIR.

However it could be interesting to make use of `reachable_blocks_in_mono` in the collector, and thus avoid collecting the functions in dead basic blocks.

Comment (saethlin) [reply compiler/rustc_codegen_ssa/src/mir/mod.rs:270]: 🤦 I didn't fully update the comment from scottmcm's PR that I stole this from

**Review by cjgillot — COMMENTED** [review]
Just saw a comment was never sent.

File: compiler/rustc_middle/src/mir/mod.rs [hunk 5]
```diff
@@ -642,6 +643,130 @@ impl<'tcx> Body<'tcx> {
...
+    /// of `if <T as Trait>::CONST`, as well as `intrinsics::debug_assertions`.
+    pub fn reachable_blocks_in_mono(
+        &self,
+        tcx: TyCtxt<'tcx>,
+        instance: Instance<'tcx>,
+    ) -> BitSet<BasicBlock> {
+        let mut set = BitSet::new_empty(self.basic_blocks.len());
+        self.reachable_blocks_in_mono_from(tcx, instance, &mut set, START_BLOCK);
+        set
+    }
```
[the remark this answers is not in the document]
Comment (saethlin) [reply compiler/rustc_middle/src/mir/mod.rs:666]: Implemented in https://github.com/rust-lang/rust/pull/123272

File: compiler/rustc_codegen_ssa/src/mir/mod.rs (hunk 4 above)
Comment (saethlin) [reply compiler/rustc_codegen_ssa/src/mir/mod.rs:270]: I'm fixing this in https://github.com/rust-lang/rust/pull/123272
