### PR TITLE
Remove &[T] from vec_deque::Drain

### LINKED ISSUE #60076: VecDeque's Drain::drop writes to memory that a shared reference points to
liballoc's `test_drain` fails when run in Miri. The error occurs in the `drain(...).collect()` call:

* `collect` is called with a `vec_deque::Drain<usize>` as argument. `Drain` contains `Iter` contains a shared reference to a slice; that slice is thus marked as "must not be mutated for the entire duration of this function call".
* `collect` calls `from_iter` calls `extend` calls `for_each` calls `fold`, which eventually drops the `Drain`.
* `Drain::drop` calls `source_deque.wrap_copy` to re-arrange stuff (I have not fully understood this yet), and in some cases this will end up writing to memory that the slice in `Iter` points to.

I am not sure what the best way to fix this is. We have to fix `Drain` holding (indirectly) a shared reference to something that it'll mutate during its `Drop`. The mutation is likely there for a reason, so I guess the shared reference has to go. (FWIW, this shared reference already caused other trouble, but that was fixed by https://github.com/rust-lang/rust/pull/56161.)

Cc @nikomatsakis @Gankro

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/60076

I don't know what the right approach is here. There were a few suggestions in the issue, and they all seem a bit thorny to implement. So I just picked one that was kind of familiar.

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/iter.rs [hunk 1]
```diff
@@ -94,18 +100,18 @@ impl<'a, T> Iterator for Iter<'a, T> {
         let (mut iter, final_res);
         if self.tail <= self.head {
             // Safety: single slice self.ring[self.tail..self.head] is initialized.
-            iter = unsafe { MaybeUninit::slice_assume_init_ref(&self.ring[self.tail..self.head]) }
-                .iter();
+            let sli: &[T] = unsafe { &(&*self.ring)[self.tail..self.head] };
```
Comment (saethlin) [inline library/alloc/src/collections/vec_deque/iter.rs:103]: I suspect this reborrowing pattern makes people uncomfortable, but this passes Miri, and I'm not really sure how to avoid constructing `&[T]`. Perhaps in this case it is worth the extra code to only construct the slice to the init region?

File: library/alloc/src/collections/vec_deque/iter.rs [hunk 2]
```diff
@@ -13,38 +15,44 @@ use super::{count, wrap_index, RingSlices};
 /// [`iter`]: super::VecDeque::iter
 #[stable(feature = "rust1", since = "1.0.0")]
 pub struct Iter<'a, T: 'a> {
-    ring: &'a [MaybeUninit<T>],
+    ring: *const [T],
```
Comment (SkiFire13) [inline library/alloc/src/collections/vec_deque/iter.rs:18]: Couldn't this be a `NonNull`?

File: library/alloc/src/collections/vec_deque/iter.rs [hunk 3]
```diff
@@ -13,38 +15,44 @@ use super::{count, wrap_index, RingSlices};
...
     tail: usize,
     head: usize,
+    _marker: PhantomData<&'a T>,
 }
 
 impl<'a, T> Iter<'a, T> {
     pub(super) fn new(ring: &'a [MaybeUninit<T>], tail: usize, head: usize) -> Self {
-        Iter { ring, tail, head }
+        Iter {
+            ring: ptr::slice_from_raw_parts(ring.as_ptr().cast(), ring.len()),
```
Comment (SkiFire13) [inline library/alloc/src/collections/vec_deque/iter.rs:27]: This could also be written as `ring as *const [MaybeUninit<T>] as *const [T]`. Not sure if the `as` cast is better than a `ptr::slice_from_raw_parts` call, but in both cases I feel like there should be a better way to write this.

File: library/alloc/src/collections/vec_deque/iter.rs [hunk 4]
```diff
@@ -13,38 +15,44 @@ use super::{count, wrap_index, RingSlices};
...
+            head,
+            _marker: PhantomData,
+        }
     }
 }
 
+#[stable(feature = "rust1", since = "1.0.0")]
+unsafe impl<T: Sync> Sync for Iter<'_, T> {}
+#[stable(feature = "rust1", since = "1.0.0")]
+unsafe impl<T: Send> Send for Iter<'_, T> {}
```
Comment (5225225) [inline library/alloc/src/collections/vec_deque/iter.rs:38]: This doesn't seem to match the current implementation. Looks like we currently bound Send on T: Sync (Which seems correct, since this is handing out *shared* references).

https://doc.rust-lang.org/nightly/std/collections/vec_deque/struct.Iter.html#impl-Send-for-Iter%3C%27a%2C%20T%3E

**Comment by RalfJung** [comment]
r? libs

File: library/alloc/src/collections/vec_deque/iter.rs [hunk 5]
```diff
@@ -13,38 +15,53 @@ use super::{count, wrap_index, RingSlices};
...
-        Iter { ring, tail, head }
+        Iter {
+            ring: unsafe { NonNull::new_unchecked(ring as *const [MaybeUninit<T>] as *mut _) },
+            tail,
+            head,
+            _marker: PhantomData,
+        }
+    }
+
+    unsafe fn ring(&self) -> &'a [MaybeUninit<T>] {
```
Comment (RalfJung) [inline library/alloc/src/collections/vec_deque/iter.rs:34]: That's a very long-lived reference, is that needed?

Comment (saethlin) [reply library/alloc/src/collections/vec_deque/iter.rs:34]: As far as I can tell, we need to get a `&'a T` by some means in order to implement all the iterator methods, so we're stuck with this hazard.

Let's see if I can do something to just `Drain` to fix the problem there...

Comment (saethlin) [reply library/alloc/src/collections/vec_deque/iter.rs]: The second commit in this PR now reverts the first one and modifies just the `Drain` struct. Do you think that approach is more satisfying?

Comment (RalfJung) [reply library/alloc/src/collections/vec_deque/iter.rs]: I haven't checked the details but I do think that reusing `Iter` was kind of a hack so this seems cleaner to me indeed.

Let's see what the libs reviewer says.

Comment (thomcc) [reply library/alloc/src/collections/vec_deque/iter.rs]: Seems fine to me.

**Comment by thomcc** [comment]
Thanks.

@bors r+
