### PR TITLE
Normalize function signature in function casting check procedure

### LINKED ISSUE #54094: Functions pointers with associated type parameters can't cast to pointers
```rust
trait Zoo {
    type X;
}

impl Zoo for u16 {
    type X = usize;
}

fn foo(abc: <u16 as Zoo>::X) {}

fn main() {
    let x: *const u8 = foo as _;
}
```

([Playground](https://play.rust-lang.org/?gist=0803ae70e4f8848bf10d3f11174600cc&version=nightly&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0605]: non-primitive cast: `fn(<u16 as Zoo>::X) {foo}` as `*const u8`
  --> src/main.rs:13:24
   |
13 |     let x: *const u8 = foo as _;
   |                        ^^^^^^^^
   |
   = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0605`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

Seems like this should work.

### PR DESCRIPTION
**Pull request by ldm0**
Fixes #54094
```rust
trait Zoo {
    type X;
}

impl Zoo for u16 {
    type X = usize;
}

fn foo(abc: <u16 as Zoo>::X) {}

fn main() {
    let x: *const u8 = foo as _;
}
```

Currently a `FnDef` need to be checked if it's able to cast to `FnPtr` before it is actually casted. But the signature of `FnPtr` target's associated types are not normalized:

https://github.com/rust-lang/rust/blob/96d77f0e5f103612d62b85938aacfb33f5768433/src/librustc_typeck/check/cast.rs#L536-L553
However, during the coercion check, the signature of `FnPtr` target's associated types are normalized (The `<u16 as Zoo>::X` turns into `usize`). 

https://github.com/rust-lang/rust/blob/96d77f0e5f103612d62b85938aacfb33f5768433/src/librustc_typeck/check/coercion.rs#L687-L729

This inconsistency leads to the error:`Err(Sorts(ExpectedFound { expected: <u16 as Zoo>::X, found: usize }))`.

### CODE REVIEW

**Comment by ldm0** [comment]
r? @eddyb 
Since 33ecf72e8e26b5bf5449ae27297e83c9f78aa3ad

File: src/librustc_typeck/check/cast.rs [hunk 1]
```diff
@@ -536,7 +536,10 @@ impl<'a, 'tcx> CastCheck<'tcx> {
                 match self.expr_ty.kind {
                     ty::FnDef(..) => {
                         // Attempt a coercion to a fn pointer type.
-                        let f = self.expr_ty.fn_sig(fcx.tcx);
+                        let f = fcx.normalize_associated_types_in(
+                            self.expr.span,
+                            &self.expr_ty.fn_sig(fcx.tcx),
+                        );
```
Comment (eddyb) [inline src/librustc_typeck/check/cast.rs:542]: cc @nikomatsakis This makes sense to me.

Comment (nikomatsakis) [reply src/librustc_typeck/check/cast.rs:542]: Yes, it seems like it is necessary, given that `fn_sig` returns the result of data from the `def_id` ..

**Review by nikomatsakis — APPROVED** [review]
