### PR TITLE
Stabilize GlobalAlloc and #[global_allocator]

### LINKED ISSUE #27389: Tracking issue for changing the global, default allocator (RFC 1974)
Tracking issue for ~~https://github.com/rust-lang/rfcs/pull/1183~~ https://github.com/rust-lang/rfcs/pull/1974

Known bugs:

* [ ] The `#[global_allocator]` attribute doesn't work in modules #44113

Current status:

* [x] Implemented in https://github.com/rust-lang/rust/pull/42727
* [ ] [Stabilization checklist](https://forge.rust-lang.org/stabilization-guide.html)
  * [ ] Remove docs from the unstable book
  * [ ] Add docs to the real book
* [x] Add jemalloc as a crates on crates.io ([jemallocator](https://crates.io/crates/jemallocator))
* [ ] Once stable, link binaries to the system allocator by default #36963
  * known issues https://github.com/rust-lang/rust/issues/36963#issuecomment-252029017
  * valgrind doesn't work on jemalloc https://github.com/rust-lang/rust/issues/28224
  * crates are gone https://github.com/rust-lang/rust/issues/33082

A quick summary of the current state of this feature is that you can change the default global allocator via:

```rust
// Change this program's global allocator. At most one `#[global_allocator]` 
// allowed in any crate graph.
#[global_allocator]
static ALLOCATOR: MyAlloc = MyAlloc;


// When defining a global allocator, the `Alloc` trait must be defined
// for `&'a T` instead of `T`
use std::heap::Alloc;

struct MyAlloc;

impl<'a> Alloc for &'a MyAlloc {
    // ...
}
```

### LINKED ISSUE #49668: Tracking issue for the GlobalAlloc trait and related APIs
PR https://github.com/rust-lang/rust/pull/49669 adds a `GlobalAlloc` trait, separate from `Alloc`. This issue track the stabilization of this trait and some related APIs, to provide the ability to [change the global allocator](https://github.com/rust-lang/rust/issues/27389), as well as allocating memory without abusing `Vec::with_capacity` + `mem::forget`.

Defined in or reexported from the `std::alloc` module:

**Update:** below is the API proposed when this issue was first opened. The one being stabilized is at https://github.com/rust-lang/rust/issues/49668#issuecomment-393263510.

<details>

```rust
/// #[global_allocator] can only be applied to a `static` item that implements this trait
pub unsafe trait GlobalAlloc {
    unsafe fn alloc(&self, layout: Layout) -> *mut Opaque;
    unsafe fn dealloc(&self, ptr: *mut Opaque, layout: Layout);

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut Opaque { 
        // Default impl: self.alloc() and ptr::write_bytes()
    }
    unsafe fn realloc(&self, ptr: *mut Opaque, layout: Layout, new_size: usize) -> *mut Opaque {
        // Default impl: self.alloc() and ptr::copy_nonoverlapping() and self.dealloc()
    }
    
    // More methods with default impls may be added in the future
}

extern {
    pub type Opaque;
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Layout { /* private */ }

impl Layout {
    pub fn from_size_align(size: usize: align: usize) -> Result<Self, LayoutError> {…}
    pub unsafe fn from_size_align_unchecked(size: usize: align: usize) -> Self {…}
    pub fn size(&self) -> usize {…}
    pub fn align(&self) -> usize {…}
    pub fn new<T>() -> Self {…}
    pub fn for_value<T: ?Sized>(t: &T) -> Self {…}
}

#[derive(Copy, Clone, Debug)]
pub struct LayoutError { /* private */ }

/// Forwards method calls to the `static` item registered
/// with `#[global_allocator]` if any, or the operating system’s default.
pub struct Global;

/// The operating system’s default allocator.
pub struct System;

impl GlobalAlloc for Global {…}
impl GlobalAlloc for System {…}
```

</details>

CC @rust-lang/libs, @glandium

## Unresolved questions or otherwise blocking

* [x] Wait for extern types https://github.com/rust-lang/rust/issues/43467 to be stable in the language before stabilazing one in the standard library.
* [x] Name of the `Global` type. `GlobalAllocator`?
* [x] ~~Name of the `Void` type. Lower-case `void` would match C (our `*mut void` is very close to C’s `void*` type), but violates the convension of camel-case for non-primitive types. But `Void` in camel-case is already the name of [an empty enum](https://docs.rs/void/1.0.2/void/enum.Void.html) (not an extern type like here) in a [popular](https://crates.io/crates/void#crate-downloads) crate. (An extern type is desirable so that `<*mut _>::offset` cannot be called without first casting to another pointer type.) Maybe call it `Opaque`? `Unknown`?~~ Renamed to `Opaque`.
  * [x] Rename again to something else?
* [x] ~Taking `Layout` by reference, or making it `Copy` https://github.com/rust-lang/rust/issues/48458.~ `Copy`: https://github.com/rust-lang/rust/pull/50109
* [x] ~`GlobalAlloc::owns`: https://github.com/rust-lang/rust/issues/44302 proposes making it required for allocators to be able to tell if it “owns” a given pointer.~ Not to be required by this trait since glibc and Windows do not support this.
* [x] ~Settle semantics of layout "fit" and other safety conditions.~ Without an `usable_size` method (for now), the layout passed to dealloc must be the same as was passed to alloc. (Same as with `Alloc::usable_size`’s default impl returning `(layout.size(), layout.size())`.)
* [x] ~An `oom` method is part of `GlobalAlloc` so that implementation-specific printing to stderr does not need to be part of liballoc and instead goes through `#[global_allocator]`, but this does not really belong in the `GlobalAlloc` trait. Should another mechanism like `#[global_allocator]` be added to have pluggable OOM handling?~ https://github.com/rust-lang/rust/pull/50144

## Not proposed (yet) for stabilization

* The `Alloc` trait
* The rest of `Layout` methods
* The `AllocErr` type

We’re not ready to settle on a design for collections generic over the allocation type. Discussion of this use case should continue on the tracking issue for the `Alloc` trait: https://github.com/rust-lang/rust/issues/32838.

### PR DESCRIPTION
**Pull request by glandium**
This PR implements the changes discussed in https://github.com/rust-lang/rust/issues/49668#issuecomment-393263510

Fixes #49668
Fixes #27389

This does not change the default global allocator: #36963

### CODE REVIEW

**Comment by glandium** [comment]
Cc: @SimonSapin

**Comment by SimonSapin** [comment]
Oh, I have pretty much the same branch and was only waiting to add docs before I submit it… :)

**Comment by glandium** [comment]
I wanted to see how that would impact me, so I went ahead but didn't bother with the doc. :)

**Comment by SimonSapin** [comment]
I’ve pushed additional commits to this PR. @glandium’s commits look good to me, mine still need review. In particular for the new docs and the API contracts they describe.

Both tracking issues for features being stabilized have already finished FCP, but since we’re making last minute changes let’s have a final Final Comment Perdiod:

@rfcbot fcp merge

File: src/libcore/alloc.rs [hunk 1]
```diff
@@ -357,23 +360,28 @@ impl fmt::Display for AllocErr {
 /// The `CannotReallocInPlace` error is used when `grow_in_place` or
 /// `shrink_in_place` were unable to reuse the given memory block for
 /// a requested layout.
+// FIXME: should this be in libcore or liballoc?
```
Comment (Amanieu) [inline src/libcore/alloc.rs]: This is used in the `Alloc` trait and therefore needs to be in libcore.

File: src/libcore/alloc.rs [hunk 2]
```diff
@@ -357,23 +360,28 @@ impl fmt::Display for AllocErr {
...
 // (we need this for downstream impl of trait Error)
+#[unstable(feature = "allocator_api", issue = "32838")]
 impl fmt::Display for CannotReallocInPlace {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
         write!(f, "{}", self.description())
     }
 }
 
 /// Augments `AllocErr` with a CapacityOverflow variant.
+// FIXME: should this be in libcore or liballoc?
```
Comment (Amanieu) [inline src/libcore/alloc.rs]: This could probably be moved to liballoc since it is only used by collections.

File: src/libcore/alloc.rs [hunk 3]
```diff
@@ -392,59 +400,194 @@ impl From<AllocErr> for CollectionAllocErr {
...
+/// ```
+///
+/// # Unsafety
+///
+/// The `GlobalAlloc` trait is an `unsafe` trait for a number of reasons, and
+/// implementors must ensure that they adhere to these contracts:
+///
+/// * Pointers returned from allocation functions must point to valid memory and
+///   retain their validity until at least the instance of `GlobalAlloc` is dropped
+///   itself.
```
Comment (Amanieu) [inline src/libcore/alloc.rs]: Does the concept of dropping an instance of `GlobalAlloc` really make sense? Should we just require pointers to be valid forever until explicitly freed?

Comment (SimonSapin) [reply src/libcore/alloc.rs]: Good point, a `static` is never dropped. I copied this from `Alloc` docs but it doesn’t make sense here, removed.

File: src/libcore/alloc.rs (hunk 1 above)
Comment (SimonSapin) [reply src/libcore/alloc.rs]: Indeed. Removed that comment.

File: src/libstd/alloc.rs [hunk 4]
```diff
@@ -8,18 +8,83 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
-//! dox
+//! Memory allocation APIs
+//!
+//! In a given program, the standard library has one “global” memory allocator
```
Comment (sfackler) [inline src/libstd/alloc.rs]: Some smart quotes snuck in here.

**Comment by sfackler** [comment]
Couple of doc nits, but LGTM!

File: src/libcore/alloc.rs [hunk 5]
```diff
@@ -392,59 +399,190 @@ impl From<AllocErr> for CollectionAllocErr {
...
     }
 
     /// Shink or grow a block of memory to the given `new_size`.
     /// The block is described by the given `ptr` pointer and `layout`.
     ///
-    /// Return a new pointer (which may or may not be the same as `ptr`),
-    /// or NULL to indicate reallocation failure.
+    /// If this returns a non-null pointer, then ownership of the memory block
+    /// referenced by `ptr` has been transferred to this alloctor.
+    /// The memory may or may not have been deallocated,
```
[the remark this answers is not in the document]
Comment (SimonSapin) [reply src/libcore/alloc.rs]: I’m not sure, I copied this form `Alloc::realloc` docs. Maybe when realloc succeeds in place and returns the same pointer? Would you rather I remove that sentence?

File: src/libstd/alloc.rs (hunk 4 above)
Comment (SimonSapin) [reply src/libstd/alloc.rs]: Is that bad?

File: src/libcore/alloc.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (SimonSapin) [reply src/libcore/alloc.rs]: I’m not sure, I copied this form `Alloc::realloc` docs. Maybe when realloc succeeds in place and returns the same pointer? Would you rather I remove that sentence?

File: src/libstd/alloc.rs (hunk 4 above)
Comment (steveklabnik) [reply src/libstd/alloc.rs]: We try to use smart quotes in the docs, but the API reference is all over the place. The book uses them 100%. Either way is fine by me.

**Comment by glandium** [comment]
Rebased.

**Comment by mark-i-m** [comment]
Does https://github.com/rust-lang/rust/issues/44113 need to be fixed before this is stabilized?

**Comment by sfackler** [comment]
@mark-i-m I don't think it needs to be fixed, but we should probably have a better error message.

**Comment by mark-i-m** [comment]
The current error happens simply because the current implementation causes weird hygeine bugs. I tried to fix it, but hygiene is hard. Neither I nor @alexcrichton knew how to fix it.

In the end, we agreed that maybe for now global_allocator should be disallowed in submodules. I started to implement that but ran into an error in #49320. If anyone has suggestions, I would be glad to fix that up and submit it.

**Comment by SimonSapin** [comment]
I think that #44113 should be fixed eventually, but that it doesn’t need to block stabilization.

**Comment by mark-i-m** [comment]
Ok. FWIW, I think I have #49320 working in #51335

**Comment by glandium** [comment]
Now that docs are up-to-date on https://doc.rust-lang.org/nightly/std/alloc/index.html, it feels like the docs for the reexports should be "inlined" (e.g. `alloc`, `alloc_zeroed`, `oom`), since the alloc crate is still unstable.

**Comment by SimonSapin** [comment]
@glandium Indeed. This is a rustdoc bug: https://github.com/rust-lang/rust/issues/51252. Maybe until that’s fixed we should explicitly re-export each item, but that leaves the opportunity to forget adding a re-export when a new item is added to `core::alloc` or `alloc::alloc`.
