### PR TITLE
Do not const prop unions

### LINKED ISSUE #121534: ICE: `invalid asymmetric binary op`
auto-reduced (treereduce-rust):
````rust
union union {
    union: u32,
    inion: i32,
    u8ion: u8,
    i64on: i64,
    u64on: u64,
}

pub fn main() {
    let union = union { union: 2 };
    let inion = union { inion: -2 };
    let mut mnion = union { inion: -16 };
    let m1 = unsafe { mnion.union };

    let u1 = unsafe { union.union };

    let u2 = unsafe { inion.union };

    let _r1 = u2 - u1 - m1;
}


````

original (gcc/testsuite/rust/compile/torture/union_union.rs) :
````rust
union union
{
  union: u32,
  inion: i32,
  u8ion: u8,
  i64on: i64,
  u64on: u64
}

pub fn main ()
{
  let union = union { union: 2 };
  let inion = union { inion: -2 };
  let mut mnion = union { inion: -16 };
  let m1 = unsafe { mnion.union };
  unsafe { mnion.union = union.union };
  let m2 = unsafe { mnion.inion };
  let u1 = unsafe { union.union };
  let i1 = unsafe { union.inion };
  let u2 = unsafe { inion.union };
  let i2 = unsafe { inion.inion };
  let _r1 = u2 - u1 - m1;
  let _r2 = i1 + i2 + m2;
  let _u8 = unsafe { union.u8ion };
  let _i64 = unsafe { union.i64on };
  let _u64 = unsafe { union.u64on };
}

````

Version information
````
rustc 1.78.0-nightly (8f359beca 2024-02-23)
binary: rustc
commit-hash: 8f359beca4e58bc3ae795a666301a8f47023044c
commit-date: 2024-02-23
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: type `union` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.lpSPfcSJdDgv/rustc_testrunner_tmpdir_reporting.PtvKbcdNLvuk/mvce.rs:1:7
  |
1 | union union {
  |       ^^^^^ help: convert the identifier to upper camel case (notice the capitalization): `Union`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: variable does not need to be mutable
  --> /tmp/icemaker_global_tempdir.lpSPfcSJdDgv/rustc_testrunner_tmpdir_reporting.PtvKbcdNLvuk/mvce.rs:12:9
   |
12 |     let mut mnion = union { inion: -16 };
   |         ----^^^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

error: internal compiler error: /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/compiler/rustc_const_eval/src/interpret/operator.rs:210:13: invalid asymmetric binary op Sub: 4294967294 (i32), 2 (u32)
 --> /tmp/icemaker_global_tempdir.lpSPfcSJdDgv/rustc_testrunner_tmpdir_reporting.PtvKbcdNLvuk/mvce.rs:9:1
  |
9 | pub fn main() {
  | ^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7fdc99bd4af6 - std::backtrace_rs::backtrace::libunwind::trace::h4d16db2f784877bc
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fdc99bd4af6 - std::backtrace_rs::backtrace::trace_unsynchronized::h584b4a9b0240fa46
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdc99bd4af6 - std::sys_common::backtrace::_print_fmt::hd30229489add2f78
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fdc99bd4af6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2c0d00d6b7d69808
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fdc99c25a7c - core::fmt::rt::Argument::fmt::hff9bfb4853f651d7
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/core/src/fmt/rt.rs:142:9
   5:     0x7fdc99c25a7c - core::fmt::write::h3421d3f24b10b162
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fdc99bc94bf - std::io::Write::write_fmt::hec18e9e87db322bb
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/io/mod.rs:1846:15
   7:     0x7fdc99bd48a4 - std::sys_common::backtrace::_print::hec336a3777e68e7b
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fdc99bd48a4 - std::sys_common::backtrace::print::hde3a6d5d13170337
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fdc99bd75eb - std::panicking::default_hook::{{closure}}::h4a4905d59aca1811
  10:     0x7fdc99bd7339 - std::panicking::default_hook::h33a18ce8d018f6fd
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/panicking.rs:292:9
  11:     0x7fdc9688467c - std[d1f7731e2ff5974d]::panicking::update_hook::<alloc[6711342ad6595d8]::boxed::Box<rustc_driver_impl[db1009755931a507]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fdc99bd7d50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h923e5082c0e2f790
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/alloc/src/boxed.rs:2030:9
  13:     0x7fdc99bd7d50 - std::panicking::rust_panic_with_hook::he294011ca89c3e63
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/panicking.rs:783:13
  14:     0x7fdc968b0d24 - std[d1f7731e2ff5974d]::panicking::begin_panic::<rustc_errors[8efb6f95facf2fed]::ExplicitBug>::{closure#0}
  15:     0x7fdc968adc46 - std[d1f7731e2ff5974d]::sys_common::backtrace::__rust_end_short_backtrace::<std[d1f7731e2ff5974d]::panicking::begin_panic<rustc_errors[8efb6f95facf2fed]::ExplicitBug>::{closure#0}, !>
  16:     0x7fdc968ad926 - std[d1f7731e2ff5974d]::panicking::begin_panic::<rustc_errors[8efb6f95facf2fed]::ExplicitBug>
  17:     0x7fdc968ba711 - <rustc_errors[8efb6f95facf2fed]::diagnostic::BugAbort as rustc_errors[8efb6f95facf2fed]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fdc96e55340 - rustc_middle[10e0138f1f482b76]::util::bug::opt_span_bug_fmt::<rustc_span[6ccc48fe7a4f1f83]::span_encoding::Span>::{closure#0}
  19:     0x7fdc96e5536a - rustc_middle[10e0138f1f482b76]::ty::context::tls::with_opt::<rustc_middle[10e0138f1f482b76]::util::bug::opt_span_bug_fmt<rustc_span[6ccc48fe7a4f1f83]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7fdc96e4e208 - rustc_middle[10e0138f1f482b76]::ty::context::tls::with_context_opt::<rustc_middle[10e0138f1f482b76]::ty::context::tls::with_opt<rustc_middle[10e0138f1f482b76]::util::bug::opt_span_bug_fmt<rustc_span[6ccc48fe7a4f1f83]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7fdc96e472e4 - rustc_middle[10e0138f1f482b76]::util::bug::span_bug_fmt::<rustc_span[6ccc48fe7a4f1f83]::span_encoding::Span>
  22:     0x7fdc9877d951 - <rustc_const_eval[57762c5f80ab379e]::interpret::eval_context::InterpCx<rustc_mir_transform[a8066d1d7333d1a3]::dataflow_const_prop::DummyMachine>>::overflowing_binary_op
  23:     0x7fdc98246015 - <rustc_mir_transform[a8066d1d7333d1a3]::known_panics_lint::ConstPropagator>::check_binary_op
  24:     0x7fdc95415d60 - <rustc_mir_transform[a8066d1d7333d1a3]::known_panics_lint::ConstPropagator as rustc_middle[10e0138f1f482b76]::mir::visit::Visitor>::visit_assign
  25:     0x7fdc9824765b - <rustc_mir_transform[a8066d1d7333d1a3]::known_panics_lint::ConstPropagator as rustc_middle[10e0138f1f482b76]::mir::visit::Visitor>::visit_body
  26:     0x7fdc9540de69 - <rustc_mir_transform[a8066d1d7333d1a3]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[a8066d1d7333d1a3]::pass_manager::MirLint>::run_lint
  27:     0x7fdc97c12289 - rustc_mir_transform[a8066d1d7333d1a3]::pass_manager::run_passes_inner
  28:     0x7fdc98363e06 - rustc_mir_transform[a8066d1d7333d1a3]::mir_drops_elaborated_and_const_checked
  29:     0x7fdc9836373d - rustc_query_impl[5f3fca9184d705d1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5f3fca9184d705d1]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10e0138f1f482b76]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7fdc97e6bc30 - rustc_query_system[3c44b3ad726fdf36]::query::plumbing::try_execute_query::<rustc_query_impl[5f3fca9184d705d1]::DynamicConfig<rustc_query_system[3c44b3ad726fdf36]::query::caches::VecCache<rustc_span[6ccc48fe7a4f1f83]::def_id::LocalDefId, rustc_middle[10e0138f1f482b76]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[5f3fca9184d705d1]::plumbing::QueryCtxt, false>
  31:     0x7fdc97e6b50c - rustc_query_impl[5f3fca9184d705d1]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fdc987ee1fa - rustc_interface[94ec20dfe64cdcea]::passes::analysis
  33:     0x7fdc987ed9d9 - rustc_query_impl[5f3fca9184d705d1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5f3fca9184d705d1]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10e0138f1f482b76]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7fdc98925643 - rustc_query_system[3c44b3ad726fdf36]::query::plumbing::try_execute_query::<rustc_query_impl[5f3fca9184d705d1]::DynamicConfig<rustc_query_system[3c44b3ad726fdf36]::query::caches::SingleCache<rustc_middle[10e0138f1f482b76]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[5f3fca9184d705d1]::plumbing::QueryCtxt, false>
  35:     0x7fdc989253bf - rustc_query_impl[5f3fca9184d705d1]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fdc98934896 - rustc_interface[94ec20dfe64cdcea]::interface::run_compiler::<core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>, rustc_driver_impl[db1009755931a507]::run_compiler::{closure#0}>::{closure#0}
  37:     0x7fdc98bcaa4d - std[d1f7731e2ff5974d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[94ec20dfe64cdcea]::util::run_in_thread_with_globals<rustc_interface[94ec20dfe64cdcea]::util::run_in_thread_pool_with_globals<rustc_interface[94ec20dfe64cdcea]::interface::run_compiler<core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>, rustc_driver_impl[db1009755931a507]::run_compiler::{closure#0}>::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>
  38:     0x7fdc98bca87a - <<std[d1f7731e2ff5974d]::thread::Builder>::spawn_unchecked_<rustc_interface[94ec20dfe64cdcea]::util::run_in_thread_with_globals<rustc_interface[94ec20dfe64cdcea]::util::run_in_thread_pool_with_globals<rustc_interface[94ec20dfe64cdcea]::interface::run_compiler<core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>, rustc_driver_impl[db1009755931a507]::run_compiler::{closure#0}>::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[bd87c62ae3a7b4ee]::result::Result<(), rustc_span[6ccc48fe7a4f1f83]::ErrorGuaranteed>>::{closure#1} as core[bd87c62ae3a7b4ee]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7fdc99be1725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h11737601996c7bc7
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/alloc/src/boxed.rs:2016:9
  40:     0x7fdc99be1725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb64bc4a2c7899523
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/alloc/src/boxed.rs:2016:9
  41:     0x7fdc99be1725 - std::sys::pal::unix::thread::Thread::new::thread_start::h9f6bca54366231ee
                               at /rustc/8f359beca4e58bc3ae795a666301a8f47023044c/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7fdc9387355a - <unknown>
  43:     0x7fdc938f0a3c - <unknown>
  44:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (8f359beca 2024-02-23) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error; 2 warnings emitted


```

</p>
</details>

### PR DESCRIPTION
**Pull request by gurry**
Unions can produce values whose types don't match their underlying layout types which can lead to ICEs on eval.

Fixes #121534

### CODE REVIEW

File: compiler/rustc_mir_transform/src/known_panics_lint.rs [hunk 1]
```diff
@@ -585,20 +585,32 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                };
+                Value::Aggregate {
+                    fields: fields
+                        .iter()
+                        .map(|field| {
+                            self.eval_operand(field).map_or(Value::Uninit, Value::Immediate)
+                        })
+                        .collect(),
+                    variant: match **kind {
+                        AggregateKind::Adt(_, variant, _, _, _) => variant,
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/known_panics_lint.rs:605]: could add the bail out logic here

Comment (gurry) [reply compiler/rustc_mir_transform/src/known_panics_lint.rs:605]: That was my first approach, but it looked ugly especially with that longish comment

**Comment by oli-obk** [comment]
r? oli-obk

@bors r+ rollup

File: compiler/rustc_mir_transform/src/known_panics_lint.rs [hunk 2]
```diff
@@ -585,20 +585,32 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
-                    AggregateKind::Adt(_, variant, _, _, _) => variant,
-                    AggregateKind::Array(_)
-                    | AggregateKind::Tuple
-                    | AggregateKind::Closure(_, _)
-                    | AggregateKind::Coroutine(_, _)
-                    | AggregateKind::CoroutineClosure(_, _) => VariantIdx::new(0),
-                },
-            },
+            Aggregate(ref kind, ref fields) => {
+                // Do not const pop union fields as they can be
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/known_panics_lint.rs:589]: "pop" -> "prop(agate)"

Comment (gurry) [reply compiler/rustc_mir_transform/src/known_panics_lint.rs:589]: Oops :p. Fixed in #121831

**Comment by cjgillot** [comment]
I suspect that this PR does not fully fix https://github.com/rust-lang/rust/issues/121534. From a glance, that ICE is caused by projecting a union field. This PR prohibits creating constants of union type in const-prop. We could still have constants of union type due to inline `const`s for instance.

**Comment by gurry** [comment]
> I suspect that this PR does not fully fix #121534. From a glance, that ICE is caused by projecting a union field. This PR prohibits creating constants of union type in const-prop. We could still have constants of union type due to inline `const`s for instance.

That makes sense, but I tested it and the eval of inline consts does not ICE 😑. 

This snippet, which is the one reported in #121534, does ICE:

```rust
union Union {
    u32_field: u32,
    i32_field: i32,
}

pub fn main() {
    let u32_variant = Union { u32_field: 2 };
    let i32_variant = Union { i32_field: 10 };
    let a = unsafe { u32_variant.u32_field };
    let b = unsafe { i32_variant.u32_field };

    let _diff = b - a;
}
```
(Plaground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9aa52ce49ce5c1a37bde946ab6e74631)

but this one, which evaluates an inline const with the exact same code in the body, does not:

```rust
union Union {
    u32_field: u32,
    i32_field: i32,
}

const C: u32 = {
    let u32_variant = Union { u32_field: 2 };
    let i32_variant = Union { i32_field: 10 };
    let a = unsafe { u32_variant.u32_field };
    let b = unsafe { i32_variant.u32_field };

    b - a
};

pub fn main() {
    let a = [3; C as usize];
    println!("{}", a.len())
}
```
(Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4bcf0f59f14964a9c090aa8bdc2d043e)

In fact, not only does it not ICE, it prints the correct value of `8`.

I've looked into the location where the ICE originates in `bin_int_op()`: https://github.com/rust-lang/rust/blob/548e14b43963882fb758deb89e8258d9b8c2fc2a/compiler/rustc_const_eval/src/interpret/operator.rs#L209

and found that in the first case the layout tys of the operands passed to this method are different (`left_layout.ty` is `i32` and `right_layout.ty` is `u32`), but in the second case they are the same (both `u32`). I have not investigated further as to why this is. Perhaps some accidental twist of type inference.

@cjgillot If you can share a different reproducer, I can try again.
