### PR TITLE
Fix primitive search in parameters and returned values

### LINKED ISSUE #74780: Type-based search does not work for primitives since March
searched nightlies: from nightly-2019-05-02 to nightly-2020-07-17
regressed nightly: nightly-2020-03-20
searched commits: from https://github.com/rust-lang/rust/commit/f509b26a7730d721ef87423a72b3fdf8724b4afa to https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8
regressed commit: https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script ./search_works.sh --start 2019-05-02 --preserve 
```

search_works.sh:

```
#!/bin/sh
set -eu
rustdoc search_function_type.rs
node ~/rustc/src/tools/rustdoc-js/tester.js --doc-folder doc --crate-name search_function_type --test-file ~/rustc/src/test/rustdoc-js/tmp/search-function-type.js
```

search_function_type.rs:

```
/// f
pub fn f(u: usize) -> usize {
    u
}
```

search-function-type.js:

```js
const QUERY = 'usize -> usize';

const EXPECTED = {
    'in_args': [
        { 'path': 'search_function_type', 'name': 'f' },
    ],
};
```

This requires a git clone of rustc as well as the following modification to `tester.js`:

```
diff --git a/src/tools/rustdoc-js/tester.js b/src/tools/rustdoc-js/tester.js
index 139e6f73f42..8a3ab056f80 100644
--- a/src/tools/rustdoc-js/tester.js
+++ b/src/tools/rustdoc-js/tester.js
@@ -182,7 +182,7 @@ function loadThings(thingsToLoad, kindOfLoad, funcToCall, fileContent) {
         var tmp = funcToCall(fileContent, thingsToLoad[i]);
         if (tmp === null) {
             console.log('unable to find ' + kindOfLoad + ' "' + thingsToLoad[i] + '"');
-            process.exit(1);
+            continue;
         }
         content += tmp;
         content += 'exports.' + thingsToLoad[i] + ' = ' + thingsToLoad[i] + ';';
```

</details>

Originally reported in https://github.com/rust-lang/rust/issues/60485#issuecomment-663900624.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #60485.
Fixes #74780.

Replacing #74879.

cc @camelid @jyn514 @CraftSpider 
r? @ollie27

### CODE REVIEW

File: src/librustdoc/clean/utils.rs [hunk 1]
```diff
@@ -176,6 +176,15 @@ crate fn get_real_types(
...
     }
+    fn insert(res: &mut FxHashSet<(Type, TypeKind)>, cx: &DocContext<'_>, ty: Type) {
+        if let Some(kind) = ty.def_id().map(|did| cx.tcx.def_kind(did).clean(cx)) {
+            res.insert((ty, kind));
+        } else {
+            // This is a primitive, let's store it as such.
+            res.insert((ty, TypeKind::Primitive));
+        }
+    }
+
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:187]: Do you think it makes sense to move this inner function to the start of the enclosing function? It seems confusing to have it wedged in the middle of some code.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:187]: Oh damn, you're absolutely right. Moving it to the top!

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by camelid** [comment]
Btw, I'm not sure if ollie27 is still doing reviews.

**Comment by ollie27** [comment]
Looks good.

@bors r+

**Comment by ollie27** [comment]
Actually this isn't quite right @bors r-

File: src/librustdoc/clean/utils.rs [hunk 2]
```diff
@@ -171,11 +171,20 @@ crate fn get_real_types(
     cx: &DocContext<'_>,
     recurse: i32,
 ) -> FxHashSet<(Type, TypeKind)> {
+    fn insert(res: &mut FxHashSet<(Type, TypeKind)>, cx: &DocContext<'_>, ty: Type) {
+        if let Some(kind) = ty.def_id().map(|did| cx.tcx.def_kind(did).clean(cx)) {
+            res.insert((ty, kind));
+        } else {
+            // This is a primitive, let's store it as such.
```
Comment (ollie27) [inline src/librustdoc/clean/utils.rs:178]: This isn't always a primitive. `ty.def_id()` will return `None` for generic parameters as well which shouldn't end up the in the search index.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:178]: Great catch! I'll fix that and add a test to ensure they're not listed.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:178]: Actually no because we check before if it's a full generic. So it should never be the case. I'll add a test to ensure it though.

**Comment by GuillaumeGomez** [comment]
@ollie27 I extended the test to ensure that generics are not added into the search index.

File: src/librustdoc/clean/utils.rs (hunk 2 above)
Comment (ollie27) [reply src/librustdoc/clean/utils.rs:178]: `is_full_generic` will only return true for generics passed by value. Generics passed by reference like `pub fn foo<T>(x: &T) {}` or `&self` show up in the search index with this PR.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:178]: I see. I'll add a `is_primitive` method then to ensure that.

**Comment by GuillaumeGomez** [comment]
@ollie27 Re-updated the test to test generics behind reference and added the `is_primitive` method.

**Comment by ollie27** [comment]
Yep, that looks better @bors r+

**Comment by GuillaumeGomez** [comment]
Thanks for the improvement! :)

File: src/librustdoc/html/render/cache.rs [hunk 3]
```diff
@@ -78,7 +78,7 @@ crate fn build_index(krate: &clean::Crate, cache: &mut Cache) -> String {
                 desc: item.doc_value().map_or_else(String::new, |s| short_markdown_summary(&s)),
                 parent: Some(did),
                 parent_idx: None,
-                search_type: get_index_search_type(&item, None),
+                search_type: get_index_search_type(&item, Some(cache)),
```
Comment (CraftSpider) [inline src/librustdoc/html/render/cache.rs:81]: Just to make sure I understand what is happening here: This adds primitives to the cache, because now in an earlier stage they are being properly added to the cache via the new `insert` method? And previously this wasn't used because... Cache wasn't working right on them, I'm guessing?

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/cache.rs:81]: Exactly. To be more precise: the cache here is needed to get the `DefId` of primitive types. If we don't have primitives, we don't need cache (and before that we didn't get the primitives in the cache). So you got it exactly rght. :)
