### PR TITLE
Replace associated item bound vars with placeholders when projecting

### LINKED ISSUE #76407: Associated type constraint fails, even if it implements requested trait
Associated type constraint fails, even if it implements requested trait. In the example below, requested trait is `Marker`, `u32` implements it, `<MyStruct as MyTrait>::Item<'a> == u32`, but `<MyStruct as MyTrait>::Item<'a>: Marker` does not pass. (Everything is ok with `<'a>` removed)

The code:

```rust
#![allow(incomplete_features)]
#![feature(generic_associated_types)]

trait Marker {}

impl Marker for u32 {}

trait MyTrait {
    type Item<'a>;
}

struct MyStruct;

impl MyTrait for MyStruct {
    type Item<'a> = u32;
}

fn ty_check<T>()
where
    T: MyTrait,
    for<'a> T::Item<'a>: Marker
{}

fn main() {
    ty_check::<MyStruct>();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (cdc8f0606 2020-09-05)
binary: rustc
commit-hash: cdc8f0606d0f3c4f3866643382c8a5776d1bdaed
commit-date: 2020-09-05
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

### LINKED ISSUE #76826: ICE when combining GATs and HRTBs
The following code triggers an ICE.

### Code

```Rust
#![feature(generic_associated_types)]

pub trait Iter {
    type Item<'a> where Self: 'a;
    
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;
    
    fn for_each<F>(mut self, mut f: F)
        where Self: Sized, F: for<'a> FnMut(Self::Item<'a>)
    {
        while let Some(item) = self.next() {
            f(item);
        }
    }
}

pub struct Windows<T> {
    items: Vec<T>,
    start: usize,
    len: usize,
}

impl<T> Windows<T> {
    pub fn new(items: Vec<T>, len: usize) -> Self {
        Self { items, start: 0, len }
    }
}

impl<T> Iter for Windows<T> {
    type Item<'a> where T: 'a = &'a mut [T];
    
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        let slice = self.items.get_mut(self.start..self.start + self.len)?;
        self.start += 1;
        Some(slice)
    }
}

fn main() {
    Windows::new(vec![1, 2, 3, 4, 5], 3)
        .for_each(|slice| println!("{:?}", slice));
}
```

[Playground version](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5fc1a17b6b474bca1e584071b06a4613)

This example can no doubt be minimised further, but it should be obvious what I'm attempting to do and why. This would be, I assume, a fairly common use-case for GATs and are likely to be essential if GATs are ever to be integrated into `Iterator`.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (d006f5734 2020-08-28)
```

### Error output

```
error: internal compiler error: src/librustc_trait_selection/traits/codegen/mod.rs:75:17: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(<Windows<i32> as Iter>::Item<'_>,)>>), Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>), Sorts(ExpectedFound { expected: &mut [i32], found: <Windows<i32> as Iter>::Item<'_> }))` selecting `Binder(<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_infer::infer::InferCtxtBuilder::enter
   9: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::codegen_fulfill_obligation>::compute
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::get_query_impl
  14: rustc_ty::instance::inner_resolve_instance
  15: rustc_ty::instance::resolve_instance
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::resolve_instance>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::get_query_impl
  20: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  21: rustc_middle::ty::instance::Instance::resolve
  22: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  23: rustc_mir::monomorphize::collector::collect_neighbours
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
  27: rustc_mir::monomorphize::collector::collect_crate_mono_items
  28: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  30: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  31: rustc_data_structures::stack::ensure_sufficient_stack
  32: rustc_query_system::query::plumbing::get_query_impl
  33: rustc_codegen_ssa::base::codegen_crate
  34: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  35: rustc_interface::passes::QueryContext::enter
  36: rustc_interface::queries::Queries::ongoing_codegen
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  38: rustc_span::with_source_map
  39: rustc_interface::interface::create_compiler_and_run
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-nightly (d006f5734 2020-08-28) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::FnMut` fulfills its obligations
#1 [resolve_instance] resolving instance `<[closure@gats.rs:41:19: 41:50] as std::ops::FnMut<(&mut [i32],)>>::call_mut`
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

Removing the final line (`.for_each(|slice| println!("{:?}", slice))`) prevents the ICE, implying that this is a codegen issue (as corroborated by the stack trace).

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #76407
Fixes #76826

Similar, but more limited, to #85499. This allows us to handle things like `for<'a> <T as Trait>::Assoc<'a>` but not `for<'a> <T as Trait<'a>>::Assoc`, unblocking GATs.

r? @nikomatsakis

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 1]
```diff
@@ -410,6 +459,259 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+        match *r {
+            ty::ReLateBound(debruijn, br) => {
+                let infcx = self.infcx;
+                let placeholder_db_index =
+                    ty::DebruijnIndex::from_u32(self.current_index.as_u32() - debruijn.as_u32());
+                let universe = *self
+                    .universes
+                    .entry(placeholder_db_index)
+                    .or_insert_with(|| infcx.create_next_universe());
+                self.universes_inverse.insert(universe, placeholder_db_index);
```
Comment (jackh726) [inline compiler/rustc_trait_selection/src/traits/project.rs:534]: This logic is wrong.

For one, if there are two binders at the same "level" (think something like `( for<'a> fn(&'a ()), for<'b> fn(&'b ()) )`), then those would get assigned to a same universe.

Second, if there *escaping* vars, then we underflow here. I misinterpreted the error from the crater reports (or my fix exposed this problem).

The second issue is a pretty simple fix, I think. The first, I have to think more about.

File: compiler/rustc_trait_selection/src/traits/query/normalize.rs [hunk 2]
```diff
@@ -204,6 +216,80 @@ impl<'cx, 'tcx> TypeFolder<'tcx> for QueryNormalizer<'cx, 'tcx> {
...
+                let infcx = self.infcx;
+                let replaced = crate::traits::project::BoundVarReplacer::replace_bound_vars(
+                    infcx,
+                    &mut self.universes,
+                    data,
+                );
+                let (data, mapped_regions, mapped_types, mapped_consts) = match replaced {
+                    Some(r) => r,
+                    None => {
+                        bug!("{:?} {:?}", data, self.universes);
```
Comment (jackh726) [inline compiler/rustc_trait_selection/src/traits/query/normalize.rs:239]: Oh...hmm. interesting. Didn't mean to leave this. But since all the tests pass, maybe the only place that we pass escaping bound vars here is under polymorphization (and supposedly there's no test for the intersection of polymorphization and GATs). But the underlying problem still exists (normalize_erasing_regions). So not sure if it's better to just ICE if we get passed bound vars (gives us test cases) or to fail and return an error (which might still allow us to succeed compilation overall).

Thoughts @nikomatsakis?

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 3]
```diff
@@ -396,6 +413,56 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+                        self.selcx,
+                        self.param_env,
+                        data,
+                        self.cause.clone(),
+                        self.depth,
+                        &mut self.obligations,
+                    )
+                    .ok()
+                    .flatten()
+                    .unwrap_or_else(|| ty);
```
Comment (klensy) [inline compiler/rustc_trait_selection/src/traits/project.rs:443]:
```suggestion
                    .unwrap_or(ty);
```

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 4]
```diff
@@ -396,6 +398,53 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+                // known enough), we *can't* register an obligation and return
+                // an inference variable (since then that obligation would have
+                // bound vars and that's a can of worms). Instead, we just
+                // give up and fall back to pretending like we never tried!
+
+                let infcx = self.selcx.infcx();
+                let (data, mapped_regions, mapped_types, mapped_consts, universe_map) =
+                    BoundVarReplacer::replace_bound_vars(infcx, data);
+
+                let normalized_ty = opt_normalize_projection_type(
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs]: I feel like we should do this in a "infcx probe"; it could have side-effects on inference variables and the like otherwise.

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 5]
```diff
@@ -308,12 +309,16 @@ impl<'a, 'b, 'tcx> AssocTypeNormalizer<'a, 'b, 'tcx> {
...
     }
 
     fn fold<T: TypeFoldable<'tcx>>(&mut self, value: T) -> T {
         let value = self.selcx.infcx().resolve_vars_if_possible(value);
 
+        if value.has_escaping_bound_vars() {
+            bug!("Normalizing without wrapping in a `Binder`");
+        }
+
         if !value.has_projections() { value } else { value.fold_with(self) }
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:322]: we should really rewrite this to a loop, shouldn't we? :)

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 6]
```diff
@@ -542,15 +581,24 @@ impl TypeFolder<'tcx> for BoundVarReplacer<'_, 'tcx> {
...
-                    ty::DebruijnIndex::from_u32(self.current_index.as_u32() - debruijn.as_u32());
-                let universe = *self
-                    .universes
-                    .entry(placeholder_db_index)
-                    .or_insert_with(|| infcx.create_next_universe());
-                self.universes_inverse.insert(universe, placeholder_db_index);
+                let index = self.universe_indices.len() - debruijn.as_usize()
+                    + self.current_index.as_usize()
+                    - 1;
+                let universe = self.universe_indices[index].unwrap_or_else(|| {
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:596]: please encapsulate this in a function =)

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 7]
```diff
@@ -562,15 +610,26 @@ impl TypeFolder<'tcx> for BoundVarReplacer<'_, 'tcx> {
...
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:627]: called here

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 8]
```diff
@@ -523,15 +553,24 @@ impl TypeFolder<'tcx> for BoundVarReplacer<'_, 'tcx> {
...
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:568]: and here

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 9]
```diff
@@ -412,37 +427,40 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
-                    ?ty,
-                    ?normalized_ty,
-                    obligations.len = ?self.obligations.len(),
-                    "AssocTypeNormalizer: normalized type"
-                );
-                normalized_ty
+                let replaced =
+                    BoundVarReplacer::replace_bound_vars(infcx, &mut self.universes, data);
+                if let Some((data, mapped_regions, mapped_types, mapped_consts)) = replaced {
+                    let normalized_ty = opt_normalize_projection_type(
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:433]: I think we should use a call to [`commit_if_ok`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.commit_if_ok) here, so that we unroll the inference effects in the event of error or ambiguity. We'd have to translate `Option` to `Error` though

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 10]
```diff
@@ -460,26 +478,42 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+    // we don't actually create a universe until we see a bound var we have to replace.
+    universe_indices: &'me mut Vec<Option<ty::UniverseIndex>>,
+    // FIXME: So, this is a less-than-ideal solution to a problem we want to solve eventually. Ideally, we
+    // shouldn't need to worry about bound vars for which we haven't passed (`self.current_index`)
+    // or that we don't explicitly know about (`self.universe_indices`). This is true for
+    // `AssocTypeNormalizer` but not `QueryNormalizer` currently. When we can always know about
+    // any binding levels above us, we can remove this. (The alternative would be
+    // `outer_exclusive_binder`, but that only exists on `Ty`. Otherwise, we would have to visit
+    // through the `T`, which we specifically want to avoid not being lazy.)
+    failed: bool,
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:501]: As discussed on Zulip, replace this with an assertion (or an `if`) to prevent us from getting into this code in the first place.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 11]
```diff
@@ -396,6 +415,55 @@ impl<'a, 'b, 'tcx> TypeFolder<'tcx> for AssocTypeNormalizer<'a, 'b, 'tcx> {
...
+                    BoundVarReplacer::replace_bound_vars(infcx, &mut self.universes, data);
+                let normalized_ty = infcx
+                    .commit_if_ok(|_| {
+                        opt_normalize_projection_type(
+                            self.selcx,
+                            self.param_env,
+                            data,
+                            self.cause.clone(),
+                            self.depth,
+                            &mut self.obligations,
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/project.rs:442]: Wait, something seems wrong here. Maybe I was wrong to suggest the `commit_if_ok`. 

In the event that `Ok(None)` is returned, I believe we already guarantee that `opt_normalize_projection_type` doesn't modify the inference state.

In the event that `Err` is returned, we will push things into `self.obligations`. If we're going to use `commit_if_ok`, we'd have to ensure that those things are removed, or else they are leaking through a transaction, and that's a bug.

I don't think it actually matters, though, it things *do* leak out in the case of an error. The only thing we push in there is an obligation to prove that the trait-ref holds, and it's ok for that to go on and be proven with the placeholders. This actually holds for any obligations that get pushed.

The case I was worried  about was something like: we return a type whose value will be informed b solving those obligations, but then we abandon it and use `ty` instead. But that just doesn't happen.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/ui/issues/issue-20831-debruijn.stderr [hunk 12]
```diff
@@ -15,10 +15,10 @@ note: ...but the lifetime must also be valid for the lifetime `'a` as defined on
...
    |      ^^
 note: ...so that the types are compatible
-  --> $DIR/issue-20831-debruijn.rs:28:33
+  --> $DIR/issue-20831-debruijn.rs:28:8
    |
 LL |     fn subscribe(&mut self, t : Box<dyn Subscriber<Input=<Self as Publisher>::Output> + 'a>) {
-   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   |        ^^^^^^^^^
    = note: expected `Publisher<'_>`
               found `Publisher<'_>`
```
Comment (estebank) [inline src/test/ui/issues/issue-20831-debruijn.stderr:23]: Sad about the output change in this case :(

Comment (jackh726) [reply src/test/ui/issues/issue-20831-debruijn.stderr:23]: Yeah, these changes are caused by liberating late bound regions *before* normalizing in `wfcheck` (see #87113). Honestly though, neither output is *great*, but it definitely got a bit worse.

**Comment by pnkfelix** [comment]
Just a heads-up: This PR was flagged as causing [regressions](https://perf.rust-lang.org/compare.html?start=b1f8e27b74c541d3d555149c8efa4bfe9385cd56&end=27e42058811e448b1a7dd8630d86ab247fbfcb9b&stat=instructions%3Au), up to 1.5% on style-servo-debug and wf-projection-stress-65510-{opt,check,debug}.

The results overall seem somewhat mixed to me: On a bunch of other benchmarks there were (smallish) wins. So it may all just be noise.

**Comment by pnkfelix** [comment]
Also, someone mentioned to me that when you do [a performance run](https://github.com/rust-lang/rust/pull/86993#issuecomment-876999688), it is good form to make some sort of note about the outcome, especially when its been tagged as a significant regression, so that others reviewing the pull request in the future will now how to interpret what action, if any, was taken in response to the performance run. If you revise the PR to address perf warnings, say so! Or, if we're choosing to land a PR despite the perf warnings, that's fine, but its good to know what the justification is.

**Comment by jackh726** [comment]
Good point @pnkfelix.

The perf run I had done matched about what I had seen in #85499, so I wasn't surprised (the thought was that the regression here probably would have canceled out the future regression there). On that PR, I've tried digging into to the regression I saw and really didn't get anywhere. I guess the couple commits that I added after the perf run was done changed the perf results a good amount. I would definitely lean towards these being noise or something that can't be easily fixed without some detailed fine tuning.

**Comment by rylev** [comment]
@jackh726 None of the testcases that showed regressions show noise historically so while noise is still possible, it's unlikely. I'll go ahead and mark this as being addressed since you said you looked into and did not see any easy and obvious ways to address the regression. We're still working through what exactly the process should be in cases like this where the regression is fairly minor. 

@rustbot label +perf-regression-triaged
