### PR TITLE
resolve: collect trait aliases along with traits

### LINKED ISSUE #56485: Bringing a trait alias into scope doesn't allow calling methods from its component traits
```rust
#![feature(trait_alias)]

mod some_module {
    pub trait Foo {
        fn foo(&self);
    }
    
    pub struct Qux;
    
    impl Foo for Qux {
        fn foo(&self) {}
    }
    
    pub trait Bar = Foo;
}

use some_module::{Bar, Qux};

fn use_baz(object: Qux) {
    // Should this work because Bar is in scope?
    object.foo();
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=169f5809b367991b8a9547b424eefe1e)) currently produces an error:

```
error[E0599]: no method named `foo` found for type `some_module::Qux` in the current scope
  --> src/lib.rs:21:12
   |
8  |     pub struct Qux;
   |     --------------- method `foo` not found for this
...
21 |     object.foo();
   |            ^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
17 | use some_module::Foo;
   |
```

cc #41517

### PR DESCRIPTION
**Pull request by seanmonstar**
It seems trait aliases weren't being collected as `TraitCandidates` in resolve, this should change that. (I can't compile the full compiler locally, so relying on CI...)

Fixes https://github.com/rust-lang/rust/issues/56485

r? @alexreg

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -4865,6 +4874,7 @@ impl<'a> Resolver<'a> {
             (TypeNS, _) if old_binding.is_extern_crate() => "extern crate",
             (TypeNS, Some(module)) if module.is_normal() => "module",
             (TypeNS, Some(module)) if module.is_trait() => "trait",
+            (TypeNS, Some(module)) if module.is_trait_alias() => "trait alias",
```
Comment (seanmonstar) [inline src/librustc_resolve/lib.rs]: There's a possible other pattern to add in https://github.com/rust-lang/rust/pull/59166/files#diff-aeb0880081a991f34aef2ab889e1fb7aR4848, but I can't for the life of me figure out how you could be resolve imports inside a trait.

Comment (alexreg) [reply src/librustc_resolve/lib.rs]: Inside a trait alias you mean? Yeah, I can't see how either. Still, just in *case* (you don't want it falling back to "enum" for a trait alias, even if it's just a bug), let's add this case.

File: src/test/run-pass/traits/trait-alias-import.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    pub struct Qux;
+
+    impl Foo for Qux {
+        fn foo(&self) {}
+    }
+
+    pub trait Bar = Foo;
+}
+
+// import only the alias, not the `Foo` trait
```
Comment (alexreg) [inline src/test/run-pass/traits/trait-alias-import.rs]:
```suggestion
// Import only the alias, not the `Foo` trait.
```
(I'm a grammar Nazi, I know...)

File: src/librustc_resolve/lib.rs (hunk 1 above)
Comment (seanmonstar) [reply src/librustc_resolve/lib.rs]: No no, I don't even know the regular `trait` case could happen. There's no way to `use Something` inside `trait Wee { .. }` (except inside a function, which I assume is the `Block` case).

Comment (alexreg) [reply src/librustc_resolve/lib.rs]: Yeah, I agree... it doesn't seem possible. Maybe this is just future-proofing it? Add it in, since it can't hurt, I say!

**Comment by alexreg** [comment]
@seanmonstar Okay, all looks good. Thanks for the PR! I'll r+ when CI passes.

Is there any case concerning the importing of trait aliases that you think should be supported but still isn't, after this PR?

**Comment by seanmonstar** [comment]
> Is there any case concerning the importing of trait aliases that you think should be supported but still isn't, after this PR?

I'd love some sort of late bounds on associated types that are themselves generic. Like this example:

```rust
trait Svc<Req> {
    type Res;
}

mod http {
    struct Req;
    struct Res<B>(pub B);

    trait Body {}

    trait HttpSvc = <B> super::Svc<Req, Res = Res<B>> {
        type Res = B;
    }
}
```

I'd need some way to propagate the body generic out of the `Res<B>`, but without requiring the generic on the `HttpSvc` itself (so not `HttpSvc<B>`), since it's based on an associated type.

**Comment by seanmonstar** [comment]
Oh noes, those errors... too bad the tests aren't run with `RUST_BACKTRACE=1`, I've no idea where those `unwrap`s are...

**Comment by alexreg** [comment]
Weird... Bors didn't auto-cancel this PR.

@bors r-

**Comment by alexreg** [comment]
@seanmonstar Poke me once you have the backtraces for those errors.

**Comment by alexreg** [comment]
> I'd love some sort of late bounds on associated types that are themselves generic. ...

I think you're talking [generic associated types](https://github.com/rust-lang/rust/issues/44265), unless I'm mistaken? This feature has been in the works for a while now, and should be in nightly in the coming months, we hope, though it's hard to predict exactly.

File: src/librustc_resolve/lib.rs (hunk 1 above)
Comment (petrochenkov) [reply src/librustc_resolve/lib.rs]: `report_conflict` is used for conflicts not involving imports as well, e.g.
```rust
trait Tr {
    fn foo();
    fn foo(); // ERROR the name `foo` is defined multiple times
}
```
, so `module.is_trait()` can occur.

Comment (petrochenkov) [reply src/librustc_resolve/lib.rs]: `module.is_trait_alias()` on the other hand cannot occur because trait aliases are not `Module`s in resolve sense, unlike traits.
(Only `Mod`s, `Enum`s and `Trait`s are `Module`s.)

Comment (petrochenkov) [reply src/librustc_resolve/lib.rs]: The whole `match` should be replaceable with `old_binding.descr()`, I think.

**Comment by petrochenkov** [comment]
@seanmonstar 
Support for resolving methods from traits in scope contains from two components - collecting the traits in scope (this PR does that), and then processing the collected traits in `fn assemble_extension_candidates_for_traits_in_scope` and looks like that function is not prepared to encounter trait *aliases* in the list yet.

**Comment by petrochenkov** [comment]
>petrochenkov unassigned alexreg just now

(The unassignment is unintentional and looks like it's performed automatically by GitHub as a side effect of blocking.)

**Comment by davidbarsky** [comment]
@seanmonstar I was able to build and test your branch. I've pasted the test [failures into a gist](https://gist.github.com/davidbarsky/4b947c920666ab9f3715e8e47016ce86).

**Comment by alexreg** [comment]
Thanks for that, @davidbarsky. Yes, the error is clearly occurring in `get_traits_in_module_containing_item` in `rustc_resolve`.

@seanmonstar So, I *think* the issue is that during the assembly of the map of all traits, trait aliases is being ignored. Take a look at `compute_all_traits` in `src/librustc_typeck/check/method/suggest.rs`

Specifically, I think you want to modify

```rust
        fn visit_item(&mut self, i: &'v hir::Item) {
            if let hir::ItemKind::Trait(..) = i.node {
                let def_id = self.map.local_def_id_from_hir_id(i.hir_id);
                self.traits.push(def_id);
            }
        }
```

to account for `ItemKind::TraitAlias` too. That may be enough.

**Comment by seanmonstar** [comment]
So I've managed to get the compiler building, and have since gone down a rabbit hole figuring this out:

- Even though I'd modified `visit_item` and such, the `get_traits_in_module_containing_item` won't ever return it because a trait alias never contains anything.
- I learned how the compiler resolves an alias when there's `fn foo<T: SomeAlias>`, by treating all the aliased traits as "super" traits in `rustc_typeck::check::method::probe::elaborate_bounds`.

So I'm thinking about next steps, possibly one of these is better:
- I could try to do something like elaborate bounds for trait aliases in `rustc_resolve`, but it doesn't do that for anything else, and it may be out of place.
- In `get_traits_id_module_containing_item`, I could just slurp all imported aliases without checking if they contain the item, and then in `probe`, try to elaborate bounds if the candidate is an alias.

Are both of those too crazy?

**Comment by seanmonstar** [comment]
I went for the second option, which got the one new run-pass test passing. I'm still a little iffy about it, and there should probably be some more compile-fail tests added. That come to mind:

- That a type that implements part of the alias but not all doesn't have it's methods resolved.
- Does this pollute resolution/probing for other types in the same module?

File: src/librustc_typeck/check/method/probe.rs [hunk 3]
```diff
@@ -895,20 +895,46 @@ impl<'a, 'gcx, 'tcx> ProbeContext<'a, 'gcx, 'tcx> {
...
         let trait_ref = ty::TraitRef::new(trait_def_id, trait_substs);
 
-        for item in self.impl_or_trait_item(trait_def_id) {
-            // Check whether `trait_def_id` defines a method with suitable name:
-            if !self.has_applicable_self(&item) {
-                debug!("method has inapplicable self");
-                self.record_static_candidate(TraitSource(trait_def_id));
-                continue;
+        // If a trait alias, elaborate its bounds magically...
+        // TODO? figure out a better way to determine if this is an alias
```
Comment (alexreg) [inline src/librustc_typeck/check/method/probe.rs]: Try using the `tcx.is_trait_alias` method instead, which I wrote in a previous PR. It works cross-crate, which this doesn't.

File: src/librustc_typeck/check/method/suggest.rs [hunk 4]
```diff
@@ -731,9 +731,13 @@ fn compute_all_traits<'a, 'gcx, 'tcx>(tcx: TyCtxt<'a, 'gcx, 'tcx>) -> Vec<DefId>
 
     impl<'v, 'a, 'tcx> itemlikevisit::ItemLikeVisitor<'v> for Visitor<'a, 'tcx> {
         fn visit_item(&mut self, i: &'v hir::Item) {
-            if let hir::ItemKind::Trait(..) = i.node {
-                let def_id = self.map.local_def_id_from_hir_id(i.hir_id);
-                self.traits.push(def_id);
+            match i.node {
+                hir::ItemKind::Trait(..) |
+                hir::ItemKind::TraitAlias(..) => {
```
Comment (alexreg) [inline src/librustc_typeck/check/method/suggest.rs]: Don't forget the cross-crate case below.

File: src/librustc_typeck/check/method/probe.rs [hunk 5]
```diff
@@ -895,20 +895,46 @@ impl<'a, 'gcx, 'tcx> ProbeContext<'a, 'gcx, 'tcx> {
...
 
-            let (xform_self_ty, xform_ret_ty) =
-                self.xform_self_ty(&item, trait_ref.self_ty(), trait_substs);
-            self.push_candidate(Candidate {
-                xform_self_ty, xform_ret_ty, item, import_id,
-                kind: TraitCandidate(trait_ref),
-            }, false);
+        if is_trait_alias {
+            debug!("assemble_extension_candidates_for_trait; no items, assuming alias, elaborating bounds");
+            self.elaborate_bounds(iter::once(trait_ref.to_poly_trait_ref()), |this, new_trait_ref, item| {
```
Comment (alexreg) [inline src/librustc_typeck/check/method/probe.rs]: I think this call is right, but I'm no expert on this area, so perhaps someone else can confirm.

File: src/librustc_typeck/check/method/probe.rs [hunk 6]
```diff
@@ -944,6 +970,8 @@ impl<'a, 'gcx, 'tcx> ProbeContext<'a, 'gcx, 'tcx> {
             return r;
         }
 
+        debug!("pick actual search failed, assemble diagnotics");
```
Comment (alexreg) [inline src/librustc_typeck/check/method/probe.rs]:
```suggestion
        debug!("pick: actual search failed; assemble diagnostics");
```

File: src/librustc_typeck/check/method/probe.rs [hunk 7]
```diff
@@ -895,20 +895,46 @@ impl<'a, 'gcx, 'tcx> ProbeContext<'a, 'gcx, 'tcx> {
...
+        };
 
-            let (xform_self_ty, xform_ret_ty) =
-                self.xform_self_ty(&item, trait_ref.self_ty(), trait_substs);
-            self.push_candidate(Candidate {
-                xform_self_ty, xform_ret_ty, item, import_id,
-                kind: TraitCandidate(trait_ref),
-            }, false);
+        if is_trait_alias {
+            debug!("assemble_extension_candidates_for_trait; no items, assuming alias, elaborating bounds");
```
Comment (alexreg) [inline src/librustc_typeck/check/method/probe.rs]: No need to keep this debug line around, I think...

**Review by alexreg — CHANGES_REQUESTED** [review]
Good work. I think this is roughly the right approach, though I'll wait for someone else to confirm. See my suggestions in any case.

**Comment by alexreg** [comment]
@seanmonstar

Oh, and not sure if you noticed, but your previous build failed early because of tidy checks -- so just wrap these lines.
```
[00:03:39] tidy error: /checkout/src/librustc_typeck/check/method/probe.rs:899: TODO is deprecated; use FIXME
[00:03:39] tidy error: /checkout/src/librustc_typeck/check/method/probe.rs:911: line longer than 100 chars
[00:03:39] tidy error: /checkout/src/librustc_typeck/check/method/probe.rs:912: line longer than 100 chars
[00:03:39] tidy error: /checkout/src/librustc_resolve/lib.rs:4393: line longer than 100 chars
[00:03:39] tidy error: /checkout/src/librustc_resolve/lib.rs:4412: line longer than 100 chars
[00:03:40] some tidy checks failed
```

**Comment by seanmonstar** [comment]
Updated.

**Comment by alexreg** [comment]
@seanmonstar Thanks. This basically looks okay to me.

Would someone else who is more familiar with this bit of code mind confirming everything is good?

**Comment by alexreg** [comment]
@seanmonstar I had another look, and this seems good to go. So, unless someone else sees a problem and wants to step in, I think it's safe to merge this. Could you tick the box giving maintainers push rights to your repo (or just add me manually) so I could push some very minor changes though? Thanks.

**Comment by seanmonstar** [comment]
It is checked.

(I have an internal worry that I have no idea how the trait resolver fully works and I've horribly broken something XD. Does that go away eventually?)

**Comment by alexreg** [comment]
@seanmonstar Weird. Mind adding me explicitly for that branch?

And yes, that feeling is natural with many parts of the Rust codebase, hah. We'll give it until tomorrow in case a real expert comes by and spots something the matter, but like I said, I *think* everything is in order. At worst, there are efficiency gains to be made, but there's no soundness violation or regression as far as I can tell.

**Comment by alexreg** [comment]
@bors r+

@seanmonstar Thanks! Good work on this. I'll try to keep an eye on issues in case any surprising consequences to name/trait resolution arise.

File: src/librustc_resolve/lib.rs [hunk 8]
```diff
@@ -4862,6 +4892,7 @@ impl<'a> Resolver<'a> {
...
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: Dead code.

File: src/librustc_resolve/resolve_imports.rs [hunk 9]
```diff
@@ -1245,7 +1245,7 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
 
         self.populate_module_if_necessary(module);
 
-        if let Some(Def::Trait(_)) = module.def() {
+        if module.is_trait() || module.is_trait_alias() {
```
Comment (petrochenkov) [inline src/librustc_resolve/resolve_imports.rs]: Trait aliases are not modules, this can be reverted.

File: src/librustc_resolve/lib.rs [hunk 10]
```diff
@@ -1195,6 +1195,13 @@ impl<'a> ModuleData<'a> {
         }
     }
 
+    fn is_trait_alias(&self) -> bool {
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: This function becomes unused if my two previous comments are addressed.

**Comment by petrochenkov** [comment]
@seanmonstar 
Could you also add a test for this case - https://github.com/rust-lang/rust/issues/56485#issuecomment-476496595.

**Comment by alexreg** [comment]
@seanmonstar Looks like you got some feedback... a bit late, but feedback nonetheless! Nothing critical it seems, but worth including before merging, so I'll undo the r+ for you to make the changes.

File: src/librustc_typeck/check/method/probe.rs [hunk 11]
```diff
@@ -895,20 +895,35 @@ impl<'a, 'gcx, 'tcx> ProbeContext<'a, 'gcx, 'tcx> {
...
+                let new_trait_ref = this.erase_late_bound_regions(&new_trait_ref);
+
+                let (xform_self_ty, xform_ret_ty) =
+                    this.xform_self_ty(&item, new_trait_ref.self_ty(), new_trait_ref.substs);
+                this.push_candidate(Candidate {
+                    xform_self_ty, xform_ret_ty, item, import_id,
+                    kind: TraitCandidate(new_trait_ref),
+                }, true);
+            });
+        } else {
```
Comment (alexreg) [inline src/librustc_typeck/check/method/probe.rs]: Maybe a line here about assuming that we have a trait? (Or even an `assert`/`debug_assert` perhaps?)

File: src/test/run-pass/traits/trait-alias-import-cross-crate.rs [hunk 12]
```diff
@@ -0,0 +1,14 @@
...
+#![feature(trait_alias)]
+
+extern crate trait_alias;
+
+// Import only the alias, not the real trait.
+use trait_alias::{Greet, Hi};
+
+fn main() {
+    let hi = Hi;
+    hi.hello(); // From Hello, through Greet alias.
```
Comment (alexreg) [inline src/test/run-pass/traits/trait-alias-import-cross-crate.rs]: ``// From `Hello,` via the `Greet` alias.``

**Review by alexreg — CHANGES_REQUESTED** [review]
Changes look good. Let's hope this passes now...

**Comment by alexreg** [comment]
@seanmonstar Looks like you need to re-bless tests. Feel free to r=me when you've done that and tests are passing.

@bors delegate+

**Comment by alexreg** [comment]
@seanmonstar Ah nope, it's not simply a matter of re-blessing. You must have inadvertently messed somethtting up with method resolution in your latest changes...

**Comment by Centril** [comment]
Ping from triage, @seanmonstar

**Comment by seanmonstar** [comment]
Yep I'll fix it, took a couple days off after a small procedure.

**Comment by alexreg** [comment]
@seanmonstar Ah, no worries. Hope that's all alright now. Just ping me when ready for another review. (Ideally don't force push so I can see the diff.)

**Comment by seanmonstar** [comment]
@alexreg there was just a missing line in an impl I added to the run-pass test. If CI passes, I'll just r=you?

**Comment by alexreg** [comment]
@seanmonstar Oh good. Yeah, feel free to r=me when CI passes if that's all.

**Comment by alexreg** [comment]
Great, finally merged! Would someone kindly tick off the box on the issue https://github.com/rust-lang/rust/issues/41517 and add `(implemented by #59166)` to the end of that that line? Maybe @centril?
