### PR TITLE
Permit impls referencing errors to overlap

### LINKED ISSUE #43400: spurious coherence error using error-chain with nonexistent type
~~~I haven't been able to minimize this, but the code is:~~~ _(edit: see below)_

```rust
error_chain! {
    foreign_links {
        Bad(nope::Thing); // nonexistent type
    }
}
```

The first error is sensical:

```
error[E0433]: failed to resolve. Use of undeclared type or module `nope`
  --> /Users/alex/.cargo/.cargo/script-cache/expr-698cc781c70734ef/expr.rs:11:47
   |
11 |     match {error_chain! { foreign_links { Bad(nope::Thing); } }} {
   |                                               ^^^^^^^^^^^ Use of undeclared type or module `nope`
```

But the knock-on errors are not:

```
error[E0119]: conflicting implementations of trait `std::convert::From<[type error]>` for type `try_main::Error`:
  --> /Users/alex/.cargo/.cargo/script-cache/expr-698cc781c70734ef/expr.rs:11:12
   |
11 |     match {error_chain! { foreign_links { Bad(nope::Thing); } }} {
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |            |
   |            first implementation here
   |            conflicting implementation for `try_main::Error`
   |
   = note: this error originates in a macro outside of the current crate
```

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Fixes #43400; previously this would emit an overlapping impls error, but no longer does.

### CODE REVIEW

File: src/test/ui/conflicting-impl-with-err.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+struct ErrorKind;
```
Comment (Centril) [inline src/test/ui/conflicting-impl-with-err.rs]: Can we move the test so that it's not in the middle of `ui/` ?

Comment (Mark-Simulacrum) [reply src/test/ui/conflicting-impl-with-err.rs]: You mean a subdirectory or something like that?

Comment (Centril) [reply src/test/ui/conflicting-impl-with-err.rs]: Yup, something like that :)

Comment (Mark-Simulacrum) [reply src/test/ui/conflicting-impl-with-err.rs]: I can, I suppose, move it to coherence, which seems like the best fit (though a poor one). I don't personally see much point though; I don't see much reason for the groupings of files within src/test/ui -- it seems like almost all or all of the time anyone will run all the tests, not a subset. But if you have a concrete suggestion I can implement it.

Comment (Centril) [reply src/test/ui/conflicting-impl-with-err.rs]: coherence seems fine; the main point is to not have many files in the root of `ui/` cause that makes navigation ungreat.

File: src/librustc/ty/mod.rs [hunk 2]
```diff
@@ -2894,6 +2894,13 @@ impl<'tcx> TyCtxt<'tcx> {
     pub fn impls_are_allowed_to_overlap(self, def_id1: DefId, def_id2: DefId)
                                         -> Option<ImplOverlapKind>
     {
+        // If either trait impl references an error, they're allowed to overlap,
+        // as one of them essentially doesn't exist.
+        if self.impl_trait_ref(def_id2).map_or(false, |tr| tr.references_error()) ||
```
Comment (ollie27) [inline src/librustc/ty/mod.rs]:
```suggestion
        if self.impl_trait_ref(def_id1).map_or(false, |tr| tr.references_error()) ||
```

maybe?

**Comment by Mark-Simulacrum** [comment]
Both comments resolved.
