### PR TITLE
reject partial init and reinit of uninitialized data

### LINKED ISSUE #54499: Invalid "variable does not need to be mutable" warning in 2018 edition with partially initialized structs
```rust
fn main() {
    let mut s: (i32, i32);
    s.0 = 3;
    s.1 = 4;
    println!("{} {}", s.0, s.1);
}
```

Causes the following warning:

```
warning: variable does not need to be mutable
 --> src/main.rs:2:9
  |
2 |     let mut s: (i32, i32);
  |         ----^
  |         |
  |         help: remove this `mut`
  |
  = note: #[warn(unused_mut)] on by default
```

Removing `mut` causes an error:

```
error[E0594]: cannot assign to `s.0`, as `s` is not declared as mutable
 --> src/main.rs:3:5
  |
2 |     let s: (i32, i32);
  |         - help: consider changing this to be mutable: `mut s`
3 |     s.0 = 3;
  |     ^^^^^^^ cannot assign

error[E0594]: cannot assign to `s.1`, as `s` is not declared as mutable
 --> src/main.rs:4:5
  |
2 |     let s: (i32, i32);
  |         - help: consider changing this to be mutable: `mut s`
3 |     s.0 = 3;
4 |     s.1 = 4;
  |     ^^^^^^^ cannot assign

error: aborting due to 2 previous errors
```

Tested on nightly on the playground. This code is stupid, but I don't think it should report "unused mut" warnings.

### LINKED ISSUE #54986: NLL: Reject partial init of uninitialized record (struct or tuple)
Spawned off of #21232 

In the short term, we want to reject code like this:

```rust
struct S { x: u32, y: u32 }
fn main() { let mut s: S; s.x = 10; }
```

See #54987 for the long-term goal.

### PR DESCRIPTION
**Pull request by pnkfelix**
Reject partial initialization of uninitialized structured types (i.e. structs and tuples) and also reject partial *reinitialization* of such types.

Fix #54986

Fix #54499 

cc #21232

### CODE REVIEW

**Comment by pnkfelix** [comment]
This PR is almost certainly subsumed by the work of @spastorino on PR #54621 

I have put this PR up here mostly as a point of comparison (e.g. to double-check the tests and to compare the choice of diagnostic wording under the two approaches).

**Comment by pnkfelix** [comment]
(I am still working on this; my mysteriously stopped working after the rebase that introduced `visit_user_ty` so I think I just messed up my rebase and need to investigate that properly.

I also need to extend it to cover #54499

**Comment by pnkfelix** [comment]
this is now ready for review

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -1439,10 +1441,7 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
         debug!("check_if_reassignment_to_immutable_state({:?})", local);
 
         // Check if any of the initializiations of `local` have happened yet:
-        let mpi = self.move_data.rev_lookup.find_local(local);
-        let init_indices = &self.move_data.init_path_map[mpi];
-        let first_init_index = init_indices.iter().find(|&ii| flow_state.ever_inits.contains(*ii));
-        if let Some(&init_index) = first_init_index {
+        if let Some(init_index) = self.is_local_ever_initialized(local, flow_state) {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: nice place for a helper fn 💯

File: src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+}
+
+
+impl Drop for D {
+    fn drop(&mut self) { }
+}
+
+fn cannot_partially_init_adt_with_drop() {
+    let d: D;
+    d.x = 10;
```
Comment (nikomatsakis) [inline src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs]: Please add `//~ ERROR` annotations where appropriate (why aren't these required, anyway? probably my fault)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
r=me with update

File: src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs (hunk 2 above)
Comment (pnkfelix) [reply src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs]: Hmm you’re right, why aren’t they required here... (is it one of those goofy things where if none of a particular diagnostic class are present then none are required?)

**Comment by pnkfelix** [comment]
@bors r-

Oops: I added the `//~ ERROR` annotations to a bunch of my new tests, but not the *particular one* where @nikomatsakis asked for it...

File: src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs (hunk 2 above)
Comment (pnkfelix) [reply src/test/ui/nll/issue-21232-partial-init-and-erroneous-use.rs]: (okay added them here and also to the way more meaty ones in borrowck for issue #54499 .)

**Comment by pnkfelix** [comment]
@bors r-

@nikomatsakis had warned about not breaking unions here: https://github.com/rust-lang/rust/issues/21232#issuecomment-412219247

but I'm worried that I may have broken that exact case.

**Comment by pnkfelix** [comment]
@bors r=nikomatsakis

I double-checked: the code that @nikomatsakis wrote was actually (I think) referring to the hypothetical world of #54987. This PR is solely about #54986. As far as I can tell, this change does not break `union`.
