### PR TITLE
Emit a hint for bad call return types due to generic arguments

### LINKED ISSUE #43608: Confusing mismatched type error
If you forget to put a semicolon after the last expression in the body of a function that returns no values, `rustc` will infer that the type of the expression should be `()`. If the programmer didn't intend to return a value, but merely forgot to type a semicolon, the resulting error can be confusing. Consider, for example, the following [toy program](https://play.rust-lang.org/?gist=0bf5eb6df01e8b850d0a413e56cc59b8&version=stable):

```rust
use std::ptr;

fn main() {
    let a = 0;
    ptr::read(&a)
}
```

This produces the following error message:

```text
error[E0308]: mismatched types
 --> src/main.rs:5:15
  |
5 |     ptr::read(&a)
  |               ^^ expected (), found integral variable
  |
  = note: expected type `*const ()`
             found type `&{integer}`
```

In this simple example, it may be obvious, but in the somewhat more complicated code I was working with that led me to this issue, I spent a decent amount of time trying to figure out why I was supposedly passing a pointer to `()` to `mem::replace`, thus causing the type of the second argument to `replace` to fail to unify. It took me a while to figure out that this was actually the culprit.

### PR DESCRIPTION
**Pull request by sulami**
When the return type of a function call depends on the type of an argument, e.g.

```
fn foo<T>(x: T) -> T {
    x
}
```

and the expected type is set due to either an explicitly typed binding, or because the call to the function is in a tail position without semicolon, the current error implies that the argument in the call has the wrong type.

This new hint highlights that the expected type doesn't match the returned type, which matches the argument type, and that that's why we're flagging the argument type.

Fixes #43608.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 1]
```diff
@@ -1941,4 +1942,54 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            "the return type of this call is `{}` due to the type of the argument passed",
+                            checked_ty
+                        )
+                    );
+            }
+        };
+        match parent_expr.kind {
+            hir::ExprKind::Call(fun, args) => {
+                let hir::ExprKind::Path(hir::QPath::Resolved(_, path)) = fun.kind else { return; };
+                let hir::def::Res::Def(_kind, def_id) = path.res else { return; };
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/demand.rs:1985]: To filter the enum variants and tuple structs away you could look at `_kind` here to see that it is *not* a Ctor ("constructor").

File: tests/ui/suggestions/args-instead-of-tuple-errors.stderr [hunk 2]
```diff
@@ -64,6 +71,13 @@ LL |     let _: Option<(i32,)> = Some(5_usize);
    |
    = note: expected tuple `(i32,)`
                found type `usize`
+help: the return type of this call is `usize` due to the type of the argument passed
+  --> $DIR/args-instead-of-tuple-errors.rs:14:29
+   |
+LL |     let _: Option<(i32,)> = Some(5_usize);
+   |                             ^^^^^-------^
+   |                                  |
+   |                                  this argument influences the return type of `Some`
```
Comment (estebank) [inline tests/ui/suggestions/args-instead-of-tuple-errors.stderr:80]: Maybe what we should do is tweak the *wording* depending on the item type? Because I'm sure people are going to be confused by talking about the "return type of an enum variant". Seeing tuple structs as functions is natural from the compiler's point of view, but not from the users'.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_hir_typeck/src/demand.rs (hunk 1 above)
Comment (sulami) [reply compiler/rustc_hir_typeck/src/demand.rs:1985]: Yeah, I'm torn on this as well because it's wide-reaching, but it does help in some cases because constructors are prone to hit the same confusing errors as regular function calls.

File: tests/ui/suggestions/args-instead-of-tuple-errors.stderr (hunk 2 above)
Comment (sulami) [reply tests/ui/suggestions/args-instead-of-tuple-errors.stderr]: I've put something in that tweaks the wording. It's slightly awkward for constructors, because they return a type that's different from the argument, and I don't know if there is a reliable way of getting that type regardless of wrapping, but this now is at least coherent.

File: tests/ui/closures/issue-84128.stderr [hunk 3]
```diff
@@ -6,6 +6,13 @@ LL |         Foo(())
    |         |
    |         arguments to this struct are incorrect
    |
+help: the type constructed contains `()` due to the type of the argument passed
+  --> $DIR/issue-84128.rs:13:9
+   |
+LL |         Foo(())
+   |         ^^^^--^
+   |             |
+   |             this argument influences the type of `Foo`
```
Comment (estebank) [inline tests/ui/closures/issue-84128.stderr:15]: I'm noticing that there are some cases where the existing machinery to detect the source of expectations isn't as robust as we'd like, but that's independent of this PR.

Comment (estebank) [reply tests/ui/closures/issue-84128.stderr:15]: Filed https://github.com/rust-lang/rust/issues/106821

File: tests/ui/suggestions/args-instead-of-tuple-errors.stderr [hunk 4]
```diff
@@ -11,6 +11,13 @@ LL |     let _: Option<(i32, bool)> = Some(1, 2);
    |                                       ^
    = note: expected tuple `(i32, bool)`
                found type `{integer}`
+help: the type constructed contains `{integer}` due to the type of the argument passed
+  --> $DIR/args-instead-of-tuple-errors.rs:6:34
+   |
+LL |     let _: Option<(i32, bool)> = Some(1, 2);
+   |                                  ^^^^^-^^^^
+   |                                       |
+   |                                       this argument influences the type of `Some`
```
Comment (estebank) [inline tests/ui/suggestions/args-instead-of-tuple-errors.stderr:20]: This case should probably have been silenced.
