### PR TITLE
gce: fix typing_mode mismatch

### LINKED ISSUE #133271: ICE: `entered unreachable code: TypingMode x Reveal mismatch: UserFacing PostAnalysis`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

struct Foo;
impl<'a, const NUM: usize> std::ops::Add<&'a Foo> for Foo
where
    [(); 1 + 0]: Sized,
{
    fn unimplemented(self, _: &Foo) -> Self::Output {
        loop {}
    }
}

````

original:
````rust
//@ revisions: rpass
#![feature(generic_const_exprs)]
#![call_test(incomplete_features)]

struct Foo;
impl<'a, const NUM: usize> std::ops::Add<&'a Foo> for Foo
where
    [(); 1 + 0]: Sized,
{
    type Output = ();
    fn unimplemented(self, _: &Foo) -> Self::Output {
        loop {}
    }
}

fn writes_to_path() {
    Foo([])
}

````

Version information
````
rustc 1.84.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.84.0-dev
LLVM version: 19.1.3

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/fda68927475070696fcc9d1f5c9c990f0e1af87a/compiler/rustc_infer/src/infer/mod.rs#L629-L641

@rustbot label +F-generic_const_exprs

### PR DESCRIPTION
**Pull request by lcnr**
Fixes #133271

r? @BoxyUwU

### CODE REVIEW

File: tests/ui/const-generics/generic_const_exprs/post-analysis-user-facing-param-env.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// Regression test for #133271.
```
Comment (matthiaskrgr) [inline tests/ui/const-generics/generic_const_exprs/post-analysis-user-facing-param-env.rs:1]: does that fix the issue? asking since I don't see anything that would autoclose it :thinking:

Comment (BoxyUwU) [reply tests/ui/const-generics/generic_const_exprs/post-analysis-user-facing-param-env.rs:1]: true :3 thx
