### PR TITLE
Test and fix Send and Sync traits of BTreeMap artefacts

### LINKED ISSUE #76686: btree_map::OccupiedEntry: Send regression
The code below does not compile on new versions of `rustc` (bisect below)

```rust
use std::collections::{btree_map::Entry, BTreeMap};
use std::thread::spawn;

fn main() {
    let map = BTreeMap::<i32, i32>::new();
    let map = Box::leak(Box::new(map));

    match map.entry(1) {
        Entry::Occupied(entry) => {
            spawn(move || {
                entry.get();
            });
        }
        _ => (),
    }
}

```

```
error[E0277]: `NonNull<BTreeMap<i32, i32>>` cannot be sent between threads safely
   --> src/main.rs:10:13
    |
10  |               spawn(move || {
    |  _____________^^^^^_-
    | |             |
    | |             `NonNull<BTreeMap<i32, i32>>` cannot be sent between threads safely
11  | |                 entry.get();
12  | |             });
    | |_____________- within this `[closure@src/main.rs:10:19: 12:14 entry:std::collections::btree_map::OccupiedEntry<'_, i32, i32>]`
    | 
   ::: /home/antek/.local/opt/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:596:8
    |
596 |       F: Send + 'static,
    |          ---- required by this bound in `spawn`
    |
    = help: within `[closure@src/main.rs:10:19: 12:14 entry:std::collections::btree_map::OccupiedEntry<'_, i32, i32>]`, the trait `Send` is not implemented for `NonNull<BTreeMap<i32, i32>>`
    = note: required because it appears within the type `alloc::collections::btree::borrow::DormantMutRef<'_, BTreeMap<i32, i32>>`
    = note: required because it appears within the type `std::collections::btree_map::OccupiedEntry<'_, i32, i32>`
    = note: required because it appears within the type `[closure@src/main.rs:10:19: 12:14 entry:std::collections::btree_map::OccupiedEntry<'_, i32, i32>]`
```

### Bisect
searched nightlies: from nightly-2020-09-11 to nightly-2020-09-12
regressed nightly: nightly-2020-09-12
searched commits: from https://github.com/rust-lang/rust/commit/a1947b3f9e2831e2060bc42f0c78e4a2bb67930a to https://github.com/rust-lang/rust/commit/99111606fcda4fdb0646e4f7ee0f6cbcb76fb84a
regressed commit: https://github.com/rust-lang/rust/commit/ee04f9a4dac3e72914862e9f2046eee70aedcbfd

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2020-09-11 
```
</details>

### PR DESCRIPTION
**Pull request by ssomers**
Fixes #76686.

I'm not quite sure what all this implies. E.g. comparing with the definitions for `NodeRef` in node.rs,  maybe an extra bound `T: 'a` is useful for something. The test compiles on stable/beta (apart from `drain_filter`) so I bet `Sync` is equally desirable.

r? @Mark-Simulacrum

### CODE REVIEW

File: library/alloc/src/collections/btree/borrow.rs [hunk 1]
```diff
@@ -16,6 +16,9 @@ pub struct DormantMutRef<'a, T> {
     _marker: PhantomData<&'a mut T>,
 }
 
+unsafe impl<'a, T: Sync> Sync for DormantMutRef<'a, T> {}
+unsafe impl<'a, T: Send> Send for DormantMutRef<'a, T> {}
```
Comment (jyn514) [inline library/alloc/src/collections/btree/borrow.rs:20]: Don't you want `&mut T` to be Send, not T?
```suggestion
unsafe impl<'a, T> Sync for DormantMutRef<'a, T> where &'a mut T: Sync {}
unsafe impl<'a, T> Send for DormantMutRef<'a, T> where &'a mut T: Send {}
```

**Comment by Mark-Simulacrum** [comment]
@jyn514 is correct, I think, that we want these in terms of &mut T.

r=me with that change made

**Comment by ssomers** [comment]
Also got more fine grained testing to compile and added newcomers `into_keys` and `into_values`.

r= @Mark-Simulacrum

File: library/alloc/src/collections/btree/borrow.rs (hunk 1 above)
Comment (cuviper) [reply library/alloc/src/collections/btree/borrow.rs]: Is there any tangible difference? That implementation is already:

```rust
unsafe impl<T: Send + ?Sized> Send for &mut T {}
```

And I believe `Sync for &mut T` is auto-implemented for `T: Sync`.

Comment (jyn514) [reply library/alloc/src/collections/btree/borrow.rs]: You could have `unsafe impl<T> Send for &mut T {}`, even if `T` is not Send.

Comment (jyn514) [reply library/alloc/src/collections/btree/borrow.rs]: And in general this is conceptually a `&mut T` so it makes sense to use the same rules as &mut T for it.

Comment (Mark-Simulacrum) [reply library/alloc/src/collections/btree/borrow.rs]: Yeah, I think they might match up in practice, but I didn't want to replicate impls when we could just use this.

Comment (cuviper) [reply library/alloc/src/collections/btree/borrow.rs]: I guess `core` could pull that trick, but nobody else:

```rust
struct Foo(*const i32);

unsafe impl Send for &mut Foo {}
```

```
error[E0119]: conflicting implementations of trait `std::marker::Send` for type `&mut Foo`:
 --> src/lib.rs:3:1
  |
3 | unsafe impl Send for &mut Foo {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> std::marker::Send for &mut T
            where T: std::marker::Send, T: ?Sized;

error[E0321]: cross-crate traits with a default impl, like `std::marker::Send`, can only be implemented for a struct/enum type, not `&mut Foo`
 --> src/lib.rs:3:1
  |
3 | unsafe impl Send for &mut Foo {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't implement cross-crate trait with a default impl for non-struct/enum type
```
