### PR TITLE
Shorten backtraces for queries in ICEs

### LINKED ISSUE #107910: Shorten backtraces in ICEs
Right now, the backtraces in an ICE are almost unreadably long (250+ frames, sometimes as much as 400+). See [message.txt](https://github.com/rust-lang/rust/files/10711831/message.txt) for an example.

Most of these frames are not particularly useful. Consider for example this snippet:

<details><summary>rustc_query_impl plumbing</summary>

```
             3: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:340:53
             4: rustc_middle::ty::context::tls::tlv::with_tlv::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:94:9
             5: rustc_middle::ty::context::tls::enter_context::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:114:5
             6: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}
                       at ./compiler/rustc_middle/src/dep_graph/mod.rs:58:13
             7: rustc_middle::ty::context::tls::with_context::<<rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:36
             8: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<<rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:131:18
             9: rustc_middle::ty::context::tls::with_context::<<rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:5
            10: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>::{closure#0}, std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_middle/src/dep_graph/mod.rs:55:9
            11: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:340:22
            12: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:290:13
            13: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:467:13
            14: stacker::maybe_grow::<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>
                       at /home/gh-yaahc/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
            15: rustc_data_structures::stack::ensure_sufficient_stack::<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>
                       at ./compiler/rustc_data_structures/src/stack.rs:17:5
            16: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}
                       at ./compiler/rustc_query_impl/src/plumbing.rs:128:17
            17: rustc_middle::ty::context::tls::tlv::with_tlv::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:94:9
            18: rustc_middle::ty::context::tls::enter_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:114:5
            19: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}
                       at ./compiler/rustc_query_impl/src/plumbing.rs:127:13
            20: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:164:9
            21: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:36
            22: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:131:18
            23: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:5
            24: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, (std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:155:5
            25: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<(std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>::{closure#3}>
                       at ./compiler/rustc_query_impl/src/plumbing.rs:112:9
            26: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:455:9
            27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:369:17
            28: rustc_query_system::query::plumbing::force_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:779:5
            29: rustc_query_impl::plumbing::force_from_dep_node::<rustc_query_impl::queries::trimmed_def_paths>
                       at ./compiler/rustc_query_impl/src/plumbing.rs:408:9
            30: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
                       at ./compiler/rustc_query_system/src/dep_graph/mod.rs:59:13
            31: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:736:13
            32: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            33: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            34: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            35: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            36: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            37: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            38: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            39: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            40: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            41: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            42: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            43: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            44: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            45: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            46: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            47: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            48: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            49: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_parent_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:726:17
            50: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:797:13
            51: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/dep_graph/graph.rs:681:17
            52: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:499:49
            53: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:445:13
            54: stacker::maybe_grow::<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>
                       at /home/gh-yaahc/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
            55: rustc_data_structures::stack::ensure_sufficient_stack::<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>
                       at ./compiler/rustc_data_structures/src/stack.rs:17:5
            56: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}::{closure#0}
                       at ./compiler/rustc_query_impl/src/plumbing.rs:128:17
            57: rustc_middle::ty::context::tls::tlv::with_tlv::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:94:9
            58: rustc_middle::ty::context::tls::enter_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:114:5
            59: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}
                       at ./compiler/rustc_query_impl/src/plumbing.rs:127:13
            60: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:164:9
            61: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:36
            62: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:131:18
            63: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:142:5
            64: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>::{closure#0}, core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
                       at ./compiler/rustc_middle/src/ty/context/tls.rs:155:5
            65: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<core::option::Option<(rustc_middle::ty::Ty, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}>
                       at ./compiler/rustc_query_impl/src/plumbing.rs:112:9
            66: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:444:28
            67: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:369:17
            68: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
                       at ./compiler/rustc_query_system/src/query/plumbing.rs:747:36
            69: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of::{closure#0}
                       at ./compiler/rustc_query_impl/src/plumbing.rs:730:17
            70: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
                       at ./compiler/rustc_query_impl/src/lib.rs:44:1
```

</details>

The only useful information here is "the type_of query was run", but it takes up 140 lines and 70 frames of the backtrace.
We should collapse these unless the user opts-in: I'm imagining something like setting RUSTC_BACKTRACE=1 which hides the frames by default and RUSTC_BACKTRACE=full which expands them.

### PR DESCRIPTION
**Pull request by chenyukang**
r? @jyn514 
Fixes #107910

### CODE REVIEW

**Review by jyn514 — CHANGES_REQUESTED** [review]
Can you please add a test case that this works? You can force a panic with `-Z treat-err-as-bug`.

**Comment by Nilstrieb** [comment]
This touches the query system by adding a call to it, so
@bors try @rust-timer queue

**Comment by jyn514** [comment]
@Zoxc What do you mean by "proper backtraces"? Why not do this by default? The only time I can imagine the query internals being useful is for people working on the query system itself, which is a very small minority of the people working on the compiler.

**Comment by Nilstrieb** [comment]
It can sometimes be useful to see where a query was exactly called from. While the query backtrace does contain the calling query name, it doesn't contain more precise information about the location of the call to the query.

**Comment by Zoxc** [comment]
> What do you mean by "proper backtraces"?

I meant backtraces generated with RUST_BACKTRACE=1.

The query internals isn't that useful for people not working on the query system, but the actual backtrace still is useful to see why a specific query was called.

**Comment by jyn514** [comment]
> Ideally we'd hide all the query internals from `tcx.x` to `fn x` ✨

That's exactly what this PR is trying to do. @chenyukang can you post an example of the shortened backtrace for the new test you added? I think having a concrete example will make it more clear what this does.

**Comment by chenyukang** [comment]
```bash
RUST_BACKTRACE=1 rustc +dev src/main.rs -Z treat-err-as-bug=1  > ./short.log 2>&1
```
[short.log](https://github.com/rust-lang/rust/files/10934143/short.log)


```bash
RUST_BACKTRACE=full rustc +dev src/main.rs -Z treat-err-as-bug=1  > ./full.log 2>&1
```
[full.log](https://github.com/rust-lang/rust/files/10934155/full.log)

**Comment by Nilstrieb** [comment]
Your example doesn't really exercise the query system, can you show an example of something deep within it instead? Like a trait bound error

**Comment by chenyukang** [comment]
> Your example doesn't really exercise the query system, can you show an example of something deep within it instead? Like a trait bound error

I just run the wrong command, re-uploaded new log files.

**Comment by jyn514** [comment]
@chenyukang I think you're missing a call to `rust_end_short_backtrace`, this is excluding *all* frames before `get_query` which isn't correct.

**Comment by chenyukang** [comment]
@jyn514 yes, we should only exclude the frames of queries.
I will take a look tomorrow, need some sleep 😁

**Comment by chenyukang** [comment]
hmm, interesting, I read the code and try some sample code, `__rust_begin_short_backtrace` and `__rust_end_short_backtrace` do not work as I thought.

Actually `__rust_end_short_backtrace` is called at the end(inner most) of backtrace:
https://github.com/rust-lang/rust/blob/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs#L579

then `__rust_begin_short_backtrace` is the starting point of the backtrace, here is the logic:

https://github.com/rust-lang/rust/blob/f37f8549940386a9d066ba199983affff47afbb4/library/std/src/sys_common/backtrace.rs#L72-L93

this means we can not use these two functions to remove a middle part of backtrace frames, instead, we can only set the starting point.

I used this sample program to verify it:
```
rust


#[inline(never)]
fn __rust_begin_short_backtrace<T, F: FnOnce() -> T>(f: F) -> T {
    let result = f();

    // prevent this frame from being tail-call optimised away
    std::hint::black_box(result)
}

#[inline(never)]
fn __rust_end_short_backtrace<T, F: FnOnce() -> T>(f: F) -> T {
    let result = f();

    // prevent this frame from being tail-call optimised away
    std::hint::black_box(result)
}


fn first() {
    println!("first ...");
    second();
}

fn second() {
    println!("second ..");
    third();
}

fn third() {
    println!("third ...");
    __rust_end_short_backtrace(|| fourth());
}

fn fourth() {
    println!("fourth ..");
    fifth();
}

fn fifth() {
    println!("fifth ...");
    __rust_begin_short_backtrace(|| sixth());
}

fn sixth() {
    println!("sixth ..");
    seven();
}

fn seven() {
    println!("seven");
    panic!("debug now");
}


fn main() {
    first();
}
```

**Comment by jyn514** [comment]
ah, that's unfortunate. can we modify that logic to support our use case without breaking existing backtraces? maybe by setting `start = false` when we hit `begin_backtrace` instead of `stop = true`?

**Comment by chenyukang** [comment]
Previous short log with:

```bash
RUST_BACKTRACE=1 rustc +dev tests/run-make/short-ice/src/lib.rs -Z treat-err-as-bug=1
```

[pre.log](https://github.com/rust-lang/rust/files/10948998/pre.log)

Change to:
[now-short.log](https://github.com/rust-lang/rust/files/10949001/now-short.log)

**Comment by jyn514** [comment]
very cool! I still see 10 or so frames related to the query plumbing in the middle - is it possible to remove those as well?

```
 38: <rustc_query_impl::queries::resolver_for_lowering as rustc_query_system::query::config::QueryConfig<rustc_query_impl::plumbing::QueryCtxt>>::compute
             at ./compiler/rustc_query_impl/src/plumbing.rs:511:21
  39: rustc_query_system::query::plumbing::execute_job::<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}
             at ./compiler/rustc_query_system/src/query/plumbing.rs:425:67
  40: rustc_middle::ty::context::tls::tlv::with_tlv::<rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:94:9
  41: rustc_middle::ty::context::tls::enter_context::<rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:114:5
  42: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}
             at ./compiler/rustc_query_impl/src/plumbing.rs:127:13
  43: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}
             at ./compiler/rustc_middle/src/ty/context/tls.rs:164:9
  44: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}
             at ./compiler/rustc_middle/src/ty/context/tls.rs:142:36
  45: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_context<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:131:18
  46: rustc_middle::ty::context::tls::with_context::<rustc_middle::ty::context::tls::with_related_context<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:142:5
  47: rustc_middle::ty::context::tls::with_related_context::<<rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>::{closure#0}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:155:5
  48: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::queries::resolver_for_lowering, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}::{closure#0}>
             at ./compiler/rustc_query_impl/src/plumbing.rs:112:9
```

**Comment by chenyukang** [comment]
yes, we could call `__rust_begin_short_backtrace` at a inner location, here is new result.
[short-log-3.log](https://github.com/rust-lang/rust/files/10949589/short-log-3.log)

File: compiler/rustc_query_system/src/dep_graph/graph.rs [hunk 1]
```diff
@@ -354,7 +355,7 @@ impl<K: DepKind> DepGraphData<K> {
             None => TaskDepsRef::Ignore,
         };
 
-        let result = K::with_deps(task_deps_ref, || task(cx, arg));
+        let result = K::with_deps(task_deps_ref, || __rust_begin_short_backtrace(|| task(cx, arg)));
```
Comment (cjgillot) [inline compiler/rustc_query_system/src/dep_graph/graph.rs:358]: I think there should only be 2 places for these functions:
- one in the `QueryEngine::$name` functions, which is the entry point for the computation;
- one in `QueryConfig::compute` functions, which is where we give back to use code.

Both are in `rustc_query_impl::plumbing`.

File: library/std/src/sys_common/backtrace.rs [hunk 2]
```diff
@@ -68,13 +68,17 @@ unsafe fn _print_fmt(fmt: &mut fmt::Formatter<'_>, print_fmt: PrintFmt) -> fmt::
...
+
+            // Any frames between `__rust_begin_short_backtrace` and `__rust_end_short_backtrace`
+            // are omitted from the backtrace in short mode, `__rust_end_short_backtrace` will be
+            // called before the panic hook, so we won't ignore any frames if there is no
+            // invoke of `__rust_begin_short_backtrace`.
             if print_fmt == PrintFmt::Short {
                 if let Some(sym) = symbol.name().and_then(|s| s.as_str()) {
                     if start && sym.contains("__rust_begin_short_backtrace") {
-                        stop = true;
+                        start = false;
```
Comment (cjgillot) [inline library/std/src/sys_common/backtrace.rs:81]: Can this have an effect on existing code?

File: tests/run-make/short-ice/src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,5 @@
+extern crate error_lib;
```
Comment (cjgillot) [inline tests/run-make/short-ice/src/lib.rs:1]: As said before, could you prefer a type error, that would better show what you are trying to do.

File: compiler/rustc_query_system/src/dep_graph/graph.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_query_system/src/dep_graph/graph.rs:358]: It's counterintuitive, because of the code logic here: 
https://github.com/rust-lang/rust/blob/f37f8549940386a9d066ba199983affff47afbb4/library/std/src/sys_common/backtrace.rs#L72-L93

We test function sym from bottom to up, so to reduce as much part of backtrace from query system, the `__rust_begin_short_backtrace` should be placed at the innermost function of query system.

I found the positions for these two functions in this way, follow the full log from up to bottom, find the first function we need to mark as `begin`, and find the second function we need to mark as `end`.

image

File: library/std/src/sys_common/backtrace.rs (hunk 2 above)
Comment (chenyukang) [reply library/std/src/sys_common/backtrace.rs:81]: no, the original code only supports one pair of `__rust_begin_short_backtrace` and `__rust_end_short_backtrace`, we extend it to support multiple pairs.

File: compiler/rustc_query_system/src/dep_graph/graph.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_query_system/src/dep_graph/graph.rs:358]: I mean: the innermost is `QueryConfig::compute`, and the outermost is `QueryEngine::$name`. That's the only 2 places where we need those functions.

Comment (chenyukang) [reply compiler/rustc_query_system/src/dep_graph/graph.rs]: ah, this makes the changes smaller and more consistent, thanks!

File: tests/run-make/short-ice/src/lib.rs (hunk 3 above)
Comment (chenyukang) [reply tests/run-make/short-ice/src/lib.rs]: yes, for type errors we could remove several parts of backtraces from query system:

[pre-short.log](https://github.com/rust-lang/rust/files/10951339/pre-short.log)

[now-short.log](https://github.com/rust-lang/rust/files/10951340/now-short.log)

FYI @jyn514

**Review by jyn514 — COMMENTED** [review]
this looks good! I'm not sure the new test is actually doing anything though - can you double check that it fails before this change?

**Comment by chenyukang** [comment]
> this looks good! I'm not sure the new test is actually doing anything though - can you double check that it fails before this change?

I add a new check in the new test, and verified the number of:

```console
cat short.log | grep rustc_query_system | wc -l 
```

changed from 66 to 3 with this change, so I pick 10 as a number in the test case.

**Comment by Mark-Simulacrum** [comment]
r? compiler 

I think this primarily affects the compiler; from a libs perspective the changes are minimal and seem mostly fine (though obviously this is not a stable implementation detail).

**Comment by Mark-Simulacrum** [comment]
It may warrant an MCP to give it a little more visibility.

**Comment by jyn514** [comment]
@Mark-Simulacrum hmm, do you think anyone will have objections? I don't mind announcing it at the next compiler meeting, but I'd rather not wait the extra 10 days if we don't need to.

**Comment by Zoxc** [comment]
I'd prefer an implementation which uses custom backtrace filtering using the QueryEngine and provider dynamic calls to avoid the performance impact. That way could also replace all the query system functions with a single query placeholder stack frame to make it clear that frames were erased.

**Comment by jyn514** [comment]
@Zoxc I don't follow, how would moving this to the query system help? don't we still need to mark *some* function as inline(never) to make sure we can find it on the stack at runtime?

**Comment by Zoxc** [comment]
There's already dynamic calls in the query system at the locations this PR inserts `__rust_begin_short_backtrace` and `__rust_end_short_backtrace` which won't get inlined.

**Comment by chenyukang** [comment]
Except for inserting mark functions, can we implement something like function attributes to mark entry and exit locations?

**Comment by Zoxc** [comment]
It should be possible to rename said virtual call targets to `__rust_end_short_backtrace` / `__rust_begin_short_backtrace`, but it does require some refactoring (which happens to be on my todo list anyway).

**Comment by WaffleLapkin** [comment]
r? compiler

**Comment by apiraino** [comment]
anyone from T-compiler with some context to review this?

r? compiler

**Comment by chenyukang** [comment]
@Zoxc 
Seems this PR needs some rework after https://github.com/rust-lang/rust/pull/109611 ?

File: tests/run-make/short-ice/Makefile [hunk 4]
```diff
@@ -1,4 +1,4 @@
-include ../../run-make-fulldeps/tools.mk
+include ../../run-make/tools.mk
```
Comment (jyn514) [inline tests/run-make/short-ice/Makefile:1]:
```suggestion
include ../tools.mk
```

**Comment by chenyukang** [comment]
@Zoxc
Could you please review my new change based on your merged PR?

File: compiler/rustc_query_impl/src/plumbing.rs [hunk 5]
```diff
@@ -490,12 +512,15 @@ macro_rules! define_queries {
                     key: query_keys::$name<'tcx>,
                     mode: QueryMode,
                 ) -> Option<Erase<query_values::$name<'tcx>>> {
```
Comment (Zoxc) [inline compiler/rustc_query_impl/src/plumbing.rs:514]: You can now create a new function named `__rust_end_short_backtrace` which calls `$name` here. Then pass that function to the `QueryEngine` constructor below. That avoids an extra function call.

Comment (chenyukang) [reply compiler/rustc_query_impl/src/plumbing.rs:504]: I figured another solution to avoids an extra function call,
since we are only checking whether the function name contains "__rust_end_short_backtrace" here: 
https://github.com/rust-lang/rust/blob/d3edfd18c790971c77845bfc1a2be4f9281c5416/library/std/src/sys_common/backtrace.rs#L80

why not we just add `__rust_end_short_backtrace` at the starting of `query`, such as commit: https://github.com/rust-lang/rust/pull/108938/commits/b871ec8d55abfe08b5da503df16cff510e674d21

I verified it works in dev.

Comment (Zoxc) [reply compiler/rustc_query_impl/src/plumbing.rs:504]: It will be inlined so that won't work without debug info.

**Comment by chenyukang** [comment]
I changed the `inline` attribute of a function

@bors try @rust-timer queue

**Comment by chenyukang** [comment]
Almost the same compared with the last version of change.

Let me try this version of change https://github.com/rust-lang/rust/pull/108938/commits/19ded7c7f82fa33079abcf659aff15350e9803f6
which based on https://github.com/rust-lang/rust/pull/109611,

@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
as a drive-by, the perf hit seems entirely acceptable to me, it's tiny on few benchmarks.

**Comment by saethlin** [comment]
I basically agree, having looked into this for a bit.

I believe the majority of the regression comes from the fact that the `__rust_begin_short_backtrace` shims are wrapping calls that LLVM refuses to inline. Why exactly that is, I don't know. I'm not intimately familiar with how the query system works. But just to highlight how goofy the codegen becomes here is one example:
```
00000000028ccd30 <rustc_query_impl::plumbing::__rust_begin_short_backtrace::<<rustc_query_impl::queries::analysis as rustc_query_system::query::config::QueryConfig<rustc_query_impl::plumbing::QueryCtxt>>::compute::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>>:
 28ccd30:       50                      push   %rax
 28ccd31:       48 8b 3f                mov    (%rdi),%rdi
 28ccd34:       ff 97 90 09 00 00       call   *0x990(%rdi)
 28ccd3a:       59                      pop    %rcx
 28ccd3b:       c3                      ret
```
Things are similarly silly on the `__rust_end_short_backtrace` end, but to a lesser extent. Those functions tend to at least be 10 instructions.

Overall, I think the perf regression here is small enough to be justified by the quality of life improvement.

---

In the future, I think the perf here may be improved by one of:
* Doing something clever with the query system code or applying `#[inline(always)]` to the functions called in the short_backtrace marker functions to make them inline into the short_backtrace functions
* Shipping debug symbols, which might make it possible to lose the `#[inline(never)]` and `black_box` trick, because the backtrace pruning code could look at names of inlined functions
* Teaching the query backtrace trimming code that this adds about the query functions themselves, instead of adding another shim function

File: compiler/rustc_query_impl/src/plumbing.rs [hunk 6]
```diff
@@ -498,12 +510,25 @@ macro_rules! define_queries {
                         mode
                     )
                 }
+
+                pub mod $name {
+                    use super::*;
+                    #[inline(never)]
+                    pub fn __rust_end_short_backtrace<'tcx>(
```
Comment (cjgillot) [inline compiler/rustc_query_impl/src/plumbing.rs:517]: Could you add a comment explaining the name?

File: compiler/rustc_query_impl/src/plumbing.rs [hunk 7]
```diff
@@ -498,12 +510,25 @@ macro_rules! define_queries {
...
+                        tcx: TyCtxt<'tcx>,
+                        span: Span,
+                        key: query_keys::$name<'tcx>,
+                        mode: QueryMode,
+                    ) -> Option<Erase<query_values::$name<'tcx>>> {
+                        $name(tcx, span, key, mode)
```
Comment (cjgillot) [inline compiler/rustc_query_impl/src/plumbing.rs:523]: Could you inline the `$name` functions into this one. This is their single call point anyway.

**Review by cjgillot — COMMENTED** [review]
I agree with the perf assessment. <1% is fine for this quality of life improvement.
r=me with 2 nits and commits squashed.

**Comment by chenyukang** [comment]
Seems we don't have proper backtraces on Andriod, #17520
Ignore Andriod now.

**Comment by chenyukang** [comment]
Ignored more targets ...

File: tests/ui/panics/short-ice-remove-middle-frames.rs [hunk 8]
```diff
@@ -0,0 +1,57 @@
+// compile-flags:-Cstrip=none
+// run-fail
+// check-run-results
+// exec-env:RUST_BACKTRACE=1
+// ignore-android FIXME #17520
+// ignore-wasm no panic support
+// ignore-openbsd no support for libbacktrace without filename
+// ignore-emscripten no panic or subprocess support
+// ignore-sgx no subprocess support
```
Comment (raoulstrackx) [inline tests/ui/panics/short-ice-remove-middle-frames.rs:9]: I'm a bit confused, where is this test using a subprocess? It's ok to ignore the SGX platform as backtraces are currently not symbolized

File: tests/run-make/short-ice/check.sh [hunk 9]
```diff
@@ -0,0 +1,36 @@
+#!/bin/sh
+
+RUST_BACKTRACE=1 $RUSTC src/lib.rs -Z treat-err-as-bug=1 1>$TMPDIR/rust-test-1.log 2>&1
```
Comment (raoulstrackx) [inline tests/run-make/short-ice/check.sh:3]: This fails on the SGX platform with:
```
/home/jenkins/workspace/rust-sgx-ci/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc: error while loading shared libraries: librustc_driver-b910c833a504f4dd.so: cannot open shared object file: No such file or directory
```
I'm confused why we get that error. You can ignore the SGX platform for this test as well.

File: tests/ui/panics/short-ice-remove-middle-frames.run.stderr [hunk 10]
```diff
@@ -0,0 +1,12 @@
+thread 'main' panicked at 'debug!!!', $DIR/short-ice-remove-middle-frames.rs:52:5
+stack backtrace:
+   0: std::panicking::begin_panic
+   1: short_ice_remove_middle_frames::seven
+   2: short_ice_remove_middle_frames::sixth
+   3: short_ice_remove_middle_frames::fifth::{{closure}}
+   4: short_ice_remove_middle_frames::second
```
Comment (bjorn3) [inline tests/ui/panics/short-ice-remove-middle-frames.run.stderr:7]: Can you please emit some kind of marker to indicate that frames have been omitted? This is just plain confusing. For example

```suggestion
   [some frames omitted]
   4: short_ice_remove_middle_frames::second
```
or

```suggestion
   [2 frames omitted]
   4: short_ice_remove_middle_frames::second
```

File: tests/ui/panics/short-ice-remove-middle-frames.rs (hunk 8 above)
Comment (chenyukang) [reply tests/ui/panics/short-ice-remove-middle-frames.rs:9]: This part is copied from another test case which also involves short backtraces `tests/ui/panics/issue-47429-short-backtraces.rs`, I will update the note part.

File: tests/ui/panics/short-ice-remove-middle-frames.run.stderr (hunk 10 above)
Comment (chenyukang) [reply tests/ui/panics/short-ice-remove-middle-frames.run.stderr:7]: I made a change: https://github.com/rust-lang/rust/commit/ddacb2dbb91ac1a438ab14db80b9a3457ecba60c

Found out we need to update https://github.com/rust-lang/backtrace-rs.git to add an API to emit the message.

Maybe we can enhance it in another PR?

**Comment by chenyukang** [comment]
@rustbot ready
Hope we can merge it this time 😂

File: tests/ui/panics/short-ice-remove-middle-frames.run.stderr (hunk 10 above)
Comment (jyn514) [reply tests/ui/panics/short-ice-remove-middle-frames.run.stderr:7]: Could you open an issue for adding the "N frame omitted" line, please?

**Comment by jyn514** [comment]
The perf regression was expected and deemed acceptable: https://github.com/rust-lang/rust/pull/108938#pullrequestreview-1425508342

File: tests/ui/panics/short-ice-remove-middle-frames.run.stderr (hunk 10 above)
Comment (chenyukang) [reply tests/ui/panics/short-ice-remove-middle-frames.run.stderr:7]: Sure, I will create an issue, then make a PR for backtrace-rs first, then another follow-up PR for it.
