### PR TITLE
Recover missing comma after match arm

### LINKED ISSUE #80112: Suggest adding a comma when match arm expression is followed by a pattern
```rust
enum Side { Left, Right }

fn match_side(s: Side) {
    match s {
        Side::Left => ()
        Side::Right => ()
    }
}
```

Currently shows:

```
error: expected one of `,`, `.`, `?`, `}`, or an operator, found `Side`
 --> src/lib.rs:6:9
  |
5 |         Side::Left => ()
  |                    --   - expected one of `,`, `.`, `?`, `}`, or an operator
  |                    |
  |                    while parsing the `match` arm starting here
6 |         Side::Right => ()
  |         ^^^^ unexpected token
```

It should be expanded with a help message to:

```
5 |          Side::Left => ()
 |                           ^ help: add , here
```

It should probably only emit this diagnostic if, by rechecking the match with the `,` there, it can find a pattern followed by `=>`.

---

For a more advanced case, consider this more convoluted example:

```rust
enum Side { Left(()), Right(()) }

fn match_side(s: Side) {
    match (s,) {
        (Side::Left(_),) => ()
        (Side::Right(_),) => ()
    }
}
```

It currently emits:

```
error: expected expression, found reserved identifier `_`
 --> src/lib.rs:6:22
  |
6 |         (Side::Right(_),) => ()
  |                      ^ expected expression

error: expected one of `,`, `.`, `?`, `}`, or an operator, found `=>`
 --> src/lib.rs:6:27
  |
5 |         (Side::Left(_),) => ()
  |                          -- while parsing the `match` arm starting here
6 |         (Side::Right(_),) => ()
  |                           ^^ expected one of `,`, `.`, `?`, `}`, or an operator
```

In this case, the pattern sort of looks like a function call and not an immediate incorrect token for an expression. The vast majority of cases can probably be caught by checking at the newline if what's after is a pattern. But there might also be a simple solution based on the pattern and expression grammars. Of course, it almost always triggers the `found =>`, so that could be used as a starting point.

### PR DESCRIPTION
**Pull request by compiler-errors**
If we're missing a comma after a match arm expression, try parsing another pattern and a following `=>`. If we find both of those, then recover by suggesting to insert a `,`.

Fixes #80112

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? rust-lang/diagnostics

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2743,15 +2742,41 @@ impl<'a> Parser<'a> {
...
                                     Applicability::MachineApplicable,
                                 );
+                                return Err(err);
                             }
-                            _ => {
-                                err.span_label(
-                                    arrow_span,
-                                    "while parsing the `match` arm starting here",
-                                );
+                        } else {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:2747]: Can't this logic be completely replaced with the `snapshot` parse attempt unconditionally? Or is it that we have advanced too much already and consumed part of the pattern by now specifically because of `&`?

**Comment by estebank** [comment]
r=me if deduplication isn't feasible

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:2747]: yeah, we would have consumed the `&Path` as the operator and RHS of operator `&` before getting here, which means we have to handle it differently.
