### PR TITLE
std: Mark `Layout::repeat` as `#[inline]`

### LINKED ISSUE #43272: Trivial vec![] creation then iteration doesn't optimize out the allocation
Rustc used to be able to replace `vec![1, 2, 3].iter().sum::<i32>()` with a constant when optimizing, not at the moment. It simply looks like a Layout method that is not inlinable.

(This is a regression strictly speaking — stable & beta can do this optimization, but not nightly.)

Code to reproduce:

[playground link](https://play.rust-lang.org/?gist=28cace98ef0d7677127ce1f4f72f2d5e&version=nightly)

```rust
pub fn sum_me() -> i32 {
    vec![1, 2, 3].iter().sum::<i32>()
}
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This fixes an optimization regression by allowing LLVM to see through more
functions.

Closes #43272

### CODE REVIEW

File: src/test/codegen/vec-optimizes-away.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+//
+// no-system-llvm
+// compile-flags: -O
+#![crate_type="lib"]
+
+#[no_mangle]
+#[no_mangle]
```
Comment (BurntSushi) [inline src/test/codegen/vec-optimizes-away.rs]: Is it intentional to have `#[no_mangle]` repeated here?

File: src/test/codegen/vec-optimizes-away.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+//
+// no-system-llvm
```
Comment (Mark-Simulacrum) [inline src/test/codegen/vec-optimizes-away.rs]: Does this not work on system LLVMs? Is it the typical behavior where LLVM doesn't recognize our allocation functions?

File: src/test/codegen/vec-optimizes-away.rs (hunk 1 above)
Comment (alexcrichton) [inline src/test/codegen/vec-optimizes-away.rs]: Oops, nope!

File: src/test/codegen/vec-optimizes-away.rs (hunk 2 above)
Comment (alexcrichton) [inline src/test/codegen/vec-optimizes-away.rs]: Yeah unfortunately only our LLVM sees our allocation functions.

**Comment by frewsxcv** [comment]
@bors r-

https://github.com/rust-lang/rust/issues/43538

```
[00:51:43] failures:
[00:51:43] 
[00:51:43] ---- [codegen] codegen/vec-optimizes-away.rs stdout ----
[00:51:43] 	
[00:51:43] error: verification with 'FileCheck' failed
[00:51:43] status: exit code: 1
[00:51:43] command: /checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck -input-file=/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/vec-optimizes-away.ll /checkout/src/test/codegen/vec-optimizes-away.rs
[00:51:43] stdout:
[00:51:43] ------------------------------------------
[00:51:43] 
[00:51:43] ------------------------------------------
[00:51:43] stderr:
[00:51:43] ------------------------------------------
[00:51:43] /checkout/src/test/codegen/vec-optimizes-away.rs:18:17: error: expected string not found in input
[00:51:43]  // CHECK-NEXT: bb{{.*}}:
[00:51:43]                 ^
[00:51:43] /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/vec-optimizes-away.ll:7:19: note: scanning from here
[00:51:43] define i32 @sum_me() unnamed_addr #0 personality i32 (...)* @rust_eh_personality {
[00:51:43]                   ^
[00:51:43] /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/vec-optimizes-away.ll:7:52: note: possible intended match here
[00:51:43] define i32 @sum_me() unnamed_addr #0 personality i32 (...)* @rust_eh_personality {
[00:51:43]                                                    ^
[00:51:43] 
[00:51:43] ------------------------------------------
[00:51:43] 
[00:51:43] thread '[codegen] codegen/vec-optimizes-away.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2499:8
[00:51:43] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
