### PR TITLE
Avoid ICE on return outside of fn with literal array

### LINKED ISSUE #64638: ICE with return outside of function body
The following ICE's on stable, beta and nightly:

```Rust
enum Bug {
    V1 = return [0][0]
}
```

<details>
<summary>Backtrace:</summary>

```
error: internal compiler error: src/librustc/ty/context.rs:556: node_type: no type for node `expr [0] (hir_id=HirId { owner: DefIndex(12), local_id: 5 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:650:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: rustc_errors::Handler::bug
  10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc::ty::context::tls::with_opt::{{closure}}
  12: rustc::ty::context::tls::with_context_opt
  13: rustc::ty::context::tls::with_opt
  14: rustc::util::bug::opt_span_bug_fmt
  15: rustc::util::bug::bug_fmt
  16: rustc::ty::context::TypeckTables::node_type::{{closure}}
  17: rustc::ty::context::TypeckTables::expr_ty_adjusted
  18: <rustc_typeck::check::writeback::WritebackCx as rustc::hir::intravisit::Visitor>::visit_expr
  19: <rustc_typeck::check::writeback::WritebackCx as rustc::hir::intravisit::Visitor>::visit_expr
  20: rustc_typeck::check::writeback::<impl rustc_typeck::check::FnCtxt>::resolve_type_vars_in_body
  21: rustc::ty::context::GlobalCtxt::enter_local
  22: rustc_typeck::check::typeck_tables_of
  23: rustc::ty::query::__query_compute::typeck_tables_of
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  27: rustc_mir::const_eval::const_eval_raw_provider
  28: rustc::ty::query::__query_compute::const_eval_raw
  29: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval_raw>::compute
  30: rustc::dep_graph::graph::DepGraph::with_task_impl
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  32: rustc_mir::const_eval::const_eval_provider
  33: rustc::ty::query::__query_compute::const_eval
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::const_eval>::compute
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  37: <rustc_typeck::collect::CollectItemTypesVisitor as rustc::hir::intravisit::Visitor>::visit_item
  38: rustc::hir::map::Map::visit_item_likes_in_module
  39: rustc_typeck::collect::collect_mod_item_types
  40: rustc::ty::query::__query_compute::collect_mod_item_types
  41: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_mod_item_types>::compute
  42: rustc::dep_graph::graph::DepGraph::with_task_impl
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  44: rustc_typeck::check_crate::{{closure}}::{{closure}}
  45: rustc::util::common::time
  46: rustc_typeck::check_crate
  47: rustc_interface::passes::analysis
  48: rustc::ty::query::__query_compute::analysis
  49: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  50: rustc::dep_graph::graph::DepGraph::with_task_impl
  51: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  52: rustc::ty::context::tls::enter_global
  53: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  54: rustc_interface::passes::create_global_ctxt::{{closure}}
  55: rustc_interface::interface::run_compiler_in_existing_thread_pool
  56: std::thread::local::LocalKey<T>::with
  57: scoped_tls::ScopedKey<T>::set
  58: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
#0 [typeck_tables_of] processing `Bug::V1::{{constant}}#0`
#1 [const_eval_raw] const-evaluating `Bug::V1::{{constant}}#0`
#2 [const_eval] const-evaluating + checking `Bug::V1::{{constant}}#0`
#3 [collect_mod_item_types] collecting item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0572`.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0 (eae3437df 2019-08-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```
</details>

Running a quick test in godbolt, the first occurrence of the ICE is in stable 1.25.
Feel free to close if this is a dupe of https://github.com/rust-lang/rust/issues/64620

### PR DESCRIPTION
**Pull request by estebank**
Do not ICE when encountering `enum E { A = return [0][0] }`.

Fix #64638.

### CODE REVIEW

**Comment by estebank** [comment]
The beta nomination is low priority, as the ICE has been present in stable for several releases, but it'd be nice if we can get such a small patch out the door sooner rather than later.

File: src/librustc_typeck/check/writeback.rs [hunk 1]
```diff
@@ -190,9 +190,23 @@ impl<'cx, 'tcx> WritebackCx<'cx, 'tcx> {
...
-            if let ty::Ref(_, base_ty, _) = tables.expr_ty_adjusted(&base).sty {
-                let index_ty = tables.expr_ty_adjusted(&index);
+            // All valid indexing looks like this; might encounter non-valid indexes at this point.
+            let base_ty = tables.expr_ty_adjusted_opt(&base).map(|t| &t.sty);
+            if base_ty.is_none() {
+                self.tcx().sess.delay_span_bug(e.span, &format!("bad base: `{:?}`", base));
+                return;
+            }
+            if let Some(ty::Ref(_, base_ty, _)) = base_ty {
+                let index_ty = match tables.expr_ty_adjusted_opt(&index) {
```
Comment (Centril) [inline src/librustc_typeck/check/writeback.rs]:
```suggestion
                let index_ty = tables.expr_ty_adjusted_opt(&index).unwrap_or_else(|| {
```

File: src/librustc_typeck/check/writeback.rs [hunk 2]
```diff
@@ -190,9 +190,23 @@ impl<'cx, 'tcx> WritebackCx<'cx, 'tcx> {
         if let hir::ExprKind::Index(ref base, ref index) = e.node {
             let mut tables = self.fcx.tables.borrow_mut();
 
-            // All valid indexing looks like this; might encounter non-valid indexes at this point
-            if let ty::Ref(_, base_ty, _) = tables.expr_ty_adjusted(&base).sty {
-                let index_ty = tables.expr_ty_adjusted(&index);
+            // All valid indexing looks like this; might encounter non-valid indexes at this point.
+            let base_ty = tables.expr_ty_adjusted_opt(&base).map(|t| &t.sty);
+            if base_ty.is_none() {
```
Comment (Centril) [inline src/librustc_typeck/check/writeback.rs]: Deserves a comment re. how it is that we got here.

File: src/librustc_typeck/check/writeback.rs [hunk 3]
```diff
@@ -190,9 +190,23 @@ impl<'cx, 'tcx> WritebackCx<'cx, 'tcx> {
...
+                self.tcx().sess.delay_span_bug(e.span, &format!("bad base: `{:?}`", base));
+                return;
+            }
+            if let Some(ty::Ref(_, base_ty, _)) = base_ty {
```
Comment (Centril) [inline src/librustc_typeck/check/writeback.rs]: We are pattern matching on `Some(...)` here anyways so the early return and checking `.is_none()` feels odd -- just use `else {` instead and you won't need `return;` at all.

**Comment by Mark-Simulacrum** [comment]
Un-nominating for beta. We do not have the time to deal with possible failures of this patch -- if this hasn't yet landed on master (or even been approved for that), it's not going to land in time for beta backport.

@rustbot modify labels: -beta-nominated

File: src/librustc_typeck/check/writeback.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_typeck/check/writeback.rs]: I originally didn't have the `return` because it _is_ unnecessary, but then I thought I'd make it clear that we should _not_ continue processing in that case in case more logic is added in the currently inexistent else case below.

Comment (Centril) [reply src/librustc_typeck/check/writeback.rs]: In case you want to have the `None` branch up-front, use a `match` and put `None =>` first then.

File: src/librustc_typeck/check/writeback.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/writeback.rs]: Originally didn't go down that route because I was thinking about `self` borrowing, but `self` is not involved here :)
