### PR TITLE
Suggest function call on pattern type mismatch

### LINKED ISSUE #101208: Provide suggestion for error when `if let` used with enum variant whose values are not initialized
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ac515a35cf754b067d63ab16f3917383)

```rust
enum E {
    One(i32, i32)
}

fn main() {
    let var = E::One;
    if let E::One(var1, var2) = var {
        println!("{var1} {var2}");
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:7:12
  |
7 |     if let E::One(var1, var2) = var {
  |            ^^^^^^^^^^^^^^^^^^   --- this expression has type `fn(i32, i32) -> E {E::One}`
  |            |
  |            expected fn item, found enum `E`
  |
  = note: expected fn item `fn(i32, i32) -> E {E::One}`
                found enum `E`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should suggest to the user that they need to initialize the enum variant's value in order to use the `if let`.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #101208

This could definitely be generalized to support more suggestions in pattern matches. We can't use all of [`FnCtxt::emit_type_mismatch_suggestions`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/fn_ctxt/struct.FnCtxt.html#method.emit_type_mismatch_suggestions), but it's on my to-do list to play around with more suggestions that would be productive in this position.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 1]
```diff
@@ -133,21 +133,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             Ok(InferOk { obligations, value: () }) => {
                 self.register_predicates(obligations);
                 None
             }
-            Err(e) => Some(self.err_ctxt().report_mismatched_types(cause, expected, actual, e)),
+            Err(e) => {
+                let mut diag = self.err_ctxt().report_mismatched_types(cause, expected, actual, e);
+                mutate_err(&mut diag);
+                Some(diag)
+            }
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/demand.rs:155]: Why add a closure, and not have the caller modify the returned value?

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 2]
```diff
@@ -41,7 +41,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         // #55810: Type check patterns first so we get types for all bindings.
         let scrut_span = scrut.span.find_ancestor_inside(expr.span).unwrap_or(scrut.span);
         for arm in arms {
-            self.check_pat_top(&arm.pat, scrutinee_ty, Some(scrut_span), true);
+            self.check_pat_top(&arm.pat, scrutinee_ty, Some(scrut_span), Some(scrut));
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/_match.rs:44]: There are 2 calls to `check_pat_top`, one here and the other is `check_decl`. IIUC, the test covers this case.
Could you complete the test to show the consequences of the change in `check_decl`?

File: compiler/rustc_hir_typeck/src/demand.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/demand.rs:155]: I had originally thought to pass in the TypeError that resulted from the demand call, but then I didn't need it anymore, so this is just an artifact of that old design.

**Comment by compiler-errors** [comment]
It has been two weeks, I'm assuming that @TaKO8Ki is not reviewing at the moment.

r? compiler

**Comment by matthiaskrgr** [comment]
Failed in a rollup (and locally)

````
---- [ui] tests/ui/suggestions/suggest-call-on-pat-mismatch.rs stdout ----
diff of stderr:

4	LL |     if let E::One(var1, var2) = var {
5	   |            ^^^^^^^^^^^^^^^^^^   --- this expression has type `fn(i32, i32) -> E {E::One}`
6	   |            |
-	   |            expected enum constructor, found enum `E`
+	   |            expected enum constructor, found `E`
8	   |
9	   = note: expected enum constructor `fn(i32, i32) -> E {E::One}`
10	                          found enum `E`

19	LL |     let Some(x) = Some;
20	   |         ^^^^^^^   ---- this expression has type `fn(_) -> Option<_> {Option::<_>::Some}`
21	   |         |
-	   |         expected enum constructor, found enum `Option`
+	   |         expected enum constructor, found `Option<_>`
23	   |
24	   = note: expected enum constructor `fn(_) -> Option<_> {Option::<_>::Some}`
25	                          found enum `Option<_>`


The actual stderr differed from the expected stderr.
Actual stderr saved to /home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/test/ui/suggestions/suggest-call-on-pat-mismatch/suggest-call-on-pat-mismatch.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args suggestions/suggest-call-on-pat-mismatch.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/matthias/vcs/github/rust/tests/ui/suggestions/suggest-call-on-pat-mismatch.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--remap-path-prefix=/home/matthias/vcs/github/rust/tests/ui=fake-test-src-base" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/test/ui/suggestions/suggest-call-on-pat-mismatch" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/test/ui/suggestions/suggest-call-on-pat-mismatch/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0308]: mismatched types
  --> fake-test-src-base/suggestions/suggest-call-on-pat-mismatch.rs:7:12
   |
LL |     if let E::One(var1, var2) = var {
   |            ^^^^^^^^^^^^^^^^^^   --- this expression has type `fn(i32, i32) -> E {E::One}`
   |            |
   |            expected enum constructor, found `E`
   |
   = note: expected enum constructor `fn(i32, i32) -> E {E::One}`
                          found enum `E`
help: use parentheses to construct this tuple variant
   |
LL |     if let E::One(var1, var2) = var(/* i32 */, /* i32 */) {
   |                                    ++++++++++++++++++++++

error[E0308]: mismatched types
  --> fake-test-src-base/suggestions/suggest-call-on-pat-mismatch.rs:13:9
   |
LL |     let Some(x) = Some;
   |         ^^^^^^^   ---- this expression has type `fn(_) -> Option<_> {Option::<_>::Some}`
   |         |
   |         expected enum constructor, found `Option<_>`
   |
   = note: expected enum constructor `fn(_) -> Option<_> {Option::<_>::Some}`
                          found enum `Option<_>`
help: use parentheses to construct this tuple variant
   |
LL |     let Some(x) = Some(/* value */);
   |                       +++++++++++++

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
------------------------------------------



failures:
    [ui] tests/ui/suggestions/suggest-call-on-pat-mismatch.rs
````

**Comment by compiler-errors** [comment]
Whoops, matthias commented but didn't r-

@bors r-
