### PR TITLE
Clone region var origins instead of taking them in borrowck

### LINKED ISSUE #12: Evaluation probe in new solver causes ICE in late borrowck
```rust
use std::collections::HashMap;

fn foo() -> &'static HashMap<i32, i32>
{
    &HashMap::new()
}

fn main() {}
```

Causes:

```
thread 'rustc' panicked at 'region constraints already solved', compiler/rustc_infer/src/infer/mod.rs:230:14
```

Since an `evaluate_obligation` call in the new solver doesn't actually call out to a query, so if we've already taken region constraints, a `InferCtxt::probe` call will ICE.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes an issue with the new solver where reporting a borrow-checker error ICEs because it calls `InferCtxt::evaluate_obligation`.

This also removes a handful of unnecessary `tcx.infer_ctxt().build()` calls that are only there to mitigate this same exact issue, but with the old solver.

Fixes compiler-errors/next-solver-hir-issues#12.

----

This implements @aliemjay's solution where we just don't *take* the region constraints, but clone them. This potentially makes it easier to write a bug about taking region constraints twice or never at all, but again, not many folks are touching this code.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Grr, meant to `r? @ghost` for now.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -633,10 +632,7 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
             let Some(default_trait) = tcx.get_diagnostic_item(sym::Default) else {
                 return false;
             };
-            // Regions are already solved, so we must use a fresh InferCtxt,
-            // but the type has region variables, so erase those.
-            tcx.infer_ctxt()
-                .build()
+            self.infcx
                 .type_implements_trait(default_trait, [tcx.erase_regions(ty)], param_env)
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:636]: we can stop erasing regions now when checking this stuff. Please do this here and at every other location where you've switched to the existing infcx.

```suggestion
                .type_implements_trait(default_trait, [ty], param_env)
```

**Review by lcnr — COMMENTED** [review]
nit

r=me afterwards

File: compiler/rustc_infer/src/infer/mod.rs [hunk 2]
```diff
@@ -226,8 +227,14 @@ impl<'tcx> InferCtxtInner<'tcx> {
     #[inline]
     pub fn unwrap_region_constraints(&mut self) -> RegionConstraintCollector<'_, 'tcx> {
         self.region_constraint_storage
-            .as_mut()
-            .expect("region constraints already solved")
+            // Replace region constraints if they've been taken.
+            // This should only happen on an error path, so delay a bug.
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/mod.rs:231]:
```suggestion
            // This should only happen on an error path, so delay a bug.
            //
            // This is only allowed so that one can use the existing inference
            // context for diagnostics.
```

**Review by aliemjay — CHANGES_REQUESTED** [review]

File: compiler/rustc_infer/src/infer/mod.rs [hunk 3]
```diff
@@ -226,8 +227,14 @@ impl<'tcx> InferCtxtInner<'tcx> {
...
+            .get_or_insert_with(|| {
+                ty::tls::with(|tcx| {
+                    tcx.sess.delay_span_bug(DUMMY_SP, "region constraints already solved");
+                });
+                RegionConstraintStorage::default()
+            })
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/mod.rs:237]: Maybe we can keep it named `take_` name, but set some flag that the infos have been taken, and delay a bug if we try to take them again or try to borrow them again?

[the remark this answers is not in the document]
Comment (aliemjay) [reply compiler/rustc_infer/src/infer/mod.rs:237]: Mm, I have no strong opinion here, but I don't like delaying a bug in InferCtxt. I prefer the code there to be independent from the compilation session as much as possible.

Changing `take_region_var_infos` is unfortunate as it would no longer guard against future addition of region constraints, but I think it's the best option here given that it's used only once in borrowck and we don't expect users of InferCtxt to implement their own region resolution.

**Comment by compiler-errors** [comment]
Ok, took the alternative approach.

@rustbot ready

File: compiler/rustc_infer/src/infer/mod.rs [hunk 4]
```diff
@@ -115,12 +115,7 @@ pub struct InferCtxtInner<'tcx> {
     float_unification_storage: ut::UnificationTableStorage<ty::FloatVid>,
 
     /// Tracks the set of region variables and the constraints between them.
-    ///
-    /// This is initially `Some(_)` but when
-    /// `resolve_regions_and_report_errors` is invoked, this gets set to `None`
-    /// -- further attempts to perform unification, etc., may fail if new
-    /// region constraints would've been added.
-    region_constraint_storage: Option<RegionConstraintStorage<'tcx>>,
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/mod.rs:123]: I think it's worth keeping this `Option` and  clearing it in InferCtxt::{resolve_regions,skip_region_resolution} . This way limit this hack to MIR borrowck, rather that lexical region resolver which is more commonly used.

**Review by aliemjay — APPROVED** [review]
r? @aliemjay
looks good. r=me with or without the previous nit.

**Comment by compiler-errors** [comment]
Ok, changed it back to `Option`.

@bors r=aliemjay

**Comment by compiler-errors** [comment]
Rebased

@bors r=aliemjay
