### PR TITLE
Fix bad caching of `~const Drop` bounds

### LINKED ISSUE #92111: `T: Drop` bound not satisfied from Option::unwrap_or (et. al) when Drop anti-bound is present
### Code

I tried this code:

```rust
pub trait NoDrop{}

impl<T: Drop> NoDrop for T{}

#[derive(Debug)]
pub struct DoesNotHaveDrop(i32);

impl NoDrop for DoesNotHaveDrop{}

fn main() {
    let x = Some(DoesNotHaveDrop(0));
    println!("{:?}",x.unwrap_or(DoesNotHaveDrop(0)))
}
```

I expected to see this happen: print `DoesNotHaveDrop(0)` (from Debug impl)

Instead, this happened: E0277, trait impl `DoesNotHaveDrop: Drop` not found

This was found by CI in the Ruffle Project: https://github.com/ruffle-rs/ruffle/runs/4576592287?check_suite_focus=true

The issue is caused by the effective anti-bound of Drop, introduced by the manual impl of the `NoDrop` trait, as well as the PR #91928 which introduced `~const Drop` bounds for a number of functions in `Option`.

### Version it worked on

It most recently worked on: rustc 1.59.0-nightly (7abab1efb 2021-12-18)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (91a0600a5 2021-12-18)
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by fee1-dead**
Fixes #92111.

### CODE REVIEW

**Comment by fee1-dead** [comment]
This is potentially perf-sensitive:

@bors try @rust-timer queue

**Comment by fee1-dead** [comment]
Just some thoughts: perf suggests that always checking if a trait is the `Drop` lang item in trait system is a bad idea. I wonder if we could remap `T: ~const Drop` bound to `T: ConstDrop` and kept `ConstDrop` private to libstd and librustc.

**Comment by oli-obk** [comment]
The big regression is in llvm, which can't be a result of this PR. The 0.3% regressions look legit (typeck), but considering this pretty bad regression, let's take the hit.

File: src/test/ui/rfc-2632-const-trait-impl/issue-92111.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
+// Regression test for #92111.
+//
+// The issue was that we normalize trait bounds before caching
+// results of selection. Checking that `impl NoDrop for S` requires
```
Comment (MinerSebas) [inline src/test/ui/rfc-2632-const-trait-impl/issue-92111.rs:4]:
```suggestion
// results of selection. Checking that `impl Tr for S` requires
```

Comment (fee1-dead) [reply src/test/ui/rfc-2632-const-trait-impl/issue-92111.rs:4]: Nice catch! Though bors has already begun testing this PR. The fix would probably have to be separated to another PR.

File: compiler/rustc_middle/src/ty/mod.rs [hunk 2]
```diff
@@ -734,6 +734,15 @@ pub struct TraitPredicate<'tcx> {
 pub type PolyTraitPredicate<'tcx> = ty::Binder<'tcx, TraitPredicate<'tcx>>;
 
 impl<'tcx> TraitPredicate<'tcx> {
+    pub fn remap_constness(&mut self, tcx: TyCtxt<'tcx>, param_env: &mut ParamEnv<'tcx>) {
+        if unlikely!(Some(self.trait_ref.def_id) == tcx.lang_items().drop_trait()) {
```
Comment (Aaron1011) [inline compiler/rustc_middle/src/ty/mod.rs:738]: It seems kind of weird to be special-casing `Drop` here. Are there any other traits that need this kind of special handling? Are you sure that this method is called in all of the places where it needs to be?

Comment (fee1-dead) [reply compiler/rustc_middle/src/ty/mod.rs:738]: 1. No because we only need to special case `~const Drop` bounds.
2. Yes because I have audited all usages of a method I added made for exactly this purpose. Remapping `T: ~const SomeTrait` to `T: SomeTrait` when not in a const context. 

See also https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/~const.20Drop which would be a better solution

**Comment by RalfJung** [comment]
@fee1-dead why does this have the const-hack label? The code changed here isn't even in `const fn` I think?

**Comment by fee1-dead** [comment]
well to be more specific this should be types-hack or const-traits-hack. I suppose the scope of const-hack is for mostly library functions using an uglier version of code because the more clean version can't be done in const yet? then we can remove it from this (this is already fixed anyways)
