### PR TITLE
Suggest removing a semicolon after derive attributes

### LINKED ISSUE #93942: suggest removing ; after derive attribute in case of error
Given the following code: 

```rust
#[derive(Debug, Clone)];
struct Todo {
    item: String,
}
```

The current output is:

```
error: expected item after attributes
 --> src/main.rs:5:1
  |
5 | #[derive(Debug, Clone)];
  | ^^^^^^^^^^^^^^^^^^^^^^^
```

Ideally the output should look like:

Rust could point at the semicolon (which causes the error) and suggest removing it in this case.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #93942

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -449,6 +450,21 @@ impl<'a> Parser<'a> {
         if end.is_doc_comment() {
             err.span_label(end.span, "this doc comment doesn't document anything");
         }
+        if end.meta_kind().is_some() {
+            let pos = end.span.hi() + BytePos(1);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:454]: Does this cause an ICE with a multi-byte unicode character following the attribute? I fear that the `+ BytePos(1)` might.

You might want to instead use [`SourceMap::next_point`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/source_map/struct.SourceMap.html#method.next_point) or something similar.

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -449,6 +450,21 @@ impl<'a> Parser<'a> {
...
+            let semi_span = end.span.shrink_to_hi().with_hi(pos);
+            match self.sess.source_map().span_to_snippet(semi_span) {
+                Ok(snippet) if snippet.ends_with(';') => {
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/item.rs:457]: Instead of fetching the source map and doing a textual comparison, could we check the current token to be a semicolon?

**Comment by cjgillot** [comment]
Thanks @TaKO8Ki! Could you squash the two commits together?

**Comment by TaKO8Ki** [comment]
@cjgillot 
I squashed my commits!
