### PR TITLE
E0034: provide disambiguated syntax for candidates

### LINKED ISSUE #37767: E0034 should provide the disambiguated syntax for the candidates
Currently, with the following code:

```rust
trait A { fn foo(&self) {} }
trait B : A { fn foo(&self) {} }

fn bar<T: B>(a: &T) {
  a.foo()
}

fn main() {}
```

prints the following error message:

```shell
error[E0034]: multiple applicable items in scope
 --> <anon>:5:5
  |
5 |   a.foo()
  |     ^^^ multiple `foo` found
  |
note: candidate #1 is defined in the trait `A`
 --> <anon>:1:11
  |
1 | trait A { fn foo(&self) {} }
  |           ^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `B`
 --> <anon>:2:15
  |
2 | trait B : A { fn foo(&self) {} }
  |               ^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

It would be nice if it would tell me what exactly do I need to type in order to choose candidate 1 or candidate 2. In particular, when associated types, Input/Output parameters, ... are involved, the disambiguation syntax can be tricky.

### PR DESCRIPTION
**Pull request by estebank**
For a given file

```rust
trait A { fn foo(&self) {} }
trait B : A { fn foo(&self) {} }

fn bar<T: B>(a: &T) {
  a.foo()
}
```

provide the following output

```
error[E0034]: multiple applicable items in scope
 --> file.rs:6:5
  |
6 |   a.foo(1)
  |     ^^^ multiple `foo` found
  |
note: candidate #1 is defined in the trait `A`
 --> file.rs:2:11
  |
2 | trait A { fn foo(&self, a: usize) {} }
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: to use it here write `A::foo(&a, 1)` instead
 --> file.rs:6:5
  |
6 |   a.foo(1)
  |     ^^^
note: candidate #2 is defined in the trait `B`
 --> file.rs:3:15
  |
3 | trait B : A { fn foo(&self, a: usize) {} }
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: to use it here write `B::foo(&a, 1)` instead
 --> file.rs:6:5
  |
6 |   a.foo(1)
  |     ^^^
```

Fix #37767.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems good to me. I'll just wait for someone else's opinion.

cc @jonathandturner

File: src/librustc_typeck/check/method/suggest.rs [hunk 1]
```diff
@@ -70,7 +70,8 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                rcvr_ty: Ty<'tcx>,
                                item_name: ast::Name,
                                rcvr_expr: Option<&hir::Expr>,
-                               error: MethodError<'tcx>) {
+                               error: MethodError<'tcx>,
+                               args: Option<&'gcx [hir::Expr]>) {
```
Comment (nrc) [inline src/librustc_typeck/check/method/suggest.rs]: In the `None` case here, could you pass an empty slice, and then not require `Option<...>`? If not, you should add a comment, explaining when and why to use `None`.

File: src/librustc_typeck/check/method/suggest.rs [hunk 2]
```diff
@@ -130,6 +131,15 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                    "candidate #{} is defined in the trait `{}`",
                                    idx + 1,
                                    self.tcx.item_path_str(trait_did));
+                        err.span_help(span,
```
Comment (nrc) [inline src/librustc_typeck/check/method/suggest.rs]: I would make this a non-span help, since the span is already part of the error, I don't think it is necessary to show the span twice.

File: src/librustc_typeck/check/method/suggest.rs [hunk 3]
```diff
@@ -130,6 +131,15 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                      &format!("to use it here write `{}::{}({}{})` instead",
+                                               self.tcx.item_path_str(trait_did),
+                                               item_name,
+                                               if rcvr_ty.is_region_ptr() { "&" } else { "" },
```
Comment (nrc) [inline src/librustc_typeck/check/method/suggest.rs]: Do you need to check for `&mut` here?

File: src/librustc_typeck/check/mod.rs [hunk 4]
```diff
@@ -4075,7 +4079,7 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                     _ => Def::Err,
                 };
                 if item_name != keywords::Invalid.name() {
-                    self.report_method_error(span, ty, item_name, None, error);
+                    self.report_method_error(span, ty, item_name, None, error, None);
```
Comment (nrc) [inline src/librustc_typeck/check/mod.rs]: Why are there no args here? Is it just that we don't have access to them, or are they inappropriate?

Comment (nrc) [inline src/librustc_typeck/check/mod.rs]: If the former, then I'd prefer to output `foo(...)` rather than `foo()`

File: src/librustc_typeck/check/method/suggest.rs [hunk 5]
```diff
@@ -130,6 +131,15 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                    "candidate #{} is defined in the trait `{}`",
                                    idx + 1,
                                    self.tcx.item_path_str(trait_did));
+                        err.span_help(span,
+                                      &format!("to use it here write `{}::{}({}{})` instead",
```
Comment (nrc) [inline src/librustc_typeck/check/method/suggest.rs]: I would change the text to "to disambiguate the method call, write `...`"

**Review by nrc — CHANGES_REQUESTED** [review]

File: src/librustc/ty/sty.rs [hunk 6]
```diff
@@ -1088,6 +1088,17 @@ impl<'a, 'gcx, 'tcx> TyS<'tcx> {
         }
     }
 
+    pub fn is_mutable(&self) -> bool {
```
Comment (nrc) [inline src/librustc/ty/sty.rs]: This might be better named is_mutable_pointer

File: src/librustc_typeck/check/mod.rs (hunk 4 above)
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: > If the former, then I'd prefer to output foo(...) rather than foo()

[This is the case](https://github.com/rust-lang/rust/pull/38168/files#diff-45ff4c3ed02cc75f5b8162af5d9c782bR147) now.

File: src/librustc/ty/sty.rs (hunk 6 above)
Comment (estebank) [inline src/librustc/ty/sty.rs]: [Done](https://github.com/rust-lang/rust/pull/38168/commits/d1807859685a6d17f8b9fca35fcc6022e91de8a8).

**Comment by nrc** [comment]
r=me, but failing tests

**Review by nrc — APPROVED** [review]

**Comment by estebank** [comment]
@nrc tests fixed after rebase/squash.
