### PR TITLE
Fix Access Violation when using lld & ThinLTO on windows-msvc

### LINKED ISSUE #81408: ACCESS_VIOLATION when dereferencing once_cell::Lazy in closure with LTO
The code in the following repository crashes with an ACCESS_VIOLATION on Windows: https://github.com/roblabla/reproduce-boom/

To reproduce, four things are needed:

- Using LLD linker
- Building with Thin LTO
- Splitting the main binary and a library.

**EDIT:** Better reproducer can be found [here](https://github.com/rust-lang/rust/issues/81408#issuecomment-847122562).

The main.rs file:

```rust
fn main() {
    reproducer::run()();
}
```

The lib.rs file:

```rust
use once_cell::sync::Lazy;

static CHANNEL: Lazy<()> = Lazy::new(|| ());

pub fn run() -> impl FnOnce() {
    || {
        let _ = *CHANNEL;
        println!("Did not crash.")
    }
}
```

Running `cargo run --release` will trigger the following output:

```
   Finished release [optimized + debuginfo] target(s) in 0.02s
     Running `C:/Users/roblabla/cargo_target\release\reproducer.exe`
error: process didn't exit successfully: `C:/Users/roblabla/cargo_target\release\reproducer.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

--------

This issue seems related to ThinLTO. It only occurs on windows.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-pc-windows-msvc
release: 1.49.0
```

<details><summary>Backtrace</summary>
<p>

```
[0x0]   reproducer!core::sync::atomic::atomic_compare_exchange + 0x3
[0x1]   reproducer!core::sync::atomic::AtomicUsize::compare_exchange + 0x3
[0x2]   reproducer!core::sync::atomic::AtomicUsize::compare_and_swap + 0x3
[0x3]   reproducer!once_cell::imp::wait + 0x5c
[0x4]   reproducer!once_cell::imp::initialize_inner + 0xcc
[0x5]   reproducer!once_cell::imp::OnceCell<tuple<>>::initialize<tuple<>,closure-0,once_cell::sync::{{impl}}::get_or_init::Void> + 0x41
[0x6]   reproducer!once_cell::sync::OnceCell<tuple<>>::get_or_try_init + 0x19
[0x7]   reproducer!once_cell::sync::OnceCell<tuple<>>::get_or_init + 0x19
[0x8]   reproducer!once_cell::sync::Lazy<tuple<>, fn()>::force + 0x19
[0x9]   reproducer!once_cell::sync::{{impl}}::deref + 0x19
[0xa]   reproducer!reproducer::run::{{closure}} + 0x19
[0xb]   reproducer!core::future::from_generator::{{impl}}::poll + 0x19
[0xc]   reproducer!reproducer::run + 0x7d
[0xd]   reproducer!reproducer::main + 0xc6
[0xe]   reproducer!core::ops::function::FnOnce::call_once + 0x2
[0xf]   reproducer!std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>> + 0x6
[0x10]   reproducer!std::rt::lang_start::{{closure}}<tuple<>> + 0xc
[0x11]   reproducer!core::ops::function::impls::{{impl}}::call_once + 0x6
[0x12]   reproducer!std::panicking::try::do_call + 0x6
[0x13]   reproducer!std::panicking::try + 0x6
[0x14]   reproducer!std::panic::catch_unwind + 0x6
[0x15]   reproducer!std::rt::lang_start_internal + 0xd9
[0x16]   reproducer!main + 0x27
[0x17]   reproducer!invoke_main + 0x22
[0x18]   reproducer!__scrt_common_main_seh + 0x10c
[0x19]   KERNEL32!BaseThreadInitThunk + 0x14
[0x1a]   ntdll!RtlUserThreadStart + 0x21
```

</p>
</details>

### PR DESCRIPTION
**Pull request by wesleywiser**
Users report an AV at runtime of the compiled binary when using lld and ThinLTO on windows-msvc. The AV occurs when accessing a static value which is defined in one crate but used in another. Based on the disassembly of the cross-crate use, it appears that the use is not correctly linked with the definition and is instead assigned a garbage pointer value.

If we look at the symbol tables for each crates' obj file, we can see what is happening:

*lib.obj*:

```
COFF SYMBOL TABLE
...
00E 00000000 SECT2  notype       External     | _ZN10reproducer7memrchr2FN17h612b61ca0e168901E
...
```

*bin.obj*:

```
COFF SYMBOL TABLE
...
010 00000000 UNDEF  notype       External     | __imp__ZN10reproducer7memrchr2FN17h612b61ca0e168901E
...
```

The use of the symbol has the "import" style symbol name but the declaration doesn't generate any symbol with the same name. As a result, linking the files generates a warning from lld:

> rust-lld: warning: bin.obj: locally defined symbol imported: reproducer::memrchr::FN::h612b61ca0e168901 (defined in lib.obj) [LNK4217]

and the symbol reference remains undefined at runtime leading to the AV.

To fix this, we just need to detect that we are performing ThinLTO (and thus, static linking) and omit the `dllimport` attribute on the extern item in LLVM IR.

Fixes #81408

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? compiler

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 1]
```diff
@@ -389,7 +390,19 @@ impl<'ll, 'tcx> CodegenCx<'ll, 'tcx> {
...
         // start) and then strongly recommending static linkage on Windows!
-        let use_dll_storage_attrs = tcx.sess.target.is_like_windows;
+        let use_dll_storage_attrs = tcx.sess.target.is_like_windows
+            // We don't support dynamic linking with ThinLTO so if it is enabled,
+            // we know that there is no need to mark items `dllimport`/`dllexport`.
+            // Fixes #81408 which occurs because lld does not fix up our mismatched
+            // `dllimport`/`dllexport` annotations.
+            // Note: eventually if we want to support a mixed ThinLTO & dynamic linking
+            // scenario where some crates are statically linked via ThinLTO and others
+            // are dynamically linked, then this check needs to become more precise
```
Comment (bjorn3) [inline compiler/rustc_codegen_llvm/src/context.rs:400]: https://github.com/rust-lang/rust/pull/101403 will enable LTO (fat and thin) for rust dynamic libraries and use on rustc itself.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/context.rs:400]: Also shouldn't dllimport be valid even for items in the same dll/exe?

Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/context.rs:400]: Does #101403 handle the problem described here? 

https://github.com/rust-lang/rust/blob/657f246812ab2684e3c3954b1c77f98fd59e0b21/compiler/rustc_session/src/session.rs#L1429-L1441

Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/context.rs:400]: > Also shouldn't dllimport be valid even for items in the same dll/exe?

I'm not sure how it could since the symbols don't line up. I also tried marking the definition with `dllexport` to try to get that to work but it doesn't seem to work either under ThinLTO.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/context.rs:400]: > Does https://github.com/rust-lang/rust/pull/101403 handle the problem described here?

That problem seems to be about linker plugin LTO, but #101403 uses rust LTO.

> I'm not sure how it could since the symbols don't line up.

It has to as in case of `extern "C" { ... }` we don't know yet if it will be a dll import or a local import. Not using dllimport would break if it is actually imported from a dll, so we have to unconditionally use it if we don't know if it is imported from a dll or not afaik.

Comment (mati865) [reply compiler/rustc_codegen_llvm/src/context.rs:400]: > > Also shouldn't dllimport be valid even for items in the same dll/exe?
> 
> I'm not sure how it could since the symbols don't line up. I also tried marking the definition with `dllexport` to try to get that to work but it doesn't seem to work either under ThinLTO.

Was it AV as well or some other problem?

**Comment by estebank** [comment]
r=me on the code changes, but I believe maybe r? @bjorn3.

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 1 above)
Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/context.rs]: Ah, ok I see. We can move this check closer to the point where we decide if we should apply `dllimport` or not specifically for Rust items, not for `extern "C"` symbols. I also gave this patch a try rebased on top of #101403 and after enabling ThinLTO in `config.toml`, I can confirm that both link.exe and lld can link rustc correctly. So based on that, I think the scenario I was originally concerned about should work fine.

**Comment by bjorn3** [comment]
I'm not a windows export, so I'm going to reassign it again.

r? compiler

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 1 above)
Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/context.rs]: > Was it AV as well or some other problem?

Sorry @mati865, GitHub didn't show me your comment for some reason. It was the same AV as happens currently.

Comment (mati865) [reply compiler/rustc_codegen_llvm/src/context.rs]: No problem.
It bothers me why it does work with `windows-gnu` with ThinLTO and LLD, I have gut feeling one of LLD's magic tricks when running in MinGW mode somehow fixes the problem. One of them could be enabled by passing `-stdcall-fixup` (depending on the context it does more than the name implies) to LLD but I guees it's not worth to be bothered by it.

**Comment by michaelwoerister** [comment]
Great find, @wesleywiser! 

Could you try to add a regression test for this?

**Comment by wesleywiser** [comment]
Thanks for the push to add a test @michaelwoerister! Added 🙂

**Comment by wesleywiser** [comment]
@michaelwoerister Now that #103610 has been merged, this should be ready to go.

**Comment by michaelwoerister** [comment]
Thanks, @wesleywiser! 
@bors r+
