### PR TITLE
CI: build FreeBSD artifacts on FreeBSD 13.4

### LINKED ISSUE #132185: FreeBSD segfault when capturing backtrace with RUST_BACKTRACE=1
### Problem

With recent nightly toolchains, cargo segfaults on FreeBSD x86_64.  The 2024-10-17 toolchain worked fine, but the bug was present in the  2024-10-24 toolchain .  The segfault is dependent on the `RUST_BACKTRACE=1` environment variable being set. This bug is causing rust-lang/libc's CI to fail.

An example CI failure:
https://github.com/rust-lang/libc/runs/32002285710

The stack trace of the segfault:
```
Program received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseCIE (addressSpace=..., cie=18446744073501904251, cieInfo=0x7fffffffacb0)
    at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/DwarfParser.hpp:332
332	  pint_t cieLength = (pint_t)addressSpace.get32(p);
(gdb) bt
#0  libunwind::CFI_Parser<libunwind::LocalAddressSpace>::parseCIE (addressSpace=..., cie=18446744073501904251, cieInfo=0x7fffffffacb0)
    at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/DwarfParser.hpp:332
rust-lang/cargo#1  0x0000000802b4ea0c in libunwind::CFI_Parser<libunwind::LocalAddressSpace>::findFDE (addressSpace=..., pc=pc@entry=19184556, ehSectionStart=41958640, sectionLength=<optimized out>, 
    fdeHint=fdeHint@entry=0, fdeInfo=fdeInfo@entry=0x7ffffffface8, cieInfo=0x7fffffffacb0) at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/DwarfParser.hpp:264
rust-lang/cargo#2  0x0000000802b4e6a2 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::getInfoFromDwarfSection (this=this@entry=0x7fffffffb330, pc=pc@entry=19184556, 
    sects=..., fdeSectionOffsetHint=fdeSectionOffsetHint@entry=0) at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/UnwindCursor.hpp:1689
rust-lang/cargo#3  0x0000000802b4bb60 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister (this=0x7fffffffb330, isReturnAddress=true)
    at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/UnwindCursor.hpp:2634
rust-lang/cargo#4  0x0000000802b4b9b2 in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step (this=0x7fffffffb330, stage2=<optimized out>)
    at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/UnwindCursor.hpp:2946
rust-lang/cargo#5  0x0000000802b48ef9 in _Unwind_Backtrace (callback=0x25720d0 <std::backtrace_rs::backtrace::libunwind::trace::trace_fn>, ref=0x7fffffffb4d8)
    at /usr/home/somers/src/freebsd.org/src/contrib/llvm-project/libunwind/src/UnwindLevel1-gcc-ext.c:156
rust-lang/cargo#6  0x0000000002558fd5 in std::backtrace_rs::backtrace::libunwind::trace () at std/src/../../backtrace/src/backtrace/libunwind.rs:116
rust-lang/cargo#7  std::backtrace_rs::backtrace::trace_unsynchronized<std::backtrace::{impl#4}::create::{closure_env#0}> () at std/src/../../backtrace/src/backtrace/mod.rs:66
rust-lang/cargo#8  std::backtrace::Backtrace::create () at std/src/backtrace.rs:331
rust-lang/cargo#9  0x0000000002558e40 in std::backtrace::Backtrace::capture () at std/src/backtrace.rs:296
rust-lang/cargo#10 0x00000000011d5c08 in <anyhow::Error as core::convert::From<clap_builder::error::Error>>::from ()
rust-lang/cargo#11 0x00000000018a1f26 in <cargo::util::errors::CliError as core::convert::From<clap_builder::error::Error>>::from ()
rust-lang/cargo#12 0x00000000012de941 in cargo::cli::main ()
rust-lang/cargo#13 0x00000000012d14e4 in cargo::main ()
rust-lang/cargo#14 0x00000000012c98e3 in std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()> ()
rust-lang/cargo#15 0x00000000012eebf9 in std::rt::lang_start::<()>::{closure#0} ()
rust-lang/cargo#16 0x0000000002558047 in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)>
    () at core/src/ops/function.rs:284
rust-lang/cargo#17 std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at std/src/panicking.rs:557
rust-lang/cargo#18 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at std/src/panicking.rs:520
rust-lang/cargo#19 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at std/src/panic.rs:358
rust-lang/cargo#20 std::rt::lang_start_internal::{closure#1} () at std/src/rt.rs:174
rust-lang/cargo#21 std::panicking::try::do_call<std::rt::lang_start_internal::{closure_env#1}, isize> () at std/src/panicking.rs:557
rust-lang/cargo#22 std::panicking::try<isize, std::rt::lang_start_internal::{closure_env#1}> () at std/src/panicking.rs:520
rust-lang/cargo#23 std::panic::catch_unwind<std::rt::lang_start_internal::{closure_env#1}, isize> () at std/src/panic.rs:358
rust-lang/cargo#24 std::rt::lang_start_internal () at std/src/rt.rs:174
rust-lang/cargo#25 0x00000000012d58d5 in main ()
```

### Steps

In a FreeBSD x86_64 environment with the latest nightly toolchain installed:

1. git clone git@github.com:rust-lang/libc.git
2. cd libc
3. env RUST_BACKTRACE=1 cargo test --features extra_traits --manifest-path libc-test/Cargo.toml --target x86_64-unknown-freebsd

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```
> cargo version --verbose
cargo 1.84.0-nightly (cf53cc54b 2024-10-18)
release: 1.84.0-nightly
commit-hash: cf53cc54bb593b5ec3dc2be4b1702f50c36d24d5
commit-date: 2024-10-18
host: x86_64-unknown-freebsd
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: FreeBSD 15.0-CURRENT [64-bit]
```

### PR DESCRIPTION
**Pull request by asomers**
13.2 is EoL, and 13.3 will be EoL too in about 2 months.  Plus, both suffer from a bug in LLVM's libunwind.  It causes a segfault inside of std::backtrace::Backtrace::capture().

Fixes #132185

cc @ehuss .  before you can do the trybuild, you'll also have to download new FreeBSD 13.4 base.txz images and place them in https://ci-mirrors.rust-lang.org/rustc , then update this PR with the correct file names.

try-job: dist-x86_64-freebsd
try-job: dist-various-2

### CODE REVIEW

File: src/ci/docker/scripts/freebsd-toolchain.sh [hunk 1]
```diff
@@ -59,7 +59,7 @@ done
 
 # Originally downloaded from:
 # URL=https://download.freebsd.org/ftp/releases/${freebsd_arch}/${freebsd_version}-RELEASE/base.txz
-URL=https://ci-mirrors.rust-lang.org/rustc/2024-02-18-freebsd-${freebsd_version}-${freebsd_arch}-base.txz
+URL=https://ci-mirrors.rust-lang.org/rustc/2024-XX-XX-freebsd-${freebsd_version}-${freebsd_arch}-base.txz
```
Comment (Urgau) [inline src/ci/docker/scripts/freebsd-toolchain.sh:62]: @MarcoIeni would you mind uploading the new artefacts to your CI mirrors.

Comment (MarcoIeni) [reply src/ci/docker/scripts/freebsd-toolchain.sh:62]: I downloaded base.txz from https://download.freebsd.org/releases/amd64/13.4-RELEASE/ and https://download.freebsd.org/releases/i386/13.4-RELEASE/

I'm uploading them to `2024-09-13-freebsd-13.4-amd64-base.txz` and `2024-09-13-freebsd-13.4-i386-base.txz`. The upload should be done in 5 minutes

**Comment by asomers** [comment]
@ehuss it should be ready to try now.

**Comment by ehuss** [comment]
Hm, I'm not sure if this will work with conflicts.

@bors try

**Comment by ehuss** [comment]
Yea, can you resolve the conflicts first?

**Comment by asomers** [comment]
@ehuss resolved.

**Comment by asomers** [comment]
That build failure was due to a merge error.  @Mark-Simulacrum @ehuss can you please `try` again?

**Comment by asomers** [comment]
@ehuss could you please explain to me how to download the artifacts?

**Comment by Urgau** [comment]
You can use [`rustup-toolchain-install-master`](https://github.com/kennytm/rustup-toolchain-install-master) to manage try-builded toolchains.
See the [usage](https://github.com/kennytm/rustup-toolchain-install-master?tab=readme-ov-file#usage) sections for a detailed workflow.

*The sha to use is the one [from the build commit](https://github.com/rust-lang/rust/pull/132232#issuecomment-2442275659).*

**Comment by asomers** [comment]
Thank you @Urgau .  I am please to report that once I installed the try-built toolchain and rebuilt cargo locally, the locally-built cargo was able to build multiple projects without error, with RUST_BACKTRACE=1 .

**Comment by ehuss** [comment]
Nice! Is the plan to sit on this until January?

**Comment by asomers** [comment]
> Nice! Is the plan to sit on this until January?

Yeah, that's my plan.

**Comment by Urgau** [comment]
Wouldn't it be better to merge it now on nightly since current master (1.84) is going to be released as stable on January 09 2025?

**Comment by asomers** [comment]
@urgau that works for me.

**Comment by asomers** [comment]
@Urgau @ehuss @Mark-Simulacrum can we merge this PR now?  Now that it's 2025 ?

**Comment by Urgau** [comment]
Last try was two months ago, let's see if it still works.

@bors try

**Comment by Urgau** [comment]
Seems like you also need to update those lines,
https://github.com/rust-lang/rust/blob/13f3924c675f5a678a849ac87412710b8bca6636/src/ci/docker/host-x86_64/dist-various-2/Dockerfile#L59-L61
