### PR TITLE
Ensure `swap_nonoverlapping` is really always untyped

### LINKED ISSUE #134713: `std::ptr::swap_nonoverlapping` is not always untyped
### Code

I tried this code:

```rust
#![allow(unused)]
use std::mem::{size_of, align_of};

#[repr(C)]
struct Foo(usize, u8);

fn main() {
    let buf1: [usize; 2] = [1000, 2000];
    let buf2: [usize; 2] = [3000, 4000];
    
    // Foo and [usize; 2] have the same size and alignment,
    // so swap_nonoverlapping should treat them the same
    assert_eq!(size_of::<Foo>(), size_of::<[usize; 2]>());
    assert_eq!(align_of::<Foo>(), align_of::<[usize; 2]>());
    
    let mut b1 = buf1;
    let mut b2 = buf2;
    // Safety: b1 and b2 are distinct local variables,
    // with the same size and alignment as Foo.
    unsafe {
        std::ptr::swap_nonoverlapping(
            b1.as_mut_ptr().cast::<Foo>(),
            b2.as_mut_ptr().cast::<Foo>(),
            1,
        );
    }
    assert_eq!(b1, buf2); // Fails: [3000, 160] != [3000, 4000] or [3000, 1952] != [3000, 4000]
    assert_eq!(b2, buf1); // Fails: [1000, 208] != [1000, 2000] or [1000, 4048] != [1000, 2000]
}
```

[godbolt link](https://rust.godbolt.org/z/s391rbG1j)

I expected to see this happen: The two `assert_eq!`s should succeed; `b1` and `b2` should be completely swapped, since [`std::ptr::swap_nonoverlapping::<T>`](https://doc.rust-lang.org/nightly/std/ptr/fn.swap_nonoverlapping.html) claims to swap bytes, not `T`s.

Instead, this happened: They are not entirely swapped. `swap_nonoverlapping` appears to be doing a typed swap at `Foo`, skipping/zeroing/not-correctly-swapping the 7 padding bytes at the end of `Foo`.

I think this only happens with types where `size_of::<T>() > size_of::<usize>()` from looking at the implementation, but I'm not sure.

In debug mode:
Rust 1.61-1.70 appear to consistently give `[3000, 160]`.
Rust 1.71-nightly appear to consistently give `[3000, 1952]`.
4000 is `0x0fa0`
160 is `0x00a0`
1952 is `0x07a0`
2000 is `0x07d0`
so it looks like Rust 1.61-1.70 are zeroing the padding bytes, and Rust 1.71-nightly are ignoring them.

### Version it worked on

It most recently worked on: Rust 1.60

### Version with regression

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### LINKED ISSUE #134946: Stop emitting one-at-a-time byte ops when swapping byte arrays
Mentioned on Discord https://discord.com/channels/273534239310479360/592856094527848449/1319367290902286367

Demo when swapping `[u8; 44]`: <https://rust.godbolt.org/z/rznror9aG>

Especially with opt-level 2, there's still
```asm
        movzx   eax, byte ptr [rdi + 32]
        movzx   ecx, byte ptr [rsi + 32]
        mov     byte ptr [rdi + 32], cl
        mov     byte ptr [rsi + 32], al
        movzx   eax, byte ptr [rdi + 33]
        movzx   ecx, byte ptr [rsi + 33]
        mov     byte ptr [rdi + 33], cl
        mov     byte ptr [rsi + 33], al
        movzx   eax, byte ptr [rdi + 34]
        movzx   ecx, byte ptr [rsi + 34]
        mov     byte ptr [rdi + 34], cl
        mov     byte ptr [rsi + 34], al
        movzx   eax, byte ptr [rdi + 35]
        movzx   ecx, byte ptr [rsi + 35]
        mov     byte ptr [rdi + 35], cl
        mov     byte ptr [rsi + 35], al
        movzx   eax, byte ptr [rdi + 36]
        movzx   ecx, byte ptr [rsi + 36]
        mov     byte ptr [rdi + 36], cl
        mov     byte ptr [rsi + 36], al
        movzx   eax, byte ptr [rdi + 37]
        movzx   ecx, byte ptr [rsi + 37]
        mov     byte ptr [rdi + 37], cl
        mov     byte ptr [rsi + 37], al
        movzx   eax, byte ptr [rdi + 38]
        movzx   ecx, byte ptr [rsi + 38]
        mov     byte ptr [rdi + 38], cl
        mov     byte ptr [rsi + 38], al
        movzx   eax, byte ptr [rdi + 39]
        movzx   ecx, byte ptr [rsi + 39]
        mov     byte ptr [rdi + 39], cl
        mov     byte ptr [rsi + 39], al
        movzx   eax, byte ptr [rdi + 40]
        movzx   ecx, byte ptr [rsi + 40]
        mov     byte ptr [rdi + 40], cl
        mov     byte ptr [rsi + 40], al
        movzx   eax, byte ptr [rdi + 41]
        movzx   ecx, byte ptr [rsi + 41]
        mov     byte ptr [rdi + 41], cl
        mov     byte ptr [rsi + 41], al
        movzx   eax, byte ptr [rdi + 42]
        movzx   ecx, byte ptr [rsi + 42]
        mov     byte ptr [rdi + 42], cl
        mov     byte ptr [rsi + 42], al
        movzx   eax, byte ptr [rdi + 43]
        movzx   ecx, byte ptr [rsi + 43]
        mov     byte ptr [rdi + 43], cl
        mov     byte ptr [rsi + 43], al
        ret
```

And in opt-level 3 it's 
```llvm
  %x16.i.i.i = getelementptr inbounds i8, ptr %a, i64 32, !dbg !55
  %y18.i.i.i = getelementptr inbounds i8, ptr %b, i64 32, !dbg !62
  %a19.i.i.i = load i8, ptr %x16.i.i.i, align 1, !dbg !12
  %b20.i.i.i = load i8, ptr %y18.i.i.i, align 1, !dbg !44
  store i8 %b20.i.i.i, ptr %x16.i.i.i, align 1, !dbg !48
  store i8 %a19.i.i.i, ptr %y18.i.i.i, align 1, !dbg !53
  %x16.i.i.i.1 = getelementptr inbounds i8, ptr %a, i64 33, !dbg !55
  %y18.i.i.i.1 = getelementptr inbounds i8, ptr %b, i64 33, !dbg !62
  %a19.i.i.i.1 = load i8, ptr %x16.i.i.i.1, align 1, !dbg !12
  %b20.i.i.i.1 = load i8, ptr %y18.i.i.i.1, align 1, !dbg !44
  store i8 %b20.i.i.i.1, ptr %x16.i.i.i.1, align 1, !dbg !48
  store i8 %a19.i.i.i.1, ptr %y18.i.i.i.1, align 1, !dbg !53
  %x16.i.i.i.2 = getelementptr inbounds i8, ptr %a, i64 34, !dbg !55
  %y18.i.i.i.2 = getelementptr inbounds i8, ptr %b, i64 34, !dbg !62
  %a19.i.i.i.2 = load i8, ptr %x16.i.i.i.2, align 1, !dbg !12
  %b20.i.i.i.2 = load i8, ptr %y18.i.i.i.2, align 1, !dbg !44
  store i8 %b20.i.i.i.2, ptr %x16.i.i.i.2, align 1, !dbg !48
  store i8 %a19.i.i.i.2, ptr %y18.i.i.i.2, align 1, !dbg !53
  %x16.i.i.i.3 = getelementptr inbounds i8, ptr %a, i64 35, !dbg !55
  %y18.i.i.i.3 = getelementptr inbounds i8, ptr %b, i64 35, !dbg !62
  %a19.i.i.i.3 = load i8, ptr %x16.i.i.i.3, align 1, !dbg !12
  %b20.i.i.i.3 = load i8, ptr %y18.i.i.i.3, align 1, !dbg !44
  store i8 %b20.i.i.i.3, ptr %x16.i.i.i.3, align 1, !dbg !48
  store i8 %a19.i.i.i.3, ptr %y18.i.i.i.3, align 1, !dbg !53
  %x16.i.i.i.4 = getelementptr inbounds i8, ptr %a, i64 36, !dbg !55
  %y18.i.i.i.4 = getelementptr inbounds i8, ptr %b, i64 36, !dbg !62
  %a19.i.i.i.4 = load i8, ptr %x16.i.i.i.4, align 1, !dbg !12
  %b20.i.i.i.4 = load i8, ptr %y18.i.i.i.4, align 1, !dbg !44
  store i8 %b20.i.i.i.4, ptr %x16.i.i.i.4, align 1, !dbg !48
  store i8 %a19.i.i.i.4, ptr %y18.i.i.i.4, align 1, !dbg !53
  %x16.i.i.i.5 = getelementptr inbounds i8, ptr %a, i64 37, !dbg !55
  %y18.i.i.i.5 = getelementptr inbounds i8, ptr %b, i64 37, !dbg !62
  %a19.i.i.i.5 = load i8, ptr %x16.i.i.i.5, align 1, !dbg !12
  %b20.i.i.i.5 = load i8, ptr %y18.i.i.i.5, align 1, !dbg !44
  store i8 %b20.i.i.i.5, ptr %x16.i.i.i.5, align 1, !dbg !48
  store i8 %a19.i.i.i.5, ptr %y18.i.i.i.5, align 1, !dbg !53
  %x16.i.i.i.6 = getelementptr inbounds i8, ptr %a, i64 38, !dbg !55
  %y18.i.i.i.6 = getelementptr inbounds i8, ptr %b, i64 38, !dbg !62
  %a19.i.i.i.6 = load i8, ptr %x16.i.i.i.6, align 1, !dbg !12
  %b20.i.i.i.6 = load i8, ptr %y18.i.i.i.6, align 1, !dbg !44
  store i8 %b20.i.i.i.6, ptr %x16.i.i.i.6, align 1, !dbg !48
  store i8 %a19.i.i.i.6, ptr %y18.i.i.i.6, align 1, !dbg !53
  %x16.i.i.i.7 = getelementptr inbounds i8, ptr %a, i64 39, !dbg !55
  %y18.i.i.i.7 = getelementptr inbounds i8, ptr %b, i64 39, !dbg !62
  %a19.i.i.i.7 = load i8, ptr %x16.i.i.i.7, align 1, !dbg !12
  %b20.i.i.i.7 = load i8, ptr %y18.i.i.i.7, align 1, !dbg !44
  store i8 %b20.i.i.i.7, ptr %x16.i.i.i.7, align 1, !dbg !48
  store i8 %a19.i.i.i.7, ptr %y18.i.i.i.7, align 1, !dbg !53
  %x16.i.i.i.8 = getelementptr inbounds i8, ptr %a, i64 40, !dbg !55
  %y18.i.i.i.8 = getelementptr inbounds i8, ptr %b, i64 40, !dbg !62
  %a19.i.i.i.8 = load i8, ptr %x16.i.i.i.8, align 1, !dbg !12
  %b20.i.i.i.8 = load i8, ptr %y18.i.i.i.8, align 1, !dbg !44
  store i8 %b20.i.i.i.8, ptr %x16.i.i.i.8, align 1, !dbg !48
  store i8 %a19.i.i.i.8, ptr %y18.i.i.i.8, align 1, !dbg !53
  %x16.i.i.i.9 = getelementptr inbounds i8, ptr %a, i64 41, !dbg !55
  %y18.i.i.i.9 = getelementptr inbounds i8, ptr %b, i64 41, !dbg !62
  %a19.i.i.i.9 = load i8, ptr %x16.i.i.i.9, align 1, !dbg !12
  %b20.i.i.i.9 = load i8, ptr %y18.i.i.i.9, align 1, !dbg !44
  store i8 %b20.i.i.i.9, ptr %x16.i.i.i.9, align 1, !dbg !48
  store i8 %a19.i.i.i.9, ptr %y18.i.i.i.9, align 1, !dbg !53
  %x16.i.i.i.10 = getelementptr inbounds i8, ptr %a, i64 42, !dbg !55
  %y18.i.i.i.10 = getelementptr inbounds i8, ptr %b, i64 42, !dbg !62
  %a19.i.i.i.10 = load i8, ptr %x16.i.i.i.10, align 1, !dbg !12
  %b20.i.i.i.10 = load i8, ptr %y18.i.i.i.10, align 1, !dbg !44
  store i8 %b20.i.i.i.10, ptr %x16.i.i.i.10, align 1, !dbg !48
  store i8 %a19.i.i.i.10, ptr %y18.i.i.i.10, align 1, !dbg !53
  %x16.i.i.i.11 = getelementptr inbounds i8, ptr %a, i64 43, !dbg !55
  %y18.i.i.i.11 = getelementptr inbounds i8, ptr %b, i64 43, !dbg !62
  %a19.i.i.i.11 = load i8, ptr %x16.i.i.i.11, align 1, !dbg !12
  %b20.i.i.i.11 = load i8, ptr %y18.i.i.i.11, align 1, !dbg !44
  store i8 %b20.i.i.i.11, ptr %x16.i.i.i.11, align 1, !dbg !48
  store i8 %a19.i.i.i.11, ptr %y18.i.i.i.11, align 1, !dbg !53
  ret void, !dbg !65
```

### PR DESCRIPTION
**Pull request by scottmcm**
This replaces #134954, which was arguably overcomplicated.

## Fixes #134713

Actually using the type passed to `ptr::swap_nonoverlapping` for anything other than its size + align turns out to not work, so this goes back to always erasing the types down to just bytes.

(Except in `const`, which keeps doing the same thing as before to preserve @RalfJung's fix from #134689)

## Fixes #134946

I'd previously moved the swapping to use auto-vectorization *on bytes*, but someone pointed out on Discord that the tail loop handling from that left a whole bunch of byte-by-byte swapping around.  This goes back to manual tail handling to avoid that, then still triggers auto-vectorization on pointer-width values.  (So you'll see `<4 x i64>` on `x86-64-v3` for example.)

### CODE REVIEW

File: library/core/src/ptr/mod.rs
Comment (RalfJung) [inline library/core/src/ptr/mod.rs:1]: Could you add a Miri test for the example from https://github.com/rust-lang/rust/issues/134713?

File: src/tools/miri/tests/pass/stdlib/swap_nonoverlapping_is_untyped.rs
Comment (RalfJung) [inline src/tools/miri/tests/pass/stdlib/swap_nonoverlapping_is_untyped.rs:1]: That's a new folder, isn't it? We have tons of stdlib tests so this only makes things more confusing I think.

Since this tests a particular issue, what about putting it in `issues/issue-134713-swap_nonoverlapping_untyped.rs` or something like that?

Comment (RalfJung) [reply src/tools/miri/tests/pass/stdlib/swap_nonoverlapping_is_untyped.rs:1]: Thanks!

**Comment by ibraheemdev** [comment]
Passing this one along because I'm not the best person to review this. r? libs

**Comment by jhpratt** [comment]
I'm mostly sticking to the trivial PRs at the moment as my review capacity is limited. Re-rolling again.

r? libs

File: library/core/src/ptr/mod.rs [hunk 1]
```diff
@@ -1094,49 +1095,26 @@ pub const unsafe fn swap_nonoverlapping<T>(x: *mut T, y: *mut T, count: usize) {
...
     )
 }
 
 /// Same behavior and safety conditions as [`swap_nonoverlapping`]
-///
-/// LLVM can vectorize this (at least it can for the power-of-two-sized types
-/// `swap_nonoverlapping` tries to use) so no need to manually SIMD it.
 #[inline]
-const unsafe fn swap_nonoverlapping_simple_untyped<T>(x: *mut T, y: *mut T, count: usize) {
+const unsafe fn swap_nonoverlapping_const<T>(x: *mut T, y: *mut T, count: usize) {
```
Comment (RalfJung) [inline library/core/src/ptr/mod.rs:1117]: This one still does copies which are "too typed", doesn't it? It copeis at `MaybeUninit<T>` which has the padding problem.

Please make do the copies using `copy_nonoverlapping` instead.

File: library/core/src/ptr/mod.rs [hunk 2]
```diff
@@ -1094,49 +1095,26 @@ pub const unsafe fn swap_nonoverlapping<T>(x: *mut T, y: *mut T, count: usize) {
...
-                        // alignment requirements, and that the division is exact so
-                        // that we don't lose any bytes off the end.
-                        return unsafe { swap_nonoverlapping_simple_untyped(x, y, count) };
-                    }
-                };
+            // Going though a slice here helps codegen know the size fits in `isize`
+            let slice = slice_from_raw_parts_mut(x, count);
+            // SAFETY: We have two non-overlapping ranges in memory and they're both
+            // readable so don't include the null address, thus they're at most
+            // `(usize::MAX - 1)/2 = isize::MAX` bytes long.
```
Comment (RalfJung) [inline library/core/src/ptr/mod.rs:1104]: I don't understand this comment. Every readable contiguous range of memory is at most `isize::MAX` bytes long as that is the largest possible allocation.

**Review by RalfJung — APPROVED** [review]
The code changes LGTM for the non-`const` path; see the comment for the `const` path.

I did not look at the tests; I think that needs an LLVM/codegen expert. @nikic maybe?

**Comment by RalfJung** [comment]
To be clear I only reviewed for correctness, I cannot judge whether all the tricks to get better performance actually work.

File: tests/codegen/swap-large-types.rs [hunk 3]
```diff
@@ -52,39 +49,61 @@ pub fn swap_slice(x: &mut [KeccakBuffer], y: &mut [KeccakBuffer]) {
...
 }
 
-// But for a large align-1 type, vectorized byte copying is what we want.
-
 type OneKilobyteBuffer = [u8; 1024];
 
 // CHECK-LABEL: @swap_1kb_slices
 #[no_mangle]
 pub fn swap_1kb_slices(x: &mut [OneKilobyteBuffer], y: &mut [OneKilobyteBuffer]) {
     // CHECK-NOT: alloca
```
[the remark this answers is not in the document]
Comment (cuviper) [reply tests/codegen/swap-large-types.rs:57]: Doesn't that goal deserve an inline comment?

File: library/core/src/ptr/mod.rs (hunk 2 above)
Comment (RalfJung) [reply library/core/src/ptr/mod.rs:1104]: This is documented at https://doc.rust-lang.org/nightly/std/ptr/index.html#allocated-object

File: library/core/src/ptr/mod.rs (hunk 1 above)
Comment (RalfJung) [reply library/core/src/ptr/mod.rs:1116]: CTFE fails to detect this UB. But that doesn't make it not-UB.

**Review by cuviper — APPROVED** [review]
LGTM!

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/139571#issuecomment-2789598180

**Comment by Mark-Simulacrum** [comment]
Correctness fix, relatively small set of regressed scenarios, compared to number of improvements. Marking as triaged.
