### PR TITLE
`-Znext-solver` Prevent committing unfulfilled unsized coercion

### LINKED ISSUE #266: unsize coercions diagnosics path can be triggered for valid code
https://github.com/rust-lang/rust/blob/f21b4c0888ca6a388fcf9365fc0044fa0642ab98/compiler/rustc_hir_typeck/src/coercion.rs#L1990-L1998

The issue is that hitting the recursion limit of the proof tree visitor results in the incorrect behavior. https://github.com/rust-lang/rust/blob/f21b4c0888ca6a388fcf9365fc0044fa0642ab98/compiler/rustc_trait_selection/src/solve/inspect/analyse.rs#L443-L450

My understanding from https://rust-lang.zulipchat.com/#narrow/channel/364551-t-types.2Ftrait-system-refactor/topic/crater.20triage.20.3A3/near/572970037 is the following, but not confident here:

We check whether the reason unsized coercions fail is due to a failing where-clause of a `Unsize` or `CoerceUnsized` impl iirc. This should only matter in case the coercion is actually required, and is purely for diagnostics. Using the coercion is otherwise always wrong.

However, if we encounter the recursion limit of the `ProoTreeVisitor` during this check, we incorrectly emit a failiing `Coerce` goal even though the coercion is not necessary.

Need to either expose a way to decide what to do when hitting the recursion limit, or change the structure of this visitor is some other way. This issue feels fairly easy to solve, doing so in a nice way seems potentially challenging or non-trivial.

Affects `gl_engine` and multiple other users of `glium` apparently :>

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/266

r? lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/coercion/unfulfilled-unsize-coercion-recursion-limit.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
+            .add(0.0)
```
Comment (ShoyuVanilla) [inline tests/ui/traits/next-solver/coercion/unfulfilled-unsize-coercion-recursion-limit.rs:23]: Added some more `.add` calls from adwin's original code to make it sure this exceeds the default recursion limit (`10`)

File: compiler/rustc_trait_selection/src/solve/inspect/analyse.rs [hunk 2]
```diff
@@ -443,6 +443,8 @@ impl<'a, 'tcx> InspectGoal<'a, 'tcx> {
     pub(crate) fn visit_with<V: ProofTreeVisitor<'tcx>>(&self, visitor: &mut V) -> V::Result {
         if self.depth < visitor.config().max_depth {
             try_visit!(visitor.visit_goal(self));
+        } else {
+            return visitor.on_recursion_limit();
         }
 
         V::Result::output()
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/solve/inspect/analyse.rs]: that can be simplified

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 3]
```diff
@@ -2019,4 +2019,11 @@ impl<'tcx> ProofTreeVisitor<'tcx> for CoerceVisitor<'_, 'tcx> {
             }
         }
     }
+
+    fn on_recursion_limit(&mut self) -> Self::Result {
+        // This prevents accidentally committing unfulfilled unsized coercions while trying to find
+        // the error source for diagnostics.
+        // See https://github.com/rust-lang/trait-system-refactor-initiative/issues/266.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]: i think this breaks the following snippet if we encounter it in the `Certainty::Maybe` recursion

```rust
struct W<T: ?Sized>(T);
type Four<T: ?Sized> = W<W<W<W<T>>>>;
type Sixteen<T: ?Sized> = Four<Four<Four<Four<T>>>>;
fn ret<T>(x: T) -> Sixteen<T> {
    todo!();
}
fn please_coerce() {
    let mut y = Default::default();
    let x = ret(y);
    let _: &Sixteen<dyn Send> = &x;
    y = 1u32;
}
```

Comment (ShoyuVanilla) [reply compiler/rustc_hir_typeck/src/coercion.rs]: Oops, I missed the case that we could visit nested goal here 😅
https://github.com/rust-lang/rust/blob/7b25457166468840db16998f507296675f0e07a0/compiler/rustc_hir_typeck/src/coercion.rs#L2012-L2015

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 4]
```diff
@@ -1961,6 +1961,8 @@ impl<'tcx> CoerceMany<'tcx> {
 struct CoerceVisitor<'a, 'tcx> {
     fcx: &'a FnCtxt<'a, 'tcx>,
     span: Span,
+    // Whether the coercion is impossible and just continuing to visit to locate the error source.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs]:
```suggestion
    /// Whether the coercion is impossible. If so we someties still try to
    /// coerce in these cases to emit better errors. This impacts changes the
    /// behavior when hitting the recursion limit.
```

**Review by lcnr — COMMENTED** [review]
comment nit, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152444/7b25457166468840db16998f507296675f0e07a0..96d2318269976785a32b4c45ba9513465b8db702)*
