### PR TITLE
dont create unnecessary `DefId`s under mgca

### LINKED ISSUE #148838: ICE: `generics_of: unexpected node kind ConstArg(ConstArg`
auto-reduced (treereduce-rust):
````rust
#![feature(min_generic_const_args)]
#![feature(generic_const_exprs)]
struct Both<const is_123: u32 = 3, T> {
    a: A<{ B::<1>::M }>,
}

````

original:
````rust
#![non_upper_case_globals = "ABCD"]
#![yes_ord(dead_code)]

struct Both<const is_123: u32=3, T> {
    a: A<{ B::<1>::M }>,
}

````

Version information
````
rustc 1.93.0-nightly (2636cb4c1 2025-11-11)
binary: rustc
commit-hash: 2636cb4c1328f5a3ab05b8d13a666ac5f3a48a08
commit-date: 2025-11-11
host: x86_64-unknown-linux-gnu
release: 1.93.0-nightly
LLVM version: 21.1.5

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/2636cb4c1328f5a3ab05b8d13a666ac5f3a48a08/compiler/rustc_hir_analysis/src/collect/generics_of.rs#L206-L218

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(min_generic_const_args) -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: generic parameters with a default must be trailing
 --> /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:1:19
  |
1 | struct Both<const is_123: u32 = 3, T> {
  |                   ^^^^^^

error[E0412]: cannot find type `A` in this scope
 --> /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:8
  |
1 | struct Both<const is_123: u32 = 3, T> {
  |                                    - similarly named type parameter `T` defined here
2 |     a: A<{ B::<1>::M }>,
  |        ^ help: a type parameter with a similar name exists: `T`

warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs`

error: internal compiler error: compiler/rustc_hir_analysis/src/collect/generics_of.rs:212:14: generics_of: unexpected node kind ConstArg(ConstArg { hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).14), kind: Path(Resolved(None, Path { span: /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:12: 2:21 (#0), res: Err, segments: [PathSegment { ident: B#0, hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).12), res: Err, args: Some(GenericArgs { args: [Const(ConstArg { hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).11), kind: Anon(AnonConst { hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).9), def_id: DefId(0:9 ~ mvce[f463]::Both::a::{constant#0}::{constant#0}), body: BodyId { hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).10) }, span: /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:16: 2:17 (#0) }) })], constraints: [], parenthesized: No, span_ext: /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:15: 2:18 (#0) }), infer_args: false }, PathSegment { ident: M#0, hir_id: HirId(DefId(0:3 ~ mvce[f463]::Both).13), res: Err, args: None, infer_args: false }] })) })
 --> /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:12
  |
2 |     a: A<{ B::<1>::M }>,
  |            ^^^^^^^^^


thread 'rustc' (1550694) panicked at compiler/rustc_hir_analysis/src/collect/generics_of.rs:212:14:
Box<dyn Any>
stack backtrace:
   0:     0x7fe014e77793 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8508b8692a67f424
   1:     0x7fe015601afc - core::fmt::write::h892b976990d68807
   2:     0x7fe014e2c113 - std::io::Write::write_fmt::h2cfb6ae7ceafc18f
   3:     0x7fe014e3d722 - std::sys::backtrace::BacktraceLock::print::h6b401f5a90fe0615
   4:     0x7fe014e438b9 - std::panicking::default_hook::{{closure}}::h4bcd3e8272ea6e1e
   5:     0x7fe014e433e3 - std::panicking::default_hook::hc47768de8da9bf00
   6:     0x7fe013e32f01 - std[2b52140d45a5d53]::panicking::update_hook::<alloc[f328c0b594c54d96]::boxed::Box<rustc_driver_impl[ff76f056f877a8d6]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7fe014e43cdb - std::panicking::panic_with_hook::h50a148ea39b0e607
   8:     0x7fe013e6ee31 - std[2b52140d45a5d53]::panicking::begin_panic::<rustc_errors[76704593d079f0be]::ExplicitBug>::{closure#0}
   9:     0x7fe013e61576 - std[2b52140d45a5d53]::sys::backtrace::__rust_end_short_backtrace::<std[2b52140d45a5d53]::panicking::begin_panic<rustc_errors[76704593d079f0be]::ExplicitBug>::{closure#0}, !>
  10:     0x7fe013e610d7 - std[2b52140d45a5d53]::panicking::begin_panic::<rustc_errors[76704593d079f0be]::ExplicitBug>
  11:     0x7fe013e8d641 - <rustc_errors[76704593d079f0be]::diagnostic::BugAbort as rustc_errors[76704593d079f0be]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7fe0143f588c - <rustc_errors[76704593d079f0be]::DiagCtxtHandle>::span_bug::<rustc_span[1859fa485aa88c5d]::span_encoding::Span, alloc[f328c0b594c54d96]::string::String>
  13:     0x7fe014418dc7 - rustc_middle[48f5e10766353194]::util::bug::opt_span_bug_fmt::<rustc_span[1859fa485aa88c5d]::span_encoding::Span>::{closure#0}
  14:     0x7fe0144190ca - rustc_middle[48f5e10766353194]::ty::context::tls::with_opt::<rustc_middle[48f5e10766353194]::util::bug::opt_span_bug_fmt<rustc_span[1859fa485aa88c5d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7fe014409ecb - rustc_middle[48f5e10766353194]::ty::context::tls::with_context_opt::<rustc_middle[48f5e10766353194]::ty::context::tls::with_opt<rustc_middle[48f5e10766353194]::util::bug::opt_span_bug_fmt<rustc_span[1859fa485aa88c5d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7fe012710ec7 - rustc_middle[48f5e10766353194]::util::bug::span_bug_fmt::<rustc_span[1859fa485aa88c5d]::span_encoding::Span>
  17:     0x7fe015fa2578 - rustc_hir_analysis[95d84e02a3e62ea1]::collect::generics_of::generics_of
  18:     0x7fe01561b969 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::generics_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>
  19:     0x7fe01561c046 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::DefIdCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  20:     0x7fe01561bd6b - rustc_query_impl[d248f320eda2a0f9]::query_impl::generics_of::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7fe015fa080f - rustc_hir_analysis[95d84e02a3e62ea1]::collect::generics_of::generics_of
  22:     0x7fe01561b969 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::generics_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7fe01561c046 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::DefIdCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  24:     0x7fe01561bd6b - rustc_query_impl[d248f320eda2a0f9]::query_impl::generics_of::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7fe015fe8f82 - rustc_hir_analysis[95d84e02a3e62ea1]::collect::predicates_of::gather_explicit_predicates_of::{closure#0}
  26:     0x7fe015fe6c10 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::explicit_predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 24usize]>>
  27:     0x7fe01574449a - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::DefIdCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  28:     0x7fe015743da2 - rustc_query_impl[d248f320eda2a0f9]::query_impl::explicit_predicates_of::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fe015743183 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 24usize]>>
  30:     0x7fe0157444b9 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::DefIdCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  31:     0x7fe015743ca2 - rustc_query_impl[d248f320eda2a0f9]::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fe015ae3748 - rustc_ty_utils[8aae495b601b2150]::ty::param_env
  33:     0x7fe015ae2cd9 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::param_env::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7fe01561c046 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::DefIdCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  35:     0x7fe01561bb31 - rustc_query_impl[d248f320eda2a0f9]::query_impl::param_env::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fe01631b6c3 - rustc_hir_typeck[429764d9bd7be61f]::typeck_with_inspect::{closure#0}
  37:     0x7fe0163162c6 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7fe015889777 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_data_structures[e91f46092e6bce0]::vec_cache::VecCache<rustc_span[1859fa485aa88c5d]::def_id::LocalDefId, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[636933bf47b8a8e3]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  39:     0x7fe015889109 - rustc_query_impl[d248f320eda2a0f9]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7fe01588a5d7 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::used_trait_imports::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>>
  41:     0x7fe015889777 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_data_structures[e91f46092e6bce0]::vec_cache::VecCache<rustc_span[1859fa485aa88c5d]::def_id::LocalDefId, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[636933bf47b8a8e3]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  42:     0x7fe015889049 - rustc_query_impl[d248f320eda2a0f9]::query_impl::used_trait_imports::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7fe015888abd - rustc_hir_analysis[95d84e02a3e62ea1]::check_unused::check_unused_traits
  44:     0x7fe0158889a9 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::check_unused_traits::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 0usize]>>
  45:     0x7fe0166917e6 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::SingleCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  46:     0x7fe0166914c2 - rustc_query_impl[d248f320eda2a0f9]::query_impl::check_unused_traits::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7fe0160fc86f - rustc_hir_analysis[95d84e02a3e62ea1]::check_crate
  48:     0x7fe01655f770 - rustc_interface[5c2f13e94b4905f7]::passes::analysis
  49:     0x7fe01655f433 - rustc_query_impl[d248f320eda2a0f9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d248f320eda2a0f9]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 0usize]>>
  50:     0x7fe0166917e6 - rustc_query_system[636933bf47b8a8e3]::query::plumbing::try_execute_query::<rustc_query_impl[d248f320eda2a0f9]::DynamicConfig<rustc_query_system[636933bf47b8a8e3]::query::caches::SingleCache<rustc_middle[48f5e10766353194]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d248f320eda2a0f9]::plumbing::QueryCtxt, false>
  51:     0x7fe01669143c - rustc_query_impl[d248f320eda2a0f9]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7fe0168d83c3 - <rustc_interface[5c2f13e94b4905f7]::passes::create_and_enter_global_ctxt<core[38695eb0a3e4dc55]::option::Option<rustc_interface[5c2f13e94b4905f7]::queries::Linker>, rustc_driver_impl[ff76f056f877a8d6]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[38695eb0a3e4dc55]::ops::function::FnOnce<(&rustc_session[e86e12dfad9d04f]::session::Session, rustc_middle[48f5e10766353194]::ty::context::CurrentGcx, alloc[f328c0b594c54d96]::sync::Arc<rustc_data_structures[e91f46092e6bce0]::jobserver::Proxy>, &std[2b52140d45a5d53]::sync::once_lock::OnceLock<rustc_middle[48f5e10766353194]::ty::context::GlobalCtxt>, &rustc_data_structures[e91f46092e6bce0]::sync::worker_local::WorkerLocal<rustc_middle[48f5e10766353194]::arena::Arena>, &rustc_data_structures[e91f46092e6bce0]::sync::worker_local::WorkerLocal<rustc_hir[9e147bcb7655fc56]::Arena>, rustc_driver_impl[ff76f056f877a8d6]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  53:     0x7fe0167a7b29 - rustc_interface[5c2f13e94b4905f7]::interface::run_compiler::<(), rustc_driver_impl[ff76f056f877a8d6]::run_compiler::{closure#0}>::{closure#1}
  54:     0x7fe01673ad87 - std[2b52140d45a5d53]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5c2f13e94b4905f7]::util::run_in_thread_with_globals<rustc_interface[5c2f13e94b4905f7]::util::run_in_thread_pool_with_globals<rustc_interface[5c2f13e94b4905f7]::interface::run_compiler<(), rustc_driver_impl[ff76f056f877a8d6]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  55:     0x7fe01673aa68 - <<std[2b52140d45a5d53]::thread::Builder>::spawn_unchecked_<rustc_interface[5c2f13e94b4905f7]::util::run_in_thread_with_globals<rustc_interface[5c2f13e94b4905f7]::util::run_in_thread_pool_with_globals<rustc_interface[5c2f13e94b4905f7]::interface::run_compiler<(), rustc_driver_impl[ff76f056f877a8d6]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[38695eb0a3e4dc55]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:     0x7fe016740bef - std::sys::thread::unix::Thread::new::thread_start::h91d6dca458fee5fb
  57:     0x7fe00fe969cb - <unknown>
  58:     0x7fe00ff1aa0c - <unknown>
  59:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.93.0-nightly (2636cb4c1 2025-11-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(min_generic_const_args) -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [generics_of] computing generics of `Both::a::{constant#0}`
#1 [generics_of] computing generics of `Both::a::{constant#0}::{constant#0}`
#2 [explicit_predicates_of] computing explicit predicates of `Both::a::{constant#0}::{constant#0}`
#3 [predicates_of] computing predicates of `Both::a::{constant#0}::{constant#0}`
#4 [param_env] computing normalized predicates of `Both::a::{constant#0}::{constant#0}`
#5 [typeck] type-checking `Both::a::{constant#0}::{constant#0}`
#6 [used_trait_imports] finding used_trait_imports `Both::a::{constant#0}::{constant#0}`
#7 [check_unused_traits] checking unused trait imports in crate
#8 [analysis] running analysis passes on crate `mvce`
end of query stack
error[E0433]: failed to resolve: use of undeclared type `B`
 --> /tmp/icemaker_global_tempdir.pMUmmFc3ZGer/rustc_testrunner_tmpdir_reporting.aRsqC0nvtFAY/mvce.rs:2:12
  |
2 |     a: A<{ B::<1>::M }>,
  |            ^
  |            |
  |            use of undeclared type `B`
  |            help: a type parameter with a similar name exists: `T`

error: aborting due to 5 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0412, E0433, E0601.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-generic_const_exprs

### LINKED ISSUE #149977: ICE: mgca: `No HirId for DefId`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --crate-type=lib
#![feature(min_generic_const_args)]
fn foo<const N: usize, const K: usize>() -> [u32; K] {
    [0; K]
}

````

original:
````rust
//@ ignore-auxiliary (used by `./allow-in-other-module.rs`)

// This should not warn.
#![allow(not_a_real_lint)]

// This should not warn, either.
fn foo<const N: usize, const K: usize>(_data: [u32; N]) -> [u32; K] {
    [0; K]
}

````

Version information
````
rustc 1.94.0-nightly (3f4dc1e02 2025-12-14)
binary: rustc
commit-hash: 3f4dc1e02d759aa3c3807d4efc1f7f6e293536a5
commit-date: 2025-12-14
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.5

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/3f4dc1e02d759aa3c3807d4efc1f7f6e293536a5/compiler/rustc_middle/src/hir/mod.rs#L378-L390

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(min_generic_const_args) --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: function `foo` is never used
 --> /tmp/icemaker_global_tempdir.U3pUa92njTMT/rustc_testrunner_tmpdir_reporting.EHEsm5rsaJxS/mvce.rs:1:4
  |
1 | fn foo<const N: usize, const K: usize>() -> [u32; K] {
  |    ^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

error: internal compiler error: compiler/rustc_middle/src/hir/mod.rs:384:32: No HirId for DefId(0:6 ~ mvce[3999]::foo::{constant#0})


thread 'rustc' (2689906) panicked at compiler/rustc_middle/src/hir/mod.rs:384:32:
Box<dyn Any>
stack backtrace:
   0:     0x7faba2190173 - <<std[e49fa185a119b89b]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[17865207963548b5]::fmt::Display>::fmt
   1:     0x7faba2810648 - core[17865207963548b5]::fmt::write
   2:     0x7faba21a67c6 - <std[e49fa185a119b89b]::sys::stdio::unix::Stderr as std[e49fa185a119b89b]::io::Write>::write_fmt
   3:     0x7faba2166938 - std[e49fa185a119b89b]::panicking::default_hook::{closure#0}
   4:     0x7faba2184043 - std[e49fa185a119b89b]::panicking::default_hook
   5:     0x7faba11741d7 - std[e49fa185a119b89b]::panicking::update_hook::<alloc[756b9f94e2773738]::boxed::Box<rustc_driver_impl[e1c4671be5271ce8]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7faba2184322 - std[e49fa185a119b89b]::panicking::panic_with_hook
   7:     0x7faba11b0c61 - std[e49fa185a119b89b]::panicking::begin_panic::<rustc_errors[c34899de065ee3bb]::ExplicitBug>::{closure#0}
   8:     0x7faba11a12b6 - std[e49fa185a119b89b]::sys::backtrace::__rust_end_short_backtrace::<std[e49fa185a119b89b]::panicking::begin_panic<rustc_errors[c34899de065ee3bb]::ExplicitBug>::{closure#0}, !>
   9:     0x7faba11a0efa - std[e49fa185a119b89b]::panicking::begin_panic::<rustc_errors[c34899de065ee3bb]::ExplicitBug>
  10:     0x7faba11ce351 - <rustc_errors[c34899de065ee3bb]::diagnostic::BugAbort as rustc_errors[c34899de065ee3bb]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7faba1771e09 - rustc_middle[7055997c00c0bb98]::util::bug::opt_span_bug_fmt::<rustc_span[ce53af16555a42ff]::span_encoding::Span>::{closure#0}
  12:     0x7faba1771f92 - rustc_middle[7055997c00c0bb98]::ty::context::tls::with_opt::<rustc_middle[7055997c00c0bb98]::util::bug::opt_span_bug_fmt<rustc_span[ce53af16555a42ff]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7faba176376b - rustc_middle[7055997c00c0bb98]::ty::context::tls::with_context_opt::<rustc_middle[7055997c00c0bb98]::ty::context::tls::with_opt<rustc_middle[7055997c00c0bb98]::util::bug::opt_span_bug_fmt<rustc_span[ce53af16555a42ff]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7fab9fc6b994 - rustc_middle[7055997c00c0bb98]::util::bug::bug_fmt
  15:     0x7faba28f3a47 - rustc_query_impl[462c6a5584cea8d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[462c6a5584cea8d4]::query_impl::local_def_id_to_hir_id::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7faba28f2e37 - rustc_query_system[5be0c069f6d5c539]::query::plumbing::try_execute_query::<rustc_query_impl[462c6a5584cea8d4]::DynamicConfig<rustc_data_structures[30161969bbcb553f]::vec_cache::VecCache<rustc_span[ce53af16555a42ff]::def_id::LocalDefId, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5be0c069f6d5c539]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[462c6a5584cea8d4]::plumbing::QueryCtxt, false>
  17:     0x7faba28f2b8b - rustc_query_impl[462c6a5584cea8d4]::query_impl::local_def_id_to_hir_id::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7faba323692e - <rustc_metadata[2002d9e21ce78884]::rmeta::encoder::EncodeContext>::encode_def_ids
  19:     0x7faba324f4df - <rustc_metadata[2002d9e21ce78884]::rmeta::encoder::EncodeContext>::encode_crate_root
  20:     0x7faba3c2b32a - <rustc_metadata[2002d9e21ce78884]::rmeta::encoder::encode_metadata::{closure#3} as core[17865207963548b5]::ops::function::FnOnce<(rustc_middle[7055997c00c0bb98]::ty::context::TyCtxt, &std[e49fa185a119b89b]::path::Path)>>::call_once
  21:     0x7faba3c28553 - rustc_metadata[2002d9e21ce78884]::rmeta::encoder::encode_metadata
  22:     0x7faba3923781 - rustc_metadata[2002d9e21ce78884]::fs::encode_and_write_metadata
  23:     0x7faba3b30125 - <rustc_interface[50af632e35c6bce3]::queries::Linker>::codegen_and_build_linker
  24:     0x7faba3b2ce9c - <rustc_interface[50af632e35c6bce3]::passes::create_and_enter_global_ctxt<core[17865207963548b5]::option::Option<rustc_interface[50af632e35c6bce3]::queries::Linker>, rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[17865207963548b5]::ops::function::FnOnce<(&rustc_session[307f8e7a4263bd4]::session::Session, rustc_middle[7055997c00c0bb98]::ty::context::CurrentGcx, alloc[756b9f94e2773738]::sync::Arc<rustc_data_structures[30161969bbcb553f]::jobserver::Proxy>, &std[e49fa185a119b89b]::sync::once_lock::OnceLock<rustc_middle[7055997c00c0bb98]::ty::context::GlobalCtxt>, &rustc_data_structures[30161969bbcb553f]::sync::worker_local::WorkerLocal<rustc_middle[7055997c00c0bb98]::arena::Arena>, &rustc_data_structures[30161969bbcb553f]::sync::worker_local::WorkerLocal<rustc_hir[5d00f225b65c0257]::Arena>, rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  25:     0x7faba39c19da - rustc_interface[50af632e35c6bce3]::interface::run_compiler::<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}
  26:     0x7faba3931d8e - std[e49fa185a119b89b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[50af632e35c6bce3]::util::run_in_thread_with_globals<rustc_interface[50af632e35c6bce3]::util::run_in_thread_pool_with_globals<rustc_interface[50af632e35c6bce3]::interface::run_compiler<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  27:     0x7faba3931b60 - <std[e49fa185a119b89b]::thread::lifecycle::spawn_unchecked<rustc_interface[50af632e35c6bce3]::util::run_in_thread_with_globals<rustc_interface[50af632e35c6bce3]::util::run_in_thread_pool_with_globals<rustc_interface[50af632e35c6bce3]::interface::run_compiler<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[17865207963548b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  28:     0x7faba39374f8 - <std[e49fa185a119b89b]::sys::thread::unix::Thread>::new::thread_start
  29:     0x7fab9d2969cb - <unknown>
  30:     0x7fab9d31aa0c - <unknown>
  31:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (3f4dc1e02 2025-12-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(min_generic_const_args) --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
#0 [local_def_id_to_hir_id] getting HIR ID of `foo::{constant#0}`
end of query stack
error: aborting due to 1 previous error; 2 warnings emitted


```

</p>
</details>

@rustbot label +F-min_generic_const_args 

since dc47a69ed94bc88b10b7d500cceacf29b87bcbbe

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes rust-lang/rust#149977
Fixes rust-lang/rust#148838

Accidentally left this out of rust-lang/rust#149136 even though being able to do this was a large part of the point of the PR :3 

First ICE was caused by the fact that we create a defid but never lower the nodeid associated with it to a hirid which later parts of the compiler can't handle.

See test for second ICE

r? oli-obk

### CODE REVIEW

File: tests/ui/const-generics/mgca/explicit_anon_consts.rs [hunk 1]
```diff
@@ -1,5 +1,8 @@
 #![feature(associated_const_equality, generic_const_items, min_generic_const_args)]
 #![expect(incomplete_features)]
+// library crates exercise weirder code paths around
+// DefIds which were created for const args.
+#![crate_type = "lib"]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/explicit_anon_consts.rs:5]: annoying that I literally went out of my way to add test cases for the ICEing code to catch stuff like this but it just didn't matter because the ICE occurs during metadata encoding or sth instead of some kind of HIR validation step

File: compiler/rustc_resolve/src/def_collector.rs [hunk 2]
```diff
@@ -357,6 +357,13 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
     }
 
     fn visit_anon_const(&mut self, constant: &'a AnonConst) {
+        if let MgcaDisambiguation::Direct = constant.mgca_disambiguation
+            && self.resolver.tcx.features().min_generic_const_args()
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/def_collector.rs:364]: Is the additional feature gate check necessary?

Comment (BoxyUwU) [reply compiler/rustc_resolve/src/def_collector.rs:364]: Yep, we can't set `MgcaDisambiguation` differently depending on whether the feature gate is enabled or not (as the parser doesn't have access to such information). So the enum is really a "if mgca is enabled, this should/shouldnt be an anon const", without mgca enabled the enum is basically meaningless
