### PR TITLE
infer array len from pattern

### LINKED ISSUE #70529: Compiler can't infer const parameter from infallible array pattern
The compiler can't infer a const parameter based on the expected array type in an infallible pattern.

I tried this code:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4673d663e2f78cdc15395c1cc3701d67
```rust
#![feature(const_generics)]

struct ArrayChunks<'a,T,const N:usize>{
    rem: &'a [T],
}

impl<'a,T,const N:usize> Iterator for ArrayChunks<'a,T,N>{
    type Item=&'a [T;N];
    
    fn next(&mut self)->Option<&'a [T;N]>{
        if self.rem.len() < N {
            return None;
        }
        
        let (ret,rem)=self.rem.split_at(N);
        self.rem=rem;
        let ret=unsafe{ std::mem::transmute::<*const T,&[T;N]>(ret.as_ptr()) };
        Some(ret)
    }
}

fn as_chunks<T,const N:usize>(slice:&[T])-> ArrayChunks<'_,T,N> {
    ArrayChunks{rem:slice}
}

fn main(){
    for &[x,y] in as_chunks(&[0,1,2,3,4]) {
        println!("x:{:?} y:{:?}",x,y)
    }
}
```

I expected the code to compile and run without errors.

Instead, I got this compiler error:
```rust
error[E0730]: cannot pattern-match on an array without a fixed length
  --> src/main.rs:27:10
   |
27 |     for &[x,y] in as_chunks(&[0,1,2,3,4]) {
   |          ^^^^^
```

### Meta

The compiler was 1.44.0-nightly (2020-03-28 77621317d643cc5d13da)

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70529#issuecomment-605910036).

### PR DESCRIPTION
**Pull request by lcnr**
closes #70529

This still errors in the following case

```rust
#![feature(const_generics)]
fn arr<const N: usize>() -> [u8; N] {
    todo!()
}

fn main() {
    match arr() {
        [5, ..] => (),
        //~^ ERROR cannot pattern-match on an array without a fixed length
        [_, _] => (),
    }
}
```
Considering that this should be rare and is harder to implement I would merge this PR without *fixing* the above.

### CODE REVIEW

**Comment by lcnr** [comment]
r? @eddyb 
cc @Centril thank you for your explanation in #70529

File: src/librustc_typeck/check/pat.rs [hunk 1]
```diff
@@ -1409,18 +1424,25 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 // so it has an array type with the remaining elements left as its size...
-                return r;
+                return Some(PatLenOrArray::Pat(pat_len));
             } else {
                 // ...however, in this case, there were no remaining elements.
                 // That is, the slice pattern requires more than the array type offers.
                 self.error_scrutinee_with_rest_inconsistent_length(span, min_len, len);
             }
+        } else if slice.is_none() {
+            // We have a pattern with a fixed length, which we can use to infer the length
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
            // We have a pattern with a fixed length,
            // which we can use to infer the length of the array.
```

File: src/librustc_typeck/check/pat.rs [hunk 2]
```diff
@@ -81,6 +81,12 @@ struct TopInfo<'tcx> {
     parent_pat: Option<&'tcx Pat<'tcx>>,
 }
 
+/// Returned by `fn check_array_pat_len`.
+enum PatLenOrArray<'tcx> {
+    Pat(u64),
+    Array(Ty<'tcx>),
+}
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: This seems unnecessary. You can unconditionally return `Ty<'tcx>` in `check_array_pat_len` instead...

File: src/librustc_typeck/check/pat.rs [hunk 3]
```diff
@@ -1391,15 +1400,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
     fn check_array_pat_len(
         &self,
         span: Span,
+        inner_ty: Ty<'tcx>,
+        arr_ty: Ty<'tcx>,
         slice: Option<&'tcx Pat<'tcx>>,
         len: &ty::Const<'tcx>,
         min_len: u64,
-    ) -> Option<u64> {
+    ) -> Option<PatLenOrArray<'tcx>> {
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
    ) -> (Ty<'tcx>, Ty<'tcx>) {
```
First one represents the `slice_ty` (so `tcx.err` where there isn't one) and the second represents the inferred type (i.e. the `expected` binding where this method is called).

File: src/test/ui/const-generics/infer_arg_from_pat.rs [hunk 4]
```diff
@@ -0,0 +1,25 @@
+// run-pass
```
Comment (Centril) [inline src/test/ui/const-generics/infer_arg_from_pat.rs]: Let's reference the issue we're closing.

File: src/test/ui/const-generics/infer_arr_len_from_pat.rs [hunk 5]
```diff
@@ -0,0 +1,11 @@
+// check-pass
```
Comment (Centril) [inline src/test/ui/const-generics/infer_arr_len_from_pat.rs]: And let's reference it in this test as well.

**Review by Centril — CHANGES_REQUESTED** [review]

**Comment by Centril** [comment]
cc @rust-lang/lang This changes slice pattern type checking such that we can infer the type of the pattern in `let [x, y] = array_with_inference_variable_for_size;`, which seems like a natural thing in light of const genercs. I'm not aware of how this could affect stable Rust, and I believe it does require const generics to take advantage of this, but I'm making y'all aware. :)

**Comment by Mark-Simulacrum** [comment]
```rust
use std::convert::TryInto;

fn main() {
    let s: &[u32] = &[0, 1];
    let [x, y] = s.try_into().unwrap();
}
```

Haven't checked, but I suspect this would compile with this PR (and currently requires type annotation, presumably because `try_into()` doesn't know how many elements to go to.

**Comment by Centril** [comment]
Ah yeah, that might work. @lcnr Please add that to the set of tests. :)

File: src/librustc_typeck/check/pat.rs (hunk 3 above)
Comment (lcnr) [reply src/librustc_typeck/check/pat.rs]: that's a lot cleaner :+1:

File: src/librustc_typeck/check/pat.rs [hunk 6]
```diff
@@ -1391,15 +1400,21 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    /// Returns the length of the variable length pattern,
     /// if it exists and there are no errors.
+    ///
+    /// In case the pattern has a fixed length and the array
+    /// length is not yet determined, returns the array type
+    /// with the inferred length.
     fn check_array_pat_len(
         &self,
         span: Span,
+        inner_ty: Ty<'tcx>,
```
Comment (eddyb) [inline src/librustc_typeck/check/pat.rs]: We usually refer to this as the "element type".

File: src/librustc_typeck/check/pat.rs [hunk 7]
```diff
@@ -1409,18 +1424,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 // That is, the slice pattern requires more than the array type offers.
                 self.error_scrutinee_with_rest_inconsistent_length(span, min_len, len);
             }
+        } else if slice.is_none() {
+            // We have a pattern with a fixed length,
+            // which we can use to infer the length of the array.
+            // of the array.
+            let updated_arr = self.tcx.mk_array(inner_ty, min_len);
+            self.demand_eqtype(span, updated_arr, arr_ty);
+            return Some(PatLenOrArray::Array(updated_arr));
```
Comment (eddyb) [inline src/librustc_typeck/check/pat.rs]: Is this extra complexity (compared to just unifying the constant) in order to be able to use `demand_eqtype`?

File: src/librustc_typeck/check/pat.rs (hunk 6 above)
Comment (Centril) [reply src/librustc_typeck/check/pat.rs]: So in that case:
```suggestion
        elem_ty: Ty<'tcx>,
```

File: src/librustc_typeck/check/pat.rs (hunk 7 above)
Comment (lcnr) [reply src/librustc_typeck/check/pat.rs]: tbh I wasn't able to find a good way to unify consts.
The only thing I found was [`unify_const_variable`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.unify_const_variable), which requires a `ConstVid`, which I do not fully understand yet. At this point I gave up and just used type equality :laughing: 

So while this is the least complex thing I found there could easily be a better approach.

**Comment by lcnr** [comment]
```rust
use std::convert::TryInto;

fn main() {
    let s: &[u32] = &[0, 1];
    let [x, y] = s.try_into().unwrap();
}
```

and similar implementations do not compile with this, as `expected` is not
`Ty::Array(elem, ???)` but `???`. It might be possible special case this if all possible impls
return arrays.

Similar example, which fails for the same reason:
```rust
struct A;

impl From<A> for [u8; 2] {
    fn from(a: A) -> Self {
        [0; 2]
    }
}

impl From<A> for [u8; 3] {
    fn from(a: A) -> Self {
        [0; 3]
    }
}


fn main() {
    let a = A;
    let [_, _] = a.into();
}
```

This seems to be the related to the following, which does not depend on const generics at all.
```rust
struct A;

impl From<A> for Vec<u8> {
    fn from(a: A) -> Self {
        vec![0]
    }
}

impl From<A> for Vec<u16> {
    fn from(a: A) -> Self {
        vec![1]
    }
}


fn main() {
    let a = A;
    let mut vec = a.into();
    //~^ ERROR type annotations needed
    vec.push(2u16);
}
```

**Comment by Centril** [comment]
> [...] and similar implementations do not compile with this, as expected is not
> Ty::Array(elem, ???) but ???. It might be possible special case this if all possible impls
> return arrays.

Presumably because we are using `structurally_resolved_type`.
Let's not special case things here, but let's add the failing test. :)

File: src/librustc_typeck/check/pat.rs (hunk 7 above)
Comment (Centril) [reply src/librustc_typeck/check/pat.rs]: The current approach might do some extra work, but it seems fairly clean, and it can't go wrong. We could always improve this later imo.

File: src/librustc_typeck/check/pat.rs [hunk 8]
```diff
@@ -1409,21 +1411,29 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                return (self.tcx.mk_array(element_ty, pat_len), arr_ty);
             } else {
                 // ...however, in this case, there were no remaining elements.
                 // That is, the slice pattern requires more than the array type offers.
                 self.error_scrutinee_with_rest_inconsistent_length(span, min_len, len);
             }
+        } else if slice.is_none() {
+            // We have a pattern with a fixed length,
+            // which we can use to infer the length of the array.
+            // of the array.
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
```

File: src/test/ui/error-codes/E0730.rs [hunk 9]
```diff
@@ -3,7 +3,7 @@
 
 fn is_123<const N: usize>(x: [u32; N]) -> bool {
     match x {
-        [1, 2, 3] => true, //~ ERROR cannot pattern-match on an array without a fixed length
```
Comment (Centril) [inline src/test/ui/error-codes/E0730.rs]: This is the only place this error occurs in the test suite, so let's add a new UI test in `src/test/ui/array-slice-vec/` for the error with a subslice pattern.

File: src/librustc_typeck/check/pat.rs [hunk 10]
```diff
@@ -1355,16 +1355,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     ) -> Ty<'tcx> {
         let err = self.tcx.types.err;
         let expected = self.structurally_resolved_type(span, expected);
-        let (inner_ty, slice_ty, expected) = match expected.kind {
+        let (element_ty, slice_ty, expected) = match expected.kind {
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
        let (element_ty, slice_ty, inferred) = match expected.kind {
```
(Makes this a bit less jarring to read cause "expected" sounds like an input, but it's really an output here.)

File: src/test/ui/error-codes/E0730.rs (hunk 9 above)
Comment (lcnr) [reply src/test/ui/error-codes/E0730.rs]: updated this test to emit E0730 again,
copied the old version to array-slice-vec

**Review by Centril — APPROVED** [review]
Thanks for doing this! 💖 The implementation looks very clean. 🎉 

r=me unless @eddyb wants to tweak the unification bits, but imo it looks good as-is.

File: src/librustc_typeck/check/pat.rs (hunk 7 above)
Comment (eddyb) [reply src/librustc_typeck/check/pat.rs]: @lcnr That's mostly because there aren't specific functions, it's all done through traits.

`demand_eqtype`, for example, passes `actual` and `expected` to a function that can take just about anything.

File: src/librustc_typeck/check/pat.rs [hunk 11]
```diff
@@ -1355,16 +1355,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             // An array, so we might have something like `let [a, b, c] = [0, 1, 2];`.
-            ty::Array(inner_ty, len) => {
+            ty::Array(element_ty, len) => {
                 let min = before.len() as u64 + after.len() as u64;
-                let slice_ty = self
-                    .check_array_pat_len(span, slice, len, min)
-                    .map_or(err, |len| self.tcx.mk_array(inner_ty, len));
-                (inner_ty, slice_ty, expected)
+                let (slice_ty, expected) =
+                    self.check_array_pat_len(span, element_ty, expected, slice, len, min);
```
Comment (eddyb) [inline src/librustc_typeck/check/pat.rs]: Is this the only caller? It feels like a bunch of stuff is muddled by the fact that it's a separate function.

Comment (lcnr) [reply src/librustc_typeck/check/pat.rs]: it is. Could inline this in a followup pr if you want :man_shrugging:

Comment (Centril) [reply src/librustc_typeck/check/pat.rs]: Please don't. I disagree with eddy here and I think the method provides separation of concerns from the rest of type checking of slice patterns (the structural parts of checking before/slice/after once you've extracted the `slice_ty` and `inferred`). At most, I think this method should be split in two, one for the `slice.is_none()` and one for the other bits.
