### PR TITLE
Pass struct field HirId when check_expr_struct_fields

### LINKED ISSUE #138319: Expect doesn't work on struct field
### Code

```Rust
fn _foo() {
    Bar {
        #[expect(deprecated)]
        foo: 0,
    };
}

struct Bar {
    #[deprecated = "reason"]
    foo: u32,
}
```

### Current output

```Shell
warning: use of deprecated field `Bar::foo`: reason
 --> src/lib.rs:4:9
  |
4 |         foo: 0,
  |         ^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: this lint expectation is unfulfilled
 --> src/lib.rs:3:18
  |
3 |         #[expect(deprecated)]
  |                  ^^^^^^^^^^
  |
  = note: `#[warn(unfulfilled_lint_expectations)]` on by default
```

### Desired output

```Shell
n/a (empty)
```

### Rationale and extra context

Expectation should be fulfilled, as the deprecated lint is actively being emitted from that field initialization. This works as expected if the expectation is moved elsewhere (e.g., to the function).

### Other cases

```Rust

```

### Rust Version

```Shell
Current stable (1.85)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #138319

r? compiler

cc @Mark-Simulacrum

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 1]
```diff
@@ -2060,7 +2060,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 // a bug to have constructed one.
                 if adt_kind != AdtKind::Enum {
-                    tcx.check_stability(v_field.did, Some(expr.hir_id), field.span, None);
+                    let field_hir_id = match expr.kind {
+                        hir::ExprKind::Struct(_qpath, fields, _tail) if idx < fields.len() => {
+                            Some(fields[idx].expr.hir_id)
+                        }
+                        _ => None,
+                    };
+                    tcx.check_stability(v_field.did, field_hir_id, field.span, None);
```
Comment (petrochenkov) [inline compiler/rustc_hir_typeck/src/expr.rs:2069]:
```suggestion
                    tcx.check_stability(v_field.did, field.hir_id, field.span, None);
```
The field is already available above.

File: tests/ui/stability-attribute/check-stability-issue-138319-1.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+//@ run-pass
```
Comment (petrochenkov) [inline tests/ui/stability-attribute/check-stability-issue-138319-1.rs:1]:
```suggestion
//@ check-pass
```
For the other test too.

Comment (petrochenkov) [reply tests/ui/stability-attribute/check-stability-issue-138319-1.rs:1]: Both tests can actually be merged together, I think.

**Comment by petrochenkov** [comment]
There's a number of other `check_stability` calls using imprecise node IDs.
For example, in `check_struct_pat_fields` and `check_pat_tuple_struct`.
Could you fixup them as well?
@rustbot author

**Comment by xizheyin** [comment]
I modified it. I'd love to fix the other parts, should I open a separate issue for this? Because this PR is for fixing #138319.
@petrochenkov 

@rustbot label -S-waiting-on-author +S-waiting-on-review

**Comment by xizheyin** [comment]
I have fixed the three `check_stability`. But I have no idea about testing `check_pat_tuple_struct`, because the code below is not allowed. @petrochenkov 
```
struct _Point(#[deprecated = "reason"]i32, i32);


fn main() {

    let p = _Point(10, 20);
    let _Point(#[expect(deprecated)]_x, ..) = p;
}
```

It report error
```
error: expected pattern, found `#`
 --> src/lib.rs:7:16
  |
7 |     let _Point(#[expect(deprecated)]_x, ..) = p;
  |                ^ expected pattern

```

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

>But I have no idea about testing `check_pat_tuple_struct`, because the code below is not allowed.

It's ok to leave this case without a test, if attributes are later supported in that position, they will have a correct node id.
