### PR TITLE
Fix intersperse_fold

### LINKED ISSUE #81145: `Iterator::intersperse` doesn't seem to work correctly when collecting into a String
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=282381d3d08c3ff8d42e2979ebce6bdd)):

```rust
#![feature(iter_intersperse)]

fn main() {
    let contents = vec![1, 2, 3];

    let contents_string = contents
        .into_iter()
        .map(|id| id.to_string())
        .intersperse(", ".to_owned())
        .collect::<String>();

    println!("{}", contents_string);
}

```

I expected to see this happen: `", "` is placed between each digit:
```
1, 2, 3
```

Instead, this happened: `intersperse` does not insert `", "` between `"1"` and `"2"`:
```
12, 3
```

Note that this works as expected when collecting into a `Vec` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6d4a0435e82e497b15eae6da7530b98a)):
```rust
#![feature(iter_intersperse)]

fn main() {
    let contents = vec![1, 2, 3];

    let contents_strings = contents
        .into_iter()
        .map(|id| id.to_string())
        .intersperse(", ".to_owned())
        .collect::<Vec<_>>();

    println!("{:?}", contents_strings);
}
```
```
["1", ", ", "2", ", ", "3"]
```

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0-nightly (8a6518427 2021-01-16)
binary: rustc
commit-hash: 8a6518427e11e6dd13d6f39663b82eb4f810ca05
commit-date: 2021-01-16
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

@rustbot modify labels: +A-iterators +T-libs

### PR DESCRIPTION
**Pull request by tesuji**
Here is a standalone playground link in case anybody wants to modify code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=626b4d044fb74f044a36098ad907e40f

Fixes #81145

cc #79479 @jonas-schievink

### CODE REVIEW

**Comment by lzutao** [comment]
The second commit 72dd5a445a3c6663399c86cd33235b5f9e6bd099 is the result of
`./x.py fmt` run locally. I expected CI catches fmt error. Does something go wrong ? cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
It looks like your local branch is using the wrong rustfmt for some reason, not sure why that would be though. Please file an issue if you can't successfully drop it from this PR so that I can investigate.

**Comment by nagisa** [comment]
Can you add a test with a string, such as reported in the original issue? They said that collecting into a vector did work regardless, but not when it was collected into a string.

**Comment by lzutao** [comment]
Here is the playground link of such test: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=26f37fc7f7fa317f3d458623d047952b

Will add that test soon though I feel the test redundant.

File: library/core/src/iter/adapters/intersperse.rs [hunk 1]
```diff
@@ -173,8 +173,7 @@ where
 {
```
Comment (camsteffen) [inline library/core/src/iter/adapters/intersperse.rs:173]: You can remove `Peekable` from this function signature.

Comment (lzutao) [reply library/core/src/iter/adapters/intersperse.rs:173]: I changed from `Peekable<I: Iterator>` to just `I: Iterator` only.

**Comment by lukaslueg** [comment]
cc @camelid
I'm unsure if the fix is correct with respect to the comment which this PR also removes.

File: library/core/src/iter/adapters/intersperse.rs [hunk 2]
```diff
@@ -173,8 +173,7 @@ where
...
     let mut accum = init;
 
-    // Use `peek()` first to avoid calling `next()` on an empty iterator.
-    if !needs_sep || iter.peek().is_some() {
+    if !needs_sep {
         if let Some(x) = iter.next() {
             accum = f(accum, x);
         }
```
Comment (m-ou-se) [inline library/core/src/iter/adapters/intersperse.rs:179]: Looks like the idea behind `.peek().is_some()` here was to prevent calling fold() after next() returned None, as we don't know if `iter` is a `FusedIterator` or not. (It might start giving elements again after a `None`.)

However, it didn't work because `||` was used instead of `&&`, also causing the bug you're fixing with this PR.

Example that goes wrong both before and after this change:

```rust
#![feature(iter_intersperse)]

fn main() {
    struct A(i32); // Produces: None, Some(2), Some(3), None, ...
    impl Iterator for A {
        type Item = i32;
        fn next(&mut self) -> Option<i32> {
            self.0 += 1;
            if self.0 % 3 == 1 {
                None
            } else {
                Some(self.0)
            }
        }
    }

    dbg!(A(0).intersperse(1000).fold(0, |a, b| a + b));
}
```

This should give `0`, but gives `2005`, as it continued after the initial `None`.

This can be fixed by either:

1. Putting `Peekable` back and using `&& iter.peek().is_some()`; or
2. Adding a `} else { return accum; }` after the `if let Some(x) ..`:

```suggestion
    if !needs_sep {
        if let Some(x) = iter.next() {
            accum = f(accum, x);
        } else {
            return accum;
        }
```

Comment (lzutao) [reply library/core/src/iter/adapters/intersperse.rs:179]: I blindly missed that. Thanks for the your thorough review. Will update the PR soon.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+
