### PR TITLE
parser: more friendly hints for handling `async move` in the 2015 edition

### LINKED ISSUE #114219: error about `async move { ` block could suggest using later edition in edition 2015
### Code

with edition 2015:
```rust
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found keyword `move`
 --> g.rs:4:11
  |
4 |     async move {}();
  |           ^^^^ expected one of 8 possible tokens

error: aborting due to previous error
````

with edition 2018:

````
error[E0618]: expected function, found `[async block@g.rs:4:5: 4:18]`
 --> g.rs:4:5
  |
4 |     async move {}();
  |     ^^^^^^^^^^^^^--
  |     |
  |     call expression requires function

error: aborting due to previous error
````
with edition < 2018, we could suggest switching to a later edition instead of throwing an obscure syntax error.

original code:

````rust
// edition: 2021
// check-pass

// This test verifies that we do not create a query cycle when typechecking has several inference
// variables that point to the same generator interior type.

use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll};

type ChannelTask = Pin<Box<dyn Future<Output = ()> + Send>>;

pub fn register_message_type() -> ChannelTask {
    Box::pin(async move {
        let f = |__cx: &mut Context<'_>| Poll::<()>::Pending;
        PollFn { f }.await
    })
}

struct PollFn<F> {
    f: F,
}

impl<F> Unpin for PollFn<F> {}

impl<T, F> Future for PollFn<F>
where
    F: FnMut(&mut Context<'_>) -> Poll<T>,
{
    type Output = T;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<T> {
        (&mut self.f)(cx)
    }
}

fn main() {}
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #114219 

An error is emitted when encountering an ﻿async move block in the 2015 edition.

Another appropriate location to raise an error is after executing ﻿[let path = this.parse_path(PathStyle::Expr)?](https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/parser/stmt.rs#L152), but it seems somewhat premature to invoke `﻿create_err` at that stage.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -573,6 +574,13 @@ impl<'a> Parser<'a> {
             return Err(self.sess.create_err(UseEqInstead { span: self.token.span }));
         }
 
+        if self.token.ident().map(|(ident, _)| ident.as_str() == "move").unwrap_or_default()
```
Comment (Nilstrieb) [inline compiler/rustc_parse/src/parser/diagnostics.rs:577]: you should compare the `Symbol` to [`kw::Move`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/kw/constant.Move.html) instead of doing a string comparison

same for the `prev_token` below, using `token_descr` is not great

Comment (bvanjoi) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: thanks!

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -573,6 +574,14 @@ impl<'a> Parser<'a> {
             return Err(self.sess.create_err(UseEqInstead { span: self.token.span }));
         }
 
+        if self.token.ident().map(|(ident, _)| ident.name == kw::Move).unwrap_or_default()
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:577]: Can you use `is_some_and` here and below?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs:577]: Also, you can use https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/struct.Token.html#method.is_keyword here (at least for `move`)

File: tests/ui/parser/issues/issue-114219.stderr [hunk 3]
```diff
@@ -0,0 +1,8 @@
+error: `async move` are only allowed in Rust 2018 or later
+  --> $DIR/issue-114219.rs:2:5
+   |
+LL |     async move {};
+   |     ^^^^^^^^^^
```
Comment (compiler-errors) [inline tests/ui/parser/issues/issue-114219.stderr:5]: The error should use the same wording as below:

```
1 | fn test() { async {}; }
  |             ^^^^^ `async` blocks are only allowed in Rust 2018 or later
```

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 2 above)
Comment (bvanjoi) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Thanks
