### PR TITLE
Ignore borrowck for static lvalues and allow assignment to static muts

### LINKED ISSUE #45129: MIR-borrowck: paths off of statics should not be borrow-checked
Paths off of statics should not be borrow-checked, as they already require `unsafe`. But currently MIR-borrowck is flagging errors for them, while AST-borrowck lets them through without complaint.

(Spawned off of https://github.com/rust-lang/rust/pull/44985#pullrequestreview-67919938)

### LINKED ISSUE #45641: MIR-borrowck: assignment to static mut shouldn't be an error
MIR borrowck errors out on assignments to mutable statics, which should be allowed (in unsafe code) e.g.

```Rust
static mut Y: u32 = 0;

unsafe fn should_ok() {
    Y = 1;
}

fn main() {}
```

which causes:
```
$ rustc x.rs -Z borrowck-mir
error: cannot assign to immutable static item Y (Mir)
 --> x.rs:5:5
  |
5 |     Y = 1;
  |     ^^^^^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #45129.
Fixes #45641.

### CODE REVIEW

File: src/librustc_mir/borrow_check.rs [hunk 1]
```diff
@@ -449,51 +449,56 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
-                                    context, lvalue_span, borrow),
-                            ReadKind::Borrow(bk) => {
-                                let end_issued_loan_span =
-                                    flow_state.borrows.base_results.operator().opt_region_end_span(
-                                        &borrow.region);
-                                this.report_conflicting_borrow(
-                                    context, common_prefix, lvalue_span, bk,
-                                    &borrow, end_issued_loan_span)
+        // Ignore all borrows rooted in statics
+        if let Lvalue::Local(_) = *self.prefixes(lvalue_span.0, PrefixSet::All).last().unwrap() {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: this `if let` makes me nervous -- if we add more lvalues in the future, it might silently squash them. I'd rather see an exhaustive `match`.

File: src/librustc_mir/borrow_check.rs [hunk 2]
```diff
@@ -449,51 +449,56 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+            self.each_borrow_involving_path(
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: also, I think this should be factored into a helper function personally

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks good! Just a few nits.

File: src/librustc_mir/borrow_check.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: Alternatively, something like:

```rust
if let Lvalue::Static(_) = ... {
    // Skip checks on statics. See #123.
} else {
    ...
}
```

**Comment by KiChjang** [comment]
Done. r? @nikomatsakis

File: src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// revisions: ast mir
+//[mir]compile-flags: -Z emit-end-regions -Z borrowck-mir
+
+// Test file taken from issue 45129 (https://github.com/rust-lang/rust/issues/45129)
```
Comment (arielb1) [inline src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs]: This code is UB. Please don't have it as a run-pass test, because verified compilation will correctly complain.

to make it non-UB, e.g. use an array and access different array indices.

File: src/librustc_mir/borrow_check.rs [hunk 4]
```diff
@@ -446,54 +446,78 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
+                    Control::Break
                 }
-            });
+            }
+        }
+
+        // Check permissions
+        self.check_access_permissions(lvalue_span, rw);
+
+        match *self.prefixes(lvalue_span.0, PrefixSet::All).last().unwrap() {
```
Comment (arielb1) [inline src/librustc_mir/borrow_check.rs]: Shouldn't borrows involving statics be handled in the same way as borrows involving raw pointers? I could open another issue for borrows through raw pointers.

```Rust
struct Foo { x: [usize; 2] }

static mut SFOO: Foo = Foo { x: [23, 32] }; 

impl Foo {
    fn x(&mut self) -> &mut usize { &mut self.x[0] }
}

fn main() {
    // this compiles with AST borrowck, should also compile with MIR borrowck
    unsafe {
        let sfoo: *mut Foo = &mut SFOO;
        let x = (*sfoo).x();
        (*sfoo).x[1] += 1;
        *x += 1; 
    }
}
```

**Comment by arielb1** [comment]
btw,
```
[00:02:41] tidy error: /checkout/src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs:18: trailing whitespace

[00:02:41] tidy error: /checkout/src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs:28: trailing whitespace
```

File: src/librustc_mir/borrow_check.rs (hunk 4 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: Yes, I agree they should be handled the same. Do you think that means however that we should unify the codepaths that make those two cases behave the same? If so, how do you think we should do it? (I think that sounds like a nice idea)

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: (In particular, if we decided to offer a lint at some point for obvious UB, I'd want it to apply to both.)

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: I guess if we just factor out a helper function `unsafe_access_path(&Lvalue)` it can test for either a deref of a raw pointer *or* the use of a `static mut`.

Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: @nikomatsakis 

One I think good way of doing it is just not registering borrows that go through an unsafe access path.

Note that for unsafe pointers this *is* different from checking the lvalue, e.g. in:
```Rust
fn main() {
    let mut x = 1 as *const ();
    let y = unsafe { &*x }; // borrow through an unsafe pointer
    let _ = &mut x; // then mutate everything - should be OK
    println!("{:p}", y);
}
```

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: I was avoiding recommending that because I wanted to consider adding a lint later on. But we could do it that way. Either way, we basically need the helper function I talked about, I imagine. It's just a question of whether we try to avoid registering the borrows in the first place, or try to ignore them when they are registered. =)

**Comment by KiChjang** [comment]
Alright, I've made changes to the test file, and am now also not registering borrows that are from an unsafe lvalue.

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 5]
```diff
@@ -164,6 +203,34 @@ impl<'a, 'gcx, 'tcx> Borrows<'a, 'gcx, 'tcx> {
...
         }
     }
+
+    fn is_unsafe_lvalue(&self, lvalue: &mir::Lvalue<'tcx>) -> bool {
+        use self::mir::Lvalue::*;
+        use self::mir::ProjectionElem;
+
+        match *lvalue {
+            Local(_) => false,
+            Static(_) => true,
```
Comment (nikomatsakis) [inline src/librustc_mir/dataflow/impls/borrows.rs]: Only `static mut` is an unsafe lvalue, not any static at all.

File: src/librustc_mir/borrow_check.rs [hunk 6]
```diff
@@ -446,54 +446,78 @@ impl<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a> MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx>
...
-                                    context, lvalue_span, borrow),
-                            ReadKind::Borrow(bk) => {
-                                let end_issued_loan_span =
-                                    flow_state.borrows.base_results.operator().opt_region_end_span(
-                                        &borrow.region);
-                                this.report_conflicting_borrow(
-                                    context, common_prefix, lvalue_span, bk,
-                                    &borrow, end_issued_loan_span)
-                            }
+        fn check_borrows_readability_or_writability<'c, 'b, 'a: 'b+'c, 'gcx, 'tcx: 'a>(
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: If we are suppressing the borrows, we shouldn't need any changes to this function.

File: src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+impl Foo {
+    fn x(&mut self) -> &mut usize { &mut self.x[0] }
+}
+
+fn main() {
+    unsafe {
+        let sfoo: *mut Foo = &mut SFOO;
+        let x = (*sfoo).x();
+        (*sfoo).x[1] += 1;
+        *x += 1;
```
Comment (nikomatsakis) [inline src/test/run-pass/borrowck/borrowck-unsafe-static-mutable-borrows.rs]: Looks good! =)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks good! I just think one part of it is no longer needed.

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 8]
```diff
@@ -164,6 +203,34 @@ impl<'a, 'gcx, 'tcx> Borrows<'a, 'gcx, 'tcx> {
             }
         }
     }
+
+    fn is_unsafe_lvalue(&self, lvalue: &mir::Lvalue<'tcx>) -> bool {
```
Comment (nikomatsakis) [inline src/librustc_mir/dataflow/impls/borrows.rs]: Why do we have this same function twice? Copy-and-paste error?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Lookin' good. One nit.

**Review by nikomatsakis — APPROVED** [review]
