### PR TITLE
Suggest the correct pattern syntax on usage of unit variant pattern for a struct variant

### LINKED ISSUE #126243: Suggest adding `{ .. }` on accidental usage of unit variant pattern for a struct variant
### Code

```Rust
pub enum Error {
    NotFound,
    
    PreconditionFailed {
        description: String,
    }
}

pub fn demonstration(error: Error) {
    match error {
        Error::NotFound => println!("gone fishin"),
        Error::PreconditionFailed => println!("you're missing something"),
        _ => println!("i literally have no idea"),
    }
}
```

### Current output

```Shell
error[E0533]: expected unit struct, unit variant or constant, found struct variant `Error::PreconditionFailed`
  --> src/lib.rs:12:9
   |
12 |         Error::PreconditionFailed => println!("you're missing something"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant
```

### Desired output

```Shell
error[E0533]: expected unit struct, unit variant or constant, found struct variant `Error::PreconditionFailed`
  --> src/lib.rs:12:9
   |
12 |         Error::PreconditionFailed => println!("you're missing something"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant
help: if you don't care about the variant's fields, ignore them with `{ .. }`
   |
12 |         Error::PreconditionFailed { .. } => println!("you're missing something"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Rationale and extra context

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fa0a09facbbd4cda06ca1c3214b99a6b)

I wrote code that looked like this while not having my brain turned on 100%. Due to said brain not functioning, it took me a while to understand what rustc was trying to tell me with the message pointing to the `Error::PreconditionFailed` pattern with the text `not a unit struct, unit variant or constant`. `Error::PreconditionFailed` sure looked like a unit variant to me!

What rustc was trying to tell me was that the _definition_ of the `Error::PreconditionFailed` variant was a struct variant ("found struct variant") and my pattern wasn't matching the definition ("this pattern you specified looks like it's trying to match a variant that is not a unit struct, unit variant or constant").

The change I needed to make was adding `{ .. }` to my pattern, because I was trying to distinguish different variants from each other, not use pieces within the variants. Suggesting `{ .. }` seems like a decent starting point to me, but there could definitely be cases I'm not considering here and I'm totally open to hearing that ❤️ 

### Other cases

_No response_

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: aarch64-apple-darwin
release: 1.78.0
LLVM version: 18.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tunawasabi**
Closes #126243

I add a suggestion on usage of unit variant pattern for a struct variant.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 1]
```diff
@@ -421,6 +421,43 @@ fn report_unexpected_variant_res(
             err.multipart_suggestion_verbose(descr, suggestion, Applicability::MaybeIncorrect);
             err
         }
+        Res::Def(DefKind::Variant, _) if expr.is_none() => {
+            let fields = tcx
+                .expect_variant_res(res)
```
Comment (tunawasabi) [inline compiler/rustc_hir_typeck/src/lib.rs:426]: this call is safe, isn't it?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/lib.rs:426]: Yeah, it's fine for `DefKind::Variant`.

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 2]
```diff
@@ -421,6 +421,43 @@ fn report_unexpected_variant_res(
...
+            let span = qpath.span().shrink_to_hi().to(span.shrink_to_hi());
+            err.span_suggestion_verbose(
+                span,
+                "use the struct variant pattern syntax",
+                if fields.is_empty() {
+                    " {}".to_string()
+                } else {
+                    format!(" {{ {} }}", fields.join(", "))
+                },
+                Applicability::MachineApplicable,
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/lib.rs:444]: These two suggestions cannot both be `MachineApplicable`. I would downgrade this down to `HasPlaceholders` if there are variants.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/lib.rs:444]: Or honestly, it may be worth just suggesting `field: _, field: _` unconditionally (or `..` if there are.. e.g. > 4 fields), and adjusting the wording to note that they're being ignored.  Two suggestions seems a bit excessive...

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/lib.rs:444]: Alternatively, use [`span_suggestions`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic/struct.Diag.html#method.span_suggestions) which supports MUTUALLY EXCLUSIVE suggestions. You'll need to make a single wording for both of them, though.

Comment (tunawasabi) [reply compiler/rustc_hir_typeck/src/lib.rs]: OK. I fixed the diagnostic to just suggest a placeholder.

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 3]
```diff
@@ -421,6 +421,18 @@ fn report_unexpected_variant_res(
             err.multipart_suggestion_verbose(descr, suggestion, Applicability::MaybeIncorrect);
             err
         }
+        Res::Def(DefKind::Variant, _) if expr.is_none() => {
+            err.span_label(span, format!("not a {expected}"));
+
+            err.span_suggestion_verbose(
+                qpath.span().shrink_to_hi().to(span.shrink_to_hi()),
+                "the struct variant's fields are being ignored",
+                " { /* field: _, field: _ */ }",
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/lib.rs:430]: Oof, I meant taking the fields themselves and emitting for each field name `name: _`. Like,

```
struct Foo { a: i32, b: i32 }
```

would result in `Foo { a: _, b: _ }`.

**Review by compiler-errors — COMMENTED** [review]
Pls adjust the suggestion sorry I wasn't clear 😅

File: compiler/rustc_hir_typeck/src/lib.rs (hunk 3 above)
Comment (tunawasabi) [reply compiler/rustc_hir_typeck/src/lib.rs:430]: Oops, I'll fix it. sorry for my misunderstanding 😭

Comment (tunawasabi) [reply compiler/rustc_hir_typeck/src/lib.rs:430]: Additionally, I provide a diagnostic `use the struct variant pattern syntax` instead of t`he struct variant's field{s} {are} being ignored` when there are no fields.

**Comment by tunawasabi** [comment]
oh, I forget to remove a comment out from the suggestion.

@rustbot author

**Review by compiler-errors — APPROVED** [review]
