### PR TITLE
Don't build `ParamEnv` and do trait solving in `ItemCtxt`s when lowering IATs

### LINKED ISSUE #108491: cycle detected for type aliases in structs
Taken out from here: https://github.com/rust-lang/rust/issues/8995#issuecomment-1445331733 as @fmease requested.

```rust
struct Foo {
    bar: Self::Bar,
}
impl Foo {
    pub type Bar = usize;
}
```

was compiled successfully a couple of nighly revisions before.

Now an error is returned:
```
error[E0391]: cycle detected when computing predicates of `Foo`
  --> src\main.rs:5:1
   |
5  | struct Foo {
   | ^^^^^^^^^^
   |
note: ...which requires computing predicates of `Foo`...
  --> src\main.rs:5:1
   |
5  | struct Foo {
   | ^^^^^^^^^^
note: ...which requires computing inferred outlives predicates of `Foo`...
  --> src\main.rs:5:1
   |
5  | struct Foo {
   | ^^^^^^^^^^
   = note: ...which requires computing the inferred outlives predicates for items in this crate...
note: ...which requires computing type of `Foo::bar`...
  --> src\main.rs:6:5
   |
6  |     bar: Self::Bar,
   |     ^^^^^^^^^^^^^^
note: ...which requires computing normalized predicates of `Foo`...
  --> src\main.rs:5:1
   |
5  | struct Foo {
   | ^^^^^^^^^^
   = note: ...which again requires computing predicates of `Foo`, completing the cycle
note: cycle used when collecting item types in top-level module
```

### Meta
`rustc --version --verbose`:
```
rustc 1.69.0-nightly (34e6673a0 2023-02-25)
```

### LINKED ISSUE #125879: ICE: `unimplemented: inhabitedness checking for inherent projections` in `rustc_middle/src/ty/inhabitedness/mod.rs`
### Code

(hand reduced & simplified)

```Rust
#![feature(inherent_associated_types)]
#![allow(incomplete_features)]

pub type PubAlias0 = PubTy::PrivAssocTy;

pub struct PubTy;
impl PubTy {
    type PrivAssocTy = ();
}

pub struct S(pub PubAlias0);

pub unsafe fn foo(a: S) -> S {
    a
}

fn main() {}
```

<details><summary><strong>original code</strong></summary>
<p>

```Rust
//@ check-pass

#![feature(inherent_associated_types)]
#![allow(incomplete_features)]
#![crate_type = "lib"]

pub type PubAlias0 = PubTy::PrivAssocTy;
//~^ WARNING associated type `PubTy::PrivAssocTy` is more private than the item `PubAlias0`
pub type PubAlias1 = PrivTy::PubAssocTy;
//~^ WARNING type `PrivTy` is more private than the item `PubAlias1`
pub type PubAlias2 = PubTy::PubAssocTy<PrivTy>;
//~^ WARNING type `PrivTy` is more private than the item `PubAlias2`

pub struct PubTy;
impl PubTy {
    type PrivAssocTy = ();
    pub type PubAssocTy<T> = T;
}

struct PrivTy;
impl PrivTy {
    pub type PubAssocTy = ();
}


//~ ERROR the parameter type `Self` may not live long enough

trait GatTrait {
    type Gat<'a>
    where
        Self: 'a;
}

trait SuperTrait<T>: for<'a> GatTrait<Gat<'a> = T> {
    fn c(&self) -> dyn SuperTrait<T>;
    //~^ ERROR associated item referring to unboxed trait object for its own trait
    //~| ERROR the trait `SuperTrait` cannot be made into an object
}

fn main() {}


//@ compile-flags: -C no-prepopulate-passes

#![crate_type = "lib"]

#![feature(repr_simd, intrinsics)]
#![allow(non_camel_case_types)]

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f32x2(pub f32, pub f32);

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f32x4(pub f32, pub f32, pub f32, pub f32);

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f32x8(pub f32, pub f32, pub f32, pub f32,
                 pub f32, pub f32, pub f32, pub f32);

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f32x16(pub f32, pub f32, pub f32, pub T,
                  pub f32, pub f32, pub f32, pub f32,
                  pub f32, pub f32, pub f32, pub f32,
                  pub f32, pub f32, pub f32, pub f32);

extern "rust-intrinsic" {
    fn simd_fsin<T>(x: T) -> T;
}

// CHECK-LABEL: @fsin_32x2
#[no_mangle]
pub unsafe fn fsin_32x2(a: f32x2) -> f32x2 {
    // CHECK: call <2 x float> @llvm.sin.v2f32
    simd_fsin(a)
}

// CHECK-LABEL: @fsin_32x4
#[no_mangle]
pub unsafe fn fsin_32x4(a: f32x4) -> f32x4 {
    // CHECK: call <4 x float> @llvm.sin.v4f32
    simd_fsin(a)
}

// CHECK-LABEL: @fsin_32x8
#[no_mangle]
pub unsafe fn fsin_32x8(a: f32x8) -> f32x8 {
    // CHECK: call <8 x float> @llvm.sin.v8f32
    simd_fsin(a)
}

// CHECK-LABEL: @fsin_32x16
#[no_mangle]
pub unsafe fn fsin_32x16(a: f32x16) -> f32x16 {
    // CHECK: call <16 x float> @llvm.sin.v16f32
    simd_fsin(a)
}

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f64x2(pub f64, pub f64);

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f64x4(pub f64, pub PubAlias0, pub f64, pub f64);

#[repr(simd)]
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct f64x8(pub f64, pub f64, pub f64, pub f64,
                 pub f64, pub f64, pub f64, pub f64);

// CHECK-LABEL: @fsin_64x4
#[no_mangle]
pub unsafe fn fsin_64x4(a: f64x4) -> f64x4 {
    // CHECK: call <4 x double> @llvm.sin.v4f64
    simd_fsin(a)
}

// CHECK-LABEL: @fsin_64x2
#[no_mangle]
pub unsafe fn fsin_64x2(a: f64x2) -> f64x2 {
    // CHECK: call <2 x double> @llvm.sin.v2f64
    simd_fsin(a)
}

// CHECK-LABEL: @fsin_64x8
#[no_mangle]
pub unsafe fn fsin_64x8(a: f64x8) -> f64x8 {
    // CHECK: call <8 x double> @llvm.sin.v8f64
    simd_fsin(a)
}
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (f67a1acc0 2024-06-01)
binary: rustc
commit-hash: f67a1acc04c7ecbf05751b17592dd8d245b75256
commit-date: 2024-06-01
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

Command: `rustc`

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/inhabitedness/mod.rs:134:17: unimplemented: inhabitedness checking for inherent projections

thread 'rustc' panicked at compiler/rustc_middle/src/ty/inhabitedness/mod.rs:134:17:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: <rustc_middle::ty::Ty>::inhabited_predicate
   7: <&mut <rustc_middle::ty::VariantDef>::inhabited_predicate::{closure#0} as core::ops::function::FnOnce<(&rustc_middle::ty::FieldDef,)>>::call_once
   8: <rustc_middle::ty::inhabitedness::inhabited_predicate::InhabitedPredicate>::all::<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::FieldDef>, <rustc_middle::ty::VariantDef>::inhabited_predicate::{closure#0}>>
   9: <rustc_middle::ty::inhabitedness::inhabited_predicate::InhabitedPredicate>::any::<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::VariantDef>, rustc_middle::ty::inhabitedness::inhabited_predicate_adt::{closure#0}>>
  10: rustc_middle::ty::inhabitedness::inhabited_predicate_adt
      [... omitted 2 frames ...]
  11: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
  12: rustc_middle::ty::inhabitedness::inhabited_predicate_type
      [... omitted 2 frames ...]
  13: <rustc_middle::ty::Ty>::inhabited_predicate
  14: <rustc_pattern_analysis::rustc::RustcPatCtxt>::ctors_for_ty
  15: rustc_pattern_analysis::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis::rustc::RustcPatCtxt>
  16: rustc_pattern_analysis::usefulness::compute_match_usefulness::<rustc_pattern_analysis::rustc::RustcPatCtxt>
  17: rustc_pattern_analysis::analyze_match
  18: <rustc_mir_build::thir::pattern::check_match::MatchVisitor>::analyze_patterns
  19: <rustc_mir_build::thir::pattern::check_match::MatchVisitor>::check_binding_is_irrefutable
  20: rustc_mir_build::thir::pattern::check_match::check_match
      [... omitted 2 frames ...]
  21: rustc_mir_build::build::mir_build
  22: rustc_mir_transform::mir_built
      [... omitted 2 frames ...]
  23: rustc_mir_build::check_unsafety::check_unsafety
      [... omitted 2 frames ...]
  24: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  25: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
  26: <rustc_session::session::Session>::time::<(), rustc_interface::passes::run_required_analyses::{closure#1}>
  27: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  28: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  29: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  30: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/jisukbyun/workspace/240601_100chaos_tree_combine_typ/icefiles/rustc-ice-2024-06-02T06_32_04-2403.txt` to your bug report

query stack during panic:
#0 [inhabited_predicate_adt] computing the uninhabited predicate of `DefId(0:8 ~ r_inhab_E562D7[ad83]::S)`
#1 [inhabited_predicate_type] computing the uninhabited predicate of `S`
#2 [check_match] match-checking `foo`
#3 [mir_built] building MIR for `foo`
#4 [check_unsafety] unsafety-checking `foo`
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error
```

</p>
</details>

### Note
- ICE location: `rustc_middle/src/ty/inhabitedness/mod.rs L134`
  https://github.com/rust-lang/rust/blob/f67a1acc04c7ecbf05751b17592dd8d245b75256/compiler/rustc_middle/src/ty/inhabitedness/mod.rs#L130-L135

### LINKED ISSUE #136678: Cycle error happens when using inherent_associated_types and generic_const_exprs features
### Code

```Rust
#![feature(inherent_associated_types)]
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

struct B<const A: usize>;

struct Test<const A: usize>;

impl<const A: usize> Test<A> {
    type B = B<{ A }>;
    
    fn test(a: Self::B) -> Self::B {
        a
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (942db6782 2025-02-06)
binary: rustc
commit-hash: 942db6782f4a28c55b0b75b38fd4394d0483390f
commit-date: 2025-02-06
host: aarch64-apple-darwin
release: 1.86.0-nightly
LLVM version: 19.1.7
```

### Error output

```
error: internal compiler error[E0391]: cycle detected when computing function signature of `<impl at src/lib.rs:9:1: 9:29>::test`
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing normalized predicates of `<impl at src/lib.rs:9:1: 9:29>::test`...
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing predicates of `<impl at src/lib.rs:9:1: 9:29>::test`...
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing explicit predicates of `<impl at src/lib.rs:9:1: 9:29>::test`...
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...which again requires computing function signature of `<impl at src/lib.rs:9:1: 9:29>::test`, completing the cycle
   = note: cycle used when computing the variances for items in this crate
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:563:16 - disabled backtrace
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
note: delayed at compiler/rustc_query_system/src/query/job.rs:563:16
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::diagnostic::Diag>::delay_as_bug
         4: rustc_query_system::query::plumbing::mk_cycle::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::consts::valtree::Value, rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
         5: rustc_query_system::query::plumbing::cycle_error::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::consts::valtree::Value, rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt>
         6: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
         7: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
         8: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
         9: rustc_hir_analysis::collect::predicates_of::gather_explicit_predicates_of
        10: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::explicit_predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        12: rustc_query_impl::query_impl::explicit_predicates_of::get_query_non_incr::__rust_end_short_backtrace
        13: rustc_hir_analysis::collect::predicates_of::predicates_of
        14: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        15: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        16: rustc_query_impl::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
        17: rustc_ty_utils::ty::param_env
        18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::param_env::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        20: rustc_query_impl::query_impl::param_env::get_query_non_incr::__rust_end_short_backtrace
        21: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
        22: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_assoc_path
        23: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
        24: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
        25: rustc_hir_analysis::collect::lower_fn_sig_recovering_infer_ret_ty
        26: rustc_hir_analysis::collect::fn_sig
        27: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        28: <rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        29: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        30: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
        31: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
        32: <rustc_hir_analysis::variance::constraints::ConstraintContext>::build_constraints_for_item
        33: rustc_hir_analysis::variance::crate_variances
        34: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::crate_variances::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        36: rustc_query_impl::query_impl::crate_variances::get_query_non_incr::__rust_end_short_backtrace
        37: rustc_hir_analysis::variance::variances_of
        38: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::variances_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        39: <rustc_query_impl::query_impl::variances_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        40: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        41: rustc_query_impl::query_impl::variances_of::get_query_non_incr::__rust_end_short_backtrace
        42: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
        43: rustc_hir_analysis::check::wfcheck::check_variances_for_type_defn
        44: rustc_hir_analysis::check::wfcheck::check_well_formed
        45: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        46: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        47: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
        48: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        49: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        50: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        51: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        52: rustc_hir_analysis::check_crate
        53: rustc_interface::passes::run_required_analyses
        54: rustc_interface::passes::analysis
        55: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        56: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        57: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        58: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        59: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        60: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        61: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        62: std::sys::pal::unix::thread::Thread::new::thread_start
        63: <unknown>
        64: clone
  --> src/lib.rs:12:5
   |
12 |     fn test(a: Self::B) -> Self::B {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

</p>
</details>

### LINKED ISSUE #138131: ICE: `unelided lifetime in signature`
auto-reduced (treereduce-rust):
````rust
#![feature(min_generic_const_args)]
#![feature(inherent_associated_types)]
struct Foo<'a> {
    x: &'a (),
}

impl<'a> Foo<'a> {
    fn foo(_: [u8; Foo::X]) {}
}

fn main() {}

````

original:
````rust
struct Foo<'a> { x: &'a () }

impl<'a> Foo<'a> {
    const X: usize = 0;

    fn foo(_: [u8; Foo::X]) {}
}


fn main() {}

````

Version information
````
rustc 1.87.0-nightly (e6af292f9 2025-03-06)
binary: rustc
commit-hash: e6af292f91f21f12ac1aab6825efb7e1e3381cbb
commit-date: 2025-03-06
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(min_generic_const_args) -Zcrate-attr=feature(inherent_associated_types)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(min_generic_const_args)
  |         ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `inherent_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(inherent_associated_types)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information

warning: struct `Foo` is never constructed
 --> /tmp/icemaker_global_tempdir.6nb7eU6SZYdW/rustc_testrunner_tmpdir_reporting.kLVtKi15t0YT/mvce.rs:1:8
  |
1 | struct Foo<'a> {
  |        ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: associated function `foo` is never used
 --> /tmp/icemaker_global_tempdir.6nb7eU6SZYdW/rustc_testrunner_tmpdir_reporting.kLVtKi15t0YT/mvce.rs:6:8
  |
5 | impl<'a> Foo<'a> {
  | ---------------- associated function in this implementation
6 |     fn foo(_: [u8; Foo::X]) {}
  |        ^^^

warning: 4 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: unelided lifetime in signature
 --> /tmp/icemaker_global_tempdir.6nb7eU6SZYdW/rustc_testrunner_tmpdir_reporting.kLVtKi15t0YT/mvce.rs:6:20
  |
6 |     fn foo(_: [u8; Foo::X]) {}
  |                    ^^^
  |
note: delayed at compiler/rustc_hir_analysis/src/collect.rs:417:13
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
         4: <rustc_hir_analysis::collect::ItemCtxt as rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::re_infer
         5: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_path
         6: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
         7: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
         8: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
         9: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
        10: rustc_hir_analysis::collect::lower_fn_sig_recovering_infer_ret_ty
        11: rustc_hir_analysis::collect::fn_sig
        12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        13: <rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
        17: <rustc_hir_analysis::variance::constraints::ConstraintContext>::build_constraints_for_item
        18: rustc_hir_analysis::variance::crate_variances
        19: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::crate_variances::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        21: rustc_query_impl::query_impl::crate_variances::get_query_non_incr::__rust_end_short_backtrace
        22: rustc_hir_analysis::variance::variances_of
        23: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::variances_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        24: <rustc_query_impl::query_impl::variances_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        26: rustc_query_impl::query_impl::variances_of::get_query_non_incr::__rust_end_short_backtrace
        27: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
        28: rustc_hir_analysis::check::wfcheck::check_variances_for_type_defn
        29: rustc_hir_analysis::check::wfcheck::check_well_formed
        30: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        32: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
        33: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        34: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        36: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        37: rustc_hir_analysis::check_crate
        38: rustc_interface::passes::run_required_analyses
        39: rustc_interface::passes::analysis
        40: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        41: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        42: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        43: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        44: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        45: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        46: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        47: std::sys::pal::unix::thread::Thread::new::thread_start
        48: <unknown>
        49: <unknown>
 --> /tmp/icemaker_global_tempdir.6nb7eU6SZYdW/rustc_testrunner_tmpdir_reporting.kLVtKi15t0YT/mvce.rs:6:20
  |
6 |     fn foo(_: [u8; Foo::X]) {}
  |                    ^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (e6af292f9 2025-03-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(min_generic_const_args) -Z crate-attr=feature(inherent_associated_types) -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-inherent_associated_types

### LINKED ISSUE #138166: ICE: `internal compiler error: no type-dependent def for method call`
code
````rust
#![feature(min_generic_const_args)]
#![feature(inherent_associated_types)]
struct a(Box<[u8; Box::b]>);
impl a {
  fn c(self) { self.0.d() }
}
fn main() {}

````

Version information
````
rustc 1.87.0-nightly (b74da9613 2025-03-06)
binary: rustc
commit-hash: b74da9613a8cb5ba67a985f71325be0b7b16c0dd
commit-date: 2025-03-06
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> a.rs:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `inherent_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> a.rs:2:12
  |
2 | #![feature(inherent_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information

warning: type `a` should have an upper camel case name
 --> a.rs:3:8
  |
3 | struct a(Box<[u8; Box::b]>);
  |        ^ help: convert the identifier to upper camel case: `A`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: struct `a` is never constructed
 --> a.rs:3:8
  |
3 | struct a(Box<[u8; Box::b]>);
  |        ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: method `c` is never used
 --> a.rs:5:6
  |
4 | impl a {
  | ------ method in this implementation
5 |   fn c(self) { self.0.d() }
  |      ^

warning: 5 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: bad placeholder type
 --> a.rs:3:19
  |
3 | struct a(Box<[u8; Box::b]>);
  |                   ^^^
  |
note: delayed at compiler/rustc_hir_analysis/src/collect.rs:422:9 - disabled backtrace
 --> a.rs:3:19
  |
3 | struct a(Box<[u8; Box::b]>);
  |                   ^^^

error: internal compiler error: no type-dependent def for method call
 --> a.rs:5:16
  |
5 |   fn c(self) { self.0.d() }
  |                ^^^^^^^^^^
  |
note: delayed at compiler/rustc_privacy/src/lib.rs:1237:26 - disabled backtrace
 --> a.rs:5:16
  |
5 |   fn c(self) { self.0.d() }
  |                ^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/crashes/rustc-ice-2025-03-07T16_04_27-3398785.txt` to your bug report

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-inherent_associated_types

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes rust-lang/rust#108491

Fixes rust-lang/rust#125879
This was due to updating inhabited predicate stuff which I had to do to make constructing ADTs with IATs in fields not ICE

Fixes rust-lang/rust#136678 (but no test added, I don't rly care about weird IAT edge cases under GCE)
Fixes rust-lang/rust#138131

Avoids doing "fully correct" candidate selection for IATs during hir ty lowering when in item signatures as it almost always leads to a query cycle from trying to build a `ParamEnv`. I replaced it with a use `DeepRejectCtxt` which should be able to handle this kind of conservative "could these types unify" while in a context where we don't want to do type equality. 

This is a relatively simple scheme and should be forwards compatible with doing something more complex/powerful.

I'm not really sure how this interacts with rust-lang/rust#126651, though I'm also not really sure its super important to support projecting IATs from IAT self types given we don't even support `T::Assoc::Other` for trait-associated types so didn't give much thought to how this might fit in with that.

r? @compiler-errors
cc @fmease

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 1]
```diff
@@ -444,6 +449,96 @@ impl<'tcx> HirTyLowerer<'tcx> for ItemCtxt<'tcx> {
...
+
+        struct ReplaceAliasesWithInfer<'tcx, 'a>(&'a InferCtxt<'tcx>);
+
+        impl<'tcx> TypeFolder<TyCtxt<'tcx>> for ReplaceAliasesWithInfer<'tcx, '_> {
+            fn cx(&self) -> TyCtxt<'tcx> {
+                self.0.tcx
+            }
+
+            fn fold_ty(&mut self, ty: Ty<'tcx>) -> Ty<'tcx> {
+                if let ty::Alias(_, _) = ty.kind() {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect.rs:471]: Possibly we're supposed to handle free type aliases specially here instead of replacing them with inference variables as it should be possible to just normalize them

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 2]
```diff
@@ -444,6 +449,96 @@ impl<'tcx> HirTyLowerer<'tcx> for ItemCtxt<'tcx> {
...
+        span: Span,
+        self_ty: Ty<'tcx>,
+        candidates: &Vec<InherentAssocCandidate>,
+    ) -> (Vec<InherentAssocCandidate>, Vec<FulfillmentError<'tcx>>) {
+        // This is all rather hacky. We attempt to unify impl headers against this self ty
+        // (even though we aren't really in a position to do so) as users of IATs in signatures
+        // are unable to explicitly disambiguate which impl to use other than by specifying the
+        // self type.
+
+        struct ReplaceAliasesWithInfer<'tcx, 'a>(&'a InferCtxt<'tcx>);
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/collect.rs:463]: Do we need this folder w/ the new solver? We could just relate and throw away all the alias-relate predicates?

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs:463]: Yeah with the new solver this is unnecessary

**Review by compiler-errors — APPROVED** [review]

**Comment by BoxyUwU** [comment]
I should probably update this to use DeepRejectCtxt and handle LTAs correctly like discussed at the all hands :thinking: I was just gonna do it in a followup PR but if I'm having to rebase and figure out new crashes tests then I may aswell just do it all now

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 3]
```diff
@@ -444,6 +448,80 @@ impl<'tcx> HirTyLowerer<'tcx> for ItemCtxt<'tcx> {
...
+
+        assert!(!self_ty.has_infer());
+        let infcx = self
+            .tcx()
+            .infer_ctxt()
+            .ignoring_regions()
+            // We use the next trait solver as it results in alias equality being deferred
+            // which we can then just ignore. We don't evaluate any goals in this infcx so
+            // the actual solver behaviour doesn't really matter...
+            .with_next_trait_solver(true)
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect.rs:471]: cc @rust-lang/initiative-trait-system-refactor 

We now use the new solver for equating IAT/IAC self types with the impl self types when *resolving* the IAT. We do this just to make the code a little simpler as we don't have to explicitly fold away unnormalized aliases to inference variables.

This is only done when *resolving* the IAT/IAC, actual wellformedness checks still use the old solver so this is not soundness relevant- no possible IAT resolution could be unsound (only lead to weird errors or weird inference guidance).

This also should only affect code using `feature(inherent_associated_types)` as IATs are unstable, and IACs are only resolved with this logic when they are used in the type system under `feature(min_generic_const_args)`.

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs:471]: Actually im dumb we were gonna use a deeprejectctxt for this. shout out to remembering things 2s after posting publicly about them

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 4]
```diff
@@ -444,6 +448,80 @@ impl<'tcx> HirTyLowerer<'tcx> for ItemCtxt<'tcx> {
...
+
+                            use rustc_trait_selection::infer::DefineOpaqueTypes;
+                            infcx
+                                // Using an empty `ParamEnv` is pretty weird but we don't actually
+                                // do anything with any of the returned obligations so it doesn't
+                                // matter too much. Building the correct `ParamEnv` would result
+                                // in undesirable query cycles.
+                                .at(&ObligationCause::dummy(), ty::ParamEnv::empty())
+                                .eq(DefineOpaqueTypes::No, self_ty, impl_ty)
+                                .is_ok()
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/collect.rs:514]: do we have a test case exercising the difference between this and just using `DeepReject` here?

It feels somewhat iffy to use `eq` and require that to 1) not rely on where-bounds and 2) don't do any eager trait solving

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs:514]: Ah so `eq` is slightly better around non lifetime binders I think- `for<T> Foo<T>::IAT` will not unify with `impl Foo<u8>` with `eq` but will with `DeepRejectCtxt` that seems perfectly fine to me though.

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs:514]: Oh I guess there's also the recursion depth stuff for deep reject ctxt

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 5]
```diff
@@ -1441,48 +1455,32 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
                 let (item, scope) =
                     self.probe_assoc_item_unchecked(name, assoc_tag, block, impl_)?;
-                Some((impl_, (item.def_id, scope)))
+                Some(InherentAssocCandidate { impl_, assoc_item: item.def_id, scope })
             })
             .collect();
 
-        if candidates.is_empty() {
-            return Ok(None);
-        }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1450]: Removing this masked a bunch of mgca ICEs I think. We now emit errors in all cases where IAT resolution fails to find any candidates which makes some delayed bugs no longer trigger. I've replaced a few of the crashes tests with examples that don't rely on IATs and I removed the two others that I couldn't find a reproducer for that didn't seem like a dupe of the other three.

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 6]
```diff
@@ -444,6 +448,65 @@ impl<'tcx> HirTyLowerer<'tcx> for ItemCtxt<'tcx> {
...
+        // correct `ParamEnv` and it seems dubious to invoke arbitrary trait solving under
+        // the wrong `ParamEnv`. Expanding free aliases doesn't need a `ParamEnv` so we do
+        // this just to make resolution a little bit smarter.
+        let self_ty = self.tcx.expand_free_alias_tys(self_ty);
+        debug!("select_inherent_assoc_candidates: self_ty={:?}", self_ty);
+        
+        // We make an infcx and replace any escaping vars with placeholders so that IAT res
+        // with type/const bound vars in arguments is slightly smarter. `for<T> <Foo<T>>::IAT`
+        // would otherwise unify with `impl Foo<u8>` when ideally we would not.
+        let infcx = self.tcx().infer_ctxt().build(TypingMode::non_body_analysis());
```
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/collect.rs:470]: do u need to? id expect expand free aliases to handle escaping bound vars. so does deep reject

[the remark this answers is not in the document]
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs:470]: deep reject "handles" escaping vars by allowing them to unify with anything, which is weaker resolution than replacing with placeholders. See `tests/ui/associated-inherent-types/bound_vars_in_args.rs` which fails if we don't replace with placeholders

File: compiler/rustc_hir_analysis/src/collect.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs]: I'll add a test for this :thinking: I quite like using deep reject instead of hacky type equality where we use a wrong paramenv and such, but I also feel like we should probably be able to handle this case,

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect.rs]: Added a test

**Comment by BoxyUwU** [comment]
oh come on lol

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 7]
```diff
@@ -308,6 +312,74 @@ impl<'tcx> HirTyLowerer<'tcx> for FnCtxt<'_, 'tcx> {
...
+                            );
+                            ocx.register_obligations(impl_obligations);
+
+                            let mut errors = ocx.select_where_possible();
+                            if !errors.is_empty() {
+                                fulfillment_errors.append(&mut errors);
+                                return false;
+                            }
+
+                            true
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs]: move this into a sub_fn

File: compiler/rustc_type_ir/src/fast_reject.rs [hunk 8]
```diff
@@ -238,6 +238,13 @@ impl<I: Interner, const INSTANTIATE_LHS_WITH_INFER: bool, const INSTANTIATE_RHS_
         self.types_may_unify_inner(lhs, rhs, Self::STARTING_DEPTH)
     }
 
+    pub fn types_may_unify_with_depth(self, lhs: I::Ty, rhs: I::Ty, depth_limit: usize) -> bool {
+        if lhs == rhs {
+            return true;
+        }
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/fast_reject.rs]: this fast path should be in `types_may_unify_inner`

Comment (lcnr) [reply compiler/rustc_type_ir/src/fast_reject.rs]: #142355

Comment (lcnr) [reply compiler/rustc_type_ir/src/fast_reject.rs]: please remove

File: tests/ui/associated-inherent-types/bound_vars_in_args.rs [hunk 9]
```diff
@@ -0,0 +1,22 @@
+#![feature(non_lifetime_binders, inherent_associated_types)]
+#![expect(incomplete_features)]
+
+// Test that we can resolve to the right IAT when the self type
+// contains a bound type.
```
Comment (lcnr) [inline tests/ui/associated-inherent-types/bound_vars_in_args.rs]:
```suggestion
// Test whether we can resolve to the right IAT when the self type
// contains a bound type. This should ideally use the second impl.
```

File: tests/ui/associated-inherent-types/candidate-with-alias-2.rs [hunk 10]
```diff
@@ -0,0 +1,26 @@
+#![feature(inherent_associated_types)]
+#![expect(incomplete_features)]
+
```
Comment (lcnr) [inline tests/ui/associated-inherent-types/candidate-with-alias-2.rs:3]:
```suggestion

// A behavior test showcasing that we do not normalize associated types when
// assembling IAT candidates.
```

File: tests/ui/associated-inherent-types/candidate-with-alias.rs [hunk 11]
```diff
@@ -0,0 +1,27 @@
+//@ check-pass
+
+#![feature(inherent_associated_types)]
+#![expect(incomplete_features)]
+
```
Comment (lcnr) [inline tests/ui/associated-inherent-types/candidate-with-alias.rs:5]: comment

File: tests/ui/associated-inherent-types/multiple-candidates-in-adt-field-2.rs [hunk 12]
```diff
@@ -0,0 +1,29 @@
+#![feature(inherent_associated_types)]
+#![expect(incomplete_features)]
+
+// Test that when we have an unnormalized projection we don't normalize it
+// to determine which IAT to resolve to.
```
Comment (lcnr) [inline tests/ui/associated-inherent-types/multiple-candidates-in-adt-field-2.rs]: difference between this test and tests/ui/associated-inherent-types/candidate-with-alias-2.rs?

**Review by lcnr — COMMENTED** [review]
nits, then r=me

File: tests/ui/associated-inherent-types/multiple-candidates-in-adt-field-2.rs (hunk 12 above)
Comment (BoxyUwU) [reply tests/ui/associated-inherent-types/multiple-candidates-in-adt-field-2.rs]: whether the alias is on the impl self ty or the IAT self ty :thinking: probably won't have a case where we mess up one of these but not the other but still feels fine to have two tests :3

**Comment by Kobzol** [comment]
@bors r-

PR CI failed.
