### PR TITLE
Normalize return type of `deduce_future_output_from_obligations`

### LINKED ISSUE #114727: TAIT: concrete type differs from previous defining opaque type use at the same location
"previous use here" seems to be the same location as the error?

```rust
error: concrete type differs from previous defining opaque type use
   --> src/storage/src/table/batch_table/storage_table.rs:505:9
    |
505 |         Ok(iter)
    |         ^^^^^^^^ expected `StorageTableInnerIter<S, SD>`, got `impl Stream<Item = std::result::Result<(Vec<u8>, OwnedRow), error::StorageError>> + 'static`
    |
note: previous use here
   --> src/storage/src/table/batch_table/storage_table.rs:412:54
    |
412 |       ) -> StorageResult<StorageTableInnerIter<S, SD>> {
    |  ______________________________________________________^
413 | |         let cache_policy = match (
414 | |             encoded_key_range.start_bound(),
415 | |             encoded_key_range.end_bound(),
...   |
505 | |         Ok(iter)
506 | |     }
    | |_____^

warning: `risingwave_storage` (lib) generated 1 warning
```

Note: tested latest `2023-08-11`, and reports same error.

Tested on this commit https://github.com/risingwavelabs/risingwave/commit/9d3e587b0aeb2b0f4236953b6015a6f1b864c1bf

```
cargo build -p risingwave_storage
```
(Sorry for not having a minimal example yet)

---

Bisect rustc and found the regression commit:

searched nightlies: from nightly-2023-06-16 to nightly-2023-07-08
regressed nightly: nightly-2023-06-18
searched commit range: https://github.com/rust-lang/rust/compare/6bba061467f7c2cab04b262b95eb67bf89265587...3b2073f0762cff4d3d625bb10017e0ce4e7abe50
regressed commit: https://github.com/rust-lang/rust/commit/0cc541e4b2eb957e71490cf44df1ac09f6d18132

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start 2023-06-16 --end 2023-07-08 -- build -p risingwave_storage 
```
</details>

---

Source code here

https://github.com/risingwavelabs/risingwave/blob/tygg-bump-toolchain-20230728/src/storage/src/table/batch_table/storage_table.rs#L386-L388

https://github.com/risingwavelabs/risingwave/blob/9d3e587b0aeb2b0f4236953b6015a6f1b864c1bf/src/storage/src/table/batch_table/storage_table.rs#L404-L504

### LINKED ISSUE #114909: Regression of TAIT with generics
I tried this code:

```rust
#![feature(type_alias_impl_trait)]

struct Foo;

impl Trait for Foo {}
pub trait Trait {}

pub type TAIT<T> = impl Trait;

async fn foo<T>() -> TAIT<T> {
    Foo
}
```

It failed with a confusing error message. (error: concrete type differs from previous defining opaque type use, at the same location)

```rust
error: concrete type differs from previous defining opaque type use
  --> src/main.rs:11:5
   |
11 |     Foo
   |     ^^^ expected `TAIT<T>`, got `Foo`
   |
note: previous use here
  --> src/main.rs:10:30
   |
10 |   async fn foo<T>() -> TAIT<T> {
   |  ______________________________^
11 | |     Foo
12 | | }
   | |_^
```

---

I'm trying to minimize https://github.com/rust-lang/rust/issues/114727, and found the problem.

`nightly-2023-06-17` compiles, but `nightly-2023-06-18` fails. Although not 100% sure, I think it's caused by the same problem as #114727 (regression caused by https://github.com/rust-lang/rust/pull/108860)

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #114909
Also confirmed to fix #114727 manually

Now that we have weak/lazy type aliases, we need to normalize those in future signatures to ensure that `replace_opaque_types_with_inference_vars` actually sees TAITs behind them. This isn't needed in the new solver, but added a test to make sure it doesn't regress there either.

r? types cc @oli-obk (who's gone, worst case can delay this PR until he's back)

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 1]
```diff
@@ -724,20 +726,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 .find_map(|(p, s)| get_future_output(p.as_predicate(), s))?,
             ty::Error(_) => return None,
             _ => span_bug!(
-                self.tcx.def_span(expr_def_id),
+                span,
                 "async fn generator return type not an inference variable: {ret_ty}"
             ),
         };
 
+        let output_ty = self.normalize(span, output_ty);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/closure.rs:734]: can you move the `normalize` call into the `ty::Alias` branch? for infer vars the obligation should already be normalized

**Review by lcnr — COMMENTED** [review]
r=me after handling nit (or without it :grin:)

File: compiler/rustc_hir_typeck/src/closure.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:734]: That's the alias that corresponds to the `impl Future`. The type we want to normalize here is the `Output` of that future, which depends on what we extract out of `get_future_output`.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:734]: Wait, wait, I think I understand here.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:734]: Actually, we still may have unnormalized obligations for infer vars as well. The obligations returned from `replace_opaque_with_infer` and `handle_opaque_ty` are not normalized, afaict.
