### PR TITLE
Opaque type collection: Guard against endlessly recursing free alias types

### LINKED ISSUE #131994: crash: lazy type alias: stack overflow
### Code

```Rust
#![feature(lazy_type_alias)]
type A = [[Y; {}]; {
    type A = [A; {}];
}];

```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (662180b34 2024-10-20)
binary: rustc
commit-hash: 662180b34d95f72d05b7c467b0baf4d23d36b1e1
commit-date: 2024-10-20
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0412]: cannot find type `Y` in this scope
 --> /tmp/crash.rs:2:12
  |
2 | type A = [[Y; {}]; {
  |            ^ not found in this scope

warning: the feature `lazy_type_alias` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/crash.rs:1:12
  |
1 | #![feature(lazy_type_alias)]
  |            ^^^^^^^^^^^^^^^
  |
  = note: see issue #112792 <https://github.com/rust-lang/rust/issues/112792> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `crash`
 --> /tmp/crash.rs:4:4
  |
4 | }];
  |    ^ consider adding a `main` function to `/tmp/crash.rs`

error[E0308]: mismatched types
 --> /tmp/crash.rs:2:15
  |
2 | type A = [[Y; {}]; {
  |               ^^ expected `usize`, found `()`

error: rustc interrupted by SIGSEGV, printing backtrace

/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x37207d3) [0x732bf89207d3]
/usr/lib/libc.so.6(+0x3d1d0) [0x732bfc5bb1d0]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x5011e81) [0x732bfa211e81]

### cycle encountered after 3 frames with period 4
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x50124ce) [0x732bfa2124ce]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x5011e86) [0x732bfa211e86]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x50124ce) [0x732bfa2124ce]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x5011e86) [0x732bfa211e86]
### recursed 63 times

/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-5396912e8af1f65d.so(+0x50124ce) [0x732bfa2124ce]

note: rustc unexpectedly overflowed its stack! this is a bug
note: maximum backtrace depth reached, frames may have been lost
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fmease**
See test description for technical details.

Fixes https://github.com/rust-lang/rust/issues/131994.

r? oli-obk (sry, your queue is large, so no rush & feel free to reassign)

### CODE REVIEW

File: compiler/rustc_ty_utils/src/opaque_types.rs [hunk 1]
```diff
@@ -223,7 +223,10 @@ impl<'tcx> TypeVisitor<TyCtxt<'tcx>> for OpaqueTypeCollector<'tcx> {
             }
             // Skips type aliases, as they are meant to be transparent.
             // FIXME(type_alias_impl_trait): can we require mentioning nested type aliases explicitly?
-            ty::Alias(ty::Free, alias_ty) if alias_ty.def_id.is_local() => {
+            ty::Alias(ty::Free, alias_ty) if let Some(def_id) = alias_ty.def_id.as_local() => {
+                if !self.seen.insert(def_id) {
```
Comment (fmease) [inline compiler/rustc_ty_utils/src/opaque_types.rs:227]: Of course, this only guards against cyclic alias types, not against "overly deep" ones. It's within the realm of possibility that this still overflows the stack on inputs like `type T${n} = T${n+1}; type T${N} = ();` where 0 ≤ `n` < `N` where `N` is *large* (like >10_000 which is the maximum I tested and which took a while to compile but didn't exhibit a stack overflow).

However, rustc struggles on such inputs anyway today whether eager or lazy (I already found a bunch of boring hangs).

Keeping track of depth instead of visited types would address that but I didn't want to make large modifications to this collector. I thought about utilizing `tcx.expand_free_alias_tys` in appropriate places which can deal with such inputs. However, that might be incompatible with `// FIXME(type_alias_impl_trait): can we require mentioning nested type aliases explicitly?` which I guess is referring to constructions like:

```rs
#![feature(type_alias_impl_trait)]
// #[define_opaque(Inner)] // <-- (?)
type Outer = Inner;
type Inner = impl Sized;
// ...
```

or sth. like that >.<

Comment (oli-obk) [reply compiler/rustc_ty_utils/src/opaque_types.rs:227]: Yea, those are fine. I think we can address generated worst-case input code situations as they occur. Most likely we have enough `ensure_sufficient_stack` in place already.
