### PR TITLE
Be more specific when type parameter shadows primitive type

### LINKED ISSUE #35030: Confusing error message due to type parameter name
This code is wrong, but the error message is confusing:

```rust
trait Parser<T> {
    fn parse(text: &str) -> Option<T>;
}

impl<bool> Parser<bool> for bool {
    fn parse(text: &str) -> Option<bool> {
        Some(true)
    }
}

fn main() {
    println!("{}", bool::parse("ok").unwrap_or(false));
}
```

Because I used `bool` accidentally as a type name when not using the right syntax ... this is pretty confusing:

```
error: mismatched types [--explain E0308]
 --> <anon>:7:14
7 |>         Some(true)
  |>              ^^^^ expected type parameter, found bool
note: expected type `bool`
note:    found type `bool`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by estebank**
When a type parameter shadows a primitive type, the error message
was non obvious. For example, given the file `file.rs`:

``` rust
trait Parser<T> {
    fn parse(text: &str) -> Option<T>;
}

impl<bool> Parser<bool> for bool {
    fn parse(text: &str) -> Option<bool> {
        Some(true)
    }
}

fn main() {
    println!("{}", bool::parse("ok").unwrap_or(false));
}
```

The output was:

``` bash
% rustc file.rs
error[E0308]: mismatched types
 --> file.rs:7:14
  |
7 |         Some(true)
  |              ^^^^ expected type parameter, found bool a
  |
  = note: expected type `bool`
  = note:    found type `bool`

error: aborting due to previous error
```

We now show extra information about the type:

``` bash
% rustc file.rs
error[E0308]: mismatched types
 --> file.rs:7:14
  |
7 |         Some(true)
  |              ^^^^ expected type parameter, found bool a
  |
  = note: expected type `bool` (type parameter)
  = note:    found type `bool` (bool)

error: aborting due to previous error
```

Fixes #35030

### CODE REVIEW

File: src/librustc_errors/lib.rs [hunk 1]
```diff
@@ -274,9 +274,20 @@ impl<'a> DiagnosticBuilder<'a> {
...
+                                     found: &fmt::Display,
+                                     expected_extra: &fmt::Display,
+                                     found_extra: &fmt::Display)
+                                     -> &mut DiagnosticBuilder<'a>
+    {
         // For now, just attach these as notes
-        self.note(&format!("expected {} `{}`", label, expected));
-        self.note(&format!("   found {} `{}`", label, found));
+        self.note(&format!("expected {} `{}` {}", label, expected, expected_extra));
+        self.note(&format!("   found {} `{}` {}", label, found, found_extra));
```
Comment (TimNN) [inline src/librustc_errors/lib.rs]: I think it would be preferable to move the added spaces to the `_extra` variables, so that there isn't any trailing space in case the `_extra` variables are empty.

That should also fix the current three ui test failures.

Comment (estebank) [inline src/librustc_errors/lib.rs]: I've done so and rebased. All tests now pass.

File: src/librustc/infer/error_reporting.rs [hunk 2]
```diff
@@ -550,7 +550,16 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
             };
 
             if !is_simple_error {
-                diag.note_expected_found(&"type", &expected, &found);
+                if expected == found {
+                  if let &TypeError::Sorts(ref values) = terr {
```
Comment (jseyfried) [inline src/librustc/infer/error_reporting.rs]: nit: This should be indented four spaces.

**Comment by jseyfried** [comment]
LGTM modulo comment

**Comment by nikomatsakis** [comment]
Yes, as @jseyfried noted, it seems like we are now missing a case where the "expected found" will not be printed, but otherwise looks good to me.

**Comment by nikomatsakis** [comment]
It'll be nice to see this fixed!

**Comment by estebank** [comment]
@nikomatsakis, @jseyfried incorporated your comments and rebased.

**Comment by estebank** [comment]
@nikomatsakis I believe this might be ready for merging. Would you agree?

**Comment by jseyfried** [comment]
@estebank Thanks for the PR!

**Comment by estebank** [comment]
@jseyfried my pleasure!
