### PR TITLE
Windows Command: Don't run batch files using verbatim paths

### LINKED ISSUE #95178: Windows Command regression - broken paths
### Code

I tried this code:

```rust
fn main() {
	std::process::Command::new("folder/echo.bat")
		.args(["hello"])
		.status()
		.unwrap();
}
```

where `folder/echo.bat` is
```bat
echo %*
```

I expected to see this happen:
```
   Compiling repro v0.1.0 (D:\projects\2022-03-20-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 1.03s
     Running `target\debug\repro.exe`

D:\projects\2022-03-20-repro>echo hello
hello
```

Instead, this happened:
```
   Compiling repro v0.1.0 (D:\projects\2022-03-20-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.95s
     Running `target\debug\repro.exe`

The system cannot find the path specified.
```

### Version it worked on
`rustc --version --verbose`:
```
rustc 1.61.0-nightly (1bfe40d11 2022-03-18)
binary: rustc
commit-hash: 1bfe40d11c3630254504fb73eeccfca28d50df52
commit-date: 2022-03-18
host: x86_64-pc-windows-msvc
release: 1.61.0-nightly
LLVM version: 14.0.0
```
(aka `nightly-2022-03-19`)

### Version with regression
`rustc --version --verbose`:
```
rustc 1.61.0-nightly (8d60bf427 2022-03-19)
binary: rustc
commit-hash: 8d60bf427a4b055f464122062e76b3ec34d4f8ba
commit-date: 2022-03-19
host: x86_64-pc-windows-msvc
release: 1.61.0-nightly
LLVM version: 14.0.0
```
(aka `nightly-2022-03-20`)

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #95178

Note that the first commit does some minor refactoring (moving command line argument building to args.rs). The actual changes are in the second.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
This is also a first step toward #94743. Rust no longer relies on the undocumented behaviour of `CreateProcessW` to run batch files. Instead it knows how to run them explicitly.

I also want to eventually do further refactoring of argument building. Given the growing number of options, a builder struct may be more appropriate. But I don't want to do that all in one PR.

File: library/std/src/sys/windows/args.rs [hunk 1]
```diff
@@ -234,3 +236,152 @@ impl Iterator for WStrUnits<'_> {
...
+}
+
+pub(crate) fn make_bat_command_line(
+    script: &[u16],
+    args: &[Arg],
+    force_quotes: bool,
+) -> io::Result<Vec<u16>> {
+    // Set the start of the command line to `cmd.exe /c "`
+    // It is necessary to surround the command in an extra pair of quotes,
+    // hence The trailing quote here. It will be closed after all arguments
```
Comment (joshtriplett) [inline library/std/src/sys/windows/args.rs:310]:
```suggestion
    // hence the trailing quote here. It will be closed after all arguments
```

File: library/std/src/sys/windows/args.rs [hunk 2]
```diff
@@ -234,3 +236,152 @@ impl Iterator for WStrUnits<'_> {
...
+    // have been added.
+    let mut cmd: Vec<u16> = "cmd.exe /c \"".encode_utf16().collect();
+
+    // Push the script name surrounded by its quote pair.
+    cmd.push(b'"' as u16);
+    cmd.extend_from_slice(script.strip_suffix(&[0]).unwrap_or(script));
```
Comment (joshtriplett) [inline library/std/src/sys/windows/args.rs:316]: Could this use `append_arg`? What happens if the script name needs quoting?

Comment (ChrisDenton) [reply library/std/src/sys/windows/args.rs:316]: It will only need quoting if it contains a `"`, which cannot occur in Windows file names. The problem with `append_arg` is it requires a `OsString` whereas at this point we have the UTF-16 string that was used to test if the file exists. I admit I'm somewhat reluctant to keep switching between encodings.

For now maybe an alternative is to return an error if the script name does in fact contain `"`?

Comment (joshtriplett) [reply library/std/src/sys/windows/args.rs:324]: Can `"` occur in filenames that get interpreted by a driver (e.g. a filesystem driver for a foreign filesystem)?

Could a `\` ever occur at the *end* of a filename that could be executable? Is it theoretically possible to achieve a filename ending in `\` using reparse points, or NTFS Streams, or special `\\` paths? If so, would the `\` escape the `"`?

File: library/std/src/sys/windows/args.rs [hunk 3]
```diff
@@ -307,12 +307,20 @@ pub(crate) fn make_bat_command_line(
...
     // Push the script name surrounded by its quote pair.
     cmd.push(b'"' as u16);
+    // Windows file names cannot contain a `"` character.
+    // If the script name does then return an error.
+    if script.contains(&(b'"' as u16)) {
+        return Err(io::const_io_error!(
+            io::ErrorKind::InvalidInput,
+            "Windows file names may not contain `\"`"
+        ));
+    }
```
Comment (joshtriplett) [inline library/std/src/sys/windows/args.rs:323]: Thank you, this does seem safer.

File: library/std/src/sys/windows/args.rs (hunk 2 above)
Comment (ChrisDenton) [reply library/std/src/sys/windows/args.rs:324]: In [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) search for "reserved characters". There's a list of characters that are reserved for special use by the OS. These cannot be used in filenames at all. Indeed, `argv[0]` depends upon this fact as a [`"` cannot be escaped in `argv[0]`](https://github.com/rust-lang/rust/blob/4ce257ff198d23bdf14e956fbf2fe0fed297201f/library/std/src/sys/windows/args.rs#L79).

A trailing `\` is guarded against [earlier](https://github.com/rust-lang/rust/blob/4ce257ff198d23bdf14e956fbf2fe0fed297201f/library/std/src/sys/windows/process.rs#L375) and I cannot think of a way that such a filename could be possible to returned from the OS. Though I guess double checking wouldn't hurt.

Comment (ChrisDenton) [reply library/std/src/sys/windows/args.rs:324]: I adjusted the last commit to do just that.

File: library/std/src/sys/windows/args.rs [hunk 4]
```diff
@@ -307,12 +307,20 @@ pub(crate) fn make_bat_command_line(
...
     let mut cmd: Vec<u16> = "cmd.exe /c \"".encode_utf16().collect();
 
     // Push the script name surrounded by its quote pair.
     cmd.push(b'"' as u16);
+    // Windows file names cannot contain a `"` character or end with `\\`.
+    // If the script name does then return an error.
+    if script.contains(&(b'"' as u16)) || script.last() == Some(&(b'\\' as u16)) {
+        return Err(io::const_io_error!(
+            io::ErrorKind::InvalidInput,
+            "Windows file names may not contain `\"` or `\\`"
```
Comment (joshtriplett) [inline library/std/src/sys/windows/args.rs:321]:
```suggestion
            "Windows file names may not contain `\"` or end with `\\`"
```

**Comment by joshtriplett** [comment]
LGTM, r=me with the message nit fixed.

**Comment by ChrisDenton** [comment]
Hm, the failure is caused by https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/issue-15149.rs.
Which is a test added for #15149. The test ends up specifically testing if argv[0] ends with `.exe`. It should probably be testing `env::current_exe()` instead.

**Comment by ChrisDenton** [comment]
Oh, looks like my format-on-save has been to work on that file. The actual changes are lines 8, 22 and 23.

**Comment by shuffle2** [comment]
hi @ChrisDenton . I'm writing some rust code that needs `argv` identically to the way a C/C++ application would receive them (on modern windows). I was thrown off for some time because of the comments above the `parse_lp_cmd_line` seem to point to the wrong things. In actuality, "normal" CRT-based apps on windows use `ucrtbase.dll!_configure_wide_argv` (or the narrow one) to parse the command line. The source for this gets installed into e.g. `C:\Program Files (x86)\Windows Kits\10\Source\10.0.22000.0\ucrt\startup\argv_parsing.cpp` when you install the build tools. I just thought I'd mention it because I was confused about the apparent implementation by trial and error in rust to adhere to this behavior for which the source is actually available - I thought maybe you weren't aware.

afaict at least the daviddeley.com link and the mention of shell32 are therefor out-of-date and/or wrong.

I'll probably still reimplement it for my project...

**Comment by ChrisDenton** [comment]
hi @shuffle2, thanks for the comment!

I'm aware that the ucrt source is available but I've avoided looking at it because I'm unclear if that would cause licensing issues. I'm not a lawyer and haven't hired one so I've taken the cautious approach as I don't want to cause problems for the Rust project in the future.

For now I'm going on public information and my own experimentation. If anyone wanted to write a more accurate description then that would be very welcome!

**Comment by shuffle2** [comment]
[continuing this conversion here... :)]

after looking at stuff a bit more, I realized that rust executables are already linking against and executing this code in ucrt. If you dynamic link against crt it's obvious by looking for imports from "api-ms-win-crt-*" libraries (these all get routed to ucrtbase.dll under the hood). In either case (dynamic or static link against crt), the function `pre_c_initialization` will be called before `main` (which is where the actual rust code begins). `pre_c_initialization` will (among other things) perform the initialization of `argv`. As far as I can tell, rust is also always compiling against ucrt in non-unicode mode (the `argv` and etc are using the "narrow" methods).

So, this created more questions than answers unfortunately:
1) Is rust knowingly linking against ucrt? Since `target-feature=+crt-static` is well documented I assume it's intentional, even though it's not yet clear to me where rust actually depends on it. Any idea what the reasoning is here? (maybe rust depends on ucrt to provide some machinery like TLS/stack cookie/other OS integrations?)
2) If rust already depends on ucrt for some reason, can we make it use wide characters (probably it should anyway, just to lessen possible confusion/footguns), and then just use the `argv` it has prepared? It's not clear to me why rust would let ucrt do the work but ignore the result.

**Comment by ChrisDenton** [comment]
The standard library does not decide on the program's entry point. That's the job of the Rust compiler. If you think it should instead use `wmain` and pass arguments to the std, then you should definitely open a new issue about that rather than discussing it on an unrelated and closed PR that's likely only being read by me. 🙂

> Is rust knowingly linking against ucrt?

MSVC Rust needs the vcruntime for mem* functions and C++ exceptions. This in turn depends on having a crt. Rust also uses the C runtime for process startup/shutdown code and running pre-main initializers. So yes, it's "knowingly" linking against ucrt but it's incidental and could even change in the future (e.g. if we decide to reimplement the needed bits in pure Rust for some reason).

MinGW Rust does not link against the UCRT and so that toolchain will have different parsing rules. There can also be third-party toolchains that do their own thing (or skip arguments entirely). And even MSVC allows changing or disabling the parsing using [special object files](https://docs.microsoft.com/en-us/cpp/c-runtime-library/link-options?view=msvc-170).

It may be surprising if `std::env::args` varied between Rust programs. Then again, this may be something you'd want. Either way I do think this should be a new issue.

**Comment by shuffle2** [comment]
> The standard library does not decide on the program's entry point. That's the job of the Rust compiler. If you think it should instead use `wmain` and pass arguments to the std, then you should definitely open a new issue about that rather than discussing it on an unrelated and closed PR that's likely only being read by me. 🙂

yes well, I stalked the git blame and picked someone who had modified the code recently :D I'm not really sure where is a good forum for this topic - I checked discord and zulip and they seem unrelated and/or inactive. If just filing a github issue is the way, then I'll do that (eventually). Thanks!

**Comment by ChrisDenton** [comment]
Zulip would also be a great place to ask. Many people involved with Rust (both compiler and libs) are active there.

In general closed PRs are somewhat "hidden" because few people will notice new comments.
