### PR TITLE
GATs outlives lint: Try to prove bounds

### LINKED ISSUE #90888: `Self: 'static` causes GAT outlives lint to needlessly fire
The following code [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=efc32d83dfbd2c1e2f34396177718e44):

```rust
#![feature(generic_associated_types)]

trait Trait: 'static {
    type Assoc<'a>;
    fn make_assoc(_: &u32) -> Self::Assoc<'_>;
}
```

Gives an error:
```
error: Missing required bounds on Assoc
 --> src/lib.rs:4:5
  |
4 |     type Assoc<'a>;
  |     ^^^^^^^^^^^^^^-
  |                   |
  |                   help: add the required where clauses: `where Self: 'a`
```

I would have expected the `where Self: 'a` not to be required as we already know that `Self` outlives `'a` as it outlives `'static`

### Meta
rustc version: 1.58.0-nightly (e90c5fbbc 2021-11-12)

### LINKED ISSUE #91036: Lifetime in GAT must outlive trait parameters
Related to https://github.com/rust-lang/rust/pull/89970

## Code

```rust
#![feature(generic_associated_types)]

trait T<'ctx> {
    type Fut<'out> 
    where 
        'ctx: 'out, 
        Self: 'out;
    
    fn test<'me, 'out>(&'me self, ctx: &'ctx i32) -> Self::Fut<'out>
    where
        'me: 'out,
        'ctx: 'out;
}
```

Basically I want to desugar `async fn`. For this I need to describe `Fut` GAT that lives the smallest of the `'me` and `'ctx`, but I get compiler error with requirement that doesn't really make sense to me.

```
error: Missing required bounds on Fut
 --> src/lib.rs:4:5
  |
4 | /     type Fut<'out> 
5 | |     where 
6 | |         'ctx: 'out, 
7 | |         Self: 'out;
  | |                   ^ help: add the required where clauses: `, 'out: 'ctx`
  | |___________________|
  | 

error: could not compile `playground` due to previous error
```

`'out` cant't outlive `'ctx`.

## Meta

fails on `1.58.0-nightly (2021-11-18 cc946fcd326f7d85d4af)` [Playground]

[Playground]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1e3760ee5aea5d551e498b7b14d59319

### LINKED ISSUE #91348: GATs: repeating not-locally-required bounds on impls?
See: #87479

So, I believe #89970 broke my code [kas-text](https://github.com/kas-gui/kas-text/blob/master/src/format.rs) (nightly rustc + `--feature gat`).

> Let's focus on the iter function. The first thing to realize is that we know that Self: 'a because of &'a self

This isn't true in *general*, though it may be in specific instances. My code (reduced) exemplifies this perfectly:
```rust
pub trait FormattableText: std::fmt::Debug {
    type FontTokenIter<'a>: Iterator<Item = FontToken>;

    fn font_tokens<'a>(&'a self, dpp: f32, pt_size: f32) -> Self::FontTokenIter<'a>;
}

impl<'t> FormattableText for &'t str {
    type FontTokenIter<'a> = std::iter::Empty<FontToken>;

    fn font_tokens<'a>(&'a self, _: f32, _: f32) -> Self::FontTokenIter<'a> {
        std::iter::empty()
    }
}
```
Here, `font_tokens` *may* return an iterator over an instance of `Self`... but it also may not (`&str` does not have any formatting). ~~A possible workaround in the impl is to write a custom iterator with a reference to the `&str` *anyway*, but this seems unnecessary.~~

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #91036
Fixes #90888
Fixes #91348 (better error + documentation to be added to linked issue)

Instead of checking for bounds directly, try to prove them in the associated type environment.

Also, add a bit of extra information to the error, including a link to the relevant discussion issue (#87479). That should be edited to include a brief summary of the current state of the outlives lint, including a brief background. It also might or might not be worth it to bump this to a full error code at some point.

r? @nikomatsakis

### CODE REVIEW

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 1]
```diff
@@ -541,7 +607,8 @@ fn region_known_to_outlive<'tcx>(
         });
 
         use rustc_infer::infer::outlives::obligations::TypeOutlivesDelegate;
-        (&infcx).push_sub_region_constraint(origin, region_a, region_b);
+        // `region_a: region_b` -> `region_b <= region_a`
+        (&infcx).push_sub_region_constraint(origin, region_b, region_a);
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/wfcheck.rs:611]: This is separate from the above logic; bug fix for #91036

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 2]
```diff
@@ -455,11 +481,19 @@ fn check_gat_where_clauses(
...
-                "add the required where clauses",
+                &format!("add the required where clause{}", plural),
                 suggestion,
                 Applicability::MachineApplicable,
             );
 
+            let bound = if clauses.len() > 1 { "these bounds are" } else { "this bound is" };
+            err.note(&format!("{} required to ensure that impls have maximum flexibility", bound));
+            err.note(
+                "see issue #87479 \
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/wfcheck.rs:492]:
```suggestion
                "we are soliciting feedback, see issue #87479 \
```

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 3]
```diff
@@ -455,11 +481,19 @@ fn check_gat_where_clauses(
...
             err.span_suggestion(
                 trait_item.generics.where_clause.tail_span_for_suggestion(),
-                "add the required where clauses",
+                &format!("add the required where clause{}", plural),
                 suggestion,
                 Applicability::MachineApplicable,
             );
 
+            let bound = if clauses.len() > 1 { "these bounds are" } else { "this bound is" };
+            err.note(&format!("{} required to ensure that impls have maximum flexibility", bound));
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/wfcheck.rs:490]:
```suggestion
            err.note(&format!("{} currently required to ensure that impls have maximum flexibility", bound));
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Comment by nikomatsakis** [comment]
r=me with the above changes
