### PR TITLE
Give better suggestion when const Range*'s are used as patterns

### LINKED ISSUE #76191: Matching a const Range
When I was doing rustlings, I found out it is possible to match with a range which is coded like this:
``` rust
fn color(n: i32) -> Option<u8> {
    match n {
        0..=255 => Some(n as u8),
        _ => None,
    }
}
```

but when I trying to replace the range with a const, 
``` rust
use std::ops::RangeInclusive;

const RGB_RANGE: RangeInclusive<i32> = 0..=255;

fn color(n: i32) -> Option<u8> {
    match n {
        RGB_RANGE => Some(n as u8),
        _ => None,
    }
}
```

the compiler gives error:
```
error[E0308]: mismatched types
 --> src/main.rs:7:9
  |
3 | const RGB: RangeInclusive<i32> = 0..=255;
  | ----------------------------------------- constant defined here
...
6 |     match n {
  |           - this expression has type `i32`
7 |         RGB => Some(n as u8),
  |         ^^^
  |         |
  |         expected `i32`, found struct `std::ops::RangeInclusive`
  |         `RGB` is interpreted as a constant, not a new binding
  |         help: introduce a new binding instead: `other_rgb`
  |
  = note: expected type `i32`
           found struct `std::ops::RangeInclusive<i32>`
```

I have no idea why matching a literal range is possible but not matching a constant which type is RangeInclusive.

### PR DESCRIPTION
**Pull request by guswynn**
Fixes #76191

let me know if there is more/different information you want to show in this case

### CODE REVIEW

File: src/test/ui/issues/issue-76191.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// Regression test for diagnostic issue #76191
+#![allow(non_snake_case)]
+
+use std::ops::RangeInclusive;
+const RANGE: RangeInclusive<i32> = 0..=255;
+
+fn main() {
+    let n: i64 = 1;
```
Comment (jonas-schievink) [inline src/test/ui/issues/issue-76191.rs:8]:
```suggestion
    let n: i32 = 1;
```

File: compiler/rustc_typeck/src/check/pat.rs [hunk 2]
```diff
@@ -772,6 +772,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         let msg = "introduce a new binding instead";
                         let sugg = format!("other_{}", ident.as_str().to_lowercase());
                         e.span_suggestion(ident.span, msg, sugg, Applicability::HasPlaceholders);
+                        match res {
+                            Res::Def(DefKind::Const, _) => {
+                                let const_msg = "Constants currently only support matching the same type. \
+                                This may support for structural matches in the future. \
+                                See https://github.com/rust-lang/rust/issues/76001.";
```
Comment (jonas-schievink) [inline compiler/rustc_typeck/src/check/pat.rs:779]: https://github.com/rust-lang/rust/issues/76001 does not look like it will ever support this. The RFC does not mention structural matches.

File: compiler/rustc_typeck/src/check/pat.rs [hunk 3]
```diff
@@ -772,6 +772,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         let msg = "introduce a new binding instead";
                         let sugg = format!("other_{}", ident.as_str().to_lowercase());
                         e.span_suggestion(ident.span, msg, sugg, Applicability::HasPlaceholders);
+                        match res {
+                            Res::Def(DefKind::Const, _) => {
```
Comment (jonas-schievink) [inline compiler/rustc_typeck/src/check/pat.rs:776]: This should ideally check for all range types whose syntax can be used in patterns and suggest something more specific. The user likely wanted to match on a range of values instead.

Comment (guswynn) [reply compiler/rustc_typeck/src/check/pat.rs:776]: ah thats a good idea. Is there an example that might show how to check something like that?

File: compiler/rustc_typeck/src/check/pat.rs (hunk 2 above)
Comment (guswynn) [reply compiler/rustc_typeck/src/check/pat.rs:779]: would https://github.com/rust-lang/rust/issues/74446 be better?

Comment (jonas-schievink) [reply compiler/rustc_typeck/src/check/pat.rs:779]: I don't think so. I don't think this is supposed to work.

File: compiler/rustc_typeck/src/check/pat.rs (hunk 3 above)
Comment (jonas-schievink) [reply compiler/rustc_typeck/src/check/pat.rs:776]: Not sure off the top of my head. You can probably get help on Zulip though.

File: compiler/rustc_typeck/src/check/pat.rs (hunk 2 above)
Comment (guswynn) [reply compiler/rustc_typeck/src/check/pat.rs:779]: Ok, ill ask in zulip and try to make it so the diagnostic checks if its a range type

File: compiler/rustc_typeck/src/check/pat.rs [hunk 4]
```diff
@@ -772,6 +773,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        };
+                        let ranges = &[
+                            self.tcx.lang_items().range_struct(),
+                            self.tcx.lang_items().range_from_struct(),
+                            self.tcx.lang_items().range_to_struct(),
+                            self.tcx.lang_items().range_full_struct(),
+                            self.tcx.lang_items().range_inclusive_struct(),
+                            self.tcx.lang_items().range_to_inclusive_struct(),
+                        ];
+                        if ranges.contains(&def_id_opt) {
```
Comment (jonas-schievink) [inline compiler/rustc_typeck/src/check/pat.rs:789]: This will search for a `None` lang item when `def_id_opt` is `None`, which is probably not right. The note should only be emitted when `pat_ty.kind` is `Adt`.

File: compiler/rustc_typeck/src/check/pat.rs [hunk 5]
```diff
@@ -772,6 +773,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            let msg = 
+                                "Constants only support matching the same type. \
+                                If you are using range syntax (i.e. ..= or similar) in your constant \
+                                you may want to move the range into the match block";
```
Comment (jonas-schievink) [inline compiler/rustc_typeck/src/check/pat.rs]: Maybe some better wording would be:

```suggestion
                                "if you meant to match against a range of values, consider using a range pattern like `min ..= max`";
```

...or something along those lines

File: compiler/rustc_typeck/src/check/pat.rs (hunk 4 above)
Comment (guswynn) [reply compiler/rustc_typeck/src/check/pat.rs:789]: my understanding is that the .lang_items().range_* above will never be none, but you are right, an explicit != None check would be good

File: src/test/ui/issues/issue-76191.stderr [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+LL |         RANGE => {}
+   |         ^^^^^
+   |         |
+   |         expected `i32`, found struct `std::ops::RangeInclusive`
+   |         `RANGE` is interpreted as a constant, not a new binding
+   |         help: introduce a new binding instead: `other_range`
+   |
+   = note: expected type `i32`
+            found struct `std::ops::RangeInclusive<i32>`
+   = note: Constants only support matching the same type. If you are using range syntax (i.e. ..= or similar) in your constant you may want to move the range into the match block
```
Comment (estebank) [inline src/test/ui/issues/issue-76191.stderr]: Ideally the output would look closer to the following:

```
error[E0308]: mismatched types
  --> $DIR/issue-76191.rs:10:9
   |
LL | const RANGE: RangeInclusive<i32> = 0..=255;
   | ------------------------------------------- constant defined here
...
LL |     match n {
   |           - this expression has type `i32`
LL |         RANGE => {}
   |         ^^^^^
   |         |
   |         expected `i32`, found struct `std::ops::RangeInclusive`
   |         `RANGE` is interpreted as a constant, not a new binding
   |
   = note: expected type `i32`
            found struct `std::ops::RangeInclusive<i32>`
   = note: constants only support matching the same type
help: you may want to move the range into the match block
   |
LL |         0..=255 => {}
   |         ^^^^^^^
```
The later suggestion might not be feasible (depending on whether you can get the `hir::Expr` corresponding to the `const`).

File: src/test/ui/issues/issue-76191.stderr [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+   | ------------------------------------------- constant defined here
+...
+LL |     match n {
+   |           - this expression has type `i32`
+LL |         RANGE => {}
+   |         ^^^^^
+   |         |
+   |         expected `i32`, found struct `std::ops::RangeInclusive`
+   |         `RANGE` is interpreted as a constant, not a new binding
+   |         help: introduce a new binding instead: `other_range`
```
Comment (estebank) [inline src/test/ui/issues/issue-76191.stderr:14]: This one suggestion shouldn't be displayed when we have identified for sure that this is a Range `const`.

File: src/test/ui/issues/issue-76191.stderr (hunk 6 above)
Comment (estebank) [inline src/test/ui/issues/issue-76191.stderr]: We don't use "proper" sentences, no leading uppercase letter and no period after the sentence.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_typeck/src/check/pat.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/pat.rs]: `.lang_items().range_*` might be `None` is special setups (I think `no_std` might be one of them).

File: src/test/ui/issues/issue-76191.stderr (hunk 6 above)
Comment (estebank) [reply src/test/ui/issues/issue-76191.stderr]: (This is not a blocker).

Comment (guswynn) [reply src/test/ui/issues/issue-76191.stderr]: Oh hmm, I can look into doing that, but would likely make that a separate pull request

**Comment by guswynn** [comment]
Updated to take into account @estebank's comments, as well as only emit this new error when its const as well as a range, as well as (try) to fix the fmt ci failure

**Review by estebank — APPROVED** [review]
Can you squash your commits? r=me after that.

File: compiler/rustc_typeck/src/check/pat.rs [hunk 8]
```diff
@@ -769,9 +770,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            self.tcx.lang_items().range_to_struct(),
+                            self.tcx.lang_items().range_full_struct(),
+                            self.tcx.lang_items().range_inclusive_struct(),
+                            self.tcx.lang_items().range_to_inclusive_struct(),
+                        ];
+                        if const_def_id != None && ranges.contains(&const_def_id) {
+                            let msg = "constants only support matching by type, \
+                            if you meant to match against a range of values, \
+                            consider using a range pattern like `min ..= max` in the match block";
+                            e.note(msg);
```
[the remark this answers is not in the document]
Comment (guswynn) [reply compiler/rustc_typeck/src/check/pat.rs:793]: Ill make a personal note to make a followup, as I'm still learning all this stuff its nice to do things 1 bit at a time

[the remark this answers is not in the document]
Comment (estebank) [reply compiler/rustc_typeck/src/check/pat.rs:793]: Sounds good to me

**Comment by guswynn** [comment]
bitten by: #76222, one sec!
