### PR TITLE
Search fixes

### LINKED ISSUE #45608: [rustdoc] Various issues with search tabs
I've come across several issues related to the search tabs:
* While on the search results screen, if you click on the "As parameters" or "As return value" tabs, then type in a query, the results shown are from the "Types/modules" tab.
* The "As parameters" and "As return value" tabs only show results that have the query string in its name or path. Even then it's missing results. For example, `std::thread::current` has signature `pub fn current() -> Thread`, yet doesn't show up in the "As return value" tab when searching for "Thread".
* When searching, functions whose name is the same as its return type are not shown on the "Types/modules" tab. (details in my second post)
* I think the first tab shouldn't be labeled "Types/modules", as it also shows functions and macros.

[Link to the recent pull request implementing the search tabs](https://github.com/rust-lang/rust/pull/45055)

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #45608.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -360,15 +368,68 @@
...
+                                .join("")
+                                .split(">")
+                                .slice(0, -1)
+                                .join("")
+                                .split(",");
+                for (var x = 0; x < values.length; ++x) {
+                    values[x] = values[x].trim();
+                }
+                return values;
+            }
```
Comment (kennytm) [inline src/librustdoc/html/static/main.js]: wat.

I would have used `indexOf`/`lastIndexOf` to extract the substring instead of the split.slice.join.split.slice.join

```js
function extractGenerics(val) {
    var values = val.substring(val.indexOf('<')+1, val.lastIndexOf('>'));
    return values.split(/\s*,\s*/);
}
```

File: src/librustdoc/html/static/main.js [hunk 2]
```diff
@@ -360,15 +368,68 @@
...
                     for (var i = 0; i < obj.type.inputs.length; i++) {
                         if (obj.type.inputs[i].name === val) {
-                            return true;
+                            // No need to check anything else: we found it. Let's just move on.
+                            return 0;
+                        }
+                        var name = obj.type.inputs[i].name.toLowerCase()
+                        var tmp_val = [name];
+                        if (name.indexOf('<') === -1 && isWrapper === true) {
+                            tmp_val = extractGenerics(name);
```
Comment (kennytm) [inline src/librustdoc/html/static/main.js]: Do you mean to use `name` here? The check above says `name` won't contain any `'<'`...

(If this is expected why not just write `tmp_valu = name.split(/\s*,\s*/)`...)

File: src/librustdoc/html/static/main.js [hunk 3]
```diff
@@ -360,15 +368,68 @@
...
+            function checkReturned(obj, val) {
+                var isWrapper = val.indexOf('<') !== -1;
+                var lev_distance = MAX_LEV_DISTANCE + 1;
+                if (obj && obj.type && obj.type.output) {
+                    if (obj.type.output.name.toLowerCase() === val) {
+                        return 0;
+                    }
+                    var tmp_val = [obj.type.output.name.toLowerCase()];
+                    if (obj.type.output.name.indexOf('<') === -1 && isWrapper === true) {
+                        tmp_val = extractGenerics(obj.type.output.name.toLowerCase());
```
Comment (kennytm) [inline src/librustdoc/html/static/main.js]: ditto

File: src/librustdoc/html/static/main.js [hunk 4]
```diff
@@ -16,6 +16,14 @@
 (function() {
     "use strict";
 
+    Object.nbElements = function(obj) {
```
Comment (killercup) [inline src/librustdoc/html/static/main.js]: Why do you define this on `Object` (of all things) and not just as a free function?

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: I preferred it as is but I can make a free function if you prefer.

Comment (killercup) [reply src/librustdoc/html/static/main.js]: Yeah, I don't think adding a static method for this on a core, well, `Object` is the way to go. This function probably shouldn't escape the scope of this file anyway.

File: src/librustdoc/html/static/main.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Way better, thanks!

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Or maybe not... Trying to understand what I was trying to do...

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: No I was right: it should have been `!== -1`!

File: src/librustdoc/html/static/main.js [hunk 5]
```diff
@@ -360,31 +360,69 @@
...
+                    if (obj.hasOwnProperty(key)) {
+                        size += 1;
+                    }
+                }
+                return size;
+            }
+
+            function extractGenerics(val) {
+                var values = val.substring(val.indexOf('<') + 1, val.lastIndexOf('>'));
+                return values.split(/\s*,\s*/);
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static/main.js]: Would it be prudent to also include the "base name" in this? It looks like this throws away the "Result" in `Result<File, Error>`. From how this is used it seems like it wouldn't be included in Levenstein comparisons because of that.

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (QuietMisdreavus) [reply src/librustdoc/html/static/main.js]: Wait a sec, this is ripping out the contents of the generics *if both the type and the search query contain them*? Am i reading this correctly? It seems like we should do that if `isWrapper === false` instead.

**Review by QuietMisdreavus — COMMENTED** [review]
I'm way shaky on everything that's going on in the last commit - it seems like the code that checks through generics should be thrown out since that needs to be in a separate PR anyway. (It's also unrelated to the linked issue.)

File: src/librustdoc/html/static/main.js (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: That's the point. :)

**Comment by GuillaumeGomez** [comment]
Removed the genericity part. I'll put it directly in #45673.

**Comment by QuietMisdreavus** [comment]
Thanks! This looks good to go now.

@bors r+
