### PR TITLE
Use correct edition when parsing `:pat` matchers

### LINKED ISSUE #84429: matches! problem with edition 2021
If I compile this:

```rust
fn main() {
    let _b = matches!(b'3', b'0' ..= b'9');
}
```

With:

```
rustc 1.53.0-nightly (b84932674 2021-04-21)
binary: rustc
commit-hash: b849326744a8eec939e592f0ab13bff85cc865d3
commit-date: 2021-04-21
host: x86_64-pc-windows-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

If I use the command:

```
...>rustc --edition 2018 -Z unstable-options test.rs
```

The compilation seems OK. If I compile with:

```
...>rustc --edition 2021 -Z unstable-options test.rs
```

rustc gives an error without line numbers:

```rust
error: `$pattern:pat` may be followed by `|`, which is not allowed for `pat` fragments
    |
    = note: allowed there are: `=>`, `,`, `=`, `if` or `in`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by Aaron1011**
As described in issue #85708, we currently do not properly decode
`SyntaxContext::root()` and `ExpnId::root()` from foreign crates. As a
result, when we decode a span from a foreign crate with
`SyntaxContext::root()`, we end up up considering it to have the edition
of the *current* crate, instead of the foreign crate where it was
originally created.

A full fix for this issue will be a fairly significant undertaking.
Fortunately, it's possible to implement a partial fix, which gives us
the correct edition-dependent behavior for `:pat` matchers when the
macro is loaded from another crate. Since we have the edition of the
macro's defining crate available, we can 'recover' from seeing a
`SyntaxContext::root()` and use the edition of the macro's defining
crate.

Any solution to issue #85708 must reproduce the behavior of this
targeted fix - properly preserving a foreign `SyntaxContext::root()`
means (among other things) preserving its edition, which by definition
is the edition of the foreign crate itself. Therefore, this fix moves us
closer to the correct overall solution, and does not expose any new
incorrect behavior to macros.

### CODE REVIEW

File: src/test/ui/macros/issue-84429-matches-edition.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// edition:2021
+// check-pass
+//
+// Regression test for issue #84429
+// Tests that we can properly invoke `masches!` from a 2021-edition crate.
```
Comment (m-ou-se) [inline src/test/ui/macros/issue-84429-matches-edition.rs:5]:
```suggestion
// Tests that we can properly invoke `matches!` from a 2021-edition crate.
```

**Comment by petrochenkov** [comment]
r=me with the typo (https://github.com/rust-lang/rust/pull/85709#discussion_r640640133) fixed.

**Comment by m-ou-se** [comment]
Thank you for fixing this, @Aaron1011!
