### PR TITLE
When a local binding shadows a fn, point at fn def in call failure

### LINKED ISSUE #53841: confusing diagnostic when variable name equals function name
`rustc 1.30.0-nightly (02cb8f2a4 2018-08-29)`
code:
````rust
struct VersionInfo {
    commit_hash: Option<String>,
}

impl VersionInfo {
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String>;

        if false {
            commit_hash = commit_hash();
        } else {
            commit_hash = Some(String::from("bla"));
        }

        VersionInfo {
            commit_hash,
        }
    }
}


fn commit_hash() -> Option<String> {
    Some("hi".to_string())
}
````

This causes a very confusing error message
````
error[E0618]: expected function, found enum variant `commit_hash`
  --> rustc_tools_util/src/lib.rs:11:27
   |
8  |         let commit_hash: Option<String>;
   |             ----------- `commit_hash` defined here
...
11 |             commit_hash = commit_hash();
   |                           ^^^^^^^^^^^^^ not a function
help: `commit_hash` is a unit variant, you need to write it without the parenthesis
   |
11 |             commit_hash = commit_hash;
   |                           ^^^^^^^^^^^
error: aborting due to previous error
````

First, the message talks about "enum variant", does it mean `struct variant`?
Second, I don't get why it does not compile anyway.
If I rename ````commit_hash()```` to ````get_commit_hash()```` it builds, but why can't it figure out that that a var and function are different things even if they have the same name?

Fun fact: 
this doesn't build either
````rust
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String>;
        commit_hash = commit_hash();

        VersionInfo {
            commit_hash,
        }
    }
````
but this does:
````rust
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String> = commit_hash();

        VersionInfo {
            commit_hash,
        }
    }
````

Shouldn't the 2 snippets behave identical?

### PR DESCRIPTION
**Pull request by estebank**
When a local binding shadows a function that is then called, this local binding will cause an E0618 error. We now point not only at the binding definition, but also at the locally defined function of the same name.

```
error[E0618]: expected function, found `&str`
  --> $DIR/issue-22468.rs:3:13
   |
LL |     let foo = "bar";
   |         --- `foo` has type `&str`
LL |     let x = foo("baz");
   |             ^^^-------
   |             |
   |             call expression requires function
...
LL | fn foo(file: &str) -> bool {
   | -------------------------- this function of the same name is available here, but it shadowed by the local binding of the same name
```

Fix #53841

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/callee.rs [hunk 1]
```diff
@@ -625,6 +625,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            let name = path.segments[0].ident.name;
+            for id in self.tcx.hir().items() {
+                if let Some(node) = self.tcx.hir().get_if_local(id.owner_id.into())
+                    && let hir::Node::Item(item) = node
+                    && let hir::ItemKind::Fn(..) = item.kind
+                    && item.ident.name == name
+                {
+                    err.span_label(
+                        self.tcx.def_span(id.owner_id),
+                        "this function of the same name is available here, but it shadowed by the \
```
Comment (fmease) [inline compiler/rustc_hir_typeck/src/callee.rs:641]:
```suggestion
                        "this function of the same name is available here, but it's shadowed by the \
```

**Review by fmease — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/callee.rs [hunk 2]
```diff
@@ -625,6 +625,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             );
         }
 
+        if let hir::ExprKind::Path(hir::QPath::Resolved(None, path)) = callee_expr.kind
+            && let Res::Local(_) = path.res
+            && path.segments.len() == 1
```
Comment (petrochenkov) [inline compiler/rustc_hir_typeck/src/callee.rs:630]:
```suggestion
            && let [seg] = &*path.segments
```

File: compiler/rustc_hir_typeck/src/callee.rs [hunk 3]
```diff
@@ -625,6 +625,26 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        {
+            let name = path.segments[0].ident.name;
+            for id in self.tcx.hir().items() {
+                if let Some(node) = self.tcx.hir().get_if_local(id.owner_id.into())
+                    && let hir::Node::Item(item) = node
+                    && let hir::ItemKind::Fn(..) = item.kind
+                    && item.ident.name == name
```
Comment (petrochenkov) [inline compiler/rustc_hir_typeck/src/callee.rs:637]:
```suggestion
                    && item.ident.name == seg.ident.name
```
Minor cleanup.

**Comment by petrochenkov** [comment]
r=me with cleanup.
@rustbot author
