### PR TITLE
Fix setting inline hint based on `InstanceDef::requires_inline`

### LINKED ISSUE #79108: `InstanceDef::requires_inline` does not result in an inline hint
The `InstanceDef::requires_inline` is described to return true if "this
instance is unconditionally marked with inline". In practice, the instance will
receive an inline hint if and only if the instance has any other user specified
inlining attributes.

For example, by default a closure will not receive an inline hint, but a
closure marked with `#[inline(never)]` counter-intuitively will (together with
`noinline`).

```rust
#![crate_type = "lib"]
#![feature(stmt_expr_attributes)]

pub fn f() {
    let a = || {};
    let b = #[inline(never)] || {};
    a();
    b();
}
```

```llvm
; a::f::{{closure}}
; Function Attrs: nonlazybind uwtable
define internal void @"_ZN1a1f28_$u7b$$u7b$closure$u7d$$u7d$17hefe1f433f470c2abE"(%"[closure@a.rs:5:13: 5:18]"* noalias nonnull readonly align 1 %_1) unnamed_addr #0 {
start:
  ret void
}

; a::f::{{closure}}
; Function Attrs: inlinehint noinline nonlazybind uwtable
define internal void @"_ZN1a1f28_$u7b$$u7b$closure$u7d$$u7d$17h7b2e25d54194ec9cE"(%"[closure@a.rs:6:30: 6:35]"* noalias nonnull readonly align 1 %_1) unnamed_addr #1 {
start:
  ret void
}
```

### PR DESCRIPTION
**Pull request by tmiasko**
For instances where `InstanceDef::requires_inline` is true, an attempt
is made to set an inline hint though a call to the `inline` function.
The attempt is ineffective, since all attributes will be usually removed
by the second call.

Fix the issue by applying the attributes only once, with user provided
attributes having a priority when provided.

Closes #79108.

### CODE REVIEW

**Comment by tmiasko** [comment]
The perf results look quite promising. This fixes a bug where inline hint was
intended to be set by default for some instances, but in fact wasn't. With a
fix, LLVM codegen takes longer, but the cost is recovered by rustc being
sligthly faster (-0.1% average instruction counts). The rutsc boostrap timings
looks are worse though with +1.7%.

**Comment by eddyb** [comment]
LGTM, cc @nagisa @wesleywiser @alexcrichton

File: src/test/codegen/inline-hint.rs [hunk 1]
```diff
@@ -0,0 +1,30 @@
+// Checks that closures, constructors, and shims except
+// for a drop glue receive inline hint by default.
+//
+// compile-flags: -Cno-prepopulate-passes -Zsymbol-mangling-version=v0
+// revisions: CLOSURE TUPLE CLONE DROP
```
Comment (nagisa) [inline src/test/codegen/inline-hint.rs:5]: Why are revisions used, when all of them are compiled with the same settings?

File: compiler/rustc_codegen_llvm/src/attributes.rs [hunk 2]
```diff
@@ -35,11 +35,8 @@ fn inline(cx: &CodegenCx<'ll, '_>, val: &'ll Value, inline: InlineAttr) {
                 Attribute::NoInline.apply_llfn(Function, val);
             }
         }
-        None => {
-            Attribute::InlineHint.unapply_llfn(Function, val);
-            Attribute::AlwaysInline.unapply_llfn(Function, val);
-            Attribute::NoInline.unapply_llfn(Function, val);
-        }
+        None if requires_inline => Attribute::InlineHint.apply_llfn(Function, val),
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/attributes.rs:38]: What's the intended behaviour here when `requires_inline == true` and `inline != None`?

Comment (nagisa) [reply compiler/rustc_codegen_llvm/src/attributes.rs:38]: If its not something that can happen, maybe `bug!()` it?

Comment (tmiasko) [reply compiler/rustc_codegen_llvm/src/attributes.rs:38]: Requires inline instances are mostly auto-generated. Closures are the exception, so it is possible but unlikely. As far as what should take priority, no idea what the intent was, if it was considered at all (although the order of calls would suggest respecting user provided attributes).

File: src/test/codegen/inline-hint.rs (hunk 1 above)
Comment (tmiasko) [reply src/test/codegen/inline-hint.rs:5]: To avoid checking the order in which those functions are emitted.

Comment (nagisa) [reply src/test/codegen/inline-hint.rs:5]: [`CHECK-DAG`](https://www.llvm.org/docs/CommandGuide/FileCheck.html#the-check-dag-directive) is a more natural approach here, I feel.

Comment (tmiasko) [reply src/test/codegen/inline-hint.rs]: I removed revisions and reordered the checks.
