### PR TITLE
Avoid zero-sized allocs in ThinBox if T and H are both ZSTs.

### LINKED ISSUE #96485: miri reports allocation of size 0 in in Thinbox::new()
I tried this code:

```rust
#![feature(thin_box)]

use std::boxed::ThinBox;
fn main() {
    let _thin_concrete_error: ThinBox<Foo> = ThinBox::new(Foo);
}

struct Foo;
```

`cargo miri run`
````
error: Undefined Behavior: creating allocation with size 0
  --> /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:89:14
   |
89 |     unsafe { __rust_alloc(layout.size(), layout.align()) }
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creating allocation with size 0
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

   = note: inside `std::alloc::alloc` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:89:14
   = note: inside `std::boxed::thin::WithHeader::<()>::new::<Foo>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed/thin.rs:159:23
   = note: inside `std::boxed::ThinBox::<Foo>::new` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed/thin.rs:52:19
note: inside `main` at src/main.rs:5:46
  --> src/main.rs:5:46
   |
5  |     let _thin_concrete_error: ThinBox<Foo> = ThinBox::new(Foo);
   |                                              ^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
````

Technically miri already shows that the code is `unsafe`-wrapped. Maybe it needs some special handing of `Thinbox`?

`miri 0.1.0 (a71a008 2022-04-25)`

### PR DESCRIPTION
**Pull request by thomcc**
This was surprisingly tricky, and took longer to get right than expected. `ThinBox` is a surprisingly subtle piece of code. That said, in the end, a lot of this was due to overthinking[^overthink] -- ultimately the fix ended up fairly clean and simple.

[^overthink]: Honestly, for a while I was convinced this couldn't be done without allocations or runtime branches in these cases, but that's obviously untrue.

Anyway, as a result of spending all that time debugging, I've extended the tests quite a bit, and also added more debug assertions. Many of these helped for subtle bugs I made in the middle (for example, the alloc/drop tracking is because I ended up double-dropping the value in the case where both were ZSTs), they're arguably a bit of overkill at this point, although I imagine they could help in the future too.

Anyway, these tests cover a wide range of size/align cases, nd fully pass under miri[^1]. They also do some smoke-check asserting that the value has the correct alignment, although in practice it's totally within the compiler's rights to delete these assertions since we'd have already done UB if they get hit. They have more boilerplate than they really need, but it's not *too* bad on a per-test basis.

A notable absence from testing is atypical header types, but at the moment it's impossible to manually implement `Pointee`. It would be really nice to have testing here, since it's not 100% obvious to me that the aligned read/write we use for `H` are correct in the face of arbitrary combinations of `size_of::<H>()`, `align_of::<H>()`, and `align_of::<T>()`. (That said, I spent a while thinking through it and am *pretty* sure it's fine -- I'd just feel... better if we could test some cases for non-ZST headers which have unequal and align).

[^1]: Or at least, they pass under miri if I copy the code and tests into a new crate and run miri on it (after making it less stdlibified).

Fixes #96485.

I'd request review @yaahc, but I believe you're taking some time away from reviews, so I'll request from the previous PR's reviewer (I think that the context helps, even if the actual change didn't end up being bad here).

r? @joshtriplett

### CODE REVIEW

**Comment by thomcc** [comment]
This doesn't touch the public API in any way (aside from fixing the unsoundness in `ThinBox<()>`).

**Comment by thomcc** [comment]
To explain why I *think* that the previous (and current) code is sound despite using aligned read/write for `H` (and also sort of why I think it's not trivial, or at least is not to me), my reasoning is something like this:

If we consider allocation as returning `(base: *mut u8, offset: usize)`, where offset is the second value returned by `Layout::extend`, and `base` is the poiner returned from the allocator. (Note: error handling is ignored below, as is the case where both T and H are ZSTs, although I don't believe it needs special handling here). Then:

1. `base` is a pointer aligned to `max(align(H), align(T))`.
2. `offset` is `(size(H) + (align(T) - 1)) & (align(T) - 1))`. Or, equivalently, it's the result of rounding `size(H)` up to `align(T)`.
3. `base + offset` produces the value pointer (which I'll call `val_ptr`), which is guaranteed to be aligned to `align(T)`, as it's the result of adding `offset` (which is a multiple of `align(T)`) to `base` (which is aligned to `T`).
4. Then, `val_ptr - size(H)` is the pointer to the header (which I'll call `hdr_ptr`).

As it is, the code relies on `hdr_ptr` being aligned to `align(H)`. I... think this is guaranteed? Since it's all powers of 2. But it's tricky. And so I added that debug_assert in `WithHeader::header`, and would eventually like tests for that case.

Anyway, I mostly wanted to write this down, so that I could (possibly) find it in the future. It's essentially unrelated to this patch (beyond, erm, the fact that I broke it in the middle of writing this patch, but fixed it by the end)

**Comment by yaahc** [comment]
I'm down to review code I'm familiar with still! Just taking a break from the rotation, not reviews in general.

File: library/alloc/src/boxed/thin.rs [hunk 1]
```diff
@@ -198,7 +223,9 @@ impl<H> WithHeader<H> {
         //    needed to align the header. Subtracting the header size from the aligned data pointer
         //    will always result in an aligned header pointer, it just may not point to the
         //    beginning of the allocation.
-        unsafe { self.0.as_ptr().sub(Self::header_size()) as *mut H }
+        let hp = unsafe { self.0.as_ptr().sub(Self::header_size()) as *mut H };
+        debug_assert!((hp.addr() & (core::mem::align_of::<H>() - 1)) == 0);
+        hp
```
Comment (yaahc) [inline library/alloc/src/boxed/thin.rs:228]: What is this checking?

Comment (thomcc) [reply library/alloc/src/boxed/thin.rs:228]: That `hp.addr()` is properly aligned.

Comment (oli-obk) [reply library/alloc/src/boxed/thin.rs:228]: If https://github.com/rust-lang/rust/pull/95643 gets accepted this will be able to use `is_aligned`

Comment (thomcc) [reply library/alloc/src/boxed/thin.rs:228]: That’d be great, I’ve wanted that for a long time.

Comment (thomcc) [reply library/alloc/src/boxed/thin.rs]: It uses that API now.

**Comment by thomcc** [comment]
I guess bors was sleeping.

@bors r=yaac
