### PR TITLE
Integer parsing should accept leading plus

### LINKED ISSUE #27580: Leading plus for string to integer parsing
The ```parse::<i32>()``` function (and all its cousins for other integer types) fail for strings starting with a ```+``` with ```ParseIntError { kind: InvalidDigit }```. Failing snippet:

```
fn main () {
  assert_eq!("+42".parse::<i32>().unwrap(), 42);
}
```

The same error occurs with the symmetric function call ```i32::from_str("+42")```.

[Test snippet on Rust Playground](http://is.gd/MS2sYy)
[Rust Forum discussion](https://users.rust-lang.org/t/leading-plus-sign-on-integers/2320/7)

### PR DESCRIPTION
**Pull request by arthurprs**
Closes #27580

### CODE REVIEW

**Comment by rkruppe** [comment]
I also had a patch for this and was only waiting for the local `make check` to pass. But mine made the minimal necessary changes and this is probably better, more coherent code, so no harm done.

File: src/libcore/num/mod.rs [hunk 1]
```diff
@@ -1387,50 +1387,49 @@ fn from_str_radix<T: FromStrRadixHelper>(src: &str, radix: u32)
...
-                };
-            }
-            Ok(result)
-        },
-        (c, digits) => {
-            // The number is signed
-            let mut result = match (c as char).to_digit(radix) {
-                Some(x) => T::from_u32(x),
+    let (is_positive, digits) = match src[0] {
+        b'+' if src.len() == 1 => return Err(PIE { kind: Empty }),
```
Comment (rkruppe) [inline src/libcore/num/mod.rs]: My personal preference would be to not check for empty inputs in the match. Instead I'd slice unconditionally and check `if digits.is_empty()` afterwards. Seems slightly simpler and shorter.

Comment (arthurprs) [inline src/libcore/num/mod.rs]: Great suggestion, I constantly abuse pattern matching...

**Comment by alexcrichton** [comment]
Thanks @arthurprs! This implementation looks fine to me, but it's a bit of a significant change to a core function in the standard library, so I'm going to tag this with `T-libs` to bring up for some broader discussion.

**Comment by alexcrichton** [comment]
cc @rust-lang/libs

**Comment by Gankro** [comment]
:+1: this seems good

**Comment by rkruppe** [comment]
Oh my! I just realized that my float parsing require in #27307 made the analogous change for floats. Compare the output of [this code](https://play.rust-lang.org/?gist=db4e56e7031b56a9168d) on stable (1.3, prior to merging my PR) and nightly. I didn't even realize at the time that this was a change of behavior (even though I encountered and worked around the integer version of it), and neither did any of the reviewers &mdash; or if they noticed, they didn't mind.

**Comment by BurntSushi** [comment]
Are there any downsides to permitting `+`?

**Comment by alexcrichton** [comment]
Nah it seems fine to me, just something to consider and make an explicit decision about! Although given the change @rkruppe mentioned it may already be decided :)

**Comment by alexcrichton** [comment]
This libs team discussed this yesterday and the conclusion was to merge. This fits a well accepted precedent from other languages and custom parsing of other formats typically have their own parser anyway so it's unlikely that changes here will affect that form of robust parsers.

Thanks for the PR @arthurprs!

@bors: r+ 123a83326fb95366e94a3be1a74775df4db97739

**Comment by aturon** [comment]
I'm adding to relnotes, and we should advertise this change widely when it lands since it's a visible behavioral change.

**Comment by alexcrichton** [comment]
Oh right, excellent idea!
