### PR TITLE
Workaround for memory unsafety in third party DLLs

### LINKED ISSUE #143078: remove_dir_all implementation on Windows is incompatible with some third-party hooks for NtOpenFile, leading to Firefox crashes
Third-party software can inject a DLL into `firefox.exe` that detours calls to `NtOpenFile` to monitor the use of this system call. Some of these third-party DLLs can assume that in any `NtOpenFile` call, `ObjectAttributes->ObjectName.Buffer` is a valid pointer to dereference, and more generally that it is a null-terminated wide string. They do not check `ObjectAttributes->ObjectName.Length` nor `ObjectAttributes->ObjectName.MaxLength`. Rust's implementation of `remove_dir_all` on Windows makes direct calls to `NtOpenFile` that violate this third-party assumption, resulting in Firefox crashes in [Bug 1973947](https://bugzilla.mozilla.org/show_bug.cgi?id=1973947).

While one could argue that this is an incorrect assumption to have in the first place, it turns out that this assumption does not usually lead to crashes. This is because the assumption seems valid for the `UNICODE_STRING` values that usually flow into `NtOpenFile`, for example through win32 API calls, because these calls happen to always provide null-terminated wide strings in `Buffer`. For example they may rely on `RtlInitUnicodeString` to wrap null-terminated wide strings as `UNICODE_STRING` values. `RtlInitUnicodeString(&unicode_string, wide_string)` will typically set `unicode_string.Buffer` to `wide_string`, `unicode_string.Length` to `wcslen(wide_string)` and `unicode_string.MaxLength` to `wcslen(wide_string) + 2` (accounting for the null wide char).

Rust's implementation of `remove_dir_all` appears to be the only violation for this assumption when `firefox.exe` runs. Would it be possible to enforce this assumption, to mimic the way usual calls to `NtOpenFile` behave, thereby preventing these crashes? In particular, the code below generates a `UNICODE_STRING` where `Length` is `0`, `MaxLength` is `0` and `Buffer` is `2`:

```rust
pub fn remove_dir_all_iterative(dir: File) -> Result<(), WinError> {
  // ...
  retry(|| delete(&dir, &[]), WinError::DIR_NOT_EMPTY)?;
  // ...
}
```

This can be reproduced in a standalone binary. The code below prints `0 0 2`:

```rust
type PWSTR = *mut u16;

#[repr(C)]
#[derive(Clone, Copy)]
struct UNICODE_STRING {
    pub Length: u16,
    pub MaximumLength: u16,
    pub Buffer: PWSTR,
}

impl UNICODE_STRING {
    pub fn from_ref(slice: &[u16]) -> Self {
        let len = size_of_val(slice);
        Self { Length: len as _, MaximumLength: len as _, Buffer: slice.as_ptr() as _ }
    }
}

fn main() {
    let str = UNICODE_STRING::from_ref(&[]);
    println!("{} {} {}", str.Length, str.MaximumLength, str.Buffer as u64);
}
```

This explains why the Firefox crashes we receive are caused by derefencing `2` as a pointer.

### PR DESCRIPTION
**Pull request by ChrisDenton**
Resolves rust-lang/rust#143078

Note that we can't make any guarantees if third parties intercept OS functions and don't implement them according to the documentation. However, I think it's practical to attempt mitigations when issues are encountered in the wild and the mitigation itself isn't too invasive.

### CODE REVIEW

File: library/std/src/sys/fs/windows/remove_dir_all.rs [hunk 1]
```diff
@@ -171,14 +171,49 @@ fn retry<T: PartialEq>(
...
 pub fn remove_dir_all_iterative(dir: File) -> Result<(), WinError> {
     let mut buffer = DirBuff::new();
     let mut dirlist = vec![dir];
+    let mut string_buffer = UnicodeStringNZ::new();
 
     let mut restart = true;
     'outer: while let Some(dir) = dirlist.pop() {
         let more_data = dir.fill_dir_buff(&mut buffer, restart)?;
         for (name, is_directory) in buffer.iter() {
+            let name = string_buffer.set(&name);
```
Comment (ChrisDenton) [inline library/std/src/sys/fs/windows/remove_dir_all.rs]: We could be smarter here and check if a null already exists after the name in the `DirBuff` buffer (which is likely) or even add a null in-place if not. But I'm not sure that's worth it.

Comment (ChrisDenton) [reply library/std/src/sys/fs/windows/remove_dir_all.rs]: To expand on that a bit, this PR is quite likely overkill for the specific issue linked. I think it would be enough to just make sure the empty string case is null-terminated since the other paths come from the OS APIs, which I'd assume are at least internally consistent. However, copying into a buffer is more robust in  case that assumption ever proves false.

**Comment by RalfJung** [comment]
> and the mitigation itself isn't too invasive.

Won't this cause extra copies and thus potentially hurt performance?

**Comment by ChrisDenton** [comment]
Potentially, I guess. Though I'd expect filesystem APIs are almost certainly going to be much slower than a memcpy.

As I mentioned in a comment, the fastest alternative would be to just ensure the empty string is null terminated. The assumption being that, however they're impersonating system APIs, they're at least being internally consistent.

**Comment by workingjubilee** [comment]
Shipping a workaround upstream for unsound software means that we are expecting all Rust programmers, not just Firefox, to pay for carrying the weight of unsound ecosystem software that they are not expected to interoperate with. Even if it's just a few bytes of code size we wouldn't need to pay otherwise, I don't think it makes sense.

**Comment by workingjubilee** [comment]
You cited us as shipping workarounds before, but the ones I remember were for *Microsoft* software. Where, yes, we may have done whatever the *owners* of the platform expected us to do, no matter how inane it may have seemed, because it doesn't matter if whatever is objectively incorrect if the local monarch will hang you(r process) for defiance.

**Comment by ChrisDenton** [comment]
The one I'm thinking of was for alignment issues with a [third party sandbox](https://github.com/sandboxie-plus/Sandboxie/issues/2443). This issue was fixed but we do still have the workaround under the assumption that other software may not do alignment properly. I guess it could be removed now but it also might break something.

**Comment by workingjubilee** [comment]
Ah.

Yes, open source software that we can see whether it is patched or not still seems like a much different story.

**Comment by the8472** [comment]
Can we set a deadline and make it public?

File: library/std/src/sys/fs/windows/remove_dir_all.rs (hunk 1 above)
Comment (ChrisDenton) [reply library/std/src/sys/fs/windows/remove_dir_all.rs]: Given the strength of feel here, I've gone with the simpler implementation.

**Comment by ChrisDenton** [comment]
Ok, I've changed it so that the impact will be minimal. The updated PR just tries to ensure null termination for our own strings and leave it up to the OS to use null termination for strings it owns (where "the OS" in this case includes people emulating OS APIs).

File: library/std/src/sys/pal/windows/api.rs [hunk 2]
```diff
@@ -291,3 +292,49 @@ impl WinError {
     pub const TIMEOUT: Self = Self::new(c::ERROR_TIMEOUT);
     // tidy-alphabetical-end
 }
+
+/// A wrapper around a UNICODE_STRING that is equivalent to `&[u16]`.
+///
+/// It is preferable to use `from_slice_with_nul` for our own strings as a
+/// mitigation for #143078.
+#[derive(Copy, Clone)]
+pub struct UnicodeStrRef<'a> {
```
Comment (tgross35) [inline library/std/src/sys/pal/windows/api.rs:304]: Could you mention in the docs something about this optionally being nul-terminated but that not being a guarantee? To help explain why the functions aren't `unsafe`.

**Comment by workingjubilee** [comment]
This seems more tolerable. I have sometimes wondered if maybe `core::ffi` should export a `static BIG_ZERO: u128 = 0;`, as pointers to it could reuse it as a sentinel.

File: library/std/src/sys/fs/windows/remove_dir_all.rs [hunk 3]
```diff
@@ -90,9 +90,9 @@ fn open_link_no_reparse(
     static ATTRIBUTES: Atomic<u32> = AtomicU32::new(c::OBJ_DONT_REPARSE);
 
     let result = unsafe {
-        let mut path_str = c::UNICODE_STRING::from_ref(path);
+        let path_str = UnicodeStrRef::from_slice(path);
         let mut object = c::OBJECT_ATTRIBUTES {
-            ObjectName: &mut path_str,
+            ObjectName: path_str.as_ptr(),
```
Comment (tgross35) [inline library/std/src/sys/fs/windows/remove_dir_all.rs]: If I am understanding things correctly, this change only ensures nul-termination if `path` is empty but otherwise passes `path` unchanged? What is the benefit here?

Comment (ChrisDenton) [reply library/std/src/sys/fs/windows/remove_dir_all.rs]: In the non-empty case the path is always given to us by the OS via directory iteration. So that falls under assuming OS returned strings are OK to use.

Comment (tgross35) [reply library/std/src/sys/fs/windows/remove_dir_all.rs]: Shouldn't it use `from_slice_with_nul` then? Or something like `from_slice_with_nul_if_nonempty` that still redirects the empty slice nul pointer but makes it clear that `\0` is otherwise expected.

Comment (ChrisDenton) [reply library/std/src/sys/fs/windows/remove_dir_all.rs]: Ah I see what you mean. The slice itself doesn't contain the nul (if any). There may or may not be a nul one beyond the end of the slice but we don't know. The point is we just assume there is if some third party is hooking OS functions and requires strings be null-terminated but otherwise we assume nothing outside of the slice.

We can't really do better than that without being more invasive. The APIs themselves say nothing about null termination.

**Comment by tgross35** [comment]
I'm thinking maybe we should leave https://github.com/rust-lang/rust/issues/143078 open once this merges, or make a new issue for eventually stripping this out. The software that will be relying on this seems objectively incorrect, and we have no way of knowing what calls actually need this; or really noticing if the `UnicodeStrRef` API here winds up used incorrectly (since nul termination isn't an invariant).

I'm on board with @the8472's suggestion that we should document in that issue that we will be reverting this PR in ~6 months or so, so we don't wind up carrying a workaround forever.

**Comment by ChrisDenton** [comment]
Based on the feedback I decided to simplify this down to a single `unicode_str!` macro so people don't have to think about what to use where. When creating a `UNICODE_STRING` just use the macro. It will null-terminate if given a literal `&str`. If given a `&[u16]` it will simply use it as-is, which is the best we can do without allocating.

I think this will make it easy for people to do the right thing by default.

**Review by tgross35 — APPROVED** [review]
r=me with try passing

@bors2 try jobs=`x86_64*msvc*`

**Comment by tgross35** [comment]
@bors2 try jobs=x86_64-msvc*
