### PR TITLE
tidy: Better license checks.

### LINKED ISSUE #62618: Dependency check of the tidy tool should verify the license
Currently, in the dependency-check of the tidy tool, dependencies having an incompatible license are white-listed, and the actual license is documented in a comment. 

Instead, the actual license should be documented in code, and the tool should check that the license is actually correct. When updating dependencies, the license might silently change into an incompatible one, and right now we don't detect this.

### LINKED ISSUE #62619: Dependency check of the tidy tool should verify libstd dependencies
There is a documentation comment explicitly saying that it is **crucial** for libcore,liballoc,libstd not to depend on any crate with incompatible licenses, yet a couple of lines after there is an exemption that does precisely this: https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs#L25

AFAICT, this property of the runtime is not verified by the tidy script, but should.

### LINKED ISSUE #63238: deps.rs EXCEPTIONS needs to be re-triaged
The [EXCEPTIONS](https://github.com/rust-lang/rust/blob/d7270712cb446aad0817040bbca73a8d024f67b0/src/tools/tidy/src/deps.rs#L27) list lists license exceptions.

After reviewing a few of them, they seem to be out of date, and some that were copyleft are now permissive, and some have the proper license.

The purpose of this list is primarily to _prevent non-permissively-licensed code_ from entering the Rust codebase, particularly the runtime. Permissively licensed code here effectively means "MIT or weaker", though as structured currently it actually makes anything without an MIT license an exception (BSD licenses are considered exceptions). This is fine and simplifies std's license (it's all MIT and most can be Apache, with the unfortunate exception of libbacktrace, which is BSD-3-Clause, and not represented in the exception list, potentially because of https://github.com/rust-lang/backtrace-rs/issues/234).

They should all be re-triaged, and re-commented or removed from the exception list as appropriate. Here are some examples from a quick look:

- thread-id - now Apache-2.0/MIT, was Apache-2.0, no longer an exception
- ryu - now Apache-2.0/BSL-1.0 (nice decision @dtolnay w/ the permissive license + runtime exception). Still an exception per the rules in this file because it doesn't carry MIT. Aside: Apache-2.0/MIT/BSL-1.0 would be a good relicense for Rust. I'd prefer ryu be tri-licensed with MIT just for uniformity with the rest of the Rust MIT-licensed ecosystem.
- utf8parse - Apache-2.0/MIT, not an exception
- vte - Apache-2.0/MIT, not an exception

### PR DESCRIPTION
**Pull request by ehuss**
This implements some improvements to the license checks in tidy:

* Use `cargo_metadata` instead of parsing vendored crates. This allows license checks to run without vendoring enabled, and allows the checks to run on PR builds.
* Check for stale entries.
* Check that the licenses for exceptions are what we think they are.
* Verify exceptions do not leak into the runtime.

Closes #62618
Closes #62619
Closes #63238 (I think)

There are some substantive changes here. The follow licenses have changed from the original comments:

* openssl BSD+advertising clause to Apache-2.0
* pest MPL2 to MIT/Apache-2.0
* smallvec MPL2 to MIT/Apache-2.0
* clippy lints MPL2 to MIT OR Apache-2.0

### CODE REVIEW

**Comment by ehuss** [comment]
cc @brson @gnzlbg FYI

File: src/tools/tidy/src/deps.rs [hunk 1]
```diff
@@ -25,404 +23,428 @@ const LICENSES: &[&str] = &[
...
+    ("fortanix-sgx-abi", "MPL-2.0"), // libstd but only for `sgx` target
+    ("dunce", "CC0-1.0"),            // mdbook-linkcheck
+    ("codespan-reporting", "Apache-2.0"), // mdbook-linkcheck
+    ("codespan", "Apache-2.0"),      // mdbook-linkcheck
+    ("crossbeam-channel", "MIT/Apache-2.0 AND BSD-2-Clause"), // cargo
 ];
 
+/// These are the root crates that are part of the runtime. The licenses for
+/// these and all their dependencies *must not* be in the exception list.
+const RUNTIME_CRATES: &[&str] = &["std", "core", "alloc", "panic_abort", "panic_unwind"];
```
Comment (ehuss) [inline src/tools/tidy/src/deps.rs]: I am assuming `libtest` is not really considered the "runtime" in the same vein as `std` is, but I can add it if people think it should.  It adds a number of dependencies, but they are all permissively licensed.

File: src/tools/tidy/src/deps.rs [hunk 2]
```diff
@@ -25,404 +23,428 @@ const LICENSES: &[&str] = &[
...
+        return;
+    }
+    let node = resolve
+        .nodes
+        .iter()
+        .find(|n| &n.id == pkg_id)
+        .unwrap_or_else(|| panic!("could not find `{}` in resolve", pkg_id));
+    // Don't care about dev-dependencies.
+    // Build dependencies *shouldn't* matter unless they do some kind of
+    // codegen. For now we'll assume they don't.
```
Comment (ehuss) [inline src/tools/tidy/src/deps.rs]: I could change this to include build deps if people think it should.  That is, should we have restrict build deps of `libstd` in case they inject code into the resulting crate?

File: src/tools/tidy/src/deps.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/tools/tidy/src/deps.rs]: I think this should include libtest, particularly as it might be linked in for e.g. black_box even in non-test executables.

File: src/tools/tidy/src/deps.rs [hunk 3]
```diff
@@ -25,404 +23,428 @@ const LICENSES: &[&str] = &[
...
+    "vcpkg",
+    "version_check",
+    "wasi",
+    "winapi",
+    "winapi-build",
+    "winapi-i686-pc-windows-gnu",
+    "winapi-util",
+    "winapi-x86_64-pc-windows-gnu",
+    "wincolor",
+    "hermit-abi",
```
Comment (Mark-Simulacrum) [inline src/tools/tidy/src/deps.rs]: Since we're changing the whole list anyway, mind sorting it while we're at it?

File: src/tools/tidy/src/deps.rs [hunk 4]
```diff
@@ -25,404 +23,428 @@ const LICENSES: &[&str] = &[
...
+            );
+            *bad = true;
+        }
+        // Check that the license hasn't changed.
+        for pkg in metadata.packages.iter().filter(|p| p.name == *name) {
+            if pkg.name == "fuchsia-cprng" {
+                // This package doesn't declare a license expression. Manual
+                // inspection of the license file is necessary, which appears
+                // to be BSD-3-Clause.
+                assert!(pkg.license.is_none());
```
Comment (Mark-Simulacrum) [inline src/tools/tidy/src/deps.rs]: cc @cramertj (?) -- could we get this populated perhaps?

File: src/tools/tidy/src/deps.rs (hunk 1 above)
Comment (ehuss) [reply src/tools/tidy/src/deps.rs]: Sure.  It can always be revisited if someone wants to add an exception, it's probably better to be safer here.  (although black_box is in core now, right?)

Just FYI for anyone curious, `test` adds the following dependencies:

- getopts
- proc_macro
- rustc-std-workspace-std
- term
- test
- unicode-width

**Comment by nikomatsakis** [comment]
cc @skade

**Comment by Mark-Simulacrum** [comment]
I'm going to r? @skade here since they've been involved with license work

File: src/tools/tidy/src/deps.rs (hunk 1 above)
Comment (skade) [reply src/tools/tidy/src/deps.rs]: I would add test as a runtime crate just to be on the conservative side. test will still be linked at runtime, (while procmacro etc. won't). Even if it is just in the test binary, it might still be confusing that the Rust compiler produces binaries with different license checking guarantees.

**Comment by skade** [comment]
r+

I'm okay with this, with the comment that I posted above: https://github.com/rust-lang/rust/pull/69443#discussion_r391416623. This probably merits its own ticket and shouldn't be discussed in a comment section, it's rather unclear what the story there should be. Is test part of the runtime or not?

**Comment by Mark-Simulacrum** [comment]
@bors r=skade,Mark-Simulacrum

I've done my best to also check the implementation, and it looks correct to me.

**Comment by ehuss** [comment]
@bors r=skade,Mark-Simulacrum
Some tests were broken since this was opened (removed chalk-engine and chalk-macros from exception list, removed in #69247).
