### PR TITLE
resolve: prohibit anon const non-static lifetimes

### LINKED ISSUE #73375: ICE: cannot convert to a region vid
### Code

```Rust
fn bug<'a>() {
    [(); (|_: &'a u8| (), 0).1];
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
rustc 1.45.0-beta.3359 (b7dc83a3f 2020-06-03)
rustc 1.46.0-nightly (4fb54ed48 2020-06-14)
```

### Error output

```
error: internal compiler error: src/librustc_mir/borrow_check/universal_regions.rs:750: cannot convert `ReFree(DefId(0:3 ~ playground[5d24]::bug[0]), BrNamed(DefId(0:4 ~ playground[5d24]::bug[0]::'a[0]), 'a))` to a region vid
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:904:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::bug_fmt
  20: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid::{{closure}}
  21: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid
  22: <rustc_mir::borrow_check::type_check::relate_tys::NllTypeRelatingDelegate as rustc_infer::infer::nll_relate::TypeRelatingDelegate>::push_outlives
  23: <rustc_infer::infer::nll_relate::TypeRelating<D> as rustc_middle::ty::relate::TypeRelation>::regions
  24: rustc_middle::ty::relate::super_relate_tys
  25: rustc_infer::infer::combine::<impl rustc_infer::infer::InferCtxt>::super_combine_tys
  26: <rustc_infer::infer::nll_relate::TypeRelating<D> as rustc_middle::ty::relate::TypeRelation>::tys
  27: rustc_mir::borrow_check::type_check::relate_tys::relate_types
  28: rustc_mir::borrow_check::type_check::input_output::<impl rustc_mir::borrow_check::type_check::TypeChecker>::equate_normalized_input_or_output
  29: rustc_mir::borrow_check::type_check::type_check
  30: rustc_mir::borrow_check::nll::compute_regions
  31: rustc_mir::borrow_check::do_mir_borrowck
  32: rustc_middle::ty::context::GlobalCtxt::enter_local
  33: rustc_mir::borrow_check::mir_borrowck
  34: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  35: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  36: rustc_query_system::query::plumbing::get_query
  37: rustc_mir::borrow_check::type_check::TypeChecker::check_rvalue
  38: rustc_mir::borrow_check::type_check::TypeChecker::typeck_mir
  39: rustc_mir::borrow_check::type_check::type_check
  40: rustc_mir::borrow_check::nll::compute_regions
  41: rustc_mir::borrow_check::do_mir_borrowck
  42: rustc_middle::ty::context::GlobalCtxt::enter_local
  43: rustc_mir::borrow_check::mir_borrowck
  44: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  46: rustc_query_system::query::plumbing::get_query
  47: rustc_query_system::query::plumbing::ensure_query
  48: rustc_mir::transform::optimized_mir
  49: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  51: rustc_query_system::query::plumbing::get_query
  52: rustc_mir::interpret::eval_context::InterpCx<M>::load_mir
  53: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  54: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_raw>::compute
  55: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  56: rustc_query_system::query::plumbing::get_query
  57: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  58: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  59: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  60: rustc_query_system::query::plumbing::get_query
  61: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  62: rustc_infer::infer::InferCtxt::const_eval_resolve
  63: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  64: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  65: rustc_typeck::check::FnCtxt::resolve_vars_with_obligations
  66: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  67: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  68: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  69: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  70: rustc_typeck::check::FnCtxt::check_stmt
  71: rustc_typeck::check::FnCtxt::check_block_with_expected
  72: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  73: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  74: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  75: rustc_typeck::check::check_fn
  76: rustc_infer::infer::InferCtxtBuilder::enter
  77: rustc_typeck::check::typeck_tables_of
  78: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_tables_of>::compute
  79: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  80: rustc_query_system::query::plumbing::get_query
  81: rustc_query_system::query::plumbing::ensure_query
  82: rustc_typeck::check::typeck_item_bodies
  83: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  84: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  85: rustc_query_system::query::plumbing::get_query
  86: rustc_typeck::check_crate
  87: rustc_interface::passes::analysis
  88: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  89: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  90: rustc_query_system::query::plumbing::get_query
  91: rustc_middle::ty::context::tls::enter_global
  92: rustc_interface::interface::run_compiler_in_existing_thread_pool
  93: scoped_tls::ScopedKey<T>::set
  94: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0 (49cae5576 2020-06-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `bug::{{constant}}#0::{{closure}}#0`
#1 [mir_borrowck] borrow-checking `bug::{{constant}}#0`
#2 [optimized_mir] processing `bug::{{constant}}#0`
#3 [const_eval_raw] const-evaluating `bug::{{constant}}#0`
#4 [const_eval_validated] const-evaluating + checking `bug::{{constant}}#0`
#5 [typeck_tables_of] type-checking `bug`
#6 [typeck_item_bodies] type-checking all item bodies
#7 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `playground`.
```

</p>
</details>

### LINKED ISSUE #74447: const generics lifetime ICE
```rust
#![feature(const_generics)]

fn test<const N: usize>() {}

fn wow<'a>() {
    test::<{
        let _: &'a ();
        3
    }>();
}
```
results in 
```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

error: internal compiler error: src/librustc_mir/borrow_check/universal_regions.rs:768:36: cannot convert `ReFree(DefId(0:5 ~ playground[38a3]::wow[0]), BrNamed(DefId(0:6 ~ playground[38a3]::wow[0]::'a[0]), 'a))` to a region vid

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:916:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.46.0-nightly (5c9e5df3a 2020-07-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error; 1 warning emitted
```

### LINKED ISSUE #75323: `min_const_generic` ICE w/ const-argument-non-static-lifetime
### Code

```Rust
#![feature(min_const_generics)]

fn test<const N: usize>() {}

fn wow<'a>() -> &'a () {
    test::<
        {
            let _: &'a ();
            3
        },
    >();
    &()
}
```

### Meta
Nightly on playground
```
   Compiling playground v0.0.1 (/playground)
error[E0658]: const generics are unstable
 --> src/lib.rs:3:15
  |
3 | fn test<const N: usize>() {}
  |               ^
  |
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information
  = help: add `#![feature(const_generics)]` to the crate attributes to enable

error: internal compiler error: src/librustc_mir/borrow_check/universal_regions.rs:768:36: cannot convert `ReEarlyBound(0, 'a)` to a region vid

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (09f4c9f50 2020-08-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/sys_common/backtrace.rs:58
   4: core::fmt::write
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/core/src/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/io/mod.rs:1510
   6: std::sys_common::backtrace::_print
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/sys_common/backtrace.rs:61
   7: std::sys_common::backtrace::print
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/sys_common/backtrace.rs:48
   8: std::panicking::default_hook::{{closure}}
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/panicking.rs:198
   9: std::panicking::default_hook
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/panicking.rs:217
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at /rustc/09f4c9f5082f78b0adcee83d3ab4337e000cd28e/library/std/src/panicking.rs:530
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::bug_fmt
  20: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid::{{closure}}
  21: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid
  22: <rustc_mir::borrow_check::type_check::relate_tys::NllTypeRelatingDelegate as rustc_infer::infer::nll_relate::TypeRelatingDelegate>::push_outlives
  23: <rustc_infer::infer::nll_relate::TypeRelating<D> as rustc_middle::ty::relate::TypeRelation>::regions
  24: rustc_middle::ty::relate::super_relate_tys
  25: rustc_infer::infer::combine::<impl rustc_infer::infer::InferCtxt>::super_combine_tys
  26: rustc_middle::ty::relate::TypeRelation::relate
  27: rustc_mir::borrow_check::type_check::TypeChecker::relate_types
  28: rustc_mir::borrow_check::type_check::type_check
  29: rustc_mir::borrow_check::nll::compute_regions
  30: rustc_mir::borrow_check::do_mir_borrowck
  31: rustc_infer::infer::InferCtxtBuilder::enter
  32: rustc_mir::borrow_check::mir_borrowck
  33: core::ops::function::FnOnce::call_once
  34: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck_const_arg>::compute
  35: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  36: rustc_data_structures::stack::ensure_sufficient_stack
  37: rustc_query_system::query::plumbing::get_query_impl
  38: rustc_query_system::query::plumbing::ensure_query_impl
  39: rustc_mir::transform::mir_drops_elaborated_and_const_checked
  40: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_drops_elaborated_and_const_checked>::compute
  41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  42: rustc_data_structures::stack::ensure_sufficient_stack
  43: rustc_query_system::query::plumbing::get_query_impl
  44: rustc_mir::transform::inner_optimized_mir
  45: rustc_mir::transform::optimized_mir_of_const_arg
  46: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir_of_const_arg>::compute
  47: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  48: rustc_data_structures::stack::ensure_sufficient_stack
  49: rustc_query_system::query::plumbing::get_query_impl
  50: rustc_mir::interpret::eval_context::InterpCx<M>::load_mir
  51: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  52: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_raw>::compute
  53: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  54: rustc_data_structures::stack::ensure_sufficient_stack
  55: rustc_query_system::query::plumbing::get_query_impl
  56: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  57: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  58: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  59: rustc_data_structures::stack::ensure_sufficient_stack
  60: rustc_query_system::query::plumbing::get_query_impl
  61: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  62: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  63: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  64: rustc_data_structures::stack::ensure_sufficient_stack
  65: rustc_query_system::query::plumbing::get_query_impl
  66: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  67: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  68: <rustc_trait_selection::traits::project::AssocTypeNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const
  69: rustc_middle::ty::fold::TypeFoldable::fold_with
  70: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  71: <rustc_trait_selection::traits::project::AssocTypeNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  72: rustc_data_structures::stack::ensure_sufficient_stack
  73: rustc_trait_selection::traits::project::normalize
  74: <rustc_infer::infer::InferCtxt as rustc_trait_selection::infer::InferCtxtExt>::partially_normalize_associated_types_in
  75: rustc_typeck::check::FnCtxt::instantiate_value_path
  76: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  77: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  78: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  79: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  80: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  81: rustc_typeck::check::FnCtxt::check_stmt
  82: rustc_typeck::check::FnCtxt::check_block_with_expected
  83: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  84: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  85: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  86: rustc_typeck::check::check_fn
  87: rustc_infer::infer::InferCtxtBuilder::enter
  88: rustc_typeck::check::typeck
  89: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  90: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  91: rustc_data_structures::stack::ensure_sufficient_stack
  92: rustc_query_system::query::plumbing::get_query_impl
  93: rustc_query_system::query::plumbing::ensure_query_impl
  94: rustc_typeck::check::typeck_item_bodies
  95: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  96: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  97: rustc_data_structures::stack::ensure_sufficient_stack
  98: rustc_query_system::query::plumbing::get_query_impl
  99: rustc_typeck::check_crate
 100: rustc_interface::passes::analysis
 101: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
 102: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
 103: rustc_data_structures::stack::ensure_sufficient_stack
 104: rustc_query_system::query::plumbing::get_query_impl
 105: rustc_interface::passes::QueryContext::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (09f4c9f50 2020-08-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck_const_arg] borrow-checking the const argument`wow::{{constant}}#0`
#1 [mir_drops_elaborated_and_const_checked] elaborating drops for `wow::{{constant}}#0`
#2 [optimized_mir_of_const_arg] optimizing MIR for the const argument `wow::{{constant}}#0`
#3 [const_eval_raw] const-evaluating `wow::{{constant}}#0`
#4 [const_eval_validated] const-evaluating + checking `wow::{{constant}}#0`
#5 [const_eval_validated] const-evaluating + checking `wow::{{constant}}#0`
#6 [typeck] type-checking `wow`
#7 [typeck_item_bodies] type-checking all item bodies
#8 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #75323, fixes #74447 and fixes #73375.

This PR prohibits non-static lifetimes in anonymous constants when only the `min_const_generics` feature is enabled. ~~To do so, `to_region_vid`'s `bug!` had to be changed into a delayed bug, which unfortunately required providing it a `TyCtxt`.~~

--- 
~~While I am happy with how the implementation of the error turned out in `rustc_passes::check_const`,  emitting an error wasn't sufficient to avoid hitting the ICE later. I also tried implementing the error in `rustc_mir::transform::check_consts::validation` and that worked, but it didn't silence the ICE either. To silence the ICE, I changed it to a delayed bug which worked but was more invasive that I would have liked, and required I return an incorrect lifetime. It's possible that this check should be implemented earlier in the compiler to make the invasive changes unnecessary, but I wasn't sure where that would be and wanted to get some feedback first.~~
The approach taken by this PR has been changed to implement the error in name resolution, which ended up being much simpler.

cc @rust-lang/wg-const-eval 
r? @lcnr

### CODE REVIEW

File: src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#![feature(min_const_generics)]
```
Comment (hameerabbasi) [inline src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs:1]: I'd test this with revisions like the other tests.

**Review by lcnr — COMMENTED** [review]
Does this PR break the following snippet which already compiles on stable?
This restriction should only apply to anonymous constants, associated constants should not be affected here.

*edit: ignore the above questions, didn't see the check on `AnonConst`, this already works correctly*
```rust
#![feature(min_const_generics)]
struct Foo<'a>(&'a ());

impl<'a> Foo<'a> {
    const ASSOC: usize = {
        let x: &'a usize = &7;
        *x
    };
}
```

It might be easier to forbid these lifetimes during name resolution instead where we hopefully should be able to replace them with `ty::ReStatic`. I would expect this be a less invasive change which does not require us to change `bug` to a `delay_span_bug`.

File: src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs (hunk 1 above)
Comment (davidtwco) [reply src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs:1]: Fixed!

**Comment by davidtwco** [comment]
Pushed a change that makes the test check both `min_const_generics` and `const_generics`.

> Does this PR break the following snippet which already compiles on stable?
> This restriction should only apply to anonymous constants, associated constants should not be affected here.

As you've noticed, it doesn't break that snippet and only applies to anonymous constants.

> It might be easier to forbid these lifetimes during name resolution instead where we hopefully should be able to replace them with ty::ReStatic. I would expect this be a less invasive change which does not require us to change bug to a delay_span_bug.

I can give this approach a go if you'd prefer.

**Comment by davidtwco** [comment]
@lcnr I've updated the PR to implement this in name resolution (cc @petrochenkov), which did end up being much cleaner.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -1599,4 +1600,32 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
+    /// Non-static lifetimes are prohibited in anonymous constants under `min_const_generics` so
+    /// this function will emit an error if `min_const_generics` is enabled, the body identified by
+    /// `body_id` is a anonymous constant and `lifetime_ref` is non-static.
+    crate fn maybe_emit_forbidden_non_static_lifetime_error(
+        &self,
+        body_id: hir::BodyId,
+        lifetime_ref: &'tcx hir::Lifetime,
+    ) {
+        let is_anon_const = matches!(
+            self.tcx.def_kind(self.tcx.hir().body_owner_def_id(body_id)),
```
Comment (lcnr) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1613]: how does this deal with
```rust
fn test<'a>() -> [u8; {
    |()| {
        let _: &'a () = &();   
    };
    7
}] { todo!() }
```
It looks to me like this always causes an ICE, even with `#[feature(const_generics)]`

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1599,4 +1600,32 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
             _ => {}
         }
     }
+
+    /// Non-static lifetimes are prohibited in anonymous constants under `min_const_generics` so
+    /// this function will emit an error if `min_const_generics` is enabled, the body identified by
+    /// `body_id` is a anonymous constant and `lifetime_ref` is non-static.
```
Comment (lcnr) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1606]:
```suggestion
    /// `body_id` is an anonymous constant and `lifetime_ref` is non-static.
```

**Review by lcnr — APPROVED** [review]
I think this looks good now, but I am not too familiar with lifetime resolution, so maybe

r? @nikomatsakis for the final approval.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1613]: This causes triggers the error with this patch and `#![feature(min_const_generics)]` and an ICE with this patch and `#![feature(const_generics)]`. It's a different ICE than before though:

```
thread 'rustc' panicked at 'escaping bound vars for WellFormed(&'a ())', /home/david/Projects/rust/rust8/compiler/rustc_middle/src/ty/mod.rs:1396:9
```

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 3 above)
Comment (davidtwco) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Fixed!

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1613]: Added this to the test.

**Comment by hameerabbasi** [comment]
One request: Right now, it's hard to tell from the test which parts cause an ICE and which parts compile on `full`. It might be good to split the test up into multiple tests into `src/test/ui/const-generics/issues`, but this is only a suggestion.

**Comment by davidtwco** [comment]
I removed the example from [this comment](https://github.com/rust-lang/rust/pull/76739#discussion_r489231947) from the test because it gives a very similar but still different ICE on CI and that causes it to fail - I wasn't able to work out why that was, even after rebasing locally.

> One request: Right now, it's hard to tell from the test which parts cause an ICE and which parts compile on `full`. It might be good to split the test up into multiple tests into `src/test/ui/const-generics/issues`, but this is only a suggestion.

Given the above, I've kept a single test since the ICE is only produced from the cases that emit an error under `min_const_generics` and each ICE is the same.

File: src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr [hunk 4]
```diff
@@ -0,0 +1,15 @@
+error: internal compiler error: compiler/rustc_mir/src/borrow_check/universal_regions.rs:LL:CC: cannot convert `ReFree(DefId(0:12 ~ forbid_non_static_lifetimes[317d]::issue_73375[0]), BrNamed(DefId(0:13 ~ forbid_non_static_lifetimes[317d]::issue_73375[0]::'a[0]), 'a))` to a region vid
```
Comment (varkor) [inline src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr:1]: Why are we adding a unit test for an ICE?

File: src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+// normalize-stderr-test "note: rustc 1.* running on .*" -> "note: rustc VERSION running on TARGET"
+// normalize-stderr-test "note: compiler flags: .*" -> "note: compiler flags: FLAGS"
+// normalize-stderr-test "/universal_regions.rs:[0-9]+:[0-9]+" -> "/universal_regions.rs:LL:CC"
+//[full]failure-status: 101
+#![cfg_attr(full, feature(const_generics))]
+#![cfg_attr(full, allow(incomplete_features))]
+#![cfg_attr(min, feature(min_const_generics))]
+
+// This test checks that non-static lifetimes are prohibited under `min_const_generics`. It
+// currently emits an error with `min_const_generics` and an ICE with `const_generics`.
```
Comment (varkor) [inline src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.rs:12]: I think we should just add the `min_const_generics` test, but leave the issue that's not fixed on `const_generics` open with an appropriate label.

File: src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr (hunk 4 above)
Comment (davidtwco) [reply src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr:1]: I added this [when it was requested by a review comment](https://github.com/rust-lang/rust/pull/76739#discussion_r488631207), I can remove it if you'd prefer that.

Comment (hameerabbasi) [reply src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr:1]: I didn't know it'd ICE when I added the comment -- I'd add a comment saying why the ICE happens and a link to the issue, and why we cannot test with revisions.

Comment (davidtwco) [reply src/test/ui/const-generics/min_const_generics/forbid-non-static-lifetimes.full.stderr]: I've removed the ICE test and slightly updated the comment.

**Comment by varkor** [comment]
Thanks!

@bors r+ rollup
