### PR TITLE
Multi-variant layouts for generators

### LINKED ISSUE #59972: Futures involving uninhabited variables are incorrectly considered uninhabited.
[The following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=94e94d2007ff9c296483de69a0446837) crashes with an illegal instruction, presumably because all the code after `contains_never` is considered unreachable:

```rust
#![feature(futures_api, async_await, await_macro)]

pub enum Uninhabited { }

fn uninhabited_async() -> Uninhabited {
    unreachable!()
}

async fn noop() { }

async fn contains_never() {
    let error = uninhabited_async();
    await!(noop());
    let error2 = error;
}

fn main() {
    contains_never();
}
```

It seems the root cause is that the struct representing the future contains a field of type `Uninhabited` as it is preserved across the (unreachable) yield point and thus is considered uninhabited itself, despite being perfectly constructible.

### PR DESCRIPTION
**Pull request by tmandry**
This allows generators to overlap fields using variants, but doesn't do any such overlapping yet. It creates one variant for every state of the generator (unresumed, returned, panicked, plus one for every yield), and puts every stored local in each of the yield-point variants.

Required for optimizing generator layouts (#52924).

There was quite a lot of refactoring needed for this change. I've done my best in later commits to eliminate assumptions in the code that only certain kinds of types are multi-variant, and to centralize knowledge of the inner mechanics of generators in as few places as possible.

This change also emits debuginfo about the fields contained in each variant, as well as preserving debuginfo about stored locals while running in the generator.

Also, fixes #59972.

Future work:
- Use this change for an optimization pass that actually overlaps locals within the generator struct (#52924)
- In the type layout fields, don't include locals that are uninitialized for a particular variant, so miri and UB sanitizers can check our memory (see https://github.com/rust-lang/rust/issues/59972#issuecomment-483058172)
- Preserve debuginfo scopes across generator yield points

### CODE REVIEW

**Comment by tmandry** [comment]
r? @eddyb 
cc @Zoxc @cramertj

**Comment by tmandry** [comment]
One funky aspect of this is that we declare locals in debuginfo multiple times, one for each yield point their storage lives across (which, for now, is all of them). This will make more sense when/if we add scopes to those locals that correspond with the yield points. For now, I don't see any downsides to this, except bigger debuginfo.

File: src/librustc_codegen_ssa/mir/mod.rs [hunk 1]
```diff
@@ -667,18 +668,25 @@ fn arg_local_refs<'a, 'tcx: 'a, Bx: BuilderMethods<'a, 'tcx>>(
...
-                                        (variant_idx, i, name, false, ty)
-                                })
+                                    if let Some(name) = decl.name {
+                                        let ty = fx.monomorphize(&ty);
+                                        let (var_scope, var_span) = fx.debug_loc(mir::SourceInfo {
+                                            span: decl.source_info.span,
+                                            scope: decl.visibility_scope,
+                                        });
+                                        let var_scope = var_scope.unwrap_or(scope);
+                                        Some((variant_idx, i, name, false, ty, var_scope, var_span))
```
Comment (tmandry) [inline src/librustc_codegen_ssa/mir/mod.rs]: This didn't have the desired effect of making locals live across suspension points only showing up in their source scopes. It's possible that without other changes, preserving the source visibility scopes is just wrong. Does anyone know?

**Comment by tmandry** [comment]
Travis failure is for the wrong commit. Can someone re-run? cc @rust-lang/infra

**Comment by kennytm** [comment]
@tmandry You could re-run it by closing & reopening the PR, or pushing a new commit. But the failure in https://travis-ci.com/rust-lang/rust/jobs/194180525 does look legit and referring to the correct HEAD commit 2cb4fadfb54e8d9a3a724f58829842bcc68927a5 (merge commit d656918bd26aa255a6288931ed16d51589f20ca8).

**Comment by tmandry** [comment]
@kennytm Nevermind I'm dumb, I forgot about merge commits, sorry.

Still having trouble reproducing this on linux, even on the exact merge commit that's failing in Travis...

**Comment by tmandry** [comment]
Rebased in hopes that this error magically goes away :)

**Comment by tmandry** [comment]
I haven't managed to reproduce locally but I suspect this is due to the enum fallback code for LLVM 6. Pushing a quick fix to see.

**Comment by tmandry** [comment]
Rebased.

**Comment by tmandry** [comment]
Squashed some small fix commits to make this easier to review.

**Comment by tmandry** [comment]
Removed submodule changes

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 2]
```diff
@@ -684,6 +684,25 @@ impl<'a, 'b, 'gcx, 'tcx> TypeVerifier<'a, 'b, 'gcx, 'tcx> {
                         }
                     }
                 }
+                ty::Generator(def_id, substs, _) => {
```
Comment (Zoxc) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Why is this needed? Do you need to downcast to access upvars now?

Comment (Zoxc) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Using `state_tys` during NLL seems problematic too.

Comment (tmandry) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Hmm, I don't think this was actually needed, I found it during grep and added it for "completeness". That was probably wrong in retrospect.

File: src/librustc_mir/transform/deaggregator.rs [hunk 3]
```diff
@@ -55,6 +56,23 @@ impl MirPass for Deaggregator {
                         }
                         active_field_index
                     }
+                    AggregateKind::Generator(..) => {
```
Comment (Zoxc) [inline src/librustc_mir/transform/deaggregator.rs]: @eddyb Does the codegen backend assume there's no aggregates or is this just an optimization?

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 2 above)
Comment (Zoxc) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: The previous MIR type check ran after generator transformation, so maybe this does too? It would be needed in that case at least.

File: src/librustc_mir/transform/deaggregator.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_mir/transform/deaggregator.rs]: It's not turned on by default AFAIK. We might change that in the future though, so it'd be good to have it work, for completeness.

File: src/librustc/mir/mod.rs [hunk 4]
```diff
@@ -2998,7 +2997,7 @@ pub struct UnsafetyCheckResult {
 /// The layout of generator state
 #[derive(Clone, Debug, RustcEncodable, RustcDecodable, HashStable)]
 pub struct GeneratorLayout<'tcx> {
-    pub fields: Vec<LocalDecl<'tcx>>,
+    pub variant_fields: IndexVec<VariantIdx, Vec<LocalDecl<'tcx>>>,
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: I think the inner `Vec` could be `IndexVec<Field`.
Also, surprised this is `LocalDecl`, is that only for debuginfo?
If so, can you add something similar to `__upvar_debuginfo_codegen_only_do_not_use`, to ensure there is no cross-talk between debuginfo and non-debuginfo usecases?

File: src/librustc/ty/layout.rs [hunk 5]
```diff
@@ -1646,6 +1691,14 @@ impl<'a, 'tcx, C> TyLayoutMethods<'tcx, C> for Ty<'tcx>
 
     fn field(this: TyLayout<'tcx>, cx: &C, i: usize) -> C::TyLayout {
         let tcx = cx.tcx();
+        let handle_discriminant = |discr: &Scalar| -> C::TyLayout {
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: I'd call this `make_discr_field` (which we should maybe pre-intern, this could be unnecessarily expensive).

File: src/librustc/ty/sty.rs [hunk 6]
```diff
@@ -470,33 +468,91 @@ impl<'tcx> GeneratorSubsts<'tcx> {
...
+    ) -> impl Iterator<Item=(VariantIdx, Discr<'tcx>)> + Captures<'gcx> + 'a {
+        self.variant_range(def_id, tcx).map(move |index| {
+            (index, Discr { val: index.as_usize() as u128, ty: self.discr_ty(tcx) })
+        })
+    }
+
+    /// Calls `f` with a reference to the name of the enumerator for the given
+    /// variant `v`.
+    #[inline]
+    pub fn map_variant_name<R>(&self, v: VariantIdx, f: impl FnOnce(&str) -> R) -> R {
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: We usually do `-> Cow<'static, str>` for this.

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_codegen_ssa/mir/mod.rs]: I wouldn't worry about it until we have proper MIR debuginfo, TBH.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I think it should run before, so you can remove this and check. cc @nikomatsakis

File: src/librustc/ty/sty.rs [hunk 7]
```diff
@@ -470,33 +468,91 @@ impl<'tcx> GeneratorSubsts<'tcx> {
...
+        let name = match v.as_usize() {
+            Self::UNRESUMED => Self::UNRESUMED_NAME,
+            Self::RETURNED => Self::RETURNED_NAME,
+            Self::POISONED => Self::POISONED_NAME,
+            _ => {
+                return f(&format!("variant#{}", v.as_usize()));
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: What if you were to use `format!("Suspend{}", v.as_usize() - 3)`? I think that would be neater overall.

File: src/librustc_codegen_llvm/type_of.rs [hunk 8]
```diff
@@ -63,6 +63,11 @@ fn uncached_llvm_type<'a, 'tcx>(cx: &CodegenCx<'a, 'tcx>,
                     write!(&mut name, "::{}", def.variants[index].ident).unwrap();
                 }
             }
+            if let (&ty::Generator(..), &layout::Variants::Single { index })
+                 = (&layout.ty.sty, &layout.variants)
+            {
+                write!(&mut name, "::variant#{:?}", index).unwrap();
```
Comment (eddyb) [inline src/librustc_codegen_llvm/type_of.rs]: This should use the `variant_name` method.

File: src/librustc_mir/transform/deaggregator.rs [hunk 9]
```diff
@@ -55,6 +56,23 @@ impl MirPass for Deaggregator {
...
+                        // Right now we only support initializing generators to
+                        // variant#0.
```
Comment (eddyb) [inline src/librustc_mir/transform/deaggregator.rs]: I'd write this `variant 0 (Unresumed)`.

File: src/test/debuginfo/generator-objects.rs [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+// min-system-llvm-version: 8.0
+// min-gdb-version: 8.2
+
+// compile-flags:-g
+
+// === GDB TESTS ===================================================================================
+
+// gdb-command:run
+// gdb-command:print b
+// gdb-check:$1 = generator_objects::main::generator {__0: 0x[...], <<variant>>: {__state: 0, 0: generator_objects::main::generator::Unresumed, 1: generator_objects::main::generator::Returned, 2: generator_objects::main::generator::Panicked, 3: generator_objects::main::generator::variant#3 {[...]}, 4: generator_objects::main::generator::variant#4 {[...]}}}
```
Comment (eddyb) [inline src/test/debuginfo/generator-objects.rs]: Surprised that `__state` is inside `<<variant>>` - is that an artifact of the old layout representation, that I left around in debuginfo in #45225 (to avoid regressions), I wonder?
cc @michaelwoerister

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: It runs before generator transformation.

Comment (tmandry) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Okay, I can remove it and replace it with a comment then.

File: src/librustc/mir/mod.rs (hunk 4 above)
Comment (tmandry) [reply src/librustc/mir/mod.rs]: Hmm, no, we also use it to get the type of the fields in `GeneratorSubsts::state_tys()`. I suppose I can turn it into a struct with something like `__upvar_debuginfo_codegen_only_do_not_use` and whatever struct we should be using here. (What should we be using? Right now we only need the type, I think.)

File: src/test/debuginfo/generator-objects.rs (hunk 10 above)
Comment (tmandry) [reply src/test/debuginfo/generator-objects.rs]: I think it's a consequence of the discriminant being a member of the "variant part". Here's the [DWARF for the generator](https://gist.github.com/tmandry/92e1368b51bea06d11da1e45218813db).

Given that this is how we handle enums it seems correct, but it might require changes to gdb/lldb to make it prettier.

Comment (eddyb) [reply src/test/debuginfo/generator-objects.rs]: I mean, I don't think we're handling enums correctly (or rather, ideally).

File: src/librustc/mir/mod.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc/mir/mod.rs]: I meant that `GeneratorLayout` should *only* have `Ty<'tcx>`, and that debuginfo should be separate.

File: src/test/debuginfo/generator-objects.rs (hunk 10 above)
Comment (tmandry) [reply src/test/debuginfo/generator-objects.rs]: Can you be more specific? The DWARF generation seems "correct", but older GDB (and current LLDB) don't handle enum variants with fields well. Is that what you mean?

Comment (eddyb) [reply src/test/debuginfo/generator-objects.rs]: Nevermind, I guess I have no idea what the syntax of `<<variant>>` is.

File: src/librustc/mir/mod.rs (hunk 4 above)
Comment (tmandry) [reply src/librustc/mir/mod.rs]: I separated these out and made a `GeneratorField` newtype. That way our layout code will also know when the same field is in two variants so it can lay them out correctly (see the FIXME I added).

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (tmandry) [reply src/librustc_codegen_ssa/mir/mod.rs]: Left as-is for now.

File: src/test/debuginfo/generator-objects.rs [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+// gdb-check:$2 = generator_objects::main::generator {__0: 0x[...], <<variant>>: {__state: 3, 0: generator_objects::main::generator::Unresumed, 1: generator_objects::main::generator::Returned, 2: generator_objects::main::generator::Panicked, 3: generator_objects::main::generator::variant#3 {c: 6, d: 7}, 4: generator_objects::main::generator::variant#4 {[...]}}}
+// gdb-command:continue
+// gdb-command:print b
+// gdb-check:$3 = generator_objects::main::generator {__0: 0x[...], <<variant>>: {__state: 4, 0: generator_objects::main::generator::Unresumed, 1: generator_objects::main::generator::Returned, 2: generator_objects::main::generator::Panicked, 3: generator_objects::main::generator::variant#3 {[...]}, 4: generator_objects::main::generator::variant#4 {c: 7, d: 8}}}
+// gdb-command:continue
+// gdb-command:print b
+// gdb-check:$4 = generator_objects::main::generator {__0: 0x[...], <<variant>>: {__state: 1, 0: generator_objects::main::generator::Unresumed, 1: generator_objects::main::generator::Returned, 2: generator_objects::main::generator::Panicked, 3: generator_objects::main::generator::variant#3 {[...]}, 4: generator_objects::main::generator::variant#4 {[...]}}}
```
Comment (eddyb) [inline src/test/debuginfo/generator-objects.rs]: These still mention `variant#`, is this still the right output?

File: src/librustc/mir/mod.rs [hunk 12]
```diff
@@ -2994,10 +2994,29 @@ pub struct UnsafetyCheckResult {
     pub unsafe_blocks: Lrc<[(hir::HirId, bool)]>,
 }
 
+newtype_index! {
+    pub struct GeneratorField {
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: Tempted to call this something other than "field", like "savee", but that sounds really bad.

File: src/test/debuginfo/generator-objects.rs (hunk 11 above)
Comment (tmandry) [reply src/test/debuginfo/generator-objects.rs]: oops, no, updated.

File: src/librustc/mir/mod.rs (hunk 12 above)
Comment (tmandry) [reply src/librustc/mir/mod.rs]: `GeneratorSavedLocal`? =/

Comment (eddyb) [reply src/librustc/mir/mod.rs]: Oh, I actually like that!

Comment (tmandry) [reply src/librustc/mir/mod.rs]: Okay, done!

**Comment by RalfJung** [comment]
This broke the generator traversal logic in Miri at https://github.com/rust-lang/rust/blob/e2326366935613816927e679d3b2dc04db44678c/src/librustc_mir/interpret/visitor.rs#L315-L323. Any advise for how to fix it?

**Comment by RalfJung** [comment]
Looks like even though generators have variants, they still also contain "wrong" fields in their variants, meaning fields that are not actually going to be initialized when that variant is active. So generators still need a special exception. I think for now I'll just treat the entire generator as if it was a union.

Are there any plans to make the layout information correct, in the sense that when a field is present in a variant according to the layout, then it will also always be initialized?

**Comment by Zoxc** [comment]
> Are there any plans to make the layout information correct, in the sense that when a field is present in a variant according to the layout, then it will also always be initialized?

No. Generators are basically a function frame, not an enum. Even for enums it is not true as they can be partially moved out of. A similar thing can happen with generators where a value in the generator is partially moved out of, even when the generator is not executing. There might be other edge cases due to generators being function frames. https://github.com/rust-lang/rust/pull/60187 should make the layout closer to the actual values contained though.

**Comment by RalfJung** [comment]
Moving out is not a problem -- that leaves the bits in the old place untouched, so they still satisfy the validity invariant.

What is a problem is having a `bool` field, and not making sure that it definitely is either `true` or `false`. At that point the layout is just not correctly reflecting the data being stored there. This can lead to all sorts of problems, and [already requires some awful hack to not break](https://github.com/rust-lang/rust/blob/2f1bc91803b04caf3e20b3849633bb7ffe6b4074/src/librustc/ty/layout.rs#L1884).

@eddyb However, this does somehow conflict with your proposal to make `Move` overwrite the moved-out data with `Undef`.

**Comment by tmandry** [comment]
@RalfJung Yeah, #60187 will get us closer. As @eddyb pointed out, we still need to save liveness (not just storage-liveness) information in `GeneratorLayout`. We also still have to worry about aggregates that are only ever partially initialized.

The short-term fix we discussed will be to wrap the types of every field with `MaybeUnitialized` in the layout code, so you don't have to handle it specially in miri. Still, I'd like to get a higher fidelity picture out at some point.

**Comment by RalfJung** [comment]
> The short-term fix we discussed will be to wrap the types of every field with MaybeUnitialized in the layout code, so you don't have to handle it specially in miri. Still, I'd like to get a higher fidelity picture out at some point.

That would also work (and will also do the right thing for inhabitedness and layout computation).
