### PR TITLE
NVPTX: Avoid PassMode::Direct for args in C abi

### LINKED ISSUE #117480: nvptx abi adjustment may keep PassMode::Direct for small aggregates in conv `extern "C"`
@kjetilkjeka I had to disable this test on nvptx64 since the `extern "C"` ABI uses `Direct` pass mode in invalid ways. I think that's caused by this code:

https://github.com/rust-lang/rust/blob/b75b3b3afecfb6638c7c75ad665f8f3091aab1ae/compiler/rustc_target/src/abi/call/nvptx64.rs#L10-L14

That's invalid since it doesn't say what to do for smaller aggregates, and they default to the (bad) `Direct`. Instead you have to say which register they are supposed to be passed in. You can check what the other targets are doing. Targets are expected to set an explicit pass mode for *all* aggregate arguments.

This should be easy to reproduce by having a function like
```rust
#[repr(C)]
struct ReprC1<T: ?Sized>(T);

extern "C" fn myfn(x: ReprC1<i32>) {}
```
which will likely ICE on the current compiler already.

_Originally posted by @RalfJung in https://github.com/rust-lang/rust/pull/117351#discussion_r1375418626_

### PR DESCRIPTION
**Pull request by kjetilkjeka**
Fixes #117480 

I must admit that I'm confused about `PassMode` altogether, is there a good sum-up threads for this anywhere? I'm especially confused about how "indirect" and "byval" goes together. To me it seems like "indirect" basically means "use a indirection through a pointer", while "byval" basically means "do not use indirection through a pointer". 

The return used to keep `PassMode::Direct` for small aggregates. It turns out that `make_indirect` messes up the tests and one way to fix it is to keep `PassMode::Direct` for all aggregates. I have mostly seen this PassMode mentioned for args. Is it also a problem for returns? When experimenting with `byval` as an alternative i ran into [this assert](https://github.com/rust-lang/rust/blob/61a3eea8043cc1c7a09c2adda884e27ffa8a1172/compiler/rustc_codegen_llvm/src/abi.rs#L463C22-L463C22) 

I have added tests for the same kind of types that is already tested for the "ptx-kernel" abi. The tests cannot be enabled until something like #117458 is completed and merged.

CC: @RalfJung since you seem to be the expert on this and have already helped me out tremendously

CC: @RDambrosio016 in case this influence your work on `rustc_codegen_nvvm`

@rustbot label +O-NVPTX

### CODE REVIEW

**Comment by RalfJung** [comment]
> I must admit that I'm confused about PassMode altogether, is there a good sum-up threads for this anywhere?

Sadly, no. The best we have are the [API docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_llvm/abi/enum.PassMode.html). I improved them a bit recently, but we are still lacking some proper "big-picture" docs for this. largely this is because while the system was designed with some big-picture ideas ~5 years ago, those were not written down at the time and since then it's been hotfixed and patched without regard for a coherent story. The entire system needs an overhaul. See https://github.com/rust-lang/compiler-team/issues/672: the compiler team accepted the proposal to overhaul this, but we're still looking for a volunteer to do the work.

> CC: @RalfJung since you seem to be the expert on this and have already helped me out tremendously

:joy: I knew nothing about this until around 3 months ago, and spent way too much time on it since.^^ I still don't feel like an expert, since all I know is reverse engineered from looking at parts of rustc. There are many things about ABI I do not know. But at this point I think I know at least how rustc deals with ABI, and I know some necessary (but not sufficient) conditions for ABI adjustments to make sense.

**Comment by RalfJung** [comment]
Sadly, for this PR, I can't really tell if it makes any sense. But if it helps fix the assertions and also still generates working code for your tests, then it's at least an improvement...

**Comment by bjorn3** [comment]
I think you will want to use `PassMode::Cast` for aggregate types.

**Comment by bjorn3** [comment]
> In ptx these primitives are padded while aggregates are not.

:scream:

**Comment by compiler-errors** [comment]
Sorry, too busy to review this 😰 

r? compiler

**Comment by cjgillot** [comment]
r? compiler

**Review by davidtwco — APPROVED** [review]
Apologies for the delay in getting to this - we don't have an expert in NVPTX on the team, so I'll take a stab at reviewing this so it isn't stuck forever. It seems reasonable to me. 

Does this mean that NVPTX can be re-enabled in `tests/ui/abi/compatibility.rs` now? If so, could you do that in this PR? Otherwise let me know and I'll approve this.

**Comment by kjetilkjeka** [comment]
When rebasing there are unfortunately regressions on some of the tests related to returning structs. I will look into re-enabling the compatibility test when I have investigated these regressions.

If there's any silver lining I guess it is that it highlights the importance of #117458 and getting the nvptx tests up and running again in CI.

**Comment by RalfJung** [comment]
> Does this mean that NVPTX can be re-enabled in tests/ui/abi/compatibility.rs now? If so, could you do that in this PR? Otherwise let me know and I'll approve this.

Yeah it should be re-enabled, otherwise the claim that it fixes the issue is not accurate.

**Comment by kjetilkjeka** [comment]
Yes, this is waiting for #117458 

It turned out to be more difficult than anticipated to get correct. I will of course spend the time to figure it out, but when I manage to get it right I would hate for it to break again. Therefore I would love to wait until the nvptx tests are enabled in CI so I can write tests and be confident that things will keep working.

**Comment by apiraino** [comment]
@kjetilkjeka when you have a sec. can you look at this patch again? Thanks

@rustbot author

**Comment by kjetilkjeka** [comment]
It's unblocked now :fireworks: . I will take a look at this at the end of this week or early next week.

**Comment by kjetilkjeka** [comment]
After looking into this my conclusions is that it's impossible to both avoid `PassMode::Direct` for the C ABI and generate correct code.

An example that illustrates this is returning a type in in this way
```rust
#[repr(C)]
pub struct SingleU8 {
    f: u8,
}

#[no_mangle]
pub unsafe extern "C" fn f_single_u8_ret() -> SingleU8 {
    SingleU8 { f: 42 }
}
```

Which should give the following signature in ptx.
```
.visible .func  (.param .align 1 .b8 func_retval0[1]) f_single_u8_ret()
```

The only two `PassModes` that give the correct signature is `Direct` and `Indirect{on_stack: true}`. For arguments it's possible to use `Indirect{on_stack: true}` but that is not the case for returns.

`PassMode::Cast` casted to an uniform does the correct thing for many types, but unfortunately not for single element structs (it passes like it was the underlying type, not the struct itself).

The solution is probably to have something like the `CAbiType` described in [this issue](https://github.com/rust-lang/compiler-team/issues/672) and a `PassMode::CAbiType(CAbiType)` that can pass like a concrete C type. But everything related to this ABI compatibility things is unfortunately too complex for me to handle.

That means that this PR avoids the use of `PassMode::Direct` in argument position. But unfortunately doesn't manage to solve it in return position. I have added tests for both return and argument position, but the test for return position is ignored.

**Review by davidtwco — APPROVED** [review]
This seems like an improvement even if it doesn't fix everything so LGTM.

**Comment by RalfJung** [comment]
Unfortunately this did not fully fix the problem, see https://github.com/rust-lang/rust/issues/117480#issuecomment-2136580581.

File: tests/assembly/nvptx-c-abi-ret-v7.rs [hunk 1]
```diff
@@ -0,0 +1,230 @@
+//@ assembly-output: ptx-linker
+//@ compile-flags: --crate-type cdylib -C target-cpu=sm_86 -Z unstable-options -Clinker-flavor=llbc
+//@ only-nvptx64
+//@ ignore-nvptx64
```
Comment (RalfJung) [inline tests/assembly/nvptx-c-abi-ret-v7.rs:4]: Why does this have to be ignored? You are still using `PassMode::Direct` for the return value, so I thought that would still generate the right ABI?

Comment (kjetilkjeka) [reply tests/assembly/nvptx-c-abi-ret-v7.rs:4]: It's unfortunately slightly broken (from before this PR) since there never were any tests for this. 

I will enable these tests in the follow up PR we talked about that I hopefully will be able to create today

Comment (kjetilkjeka) [reply tests/assembly/nvptx-c-abi-ret-v7.rs:4]: Enabled in #125980
