### PR TITLE
interpret: support for per-byte provenance

### LINKED ISSUE #2181: Miri cannot represent partial pointers (for byte-wise copy and partial overwrite)
Miri's model of memory can only attach provenance to pointer-sized chunks of memory, but not to individual bytes. This leads to incorrect behavior in several situations:
- We cannot copy a pointer one `MaybeUninit<u8>` at a time. In particular this affects `ptr::swap_nonoverlapping`.
- We cannot overwrite some of the bytes of a pointer, but preserve provenance on the bytes that remain.

### PR DESCRIPTION
**Pull request by RalfJung**
Also factors the provenance map into its own module.

The third commit does the same for the init mask. I can move it in a separate PR if you prefer.

Fixes https://github.com/rust-lang/miri/issues/2181

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Only stress tests regress... but I still wonder why, since `OFFSET_IS_ADDR` will be false there so most of the new code is dead code.

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs [hunk 1]
```diff
@@ -0,0 +1,283 @@
...
+}
+
+impl ProvenanceMap {
+    /// Give access to the ptr-sized provenances (which can also be thought of as relocations, and
+    /// indeed that is how codegen treats them).
+    ///
+    /// Only exposed with `AllocId` provenance, since it panics if there is bytewise provenance.
+    #[inline]
+    pub fn ptrs(&self) -> &SortedMap<Size, AllocId> {
+        debug_assert!(self.bytes.is_empty());
```
Comment (bjorn3) [inline compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:42]: Does const eval check this before returning the allocation to a codegen backend?

**Comment by RalfJung** [comment]
Wtf how did this patch make things worse?!?

**Comment by oli-obk** [comment]
the cranelift cachegrind against master is

> 230,826,737  ???:<rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>

the keccak cachegrind against master is

> 894,593,427  ???:<rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>

In contrast, before your "perf improvements" 😝 the CTFE regression was 

```
469,763,341  ???:<rustc_middle::mir::interpret::allocation::provenance_map::ProvenanceMap>::prepare_copy::<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>
-68,841,143  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::run
 15,729,623  ???:<rustc_middle::mir::interpret::allocation::init_mask::InitMask>::set_range
-15,729,396  ???:<rustc_middle::mir::interpret::allocation::InitMask>::set_range
  8,388,642  ???:<rustc_const_eval::interpret::memory::AllocRef<rustc_middle::mir::interpret::AllocId, ()>>::get_bytes_strip_provenance
 -7,341,503  ???:<rustc_middle::mir::interpret::allocation::Allocation>::is_init
  7,078,108  ???:<rustc_middle::mir::interpret::allocation::Allocation>::init_mask_apply_copy
 -7,078,082  ???:<rustc_middle::mir::interpret::allocation::Allocation>::mark_compressed_init_range
  6,292,512  ???:<rustc_middle::mir::interpret::allocation::init_mask::InitMask>::prepare_copy
 -5,506,061  ???:<rustc_middle::mir::interpret::allocation::Allocation>::compress_uninit_range
  5,113,981  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::copy_op_no_validate
  4,719,336  ???:<rustc_middle::mir::interpret::allocation::Allocation>::get_bytes_mut_ptr::<rustc_middle::ty::query::TyCtxtAt>
  4,718,592  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::read_scalar
 -1,441,903  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::size_and_align_of
  1,205,870  ???:<rustc_middle::ty::context::TyCtxt>::try_subst_and_normalize_erasing_regions::<rustc_middle::ty::Ty>
 -1,048,576  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::unsize_into_ptr
  1,004,228  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::eval_operand
    734,086  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::eval_fn_call
    734,054  ???:<rustc_const_eval::const_eval::machine::CompileTimeInterpreter as rustc_const_eval::interpret::machine::Machine>::find_mir_or_eval_fn
    427,361  ???:rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::implementations_of_trait
```

**Comment by oli-obk** [comment]
maybe the new "regressions" are not related to this PR at all and happen spuriously everywhere?

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:42]: This is the check -- a debug assertion.

It is impossible for const-eval to ever have byte provenance since `OFFSET_IS_ADDR` is false.

Comment (bjorn3) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:42]: > It is impossible for const-eval to ever have byte provenance since OFFSET_IS_ADDR is false.

This is the part I was missing.

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:42]: I should add comments explaining that.

**Comment by RalfJung** [comment]
I guess we can re-run perf since I changed a comment; that could give us an idea whether the result reproduces.

@bors try @rust-timer queue

**Comment by RalfJung** [comment]
Well that looks a lot better, despite being the exact same code...

**Comment by oli-obk** [comment]
Comparing the new and the old logic for `prepare_copy`, I think we just need a fast path for the const eval case. There are various additional things happening now that just weren't checked before, and I don't see a good way to untangle them.

**Comment by RalfJung** [comment]
Which additional things?

The `range_get_ptrs` queries for ptrs at the edges already existed before, they were just done in `memory.rs`.

I guess the one new thing is that we are computing the range of pointers *inside* the range, rather than first checking there is nothing on the edges and then computing the range of pointers that overlaps with the range. That's one extra conditional for the `src.size < ptr_size`. Given that in the first branch, `ptrs` is empty, we can probably make this a bit less silly.

**Comment by RalfJung** [comment]
The only other idea I have is that this might be related to Allocation and ProvenanceCopy being 24 bytes bigger now.

**Comment by oli-obk** [comment]
Could try making this generic over the machine or provenance  trait, so CTFE doesn't see any of this. Or we say we'll take the hit because we'll allow bytewise provenance in CTFE at some point

**Comment by RalfJung** [comment]
I'll try some Box-ing before going generic.

Supporting this in CTFE will be a lot of work. We'll need a way to remember "this is byte N of that pointer".

**Comment by RalfJung** [comment]
That looks better? The primary regressions have very low significance and are small in absolute terms. The secondary regressions did go down a bit. On ctfe-stress-5 this is even an improvement. :)

I assume to shrink this further I would indeed need associated types to entirely remove the new struct fields in the CTFE machine.

@oli-obk let me know how you want to proceed, then I can squash the commits accordingly.

**Comment by saethlin** [comment]
Just trying to follow along... The fact that we're basically only regressing on incr- benchmarks and faster on ctfe-stress makes me wonder if the source of the regression is not the speed of const eval, but the increased complexity of the provenance maps being serialized?

**Comment by RalfJung** [comment]
We're only serializing an extra None pointer though...

**Comment by oli-obk** [comment]
Looking at cachegrind

```
 13,163,790  ???:<rustc_middle::ty::Ty as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
-12,034,729  ???:<alloc::boxed::Box<rustc_middle::mir::Constant> as rustc_serialize::serialize::Encodable<rustc_metadata::rmeta::encoder::EncodeContext>>::encode
 11,998,830  ???:<rustc_middle::mir::Constant as rustc_serialize::serialize::Encodable<rustc_metadata::rmeta::encoder::EncodeContext>>::encode
 -4,797,299  ???:<[rustc_middle::mir::LocalDecl] as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
 -3,869,148  ???:<rustc_middle::mir::Constant as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
 -2,680,064  ???:<&rustc_middle::ty::context::TypeckResults as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
  2,459,698  ???:<[rustc_middle::mir::Statement] as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
 -1,481,768  ???:<[rustc_middle::ty::adjustment::Adjustment] as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
    930,338  ???:<rustc_query_impl::on_disk_cache::CacheEncoder as rustc_serialize::serialize::Encoder>::emit_enum_variant::<<rustc_middle::mir::syntax::Operand as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode::{closure
    502,162  ???:<rustc_middle::ty::Ty as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   -346,802  ???:<alloc::vec::Vec<rustc_middle::mir::syntax::Operand> as rustc_serialize::serialize::Encodable<rustc_query_impl::on_disk_cache::CacheEncoder>>::encode
   -249,517  ???:<rustc_parse::parser::Parser>::expect_one_of
    217,827  ???:<rustc_middle::ty::Ty as rustc_serialize::serialize::Encodable<rustc_metadata::rmeta::encoder::EncodeContext>>::encode
    179,943  ???:<rustc_parse::parser::Parser>::parse_arm::{closure
    174,930  ???:<alloc::rc::Rc<alloc::vec::Vec<rustc_ast::tokenstream::TokenTree>> as core::ops::drop::Drop>::drop
```

this seems to be indeed caching related (or just caching code inlining noise). It seems fine to me, but I'm wondering now if we ever serialize anything but `None`? And if that is the case, we can just not serialize it and assert that it is `None`.

**Comment by RalfJung** [comment]
The `bytes` field is always `None` for CTFE. So yes we could skip it when serializing.

> And if that is the case, we can just not serialize it and assert that it is None.

I have no idea how to do that.^^

**Comment by oli-obk** [comment]
> I have no idea how to do that.^^

done XD

File: compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs [hunk 2]
```diff
@@ -21,6 +22,20 @@ pub struct ProvenanceMap<Prov = AllocId> {
...
+impl<D: Decoder, Prov: Decodable<D>> Decodable<D> for ProvenanceMap<Prov> {
+    fn decode(d: &mut D) -> Self {
+        Self { ptrs: Decodable::decode(d), bytes: None }
+    }
+}
+
+impl<S: Encoder, Prov: Encodable<S>> Encodable<S> for ProvenanceMap<Prov> {
+    fn encode(&self, s: &mut S) {
+        let Self { ptrs, bytes } = self;
+        debug_assert!(bytes.is_none());
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:34]: This is only true when `Prov` is `AllocId` (or more generally, when `Prov::OFFSET_IS_ADDR` is false). But we only need that instance. So maybe we can avoid making it generic?

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/allocation/provenance_map.rs:34]: I tried that, but then we'd need to add manual impls for everything using `ProvenanceMap` (like `Allocation`, and I don't like that)

**Comment by RalfJung** [comment]
Ah that looks much better. :D

**Comment by RalfJung** [comment]
@oli-obk is there still anything blocking this?
