### PR TITLE
rustc: Stabilize `-Zrun-dsymutil` as `-Csplit-debuginfo`

### LINKED ISSUE #79361: Tracking issue for `-Zrun-dsymutil`
This is a (belatedly-opened) issue with the intention of tracking the `-Zrun-dsymutil` flag to the compiler. This flag was implemented long ago in https://github.com/rust-lang/rust/pull/47784 and the intention is to prevent rustc from automatically running `dsymutil` on macOS, which it automatically does today for builds with debuginfo. The purpose for doing this is that `dsymutil` is a pretty slow process and can make debug incremental compile times quite painful.

The purpose of `dsymutil` itself is to collect all debuginfo from the executable and all its dependencies into an adjacent `*.dSYM` folder next to the executable itself. This form of split-debuginfo is then read by debuggers and such. This consequently means that `dsymutil` is inherently not incremental. It will unconditionally run over the entire final binary and produce the entire `*.dSYM` folder each time. Since this runs over the final artifact which typically has a lot of debuginfo this can take quite a long time.

As discovered on https://github.com/rust-lang/rust/pull/47784, however, the reason this has been unstable for so long is that `dsymutil` was required for filenames and line numbers with `RUST_BACKTRACE` by default. It was too unreasonable for Cargo or other tooling to not run `dsymutil` because it broke this important feature.  With the advent of a Rust-based backtrace backend, however, we [now have support to parse debuginfo](https://github.com/rust-lang/backtrace-rs/pull/377) even if `dsymutil` hasn't run. This uses the same technique LLDB uses to give you debuginfo even when `dsymutil` hasn't run. This was then later [integrated into libstd](https://github.com/rust-lang/rust/pull/79237) and is purportedly [working well and greatly improving incremental compile time](https://github.com/rust-lang/rust/pull/79237#issuecomment-732348580).

As for the nitty-gritty of what this flag does:

* If enabled `run-dsymutil` will execute `dsymutil` over the final binary. This flag is enabled  by default since it's always been rustc's default behavior.
* If disabled, the compiler both does not run `dsymutil` *and* it doesn't delete the object files on disk relevant for the final compilation. This ensures that references in the binary to the object files for debuginfo can be followed and found.

I'd like to, while opening this issue, also propose that this flag get stabilized. I think the interface is work bikeshedding (e.g. naming and such), but I think the functionality is all in what should be the final end state. I think the expected vision for how we ship this benefit to end users is to switch Cargo's defaults to passing `run-dsymutil=no` (or the equivalent) by default on macOS. That way macOS users should, by default, get the benefit of no `dsymutil` invocations but should retain the ability to debug executables as well as get filenames/line numbers with backtraces. Furthermore if `*.dSYM` is still required by the user, end-applications can always run it as part of a build process themselves.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit adds a new stable codegen option to rustc,
`-Csplit-debuginfo`. The old `-Zrun-dsymutil` flag is deleted and now
subsumed by this stable flag. Additionally `-Zsplit-dwarf` is also
subsumed by this flag but still requires `-Zunstable-options` to
actually activate. The `-Csplit-debuginfo` flag takes one of
three values:

* `off` - This indicates that split-debuginfo from the final artifact is
  not desired. This is not supported on Windows and is the default on
  Unix platforms except macOS. On macOS this means that `dsymutil` is
  not executed.

* `packed` - This means that debuginfo is desired in one location
  separate from the main executable. This is the default on Windows
  (`*.pdb`) and macOS (`*.dSYM`). On other Unix platforms this subsumes
  `-Zsplit-dwarf=single` and produces a `*.dwp` file.

* `unpacked` - This means that debuginfo will be roughly equivalent to
  object files, meaning that it's throughout the build directory
  rather than in one location (often the fastest for local development).
  This is not the default on any platform and is not supported on Windows.

Each target can indicate its own default preference for how debuginfo is
handled. Almost all platforms default to `off` except for Windows and
macOS which default to `packed` for historical reasons.

Some equivalencies for previous unstable flags with the new flags are:

* `-Zrun-dsymutil=yes` -> `-Csplit-debuginfo=packed`
* `-Zrun-dsymutil=no` -> `-Csplit-debuginfo=unpacked`
* `-Zsplit-dwarf=single` -> `-Csplit-debuginfo=packed`
* `-Zsplit-dwarf=split` -> `-Csplit-debuginfo=unpacked`

Note that `-Csplit-debuginfo` still requires `-Zunstable-options` for
non-macOS platforms since split-dwarf support was *just* implemented in
rustc.

There's some more rationale listed on #79361, but the main gist of the
motivation for this commit is that `dsymutil` can take quite a long time
to execute in debug builds and provides little benefit. This means that
incremental compile times appear that much worse on macOS because the
compiler is constantly running `dsymutil` over every single binary it
produces during `cargo build` (even build scripts!). Ideally rustc would
switch to not running `dsymutil` by default, but that's a problem left
to get tackled another day.

Closes #79361

### CODE REVIEW

**Comment by bjorn3** [comment]
> off - this is the platform-specific default that platforms other
than Apple use. This defaults to whatever rustc does today, which
unfortunately does mean split-debuginfo for MSVC targets (with PDB
files), but rustc currently has no means of turning that off today.
Note, though, that if this is selected on Apple platforms and
debuginfo is enabled then the final object files are not deleted and
instead preserved on-disk (since the main executable points to them).

I think `off` should mean debuginfo included in the final linked artifact. For the macOS behavior there should be something like an `original-object` option.

**Comment by bjorn3** [comment]
To elaborate, I think there should be three modes:

* **off**: The debuginfo is included in the linked artifact. this is the default on all platforms except macOS and Windows, which don't support this.
* **packed**: The debuginfo is included in a single file/directory that is separate from the linked artifact. On macOS this would be a `.dSYM` dir. On Windows a `.pdb` file and with split dwarf, a `.dwp` file. this is the default for macOS and Windows. For non-linked crate types this is equivalent to unpacked.
* **unpacked**: The debuginfo is included in several debuginfo files separate from the linked artifact. For split dwarf this would be `.dwo` files. For macOS this would be the original object files. This requires that all the rlibs that the crate depends are not deleted.

This does bring the question of how to handle different `-Csplit-debuginfo` values for different crates.

rlib\executable/dylib|off|packed|unpacked
-|-|-|-
off|trivial|debuginfo packer could read debuginfo from rlib. it likely won't on many systems|unpacked requires all compilation artifacts to remain in place, so at runtime the debuginfo could be loaded from the object files in the rlib
packed|see unpacked|see unpacked|see unpacked
unpacked|**unsupported** as the linker can't add the debuginfo to the link artifact again as far as I know|unpacked and packed are equivalent for rlibs|trivial

**Comment by briansmith** [comment]
> This defaults to whatever rustc does today, which
unfortunately does mean split-debuginfo for MSVC targets (with PDB
files), but rustc currently has no means of turning that off today.

I don't understand why the PDB files are "unfortunate." It seems like they are actually the ideal mechanism: they separate out the debug info while avoiding the wasted work that is required in macOS's toolchain.

> There's some more rationale listed on #79361, but the main gist of the
motivation for this commit is that dsymutil can take quite a long time
to execute in debug builds and provides little benefit. This means that
incremental compile times appear that much worse on macOS because the
compiler is constantly running dsymutil over every single binary it
produces during cargo build (even build scripts!). Ideally rustc would
switch to not running dsymutil by default, but that's a problem left
to get tackled another day.

I noticed that the mechanism and the motivation don't seem well aligned. The goal is to make builds fast while retaining debug info, but the proposed mechanism is all about where to place the debug info, regardless of performance. It seems likely that in the future different toolchains will evolve so that the fastest thing to do varies by target and/or toolchain. So it seems like there should be a way to say `-Cput-debuginfo-wherever-results-in-the-fastest-build` (with a better name), and it doesn't seem like any other values are necessary.

**Comment by bjorn3** [comment]
The three modes of `-Csplit-debuginfo` each serve a different purpose. `off` ensures that you always have the debuginfo when you have the executable. This comes at the cost of a bigger executable. `packed` results in a smaller executable, but requires you to copy the debuginfo file in addition to the executable when you want to have debuginfo. `unpacked` results in the fastest possible link time, but you can't delete any of the compilation artifacts if you want to have debuginfo.

**Comment by alexcrichton** [comment]
@bjorn3 ah yeah those three modes sound reasonable to me! It would be easy to say that "off" isn't supported on Windows and macOS and it just defaults to "packed". I'm trying to interpret your table though and am having confusion, should one of the row or column headers be crate types? (not sure how to decipher the crate types only mentioned in the corner and having a matrix of debuginfo type x debuginfo type)

@briansmith ah by "unfortunate" I mean that as proposed if you say `-Csplit-debuginfo=off` you get split debuginfo on Windows, which is weird. I don't mean to try to pass a value judgment on the usefulness of MSVC's PDB splitting. I think it's a good point is that the defaults ideally are "build me the fastest" but given the interaction of debuginfo with other tooling it's not quite as straightforward. For example Rust's RUST_BACKTRACE support until just recently didn't support debuginfo-in-object-files on macOS (and still doesn't on Linux). That's just libstd's own support and depending on the tooling that Rust artifacts are integrated with I'd imagine that a specific strategy would be relied upon. If a project relied on whatever `-Cput-debuginfo-wherever-results-in-the-fastest-build` happened to do when it was implemented and then we changed it, we still run the risk of breaking projects.

It's still an open question how this is going to get integrated into Cargo. I would ideally like to turn this on by default but there are backwards compatibility concerns.

**Comment by bjorn3** [comment]
> I'm trying to interpret your table though and am having confusion

A row represents the `-Csplit-debuginfo` value for a dependency. A column represents the `-Csplit-debuginfo` value for the crate that is being linked.

**Comment by alexcrichton** [comment]
@bjorn3 from a theoretical perspective we'd have to handle those various combinations for dependencies and the final executable but I'm not sure those situations come up in practice? If you're linking to a dylib then the compiler doesn't really worry itself with the debuginfo for that dylib itself as that's the responsibility of the dylib itself.

The only case it really matters is with an rlib (an archive) since those objects are being used in the final artifact. For rlibs, however, it seems like they're compiled some way and we'd just try to be compatible with it? I guess I don't really understand why we need to consider mixing and matching different modes with dependencies, since that seems like a linker or toolchain thing to worry about and rustc is just respecting what the user asked for. It may also mean that each option means different things on different platforms?

I think it seems reasonable to have a tri-state as you're proposing, but I can't seem to wrap my head around the "packed" and "unpacked" terminology, I get confused every time I think about it. I like how it's platform-agnostic, though, and we avoid the term "dsymutil" in a cli option ideally.

I think we're basically trying to find names for:

|   | **off** | **packed** | **unpacked** |
|---|---|---|---|
| Linux | *default* | `*.dwp` file on link | `*.dwo` files everywhere |
| macOS | no `dsymutil`, no objects saved | *default* (`*.dSYM`) | `-Zrun-dsymutil=no` equivalent |
| MSVC | no pdb from the linker | *default* (`*.pdb`) | not supported |

(I'm not actually sure if MinGW supports split-debuginfo in the same way as Linux since it's DWARF, but I would presume so)

What if "packed" were changed to "on" and "unpacked" were changed to "objects"?

**Comment by bjorn3** [comment]
> from a theoretical perspective we'd have to handle those various combinations for dependencies and the final executable but I'm not sure those situations come up in practice?

Maybe not, but it should be handled in some way. Even if just by giving a warning that debuginfo is unavailable or straight up error.

> If you're linking to a dylib then the compiler doesn't really worry itself with the debuginfo for that dylib itself as that's the responsibility of the dylib itself.

Correct

> The only case it really matters is with an rlib (an archive) since those objects are being used in the final artifact. For rlibs, however, it seems like they're compiled some way and we'd just try to be compatible with it? I guess I don't really understand why we need to consider mixing and matching different modes with dependencies, since that seems like a linker or toolchain thing to worry about and rustc is just respecting what the user asked for. It may also mean that each option means different things on different platforms?

Rlibs include the debuginfo in a way that would be compatible with linking them using a certain `-Csplit-debuginfo`. On macOS and I think Windows that would be always including the debuginfo in the object files. On Linux that would be including it in the object files for `-Csplit-debuginfo=off`. For `-Csplit-debuginfo=packed/unpacked`, that would be as separate `.dwo` files. During the linking step the debuginfo would then be stored in the appropriate place. If `.dwo` files are generated, but `-Csplit-debuginfo=no` is used for the linked artifact, it would be necessary to stuff the `.dwo` files into the final artifact. To the best of my knowledge no linker allows this and as such rustc shouldn't allow this combination either. The other way around would require extracting `.dwo`/`.dwp` files from the rlib object files, which no toolchain supports either I think, but should be easier to do using something like gimli. I propose that this combination will also be forbidden. Combining `unpacked` and `packed` would work just fine as either way `.dwo` files are included in the rlib on Linux and the debuginfo would be stored in the object files on macOS and I think Windows.

> I think it seems reasonable to have a tri-state as you're proposing, but I can't seem to wrap my head around the "packed" and "unpacked" terminology, I get confused every time I think about it. I like how it's platform-agnostic, though, and we avoid the term "dsymutil" in a cli option ideally.

Packed means that all debuginfo for the linked artifact is packed together in a single place. Unpacked means that the debuginfo is scattered all over the place.

For macOS and Windows `off` should be unsupported as `off` means that the debuginfo is included in the linked artifact. This is unsupported on these platforms.

> What if "packed" were changed to "on" and "unpacked" were changed to "objects"?

`unpacked` wouldn't necessarily mean that it is stored in object files. In fact I think it should be allowed to store the debuginfo basically anywhere including for example a database at a fixed location with an index based on the full path of the executable or dylib.

**Comment by alexcrichton** [comment]
Sorry I don't really understand what you're asking for about warnings and dealing with mixed split-debuginfo states in dependencies. We don't do any warning or anyhing really with mixed values of debuginfo in dependencies, so why would we do anything with relation to split-debuginfo? Practically this is unlikely to ever really matter since the only "split" is whatever libstd does and what your local build does, and we don't ever want to warn folks about what libstd is doing since you wouldn't be able to silence it.

I still feel that "packed" and "unpacked" aren't the right terms for this, however. I think "on" and "off" are good terms for "in the executable" or "everything next to the executable" (sorry I keep confusing =off as "turn off debuginfo" whereas it's actually "put it all in one place in the executable"). The only other thing is "put it somewhere else that doesn't require assembling into one thing" and while it may not literally be in an object file I feel like `*.dwo` is similar enough to "object" that "=objects" would be good enough.

In any case though, what would the next steps for this be? I think it's an FCP, right? Could that perhaps be started to see if others have thoughts on this as well?

**Comment by bjorn3** [comment]
> We don't do any warning or anyhing really with mixed values of debuginfo in dependencies, so why would we do anything with relation to split-debuginfo?

Because mixing `-Csplit-debuginfo` could cause the debuginfo for crates that should include debuginfo to become unavailable. When mixing values of `-Cdebuginfo`, you explicitly state for which crates you want debuginfo to be available.

> I still feel that "packed" and "unpacked" aren't the right terms for this, however. I think "on" and "off" are good terms for "in the executable" or "everything next to the executable" (sorry I keep confusing =off as "turn off debuginfo" whereas it's actually "put it all in one place in the executable"). The only other thing is "put it somewhere else that doesn't require assembling into one thing" and while it may not literally be in an object file I feel like *.dwo is similar enough to "object" that "=objects" would be good enough.

`-Csplit-debuginfo=objects` to me doesn't say that you can't really remove the target dir without debuginfo becoming unavailable. There is no way to tell the build system what files contain the debuginfo. Cargo uses `rustc --crate-name ___ --print file-names` to get determine how to get the file names of all output artifacts. This only allows a fixed amount of file names.

**Comment by bjorn3** [comment]
> In any case though, what would the next steps for this be? I think it's an FCP, right?

Makes sense

> Could that perhaps be started to see if others have thoughts on this as well?

I don't really know what the procedure for this is.

**Comment by alexcrichton** [comment]
I would consider the availability of debuginfo the toolchain's or tool's issue. If debuginfo is somewhere but can't be loaded then it's either the tool's fault because it isn't reading what the compiler is emitting or it's the compiler's issue because it's not emitting information to find the debuginfo.

Yes it's currently an issue where the object files aren't considered outputs of a compilation. I don't think it's quite right to say that a variable number of ouputs isn't supported, the dep-info file can list all the files necessary.

I'm also not sure how to kick off FCP nowadays, how would one learn this?

**Comment by bjorn3** [comment]
> I would consider the availability of debuginfo the toolchain's or tool's issue. If debuginfo is somewhere but can't be loaded then it's either the tool's fault because it isn't reading what the compiler is emitting or it's the compiler's issue because it's not emitting information to find the debuginfo.

The build system is also in part responsible as it is responsible for managing all compilation artifacts.

> Yes it's currently an issue where the object files aren't considered outputs of a compilation. I don't think it's quite right to say that a variable number of ouputs isn't supported, the dep-info file can list all the files necessary.

The dep-info file is only used by cargo for getting the build inputs and not outputs as far as I know. Also the dep-info files don't clearly separate inputs from outputs without any dependencies, as inputs also get an output entry to silence a warning/error from make when an input file gets deleted. Nor do they say what kind of output a file is.

> I'm also not sure how to kick off FCP nowadays, how would one learn this?

Found the documentation: https://github.com/rust-lang/rfcbot-rs

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

It seems like there's still some bikeshedding about the proper term, but I'd like to kick off an FCP for the this stabilization. This seems like a really useful step forward to me!

**Comment by wesleywiser** [comment]
I like the packed/unpacked terminology but I'm happy to defer to others on the naming.

**Comment by alexcrichton** [comment]
Sorry @bjorn3 I'm sort of lost and confused, are you bringing up blocking objections you'd like to see resolved? I know the specific names of things here are being bikeshedded, but it's not clear to me whether you want to require implementing logic about mixed split-debuginfo values or handling output names in this PR before this feature is stabilized.

**Comment by bjorn3** [comment]
I would like to at least get a warning when mixing incompatible `-Csplit-debuginfo` levels. (That is linking with `-Csplit-debuginfo=off` when any dependency was compiled with a different value) Handling output names can be done later.

**Comment by alexcrichton** [comment]
Ok that makes sense. I tried to [respond to that above](https://github.com/rust-lang/rust/pull/79570#issuecomment-740023624) but I don't really understand how your responses line up. I mentioned that debuginfo is the toolchain or tool's issue and you responded that it's the build system's issue. I'm not sure if you're agreeing or disagreeing with me?

If a dependency is compiled with split-debuginfo=unpacked and the final executable is split-debuginfo=off, then why would rustc warn about that? That was chosen by the build system and may have been selected for performance reasons. If a debugger can't find the debuginfo that's a problem, but if all the pointers in place why should rustc warn about this situation?

To me warnings are "this is wrong all the time but not bad enough to halt compilation", where the "all the time" is important in that a warning should always be actionable. I don't know why mixing values of split-debuginfo are such that they should *require* action on behalf of a user to figure out what to do.

**Comment by bjorn3** [comment]
> I mentioned that debuginfo is the toolchain or tool's issue and you responded that it's the build system's issue. I'm not sure if you're agreeing or disagreeing with me?

The toolchain and tool have to agree how to store it, but the build system has to copy it around as necessary. It is the shared responsibility of everyone.

> If a dependency is compiled with split-debuginfo=unpacked and the final executable is split-debuginfo=off, then why would rustc warn about that? That was chosen by the build system and may have been selected for performance reasons. If a debugger can't find the debuginfo that's a problem, but if all the pointers in place why should rustc warn about this situation?

`-Csplit-debuginfo=no` means that all debuginfo must be part of the linked artifact. Rustc shouldn't silently drop debuginfo when it can't do this. That would be very confusing for users. That combination can't have been chosen for the build system as `-Csplit-debuginfo=no` when linking us the slowest option.

> To me warnings are "this is wrong all the time but not bad enough to halt compilation", where the "all the time" is important in that a warning should always be actionable. I don't know why mixing values of split-debuginfo are such that they should require action on behalf of a user to figure out what to do.

It can be fixed by always using `-Csplit-debuginfo=no`. Not having debuginfo when it was requested using `-Cdebuginfo` is just wrong.

**Comment by alexcrichton** [comment]
Sorry I'm still not sure what you're saying about build systems. I don't disagree with what you're saying but I don't understand its relevance to mixing `split-debuginfo` values.

I don't agree with your conclusion about `-Csplit-debuginfo=no`, though. If I write `-g` for the final artifact that's not interpreted as "add debuginfo for the whole program" but instead just the final artifact. Similarly `-Csplit-debuginfo`, and all other codegen flags, only applies to the final artifact. If an intermediate artifact was compiled with split debug information then the final artifact should just reference that. 

An example of this is that we're probably not going to split-debuginfor for libstd any time soon. This means that your final artifact is going to have libstd's debuginfo if you bring it in, even if you say `-Csplit-debuginfo=unpacked` on Linux (I think at least). We definitely shouldn't warn about what happens with libstd by default.

In general I'm not disagreeing that it *can* be confusing, but I don't think it's the place of rustc to generate a warning about it. Whomever configures the toolchain/build system needs to be cognizant of any nonstandard choices made and how they interact.

I'm not sure why you're mentioning why not having debuginfo when it was requested is wrong. I agree with that but I don't understand how it appliess to split-debuginfo. In what situation if you requested debuginfo would it not actually show up? (being concrete would be really helpful here, I get the impression we're not understanding each other and talking past each other)

**Comment by bjorn3** [comment]
I am not suggesting to warn when combining `-Csplit-debuginfo=no` for a dependency with another value for the linked artifact. Including sone debuginfo in the linked artifact anyway is a sane choice. I am suggesting to warn about `-Csplit-debuginfo=packed` for a dependency with `-Csplit-debuginfo=no` for the linked artifact as in that case the debuginfo of the dependency will be included in the rlib, which has an unstable format. (it is currently an ar archive, but there may be reasons in the future to switch to a different format) This would mean that the debuginfo may not be accessible by the debugger. This would also happen when using `-Csplit-debuginfo=unpacked` for everything, but in that case I think it is less of a problem as it is more of a "do whatever you need to make it link fast" with less stability guarantees and more freedom for the compiler than the other options. At least in my opinion.

As far as I know rustc guarantees that debuginfo is available when using `-Cdebuginfo`, but just doesn't guarantee exactly how much detail and how certain things are encoded in thr native debuginfo format when there are multiple options.

**Comment by alexcrichton** [comment]
The case you're describing we should warn about, I think that's exactly how we're distributing libstd and recommending to use this feature? The standard library is effectively build with `-Csplit-debuginfo=no` because its objects include debuginfo in the objects themselves. The macOS default of `-Cdebuginfo=packed` doesn't warn today and shouldn't warn in the future about this?

In some sense though `-Csplit-debuginfo` for  rlibs only has meaning on Linux, on all other platforms it's irrelevant what you do for rlibs.

**Comment by bjorn3** [comment]
> I think that's exactly how we're distributing libstd and recommending to use this feature?

I am suggesting about warning when a dependency does **not** use `-Csplit-debuginfo=no`, aka it uses `-Csplit-debuginfo=(un)packed` but the linked artifact is compiled with `-Csplit-debuginfo=no`.

> In some sense though -Csplit-debuginfo for rlibs only has meaning on Linux, on all other platforms it's irrelevant what you do for rlibs.

I think it has a meaning for all platforms that use DWARF split debuginfo. Windows uses PDB and macOS their own way of split debuginfo. BSD platforms likely use DWARF split debuginfo too.

**Comment by alexcrichton** [comment]
I still don't understand why rustc would issue a warning there. I don't understand how this is different from any other crate-specific codegen option. No option AFAIK warns you "an upstream crate is different you may want to consider this". Additionally I don't think there's any code implementing split-dwarf in rustc today? So how would I implement this warning for a feature that doesn't exist? Do we know what would actually happen in the situation you're describing, and does it not actually work?

**Comment by bjorn3** [comment]
> Additionally I don't think there's any code implementing split-dwarf in rustc today? So how would I implement this warning for a feature that doesn't exist?

Correct. This can't be implemented yet.

> I still don't understand why rustc would issue a warning there. I don't understand how this is different from any other crate-specific codegen option.

I wanted a warning to prevent confusing behavior when mixing different `-Csplit-debuginfo` values. I guess this is unlikely enough to happen and the effects are small enough that it isn't that important to warn about it.

**Comment by alexcrichton** [comment]
While the FCP stews, the merging of #77117 (split dwarf support) now raises an interesting question. Should that be tied into this option? Doing so would effectively stabilize split dwarf, but otherwise there would be two options `-Csplit-debuginfo` and `-Zsplit-dwarf` temporarily which may not work as expected. The packed/unpacked/off terminology maps well to the split-dwarf implementation (which isn't really a coincidence), so it would be easy to move over `-Zsplit-dwarf` into `-Csplit-debuginfo` here if desired.

I'm basically just curious how to resolve the merge conflict with #77117 since it seems related.

**Comment by bjorn3** [comment]
Yeah, they should be tied to the same option I think. You could have `-Csplit-debuginfo` require `-Zunstable-options` on everything but macOS, but that seems like a bit of a hack.

**Comment by nagisa** [comment]
> that seems like a bit of a hack.

I think it'd be good enough. We already have some non-`-Z` flags gated by `-Zunstable-options`, and its the “usual” way to access unstable CLI.

**Comment by pnkfelix** [comment]
(I interpret the "hack" there being the host-dependent semantics of whether it would be guarded by `-Z unstable-options` or not)

**Comment by alexcrichton** [comment]
Ok I have rebased this, implemented packed/unpacked/off, deleted `-Zsplit-dwarf` by folding it into `-Csplit-debuginfo`, and gated `-Csplit-debuginfo={packed,unpacked}` on non-macOS platforms.

File: compiler/rustc_interface/src/tests.rs [hunk 1]
```diff
@@ -446,6 +446,7 @@ fn test_codegen_options_tracking_hash() {
     tracked!(profile_use, Some(PathBuf::from("abc")));
     tracked!(relocation_model, Some(RelocModel::Pic));
     tracked!(soft_float, true);
+    tracked!(split_debuginfo, Some(SplitDebuginfo::Dsymutil));
```
Comment (bjorn3) [inline compiler/rustc_interface/src/tests.rs:449]: This variant doesn't exist anymore.

File: src/bootstrap/builder.rs [hunk 2]
```diff
@@ -1129,10 +1129,18 @@ impl<'a> Builder<'a> {
...
-                rustflags.arg("-Zrun-dsymutil=yes");
+            if stage == 0 {
+                if self.config.rust_run_dsymutil {
+                    rustflags.arg("-Zrun-dsymutil=yes");
+                } else {
+                    rustflags.arg("-Zrun-dsymutil=no");
+                }
             } else {
-                rustflags.arg("-Zrun-dsymutil=no");
+                if self.config.rust_run_dsymutil {
```
Comment (bjorn3) [inline src/bootstrap/builder.rs:1139]: Can this option be renamed? Also it would now be possible to ship rustc debuginfo as rustup component.

**Comment by bjorn3** [comment]
Can you remove the unrelated reformatting? Also please update the commit message.

File: src/bootstrap/builder.rs (hunk 2 above)
Comment (alexcrichton) [reply src/bootstrap/builder.rs:1139]: My desired change of "I want my macOS build to be faster" has already snowballed into "I'm responsible for designing how to stabilize split-dwarf debuginfo" and a lot of other changes. I would rather not take on more responsibility in this PR for changing Rust's build system as well.

**Comment by petrochenkov** [comment]
The description in top comment and in `src/doc/rustc/src/codegen-options/index.md` says "Windows", but means "Windows/MSVC" specifically, on Windows/GNU debuginfo seems to be kept in COFF sections, similarly to ELF-based targets.

**Comment by alexcrichton** [comment]
Ah yes good catch, I've clarified those sections hopefully now. I'm not really sure if split-dwarf works at all on MinGW platforms, but I figure that's a question best left for a future stabilization.

File: compiler/rustc_session/src/config.rs [hunk 3]
```diff
@@ -1890,6 +1873,15 @@ pub fn build_session_options(matches: &getopts::Matches) -> Options {
 
     let pretty = parse_pretty(matches, &debugging_opts, error_format);
 
+    if !debugging_opts.unstable_options
+        && !target_triple.triple().contains("darwin")
```
Comment (bjorn3) [inline compiler/rustc_session/src/config.rs:1877]: Are custom target specs stable? Combined with `-Zbuild-std` once it becomes stable would allow faking macOS for thevpurpose of this check, while actually building for another target.

File: compiler/rustc_session/src/options.rs [hunk 4]
```diff
@@ -722,6 +710,15 @@ macro_rules! options {
                 None => false,
             }
         }
+
+        fn parse_split_debuginfo(slot: &mut Option<SplitDebuginfo>, v: Option<&str>) -> bool {
+            match v.and_then(|s| SplitDebuginfo::from_str(s).ok()) {
```
Comment (bjorn3) [inline compiler/rustc_session/src/options.rs:715]: This will ignore any parse errors.

File: compiler/rustc_target/src/spec/mod.rs [hunk 5]
```diff
@@ -442,6 +442,69 @@ impl fmt::Display for LinkOutputKind {
...
 pub type LinkArgs = BTreeMap<LinkerFlavor, Vec<String>>;
 
+#[derive(Clone, Copy, Hash, Debug, PartialEq, Eq)]
+pub enum SplitDebuginfo {
+    /// Split debug-information is disabled, meaning that on supported platforms
+    /// you can find all debug information in the executable itself. This is
+    /// only supported for ELF effectively.
+    ///
+    /// * Windows - not supported
+    /// * macOS - don't run `dsymutil`
```
Comment (bjorn3) [inline compiler/rustc_target/src/spec/mod.rs:452]: That would be equivalent to unpacked except for not preserving the necessary object files.

File: src/test/run-make-fulldeps/split-debuginfo/Makefile [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+	[ -d $(TMPDIR)/foo.dSYM ]
+	rm -rf $(TMPDIR)/*.dSYM
+	$(RUSTC) foo.rs -g -C split-debuginfo=packed
+	[ -d $(TMPDIR)/foo.dSYM ]
+	rm -rf $(TMPDIR)/*.dSYM
+
+# Object files are preserved with unpacked and `dsymutil` isn't run
+unpacked:
+	$(RUSTC) foo.rs -g -C split-debuginfo=unpacked
+	ls $(TMPDIR)/*.o
```
Comment (bjorn3) [inline src/test/run-make-fulldeps/split-debuginfo/Makefile:28]: Does this exist with an error code when no object files could be found?

File: compiler/rustc_session/src/config.rs (hunk 3 above)
Comment (alexcrichton) [reply compiler/rustc_session/src/config.rs:1877]: Do you have a proposed alternative for how to change this?

File: src/test/run-make-fulldeps/split-debuginfo/Makefile (hunk 6 above)
Comment (alexcrichton) [reply src/test/run-make-fulldeps/split-debuginfo/Makefile:28]: Yes

File: compiler/rustc_session/src/options.rs (hunk 4 above)
Comment (alexcrichton) [reply compiler/rustc_session/src/options.rs:715]: This does what other parsing functions do in this file.

File: compiler/rustc_session/src/config.rs (hunk 3 above)
Comment (bjorn3) [reply compiler/rustc_session/src/config.rs:1877]: Maybe the llvm target could be checked instead? That will ensure that at the very least the object file format is Mach-O, for which macOS is pretty much the only OS that supports it.

**Comment by alexcrichton** [comment]
@eddyb, @estebank, or @matthewjasper, would y'all mind taking a look at the [FCP proposal above](https://github.com/rust-lang/rust/pull/79570#issuecomment-740257153)?

**Comment by alexcrichton** [comment]
Was there any other change folks wanted to the code here?

**Comment by bjorn3** [comment]
Can you do https://github.com/rust-lang/rust/pull/79570#discussion_r554080423?

File: compiler/rustc_session/src/config.rs (hunk 3 above)
Comment (alexcrichton) [reply compiler/rustc_session/src/config.rs:1883]: Is this really worth pursuing at this point? Everything about custom target specs is pseudo-unstable anyway and I'm not sure if this information is otherwise trivially accessible at this point. This is just a temporary workaround anyway until split-debuginfo is implemented and vetted on other platforms.

Comment (bjorn3) [reply compiler/rustc_session/src/config.rs:1883]: I am fine with leaving this as is then.

**Comment by jonas-schievink** [comment]
@bors r- failed in https://github.com/rust-lang/rust/pull/81390#issuecomment-767051345

Looks like you have to move the UI test into a subdirectory

**Comment by alexcrichton** [comment]
The new tests belongs with the other `backtrace-*.rs` tests in that directory which haven't moved so I've increased the limit there to include this test. Presumably when the other tests move this one will move as well.

@bors: r=bjorn3

**Comment by JohnTitor** [comment]
Failed in rollup (https://github.com/rust-lang-ci/rust/runs/1771243207):
```
error: failed to run `rustc` to learn about target-specific information
failed to run: /Users/runner/work/rust/rust/build/bootstrap/debug/bootstrap dist

Build completed unsuccessfully in 1:33:49
Caused by:
== clock drift check ==
  process didn't exit successfully: `/Users/runner/work/rust/rust/build/bootstrap/debug/rustc - --crate-name ___ --print=file-names -Zmacro-backtrace -Zosx-rpath-install-name '-Clink-args=-Wl,-rpath,@loader_path/../lib' -Csplit-debuginfo=unpacked -Zsave-analysis -Cprefer-dynamic -Cembed-bitcode=yes --target aarch64-apple-ios --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  local time: Tue Jan 26 19:35:44 UTC 2021
  --- stderr
  error: `-Csplit-debuginfo` is unstable on this platform

  [RUSTC-TIMING] ___ test:false 0.021
command did not execute successfully: "/Users/runner/work/rust/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "aarch64-apple-ios" "-Zbinary-dep-depinfo" "-j" "3" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace profiler compiler-builtins-c" "--manifest-path" "/Users/runner/work/rust/rust/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
```

@bors r-

**Comment by alexcrichton** [comment]
I've [posted about this on internals](https://internals.rust-lang.org/t/help-test-faster-incremental-debug-macos-builds-on-nightly/14016) for the next step hopefully in turning this on by default for Cargo users.

File: src/bootstrap/builder.rs [hunk 7]
```diff
@@ -1139,10 +1139,18 @@ impl<'a> Builder<'a> {
...
         // See https://github.com/rust-lang/rust/issues/79361 for more info on this flag.
         if target.contains("apple") {
-            if self.config.rust_run_dsymutil {
-                rustflags.arg("-Zrun-dsymutil=yes");
+            if stage == 0 {
+                if self.config.rust_run_dsymutil {
+                    rustflags.arg("-Zrun-dsymutil=yes");
+                } else {
+                    rustflags.arg("-Zrun-dsymutil=no");
+                }
```
Comment (jyn514) [inline src/bootstrap/builder.rs:1147]: FYI, it would be helpful next time to add `// cfg(bootstrap)` as a comment, this caused a failure that wasn't caught until testing on Mac: https://github.com/rust-lang/rust/pull/82076#issuecomment-780253845

**Comment by luser** [comment]
> * `unpacked` - This means that debuginfo will be roughly equivalent to
>   object files, meaning that it's throughout the build directory
>   rather than in one location (often the fastest for local development).
>   This is not the default on any platform and is not supported on Windows.

I know this is an old PR but I was catching up on this and I wanted to note that there *are* two MSVC features that are related and could potentially be lumped under this feature:

* `link.exe` supports a [`/DEBUG:FASTLINK`](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-160) option, which makes it operate roughly the same as Apple's `ld` without running `dsymutil`: it produces a simple PDB during the link that is just an index to the debug info contained in the PDB files for each compilation unit. It comes with quite a few caveats, several of which are detailed [in this LLVM blog post](http://blog.llvm.org/2018/01/improving-link-time-on-windows-with.html).
* `cl.exe` supports a [`/Z7`](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-160) option to include debug info directly in the generated `.obj` file instead of in a `.pdb` file. The linker can still produce a `.pdb` file from this debug info during linking. While I was at Mozilla we made the Firefox build use this option because it plays nicer with `sccache` caching. (I admit I don't know where debug info for `.rlib` compilation on Windows winds up currently. In a PDB next to the rlib? Inside the rlib?)

**Comment by bjorn3** [comment]
> I admit I don't know where debug info for .rlib compilation on Windows winds up currently. In a PDB next to the rlib? Inside the rlib?

AFAIK inside the object files inside an rlib.
