### PR TITLE
Reject unsupported `extern "{abi}"`s consistently in all positions

### LINKED ISSUE #86232: The `check_abi` function in typeck is not called for ABIs in trait declarations
Consider the following code:

```rs
trait T {
    extern "amdgpu-kernel" fn mu();
}

type TAU = extern "amdgpu-kernel" fn();
```

The `check_abi` function… 

https://github.com/rust-lang/rust/blob/0a8629bff642c3c3b84bb644c0099194f063b627/compiler/rustc_typeck/src/check/check.rs#L37-L59

… is not called for the following two ABI lines, meaning that the checks present therein do not activate, potentially allowing circumvention of the checks this function implements. In particular one thing that is allowed is taking the `TAU` function pointer as an argument and calling it on architectures where this ABI is unsupported.

This becomes especially relevant after #86231 lands.

### LINKED ISSUE #132430: ICE: `internal compiler error[E0391]: cycle detected when computing function signature of impl`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2018 --crate-type=lib
#![feature(cmse_nonsecure_entry)]
struct Test;

impl Test {
    pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
}

````

original:
````rust
struct Test;

impl Test {
    pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {

    }
}

````

Version information
````
rustc 1.84.0-nightly (a0d98ff0e 2024-10-31)
binary: rustc
commit-hash: a0d98ff0e5b6e1f2c63fd26f68484792621b235c
commit-date: 2024-10-31
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(cmse_nonsecure_entry) --edition=2018 --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: struct `Test` is never constructed
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:1:8
  |
1 | struct Test;
  |        ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: associated function `test` is never used
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:57
  |
3 | impl Test {
  | --------- associated function in this implementation
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |                                                         ^^^^

warning: `extern` fn uses type `str`, which is not FFI-safe
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:67
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |                                                                   ^^^^ not FFI-safe
  |
  = help: consider using `*const u8` and a length instead
  = note: string slices have no C equivalent
  = note: `#[warn(improper_ctypes_definitions)]` on by default

warning: `extern` fn uses type `impl Future<Output = ()>`, which is not FFI-safe
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
  |
  = note: opaque types have no C equivalent

warning: 4 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error[E0391]: cycle detected when computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
  = note: ...which requires normalizing `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
note: ...which requires computing type of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing the opaque types defined by `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`, completing the cycle
note: cycle used when checking that `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` is well-formed
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:596:16 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
  = note: ...which requires normalizing `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
note: ...which requires computing type of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`, completing the cycle
note: cycle used when checking that `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` is well-formed
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:596:16 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
  = note: ...which requires normalizing `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
note: ...which requires computing type of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` contains FFI-unwind calls...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`, completing the cycle
note: cycle used when checking that `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` is well-formed
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:596:16 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error[E0391]: cycle detected when computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which requires computing layout of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
  = note: ...which requires normalizing `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
note: ...which requires computing type of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of opaque `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test::{opaque#0}`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires borrow-checking `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` contains FFI-unwind calls...
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires computing function signature of `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test`, completing the cycle
note: cycle used when checking that `<impl at /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:3:1: 3:10>::test` is well-formed
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
note: delayed at compiler/rustc_query_system/src/query/job.rs:596:16 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.q2k4BBLCKuN9/rustc_testrunner_tmpdir_reporting.5aASWsrfzxJL/mvce.rs:4:5
  |
4 |     pub async unsafe extern "C-cmse-nonsecure-entry" fn test(val: &str) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.84.0-nightly (a0d98ff0e 2024-10-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(cmse_nonsecure_entry) --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-cmse_nonsecure_entry

### LINKED ISSUE #138738: ICE: `Architecture x86_64 does not support GpuKernel calling convention`
auto-reduced (treereduce-rust):
````rust
#![feature(abi_ptx)]
fn main() {
    let non_secure_function = unsafe {
        core::mem::transmute::<usize, extern "ptx-kernel" fn(i32, i32, i32, i32) -> i32>(0x10000004)
    };
    let mut toto = 5;
    toto += non_secure_function(toto, 2, 3, 5);
}

````

original:
````rust
// gate-test-abi_c_cmse_nonsecure_call
#[allow(unsupported_fn_ptr_calling_conventions)]
fn main() {
    let non_secure_function = unsafe {
        core::mem::transmute::<usize, extern "ptx-kernel" fn(i32, i32, i32, i32) -> i32>(
            //~^ ERROR [E0658]
            0x10000004,
        )
    };
    let mut toto = 5;
    toto += non_secure_function(toto, 2, 3, 5);
}

````

Version information
````
rustc 1.87.0-nightly (70237a8cb 2025-03-20)
binary: rustc
commit-hash: 70237a8cb905fc48ed6148d2f2dba756535a5940
commit-date: 2025-03-20
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/70237a8cb905fc48ed6148d2f2dba756535a5940/compiler/rustc_codegen_llvm/src/abi.rs#L674-L686

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(abi_ptx)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the calling convention "ptx-kernel" is not supported on this target
 --> /tmp/icemaker_global_tempdir.5RiKb1aS18Mo/rustc_testrunner_tmpdir_reporting.vC9uw8ssapd6/mvce.rs:3:39
  |
3 |         core::mem::transmute::<usize, extern "ptx-kernel" fn(i32, i32, i32, i32) -> i32>(0x10000004)
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #130260 <https://github.com/rust-lang/rust/issues/130260>
  = note: `#[warn(unsupported_fn_ptr_calling_conventions)]` on by default

warning: value assigned to `toto` is never read
 --> /tmp/icemaker_global_tempdir.5RiKb1aS18Mo/rustc_testrunner_tmpdir_reporting.vC9uw8ssapd6/mvce.rs:6:5
  |
6 |     toto += non_secure_function(toto, 2, 3, 5);
  |     ^^^^
  |
  = help: maybe it is overwritten before being read?
  = note: `#[warn(unused_assignments)]` on by default


thread 'rustc' panicked at compiler/rustc_codegen_llvm/src/abi.rs:680:21:
Architecture x86_64 does not support GpuKernel calling convention
stack backtrace:
   0:     0x79ada6830003 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h879fffc75fdea4ca
   1:     0x79ada7005a58 - core::fmt::write::h4872d0510b46ecc6
   2:     0x79ada83c5751 - std::io::Write::write_fmt::hbd981463303fde9c
   3:     0x79ada682fe62 - std::sys::backtrace::BacktraceLock::print::hcf9aac352b7eac82
   4:     0x79ada683271a - std::panicking::default_hook::{{closure}}::hedab5cca755b9743
   5:     0x79ada683229f - std::panicking::default_hook::h1fcdc03d8389a618
   6:     0x79ada589bf20 - std[c9702a20cd481928]::panicking::update_hook::<alloc[49ba14cf04ef8a65]::boxed::Box<rustc_driver_impl[8a35e1c27f9e238f]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x79ada6832f93 - std::panicking::rust_panic_with_hook::ha0e51fe2d11054e2
   8:     0x79ada6832c8a - std::panicking::begin_panic_handler::{{closure}}::hc5cbb737c532592b
   9:     0x79ada68304d9 - std::sys::backtrace::__rust_end_short_backtrace::hf92f52b58bf43613
  10:     0x79ada683294d - __rustc[bd409a3545e2ef9f]::rust_begin_unwind
  11:     0x79ada326b750 - core::panicking::panic_fmt::hfabf34321fa7b35b
  12:     0x79ada72be178 - <rustc_target[4ee8a907d88b8e02]::callconv::FnAbi<rustc_middle[d57d21cb3f97984b]::ty::Ty> as rustc_codegen_llvm[3ffc3f5f98c79521]::abi::FnAbiLlvmExt>::apply_attrs_callsite
  13:     0x79ada72bbcbf - <rustc_codegen_llvm[3ffc3f5f98c79521]::builder::GenericBuilder<rustc_codegen_llvm[3ffc3f5f98c79521]::context::FullCx> as rustc_codegen_ssa[91b4b525e278393]::traits::builder::BuilderMethods>::call
  14:     0x79ada72b521c - <rustc_codegen_ssa[91b4b525e278393]::mir::block::TerminatorCodegenHelper>::do_call::<rustc_codegen_llvm[3ffc3f5f98c79521]::builder::GenericBuilder<rustc_codegen_llvm[3ffc3f5f98c79521]::context::FullCx>>
  15:     0x79ada3f29b53 - <rustc_codegen_ssa[91b4b525e278393]::mir::FunctionCx<rustc_codegen_llvm[3ffc3f5f98c79521]::builder::GenericBuilder<rustc_codegen_llvm[3ffc3f5f98c79521]::context::FullCx>>>::codegen_terminator
  16:     0x79ada80b87a9 - rustc_codegen_ssa[91b4b525e278393]::mir::codegen_mir::<rustc_codegen_llvm[3ffc3f5f98c79521]::builder::GenericBuilder<rustc_codegen_llvm[3ffc3f5f98c79521]::context::FullCx>>
  17:     0x79ada809c351 - rustc_codegen_llvm[3ffc3f5f98c79521]::base::compile_codegen_unit::module_codegen
  18:     0x79ada8165995 - <rustc_codegen_llvm[3ffc3f5f98c79521]::LlvmCodegenBackend as rustc_codegen_ssa[91b4b525e278393]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  19:     0x79ada81622d7 - <rustc_codegen_llvm[3ffc3f5f98c79521]::LlvmCodegenBackend as rustc_codegen_ssa[91b4b525e278393]::traits::backend::CodegenBackend>::codegen_crate
  20:     0x79ada8191405 - <rustc_interface[1dd91e2665f7489c]::queries::Linker>::codegen_and_build_linker
  21:     0x79ada818ecb0 - rustc_interface[1dd91e2665f7489c]::passes::create_and_enter_global_ctxt::<core[fb772cbc65c9782a]::option::Option<rustc_interface[1dd91e2665f7489c]::queries::Linker>, rustc_driver_impl[8a35e1c27f9e238f]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  22:     0x79ada813fcaf - rustc_interface[1dd91e2665f7489c]::interface::run_compiler::<(), rustc_driver_impl[8a35e1c27f9e238f]::run_compiler::{closure#0}>::{closure#1}
  23:     0x79ada7fbbfc8 - std[c9702a20cd481928]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1dd91e2665f7489c]::util::run_in_thread_with_globals<rustc_interface[1dd91e2665f7489c]::util::run_in_thread_pool_with_globals<rustc_interface[1dd91e2665f7489c]::interface::run_compiler<(), rustc_driver_impl[8a35e1c27f9e238f]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  24:     0x79ada7fbc8b4 - <<std[c9702a20cd481928]::thread::Builder>::spawn_unchecked_<rustc_interface[1dd91e2665f7489c]::util::run_in_thread_with_globals<rustc_interface[1dd91e2665f7489c]::util::run_in_thread_pool_with_globals<rustc_interface[1dd91e2665f7489c]::interface::run_compiler<(), rustc_driver_impl[8a35e1c27f9e238f]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[fb772cbc65c9782a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x79ada7fbdcb7 - std::sys::pal::unix::thread::Thread::new::thread_start::h2500dd9e4f747739
  26:     0x79ada1ea370a - <unknown>
  27:     0x79ada1f27aac - <unknown>
  28:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (70237a8cb 2025-03-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(abi_ptx) -Z dump-mir-dir=dir

query stack during panic:
end of query stack
warning: 2 warnings emitted


```

</p>
</details>

@rustbot label +F-abi_ptx

### PR DESCRIPTION
**Pull request by workingjubilee**
Modify the handling of `extern "{abi}"` in the compiler so that it has consistent errors without regard to the position in the grammar.

## What

Implement the following breakages:
- Promote [`unsupported_fn_ptr_calling_conventions`] from a warning to a hard error
- Guarantee future edge-cases like trait declarations will not escape so that *ABIs that have already been unusable in most positions* will now be unusable in **all positions**. See "How" and "Why or Why Not" for more details.

In particular, these architecture-specific ABIs now only compile on their architectures[^4]:
  - amdgpu: "gpu-kernel"
  - arm: "aapcs", "C-cmse-nonsecure-entry", "C-cmse-nonsecure-call"
  - avr: "avr-interrupt", "avr-non-blocking-interrupt"
  - msp430: "msp430-interrupt"
  - nvptx64: "gpu-kernel", "ptx-kernel"
  - riscv32 and riscv64: "riscv-interrupt-m", "riscv-interrupt-s"
  - x86: "thiscall"
  - x86 and x86_64: "x86-interrupt"
  - x86_64: "sysv64", "win64"

ABIs that are logically x86-specific but actually permitted on all Windows targets remain permitted on Windows, as before. For non-Windows targets, they error if we had previously done so in other positions.

## How

We modify rustc_ast_lowering to prevent unsupported ABIs from leaking through the HIR without being checked for target support. They now emit hard errors for every case where we would return `Invalid` from `AbiMap::canonize_abi`. Previously ad-hoc checking on various HIR items required making sure we check every HIR item which could contain an `extern "{abi}"` string. This is a losing proposition compared to gating the lowering itself.

As a consequence, unsupported ABI strings error instead of triggering the warning `unsupported_fn_ptr_calling_conventions`. The code is also simpler compared to alternative implementations that might e.g. split on unstable vs. stable, only suffering some unavoidable complication to support the newly-revived `unsupported_calling_conventions` lint.[^5]

However, per rust-lang/rust#86232 this does cause errors for rare usages of `extern "{abi}"` that were theoretically possible to write in Rust source, without previous warning or error. For instance, trait declarations without impls were never checked. These are the exact kinds of leakages that this new approach prevents.

This differs from the following PRs:
- rust-lang/rust#141435 is orthogonal, as it adds a new lint for ABIs we have not warned on and are not touched by this PR
- rust-lang/rust#141877 is subsumed by this, in that this simply cuts out bad functionality instead of adding epicycles for stable code

## Why or Why Not

We already made the decision to issue the `unsupported_fn_ptr_calling_conventions` future compatibility warning. It has warned in dependencies since rust-lang/rust#135767, which reached stable with Rust 1.87. That was released on 2025 May 17, and it is now June. As we already had erred on these ABI strings in most other positions, and warn on stable for function pointer types, this breakage has had reasonable foreshadowing.

Upgrading the warning to an error addresses a real problem. In some cases the Rust compiler can attempt to actually compute the ABI for calling a function with an unsupported ABI. We could accept this case and compute unsupported ABIs according to some other ABI, silently[^6]. However, this obviously exposes Rust to errors in codegen. We cannot lower directly to the "obvious", target-incorrect ABI and then trust code generators like LLVM to reliably error on these cases, either.

Other considerations include:
- We could refactor the compiler to defer ABI computations, but that seems like it would suffer the "whack-a-mole" problem close to linking instead of after parsing and expansion.
- We could run a deprecation cycle for the edge cases, but we would be warning highly marginal cases, like this trait declaration without a definition that cannot be implemented without error[^9].
```rust
pub trait UsedToSneakBy {
    pub extern "gpu-kernel" fn sneaky();
}
```
- The [crater run] on this PR's draft form suggests the primary issue is with implementations on function pointers, which has already been warned on, so it does not seem like we would be benefiting any real code.
- Converting this to a hard error now, in the same cycle that we ship the reanimation of the `unsupported_calling_conventions` lint, means people who would otherwise have to deal with two lints only have to update their code in one batch. Of course, one of them is as breakage.

r? lang

Fixes rust-lang/rust#86232
Fixes rust-lang/rust#132430 
Fixes rust-lang/rust#138738
Fixes rust-lang/rust#142107

[`unsupported_fn_ptr_calling_conventions`]: https://github.com/rust-lang/rust/issues/130260
[crater run]: https://github.com/rust-lang/rust/pull/142134#issuecomment-2953837506
[^9]: Upon any impl, even for provided fn within trait declarations, e.g. `pub extern "gpu-kernel" fn sneaky() {}`, different HIR types were used which would, in fact, get checked. Likewise for anything with function pointers. Thus we would be discussing deprecation cycles for code that is impotent or forewarned[^7].
[^4]: Some already will not compile, due to reaching ICEs or LLVM errors.
[^5]: That lint cannot be moved in a similar way yet because lints operate on HIR, so you cannot emit lints when the HIR has not been completely formed.
[^6]:  We already do this for all `AbiStr` we cannot parse, pretending they are `ExternAbi::Rust`, but we also emit an error to prevent reaching too far into codegen.
[^7]: It actually did appear in two cases in rustc's test suite because we are a collection of Rust edge-cases by the simple fact that we don't care if the code actually runs. These cases are being excised in 643a9d233b4f1547220134daea4bcca809302d40

### CODE REVIEW

**Comment by workingjubilee** [comment]
@bors2 try

**Comment by workingjubilee** [comment]
@craterbot run mode=build-only name=pr-142134-abi-ast-error cap-lints=warn

**Comment by workingjubilee** [comment]
I'll send the necessary PRs to `size-of` and `retour`.

The primary culprit seems to be impls on function pointers, which are already warned on: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=e1e8ca91878cbbcba5c6dc3b064cea2b

## on `retour`

I should note that while impls on function pointers are convenient, it's not clear that code that works at the low level that `retour` does can be *correct* when interacting with these function pointers unless it is written with full awareness that the relevant ABIs are translated to `extern "C"`. Some simple versions, maybe, but often detouring libraries have to make assumptions about codegen, and consistently getting that correct seems unlikely. So I believe enforcing this lint in a now-absolutist fashion will, in fact, make the world's code more correct.

## on `size_of`

For `size_of` the upgrade to warn-on-deps seems to have attracted notice: https://github.com/Kixiron/size-of/issues/6

I was able to contact the maintainer who is happy to run a release once I draft a PR that fixes this.

### on the rest

- https://github.com/EnmanuelParache/msp430fr2476 is archived, but clearly only intended to be a crossbuild for msp430 devices which would support msp430-interrupt in the first place.
- https://github.com/ejaanens/msp430fr2476 is a skeleton project generated by svd2rust and has the same caveat.
- https://github.com/bekker/qvopenapi-rs looks abandoned and I expect a contrib will have a language barrier, but I'll try.

The "regressions" for libc, serde_derive, etc. all appear to be spurious failures due to build space running out.

**Comment by RalfJung** [comment]
> Fixes https://github.com/rust-lang/rust/issues/86232

So what does this do with invalid ABIs in traits? I can't see a new lint being introduced here -- but making this a hard error immediately would be a breaking change, no?

File: tests/ui/abi/unsupported-extern-abi-in-type-impl.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+//@ compile-flags: --crate-type=lib
+//@ edition: 2018
+#![feature(abi_gpu_kernel)]
+struct Test;
+
+impl Test {
+    pub extern "gpu-kernel" fn test(val: &str) {}
+    //~^ ERROR [E0570]
```
Comment (RalfJung) [inline tests/ui/abi/unsupported-extern-abi-in-type-impl.rs]: Error codes are pretty meaningless, making the test file hard to read. IMO it'd be better to have a snippet of the error message in the test file here.

File: tests/ui/abi/unsupported-abi-transmute.rs
Comment (RalfJung) [inline tests/ui/abi/unsupported-abi-transmute.rs:1]: All these tests seem to assume that "gpu-kernel" is not a valid ABI. But that's target-specific, so this will fail when the test suite is run on a GPU target, right?

Like the other unsupported ABI tests, I think this should use `--target` and `#![no_core]` (ideally with [minicore](https://rustc-dev-guide.rust-lang.org/tests/minicore.html)) so that the test does not depend on what the host target happens to be.

Comment (workingjubilee) [reply tests/ui/abi/unsupported-abi-transmute.rs:1]: hm, I mean technically GPUs shouldn't ever be hosts so I wouldn't think we would build tests for them, but then Aaron Hsu's codfns compiler exists so maybe I shouldn't think that.

**Comment by workingjubilee** [comment]
> So what does this do with invalid ABIs in traits? I can't see a new lint being introduced here -- but making this a hard error immediately would be a breaking change, no?

Correct.

My proposal to lang is that they should consider it a functional non-event, because it truly seems to be. All the crater regressions are from doing things with function pointers, not unimplementable associated functions of traits. We have been writing these lints and missing cases every time, even though we thought we covered our bases last time. I think we should cut out the problem at the root. If they think we should write another lint, that's... probably fine, actually, but how many more times are we going to do this? I'd like to have a commitment to `break;` when the loop counter reaches some limit, even if we haven't done everything perfectly, before we go further.

Obviously, I think 0 would be a reasonable number of additional repetitions, but there's other integers I could see myself happy with.

@rustbot label: I-lang-nominated

**Comment by RalfJung** [comment]
>  We have been writing these lints and missing cases every time, even though we thought we covered our bases last time. 

Did we? https://github.com/rust-lang/rust/issues/86232 was very clear about affecting traits and fn ptrs, and the fn ptr lint is very clear about only checking fn ptrs. I don't think anyone was confused about the trait case, it's just that so far nobody felt like implementing the lint for that.

File: compiler/rustc_ast_lowering/src/item.rs [hunk 2]
```diff
@@ -1617,9 +1617,28 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
+            if let ExternAbi::Stdcall { unwind } = extern_abi {
+                let c_abi = ExternAbi::C { unwind };
+                let system_abi = ExternAbi::System { unwind };
+                err.help(format!("if you need `extern {extern_abi}` on win32 and `extern {c_abi}` everywhere else, \
+                use `extern {system_abi}`"
+                ));
+            }
+            err.emit();
+        }
+        // stability gate even things that are already errored on
```
Comment (RalfJung) [inline compiler/rustc_ast_lowering/src/item.rs]: Why would we emit a stability error on top of the hard error? Usually we avoid showing more than one error for the same thing if possible.

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 3]
```diff
@@ -37,54 +36,32 @@ use {rustc_attr_data_structures as attrs, rustc_hir as hir};
...
-                tcx.dcx(),
-                span,
-                E0570,
-                "`{abi}` is not a supported ABI for the current target",
-            );
-            add_help(abi, &mut err);
-            err.emit();
-        }
+        // already erred in rustc_ast_lowering
+        AbiMapping::Invalid => (),
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/check/check.rs]: Given the history of leaky checks, maybe add a delay_span_bug here?

File: tests/ui/abi/unsupported.rs
Comment (RalfJung) [inline tests/ui/abi/unsupported.rs:1]: Could you add some trait declarations here? That can replace at least one of your new tests, too.

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 4]
```diff
@@ -37,54 +36,32 @@ use {rustc_attr_data_structures as attrs, rustc_hir as hir};
...
+        let c_abi = ExternAbi::C { unwind };
+        let system_abi = ExternAbi::System { unwind };
+        diag.help(format!(
+            "if you need `extern {abi}` on win32 and `extern {c_abi}` everywhere else, \
+                use `extern {system_abi}`"
+        ));
+    }
+}
+
 pub fn check_abi(tcx: TyCtxt<'_>, hir_id: hir::HirId, span: Span, abi: ExternAbi) {
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/check/check.rs:54]: If I understand this PR correctly, we still do not call this function for trait declarations. This means that UNSUPPORTED_CALLING_CONVENTIONS is not emitted for them, and so moving cdecl and friends to `Invalid` will be another sudden breaking change with no prior lint. Is that right?

How hard would it be to find a place in hir_analysis (or wherever) to call this on trait declarations, too?

**Comment by workingjubilee** [comment]
> Did we? #86232 was very clear about affecting traits and fn ptrs, and the fn ptr lint is very clear about only checking fn ptrs. I don't think anyone was confused about the trait case, it's just that so far nobody felt like implementing the lint for that.

"Nobody felt like it" is kind of the problem.

I have been triaging issues up and down the issue tracker for years, spending large amounts of time tagging and sorting issues, and increasingly trying to focus on understanding and collecting all the ones specifically related to ABI. Talking with you, even!... and ~last week was the first time I saw it. Even the people who know about it have bigger fish to fry. There is exactly zero code on crater that is affected by the edge-case breakage in practice. Usually, even the most obscure breakage at least hits some random unfinished project on GitHub, and then we decide whether to write off some abandoned code from 2017 or not, but the breakage I saw was purely about function pointers.

If people insist on a performance then I will be their Pierrot, but not before the ringmaster directs me. They know well I have more interesting acts I could be rehearsing.

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 3 above)
Comment (workingjubilee) [reply compiler/rustc_hir_analysis/src/check/check.rs]: Sure.

**Comment by RalfJung** [comment]
0 crater regressions is a good sign, I agree. Crater doesn't see all code though, and it only builds for Linux (which is quite relevant when talking about target-specific behavior such as this).

File: compiler/rustc_ast_lowering/src/item.rs (hunk 2 above)
Comment (workingjubilee) [reply compiler/rustc_ast_lowering/src/item.rs]: Because if they typed out an `extern "{abi}"` that is unstable, because most of them are quite special, they *probably* want to use it on a target that *does* support it, so omitting the stability gate info is just hiding data they will want later.

Comment (RalfJung) [inline compiler/rustc_ast_lowering/src/item.rs]:
```suggestion
        // Show required feature gate even if we already errored, as the user is likely to build the code
        // for the actually intended target next and then they will need the feature gate.
```

**Comment by traviscross** [comment]
@rfcbot fcp merge

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 4 above)
Comment (workingjubilee) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: Yes, it's possible to hunt down the various places in HIR, assuming nothing warps the HIR so that a slightly different arrangement of data structures contains `extern "{abi}"` instances that should be checked.

But I think I would rather wait until https://github.com/rust-lang/rust/pull/138164 so I can make `UNSUPPORTED_CALLING_CONVENTIONS` also correct-by-construction (...by checking it during construction).

Comment (RalfJung) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: If that PR has a realistic chance of landing in the next few months, sure. ;)

Anyway this PR does not make things worse here, so while I think it is a missed opportunity for improving the lint, it is not a blocker for this PR.

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 5]
```diff
@@ -57,46 +56,16 @@ pub fn check_abi(tcx: TyCtxt<'_>, hir_id: hir::HirId, span: Span, abi: ExternAbi
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/check/check.rs:58]: Regarding the FIXME just above this line: since https://github.com/rust-lang/rust/issues/86232 will be marked as fixed, it seems good to update the FIXME. Github doesn't think this is useful though so we have to do it by hand:
```
// FIXME: this currently only guards function imports, function definitions, and function pointer types.
// Functions in trait declarations can still use "deprecated" ABIs without any warning.
```

**Review by RalfJung — COMMENTED** [review]
The HIR parts LGTM, but I know nothing about that AST code so I can't tell if that's truly the one place all ABI strings go through.

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 4 above)
Comment (jdonszelmann) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: should land today, already got the r+, just cursed by the conflict gods :sob:

Comment (RalfJung) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: Oh wow, that's amazing. :) Yeah this is fine then (the FIXME should still be added though IMO, to leave *some* transactional evidence in case Jubilee has to drop the ball on this).

Comment (jdonszelmann) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: reasonable

Comment (jdonszelmann) [reply compiler/rustc_hir_analysis/src/check/check.rs:54]: there we go! :tada:

File: tests/ui/abi/unsupported.i686.stderr [hunk 6]
```diff
@@ -1,222 +1,123 @@
-warning: the calling convention "ptx-kernel" is not supported on this target
-  --> $DIR/unsupported.rs:38:15
+error[E0570]: `"ptx-kernel"` is not a supported ABI for the current target
```
Comment (RalfJung) [inline tests/ui/abi/unsupported.i686.stderr]: Do we really want backtics around the quotes here? That seems like unnecessary double-quoting.

Comment (workingjubilee) [reply tests/ui/abi/unsupported.i686.stderr]: IMO no.

Comment (workingjubilee) [reply tests/ui/abi/unsupported.i686.stderr]: I just at first had tried to angle for reducing conflicts but that ship has sailed

**Comment by workingjubilee** [comment]
- rebased with minor cleanup: https://github.com/rust-lang/rust/compare/1530ca434819bf30294da3d930307a2dd0a3978b..536e96e25f4cbf2f5cbc42ef320282d66623fa45

**Comment by workingjubilee** [comment]
hm. idk who best to ask for the final check of just the AST lowering code.

r? @jdonszelmann maybe?

**Comment by workingjubilee** [comment]
Okay, done fixing up that test. I hope.

**Comment by jdonszelmann** [comment]
@workingjubilee I see nothing wrong with the ast lowering code, r=me if I'm the last to give my review :)

**Comment by workingjubilee** [comment]
wait, @bors r-

**Comment by workingjubilee** [comment]
*Now* it should be good.

@bors r=jdonszelmann,RalfJung

**Comment by workingjubilee** [comment]
This is conflict-prone: the majority of these conflicts have not been my own PRs. It is also blocking another PR. Assigning

@bors rollup=iffy

If it conflicts again I'm going to prio it.
