### PR TITLE
Fixes NLL: error from URL crate

### LINKED ISSUE #47703: NLL: error from URL crate
In https://github.com/rust-lang/rust/issues/47596, @SimonSapin reported several NLL errors in dependencies of the servo crate. @Aaron1011 later minimized one of those errors into [this example](https://play.rust-lang.org/?gist=0bd31f0d318c0a4889f720fe54d7979d&version=undefined):

```rust
#![feature(nll)]

struct MyStruct<'a> {
    field: &'a mut (),
    field2: WithDrop
}

struct WithDrop;

impl Drop for WithDrop {

    fn drop(&mut self) {}

}

impl<'a> MyStruct<'a> {

    fn consume(self) -> &'a mut () { self.field }
}

fn main() {}
```

which yields:

```
error[E0597]: `*self.field` does not live long enough
  --> src/main.rs:18:38
   |
18 |     fn consume(self) -> &'a mut () { self.field }
   |                                      ^^^^^^^^^^  - borrowed value only lives until here
   |                                      |
   |                                      borrowed value does not live long enough
   |
   = note: borrowed value must be valid for lifetime '_#3r...
```

Removing feature(nll) makes the code work, so *probably* this is an NLL bug.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #47703.

r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
A quick note about this initial solution, I'm not all that confident that I should be using a `Shallow` access for the individual fields, so happy to find another solution to the issues that fixed if it causes an problem I didn't anticipate.

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -2064,20 +2064,50 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
         // FIXME: analogous code in check_loans first maps `place` to
         // its base_path.
 
+        // When this function is called as a result of an `access_terminator` call attempting
+        // to drop a struct, if that struct does not have a destructor, then we need to check
+        // each of the fields in the struct. See #47703.
+        let (access, places) = if let ContextKind::Drop = context.kind {
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: This should be resolved now.

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -708,6 +702,66 @@ impl InitializationRequiringAction {
...
+            ty::TyAdt(def, substs) if def.is_struct() && !def.has_dtor(self.tcx) => {
+                for (index, field) in def.all_fields().enumerate() {
+                    let field_ty = field.ty(self.tcx, substs);
+                    let proj = Projection {
+                        base: drop_place.clone(),
+                        elem: ProjectionElem::Field(Field::new(index), field_ty),
+                    };
+                    let place = Place::Projection(Box::new(proj));
+
+                    match field_ty.sty {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: instead of this match, we could invoke:

```rust
self.visit_terminator_drop(self, loc, term, flow_state, &place, span);
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 3]
```diff
@@ -708,6 +702,66 @@ impl InitializationRequiringAction {
...
+                                flow_state,
+                                &place,
+                                span,
+                            );
+                        },
+                        _ => {
+                            self.access_place(
+                                ContextKind::Drop.new(loc),
+                                (&place, span),
+                                (Shallow(None), Write(WriteKind::StorageDeadOrDrop)),
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: In particular, this `Shallow(None)` is wrong -- we should fall through to the `Deep` case below. 

Here is why: imagine this *is* a struct with a destructor. Then we will be running random user code, it could touch anything within!

File: src/librustc_mir/borrow_check/mod.rs [hunk 4]
```diff
@@ -708,6 +702,66 @@ impl InitializationRequiringAction {
...
+    ) {
+        let ty = drop_place.ty(self.mir, self.tcx).to_ty(self.tcx);
+        match ty.sty {
+            // When a struct is being dropped, we need to check whether it has a
+            // destructor, if it does, then we can call it, if it does not then we
+            // need to check the individual fields instead.
+            // See #47703.
+            ty::TyAdt(def, substs) if def.is_struct() && !def.has_dtor(self.tcx) => {
+                for (index, field) in def.all_fields().enumerate() {
+                    let field_ty = field.ty(self.tcx, substs);
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Sadly, before landing we're going to have to normalize associated types here. I have to dig a bit to see what's the most convenient way to do that. Probably we can erase regions, actually, which might simplify our lives a bit.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/borrow_check/mod.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: I wasn't sure about the `Shallow(None)`, but when using the place for just the field, we still get an error, so figured it must have been necessary:

```
DEBUG:<unknown>: MirBorrowckCtxt::process_terminator(bb0[4], Terminator { source_info: SourceInfo { span: src/test/run-pass/issue-47703.rs:25:50: 25:50, scope: scope[0] }, kind: drop(_1) -> [return: bb2, unwind: bb1] }): borrows in effect: [&mut (*(_1.0: &mut ())), &mut (*(_1.0: &mut ()))@active] borrows generated: [] inits: [_0, _1] uninits: [_2] move_out: [] ever_init: [mp1@src/test/run-pass/issue-47703.rs:25:16: 25:20 (Deep), mp0@src/test/run-pass/issue-47703.rs:25:36: 25:50 (Deep)]
DEBUG:<unknown>: check_access_permissions((_1.0: &mut ()), Write(StorageDeadOrDrop), Yes)
DEBUG:<unknown>: places_conflict((*(_1.0: &mut ())),(_1.0: &mut ()),Deep)
DEBUG:<unknown>: places_conflict: components [_1, (_1.0: &mut ()), (*(_1.0: &mut ()))] / [_1, (_1.0: &mut ())]
DEBUG:<unknown>: places_conflict: Some(_1) vs. Some(_1)
DEBUG:<unknown>: place_element_conflict: DISJOINT-OR-EQ-LOCAL
DEBUG:<unknown>: places_conflict: Some((_1.0: &mut ())) vs. Some((_1.0: &mut ()))
DEBUG:<unknown>: place_element_conflict: DISJOINT-OR-EQ-FIELD
DEBUG:<unknown>: places_conflict: Some((*(_1.0: &mut ()))) vs. None
DEBUG:<unknown>: places_conflict: None vs. None
DEBUG:<unknown>: places_conflict: full borrow, CONFLICT
```

File: src/librustc_mir/borrow_check/mod.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: I've changed this locally, will push with other changes.

File: src/librustc_mir/borrow_check/mod.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: I'm able to change this so that the `access_place` ends up matching the `borrow_place`, ie. `(*(_1.0: &mut ()))` on both sides. This also does not fix the error.

```
DEBUG:<unknown>: MirBorrowckCtxt::process_terminator(bb0[4], Terminator { source_info: SourceInfo { span: src/test/run-pass/issue-47703.rs:25:50: 25:50, scope: scope[0] }, kind: drop(_1) -> [return: bb2, unwind: bb1] }): borrows in effect: [&mut (*(_1.0: &mut ())), &mut (*(_1.0: &mut ()))@active] borrows generated: [] inits: [_0, _1] uninits: [_2] move_out: [] ever_init: [mp1@src/test/run-pass/issue-47703.rs:25:16: 25:20 (Deep), mp0@src/test/run-pass/issue-47703.rs:25:36: 25:50 (Deep)]
DEBUG:<unknown>: check_access_permissions((*(_1.0: &mut ())), Write(StorageDeadOrDrop), Yes)
DEBUG:<unknown>: places_conflict((*(_1.0: &mut ())),(*(_1.0: &mut ())),Deep)
DEBUG:<unknown>: places_conflict: components [_1, (_1.0: &mut ()), (*(_1.0: &mut ()))] / [_1, (_1.0: &mut ()), (*(_1.0: &mut ()))]
DEBUG:<unknown>: places_conflict: Some(_1) vs. Some(_1)
DEBUG:<unknown>: place_element_conflict: DISJOINT-OR-EQ-LOCAL
DEBUG:<unknown>: places_conflict: Some((_1.0: &mut ())) vs. Some((_1.0: &mut ()))
DEBUG:<unknown>: place_element_conflict: DISJOINT-OR-EQ-FIELD
DEBUG:<unknown>: places_conflict: Some((*(_1.0: &mut ()))) vs. Some((*(_1.0: &mut ())))
DEBUG:<unknown>: place_element_conflict: DISJOINT-OR-EQ-DEREF
DEBUG:<unknown>: places_conflict: None vs. None
DEBUG:<unknown>: places_conflict: full borrow, CONFLICT
```

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/mod.rs]: I'm a bit confused by what you are showing me -- you are saying that if you *don't* use the "shallow" case, you get an error on the original test case?

Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: Yes. If I change it to `Deep` (or let it fall through to that case), then I get the error on the original test case. That's why I had it as `Shallow(None)` initially.

**Comment by davidtwco** [comment]
I've pushed what changes I made locally as requested by @nikomatsakis. It will fail the tests because the previous version used `Shallow(None)` instead of `Deep`. It also doesn't normalize associated types.

Also, the line below is included because it was something I tried out to see if it would help, I don't think it's what we should have:

https://github.com/davidtwco/rust/blob/f9de0484ce401b9407dc05c8eb6291cdc2ef5269/src/librustc_mir/borrow_check/mod.rs#L724

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
OK, I pushed a few tweaks, but we still need to solve the normalization problem.

**Comment by nikomatsakis** [comment]
Marking as S-blocked for now -- I have an in-progress branch that may be very helpful here.

File: src/librustc_mir/borrow_check/mod.rs [hunk 5]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+    /// always for a variable (e.g., `Drop(x)`) -- but we recursively
+    /// break this variable down into subpaths (e.g., `Drop(x.foo)`)
+    /// to indicate more precisely which fields might actually be
+    /// accessed by a destructor.
+    fn visit_terminator_drop(
+        &mut self,
+        loc: Location,
+        term: &Terminator<'tcx>,
+        flow_state: &Flows<'cx, 'gcx, 'tcx>,
+        drop_place: &Place<'tcx>,
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: This will take an extra argument:

```
erased_drop_place_ty: Ty<'gcx>,
```

Note that it belongs in the global arena (`'gcx`) -- this is possible because its regions have been erased.

File: src/librustc_mir/borrow_check/mod.rs [hunk 6]
```diff
@@ -464,13 +464,7 @@ impl<'cx, 'gcx, 'tcx> DataflowResultsConsumer<'cx, 'tcx> for MirBorrowckCtxt<'cx
...
                 unwind: _,
             } => {
-                self.access_place(
-                    ContextKind::Drop.new(loc),
-                    (drop_place, span),
-                    (Deep, Write(WriteKind::StorageDeadOrDrop)),
-                    LocalMutationIsAllowed::Yes,
-                    flow_state,
-                );
+                self.visit_terminator_drop(loc, term, flow_state, drop_place, span);
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Here, we will start by erasing the type of the `drop_place`, roughly like so:

```rust
let gcx = self.tcx.global_tcx();

// Compute the type with accurate region information.
let drop_place_ty = drop_place.ty(self.mir, self.tcx);

// Erase the regions.
let drop_place_ty = self.tcx.erase_regions(&drop_place_ty);

// "Lift" into the gcx -- once the regions are erased, this type should be in the global arenas; this "lift" operation basically just asserts that this is true, but that's useful later.
let drop_place_ty = gcx.lift(&drop_place_ty).unwrap();
```

(Note that I am intentionally shadowing `drop_place_ty` here, because we don't want to accidentally access the intermediate values.)

Then we'll add this `drop_place_ty` as an argument to `visit_terminator_drop`

File: src/librustc_mir/borrow_check/mod.rs [hunk 7]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+    /// accessed by a destructor.
+    fn visit_terminator_drop(
+        &mut self,
+        loc: Location,
+        term: &Terminator<'tcx>,
+        flow_state: &Flows<'cx, 'gcx, 'tcx>,
+        drop_place: &Place<'tcx>,
+        span: Span,
+    ) {
+        let ty = drop_place.ty(self.mir, self.tcx).to_ty(self.tcx);
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: remove this line

File: src/librustc_mir/borrow_check/mod.rs [hunk 8]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+        match ty.sty {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: becomes

```rust
match erased_drop_place_ty.sty {
...
}
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 9]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+            // When a struct is being dropped, we need to check
+            // whether it has a destructor, if it does, then we can
+            // call it, if it does not then we need to check the
+            // individual fields instead. This way if `foo` has a
+            // destructor but `bar` does not, we will only check for
+            // borrows of `x.foo` and not `x.bar`. See #47703.
+            ty::TyAdt(def, substs) if def.is_struct() && !def.has_dtor(self.tcx) => {
+                for (index, field) in def.all_fields().enumerate() {
+                    let place = drop_place.clone();
+                    let place = place.field(Field::new(index), field.ty(self.tcx, substs));
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Here, we can normalize like so:

```
let gcx = self.tcx.global_tcx();
let field_ty = field.ty(gcx, substs);
let field_ty = gcx.normalize_associated_types_in_env(&field_ty, self.param_env);
let place = place.field(Field::new(index), field_ty);
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 10]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+                }
+            },
+            _ => {
+                // We have now refined the type of the value being
+                // dropped (potentially) to just the type of a
+                // subfield; so check whether that field's type still
+                // "needs drop". If so, we assume that the destructor
+                // may access any data it likes (i.e., a Deep Write).
+                let gcx = self.tcx.global_tcx();
+                let erased_ty = gcx.lift(&self.tcx.erase_regions(&ty)).unwrap();
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Here, the regions etc are already erased, so we can just remove this code

File: src/librustc_mir/borrow_check/mod.rs [hunk 11]
```diff
@@ -708,6 +702,64 @@ impl InitializationRequiringAction {
...
+                if erased_ty.needs_drop(gcx, self.param_env) {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Here we would use `if erased_drop_place_ty.needs_drop(...) {`

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
OK, I laid out how I think we can make the transformation. If we do this, it's probably worth adding some comments to `access_place` that the `Place<'tcx>` may have a region-erased type in some cases. But I don't think that should matter, those bits of code ought not to be testing the region. Certainly my searches through the code suggest that this is the case. (All instances of `TyRef` ignore the region, for example.)

**Comment by davidtwco** [comment]
@nikomatsakis pushed up rebased changes that include associated type normalization.

File: src/librustc_mir/borrow_check/mod.rs [hunk 12]
```diff
@@ -463,13 +463,20 @@ impl<'cx, 'gcx, 'tcx> DataflowResultsConsumer<'cx, 'tcx> for MirBorrowckCtxt<'cx
...
+                let gcx = self.tcx.global_tcx();
+
+                // Compute the type with accurate region information.
+                let drop_place_ty = drop_place.ty(self.mir, self.tcx);
+
+                // Erase the regions.
+                let drop_place_ty = self.tcx.erase_regions(&drop_place_ty).to_ty(self.tcx);
+
+                // "Lift" into the gcx -- once regions are erased, this type should be in the
+                // global areans; this "lift" operation basically just asserts that is true, but
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Nit: arenas, not "areans"

File: src/librustc_mir/borrow_check/mod.rs [hunk 13]
```diff
@@ -717,6 +724,65 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+    /// break this variable down into subpaths (e.g., `Drop(x.foo)`)
+    /// to indicate more precisely which fields might actually be
+    /// accessed by a destructor.
+    fn visit_terminator_drop(
+        &mut self,
+        loc: Location,
+        term: &Terminator<'tcx>,
+        flow_state: &Flows<'cx, 'gcx, 'tcx>,
+        drop_place: &Place<'tcx>,
+        erased_drop_place_ty: &'gcx ty::TyS<'gcx>,
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: This is always written `Ty<'gcx>`. We never reference `TyS` outside of the `ty` module if we can help it. =)

File: src/librustc_mir/borrow_check/mod.rs [hunk 14]
```diff
@@ -2093,7 +2159,7 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
         while let Some(i) = elems_incoming.next() {
             let borrowed = &data[i.borrow_index()];
 
-            if self.places_conflict(&borrowed.borrowed_place, place, access) {
+            if self.places_conflict(&borrowed.borrowed_place, &place, access) {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Why this diff?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Left a few nits, but seems good.

File: src/librustc_mir/borrow_check/mod.rs (hunk 14 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: I have no idea what that came from. My bad.

File: src/librustc_mir/borrow_check/mod.rs (hunk 13 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: Fixed.

File: src/librustc_mir/borrow_check/mod.rs (hunk 12 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: Oops, fixed.

**Comment by davidtwco** [comment]
@nikomatsakis fixed those nits.

**Review by nikomatsakis — APPROVED** [review]
