### PR TITLE
Restore `Opaque` behavior to coherence check

### LINKED ISSUE #99663: Documentation build failed for `teloxide` v0.10.1
The full log is available from this link: https://docs.rs/crate/teloxide/0.10.1/builds/597656.

### Meta

From the aforementioned link:

```
# rustc version
rustc 1.64.0-nightly (62b272d25 2022-07-21)
# docs.rs version
docsrs 0.6.0 (19b354a 2022-07-16)
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #99663.

This broke in 84c3fcd2a0285c06a682c9b064640084e4c7271b. I'm not exactly certain that adding this behavior back is necessarily correct, but at least the UI test I provided may stimulate some thoughts. 

I think delaying a bug here is certainly not correct in the case of opaques -- if we want to change coherence behavior for opaques, then we should at least be emitting a new error.

r? @lcnr

### CODE REVIEW

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/rust/pull/99552#issuecomment-1191313601

> The algorithm replicates the existing behaviour, so...

Hm, guess not?

**Comment by lcnr** [comment]
> Hm, guess not?

@compiler-errors is the `Opaque` difference the only reason why you wrote this?

**Comment by compiler-errors** [comment]
@lcnr that's the only difference I could find, but I didn't look further than the opaque change that I touched in this PR.

Just pointed out that comment because it seems #99552 changed behavior, not just replicated the old behavior, unless I'm misunderstanding the original point of that comment.

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 1]
```diff
@@ -703,13 +703,41 @@ impl<'tcx> TypeVisitor<'tcx> for OrphanChecker<'tcx> {
...
                 ControlFlow::Break(OrphanCheckEarlyExit::LocalTy(ty))
             }
+            ty::Opaque(..) => {
+                // This merits some explanation.
+                // Normally, opaque types are not involved when performing
+                // coherence checking, since it is illegal to directly
+                // implement a trait on an opaque type. However, we might
+                // end up looking at an opaque type during coherence checking
+                // if an opaque type gets used within another type (e.g. as
+                // a type parameter). This requires us to decide whether or
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:720]: that's definitely wrong.

the issue is with TAIT, opaque types can be used as struct fields and struct fields are used during coherence for auto traits and `Sized`.

```suggestion
                // if an opaque type gets used within another type (e.g. as
                // the type of a field). This requires us to decide whether or
```

File: src/test/ui/coherence/issue-99663.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+}
+
+type InnerSend<T> = impl Sized;
+
+fn constrain<T>() -> InnerSend<T> {
+    ()
+}
+
+trait SendMustNotImplDrop {}
+#[allow(clippy::drop_bounds, drop_bounds)]
```
Comment (lcnr) [inline src/test/ui/coherence/issue-99663.rs:16]:
```suggestion
```

**Review by lcnr — COMMENTED** [review]
please add the following as an additional test:
```rust
#![feature(type_alias_impl_trait)]

struct Outer<T: ?Sized> {
    i: InnerSend<T>,
}

type InnerSend<T: ?Sized> = impl Send;

fn constrain<T: ?Sized>() -> InnerSend<T> {
    ()
}

trait SendMustNotImplDrop {}
impl<T: ?Sized + Send + Drop> SendMustNotImplDrop for T {}
impl<T: ?Sized> SendMustNotImplDrop for Outer<T> {}

fn main() {}
```
this triggers the ice using auto traits.

It was surprising to me that we never look into the opaque types during coherence, causing an ICE for closures etc as well, (by changing `constrain` to `|| ()`). The reason for that is that `is_knowable` fails for auto trait/sized impls on `Opaque` types as they always result in `Conflict::Upstream`.

r=me after adding this test and fixing my nit

**Comment by lcnr** [comment]
> Just pointed out that comment because it seems #99552 did change behavior, not just replicated the old behavior like the comment suggested, unless I'm misunderstanding the point of that comment.

It did change the behavior for `Opaque` types because we thought that case would be unreachable.

I interpreted the comment by oli to be about #99552 my new FIXME. While `orphan_check_trait_ref` is now "visibly wrong" (or at least in need of some further thought), it does keep the previous behavior, so merging it as is was fine.
https://github.com/rust-lang/rust/blob/7f93d4aa0dc4ac071c617e0e07d2758e3bb388f9/compiler/rustc_trait_selection/src/traits/coherence.rs#L720-L723

File: src/test/ui/coherence/issue-99663.rs (hunk 2 above)
Comment (compiler-errors) [reply src/test/ui/coherence/issue-99663.rs:16]: I need `allow(drop_bounds)` because this is a `// check-pass` test, or else it'll fail due to the warn.
