### PR TITLE
minimize the rust-std component

### LINKED ISSUE #61978: Rust platform size
I went to this page:

https://forge.rust-lang.org/other-installation-methods

and I discovered that the download is 203 MB. This was surprising to me, so I
looked at other languages:

Language | Size   | Link
---------|--------|----------------------
Go       | 135 MB | https://golang.org/dl
Perl     | 102 MB | http://strawberryperl.com/releases.html
Julia    | 50 MB  | https://julialang.org/downloads
Python   | 25 MB  | https://python.org/downloads/release/python-373
PHP      | 25 MB  | https://windows.php.net/download
D        | 23 MB  | https://dlang.org/download.html
Nim      | 19 MB  | https://nim-lang.org/install_windows.html
Ruby     | 11 MB  | https://rubyinstaller.org/downloads

So Rust is 70% larger than Go. Or to put another way, Rust is larger than Julia,
Python, PHP, D, Nim and Ruby **combined**. Can anything be done about this or is
the large size unavoidable?

### LINKED ISSUE #62486: The total Rust archive size has intensified recently
**Edit**: 
> I forgot that with nightly, I also installed clippy, rustfmt, musl target.
> The new edit will not contains those.

The total Rust archive size has intensified recently.

```console
% rustc +nightly-2019-07-07-x86_64-unknown-linux-gnu -V
rustc 1.38.0-nightly (dfd52ba6a 2019-07-06)
% du -sch ~/.rustup/toolchains/nightly-2019-07-07-x86_64-unknown-linux-gnu
868M    /home/lzutao/.rustup/toolchains/nightly-2019-07-07-x86_64-unknown-linux-gnu
868M    total
```

```console
% rustc +nightly-2019-07-08-x86_64-unknown-linux-gnu -V
rustc 1.38.0-nightly (6e310f2ab 2019-07-07)
% du -sch ~/.rustup/toolchains/nightly-2019-07-08-x86_64-unknown-linux-gnu
1.1G    /home/lzutao/.rustup/toolchains/nightly-2019-07-08-x86_64-unknown-linux-gnu
1.1G    total
```

Is this a regression caused by #59800 ?
cc @Zoxc (for the PR), @Centril (infra team)

### PR DESCRIPTION
**Pull request by cuviper**
This changes the `rust-std` dist component to only include the artifacts of compiling the `libstd` step, as listed in `.libstd.stamp`. This does include `test` and `proc-macro` as well. The remaining _unstable_ libraries that are built as part of `rustc` are packaged into a new `rustc-dev` component, intended for use in the development of closely related tools (clippy, miri, rls).

Here are the component sizes from the [try build](https://dev-static.rust-lang.org/dist/2019-10-07/index.html):

| Name | Size
| --- | ---
| rust-std-nightly-x86_64-unknown-linux-gnu.tar.gz | 23.94 MiB
| rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz | 17.4 MiB
| rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.gz | 182.03 MiB
| rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz | 157.91 MiB

Fixes #61978
Fixes #62486

### CODE REVIEW

**Comment by cuviper** [comment]
<details>
  <summary>rust-std contents</summary>

```
rustlib
rustlib/x86_64-unknown-linux-gnu
rustlib/x86_64-unknown-linux-gnu/lib
rustlib/x86_64-unknown-linux-gnu/lib/liballoc-829f3101d977f206.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-ee59192b6de9f368.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-038ea4a0a8c77604.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7094efc75c4be484.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-a02a6d088515bc50.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcore-32273be0eb3afdcf.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-36cd9a743b40ef37.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-2e9c5bd77f293b4d.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblibc-cd20ad3e31945caa.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpanic_abort-4b7362f1daba0b67.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e8f25f1479c7909f.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-117a68358dd52808.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_asan-72a98db263e5b446.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-360973d6a8a839f2.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_lsan-31819e91fec99c27.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_msan-5690f798957a29fb.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-ccb7f85b9552784b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-385f65ee94807303.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-541cc8a35bc662dd.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_tsan-3a588f132cd70943.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libstd-b36f3fa61e38f00c.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libstd-b36f3fa61e38f00c.so
rustlib/x86_64-unknown-linux-gnu/lib/libterm-d4f65c2c1fcd90e6.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtest-d8d279e9d913926e.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtest-d8d279e9d913926e.so
rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-61a3636ef768b313.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b80ef1b761dd638e.rlib
```

</details>

<details>
  <summary>rust-stdZ contents</summary>

```
rustlib
rustlib/x86_64-unknown-linux-gnu
rustlib/x86_64-unknown-linux-gnu/lib
rustlib/x86_64-unknown-linux-gnu/lib/liballoc-829f3101d977f206.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libannotate_snippets-a90b1a04ef902ce2.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libarena-917bcbaf4b9cf449.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libarrayvec-1cbfed4e0b63e66c.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libatty-a6a968217626980d.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-b9e825406ed2c8cf.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-ee59192b6de9f368.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-038ea4a0a8c77604.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-28a66cf5842b6293.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbitflags-7f2440c8280521d9.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libbyteorder-97eddc76e7dae5fb.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libc2_chacha-d5df7772d76f51b1.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcc-fba1b04a84d96b8e.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7094efc75c4be484.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-efadd5aed3f96838.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libchalk_engine-539c05987df4c4fc.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libchalk_macros-dcb718f1369419bc.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-a02a6d088515bc50.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcore-32273be0eb3afdcf.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcrc32fast-8105e34220be3072.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcrossbeam_deque-fe474ed469d8bbce.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcrossbeam_epoch-aff57d47277c9a5a.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcrossbeam_utils-9ece8d4987b2f7ca.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libcrossbeam_utils-cf94384094407dbf.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libdatafrog-e15cc7f54f5da188.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libeither-212f3321a8ee66dd.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libena-75bdc410590317b9.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libenv_logger-4f2ca51a92a6d91c.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libflate2-268ba7c6f3d0e098.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libfmt_macros-1985ee02fa190c72.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-36cd9a743b40ef37.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libgetrandom-7e2fc951db31d21b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libgraphviz-6835b819b1a43ba4.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-2e9c5bd77f293b4d.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libindexmap-f384467b29b8520b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libitoa-f3ab8e820f2f3e46.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libjobserver-b63b1c7e22888428.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblazy_static-31194f3d49621e6f.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblazy_static-d95434e3898989e6.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblibc-cd20ad3e31945caa.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblibc-ce37efd4d5605311.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblock_api-751b85934c961cac.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblog-ff5d2491f3d05340.rlib
rustlib/x86_64-unknown-linux-gnu/lib/liblog_settings-316ffc51cb6cb4bf.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libmeasureme-846e877e2fa9dedb.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libmemmap-5d1ce05df91ff5ad.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libmemoffset-826dd9e6a27e7be8.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libminiz_sys-1ca108c45fcef254.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libnodrop-9548fd0c1aab0345.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libnum_cpus-7a33609527bcec71.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libonce_cell-5effcb4d92b09ec0.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpanic_abort-4b7362f1daba0b67.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e8f25f1479c7909f.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libparking_lot-c0254d78de2fb43c.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libparking_lot_core-7ed1adc4d24cd3fc.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpolonius_engine-38bf41783de8ef85.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libppv_lite86-de8a066e3a7b47e1.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-117a68358dd52808.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libpunycode-b8837a6f7f1330e0.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librand-57a3f0d5fd302039.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librand_chacha-848d1e2a0a29fee0.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librand_core-dc5a3b7e4d118535.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libremove_dir_all-a43548349482c5ea.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librls_data-4f2c6d6f34f4396b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librls_span-d68555bad0c8b4c4.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_apfloat-f7e7bb8e208816f3.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_asan-72a98db263e5b446.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_ast_borrowck-ac2d73d5776bcf49.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc-bbf7197366ce1511.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_codegen_ssa-0fcff69c6a276ffb.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_codegen_utils-5a8d0a51bf30ef9b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_data_structures-952e0c68e9cca6e1.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-360973d6a8a839f2.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a4a5d110fcb9fa25.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-29e6cebe3c3971a7.so
rustlib/x86_64-unknown-linux-gnu/lib/librustc_errors-1dbd806ce6e365ac.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_fs_util-8191714d3280668f.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_hash-22497d43d2cc6980.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_incremental-d2c59145d1cae9df.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_interface-8980247355978da1.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_lexer-64c2ae2961f301d7.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_lint-9124cea9598c026e.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_lsan-31819e91fec99c27.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_macros-ec44d4856a2db4cd.so
rustlib/x86_64-unknown-linux-gnu/lib/librustc_metadata-0dad06b5ad11c6e2.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_mir-7d16ed7716874475.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_msan-5690f798957a29fb.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_passes-829b6f2c7e8c9f27.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_plugin-7f4bebb377e6f695.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_plugin_impl-ecc88b36ceb20b61.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_privacy-492552cefb919cf2.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_rayon_core-b29424abf39b468a.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_rayon-df53eccb80fe0377.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_resolve-670b13e9fd45ca39.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_save_analysis-a757b57b3dbcce55.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-ccb7f85b9552784b.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-385f65ee94807303.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-541cc8a35bc662dd.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_target-e350a4a7004a9634.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_traits-b4c705fb4e7105f0.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_tsan-3a588f132cd70943.rlib
rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck-19519d05e570a035.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libryu-57fed4e24d38e082.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libscoped_tls-db421b31bcc23dbc.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libscopeguard-443b1815dd811120.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libscopeguard-c58b19b79683e2ed.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libserde-dda0d123617e8257.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libserde_json-14ae927e29a576d5.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libserialize-afda782ae116fae8.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libsmallvec-863535aef490ac47.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libstable_deref_trait-e83e41401065dbcc.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libstd-b36f3fa61e38f00c.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libstd-b36f3fa61e38f00c.so
rustlib/x86_64-unknown-linux-gnu/lib/libsyntax-1af5aec2ec936254.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libsyntax_ext-b10a0f6ab0d97a78.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libsyntax_pos-17a1a353e8a92672.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtempfile-4e88c3b9cfcf48be.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtermcolor-1cfb690fc61a1c36.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libterm-d4f65c2c1fcd90e6.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libterm_size-52ef24c2e5daa8d8.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtest-d8d279e9d913926e.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libtest-d8d279e9d913926e.so
rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-61a3636ef768b313.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-ce3cfcbd66a1b115.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libunicode_xid-dd34bf041afa96c3.rlib
rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b80ef1b761dd638e.rlib
```

</details>

File: src/bootstrap/dist.rs [hunk 1]
```diff
@@ -675,6 +675,81 @@ impl Step for Std {
...
+
+    fn run(self, builder: &Builder<'_>) -> PathBuf {
+        let compiler = self.compiler;
+        let target = self.target;
+
+        let name = pkgname(builder, "rust-stdZ");
+
+        // The only true set of target libraries came from the build triple, so
+        // let's reduce redundant work by only producing archives from that host.
+        if compiler.host != builder.config.build {
```
Comment (Centril) [inline src/bootstrap/dist.rs]: btw, once this is no longer WIP it would be good to dedupe the code :)

**Comment by Mark-Simulacrum** [comment]
I do think this is a conversation worth having -- at least, it would make sense to me to not ship these components on beta/stable, since to my knowledge no one (should be) using them there; even we don't do so in-tree.

I think in some sense this is also a broader question than just release team, though I'm not sure what teams I'd include necessarily. I guess maybe compiler and infra teams?

**Comment by Centril** [comment]
This seems like an excellent idea!

One wonders why we haven't done this before...

r? @Mark-Simulacrum

**Comment by Centril** [comment]
(Summary from [discussion on Discord](https://discordapp.com/channels/442252698964721669/443148290352218115/626903715852582913)):

I think we should move out the sanitizers (tsan, lsan, msan, asan) from the rust-std component as well. In total they account for 14M which is 8% of 171M -- that's not nothing. Also worth noting that the sanitizers are unstable (see https://github.com/rust-lang/rust/issues/47174) and not available on all tier-1 targets (e.g. macOS). Maybe people have no clue how to use them, including myself.

**Comment by cuviper** [comment]
Oh, the sanitizers are a direct dependency of `std`, which is why they exist as minimal shims even when not enabled in the build configuration.
https://github.com/rust-lang/rust/blob/ddf43867a9cbb3766b48552632a602498fae2699/src/libstd/Cargo.toml#L37-L45

**Comment by eddyb** [comment]
Aren't the `rustc` rlibs supposed to be part of the `rustc` component, in the host part of the sysroot, not in the per-target dirs? Or is that just the dylibs necessary to run the compiler?

I would probably suggest `rustc-dev` if we want to have a component for specifically rlibs you need in order to build code against *host* rustc (and see no point in providing *target* rlibs).

**Comment by bjorn3** [comment]
> Aren't the rustc rlibs supposed to be part of the rustc component, in the host part of the sysroot, not in the per-target dirs?

You need them to cross compile for example miri.

**Comment by ollie27** [comment]
This looks like it will be fixing #44037.

**Comment by cuviper** [comment]
> Aren't the `rustc` rlibs supposed to be part of the `rustc` component, in the host part of the sysroot, not in the per-target dirs? Or is that just the dylibs necessary to run the compiler?

The latter -- the `rustc` component only has `bin/rustc` etc. and their related shared objects.

> I would probably suggest `rustc-dev` if we want to have a component for specifically rlibs you need in order to build code against _host_ rustc (and see no point in providing _target_ rlibs).

I'm fine with the name `rustc-dev`, but I think we probably do want this available for cross compiles. AFAIK that's only a difference in the rustup manifest (`src/tools/build-manifest`).

---

Status: the code as-is works for `./x.py dist libstd`, but `./x.py install libstd` ends up trying to use `stage2-std/$target/release/.libstd.stamp`, which doesn't exist unless you do a full bootstrap. I'm not sure why `dist` only uses stage1 in the first place though. I'll try to work this out.

**Comment by cuviper** [comment]
I think this is in a fairly good state now, with a `rustc-dev` package for the unstable compiler libs. I'm not sure about the build-manifest stuff, because I don't know how to run that locally. I also don't know how to install `rustc-dev` by default for nightly users, if we indeed want that.

**Comment by Mark-Simulacrum** [comment]
I personally am not sure who all should be in charge of this decision so I'll try and bring it up at core team meeting tomorrow. _I_ myself believe this to be a good step to take presuming it doesn't break anything for our own shipped tools (RLS, clippy).

**Comment by alexcrichton** [comment]
I'm not sure if I'll make it to triage this afternoon but wanted to say that I'm also in favor of this, it's indeed a bummer that a few hundred never-used megabytes are downloaded for only wanting libstd!

I do think that separation into `rust-dev` packages will break *development* of clippy/rls/etc since they all link to the compiler and the libraries will no longer be there. Fixing should be relatively easy though since it's just `rustup component add`. I am not certain whether rustup changes will be necessary to actually use this component (I always forget if they're hardcoded in rustup or dynamically learned about). In any case we probably want to make sure everyone's aware of this change happening (clippy/rls/rustup/etc) before we land it, although I suspect everyone's on board with downloading hundreds of less megabytes for targets!

**Comment by Mark-Simulacrum** [comment]
cc @Manishearth (clippy) @Xanewok (RLS) @oli-obk @RalfJung (miri) for I think a pretty good list of "tools" people -- feel free to ping others if you think of them

**Comment by lzutao** [comment]
cc @nrc or @kinnison  (rustup)

**Comment by Manishearth** [comment]
We already use `rustup-toolchain-install-master`, as long as that continues to install the entire rustc distribution we should be fine. We'd also like the ability to install the entire distribution on stable and beta for testing (which this PR seems to allow as an additional `rust-dev` component).

Clippy and RLS _link_ to the libraries `rustc` links to in the distribution, but if you're just using them I don't think you need the rust-dev packages.

**Comment by cuviper** [comment]
Clarification -- the new component is currently `rustc-dev`, with a `c`, but we can change to `rust-dev` if folks find that more natural.

> Clippy and RLS _link_ to the libraries `rustc` links to in the distribution, but if you're just using them I don't think you need the rust-dev packages.

Right, they're ultimately linked to `librustc_driver.so`, which users get in the `rustc` component.

**Comment by cuviper** [comment]
> We already use `rustup-toolchain-install-master`, as long as that continues to install the entire rustc distribution we should be fine.

That's a neat tool! It seems it only installs `rustc` and `rust-std` by default, not even `cargo`, but you can specify additional components. I just ran it for the try-build above:

```
$ rustup-toolchain-install-master --component cargo rustc-dev -- 98951af235be5a9ac3aa0b556298b09d97d97924
detecting the channel of the `98951af235be5a9ac3aa0b556298b09d97d97924` toolchain...
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/98951af235be5a9ac3aa0b556298b09d97d97924/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
completed
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/98951af235be5a9ac3aa0b556298b09d97d97924/cargo-nightly-x86_64-unknown-linux-gnu.tar.xz>...
completed
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/98951af235be5a9ac3aa0b556298b09d97d97924/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz>...
completed
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/98951af235be5a9ac3aa0b556298b09d97d97924/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
completed
toolchain `98951af235be5a9ac3aa0b556298b09d97d97924` is successfully installed!
```

However, despite apparent success, it didn't actually install anything from `rustc-dev`. :confused: 

So I downloaded and installed that tarball manually:

```
$ curl https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/98951af235be5a9ac3aa0b556298b09d97d97924/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz | tar xJ
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  157M  100  157M    0     0  27.8M      0  0:00:05  0:00:05 --:--:-- 29.3M
$ cd rustc-dev-nightly-x86_64-unknown-linux-gnu/
$ ./install.sh --prefix=~/.rustup/toolchains/98951af235be5a9ac3aa0b556298b09d97d97924
install: creating uninstall script at /home/jistone/.rustup/toolchains/98951af235be5a9ac3aa0b556298b09d97d97924/lib/rustlib/uninstall.sh
install: installing component 'rustc-dev-x86_64-unknown-linux-gnu'
install: WARNING: failed to run ldconfig. this may happen when not installing as root. run with --verbose to see the error

    Rust is ready to develop.
```

I confirmed that clippy, miri, and rls are all able to build with this.

**Comment by Manishearth** [comment]
Yeah, and we can default RTIM to installing the dev component since most of the people using it need it

**Comment by bjorn3** [comment]
Will the `rustc-dev` component be installable for other targets than your local target, like `rust-std`, so that you can cross-compile?

**Comment by Mark-Simulacrum** [comment]
I don't see why we'd do anything special/different for the rustc-dev component that would make it not instalable for other targets.

**Comment by bjorn3** [comment]
The tools components can only be installed for the same target as the toolchain:

```
$ rustup component list
cargo-x86_64-unknown-linux-gnu (default)
clippy-x86_64-unknown-linux-gnu
llvm-tools-preview-x86_64-unknown-linux-gnu
rls-x86_64-unknown-linux-gnu (installed)
rust-analysis-x86_64-unknown-linux-gnu (installed)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-src (installed)
rust-std-aarch64-apple-ios
rust-std-aarch64-fuchsia
rust-std-aarch64-linux-android
rust-std-aarch64-pc-windows-msvc
[.,.]
rust-std-x86_64-unknown-freebsd
rust-std-x86_64-unknown-linux-gnu (default)
rust-std-x86_64-unknown-linux-gnux32
rust-std-x86_64-unknown-linux-musl
rust-std-x86_64-unknown-netbsd
rustc-x86_64-unknown-linux-gnu (default)
rustfmt-x86_64-unknown-linux-gnu (installed)
```

I believe the manifest has to list every allowed toolchain target + component target combination.

**Comment by kinnison** [comment]
This might end up needing rustup updates if there're target related things because we have to process components and targets differently.  Certainly this will be interesting to get a good UX for.  If this does get merged then I can look at what's necessary this weekend.  I was hoping to do a rustup release soon (next week maybe) so now is the right time if we are "breaking" nightly for a little while until we can make rustup work.

**Comment by Mark-Simulacrum** [comment]
I definitely think we have time here; the code is hopefully already in place: we want the rust-dev component to behave exactly like the std component.

**Comment by kinnison** [comment]
Is there a nightly manifest published with this content for me to work from?

**Comment by eddyb** [comment]
This is a very minor nit, but since I suggested `rustc-dev` in the first place, I hope everyone saying `rust-dev` is just typos.

Part of the reason I said `rustc-dev` was that distros tend to have separate packages for using a library and *dev*eloping software against it, and this seems to fit right in: `rustc-dev` has the development resources (`rlib`s) for `rustc`.

Anything prefixed with `rust-` sounds like it's about the language as a whole, not `rustc`.

**Comment by Manishearth** [comment]
It's a typo on my side, I don't really care what the name is, I like rustc-dev

**Comment by Mark-Simulacrum** [comment]
> Is there a nightly manifest published with this content for me to work from?

I think we don't produce manifests until we build nightlies -- it might be possible to do so manually, the commit hash for a try build is `98951af235be5a9ac3aa0b556298b09d97d97924` as noted above.

**Comment by cuviper** [comment]
@bjorn3 
> I believe the manifest has to list every allowed toolchain target + component target combination.

I think that's accomplished here, mimicking what rust-std is doing:
https://github.com/rust-lang/rust/pull/64823/files#diff-2ca914af4ccadf4a4cafbf6a7bc13dcdR503-R507

@kinnison 
> Is there a nightly manifest published with this content for me to work from?

AFAICS the try build didn't generate that. I'd be happy to run it locally, if you can tell me how. :slightly_smiling_face:

**Comment by kinnison** [comment]
I don't know how the manifest files get generated per-se, though the tool is somewhere in this repo I believe.  It'd be much much easier for me if there's a release containing the updated manifest, even if it's on dev-static or similar for me to try against.

Also, if anyone has an idea for how the UX for this would feel, I'd appreciate input.  Currently installing `rust-std` for a non-host target is `rustup target add $arch`

**Comment by Mark-Simulacrum** [comment]
I believe you can build manifests with https://github.com/rust-lang/rust/tree/master/src/tools/build-manifest

It'd be great to come up with a way to publish a dev-static released nightly from a given PR build -- cc @pietroalbini -- to experiment with things like this without just shipping possibly broken nightlies.

**Comment by cuviper** [comment]
Oh hey, there's a build-manifest/README that tells how to test it!

Here the channel file that I got from my local build: [channel-rust-1.40.0-dev.toml.txt](https://github.com/rust-lang/rust/files/3692512/channel-rust-1.40.0-dev.toml.txt)

**Comment by RalfJung** [comment]
So, did I understand correctly that this means that nothing changes for Miri *users*? They can still do `rustup component add miri-preview` and things will work, they don't need all these extra libs? But Miri *developers* will have to `rustup component add rustc-dev`? If yes, then that seems okay to me. If not, please explain what this change entails.

**Comment by Mark-Simulacrum** [comment]
Yes, that's our current understanding and we won't move forward if it changes. We discussed briefly during core team triage and though we didn't really have quorum today, mostly concluded that we'd like to confirm compiler team is okay with this but otherwise we can probably move forward. @nikomatsakis @pnkfelix Could one of you please kick FCP to merge off?

@cuviper since it sounds like we're moving forward with this change, can you update the description with rustc-dev as the component name? (And any other details we've decided since then)

**Comment by kinnison** [comment]
I have now reviewed the proposed channel manifest and `rustup` and I believe that this will be fully supportable without change to `rustup`.  We've had for a long time the ability to say `rustup component add --target some-other-target rust-std` as "longhand" for `rustup target add some-other-target`

As such the recommendation here would be "If you need the rustc-dev component for a target other than your own, you will need to do `rustup component add --target another-target rustc-dev`" which isn't as pithy as `rustup target add another-target` but given this is only for developers working on miri etc, I think this is likely to be fine.

**Comment by Mark-Simulacrum** [comment]
Thanks for doing that investigation, @kinnison! Results definitely seem good to me.

I've taken a brief glance at the code and it looks good, too.

I've nominated for compiler team -- hopefully we can get FCP kicked off before then, or a discussion at Thursday's compiler team meeting from which we can draw approval here. I'll also briefly bring this up in Thursday's release team meeting since it does affect what we ship, though I don't personally believe that the release team should care too much here (as this is just changing the default set of libraries in such a way that excludes unstable libraries).

**Comment by pietroalbini** [comment]
Opened [a PR](https://github.com/rust-lang/rust-central-station/pull/517) to our release tooling to allow making dev-static releases from arbitrary commits. Also pushed the try build commit to the [`promote-tmp`](https://github.com/rust-lang/rust/tree/promote-tmp) branch.

Once the PR is reviewed this should allow us to make a dev-static nightly release with this PR, without affecting the real releases.

**Comment by pietroalbini** [comment]
A nightly containing this PR is available on the dev server. To install it, run:

```
RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup toolchain install nightly-2019-10-07
```

Note that running the command will override an eventual `nightly-2019-10-07` already installed, and despite the name the nightly doesn't contain today commits, but all commits until 032a53a06ce293571e51bbe621a5c480e8a28e95.

**Comment by stefson** [comment]
Can you please paste an link to the index.html, if there is one, or paste the direct links to the stages here? I can't use rustup, thanks.

**Comment by cuviper** [comment]
@stefson https://dev-static.rust-lang.org/dist/2019-10-07/index.html

File: src/tools/build-manifest/src/main.rs [hunk 2]
```diff
@@ -473,6 +474,7 @@ impl Builder {
         // and so is rust-mingw if it's available for the target.
         components.extend(vec![
             host_component("rustc"),
+            host_component("rustc-dev"),
```
Comment (cuviper) [inline src/tools/build-manifest/src/main.rs]: I noticed that `rustc-dev` was automatically included when installing the dev-static try build, and I think it's because adding it to `components` here made it mandatory. That's fine for nightly, perhaps even what we want (for now), but we probably don't want that by default on beta or stable channels. I will add a conditional for this.

Comment (cuviper) [reply src/tools/build-manifest/src/main.rs]: Done.

**Comment by kinnison** [comment]
It's worth noting that the component vs. extensions thing will only be relevant until the next rustup release (and for those running older rustups)  Profiles will deal with it beyond then.

**Comment by cuviper** [comment]
Hmm, so we need to add `rustc-dev` to the default profile for nightly users? And *maybe* in the complete profile for all channels?

https://github.com/rust-lang/rust/blob/f64a798c1d08dd4da3fb011a4f32b93a659979e4/src/tools/build-manifest/src/main.rs#L417-L430

**Comment by kinnison** [comment]
Assuming you're trying to ensure that it's installed by default for nightly people and so on then yes, that's almost certainly what needs to be done.  @nrc can confirm for sure, but in his absence, I believe that's right.  Once you have a suitable channel manifest on dev-static you can try with rustup's master if you want (I can provide instructions for that)

**Comment by nrc** [comment]
> Hmm, so we need to add rustc-dev to the default profile for nightly users? And maybe in the complete profile for all channels?

It should be in the same profile for all channels, I think. I don't think it should be in the default profile, just the complete one.

**Comment by cuviper** [comment]
I'm OK either way for nightly -- I just don't want all that stuff by default on stable. :slightly_smiling_face: 
(I think it's questionable for stable's `complete` profile too, but I don't care as much.)

**Comment by Centril** [comment]
The compiler team discussed the prospect of an FCP this week at the meeting and [they felt that they weren't best suited](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-10-10.20.2354818/near/177814900) for this PR and [decided to pass the ball to T-release](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-10-10.20.2354818/near/177815127).

Keeping this nominated for the release team.

**Comment by mati865** [comment]
I couldn't find it in the discussion, sorry if it has been already spoken of.

>>Clippy and RLS link to the libraries rustc links to in the distribution, but if you're just using them I don't think you need the rust-dev packages.

> Right, they're ultimately linked to librustc_driver.so, which users get in the rustc component.

If `rustc-dev` is missing and somebody installs and tries to run a tool will it a) automagically download `rustc-dev`, b) print friendly message, or c) print message unfriendly to inexperienced users?

**Comment by pietroalbini** [comment]
> If rustc-dev is missing and somebody installs and tries to run a tool will it a) automagically download rustc-dev, b) print friendly message, or c) print message unfriendly to inexperienced users?

My understanding is people using tools won't need `rustc-dev` at all. Tools developers will.

**Comment by Mark-Simulacrum** [comment]
We discussed this in today's release team meeting and concluded that we're going to merge this PR as it is. It changes essentially nothing on nightly, and changes the defaults on stable/beta to _not_ install the rustc-dev component. @cuviper is also going to work on a PR which will be FCP'd that will change the default on nightly to not installing the rustc-dev component as well.

The main reasoning for landing this PR first is to keep the FCP focused on a small subset of the changes this PR makes. We also want to make sure that the next beta/stable releases (i.e., 1.40 and onwards) get the wins of a much smaller distribution due to omitting the second set of compiler artifacts.

This'll also help us get testing for the tooling around the component being optional, though preliminary results based on the try build are positive.

Thanks for doing the legwork here @cuviper!

@bors r+

**Comment by stefson** [comment]
may I ask, can this fix be backported to the rust-1.39 branch? Or will it be available only for >=rust-1.40?

**Comment by Mark-Simulacrum** [comment]
This will not be backported for the 1.39 branch (it's a rather big PR).

**Comment by RalfJung** [comment]
@cup this PR doesn't retroactively fix nightlies released before it landed. ;) The next nightly should be better.

**Comment by RalfJung** [comment]
Looks like something went wrong with this PR: Despite adding `-c rustc-dev` to the `rustup-toolchain-install-master` invocation, Miri [fails to build](https://github.com/rust-lang/miri/pull/984), saying
```
error[E0463]: can't find crate for `syntax`
 --> src/lib.rs:9:1
  |
9 | extern crate syntax;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

**Comment by lzutao** [comment]
Clippy also failed to build:
```rust
error[E0463]: can't find crate for `rustc`
  --> /home/lzutao/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.23/src/lib.rs:19:1
   |
19 | extern crate rustc;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

**Comment by phansch** [comment]
At least according to https://github.com/rust-lang/rust/pull/64823#issuecomment-538491294, I think we'll have to patch RTIM to _really_ install the rustc-dev component?

**Comment by RalfJung** [comment]
Hm... @kennytm any idea why adding `-c rustc-dev` currently doesn't actually properly install that component?

**Comment by kennytm** [comment]
@RalfJung could you file an issue in `rustup-toolchain-install-master`? I guess it is similar to kennytm/rustup-toolchain-install-master#15.

**Comment by lzutao** [comment]
@cuviper I examine the rustc-dev component and I see that there is different in how
rustc-dev and rustc components packaged.

In particular, rustc-dev has this path: `rustc-dev-nightly-x86_64-unknown-linux-gnu/rustc-dev`**`-x86_64-unknown-linux-gnu`**.
While rustc component only has `rustc-nightly-x86_64-unknown-linux-gnu/rustc`.

Is additional **`-x86_64-unknown-linux-gnu`** part necessary?

**Comment by cuviper** [comment]
I think that's a consequence of it being a cross-target available component. It looks like ` rustup-toolchain-install-master` treats `rust-std` specially in this regard, so maybe it needs the same for `rustc-dev`?

**Comment by RalfJung** [comment]
Here's a hack that at least lets us build Miri and Clippy again: https://github.com/kennytm/rustup-toolchain-install-master/pull/25

**Comment by jethrogb** [comment]
This PR likely broke targets with 3rd party objects, https://github.com/rust-lang/rust/issues/65335

**Comment by kennytm** [comment]
All PRs filed involving `rustc-dev` has been merged and published as v1.7.0.

**Comment by RalfJung** [comment]
FWIW this is being reverted in #65342 because of the [problems it caused](https://github.com/rust-lang/rust/issues/65335).

**Comment by stefson** [comment]
Since it was reverted due to problems, is this pullrequest going to be rebooted at some point in the future?
