### PR TITLE
Tweak `self` arg not as first argument of a method diagnostic

### LINKED ISSUE #51547: E0424 short message weirdly confusing
This invalid function gives two instances of E0424.

```
fn foo(self: i32) -> i32 { self }
```

```
error[E0424]: expected unit struct/variant or constant, found module `self`
 --> src/main.rs:8:8
  |
L | fn foo(self: i32) -> i32 { self }
  |        ^^^^ `self` value is only available in methods with `self` parameter

error[E0424]: expected value, found module `self`
 --> src/main.rs:8:28
  |
L | fn foo(self: i32) -> i32 { self }
  |                            ^^^^ `self` value is only available in methods with `self` parameter
```

The long diagnostic for this error states "The self keyword was used in a static method." which while slightly wrong in this case (it's a free function, not a method at all), it's more correct than what's emitted by the compiler.

Overall, this diagnostic needs to be cleaned up.

1. In the first instance, the error message should state "`self` parameter can only be declared on methods".
2. In the first instance, the help message should just be removed.
3. In the second instance, it probably shouldn't even be emitted. Possibly check if a parameter was erroneously named `self` and if so, pretend it's a valid variable name in the function. Maybe a `note` pointing out its usage as part of the first emitted error would be okay here?
4. The long error description (in the error index) should say "free function or method".

### PR DESCRIPTION
**Pull request by estebank**
Mention that `self` is only valid on "associated functions"
```
error: unexpected `self` argument in function
  --> $DIR/self-in-function-arg.rs:1:15
   |
LL | fn foo(x:i32, self: i32) -> i32 { self }
   |               ^^^^ not valid as function argument
   |
   = note: `self` is only valid as the first argument of an associated function
```

When it is a method, mention it must be first
```
error: unexpected `self` argument in function
  --> $DIR/trait-fn.rs:4:20
   |
LL |     fn c(foo: u32, self) {}
   |                    ^^^^ must be the first associated function argument
```

Move a bunch of error recovery methods to `diagnostics.rs` away from `parser.rs`.

Fix #51547. CC #60015.

### CODE REVIEW

File: src/libsyntax/parse/diagnostics.rs [hunk 1]
```diff
@@ -60,6 +146,449 @@ impl RecoverQPath for Expr {
 }
 
 impl<'a> Parser<'a> {
+    pub fn look_ahead<R, F>(&self, dist: usize, f: F) -> R where
```
Comment (petrochenkov) [inline src/libsyntax/parse/diagnostics.rs]: This function is not diagnostics specific.

File: src/libsyntax/parse/diagnostics.rs [hunk 2]
```diff
@@ -501,6 +1030,141 @@ impl<'a> Parser<'a> {
...
+    }
+
+    crate fn recover_bad_self_arg(
+        &mut self,
+        mut arg: ast::Arg,
+        is_trait_item: bool,
+    ) -> PResult<'a, ast::Arg> {
+        let sp = arg.pat.span;
+        arg.ty.node = TyKind::Err;
+        let mut err = self.struct_span_err(sp, "unexpected `self` argument in function");
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]:
```suggestion
        let mut err = self.struct_span_err(sp, "unexpected `self` parameter in function");
```

File: src/libsyntax/parse/diagnostics.rs [hunk 3]
```diff
@@ -501,6 +1030,141 @@ impl<'a> Parser<'a> {
...
+        if is_trait_item {
+            err.span_label(sp, "must be the first associated function argument");
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]:
```suggestion
            err.span_label(sp, "must be the first associated function parameter");
```

File: src/libsyntax/parse/diagnostics.rs [hunk 4]
```diff
@@ -501,6 +1030,141 @@ impl<'a> Parser<'a> {
...
+        } else {
+            err.span_label(sp, "not valid as function argument");
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]:
```suggestion
            err.span_label(sp, "not valid as function parameter");
```

File: src/libsyntax/parse/diagnostics.rs [hunk 5]
```diff
@@ -501,6 +1030,141 @@ impl<'a> Parser<'a> {
...
+            err.note("`self` is only valid as the first argument of an associated function");
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]:
```suggestion
            err.note("`self` is only valid as the first parameter of an associated function");
```

**Review by Centril — CHANGES_REQUESTED** [review]

File: src/libsyntax/parse/diagnostics.rs [hunk 6]
```diff
@@ -60,6 +146,449 @@ impl RecoverQPath for Expr {
...
+        }
+        err
+    }
+
+    /// Expects and consumes the token `t`. Signals an error if the next token is not `t`.
+    pub fn expect(&mut self, t: &token::Token) -> PResult<'a,  bool /* recovered */> {
+        if self.expected_tokens.is_empty() {
+            if self.token == *t {
+                self.bump();
+                Ok(false)
```
Comment (petrochenkov) [inline src/libsyntax/parse/diagnostics.rs]: Functions like this have a small "good" path (which doesn't belong to diagnostics) and the remaining big part belonging to diagnostics.
In this case perhaps it's reasonable to split them into two functions, one in `parse.rs` and another in `diagnostics.rs`.

File: src/libsyntax/parse/diagnostics.rs [hunk 7]
```diff
@@ -60,6 +146,449 @@ impl RecoverQPath for Expr {
...
+        inedible: &[token::Token],
+    ) -> PResult<'a, bool /* recovered */> {
+        fn tokens_to_string(tokens: &[TokenType]) -> String {
+            let mut i = tokens.iter();
+            // This might be a sign we need a connect method on Iterator.
+            let b = i.next()
+                     .map_or(String::new(), |t| t.to_string());
+            i.enumerate().fold(b, |mut b, (i, a)| {
+                if tokens.len() > 2 && i == tokens.len() - 2 {
+                    b.push_str(", or ");
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]: Refactor out `b.push_str(connective)`?

File: src/libsyntax/parse/diagnostics.rs [hunk 8]
```diff
@@ -60,6 +146,449 @@ impl RecoverQPath for Expr {
...
+
+        match self.token_cursor.frame.tree_cursor.look_ahead(dist - 1) {
+            Some(TokenTree::Token(span, _)) => span,
+            Some(TokenTree::Delimited(span, ..)) => span.entire(),
+            None => self.look_ahead_span(dist - 1),
+        }
+    }
+
+    pub fn fatal(&self, m: &str) -> DiagnosticBuilder<'a> {
+        self.sess.span_diagnostic.struct_span_fatal(self.span, m)
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]:
```suggestion
        self.span_fatal(self.span, m)
```

**Comment by Centril** [comment]
I'll do a more thorough review later.

@estebank Can you split the "move stuff" and "change diagnostics output" into separate commits?

**Review by Centril — CHANGES_REQUESTED** [review]

**Comment by estebank** [comment]
@Centril addressed all review comments but one, which I think should be part of a separate PR cleaning up all the times this has been done in the parser.

**Review by Centril — COMMENTED** [review]
r=me with rebase and possibly a fix to the comment below

File: src/libsyntax/parse/diagnostics.rs [hunk 9]
```diff
@@ -542,6 +1017,138 @@ impl<'a> Parser<'a> {
...
+        Ok((pat, ty))
+    }
+
+    crate fn recover_bad_self_arg(
+        &mut self,
+        mut arg: ast::Arg,
+        is_trait_item: bool,
+    ) -> PResult<'a, ast::Arg> {
+        let sp = arg.pat.span;
+        arg.ty.node = TyKind::Err;
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/libsyntax/parse/diagnostics.rs]: Because we don't _know_ wether this is any of the following:

- a function with an arbitrary argument called `self`
- a method with `self` not at the start
- a method with `self` at the start _and_ a second `self`

I thought it'd be safer to just mark it as `TyKind::Err` and avoid potential incorrect diagnostics elsewhere.

[the remark this answers is not in the document]
Comment (Centril) [reply src/libsyntax/parse/diagnostics.rs]: Good insight; on the other hand, I'd say that `self` not at the start is probabilistically more correct than the others... but, in any case, let's land this as-is. :)
