### PR TITLE
Location-sensitive polonius prototype: endgame

### LINKED ISSUE #127628: ICE: `polonius loan scopes differ from NLL borrow scopes,`
auto-reduced (treereduce-rust):
````rust
use std::io::{self, Read};

pub struct Container<'a> {
    reader: &'a mut dyn Read,
}

impl<'a> Container {
    pub fn wrap<'s>(reader: &'s mut dyn io::Read) -> Container<'s> {
        Container { reader: reader }
    }
}


````

original:
````rust
use std::io::{self, Read};
use std::vec;

pub struct Container<'a> {
    reader: &'a mut dyn Read
}

impl<'a> Container<'local_mac_tt> {
    pub fn wrap<'s>(reader: &'s mut dyn io::Read) -> Container<'s> {
        Container { reader: reader }
    }

    pub fn read_to(&mut self, vec: &mut [u8]) {
        self.reader.read(3, 4);
    }
}

pub fn for_stdin<'a>() -> Container<'dropping_copy_types> {
    let mut r = io::stdin();
    Container::wrap(&mut r as &mut dyn io::Read)
    //~^ ERROR cannot return value referencing local variable
}

fn main() {
    let mut c = for_stdin();
    let (Ok(_x) | Err(!)) = &res;
    c.read_to(v); //~ ERROR E0308
}

````

Version information
````
rustc 1.81.0-nightly (bcf1f6db4 2024-07-11)
binary: rustc
commit-hash: bcf1f6db4594ae6132378b179a30cdb3599a863d
commit-date: 2024-07-11
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zpolonius=next`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0726]: implicit elided lifetime not allowed here
 --> /tmp/icemaker_global_tempdir.4feaX3V4ADCu/rustc_testrunner_tmpdir_reporting.ZXhnCcXmdGdv/mvce.rs:7:10
  |
7 | impl<'a> Container {
  |          ^^^^^^^^^ expected lifetime parameter
  |
help: indicate the anonymous lifetime
  |
7 | impl<'a> Container<'_> {
  |                   ++++

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.4feaX3V4ADCu/rustc_testrunner_tmpdir_reporting.ZXhnCcXmdGdv/mvce.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.4feaX3V4ADCu/rustc_testrunner_tmpdir_reporting.ZXhnCcXmdGdv/mvce.rs`

thread 'rustc' panicked at compiler/rustc_borrowck/src/dataflow.rs:418:13:
assertion `left == right` failed: polonius loan scopes differ from NLL borrow scopes, for body /tmp/icemaker_global_tempdir.4feaX3V4ADCu/rustc_testrunner_tmpdir_reporting.ZXhnCcXmdGdv/mvce.rs:8:5: 10:6 (#0)
  left: {bb0[3]: [bw0]}
 right: {bb0[4]: [bw0]}
stack backtrace:
   0:     0x7362c658f655 - std::backtrace_rs::backtrace::libunwind::trace::hcb29af1cb57bcb8d
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7362c658f655 - std::backtrace_rs::backtrace::trace_unsynchronized::he36459e1f5f5e93a
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7362c658f655 - std::sys::backtrace::_print_fmt::heffc99ac4b4675cf
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/backtrace.rs:68:5
   3:     0x7362c658f655 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf245997fe8a5daf1
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/backtrace.rs:44:22
   4:     0x7362c65ded3b - core::fmt::rt::Argument::fmt::h0e5779e064dbb7df
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/core/src/fmt/rt.rs:173:76
   5:     0x7362c65ded3b - core::fmt::write::h98cec97192061fdf
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/core/src/fmt/mod.rs:1182:21
   6:     0x7362c658403f - std::io::Write::write_fmt::he6c3afdd93fdc681
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/io/mod.rs:1835:15
   7:     0x7362c658f42e - std::sys::backtrace::_print::h636b421fd7a2e420
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/backtrace.rs:47:5
   8:     0x7362c658f42e - std::sys::backtrace::print::haa02f8c85818b01f
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/backtrace.rs:34:9
   9:     0x7362c6591d79 - std::panicking::default_hook::{{closure}}::h50c9c60844185e9c
  10:     0x7362c6591b1c - std::panicking::default_hook::hde778ca172ded902
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/panicking.rs:292:9
  11:     0x7362c2a21c59 - std[ad414beb854749b5]::panicking::update_hook::<alloc[4dde9fbc2019d87d]::boxed::Box<rustc_driver_impl[7c2f87ab8379164f]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7362c659269f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h77bec8c01b3205fe
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/alloc/src/boxed.rs:2078:9
  13:     0x7362c659269f - std::panicking::rust_panic_with_hook::h02aa1f3fa26e53db
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/panicking.rs:804:13
  14:     0x7362c65922c7 - std::panicking::begin_panic_handler::{{closure}}::he573aa5eefbb7bfc
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/panicking.rs:670:13
  15:     0x7362c658fb19 - std::sys::backtrace::__rust_end_short_backtrace::ha97f3bba049b4ef0
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/backtrace.rs:171:18
  16:     0x7362c6591f54 - rust_begin_unwind
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/panicking.rs:661:5
  17:     0x7362c65db2f3 - core::panicking::panic_fmt::hd5960ad38e738d13
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/core/src/panicking.rs:74:14
  18:     0x7362c65db8cf - core::panicking::assert_failed_inner::h02724f5e69869174
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/core/src/panicking.rs:405:23
  19:     0x7362c26d1527 - core[5577311df7d42be1]::panicking::assert_failed::<indexmap[5fb9d275e5314e4d]::map::IndexMap<rustc_middle[77b0c22bfadf3e56]::mir::Location, alloc[4dde9fbc2019d87d]::vec::Vec<rustc_borrowck[6a0718d1facf5b73]::dataflow::BorrowIndex>, core[5577311df7d42be1]::hash::BuildHasherDefault<rustc_hash[fad87a7c8a3801b7]::FxHasher>>, indexmap[5fb9d275e5314e4d]::map::IndexMap<rustc_middle[77b0c22bfadf3e56]::mir::Location, alloc[4dde9fbc2019d87d]::vec::Vec<rustc_borrowck[6a0718d1facf5b73]::dataflow::BorrowIndex>, core[5577311df7d42be1]::hash::BuildHasherDefault<rustc_hash[fad87a7c8a3801b7]::FxHasher>>>
  20:     0x7362c504194c - rustc_borrowck[6a0718d1facf5b73]::do_mir_borrowck
  21:     0x7362c5025142 - rustc_query_impl[996ec1e1a9f37899]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[996ec1e1a9f37899]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[77b0c22bfadf3e56]::query::erase::Erased<[u8; 8usize]>>
  22:     0x7362c43a47b3 - rustc_query_system[f92dbd75fbf471ce]::query::plumbing::try_execute_query::<rustc_query_impl[996ec1e1a9f37899]::DynamicConfig<rustc_query_system[f92dbd75fbf471ce]::query::caches::VecCache<rustc_span[9d9e1055ab85fce3]::def_id::LocalDefId, rustc_middle[77b0c22bfadf3e56]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[996ec1e1a9f37899]::plumbing::QueryCtxt, false>
  23:     0x7362c43a420d - rustc_query_impl[996ec1e1a9f37899]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7362c4397a21 - rustc_interface[d8bba0fea4cb4dbe]::passes::analysis
  25:     0x7362c4396c07 - rustc_query_impl[996ec1e1a9f37899]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[996ec1e1a9f37899]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[77b0c22bfadf3e56]::query::erase::Erased<[u8; 1usize]>>
  26:     0x7362c4ef7be5 - rustc_query_system[f92dbd75fbf471ce]::query::plumbing::try_execute_query::<rustc_query_impl[996ec1e1a9f37899]::DynamicConfig<rustc_query_system[f92dbd75fbf471ce]::query::caches::SingleCache<rustc_middle[77b0c22bfadf3e56]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[996ec1e1a9f37899]::plumbing::QueryCtxt, false>
  27:     0x7362c4ef794f - rustc_query_impl[996ec1e1a9f37899]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7362c4df7305 - rustc_interface[d8bba0fea4cb4dbe]::interface::run_compiler::<core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>, rustc_driver_impl[7c2f87ab8379164f]::run_compiler::{closure#0}>::{closure#1}
  29:     0x7362c4dc5509 - std[ad414beb854749b5]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d8bba0fea4cb4dbe]::util::run_in_thread_with_globals<rustc_interface[d8bba0fea4cb4dbe]::util::run_in_thread_pool_with_globals<rustc_interface[d8bba0fea4cb4dbe]::interface::run_compiler<core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>, rustc_driver_impl[7c2f87ab8379164f]::run_compiler::{closure#0}>::{closure#1}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>::{closure#0}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>
  30:     0x7362c4dc52ba - <<std[ad414beb854749b5]::thread::Builder>::spawn_unchecked_<rustc_interface[d8bba0fea4cb4dbe]::util::run_in_thread_with_globals<rustc_interface[d8bba0fea4cb4dbe]::util::run_in_thread_pool_with_globals<rustc_interface[d8bba0fea4cb4dbe]::interface::run_compiler<core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>, rustc_driver_impl[7c2f87ab8379164f]::run_compiler::{closure#0}>::{closure#1}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>::{closure#0}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5577311df7d42be1]::result::Result<(), rustc_span[9d9e1055ab85fce3]::ErrorGuaranteed>>::{closure#2} as core[5577311df7d42be1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x7362c659c4fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4b9d0e9c592a6ae1
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/alloc/src/boxed.rs:2064:9
  32:     0x7362c659c4fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6892ad45769a753a
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/alloc/src/boxed.rs:2064:9
  33:     0x7362c659c4fb - std::sys::pal::unix::thread::Thread::new::thread_start::h4695e9cd59270e16
                               at /rustc/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sys/pal/unix/thread.rs:108:17
  34:     0x7362bf4a6ded - <unknown>
  35:     0x7362bf52a0dc - <unknown>
  36:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (bcf1f6db4 2024-07-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polonius=next -Z dump-mir-dir=dir

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at /tmp/icemaker_global_tempdir.4feaX3V4ADCu/rustc_testrunner_tmpdir_reporting.ZXhnCcXmdGdv/mvce.rs:7:1: 7:19>::wrap`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0601, E0726.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by lqd**
This PR sets up the naive location-sensitive analysis end-to-end, and replaces the location-insensitive analysis. It's roughly all the in-progress work I wanted to land for the prototype, modulo cleanups I still want to do after the holidays, or the polonius debugger, and so on.

Here, we traverse the localized constraint graph, have to deal with kills and time-traveling (👌), and record that as loan liveness for the existing scope and active loans computations.

Then the near future looks like this, especially if the 2025h1 project goal is accepted:
- gradually bringing it up to completion
- analyzing and fixing the few remaining test failures
- going over the *numerous* fixmes in this prototype (one of which is similar to a hang on one test's millions and millions of constraints)
- trying to see how to lower the impact of the lack of NLL liveness optimization on diagnostics, and their categorization of local variables and temporaries (the vast majority of blessed expectations differences), as well as the couple ICEs trying to find an NLL constraint to blame for errors.
- dealing with the theoretical weakness around kills, conflating reachability for the two TCS, etc that is described ad nauseam in the code.
- switching the compare mode to the in-tree implementation, and blessing the diagnostics 
- apart from the hang, it's not catastrophically slower on our test suite, so then we can try to enable it on CI
- checking crater, maybe trying to make it faster :3, etc.

I've tried to gradually introduce this PR's work over 4 commits, because it's kind of subtle/annoying, and Niko/I are not completely convinced yet. That one comment explaining the situation is maybe 30% of the PR 😓. Who knew that spacetime reachability and time-traveling could be mind bending. 

I kinda found this late and the impact on this part of the computation was a bit unexpected to us. A bit more care/thought will be needed here. I've described my plan in the comments though. In any case, I believe we have the current implementation is a conservative approximation that shouldn't result in unsoundness but false positives at worst. So it feels fine for now.

r? @jackh726 

---

Fixes #127628 -- which was a assertion triggered for a difference in loan computation between NLLs and the location-insensitive analysis. That doesn't exist anymore so I've removed this crash test.

### CODE REVIEW

**Comment by lqd** [comment]
<sub>borrow checking is easy with time travel and spacetime reachability</sub>

image

**Review by jackh726 — COMMENTED** [review]
Just starting to review

File: compiler/rustc_borrowck/src/polonius/mod.rs [hunk 1]
```diff
@@ -113,8 +124,19 @@ impl PoloniusContext {
...
+        // Now that we have a complete graph, we can compute reachability to trace the liveness of
+        // loans for the next step in the chain, the NLL loan scope and active loans computations.
+        let mut live_loans = LiveLoans::new(borrow_set.len());
+        compute_loan_liveness(
+            tcx,
+            body,
+            regioncx.liveness_constraints(),
+            borrow_set,
+            &localized_outlives_constraints,
+            &mut live_loans,
```
[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/mod.rs]: Sure. The goal was to give a mut ref from the context. It's annoying to do now because some of the regioncx data is accessible through a shared ref and we need to mutate the context or live loans, so I've left doing that to a future PR (or if we come up with a better design now that we have all the flow mapped out).

Until then, I've force pushed returning the live loans as you suggested.

**Comment by lqd** [comment]
Rebased and marked ready to review (but jack had already started) now that #134920 has landed.

**Comment by lqd** [comment]
(This last force push was to fix conflicts and can be ignored)

File: compiler/rustc_borrowck/src/dataflow.rs [hunk 2]
```diff
@@ -461,34 +460,26 @@ impl<'a, 'tcx> Borrows<'a, 'tcx> {
...
-            borrows_out_of_scope_at_location = polonius_prec.loans_out_of_scope_at_location;
-        }
+        let borrows_out_of_scope_at_location =
+            if !tcx.sess.opts.unstable_opts.polonius.is_next_enabled() {
+                calculate_borrows_out_of_scope_at_location(body, regioncx, borrow_set)
+            } else {
+                // The in-tree polonius analysis computes loans going out of scope using the
+                // set-of-loans model.
+                let mut polonius_prec = PoloniusOutOfScopePrecomputer::new(body, regioncx);
+                for (loan_idx, loan_data) in borrow_set.iter_enumerated() {
```
Comment (jackh726) [inline compiler/rustc_borrowck/src/dataflow.rs:470]: I know this is preexisting, but personally I would prefer this to be inside `PoloniusOutOScopePrecomputer::new` (you could rename to `compute` and make it return `loans_out_of_scope_at_location`.

This could be done in a separate PR (before or after this PR lands).

File: compiler/rustc_borrowck/src/polonius/mod.rs [hunk 3]
```diff
@@ -98,7 +98,7 @@ impl PoloniusContext {
     pub(crate) fn compute_loan_liveness<'tcx>(
         &self,
         tcx: TyCtxt<'tcx>,
-        regioncx: &RegionInferenceContext<'tcx>,
+        regioncx: &mut RegionInferenceContext<'tcx>,
```
Comment (jackh726) [inline compiler/rustc_borrowck/src/polonius/mod.rs:101]: I'm looking at this. It might be a slightly bigger refactor, but I wonder if it makes sense to move `live_loans` out of RegionInferenceContext. You basically need to manually pass it anywhere you use `is_loan_live_at`, but there must *already* be some special handling wherever that is, or it would panic.

Thoughts?

**Review by jackh726 — COMMENTED** [review]
Some more review comments not all the way done.

File: compiler/rustc_borrowck/src/polonius/loan_liveness.rs [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+        let source = LocalizedNode { region: constraint.source, point: constraint.from };
+        let target = LocalizedNode { region: constraint.target, point: constraint.to };
+        edges.entry(source).or_default().insert(target);
+    }
+
+    edges
+}
+
+/// Returns the outgoing edges of a given node, not its transitive closure.
+fn outgoing_edges(
```
[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/loan_liveness.rs:153]: We do add the logical edges there in https://github.com/rust-lang/rust/pull/135290/commits/da1a5ae87b24d33d618ee5671822d6c8b56e7e3b#diff-954e3381998b1d9ebf23c2136c0289705886245ef103e76127bd4a63e559e861R178

File: compiler/rustc_borrowck/src/dataflow.rs (hunk 2 above)
Comment (lqd) [reply compiler/rustc_borrowck/src/dataflow.rs:470]: I can do that in the next PR, sure. The structure used to be identical to the NLL scope precomputer in this function, but that was since moved out to `calculate_borrows_out_of_scope_at_location`. I’ll try to keep the symmetry with NLLs and do what you suggest there as well if possible.

File: compiler/rustc_borrowck/src/polonius/mod.rs (hunk 3 above)
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/mod.rs:101]: Sure, I can look into it for a follow up PR. What’s the goal you’re trying to achieve? 

My recollection is that only the scope precomputer accesses these, so while there’s no special handling per se, it sounds possible to pass these optional live loans when creating the `Borrows` data flow computation instead.

File: compiler/rustc_borrowck/src/polonius/loan_liveness.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/loan_liveness.rs:153]: I can slightly simplify it here though.

[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/loan_liveness.rs:152]: It was a trivial simplification so I didn't put it in its own commit and absorbed it into https://github.com/rust-lang/rust/pull/134980/commits/877fee9543a3376c5f7171858ff42f504b828e99

File: compiler/rustc_borrowck/src/dataflow.rs (hunk 2 above)
Comment (lqd) [reply compiler/rustc_borrowck/src/dataflow.rs]: I pushed a commit to do this

**Comment by lqd** [comment]
(Force pushed to fix conflicts, not to push new code that needs reviewing)

File: compiler/rustc_borrowck/src/polonius/loan_liveness.rs [hunk 5]
```diff
@@ -42,7 +54,16 @@ pub(super) fn compute_loan_liveness<'tcx>(
             // Record the loan as being live on entry to this point.
             live_loans.insert(node.point, loan_idx);
 
+            // Continuing traversal will depend on whether the loan is killed at this point.
+            let current_location = liveness.location_from_point(node.point);
+            let is_loan_killed =
+                kills.get(&current_location).is_some_and(|kills| kills.contains(&loan_idx));
+
             for succ in outgoing_edges(&graph, node) {
+                // If the loan is killed at this point, it is killed _on exit_.
```
[the remark this answers is not in the document]
Comment (jackh726) [reply compiler/rustc_borrowck/src/polonius/loan_liveness.rs]: Ah, this is modified later.

File: compiler/rustc_borrowck/src/polonius/mod.rs (hunk 3 above)
Comment (lqd) [reply compiler/rustc_borrowck/src/polonius/mod.rs:101]: I see. A possibility could be if we were to duplicate more of the borrowck into two instead of one handling multiple codepaths, we wouldn’t have options.
