### PR TITLE
[rustdoc] Don't document stripped items in JSON renderer.

### LINKED ISSUE #80664: ICE on rustdoc-json with re-export due to ID collision
### Code

```Rust
mod inner {
    pub struct Public;
}
pub use inner::Public as Reexported;
```

### Meta
Invoke with `rustdoc broke.rs --output-format json`

`rustdoc --version --verbose`:
```
rustdoc 1.51.0-nightly (fde692739 2021-01-02)
binary: rustdoc
commit-hash: fde692739576089729885b7f79aa2232cb9778c5
commit-date: 2021-01-02
host: x86_64-apple-darwin
release: 1.51.0-nightly
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:4"), crate_id: 0, name: Some("Reexported"), source: Some(Span { filename: "broke.rs", begin: (2, 4), end: (2, 22) }), visibility: Public, docs: "", links: {}, attrs: [], deprecation: None, kind: Struct, inner: StructItem(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [Id("0:9"), Id("0:10"), Id("0:11"), Id("0:13"), Id("0:14")] }) }`,
 right: `Item { id: Id("0:4"), crate_id: 0, name: Some("Public"), source: Some(Span { filename: "broke.rs", begin: (2, 4), end: (2, 22) }), visibility: Public, docs: "", links: {}, attrs: [], deprecation: None, kind: Struct, inner: StructItem(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [Id("0:9"), Id("0:10"), Id("0:11"), Id("0:13"), Id("0:14")] }) }`', src/librustdoc/json/mod.rs:167:17
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
RUST_BACKTRACE=1 rustdoc broke.rs --output-format json
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:4"), crate_id: 0, name: Some("Reexported"), source: Some(Span { filename: "broke.rs", begin: (2, 4), end: (2, 22) }), visibility: Public, docs: "", links: {}, attrs: [], deprecation: None, kind: Struct, inner: StructItem(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [Id("0:9"), Id("0:10"), Id("0:11"), Id("0:13"), Id("0:14")] }) }`,
 right: `Item { id: Id("0:4"), crate_id: 0, name: Some("Public"), source: Some(Span { filename: "broke.rs", begin: (2, 4), end: (2, 22) }), visibility: Public, docs: "", links: {}, attrs: [], deprecation: None, kind: Struct, inner: StructItem(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [Id("0:9"), Id("0:10"), Id("0:11"), Id("0:13"), Id("0:14")] }) }`', src/librustdoc/json/mod.rs:167:17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustdoc::json::JsonRenderer as rustdoc::formats::renderer::FormatRenderer>::item
   3: rustdoc::formats::renderer::run_format
   4: rustdoc::run_renderer
   5: rustc_session::utils::<impl rustc_session::session::Session>::time
   6: rustc_interface::passes::QueryContext::enter
   7: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
   8: rustc_span::with_source_map
   9: rustc_interface::interface::create_compiler_and_run
  10: rustdoc::main_options
  11: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

error: Unrecognized option: 'output-format'
```

</p>
</details>

### Working variants
```rust
mod inner { pub struct Public; }
use inner::Public as Reexported;
```
<details><summary>json</summary>

```json
{
    "root": "0:0",
    "crate_version": null,
    "includes_private": false,
    "index": {
        "0:0": {
            "id": "0:0",
            "inner": {
                "is_crate": true,
                "items": []
            },
            "kind": "module",
            "name": "work1",
            "visibility": "public"
        }
    },
    "paths": {
        "0:0": {
            "crate_id": 0,
            "path": ["work1"],
            "kind": "module"
        }
    },
    "external_crates": {},
    "format_version": 1
}
```

</details>

```rust
mod inner { pub struct Public; }
pub use inner::Public;
```
<details><summary>json</summary>

```json
{
    "root": "0:0",
    "crate_version": null,
    "includes_private": false,
    "index": {
        "0:0": {
            "id": "0:0",
            "inner": {
                "is_crate": true,
                "items": ["0:4"]
            },
            "kind": "module",
            "name": "work2",
            "visibility": "public"
        },
        "0:4": {
            "id": "0:4",
            "inner": {
                "struct_type": "unit",
                "generics": {
                    "params": [],
                    "where_predicates": []
                },
                "fields_stripped": false,
                "fields": [],
                "impls": ["0:9", "0:10", "0:11", "0:13", "0:14"]
            },
            "kind": "struct",
            "name": "Public",
            "visibility": "public"
        }
    },
    "paths": {
        "0:4": {
            "crate_id": 0,
            "path": ["work2", "Public"],
            "kind": "struct"
        },
        "0:0": {
            "crate_id": 0,
            "path": ["work2"],
            "kind": "module"
        }
    },
    "external_crates": {},
    "format_version": 1
}
```

</details>

```rust
pub mod inner { pub struct Public; }
pub use inner::Public as Reexported;
```
<details><summary>json</summary>

```json
{
    "root": "0:0",
    "crate_version": null,
    "includes_private": false,
    "index": {
        "0:6": {
            "id": "0:6",
            "inner": {
                "span": "inner::Public",
                "name": "Reexported",
                "id": "0:4",
                "glob": false
            },
            "kind": "import",
            "name": null,
            "visibility": "public"
        },
        "0:3": {
            "id": "0:3",
            "inner": {
                "is_crate": false,
                "items": ["0:4"]
            },
            "kind": "module",
            "name": "inner",
            "visibility": "public"
        },
        "0:0": {
            "id": "0:0",
            "inner": {
                "is_crate": true,
                "items": ["0:6", "0:3"]
            },
            "kind": "module",
            "name": "work3",
            "visibility": "public"
        },
        "0:4": {
            "id": "0:4",
            "inner": {
                "struct_type": "unit",
                "generics": {
                    "params": [],
                    "where_predicates": []
                },
                "fields_stripped": false,
                "fields": [],
                "impls": ["0:9", "0:10", "0:11", "0:13", "0:14"]
            },
            "kind": "struct",
            "name": "Public",
            "visibility": "public"
        }
    },
    "paths": {
        "0:4": {
            "crate_id": 0,
            "path": ["work3", "inner", "Public"],
            "kind": "struct"
        },
        "0:3": {
            "crate_id": 0,
            "path": ["work3", "inner"],
            "kind": "module"
        },
        "0:0": {
            "crate_id": 0,
            "path": ["work3"],
            "kind": "module"
        }
    },
    "external_crates": {},
    "format_version": 1
}
```

</details>

### Whats happening

The panic is here
https://github.com/rust-lang/rust/blob/db69136369bc2baf3c2244b57e6541dc558d0f2c/src/librustdoc/json/mod.rs#L163-L169

`inner::Public` is being added to the index when is shouldn't (I think), so when `Reexported` is added, the IDs colide, and we bail. 

I think the solution is that `inner::Public` should never have been added into the index.

- Related comment: https://github.com/rust-lang/rust/pull/79751#issuecomment-740116224
- [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/The.20duplication.20in.20json)
- [bless scripts](https://gist.github.com/aDotInTheVoid/a67e18991e7b45a7fdc8980b0126e546)

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Fixes #80664, see [my comment there](https://github.com/rust-lang/rust/issues/80664#issuecomment-797557948) for why

Note that we already do something similar in `convert_item`:

https://github.com/rust-lang/rust/blob/bb4cdf8ec034dca5c056ec9295f38062e5b7e871/src/librustdoc/json/conversions.rs#L28-L31

@rustbot modify labels: +T-rustdoc +A-rustdoc-json

r? @jyn514 
cc @CraftSpider

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
This line

https://github.com/rust-lang/rust/blob/b97fd3e5a1545ab02e18c52e7f3d2e78a5c960bf/src/librustdoc/json/conversions.rs#L182

Should be changed to `unreachable` I think, as we should never call `from_clean_item_kind` on a `StrippedItem`
(or make `from_clean_item_kind` return an `Option`)

File: src/librustdoc/formats/renderer.rs [hunk 1]
```diff
@@ -13,6 +13,10 @@ crate trait FormatRenderer<'tcx>: Sized {
     /// Gives a description of the renderer. Used for performance profiling.
     fn descr() -> &'static str;
 
+    /// Whether to call `item` on `clean::StrippedItem`
+    /// See #80664
+    const RUN_ON_STRIPED: bool;
```
Comment (jyn514) [inline src/librustdoc/formats/renderer.rs:18]:
```suggestion
    const RUN_ON_STRIPPED: bool;
```

File: src/librustdoc/formats/renderer.rs [hunk 2]
```diff
@@ -84,13 +88,22 @@ crate fn run_format<'tcx, T: FormatRenderer<'tcx>>(
...
+
+            if let Some(module) = match *item.kind {
+                clean::ModuleItem(m) => Some(m),
+                clean::StrippedItem(box clean::ModuleItem(m)) => {
+                    if T::RUN_ON_STRIPED {
+                        Some(m)
+                    } else {
+                        None
+                    }
+                }
```
Comment (jyn514) [inline src/librustdoc/formats/renderer.rs:100]: nit: I find this pretty hard to read, I would assign the option to a local variable instead of putting a `match` in the if condition.

**Review by jyn514 — APPROVED** [review]
Looks good assuming my comment in https://github.com/rust-lang/rust/issues/80664#issuecomment-803744519 is accurate that JSON doesn't care about inlining.

**Comment by jyn514** [comment]
> This line
> 
> https://github.com/rust-lang/rust/blob/b97fd3e5a1545ab02e18c52e7f3d2e78a5c960bf/src/librustdoc/json/conversions.rs#L182
> 
> Should be changed to `unreachable` I think, as we should never call `from_clean_item_kind` on a `StrippedItem`
> (or make `from_clean_item_kind` return an `Option`)

Sounds good - could you add that here?

File: src/librustdoc/json/mod.rs [hunk 3]
```diff
@@ -170,12 +170,9 @@ impl<'tcx> FormatRenderer<'tcx> for JsonRenderer<'tcx> {
...
             }
-            let removed = self.index.borrow_mut().insert(from_def_id(id), new_item.clone());
-            // FIXME(adotinthevoid): Currently, the index is duplicated. This is a sanity check
-            // to make sure the items are unique.
-            if let Some(old_item) = removed {
-                assert_eq!(old_item, new_item);
-            }
+            let removed = self.index.borrow_mut().insert(from_def_id(id), new_item);
+
+            assert_matches!(removed, None);
```
Comment (jyn514) [inline src/librustdoc/json/mod.rs:175]:
```suggestion

            assert!(removed.is_none());
```

**Review by jyn514 — COMMENTED** [review]
It looks like you're still making changes, but when you're ready for review - what's going on in https://github.com/rust-lang/rust/pull/83055/commits/bdf6786f91a98c702f7ba624b157c1685a6e5db1 ?

File: src/librustdoc/json/mod.rs (hunk 3 above)
Comment (aDotInTheVoid) [reply src/librustdoc/json/mod.rs:175]: This gives a nicer panic messages when `removed` is `Some`

**Comment by aDotInTheVoid** [comment]
> It looks like you're still making changes, but when you're ready for review - what's going on in [bdf6786](https://github.com/rust-lang/rust/commit/bdf6786f91a98c702f7ba624b157c1685a6e5db1) ?

It turns out that we also don't need to call `item` even for no striped modules. And this fixes the Duplication, at least with the current test suite. I'm trying it with tests for #83057 now, and it looks less promizing.

I'll let you know when this is ready for review

**Comment by aDotInTheVoid** [comment]
This PR is a bit of a mess, but now does 3 things

1. Avoids recursing in `run_format`, controlled by a const in `FormatRenderer`. This fixes #80664. Also add a test for that
2. Adds tests for where the index still has collisions, even with change 1
3. Improvements to `jsondocck` to make the first 2 changes possible

The git history is a mess, and I'd be willing to clean it up and/or split this into 3 pr's if you want

@rustbot modify labels: -S-waiting-on-author +S-waiting-on-review

**Comment by jyn514** [comment]
> It turns out that we also don't need to call item even for non stripped modules. And this fixes the Duplication, at least with the current test suite. I'm trying it with tests for #83057 now, and it looks less promizing.

Can you post what tests fail when you disable this for the HTML backend too? I'd like to keep it in sync with the JSON backend where possible.

**Comment by jyn514** [comment]
> The git history is a mess, and I'd be willing to clean it up and/or split this into 3 pr's if you want

Splitting this into 2 commits - one changing jsondocck, the other fixing the bug - seems fine.

**Comment by jyn514** [comment]
> Adds tests for where the index still has collisions, even with change 1

It wasn't clear to me by reading: which test is this? Where is the collision? Could you add it as a comment?

**Comment by aDotInTheVoid** [comment]
Welp, I guess not. Cant reproduce the error (`./x.py test  src/test/rustdoc-json/reexport/in_root_and_mod_pub.rs`) passes

@rustbot modify labels: -S-waiting-on-review +S-waiting-on-author

**Comment by aDotInTheVoid** [comment]
Rebased onto master, can reproduce
