### PR TITLE
Eliminate mut reference UB in Drop impl for Rc<T>

### LINKED ISSUE #76509: "test_rc_cyclic_with_one_ref" fails in Miri
In the latest [test suite run in Miri](https://travis-ci.org/github/RalfJung/miri-test-libstd/builds/725503482), `test_rc_cyclic_with_one_ref` failed. This test was added in f03d0b38d6a33a64307d83f8ddd3df8ef57ca537 as part of https://github.com/rust-lang/rust/pull/75994. The cyclic `Arc` tests work fine, so either the tests are different or something about the `Rc` implementation is.

The error is "error: Undefined Behavior: not granting access to tag <untagged> because incompatible item is protected: [Unique for <74172040> (call 24024731)]", which means that some memory is deallocated while a mutable reference to it exists that is kept alive because it was passed as an argument to some function that is still running.

Cc @mental32

### PR DESCRIPTION
**Pull request by carbotaniuman**
This changes `self.ptr.as_mut()` with `get_mut_unchecked` which
does not use an intermediate reference.  Arc<T> already handled this
case properly.

Fixes #76509

### CODE REVIEW

**Comment by carbotaniuman** [comment]
Hmm still fails Miri.

File: library/alloc/src/rc.rs [hunk 1]
```diff
@@ -2108,26 +2135,30 @@ trait RcBoxPtr<T: ?Sized> {
...
+        self.weak_ref().set(self.weak() - 1);
     }
 }
 
-impl<T: ?Sized> RcBoxPtr<T> for Rc<T> {
-    #[inline(always)]
-    fn inner(&self) -> &RcBox<T> {
-        unsafe { self.ptr.as_ref() }
+impl<T: ?Sized> RcInnerPtr for RcBox<T> {
+    fn weak_ref(&self) -> &Cell<usize> {
```
Comment (RalfJung) [inline library/alloc/src/rc.rs:2148]: These functions should probably be `#[inline(always)]`, just to be sure.

File: library/alloc/src/rc.rs [hunk 2]
```diff
@@ -844,7 +844,16 @@ impl<T: ?Sized> Rc<T> {
...
     #[unstable(feature = "get_mut_unchecked", issue = "63292")]
     pub unsafe fn get_mut_unchecked(this: &mut Self) -> &mut T {
-        unsafe { &mut this.ptr.as_mut().value }
+        // We are careful to *not* create a reference covering the "count" fields, as
+        // this would alias with concurrent access to the reference counts (e.g. by `Weak`).
+        unsafe { &mut (*this.ptr.as_ptr()).value }
+    }
+
+    #[inline]
+    fn inner(&self) -> &RcBox<T> {
```
Comment (RalfJung) [inline library/alloc/src/rc.rs:853]: Might make sense to move this function up to `fn from_inner`, where such helper functions seem to live. Also it should probably be `inline(always)`.

**Comment by RalfJung** [comment]
Thanks a lot, this is great. :) I just have some minor nits.

File: library/alloc/src/rc.rs [hunk 3]
```diff
@@ -844,7 +844,16 @@ impl<T: ?Sized> Rc<T> {
     #[inline]
     #[unstable(feature = "get_mut_unchecked", issue = "63292")]
     pub unsafe fn get_mut_unchecked(this: &mut Self) -> &mut T {
-        unsafe { &mut this.ptr.as_mut().value }
+        // We are careful to *not* create a reference covering the "count" fields, as
+        // this would alias with concurrent access to the reference counts (e.g. by `Weak`).
```
Comment (RalfJung) [inline library/alloc/src/rc.rs:848]: "concurrent" cannot really happen here.
```suggestion
        // this would conflict with accesses to the reference counts (e.g. by `Weak`).
```

**Comment by RalfJung** [comment]
Looking good, thanks again. :)
@bors r+ rollup
