### PR TITLE
Fix documentation of `Rc::make_mut` regarding `rc::Weak`.

### LINKED ISSUE #60961: Rc::make_mut doesn't clone if there are weak refs
The docs for Rc::make_mut say:

> If there are other Rc or Weak pointers to the same value, then make_mut will invoke clone on the inner value to ensure unique ownership. This is also referred to as clone-on-write.

(See https://doc.rust-lang.org/std/rc/struct.Rc.html#method.make_mut )

As I read the above paragraph, the last line of the following program should not print 'None'. In fact, it does print None, at least on stable rust 1.34.2.

```rust
use std::rc::Rc;

#[derive(Clone,Debug)]
struct Example {
    value: String
}

pub fn main() {
    let mut strong1 = Rc::new(Example{value:"First".to_string()});
    let mut strong2 = strong1.clone();
    let weak2 = Rc::downgrade(&strong2);
    strong2 = Rc::new(Example{value:"Second".to_string()}); //Make sure there is one strong and one weak
    println!("Strong count: {}",Rc::strong_count(&strong1));
    println!("Weak count: {}",Rc::weak_count(&strong1));
    let strong1mut = Rc::make_mut(&mut strong1);  //should clone Example, at least according to docs
    strong1mut.value = "Mutated".to_string();
    let weak2ref = weak2.upgrade();
    println!("Weak: {:?}",weak2ref); //Should not print None, at least docs seem to imply this
    
}

```

I'm not being bit by this, possibly no-one is. Just thought I should report it. 

Edit: The following paragraph didn't make much sense. This is just a doc error. After make_mut has finished, there are no strong refs so the weak refs should just all die anyway. The docs as written don't make sense, the implementation is the only reasonable one.

~~(If I haven't missed anything, and there actually is a discrepancy between the documentation and the code, what would be the correct solution? Changing the code or the docs?)~~

### PR DESCRIPTION
**Pull request by czipperz**
Closes #60961

### CODE REVIEW

File: src/liballoc/rc.rs [hunk 1]
```diff
@@ -584,15 +584,18 @@ impl<T: ?Sized> Rc<T> {
...
     ///
-    /// If there are other `Rc` or [`Weak`][weak] pointers to the same value,
-    /// then `make_mut` will invoke [`clone`][clone] on the inner value to
-    /// ensure unique ownership. This is also referred to as clone-on-write.
+    /// If there are other `Rc` pointers to the same value, then `make_mut` will
+    /// [`clone`] the inner value to ensure unique ownership.  This is also
+    /// referred to as clone-on-write.
     ///
-    /// See also [`get_mut`][get_mut], which will fail rather than cloning.
+    /// If there are not other `Rc` pointers to this value, then [`Weak`]
```
Comment (jonas-schievink) [inline src/liballoc/rc.rs]:
```suggestion
    /// If there are no other `Rc` pointers to this value, then [`Weak`]
```

**Comment by czipperz** [comment]
Ping @bluss

**Comment by Mark-Simulacrum** [comment]
Seems like a fairly straightforward improvement. I'm not a fan of "disassociated" here but can't come up with anything that sounds better so going to approve as-is. Can always iterate later.

@bors r+ rollup
