### PR TITLE
Apply effects to `otherwise` edge in dataflow analysis

### LINKED ISSUE #142705: Drop is called for match wildcards even when all matched variants have no Drop
Consider matching on an enum where multiple variants should match to the same expression. Those variants can be explicitly spelled out in one or more match arms, or they can be grouped with the wildcard pattern `_` instead.

In some cases, spelling out the variants (ideally in a single arm with a pattern like `Variant1 | Variant2`) can generate smaller LLVM IR compared to the wildcard version, and less frequently can generate better machine code. One way this can happen is when another variant in a different match arm has a nontrivial `Drop` but the groupable variants don't. The optimized MIR will still try to drop the whole enum or check for the variants that need `Drop`, potentially leading to larger LLVM IR that takes longer for LLVM to process or results in worse machine code.

---

Here is a simple example, a function that converts a container with multiple full and empty variants to an `Option`:

```rust
pub enum Container {
    Empty1,
    Empty2,
    Full1(String),
    Full2(String),
}

pub fn into_option(container: Container) -> Option<String> {
    match container {
        Container::Full1(s) | Container::Full2(s) => Some(s),
        Container::Empty1 | Container::Empty2 => None,
        // _ => None,
    }
}
```

Both approaches generate similar machine code with `opt-level=3`, but the initial LLVM IR is significantly larger with the wildcard.

<details>
<summary>LLVM IR with variants spelled out</summary>

`rustc -C opt-level=3 -C no-prepopulate-passes --target x86_64-unknown-linux-gnu --emit=llvm-ir`

`into_option` takes 42 lines and the .ll file is 3.01 KiB total.

```llvm
define dso_local void @into_option(ptr dead_on_unwind noalias nocapture noundef writable sret([24 x i8]) align 8 dereferenceable(24) %_0, ptr noalias nocapture noundef readonly align 8 dereferenceable(32) %container) unnamed_addr #0 {
start:
  %_4 = alloca [24 x i8], align 8
  %s = alloca [24 x i8], align 8
  %_2 = load i64, ptr %container, align 8, !range !4, !noundef !5
  switch i64 %_2, label %bb1 [
    i64 0, label %bb2
    i64 1, label %bb2
    i64 2, label %bb4
    i64 3, label %bb3
  ]

bb1:                                              ; preds = %start
  unreachable

bb2:                                              ; preds = %start, %start
  store i64 -9223372036854775808, ptr %_0, align 8
  br label %bb6

bb4:                                              ; preds = %start
  call void @llvm.lifetime.start.p0(i64 24, ptr %s)
  %0 = getelementptr inbounds i8, ptr %container, i64 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %0, i64 24, i1 false)
  br label %bb5

bb3:                                              ; preds = %start
  call void @llvm.lifetime.start.p0(i64 24, ptr %s)
  %1 = getelementptr inbounds i8, ptr %container, i64 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %1, i64 24, i1 false)
  br label %bb5

bb6:                                              ; preds = %bb5, %bb2
  ret void

bb5:                                              ; preds = %bb3, %bb4
  call void @llvm.lifetime.start.p0(i64 24, ptr %_4)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_4, ptr align 8 %s, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_0, ptr align 8 %_4, i64 24, i1 false)
  call void @llvm.lifetime.end.p0(i64 24, ptr %_4)
  call void @llvm.lifetime.end.p0(i64 24, ptr %s)
  br label %bb6
}
```

</details>

<details>
<summary>LLVM IR with wildcard</summary>

`rustc -C opt-level=3 -C no-prepopulate-passes --target x86_64-unknown-linux-gnu --emit=llvm-ir`

`into_option` takes 70 lines and the .ll file is 20.73 KiB total (though that's mostly library functions that a bigger project would call from multiple places).

```llvm
define dso_local void @into_option(ptr dead_on_unwind noalias nocapture noundef writable sret([24 x i8]) align 8 dereferenceable(24) %_0, ptr noalias nocapture noundef align 8 dereferenceable(32) %container) unnamed_addr #0 {
start:
  %_5 = alloca [8 x i8], align 8
  %_4 = alloca [24 x i8], align 8
  %s = alloca [24 x i8], align 8
  %_2 = load i64, ptr %container, align 8, !range !8, !noundef !4
  switch i64 %_2, label %bb1 [
    i64 2, label %bb3
    i64 3, label %bb2
  ]

bb1:                                              ; preds = %start
  store i64 -9223372036854775808, ptr %_0, align 8
  %0 = load i64, ptr %container, align 8, !range !8, !noundef !4
  store i64 %0, ptr %_5, align 8
  %1 = load i64, ptr %_5, align 8, !noundef !4
  switch i64 %1, label %bb4 [
    i64 2, label %bb5
    i64 3, label %bb6
  ]

bb3:                                              ; preds = %start
  call void @llvm.lifetime.start.p0(i64 24, ptr %s)
  %2 = getelementptr inbounds i8, ptr %container, i64 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %2, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr %_4)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_4, ptr align 8 %s, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_0, ptr align 8 %_4, i64 24, i1 false)
  call void @llvm.lifetime.end.p0(i64 24, ptr %_4)
  call void @llvm.lifetime.end.p0(i64 24, ptr %s)
  %3 = load i64, ptr %container, align 8, !range !8, !noundef !4
  store i64 %3, ptr %_5, align 8
  %4 = load i64, ptr %_5, align 8, !noundef !4
  switch i64 %4, label %bb4 [
    i64 2, label %bb4
    i64 3, label %bb6
  ]

bb2:                                              ; preds = %start
  call void @llvm.lifetime.start.p0(i64 24, ptr %s)
  %5 = getelementptr inbounds i8, ptr %container, i64 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %5, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr %_4)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_4, ptr align 8 %s, i64 24, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_0, ptr align 8 %_4, i64 24, i1 false)
  call void @llvm.lifetime.end.p0(i64 24, ptr %_4)
  call void @llvm.lifetime.end.p0(i64 24, ptr %s)
  %6 = load i64, ptr %container, align 8, !range !8, !noundef !4
  store i64 %6, ptr %_5, align 8
  %7 = load i64, ptr %_5, align 8, !noundef !4
  switch i64 %7, label %bb4 [
    i64 2, label %bb5
    i64 3, label %bb4
  ]

bb4:                                              ; preds = %bb6, %bb5, %bb1, %bb2, %bb2, %bb3, %bb3
  ret void

bb6:                                              ; preds = %bb1, %bb3
  %8 = getelementptr inbounds i8, ptr %container, i64 8
; call core::ptr::drop_in_place<alloc::string::String>
  call void @"_ZN4core3ptr42drop_in_place$LT$alloc..string..String$GT$17hb544879c41d56b0bE"(ptr noalias noundef align 8 dereferenceable(24) %8)
  br label %bb4

bb5:                                              ; preds = %bb1, %bb2
  %9 = getelementptr inbounds i8, ptr %container, i64 8
; call core::ptr::drop_in_place<alloc::string::String>
  call void @"_ZN4core3ptr42drop_in_place$LT$alloc..string..String$GT$17hb544879c41d56b0bE"(ptr noalias noundef align 8 dereferenceable(24) %9)
  br label %bb4
}
```

</details>

---

Another example is a `take` function for a container that panics if it's "locked":

```rust
pub enum Container {
    Empty,
    Locked,
    Full(String),
}

pub fn take(container: &mut Container) -> Option<String> {
    match container {
        Container::Empty => None,
        Container::Locked => panic!("you tried to break into the container!"),
        Container::Full(_) => match std::mem::replace(container, Container::Empty) {
            Container::Full(content) => Some(content),
            Container::Empty | Container::Locked => unreachable!(),
            // _ => unreachable!(),
        },
    }
}
```

This time, in addition to larger LLVM IR, the final machine code is larger and contains an unnecessary unreachable check when using `panic_unwind`. (With `panic_abort`, the LLVM IR is very similar in both cases. The wildcard machine code still contains the unreachable check, but that's a different issue that seems more suited to the LLVM side.)

(Note that if `Locked` becomes `Locked(String)` so that it needs `Drop`, the machine code will contain the unreachable check no matter how you write the match arms when using `panic_unwind`. That might be better characterized as an LLVM improvement, but I'm mentioning it because an LLVM opt improvement fixing that might also fix the case above without any MIR opt changes. I haven't looked into it though.)

<details>
<summary>x86 asm with variants spelled out</summary>

```gas
take:
    movabsq $-9223372036854775808, %rcx
    movq (%rsi), %rax
    movq %rax, %r8
    xorq %rcx, %r8
    cmpq $2, %r8
    movl $2, %edx
    cmovbq %r8, %rdx
    testq %rdx, %rdx
    je .LBB0_1
    cmpq $2, %rdx
    jne .LBB0_5
    movups 8(%rsi), %xmm0
    movups %xmm0, 8(%rdi)
    movq %rcx, (%rsi)
    movq %rax, (%rdi)
    movq %rdi, %rax
    retq
.LBB0_1:
    movq %rcx, %rax
    movq %rax, (%rdi)
    movq %rdi, %rax
    retq
.LBB0_5:
    pushq %rax
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.0(%rip), %rdi
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.2(%rip), %rdx
    movl $38, %esi
    callq *_ZN3std9panicking11begin_panic17h60e0c77c4eaa68d9E@GOTPCREL(%rip)

.Lanon.600d6af0f320a021dc494cfa2daca569.0:
    .ascii "you tried to break into the container!"

.Lanon.600d6af0f320a021dc494cfa2daca569.1:
    .ascii "main.rs"

.Lanon.600d6af0f320a021dc494cfa2daca569.2:
    .quad .Lanon.600d6af0f320a021dc494cfa2daca569.1
    .asciz "\007\000\000\000\000\000\000\000\"\000\000\000\036\000\000"
```

</details>

<details>
<summary>x86 asm with wildcard</summary>

```gas
take:
    pushq %rax
    movabsq $-9223372036854775808, %rcx
    movq (%rsi), %rax
    movq %rax, %r8
    xorq %rcx, %r8
    cmpq $2, %r8
    movl $2, %edx
    cmovbq %r8, %rdx
    testq %rdx, %rdx
    je .LBB0_4
    cmpq $2, %rdx
    jne .LBB0_7
    movq 8(%rsi), %rdx
    movq 16(%rsi), %r8
    movq %rcx, (%rsi)
    incq %rcx
    cmpq %rcx, %rax
    jle .LBB0_6
    movq %rax, (%rdi)
    movq %rdx, 8(%rdi)
    movq %r8, 16(%rdi)
    movq %rdi, %rax
    popq %rcx
    retq
.LBB0_4:
    movq %rcx, (%rdi)
    movq %rdi, %rax
    popq %rcx
    retq
.LBB0_7:
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.0(%rip), %rdi
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.2(%rip), %rdx
    movl $38, %esi
    callq *_ZN3std9panicking11begin_panic17h60e0c77c4eaa68d9E@GOTPCREL(%rip)
.LBB0_6:
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.3(%rip), %rdi
    leaq .Lanon.600d6af0f320a021dc494cfa2daca569.4(%rip), %rdx
    movl $40, %esi
    callq *_ZN4core9panicking5panic17h48a7e1f3665210c6E@GOTPCREL(%rip)

.Lanon.600d6af0f320a021dc494cfa2daca569.0:
    .ascii "you tried to break into the container!"

.Lanon.600d6af0f320a021dc494cfa2daca569.1:
    .ascii "main.rs"

.Lanon.600d6af0f320a021dc494cfa2daca569.2:
    .quad .Lanon.600d6af0f320a021dc494cfa2daca569.1
    .asciz "\007\000\000\000\000\000\000\000\"\000\000\000\036\000\000"

.Lanon.600d6af0f320a021dc494cfa2daca569.3:
    .ascii "internal error: entered unreachable code"

.Lanon.600d6af0f320a021dc494cfa2daca569.4:
    .quad .Lanon.600d6af0f320a021dc494cfa2daca569.1
    .asciz "\007\000\000\000\000\000\000\000&\000\000\000\022\000\000"
```

</details>

### PR DESCRIPTION
**Pull request by ashivaram23**
This allows `ElaborateDrops` to remove drops when a `match` wildcard arm covers multiple no-Drop enum variants. It modifies dataflow analysis to update the `MaybeUninitializedPlaces` and `MaybeInitializedPlaces` data for a block reached through an `otherwise` edge.

Fixes rust-lang/rust#142705.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? compiler

**Comment by workingjubilee** [comment]
hm.
@bors2 try @rust-timer queue

**Comment by ashivaram23** [comment]
Hmm that's unfortunate. It might help to avoid paying the cost of the extra clone and checks when it won't make a difference, like in the trivial `otherwise` targets when there's no wildcard. Maybe the `otherwise` could be handled in a separate pass after collecting variants to kill/add in a `SmallVec`, in case that helps somehow.

What's more concerning is runtime benchmarks being worse. There are only two, and I don't know how noisy they are, but 8% wall time increase for css-parse-fb is pretty bad. There are also some compile time benchmarks whose graphs show significant increases in wall time spent in LLVM. Does this just not play well with later optimizations?

**Comment by ashivaram23** [comment]
The last commit makes it so that there's an option in the `MaybeUninitializedPlaces` and `MaybeInitializedPlaces` builders for whether or not to update the `otherwise` block's lattice element, and it's set to only do so for `MaybeInitializedPlaces` in `RemoveUninitDrops` and `ElaborateDrops`. That should be enough to clean up some drops while hopefully being faster and not messing with other passes in ways that cause runtime slowdowns.

**Comment by workingjubilee** [comment]
the runtime benchmarks are unfortunately very noisy

File: compiler/rustc_mir_dataflow/src/drop_flag_effects.rs [hunk 1]
```diff
@@ -155,16 +155,15 @@ where
...
-pub(crate) fn on_all_inactive_variants<'tcx>(
+/// Handles each variant that corresponds to one of the child move paths of `enum_place`. If the
+/// variant is `active_variant`, `handle_active_variant` will be called (if provided). Otherwise,
+/// `handle_inactive_variant` will be called.
+pub(crate) fn on_all_variants<'tcx>(
     move_data: &MoveData<'tcx>,
     enum_place: mir::Place<'tcx>,
     active_variant: VariantIdx,
     mut handle_inactive_variant: impl FnMut(MovePathIndex),
+    mut handle_active_variant: Option<impl FnMut(MovePathIndex)>,
```
Comment (fee1-dead) [inline compiler/rustc_mir_dataflow/src/drop_flag_effects.rs]: I wonder if it will be better, perf-wise to make this not take an option but just use a no-op for callers that do not want to handle it.

**Comment by fee1-dead** [comment]
this part of MIR is a little above my level of confidence for review, so

r? compiler

**Comment by lcnr** [comment]
r? wg-mir-opt

File: compiler/rustc_mir_dataflow/src/drop_flag_effects.rs (hunk 1 above)
Comment (ashivaram23) [reply compiler/rustc_mir_dataflow/src/drop_flag_effects.rs]: That's definitely possible, since I think in that case `on_all_children_bits` could be monomorphized into an empty function. I made the change and it does reduce stage2 `librustc_driver.so` size a bit.

**Comment by dianqk** [comment]
I need some time to understand the relevant code that I'm not familiar. If you want, feell free to reroll.

**Comment by ashivaram23** [comment]
@dianqk That's fine, thanks! Is it possible to do another perf run in the meantime, since my recent changes could have made it better/worse?

**Comment by lqd** [comment]
@bors2 try @rust-timer queue

cc dataflow expert @cjgillot

**Comment by dianqk** [comment]
Your purpose makes sense to me. Could you add a test case?
But in my mind, the change would like the following one. What do you think?

```diff
--- a/compiler/rustc_mir_dataflow/src/drop_flag_effects.rs
+++ b/compiler/rustc_mir_dataflow/src/drop_flag_effects.rs
@@ -155,6 +155,22 @@ fn for_location_inits<'tcx, F>(move_data: &MoveData<'tcx>, loc: Location, mut ca
     }
 }
 
+pub(crate) enum ActiveVariant {
+    Active(VariantIdx),
+    Inactives(Vec<VariantIdx>),
+}
+
+impl ActiveVariant {
+    fn active(&self, variant_idx: VariantIdx) -> bool {
+        match self {
+            ActiveVariant::Active(active_variant) => variant_idx == *active_variant,
+            ActiveVariant::Inactives(inactive_variants) => {
+                !inactive_variants.contains(&variant_idx)
+            }
+        }
+    }
+}
+
 /// Calls `handle_inactive_variant` for each descendant move path of `enum_place` that contains a
 /// `Downcast` to a variant besides the `active_variant`.
 ///
@@ -163,7 +179,7 @@ fn for_location_inits<'tcx, F>(move_data: &MoveData<'tcx>, loc: Location, mut ca
 pub(crate) fn on_all_inactive_variants<'tcx>(
     move_data: &MoveData<'tcx>,
     enum_place: mir::Place<'tcx>,
-    active_variant: VariantIdx,
+    active_variant: ActiveVariant,
     mut handle_inactive_variant: impl FnMut(MovePathIndex),
 ) {
     let LookupResult::Exact(enum_mpi) = move_data.rev_lookup.find(enum_place.as_ref()) else {
@@ -182,7 +198,7 @@ pub(crate) fn on_all_inactive_variants<'tcx>(
             unreachable!();
         };
 
-        if variant_idx != active_variant {
+        if !active_variant.active(variant_idx) {
             on_all_children_bits(move_data, variant_mpi, |mpi| handle_inactive_variant(mpi));
         }
     }
diff --git a/compiler/rustc_mir_dataflow/src/framework/direction.rs b/compiler/rustc_mir_dataflow/src/framework/direction.rs
index e955e38ad10..73fae9a89c8 100644
--- a/compiler/rustc_mir_dataflow/src/framework/direction.rs
+++ b/compiler/rustc_mir_dataflow/src/framework/direction.rs
@@ -112,12 +112,13 @@ fn apply_effects_in_block<'mir, 'tcx, A>(
                     propagate(pred, &tmp);
                 }
 
-                mir::TerminatorKind::SwitchInt { targets: _, ref discr } => {
+                mir::TerminatorKind::SwitchInt { ref targets, ref discr } => {
                     if let Some(mut data) = analysis.get_switch_int_data(block, discr) {
                         let mut tmp = analysis.bottom_value(body);
                         for &value in &body.basic_blocks.switch_sources()[&(block, pred)] {
                             tmp.clone_from(exit_state);
-                            analysis.apply_switch_int_edge_effect(&mut data, &mut tmp, value);
+                            analysis
+                                .apply_switch_int_edge_effect(targets, &mut data, &mut tmp, value);
                             propagate(pred, &tmp);
                         }
                     } else {
@@ -290,7 +291,7 @@ fn apply_effects_in_block<'mir, 'tcx, A>(
                     for (value, target) in targets.iter() {
                         tmp.clone_from(exit_state);
                         let value = SwitchTargetValue::Normal(value);
-                        analysis.apply_switch_int_edge_effect(&mut data, &mut tmp, value);
+                        analysis.apply_switch_int_edge_effect(targets, &mut data, &mut tmp, value);
                         propagate(target, &tmp);
                     }
 
@@ -299,6 +300,7 @@ fn apply_effects_in_block<'mir, 'tcx, A>(
                     // a clone of the dataflow state.
                     let otherwise = targets.otherwise();
                     analysis.apply_switch_int_edge_effect(
+                        targets,
                         &mut data,
                         exit_state,
                         SwitchTargetValue::Otherwise,
diff --git a/compiler/rustc_mir_dataflow/src/framework/mod.rs b/compiler/rustc_mir_dataflow/src/framework/mod.rs
index 9cadec100b5..d2034ce12e7 100644
--- a/compiler/rustc_mir_dataflow/src/framework/mod.rs
+++ b/compiler/rustc_mir_dataflow/src/framework/mod.rs
@@ -39,7 +39,8 @@
 use rustc_index::{Idx, IndexVec};
 use rustc_middle::bug;
 use rustc_middle::mir::{
-    self, BasicBlock, CallReturnPlaces, Location, SwitchTargetValue, TerminatorEdges, traversal,
+    self, BasicBlock, CallReturnPlaces, Location, SwitchTargetValue, SwitchTargets,
+    TerminatorEdges, traversal,
 };
 use rustc_middle::ty::TyCtxt;
 use tracing::error;
@@ -221,6 +222,7 @@ fn get_switch_int_data(
     /// See comments on `get_switch_int_data`.
     fn apply_switch_int_edge_effect(
         &mut self,
+        _targets: &SwitchTargets,
         _data: &mut Self::SwitchIntData,
         _state: &mut Self::Domain,
         _value: SwitchTargetValue,
diff --git a/compiler/rustc_mir_dataflow/src/impls/initialized.rs b/compiler/rustc_mir_dataflow/src/impls/initialized.rs
index 18165b0b9bd..5b8bda65e10 100644
--- a/compiler/rustc_mir_dataflow/src/impls/initialized.rs
+++ b/compiler/rustc_mir_dataflow/src/impls/initialized.rs
@@ -5,7 +5,7 @@
 use rustc_index::bit_set::{DenseBitSet, MixedBitSet};
 use rustc_middle::bug;
 use rustc_middle::mir::{
-    self, Body, CallReturnPlaces, Location, SwitchTargetValue, TerminatorEdges,
+    self, Body, CallReturnPlaces, Location, SwitchTargetValue, SwitchTargets, TerminatorEdges,
 };
 use rustc_middle::ty::util::Discr;
 use rustc_middle::ty::{self, TyCtxt};
@@ -39,6 +39,16 @@ fn next_discr(&mut self, value: u128) -> VariantIdx {
             }
         }
     }
+
+    fn variants(&mut self, targets: &SwitchTargets) -> Vec<VariantIdx> {
+        self.index = 0;
+        let mut variants = Vec::new();
+        for (value, _) in targets.iter() {
+            variants.push(self.next_discr(value));
+        }
+        self.index = 0;
+        variants
+    }
 }
 
 impl<'tcx> MaybePlacesSwitchIntData<'tcx> {
@@ -428,20 +438,28 @@ fn get_switch_int_data(
 
     fn apply_switch_int_edge_effect(
         &mut self,
+        targets: &SwitchTargets,
         data: &mut Self::SwitchIntData,
         state: &mut Self::Domain,
         value: SwitchTargetValue,
     ) {
-        if let SwitchTargetValue::Normal(value) = value {
-            // Kill all move paths that correspond to variants we know to be inactive along this
-            // particular outgoing edge of a `SwitchInt`.
-            drop_flag_effects::on_all_inactive_variants(
-                self.move_data,
-                data.enum_place,
-                data.next_discr(value),
-                |mpi| state.kill(mpi),
-            );
-        }
+        // Kill all move paths that correspond to variants we know to be inactive along this
+        // particular outgoing edge of a `SwitchInt`.
+        let active_variant = match value {
+            SwitchTargetValue::Normal(value) => {
+                drop_flag_effects::ActiveVariant::Active(data.next_discr(value))
+            }
+            SwitchTargetValue::Otherwise => {
+                // TODO: Is it better to collect within the loop of `apply_effects_in_block`?
+                drop_flag_effects::ActiveVariant::Inactives(data.variants(targets))
+            }
+        };
+        drop_flag_effects::on_all_inactive_variants(
+            self.move_data,
+            data.enum_place,
+            active_variant,
+            |mpi| state.kill(mpi),
+        );
     }
 }
 
@@ -541,20 +559,27 @@ fn get_switch_int_data(
 
     fn apply_switch_int_edge_effect(
         &mut self,
+        targets: &SwitchTargets,
         data: &mut Self::SwitchIntData,
         state: &mut Self::Domain,
         value: SwitchTargetValue,
     ) {
-        if let SwitchTargetValue::Normal(value) = value {
-            // Mark all move paths that correspond to variants other than this one as maybe
-            // uninitialized (in reality, they are *definitely* uninitialized).
-            drop_flag_effects::on_all_inactive_variants(
-                self.move_data,
-                data.enum_place,
-                data.next_discr(value),
-                |mpi| state.gen_(mpi),
-            );
-        }
+        // Mark all move paths that correspond to variants other than this one as maybe
+        // uninitialized (in reality, they are *definitely* uninitialized).
+        let active_variant = match value {
+            SwitchTargetValue::Normal(value) => {
+                drop_flag_effects::ActiveVariant::Active(data.next_discr(value))
+            }
+            SwitchTargetValue::Otherwise => {
+                drop_flag_effects::ActiveVariant::Inactives(data.variants(targets))
+            }
+        };
+        drop_flag_effects::on_all_inactive_variants(
+            self.move_data,
+            data.enum_place,
+            active_variant,
+            |mpi| state.gen_(mpi),
+        );
     }
 }
```

@rustbot author

**Comment by ashivaram23** [comment]
Sorry it took me a while to get to this! I added a test in `otherwise_drops.rs`.

As for your suggestion, I think it makes sense. It's more readable and while it does involve an additional allocation and another pass through the variants and move paths, it also saves a clone of the dataflow state, and the non-otherwise targets do the same quadratic loops anyway (could only be avoided if there was a guarantee that move paths are in the same order as discriminants).

I can implement the `ActiveVariants` enum suggestion as is, but I was thinking of combining it with a few other changes that may or may not be a good idea, and would like to hear your thoughts.

My idea was that it could be nicer to collect the `VariantIdx`s of each switch target while creating `MaybePlacesSwitchIntData` so they could be passed directly to `on_all_inactive_variants` without a new allocation, and the non-otherwise targets won't have to skip over variants with `next_discr` every time either. Nobody else uses `MaybePlacesSwitchIntData` and its main purpose seems to be mapping switch target `u128` values to `VariantIdx`, so we can avoid the extra work and indirection with something like this:

```rust
pub struct MaybePlacesSwitchIntData<'tcx> {
    enum_place: mir::Place<'tcx>,
    
    // only the targets in the SwitchInt, not all discriminants
    targets: Vec<(VariantIdx, mir::BasicBlock)>,

    // discriminants: Vec<(VariantIdx, Discr<'tcx>)>,
    // index: usize,
}
```

Then `SwitchTargetValue` could store `VariantIdx` instead of `u128`, so the whole `next_discr` process and index state tracking would be unnecessary, and the `otherwise` pass could use this filtered `targets` list that contains the `VariantIdx`s without needing to allocate a new `Vec` for it.

This would probably require removing the call to `BasicBlocks::switch_sources` in backward `apply_effects_in_block` because it's tough to make `switch_sources` get `VariantIdx`s. Setting aside how all of the backward code is currently unused, I think that could make it more efficient. Since `get_switch_int_data` is being called on each predecessor* anyway, it's not necessary to loop through targets returned by `switch_sources` (which goes through every block in the CFG on the first call, though that gets cached). The only benefit of doing so at the moment is avoiding a check to filter for the correct successor, but the point of this idea is for `get_switch_int_data` to filter everything upfront.

---

\* To me it seems like it should be called on the block's predecessor, but it's currently being passed the block itself. Again it's unused so it doesn't matter, but I wonder if this was actually a typo. @nnethercote because [this line](https://github.com/rust-lang/rust/blob/0d11be5aabe0cd49609fff5fce57c4691a22fe55/compiler/rustc_mir_dataflow/src/framework/direction.rs#L116) is from #133328.

File: tests/mir-opt/otherwise_drops.rs [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// skip-filecheck
+//@ test-mir-pass: ElaborateDrops
+
+// Ensures there are no drops for the wildcard match arm.
+
+// EMIT_MIR otherwise_drops.result_ok.ElaborateDrops.after.mir
```
Comment (dianqk) [inline tests/mir-opt/otherwise_drops.rs]: Why not `EMIT_MIR otherwise_drops.result_ok.ElaborateDrops.diff`

File: tests/mir-opt/otherwise_drops.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// skip-filecheck
```
Comment (dianqk) [inline tests/mir-opt/otherwise_drops.rs]: Please add what you want to check, such as `// CHECK-NOT: drop(`.

**Review by dianqk — COMMENTED** [review]
Maybe, but I think it should be an independent PR.

**Comment by dianqk** [comment]
BTW, the PR title could probably be something like: "Applying effects to otherwise in dataflow"

File: tests/mir-opt/otherwise_drops.rs (hunk 2 above)
Comment (ashivaram23) [reply tests/mir-opt/otherwise_drops.rs]: When I run `./x test --bless` with diff output, the first runs generate a slightly different "before" than the later runs, which means running `./x test` immediately afterwards fails. There's one line that starts out as `unwind: continue` in the first platform tests and then becomes `unwind: bb9` later.

**Comment by ashivaram23** [comment]
In the last commit I fixed the test file and incorporated the suggestions. I used a `SmallVec` since that's what `SwitchTargets` and other structs do, and I switched it to `InactiveVariants` for the double negative.

**Comment by tmiasko** [comment]
> To me it seems like it should be called on the block's predecessor, but it's currently being passed the block itself.

Yes, it should have been called on the predecessor which contains the switch. 

I haven't followed all the discussion, but if removing unused switch int handling in the backward direction makes anything easier that seems perfectly fine.

File: tests/mir-opt/otherwise_drops.rs (hunk 2 above)
Comment (dianqk) [reply tests/mir-opt/otherwise_drops.rs]: Perhaps you want to add `//@ compile-flags: -Cpanic=abort` or `// EMIT_MIR_FOR_EACH_PANIC_STRATEGY`. I prefer the first one here.

File: tests/mir-opt/otherwise_drops.rs [hunk 4]
```diff
@@ -0,0 +1,18 @@
+//@ test-mir-pass: ElaborateDrops
+
+// Ensures there are no drops for the wildcard match arm.
+
+// EMIT_MIR otherwise_drops.result_ok.ElaborateDrops.after.mir
+fn result_ok(result: Result<String, ()>) -> Option<String> {
+    // CHECK-LABEL: fn result_ok(
+    // CHECK-NOT: drop
+    // CHECK: return
```
Comment (dianqk) [inline tests/mir-opt/otherwise_drops.rs]:
```suggestion
```
The return statement isn't the final line of this function.

File: tests/mir-opt/otherwise_drops.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+    match result {
+        Ok(s) => Some(s),
+        _ => None,
+    }
+}
+
+fn main() {
+    result_ok(Err(()));
+}
```
Comment (dianqk) [inline tests/mir-opt/otherwise_drops.rs]:
```suggestion
```
Removing this function makes file check easier.

**Review by dianqk — APPROVED** [review]
Please squash your commits into one and update the PR description, remembering to use https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.

**Comment by dianqk** [comment]
@bors2 try @rust-timer queue

**Comment by ashivaram23** [comment]
Squashed and force pushed, the only changes since the last commit are addressing the test file review comments.

Regarding the perf run results, there are 8 cases this could affect:

1. `MaybeInitializedPlaces` in MIR type check liveness analysis
2. `MaybeUninitializedPlaces` in MIR borrow check
3. `MaybeInitializedPlaces` in `SanityCheck`
4. `MaybeUninitializedPlaces` in `SanityCheck`
5. `MaybeInitializedPlaces` in `lint_tail_expr_drop_order`
6. `MaybeInitializedPlaces` in `RemoveUninitDrops`
7. `MaybeInitializedPlaces` in `ElaborateDrops`
8. `MaybeUninitializedPlaces` in `ElaborateDrops`

The first perf run handled `otherwise` edges everywhere, the second did it only for 6 and 7, and the third did it for 6-8.

The first has the strongest results, with a lot of improvements and a few regressions. (Also a runtime test regression, which seems to follow a step function where it fluctuates between either exactly 0 or exactly 1.9% relative to the baseline over the past 30 days and went back to 1.9% here, not sure what that means)

The second still shows an overall improvement in compile times but applies to much fewer tests. It also has a different runtime regression with the same binary/step pattern.

The third has more regressions and fewer improvements, and an overall regression in compile times for all benchmarks (mostly due to the secondary benchmarks especially `tt-muncher`, it's a small overall improvement for the primary ones only). But there are no runtime test regressions and bootstrap times are four seconds faster.

Should I just enable the change for all 8 cases again? Or make it as limited as possible (number 7 alone is enough to fix the wildcard problem), or try other combinations?

**Comment by dianqk** [comment]
These can be subsequent PRs. Thanks!
@bors r+

**Comment by Kobzol** [comment]
More improvements than regressions, and improvements are mostly in primary benchmarks, while regressions are in secondary benchmarks. [This comment](https://github.com/rust-lang/rust/pull/142707#issuecomment-3050525801) mentions a plan for possible future improvements.

@rustbot label: +perf-regression-triaged
