### PR TITLE
MinGW: enable dllexport/dllimport

### LINKED ISSUE #72319: Linking static lib to dylib can cause symbols to be missing from import lib
I tried this code:
```toml
[package]
name = "test5"
version = "0.1.0"
authors = ["Mateusz Mikuła <mati865@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
```
```rust
// LLVM unwind library from MSYS2 repo
#[link(name = "unwind", kind = "static")]
extern "C" {}

#[no_mangle]
pub fn foo() {
    println!("Hello, world!");
}

```

I expected to see this happen:
```
$ cargo +stage2 b && nm target/debug/libtest5.dll.a | grep foo || echo "not found"
   Compiling test5 v0.1.0 (D:\msys64\tmp\test5)
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
0000000000000000 I __imp_foo
0000000000000000 T foo
```
stage2 is https://github.com/rust-lang/rust/pull/72049

Instead, this happened:
```
$ cargo b && nm target/debug/libtest5.dll.a | grep foo || echo "not found"
   Compiling test5 v0.1.0 (D:\msys64\tmp\test5)
    Finished dev [unoptimized + debuginfo] target(s) in 0.57s
not found
```

### Meta

`rustc --version --verbose`:
```
$ rustc -vV
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
binary: rustc
commit-hash: a74d1862d4d87a56244958416fd05976c58ca1a8
commit-date: 2020-05-14
host: x86_64-pc-windows-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

</p>
</details>

<details>
<summary>All symbols from import libraries</summary>

```
$ cargo b && nm target/debug/libtest5.dll.a
   Compiling test5 v0.1.0 (D:\msys64\tmp\test5)
    Finished dev [unoptimized + debuginfo] target(s) in 0.60s

d000034.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$7
0000000000000000 I test5_dll_iname

d000000.o:
0000000000000000 i .idata$2
0000000000000000 b .idata$4
0000000000000000 b .idata$5
0000000000000000 I _head_test5_dll
                 U test5_dll_iname

d000033.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_step
                 U _head_test5_dll
0000000000000000 T unw_step

d000032.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_set_reg
                 U _head_test5_dll
0000000000000000 T unw_set_reg

d000031.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_set_fpreg
                 U _head_test5_dll
0000000000000000 T unw_set_fpreg

d000030.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_resume
                 U _head_test5_dll
0000000000000000 T unw_resume

d000029.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_regname
                 U _head_test5_dll
0000000000000000 T unw_regname

d000028.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_local_addr_space
0000000000000000 I __nm_unw_local_addr_space
                 U _head_test5_dll

d000027.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_is_signal_frame
                 U _head_test5_dll
0000000000000000 T unw_is_signal_frame

d000026.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_is_fpreg
                 U _head_test5_dll
0000000000000000 T unw_is_fpreg

d000025.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_init_local
                 U _head_test5_dll
0000000000000000 T unw_init_local

d000024.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_getcontext
                 U _head_test5_dll
0000000000000000 T unw_getcontext

d000023.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_reg
                 U _head_test5_dll
0000000000000000 T unw_get_reg

d000022.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_proc_name
                 U _head_test5_dll
0000000000000000 T unw_get_proc_name

d000021.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_proc_info
                 U _head_test5_dll
0000000000000000 T unw_get_proc_info

d000020.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_fpreg
                 U _head_test5_dll
0000000000000000 T unw_get_fpreg

d000019.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_SetIP
                 U _head_test5_dll
0000000000000000 T _Unwind_SetIP

d000018.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_SetGR
                 U _head_test5_dll
0000000000000000 T _Unwind_SetGR

d000017.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Resume_or_Rethrow
                 U _head_test5_dll
0000000000000000 T _Unwind_Resume_or_Rethrow

d000016.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Resume
                 U _head_test5_dll
0000000000000000 T _Unwind_Resume

d000015.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_RaiseException
                 U _head_test5_dll
0000000000000000 T _Unwind_RaiseException

d000014.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetTextRelBase
                 U _head_test5_dll
0000000000000000 T _Unwind_GetTextRelBase

d000013.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetRegionStart
                 U _head_test5_dll
0000000000000000 T _Unwind_GetRegionStart

d000012.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetLanguageSpecificData
                 U _head_test5_dll
0000000000000000 T _Unwind_GetLanguageSpecificData

d000011.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetIPInfo
                 U _head_test5_dll
0000000000000000 T _Unwind_GetIPInfo

d000010.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetIP
                 U _head_test5_dll
0000000000000000 T _Unwind_GetIP

d000009.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetGR
                 U _head_test5_dll
0000000000000000 T _Unwind_GetGR

d000008.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetDataRelBase
                 U _head_test5_dll
0000000000000000 T _Unwind_GetDataRelBase

d000007.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetCFA
                 U _head_test5_dll
0000000000000000 T _Unwind_GetCFA

d000006.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_ForcedUnwind
                 U _head_test5_dll
0000000000000000 T _Unwind_ForcedUnwind

d000005.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Find_FDE
                 U _head_test5_dll
0000000000000000 T _Unwind_Find_FDE

d000004.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_FindEnclosingFunction
                 U _head_test5_dll
0000000000000000 T _Unwind_FindEnclosingFunction

d000003.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_DeleteException
                 U _head_test5_dll
0000000000000000 T _Unwind_DeleteException

d000002.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Backtrace
                 U _head_test5_dll
0000000000000000 T _Unwind_Backtrace

d000001.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__GCC_specific_handler
0000000000000000 T _GCC_specific_handler
                 U _head_test5_dll
```
```
$ cargo +stage2 b && nm target/debug/libtest5.dll.a
   Compiling test5 v0.1.0 (D:\msys64\tmp\test5)
    Finished dev [unoptimized + debuginfo] target(s) in 0.84s

d000036.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$7
0000000000000000 I test5_dll_iname

d000000.o:
0000000000000000 i .idata$2
0000000000000000 b .idata$4
0000000000000000 b .idata$5
0000000000000000 I _head_test5_dll
                 U test5_dll_iname

d000035.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_step
                 U _head_test5_dll
0000000000000000 T unw_step

d000034.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_set_reg
                 U _head_test5_dll
0000000000000000 T unw_set_reg

d000033.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_set_fpreg
                 U _head_test5_dll
0000000000000000 T unw_set_fpreg

d000032.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_resume
                 U _head_test5_dll
0000000000000000 T unw_resume

d000031.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_regname
                 U _head_test5_dll
0000000000000000 T unw_regname

d000030.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_local_addr_space
0000000000000000 I __nm_unw_local_addr_space
                 U _head_test5_dll

d000029.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_is_signal_frame
                 U _head_test5_dll
0000000000000000 T unw_is_signal_frame

d000028.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_is_fpreg
                 U _head_test5_dll
0000000000000000 T unw_is_fpreg

d000027.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_init_local
                 U _head_test5_dll
0000000000000000 T unw_init_local

d000026.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_getcontext
                 U _head_test5_dll
0000000000000000 T unw_getcontext

d000025.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_reg
                 U _head_test5_dll
0000000000000000 T unw_get_reg

d000024.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_proc_name
                 U _head_test5_dll
0000000000000000 T unw_get_proc_name

d000023.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_proc_info
                 U _head_test5_dll
0000000000000000 T unw_get_proc_info

d000022.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_unw_get_fpreg
                 U _head_test5_dll
0000000000000000 T unw_get_fpreg

d000021.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_rust_eh_personality
                 U _head_test5_dll
0000000000000000 T rust_eh_personality

d000020.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_foo
                 U _head_test5_dll
0000000000000000 T foo

d000019.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_SetIP
                 U _head_test5_dll
0000000000000000 T _Unwind_SetIP

d000018.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_SetGR
                 U _head_test5_dll
0000000000000000 T _Unwind_SetGR

d000017.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Resume_or_Rethrow
                 U _head_test5_dll
0000000000000000 T _Unwind_Resume_or_Rethrow

d000016.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Resume
                 U _head_test5_dll
0000000000000000 T _Unwind_Resume

d000015.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_RaiseException
                 U _head_test5_dll
0000000000000000 T _Unwind_RaiseException

d000014.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetTextRelBase
                 U _head_test5_dll
0000000000000000 T _Unwind_GetTextRelBase

d000013.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetRegionStart
                 U _head_test5_dll
0000000000000000 T _Unwind_GetRegionStart

d000012.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetLanguageSpecificData
                 U _head_test5_dll
0000000000000000 T _Unwind_GetLanguageSpecificData

d000011.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetIPInfo
                 U _head_test5_dll
0000000000000000 T _Unwind_GetIPInfo

d000010.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetIP
                 U _head_test5_dll
0000000000000000 T _Unwind_GetIP

d000009.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetGR
                 U _head_test5_dll
0000000000000000 T _Unwind_GetGR

d000008.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetDataRelBase
                 U _head_test5_dll
0000000000000000 T _Unwind_GetDataRelBase

d000007.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_GetCFA
                 U _head_test5_dll
0000000000000000 T _Unwind_GetCFA

d000006.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_ForcedUnwind
                 U _head_test5_dll
0000000000000000 T _Unwind_ForcedUnwind

d000005.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Find_FDE
                 U _head_test5_dll
0000000000000000 T _Unwind_Find_FDE

d000004.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_FindEnclosingFunction
                 U _head_test5_dll
0000000000000000 T _Unwind_FindEnclosingFunction

d000003.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_DeleteException
                 U _head_test5_dll
0000000000000000 T _Unwind_DeleteException

d000002.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__Unwind_Backtrace
                 U _head_test5_dll
0000000000000000 T _Unwind_Backtrace

d000001.o:
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp__GCC_specific_handler
0000000000000000 T _GCC_specific_handler
                 U _head_test5_dll
```

</details>

### PR DESCRIPTION
**Pull request by mati865**
Fixes (only when using LLD) https://github.com/rust-lang/rust/issues/50176
Fixes https://github.com/rust-lang/rust/issues/72319

This makes `windows-gnu` on pair with `windows-msvc` when it comes to symbol exporting.
For MinGW it means both good things like correctly working dllimport/dllexport, ability to link with LLD and bad things like https://github.com/rust-lang/rust/issues/27438.

Not sure but maybe this should land behind unstable compiler option (`-Z`) or environment variable?

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? @petrochenkov 

cc @retep998, do you know anything about the changes in `src/librustc_codegen_llvm/context.rs` by chance?
(I've seen the other parts of this PR in https://github.com/rust-lang/rust/pull/70852, but didn't investigate this one yet.)

**Comment by retep998** [comment]
@petrochenkov This table covers dllimport linking success in the MSVC case: https://github.com/rust-lang/rust/issues/27438#issuecomment-143251350

For MinGW, several more of those entries become success instead of error (because it tries really hard to support minimally ported C code from non-windows which never put any thought into dllimport/dllexport), however the case of plain static with dynamic library is still *always* an error because direct access to a static cannot be redirected with a thunk the way functions can.

We should absolutely emit the appropriate dllimport/dllexport attributes on all Windows targets including MinGW as the resulting codegen is still better when done correctly.

File: src/librustc_session/session.rs [hunk 1]
```diff
@@ -1281,7 +1281,7 @@ fn validate_commandline_args_with_session_available(sess: &Session) {
     // the `dllimport` attributes and `__imp_` symbols in that case.
     if sess.opts.cg.linker_plugin_lto.enabled()
         && sess.opts.cg.prefer_dynamic
-        && sess.target.target.options.is_like_msvc
+        && sess.target.target.options.is_like_windows
     {
         sess.err(
             "Linker plugin based LTO is not supported together with \
```
Comment (petrochenkov) [inline src/librustc_session/session.rs:1287]:
```suggestion
            "Linker plugin based LTO is not supported together with \
                  `-C prefer-dynamic` when targeting Windows-like targets",
```

File: src/librustc_codegen_llvm/context.rs [hunk 2]
```diff
@@ -247,8 +252,8 @@ impl<'ll, 'tcx> CodegenCx<'ll, 'tcx> {
         // this effect) by marking very little as `dllimport` and praying the
         // linker will take care of everything. Fixing this problem will likely
         // require adding a few attributes to Rust itself (feature gated at the
-        // start) and then strongly recommending static linkage on MSVC!
-        let use_dll_storage_attrs = tcx.sess.target.target.options.is_like_msvc;
+        // start) and then strongly recommending static linkage on Windows!
```
Comment (petrochenkov) [inline src/librustc_codegen_llvm/context.rs:255]: Large parts of the comment above are outdated.
E.g. we don't set dllexport LLVM attributes now and export everything with `/DEF`.
It would be great to remove or update the outdated parts.

**Comment by petrochenkov** [comment]
@mati865 
Could you add a test for https://github.com/rust-lang/rust/issues/72319?
Tests using `nm` are usually put into the `run-make` directory.

**Comment by mati865** [comment]
#72319 happens only when linking specific libs like llvm-libunwind. I have no idea what makes it so "special" but the test would probably require shipping that library...

**Comment by petrochenkov** [comment]
Ok, I think this is similar to https://github.com/rust-lang/rust/pull/70937 in the sense that it should be the right thing to do, it affects only windows-gnu, but there may be compatibility issues.

So, same comments from https://github.com/rust-lang/rust/pull/70937#issuecomment-612105164 apply, and we can choose the [same process](https://github.com/rust-lang/rust/pull/70937#issuecomment-611432748) of dealing with the change - land it and see whether it causes any complaints in practice.

File: src/librustc_session/session.rs (hunk 1 above)
Comment (petrochenkov) [reply src/librustc_session/session.rs:1287]: "Linker ..." -> "linker", diagnostics are conventionally lowercase.

**Comment by petrochenkov** [comment]
>#72319 happens only when linking specific libs like llvm-libunwind

Ok, shipping libunwind for a test is overkill.
(Although it would be great to figure out what happens exactly.)

File: src/librustc_codegen_llvm/context.rs (hunk 2 above)
Comment (mati865) [reply src/librustc_codegen_llvm/context.rs:255]: I don't know details about how rustc handles that and I'm not confident in rewriting it 🤷‍♂️

Comment (petrochenkov) [reply src/librustc_codegen_llvm/context.rs:255]: Ok.

**Comment by mati865** [comment]
@bors r-

Sorry but there is one missing change here. I'd have committed it already but had to fix ` undefined reference to __ms_vsnprintf` first and I'm waiting on all tests passed.

**Comment by mati865** [comment]
Explanation what happened:
Yesterday I locally rebased this branch and decided to run the tests again. That resulted in build failure, that I fixed by changing `is_like_msvc` to `is_like_windows` here: https://github.com/rust-lang/rust/pull/72049/files#diff-4a91d38f147ba278726bb7ec5deaf5eaL1814
Then [`run-make-fulldeps/no-duplicate-libs`](https://github.com/rust-lang/rust/tree/5a59527516a917738c2e5f5d9f5e9a3533a6a5bc/src/test/run-make-fulldeps/no-duplicate-libs) test started failing:
```
D:\msys64\mingw64\bin\ld: D:/Projekty/rust/build/x86_64-pc-windows-gnu/test/run-make-fulldeps/no-duplicate-libs/no-duplicate-libs\main.main.7rcbfp3g-cgu.0.rcgu.o:main.7rcbfp3g-cgu.:(.text+0x6): undefined reference to `__imp_bar'
```

I could swear the tests were previously passing, maybe some of them like `no-duplicate-libs` were ignored for whatever reason?

---

IMO the test is wrong since it uses `#[link(name = "foo")]` without `kind` (so it defaults to `dylib`) but foo and bar are static libs. It started failing with this PR because when Rust links to `dylib` kind it will use dllimport (`__imp_`).
Now there are 3 ways to make that test pass:
1. Ignore it on all Windows targets (it's already ignored on MSVC because of the same error).
2. Make it use `#[link(name = "foo", kind = "static-nobundle")]` which it should do IMO.
3. Let the linker decide whether to look for `__imp_bar` or `bar` symbol.

In https://github.com/rust-lang/rust/pull/72049/commits/53800919d88c7a41b99d9ce7e6b29743998149c9 I went with option 3 to retain as much compatibility as possible.

**Comment by mati865** [comment]
After rethinking I think we can land that with relying on linker automatic dllimport.

Some of the caveats of auto dllimport if symbol was "exported" without dllexport (this can happen with Rust and with external libraries):
- negligible overhead due to additional relocation
- Microsoft Store will reject the app
- depending on relocation type it might not work on ARM and ARM64 (there is no such Rust MinGW target yet)

They do not apply when auto importing symbol that has proper dllexport (at least with LLD, I'm not going to read BFD source code).

> Perhaps we need to start treating #[link(name = "foo")] and #[link(name = "foo", kind = "dylib")] differently for the purpose of emitting dllimport.

Wouldn't that be breaking change for MSVC?

I'm still inclined for MinGW to use the same dllexport machinery as MSVC.
When it comes to dllimport `uwp-windows-gnu` should behave just like MSVC (not use linker auto dllimport) while `pc-windows-gnu` could rely on auto dllimport for *functions only*.

**Comment by mati865** [comment]
I've played a bit more with https://github.com/rust-lang/rust/issues/50176 and it's getting clearer:
```
// Nightly with LD, not exported
$ cargo build --target i686-pc-windows-gnu; llvm-nm target/i686-pc-windows-gnu/debug/cdylib.dll | rg SomeFunction && echo implib: && llvm-nm target/i686-pc-windows-gnu/debug/libcdylib.dll.a | rg SomeFunction
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
69a814b0 T _SomeFunction@0
implib:

// Nightly with LLD, doesn't support linker script
$ RUSTFLAGS='-C link-arg=-fuse-ld=lld' cargo build --target i686-pc-windows-gnu; llvm-nm target/i686-pc-windows-gnu/debug/cdylib.dll | rg SomeFunction && echo implib: && llvm-nm target/i686-pc-windows-gnu/debug/libcdylib.dll.a | rg SomeFunction
[..]
  = note: lld: error: unknown argument: --version-script=C:\Users\mateusz\AppData\Local\Temp\rustc7TPSJT\list
[..]

// This PR with LD, almost good but it should have exported _SomeFunction@0 not _SomeFunction
$ cargo +stage2 build --target i686-pc-windows-gnu; llvm-nm target/i686-pc-windows-gnu/debug/cdylib.dll | rg SomeFunction && echo implib: && llvm-nm target/i686-pc-windows-gnu/debug/libcdylib.dll.a | rg SomeFunction
   Compiling cdylib v0.1.0 (D:\msys64\tmp\cdylib)
    Finished dev [unoptimized + debuginfo] target(s) in 0.83s
69a81460 T _SomeFunction
69a81460 T _SomeFunction@0
implib:
00000000 T _SomeFunction
00000000 I __imp__SomeFunction

// This PR with LLD, perfect, the test would pass (if there was any)
$ RUSTFLAGS='-C link-arg=-fuse-ld=lld' cargo +stage2 build --target i686-pc-windows-gnu; llvm-nm target/i686-pc-windows-gnu/debug/cdylib.dll | rg SomeFunction && echo implib: && llvm-nm target/i686-pc-windows-gnu/debug/libcdylib.dll.a | rg SomeFunction
   Compiling cdylib v0.1.0 (D:\msys64\tmp\cdylib)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
10001460 T _SomeFunction@0
implib:
00000000 T _SomeFunction@0
00000000 T __imp__SomeFunction@0
```
It's only a guess but we probably would have to write `__stdcall` symbols decorated with  `@<size of arguments>` in `src/librustc_codegen_ssa/back/linker.rs` to fix #50176 with LD.

File: src/librustc_codegen_ssa/back/linker.rs [hunk 3]
```diff
@@ -538,6 +539,21 @@ impl<'a> Linker for GccLinker<'a> {
...
+                // because LD doesn't like when it's empty
+                writeln!(f, "EXPORTS")?;
+                for symbol in self.info.exports[&crate_type].iter() {
+                    debug!("  _{}", symbol);
+                    writeln!(f, "  {}", symbol)?;
+                }
+            };
+            if let Err(e) = res {
+                self.sess.fatal(&format!("failed to write list.def file: {}", e));
+            }
```
Comment (petrochenkov) [inline src/librustc_codegen_ssa/back/linker.rs:556]: I forgot to ask - what exactly makes `.def` files work with `ld` in this PR?
The `--version-script` -> `list.def` change caused test failures in https://github.com/rust-lang/rust/pull/70852 despite the export list being the same.

Comment (mati865) [reply src/librustc_codegen_ssa/back/linker.rs:556]: > I forgot to ask - what exactly makes .def files work with ld in this PR?

TL;DR we now manually add dllexport/dllimport.

With version-scripts LD sort of scans the symbols to decide when to automatically add dllexport.
With `.def` it doesn't use automatic dllexport but dllexport can be manually enabled by what this PR does or writing `DATA` next to the symbol on the list.

Previously most of the tests worked before because of automatic dllimport, broken tests were using statics which don't work with automatic dllimport.

**Comment by petrochenkov** [comment]
@mati865 
Do I understand correctly that the export part can be landed independently?
In the worst case the generated `__imp_` will just end up unused?
It will resolve the issue with lld and version scripts though.

Could you move it to a separate PR then?
The export part looks straightforward (if the answer to the previous questions is yes/yes), but the import part is still something I'm not sure what to do with.

**Comment by mati865** [comment]
@petrochenkov `src/librustc_codegen_ssa/back/linker.rs` (exporting via `.def` file instead of version script) changes can be moved to separate PR.
I'll have to test but dllimport shouldn't be necessary if using version scripts.

Theoretically none of the dllexport/dllimport could be necessary for LD if symbols in `.def` file were correctly annotated with `DATA` (the same logic applies as for MSVC dllexport/dllimport code). Should I test that as well?

**Comment by mati865** [comment]
>>  Do I understand correctly that the export part can be landed independently?

> I'll have to test but dllimport shouldn't be necessary if using version scripts.

LD never ends to amaze me. With all changes except `src/librustc_codegen_ssa/back/write.rs` reverted:
```
  = note: D:\msys64\mingw64\bin\ld: C:\Users\mateusz\AppData\Local\Temp\rustcmjXtgU\librand_chacha-5071dc228d7f3863.rlib(rand_chacha-5071dc228d7f3863.rand_chacha.6608if8s-cgu.3.rcgu.o):rand_chacha.6608if:(.rdata$.refptr._ZN3std10std_detect6detect5cache5CACHE17h7630fb10d935399dE[.refptr._ZN3std10std_detect6detect5cache5CACHE17h7630fb10d935399dE]+0x0): undefined reference to `std::std_detect::detect::cache::CACHE'
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Dllexport was applied but with version script LD haven't actually propagated it into import library:
```
$ llvm-nm /d/Projekty/rust/build/x86_64-pc-windows-gnu/stage1-std/x86_64-pc-windows-gnu/release/libstd.dll.a | rg std_detect6detect5cache5CACHE17h7630fb10d935399dE

mateusz@DESKTOP-mati MINGW64 ~
$ llvm-nm /d/Projekty/rust/build/x86_64-pc-windows-gnu/stage1-std/x86_64-pc-windows-gnu/release/std.dll | rg std_detect6detect5cache5CACHE17h7630fb10d935399dE  62dff068 D _ZN3std10std_detect6detect5cache5CACHE17h7630fb10d935399dE
62dff078 D __imp__ZN3std10std_detect6detect5cache5CACHE17h7630fb10d935399dE
```

**Comment by petrochenkov** [comment]
Some more quick questions.

- What happens if we don't add `DATA` to `EXPORTS` for a static?
From the [docs](https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=vs-2019) it seems like we should always add these annotations, but we don't add them even for MSVC. Suspicious.

>TL;DR we now manually add dllexport
- What exactly do you mean by this?
I want to understand how to match terminology used in this thread with one used by the [doc](https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=vs-2019).
We do not use dllexport attributes at LLVM level, so we don't get any `/EXPORT` directives in object files.
All exporting is done with `.def` files at link time without involving dllexport in any way. (At least the doc describes `.def` files as an *alternative* to dllexport for exporting things.)

>Dllexport was applied but with version script LD haven't actually propagated it into import library
- Same question as above, what does "dllexport was applied" if we don't use dllexport.

**Comment by mati865** [comment]
> What happens if we don't add DATA to EXPORTS for a static?

AFAIK dllimport/dllexport are relocations. From MinGW linkers POV: 
If linker accessed static variable directly (just like for ELF formats) it'd get address of that relocation while it expects the real address of a variable. You can see how that broke tests with previous PR: https://dev.azure.com/rust-lang/rust/_build/results?buildId=26116&view=logs&j=90f6024d-9735-531d-4933-8983ca347d60&t=c9a02f8e-4843-5e08-2fa6-158802a1c3b3

IIUC this currently works without `DATA` thanks to this code:
https://github.com/rust-lang/rust/blob/e55d3f9c5213fe1a25366450127bdff67ad1eca2/src/librustc_codegen_llvm/back/write.rs#L995

LD docs have better explanation at https://sourceware.org/binutils/docs/ld/WIN32.html:
> DATA: The symbol is a variable or object, rather than a function. The import lib will export only an indirect reference to foo as the symbol _imp__foo (ie, foo must be resolved as *_imp__foo).

FWIW before opening this PR I tried adding `DATA` to every symbol except [these](https://github.com/rust-lang/rust/blob/be055d96c4c223a5ad49a0181f0b43bc46781708/src/librustc_hir/weak_lang_items.rs#L43-L47) and [these](https://github.com/rust-lang/rust/blob/b543afca9b90ad6e4689b6d613ab51f9d3ba15e7/src/liballoc/alloc.rs#L15-L29) to the previous PR https://github.com/rust-lang/rust/pull/70852 and all the tests passed locally with LD.

> What exactly do you mean by this?

I meant https://github.com/rust-lang/rust/blob/e55d3f9c5213fe1a25366450127bdff67ad1eca2/src/librustc_codegen_llvm/back/write.rs#L990
I think that's literally what dllexport does.

> Same question as above, what does "dllexport was applied" if we don't use dllexport.

Symbol was exported with `__imp_`.
Nightly DLLs don't have dllexport on that symbol:
```
$ llvm-nm `rustc --print sysroot`/lib/rustlib/x86_64-pc-windows-gnu/lib/std* | rg std_detect6detect5cache5CACHE
6f280048 D _ZN3std10std_detect6detect5cache5CACHE17hed91aa03ee9b39f3E
```
But dllexport for that symbol is present in the import library:
```
$ llvm-nm `rustc --print sysroot`/lib/rustlib/x86_64-pc-windows-gnu/lib/libstd* | rg std_detect6detect5cache5CACHE
00000000 I __imp__ZN3std10std_detect6detect5cache5CACHE17hed91aa03ee9b39f3E
00000000 I __nm__ZN3std10std_detect6detect5cache5CACHE17hed91aa03ee9b39f3E
---------------- D _ZN3std10std_detect6detect5cache5CACHE17hed91aa03ee9b39f3E
```

**Comment by petrochenkov** [comment]
@mati865 
It looks like I won't be able to investigate all of this in detail at least until mid-July, so I'm going to trust you with what should be the end state here, with some requirements
- no significant breakage to tier 1 pc-windows-gnu platforms (tier 3 uwp-windows-gnu can be broken)
- the change is broken into as many "atomic" independently landable PRs as possible.
- Each atomic change has a test case

**Comment by mati865** [comment]
> the change is broken into as many "atomic" independently landable PRs as possible.

This PR is already as atomic as it can be :(

> Each atomic change has a test case

Since there are import libraries created now I could make test for https://github.com/rust-lang/rust/issues/50176 to verify if the symbol is present.

**Comment by mati865** [comment]
Added test that depends on https://github.com/rust-lang/rust/pull/74009

**Comment by Muirrum** [comment]
@mati865 This is a triage bump

**Comment by mati865** [comment]
@rustbot modify labels: -S-waiting-on-author +S-waiting-on-review

The other PR was merged.

File: src/librustc_codegen_ssa/back/linker.rs [hunk 4]
```diff
@@ -524,8 +524,9 @@ impl<'a> Linker for GccLinker<'a> {
             return;
         }
 
+        let is_windows = self.sess.target.target.options.is_like_windows;
         let mut arg = OsString::new();
-        let path = tmpdir.join("list");
+        let path = tmpdir.join(if is_windows { "list.def" } else { "list" });
```
Comment (petrochenkov) [inline src/librustc_codegen_ssa/back/linker.rs:529]: Nit: it can be `list.def` in both cases?

**Comment by petrochenkov** [comment]
I don't have anything new to say compared to https://github.com/rust-lang/rust/pull/72049#issuecomment-647036824, unfortunately.

r=me after squashing commits if this doesn't break tier 1 targets.

File: src/librustc_codegen_ssa/back/linker.rs (hunk 4 above)
Comment (mati865) [reply src/librustc_codegen_ssa/back/linker.rs:529]: I'm not sure if this won't break linkers on Unix but I'll check tomorrow.

Comment (mati865) [reply src/librustc_codegen_ssa/back/linker.rs:529]: Seems to work just fine on Linux but looking at the docs version-scripts typically use `.map` extension.
What should I do here?

Comment (retep998) [reply src/librustc_codegen_ssa/back/linker.rs:529]: On Windows `.map` files have a different meaning. https://docs.microsoft.com/en-us/cpp/build/reference/map-generate-mapfile?view=vs-2019

Comment (mati865) [reply src/librustc_codegen_ssa/back/linker.rs:529]: On Windows MinGW linkers won't work unless that file has `.def` extension so it's out of the question here.

Comment (petrochenkov) [reply src/librustc_codegen_ssa/back/linker.rs:529]: Ok, if there are any doubts then it can stay as is.

**Comment by petrochenkov** [comment]
Needs a tidy fix.

**Comment by mati865** [comment]
Apparently I forgot to hit submit button after the rebase.
I've reworded my in-code comments hoping they are clearer now. I'll spellcheck them and fix tidy tomorrow.

**Comment by mati865** [comment]
I don't expect any breakage on the affected targets (only windows-gnu) but we should start testing ASAP and if need we can revert it for beta to give more time.

@bors r=petrochenkov
