### PR TITLE
unix fs: Make hurd using explicit new rather than From

### LINKED ISSUE #123032: GNU Hurd compilation failure: expected `SystemTime`, found `timespec`
Compiling project with `cargo build -Z build-std=std --target=i686-unknown-hurd-gnu --features="std"` causes the following compilation error:
```
error[E0308]: mismatched types
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/fs.rs:520:29
    |
520 |         Ok(SystemTime::from(self.stat.st_mtim))
    |            ---------------- ^^^^^^^^^^^^^^^^^ expected `SystemTime`, found `timespec`
    |            |
    |            arguments to this function are incorrect
    |
note: associated function defined here
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:585:8
    |
585 |     fn from(value: T) -> Self;
    |        ^^^^

error[E0308]: mismatched types
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/fs.rs:548:29
    |
548 |         Ok(SystemTime::from(self.stat.st_atim))
    |            ---------------- ^^^^^^^^^^^^^^^^^ expected `SystemTime`, found `timespec`
    |            |
    |            arguments to this function are incorrect
    |
note: associated function defined here
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:585:8
    |
585 |     fn from(value: T) -> Self;
    |        ^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `std` (lib) due to 2 previous errors
Error: Process completed with exit code 101.
```
See this [CI job](https://github.com/rust-random/getrandom/actions/runs/8390308799/job/23052022971).

### PR DESCRIPTION
**Pull request by sthibaul**
408c0ea2162b ("unix time module now return result") dropped the From impl for SystemTime, breaking the hurd build (and probably the horizon build)

Fixes #123032

### CODE REVIEW

**Comment by workingjubilee** [comment]
cc @leo60228 @jam1garner Should the Horizon targets get the same fix here?

**Comment by jhpratt** [comment]
r=me with that concern resolved ^^

**Comment by leo60228** [comment]
@workingjubilee I think you meant to ping the `armv6k-nintendo-3ds` maintainers (@Meziu, @AzureMarker, @ian-h-chamberlain)? `aarch64-nintendo-switch-freestanding` is currently `no_std` only.

**Comment by workingjubilee** [comment]
oops.

**Comment by workingjubilee** [comment]
@leo60228 Thanks, sorry about that!

**Comment by workingjubilee** [comment]
re: beta-nominated:

The relevant breaking commit has crept into the beta, as I noted here: https://github.com/rust-lang/rust/issues/123032#issuecomment-2019022537

This will fix the stdlib build for Debian Hurd, which is supposed to use the stable branch, per the policy cited by @sthibaul: https://github.com/rust-lang/rust/issues/123032#issuecomment-2018988270

It seems fairly harmless to backport this.

**Comment by ian-h-chamberlain** [comment]
Hi, thanks for the ping! I just double checked and yes, this fix would also apply for `horizon`, if you could roll it in here that would be great (or if not, we can open another PR after).

File: library/std/src/sys/pal/unix/fs.rs [hunk 1]
```diff
@@ -515,11 +515,16 @@ impl FileAttr {
...
 
-    #[cfg(any(target_os = "horizon", target_os = "hurd"))]
+    #[cfg(target_os = "horizon")]
     pub fn modified(&self) -> io::Result<SystemTime> {
         Ok(SystemTime::from(self.stat.st_mtim))
     }
 
+    #[cfg(target_os = "hurd")]
+    pub fn modified(&self) -> io::Result<SystemTime> {
+        SystemTime::new(self.stat.st_mtim.tv_sec as i64, self.stat.st_mtim.tv_nsec as i64)
```
Comment (Nilstrieb) [inline library/std/src/sys/pal/unix/fs.rs:525]: instead of adding the cfg here, can we align the impls for hurd `SystemTime` such that the old cfg works?

Comment (Nilstrieb) [reply library/std/src/sys/pal/unix/fs.rs:525]: Ah I see it applies to horizon too, in that case only the existing body has to be changed with no new functions, that sounds good.

**Comment by sthibaul** [comment]
I updated the change to include horizon too.

**Review by ian-h-chamberlain — APPROVED** [review]

**Comment by cuviper** [comment]
@Amanieu, we (T-release) deliberately remove "nominated" labels once a PR has been added to a backport PR.
