### PR TITLE
rustdoc: Fix resolution of `crate`-relative paths in doc links

### LINKED ISSUE #78696: intra-doc links: `crate::` considers the traits in the crate scope, not the current scope
I tried this code:

```rust
#![allow(unused_imports, dead_code)]

// Uncomment this and the warning will go away
// use crate::io::Read;

pub mod io {
    pub trait Read {
        fn read(&mut self, buf: &mut [u8]) -> usize;
    }
}

pub mod bufreader {
    use crate::io::Read;

    /// It can be excessively inefficient to work directly with a [`Read`] instance.
    /// For example, every [`Read::read`] call to [`TcpStream::read`] or [`TcpStream::yes`] on [`TcpStream`]
    ///
    /// [`TcpStream::yes`]: crate::net::TcpStream::yes
    /// [`TcpStream::read`]: crate::net::TcpStream::read
    /// [`Read::read`]: Read::read
    /// [`TcpStream`]: crate::net::TcpStream
    pub struct BufReader;
}

pub mod net {
    pub struct TcpStream;

    impl TcpStream {
        fn yes() -> bool {
            true
        }
    }

    impl crate::io::Read for TcpStream {
        fn read(&mut self, buf: &mut [u8]) -> usize {
            buf.len()
        }
    }
}
```

I expected to see this happen: Rustdoc should complete with no warnings

Instead, this happened:

Only the following warning is output by rustdoc
```sh
warning: unresolved link to `self::net::TcpStream::read`
  --> src/main.rs:13:30
   |
13 |     /// [`TcpStream::read`]: crate::net::TcpStream::read
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the struct `TcpStream` has no field or associated item named `read`
   |
   = note: `#[warn(broken_intra_doc_links)]` on by default
```

If you uncomment the line as it says, the warning goes away.

### Meta

`rustc +stage2 --version --verbose`:
```
rustc 1.49.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.49.0-dev
```

Commit hash: b2025326088b54fb3f083bebeba14e0a15bf00d3

Here's a crate that repros this issue: https://github.com/pitaj/rustdoc-78006-repro

@rustbot modify labels: T-doc, A-intra-doc-links

@jyn514 Here's the repro I promised.

First came across this in #78006

### LINKED ISSUE #94924: rustdoc shows `self::` path in a warning when `crate::` was used
The following code currently produces the following warning:
```rust
#![warn(rustdoc::broken_intra_doc_links)]

/// [a](crate::DoesNotExist)
pub struct Item;
```
```text
warning: unresolved link to `self::DoesNotExist`
 --> src/lib.rs:3:9
  |
3 | /// [a](crate::DoesNotExist)
  |         ^^^^^^^^^^^^^^^^^^^ no item named `DoesNotExist` in module `rustdoc_why_self`
  |
note: the lint level is defined here
 --> src/lib.rs:1:9
  |
1 | #![warn(rustdoc::broken_intra_doc_links)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Note that the warning says "unresolved link to `self::DoesNotExist`" even though the code mentions `crate::DoesNotExist`

@rustbot label +T-rustdoc +A-intra-doc-links

### Meta

`rustdoc --version --verbose`:
```
rustdoc 1.61.0-nightly (4ce374923 2022-02-28)
binary: rustdoc
commit-hash: 4ce3749235fc31d15ebd444b038a9877e8c700d7
commit-date: 2022-02-28
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Resolve `crate::foo` paths transparently to rustdoc, so their resolution no longer affects diagnostics and modules used for determining traits in scope.

The proper solution is to account for the current `module_id`/`parent_scope` in `fn resolve_crate_root`, but it's a slightly larger compiler changes. This PR moves the code closer to it, but keeps it rustdoc-specific.

Fixes https://github.com/rust-lang/rust/issues/78696
Fixes https://github.com/rust-lang/rust/issues/94924

### CODE REVIEW

File: compiler/rustc_resolve/src/lib.rs [hunk 1]
```diff
@@ -3285,12 +3285,21 @@ impl<'a> Resolver<'a> {
...
         path_str: &str,
         ns: Namespace,
-        module_id: DefId,
+        mut module_id: DefId,
     ) -> Option<Res> {
         let mut segments =
             Vec::from_iter(path_str.split("::").map(Ident::from_str).map(Segment::from_ident));
-        if path_str.starts_with("::") {
-            segments[0].ident.name = kw::PathRoot;
+        if let Some(segment) = segments.get_mut(0) {
```
Comment (camelid) [inline compiler/rustc_resolve/src/lib.rs:3292]:
```suggestion
        if let Some(segment) = segments.first_mut() {
```

File: src/test/rustdoc-ui/intra-doc/crate-nonexistent.rs [hunk 2]
```diff
@@ -0,0 +1,4 @@
+#![deny(rustdoc::broken_intra_doc_links)]
+
+/// [crate::DoesNotExist] //~ ERROR unresolved link to `crate::DoesNotExist`
```
Comment (camelid) [inline src/test/rustdoc-ui/intra-doc/crate-nonexistent.rs:3]: I'd rather the comment not be part of the docs it's testing:

```suggestion
/// [crate::DoesNotExist]
//~^ ERROR unresolved link to `crate::DoesNotExist`
```

File: src/librustdoc/passes/collect_intra_doc_links/early.rs [hunk 3]
```diff
@@ -32,11 +32,6 @@ crate fn early_resolve_intra_doc_links(
         all_trait_impls: Default::default(),
     };
 
-    // Because of the `crate::` prefix, any doc comment can reference
-    // the crate root's set of in-scope traits. This line makes sure
-    // it's available.
-    loader.add_traits_in_scope(CRATE_DEF_ID.to_def_id());
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links/early.rs:38]: Can you explain to me the rationale of why this is no longer necessary (i.e., what the new behavior is) with the new way `crate::` is resolved? I partially understand, but I want to make sure I understand fully.

File: src/librustdoc/passes/collect_intra_doc_links/early.rs [hunk 4]
```diff
@@ -105,9 +100,6 @@ impl IntraLinkCrateLoader<'_, '_> {
     /// having impls in them.
     fn add_foreign_traits_in_scope(&mut self) {
         for cnum in Vec::from_iter(self.resolver.cstore().crates_untracked()) {
-            // FIXME: Due to #78696 rustdoc can query traits in scope for any crate root.
-            self.add_traits_in_scope(cnum.as_def_id());
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links/early.rs:109]: Ditto.

**Review by camelid — COMMENTED** [review]
Thanks for this refactoring! It looks very good overall; I just have a few questions.

File: src/librustdoc/passes/collect_intra_doc_links/early.rs (hunk 3 above)
Comment (petrochenkov) [reply src/librustdoc/passes/collect_intra_doc_links/early.rs:38]: `crate::Type::AssocItem` now takes the set of traits in scope at the point where it's written, and not elsewhere (in the crate root module). This is the change that fixes https://github.com/rust-lang/rust/issues/78696.

So we no longer need to collect traits in scope at arbitrary root modules.

(The old buggy behavior was caused by replacing `module_id` with `CRATE_DEF_ID` too early.)

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links/early.rs:38]: > (The old buggy behavior was caused by replacing module_id with CRATE_DEF_ID too early.)

Ah, thanks, I understand now.

**Comment by petrochenkov** [comment]
Updated.
@rustbot ready

**Comment by petrochenkov** [comment]
ping @camelid

**Review by camelid — APPROVED** [review]
Sorry for the delay, I got busy.

**Comment by rylev** [comment]
@petrochenkov @camelid this broke one of the perf benchmarks. You can see the error if you click of the perf comparison url and look at the "Newly broken benchmarks" section. I've pasted the error below. 

Looks like the this PR caused [this unreachable code](https://github.com/rust-lang/rust/blob/949b98cab8a186b98bf87e64374b8d0848c55271/compiler/rustc_resolve/src/lib.rs#L3302) to be reached. 

<details> 
```
expected success, got exit status: 101

stderr= Documenting hyper v0.14.18 (/tmp/.tmpR27TDg)
warning: unresolved link to `HttpConnector`
  --> src/client/connect/mod.rs:76:24
   |
76 | //! [`HttpConnector`]: HttpConnector
   |                        ^^^^^^^^^^^^^ no item named `HttpConnector` in scope
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_resolve/src/lib.rs:3302:67
stack backtrace:
   0:     0x7ffff3aca1dd - std::backtrace_rs::backtrace::libunwind::trace::h75176593bb62f62a
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ffff3aca1dd - std::backtrace_rs::backtrace::trace_unsynchronized::h12654fcc70e2c601
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffff3aca1dd - std::sys_common::backtrace::_print_fmt::h081a0a8322e3e74e
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7ffff3aca1dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he5cb783ae9a0bd4d
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7ffff3b2402c - core::fmt::write::heb8d87aaf445edfe
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/core/src/fmt/mod.rs:1194:17
   5:     0x7ffff3abb7d1 - std::io::Write::write_fmt::hfc2c392af2391fc5
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/io/mod.rs:1655:15
   6:     0x7ffff3acd2c5 - std::sys_common::backtrace::_print::he7692a4ef31f048c
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7ffff3acd2c5 - std::sys_common::backtrace::print::hf1603cac26d5cb4b
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7ffff3acd2c5 - std::panicking::default_hook::{{closure}}::h6b5f6cb3ea4b85e5
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/panicking.rs:295:22
   9:     0x7ffff3accf79 - std::panicking::default_hook::h483e5e433ebc4d74
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/panicking.rs:314:9
  10:     0x7ffff424abb1 - rustc_driver[222a2ff83352d4e4]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7ffff3acda10 - std::panicking::rust_panic_with_hook::h1e6ab8b51ddf2684
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/panicking.rs:702:17
  12:     0x7ffff3acd809 - std::panicking::begin_panic_handler::{{closure}}::hdc8d1488a17520d7
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/panicking.rs:586:13
  13:     0x7ffff3aca694 - std::sys_common::backtrace::__rust_end_short_backtrace::h27b6ba662afd99b9
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7ffff3acd579 - rust_begin_unwind
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/panicking.rs:584:5
  15:     0x7ffff3a916c3 - core::panicking::panic_fmt::h22ec5cb40549a7de
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/core/src/panicking.rs:143:14
  16:     0x7ffff3a9158d - core::panicking::panic::hf3fcde471d557154
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/core/src/panicking.rs:48:5
  17:     0x7ffff468dfcc - <rustc_resolve[cf0048bb215d1c2]::Resolver>::resolve_rustdoc_path
  18:     0x55555587bbb0 - <rustdoc[4914734c398c8c87]::core::DocContext>::enter_resolver::<<rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector>::resolve_path::{closure#0}, core[8d315dfdf426e172]::option::Option<rustc_hir[849237a15a4cdc53]::def::Res<rustc_ast[e776d9e7e3e27950]::node_id::NodeId>>>
  19:     0x5555557c90a4 - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  20:     0x5555557ca4de - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector>::resolve
  21:     0x5555557d0d96 - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4914734c398c8c87]::visit::DocVisitor>::visit_item
  22:     0x5555557db9ba - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4914734c398c8c87]::visit::DocVisitor>::visit_inner_recur
  23:     0x5555557d3014 - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4914734c398c8c87]::visit::DocVisitor>::visit_item
  24:     0x5555557db9ba - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4914734c398c8c87]::visit::DocVisitor>::visit_inner_recur
  25:     0x5555557d3014 - <rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4914734c398c8c87]::visit::DocVisitor>::visit_item
  26:     0x5555557c848c - rustdoc[4914734c398c8c87]::passes::collect_intra_doc_links::collect_intra_doc_links
  27:     0x555555620ef4 - <rustc_session[7828e3b06ab6d75f]::session::Session>::time::<rustdoc[4914734c398c8c87]::clean::types::Crate, rustdoc[4914734c398c8c87]::core::run_global_ctxt::{closure#8}>
  28:     0x5555558821ed - rustdoc[4914734c398c8c87]::core::run_global_ctxt
  29:     0x555555621362 - <rustc_session[7828e3b06ab6d75f]::session::Session>::time::<(rustdoc[4914734c398c8c87]::clean::types::Crate, rustdoc[4914734c398c8c87]::config::RenderOptions, rustdoc[4914734c398c8c87]::formats::cache::Cache), rustdoc[4914734c398c8c87]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  30:     0x5555558dd356 - <rustc_interface[bfae82b4e08272cc]::passes::QueryContext>::enter::<rustdoc[4914734c398c8c87]::main_options::{closure#0}::{closure#0}::{closure#1}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>
  31:     0x55555580775b - rustc_interface[bfae82b4e08272cc]::interface::create_compiler_and_run::<core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>, rustdoc[4914734c398c8c87]::main_options::{closure#0}>
  32:     0x555555654773 - rustdoc[4914734c398c8c87]::main_options
  33:     0x555555695a0b - <scoped_tls[29151e41f7e0807]::ScopedKey<rustc_span[73acaaee73cf7b1c]::SessionGlobals>>::set::<rustdoc[4914734c398c8c87]::main_args::{closure#0}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>
  34:     0x5555557b220f - std[ea65a2ca40ed4585]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bfae82b4e08272cc]::util::run_in_thread_pool_with_globals<rustdoc[4914734c398c8c87]::main_args::{closure#0}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>::{closure#0}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>
  35:     0x5555558a0fd9 - <<std[ea65a2ca40ed4585]::thread::Builder>::spawn_unchecked_<rustc_interface[bfae82b4e08272cc]::util::run_in_thread_pool_with_globals<rustdoc[4914734c398c8c87]::main_args::{closure#0}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>::{closure#0}, core[8d315dfdf426e172]::result::Result<(), rustc_errors[dbeffaaccd898c48]::ErrorGuaranteed>>::{closure#1} as core[8d315dfdf426e172]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x7ffff3ad7c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc61524b7de27ca02
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/alloc/src/boxed.rs:1861:9
  37:     0x7ffff3ad7c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h276e5f67aaedfc7d
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/alloc/src/boxed.rs:1861:9
  38:     0x7ffff3ad7c03 - std::sys::unix::thread::Thread::new::thread_start::heac60c31b6e17c64
                               at /rustc/949b98cab8a186b98bf87e64374b8d0848c55271/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7ffff38146db - start_thread
                               at /build/glibc-S9d2JN/glibc-2.27/nptl/pthread_create.c:463
  40:     0x7ffff2b7b71f - __GI___clone
                               at /build/glibc-S9d2JN/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  41:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (949b98cab 2022-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z incremental -Z self-profile=/tmp/.tmpR27TDg/self-profile-output

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread 'main' panicked at 'command did not complete successfully: "perf" "stat" "-x;" "-e" "instructions:u,cycles:u,task-clock,cpu-clock,faults,context-switches" "--log-fd" "1" "setarch" "x86_64" "-R" "/home/collector/rustc-perf/cache/949b98cab8a186b98bf87e64374b8d0848c55271/bin/rustdoc" "--edition=2018" "--crate-type" "lib" "--crate-name" "hyper" "src/lib.rs" "-o" "/tmp/.tmpR27TDg/target/doc" "--cfg" "feature=\"client\"" "--cfg" "feature=\"default\"" "--cfg" "feature=\"h2\"" "--cfg" "feature=\"http1\"" "--cfg" "feature=\"http2\"" "--cfg" "feature=\"server\"" "--cfg" "feature=\"stream\"" "--error-format=json" "--json=diagnostic-rendered-ansi,artifacts,future-incompat" "-C" "metadata=74705a8a0fde0363" "-L" "dependency=/tmp/.tmpR27TDg/target/debug/deps" "--extern" "bytes=/tmp/.tmpR27TDg/target/debug/deps/libbytes-0b6620405fcf1713.rmeta" "--extern" "futures_channel=/tmp/.tmpR27TDg/target/debug/deps/libfutures_channel-02da1a1cb4f62b2e.rmeta" "--extern" "futures_core=/tmp/.tmpR27TDg/target/debug/deps/libfutures_core-5fb9cc94722604e5.rmeta" "--extern" "futures_util=/tmp/.tmpR27TDg/target/debug/deps/libfutures_util-777b06c944bd2cf2.rmeta" "--extern" "h2=/tmp/.tmpR27TDg/target/debug/deps/libh2-d0a9117f2fd97e74.rmeta" "--extern" "http=/tmp/.tmpR27TDg/target/debug/deps/libhttp-e99ce43994491469.rmeta" "--extern" "http_body=/tmp/.tmpR27TDg/target/debug/deps/libhttp_body-5a14cbff275f9bd9.rmeta" "--extern" "httparse=/tmp/.tmpR27TDg/target/debug/deps/libhttparse-383992b20d31af4a.rmeta" "--extern" "httpdate=/tmp/.tmpR27TDg/target/debug/deps/libhttpdate-7325359abe6f9cd0.rmeta" "--extern" "itoa=/tmp/.tmpR27TDg/target/debug/deps/libitoa-ffb405c4aca92714.rmeta" "--extern" "pin_project_lite=/tmp/.tmpR27TDg/target/debug/deps/libpin_project_lite-b1034f76d9613473.rmeta" "--extern" "tokio=/tmp/.tmpR27TDg/target/debug/deps/libtokio-9d84a93d231916f8.rmeta" "--extern" "tower_service=/tmp/.tmpR27TDg/target/debug/deps/libtower_service-d28b356326dc660e.rmeta" "--extern" "tracing=/tmp/.tmpR27TDg/target/debug/deps/libtracing-3198eda78fea3217.rmeta" "--extern" "want=/tmp/.tmpR27TDg/target/debug/deps/libwant-2dbdeb7840d3ea3d.rmeta" "--crate-version" "0.14.18" "-Adeprecated" "-Aunknown-lints" "-Zincremental-verify-ich" "-Zself-profile=/tmp/.tmpR27TDg/self-profile-output"', collector/src/rustc-fake.rs:24:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: `hyper` (lib doc) generated 1 warning
error: could not document `hyper`

Caused by:
  process didn't exit successfully: `/home/collector/rustc-perf/target/release/rustdoc-fake --edition=2018 --crate-type lib --crate-name hyper src/lib.rs -o /tmp/.tmpR27TDg/target/doc --cfg 'feature="client"' --cfg 'feature="default"' --cfg 'feature="h2"' --cfg 'feature="http1"' --cfg 'feature="http2"' --cfg 'feature="server"' --cfg 'feature="stream"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --wrap-rustc-with PerfStatSelfProfile -C metadata=74705a8a0fde0363 -L dependency=/tmp/.tmpR27TDg/target/debug/deps --extern bytes=/tmp/.tmpR27TDg/target/debug/deps/libbytes-0b6620405fcf1713.rmeta --extern futures_channel=/tmp/.tmpR27TDg/target/debug/deps/libfutures_channel-02da1a1cb4f62b2e.rmeta --extern futures_core=/tmp/.tmpR27TDg/target/debug/deps/libfutures_core-5fb9cc94722604e5.rmeta --extern futures_util=/tmp/.tmpR27TDg/target/debug/deps/libfutures_util-777b06c944bd2cf2.rmeta --extern h2=/tmp/.tmpR27TDg/target/debug/deps/libh2-d0a9117f2fd97e74.rmeta --extern http=/tmp/.tmpR27TDg/target/debug/deps/libhttp-e99ce43994491469.rmeta --extern http_body=/tmp/.tmpR27TDg/target/debug/deps/libhttp_body-5a14cbff275f9bd9.rmeta --extern httparse=/tmp/.tmpR27TDg/target/debug/deps/libhttparse-383992b20d31af4a.rmeta --extern httpdate=/tmp/.tmpR27TDg/target/debug/deps/libhttpdate-7325359abe6f9cd0.rmeta --extern itoa=/tmp/.tmpR27TDg/target/debug/deps/libitoa-ffb405c4aca92714.rmeta --extern pin_project_lite=/tmp/.tmpR27TDg/target/debug/deps/libpin_project_lite-b1034f76d9613473.rmeta --extern tokio=/tmp/.tmpR27TDg/target/debug/deps/libtokio-9d84a93d231916f8.rmeta --extern tower_service=/tmp/.tmpR27TDg/target/debug/deps/libtower_service-d28b356326dc660e.rmeta --extern tracing=/tmp/.tmpR27TDg/target/debug/deps/libtracing-3198eda78fea3217.rmeta --extern want=/tmp/.tmpR27TDg/target/debug/deps/libwant-2dbdeb7840d3ea3d.rmeta --crate-version 0.14.18` (exit status: 101)


 stdout=6460071822;;instructions:u;1249486087;100.00;1.44;insn per cycle;;
4496385516;;cycles:u;1249486087;100.00;3.598;GHz
1249.529528;;task-clock;1249529528;100.00;0.988;CPUs utilized
```
</details>

**Comment by petrochenkov** [comment]
@rylev 
I'll investigate.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/95681.
