### PR TITLE
Fix #54707 - parse_trait_item_ now handles interpolated blocks as function body decls

### LINKED ISSUE #54707: Creating a trait function with a macro using block designator: error: expected `;` or `{`, found `{ ... }`
Given a simple macro:
```rust
macro_rules! def_fn{
    ($body:block) => {
        fn test() $body
    };
}
```

I can use it without problems to define a function:
```rust
def_fn!({println!("test"); });
```

I can also use it to define a struct method without problems:
```rust
struct Test {}

impl Test {
    def_fn!({println!("test"); });
}
```

However when I try to use it to define a default method for a trait it doesn't work:
```rust
trait Test {
    def_fn!({println!("test"); });
}
```

It gives an error message:
```
error: expected `;` or `{`, found `{ println!("test"); }`
  --> src/main.rs:9:19
   |
9  |         fn test() $body
   |                   ^^^^^ expected `;` or `{`
...
16 |     def_fn!({println!("test"); });
   |     ------------------------------ in this macro invocation
error: aborting due to previous error
```

If I change the macro to include braces around `$body` it works:
```rust
macro_rules! def_fn{
    ($body:block) => {
        fn test() {$body}
    };
}
```

I have no idea why this happens but I guess it is some sort of bug in how default trait methods are parsed.

### PR DESCRIPTION
**Pull request by matthew-russo**
Fix #54707 - parse_trait_item_ now handles interpolated blocks as function body decls

Previously parsing trait items only handled opening brace token and semicolon, I added a branch to the match statement that will also handle interpolated blocks.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Can you add some form of test, @mcr431 ?

**Comment by mcr431** [comment]
@nikomatsakis added a test, let me know if you'd like any more or if it should be in a different spot. first time adding a new test.

File: src/test/run-pass/traits/traits-default-method-macro2.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+macro_rules! def_fn {
+    ($body:block) => {
+        fn bar() $body
+    }
+}
+
+trait Foo {
+    def_fn!({ println!("bar"); });
+}
```
Comment (nikomatsakis) [inline src/test/run-pass/traits/traits-default-method-macro2.rs]: Thanks =) I think it'd be good to include in the text the other various places one might use this as well -- e.g., for a free function etc. Skimming the existing tests I did find that `macros/macro-interpolation.rs` and `macros/macro-stmt` both test the free fn case but there don't appear to be tests in impls.

Comment (nikomatsakis) [reply src/test/run-pass/traits/traits-default-method-macro2.rs]: I think it'd be good to just have one single test dedicated to testing that `$b` can be used as a fn body in all relevant contexts (the other tests are kind of testing a wider variety of things)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/run-pass/traits/traits-default-method-macro2.rs (hunk 1 above)
Comment (mcr431) [reply src/test/run-pass/traits/traits-default-method-macro2.rs]: Noted. will update and let you know when its ready

**Comment by mcr431** [comment]
@nikomatsakis I made a new test file: `src/test/run-pass/macros/macro-as-fn-body.rs` that includes the 3 situations described in the issue  -- free function, method, and default trait method. If I'm missing any or you'd like something changed let me know

**Review by nikomatsakis — APPROVED** [review]
