### PR TITLE
Remove attributes from generics in built-in derive macros

### LINKED ISSUE #132561: Proc-macro helper attributes on lifetime and const parameters fail to resolve if a built-in derive macro is present
I was making a derive proc macro and stumbled upon this weird error, and was told on the rust discord that this might be a bug. Basically, I have a proc macro that uses a helper attribute like this:

```rust
#[proc_macro_derive(Test, attributes(test_helper))]
pub fn derive(input: TokenStream) -> TokenStream {
    ...
}
```

The `#[test_helper]` attribute is used on generics - including lifetime generics.

When I use it normally it works fine, but if I try to derive it together with another trait, such as `Clone` - it fails to compile, saying that `#[test_helper]` was not found in the scope.

```rust
#[derive(Test, Clone)]
struct MyStruct<#[test_helper] 'a> {
    inner: &'a (),
}
```

```rust
error: cannot find attribute `test_helper` in this scope
 --> src/lib.rs:3:19
  |
3 | struct MyStruct<#[test_helper] 'a> {
  |                   ^^^^^^^^^^^
```

There is no error if I put the attribute on a type generic or on a field.

`cargo expand`-ed code:

```rust
struct MyStruct<#[test_helper] 'a> {
    inner: &'a (),
}
#[automatically_derived]
impl<#[test_helper] 'a> ::core::clone::Clone for MyStruct<'a> {
    #[inline]
    fn clone(&self) -> MyStruct<'a> {
        MyStruct {
            inner: ::core::clone::Clone::clone(&self.inner),
        }
    }
}
```

[I have also made a minimal reproducible example.](https://github.com/PonasKovas/macro_helper_attribute_bug)

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b3f75cc87 2024-11-02)
binary: rustc
commit-hash: b3f75cc872cfd306860c3ad76a239e719015f855
commit-date: 2024-11-02
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

If this is really a bug, I can try to investigate if anyone can help me and point me in the right direction.

### PR DESCRIPTION
**Pull request by PonasKovas**
Related issue #132561 

Removes all attributes from generics in the expanded implementations of built-in derive macros.

### CODE REVIEW

**Review by fmease — COMMENTED** [review]
Could you add regression tests for #132561?

**Comment by fmease** [comment]
Note to others: This is consistent with the current behavior for type parameters. I've thought about this and while technically *technically* speaking it's a breaking change, I don't think it's observable by the user -- apart from affecting the emission of lints

   1. which is mostly(?) excluded from Rust's stability guarantees
   2. which is unreachable/masked anyway due to a bug, cc https://github.com/rust-lang/rust/issues/61552

File: compiler/rustc_builtin_macros/src/deriving/generic/mod.rs
Comment (fmease) [inline compiler/rustc_builtin_macros/src/deriving/generic/mod.rs:1]: So a UI test for the helper attr issue would sth. like the following (I haven't tested this):

`auxiliary/dep.rs`:

```rs
//@ force-host
//@ no-prefer-dynamic
#![crate_type = "proc-macro"]

extern crate proc_macro;

#[proc_macro_derive(M, attributes(x))] 
pub fn m(_: proc_macro::TokenStream) -> proc_macro::TokenStream { Default::default() }
```

`usr.rs`:

```rs
// <DESCRIPTION OF THIS TEST>
// issue: rust-lang/rust#132561
//@ check-pass
//@ aux-crate:a=a.rs
//@ edition: 2021

#[derive(a::M, Clone)] struct S<#[x] 'a>(&'a ());

fn main() {}
```

Of course, you should pick better file names and a fitting directory.

Comment (PonasKovas) [reply compiler/rustc_builtin_macros/src/deriving/generic/mod.rs:1]: Ahh, I didn't add the issue link to the test

**Comment by nnethercote** [comment]
@fmease, I'll pass the review to you.

**Comment by PonasKovas** [comment]
@fmease  Is there a problem? I don't want to be annoying or rush things, just wondering. My project is partially blocked by this bug, so I'm just not sure if I am to expect a fix (whether this PR, or something else) to be merged in a relatively short time frame, or should I just use a workaround in my project for now?

Again, I don't want to rush anything, just want to know what is the situation 😅

File: compiler/rustc_builtin_macros/src/deriving/generic/mod.rs [hunk 1]
```diff
@@ -680,6 +680,12 @@ impl<'a> TraitDef<'a> {
                     param_clone
                 }
             })
+            .map(|mut param| {
+                // Remove all attributes, because there might be helper attributes
+                // from other macros that will not be valid in the expanded implementation.
+                param.attrs = ThinVec::new();
```
Comment (fmease) [inline compiler/rustc_builtin_macros/src/deriving/generic/mod.rs:686]: Right now, we clear the attrs of the param after having cloned the entire param. As a result we clone the attrs only to throw them away. However, avoiding this makes the code more awkward. I've just noticed that we also needlessly clone const parameter defaults. Er, this could be addressed in a separate PR, if need be.

**Review by fmease — APPROVED** [review]
Sorry for the delay, one suggestion

File: compiler/rustc_builtin_macros/src/deriving/generic/mod.rs (hunk 1 above)
Comment (PonasKovas) [reply compiler/rustc_builtin_macros/src/deriving/generic/mod.rs:686]: I think the compiler would optimize it away, and writing it like this is easier to read?

Either way, if this whole thing might be significantly changed in the near future by addressing the real bug here (#61552), I don't think it's necessary to do anything about it in this PR

[the remark this answers is not in the document]
Comment (PonasKovas) [reply compiler/rustc_builtin_macros/src/deriving/generic/mod.rs:686]: The reason I wrote it like this, was that I assumed creating a new `ThinVec` doesn't allocate, and by creating a new one instead of just clearing the old one, we're telling the compiler that we don't need the allocated memory, which is a nano-optimization, if the compiler doesn't already optimize it away in either case haha.

**Review by fmease — APPROVED** [review]
Ah, I forgot to say, could you squash into one commit? Then I'll place it into merge queue.

**Comment by PonasKovas** [comment]
@fmease Done

**Comment by fmease** [comment]
> https://github.com/rust-lang/rust/pull/132651#issuecomment-2457768951

This is clearly a bug fix and doesn't need T-lang involvement (cc rust-lang/lang-team#290).
Therefore I'll unilaterally approve this PR.

@bors r+
