### PR TITLE
Issue #50974 : Suboptimal error in case of duplicate `,` in struct constructor

### LINKED ISSUE #50974: Suboptimal error in case of duplicate `,` in struct constructor
```rust
struct Foo {
    a: i32,
    b: i32,
}

fn main() {
    let x = Foo {
        a: 42,,
        b: 3,
    };
}
```

results  in 

```
error: expected identifier, found `,`
 --> src/main.rs:9:15
  |
8 |     let x = Foo {
  |             --- while parsing this struct
9 |         a: 42,,
  |               ^ expected identifier

error[E0063]: missing field `b` in initializer of `Foo`
 --> src/main.rs:8:13
  |
8 |     let x = Foo {
  |             ^^^ missing `b`
```

we may want to add a parser recovery that just reports the error, eats the comma and continues parsing as normally

### PR DESCRIPTION
**Pull request by lambtowolf**
Fixes #50974

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -767,6 +767,9 @@ impl<'a> Parser<'a> {
             err.span_label(self.span, format!("expected identifier, found {}", token_descr));
         } else {
             err.span_label(self.span, "expected identifier");
+            if self.token == token::Comma {
+                err.span_suggestion(self.span, "remove this comma", ",".into());
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: The third argument here [should be an empty string](https://github.com/rust-lang/rust/pull/51184/files#diff-da9d34ca1d0f6beee2838cf02e07345cR2515). This will change the output to `help: remove this comma`.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -767,6 +767,9 @@ impl<'a> Parser<'a> {
             err.span_label(self.span, format!("expected identifier, found {}", token_descr));
         } else {
             err.span_label(self.span, "expected identifier");
+            if self.token == token::Comma {
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: I'm not sure this is the best thing to do, as is. I would only add this suggestion if the next token is indeed an ident:

```
    if self.token == token::Comma && self.look_ahead(1, |t| *t.is_ident()) {
```

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -2527,8 +2530,11 @@ impl<'a> Parser<'a> {
                 Err(mut e) => {
                     e.span_label(struct_sp, "while parsing this struct");
                     e.emit();
-                    self.recover_stmt();
-                    break;
+
+                    if self.token != token::Comma {
```
Comment (nikomatsakis) [inline src/libsyntax/parse/parser.rs]: This confuses me a bit — when does this `,` token get dropped, if not by `recover_stmt`?

Comment (lambtowolf) [reply src/libsyntax/parse/parser.rs]: It gets dropped afterwards at line 2541 : 
```rust
self.expect_one_of(&[token::Comma], &[token::CloseDelim(token::Brace)])
```

File: src/libsyntax/parse/parser.rs (hunk 2 above)
Comment (lambtowolf) [reply src/libsyntax/parse/parser.rs]: I think it will still be useful even if the next token is not an identifier. We should not ever have 2 commas in a row in a struct constructor.
```rust
struct Bar {
    a: u8,
    b: u8
}

let foo = Bar {
    a: 42,
    b: 42,,
};
```
In this example, the user still has to remove the comma to get his code to compile.

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/libsyntax/parse/parser.rs]: Ah, I see now. Yes, put a comment if you don't mind.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@lambtowolf think you can add that explanatory comment? =)

**Comment by nikomatsakis** [comment]
@lambtowolf Needs rebase 😿

**Comment by pietroalbini** [comment]
@lambtowolf you should rebase on master, even if you don't see any conflict at first glance.

**Comment by pietroalbini** [comment]
Ping from triage @lambtowolf! It's been a while since we heard from you, will you have time to work on this again?

**Comment by pietroalbini** [comment]
Rebased this on top of the latest master.

@bors r=nikomatsakis
