### PR TITLE
fix: dedup `static_candidates` before report

### LINKED ISSUE #103646: Unhelpful help when calling associated trait function as method
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=895f7d2db9412f8cb60bcdd2fa05105d

```rust
trait Cat {
    fn nya() {}
}

fn uwu<T: Cat>(c: T) {
    c.nya();
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): no method named `nya` found for type parameter `T` in the current scope
 --> src/lib.rs:6:7
  |
5 | fn uwu<T: Cat>(c: T) {
  |        - method `nya` not found for this type parameter
6 |     c.nya();
  |       ^^^ this is an associated function, not a method
  |
  = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in the trait `Cat`
 --> src/lib.rs:2:5
  |
2 |     fn nya() {}
  |     ^^^^^^^^
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: disambiguate the associated function for the candidate
  |
6 |     <T as Cat>::nya(c);
  |     ~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error
```

```
Compiling playground v0.0.1 (/playground)
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): no method named `nya` found for type parameter `T` in the current scope
 --> src/lib.rs:6:7
  |
5 | fn uwu<T: Cat>(c: T) {
  |        - method `nya` not found for this type parameter
6 |     c.nya();
  |       ^^^ this is an associated function, not a method
  |
  = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in the trait `Cat`
 --> src/lib.rs:2:5
  |
2 |     fn nya() {}
  |     ^^^^^^^^


For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error
```

The error already explains the problem ("this is an associated function, not a method") and the suggestion to use a fully qualified call doesn't help. Optionally,  it could even suggest calling `T::nya()` instead.

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes https://github.com/rust-lang/rust/issues/103646

`record_static_candidate` had been executed twice, resulting in the presence of two identical `CandidateSource::Trait(Cat)`  in static_candidates. This PR aims to deduplication the `static_candidates` list, allowing it to execute `suggest_associated_call_syntax` properly.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -473,6 +473,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let mut custom_span_label = false;
 
         let static_candidates = &mut no_match_data.static_candidates;
+
+        static_candidates.dedup();
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:477]: Could you add a comment why we cannot remove the duplicated call to `record_static_candidate`?

Comment (bvanjoi) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:480]: `inherent` and `extension` may append the same item to `static_candidates`.

For example:

```rs
trait Cat {
    fn nya() {}
}

fn uwu<T: Cat>(c: T) {
    c.nya();
}
```

Both `<T as Cat>` (inherent) and `<_ as Cat>` (extension) had been tried.

And another:

```rs
trait Cat {
    fn nya() {}
}

fn uwu<T>(c: T) {
    c.nya();
}
```

`<_ as Cat>` (extension) should be tried.

Therefore, we can't remove duplicated call of `record_static_candidate`.

Comment (cjgillot) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:480]: The comment you added says that in order to improve the diagnostic, we record both inherent and extension cases. But this PR does the opposite: we deduplicate to improve the diagnostic.
You don't need to link to the PR. The 2 lines-long explanation is enough.

Comment (bvanjoi) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:480]: I have two questions:
1. Is it correct to say that we cannot remove the duplicated call of ﻿`record_static_candidate`? Also, is it intended behavior that the unexpected diagnostic of #103646 was caused by invoking ﻿`record_static_candidate` for the same item in both ﻿`assemble_extension_candidates_for_trait` and ﻿`assemble_inherent_impl_probe`?
2. Is ﻿`static_candidates.dedup()` the right approach here? If this statement has too broad impact, can we change the condition to ﻿`!self.has_applicable_self(&item) && !self.static_candidates.contains(&item)` in [extension_candidates](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_typeck/src/method/probe.rs#L968)?

**Comment by cjgillot** [comment]
Thanks!
@bors r+
