### PR TITLE
Suggest type for overflowing bin/hex-literals

### LINKED ISSUE #48073: Wrong warning?: literal out of range for i8
I have this code:

```
fn main() {
    println!("-1 = {:b}", -1 as i8);
    println!("0b11111111 = {}", 0b11111111 as i8);
}
```

Both lines return the expected result, namely

> -1 = 11111111
> 0b11111111 = -1

However, the compiler raises a warning as follows:

warning: src\main.rs:3: literal out of range for i8
note: src\main.rs:3: #[warn(overflowing_literals)] on by default

To my understanding, `0b11111111` is a valid signed integer and means -1 in decimal. Therefore the warning seems to be wrong to me.

### PR DESCRIPTION
**Pull request by flip1995**
Fixes #48073 

For hexadecimal and binary literals, which overflow, it gives an additional note to the warning message, like in this [comment](https://github.com/rust-lang/rust/issues/48073#issuecomment-365370113).

Additionally it will suggest a type (`X < Y`):
- `iX`: if literal fits in `uX` => `uX`, else => `iY`
- `-iX` => `iY`
- `uX` => `uY`

Exceptions: `isize`, `usize`. I don't think you can make a good suggestion here. The programmer has to figure it out on it's own in this case.

r? @oli-obk

### CODE REVIEW

File: src/librustc_lint/types.rs [hunk 1]
```diff
@@ -152,11 +152,52 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
-                                                 e.span,
-                                                 &format!("literal out of range for {:?}", t));
+                                if (negative && v > max + 1) || (!negative && v > max) {
+                                    if let Some(repr_str) = get_bin_hex_repr(cx, lit) {
+                                        let bits = int_ty_bits(t, cx.sess().target.isize_ty);
+                                        let mut actually = v as i128;
+                                        if bits < 128 {
+                                            // v & 0b0..01..1, |1| = bits
+                                            let trimmed = v & ((1 << bits) - 1);
+                                            actually = if v & (1 << (bits - 1)) == 0 {
```
Comment (oli-obk) [inline src/librustc_lint/types.rs]: You can simplify these conversions by first casting to `i128` and then bitshifting by `128 - bits` to the left and then to the right.

File: src/librustc_lint/types.rs [hunk 2]
```diff
@@ -182,37 +223,77 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
                     ty::TyFloat(t) => {
                         let is_infinite = match lit.node {
-                            ast::LitKind::Float(v, _) |
-                            ast::LitKind::FloatUnsuffixed(v) => {
-                                match t {
-                                    ast::FloatTy::F32 => v.as_str().parse().map(f32::is_infinite),
-                                    ast::FloatTy::F64 => v.as_str().parse().map(f64::is_infinite),
-                                }
-                            }
+                            ast::LitKind::Float(v, _) | ast::LitKind::FloatUnsuffixed(v) => match t
```
Comment (oli-obk) [inline src/librustc_lint/types.rs]: unrelated formatting change

File: src/librustc_lint/types.rs [hunk 3]
```diff
@@ -182,37 +223,77 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+                                ast::FloatTy::F32 => v.as_str().parse().map(f32::is_infinite),
+                                ast::FloatTy::F64 => v.as_str().parse().map(f64::is_infinite),
+                            },
                             _ => bug!(),
                         };
                         if is_infinite == Ok(true) {
-                            cx.span_lint(OVERFLOWING_LITERALS,
-                                         e.span,
-                                         &format!("literal out of range for {:?}", t));
+                            cx.span_lint(
```
Comment (oli-obk) [inline src/librustc_lint/types.rs]: unrelated formatting change

File: src/librustc_lint/types.rs [hunk 4]
```diff
@@ -340,6 +421,69 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
                 _ => false,
             }
         }
+
+        fn get_bin_hex_repr(cx: &LateContext, lit: &ast::Lit) -> Option<String> {
+            if let Some(src) = cx.sess().codemap().span_to_snippet(lit.span).ok() {
```
Comment (oli-obk) [inline src/librustc_lint/types.rs]: you can rewrite this entire function with the `?` operator instead of `if let`

File: src/librustc_lint/types.rs [hunk 5]
```diff
@@ -182,37 +223,77 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+                                    },
+                                );
+                                if !sugg_ty.is_empty() {
+                                    err.help(&sugg_ty);
+                                }
+
+                                err.emit();
+                                return;
+                            }
+                            cx.span_lint(
```
Comment (oli-obk) [inline src/librustc_lint/types.rs]: It feels like there's a lot of duplication between the error reporting of signed and unsigned integers. Is it possible to merge them into a function?

**Review by oli-obk — CHANGES_REQUESTED** [review]
The final error message output looks good to me

File: src/librustc_lint/types.rs [hunk 6]
```diff
@@ -340,6 +421,69 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+            val: u128,
+            negative: bool,
+        ) -> Option<ty::TypeVariants<'a>> {
+            use syntax::ast::IntTy::*;
+            use syntax::ast::UintTy::*;
+            macro_rules! find_fit {
+                ($ty:expr, $val:expr, $negative:expr,
+                 $($type:ident => [$($utypes:expr),*] => [$($itypes:expr),*]),+) => {
+                    {
+                        let _neg = if negative { 1 } else { 0 };
```
Comment (mattico) [inline src/librustc_lint/types.rs]: nit: preceding underscores suppress dead code warnings, so I'd avoid them if that is not intended.

Also the PR has a succint description for what this function does, which you could copy into a comment.

Comment (flip1995) [reply src/librustc_lint/types.rs]: The underscore is intended: for finding a fitting unsigned type, we don't look at integer types so the expanded macro never uses `_neg` in this case. So the line 
```rust
if let &ty::TyUint(u) = t {
    return find_fit!(u, val, negative
...}
```
gives a warning. If there is a better way to do this, it would be nice to know :)

And yeah maybe I should have wrote a few more comments. Will do this, while implementing the other suggestions

File: src/librustc_lint/types.rs (hunk 5 above)
Comment (flip1995) [reply src/librustc_lint/types.rs]: I think changing the function get_fitting_type(), that it returns the suggestion string directly is the best approach here. 
An extra function for the `err.note()` part is hard, because we need the `actually` value as `i128` in the singed case and as `u128` in the unsigned case. Same problem with the Type.

File: src/librustc_lint/types.rs [hunk 7]
```diff
@@ -340,6 +394,67 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+        }
+
+        // This function finds the next fitting type and generates a suggestion string.
+        // It searches for fitting types in the following way (`X < Y`):
+        //  - `iX`: if literal fits in `uX` => `uX`, else => `iY`
+        //  - `-iX` => `iY`
+        //  - `uX` => `uY`
+        //
+        // No suggestion for: `isize`, `usize`.
+        fn get_type_suggestion<'a>(t: &ty::TypeVariants, val: u128, negative: bool) -> String {
```
Comment (estebank) [inline src/librustc_lint/types.rs]: Could `get_type_suggestion` return an `Option<String>` instead? That way you communicate intent that the empty `String` doesn't.

File: src/librustc_lint/types.rs [hunk 8]
```diff
@@ -340,6 +394,67 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+            use syntax::ast::UintTy::*;
+            macro_rules! find_fit {
+                ($ty:expr, $val:expr, $negative:expr,
+                 $($type:ident => [$($utypes:expr),*] => [$($itypes:expr),*]),+) => {
+                    {
+                        let _neg = if negative { 1 } else { 0 };
+                        match $ty {
+                            $($type => {
+                                $(if !negative && val <= uint_ty_range($utypes).1 {
+                                    return format!("Consider using `{:?}`", $utypes)
```
Comment (estebank) [inline src/librustc_lint/types.rs]: use leading lowercase here and below

"consider using `{:?}` instead"

File: src/librustc_lint/types.rs [hunk 9]
```diff
@@ -193,9 +220,36 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+                                     an `{:?}` and will become `{}{:?}`.",
+                                    repr_str, lit_val, t, actually, t
+                                ));
+                                let sugg_ty = get_type_suggestion(
+                                    &cx.tables.node_id_to_type(e.hir_id).sty,
+                                    lit_val,
+                                    false,
+                                );
+                                if !sugg_ty.is_empty() {
+                                    err.help(&sugg_ty);
```
Comment (estebank) [inline src/librustc_lint/types.rs]: It'd be nice if this were a `span_suggestion` instead if it is a numeric literal that sets the type, otherwise provide the help (ideally I would check the source of the type constraint and point at it, but it is not necessary to go down that rabbit hole in this PR):

```
warning: literal out of range for i8
  --> $DIR/type-overflow.rs:34:17
   |
34 |     let fail = -0b1111_1111i8;
   |                 ^^^^^^^^^^^^^ help: consider using `i16` instead: `-0b1111_1111i16`
   |
   = note: the literal `0b1111_1111i8` (decimal `255`) does not fit into an `i8` and will become `-1i8`
```

File: src/librustc_lint/types.rs [hunk 10]
```diff
@@ -193,9 +220,36 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
...
+                                let bits = uint_ty_bits(t, cx.sess().target.usize_ty);
+                                let actually = (lit_val << (128 - bits)) >> (128 - bits);
+                                let mut err = cx.struct_span_lint(
+                                    OVERFLOWING_LITERALS,
+                                    e.span,
+                                    &format!("literal out of range for {:?}", t),
+                                );
+                                err.note(&format!(
+                                    "the literal `{}` (decimal `{}`) does not fit into \
+                                     an `{:?}` and will become `{}{:?}`.",
```
Comment (estebank) [inline src/librustc_lint/types.rs]: remove trailing `.`

**Review by estebank — CHANGES_REQUESTED** [review]
Looks great!

Could you address @oli-obk's and my comments?

File: src/librustc_lint/types.rs (hunk 9 above)
Comment (flip1995) [reply src/librustc_lint/types.rs]: This looks better. I will add this, this evening.

File: src/test/ui/lint/type-overflow.stderr [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+   |
+   = note: the literal `0x8000_0000_0000_0000` (decimal `9223372036854775808`) does not fit into an `isize` and will become `-9223372036854775808isize`
+
+warning: literal out of range for i8
+  --> $DIR/type-overflow.rs:34:17
+   |
+34 |     let fail = -0b1111_1111i8; //~WARNING literal out of range for i8
+   |                 ^^^^^^^^^^^^^ help: consider using `i16` instead: `0b1111_1111i16`
+   |
+   = note: the literal `0b1111_1111i8` (decimal `255`) does not fit into an `i8` and will become `-1i8`
```
Comment (flip1995) [inline src/test/ui/lint/type-overflow.stderr]: The note says that the literal will become `-1i8` (which is technically correct), while `fail` will have the value `1i8` due to the negation. That is, because I ignore whether the literal is negated in the generation of the note.

I'm not sure if I should change this because it is correct for the given span.

Comment (estebank) [reply src/test/ui/lint/type-overflow.stderr]: I think that this is fine for now. Filed #48535 to follow up.

**Review by estebank — APPROVED** [review]

**Comment by estebank** [comment]
@bors r-

@flip1995 you'll have to rebase and fix the ui test output to replace the line numbers in he margins with `LL`

**Comment by flip1995** [comment]
Whoops. I failed hard on the rebase. Sorry... :(
Should I open a new PR for this?

**Comment by estebank** [comment]
If you can fix the rebase, just do a `git push --force`.

**Comment by flip1995** [comment]
Fixed it somehow. That should be good now.

**Comment by Manishearth** [comment]
```
[00:51:04] failures:
[00:51:04] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22
[00:51:04] 
[00:51:04] ---- [ui] ui/lint/type-overflow.rs stdout ----
[00:51:04] 	diff of stderr:
[00:51:04] 
[00:51:04] 54	LL |     let fail: isize = 0x8000_0000_0000_0000; //~WARNING literal out of range for isize
[00:51:04] 55	   |                       ^^^^^^^^^^^^^^^^^^^^^
[00:51:04] 56	   |
[00:51:04] -	   = note: the literal `0x8000_0000_0000_0000` (decimal `9223372036854775808`) does not fit into an `isize` and will become `-9223372036854775808isize`
[00:51:04] +	   = note: the literal `0x8000_0000_0000_0000` (decimal `9223372036854775808`) does not fit into an `isize` and will become `0isize`
[00:51:04] 58	
[00:51:04] 59	warning: literal out of range for i8
[00:51:04] 60	  --> $DIR/type-overflow.rs:34:17
[00:51:04] 
[00:51:04] 
[00:51:04] The actual stderr differed from the expected stderr.
[00:51:04] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/type-overflow.stderr
[00:51:04] To update references, run this command from build directory:
[00:51:04] /checkout/src/test/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui' 'lint/type-overflow.rs'
[00:51:04] 
[00:51:04] error: 1 errors occurred comparing output.
[00:51:04] status: exit code: 0
[00:51:04] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lint/type-overflow.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=wasm32-unknown-unknown" "-Zui-testing" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/type-overflow.stage2-wasm32-unknown-unknown.wasm" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/wasm32-unknown-unknown/native/rust-test-helpers" "-Clinker=cc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/type-overflow.stage2-wasm32-unknown-unknown.aux" "-A" "unused"
[00:51:04] stdout:
[00:51:04] ------------------------------------------
[00:51:04] 
[00:51:04] ------------------------------------------
[00:51:04] stderr:
[00:51:04] ------------------------------------------
[00:51:04] warning: literal out of range for i8
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:16:17
[00:51:04]    |
[00:51:04] LL |     let error = 255i8; //~WARNING literal out of range for i8
[00:51:04]    |                 ^^^^^
[00:51:04]    |
[00:51:04]    = note: #[warn(overflowing_literals)] on by default
[00:51:04] 
[00:51:04] warning: literal out of range for i8
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:21:16
[00:51:04]    |
[00:51:04] LL |     let fail = 0b1000_0001i8; //~WARNING literal out of range for i8
[00:51:04]    |                ^^^^^^^^^^^^^ help: consider using `u8` instead: `0b1000_0001u8`
[00:51:04]    |
[00:51:04]    = note: the literal `0b1000_0001i8` (decimal `129`) does not fit into an `i8` and will become `-127i8`
[00:51:04] 
[00:51:04] warning: literal out of range for i64
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:23:16
[00:51:04]    |
[00:51:04] LL |     let fail = 0x8000_0000_0000_0000i64; //~WARNING literal out of range for i64
[00:51:04]    |                ^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `u64` instead: `0x8000_0000_0000_0000u64`
[00:51:04]    |
[00:51:04]    = note: the literal `0x8000_0000_0000_0000i64` (decimal `9223372036854775808`) does not fit into an `i64` and will become `-9223372036854775808i64`
[00:51:04] 
[00:51:04] warning: literal out of range for u32
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:25:16
[00:51:04]    |
[00:51:04] LL |     let fail = 0x1_FFFF_FFFFu32; //~WARNING literal out of range for u32
[00:51:04]    |                ^^^^^^^^^^^^^^^^ help: consider using `u64` instead: `0x1_FFFF_FFFFu64`
[00:51:04]    |
[00:51:04]    = note: the literal `0x1_FFFF_FFFFu32` (decimal `8589934591`) does not fit into an `u32` and will become `4294967295u32`
[00:51:04] 
[00:51:04] warning: literal out of range for i128
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:27:22
[00:51:04]    |
[00:51:04] LL |     let fail: i128 = 0x8000_0000_0000_0000_0000_0000_0000_0000;
[00:51:04]    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:51:04]    |
[00:51:04]    = note: the literal `0x8000_0000_0000_0000_0000_0000_0000_0000` (decimal `170141183460469231731687303715884105728`) does not fit into an `i128` and will become `-170141183460469231731687303715884105728i128`
[00:51:04]    = help: consider using `u128` instead
[00:51:04] 
[00:51:04] warning: literal out of range for i32
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:30:16
[00:51:04]    |
[00:51:04] LL |     let fail = 0x8FFF_FFFF_FFFF_FFFE; //~WARNING literal out of range for i32
[00:51:04]    |                ^^^^^^^^^^^^^^^^^^^^^
[00:51:04]    |
[00:51:04]    = note: the literal `0x8FFF_FFFF_FFFF_FFFE` (decimal `10376293541461622782`) does not fit into an `i32` and will become `-2i32`
[00:51:04]    = help: consider using `i128` instead
[00:51:04] 
[00:51:04] warning: literal out of range for isize
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:32:23
[00:51:04]    |
[00:51:04] LL |     let fail: isize = 0x8000_0000_0000_0000; //~WARNING literal out of range for isize
[00:51:04]    |                       ^^^^^^^^^^^^^^^^^^^^^
[00:51:04]    |
[00:51:04]    = note: the literal `0x8000_0000_0000_0000` (decimal `9223372036854775808`) does not fit into an `isize` and will become `0isize`
[00:51:04] 
[00:51:04] warning: literal out of range for i8
[00:51:04]   --> /checkout/src/test/ui/lint/type-overflow.rs:34:17
[00:51:04]    |
[00:51:04] LL |     let fail = -0b1111_1111i8; //~WARNING literal out of range for i8
[00:51:04]    |                 ^^^^^^^^^^^^^ help: consider using `i16` instead: `0b1111_1111i16`
[00:51:04]    |
[00:51:04]    = note: the literal `0b1111_1111i8` (decimal `255`) does not fit into an `i8` and will become `-1i8`
[00:51:04] 
[00:51:04] 
[00:51:04] ------------------------------------------
[00:51:04] 
[00:51:04] thread '[ui] ui/lint/type-overflow.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2893:9
[00:51:04] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:51:04] 
[00:51:04] 
[00:51:04] failures:
[00:51:04]     [ui] ui/lint/type-overflow.rs
[00:51:04] 
[00:51:04] test result: FAILED. 1242 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out
[00:51:04] 
[00:51:04] 
[00:51:04] 
[00:51:04] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/wasm32-unknown-unknown/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-wasm32-unknown-unknown" "--mode" "ui" "--target" "wasm32-unknown-unknown" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--nodejs" "/node-v9.2.0-linux-x64/bin/node" "--linker" "cc" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/wasm32-unknown-unknown/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--llvm-version" "6.0.0\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:51:04] expected success, got: exit code: 101
[00:51:04] 
[00:51:04] 
[00:51:04] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --target wasm32-unknown-unknown src/test/ui src/test/run-pass src/test/compile-fail src/test/parse-fail src/test/mir-opt src/test/codegen-units src/libcore src/libstd_unicode/
[00:51:04] Build completed unsuccessfully in 0:47:59
```

@bors r- till tests pass

**Comment by estebank** [comment]
Completely missed this pitfall, @Manishearth.

@flip1995, don't test the i/u size cases, as they're platform dependent and are prone to work locally and in travis, but break in the full run on all targets.

**Comment by flip1995** [comment]
Should I rebase again?

**Review by oli-obk — COMMENTED** [review]
No need to rebase if Travis passes

File: src/librustc_lint/types.rs [hunk 12]
```diff
@@ -340,6 +394,67 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeLimits {
                 _ => false,
             }
         }
+
+        fn get_bin_hex_repr(cx: &LateContext, lit: &ast::Lit) -> Option<String> {
+            let src = cx.sess().codemap().span_to_snippet(lit.span).ok()?;
+            let firstch = src.chars().next()?;
+
+            if let Some(0) = char::to_digit(firstch, 10) {
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_lint/types.rs]: r=me after @oli-obk's comment is addressed. Sorry for the back and forth, @flip1995, I didn't catch this.

[the remark this answers is not in the document]
Comment (flip1995) [reply src/librustc_lint/types.rs]: Don't know why I made this so complicated. 

No problem. I'm happy for the great support on my first PR to the rust compiler! :)

**Review by oli-obk — APPROVED** [review]
