### PR TITLE
Pass the right HIR back from `get_fn_decl`

### LINKED ISSUE #109232: ICE: not enough bound vars
[log.zip](https://github.com/rust-lang/rust/files/10996151/log.zip)
### Code

```Rust
async fn ice(&self) {
    true
}
```

### Meta

`rustc --version --verbose`:
```
cd6c574af3886c41f34086d90df42c3da0144693 with debug assertions
```

### Error output

```
error[E0670]: `async fn` is not permitted in Rust 2015
 --> treereduce.out:1:1
  |
1 | async fn ice(&self) {
  | ^^^^^ to use `async fn`, switch to Rust 2018 or later
  |
  = help: pass `--edition 2021` to `rustc`
  = note: for more on editions, read https://doc.rust-lang.org/edition-guide

error: `self` parameter is only allowed in associated functions
 --> treereduce.out:1:14
  |
1 | async fn ice(&self) {
  |              ^^^^^ not semantically valid as function parameter
  |
  = note: associated functions are those in `impl` or `trait` definitions

error[E0601]: `main` function not found in crate `treereduce`
 --> treereduce.out:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `treereduce.out`

error[E0308]: mismatched types
 --> treereduce.out:2:5
  |
1 | async fn ice(&self) {
  |                     - help: try adding a return type: `-> bool`
2 |     true
  |     ^^^^ expected `()`, found `bool`

error: aborting due to 4 previous errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/visit.rs:340:21: Not enough bound vars: BoundRegion { var: 0, kind: BrNamed(DefId(0:5 ~ treereduce[ec07]::ice::'_), '_) } not found in []

thread 'rustc' panicked at 'Box<dyn Any>', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7fc8361656d4 - std::backtrace_rs::backtrace::libunwind::trace::h154b4ffb8ddaa4c5
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fc8361656d4 - std::backtrace_rs::backtrace::trace_unsynchronized::h80c3570785f36849
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc8361656d4 - std::sys_common::backtrace::_print_fmt::h4c724079b81989bf
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fc8361656d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb8e6266f21fedb2e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc8361e7298 - core::fmt::write::h2dac34aae88eac3a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1232:17
   5:     0x7fc83614adaf - std::io::Write::write_fmt::he4a6f86c0870d055
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1684:15
   6:     0x7fc8361654d5 - std::sys_common::backtrace::_print::hd9fa4da5fb35e3c2
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fc8361654d5 - std::sys_common::backtrace::print::h96adbffa1fffcf04
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fc8361389f4 - std::panicking::default_hook::{{closure}}::hb425055b1e88d07e
   9:     0x7fc836138661 - std::panicking::default_hook::h096318d450721a10
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:290:9
  10:     0x7fc838c4c595 - <alloc[df9d1ca7e15cbd48]::boxed::Box<dyn for<'a, 'b> core[56d2be079082b2f7]::ops::function::Fn<(&'a core[56d2be079082b2f7]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[56d2be079082b2f7]::marker::Send + core[56d2be079082b2f7]::marker::Sync> as core[56d2be079082b2f7]::ops::function::Fn<(&core[56d2be079082b2f7]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  11:     0x7fc838c4c595 - rustc_driver_impl[e099f41864aa826c]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1185:17
  12:     0x7fc83613934a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd5e684618c375fd7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  13:     0x7fc83613934a - std::panicking::rust_panic_with_hook::he6a6c9655719b7f7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:696:13
  14:     0x7fc839ccdd03 - std[a36a78ba7a755d70]::panicking::begin_panic::<rustc_errors[f6f1d49adb334bed]::ExplicitBug>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:612:9
  15:     0x7fc839cc1e36 - std[a36a78ba7a755d70]::sys_common::backtrace::__rust_end_short_backtrace::<std[a36a78ba7a755d70]::panicking::begin_panic<rustc_errors[f6f1d49adb334bed]::ExplicitBug>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x7fc839c385c6 - std[a36a78ba7a755d70]::panicking::begin_panic::<rustc_errors[f6f1d49adb334bed]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:611:12
  17:     0x7fc839d31376 - std[a36a78ba7a755d70]::panic::panic_any::<rustc_errors[f6f1d49adb334bed]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:61:5
  18:     0x7fc839d2ecea - <rustc_errors[f6f1d49adb334bed]::HandlerInner>::bug::<&alloc[df9d1ca7e15cbd48]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1644:9
  19:     0x7fc839d2e870 - <rustc_errors[f6f1d49adb334bed]::Handler>::bug::<&alloc[df9d1ca7e15cbd48]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1064:9
  20:     0x7fc839d711a7 - rustc_middle[8dd2ca4c4a36fdd]::util::bug::opt_span_bug_fmt::<rustc_span[bb67bf6d5ab84d80]::span_encoding::Span>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:35:34
  21:     0x7fc839d6f7e4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_opt::<rustc_middle[8dd2ca4c4a36fdd]::util::bug::opt_span_bug_fmt<rustc_span[bb67bf6d5ab84d80]::span_encoding::Span>::{closure#0}, !>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:185:36
  22:     0x7fc839d6f798 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context_opt::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_opt<rustc_middle[8dd2ca4c4a36fdd]::util::bug::opt_span_bug_fmt<rustc_span[bb67bf6d5ab84d80]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:131:18
  23:     0x7fc839d710e7 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_opt::<rustc_middle[8dd2ca4c4a36fdd]::util::bug::opt_span_bug_fmt<rustc_span[bb67bf6d5ab84d80]::span_encoding::Span>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:185:5
  24:     0x7fc839d710e7 - rustc_middle[8dd2ca4c4a36fdd]::util::bug::opt_span_bug_fmt::<rustc_span[bb67bf6d5ab84d80]::span_encoding::Span>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:31:5
  25:     0x7fc839d71063 - rustc_middle[8dd2ca4c4a36fdd]::util::bug::bug_fmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:15:5
  26:     0x7fc839d6f25c - <rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitor<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_region
  27:     0x7fc839cf942c - <rustc_middle[8dd2ca4c4a36fdd]::ty::sty::Region as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/structural_impls.rs:579:9
  28:     0x7fc839cf942c - <rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/subst.rs:246:45
  29:     0x7fc839cf942c - <&rustc_middle[8dd2ca4c4a36fdd]::ty::list::List<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/subst.rs:552:38
  30:     0x7fc839cf942c - core[56d2be079082b2f7]::iter::traits::iterator::Iterator::try_for_each::call::<&rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg, core[56d2be079082b2f7]::ops::control_flow::ControlFlow<()>, <&rustc_middle[8dd2ca4c4a36fdd]::ty::list::List<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:2358:26
  31:     0x7fc839cf942c - <core[56d2be079082b2f7]::slice::iter::Iter<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as core[56d2be079082b2f7]::iter::traits::iterator::Iterator>::try_fold::<(), core[56d2be079082b2f7]::iter::traits::iterator::Iterator::try_for_each::call<&rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg, core[56d2be079082b2f7]::ops::control_flow::ControlFlow<()>, <&rustc_middle[8dd2ca4c4a36fdd]::ty::list::List<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::ops::control_flow::ControlFlow<()>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:2299:21
  32:     0x7fc839cf942c - <core[56d2be079082b2f7]::slice::iter::Iter<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as core[56d2be079082b2f7]::iter::traits::iterator::Iterator>::try_for_each::<<&rustc_middle[8dd2ca4c4a36fdd]::ty::list::List<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>::{closure#0}, core[56d2be079082b2f7]::ops::control_flow::ControlFlow<()>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/traits/iterator.rs:2361:9
  33:     0x7fc839cf942c - <&rustc_middle[8dd2ca4c4a36fdd]::ty::list::List<rustc_middle[8dd2ca4c4a36fdd]::ty::subst::GenericArg> as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/subst.rs:552:21
  34:     0x7fc839cf942c - <rustc_middle[8dd2ca4c4a36fdd]::ty::sty::AliasTy as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/sty.rs:1244:36
  35:     0x7fc839d6eea7 - <rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitor<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_ty
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/visit.rs:333:9
  36:     0x7fc839345aa5 - <rustc_middle[8dd2ca4c4a36fdd]::ty::Ty as rustc_type_ir[86bbdcd4ef35acbf]::visit::TypeVisitable<rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>>::visit_with::<rustc_middle[8dd2ca4c4a36fdd]::ty::visit::ValidateBoundVars>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/structural_impls.rs:467:9
  37:     0x7fc839345aa5 - <rustc_middle[8dd2ca4c4a36fdd]::ty::sty::Binder<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty>>::bind_with_vars
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/sty.rs:1013:13
  38:     0x7fc8392776e9 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::suggest_missing_break_or_return_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:903:56
  39:     0x7fc83927051c - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::suggest_mismatched_types_on_tail
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:77:13
  40:     0x7fc839516edc - <rustc_hir_typeck[16eec824639b7883]::coercion::CoerceMany<&rustc_hir[5fda88f76d311920]::hir::Expr>>::report_return_mismatched_types
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/coercion.rs:1690:17
  41:     0x7fc8395216f2 - <rustc_hir_typeck[16eec824639b7883]::coercion::CoerceMany<&rustc_hir[5fda88f76d311920]::hir::Expr>>::coerce_inner
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/coercion.rs:1555:31
  42:     0x7fc83926d7e6 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1535:17
  43:     0x7fc83926d7e6 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1462:22
  44:     0x7fc83926d7e6 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1515:26
  45:     0x7fc8392bdd9d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:328:41
  46:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:235:18
  47:     0x7fc83924247d - stacker[a1b2ff0363358e05]::maybe_grow::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  48:     0x7fc83924247d - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  49:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:231:18
  50:     0x7fc8392bcd25 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:185:9
  51:     0x7fc8392bd58a - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:342:39
  52:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:235:18
  53:     0x7fc83924247d - stacker[a1b2ff0363358e05]::maybe_grow::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  54:     0x7fc83924247d - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  55:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:231:18
  56:     0x7fc8392bcd25 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:185:9
  57:     0x7fc83926d531 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1522:50
  58:     0x7fc83926d531 - <core[56d2be079082b2f7]::option::Option<&&rustc_hir[5fda88f76d311920]::hir::Expr>>::map::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1137:29
  59:     0x7fc83926d531 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1522:32
  60:     0x7fc83926d531 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1462:22
  61:     0x7fc83926d531 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_block_with_expected
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1515:26
  62:     0x7fc8392bdd9d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:328:41
  63:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:235:18
  64:     0x7fc83924247d - stacker[a1b2ff0363358e05]::maybe_grow::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  65:     0x7fc83924247d - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  66:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:231:18
  67:     0x7fc8392bcd25 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:185:9
  68:     0x7fc8392442b8 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_hint
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:137:9
  69:     0x7fc8392442b8 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_return_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:835:30
  70:     0x7fc83946f32a - rustc_hir_typeck[16eec824639b7883]::check::check_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/check.rs:122:9
  71:     0x7fc8392b4f03 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_closure::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/closure.rs:86:31
  72:     0x7fc8392b4f03 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_closure
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/closure.rs:75:19
  73:     0x7fc8392b4f03 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_closure
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/closure.rs:64:9
  74:     0x7fc8392bd53f - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:327:43
  75:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:235:18
  76:     0x7fc83924247d - stacker[a1b2ff0363358e05]::maybe_grow::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  77:     0x7fc83924247d - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<rustc_middle[8dd2ca4c4a36fdd]::ty::Ty, <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  78:     0x7fc83924247d - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:231:18
  79:     0x7fc8392bcd25 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:185:9
  80:     0x7fc8392442b8 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_expr_with_hint
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:137:9
  81:     0x7fc8392442b8 - <rustc_hir_typeck[16eec824639b7883]::fn_ctxt::FnCtxt>::check_return_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:835:30
  82:     0x7fc83946f32a - rustc_hir_typeck[16eec824639b7883]::check::check_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/check.rs:122:9
  83:     0x7fc839469ef4 - rustc_hir_typeck[16eec824639b7883]::typeck_with_fallback::<rustc_hir_typeck[16eec824639b7883]::typeck::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:231:9
  84:     0x7fc839469ef4 - rustc_hir_typeck[16eec824639b7883]::typeck_with_fallback::<rustc_hir_typeck[16eec824639b7883]::typeck::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:191:36
  85:     0x7fc839469ef4 - rustc_hir_typeck[16eec824639b7883]::typeck
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:172:9
  86:     0x7fc83a8d2065 - <rustc_query_impl[1bfa329cb631a952]::queries::typeck as rustc_query_system[ca658de1842f098f]::query::config::QueryConfig<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
  87:     0x7fc83a8d2065 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:71
  88:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::tlv::with_tlv::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:94:9
  89:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::enter_context::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:114:5
  90:     0x7fc83a8d2065 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
  91:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:164:9
  92:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:36
  93:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context_opt::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:131:18
  94:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:5
  95:     0x7fc83a8d2065 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:155:5
  96:     0x7fc83a8d2065 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:9
  97:     0x7fc83a8d2065 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:17
  98:     0x7fc83a8d2065 - rustc_query_system[ca658de1842f098f]::query::plumbing::try_execute_query::<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:382:44
  99:     0x7fc83ac0c255 - rustc_query_system[ca658de1842f098f]::query::plumbing::get_query::<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:814:36
 100:     0x7fc83ac0c255 - stacker[a1b2ff0363358e05]::maybe_grow::<(&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, core[56d2be079082b2f7]::option::Option<rustc_query_system[ca658de1842f098f]::dep_graph::graph::DepNodeIndex>), rustc_query_system[ca658de1842f098f]::query::plumbing::get_query<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 101:     0x7fc83ac0c255 - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<(&rustc_middle[8dd2ca4c4a36fdd]::ty::typeck_results::TypeckResults, core[56d2be079082b2f7]::option::Option<rustc_query_system[ca658de1842f098f]::dep_graph::graph::DepNodeIndex>), rustc_query_system[ca658de1842f098f]::query::plumbing::get_query<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
 102:     0x7fc83ac0c255 - rustc_query_system[ca658de1842f098f]::query::plumbing::get_query::<rustc_query_impl[1bfa329cb631a952]::queries::typeck, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:814:9
 103:     0x7fc83ac0c255 - <rustc_query_impl[1bfa329cb631a952]::Queries as rustc_middle[8dd2ca4c4a36fdd]::ty::query::QueryEngine>::typeck::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:805:17
 104:     0x7fc83ac0c255 - <rustc_query_impl[1bfa329cb631a952]::Queries as rustc_middle[8dd2ca4c4a36fdd]::ty::query::QueryEngine>::typeck
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:47:1
 105:     0x7fc839bc001f - <rustc_middle[8dd2ca4c4a36fdd]::ty::query::TyCtxtAt>::typeck::<rustc_span[bb67bf6d5ab84d80]::def_id::LocalDefId>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:380:29
 106:     0x7fc839bc001f - <rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>::typeck::<rustc_span[bb67bf6d5ab84d80]::def_id::LocalDefId>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:366:35
 107:     0x7fc839bc001f - <rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>::typeck_opt_const_arg
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:593:18
 108:     0x7fc839f16eda - <rustc_mir_build[58190bba202a1d36]::thir::cx::Cx>::new
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_mir_build/src/thir/cx/mod.rs:82:30
 109:     0x7fc839f16eda - rustc_mir_build[58190bba202a1d36]::thir::cx::thir_body
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_mir_build/src/thir/cx/mod.rs:27:18
 110:     0x7fc83a8f04f4 - <rustc_query_impl[1bfa329cb631a952]::queries::thir_body as rustc_query_system[ca658de1842f098f]::query::config::QueryConfig<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
 111:     0x7fc83a8f04f4 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:71
 112:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::tlv::with_tlv::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:94:9
 113:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::enter_context::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:114:5
 114:     0x7fc83a8f04f4 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
 115:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:164:9
 116:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:36
 117:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context_opt::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:131:18
 118:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:5
 119:     0x7fc83a8f04f4 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:155:5
 120:     0x7fc83a8f04f4 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:9
 121:     0x7fc83a8f04f4 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:17
 122:     0x7fc83a8f04f4 - rustc_query_system[ca658de1842f098f]::query::plumbing::try_execute_query::<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:382:44
 123:     0x7fc83abe0ded - rustc_query_system[ca658de1842f098f]::query::plumbing::get_query::<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:814:36
 124:     0x7fc83abe0ded - stacker[a1b2ff0363358e05]::maybe_grow::<(core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, core[56d2be079082b2f7]::option::Option<rustc_query_system[ca658de1842f098f]::dep_graph::graph::DepNodeIndex>), rustc_query_system[ca658de1842f098f]::query::plumbing::get_query<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 125:     0x7fc83abe0ded - rustc_data_structures[553a418dbf8a20c9]::stack::ensure_sufficient_stack::<(core[56d2be079082b2f7]::result::Result<(&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::thir::Thir>, rustc_middle[8dd2ca4c4a36fdd]::thir::ExprId), rustc_span[bb67bf6d5ab84d80]::ErrorGuaranteed>, core[56d2be079082b2f7]::option::Option<rustc_query_system[ca658de1842f098f]::dep_graph::graph::DepNodeIndex>), rustc_query_system[ca658de1842f098f]::query::plumbing::get_query<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
 126:     0x7fc83abe0ded - rustc_query_system[ca658de1842f098f]::query::plumbing::get_query::<rustc_query_impl[1bfa329cb631a952]::queries::thir_body, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:814:9
 127:     0x7fc83abe0ded - <rustc_query_impl[1bfa329cb631a952]::Queries as rustc_middle[8dd2ca4c4a36fdd]::ty::query::QueryEngine>::thir_body::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:805:17
 128:     0x7fc83abe0ded - <rustc_query_impl[1bfa329cb631a952]::Queries as rustc_middle[8dd2ca4c4a36fdd]::ty::query::QueryEngine>::thir_body
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:47:1
 129:     0x7fc839e764cc - <rustc_middle[8dd2ca4c4a36fdd]::ty::query::TyCtxtAt>::thir_body
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:380:29
 130:     0x7fc839e764cc - <rustc_middle[8dd2ca4c4a36fdd]::ty::context::TyCtxt>::thir_body
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:366:35
 131:     0x7fc839e764cc - rustc_mir_build[58190bba202a1d36]::build::mir_build
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_mir_build/src/build/mod.rs:62:26
 132:     0x7fc839e75a5a - rustc_mir_build[58190bba202a1d36]::build::mir_built
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_mir_build/src/build/mod.rs:39:20
 133:     0x7fc83a8ea441 - <rustc_query_impl[1bfa329cb631a952]::queries::mir_built as rustc_query_system[ca658de1842f098f]::query::config::QueryConfig<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
 134:     0x7fc83a8ea441 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:71
 135:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::tlv::with_tlv::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:94:9
 136:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::enter_context::<rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:114:5
 137:     0x7fc83a8ea441 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
 138:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:164:9
 139:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:36
 140:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context_opt::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:131:18
 141:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_context::<rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:142:5
 142:     0x7fc83a8ea441 - rustc_middle[8dd2ca4c4a36fdd]::ty::context::tls::with_related_context::<<rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:155:5
 143:     0x7fc83a8ea441 - <rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt as rustc_query_system[ca658de1842f098f]::query::QueryContext>::start_query::<&rustc_data_structures[553a418dbf8a20c9]::steal::Steal<rustc_middle[8dd2ca4c4a36fdd]::mir::Body>, rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:9
 144:     0x7fc83a8ea441 - rustc_query_system[ca658de1842f098f]::query::plumbing::execute_job::<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:440:17
 145:     0x7fc83a8ea441 - rustc_query_system[ca658de1842f098f]::query::plumbing::try_execute_query::<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:382:44
 146:     0x7fc83abe44a1 - rustc_query_system[ca658de1842f098f]::query::plumbing::get_query::<rustc_query_impl[1bfa329cb631a952]::queries::mir_built, rustc_query_impl[1bfa329cb631a952]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:814:36

 <snip>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `ice`
#1 [thir_body] building THIR for `ice`
#2 [mir_built] building MIR for `ice`
#3 [unsafety_check_result] unsafety-checking `ice`
#4 [mir_const] preparing `ice` for borrow checking
#5 [mir_promoted] processing MIR for `ice`
#6 [mir_borrowck] borrow-checking `ice`
#7 [type_of] computing type of `ice::{opaque#0}`
#8 [check_mod_item_types] checking item types in top-level module
#9 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0601, E0670.
For more information about an error, try `rustc --explain E0601`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #109232

Makes sure that the `fn_id: HirId` that we pass to `suggest_missing_return_type` matches up with the `fn_decl: hir::FnDecl` that we pass to it, so the late-bound vars that we fetch from the former match up with the types in the latter...

This HIR suggestion code really needs a big refactor. I've tried to do it in the past (a couple of attempts), but it's a super tangled mess. It really shouldn't be passing around things like `hir::Node` and just deal with `LocalDefId`s everywhere... Anyways, I'd rather fix this ICE, now.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 1]
```diff
@@ -902,47 +902,63 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                Some((&sig.decl, ident, ident.name != sym::main))
-            },
+                ident.name != sym::main,
+            )),
             _ => None,
         }
     }
 
     /// Given a `HirId`, return the `FnDecl` of the method it is enclosed by and whether a
     /// suggestion can be made, `None` otherwise.
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:951]: Can you update the docs, so they actually say what the function returns?

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 2]
```diff
@@ -902,47 +902,63 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     pub(in super::super) fn get_node_fn_decl(
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:902]: Same here: what this function returns?...

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 3]
```diff
@@ -902,47 +902,63 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-            Node::Expr(&hir::Expr {
-                hir_id,
-                kind: hir::ExprKind::Closure(..),
-                ..
-            }) if let Some(Node::Item(&hir::Item {
+            }) => Some((hir::HirId::make_owner(owner_id.def_id), &sig.decl, ident, false)),
+            Node::Expr(&hir::Expr { hir_id, kind: hir::ExprKind::Closure(..), .. })
+                if let Some(Node::Item(&hir::Item {
+                    ident,
+                    kind: hir::ItemKind::Fn(ref sig, ..),owner_id,
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:938]: rustfmt: 💀 💀 💀 
```suggestion
                    kind: hir::ItemKind::Fn(ref sig, ..),
                    owner_id,
```

**Review by WaffleLapkin — COMMENTED** [review]
r=me after minor nitpicks fixed
