### PR TITLE
Fix deprecated attribute intra-doc link not resolved in the right location on reexported item

### LINKED ISSUE #151028: ICE on nightly building futures-util
I encountered an internal compiler error when building `future-utils` on rust nightly (01/11).

### Reproduction

```
rustup toolchain install nightly

git clone https://github.com/rust-lang/futures-rs.git
cd futures-rs

cargo +nightly doc
```

### Meta

Rust version:
```
>  rustup +nightly show -v
...

nightly-x86_64-unknown-linux-gnu (active)
  rustc 1.94.0-nightly (b68e16cfc 2026-01-11)

...
```

### Error output and Backtrace

```
> RUST_BACKTRACE=1 cargo +nightly doc
...

error: internal compiler error: src/librustdoc/passes/collect_intra_doc_links.rs:419:17: no resolution for "Flatten" MacroNS DefId(0:117 ~ futures_util[2b92]::future::future)
   --> futures-util/src/lib.rs:270:9
    |
270 | /         pin_project_lite::pin_project! {
271 | |             #[must_use = "futures/streams/sinks do nothing unless you `.await` or poll them"]
272 | |             $(#[$attr])*
273 | |             pub struct $name< $($arg),* > $(where $($bound)*)* { #[pin] inner: $t }
274 | |         }
    | |_________^
    |
   ::: futures-util/src/future/future/mod.rs:37:1
    |
 37 | / delegate_all!(
 38 | |     /// Stream for the [`flatten_stream`](FutureExt::flatten_stream) method.
 39 | |     FlattenStream<F>(
 40 | |         flatten::Flatten<F, <F as Future>::Output>
 41 | |     ): Debug + Sink + Stream + FusedStream + New[|x: F| flatten::Flatten::new(x)]
 42 | |     where F: Future
 43 | | );
    | |_- in this macro invocation
    |
    = note: this error: internal compiler error originates in the macro `$crate::__pin_project_reconstruct` which comes from the expansion of the macro `delegate_all` (in Nightly builds, run with -Z macro-backtrace for more info)


thread 'rustc' (378876) panicked at src/librustdoc/passes/collect_intra_doc_links.rs:419:17:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: <rustc_errors::DiagCtxtHandle>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_path
   8: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
   9: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_link
  10: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_links::{closure#0}
  11: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  13: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  14: rustdoc::core::run_global_ctxt
  15: rustdoc::main_args::{closure#2}::{closure#0}
  16: rustc_interface::interface::run_compiler::<(), rustdoc::main_args::{closure#2}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Suspected culprit

We believe that it is caused by one of [these commits](https://github.com/rust-lang/rust/commit/3fda0e426ca17b0baa0d6e765a0d23f487350573). Possibly [deprecated-doc-intra-link](https://github.com/rust-lang/rust/commit/d763ffaf04ef97d2a7ef254fafc01d07ea5b6605#diff-53e2bb31a1a4804925f22caf5a4844d0b6ffc9f7f307d93ef6098d62381a5085).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/151028.
Follow-up of https://github.com/rust-lang/rust/pull/150721.

So when we resolve an intra-doc link, its current context (the module from which we resolve in short) is very important. However, when we use an intra-doc link in a `#[deprecated]` attribute on a reexported item, we were using the context of the reexported item and not of the `use` itself. Meaning that if you have an intra-doc link `std::mem::drop` on an item from another crate (let's say `core`), then the import will simply fail since there is no `std` dependency.

Now comes the not so funny fix: at this point, we don't know anymore where the attribute came from (ie, from the reexport or from the reexported item) since we already merged the attribute at this point. The solution I found to go around this problem is to check if the item span contains the attribute, and if not, then we use the `inline_stmt_id` as context instead of the item's ID. I'm not super happy and I'm sure we'll find corner cases in the future (like with macros), however there are a few things that mitigate this fix:
1. The only way to generate an attribute with a macro with its item while having different spans is by using proc-macros. In that case, we can always default to the `inline_stmt_id` as context and be fine, but I guess we'll see when get there.
2. It only concerns reexports, so the area of the problem is quite restricted.

Hopefully this explanation made sense. :)

cc @folkertdev 
r? @lolbinarycat

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -1084,15 +1084,29 @@ impl LinkCollector<'_, '_> {
...
             debug!("deprecated_note={note}");
-            insert_links(item.item_id.expect_def_id(), note)
+            let item_id = if let Some(inline_stmt_id) = item.inline_stmt_id
+                && !item.span(tcx).is_none_or(|item_span| item_span.inner().contains(*span))
+            {
+                inline_stmt_id.to_def_id()
+            } else {
+                item.item_id.expect_def_id()
+            };
+            insert_links(item_id, note)
```
Comment (lolbinarycat) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1113]:
```suggestion
            // when resolving an intra-doc link inside a deprecation note
            // that is on an inlined `use` statement, we need to use the `def_id` of
            // the `use` statement, not the inlined item.
            // <https://github.com/rust-lang/rust/pull/151120>
            let item_id = if let Some(inline_stmt_id) = item.inline_stmt_id
                && item.span(tcx).is_some_and(|item_span| !item_span.inner().contains(*span))
            {
                inline_stmt_id.to_def_id()
            } else {
                item.item_id.expect_def_id()
            };
            insert_links(item_id, note)
```

1. I think moving the negation inwards makes the condition easier to reason about
2. This is a weird edge case so I think it's good to give a comment.  yes git blame exists but if a refactor happens between now and when this needs to be re-investigated, it might not be very helpful (it doesn't have to be this exact comment, feel free to write your own if you think you can do better, i left out the macro hazard for brevity).

**Review by lolbinarycat — COMMENTED** [review]
Two small potential improvements, otherwise the code looks good!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151120/8c52f735abd1af9a73941b78fe7ed2ab08b9c0dd..46ded94c54ed7abca310d2229fa8211b67c3690c)*

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1113]: Agreed for the comment, however if the span is `None`, or doesn't contain the attribute, then we should use the `use` span, which means my original condition was wrong too, the `!` should have been for the `contains`, not the whole thing. ^^'

**Comment by GuillaumeGomez** [comment]
Added comment and fixed condition.

**Comment by lolbinarycat** [comment]
The new condition has a different behavior than the old one, and from the equivalent one I suggested.  was this intentional? why?

**Comment by GuillaumeGomez** [comment]
yes it's intentional, explained it in [my comment](https://github.com/rust-lang/rust/pull/151120#discussion_r2692019479). ;)

**Comment by GuillaumeGomez** [comment]
This will not make the review go any faster. ^^'

**Comment by gulfemsavrun** [comment]
> This will not make the review go any faster. ^^'

What is the alternative in this case? The established revert policy (https://forge.rust-lang.org/compiler/reviews.html?highlight=revert#reverts) suggests that regressions should be addressed promptly. Given that we have already confirmed the landed code introduced a regression, why can't we follow that policy and revert while the fix undergoes a more lengthy review?

**Comment by apiraino** [comment]
> What is the alternative in this case?

@gulfemsavrun  The alternative is to let our team do their job. The regression *is* being addressed promptly (reported 3 days ago) and the fix is being reviewed. The regression is on our nightly release channel, unstable by definition.

I am not familiar with your toolchain builders, one option could be to [pin the latest working nightly](https://forge.rust-lang.org/docs-rs/maintenance.html#pinning-a-version-of-nightly) in the meantime.
