### PR TITLE
Tweak "incompatible match arms" error

### LINKED ISSUE #46776: Somewhat unclear error message when match arms evaluate to different types
Hi, I just found a minor annoyance in the compiler diagnostics.

Here's the code:
```rust
for key in 0..0x10 {
    match Keyboard::assoc_key(key) {
        Some(x) => keyboard.data.insert(x, false),
        _ => {},
    };
}
```
keyboard.data is a HashMap inside a struct, defined as:
```rust 
data: HashMap<Keys, bool>
```
Keyboard::assoc_key is defined as:
```rust
fn assoc_key(n: u8) -> Option<Keys>
```
`Keys` is just a simple enum type.

The problem with the code above is that `HashMap::insert` returns an `Option` and so the match tries to evaluate to that type which is, however, not needed in this case. But it means that the default arm must also evaluate to an `Option` which it doesn't.
The compiler obviously complains about this:
```
error[E0308]: match arms have incompatible types
  --> src/keyboard.rs:21:13
   |
21 | /             match Keyboard::assoc_key(key) {
22 | |                 Some(x) => keyboard.data.insert(x, false),
23 | |                 _ => {},
24 | |             };
   | |_____________^ expected enum `std::option::Option`, found ()
   |
   = note: expected type `std::option::Option<bool>`
              found type `()`
note: match arm with an incompatible type
  --> src/keyboard.rs:23:22
   |
23 |                 _ => {},
   |                      ^^

error: aborting due to previous error
```
This confused me for a while because that was the first time I used a `HashMap` and I didn't have in mind that `HashMap::insert` returns something.
I think the compiler should specifically mention **why** it expects an `Option`, that is, from where it inferred the type which would have made it more obvious that `HashMap::insert` returns an `Option`.
I suppose this is something that typically doesn't happen to someone who is familiar enough with the language but it's confusing for someone who only recently began learning Rust.

I've looked for existing similar issues but found nothing obvious. If this has already been discussed somewhere or is not considered an issue, please close this :)

### LINKED ISSUE #57206: Type inference failure leads to incorrect "match arm with an incompatible type" message
In the code sample below, there are two ultimately identical functions with the same problem, but while the compiler correctly reports the incorrect match block in the first function (`test_func1()`), it fails to do so in the second (`test_func2()`):

```rust
fn main() {
    let _ = test_func1(1);
    let _ = test_func2(1);
}

fn test_func1(n: i32) -> i32 {
    match n {
        12 => 'b',
        _ => 42,
    }
}

fn test_func2(n: i32) -> i32 {
    let x = match n {
        12 => 'b',
        _ => 42,
    };

    x
}
```

which produces the following correct error for the first function:

```
error[E0308]: match arms have incompatible types
  --> ./test.rs:7:5
   |
7  | /     match n {
8  | |         12 => 'b',
   | |               --- match arm with an incompatible type
9  | |         _ => 42,
10 | |     }
   | |_____^ expected i32, found char
```

but an incorrect error for the second message: 

```
error[E0308]: match arms have incompatible types
  --> ./test.rs:14:13
   |
14 |       let x = match n {
   |  _____________^
15 | |         12 => 'b',
16 | |         _ => 42,
   | |              -- match arm with an incompatible type
17 | |     };
   | |_____^ expected char, found integral variable
   |
   = note: expected type `char`
              found type `{integer}`
```

When `test_func2()` is extended with an explicit type hint (that should not be necessary as it can be derived from the existing code), the resulting error message is correct once again:

```rust
fn test_func3(n: i32) -> i32 {
    let x: i32 = match n {
        12 => 'b',
        _ => 42,
    };

    x
}
```

producing

```
error[E0308]: match arms have incompatible types
  --> ./test.rs:23:18
   |
23 |       let x: i32 = match n {
   |  __________________^
24 | |         12 => 'b',
   | |               --- match arm with an incompatible type
25 | |         _ => 42,
26 | |     };
   | |_____^ expected i32, found char
```

### PR DESCRIPTION
**Pull request by estebank**
- Point at the body expression of the match arm with the type error.
- Point at the prior match arms explicitly stating the evaluated type.
- Point at the entire match expr in a secondary span, instead of primary.
- For type errors in the first match arm, the cause is outside of the
  match, treat as implicit block error to give a more appropriate error.

Fix #46776, fix #57206.
CC #24157, #38234.

### CODE REVIEW

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -709,17 +710,31 @@ https://doc.rust-lang.org/reference/types.html#trait-objects");
...
-                });
+                let cause = if i == 0 {
+                    // The reason for the first arm to fail is not that the match arms diverge,
+                    // but rather that there's a prior obligation that doesn't hold.
+                    self.cause(arm_span, ObligationCauseCode::BlockTailExpression(arm.body.id))
+                } else {
+                    self.cause(expr.span, ObligationCauseCode::MatchExpressionArm {
+                        arm_span,
+                        source: match_src,
+                        prior_arms: other_arms.clone(),
```
Comment (matthewjasper) [inline src/librustc_typeck/check/_match.rs]: Since we're not using anything other than the last element when we have more than 3 arms, can we avoid cloning and storing the entire `Vec` for all of the arms after the 4th arm?

**Review by matthewjasper — CHANGES_REQUESTED** [review]
