### PR TITLE
resolve: Suggest `use self` when import resolves

### LINKED ISSUE #34191: Suggest `use self::Thing::OtherThing` when using `use Thing::OtherThing`
This frequently happens for code like this:
```rust
mod m {
    enum MyEnum {
        MyVariant
    }
    
    // Import all variants:
    use MyEnum::*;
}

fn main() {}
```

Since this *will* compile when putting `m`s contents into the main module, this can be quite confusing (for example when refactoring some code into it's own module).

Currently, this yields ``error: unresolved import `MyEnum::*`. Maybe a missing `extern crate MyEnum`?``. When this case is detected, the ``Maybe a missing `extern crate MyEnum`?`` probably shouldn't be printed.

### PR DESCRIPTION
**Pull request by euclio**
Improves errors messages by replacing "Maybe a missing `extern crate`" messages
with "Did you mean `self::...`" when the `self` import would succeed.

Fixes #34191.

Thank you for the help @jseyfried!

### CODE REVIEW

File: src/librustc_resolve/resolve_imports.rs [hunk 1]
```diff
@@ -587,7 +587,21 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+                    &self_module, &module_path, 0, Some(span));
+
+                return match resolve_from_self_result {
+                    Success(_) => {
+                        let msg = format!("Did you mean `self::{}`?",
+                                          &names_to_string(module_path));
+                        Failed(Some((span, msg)))
+                    },
+                    _ => Failed(err),
+                };
```
Comment (jseyfried) [inline src/librustc_resolve/resolve_imports.rs]: optional nit: I think this `match` would look better as an `if let` (i.e. `if let Success(_) = self_result { ... }`).

File: src/librustc_resolve/resolve_imports.rs [hunk 2]
```diff
@@ -587,7 +587,21 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
         let module = match module_result {
             Success(module) => module,
             Indeterminate => return Indeterminate,
-            Failed(err) => return Failed(err),
+            Failed(err) => {
+                let self_module = self.current_module.clone();
```
Comment (jseyfried) [inline src/librustc_resolve/resolve_imports.rs]: This could just be `let self_module = self.current_module`.

However, https://github.com/rust-lang/rust/issues/34191#issuecomment-241935757 isn't entirely correct (sorry). If we are in a block that has items in it, `self.current_module` is the anonymous module associated with the block, but `self` is the "normal" (`mod`) module that contains the block.

To get the `self` module, you can use `self.module_map[&self.current_module.normal_ancestor_id.unwrap()]`
(c.f. `fn resolve_module_prefix` in `librustc_resolve/lib.rs`).

**Comment by jseyfried** [comment]
@euclio Thanks for the PR!
Looks good to me modulo the comment about `self.current_module`.
