### PR TITLE
Liveness analysis for everybody

### LINKED ISSUE #77169: Unused variables lint does not work inside an array length expression
Array length expressions can can do anything that a `const` initializer can. However, the unused variables lint does not work inside an array length expression. For example,

```rust
fn main() {
    let _ = [(); {
        let x = 42;
        35
    }];
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d049315166724f100c266cdfda761e89))

...compiles with no warnings:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
     Running `target/debug/playground`

```

### PR DESCRIPTION
**Pull request by tmiasko**
Perform liveness analysis for every body instead of limiting it to fns.

Fixes #77169.

### CODE REVIEW

File: src/test/ui/consts/control-flow/drop-pass.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 // `x` is always moved into the final value and is not dropped inside the initializer.
 const _: Option<Vec<i32>> = {
-    let y: Option<Vec<i32>> = None;
+    let y: Option<Vec<i32>> = None; //~ WARN unused variable: `y`
```
Comment (lcnr) [inline src/test/ui/consts/control-flow/drop-pass.rs:8]: I think it's better to instead add `#![allow(unused)]` to these tests?

**Review by lcnr — APPROVED** [review]
LGTM!

I don't have too much experience with this code though, so I won't r+ this myself yet

**Comment by oli-obk** [comment]
@bors try @rust-timer queue

I don't care whether this has a perf impact, but I'd like to know before merging so we make a concious decision about it

File: compiler/rustc_passes/src/liveness.rs [hunk 2]
```diff
@@ -318,49 +318,39 @@ impl<'tcx> Visitor<'tcx> for IrMaps<'tcx> {
...
-        if let FnKind::Method(..) = fk {
-            let parent = self.tcx.hir().get_parent_item(id);
+        if let Node::ImplItem(..) = self.tcx.hir().get(hir_id) {
+            let parent = self.tcx.hir().get_parent_item(hir_id);
             if let Some(Node::Item(i)) = self.tcx.hir().find(parent) {
                 if i.attrs.iter().any(|a| self.tcx.sess.check_name(a, sym::automatically_derived)) {
                     return;
                 }
             }
         }
```
Comment (oli-obk) [inline compiler/rustc_passes/src/liveness.rs]: Not sure if the parent relation in the `DefId` space is set up like this, but can you try whether 

```rust
if let Some(parent) = self.tcx.parent(def_id) {
    if self.tcx.has_attr(parent, sym::automatically_derived) {
        return;
    }
}
```

also works? If so, please use that

Comment (tmiasko) [reply compiler/rustc_passes/src/liveness.rs]: Yep, that works as well.

Part of the motivation for the current form of the check was to avoid using the `automatically_derived` attribute if it were to occur in completely unexpected place, like a crate or a module. Should I change it anyway?

Comment (oli-obk) [reply compiler/rustc_passes/src/liveness.rs]: I think we should prevent such uses via other means, but you can also add an `assert_eq!(self.tcx.def_kind(parent), DefKind::Impl)` before the return to make sure.

Comment (tmiasko) [reply compiler/rustc_passes/src/liveness.rs]: We do not prevent such uses this right now, so I used this as a part of condition. I would like to be extra conservative about any additional uses of this attribute since I think it is stabilized unintentionally and its purpose has changed over time.

**Comment by tmiasko** [comment]
The performance impact is limited, except for the many-assoc-items benchmark which contains mostly associated consts. 

To a large degree we were paying the price of the computation already. The previous code was creating variables and lives nodes for all bodies, it just didn't always run the liveness analysis. Furthermore, when the liveness analysis didn't run, the live nodes and variables were included in the analysis of a parent if any.

File: compiler/rustc_passes/src/liveness.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_passes/src/liveness.rs]: oh :/ that's not great. Yea let's go with a non-panicking version for now

**Comment by oli-obk** [comment]
@bors r+

I was expecting *some* sort of perf hit on assoc const heavy code, but this is a bugfix, so let's roll with it
