### PR TITLE
Detect `fn` with a body in an `extern` block

### LINKED ISSUE #62109: Confusing error message when trying to implement a function in an extern block
A programmer new to Rust (yours truly, for example) may assume that these two syntaxes are equivalent:
```rust
extern "C" {
    fn foo() -> i32 {
        return 0;
    }
}

extern "C" fn foo() -> i32 {
    return 0;
}
```

This is not the case, of course—the first is a syntax error. However, the compiler points this out [rather unhelpfully](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=087bebda2511bc2ed0c80fa5c6787600): 
```
error: expected one of `!`, `(`, `+`, `::`, `;`, `<`, or `where`, found `{`
 --> src/lib.rs:2:21
  |
2 |     fn foo() -> i32 {
  |                     ^ expected one of 7 possible tokens here
```

A message such as "If you're trying to declare a function callable from other languages, use `extern "C" fn foo()` (wording is bikesheddable, obviously) would have saved me a lot of hair-tearing.

### PR DESCRIPTION
**Pull request by estebank**
Fix #62109.

### CODE REVIEW

File: src/libsyntax/parse/diagnostics.rs [hunk 1]
```diff
@@ -783,6 +784,38 @@ impl<'a> Parser<'a> {
...
+            let parser_snapshot = self.clone();
+            match self.parse_inner_attrs_and_block() {
+                Ok((_, body)) => {
+                    self.struct_span_err(ident.span, "incorrect `fn` inside `extern` block")
+                        .span_label(ident.span, "can't have a body")
+                        .span_label(body.span, "this body is invalid here")
+                        .span_label(
+                            extern_sp,
+                            "`extern` blocks define existing foreign functions and `fn`s \
+                             inside of them can't have a body")
```
Comment (Centril) [inline src/libsyntax/parse/diagnostics.rs]: Can't - - > cannot

**Comment by petrochenkov** [comment]
This should be a semantic error eventuall (https://github.com/rust-lang/rust/issues/48137).

@bors r+
