### PR TITLE
Fix linker error by resolving regions for main return type obligations

### LINKED ISSUE #148421: `main()` returning a type that implements `Termination` with an unsatisfied lifetime bound gives a linker error
I tried this code:

```rust
use std::process::ExitCode;
use std::process::Termination;

trait IsStatic {}
impl<'a: 'static> IsStatic for &'a () {}

struct Thing;
impl Termination for Thing where for<'a> &'a (): IsStatic {
    fn report(self) -> ExitCode { panic!() }
}

fn main() -> Thing { Thing }
```

I expected a normal compiler error. Instead, I got the following:

```
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" ....... <arguments omitted for brevity of this issue>
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: undefined hidden symbol: std::rt::lang_start::h005004333204f9e0
          >>> referenced by playground.b3525d8026055c0f-cgu.0
          >>>               /playground/target/debug/deps/playground-65a1e30147052435.playground.b3525d8026055c0f-cgu.0.rcgu.o:(main)
          collect2: error: ld returned 1 exit status
```

### Meta

Reproducible on the playground with version `1.93.0-nightly (2025-11-01 bd3ac0330018c23b111b)`

### PR DESCRIPTION
**Pull request by xonx4l**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/151377)*

This PR fix linker error by resolving regions for main return type obligations as discussed in https://github.com/rust-lang/rust/issues/148421

Added a final check . Now the compiler double-checks the lifetimes for main right away. If they don't work it stops and gives the user a clean compiler error instead of a linker crash.

Fixes https://github.com/rust-lang/rust/issues/148421.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/entry.rs [hunk 1]
```diff
@@ -143,6 +144,19 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
...
             error = true;
         }
+        let errors = ocx.evaluate_obligations_error_on_ambiguity();
+        if !errors.is_empty() {
+            infcx.err_ctxt().report_fulfillment_errors(errors);
+            error = true;
+        }
+
+        let region_errors =
+            infcx.resolve_regions(main_diagnostics_def_id, param_env, tcx.mk_type_list(&[]));
```
Comment (xonx4l) [inline compiler/rustc_hir_analysis/src/check/entry.rs]: One thing I'm slightly unsure about is the diagnostic span `main_diagnostics_def_id` as this points to the function as a whole.

File: compiler/rustc_hir_analysis/src/check/entry.rs [hunk 2]
```diff
@@ -143,6 +144,19 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
             infcx.err_ctxt().report_fulfillment_errors(errors);
             error = true;
         }
+        let errors = ocx.evaluate_obligations_error_on_ambiguity();
+        if !errors.is_empty() {
+            infcx.err_ctxt().report_fulfillment_errors(errors);
+            error = true;
+        }
```
Comment (fee1-dead) [inline compiler/rustc_hir_analysis/src/check/entry.rs:138]: ?

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_analysis/src/check/entry.rs (hunk 2 above)
Comment (xonx4l) [reply compiler/rustc_hir_analysis/src/check/entry.rs:138]: This is one of the consequence of me not using git revert so my bad . Removed the duplicated content . Thanks

File: compiler/rustc_hir_analysis/src/check/entry.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/entry.rs]: This `DefId` is the context in which we're emitting the errors, so it should be the `DefId` of the whole body. This is correct. Please use `ty::List::empty()` instead of `mk_type_list`

Also, can you change this function to return `Result<(), ErrorGuaranteed>` and instead of using `error = true` just return `Err(guar)`.

We shouldn't emit region errors if there are fulfillment errors

Comment (xonx4l) [reply compiler/rustc_hir_analysis/src/check/entry.rs]: @lcnr sorry I was a bit busy . I have made the the changes you asked for . Thanks!

File: compiler/rustc_hir_analysis/src/check/entry.rs [hunk 3]
```diff
@@ -113,7 +114,7 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
     }
 
     if error {
-        return;
+        return Ok(());
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/entry.rs]: ?

we should return `Err(ErrorGuaranteed)` here

File: compiler/rustc_hir_analysis/src/check/entry.rs [hunk 4]
```diff
@@ -171,23 +176,25 @@ fn check_main_fn_ty(tcx: TyCtxt<'_>, main_def_id: DefId) {
     )
     .is_err()
     {
-        return;
+        return Ok(());
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/entry.rs]: and here

File: compiler/rustc_hir_analysis/src/check/entry.rs (hunk 3 above)
Comment (xonx4l) [reply compiler/rustc_hir_analysis/src/check/entry.rs]: I am sorry I got a bit busy and it just slipped out of my focus . Updated to enforce Err(ErrorGuaranteed). Thanks !

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 5]
```diff
@@ -2370,7 +2350,8 @@ pub(super) fn check_type_wf(tcx: TyCtxt<'_>, (): ()) -> Result<(), ErrorGuarante
             }))
             .and(items.par_nested_bodies(|item| tcx.ensure_result().check_well_formed(item)))
             .and(items.par_opaques(|item| tcx.ensure_result().check_well_formed(item)));
-    super::entry::check_for_entry_fn(tcx);
+
+    super::entry::check_for_entry_fn(tcx)?;
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:2354]: why not part of the `and` 🤔

File: tests/ui/typeck/main-termination-lifetime-issue-148421.rs [hunk 6]
```diff
@@ -0,0 +1,15 @@
+// check-fail
```
Comment (lcnr) [inline tests/ui/typeck/main-termination-lifetime-issue-148421.rs]: `check-fail` isn't necessary.

Can you add a comment for what this is testing (and link to the issue in the file (and not necessarily in the test name))

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 5 above)
Comment (xonx4l) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:2354]: I kept it separate to make sure error is propagated.

File: tests/ui/typeck/main-termination-lifetime-issue-148421.rs (hunk 6 above)
Comment (xonx4l) [reply tests/ui/typeck/main-termination-lifetime-issue-148421.rs]: Okay will add.
