### PR TITLE
interpret: dyn trait metadata check: equate traits in a proper way

### LINKED ISSUE #3541: "constructing invalid value: wrong trait in wide pointer vtable" for seemingly identical traits
I don't have a minimal reduction atm, but the issue can be reproduced by cloning <https://github.com/Jules-Bertholet/unsized-vec> and running `cargo miri test -p emplacable`. This results in the following report of UB:

```
constructing invalid value: wrong trait in wide pointer vtable: expected `for<'b> std::ops::FnMut(std::alloc::Layout, <[std::boxed::Box<i32>] as std::ptr::Pointee>::Metadata, &'b mut (dyn std::ops::FnMut(*mut std::marker::PhantomData<[std::boxed::Box<i32>]>) + 'b))`, but encountered `for<'a> std::ops::FnMut<(std::alloc::Layout, usize, &'a mut (dyn std::ops::FnMut(*mut std::marker::PhantomData<[std::boxed::Box<i32>]>) + 'a))>`
```

But the two traits are the same! `<[std::boxed::Box<i32>] as std::ptr::Pointee>::Metadata` is `usize`, and `for<'a> ...` vs `for<'b> ...` should not make a difference either.

@rustbot label I-false-UB A-validation

### PR DESCRIPTION
**Pull request by RalfJung**
Hopefully fixes https://github.com/rust-lang/miri/issues/3541... unfortunately we don't have a testcase.

The first commit is just a refactor without functional change.

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/traits.rs [hunk 1]
```diff
@@ -57,4 +60,82 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
+            let infcx = self.tcx.infer_ctxt().build();
+            let ocx = ObligationCtxt::new(&infcx);
+            let cause = ObligationCause::dummy_with_span(self.cur_span());
+            // equate the two trait refs
+            if ocx.eq(&cause, self.param_env, expected_trait, vtable_trait).is_ok() {
+                if ocx.select_all_or_error().is_empty() {
+                    // All good.
+                    return Ok(());
+                }
+            }
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/traits.rs:88]: @lcnr I hope this is the right way to do the trait equality check.

Comment (lcnr) [reply compiler/rustc_const_eval/src/interpret/traits.rs:88]: yes, that looks good to me :+1:

**Comment by RalfJung** [comment]
@lcnr turns out that using the trait system here is not sufficient, the test still fails with this PR...

**Comment by RalfJung** [comment]
Ah never mind, I missed one place where we are using `!=`.

File: compiler/rustc_const_eval/src/interpret/traits.rs [hunk 2]
```diff
@@ -33,28 +36,88 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
+            return Ok(());
+        }
+        if let (Some(expected_trait), Some(vtable_trait)) =
+            (expected_trait.principal(), vtable_trait)
+        {
+            // Slow path: spin up an inference context to check if these traits are sufficiently equal.
+            let infcx = self.tcx.infer_ctxt().build();
+            let ocx = ObligationCtxt::new(&infcx);
+            let cause = ObligationCause::dummy_with_span(self.cur_span());
+            // equate the two trait refs
```
Comment (lcnr) [inline compiler/rustc_const_eval/src/interpret/traits.rs:67]: that's because I forgot that the old solver exists/didn't look carefully enough. We still need to first normalize here

```suggestion
            // equate the two trait refs after normalization
            let expected_trait = ocx.normalize(&cause, self.param_env, expected_trait);
            let vtable_trait = ocx.normalize(&cause, self.param_env, vtable_trait);
```

**Comment by RalfJung** [comment]
So just normalizing and then using == does not work?

**Comment by RalfJung** [comment]
Makes sense. This seems to work, thanks!

@rustbot ready
