### PR TITLE
Fix invalid bounds string generation in rustdoc

### LINKED ISSUE #58737: rustdoc: redundant `where 'env: 'env`
Source: https://docs.rs/crossbeam/0.7.1/crossbeam/thread/struct.Scope.html

Generated by rustdoc:

```rust
pub struct Scope<'env>
where
    'env: 'env,
 { /* fields omitted */ }
```
Original code:

```rust
pub struct Scope<'env> {
    handles: SharedVec<SharedOption<thread::JoinHandle<()>>>,
    wait_group: WaitGroup,
    _marker: PhantomData<&'env mut &'env ()>,
}
```

Rustdoc has somehow inferred the `'env: 'env` bound, which is a tautology.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #58737.

Very weird and I'm not sure this is the best fix around. However, trying to fix it beforehand seems overly complicated compared to the gain (in `clean`, it wouldn't change anything since we **have to** return something so that wouldn't work, and in `hir`, I'm afraid I'd break something else for very little gain).

Also, I wasn't able to make a small code to reproduce the issue. The only way to test is to document `crossbeam` directly and check the `Scope` struct...

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
The bug seems to be introduced when re-exporting the struct (`Scope` is actually defined in `crossbeam_utils`), and i bet the `PhantomData<&'env mut &'env ()>` has something to do with the erroneous bound.

I was able to reproduce the error with the following code:

```rust
use std::marker::PhantomData;

pub struct Scope<'env> {
    _marker: PhantomData<&'env mut &'env ()>,
}
```

A downstream crate that re-exports the `Scope` struct will create the erroneous bound. I wonder if this is something we should deal with inside the compiler? @rust-lang/compiler Do inferred region bounds somehow make it into a crate's metadata? Rustdoc is seeing an erroneous `where 'env: 'env` on the above struct, and we're looking for ways to filter that out in the docs.

**Comment by QuietMisdreavus** [comment]
Your test doesn't properly exercise the bug, since it primarily appears when the struct is re-exported. However, i would still like to see input from @rust-lang/compiler in case it can be fixed on their end.

**Comment by eddyb** [comment]
> Do inferred region bounds somehow make it into a crate's metadata?

Well... they must be, mustn't they? Otherwise how do you rely on them cross-crate?

It may be possible that in rustdoc you're using `predicates_of` (which includes `inferred_outlives_of`) when you want `explicit_predicates_of`:
https://github.com/rust-lang/rust/blob/0f88167f89fffe321590c5148f21b7d51d44388d/src/librustc/ty/query/mod.rs#L136-L142

**Comment by QuietMisdreavus** [comment]
> > Do inferred region bounds somehow make it into a crate's metadata?
> 
> Well... they must be, mustn't they? Otherwise how do you rely on them cross-crate?

I was under the assumption that they could be re-calculated from the definition, but i guess not.

> It may be possible that in rustdoc you're using `predicates_of` (which includes `inferred_outlives_of`) when you want `explicit_predicates_of`:
> [rust/src/librustc/ty/query/mod.rs](https://github.com/rust-lang/rust/blob/0f88167f89fffe321590c5148f21b7d51d44388d/src/librustc/ty/query/mod.rs#L136-L142)

It looks like we are using `predicates_of` when cleaning the AST (and inlining items). I feel like switching to `explicit_predicates_of` would fix both this issue and https://github.com/rust-lang/rust/issues/56331.

**Comment by nikomatsakis** [comment]
JFYI we could probably screen out `'a: 'a` bounds from the inferred bounds list, although it doesn't sound to me like the "right" fix here necessarily -- that would be done by [adding a check roughly here](https://github.com/rust-lang/rust/blob/ef4d1c419525e1510aa650e2bec0d8f7449a2130/src/librustc_typeck/outlives/utils.rs#L115-L120) to see whether `r == outlived_region`, I think

**Comment by Centril** [comment]
Ping from triage, @GuillaumeGomez :)

**Comment by GuillaumeGomez** [comment]
> It looks like we are using predicates_of when cleaning the AST (and inlining items). I feel like switching to explicit_predicates_of would fix both this issue and #56331.

Well, it panics when I tried to switch so not sure about that... Investigating.

**Comment by GuillaumeGomez** [comment]
I changed a few things around but we now have a new issue: for non local elements, it just doesn't work. Any idea on this @eddyb?

**Comment by eddyb** [comment]
> I was under the assumption that they could be re-calculated from the definition, but i guess not.

Yeah, the problem is that the definition is sort of lost (part of why rustdoc needs two codepaths for everything...), and only some information of note is kept.

Although specifically in this case, enough information might be there, but it would be a bit of waste to recompute it each time.

**Comment by GuillaumeGomez** [comment]
I also added the test from #59033.

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/compiler

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -1918,7 +1918,10 @@ fn explicit_predicates_of<'a, 'tcx>(
         }
     }
 
-    let hir_id = tcx.hir().as_local_hir_id(def_id).unwrap();
+    let hir_id = match tcx.hir().as_local_hir_id(def_id) {
+        Some(hir_id) => hir_id,
+        None => return tcx.predicates_of(def_id),
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: This is another change to `rustc_typeck` that wasn't explicitly approved (the comment thread doesn't make it clear that *a hack* was added outside of rustdoc), can we please not do this? I'll create a PR reverting these, but I feel like we have a larger process break issue...

Yes, I didn't see this notification until now, but *please* ping me elsewhere instead of merging typeck hacks like this.

Comment (eddyb) [reply src/librustc_typeck/collect.rs]: Not to mention this is wrong for cross-crate items, my expectation was that `explicit_predicates_of` was available cross-crate.

Comment (Centril) [reply src/librustc_typeck/collect.rs]: @estebank ^

Comment (GuillaumeGomez) [reply src/librustc_typeck/collect.rs]: I did ping the compiler team so I thought you'd see the notification, my bad.

Comment (estebank) [reply src/librustc_typeck/collect.rs]: Talked with Eddy on chat. My bad as the previous seemed to make sense on isolation. I'll defer to Eddy's assessment on typeck code in the future.

Comment (eddyb) [reply src/librustc_typeck/collect.rs]: @GuillaumeGomez Being notified isn't enough, we need to acknowledge it too.
With @nikomatsakis less active lately (and also on PTO more recently), a bit more care should be taken.

Comment (eddyb) [reply src/librustc_typeck/collect.rs]: Opened #59789.

Comment (GuillaumeGomez) [reply src/librustc_typeck/collect.rs]: I didn't approved the PR nor asked anyone (except the compiler team) to review it. I approve for more care to be taken but I feel like taking the blame for an error I didn't make. :-/

Comment (oli-obk) [reply src/librustc_typeck/collect.rs]: This is a process failure, not your failure! We'll figure out how to prevent such things happening in the future.

Comment (estebank) [reply src/librustc_typeck/collect.rs]: @GuillaumeGomez The one at fault here was _me_, not you, as I approved this change thinking it looked reasonable without being my main area of expertise, _I_ should have deferred to @eddyb's or @nikomatsakis' judgement on this case.
