### PR TITLE
check_match: Dereference `ref x` before comparing it and some other type

### LINKED ISSUE #23009: unexpected panic in pattern matching
This is the code that ICEs, as minimal as I could make it.

```
fn main() {
    let mut v = vec![1, 2, 3];

    match &v[..] {
        [1, ref n, 3] => {},
        [1, 2, 3] => {},
    }
}
```

```
$ RUST_BACKTRACE=1 rustc ble.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/check_match.rs:658

stack backtrace:
   1:         0x5c1b4c4f - sys::backtrace::write::hb08af03691eab78a5kA
   2:         0x5c1dd782 - panicking::on_panic::h37164609ca1c02afBnJ
   3:         0x5c11d63a - rt::unwind::begin_unwind_inner::h24d5e7492198457b43I
   4:         0x5c11dd24 - rt::unwind::begin_unwind_fmt::hee1a09c48e390d87H2I
   5:         0x5c1dd307 - rust_begin_unwind
   6:         0x5c226cb4 - panicking::panic_fmt::h129020744e7a1c43Z9r
   7:         0x5c23022c - panicking::panic_bounds_check::h42fcb0eaffcd0f1058r
   8:         0x59fa83ca - middle::check_match::is_useful::h564cfcfb5611bfb3FRf
   9:         0x59fd47c5 - middle::check_match::is_useful_specialized::h6723fd8117540027XZf
  10:         0x59fd5641 - middle::check_match::is_useful::closure.75994
  11:         0x59fd5309 - iter::Map<I, F>.Iterator::next::h6922741939313682342
  12:         0x59fa783a - middle::check_match::is_useful::h564cfcfb5611bfb3FRf
  13:         0x59fd47c5 - middle::check_match::is_useful_specialized::h6723fd8117540027XZf
  14:         0x59fd5641 - middle::check_match::is_useful::closure.75994
  15:         0x59fd5309 - iter::Map<I, F>.Iterator::next::h6922741939313682342
  16:         0x59fa783a - middle::check_match::is_useful::h564cfcfb5611bfb3FRf
  17:         0x59fd47c5 - middle::check_match::is_useful_specialized::h6723fd8117540027XZf
  18:         0x59fd5641 - middle::check_match::is_useful::closure.75994
  19:         0x59fd5309 - iter::Map<I, F>.Iterator::next::h6922741939313682342
  20:         0x59fa783a - middle::check_match::is_useful::h564cfcfb5611bfb3FRf
  21:         0x59fd47c5 - middle::check_match::is_useful_specialized::h6723fd8117540027XZf
  22:         0x59fd5641 - middle::check_match::is_useful::closure.75994
  23:         0x59fd5309 - iter::Map<I, F>.Iterator::next::h6922741939313682342
  24:         0x59fa783a - middle::check_match::is_useful::h564cfcfb5611bfb3FRf
  25:         0x59fa0852 - middle::check_match::check_expr::h40117a214c57fedfadf
  26:         0x59fa252a - middle::check_match::check_fn::h951fa0814382c1eaKpg
  27:         0x59fa2d8c - visit::walk_item::h4129520673127106273
  28:         0x59fa2baa - middle::check_match::check_crate::hb09e09956c3438ffNcf
  29:         0x5c8364b2 - driver::phase_3_run_analysis_passes::h55e7e7af941f4089xFa
  30:         0x5c81a411 - driver::compile_input::hee81c045ab46c74fIba
  31:         0x5c8e4e6e - run_compiler::h875c1e123fe4ae2cF5b
  32:         0x5c8e2a1c - thunk::F.Invoke<A, R>::invoke::h14796375338076039584
  33:         0x5c8e1770 - rt::unwind::try::try_fn::h17889328263510442428
  34:         0x5c248fe8 - rust_try_inner
  35:         0x5c248fd5 - rust_try
  36:         0x5c8e1e5c - thunk::F.Invoke<A, R>::invoke::h2091551127524498175
  37:         0x5c1c92d5 - sys::thread::thread_start::h1b1bb1e7ac08d3a6yRE
  38:         0x55eeb529 - start_thread
  39:         0x5bda379c - clone
  40:         0xffffffff - <unknown>
```

```
$ rustc --version --verbose
rustc 1.0.0-nightly (890293655 2015-02-28) (built 2015-03-01)
binary: rustc
commit-hash: 890293655251c372ea99694c0c9f0795e2663286
commit-date: 2015-02-28
build-date: 2015-03-01
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

### PR DESCRIPTION
**Pull request by barosl**
The arity of `ref x` is always 1, so it needs to be dereferenced before being compared with some other type whose arity is not 1.

Fixes #23009.

### CODE REVIEW

**Comment by barosl** [comment]
I'm really not sure if this is the right way to fix the issue, so I beg for the forgiveness in advance.

File: src/test/compile-fail/match-specialize-ice.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// Related issue: #23009
```
Comment (nrc) [inline src/test/compile-fail/match-specialize-ice.rs]: Please add a comment to tests saying what is being tested - why it should fail, why it shouldn't ICE. This is helpful for future contributors who break your test and need to know if it is important.

**Comment by nrc** [comment]
Afraid I don't know this code well enough to review, sorry. Perhaps r? @pnkfelix

File: src/librustc/middle/check_match.rs [hunk 2]
```diff
@@ -864,7 +864,10 @@ pub fn specialize<'a>(cx: &MatchCheckCtxt, r: &[&'a Pat],
                 } else {
                     None
                 },
-                _ => Some(repeat(DUMMY_WILD_PAT).take(arity).collect())
+                _ => match *constructor {
+                    ConstantValue(..) => Some(vec![]),
```
Comment (pnkfelix) [inline src/librustc/middle/check_match.rs]: so I'm not totally familiar with this code; I'm looking at what you've added here, and I do not immediately see why it suffices to add a special case for `ConstantValue(..)` but not need one for e.g. `ConstantRange` .  Can you enlighten me?

**Comment by pnkfelix** [comment]
(i'm going to be out until wedneday; handing off to @nikomatsakis to find a reviewer to replace me.)

r? @nikomatsakis

**Comment by jakub-** [comment]
I'll take this.

@barosl Thanks for tackling this. I don't think your fix is the appropriate one here. If you notice, the example will compile fine if you drop the `ref` from the binding.

It looks like we're getting bitten by our old problem of `ref x` having a type of '&T' as opposed to just 'T'. In this case, this is problematic for the `check_match::constructor_arity` function. For non-structural types such as usize in this case, the arity of `ref x` should be 0 but is instead 1 due to the misleading type information.

The place to hunt for a solution will be around https://github.com/rust-lang/rust/blob/ee7696383f3423cdd17373ff9e75c01acd8e3417/src/librustc/middle/check_match.rs#L649-658.

```rust
    let left_ty = if real_pat.id == DUMMY_NODE_ID {
        ty::mk_nil(cx.tcx)
    } else {
        ty::pat_ty(cx.tcx, &*real_pat)
    };
```

One way or another, we will need this to be the type of the value being destructured, free from the idiosyncracies of `ref x`.

**Comment by jakub-** [comment]
Also, could you add the following assertion:
```rust
assert!(rows.iter().all(|row| row.len() == v.len()));
```
above this line:
https://github.com/rust-lang/rust/blob/ee7696383f3423cdd17373ff9e75c01acd8e3417/src/librustc/middle/check_match.rs#L649

**Comment by barosl** [comment]
If we sanitize `left_ty` before passing it to another function, as you said, the following code would work:

```rust
let left_ty = match (&real_pat.node, &left_ty.sty) {
    (&ast::PatIdent(..), &ty::ty_rptr(_, ty::mt { ty, .. })) => match ty.sty {
        ty_int(..) | ty_uint(..) | ty_bool | ty_char | ty_float(..) => ty,
        _ => left_ty,
    },
    _ => left_ty,
};
```

But how about modifying `constructor_arity()` directly? In that case, we can utilize `ctor` to guess the type of the previous row. I've updated my code to reflect this approach. If it is not appropriate, I will change it again to apply the code above.

**Comment by jakub-** [comment]
@barosl `left_ty` is used for various things across the board so I am afraid it needs to be correct.

I don't think we need the nested match at all. Any time you see the pattern `ref x`, the real type we're interested in is ty::deref(left_ty), no matter what the inner type is.

```rust
left_ty = match left_ty {
    ast::PatIdent(ByRef, _, _) => ty::deref(left_ty).unwrap().ty
    _ => left_ty
};
```

**Comment by jakub-** [comment]
Sorry, I realise I'd misled you by talking about non-structural and structural types. My only point was that non-structural types should always have arity of 0 but that when for `ref x` it's always 1.

**Comment by barosl** [comment]
Oh, I see! So the arity itself wasn't wrong.

It seems that you coded the most part, though :smile:. I'll update my pull request based on your comment, and run tests locally.

**Comment by barosl** [comment]
@jakub- Ok, I've done it. The tests pass locally.

Also, I changed the code to pass `explicit=false` to `ty::deref()`, in order to make sure the type is not `ty_ptr`. Would that be OK?

**Comment by jakub-** [comment]
@barosl: Sure, that's fine. :) Thanks!

**Comment by barosl** [comment]
a
