### PR TITLE
Fix suggestion to use lifetime in type and in assoc const

### LINKED ISSUE #72404: On missing HRLT annotation, we sometimes provide a slightly incorrect suggestion
[Given the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=12786f810de4e1832983c2f8f5d5e2d3):

```rust
struct X<'a>(&'a ());
struct S<'a>(&'a dyn Fn(&X) -> &X);

fn main() {
    let x = S(&|x| {
        println!("hi");
        x
    });
    x.0(&X(&()));
}
```

we currently give the following output

```
error[E0106]: missing lifetime specifier
 --> src/main.rs:2:32
  |
2 | struct S<'a>(&'a dyn Fn(&X) -> &X);
  |                         --     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of argument 1's 2 lifetimes it is borrowed from
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
2 | struct S<'a>(&'a dyn for<'a> Fn(&'a X) -> &'a X);
  |                      ^^^^^^^    ^^^^^     ^^^
help: consider introducing a named lifetime parameter
  |
2 | struct S<'a, 'a>(&'a dyn Fn(&'a X) -> &'a X);
  |          ^^^                ^^^^^     ^^^

error[E0106]: missing lifetime specifier
 --> src/main.rs:2:33
  |
2 | struct S<'a>(&'a dyn Fn(&X) -> &X);
  |                         --      ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of argument 1's 2 lifetimes it is borrowed from
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
2 | struct S<'a>(&'a dyn for<'a> Fn(&'a X) -> &X<'a>);
  |                      ^^^^^^^    ^^^^^      ^^^^^
help: consider introducing a named lifetime parameter
  |
2 | struct S<'a, 'a>(&'a dyn Fn(&'a X) -> &X<'a>);
  |          ^^^                ^^^^^      ^^^^^
```

Beyond the verbosity, one of the suggestions offers `struct S<'a, 'a>`, which is not ideal.

### LINKED ISSUE #74264: Suggestion diagnostic for new generic argument is placed at beginning of file
The suggestion to change `&str` to `&'a str` and give `ZstAssert` a `<'a>` generic argument places the `<'a>` at the beginning of the file. If you add any items before the trait decl, the suggestion will be before those unrelated items.

```rust
trait ZstAssert: Sized {
    const TYPE_NAME: &str = "";
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dee6e7e4dac5b45670801fad68c2e3ee))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0106]: missing lifetime specifier
 --> src/lib.rs:2:22
  |
2 |     const TYPE_NAME: &str = "";
  |                      ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 | <'a>trait ZstAssert: Sized {
2 |     const TYPE_NAME: &'a str = "";
  |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by estebank**
_Do not merge until #75363 has landed, as it has the test case for this._

* Account for associated types
* Associated `const`s can't have generics (fix #74264)
* Do not suggest duplicate lifetimes and suggest `for<'a>` more (fix #72404)

### CODE REVIEW

**Comment by estebank** [comment]
cc @JohnTitor

File: src/librustc_resolve/late/diagnostics.rs [hunk 1]
```diff
@@ -1301,26 +1360,26 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
 
         match (lifetime_names.len(), lifetime_names.iter().next(), snippet.as_deref()) {
```
Comment (lcnr) [inline src/librustc_resolve/late/diagnostics.rs:1361]: this match is somewhat hard to read, considering that perf is somewhat irrelevant here, I think it might be a good idea to convert `lifetime_names` to a `Vec` and use slice patterns here

File: src/librustc_resolve/late/diagnostics.rs [hunk 2]
```diff
@@ -1301,26 +1360,26 @@ impl<'tcx> LifetimeContext<'_, 'tcx> {
...
-                suggest_existing(err, format!("&{} ", name));
+                suggest_existing(err, &name.as_str()[..], &|name| format!("&{} ", name));
             }
             (1, Some(name), Some("'_")) => {
-                suggest_existing(err, name.to_string());
+                suggest_existing(err, &name.as_str()[..], &|n| n.to_string());
             }
             (1, Some(name), Some("")) => {
-                suggest_existing(err, format!("{}, ", name).repeat(count));
+                suggest_existing(err, &name.as_str()[..], &|n| format!("{}, ", n).repeat(count));
```
Comment (lcnr) [inline src/librustc_resolve/late/diagnostics.rs:1369]: I don't quite understand that branch :thinking: is there a test where this is used?

Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs:1369]: There should be, but this PR shouldn't affect those tests. I inverted the formatting of the suggested name by using a closure so that we can use either the provided name or the name that `suggest_existing` will come up with that doesn't clash with any other present lifetime name. This is because you might have `X<'_, '_>`, so we would suggest both `X<'a, 'a>` where `'a` already exists and `for<'b> X<'b, 'b>`.

File: src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr [hunk 3]
```diff
@@ -0,0 +1,15 @@
+error[E0106]: missing lifetime specifier
+  --> $DIR/missing-lifetime-in-assoc-const-type.rs:2:22
+   |
+LL |     const TYPE_NAME: &str = "";
+   |                      ^ expected named lifetime parameter
+   |
+help: consider introducing a named lifetime parameter
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr:7]: Makes sense.

File: src/librustc_resolve/late/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs:1361]: I think this code predates slice patterns. Good idea.

Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs]: done

File: src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr (hunk 3 above)
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr:62]: done

File: src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+   |
+LL |     const D: T<'static, 'static> = T { a: &(), b: &() };
+   |               ^^^^^^^^^^^^^^^^^^
+help: consider introducing a named lifetime parameter
+   |
+LL | trait ZstAssert<'a>: Sized {
+LL |     const A: &str = "";
+LL |     const B: S = S { s: &() };
+LL |     const C: &'_ str = "";
+LL |     const D: T<'a, 'a> = T { a: &(), b: &() };
```
Comment (lcnr) [inline src/test/ui/suggestions/missing-lifetime-in-assoc-const-type.stderr:68]: That error message is somewhat unfortunate, but I don't think there is something we can do here :shrug:

**Review by lcnr — APPROVED** [review]
:+1:
