### PR TITLE
Fix handling of parse errors when using `include!()`.

### LINKED ISSUE #21146: `include!`'d source, when encountering a parse error, does not report-and-abort.
Testcase:

`inc.rs`:
```rust
afddafadsfasdfdasfaf
fn never_parsed() -> i32 { 42 }
```

`main.rs`:
```rust
include!("inc.rs");
fn main() { never_parsed(); }
```

Output:

```
csguest@itl:~/Downloads$ rustc main.rs
main.rs:4:2: 4:14 error: unresolved name `never_parsed`
main.rs:4 	never_parsed();
          	^~~~~~~~~~~~
error: aborting due to previous error
```

Should output, instead, the parse errors from `include!`. Probably misplacing the diagnostic emitter somehow, when creating the nested parser for the included source, and doesn't have an `abort_if_errors`.

### PR DESCRIPTION
**Pull request by LeoTestard**
Makes the compilation abort when a parse error is encountered while
trying to parse an item in an included file. The previous behaviour was
to stop processing the file when a token that can't start an item was
encountered, without producing any error. Fixes #21146.

### CODE REVIEW

File: src/test/compile-fail/issue-21146-inc.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// ignore-test
+// include file for issue-21146.rs
+// not supposed to be tested alone
+
+parse_error
```
Comment (eddyb) [inline src/test/compile-fail/issue-21146-inc.rs]: We have auxiliary directories (or something along those lines) for stuff like this.

Comment (LeoTestard) [inline src/test/compile-fail/issue-21146-inc.rs]: Didn't know that. Fixed, thanks.

**Comment by alexcrichton** [comment]
@bors: r+ 8f2ab66

Thanks!

**Comment by Manishearth** [comment]
Perhaps the test should be placed in the [newly created](https://github.com/rust-lang/rust/pull/22011) `parse-fail`?

Or we can move it later as a rollup. Either works.

**Comment by cmr** [comment]
Thank you so much <3
