### PR TITLE
Fix missing leading space in suggestion

### LINKED ISSUE #117380: Rustc suggests incorrect fixes (`#[warn(unused_parens)]`)
### Code

```Rust
fn main() {
    let(mut _x): i8 = 0;
    let( mut _x): i8 = 0;
    let(_x): i8 = 0;
}
```

### Current output

```Shell
warning: unnecessary parentheses around pattern
 --> src/main.rs:2:8
  |
2 |     let(mut _x): i8 = 0;
  |        ^      ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
2 -     let(mut _x): i8 = 0;
2 +     letmut _x: i8 = 0;
  |

warning: unnecessary parentheses around pattern
 --> src/main.rs:3:8
  |
3 |     let( mut _x): i8 = 0;
  |        ^^      ^
  |
help: remove these parentheses
  |
3 -     let( mut _x): i8 = 0;
3 +     letmut _x: i8 = 0;
  |

warning: unnecessary parentheses around pattern
 --> src/main.rs:4:8
  |
4 |     let(_x): i8 = 0;
  |        ^  ^
  |
help: remove these parentheses
  |
4 -     let(_x): i8 = 0;
4 +     let_x: i8 = 0;
  |
```

### Desired output

```Shell
warning: unnecessary parentheses around pattern
 --> src/main.rs:2:8
  |
2 |     let(mut _x): i8 = 0;
  |        ^      ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
2 -     let(mut _x): i8 = 0;
2 +     let mut _x: i8 = 0;
  |

warning: unnecessary parentheses around pattern
 --> src/main.rs:3:8
  |
3 |     let( mut _x): i8 = 0;
  |        ^^      ^
  |
help: remove these parentheses
  |
3 -     let( mut _x): i8 = 0;
3 +     let mut _x: i8 = 0;
  |

warning: unnecessary parentheses around pattern
 --> src/main.rs:4:8
  |
4 |     let(_x): i8 = 0;
  |        ^  ^
  |
help: remove these parentheses
  |
4 -     let(_x): i8 = 0;
4 +     let _x: i8 = 0;
  |
```

### Rationale and extra context

Rustc suggests incorrect fixes for #[warn(unused_parens)] for these patterns.

### Other cases

_No response_

### Anything else?

Rustc version:
```bash
rustc 1.75.0-nightly (e5cfc5547 2023-10-28)
binary: rustc
commit-hash: e5cfc55477eceed1317a02189fdf77a4a98f2124
commit-date: 2023-10-28
host: x86_64-pc-windows-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3
```

(the same issue with the stable 1.73.0 rustc).

### PR DESCRIPTION
**Pull request by gurry**
For a local pattern with no space between `let` and `(` e.g.:
```rust
  let(_a) = 3;
```
we were previously suggesting this illegal code:
```rust
  let_a = 3;
```
After this change the suggestion will instead be:
```rust
  let _a = 3;
```
Fixes #117380

### CODE REVIEW

File: compiler/rustc_lint/src/unused.rs [hunk 1]
```diff
@@ -1154,7 +1154,7 @@ impl EarlyLintPass for UnusedParens {
 
     fn check_stmt(&mut self, cx: &EarlyContext<'_>, s: &ast::Stmt) {
         if let StmtKind::Local(ref local) = s.kind {
-            self.check_unused_parens_pat(cx, &local.pat, true, false, (false, false));
+            self.check_unused_parens_pat(cx, &local.pat, true, false, (true, false));
```
Comment (Nilstrieb) [inline compiler/rustc_lint/src/unused.rs:1157]: these awful unreadable arguments mean this:
```rust
        avoid_or: bool,
        avoid_mut: bool,
        keep_space: (bool, bool),
```

Comment (gurry) [reply compiler/rustc_lint/src/unused.rs:1157]: @Nilstrieb do you want me to refactor this function's signature to make the args more readable?

Comment (Nilstrieb) [reply compiler/rustc_lint/src/unused.rs:1157]: that would be nice as a follow up PR if you want to :3

Comment (gurry) [reply compiler/rustc_lint/src/unused.rs:1157]: Okay, sure :)._

**Comment by Nilstrieb** [comment]
r? Nilstrieb
@bors r+ rollup
looks reasonable to me
