### PR TITLE
Limit I/O vector count on Unix

### LINKED ISSUE #68042: std::io::Write::write_vectored() does not properly limit the number of iovecs.
The callers of `std::io::Write::write_vectored()` should not have to go through the effort of determining what the maximum number of iovec structures can be passed to the underlying system call.  As demonstrated by this example:

```rust
use std::fs::File;
use std::io::prelude::*;
use std::io::{BufWriter, IoSlice};

fn main() {
    let mut file = BufWriter::new(File::create("./example-output.txt").unwrap());
    let mut write_array: Vec<IoSlice> = Vec::new();
    for _ in 1..1024 * 5 {
        write_array.push(IoSlice::new(b"1"));
        write_array.push(IoSlice::new(b"\n"));
    }
    file.write_vectored(&write_array).unwrap();
    file.flush().unwrap();
}
```

The output is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x10621f175 - backtrace::backtrace::libunwind::trace::hb16ec6045891ce5a
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10621f175 - backtrace::backtrace::trace_unsynchronized::hcacbd0efdffd74c6
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10621f175 - std::sys_common::backtrace::_print_fmt::h39e22de9d6757d12
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x10621f175 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415ddd0ba88caaaf
                               at src/libstd/sys_common/backtrace.rs:61
   4:        0x106236cb0 - core::fmt::write::h3335552e2df81c1d
                               at src/libcore/fmt/mod.rs:1028
   5:        0x10621db6b - std::io::Write::write_fmt::he6837371b9a45188
                               at src/libstd/io/mod.rs:1412
   6:        0x106220d43 - std::sys_common::backtrace::_print::h89459d14ba97f5fa
                               at src/libstd/sys_common/backtrace.rs:65
   7:        0x106220d43 - std::sys_common::backtrace::print::ha4c6688e811b8829
                               at src/libstd/sys_common/backtrace.rs:50
   8:        0x106220d43 - std::panicking::default_hook::{{closure}}::h708e66cfeb0483ba
                               at src/libstd/panicking.rs:188
   9:        0x106220a4a - std::panicking::default_hook::h39ea8ddf674c04ec
                               at src/libstd/panicking.rs:205
  10:        0x10622134b - std::panicking::rust_panic_with_hook::h9db77b22c2255a16
                               at src/libstd/panicking.rs:464
  11:        0x106220ed9 - std::panicking::continue_panic_fmt::h2dfa3a5b90265361
                               at src/libstd/panicking.rs:373
  12:        0x106220e29 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:        0x1062397cc - std::panicking::begin_panic::h8518f1142ed7061c
  14:        0x1062398a9 - std::panicking::begin_panic::h8518f1142ed7061c
  15:        0x1062181c1 - core::result::Result<T,E>::unwrap::h79b719002edcbf6d
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16:        0x106214a2a - vector_bug::main::h3df611f13f1e9a88
                               at src/main.rs:12
  17:        0x106211c92 - std::rt::lang_start::{{closure}}::h4e4da6e08497b9a6
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  18:        0x106220e08 - std::rt::lang_start_internal::{{closure}}::hccd7db6d8a0ebab5
                               at src/libstd/rt.rs:48
  19:        0x106220e08 - std::panicking::try::do_call::hd5a3af8d00c06681
                               at src/libstd/panicking.rs:287
  20:        0x10622281f - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  21:        0x1062216de - std::panicking::try::h7a0bd4c078131d2f
                               at src/libstd/panicking.rs:265
  22:        0x1062216de - std::panic::catch_unwind::h75c3fbe62776ab10
                               at src/libstd/panic.rs:396
  23:        0x1062216de - std::rt::lang_start_internal::haa52aabac43378ff
                               at src/libstd/rt.rs:47
  24:        0x106211c72 - std::rt::lang_start::h34001aec5ec8c720
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25:        0x106214ac2 - vector_bug::main::h3df611f13f1e9a88
```

The underlying system call of writev() has limit on the number of iovec items that can be passed specifically the [man page for writev()](https://linux.die.net/man/2/writev) has

> POSIX.1-2001 allows an implementation to place a limit on the number of items that can be passed in iov. An implementation can advertise its limit by defining IOV_MAX in <limits.h> or at run time via the return value from sysconf(_SC_IOV_MAX). On Linux, the limit advertised by these mechanisms is 1024, which is the true kernel limit. However, the glibc wrapper functions do some extra work if they detect that the underlying kernel system call failed because this limit was exceeded. In the case of readv() the wrapper function allocates a temporary buffer large enough for all of the items specified by iov, passes that buffer in a call to read(2), copies data from the buffer to the locations specified by the iov_base fields of the elements of iov, and then frees the buffer. The wrapper function for writev() performs the analogous task using a temporary buffer and a call to write(2).

When running on Mac OS X it appears the libc implementation is not doing the extra work of determining the limit of the number of items that can be used in one call of writev().  On Mac OS X this limit is defined by `UIO_MAXIOV`.

Looking at the unix implementation of write_vectored it seems that line 113 is the problem.

https://github.com/rust-lang/rust/blob/3982d3514efbb65b3efac6bb006b3fa496d16663/src/libstd/sys/unix/fd.rs#L108-L117

The code that assumes the upper limit of the number of iovecs being passed can equal  `c_int::max_value()` is too large.  It should either be limited to `UID_MAXIOV` on Max OS X or the result of `sysconf(_SC_IOV_MAX)` on Linux.

Changing this logic will help the logic work such that any number of IoSlices can be passed to `io::std::Write::write_vectored()`.

### PR DESCRIPTION
**Pull request by adamreichold**
Unix systems enforce limits on the vector count when performing vectored I/O via the readv and writev system calls and return EINVAL when these limits are exceeded. This changes the standard library to handle those limits as short reads and writes to avoid forcing its users to query these limits using platform specific mechanisms.

Fixes #68042

### CODE REVIEW

**Comment by adamreichold** [comment]
This is my first PR and I am sorry if I messed up the procedure.

I also am rather unsure whether the overhead of `SyncOnceCell` for each call to `writev` is tenable but I also did not immediately find another instance where a system configuration parameter is queried via `sysconf` and then used with a frequently invoked system call.

File: library/std/src/sys/unix/fd.rs [hunk 1]
```diff
@@ -26,6 +27,31 @@ const READ_LIMIT: usize = c_int::MAX as usize - 1;
 #[cfg(not(target_os = "macos"))]
 const READ_LIMIT: usize = libc::ssize_t::MAX as usize;
 
+#[cfg(any(target_os = "linux", target_os = "macos"))]
+fn max_iov() -> c_int {
+    static LIM: SyncOnceCell<c_int> = SyncOnceCell::new();
```
Comment (matklad) [inline library/std/src/sys/unix/fd.rs:32]: Drive by comment, but for things that don't need exactly once semantics I prefer code like this, which doesn't invoke synchronization machinery:

```
static CACHE: AtomicUsize = AtomicUsize::new(!0);
let val = CACHE.load(Relaxed);
if val != !0 { return val }
let val = compute_val();
CACHE.store(val, Relaxed)
val
```

There's no real benefits to this, just using the smallest tool for the job.

Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs]: Thank you for the advice! I adjusted the code following your suggestion but using zero as the initial value as this is not a valid value in this case.

File: library/std/src/sys/unix/fd.rs [hunk 2]
```diff
@@ -26,6 +27,35 @@ const READ_LIMIT: usize = c_int::MAX as usize - 1;
...
+                #[cfg(target_os = "linux")]
+                libc::_SC_IOV_MAX,
+                #[cfg(target_os = "macos")]
+                libc::_SC_UIO_MAXIOV,
+            )
+        };
+
+        // 1024 is the default value on modern Linux systems
+        // and hopefully more useful than `c_int::MAX`.
+        lim = if ret > 0 { ret as usize } else { 1024 };
```
Comment (lzutao) [inline library/std/src/sys/unix/fd.rs:47]: Should we set `errno=0` before `sysconf` and check it again when `ret == -1`?

Comment (lzutao) [reply library/std/src/sys/unix/fd.rs:47]: Ref https://man7.org/linux/man-pages/man3/sysconf.3p.html#RETURN_VALUE

**Comment by hanna-kruppe** [comment]
I don't really know anything about vectored I/O. r? @Amanieu maybe?

File: library/std/src/sys/unix/fd.rs (hunk 2 above)
Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:47]: I though about this and decided to not try to handle/propagate errors here and silently fallback to a default value instead as
* the value will not change for the lifetime of the process and I therefore want to report an error at most once to avoid repeatedly making a failing system call
* but I also would not like the first call to `FileDesc::write_vectored` to behave observably different by reporting the error from `libc::sysconf`
* thereby logging the error seems to be the only reasonable action in addition to the fallback but I did not find any infrastructure for logging within the standard library

**Comment by Amanieu** [comment]
On Linux `UIO_MAXIOV` is a constant defined in the kernel headers:
```c

**Comment by adamreichold** [comment]
> On Linux `UIO_MAXIOV` is a constant defined in the kernel headers:
> 
> ```c
> #define UIO_MAXIOV	1024
> ```

Could you expand on the implication you see here? Do you mean that we should just hard code the constant and thereby avoid the call to `sysconf`? (Even with the plain relaxed load instead of `SyncOnceCell`?)

**Comment by adamreichold** [comment]
> Could you expand on the implication you see here?

Or put differently, isn't the `sysconf` mechanism exactly meant to query such configuration parameters in a well-defined manner? Otherwise one would need to change our constant value here if the "official" value in the kernel headers changes or someone builds a custom kernel where the value is modified.

File: library/std/src/sys/unix/fd.rs [hunk 3]
```diff
@@ -26,6 +27,35 @@ const READ_LIMIT: usize = c_int::MAX as usize - 1;
 #[cfg(not(target_os = "macos"))]
 const READ_LIMIT: usize = libc::ssize_t::MAX as usize;
 
+#[cfg(any(target_os = "linux", target_os = "macos"))]
+fn max_iov() -> usize {
```
Comment (lzutao) [inline library/std/src/sys/unix/fd.rs:31]: Does it include unix as _SC_IOV_MAX declared in POSIX 1: https://pubs.opengroup.org/onlinepubs/009695399/functions/sysconf.html ?

File: library/std/src/sys/unix/fd.rs (hunk 2 above)
Comment (lzutao) [reply library/std/src/sys/unix/fd.rs:47]: But while not explicitly check for -1?

Comment (lzutao) [reply library/std/src/sys/unix/fd.rs:47]: While not explicitly check for -1?

Comment (Amanieu) [reply library/std/src/sys/unix/fd.rs:47]: I would suggest using 16 as the fallback value since that is the minimum guaranteed by POSIX.

Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:47]: > While not explicitly check for -1?

Accepting zero is not reasonable either as calls to `write_vectored` would not make progress using that limit, hence the check for `ret > 0` instead of checking `ret == 0` and `ret < 0` separately as the reaction is the same: use the fallback value.

> I would suggest using 16 as the fallback value since that is the minimum guaranteed by POSIX.

Will do.

File: library/std/src/sys/unix/fd.rs [hunk 4]
```diff
@@ -26,6 +27,35 @@ const READ_LIMIT: usize = c_int::MAX as usize - 1;
 #[cfg(not(target_os = "macos"))]
 const READ_LIMIT: usize = libc::ssize_t::MAX as usize;
 
+#[cfg(any(target_os = "linux", target_os = "macos"))]
```
Comment (Amanieu) [inline library/std/src/sys/unix/fd.rs:30]: This shouldn't be restricted to just Linux and macOS, all Unix-like OSes have limits on iovec length. Also it seems that all these targets have a definition of `_SC_IOV_MAX` so there is no need to special case `_SC_UIO_MAXIOV` for macOS.

**Comment by Amanieu** [comment]
After thinking about it a bit, I think sticking to `sysconf` is probably safer in the long run.

File: library/std/src/sys/unix/fd.rs (hunk 4 above)
Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:30]: > This shouldn't be restricted to just Linux and macOS, all Unix-like OSes have limits on iovec length.

What I was wondering here is whether `#[cfg(unix)]` implies POSIX and hence allows relying on `sysconf` and friends? Will change the code under that assumption...

> so there is no need to special case _SC_UIO_MAXIOV for macOS.

I am admittedly just not knowledgeable on macOS and took that information from the linked bug report. Will change both to just use `_SC_IOV_MAX`.

File: library/std/src/sys/unix/fd.rs (hunk 3 above)
Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:31]: I was not sure whether `#[cfg(unix)]` actually implies POSIX but as per @Amanieu's comment below, I will change this to purely rely on POSIX semantics.

File: library/std/src/sys/unix/fd.rs [hunk 5]
```diff
@@ -26,6 +27,21 @@ const READ_LIMIT: usize = c_int::MAX as usize - 1;
 #[cfg(not(target_os = "macos"))]
 const READ_LIMIT: usize = libc::ssize_t::MAX as usize;
 
+fn max_iov() -> usize {
+    static LIM: AtomicUsize = AtomicUsize::new(0);
```
Comment (pickfire) [inline library/std/src/sys/unix/fd.rs:31]: Are we doing this `LIM` thing just for lazy loading. IIRC std have some sort of `Lazy` that we could use for lazy loading right which may be simpler? Can we use that instead?

Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:31]: Please have a look at the resolved discussion at https://github.com/rust-lang/rust/pull/75005#discussion_r463961946 I started out with `std::lazy::SyncOnceCell` but since we do not need only-once semantics here (the `sysconf` value is guaranteed to not change during process lifetime and hence calling at most once per thread is sufficient), using the plain atomic is more efficient.

Comment (matklad) [reply library/std/src/sys/unix/fd.rs:31]: To unpack „simpler“, using OnceCell would allow us to write simpler (shorter) source code, but in terms of what the resulting assembly looks like, atomic version would be much simpler, as it would not include the whole waiting machinery.

**Comment by adamreichold** [comment]
@Amanieu Is there anything that is still needs of a resolution?

File: library/std/src/sys/unix/fd.rs [hunk 6]
```diff
@@ -256,3 +272,16 @@ impl Drop for FileDesc {
...
     }
 }
+
+#[cfg(test)]
+mod tests {
+    use super::{FileDesc, IoSlice};
+
+    #[test]
+    fn limit_vector_count() {
+        let stdout = FileDesc { fd: 0 };
```
Comment (Amanieu) [inline library/std/src/sys/unix/fd.rs:282]: Standard output is fd 1. 0 is standard input.

Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs:282]: Indeed. Interesting that writing to stdin does not fail. (I did test this before and after to check that it triggers the issue here and is fixed by the fix.) Will fix.

Comment (adamreichold) [reply library/std/src/sys/unix/fd.rs]: Fixed. I also checked and
```
use std::fs::File;
use std::io::Write;
use std::os::unix::io::FromRawFd;

fn main() {
    unsafe { File::from_raw_fd(0) }.write_all(b"FOO\n").unwrap();
}
```
write happily write to stdin which appears in the terminal just like stdout but indeed is not captured when e.g. redirecting stdout. Today I learned...

**Comment by adamreichold** [comment]
> broken_heart Test failed - [checks-actions](https://github.com/rust-lang-ci/rust/runs/949559205)

@Amanieu The build as Redox OS' `libc` does not define `_SC_IOV_MAX`. What do you think about adding a fallback like
```rust
#[cfg(target_os = "redox")]
fn max_iov() -> usize { 16 }
```
for this case?

**Comment by Amanieu** [comment]
Sounds good!

**Comment by adamreichold** [comment]
> Sounds good!

Added it and build tested on `x86_64-unknown-redox`. Does anybody know any other `cfg(unix)` targets up front that will need this before bors try this again?

**Comment by adamreichold** [comment]
> Does anybody know any other `cfg(unix)` targets up front that will need this before bors try this again?

Grepping `libc` sources suggests `target_env = "newlib"` would be affected as well...
