### PR TITLE
Exit the process a short time after entering our ctrl-c handler

### LINKED ISSUE #124212: The compiler keeps going on Ctrl-C
Sometimes when things go really wrong the compiler emits a *ton* of error messages. This can actually take a while to render them all. And since somewhat recently, hitting Ctrl-C no longer interrupts that, I get a thousand error messages displayed after Ctrl-C.

I suspect this may have to do with https://github.com/rust-lang/rust/pull/111769. The Ctrl-C handler does nothing at all on the first Ctrl-C unless the compiler is in the middle of const-eval.

Cc @saethlin

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/124212

r? @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
Thanks!

@bors r+

File: compiler/rustc_driver_impl/src/lib.rs [hunk 1]
```diff
@@ -1502,14 +1502,13 @@ pub fn init_logger(early_dcx: &EarlyDiagCtxt, cfg: rustc_log::LoggerConfig) {
...
-        // process on the second Ctrl-C.
-        if CTRL_C_RECEIVED.swap(true, Ordering::Relaxed) {
-            std::process::exit(1);
-        }
+        // Indicate that we have been signaled to stop, then give the rest of the compiler a bit of
+        // time to check CTRL_C_RECEIVED and run its own shutdown logic, but after a short amount
+        // of time exit the process. This sleep+exit ensures that even if nobody is checking
+        // CTRL_C_RECEIVED, the compiler exits reasonably promptly.
+        CTRL_C_RECEIVED.store(true, Ordering::Relaxed);
+        std::thread::sleep(Duration::from_millis(100));
```
Comment (jyn514) [inline compiler/rustc_driver_impl/src/lib.rs:1510]: this has a change in behavior which I think may not be intentional: if the user hits Ctrl C twice, it will still wait 100 ms instead of exiting immediately

Comment (saethlin) [reply compiler/rustc_driver_impl/src/lib.rs:1510]: It's intentional. You could definitely argue that it is bad, if you want. 

I added the behavior of immediately exiting on the second ctrl-c because I thought it would be the obvious thing to try if the compiler didn't respond to the first. At least the most recent issue https://github.com/rust-lang/rust/issues/125428 indicates this is either not obvious or prevented in some scenarios.

100 ms is a long time for a program, but significantly shorter than even an athlete's reaction time. Unless the OS scheduler truly hates us, the process should exit before the user even has time to realize the process haven't exited and send a second ctrl-c.
