### PR TITLE
promote debug_assert to assert when possible and useful

### LINKED ISSUE #94705: stdlib makes assumptions about errors returned by POSIX functions
Split off from https://github.com/rust-lang/miri/pull/1981#discussion_r820782765

For example, we assume that the return value of `pthread_rwlock_rdlock()` is either 0, `EAGAIN`, or `EDEADLK`: https://github.com/rust-lang/rust/blob/ac470e95852336172197810a9a4f6d2e8c8b6574/library/std/src/sys/unix/rwlock.rs#L51-L54

And that's kinda what POSIX documents: https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_rdlock.html

> ### RETURN VALUE
> 
> If successful, the *pthread_rwlock_rdlock()* function shall return zero; otherwise, an error number shall be returned to indicate the error. ...
>
> ### ERRORS
>
> ... The *pthread_rwlock_rdlock()* and *pthread_rwlock_tryrdlock()* functions may fail if:
>
> [EAGAIN]
>     The read lock could not be acquired because the maximum number of read locks for rwlock has been exceeded.
>
> The *pthread_rwlock_rdlock()* function may fail if:
>
> [EDEADLK]
>     A deadlock condition was detected or the current thread already owns the read-write lock for writing.
>
> These functions shall not return an error code of [EINTR].

But the thing is, POSIX error sections are not exhaustive: https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_03

> Implementations may generate error numbers listed here under circumstances other than those described, if and only if all those error conditions can always be treated identically to the error conditions as described in this volume of POSIX.1-2017. Implementations shall not generate a different error number from one required by this volume of POSIX.1-2017 for an error condition described in this volume of POSIX.1-2017, but may generate additional errors unless explicitly disallowed for a particular function.

And even the docs for that function mention "shall not return an error code of [EINTR]" rather than "shall not return any other error code".  So unless there's limits documented elsewhere, I don't think it's sound to assume that there can't be another error code returned from these functions.

CC: @RalfJung

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
This PR fixed a very old issue https://github.com/rust-lang/rust/issues/94705 to clarify and improve the POSIX error checking, and some of the checks are skipped because can have no benefit, but I'm sure that this can open some interesting discussion.

Fixes https://github.com/rust-lang/rust/issues/94705

cc: @tavianator
cc: @cuviper

### CODE REVIEW

File: library/std/src/sys/unix/thread.rs [hunk 1]
```diff
@@ -112,8 +112,7 @@ impl Thread {
     }
 
     pub fn yield_now() {
-        let ret = unsafe { libc::sched_yield() };
-        debug_assert_eq!(ret, 0);
+        let _ = unsafe { libc::sched_yield() };
```
Comment (5225225) [inline library/std/src/sys/unix/thread.rs:115]: Intentionally ignoring the return value here? If so, we should probably leave a comment about it.

File: library/std/src/sys/unix/fs.rs [hunk 2]
```diff
@@ -640,7 +640,10 @@ impl Iterator for ReadDir {
 impl Drop for Dir {
     fn drop(&mut self) {
         let r = unsafe { libc::closedir(self.0) };
-        debug_assert_eq!(r, 0);
+        // a close_dir operation can fail also with EINTR error code
+        // that means that the operation was interrupted by a signal,
+        // and this can be an accepted case.
+        assert!(r == 0 || r == libc::EINTR, "unexpected error during closedir: {:?}", r);
```
Comment (5225225) [inline library/std/src/sys/unix/fs.rs:646]: We might want to use `std::io::Error::last_os_error` here (and elsewhere) if the assert fails, since according to the docs, `closedir` just returns `-1` on failure, which doesn't explain *what* happened.

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: I'm not able to catch your suggestion elsewhere and why to use _probably_ `std::io::Error::last_os_error` can you give a motivation that can convince me?

Comment (5225225) [reply library/std/src/sys/unix/fs.rs:646]: Well, we're showing `r` to the user here. But according to the `closedir` manual, it will only ever return either 0 or -1. So if this assert fails, it will never be anything other than -1, as far as I can see?

> The closedir() function returns 0 on success.  On error, -1 is returned, and errno is set to indicate the error.

(https://linux.die.net/man/3/closedir) (And EINTR doesn't *seem* to be a possible return, especially since that's presumably returned in `errno`, not directly)

File: library/std/src/sys/unix/thread.rs (hunk 1 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/thread.rs:115]: Still thinking that this makes sense, open a PR to have some review from @tavianator that looks like having some strong opinion on it.

I personally like an assertion here because if something bad happens I can find it, but in this case when something bad happens if is it useful to know this info?

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: This should contain the complete list https://pubs.opengroup.org/onlinepubs/007904975/functions/closedir.html 

But I'm still unable to catch why `std::io::Error::last_os_error` and also this will be an API breaking change no?

Comment (5225225) [reply library/std/src/sys/unix/fs.rs:646]: Oh, i'm not saying to return the error as a Result, i'm saying to panic with that error, instead of panicking with `r`. Because closedir will only ever return -1 or 0, it can never return EINTR. That goes in errno.

So if you want to ignore EINTR, you need to check errno anyways.

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: we are interested in `r` in this case because we want to know why we are failing, and maybe different Unix systems can return different `r` value and we want to know this!

Comment (tavianator) [reply library/std/src/sys/unix/fs.rs:646]: No, @5225225 is right, the error code is in `errno` not `r`:

> ```
> RETURN VALUE
>        Upon successful completion, closedir() shall return 0; otherwise, -1 shall be returned
>        and errno set to indicate the error.
> ```

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: While waiting for the performance resolution I will be back on this point!

I think I misunderstood the review from the beginning, and my mind was convinced that `r` was the last error.

Now each time that we have a failure we should do something like

```rust
assert_eq!(r, 0, "unexpected error: {:?}", std::io::Error::last_os_error());
```

let's see what the performance result is and we will try to run another time with these changes!

Apologize for the misunderstood here @5225225

File: library/std/src/sys/unix/locks/futex_rwlock.rs [hunk 3]
```diff
@@ -95,7 +95,11 @@ impl RwLock {
 
         // It's impossible for a reader to be waiting on a read-locked RwLock,
         // except if there is also a writer waiting.
-        debug_assert!(!has_readers_waiting(state) || has_writers_waiting(state));
+        assert!(
```
Comment (thomcc) [inline library/std/src/sys/unix/locks/futex_rwlock.rs:98]: I'm not sure the changes to this file are good. These are impossible states -- they are also pretty hot functions (and they won't necessarily be covered by perf, given that rustc is largely single threaded) which are marked as `#[inline]`, The formatting here will end up with a bunch of additional code in the bodies from the formatting, which will often result in them not getting inlined.

So, I think this should stick to cases where it's checking the result of a syscall. That seems much more justifiable, since those cases are likely not going to be nearly as hot anyway.

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (thomcc) [reply library/std/src/sys/unix/fs.rs:646]: Panicking in Drop is a bit dodgy, since if we're already panicking, it will abort.

@saethlin pointed out on discord that we could fail to close the directory for a decently sized number of reasons (the fd was closed already, IO errors especially on a network filesystem, ...), none of which are such flaws as to justify aborting the process, and elsewhere we have precedent that dropping `File` ignores all errors.

File: library/std/src/sys/unix/thread.rs (hunk 1 above)
Comment (saethlin) [reply library/std/src/sys/unix/thread.rs:115]: This function is documented to be infallible on Linux, but on BSDs it is documented to be able to fail with ENOSYS, if this system call is not enabled. This is a perfect place for a debug assertion.

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: I'm not able to access the `rustc-dev` on discord, so I can not follow the discussion, but I like to keep the same behavior across all the API.

I'm having a hard time to understand when we need to panic or skip panic, looks like a local choice for each call, but I think it is possible to scratch some high-level rules?

Like:
- "Ignore all errors where there are different error causes" like the one in the `File`;
- "using assert instead of debug_assert if os `error` is involved";
- "using debug_assert when the sys call returns a specific error code".

I see this pattern in the review of this PR, but maybe I'm wrong and missing something.

I can have a pointer of the ignore error in the `File`?

File: library/std/src/sys/unix/thread.rs (hunk 1 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/thread.rs]: Reintrodiced!

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (thomcc) [reply library/std/src/sys/unix/fs.rs:646]: Using assert in Drop is always dodgy -- it can crash the process. The reason `debug_assert` is permitted is mostly because libstd doesn't ship with debug assertions enabled.

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs:646]: So, the option here is:

- continue to use debu_assert and improve the error with a `std::io::Error::last_os_error()`
- skip the check at all?

Comment (thomcc) [reply library/std/src/sys/unix/fs.rs:646]: Continue debug_assert and using `std::io::Error::last_os_error()` sounds fine.

File: library/std/src/sys/unix/locks/pthread_mutex.rs [hunk 4]
```diff
@@ -113,6 +113,7 @@ impl Mutex {
         // Once it is used (locked/unlocked) or pthread_mutex_init() is called,
         // this behaviour no longer occurs.
         debug_assert!(r == 0 || r == libc::EINVAL);
```
Comment (thomcc) [inline library/std/src/sys/unix/locks/pthread_mutex.rs:115]: You shouldn't have both `debug_assert` and `assert` here. If were going to assert, you should delete the debug_assert.

I'm still hesitant about this one also, since it will be called from a drop impl as well.

File: library/std/src/sys/unix/fs.rs (hunk 2 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/fs.rs]: >Continue debug_assert and using std::io::Error::last_os_error() sounds fine.

Done, not sure if my tentative to avoid evaluating std::io::Error::last_os_error() always is a good thing, but happy to receive feedback on how to improve the code!

If you think that this PR is good enough maybe we can give it a run to see the performance? this change should not impact to at all I think, but not sure

File: library/std/src/sys/unix/locks/pthread_mutex.rs (hunk 4 above)
Comment (vincenzopalazzo) [reply library/std/src/sys/unix/locks/pthread_mutex.rs]: was just a copy and paste issue sorry about that! I do not think we need to move this in `assert` we have all the info inside r and we can check if it is right?

File: library/std/src/sys/unix/locks/pthread_condvar.rs [hunk 5]
```diff
@@ -172,7 +172,7 @@ impl Condvar {
         let mut sys_now = libc::timeval { tv_sec: 0, tv_usec: 0 };
         let stable_now = Instant::now();
         let r = libc::gettimeofday(&mut sys_now, ptr::null_mut());
-        debug_assert_eq!(r, 0);
+        assert_eq!(r, 0, "unexpected error: {:?}", std::io::Error::last_os_error());
```
Comment (tavianator) [inline library/std/src/sys/unix/locks/pthread_condvar.rs:175]: POSIX says `gettimeofday()` isn't allowed to fail: https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html.  I think it's okay to keep this as a debug assert.

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/locks/pthread_condvar.rs:175]: I make this because I read this https://man7.org/linux/man-pages/man2/gettimeofday.2.html that is the same linked [here](https://github.com/rust-lang/rust/pull/99624#discussion_r928030940)

What this is criteria of choice here? on what docs follow? I'm getting confused

Comment (Mark-Simulacrum) [reply library/std/src/sys/unix/locks/pthread_condvar.rs:175]: I think there's likely varying behaviors across platforms, but in general keeping the assert seems better to me.

Comment (vincenzopalazzo) [reply library/std/src/sys/unix/locks/pthread_condvar.rs:175]: yes I agree @Mark-Simulacrum different os can return different result due custom conf

**Comment by Amanieu** [comment]
I would prefer keeping these as `debug_assert`: POSIX says that these functions cannot fail, so these asserts would only trigger if we made a mistake in the call arguments (`EBADF`, `EFAULT`) or the system is fundamentally broken (in which case it is outside the scope of Rust's safety anyways).

Since these asserts will never fire in practice, panic-in-drop is irrelevant here.

**Comment by Mark-Simulacrum** [comment]
I think the main advantage to making them regular asserts is that for platforms were we'd otherwise have zero coverage -- e.g., tier 2 or 3 platforms. Those also seem the most likely to be platforms where we'd accidentally get the API wrong.

In general I think it makes sense to assert that we're doing the right thing at runtime, even in code we're shipping to end users.

**Comment by Amanieu** [comment]
In any case, this is irrelevant for panic-in-drop: if these asserts trigger then either the standard library is buggy or the platform is buggy. Either case is reasonable grounds for aborting the program.

@bors r+

**Comment by vincenzopalazzo** [comment]
I will look inside the error today!

File: library/std/src/sys/unix/fs.rs [hunk 6]
```diff
@@ -687,7 +687,11 @@ impl Iterator for ReadDir {
 impl Drop for Dir {
     fn drop(&mut self) {
         let r = unsafe { libc::closedir(self.0) };
-        debug_assert_eq!(r, 0);
+        assert!(
+            r == 0 || r == libc::EINTR,
```
Comment (tavianator) [inline library/std/src/sys/unix/fs.rs:691]: This is still wrong, `r` is never `EINTR`.  You need to check `errno`

**Review by tavianator — CHANGES_REQUESTED** [review]

**Comment by RalfJung** [comment]
> POSIX says that these functions cannot fail

That's the thing, just because POSIX doesn't list an error doesn't mean the function cannot raise the error -- error lists are not exhaustive. See https://github.com/rust-lang/rust/issues/94705.

**Comment by vincenzopalazzo** [comment]
I agree with you @RalfJung I do not care if the docs tell us that this will not fail at all, a sanity check is always good. 

However the majority of the review point in the way to do not add this promotion assert! I'm open to discuss it, but I think before reopen the issue we need to converge on trusting the POSIX docs or not otherwise work on this simple change will be super confusing because i like a ping pong game you add and revert the change!

**Comment by RalfJung** [comment]
The issue should remain open until we decided for good one way or the other, but I agree that things should be discussed on the issue before another PR is opened.
