### PR TITLE
std: Synchronize access to global env during `exec` 

### LINKED ISSUE #46775: std::os::unix::process::CommandExt::exec should be unsafe
This method assigns to `environ` outside of any lock, meaning that it's automatically unsafe for multi-threaded programs.

For single-threaded programs, if the `exec` fails, `environ` will point to memory that has been freed. The [documentation](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.exec) gives a false sense of security:
> The process may be in a "broken state" if this function returns in error. For example the working directory, environment variables, signal handling settings, various user/group information, or aspects of stdio file descriptors may have changed.

### LINKED ISSUE #55775: Regression in `Command::exec`'s PATH resolution
Using `env_clear()` + `exec()` currently exhibits different behaviour on nightly and stable.

I believe the first nightly to regress was `2018-11-02`.

A minimal reproduction is the following code:

```rust
use std::process::Command;
use std::os::unix::process::CommandExt;

fn main() {
    let mut cmd = Command::new("true");
    cmd.env_clear();
    let err = cmd.exec();
    println!("error: {}", err);
}
```

On stable, it prints no error. On nightly, it prints `error: No such file or directory (os error 2)`.

Using `strace -e trace=execve`, we can see the difference:

```
# stable
execve("/bin/true", ["true"], 0x7fedf1821010 /* 0 vars */) = 0
# nightly
execve("true", ["true"], 0x561a58edbb80 /* 0 vars */) = -1 ENOENT (No such file or directory)
```

## Meta

```
$ rustc --version --verbose
rustc 1.32.0-nightly (15d770400 2018-11-06)
binary: rustc
commit-hash: 15d770400eed9018f18bddf83dd65cb7789280a5
commit-date: 2018-11-06
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit, after reverting #55359, applies a different fix for #46775
while also fixing #55775. The basic idea was to go back to pre-#55359
libstd, and then fix #46775 in a way that doesn't expose #55775.

The issue described in #46775 boils down to two problems:

* First, the global environment is reset during `exec` but, but if the
  `exec` call fails then the global environment was a dangling pointer
  into free'd memory as the block of memory was deallocated when
  `Command` is dropped. This is fixed in this commit by installing a
  `Drop` stack object which ensures that the `environ` pointer is
  preserved on a failing `exec`.

* Second, the global environment was accessed in an unsynchronized
  fashion during `exec`. This was fixed by ensuring that the
  Rust-specific environment lock is acquired for these system-level
  operations.

Thanks to Alex Gaynor for pioneering the solution here!

Closes #55775

### CODE REVIEW

File: src/test/run-pass/command-exec.rs [hunk 1]
```diff
@@ -84,4 +94,14 @@ fn main() {
     assert!(output.status.success());
     assert!(output.stderr.is_empty());
     assert_eq!(output.stdout, b"passed\n");
+
+    let output = Command::new(&me).arg("exec-test6").output().unwrap();
```
Comment (sfackler) [inline src/test/run-pass/command-exec.rs]: Are exec-test6 and exec-test7 identical?

Comment (alexcrichton) [reply src/test/run-pass/command-exec.rs]: I think morally yeah, they're just testing the two routes you can get at removing `PATH` from env (either by clearing or singularly removing it)

Comment (sfackler) [reply src/test/run-pass/command-exec.rs]: Oh I missed the path manipulation up above.

**Comment by alexcrichton** [comment]
@bors: p=5

we'll need to backport this to fix the beta-regression as well

**Comment by kennytm** [comment]
@bors p=83

rollup fairness

**Comment by kennytm** [comment]
@bors retry 

30 minutes timeout (9696)

**Comment by RalfJung** [comment]
> I think it's actually always been a bug that we don't call the exec* family of functions with the global env lock.

Don't they do the env modifications *after* forking, where they are the only thread, thus avoiding race conditions?

**Comment by kennytm** [comment]
🤔 Any chance this change causes dead-lock during doc tests?

**Comment by alexcrichton** [comment]
Yes this seems non spurious, I will investigate

**Comment by alexcrichton** [comment]
Oh right, if a process forks with the lock held in one thread we can't then try to acquire it later. This will.need to acquire the lock before the fork
