### PR TITLE
rustdoc: Don't load all extern crates unconditionally

### LINKED ISSUE #68427: rustdoc only: duplicate lang item `panic_halt`
This is a regression from `rustdoc 1.40.0 (73528e339 2019-12-16)` to `rustdoc 1.41.0-beta.3 (fb3056216 2020-01-19)`.

If rustdoc attempts to document a crate that has at least two dependencies which implement a `panic_handler`, it fails with an error similar to

```
error: duplicate lang item in crate `panic_halt` (which `panic2` depends on): `panic_impl`.
  |
  = note: first defined in crate `std` (which `panic2` depends on).
```

Note that the crate *builds* fine, it's just documenting that is broken.

---

**Steps to reproduce**

1. Create a new project, e.g. `cargo new panic2`
2. Add a dependency on `panic-halt = "0.2.0"`, e.g. `cargo add panic-halt`
3. Attempt to document the crate, e.g. `cargo doc`

<details><summary>An example of the different behavior between `stable`/`beta` and `build`/`doc`.</summary>

```shell
$ cargo +stable clean

$ cargo +beta clean

$ cargo +stable build
   Compiling panic-halt v0.2.0
   Compiling panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s

$ cargo +stable doc
 Documenting panic-halt v0.2.0
    Checking panic-halt v0.2.0
 Documenting panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 1.40s

$ cargo +beta build
   Compiling panic-halt v0.2.0
   Compiling panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s

$ cargo +beta doc
 Documenting panic-halt v0.2.0
    Checking panic-halt v0.2.0
 Documenting panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
error: duplicate lang item in crate `panic_halt` (which `panic2` depends on): `panic_impl`.
  |
  = note: first defined in crate `std` (which `panic2` depends on).

error: aborting due to previous error

error: Could not document `panic2`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type bin --crate-name panic2 src/main.rs -o /Users/logic/Projects/tmp/panic2/target/doc --error-format=json --json=diagnostic-rendered-ansi --document-private-items -L dependency=/Users/logic/Projects/tmp/panic2/target/debug/deps --extern panic_halt=/Users/logic/Projects/tmp/panic2/target/debug/deps/libpanic_halt-6d0ca720c3c355fb.rmeta` (exit code: 1)
```

</details>

### PR DESCRIPTION
**Pull request by jyn514**
Instead, only load the crates that are linked to with intra-doc links.

This doesn't help very much with any of rustdoc's fundamental issues
with freezing the resolver, but it at least fixes a stable-to-stable
regression, and makes the crate loading model somewhat more consistent
with rustc's. I tested and it unfortunately does not help at all with https://github.com/rust-lang/rust/pull/82496.

Closes https://github.com/rust-lang/rust/issues/68427. Opened https://github.com/rust-lang/rust/issues/83761 to track the more fundamental issues.
r? @petrochenkov cc @eddyb @ollie27

### CODE REVIEW

File: src/test/run-make/unused-extern-crate/panic-item.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+#[panic_handler]
+fn panic(_info: &PanicInfo) -> ! {
+    loop {
+        atomic::compiler_fence(Ordering::SeqCst);
+    }
+}
+
+#[lang = "eh_personality"]
+fn foo() {}
```
Comment (petrochenkov) [inline src/test/run-make/unused-extern-crate/panic-item.rs:15]: I think this can be a regular UI test.

File: src/librustdoc/core.rs [hunk 2]
```diff
@@ -348,42 +349,65 @@ crate fn create_config(
...
+            if let Some(doc) = attr.doc_str() {
+                for MarkdownLink { link, .. } in markdown_links(&doc.as_str()) {
+                    // FIXME: this misses a *lot* of the preprocessing done in collect_intra_doc_links
+                    // I think most of it shouldn't be necessary since we only need the crate prefix?
+                    let path_str = match Disambiguator::from_str(&link) {
+                        Ok(x) => x.map_or(link.as_str(), |(_, p)| p),
+                        Err(_) => continue,
+                    };
+                    self.resolver.borrow_mut().access(|resolver| {
+                        let _ = resolver.resolve_str_path_error(
```
Comment (petrochenkov) [inline src/librustdoc/core.rs:380]: If you save the resolution results for later instead of throwing them away, then you'll no longer need the resolver later on.
That's basically the idea behind fixing the resolver cloning/freezing issue.

**Comment by petrochenkov** [comment]
>Let me know if you want me to open a separate issue for not freezing the resolver.

Yes, could you create the issue?
The fix is to pretty much do what this PR does but more extensively - resolve everything that needs to be resolved early and save the results for later.
Once `Resolver::clone_outputs` is removed the problem can be considered fixed.

File: src/test/run-make/unused-extern-crate/panic-item.rs (hunk 1 above)
Comment (jyn514) [reply src/test/run-make/unused-extern-crate/panic-item.rs]: Thanks, done.

**Comment by jyn514** [comment]
> Yes, could you create the issue?

Sure thing, I opened https://github.com/rust-lang/rust/issues/83761. I left a question about the approach, but it's not related to this PR.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/83778#issuecomment-812472514
@bors r-

**Comment by jyn514** [comment]
The error doesn't make sense to me:
```
error: auxiliary build of "D:\\a\\rust\\rust\\src/test\\rustdoc-ui\\auxiliary\\panic-item.rs" failed to compile: 
error: linking with `link.exe` failed: exit code: 1120
   = note:    Creating library D:\a\rust\rust\build\i686-pc-windows-msvc\test\rustdoc-ui\unused-extern-crate\auxiliary\panic_item.dll.lib and object D:\a\rust\rust\build\i686-pc-windows-msvc\test\rustdoc-ui\unused-extern-crate\auxiliary\panic_item.dll.exp
           LINK : error LNK2001: unresolved external symbol __DllMainCRTStartup@12
           libcompiler_builtins-7c5b31ab71d8ac29.rlib(compiler_builtins-7c5b31ab71d8ac29.compiler_builtins.9vzca8r7-cgu.61.rcgu.o) : error LNK2019: unresolved external symbol __alldiv referenced in function __ZN51_$LT$i64$u20$as$u20$compiler_builtins..int..Int$GT$12aborting_div17h904dfe06db60aae9E
```
@petrochenkov can I only use aux-build or aux-crate but not both, or something? I can't reproduce the failure on linux.

**Comment by petrochenkov** [comment]
@jyn514 
Try using `// no-prefer-dynamic` in `auxiliary/panic-item.rs`.
Auxiliary libraries for tests are built as dylibs by default, and `#![no_std]` dylibs require linking in some additional stuff on Windows to work.

**Comment by jyn514** [comment]
Ok, I added that. Not sure how to test it worked from linux. I also had to add `crate_type = "lib"` or it gave a weird error about conflicting outputs:
```
error: the generated executable for the input file "/home/joshua/rustc3/src/test/rustdoc-ui/auxiliary/panic-item.rs" conflicts with the existing directory "/home/joshua/rustc3/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/unused-extern-crate/auxiliary/panic-item"
```

**Comment by klensy** [comment]
Somehow this works good for cargo-doc, but not for other:
https://perf.rust-lang.org/compare.html?start=ccd997592bf545fc54a9cce31f1280f833915ba1&end=640ce99bfe70375a24c6775a937d6a258b40398b&stat=instructions%3Au

**Comment by jyn514** [comment]
@klensy this is a bug fix - it doesn't really matter what the performance is as long as it's not a giant regression. Cargo is probably lower because it has a lot of `--extern` crates that no longer need to be lower.

**Comment by klensy** [comment]
@jyn514 No, i mean, look at `-doc` full builds: for `cargo-doc` there some changes in `executions delta` column, but literally zero changes for others in that column (didn't checked all of them).

**Comment by jyn514** [comment]
I don't understand what you're trying to tell me. On the "detailed self profile results" page I see no change in time, which is what I'd expect from this PR. If there's an inconsistency between that and instructions that sounds like an issue with perf.rlo, I think there's some ongoing work to measure instructions for self-profile.

**Comment by klensy** [comment]
`cargo-doc`: https://perf.rust-lang.org/detailed-query.html?commit=640ce99bfe70375a24c6775a937d6a258b40398b&base_commit=ccd997592bf545fc54a9cce31f1280f833915ba1&benchmark=cargo-doc&run_name=full , `Executions delta` diff not zero

any(?) other `-doc` profile : `Executions delta` equal to zero
https://perf.rust-lang.org/detailed-query.html?commit=640ce99bfe70375a24c6775a937d6a258b40398b&base_commit=ccd997592bf545fc54a9cce31f1280f833915ba1&benchmark=clap-rs-doc&run_name=full
https://perf.rust-lang.org/detailed-query.html?commit=640ce99bfe70375a24c6775a937d6a258b40398b&base_commit=ccd997592bf545fc54a9cce31f1280f833915ba1&benchmark=regex-doc&run_name=full
https://perf.rust-lang.org/detailed-query.html?commit=640ce99bfe70375a24c6775a937d6a258b40398b&base_commit=ccd997592bf545fc54a9cce31f1280f833915ba1&benchmark=webrender-doc&run_name=full

>If there's an inconsistency between that and instructions that sounds like an issue with perf.rlo, I think there's some ongoing work to measure instructions for self-profile.

Or `cargo-doc` works somehow special, or it issue with profiler, yes.

**Comment by Mark-Simulacrum** [comment]
Those runs suggest that there is some difference in the documented code for cargo and clap-rs, and this particular PR sees a larger improvement in terms of less queries being run on the cargo benchmark (compared to the other ones you've cited). That's not really a problem, it's pretty intentional that our benchmarks differ in what they look like to the compiler (otherwise there'd be no point in having two different ones) -- I'm trying to understand what problem or note you're trying to make :)
