### PR TITLE
Check for negative impls when finding auto traits

### LINKED ISSUE #55321: ICE in cargo doc with optin_builtin_traits
Hi, I noticed a weird internal error using `cargo doc`. The smallest example I could make to reproduce the bug is an basic library project (`cargo init --lib`) whose lib.rs contains:
```rust
#![feature(optin_builtin_traits)]

// the bug doesn't occur if the declaration of B is moved here

pub struct A();

// the bug still happens if the declaration of B is moved here

impl !Send for A {}
impl !Sync for A {}

pub struct B<T: ?Sized>(A, Box<T>);
```
`cargo build`, `cargo build --release`, and `cargo check` all work fine; and as mentioned in the code, the place where `B` is declared seems to matter.

Here is the output and trace of `cargo doc --verbose`: [log was from an out of date nightly rust, see my comment below for the log for the latest nightly as of this edit]

Have a nice day.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #55321

When AutoTraitFinder begins examining a type, it checks for an explicit
negative impl. However, it wasn't checking for negative impls found when
calling 'select' on predicates found from nested obligations.

This commit makes AutoTraitFinder check for negative impls whenever it
makes a call to 'select'. If a negative impl is found, it immediately
bails out.

Normal users of SelectioContext don't need to worry about this, since
they stop as soon as an Unimplemented error is encountered. However, we
add predicates to our ParamEnv when we encounter this error, so we need
to handle negative impls specially (so that we don't try adding them to
our ParamEnv).

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @nikomatsakis: This PR requires your review.

**Comment by QuietMisdreavus** [comment]
Beta-nominating since the ICE this is fixing is on stable (and has been for a while).

File: src/librustc/traits/auto_trait.rs [hunk 1]
```diff
@@ -338,6 +338,21 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
 
             match &result {
                 &Ok(Some(ref vtable)) => {
+                    // If we see an explicit negative impl (e.g. 'impl !Send for MyStruct'),
+                    // we immediately bail out, since it's impossible for us to continue'
```
Comment (varkor) [inline src/librustc/traits/auto_trait.rs]:
```suggestion
                    // we immediately bail out, since it's impossible for us to continue.
```

**Review by nikomatsakis — APPROVED** [review]

**Comment by nagisa** [comment]
We have decided to not backport this fix. It fixes a stable-to-stable regression that involves an unstable feature. Since it hasn’t been noticed for such a long time, it does not appear to be important enough to warrant a backport.
