### PR TITLE
Make std::sync::Arc compatible with ThreadSanitizer

### LINKED ISSUE #39608: ThreadSanitizer detects a data race in the test runner (`rustc --test`)
iff the crate contains two or more unit tests.

### STR

```
$ cargo new --lib test-runner && cd $_

$ edit src/lib.rs && cat $_
```

``` rust
#[test]
fn foo() {}

#[test]
fn bar() {}
```

```
$ RUSTFLAGS="-Z sanitizer=thread" cargo test --target x86_64-unknown-linux-gnu                                                                                                                                   <<<
     Running target/x86_64-unknown-linux-gnu/debug/deps/test_runner-d861d6557762b235

running 2 tests
test bar ... ok
test foo ... ok
==================
WARNING: ThreadSanitizer: data race (pid=30969)
  Write of size 8 at 0x7c4c0000ed90 by thread T2:
    #0 free $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:634 (test_runner-d861d6557762b235+0x0000000ce207)
    #1 __rust_deallocate <null> (test_runner-d861d6557762b235+0x000000155663)
    #2 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hffd2bcc3b04fe791 <null> (test_runner-d861d6557762b235+0x00000001b835)
    #3 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hffd2bcc3b04fe791 <null> (test_runner-d861d6557762b235+0x00000001b835)
    #4 drop::h62528215215ec760 <null> (test_runner-d861d6557762b235+0x000000029a65)
    #5 drop::h62528215215ec760 <null> (test_runner-d861d6557762b235+0x000000029a65)
    #6 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he23b8085b7ff608a <null> (test_runner-d861d6557762b235+0x00000002dc34)
    #7 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he23b8085b7ff608a <null> (test_runner-d861d6557762b235+0x00000002dc34)
    #8 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #9 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #10 __tsan_thread_start_func $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:892 (test_runner-d861d6557762b235+0x0000000caf0b)
    #11 __tsan_thread_start_func $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:892 (test_runner-d861d6557762b235+0x0000000caf0b)

  Previous atomic write of size 8 at 0x7c4c0000ed90 by main thread:
    #0 __tsan_atomic64_fetch_sub $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interface_atomic.cc:623 (test_runner-d861d6557762b235+0x0000001131b0)
    #1 drop::h62528215215ec760 <null> (test_runner-d861d6557762b235+0x000000029a33)
    #2 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288fd)
    #3 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288fd)
    #4 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288fd)
    #5 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288fd)
    #6 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060f65)
    #7 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060f65)
    #8 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060f65)
    #9 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #10 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x000000054a4a)
    #11 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #12 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #13 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #14 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #15 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #16 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #17 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #18 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #19 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #20 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #21 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #22 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

  Thread T2 'foo' (tid=30972, running) created by main thread at:
    #0 pthread_create $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:902 (test_runner-d861d6557762b235+0x0000000cf546)
    #1 std::sys::imp::thread::Thread::new::h59257a01c2b82abe <null> (test_runner-d861d6557762b235+0x0000000bc1ea)
    #2 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060cd2)
    #3 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #4 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #5 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x000000054a4a)
    #6 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #7 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #8 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #9 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #10 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #11 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #12 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #13 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #14 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #15 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #16 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #17 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

SUMMARY: ThreadSanitizer: data race ($PWD/target/x86_64-unknown-linux-gnu/debug/deps/test_runner-d861d6557762b235+0x155663) in __rust_deallocate
==================
==================
WARNING: ThreadSanitizer: data race (pid=30969)
  Write of size 8 at 0x7c580000ef40 by main thread:
    #0 free $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:634 (test_runner-d861d6557762b235+0x0000000ce207)
    #1 __rust_deallocate <null> (test_runner-d861d6557762b235+0x000000155663)
    #2 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hc07f22e2b818fd5e <null> (test_runner-d861d6557762b235+0x00000001b234)
    #3 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hc07f22e2b818fd5e <null> (test_runner-d861d6557762b235+0x00000001b234)
    #4 drop::hd5322f45aa23e49d <null> (test_runner-d861d6557762b235+0x00000002c005)
    #5 drop::hd5322f45aa23e49d <null> (test_runner-d861d6557762b235+0x00000002c005)
    #6 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #7 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #8 drop::ha932b14572fc49af <null> (test_runner-d861d6557762b235+0x00000002ae22)
    #9 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x0000000588b1)
    #10 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x0000000588b1)
    #11 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x0000000588b1)
    #12 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #13 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #14 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #15 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #16 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #17 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #18 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #19 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #20 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #21 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #22 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #23 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

  Previous atomic write of size 8 at 0x7c580000ef40 by thread T2:
    #0 __tsan_atomic64_fetch_sub $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interface_atomic.cc:623 (test_runner-d861d6557762b235+0x0000001131b0)
    #1 drop::hd5322f45aa23e49d <null> (test_runner-d861d6557762b235+0x00000002bfd3)
    #2 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #3 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #4 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #5 drop::hb2fbb6e76af21657 <null> (test_runner-d861d6557762b235+0x00000002b98e)
    #6 drop::ha932b14572fc49af <null> (test_runner-d861d6557762b235+0x00000002ae22)
    #7 std::panicking::try::do_call::heac7d42b6d137ab0 <null> (test_runner-d861d6557762b235+0x00000001e7a7)
    #8 std::panicking::try::do_call::heac7d42b6d137ab0 <null> (test_runner-d861d6557762b235+0x00000001e7a7)
    #9 std::panicking::try::do_call::heac7d42b6d137ab0 <null> (test_runner-d861d6557762b235+0x00000001e7a7)
    #10 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #11 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #12 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #13 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he23b8085b7ff608a <null> (test_runner-d861d6557762b235+0x00000002db21)
    #14 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::he23b8085b7ff608a <null> (test_runner-d861d6557762b235+0x00000002db21)
    #15 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #16 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #17 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #18 std::sys::imp::thread::Thread::new::thread_start::hee5c0f50902195ab <null> (test_runner-d861d6557762b235+0x0000000bcacc)
    #19 __tsan_thread_start_func $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:892 (test_runner-d861d6557762b235+0x0000000caf0b)
    #20 __tsan_thread_start_func $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:892 (test_runner-d861d6557762b235+0x0000000caf0b)

  Thread T2 'foo' (tid=30972, running) created by main thread at:
    #0 pthread_create $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:902 (test_runner-d861d6557762b235+0x0000000cf546)
    #1 std::sys::imp::thread::Thread::new::h59257a01c2b82abe <null> (test_runner-d861d6557762b235+0x0000000bc1ea)
    #2 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060cd2)
    #3 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #4 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #5 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x000000054a4a)
    #6 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #7 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #8 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #9 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #10 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #11 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #12 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #13 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #14 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #15 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #16 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #17 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

SUMMARY: ThreadSanitizer: data race ($PWD/target/x86_64-unknown-linux-gnu/debug/deps/test_runner-d861d6557762b235+0x155663) in __rust_deallocate
==================

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured

==================
WARNING: ThreadSanitizer: data race (pid=30969)
  Write of size 8 at 0x7c540000ef60 by thread T2:
    #0 free $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:634 (test_runner-d861d6557762b235+0x0000000ce207)
    #1 __rust_deallocate <null> (test_runner-d861d6557762b235+0x000000155663)
    #2 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hff346d8fec1237f8 <null> (test_runner-d861d6557762b235+0x00000009fbc4)
    #3 _$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::hff346d8fec1237f8 <null> (test_runner-d861d6557762b235+0x00000009fbc4)
    #4 drop::h5f9d93ca09665cd2 <null> (test_runner-d861d6557762b235+0x0000000a395d)
    #5 drop::h5f9d93ca09665cd2 <null> (test_runner-d861d6557762b235+0x0000000a395d)
    #6 drop::h1a3c63fc24632ae0 <null> (test_runner-d861d6557762b235+0x0000000a34bf)
    #7 drop::h1a3c63fc24632ae0 <null> (test_runner-d861d6557762b235+0x0000000a34bf)
    #8 drop::h1a3c63fc24632ae0 <null> (test_runner-d861d6557762b235+0x0000000a34bf)
    #9 std::sys::imp::fast_thread_local::destroy_value::hd0a16359cb28bafd <null> (test_runner-d861d6557762b235+0x0000000b9518)
    #10 std::sys::imp::fast_thread_local::destroy_value::hd0a16359cb28bafd <null> (test_runner-d861d6557762b235+0x0000000b9518)
    #11 std::sys::imp::fast_thread_local::destroy_value::hd0a16359cb28bafd <null> (test_runner-d861d6557762b235+0x0000000b9518)
    #12 __GI___call_tls_dtors <null> (libc.so.6+0x000000035efe)
    #13 __GI___call_tls_dtors <null> (libc.so.6+0x000000035efe)
    #14 __GI___call_tls_dtors <null> (libc.so.6+0x000000035efe)

  Previous atomic write of size 8 at 0x7c540000ef60 by main thread:
    #0 __tsan_atomic64_fetch_sub $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interface_atomic.cc:623 (test_runner-d861d6557762b235+0x0000001131b0)
    #1 drop::h76fdafd6e6eb83b7 <null> (test_runner-d861d6557762b235+0x00000002a0fb)
    #2 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288e9)
    #3 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288e9)
    #4 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288e9)
    #5 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288e9)
    #6 drop::h26c9032b0f649bf6 <null> (test_runner-d861d6557762b235+0x0000000288e9)
    #7 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060f65)
    #8 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060f65)
    #9 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #10 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x000000054a4a)
    #11 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #12 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #13 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #14 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #15 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #16 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #17 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #18 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #19 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #20 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #21 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #22 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

  Thread T2 'foo' (tid=30972, running) created by main thread at:
    #0 pthread_create $RUST_SRC/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:902 (test_runner-d861d6557762b235+0x0000000cf546)
    #1 std::sys::imp::thread::Thread::new::h59257a01c2b82abe <null> (test_runner-d861d6557762b235+0x0000000bc1ea)
    #2 test::run_test::run_test_inner::h68ccb59ad7634829 <null> (test_runner-d861d6557762b235+0x000000060cd2)
    #3 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #4 test::run_test::hbe43efe8762b5fcb <null> (test_runner-d861d6557762b235+0x00000005f4bd)
    #5 test::run_tests::h007db7d7a30e05b9 <null> (test_runner-d861d6557762b235+0x000000054a4a)
    #6 test::run_tests_console::h51b8f804fcc03777 <null> (test_runner-d861d6557762b235+0x00000004db4c)
    #7 test::test_main::h30f1de6986f689a9 <null> (test_runner-d861d6557762b235+0x0000000429d0)
    #8 test::test_main_static::h2d9326de74ff96ef <null> (test_runner-d861d6557762b235+0x000000043fe3)
    #9 test_runner::__test::main::h164d7dfa966cbb3f $PWD/src/lib.rs:1 (test_runner-d861d6557762b235+0x000000011362)
    #10 std::panicking::try::do_call::hb1cd11518796216e <null> (test_runner-d861d6557762b235+0x0000000be876)
    #11 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #12 __rust_maybe_catch_panic <null> (test_runner-d861d6557762b235+0x0000000c2363)
    #13 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #14 std::rt::lang_start::h0661a76cd511ea2d <null> (test_runner-d861d6557762b235+0x0000000c0487)
    #15 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #16 main <null> (test_runner-d861d6557762b235+0x0000000113b7)
    #17 main <null> (test_runner-d861d6557762b235+0x0000000113b7)

SUMMARY: ThreadSanitizer: data race ($PWD/target/x86_64-unknown-linux-gnu/debug/deps/test_runner-d861d6557762b235+0x155663) in __rust_deallocate
==================
ThreadSanitizer: reported 3 warnings
error: test failed
```

### Meta

**TODO** Sanitizers are not yet in tree. (cf. #38699)

---

cc @alexcrichton @brson

### PR DESCRIPTION
**Pull request by tmiasko**
The memory fences used previously in Arc implementation are not properly
understood by thread sanitizer as synchronization primitives. This had
unfortunate effect where running any non-trivial program compiled with
`-Z sanitizer=thread` would result in numerous false positives.

Replace acquire fences with acquire loads to address the issue.

Fixes #39608.

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @jhjourdan who did the formal verification of current `Arc`

**Comment by RalfJung** [comment]
I don't think I know the correctness argument of `Arc` well enough to review this on my own -- I have never tried to convince myself of its correctness. Some of my colleagues did though, I am trying to get them to help.

Do we have anyone else who is enough of an expert in weak memory to help? IIRC @aturon wrote most of this, but they are busy with other things these days.

**Comment by RalfJung** [comment]
Looking at the changes, this seems to mostly un-do deliberate optimizations that specifically keep synchronization to the absolute minimum that is necessary. I am not sure if "sanitizers do not properly support fences" is a good enough argument to change our code -- shouldn't sanitizers be fixed instead? Fences are an important part of Rust's and C's concurrency model.

I feel before we do a correctness review, we need a policy decision by *some* team (T-libs, I assume) whether we are willing to reduce code quality in order to help sanitizers.

**Comment by tmiasko** [comment]
AFAIK there are no known algorithmic approaches supporting memory barriers with
practical runtime overhead. Presuming that thread sanitizer should be fixed is
no solution, other approaches might be. For example, a conditional compilation
would be another thing to consider (if that is more agreeable?).

Changes here have no effect on tier 1, since generated code on i686 / x86_64 is
unaffected. On aarch64 assembly changes roughly reflect those made in the code,
i.e., `dmb ishld` is removed and `ldxr` is replaced with `ldaxr`.

I also mentioned other implementations (libc++ / libstdc++) as implicit
reflection of their views on the trade-offs involved. Personally I find thread
sanitizer to be invaluable, and if the only thing to make it work correctly is
to change standalone memory fence to an operation on concrete memory location, the
decision to me is clear. This is especially true here, since the issue is
limited to `Arc`.

**Comment by RalfJung** [comment]
> Changes here have no effect on tier 1, since generated code on i686 / x86_64 is
unaffected.

Did you test that? I know that lowering of atomic operations to x86 assembly is the same, but this change *will* affect compiler transformations even on x86. So there can still easily be differences.

**Comment by tmiasko** [comment]
I extracted the code form Arc (before and after changes) and examined
assembly. On i686 / x86_64 the difference was disappearance of `#MEMBARRIER`
compiler marker after changes, which is actually promising.

**Comment by RalfJung** [comment]
> AFAIK there are no known algorithmic approaches supporting memory barriers with
practical runtime overhead.

Interesting. I thought I new that these fences are equivalent to doing a release-acquire RMW from a global location, which would be trivial to check algorithmically (assuming a release/acquire checker is already implemented) but I may misremember.

> I extracted the code form Arc (before and after changes) and examined
assembly. On i686 / x86_64 the difference was disappearance of #MEMBARRIER
compiler marker after changes, which is actually promising.

Thanks, that is useful.

---

So, the nominated question here for @rust-lang/libs is: we have a trade-off here between (a) keeping the existing, highly optimized, well-reviewed and even formally analyzed code, which however at least current dynamic thread sanitizers cannot handle properly, and (b) changing this code to be less efficient in theory due to stronger synchronization, but ultimately simpler for the same reason (and with likely no perf change in practice), working better with thread sanitizers, but also changing extremely subtle code that is very well-tested (any change has some risk of introducing a bug) and losing the existing formal results. What do you think we should do? I am asking you because I don't think I should make such calls.

My personal feeling is: I am a big fan of sanitizers, so it seems worth sacrificing some entirely theoretical performance benefit of the current code for better testability. However, losing the existing formal analyses is an unfortunate regression. That said, comparing the assembly gives some assurance that at least for simple clients, the behavior did not change.

**Comment by Amanieu** [comment]
I would like to benchmark this on ARM first since that platform seems to be affected. The main issue here is that we will have to unconditional emit an acquire fence even if the ref count isn't dropping to zero.

**Comment by Amanieu** [comment]
I ran a quick benchmark comparison of `fetch_sub(Release)` and `fetch_sub(AcqRel)` but couldn't fine a difference in performance (they both report a consistent 20ns). I did check the assembly and `Release` uses `ldxr` while `AcqRel` uses `ldaxr`, and that is the only difference.

In theory `ldaxr` is slower than `ldxr` since it acts as an acquire barrier which prevents loads after it from being executed before it in an out-of-order CPU. I guess this isn't visible in this benchmark since there are no other loads.

**Comment by joshtriplett** [comment]
On Thu, Oct 10, 2019 at 10:21:34AM -0700, Amanieu wrote:
> I ran a quick benchmark comparison of `fetch_sub(Release)` and `fetch_sub(AcqRel)` but couldn't fine a difference in performance (they both report a consistent 20ns). I did check the assembly and `Release` uses `ldxr` while `AcqRel` uses `ldaxr`, and that is the only difference.
> 
> In theory `ldaxr` is slower than `ldxr` since it acts as an acquire barrier which prevents loads after it from being executed before it in an out-of-order CPU. I guess this isn't visible in this benchmark since there are no other loads.

Right; in general you have to take care in benchmarking atomic
operations and synchronized operations, as their costs depend greatly on
other operations in the same CPU's pipeline, and on the cache state of the
system (which depends on ongoing operations on other CPUs).

**Comment by alexcrichton** [comment]
The comments in the code indicate where all this logic originally came from (Boost) and its history also shows that this is an extremely sensitive operation for performance (see https://github.com/rust-lang/rust/pull/41714 for example). Benchmarking this change to evaluate its performance impact would be quite difficult, but leaning on users who have previously benchmarked various changes here (such as Servo/Gecko) is a good start.

I don't think that the correctness of the current code is in question, this looks like it's a change intended on making `Arc` compatible with the thread sanitizer. Given that it may be a regression in performance to an operation that is quite sensitive to performance I would personally prefer to not merge this PR as-is until sufficient data is gathered showing that this *isn't* a performance regression. If it is indeed a performance regression, or if data does not wish to be gathered, then landing this would indeed require some form of conditional compilation, but that is also somewhat hard to do since this is already quite tricky code to read, and adding a conditional path for only-rarely-used thread sanitization isn't necessarily great.

**Comment by JohnTitor** [comment]
Ping from triage: @rust-lang/libs @tmiasko any updates on this?

**Comment by pitdicker** [comment]
To summarize this PR is changing a few cases of:
```rust
fn drop(&mut self) {
    if self.inner().strong.fetch_sub(1, Release) != 1 {
        return;
    }
    atomic::fence(Acquire);
    /* drop contents of Arc */
}
```
to:
```rust
fn drop(&mut self) {
    if self.inner().strong.fetch_sub(1, AcqRel) != 1 {
        return;
    }
    /* drop contents of Arc */
}
```

This places an extra requirement to do an acquire synchronization in what may be hot code (cloning and dropping Arc references should be cheap). Before the acquire was in the colder path that drops the final reference of the Arc and drops the contents.

If avoiding fences is a goal, Something like https://github.com/rust-lang/rust/pull/41714 seems like the much better option to me. I.e. change the same code to:
```rust
fn drop(&mut self) {
    if self.inner().strong.fetch_sub(1, Release) != 1 {
        return;
    }
    let _ = self.inner().strong.load(Acquire);
    /* drop contents of Arc */
}
```
This keeps the hot path the same, and it adds at most an extra `mov` in the colder path.

I would actually feel better about an acquire load instead of a fence, because of the trickiness of fences ([Atmic-fence synchronisation](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence#Atomic-fence_synchronization)). Using a fence just to optimize out one instruction in a colder path seems like a questionable optimization. Especially because the processor knows just as good as we do that there are no other references to this atomic. So it can't have been changed in the meantime, and should still be in a register or cache. The `mov` should basically be free.

**Comment by pitdicker** [comment]
> Interesting. I thought I new that these fences are equivalent to doing a release-acquire RMW from a global location, which would be trivial to check algorithmically (assuming a release/acquire checker is already implemented) but I may misremember.

According to [Atomic-fence synchronization](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence#Atomic-fence_synchronization) a fence binds to a nearby atomic operation.

```rust
atomic_a.load(Relaxed);
atomic_b.store(Relaxed);
fence(Acquire);
atomic_b.load(Relaxed);
````

An acquire fence works together with the atomic that last did a load operation, in the example `atomic_a.load(Relaxed)`. In theory it only has to synchronize data with the other threads that did a release on `atomic_a`.

In the same vein `fence(Release)` works together with the store on an atomic right after.

The reordering rules for fences are carefully worded to not talk about themselves, but the previous read or the next write ([Acquire and Release Fences Don't Work the Way You'd Expect](https://preshing.com/20131125/acquire-and-release-fences-dont-work-the-way-youd-expect/)).

In all cases a fence needs operations on some atomic to bind to, a fence-fence synchronization without atomics does not seem to be a thing.

**Comment by RalfJung** [comment]
> In all cases a fence needs operations on some atomic to bind to, a fence-fence synchronization without atomics does not seem to be a thing.

Indeed, synchronization always arises from a reads-from edge. Fences can just "upgrade" relaxed reads/writes to still incur synchronization.

**Comment by JohnTitor** [comment]
Ping from triage: @tmiasko and @rust-lang/libs what do you think about the above comments?

**Comment by alexcrichton** [comment]
I think my [previous comment](https://github.com/rust-lang/rust/pull/65097#issuecomment-542240958) about a performance investigation still stands.

**Comment by tmiasko** [comment]
The approach suggested so far (including current implementation) are:

1. Use acquire fence (currently used in `std::sync::Arc`).
2. Use acquire load instead of acquire fence (current used in `servo_arc::Arc` for example).
3. Use acq-rel in fetch_sub, removing the fence.
4. Conditional compilation. I am not particularly fond of this approach, but
   this could be limited to a conditional definition of a single constant,
   i.e., ordering used with fetch_sub, while leaving memory fence in place.

I performed micro benchmarks on x86-64 (https://github.com/tmiasko/arc):

* 1 and 3 generate equivalent code, so there is nothing interesting to see there.
* When only fast path is involved (clone and drop, but refcount never reaches zero) the results of 1,2 and 3 are indistinguishable, as generated code is equivalent in that part.
* When only slow path is involved (create and immediately drop the arc) the results are:
  * 30 ns for 1 and 3
  * 39 ns for 2 (additional mov instructions)

@pitdicker I agree that the second approach would be preferable to the third
one from perspective of architectures with weaker memory models, while still
being compatible with tsan.

@alexcrichton I looked briefly at servo benchmarks (test-dromaeo, test-perf),
but generally as far as I can see the benchmarks are quite noisy, and
`std::sync::Arc` and `servo_arc::Arc` account for too little runtime, so any
changes like this are well within measurement error.

Unfortunately neither of those approaches is a Pareto improvement over current
state of affairs, so there is a trade-off involved.

**Comment by alexcrichton** [comment]
It's really difficult to measure the performance here unfortunately, and I think that focusing only on one architecture may be missing the purpose of these atomics as well. 

I also believe that (2) as you proposed is an incorrect solution because I believe that an acquire load only synchronizes with one release store, and the reason we use a fence is want to synchronize with all of the release stores, not just one.

**Comment by tmiasko** [comment]
> an acquire load only synchronizes with one release store, and the reason we use a fence is want to synchronize with all of the release stores, not just one.

Note that atomic operation A that performs an acquire operation synchronizes not
only with atomic operation B it reads value from (when B performs a release
operation), but with any release operation C such that release sequence headed
by C includes B.

Release sequences are formed from contiguous sequences of atomic
read-modify-write operations on the object. In the case of a counter, after
an initialization all modifications will be of this kind, which guarantees
synchronization with all release operations.

**Comment by alexcrichton** [comment]
I am by no means an expert on atomic orderings, but if this were switched to an acquire load I'm pretty certain that it is incorrect. Specifically with this code:

```rust
fn drop(&mut self) {
    if self.inner().strong.fetch_sub(1, Release) != 1 {
        return;
    }
    let _ = self.inner().strong.load(Acquire);
    /* drop contents of Arc */
}
```

The `Acquire` load generates a happens-before to yourself on that thread, since you did the last `Release`. There is no happens-before with any other thread, so you aren't actually guaranteed to see the `Arc` contents as published by any other thread, meaning you could `Drop` invalid data. 

The acquire `fence` does exactly what we want, which is to synchronize with all other possible threads. IIRC this is like a very specific case in the standard, basically invented for this exact problem.

> with any release operation C such that release sequence headed
by C includes B.

I believe this is only if there's a happens-before relationship between B and C. In the case of the `drop` method I gisted above, there is no happens-before for any Arc on any thread with any other.

**Comment by RalfJung** [comment]
> I believe this is only if there's a happens-before relationship between B and C. In the case of the drop method I gisted above, there is no happens-before for any Arc on any thread with any other.

According to [this](https://stackoverflow.com/questions/38565650/what-does-release-sequence-mean), for a *release sequence* to form we need to make sure that

>  the store is tagged with memory_order_release, memory_order_acq_rel, or memory_order_seq_cst, and the load is tagged with memory_order_consume, memory_order_acquire, or memory_order_seq_cst, and each operation in the chain loads the value written by the previous operation

I believe these conditions are met here: the earlier stores are memory_order_release and the final load is memory_order_acquire; the RMWs in the middle to not matter.

**Comment by alexcrichton** [comment]
Ok well I'm clearly not helping here, so I'm just going to unsubscribe and let this play out on its own.

**Comment by tmiasko** [comment]
As per earlier discussion, I changed the implementation to use acquire load in place of acquire fences.

Regarding correctness of that I approach, I stand by the argument given in https://github.com/rust-lang/rust/pull/65097#issuecomment-557776850. The explanation follows the wording of the standard, which should make it easier to validate it (or point out why it is incorrect). The existing implementation de-facto works for similar reasons.

The goal of PR is compatibility with ThreadSanitizer, so other implementation possible. For example, if there is strong preference to retain existing implementation the conditional compilation might be acceptable:

```rust
#[cfg(not(sanitize = "thread"))]
macro_rules! acquire { ($x:expr) => { atomic::fence(Acquire) } }

#[cfg(sanitize = "thread")]
macro_rules! acquire { ($x:expr) => { $x.load(Acquire) } }
```

I would appreciate any feedback from libs team to move this forward. This is last remaining blocker for ThreadSanitizer just working with Rust.

**Comment by Ixrec** [comment]
How much work is it to "redo" the formal verification of Arc for a change like this? (re-cc @jhjourdan)

**Comment by jhjourdan** [comment]
That's more a question for @hans89. As far as I can remember, he said that this should obviously work, but he do not have the time to redo the verification, given that this is uninteresting and still quite a bit of work.

**Comment by hans89** [comment]
If the change is to place the acquire `fence` with the acquire reads of the corresponding counter (weak/strong), I'm confident that it is correct. The verification is however, unexpectedly interesting, as this requires strengthening the logic I currently use to encode the synchronization power of such acquire reads. This will take some time to redo (as it involves reproving rules of the logic), but I'm in favor of this implementation.

**Comment by RalfJung** [comment]
Assigning to someone in T-libs... r? @Amanieu

**Comment by Amanieu** [comment]
On x86 the `lock xadd` instruction (which is what `fetch_sub` lowers to) always has SeqCst semantics. We could change `fetch_sub(Release)` to `fetch_sub(AcqRel)` on x86 only since that has no performance cost. This would enable ThreadSanitizer to work correctly on x86, which seems like a reasonable compromise.

**Comment by bjorn3** [comment]
Using a stronger ordering can still prevent optimizations, even when there is no difference at asm level.

**Comment by tmiasko** [comment]
@Amanieu using AcqRel on x86 would be fine, but if we are going in the direction of conditional compilation what would you say about proposal from comment https://github.com/rust-lang/rust/pull/65097#issuecomment-574286268 (I pushed a commit that implements it)?. It affects only those who actually use ThreadSanitizer and will work on other architectures once enabled in rustc.

**Comment by Amanieu** [comment]
@tmiasko I'm happy with that approach as well, but you'll need to use a tool like xargo to recompile libcore/libstd if you want to use it with that feature enable. I would expect that the default versions of libcore/libstd shipped with the compiler would not have this option enabled.

**Comment by tmiasko** [comment]
ThreadSanitizer works by compile time instrumentation of atomic operations, memory loads, and memory stores so recompilation is necessary regardless. Nowadays I would expect it to be used through `cargo -Zbuild-std` which makes the process straightforward

File: src/liballoc/sync.rs [hunk 1]
```diff
@@ -40,6 +40,20 @@ mod tests;
...
+        atomic::fence(Acquire)
+    };
+}
+
+#[cfg(sanitize = "thread")]
+macro_rules! acquire {
+    ($x:expr) => {
+        $x.load(Acquire)
+    };
+}
```
Comment (Amanieu) [inline src/liballoc/sync.rs]: Add a comment explaining why this is needed.

Comment (tmiasko) [reply src/liballoc/sync.rs]: Now with a comment.

**Comment by joshtriplett** [comment]
If you change the barrier types when ThreadSanitizer is enabled, you risk masking bugs you might have been trying to debug.

(And also, we *definitely* shouldn't change the required barrier type unconditionally based on the limitations of a debugging tool.)

**Comment by tmiasko** [comment]
Note that the synchronization used here is not really stronger, so there is no
risk of that kind, except in trivially true sense that with ThreadSanitizer you
are de-facto executing completely difference machine code, with additional
calls to the runtime for each atomic operation etc.

Furthermore if you are actually trying to debug issues in Arc / Weak,
ThreadSanitizer was of no use so far. On the other hand with changes
proposed here it is able to detect previous bugs when reintroduced.

**Comment by RalfJung** [comment]
One could actually argue synchronization is weaker, because an acquire fence syncs with all release writes/fences, while an acquire load only syncs with release writes *to the same location*.

**Comment by choller** [comment]
Thank you @tmiasko for working on this. This should get us one step closer to find races between C++ and Rust code in Firefox.

And fwiw, we have taken similar measures to replace a fence in our implementation with a load for TSan:

https://searchfox.org/mozilla-central/rev/4e228dc5f594340d35da7453829ad9f3c3cb8b58/mfbt/RefCounted.h#142-149
