### PR TITLE
inliner: Use substs_for_mir_body

### LINKED ISSUE #78529: type parameter `V/#2` (V/2) out of range when substituting with MIR inlining enabled
```console
env RUSTFLAGS=-Zmir-opt-level=2 cargo check -Zbuild-std --target x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:528:17: type parameter `V/#2` (V/2) out of range when substituting, substs=[fn() -> collections::btree::node::Root<K, V> {collections::btree::node::Root::<K, V>::new_leaf}, ()]

thread 'rustc' panicked at 'Box<Any>', /rustc/0da6d42f297642a60f2640ec313b879b376b9ad8/compiler/rustc_errors/src/lib.rs:891:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (0da6d42f2 2020-10-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z force-unstable-if-unmarked -Z mir-opt-level=2 -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<collections::btree::map::BTreeMap<K, V> as core::clone::Clone>::clone::clone_subtree`
#1 [optimized_mir] optimizing MIR for `<collections::btree::map::BTreeMap<K, V> as core::clone::Clone>::clone`
```

Regressed in #68965, cc @eddyb.

### LINKED ISSUE #78560: ICE:  type parameter out of range -Zmir-opt-level=2 --emit=mir
### Code
reduced from `./src/test/ui/issues/issue-28561.rs`
```Rust
#[derive(Clone)]
struct Fn<A, B> {
    f02: fn(A, B)
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (0d33ab7af 2020-10-30)
binary: rustc
commit-hash: 0d33ab7af4aebe786410b4c10367eb6ddf13af0b
commit-date: 2020-10-30
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

### Error output
`rustc ./src/test/ui/issues/issue-28561.rs  -Zmir-opt-level=2 --emit=mir`
```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:528:17: type parameter `B/#1` (B/1) out of range when substituting, substs=[fn(A, B)]

thread 'rustc' panicked at 'Box<Any>', /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/compiler/rustc_errors/src/lib.rs:891:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (0d33ab7af 2020-10-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<Fn<A, B> as std::clone::Clone>::clone`
end of query stack
error: aborting due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:528:17: type parameter `B/#1` (B/1) out of range when substituting, substs=[fn(A, B)]

thread 'rustc' panicked at 'Box<Any>', /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/compiler/rustc_errors/src/lib.rs:891:9
stack backtrace:
   0:     0x7f21197865f0 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7f21197865f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h881b9d30a8a89a0c
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f21197865f0 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f21197865f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f21197f652c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/core/src/fmt/mod.rs:1078:17
   5:     0x7f2119778252 - std::io::Write::write_fmt::h16a9fe7680ac245c
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/io/mod.rs:1518:15
   6:     0x7f211978b5a5 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f211978b5a5 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f211978b5a5 - std::panicking::default_hook::{{closure}}::h8d48653392f3b04c
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/panicking.rs:208:50
   9:     0x7f211978b248 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/panicking.rs:227:9
  10:     0x7f211a0554b8 - rustc_driver::report_ice::h1ddbc5609a6e1f37
  11:     0x7f211978bea6 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/panicking.rs:597:17
  12:     0x7f211cdb27fd - std::panicking::begin_panic::{{closure}}::hd947eabc42434d7e
  13:     0x7f211cdb2676 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48eb0455bf6d0a2
  14:     0x7f211cdb2756 - std::panicking::begin_panic::h673793876dd52a84
  15:     0x7f211cda38c5 - rustc_errors::HandlerInner::span_bug::h96d4d1f33fe11a81
  16:     0x7f211cda46c0 - rustc_errors::Handler::span_bug::hd4174033c6f30272
  17:     0x7f211cabfa64 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::hb4ddd0d3902006f3
  18:     0x7f211cab956b - rustc_middle::ty::context::tls::with_opt::{{closure}}::ha7f81bc36cab3c9f
  19:     0x7f211cab8f22 - rustc_middle::ty::context::tls::with_opt::hf0c2c2aff96e53ba
  20:     0x7f211cabf969 - rustc_middle::util::bug::opt_span_bug_fmt::hc7cbb029c2646db9
  21:     0x7f211cabf923 - rustc_middle::util::bug::span_bug_fmt::h3bf186beb4ce6b92
  22:     0x7f211cab701e - <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty::h5265163b4487a38a
  23:     0x7f211cc41852 - <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend::h5dc0ab4942b60e5f
  24:     0x7f211cd92602 - rustc_middle::ty::structural_impls::fold_list::h6987b80cfa543859
  25:     0x7f211cbe0ee5 - rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with::hcd50cd058363ef2d
  26:     0x7f211cab6e80 - <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty::h5265163b4487a38a
  27:     0x7f211cbe0e95 - rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with::hcd50cd058363ef2d
  28:     0x7f211cab6e80 - <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty::h5265163b4487a38a
  29:     0x7f211b67e213 - rustc_middle::ty::fold::TypeFoldable::fold_with::hcfc0bcab5eee2a4b
  30:     0x7f211b5ea834 - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::subst_and_normalize_erasing_regions::h50c1d5daecb56882
  31:     0x7f211b393dff - rustc_mir::transform::inline::Inliner::run_pass::h160d0d273d881e9b
  32:     0x7f211b39281a - <rustc_mir::transform::inline::Inline as rustc_mir::transform::MirPass>::run_pass::h616a912953f0ee0e
  33:     0x7f211b84987d - rustc_mir::transform::run_passes::h211303d522a12d5d
  34:     0x7f211b84b9d3 - rustc_mir::transform::run_optimization_passes::he68a023a63197fe9
  35:     0x7f211b84bc53 - rustc_mir::transform::optimized_mir::h9877cf2dcd224775
  36:     0x7f211b322a52 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::hc1fb28a214043661
  37:     0x7f211b6bf644 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hdcbd220a91a0fa7d
  38:     0x7f211b6cf561 - rustc_data_structures::stack::ensure_sufficient_stack::h8cd2d9586b9bff8c
  39:     0x7f211b4bcbbf - rustc_query_system::query::plumbing::get_query_impl::h426160ef8626bfd8
  40:     0x7f211b3a2597 - rustc_mir::util::pretty::write_mir_pretty::ha9d3fce2e2d6083a
  41:     0x7f211b590331 - rustc_mir::transform::dump_mir::emit_mir::he6266d14022fc931
  42:     0x7f211a2a1c54 - rustc_interface::passes::QueryContext::enter::h9b049407f643d454
  43:     0x7f211a2c1933 - rustc_interface::queries::Queries::ongoing_codegen::h90e1d78cee1f0a3b
  44:     0x7f211a0723a0 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h25b522245624a405
  45:     0x7f211a035a2f - rustc_span::with_source_map::h7455fffe3cd153a4
  46:     0x7f211a06d4f1 - scoped_tls::ScopedKey<T>::set::h8ae8151712a551fd
  47:     0x7f211a077c25 - std::sys_common::backtrace::__rust_begin_short_backtrace::h26de371bc27662fc
  48:     0x7f2119fdf648 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h80d1a8eb7971174b
  49:     0x7f211979aeaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/alloc/src/boxed.rs:1307:9
  50:     0x7f211979aeaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/alloc/src/boxed.rs:1307:9
  51:     0x7f211979aeaa - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/0d33ab7af4aebe786410b4c10367eb6ddf13af0b/library/std/src/sys/unix/thread.rs:89:17
  52:     0x7f21196963e9 - start_thread
  53:     0x7f21195b3293 - __GI___clone
  54:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (0d33ab7af 2020-10-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<Fn<A, B> as std::clone::Clone>::clone`
end of query stack
error: aborting due to previous error

```

</p>
</details>

### PR DESCRIPTION
**Pull request by tmiasko**
Changes from 68965 extended the kind of instances that are being
inlined. For some of those, the `instance_mir` returns a MIR body that
is already expressed in terms of the types found in substitution array,
and doesn't need further substitution.

Use `substs_for_mir_body` to take that into account.

Resolves #78529.
Resolves #78560.

### CODE REVIEW

File: compiler/rustc_mir/src/transform/inline.rs [hunk 1]
```diff
@@ -127,16 +129,14 @@ impl Inliner<'tcx> {
...
+                continue;
+            }
 
-            let callee_body = if self.consider_optimizing(callsite, callee_body) {
-                self.tcx.subst_and_normalize_erasing_regions(
-                    &callsite.callee.substs,
-                    self.param_env,
-                    callee_body,
-                )
+            let callee_body = if let Some(substs) = callsite.callee.substs_for_mir_body() {
```
Comment (oli-obk) [inline compiler/rustc_mir/src/transform/inline.rs:136]: There are like 5 duplications of this code spread around the various backends, the mir interpreter and the collector. Maybe create a method on `Instance` that takes a param env, a tcx and a generic arg that should be substituted (maybe) and returns that value?

Comment (tmiasko) [reply compiler/rustc_mir/src/transform/inline.rs]: I introduced a dedicated methods on `Instance` and replaced other uses like that.

**Comment by oli-obk** [comment]
@bors r+

Thanks!

File: compiler/rustc_middle/src/ty/instance.rs [hunk 2]
```diff
@@ -470,10 +470,33 @@ impl<'tcx> Instance<'tcx> {
     /// This function returns `Some(substs)` in the former case and `None` otherwise -- i.e., if
     /// this function returns `None`, then the MIR body does not require substitution during
     /// codegen.
```
Comment (o752d) [inline compiler/rustc_middle/src/ty/instance.rs:472]:
```suggestion
    /// This function returns `Some(substs)` in the former case and `None`
    /// otherwise -- i.e., if this function returns `None`, then the MIR body
    /// does not require substitution during codegen.
```
These line ran long in my reader.

**Comment by oli-obk** [comment]
@bors delegate+

r=me with the documentation nit resolved.

File: compiler/rustc_middle/src/ty/instance.rs (hunk 2 above)
Comment (tmiasko) [reply compiler/rustc_middle/src/ty/instance.rs:472]: The formatting already matches column used for wrapping the code. It also matches one of two predominant columns used for wrapping comments in this file. 

Furthermore, the comment is not being modified here, so I see no reason to introduce additional spurious formatting changes.

**Comment by jyn514** [comment]
@bors r-

[Failed in rollup](https://github.com/rust-lang/rust/pull/78792#issuecomment-722803749):

```

---- [mir-opt] mir-opt/inline/inline-shims.rs stdout ----
9	      let mut _4: *mut std::vec::Vec<A>;   // in scope 0 at $DIR/inline-shims.rs:10:38: 10:39
10	      let mut _5: *mut std::option::Option<B>; // in scope 0 at $DIR/inline-shims.rs:11:38: 11:39
11	      scope 1 {
+	+         scope 3 (inlined drop_in_place::<Vec<A>> - shim(Some(Vec<A>))) { // at $DIR/inline-shims.rs:10:14: 10:40
+	+             let mut _6: &mut std::vec::Vec<A>; // in scope 3 at $DIR/inline-shims.rs:10:14: 10:40
+	+             let mut _7: ();              // in scope 3 at $DIR/inline-shims.rs:10:14: 10:40
+	+         }
12	      }
13	      scope 2 {
-	+         scope 3 (inlined drop_in_place::<Option<B>> - shim(Some(Option<B>))) { // at $DIR/inline-shims.rs:11:14: 11:40
-	+             let mut _6: isize;           // in scope 3 at $DIR/inline-shims.rs:11:14: 11:40
-	+             let mut _7: isize;           // in scope 3 at $DIR/inline-shims.rs:11:14: 11:40
+	+         scope 4 (inlined drop_in_place::<Option<B>> - shim(Some(Option<B>))) { // at $DIR/inline-shims.rs:11:14: 11:40
+	+             let mut _8: isize;           // in scope 4 at $DIR/inline-shims.rs:11:14: 11:40
+	+             let mut _9: isize;           // in scope 4 at $DIR/inline-shims.rs:11:14: 11:40
17	+         }
18	      }
19	  

21	          StorageLive(_3);                 // scope 0 at $DIR/inline-shims.rs:10:5: 10:42
22	          StorageLive(_4);                 // scope 1 at $DIR/inline-shims.rs:10:38: 10:39
23	          _4 = _1;                         // scope 1 at $DIR/inline-shims.rs:10:38: 10:39
-	          _3 = drop_in_place::<Vec<A>>(move _4) -> bb1; // scope 1 at $DIR/inline-shims.rs:10:14: 10:40
+	-         _3 = drop_in_place::<Vec<A>>(move _4) -> bb1; // scope 1 at $DIR/inline-shims.rs:10:14: 10:40
+	+         _6 = &mut (*_4);                 // scope 3 at $DIR/inline-shims.rs:10:14: 10:40
+	+         _7 = <Vec<A> as Drop>::drop(move _6) -> bb2; // scope 3 at $DIR/inline-shims.rs:10:14: 10:40
25	                                           // mir::Constant
-	                                           // + span: $DIR/inline-shims.rs:10:14: 10:37
-	                                           // + literal: Const { ty: unsafe fn(*mut std::vec::Vec<A>) {std::intrinsics::drop_in_place::<std::vec::Vec<A>>}, val: Value(Scalar(<ZST>)) }
+	-                                          // + span: $DIR/inline-shims.rs:10:14: 10:37
+	-                                          // + literal: Const { ty: unsafe fn(*mut std::vec::Vec<A>) {std::intrinsics::drop_in_place::<std::vec::Vec<A>>}, val: Value(Scalar(<ZST>)) }
+	+                                          // + span: $DIR/inline-shims.rs:10:14: 10:40
+	+                                          // + literal: Const { ty: for<'r> fn(&'r mut std::vec::Vec<A>) {<std::vec::Vec<A> as std::ops::Drop>::drop}, val: Value(Scalar(<ZST>)) }
28	      }
29	  
30	      bb1: {

36	-                                          // mir::Constant
37	-                                          // + span: $DIR/inline-shims.rs:11:14: 11:37
38	-                                          // + literal: Const { ty: unsafe fn(*mut std::option::Option<B>) {std::intrinsics::drop_in_place::<std::option::Option<B>>}, val: Value(Scalar(<ZST>)) }
-	+         _6 = discriminant((*_5));        // scope 3 at $DIR/inline-shims.rs:11:14: 11:40
-	+         switchInt(move _6) -> [0_isize: bb2, otherwise: bb3]; // scope 3 at $DIR/inline-shims.rs:11:14: 11:40
+	+         _8 = discriminant((*_5));        // scope 4 at $DIR/inline-shims.rs:11:14: 11:40
+	+         switchInt(move _8) -> [0_isize: bb3, otherwise: bb4]; // scope 4 at $DIR/inline-shims.rs:11:14: 11:40
41	      }
42	  
43	      bb2: {

+	+         drop(((*_4).0: alloc::raw_vec::RawVec<A>)) -> bb1; // scope 3 at $DIR/inline-shims.rs:10:14: 10:40
+	+     }
+	+ 
+	+     bb3: {
44	          StorageDead(_5);                 // scope 2 at $DIR/inline-shims.rs:11:39: 11:40
45	          return;                          // scope 0 at $DIR/inline-shims.rs:12:2: 12:2
46	+     }

47	+ 
-	+     bb3: {
-	+         drop((((*_5) as Some).0: B)) -> bb2; // scope 3 at $DIR/inline-shims.rs:11:14: 11:40
+	+     bb4: {
+	+         drop((((*_5) as Some).0: B)) -> bb3; // scope 4 at $DIR/inline-shims.rs:11:14: 11:40
50	      }
51	  }
52	  

thread '[mir-opt] mir-opt/inline/inline-shims.rs' panicked at 'Actual MIR output differs from expected MIR output /checkout/src/test/mir-opt/inline/inline_shims.drop.Inline.diff', src/tools/compiletest/src/runtest.rs:3272:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by oli-obk** [comment]
@tmiasko  you still have delegation rights, so r=me after a rebase

**Comment by tmiasko** [comment]
Ignored new tests on wasm target.

@bors r=oli-obk
