### PR TITLE
smarter E0390

### LINKED ISSUE #79760: Error wrongly trying to assign assoc const to primitive speaks of methods
Imperfection in error output.

I just tried adding an associated constant to a type alias of a primitive (to see if it was allowed or whether I'd need a wrapper) and noticed an imperfection in the error output in that it says "help: consider using a trait to implement these methods" pointing to the impl block that actually just contains an constant.

```bash
error[E0390]: only a single inherent implementation marked with `#[lang = "u64"]` is allowed for the `u64` primitive
  --> pulse-binding/src/channelmap.rs:50:1
   |
50 | / impl PositionMask {
51 | |     pub const POSITION_MASK_ALL: PositionMask = 0xffffffffffffffffu64;
52 | | }
   | |_^
   |
help: consider using a trait to implement these methods
  --> pulse-binding/src/channelmap.rs:50:1
   |
50 | / impl PositionMask {
51 | |     pub const POSITION_MASK_ALL: PositionMask = 0xffffffffffffffffu64;
52 | | }
   | |_^
```

### PR DESCRIPTION
**Pull request by eopb**
Should fix #79760

I am fairly new to the compiler so am hoping I did things correctly :).

### CODE REVIEW

File: compiler/rustc_typeck/src/coherence/inherent_impls.rs [hunk 1]
```diff
@@ -387,7 +412,34 @@ impl InherentCollect<'tcx> {
...
+                                        .all(|x| matches! {x, hir::AssocItemKind::Fn{ .. } })
+                                    {
+                                        "method"
+                                    } else {
+                                        "associated item"
+                                    }
+                                },
+                                if plural { "s" } else { "" }
+                            )
+                        }
```
Comment (camelid) [inline compiler/rustc_typeck/src/coherence/inherent_impls.rs:440]: I think ideally you would extract these computations out to before the `struct_span_err!` call. Then you would just reference local variables in the `format!` call. The way it is right now is quite hard to read, since it has a lot of nested computations inside nested `format!` calls.

File: compiler/rustc_typeck/src/coherence/inherent_impls.rs [hunk 2]
```diff
@@ -387,7 +412,34 @@ impl InherentCollect<'tcx> {
                     lang,
                     ty
                 )
-                .span_help(span, "consider using a trait to implement these methods")
+                .span_help(
```
Comment (camelid) [inline compiler/rustc_typeck/src/coherence/inherent_impls.rs:415]: I know you didn't change this, but I think this should be `.help`, not `.span_help`. Using `span_help` causes it to reprint the source code, which is not helpful and also confusing because it's exactly the same.

```suggestion
                .help(
```

**Comment by oli-obk** [comment]
This is a really nice improvement in diagnostics, thanks!

@bors r+ rollup
