### PR TITLE
Emits E0599 when meeting `MyTrait::missing_method`

### LINKED ISSUE #111312: confusing diagnostic when calling a method that doesn't exist on a trait but exists on another trait
### Code

```Rust
trait Has {
    fn has() {}
}

trait HasNot {}

fn main() {
    HasNot::has();
}
```

### Current output

```Shell
error[E0782]: trait objects must include the `dyn` keyword
 --> src/main.rs:8:5
  |
8 |     HasNot::has();
  |     ^^^^^^
  |
help: add `dyn` keyword before this trait
  |
8 |     <dyn HasNot>::has();
  |     ++++       +

error[E0599]: no function or associated item named `has` found for trait object `dyn HasNot` in the current scope
 --> src/main.rs:8:13
  |
8 |     HasNot::has();
  |             ^^^ function or associated item not found in `dyn HasNot`
  |
  = help: items from traits can only be used if the trait is implemented and in scope
note: `Has` defines an item `has`, perhaps you need to implement it
 --> src/main.rs:1:1
  |
1 | trait Has {
  | ^^^^^^^^^

Some errors have detailed explanations: E0599, E0782.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `playground` due to 2 previous errors
```

code snippet by @WaffleLapkin. (this is from December 2022)

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #111312

### CODE REVIEW

**Comment by MU001999** [comment]
I am confused by the error when testing `tests/ui/runtime/backtrace-debuginfo.rs`. How should I solve this failure?

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 1]
```diff
@@ -883,10 +894,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         error,
                         None,
                         Expectation::NoExpectation,
+                        trait_missing_method && span.edition() >= Edition::Edition2021, // emits missing method for trait only after edition 2021
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:897]: Use `.edition().is_rust_2021()` instead

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 2]
```diff
@@ -853,6 +854,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let item_name = item_segment.ident;
         let result = self
             .resolve_fully_qualified_call(span, item_name, ty.normalized, qself.span, hir_id)
+            .and_then(|r| {
+                // lint bare trait if the method is found in the trait
+                if span.edition() >= Edition::Edition2021 {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:859]: I don't really like that the error here got moved from astconv... See above comment about delaying a bug or stashing a diagnostic.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 3]
```diff
@@ -359,21 +369,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    Cow::from("trait")
+                } else {
+                    rcvr_ty.prefix_string(self.tcx)
+                },
                 ty_str_reported,
+                if trait_missing_method {
+                    ""
+                } else {
+                    " in the current scope"
+                },
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:386]: Please also make these translatable too. `rustc_hir_typeck` currently has a lot of untranslatable diagnostics so it would be pretty nice to have PRs that touch code with untranslatable diagnostics to turn them translatable.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 4]
```diff
@@ -2747,12 +2773,17 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                            item_name,
-                            action
-                        ),
+                        fluent::hir_typeck_candidate_trait_note,
+                    )
+                    .set_arg("trait_name", self.tcx.def_path_str(trait_info.def_id))
+                    .set_arg("item_name", item_name)
+                    .set_arg(
+                        "postfix",
+                        if trait_missing_method {
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2782]: Please use diagnostic structs in `src/errors.rs` See [this](https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html).

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 5]
```diff
@@ -355,25 +365,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                Cow::from("trait")
+            } else {
+                rcvr_ty.prefix_string(self.tcx)
+            })
+            .set_arg("ty_str", ty_str_reported)
+            .set_arg("postfix", if trait_missing_method {
+                ""
+            } else {
+                " in the current scope"
+            });
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:382]: This is not the best way to do this, since the string would be in english. You should set a bool and match that in the fluent resource.

File: compiler/rustc_hir_typeck/messages.ftl [hunk 6]
```diff
@@ -79,3 +79,13 @@ hir_typeck_arg_mismatch_indeterminate = argument type mismatch was detected, but
...
+
+hir_typeck_no_associated_item = no {$item_kind} named `{$item_name}` found for {$ty_prefix} `{$ty_str}`{$trait_missing_method ->
+    [true] {""}
+    *[other] {" "}in the current scope
+}
+
+hir_typeck_candidate_trait_note = `{$trait_name}` defines an item `{$item_name}`{$action ->
+    [NONE] {""}
+    *[other] , perhaps you need to {$action} it
+}
```
Comment (fee1-dead) [inline compiler/rustc_hir_typeck/messages.ftl:91]: Ideally, this should cover all cases, so something like

```suggestion
hir_typeck_candidate_trait_note = `{$trait_name}` defines an item `{$item_name}`{$action ->
    [none] {""}
    [restrict] , perhaps you need to restrict type parameter `{$ty}` with it
    [implement] , perhaps you need to implement it
    *[unreachable] {""}
}
```

Otherwise this change LGTM.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 7]
```diff
@@ -853,6 +853,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         let item_name = item_segment.ident;
         let result = self
             .resolve_fully_qualified_call(span, item_name, ty.normalized, qself.span, hir_id)
+            .and_then(|r| {
+                // lint bare trait if the method is found in the trait
+                if span.edition().rust_2021() && let Some(mut diag) = self.tcx.sess.diagnostic().steal_diagnostic(qself.span, StashKey::TraitMissingMethod) {
+                    diag.emit();
+                }
+                Ok(r)
+            })
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:862]: Isn't this redundant with the code below?

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 8]
```diff
@@ -863,17 +870,30 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                // emit or cancel the diagnostic for bare traits
+                if span.edition().rust_2021() && let Some(mut diag) = self.tcx.sess.diagnostic().steal_diagnostic(qself.span, StashKey::TraitMissingMethod) {
+                    if trait_missing_method {
+                        // cancel the diag for bare traits when meeting `MyTrait::missing_method`
+                        diag.cancel();
+                    } else {
+                        diag.emit();
+                    }
+                }
+
```
Comment (cjgillot) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:896]: Should this code be in `report_method_error`?

**Review by cjgillot — COMMENTED** [review]
2 nits here. @MU001999 could you see about them as part of https://github.com/rust-lang/rust/pull/111731?

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 7 above)
Comment (MU001999) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:862]: I don't think so. This code emits steal and emit the diag when it is able to find the target method for `dyn MyTrait`. The code below is executed only when it is not able to find such a method.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 8 above)
Comment (MU001999) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:896]: I think it is good to pass only `trait_missing_method` to `report_method_error`. There are two reasons for this: first, the diag for the bare traits will only be emitted or cancelled here; and second, the diag for bare traits is not a method-error. Putting this code in `report_method_error` will lead to logical dispersion.
