### PR TITLE
[const-prop] Fix ICE when trying to eval polymorphic promoted MIR

### LINKED ISSUE #64908: ICE building Apache Arrow PR in `librustc_traits/normalize_erasing_regions.rs:42`
See https://travis-ci.org/apache/arrow/jobs/591264273 for failed build

```
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:42: could not fully normalize `fn() -> usize {std::mem::size_of::<<T as datatypes::ArrowPrimitiveType>::Native>}`
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.40.0-nightly (488381ce9 2019-09-28) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #64908 

r? @oli-obk 
cc @nikomatsakis @pnkfelix

### CODE REVIEW

File: src/librustc_mir/interpret/place.rs [hunk 1]
```diff
@@ -594,6 +594,13 @@ where
             StaticKind::Promoted(promoted, promoted_substs) => {
                 let substs = self.subst_from_frame_and_normalize_erasing_regions(promoted_substs);
                 let instance = ty::Instance::new(place_static.def_id, substs);
+
+                // even after getting substs from the frame, this instance may still be
```
Comment (Centril) [inline src/librustc_mir/interpret/place.rs]:
```suggestion
                // Even after getting `substs` from the frame, this instance may still be
```

File: src/librustc_mir/interpret/place.rs [hunk 2]
```diff
@@ -594,6 +594,13 @@ where
...
+                // polymorphic because ConstProp will try to polymorphic promoted MIR
```
Comment (Centril) [inline src/librustc_mir/interpret/place.rs]:
```suggestion
                // polymorphic because `ConstProp` will try to polymorphic promoted MIR.
```

File: src/test/ui/consts/const-eval/issue-64908.rs [hunk 3]
```diff
@@ -0,0 +1,17 @@
+// run-pass
```
Comment (Centril) [inline src/test/ui/consts/const-eval/issue-64908.rs]: Could this test be described a bit more with a comment?

File: src/librustc_mir/interpret/place.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/place.rs]:
```suggestion
                // polymorphic because ConstProp will try to promote polymorphic MIR
```

**Review by oli-obk — COMMENTED** [review]
r=me with nits

File: src/librustc_mir/interpret/place.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_mir/interpret/place.rs]: @oli-obk integrated your nit in my nit. :)
