### PR TITLE
Use heuristics to recover parsing of missing `;`

### LINKED ISSUE #44767: Confusing parse error with let bindings
This code:
```rust
fn main() {
    let a = 3
}
```
gives the error:
```
error: expected one of `.`, `;`, `?`, or an operator, found `}`
 --> src/main.rs:3:1
  |
2 |     let a = 3
  |              - expected one of `.`, `;`, `?`, or an operator here
3 | }
  | ^ unexpected token
```

It would be nice if this would instead say that `let` is not an expression.

### LINKED ISSUE #48160: parser should recover from seeing `,` when `;` is expected
Right now, if `rustc` is parsing a function body and sees a `,` when it expected a `;`, it will give up on parsing the rest of the current function body.

Meanwhile, later phases of the compiler still run. Which means, for example, if the remainder of that erroneous function body contains the sole references to certain imports, then you get false warnings about those imports being unused.

Here is a concrete example ([playground](https://play.rust-lang.org/?gist=e22178b3eef8977777022ea98144b439&version=beta)):

```rust
use std::iter::Iterator;

fn main() {
    struct S;
    let _x = 3,
    impl Iterator for S {
        type Item = S;
        fn next(&mut self) -> Option<S> { Some(S) }
    }
}
```

which yields the following diagnostic output on nightly and beta:

```
error: expected one of `.`, `;`, `?`, or an operator, found `,`
 --> src/main.rs:5:15
  |
5 |     let _x = 3,
  |               ^ expected one of `.`, `;`, `?`, or an operator here

warning: unused import: `std::iter::Iterator`
 --> src/main.rs:1:5
  |
1 | use std::iter::Iterator;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to previous error
```

This seems to affect the current nightly and beta, but not stable (I.e., the stable channel just presents the parse error, not the erroneous lint about the supposedly unused import.)

### PR DESCRIPTION
**Pull request by estebank**
- Detect `,` and `:` typos where `;` was intended.
- When the next token could have been the start of a new statement,
  detect a missing semicolon.

Fix #48160, fix #44767 (after adding note about statements).

### CODE REVIEW

**Comment by estebank** [comment]
Still needs a bit of a clean up, but the idea is to detect some common typos that can occur during development and the lack of a semicolon, which is also quite common when writing code.

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 1]
```diff
@@ -916,6 +916,54 @@ impl<'a> Parser<'a> {
         Err(err)
     }
 
+    pub(super) fn expect_semi(&mut self) -> PResult<'a, ()> {
+        if self.eat(&token::Semi) {
+            return Ok(());
+        }
+        let sm = self.sess.source_map();
+        if self.look_ahead(1, |t| {
+            (t == &token::CloseDelim(token::Brace) || token_can_begin_expr(t)) && t.kind != token::Colon
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: Two points here:
1. `t == token::CloseDelim(...)` implies `t.kind != token::Colon` so this check is redundant in the LHS of `||` and can be moved into the RHS.
2. It's easier to read if you use the rustfmt formatting with:
```rust
long_expression_seriously_this_is_long
binop some_other_random_expression
```

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 2]
```diff
@@ -916,6 +916,54 @@ impl<'a> Parser<'a> {
...
+        }) && [token::Comma, token::Colon].contains(&self.token.kind) {
+            // Likely typo: `,` → `;`, `:` → `;`.
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]:
```suggestion
            // Likely typo: `,` → `;` or `:` → `;`.
```
(ETOOMANYSIGILS)

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 3]
```diff
@@ -916,6 +916,54 @@ impl<'a> Parser<'a> {
...
+            match (sm.lookup_line(self.prev_span.lo()), sm.lookup_line(self.token.span.lo())) {
+                (Ok(ref a), Ok(ref b)) if a.line != b.line => {
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: Elaborate on all the various conditions that lead here would be good & include an example that illustrates why this heuristic is used.

File: src/libsyntax/parse/token.rs [hunk 4]
```diff
@@ -143,16 +143,20 @@ impl Lit {
 
 pub(crate) fn ident_can_begin_expr(name: ast::Name, span: Span, is_raw: bool) -> bool {
     let ident_token = Token::new(Ident(name, is_raw), span);
+    token_can_begin_expr(&ident_token)
+}
+
+pub(crate) fn token_can_begin_expr(ident_token: &Token) -> bool {
+    let name = if let TokenKind::Ident(ident, _) = ident_token.kind {
```
Comment (Centril) [inline src/libsyntax/parse/token.rs]: This is performing redundant work in case `name.map_or` never happens, inline it? (also a `match` would subjectively be nicer here imo).

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 5]
```diff
@@ -916,6 +916,54 @@ impl<'a> Parser<'a> {
...
+                _ => {}
+            }
+        } else if self.look_ahead(0, |t| {
+            (t == &token::CloseDelim(token::Brace) || token_can_begin_expr(t))
+                && t != &token::Semi
+                && t != &token::Pound // Avoid triggering with too many trailing `#` in raw string.
+        }) {
+            // Missing semicolon typo.
+            match (sm.lookup_line(self.prev_span.lo()), sm.lookup_line(self.token.span.lo())) {
+                (Ok(ref a), Ok(ref b)) if a.line != b.line => {
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: This could be turned into a method (`fn spans_on_same_line(self: &SourceMap`) that returns `true` if this condition holds. This logic is used twice in this method and `fn unexpected_try_recover` as well (worth checking if other places in this file has it too).

This could probably(?) also be rephrased as:
```rust
self.is_multiline(lo.to(hi))
```

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 6]
```diff
@@ -916,6 +916,54 @@ impl<'a> Parser<'a> {
...
+                            ";".to_string(),
+                            Applicability::MaybeIncorrect,
+                        ).emit();
+                    return Ok(())
+                }
+                _ => {}
+            }
+        } else if self.look_ahead(0, |t| {
+            (t == &token::CloseDelim(token::Brace) || token_can_begin_expr(t))
+                && t != &token::Semi
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: Same point about `||` as above.

File: src/libsyntax/parse/parser/item.rs [hunk 7]
```diff
@@ -98,7 +98,7 @@ impl<'a> Parser<'a> {
         if self.eat_keyword(kw::Use) {
             // USE ITEM
             let item_ = ItemKind::Use(P(self.parse_use_tree()?));
-            self.expect(&token::Semi)?;
+            self.expect_semi()?;
```
Comment (Centril) [inline src/libsyntax/parse/parser/item.rs]: I assume you grepped for the various places?

Comment (estebank) [reply src/libsyntax/parse/parser/item.rs]: Yep.

**Comment by RalfJung** [comment]
> Could not resolve host: rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com

@bors retry

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 8]
```diff
@@ -326,34 +326,8 @@ impl<'a> Parser<'a> {
...
-            self.token.is_keyword(kw::For) ||
-            self.token.is_keyword(kw::If) ||
-            self.token.is_keyword(kw::Let) ||
-            self.token.is_keyword(kw::Loop) ||
-            self.token.is_keyword(kw::Match) ||
-            self.token.is_keyword(kw::Return) ||
-            self.token.is_keyword(kw::While)
-        );
         let sm = self.sess.source_map();
         match (sm.lookup_line(self.token.span.lo()), sm.lookup_line(sp.lo())) {
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: `is_multiline` could be used here also?

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 9]
```diff
@@ -902,18 +876,61 @@ impl<'a> Parser<'a> {
             }
         }
         let sm = self.sess.source_map();
-        match (sm.lookup_line(prev_sp.lo()), sm.lookup_line(sp.lo())) {
-            (Ok(ref a), Ok(ref b)) if a.line == b.line => {
-                // When the spans are in the same line, it means that the only content
-                // between them is whitespace, point only at the found token.
-                err.span_label(sp, label_exp);
+        if !sm.is_multiline(prev_sp.until(sp)) {
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: The logic here seems very similar to the case in my comment above -- a refactoring opportunity?

File: src/libsyntax/parse/parser/diagnostics.rs [hunk 10]
```diff
@@ -902,18 +876,61 @@ impl<'a> Parser<'a> {
...
+        if self.look_ahead(1, |t| t == &token::CloseDelim(token::Brace)
+            || token_can_begin_expr(t) && t.kind != token::Colon
+        ) && [token::Comma, token::Colon].contains(&self.token.kind) {
+            // Likely typo: `,` → `;` or `:` → `;`. This is triggered if the current token is
+            // either `,` or `:`, and the next token could either start a new statement or is a
+            // block close. For example:
+            //
+            //   let x = 32:
+            //   let y = 42;
+            if sm.is_multiline(self.prev_span.until(self.token.span)) {
```
Comment (Centril) [inline src/libsyntax/parse/parser/diagnostics.rs]: Looking at the code now, it seems to me you can hoist `if sm.is_multiline(...)` out from both branches since they are identical; that will reduce number of checks and allow you to inline `let sm` and move the allocation into `if self.sess.source_map().is_multiline(...) {`.

File: src/libsyntax/parse/parser/diagnostics.rs (hunk 8 above)
Comment (estebank) [reply src/libsyntax/parse/parser/diagnostics.rs]: This block works even if any of the spans is `DUMMY_SP`, which can happen with macros. This approach is a bit more robust than `is_multiline`, but maybe it isn't worth it to protect against it this way?

Comment (Centril) [reply src/libsyntax/parse/parser/diagnostics.rs]: Could that robustness be integrated into `is_multiline`?

File: src/libsyntax/parse/parser/diagnostics.rs (hunk 10 above)
Comment (Centril) [reply src/libsyntax/parse/parser/diagnostics.rs]: I'm thinking that we're going to unconditionally error in either case so does that matter? :)

File: src/libsyntax/parse/parser/diagnostics.rs (hunk 8 above)
Comment (estebank) [reply src/libsyntax/parse/parser/diagnostics.rs]: I'll see what I can do :)

File: src/test/ui/parser/recover-missing-semi.stderr [hunk 11]
```diff
@@ -1,20 +1,20 @@
...
+  --> $DIR/recover-missing-semi.rs:2:22
    |
 LL |     let _: usize = ()
-   |                      - help: a semicolon may be missing here
-LL |
+   |                      ^ help: add `;` here
+...
 LL |     let _ = 3;
-   |     ^^^
+   |     --- unexpected token
```
Comment (estebank) [inline src/test/ui/parser/recover-missing-semi.stderr]: I like the look of this error, but it _is_ slightly misleading because it could have been any of the other expected tokens, but given it was followed by a "token capable of starting statement", I feel comfortable to ignore the other possibilities. What do you think?

File: src/test/ui/macros/issue-54441.stderr [hunk 12]
```diff
@@ -1,8 +1,8 @@
-error: expected one of `crate`, `fn`, `pub`, `static`, or `type`, found `let`
+error: expected one of `crate`, `fn`, `pub`, `static`, or `type`, found keyword `let`
   --> $DIR/issue-54441.rs:3:9
    |
 LL |         let
-   |         ^^^ unexpected token
+   |         ^^^ expected one of `crate`, `fn`, `pub`, `static`, or `type` here
```
Comment (JeanMertz) [inline src/test/ui/macros/issue-54441.stderr]: In the change above this one the word `here` is removed in this PR (“ ^^ expected `fn` here”), while it is still present in this change.

Is that as intended?

File: src/test/ui/parser/recover-missing-semi.stderr (hunk 11 above)
Comment (Centril) [reply src/test/ui/parser/recover-missing-semi.stderr]: Seems reasonable as a heuristic. You could optionally add a note below for the additional expected tokens. I'll leave that up to you.

**Comment by Centril** [comment]
r=me with or without the additional note and "here".

File: src/test/ui/macros/issue-54441.stderr (hunk 12 above)
Comment (estebank) [reply src/test/ui/macros/issue-54441.stderr]: Updated these as well.
