### PR TITLE
Use recursion_limit for const eval stack limit

### LINKED ISSUE #643: Should be able to change stack limit
It is currently not possible to change the stack limit. It would be great to get that functionality back!

# Original report

Maybe I'm doing something wrong, but I'm unable to set the stack limit for miri.

If I call `cargo miri test --help` it says:

```text
The config flag `miri` is automatically defined for convenience. You can use
it to configure the resource limits

    #![cfg_attr(miri, memory_size = 42)]

available resource limits are `memory_size`, `step_limit`, `stack_limit`
```

After adding

```rust 
#![cfg_attr(miri, stack_limit = 100000)]
```

to my `lib.rs` I get "stack limit reached error" at the same depth.

### PR DESCRIPTION
**Pull request by CAD97**
cc https://github.com/rust-lang/miri/issues/643 @orium @RalfJung 

I'm really not certain how exactly to handle this change, but it looks like it's that simple.

Reuse `recursion_limit` ("The maximum recursion limit for potentially infinitely recursive operations such as auto-dereference and monomorphization") which is configurable by the user for the const evaluation stack frame limit.

The other option is to make `const_eval_stack_frame_limit` configurable in the same way as `recursion_limit` (but I'm not sure how to do that and it'd be a bigger change).

Fixes https://github.com/rust-lang/miri/issues/643.

### CODE REVIEW

**Comment by CAD97** [comment]
(I just want to note that apparently I am failing at git/rebase currently, so the commit is weird and misbehaving.)

**Comment by CAD97** [comment]
(There, commit should be fixed.)

**Comment by RalfJung** [comment]
Looks like you will have to adjust some UI tests.

The approach LGTM, but I'd also like to hear @oli-obk's opinion.

**Comment by CAD97** [comment]
[I'm building a new computer over the holidays and apparently my current setup is fighting me all the way down, because my dev setup is revealing itself to be broken in ways I've never imagined, apparently, so I'm currently unable to build the compiler locally in order to bless the UI tests.](https://internals.rust-lang.org/t/x-py-1-is-not-a-valid-win32-application/11371/3)

File: src/librustc_mir/interpret/eval_context.rs [hunk 1]
```diff
@@ -546,7 +546,7 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
 
         info!("ENTERING({}) {}", self.cur_frame(), self.frame().instance);
 
-        if self.stack.len() > self.tcx.sess.const_eval_stack_frame_limit {
+        if self.stack.len() > *self.tcx.sess.recursion_limit.get() {
```
Comment (oli-obk) [inline src/librustc_mir/interpret/eval_context.rs]: This is kind of a breaking change now. If users were using a low recursion limit (below 100), their code will now stop compiling if they were using a const eval stack deeper than their recursion limit. I think it would be best to use a minimum of 100 for the check here.

Comment (RalfJung) [reply src/librustc_mir/interpret/eval_context.rs]: Alternatively we could crater this... this is the kind of breaking change we can do if the diagnostics are good enough.

What is the default recursion limit?

Comment (oli-obk) [reply src/librustc_mir/interpret/eval_context.rs]: the default is 128, so no worries there. It would only be a breaking change if ppl explicitly set a lower value

Comment (RalfJung) [reply src/librustc_mir/interpret/eval_context.rs]: I'd rather not introduce a hack in the Miri engine if the number of affected crates is most likely to be 0 (and moreover, if crates actually are affected, the fix of raising the recursion limit to 100 is trivial).

Comment (oli-obk) [reply src/librustc_mir/interpret/eval_context.rs]: seems fine to me, too, I just wanted to bring it up. Crater seems like a waste for this. We can always add the hack later if it ends up being important

**Comment by oli-obk** [comment]
lgtm modulo tests

File: src/librustc_mir/interpret/eval_context.rs (hunk 1 above)
Comment (CAD97) [reply src/librustc_mir/interpret/eval_context.rs]: > if the diagnostics are good enough.

Currently, I've not changed the diagnostics at all, so it doesn't mention that the limit can be changed via `#![recursion_limit]` at all. I'm not sure exactly how to make that adjustment, though.

**Comment by CAD97** [comment]
I believe other changes caused the two failing UI tests to output a recursive requirement warning rather than a depth limit exceeded, so the tests don't need updating anymore. I did manage to get "most" of a bless run done.
