### PR TITLE
Avoid ICE in macro's diagnostics

### LINKED ISSUE #68629: internal compiler error: "byte index 15 is not a char boundary"
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```
$ echo IBwfdHMAIVt7aQoAACAgZm4gct27b2E+ct27bQ== | base64 --decode > main.rs
$ rustc main.rs
error: unknown start of token: \u{1c}
 --> main.rs:1:2
  |
1 |  ts![{i
  |  ^

error: unknown start of token: \u{1f}
 --> main.rs:1:3
  |
1 |  ts![{i
  |  ^

error: unknown start of token: \u{0}
 --> main.rs:1:6
  |
1 |  ts![{i
  |    ^

error: unknown start of token: \u{0}
 --> main.rs:2:1
  |
2 |   fn rݻoa>rݻm
  | ^

error: unknown start of token: \u{0}
 --> main.rs:2:2
  |
2 |   fn rݻoa>rݻm
  | ^

error: this file contains an unclosed delimiter
 --> main.rs:2:16
  |
1 |  ts![{i
  |     -- unclosed delimiter
  |     |
  |     unclosed delimiter
2 |   fn rݻoa>rݻm
  |              ^

error: macros that expand to items must be delimited with braces or followed by a semicolon
 --> main.rs:1:8
  |
1 |    ts![{i
  |  _____^
2 | |   fn rݻoa>rݻm
  | |_____________^
  |
thread 'rustc' panicked at 'byte index 15 is not a char boundary; it is inside 'ݻ' (bytes 14..16) of `  fn rݻoa>rݻm`', src/libcore/str/mod.rs:2154:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (3761dcd34 2020-01-28) running on x86_64-unknown-linux-gnu

error: aborting due to 6 previous errors
```

My compiler version is:
```
$ rustc -vV
rustc 1.42.0-nightly (3761dcd34 2020-01-28)
binary: rustc
commit-hash: 3761dcd3467441f78939ccb3b341b03b6a7558d7
commit-date: 2020-01-28
host: x86_64-unknown-linux-gnu
release: 1.42.0-nightly
LLVM version: 9.0
```

I also observe the error on `beta`, but not on `stable`.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #68629

r? @estebank

### CODE REVIEW

File: src/librustc_parse/parser/item.rs [hunk 1]
```diff
@@ -1638,26 +1638,32 @@ impl<'a> Parser<'a> {
...
+                    (self.prev_span.with_lo(self.prev_span.hi() - BytePos(1)), '}'.to_string()),
+                ],
+                Applicability::MaybeIncorrect,
+            );
+        } else {
+            err.span_suggestion(
+                self.prev_span,
+                "change the delimiters to curly braces",
+                " { /* items */ }".to_string(),
+                Applicability::MaybeIncorrect,
```
Comment (CryZe) [inline src/librustc_parse/parser/item.rs]: Shouldn't this be `Applicability::HasPlaceholders`?

File: src/librustc_parse/parser/item.rs [hunk 2]
```diff
@@ -1638,26 +1638,32 @@ impl<'a> Parser<'a> {
...
-        .span_suggestion(
+        );
+
+        // To avoid ICE, we shouldn't emit actual suggestions when it hasn't closing delims
+        if has_close_delim {
+            err.multipart_suggestion(
+                "change the delimiters to curly braces",
+                vec![
+                    (self.prev_span.with_hi(self.prev_span.lo() + BytePos(1)), '{'.to_string()),
+                    (self.prev_span.with_lo(self.prev_span.hi() - BytePos(1)), '}'.to_string()),
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]: Feels like there's a missing `Span` method here (`self.prev_span.shift_left(...)`)

Comment (JohnTitor) [reply src/librustc_parse/parser/item.rs]: I couldn't find the `shift_left` method: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/struct.Span.html
Am I still missing something?

Comment (Centril) [reply src/librustc_parse/parser/item.rs]: I'm saying that we could add a higher level operation to avoid dealing with primitives like this. :)

Comment (JohnTitor) [reply src/librustc_parse/parser/item.rs]: Ah, so we can add this tweak as a pub method of `Span`, right?

Comment (Centril) [reply src/librustc_parse/parser/item.rs]: Yeah that would be the idea, if we think it's a good one. cc also @petrochenkov

Comment (JohnTitor) [reply src/librustc_parse/parser/item.rs]: I feel it'd be nice that we'll do it as follow-up work?

Comment (Centril) [reply src/librustc_parse/parser/item.rs]: Works for me.

**Comment by JohnTitor** [comment]
I think it's ready to review, could you confirm the diagnostics are valid? @estebank

File: src/librustc_parse/parser/item.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_parse/parser/item.rs]: `SourceMap::next_point` let's you advance 1 char at a time (and is now unicode aware). We don't have a method to move left. It is in `SourceMap` instead of `Span` because you need to look at the underlying code for the span to be validated as not falling in the middle of a character.

Comment (estebank) [reply src/librustc_parse/parser/item.rs]: Also, this might work better with `shrink_to_hi` and `shrink_to_lo` instead of `with_*`.

**Comment by estebank** [comment]
@JohnTitor The output is fine 👍
