### PR TITLE
Parse expression after `else` as a condition if followed by `{`

### LINKED ISSUE #49361: Confusing suggestion when if is missing in else if
``` rust
pub fn nth(n:u32)->Option<u32>{
    let mut x:u32 = 2;
    let mut m:u32 = 1;
    let mut p:Vec<u32> = vec![2];
    'outer: loop {
        x += 1;
        'inner: for i in p.iter() {
            if x % i ==0{
                continue 'outer;
            }
        }
        p.push(x);
        m+=1;
        if n < 1 {
            return None;        
        } else if n == 1 {
            return Some(2);
        } else m == n { // should be else if here
            return Some(x);
        }
    }
}

fn main(){
    println!("{:?}", nth(1));
}
```
The error here is if is missing in else if

but compiler reports: error:

```
error: expected identifier, found keyword `return`
  --> src/main.rs:19:13
   |
19 |             return Some(x);
   |             ^^^^^^
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #49361.

Two things:
1. This wording needs help. I can never find a natural/intuitive phrasing when I write diagnostics :sweat_smile: 
2. Do we even want to show the "wrap in braces" case? I would assume most of the time the "add an `if`" case is the right one.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -2256,15 +2270,49 @@ impl<'a> Parser<'a> {
...
+        let else_span = self.prev_token.span; // `else`
         let attrs = self.parse_outer_attributes()?.take_for_recovery(); // For recovery.
         let expr = if self.eat_keyword(kw::If) {
             self.parse_if_expr(AttrVec::new())?
+        } else if self.check(&TokenKind::OpenDelim(Delimiter::Brace)) {
+            self.parse_simple_block()?
         } else {
-            let blk = self.parse_block()?;
-            self.mk_expr(blk.span, ExprKind::Block(blk, None), AttrVec::new())
+            let snapshot = self.clone();
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/expr.rs:2280]: There's a [`create_snapshot_for_diagnostic`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_parse/parser/struct.Parser.html#method.create_snapshot_for_diagnostic) helper function for doing this that clears some of the internal state of the snapshot that might make it emit diagnostics when dropped.

**Review by davidtwco — CHANGES_REQUESTED** [review]
One suggestion, otherwise looks good to me.

File: src/test/ui/parser/else-no-if.stderr [hunk 2]
```diff
@@ -0,0 +1,54 @@
+error: expected `{`, found keyword `false`
+  --> $DIR/else-no-if.rs:3:7
+   |
+LL |     } else false {
+   |       ^^^^
```
Comment (fmease) [inline src/test/ui/parser/else-no-if.stderr:5]:
```suggestion
   |            ^^^^^
```

Shouldn't the unexpected _expression_ (here: `false`) be highlighted to be in line with the diagnostic message? The `else` is not the unexpected token and thus shouldn't have a primary highlight (maybe only a secondary one for context).
Alternative (with secondary span):

```suggestion
   |       ---- because of this `else`
```

File: src/test/ui/parser/else-no-if.stderr [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+help: ... otherwise, place this expression inside of a block if it is not an `if` condition
+   |
+LL |     } else { false } {
+   |            +       +
+
+error: expected `{`, found `falsy`
+  --> $DIR/else-no-if.rs:10:7
+   |
+LL |     } else falsy() {
+   |       ^^^^
```
Comment (fmease) [inline src/test/ui/parser/else-no-if.stderr:20]:
```suggestion
   |            ^^^^^^^
```

```suggestion
   |       ---- because of this `else`
```

(reasoning as above)

**Review by davidtwco — APPROVED** [review]

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -2256,15 +2270,53 @@ impl<'a> Parser<'a> {
...
+            let snapshot = self.create_snapshot_for_diagnostic();
+            let first_tok = super::token_descr(&self.token);
+            let first_tok_span = self.token.span;
+            match self.parse_expr() {
+                Ok(cond)
+                // If it's not a free-standing expression, and is followed by a block,
+                // then it's very likely the condition to an `else if`.
+                    if self.check(&TokenKind::OpenDelim(Delimiter::Brace))
+                        && classify::expr_requires_semi_to_be_stmt(&cond) =>
+                {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:2289]: Given all the checks you have here...

File: compiler/rustc_parse/src/parser/expr.rs [hunk 5]
```diff
@@ -2256,15 +2270,53 @@ impl<'a> Parser<'a> {
...
+                            "if ".to_string(),
+                            Applicability::MaybeIncorrect,
+                        ).multipart_suggestion(
+                            "... otherwise, place this expression inside of a block if it is not an `if` condition",
+                            vec![
+                                (cond.span.shrink_to_lo(), "{ ".to_string()),
+                                (cond.span.shrink_to_hi(), " }".to_string()),
+                            ],
+                            Applicability::MaybeIncorrect,
+                        )
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:2304]: ...I would have likely skipped this suggestion :)

File: compiler/rustc_parse/src/parser/expr.rs [hunk 6]
```diff
@@ -2256,15 +2270,53 @@ impl<'a> Parser<'a> {
...
+                // If it's not a free-standing expression, and is followed by a block,
+                // then it's very likely the condition to an `else if`.
+                    if self.check(&TokenKind::OpenDelim(Delimiter::Brace))
+                        && classify::expr_requires_semi_to_be_stmt(&cond) =>
+                {
+                    self.struct_span_err(first_tok_span, format!("expected `{{`, found {first_tok}"))
+                        .span_label(else_span, "expected an `if` or a block after this `else`")
+                        .span_suggestion(
+                            cond.span.shrink_to_lo(),
+                            "add an `if` if this is the condition to an chained `if` statement after the `else`",
```
Comment (neoeinstein) [inline compiler/rustc_parse/src/parser/expr.rs:2294]:
```suggestion
                            "add an `if` if this is the condition to a chained `if` statement after the `else`",
```

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:2294]: #97370 addresses this suggestion and @estebank's above.
