### PR TITLE
Trait-associated const fixes

### LINKED ISSUE #25046: Cannot use associated constant in a provided associated method
The compiler fails to compile this:

```
#![feature(associated_consts)]

pub trait Foo {
    const MIN: i32;
    
    fn get_min() -> i32 {
        Self::MIN
    }
}

fn main() {}
```

The error message:
```
main.rs:4:5: 4:20 error: internal compiler error: Encountered error `Unimplemented` when trying to select an implementation for constant trait item reference.
main.rs:4     const MIN: i32;
              ^~~~~~~~~~~~~~~
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:170
```

## Meta

`rustc --version --verbose`:
rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)
binary: rustc
commit-hash: c4b23aec4c5ddf32df1e0ba3cc23212327cd8b1f
commit-date: 2015-04-29
build-date: 2015-04-28
host: x86_64-apple-darwin
release: 1.1.0-nightly

Stack backtrace:
```
   1:        0x10ae5424f - sys::backtrace::write::h0714aaf7fe41e02dzVr
   2:        0x10ae5c8c0 - panicking::on_panic::hb86b9b356f51f92dEVv
   3:        0x10ae18c35 - rt::unwind::begin_unwind_inner::h58f79e41dbedf2efnDv
   4:        0x10a60998e - rt::unwind::begin_unwind::h17476740655312162035
   5:        0x10a60991a - diagnostic::SpanHandler::span_bug::h6ece18e7aebef0b3cFB
   6:        0x108027cfa - middle::const_eval::resolve_trait_associated_const::hfcf715732ac1e584QMi
   7:        0x107fdba61 - middle::const_eval::lookup_const_by_id::hc5a8309a206ad882OOg
   8:        0x107fd58b2 - middle::check_const::check_expr::h4c113c7ea3d8c1ffB2d
   9:        0x107fcd77c - middle::check_const::CheckCrateVisitor<'a, 'tcx>.Visitor<'v>::visit_expr::hdb217d3565a2586cGTd
  10:        0x107fd3e7e - middle::check_const::CheckCrateVisitor<'a, 'tcx>.Visitor<'v>::visit_fn::h37b9b5487c182e36DRd
  11:        0x107fd454e - visit::walk_trait_item::h8343690369834256746
  12:        0x107fd349f - visit::walk_item::h4252660852014709521
  13:        0x107fd2e1c - middle::check_const::CheckCrateVisitor<'a, 'tcx>.Visitor<'v>::visit_item::h3645f3202d46494bKMd
  14:        0x107fdbeea - middle::check_const::check_crate::ha1c34da7b8765db0Hle
  15:        0x107584171 - driver::phase_3_run_analysis_passes::h2554ff95bce00587tGa
  16:        0x10756618c - driver::compile_input::h7c6cf9b085c57594Qba
  17:        0x107625ac3 - run_compiler::h55b523753cbd518765b
  18:        0x10762322a - boxed::F.FnBox<A>::call_box::h11476165885616507686
  19:        0x107622767 - rt::unwind::try::try_fn::h13518150216340287792
  20:        0x10aedec58 - rust_try_inner
  21:        0x10aedec45 - rust_try
  22:        0x107622a4e - boxed::F.FnBox<A>::call_box::h735039165869315632
  23:        0x10ae5b2bd - sys::thread::Thread::new::thread_start::hf4c42a114072ab47mYu
  24:     0x7fff8cfab267 - _pthread_body
  25:     0x7fff8cfab1e4 - _pthread_start
```

### PR DESCRIPTION
**Pull request by quantheory**
Closes #25046 (by rejecting the code that causes the ICE) and #24946. I haven't been able to deal with the array size or recursion issues yet for associated consts, though my hope was that the change I made for range match patterns might help with array sizes, too.

This PR is pretty much orthogonal to #25065.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@quantheory argh, I must again ask your apologies for the delay. I'm going over assigned PRs now and I see this one has been sitting for quite a while!

File: src/librustc_trans/trans/_match.rs [hunk 1]
```diff
@@ -233,7 +233,8 @@ struct ConstantExpr<'a>(&'a ast::Expr);
 
 impl<'a> ConstantExpr<'a> {
     fn eq(self, other: ConstantExpr<'a>, tcx: &ty::ctxt) -> bool {
-        match const_eval::compare_lit_exprs(tcx, self.0, other.0, None) {
+        match const_eval::compare_lit_exprs(tcx, self.0, other.0, None,
+                                            |id| {ty::node_id_item_substs(tcx, id).substs}) {
```
Comment (nikomatsakis) [inline src/librustc_trans/trans/_match.rs]: the usual thing here is not to pass a closure, but rather a `Typer` -- but I'm not sure off-hand if we have a method getting the substs of an id

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -3763,8 +3763,36 @@ pub fn resolve_ty_and_def_ufcs<'a, 'b, 'tcx>(fcx: &FnCtxt<'b, 'tcx>,
...
+
+    // Associated constants can't depend on generic types.
+    fn have_disallowed_generic_consts<'a, 'tcx>(fcx: &FnCtxt<'a, 'tcx>,
+                                                def: def::Def,
+                                                ty: Ty<'tcx>,
+                                                span: Span,
+                                                node_id: ast::NodeId) -> bool {
+        match def {
+            def::DefAssociatedConst(..) => {
+                if ty::type_has_params(ty) || ty::type_has_self(ty) {
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: we probably need to take lifetime parameters into account as well -- I don't know if there's an easy predicate to test for that, though. It seems like it'd be nice have a single flag for "NEEDS_SUBST" that applies to any type which references a `ty_param` or `ReEarlyBound`.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: (Note that lifetime parameters on the trait will be early bound)

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3763,8 +3763,36 @@ pub fn resolve_ty_and_def_ufcs<'a, 'b, 'tcx>(fcx: &FnCtxt<'b, 'tcx>,
...
+                    fcx.sess().span_err(span,
+                                        "Associated consts cannot depend \
+                                         on type parameters or Self.");
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: can you add a diagnostic (and associated code) use the `span_err!` macro?

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (quantheory) [inline src/librustc_typeck/check/mod.rs]: Are you sure that lifetime parameters are relevant? The reason that type parameters are relevant is that they can influence the constant value that you end up with. I don't see how this could be true for lifetime parameters. E.g. I think that if `<&'a Foo>::CONST` can be resolved at all, it should resolve to the same thing as `<&'b Foo>::CONST` and `<&'static Foo>::CONST`?

Hmm, except if you have a trait impl that applies to `<&'a Foo>::CONST`, and an inherent impl that applies only `<&'static Foo>::CONST`, which is *sort of* like a specialization for `'static`? Is that what you mean?

File: src/librustc_trans/trans/_match.rs (hunk 1 above)
Comment (quantheory) [inline src/librustc_trans/trans/_match.rs]: Well, the other thing is that const_eval has to be working already in `collect`, and I'm trying to get resolution of trait-associated constants working there. We don't have `ClosureTyper` and `ParameterEnvironment` in play at that point, and it would be kind of funky to use them that early.

**Comment by quantheory** [comment]
@nikomatsakis I've made the `span_err!` change. Let me know whether/how the other points should be addressed?

**Comment by quantheory** [comment]
@nikomatsakis (Also, on your earlier point, you don't have to apologize. I'll bug you about moving faster or delegating the review if I'm feeling *really* impatient for some reason, but I know that you have lots of important things to do, and a real life and family and all of that. Your insight is always appreciated, though.)

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: @quantheory 

> Are you sure that lifetime parameters are relevant?

So, I think that lifetime parameters are as relevant as type parameters, but thinking on this a bit more I'm actually unclear on why the restriction on type parameters is needed. Am I missing something obvious? Perhaps you can spell out the scenario for me that you are concerned about?

Comment (quantheory) [inline src/librustc_typeck/check/mod.rs]: This is a temporary restriction to prevent ICEs like #25046, until something like rust-lang/rfcs#1062 is implemented. Right now we expect to be able to evaluate constants in `typeck`, but if the constant's value depends on a type parameter, it can't be evaluated until `trans`. To deal with generic constants, we use have something like a projection, but this is much easier to implement in the meantime.

The only reason that a type parameter can affect the value of a const seems to be because it can affect which const we actually resolve to. This doesn't seem to be true of lifetime parameters, so I don't think that we need to worry about them. (And this makes some sense, because constants are... constant, more like statics or macros than something that's restricted to a particular region.) In any case, I haven't been able to construct an equivalent of #25046 that crashes due to a rogue lifetime parameter.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: OK, I see, I was a bit confused. As a temporary bypass for an ICE, this change (probably) makes sense. I thought at first you were imposing a more permanent restriction against associated constants whose types depending on type parameters -- and this didn't seem to make any sense to me, as I don't see any fundamental problem there.

We do need to get our story straight about constants that cannot be resolved until trans, clearly -- seems to me that "constant equality" ought to be handled in a similar way to "type equality" in any case (and hence constant evaluation at type-check time is basically a form of normalization). But I have to finish a write-up talking about normalization and how we should consider a (mildly) different approach there too, so I guess it would apply equally. 

*Anyway*...

**Comment by nikomatsakis** [comment]
@bors r+ 

This seems ok as a temporary hack.

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (tamird) [inline src/librustc_typeck/check/mod.rs]: Is there a tracking issue for this?

Comment (quantheory) [inline src/librustc_typeck/check/mod.rs]: I don't think so. I'd like to get there, but have been tangled up in #22519 and related issues.
