### PR TITLE
Avoid `cfg_if` in `std::os`

### LINKED ISSUE #6038: Unresolved import for platform specific modules
I tried to search if it was reported but didn't found anything.

When importing the platform specific modules in `std::os` rust-analyzer gives me the following error:
`unresolved import`. Also those modules don't show up for auto-complete.

When the module is used outside `use` statement, there is no error, but the semantic token are of the type `unresolvedReference`.

### RA version
Latest master branch

### Example
```rust
use std::os::unix;
```

### PR DESCRIPTION
**Pull request by jonas-schievink**
rust-analyzer cannot currently load the `cfg_if` crate, which means that rust-analyzer is unable to see `std::os::{unix, windows, linux}` here. This works around that by avoiding `cfg_if`; the `#[cfg]` expressions are simple enough to reasonably write by hand.

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6038

### CODE REVIEW

**Comment by jyn514** [comment]
> rust-analyzer cannot currently load the cfg_if crate

Is there an issue open for this?

**Comment by jonas-schievink** [comment]
Well, apart from the issue linked above, no, but I'll create a new one. https://github.com/rust-analyzer/rust-analyzer/issues/6038#issuecomment-751699390 explains in more detail what isn't working.

**Comment by jonas-schievink** [comment]
Opened https://github.com/rust-analyzer/rust-analyzer/issues/7637

File: library/std/src/os/mod.rs [hunk 1]
```diff
@@ -3,40 +3,31 @@
...
-        #[cfg(windows)]
-        #[stable(feature = "rust1", since = "1.0.0")]
-        pub use crate::sys::ext as windows;
-
-        #[cfg(any(target_os = "linux", target_os = "l4re"))]
-        pub mod linux;
-
-    }
-}
+#[cfg(any(doc, target_os = "linux", target_os = "l4re"))]
```
Comment (Mark-Simulacrum) [inline library/std/src/os/mod.rs:29]: Just want to note that this is technically a behavior change -- previously doc and l4re didn't result in a linux module I think -- but that seems fine to me.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/82355#issuecomment-782790775
I guess we missed some targets.
@bors r-
