### PR TITLE
clippy: make tests work in stage 1

### LINKED ISSUE #78717: x.py test --stage 0 src/tools/clippy does not work
```
$ x.py test --stage 0 src/tools/clippy 
Updating only changed submodules
Submodules updated in 0.01 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.09s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.13s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 tool clippy-driver (x86_64-unknown-linux-gnu)
   Compiling clippy v0.0.212 (/home/joshua/rustc/src/tools/clippy)
    Finished release [optimized] target(s) in 1.54s
   Compiling clippy v0.0.212 (/home/joshua/rustc/src/tools/clippy)
    Finished release [optimized] target(s) in 1.49s
     Running build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/clippy_driver-c0ddca9b2ddf2dba

running 1 test
test test_arg_value ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/compile_test-93629616c1644211

running 1 test
test compile_test ... FAILED

failures:

---- compile_test stdout ----
thread 'compile_test' panicked at 'Found multiple rlibs for crate `serde`: `"/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde-0cbb27a77c795012.rlib"` and `"/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde-d748cd52d3612bbb.rlib"', src/tools/clippy/tests/compile-test.rs:46:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Meta

3478d7c3607ffbba629af2265c01002771e48c18

### PR DESCRIPTION
**Pull request by RalfJung**
This finally fixes https://github.com/rust-lang/rust/issues/78717 :)

Similar to what Miri already does, the clippy test step needs to carefully consider  which compiler is used to build clippy and which compiler is linked into clippy (and thus must be used to build the test dependencies). On top of that we have some extra complications that Miri avoided by using `cargo-miri` for building its test dependencies: we need cargo to use the right rustc and the right sysroot, but https://github.com/rust-lang/cargo/issues/4423 makes this quite hard to do. See the long comment in `src/tools/clippy/tests/compile-test.rs` for details.

Some clippy tests tried to import rustc crates; that fundamentally requires a full bootstrap loop so it cannot work in stage 1. I had to kind of guess what those tests were doing so I don't know if my changes there make any sense.

Cc @flip1995 @Kobzol

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/test.rs [hunk 1]
```diff
@@ -768,18 +768,16 @@ impl Step for Clippy {
     fn run(self, builder: &Builder<'_>) {
         let stage = self.stage;
         let host = self.host;
-        let compiler = builder.compiler(stage, host);
-
-        if stage < 2 {
-            eprintln!("WARNING: clippy tests on stage {stage} may not behave well.");
-            eprintln!("HELP: consider using stage 2");
-        }
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/test.rs:776]: There is some logic somewhere that changes the default stage for `./x test clippy` to 2... that can be removed now, but I couldn't find the logic.

File: src/tools/clippy/tests/ui/iter_over_hash_type.rs [hunk 2]
```diff
@@ -3,15 +3,13 @@
...
-
 extern crate proc_macros;
 
 fn main() {
     let mut hash_set = HashSet::<i32>::new();
     let mut hash_map = HashMap::<i32, i32>::new();
-    let mut fx_hash_map = rustc_data_structures::fx::FxHashMap::<i32, i32>::default();
-    let mut fx_hash_set = rustc_data_structures::fx::FxHashMap::<i32, i32>::default();
+    let mut fx_hash_map = rustc_hash::FxHashMap::<i32, i32>::default();
+    let mut fx_hash_set = rustc_hash::FxHashMap::<i32, i32>::default();
```
Comment (RalfJung) [inline src/tools/clippy/tests/ui/iter_over_hash_type.rs]: Adding an entire dependency for this test seems a bit wasteful; is there some way to still test the essence of what this is about without having the full FxHashMap available?

Comment (flip1995) [reply src/tools/clippy/tests/ui/iter_over_hash_type.rs]: > // test type-aliased hashers

IIUC this is only about type aliased hashers. So this should be fully replaceable by `type MyHashMap = HashMap<...>` aliases.

Comment (samueltardieu) [reply src/tools/clippy/tests/ui/iter_over_hash_type.rs]: Yes, the patch at https://rfc1149.pastes.sh/patch-aliased-map.txt could be applied (I tested it in Clippy sources) and gives the same result.

Comment (RalfJung) [reply src/tools/clippy/tests/ui/iter_over_hash_type.rs]: I used a slightly different variant now, should be functionally equivalent.

Comment (samueltardieu) [reply src/tools/clippy/tests/ui/iter_over_hash_type.rs]: Oh, no need, I hadn't seen your new change yet. Perfect.

File: src/tools/clippy/tests/ui/iter_over_hash_type.rs [hunk 3]
```diff
@@ -3,15 +3,18 @@
...
+type FxHashMap<K, V> = HashMap<K, V, FxBuildHasher>;
+type FxHashSet<K> = HashSet<K, FxBuildHasher>;
+
 fn main() {
     let mut hash_set = HashSet::<i32>::new();
     let mut hash_map = HashMap::<i32, i32>::new();
-    let mut fx_hash_map = rustc_data_structures::fx::FxHashMap::<i32, i32>::default();
-    let mut fx_hash_set = rustc_data_structures::fx::FxHashMap::<i32, i32>::default();
+    let mut fx_hash_map = FxHashMap::<i32, i32>::default();
+    let mut fx_hash_set = FxHashMap::<i32, i32>::default();
```
Comment (flip1995) [inline src/tools/clippy/tests/ui/iter_over_hash_type.rs]: I think this was supposed to be


```suggestion
    let mut fx_hash_set = FxHashSet::<i32>::default();
```

Could be 🥷 fixed here.

File: src/tools/clippy/tests/compile-test.rs [hunk 4]
```diff
@@ -151,7 +151,31 @@ impl TestContext {
...
+                    let mut p = CommandBuilder::cargo();
+                    // If we run in bootstrap, we need to use the right compiler for building the
+                    // tests -- not the compiler that built clippy, but the compiler that got linked
+                    // into clippy. Just invoking TEST_RUSTC does not work because LD_LIBRARY_PATH
+                    // is set in a way that makes it pick the wrong sysroot. Sadly due to
+                    // <https://github.com/rust-lang/cargo/issues/4423> we cannot use RUSTFLAGS to
+                    // set `--sysroot`, so we need to use bootstrap's rustc wrapper. That wrapper
+                    // however has some staging logic that is hurting us here, so to work around
+                    // that we set both the "real" and "staging" rustc to TEST_RUSTC, including the
+                    // associated library paths.
```
Comment (RalfJung) [inline src/tools/clippy/tests/compile-test.rs:164]: It should be possible to use a different approach here... somehow, aux builds are working for clippy tests. It seems to be using clippy itself as the compiler for that, and that's somehow okay? So, we could try to do the same here, instead of all this TEST_RUSTC stuff. (That would also be closer to what Miri does.)

But TBH I found something that works so I am not overly inclined to debug a different approach. ;)

**Comment by Kobzol** [comment]
FWIW, I have a WIP branch (there are so many stacked changes to bootstrap that I'm doing rn that it takes a while to unload) where I refactor the building of tools, so that the correct compiler should always be chosen, and we don't need to do this careful dance for each tool and bootstrap Step separately. Essentially we'd invert the compiler "flow" in the tool, so that we pass it the build compiler instead of figuring it out from the tool, and also hopefully we'll be able to get rid of the implicit rmeta/rlib copy into the build compiler's sysroot and make that explicit.

Anyway, I'm fine with this specific fix if it helps the stage 1 Clippy tests in the meantime (it seems like there are some other blockers in the tests themselves, which can be resolved in parallel), just wanted to note that hopefully soonish this will all be unified away so that we always do The Right Thing™.

File: src/bootstrap/src/core/build_steps/test.rs (hunk 1 above)
Comment (RalfJung) [reply src/bootstrap/src/core/build_steps/test.rs:776]: @Kobzol do you know where that logic lives?

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/test.rs:776]: Right there in the Clippy step, 10 lines up xD https://github.com/rust-lang/rust/blob/91d064b44286d87723fc8ef2ae9d8e3d047d12f2/src/bootstrap/src/core/build_steps/test.rs#L758

Comment (RalfJung) [reply src/bootstrap/src/core/build_steps/test.rs:776]: :facepalm:

**Comment by RalfJung** [comment]
I had to add `libc` to test test devs -- on Windows it is not available in the sysroot.

@bors2 try jobs=x86_64-msvc-ext3
