### PR TITLE
Fix ICE with explicit late-bound lifetimes

### LINKED ISSUE #72278: ICE when using lifetime arguments explicitly in late bound lifetime parameters
### Code

Ignore the purpose of the code (it was to create a C-API compatible Box<Any> that can be used to and from C) - [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5f918b37761b38fc297abba5be5c05e2)

```Rust
pub struct RefAny { }

impl RefAny {
    pub fn downcast_mut<'a, U: 'static>(&'a mut self) -> Option<&'a mut U> {
        unsafe { self.downcast_mut_unchecked::<'a, U>() } // <- panic here in lifetime resolution
    }

    unsafe fn downcast_mut_unchecked<'a, U>(&'a mut self) -> Option<&'a mut U> {
        None
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04) running on x86_64-unknown-linux-gnu
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
warning: cannot specify lifetime arguments explicitly if late bound lifetime parameters are present
  --> src/main.rs:78:52
   |
78 |             unsafe { self.downcast_mut_unchecked::<'a, U>() }
   |                                                    ^^
...
82 |     unsafe fn downcast_mut_unchecked<'a, U>(&'a mut self) -> Option<&'a mut U> {
   |                                      -- the late bound lifetime parameter is introduced here
   |
   = note: `#[warn(late_bound_lifetime_arguments)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #42868 <https://github.com/rust-lang/rust/issues/42868>

error: internal compiler error: src/librustc_typeck/check/mod.rs:3314: no type for node HirId { owner: DefIndex(31), local_id: 5 }: type U (hir_id=HirId { owner: DefIndex(31), local_id: 5 }) in fcx 0x7f8e2c3f06e0

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.1 (8d69840ab 2020-05-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] type-checking `RefAny::downcast_mut`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `playground`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_typeck/check/mod.rs:3314: no type for node HirId { owner: DefIndex(31), local_id: 5 }: type U (hir_id=HirId { owner: DefIndex(31), local_id: 5 }) in fcx 0x7fe1f35f06e0

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc_typeck::check::FnCtxt::node_ty
  21: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_ty
  22: rustc_hir::intravisit::walk_generic_args
  23: rustc_hir::intravisit::walk_expr
  24: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
  25: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
  26: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
  27: rustc_hir::intravisit::walk_expr
  28: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
  29: <rustc_typeck::check::writeback::WritebackCx as rustc_hir::intravisit::Visitor>::visit_expr
  30: rustc_typeck::check::writeback::<impl rustc_typeck::check::FnCtxt>::resolve_type_vars_in_body
  31: rustc::ty::context::GlobalCtxt::enter_local
  32: rustc_typeck::check::typeck_tables_of
  33: rustc::ty::query::__query_compute::typeck_tables_of
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  37: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  38: rustc_typeck::check::typeck_item_bodies
  39: rustc::ty::query::__query_compute::typeck_item_bodies
  40: rustc::dep_graph::graph::DepGraph::with_task_impl
  41: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  42: rustc_typeck::check_crate
  43: rustc_interface::passes::analysis
  44: rustc::ty::query::__query_compute::analysis
  45: rustc::dep_graph::graph::DepGraph::with_task_impl
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  47: rustc::ty::context::tls::enter_global
  48: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by cofibrant**
Rather than returning an explicit late-bound lifetime as a generic argument count mismatch (which is not necessarily true), this PR propagates the presence of explicit late-bound lifetimes.

This avoids an ICE that can occur due to the presence of explicit late-bound lifetimes when building generic substitutions by explicitly ignoring them.

r? @varkor

cc @davidtwco (this removes a check you introduced in #60892)

Resolves #72278

### CODE REVIEW

File: src/librustc_typeck/astconv.rs [hunk 1]
```diff
@@ -132,13 +138,22 @@ enum GenericArgPosition {
...
     pub invalid_args: Vec<Span>,
 }
 
+/// Decorates the result of a generic argument count mismatch
+/// check with whether explicit late bounds were provided.
+#[derive(Clone)]
+pub struct GenericArgCountResult {
+    pub explicit_late_bound: ExplicitLateBound,
+    pub correct: Result<(), GenericArgCountMismatch>,
+}
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs:155]: Couldn't this information go into the `GenericArgCountMismatch`?

Comment (doctorn) [reply src/librustc_typeck/astconv.rs:155]: The problem is we want to warn not error at the moment (introducing an error would be a breaking change - see #42868), so basically we end up with situations where we might not have a generic arg count mismatch but we still have explicit late bounds. That's part of what's causing the ICE. (If you `#[deny(warnings)]` the ICE disappears.)

**Comment by doctorn** [comment]
Reading, I think @nikomatsakis's suggestion [here](http://www.smallcultfollowing.com/babysteps/blog/2013/10/29/intermingled-parameter-lists/#my-proposed-solution) is probably the right answer, but we'd definitely have to wait for a new edition before it could be integrated.

File: src/test/ui/issues/issue-72278.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+    fn func<'a, U>(&'a self) -> U {
+        todo!()
+    }
+}
+
+fn dont_crash<'a, U>() -> U {
+    S.func::<'a, U>()
+    //~^ WARN cannot specify lifetime arguments explicitly
+    //~| WARN this was previously accepted
+}
```
Comment (nikomatsakis) [inline src/test/ui/issues/issue-72278.rs:17]: Do we have tests for all the other random scenarios that can occur? It seems like we should try to test them all -- in particular the case of "got a lifetime but expected something else"...

Comment (doctorn) [reply src/test/ui/issues/issue-72278.rs:17]: I was under the impression that

- [src/test/ui/methods/method-call-lifetime-args.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/methods/method-call-lifetime-args.rs)
- [src/test/ui/methods/method-call-lifetime-args-fail.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/methods/method-call-lifetime-args-fail.rs)

cover pretty much everything but I could be wrong

File: src/librustc_typeck/astconv.rs (hunk 1 above)
Comment (doctorn) [reply src/librustc_typeck/astconv.rs:155]: So #42868 lists two future PRs, one to make the lint deny-by-default, and the other to turn the warning into a hard error. Making the lint deny-by-default would still require this patch, but if we jumped straight to a hard error, then none of this work is necessary. It doesn't resolve the issue that this is still a breaking change though, but I guess that might not matter so much seeing as it's already broken?

File: src/test/ui/issues/issue-72278.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/issues/issue-72278.rs:17]: Those tests look pretty good. I guess they don't cover lifetimes + types intermixed. But I'm satisfied.

**Comment by nikomatsakis** [comment]
So I guess r=me with comment applied
