### PR TITLE
Replace hardcoded forward slash with path::MAIN_SEPARATOR

### LINKED ISSUE #40149: Slash (/) in diagnostic's path on Windows
```
cargo new app
```

src/lib.rs: `mod f;`

src/f/mod.rs: `f`

```
cargo build
```

```
error: expected one of `!` or `::`, found `<eof>`
 --> src\f/mod.rs:1:1
```

It must be src\f **\\** mod.rs, but it is src\f **/** mod.rs

src/f/mod.rs: `mod g;`

src/f/g/mod.rs: `g`

```
cargo build
```

```
error: expected one of `!` or `::`, found `<eof>`
 --> src\f\g/mod.rs:1:1
```

### PR DESCRIPTION
**Pull request by laumann**
Fixes #40149

### CODE REVIEW

**Comment by BurntSushi** [comment]
@laumann Thanks!

**Comment by laumann** [comment]
@BurntSushi Thank you :-)

Also came across https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L5307 - can it be fixed here or is it too late?

**Comment by BurntSushi** [comment]
@laumann Probably not a good idea to add commits after a PR has been r+'d. I think it will rightyfully cause the PR to fail to merge.

The new changes look OK. Could you please squash them down to a single commit please?

**Comment by laumann** [comment]
@BurntSushi OK, can I fix it here, or should I open a new PR?

**Comment by BurntSushi** [comment]
@laumann You can fix it here by squashing your branch locally (probably with a rebase) and then force pushing.

**Comment by laumann** [comment]
OK, no problem, thanks :-)

**Comment by laumann** [comment]
Rebased. Something went wrong with https://travis-ci.org/rust-lang/rust/jobs/212496260, but I can't really tell what.

**Comment by BurntSushi** [comment]
@laumann You need to merge changes from master back into this PR because someone else has made changes since submitting your PR that conflict with your changes.

You can do this by checking out your `master` branch and re-syncing it with `master` on `rust-lang/rust`, usually with `git pull origin master --ff-only` (assuming `origin` points to `rust-lang/rust` and not your fork). Then checkout your PR branch, `git checkout slash-in-diagnostics-path`, and rebase it on to master.

**Comment by laumann** [comment]
@BurntSushi Rebased.

**Comment by BurntSushi** [comment]
@laumann Thanks!

**Comment by frewsxcv** [comment]
I think this is causing a test failure on Windows:

https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2460/job/kfyqxp0uxi22y3lk

@bors r-

**Comment by laumann** [comment]
@frewsxcv You are right - it looks like `test/parse-fail/mod_file_not_exists.rs` which makes sense :-) I'll get it fixed!

Why is that test in parse-fail and not compile-fail?

**Comment by laumann** [comment]
It seems the issue can be fixed several ways, but which one would be preferred?

1. Duplicate the test in `parse-fail/mod_file_not_exists_windows.rs` and add:
```
// ignore-gnu
// ignore-android
// ignore-bitrig
// ignore-macos
// ignore-dragonfly
// ignore-freebsd
// ignore-haiku
// ignore-ios
// ignore-linux
// ignore-netbsd
// ignore-openbsd
// ignore-solaris
// ignore-emscripten
```
and add `ignore-windows` to `parse-fail/mod_file_not_exists.rs`

2. Convert the test to a run-make test (suggested by @jseyfried), to make it easier to switch on OS

But I'm wondering what the preferred approach is...

I tried fiddling with `#[cfg(windows)]` and something like:
```
#[cfg(windows)]
mod not_a_real_file; //[windows]~ ERROR file not found for module `not_a_real_file`
//[windows]~^ HELP name the file either not_a_real_file.rs or not_a_real_file\mod.rs inside the directory

#[cfg(not(windows))]
mod not_a_real_file; //[not(windows)]~ ERROR file not found for module `not_a_real_file`
//[not(windows)]~^ HELP name the file either not_a_real_file.rs or not_a_real_file/mod.rs inside the directory


fn main() {
    assert_eq!(mod_file_aux::bar(), 10);
}
```
But that trick didn't work :-)

**Comment by laumann** [comment]
@BurntSushi Should I prefer to amend the existing commit, or should I just add new ones (to fix the test)?

**Comment by BurntSushi** [comment]
@laumann Amend the existing commit. We shouldn't have broken commits. :-)

**Comment by laumann** [comment]
@BurntSushi The build failed, but I can't really tell why - is there some way to try again?

**Comment by BurntSushi** [comment]
@laumann I kicked it.

**Comment by laumann** [comment]
@BurntSushi Yay! Thanks :-)

**Comment by laumann** [comment]
@frewsxcv It should be fixed now, not sure if I need to do anything else.

File: src/test/parse-fail/mod_file_not_exist.rs [hunk 1]
```diff
@@ -8,6 +8,8 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+// ignore-windows
```
Comment (BurntSushi) [inline src/test/parse-fail/mod_file_not_exist.rs]: It doesn't seem OK to ignore this test on Windows.

@alexcrichton What should we do here? This PR is changing a few places to use the native path separator when printing file paths, so I assume this test is failing because the error messages don't compare equal. Is there a way to do conditional testing based on platform?

Comment (BurntSushi) [inline src/test/parse-fail/mod_file_not_exist.rs]: I now see that there is another test in this PR, `mod_file_not_exist_windows.rs`, which essentially does this. But it's done by exhausting every non-Windows platform. Is that the right way to do this?

Comment (laumann) [inline src/test/parse-fail/mod_file_not_exist.rs]: @BurntSushi I considered different approaches - this could maybe be turned into a run-make test instead.

I went for this solution, because I looked at `src/test/codegen/dllimports/main.rs` (and others) that do windows-specific things by exhausting the other options.

Comment (BurntSushi) [inline src/test/parse-fail/mod_file_not_exist.rs]: Precedence is good enough for me.

Comment (BurntSushi) [inline src/test/parse-fail/mod_file_not_exist.rs]: Thanks!

Comment (laumann) [inline src/test/parse-fail/mod_file_not_exist.rs]: Thank you :-)

Ah, of course, you have to r+ it! I was wondering why it wasn't being tested again...

**Comment by laumann** [comment]
@BurntSushi Should I rebase again?

**Comment by BurntSushi** [comment]
Yup. Looks like something else got merged that conflicts with this, so you'll need to rebase to resolve conflicts.

**Comment by laumann** [comment]
Will do

**Comment by laumann** [comment]
Seems to be good now. :crossed_fingers:
