### PR TITLE
Suggest removing parentheses surrounding lifetimes

### LINKED ISSUE #57386: Suggest removing parenthesis surrounding lifetimes
[Given](https://github.com/rust-lang/rust/blob/1f64f60d5cba64beca6e812e16d6d99519d3551b/src/test/ui/parser/trait-object-lifetime-parens.rs):

```
trait Trait {}
fn f<'a, T: Trait + ('a)>() {}
```
suggest the correct syntax
```
error: parenthesized lifetime bounds are not supported
  --> $DIR/trait-object-lifetime-parens.rs:5:24
   |
LL | fn f<'a, T: Trait + ('a)>() {}
   |                        ^
help: remove the braces
   |
LL | fn f<'a, T: Trait + 'a>() {}
   |                     ^^
```

### PR DESCRIPTION
**Pull request by igorsdv**
Fixes #57386.

r? @estebank

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -5377,9 +5378,21 @@ impl<'a> Parser<'a> {
...
+                        let inner_span = inner_lo.to(self.prev_span);
                         self.expect(&token::CloseDelim(token::Paren))?;
-                        self.span_err(self.prev_span,
-                                      "parenthesized lifetime bounds are not supported");
+                        let mut err = self.struct_span_err(
+                            lo.to(self.prev_span),
+                            "parenthesized lifetime bounds are not supported"
+                        );
+                        if let Ok(snippet) = self.sess.source_map().span_to_snippet(inner_span) {
+                            err.span_suggestion_short_with_applicability(
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Please rebase against latest master and change to `span_suggestion_short` (this method was renamed and all of them now require the applicability flag).

R=me after this.

**Comment by oli-obk** [comment]
@igorsdv Unfortunately github does not send us notifications when a PR has been force pushed. In order to get a faster review after force pushing, you can leave a comment on the PR.
