### PR TITLE
Avoid calling the column!() macro in panic

### LINKED ISSUE #43057: My code fails to build with „unexpected end of macro invocation“ since nightly 2017-07-02
Hello

I have this code: https://gitlab.labs.nic.cz/turris/pakon-aggregator (unfortunately, I don't have a minimal code example yet). It fails with `rustc 1.20.0-nightly (067971139 2017-07-02)` (for some reason this is the version I get if I run `rustup default nightly-2017-07-03`, it seems to be one day off) and newer, but passes with older versions of nighly as well as stable and beta.

The error I get is:

```
error: unexpected end of macro invocation
   --> src/keeper/column.rs:269:1
    |
269 | / column! {
270 | |     /// Identifier of an address inside an endpoint.
271 | |     ///
272 | |     /// This is usually used to specify aggregation by a value in queries.
...   |
357 | |     name Port u16;
358 | | }
    | |_^ in this macro invocation
    |
    = note: this error originates in a macro outside of the current crate
```

This is actually [my own macro](https://gitlab.labs.nic.cz/turris/pakon-aggregator/blob/master/src/keeper/column.rs#L55), so the „originates in a macro outside of the current crate“ part is wrong. Also, renaming the macro makes it compile again. This leads me to think something (the compiler) brought in a colliding macro with the same name.

Is my theory about the colliding macro true? Can this killing of my poor innocent macro be prevented somehow? Should local macros have precedence? Or, at least, should I get a better error message, like complaining when I *define* the macro, not when I *use* it? This makes me think that if I had the bad luck of having a same-name macro with the same invocation syntax, it would silently expand the wrong one.

# Exact version

```
$ rustc --version --verbose
rustc 1.20.0-nightly (067971139 2017-07-02)
binary: rustc
commit-hash: 0679711398bef656699e1ff6b004ecccbdb67284
commit-date: 2017-07-02
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0
```

### PR DESCRIPTION
**Pull request by est31**
Closes #43057

This "fix" adds a new macro called `__rust_unstable_column` and to use it instead of the `column` macro inside panic. The new macro can be shadowed as well as `column` can, but its very likely that there is no code that does this in practice.

There is no real way to make "unstable" macros that are usable by stable macros, so we do the next best thing and prefix the macro with `__rust_unstable` to make sure people recognize it is unstable.

r? @alexcrichton

### CODE REVIEW

**Comment by arielb1** [comment]
> There is no real way to make "unstable" macros that are usable by stable macros

Yes there is - macros 2.0.

File: src/libcore/macros.rs [hunk 1]
```diff
@@ -8,6 +8,16 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+#[macro_export]
+// This stability attribute is totally useless.
+#[stable(feature = "rust1", since = "1.0.0")]
```
Comment (durka) [inline src/libcore/macros.rs]: Maybe wishful thinking, but if we ever fix macro stability checking it'd be good to have accurate info here. Also for rustdoc purposes.

Comment (est31) [inline src/libcore/macros.rs]: The attribute is useless because a) stability attributes on macros are generally useless, and b) because of the `#[cfg(stage0)]` below. This won't have any impact on anything presented to users of the compiler. This entire macro definition may be removed if we switch stage0.

Comment (durka) [inline src/libcore/macros.rs]: Oh OK, missed the `#[cfg(stage0)]`. So it will never even reach rustdoc. Carry on then.

**Comment by alexcrichton** [comment]
Thanks @est31!

Could this be made as "real unstable" via the [same mechanism as `global_asm`](https://github.com/rust-lang/rust/blob/b2bf1639ac88afd4c163aac99cfdf6d6816e3c7d/src/libsyntax_ext/global_asm.rs#L37-L45) perhaps?

**Comment by est31** [comment]
@alexcrichton I don't think this will work? Because the `cx` refers to the leaf crate's context (where the macro is being expanded), so a feature gate like this would require users of the panic macro to have a `#![feature()]` attribute in their crate root.

**Comment by alexcrichton** [comment]
Hm yeah that's true. Perhaps the span could be checked though for `allow_internal_unstable`?
