### PR TITLE
De-duplicate consecutive libs when printing native-static-libs

### LINKED ISSUE #113209: many unexpected duplicates in --print native-static-libs output in some configurations
Hi there,

In [rustls-ffi](https://github.com/rustls/rustls-ffi) we use `RUSTFLAGS="--print native-static-libs" cargo build` to try and keep our crate's linking instructions up-to-date across supported platforms.

We've noticed that in some build configurations the output can change in surprising ways.

For instance, using rustc nightly (1.70.0) on Windows (x86_64-pc-windows-msvc) in a `--debug` configuration driven by `cmake` we see _many_ consecutive duplicate libraries in the `--print-native-static-libs` output.

I understand duplicates are to be expected, and can be meaningful on some platforms, but seeing so many consecutive repeats seems unexpected and unlikely to be meaningful for the build process.

Is this perhaps a regression? Or are we making a mistake by relying on the stability of this output across versions/build configurations? This feature is [documented](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information) as having a known prefix to "make it easier to fetch the output." leading to the idea that it is expected to be machine consumable.

### Code

I tried this code:

```
RUSTFLAGS="--print native-static-libs" cargo build 
```

I expected to see this happen:

A list produced, with some duplicates (e.g. multiple `kernel32.lib`), but not many consecutive duplicates. E.g.:

```
advapi32.lib credui.lib kernel32.lib secur32.lib legacy_stdio_definitions.lib kernel32.lib advapi32.lib bcrypt.lib kernel32.lib ntdll.lib userenv.lib ws2_32.lib kernel32.lib ws2_32.lib kernel32.lib msvcrt.lib
```

Instead, this happened:

A list with many consecutive duplicates is produced:

```
advapi32.lib credui.lib kernel32.lib secur32.lib legacy_stdio_definitions.lib kernel32.lib advapi32.lib advapi32.lib bcrypt.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib kernel32.lib ntdll.lib ntdll.lib ntdll.lib ntdll.lib userenv.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib ws2_32.lib kernel32.lib ws2_32.lib kernel32.lib kernel32.lib msvcrt.lib
```
</details>

### Version it worked on

rustc nightly (1.70.0) on Windows (x86_64-pc-windows-msvc) in a `--release` configuration.

### Version with regression

rustc nightly (1.70.0) on Windows (x86_64-pc-windows-msvc) in a `--debug` configuration.

### Extra links

Project: https://github.com/rustls/rustls-ffi
CMakeLists.txt: https://github.com/rustls/rustls-ffi/blob/2508f98ebb39be6103c78183e42ba94d70d9dd07/CMakeLists.txt
Build task: https://github.com/rustls/rustls-ffi/blob/2508f98ebb39be6103c78183e42ba94d70d9dd07/.github/workflows/test.yaml#L73-L93

### PR DESCRIPTION
**Pull request by Urgau**
This PR adds a de-duplicate step just before printing the `native-static-libs`.

This step de-duplicates all the consecutive libs based only on the relevant comparison elements (this exclude spans, ast elements, ...).

Fixes https://github.com/rust-lang/rust/issues/113209

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -1391,6 +1391,11 @@ fn print_native_static_libs(
 ) {
     let mut lib_args: Vec<_> = all_native_libs
         .iter()
+        // Deduplicate consecutive repeated librairies, see rust-lang/rust#113209
+        //
+        // note: we don't use PartialEq/Eq because NativeLib transitivly depends on local
+        // item like spans, which we don't care here and would make the deduplication impossible
+        .dedup_by(|l1, l2| l1.name == l2.name && l1.kind == l2.kind && l1.verbatim == l2.verbatim)
         .filter(|l| relevant_lib(sess, l))
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1399]: Deduplication needs to be performed after `relevant_lib` filtering, otherwise you'll have issues like https://github.com/rust-lang/rust/pull/85554.

Comment (Urgau) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Fixed.

**Comment by bjorn3** [comment]
Some dylibs need to be present multiple times to handle circular dependencies. Whatever logic you use for this printing please make sure that it also works for rustc doing linking of a dylib or executable too.

**Comment by Urgau** [comment]
> Some libraries need to be present multiple times to handle circular dependencies. Whatever logic you use for this printing please make sure that it also works for rustc doing linking of a dylib or executable too.

As stated in the PR description, this PR only removes **consecutive** libs and does not touch libs that are present multiple times but not consecutive. That means that instead of generating (before this PR):
```
-lunwind -lunwind -lunwind -lsystemd -lunwind
```
we would now generate:
```
-lunwind -lsystemd -lunwind
```
Given this I don't think there is any issues with circular dependencies since linker args are still present (just not consecutive duplicated).

**Comment by bjorn3** [comment]
Right, no objections in that case.
