### PR TITLE
Fix Debug for Location

### LINKED ISSUE #142279: `panic::Location` `Debug` implementation now prints a byte array
Since https://github.com/rust-lang/rust/pull/135054, the `Debug` implementation for `std::panic::Location` just prints the byte bag:

```rust
fn main() {
    dbg!(std::panic::Location::caller());
}
```

Stable:

```text
[src/main.rs:2:5] std::panic::Location::caller() = Location {
    file: "src/main.rs",
    line: 2,
    col: 10,
}
```

Nightly:

```text
[src/main.rs:2:5] std::panic::Location::caller() = Location {
    file_bytes_with_nul: [
        115,
        114,
        99,
        47,
        109,
        97,
        105,
        110,
        46,
        114,
        115,
        0,
    ],
    line: 2,
    col: 10,
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=698066c5427dd43cb12df0d2fb5b9300

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes https://github.com/rust-lang/rust/issues/142279

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]

File: library/coretests/tests/panic/location.rs [hunk 1]
```diff
@@ -29,3 +29,11 @@ fn location_const_column() {
     const COLUMN: u32 = CALLER.column();
     assert_eq!(COLUMN, 40);
 }
+
+#[test]
+fn location_debug() {
+    let f = format!("{:?}", Location::caller());
+    assert!(f.contains("location.rs"));
```
Comment (joshtriplett) [inline library/coretests/tests/panic/location.rs]:
```suggestion
    assert!(f.contains("location.rs"));
    assert!(!f.contains("\0"));
    assert!(!f.contains("\\0"));
```

File: library/coretests/tests/panic/location.rs [hunk 2]
```diff
@@ -29,3 +29,11 @@ fn location_const_column() {
...
+    assert!(f.contains("35"));
```
Comment (tgross35) [inline library/coretests/tests/panic/location.rs:37]: I suppose `(line!() - 2).to_string()` would be more robust to test changes than literal 35

Comment (m-ou-se) [reply library/coretests/tests/panic/location.rs:37]: Sure. But the other tests in this file also just hardcode the number. I like putting as little logic as possible in tests.

File: library/coretests/tests/panic/location.rs (hunk 1 above)
Comment (m-ou-se) [reply library/coretests/tests/panic/location.rs]: I immediately clicked 'commit suggestion', but actually: i think this might cause funny failures:

If someone works on windows in a directory that starts with a `0`, the file name might be `"C:\\Users\\0abc\\Rust\\..."`, which will contain `\\0`.

File: library/coretests/tests/panic/location.rs (hunk 2 above)
Comment (tgross35) [reply library/coretests/tests/panic/location.rs:37]: Didn't realize the entire file hardcodes them, 🤷‍♂️ in that case

File: library/coretests/tests/panic/location.rs (hunk 1 above)
Comment (m-ou-se) [reply library/coretests/tests/panic/location.rs]: I changed it to `assert!(f.contains(&format!("{:?}", file!())));`. That way, it checks the entire file name *including* the surrounding quotes. Then we can be sure there's no additional `\0` displayed.

**Review by tgross35 — APPROVED** [review]
Could use a squash, r=me again after that

**Comment by tgross35** [comment]
@m-ou-se I just squashed the last two for you so we can get this fix in. Thanks!

@bors r+ rollup
