### PR TITLE
Run borrowck tests on BIDs and emit tail-expr-drop-order lints for violations

### LINKED ISSUE #132861: Possible false-negative with `tail-expr-drop-order`
There may be a false-negative with `tail-expr-drop-order`. Reproduction:

1. `curl -L https://crates.io/api/v1/crates/faer-core/0.17.1/download | tar -xz`
2. cd `faer-core-0.17.1`
3. Set up cargo-features and a git repo: `git init . && sed -i '1i cargo-features = ["edition2024"]' Cargo.toml && git add . && git commit -m test`
4. `cargo fix --edition`

On current nightly (2024-11-09), this generates a large number of warnings about tail-expr-drop-order. However, none of them are in the offending function `swap_cols`. Additionally, after #131326, there are no warnings at all.

After switching to 2024, this yields an error:

```
error[E0716]: temporary value dropped while borrowed
     --> src/lib.rs:10425:69
      |
10425 |           $crate::zip::ZipEq::new($crate::zip::ViewMut::view_mut(&mut { $head }), $crate::zipped!($($tail,)*))
      |                                                                       ^^^^^^^^^                              - temporary value is freed at the end of this statement
      |                                                                       |
      |                                                                       creates a temporary value which is freed while still in use
      |
     ::: src/permutation.rs:304:9
      |
304   | /         zipped!(
305   | |             mat_a.const_cast().as_2d_mut(),
306   | |             mat_b.const_cast().as_2d_mut(),
307   | |         )
      | |_________- in this macro invocation
308   |       }
309   |       .for_each(|unzipped!(mut a, mut b)| {
      |        -------- borrow later used by call
      |
      = note: consider using a `let` binding to create a longer lived value
      = note: this error originates in the macro `zipped` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Unfortunately that crate is a maze of types and generics, so it is a bit difficult to minimize.

I'm just assuming this is a tail expression drop change due to the shape of the error.

It does not seem related to the macro, since manually expanding it also does not change anything.

I would expect tail-expr-drop-order to at least warn something here. 

cc @dingxiangfei2009 

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (59cec72a5 2024-11-08)
binary: rustc
commit-hash: 59cec72a57af178767a7b8e7f624b06cc50f1087
commit-date: 2024-11-08
host: aarch64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #132861 

r? @nikomatsakis 
cc @compiler-errors 

This patch enlarges the scope where the `tail-expr-drop-order` lint applies, so that all locals involved in tail expressions are inspected. This is necessary to run borrow-checking to capture the cases where it used to compile under Edition 2021 but is not going to pass borrow-checking from Edition 2024 onwards.

The way it works is to inspect each BID against the set of borrows that are still live. If the local involved in BID has a borrow index which happens to be live as well at the location of this BID statement, in the future this will be a borrow-checking violation. The lint will fire in this case.

### CODE REVIEW

File: compiler/rustc_borrowck/src/lib.rs [hunk 1]
```diff
@@ -994,6 +997,23 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, '_, 'tcx> {
         }
     }
 
+    fn maybe_polonius_borrows_in_scope<'s>(
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/lib.rs:1000]: why does this mention polonius at all? why isn't this just called borrows_in_scope?

Comment (dingxiangfei2009) [reply compiler/rustc_borrowck/src/lib.rs]: Yes, let's.

I am tucking the comment into this function, too.

File: compiler/rustc_borrowck/src/lib.rs [hunk 2]
```diff
@@ -1136,6 +1146,46 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, '_, 'tcx> {
...
+    #[instrument(level = "debug", skip(self, state))]
+    fn check_backward_incompatible_drop(
+        &mut self,
+        location: Location,
+        place_span: (Place<'tcx>, Span),
+        state: &BorrowckDomain,
+    ) {
+        let sd = AccessDepth::Drop;
+
+        // Use polonius output if it has been enabled.
```
Comment (lqd) [inline compiler/rustc_borrowck/src/lib.rs:1160]:
```suggestion
```

**Review by nikomatsakis — APPROVED** [review]

**Comment by dingxiangfei2009** [comment]
I have prepared the following craterbot message.

```
@craterbot run start=master#11663cd3bfefef7d34e8f0892c250bf698049392 end=try#9b5e8b16bd1c4acf4cf8e6880368314cf021a987 mode=build-only +rustflags=-Dtail-expr-drop-order
```

- I would like to check the difference in lint effects with `-Dtail-expr-drop-order` before and after, to see if there is any false positives and negatives.
- `build-only` is required, because #134493 is still not on `master` yet. Otherwise, we could use `check-only` for the experiment.

Shall we double-check and give this a go afterwards? Big thanks!

**Comment by lqd** [comment]
A perf run shouldn't show anything since this shouldn't be enabled by default. However, some of these previous PRs have been unexpected regressions, let's check.

@rust-timer build 9b5e8b16bd1c4acf4cf8e6880368314cf021a987

**Comment by compiler-errors** [comment]
@craterbot run start=master#11663cd3bfefef7d34e8f0892c250bf698049392+rustflags=-Dtail-expr-drop-order end=try#9b5e8b16bd1c4acf4cf8e6880368314cf021a987+rustflags=-Dtail-expr-drop-order mode=build-only

**Comment by Skgland** [comment]
I ran <https://github.com/Skgland/Crater-Analysis> to classify the `build failed (unknown)` regressions.

31091 contain `error: internal compiler error:` so are likly ICEs, from a small sample these are all in dependencies of the tested crate so likely not classified as a deps breakage due to the problem I am trying to fix in rust-lang/crater#758 .

85 failures appear to be due to running out of disk space, 
either containing `no space left on device` or in one instance `collect2: fatal error: ld terminated with signal 7 [Bus error]` 

<details>
<summary>84 contain no string my tool is searching for</summary>

```rust
["12e9881f53658734f7d0005e8f9091def068a65.currently_logged_in_user.bde0ba1490ce443cc8df1d5fef592370d0fd04c3", "13jon37.thething.5284b7f804d91e2e973e4d32912503f21e605ad8", "AlbinEriksson.aoc2023.0d5a9cdd3a34fb9d3c3f0bbef74ece2e85700799", "Apsapeh.ncvm_asm.275f3f73976f863bbeda685819b394ff38cd4ef9", "Aym-n.ChessEngine.6599f770fb5cd5ae8c15d664f986c96f1c6b284d", "CryZe.sysprog-web.1e8334823e48dd3aa5cd62f468fe35993f8b940b", "EpicEric.aoc-2024.d735c25d3fb7926eadadd22d71953f41dfcc4f54", "Flying-Toast.lang.9586e323c23abf9a57dc074d09470eac07f59259", "Foolish1337.hook_32.197270ca0d75c5012db60ef940edbf5f1a752955", "GabrielBFern.aoc2020.82cb1f4118ad1bbecd9c9a76275fd10ee44f8dc2", "JanBerktold.jute-rust.0a9a534599efa22a7c317c1b9963ac2438ac028b", "Jobin-Nelson.aoclib.d56913b61be69cfe132f5332e1bd4e1a541a4c41", "KavinduShamalka.rust_addnames.a7aeddf247ddc1e9cc4c357a8d229bd3ea69de59", "Mike-Neto.advent-of-code-2022.84a91bd7308dfce7e5b1b6a5ad5ae578854e0f5d", "QuaeroEtTego.file-adder.7d80ea1bef7198366ba1c07de54ef7fc9d69a664", "RastislavTuranyi.point_group.273487f1016ce49ecf29162a993b4ea85e5de2ef", "Redempt.crunch_eval.16fd11837205c842fc94e3112eedc6db124e7659", "Wopple.bookcase-rs.ce12f79a71946ea65b637b34773af863f1c034fd", "Zemogus.AOC-2023.328dc6618f3a360c3d3851ad1b10513a6c133336", "alttch.owfs-rs.ba53c801883a6edddf46c77c8612d482ccc6e7e1", "butzist.lc-1-two-sum.3f14af8810ec4f8a4ac6890d0afe2d021b4812c3", "datdenkikniet.cucumber.7f0c056ba57ed7978bf6e520f6ead988ccf25ca5", "emk.snappy_framed-rs.be6a886b52ecb23aff7d3b048f1445cba26ce9c2", "evomassiny.rlox.a196b86f50ef4d5e1f681e9d38875fc8ee9d8c65", "hardglitch.xmath.bda74b1d575c7c65e13558c361f26947597295aa", "hashedone.aoc2020.62ee99c624e1fdff664d4b11084ebe032ac0ddf7", "hfaulds.queue.22f94b3e2b94551d132996144296714b5b5cd27b", "higumachan.zero-rust-regex.8732c7af51d5de65474ef0aae1a0cd3eb44454ad", "hmpthcs.eLisDo.d1a872f553c215175b661cf49c5eb806005be538", "irreducible-io.term-rewriting.546119b6ecbd8ef8c0270bc7893e28d3286384e1", "jeroen-rooijmans.advent-of-code-2024-rust.08505115fb47f962d8fd9a8d0e899298a836b104", "john-the-inhaler.terminal_juice.a1a714a6b4b2ef00658930f4948f409bb69ac27a", "kirisaki.jit-compiler.5ceb89cb2a39b0f5cfe69ae1cb7944580f41eb89", "konradpoweska.aoc2022.8c145244dea75eeeac528646d99003a053700c6d", "meddion.fugue.9ad7c4b881efcb66a6edde1681a01aadc4a12142", "mii443.breakout-checker.62e4dabd9f7940cbf0bed01793284cf1bfe20b75", "oliverjantar.advent-of-code-2022.0c7289d006686c28edfc55b6dd960eb8c43d5121", "overlandandseas.aoc_2024.064a2239233e52b1cdba1d4c8c196f706044d318", "paddison.aoc23.4dfc510d5306e7a588cc1681edb66769b7cc4880", "poursa.AOC2024-Rust.c6e0d6f8108867310231f566e10e731ed2417668", "raviqqe.stak.d6fa9052b0eea9e9276da15a1ac60e06b251ce1e", "realprogrammersusevim.aoc-2024.8d0f7785a0eb16468725ec09ec4625315f906125", "rkevingibson.AoC2021.5e8e8ac898b42564f7ae5dbcaa8b395304113e18", "rush-rs.rush.dbcbfa8177fb3529bbf709d6c8452941b71305d5", "scupit.gcmake-rust.50476479f7776605d30e7f1a40026c3a13e85d7b", "sidit77.clipboard-typer.e8801650bb8632b45a8f94b9f6ea104731a1348b", "ssav7912.rust-FreeD.6f1bbd038d6746ae06276034375dcba78453bef3", "tannermpeterson.AoC-2024.c95d24ad3695ae1cd46cdf881e3f1d85c33c4af4", "tobyjsullivan.titan.1f414a81fa705273b7872272b79af9f6993cbf38", "whitequark.touptek-acquire.1222080870ec572204d75d2f349e7d3554809bca", "winksaville.exper_message_trait.1222f3a4dfab69747e073cd147115425dad23fd9", "yoo2001818.rust-8086.9fbf118c5ce50759d79c48adbf643f4dc882f6ef", "zackyvt.jack-compiler.9e2dc8e9cc676818c3f5a20f070c4948565c5eeb", "blink-alloc-0.3.1", "blsctl-0.2.3", "bookcase_alloc-0.0.2", "brotli-decompressor-4.0.1", "corsairmi-2.0.1+deprecated", "crypto-brainfuck-0.2.0", "enigo-copy-0.0.14", "ext4-view-0.7.0", "include-bytes-plus-1.1.0", "input-0.9.1", "libcgroup_rs-0.1.0", "libmpv-sirno-2.0.2-fork.1", "libmpv-2.0.1", "macsmc-0.1.7", "noct-0.1.0", "owfs-0.1.0", "papi-bindings-0.5.3", "plumber-rs-0.1.2", "postgres-extension-0.1.1", "protobuf3-2.27.2", "rsplit-0.1.2", "rusty-cl-0.1.8", "rx509-0.2.1", "split-0.1.0", "sweep-bptree-0.4.1", "urcu-0.0.3", "uwasm-0.2.0", "vec-with-gaps-0.7.0", "wowdbdefs-rs-0.1.0", "yarn-spool-0.1.0", "zinc64-emu-0.8.0"]
```

</details>

**Comment by compiler-errors** [comment]
@bors try

Need to re-run crater after #134575 was merged

**Comment by compiler-errors** [comment]
`craterbot run start=master#8d2c06d151972fefa3f0bbf04ace3beede737145+rustflags=-Dtail-expr-drop-order end=try#45e7e02865cae718624ebeb3feed6d2f7848b800+rustflags=-Dtail-expr-drop-order mode=build-only`

**Comment by compiler-errors** [comment]
@craterbot run start=master#8d2c06d151972fefa3f0bbf04ace3beede737145+rustflags=-Dtail-expr-drop-order end=try#45e7e02865cae718624ebeb3feed6d2f7848b800+rustflags=-Dtail-expr-drop-order mode=check-only

**Comment by Skgland** [comment]
I ran https://github.com/Skgland/Crater-Analysis to classify the `build failed (unknown)` regressions.

Mostly Cycle Detection Errors, some running out of disk space, two ices and some other problems.

ICEs
- [gh/alv-around.openvm-sdk-example](https://crater-reports.s3.amazonaws.com/pr-134523-1/try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/alv-around.openvm-sdk-example/log.txt)
- [gh/scroll-tech.rust-zstd-decompressor](https://crater-reports.s3.amazonaws.com/pr-134523-1/try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/scroll-tech.rust-zstd-decompressor/log.txt)

Others:
- rustc stack overflow
- 2x `error: a temporary value will be dropped here before the execution exits the block in Edition 2024, which will raise borrow checking error` in dependencies
- 3x (c)make can't build something due to some missing file
- 3x linking fails due to missing file
- cmake cannot create directory
- docker no such file or directory

<details>
<summary>Full report</summary>

```
Regressed: 984
build failed(unknown): 527
----------------------------------
Results:
E0391: 388
ice: 2
no-space: 126
----------------------------------
sum: 516
others: 11
----------------------------------
[
    (
        "JakeDawkins.graphql-client-302-repro.0378a702e84d04a3d3a7b20fdfbbf3ce2d2e728c",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/JakeDawkins.graphql-client-302-repro",
    ),
    (
        "MoAlyousef.objectif.bd283ccd33e664b22fada4311f438c0e69d0ca40",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/MoAlyousef.objectif",
    ),
    (
        "dbydd.dawdle-todo-backend.fb1a455e344738cc2aca38fc7cf62f8a70314619",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/dbydd.dawdle-todo-backend",
    ),
    (
        "gnicod.earthel.d3fd147b82db0c7c034402ec6db1c9649b2cfaf5",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/gnicod.earthel",
    ),
    (
        "jhbruhn.ics-adapter.300a22f5ea1558967c8a8d1bd873c02a779ceffd",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/jhbruhn.ics-adapter",
    ),
    (
        "lfn3.pyru-graphql.47e488e25b1ace40f22401b90fd65dcbf2cbfe05",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/lfn3.pyru-graphql",
    ),
    (
        "llpghn.mqtt_monitor.88cd673821c0784719c85a29003670e138c4d85a",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/llpghn.mqtt_monitor",
    ),
    (
        "vasily-kirichenko.DropTest.9e4abfe0738df924002113d8859c50ea21cdd04e",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/gh/vasily-kirichenko.DropTest",
    ),
    (
        "dbus-executor-0.1.0",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/reg/dbus-executor-0.1.0",
    ),
    (
        "ministo-0.1.0",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/reg/ministo-0.1.0",
    ),
    (
        "wordexp-0.1.0",
        "try%2345e7e02865cae718624ebeb3feed6d2f7848b800%2Brustflags=-Dtail-expr-drop-order/reg/wordexp-0.1.0",
    ),
]
```

</details>

**Comment by compiler-errors** [comment]
@craterbot run start=master#dcfa38fe234de9304169afc6638e81d0dd222c06+rustflags=-Dtail-expr-drop-order end=try#214d5c94d03280918aa7845a8377fe60924de7b4+rustflags=-Dtail-expr-drop-order mode=check-only

**Comment by compiler-errors** [comment]
I believe I've fixed the ICEs and the cycle errors, and I'll rerun crater on just the subset of failing crates.

@craterbot crates=https://crater-reports.s3.amazonaws.com/pr-134523-1/retry-regressed-list.txt

**Review by nikomatsakis — APPROVED** [review]

**Comment by compiler-errors** [comment]
This will need a beta backport if we want this lint to trigger with the edition

@rustbot label: +beta-nominated

**Comment by dingxiangfei2009** [comment]
@compiler-errors Thank you for your help! 🙏

Niko Matsakis ***@***.***> schrieb am Di. 7. Jan. 2025 um
03:47:

File: compiler/rustc_borrowck/src/lib.rs [hunk 3]
```diff
@@ -1149,6 +1161,61 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, '_, 'tcx> {
         error_reported
     }
 
+    /// Through #123739, backward incompatible drops (BIDs) are introduced.
```
Comment (apiraino) [inline compiler/rustc_borrowck/src/lib.rs:1164]: @dingxiangfei2009 A tiny late nit. I have just learned from this comment what `BID` stand for. Is it a commonly used acronym? I wasn't able to find it using a search engine. Could only find it disentangled here.

(thanks @lqd for the pointing me here)

**Comment by dingxiangfei2009** [comment]
Hey @apiraino. BID is a shorthand that is  unfortunately not well
documented yet. It refers to backward-incompatible drop statements
generated exclusively when edition migration is run. It is defined in
https://github.com/rust-lang/rust/blob/b6b8361bce8561fb8786ad33ca1abfdf4bc487b6/compiler/rustc_middle/src/mir/syntax.rs#L440.
It does not have any semantic significance other than being a hint that
lints can rely on and can be treated safely as a NOP.

apiraino ***@***.***> schrieb am Do. 9. Jan. 2025 um 11:59:

**Comment by lqd** [comment]
note for t-release if the backport is approved: the backport will likely not apply cleanly due to landing after #133858. I hit similar conflicts when doing a revert, so the conflicting pieces will be present and fixed in #135263. (But if there are issues, dingxiangfei/errs/I should be able to prepare it for you.)

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-01-09/near/492745358). A backport PR will be authored by the release team at the end of the current development cycle. Backport labels  handled by them.

@rustbot label +beta-accepted
