### PR TITLE
rustdoc: improve refdef handling in the unresolved link lint

### LINKED ISSUE #133150: rustdoc skips first line of some list items, and incorrect clippy warning
I tried this code (minimal reproduction `lib.rs`):

```rust
/// - [`SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER`]: the
///   `(__unsafe_unretained)` NSWindow associated with the window, if you want
///   to wrap an existing window.
/// - [`SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER`]: the `(__unsafe_unretained)`
///   NSView associated with the window, defaults to `[window contentView]`
pub fn a() {}

/// - [`SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER`]: the maximum texture width
///   and height
/// - [`SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER`]: a (const [`SDL_PixelFormat`] *)
///   array of pixel formats, terminated with [`SDL_PIXELFORMAT_UNKNOWN`],
///   representing the available texture formats for this renderer.
pub fn b() {}

pub const SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER: () = ();
pub const SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER: () = ();

pub const SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER: () = ();
pub const SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER: () = ();
pub const SDL_PIXELFORMAT_UNKNOWN: () = ();
#[allow(non_camel_case_types)]
pub type SDL_PixelFormat = ();
```

When I run `cargo doc` on this, there are no warnings or errors, but the output is wrong. The first line of the first list item of `a` is missing, and the first line of the second list item of `b` is also missing.

Image
Image

If I run `cargo clippy` on the file it complains:
```
warning: doc list item without indentation
 --> src/lib.rs:3:5
  |
3 | ///   to wrap an existing window.
  |     ^^
  |
  = help: if this is supposed to be its own paragraph, add a blank line
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
  = note: `#[warn(clippy::doc_lazy_continuation)]` on by default
help: indent this line
  |
3 | ///                                                          to wrap an existing window.
  |       +++++++++++++++++++++++++++++++++++++++++++++++++++++++

warning: doc list item without indentation
  --> src/lib.rs:12:5
   |
12 | ///   representing the available texture formats for this renderer.
   |     ^^
   |
   = help: if this is supposed to be its own paragraph, add a blank line
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
help: indent this line
   |
12 | ///                                                                                    representing the available texture formats for this renderer.
   |       +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

warning: `rustdocbug` (lib) generated 2 warnings
```
But this makes no sense. Those lines have the correct indentation, same as the previous lines. It seems to think there's a new sublist getting created at the end of the first lines, but I don't see why

### Meta
`rustc --version --verbose`:
```
% rustc --version --verbose
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: aarch64-apple-darwin
release: 1.82.0
LLVM version: 19.1.1

% rustc +nightly --version --verbose
rustc 1.84.0-nightly (798fb83f7 2024-10-16)
binary: rustc
commit-hash: 798fb83f7d24e31b16acca113496f39ff168c143
commit-date: 2024-10-16
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.1
```

### PR DESCRIPTION
**Pull request by notriddle**
This commit takes advantage of a feature in pulldown-cmark that makes the list of link definitions available to the consuming application. It produces unresolved link warnings for refdefs that aren't used, and can now produce exact spans for the dest even when it has escapes.

Closes #133150 since this lint would have caught the mistake in that issue, and, along with https://github.com/rust-lang/rust-clippy/pull/13707, most mistakes in this class should produce a warning from one of them.

### CODE REVIEW

File: tests/rustdoc-ui/intra-doc/weird-syntax.rs [hunk 1]
```diff
@@ -117,24 +117,49 @@ pub struct WLinkToCloneWithUnmatchedEscapedCloseParenAndDoubleSpace;
...
-/// [cln]: Clone() //~ERROR link
+/// The [cln][] link here is going to be unresolved, because `Clone()` gets
+//~^ ERROR link
+/// rejected in Markdown for not being URL-shaped enough.
+/// [cln]: Clone()
+//~^ ERROR link
 pub struct LinkToCloneWithParensInReference;
 
-/// The [cln][] link here is going to be unresolved, because `struct@Clone` gets //~ERROR link
-/// rejected in Markdown for not being URL-shaped enough.
```
Comment (notriddle) [inline tests/rustdoc-ui/intra-doc/weird-syntax.rs:127]: This comment was wrong.

`struct@Clone` is URL-ish enough to match CommonMark's refdef grammar. The reason it was rejected before was because the `//~ERROR link` hot comment got fed to the markdown parser, and, as a result, caused the refdef to not get parsed there.

By using a below-the-line comment, I can work around that and demonstrate the change correctly.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 2]
```diff
@@ -439,13 +441,25 @@ fn parse_links<'md>(doc: &'md str) -> Vec<Box<str>> {
...
+                    refids.insert(id);
+                }
 
                 links.push(preprocess_link(&dest_url));
             }
             _ => {}
         }
     }
 
+    for (label, refdef) in event_iter.reference_definitions().iter() {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/rustdoc.rs:457]: This logic is run on a compiler's happy path, when rustdoc and its lints are not involved.
Could you do a perf run before merging this?

**Comment by notriddle** [comment]
Not a problem.

@bors try @rust-timer queue

**Comment by notriddle** [comment]
The two regressions are both `doc` builds, tiny, and they come with a diagnostic that can help people out of a pretty bad syntax hole.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It's really cool, great idea! Perf impact seems acceptable to me. Not sure if we are waiting on petrochenkov or not so I'll let you r+.

**Comment by notriddle** [comment]
> This logic is run on a compiler's happy path, when rustdoc and its lints are not involved.
> Could you do a perf run before merging this?

The result of the lint is no perf impacts other than rustdoc, so it shouldn't be a problem.

@bors r=GuillaumeGomez

**Comment by notriddle** [comment]
Rebased it. This change required weird-syntax.stderr to be re-blessed because of a minor output change:

```diff
- LL | /// [cln]: trait@Clone
-    |            ~~~~~~
+ LL - /// [cln]: struct@Clone
+ LL + /// [cln]: trait@Clone
```

@bors r=GuillaumeGomez
