### PR TITLE
Make bootstrap git tests more self-contained

### LINKED ISSUE #140387: bootstrap config tests failing locally
> When I run the bootstrap tests locally I get the failure new failures. Could this PR be responsible?

```text
running 119 tests
........................................................................
core::config::tests::test_local_changes_subtree_that_used_bors ... F

core::config::tests::test_local_committed_modifications ... F
..............  88/119
...............................

failures:

---- core::config::tests::test_local_changes_subtree_that_used_bors stdout ----
Running cd "/tmp/.tmpQ834nG" && "git" "init"
Running cd "/tmp/.tmpQ834nG" && "git" "config" "user.name" "Tester"
Running cd "/tmp/.tmpQ834nG" && "git" "config" "user.email" "tester@rust-lang.org"
Running cd "/tmp/.tmpQ834nG" && "git" "add" "."
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "branch" "-m" "main"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "checkout" "-b" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "add" "."
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "switch" "main"
Running cd "/tmp/.tmpQ834nG" && "git" "merge" "--no-commit" "--no-ff" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "Merge of previous-pr into main" "--author" "Merge bot <merge-bot@rust-lang.org>"
Running cd "/tmp/.tmpQ834nG" && "git" "branch" "-d" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "switch" "--orphan" "subtree"
Running cd "/tmp/.tmpQ834nG" && "git" "add" "."
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "checkout" "-b" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "add" "."
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "switch" "subtree"
Running cd "/tmp/.tmpQ834nG" && "git" "merge" "--no-commit" "--no-ff" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "Merge of previous-pr into subtree" "--author" "Merge bot <merge-bot@rust-lang.org>"
Running cd "/tmp/.tmpQ834nG" && "git" "branch" "-d" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "--amend" "--date" "Wed Feb 16 14:00 2011 +0100" "--no-edit"
Running cd "/tmp/.tmpQ834nG" && "git" "switch" "main"
Running cd "/tmp/.tmpQ834nG" && "git" "merge" "subtree" "--allow-unrelated"
Running cd "/tmp/.tmpQ834nG" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpQ834nG" && "git" "checkout" "-b" "previous-pr"
Running cd "/tmp/.tmpQ834nG" && "git" "add" "."
Running cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"

thread 'core::config::tests::test_local_changes_subtree_that_used_bors' panicked at src/bootstrap/src/utils/tests/git.rs:125:13:
Git command `cd "/tmp/.tmpQ834nG" && "git" "commit" "-m" "commit message"` failed
Stdout
On branch previous-pr
nothing to commit, working tree clean
Stderr


---- core::config::tests::test_local_committed_modifications stdout ----
Running cd "/tmp/.tmpHfIPXx" && "git" "init"
Running cd "/tmp/.tmpHfIPXx" && "git" "config" "user.name" "Tester"
Running cd "/tmp/.tmpHfIPXx" && "git" "config" "user.email" "tester@rust-lang.org"
Running cd "/tmp/.tmpHfIPXx" && "git" "add" "."
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "branch" "-m" "main"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "checkout" "-b" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "add" "."
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "switch" "main"
Running cd "/tmp/.tmpHfIPXx" && "git" "merge" "--no-commit" "--no-ff" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "Merge of previous-pr into main" "--author" "Merge bot <merge-bot@rust-lang.org>"
Running cd "/tmp/.tmpHfIPXx" && "git" "branch" "-d" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "checkout" "-b" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "add" "."
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "commit message"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "switch" "main"
Running cd "/tmp/.tmpHfIPXx" && "git" "merge" "--no-commit" "--no-ff" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "--abbrev-ref" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "Merge of previous-pr into main" "--author" "Merge bot <merge-bot@rust-lang.org>"
Running cd "/tmp/.tmpHfIPXx" && "git" "branch" "-d" "previous-pr"
Running cd "/tmp/.tmpHfIPXx" && "git" "rev-parse" "HEAD"
Running cd "/tmp/.tmpHfIPXx" && "git" "checkout" "-b" "feature"
Running cd "/tmp/.tmpHfIPXx" && "git" "add" "."
Running cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "commit message"

thread 'core::config::tests::test_local_committed_modifications' panicked at src/bootstrap/src/utils/tests/git.rs:125:13:
Git command `cd "/tmp/.tmpHfIPXx" && "git" "commit" "-m" "commit message"` failed
Stdout
On branch feature
nothing to commit, working tree clean
Stderr



failures:
    core::config::tests::test_local_changes_subtree_that_used_bors
    core::config::tests::test_local_committed_modifications
```

_Originally posted by @nnethercote in https://github.com/rust-lang/rust/issues/138591#issuecomment-2827461198_
            
UPD: still fails even if fully default git config is used

```
thread 'core::config::tests::test_local_committed_modifications' panicked at src/bootstrap/src/utils/tests/git.rs:125:13:
Git command `cd "/tmp/.tmpMwcVVE" && GIT_CONFIG_NOSYSTEM="1" GIT_CONFIG_SYSTEM="/tmp/non-existent-config" "git" "commit" "-m" "commit message"` failed
Stdout
On branch feature
nothing to commit, working tree clean
Stderr
```

### PR DESCRIPTION
**Pull request by Kobzol**
Based on https://stackoverflow.com/a/67512433/1107768.

Fixes: https://github.com/rust-lang/rust/issues/140387

r? @jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Actually good point. I should try `GIT_CONFIG_NOSYSTEM` *additionally* for my rustc-dev-guide sync attempts too :skull:

Thanks!

**Comment by Kobzol** [comment]
Yeah we might set it in the josh tooling scripts.

File: src/bootstrap/src/utils/tests/git.rs [hunk 1]
```diff
@@ -129,6 +129,9 @@ impl GitCtx {
 
     fn git_cmd(&self) -> Command {
         let mut cmd = Command::new("git");
+        cmd.env("GIT_CONFIG_NOSYSTEM", "1");
+        cmd.env("GIT_CONFIG_SYSTEM", "/tmp/nonexistent");
+        cmd.env("GIT_CONFIG_GLOBAL", "/tmp/nonexistent");
```
Comment (jieyouxu) [inline src/bootstrap/src/utils/tests/git.rs:134]: I hope we don't also have to override `$HOME` or `$XDG_USER_HOME` somehow (cf. https://git-scm.com/docs/git#Documentation/git.txt-codeGITCONFIGNOSYSTEMcode)
