### PR TITLE
Partially fix `explicit_outlives_requirements` lint in macros

### LINKED ISSUE #106044: Wrong suggestion for `explicit_outlives_requirements` in macro
### Steps to reproduce

```sh
git clone https://github.com/serde-rs/serde
cd serde
git switch --detach v1.0.151
RUSTFLAGS=-Wexplicit-outlives-requirements cargo +stage1 check
```

### Meta

master at 2d8651a92761421b0437ffb44ba5670bea5ee1df

config.toml:
```toml
profile = "compiler"
changelog-seen = 2

[rust]
debuginfo-level = 1 # show line numbers
debug = true

[llvm]
assertions = true
```

### Error output

```
thread 'rustc' panicked at 'Span must not be empty and have no suggestion', /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic.rs:633:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
--SNIP--
  16:     0x7f0d5c49725a - rust_begin_unwind
                               at /home/lukas/code/rust/library/std/src/panicking.rs:575:5
  17:     0x7f0d5c47e103 - core::panicking::panic_fmt::h1cf4116ecb7f2344
                               at /home/lukas/code/rust/library/core/src/panicking.rs:64:14
  18:     0x7f0d5f59f399 - <rustc_errors[6144feb2896255d4]::diagnostic::Diagnostic>::multipart_suggestion_with_style::<rustc_error_messages[e3220e15e8c2fcd5]::SubdiagnosticMessage>
                               at /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic.rs:633:9
  19:     0x7f0d5f5f5360 - <rustc_errors[6144feb2896255d4]::diagnostic::Diagnostic>::multipart_suggestion::<rustc_error_messages[e3220e15e8c2fcd5]::SubdiagnosticMessage>
                               at /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic.rs:601:9
  20:     0x7f0d5f5f5360 - <rustc_errors[6144feb2896255d4]::diagnostic_builder::DiagnosticBuilder<()>>::multipart_suggestion::<rustc_error_messages[e3220e15e8c2fcd5]::SubdiagnosticMessage>
                               at /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic_builder.rs:375:13
  21:     0x7f0d5f633299 - <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/builtin.rs:2388:25
  22:     0x7f0d5f633299 - <<rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0} as core[584d80f921d3c2b7]::ops::function::FnOnce<(&mut rustc_errors[6144feb2896255d4]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
                               at /home/lukas/code/rust/library/core/src/ops/function.rs:422:5
  23:     0x7f0d5f5a20a1 - <alloc[bca6fb222e2b29c7]::boxed::Box<dyn for<'a, 'b> core[584d80f921d3c2b7]::ops::function::FnOnce<(&'a mut rustc_errors[6144feb2896255d4]::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = &'a mut rustc_errors[6144feb2896255d4]::diagnostic_builder::DiagnosticBuilder<'b, ()>>> as core[584d80f921d3c2b7]::ops::function::FnOnce<(&mut rustc_errors[6144feb2896255d4]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
                               at /home/lukas/code/rust/library/alloc/src/boxed.rs:1990:9
  24:     0x7f0d5f626ba4 - rustc_middle[3d80386755b367e]::lint::struct_lint_level::struct_lint_level_impl::<rustc_error_messages[e3220e15e8c2fcd5]::DiagnosticMessage>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/lint.rs:466:9
  25:     0x7f0d5f62437a - rustc_middle[3d80386755b367e]::lint::struct_lint_level::<rustc_error_messages[e3220e15e8c2fcd5]::DiagnosticMessage, <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/lint.rs:470:5
  26:     0x7f0d5f5c31e8 - <rustc_middle[3d80386755b367e]::ty::context::TyCtxt>::struct_span_lint_hir::<alloc[bca6fb222e2b29c7]::vec::Vec<rustc_span[bb221821e4c136c5]::span_encoding::Span>, rustc_error_messages[e3220e15e8c2fcd5]::DiagnosticMessage, <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:2263:9
  27:     0x7f0d5f5e7fde - <rustc_lint[950f5d5b3082c6d3]::context::LateContext as rustc_lint[950f5d5b3082c6d3]::context::LintContext>::lookup::<alloc[bca6fb222e2b29c7]::vec::Vec<rustc_span[bb221821e4c136c5]::span_encoding::Span>, rustc_error_messages[e3220e15e8c2fcd5]::DiagnosticMessage, <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/context.rs:1028:24
  28:     0x7f0d5f5e7fde - <rustc_lint[950f5d5b3082c6d3]::context::LateContext as rustc_lint[950f5d5b3082c6d3]::context::LintContext>::struct_span_lint::<alloc[bca6fb222e2b29c7]::vec::Vec<rustc_span[bb221821e4c136c5]::span_encoding::Span>, rustc_error_messages[e3220e15e8c2fcd5]::DiagnosticMessage, <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/context.rs:932:9
  29:     0x7f0d5f55ed67 - <rustc_lint[950f5d5b3082c6d3]::builtin::ExplicitOutlivesRequirements as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/builtin.rs:2383:17
  30:     0x7f0d5f5b9898 - <rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass as rustc_lint[950f5d5b3082c6d3]::passes::LateLintPass>::check_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/passes.rs:93:13
  31:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:136:17
  32:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_param_env::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:76:9
  33:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:135:13
  34:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:63:9
  35:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:134:9
  36:     0x7f0d5f5fb6c9 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_nested_item
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:238:13
  37:     0x7f0d5f5fe9b3 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_stmt
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:174:9
  38:     0x7f0d5f5c949c - rustc_hir[c0973907b1a4476]::intravisit::walk_block::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:592:5
  39:     0x7f0d5f5d516b - rustc_hir[c0973907b1a4476]::intravisit::walk_expr::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
  40:     0x7f0d5f5fe00c - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_expr::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:163:13
  41:     0x7f0d5f5fe00c - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:63:9
  42:     0x7f0d5f5fe00c - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_expr
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:161:9
  43:     0x7f0d5f5fd0c2 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_body
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:125:9
  44:     0x7f0d5f5fd0c2 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_nested_body
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:108:9
  45:     0x7f0d5f5fed31 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_fn
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:191:9
  46:     0x7f0d5f5cbf1b - rustc_hir[c0973907b1a4476]::intravisit::walk_impl_item::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:1011:13
  47:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:285:17
  48:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_param_env::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:76:9
  49:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:283:13
  50:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:63:9
  51:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:282:9
  52:     0x7f0d5f5fbdfd - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_nested_impl_item
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:258:13
  53:     0x7f0d5f5d77ec - rustc_hir[c0973907b1a4476]::intravisit::walk_impl_item_ref::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:1039:5
  54:     0x7f0d5f5d77ec - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_impl_item_ref
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:386:9
  55:     0x7f0d5f5d77ec - rustc_hir[c0973907b1a4476]::intravisit::walk_item::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:523:13
  56:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:137:17
  57:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_param_env::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:76:9
  58:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:135:13
  59:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:63:9
  60:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:134:9
  61:     0x7f0d5f5fb6d4 - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c0973907b1a4476]::intravisit::Visitor>::visit_nested_item
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:238:13
  62:     0x7f0d5f5d29dc - rustc_hir[c0973907b1a4476]::intravisit::walk_mod::<rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:557:9
  63:     0x7f0d5f600f9d - <rustc_lint[950f5d5b3082c6d3]::late::LateContextAndPass<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>>::process_mod
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:82:9
  64:     0x7f0d5f600f9d - rustc_lint[950f5d5b3082c6d3]::late::late_lint_mod_inner::<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:375:5
  65:     0x7f0d5f600f9d - rustc_lint[950f5d5b3082c6d3]::late::late_lint_mod::<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedModuleLateLintPass>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:358:9
  66:     0x7f0d5f5b519d - rustc_lint[950f5d5b3082c6d3]::lint_mod
                               at /home/lukas/code/rust/compiler/rustc_lint/src/lib.rs:127:5
  67:     0x7f0d5ecdae24 - <rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:342:53
  68:     0x7f0d5ecdae24 - <rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:58:46
  69:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::enter_context::<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:50
  70:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::set_tlv::<rustc_middle[3d80386755b367e]::ty::context::tls::enter_context<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1295:9
  71:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::enter_context::<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:9
  72:     0x7f0d5ecdae24 - <rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:58:13
  73:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::with_context::<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1339:40
  74:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::with_context_opt::<rustc_middle[3d80386755b367e]::ty::context::tls::with_context<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1328:22
  75:     0x7f0d5ecdae24 - rustc_middle[3d80386755b367e]::ty::context::tls::with_context::<<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1339:9
  76:     0x7f0d5ecdae24 - <rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind as rustc_query_system[242f28f82f33429e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:55:9
  77:     0x7f0d5ec69718 - <rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:342:22
  78:     0x7f0d5ec69718 - <rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepGraph<rustc_middle[3d80386755b367e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[3d80386755b367e]::ty::context::TyCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:290:13
  79:     0x7f0d5e9d42cf - rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job::<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:471:13
  80:     0x7f0d5e9d42cf - stacker[5d738903658daaa0]::maybe_grow::<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  81:     0x7f0d5e9d42cf - rustc_data_structures[92ac3f36488757b]::stack::ensure_sufficient_stack::<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  82:     0x7f0d5e9d42cf - <rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query::<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:128:17
  83:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::enter_context::<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:50
  84:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::set_tlv::<rustc_middle[3d80386755b367e]::ty::context::tls::enter_context<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1295:9
  85:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::enter_context::<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:9
  86:     0x7f0d5e9d42cf - <rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query::<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:127:13
  87:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::with_related_context::<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1355:13
  88:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::with_context::<rustc_middle[3d80386755b367e]::ty::context::tls::with_related_context<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1339:40
  89:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::with_context_opt::<rustc_middle[3d80386755b367e]::ty::context::tls::with_context<rustc_middle[3d80386755b367e]::ty::context::tls::with_related_context<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1328:22
  90:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::with_context::<rustc_middle[3d80386755b367e]::ty::context::tls::with_related_context<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1339:9
  91:     0x7f0d5e9d42cf - rustc_middle[3d80386755b367e]::ty::context::tls::with_related_context::<<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>::{closure#0}, ((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1352:9
  92:     0x7f0d5e9d42cf - <rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt as rustc_query_system[242f28f82f33429e]::query::QueryContext>::start_query::<((), rustc_query_system[242f28f82f33429e]::dep_graph::graph::DepNodeIndex), rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>::{closure#3}>
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:112:9
  93:     0x7f0d5e9d42cf - rustc_query_system[242f28f82f33429e]::query::plumbing::execute_job::<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:460:9
  94:     0x7f0d5e9d42cf - rustc_query_system[242f28f82f33429e]::query::plumbing::try_execute_query::<rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt, rustc_query_system[242f28f82f33429e]::query::caches::VecCache<rustc_span[bb221821e4c136c5]::def_id::LocalDefId, ()>>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:379:44
  95:     0x7f0d5eac01d1 - rustc_query_system[242f28f82f33429e]::query::plumbing::get_query::<rustc_query_impl[dec3f3edb2b7f47f]::queries::lint_mod, rustc_query_impl[dec3f3edb2b7f47f]::plumbing::QueryCtxt>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:760:36
  96:     0x7f0d5e7fa0a5 - <rustc_query_impl[dec3f3edb2b7f47f]::Queries as rustc_middle[3d80386755b367e]::ty::query::QueryEngine>::lint_mod::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:721:17
  97:     0x7f0d5e7fa0a5 - <rustc_query_impl[dec3f3edb2b7f47f]::Queries as rustc_middle[3d80386755b367e]::ty::query::QueryEngine>::lint_mod
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/lib.rs:45:1
  98:     0x7f0d5d12ad31 - std[2237cce644beac22]::panicking::try::do_call::<core[584d80f921d3c2b7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[92ac3f36488757b]::sync::par_for_each_in<&[rustc_hir[c0973907b1a4476]::hir_id::OwnerId], <rustc_middle[3d80386755b367e]::hir::map::Map>::par_for_each_module<rustc_lint[950f5d5b3082c6d3]::late::check_crate<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedLateLintPass, rustc_interface[387306c137d4009]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/lukas/code/rust/library/std/src/panicking.rs:483:40
  99:     0x7f0d5d12ad31 - std[2237cce644beac22]::panicking::try::<(), core[584d80f921d3c2b7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[92ac3f36488757b]::sync::par_for_each_in<&[rustc_hir[c0973907b1a4476]::hir_id::OwnerId], <rustc_middle[3d80386755b367e]::hir::map::Map>::par_for_each_module<rustc_lint[950f5d5b3082c6d3]::late::check_crate<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedLateLintPass, rustc_interface[387306c137d4009]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
                               at /home/lukas/code/rust/library/std/src/panicking.rs:447:19
 100:     0x7f0d5d0f40e5 - std[2237cce644beac22]::panic::catch_unwind::<core[584d80f921d3c2b7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[92ac3f36488757b]::sync::par_for_each_in<&[rustc_hir[c0973907b1a4476]::hir_id::OwnerId], <rustc_middle[3d80386755b367e]::hir::map::Map>::par_for_each_module<rustc_lint[950f5d5b3082c6d3]::late::check_crate<rustc_lint[950f5d5b3082c6d3]::BuiltinCombinedLateLintPass, rustc_interface[387306c137d4009]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/lukas/code/rust/library/std/src/panic.rs:137:14
--SNIP--

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [lint_mod] linting module `de::impls`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

https://github.com/rust-lang/rust/blob/2d8651a92761421b0437ffb44ba5670bea5ee1df/compiler/rustc_lint/src/builtin.rs#L2388-L2395

@rustbot label requires-debug-assertions E-needs-mcve

### LINKED ISSUE #106063: Wrong suggestion for `explicit_outlives_requirements` in macro, part 2
Given the following code: [clicky](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7b4ab9f9a1b99a7fe1660374f832a3ba)

```rust
#![warn(explicit_outlives_requirements)]
#![allow(dead_code)]

macro_rules! make_baz {
    ($a:lifetime, $b:lifetime) => {
        struct Baz<$a, $b: $a> where (): Sized, $b: $a {
            baz: &$a &$b (),
        }
    };
}

make_baz!{ 'a, 'b }
```

The current output is:

```
warning: outlives requirements can be inferred
  --> src/lib.rs:6:49
   |
6  |         struct Baz<$a, $b: $a> where (): Sized, $b: $a {
   |                                                 ^
...
12 | make_baz!{ 'a, 'b }
   | -----------^^^^^^-- in this macro invocation
   |
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![warn(explicit_outlives_requirements)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this warning originates in the macro `make_baz` (in Nightly builds, run with -Z macro-backtrace for more info)
help: remove these bounds
   |
6  ~         struct Baz<$a, $b: $a> where (): Sized, $b: $a {
7  |             baz: &$a &$b (),
 ...
11 | 
12 ~ make_baz!{  }
   |

warning: `rust-test` (lib) generated 1 warning (run `cargo fix --lib -p rust-test` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
```

Notice the invalid machine applicable suggestion.

Ideally the output should look like: Probably no warning at all?

related to https://github.com/rust-lang/rust/issues/106044

@rustbot label A-suggestion-diagnostics A-lifetimes D-invalid-suggestion

### PR DESCRIPTION
**Pull request by lukas-code**
Show the suggestion if and only if the bounds are from the same source context.

fixes https://github.com/rust-lang/rust/issues/106044
fixes https://github.com/rust-lang/rust/issues/106063

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler (on vacation)

File: compiler/rustc_ast_lowering/src/item.rs [hunk 1]
```diff
@@ -1377,21 +1377,8 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-                    None
-                } else if let Some(span) = span {
-                    Some(span.to(bound_span))
-                } else {
-                    Some(bound_span)
-                }
-            })
-            .unwrap_or(param_span.shrink_to_hi());
+        let span =
+            bounds.iter().fold(param_span.shrink_to_hi(), |span, bound| span.to(bound.span()));
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/item.rs:1381]: IMO, the issue is that we are trying to reconstruct a span during lowering, which will mix spans coming from macro different expansions.
Fortunately, we know what `SyntaxContext` produces the `:`, it's `GenericParam::colon_span`.
So there are 2 cases here:
- if `colon_span` is `None`, we should use `param_span.shrink_to_hi()`;
- if not, we should use it, and extend it with `bound.span().find_ancestor_in_same_ctxt(colon_span.ctxt())`.

File: compiler/rustc_lint/src/builtin.rs [hunk 2]
```diff
@@ -2184,30 +2184,36 @@ impl ExplicitOutlivesRequirements {
...
+                        .iter()
+                        .any(|r| matches!(**r, ty::ReEarlyBound(ebr) if { ebr.def_id == def_id })),
+                    _ => false,
+                };
+
+                if !is_inferred {
+                    return None;
+                }
+
+                let span = bound.span();
```
Comment (cjgillot) [inline compiler/rustc_lint/src/builtin.rs:2210]:
```suggestion
                let span = bound.span().find_ancestor_inside(whole_predicate_span)?
```
This will allow to support a few more cases.

File: compiler/rustc_ast_lowering/src/item.rs (hunk 1 above)
Comment (lukas-code) [reply compiler/rustc_ast_lowering/src/item.rs]: `bound.span().find_ancestor_in_same_ctxt(colon_span.ctxt())` goes horribly wrong when the colon also comes from a macro parameter:

https://github.com/rust-lang/rust/blob/d379a25e415e1291ced6c8bbf03c080d638ecc49/src/test/ui/rust-2018/edition-lint-infer-outlives-macro.fixed#L89-L96

I changed this to search only in the "parent span", which is either the entire generics list for (normal) generic args or the `impl Trait` span.

**Comment by lukas-code** [comment]
I've addressed the review comments and this PR also fixes #106063 now. There are, however, still some remaining inconsistencies. See the `FIXME` at the bottom of the UI test for an example.

This happens, because the where clause span gets messed up in the parser here:
https://github.com/rust-lang/rust/blob/a1fc71196a5554eafc5dd9a1b4e0c159717141e0/compiler/rustc_parse/src/parser/generics.rs#L248-L315

... due to incomplete handling of mixed macro expansions in `Span::to`:
https://github.com/rust-lang/rust/blob/a1fc71196a5554eafc5dd9a1b4e0c159717141e0/compiler/rustc_span/src/lib.rs#L810-L818

This is presumably a problem elsewhere too and should probably be addressed in general (in a different PR) instead of adding more special casing here.

@rustbot review

**Comment by cjgillot** [comment]
I'm not sure I understand what is the issue with your FIXME.
Anyway, this is a great improvement!
@bors r+
