### PR TITLE
Fix off-by-one spans in MIR borrowck errors

### LINKED ISSUE #46885: Off-by-one spans in MIR borrowck errors
This is a minor thing, but you can see in the below snippet that just below line 18, the `borrowed value only lives until here` is a character to the right of where it is in the Ast equivalent.

```
error[E0597]: `x` does not live long enough (Ast)
  --> $DIR/issue-46471.rs:15:6
   |
15 |     &x
   |      ^ does not live long enough
...
18 | }
   | - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...

error[E0597]: `x` does not live long enough (Mir)
  --> $DIR/issue-46471.rs:15:5
   |
15 |     &x
   |     ^^ does not live long enough
...
18 | }
   |  - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...

error: aborting due to 2 previous errors
```

I've seen it in the following tests and there are probably a handful of others:

- [src/test/ui/issue-46471-1](https://github.com/rust-lang/rust/blob/master/src/test/ui/issue-46471-1.stderr)
- [src/test/ui/issue-46471](https://github.com/rust-lang/rust/blob/master/src/test/ui/issue-46471.stderr)
- [src/test/ui/issue-46472](https://github.com/rust-lang/rust/blob/master/src/test/ui/issue-46472.stderr)
- [src/test/ui/nll/capture-ref-in-struct](https://github.com/rust-lang/rust/blob/master/src/test/ui/nll/capture-ref-in-struct.stderr)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #46885.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/build/scope.rs [hunk 1]
```diff
@@ -695,10 +695,17 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                 if let DropKind::Value { .. } = drop_kind {
                     scope.needs_cleanup = true;
                 }
+
                 let region_scope_span = region_scope.span(self.hir.tcx(),
                                                           &self.hir.region_scope_tree);
-                // Attribute scope exit drops to scope's closing brace
-                let scope_end = region_scope_span.with_lo(region_scope_span.hi());
+                // Attribute scope exit drops to scope's closing brace.
+                // Without this check when finding the endpoint, we'll run into an ICE.
```
Comment (estebank) [inline src/librustc_mir/build/scope.rs]: Should this be somehow handled in `end_point`?

**Comment by estebank** [comment]
_The following was removed from the PR description:_

>  I had two ui test errors in ui/explain.rs and ui/lint/use_suggestion_json.rs that seemed entirely unrelated to my changes so I assumed they were something strange with my local environment.

I've seen that as well and your guess is correct. I haven't looked into how to avoid that issue yet.

File: src/librustc_mir/build/scope.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/build/scope.rs]: I think it would make sense to have a check in `end_point` that makes sure it doesn't cause any overflow when doing `self.hi().0 - 1`.

I'm not entirely sure why the MIR borrow checker has any spans where that would be an issue (particularly since the AST borrow checker doesn't need this check). I only noticed this when compiling `rustc_tsan` in the std artifacts compilation step.

Comment (estebank) [reply src/librustc_mir/build/scope.rs]: It _is_ weird. Could you make that change so that any other code calling `end_point` doesn't need to worry about this?

Also, if you could post the ICE that happens in `rustc_tsan` it would be great, as I am intrigued at which piece of code it was triggering this (my guess is that it just made an existing bug apparent).

Comment (davidtwco) [reply src/librustc_mir/build/scope.rs]: I'm already compiling a change that moves that check into `end_point` as I write this.

The only error it gave me that is left in my scrollback is this, which isn't very useful, sorry about that:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-dev running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'attempt to subtract with overflow', libsyntax_pos/lib.rs:222:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I didn't bother to look into it further than that when I confirmed it was my change that caused it. I did notice though that of the four instances of the ICE in my scrollback, they occured in different modules: `rustc_lsan`, `rustc_asan`, `compiler_builtins` and `rustc_tsan` - each run was probably with minor adjustments to my code to try work out what was happening.

Comment (estebank) [reply src/librustc_mir/build/scope.rs]: Cool. I'll r+ once that last change is in (and CI has run successfully).

**Comment by estebank** [comment]
It looks like an assertion in [`bytepos_to_file_charpos` checking wether a position falls in the middle of a wide character](https://github.com/rust-lang/rust/blob/80e2e67f4c6fbbef5e4789df7fc96804e6a84196/src/libsyntax/codemap.rs#L613) is [failing in `debuginfo/multi-byte-chars.rs`](https://travis-ci.org/rust-lang/rust/builds/328598585#L2422):

```
[01:02:27] ---- [debuginfo-gdb] debuginfo/multi-byte-chars.rs stdout ----
[01:02:27] 	NOTE: compiletest thinks it is using GDB without native rust support
[01:02:27] 
[01:02:27] error: compilation failed!
[01:02:27] status: exit code: 101
[01:02:27] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/debuginfo/multi-byte-chars.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/multi-byte-chars.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/multi-byte-chars.stage2-x86_64-unknown-linux-gnu.gdb.aux"
[01:02:27] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22
[01:02:27] stdout:
[01:02:27] ------------------------------------------
[01:02:27] 
[01:02:27] ------------------------------------------
[01:02:27] stderr:
[01:02:27] ------------------------------------------
[01:02:27] error: internal compiler error: unexpected panic
[01:02:27] 
[01:02:27] note: the compiler unexpectedly panicked. this is a bug.
[01:02:27] 
[01:02:27] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:02:27] 
[01:02:27] note: rustc 1.25.0-dev running on x86_64-unknown-linux-gnu
[01:02:27] 
[01:02:27] thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', libsyntax/codemap.rs:613:17
[01:02:27] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:02:27] 
[01:02:27] 
[01:02:27] ------------------------------------------
[01:02:27] 
[01:02:27] thread '[debuginfo-gdb] debuginfo/multi-byte-chars.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2884:9
[01:02:27] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:02:27] 
[01:02:27] 
[01:02:27] failures:
[01:02:27]     [debuginfo-gdb] debuginfo/multi-byte-chars.rs
[01:02:27] 
[01:02:27] test result: FAILED. 84 passed; 1 failed; 24 ignored; 0 measured; 0 filtered out
```

**Comment by oli-obk** [comment]
> I've seen that as well and your guess is correct. I haven't looked into how to avoid that issue yet.

That's just a stage 1 issue. Should be gone with the next snapshot. There are no error explanations in stage 1 since the system changed

File: src/libsyntax_pos/lib.rs [hunk 2]
```diff
@@ -219,7 +219,9 @@ impl Span {
     /// Returns a new span representing just the end-point of this span
     pub fn end_point(self) -> Span {
         let span = self.data();
-        let lo = cmp::max(span.hi.0 - 1, span.lo.0);
+        // We can avoid an ICE by checking if subtraction would cause an overflow.
+        let hi = if span.hi.0 == u32::min_value() { span.hi.0 } else { span.hi.0 - 1 };
```
Comment (nikomatsakis) [inline src/libsyntax_pos/lib.rs]: there is also `checked_sub` -- e.g.,

```rust
let hi = span.hi.0.checked_sub(1).unwrap_or(span.hi.0);
```

**Comment by davidtwco** [comment]
I've pushed a fix for the multibyte characters. After discussion with @nikomatsakis [on Gitter](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5a5b5b0281cd9a5d7ea2af79), I originally attempted to walk backwards from the `BytePos` until the start of the character, but I struggled to get this implemented so I took an alternative approach - not sure if this is a great approach or how performant it is.

`end_point` and `next_point` had to be moved into `CodeMap` since it cannot be used within `Span` without running into cyclic dependency issues.

File: src/libsyntax/codemap.rs [hunk 3]
```diff
@@ -576,6 +577,42 @@ impl CodeMap {
...
+        Span::new(BytePos(lo), BytePos(lo), sp.ctxt())
+    }
+
+    fn get_start_of_char_bytepos(&self, bpos: BytePos) -> BytePos {
+        let idx = self.lookup_filemap_idx(bpos);
+        let files = self.files.borrow();
+        let map = &(*files)[idx];
+
+        for mbc in map.multibyte_chars.borrow().iter() {
+            if mbc.pos < bpos {
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/libsyntax/codemap.rs]: I think I'd probably be able to get the "subtract one and go further back if needed" strategy working, but when I implemented it, I made a logic error, it would compile but subsequent compiles would fall into an infinite loop. In a subsequent attempt, I took the approach currently in the PR.

I'd be happy to take another go at it if you'd like.

[the remark this answers is not in the document]
Comment (davidtwco) [reply src/libsyntax/codemap.rs]: Pushed the "subtract one and go further back if needed" version.

**Comment by nikomatsakis** [comment]
lgtm, it'd be nice if we could assert that spans are well-formed, but that seems like a separate issue

File: src/libsyntax/codemap.rs [hunk 4]
```diff
@@ -579,38 +579,75 @@ impl CodeMap {
...
-    fn get_start_of_char_bytepos(&self, bpos: BytePos) -> BytePos {
-        let idx = self.lookup_filemap_idx(bpos);
-        let files = self.files.borrow();
-        let map = &(*files)[idx];
+    /// Finds the width of a character, either before or after the provided span.
+    fn find_width_of_character_at_span(&self, sp: Span, forwards: bool) -> u32 {
+        // Disregard malformed spans and assume a one-byte wide character.
+        if sp.lo() > sp.hi() {
+            return 1;
+        }
```
Comment (estebank) [inline src/libsyntax/codemap.rs]: Did you trigger this check anywhere? I'd like to keep it, but there have been efforts to avoid creating malformed spans in the first place.

File: src/libsyntax/codemap.rs [hunk 5]
```diff
@@ -579,38 +579,75 @@ impl CodeMap {
...
-        let hi = sp.lo().0.checked_add(1).unwrap_or(sp.lo().0);
-        let hi = self.get_start_of_char_bytepos(BytePos(hi));
-        let lo = cmp::max(sp.hi().0, hi.0);
-        Span::new(BytePos(lo), BytePos(lo), sp.ctxt())
+        let pos = sp.lo().0;
+
+        let width = self.find_width_of_character_at_span(sp, true);
+        let corrected_next_position = pos.checked_add(width).unwrap_or(pos);
+
+        let next_point = BytePos(cmp::max(sp.hi().0, corrected_next_position));
```
Comment (estebank) [inline src/libsyntax/codemap.rs]: You also need to account for the (low) chance that `next_point` might _also_ be a wide character, as `next_point` could potentially be used anywhere, including at the start of an ident (in practice this might never happen, and even if it does, the presentation would be ok, but would break havoc on tools depending on offsets).

**Review by estebank — APPROVED** [review]
Only one nitpick that _shouldn't_ be a problem in practice, but I'd like to fix before merging.

File: src/libsyntax/codemap.rs (hunk 4 above)
Comment (davidtwco) [reply src/libsyntax/codemap.rs]: I don't create any spans that would trigger this. I know that if I attempt to assert that `lo < hi` then it fails when compiling the compiler, so I think this check is necessary for now.

File: src/libsyntax/codemap.rs (hunk 5 above)
Comment (davidtwco) [reply src/libsyntax/codemap.rs]: Does the second parameter of `find_width_of_character_at_span` that searches forward for the character boundary rather than backwards not handle this or am I misunderstanding?

File: src/libsyntax/codemap.rs (hunk 4 above)
Comment (estebank) [reply src/libsyntax/codemap.rs]: Yes, we should definitely keep the check. Checks like this are peppered throughout the compiler because the compiler is making bad spans. Filed #47504 with my thoughts on the matter.

File: src/libsyntax/codemap.rs (hunk 5 above)
Comment (estebank) [reply src/libsyntax/codemap.rs]: My understanding of this code is that in the code `println!("☃☃")` if you have a span pointing at `println!(` and use `next_point`, the new span will point at the first `"`. If you call `next_point` on _that_ span, it would point to `0xE2`, when it should actually be pointing at `0xE2 0x98 0x83`. This happens because of the line below, where you create the span with the same start and end. Your code correctly handles the case where your span points to the inside of the text `0xE2 0x98 0x83 0xE2 0x98 0x83` and you call `next_point`, yielding the second `"`. Does that make sense?

Comment (davidtwco) [reply src/libsyntax/codemap.rs]: In the original version of the `next_point` function it returned a span with the same start and end, wouldn't it have had the same issue?

Comment (estebank) [reply src/libsyntax/codemap.rs]: Yes :)

Comment (davidtwco) [reply src/libsyntax/codemap.rs]: I'm not sure I understand, what change is required?

**Comment by davidtwco** [comment]
Forgot to run the ui tests after the change to the multibyte character (and never realised that Travis was having troubles) so never noticed that something in the that change caused the spans to go back a position, will fix that and update that last commit.

File: src/libsyntax/codemap.rs (hunk 5 above)
Comment (estebank) [reply src/libsyntax/codemap.rs]: We can do that on a follow up PR. I'll approve once ci is happy.

Comment (davidtwco) [reply src/libsyntax/codemap.rs]: I've already got it added. Only had one little thing remaining yesterday but it was getting late.

Comment (estebank) [reply src/libsyntax/codemap.rs]: No problem! Thank you for all the work you put into this! I know that the user facing change is  not that big given the effort, but you're fixing quite a few potential pernicious ICEs :)

Comment (davidtwco) [reply src/libsyntax/codemap.rs]: Pushed up the fix for this.

**Comment by davidtwco** [comment]
Noticed that the tests failed, which is strange - they all ran fine on my machine. Will look into it.

**Comment by nikomatsakis** [comment]
@davidtwco hmm, [seeing some ICEs in the travis tests](https://travis-ci.org/rust-lang/rust/builds/329896056#L1684)

**Comment by davidtwco** [comment]
@nikomatsakis working on it, seems like it is getting some spans that have the same `hi` and `lo`.

**Comment by estebank** [comment]
https://travis-ci.org/rust-lang/rust/jobs/333941636#L7276

```
[01:13:14] test cargo_fail_with_no_stderr has been running for over 60 seconds
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

@bors retry

**Comment by alexcrichton** [comment]
@bors: r-

Oh I think this is the same as https://github.com/rust-lang/rust/pull/47572#issuecomment-359125992, a legitimate infinite loop

**Comment by estebank** [comment]
@alexcrichton do we have a reason for it?

**Comment by alexcrichton** [comment]
@estebank I was able to reproduce it awhile back in the linked comment there (it's a reduction of a test case in Cargo)

**Comment by davidtwco** [comment]
I'll look into this, apologies.

**Comment by davidtwco** [comment]
This should now be resolved.

**Comment by alexcrichton** [comment]
@bors: r=estebnk

no worries, thanks @davidtwco!
