### PR TITLE
Add tests for some old fixed issues

### LINKED ISSUE #23600: ICE: capacity overflow or "Illegal instruction (core dumped)" with very large static item
Added by pnkfelix: here is a summary of cases discussed in comment dialogue on issue..

Outcome Matrix | nonzero elem size | zero-sized elems
---------------- | ------------------ | ------------------
array length = 0xffff_ffff_ffff_ffff | [error: "too big for the current architecture"][smallNZ] | [takes too long to know outcome?][smallZ]
array length = 0xffff_ffff |  [LLVM OOM][largeNZ]  | [successful compile after several minutes][largeZ]

[smallNZ]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=268096ace30d8abc69752eb4e9ed0cc4
[largeNZ]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4129527cb5d1166eed91ecd0e01183f6
[smallZ]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c66386c4be2f0866d77f0f33582b9de8
[largeZ]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f92457a38210b6c03a9b150b2ff961da

Original bug report below
----

Test case one:

``` rust
static V1: [u8; 0xffff_ffff] = [0u8; 0xffff_ffff];
fn main() { V1[0]; }
```

```
$ rustc test.rs
Illegal instruction (core dumped)
```

Test case two:

``` rust
static V1: [u8; 0xffff_ffff_ffff_ffff] = [0u8; 0xffff_ffff_ffff_ffff];
fn main() { V1[0]; }
```

```
$ RUST_BACKTRACE=1 rustc test.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'capacity overflow', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:330

stack backtrace:
   1:     0x7f4ba1cdfb84 - sys::backtrace::write::h00123aaa25bd3a87l4C
   2:     0x7f4ba1d08528 - panicking::on_panic::h132e5f71ec66ef60YiJ
   3:     0x7f4ba1c3bb0c - rt::unwind::begin_unwind_inner::ha3837a1e391d832bfZI
   4:     0x7f4ba1c3bef1 - rt::unwind::begin_unwind_fmt::h12ca28db54db2d68QXI
   5:     0x7f4ba1d08167 - rust_begin_unwind
   6:     0x7f4ba1d57324 - panicking::panic_fmt::h99de93df94b78c1afXA
   7:     0x7f4ba13e9550 - trans::consts::const_expr_unadjusted::hc13ed55a56b0ff20YAn
   8:     0x7f4ba13ea349 - trans::consts::const_expr::h138812d7f28437d4ron
   9:     0x7f4ba1324a7b - trans::base::get_item_val::h36642395ea7e258dF7t
  10:     0x7f4ba1321799 - trans::base::trans_item::h90869e00e43d4702mCt
  11:     0x7f4ba140a492 - trans::base::trans_crate::h909d471e074343adQyu
  12:     0x7f4ba2338e73 - driver::phase_4_translate_to_llvm::h2d7e84da5a579268mOa
  13:     0x7f4ba2314153 - driver::compile_input::hd802b376244c1b88Rba
  14:     0x7f4ba23cb942 - run_compiler::hc447d2d22477a14av2b
  15:     0x7f4ba23c9713 - thunk::F.Invoke<A, R>::invoke::h3003831543088172262
  16:     0x7f4ba23c8ba9 - rt::unwind::try::try_fn::h6527156377446821573
  17:     0x7f4ba1d7e358 - rust_try_inner
  18:     0x7f4ba1d7e345 - rust_try
  19:     0x7f4ba23c8ecc - thunk::F.Invoke<A, R>::invoke::h1217623451251402195
  20:     0x7f4ba1cf4b18 - sys::thread::create::thread_start::h36340a6690985d3f9TH
  21:     0x7f4b9bbc4181 - start_thread
  22:     0x7f4ba18a347c - __clone
  23:                0x0 - <unknown>
```

rustc version:

```
rustc 1.0.0-nightly (e2fa53e59 2015-03-20) (built 2015-03-21)
binary: rustc
commit-hash: e2fa53e593a854a609ae9efe5a1bbe15265f0a6f
commit-date: 2015-03-20
build-date: 2015-03-21
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

I didn't see any other open issues mentioning `capacity overflow`.

### LINKED ISSUE #26719: `rustc -o -` crashes
When I tried this, I was hoping it would output the executable to stdout. Saving it as a file called `-` would be reasonable behavior too.

``` sh-session
$ ls
example.rs
$ rustc -o - example.rs
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "-" "-.o" "-Wl,--whole-archive" "-lmorestack" "-Wl,--no-whole-archive" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-7d23ff90.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-7d23ff90.rlib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/d/tmp/x/.rust/lib64/x86_64-unknown-linux-gnu" "-L" "/home/d/tmp/x/lib64/x86_64-unknown-linux-gnu" "-Wl,--whole-archive" "-Wl,-Bstatic" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-ldl" "-lpthread" "-lrt" "-lgcc_s" "-lpthread" "-lc" "-lm" "-lcompiler-rt"
note: cc: error: unrecognized command line option ‘-.o’

error: aborting due to previous error
$ ls
example.rs  -.metadata.o  -.o
```

### LINKED ISSUE #28994: HRTB and Associated Types combine to make fn not implement corresponding Fn trait
``` rust
trait LifetimeToType<'a> {
    type Out;
}

impl<'a> LifetimeToType<'a> for () {
    type Out = &'a ();
}

fn id<'a>(val: &'a ()) -> <() as LifetimeToType<'a>>::Out {
    val
}

fn assert_fn<F: for<'a> FnOnce(&'a ()) -> <() as LifetimeToType<'a>>::Out>(_func: F) { }

fn main() {
    assert_fn(id);
}
```

fails with

```
test.rs:16:5: 16:14 error: type mismatch resolving `for<'a> <fn(&'a ()) -> <() as LifetimeToType<'a>>::Out {id} as core::ops::FnOnce<(&'a (),)>>::Output == <() as LifetimeToType<'a>>::Out`:
 expected &-ptr,
    found associated type [E0271]
test.rs:16     assert_fn(id);
               ^~~~~~~~~
test.rs:16:5: 16:14 help: run `rustc --explain E0271` to see a detailed explanation
test.rs:16:5: 16:14 note: required by `assert_fn`
error: aborting due to previous error
```

### LINKED ISSUE #30472: Associated type projections don't play well with HRTBs and normalization
``` rust
trait MyFrom<T> {}
impl<T> MyFrom<T> for T {}

trait MyInto<T> {}
impl<T, U> MyInto<U> for T where U: MyFrom<T> {}


trait A<'self_> {
    type T;
}
trait B: for<'self_> A<'self_> {
    //type U: for<'self_> MyFrom<<Self as A<'self_>>::T>;  // <-- this won't compile
    type U: for<'self_> MyInto<<Self as A<'self_>>::T>;  // <-- but this will
}


struct M;
impl<'self_> A<'self_> for M {
    type T = usize;
}
impl B for M {
    type U = usize;
}


fn main() {}
```

[playpen link](http://is.gd/a4V2sj)

This could've been written with `MyInto` written as `Into` and similarly for `MyFrom`/`From`. It was written this way only to make explicit the necessity of one blanket impl for satisfying the other.

I'm guessing that extensional equality is not judged, even though it is possible to make such a judgment and such a judgment must be made to compile code that compiles today. `<Self as A<'self_>>::T` on line 12 ought to be equated to `usize` (which must be detected at some other point in time else line 13 wouldn't be able to compile).

EDIT: Playing around a bit, it looks more and more like it's all about the HKL bounds...

### LINKED ISSUE #30867: HRTB impl selection does not cover type parameters not directly related to the trait.
The following doesn't compile, as it tries to assign `U` a concrete `&'x i32` instead of `&'a i32`:

``` rust
trait Unary<T> {}
impl<T, U, F: Fn(T) -> U> Unary<T> for F {}
fn unary<F: for<'a> Unary<&'a T>, T>() {}

fn test<F: for<'a> Fn(&'a i32) -> &'a i32>() {
    unary::<F, i32>()
}
```

Removing the `U` type parameter makes it work - `U` is only used for the associated type `Fn::Output` anyway:

``` rust
#![feature(unboxed_closures)]

trait Unary<T> {}
impl<T, F: Fn<(T,)>> Unary<T> for F {}
fn unary<F: for<'a> Unary<&'a T>, T>() {}

fn test<F: for<'a> Fn(&'a i32) -> &'a i32>() {
    unary::<F, i32>()
}
```

AFAICT, the selection results in `for<'a, U> F: Fn<(&'a i32,), Output=U>` in the first case, and `for<'a> F: Fn<(&'a i32,)>` in the second case, and we refuse to allow `U` to be parameterized by `'a` in the former case, even though it's only used to satisfy the sugary form of the `Fn` trait.

### PR DESCRIPTION
**Pull request by clubby789**
Closes #30867 
Closes #30472 
Closes #28994 
Closes #26719 (and migrates the relevant test to the new run-make)
Closes #23600

cc @jieyouxu for the run-make-support changes

try-job: x86_64-msvc

### CODE REVIEW

File: src/tools/run-make-support/src/external_deps/rustc.rs [hunk 1]
```diff
@@ -300,6 +301,30 @@ impl Rustc {
         self
     }
 
+    /// Configuration for the child process’s standard input (stdin) handle.
+    ///
+    /// See [`std::process::Command::stdin`].
+    pub fn stdin<T: Into<Stdio>>(&mut self, cfg: T) -> &mut Self {
+        self.cmd.stdin(cfg);
+        self
+    }
```
Comment (jieyouxu) [inline src/tools/run-make-support/src/external_deps/rustc.rs:310]: Suggestion: actually, can you move these impls to the `impl_common_helpers!` macro? These should be command-specific, not rustc specific.

File: tests/run-make/emit-to-stdout/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,60 @@
+// Test that emitting to stdout works
```
Comment (jieyouxu) [inline tests/run-make/emit-to-stdout/rmake.rs:1]: Suggestion: (not reflowed, also please double check if this comment is accurate)

```suggestion
//! If `-o -` or `--emit KIND=-` is provided, output should be written
//! to stdout instead. Binary output (`obj`, `llvm-bc`, `link` and
//! `metadata`) being written this way will result in an error if
//! stdout is a tty. Multiple output types going to stdout will
//! trigger an error too, as they will all be mixed together.
//!
//! See <https://github.com/rust-lang/rust/pull/111626>.
```

File: tests/run-make/emit-to-stdout/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+fn run_diff(name: &str, file_args: &[&str]) {
+    rustc().emit(format!("{name}={name}")).input("test.rs").args(file_args).run();
+    let out = rustc().emit(format!("{name}=-")).input("test.rs").run().stdout_utf8();
+    diff().expected_file(name).actual_text("stdout", &out).run();
+}
+
+// Test that emitting binary formats to a terminal gives the correct error
+fn run_terminal_err_diff(name: &str) {
+    let pty = File::create("/dev/ptmx").unwrap();
+    let err = File::create(name).unwrap();
```
Comment (jieyouxu) [inline tests/run-make/emit-to-stdout/rmake.rs:17]: Problem: this will only work for unix and msys2, but not native windows.

@ChrisDenton came up with a version that might work for native Windows in https://github.com/rust-lang/rust/pull/128460#issuecomment-2380716435, reproduced below:

```rs
#[cfg(not(windows))]
let stdout = std::fs::File::options().write(true).open("/dev/ptmx").unwrap();
// FIXME: If this test fails and the compiler does print to the console, then this will produce a lot of output.
// We should spawn a new console instead to print stdout.
#[cfg(windows)]
let stdout = std::fs::File::options().read(true).write(true).open(r"\\.\CONOUT$").unwrap();
```

File: tests/ui/consts/issue-77062-large-zst-array.rs
Comment (jieyouxu) [inline tests/ui/consts/issue-77062-large-zst-array.rs:1]: Suggestion: can you rename this test to `large-zst-array-77062.rs`?

File: tests/ui/traits/assoc-type-hrtb-normalization-30472.rs [hunk 4]
```diff
@@ -0,0 +1,28 @@
+//@ check-pass
```
Comment (jieyouxu) [inline tests/ui/traits/assoc-type-hrtb-normalization-30472.rs:1]: Suggestion: can you add a brief doc comment on what this test is trying to exercise, and also add a link to #30472 in the doc comment?

File: tests/ui/traits/fn-pointer/hrtb-assoc-fn-traits-28994.rs [hunk 5]
```diff
@@ -0,0 +1,19 @@
+//@ check-pass
```
Comment (jieyouxu) [inline tests/ui/traits/fn-pointer/hrtb-assoc-fn-traits-28994.rs:1]: Suggestion: ditto on doc comment for test purpose and link to #28994.

File: tests/ui/traits/hrtb-related-type-params-30867.rs [hunk 6]
```diff
@@ -0,0 +1,10 @@
+//@ check-pass
```
Comment (jieyouxu) [inline tests/ui/traits/hrtb-related-type-params-30867.rs:1]: Suggestion: ditto on doc comment for test purpose and link to #30687.

File: tests/run-make/emit-to-stdout/rmake.rs
Comment (jieyouxu) [inline tests/run-make/emit-to-stdout/rmake.rs:1]: Note: https://github.com/rust-lang/rust/pull/128460 also is migrating this test. We can consoliate the efforts into this version though.

**Review by jieyouxu — CHANGES_REQUESTED** [review]
Thanks for the PR! I left some suggestions.

File: tests/ui/consts/issue-77062-large-zst-array.rs [hunk 7]
```diff
@@ -1,4 +1,5 @@
 //@ build-pass
+pub static FOO: [(); 9223372036854775807] = [(); 9223372036854775807];
```
Comment (jieyouxu) [inline tests/ui/consts/issue-77062-large-zst-array.rs:2]: Note: there might've been an explicit `isize::MAX` check for arrays?

**Review by jieyouxu — APPROVED** [review]
Thanks!
