### PR TITLE
Consider parent predicates in ImpossiblePredicates pass.

### LINKED ISSUE #121363: ICE: `Got a scalar pair where a scalar was expected`
auto-reduced (treereduce-rust):
````rust
#![feature(trivial_bounds)]

#[derive(Debug)]
struct TwoStrs(str, str)
where
    str: Sized;

````

original:
````rust
#[derive(Debug)]
struct Foo(i32);

#[derive(Debug)]
struct TwoStrs(str, str) where str: Sized;

````

Version information
````
rustc 1.78.0-nightly (bb594538f 2024-02-20)
binary: rustc
commit-hash: bb594538fc6e84213a6b8d5e165442570aa48923
commit-date: 2024-02-20
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zcrate-attr=feature(trivial_bounds) --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: struct `TwoStrs` is never constructed
 --> /tmp/icemaker_global_tempdir.d7BGTl8YHHxI/rustc_testrunner_tmpdir_reporting.Zw6CwslhbT5j/mvce.rs:2:8
  |
2 | struct TwoStrs(str, str)
  |        ^^^^^^^
  |
  = note: `TwoStrs` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  = note: `#[warn(dead_code)]` on by default

warning: trait bound str: Sized does not depend on any type or lifetime parameters
 --> /tmp/icemaker_global_tempdir.d7BGTl8YHHxI/rustc_testrunner_tmpdir_reporting.Zw6CwslhbT5j/mvce.rs:4:10
  |
4 |     str: Sized;
  |          ^^^^^
  |
  = note: `#[warn(trivial_bounds)]` on by default

error: internal compiler error: /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/compiler/rustc_const_eval/src/interpret/operand.rs:82:42: Got a scalar pair where a scalar was expected

thread 'rustc' panicked at compiler/rustc_middle/src/util/bug.rs:35:44:
Box<dyn Any>
stack backtrace:
   0:     0x7ff23b050af6 - std::backtrace_rs::backtrace::libunwind::trace::h1eedb42239d9af6b
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7ff23b050af6 - std::backtrace_rs::backtrace::trace_unsynchronized::hf37e37075d32c152
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff23b050af6 - std::sys_common::backtrace::_print_fmt::h089ff4e21712e78d
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7ff23b050af6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h249f2f40a85530bd
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ff23b0a1a7c - core::fmt::rt::Argument::fmt::h0aeed2b676ebf5da
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/fmt/rt.rs:142:9
   5:     0x7ff23b0a1a7c - core::fmt::write::h25b3f5340152b6c4
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/fmt/mod.rs:1120:17
   6:     0x7ff23b04542f - std::io::Write::write_fmt::h8746a81e0adfe285
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/io/mod.rs:1846:15
   7:     0x7ff23b0508a4 - std::sys_common::backtrace::_print::hcf22409f3667d346
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ff23b0508a4 - std::sys_common::backtrace::print::h7d3fd33863df24d3
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ff23b0535eb - std::panicking::default_hook::{{closure}}::h69f3f4f5b3bceec1
  10:     0x7ff23b053339 - std::panicking::default_hook::hf73563d650f0e118
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:292:9
  11:     0x7ff237e1a63c - std[38a2ac7f7aa65357]::panicking::update_hook::<alloc[250c3b7c6f6c60ed]::boxed::Box<rustc_driver_impl[98bdfcf9c8fb7ba2]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7ff23b053d50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0f1d4fd9cb21869d
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/alloc/src/boxed.rs:2030:9
  13:     0x7ff23b053d50 - std::panicking::rust_panic_with_hook::h55549baaf7aa2e9c
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:786:13
  14:     0x7ff237e47244 - std[38a2ac7f7aa65357]::panicking::begin_panic::<rustc_errors[31b00c9a61d6a627]::ExplicitBug>::{closure#0}
  15:     0x7ff237e43e96 - std[38a2ac7f7aa65357]::sys_common::backtrace::__rust_end_short_backtrace::<std[38a2ac7f7aa65357]::panicking::begin_panic<rustc_errors[31b00c9a61d6a627]::ExplicitBug>::{closure#0}, !>
  16:     0x7ff237e3f626 - std[38a2ac7f7aa65357]::panicking::begin_panic::<rustc_errors[31b00c9a61d6a627]::ExplicitBug>
  17:     0x7ff237e51ad1 - <rustc_errors[31b00c9a61d6a627]::diagnostic_builder::BugAbort as rustc_errors[31b00c9a61d6a627]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7ff2382247ec - <rustc_errors[31b00c9a61d6a627]::DiagCtxt>::bug::<alloc[250c3b7c6f6c60ed]::string::String>
  19:     0x7ff2382c76eb - rustc_middle[cfb3c689534e2244]::util::bug::opt_span_bug_fmt::<rustc_span[39701832932d6f53]::span_encoding::Span>::{closure#0}
  20:     0x7ff2382ac41a - rustc_middle[cfb3c689534e2244]::ty::context::tls::with_opt::<rustc_middle[cfb3c689534e2244]::util::bug::opt_span_bug_fmt<rustc_span[39701832932d6f53]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7ff2382ac2b8 - rustc_middle[cfb3c689534e2244]::ty::context::tls::with_context_opt::<rustc_middle[cfb3c689534e2244]::ty::context::tls::with_opt<rustc_middle[cfb3c689534e2244]::util::bug::opt_span_bug_fmt<rustc_span[39701832932d6f53]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7ff236740bc0 - rustc_middle[cfb3c689534e2244]::util::bug::bug_fmt
  23:     0x7ff2395a8f6b - <rustc_mir_transform[3a9949066bb08602]::gvn::VnState>::simplify_operand
  24:     0x7ff2370be253 - <rustc_mir_transform[3a9949066bb08602]::gvn::GVN as rustc_middle[cfb3c689534e2244]::mir::MirPass>::run_pass
  25:     0x7ff239012649 - rustc_mir_transform[3a9949066bb08602]::pass_manager::run_passes_inner
  26:     0x7ff2394a84bf - rustc_mir_transform[3a9949066bb08602]::optimized_mir
  27:     0x7ff239073c75 - rustc_query_impl[72e671e77ccdc0fd]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[72e671e77ccdc0fd]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfb3c689534e2244]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7ff239074321 - rustc_query_system[eb6d0acd22a0ff82]::query::plumbing::try_execute_query::<rustc_query_impl[72e671e77ccdc0fd]::DynamicConfig<rustc_query_system[eb6d0acd22a0ff82]::query::caches::DefIdCache<rustc_middle[cfb3c689534e2244]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[72e671e77ccdc0fd]::plumbing::QueryCtxt, false>
  29:     0x7ff239073a9e - rustc_query_impl[72e671e77ccdc0fd]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7ff239453461 - rustc_middle[cfb3c689534e2244]::query::plumbing::query_get_at::<rustc_query_system[eb6d0acd22a0ff82]::query::caches::DefIdCache<rustc_middle[cfb3c689534e2244]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x7ff239f9d7fd - <rustc_metadata[7844668d1f998472]::rmeta::encoder::EncodeContext>::encode_crate_root
  32:     0x7ff239fdf116 - rustc_metadata[7844668d1f998472]::rmeta::encoder::encode_metadata
  33:     0x7ff239fdd2b8 - rustc_metadata[7844668d1f998472]::fs::encode_and_write_metadata
  34:     0x7ff239fdc65d - rustc_interface[d43ea88de449c898]::passes::start_codegen
  35:     0x7ff239fdbed8 - <rustc_interface[d43ea88de449c898]::queries::Queries>::codegen_and_build_linker
  36:     0x7ff239d6482d - rustc_interface[d43ea88de449c898]::interface::run_compiler::<core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>, rustc_driver_impl[98bdfcf9c8fb7ba2]::run_compiler::{closure#0}>::{closure#0}
  37:     0x7ff239fc1c05 - std[38a2ac7f7aa65357]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d43ea88de449c898]::util::run_in_thread_with_globals<rustc_interface[d43ea88de449c898]::util::run_in_thread_pool_with_globals<rustc_interface[d43ea88de449c898]::interface::run_compiler<core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>, rustc_driver_impl[98bdfcf9c8fb7ba2]::run_compiler::{closure#0}>::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>
  38:     0x7ff239fc1a32 - <<std[38a2ac7f7aa65357]::thread::Builder>::spawn_unchecked_<rustc_interface[d43ea88de449c898]::util::run_in_thread_with_globals<rustc_interface[d43ea88de449c898]::util::run_in_thread_pool_with_globals<rustc_interface[d43ea88de449c898]::interface::run_compiler<core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>, rustc_driver_impl[98bdfcf9c8fb7ba2]::run_compiler::{closure#0}>::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9082f35584c4c405]::result::Result<(), rustc_span[39701832932d6f53]::ErrorGuaranteed>>::{closure#1} as core[9082f35584c4c405]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7ff23b05d725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8e2928e2096a726d
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/alloc/src/boxed.rs:2016:9
  40:     0x7ff23b05d725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4f25e5317edfd617
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/alloc/src/boxed.rs:2016:9
  41:     0x7ff23b05d725 - std::sys::pal::unix::thread::Thread::new::thread_start::hc7193b55f6b48c9a
                               at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7ff234eaa9eb - <unknown>
  43:     0x7ff234f2e7cc - <unknown>
  44:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (bb594538f 2024-02-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z crate-attr=feature(trivial_bounds) --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<impl at /tmp/icemaker_global_tempdir.d7BGTl8YHHxI/rustc_testrunner_tmpdir_reporting.Zw6CwslhbT5j/mvce.rs:1:10: 1:15>::fmt`
end of query stack
error: aborting due to 1 previous error; 2 warnings emitted


```

</p>
</details>

### LINKED ISSUE #131507: ICE: `invalid immediate for given destination place: value ScalarPair .. does not match ABI`
auto-reduced (treereduce-rust):
````rust
#![feature(non_lifetime_binders)]
fn Brick()
where
    for<T> T: Copy,
{
    let mut foo: Option<Box<_>> = Some(Box::new(8));
    let f = move || {
        println!("'{}'", foo.unwrap());
    };
    f();
}

````

original:
````rust
#![feature(attr_literals)]

fn Brick() where for<T> T: Copy {
    let mut foo: Option<Box<_>> = Some(Box::new(8));
    let f = move|| {
        match foo {
            None => {},
            Some(x) => {
                foo = Some(x);
            }
        }
        println!("'{}'", foo.unwrap());
    };
    f();
}

fn main() {
    foo();
}

````

Version information
````
rustc 1.83.0-nightly (8d94e06ec 2024-10-10)
binary: rustc
commit-hash: 8d94e06ec9758b5c03ea77bb5dab22a1a76bc261
commit-date: 2024-10-10
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir -Zcrate-attr=feature(non_lifetime_binders)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(non_lifetime_binders)
  |         ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.UkDLZIiGWuhn/rustc_testrunner_tmpdir_reporting.sOtl1K9lpDK5/mvce.rs:10:2
   |
10 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.UkDLZIiGWuhn/rustc_testrunner_tmpdir_reporting.sOtl1K9lpDK5/mvce.rs`

warning: variable does not need to be mutable
 --> /tmp/icemaker_global_tempdir.UkDLZIiGWuhn/rustc_testrunner_tmpdir_reporting.sOtl1K9lpDK5/mvce.rs:5:9
  |
5 |     let mut foo: Option<Box<_>> = Some(Box::new(8));
  |         ----^^^
  |         |
  |         help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default

error: internal compiler error: compiler/rustc_const_eval/src/interpret/operand.rs:157:17: invalid immediate for given destination place: value ScalarPair(alloc5<imm>, 0x0000000000000001) does not match ABI Scalar(Initialized { value: Pointer(AddressSpace(0)), valid_range: 1..=18446744073709551615 }))

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/operand.rs:157:17:
Box<dyn Any>
stack backtrace:
   0:     0x71a61e1d6a5a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha20e66cea8d40da6
   1:     0x71a61ea034a6 - core::fmt::write::hf2daaa73a1dc1c93
   2:     0x71a61fc02e51 - std::io::Write::write_fmt::h378271f9be5fe2f8
   3:     0x71a61e1d68b2 - std::sys::backtrace::BacktraceLock::print::hc64e8d2bde51fd49
   4:     0x71a61e1d8d86 - std::panicking::default_hook::{{closure}}::h0d83bed2db8cab1c
   5:     0x71a61e1d8bd0 - std::panicking::default_hook::h128ef1b79513126f
   6:     0x71a61d22df6f - std[a9199b77cdff7b9b]::panicking::update_hook::<alloc[226919ebccef61a6]::boxed::Box<rustc_driver_impl[92ba7bf89b2038aa]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x71a61e1d9498 - std::panicking::rust_panic_with_hook::h5cd591a4b9cf7e7b
   8:     0x71a61d267a51 - std[a9199b77cdff7b9b]::panicking::begin_panic::<rustc_errors[62337987763b3873]::ExplicitBug>::{closure#0}
   9:     0x71a61d25aaf6 - std[a9199b77cdff7b9b]::sys::backtrace::__rust_end_short_backtrace::<std[a9199b77cdff7b9b]::panicking::begin_panic<rustc_errors[62337987763b3873]::ExplicitBug>::{closure#0}, !>
  10:     0x71a61d25aab3 - std[a9199b77cdff7b9b]::panicking::begin_panic::<rustc_errors[62337987763b3873]::ExplicitBug>
  11:     0x71a61d2712e1 - <rustc_errors[62337987763b3873]::diagnostic::BugAbort as rustc_errors[62337987763b3873]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x71a61d8ca144 - rustc_middle[d89ba7dfe97f8d9e]::util::bug::opt_span_bug_fmt::<rustc_span[80b8a8e8ce77617b]::span_encoding::Span>::{closure#0}
  13:     0x71a61d8affca - rustc_middle[d89ba7dfe97f8d9e]::ty::context::tls::with_opt::<rustc_middle[d89ba7dfe97f8d9e]::util::bug::opt_span_bug_fmt<rustc_span[80b8a8e8ce77617b]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x71a61d8afe5b - rustc_middle[d89ba7dfe97f8d9e]::ty::context::tls::with_context_opt::<rustc_middle[d89ba7dfe97f8d9e]::ty::context::tls::with_opt<rustc_middle[d89ba7dfe97f8d9e]::util::bug::opt_span_bug_fmt<rustc_span[80b8a8e8ce77617b]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x71a61adf99a0 - rustc_middle[d89ba7dfe97f8d9e]::util::bug::bug_fmt
  16:     0x71a61c1dbf23 - <rustc_const_eval[71c2be5c4d1e6846]::interpret::eval_context::InterpCx<rustc_const_eval[71c2be5c4d1e6846]::const_eval::machine::CompileTimeMachine>>::eval_rvalue_into_place
  17:     0x71a61c173403 - rustc_const_eval[71c2be5c4d1e6846]::const_eval::eval_queries::eval_to_allocation_raw_provider
  18:     0x71a61f11f2f6 - rustc_query_impl[121dfa8c420f6771]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[121dfa8c420f6771]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 24usize]>>
  19:     0x71a61f11eb1a - rustc_query_system[f00ba4d010ca6a7e]::query::plumbing::try_execute_query::<rustc_query_impl[121dfa8c420f6771]::DynamicConfig<rustc_query_system[f00ba4d010ca6a7e]::query::caches::DefaultCache<rustc_middle[d89ba7dfe97f8d9e]::ty::ParamEnvAnd<rustc_middle[d89ba7dfe97f8d9e]::mir::interpret::GlobalId>, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[121dfa8c420f6771]::plumbing::QueryCtxt, false>
  20:     0x71a61f11e6ef - rustc_query_impl[121dfa8c420f6771]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  21:     0x71a61f12055f - rustc_const_eval[71c2be5c4d1e6846]::const_eval::eval_queries::eval_to_const_value_raw_provider
  22:     0x71a61f120376 - rustc_query_impl[121dfa8c420f6771]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[121dfa8c420f6771]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 24usize]>>
  23:     0x71a61f11eadd - rustc_query_system[f00ba4d010ca6a7e]::query::plumbing::try_execute_query::<rustc_query_impl[121dfa8c420f6771]::DynamicConfig<rustc_query_system[f00ba4d010ca6a7e]::query::caches::DefaultCache<rustc_middle[d89ba7dfe97f8d9e]::ty::ParamEnvAnd<rustc_middle[d89ba7dfe97f8d9e]::mir::interpret::GlobalId>, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[121dfa8c420f6771]::plumbing::QueryCtxt, false>
  24:     0x71a61f11e5f3 - rustc_query_impl[121dfa8c420f6771]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  25:     0x71a61b620a96 - <rustc_middle[d89ba7dfe97f8d9e]::ty::context::TyCtxt>::const_eval_resolve
  26:     0x71a61f4d7074 - <rustc_mir_transform[494498406daaddfd]::gvn::VnState>::insert
  27:     0x71a61f4d2d4d - <rustc_mir_transform[494498406daaddfd]::gvn::VnState>::simplify_operand
  28:     0x71a61be885f4 - <rustc_mir_transform[494498406daaddfd]::gvn::GVN as rustc_mir_transform[494498406daaddfd]::pass_manager::MirPass>::run_pass
  29:     0x71a61ea0b70d - rustc_mir_transform[494498406daaddfd]::pass_manager::run_passes_inner
  30:     0x71a61ed082e2 - rustc_mir_transform[494498406daaddfd]::optimized_mir
  31:     0x71a61ed06ba1 - rustc_query_impl[121dfa8c420f6771]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[121dfa8c420f6771]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 8usize]>>
  32:     0x71a61ed58778 - rustc_query_system[f00ba4d010ca6a7e]::query::plumbing::try_execute_query::<rustc_query_impl[121dfa8c420f6771]::DynamicConfig<rustc_query_system[f00ba4d010ca6a7e]::query::caches::DefIdCache<rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[121dfa8c420f6771]::plumbing::QueryCtxt, false>
  33:     0x71a61ed57d33 - rustc_query_impl[121dfa8c420f6771]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  34:     0x71a61bcd0cc4 - <rustc_middle[d89ba7dfe97f8d9e]::ty::context::TyCtxt>::instance_mir
  35:     0x71a61ee7b30a - rustc_interface[70865a4857b6d971]::passes::run_required_analyses
  36:     0x71a61f75c35e - rustc_interface[70865a4857b6d971]::passes::analysis
  37:     0x71a61f75c331 - rustc_query_impl[121dfa8c420f6771]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[121dfa8c420f6771]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 1usize]>>
  38:     0x71a61f8fc62e - rustc_query_system[f00ba4d010ca6a7e]::query::plumbing::try_execute_query::<rustc_query_impl[121dfa8c420f6771]::DynamicConfig<rustc_query_system[f00ba4d010ca6a7e]::query::caches::SingleCache<rustc_middle[d89ba7dfe97f8d9e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[121dfa8c420f6771]::plumbing::QueryCtxt, false>
  39:     0x71a61f8fc30f - rustc_query_impl[121dfa8c420f6771]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  40:     0x71a61f753b5e - rustc_interface[70865a4857b6d971]::interface::run_compiler::<core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>, rustc_driver_impl[92ba7bf89b2038aa]::run_compiler::{closure#0}>::{closure#1}
  41:     0x71a61f7d9450 - std[a9199b77cdff7b9b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[70865a4857b6d971]::util::run_in_thread_with_globals<rustc_interface[70865a4857b6d971]::util::run_in_thread_pool_with_globals<rustc_interface[70865a4857b6d971]::interface::run_compiler<core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>, rustc_driver_impl[92ba7bf89b2038aa]::run_compiler::{closure#0}>::{closure#1}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>::{closure#0}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>
  42:     0x71a61f7d9b17 - <<std[a9199b77cdff7b9b]::thread::Builder>::spawn_unchecked_<rustc_interface[70865a4857b6d971]::util::run_in_thread_with_globals<rustc_interface[70865a4857b6d971]::util::run_in_thread_pool_with_globals<rustc_interface[70865a4857b6d971]::interface::run_compiler<core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>, rustc_driver_impl[92ba7bf89b2038aa]::run_compiler::{closure#0}>::{closure#1}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>::{closure#0}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a4436d16a4783843]::result::Result<(), rustc_span[80b8a8e8ce77617b]::ErrorGuaranteed>>::{closure#1} as core[a4436d16a4783843]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x71a61f7daa01 - std::sys::pal::unix::thread::Thread::new::thread_start::h1576647e75736287
  44:     0x71a620e6139d - <unknown>
  45:     0x71a620ee649c - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (8d94e06ec 2024-10-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z crate-attr=feature(non_lifetime_binders) -Z dump-mir-dir=dir

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `Brick::{closure#0}::promoted[0]`
#1 [eval_to_const_value_raw] simplifying constant for the type system `Brick::{closure#0}::promoted[0]`
end of query stack
error: aborting due to 2 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-non_lifetime_binders

### LINKED ISSUE #140100: ICE: `invalid immediate for given destination place: value ScalarPair does not match ABI Scalar`
auto-reduced (treereduce-rust):
````rust







fn test()
where
    for<'a> <Foo<'a> as Bar>::Type: Sized,
{
    'b: {
        println!("hi");
        
        'c: 
        
        if true {
            break 'b;
        }
    }
}



````

original:
````rust
trait Bar {
    type Type;
}
struct Foo<'a>(&'a ());
impl<'a> Bar for Foo<'a> {
    type ASSUME_LIFETIMES = ();
}

fn func<'a>(_: <Foo<'a> as Bar>::repr_u8) {}
fn assert_is_func<Power>(_: fn(f: Foo)) {}

fn test()
where
    for<'a> <Foo<'a> as Bar>::Type: Sized,
{
    'b: {
        println!("hi");
        if false {
            break 'b;
        }
        'c: {
            if false {
                break 'b;
            }
            break 'c;
        }
        println!("hello");
        if true {
            break 'b;
        }
    }
}

fn main() {}

````

Version information
````
rustc 1.88.0-nightly (b8005bff3 2025-04-20)
binary: rustc
commit-hash: b8005bff3248cfc6e327faf4fa631ac49bb49ba9
commit-date: 2025-04-20
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/b8005bff3248cfc6e327faf4fa631ac49bb49ba9/compiler/rustc_const_eval/src/interpret/operand.rs#L151-L163

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected `while`, `for`, `loop` or `{` after a label
  --> /tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs:17:9
   |
17 |         if true {
   |         ^^ expected `while`, `for`, `loop` or `{` after a label
   |
help: consider enclosing expression in a block
   |
17 ~         { if true {
18 |             break 'b;
19 ~         } }
   |

error[E0405]: cannot find trait `Bar` in this scope
  --> /tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs:10:25
   |
10 |     for<'a> <Foo<'a> as Bar>::Type: Sized,
   |                         ^^^ not found in this scope

error[E0412]: cannot find type `Foo` in this scope
  --> /tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs:10:14
   |
10 |     for<'a> <Foo<'a> as Bar>::Type: Sized,
   |              ^^^ not found in this scope

warning: unused label
  --> /tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs:15:9
   |
15 |         'c: 
   |         ^^
   |
   = note: `#[warn(unused_labels)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs:21:2
   |
21 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.4Oq9irvDKofF/rustc_testrunner_tmpdir_reporting.JwSxZ3drFIdf/mvce.rs`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/operand.rs:157:17: invalid immediate for given destination place: value ScalarPair(alloc3<imm>, 0x0000000000000003) does not match ABI Scalar(Initialized { value: Pointer(AddressSpace(0)), valid_range: 1..=18446744073709551615 }))


thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/operand.rs:157:17:
Box<dyn Any>
stack backtrace:
   0:     0x74b0d1cbfa13 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd3d6a01c34b68e33
   1:     0x74b0d2405b07 - core::fmt::write::hc8609d2830ea7209
   2:     0x74b0d38a2b11 - std::io::Write::write_fmt::h5803b161d154e6bb
   3:     0x74b0d1cbf872 - std::sys::backtrace::BacktraceLock::print::h7d1ba71c4ac8a197
   4:     0x74b0d1cc31ea - std::panicking::default_hook::{{closure}}::h81636b35691bb80d
   5:     0x74b0d1cc2d6f - std::panicking::default_hook::h3d6df3ec9a366961
   6:     0x74b0d0d439a3 - std[a4b1c5db45b5369]::panicking::update_hook::<alloc[a753183b20116edd]::boxed::Box<rustc_driver_impl[64822a3bbb8e5a99]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x74b0d1cc3a63 - std::panicking::rust_panic_with_hook::hc0072f606cfb3c45
   8:     0x74b0d0d7f3a1 - std[a4b1c5db45b5369]::panicking::begin_panic::<rustc_errors[e87d3527ff012bd9]::ExplicitBug>::{closure#0}
   9:     0x74b0d0d73276 - std[a4b1c5db45b5369]::sys::backtrace::__rust_end_short_backtrace::<std[a4b1c5db45b5369]::panicking::begin_panic<rustc_errors[e87d3527ff012bd9]::ExplicitBug>::{closure#0}, !>
  10:     0x74b0d0d6faa9 - std[a4b1c5db45b5369]::panicking::begin_panic::<rustc_errors[e87d3527ff012bd9]::ExplicitBug>
  11:     0x74b0d0d89771 - <rustc_errors[e87d3527ff012bd9]::diagnostic::BugAbort as rustc_errors[e87d3527ff012bd9]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x74b0d13ce68a - rustc_middle[105e55ff3e6629a7]::util::bug::opt_span_bug_fmt::<rustc_span[f33b24d4c40821a8]::span_encoding::Span>::{closure#0}
  13:     0x74b0d13a96aa - rustc_middle[105e55ff3e6629a7]::ty::context::tls::with_opt::<rustc_middle[105e55ff3e6629a7]::util::bug::opt_span_bug_fmt<rustc_span[f33b24d4c40821a8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x74b0d13a951b - rustc_middle[105e55ff3e6629a7]::ty::context::tls::with_context_opt::<rustc_middle[105e55ff3e6629a7]::ty::context::tls::with_opt<rustc_middle[105e55ff3e6629a7]::util::bug::opt_span_bug_fmt<rustc_span[f33b24d4c40821a8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x74b0ce686ed0 - rustc_middle[105e55ff3e6629a7]::util::bug::bug_fmt
  16:     0x74b0d33cc1a3 - <rustc_const_eval[6f9def1c42cc4e3b]::interpret::eval_context::InterpCx<rustc_const_eval[6f9def1c42cc4e3b]::const_eval::machine::CompileTimeMachine>>::eval_rvalue_into_place
  17:     0x74b0d3368979 - rustc_const_eval[6f9def1c42cc4e3b]::const_eval::eval_queries::eval_to_allocation_raw_provider
  18:     0x74b0d33675be - rustc_query_impl[f9677782d554bbe0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f9677782d554bbe0]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 24usize]>>
  19:     0x74b0d2f8e582 - rustc_query_system[6c94265d9bb07c02]::query::plumbing::try_execute_query::<rustc_query_impl[f9677782d554bbe0]::DynamicConfig<rustc_query_system[6c94265d9bb07c02]::query::caches::DefaultCache<rustc_middle[105e55ff3e6629a7]::ty::PseudoCanonicalInput<rustc_middle[105e55ff3e6629a7]::mir::interpret::GlobalId>, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[f9677782d554bbe0]::plumbing::QueryCtxt, false>
  20:     0x74b0d2f8e134 - rustc_query_impl[f9677782d554bbe0]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  21:     0x74b0d2f90a85 - rustc_const_eval[6f9def1c42cc4e3b]::const_eval::eval_queries::eval_to_const_value_raw_provider
  22:     0x74b0d2f90890 - rustc_query_impl[f9677782d554bbe0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f9677782d554bbe0]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 24usize]>>
  23:     0x74b0d2f8ffda - rustc_query_system[6c94265d9bb07c02]::query::plumbing::try_execute_query::<rustc_query_impl[f9677782d554bbe0]::DynamicConfig<rustc_query_system[6c94265d9bb07c02]::query::caches::DefaultCache<rustc_middle[105e55ff3e6629a7]::ty::PseudoCanonicalInput<rustc_middle[105e55ff3e6629a7]::mir::interpret::GlobalId>, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 24usize]>>, false, true, false>, rustc_query_impl[f9677782d554bbe0]::plumbing::QueryCtxt, false>
  24:     0x74b0d2f8fb74 - rustc_query_impl[f9677782d554bbe0]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  25:     0x74b0d31ebd22 - <rustc_middle[105e55ff3e6629a7]::ty::context::TyCtxt>::const_eval_resolve
  26:     0x74b0d2d43270 - <rustc_mir_transform[79ecba53e0945e11]::known_panics_lint::ConstPropagator as rustc_middle[105e55ff3e6629a7]::mir::visit::Visitor>::visit_assign
  27:     0x74b0d2d3f87e - <rustc_mir_transform[79ecba53e0945e11]::known_panics_lint::ConstPropagator as rustc_middle[105e55ff3e6629a7]::mir::visit::Visitor>::visit_body
  28:     0x74b0d3258c3a - <rustc_mir_transform[79ecba53e0945e11]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[79ecba53e0945e11]::pass_manager::MirLint>::run_lint
  29:     0x74b0d240bef0 - rustc_mir_transform[79ecba53e0945e11]::run_analysis_to_runtime_passes
  30:     0x74b0d2a1fa25 - rustc_mir_transform[79ecba53e0945e11]::mir_drops_elaborated_and_const_checked
  31:     0x74b0d2a1f3e3 - rustc_query_impl[f9677782d554bbe0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f9677782d554bbe0]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 8usize]>>
  32:     0x74b0d2685e2c - rustc_query_system[6c94265d9bb07c02]::query::plumbing::try_execute_query::<rustc_query_impl[f9677782d554bbe0]::DynamicConfig<rustc_data_structures[d346d185fbcc034d]::vec_cache::VecCache<rustc_span[f33b24d4c40821a8]::def_id::LocalDefId, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6c94265d9bb07c02]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[f9677782d554bbe0]::plumbing::QueryCtxt, false>
  33:     0x74b0d268570f - rustc_query_impl[f9677782d554bbe0]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  34:     0x74b0d2dbac58 - rustc_interface[87387720858aeda]::passes::run_required_analyses
  35:     0x74b0d301e41e - rustc_interface[87387720858aeda]::passes::analysis
  36:     0x74b0d301e3ed - rustc_query_impl[f9677782d554bbe0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f9677782d554bbe0]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 0usize]>>
  37:     0x74b0d340db3d - rustc_query_system[6c94265d9bb07c02]::query::plumbing::try_execute_query::<rustc_query_impl[f9677782d554bbe0]::DynamicConfig<rustc_query_system[6c94265d9bb07c02]::query::caches::SingleCache<rustc_middle[105e55ff3e6629a7]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[f9677782d554bbe0]::plumbing::QueryCtxt, false>
  38:     0x74b0d340d838 - rustc_query_impl[f9677782d554bbe0]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x74b0d371ee3e - rustc_interface[87387720858aeda]::passes::create_and_enter_global_ctxt::<core[89ea4ceba863dd14]::option::Option<rustc_interface[87387720858aeda]::queries::Linker>, rustc_driver_impl[64822a3bbb8e5a99]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  40:     0x74b0d3555404 - rustc_interface[87387720858aeda]::interface::run_compiler::<(), rustc_driver_impl[64822a3bbb8e5a99]::run_compiler::{closure#0}>::{closure#1}
  41:     0x74b0d32ecd68 - std[a4b1c5db45b5369]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[87387720858aeda]::util::run_in_thread_with_globals<rustc_interface[87387720858aeda]::util::run_in_thread_pool_with_globals<rustc_interface[87387720858aeda]::interface::run_compiler<(), rustc_driver_impl[64822a3bbb8e5a99]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  42:     0x74b0d32ed1b4 - <<std[a4b1c5db45b5369]::thread::Builder>::spawn_unchecked_<rustc_interface[87387720858aeda]::util::run_in_thread_with_globals<rustc_interface[87387720858aeda]::util::run_in_thread_pool_with_globals<rustc_interface[87387720858aeda]::interface::run_compiler<(), rustc_driver_impl[64822a3bbb8e5a99]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[89ea4ceba863dd14]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x74b0d32ee5b7 - std::sys::pal::unix::thread::Thread::new::thread_start::h763527da6478f178
  44:     0x74b0cd2a370a - <unknown>
  45:     0x74b0cd327aac - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (b8005bff3 2025-04-20) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `test::promoted[0]`
#1 [eval_to_const_value_raw] simplifying constant for the type system `test::promoted[0]`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `test`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0405, E0412, E0601.
For more information about an error, try `rustc --explain E0405`.

```

</p>
</details>

### LINKED ISSUE #140365: ICE: `Got a scalar pair where a scalar was expected` when using the `Self` on `fn`, a wrong place.
A really similar case I found is: #135128 
But I think they are different, as when trying the code in that issue, it didn't panic in the latest rustc: 1.88.0-nightly, but mine does.

### Code

```Rust
fn f() -> &'static str
where
    Self: Sized,
{
    ""
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (10fa3c449 2025-04-26)
binary: rustc
commit-hash: 10fa3c449f6b1613b352a6cbf78d3d91fd9a1d81
commit-date: 2025-04-26
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Error output

```
error[E0411]: cannot find type `Self` in this scope
 --> test/tmp.rs:3:5
  |
1 | fn f() -> &'static str
  |    - `Self` not allowed in a function
2 | where
3 |     Self: Sized,
  |     ^^^^ `Self` is only available in impls, traits, and type definitions

error: internal compiler error: /rustc/10fa3c449f6b1613b352a6cbf78d3d91fd9a1d81/compiler/rustc_const_eval/src/interpret/operand.rs:84:42: Got a scalar pair where a scalar was expected


thread 'rustc' panicked at /rustc/10fa3c449f6b1613b352a6cbf78d3d91fd9a1d81/compiler/rustc_const_eval/src/interpret/operand.rs:84:42:
Box<dyn Any>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0411]: cannot find type `Self` in this scope
 --> test/tmp.rs:3:5
  |
1 | fn f() -> &'static str
  |    - `Self` not allowed in a function
2 | where
3 |     Self: Sized,
  |     ^^^^ `Self` is only available in impls, traits, and type definitions

error: internal compiler error: /rustc/10fa3c449f6b1613b352a6cbf78d3d91fd9a1d81/compiler/rustc_const_eval/src/interpret/operand.rs:84:42: Got a scalar pair where a scalar was expected


thread 'rustc' panicked at /rustc/10fa3c449f6b1613b352a6cbf78d3d91fd9a1d81/compiler/rustc_const_eval/src/interpret/operand.rs:84:42:
Box<dyn Any>
stack backtrace:
   0:     0x7837b4ce90f3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he1cc6de51b8e3e46
   1:     0x7837b5405ac7 - core::fmt::write::h546351ef89cac2c3
   2:     0x7837b683e6d1 - std::io::Write::write_fmt::hdd0a9df47aae8e9f
   3:     0x7837b4ce8f52 - std::sys::backtrace::BacktraceLock::print::h575bf1241b79e77a
   4:     0x7837b4cecd9a - std::panicking::default_hook::{{closure}}::h9889804a123e7c5b
   5:     0x7837b4cec91f - std::panicking::default_hook::h0459a96a46f07fba
   6:     0x7837b3d710d3 - std[799ab5ff8c92313d]::panicking::update_hook::<alloc[8b075dae1d9a4a4]::boxed::Box<rustc_driver_impl[8ffa39a1f100e9bb]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7837b4ced613 - std::panicking::rust_panic_with_hook::hb01102643345a267
   8:     0x7837b3dacac1 - std[799ab5ff8c92313d]::panicking::begin_panic::<rustc_errors[3ee20515ee49c7f0]::ExplicitBug>::{closure#0}
   9:     0x7837b3da0af6 - std[799ab5ff8c92313d]::sys::backtrace::__rust_end_short_backtrace::<std[799ab5ff8c92313d]::panicking::begin_panic<rustc_errors[3ee20515ee49c7f0]::ExplicitBug>::{closure#0}, !>
  10:     0x7837b3da097b - std[799ab5ff8c92313d]::panicking::begin_panic::<rustc_errors[3ee20515ee49c7f0]::ExplicitBug>
  11:     0x7837b3db6fb1 - <rustc_errors[3ee20515ee49c7f0]::diagnostic::BugAbort as rustc_errors[3ee20515ee49c7f0]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7837b43f1f9a - rustc_middle[d1b324fb2b9fb44f]::util::bug::opt_span_bug_fmt::<rustc_span[9169b51a7177056a]::span_encoding::Span>::{closure#0}
  13:     0x7837b43ccdfa - rustc_middle[d1b324fb2b9fb44f]::ty::context::tls::with_opt::<rustc_middle[d1b324fb2b9fb44f]::util::bug::opt_span_bug_fmt<rustc_span[9169b51a7177056a]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7837b43ccc6b - rustc_middle[d1b324fb2b9fb44f]::ty::context::tls::with_context_opt::<rustc_middle[d1b324fb2b9fb44f]::ty::context::tls::with_opt<rustc_middle[d1b324fb2b9fb44f]::util::bug::opt_span_bug_fmt<rustc_span[9169b51a7177056a]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7837b168a6c0 - rustc_middle[d1b324fb2b9fb44f]::util::bug::bug_fmt
  16:     0x7837b2ad897c - <rustc_mir_transform[b9389225760552bd]::gvn::VnState as rustc_middle[d1b324fb2b9fb44f]::mir::visit::MutVisitor>::visit_statement
  17:     0x7837b2acea5b - <rustc_mir_transform[b9389225760552bd]::gvn::GVN as rustc_mir_transform[b9389225760552bd]::pass_manager::MirPass>::run_pass
  18:     0x7837b54039fb - rustc_mir_transform[b9389225760552bd]::pass_manager::run_passes_inner
  19:     0x7837b5d87c1f - rustc_mir_transform[b9389225760552bd]::optimized_mir
  20:     0x7837b5d8720d - rustc_query_impl[5054593ac04cc94b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5054593ac04cc94b]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d1b324fb2b9fb44f]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7837b57b646f - rustc_query_system[868e915c35b94eeb]::query::plumbing::try_execute_query::<rustc_query_impl[5054593ac04cc94b]::DynamicConfig<rustc_query_system[868e915c35b94eeb]::query::caches::DefIdCache<rustc_middle[d1b324fb2b9fb44f]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[5054593ac04cc94b]::plumbing::QueryCtxt, false>
  22:     0x7837b57b589d - rustc_query_impl[5054593ac04cc94b]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7837b58d782f - <rustc_middle[d1b324fb2b9fb44f]::ty::context::TyCtxt>::instance_mir
  24:     0x7837b5ef588c - rustc_interface[4f0825a59a6ff88a]::passes::run_required_analyses
  25:     0x7837b62d7c5e - rustc_interface[4f0825a59a6ff88a]::passes::analysis
  26:     0x7837b62d7c2d - rustc_query_impl[5054593ac04cc94b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5054593ac04cc94b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d1b324fb2b9fb44f]::query::erase::Erased<[u8; 0usize]>>
  27:     0x7837b62dd73d - rustc_query_system[868e915c35b94eeb]::query::plumbing::try_execute_query::<rustc_query_impl[5054593ac04cc94b]::DynamicConfig<rustc_query_system[868e915c35b94eeb]::query::caches::SingleCache<rustc_middle[d1b324fb2b9fb44f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[5054593ac04cc94b]::plumbing::QueryCtxt, false>
  28:     0x7837b62dd438 - rustc_query_impl[5054593ac04cc94b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7837b66341c0 - rustc_interface[4f0825a59a6ff88a]::passes::create_and_enter_global_ctxt::<core[30c64d6a260d8eb8]::option::Option<rustc_interface[4f0825a59a6ff88a]::queries::Linker>, rustc_driver_impl[8ffa39a1f100e9bb]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  30:     0x7837b64aeb84 - rustc_interface[4f0825a59a6ff88a]::interface::run_compiler::<(), rustc_driver_impl[8ffa39a1f100e9bb]::run_compiler::{closure#0}>::{closure#1}
  31:     0x7837b6353b28 - std[799ab5ff8c92313d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4f0825a59a6ff88a]::util::run_in_thread_with_globals<rustc_interface[4f0825a59a6ff88a]::util::run_in_thread_pool_with_globals<rustc_interface[4f0825a59a6ff88a]::interface::run_compiler<(), rustc_driver_impl[8ffa39a1f100e9bb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  32:     0x7837b6353f74 - <<std[799ab5ff8c92313d]::thread::Builder>::spawn_unchecked_<rustc_interface[4f0825a59a6ff88a]::util::run_in_thread_with_globals<rustc_interface[4f0825a59a6ff88a]::util::run_in_thread_pool_with_globals<rustc_interface[4f0825a59a6ff88a]::interface::run_compiler<(), rustc_driver_impl[8ffa39a1f100e9bb]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[30c64d6a260d8eb8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7837b6355377 - std::sys::pal::unix::thread::Thread::new::thread_start::h6104b903ae36f332
  34:     0x7837b02a3708 - <unknown>
  35:     0x7837b0327aac - <unknown>
  36:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (10fa3c449 2025-04-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -Z no-codegen -Z validate-mir --crate-type lib

query stack during panic:
#0 [optimized_mir] optimizing MIR for `f`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0411`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
This pass is double edged. It avoids some ICEs (yay!) but also degrades diagnostics from constant evaluation.

Fixes rust-lang/rust#121363
Fixes rust-lang/rust#131507
Fixes rust-lang/rust#140100 
Fixes rust-lang/rust#140365

### CODE REVIEW

File: compiler/rustc_mir_transform/src/impossible_predicates.rs [hunk 1]
```diff
@@ -36,14 +36,26 @@ use crate::pass_manager::MirPass;
...
-        let predicates = tcx
-            .predicates_of(body.source.def_id())
+        tracing::trace!(def_id = ?body.source.def_id());
+        let predicates = tcx.predicates_of(body.source.def_id()).instantiate_identity(tcx);
+        tracing::trace!(?predicates);
+        let predicates: Vec<_> = predicates
             .predicates
-            .iter()
-            .filter_map(|(p, _)| if p.is_global() { Some(*p) } else { None });
-        if traits::impossible_predicates(tcx, traits::elaborate(tcx, predicates).collect()) {
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/impossible_predicates.rs:45]: We still need to elaborate the filtered predicates I presume?

Comment (compiler-errors) [reply compiler/rustc_mir_transform/src/impossible_predicates.rs:45]: Yeah, we should still be elaborating here.

**Comment by compiler-errors** [comment]
Should also queue a perf run once we're elaborating again.
