### PR TITLE
refactor merge base logic and fix `x fmt`

### LINKED ISSUE #130147: x.py fmt: logic for "which files changed" is broken when there are no changes
When I run `./x.py fmt` in a clean checkout, I get the following:
```
fmt: formatted 5534 modified files
```
If I now change a single file manually, it says instead:
```
fmt: formatted modified file library/core/src/ptr/mod.rs
```

Cc @rust-lang/bootstrap

### PR DESCRIPTION
**Pull request by onur-ozkan**
When remote upstream is not configured, using [get_git_modified_files](https://github.com/rust-lang/rust/blob/38e3a5771cefc9362976a605549f8b04d5707311/src/tools/build_helper/src/git.rs#L114) to find modified files fails because [get_rust_lang_rust_remote](https://github.com/rust-lang/rust/blob/38e3a5771cefc9362976a605549f8b04d5707311/src/tools/build_helper/src/git.rs#L46-L48) can not resolve "rust-lang/rust" from the git output. The changes in this PR makes bootstrap to find the latest bors commit, treating it as the "closest upstream commit" so that the change tracker logic can use it to find the diffs.

In addition, [skips formatting](https://github.com/rust-lang/rust/commit/e3924544832668a6e239153a90d3be2077fbdce4) if there are no modified files.

Fixes #130147

### CODE REVIEW

**Comment by Kobzol** [comment]
Just noting that `./x fmt` for me shows the same output (and generates very long `strace` output), and I have a classic setup with a working remote and no worktrees. So I'm not sure if this is just about (un)configured upstream.

**Comment by onur-ozkan** [comment]
> Just noting that `./x fmt` for me shows the same output (and generates very long `strace` output), and I have a classic setup with a working remote and no worktrees. So I'm not sure if this is just about (un)configured upstream.

Does `git remote -v | grep "rust-lang"` print anything?

**Comment by Kobzol** [comment]
```
(venv) /pr/pe/ru/rust [test/u]$ git remote -v | grep "rust-lang"
origin  https://github.com/rust-lang/rust (fetch)
origin  https://github.com/rust-lang/rust (push)
```

**Comment by onur-ozkan** [comment]
Oh, so configuring the remote just fixes this:

```sh
fmt warning: Something went wrong running git commands:
fmt warning: rust-lang/rust remote not found
```

so there is another problem (if there is truly no change at all, bootstrap should skip formatting files) to solve.

**Comment by Kobzol** [comment]
I think that the problem is simply that when no files are modified, untracked or ignored, then the `override_builder` builder is empty, and thus everything gets formatted. I'll send a PR to fix.

**Comment by onur-ozkan** [comment]
> I think that the problem is simply that when no files are modified, untracked or ignored, then the `override_builder` builder is empty, and thus everything gets formatted. I'll send a PR to fix.

I fixed it already with https://github.com/rust-lang/rust/pull/130161/commits/e3924544832668a6e239153a90d3be2077fbdce4. It was quite simple to figure out.

File: src/tools/build_helper/src/git.rs [hunk 1]
```diff
@@ -108,6 +105,37 @@ pub fn get_git_merge_base(
     Ok(output_result(git.arg("merge-base").arg(&updated_master).arg("HEAD"))?.trim().to_owned())
 }
 
+/// Resolves the closest merge commit by the given `author` and `target_paths`.
+///
+/// If it fails to find the commit from upstream using `git merge-base`, fallbacks to HEAD.
+pub fn get_closest_merge_commit(
```
Comment (Kobzol) [inline src/tools/build_helper/src/git.rs:111]: Could you add a comment explaining how does this differ from just using merge base (I know that it is to handle missing upstream remotes, but currently the information is only in a commit message, would be nicer to be in a comment).

**Review by Kobzol — APPROVED** [review]

**Comment by Kobzol** [comment]
You can r=me with the added comment.

**Comment by RalfJung** [comment]
> In addition, [skips formatting](https://github.com/rust-lang/rust/commit/e3924544832668a6e239153a90d3be2077fbdce4) if there are modified files.

There's a "no" missing here, right?

**Comment by RalfJung** [comment]
> The changes in this PR makes bootstrap to find the latest bors commit, treating it as the "closest upstream commit" so that the change tracker logic can use it to find the diffs.

Won't that make https://github.com/rust-lang/rust/issues/101907 worse again when the local branch is a miri (or other tool) sync -- which contains *local*, non-upstream bors commits, from the "other bors" running in the other repo?

**Comment by onur-ozkan** [comment]
> > In addition, [skips formatting](https://github.com/rust-lang/rust/commit/e3924544832668a6e239153a90d3be2077fbdce4) if there are modified files.
> 
> There's a "no" missing here, right?

Yes..

> Won't that make #101907 worse again when the local branch is a miri (or other tool) sync -- which contains _local_, non-upstream bors commits, from the "other bors" running in the other repo?
> 
> See #113588 and #115409 for some context of why the logic currently works the way it does.
> 
> OTOH, things are already not reliably working for these miri syncs, so... it's probably not worth preserving the current half-working state.

I don't see how this could make https://github.com/rust-lang/rust/issues/101907 worse, as we don't change any behavior for CI-LLVM in this PR. If the most recent bors commit isn't from upstream, then bootstrap will attempt to modify some more files in addition to the ones actually changed.

File: src/tools/build_helper/src/git.rs (hunk 1 above)
Comment (onur-ozkan) [reply src/tools/build_helper/src/git.rs:116]: I am not sure if explaining `get_git_merge_base` in the `get_closest_merge_commit` doc-comments would be a good idea as `get_git_merge_base` is a private function. I just pushed https://github.com/rust-lang/rust/pull/130161/commits/991a60dc7076d550921121d95d861cdc8f16216b, let me know if you like that approach.

Comment (Kobzol) [reply src/tools/build_helper/src/git.rs:116]: Thank you! I think it's clearer now.

**Comment by RalfJung** [comment]
> I don't see how this could make https://github.com/rust-lang/rust/issues/101907 worse, as we don't change any behavior for CI-LLVM in this PR. If the most recent bors commit isn't from upstream, then bootstrap will attempt to modify some more files in addition to the ones actually changed.

Oh we are using different "upstream base commit" logic for LLVM and formatting? That seems even worse, to be honest...^^

File: src/bootstrap/src/core/build_steps/llvm.rs [hunk 2]
```diff
@@ -153,10 +154,9 @@ pub fn prebuilt_llvm_config(builder: &Builder<'_>, target: TargetSelection) -> L
 /// This retrieves the LLVM sha we *want* to use, according to git history.
 pub(crate) fn detect_llvm_sha(config: &Config, is_git: bool) -> String {
     let llvm_sha = if is_git {
-        helpers::get_closest_merge_base_commit(
+        get_closest_merge_commit(
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/llvm.rs:157]: This here makes it look like the logic for finding the LLVM commit will change. So I am confused by your statement saying that it will not change.

**Comment by onur-ozkan** [comment]
> > I don't see how this could make #101907 worse, as we don't change any behavior for CI-LLVM in this PR. If the most recent bors commit isn't from upstream, then bootstrap will attempt to modify some more files in addition to the ones actually changed.
> 
> Oh we are using different "upstream base commit" logic for LLVM and formatting? That seems even worse, to be honest...^^

Previously formatting and LLVM had different "merge base commit" logic, this PR makes formatting to use the LLVM logic.

File: src/tools/build_helper/src/git.rs [hunk 3]
```diff
@@ -107,6 +109,38 @@ pub fn get_git_merge_base(
...
+    config: &GitConfig<'_>,
+    target_paths: &[PathBuf],
+) -> Result<String, String> {
+    let mut git = Command::new("git");
+
+    if let Some(git_dir) = git_dir {
+        git.current_dir(git_dir);
+    }
+
+    let merge_base = get_git_merge_base(config, git_dir).unwrap_or_else(|_| "HEAD".into());
```
Comment (RalfJung) [inline src/tools/build_helper/src/git.rs:127]: Oh, so of upstream is available this will start at the upstream merge base and then find the nearest commit from there. The doc comment of this function doesn't mention that so I got confused.

File: src/bootstrap/src/core/build_steps/llvm.rs (hunk 2 above)
Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/llvm.rs:157]: We just moved bootstrap function to build_helper crate.

File: src/tools/compiletest/src/lib.rs [hunk 4]
```diff
@@ -163,7 +163,8 @@ pub fn parse_config(args: Vec<String>) -> Config {
         )
         .optopt("", "edition", "default Rust edition", "EDITION")
         .reqopt("", "git-repository", "name of the git repository", "ORG/REPO")
-        .reqopt("", "nightly-branch", "name of the git branch for nightly", "BRANCH");
+        .reqopt("", "nightly-branch", "name of the git branch for nightly", "BRANCH")
+        .reqopt("", "git-merge-commit-email", "email address used for the merge commits", "EMAIL");
```
Comment (RalfJung) [inline src/tools/compiletest/src/lib.rs:167]: "the" here should be removed.

Also, this is used to *find* merge commits, not to create them, right? It should specifically be the bors email? That's not clear at all currently, neither here nor in the code.

File: src/tools/build_helper/src/git.rs [hunk 5]
```diff
@@ -107,6 +109,38 @@ pub fn get_git_merge_base(
     Ok(output_result(git.arg("merge-base").arg(&updated_master).arg("HEAD"))?.trim().to_owned())
 }
 
+/// Searches for the nearest merge commit in the repository.
```
Comment (RalfJung) [inline src/tools/build_helper/src/git.rs:112]:
```suggestion
/// Searches for the nearest merge commit in the repository that also exists upstream.
```

File: src/tools/build_helper/src/git.rs [hunk 6]
```diff
@@ -95,10 +96,11 @@ pub fn updated_master_branch(
...
 
-pub fn get_git_merge_base(
-    config: &GitConfig<'_>,
-    git_dir: Option<&Path>,
-) -> Result<String, String> {
+/// Finds the nearest merge commit by comparing the local `HEAD` with the upstream branch's state.
+/// To work correctly, the upstream remote must be properly configured using `git remote add <name> <url>`.
+/// In most cases `get_closest_merge_commit` is the function you are looking for as it doesn't require remote
+/// to be configured.
+fn get_git_merge_base(config: &GitConfig<'_>, git_dir: Option<&Path>) -> Result<String, String> {
```
Comment (RalfJung) [inline src/tools/build_helper/src/git.rs:103]: maybe "git_upstream_merge_base" would be more clear?

**Comment by RalfJung** [comment]
> Previously formatting and LLVM had different "merge base commit" logic, this PR makes formatting to use the LLVM logic.

Previously both used get_closest_merge_base_commit, now both use get_closest_merge_commit... seems like they used the same logic before as well?

**Comment by onur-ozkan** [comment]
> > Previously formatting and LLVM had different "merge base commit" logic, this PR makes formatting to use the LLVM logic.
> 
> Previously both used get_closest_merge_base_commit, now both use get_closest_merge_commit... seems like they used the same logic before as well?



> > Previously formatting and LLVM had different "merge base commit" logic, this PR makes formatting to use the LLVM logic.
> 
> Previously both used get_closest_merge_base_commit, now both use get_closest_merge_commit... seems like they used the same logic before as well?

Formatting logic uses [get_git_modified_files](https://github.com/rust-lang/rust/blob/52419fc5ed14e8d3215e9158412dda9f2641e00e/src/tools/build_helper/src/git.rs#L148) to find changed files, which was utilizing "get_git_merge_base" before, and now it uses "get_closest_merge_commit".

**Comment by RalfJung** [comment]
Oh sorry, I was looking at the wrong place. *oops*

File: src/tools/build_helper/src/git.rs (hunk 5 above)
Comment (onur-ozkan) [reply src/tools/build_helper/src/git.rs:112]: I am fine with adding that comment, but in rare cases it's not correct (like you mentioned at https://github.com/rust-lang/rust/pull/130161#issuecomment-2340775588).

File: src/tools/build_helper/src/git.rs (hunk 3 above)
Comment (onur-ozkan) [reply src/tools/build_helper/src/git.rs]: With the "If it fails to find the upstream remote," part, it looks quite clear to me actually :thinking: 

https://github.com/rust-lang/rust/blob/5f327176492e3ef66d8140fb771d77bc2b5eebac/src/tools/build_helper/src/git.rs#L115-L119

**Comment by onur-ozkan** [comment]
This should be ready to land if everyone is happy with the [recent changes](https://github.com/rust-lang/rust/compare/52419fc5ed14e8d3215e9158412dda9f2641e00e..5f327176492e3ef66d8140fb771d77bc2b5eebac).

File: src/tools/build_helper/src/git.rs (hunk 5 above)
Comment (RalfJung) [reply src/tools/build_helper/src/git.rs]: Even in those cases, the merge commit exists upstream. It's just not the one we wanted...

File: src/tools/build_helper/src/git.rs (hunk 3 above)
Comment (RalfJung) [reply src/tools/build_helper/src/git.rs]: That only explains what it does when it does not find the upstream remote, it says nothing about what it does when it finds the upstream remote.

**Comment by Kobzol** [comment]
Fine by me.

**Comment by RalfJung** [comment]
LGTM, thanks!
