### PR TITLE
Do not recover from `Trait()` if generic list is unterminated

### LINKED ISSUE #141436: Forgetting a right angle bracket (`>`) gives: "error: `Fn` traits cannot take lifetime parameters"
### Code

```Rust
trait Trait<'a> {}

fn foo<T: Trait<'static>() {}
```

### Current output

```Shell
error: `Fn` traits cannot take lifetime parameters
 --> src/lib.rs:3:16
  |
3 | fn foo<T: Trait<'static>() {}
  |                ^^^^^^^^^
  |
help: consider using a higher-ranked trait bound instead
  |
3 - fn foo<T: Trait<'static>() {}
3 + fn foo<T: for<'static> Trait() {}
  |

error: expected one of `+`, `,`, `->`, `=`, or `>`, found `{`
 --> src/lib.rs:3:28
  |
3 | fn foo<T: Trait<'static>() {}
  |                            ^ expected one of `+`, `,`, `->`, `=`, or `>`
  |
help: you might have meant to end the type parameters here
  |
3 | fn foo<T: Trait<'static>()> {}
  |                           +

error: could not compile `playground` (lib) due to 2 previous errors
```

### Desired output

```Shell

```

### Rationale and extra context

The first error is confusing and unhelpful. Maybe only suggest it when the trait is named `Fn`/`FnMut`/`FnOnce`?

Also, the second error suggests adding the `>` in the wrong place.

### Other cases

```Rust

```

### Rust Version

```Shell
Reproducible on the playground with rustc 1.89.0-nightly (2025-05-22 2eef47813f25df637026)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
If we encounter `fn foo<T: Trait()`, the recovery logic would it as if `Trait` was intended to use the Fn-like trait syntax, but if we don't know for certain that we've parsed a full trait bound (`fn foo<T: Trait()>`), we bail from the recovery as more likely there could have been a missing closing `>` and the `(` corresponds to the start of the fn parameter list.

Fix rust-lang/rust#141436.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -1488,21 +1488,62 @@ impl<'a> Parser<'a> {
...
+            Err(err) => {
+                if let Some(snapshot) = snapshot {
+                    self.restore_snapshot(snapshot);
+                    err.cancel();
+                    return Ok(());
+                } else {
+                    return Err(err);
+                }
+            }
+        };
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/ty.rs:1513]: These changes weren't strictly necessary for the test case, but we should always be restoring snapshots if we encounter parse errors in recovery logic.

**Review by davidtwco — APPROVED** [review]
While there clearly isn't broad consensus on how much recovery in the parser is too much, my disposition is that parser complexity is relatively low-risk for the impact changes like these have.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151171/7704328ba5ae8d6ce0ac303c9d5a1a1605906766..c6c4372f8231bab89007267c23a42e35b177578b)*
