### PR TITLE
drop global where-bounds before merging candidates

### LINKED ISSUE #172: downcast regression
https://crater-reports.s3.amazonaws.com/pr-133502-1/try%23fa8e241660363f48d64b66b05eea58c93ab828fb/reg/mockall-0.13.1/log.txt

```rust
pub trait Any: 'static {}

pub trait Downcast<T>: Any
where
    T: Any,
{
}

impl dyn Any {
    pub fn is<T>(&self)
    where
        T: Any,
        Self: Downcast<T>,
    {
    }
}
```

### PR DESCRIPTION
**Pull request by lcnr**
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/172

r? @compiler-errors

### CODE REVIEW

File: tests/ui/traits/winnowing/global-where-bound-region-constraints-2.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+where
+    T: Any,
+{
+}
+
+impl dyn Any {
+    pub fn is<T>(&self)
+    where
+        T: Any,
+        Self: Downcast<T>,
```
Comment (compiler-errors) [inline tests/ui/traits/winnowing/global-where-bound-region-constraints-2.rs:26]: Please add a comment that elaborating this is where the global where bound comes from; it's not obviously clear from the test file.

Comment (lcnr) [reply tests/ui/traits/winnowing/global-where-bound-region-constraints-2.rs:28]: done
