### PR TITLE
Automatically enable -Zorbit if -Zincremental is specified.

### LINKED ISSUE #34973: Warn or abort if -Zincremental is used without -Zorbit
Because of #34151, incremental compilation cannot work reliably without MIR-trans. We should make sure that we can't run into this accidentally.

cc @nikomatsakis

### PR DESCRIPTION
**Pull request by michaelwoerister**
Fixes #34973

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/session/config.rs [hunk 1]
```diff
@@ -1145,6 +1145,20 @@ pub fn build_session_options(matches: &getopts::Matches) -> Options {
...
+    // Incremental compilation only works reliably when translation is done via
+    // MIR, so let's enable -Z orbit if necessary (see #34973).
+    let debugging_opts = if debugging_opts.incremental.is_some() &&
+                            !debugging_opts.orbit {
+        early_warn(error_format, "Automatically enabling `-Z orbit` because \
+                                  `-Z incremental` was specified");
+        DebuggingOptions {
+            orbit: true,
+            .. debugging_opts
+        }
```
Comment (eddyb) [inline src/librustc/session/config.rs]: This is a bit too much, could mutation be used instead?

Comment (nagisa) [inline src/librustc/session/config.rs]: Easily optimised out.

Comment (nagisa) [inline src/librustc/session/config.rs]: Though, I agree it would look better with mutation here.

Comment (eddyb) [inline src/librustc/session/config.rs]: I was talking about code readability, not performance :laughing:.

Comment (michaelwoerister) [inline src/librustc/session/config.rs]: > This is a bit too much, could mutation be used instead?

You think? I actually thought that it was more readable that way. The alternative would be to make `debugging_opts` mutable, but it's within a *huge* function.

Or would you prefer this:
```rust
    let debugging_opts = if debugging_opts.incremental.is_some() &&
                            !debugging_opts.orbit {
        early_warn(error_format, "Automatically enabling `-Z orbit` because \
                                  `-Z incremental` was specified");
        let mut debugging_opts = debugging_opts;
        debugging_opts.orbit = true;
        debugging_opts
    }
```
I really don't care that much one way or the other, just tell me which version you want :)

Comment (eddyb) [inline src/librustc/session/config.rs]: I would've expected making `debugging_opts` mutable to be fine.

Comment (michaelwoerister) [inline src/librustc/session/config.rs]: OK, I'll change it.

**Comment by nikomatsakis** [comment]
r=me once updated

File: src/test/compile-fail/enable-orbit-for-incr-comp.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// ignore-pretty
+// compile-flags:-Zincremental=tmp/cfail-tests/enable-orbit-for-incr-comp
```
Comment (eddyb) [inline src/test/compile-fail/enable-orbit-for-incr-comp.rs]: You need `-Zorbit=off` now to test this.

**Comment by michaelwoerister** [comment]
@bors r=nikomatsakis

Set `-Zorbit=off` in the test case...
