### PR TITLE
avoid type-live-for-region obligations on dummy nodes

### LINKED ISSUE #46069: ICE: region_obligations not empty
New ICE discovered (in itertools' test suite):

```rust
thread 'rustc' panicked at 'region_obligations not empty: [
    (
        NodeId(
            0
        ),  
        RegionObligation(sub_region='_#60r, sup_type=u8)
    )   
]', /checkout/src/librustc/infer/mod.rs:1160:8
```

(Note, the issue has been worked around in itertools, to keep CI green)

## Code to reproduce
<details>

[(playground link)](https://play.rust-lang.org/?gist=1138d2faf4adf6c947d4fbdffb4a41af&version=nightly)

```rust
//! ```cargo
//! [dependencies]
//! itertools = "=0.7.2"
//! ```
extern crate itertools;

use itertools::Itertools;

fn equal_combinations_2(a: Vec<u8>) {
    a.iter().cloned().tuple_combinations::<(_, _)>();
}
```

Implementation links for tuple_combinations:

1. https://github.com/bluss/rust-itertools/blob/c56a69d7cc3014b04bb88bbe42040a0243168a0a/src/lib.rs#L992-L998
2. https://github.com/bluss/rust-itertools/blob/c56a69d7cc3014b04bb88bbe42040a0243168a0a/src/adaptors/mod.rs#L910-L921
</details>

## Full error
<details>

```rust
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0-nightly (d0f8e2913 2017-11-16) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'region_obligations not empty: [
    (
        NodeId(
            0
        ),  
        RegionObligation(sub_region='_#60r, sup_type=u8)
    )   
]', /checkout/src/librustc/infer/mod.rs:1160:8
```
</details>

### PR DESCRIPTION
**Pull request by arielb1**
Type-live-for-region obligations on DUMMY_NODE_ID cause an ICE, and it
turns out that in the few cases they are needed, these obligations are not
needed anyway because they are verified elsewhere.

Fixes #46069.

Beta-nominating because this is a regression for our new beta.
r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/mod.rs [hunk 1]
```diff
@@ -511,8 +514,24 @@ pub fn normalize_param_env_or_error<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+        // regionck (though I made some efforts to extract it
+        // out). -nmatsakis
+        //
+        // @arielby: In any case, these obligations are checked
+        // by wfcheck anyway, so I'm not sure we have to check
+        // them here too, and we will remove this function when
+        // we move over to lazy normalization *anyway*.
+        let fulfill_cx = FulfillmentContext::new_ignoring_regions();
+
         let predicates = match fully_normalize(
```
Comment (kennytm) [inline src/librustc/traits/mod.rs]: You mean `fully_normalize_with_fulfillcx` here?

```
[00:08:49] error[E0061]: this function takes 4 parameters but 5 parameters were supplied
[00:08:49]    --> /checkout/src/librustc/traits/mod.rs:533:13
[00:08:49]     |
[00:08:49] 533 |               &infcx,
[00:08:49]     |               ^^^^^^ expected 4 parameters
[00:08:49] ...
[00:08:49] 588 | / pub fn fully_normalize<'a, 'gcx, 'tcx, T>(infcx: &InferCtxt<'a, 'gcx, 'tcx>,
[00:08:49] 589 | |                                           cause: ObligationCause<'tcx>,
[00:08:49] 590 | |                                           param_env: ty::ParamEnv<'tcx>,
[00:08:49] 591 | |                                           value: &T)
[00:08:49] ...   |
[00:08:49] 609 | |     fully_normalize_with_fulfillcx(infcx, fulfillcx, cause, param_env, value)
[00:08:49] 610 | | }
[00:08:49]     | |_- defined here
```

**Review by nikomatsakis — APPROVED** [review]

**Comment by WiSaGaN** [comment]
Hmm, was it supposed to be backported to 1.23.0? Stable 1.23.0 failed the test in this pull request.

**Comment by alexcrichton** [comment]
Looks like we forgot to backport to 1.23.0 (sorry about that!) so removing the beta tags.
