### PR TITLE
Suppress debuginfo on naked function arguments

### LINKED ISSUE #42779: Naked functions with arguments generate a prologue
When compiling

```rust
#[naked]
pub extern fn naked_test(_fubar: u64) {
    unsafe { asm!("int3") }
}
```
(https://is.gd/Q03g7b)

The generated assembly includes a prologue with unexpected `mov`'s (as well as a trailing `ret`, already reported in https://github.com/rust-lang/rust/issues/32487)

Expected behaviour would be to have no prologue (and prevent compilation of a `#[naked]` function that is not `extern` as this would require implementing an undefined ABI, contrarily to what seems to happen https://is.gd/sQFBIy).

This is treacherous, as it dereferences some memory locations that may not be accessible, as happened to me and led to hours of debugging to finally figure out the compiled function was not the one defined.

cc https://github.com/rust-lang/rust/issues/32408

### PR DESCRIPTION
**Pull request by npmccallum**
A function that has no prologue cannot be reasonably expected to support
debuginfo. In fact, the existing code (before this patch) would generate
invalid instructions that caused crashes. We can solve this easily by
just not emitting the debuginfo in this case.

Fixes https://github.com/rust-lang/rust/issues/42779
cc https://github.com/rust-lang/rust/issues/32408

### CODE REVIEW

File: src/librustc_mir_build/build/mod.rs [hunk 1]
```diff
@@ -790,12 +791,22 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
         for &ArgInfo(ty, _, arg_opt, _) in arguments.iter() {
             let source_info =
                 SourceInfo::outermost(arg_opt.map_or(self.fn_span, |arg| arg.pat.span));
             let arg_local = self.local_decls.push(LocalDecl::with_source_info(ty, source_info));
 
+            // Emit function argument debuginfo only for non-naked functions.
+            // See: https://github.com/rust-lang/rust/issues/42779
+            if naked {
+                continue;
+            }
```
Comment (eddyb) [inline src/librustc_mir_build/build/mod.rs:808]: I don't think this is a good idea, wouldn't be safer to just disable *all* debuginfo generation for `#[naked]` functions in codegen?

Comment (eddyb) [reply src/librustc_mir_build/build/mod.rs:808]: Also this PR doesn't add a `mir-opt` test showing the lack of MIR debuginfo (but which we might not want anyway).

Comment (npmccallum) [reply src/librustc_mir_build/build/mod.rs:808]: @eddyb We don't want to suppress the debuginfo describing the calling contract of the function, just the internal function operations. The lldb can reference this information to show the contents of (for example) the first argument in `%rdi`. But if you think we need to implement this another way, I'm not particular.

**Comment by Manishearth** [comment]
@bors r- rollup-
 
I think this is causing a hang on arm-android, two rollups have hung on this:

https://github.com/rust-lang-ci/rust/runs/860094251 and https://github.com/rust-lang-ci/rust/runs/856552047:

```
2020-07-11T02:39:35.4466629Z test [debuginfo-gdb] debuginfo/extern-c-fn.rs ... /checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/extern-c-fn.gdb/a: 1 file pushed. 9.4 MB/s (52944 bytes in 0.005s)
2020-07-11T02:39:36.3020313Z [32mok(B[m
2020-07-11T02:39:36.3021136Z test [debuginfo-gdb] debuginfo/function-arg-initialization.rs ... [33mignored(B[m
2020-07-11T02:39:36.4432938Z test [debuginfo-gdb] debuginfo/function-arguments.rs ... /checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/function-arguments.gdb/a: 1 file pushed. 2.8 MB/s (52292 bytes in 0.018s)
```

**Comment by npmccallum** [comment]
@Manishearth Can you help me out? I'm not sure what to do here. I suspect there is some problem with the test. But I have no idea how to set up arm-android to test it.

**Comment by Manishearth** [comment]
I'm sorry, I have no idea

**Comment by npmccallum** [comment]
@Manishearth I spent ~6 hours today trying to get an `arm-android` environment running to debug the test, but I failed. The latest version of this patch is a practical solution: split debuginfo testing for naked functions into a separate test and `ignore-android`.

**Comment by Manishearth** [comment]
I'm not the reviewer, you have to convince @matthewjasper or someone else on the compiler team that this is acceptable

**Comment by matthewjasper** [comment]
The hang appears to happen in master as well, r=me with an issue opened and referenced in the test for this.

**Comment by npmccallum** [comment]
@matthewjasper I'm not clear what you're asking for. Do you want me to open an issue about `arm-android` hangs, mention you in it and add a comment to this test with a link to the issue?

**Comment by matthewjasper** [comment]
Yes

**Comment by npmccallum** [comment]
@matthewjasper Done. Thanks!

**Comment by npmccallum** [comment]
Can someone please remove `S-waiting-on-author`? Thanks!
