### PR TITLE
_match: correct max_slice_length logic

### LINKED ISSUE #37598: advanced_slice_patterns has unreachable expression
Hello,

According to this [chapiter](https://doc.rust-lang.org/book/slice-patterns.html), I have writted this example:
```rust
#![feature(advanced_slice_patterns, slice_patterns)]


fn check(list: &[u8]) {
    match list {
        &[] => {},
        &[u1 @ b'\xF0' ... b'\xF4', u2 @ b'\x8F' ... b'\x90',
          u3 @ b'\x80' ... b'\xBF', u4 @ b'\x80' ... b'\xBF', ref next..] => {
            println!("{} {} {} {}", u1, u2, u3, u4);
            check(next)
        },
        &[u1, ref next..] => {
            println!("{}", u1);
            check(next)
        },
    }
}

fn main() {
    let buf = &[b'0', b'1', b'4'];
    
    check(&buf[..]);
}
```

But after the rustc 1.14.0-nightly version from 2016-10-25 -aef18be1b-, 
I expected to see this happen:
```rust

error[E0001]: unreachable pattern
  --> <anon>:12:9
   |
12 |         &[u1 @ b'\xF0' ... b'\xF4',
   |         ^ this is an unreachable pattern

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by arielb1**
The logic used to be wildly wrong, but before the HAIR patch its wrongness was in most cases hidden by another bug.

Fixes #37598.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_const_eval/_match.rs [hunk 1]
```diff
@@ -419,6 +419,52 @@ fn all_constructors(_cx: &mut MatchCheckCtxt, pcx: PatternContext) -> Vec<Constr
...
+    // only variable-length patterns apply.
+    //
+    // For variable length patterns, all elements after the first
+    // `prefix_len` but before the last `suffix_len` are matched by
+    // the wildcard "middle" pattern, and therefore can be added/removed
+    // without affecting the match result.
+    //
+    // This means that all patterns with length at least
+    // `max(max_fixed+1,max_prefix+max_suffix)` are equivalent, so we
+    // only need to check patterns from that length and below.
```
Comment (nikomatsakis) [inline src/librustc_const_eval/_match.rs]: This is a good comment! 

A minor note: I think it would be marginally improved by a code example, showing what (e.g.) `max_fixed` etc mean in Rust code.

Comment (nikomatsakis) [inline src/librustc_const_eval/_match.rs]: Actually, I *am* a bit confused -- why is it `max_fixed_len + 1`?

File: src/librustc_const_eval/_match.rs [hunk 2]
```diff
@@ -419,6 +419,99 @@ fn all_constructors(_cx: &mut MatchCheckCtxt, pcx: PatternContext) -> Vec<Constr
...
+    // by an infinite collection of fixed-length array patterns.
+    //
+    // Checking the infinite set directly would take an infinite amount
+    // of time. However, it turns out that for each finite set of
+    // patterns `P`, all sufficiently large array lengths are equivalent:
+    //
+    // Each slice `s` with a "sufficiently-large" length `l ≥ L` that applies
+    // to exactly the subset `Pₜ` of `P` can be transformed to a slice
+    // `sₘ` for each sufficiently-large length `m` that applies to exactly
+    // the same subset of `P`.
```
Comment (nikomatsakis) [inline src/librustc_const_eval/_match.rs]: This comment is now even more awesome =) But I admit I am kind of getting lost a bit. It would have been helpful (for me) to note that these are *byte* slices, and that -- effectively -- `b"123"` is equivalent to `&[b'1', b'2', b'3']`.

And then maybe some examples like:

```rust
match foo { // foo : &[u8]
    b"123" => ..., // matches byte strings of length 3
    b"1234" => ..., // matches byte strings of length 4
    &[b'1', ..c, b'9'] => , // matches byte strings of length 2..infinity
} // here `max_slice_check` yields 5, as `max_fixed_len` is 4, `max_prefix_len` is 1, `max_suffix_len` is 1
```

```rust
match foo { // foo : &[u8]
    b"123" => ..., // matches byte strings of length 3
    b"1234" => ..., // matches byte strings of length 4
    &[b'1', b'2',  ..c, b'7', b'8, b'9'] => , // matches byte strings of length 5..infinity
} // here `max_slice_check` again yields 5, as `max_fixed_len` is 4, `max_prefix_len` is 2, `max_suffix_len` is 3
```

Comment (arielb1) [inline src/librustc_const_eval/_match.rs]: These are *not* byte slices, in general (see examples with boolean slices and `Option<()>` slices).

If there is a byte literal, then *as usual* it is treated like the expanded byte slice.
