### PR TITLE
Avoid "no field" error and ICE on recovered ADT variant

### LINKED ISSUE #126344: struct fields are reported as unknown if their type is syntactically invalid.
### Code

```Rust
struct Wrong {
    x: 1,
}

fn oops(w: &Wrong) {
    w.x;
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error: expected type, found `1`
 --> src/lib.rs:2:8
  |
1 | struct Wrong {
  |        ----- while parsing this struct
2 |     x: 1,
  |        ^ expected type

error[E0609]: no field `x` on type `&Wrong`
 --> src/lib.rs:6:7
  |
6 |     w.x;
  |       ^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `playground` (lib) due to 2 previous errors
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error: expected type, found `1`
 --> src/lib.rs:2:8
  |
1 | struct Wrong {
  |        ----- while parsing this struct
2 |     x: 1,
  |        ^ expected type

For more information about this error, try `rustc --explain E0609`.
error: could not compile `playground` (lib) due to 2 previous errors
```

### Rationale and extra context

this can lead to an unmanageably large number of errors if there is a syntactic error in a struct that is used frequently throughout a crate, potentially even thousands of lines.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.80.0-nightly (debd22da6 2024-05-29)
binary: rustc
commit-hash: debd22da66cfa97c74040ebf68e420672ac8560e
commit-date: 2024-05-29
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Anything else?

_No response_

### LINKED ISSUE #126744: ICE: typeck: `no index for a field`
snippet:
````rust
struct TestStruct {,}

fn edge_case_if() {
    let ts = TestStruct {};
    let _b = || { match ts {
        TestStruct{ x: 1, .. } | _ => (),
    }};
}



````

Version information
````
rustc 1.81.0-nightly (1ca578e68 2024-06-20)
binary: rustc
commit-hash: 1ca578e68eb715e772fc0c1b9e6ca7c5b122765a
commit-date: 2024-06-20
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected identifier, found `,`
 --> /tmp/icemaker_global_tempdir.hJLG4Uu9QCDq/rustc_testrunner_tmpdir_reporting.cVa4rm3LGIDH/mvce.rs:1:20
  |
1 | struct TestStruct {,}
  |        ----------  ^ expected identifier
  |        |
  |        while parsing this struct

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.hJLG4Uu9QCDq/rustc_testrunner_tmpdir_reporting.cVa4rm3LGIDH/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.hJLG4Uu9QCDq/rustc_testrunner_tmpdir_reporting.cVa4rm3LGIDH/mvce.rs`

thread 'rustc' panicked at compiler/rustc_hir_typeck/src/expr_use_visitor.rs:1697:26:
no index for a field
stack backtrace:
   0:     0x71e31da31915 - std::backtrace_rs::backtrace::libunwind::trace::h796e75e96c439f3e
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x71e31da31915 - std::backtrace_rs::backtrace::trace_unsynchronized::h57b5b13bb46e11ba
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x71e31da31915 - std::sys::backtrace::_print_fmt::h11ce45f986076e87
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/backtrace.rs:68:5
   3:     0x71e31da31915 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcd09ba6a4fc236f1
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/backtrace.rs:44:22
   4:     0x71e31da824bb - core::fmt::rt::Argument::fmt::h914f09f4a1c58d59
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/core/src/fmt/rt.rs:165:63
   5:     0x71e31da824bb - core::fmt::write::hc590b91d463e6a2c
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/core/src/fmt/mod.rs:1168:21
   6:     0x71e31da265af - std::io::Write::write_fmt::hc69b1d0ded026622
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/io/mod.rs:1835:15
   7:     0x71e31da316ee - std::sys::backtrace::_print::hc852e4497da27a95
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/backtrace.rs:47:5
   8:     0x71e31da316ee - std::sys::backtrace::print::hc624de700d5fe576
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/backtrace.rs:34:9
   9:     0x71e31da34129 - std::panicking::default_hook::{{closure}}::hf8d8481f1d9702fb
  10:     0x71e31da33ecc - std::panicking::default_hook::he469b58de751f8ee
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/panicking.rs:292:9
  11:     0x71e31a147870 - std[eca1b30e63fdea7a]::panicking::update_hook::<alloc[79c37403ec1ba474]::boxed::Box<rustc_driver_impl[93e75e0175b92285]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x71e31da34a4f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7fb9108d23a6d563
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/alloc/src/boxed.rs:2076:9
  13:     0x71e31da34a4f - std::panicking::rust_panic_with_hook::h738066c73a52890f
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/panicking.rs:804:13
  14:     0x71e31da34677 - std::panicking::begin_panic_handler::{{closure}}::h8534a2aac695431b
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/panicking.rs:670:13
  15:     0x71e31da31dd9 - std::sys::backtrace::__rust_end_short_backtrace::h3420ee35d28bf807
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/backtrace.rs:171:18
  16:     0x71e31da34304 - rust_begin_unwind
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/panicking.rs:661:5
  17:     0x71e31da7ea73 - core::panicking::panic_fmt::h51cb44e3a97167f8
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/core/src/panicking.rs:74:14
  18:     0x71e31da7e8cb - core::panicking::panic_display::h01c80b100e2db3b0
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/core/src/panicking.rs:264:5
  19:     0x71e31da7e8cb - core::option::expect_failed::h227980ecada19c49
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/core/src/option.rs:2023:5
  20:     0x71e31c05cd08 - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::cat_pattern::<<rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::maybe_read_scrutinee<core[daaba097f859fa28]::iter::adapters::map::Map<core[daaba097f859fa28]::slice::iter::Iter<rustc_hir[f2dc79efc6c2027e]::hir::Arm>, <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::walk_expr::{closure#1}>>::{closure#0}>
  21:     0x71e31c05c919 - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::cat_pattern::<<rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::maybe_read_scrutinee<core[daaba097f859fa28]::iter::adapters::map::Map<core[daaba097f859fa28]::slice::iter::Iter<rustc_hir[f2dc79efc6c2027e]::hir::Arm>, <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::walk_expr::{closure#1}>>::{closure#0}>
  22:     0x71e31c0669c0 - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::walk_expr
  23:     0x71e31c0656b0 - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::consume_expr
  24:     0x71e31c06404e - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::walk_block
  25:     0x71e31c0656b0 - <rustc_hir_typeck[3a3cc19eb2dfac16]::expr_use_visitor::ExprUseVisitor<&rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt, &mut rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKind>>::consume_expr
  26:     0x71e31c05e887 - <rustc_hir_typeck[3a3cc19eb2dfac16]::fn_ctxt::FnCtxt>::analyze_closure
  27:     0x71e31900c688 - <rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKindVisitor as rustc_hir[f2dc79efc6c2027e]::intravisit::Visitor>::visit_expr
  28:     0x71e31b8a58ef - <rustc_hir_typeck[3a3cc19eb2dfac16]::upvar::InferBorrowKindVisitor as rustc_hir[f2dc79efc6c2027e]::intravisit::Visitor>::visit_block
  29:     0x71e31b8a780b - rustc_hir_typeck[3a3cc19eb2dfac16]::typeck
  30:     0x71e31b8a6ffb - rustc_query_impl[da2d3b64247f93f0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[da2d3b64247f93f0]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a7abdaade2c6424c]::query::erase::Erased<[u8; 8usize]>>
  31:     0x71e31ba031ee - rustc_query_system[5e65d9b3abdd3162]::query::plumbing::try_execute_query::<rustc_query_impl[da2d3b64247f93f0]::DynamicConfig<rustc_query_system[5e65d9b3abdd3162]::query::caches::VecCache<rustc_span[1efc0ab8e6bb0790]::def_id::LocalDefId, rustc_middle[a7abdaade2c6424c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[da2d3b64247f93f0]::plumbing::QueryCtxt, false>
  32:     0x71e31ba01cdf - rustc_query_impl[da2d3b64247f93f0]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  33:     0x71e31ba01915 - <rustc_middle[a7abdaade2c6424c]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[74e881c9b9f2b37]::check_crate::{closure#4}>::{closure#0}
  34:     0x71e31ba003bc - rustc_hir_analysis[74e881c9b9f2b37]::check_crate
  35:     0x71e31bdf4f87 - rustc_interface[7fb7dc76513cf959]::passes::analysis
  36:     0x71e31bdf4ac7 - rustc_query_impl[da2d3b64247f93f0]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[da2d3b64247f93f0]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a7abdaade2c6424c]::query::erase::Erased<[u8; 1usize]>>
  37:     0x71e31c433ea5 - rustc_query_system[5e65d9b3abdd3162]::query::plumbing::try_execute_query::<rustc_query_impl[da2d3b64247f93f0]::DynamicConfig<rustc_query_system[5e65d9b3abdd3162]::query::caches::SingleCache<rustc_middle[a7abdaade2c6424c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[da2d3b64247f93f0]::plumbing::QueryCtxt, false>
  38:     0x71e31c433c0f - rustc_query_impl[da2d3b64247f93f0]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x71e31c2dd252 - rustc_interface[7fb7dc76513cf959]::interface::run_compiler::<core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>, rustc_driver_impl[93e75e0175b92285]::run_compiler::{closure#0}>::{closure#1}
  40:     0x71e31c29dac9 - std[eca1b30e63fdea7a]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[7fb7dc76513cf959]::util::run_in_thread_with_globals<rustc_interface[7fb7dc76513cf959]::util::run_in_thread_pool_with_globals<rustc_interface[7fb7dc76513cf959]::interface::run_compiler<core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>, rustc_driver_impl[93e75e0175b92285]::run_compiler::{closure#0}>::{closure#1}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>::{closure#0}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>
  41:     0x71e31c29d880 - <<std[eca1b30e63fdea7a]::thread::Builder>::spawn_unchecked_<rustc_interface[7fb7dc76513cf959]::util::run_in_thread_with_globals<rustc_interface[7fb7dc76513cf959]::util::run_in_thread_pool_with_globals<rustc_interface[7fb7dc76513cf959]::interface::run_compiler<core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>, rustc_driver_impl[93e75e0175b92285]::run_compiler::{closure#0}>::{closure#1}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>::{closure#0}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[daaba097f859fa28]::result::Result<(), rustc_span[1efc0ab8e6bb0790]::ErrorGuaranteed>>::{closure#2} as core[daaba097f859fa28]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x71e31da3e8cb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1ad2417ff4e2c89
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/alloc/src/boxed.rs:2062:9
  43:     0x71e31da3e8cb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha5ab2243447620ef
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/alloc/src/boxed.rs:2062:9
  44:     0x71e31da3e8cb - std::sys::pal::unix::thread::Thread::new::thread_start::he00df2d38aeed7a5
                               at /rustc/1ca578e68eb715e772fc0c1b9e6ca7c5b122765a/library/std/src/sys/pal/unix/thread.rs:108:17
  45:     0x71e316ca6ded - <unknown>
  46:     0x71e316d2a0dc - <unknown>
  47:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (1ca578e68 2024-06-20) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `edge_case_if`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes https://github.com/rust-lang/rust/issues/126744
Fixes https://github.com/rust-lang/rust/issues/126344, a more general fix compared with https://github.com/rust-lang/rust/pull/127426

r? @oli-obk

From @compiler-errors 's comment https://github.com/rust-lang/rust/pull/127502#discussion_r1669538204 
Seems most of the ADTs don't have taint, so maybe it's not proper to change `TyCtxt::type_of` query.

### CODE REVIEW

File: compiler/rustc_middle/src/ty/mod.rs [hunk 1]
```diff
@@ -1227,15 +1229,23 @@ impl VariantDef {
             flags |= VariantFlags::IS_FIELD_LIST_NON_EXHAUSTIVE;
         }
 
-        if recovered {
+        if recover_tainted.is_some() {
             flags |= VariantFlags::IS_RECOVERED;
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/mod.rs:1233]: you can remove the `IS_RECOVERED` flag from the compiler now

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 2]
```diff
@@ -2547,6 +2544,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        for (ty, _) in self.autoderef(expr.span, base_ty) {
+            if let ty::Adt(def, _) = ty.kind()
+                && !def.is_enum()
+            {
+                let variant = def.non_enum_variant();
+                if let Some(taint) = variant.has_errors() {
+                    return taint;
+                }
+            }
+        }
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/expr.rs:2557]: Additions like this are what I would like to avoid, as we have to add them piecemeal to fix ICEs. Not sure yet how to systematically fix that

**Comment by oli-obk** [comment]
> Seems most of the ADTs don't have taint, so maybe it's not proper to change `TyCtxt::type_of` query.

If we changed the `type_of` query, does the ICE get fixed without having to add extra checks in typeck?

**Comment by oli-obk** [comment]
lol we could make https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Ty.html#method.new_adt return an error type if the `AdtDef` is tainted. It may require some additional adjustments of other code that relies on getting an `ty::Adt` when explicitly asking for one, but it can be done.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 3]
```diff
@@ -2547,6 +2544,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             "ban_nonexisting_field: field={:?}, base={:?}, expr={:?}, base_ty={:?}",
             ident, base, expr, base_ty
         );
+
+        for (ty, _) in self.autoderef(expr.span, base_ty) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/expr.rs:2548]: What is this trying to achieve?

File: compiler/rustc_middle/src/ty/mod.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_middle/src/ty/mod.rs]: yeah, removed.

**Comment by compiler-errors** [comment]
@oli-obk:

> lol we could make https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Ty.html#method.new_adt return an error type if the AdtDef is tainted. It may require some additional adjustments of other code that relies on getting an ty::Adt when explicitly asking for one, but it can be done.

I really don't think we should do this unless there's a compelling reason to do so. These constructor functions shouldn't be lying about their output.

It's one thing to change the `type_of` query, which already has precedent to return `Error` when the query has issues with resolving an item's type, but it's another thing to change the constructors themselves. I will probably reject such a change.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_hir_typeck/src/expr.rs:2548]: trying to avoid no fields diagnostics for this kind of case:
https://github.com/rust-lang/rust/pull/127575/files#diff-6ae6bc33074732b1c0e778c75e56ea6be0c78894cea7c280423f9c1b84a3e82bR8-R18

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 4]
```diff
@@ -1091,7 +1091,10 @@ fn lower_variant(
             vis: tcx.visibility(f.def_id),
         })
         .collect();
-    let recovered = matches!(def, hir::VariantData::Struct { recovered: Recovered::Yes(_), .. });
+    let recovered = match def {
+        hir::VariantData::Struct { recovered: Recovered::Yes(guard), .. } => Some(guard).copied(),
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/collect.rs:1095]:
```suggestion
        hir::VariantData::Struct { recovered: Recovered::Yes(guard), .. } => Some(*guard),
```

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 3 above)
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/expr.rs:2548]: I'd kinda rather you handle this in the autoderef loop in `check_field`.

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 5]
```diff
@@ -1531,9 +1531,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             .filter(|(_, ident)| !used_fields.contains_key(ident))
             .collect::<Vec<_>>();
 
-        let inexistent_fields_err = if !(inexistent_fields.is_empty() || variant.is_recovered())
+        let inexistent_fields_err = if !inexistent_fields.is_empty()
             && !inexistent_fields.iter().any(|field| field.ident.name == kw::Underscore)
         {
+            if let Some(guard) = variant.has_errors() {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/pat.rs:1537]: Make `has_errors` into a `Result<(), ErrorGuaranteed>` so this can just be `variant.has_errors()?;`

**Review by compiler-errors — COMMENTED** [review]
You also need to delete a test from the crashes directory I think

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 6]
```diff
@@ -2342,6 +2343,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     let mut last_ty = None;
                     let mut nested_fields = Vec::new();
                     let mut index = None;
+                    if let Err(guard) = adt_def.non_enum_variant().has_errors() {
+                        recovered_variant = Some(guard);
+                        break;
+                    }
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/expr.rs:2349]:
```suggestion
                    if let Err(guar) = adt_def.non_enum_variant().has_errors() {
                        return Ty::new_error(self.tcx, guar);
                    }
```

**Review by compiler-errors — COMMENTED** [review]
also side note: s/guard/guar, since "guar" is short for "guarantee"

**Comment by compiler-errors** [comment]
Also can you squash this PR lol

**Review by compiler-errors — COMMENTED** [review]
One last thing -- can you leave a short comment next to all of these error-shortcuts you added saying something along the lines of "we don't care to report errors for a struct if the struct itself is tainted" or something

**Comment by compiler-errors** [comment]
r=me after
