### PR TITLE
Do not suggest 'Trait<Assoc=arg>' when in trait impl

### LINKED ISSUE #116464: Incorrect suggestion to define associated type in type parameter list
### Code

```Rust
pub trait One<T> {
    type Assoc;
}

impl<T, S> One<T, S> for () {}
```

### Current output

```Shell
error[E0107]: trait takes 1 generic argument but 2 generic arguments were supplied
 --> src/lib.rs:5:12
  |
5 | impl<T, S> One<T, S> for () {}
  |            ^^^ expected 1 generic argument
  |
note: trait defined here, with 1 generic parameter: `T`
 --> src/lib.rs:1:11
  |
1 | pub trait One<T> {
  |           ^^^ -
help: replace the generic bound with the associated type
  |
5 | impl<T, S> One<T, Assoc = S> for () {}
  |                   +++++++

For more information about this error, try `rustc --explain E0107`.
```

### Desired output

```Shell
error[E0107]: trait takes 1 generic argument but 2 generic arguments were supplied
 --> src/lib.rs:5:12
  |
5 | impl<T, S> One<T, S> for () {}
  |            ^^^ expected 1 generic argument
  |
note: trait defined here, with 1 generic parameter: `T`
 --> src/lib.rs:1:11
  |
1 | pub trait One<T> {
  |           ^^^ -
help: define the associated type in the implementation body
  |
5 | impl<T> One<T> for () {
  |     type Assoc = SomeType;
  |     ++++++++++++++++++++++
  | }

For more information about this error, try `rustc --explain E0107`.
```

### Rationale and extra context

The suggestion is not valid syntax. Applying the original suggestion like so:

```rs
pub trait One<T> {
    type Assoc;
}

impl<T, S> One<T, Assoc = S> for () {}
```

...leads to this error instead:

```text
 --> src/lib.rs:5:19
  |
5 | impl<T, S> One<T, Assoc = S> for () {}
  |                   ^^^^^^^^^ associated type not allowed here

For more information about this error, try `rustc --explain E0229`.
```

Note also that a more naive suggestion to keep the `S` parameter like so:

```rs
pub trait One<T> {
    type Assoc;
}

impl<T, S> One<T> for () {
    type Assoc = S;
}
```

...would fail because it's unconstrained:

```text
error[E0207]: the type parameter `S` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:5:9
  |
5 | impl<T, S> One<T> for () {
  |         ^ unconstrained type parameter

For more information about this error, try `rustc --explain E0207`.
```

`Assoc` needs to be a concrete type or an associated type of an input type parameter.

The diagnostic is identical in beta and nightly.

### PR DESCRIPTION
**Pull request by gurry**
Fixes #116464 

We now skip the suggestion if we're in an impl of the trait.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs [hunk 1]
```diff
@@ -129,6 +129,18 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
         if self.missing_lifetimes() { "lifetime" } else { "generic" }
     }
 
+    fn is_trait(&self) -> bool {
+        self.tcx.is_trait(self.def_id)
+    }
+
+    fn is_in_trait_impl(&self) -> bool {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs:136]: I fear that this will affect the wrong-number-of-generics suggestions when they show up in the self type of a trait impl.

I think we should just check that the path segment associated with this error is contained in this trait ref: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/struct.Impl.html#structfield.of_trait

Comment (gurry) [reply compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs:138]: Thanks. Done.

**Comment by gurry** [comment]
@compiler-errors please review

**Comment by gurry** [comment]
@compiler-errors please review

File: compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs [hunk 2]
```diff
@@ -129,6 +129,46 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
         if self.missing_lifetimes() { "lifetime" } else { "generic" }
     }
 
+    fn is_trait(&self) -> bool {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs:132]: please inline this function into its one callsite

File: compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs [hunk 3]
```diff
@@ -129,6 +129,46 @@ impl<'a, 'tcx> WrongNumberOfGenericArgs<'a, 'tcx> {
...
+        self.tcx.is_trait(self.def_id)
+    }
+
+    /// Returns true if the generic type is a trait
+    /// and is being referred to from one of its trait impls
+    fn is_in_trait_impl(&self) -> bool {
+        self.is_trait() && {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs:139]: what's up with the extra block here? I would just use an if statement.

**Comment by compiler-errors** [comment]
Looks fine, sorry, a few more nits. I've been busy, thanks for the ping.

File: compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs (hunk 2 above)
Comment (gurry) [reply compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs]: Fixed

File: compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs (hunk 3 above)
Comment (gurry) [reply compiler/rustc_hir_analysis/src/structured_errors/wrong_number_of_generic_args.rs]: Guess I overthought this one a bit.

Fixed.

**Comment by gurry** [comment]
> Looks fine, sorry, a few more nits. I've been busy, thanks for the ping.

No worries at all 👍

**Review by compiler-errors — APPROVED** [review]
👍
