### PR TITLE
Saturating casts between integers and floats

### LINKED ISSUE #45134: ICE when casting float to integer (out-of-bounds)
The following program (with perhaps undefined behaviour) causes an ICE:
```rust
fn ice() {
    println!("{:?}", Some(257.0f32 as u8));
}
```

Interestingly, if not wrapping the result in a `Some`, then there's no ICE.
```rust
fn no_ice() {
    println!("{:?}", 257.0f32 as u8);
}
```

Here's the result from running it on the playground:
```rust
   Compiling playground v0.0.1 (file:///playground)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0 (f3d6973f4 2017-08-27) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'assertion failed: !is_undef(val)', /checkout/src/librustc_trans/mir/constant.rs:1083:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by hanna-kruppe**
Introduces a new flag, `-Z saturating-float-casts`, which makes code generation for int->float and float->int casts safe (`undef`-free), implementing [the saturating semantics laid out by](https://github.com/rust-lang/rust/issues/10184#issuecomment-299229143) @jorendorff for float->int casts and overflowing to infinity for `u128::MAX` -> `f32`.
Constant evaluation in trans was changed to behave like HIR const eval already did, i.e., saturate for u128->f32 and report an error for problematic float->int casts.

Many thanks to @eddyb, whose APFloat port simplified many parts of this patch, and made HIR constant evaluation recognize dangerous float casts as mentioned above.
Also thanks to @ActuallyaDeviloper whose branchless implementation served as inspiration for this implementation.

cc #10184 #41799
fixes #45134

### CODE REVIEW

File: src/test/run-pass/saturating-float-casts.rs [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+        common_fptoi_tests!(f64 -> $($ity)+);
+    })
+}
+
+macro_rules! fptoui_tests {
+    ($fty: ident -> $($ity: ident)+) => ({ $(
+        test!(-0., $fty -> $ity, 0);
+        test!(-$fty::MIN_POSITIVE, $fty -> $ity, 0);
+        test!(-1., $fty -> $ity, 0);
+        test!(-100., $fty -> $ity, 0);
```
Comment (sunfishcode) [inline src/test/run-pass/saturating-float-casts.rs]: It'd also be interesting to test a number in (-1,-0.5), such as -0.9, to make sure it's properly rounded up to 0.

File: src/librustc_trans/mir/constant.rs [hunk 2]
```diff
@@ -955,6 +952,55 @@ pub fn const_scalar_checked_binop<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+               Value(llval));
+    });
+    // If this is an u128 cast and the value is > f32::MAX + 0.5 ULP, round up to infinity.
+    if signed {
+        llvm::LLVMConstSIToFP(llval, float_ty.to_ref())
+    } else if value >= 0xffffff80000000000000000000000000_u128 {
+        let infinity_bits = match float_ty.float_width() {
+            32 => C_u32(ccx, ieee::Single::INFINITY.to_bits() as u32),
+            64 => C_u64(ccx, ieee::Double::INFINITY.to_bits() as u64),
+            n => bug!("unsupported float width {}", n),
```
Comment (kennytm) [inline src/librustc_trans/mir/constant.rs]: Only u128 → f32 is the problematic cast here, so the `64 =>` branch should never be entered (i.e. it should be a `bug!`). There's no problem representing `u128::MAX` in `f64` as a finite number.

File: src/librustc_trans/mir/rvalue.rs [hunk 3]
```diff
@@ -815,3 +816,176 @@ fn get_overflow_intrinsic(oop: OverflowOp, bcx: &Builder, ty: Ty) -> ValueRef {
...
+    let is_u128 = !signed && int_ty.int_width() == 128;
+    if is_u128 && bcx.sess().opts.debugging_opts.saturating_float_casts {
+        // f32::MAX + 0.5 ULP as u128. All inputs greater or equal to this should be
+        // rounded to infinity, for everything else LLVM's uitofp works just fine.
+        let max = C_big_integral(int_ty, 0xffffff80000000000000000000000000_u128);
+        let overflow = bcx.icmp(llvm::IntUGE, x, max);
+        let infinity_bits = match float_ty.float_width() {
+            32 => C_u32(bcx.ccx, ieee::Single::INFINITY.to_bits() as u32),
+            64 => C_u64(bcx.ccx, ieee::Double::INFINITY.to_bits() as u64),
+            n => bug!("unsupported float width {}", n),
```
Comment (kennytm) [inline src/librustc_trans/mir/rvalue.rs]: ditto.

Comment (rkruppe) [reply src/librustc_trans/mir/rvalue.rs]: Yes it should be, and that would have caught a bug - I applied the f32 overflow check even when casting to f64. Will add tests for that.

**Comment by rkruppe** [comment]
Incorportated the suggestioned by @sunfishcode and @kennytm.

File: src/librustc_trans/mir/constant.rs [hunk 4]
```diff
@@ -955,6 +952,55 @@ pub fn const_scalar_checked_binop<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+    // Note: this breaks if addresses can be turned into integers (is that possible?)
+    // But at least an ICE is better than producing undef.
+    let value = const_to_opt_u128(llval, signed).unwrap_or_else(|| {
+        panic!("could not get z128 value of constant integer {:?}",
+               Value(llval));
+    });
+    // If this is an u128 cast and the value is > f32::MAX + 0.5 ULP, round up to infinity.
+    if signed {
+        llvm::LLVMConstSIToFP(llval, float_ty.to_ref())
+    } else if value >= 0xffffff80000000000000000000000000_u128 && float_ty.float_width() == 32 {
```
Comment (eddyb) [inline src/librustc_trans/mir/constant.rs]: Do you really need to hardcode this value?

File: src/librustc_trans/mir/rvalue.rs [hunk 5]
```diff
@@ -815,3 +816,176 @@ fn get_overflow_intrinsic(oop: OverflowOp, bcx: &Builder, ty: Ty) -> ValueRef {
...
+                     int_ty: Type,
+                     float_ty: Type) -> ValueRef {
+    // Most integer types, even i128, fit into [-f32::MAX, f32::MAX] after rounding.
+    // It's only u128 -> f32 that can cause overflows (i.e., should yield infinity).
+    // LLVM's uitofp produces undef in those cases, so we manually check for that case.
+    let is_u128_to_f32 = !signed && int_ty.int_width() == 128 && float_ty.float_width() == 32;
+    if is_u128_to_f32 && bcx.sess().opts.debugging_opts.saturating_float_casts {
+        // f32::MAX + 0.5 ULP as u128. All inputs greater or equal to this should be
+        // rounded to infinity, for everything else LLVM's uitofp works just fine.
+        let max = C_big_integral(int_ty, 0xffffff80000000000000000000000000_u128);
```
Comment (eddyb) [inline src/librustc_trans/mir/rvalue.rs]: Same here.

**Comment by eddyb** [comment]
cc @est31 @nagisa @alexcrichton Is there someone better qualified to review floating-point code?

File: src/librustc_trans/mir/constant.rs (hunk 4 above)
Comment (rkruppe) [reply src/librustc_trans/mir/constant.rs]: I don't *need* to, I just didn't see a way to calculate it from existing constants that is simpler to understand and verify, at least to me. However, I didn't put too much thought into it and suggestions are welcome.

File: src/librustc_trans/mir/constant.rs [hunk 6]
```diff
@@ -955,6 +952,55 @@ pub fn const_scalar_checked_binop<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
     }
 }
 
+unsafe fn const_cast_from_float(operand: &Const, signed: bool, int_ty: Type) -> ValueRef {
+    let llval = operand.llval;
+    // Note: this breaks if addresses can be turned into integers (is that possible?)
```
Comment (est31) [inline src/librustc_trans/mir/constant.rs]: This is valid rust code, isn't it?

```
println!("{}", {let w: * const u32 = {let v = 0u32; &v}; w} as usize);
```

File: src/librustc_trans/mir/rvalue.rs [hunk 7]
```diff
@@ -815,3 +816,176 @@ fn get_overflow_intrinsic(oop: OverflowOp, bcx: &Builder, ty: Ty) -> ValueRef {
...
+        let overflow = bcx.icmp(llvm::IntUGE, x, max);
+        let infinity_bits = match float_ty.float_width() {
```
Comment (est31) [inline src/librustc_trans/mir/rvalue.rs]: You don't need the match here

File: src/librustc_trans/mir/constant.rs (hunk 6 above)
Comment (rkruppe) [reply src/librustc_trans/mir/constant.rs]: Yes, but this is constant evaluation and pointer->integer casts in constant expression [do not compile](https://play.rust-lang.org/?gist=6fee9754dcf18aa52ff07a2d477a061a&version=nightly):

```
static Y: i32 = 0;
static Z: usize = &Y as usize;
```

File: src/librustc_trans/mir/rvalue.rs (hunk 7 above)
Comment (rkruppe) [reply src/librustc_trans/mir/rvalue.rs]: I guess that's true now. It wasn't before @kennytm pointed out that I needed the width check up there. (Same in constant evaluation.)

**Comment by rkruppe** [comment]
What's up with travis? The run-pass test fails with an error that looks plausible and platform-independent, but I can't reproduce it.

```
[00:48:14] error: internal compiler error: unexpected panic
[00:48:14] 
[00:48:14] note: the compiler unexpectedly panicked. this is a bug.
[00:48:14] 
[00:48:14] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:48:14] 
[00:48:14] note: rustc 1.22.0-dev running on x86_64-unknown-linux-gnu
[00:48:14] 
[00:48:14] thread 'rustc' panicked at 'attempt to negate with overflow', /checkout/src/librustc_apfloat/lib.rs:383:31
[00:48:14] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

File: src/librustc_trans/mir/constant.rs (hunk 4 above)
Comment (est31) [reply src/librustc_trans/mir/constant.rs]: Where does the 8 come from? The float mantissa has 23 bits. Add the implicit bit, you get 24, which is six times `f`. `println!("{:x}", std::f32::MAX as u128);` gives me six times `f` as well, and its the same [according to the internet](https://stackoverflow.com/questions/11857797/maximum-value-for-type-float-in-c-sharp#comment56894069_11857844).

Comment (est31) [reply src/librustc_trans/mir/constant.rs]: IMO it would be best to have a constant somewhere (maybe in the file?) and use it in both places, e.g. representing it as `0xffffff_u128 << (128 - 24)`, which is IMO the clearest way to display the number.

Comment (est31) [reply src/librustc_trans/mir/constant.rs]: OH I get it, the 8 is needed due to rounding. Disregard my last 2 comments! I still think a constant somewhere with a nice explanation would be cool.

**Comment by rkruppe** [comment]
@est31 This constant isn't f32::MAX, it's f32::MAX + 0.5 ULP. Evidently the constant is not as self-evident as I'd hoped, so I'll figure out a way to compute it that hopefully makes it clearer what's happening.

How about

```
ieee::Single::largest().to_u128(128).value + (1 << (128 - ieee::Single::PRECISION - 1))
```

The -1 is pretty ugly as well ¯\_(ツ)_/¯

File: src/librustc_trans/mir/constant.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_trans/mir/constant.rs]: Since it seems to be a number of `1`s at the top of `u128`, how about computing it from the number of significand bits?

File: src/librustc_trans/mir/rvalue.rs [hunk 8]
```diff
@@ -815,3 +816,172 @@ fn get_overflow_intrinsic(oop: OverflowOp, bcx: &Builder, ty: Ty) -> ValueRef {
...
+    // It's only u128 -> f32 that can cause overflows (i.e., should yield infinity).
+    // LLVM's uitofp produces undef in those cases, so we manually check for that case.
+    let is_u128_to_f32 = !signed && int_ty.int_width() == 128 && float_ty.float_width() == 32;
+    if is_u128_to_f32 && bcx.sess().opts.debugging_opts.saturating_float_casts {
+        // f32::MAX + 0.5 ULP as u128. All inputs greater or equal to this should be
+        // rounded to infinity, for everything else LLVM's uitofp works just fine.
+        let max = C_big_integral(int_ty, 0xffffff80000000000000000000000000_u128);
+        let overflow = bcx.icmp(llvm::IntUGE, x, max);
+        let infinity_bits = C_u32(bcx.ccx, ieee::Single::INFINITY.to_bits() as u32);
+        let infinity = consts::bitcast(, float_ty);
```
Comment (kennytm) [inline src/librustc_trans/mir/rvalue.rs]: 🤣 

```
[00:13:30] error: expected expression, found `,`
[00:13:30]    --> /checkout/src/librustc_trans/mir/rvalue.rs:835:40
[00:13:30]     |
[00:13:30] 835 |         let infinity = consts::bitcast(, float_ty);
[00:13:30]     |                                        ^
```

File: src/librustc_trans/mir/constant.rs (hunk 4 above)
Comment (rkruppe) [reply src/librustc_trans/mir/constant.rs]: Regardless of whether it's hardcoded or computed, I'm not sure where it should live if it's a shared definition. I guess I could chuck it in `common` or something, but ehhhh

File: src/librustc_trans/mir/rvalue.rs (hunk 8 above)
Comment (rkruppe) [reply src/librustc_trans/mir/rvalue.rs]: 😱

File: src/librustc_trans/mir/constant.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_trans/mir/constant.rs]: I'd put it in `rustc_const_math::float`.

File: src/librustc_trans/mir/rvalue.rs [hunk 9]
```diff
@@ -815,3 +816,172 @@ fn get_overflow_intrinsic(oop: OverflowOp, bcx: &Builder, ty: Ty) -> ValueRef {
...
+    // cast result is the integer equal to f_max. If the conversion from int_ty::MAX to f_max
+    // was exact, then the result of casting f_max is again int_ty::MAX, so we'd return the same
+    // value whether or not x > f_max holds. Therefore, we only need to execute this step
+    // if f_max is inexact.
+    if f_max_status.contains(Status::INEXACT) {
+        let int_max = C_big_integral(int_ty, int_max(signed, int_ty));
+        bcx.select(bcx.fcmp(llvm::RealOGT, x, f_max), int_max, cast_result)
+    } else {
+        cast_result
+    }
```
Comment (sunfishcode) [inline src/librustc_trans/mir/rvalue.rs]: I don't know if you're interested in micro-optimizing at this point, but if you are: it looks like this code does 4 selects for f32->i32; it would be a little shorter to take advantage of the fact that fptoui/fptosi in LLVM return undef rather than having UB, so you could do the fptosi/fptoui first, and then use selects to pick between the fptosi/fptui result value and the integer min/max/0 values in the various exceptional cases. That way, you'd always need at most 3 selects.

Comment (rkruppe) [reply src/librustc_trans/mir/rvalue.rs]: I played around with this option a bit but I didn't quickly find a way to write the first two selects such that `ity::MIN` comes out if `x` is NaN. If that's not possible, i.e., a separate NaN check is always necessary, the current code is shorter (two selects) for casts such as f32 -> u16 or f64 -> f32. But perhaps I'm missing the forest for the trees? If someone can come up with a way to do three selects for signed types and two for unsigned casts, I'd gladly implement that (after I find time to address the other nits).

Comment (sunfishcode) [reply src/librustc_trans/mir/rvalue.rs]: Here's a way to do three selects for signed and two for unsigned, which should be generalizable to other bitwidths:

```llvm
define i32 @fptosi(float %f) {
  %t = fptosi float %f to i32
  %c0 = fcmp olt float %f, 0xC1E0000000000000 ; -0x1p31
  %c1 = fcmp oge float %f, 0x41E0000000000000 ; 0x1p31
  %c2 = fcmp uno float %f, 0.000000e+00
  %s0 = select i1 %c0, i32 -2147483648, i32 %t
  %s1 = select i1 %c1, i32 2147483647, i32 %s0
  %s2 = select i1 %c2, i32 0, i32 %s1
  ret i32 %s2
}
```

```llvm
define i32 @fptoui(float %f) {
  %t = fptoui float %f to i32
  %c0 = fcmp ule float %f, 0.000000e+00
  %c1 = fcmp oge float %f, 0x41F0000000000000 ; 0x1p32
  %s0 = select i1 %c0, i32 0, i32 %t
  %s1 = select i1 %c1, i32 -1, i32 %s0
  ret i32 %s1
}
```

File: src/librustc_apfloat/lib.rs [hunk 10]
```diff
@@ -380,7 +380,9 @@ pub trait Float
     fn from_bits(input: u128) -> Self;
     fn from_i128_r(input: i128, round: Round) -> StatusAnd<Self> {
         if input < 0 {
-            Self::from_u128_r(-input as u128, -round).map(|r| -r)
+            // This is equivalent to `(-input) as u128` except it doesn't overflow on i128::MIN
+            let abs_input = !(input as u128) + 1;
```
Comment (eddyb) [inline src/librustc_apfloat/lib.rs]: Ehm, just use `wrapping_neg`? Somehow I forgot to.

Comment (rkruppe) [reply src/librustc_apfloat/lib.rs]: Oh, right, that's a thing.

**Comment by rkruppe** [comment]
@eddyb IIRC you wanted to run crater with the variant that errors on overflow/NaN in trans const eval? That's implemented now.

(That it's implemented now also means this shouldn't be merged in the current state until we've had a crater run.)

**Comment by aidanhs** [comment]
This is behind a couple of other crater runs so will start being cratered in ~4 days.

**Comment by rkruppe** [comment]
Ping @aidanhs, what's the status of the crater run?

**Comment by aidanhs** [comment]
Crater run started - sorry for the delay, I've had a busy week!

**Comment by aidanhs** [comment]
Crater results: http://cargobomb-reports.s3.amazonaws.com/pr-45205/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/blacklist.md). If you see any spurious failures not on the list, please make a PR against that file.

**Comment by rkruppe** [comment]
I assume outputs like concurrent ([before](http://cargobomb-reports.s3.amazonaws.com/pr-45205/f6d7514545cbe83e771a400d04049b96dfb210cd/reg/concurrent-0.2.2/log.txt) / [after](http://cargobomb-reports.s3.amazonaws.com/pr-45205/cc787eba2ca6e3cf90a5e6b04f4fedd924787b68/reg/concurrent-0.2.2/log.txt)), where the log just stops in the middle without any indication of error, are timeouts?

If that's correct, then it appears there are no crates legtimiately affected, with the possible exception of two google projects whose logs I can't access (in bold below):

## Regressions

15 regressions, none(?) legit:
- 4 timeouts: `conc-0.5.0` `pmarino90.blackhole.77884a7cd7beb199b646e69ffc16b0ec46ef8042` `fountaincode-0.0.8` `hopper-0.3.2`
- 1 that might be a timeout, apparently it timed out the tests finished (?): `ceramic-0.3.0`
- 6 spurious already on blacklist: `ai-0.1.0` `rustlearn-0.4.2` `quandl-v3-1.1.0` `simple-munin-plugin-0.1.0` `vidar-0.1.0` `tinco.rust-static_any_map.909025e6146137938d43fd01b2f715a990358662`
- 3 seem spurious, not on blacklist: `assert_cli-0.5.4` `cc-1.0.3` `treeflection-0.1.30`
- **1 whose logs I can't access:** `google-dfareporting2d5-cli-1.0.6+20170428` 

## Fixed
14 "fixed", none(?) legit:
- 4 timeouts: `concurrent-0.2.2` `kernel_density-0.0.1` `fftw-src-0.2.2` `relm-0.10.1`
- 4 spurious already on blacklist: `gcc-0.3.54` `hashconsing-0.3.0` `lua53-ext-0.1.1` `stringsort-2.0.0`
- 5 seem spurious, not on blacklist: `loaded_dice-0.1.1` `tokio-periodic-0.1.1` `unbase-0.1.1` `inotify-0.1.12` `libfuzzy-sys-0.1.0`
- **1 whose logs I can't access:** `google-dfareporting2d8-cli-1.0.6+20170818`

**Comment by kennytm** [comment]
@rkruppe See rust-lang-nursery/crater#153 for how to access that log 😞

**Comment by rkruppe** [comment]
@kennytm Thanks!

@eddyb So in summary, no crates were broken by trans const eval erroring on overflow/NaN. Yay!

**Comment by carols10cents** [comment]
review ping @eddyb!

File: src/librustc_const_math/float.rs [hunk 11]
```diff
@@ -203,3 +203,7 @@ impl ::std::ops::Neg for ConstFloat {
         ConstFloat { bits, ty: self.ty }
     }
 }
+
+/// This is `(f32::MAX + 0.5 ULP)` as an integer. Numbers greater or equal to this
+/// are rounded to infinity when converted to `f32`.
+pub const MAX_F32_PLUS_HALF_ULP: u128 = 0xffffff80000000000000000000000000_u128;
```
Comment (eddyb) [inline src/librustc_const_math/float.rs]: Is there no way to obtain this from `rustc_apfloat`, using the max exponent or something?

File: src/librustc_llvm/ffi.rs [hunk 12]
```diff
@@ -617,6 +617,8 @@ extern "C" {
     pub fn LLVMConstIntGetSExtValue(ConstantVal: ValueRef) -> c_longlong;
     pub fn LLVMRustConstInt128Get(ConstantVal: ValueRef, SExt: bool,
                                   high: *mut u64, low: *mut u64) -> bool;
+    pub fn LLVMRustIsConstantFP(ConstantVal: ValueRef) -> bool;
+    pub fn LLVMRustConstFloatGetBits(ConstantVal: ValueRef) -> u64;
```
Comment (eddyb) [inline src/librustc_llvm/ffi.rs]: Does a bitcast + the existing methods for getting the value of an integer not work?

**Comment by eddyb** [comment]
LGTM in terms of compiler internals, assuming my comments have answers.
r? @alexcrichton for making this user-facing

**Comment by alexcrichton** [comment]
Looks fantastic! I think this is all unstable, right @rkruppe? In that sense once the comments are addressed seems fine to me to land.

File: src/librustc_const_math/float.rs (hunk 11 above)
Comment (rkruppe) [reply src/librustc_const_math/float.rs]: As discussed before, there are several ways but so far nobody found a way that's clearly better than hardcoding. I did discover this just now, which still isn't pretty or very intuitive, but tolerable:

```
pub const MAX_F32_PLUS_HALF_ULP: u128 =
  (1 << Single::PRECISION + 1) - 1 << (Single::MAX_EXP - Single::PRECISION as i16);
```

If you want, I'll update to use that expression instead of hardcoding.

File: src/librustc_llvm/ffi.rs (hunk 12 above)
Comment (rkruppe) [reply src/librustc_llvm/ffi.rs]: No, they do, I just didn't realize that at the time I wrote this. Will update.

**Comment by rkruppe** [comment]
@alexcrichton The runtime code generation is gated on an ordinary -Z flag, so it's only accepted by nightly compilers (but there it works without `-Z unstable-options`). The trans const eval changes are not gated, but those just bring the backend's interpretation of the casts in line with the HIR-based const eval's interpretation.

**Comment by rkruppe** [comment]
Updated to address @eddyb's questions.

**Comment by alexcrichton** [comment]
Ok that all sounds great to me! Sounds like r=eddyb when CI is green

File: src/librustc_const_math/float.rs (hunk 11 above)
Comment (eddyb) [reply src/librustc_const_math/float.rs]: Where is that ` + 1` coming from? Is it supposed to be added to `Single::PRECISION`?

File: src/librustc_const_math/float.rs [hunk 13]
```diff
@@ -203,3 +203,8 @@ impl ::std::ops::Neg for ConstFloat {
         ConstFloat { bits, ty: self.ty }
     }
 }
+
+/// This is `(f32::MAX + 0.5 ULP)` as an integer. Numbers greater or equal to this
+/// are rounded to infinity when converted to `f32`.
+pub const MAX_F32_PLUS_HALF_ULP: u128 =
+  (1 << Single::PRECISION + 1) - 1 << (Single::MAX_EXP - Single::PRECISION as i16);;
```
Comment (eddyb) [inline src/librustc_const_math/float.rs]: There's an extra `;` on this line. Also, to repeat my question, what's the `+ 1` for? The previous constant looked like a subtraction of two powers of 2. Maybe there are "not enough parens" both around shifts and around nontrivial shift operands?

Comment (rkruppe) [reply src/librustc_const_math/float.rs]: I don't think of this constant as a difference of powers of two, but rather as PRECISION + 1 bits set (maximum significand + 1 bit for the half ulp), multiplied by maximum exponent (accounting for normalization).

Comment (eddyb) [reply src/librustc_const_math/float.rs]: Oh then I guess your choice of parens isn't uniform and that's what confused me.

Comment (rkruppe) [reply src/librustc_const_math/float.rs]: I added a bunch of parens and an explanatory comment now (and also removed the duplicate `;`).

Comment (rkruppe) [reply src/librustc_const_math/float.rs]: I added a bunch of parens and an explanatory comment.

**Comment by rkruppe** [comment]
Rebased. Travis is green.

**Comment by kennytm** [comment]
`asmjs` does not support i128 (`Unsupported:   %1826 = fptosi float %1825 to i128`)

<details>

```
[01:32:24] failures:
[01:32:24] 
[01:32:24] ---- [run-pass] run-pass/saturating-float-casts.rs stdout ----
[01:32:24] 	
[01:32:24] error: compilation failed!
[01:32:24] status: exit code: 101
[01:32:24] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/saturating-float-casts.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=asmjs-unknown-emscripten" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.stage2-asmjs-unknown-emscripten.js" "-Crpath" "-O" "-Lnative=/checkout/obj/build/asmjs-unknown-emscripten/native/rust-test-helpers" "-Z" "saturating-float-casts" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.stage2-asmjs-unknown-emscripten.aux"
[01:32:24] stdout:
[01:32:24] ------------------------------------------
[01:32:24] 
[01:32:24] ------------------------------------------
[01:32:24] stderr:
[01:32:24] ------------------------------------------
[01:32:24] error: linking with `emcc` failed: exit code: 1
[01:32:24]   |
[01:32:24]   = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.saturating_float_casts0.rcgu.o" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.stage2-asmjs-unknown-emscripten.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.crate.allocator.rcgu.o" "-O2" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "-L" "/checkout/obj/build/asmjs-unknown-emscripten/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/saturating-float-casts.stage2-asmjs-unknown-emscripten.aux" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libtest-183e233b7c075ec2.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libterm-08fb69f2f719b59c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libgetopts-4f65f6654127877d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libstd-2b35d1b36dfa7e3a.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libpanic_unwind-5bef2c52ac19d279.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-3830ae5679a0b739.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc_system-9ff2c67f40fe5858.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/liblibc-e1c7eeeb00260d82.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc-bad119b0f880de53.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libstd_unicode-c87147d9878a34a6.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/librand-efb9ae917b0ef713.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libcore-f61c023fb8fcfea8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/asmjs-unknown-emscripten/lib/libcompiler_builtins-709204c2e3fe5ec9.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
[01:32:24]   = note: Unsupported:   %1826 = fptosi float %1825 to i128
[01:32:24]           LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
[01:32:24]           Traceback (most recent call last):
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13//emcc", line 13, in <module>
[01:32:24]               emcc.run()
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emcc.py", line 1526, in run
[01:32:24]               final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/tools/shared.py", line 1963, in emscripten
[01:32:24]               call_emscripten(cmdline)
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emscripten.py", line 2190, in _main
[01:32:24]               temp_files.run_and_clean(lambda: main(
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/tools/tempfiles.py", line 78, in run_and_clean
[01:32:24]               return func()
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emscripten.py", line 2195, in <lambda>
[01:32:24]               DEBUG=DEBUG,
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emscripten.py", line 2095, in main
[01:32:24]               temp_files=temp_files, DEBUG=DEBUG)
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emscripten.py", line 93, in emscript
[01:32:24]               backend_output = compile_js(infile, settings, temp_files, DEBUG)
[01:32:24]             File "/emsdk-portable/emscripten/1.37.13/emscripten.py", line 127, in compile_js
[01:32:24]               backend_output = open(temp_js).read()
[01:32:24]           IOError: [Errno 2] No such file or directory: '/tmp/tmptj926K.4.js'
[01:32:24]           
[01:32:24] 
[01:32:24] error: aborting due to previous error
[01:32:24] 
[01:32:24] 
[01:32:24] ------------------------------------------
[01:32:24] 
[01:32:24] thread '[run-pass] run-pass/saturating-float-casts.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2498:8
[01:32:24] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:32:24] 
[01:32:24] 
[01:32:24] failures:
[01:32:24]     [run-pass] run-pass/saturating-float-casts.rs
[01:32:24] 
[01:32:24] test result: [31mFAILED(B[m. 2678 passed; 1 failed; 144 ignored; 0 measured; 0 filtered out
```

</details>

File: src/test/codegen/unchecked-float-casts.rs [hunk 14]
```diff
@@ -0,0 +1,65 @@
...
+pub fn f32_to_i32(x: f32) -> i32 {
+    // CHECK: fptosi
+    // CHECK-NOT: fcmp
+    // CHECK-NOT: icmp
+    // CHECK-NOT: select
+    x as i32
+}
+
+#[no_mangle]
+pub fn f64_to_u8(x: f32) -> u16 {
```
Comment (kpp) [inline src/test/codegen/unchecked-float-casts.rs:40]: Should be either `f32_to_u16(x: f32) -> u16` or `f64_to_u8(x: f64) -> u8`.
