### PR TITLE
Check for missing space between fat arrow and range pattern

### LINKED ISSUE #107420: "inclusive range with no end" error when forgetting a space
### Code

```Rust
fn main(){
    let x = 42;
    match x{
        0..=73 => {}
        74..=> {},
    }
}
```

### Current output

```Shell
error[E0586]: inclusive range with no end
 --> src/main.rs:5:11
  |
5 |         74..=> {},
  |           ^^^ help: use `..` instead
  |
  = note: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)

error: expected one of `=>`, `if`, or `|`, found `>`
 --> src/main.rs:5:14
  |
5 |         74..=> {},
  |              ^ expected one of `=>`, `if`, or `|`

For more information about this error, try `rustc --explain E0586`.
error: could not compile `playground` due to 2 previous errors
```

### Desired output

It should suggest inserting a space:
```diff
-        74..=> {},
+        74.. => {},
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #107420

Ideally we wouldn't emit an error about expecting `=>` etc., but I'm not sure how to recover from this.

@rustbot label +A-diagnostics

### CODE REVIEW

File: compiler/rustc_parse/src/parser/pat.rs [hunk 1]
```diff
@@ -758,20 +758,26 @@ impl<'a> Parser<'a> {
 
         // If the user typed "..==" instead of "..=", we want to give them
         // a specific error message telling them to use "..=".
+        // If they typed "..=>", suggest they use ".. =>".
         // Otherwise, we assume that they meant to type a half open exclusive
         // range and give them an error telling them to do that instead.
-        if matches!(tok.kind, token::Eq) && tok.span.lo() == span.hi() {
-            let span_with_eq = span.to(tok.span);
+        let no_space = tok.span.lo() == span.hi();
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/pat.rs:764]: is `span` always coming from `self.prev_token.span`? If so, could we drop the `span` argument to this fn?

File: compiler/rustc_parse/src/parser/pat.rs [hunk 2]
```diff
@@ -782,6 +788,18 @@ impl<'a> Parser<'a> {
             .emit();
     }
 
+    fn error_inclusive_range_match_arrow(&self, span: Span) {
+        let without_eq = span.with_hi(span.hi() - rustc_span::BytePos(1));
+        self.struct_span_err(span, "unexpected `=>` after open range")
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/pat.rs:793]: could you make this into a derive diagnostic?

File: compiler/rustc_parse/src/parser/pat.rs [hunk 3]
```diff
@@ -782,6 +788,18 @@ impl<'a> Parser<'a> {
...
+            .span_suggestion_verbose(
+                without_eq,
+                "add a space between the pattern and `=>`",
+                ".. ",
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/pat.rs:797]: We could probably adjust the spans a bit more carefully to just make the suggestion `" "`. Do you mind doing that?

**Review by compiler-errors — COMMENTED** [review]
Looks good to me. Minor tweaks, then I can approve.

**Review by compiler-errors — APPROVED** [review]
Wonderful, thanks

**Comment by compiler-errors** [comment]
@clubby789 can you fix the errors?

File: tests/ui/half-open-range-patterns/half-open-range-pats-inclusive-match-arrow.stderr [hunk 4]
```diff
@@ -0,0 +1,19 @@
+error: unexpected `=>` after open range
```
Comment (estebank) [inline tests/ui/half-open-range-patterns/half-open-range-pats-inclusive-match-arrow.stderr:1]: I would have preferred more elaboration in this message. Right now the suggestion helps the user, but it doesn't teach the user what the problem actually was (this was parsed as `InclusiveRangeStart(74) >` and not `ExclusiveRangeStart(74) =>`.

Comment (compiler-errors) [reply tests/ui/half-open-range-patterns/half-open-range-pats-inclusive-match-arrow.stderr:1]: Actually, I agree that this message is confusing now that I look at it. 

It honestly could've probably just been left as the old primary, like "unexpected `>` after inclusive range", perhaps with a label saying something like:

```
 --> $DIR/half-open-range-pats-inclusive-match-arrow.rs:5:11
   |
LL |         74..=> {},
   |           ^^^ This is parsed as an inclusive range `..=`
```

@clubby789, would you like to follow up on this message?
