### PR TITLE
Windows: Allow `File::create` to work on hidden files

### LINKED ISSUE #115745: `File::create` fails on hidden files on Windows
Reported on discord, using `OpenOptions::new().write(true).create(true).truncate(true).open(&path)` will fail on Windows if the file is hidden. This also affects methods like `File::create` or `fs::write` that open the file the same way.

The reason for this is that we use `CREATE_ALWAYS`, which has [strange behaviour](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#files):

> If `CREATE_ALWAYS` and `FILE_ATTRIBUTE_NORMAL` are specified, `CreateFile` fails and sets the last error to `ERROR_ACCESS_DENIED` if the file exists and has the `FILE_ATTRIBUTE_HIDDEN` or `FILE_ATTRIBUTE_SYSTEM` attribute. To avoid the error, specify the same attributes as the existing file.

So to make it work the caller needs to match the requested attributes to the existing attributes at the time of opening.

## Possible solution

It was suggested we could instead use `OPEN_ALWAYS` and then manually truncate the file using [`SetFileInformationByHandle`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileinformationbyhandle) to set the [`FILE_ALLOCATION_INFO`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_allocation_info) to zero.

### PR DESCRIPTION
**Pull request by ChrisDenton**
This makes `OpenOptions::new().write(true).create(true).truncate(true).open(&path)` work if the path exists and is a hidden file. Previously it would fail with access denied.

This makes it consistent with `OpenOptions::new().write(true).truncate(true).open(&path)` (note the lack of `create`) which does not have this restriction. It's also more consistent with other platforms.

Fixes #115745 (see that issue for more details).

### CODE REVIEW

File: library/std/src/sys/windows/fs.rs [hunk 1]
```diff
@@ -287,19 +289,40 @@ impl OpenOptions {
...
+                unsafe {
+                    // Setting the allocation size to zero also sets the
+                    // EOF position to zero.
+                    let alloc = c::FILE_ALLOCATION_INFO { AllocationSize: 0 };
+                    let result = c::SetFileInformationByHandle(
+                        handle.as_raw_handle(),
+                        c::FileAllocationInfo,
+                        ptr::addr_of!(alloc).cast::<c_void>(),
+                        mem::size_of::<c::FILE_ALLOCATION_INFO>() as u32,
+                    );
```
Comment (workingjubilee) [inline library/std/src/sys/windows/fs.rs:320]: Oh **exciting**.

Comment (ChrisDenton) [reply library/std/src/sys/windows/fs.rs:320]: Just a *fancy* way to pass a `u64` to a function 😇

**Comment by thomcc** [comment]
I'm a little worried about the possible race here (between file creation and truncation) but I suppose there's no avoiding it, and it's not like we make any guarantee about atomicity anyway.

@bors r+

**Comment by ChrisDenton** [comment]
> I'm a little worried about the possible race here (between file creation and truncation) but I suppose there's no avoiding it, and it's not like we make any guarantee about atomicity anyway.

Indeed. Also it should be noted that this is essentially how `TRUNCATE_EXISTING` is currently implemented under the hood (well, using the NT equivalent) so we've already unwittingly crossed that bridge,

**Comment by ChrisDenton** [comment]
Hm, a few cargo tests failing. It could be because file metadata is affected differently. Will need to investigate.

**Comment by ChrisDenton** [comment]
Ok... so I think the issue is that a few cargo tests use `fs::write(path, "")` to update the last write time. That has a few problems:

* With this PR, setting the file size to zero when it's already zero does not update the last write time
* Even without this PR, writing an empty string to the file also does not update the last write time

Looking at the docs for [`OpenOptions::create`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.truncate) and [`truncate`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.truncate) I think the new behaviour is arguably within spec, if only by omission.

The easiest fix in this PR would be to set the last write time explicitly. The other option is to say this is fine and Cargo's tests are relying on something we never promised (and I don't think this introduces any actual bug to Cargo as a zero length file that remains zero length is indeed unchanged). I might need to think about this some more.

cc @epage maybe, for if Cargo has a view on this. Also just in case my explanation is missing anything.

**Comment by epage** [comment]
Looking at this, while we do `write(p, "")` in production code, it doesn't seem to be for updating the mtime.  It looks like we only do that in test code.  Whether that is a justifiable change, I leave to libs.

**Comment by ChrisDenton** [comment]
Thanks! I'm kinda leaning towards breaking Cargo's tests here. Especially as we're about to stabilise an API for setting mtimes so it won't be necessary to rely on side-effects.

But I'm not 100% sure yet.

**Comment by ChrisDenton** [comment]
Marking this as blocked on the stabilization of [`File::set_times`](https://doc.rust-lang.org/std/fs/struct.File.html#method.set_times). It'll be good to have a stable and guaranteed way of updating the last write time before this change lands.

**Comment by ChrisDenton** [comment]
Not sure why this was in the queue again so soon. `File::set_times` is now stable (in beta) 🎉 but we'll need to wait for a cargo update before this can be retried.

**Comment by workingjubilee** [comment]
A sync.
@bors r-

**Comment by ChrisDenton** [comment]
#118765 updated cargo so let's try this again

@bors r=thomcc

**Comment by Emilgardis** [comment]
This somehow broke something in wine, not sure how broad the issue is, see https://github.com/cross-rs/cross/discussions/1386#discussioncomment-7874032

**Comment by ChrisDenton** [comment]
Hm, I tend toward thinking that wine should support Windows applications rather than Windows applications should support wine but in this case I think there's a simple fix: we can fallback to a possibly less efficient function if wine tells us its unsupported.

Btw, if anyone does want to have wine support this then head over to [NtSetInformationFile](https://gitlab.winehq.org/wine/wine/-/blob/master/dlls/ntdll/unix/file.c?ref_type=heads#L4566) and write a quick implementation for `FileAllocationInformation` (we don't use this low level interface in Rust's std but it has to be implemented before the higher level one can be). See the [win api docs for info on the behaviour](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_allocation_information#remarks). It's more or less `ftruncate` if `AllocationSize <= st_size` (though it also moves the file pointer) or `fallocate` (with `FALLOC_FL_KEEP_SIZE`) otherwise.

**Comment by ChrisDenton** [comment]
I created #119051 to fix this issue. I ended up going the simpler route of always using something that is supported by WINE instead of only as a fallback.
