### PR TITLE
fix: fs::remove_dir_all: treat internal ENOENT as success

### LINKED ISSUE #127576: `std::fs::remove_dir_all` fails if any of the intermediate file deletions fails with `ENOENT`
https://github.com/rust-lang/rust/blob/d81987661a06ae8d49a5f014f81824c655e87768/library/std/src/sys/pal/unix/fs.rs#L2144

https://github.com/rust-lang/rust/blob/d81987661a06ae8d49a5f014f81824c655e87768/library/std/src/sys/pal/unix/fs.rs#L2156-L2159

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes #127576

try-job: test-various

### CODE REVIEW

**Comment by tbu-** [comment]
I think there's also the fallback implementation which also needs this treatment.

**Comment by tgross35** [comment]
This changes behavior of a user-visible interface, and has an ACP open at https://github.com/rust-lang/libs-team/issues/410.

@rustbot label +S-waiting-on-ACP +T-libs-api -T-libs

**Comment by cuviper** [comment]
r? libs-api

**Comment by tgross35** [comment]
🤔 does libs-api not go through triagebot.toml? Mara removed herself from the libs rotation recently.

r? libs-api

**Comment by Amanieu** [comment]
> 🤔 does libs-api not go through triagebot.toml? Mara removed herself from the libs rotation recently.

libs-api uses the team member list directly. triagebot.toml is only used for the initial assignment.

**Comment by tgross35** [comment]
I stand corrected about the ACP, that is for a superset of this change so this PR alone shouldn't be blocked.

@rustbot author

File: library/std/src/sys/pal/unix/fs.rs [hunk 1]
```diff
@@ -2113,6 +2113,16 @@ mod remove_dir_impl {
...
 
+    fn is_enoent(result: &io::Result<()>) -> bool {
+        if let Err(err) = result
+            && matches!(err.raw_os_error(), Some(libc::ENOENT))
+        {
+            true
+        } else {
+            false
+        }
+    }
```
Comment (tbu-) [inline library/std/src/sys/pal/unix/fs.rs:2124]:
```suggestion
    fn ignore_enoent(result: io::Result<()>) -> io::Result<()> {
        if let Err(err) = &result && err.raw_os_error() == Some(libc::ENOENT) {
            Ok(())
        } else {
            result
        }
    }
```

With this function, you can simply wrap the relevant function calls in `ignore_enoent`.

File: library/std/src/sys/pal/unix/fs.rs [hunk 2]
```diff
@@ -2113,6 +2113,16 @@ mod remove_dir_impl {
...
+
     fn remove_dir_all_recursive(parent_fd: Option<RawFd>, path: &CStr) -> io::Result<()> {
         // try opening as directory
         let fd = match openat_nofollow_dironly(parent_fd, &path) {
```
Comment (tbu-) [inline library/std/src/sys/pal/unix/fs.rs:2128]:
```suggestion
        let fd = match ignore_enoent(openat_nofollow_dironly(parent_fd, &path)) {
```

File: library/std/src/sys/pal/unix/fs.rs [hunk 3]
```diff
@@ -2128,36 +2138,57 @@ mod remove_dir_impl {
...
-        let (dir, fd) = fdreaddir(fd)?;
-        for child in dir {
-            let child = child?;
-            let child_name = child.name_cstr();
-            match is_dir(&child) {
-                Some(true) => {
-                    remove_dir_all_recursive(Some(fd), child_name)?;
-                }
-                Some(false) => {
-                    cvt(unsafe { unlinkat(fd, child_name.as_ptr(), 0) })?;
```
Comment (tbu-) [inline library/std/src/sys/pal/unix/fs.rs:2144]:
```rs
                    ignore_enoent(cvt(unsafe { unlinkat(fd, child_name.as_ptr(), 0) }))?;
```

File: tests/run-make/remove-dir-all-race/rmake.rs [hunk 4]
```diff
@@ -0,0 +1,37 @@
+use run_make_support::{
```
Comment (jieyouxu) [inline tests/run-make/remove-dir-all-race/rmake.rs:1]: This test slightly concerns me, as in is this a non-deterministic test that *usually* fails or *usually passes*, but we can guarantee it to be reproducible?

Comment (jieyouxu) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: This will also need to run through various try jobs, including various cross-compilation scenarios.

Is this test meant to be reproducible across each platform? Are macOS/various linux/Windows behavior different with respect to remove_dir_all?

Also note that some of the CI runners are ran as root, which may cause behavioral differences versus running as non-root. (As in, even if it passes in CI does not guarantee it passes locally as non-root...)

Comment (ChrisDenton) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: I think to test this reliably it'd require a much larger directory structure and with many more threads. Even then it may not be 100% reliable.

Comment (Nilstrieb) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: if we make the test platform specific we may be able to do some LD_PRELOAD fault injection? not sure if that's better^^

Comment (ChrisDenton) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: I do not think that's better, lol.

Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: race conditions are inherently nondeterministic, so i don't think that can be helped.

it would be possible to insert yield_now calls specifically for testing, but then the code being tested isn't the same as that being used in production.

Comment (ChrisDenton) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: I *think* @jieyouxu is suggesting that it may be better to have no test than a potentially flaky test? Because flaky tests can be hard to pin down and diagnose.

Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: > This will also need to run through various try jobs, including various cross-compilation scenarios.

can you point me to an existing test that does this so i can implement its strategies into my test?

> Is this test meant to be reproducible across each platform?

it should be, but that will probably need to be done by someone else, as i am not a windows programmer

> Are macOS/various linux/Windows behavior different with respect to remove_dir_all?

windows already ignores ENOENT when removing files (but not directories?), no idea how it works on macos

> I think to test this reliably it'd require a much larger directory structure and with many more threads. Even then it may not be 100% reliable.

a larger directory structure *might* help, but i'm not sure how i would integrate more threads into this.  because `remove_dir_all` still returns an error if the top-level dir is missing, only one of the threads can actually check for errors, while the other thread only deletes files within the outer dir, not the outer dir itself.

personally, i think the best way to decrease the chance of false negatives would be to run the existing test more times with smaller increments to the `thread::sleep` call.  the reason i didn't do this already is because i didn't want the test to take too long, and because the existing test already did a good job of catching errors (i implemented the test before the fix, so i know it fails without it)

File: library/std/src/sys/pal/unix/fs.rs (hunk 1 above)
Comment (tbu-) [reply library/std/src/sys/pal/unix/fs.rs:2124]: > 1. inside the loop, we need to `continue` on ENOENT, not ignore it

As far as I can tell, this actually works with the function. It'd treat removal failed with `ENOENT` the same as successful deletion and continue into the next loop.

> 2\. there are lots of function calls, and almost all of them need to ignore ENOENT. if someone adds a new `unlinkat` call in the future, they will probably also need to wrap it, and if they don't, it will introduce a sneaky regression.

I actually feel the opposite way, it's better if we annotate all the places where we treat `ENOENT` as not an error rather than treating all possible `ENOENT` in this function as non-errors.

E.g. the recursive call does not need to ignore `ENOENT` as far as I can tell, but using try blocks will silence any errors that come from that.

File: library/std/src/sys/pal/unix/fs.rs [hunk 5]
```diff
@@ -2113,6 +2113,16 @@ mod remove_dir_impl {
         }
     }
 
+    fn is_enoent(result: &io::Result<()>) -> bool {
+        if let Err(err) = result
+            && matches!(err.raw_os_error(), Some(libc::ENOENT))
```
Comment (tbu-) [inline library/std/src/sys/pal/unix/fs.rs:2118]:
```suggestion
        if let Err(err) = result && err.raw_os_error() == Some(libc::ENOENT)
```

File: library/std/src/sys/pal/unix/fs.rs [hunk 6]
```diff
@@ -2128,36 +2138,57 @@ mod remove_dir_impl {
                     None => Err(err),
                 };
             }
+            Err(err) if matches!(err.raw_os_error(), Some(libc::ENOENT)) => {
```
Comment (tbu-) [inline library/std/src/sys/pal/unix/fs.rs:2141]:
```suggestion
            Err(err) if err.raw_os_error() == Some(libc::ENOENT) => {
```

File: tests/run-make/remove-dir-all-race/rmake.rs (hunk 4 above)
Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: > it would be good to take a quick look at the other remove_dir_all implementations in library/std/src/sys/pal and see if there are any obvious similar situations.

thanks for the pointer, luckily these implementations were pretty simple so i could fix them without knowing a ton about the individual platforms.

File: library/std/src/sys/pal/unix/fs.rs (hunk 1 above)
Comment (lolbinarycat) [reply library/std/src/sys/pal/unix/fs.rs:2124]: > E.g. the recursive call does not need to ignore ENOENT as far as I can tell, but using try blocks will silence any errors that come from that.

actually, maybe we should ignore the error in the recursive call, but not ignore any ENOENT errors outside of the for loop, as top-level ENOENT errors *should* be returned (currently this happens in `remove_dir_all_modern`).

**Comment by lolbinarycat** [comment]
note that the linked ACP proposes something that is different from what this PR implements, and thus the `S-waiting-on-ACP` label should be removed.  if that proposal is accepted, the code to ignore internal errors will still be needed.

[difference explained in this comment](https://github.com/rust-lang/libs-team/issues/410#issuecomment-2226385128)

File: tests/run-make/remove-dir-all-race/rmake.rs (hunk 4 above)
Comment (jieyouxu) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: > I _think_ @jieyouxu is suggesting that it may be better to have no test than a potentially flaky test? Because flaky tests can be hard to pin down and diagnose.

To be clear, I'm not *advocating* to have no tests, I'm just uneasy whenever I see a *potentially* flakey test that may *potentially* non-deterministically fail (whether in CI or locally). I'm not going to block this PR on this (I'm not a T-libs reviewer anyway) especially since I don't know of a better alternative way to deterministic test this.

File: library/std/src/sys_common/fs.rs [hunk 7]
```diff
@@ -32,11 +32,19 @@ pub fn remove_dir_all(path: &Path) -> io::Result<()> {
...
+            }
+        };
+        // ignore internal NotFound errors to prevent race conditions
+        if let Err(err) = &result
+            && err.kind() != io::ErrorKind::NotFound
+        {
+            return result;
         }
     }
     fs::remove_dir(path)
```
Comment (Amanieu) [inline library/std/src/sys_common/fs.rs:50]: We should also ignore `NotFound` errors when deleting the directory after recursing through. Basically, the idea is that we only report `NotFound` if the specified directory didn't exist at the start of the call to `remove_dir_all`, and otherwise report a successful deletion even if someone else raced us to it.

File: tests/run-make/remove-dir-all-race/rmake.rs (hunk 4 above)
Comment (Amanieu) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: I'm also somewhat uncomfortable with this test. I would prefer if the test didn't fail if it couldn't manage to cause a race.

File: library/std/src/sys_common/fs.rs (hunk 7 above)
Comment (lolbinarycat) [reply library/std/src/sys_common/fs.rs:50]: hmm, this initially seems like a good idea, but there's actually a lot of subtle issues i have:
1. the point of this PR is to trivialize implementing an idiomatic version of remove_dir_all  
2. ignoring this error may cause some race conditions to be more hidden, before two racing `remove_dir_all` would always cause one of them to give NotFound, but this tweak would cause such an error to occur only sometimes
3. this adds complexity to code that is duplicated 5 different times for various platforms, sometimes with the code subjected to complex conditional compilation, such as on macos, where the usual comptime check is actually deferred to runtime.

File: tests/run-make/remove-dir-all-race/rmake.rs (hunk 4 above)
Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: @Amanieu is there another status a run-make test can have other than pass or fail? i would like to alert people if the test breaks.

Comment (Amanieu) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: Not that I know of. Either the test passes or it fails and blocks CI.

File: library/std/src/sys_common/fs.rs (hunk 7 above)
Comment (Amanieu) [reply library/std/src/sys_common/fs.rs:50]: I'm revisiting this after thinking about it a bit, and I still think we should ignore `NotFound` errors on the final removal.

My main argument is that we shouldn't return a `NotFound` error if we actually performed any deletions within the directory, since that means that the directory clearly was found. I would expect no deletions to have been done if a `NotFound` error is returned.

Comment (lolbinarycat) [reply library/std/src/sys_common/fs.rs:50]: yeah, it sounds like that's the consensus of t-libs on the ACP, and i hadn't considered the ambiguity of the error that would create.

i'll get working on it this morning.

File: tests/run-make/remove-dir-all-race/rmake.rs
Comment (jieyouxu) [inline tests/run-make/remove-dir-all-race/rmake.rs:1]: Question: so I recently ran into some Windows symlink funny business in another run-make test. Do we want any behavior check in relation to symlinks -- like soft links, hard links or junction points, etc.? Does that matter for `remove_dir_all`?

File: tests/run-make/remove-dir-all-race/rmake.rs (hunk 4 above)
Comment (jieyouxu) [reply tests/run-make/remove-dir-all-race/rmake.rs]: > I'm also somewhat uncomfortable with this test. I would prefer if the test didn't fail if it couldn't manage to cause a race.

+1 to this. If this test absolutely *has* to be flaky and non-deterministic and has no other choice, then I would prefer it at least not fail if we couldn't manage to cause a race, because otherwise it can randomly block *every* PR on PR CI or full CI. It's still not ideal because then if this regresses, a PR-local try-job might pass, and so might its full CI test run, but then start failing in completely unrelated PRs.

> Is there another status a run-make test can have other than pass or fail? i would like to alert people if the test breaks.

This would require some significant infra support, maybe even moving to a new test suite called `run-make-no-block` that doesn't block full CI but is run in a separate CI job (something like a tool state check job?)... but then the feedback loop can be quite long.

File: tests/run-make/remove-dir-all-race/rmake.rs
Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: `remove_dir_all` should remove symlinks, not the files or directories they point to, anything else is a potential vulnerability (eg. creating a symlink to an important file in a world-writable directory like /tmp, then waiting for a privalaged process (like a tempdir cleaner) to delete the file it points to)

hardlinks should be handled correctly by default, deleting them simply decrements the hardlink count of their inode.

File: tests/run-make/remove-dir-all-race/rmake.rs [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+            };
+            assert_eq!(err.kind(), std::io::ErrorKind::NotFound);
+        }
+    });
+    assert!(
+        race_happened,
+        "multithreaded deletion never raced, \
+         try increasing the number of attempts or \
+         adjusting the sleep timing"
+    );
```
Comment (Amanieu) [inline tests/run-make/remove-dir-all-race/rmake.rs:48]: The implementation LGTM, I just think we should remove this last assert. I would rather have this test silently do nothing if it couldn't trigger a race than failing.

Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:48]: I'll just downgrade it to a warning, although it'll probably be hidden unless someone runs the test suite in its least verbose mode.

**Comment by tgross35** [comment]
@lolbinarycat can you squash? This has 14 commits with a lot of back and forth.
@bors r- since this is about to be picked up

**Comment by tgross35** [comment]
Thanks.

@bors r=Amanieu

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/129254#issuecomment-2295414459
https://github.com/rust-lang-ci/rust/actions/runs/10443963448/job/28917967814#step:25:3430

**Comment by jieyouxu** [comment]
Failed in https://github.com/rust-lang/rust/pull/129304#issuecomment-2299486846

```
command: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-make\\remove-dir-all-race\\rmake.exe"
--- stderr -------------------------------
thread '<unnamed>' panicked at C:\a\rust\rust\tests\run-make\remove-dir-all-race\rmake.rs:20:45:
called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not sure if it's due to *this* PR or if it's due to some compiletest/bootstrap `remove_dir_all` issues.

**Comment by ChrisDenton** [comment]
> Not sure if it's due to this PR or if it's due to some compiletest/bootstrap remove_dir_all issues.

This is likely to be a pre-existing issue. It was designed to be *safe* against concurrent access but it's not necessarily fully *robust*. I can look into but I'd suggest marking the test as ignore windows for now and merging because I suspect the fix will be non-trivial.

File: tests/run-make/remove-dir-all-race/rmake.rs [hunk 9]
```diff
@@ -0,0 +1,52 @@
+//@ ignore-windows
```
Comment (jieyouxu) [inline tests/run-make/remove-dir-all-race/rmake.rs:1]: Suggestions:

1. Could we leave a brief overview of what this test is trying check? Namely, this test is not *guaranteed* to fail even if the underlying impl regresses (that's okay, but we should document it). Even better *why* the check is done this way.
2. We should remark why this is ignore-windows.

Comment (lolbinarycat) [reply tests/run-make/remove-dir-all-race/rmake.rs:1]: yeah, that's a good idea, a lot of tests are lacking documentation and are hard to understand because of it.
