### PR TITLE
Use `eq_opaque_type_and_type` when type-checking closure signatures

### LINKED ISSUE #63263: ICE with closure return type as impl trait type alias defining use
In an attempt to make the compiler recognize my defining use of an impl trait type alias without making a separate wrapper function, I ran this code, but it resulted in an ICE:

```rust
#![feature(type_alias_impl_trait)]

pub type Closure = impl FnOnce();

fn main() {
    || -> Closure { || () };
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dac650bec742a37714a53eb76fb61889)

Compiler Output:

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: broken MIR in DefId(0:14 ~ playground[1d12]::main[0]::{{closure}}[0]) (bb0[0]): equate_normalized_input_or_output: `Closure==[closure@src/main.rs:6:21: 6:26]` failed with `NoSolution`
 --> src/main.rs:6:28
  |
6 |     || -> Closure { || () };
  |                            ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:361:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: <rustc_errors::Handler as core::ops::drop::Drop>::drop
  10: core::ptr::real_drop_in_place
  11: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  12: core::ptr::real_drop_in_place
  13: rustc_interface::interface::run_compiler_in_existing_thread_pool
  14: std::thread::local::LocalKey<T>::with
  15: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (d3f8a0b5d 2019-08-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by Aaron1011**
This handles the case where a user explicitly annotations a closure
signature with a opaque return type.

Fixes #63263

### CODE REVIEW

File: src/test/ui/type-alias-impl-trait/issue-63263-closure-return.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// Regression test for issue #63263.
+// Tests that we properly handle closures with an explicit return type
+// that return an opaque type.
+
+// run-pass
```
Comment (Centril) [inline src/test/ui/type-alias-impl-trait/issue-63263-closure-return.rs]:
```suggestion
// check-pass
```

**Comment by JohnCSimon** [comment]
Ping from triage:
@pnkfelix can you please review this PR?
@petrochenkov @Centril @Aaron1011

**Comment by JohnCSimon** [comment]
Pinging again from triage:
@pnkfelix can you please review this PR?
Thanks
