### PR TITLE
Fix off-by-one error causing slice::sort to abort the program

### LINKED ISSUE #136103: Sorting a Slice Raises an Illegal Instruction Signal
As the issue title indicates, I have discovered that, in some cases, sorting a slice via `slice::sort` erroneously raises SIGILL (illegal instruction). Below is a minimal test case for the observed behavior.

```rust
use std::fmt;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct S(bool, [u8; 999_999]);

impl fmt::Debug for S {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.0, f)
    }
}

fn main() {
    let n = 101;
    let mut objs = Vec::with_capacity(n);

    let mut on = false;

    for _ in 0..n {
        objs.push(S(on, [0; 999_999]));
        on = !on;
    }

    println!("Done adding elements.");
    println!("Objects: {:?}", objs);

    objs.sort();

    println!("Objects: {:?}", objs);
}
```

If you run this code in a debugger, you will see that the SIGILL comes from the call to `core::intrinsics::abort` [here](https://github.com/rust-lang/rust/blob/f7cc13af822fe68c64fec0b05aa9dd1412451f7c/library/core/src/slice/sort/stable/quicksort.rs#L98). That is, something is causing `scratch.len()` to be less than `len` when it shouldn't be.

I think I have traced the cause of the problem to how `min_good_run_len` is calculated [here](https://github.com/rust-lang/rust/blob/f7cc13af822fe68c64fec0b05aa9dd1412451f7c/library/core/src/slice/sort/stable/drift.rs#L37). If `len <= MIN_SQRT_RUN_LEN * MIN_SQRT_RUN_LEN` holds true and `len - len / 2` (which is really just `ceil(len / 2)`) happens to be `<= MIN_SQRT_RUN_LEN`, then `min_good_run_len` is given the value `len - len / 2` (which, again, is just `ceil(len / 2)`). When the function `create_run` in the same file cannot find an ascending or descending run of at least `min_good_run_len` elements, it extracts an unsorted run that extends for `min_good_run_len` elements or until the end of the slice/array (whichever is earlier). Later, the function `logical_merge` in the same file will sort an unsorted run if it and the run with which it is to be merged do not together fit in `scratch`.

`scratch.len()` is at least `floor(len / 2)`, and `floor(len / 2)` is less than `ceil(len / 2)` when `len` is an odd integer, so a problem arises when `scratch.len()` is equal to `floor(len / 2)`, `min_good_run_len` is equal to `ceil(len / 2)`, and `len` is odd, because, then, `logical_merge` might try to sort an unsorted run that cannot fit in `scratch`. If my math is correct, this is exactly the situation occurring in my minimal test case.

Replacing `len - len / 2` with `len / 2` in the calculation of `min_good_run_len` would therefore fix the issue, if I am not mistaken. I do not know why the author(s) of the driftsort chose `len - len / 2` instead of `len / 2`. Neither the commit (in the original driftsort GitHub repository) where it first appeared (https://github.com/Voultapher/driftsort/commit/dbe1d246d9d35f4bafdbb2cbefb8d63e18fb7b52) nor the associated pull request (https://github.com/Voultapher/driftsort/pull/39) appears to give an explanation.

### Meta
`rustc --version --verbose`:
```
rustc 1.86.0-nightly (f7cc13af8 2025-01-25)
binary: rustc
commit-hash: f7cc13af822fe68c64fec0b05aa9dd1412451f7c
commit-date: 2025-01-25
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by uellenberg**
Fixes #136103.
Based on the analysis by @jonathan-gruber-jg and @orlp.

### CODE REVIEW

File: library/core/src/slice/sort/stable/mod.rs
Comment (uellenberg) [inline library/core/src/slice/sort/stable/mod.rs:1]: I'm not sure how to make GitHub put this comment on the specific line, but we have:
```rust
    cfg_if! {
        if #[cfg(any(feature = "optimize_for_size", target_pointer_width = "16"))] {
            let alloc_len = len / 2;
            cfg_if! {
                if #[cfg(target_pointer_width = "16")] {
                    let mut heap_buf = BufT::with_capacity(alloc_len);
                    let scratch = heap_buf.as_uninit_slice_mut();
                } else {
                    // For small inputs 4KiB of stack storage suffices, which allows us to avoid
                    // calling the (de-)allocator. Benchmarks showed this was quite beneficial.
                    let mut stack_buf = AlignedStorage::<T, 4096>::new();
                    let stack_scratch = stack_buf.as_uninit_slice_mut();
                    let mut heap_buf;
                    let scratch = if stack_scratch.len() >= alloc_len {
                        stack_scratch
                    } else {
                        heap_buf = BufT::with_capacity(alloc_len);
                        heap_buf.as_uninit_slice_mut()
                    };
                }
            }
            tiny::mergesort(v, scratch, is_less);
```

Should this be updated as well? As far as I can tell, tiny::mergesort is fine with the length, but I'm not sure.

Comment (uellenberg) [reply library/core/src/slice/sort/stable/mod.rs:1]: The scratch usage requires that `scratch.len() >= cmp::min(mid, len - mid)`, and `mid` is computed as `v.len() / 2`, so the largest mid is `len / 2`.

We require `len / 2 >= min(len / 2, len - len / 2)`, which reduces to `len / 2 >= len / 2` (because `len / 2` is always <= `len - len / 2`), so it should be fine. It may be worth a comment though, since having this inconsistency may lead to bugs like this being reintroduced.

**Comment by workingjubilee** [comment]
r? libs

**Comment by orlp** [comment]
Looks good to me, @Voultapher any thoughts?

File: library/core/src/slice/sort/stable/mod.rs [hunk 1]
```diff
@@ -91,16 +91,18 @@ fn driftsort_main<T, F: FnMut(&T, &T) -> bool, BufT: BufGuard<T>>(v: &mut [T], i
...
     // random and low-cardinality distributions. However, we still want to
-    // reduce our memory usage to n / 2 for large inputs. We do this by scaling
-    // our allocation as max(n / 2, min(n, 8MB)), ensuring we scale like n for
-    // small inputs and n / 2 for large inputs, without a sudden drop off. We
+    // reduce our memory usage to n - n / 2 for large inputs. We do this by scaling
+    // our allocation as max(n - n / 2, min(n, 8MB)), ensuring we scale like n for
+    // small inputs and n - n / 2 for large inputs, without a sudden drop off. We
     // also need to ensure our alloc >= MIN_SMALL_SORT_SCRATCH_LEN, as the
     // small-sort always needs this much memory.
     const MAX_FULL_ALLOC_BYTES: usize = 8_000_000; // 8MB
```
Comment (Voultapher) [inline library/core/src/slice/sort/stable/mod.rs:99]: I would mention the connection to `min_good_run_len`.

File: tests/ui/array-slice-vec/driftsort-off-by-one-issue-136103.rs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+}
+
+impl PartialEq for S {
+    #[inline]
+    fn eq(&self, other: &S) -> bool {
+        self.0 == other.0
+    }
+}
+
+fn main() {
```
Comment (Voultapher) [inline tests/ui/array-slice-vec/driftsort-off-by-one-issue-136103.rs:35]: This is test case can easily run into stack overflows, 1MB values are just asking for trouble, in my testing such values blow up `into_iter` and easily `slice::sort`, 2MB values can't even be used with `Vec::push` - particularly so in debug builds - in combination with being needlessly noisy - the `Ord` impls only distract - I suggest using the minimal reproducer @orlp shared.

**Review by Voultapher — CHANGES_REQUESTED** [review]

**Comment by Voultapher** [comment]
I'm suggesting minor changes, the fix itself looks good.

**Comment by uellenberg** [comment]
Some of the comments mention `MIN_SMALL_SORT_SCRATCH_LEN` but I don't see that actually defined anywhere, nor used in any code. Was this renamed at some point, or am I missing something?

File: library/core/src/slice/sort/stable/mod.rs (hunk 1 above)
Comment (uellenberg) [reply library/core/src/slice/sort/stable/mod.rs:109]: @Voultapher Does this look good?

```rust
    // driftsort will produce unsorted runs of up to min_good_run_len, which
    // is at most len - len / 2.
    // Unsorted runs need to be processed by quicksort, which requires as much
    // scratch space as the run length, therefore the scratch space must be at
    // least len - len / 2.
    // If min_good_run_len is ever modified, this code must be updated to allocate
    // the correct scratch size for it.
 ```

Comment (Voultapher) [reply library/core/src/slice/sort/stable/mod.rs:109]: Looks good, thanks.

**Review by Voultapher — APPROVED** [review]
LGTM, thanks for the fix @uellenberg

**Comment by Voultapher** [comment]
> Some of the comments mention MIN_SMALL_SORT_SCRATCH_LEN but I don't see that actually defined anywhere, nor used in any code. Was this renamed at some point, or am I missing something?

In the original driftsort repository this constant was defined as `pub const MIN_SMALL_SORT_SCRATCH_LEN: usize = i32::SMALL_SORT_THRESHOLD + 16;`, while merging the driftsort and ipnsort code bases it was renamed to `SMALL_SORT_GENERAL_SCRATCH_LEN`. I think this kind of coment fixup doesn't need a separate PR, so feel free to do it here.

File: library/core/src/slice/sort/stable/mod.rs
Comment (uellenberg) [reply library/core/src/slice/sort/stable/mod.rs:1]: I added a comment.

**Comment by Voultapher** [comment]
Could we maybe change the PR title, crash usually suggests UB, here we are just running into assert style function preconditions, in this case not using panics and instead abort to save on binary-size.
