### PR TITLE
Handle closures correctly in MIR inlining

### LINKED ISSUE #45894: [MIR-opt] MIR inlining handles closures incorrectly
```
$ rustc -V
rustc 1.23.0-nightly (90ef3372e 2017-10-29)
$ rustc klosure.rs
$ ./klosure 
28
$ rustc klosure.rs -Z mir-opt-level=2
Function return type does not match operand type of return inst!
  ret { i32, [0 x i8], i32, [0 x i8] } %15
 i32LLVM ERROR: Broken function found, compilation aborted!
```

Code:

```Rust
fn main() {
    println!("{}", foo(0, 14));
}

fn foo<T: Copy>(_t: T, q: i32) -> i32 {
    let x = |_t, _q| _t;
    x(q*2, q*3)
}
```

Expected result: no LLVM assert, should work.

### PR DESCRIPTION
**Pull request by sinkuu**
Fixes #45894.

### CODE REVIEW

**Comment by shepmaster** [comment]
Auto-assigning to...

r? @nikomatsakis

File: src/librustc_mir/transform/inline.rs [hunk 1]
```diff
@@ -546,22 +547,31 @@ impl<'a, 'tcx> Inliner<'a, 'tcx> {
...
+        args: Vec<Operand<'tcx>>,
+        callsite: &CallSite<'tcx>,
+        caller_mir: &mut Mir<'tcx>,
+    ) -> Vec<Operand<'tcx>> {
         // FIXME: Analysis of the usage of the arguments to avoid
         // unnecessary temporaries.
-        args.into_iter().map(|a| {
-            if let Operand::Consume(Lvalue::Local(local)) = a {
+
+        fn create_temp_if_necessary<'a, 'tcx: 'a>(
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/inline.rs]: Nit: Could we move this to a method (and then get rid of the `tcx` argument)? (I just find it harder to read things "nested" funtions, that's all.)

File: src/librustc_mir/transform/inline.rs [hunk 2]
```diff
@@ -571,11 +581,47 @@ impl<'a, 'tcx> Inliner<'a, 'tcx> {
...
             caller_mir[callsite.bb].statements.push(stmt);
             Operand::Consume(arg_tmp)
-        }).collect()
+        }
+
+        let tcx = self.tcx;
+
+        // A closure is passed its self-type and a tuple like `(arg1, arg2, ...)`,
+        // hence mappings to tuple fields are needed.
+        if tcx.def_key(callsite.callee).disambiguated_data.data == DefPathData::ClosureExpr {
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/inline.rs]: Nit: let's do `if let DefPathData::ClosureExpr = tcx.def_key(callsite.callee).disambiguated_data.data`

Comment (nikomatsakis) [reply src/librustc_mir/transform/inline.rs]: better yet, let's add a `is_closure(def_id: DefId)` helper to the tcx (and call it from `closure_base_def_id`)

File: src/librustc_mir/transform/inline.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/transform/inline.rs]: Also, good opportunity to add a comment (the surrounding code is a bit...comment-poor). Perhaps something like:

```
/// If `arg` is already a temporary, returns it. Otherwise, introduces a fresh
/// temporary `T` and an instruction `T = arg`, and returns `T`.
```

(Does that sound accurate?)

Comment (nikomatsakis) [reply src/librustc_mir/transform/inline.rs]: Finally, can we change the return value to `Lvalue`, to reflect the fact that this *always* returns an `Operand::Consume`?

File: src/librustc_mir/transform/inline.rs [hunk 3]
```diff
@@ -571,11 +581,47 @@ impl<'a, 'tcx> Inliner<'a, 'tcx> {
...
+            let mut args = args.into_iter();
+
+            let self_ = create_temp_if_necessary(args.next().unwrap(), tcx, callsite, caller_mir);
+
+            let tuple = if let Operand::Consume(lvalue) =
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/inline.rs]: (if we changed return type, this `if let` would not be necessary)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks great! I left a few style nits.

File: src/librustc_mir/transform/check_unsafety.rs [hunk 4]
```diff
@@ -361,11 +361,11 @@ fn unsafety_violations<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>, def_id: DefId) ->
...
-    match tcx.def_key(def_id).disambiguated_data.data {
-        // closures are handled by their parent fn.
-        DefPathData::ClosureExpr => return,
-        _ => {}
-    };
+
+    // closures are handled by their parent fn.
+    if tcx.is_closure(def_id) {
+        return;
+    }
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/check_unsafety.rs]: nice drive-by cleanup =)

**Review by nikomatsakis — APPROVED** [review]

**Comment by sinkuu** [comment]
Rebased.

File: src/test/mir-opt/inline-closure.rs [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+// bb0: {
+//     StorageLive(_3);
+//     _3 = [closure@NodeId(28)];
+//     StorageLive(_4);
+//     _4 = &_3;
+//     StorageLive(_5);
+//     StorageLive(_6);
+//     StorageLive(_7);
+//     _7 = _2;
+//     _6 = Mul(_7, const 2i32);
```
Comment (kennytm) [inline src/test/mir-opt/inline-closure.rs]: Checked arithmetic strikes again! These are `CheckedMul` in debug build. Please change to a non-checked operator like `&` or maybe just write `x(q, q)`.

<details>

```
[01:06:23] ---- [mir-opt] mir-opt/inline-closure.rs stdout ----
[01:06:23] 	thread '[mir-opt] mir-opt/inline-closure.rs' panicked at 'Did not find expected line, error: Mismatch in lines
[01:06:23] Currnt block: None
[01:06:23] Expected Line: "        _8 = CheckedMul(_7, const 2i32); // scope 1 at /checkout/src/test/mir-opt/inline-closure.rs:21:7: 21:10"
[01:06:23] Actual Line: "    _6 = Mul(_7, const 2i32);"
[01:06:23] Expected:
[01:06:23] ... (elided)
[01:06:23] ... (elided)
[01:06:23] bb0: {
[01:06:23]     StorageLive(_3);
[01:06:23]     _3 = [closure@NodeId(28)];
[01:06:23]     StorageLive(_4);
[01:06:23]     _4 = &_3;
[01:06:23]     StorageLive(_5);
[01:06:23]     StorageLive(_6);
[01:06:23]     StorageLive(_7);
[01:06:23]     _7 = _2;
[01:06:23]     _6 = Mul(_7, const 2i32);
[01:06:23]     StorageDead(_7);
[01:06:23]     StorageLive(_8);
[01:06:23]     StorageLive(_9);
[01:06:23]     _9 = _2;
[01:06:23]     _8 = Mul(_9, const 3i32);
[01:06:23]     StorageDead(_9);
[01:06:23]     _5 = (_6, _8);
[01:06:23]     _0 = (_5.0: i32);
[01:06:23]     StorageDead(_5);
[01:06:23]     StorageDead(_8);
[01:06:23]     StorageDead(_6);
[01:06:23]     StorageDead(_4);
[01:06:23]     StorageDead(_3);
[01:06:23]     return;
[01:06:23] }
[01:06:23] ... (elided)
[01:06:23] Actual:
[01:06:23] fn foo(_1: T, _2: i32) -> i32 {
[01:06:23]     let mut _0: i32;
[01:06:23]     scope 1 {
[01:06:23]         let _3: [closure@NodeId(28)];
[01:06:23]         scope 3 {
[01:06:23]         }
[01:06:23]     }
[01:06:23]     scope 2 {
[01:06:23]     }
[01:06:23]     let mut _4: &[closure@NodeId(28)];
[01:06:23]     let mut _5: (i32, i32);
[01:06:23]     let mut _6: i32;
[01:06:23]     let mut _7: i32;
[01:06:23]     let mut _8: (i32, bool);
[01:06:23]     let mut _9: i32;
[01:06:23]     let mut _10: i32;
[01:06:23]     let mut _11: (i32, bool);
[01:06:23]     bb0: {                              
[01:06:23]         StorageLive(_3);
[01:06:23]         _3 = [closure@NodeId(28)];
[01:06:23]         StorageLive(_4);
[01:06:23]         _4 = &_3;
[01:06:23]         StorageLive(_5);
[01:06:23]         StorageLive(_6);
[01:06:23]         StorageLive(_7);
[01:06:23]         _7 = _2;
[01:06:23]         _8 = CheckedMul(_7, const 2i32);
[01:06:23]         assert(!(_8.1: bool), "attempt to multiply with overflow") -> bb1;
[01:06:23]     }
[01:06:23]     bb1: {                              
[01:06:23]         _6 = (_8.0: i32);
[01:06:23]         StorageDead(_7);
[01:06:23]         StorageLive(_9);
[01:06:23]         StorageLive(_10);
[01:06:23]         _10 = _2;
[01:06:23]         _11 = CheckedMul(_10, const 3i32);
[01:06:23]         assert(!(_11.1: bool), "attempt to multiply with overflow") -> bb2;
[01:06:23]     }
[01:06:23]     bb2: {                              
[01:06:23]         _9 = (_11.0: i32);
[01:06:23]         StorageDead(_10);
[01:06:23]         _5 = (_6, _9);
[01:06:23]         _0 = (_5.0: i32);
[01:06:23]         StorageDead(_5);
[01:06:23]         StorageDead(_9);
[01:06:23]         StorageDead(_6);
[01:06:23]         StorageDead(_4);
[01:06:23]         StorageDead(_3);
[01:06:23]         return;
[01:06:23]     }
[01:06:23] }', /checkout/src/tools/compiletest/src/runtest.rs:2337:12
[01:06:23] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:23] 
[01:06:23] 
[01:06:23] failures:
[01:06:23]     [mir-opt] mir-opt/inline-closure.rs
[01:06:23] 
[01:06:23] test result: [31mFAILED(B[m. 44 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

</details>
