### PR TITLE
Fix passing/returning structs with the 64-bit SPARC ABI

### LINKED ISSUE #115336: `extern "C" fn` on sparc64 targets does not respect repr(transparent)
I tried the following code:
```rust
#![feature(rustc_attrs)]

#[rustc_abi(debug)]
extern "C" fn test1(_x: [u8; 0]) {}

#[repr(transparent)]
struct Wrap<T>(T);

#[rustc_abi(debug)]
extern "C" fn test2(_x: Wrap<[u8; 0]>) {}
```
When running this with `--target sparc64-unknown-linux-gnu` (using Miri), the first function reports an argument pass mode of
```
                   mode: Indirect {
                       attrs: ArgAttributes {
                           regular: NoAlias | NoCapture | NonNull | NoUndef,
                           arg_ext: None,
                           pointee_size: Size(0 bytes),
                           pointee_align: Some(
                               Align(1 bytes),
                           ),
                       },
                       extra_attrs: None,
                       on_stack: false,
                   },
```
but the 2nd function reports
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Integer,
                                   size: Size(8 bytes),
                               },
                               total: Size(0 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```
I'm not an expert in interpreting PassMode, but `Indirect` and `Cast` are not compatible, are they?

Cc @bjorn3 @eddyb @psumbera

### LINKED ISSUE #122620: sparc64 has incorrect ABI for struct containing f64 and f32
**I tried this code**:

```rust
// with --target=sparc64-unknown-linux-gnu

#[repr(C)]
pub struct DoubleFloat {
    f: f64,
    g: f32,
}

#[no_mangle]
pub extern "C" fn foo(x: DoubleFloat) {}
```

**I expected to see this happen**: Compiles successfully

**Instead, this happened**:

Before #122619, this crashes the compiler (https://godbolt.org/z/bKn6d5jeM):

```
thread 'rustc' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/compiler/rustc_abi/src/lib.rs:565:13:
Size::sub: 0 - 8 would result in negative size
```

(see backtrace below).

After #122619, this will compile, but it will use a bizarre ABI that's probably wrong:

```ll
declare void @receives_doublefloat({ double, float, i32, i64 } inreg)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

(also reproducible on very recent master https://github.com/rust-lang/rust/commit/766bdce744d531267d53ba2a3f9ffcda69fb9b17)

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/compiler/rustc_abi/src/lib.rs:565:13:
Size::sub: 0 - 8 would result in negative size
stack backtrace:
   0:     0x7f8961a1a6f6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f8961a1a6f6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8961a1a6f6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f8961a1a6f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8961a6cf40 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7f8961a6cf40 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f8961a0e53f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7f8961a1a4d4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f8961a1a4d4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8961a1d267 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x7f8961a1cfc9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7f895ea1461c - std[79729d9c385e1623]::panicking::update_hook::<alloc[6df67106ebca92c0]::boxed::Box<rustc_driver_impl[66ed8fdbde15dc6c]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8961a1d9b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x7f8961a1d9b6 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x7f8961a1d702 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  15:     0x7f8961a1abf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f8961a1d460 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x7f8961a69645 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x7f895f544152 - rustc_target[edc8d30e58965941]::abi::call::sparc64::arg_scalar::<rustc_middle[e0f609162babcb92]::ty::layout::LayoutCx<rustc_middle[e0f609162babcb92]::ty::context::TyCtxt>>
  19:     0x7f895f54460d - rustc_target[edc8d30e58965941]::abi::call::sparc64::arg_scalar_pair::<rustc_middle[e0f609162babcb92]::ty::layout::LayoutCx<rustc_middle[e0f609162babcb92]::ty::context::TyCtxt>>
  20:     0x7f895f54486b - rustc_target[edc8d30e58965941]::abi::call::sparc64::parse_structure::<rustc_middle[e0f609162babcb92]::ty::Ty, rustc_middle[e0f609162babcb92]::ty::layout::LayoutCx<rustc_middle[e0f609162babcb92]::ty::context::TyCtxt>>
  21:     0x7f895f5442a2 - rustc_target[edc8d30e58965941]::abi::call::sparc64::classify_arg::<rustc_middle[e0f609162babcb92]::ty::Ty, rustc_middle[e0f609162babcb92]::ty::layout::LayoutCx<rustc_middle[e0f609162babcb92]::ty::context::TyCtxt>>
  22:     0x7f895f544a33 - rustc_target[edc8d30e58965941]::abi::call::sparc64::compute_abi_info::<rustc_middle[e0f609162babcb92]::ty::Ty, rustc_middle[e0f609162babcb92]::ty::layout::LayoutCx<rustc_middle[e0f609162babcb92]::ty::context::TyCtxt>>
  23:     0x7f89607772dc - rustc_ty_utils[112fed09b8de77ee]::abi::fn_abi_new_uncached
  24:     0x7f896018f406 - rustc_ty_utils[112fed09b8de77ee]::abi::fn_abi_of_instance
  25:     0x7f896018ddb3 - rustc_query_impl[aa9389cf74aaab3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[aa9389cf74aaab3]::query_impl::fn_abi_of_instance::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e0f609162babcb92]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7f8960102553 - rustc_query_system[84cc5057ded7d916]::query::plumbing::try_execute_query::<rustc_query_impl[aa9389cf74aaab3]::DynamicConfig<rustc_query_system[84cc5057ded7d916]::query::caches::DefaultCache<rustc_middle[e0f609162babcb92]::ty::ParamEnvAnd<(rustc_middle[e0f609162babcb92]::ty::instance::Instance, &rustc_middle[e0f609162babcb92]::ty::list::List<rustc_middle[e0f609162babcb92]::ty::Ty>)>, rustc_middle[e0f609162babcb92]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[aa9389cf74aaab3]::plumbing::QueryCtxt, false>
  27:     0x7f89601021ef - rustc_query_impl[aa9389cf74aaab3]::query_impl::fn_abi_of_instance::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f895d402af9 - <rustc_codegen_llvm[3c1678ba3e8e7d64]::context::CodegenCx as rustc_codegen_ssa[8f0ba34f7d763469]::traits::declare::PreDefineMethods>::predefine_fn
  29:     0x7f89607214a8 - rustc_codegen_llvm[3c1678ba3e8e7d64]::base::compile_codegen_unit::module_codegen
  30:     0x7f8960942a86 - <rustc_codegen_llvm[3c1678ba3e8e7d64]::LlvmCodegenBackend as rustc_codegen_ssa[8f0ba34f7d763469]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  31:     0x7f8960595746 - <rustc_codegen_llvm[3c1678ba3e8e7d64]::LlvmCodegenBackend as rustc_codegen_ssa[8f0ba34f7d763469]::traits::backend::CodegenBackend>::codegen_crate
  32:     0x7f896059331f - rustc_interface[bf5cafa581ab7832]::passes::start_codegen
  33:     0x7f8960592b22 - <rustc_interface[bf5cafa581ab7832]::queries::Queries>::codegen_and_build_linker
  34:     0x7f89608fe7a0 - rustc_interface[bf5cafa581ab7832]::interface::run_compiler::<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}
  35:     0x7f8960a2c7db - std[79729d9c385e1623]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>
  36:     0x7f8960a2c639 - <<std[79729d9c385e1623]::thread::Builder>::spawn_unchecked_<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#1} as core[f975038e3cc9791c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f8961a278e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  38:     0x7f8961a278e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  39:     0x7f8961a278e5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f895ba94ac3 - <unknown>
  41:     0x7f895bb26850 - <unknown>
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0 (07dca489a 2024-02-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=1 -C llvm-args=--x86-asm-syntax=intel --crate-type rlib -C opt-level=3 -C debuginfo=0 -C no-prepopulate-passes

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `foo`
end of query stack
```

</p>
</details>

### LINKED ISSUE #147883: "Size::sub: 0 - 8 would result in negative size" ICE on sparc
### Code

```Rust
#[repr(C)]
pub struct C {
    a: f64,
    b: f32
}

#[unsafe(no_mangle)]
pub extern "C" fn foo(c: C) {}
```

compiled for `sparc64-unknown-linux-gnu`

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (53a741fc4 2025-10-16)
binary: rustc
commit-hash: 53a741fc4b8cf2d8e7b1b2336ed8edf889db84f4
commit-date: 2025-10-16
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.3
```

### Error output

```
thread 'rustc' (3) panicked at /rustc-dev/53a741fc4b8cf2d8e7b1b2336ed8edf889db84f4/compiler/rustc_abi/src/lib.rs:884:13:
Size::sub: 0 - 8 would result in negative size
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' (3) panicked at /rustc-dev/53a741fc4b8cf2d8e7b1b2336ed8edf889db84f4/compiler/rustc_abi/src/lib.rs:884:13:
Size::sub: 0 - 8 would result in negative size
stack backtrace:
   0:     0x7904d7866263 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hdfccfc3d07cf8ba1
   1:     0x7904d8001c18 - core::fmt::write::h77f0ee94152958b8
   2:     0x7904d781a603 - std::io::Write::write_fmt::hf6dd3f11ce87ebfd
   3:     0x7904d782b922 - std::sys::backtrace::BacktraceLock::print::hf0ee2015b068d272
   4:     0x7904d78319f9 - std::panicking::default_hook::{{closure}}::hf66190d472a04973
   5:     0x7904d7831523 - std::panicking::default_hook::h214c836e53748476
   6:     0x7904d68368e7 - std[d75eede35f95485e]::panicking::update_hook::<alloc[c5f1165681da87d5]::boxed::Box<rustc_driver_impl[483de4215d5a0d3a]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7904d7831e1f - std::panicking::panic_with_hook::ha35d30be6548755c
   8:     0x7904d7831bda - std::panicking::panic_handler::{{closure}}::hf26b182862a4d512
   9:     0x7904d782ba59 - std::sys::backtrace::__rust_end_short_backtrace::hca5b955de0500289
  10:     0x7904d780c81d - __rustc[cd85992985178f8b]::rust_begin_unwind
  11:     0x7904d47f74e0 - core::panicking::panic_fmt::h39cc62a8520496e4
  12:     0x7904d77a43f7 - <rustc_abi[90d1dadb8d98cb9e]::Size as core[e9d4aeab7aaf03ba]::ops::arith::Sub>::sub::{closure#0}
  13:     0x7904d77873bb - rustc_target[aea0b2dab06d98f7]::callconv::sparc64::arg_scalar::<rustc_middle[dd66a2b5e7436936]::ty::layout::LayoutCx>
  14:     0x7904d7787966 - rustc_target[aea0b2dab06d98f7]::callconv::sparc64::parse_structure::<rustc_middle[dd66a2b5e7436936]::ty::Ty, rustc_middle[dd66a2b5e7436936]::ty::layout::LayoutCx>
  15:     0x7904d7787504 - rustc_target[aea0b2dab06d98f7]::callconv::sparc64::classify_arg::<rustc_middle[dd66a2b5e7436936]::ty::Ty, rustc_middle[dd66a2b5e7436936]::ty::layout::LayoutCx>
  16:     0x7904d7787ae8 - rustc_target[aea0b2dab06d98f7]::callconv::sparc64::compute_abi_info::<rustc_middle[dd66a2b5e7436936]::ty::Ty, rustc_middle[dd66a2b5e7436936]::ty::layout::LayoutCx>
  17:     0x7904d8a9a1fa - rustc_ty_utils[d8e69fb91dd29d5f]::abi::fn_abi_new_uncached
  18:     0x7904d8a8b663 - rustc_ty_utils[d8e69fb91dd29d5f]::abi::fn_abi_of_instance
  19:     0x7904d8a8ac94 - rustc_query_impl[f50001754b2af376]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f50001754b2af376]::query_impl::fn_abi_of_instance::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 16usize]>>
  20:     0x7904d8bcf33b - rustc_query_system[42e1b345d4a75a04]::query::plumbing::try_execute_query::<rustc_query_impl[f50001754b2af376]::DynamicConfig<rustc_query_system[42e1b345d4a75a04]::query::caches::DefaultCache<rustc_middle[dd66a2b5e7436936]::ty::PseudoCanonicalInput<(rustc_middle[dd66a2b5e7436936]::ty::instance::Instance, &rustc_middle[dd66a2b5e7436936]::ty::list::RawList<(), rustc_middle[dd66a2b5e7436936]::ty::Ty>)>, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[f50001754b2af376]::plumbing::QueryCtxt, false>
  21:     0x7904d8bceed3 - rustc_query_impl[f50001754b2af376]::query_impl::fn_abi_of_instance::get_query_non_incr::__rust_end_short_backtrace
  22:     0x7904d50d8d4e - rustc_monomorphize[4f677f822e948498]::mono_checks::check_mono_item
  23:     0x7904d800e4e0 - rustc_query_impl[f50001754b2af376]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f50001754b2af376]::query_impl::check_mono_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 0usize]>>
  24:     0x7904d8c6af4b - rustc_query_system[42e1b345d4a75a04]::query::plumbing::try_execute_query::<rustc_query_impl[f50001754b2af376]::DynamicConfig<rustc_query_system[42e1b345d4a75a04]::query::caches::DefaultCache<rustc_middle[dd66a2b5e7436936]::ty::instance::Instance, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[f50001754b2af376]::plumbing::QueryCtxt, false>
  25:     0x7904d8c6abd1 - rustc_query_impl[f50001754b2af376]::query_impl::check_mono_item::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7904d50b200e - rustc_monomorphize[4f677f822e948498]::collector::items_of_instance
  27:     0x7904d82d29ca - rustc_query_impl[f50001754b2af376]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f50001754b2af376]::query_impl::items_of_instance::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 32usize]>>
  28:     0x7904d8a5c395 - rustc_query_system[42e1b345d4a75a04]::query::plumbing::try_execute_query::<rustc_query_impl[f50001754b2af376]::DynamicConfig<rustc_query_system[42e1b345d4a75a04]::query::caches::DefaultCache<(rustc_middle[dd66a2b5e7436936]::ty::instance::Instance, rustc_middle[dd66a2b5e7436936]::mir::mono::CollectionMode), rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 32usize]>>, false, false, false>, rustc_query_impl[f50001754b2af376]::plumbing::QueryCtxt, false>
  29:     0x7904d8a5bfb1 - rustc_query_impl[f50001754b2af376]::query_impl::items_of_instance::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7904d8a5e9d7 - rustc_monomorphize[4f677f822e948498]::collector::collect_items_rec::{closure#0}
  31:     0x7904d8a5fb3e - rustc_monomorphize[4f677f822e948498]::collector::collect_items_rec
  32:     0x7904d827e5e1 - rustc_monomorphize[4f677f822e948498]::collector::collect_crate_mono_items::{closure#1}::{closure#0}
  33:     0x7904d86e8638 - rustc_monomorphize[4f677f822e948498]::partitioning::collect_and_partition_mono_items
  34:     0x7904d9463164 - rustc_query_impl[f50001754b2af376]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f50001754b2af376]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 24usize]>>
  35:     0x7904d9463149 - <rustc_query_impl[f50001754b2af376]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2} as core[e9d4aeab7aaf03ba]::ops::function::FnOnce<(rustc_middle[dd66a2b5e7436936]::ty::context::TyCtxt, ())>>::call_once
  36:     0x7904d9462ca8 - rustc_query_system[42e1b345d4a75a04]::query::plumbing::try_execute_query::<rustc_query_impl[f50001754b2af376]::DynamicConfig<rustc_query_system[42e1b345d4a75a04]::query::caches::SingleCache<rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[f50001754b2af376]::plumbing::QueryCtxt, false>
  37:     0x7904d9462a4d - rustc_query_impl[f50001754b2af376]::query_impl::collect_and_partition_mono_items::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7904d8d07c71 - rustc_codegen_ssa[16dc2902a2946f7d]::back::symbol_export::exported_generic_symbols_provider_local
  39:     0x7904d8e0e575 - rustc_query_impl[f50001754b2af376]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f50001754b2af376]::query_impl::exported_generic_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 16usize]>>
  40:     0x7904d8e0e54b - <rustc_query_impl[f50001754b2af376]::query_impl::exported_generic_symbols::dynamic_query::{closure#2} as core[e9d4aeab7aaf03ba]::ops::function::FnOnce<(rustc_middle[dd66a2b5e7436936]::ty::context::TyCtxt, rustc_span[4f3535c5822034d]::def_id::CrateNum)>>::call_once
  41:     0x7904d8e0c2a6 - rustc_query_system[42e1b345d4a75a04]::query::plumbing::try_execute_query::<rustc_query_impl[f50001754b2af376]::DynamicConfig<rustc_data_structures[32ba421f28fd0f11]::vec_cache::VecCache<rustc_span[4f3535c5822034d]::def_id::CrateNum, rustc_middle[dd66a2b5e7436936]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[42e1b345d4a75a04]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[f50001754b2af376]::plumbing::QueryCtxt, false>
  42:     0x7904d8e0bdcc - rustc_query_impl[f50001754b2af376]::query_impl::exported_generic_symbols::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7904d8b1da26 - <rustc_metadata[46f894f4ef43a6bc]::rmeta::encoder::EncodeContext>::encode_crate_root
  44:     0x7904d937a70e - <rustc_metadata[46f894f4ef43a6bc]::rmeta::encoder::encode_metadata::{closure#3} as core[e9d4aeab7aaf03ba]::ops::function::FnOnce<(rustc_middle[dd66a2b5e7436936]::ty::context::TyCtxt, &std[d75eede35f95485e]::path::Path)>>::call_once
  45:     0x7904d93778d0 - rustc_metadata[46f894f4ef43a6bc]::rmeta::encoder::encode_metadata
  46:     0x7904d9034745 - rustc_metadata[46f894f4ef43a6bc]::fs::encode_and_write_metadata
  47:     0x7904d935e2e9 - <rustc_interface[dcfd73859d92938d]::queries::Linker>::codegen_and_build_linker
  48:     0x7904d935b870 - <rustc_interface[dcfd73859d92938d]::passes::create_and_enter_global_ctxt<core[e9d4aeab7aaf03ba]::option::Option<rustc_interface[dcfd73859d92938d]::queries::Linker>, rustc_driver_impl[483de4215d5a0d3a]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[e9d4aeab7aaf03ba]::ops::function::FnOnce<(&rustc_session[8d2fd3d44d3f439b]::session::Session, rustc_middle[dd66a2b5e7436936]::ty::context::CurrentGcx, alloc[c5f1165681da87d5]::sync::Arc<rustc_data_structures[32ba421f28fd0f11]::jobserver::Proxy>, &std[d75eede35f95485e]::sync::once_lock::OnceLock<rustc_middle[dd66a2b5e7436936]::ty::context::GlobalCtxt>, &rustc_data_structures[32ba421f28fd0f11]::sync::worker_local::WorkerLocal<rustc_middle[dd66a2b5e7436936]::arena::Arena>, &rustc_data_structures[32ba421f28fd0f11]::sync::worker_local::WorkerLocal<rustc_hir[e927335bd4ed3a34]::Arena>, rustc_driver_impl[483de4215d5a0d3a]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  49:     0x7904d8fd3f00 - rustc_interface[dcfd73859d92938d]::interface::run_compiler::<(), rustc_driver_impl[483de4215d5a0d3a]::run_compiler::{closure#0}>::{closure#1}
  50:     0x7904d9392f09 - std[d75eede35f95485e]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[dcfd73859d92938d]::util::run_in_thread_with_globals<rustc_interface[dcfd73859d92938d]::util::run_in_thread_pool_with_globals<rustc_interface[dcfd73859d92938d]::interface::run_compiler<(), rustc_driver_impl[483de4215d5a0d3a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  51:     0x7904d9392bea - <<std[d75eede35f95485e]::thread::Builder>::spawn_unchecked_<rustc_interface[dcfd73859d92938d]::util::run_in_thread_with_globals<rustc_interface[dcfd73859d92938d]::util::run_in_thread_pool_with_globals<rustc_interface[dcfd73859d92938d]::interface::run_compiler<(), rustc_driver_impl[483de4215d5a0d3a]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[e9d4aeab7aaf03ba]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x7904d8cf35af - std::sys::thread::unix::Thread::new::thread_start::h262bd1e8192b1475
  53:     0x7904d2894ac3 - <unknown>
  54:     0x7904d2926850 - <unknown>
  55:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/app/rustc-ice-2025-10-19T11_41_08-1.txt` to your bug report

note: compiler flags: -C debuginfo=2 -C llvm-args=--x86-asm-syntax=intel --crate-type rlib

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `foo`
#1 [check_mono_item] monomorphization-time checking
... and 3 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by beetrees**
Fixes the 64-bit SPARC part of rust-lang/rust#115609 by replacing the current implementation with a new implementation modelled on the RISC-V calling convention code ([SPARC ABI reference](https://sparc.org/wp-content/uploads/2014/01/SCD.2.4.1.pdf.gz)).

Pinging `sparcv9-sun-solaris` target maintainers: @psumbera @kulikjak
Fixes rust-lang/rust#115336
Fixes rust-lang/rust#115399
Fixes rust-lang/rust#122620
Fixes https://github.com/rust-lang/rust/issues/147883
r? @workingjubilee

### CODE REVIEW

**Comment by beetrees** [comment]
Note that there are currently two places that Clang and GCC disagree AFAIK:

- Clang fails to correctly align 16-byte structs when passing them as arguments, whereas GCC correctly aligns them. As the specification states that the structs must be aligned, I've filed an Clang bug at https://github.com/llvm/llvm-project/issues/144709.
- Clang passes floating point fields in packed structs in floating point register if the field is aligned within the argument as a whole, whereas GCC always passes packed structs in integer registers. The specification doesn't consider the existence of packed structs, however in my opinion Clang's interpretation seems more correct so that's what I've implemented in this PR. Issues for [Rust](https://github.com/rust-lang/rust/issues/57103), [Clang](https://github.com/llvm/llvm-project/issues/39500) and [GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88592).

**Comment by psumbera** [comment]
Thank you for doing this! My knowledge in this area is rather limited.

I was able to build latest Rust sources with your fix on top on Solaris 11.4 SPARC. Then I used this version to build Firefox on Solaris. There was no problem. Firefox also worked as expected.

I also tested some problematic cases which I was handling few years ago (https://github.com/psumbera/rust-sparc64-abi-tests). All seemed to be ok.

**Comment by bjorn3** [comment]
I don't have time to properly review this right now.

r? compiler

**Comment by beetrees** [comment]
Rebased

**Comment by wesleywiser** [comment]
Hi @workingjubilee, are you still interested in reviewing this? If not, we can reroll for a different reviewer. Thanks!

File: tests/assembly-llvm/sparc-struct-abi.rs
Comment (tgross35) [inline tests/assembly-llvm/sparc-struct-abi.rs:1]: Do these need `fn(T) -> T` signatures? I've found abi tests a bit easier to follow if split to `fn(T, &mutT)` and `fn(&T) -> T`

File: tests/assembly-llvm/sparc-struct-abi.rs [hunk 1]
```diff
@@ -66,3 +82,58 @@ pub unsafe extern "C" fn caller() {
     opaque_callee(Franta { a: 1.0, b: 2.0, c: 3.0, d: 4.0 }, 3);
     tail_call_avoidance_fn();
 }
+
```
Comment (tgross35) [inline tests/assembly-llvm/sparc-struct-abi.rs:95]: Mind adding comments about what these are showing?

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 2]
```diff
@@ -224,9 +185,10 @@ where
                 && arg.layout.is_zst()
             {
                 arg.make_indirect_from_ignore();
+                double_word_count += 1;
             }
-            return;
+            continue;
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs:226]: Huh, was this just ignoring all args after a ZST? This would probably be a good test to add.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 3]
```diff
@@ -1,210 +1,170 @@
...
+                        if let DoubleWord::Words(words) = &mut double_words[index] {
+                            words[(offset.bytes_usize() % 8) / 4] = Word::F32;
+                        } else {
+                            unreachable!();
+                        }
+                    }
+                    Float::F16 => {
+                        // FIXME(llvm/llvm-project#97981): f16 doesn't have a proper ABI in LLVM on
+                        // sparc64 yet. Once it does, double-check if it needs to be passed in a
+                        // floating-point register here.
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: Maybe worth just updating to what Clang has now? (Since the sparc part of that issue was addressed). I don't think they would update again unless GCC does something different

File: tests/assembly-llvm/sparc-struct-abi.rs [hunk 4]
```diff
@@ -66,3 +82,58 @@ pub unsafe extern "C" fn caller() {
...
+    // CHECK-NEXT: sllx %o0, 32, %o0
+    value
+}
+
+// CHECK-LABEL: less_floats:
+#[no_mangle]
+extern "C" fn less_floats(_: i64, value: LessFloats) -> LessFloats {
+    // CHECK: mov %o1, %o0
+    // CHECK-NEXT: fmovs %f2, %f0
+    // CHECK-NEXT: fmovd %f4, %f2
```
Comment (tgross35) [inline tests/assembly-llvm/sparc-struct-abi.rs]: Maybe CHECK-DAG to allow for reordering

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 5]
```diff
@@ -1,210 +1,170 @@
...
+        *total_double_word_count = start_double_word_count + double_word_count;
         return;
     }
 
     let total = arg.layout.size;
     if total > in_registers_max {
         arg.make_indirect();
+        *total_double_word_count += 1;
         return;
     }
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs:141]: Would you mind giving a couple of comments about what behavior this is implementing?

**Comment by workingjubilee** [comment]
Sorry about that, currently in catchup mode so I am going to delegate, yes.

r? @tgross35

File: tests/assembly-llvm/sparc-struct-abi.rs
Comment (beetrees) [reply tests/assembly-llvm/sparc-struct-abi.rs:1]: I've split the tests.

File: tests/assembly-llvm/sparc-struct-abi.rs (hunk 1 above)
Comment (beetrees) [reply tests/assembly-llvm/sparc-struct-abi.rs:95]: Done

File: compiler/rustc_target/src/callconv/sparc64.rs (hunk 2 above)
Comment (beetrees) [reply compiler/rustc_target/src/callconv/sparc64.rs:226]: Test added.

File: compiler/rustc_target/src/callconv/sparc64.rs (hunk 3 above)
Comment (beetrees) [reply compiler/rustc_target/src/callconv/sparc64.rs]: Done

File: tests/assembly-llvm/sparc-struct-abi.rs (hunk 4 above)
Comment (beetrees) [reply tests/assembly-llvm/sparc-struct-abi.rs]: I generally favour `CHECK-NEXT` as it allows ensuring that all the lines of a particular block of assembly are mentioned in the test. AFAIK there is no way to use `CHECK-DAG` in a "require all lines are matched" mode.

File: compiler/rustc_target/src/callconv/sparc64.rs (hunk 5 above)
Comment (beetrees) [reply compiler/rustc_target/src/callconv/sparc64.rs:141]: I've added some comments to the start of the function.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 6]
```diff
@@ -1,210 +1,185 @@
...
-    arg.cast_to(Uniform::new(Reg::i64(), total));
+    if let [Some(reg), None, ..] = regs {
+        arg.cast_to_and_pad_i32(CastTarget::from(reg).with_attrs(attrs.into()), pad);
+    } else {
+        arg.cast_to_and_pad_i32(
+            CastTarget::prefixed(regs, Uniform::new(Reg::i8(), Size::ZERO))
+                .with_attrs(attrs.into()),
+            pad,
+        );
+    }
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: Could you add a note about why the `Some(reg), None` case is special?

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 7]
```diff
@@ -1,210 +1,185 @@
...
+                        // Match LLVM by passing `f16` in integer registers.
+                    }
                 }
-                data = parse_structure(cx, layout.field(cx, i), data.clone(), offset);
             }
-        }
-        _ => {
-            if let BackendRepr::ScalarPair(scalar1, scalar2) = &layout.backend_repr {
-                data = arg_scalar_pair(cx, scalar1, scalar2, offset, data);
+            _ => {}
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: What happens in the fallback case where offset isn't aligned?

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 8]
```diff
@@ -1,210 +1,185 @@
...
+                    }
+                }
+            }
+            FieldsShape::Array { .. } => {}
+            FieldsShape::Arbitrary { .. } => match arg_layout.variants {
+                Variants::Multiple { .. } => {}
+                Variants::Single { .. } | Variants::Empty => {
+                    // Match Clang by ignoring whether a struct is packed and just considering
+                    // whether individual fields are aligned. GCC currently uses only integer
+                    // registers when passing packed structs.
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs:87]: This has come up a couple of times; it may be worth noting in a comment for the module that GCC and Clang have disagreements that the ABI doesn't resolve, and we match Clang's behavior in these cases.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 9]
```diff
@@ -1,210 +1,185 @@
...
-                Sdata {
-                    prefix: [None; 8],
-                    prefix_index: 0,
-                    last_offset: Size::ZERO,
-                    has_float: false,
-                    arg_attribute: ArgAttribute::default(),
-                },
-                Size::ZERO,
-            );
+    let mut double_words = [DoubleWord::Words([Word::Integer; 2]); 4];
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: Could you note where the length 4 comes from, or put it in a const? Assuming 8 word-sized registers for arg passing.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 10]
```diff
@@ -213,9 +188,10 @@ where
     C: HasDataLayout + HasTargetSpec,
 {
     if !fn_abi.ret.is_ignore() {
-        classify_arg(cx, &mut fn_abi.ret, Size::from_bytes(32));
+        classify_arg(cx, &mut fn_abi.ret, Size::from_bytes(32), &mut 0);
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs:210]: Could you mention the significance of 32 bytes?

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 11]
```diff
@@ -224,9 +200,10 @@ where
                 && arg.layout.is_zst()
             {
                 arg.make_indirect_from_ignore();
+                double_word_count += 1;
             }
-            return;
+            continue;
         }
-        classify_arg(cx, arg, Size::from_bytes(16));
+        classify_arg(cx, arg, Size::from_bytes(16), &mut double_word_count);
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs:229]: Similarly for 16 here

**Review by tgross35 — APPROVED** [review]
This looks great, thanks for the updates. I requested a few more comments for things that weren't obvious, r=me after those.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/142680/565a9ca63e9df4b223fed0da01f15e578acfb538..b2e4ee99ecb4fe09faaadcab9e9391cc4444df95)*

**Comment by psumbera** [comment]
> @psumbera if you have access to a sparc machine, any chance you could run https://github.com/Gankra/abi-cafe with and without this PR as a sanity check? You should be able to clone the repo and run `cargo run -- --toolchains 'rustc,cc,gcc,clang' and post the list of failures from stdout. To rerun with the `PATH=

Not sure how to analyze it. But `grep failed! test.log | wc -l` gives me `156` without the change and `228` with the change. So there seems to be some regression.

Generally I would suggest to use for tests: https://portal.cfarm.net/machines/list/ (cfarm216). This is latest Solaris (SPARC-M8).

I'm ready to help and provide full logs somewhere or anything.

Here are just few tests which are newly failing:
```
+  F32Array::conv_c::repr_c::cc_calls_rustc::struct_in_1              failed!
+  F32Array::conv_c::repr_c::cc_calls_rustc::val_in                   failed!
+  F32Array::conv_c::repr_c::cc_calls_rustc::val_in_10                failed!
..
+  F32Array::conv_c::repr_c::gcc_calls_rustc::struct_in_1              failed!
+  F32Array::conv_c::repr_c::gcc_calls_rustc::val_in                   failed!
+  F32Array::conv_c::repr_c::gcc_calls_rustc::val_in_10                failed!
..
+  Test F32Array::conv_c::repr_c::cc_calls_rustc::struct_in_1              failed!
+  Test F32Array::conv_c::repr_c::cc_calls_rustc::val_in                   failed!
+  Test F32Array::conv_c::repr_c::cc_calls_rustc::val_in_10    
..
+  Test F32Array::conv_c::repr_c::gcc_calls_rustc::struct_in_1              failed!
+  Test F32Array::conv_c::repr_c::gcc_calls_rustc::val_in                   failed!
+  Test F32Array::conv_c::repr_c::gcc_calls_rustc::val_in_10                failed!
..
```

**Comment by folkertdev** [comment]
Presumably this also fixes https://github.com/rust-lang/rust/issues/147883, though it would be good to test for it explicitly. 

We potentially also need to handle `{ i32, float }` in a custom way. With clang/LLVM the struct fields are actually unpacked and passed separately. There some information on why here https://github.com/llvm/llvm-project/blob/fcb1a82811490ca581b4db484a2b67be86650a84/clang/lib/CodeGen/Targets/Sparc.cpp#L81-L106. However the current implementation (passing `{ i32, float }` does appear to work as expected 

https://godbolt.org/z/7sW5TE5Gx.

In any case, that probably deserves a test too given that LLVM calls it out as a special case.

**Comment by SpriteOvO** [comment]
Hi @beetrees, ping from triage team. Are there any further updates on this PR?

**Comment by folkertdev** [comment]
In @beetrees's absence, @tgross35 and I decided that we should move forward here to remove a blocker for `f128`, so I'll rebase and add some comments and this should be good to go.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 12]
```diff
@@ -1,239 +1,220 @@
...
+                }
             }
         }
     }
 
-    arg.cast_to(Uniform::new(Reg::i64(), total));
+    let cast_target = match regs {
+        [Some(reg), None, ..] => CastTarget::from(reg),
+        _ => CastTarget::prefixed(regs, Uniform::new(Reg::i8(), Size::ZERO)),
+    };
```
Comment (folkertdev) [inline compiler/rustc_target/src/callconv/sparc64.rs:198]: I'm not entirely sure why the special-casing is, but the first case fits in a register no problem, while the second case requires some sort of larger struct that is cast.

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 13]
```diff
@@ -1,214 +1,199 @@
...
+                        Word::Integer => push(Reg::i32()),
+                    }
+                }
             }
         }
     }
 
-    arg.cast_to(Uniform::new(Reg::i64(), total));
+    let cast_target = match regs {
+        [Some(reg), None, ..] => CastTarget::from(reg),
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: Optional nit, sanity check

```rust
        [Some(reg), None, rest @ ..] => {
            debug_assert!(rest.iter().all(|x| x.is_none());
            CastTarget::from(reg)
        }
```

File: compiler/rustc_target/src/callconv/sparc64.rs [hunk 14]
```diff
@@ -217,23 +202,29 @@ where
...
-        classify_arg(cx, &mut fn_abi.ret, Size::from_bytes(32));
+        // A return value of 32 bytes or smaller is passed via registers.
+        classify_arg(cx, &mut fn_abi.ret, Size::from_bytes(32), &mut 0);
     }
 
+    // sparc64-unknown-linux-{gnu,musl,uclibc} doesn't ignore ZSTs.
+    let passes_zsts = match cx.target_spec().os {
+        Os::Linux => matches!(cx.target_spec().env, Env::Gnu | Env::Musl | Env::Uclibc),
+        _ => false,
+    };
```
Comment (tgross35) [inline compiler/rustc_target/src/callconv/sparc64.rs]: What makes this env-dependent? The only supported Linux env seems to be gnu at this time.

**Review by tgross35 — APPROVED** [review]
Two nits but LGTM, thanks for picking this up. Two comment requests below.

I believe you should technically make yourself the commit author since you're the one submitting it in its final form. Then add beetrees back via a `Co-authored-by:` trailer.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/142680/271951ba187953d39b1c66b062d83f558aa23856..7515aca433e707d54d31d3f05fe5d955f051cf3f)*

File: compiler/rustc_target/src/callconv/sparc64.rs (hunk 14 above)
Comment (folkertdev) [reply compiler/rustc_target/src/callconv/sparc64.rs]: We have

```
sparc64-unknown-linux-gnu
sparc64-unknown-netbsd
sparc64-unknown-openbsd
sparcv9-sun-solaris
```

so this only matches in if the os is linux, and it's a bit more general so that if a new target (e.g. musl) is added, it does the right thing from the start. There could, I suppose, be a linux env that does ignore ZSTs.

Comment (tgross35) [reply compiler/rustc_target/src/callconv/sparc64.rs]: Why would it ever be coupled to the env though? I see that this exists across other arches but it seems a bit bogus.

Doing some archaeology, the pattern kind of follows:

- 65dabd6eaf24bbf3b7069a51984411aea2864856 which references the SPARC ABI
- 19b84088d76b8ded63cbaf12991213f4f437e689
- e177207b3685de49301518e56add65494d828b51
- More targets, grouping
- https://github.com/rust-lang/rust/pull/125854

The env had to be specified on Windows and it seems like others followed suit. I think this can just be deleted here, probably the same in the other places, under the assumption that we're not likely to get a nightmare env that breaks from the psABI (at least not on Linux).

**Review by tgross35 — APPROVED** [review]
Awesome, lgtm

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/142680/f21b4c0888ca6a388fcf9365fc0044fa0642ab98..4373d2f2228697ccdd7306d2023b82483c296533)*
