### PR TITLE
Fix DWARF generation for enums

### LINKED ISSUE #32920: DWARF for enums could be improved
Suppose you have a "non-trivial" enum like:

```
enum MoreComplicated {
    One,
    Two(i32),
}
```

The DWARF looks like:

```
 <2><a7>: Abbrev Number: 6 (DW_TAG_union_type)
    <a8>   DW_AT_name        : (indirect string, offset: 0x16e): MoreComplicated
    <ac>   DW_AT_byte_size   : 24
 <3><ad>: Abbrev Number: 7 (DW_TAG_member)
    <ae>   DW_AT_type        : <0xc0>
    <b2>   DW_AT_data_member_location: 0
 <3><b3>: Abbrev Number: 7 (DW_TAG_member)
    <b4>   DW_AT_type        : <0xd1>
    <b8>   DW_AT_data_member_location: 0
```

Then looking at the type of `One`, aka DIE 0xc0:

```
 <2><c0>: Abbrev Number: 8 (DW_TAG_structure_type)
    <c1>   DW_AT_name        : (indirect string, offset: 0x160): One
    <c5>   DW_AT_byte_size   : 1
 <3><c6>: Abbrev Number: 9 (DW_TAG_member)
    <c7>   DW_AT_name        : (indirect string, offset: 0x1b7): RUST$ENUM$DISR
    <cb>   DW_AT_type        : <0x6d>
    <cf>   DW_AT_data_member_location: 0
```

This is peculiar DWARF in a few ways.

First, this emits a separate structure type for each branch.  DWARF has a notion of a discriminated union that might be a closer fit semantically.  See `DW_TAG_variant_part`, `DW_AT_discr`, etc.  (gdb's DWARF reader doesn't handle these at all, but it certainly could be made to.)

Second, I think at the very least the discriminant should be marked `DW_AT_artificial`.

### LINKED ISSUE #32924: DWARF puts enum and union with same name into the same scope
This is perhaps a bit of a gdb-specific bug.  The basic issue is that having multiple entities in the same scope with the same name but different DWARF tags makes it a pain for gdb to sensibly create its symbol table.

I see the issue with a number of constructs.  For this example, consider something like:

```
enum MoreComplicated {
    One,
    Two(i32),
}
```

The DWARF gets an enum:

```
 <2><6d>: Abbrev Number: 4 (DW_TAG_enumeration_type)
    <6e>   DW_AT_type        : <0x415>
    <72>   DW_AT_enum_class  : 1
    <72>   DW_AT_name        : (indirect string, offset: 0x16e): MoreComplicated
    <76>   DW_AT_byte_size   : 1
```

... but also a union:

```
 <2><a7>: Abbrev Number: 6 (DW_TAG_union_type)
    <a8>   DW_AT_name        : (indirect string, offset: 0x16e): MoreComplicated
    <ac>   DW_AT_byte_size   : 24
```

It would be better for gdb to unify these two objects into a single representation in DWARF.  For gdb's purposes it is fine if this representation requires some special Rust-specific code, for example knowing what names to insert into what scopes.

This is related to issue #32920, in that maybe a tagged variant would also help this situation.

### LINKED ISSUE #52762: Rust DWARF debug info creates duplicate `DW_TAG_structure_type`s with the same name
Given this pretty common pattern
```
enum Foo { Bar(Bar) }
struct Bar { ... }
```
`rustc` generates two `DW_TAG_structure_type` entries in the same namespace both called `Bar`, one for the Rust struct, the other for the `Foo::Bar` variant. This is a problem for tools that want to refer to DWARF structure types by name (e.g. when trying to guess type identities across compilation unit boundaries). It would also be a problem if a user tries to refer to the type `Bar` in the user interface of a debugger (without additional hacks like ignoring types containing `RUST$ENUM$DISR`).

### LINKED ISSUE #53153: Pretty printing debuginfo for size-optimized enums is broken
The [code](https://github.com/rust-lang/rust/blob/11a902431b8e66da8486b3b9a2d8527746c6ab1a/src/librustc_codegen_llvm/debuginfo/metadata.rs#L1248-L1289) that generates the special DWARF field names for size-optimized enums is broken for a while now. PRs keep getting opened to "fix" this on the pretty printer side but that's not possible because the debuginfo does not contain the necessary information for the pretty printer to correctly decode a given value. See https://github.com/rust-lang/rust/pull/51777#issuecomment-404828872 for an example and some discussion on a possible fix.

This will be fixed eventually when enums get a proper representation in DWARF. Meanwhile, it's unclear how much of a priority fixing this is.

cc @tromey

### PR DESCRIPTION
**Pull request by tromey**
The DWARF generated for Rust enums was always somewhat unusual.
Rather than using DWARF constructs directly, it would emit magic field
names like "RUST$ENCODED$ENUM$0$Name" and "RUST$ENUM$DISR".  Since
PR #45225, though, even this has not worked -- the ad hoc scheme was
not updated to handle the wider variety of niche-filling layout
optimizations now available.

This patch changes the generated DWARF to use the standard tags meant
for this purpose; namely, DW_TAG_variant and DW_TAG_variant_part.

The patch to implement this went in to LLVM 7.  In order to work with
older versions of LLVM, and because LLVM doesn't do anything here for
PDB, the existing code is kept as a fallback mode.

Support for this DWARF is in the Rust lldb and in gdb 8.2.

Closes #32920
Closes #32924
Closes #52762
Closes #53153

### CODE REVIEW

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 1]
```diff
@@ -1220,75 +1261,120 @@ impl EnumMemberDescriptionFactory<'ll, 'tcx> {
...
+                                write!(name, "{}$", i).unwrap();
+                                compute_field_path(cx, name, field, inner_offset, size);
+                            }
                         }
                     }
+                    compute_field_path(cx, &mut name,
+                                       self.layout,
+                                       self.layout.fields.offset(0),
+                                       self.layout.field(cx, 0).size);
+                    name.push_str(&adt.variants[*niche_variants.start()].name.as_str());
```
Comment (eddyb) [inline src/librustc_codegen_llvm/debuginfo/metadata.rs]: Aww, it's a bit sad we have to keep this suboptimal form around.

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 2]
```diff
@@ -1220,75 +1261,120 @@ impl EnumMemberDescriptionFactory<'ll, 'tcx> {
...
+
+                        set_members_of_composite_type(cx,
+                                                      variant_type_metadata,
+                                                      member_descriptions);
+
+                        let niche_value = if i == dataful_variant {
+                            None
+                        } else {
+                            Some((i.wrapping_sub(*niche_variants.start()) as u128)
+                                 .wrapping_add(niche_start) as u64)
```
Comment (eddyb) [inline src/librustc_codegen_llvm/debuginfo/metadata.rs]: This LGTM. cc @oli-obk @nagisa (in case I'm missing some arithmetic subtleties)

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 3]
```diff
@@ -1487,30 +1588,146 @@ fn prepare_enum_metadata(
...
+        );
+    }
+
+    let discriminator_metadata = match &layout.variants {
+        // A single-variant enum has no discriminant.
+        &layout::Variants::Single { .. } => None,
+
+        &layout::Variants::NicheFilling { ref niche, .. } => {
+            // Find the integer type of the correct size.
+            let discr_type = niche.value.to_ty(cx.tcx);
```
Comment (eddyb) [inline src/librustc_codegen_llvm/debuginfo/metadata.rs]: You can get the size and alignment from `niche.value` directly.

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 4]
```diff
@@ -1487,30 +1588,146 @@ fn prepare_enum_metadata(
...
+            let (size, align) = cx.size_and_align_of(discr_type);
+
+            let discr_type = (match size.bits() {
+                8 => Integer::I8,
+                16 => Integer::I16,
+                32 => Integer::I32,
+                64 => Integer::I64,
+                bits => bug!("prepare_enum_metadata: unknown niche bit size {}", bits),
```
Comment (eddyb) [inline src/librustc_codegen_llvm/debuginfo/metadata.rs]: Is there no method on `Integer` to do this conversion?

**Comment by nagisa** [comment]
This definitely wants a test or two.

**Review by eddyb — CHANGES_REQUESTED** [review]
r=me with nits fixed

**Comment by eddyb** [comment]
cc @michaelwoerister @alexcrichton

**Comment by nikomatsakis** [comment]
r? @eddyb 

(I pinged him on Discord as I'm not really that familiar with this code. But I see he already left a review before I came back to re-assign. I agree with @nagisa that we could use more tests here :)

**Comment by tromey** [comment]
I can write more tests but note that there are existing debuginfo tests that already cover the ordinary cases.  The new test is testing the case that could not be made to work previously.

File: src/librustc_codegen_llvm/debuginfo/metadata.rs (hunk 4 above)
Comment (tromey) [reply src/librustc_codegen_llvm/debuginfo/metadata.rs]: Not directly (that I could find) but I can use `Integer::fit_unsigned`.

**Comment by tromey** [comment]
Still investigating that failure.  I'd tried things out with llvm 6 but not 5.  I somewhat recall having to make a change here for 6; I will try all 3 ways again but if something has to regress, I think we should let it be 5.

File: src/librustc_codegen_llvm/debuginfo/metadata.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_codegen_llvm/debuginfo/metadata.rs]: Oh, I think you should match on `Primitive`, convert floats to `I32` / `I64`, and pointers to `cx.data_layout().ptr_sized_integer()`. That way you don't need to turn an integer back into itself by looking at its size.

**Comment by tromey** [comment]
I built rust against LLVM 5, 6, and rust-llvm; and then I tested each one against gdb 7.11, 8.1, and 8.2.

This found a crash in 8.2, filed: https://sourceware.org/bugzilla/show_bug.cgi?id=23626.  I'll fix this before 8.2.1.

I couldn't reproduce the bot's failure; but the bot is using 7.11, and my feeling is that a minor output regression there is nothing to worry about.  So, if it persists and there are no objections, I'll just bump the minimum gdb version for the test.

**Comment by tromey** [comment]
> I couldn't reproduce the bot's failure

I rebased & tried again and now it failed.

**Comment by tromey** [comment]
> I rebased & tried again and now it failed.

At some point I thought I needed to give the variants names, but reverting this and re-testing didn't show any problems.

**Comment by tromey** [comment]
@eddyb can you re-review? I don't think I have sufficient permissions to mark it.  Thanks.

**Comment by eddyb** [comment]
@tromey Is the compiler-builtins submodule change intentional?

**Comment by tromey** [comment]
> @tromey Is the compiler-builtins submodule change intentional?

Nope.

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 5]
```diff
@@ -1487,30 +1602,145 @@ fn prepare_enum_metadata(
...
+    let empty_array = create_DIArray(DIB(cx), &[]);
+    let variant_part = unsafe {
+        llvm::LLVMRustDIBuilderCreateVariantPart(
+            DIB(cx),
+            containing_scope,
+            ptr::null_mut(),
+            file_metadata,
+            UNKNOWN_LINE_NUMBER,
+            enum_type_size.bits(),
+            enum_type_align.abi_bits() as u32,
```
[the remark this answers is not in the document]
Comment (tromey) [reply src/librustc_codegen_llvm/debuginfo/metadata.rs]: This part is just a bit of DWARF formalism.  This is emitting a `DW_TAG_variant_part`, which according to DWARF is the part of an enclosing structure that can vary.  For Rust, the entire thing can vary, so we emit a structure wrapping a variant part, which wraps the variants.  Since there can only be one variant part, it makes sense for it to fill the enclosing structure.  And, the location of this thing is unimportant as it is basically entirely artificial -- a synthetic construct only necessary because this is how DWARF mandates it.

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc_codegen_llvm/debuginfo/metadata.rs]: Ah, so it's not per-variant?

[the remark this answers is not in the document]
Comment (tromey) [reply src/librustc_codegen_llvm/debuginfo/metadata.rs]: Nope.

**Review by eddyb — APPROVED** [review]

**Comment by kennytm** [comment]
@bors retry travis-ci/travis-ci#9696

```
Could not resolve host: s3-us-west-1.amazonaws.com
```

**Comment by tromey** [comment]
I couldn't reproduce that locally.  Next week I'll try setting up docker and finding the images and doing a build that is closer to the one that was reported.  Unless someone has a better idea.

**Comment by tromey** [comment]
Doing the musl docker build locally (`./src/ci/docker/run.sh dist-i586-gnu-i586-i686-musl`) fails with
```
error: internal compiler error: librustc/ty/context.rs:273: node unknown node (id=651468) with HirId::owner DefId(0/0:0 ~ core[f3a2]) cannot be placed in TypeckTables with local_id_root DefId(0/0:1807 ~ core[f3a2]::panicking[0]::panic_fmt[0])
```

**Comment by tromey** [comment]
@kennytm actually this is more of a thumbs-down situation because the way it fails locally is not the way it fails in travis, so I still don't know how to reproduce this enough to debug it.

Is there a way to get a travis build with more debuginfo?  My attempts to set up one of these builds by hand (without going through docker) have also not been successful.  Those work, but it is complicated enough that I imagine I must have done something wrong.

**Comment by tromey** [comment]
> [01:16:47] LLVM ERROR: IO failure on output stream: No space left on device

I'll ask around in a bit to see what to do about this.

**Comment by tromey** [comment]
Compiling LLVM with `-g1` doesn't run out of disk space and gets a better-enough stack trace to maybe, finally, make progress.

**Comment by tromey** [comment]
OMG I got it to crash here.

**Comment by tromey** [comment]
I think back in February I had an off-by-1 error in my LLVM patch: https://github.com/rust-lang/llvm/blob/rust-llvm-release-8-0-0-v1/lib/Bitcode/Reader/MetadataLoader.cpp#L1298-L1299

**Comment by tromey** [comment]
Ugh, no, that's not it, but it is something close by I think.

**Comment by tromey** [comment]
This call: https://github.com/rust-lang/llvm/blob/rust-llvm-release-8-0-0-v1/lib/Bitcode/Reader/MetadataLoader.cpp#L1310-L1314
... does not preserve the discriminant, fixing this makes it work.

**Comment by tromey** [comment]
https://reviews.llvm.org/D52340

**Comment by tromey** [comment]
Once the rust-llvm change lands, I'll resubmit this.

**Comment by tromey** [comment]
I don't know the protocol here - whether I can carry over the r+ or not.  So in the interest of conservatism, ping @eddyb once again.  The only change from the last time around is that this incorporates the upstream LLVM bug fix.

**Comment by tromey** [comment]
I think what I want to do here is try to upgrade the gdb that's used for tests.  But maybe that will be a pain, I am not sure yet.  So a plan B would be to disable a few debuginfo tests when using an older gdb and a newer LLVM... there's no syntax for that yet AFAIK but I can add something.

**Comment by tromey** [comment]
Rebased and with the existing test cases redone.  The commit messages explain a bit more.  I tested this locally using rustc built against LLVM 5, LLVM 6, and rust-llvm; and running debuginfo tests against gdb 7.11, gdb 8.1, and gdb 8.2.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks so much!

**Comment by tromey** [comment]
The log says that gdb 7.7 was installed for that build, but the test says:
```
// min-gdb-version: 8.2
```

**Comment by tromey** [comment]
It's actually running `arm-linux-androideabi-gdb` but doesn't seem to record the gdb version.

**Comment by tromey** [comment]
compiletest special-cases the android gdb invocation but doesn't extend the same special case to the version check.  I'll open a new PR for this.

**Comment by tromey** [comment]
See #54645.  When that lands I will rebase this.

**Comment by tromey** [comment]
Rebased to pick up the Android fix.  Since the patch didn't change I will see if this works:

@bors: r+

**Comment by tromey** [comment]
Failures with an lldb I don't have.  I think we'll need a mechanism to detect the rust-enabled lldb and to test against it.  Or maybe just require it on one builder, I'll look.

**Comment by TimNN** [comment]
I'll mark this PR as blocked on #54764. (Let me know if that is incorrect).

**Comment by tromey** [comment]
> I'll mark this PR as blocked on #54764. (Let me know if that is incorrect).

It's correct and it will also be blocked on the PR for #54721, which can't be submitted yet.

**Comment by tromey** [comment]
Now blocked on #54964.

**Comment by tromey** [comment]
I found a bug in the rust-lldb that affects enum printing, so this is blocked while I fix that.

**Comment by tromey** [comment]
Now this should probably wait for #53497, which it will clash with a bit.

**Comment by alexcrichton** [comment]
@tromey should this be approved? I think you're approved to merge this as well?

**Comment by tromey** [comment]
Yes, it should be approved.  I'll try.

@bors r+

**Comment by tromey** [comment]
Some difference between the apple lldb and the (non-rust-enabled) linux lldb I suppose.  Will do another macOS build next week.

**Comment by tromey** [comment]
Forgot to make those tests rust-lldb-only.

**Comment by michaelwoerister** [comment]
🎉 🎉 🎉 !
