### PR TITLE
thread parking: fix docs and examples

### LINKED ISSUE #145816: std `thread::Thread::unpark` test deadlocked when run under miri
```
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/145816

r? @joboet 
Cc @m-ou-se @Amanieu

### CODE REVIEW

File: library/std/src/thread/mod.rs [hunk 1]
```diff
@@ -1058,33 +1068,45 @@ impl Drop for PanicGuard {
 ///
 /// ```
 /// use std::thread;
-/// use std::sync::{Arc, atomic::{Ordering, AtomicBool}};
+/// use std::sync::atomic::{Ordering, AtomicBool};
 /// use std::time::Duration;
 ///
-/// let flag = Arc::new(AtomicBool::new(false));
-/// let flag2 = Arc::clone(&flag);
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1065]: I switched this from Arc to static as I find that easier to read.

File: library/std/src/thread/mod.rs [hunk 2]
```diff
@@ -1058,33 +1068,45 @@ impl Drop for PanicGuard {
...
+///     println!("Thread spawned");
+///     // Signal that we are going to `park`. Between this store and our `park`, there may
+///     // be no other `park`, or else that `park` could consume our `unpark` token!
+///     QUEUED.store(true, Ordering::Release);
 ///     // We want to wait until the flag is set. We *could* just spin, but using
 ///     // park/unpark is more efficient.
-///     while !flag2.load(Ordering::Relaxed) {
-///         println!("Parking thread");
+///     while !FLAG.load(Ordering::Acquire) {
+///         // `eprintln!` does not do any thread parking internally so we can safely call it here.
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs]: I don't think we actually guarantee that `eprintln!` does not park, so this comment is dubious.

File: library/std/src/thread/mod.rs [hunk 3]
```diff
@@ -1058,33 +1068,45 @@ impl Drop for PanicGuard {
...
 /// let parked_thread = thread::spawn(move || {
+///     println!("Thread spawned");
+///     // Signal that we are going to `park`. Between this store and our `park`, there may
+///     // be no other `park`, or else that `park` could consume our `unpark` token!
+///     QUEUED.store(true, Ordering::Release);
 ///     // We want to wait until the flag is set. We *could* just spin, but using
 ///     // park/unpark is more efficient.
-///     while !flag2.load(Ordering::Relaxed) {
-///         println!("Parking thread");
+///     while !FLAG.load(Ordering::Acquire) {
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:1084]: I used release/acquire orderings for my variables since generally IMO one should only used relaxed when it is quite obviously the right thing, and I don't think that's obvious here at all. I then also changed the flag for consistency. If this flag indicates that some work was done (as flags often do), then it really should use release/acquire.

File: library/std/src/sys/sync/once/queue.rs [hunk 4]
```diff
@@ -276,7 +276,9 @@ fn wait(
             // If the managing thread happens to signal and unpark us before we
             // can park ourselves, the result could be this thread never gets
             // unparked. Luckily `park` comes with the guarantee that if it got
-            // an `unpark` just before on an unparked thread it does not park.
+            // an `unpark` just before on an unparked thread it does not park. Curcially, we know
```
Comment (RossSmyth) [inline library/std/src/sys/sync/once/queue.rs]:
```suggestion
            // an `unpark` just before on an unparked thread it does not park. Crucially, we know
```

**Review by RossSmyth — CHANGES_REQUESTED** [review]

File: library/std/src/thread/mod.rs (hunk 2 above)
Comment (joboet) [reply library/std/src/thread/mod.rs]: This isn't a guarantee we should give, `eprintln!` might very well be changed to use `park` once I get around to improving the `Mutex` implementation to a lockless-queue variant.

**Review by joboet — CHANGES_REQUESTED** [review]
Thank you, this should *definitely* be documented (this caveat was obvious to me, but I didn't think to point it out).

Could you also add a comment stating that this means that `Waker` cannot be correctly implemented with `thread::park` and `unpark` alone? I know of at least one crate ([pollster](https://github.com/zesterer/pollster/blob/841809207eb2060c1913491cecfa532e01f3b43d/src/lib.rs#L76-L82)) that is subtly broken because it fails to account for this.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145895/269d5b56bcfdf2be82213e72ef9a2e4c592a8c6b..0b926a2132fcb6c1fe818a08e38818e1de3c4530)*

File: library/std/src/thread/mod.rs (hunk 2 above)
Comment (RalfJung) [reply library/std/src/thread/mod.rs]: Then what do you propose we do with this example?

**Comment by RalfJung** [comment]
> Could you also add a comment stating that this means that Waker cannot be correctly implemented with thread::park and unpark alone? I know of at least one crate ([pollster](https://github.com/zesterer/pollster/blob/841809207eb2060c1913491cecfa532e01f3b43d/src/lib.rs#L76-L82)) that is subtly broken because it fails to account for this.

Where do you think such a comment should go?

File: library/std/src/thread/mod.rs (hunk 2 above)
Comment (RalfJung) [reply library/std/src/thread/mod.rs]: It also seems quite problematic for debugging if you can't even call `eprintln` in code like this.

File: library/std/src/thread/mod.rs [hunk 5]
```diff
@@ -1021,13 +1021,23 @@ impl Drop for PanicGuard {
...
+/// desired condition is met, another thread calls [`unpark`] on the handle. The last bullet point
+/// above guarantees that even if the `unpark` occurs before the thread is finished `park`ing, it
+/// will be woken up properly.
+///
+/// Note that the coordination via the shared data structure is crucial: If you `unpark` a thread
+/// without first establishing that it is about to be `park`ing within your code, that `unpark` may
+/// get consumed by a *different* `park` in the same thread, leading to a deadlock. This also means
+/// you must not call unknown code between setting up for parking and calling `park`; for instance,
+/// if you invoke `println!`, that may itself call `park` and thus consume your `unpark` and cause a
+/// deadlock.
```
Comment (joboet) [inline library/std/src/thread/mod.rs:1040]: > Where do you think such a comment should go?

Maybe here?

```suggestion
/// deadlock.
/// 
/// In particular, this means that it is incorrect to...
```

File: library/std/src/thread/mod.rs (hunk 2 above)
Comment (joboet) [reply library/std/src/thread/mod.rs]: > Then what do you propose we do with this example?

I'd just remove the printing in favour of comments.

**Comment by joboet** [comment]
> > I know of at least one crate ([pollster](https://github.com/zesterer/pollster/blob/841809207eb2060c1913491cecfa532e01f3b43d/src/lib.rs#L76-L82)) that is subtly broken because it fails to account for this.
> 
> That seems worth a bug report, no?^^

Yeah, I'll file one (or maybe make a PR) once I get around to it.

File: library/std/src/thread/mod.rs (hunk 5 above)
Comment (RalfJung) [reply library/std/src/thread/mod.rs:1040]: Seems a bit odd to put this in the `park` docs, this seems to be more of a `Waker` thing, no?

I also realized I don't understand why this is insufficient for `Waker`. I just know next to nothing about `Waker`. I don't think just saying "it's insufficient" is very insightful as it raises the inevitable "why".

So I'm going to have to leave adding this comment to you or someone else.
