### PR TITLE
Fix redundant import errors for preload extern crate

### LINKED ISSUE #121915: `unused_imports` redundant import `is already defined here` points to self
`is already defined here` doesn't point to the proper place:
[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cce41d39c93a101266e675c6c7545ffc)
in this output:
```rust
   Compiling playground v0.0.1 (/playground)
warning: the item `libc` is imported redundantly
 --> src/main.rs:3:5
  |
3 | use libc;
  |     ^^^^ the item `libc` is already defined here
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `playground` (bin "playground") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/playground`
```
for this code:
```rust
use std::ffi::{CStr, CString};

use libc;

fn main() {
    let lib_name = CString::new("libEGL.so").unwrap();
    let lib_ptr = unsafe { libc::dlopen(lib_name.as_ptr(), libc::RTLD_NOW) };

    if lib_ptr.is_null() {
        let error_msg = unsafe { CStr::from_ptr(libc::dlerror()) }.to_str().unwrap();
        println!("Error loading library: {}", error_msg);
        return;
    }

    // Access functions from the library
    // ...

    unsafe { libc::dlclose(lib_ptr) };
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (ef324565d 2024-02-27)
binary: rustc
commit-hash: ef324565d071c6d7e2477a195648549e33d6a465
commit-date: 2024-02-27
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0


```

initially mentioned it here, on the pull request: https://github.com/rust-lang/rust/pull/117772#issuecomment-1974877122

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #121915

### CODE REVIEW

File: compiler/rustc_resolve/src/imports.rs [hunk 1]
```diff
@@ -1368,12 +1367,24 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             let mut redundant_spans: Vec<_> = redundant_span.present_items().collect();
             redundant_spans.sort();
             redundant_spans.dedup();
+            let is_preload = self.extern_prelude_get(target, false).is_some();
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:1370]: I don't think this is a correct approach, it regresses the 2015 edition case in particular, when we can indeed emit the "the item `{ident}` is already {introduced} here" with a good span (the `extern crate` item).

(Also `ns` is not checked, so `is_preload` can return true for values and macros, and "preload" is not a terminology used anywhere else.)

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 2]
```diff
@@ -114,6 +114,9 @@ pub(super) fn builtin(sess: &Session, diagnostic: BuiltinLintDiagnostics, diag:
                 diag.span_label(span, format!("the item `{ident}` is already {introduced} here"));
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/context/diagnostics.rs:114]: I think we just need to say
```rust
"the item `{ident}` is already {introduced} by prelude"
```
if the `span` is dummy and cannot be meaningfully used for a label.

File: tests/ui/imports/redundant-import-issue-121915.rs [hunk 3]
```diff
@@ -0,0 +1,12 @@
+//@ revisions: edition2018 edition2021
+//@ [edition2018] edition:2018
+//@ [edition2021] edition:2021
```
Comment (petrochenkov) [inline tests/ui/imports/redundant-import-issue-121915.rs:3]: Any specific reason to test this on both editions?
2018 and 2021 are identical with regards to name resolution (unlike 2015).

File: compiler/rustc_resolve/src/imports.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:1370]: https://github.com/rust-lang/rust/pull/121958#discussion_r1511402323

**Comment by fmease** [comment]
I've closed the rollup PR, #121982, which included this PR. petrochenkov, in the future could you please immediately `r-` any correspoding rollup PRs to avoid merging outdated/`r-`'ed commits. Thanks!

File: compiler/rustc_resolve/src/imports.rs (hunk 1 above)
Comment (surechen) [reply compiler/rustc_resolve/src/imports.rs:1370]: Hi, I am also paying attention to this issue. This detection method may can't cover the situation for https://github.com/rust-lang/rust/issues/121315.

It would be great if both issues could be fixed in this PR.

**Comment by chenyukang** [comment]
@petrochenkov @surechen 
I updated the code and tests.

File: compiler/rustc_resolve/src/imports.rs [hunk 4]
```diff
@@ -1371,9 +1369,9 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             self.lint_buffer.buffer_lint_with_diagnostic(
                 UNUSED_IMPORTS,
                 id,
-                import.span,
+                import.use_span,
                 format!("the item `{source}` is imported redundantly"),
-                BuiltinLintDiag::RedundantImport(redundant_spans, source),
+                BuiltinLintDiag::RedundantImport(redundant_spans, source, import.use_span),
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:1374]: `import.use_span` cannot be used for removal in general case (e.g. if the redundant import in inside braces `use a::{b, c};`).

Ideally, the removal algorithm for usual unused imports from `fn check_unused` should be used, but otherwise maybe it can be approximated with `import.span/use_span/root_span` somehow.

File: compiler/rustc_resolve/src/imports.rs [hunk 5]
```diff
@@ -1371,9 +1369,9 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             self.lint_buffer.buffer_lint_with_diagnostic(
                 UNUSED_IMPORTS,
                 id,
-                import.span,
+                import.use_span,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:1372]: `import.span` was the right span to use here.

Comment (chenyukang) [reply compiler/rustc_resolve/src/imports.rs]: fixed.

File: compiler/rustc_resolve/src/imports.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/imports.rs]: Done with some code changes, I change `check_for_redundant_imports` to return spans, and add a new `ImportFinderVisitor` to find UseTree, and then use `calc_unused_spans` to fix spans.

File: tests/ui/imports/suggest-remove-issue-121315.rs [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+// Test remove NestedFullUnused
+use std::convert::{TryInto};
+//~^ ERROR the item `TryInto` is imported redundantly
+
+// Test remove NestedPartialUnused
+use std::convert::{From, Infallible};
+//~^ ERROR the item `From` is imported redundantly
+
+// Test remove both redundant and unused?
+// use std::convert::{AsMut, Into};
```
Comment (chenyukang) [inline tests/ui/imports/suggest-remove-issue-121315.rs:19]: The problem now is here, `AsMut` is an unused_import, `Into` is redundant_import, because we suggest removing at different places, there will be an error in rustfix: 

```
rustfix: Could not replace range 499...505 in file -- maybe parts of it were already replaced?
```

I will try to merge these different kinds of removing, so that `check_for_redundant_imports` will handle well for removing spans.

Comment (chenyukang) [reply tests/ui/imports/suggest-remove-issue-121315.rs:19]: @petrochenkov @surechen 
do you think is it a good direction to go?

Comment (chenyukang) [reply tests/ui/imports/suggest-remove-issue-121315.rs]: Done with commit https://github.com/rust-lang/rust/pull/121958/commits/300c184d2cf0139da2e54e6da4baa5432dd51f48

There are some test cases are failing, I need more cleanup on the labels.

How to show the labels if there are `AsMut` is `unused_import` and `Into` is `redundant_import `, they are all need to be removed: 
```rust
 use std::convert::{AsMut, Into};
```

😂

**Comment by petrochenkov** [comment]
I suggest landing all the changes except removal spans in a separate PR.

**Comment by chenyukang** [comment]
> #121915

Rollbacked to only fix #121915 now, will send another PR for #121315.

**Comment by chenyukang** [comment]
> I suggest landing all the changes except removal spans in a separate PR.

Rollbacked to only fix https://github.com/rust-lang/rust/issues/121915 now, will send another PR for https://github.com/rust-lang/rust/issues/121315.

**Comment by petrochenkov** [comment]
I see you kept the added tests, that's great.
@bors r+
