### PR TITLE
Consistently use subtyping in method resolution

### LINKED ISSUE #126062: ICE: `instantiate_value_path: (UFCS) Fail<T/#0> was a subtype of Fail<i32> but now is not?`
auto-reduced (treereduce-rust):
````rust
struct Fail<T>(Fail);
impl<T> Fail<i32> {
    const C: () = panic!();
}

fn f<T>() {
    if false {
        let _val = &Fail::<T>::C;
    }
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@revisions: noopt opt
//@ build-fail
//@[noopt] compile-flags: -Copt-level=0
//@[opt] compile-flags: -O
// (Not sure why optimizations lead to this being emitted twice, but as long as compilation
struct Fail<T>(Fail);
impl<T> Fail<i32> {
    const C: () = panic!(); //~ERROR evaluation of `Fail::<i32>::C` failed
    //[opt]~^ ERROR evaluation of `Fail::<T>::C` failed
    // (Not sure why optimizations lead to this being emitted twice, but as long as compilation
    // fails either way it's fine.)
}

#[panic(C)]
fn f<T>() {
    if false {
        // If promotion moved `C` from our required_consts to its own, without adding itself to
        // our required_consts, then we'd miss the const-eval failure here.
        let _val = &Fail::<T>::C;
    }
}

fn main() {
    if false {
        // If promotion moved `C` from our required_consts to its own, without adding itself to
        // our required_consts, then we'd miss the const-eval failure here.
        let _val = &Fail::<T>::C;
    }
}

````
</p>
</details>

Version information
````
rustc 1.80.0-nightly (72fdf913c 2024-06-05)
binary: rustc
commit-hash: 72fdf913c53dd0e75313ba83e4aa80df3f6e2871
commit-date: 2024-06-05
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:10:2
   |
10 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs`

error[E0107]: missing generics for struct `Fail`
 --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:1:16
  |
1 | struct Fail<T>(Fail);
  |                ^^^^ expected 1 generic argument
  |
note: struct defined here, with 1 generic parameter: `T`
 --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:1:8
  |
1 | struct Fail<T>(Fail);
  |        ^^^^ -
help: add missing generic argument
  |
1 | struct Fail<T>(Fail<T>);
  |                    +++

error[E0072]: recursive type `Fail` has infinite size
 --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:1:1
  |
1 | struct Fail<T>(Fail);
  | ^^^^^^^^^^^^^^ ---- recursive without indirection
  |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to break the cycle
  |
1 | struct Fail<T>(Box<Fail>);
  |                ++++    +

error[E0207]: the type parameter `T` is not constrained by the impl trait, self type, or predicates
 --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:2:6
  |
2 | impl<T> Fail<i32> {
  |      ^ unconstrained type parameter

error: internal compiler error: instantiate_value_path: (UFCS) Fail<T/#0> was a subtype of Fail<i32> but now is not?
 --> /tmp/icemaker_global_tempdir.0hca098Ozkau/rustc_testrunner_tmpdir_reporting.urLT6Xgm3pBR/mvce.rs:8:21
  |
8 |         let _val = &Fail::<T>::C;
  |                     ^^^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1419:32:
Box<dyn Any>
stack backtrace:
   0:     0x7ac91e1a6d45 - std::backtrace_rs::backtrace::libunwind::trace::hb2aae96f7a63ad27
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7ac91e1a6d45 - std::backtrace_rs::backtrace::trace_unsynchronized::h21f79cd140dff600
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ac91e1a6d45 - std::sys_common::backtrace::_print_fmt::hc8ebdc1b64ae52ee
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7ac91e1a6d45 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7ba491a968dfae1d
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ac91e1f74eb - core::fmt::rt::Argument::fmt::he322040f856802e1
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/rt.rs:165:63
   5:     0x7ac91e1f74eb - core::fmt::write::hb4f7da2a314ef133
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/mod.rs:1168:21
   6:     0x7ac91e19ba1f - std::io::Write::write_fmt::h9e79d11af9b4686b
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/io/mod.rs:1835:15
   7:     0x7ac91e1a6b1e - std::sys_common::backtrace::_print::h9276d72631ea2ebd
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ac91e1a6b1e - std::sys_common::backtrace::print::h301edb80f46c58f8
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ac91e1a9559 - std::panicking::default_hook::{{closure}}::h08c68fc043d12d43
  10:     0x7ac91e1a92fa - std::panicking::default_hook::hdf65558cafad5039
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:298:9
  11:     0x7ac91a97206f - std[6e8d71b68429f045]::panicking::update_hook::<alloc[5a6e81a1c85e3cc3]::boxed::Box<rustc_driver_impl[3b16240f18c6f62f]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7ac91e1a9c8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h69f90a497fd344b0
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2077:9
  13:     0x7ac91e1a9c8b - std::panicking::rust_panic_with_hook::h9576f09a7a058c94
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:799:13
  14:     0x7ac91a9a2bc4 - std[6e8d71b68429f045]::panicking::begin_panic::<rustc_errors[85e49f4302adcb2e]::ExplicitBug>::{closure#0}
  15:     0x7ac91a99f7c6 - std[6e8d71b68429f045]::sys_common::backtrace::__rust_end_short_backtrace::<std[6e8d71b68429f045]::panicking::begin_panic<rustc_errors[85e49f4302adcb2e]::ExplicitBug>::{closure#0}, !>
  16:     0x7ac91a99f4a6 - std[6e8d71b68429f045]::panicking::begin_panic::<rustc_errors[85e49f4302adcb2e]::ExplicitBug>
  17:     0x7ac91a9ac021 - <rustc_errors[85e49f4302adcb2e]::diagnostic::BugAbort as rustc_errors[85e49f4302adcb2e]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7ac91aaf9928 - <rustc_errors[85e49f4302adcb2e]::DiagCtxt>::span_bug::<rustc_span[94e0545083c6ac7f]::span_encoding::Span, alloc[5a6e81a1c85e3cc3]::string::String>
  19:     0x7ac91c106c8d - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::instantiate_value_path
  20:     0x7ac91c0fbf19 - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_path
  21:     0x7ac91c84188e - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:     0x7ac91c84436e - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:     0x7ac91c83c86b - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_decl
  24:     0x7ac91c83f181 - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_block_with_expected
  25:     0x7ac91c843bf2 - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7ac91c845c27 - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x7ac91c83e2cf - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_block_with_expected
  28:     0x7ac91c843bf2 - <rustc_hir_typeck[7d07483f08c89c92]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7ac91c12f417 - rustc_hir_typeck[7d07483f08c89c92]::check::check_fn
  30:     0x7ac91c125e89 - rustc_hir_typeck[7d07483f08c89c92]::typeck
  31:     0x7ac91c125907 - rustc_query_impl[1572c7dfdd517a64]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1572c7dfdd517a64]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[62e7a9badcda725c]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7ac91c1cf2b1 - rustc_query_system[dd7ca378a021eaaf]::query::plumbing::try_execute_query::<rustc_query_impl[1572c7dfdd517a64]::DynamicConfig<rustc_query_system[dd7ca378a021eaaf]::query::caches::VecCache<rustc_span[94e0545083c6ac7f]::def_id::LocalDefId, rustc_middle[62e7a9badcda725c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1572c7dfdd517a64]::plumbing::QueryCtxt, false>
  33:     0x7ac91c1cdfd5 - rustc_query_impl[1572c7dfdd517a64]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7ac91c1cdc0b - <rustc_middle[62e7a9badcda725c]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[f003d1007c3f00fd]::check_crate::{closure#4}>::{closure#0}
  35:     0x7ac91c1cc6c7 - rustc_hir_analysis[f003d1007c3f00fd]::check_crate
  36:     0x7ac91c409c3e - rustc_interface[8fb37091e3fd3ade]::passes::analysis
  37:     0x7ac91c40979b - rustc_query_impl[1572c7dfdd517a64]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1572c7dfdd517a64]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[62e7a9badcda725c]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7ac91cbaa725 - rustc_query_system[dd7ca378a021eaaf]::query::plumbing::try_execute_query::<rustc_query_impl[1572c7dfdd517a64]::DynamicConfig<rustc_query_system[dd7ca378a021eaaf]::query::caches::SingleCache<rustc_middle[62e7a9badcda725c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1572c7dfdd517a64]::plumbing::QueryCtxt, false>
  39:     0x7ac91cbaa48f - rustc_query_impl[1572c7dfdd517a64]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7ac91c9f1612 - rustc_interface[8fb37091e3fd3ade]::interface::run_compiler::<core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>, rustc_driver_impl[3b16240f18c6f62f]::run_compiler::{closure#0}>::{closure#1}
  41:     0x7ac91c9cf489 - std[6e8d71b68429f045]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8fb37091e3fd3ade]::util::run_in_thread_with_globals<rustc_interface[8fb37091e3fd3ade]::util::run_in_thread_pool_with_globals<rustc_interface[8fb37091e3fd3ade]::interface::run_compiler<core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>, rustc_driver_impl[3b16240f18c6f62f]::run_compiler::{closure#0}>::{closure#1}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>::{closure#0}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>
  42:     0x7ac91c9cf23c - <<std[6e8d71b68429f045]::thread::Builder>::spawn_unchecked_<rustc_interface[8fb37091e3fd3ade]::util::run_in_thread_with_globals<rustc_interface[8fb37091e3fd3ade]::util::run_in_thread_pool_with_globals<rustc_interface[8fb37091e3fd3ade]::interface::run_compiler<core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>, rustc_driver_impl[3b16240f18c6f62f]::run_compiler::{closure#0}>::{closure#1}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>::{closure#0}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[31c46ae728976beb]::result::Result<(), rustc_span[94e0545083c6ac7f]::ErrorGuaranteed>>::{closure#2} as core[31c46ae728976beb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7ac91e1b3c7b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd9d8a12a4cec8653
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2063:9
  44:     0x7ac91e1b3c7b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc87e6ebe32d18c90
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2063:9
  45:     0x7ac91e1b3c7b - std::sys::pal::unix::thread::Thread::new::thread_start::h68df5163d04f9130
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys/pal/unix/thread.rs:108:17
  46:     0x7ac9176a6ded - <unknown>
  47:     0x7ac91772a0dc - <unknown>
  48:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (72fdf913c 2024-06-05) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `f`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0072, E0107, E0207, E0601.
For more information about an error, try `rustc --explain E0072`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #126062

An earlier version of this PR modified how we compute variance, but the root cause was an inconsistency between the usage of `eq` and `sub`, where we assumed that the latter passing implies the former will pass.

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_type_ir/src/lib.rs [hunk 1]
```diff
@@ -273,6 +284,7 @@ impl fmt::Debug for Variance {
             Variance::Contravariant => "-",
             Variance::Invariant => "o",
             Variance::Bivariant => "*",
+            Variance::Errvariant(_) => "💥",
```
Comment (compiler-errors) [inline compiler/rustc_type_ir/src/lib.rs:287]: Can we not use emojis in the compiler? It's really awkward and impossible to type.

Comment (compiler-errors) [reply compiler/rustc_type_ir/src/lib.rs:287]: This reminds me of how awkward it was to use that 🔬 file extension in a-mir-formality. I think it's cute, but please let's don't 😓

Comment (oli-obk) [reply compiler/rustc_type_ir/src/lib.rs:287]: Oh right, we need to type it in diagnostic patterns

**Comment by compiler-errors** [comment]
I don't personally feel comfortable about adding a new error variance. Seems really strange imo.

I think we could easily just force the error variance to `Invariant` rather than `Bivariant`, which would prevent these ICEs at risk of slightly more awkward errors, but at the benefit having it be its own thing that actually need to be handled in relations.

r? lcnr

**Comment by compiler-errors** [comment]
More thoughts:

So the underlying issue is the inconsistency we have with the xform, where:

* invariant xform bivariant = invariant
* covariant xform bivariant = bivariant

... and the fact we're using equality during method lookup and subtyping during confirmation, leading to a mismatch in the result of those relations.

This seems like a kind of roundabout way of fixing this, since the real underlying issue is that the way we handle bivariance in the compiler is just kind of awkward.

Not to repeat myself, but I think forcing invariance would just fix things in a simpler way.

**Comment by oli-obk** [comment]
> Not to repeat myself, but I think forcing invariance would just fix things in a simpler way.

done

**Comment by compiler-errors** [comment]
OK -- will review this then. Thanks for considering my feedback.

 If lcnr strongly disagrees about forcing invariance, then it shouldn't be hard to do a follow-up and actually introduce the error variance later.

r? compiler-errors

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 2]
```diff
@@ -1880,18 +1880,20 @@ pub fn check_variances_for_type_defn<'tcx>(
...
+                }
             }
-        }
+        };
+        let mut v = variances.to_vec();
+        v[index] = ty::Invariant;
+        variances = tcx.arena.alloc_slice(&v);
     }
-    res
+    Ok(variances)
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1896]: Does this function ever return `Err`?

Unless I'm being particularly unobservant, maybe let's rename this fn to `check_variances_for_type_defn_and_set_unconstrained_to_invariant`

(long name but there's only a few callsites -- happy to workshop the name lol

File: compiler/rustc_hir_analysis/src/variance/mod.rs [hunk 3]
```diff
@@ -72,8 +72,10 @@ fn variances_of(tcx: TyCtxt<'_>, item_def_id: LocalDefId) -> &[ty::Variance] {
         }
     };
 
-    let _ = crate::check::wfcheck::check_variances_for_type_defn(tcx, item_def_id, variances);
-    variances
+    match crate::check::wfcheck::check_variances_for_type_defn(tcx, item_def_id, variances) {
+        Ok(variances) => variances,
+        Err(_) => tcx.arena.alloc_from_iter(variances.iter().map(|_| ty::Invariant)),
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/variance/mod.rs:77]: This branch is unreachable rn

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 4]
```diff
@@ -308,21 +308,12 @@ fn check_item<'tcx>(tcx: TyCtxt<'tcx>, item: &'tcx hir::Item<'tcx>) -> Result<()
...
-            let res = check_type_defn(tcx, item, true);
-            check_variances_for_type_defn(tcx, item, hir_generics);
-            res
-        }
-        hir::ItemKind::Enum(_, hir_generics) => {
-            let res = check_type_defn(tcx, item, true);
-            check_variances_for_type_defn(tcx, item, hir_generics);
-            res
-        }
+        hir::ItemKind::Struct(_, hir_generics) => check_type_defn(tcx, item, false)
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs]: can we use `?` like:

```
check_type_defn()?;
check_variances_for_type_defn()?;
```

then at the bottom we can `Ok(())`?

Seems to simplify control flow a bit

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:1896]: edit: nvm I guess lol

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 5]
```diff
@@ -1813,25 +1803,21 @@ fn check_variances_for_type_defn<'tcx>(
...
+) -> Result<(), ErrorGuaranteed> {
     let identity_args = ty::GenericArgs::identity_for_item(tcx, item.owner_id);
 
     match item.kind {
         ItemKind::Enum(..) | ItemKind::Struct(..) | ItemKind::Union(..) => {
             for field in tcx.adt_def(item.owner_id).all_fields() {
-                if field.ty(tcx, identity_args).references_error() {
-                    return;
-                }
+                field.ty(tcx, identity_args).error_reported()?;
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1812]: I wonder if we should just use `error_reported` to delay the error message below *but* don't early-return (using `emit_unless`). I kinda feel bad that we're setting *all* of the substs to bivariant even if they are constrained otherwise (e.g. to covariance) somewhere else in the definition.

**Review by compiler-errors — COMMENTED** [review]
some random thoughts -- pls forgive me for commenting on things that were modified subsequently in a follow-up commit lol

File: compiler/rustc_hir_analysis/src/variance/mod.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/variance/mod.rs:77]: nvm

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs]: nvm this is irrelevant

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:1812]: Yea, these early aborts were preexisting. I didn't want to touch them in the previously-big PR (I'm assuming they got added to avoid ICEs), but now it's reasonable to investigate.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:1896]: I could return a vec of erroneous indices instead of doing the modification and the checks. Seems cleaner to separate these things

**Comment by lcnr** [comment]
> More thoughts:
> 
> So the underlying issue is the inconsistency we have with the xform implementation, where:
> 
>     * invariant xform bivariant = invariant
> 
>     * covariant xform bivariant = bivariant
> 
> 
> ... and the fact we're using equality during method lookup and subtyping during confirmation, leading to a mismatch in the result of those relations.

We get subtyping to succeed and equate to fail and that causes an ICE because we expect "subtype implies equal"? The underlying issue is just that, isn't it? We have types which are subtypes of each other but not equal. Apart from variance this is also the case with the leak check. This can't currently trigger as we just put the nested obligations in the `FnCtxt` without trying them, even in the new solver, but if we were to eagerly compute nested obligations, the following test would ICE https://rust.godbolt.org/z/KxGeqevaW.

I also don't see how this PR fixes the underlying issue with bivariance:

```rust
trait Proj {
    type Assoc;
}
impl<T> Proj for T {
    type Assoc = T;
}


struct Fail<T: Proj<Assoc = U>, U>(T);

impl Fail<i32, i32> {
    const C: () = ();
}

fn main() {
    Fail::<i32, u32>::C
}
```

**Comment by oli-obk** [comment]
> We get subtyping to succeed and equate to fail and that causes an ICE because we expect "subtype implies equal"? The underlying issue is just that, isn't it?

yes, but I did not want to touch that behaviour, because I really can't tell the implications. Almost nothing should be affected, because we already generate fresh inference vars during method resolution, so all we're doing is constraining inference vars that have no other constraints.

I did the change (see latest force push), and the only affected test is never type fallback, which checks with my analysis above.

File: tests/ui/coercion/coerce-issue-49593-box-never.rs [hunk 6]
```diff
@@ -15,8 +14,10 @@ fn raw_ptr_box<T>(t: T) -> *mut T {
 }
 
 fn foo(x: !) -> Box<dyn Error> {
-    /* *mut $0 is coerced to Box<dyn Error> here */ Box::<_ /* ! */>::new(x)
-    //[nofallback]~^ ERROR trait bound `(): std::error::Error` is not satisfied
+    // Subtyping during method resolution will generate new inference vars and
+    // subtype them. Thus fallback will not fall back to `!`, but `()` instead.
+    Box::<_ /* ! */>::new(x)
```
Comment (lcnr) [inline tests/ui/coercion/coerce-issue-49593-box-never.rs:19]: why this change?

**Comment by lcnr** [comment]
> yes, but I did not want to touch that behaviour, because I really can't tell the implications. 

I think non-method calls should use `eq` instead of `sub` everywhere :thinking: it seems surprising that `Type::<Subtype>::CONST` works? though i'd like @compiler-errors input on that

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/pull/122317 switched from eq to subtyping

**Comment by lcnr** [comment]
oh well, that's ugly :thinking: 

```rust
struct B<T>(T);

impl B<fn(&'static ())> {
    fn method(self) {
        println!("hey");
    }
}

fn foo(x: B<for<'a> fn(&'a ())>) {
    x.method();
}

fn main() {
    B::<for<'a> fn(&'a ())>::method(B(|&()| ()));
}
```
i expected us to only use subtyping when looking up the self type, not when using a path :thinking: that's kinda meh. But yeah, I guess `sub` is fine here, opening an issue as I would like to try and change that

File: tests/ui/coercion/coerce-issue-49593-box-never.rs (hunk 6 above)
Comment (oli-obk) [reply tests/ui/coercion/coerce-issue-49593-box-never.rs:19]: Instead of merging the two infer vars, we now create a subtyping relation for them, so they aren't the same. Never type fallback will still fall back to `!` for the one type var, but the other type var which is a subtype, will only fall back to `()`. I haven't debugged this deeply, since never type fallback is cursed and debugging it will probably yield no new information beyond all the edge cases that already are know for never type fallback.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 7]
```diff
@@ -1417,10 +1414,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             let self_ty = self.normalize(span, self_ty);
-            match self.at(&self.misc(span), self.param_env).eq(
+            match self.at(&self.misc(span), self.param_env).sub(
                 DefineOpaqueTypes::Yes,
-                impl_ty,
                 self_ty,
+                impl_ty,
             ) {
                 Ok(ok) => self.register_infer_ok_obligations(ok),
                 Err(_) => {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1423]: can this be a `bug!` now?

File: tests/ui/coercion/coerce-issue-49593-box-never.rs (hunk 6 above)
Comment (lcnr) [reply tests/ui/coercion/coerce-issue-49593-box-never.rs:19]: oh lel, you didn't change the UI test, you just reformatted it

**Review by lcnr — COMMENTED** [review]
r=me after final nit

**Comment by lcnr** [comment]
also, please update this PR description + title before merging it

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 7 above)
Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1423]: it is
