### PR TITLE
Do not allow a module and tuple struct of the same name to coexist.

### LINKED ISSUE #21546: Inconsistent symbol duplication checking
This compiles:
```rust
mod Foo {}
struct Foo;

fn main() {}
```
but this doesn't:
```rust
mod Foo {}
struct Bar;
type Foo = Bar;

fn main() {}
```

```
<anon>:3:1: 3:16 error: duplicate definition of type or module `Foo`
<anon>:3 type Foo = Bar;
         ^~~~~~~~~~~~~~~
<anon>:1:1: 1:11 note: first definition of type or module `Foo` here
<anon>:1 mod Foo {}
         ^~~~~~~~~~
```
  
I'd have expected both to either succeed or fail.

### PR DESCRIPTION
**Pull request by nham**
Fixes #21546.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is unfortunately a breaking change, so we need to be sure to tread carefully here (especially in resolve).

cc @rust-lang/lang, @nrc, I forget if cases like this were intentional or not?
cc @brson, perhaps a crater run to see if this causes compiles to fail?

**Comment by brson** [comment]
I've started this on crater.

File: src/test/compile-fail/issue-21546.rs [hunk 1]
```diff
@@ -8,8 +8,14 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+// Also works as a test for #14564
+
 mod Foo { }
+//~^ NOTE first definition of type or module
+
 struct Foo;
+//~^ ERROR duplicate definition of type or module `Foo`
```
Comment (pnkfelix) [inline src/test/compile-fail/issue-21546.rs]: given that [RFC 218] ("empty struct with braces") was accepted, it would probably be a good idea to have both this test and a separate one of non-empty tuple structs, since I expect the code paths for how the two are handled to diverge somewhat in the future.

[RFC 218]: https://github.com/rust-lang/rfcs/blob/master/text/0218-empty-struct-with-braces.md

**Comment by pnkfelix** [comment]
@alexcrichton asked:
> cc @rust-lang/lang, @nrc, I forget if cases like this were intentional or not?

I'm pretty sure this was an oversight.  Every kind of struct definition puts an entry into the type namespace (while only some put an entry into the value namespace, but this is not relevant).  The collision at the type namespace level is what is problematic.

In other words, this errors today:
```rust
mod Foo {}
struct Foo { x: i32 }

fn main() {}
```

so there's no reason for these to be succeeding:
```rust
mod Foo {}
struct Foo(i32);

fn main() {}
```
and
```rust
mod Foo {}
struct Foo;

fn main() {}
```

**Comment by pnkfelix** [comment]
Here is a more concrete example of a problematic program this bug is exposing:

```rust
#[allow(non_snake_case)]
mod Foo { pub fn foo() -> i32 { 4 } }

struct Foo(i32);
impl Foo { fn foo() -> i32 { 3 } }

fn main() { println!("foo: {}", Foo::foo()); } // what does this print?
```

**Comment by pnkfelix** [comment]
Having said that, its not a soundness issue to my knowledge.

Fixing it would not break code that is following "usual" style conventions about struct and module names, but otherwise it is indeed a breaking change.

Does it qualify as a course correction, or just a bug fix?  We could certainly employ the `#[legacy(...)]` flag idea here, I would imagine.

File: src/test/compile-fail/issue-21546.rs (hunk 1 above)
Comment (nham) [inline src/test/compile-fail/issue-21546.rs]: done

**Comment by nrc** [comment]
This was not intentional. I think it is definitely a bug fix, not a course correction or 'proper' breaking change.

**Comment by brson** [comment]
[crater says no regressions](https://gist.github.com/brson/ec673b67ef197bcadea3)

**Comment by alexcrichton** [comment]
Tagging with T-lang and I-nominated, just getting some broader visibility (and will be dealt with during triage)

**Comment by pnkfelix** [comment]
Similarly to #27026 (which was specifically mentioned during the last lang team meeting, where the response was "warning cycle first, then release the breaking change"), I am again wondering whether this needs to go through a warning cycle or not.

I interpret @nrc  above as saying "no, it does not need a warning cycle."  But if that is the case, then why apply a different policy to #27026  ?  Are these two cases all that different?

cc @rust-lang/lang

**Comment by nrc** [comment]
I think it could (and probably should) get a warning cycle. I don't think it should get a legacy flag or anything more permanent than a warning cycle.

**Comment by nham** [comment]
So under this policy, does the change in https://github.com/rust-lang/rust/pull/25993 need to be reverted and have a warning cycle added? The following program used to compile pre-patch, but does not after:

```rust
trait Foo {
    type Ty;
}

impl Foo for () {
    type Ty = ();
    type Ty = usize;
}

fn main() { 
    let _: <() as Foo>::Ty = ();
}
```

**Comment by nikomatsakis** [comment]
Triage: removing I-nominated as we've taken a look. Seems like a warning cycle makes sense, given how widely used tuple structs and modules are. With respect to #25993, I think we can let that go --- istm that overlap there is less likely, and of course we'll see if crater picks up anything.

**Comment by alexcrichton** [comment]
ping? @nham would you be ok implementing a warning for this change?

**Comment by pnkfelix** [comment]
Re assigning to myself, I will try to revise with warning cycle support if we see no response from @nham

**Comment by nham** [comment]
Sorry, I've been busy the past couple of weeks. I have some time to look at it this week, but I still need to figure out how the warning cycles work, so if you want to take it @pnkfelix that's okay with me.

**Comment by pnkfelix** [comment]
@nham oh I have plenty of other stuff on my plate, so you've got time to look at it this week if you like.  :)

**Comment by nham** [comment]
I've made an attempt at adding warnings. The warnings address both the original issue and another issue mentioned by @james-darkfox in #29185, which is that programs like this currently compile:

```rust
struct Foo { x: i32 }
mod Foo { }
fn main() {}
```

This is a separate issue because it is allowed only when the module comes after the struct, and also because it works for all structs, not just unit/tuple structs.

**Comment by james-darkfox** [comment]
@nham Sidenote: I'm "abusing" this bug in #29182 due to a limitation in the test cases. Here in the module I have my `#[test] fn ...`. My point here is that although this is a bug, it is a useful one until the `#[test]` cases can be implemented in `impl` blocks.

File: src/librustc_resolve/build_reduced_graph.rs [hunk 2]
```diff
@@ -404,6 +404,29 @@ impl<'a, 'b:'a, 'tcx:'b> GraphBuilder<'a, 'b, 'tcx> {
             }
 
             ItemMod(..) => {
+                let child = parent.children.borrow().get(&name).cloned();
```
Comment (pnkfelix) [inline src/librustc_resolve/build_reduced_graph.rs]: Seems a shame to clone the child; I would have thought there was a way to structure this to avoid that.

File: src/librustc_resolve/build_reduced_graph.rs [hunk 3]
```diff
@@ -495,6 +518,28 @@ impl<'a, 'b:'a, 'tcx:'b> GraphBuilder<'a, 'b, 'tcx> {
                 let (forbid, ctor_id) = if struct_def.is_struct() {
                     (ForbidDuplicateTypesAndModules, None)
                 } else {
+                    let child = parent.children.borrow().get(&name).cloned();
+                    if let Some(child) = child {
+                        // check if theres a DefMod
+                        if let Some(DefMod(_)) = child.def_for_namespace(TypeNS) {
+                            self.session.span_warn(sp, &format!(
```
Comment (pnkfelix) [inline src/librustc_resolve/build_reduced_graph.rs]: should we consider allocating a error number now for this?

I guess it can wait until we promote the warning into a proper error, since I don't know if our error number policy would allow us to reuse the same number for the warning and the error it is later promoted into.

**Comment by pnkfelix** [comment]
@nham this looks fine to me, apart from the clone, which I assume you tried to avoid and I must just be missing some reason why it didn't work.
