### PR TITLE
Reduce `Box::default` stack copies in debug mode

### LINKED ISSUE #136043: Crash writing PNG from a C++ background thread on macOS Rust 1.84.0
I'm writing PNG files from a C++ background thread. It used to work on Rust stable 1.83.0, but it crashes on Rust stable 1.84.0 and nightly. I'm using the `png` crate, but it or its dependencies [shouldn't have any code](https://github.com/Frommi/miniz_oxide/issues/160), which would cause the crash.

The crash happens on macOS and Rust 1.84.0 (I tested on arm and intel macs). The program runs without issues on Ubuntu linux Rust 1.84.0. I didn't test Windows. There are no issues writing PNGs from the C++ main thread, but PNG writing crashes on the C++ background thread. If I write the same program in pure Rust without ffi and using Rust threads, then everything works without issues.

Could this be a regression in the Rust standard library? Or is the Rust function called from the C++ background thread in a way that is incompatible with Rust 1.84.0?

### Code

Here's a minimal example project as a zip file so that you can see the code and try it yourself:  [test-cthread-png.zip](https://github.com/user-attachments/files/18545493/test-cthread-png.zip)

I expected to see this happen: Two PNG files should be written to the current folder: 'out-png-1.png' and 'out-png-2.png'

Instead, this happened: Only one PNG file is written: 'out-png-1.png' (on the main thread) and then the program crashes:

```
Rust PNG writing to 'out-png-1.png'
Waiting thread to finish..
Rust PNG writing to 'out-png-2.png'
zsh: bus error  ./main
```

### Version it worked on

It most recently worked on: Rust 1.83

### Version with regression

`rustc --version --verbose`:
```
rustc 1.84.0 (9fc6b4312 2025-01-07)
binary: rustc
commit-hash: 9fc6b43126469e3858e2fe86cafb4f0fd5068869
commit-date: 2025-01-07
host: aarch64-apple-darwin
release: 1.84.0
LLVM version: 19.1.5
```

### LLVM Stack Trace

<details><summary>Stack trace of the example project</summary>
<p>

```
Process 62208 launched: '/Users/temp/rust/test-cthread-png/main' (arm64)
Rust PNG writing to 'out-png-1.png'
Waiting thread to finish..
Rust PNG writing to 'out-png-2.png'
Process 62208 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=2, address=0x16fe036b0)
    frame #0: 0x000000010005a334 main`alloc::boxed::Box$LT$core..mem..maybe_uninit..MaybeUninit$LT$T$GT$$C$A$GT$::write::hf0470a3673d75fd5(boxed=0x0000000000000000, value=<unavailable>) at boxed.rs:1008
   1005	    /// ```
   1006	    #[unstable(feature = "box_uninit_write", issue = "129397")]
   1007	    #[inline]
-> 1008	    pub fn write(mut boxed: Self, value: T) -> Box<T, A> {
   1009	        unsafe {
   1010	            (*boxed).write(value);
   1011	            boxed.assume_init()
Target 0: (main) stopped.

(lldb) thread backtrace
* thread #2, stop reason = EXC_BAD_ACCESS (code=2, address=0x16fe036b0)
  * frame #0: 0x000000010005a334 main`alloc::boxed::Box$LT$core..mem..maybe_uninit..MaybeUninit$LT$T$GT$$C$A$GT$::write::hf0470a3673d75fd5(boxed=0x0000000000000000, value=<unavailable>) at boxed.rs:1008
    frame #1: 0x000000010005a540 main`_$LT$alloc..boxed..Box$LT$T$GT$$u20$as$u20$core..default..Default$GT$::default::h770abf79bd18dfcf at boxed.rs:1733:9
    frame #2: 0x0000000100045818 main`miniz_oxide::deflate::core::DictOxide::new::hf9b523780f33e231(flags=4112) at core.rs:1156:16
    frame #3: 0x000000010004116c main`_$LT$miniz_oxide..deflate..core..CompressorOxide$u20$as$u20$core..default..Default$GT$::default::h98fdbfee01692241 at core.rs:436:19
    frame #4: 0x000000010003dea8 main`_$LT$alloc..boxed..Box$LT$T$GT$$u20$as$u20$core..default..Default$GT$::default::h89b44e0f0b402adf at boxed.rs:1733:39
    frame #5: 0x000000010003ecc8 main`_$LT$flate2..ffi..rust..Deflate$u20$as$u20$flate2..ffi..DeflateBackend$GT$::make::hee247c1da637a407(level=(__0 = 6), zlib_header=true, _window_bits='\x0f') at rust.rs:131:47
    frame #6: 0x000000010003fc8c main`flate2::mem::Compress::new::h1c4d10d7643a257f(level=(__0 = 6), zlib_header=true) at mem.rs:197:20
    frame #7: 0x000000010002d1dc main`flate2::zlib::write::ZlibEncoder$LT$W$GT$::new::h9b8a7495719a8ece(w=Vec<u8, alloc::alloc::Global> @ 0x000000016fe863a8, level=(__0 = 6)) at write.rs:43:40
    frame #8: 0x000000010000c398 main`png::encoder::Writer$LT$W$GT$::write_image_data::h1a6cf982c65de46c(self=0x000000016fe86b98, data=(data_ptr = "", length = 307200)) at encoder.rs:742:32
    frame #9: 0x000000010000b99c main`rspng_write(filenumber='\x02') at lib.rs:20:8
    frame #10: 0x00000001000022fc main`MyThread::run(this=0x000000016fdff32b) at main.cpp:9:13
    frame #11: 0x0000000100002e54 main`decltype(*std::declval<MyThread*>().*std::declval<void (MyThread::*)()>()()) std::__1::__invoke[abi:ne180100]<void (MyThread::*)(), MyThread*, void>(__f=0x0000600002b940c8, __a0=0x0000600002b940d8) at invoke.h:312:25
    frame #12: 0x0000000100002d84 main`void std::__1::__thread_execute[abi:ne180100]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (MyThread::*)(), MyThread*, 2ul>(__t=size=3, (null)=__tuple_indices<2UL> @ 0x000000016fe86f7f) at thread.h:199:3
    frame #13: 0x0000000100002680 main`void* std::__1::__thread_proxy[abi:ne180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (MyThread::*)(), MyThread*>>(__vp=0x0000600002b940c0) at thread.h:208:3
    frame #14: 0x0000000188b272e4 libsystem_pthread.dylib`_pthread_start + 136
(lldb)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jwong101**
The `Box::new(T::default())` implementation of `Box::default` only
had two stack copies in debug mode, compared to the current version,
which has four. By avoiding creating any `MaybeUninit<T>`'s and just writing
`T` directly to the `Box` pointer, the stack usage in debug mode remains
the same as the old version.

Another option would be to mark `Box::write` as `#[inline(always)]`,
and change it's implementation to to avoid calling `MaybeUninit::write`
(which creates a `MaybeUninit<T>` on the stack) and to use `ptr::write` instead.

Fixes: #136043

### CODE REVIEW

File: library/alloc/src/boxed.rs [hunk 1]
```diff
@@ -1730,7 +1730,20 @@ impl<T: Default> Default for Box<T> {
...
+        unsafe {
+            // SAFETY: `x` is valid for writing and has the same layout as `T`.
+            // If `T::default()` panics, dropping `x` will just deallocate the Box as `MaybeUninit<T>`
+            // does not have a destructor.
+            //
+            // We use `ptr::write` as `MaybeUninit::write` creates
+            // extra stack copies of `T` in debug mode.
+            //
+            // See https://github.com/rust-lang/rust/issues/136043 for more context.
+            ptr::write(&raw mut *x as *mut T, T::default());
```
Comment (Amanieu) [inline library/alloc/src/boxed.rs:1743]: Doesn't the stack frame of `ptr::write` also involve a stack allocation since it takes the argument by value? A more robust solution would be to use `copy_nonoverlapping` from the local in `Box::default` directly to the heap.

Comment (jwong101) [reply library/alloc/src/boxed.rs:1743]: > Doesn't the stack frame of `ptr::write` also involve a stack allocation since it takes the argument by value?

From what I've observed, `ptr::write` doesn't actually create a new alloca, and essentially just calls `memcpy` directly on the argument(assuming the argument is passed is big enough and not something like a usize). [Godbolt](https://rust.godbolt.org/z/ErYPKzrqq). Let me check how we lower the `ptr::write` intrinsic to make sure of this though.

> A more robust solution would be to use copy_nonoverlapping from the local in Box::default directly to the heap.

Unfortunately, we need to also `mem::forget` the actual value after copying it, or create a `ManuallyDrop<T>`. The `mem::forget` copy doesn't appear to be eliminated in debug mode, and `ManuallyDrop::<T>::default()` call copies `T::default` to an additional alloca on its stack frame. I created two additional functions in the Godbolt link to showcase this codegen behavior.

**Comment by jwong101** [comment]
I was looking into where we do the optimization of not creating an alloca in `ptr::write`'s stack frame in debug mode, and I found something weird.

Given the following code:

```rust
const NUM: usize = 1000000;

// Thing is not `Copy`, but has no drop glue
pub struct Thing([u8; NUM]);

#[no_mangle]
pub fn src(move_thing: fn(Thing), capture_arg: fn(&Thing), maybe_use_both: fn(), y: Thing) {
    capture_arg(&y);
    move_thing(y);
    maybe_use_y();
}
```

There's no alloca created in debug mode:

```llvm
define void @src(ptr %move_thing, ptr %capture_arg, ptr %maybe_use_both, ptr align 1 %y) unnamed_addr {
start:
  %maybe_use_both.dbg.spill = alloca [8 x i8], align 8
  %capture_arg.dbg.spill = alloca [8 x i8], align 8
  %move_thing.dbg.spill = alloca [8 x i8], align 8
  store ptr %move_thing, ptr %move_thing.dbg.spill, align 8
  store ptr %capture_arg, ptr %capture_arg.dbg.spill, align 8
  store ptr %maybe_use_both, ptr %maybe_use_both.dbg.spill, align 8
  call void %capture_arg(ptr align 1 %y)
  call void %move_thing(ptr align 1 %y)
  call void %maybe_use_y()
  ret void
}
```

However, there is an alloca in Release mode:

```llvm
define void @src(ptr nocapture noundef nonnull readonly %move_thing, ptr nocapture noundef nonnull readonly %capture_arg, ptr nocapture noundef nonnull readonly %maybe_use_both, ptr noalias nocapture noundef readonly align 1 dereferenceable(1000000) %y) unnamed_addr {
start:
  %0 = alloca [1000000 x i8], align 1
  tail call void %capture_arg(ptr noalias noundef nonnull readonly align 1 dereferenceable(1000000) %y)
  call void @llvm.lifetime.start.p0(i64 1000000, ptr nonnull %0)
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(1000000) %0, ptr noundef nonnull align 1 dereferenceable(1000000) %y, i64 1000000, i1 false)
  call void %move_thing(ptr noalias nocapture noundef nonnull align 1 dereferenceable(1000000) %0)
  call void @llvm.lifetime.end.p0(i64 1000000, ptr nonnull %0)
  tail call void %maybe_use_y()
  ret void
}
```

I haven't been keeping up with Rust's opsem, however, the last time I checked, the legality[^1] of this was unresolved as per https://github.com/rust-lang/unsafe-code-guidelines/issues/416 and https://github.com/rust-lang/unsafe-code-guidelines/issues/188.

cc @saethlin since you're already in this thread and I think this is in your area of expertise

[^1]: Personally, I think that moving out of a local/argument should invalidate all previous borrows, unless there's a bunch of unsafe code that this breaks.

**Comment by saethlin** [comment]
I don't follow your reasoning. You're looking at LLVM IR and trying to reason about MIR semantics, and that is not going to go well. The relevant MIR optimization that changes how arguments are passed is GVN, which turns a Move operand into a Copy operand: https://godbolt.org/z/sEWz399Mj

I also don't think this discussion belongs on this PR, if you want to ask opsem questions you should go to the Zulip.
