### PR TITLE
More suggestion for converting `Option<&Vec<T>>` to `Option<&[T]>`

### LINKED ISSUE #127545: Improve compile errors for type mismatch when encoutering `unwrap_or`
Given [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7aa9ddf279169346dc73a1a1f4a84d43):
```rust
use std::collections::HashMap;

pub fn get(index: &HashMap<usize, Vec<i32>>, id: usize) -> &[i32] {
    index.get(&id).unwrap_or(&[])
}
```

Current error, for the motivating use case above:

```console
error[E0308]: mismatched types
   --> src/lib.rs:5:30
    |
5   |     index.get(&id).unwrap_or(&[])
    |                    --------- ^^^ expected `&Vec<i32>`, found `&[_; 0]`
    |                    |
    |                    arguments to this method are incorrect
    |
    = note: expected reference `&Vec<i32>`
               found reference `&[_; 0]`
help: the return type of this call is `&[_; 0]` due to the type of the argument passed
   --> src/lib.rs:5:5
    |
5   |     index.get(&id).unwrap_or(&[])
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^---^
    |                              |
    |                              this argument influences the return type of `unwrap_or`
```

It should be possible for rustc to suggest replacing this specific instantiation of `unwrap_or` with `map_or(&[], Vec::as_slice)`. Maybe similarly for some other common cases: `map_or("", String::as_str)`.

_Originally posted by `@dtolnay` in https://github.com/rust-lang/libs-team/issues/407#issuecomment-2218677110_

@rustbot label -T-rustdoc T-compiler

### PR DESCRIPTION
**Pull request by tesuji**
Please review commit-by-commit.

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
This PR implements two basically unrelated suggestions. Could you please split it into two PRs?

My opinion about these two suggestions are split. I think the first suggestion is fine and we can land it (8acf2e408dc8afe0ced20808fa7f39acad0e1916), but the second (7e719c9e4ba697e064a7fbf21288cdf543e94a33) seems somewhat invasive and also really specific, to the point that I don't think we should land it. Putting a new suggestion right into the middle of the argument checking logic seems like the wrong thing to do IMO, and I don't know if there's an easier way to do it.

**Comment by tesuji** [comment]
Alright, I'll split this PR into 2 parts. 

About:
> the second (https://github.com/rust-lang/rust/commit/7e719c9e4ba697e064a7fbf21288cdf543e94a33) seems somewhat invasive and also really specific, to the point that I don't think we should land it. 

I mean people prefer using `Option::unwrap_or` over manually matching seem to be benefit from this suggest.

> Putting a new suggestion right into the middle of the argument checking logic seems like the wrong thing to do IMO

I don't understand what it means. That change add a new suggestion in `fn report_arg_errors` 
https://github.com/rust-lang/rust/blob/bcf1f6db4594ae6132378b179a30cdb3599a863d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L482
and it is laid after `suggest_ptr_null_mut`, which is also a suggestion:
https://github.com/rust-lang/rust/blob/bcf1f6db4594ae6132378b179a30cdb3599a863d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L944-L949

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -466,21 +466,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                err.subdiagnostic(errors::SuggestConvertViaMethod {
-                    span: expr.span.shrink_to_hi(),
-                    sugg,
-                    expected,
-                    found,
-                    borrow_removal_span,
-                });
-                return true;
-            } else if let ty::Adt(adt, _) = found_ty_inner.peel_refs().kind()
+            } else if let ty::Ref(_, peeled_found_ty, _) = found_ty_inner.kind()
```
Comment (tesuji) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:469]: This change is necessary. Because suggesting `Option<String>.map(|v| v.as_str())` is violating ownership rules.
