### PR TITLE
On unresolved imports, suggest a disambiguated path if necessary to avoid collision with local items

### LINKED ISSUE #116970: Rustc suggests the same `use` statement that caused the error when two  modules share their name
### Code

I tried to reproduce the problem in the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1827c057d0c91fded0e903aaa969ec9a)
```rust
mod a {
    pub mod log {
        pub struct S {}
    }
}

use a::log::{self};

use log::SetLoggerError;

fn main() {}
```

### Current output
The output for the playground code is the following:
```Shell

error[E0432]: unresolved import `log::SetLoggerError`
  --> src/main.rs:12:5
   |
12 | use log::SetLoggerError;
   |     ^^^^^^^^^^^^^^^^^^^ no `SetLoggerError` in `a::log`
   |
help: consider importing this struct instead
   |
12 | use log::SetLoggerError;
   |     ~~~~~~~~~~~~~~~~~~~
```
The one I actually saw:
```shell
 unresolved import `proto::LogLevelValue`
 --> tests/tests/server_api.rs:3:5
  |
3 | use proto::LogLevelValue;
  |     ^^^^^^^^^^^^^^^^^^^^ no `LogLevelValue` in `proto`
  |
help: consider importing this enum instead
  |
3 | use proto::LogLevelValue;
  |     ~~~~~~~~~~~~~~~~~~~~
```

The second one is worse, because "no `LogLevelValue` in `proto`" doesn't indicate that this `proto` comes is a different `proto` than the one in the suggestion. I think this happens because the modules aren't in the same file or crate, so I couldn't reproduce it in the playground.

### Desired output

Ideally, `rustc` should be able to notify the user that the error comes from the fact that there are two modules with the same name, instead of suggesting the same code as a fix.

### Rationale and extra context

`rustc 1.73.0 (cc66ad468 2023-10-03)`

### Other cases

_No response_

### Anything else?

Sorry if this is duplicated, but I couldn't find an issue regarding this problem

### PR DESCRIPTION
**Pull request by fmease**
Fixes #116970.

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1163,8 +1163,6 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             Some(x) => Some(x),
         } {
             let in_module_is_extern = !in_module.def_id().is_local();
-            // We have to visit module children in deterministic order to avoid
-            // instabilities in reported imports (#43552).
```
Comment (fmease) [inline compiler/rustc_resolve/src/diagnostics.rs:1167]: This comment was added in #43552 but is no longer relevant. It should've been removed in #65043. Doing it now instead :)

File: tests/ui/imports/issue-56125.stderr
Comment (fmease) [inline tests/ui/imports/issue-56125.stderr:1]: The new suggestion is technically correct. I don't think it's so much a regression as an obscure test case.

File: tests/ui/unresolved/unresolved-import-avoid-suggesting-global-path.rs
Comment (fmease) [inline tests/ui/unresolved/unresolved-import-avoid-suggesting-global-path.rs:1]: I think it's possible to merge this test file into the main one, if you'd like me to.

Comment (fmease) [reply tests/ui/unresolved/unresolved-import-avoid-suggesting-global-path.rs:1]: On second thought, having two `run-rustfix` tests might be a bit overkill lol :sweat_smile:

**Comment by fmease** [comment]
pro tip: be well rested when working on a PR to get the title and comment texts right the first time ^^

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 2]
```diff
@@ -1214,12 +1212,14 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
                     if filter_fn(res) {
                         // create the path
-                        let mut segms = path_segments.clone();
-                        if lookup_ident.span.at_least_rust_2018() {
+                        let mut segms = if lookup_ident.span.at_least_rust_2018() {
                             // crate-local absolute paths start with `crate::` in edition 2018
                             // FIXME: may also be stabilized for Rust 2015 (Issues #45477, #44660)
-                            segms.insert(0, ast::PathSegment::from_ident(crate_name));
-                        }
+                            crate_path.clone()
```
Comment (b-naber) [inline compiler/rustc_resolve/src/diagnostics.rs:1218]: We should be able to move this here.

**Review by b-naber — APPROVED** [review]
r=me with nit addressed.

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 2 above)
Comment (fmease) [reply compiler/rustc_resolve/src/diagnostics.rs:1218]: You mean the whole `let needs_disambiguation = self.resolutions(…).iter().any(…); …` code or just the `let crate_path = …; …` one? If `self.resolutions(…)` was moved here, it would get executed several times: For each work item (`while let Some(…) = worklist.pop()`) and `for_each_child` `in_module`.

Comment (b-naber) [reply compiler/rustc_resolve/src/diagnostics.rs:1218]: 🤦 sorry, should have looked more carefully.
