### PR TITLE
fix download-llvm logic for subtree sync branches

### LINKED ISSUE #101907: Merge commits break LLVM CI download
While PRs are not allowed to have merge commits, they can still be useful locally (or for not rewriting history for longer-running branches). 

However, they break the commit detection logic for downloading CI artifacts.

### Steps to Reproduce

1. `git checkout <old-commit>`
2. `git merge --no-ff master`
3. `./x.py build library/std`

### Expected Result

Builds fine.

### Actual Result

~~~
...
downloading https://ci-artifacts.rust-lang.org/rustc-builds/<old-commit>/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
curl: (22) The requested URL returned error: 404      #                                                                               

error: failed to download llvm from ci

help: old builds get deleted after a certain time
help: if trying to compile an old commit of rustc, disable `download-ci-llvm` in config.toml:

[llvm]
download-ci-llvm = false

Build completed unsuccessfully in 0:01:43
~~~

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/101907

Cc @onur-ozkan 
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by klensy** [comment]
This change partially merged in #137594, weird.

**Comment by RalfJung** [comment]
I have updated the PR based on what I found [here](https://github.com/rust-lang/rust/issues/101907#issuecomment-2697671282). I still think we shouldn't even try to look at the history when we no that basically none of the history has even been fetched, but that's a much larger change I will not undertake. I hope (and confirmed to the extent that I can, by playing with `git log` in a sparse checkout) this change now both fixes the issue I am running into and keeps CI working.

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
r=me if we didn't need to revert this somewhere (I seem to vaguely recall that happening somewhere)

**Comment by RalfJung** [comment]
We had to revert an earlier version of this. So I went for a different approach now, which should fix that issue.

@bors r=Mark-Simulacrum

**Comment by jieyouxu** [comment]
Hm, this might've somehow broken perf, but I'm not 100%

**Comment by jieyouxu** [comment]
It's like the `rev-list` args is somehow wrong because the rustc-perf log output has

```
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
         limiting output:
           --max-count=<n>
           --max-age=<epoch>
           --min-age=<epoch>
           --sparse
           --no-merges
           --min-parents=<n>
           --no-min-parents
           --max-parents=<n>
           --no-max-parents
           --remove-empty
           --all
           --branches
           --tags
           --remotes
           --stdin
           --quiet
         ordering output:
           --topo-order
           --date-order
           --reverse
         formatting output:
           --parents
           --children
           --objects | --objects-edge
           --unpacked
           --header | --pretty
           --abbrev=<n> | --no-abbrev
           --abbrev-commit
           --left-right
           --count
         special purpose:
           --bisect
           --bisect-vars
           --bisect-all
```

File: src/build_helper/src/git.rs [hunk 1]
```diff
@@ -150,11 +151,18 @@ pub fn get_closest_merge_commit(
...
+    // At the same time, we use this logic in CI where only a tiny part of the history
+    // is even checked out, making this kind of history search very fragile. It turns
+    // out that by adding `--diff-merges=first-parent`, we get a usable reply
+    // even for sparse checkouts: it will just return the most recent bors commit.
     git.args([
         "rev-list",
         &format!("--author={}", config.git_merge_commit_email),
         "-n1",
-        "--first-parent",
+        "--diff-merges=first-parent",
```
Comment (jieyouxu) [inline src/build_helper/src/git.rs:165]: I think `--diff-merges` is a `git show`-only flag, not `git rev-list`.

**Comment by jieyouxu** [comment]
I posted a revert https://github.com/rust-lang/rust/pull/138878 to fix perf, because I know nothing about the distinction between these two flags, so a fix-forward seems also risky.

File: src/build_helper/src/git.rs (hunk 1 above)
Comment (RalfJung) [reply src/build_helper/src/git.rs:165]: I tried it locally and it works for `git rev-list` as well.
```
$ git --version
git version 2.47.2
```
