### PR TITLE
Make RPITITs capture all in-scope lifetimes

### LINKED ISSUE #112194: RPITIT is allowed to name any in-scope lifetime parameter, unlike inherent RPIT methods
I noticed (while responding to [this comment](https://github.com/rust-lang/rfcs/pull/3425#pullrequestreview-1443027655) by @aliemjay) that there's an inconsistency in how we handle returning `Self` if it captures lifetimes. For both inherent methods and RPITIT, if you write `-> impl Trait` and then return `self` on an impl for a type that containing a lifetime, we give you an error:

```rust
struct Foo<'a>(&'a str);

// ERROR: hidden type for `impl Sized` captures lifetime that does not appear in bounds
impl<'a> Foo<'a> {
    fn foo(self) -> impl Sized { self }
}

trait Trait<'a> {
    fn bar(self) -> impl Sized;
}

// ERROR: hidden type for `impl Sized` captures lifetime that does not appear in bounds
impl<'a> Trait<'a> for &'a i32 {
    fn bar(self) -> impl Sized { self }
}
```

However, if you write `-> Self` on an implementation of a trait method that's written with `-> impl Trait`, there is no error (though this would require `#[refine]` with RFC 3245):

```rust
// OK?
impl<'a> Trait<'a> for &'a u32 {
    fn bar(self) -> Self { self }
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6a522a1ab93edceff5ce7ed84b0a47a0)

First, this inconsistency is weird from a user perspective because it seems like the capture rules say what lifetimes your hidden type is allowed to _reference_, and such a property can only be strengthened by an implementation (by referencing fewer, or longer-lived, lifetimes than the trait allows), never weakened. But here, the implementation specifies it a concrete type which allows it to name _additional_ lifetimes.

If we could I we would say we should probably accept all of these examples and consider `Self` to be a type parameter in how we interpret [RFC 1951](https://rust-lang.github.io/rfcs/1951-expand-impl-trait.html#scoping-for-type-and-lifetime-parameters). That said, I don't think it's possible to change today given that [you can depend on the return type not referencing the lifetime](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d4aff22d7a47baa11c521518c3b05372).

Given that, we should probably apply the same restriction to RPITIT for the sake of consistency and _not_ allow it to name any lifetime parameters as we [assume it can today](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d7696e18bb9a6aa75674ad6fbadc3487) (including through `Self`). Though this might create other issues I'm not thinking of.

cc @compiler-errors

### PR DESCRIPTION
**Pull request by compiler-errors**
Much like #114616, this implements the lang team decision from this T-lang meeting on [opaque captures strategy moving forward](https://hackmd.io/sFaSIMJOQcuwCdnUvCxtuQ?view). This will be RFC'd soon, but given that RPITITs are a nightly feature, this shouldn't necessarily be blocked on that.

We unconditionally capture all lifetimes in RPITITs -- impl is not as simple as #114616, since we still need to duplicate RPIT lifetimes to make sure we reify any late-bound lifetimes in scope.

Closes #112194

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-114489/retry-regressed-list.txt p=1

File: tests/ui/impl-trait/in-trait/object-safety.rs [hunk 1]
```diff
@@ -19,4 +19,5 @@ fn main() {
     //~| ERROR the trait `Foo` cannot be made into an object
     let s = i.baz();
     //~^ ERROR the trait `Foo` cannot be made into an object
+    //~| ERROR the trait bound `dyn Foo: Foo`
```
Comment (compiler-errors) [inline tests/ui/impl-trait/in-trait/object-safety.rs:22]: This "regression" is due to the fact that the RPITIT is now a GAT (since it captures lifetimes now). GATs hit this code:

https://github.com/rust-lang/rust/blob/f525bb4e2afac6d2491a86c178aa98e3f3931130/compiler/rustc_trait_selection/src/traits/select/confirmation.rs#L547-L553
