### PR TITLE
Sized Hierarchy: Part I

### LINKED ISSUE #79409: ICE with unsizing an extern type
### Code

```Rust
#![feature(extern_types)]
#![feature(unsized_locals)]

extern { 
    type Device;
}

unsafe fn make_device() -> Box<Device> {
    Box::from_raw(0 as *mut _)
}

fn main() {
    let d: Device = unsafe { *make_device() };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', compiler/rustc_codegen_llvm/src/builder.rs:445:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: <rustc_codegen_llvm::builder::Builder as rustc_codegen_ssa::traits::builder::BuilderMethods>::load_operand
   3: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_consume
   4: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
   5: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
   6: rustc_codegen_ssa::mir::codegen_mir
   7: rustc_codegen_ssa::base::codegen_instance
   8: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
   9: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  11: rustc_codegen_llvm::base::compile_codegen_unit
  12: rustc_codegen_ssa::base::codegen_crate
  13: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  14: rustc_interface::queries::Queries::ongoing_codegen
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidtwco**
This patch implements the non-const parts of rust-lang/rfcs#3729. It introduces two new traits to the standard library, `MetaSized` and `PointeeSized`. See the RFC for the rationale behind these traits and to discuss whether this change makes sense in the abstract.

These traits are unstable (as is their constness), so users cannot refer to them without opting-in to `feature(sized_hierarchy)`. These traits are not behind `cfg`s as this would make implementation unfeasible, there would simply be too many `cfg`s required to add the necessary bounds everywhere. So, like `Sized`, these traits are automatically implemented by the compiler.

RFC 3729 describes changes which are necessary to preserve backwards compatibility given the introduction of these traits, which are implemented and as follows:

- `?Sized` is rewritten as `MetaSized`
- `MetaSized` is added as a default supertrait for all traits w/out an explicit sizedness supertrait already.

There are no edition migrations implemented in this,  as these are primarily required for the constness parts of the RFC and prior to stabilisation of this (and so will come in follow-up PRs alongside the const parts). All diagnostic output should remain the same (showing `?Sized` even if the compiler sees `MetaSized`) unless the `sized_hierarchy` feature is enabled.

Due to the use of unstable extern types in the standard library and rustc, some bounds in both projects have had to be relaxed already - this is unfortunate but unavoidable so that these extern types can continue to be used where they were before. Performing these relaxations in the standard library and rustc are desirable longer-term anyway, but some bounds are not as relaxed as they ideally would be due to the inability to relax `Deref::Target` (this will be investigated separately).

It is hoped that this is implemented such that it could be merged and these traits could exist "under the hood" without that being observable to the user (other than in any performance impact this has on the compiler, etc). Some details might leak through due to the standard library relaxations, but this has not been observed in test output.

**Notes:**

- Any commits starting with "upstream:" can be ignored, as these correspond to other upstream PRs that this is based on which have yet to be merged.
- This best reviewed commit-by-commit. I've attempted to make the implementation easy to follow and keep similar changes and test output updates together.
  - Each commit has a short description describing its purpose.
  - This patch is large but it's primarily in the test suite.
- I've worked on the performance of this patch and a few optimisations are implemented so that the performance impact is neutral-to-minor.
- `PointeeSized` is a different name from the RFC just to make it more obvious that it is different from `std::ptr::Pointee` but all the names are yet to be bikeshed anyway.
- @nikomatsakis has confirmed [that this can proceed as an experiment from the t-lang side](https://rust-lang.zulipchat.com/#narrow/channel/435869-project-goals/topic/SVE.20and.20SME.20on.20AArch64.20.28goals.23270.29/near/506196491)
- FCP in https://github.com/rust-lang/rust/pull/137944#issuecomment-2912207485

Fixes rust-lang/rust#79409.

r? @ghost (I'll discuss this with relevant teams to find a reviewer)

### CODE REVIEW

**Comment by davidtwco** [comment]
I can reproduce this locally but I have no idea why it would be related to this patch.

File: compiler/rustc_type_ir/src/flags.rs [hunk 1]
```diff
@@ -124,5 +124,8 @@ bitflags::bitflags! {
 
         /// Does this have any binders with bound vars (e.g. that need to be anonymized)?
         const HAS_BINDER_VARS             = 1 << 25;
+
+        /// Does this type only has non-const implementations of sizedness traits?
```
Comment (workingjubilee) [inline compiler/rustc_type_ir/src/flags.rs:128]:
```suggestion
        /// Does this type only have non-const implementations of sizedness traits?
```

File: compiler/rustc_passes/src/check_attr.rs [hunk 2]
```diff
@@ -2578,6 +2581,18 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
         }
     }
 
+    /// `#[rustc_non_const_sized]` is a testing attribute for forcing `const Sized` not to be
+    /// implemented (while there are no types which are non-`const Sized`) - it should only be
+    /// applied to structs or enums.
```
Comment (workingjubilee) [inline compiler/rustc_passes/src/check_attr.rs:2586]: "forcing `const Sized` not to be implemented while there are no types which are non-`const Sized`"...? ...forgive me, I'm not sure I understand, do you mean disabling the assumption the type would be `const Sized`, or do you mean actively requiring it to be `!const Sized`?

File: tests/ui/target-feature/tied-features-no-implication-1.rs [hunk 3]
```diff
@@ -5,11 +5,19 @@
...
+#[lang = "pointeesized"]
+pub trait PointeeSized {}
+
+#[lang = "metasized"]
+#[const_trait]
+pub trait MetaSized: PointeeSized {}
+
+#[lang = "sized"]
+#[const_trait]
+pub trait Sized: MetaSized {}
```
Comment (workingjubilee) [inline tests/ui/target-feature/tied-features-no-implication-1.rs:20]: maybe these tests should be using minicore... well, whatever for now.

**Comment by traviscross** [comment]
cc @rust-lang/lang

File: tests/ui/target-feature/tied-features-no-implication-1.rs (hunk 3 above)
Comment (davidtwco) [reply tests/ui/target-feature/tied-features-no-implication-1.rs:20]: I ported as many tests as I could to using minicore in rust-lang/rust#137599, if this one wasn't ported it was either because adding minicore made it fail or because adding minicore made it harder to debug/reason about/some-other-test-specific-reason.

File: compiler/rustc_passes/src/check_attr.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_passes/src/check_attr.rs]: Rewritten this comment, should be clearer

**Comment by davidtwco** [comment]
> Does this perhaps fix #127336 by rejecting it?

It doesn't currently.

**Comment by davidtwco** [comment]
Undrafting now that CI passes

File: compiler/rustc_ty_utils/src/ty.rs [hunk 4]
```diff
@@ -78,12 +105,48 @@ fn defaultness(tcx: TyCtxt<'_>, def_id: LocalDefId) -> hir::Defaultness {
...
     tcx: TyCtxt<'tcx>,
     def_id: DefId,
+) -> Option<ty::EarlyBinder<'tcx, Ty<'tcx>>> {
+    adt_sizedness_constraint(tcx, Sizedness::Sized, def_id)
+}
+
+/// Calculates the `MetaSized` constraint.
+///
+/// In fact, there are only a few options for the types in the constraint:
+///     - an pointeesized type
```
Comment (fee1-dead) [inline compiler/rustc_ty_utils/src/ty.rs:122]: as above

File: compiler/rustc_ty_utils/src/ty.rs [hunk 5]
```diff
@@ -78,12 +105,48 @@ fn defaultness(tcx: TyCtxt<'_>, def_id: LocalDefId) -> hir::Defaultness {
...
+#[instrument(level = "debug", skip(tcx), ret)]
+fn adt_metasized_constraint<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    def_id: DefId,
+) -> Option<ty::EarlyBinder<'tcx, Ty<'tcx>>> {
+    adt_sizedness_constraint(tcx, Sizedness::MetaSized, def_id)
+}
+
+///
+/// Calculates the `PointeeSized` constraint.
```
Comment (fee1-dead) [inline compiler/rustc_ty_utils/src/ty.rs:133]: extra line of empty docstring

File: compiler/rustc_ty_utils/src/ty.rs [hunk 6]
```diff
@@ -78,12 +105,48 @@ fn defaultness(tcx: TyCtxt<'_>, def_id: LocalDefId) -> hir::Defaultness {
...
+///
+/// In fact, there are only a few options for the types in the constraint:
+///     - a type parameter or projection whose sizedness can't be known
```
Comment (fee1-dead) [inline compiler/rustc_ty_utils/src/ty.rs:136]: this should be reworded now that there's only one case

File: compiler/rustc_ty_utils/src/ty.rs [hunk 7]
```diff
@@ -93,21 +156,26 @@ fn adt_sized_constraint<'tcx>(
...
     }
 
     let tail_def = def.non_enum_variant().tail_opt()?;
     let tail_ty = tcx.type_of(tail_def.did).instantiate_identity();
 
-    let constraint_ty = sized_constraint_for_ty(tcx, tail_ty)?;
+    let constraint_ty = sizedness_constraint_for_ty(tcx, sizedness, tail_ty)?;
 
-    // perf hack: if there is a `constraint_ty: Sized` bound, then we know
+    // perf hack: if there is a `constraint_ty: {Meta,}Sized` bound, then we know
```
Comment (fee1-dead) [inline compiler/rustc_ty_utils/src/ty.rs:167]: `{Meta,Pointee,}`

File: compiler/rustc_type_ir/src/solve/mod.rs [hunk 8]
```diff
@@ -294,3 +294,14 @@ pub enum AdtDestructorKind {
     NotConst,
     Const,
 }
+
+/// Which sizedness trait - `Sized`, `MetaSized` or `PointeeSized`?
+#[derive(Copy, Clone, Debug)]
+pub enum Sizedness {
```
Comment (fee1-dead) [inline compiler/rustc_type_ir/src/solve/mod.rs:300]: I'd prefer it to be named as `SizedTraitKind`.

File: tests/ui/sized-hierarchy/impls.rs [hunk 9]
```diff
@@ -0,0 +1,307 @@
...
+
+    // tuple w/ all elements metasized
+    needs_sized::<([u8], [u8])>();
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+    needs_metasized::<([u8], [u8])>();
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+    needs_pointeesized::<([u8], [u8])>();
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+
+    // tuple w/ all elements unsized
```
Comment (fee1-dead) [inline tests/ui/sized-hierarchy/impls.rs:207]: should be PointeeSized

File: tests/ui/sized-hierarchy/impls.rs [hunk 10]
```diff
@@ -0,0 +1,307 @@
...
+    needs_pointeesized::<(Foo, Foo)>();
+    //~^ ERROR the size for values of type `main::Foo` cannot be known at compilation time
+
+    // tuple w/ last element metasized
+    needs_sized::<(u32, [u8])>();
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+    needs_metasized::<(u32, [u8])>();
+    needs_pointeesized::<(u32, [u8])>();
+
+    // tuple w/ last element unsized
```
Comment (fee1-dead) [inline tests/ui/sized-hierarchy/impls.rs:221]: PointeeSized

File: tests/ui/sized-hierarchy/impls.rs [hunk 11]
```diff
@@ -0,0 +1,307 @@
...
+    needs_sized::<StructAllFieldsSized>();
+    needs_metasized::<StructAllFieldsSized>();
+    needs_pointeesized::<StructAllFieldsSized>();
+
+    // struct w/ all fields metasized
+    struct StructAllFieldsMetaSized { x: [u8], y: [u8] }
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+    needs_sized::<StructAllFieldsMetaSized>();
+    //~^ ERROR the size for values of type `[u8]` cannot be known at compilation time
+    needs_metasized::<StructAllFieldsMetaSized>();
```
Comment (fee1-dead) [inline tests/ui/sized-hierarchy/impls.rs:245]: I'm a little confused as to what this achieves with this kind of type implementing `MetaSized`, although that is what is described in the RfC..

File: library/core/src/cmp.rs [hunk 12]
```diff
@@ -245,6 +246,241 @@ use self::Ordering::*;
...
+    #[rustc_diagnostic_item = "cmp_partialeq_ne"]
+    fn ne(&self, other: &Rhs) -> bool {
+        !self.eq(other)
+    }
+}
+
+/// Trait for comparisons using the equality operator.
+///
+/// Implementing this trait for types provides the `==` and `!=` operators for
+/// those types.
```
Comment (fee1-dead) [inline library/core/src/cmp.rs:271]: You don't need docs for `cfg(bootstrap)`ed items.

**Review by fee1-dead — COMMENTED** [review]
had an initial look until the "library/compiler" commit. Will look more into it later.

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 13]
```diff
@@ -128,13 +167,19 @@ where
...
-        | ty::Dynamic(..)
-        | ty::Foreign(..)
-        | ty::Alias(..)
-        | ty::Param(_)
-        | ty::Placeholder(..) => Err(NoSolution),
+        // impl {Meta,Pointee,}Sized for str, [T], dyn Trait
+        ty::Str | ty::Slice(_) | ty::Dynamic(..) => match sizedness {
+            Sizedness::Sized => Err(NoSolution),
+            Sizedness::MetaSized | Sizedness::PointeeSized => Ok(ty::Binder::dummy(vec![])),
+        },
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:175]: It is, everything is `PointeeSized`.

File: compiler/rustc_middle/src/ty/adt.rs [hunk 14]
```diff
@@ -625,6 +633,24 @@ impl<'tcx> AdtDef<'tcx> {
     pub fn sized_constraint(self, tcx: TyCtxt<'tcx>) -> Option<ty::EarlyBinder<'tcx, Ty<'tcx>>> {
         if self.is_struct() { tcx.adt_sized_constraint(self.did()) } else { None }
     }
+
+    /// Returns a type such that `Self: MetaSized` if and only if that type is `MetaSized`,
+    /// or `None` if the type is always metasized.
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_middle/src/ty/adt.rs]: Fixed

File: compiler/rustc_middle/src/ty/adt.rs [hunk 15]
```diff
@@ -625,6 +633,24 @@ impl<'tcx> AdtDef<'tcx> {
...
+    pub fn metasized_constraint(
+        self,
+        tcx: TyCtxt<'tcx>,
+    ) -> Option<ty::EarlyBinder<'tcx, Ty<'tcx>>> {
+        if self.is_struct() { tcx.adt_metasized_constraint(self.did()) } else { None }
+    }
+
+    /// Returns a type such that `Self: PointeeSized` if and only if that type is `PointeeSized`,
+    /// or `None` if the type is always pointeesized.
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_middle/src/ty/adt.rs]: Fixed

File: compiler/rustc_middle/src/ty/adt.rs [hunk 16]
```diff
@@ -625,6 +633,24 @@ impl<'tcx> AdtDef<'tcx> {
...
+    pub fn pointeesized_constraint(
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_middle/src/ty/adt.rs:665]: I thought it better that it match the trait name which doesn't have the underscore.

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 17]
```diff
@@ -143,22 +188,27 @@ where
 
         ty::UnsafeBinder(bound_ty) => Ok(bound_ty.map_bound(|ty| vec![ty])),
 
-        // impl Sized for ()
-        // impl Sized for (T1, T2, .., Tn) where Tn: Sized if n >= 1
+        // impl {Meta,}Sized for ()
+        // impl {Meta,}Sized for (T1, T2, .., Tn) where Tn: {Meta,}Sized if n >= 1
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs]: Unintentional, fixed

File: compiler/rustc_ty_utils/src/ty.rs [hunk 18]
```diff
@@ -78,12 +105,48 @@ fn defaultness(tcx: TyCtxt<'_>, def_id: LocalDefId) -> hir::Defaultness {
 /// Calculates the `Sized` constraint.
 ///
 /// In fact, there are only a few options for the types in the constraint:
-///     - an obviously-unsized type
+///     - an metasized type
+///     - an pointee-sized type
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: Fixed

File: compiler/rustc_ty_utils/src/ty.rs (hunk 4 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: Fixed

File: compiler/rustc_ty_utils/src/ty.rs (hunk 5 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: Fixed

File: compiler/rustc_ty_utils/src/ty.rs (hunk 6 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: Fixed

File: compiler/rustc_ty_utils/src/ty.rs (hunk 7 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: Fixed

File: tests/ui/sized-hierarchy/impls.rs (hunk 9 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/impls.rs]: Fixed

File: compiler/rustc_type_ir/src/solve/mod.rs (hunk 8 above)
Comment (davidtwco) [reply compiler/rustc_type_ir/src/solve/mod.rs]: Fixed

File: tests/ui/sized-hierarchy/impls.rs (hunk 10 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/impls.rs]: Fixed

File: tests/ui/sized-hierarchy/impls.rs (hunk 11 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/impls.rs:245]: This type wouldn't be especially useful but I think it's better for the rule for what is `MetaSized` to be consistent.

**Comment by davidtwco** [comment]
Thanks for the initial review @fee1-dead, addressed all of those comments now.

**Comment by fee1-dead** [comment]
Has there been approval (on GH/Zulip/otherwise) from the lang team to do an experiment? Please link it in the PR description.

**Comment by davidtwco** [comment]
I've been meaning to run perf on this and see what the damage is:

@bors try @rust-timer queue

**Comment by davidtwco** [comment]
Okay, so there's some work to do on perf, as expected.

File: compiler/rustc_middle/src/ty/adt.rs (hunk 16 above)
[the remark this answers is not in the document]
Comment (fee1-dead) [reply compiler/rustc_middle/src/ty/adt.rs:657]: When you convert from camel case, underscore is used to split the capitalized name. This happens to every lang item like `partial_eq`. Better to be consistent here. I suggest you to use `pointee_sized` and so on in these contexts.

File: library/core/src/marker.rs [hunk 19]
```diff
@@ -151,10 +151,50 @@ unsafe impl<T: Sync + ?Sized> Send for &T {}
...
+    // Empty
+}
+
+#[cfg(bootstrap)]
+#[unstable(feature = "sized_hierarchy", issue = "none")]
+impl<T: ?Sized> MetaSized for T {}
+
+/// Types that may or may not have a size.
+#[unstable(feature = "sized_hierarchy", issue = "none")]
+#[cfg_attr(not(bootstrap), lang = "pointeesized")]
```
Comment (fee1-dead) [inline library/core/src/marker.rs:184]: lang = "pointee_sized"

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 20]
```diff
@@ -146,31 +147,18 @@ where
...
-    ) -> Result<Candidate<I>, NoSolution>;
-
-    /// A type is `PointeeSized` if its tail component is `PointeeSized`.
-    ///
-    /// These components are given by built-in rules from
-    /// [`structural_traits::instantiate_constituent_tys_for_sized_trait`].
-    fn consider_builtin_pointeesized_candidate(
+    /// [`structural_traits::instantiate_constituent_tys_for_sized_trait`],
+    /// [`structural_traits::instantiate_constituent_tys_for_metasized_trait`] and
+    /// [`structural_traits::instantiate_constituent_tys_for_pointeesized_trait`].
```
Comment (fee1-dead) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:157]: Maybe better to just refer to `instantiate_constituent_tys_for_sizedness_trait` only

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 21]
```diff
@@ -228,37 +229,17 @@ where
...
+                SizedTraitKind::Sized => {
+                    structural_traits::instantiate_constituent_tys_for_sized_trait
+                }
+                SizedTraitKind::MetaSized => {
+                    structural_traits::instantiate_constituent_tys_for_metasized_trait
+                }
+                SizedTraitKind::PointeeSized => {
+                    structural_traits::instantiate_constituent_tys_for_pointeesized_trait
+                }
+            },
```
Comment (fee1-dead) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:242]: I don't think we this extra layer of indirection as there is already `instantiate_constituent_tys_for_sizedness_trait` which takes any `SizedTraitKind`

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 22]
```diff
@@ -143,22 +190,27 @@ where
...
-        //   As a performance optimization, `sized_constraint(Adt)` can return `None`
-        //   if the ADTs definition implies that it is sized by for all possible args.
+        // impl {Meta,}Sized for Adt<Args...> if {meta,}sized_constraint(Adt) == None
+        //   As a performance optimization, `{meta,}sized_constraint(Adt)` can return `None`
+        //   if the ADTs definition implies that it is {meta,}sized by for all possible args.
         //   In this case, the builtin impl will have no nested subgoals. This is a
-        //   "best effort" optimization and `sized_constraint` may return `Some`, even
-        //   if the ADT is sized for all possible args.
+        //   "best effort" optimization and `{meta,}sized_constraint` may return `Some`, even
+        //   if the ADT is {meta,}sized for all possible args.
```
Comment (fee1-dead) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:206]: these should all contain pointee also

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs [hunk 23]
```diff
@@ -21,104 +21,224 @@ use crate::hir_ty_lowering::{
...
-        for unbound in &unbounds {
-            if let Res::Def(DefKind::Trait, unbound_def_id) = unbound.trait_ref.path.res {
-                seen_repeat |= !unique_bounds.insert(unbound_def_id);
+            if ptr.trait_ref.path.res == Res::Def(DefKind::Trait, pointeesized_did) {
+                match ptr.modifiers.polarity {
+                    hir::BoundPolarity::Maybe(_) => pointeesized.maybe = true,
+                    hir::BoundPolarity::Negative(_) => pointeesized.negative = true,
+                    hir::BoundPolarity::Positive => pointeesized.positive = true,
+                }
             }
```
Comment (fee1-dead) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs]: This part can be deduplicated through doing something like

```rust
let collected = if ... { &mut sized } else if ... { &mut meta_sized } else if { &mut pointee_sized } else { continue };  
```

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs [hunk 24]
```diff
@@ -21,104 +21,224 @@ use crate::hir_ty_lowering::{
...
+        if let Some(clause) = clause.as_trait_clause()
+            && clause.skip_binder().def_id() == did
+        {
+            idx = Some(cur_idx);
+        }
+    }
+
+    if let Some(idx) = idx {
+        bounds.remove(idx);
+    }
```
Comment (fee1-dead) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs:180]: Any chance for duplication? In any case we should use

```rust
bounds.retain(|(clause, _)| clause.as_trait_clause().map_or(false, |clause| clause.skip_binder().def_id() != did))
```
instead.

File: tests/ui/sized-hierarchy/default-supertrait.rs [hunk 25]
```diff
@@ -0,0 +1,49 @@
...
+
+trait NegMetaSized: ?MetaSized { }
+//~^ ERROR `?Trait` is not permitted in supertraits
+
+
+trait PointeeSized_: PointeeSized { }
+
+trait NegPointeeSized: ?PointeeSized { }
+//~^ ERROR `?Trait` is not permitted in supertraits
+
```
Comment (fee1-dead) [inline tests/ui/sized-hierarchy/default-supertrait.rs:22]: Should add a `trait Bare {}` here and test

File: tests/ui/sized-hierarchy/pointee-supertrait.rs [hunk 26]
```diff
@@ -0,0 +1,24 @@
...
+    where
+        T: for<'c> Bar<'c>,
+        <T as Bar<'a>>::Foo: PartialEq<<T as Bar<'b>>::Foo>,
+{
+    fn eq(&self, _: &Foo<'b, T>) -> bool {
+        loop {}
+    }
+}
+
+fn main() { }
```
Comment (fee1-dead) [inline tests/ui/sized-hierarchy/pointee-supertrait.rs]: Hmmm. Where does this test come from?

**Review by fee1-dead — CHANGES_REQUESTED** [review]
Second pass. Will spend more time on it today after I get to my PC and not from my laptop :)

File: tests/ui/traits/resolve-impl-before-constrain-check.rs [hunk 27]
```diff
@@ -1,12 +1,15 @@
...
+
     pub trait Callable {
         fn call();
     }
 
-    impl<V: ?Sized> Callable for () {
+    impl<V: PointeeSized> Callable for () {
     //~^ ERROR the type parameter `V` is not constrained by the impl trait, self type, or predicates
         fn call() {}
     }
```
Comment (fee1-dead) [inline tests/ui/traits/resolve-impl-before-constrain-check.rs:16]: This error still fires for `impl<V: ?Sized>` right? They probably don't need to use `feature(sized_hierarchy)`?

File: tests/ui/traits/non_lifetime_binders/on-rpit.rs [hunk 28]
```diff
@@ -1,11 +1,14 @@
...
 
-trait Trait<T: ?Sized> {}
+use std::marker::PointeeSized;
 
-impl<T: ?Sized> Trait<T> for i32 {}
+trait Trait<T: PointeeSized> {}
+
+impl<T: PointeeSized> Trait<T> for i32 {}
 
 fn produce() -> impl for<T> Trait<T> {
```
Comment (fee1-dead) [inline tests/ui/traits/non_lifetime_binders/on-rpit.rs]: After the sized hierarchy is introduced, does this _need_ `sized_hierarchy` enabled to work? If yes, that is a potential concern. If not, these tests should remain without using the feature, while you can add the tests to under the experimental feature.

**Review by fee1-dead — DISMISSED** [review]
I have some general issues with the commits starting from "[tests: PointeeSized bounds with extern types](https://github.com/rust-lang/rust/pull/137944/commits/69e48953b3c9164208858b570ce57dac98df47c9)" to "[tests: bless remaining tests](https://github.com/rust-lang/rust/pull/137944/commits/552a6d7d3b4fc458ea65e8c8e0018611fff83419)".

In those tests' cases, were enabling the `sized_hierarchy` required for some tests to work? For example, before the feature was enabled, do functions like `fn foo<T: ?Sized>()` still accept opaque types? If they don't and need the feature to be enabled to work again, then that's a potential breakage.

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs (hunk 21 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs (hunk 23 above)
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs]: Fixed

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs (hunk 24 above)
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs]: Fixed

File: tests/ui/sized-hierarchy/default-supertrait.rs (hunk 25 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/default-supertrait.rs:22]: Added

File: tests/ui/sized-hierarchy/pointee-supertrait.rs (hunk 26 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/pointee-supertrait.rs]: This is reduction of the error that requires the `cfg(bootstrap)` on `PartialEq` - I forget what the exact error I was getting was, but it happened w/ my changes and w/out my changes when adding a blanket `PointeeSized` bound. This motivated the change making `PointeeSized` effectively syntactic sugar for an absence of any bounds whatsoever. I've added a comment describing this.

File: compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs [hunk 29]
```diff
@@ -600,11 +601,23 @@ fn receiver_is_dispatchable<'tcx>(
...
         };
 
+        let metasized_predicate = {
+            let metasized_did = tcx.require_lang_item(LangItem::MetaSized, None);
+            ty::TraitRef::new(tcx, metasized_did, [unsized_self_ty]).upcast(tcx)
+        };
+        let pointeesized_predicate = {
+            let pointeesized_did = tcx.require_lang_item(LangItem::PointeeSized, None);
+            ty::TraitRef::new(tcx, pointeesized_did, [unsized_self_ty]).upcast(tcx)
+        };
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs]: It doesn't, fixed

File: tests/ui/sized-hierarchy/pretty-print-no-feat.stderr
[the remark this answers is not in the document]
Comment (davidtwco) [reply tests/ui/sized-hierarchy/pretty-print-no-feat.stderr:1]: Added a test, works as expected, crate w/out feature sees `?Sized` written rather than the new traits

File: tests/ui/traits/resolve-impl-before-constrain-check.rs (hunk 27 above)
Comment (davidtwco) [reply tests/ui/traits/resolve-impl-before-constrain-check.rs:16]: It does but it produces a second error, so I added the feature so that what the test was doing remained the same. If we'd prefer to leave it unmodified and test something slightly different (`V: const MetaSized`) then I can do that too.

File: tests/ui/traits/non_lifetime_binders/on-rpit.rs (hunk 28 above)
Comment (davidtwco) [reply tests/ui/traits/non_lifetime_binders/on-rpit.rs]: It is necessary for the `non_lifetime_binders` tests - these tests only work when `for<T>` is unconstrained and with that feature being incomplete, it isn't possible to  add the bounds necessary to keep this test passing w/out the parameters being unconstrained. The only way to make a parameter unconstrained now is with `PointeeSized`, so the feature needs to be enabled.

File: library/core/src/marker.rs (hunk 19 above)
Comment (davidtwco) [reply library/core/src/marker.rs:184]: I haven't changed this because I think it should match the trait.

Comment (davidtwco) [reply library/core/src/marker.rs:184]: Oh, I see your previous comment regarding this now, will change it.

**Comment by davidtwco** [comment]
> Has there been approval (on GH/Zulip/otherwise) from the lang team to do an experiment? Please link it in the PR description.

I believe this came up in one of the design meetings but I can't see it mentioned in any notes, will get something to link to.

File: library/core/src/marker.rs (hunk 19 above)
Comment (davidtwco) [reply library/core/src/marker.rs]: Fixed

**Comment by davidtwco** [comment]
Skipping predicate elaboration for sizedness traits helped but not anywhere near enough.

**Comment by davidtwco** [comment]
Adding some sizedness special-casing to the fast path for the `type_op_prove_predicate` query didn't seem to do anything.

**Comment by davidtwco** [comment]
CI failure is spurious. After some chatting with @oli-obk, I believe that the performance regression is unrelated to the vast majority of the changes in this patch - a smaller patch just making `Sized` into a const trait and making `Sized` bounds (implicit and explicit) into `const Sized` will have the same regression - it's just adding the host effect predicates that does it. Looking into this.

File: tests/ui/traits/non_lifetime_binders/on-rpit.rs (hunk 28 above)
Comment (fee1-dead) [reply tests/ui/traits/non_lifetime_binders/on-rpit.rs]: Understood, thanks.

**Comment by davidtwco** [comment]
Dropped the changes from #139576 as they didn't seem to help.

**Comment by davidtwco** [comment]
This shouldn't be any different than perf runs in experiment runs but to confirm:

@bors try @rust-timer queue

File: compiler/rustc_next_trait_solver/src/solve/effect_goals.rs [hunk 30]
```diff
@@ -54,21 +57,34 @@ where
...
-            } else {
-                Err(NoSolution)
+                });
+            }
+
+            // PERF(sized-hierarchy): Sizedness supertraits aren't elaborated to improve perf, so
+            // check for a `Sized` subtrait when looking for `MetaSized`. `PointeeSized` bounds
+            // are syntactic sugar for a lack of bounds so don't need this.
+            if ecx.cx().is_lang_item(goal_did, TraitSolverLangItem::MetaSized)
+                && ecx.cx().is_lang_item(host_clause_did, TraitSolverLangItem::Sized)
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/effect_goals.rs:75]: this does not check that the clause and the goal have the same polarity cc https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/perf.20of.20sized.20hierarchy.20changes.20.28.23137944.29/near/512855088

**Comment by fee1-dead** [comment]
Had an initial glance yesterday (not posting the review comment yet), might have more time to do a full review next week, but I might reroll depending on my IRL availability.

**Comment by davidtwco** [comment]
> Had an initial glance yesterday (not posting the review comment yet), might have more time to do a full review next week, but I might reroll depending on my IRL availability.

No worries, feel free to post what you have. @oli-obk said he'd try and review this week so don't worry about having to get through it all yourself. Thanks for reviewing so far.

File: compiler/rustc_hir_analysis/src/collect/item_bounds.rs [hunk 31]
```diff
@@ -45,6 +45,13 @@ fn associated_type_bounds<'tcx>(
             | PredicateFilter::SelfTraitThatDefines(_)
             | PredicateFilter::SelfAndAssociatedTypeBounds => {
                 icx.lowerer().add_default_traits(&mut bounds, item_ty, hir_bounds, None, span);
+                icx.lowerer().adjust_sizedness_params_and_assoc_types(
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/collect/item_bounds.rs:48]: All the other sites adjust sizedness before adding default bounds and right after lower_bounds. May be worth a comment here

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/collect/item_bounds.rs:48]: it is kind of annoying that every `lower_bounds` call has to be paired with an adjust call, but with subtle differences

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 32]
```diff
@@ -506,20 +507,80 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
+
+    candidates.into_iter().find(|c| {
+        if !infcx.tcx.is_lang_item(c.def_id(), LangItem::Sized) {
+            return false;
+        }
+
+        let expected_self_ty = infcx.resolve_vars_if_possible(predicate.self_ty());
+        let found_self_ty = infcx.resolve_vars_if_possible(c.self_ty());
+        expected_self_ty == found_self_ty
+    })
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/util.rs:585]: Similarly polarity is not checked here

File: compiler/rustc_ty_utils/src/ty.rs [hunk 33]
```diff
@@ -35,31 +42,44 @@ fn sized_constraint_for_ty<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> Option<Ty<'
...
-            sized_constraint_for_ty(tcx, inner_ty.skip_binder()).map(|_| ty)
+            sizedness_constraint_for_ty(tcx, sizedness, inner_ty.skip_binder()).map(|_| ty)
+        }
+
+        ty::Foreign(..) => match sizedness {
+            // Never `MetaSized` or `Sized`
+            SizedTraitKind::Sized | SizedTraitKind::MetaSized => Some(ty),
+            // Always `PointeeSized`
+            SizedTraitKind::PointeeSized => None,
+        },
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/ty.rs:67]: it's kind of unfortunate that we need to have the same match in multiple places, but it also seems kinda unavoidable

File: compiler/rustc_ty_utils/src/ty.rs [hunk 34]
```diff
@@ -93,21 +121,26 @@ fn adt_sized_constraint<'tcx>(
...
 
-    // perf hack: if there is a `constraint_ty: Sized` bound, then we know
+    // perf hack: if there is a `constraint_ty: {Meta,Pointee,}Sized` bound, then we know
     // that the type is sized and do not need to check it on the impl.
-    let sized_trait_def_id = tcx.require_lang_item(LangItem::Sized, None);
+    let lang_item = match sizedness {
+        SizedTraitKind::Sized => LangItem::Sized,
+        SizedTraitKind::MetaSized => LangItem::MetaSized,
+        SizedTraitKind::PointeeSized => LangItem::PointeeSized,
+    };
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/ty.rs:138]: make this a method on `SizedTraitKind` and reuse it

File: compiler/rustc_type_ir/src/elaborate.rs [hunk 35]
```diff
@@ -79,20 +80,55 @@ pub fn elaborate<I: Interner, O: Elaboratable<I>>(
...
-            obligations.into_iter().filter(|o| {
-                self.visited.insert(self.cx.anonymize_bound_vars(o.predicate().kind()))
-            }),
+            obligations
+                .into_iter()
+                .filter(|o| self.visited.insert(self.cx.anonymize_bound_vars(o.predicate().kind())))
+                .filter(|o| {
+                    let Some(current_clause) = current_clause else {
+                        return true;
+                    };
```
Comment (oli-obk) [inline compiler/rustc_type_ir/src/elaborate.rs:106]: Kinda weird that this is run every loop, but I do see why the alternatives would just be more roundabout

File: library/core/src/ops/unsize.rs [hunk 36]
```diff
@@ -33,40 +33,67 @@ use crate::marker::Unsize;
 /// [nomicon-coerce]: ../../nomicon/coercions.html
 #[unstable(feature = "coerce_unsized", issue = "18598")]
 #[lang = "coerce_unsized"]
-pub trait CoerceUnsized<T: ?Sized> {
+pub trait CoerceUnsized<T: ?Sized + PointeeSized> {
```
Comment (oli-obk) [inline library/core/src/ops/unsize.rs:36]: After a bootstrap bump we'll be able to remove most `?Sized` from libcore, right?

File: tests/incremental/hashes/trait_defs.rs [hunk 37]
```diff
@@ -30,7 +30,7 @@ trait TraitVisibility { }
 #[cfg(not(any(cfail1,cfail4)))]
 #[rustc_clean(cfg="cfail2")]
 #[rustc_clean(cfg="cfail3")]
-#[rustc_clean(cfg="cfail5", except="opt_hir_owner_nodes")]
+#[rustc_clean(cfg="cfail5", except="opt_hir_owner_nodes,predicates_of")]
```
Comment (oli-obk) [inline tests/incremental/hashes/trait_defs.rs:33]: why are predicates_of now dirty?

File: tests/ui/layout/unconstrained-param-ice-137308.rs [hunk 38]
```diff
@@ -3,14 +3,16 @@
...
 #![crate_type = "lib"]
 
+use std::marker::PointeeSized;
+
 trait A {
     const B: usize;
 }
 
-impl<C: ?Sized> A for u8 { //~ ERROR: the type parameter `C` is not constrained
+impl<C: PointeeSized> A for u8 { //~ ERROR: the type parameter `C` is not constrained
```
Comment (oli-obk) [inline tests/ui/layout/unconstrained-param-ice-137308.rs:15]: did you search and replace the test suite for `?Sized`? I'm not sure what's best, but I would have assumed keeping most of the test suite on `?Sized` and only changing what needs changing would be best.

**Review by oli-obk — CHANGES_REQUESTED** [review]
Still need to review bounds.rs

Is there any new stuff that people can rely on and get wrong in unsafe code that we should be checking in miri?

File: library/core/src/ops/unsize.rs (hunk 36 above)
Comment (davidtwco) [reply library/core/src/ops/unsize.rs:36]: Yeah, they're just there because the bootstrap compiler doesn't understand that `PointeeSized` does a relxation.

File: tests/ui/layout/unconstrained-param-ice-137308.rs (hunk 38 above)
Comment (davidtwco) [reply tests/ui/layout/unconstrained-param-ice-137308.rs:15]: I didn't. In this test, for example, `?Sized` would no longer be unconstrained, it would be `MetaSized`-constrained, and so the test would be doing something different (and failing as a consequence) - I only changed tests that failed and needed changing.

Comment (oli-obk) [reply tests/ui/layout/unconstrained-param-ice-137308.rs:15]: I think something is wrong then. `C` is unconstrained because it is not used in the impl, what bounds are on it are irrelevant.

File: tests/incremental/hashes/trait_defs.rs (hunk 37 above)
Comment (davidtwco) [reply tests/incremental/hashes/trait_defs.rs:33]: I'm not sure - it fails without the change. `predicates_of` is where the default bounds/supertrait are added, so I just assumed it was related to that.

File: compiler/rustc_type_ir/src/elaborate.rs (hunk 35 above)
Comment (davidtwco) [reply compiler/rustc_type_ir/src/elaborate.rs:106]: Yeah, I had initially implemented it in the `elaborate` function but `extend_deduped` made more sense in the end.

File: compiler/rustc_ty_utils/src/ty.rs (hunk 34 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: It's a little tricky to do this because `SizedTraitKind` is in `type_ir` so only has `TraitSolverLangItem`, and the mapping between `LangItem` and `TraitSolverLangItem` isn't public, so I just added a `SizedTraitKind::require_lang_item` method that returned the `DefId` and took an `Interner`. I only found this snippet of code to use the function at though, from a couple quick greps of `match sizedness` or `match sized_trait_kind`, I don't get the `LangItem` elsewhere.

File: compiler/rustc_ty_utils/src/ty.rs (hunk 33 above)
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs:66]: Yeah, between the new solver, old solver and `is_trivially_sized`, lots of similar functions, but hard to deduplicate.

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 32 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: Fixed!

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 39]
```diff
@@ -582,6 +583,16 @@ fn try_prove_negated_where_clause<'tcx>(
         return false;
     };
 
+    if let Some(pred) = clause.as_trait_clause()
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/coherence.rs:589]: Fixed

File: compiler/rustc_hir_analysis/src/collect/item_bounds.rs (hunk 31 above)
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/collect/item_bounds.rs:47]: I've reordered these, the difference wasn't significant. I've also pulled forward a change from Part II that removes `adjust_sizedness_predicate` (where I removed `PointeeSized`) and just puts that in `lower_bounds` to avoid lowering any of those predicates in the first place (in Part II, I also need to migrate `Sized` to `const Sized`, which ended up being another change that made sense in `lower_bounds` to make sure it always happened).

File: compiler/rustc_next_trait_solver/src/solve/effect_goals.rs (hunk 30 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/effect_goals.rs]: Fixed

**Comment by davidtwco** [comment]
Rebased and addressed feedback.

> Is there any new stuff that people can rely on and get wrong in unsafe code that we should be checking in miri?

I don't think so, but I'm not as familiar with what type of stuff that would be as I ought to be.

**Review by fee1-dead — CHANGES_REQUESTED** [review]
Already got some comments stashed up, posting them now

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs [hunk 40]
```diff
@@ -32,6 +32,57 @@ use crate::fluent_generated as fluent;
 use crate::hir_ty_lowering::{AssocItemQSelf, HirTyLowerer};
 
 impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
+    /// Check for multiple relaxed default bounds and relaxed bounds of non-sizedness traits.
+    pub(crate) fn check_and_report_invalid_unbounds_on_param(
+        &self,
+        unbounds: SmallVec<[&PolyTraitRef<'_>; 1]>,
+    ) {
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs:39]: This function is just moving the error reporting logic that already existed for default bounds into its own function, so the tests are just what were already there.

File: tests/incremental/hashes/trait_defs.rs (hunk 37 above)
Comment (oli-obk) [reply tests/incremental/hashes/trait_defs.rs:33]: right, the question is why. I don't think your changes should have affected that, so some additional query edges seem to have been added. I wish incremental tests told us why something was dirty 🙃 Would be nice to fix or at least know why

File: compiler/rustc_ty_utils/src/ty.rs (hunk 34 above)
Comment (oli-obk) [reply compiler/rustc_ty_utils/src/ty.rs]: yea makes sense to just not do anything then, thx for checking

File: tests/ui/layout/unconstrained-param-ice-137308.rs (hunk 38 above)
Comment (davidtwco) [reply tests/ui/layout/unconstrained-param-ice-137308.rs:15]: I can check if this test still fails because it might just have been the state of the implementation at the time.

File: compiler/rustc_hir_analysis/src/collect/item_bounds.rs [hunk 41]
```diff
@@ -334,6 +341,13 @@ fn opaque_type_bounds<'tcx>(
...
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/collect/item_bounds.rs:344]: Same thing, reorder to keep it the same everywhere

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs (hunk 40 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs:39]: No, we just check for repeated default bounds where `MetaSized`/`PointeeSized` are irrelevant, and for non-`Sized` relaxed bounds, which was already written such that it would catch `?MetaSized` and `?PointeeSized`.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs [hunk 42]
```diff
@@ -242,90 +428,8 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-            match unbound_def_id {
-                Some(def_id) if !tcx.is_default_trait(def_id) => emit_relax_err(),
-                None => emit_relax_err(),
-                _ => {}
-            }
-        }
-
-        !(seen_unbound || seen_negative_bound || seen_positive_bound)
+        let collected = collect_bounds(hir_bounds, self_ty_where_predicates, trait_def_id);
+        !(collected.positive || collected.maybe || collected.negative)
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs:432]:
```suggestion
        !collected.any()
```

File: tests/incremental/hashes/trait_defs.rs (hunk 37 above)
Comment (davidtwco) [reply tests/incremental/hashes/trait_defs.rs:33]: Confirmed that this change to the test is definitely still necessary.

My best guess is that I check `tcx.trait_is_auto` now? I need that to avoid adding the default supertrait to things like `Copy`, because if I do that, I can't relax it back with `PointeeSized` unless I do it with a `cfg(bootstrap)` (beta rustc won't allow explicit supertraits on auto traits). This could be fixed later by allowing the sizedness traits to be added to auto traits and then once that is in beta, removing the `trait_is_auto` condition (or doing that now with a `cfg` on all(?) our auto traits). 

Other than that, the only methods called in diff additions in all of `rustc_hir_analysis` on `tcx` are:

- `require_lang_item`
- `is_lang_item`
- `is_default_trait`
- `trait_is_auto`

File: tests/ui/layout/unconstrained-param-ice-137308.rs (hunk 38 above)
Comment (davidtwco) [reply tests/ui/layout/unconstrained-param-ice-137308.rs]: I've revisited these tests and they fail with some additional "type annotations needed" errors, which I expect is what I was trying to avoid, but these are likely just downstream of the unconstrained parameter error as there's now an unconstrained `C: MetaSized` instead of bare `C`. I've just blessed these instead in the commit which was changing them.

File: compiler/rustc_middle/src/ty/adt.rs [hunk 43]
```diff
@@ -636,10 +640,14 @@ impl<'tcx> AdtDef<'tcx> {
         tcx.adt_async_destructor(self.did())
     }
 
-    /// Returns a type such that `Self: Sized` if and only if that type is `Sized`,
-    /// or `None` if the type is always sized.
-    pub fn sized_constraint(self, tcx: TyCtxt<'tcx>) -> Option<ty::EarlyBinder<'tcx, Ty<'tcx>>> {
-        if self.is_struct() { tcx.adt_sized_constraint(self.did()) } else { None }
+    /// Returns a type such that `Self: {Meta,Pointee,}Sized` if and only if that type is
+    /// `{Meta,Pointee,}Sized`, or `None` if the type is always {meta,pointee,}sized.
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_middle/src/ty/adt.rs]: I've rewritten the comments on `sizedness_constraint`, `adt_sizedness_constraint` and `sizedness_constraint_for_ty` but I haven't renamed them. I don't think `opt_trailing_field_ty` is the correct name because the functions do sizedness-specific things.

In the case of this specific function, it wouldn't return `None` for a `str` because this is a function on `AdtDef` and could never be a `str`. This could apply to `adt_sizedness_constraint` or `sizedness_constraint_for_ty` and I've clarified what the result would be in the comments of those.

File: compiler/rustc_ty_utils/src/ty.rs [hunk 44]
```diff
@@ -75,15 +95,23 @@ fn defaultness(tcx: TyCtxt<'_>, def_id: LocalDefId) -> hir::Defaultness {
...
+///
+/// For `MetaSized`, there are only a few options for the types in the constraint:
+///     - an pointee-sized type (extern types)
+///     - a type parameter or projection whose sizedness can't be known
+///
+/// For `PointeeSized`, there is only one option for the types in the constraint:
 ///     - a type parameter or projection whose sizedness can't be known
 #[instrument(level = "debug", skip(tcx), ret)]
-fn adt_sized_constraint<'tcx>(
+fn adt_sizedness_constraint<'tcx>(
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_ty_utils/src/ty.rs]: See previous comment

File: library/core/src/ops/deref.rs [hunk 45]
```diff
@@ -267,7 +269,8 @@ impl<T: ?Sized> const Deref for &mut T {
 #[stable(feature = "rust1", since = "1.0.0")]
 #[const_trait]
 #[rustc_const_unstable(feature = "const_deref", issue = "88955")]
-pub trait DerefMut: ~const Deref {
+#[allow(multiple_supertrait_upcastable)] // FIXME(sized_hierarchy): remove this
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply library/core/src/ops/deref.rs]: It's still necessary for bootstrap, but I'll add a `cfg_attr(bootstrap, ..)` in that commit

File: compiler/rustc_hir_analysis/src/collect/item_bounds.rs (hunk 41 above)
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/collect/item_bounds.rs]: Fixed

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs (hunk 42 above)
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs]: Fixed

**Comment by davidtwco** [comment]
I'll assign this to @oli-obk having already done a review rather than add a new reviewer entirely.

**Comment by oli-obk** [comment]
@bors try

cratertime

**Comment by oli-obk** [comment]
@craterbot check

File: compiler/rustc_lint/src/multiple_supertrait_upcastable.rs [hunk 46]
```diff
@@ -46,7 +46,11 @@ impl<'tcx> LateLintPass<'tcx> for MultipleSupertraitUpcastable {
                 .tcx
                 .explicit_super_predicates_of(def_id)
                 .iter_identity_copied()
-                .filter_map(|(pred, _)| pred.as_trait_clause());
+                .filter_map(|(pred, _)| pred.as_trait_clause())
+                .filter(|pred| {
+                    !cx.tcx.is_lang_item(pred.def_id(), hir::LangItem::Sized)
```
Comment (lcnr) [inline compiler/rustc_lint/src/multiple_supertrait_upcastable.rs:51]: i'd expect this lint to never trigger for `Sized` :thinking: if `Sized` is a super trait the trait cannot be used as a trait object, can it?

File: compiler/rustc_next_trait_solver/src/solve/effect_goals.rs [hunk 47]
```diff
@@ -54,21 +57,19 @@ where
...
-                })
-            } else {
-                Err(NoSolution)
+                });
             }
-        } else {
-            Err(NoSolution)
         }
+
+        Err(NoSolution)
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/effect_goals.rs:72]: please move these spurious cleanups/changes into a separate PR

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 48]
```diff
@@ -133,31 +133,45 @@ where
...
+            // check for a `Sized` subtrait when looking for `MetaSized`. `PointeeSized` bounds
+            // are syntactic sugar for a lack of bounds so don't need this.
+            if ecx.cx().is_lang_item(goal_did, TraitSolverLangItem::MetaSized)
+                && ecx.cx().is_lang_item(trait_clause_did, TraitSolverLangItem::Sized)
+                && {
+                    let expected_self_ty = ecx.resolve_vars_if_possible(goal.predicate.self_ty());
+                    let found_self_ty =
+                        ecx.resolve_vars_if_possible(trait_clause.self_ty().skip_binder());
+                    goal.predicate.polarity == trait_clause.polarity()
+                        && expected_self_ty == found_self_ty
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/trait_goals.rs:167]: structurally equatingn (`==`) types does not handle alias types. Create a `<sized_self_type>: MetaSized` assumption instead and then recur.

With your impl, a `<T as Id>::This: Sized` where-clause does not imply `T: MetaSized`. Please add this as a test.

File: compiler/rustc_trait_selection/src/traits/coherence.rs [hunk 49]
```diff
@@ -582,6 +583,19 @@ fn try_prove_negated_where_clause<'tcx>(
...
+    // are syntactic sugar for a lack of bounds so don't need this.
+    if let Some(pred) = clause.as_trait_clause()
+        && is_unelaborated_sizedness_optimisation(
+            root_infcx,
+            pred,
+            param_env.caller_bounds().iter().filter_map(|c| c.as_trait_clause()),
+        )
+    {
+        return false;
+    }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/coherence.rs:597]: why is that necessary. I would expect the change in the trait solver itself to be sufficient.

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 50]
```diff
@@ -506,20 +507,80 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
-        if tcx.is_lang_item(trait_ref.def_id(), LangItem::Sized)
-            && trait_ref.self_ty().is_trivially_sized(tcx)
+        let sizedness = if tcx.is_lang_item(trait_ref.def_id(), LangItem::Sized) {
+            Some(SizedTraitKind::Sized)
+        } else if tcx.is_lang_item(trait_ref.def_id(), LangItem::MetaSized) {
+            Some(SizedTraitKind::MetaSized)
+        } else if tcx.is_lang_item(trait_ref.def_id(), LangItem::PointeeSized) {
+            Some(SizedTraitKind::PointeeSized)
+        } else {
+            None
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:528]: style: instead of using an `Option` here, early return if the trait isn't a `Sized` trait

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 51]
```diff
@@ -506,20 +507,80 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
+        if matches!(sizedness, Some(SizedTraitKind::MetaSized)) {
+            let has_sized_in_param_env =
+                param_env.caller_bounds().iter().filter_map(|c| c.as_trait_clause()).any(|c| {
+                    trait_ref.self_ty() == c.skip_binder().self_ty()
+                        && tcx.is_lang_item(c.def_id(), LangItem::Sized)
+                });
+            if has_sized_in_param_env {
+                debug!("fast path -- metasized paramenv");
+                return true;
+            }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:547]: this is observable if you've got the following environment:
```
where
    MyType<'a, T>: Sized,
    MyType<'static, T>: Sized,
```

Actually proving `MyType<'some_region, T>: [Meta]Sized` would be ambiguous. This fast path does structural equality instead so it may succeed if `'some_region` ended up as literally the same region var as `'a` or `'static`.

I am confident that this can cause MIR borrowck ICE similar to the issue in https://github.com/rust-lang/trait-system-refactor-initiative/issues/27

We're able to prove `MyType<'a, T>: Sized` during HIR typeck. We then erase the region during writeback and replace it with a fresh nll var at the start of borrowck. At this point the fastpath no longer applies, we get ambiguity and an ICE.

What's the perf impact of this fast path?

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 52]
```diff
@@ -506,20 +507,80 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
+    }
+
+    candidates.into_iter().find(|c| {
+        if !infcx.tcx.is_lang_item(c.def_id(), LangItem::Sized) {
+            return false;
+        }
+
+        let expected_self_ty = infcx.resolve_vars_if_possible(predicate.self_ty());
+        let found_self_ty = infcx.resolve_vars_if_possible(c.self_ty());
+        predicate.polarity() == c.polarity() && expected_self_ty == found_self_ty
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:584]: again, structurally comparing types is insufficient if there are aliases/regions

This fast path means we fail to prove `MyType<'_, T>: MetaSized` if there's `MyType<'a, T>: Sized` in the env

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 53]
```diff
@@ -568,6 +568,14 @@ impl<'a, 'tcx> WfPredicates<'a, 'tcx> {
         def_id: DefId,
         args: GenericArgsRef<'tcx>,
     ) -> PredicateObligations<'tcx> {
+        // PERF: `Sized`'s predicates include `MetaSized`, but both are compiler implemented marker
+        // traits, so `MetaSized` will never be WF if `Sized` is WF and vice-versa. Determining
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/wf.rs:572]:
```suggestion
        // traits, so `MetaSized` will always be WF if `Sized` is WF and vice-versa. Determining
```

File: compiler/rustc_type_ir/src/elaborate.rs [hunk 54]
```diff
@@ -132,12 +168,14 @@ impl<I: Interner, O: Elaboratable<I>> Elaborator<I, O> {
                 // Get predicates implied by the trait, or only super predicates if we only care about self predicates.
                 match self.mode {
                     Filter::All => self.extend_deduped(
+                        Some(clause),
                         cx.explicit_implied_predicates_of(data.def_id())
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/elaborate.rs:172]: why not instead do this filter in `implied_predicates_of` and `super_predicates_of`? :thinking:

**Review by lcnr — COMMENTED** [review]
only reviewed the type system changes and have some general thoughts:
- I mentioned this in a review comment. Please move all the unrelated refactorings and style changes out of this PR and land them separately
- a lot of type system tests currently use `?Sized` to mean "no implicit bounds". For most tests, this is just to simplify debugging, but there are at least some tests, e.g. for cycle/overflow handling, where the issue only reproduces without proving `Sized`. I expect these to no longer cover the original issue if we now add a `MetaSized` bound. Please add a `#![rustc_no_implicit_bounds]` (or sth like it) crate attribute in a separate PR which can be used to avoid relying on `?Sized`.
- these sort of type system changes generally make me uncomfortable as it's really easy to miss subtle interactions and insufficiencies. Changing the approach later on tends to be a lot more difficult as it needs to be pretty much *more powerful* than the current impl to avoid introducing regressions. I am somewhat sorry that I am insisting on overwhelmingly theoretical issues. I deeply care about avoiding any user-facing hacks

**Comment by davidtwco** [comment]
Thanks for the review @lcnr, I'll have a look at fixing these this week. I think any of the refactoring changes are just places where I had made a functional change but ended up undoing it while working things out, I'll remove those. It seems looks like the issues are primarily in the optimisations to try and speed things up, I'll back out any that I can't address and see what that does to the perf.

---

A very quick triage of the crater run results, some legit failures in there that I'll look into:

- Failures (6)
  - `slice_trait-0.2.0`
    - "the size for values of type `Self` cannot be known" error related to `core::ops::IndexMut`
  - `fmhall.chess-program` + `severiano-sisneros.jolt_volatility`
    - ```
      error: internal compiler error: Encountered anon const with inference variable args but no error reported
      [INFO] [stdout]   |
      [INFO] [stdout]   = note: delayed at compiler/rustc_trait_selection/src/traits/mod.rs:596:27
      ```
  - `red-lighting123.hwc`
    - ``overflow evaluating the requirement `sum::Sum: Sized` ``
  - `explodingcamera.rust-http-server-from-scratch`
    - Trait alias with a `?Sized` and a bound from a `Fn`
  - `AndreiCravtov.rusty-type-experiments`
    - ```trait bound `T: MetaSized` was not satisfied```
- Spurious (3)
  - `windows_x86_64_gnu-0.48.0`
    - Looks spurious - no such file or directory error during linking
  - `purrie.adventure-book`
    - CMake failures
  - `minigrep_by_mist-0.1.1`
    - Environmental
- Acceptable failures (2)
  - `ben0x539.narrow_box`
    - Using `extern type` in a way that should now fail w/out bounds relaxations
  - `rebenkoy.rust-ice-non_lifetime_binders`
    - Uses `non_lifetime_binders`, like the tests updated in the PR, `?Sized` isn't sufficient for these to be completely relaxed anymore
- All of the ones that previously failed and now pass were spurious failures and so it's okay they pass - not accepting code that used to fail as far as I can tell

**Comment by davidtwco** [comment]
Produced some minimal reproductions from the crater runs:

**red-lightning123.hwc**
```rust
//@ check-pass
//@ compile-flags: --crate-type=lib

use std::marker::PhantomData;

// Derived from `hwc` in crater run

pub struct Token;

pub trait ParseTokens {
    type Output;
}

macro_rules! define_parser_combinator {
    ( $name:ident, $parse_type:ty ) => {
        pub struct $name(pub <$parse_type as ParseTokens>::Output);

        impl ParseTokens for $name {
            type Output = Self;
        }
    };
}

impl<T: ParseTokens + ?Sized> ParseTokens for Box<T> {
    type Output = Box<<T as ParseTokens>::Output>;
}

pub struct Group<T> {
    marker: PhantomData<T>,
}

impl<A: ParseTokens, B: ParseTokens> ParseTokens for Group<(A, B)> {
    type Output = (A, B);
}

define_parser_combinator! {
    Element,
    Group<(
        Box<ElementArray>,
        Box<ElementArray>,
    )>
}

define_parser_combinator! {
    ElementArray,
    Group<(
        Element,
        Element,
    )>
}
```

**`fmhall.chess-program` + `severiano-sisneros.jolt_volatility`**
This one was a nightmare because it was cross-crate and in a macro expansion, and ended up requiring `generic_const_exprs`:

_Auxiliary:_
```rust
#![feature(generic_const_exprs)]

pub trait Tr<PCS, const C: usize> {
    fn foo(bar: PCS) { unimplemented!(); }
}

pub struct Foo;

pub const M: usize = 4;

impl<CS> Tr<CS, M> for Foo {}
```

_Test:_
```rust
//@ aux-build:generic-const-exprs-dep.rs
//@ check-pass
//@ compile-flags: --crate-type=lib

extern crate generic_const_exprs_dep;
use generic_const_exprs_dep::{Tr, Foo};

// Derived from `jolt_volatility` and `chess-program` in crater run

pub fn build(bar: ()) {
    Foo::foo(bar)
}
```

**Comment by lcnr** [comment]
feel free to ignore any `generic_const_exprs` failures.

File: compiler/rustc_lint/src/multiple_supertrait_upcastable.rs (hunk 46 above)
Comment (davidtwco) [reply compiler/rustc_lint/src/multiple_supertrait_upcastable.rs:51]: Removed `Sized` from this commit.

File: compiler/rustc_next_trait_solver/src/solve/effect_goals.rs (hunk 47 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/effect_goals.rs:72]: Removed these changes, they were fixup'ed into the wrong commit from later changes in the Part II with constness.

File: compiler/rustc_trait_selection/src/traits/coherence.rs (hunk 49 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/coherence.rs:597]: I thought this was necessary when I added it but I presume the changes in the trait solver were broken at that point and I mistook that for this being necessary, removed now

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 50 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs:528]: Fixed

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 51 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs:547]: I've removed this particular part of the fast path, will need to re-run perf to see the impact

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 52 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs:584]: Fixed and added test

File: compiler/rustc_trait_selection/src/traits/wf.rs (hunk 53 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/wf.rs:572]: Fixed

**Comment by davidtwco** [comment]
Rebased, addressed most of @lcnr's feedback, fixed the crater regressions and added tests, still to do:

- `red-lightning123.hwc` regression with the new overflow errors
- `#![rustc_no_implicit_bounds]` per @lcnr's request
- re-run perf

**Comment by davidtwco** [comment]
Oh, apparently GitHub is still "processing the push", never seen that before

**Comment by davidtwco** [comment]
I had to `git commit --amend`, make no changes, and then force push - but it's updated now.

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 51 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: There's obviously confounding from the rebase and other changes responding to feedback, but [perf after this change](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=18f4fd1d643f4d3e2d2edf23b46129871523de68&stat=instructions:u) and [perf before this change](https://perf.rust-lang.org/compare.html?start=5961e5ba3daa20d98f549eb9029105ae50c13aed&end=5a7aba305fbc1cffcc0a0e13f4b147809f7276c7&stat=instructions:u).

File: compiler/rustc_trait_selection/src/traits/coherence.rs (hunk 49 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/coherence.rs]: I thought this was necessary as part of the elaboration optimisation, but in attempting to re-add something like https://github.com/rust-lang/rust/pull/137944#discussion_r2059089523, it turns out it's that change which made this necessary.

**Comment by davidtwco** [comment]
935665030a34700440ef08fc6a33f17dd6239a39 regressed performance rather than improve it, so I'll drop that commit.

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 51 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: I tried to re-add this in https://github.com/rust-lang/rust/commit/935665030a34700440ef08fc6a33f17dd6239a39 with a `can_eq` check rather than just structural equality and it regressed performance rather than improved it.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 55]
```diff
@@ -466,7 +470,19 @@ where
...
             match cx.as_lang_item(trait_def_id) {
-                Some(TraitSolverLangItem::Sized) => G::consider_builtin_sized_candidate(self, goal),
+                Some(TraitSolverLangItem::Sized) => {
+                    G::consider_builtin_sizedness_candidates(self, goal, SizedTraitKind::Sized)
+                }
+                Some(TraitSolverLangItem::MetaSized) => {
+                    G::consider_builtin_sizedness_candidates(self, goal, SizedTraitKind::MetaSized)
+                }
+                Some(TraitSolverLangItem::PointeeSized) => {
+                    G::consider_builtin_sizedness_candidates(
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs:480]: ICE baby

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 56]
```diff
@@ -104,17 +105,19 @@ where
...
 where
     D: SolverDelegate<Interner = I>,
     I: Interner,
 {
     match ty.kind() {
-        // impl Sized for u*, i*, bool, f*, FnDef, FnPtr, *(const/mut) T, char, &mut? T, [T; N], dyn* Trait, !
-        // impl Sized for Coroutine, CoroutineWitness, Closure, CoroutineClosure
+        // impl {Meta,Pointee,}Sized for u*, i*, bool, f*, FnDef, FnPtr, *(const/mut) T, char
+        // impl {Meta,Pointee,}Sized for &mut? T, [T; N], dyn* Trait, !, Coroutine, CoroutineWitness
+        // impl {Meta,Pointee,}Sized for Closure, CoroutineClosure
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:120]: no `Pointee` in comments

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 57]
```diff
@@ -171,15 +187,26 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                            // As `ProjectionCandidate` takes an index and not a predicate, a
+                            // "corrected" `<Projection>: MetaSized` candidate cannot be created,
+                            // so instead keep the index of the `<Projection>: Sized` predicate and
+                            // correct for this in confirmation.
+                            candidates.vec.push(ProjectionCandidate(idx));
+                            return;
+                        }
+
                         // We checked the polarity already
                         match selcx.match_normalize_trait_ref(
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:211]: even for unelaborated `Sized` bounds, check `match_normalize_trait_ref` using the trait ref returned by `unelaborated_sizedness_candidate`

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 58]
```diff
@@ -218,6 +245,13 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
     ) -> Result<(), SelectionError<'tcx>> {
         debug!(?stack.obligation);
 
+        if let Some(bound) =
+            util::unelaborated_sizedness_candidate_from_obligation(self.infcx, stack.obligation)
+        {
+            candidates.vec.push(ParamCandidate(bound));
+            return Ok(());
+        }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:253]: also use the below reject logic

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 59]
```diff
@@ -507,19 +509,72 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
         }
     }
 
     false
 }
+
+/// To improve performance, sizedness traits are not elaborated and so special-casing is required
+/// in the trait solver to find a `Sized` candidate for a `MetaSized` obligation. Returns the
+/// predicate to used in the candidate for such a `obligation`, given `candidates`.
+pub(crate) fn unelaborated_sizedness_candidate<'tcx>(
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:540]: `fn prove_meta_sized_via_elaborated_sized`

pls only take a single candidate per call

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 60]
```diff
@@ -507,19 +509,72 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
+        let expected_self_ty = obligation.self_ty();
+        let found_self_ty = c.self_ty();
+        obligation.predicate.polarity() == c.polarity()
+            && expected_self_ty.bound_vars() == found_self_ty.bound_vars()
+            && {
+                let expected_self_ty =
+                    infcx.tcx.instantiate_bound_regions_with_erased(expected_self_ty);
+                let found_self_ty = infcx.tcx.instantiate_bound_regions_with_erased(found_self_ty);
+                infcx.can_eq(obligation.param_env, expected_self_ty, found_self_ty)
+            }
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:564]: && DeepReject::relate_rigid_rigid`

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 61]
```diff
@@ -507,19 +509,72 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
-        if tcx.is_lang_item(trait_ref.def_id(), LangItem::Sized)
-            && trait_ref.self_ty().is_trivially_sized(tcx)
-        {
+        let sizedness = if tcx.is_lang_item(trait_ref.def_id(), LangItem::Sized) {
+            SizedTraitKind::Sized
+        } else if tcx.is_lang_item(trait_ref.def_id(), LangItem::MetaSized) {
+            SizedTraitKind::MetaSized
+        } else if tcx.is_lang_item(trait_ref.def_id(), LangItem::PointeeSized) {
+            SizedTraitKind::PointeeSized
+        } else {
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:524]: this can be faster, use `as_lang_item` , @oli-obk lang item hacks :>

File: compiler/rustc_type_ir/src/elaborate.rs [hunk 62]
```diff
@@ -132,12 +168,14 @@ impl<I: Interner, O: Elaboratable<I>> Elaborator<I, O> {
                 // Get predicates implied by the trait, or only super predicates if we only care about self predicates.
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/elaborate.rs:168]: instead: bail here?

File: compiler/rustc_type_ir/src/elaborate.rs [hunk 63]
```diff
@@ -147,6 +185,7 @@ impl<I: Interner, O: Elaboratable<I>> Elaborator<I, O> {
             }
             // `T: ~const Trait` implies `T: ~const Supertrait`.
             ty::ClauseKind::HostEffect(data) => self.extend_deduped(
+                Some(clause),
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/elaborate.rs:188]: also check for `Sized` and bail here

File: src/tools/miri/src/shims/native_lib.rs [hunk 64]
```diff
@@ -72,7 +72,7 @@ trait EvalContextExtPriv<'tcx>: crate::MiriInterpCxExt<'tcx> {
             }
             // Functions with no declared return type (i.e., the default return)
             // have the output_type `Tuple([])`.
-            ty::Tuple(t_list) if t_list.is_empty() => {
+            ty::Tuple(t_list) if (*t_list).deref().is_empty() => {
```
Comment (lcnr) [inline src/tools/miri/src/shims/native_lib.rs:75]: :thinking:

Comment (davidtwco) [reply src/tools/miri/src/shims/native_lib.rs:75]: Tried this and it doesn't work, so leaving it as-is.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs (hunk 55 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 56 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 61 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: Fixed, also all the other places that I did this.

File: compiler/rustc_type_ir/src/elaborate.rs (hunk 62 above)
Comment (davidtwco) [reply compiler/rustc_type_ir/src/elaborate.rs]: Fixed

File: compiler/rustc_type_ir/src/elaborate.rs (hunk 63 above)
Comment (davidtwco) [reply compiler/rustc_type_ir/src/elaborate.rs]: Fixed

File: compiler/rustc_type_ir/src/predicate.rs [hunk 65]
```diff
@@ -97,6 +97,10 @@ impl<I: Interner> TraitRef<I> {
         )
     }
 
+    pub fn with_def_id(self, interner: I, def_id: I::DefId) -> Self {
+        TraitRef::new_from_args(interner, def_id, self.args)
+    }
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_type_ir/src/predicate.rs]: Fixed by inlining in the two places I was using this.

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs (hunk 58 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs]: Fixed per our discussion earlier

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs (hunk 57 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:224]: Fixed

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 59 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs:538]: Fixed, didn't rename as it is now returning the `candidate`, but I can if we want to.

**Comment by davidtwco** [comment]
Submitted a bunch of perf runs to go overnight to try and isolate the change that caused the regression:

- #141015
- #141016
- #141017
- #141018

**Comment by davidtwco** [comment]
None of those partial reverts explain the 5% regression over the patch's previous regression. Some were mildly better or mildly worse, but not sufficient. I didn't revert each change to exactly what it was proor, but it should have been close enough. Only thing I didn't check was the addition of the `DeepRejectCtxt`, but it seems unlikely to be that?

**Comment by davidtwco** [comment]
It appears that the difference is just changes in the benchmark suite.

File: tests/ui/sized-hierarchy/elaboration-opt-regions-1.rs [hunk 66]
```diff
@@ -0,0 +1,18 @@
...
+//@ compile-flags: --crate-type=lib
+//@ revisions: old next
+//@[next] compile-flags: -Znext-solver
+#![feature(sized_hierarchy)]
+
+use std::marker::{PhantomData, MetaSized, PointeeSized};
+
+struct Foo<'a, T: PointeeSized>(*mut &'a (), T);
+
+fn requires_metasized<'a, T: MetaSized>(f: &T) {}
```
Comment (oli-obk) [inline tests/ui/sized-hierarchy/elaboration-opt-regions-1.rs:11]:
```suggestion
fn requires_metasized<'a, T: MetaSized>(f: &'a T) {}
```

File: tests/ui/sized-hierarchy/trait-aliases.rs [hunk 67]
```diff
@@ -0,0 +1,9 @@
+//@ check-pass
+//@ compile-flags: --crate-type=lib
+#![feature(trait_alias)]
+
+// Tests that `?Sized` is migrated to `MetaSized` in trait aliases.
```
Comment (oli-obk) [inline tests/ui/sized-hierarchy/trait-aliases.rs:5]: How is this test actually testing that?

File: tests/ui/traits/next-solver/cycles/normalizes-to-is-not-productive.stderr [hunk 68]
```diff
@@ -12,6 +12,13 @@ LL | impl<T: Bound, U> Trait<U> for T {
    |         -----     ^^^^^^^^     ^
    |         |
    |         unsatisfied trait bound introduced here
+note: required by a bound in `Bound`
+  --> $DIR/normalizes-to-is-not-productive.rs:8:1
+   |
+LL | / trait Bound {
+LL | |     fn method();
+LL | | }
+   | |_^ required by this bound in `Bound`
```
Comment (oli-obk) [inline tests/ui/traits/next-solver/cycles/normalizes-to-is-not-productive.stderr:21]: bogus note, Can be resolved in follow up, but open an issue in that case

**Review by oli-obk — CHANGES_REQUESTED** [review]
ok! I'm done 😆

🚢 it the moment #140386 lands

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 69]
```diff
@@ -1069,24 +1069,38 @@ pub trait PrettyPrinter<'tcx>: Printer<'tcx> + fmt::Write {
...
                             ty::PredicatePolarity::Negative => has_negative_sized_bound = true,
+                        },
+                        Some(LangItem::MetaSized) => {
+                            has_meta_sized_bound = true;
+                            continue;
+                        }
+                        Some(LangItem::PointeeSized) => {
+                            // Unexpected - `PointeeSized` is the absence of bounds.
+                            has_pointee_sized_bound = true;
+                            continue;
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1101]: please ICE

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs [hunk 70]
```diff
@@ -135,13 +138,20 @@ where
...
-        | ty::Dynamic(..)
-        | ty::Foreign(..)
-        | ty::Alias(..)
-        | ty::Param(_)
-        | ty::Placeholder(..) => Err(NoSolution),
+        // impl {Meta,}Sized for str, [T], dyn Trait
+        ty::Str | ty::Slice(_) | ty::Dynamic(..) => match sizedness {
+            SizedTraitKind::Sized => Err(NoSolution),
+            SizedTraitKind::MetaSized => Ok(ty::Binder::dummy(vec![])),
+            SizedTraitKind::PointeeSized => unreachable!(),
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:145]: when do we want the `PointeeSized` variant of this enum? I feel like pretty much every use site shouldn't consider handling it

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs [hunk 71]
```diff
@@ -413,11 +414,12 @@ where
...
     }
 
-    fn consider_builtin_sized_candidate(
+    fn consider_builtin_sizedness_candidates(
         _ecx: &mut EvalCtxt<'_, D>,
         goal: Goal<I, Self>,
+        _sizedness: SizedTraitKind,
     ) -> Result<Candidate<I>, NoSolution> {
-        panic!("`Sized` does not have an associated type: {:?}", goal);
+        panic!("`Sized`/`MetaSized`/`PointeeSized` does not have an associated type: {:?}", goal);
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:422]:
```suggestion
        panic!("Sized/MetaSized does not have an associated type: {:?}", goal);
```

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 72]
```diff
@@ -507,19 +510,69 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
+            obligation.predicate.skip_binder().trait_ref.args,
+            candidate.skip_binder().trait_ref.args,
+        )
+        && expected_self_ty.bound_vars() == found_self_ty.bound_vars()
+        && {
+            let expected_self_ty =
+                infcx.tcx.instantiate_bound_regions_with_erased(expected_self_ty);
+            let found_self_ty = infcx.tcx.instantiate_bound_regions_with_erased(found_self_ty);
+            infcx.can_eq(obligation.param_env, expected_self_ty, found_self_ty)
+        };
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:564]:
```suggestion
        && drcx.args_may_unify(
            obligation.predicate.skip_binder().trait_ref.args,
            candidate.skip_binder().trait_ref.args,
        );
```
the `args_may_unify` should be enough here :thinking:

style: please change this to use early returns instead

File: compiler/rustc_trait_selection/src/traits/util.rs [hunk 73]
```diff
@@ -507,19 +510,69 @@ impl<'tcx> TypeFolder<TyCtxt<'tcx>> for PlaceholderReplacer<'_, 'tcx> {
...
         }
     }
 
     false
 }
+
+/// To improve performance, sizedness traits are not elaborated and so special-casing is required
+/// in the trait solver to find a `Sized` candidate for a `MetaSized` obligation. Returns the
+/// predicate to used in the candidate for such a `obligation`, given a `candidate`.
+pub(crate) fn unelaborated_sizedness_candidate<'tcx>(
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/util.rs:538]:
```suggestion
pub(crate) fn lazily_elaborate_sizedness_candidate<'tcx>(
```

File: compiler/rustc_type_ir/src/elaborate.rs [hunk 74]
```diff
@@ -111,6 +113,18 @@ impl<I: Interner, O: Elaboratable<I>> Elaborator<I, O> {
             return;
         };
 
+        // PERF(sized-hierarchy): To avoid iterating over sizedness supertraits in
+        // parameter environments, as an optimisation, sizedness supertraits aren't
+        // elaborated, so check if a `Sized` obligation is being elaborated to a
+        // `MetaSized` obligation and emit it. Candidate assembly and confirmation
+        // are modified to check for the `Sized` subtrait when a `MetaSized` obligation
+        // is present.
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/elaborate.rs:121]:
```suggestion
        // elaborated. Candidate assembly and confirmation are modified to lazily
        // check for the `Sized` subtrait when a `MetaSized` obligation is present.
```
emit/omit?

Comment (lcnr) [reply compiler/rustc_type_ir/src/elaborate.rs:121]: also, please explicitly match on `Filter` here even if we treat both variants the same for now and add a FIXME that we need to decide this on a per use basis.

Hmm, alternatively add a separate 2 state enum to the `elaborate`
```rust
enum ElaborateSized {
    Yes,
    No,
}
``` 

E.g. the overlap check in coherence uses elaboration and this one should properly elaborate `MetaSized`

**Review by lcnr — COMMENTED** [review]
the type system impl looks good to me now, modulo some final nits.

This is a breaking change so landing it as is needs a T-types FCP https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/sized.20hierarchy.20.28.23137944.29/near/517823418

Alternatively, make `MetaSized` trivially hold for all types unless `feature(sized_hierarchy)` or `feature(extern_types)` is enabled. This would avoid the breakage and likely also the perf impact.

It's kinda *unsound*:tm: when interacting with other uses of `MetaSized`, but given that this only ever affects extern types, it should not matter

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 75]
```diff
@@ -162,9 +162,10 @@ fn gather_explicit_predicates_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> ty::Gen
...
             }
-
-            ItemKind::Trait(_, _, _, _, self_bounds, ..)
-            | ItemKind::TraitAlias(_, _, self_bounds) => {
+            ItemKind::Trait(_, _, _, _, self_bounds, ..) => {
+                is_trait = Some((self_bounds, item.span));
+            }
+            ItemKind::TraitAlias(_, _, self_bounds) => {
                 is_trait = Some((self_bounds, item.span));
             }
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs]: Yeah, this was left over from when `add_sizedness_bounds` used to be two functions - one for params/assoc types/opaques and another for supertraits, and `IsAuto` was passed in to the supertrait function. Reverted now.

File: compiler/rustc_next_trait_solver/src/solve/trait_goals.rs [hunk 76]
```diff
@@ -131,16 +131,37 @@ where
...
+                let meta_sized_clause = trait_clause
+                    .map_bound(|c| TraitPredicate {
+                        trait_ref: TraitRef::new_from_args(
+                            ecx.cx(),
+                            goal.predicate.def_id(),
+                            c.trait_ref.args,
+                        ),
+                        polarity: c.polarity,
+                    })
+                    .upcast(ecx.cx());
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/trait_goals.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 77]
```diff
@@ -65,71 +65,108 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             let def_id = obligation.predicate.def_id();
             let tcx = self.tcx();
 
-            if tcx.is_lang_item(def_id, LangItem::Copy) {
-                debug!(obligation_self_ty = ?obligation.predicate.skip_binder().self_ty());
+            match tcx.as_lang_item(def_id) {
+                Some(LangItem::Copy) => {
+                    debug!(obligation_self_ty = ?obligation.predicate.skip_binder().self_ty());
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs]: #140386 has landed and I've rebased.

File: tests/ui/sized-hierarchy/elaboration-opt-regions-1.rs (hunk 66 above)
Comment (davidtwco) [reply tests/ui/sized-hierarchy/elaboration-opt-regions-1.rs]: Fixed

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 69 above)
Comment (davidtwco) [reply compiler/rustc_middle/src/ty/print/pretty.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs (hunk 70 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs]: Removed that variant of `SizedTraitKind` and removed a bunch of `unreachable` branches.

File: compiler/rustc_next_trait_solver/src/solve/effect_goals.rs [hunk 78]
```diff
@@ -198,11 +199,12 @@ where
...
     }
 
-    fn consider_builtin_sized_candidate(
+    fn consider_builtin_sizedness_candidates(
         _ecx: &mut EvalCtxt<'_, D>,
         _goal: Goal<I, Self>,
+        _sizedness: SizedTraitKind,
     ) -> Result<Candidate<I>, NoSolution> {
-        unreachable!("Sized is never const")
+        unreachable!("Sized/MetaSized/PointeeSized is never const")
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/effect_goals.rs]: Fixed

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs (hunk 71 above)
Comment (davidtwco) [reply compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs]: Removed `PointeeSized` here but kept the backticks because the other functions in this file all had them.

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 72 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: Fixed

File: compiler/rustc_trait_selection/src/traits/util.rs (hunk 73 above)
Comment (davidtwco) [reply compiler/rustc_trait_selection/src/traits/util.rs]: Fixed

File: compiler/rustc_type_ir/src/elaborate.rs (hunk 74 above)
Comment (davidtwco) [reply compiler/rustc_type_ir/src/elaborate.rs:140]: Fixed, added `ElaborateSized`, defaulting it to `ElaborateSized::No` in the `Elaborator`, and then toggling it to `ElaborateSized::Yes` in coherence.

**Comment by oli-obk** [comment]
# t-types FCP Report

We're proposing to merge rust-lang/rust#137944. It is the first half of an unstable implementation of rust-lang/rfcs#3729, adding new supertraits of `Sized` - `MetaSized` and `PointeeSized` - to `std::marker`.

A quick refresher of the RFC: `MetaSized` is implemented for everything except `extern type` and is intended to correspond to those types where their size is known given pointer metadata (string slices, dyn trait, etc) - basically what `?Sized` means today. `PointeeSized` is for when a type's size is unknowable and is implemented for everything including `extern type`. This allows a distinction to be drawn between `extern type` and everything else, allowing `size_of_val` and `align_of_val` to reject instantiations with `extern type`, unblocking that feature. Both names are subject to bikeshed in the RFC.

This half of the RFC could feasibly be stabilised without the rest of the RFC's contents and unblocks `extern type`s. There are minimal edition migrations that could be performed prior to stabilisation, see *Next steps*.

## Summary of changes
Of relevance to the types team:
- Syntax/lowering changes for context:
  - `?Sized` is treated as syntactic sugar for a `MetaSized` bound
  - Adding a `MetaSized` or `PointeeSized` bound will remove the default `Sized` bound
- `PointeeSized` is syntactic sugar for an absence of any sizedness bounds (like `?Sized` previously)
- `MetaSized` and `PointeeSized` have builtin impls in the trait system
  - This is largely a small generalisation of the existing builtin `Sized` impl
- `MetaSized` is added as a default supertrait to all traits without an explicit `Sized` supertrait
  - Except auto traits, as writing an explicit supertrait is prohibited and this would need a bootstrap bump before automatic addition to auto traits could be added
- Some bounds in the compiler and standard library have been relaxed to `PointeeSized` to permit continued use of `extern type` where this was already present
- To improve performance:
  - `Sized` is skipped during elaboration and this is explicitly handled in candidate assembly and confirmation
  - `MetaSized` and `PointeeSized` are assumed to be well-formed if `Sized` is
- There has been a crater run (see *Breaking changes* below)

### Previous patches
The following patches have been landed already in support of this work:
- rust-lang/rust#137599
- rust-lang/rust#137600
- rust-lang/rust#137601
- rust-lang/rust#137602
- rust-lang/rust#137603
- rust-lang/rust#137604
- rust-lang/rust#137606
- rust-lang/rust#137613
- rust-lang/rust#139577
- rust-lang/rust#140978

## Breaking changes
There is one known breaking change in this patch, due to `?Sized` now introducing a bound where it did not previously:

```rust
trait ParseTokens {
    type Output;
}
impl<T: ParseTokens + ?Sized> ParseTokens for Box<T> {
    type Output = ();
}

struct Element(<Box<Box<Element>> as ParseTokens>::Output);
impl ParseTokens for Element {
    type Output = ();
}
```

This is fixed with the next trait solver, but with the current trait solver has the following behaviour:
- `Element: MetaSized`
- `<Box<Box<Element>> as ParseTokens>::Output: MetaSized`
- Normalize associated type, requires `Box<Element>: ParseTokens`
- Requires `Element: MetaSized` cycle, goes through the non-coinductive `Box<Element>: ParseTokens` obligation, resulting in an overflow

Without these changes, there was no `Element: MetaSized` constraint as `T: ?Sized` did not introduce any constraints.

This case was discovered in a crater run in the [red-lighting123/hwc](https://github.com/red-lightning123/hwc) repository, it does not appear to be on crates.io or be a dependency of any other packages.

## Performance

This is currently an average 0.9% icount regression ([summary comment](https://github.com/rust-lang/rust/pull/137944#issuecomment-2880497028)/[perf report](https://perf.rust-lang.org/compare.html?start=414482f6a0d4e7290f614300581a0b55442552a3&end=bde19de91a25b5b6363890bcb8bc28b42263f16e&stat=instructions:u)), with a maximum on 9.08% on incr-full check and a maximum of 6.75% on non-incr check (both with diesel). Crates with many traits and generic parameters are most impacted.

Many attempts have been made to improve the performance and it's probably still possible to improve it somewhat, but it would be easier to do this in a follow-up to avoid needing to maintain the entire patch in a PR.

Successful attempts to improve performance have included:
- Re-using the `Sized` fast-path from `type_op_prove_predicate` in more places and adding `MetaSized` to it
  - rust-lang/rust#139577 and 37d1e84d89915005c29d6f110f06254a15712315
- Avoiding elaboration of `Sized`
  - ff7531b81e023ac6fb5598f8c6b9b1a77a55eeb2
- Skipping `nominal_obligations` for `Sized`
  - 5e09173cf111536336cdc9f0996ca3916b17e925

Unsuccessful attempts have included:
- Splitting `ParamEnv::caller_bounds` into multiple fields
  - rust-lang/rust#139576
- Various experimental tweaks to the patch itself
  - rust-lang/rust#139663
  - rust-lang/rust#139684
  - rust-lang/rust#139725
  - rust-lang/rust#141018
  - rust-lang/rust#141015
  - rust-lang/rust#141017
  - rust-lang/rust#141016

## Approving reviews
There have been multiple reviews from @fee1-dead, @oli-obk, @lcnr, @workingjubilee and @fmease, culminating in:
- @oli-obk left an approving review in https://github.com/rust-lang/rust/pull/137944#pullrequestreview-2856698486
- @lcnr left an approving review in https://github.com/rust-lang/rust/pull/137944#pullrequestreview-2860421607

## Next steps
- Add a `#[rustc_no_implicit_bounds]` attribute and use this in type system tests
  - Requested by @lcnr
  - Would avoid churn for future patches where default bounds just get in the way of debugging or what is being tested
  - Tests with unconstrained parameters are already updated in this patch
- Investigate relaxing `Deref::Target`'s `?Sized` to `PointeeSized`
  - Technically a breaking change but would enable much greater use of `PointeeSized`, quite unlikely to actually break anyone
    - If unsuccessful, alternatives will be investigated
    - If successful, rust-lang/rust#137603 will be reverted
- Migrate `?Sized` to `MetaSized` and prohibit `?Sized` over an edition (w/ feature gate enabled)
- Evaluate where relaxation of other standard library bounds to `PointeeSized` is appropriate
- Implement part two with `const Sized`/`const MetaSized`
  - This has more complicated migration issues which need considered, but these are largely separate from this half and this half has value on its own

@rustbot merge

**Comment by oli-obk** [comment]
@rfcbot fcp merge

**Comment by compiler-errors** [comment]
Can you rerun perf one more time? I'd like to see if this work has a negative effect on the new trait solver, which is now in the perf suite.

**Comment by lcnr** [comment]
I am slightly uncomfortable about breaking the pattern in https://github.com/red-lightning123/hwc. We could land this while just blanket assuming `T: MetaSized` for all `T` unless `feature(extern_types)` or `feature(sized_hierarchy)` is enabled and then wait for the new solver to actually stabilize the new traits. Esp because I cannot actually fix this error as a crate author without significantly restructuring these impls from what I can tell.

As a concrete question, what's the expected timeline to properly stabilize this feature? If it's expected to take at least half a year, I would like to block enabling this by default on the new solver. Otherwise I am fine as is. Either way, I don't feel strongly enough for this to be blocking, so 

@rfcbot reviewed

**Comment by oli-obk** [comment]
@bors r+ p=5

Let's not let this bit rot any more

**Comment by workingjubilee** [comment]
Handwritten minicores.

**Comment by workingjubilee** [comment]
572b452bd50ae2c01ee783f584dbcd3fbd2e87f9 is in so this should be good to go after rebase.

**Comment by davidtwco** [comment]
I thought I had checked all the tests for missing lang items after the last failure but this time I'm doubly sure.

**Comment by davidtwco** [comment]
Thanks @oli-obk, @lcnr, @fee1-dead, @fmease and @workingjubilee for reviews!

**Comment by Kobzol** [comment]
(Note: the bootstrap change is unrelated to this PR, we used to unnecessarily compile too much stuff in the bootstrap benchmark).

**Comment by rylev** [comment]
As noted in [this summary comment](https://github.com/rust-lang/rust/pull/137944#issuecomment-2912207485), the performance regression is expected and will be addressed in follow ups. 

@rustbot label: +perf-regression-triaged
