### PR TITLE
MIR: terminate unreachable blocks in construct_const

### LINKED ISSUE #46843: ICE with match on non-const functions in constant definitions
```rust
enum Thing { This, That }

fn non_const() -> Thing {
    Thing::This
}

pub const Q: i32 = match non_const() {
    Thing::This => 1,
    Thing::That => 0
};
```

```
error: internal compiler error: /checkout/src/librustc_mir/build/mod.rs:534: no terminator on block 10

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (0077d128d 2017-12-14) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:448:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

([playground](https://play.rust-lang.org/?gist=537f252c52447e25c6b072d469d5232a&version=nightly))

This ICEs on nightly/beta, but produces a correct error on stable.

Originally reported on Reddit [here](https://www.reddit.com/r/rust/comments/7kulgv/before_i_report_this_as_a_bug_let_me_ask_here/).

### PR DESCRIPTION
**Pull request by Deewiant**
Fixes #46843.

#45821 added unreachable blocks in matches, which were terminated in
construct_fn but not in construct_const, causing a panic due to "no
terminator on block" when constants involved matching on enums.

The "unimplemented expression type" error may go away in the future, the
key is that we see the E0015 about using a non-const function and then
don't ICE.

### CODE REVIEW

File: src/librustc_mir/build/mod.rs [hunk 1]
```diff
@@ -472,6 +472,13 @@ fn construct_const<'a, 'gcx, 'tcx>(hir: Cx<'a, 'gcx, 'tcx>,
     // Constants can't `return` so a return block should not be created.
     assert_eq!(builder.cached_return_block, None);
 
+    // Constants may be match expressions in which case an unreachable block may
+    // be created, so terminate it properly.
+    if let Some(unreachable_block) = builder.cached_unreachable_block {
+        builder.cfg.terminate(unreachable_block, source_info,
+                              TerminatorKind::Unreachable);
+    }
```
Comment (eddyb) [inline src/librustc_mir/build/mod.rs]: If this is also in `construct_fn`, can it be moved to `Builder::finish`?

Comment (Deewiant) [reply src/librustc_mir/build/mod.rs]: Maybe, but it's not obvious to me how that could happen. The call to `terminate` depends on `source_info` which is defined differently here than in `construct_fn`, and doesn't seem like it could be obtained in a general fashion in `Builder::finish`.

**Comment by alexcrichton** [comment]
Looks like we forgot to backport this for 1.23.0 (sorry about that!) so removing beta tags
