### PR TITLE
Pretty-print macro matchers instead of using source code

### LINKED ISSUE #86208: rustdoc: Regression in display of `macro_rules!` matchers
Oddly enough, the two lines (and the areas around them) that show up when I grep for `"macro_rules!` in rustdoc don't appear to have changed at all in a while, so I'm not sure what caused this regression. Perhaps the span of the matcher changed? I wasn't able to reproduce this locally, even when I tried using a cross-crate re-export with a copy-pasted version of `core::todo` (modulo replacing `$crate::` with `::std::`). Also, the bug doesn't appear with, e.g., `panic!`, but does with `compile_error!`. So, this seems to be a subtle bug.

```console
$ rg '"macro_rules!' src/librustdoc/
src/librustdoc/clean/mod.rs
2167:                "macro_rules! {} {{\n{}}}",

src/librustdoc/clean/inline.rs
541:                "macro_rules! {} {{\n{}}}",
```

### [beta](https://doc.rust-lang.org/beta/std/macro.todo.html) (incorrect)

image

### [stable](https://doc.rust-lang.org/stable/std/macro.todo.html) (correct)

image

### PR DESCRIPTION
**Pull request by camelid**
Fixes #86208.

### CODE REVIEW

**Comment by camelid** [comment]
Beta-nominating because this fixes a `P-high` stable-to-beta regression.

**Comment by camelid** [comment]
Before/after:

#### stable (pre-regression)

image


#### beta (with regression)

image


#### this PR (with fix)

image

**Comment by camelid** [comment]
I left some comments in the commit messages too, so they may be helpful to read.

File: src/test/rustdoc/macro_rules-matchers.rs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+// @has - '//span[@class="op"]' '='
+// @has - '//span[@class="op"]' '>'
+// @has - '{ ... };'
+
+// @has - '($ ($'
+// @has - '//span[@class="ident"]' 'arg'
+// @has - ':'
+// @has - '//span[@class="ident"]' 'tt'
+// @has - '//span[@class="op"]' '+'
+// @has - ')'
```
Comment (camelid) [inline src/test/rustdoc/macro_rules-matchers.rs:22]: Do you know of a way to do a `@has` check that matches on the `innerText` of an element (in this case, `<pre class="rust macro">`) to avoid this mess?

**Comment by camelid** [comment]
I figured out a way to print the matchers in a prettier way, but it may have edge cases that I'm not aware of. Here's the new output:

image

And here's what the code looks like:

```rust
pub(super) fn render_macro_matcher(matcher: &TokenTree) -> String {
    match matcher {
        TokenTree::Token(tok) => rustc_ast_pretty::pprust::token_to_string(tok),
        TokenTree::Delimited(_span, delim_tok, stream) => {
            let open_tok = Token::new(token::OpenDelim(*delim_tok), DUMMY_SP);
            let close_tok = Token::new(token::CloseDelim(*delim_tok), DUMMY_SP);
            format!(
                "{}{}{}",
                rustc_ast_pretty::pprust::token_to_string(&open_tok),
                stream.trees().map(|tt| render_macro_matcher(&tt)).collect::<String>(),
                rustc_ast_pretty::pprust::token_to_string(&close_tok)
            )
        }
    }
}
```

File: src/librustdoc/clean/utils.rs [hunk 2]
```diff
@@ -562,3 +547,18 @@ crate fn has_doc_flag(attrs: ty::Attributes<'_>, flag: Symbol) -> bool {
...
 /// Set by `bootstrap::Builder::doc_rust_lang_org_channel` in order to keep tests passing on beta/stable.
 crate const DOC_RUST_LANG_ORG_CHANNEL: &'static str = env!("DOC_RUST_LANG_ORG_CHANNEL");
+
+/// Render a sequence of macro arms in a format suitable for displaying to the user
+/// as part of an item declaration.
+pub(super) fn render_macro_arms(matchers: &[TokenTree]) -> String {
+    matchers
+        .iter()
+        .map(|matcher| format!("    {} => {{ ... }};\n", render_macro_matcher(matcher)))
+        .collect::<String>()
```
Comment (jyn514) [inline src/librustdoc/clean/utils.rs:557]: Rather than allocating a new string for each arm, can you use a for loop and push_str?

File: src/librustdoc/clean/utils.rs [hunk 3]
```diff
@@ -562,3 +547,18 @@ crate fn has_doc_flag(attrs: ty::Attributes<'_>, flag: Symbol) -> bool {
...
+}
+
+/// Render a macro matcher in a format suitable for displaying to the user
+/// as part of an item declaration.
+pub(super) fn render_macro_matcher(matcher: &TokenTree) -> String {
+    rustc_ast_pretty::pprust::tt_to_string(matcher)
+}
```
Comment (jyn514) [inline src/librustdoc/clean/utils.rs:564]: Why have this as a separate function? Just use tt_to_string.

File: src/test/rustdoc/macro_rules-matchers.rs (hunk 1 above)
Comment (jyn514) [reply src/test/rustdoc/macro_rules-matchers.rs:22]: I don't, @GuillaumeGomez may.

Actually my understanding is that is *always* used innerText, are you sure doing it the obvious way doesn't work?

File: src/librustdoc/clean/inline.rs [hunk 4]
```diff
@@ -530,20 +529,18 @@ fn build_macro(cx: &mut DocContext<'_>, did: DefId, name: Symbol) -> clean::Item
     let imported_from = cx.tcx.crate_name(did.krate);
     match cx.enter_resolver(|r| r.cstore().load_macro_untracked(did, cx.sess())) {
         LoadedMacro::MacroDef(def, _) => {
-            let matchers: Vec<Span> = if let ast::ItemKind::MacroDef(ref def) = def.kind {
+            let matchers: Vec<_> = if let ast::ItemKind::MacroDef(ref def) = def.kind {
                 let tts: Vec<_> = def.body.inner_tokens().into_trees().collect();
-                tts.chunks(4).map(|arm| arm[0].span()).collect()
+                // FIXME: remove this clone
```
Comment (jyn514) [inline src/librustdoc/clean/inline.rs:534]: I don't think this can be removed, I would just remove the comment.

**Review by jyn514 — COMMENTED** [review]
> I figured out a way to print the matchers in a prettier way, but it may have edge cases that I'm not aware of. 

I don't think rustdoc's pretty print should behave differently from rustc's. Can you change this in rustc_ast_pretty instead? It should be easier there because these already have to be handled.

File: src/test/rustdoc/macro_rules-matchers.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/macro_rules-matchers.rs:22]: Just like @jyn514 said. The problem might be that the text doesn't "look like" what you might expect but that's it. :)

Comment (camelid) [reply src/test/rustdoc/macro_rules-matchers.rs:22]: I had tried something like `@has - 'macro_rules! todo {'` and it failed; maybe I need to explicitly specify `//pre`? I also had this issue in #83501 where `@has - 'Size: 1 byte'` didn't work because `Size:` was wrapped with `<b>`.

Comment (GuillaumeGomez) [reply src/test/rustdoc/macro_rules-matchers.rs:22]: Ah! Maybe try with `//text()` at the end.

**Comment by camelid** [comment]
> Can you change this in rustc_ast_pretty instead? It should be easier there because these already have to be handled.

The problem is that they *aren't* already handled. For example, this is what [`print_tt()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast_pretty/pprust/state/trait.PrintState.html#method.print_tt)'s docs say (`tt_to_string()` is just a wrapper around this function):

> This doesn’t deserve to be called “pretty” printing, but it should be meaning-preserving. A quick hack that might help would be to look at the spans embedded in the TTs to decide where to put spaces and newlines. But it’d be better to parse these according to the grammar of the appropriate macro, transcribe back into the grammar we just parsed from, and then pretty-print the resulting AST nodes (so, e.g., we print expression arguments as expressions). It can be done! I think.

From what I can tell, it just puts a space after every token, which is why the output is not so great:

```rust
        match tt {
            TokenTree::Token(token) => {
                let token_str = self.token_to_string_ext(&token, convert_dollar_crate);
                self.word(token_str);
                if let token::DocComment(..) = token.kind {
                    self.hardbreak()
                }
            }
            // ...
```

So I don't think it would be easier to change in `rustc_ast_pretty`. It might even be harder because we'd have to deal with the existing pretty-printing logic.

File: src/librustdoc/clean/utils.rs (hunk 3 above)
Comment (camelid) [reply src/librustdoc/clean/utils.rs:564]: We may not use `tt_to_string` in the future, or we may have additional logic, so I'd rather err on the side of having an extra function. But I can remove it if you prefer.

Comment (jyn514) [reply src/librustdoc/clean/utils.rs:564]: Please remove it until and unless we add more logic.

Comment (camelid) [reply src/librustdoc/clean/utils.rs:564]: Actually, `render_macro_matcher` is used in another place, for rendering macros 2.0. I'd really rather keep it so there aren't multiple places to update later on.

File: src/librustdoc/clean/inline.rs (hunk 4 above)
Comment (camelid) [reply src/librustdoc/clean/inline.rs:534]: I found a way to get rid of the `clone` in `clean/mod.rs` and avoid collecting into a `Vec`, but I'm not sure if it's worth it. What do you think?

```diff
diff --git a/src/librustdoc/clean/inline.rs b/src/librustdoc/clean/inline.rs
index 613ac60a9ba..03304b4b981 100644
--- a/src/librustdoc/clean/inline.rs
+++ b/src/librustdoc/clean/inline.rs
@@ -531,7 +531,6 @@ fn build_macro(cx: &mut DocContext<'_>, did: DefId, name: Symbol) -> clean::Item
         LoadedMacro::MacroDef(def, _) => {
             let matchers: Vec<_> = if let ast::ItemKind::MacroDef(ref def) = def.kind {
                 let tts: Vec<_> = def.body.inner_tokens().into_trees().collect();
-                // FIXME: remove this clone
                 tts.chunks(4).map(|arm| arm[0].clone()).collect()
             } else {
                 unreachable!()
@@ -540,7 +539,7 @@ fn build_macro(cx: &mut DocContext<'_>, did: DefId, name: Symbol) -> clean::Item
             let source = format!(
                 "macro_rules! {} {{\n{}}}",
                 name.clean(cx),
-                utils::render_macro_arms(&matchers, ";")
+                utils::render_macro_arms(matchers.iter(), ";")
             );
 
             clean::MacroItem(clean::Macro { source, imported_from: Some(imported_from) })
diff --git a/src/librustdoc/clean/mod.rs b/src/librustdoc/clean/mod.rs
index 2949f502928..0b0ff34b71a 100644
--- a/src/librustdoc/clean/mod.rs
+++ b/src/librustdoc/clean/mod.rs
@@ -2161,11 +2161,10 @@ fn clean(&self, cx: &mut DocContext<'_>) -> Item {
         let name = renamed.unwrap_or(item.ident.name);
         let tts = item.ast.body.inner_tokens().trees().collect::<Vec<_>>();
         // Extract the macro's matchers. They represent the "interface" of the macro.
-        // FIXME: remove this clone
-        let matchers = tts.chunks(4).map(|arm| arm[0].clone()).collect::<Vec<_>>();
+        let matchers = tts.chunks(4).map(|arm| &arm[0]);
 
         let source = if item.ast.macro_rules {
-            format!("macro_rules! {} {{\n{}}}", name, render_macro_arms(&matchers, ";"))
+            format!("macro_rules! {} {{\n{}}}", name, render_macro_arms(matchers, ";"))
         } else {
             let vis = item.vis.clean(cx);
             let def_id = item.def_id.to_def_id();
@@ -2175,14 +2174,14 @@ fn clean(&self, cx: &mut DocContext<'_>) -> Item {
                     "{}macro {}{} {{\n    ...\n}}",
                     vis.to_src_with_space(cx.tcx, def_id),
                     name,
-                    matchers.iter().map(render_macro_matcher).collect::<String>(),
+                    matchers.map(render_macro_matcher).collect::<String>(),
                 )
             } else {
                 format!(
                     "{}macro {} {{\n{}}}",
                     vis.to_src_with_space(cx.tcx, def_id),
                     name,
-                    render_macro_arms(&matchers, ","),
+                    render_macro_arms(matchers, ","),
                 )
             }
         };
diff --git a/src/librustdoc/clean/utils.rs b/src/librustdoc/clean/utils.rs
index d90ee21cbd3..45973a7c194 100644
--- a/src/librustdoc/clean/utils.rs
+++ b/src/librustdoc/clean/utils.rs
@@ -551,7 +551,10 @@ fn print_const_with_custom_print_scalar(tcx: TyCtxt<'_>, ct: &'tcx ty::Const<'tc
 
 /// Render a sequence of macro arms in a format suitable for displaying to the user
 /// as part of an item declaration.
-pub(super) fn render_macro_arms(matchers: &[TokenTree], arm_delim: &str) -> String {
+pub(super) fn render_macro_arms<'a>(
+    matchers: impl Iterator<Item = &'a TokenTree>,
+    arm_delim: &str,
+) -> String {
     let mut out = String::new();
     for matcher in matchers {
         writeln!(out, "    {} => {{ ... }}{}", render_macro_matcher(matcher), arm_delim).unwrap();
```

File: src/test/rustdoc/macro_rules-matchers.rs (hunk 1 above)
Comment (camelid) [reply src/test/rustdoc/macro_rules-matchers.rs:22]: Hmm, it doesn't seem to be working. `//text()` by itself gave this error:

```
27: Non-absolute XPath is not supported due to implementation issues
	    // @has - '//text()' 'macro_rules! macro1 {'
28: Non-absolute XPath is not supported due to implementation issues
	    // @has - '//text()' '() => { ... };'
29: Non-absolute XPath is not supported due to implementation issues
	    // @has - '//text()' '$ ($ arg : expr), +) => { ... };'
30: Non-absolute XPath is not supported due to implementation issues
	    // @has - '//text()' '}'

Encountered 4 errors
```

and `//pre//text()` gave this:

```
27: @has check failed
	`XPATH PATTERN` did not match
	    // @has - '//pre//text()' 'macro_rules! macro1 {'
28: @has check failed
	`XPATH PATTERN` did not match
	    // @has - '//pre//text()' '() => { ... };'
29: @has check failed
	`XPATH PATTERN` did not match
	    // @has - '//pre//text()' '$ ($ arg : expr), +) => { ... };'
30: @has check failed
	`XPATH PATTERN` did not match
	    // @has - '//pre//text()' '}'

Encountered 4 errors
```

I also tried `//pre///text()` (extra slash), but that didn't work either.

**Comment by Mark-Simulacrum** [comment]
Dropping beta nomination; this is not ready for beta backport based on the extensive discussion on PR and #86208 does not seem like a critical bug. #86208 will shortly be a stable/stable regression and I don't think this warrants a backport in that case.

**Comment by camelid** [comment]
> Dropping beta nomination; this is not ready for beta backport based on the extensive discussion on PR and #86208 does not seem like a critical bug. #86208 will shortly be a stable/stable regression and I don't think this warrants a backport in that case.

Yeah, I realized that a backport into 1.53 wouldn't make sense, but I left the label on since this will likely land in 1.55 and need to be backported to 1.54. Should I just wait until 1.53 is released before adding the label back?

**Comment by Mark-Simulacrum** [comment]
I do not think it should be backported to 1.54 either; it is merely fixing a (seemingly to me) minor bug, and not patching a beta regression.

**Comment by jyn514** [comment]
@Mark-Simulacrum it is a beta regression (stable now; it broke in 1.53), but for something that has been broken and fixed several times in the past.

File: src/librustdoc/clean/utils.rs (hunk 3 above)
Comment (jyn514) [reply src/librustdoc/clean/utils.rs:566]: I don't understand why you think this would ever change. Rustdoc uses rustc in *lots* of places, it doesn't make sense to wrap every single one in our own function.

File: src/librustdoc/clean/inline.rs (hunk 4 above)
Comment (jyn514) [reply src/librustdoc/clean/inline.rs:534]: Sure, seems fine. You forgot to remove the first `.clone()` though :P

File: src/librustdoc/clean/utils.rs (hunk 3 above)
Comment (jyn514) [reply src/librustdoc/clean/utils.rs:566]: Oh I see, this is the function you mentioned above for removing the whitespace in the matcher. I think we should keep the function if we keep your special-casing, and remove it if not. And I do like that the special-casing makes it prettier. So I guess I'm in favor of keeping it.

Comment (jyn514) [reply src/librustdoc/clean/utils.rs:566]: See also the discussion in https://github.com/rust-lang/compiler-team/issues/403

File: src/test/rustdoc/decl_macro.rs [hunk 5]
```diff
@@ -18,8 +18,8 @@ pub macro my_macro_2($($tok:tt)*) {
 
 // @has decl_macro/macro.my_macro_multi.html //pre 'pub macro my_macro_multi {'
 // @has - //pre '(_) => { ... },'
-// @has - //pre '($foo:ident . $bar:expr) => { ... },'
-// @has - //pre '($($foo:literal),+) => { ... }'
+// @has - //pre '($ foo : ident.$ bar : expr) => { ... },'
+// @has - //pre '($ ($ foo : literal), +) => { ... },'
```
Comment (bjorn3) [inline src/test/rustdoc/decl_macro.rs:22]: This is less readable IMO. The `$foo:ident` is semantically a single entity. I have never seen anyone write it with spaces inbetween.

Comment (jyn514) [reply src/test/rustdoc/decl_macro.rs:22]: See https://github.com/rust-lang/rust/pull/86282#issuecomment-860296914.

File: src/librustdoc/clean/inline.rs (hunk 4 above)
Comment (camelid) [reply src/librustdoc/clean/inline.rs]: Done! :)

File: src/librustdoc/clean/utils.rs (hunk 2 above)
Comment (camelid) [reply src/librustdoc/clean/utils.rs]: I changed it to use `writeln!`, which I think should generate code fairly similar to `push_str`, but is more readable.

**Comment by camelid** [comment]
> I figured out a way to print the matchers in a prettier way, but it may have edge cases that I'm not aware of.

Ok, here's an edge case, though it's not even that "edge":

```rust
#[macro_export]
macro_rules! foo {
    (abc 123) => {};
}
```

renders as:

```rust
macro_rules! foo {
    (abc123) => { ... };
}
```

which has a very different meaning.

**Comment by jyn514** [comment]
Ok. I think we should render the matchers with spaces then - there may be other regressions and I would rather have it be ugly than wrong.

**Comment by camelid** [comment]
> Ok. I think we should render the matchers with spaces then - there may be other regressions and I would rather have it be ugly than wrong.

Yeah, that's what I think too. I'm currently doing a quick experiment to see if I can avoid the space after `$`, because that's the most weird-looking part, and I don't think it can cause conflicts.

**Comment by camelid** [comment]
Hmm, I feel confused about how to stop it from emitting a space. I asked [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/pretty-print.20without.20space) to see if anyone can help me figure it out.

**Comment by jyn514** [comment]
r=me with CI passing, thanks for fixing this!

**Comment by jyn514** [comment]
Oh, please squash the commits first though.

**Comment by camelid** [comment]
The `rustc_ast_pretty` change I made affect some test output. @jyn514 do you want to take a look at that before we merge? From what I can see in https://github.com/rust-lang/rust/issues/65207#issuecomment-539726344 and https://github.com/rust-lang/rust/issues/63896#issuecomment-530563612, whitespace changes in pretty-printing output should be okay.

**Comment by camelid** [comment]
Weird, I thought I blessed all the tests...

**Comment by camelid** [comment]
It might be a good idea to have someone on T-compiler review the pretty-printer change to make sure it doesn't have edge cases that I'm not aware of. Do you want to ping someone who can review that part of the code?

**Comment by jyn514** [comment]
I guess we should. But AFAIK rustc_ast_pretty is mostly only used for pretty-printing.

r? @petrochenkov

**Comment by camelid** [comment]
> I guess we should. But AFAIK rustc_ast_pretty is mostly only used for -Zunpretty.

I think the problem is that `stringify!` relies on `rustc_ast_pretty`.

For example, this code:

```rust
fn main() {
    println!("{}", stringify!($foo));
}
```

produces the following on **nightly**:

```
$ foo
```

but produces this instead **after this PR**:

```
$foo
```

**Comment by petrochenkov** [comment]
It seems fine to omit the space after `$`, although eventually we should fully preserve token jointness information produced by lexer and pretty-print precisely instead of guessing with `fn tt_prepend_space`.

>I think the problem is that `stringify!` relies on `rustc_ast_pretty`.

It's not a problem, similar changes were done to the pretty-printer quite often in the past, `stringify!` docs even have a disclaimer about this.

r? @jyn514

**Review by petrochenkov — APPROVED** [review]
