### PR TITLE
ptr::add/sub: do not claim equivalence with `offset(c as isize)`

### LINKED ISSUE #130211: pointer addition semantics are unclear
### Location

[core::ptr::add](https://doc.rust-lang.org/std/primitive.pointer.html#method.add)
https://github.com/rust-lang/rust/blob/33855f80d4393bff5d1226eabf8e61f348179cee/library/core/src/ptr/const_ptr.rs#L810-L854

[core::ptr::offset](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset-1)
https://github.com/rust-lang/rust/blob/33855f80d4393bff5d1226eabf8e61f348179cee/library/core/src/ptr/const_ptr.rs#L349-L393

### Summary

The documentation for `core::ptr::add` currently states that it:

https://github.com/rust-lang/rust/blob/33855f80d4393bff5d1226eabf8e61f348179cee/library/core/src/ptr/const_ptr.rs#L810

Except it's not a convenience for just doing `.offset(count as isize)`, both according to Miri and the constant interpreter:

```rust
#[no_mangle]
pub const fn mul() -> i32 {
    const {
        let x = &[0i32; 2];
        let x = x.as_ptr().wrapping_add(1);
        unsafe {
            // has UB according to MIRI and fails compilation on nightly if you comment this out
            // mul nuw i64 -1, 4 is poison
            // x.add(!0).read();
            
            // DB and passes compilation
            // mul nsw i64 -1, 4 is defined
            x.offset(-1).read();
        }
        x[0]
    }
}
```

So one might infer that the following requirement:

https://github.com/rust-lang/rust/blob/33855f80d4393bff5d1226eabf8e61f348179cee/library/core/src/ptr/const_ptr.rs#L819

means that the `count * size_of::<T>()` must not overflow in the unsigned sense for `add` and signed sense for `offset`.

However, it's unclear if `overflowing isize` means the unsigned multiplication result has to be positive, or if the unsigned multiplication also has to not wrap in the signed sense. Both Miri and the constant interpreter allow the following:

```rust
#[no_mangle]
pub const fn mulnsw() -> i32 {
    const {
        let x = &[0i32; 2];
        let x = x.as_ptr().wrapping_add(1);
        let offset = !0usize >> 2; // will be -4 when multiplied
        let mut ret = 0;
        unsafe {
            // has no UB according to MIRI and does not fail compilation on nightly
            // does not wrap in the unsigned sense
            // however wraps in the signed sense
            // has UB in our codegen
            ret = x.add(offset).read();
            
            // UB in codegen due to signed overflow
            // both MIRI and constant interpreter fail
            // ret = x.offset(offset as isize).read();
        }
        ret
    }
}
```

However, `x.add(offset)` will also get lowered to `getelementptr inbounds i32, %x, i64 %offset`, which has UB according to the LLVM [langref](https://llvm.org/docs/LangRef.html#getelementptr-instruction).

> The multiplication of an index by the type size does not wrap the pointer index type in a signed sense (mul nsw).

If the `core::ptr::add` does have defined behavior in the above case, then we can't directly use `getelementptr inbounds` for types larger than a byte, without doing a `mul nuw` beforehand, and then doing `getelementptr inbounds i8`. However, if it's UB, then the docs should make it clear.

So `core::ptr::add` still carries the responsibility of preventing signed overflow in the multiplication(at least according to our codegen semantics). However, it's unclear if "must not overflow isize", means that the unsigned result has to fit in `[0, isize::MAX]`, as the following passes:

```rust
#[no_mangle]
pub const fn addaddr() -> i32 {
    const {
        let x = &[0i32; 2];
        let x = x.as_ptr().wrapping_add(1).cast::<u8>();
        unsafe {
            // -1 * 1 doesn't overflow in both the signed and unsigned sense
            // however the result doesn't fit in [0, isize::MAX]
            // passes MIRI and the constant interpreter
            x.byte_add(!0).read();
        }
        x[0]
    }
}
```

To summarize:

1. Does the multiplication of `count * size_of::<T>()` need to not overflow in both the signed and unsigned sense for `core::ptr::add`?
2. In `core::ptr::add`, is the resulting offset treated as a signed integer or unsigned integer for the following requirement: https://github.com/rust-lang/rust/blob/33855f80d4393bff5d1226eabf8e61f348179cee/library/core/src/ptr/const_ptr.rs#L821-L824

Rationale for inquiry:

LLVM recently added a `nuw` attribute to the `getelementptr` instruction in order to inform the optimizer that the offset is non-negative. I was checking the `core::ptr::add` documentation to see if we could use it for that, however, I found some contradictory information w.r.t the docs and the current behavior of the constant interpreter and Miri.

### PR DESCRIPTION
**Pull request by RalfJung**
In https://github.com/rust-lang/rust/pull/110837, the `offset` intrinsic got changed to also allow a `usize` offset parameter. The intention is that this will do an unsigned multiplication with the size, and we have UB if that overflows -- and we also have UB if the result is larger than `usize::MAX`, i.e., if a subsequent cast to `isize` would wrap. ~~The LLVM backend sets some attributes accordingly.~~

This updates the docs for `add`/`sub` to match that intent, in preparation for adjusting codegen to exploit this UB. We use this opportunity to clarify what the exact requirements are: we compute the offset using mathematical multiplication (so it's no problem to have an `isize * usize` multiplication, we just multiply integers), and the result must fit in an `isize`.
Cc @rust-lang/opsem @nikic 

https://github.com/rust-lang/rust/pull/130239 updates Miri to detect this UB.

`sub` still has some cases of UB not reflected in the underlying intrinsic semantics (and Miri does not catch): when we subtract `usize::MAX`, then after casting to `isize` that's just `-1` so we end up adding one unit without noticing any UB, but actually the offset we gave does not fit in an `isize`. Miri will currently still not complain for such cases:
```rust
fn main() {
    let x = &[0i32; 2];
    let x = x.as_ptr();
    // This should be UB, we are subtracting way too much.
    unsafe { x.sub(usize::MAX).read() };
}
```
However, the LLVM IR we generate here also is UB-free. This is "just" library UB but not language UB.
Cc @saethlin; might be worth adding precondition checks against overflow on `offset`/`add`/`sub`?

Fixes https://github.com/rust-lang/rust/issues/130211

### CODE REVIEW

File: library/core/src/ptr/const_ptr.rs [hunk 1]
```diff
@@ -355,7 +355,8 @@ impl<T: ?Sized> *const T {
     ///
     /// If any of the following conditions are violated, the result is Undefined Behavior:
     ///
-    /// * The computed offset, `count * size_of::<T>()` bytes, must not overflow `isize`.
+    /// * The computed offset, `count * size_of::<T>()` bytes (using unbounded arithmetic),
+    ///   must fit in an `isize`.
```
Comment (RalfJung) [inline library/core/src/ptr/const_ptr.rs:359]: What is the most clear and concise way to say "convert `count` and `size_of::<T>()` from whatever their types are into unbounded mathematical integers, multiply those, and check if the result fits in the value range of `isize`"?

**Comment by lukas-code** [comment]
To me this feels like we're changing the docs here to introduce new UB where there was none before. FWIW I'm in favor of this change and see how the new definition is much more useful, but I still feel that we should at least do a crater run (with an assert for the overflow) or something to see how widespread this misuse of `add` is in practice.

**Review by lukas-code — CHANGES_REQUESTED** [review]
The `byte_add`/`byte_sub` methods also need to be updated, especially that `byte_add` also cannot go "backwards".

File: library/core/src/ptr/const_ptr.rs (hunk 1 above)
Comment (lukas-code) [reply library/core/src/ptr/const_ptr.rs:359]: FWIW, the docs on `offset_from` say

> the absolute distance between the pointers, in bytes, computed on mathematical integers (without "wrapping around"), cannot overflow an `isize`

so maybe something like this could work

> The offset in bytes (`count * size_of::<T>()`), computed on mathematical integers (without "wrapping around"), must fit in an `isize`.

Comment (RalfJung) [reply library/core/src/ptr/const_ptr.rs:359]: I think "mathematical multiplication" is the most intuitive version here -- good catch with the `offset_from` docs, I will follow that.

**Comment by RalfJung** [comment]
> To me this feels like we're changing the docs here to introduce new UB where there was none before. FWIW I'm in favor of this change and see how the new definition is much more useful, but I still feel that we should at least do a crater run (with an assert for the overflow) or something to see how widespread this misuse of `add` is in practice.

This is skirting the edge of clarifying docs vs introducing new UB. "must not overflow `isize`" arguably already made this UB before, but "convenience for `.offset(count as isize)`" contradicts that. Paging in @rust-lang/lang for awareness.

I'm not sure such a crater run would be meaningful though, it would also catch all the cases that already were UB before...

**Comment by RalfJung** [comment]
I have moved the Miri changes into a separate PR (https://github.com/rust-lang/rust/pull/130239) so it is not held up by discussions around how to deal with the "kind of breaking change" aspect of this.

I also incorporated the feedback. The `wrapping_` methods also still have the wording around "convenience for ... as isize ...". There it is technically correct due to the wrapping semantics, but it might make sense to keep the docs consistent with the non-wrapping versions?

File: library/core/src/ptr/const_ptr.rs [hunk 2]
```diff
@@ -807,7 +808,11 @@ impl<T: ?Sized> *const T {
         }
     }
 
-    /// Adds an offset to a pointer (convenience for `.offset(count as isize)`).
+    /// Adds an offset to a pointer.
```
Comment (nikic) [inline library/core/src/ptr/const_ptr.rs:811]: Make this "unsigned offset" or "non-negative offset" for clearer symmetry with the signed APIs?

**Review by nikic — COMMENTED** [review]
Thanks, the new wording is clearer.

**Comment by saethlin** [comment]
> might be worth adding precondition checks against overflow on `offset`/`add`/`sub`?

It is definitely worth adding. I'm working on it.

**Comment by WaffleLapkin** [comment]
> I also incorporated the feedback. The `wrapping_` methods also still have the wording around "convenience for ... as isize ...". There it is technically correct due to the wrapping semantics, but it might make sense to keep the docs consistent with the non-wrapping versions?

I think this is a good idea. Looking at the docs now I think this "convinience for ... as isize" only adds confusion.

**Comment by RalfJung** [comment]
All right so what's the process here? This is a library API so by default I would assume t-libs-api is responsible. This is fairly directly exposing a language primitive though, which is why I pinged t-lang above.

But still, let's nominate t-libs-api -- @rust-lang/libs-api are you okay with this change to the docs for our inbounds pointer arithmetic methods? This can be seen as a breaking change since we previously documented e.g. `ptr.add(count)` as convenience for `ptr.offset(count as isize)`. This hasn't been true for a while, there are cases where the latter is fine but the former has UB: codegen assumes you're not able to move "backwards" even if `count as isize` would be negative. That's a useful assumption for codegen to have.

OTOH, the docs do say:

> The computed offset, count * size_of::<T>() bytes, must not overflow isize.

I would say if `count * size_of::<T>()` is `usize::MAX` then this overflows `isize`. So the docs kind of already say that `ptr.add(usize::MAX)` is UB, but they also say it is equivalent to `ptr.offset(-1)` which is not UB...

It seems unlikely that someone would rely on `add` with really big `usize` values to move the pointer backwards (why would they not use `offset`) -- unless of course they took our docs too literally. Therefore I hope this is acceptable breakage. Miri has already been adjusted to detect this UB and @saethlin is looking into the possibility of adding checks against this UB for debug builds.

**Review by scottmcm — APPROVED** [review]

**Comment by RalfJung** [comment]
> add was added well after offset existed, so I've always read that parenthetical as "if you've been using .offset(foo as isize) -- as we saw most uses of offset were -- then you probably want to switch to using .add(foo) now as shorter and easier", 

However, if `foo` is `usize::MAX`, then this switch is wrong under our current codegen.

Of course that's a very unlikely thing to happen...

**Comment by workingjubilee** [comment]
Both were added before we realized that we could not actually offset something by more than `isize::MAX` and remain within the same allocation according to the backend semantics we are constrained by.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by RalfJung** [comment]
Looking at https://github.com/rust-lang/rust/issues/130211 again it seems to me that actually we don't *yet* have codegen that makes things like `p.add(usize::MAX)` UB even when `p.sub(1)` is fine -- however, we'd like to adjust codegen to do this. So this is not catching up with what codegen already did, but it prepares for what we want to do in codegen, and makes the docs match the semantics that https://github.com/rust-lang/rust/pull/110837 intended for the underlying intrinsic (and that https://github.com/rust-lang/rust/pull/130239 implements for Miri).

**Comment by nikic** [comment]
@RalfJung Yes, that's correct. The backend doesn't make use of this right now, but intends to do so in the future. We'll likely start with LLVM 20, as `getelementptr nuw` support in LLVM 19 is still a bit weak.

**Comment by the8472** [comment]
Can we add an ub_check for this?
