### PR TITLE
fix `is_non_exhaustive` confusion between structs and enums

### LINKED ISSUE #53549: [nightly regression] E0639 + adding #[non_exhaustive] to io::ErrorKind is a breaking change
In stable and beta, you can write `ErrorKind::Other {}`, but in nightly this triggers E0639: cannot create non-exhaustive variant using struct expression. (As an aside, that error message should be rephrased and examples added to `--explain`.)

This is either a bug with `#[non_exhaustive]`, or it means that the attribute can't be applied to public enums without creating a breaking change.

### PR DESCRIPTION
**Pull request by arielb1**
Structs and enums can both be non-exhaustive, with a very different
meaning. This PR splits `is_non_exhaustive` to 2 separate functions - 1
for structs, and another for enums, and fixes the places that got the
usage confused.

Fixes #53549.

r? @eddyb

### CODE REVIEW

File: src/librustc/ty/mod.rs [hunk 1]
```diff
@@ -1981,10 +1981,30 @@ impl<'a, 'gcx, 'tcx> AdtDef {
     }
 
     #[inline]
-    pub fn is_non_exhaustive(&self) -> bool {
+    fn is_non_exhaustive(&self) -> bool {
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: I would rename this to `has_nonexhaustive_flag` and add a comment about how the meaning of this flag depends a lot on the kind of the ADT. Personally, I find this setup pretty unfortunate: I think we should  be "desugaring" the flag so that it appears on the variant for structs and on the adt only for enums ([as I described here](https://github.com/rust-lang/rust/issues/44109#issuecomment-408127667)). But I guess we can separate that out as a distinct sort of refactoring.

File: src/librustc/ty/mod.rs [hunk 2]
```diff
@@ -1981,10 +1981,30 @@ impl<'a, 'gcx, 'tcx> AdtDef {
...
         self.flags.intersects(AdtFlags::IS_NON_EXHAUSTIVE)
     }
 
+    #[inline]
+    pub fn is_enum_non_exhaustive(&self) -> bool {
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: I think we should call this method:

```rust
can_extend_variant_list
```

and add a suitable comment explaining how it is derived from a `#[non_exhaustive]` that appears on the enum (but not a variant).

File: src/librustc/ty/mod.rs [hunk 3]
```diff
@@ -1981,10 +1981,30 @@ impl<'a, 'gcx, 'tcx> AdtDef {
...
+        match self.adt_kind() {
+            AdtKind::Enum => self.is_non_exhaustive(),
+            AdtKind::Struct | AdtKind::Union => {
+                bug!("is_non_exhaustive_enum called on non-enum `{:?}`", self);
+            }
+        }
+    }
+
+    #[inline]
+    pub fn is_univariant_non_exhaustive(&self) -> bool {
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: I think we should call this method:

```rust
can_extend_field_list
```

and -- really -- I think it should be on the variant. But if we want to keep it here, perhaps a name like `can_extend_univariant_field_list` (again with a comment linking to how it maps to Rust source).

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc/ty/mod.rs (hunk 3 above)
Comment (arielb1) [reply src/librustc/ty/mod.rs]: I like to use the name `nonexhaustive` here, because that's how the feature is called.

**Comment by arielb1** [comment]
pushed..

**Review by nikomatsakis — APPROVED** [review]

**Comment by nnethercote** [comment]
This hurt compile times by up to 3%, mostly for shorter-running benchmarks:
https://perf.rust-lang.org/compare.html?start=27e5457f3fa6c6e322e05352f0109f2cd511396c&end=20ca02569ae3e1dc29962e92739fbab632abf241&stat=instructions:u

@arielb1: any thoughts?

**Comment by arielb1** [comment]
Some bug? This commit should not change performance.

**Comment by arielb1** [comment]
Looks like `alloc_adt_def` is taking much more time for some reason - at least on my callgrind. This at least *makes sense*.

**Comment by arielb1** [comment]
Ah decoding of item attrs is duplicated between a struct and its constructor:
https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/decoder.rs#L925-L930

The code I have written uses the constructor's attrs in `VariantDef::new`, and the ADT's attrs in `AdtDef::new`, which causes the double decoding.
