### PR TITLE
Disallow mutable borrow to non-mut statics

### LINKED ISSUE #42344: error: internal compiler error: /checkout/src/librustc_borrowck/borrowck/mod.rs:808: aliasability violation for static `cannot borrow data mutably`
When compiling the following code, with rustc (nightly, beta or stable at the moment):

```rust
static TAB: [&mut [u8]; 0] = [];
pub unsafe fn test() {
    TAB[0].iter_mut();
}
pub fn main() {}
```

I get the following error:

```
error: internal compiler error: /checkout/src/librustc_borrowck/borrowck/mod.rs:808: aliasability violation for static `cannot borrow data mutably`
```

Here is the relevant playground link: https://is.gd/42slwV

Hope that helps,
Leo

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #42344.

### CODE REVIEW

**Comment by topecongiro** [comment]
Hmm, I just realized that when nll is enabled, the error message is slightly different. 
Is this acceptable?

#### with nll
```rust
error[E0596]: cannot borrow immutable item `*TAB[..]` as mutable
  --> test.rs:16:5
   |
16 |     TAB[0].iter_mut();
   |     ^^^^^^ cannot borrow as mutable
   |
   = note: Value not mutable causing this error: `TAB`

error: aborting due to previous error
```

#### without nll

```rust
error[E0596]: cannot borrow borrowed content of mutable binding as mutable
  --> test.rs:14:5
   |
14 |     TAB[0].iter_mut();
   |     ^^^^^^ cannot borrow as mutable

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
@topecongiro that's acceptable, it's a separate issue

**Comment by nikomatsakis** [comment]
tbh, though, I find the MIR borrowck error much easier to understand =)

File: src/librustc_borrowck/borrowck/gather_loans/mod.rs [hunk 1]
```diff
@@ -233,7 +233,17 @@ fn check_mutability<'a, 'tcx>(bccx: &BorrowckCtxt<'a, 'tcx>,
                                            cmt,
                                            code: err_mutbl }))
             } else {
-                Ok(())
+                match cmt.maybe_static_mutability() {
```
Comment (nikomatsakis) [inline src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Something about this check doesn't feel right. There is a specific check that is supposed to guarantee that the reference is not an "aliasable" location, and it seems to be going awry, but I feel like we should be fixing *that* check, and not adding a new one. This is the check I am talking about:

https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/librustc_borrowck/borrowck/gather_loans/mod.rs#L164-L203

Can you maybe tell me what the `cmt` is in this case, and what the value of `aliasability` is?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Thanks! =)

**Comment by shepmaster** [comment]
Ping from triage, @topecongiro ! Will you be able to respond to the most recent set of feedback soon?

**Comment by shepmaster** [comment]
> Disallow mutable borrow to non-mut statics

I got excited and thought this fixed #46557 😝

**Comment by topecongiro** [comment]
Oops, I missed the notification of review by @nikomatsakis. Sorry!

I will work on this today at some point.

File: src/librustc_borrowck/borrowck/gather_loans/mod.rs (hunk 1 above)
Comment (topecongiro) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: The `cmt` is
```rust
cmt=cmt_ {
        id: NodeId(16),
        span: test.rs:13:5: 13:11,
        cat: Deref(cmt_ {
            id: NodeId(16),
            span: test.rs:13:5: 13:11,
            cat: Interior(cmt_ {
                id: NodeId(14),
                span: test.rs:13:5: 13:8,
                cat: StaticItem,
                mutbl: McImmutable,
                ty: [&'static mut [u8]; 0],
                note: NoteNone,
            }, []),
            mutbl: McImmutable,
            ty: &'static mut [u8],
            note: NoteNone,
        }, BorrowedPtr(MutBorrow, ReStatic)),
        mutbl: McDeclared,
        ty: [u8],
        note: NoteNone
    }
```

and the value of `aliasability` is
```rust
aliasability=FreelyAliasable(AliasableStatic)
```

Comment (nikomatsakis) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Huh, so I wonder in that case why this code:

https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/librustc_borrowck/borrowck/gather_loans/mod.rs#L190-L198

doesn't execute... `req_kind` is `ty::MutBorrow`, right?

**Comment by nikomatsakis** [comment]
@topecongiro left another question :)

File: src/librustc_borrowck/borrowck/gather_loans/mod.rs (hunk 1 above)
Comment (topecongiro) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: That is because `check_mutability` triggers an error, and `check_aliasability` is no called at all.

Comment (nikomatsakis) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Huh. So how come I don't see an error reporting in the original issue #42344?  I see the ICE -- where does that ICE occur?

Comment (topecongiro) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Oh, were you asking about the behavior of the original rustc? I was talking about how rustc bahaves when this PR was applied. I am sorry for the confusion.

Using the master branch, yes, `req_kind` is `ty::MutBorrow`, and `bccx.report_aliasability_violation` is executed. The following error is reported.

```
error: internal compiler error: aliasability violation for static `cannot borrow data mutably`
 --> test.rs:3:5
  |
3 |     TAB[0].iter_mut();
  |     ^^^^^^

error: aborting due to previous error
```

Comment (nikomatsakis) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: @topecongiro ah, I see -- actually, I think that the `delay_span_bug` is just wrong and should be removed. The logic was that a case like `static X: u32 = 2; &mut X` should not reach there (and indeed I think it won't) -- but it overlooked the possibility of an `&mut` living in a `static`.

Comment (nikomatsakis) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Can you update this PR to just remove the `delay_span_bug` call for `AliasabilityReason::Static`?

Comment (topecongiro) [reply src/librustc_borrowck/borrowck/gather_loans/mod.rs]: Sure! Thank your for your patience with my slow updates.

**Comment by nikomatsakis** [comment]
@bors r+

Nice =)
