### PR TITLE
Move generic arg/param validation to `create_substs_for_generic_args` to resolve various const generics issues

### LINKED ISSUE #68257: Cannot use generic const argument without `{}`, despite no conflict
I would expect this code to compile, but it does not:

```rust
#![feature(const_generics)]

struct Foo<const A: usize, const B: usize> {
    a: [usize; A],
    b: [usize; B],
}

impl<const A: usize> Foo<A, 1> {
    fn get_b(&self) -> usize {
        self.b[0]
    }
}

impl<const B: usize> Foo<1, B> {
    fn get_a(&self) -> usize {
        self.a[0]
    }
}


fn main() {
    let foo = Foo { a: [0, 3], b: [0] };
    dbg!(foo.get_b());
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=00aba90934a80e43114bae17991b8caf))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: type arguments must be declared prior to const arguments
  --> src/main.rs:14:29
   |
14 | impl<const B: usize> Foo<1, B> {
   |                             ^

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### LINKED ISSUE #68398: Const generic parameters are allowed in the wrong position (causing ICEs).
Note the `Array<N, ()>` use, instead of `Array<(), N>`:
```rust
#![feature(const_generics)]

pub type Array<T, const N: usize> = [T; N];

pub fn foo<const N: usize>() -> Array<N, ()> {
    unimplemented!()
}
```
This currently results in `cat_expr Errd` and `broken MIR` ICEs.

cc @varkor @yodaldevoid @oli-obk

### PR DESCRIPTION
**Pull request by varkor**
This changes some diagnostics, but I think they're around as helpful as the previous ones, and occur infrequently regardless.

Fixes https://github.com/rust-lang/rust/issues/68257.
Fixes https://github.com/rust-lang/rust/issues/68398.

r? @eddyb

### CODE REVIEW

**Review by eddyb — APPROVED** [review]
LGTM, but I'd like a second opinion from @rust-lang/compiler (and maybe we need a check-mode crater run? I doubt it though)

File: src/librustc_typeck/astconv.rs [hunk 1]
```diff
@@ -562,28 +574,74 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                                    };
+                                    struct_span_err!(
+                                        tcx.sess,
+                                        arg.span(),
+                                        E0747,
+                                        "{} provided when a {} was expected",
+                                        arg_kind(arg),
+                                        param_kind,
+                                    )
+                                    .emit();
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]: Can we move this out (a lot of rightward drift here + diagnostics code in happy path)?

Comment (Centril) [reply src/librustc_typeck/astconv.rs]: Also, `structural_impls` has:
```rust
impl fmt::Debug for ty::GenericParamDef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let type_name = match self.kind {
            ty::GenericParamDefKind::Lifetime => "Lifetime",
            ty::GenericParamDefKind::Type { .. } => "Type",
            ty::GenericParamDefKind::Const => "Const",
        };
        write!(f, "{}({}, {:?}, {})", type_name, self.name, self.def_id, self.index)
    }
}
```
Consider sharing the `match` code.

File: src/librustc_typeck/astconv.rs [hunk 2]
```diff
@@ -562,28 +574,74 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                                force_infer_lt.expect("lifetimes ought to have been inferred");
+                            struct_span_err!(
+                                tcx.sess,
+                                provided.span(),
+                                E0747,
+                                "{} provided when a {} was expected",
+                                arg_kind(provided),
+                                kind,
+                            )
+                            .emit();
```
Comment (Centril) [inline src/librustc_typeck/astconv.rs]: Can we move this out too (+ `arg_kind`)?

File: src/librustc/ty/structural_impls.rs [hunk 3]
```diff
@@ -19,12 +19,7 @@ use syntax::ast;
 
 impl fmt::Debug for ty::GenericParamDef {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
-        let type_name = match self.kind {
-            ty::GenericParamDefKind::Lifetime => "Lifetime",
-            ty::GenericParamDefKind::Type { .. } => "Type",
-            ty::GenericParamDefKind::Const => "Const",
-        };
-        write!(f, "{}({}, {:?}, {})", type_name, self.name, self.def_id, self.index)
+        write!(f, "{}({}, {:?}, {})", self.kind.descr(), self.name, self.def_id, self.index)
```
Comment (eddyb) [inline src/librustc/ty/structural_impls.rs]: The casing is different though - consider deriving `Debug` instead of this custom `impl`.

File: src/librustc_typeck/astconv.rs [hunk 4]
```diff
@@ -480,6 +496,7 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
         parent_substs: &[subst::GenericArg<'tcx>],
         has_self: bool,
         self_ty: Option<Ty<'tcx>>,
+        arg_count_mismatch: bool,
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: Hmm, maybe you can replace this with a `Result<(), GenericArgCountMismatch>`?
Especially if it's the same `bool` returned by some functions.

File: src/librustc_typeck/astconv.rs [hunk 5]
```diff
@@ -337,112 +341,128 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
-        };
+        let mut arg_count_mismatch = reported_late_bound_region_err;
+        let mut unexpected_spans = vec![];
 
-        if reported_late_bound_region_err.is_none()
+        if !reported_late_bound_region_err
             && (!infer_lifetimes || arg_counts.lifetimes > param_counts.lifetimes)
         {
-            check_kind_count(
+            arg_count_mismatch |= check_kind_count(
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: AFAIK you can have a `Result` variable and combine it with `x = x.and(...)`.

File: src/librustc_typeck/astconv.rs [hunk 6]
```diff
@@ -337,112 +341,128 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            |kind, required, permitted, provided, offset, unexpected_spans: &mut Vec<Span>| {
+                debug!(
+                    "check_kind_count: kind: {} required: {} permitted: {} provided: {} offset: {}",
+                    kind, required, permitted, provided, offset
+                );
+                // We enforce the following: `required` <= `provided` <= `permitted`.
+                // For kinds without defaults (e.g.., lifetimes), `required == permitted`.
+                // For other kinds (i.e., types), `permitted` may be greater than `required`.
+                if required <= provided && provided <= permitted {
+                    return false;
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: At the very least, I'd like to see this closure return `Result` too.
I can't easily tell if `false` here is success or failure, but `Ok(())` would be clear.

File: src/librustc_typeck/astconv.rs [hunk 7]
```diff
@@ -314,9 +318,10 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
         }
 
         // Prohibit explicit lifetime arguments if late-bound lifetime parameters are present.
-        let mut reported_late_bound_region_err = None;
+        let mut reported_late_bound_region_err = false;
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: This could probably also avoid being `bool`.

File: src/librustc_typeck/astconv.rs [hunk 8]
```diff
@@ -327,7 +332,6 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
                     let mut err = tcx.sess.struct_span_err(span, msg);
                     err.span_note(span_late, note);
                     err.emit();
-                    reported_late_bound_region_err = Some(true);
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: `reported_late_bound_region_err.unwrap_or(false)` below would suggest that only this branch should have `reported_late_bound_region_err = true;`, not the lint one below?

File: src/librustc_typeck/astconv.rs (hunk 5 above)
Comment (varkor) [reply src/librustc_typeck/astconv.rs]: I don't think the code becomes more readable using a `Result` instead of `bool` here.

File: src/librustc_typeck/astconv.rs (hunk 8 above)
Comment (varkor) [reply src/librustc_typeck/astconv.rs]: I can change the variable name. I thought it was reasonable to include emission of a lint as "reported", though, so the name still seemed appropriate.

File: src/librustc_typeck/astconv.rs [hunk 9]
```diff
@@ -337,112 +341,128 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+    fn generic_arg_mismatch_err(sess: &Session, arg: &GenericArg<'_>, kind: &'static str) {
+        struct_span_err!(
+            sess,
+            arg.span(),
+            E0747,
+            "{} provided when a {} was expected",
+            arg.descr(),
+            kind,
+        )
+        .emit();
```
Comment (estebank) [inline src/librustc_typeck/astconv.rs]: No reordering suggestion for this case?

Comment (varkor) [reply src/librustc_typeck/astconv.rs]: I'd rather leave this PR for the bug-fixes and follow up with the diagnostics improvements. That's a good follow up, though.

File: src/librustc_typeck/astconv.rs (hunk 8 above)
Comment (eddyb) [reply src/librustc_typeck/astconv.rs]: Doesn't that change the behavior later on (potentially preventing real errors from being emitted)?

The important thing, I thought, is whether there was an actual error that would stop compilation (maybe we should use `ErrorReported` to indicate that?).

Comment (varkor) [reply src/librustc_typeck/astconv.rs]: It's possible there are interactions with `impl Trait` that aren't being tested at all. I'll check this.

Comment (eddyb) [reply src/librustc_typeck/astconv.rs]: I more or less really want to keep the preexisting behavior, if the tests pass either way.

File: src/librustc_typeck/astconv.rs [hunk 10]
```diff
@@ -321,18 +322,19 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
                            if late bound lifetime parameters are present";
                 let note = "the late bound lifetime parameter is introduced here";
                 let span = args.args[0].span();
                 if position == GenericArgPosition::Value
                     && arg_counts.lifetimes != param_counts.lifetimes
                 {
+                    explicit_lifetimes = Err(GenericArgCountMismatch(Some(ErrorReported)));
                     let mut err = tcx.sess.struct_span_err(span, msg);
                     err.span_note(span_late, note);
                     err.emit();
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: @Centril @estebank Can we make it so you have to emit an error to get an `ErrorReported` token, and maybe make it unconstructible except by the diagnostic reporting machinery?

**Comment by yodaldevoid** [comment]
Is this PR waiting on anything specific?

**Comment by varkor** [comment]
@yodaldevoid: a second reviewer's opinion on the PR.

File: src/librustc_typeck/astconv.rs (hunk 10 above)
Comment (nikomatsakis) [reply src/librustc_typeck/astconv.rs]: Oh, that'd be cute. :)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
I didn't follow 100% of what's going on here, but it overall seems pretty reasonable -- except that I think the new errors are kind of confusingly worded. Am I missing something?

File: src/librustc_error_codes/error_codes/E0747.md [hunk 11]
```diff
@@ -0,0 +1,11 @@
...
+generic parameters are declared.
+
+Erroneous code example:
+
+```compile_fail,E0747
+struct S<'a, T>(&'a T);
+
+type X = S<(), 'static>; // error: the type argument is provided before the
+                         // lifetime argument
+```
```
Comment (estebank) [inline src/librustc_error_codes/error_codes/E0747.md]: Add the fixed example.

File: src/test/ui/const-generics/const-param-after-const-literal-arg.rs [hunk 12]
```diff
@@ -0,0 +1,10 @@
+// check-pass
+
+#![feature(const_generics)]
+//~^ WARN the feature `const_generics` is incomplete and may cause the compiler to crash
```
Comment (estebank) [inline src/test/ui/const-generics/const-param-after-const-literal-arg.rs]: Can't we just add `#![allow(incomplete_features)]` instead?

File: src/test/ui/const-generics/const-param-before-other-params.rs [hunk 13]
```diff
@@ -1,4 +1,5 @@
 #![feature(const_generics)]
+//~^ WARN the feature `const_generics` is incomplete and may cause the compiler to crash
```
Comment (estebank) [inline src/test/ui/const-generics/const-param-before-other-params.rs]: Same here.

File: src/test/ui/suggestions/suggest-move-types.stderr [hunk 14]
```diff
@@ -74,29 +74,30 @@ LL | struct Dl<'a, 'b, 'c, T, U, V, M: ThreeWithLifetime<T, 'a, A=(), B=(), U, '
    |                                                            |     this associated type binding should be moved after the generic parameters
    |                                                            this associated type binding should be moved after the generic parameters
 
-error: lifetime arguments must be declared prior to type arguments
-  --> $DIR/suggest-move-types.rs:34:46
+error[E0747]: type provided when a lifetime was expected
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/suggestions/suggest-move-types.stderr]: I'm convinced we should be suggesting the correct order in all of these cases.

File: src/librustc_typeck/astconv.rs (hunk 10 above)
Comment (varkor) [reply src/librustc_typeck/astconv.rs]: Are we tracking this anywhere?

File: src/test/ui/generic/generic-arg-mismatch-recover.rs [hunk 15]
```diff
@@ -4,7 +4,6 @@ struct Bar<'a>(&'a ());
 
 fn main() {
     Foo::<'static, 'static, ()>(&0); //~ ERROR wrong number of lifetime arguments
```
[the remark this answers is not in the document]
Comment (varkor) [reply src/test/ui/generic/generic-arg-mismatch-recover.rs]: Previously if we encountered an incorrect generic argument, we would just try to skip it and continue going: https://github.com/rust-lang/rust/pull/68434/files#diff-1b4d50b82a87f1031cd5f99b64123de7L578. Now we just stop checking the remaining arguments, because there's a high likelihood the remaining arguments are invalid and we'd just spit out lots of errors that aren't particularly helpful.

File: src/test/ui/suggestions/suggest-move-types.stderr (hunk 14 above)
[the remark this answers is not in the document]
Comment (varkor) [reply src/test/ui/suggestions/suggest-move-types.stderr]: The reason I changed this is because there isn't really a restriction on the order of generic arguments: the restriction is on generic parameters, but generic arguments must match the order of generic parameters. The fact that lifetime arguments must precede type arguments is a side-effect of the parameter order. I'll try tweaking the wording to improve this. As @estebank says, ideally we'd suggest the correct order, but I'd like to get this merged sooner rather than later, as I don't know how much time I'll have for more elaborate changes now.

**Comment by varkor** [comment]
@nikomatsakis: I've addressed the code comments, and also added a note to the error messages making them as descriptive as the previous ones. I'll open an issue for suggesting the correct order of all provided arguments, though I'd rather split it out into a separate PR.

File: src/librustc_typeck/astconv.rs (hunk 10 above)
Comment (eddyb) [reply src/librustc_typeck/astconv.rs]: Don't think so.

Comment (varkor) [reply src/librustc_typeck/astconv.rs]: Created https://github.com/rust-lang/rust/issues/69426.

File: src/test/ui/suggestions/suggest-move-types.stderr (hunk 14 above)
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/test/ui/suggestions/suggest-move-types.stderr]: OK, I see. I still find the message more confusing than the old one, but perhaps I now better understand what this PR is aiming for.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

thanks, @varkor
