### PR TITLE
Stabilize `peekable_next_if`

### LINKED ISSUE #72480: Tracking Issue for peekable_next_if
This is a tracking issue for the feature `peekable_next_if` (https://github.com/rust-lang/rust/pull/72310).
The feature gate for the issue is `#![feature(peekable_next_if)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should `next_if` be named `consume_if` or `eat_if`?
- Should `next_if_eq` be named `consume` or `eat`?

### PR DESCRIPTION
**Pull request by Stupremee**
This PR stabilizes the `peekable_next_if` feature

Resolves #72480

### CODE REVIEW

**Comment by jyn514** [comment]
I'm not on T-libs, I shouldn't be the reviewer. r? @dtolnay maybe since they reviewed the initial PR, but it will need FCP either way.

File: library/core/src/iter/adapters/peekable.rs [hunk 1]
```diff
@@ -277,14 +276,13 @@ impl<I: Iterator> Peekable<I> {
...
     /// ```
-    /// #![feature(peekable_next_if)]
     /// let mut iter = (1..20).peekable();
     /// // Consume all numbers less than 10
     /// while iter.next_if(|&x| x < 10).is_some() {}
     /// // The next value returned will be 10
     /// assert_eq!(iter.next(), Some(10));
     /// ```
-    #[unstable(feature = "peekable_next_if", issue = "72480")]
+    #[stable(feature = "peekable_next_if", since = "1.49.0")]
```
Comment (jyn514) [inline library/core/src/iter/adapters/peekable.rs:285]: 1.49 is currently in beta, this will be in 1.50.
```suggestion
    #[stable(feature = "peekable_next_if", since = "1.50.0")]
```

File: library/core/src/iter/adapters/peekable.rs [hunk 2]
```diff
@@ -311,7 +308,7 @@ impl<I: Iterator> Peekable<I> {
     /// // `next_if_eq` saves the value of the next item if it was not equal to `expected`.
     /// assert_eq!(iter.next(), Some(1));
     /// ```
-    #[unstable(feature = "peekable_next_if", issue = "72480")]
+    #[stable(feature = "peekable_next_if", since = "1.49.0")]
```
Comment (jyn514) [inline library/core/src/iter/adapters/peekable.rs:311]:
```suggestion
    #[stable(feature = "peekable_next_if", since = "1.50.0")]
```

**Review by jyn514 — APPROVED** [review]

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
@rust-lang/libs:
@rfcbot fcp merge

These two methods on std::iter::Peekable:

```diff
  impl<I: Iterator> Peekable<I> {
+     pub fn next_if(&mut self, func: impl FnOnce(&I::Item) -> bool) -> Option<I::Item>;

+     pub fn next_if_eq<T>(&mut self, expected: &T) -> Option<I::Item>
+     where
+         T: ?Sized,
+         I::Item: PartialEq<T>;
  }
```

```rust
let alnum = peekable.next_if(char::is_ascii_alphanumeric);

// equivalent to:
let alnum = match peekable.peek() {
    Some(ch) if ch.is_ascii_alphanumeric() => Some(peekable.next().unwrap()),
    _ => None,
};
```

https://doc.rust-lang.org/nightly/std/iter/struct.Peekable.html#method.next_if
https://doc.rust-lang.org/nightly/std/iter/struct.Peekable.html#method.next_if_eq

**Comment by m-ou-se** [comment]
Now that `Peekable::peek_mut` also exists, I'm wondering if `next_if` should provide a `&mut Item` rather than a `&Item`. (To not make the same mistake as with `Vec::retain`, which in hindsight could've/should've given a `&mut` but only gives a `&`.)

**Comment by m-ou-se** [comment]
@rfcbot concern mut

Now that `Peekable::peek_mut` also exists, I'm wondering if `next_if` should provide a `&mut Item` rather than a `&Item`. (To not make the same mistake as with `Vec::retain`, which in hindsight could've/should've given a `&mut` but only gives a `&`.) What do you all think?

**Comment by jyn514** [comment]
Why would you need to mutate the item?

**Comment by KodrAus** [comment]
> I'm wondering if next_if should provide a &mut Item rather than a &Item

Oh that's an interesting philosophical question... Should we always try offer up the most exclusive reference we can?

> Why would you need to mutate the item?

I wonder if we asked the same question about `Vec::retain`. The problem there is that in order to both retain and mutate you have to iterate the collection twice, isn't it?

With `next_if` [it looks like there isn't much difference](https://godbolt.org/z/KPG94e) between `next_if(filter).map(mutate)` and a `next_if_mut(filter_and_mutate_in_place)`. Since we stash the value in `peeked`, the semantics of `next_if(|v| { mutate(v); false })` also seem a bit strange.

But I think _is a shared reference sufficient when we could use an exclusive one?_ is a good question we should keep asking!

**Comment by KodrAus** [comment]
A `next_if_mut` method also doesn’t seem too offensive to me if we did want one. At least when reviewing code the `_mut` suffix would suggest there’s something more going on than just filtering and yielding values.

**Comment by KodrAus** [comment]
@m-ou-se Do you feel strongly that `next_if` should accept a `&mut` item, or are you satisfied with some combination of `.peek_mut(mutate).next_if(condition_after_mutate)` or `.peek().next_if(condition).map(mutate)`, with a possible `next_if_mut` alternative introduced later if it proves useful?

**Comment by m-ou-se** [comment]
That sounds good to me.

@rfcbot resolve mut

**Review by dtolnay — APPROVED** [review]

**Comment by m-ou-se** [comment]
Note: If https://github.com/rust-lang/rust/pull/81810 fails but https://github.com/rust-lang/rust/pull/81792 (which is in the queue right after) gets merged, this will need to be updated to `since = "1.52"` instead.
