### PR TITLE
Fix const_err with `-(-0.0)`

### LINKED ISSUE #64059: `-(-0.0)` raises const_err "attempt to negate with overflow"
```rust
fn main() {
    let _ = -(-0.0);
}
```

```
error: this expression will panic at runtime
 --> test.rs:2:13
  |
2 |     let _ = -(-0.0);
  |             ^^^^^^^ attempt to negate with overflow
  |
  = note: `#[deny(const_err)]` on by default

error: aborting due to previous error
```

<details><summary>Meta</summary>

```
rustc 1.39.0-nightly (fba38ac27 2019-08-31)
binary: rustc
commit-hash: fba38ac27e2ade309f4c2504a6d6cd3556972a28
commit-date: 2019-08-31
host: x86_64-unknown-linux-gnu
release: 1.39.0-nightly
LLVM version: 9.0
```

</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #64059

r? @oli-obk

### CODE REVIEW

File: src/librustc_mir/transform/const_prop.rs [hunk 1]
```diff
@@ -407,18 +407,6 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                 let arg = self.eval_operand(arg, source_info)?;
                 let val = self.use_ecx(source_info, |this| {
                     let prim = this.ecx.read_immediate(arg)?;
-                    match op {
-                        UnOp::Neg => {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: oh... we have this check for debug mode... I guess keep it but add an `opt-level` check here ( like https://github.com/rust-lang/rust/blob/35c9e5f1229d8b634ebd98c49e35c74e237e17f7/src/librustc_mir/transform/inline.rs#L42 ) so we only run this code in release mode (and add a comment so it's clear why we need to do this)

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: Probably a good idea to do the same release mode opt out in https://github.com/rust-lang/rust/blob/35c9e5f1229d8b634ebd98c49e35c74e237e17f7/src/librustc_mir/transform/const_prop.rs#L476

Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: So, should we have the check like
```rust
self.tcx.sess.opts.debugging_opts.mir_opt_level >= 2
&& prim.to_bits()? == (1 << (prim.layout.size.bits() - 1)) {..}
```
here and L476?

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: Yes

Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: pushed the change

File: src/librustc_mir/transform/const_prop.rs [hunk 2]
```diff
@@ -405,13 +405,13 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                 }
 
                 let arg = self.eval_operand(arg, source_info)?;
+                let is_release_mode = self.tcx.sess.opts.debugging_opts.mir_opt_level >= 2;
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: I'm very sorry about this back and forth. I should have realized it's not the optimization level.

The thing that's actually making the decision is `tcx.sess.overflow_checks()`, so you need to use that.

There's actually 3 levels of optimization decisions going on:

1. `-O`
2. `-C mir-opt-level=2`
3. `-C overflow-checks=false`

The first one impacts the third one if there's no third one specified. The second one doesn't impact anything related to overflow checks.

Also please leave a comment here and at the binop overflow site explaining that we're doing the overflow checks in release mode, too, where there's no assert-terminator doing them for us

Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: Okay, added comments and used `overflow_check()`.

File: src/librustc_mir/transform/const_prop.rs [hunk 3]
```diff
@@ -405,13 +405,15 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                let is_release_mode = self.tcx.sess.overflow_checks();
                 let val = self.use_ecx(source_info, |this| {
                     let prim = this.ecx.read_immediate(arg)?;
                     match op {
                         UnOp::Neg => {
-                            // Need to do overflow check here: For actual CTFE, MIR
-                            // generation emits code that does this before calling the op.
-                            if prim.to_bits()? == (1 << (prim.layout.size.bits() - 1)) {
+                            // We don't have to check overflow here when we already
+                            // check it in release mode.
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: We're checking it already in debug mode. We need to check in release mode.

File: src/librustc_mir/transform/const_prop.rs [hunk 4]
```diff
@@ -405,13 +405,15 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                 }
 
                 let arg = self.eval_operand(arg, source_info)?;
+                let is_release_mode = self.tcx.sess.overflow_checks();
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: This is the wrong way around, if overflow checks are on, we don't need to check again

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: src/librustc_mir/transform/const_prop.rs [hunk 5]
```diff
@@ -485,7 +487,9 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                         Scalar::from_bool(overflow).into(),
                     )
                 } else {
-                    if overflow {
+                    // We don't have to check overflow here when we already
+                    // check it in release mode.
+                    if self.tcx.sess.overflow_checks() && overflow {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: same here

File: src/librustc_mir/transform/const_prop.rs (hunk 4 above)
Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: Should be `let is_release_mode = !self.tcx.sess.overflow_checks()`?

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: Or just do `let oflo_checks = self.tcx.sess.overflow_checks();` and use `!oflo_checks` in the `if` condition

Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: changed the conditions

File: src/librustc_mir/transform/const_prop.rs (hunk 3 above)
Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: updated the comments

File: src/test/ui/consts/issue-64059.rs [hunk 6]
```diff
@@ -0,0 +1,4 @@
+fn main() {
+    let _ = -(-0.0);
+    //~^ ERROR: this expression will panic at runtime
```
Comment (JohnTitor) [inline src/test/ui/consts/issue-64059.rs]: Hmm, is the test okay?

File: src/librustc_mir/transform/const_prop.rs [hunk 7]
```diff
@@ -405,13 +405,15 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
                 }
 
                 let arg = self.eval_operand(arg, source_info)?;
+                let oflo_check = self.tcx.sess.overflow_checks();
                 let val = self.use_ecx(source_info, |this| {
                     let prim = this.ecx.read_immediate(arg)?;
                     match op {
                         UnOp::Neg => {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: Oh right. Now we have the original issue again. I believe this can only happen for signed integers, so add one more check and we should be good to go: `prim.layout.ty.is_signed()` (https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyS.html#method.is_signed) Should return `true` if the type that we're negating is a signed integer

**Comment by oli-obk** [comment]
I'm surprised this change doesn't cause any reduction in duplicate diagnostics... Not sure what's going on.

If I'm grepping correctly, we don't have a single test running in debug mode and thus producing double the warnings that release mode does.

Can you add a test with `// -C overflow-checks=true -O` with a bunch of overflow examples and see if there's only one error per overflow?

File: src/librustc_mir/transform/const_prop.rs (hunk 7 above)
Comment (JohnTitor) [reply src/librustc_mir/transform/const_prop.rs]: Is the condition also needed at the later change?

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: No, the other place does a type agnostic check already. Only the bit trickery here is problematic

File: src/test/ui/consts/const-err2.rs [hunk 8]
```diff
@@ -5,6 +5,8 @@
 
 #![feature(rustc_attrs)]
 #![allow(exceeding_bitshifts)]
+// compile-flags: -C overflow-checks=on -O
```
Comment (oli-obk) [inline src/test/ui/consts/const-err2.rs]: Oh sorry. That wasn't clear. Please add a *new* test with that flag. You can copy an existing test and add it to that, but don't modify existing tests. We need to test both with and without the flag

Comment (JohnTitor) [reply src/test/ui/consts/const-err2.rs]: Ah, okay, I'll do that.

Comment (JohnTitor) [reply src/test/ui/consts/const-err2.rs]: Fixed tests again

**Comment by oli-obk** [comment]
Super thanks

@bors r+

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/64122#issuecomment-527434767, @bors r-

**Comment by JohnTitor** [comment]
I'm not sure why the test is failed in `x86_64-gnu-nopt`, any thoughts? @oli-obk

File: src/test/ui/issues/issue-8460-const2.rs [hunk 9]
```diff
@@ -0,0 +1,59 @@
+// compile-flags: -C overflow-checks=on -O
```
Comment (oli-obk) [inline src/test/ui/issues/issue-8460-const2.rs]: Maybe noopt overwrites this `-O`? That would be weird. Also weird that noopt causes *fewer* diagnostics... I'm not sure what's going on. You can undo the changes unrelated to `-(-0.0)` if you want so we can get the PR merged and open an issue about not being able to test noopt properly.

File: src/librustc_mir/transform/const_prop.rs [hunk 10]
```diff
@@ -405,13 +405,16 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
-                            // Need to do overflow check here: For actual CTFE, MIR
-                            // generation emits code that does this before calling the op.
-                            if prim.to_bits()? == (1 << (prim.layout.size.bits() - 1)) {
+                            // We check overflow in debug mode already
+                            // so should only check in release mode.
+                            if !oflo_check
+                            && prim.layout.ty.is_signed()
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs]: essentially this condition the only needed thing for the fix. The rest is what's causing the CI failure

File: src/test/ui/issues/issue-8460-const2.rs (hunk 9 above)
Comment (JohnTitor) [reply src/test/ui/issues/issue-8460-const2.rs]: The weird thing is that it happened in `issue-8460-const.rs` not `issue-8460-const2.rs`. `issue-8460-const.rs` has no compile flags.

Comment (oli-obk) [reply src/test/ui/issues/issue-8460-const2.rs]: Oh. That may explain it... not sure what the best thing to do here is. Maybe instead of copying the files we should use the scheme where one test is built in multiple modes? I forget what the appropriate flags are, but incremental has loads of them

Comment (JohnTitor) [reply src/test/ui/issues/issue-8460-const2.rs]: Or could we add the `-O` flag to `issue-8460-const.rs`? The other tests we touch have this flag but that hasn't.

Comment (oli-obk) [reply src/test/ui/issues/issue-8460-const2.rs]: If that solves it, sure

Comment (JohnTitor) [reply src/test/ui/issues/issue-8460-const2.rs]: I added the flag to the test, could we run `bors try`?

Comment (oli-obk) [reply src/test/ui/issues/issue-8460-const2.rs]: You can test this locally by setting https://github.com/rust-lang/rust/blob/b9de4ef89e0e53099a084001b26ec3207c5f8391/config.toml.example#L355 to false in your `config.toml`

Unfortunately `bors try` won't run the noopt tests, so that's the only way to test

Comment (JohnTitor) [reply src/test/ui/issues/issue-8460-const2.rs]: Oh, I didn't know that.
I created `config.toml` with `optimize-tests = false` and ran `x.py test src/test/ui --stage=1 --bless --config config.toml`, the test seems passed.
