### PR TITLE
Include enum path in variant suggestion

### LINKED ISSUE #101356: E0004 non-exhaustive patterns suggestion has unqualified enum variant
Given the following code: 

```rust
enum Foo {
    Variant1,
    Variant2,
}

fn main() {
    match Foo::Variant2 {
        Foo::Variant1 => {}
    }
}
```

The current output is:

```
    Checking foo v0.1.0 (/Users/eric/Temp/foo)
error[E0004]: non-exhaustive patterns: `Variant2` not covered
 --> src/main.rs:7:11
  |
7 |     match Foo::Variant2 {
  |           ^^^^^^^^^^^^^ pattern `Variant2` not covered
  |
note: `Foo` defined here
 --> src/main.rs:3:5
  |
1 | enum Foo {
  |      ---
2 |     Variant1,
3 |     Variant2,
  |     ^^^^^^^^ not covered
  = note: the matched value is of type `Foo`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
  |
8 ~         Foo::Variant1 => {}
9 +         Variant2 => todo!()
  |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `foo` due to previous error
```

The problem with the suggestion is that it suggests `Variant2` without the `Foo::` prefix. Ideally the suggestion should be:

```
9 +         Foo::Variant2 => todo!()
```

The current suggestion does not compile.

```
rustc 1.65.0-nightly (9c20b2a8c 2022-08-17)
```

### PR DESCRIPTION
**Pull request by compiler-errors**
(except for `Result` and `Option`, which we should have via the prelude)

Fixes #101356

### CODE REVIEW

File: compiler/rustc_middle/src/thir.rs [hunk 1]
```diff
@@ -695,17 +695,32 @@ impl<'tcx> fmt::Display for Pat<'tcx> {
...
-                        Some(adt_def.variant(variant_index))
-                    }
-                    _ => self.ty.ty_adt_def().and_then(|adt| {
-                        if !adt.is_enum() { Some(adt.non_enum_variant()) } else { None }
+                let variant_and_name = match self.kind {
+                    PatKind::Variant { adt_def, variant_index, .. } => ty::tls::with(|tcx| {
+                        let variant = adt_def.variant(variant_index);
+                        let adt_did = adt_def.did();
+                        let name = if tcx.get_diagnostic_item(sym::Option) == Some(adt_did)
+                            || tcx.get_diagnostic_item(sym::Result) == Some(adt_did)
```
Comment (PatchMixolydic) [inline compiler/rustc_middle/src/thir.rs:703]: This seems like it might give incorrect suggestions when using [`#![no_implicit_prelude]`](https://doc.rust-lang.org/reference/names/preludes.html#the-no_implicit_prelude-attribute).

Comment (compiler-errors) [reply compiler/rustc_middle/src/thir.rs:703]: I guess, but that could probably be said about plenty of other suggestions where we're currently render. They're, at most, best effort.

I don't think this needs to be fixed, especially because it's basically impossible to determine what the proper shortest path to refer to an item is in any module, due to `rustc_resolve` not exposing, and it would be unnecessarily verbose to print the full untrimmed path (e.g. `std::option::Option::Some`).

Comment (oli-obk) [reply compiler/rustc_middle/src/thir.rs:703]: cc @estebank I remember some tests getting updated that now figure out the best import path to use, but  I may be totally off here

File: compiler/rustc_middle/src/thir.rs [hunk 2]
```diff
@@ -695,17 +695,32 @@ impl<'tcx> fmt::Display for Pat<'tcx> {
...
+                        {
+                            variant.name.to_string()
+                        } else {
+                            format!("{}::{}", tcx.def_path_str(adt_def.did()), variant.name)
```
Comment (estebank) [inline compiler/rustc_middle/src/thir.rs:707]: Don't variants have a def id that can be passed into `def_path_str`?

File: compiler/rustc_middle/src/thir.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_middle/src/thir.rs:703]: I believe the change you remember @oli-obk was about the ordering of suggestions (it filters `core::` paths if the `std::` is available too), not for this. I think that we eventually would want to rebuild suggestions so that we can ask for paths in a specific DefId or HirId so that it is always accurate for that scope, but we're far from there.

I'm ok with landing this as is.

File: compiler/rustc_middle/src/thir.rs [hunk 3]
```diff
@@ -695,17 +695,32 @@ impl<'tcx> fmt::Display for Pat<'tcx> {
...
-                    _ => self.ty.ty_adt_def().and_then(|adt| {
-                        if !adt.is_enum() { Some(adt.non_enum_variant()) } else { None }
+                let variant_and_name = match self.kind {
+                    PatKind::Variant { adt_def, variant_index, .. } => ty::tls::with(|tcx| {
+                        let variant = adt_def.variant(variant_index);
+                        let adt_did = adt_def.did();
+                        let name = if tcx.get_diagnostic_item(sym::Option) == Some(adt_did)
+                            || tcx.get_diagnostic_item(sym::Result) == Some(adt_did)
+                        {
+                            variant.name.to_string()
```
Comment (estebank) [inline compiler/rustc_middle/src/thir.rs:705]: If we use the printing machinery (that only uses the name if it is unique, otherwise the full path), then this suggestion would be mostly right in the face of local shadowing (but see previous comment about needing a function that takes a scope identifier for accurate paths, always).
