### PR TITLE
Make rustdoc JSON Span column 1-based, just like line numbers

### LINKED ISSUE #139906: Line indexes in `Span` are incorrectly claimed to be "zero indexed"
### Location

* https://docs.rs/rustdoc-types/0.39.0/rustdoc_types/struct.Span.html#structfield.begin
* https://docs.rs/rustdoc-types/0.39.0/rustdoc_types/struct.Span.html#structfield.end

### Summary

```sh
echo "pub mod bbb {}" > aaa.rs;
RUSTC_BOOTSTRAP=1 rustdoc aaa.rs -Zunstable-options -wjson -o- |
jq '.index | map(select(.name == "bbb"))[0].span';
rm aaa.rs
```

outputs

```jsonc
{
  "filename": "aaa.rs",
  "begin": [
    1, // Not zero indexed.
    0
  ],
  "end": [
    1, // Not zero indexed.
    11
  ]
}
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/139906.

This PR does two things:
 1. It makes column 1-indexed as well, just like lines.
 2. It updates documentation about them to mention that they are 1-indexed.

I think it's better for coherency to have them both 1-indexed instead of the weird mix we used to have. Docs for `line` and `col` fields can be found [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/struct.Loc.html#structfield.line).

And finally: it adds a regression test to ensure they are indeed 1-indexed.

r? @aDotInTheVoid

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Consider bumping the format version here? Otherwise downstream snapshot tests can't be fixed because the column number is different for different runs within the same format version.

**Comment by GuillaumeGomez** [comment]
And done!

**Comment by obi1kenobi** [comment]
No worries at all, teamwork makes the dream work :)

File: src/rustdoc-json-types/lib.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ pub type FxHashMap<K, V> = HashMap<K, V>; // re-export for use in src/librustdoc
 /// This integer is incremented with every breaking change to the API,
 /// and is returned along with the JSON blob as [`Crate::format_version`].
 /// Consuming code should assert that this value matches the format version(s) that it supports.
-pub const FORMAT_VERSION: u32 = 43;
+pub const FORMAT_VERSION: u32 = 44;
```
Comment (aDotInTheVoid) [inline src/rustdoc-json-types/lib.rs:33]: After https://github.com/rust-lang/rust/pull/139393 lands, this should be rebased ontop of master, and then this should be 44->45 instead. See https://github.com/rust-lang/rust/issues/94591#issuecomment-2810339073 for details.

r=me after that.

Comment (GuillaumeGomez) [reply src/rustdoc-json-types/lib.rs:33]: Shouldn't we do one release for both and therefore only increase by 1?

Comment (aDotInTheVoid) [reply src/rustdoc-json-types/lib.rs:33]: rustdoc-json (the in-tree feature, not the crate) doesn't really do "releases".

Trying to merge them would rely on both PR's first appearing on the same nightly, and that's painful to organize and easy to get wrong. (More of a theoretical concern, but it'd be incorrect if someone was consuming rust from HEAD instead of nightly releases)

Comment (GuillaumeGomez) [reply src/rustdoc-json-types/lib.rs:33]: Makes sense. Well, waiting for #139393 to be merged then. :)

**Comment by GuillaumeGomez** [comment]
https://github.com/rust-lang/rust/pull/139393 was merged, I updated the version number to 45. PR is ready for review. :)

**Comment by obi1kenobi** [comment]
Very excited for this to merge so I can avoid needing to support v44 at all :)
