### PR TITLE
Fix [src] hyperlinks in rustdoc

### LINKED ISSUE #23192: The online documentation no longer links to the source
When visiting a page such as [stdlib](http://doc.rust-lang.org/std/) or [option](http://doc.rust-lang.org/std/option/) the link **src** (for the source code) no longer works. Instead a 404 is returned. This seems to have been broken for several days now.

### PR DESCRIPTION
**Pull request by ipetkov**
- rustdoc was doubly appending the file name to the path of where to
  generate the source files, meanwhile, the [src] hyperlinks were not
- Added a flag to rustdoc::html::render::clean_srcpath to ignore the
  last path component, i.e. the file name itself to prevent the issue
- This also avoids creating directories with the same name as source
  files, and it makes sure the link to `main.css` is correct as well.

Fixes #23192

### CODE REVIEW

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2013-2014 The Rust Project Developers. See the COPYRIGHT
+// Copyright 2013-2015 The Rust Project Developers. See the COPYRIGHT
```
Comment (Gankro) [inline src/librustdoc/html/render.rs]: We've basically agreed to stop touching these. They're legal cargo-culting.

**Comment by Gankro** [comment]
Wouls it be possible to write a regression test for this?

File: src/librustdoc/html/render.rs (hunk 1 above)
Comment (frewsxcv) [inline src/librustdoc/html/render.rs]: @Gankro https://github.com/rust-lang/rust/issues/9070#issuecomment-72514411

Comment (Gankro) [inline src/librustdoc/html/render.rs]: Fair enough.

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by tomjakubowski** [comment]
@ipetkov if you're not familiar with rustdoc integration/regression testing, look in the `src/test/run-make/rustdoc-*` directories. They are run with a Python script located at `etc/htmldocck.py`; in brief parses directives from comments and tries to match text/patterns at a given XPath.

**Comment by Gankro** [comment]
@tomjakubowski Are you interested in being the unofficial-official reviewer for this? You're the most active in this codebase recently.

**Comment by ipetkov** [comment]
@tomjakubowski I wasn't until today, but it seemed pretty straight forward :)

Also the PR has been updated to include a regression test

**Comment by tomjakubowski** [comment]
@ipetkov looks good to me, but I'd prefer if this regression had its own test. `rustdoc-smoke` is already vague enough and I'd rather it not get cluttered over time.

I'm also a little bit curious why this bug only cropped up recently. Generating `[src]` links worked fine  (minus some special cases like the `alloc` crate bug) until a week or so ago and then it broke seemingly out of nowhere.

**Comment by ipetkov** [comment]
@tomjakubowski I'm really not sure what caused the breakage, though I have a feeling it might be related with reforming `PathBuf` because in the past it might not have included the file name when it was converted into an iterator (though I have not looked into it and I could be wrong).

@Gankro @tomjakubowski I've updated the PR so that the regression tests are in their own test rather than in `rustdoc-smoke` and rebased against the updated master.

Sorry for the delay at updating this, my machine suffered from a hardware failure a few nights ago and I haven't had access to my files. I haven't tested (or built) these new updates, though I tried to double check the test cases, and hopefully the build will pass.

File: src/librustdoc/html/render.rs [hunk 2]
```diff
@@ -695,13 +695,18 @@ fn shortty(item: &clean::Item) -> ItemType {
 /// static HTML tree.
 // FIXME (#9639): The closure should deal with &[u8] instead of &str
 // FIXME (#9639): This is too conservative, rejecting non-UTF-8 paths
-fn clean_srcpath<F>(src_root: &Path, p: &Path, mut f: F) where
+fn clean_srcpath<F>(src_root: &Path, p: &Path, keep_filename: bool, mut f: F) where
```
Comment (huonw) [inline src/librustdoc/html/render.rs]: Could you add a brief mention of what `keep_filename` does to the docs?

**Comment by ipetkov** [comment]
@huonw Updated with docs!

**Comment by Manishearth** [comment]
Test breaks on a mac?

http://buildbot.rust-lang.org/builders/auto-mac-64-nopt-t/builds/4122/steps/test/logs/stdio

```
----- /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/run-make/rustdoc-src-links/ --------------------
------ stdout ---------------------------------------------
DYLD_LIBRARY_PATH="/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/obj/x86_64-apple-darwin/test/run-make/rustdoc-src-links:/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/obj/x86_64-apple-darwin/stage2/lib:" /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/obj/x86_64-apple-darwin/stage2/bin/rustdoc -w html -o /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/obj/x86_64-apple-darwin/test/run-make/rustdoc-src-links/doc foo.rs
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/etc/htmldocck.py /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/obj/x86_64-apple-darwin/test/run-make/rustdoc-src-links/doc foo.rs

------ stderr ---------------------------------------------
Traceback (most recent call last):
  File "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/etc/htmldocck.py", line 396, in <module>
    check(sys.argv[1], get_commands(sys.argv[2]))
  File "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/etc/htmldocck.py", line 389, in check
    c.cmd, c.lineno))
RuntimeError: @has check failed at line 42
make[1]: *** [all] Error 1
```

**Comment by ipetkov** [comment]
@huonw @Manishearth d'oh copy paste error in a test file. I was able to test a fix locally and the update should fix things now!
