### PR TITLE
fix(resolve): update def if binding is warning ambiguity

### LINKED ISSUE #115380: no MIR available ICE instead of an ambiguity error
I tried this code:

a.rs:

```rust
pub use a::*;
mod a {
    pub use a::*;
    pub use b::*;
    mod a {
        pub fn f() {}
    }
    mod b {
        pub fn f() {}
    }
}
```

b.rs:

```rust
pub fn main() {
    a::f();
}
```

```console
rustc a.rs --edition=2018 --crate-type=lib
rustc b.rs --edition=2018 --crate-type=lib -L. --extern a
```

I expected it to fail with an ambiguity error, instead it ICEs.

The code compiles successfully in 1.72.

Since #113099 it generates an ICE (it seems that now when an ambiguity is detected, the processing is not fully finalized and effective visibilities and reachability is incomplete).

Reporting primarily due to the fact that the future incompatibility for ambiguous glob imports is not enabled by default for dependencies https://github.com/rust-lang/rust/issues/114095#issuecomment-1699059334, which hides the root cause of the issue.

### Error output

```
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:963:9: no MIR available for DefId(20:8 ~ a[024e]::a::a::f)
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #115380

### CODE REVIEW

File: tests/ui/imports/issue-115380.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// check-pass
+// compile-flags: --emit link
```
Comment (petrochenkov) [inline tests/ui/imports/issue-115380.rs:2]: `--emit link` is already the default, no need to specify it.

File: compiler/rustc_resolve/src/effective_visibilities.rs [hunk 2]
```diff
@@ -141,9 +142,10 @@ impl<'r, 'a, 'tcx> EffectiveVisibilitiesVisitor<'r, 'a, 'tcx> {
 
                     parent_id = ParentId::Import(binding);
                     binding = nested_binding;
+                    warn_ambiguity |= nested_binding.warn_ambiguity;
                 }
-
-                if binding.ambiguity.is_none()
+                let no_ambiguity = binding.ambiguity.is_none() || warn_ambiguity;
+                if no_ambiguity
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/effective_visibilities.rs:148]: The `binding.ambiguity.is_some()` condition a few lines above also needs to be replaced with `binding.ambiguity.is_some() && !warn_ambiguity`.

File: tests/ui/imports/issue-115380.rs (hunk 1 above)
Comment (bvanjoi) [reply tests/ui/imports/issue-115380.rs:2]: When using `﻿./x.py test`, the default value of ﻿`--emit` might be `﻿metadata`. see: https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/runtest.rs#L3707-L3708.

Comment (petrochenkov) [reply tests/ui/imports/issue-115380.rs:2]: If the issue doesn't reproduce with just checking, and the goal is to continue compilation further then the test should probably use `// build-pass` instead of `// check-pass` and specifying `--emit link` manually.
https://rustc-dev-guide.rust-lang.org/tests/ui.html#controlling-passfail-expectations

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-09-14/near/390940232)

@rustbot label +beta-accepted
