### PR TITLE
Prevent `rmake.rs` from using unstable features, and fix 3 run-make tests that currently do

### LINKED ISSUE #137532: Prevent `run-make` test recipes (`rmake.rs`) from using *any* unstable features
Three `rmake.rs` use `unstable` features that cannot be used (because they need to be build by the stage0 compiler which usually is not a nightly compiler), and needs to be fixed (this was a bug in the previous infra implementation and partially rectified in #137373):

- [x] `tests/run-make/issue-107495-archive-permissions/rmake.rs`: https://github.com/rust-lang/rust/blob/f43e549b88698568581a9d329c7582e3708ac187/tests/run-make/issue-107495-archive-permissions/rmake.rs#L1
- [x] `tests/run-make/cross-lang-lto/rmake.rs`: https://github.com/rust-lang/rust/blob/f43e549b88698568581a9d329c7582e3708ac187/tests/run-make/cross-lang-lto/rmake.rs#L6
- [x] `tests/run-make/broken-pipe-no-ice/rmake.rs`: https://github.com/rust-lang/rust/blob/f43e549b88698568581a9d329c7582e3708ac187/tests/run-make/broken-pipe-no-ice/rmake.rs#L14

After these tests are fixed and #137373 merges, we need to:

- [x] Build `rmake.rs` with `RUSTC_BOOTSTRAP=-1` to prevent *any* nightly feature usages within `rmake.rs` recipes by convincing the stage 0 compiler used to build `rmake.rs` that it is a stable-channel compiler. https://github.com/rust-lang/rust/pull/137537
- [x] Explicitly document this requirement in rustc-dev-guide. https://github.com/rust-lang/rust/pull/137537

### FIXME

- [x] Replace `os_pipe` with `anonymous_pipe` once it stabilizes and reaches beta. cf. #135822 or https://github.com/rust-lang/rust/pull/137793.
  - #139976

### PR DESCRIPTION
**Pull request by jieyouxu**
Addresses (mostly) #137532.
Follow-up to #137373.

### Summary

- Fix 3 run-make tests that currently use unstable features:
    1. `tests/run-make/issue-107495-archive-permissions/rmake.rs` uses `#![feature(rustc_private)]` for `libc` on `unix`, but `run_make_support` already exports `libc`, so just use that.
    2. `tests/run-make/cross-lang-lto/rmake.rs` uses `#![feature(path_file_prefix)]` for convenience, replaced with similar filename prefix logic.
    3. `tests/run-make/broken-pipe-no-ice/rmake.rs` uses `#![feature(anonymous_pipe)]` for anonymous pipes. This is more complicated[^race-condition], and I decided to temporarily introduce a dependency on [`os_pipe`] before std's `anonymous_pipe` library feature is stabilized[^pipe-stab]. I left a FIXME tracked by #137532 to make the switch once `anonymous_pipe` stabilizes and reaches beta.
- Use `RUSTC_BOOTSTRAP=-1` when building `rmake.rs` to have the stage 0 rustc reject any unstable features used in `rmake.rs`.

- The requirement that `rmake.rs` may not use any unstable features is now documented in rustc-dev-guide.
- This PR does not impose `RUSTC_BOOTSTRAP=-1` when building `run-make-support`, but I suppose we could.

r? @Kobzol

try-job: x86_64-msvc-1
try-job: x86_64-mingw-1

[`os_pipe`]: https://github.com/oconnor663/os_pipe.rs

[^race-condition]: We can't just try to spawn `rustc` and immediate close the stderr handle because of race condition, as there's no guarantee `rustc` will not try to print to stderr before the handle gets closed.
[^pipe-stab]: In-progress stabilization PR over at https://github.com/rust-lang/rust/pull/135822.

### CODE REVIEW

**Review by Kobzol — COMMENTED** [review]
Thanks! I think that we should do the same for `run-make-support` (disable unstable features), but it's probably not trivial given it is now defined by a macro. Let me know once this is rebased after my PR is merged.

File: tests/run-make/cross-lang-lto/rmake.rs [hunk 1]
```diff
@@ -92,10 +90,17 @@ fn check_bitcode(instructions: LibBuild) {
         llvm_ar().extract().arg(&instructions.output).run();
     }
 
-    for object in shallow_find_files(cwd(), |path| {
-        has_prefix(path, instructions.output.file_prefix().unwrap().to_str().unwrap())
+    let objects = shallow_find_files(cwd(), |path| {
+        let mut output_path = instructions.output.clone();
+        output_path.set_extension("");
```
[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/cross-lang-lto/rmake.rs:95]: Yeah it is not equivalent, however, this is kinda what we want, because if there's something like `$name$hash.cgu0.o` AFAIK we still want to check that file.

**Comment by BoxyUwU** [comment]
TIP: you can start your PR title with the word "wipe" and then it wont be merged, that way you can ensure it isn't merged while its still based on top of another PR

**Comment by jieyouxu** [comment]
> TIP: you can start your PR title with the word "wipe" and then it wont be merged, that way you can ensure it isn't merged while its still based on top of another PR

Fair. It's mostly a remark for myself though 😆

**Comment by jieyouxu** [comment]
> I think that we should do the same for `run-make-support` (disable unstable features), but it's probably not trivial given it is now defined by a macro.

I briefly looked at this, doesn't seem worth it to add a special hack to the `ToolBuild` step or add yet another thing to the macro.

So only rebased, no functional changes.
@rustbot ready

**Comment by Kobzol** [comment]
Thanks, looks good! You can r=me once CI is green.

**Comment by jhpratt** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/138146#issuecomment-2705881581

File: Cargo.lock [hunk 2]
```diff
@@ -2526,6 +2526,16 @@ version = "0.2.0"
...
 checksum = "04744f49eae99ab78e0d5c0b603ab218f515ea8cfe5a456d7629ad883a3b6e7d"
 
+[[package]]
+name = "os_pipe"
+version = "1.2.1"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "5ffd2b0a5634335b135d5728d84c5e0fd726954b87111f7506a61c502280d982"
+dependencies = [
+ "libc",
+ "windows-sys 0.59.0",
```
Comment (jieyouxu) [inline Cargo.lock:2536]: Remark [RAW_DYLIB 1/2]: `os_pipe` depends on `windows-sys` which tries to link in `windows.0.52.0.lib` unless you pass a `--cfg windows_raw_dylib`. This is already what rustc / rustc tool cargo uses. I.e. the comment

```
// By default, windows-rs depends on a native library that doesn't get copied into the
// sysroot. Passing this cfg enables raw-dylib support instead, which makes the native
// library unnecessary. This can be removed when windows-rs enables raw-dylib
// unconditionally.
```

applies here.

File: src/bootstrap/src/core/builder/cargo.rs [hunk 3]
```diff
@@ -597,7 +597,7 @@ impl Builder<'_> {
         // sysroot. Passing this cfg enables raw-dylib support instead, which makes the native
         // library unnecessary. This can be removed when windows-rs enables raw-dylib
         // unconditionally.
-        if let Mode::Rustc | Mode::ToolRustc = mode {
+        if let Mode::Rustc | Mode::ToolRustc | Mode::ToolBootstrap = mode {
             rustflags.arg("--cfg=windows_raw_dylib");
         }
```
Comment (jieyouxu) [inline src/bootstrap/src/core/builder/cargo.rs:602]: Remark [RAW_DYLIB 2/2]: here.

File: src/doc/rustc-dev-guide/src/tests/compiletest.md [hunk 4]
```diff
@@ -415,6 +415,10 @@ Compiletest directives like `//@ only-<target>` or `//@ ignore-<target>` are
 supported in `rmake.rs`, like in UI tests. However, revisions or building
 auxiliary via directives are not currently supported.
 
+`rmake.rs` and `run-make-support` may *not* use any nightly/unstable features,
+as they must be compilable by a stage 0 rustc that may be a beta or even stable
+rustc.
```
Comment (jieyouxu) [inline src/doc/rustc-dev-guide/src/tests/compiletest.md:420]: Remark: adjusted this to also say that `run-make-support` may not depend on nightly/unstable features.

**Comment by jieyouxu** [comment]
This passes on msvc locally, but let's try anyway.
@bors try

**Comment by Kobzol** [comment]
You can r=me if the try job passes.
