### PR TITLE
Reject octal zeros in IPv4 addresses

### LINKED ISSUE #86964: std::net::Ipv4Addr parsing violates the "strict" form in IETF RFC 6943 Section 3.1.1.
According to the `std::net::Ipv4Addr` [documentation](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html), "The four octets are in decimal notation, divided by . (this is called 'dot-decimal notation'). Notably, octal numbers and hexadecimal numbers are not allowed per IETF RFC 6943"; however the parsing of the `&str` `127.0000.0.1` violates the "strict" form mentioned in [Section 3.1.1.](https://datatracker.ietf.org/doc/html/rfc6943#section-3.1.1)—this form is what prohibits octal and hexadecimal numbers—meanwhile the `&str` `127.0.0.001` conforms to it. IETF RFC 6943 Section 3.1.1. states:

   If the af argument of inet_pton() is AF_INET, the src string shall
   be in the standard IPv4 dotted-decimal form:

   ddd.ddd.ddd.ddd

   where "ddd" is a one to three digit decimal number between 0 and
   255.  The inet_pton() function does not accept other formats (such
   as the octal numbers, hexadecimal numbers, and fewer than four
   numbers that inet_addr() accepts).
   As shown above, inet_pton() uses what we will refer to as the
   "strict" form of an IPv4 address literal.  Some platforms also use
   the strict form with getaddrinfo() when the AI_NUMERICHOST flag is
   passed to it.

I tried this code:

```
use std::net::Ipv4Addr;
fn main() {

    // This causes a panic despite violating the "strict" form
    // mentioned in RFC 6943 Section 3.1.1. specifically
    // the fact the second octet is represented as a 4-digit base-10
    // number.
    assert!("127.0000.0.1".parse::<Ipv4Addr>().is_err());
    // This causes a panic despite conforming to the "strict" form
    // mentioned in RFC 6943 Section 3.1.1. specifically
    // it is a string of exactly 4 octets separated by '.'
    // where each octet is represented as a one-to-three digit
    // base-10 number.
    assert!("127.0.0.001".parse::<Ipv4Addr>().is_ok())
}
```

I expected to see this happen: both `assert!`s not causing a panic since the first `&str` has an octet represented by more than three base-10 numbers despite the requirement per RFC 6943 stating each octet be a "one to three digit decimal number". The second `&str` is valid per RFC 6943 since it is a string of exactly 4 octets separated by `.` where each octet is a "one to three digit decimal number".

Instead, this happened: Both lines cause a panic.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-apple-darwin
release: 1.53.0
LLVM version: 12.0.1
```

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (885399992 2021-07-06)
binary: rustc
commit-hash: 885399992c4c1dde37b506b8507a7d69415646b9
commit-date: 2021-07-06
host: x86_64-apple-darwin
release: 1.55.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: \"127.0000.0.1\".parse::<Ipv4Addr>().is_err()', src/main.rs:8:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/panicking.rs:50:5
   3: playground::main
             at /Users/zack/Documents/rust/playground/src/main.rs:8:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/885399992c4c1dde37b506b8507a7d69415646b9/library/core/src/ops/function.rs:227:5
```

</p>
</details>

### PR DESCRIPTION
**Pull request by syvb**
This fixes #86964 by rejecting octal zeros in IP addresses, such that `192.168.00.00000000` is rejected with a parse error, since having leading zeros in front of another zero indicates it is a zero written in octal notation, which is not allowed in the strict mode specified by RFC 6943 3.1.1. Octal rejection was implemented in #83652, but due to the way it was implemented octal zeros were still allowed.

### CODE REVIEW

**Comment by cuviper** [comment]
I understand we're currently a bit "loose" here, but is there any practical difference? It's a numeric 0 either way you look at it. So with your change, we would stop accepting octal zeros just for the sake of strictness?

**Comment by zacknewman** [comment]
The documentation for `std::net::Ipv4Addr` pretty clearly states that the octets are in "decimal notation"; thus I personally don't even understand why the octet `001` is rejected since that is a perfectly reasonable base-10 representation of the integer 1. While that octet can be interpreted in any numeral system (including base-8), the octet `127` can also be interpreted in any numeral system starting from base-8. To me, this is inconsistent and very much confusing. It's like the parser says "`127` can be in base-8, base-9, base-10, etc.; but we will default to interpreting it as base-10"; but for some reason, the parser doesn't apply that same logic to the octet `001`.

The documentation also clearly cites IETF RFC 6943, but Section 3.1.1. in that RFC defines the "strict" form—the form that forbids other numeral systems (e.g., base-8)—as 4 octets in decimal notation separated by a "." such that each octet is between one and three digits. The current behavior doesn't conform to any obvious standard.

Apparently other languages default to interpreting any integer with padded 0s as base-8, but that is not true in most areas of Rust except here (e.g., `assert_eq!("010".parse::<u32>().unwrap(), 10u32);`).

To me if for some reason we want to forbid `0`-padded numbers, then it should be applied consistently for all integers not all integers except 0.

**Comment by cuviper** [comment]
AIUI, it was defined in POSIX that a leading `0` in an IPv4 address should indicate octal. Rust was always parsing as decimal, but this could lead to bugs, even security issues, if you have system that combines Rust and POSIX ideas of a given input address. You might validate "010" in one mode and then use it in the other with a different interpretation. The Rust parser was changed to reject octal to avoid this confusion altogether.

You could debate whether `"0"` alone really has a _leading_ zero to make it octal rather than decimal, but it usually doesn't matter. Longer strings of zeros are more plausibly octal, I guess, but it still seems pedantic to reject it.

**Comment by zacknewman** [comment]
Hm, maybe this is yet another area where my math background is biting me in the butt because it's rather foreign to me to treat leading `0`s as "more likely" to be base-8 than any other base since all numeral systems are based on the same fundamental algorithm.  Seems overly restrictive to assume leading `0`s means base-8 too since clearly something like `008` is not base-8 due to the `8` not being a symbol in the base-8 numeral system; and since the documentation states each octet is in base-10, the problem of "how to interpret each octet" is already answered: base-10. I'm clearly in the minority with this point-of-view though, so I'll drop it.

**Comment by cuviper** [comment]
Octal `0...` goes back to C, at least: https://en.cppreference.com/w/c/language/integer_constant

> - decimal-constant is a non-zero decimal digit (1, 2, 3, 4, 5, 6, 7, 8, 9), followed by zero or more decimal digits (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
> - octal-constant is the digit zero (0) followed by zero or more octal digits (0, 1, 2, 3, 4, 5, 6, 7) 

(which does mean a lone `0` is _technically_ octal as well in C, not that it matters)

**Comment by RalfJung** [comment]
> The documentation for std::net::Ipv4Addr pretty clearly states that the octets are in "decimal notation"; thus I personally don't even understand why the octet 001 is rejected since that is a perfectly reasonable base-10 representation of the integer 1. 

The docs should probably be clarified: the octets are in decimal notation, and leading 0s are disallowed (except, as usual, for a plain `0`).

This *almost* matches current behavior, except for `0000`. So with this PR, those docs would be correct. Without this PR, the docs should say: the octets are in decimal notation, and leading 0s are disallowed, except for the number `0` itself which may have an arbitrary amount of leading 0s.

> Seems overly restrictive to assume leading 0s means base-8

I'm not disagreeing, but this is what other parts of the ecosystem do. It is much better for Rust to reject `011` than for both Rust and POSIX to accept ti *and interpret it differently* -- would you agree to that? We could probably stretch the limits here and reject `011`  but accept `008` (since POSIX could not accept the latter), but that seems even more surprising and weird than just reject leading `0`s outright.

The docs possibly should say that this is why leading 0s are rejected.

**Comment by zacknewman** [comment]
> The docs should probably be clarified: the octets are in decimal notation, and leading 0s are disallowed (except, as usual, for a plain `0`).

That is perfectly OK to me. While I would prefer something like `001.001.001.001` to be parseable because it is technically in base-10—I know my Nintendo Switch requires exactly 3 base-10 digits when typing in the IP—I realize that POSIX compatibility is very important.

> I'm not disagreeing, but this is what other parts of the ecosystem do. It is much better for Rust to reject `011` in IP addresses than for both Rust and POSIX to accept it _and interpret it differently_ -- would you agree to that? Rust does not exist in a vacuum, we have to take into account the surrounding reality here, and reality often uses a leading 0 to indicate octal notation (and yes this makes no mathematical sense; whoever decided that decades ago didn't ask mathematicians it seems, but without a time machine no amount of good arguments is going to change this). We could probably stretch the limits here and reject `011` but accept `008` (since POSIX could not accept the latter), but that seems even more surprising and weird than just rejecting leading `0`s outright.

I absolutely agree. I was not aware POSIX stated that leading `0`s meant base-8 until @cuviper pointed that out (i.e., my "complaint" would have been purely about the documentation and nothing else had I known this). I admit that I am probably in the minority when it comes to my background as a Rustacean. I've never written a line of assembly, C, C++, or kernel code in my life—something I'm not proud of, but c'est la vie—so it very well could be the case that "decimal notation" obviously means "mathematical base-10 with the added restriction that leading 0s are not allowed with the exception of 0 itself which is allowed to have any non-negative integer amount of leading 0s" to the majority of other Rustaceans.

**Comment by RalfJung** [comment]
> so it very well could be the case that "decimal notation" obviously means "mathematical base-10 with the added restriction that leading 0s are not allowed with the exception of 0 itself which is allowed to have any non-negative integer amount of leading 0s" to the majority of other Rustaceans.

I don't think it does. :)  Leading 0s being code for "base 8" is a weird C thing that Rust did *not* do for its own integer literals, but that doesn't help us here.

So, we are in full agreement that the docs should document this more clearly. Usually, lading 0s *are* allowed.

**Comment by RalfJung** [comment]
> While I would prefer something like 001.001.001.001 to be parseable because that is technically valid base-10 (at least mathematically)—I know my Nintendo Switch requires exactly 3 base-10 digits when typing in the IP—I realize that POSIX compatibility is very important.

What I could imagine being useful (but I am not a libs person) is a parsing function that explicitly is *not* POSIX compatible, and that does interpret `010.010.010.010` entirely in decimal. But that should not be the default parsing function. I am not sure if the Rust stdlib is the right place for this, but it might be worth suggesting.

I am honestly quite shocked that POSIX would interpret this as `8.8.8.8`, and I did not know that this is the case... but my `ping` agrees:
```
$ ping 010.010.010.010
PING 010.010.010.010 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=11.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=118 time=10.4 ms
```

**Comment by Smittyvb** [comment]
I've updated the documentation for `Ipv4Addr` to be more clear as what octal/hex literals are, and some examples of which ones are rejected.

**Comment by zacknewman** [comment]
Now this probably is a pedantic request—thus something I am not that passionate about and OK with not doing—but I would like of an example like the parsing of `00.0.0.0` leading to a successful result despite having leading `0`s.

File: library/std/src/net/parser.rs [hunk 1]
```diff
@@ -127,7 +129,16 @@ impl<'a> Parser<'a> {
                 }
             }
 
-            if digit_count == 0 { None } else { Some(result) }
+            if digit_count == 0 {
+                None
+            } else if !allow_zero_prefix
+                && has_leading_zero
+                && (result != T::ZERO || result == T::ZERO && digit_count > 1)
```
Comment (xu-cheng) [inline library/std/src/net/parser.rs:136]: I think this can be simplified as the following:

```suggestion
            } else if !allow_zero_prefix && has_leading_zero && digit_count > 1
```

With this, you also don't need to add `crate::cmp::PartialEq` bound to `ReadNumberHelper`

**Comment by marmeladema** [comment]
Does this require libs team signoff or an fcp or something? This is another breaking change after the one that rejected the octal notation. I've encountered the regression at work and will probably encounter this one too when its available in stable.

That being said, I think the PR does make things more consistent and coherent.

File: library/std/src/net/parser.rs [hunk 2]
```diff
@@ -140,10 +148,7 @@ impl<'a> Parser<'a> {
                 *slot = p.read_separator('.', i, |p| {
                     // Disallow octal number in IP string.
                     // https://tools.ietf.org/html/rfc6943#section-3.1.1
-                    match (p.peek_char(), p.read_number(10, None)) {
-                        (Some('0'), Some(number)) if number != 0 => None,
-                        (_, number) => number,
-                    }
+                    p.read_number(10, None, false)
```
Comment (xu-cheng) [inline library/std/src/net/parser.rs:151]: Just an advice. 

```suggestion
                    p.read_number(10, Some(3), false)
```

With this, we can avoid `if s.len() > 15 {` check in `Ipv4Addr::from_str`.

Comment (Smittyvb) [reply library/std/src/net/parser.rs]: The `s.len() >= 15` check is just an optimization to avoid parsing overly long IPs that can't possibly be valid, it's never been needed.

**Comment by joshtriplett** [comment]
I think we should go ahead with this change.

@rfcbot merge

**Comment by BurntSushi** [comment]
I was personally somewhat on the side of just interpreting octets as decimal, even with a leading zero, POSIX be damned. But one thing that convinced me otherwise was the fact that, well, those leading zeroes are indeed interpreted as indicating octal base in many other places. So if our routine accepts the same IP _but gives a different result than others_, that could indeed be quite surprising. So I think it's the right decision to fail here.

(I am not aware of the history of rejecting octal in this routine, so I may just be re-treading old ground, but wanted to mention it since there was some discussion above.)
