### PR TITLE
Suggest appropriate syntax on missing lifetime specifier in return type

### LINKED ISSUE #55170: Suggest appropriate syntax on missing lifetime specifier in return type
Given [the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=3333fa5b819e9664d80523b63d3c5473):

```
extern crate futures;

use futures::Future;
use std::error::Error;

fn foo() -> impl Future<Item=(), Error=Box<Error>> {
    Ok(())
}
```

Suggest the appropriate syntax to add the `'static` lifetime bound (`Box<Error + 'static>`).

CC: https://www.reddit.com/r/rust/comments/9ozzic/expected_lifetime_parameter_with_future_utilizing/

### PR DESCRIPTION
**Pull request by estebank**
Suggest using `'static` when a lifetime is missing in the return type
with a structured suggestion instead of a note.

Fix #55170.

### CODE REVIEW

File: src/librustc/middle/resolve_lifetime.rs [hunk 1]
```diff
@@ -2241,19 +2242,59 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
                 "this function's return type contains a borrowed value, but \
                  there is no value for it to be borrowed from"
             );
-            help!(db, "consider giving it a 'static lifetime");
+            let msg = "consider giving it a 'static lifetime";
+            match self.tcx.sess.source_map().span_to_snippet(span) {
+                Ok(ref snippet) if snippet == "&" => db.span_suggestion_with_applicability(
```
Comment (oli-obk) [inline src/librustc/middle/resolve_lifetime.rs]: This match has some formattings that threw me off. I think it would be easier on the eyes to have something along the lines of

```rust
Ok(ref snippet) => {
    let (sugg, app) = match &snippet[..] {
        "&" => ("&'static ".to_owned(), Applicability::MachineApplicable),
        "'_" => ("'static ".to_owned(), Applicability::MachineApplicable),
        snippet => (format!("{} + 'static", snippet), Applicability::MaybeIncorrect),
    };
    db.span_suggestion_with_applicability(span, msg, sugg, app);
}
```

File: src/librustc/middle/resolve_lifetime.rs [hunk 2]
```diff
@@ -2241,19 +2242,59 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
...
                  an elided lifetime, but the lifetime cannot be derived from \
                  the arguments"
             );
-            help!(
-                db,
-                "consider giving it an explicit bounded or 'static \
-                 lifetime"
-            );
+            let msg = "consider giving it an explicit bounded or 'static lifetime";
+            match self.tcx.sess.source_map().span_to_snippet(span) {
```
Comment (oli-obk) [inline src/librustc/middle/resolve_lifetime.rs]: same here, in fact, this could probably be unified into a function

File: src/test/ui/associated-types/bound-lifetime-in-binding-only.elision.stderr [hunk 3]
```diff
@@ -2,10 +2,12 @@ error[E0106]: missing lifetime specifier
   --> $DIR/bound-lifetime-in-binding-only.rs:62:23
    |
 LL | fn elision<T: Fn() -> &i32>() {
-   |                       ^ expected lifetime parameter
+   |                       ^
+   |                       |
+   |                       expected lifetime parameter
```
Comment (oli-obk) [inline src/test/ui/associated-types/bound-lifetime-in-binding-only.elision.stderr]: maybe remove the "expected lifetime parameter" message completely? It already says "missing lifetime specifier" in the error message

**Review by oli-obk — CHANGES_REQUESTED** [review]

**Comment by estebank** [comment]
@oli-obk addressed review comments

File: src/librustc/middle/resolve_lifetime.rs [hunk 4]
```diff
@@ -2172,21 +2172,46 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
...
+            add_missing_lifetime_specifiers_label(&mut err, span, lifetime_refs.len());
+        }
 
         err.emit();
     }
 
+    fn suggest_lifetime(&self, db: &mut DiagnosticBuilder<'_>, span: Span, msg: &str) -> bool {
+        match self.tcx.sess.source_map().span_to_snippet(span) {
+            Ok(ref snippet) => {
+                let (sugg, applicability) = if &snippet[..] == "&" {
```
Comment (oli-obk) [inline src/librustc/middle/resolve_lifetime.rs]:
```suggestion
                let (sugg, applicability) = if snippet == "&" {
```

File: src/test/ui/lifetimes/lifetime-elision-return-type-trait.rs [hunk 5]
```diff
@@ -0,0 +1,10 @@
+trait Future {
+    type Item;
+    type Error;
+}
+
+use std::error::Error;
+
+fn foo() -> impl Future<Item=(), Error=Box<Error>> {
+    Ok(())
+}
```
Comment (oli-obk) [inline src/test/ui/lifetimes/lifetime-elision-return-type-trait.rs]:
```suggestion
}

fn main() {}
```

**Comment by oli-obk** [comment]
r=me with nits applied
