### PR TITLE
Force exhaustion in iter::ArrayChunks::into_remainder

### LINKED ISSUE #123333: core::iter::ArrayChunks does not return the remainder if None is never yielded
I tried this code:

```rust
#![feature(iter_array_chunks)]


fn main() {
    let x = [1].into_iter().array_chunks::<2>();
    let x = x.into_remainder();
    assert!(x.is_some());
}
```

I expected to see this happen:
There should be a remainder as `1` will not be yielded.

Instead, this happened:

```
   Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/playground`
thread 'main' panicked at src/main.rs:7:5:
assertion failed: x.is_some()
```

If this is intended behavior, then it should probably be documented, as the current documentation of [ArrayChunks::into_remainder](https://doc.rust-lang.org/std/iter/struct.ArrayChunks.html#method.into_remainder) states that it:

> Returns an iterator over the remaining elements of the original iterator that are not going to be returned by this iterator. The returned iterator will yield at most N-1 elements.

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (805813650 2024-03-31)
binary: rustc
commit-hash: 805813650248c1a2f6f271460d728d1bb852d2a7
commit-date: 2024-03-31
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### PR DESCRIPTION
**Pull request by krtab**
Closes: #123333

### CODE REVIEW

File: library/core/src/iter/adapters/array_chunks.rs [hunk 1]
```diff
@@ -34,9 +34,20 @@ where
...
+    /// let x = [1,2,3,4,5].into_iter().array_chunks::<2>();
+    /// let mut rem = x.into_remainder().unwrap();
+    /// assert_eq!(rem.next(), Some(5));
+    /// assert_eq!(rem.next(), None);
+    /// ```
     #[unstable(feature = "iter_array_chunks", reason = "recently added", issue = "100450")]
     #[inline]
-    pub fn into_remainder(self) -> Option<array::IntoIter<I::Item, N>> {
+    pub fn into_remainder(mut self) -> Option<array::IntoIter<I::Item, N>> {
+        while let Some(_) = self.next() {}
```
Comment (zachs18) [inline library/core/src/iter/adapters/array_chunks.rs:50]:
```suggestion
        if self.remainder.is_none() {
            while let Some(_) = self.next() {}
        }
```

If `I: DoubleEndedIterator + ExactSizeIterator` (thus `Self: DoubleEndedIterator`), and `self.next_back()` has been called, and there is a remainder, then `self.remainder` is already set to `Some`, so we can skip exhausting the iterator. (Optimization , not required for correctness).

Hypothetically, specialization could be used to do the "fast" thing if `I: DEI + ESI` regardless of if the remainder has already been found, but in general that would be unsound (I think?), since user implementations of DEI/ESI can have lifetime requirements.

**Review by zachs18 — CHANGES_REQUESTED** [review]

File: library/core/src/iter/adapters/array_chunks.rs (hunk 1 above)
Comment (krtab) [reply library/core/src/iter/adapters/array_chunks.rs:50]: Nice catch regarding next_back. I'll implement it.
I didn't get your point about specialization.
