### PR TITLE
Use ThreadId instead of TLS-address in `ReentrantLock`

### LINKED ISSUE #123458: ReentrantLock can be held by multiple threads at the same time
The code below verifies that the only one thread holds the ReentrantLock by recording the owner thread id inside. It should be true since the lock is never unlocked (note that the lock guard is leaked). In practice, in some executions the assertion fails:

```rust
#![feature(reentrant_lock)]
#![feature(thread_id_value)]

use std::cell::Cell;
use std::mem::ManuallyDrop;
use std::sync::ReentrantLock;
use std::thread;

fn main() {
    let lock = ReentrantLock::new(Cell::new(None));
    let run = || {
        let id = ManuallyDrop::new(lock.lock());
        match id.get() {
            None => id.set(Some(thread::current().id())),
            Some(id) => assert_eq!(id, thread::current().id()),
        }
    };
    thread::scope(|s| {
        s.spawn(run);
    });
    thread::scope(|s| {
        s.spawn(run);
    });
}
```

```console
$ cargo run
thread '<unnamed>' panicked at src/main.rs:15:25:
assertion `left == right` failed
  left: ThreadId(2)
 right: ThreadId(3)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:21:5:
a scoped thread panicked
```
Inspired by report from https://github.com/rust-lang/miri/issues/3450, which also explains why this fails. 

Ideally the assertion failure wouldn't be among possible executions.

### PR DESCRIPTION
**Pull request by Sp00ph**
Fixes #123458

`ReentrantLock` currently uses the address of a thread local variable as an ID that's unique across all currently running threads. This can lead to uninituitive behavior as in #123458 if TLS blocks get reused. This PR changes `ReentrantLock` to instead use the `ThreadId` provided by `std` as the unique ID. `ThreadId` guarantees uniqueness across the lifetime of the whole process, so we don't need to worry about reusing IDs of terminated threads. The main appeal of this PR is thus the possibility of changing the `ReentrantLock` API to guarantee that if a thread leaks a lock guard, no other thread may ever acquire that lock again.

This does entail some complications:
- previously, the only way to retrieve the current thread ID would've been using `thread::current().id()` which creates a temporary `Arc` and which isn't available in TLS destructors. As part of this PR, the thread ID instead gets cached in its own thread local, as suggested [here](https://github.com/rust-lang/rust/issues/123458#issuecomment-2038207704).
- `ThreadId` is always 64-bit whereas the current implementation uses a usize-sized ID. Since this ID needs to be updated atomically, we can't simply use a single atomic variable on 32 bit platforms. Instead, we fall back to using a (sound) seqlock on 32-bit platforms, which works because only one thread at a time can write to the ID. This seqlock is technically susceptible to the ABA problem, but the attack vector to create actual unsoundness has to be very specific:
  - You would need to be able to lock+unlock the lock exactly 2^31 times (or a multiple thereof) while a thread trying to lock it sleeps
  - The sleeping thread would have to suspend after reading one half of the thread id but before reading the other half
  - The teared result from combining the halves of the thread ID would have to exactly line up with the sleeping thread's ID

The risk of this occurring seems slim enough to be acceptable to me, but correct me if I'm wrong. This also means that the size of the lock increases by 8 bytes on 32-bit platforms, but this also shouldn't be an issue.

Performance wise, I did some crude testing of the only case where this could lead to real slowdowns, which is the case of locking a `ReentrantLock` that's already locked by the current thread. On both aarch64 and x86-64, there is (expectedly) pretty much no performance hit. I didn't have any 32-bit platforms to test the seqlock performance on, so I did the next best thing and just forced the 64-bit platforms to use the seqlock implementation. There, the performance degraded by ~1-2ns/(lock+unlock) on x86-64 and ~6-8ns/(lock+unlock) on aarch64, which is measurable but seems acceptable to me seeing as 32-bit platforms should be a small minority anyways.

cc @joboet @RalfJung @CAD97

### CODE REVIEW

**Comment by RalfJung** [comment]
32bit x86 has max_atomic_width set to 64. So even on those targets we won't be using the seqlock.

File: library/std/src/sync/reentrant_lock.rs [hunk 1]
```diff
@@ -303,18 +385,23 @@ impl<T: ?Sized> Drop for ReentrantLockGuard<'_, T> {
...
-    X.with(|x| <*const _>::addr(x))
+/// Panics if called during a TLS destructor on a thread that hasn't
+/// been assigned an ID.
+pub(crate) fn current_thread_id() -> u64 {
+    #[cold]
+    fn no_tid() -> ! {
+        panic!("Thread hasn't been assigned an ID!")
+    }
+
+    crate::thread::try_current_id().map_or_else(|| no_tid(), |tid| tid.as_u64().get())
```
Comment (RalfJung) [inline library/std/src/sync/reentrant_lock.rs:406]: I think this is more readable as
```suggestion
    crate::thread::try_current_id().unwrap_or_else(|| no_tid()).as_u64().get()
```

File: library/std/src/thread/mod.rs [hunk 2]
```diff
@@ -718,7 +720,25 @@ pub(crate) fn set_current(thread: Thread) {
 /// In contrast to the public `current` function, this will not panic if called
 /// from inside a TLS destructor.
 pub(crate) fn try_current() -> Option<Thread> {
-    CURRENT.try_with(|current| current.get_or_init(|| Thread::new_unnamed()).clone()).ok()
+    CURRENT
+        .try_with(|current| {
+            let thread = current.get_or_init(Thread::new_unnamed).clone();
+            CURRENT_ID.set(Some(thread.id()));
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:726]: So this does a `set` over and over again? Isn't that excessive?

File: library/std/src/thread/mod.rs [hunk 3]
```diff
@@ -699,16 +699,18 @@ where
 
 thread_local! {
     static CURRENT: OnceCell<Thread> = const { OnceCell::new() };
+    static CURRENT_ID: Cell<Option<ThreadId>> = const { Cell::new(None) };
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:702]: So now we redundantly store the thread ID twice, once in the `Thread` and once here?

At least we should explicitly document this invariant. Ideally we can avoid the redundancy...

File: library/std/src/thread/mod.rs [hunk 4]
```diff
@@ -718,7 +720,25 @@ pub(crate) fn set_current(thread: Thread) {
...
+}
+
+/// Gets the id of the thread that invokes it.
+///
+/// If called from inside a TLS destructor and the thread was never
+/// assigned an id, returns `None`.
+#[inline]
+pub(crate) fn try_current_id() -> Option<ThreadId> {
+    if CURRENT_ID.get().is_none() {
+        let _ = try_current();
```
Comment (RalfJung) [inline library/std/src/thread/mod.rs:739]: This will access `CURRENT`, is that really what we want? I thought the goal is to not touch `CURRENT` at all in this function.

File: library/std/src/thread/mod.rs (hunk 3 above)
Comment (Sp00ph) [reply library/std/src/thread/mod.rs:702]: I'm not sure the redundancy can be avoided, seeing as we want to access the thread local without accessing the `Thread` and vice versa. And since the `Thread` instance can outlive the thread itself, we also can't store a reference to the thread local in the `Thread` instance. Maybe we could store something like a `UnsendUnsync<&'static Thread>` in a thread local pointing to the current `Thread` instance? That way we could at least avoid the `Arc` clone + drop that occurs with `thread::current().id()`...

File: library/std/src/thread/mod.rs (hunk 4 above)
Comment (Sp00ph) [reply library/std/src/thread/mod.rs:739]: It'll only access `CURRENT` at most once, when the `CURRENT_ID` is unset. In that case, accessing `CURRENT` is unavoidable, because one way or another you need to access the thread id. `try_current` then initializes the `CURRENT_ID` so that subsequent `try_current_id()` calls don't need to call `try_current()` again.

File: library/std/src/thread/mod.rs (hunk 2 above)
Comment (Sp00ph) [reply library/std/src/thread/mod.rs:726]: Oh right, not sure how I didn't catch that. I suppose I can just move the `CURRENT_ID.set()` into the `get_or_init()` so it's only executed once.

File: library/std/src/sync/reentrant_lock.rs [hunk 5]
```diff
@@ -303,18 +385,23 @@ impl<T: ?Sized> Drop for ReentrantLockGuard<'_, T> {
...
-pub(crate) fn current_thread_unique_ptr() -> usize {
-    // Use a non-drop type to make sure it's still available during thread destruction.
-    thread_local! { static X: u8 = const { 0 } }
-    X.with(|x| <*const _>::addr(x))
+/// Panics if called during a TLS destructor on a thread that hasn't
+/// been assigned an ID.
+pub(crate) fn current_thread_id() -> u64 {
+    #[cold]
+    fn no_tid() -> ! {
+        panic!("Thread hasn't been assigned an ID!")
```
Comment (RalfJung) [inline library/std/src/sync/reentrant_lock.rs:403]: This should probably be `rtabort!` or so, `panic!` may call user code which may try to print things which may try to do reentrant lock stuff again.

File: library/std/src/thread/mod.rs (hunk 4 above)
Comment (RalfJung) [reply library/std/src/thread/mod.rs:739]: Right, the entire lifecycle here is kind of subtle... and there are no comments to help the reader.

There's also the invariant that CURRENT and CURRENT_ID are always initialized together, I think?

Comment (Sp00ph) [reply library/std/src/thread/mod.rs:739]: Yeah, they're always initialized together (but `CURRENT_ID` stays initialized even for TLS dtors, unlike `CURRENT`). I mostly just copied @CAD97's code from #123458, but I can definitely add some comments later.

File: library/std/src/sync/reentrant_lock.rs (hunk 5 above)
Comment (Sp00ph) [reply library/std/src/sync/reentrant_lock.rs:403]: Hm, is there a meaningful difference between this and something like `RwLock::read` (which panics when the reader count hits the max value)? In both cases, if you try to relock it then it'll just panic again.

Comment (Sp00ph) [reply library/std/src/sync/reentrant_lock.rs:403]: > IIRC ReentrantLock is used deep in the guts of std, unlike RwLock? 

That makes sense, I'll change it to an `rtabort!` then.

> Other parts of your PR even assume for correctness that such overflow never happens.

Are you referring to the `seq` counter? That's the only place I can think of where overflow can matter and that can only cause problems in the exact case described in the PR. There's also precedence for this, e.g. `Condvar` also operates like this (though you could argue that the fallout from hitting this case in `Condvar` is smaller as it just keeps a thread asleep indefinitely instead of potentially causing unsoundness).

File: library/std/src/sync/reentrant_lock.rs [hunk 6]
```diff
@@ -72,14 +73,95 @@ use crate::sys::sync as sys;
...
+                        // The acquire-increment in `set()` synchronizes with this release
+                        // store to ensure that `get()` doesn't see data from a subsequent
+                        // `set()` call.
+                        match self.seq.compare_exchange_weak(seq, seq, Release, Acquire) {
+                            Ok(_) => return u64::from(low) | (u64::from(high) << 32),
+                            Err(new) => seq = new,
+                        }
+                    } else {
+                        crate::hint::spin_loop();
+                        seq = self.seq.load(Acquire);
```
Comment (joboet) [inline library/std/src/sync/reentrant_lock.rs:145]: No need to spin here: if there is a write in progress, the current thread cannot be the lock owner.

File: library/std/src/sync/reentrant_lock.rs [hunk 7]
```diff
@@ -72,14 +73,95 @@ use crate::sys::sync as sys;
...
+        use crate::sync::atomic::{AtomicU32, Ordering::{Acquire, Relaxed, Release}};
+
+        struct Tid {
+            seq: AtomicU32,
+            low: AtomicU32,
+            high: AtomicU32,
+        }
+
+        impl Tid {
+            const fn new(tid: u64) -> Self {
```
Comment (joboet) [inline library/std/src/sync/reentrant_lock.rs:119]: This is subjective, but for me this code would be more readable if the `ThreadId` abstraction was only taken away inside here. Upon first glance, this PR seemed unsound to me because I didn't remember that `ThreadId`s are guaranteed to be non-zero, using `u64` instead of `Option<ThreadId>` in the comparison makes the logic clearer. May I suggest doing
```suggestion
            const fn new(tid: Option<ThreadId>) -> Self {
```
and so on?

**Review by joboet — CHANGES_REQUESTED** [review]
Frankly I'm still not entirely convinced that this should be fixed at all, I just don't see what you would want this guarantee for. I struggle to come up with any usecase that couldn't be better solved another way.

@rustbot label +I-libs-api-nominated

As for the implementation, I think you could still use word-sized IDs by recording the number of currently locked `ReentrantLock`s in a TLS variable and leaking the current ID when that number is non-zero on thread exit. But you don't have to do that.

**Comment by Sp00ph** [comment]
bump

File: library/std/src/sync/reentrant_lock.rs [hunk 8]
```diff
@@ -72,14 +74,103 @@ use crate::sys::sync as sys;
...
+                self.0.store(value, Relaxed);
+            }
+        }
+    } else if #[cfg(target_has_atomic = "32")] {
+        use crate::sync::atomic::{AtomicU32, Ordering::{Acquire, Relaxed, Release}};
+
+        struct Tid {
+            seq: AtomicU32,
+            low: AtomicU32,
+            high: AtomicU32,
```
Comment (joboet) [inline library/std/src/sync/reentrant_lock.rs:117]: It just occurred to me: Instead of a seq-lock you could use the thread-local address as a fast check and only if it matches check the thread ID. Since the thread-local address is unique for a thread at any given time, there is no need to synchronize the thread ID, so it can be inside a `Cell`.

File: library/std/src/thread/mod.rs [hunk 9]
```diff
@@ -718,7 +723,32 @@ pub(crate) fn set_current(thread: Thread) {
...
+/// assigned an id, returns `None`.
+#[inline]
+pub(crate) fn try_current_id() -> Option<ThreadId> {
+    if CURRENT_ID.get().is_none() {
+        // If `CURRENT_ID` isn't initialized yet, then `CURRENT` must also not be initialized.
+        // `try_current()` will try to initialize both `CURRENT` and `CURRENT_ID`.
+        // Subsequent calls to `try_current_id` will then no longer enter this if-branch.
+        let _ = try_current();
+    }
+    CURRENT_ID.get()
```
Comment (joboet) [inline library/std/src/thread/mod.rs:751]:
```suggestion
    CURRENT_ID.get().unwrap_or_else(|| {
        // If `CURRENT_ID` isn't initialized yet, then `CURRENT` must also not be initialized. `current()` will initialize both `CURRENT` and `CURRENT_ID` so subsequent calls to `id` will succeed immediately.
        current().id()
    })
```

File: library/std/src/thread/mod.rs [hunk 10]
```diff
@@ -698,17 +698,22 @@ where
 }
 
 thread_local! {
+    // Invariant: `CURRENT` and `CURRENT_ID` will always be initialized
+    // together. However, while `CURRENT_ID` will be available during
+    // TLS constructors, `CURRENT` will not.
```
Comment (joboet) [inline library/std/src/thread/mod.rs:703]: I think you mean destructors? And this isn't quite true, key-based TLS is always destroyed (but can be reinitialized, so this isn't that much of a problem).

File: library/std/src/thread/mod.rs [hunk 11]
```diff
@@ -718,7 +723,32 @@ pub(crate) fn set_current(thread: Thread) {
...
+        })
+        .ok()
+}
+
+/// Gets the id of the thread that invokes it.
+///
+/// If called from inside a TLS destructor and the thread was never
+/// assigned an id, returns `None`.
+#[inline]
+pub(crate) fn try_current_id() -> Option<ThreadId> {
```
Comment (joboet) [inline library/std/src/thread/mod.rs:744]: That's not true. If `CURRENT` hasn't been initialized yet, it can be initialized, even in a TLS destructor. If it has been initialized, and we are inside its destructor, then `CURRENT_ID` has been set already. So the only place where this can fail is if the global allocator calls this function while trying to deallocate the TLS storage for the current ID. The global allocator shouldn't be doing that anyway, so we can just panic in that case. Therefore, this function can be infallible (I slightly prefer the name `id`, like with `current` the module and signature alone suffice IMHO):
```suggestion
#[inline]
pub(crate) fn id() -> ThreadId {
```

**Review by joboet — APPROVED** [review]
Mara is on vacation, so
r? @joboet

I changed my mind, this makes sense. The implementation looks good, but I think it can be slightly improved, if you have the time. Otherwise, I'll just approve this.

**Comment by Sp00ph** [comment]
I believe this addresses all your comments.

File: library/std/src/sync/reentrant_lock.rs [hunk 12]
```diff
@@ -72,14 +74,103 @@ use crate::sys::sync as sys;
 // since we're not dealing with multiple threads. If it's not equal,
 // synchronization is left to the mutex, making relaxed memory ordering for
 // the `owner` field fine in all cases.
+//
+// On systems without 64 bit atomics we use a simple seqlock to emulate a 64 bit Tid using
+// 32 bit atomics (which should be supported on all platforms with `std`). This works
+// because only one thread at a time (the one holding the mutex) writes to it.
```
Comment (joboet) [inline library/std/src/sync/reentrant_lock.rs:80]: This comment needs an update.

File: library/std/src/sync/reentrant_lock.rs [hunk 13]
```diff
@@ -72,14 +74,103 @@ use crate::sys::sync as sys;
...
+            // thread, and may spuriously return `false` if that's not the case.
+            fn contains(&self, owner: ThreadId) -> bool {
+                // SAFETY: See the comments in the struct definition.
+                self.tls_addr.load(Ordering::Relaxed) == tls_addr()
+                    && unsafe { *self.tid.get() } == owner.as_u64().get()
+            }
+
+            #[inline]
+            // This may only be called by one thread at a time.
+            fn set(&self, tid: Option<ThreadId>) {
```
Comment (joboet) [inline library/std/src/sync/reentrant_lock.rs:161]: That's a safety precondition, so I think this needs to be `unsafe`?

File: library/std/src/thread/mod.rs [hunk 14]
```diff
@@ -698,17 +698,20 @@ where
 }
 
 thread_local! {
+    // Invariant: `CURRENT` and `CURRENT_ID` will always be initialized together.
```
Comment (joboet) [inline library/std/src/thread/mod.rs:701]: Could you also add a note about `CURRENT_ID` always holding the same ID as the thread in `CURRENT`, if it is initialized?

**Review by joboet — APPROVED** [review]
Looks good, just some small nits.

**Comment by joboet** [comment]
Great, thank you! Please squash the commits and then r=me.

@bors delegate+
