### PR TITLE
Parse macros named "default" correctly.

### LINKED ISSUE #42292: A macro named `default` can't be called in an impl
There is a corner case where the weak (contextual) keyword `default` can't be used in an identifier position. It occurs when a macro whose path starts with `default` is called inside an `impl`.

```rust
macro_rules! foo {
    ($($x:tt)*) => { $($x)* }
}
macro_rules! default {
    ($($x:tt)*) => { $($x)* }
}

struct A;
impl A {
    foo! { fn bar() {} }
    default! { fn baz() {} } // ERROR
}

fn main() {
    A::bar();
    A::baz();
}
```

Expected behavior: it compiles.

Observed behavior: parse error.

Version: `rustc 1.19.0-nightly (28fd1e519 2017-05-27)`

### PR DESCRIPTION
**Pull request by qnighy**
Fixes #42292.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -3755,6 +3737,18 @@ impl<'a> Parser<'a> {
...
+        // `pub` is included for better error messages
+        self.token.is_keyword(keywords::Default) &&
+        self.look_ahead(1, |t| t.is_keyword(keywords::Impl) ||
+                        t.is_keyword(keywords::Const) ||
+                        t.is_keyword(keywords::Fn) ||
+                        t.is_keyword(keywords::Unsafe) ||
+                        t.is_keyword(keywords::Extern) ||
+                        t.is_keyword(keywords::Type) ||
+                        t.is_keyword(keywords::Pub))
+    }
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Could you do something like this instead, to keep `default` in the expected token set
```rust
fn eat_defaultness(&self) -> bool {
    let is_defaultness = self.is_defaultness();
    if is_defaultness {
        self.bump();
    } else {
        self.expected_tokens.push(/*default keyword token*/);
    }
    is_defaultness
}
```

All this logic can probably be just inlined into `parse_defaultness` as well.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
