### PR TITLE
Bootstrap: Try renaming the file if removing fails

### LINKED ISSUE #127126: spurious ci failure: `The process cannot access the file because it is being used by another process`
See https://github.com/rust-lang/rust/pulls?q=is%3Apr+%22The+process+cannot+access+the+file+because+it+is+being+used+by+another+process%22+is%3Aclosed 

seems to happen on `x86_64-msvc-ext`a lot
```
[RUSTC-TIMING] miri test:false 64.073
[RUSTC-TIMING] miri test:false 2.939
    Finished `release` profile [optimized] target(s) in 0.39s
thread 'main' panicked at src/lib.rs:1697:17:
failed to copy `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools\x86_64-pc-windows-msvc\release\miri.exe` to `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools-bin\miri.exe`: The process cannot access the file because it is being used by another process. (os error 32)
##[endgroup]
Build completed unsuccessfully in 0:00:11
  local time: Sat, Jun 29, 2024  5:48:11 PM
  network time: Sat, 29 Jun 2024 17:48:11 GMT
```

### PR DESCRIPTION
**Pull request by ChrisDenton**
Second attempt at working around https://github.com/rust-lang/rust/issues/127126

If we can't remove the file, then try renaming it. This will leave the destination path free to use.

try-job: x86_64-msvc-ext

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Try build succeeded but considering the failure is intermittent that's doesn't prove this fixes the issue. Still, it's a good sign. I've just tied up the code a bit so I think this is ready for review.

**Comment by onur-ozkan** [comment]
AFAIK it's not possible to rename locked files on Windows.

**Comment by ChrisDenton** [comment]
The file is almost certaibly only locked because it's still being executed. That type of lock allows renames but not deletes (specifically it's locked due to a memory map, not due to a `FILE_SHARE` ).

**Comment by ChrisDenton** [comment]
Incidentally this can be trivially demonstrated on a Windows machine by this program:

```rust
fn main() {
    let exe = std::env::current_exe().unwrap();
    std::fs::rename(&exe, "moved.exe").unwrap();
}
```

That is, an application the renames itself while it is running.

File: src/bootstrap/src/lib.rs [hunk 1]
```diff
@@ -1676,7 +1677,14 @@ impl Build {
...
         }
-        let _ = fs::remove_file(dst);
+        if let Err(e) = fs::remove_file(dst) {
+            if e.kind() != io::ErrorKind::NotFound {
+                // workaround for https://github.com/rust-lang/rust/issues/127126
+                // if removing the file fails, attempt to rename it instead.
+                let now = t!(SystemTime::now().duration_since(SystemTime::UNIX_EPOCH));
+                let _ = fs::rename(dst, format!("{}-{}", dst.display(), now.as_nanos()));
+            }
+        }
```
Comment (onur-ozkan) [inline src/bootstrap/src/lib.rs:1687]: Seems like a good use case `#[cfg(windows)]`.

**Review by onur-ozkan — COMMENTED** [review]
r=me with the nit fix

File: src/bootstrap/src/lib.rs (hunk 1 above)
Comment (ChrisDenton) [reply src/bootstrap/src/lib.rs]: I used `cfg!(windows)` if that's alright as it's easier to integrate.
