### PR TITLE
Restrict linker version script of proc-macro crates to just its two symbols 

### LINKED ISSUE #99978: Don't export no_mangle symbols from proc macros
https://github.com/rust-lang/rust/pull/99944 will hide all non-no_mangle symbols, but given that proc macros will only be loaded by rustc, we can hide all symbols except the specific ones that rustc needs.

### LINKED ISSUE #111888: regression - nightly 2023-03-30 -> 2023-03-31 causes linker error when importing wasm_bindgen::JsValue in a proc_macro
#### (2023-07-19)

1. stylist-rs has been updated with a workaround, so the reproduction described below will need adapting (e.g. check out that repo from around https://github.com/futursolo/stylist-rs/commit/fbd788f0a9a63ccadf6a25e028829a25224140eb or earlier, since that will not include the workaround added in https://github.com/futursolo/stylist-rs/pull/123 )

2. This problem exhibits itself only with certain numbers of codegen-units. The default setting for codegen-units is host dependent (the default is chosen, in part, as a function of the number of cores the host has available, in order to parallelize the code-generation performed by LLVM). In my own experiments, the problem is masked (does not arise) for codegen-units={1,2,4,8}, and the problem *does* arise for codegen-units={16,32,64,128,256}. You are best off passing `-Ccodegen-units` explicit when investigating this, just to ward against that being an invisible factor in the experiments.

(bug report follows below)

### Code

I tried this code:

```toml
[package]
name = "nightly_stylist"
version = "0.1.0"
edition = "2021"

[dependencies]
stylist-macros = "0.12"
```

```rust
fn main() {}
```

[stylist-macros](https://docs.rs/stylist-macros/0.12.0/stylist_macros/)

I expected to see this happen: `cargo check` succeeds in debug mode.

Instead, this happened: `cargo check` fails in debug mode.

```console
  = note: /usr/bin/ld: __wbindgen_realloc: undefined version: 
          /usr/bin/ld: __wbindgen_malloc: undefined version: 
          /usr/bin/ld: __wbindgen_free: undefined version: 
          /usr/bin/ld: __wbindgen_exn_store: undefined version: 
          /usr/bin/ld: failed to set dynamic section sizes: bad value
          collect2: error: ld returned 1 exit status
```

### Version it worked on

```
rustc 1.70.0-nightly (ec2f40c6b 2023-03-30)
binary: rustc
commit-hash: ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b
commit-date: 2023-03-30
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Version with regression

```
rustc 1.70.0-nightly (5e1d3299a 2023-03-31)
binary: rustc
commit-hash: 5e1d3299a290026b85787bc9c7e72bcc53ac283f
commit-date: 2023-03-31
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Cargo bisect-rustc

```
searched toolchains ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b through 5e1d3299a290026b85787bc9c7e72bcc53ac283f


********************************************************************************
Regression in 22a7a19f9333bc1fcba97ce444a3515cb5fb33e6
********************************************************************************
```
*isn't immediately obvious why [this change](https://github.com/rust-lang/rust/commit/22a7a19f9333bc1fcba97ce444a3515cb5fb33e6) would cause the problem

searched nightlies: from nightly-2023-03-27 to nightly-2023-04-02
regressed nightly: nightly-2023-04-01
searched commit range: https://github.com/rust-lang/rust/compare/ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b...5e1d3299a290026b85787bc9c7e72bcc53ac283f
regressed commit: https://github.com/rust-lang/rust/commit/22a7a19f9333bc1fcba97ce444a3515cb5fb33e6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-03-27 --end 2023-04-02 
```
</details>

### PR DESCRIPTION
**Pull request by pnkfelix**
Restrict linker version script of proc-macro crates to just the two symbols of each proc-macro crate. 

The main known effect of doing this is to stop including `#[no_mangle]` symbols in the linker version script.

Background: 

The combination of a proc-macro crate with an import of another crate that itself exports a no_mangle function was broken for a period of time, because:

* In PR #99944 we stopped exporting no_mangle symbols from proc-macro crates; proc-macro crates have a very limited interface and are meant to be treated as a blackbox to everything except rustc itself. However: he constructed linker version script still referred to them, but resolving that discrepancy was left as a FIXME in the code, tagged with issue #99978.
* In PR #108017 we started telling the linker to check (via the`--no-undefined-version` linker invocation flag) that every symbol referenced in the "linker version script" is provided as linker input. So the unresolved discrepancy from #99978 started surfacing as a compile-time error (e.g. #111888).

Fix #111888 
Fix #99978.

### CODE REVIEW

File: tests/ui/proc-macro/no-mangle-in-proc-macro-issue-111888.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
+// run-pass
```
Comment (wesleywiser) [inline tests/ui/proc-macro/no-mangle-in-proc-macro-issue-111888.rs:1]: I think this needs to be `build-pass` since this is a proc-macro and not directly executable. 

```suggestion
// build-pass
```

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 2]
```diff
@@ -1691,6 +1697,26 @@ pub(crate) fn exported_symbols(tcx: TyCtxt<'_>, crate_type: CrateType) -> Vec<St
...
+fn exported_symbols_for_proc_macro_crate(tcx: TyCtxt<'_>) -> Vec<String> {
+    let mut symbols = Vec::new();
+
+    let stable_crate_id = tcx.sess.local_stable_crate_id();
+    let proc_macro_decls_name = tcx.sess.generate_proc_macro_decls_symbol(stable_crate_id);
+    let metadata_symbol_name = exported_symbols::metadata_symbol_name(tcx);
+
+    // You would think that both the two names would always be there, but in
+    // pnkfelix's local experiments that was not case. So instead we walk the
+    // list and only add them if they *are* there.
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Surprising. In what kind of cases is it missing?

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: I didn't investigate too deeply; my memory was that it didn't pass the test suite, so I switched to this...

... but actually, now that I say that: My test suite was borked (without my realizing it) when I was first investigating this (due to my wacky [columns env var issue](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/rustc_expand.20test.20failures.20on.20nightly/near/377370244)). I should re-do the experiment again now that that is resolved.

(I do think that the failing tests were clearly related to this problem; the columns thing was only in later test phases. But it is still worth teasing out explicitly.)

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Okay, so I made a variation that emits warnings when each of the two symbols for a proc-macro crate are missing. 

Here are the first set of ui test suite failures with that in place, all three of which emit neither the decls list symbol nor the metadata symbol.

```
failures:
    [ui] tests/ui/proc-macro/allowed-signatures.rs
    [ui] tests/ui/proc-macro/panic-abort.rs
    [ui] tests/ui/proc-macro/proc-macro-deprecated-attr.rs
```

All three of these are marked as "check-pass" (and I'm now wondering if my own test in this PR should have been "check-pass" instead of "build-pass", which very few of the other proc-macro tests have ...)

I skimmed their sources (linked below) but nothing immediately struck me as being a common root cause that would make *these* specific files fall into the cases in question.

[allow-signatures.rs](https://github.com/rust-lang/rust/blob/5881e5f88d9245ef9259ca600b32af80d5972a7f/tests/ui/proc-macro/allowed-signatures.rs)

[panic-abort](https://github.com/rust-lang/rust/blob/5881e5f88d9245ef9259ca600b32af80d5972a7f/tests/ui/proc-macro/panic-abort.rs)

[proc-macro-deprecated-attr.rs](https://github.com/rust-lang/rust/blob/5881e5f88d9245ef9259ca600b32af80d5972a7f/tests/ui/proc-macro/proc-macro-deprecated-attr.rs)

Comment (wesleywiser) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: > and I'm now wondering if my own test in this PR should have been "check-pass" instead of "build-pass", which very few of the other proc-macro tests have ...

I don't think `check-pass` on this test would truly represent a regression test as `check` doesn't codegen or link the crate.

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Oh wait, ... I think I found the common elements here.

I hypothesize the three test crates listed in my previous comment are the *only* crates in the ui/proc-macro test directory itself (i.e. not the auxiliary directory) that are:
 1. *proc-macro* crates (as opposed to being *users of proc-macros*),
 2. that do not themselves import `extern crate proc_macro;`, and
 3. are set as "check-pass" (rather than "compile-fail") 
 
*That* might explain somewhat why they're singled out in their behavior here.

And maybe these are cases we should not be concerned about supporting? I.e., any well-behaved proc-macro crate should be including `extern crate proc_macro;` in its source listing, right?

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: (Also there's been some relatively recent movement here that might be relevant, in terms of making assumptions about whether codegen does or does not need to be exercised, in PR #114124 )

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: For a check-pass build the linker code shouldn't be invoked at all, right?

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: > For a check-pass build the linker code shouldn't be invoked at all, right?

The linker wouldn't be invoked, right. But my current understanding is that the `exported_symbols` procedure is still *run*, and thus the code I added to this PR to perform the [aforementioned experiment ](https://github.com/rust-lang/rust/pull/114470#discussion_r1284877313) is still exercised (and so we end up seeing the diagnostics I'm emitting, and so the tests fail.

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Here is how I see things. The choice I have in this PR is either:

 1.  unconditionally emit the two symbols, or
 2.  conditionally emit them if and only if we find in them in the traversal performed by `for_each_exported_symbols_include_dep`.

To me, it seems wrong to emit the two symbols if they aren't part of the `for_each_exported_symbols_include_dep` traversal.

So in my head, we can recast the two options above as:

 1. There *should* be an invariant that the two symbols are always in the `for_each_exported_symbols_include_dep` traversal (which would justify the unconditional emission), but today, if that invariant is supposed to hold, it clearly does not. Or
 2. There is no such invariant, and so the emission must be conditional (in the manner that this PR is written today).

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: I suppose I could post a pernos.co build of one of the cases showing the invariant failing. I'll plan to do that on Monday.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Does the invariant ever fail in non-check mode? I think `for_each_exported_symbols_include_dep` simply returns no symbols at all in check mode. It would make sense to me to check `tcx.sess.opts.output_types.should_codegen()` and return an empty list if false.

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:1709]: Okay I'll investigate that option.

Comment (pnkfelix) [reply compiler/rustc_codegen_ssa/src/back/linker.rs]: > It would make sense to me to check tcx.sess.opts.output_types.should_codegen() and return an empty list if false.

This is now done, in commit https://github.com/rust-lang/rust/pull/114470/commits/a2058ddbed82adda55ce39f0e0915996706cb2b9

**Comment by wesleywiser** [comment]
@bors p=1 

Bumping priority as this fixes a P-high regression and is beta-nominated.

**Comment by pnkfelix** [comment]
> ```
> To only update this specific test, also pass `--test-args proc-macro/no-mangle-in-proc-macro-issue-111888.rs`
> 
> error: 1 errors occurred comparing output.
> status: exit status: 0
> command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/proc-macro/no-mangle-in-proc-macro-issue-111888.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=wasm32-unknown-unknown" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/proc-macro/no-mangle-in-proc-macro-issue-111888" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/wasm32-unknown-unknown/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/proc-macro/no-mangle-in-proc-macro-issue-111888/auxiliary"
> --- stderr -------------------------------
> warning: dropping unsupported crate type `proc-macro` for target `wasm32-unknown-unknown`
> 
> warning: 1 warning emitted
> ```

Whoops, I guess I need to add wasm32-unknown-unknown to the targets I include in my local testing.

I'm skimming and I'm not seeing a clear pattern in how the other proc-macro crates in this directory avoid hitting this error. I'm *guessing* most of them are handling it via `// force-host`, but it is strange that not *all* of the `crate_type = "proc-macro"` include that header entry...

**Comment by bjorn3** [comment]
> thread 'main' panicked at 'client.read_exact(&mut header) failed with Connection reset by peer (os error 104)', src/tools/remote-test-client/src/main.rs:310:9

@bors retry spurious connection error for remote test client

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-08-10/near/383637932)

@rustbot label +beta-accepted
