### PR TITLE
Fix SGX delayed host lookup via ToSocketAddr

### LINKED ISSUE #152848: Host lookup via ToSocketAddr broken in SGX
#146541 introduced a regression in the `x86_64-fortanix-unknown-sgx` target, where arguments to TcpStream::connect and TcpListener::bind are no longer being passed down correctly to the underlying platform, resulting in connection/bind failures. See 08abc44fa5eec6639cc10d60efa6807038d107ad

### PR DESCRIPTION
**Pull request by jethrogb**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/152851)*

rust-lang/rust#146541 introduced a regression in the `x86_64-fortanix-unknown-sgx` target, where arguments to TcpStream::connect and TcpListener::bind are no longer being passed down correctly to the underlying platform, resulting in connection/bind failures

* Add a test for the desired behavior (this test passes on Rust 1.33 through 1.91)
* Refactor lookup_host logic again

Fixes rust-lang/rust#152848

cc @joboet

### CODE REVIEW

**Comment by joboet** [comment]
> which is [self-described as a "terrible, terrible hack" that "leads to buggy code"](https://github.com/rust-lang/rust/blob/0028f344ce9f64766259577c998a1959ca1f6a0b/library/std/src/sys/net/connection/sgx.rs#L79)

I should point out that I added that line in https://github.com/rust-lang/rust/pull/145327. But I stand by it, this completely breaks the API of `ToSocketAddrs`.

File: library/std/src/net/socket_addr.rs [hunk 1]
```diff
@@ -189,9 +189,23 @@ impl ToSocketAddrs for (Ipv6Addr, u16) {
...
-fn lookup_host(host: &str, port: u16) -> io::Result<vec::IntoIter<SocketAddr>> {
-    let addrs = crate::sys::net::lookup_host(host, port)?;
-    Ok(Vec::from_iter(addrs).into_iter())
+// Default implementation, this shouldn't be called directly by the function's
+// path in this module. Instead, use the platform-specific implementation
+// (which may be this one).
+//
+// allow(dead_code): This function is only used on some targets
+#[allow(dead_code)]
+pub(crate) fn lookup_host_string(addr: &str) -> io::Result<impl Iterator<Item = SocketAddr>> {
```
Comment (Mark-Simulacrum) [inline library/std/src/net/socket_addr.rs]: Shouldn't this go into sys/common or similar? I feel like that's how we usually treat generic code?

**Review by Mark-Simulacrum — APPROVED** [review]
r=me with fcp finished

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152851/859951e3c7c9d0322c39bad49221937455bdffcd..e2b308726ae6336c837688664953097ce2cab83c)*

File: library/std/src/net/socket_addr.rs (hunk 1 above)
Comment (joshtriplett) [reply library/std/src/net/socket_addr.rs]: Yeah, that's probably true. @jethrogb?

Comment (sardok) [reply library/std/src/net/socket_addr.rs]: @Mark-Simulacrum @joshtriplett I moved the implementation of `lookup_host_string` to `sys/net/connection` and this function is overriden by sgx only now. Let'me know if this change is aligned with your suggestion.
