### PR TITLE
std: Fix thread_local! in non-PIE binaries

### LINKED ISSUE #24445: thread_local!s with destructors segfault in non-PIE executables
```c
void foo();
int main()
{
    foo();
    return 0;
}
```

```rust
#![crate_type = "staticlib"]
 
struct Destroy;
impl Drop for Destroy { fn drop(&mut self) {} }
 
thread_local! {
    static X: Destroy = Destroy
}
 
#[no_mangle]
pub extern "C" fn foo() {
    X.with(|_| ());
}
```

```
rustc staticlib2.rs
gcc staticlib2.c libstaticlib2.a -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o staticlib2
gcc staticlib2.c -pie libstaticlib2.a -ldl -lpthread -lrt -lgcc_s -lpthread -lc -lm -o staticlib2-pie
```

`staticlib2` segfaults, `staticlib2-pie` doesn't.

This is possibly/probably the expected behaviour, but it would be quite nice to not cause a segfault or at least find some way to help the user get it right. (cc http://stackoverflow.com/q/29632715/1256624)

### PR DESCRIPTION
**Pull request by alexcrichton**
One of the parameters to the magical "register a thread-local destructor"
function is called `__dso_handle` and largely just passed along (this seems to
be what other implementations do). Currently we pass the _value_ of this symbol,
but apparently the correct piece of information to pass is the _address_ of the
symbol.

In a PIE binary the symbol actually contains an address to itself which is why
we've gotten away with what we're doing as long as we have. In a non-PIE binary
the symbol contains the address `NULL`, causing a segfault in the runtime
library if it keeps going.

Closes #24445

### CODE REVIEW

**Comment by Manishearth** [comment]
Might have caused http://buildbot.rust-lang.org/builders/auto-linux-64-opt/builds/4486/steps/test/logs/stdio

File: src/test/run-make/issue-24445/foo.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![crate_type = "staticlib"]
+
+struct Destroy;
+impl Drop for Destroy {
+    fn drop(&mut self) { println!("drop"); }
```
Comment (nagisa) [inline src/test/run-make/issue-24445/foo.rs]: This test might not reproduce this issue in the future, when/if `println!` does not depend on `thread_local!` anymore.

Comment (alexcrichton) [inline src/test/run-make/issue-24445/foo.rs]: Oh this was actually just here to help me debug it, it's triggered via the use of `X` instead of the contents of this destructor.
