### PR TITLE
mgca: Add ConstArg representation for const items

### LINKED ISSUE #131046: access outside the bounds for given AllocRange
### Code

```Rust
#![feature(generic_const_exprs, generic_arg_infer, generic_const_items, associated_const_equality, adt_const_params)]
#![allow(incomplete_features)]

fn foo<const N: usize, const M: usize>(_: [(); N + 1 + M]) {}

#![a]

trait Owner {
    const C<const N: u32>: u32;
}

impl Owner for () {
    const C<const N: u32>: u32 = N;
}

fn take0<const N: usize>(_: impl Owner<C<N> = { N }>) {}

fn main() {
    take0::<128>(());
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (7608018cb 2024-09-29)
binary: rustc
commit-hash: 7608018cbdac9e55d0d13529cf43adc33d53efcf
commit-date: 2024-09-29
host: x86_64-apple-darwin
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

```
error: an inner attribute is not permitted in this context
  --> ./9A756-1.rs:11:1
   |
11 |   #![this_just_works]
   |   ^^^^^^^^^^^^^^^^^^^
12 |
13 | / trait Owner {
14 | |     const C<const N: u32>: u32;
15 | | }
   | |_- the inner attribute doesn't annotate this trait
   |
   = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files

error: the constant `N` is not of type `u32`
  --> ./9A756-1.rs:21:40
   |
21 | fn take0<const N: usize>(_: impl Owner<C<N> = { N }>) {}
   |                                        ^^^^^^^^^^^^ expected `u32`, found `usize`
   |
note: required by a const generic parameter in `Owner::C`
  --> ./9A756-1.rs:14:13
   |
14 |     const C<const N: u32>: u32;
   |             ^^^^^^^^^^^^ required by this const generic parameter in `Owner::C`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf/compiler/rustc_middle/src/mir/interpret/allocation.rs:268:9:
access outside the bounds for given AllocRange
stack backtrace:
   0:        0x10d3193e7 - std::backtrace::Backtrace::create::h697070a74b47c5a1
   1:        0x10d319335 - std::backtrace::Backtrace::force_capture::hd4e20dc44637c239
   2:        0x10b13a7ce - std[a533c313b02b6cfe]::panicking::update_hook::<alloc[3194a7a73d70d243]::boxed::Box<rustc_driver_impl[e0e0c21a20d76ec4]::install_ice_hook::{closure#0}>>::{closure#0}
   3:        0x10d334af8 - std::panicking::rust_panic_with_hook::h9b093984c0b2ae3e
   4:        0x10d334735 - std::panicking::begin_panic_handler::{{closure}}::h350248c9538498ad
   5:        0x10d331f49 - std::sys::backtrace::__rust_end_short_backtrace::h51a3ed22bf72bc03
   6:        0x10d3343ac - _rust_begin_unwind
   7:        0x10ff4ff8f - core::panicking::panic_fmt::ha29ff0ee788aef57
   8:        0x10b001b9f - <rustc_middle[3d266d78c9b198e4]::mir::interpret::allocation::AllocRange>::subrange
   9:        0x10b0862dd - <rustc_const_eval[298ced3d0b3bd135]::interpret::memory::AllocRefMut<rustc_middle[3d266d78c9b198e4]::mir::interpret::pointer::CtfeProvenance, ()>>::write_scalar
  10:        0x10b097b4a - <rustc_const_eval[298ced3d0b3bd135]::interpret::eval_context::InterpCx<rustc_const_eval[298ced3d0b3bd135]::const_eval::machine::CompileTimeMachine>>::write_immediate_to_mplace_no_validate
  11:        0x10b097977 - <rustc_const_eval[298ced3d0b3bd135]::interpret::eval_context::InterpCx<rustc_const_eval[298ced3d0b3bd135]::const_eval::machine::CompileTimeMachine>>::write_immediate_no_validate::<rustc_const_eval[298ced3d0b3bd135]::interpret::place::MPlaceTy>
  12:        0x10b0c993b - <rustc_const_eval[298ced3d0b3bd135]::interpret::eval_context::InterpCx<rustc_const_eval[298ced3d0b3bd135]::const_eval::machine::CompileTimeMachine>>::copy_op_no_validate::<rustc_const_eval[298ced3d0b3bd135]::interpret::operand::OpTy, rustc_const_eval[298ced3d0b3bd135]::interpret::place::MPlaceTy>
  13:        0x10b0c278b - <rustc_const_eval[298ced3d0b3bd135]::interpret::eval_context::InterpCx<rustc_const_eval[298ced3d0b3bd135]::const_eval::machine::CompileTimeMachine>>::return_from_current_stack_frame
  14:        0x10b0a1446 - <rustc_const_eval[298ced3d0b3bd135]::interpret::eval_context::InterpCx<rustc_const_eval[298ced3d0b3bd135]::const_eval::machine::CompileTimeMachine>>::eval_terminator
  15:        0x10b0b9cd4 - rustc_const_eval[298ced3d0b3bd135]::const_eval::eval_queries::eval_to_allocation_raw_provider
  16:        0x10c980cfc - rustc_query_impl[75f1704df0e38289]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>
  17:        0x10c93173e - <rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2} as core[907a20686bf8bf7a]::ops::function::FnOnce<(rustc_middle[3d266d78c9b198e4]::ty::context::TyCtxt, rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>)>>::call_once
  18:        0x10c748579 - rustc_query_system[13e780f7d1d88911]::query::plumbing::try_execute_query::<rustc_query_impl[75f1704df0e38289]::DynamicConfig<rustc_query_system[13e780f7d1d88911]::query::caches::DefaultCache<rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[75f1704df0e38289]::plumbing::QueryCtxt, false>
  19:        0x10c9b823c - rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  20:        0x10afc62a2 - rustc_middle[3d266d78c9b198e4]::query::plumbing::query_get_at::<rustc_query_system[13e780f7d1d88911]::query::caches::DefaultCache<rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>>
  21:        0x10b05e831 - rustc_const_eval[298ced3d0b3bd135]::const_eval::valtrees::eval_to_valtree
  22:        0x10bae8d03 - <rustc_const_eval[298ced3d0b3bd135]::provide::{closure#0} as core[907a20686bf8bf7a]::ops::function::FnOnce<(rustc_middle[3d266d78c9b198e4]::ty::context::TyCtxt, rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>)>>::call_once
  23:        0x10c97ee5c - rustc_query_impl[75f1704df0e38289]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>
  24:        0x10c910a7e - <rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[907a20686bf8bf7a]::ops::function::FnOnce<(rustc_middle[3d266d78c9b198e4]::ty::context::TyCtxt, rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>)>>::call_once
  25:        0x10c748579 - rustc_query_system[13e780f7d1d88911]::query::plumbing::try_execute_query::<rustc_query_impl[75f1704df0e38289]::DynamicConfig<rustc_query_system[13e780f7d1d88911]::query::caches::DefaultCache<rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[75f1704df0e38289]::plumbing::QueryCtxt, false>
  26:        0x10c9b946c - rustc_query_impl[75f1704df0e38289]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  27:        0x10bf74b88 - rustc_middle[3d266d78c9b198e4]::query::plumbing::query_get_at::<rustc_query_system[13e780f7d1d88911]::query::caches::DefaultCache<rustc_middle[3d266d78c9b198e4]::ty::ParamEnvAnd<rustc_middle[3d266d78c9b198e4]::mir::interpret::GlobalId>, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 24usize]>>>
  28:        0x10bf796f3 - <rustc_middle[3d266d78c9b198e4]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  29:        0x10bf79028 - <rustc_middle[3d266d78c9b198e4]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  30:        0x10b9c469a - <rustc_infer[9b67ab4c7e1e7e36]::infer::InferCtxt>::const_eval_resolve
  31:        0x10b9b3c9a - <rustc_infer[9b67ab4c7e1e7e36]::infer::InferCtxt>::try_const_eval_resolve
  32:        0x10d0fd1cf - <rustc_trait_selection[1363494f2f4ec6d3]::traits::fulfill::FulfillProcessor as rustc_data_structures[3069d1c4d7b76162]::obligation_forest::ObligationProcessor>::process_obligation::{closure#0}
  33:        0x10d0fc596 - <rustc_trait_selection[1363494f2f4ec6d3]::traits::fulfill::FulfillProcessor as rustc_data_structures[3069d1c4d7b76162]::obligation_forest::ObligationProcessor>::process_obligation
  34:        0x10b602dfb - <rustc_data_structures[3069d1c4d7b76162]::obligation_forest::ObligationForest<rustc_trait_selection[1363494f2f4ec6d3]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[1363494f2f4ec6d3]::traits::fulfill::FulfillProcessor>
  35:        0x10b714556 - <rustc_trait_selection[1363494f2f4ec6d3]::traits::fulfill::FulfillmentContext<rustc_trait_selection[1363494f2f4ec6d3]::traits::FulfillmentError> as rustc_infer[9b67ab4c7e1e7e36]::traits::engine::TraitEngine<rustc_trait_selection[1363494f2f4ec6d3]::traits::FulfillmentError>>::select_where_possible
  36:        0x10b7d18c2 - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_argument_types
  37:        0x10b76d5ce - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::confirm_builtin_call
  38:        0x10b8802b1 - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_expr_kind
  39:        0x10b79c073 - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  40:        0x10b7e087e - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_block_with_expected
  41:        0x10b79c073 - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  42:        0x10b79e237 - <rustc_hir_typeck[83d45668b9c71bf7]::fn_ctxt::FnCtxt>::check_return_expr
  43:        0x10b8661c2 - rustc_hir_typeck[83d45668b9c71bf7]::check::check_fn
  44:        0x10b85f9bc - rustc_hir_typeck[83d45668b9c71bf7]::typeck
  45:        0x10c982a7a - rustc_query_impl[75f1704df0e38289]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75f1704df0e38289]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 8usize]>>
  46:        0x10c7d8f4e - rustc_query_system[13e780f7d1d88911]::query::plumbing::try_execute_query::<rustc_query_impl[75f1704df0e38289]::DynamicConfig<rustc_query_system[13e780f7d1d88911]::query::caches::VecCache<rustc_span[51e7cf5b04f4660f]::def_id::LocalDefId, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[75f1704df0e38289]::plumbing::QueryCtxt, false>
  47:        0x10c9b1bca - rustc_query_impl[75f1704df0e38289]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  48:        0x10b3f209e - <rustc_middle[3d266d78c9b198e4]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[e5ecc290d4e18640]::check_crate::{closure#4}>::{closure#0}
  49:        0x10b57345c - rustc_hir_analysis[e5ecc290d4e18640]::check_crate
  50:        0x10bb0a187 - rustc_interface[ee26b89eef7e70ed]::passes::run_required_analyses
  51:        0x10bb0d170 - rustc_interface[ee26b89eef7e70ed]::passes::analysis
  52:        0x10c982aca - rustc_query_impl[75f1704df0e38289]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75f1704df0e38289]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 1usize]>>
  53:        0x10c7388ee - rustc_query_system[13e780f7d1d88911]::query::plumbing::try_execute_query::<rustc_query_impl[75f1704df0e38289]::DynamicConfig<rustc_query_system[13e780f7d1d88911]::query::caches::SingleCache<rustc_middle[3d266d78c9b198e4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[75f1704df0e38289]::plumbing::QueryCtxt, false>
  54:        0x10c98f177 - rustc_query_impl[75f1704df0e38289]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  55:        0x10b0e3e77 - <rustc_interface[ee26b89eef7e70ed]::queries::QueryResult<&rustc_middle[3d266d78c9b198e4]::ty::context::GlobalCtxt>>::enter::<core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>, rustc_driver_impl[e0e0c21a20d76ec4]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  56:        0x10b14195d - rustc_interface[ee26b89eef7e70ed]::interface::run_compiler::<core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>, rustc_driver_impl[e0e0c21a20d76ec4]::run_compiler::{closure#0}>::{closure#1}
  57:        0x10b12d59c - std[a533c313b02b6cfe]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ee26b89eef7e70ed]::util::run_in_thread_with_globals<rustc_interface[ee26b89eef7e70ed]::util::run_in_thread_pool_with_globals<rustc_interface[ee26b89eef7e70ed]::interface::run_compiler<core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>, rustc_driver_impl[e0e0c21a20d76ec4]::run_compiler::{closure#0}>::{closure#1}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>::{closure#0}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>
  58:        0x10b143f1a - <<std[a533c313b02b6cfe]::thread::Builder>::spawn_unchecked_<rustc_interface[ee26b89eef7e70ed]::util::run_in_thread_with_globals<rustc_interface[ee26b89eef7e70ed]::util::run_in_thread_pool_with_globals<rustc_interface[ee26b89eef7e70ed]::interface::run_compiler<core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>, rustc_driver_impl[e0e0c21a20d76ec4]::run_compiler::{closure#0}>::{closure#1}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>::{closure#0}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[907a20686bf8bf7a]::result::Result<(), rustc_span[51e7cf5b04f4660f]::ErrorGuaranteed>>::{closure#1} as core[907a20686bf8bf7a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:        0x10d33f95b - std::sys::pal::unix::thread::Thread::new::thread_start::hc5e64771570de417
  60:     0x7ff801f5318b - __pthread_start


rustc version: 1.83.0-nightly (7608018cb 2024-09-29)
platform: x86_64-apple-darwin

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `<impl at ./9A756-1.rs:17:1: 17:18>::C`
#1 [eval_to_valtree] evaluating type-level constant
#2 [typeck] type-checking `main`
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### Note
<strong>Ice location:</strong>
https://github.com/rust-lang/rust/blob/7608018cbdac9e55d0d13529cf43adc33d53efcf/compiler/rustc_middle/src/mir/interpret/allocation.rs#L257-L271

### LINKED ISSUE #134641: [ICE]: Associated const projection not yet supported
### Code

```Rust
#![feature(specialization)]
#![feature(associated_const_equality)]

pub trait IsVoid
{
    const IS_VOID: bool;
}
impl<T> IsVoid for T
where
    T: ?Sized
{
    default const IS_VOID: bool = false;
}
impl IsVoid for ()
{
    const IS_VOID: bool = true;
}

pub trait NotVoid: IsVoid<IS_VOID = false>
{

}
impl<T> NotVoid for T
where
    T: IsVoid<IS_VOID = false> + ?Sized
{

}

pub trait Maybe<T>
where
    T: ?Sized
{

}
impl<T> Maybe<T> for T
where
    T: ?Sized
{

}
impl<T> Maybe<T> for ()
where
    T: NotVoid + ?Sized
{

}
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.85.0-nightly (5f23ef7d3 2024-12-20)
binary: rustc
commit-hash: 5f23ef7d3f7a8c3e0ca5c4e1978829c0448a3686
commit-date: 2024-12-20
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6
```

### Current error output

```Shell
thread 'rustc' panicked at /rustc/5f23ef7d3f7a8c3e0ca5c4e1978829c0448a3686/compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:305:25:
associated const projection is not supported yet
stack backtrace:
   0:     0x7d04bc345a25 - std::backtrace::Backtrace::create::hdebb59933e0bdc30
   1:     0x7d04ba957975 - std::backtrace::Backtrace::force_capture::h53ec951c239bfd2c
   2:     0x7d04b9ada1fe - std[da923ce35ba8e93c]::panicking::update_hook::<alloc[4441fbf4cb6e4b6f]::boxed::Box<rustc_driver_impl[c20abde1d352895d]::install_ice_hook::{closure#0}>>::{closure#0}
   3:     0x7d04ba96f8e8 - std::panicking::rust_panic_with_hook::h7657da2fd0e20b26
   4:     0x7d04ba96f5a6 - std::panicking::begin_panic_handler::{{closure}}::hcfd13c7cdcd5288f
   5:     0x7d04ba96d279 - std::sys::backtrace::__rust_end_short_backtrace::h3430a6f8e3db4577
   6:     0x7d04ba96f29d - rust_begin_unwind
   7:     0x7d04b75a9a90 - core::panicking::panic_fmt::h662311b58e97f788
   8:     0x7d04bbbe87d8 - <rustc_type_ir[ae70c870ceb953b8]::predicate::NormalizesTo<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt> as rustc_next_trait_solver[c1d5e55899188338]::solve::assembly::GoalKind<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::consider_impl_candidate
   9:     0x7d04bbc0179a - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  10:     0x7d04bbbfb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  11:     0x7d04bbbf4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  12:     0x7d04bbbefdac - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  13:     0x7d04bbc01f19 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  14:     0x7d04bbbfb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  15:     0x7d04bbbf4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  16:     0x7d04bbbefb0e - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  17:     0x7d04bbbf09f5 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_added_goals_and_make_canonical_response::{closure#0}
  18:     0x7d04bbc02bbb - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  19:     0x7d04bbbfb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  20:     0x7d04bbbf4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  21:     0x7d04bbbefb0e - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  22:     0x7d04bbbf09f5 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_added_goals_and_make_canonical_response::{closure#0}
  23:     0x7d04bbbe92a1 - <rustc_type_ir[ae70c870ceb953b8]::predicate::TraitPredicate<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt> as rustc_next_trait_solver[c1d5e55899188338]::solve::assembly::GoalKind<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::consider_impl_candidate
  24:     0x7d04b88e98f3 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::assemble_and_evaluate_candidates::<rustc_type_ir[ae70c870ceb953b8]::predicate::TraitPredicate<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>
  25:     0x7d04bbc014fd - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  26:     0x7d04bbbfb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  27:     0x7d04bbbf4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  28:     0x7d04bbbedefa - rustc_trait_selection[4ac552fdfe0abeba]::traits::coherence::overlap
  29:     0x7d04bb018499 - <rustc_middle[647cd99ec441dfa7]::traits::specialization_graph::Children as rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph::ChildrenExt>::insert
  30:     0x7d04bbec3075 - <rustc_middle[647cd99ec441dfa7]::traits::specialization_graph::Graph as rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph::GraphExt>::insert
  31:     0x7d04bb1f4c50 - rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph_provider
  32:     0x7d04bb1f49a1 - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7d04bb420fb5 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefIdCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  34:     0x7d04bbe331e8 - rustc_query_impl[baa7e9e66730a851]::query_impl::specialization_graph_of::get_query_incr::__rust_end_short_backtrace
  35:     0x7d04bb6ab290 - rustc_hir_analysis[e35026f032d6c888]::coherence::coherent_trait
  36:     0x7d04bb6aafef - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7d04bb416b72 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefIdCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  38:     0x7d04bb77d9e0 - rustc_query_impl[baa7e9e66730a851]::query_impl::coherent_trait::get_query_incr::__rust_end_short_backtrace
  39:     0x7d04b8b967d5 - rustc_hir_analysis[e35026f032d6c888]::check::wfcheck::check_well_formed
  40:     0x7d04bba1f17b - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7d04bb41a0d2 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_data_structures[d4cf7d399ba92dfc]::vec_cache::VecCache<rustc_span[3a9ac5c7918c6957]::def_id::LocalDefId, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[e35f56ec1f563ec5]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  42:     0x7d04bb41942e - rustc_query_impl[baa7e9e66730a851]::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
  43:     0x7d04bba1f3ec - rustc_hir_analysis[e35026f032d6c888]::check::wfcheck::check_mod_type_wf
  44:     0x7d04bba1f20b - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7d04bbf8aec1 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefaultCache<rustc_span[3a9ac5c7918c6957]::def_id::LocalModDefId, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  46:     0x7d04bbf8bbda - rustc_query_impl[baa7e9e66730a851]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  47:     0x7d04bb250fdc - rustc_hir_analysis[e35026f032d6c888]::check_crate
  48:     0x7d04bb40c23c - rustc_interface[ea487bdd263c790d]::passes::run_required_analyses
  49:     0x7d04bbf1629e - rustc_interface[ea487bdd263c790d]::passes::analysis
  50:     0x7d04bbf1626f - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 0usize]>>
  51:     0x7d04bbf1babc - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::SingleCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  52:     0x7d04bbf1b315 - rustc_query_impl[baa7e9e66730a851]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  53:     0x7d04bbf7f61e - rustc_interface[ea487bdd263c790d]::passes::create_and_enter_global_ctxt::<core[5897668cda8e5696]::option::Option<rustc_interface[ea487bdd263c790d]::queries::Linker>, rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  54:     0x7d04bbfd4aa8 - rustc_interface[ea487bdd263c790d]::interface::run_compiler::<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}
  55:     0x7d04bbee1c87 - std[da923ce35ba8e93c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ea487bdd263c790d]::util::run_in_thread_with_globals<rustc_interface[ea487bdd263c790d]::util::run_in_thread_pool_with_globals<rustc_interface[ea487bdd263c790d]::interface::run_compiler<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  56:     0x7d04bbee211c - <<std[da923ce35ba8e93c]::thread::Builder>::spawn_unchecked_<rustc_interface[ea487bdd263c790d]::util::run_in_thread_with_globals<rustc_interface[ea487bdd263c790d]::util::run_in_thread_pool_with_globals<rustc_interface[ea487bdd263c790d]::interface::run_compiler<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[5897668cda8e5696]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  57:     0x7d04bbee3701 - std::sys::pal::unix::thread::Thread::new::thread_start::h1c08419e700d562f
  58:     0x7d04b62a339d - <unknown>
  59:     0x7d04b632849c - <unknown>
  60:                0x0 - <unknown>


rustc version: 1.85.0-nightly (5f23ef7d3 2024-12-20)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `Maybe`
#1 [coherent_trait] coherence checking all impls of trait `Maybe`
#2 [check_well_formed] checking that `<impl at minimum_reproducable_example/src/main.rs:36:1: 38:14>` is well-formed
#3 [check_mod_type_wf] checking that types are well-formed in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
```

### Backtrace

```Shell
Compiling minimum_reproducable_example v0.1.0 (/home/sigurd/Code/rust/sss/minimum_reproducable_example)
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> minimum_reproducable_example/src/main.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `minimum_reproducable_example`
  --> minimum_reproducable_example/src/main.rs:47:2
   |
47 | }
   |  ^ consider adding a `main` function to `minimum_reproducable_example/src/main.rs`

thread 'rustc' panicked at /rustc/5f23ef7d3f7a8c3e0ca5c4e1978829c0448a3686/compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:305:25:
associated const projection is not supported yet
stack backtrace:
   0:     0x78a95ad6cdda - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h4fc5c49bc95814ca
   1:     0x78a95b41b13c - core::fmt::write::h02478b1210db5d91
   2:     0x78a95c312411 - std::io::Write::write_fmt::hf65323128dc901c4
   3:     0x78a95ad6cc32 - std::sys::backtrace::BacktraceLock::print::heed3495364f53012
   4:     0x78a95ad6f12a - std::panicking::default_hook::{{closure}}::h3a2c63f83169a713
   5:     0x78a95ad6ef73 - std::panicking::default_hook::h5d312750e94809b0
   6:     0x78a959ed9a98 - std[da923ce35ba8e93c]::panicking::update_hook::<alloc[4441fbf4cb6e4b6f]::boxed::Box<rustc_driver_impl[c20abde1d352895d]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x78a95ad6f8e8 - std::panicking::rust_panic_with_hook::h7657da2fd0e20b26
   8:     0x78a95ad6f5a6 - std::panicking::begin_panic_handler::{{closure}}::hcfd13c7cdcd5288f
   9:     0x78a95ad6d279 - std::sys::backtrace::__rust_end_short_backtrace::h3430a6f8e3db4577
  10:     0x78a95ad6f29d - rust_begin_unwind
  11:     0x78a9579a9a90 - core::panicking::panic_fmt::h662311b58e97f788
  12:     0x78a95bfe87d8 - <rustc_type_ir[ae70c870ceb953b8]::predicate::NormalizesTo<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt> as rustc_next_trait_solver[c1d5e55899188338]::solve::assembly::GoalKind<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::consider_impl_candidate
  13:     0x78a95c00179a - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  14:     0x78a95bffb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  15:     0x78a95bff4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  16:     0x78a95bfefdac - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  17:     0x78a95c001f19 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  18:     0x78a95bffb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  19:     0x78a95bff4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  20:     0x78a95bfefb0e - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  21:     0x78a95bff09f5 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_added_goals_and_make_canonical_response::{closure#0}
  22:     0x78a95c002bbb - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  23:     0x78a95bffb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  24:     0x78a95bff4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  25:     0x78a95bfefb0e - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::try_evaluate_added_goals
  26:     0x78a95bff09f5 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_added_goals_and_make_canonical_response::{closure#0}
  27:     0x78a95bfe92a1 - <rustc_type_ir[ae70c870ceb953b8]::predicate::TraitPredicate<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt> as rustc_next_trait_solver[c1d5e55899188338]::solve::assembly::GoalKind<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::consider_impl_candidate
  28:     0x78a958ce98f3 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::assemble_and_evaluate_candidates::<rustc_type_ir[ae70c870ceb953b8]::predicate::TraitPredicate<rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>
  29:     0x78a95c0014fd - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_in_task::<&mut <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  30:     0x78a95bffb086 - <rustc_type_ir[ae70c870ceb953b8]::search_graph::SearchGraph<rustc_next_trait_solver[c1d5e55899188338]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate>, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::with_new_goal::<<rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  31:     0x78a95bff4f62 - <rustc_next_trait_solver[c1d5e55899188338]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[4ac552fdfe0abeba]::solve::delegate::SolverDelegate, rustc_middle[647cd99ec441dfa7]::ty::context::TyCtxt>>::evaluate_goal_raw
  32:     0x78a95bfedefa - rustc_trait_selection[4ac552fdfe0abeba]::traits::coherence::overlap
  33:     0x78a95b418499 - <rustc_middle[647cd99ec441dfa7]::traits::specialization_graph::Children as rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph::ChildrenExt>::insert
  34:     0x78a95c2c3075 - <rustc_middle[647cd99ec441dfa7]::traits::specialization_graph::Graph as rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph::GraphExt>::insert
  35:     0x78a95b5f4c50 - rustc_trait_selection[4ac552fdfe0abeba]::traits::specialize::specialization_graph_provider
  36:     0x78a95b5f49a1 - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 8usize]>>
  37:     0x78a95b820fb5 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefIdCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  38:     0x78a95c2331e8 - rustc_query_impl[baa7e9e66730a851]::query_impl::specialization_graph_of::get_query_incr::__rust_end_short_backtrace
  39:     0x78a95baab290 - rustc_hir_analysis[e35026f032d6c888]::coherence::coherent_trait
  40:     0x78a95baaafef - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  41:     0x78a95b816b72 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefIdCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  42:     0x78a95bb7d9e0 - rustc_query_impl[baa7e9e66730a851]::query_impl::coherent_trait::get_query_incr::__rust_end_short_backtrace
  43:     0x78a958f967d5 - rustc_hir_analysis[e35026f032d6c888]::check::wfcheck::check_well_formed
  44:     0x78a95be1f17b - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  45:     0x78a95b81a0d2 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_data_structures[d4cf7d399ba92dfc]::vec_cache::VecCache<rustc_span[3a9ac5c7918c6957]::def_id::LocalDefId, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[e35f56ec1f563ec5]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  46:     0x78a95b81942e - rustc_query_impl[baa7e9e66730a851]::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
  47:     0x78a95be1f3ec - rustc_hir_analysis[e35026f032d6c888]::check::wfcheck::check_mod_type_wf
  48:     0x78a95be1f20b - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>
  49:     0x78a95c38aec1 - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::DefaultCache<rustc_span[3a9ac5c7918c6957]::def_id::LocalModDefId, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  50:     0x78a95c38bbda - rustc_query_impl[baa7e9e66730a851]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  51:     0x78a95b650fdc - rustc_hir_analysis[e35026f032d6c888]::check_crate
  52:     0x78a95b80c23c - rustc_interface[ea487bdd263c790d]::passes::run_required_analyses
  53:     0x78a95c31629e - rustc_interface[ea487bdd263c790d]::passes::analysis
  54:     0x78a95c31626f - rustc_query_impl[baa7e9e66730a851]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[baa7e9e66730a851]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 0usize]>>
  55:     0x78a95c31babc - rustc_query_system[e35f56ec1f563ec5]::query::plumbing::try_execute_query::<rustc_query_impl[baa7e9e66730a851]::DynamicConfig<rustc_query_system[e35f56ec1f563ec5]::query::caches::SingleCache<rustc_middle[647cd99ec441dfa7]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[baa7e9e66730a851]::plumbing::QueryCtxt, true>
  56:     0x78a95c31b315 - rustc_query_impl[baa7e9e66730a851]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  57:     0x78a95c37f61e - rustc_interface[ea487bdd263c790d]::passes::create_and_enter_global_ctxt::<core[5897668cda8e5696]::option::Option<rustc_interface[ea487bdd263c790d]::queries::Linker>, rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  58:     0x78a95c3d4aa8 - rustc_interface[ea487bdd263c790d]::interface::run_compiler::<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}
  59:     0x78a95c2e1c87 - std[da923ce35ba8e93c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ea487bdd263c790d]::util::run_in_thread_with_globals<rustc_interface[ea487bdd263c790d]::util::run_in_thread_pool_with_globals<rustc_interface[ea487bdd263c790d]::interface::run_compiler<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  60:     0x78a95c2e211c - <<std[da923ce35ba8e93c]::thread::Builder>::spawn_unchecked_<rustc_interface[ea487bdd263c790d]::util::run_in_thread_with_globals<rustc_interface[ea487bdd263c790d]::util::run_in_thread_pool_with_globals<rustc_interface[ea487bdd263c790d]::interface::run_compiler<(), rustc_driver_impl[c20abde1d352895d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[5897668cda8e5696]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  61:     0x78a95c2e3701 - std::sys::pal::unix::thread::Thread::new::thread_start::h1c08419e700d562f
  62:     0x78a9566a339d - <unknown>
  63:     0x78a95672849c - <unknown>
  64:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/sigurd/Code/rust/sss/rustc-ice-2024-12-22T03_01_02-3451.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `Maybe`
#1 [coherent_trait] coherence checking all impls of trait `Maybe`
#2 [check_well_formed] checking that `<impl at minimum_reproducable_example/src/main.rs:36:1: 38:14>` is well-formed
#3 [check_mod_type_wf] checking that types are well-formed in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
For more information about this error, try `rustc --explain E0601`.
warning: `minimum_reproducable_example` (bin "minimum_reproducable_example") generated 1 warning
error: could not compile `minimum_reproducable_example` (bin "minimum_reproducable_example") due to 1 previous error; 1 warning emitted
```

### Anything else?

Managed to reproduce this with just the code shown in this report.

### PR DESCRIPTION
**Pull request by camelid**
tracking issue: rust-lang/rust#132980
fixes rust-lang/rust#131046 
fixes rust-lang/rust#134641

As part of implementing `min_generic_const_args`, we need to distinguish const items that can be used in the type system, such as in associated const equality projections, from const items containing arbitrary const code, which must be kept out of the type system. Specifically, all "type consts" must be either concrete (no generics) or generic with a trivial expression like `N` or a path to another type const item.

To syntactically distinguish these cases, we require, for now at least, that users annotate all type consts with the `#[type_const]` attribute. Then, we validate that the const's right-hand side is indeed eligible to be a type const and represent it differently in the HIR.

We accomplish this representation using a new `ConstItemRhs` enum in the HIR, and a similar but simpler enum in the AST. When `#[type_const]` is **not** applied to a const (e.g. on stable), we represent const item right-hand sides (rhs's) as HIR bodies, like before. However, when the attribute is applied, we instead lower to a `hir::ConstArg`. This syntactically distinguishes between trivial const args (paths) and arbitrary expressions, which are represented using `AnonConst`s. Then in `generics_of`, we can take advantage of the existing machinery to bar the `AnonConst` rhs's from using parent generics.

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/item.rs [hunk 1]
```diff
@@ -182,37 +182,43 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
+                let (generics, (ty, body)) = self.lower_generics(
                     generics,
                     id,
                     ImplTraitContext::Disallowed(ImplTraitPosition::Generic),
                     |this| {
-                        this.lower_const_item(ty, span, expr.as_deref(), ImplTraitPosition::ConstTy)
+                        let ty = this
+                            .lower_ty(ty, ImplTraitContext::Disallowed(ImplTraitPosition::ConstTy));
+                        let body =
+                            this.lower_const_item(span, body_id.unwrap(), expr.as_deref().unwrap());
```
Comment (camelid) [inline compiler/rustc_ast_lowering/src/item.rs:216]: These new unwraps should be correct in theory since an error should've already been emitted, but they might ICE if the compiler didn't stop earlier. It might be a good idea to add ConstArgKind::Err and use delayed_span_bug.

File: compiler/rustc_resolve/src/def_collector.rs [hunk 2]
```diff
@@ -174,6 +174,10 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
                             );
                         }
                     }
+                    // HACK(mgca): see lower_const_item in ast_lowering
+                    ItemKind::Const(box ConstItem { body_id: Some(body_id), .. }) => {
+                        this.create_def(body_id, None, DefKind::AnonConst, i.span);
+                    }
```
Comment (BoxyUwU) [inline compiler/rustc_resolve/src/def_collector.rs:180]: Shouldn't need to be changing def collector, it should just handle anon consts in the AST correctly already. Just need to change `ast::ConstItem` to store an `AnonConst` instead of NodeId/Expr as separate fields. This should also fix some of the ICEs you've been encountering

File: compiler/rustc_hir_analysis/src/lib.rs [hunk 3]
```diff
@@ -214,12 +214,6 @@ pub fn check_crate(tcx: TyCtxt<'_>) {
                 tcx.ensure_ok().eval_static_initializer(item_def_id);
                 check::maybe_check_static_with_link_section(tcx, item_def_id);
             }
-            DefKind::Const if tcx.generics_of(item_def_id).is_empty() => {
-                let instance = ty::Instance::new_raw(item_def_id.into(), ty::GenericArgs::empty());
-                let cid = GlobalId { instance, promoted: None };
-                let typing_env = ty::TypingEnv::fully_monomorphized();
-                tcx.ensure_ok().eval_to_const_value_raw(typing_env.as_query_input(cid));
-            }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/lib.rs:222]: You should be able to replace this with calling your `const_of_item` query then calling `try_normalize_erasing_regions` on it.

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 4]
```diff
@@ -23,6 +23,16 @@ use crate::hir_ty_lowering::{HirTyLowerer, PredicateFilter, RegionInferReason};
...
+    // Anon const as RHS of const item is the body, so should have the same predicates.
+    // FIXME(mgca): probably should have only the predicates of params that are explicitly referenced,
+    // as should generics_of (maybe only under mgca?)
+    if matches!(tcx.def_kind(def_id), DefKind::AnonConst)
+        && let parent = tcx.parent(def_id)
+        && matches!(tcx.def_kind(parent), DefKind::Const | DefKind::AssocConst)
+    {
+        return tcx.predicates_of(parent);
+    }
+
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect/predicates_of.rs:35]: This should instead be a change to `fn generics_of` to set the parent of anon consts of the RHS of a const item to be the parent definition.

Also yeah the logic will need to be different under mgca but on stable we want to just always inherit generic params and predicates

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 5]
```diff
@@ -294,6 +294,29 @@ pub fn eval_to_const_value_raw_provider<'tcx>(
...
+                ));
+            }
+            ty::ConstKind::Expr(_) => return Err(ErrorHandled::TooGeneric(DUMMY_SP)),
+            ty::ConstKind::Param(_) | ty::ConstKind::Placeholder(_) => {
+                return Err(ErrorHandled::TooGeneric(DUMMY_SP));
+            }
+            ty::ConstKind::Infer(_) | ty::ConstKind::Bound(..) => {
+                bug!("unexpected constant {ct:?}")
+            }
+        }
```
Comment (BoxyUwU) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs:319]: I think this is in the slightly wrong place after all. `eval_to_allocation_raw_provider` seems to be the common denominator of all the CTFE entry points so this is currently missing some stuff. If you move it though I think `ConstKind::Value` is going to become a complete pain in the ass to support so we should possibly just *not* support that.

We should change `lower_anon_const` to not special case lowering `{ 1 }` to `Value(0x1)` when the anon const is the rhs of a const item. Then we'll never encounter a `ConstKind::Value` here and dont have to worry about trying to convert it to an allocation or whatever.

File: compiler/rustc_ty_utils/src/instance.rs [hunk 6]
```diff
@@ -90,13 +92,30 @@ fn resolve_instance_raw<'tcx>(
...
+            debug!(" => free or inherent item");
             ty::InstanceKind::Item(def_id)
         };
 
         Ok(Some(Instance { def, args }))
     };
-    debug!("resolve_instance: result={:?}", result);
+    if let Ok(Some(Instance { def: ty::InstanceKind::Item(def_id), args })) = result
+        && matches!(tcx.def_kind(def_id), DefKind::Const | DefKind::AssocConst)
+    {
```
Comment (BoxyUwU) [inline compiler/rustc_ty_utils/src/instance.rs:103]: So it turns out that not all CTFE entry points actually call `try_resolve`, some of them just manually construct an instance for a const item. Not sure what to do about that long term :thinking:

For now though you can go through all the entry points in `rustc_middle/src/mir/interpret/queries` and update everything to use `Instance::expect_resolve` instead of `Instance::new_raw` which should atleast solve any ICEs in the short term until we figure out how to properly handle this

**Comment by BoxyUwU** [comment]
@oli-obk I've assigned you to this PR alongside me because I'd definitely want you to review it before it lands since its so CTFE involved :thinking: I don't think it needs reviewing rn though, things are so up in the air and we're not bootstrapping yet :3

File: compiler/rustc_hir_analysis/src/collect/generics_of.rs [hunk 7]
```diff
@@ -105,6 +106,13 @@ pub(super) fn generics_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> ty::Generics {
             }
 
             match tcx.anon_const_kind(def_id) {
+                // Stable: the RHS of a const item is desugared to be either a const path or an anon const.
+                // If it's an anon const, it should inherit the const item's generics.
+                ty::AnonConstKind::MCG
+                    if matches!(parent_def_kind, DefKind::Const | DefKind::AssocConst) =>
+                {
+                    Some(parent_did)
+                }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect/generics_of.rs:115]: This will probably make the anon const in `const FOO: [u8; ...]` have generics too which is not desirable :thinking: Should look at the HIR instead to see if the parent hir node of the `ConstArg` node is a const item or not. Not sure whether it makes sense to add a new variant to `ty::AnonConstKind` or not, I guess it depends on whether we wind up special casing them elsewhere (e.g. HIR ty lowering).

Actually that reminds me- we should have a test about `const ASSOC: usize = (N);`. It's possible that will get lowered to an anon const instead of a path (expected) and then ICE in ty lowering due to being a bare usage of a generic parameter not lowered to a path. Properly fixing this might just require changing ty lowering to not do anything fancy for anon consts used as the rhs of const items, which probably motivates adding a `ty::AnonConstKind::ConstBody`

File: compiler/rustc_ast_lowering/src/item.rs [hunk 8]
```diff
@@ -172,37 +172,41 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-                let (generics, (ty, body_id)) = self.lower_generics(
+                let (generics, (ty, body)) = self.lower_generics(
                     generics,
                     id,
                     ImplTraitContext::Disallowed(ImplTraitPosition::Generic),
                     |this| {
-                        this.lower_const_item(ty, span, expr.as_deref(), ImplTraitPosition::ConstTy)
+                        let ty = this
+                            .lower_ty(ty, ImplTraitContext::Disallowed(ImplTraitPosition::ConstTy));
+                        let body = this.lower_anon_const_to_const_arg(body.as_deref().unwrap());
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/item.rs]: this unwrap probably causes us to ICE on free const items like `const FOO: u8;` (?)

File: compiler/rustc_ast_lowering/src/item.rs [hunk 9]
```diff
@@ -1033,8 +1026,8 @@ impl<'hir> LoweringContext<'_, 'hir> {
                     |this| {
                         let ty = this
                             .lower_ty(ty, ImplTraitContext::Disallowed(ImplTraitPosition::ConstTy));
-                        let body = this.lower_const_body(i.span, expr.as_deref());
                         this.lower_define_opaque(hir_id, &define_opaque);
+                        let body = this.lower_anon_const_to_const_arg(body.as_deref().unwrap());
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/item.rs]: this unwrap probably causes us to ice on impl assoc consts like `impl Trait for () { const ASSOC: usize; }`

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 10]
```diff
@@ -347,6 +347,31 @@ pub fn eval_to_allocation_raw_provider<'tcx>(
         trace!("const eval: {:?} ({})", key, instance);
     }
 
+    if let ty::InstanceKind::Item(def_id) = key.value.instance.def
+        && matches!(tcx.def_kind(def_id), DefKind::Const | DefKind::AssocConst)
+    {
+        let ct = tcx.const_of_item(def_id).instantiate(tcx, key.value.instance.args);
```
Comment (BoxyUwU) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs]: This is probably wrong because it assumes there's always a rhs of a const item to "get" :thinking:

File: compiler/rustc_ty_utils/src/instance.rs [hunk 11]
```diff
@@ -90,13 +92,30 @@ fn resolve_instance_raw<'tcx>(
...
+        debug!(" => resolved to const item");
+        let ct = tcx.const_of_item(def_id).instantiate(tcx, args);
```
Comment (BoxyUwU) [inline compiler/rustc_ty_utils/src/instance.rs]: this probably is also wrong for the same reason :thinking: We ought to figure out a better way to get the actually evaluatable thing of const items for const eval

File: src/tools/clippy/clippy_lints/src/undocumented_unsafe_blocks.rs [hunk 12]
```diff
@@ -202,13 +201,171 @@ impl<'tcx> LateLintPass<'tcx> for UndocumentedUnsafeBlocks {
...
         let item_has_safety_comment = item_has_safety_comment(cx, item);
+<<<<<<< HEAD
         match item_has_safety_comment {
             HasSafetyComment::Yes(pos) => check_has_safety_comment(cx, item, mk_spans(pos)),
             HasSafetyComment::No => check_has_no_safety_comment(cx, item),
             HasSafetyComment::Maybe => {},
         }
     }
 }
+||||||| parent of ed062304ce5 (mgca: Add ConstArg representation for const items)
```
Comment (BoxyUwU) [inline src/tools/clippy/clippy_lints/src/undocumented_unsafe_blocks.rs]: git whoopsie :3

File: compiler/rustc_ast_lowering/src/item.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_ast_lowering/src/item.rs]: added a `ConstArgKind::Error`

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 13]
```diff
@@ -1231,7 +1232,7 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             LowerTypeRelativePathMode::Const,
         )? {
             TypeRelativePath::AssocItem(def_id, args) => {
-                if !tcx.associated_item(def_id).is_type_const_capable(tcx) {
+                if !find_attr!(self.tcx().get_all_attrs(def_id), AttributeKind::TypeConst(_)) {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1282]: I don't know why `find_attr!` works here but `tcx.has_attr(sym::type_const)` doesnt. cc @jdonszelmann does `has_attr` work with new style attributes?

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1282]: https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_hir/hir.rs.html#1283 seems like no new style attributes don't work with `has_attr` if it's been parsed

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1282]: it works *sometimes* though because we added `has_attr` calls in some places to fix ICEs which worked. 

edit: ah no it probably just made that code unreachable lmao

File: compiler/rustc_ast/src/ast.rs [hunk 14]
```diff
@@ -3754,10 +3754,29 @@ pub struct ConstItem {
     pub ident: Ident,
     pub generics: Generics,
     pub ty: Box<Ty>,
-    pub expr: Option<Box<Expr>>,
+    pub body: Option<ConstItemRhs>,
```
Comment (BoxyUwU) [inline compiler/rustc_ast/src/ast.rs]:
```suggestion
    pub rhs: Option<ConstItemRhs>,
```

body terminology doesn't make too much sense since it's only *sometimes* a body

File: compiler/rustc_const_eval/src/check_consts/qualifs.rs [hunk 15]
```diff
@@ -366,8 +370,15 @@ where
         // check performed after the promotion. Verify that with an assertion.
         assert!(promoted.is_none() || Q::ALLOW_PROMOTED);
 
-        // Don't peek inside trait associated constants.
-        if promoted.is_none() && cx.tcx.trait_of_assoc(def).is_none() {
+        let is_type_const_item = matches!(cx.tcx.def_kind(def), DefKind::Const | DefKind::AssocConst)
+            && find_attr!(cx.tcx.get_all_attrs(def), AttributeKind::TypeConst(_));
```
Comment (BoxyUwU) [inline compiler/rustc_const_eval/src/check_consts/qualifs.rs]: this probably can just be inlined into the `if` and the `matches` dropped. we should only ever have `type_const` on `DefKind::Const` and `DefKind::AssocConst` anyway

File: compiler/rustc_const_eval/src/const_eval/valtrees.rs [hunk 16]
```diff
@@ -349,6 +349,20 @@ pub fn valtree_to_const_value<'tcx>(
     }
 }
 
+#[instrument(skip(tcx), level = "debug", ret)]
+pub(crate) fn valtree_to_const_alloc<'tcx>(
```
Comment (BoxyUwU) [inline compiler/rustc_const_eval/src/const_eval/valtrees.rs]: can be removed now

File: compiler/rustc_hir/src/hir.rs [hunk 17]
```diff
@@ -4368,7 +4386,8 @@ pub enum ItemKind<'hir> {
     /// A `static` item.
     Static(Mutability, Ident, &'hir Ty<'hir>, BodyId),
     /// A `const` item.
-    Const(Ident, &'hir Generics<'hir>, &'hir Ty<'hir>, BodyId),
+    // TODO: make sure we only allow usage of path RHS in generic contexts under mgca, not stable!
```
Comment (BoxyUwU) [inline compiler/rustc_hir/src/hir.rs]: This is now done, uncertain whether we may want some kind of ast validator or hir visitor to assert this :3

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 18]
```diff
@@ -1544,3 +1546,31 @@ fn anon_const_kind<'tcx>(tcx: TyCtxt<'tcx>, def: LocalDefId) -> ty::AnonConstKin
         _ => ty::AnonConstKind::NonTypeSystem,
     }
 }
+
+fn const_of_item<'tcx>(
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect.rs:1549]:
```suggestion
#[instrument(level = "debug", skip(tcx), ret)]
fn const_of_item<'tcx>(
```
seems useful for debugging

File: compiler/rustc_hir_analysis/src/collect/type_of.rs [hunk 19]
```diff
@@ -104,6 +104,12 @@ fn const_arg_anon_type_of<'tcx>(icx: &ItemCtxt<'tcx>, arg_hir_id: HirId, span: S
             icx.lower_ty(ty)
         }
 
+        Node::Item(hir::Item { kind: hir::ItemKind::Const(..), owner_id, .. })
+        | Node::ImplItem(hir::ImplItem { kind: hir::ImplItemKind::Const(..), owner_id, .. })
+        | Node::TraitItem(hir::TraitItem {
+            kind: hir::TraitItemKind::Const(..), owner_id, ..
+        }) => tcx.type_of(owner_id.def_id).instantiate_identity(),
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect/type_of.rs]: shouldnt be necessary anymore as we only have anon consts for the rhs of type consts which are fed in `const_of_item`

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 20]
```diff
@@ -2161,7 +2171,9 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             }
             // We error when the type contains unsubstituted generics since we do not currently
             // give the anon const any of the generics from the parent.
-            if anon_const_type.has_non_region_param() {
+            if tcx.features().generic_const_parameter_types()
+                && anon_const_type.has_non_region_param()
+            {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: can be reverted now that we only have anon consts for type consts which are non-generic

File: compiler/rustc_lint/src/context.rs [hunk 21]
```diff
@@ -978,9 +978,9 @@ impl<'tcx> LateContext<'tcx> {
                     ..
                 }) => *init,
                 hir::Node::Item(item) => match item.kind {
-                    hir::ItemKind::Const(.., body_id) | hir::ItemKind::Static(.., body_id) => {
-                        Some(self.tcx.hir_body(body_id).value)
-                    }
+                    // TODO(mgca): figure out how to handle ConstArgKind::Path (or don't but add warning in docs here)
```
Comment (BoxyUwU) [inline compiler/rustc_lint/src/context.rs]:
```suggestion
                    // FIXME(mgca): figure out how to handle ConstArgKind::Path (or don't but add warning in docs here)
```

File: compiler/rustc_middle/src/mir/interpret/queries.rs [hunk 22]
```diff
@@ -134,6 +134,7 @@ impl<'tcx> TyCtxt<'tcx> {
                 // If we don't *only* FCW anon consts we can wind up incorrectly FCW'ing uses of assoc
                 // consts in pattern positions. #140447
                 && self.def_kind(cid.instance.def_id()) == DefKind::AnonConst
+                && self.anon_const_kind(cid.instance.def_id()) == ty::AnonConstKind::RepeatExprCount
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/mir/interpret/queries.rs]:
```suggestion
```
can be reverted now that we dont have anon consts for non-type_consts

File: compiler/rustc_trait_selection/src/traits/normalize.rs [hunk 23]
```diff
@@ -284,7 +284,6 @@ impl<'a, 'b, 'tcx> AssocTypeNormalizer<'a, 'b, 'tcx> {
         }
     }
 
-    // FIXME(mgca): While this supports constants, it is only used for types by default right now
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/normalize.rs:287]: should re-add this, the fixme is about stabilizing mgca and how on stable `Foo<{ <u8 as Trait>::Assoc }>` doesnt go through this codepath

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 24]
```diff
@@ -483,7 +483,6 @@ fn normalize_to_error<'a, 'tcx>(
 }
 
 /// Confirm and normalize the given inherent projection.
-// FIXME(mgca): While this supports constants, it is only used for types by default right now
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/project.rs:486]: ditto

File: compiler/rustc_hir_analysis/src/collect/type_of.rs [hunk 25]
```diff
@@ -459,7 +459,7 @@ fn infer_placeholder_type<'tcx>(
                     );
                 } else {
                     with_forced_trimmed_paths!(err.span_note(
-                        tcx.hir_body(body_id).value.span,
+                        tcx.hir_span(hir_id),
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/collect/type_of.rs]: maybe this is what caused the weird span changes :thinking:

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/collect/type_of.rs]: yh it was

**Comment by BoxyUwU** [comment]
(rustfmt changes seem to have been accidental and have since been removed)

File: compiler/rustc_hir/src/hir.rs (hunk 17 above)
Comment (camelid) [reply compiler/rustc_hir/src/hir.rs]: We decided we don't need the validator because the fact that all UI tests pass ends up validating that the lowering is correct.

File: compiler/rustc_hir_analysis/src/collect.rs [hunk 26]
```diff
@@ -1543,3 +1544,32 @@ fn anon_const_kind<'tcx>(tcx: TyCtxt<'tcx>, def: LocalDefId) -> ty::AnonConstKin
...
+        hir::ConstItemRhs::TypeConst(ct_arg) => ct_arg,
+        hir::ConstItemRhs::Body(body_id) => {
+            bug!("cannot call const_of_item on a non-type_const {body_id:?}")
+        }
+    };
+    let icx = ItemCtxt::new(tcx, def_id);
+    let identity_args = ty::GenericArgs::identity_for_item(tcx, def_id);
+    let ct = icx
+        .lowerer()
+        .lower_const_arg(ct_arg, FeedConstTy::Param(def_id.to_def_id(), identity_args));
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/collect.rs:1573]: handle the case where the lowerer has an error registered and unconditionally produce an error constant in that case (see what type_of does)

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 27]
```diff
@@ -1604,6 +1604,23 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
...
+            {
+                let assoc_item = tcx.associated_item(def_id);
+                let should_encode = match assoc_item.container {
+                    ty::AssocContainer::InherentImpl | ty::AssocContainer::TraitImpl(_) => true,
+                    ty::AssocContainer::Trait => assoc_item.defaultness(tcx).has_value(),
+                };
+                if should_encode {
+                    record!(self.tables.const_of_item[def_id] <- self.tcx.const_of_item(def_id));
+                }
+            }
```
Comment (oli-obk) [inline compiler/rustc_metadata/src/rmeta/encoder.rs]: use a single `should_encode` function to check whether we should encode and only have one site that actually does the record! call

File: compiler/rustc_middle/src/query/mod.rs [hunk 28]
```diff
@@ -293,6 +293,13 @@ rustc_queries! {
         separate_provide_extern
     }
 
+    /// Returns the const of the RHS of a const item.
+    query const_of_item(def_id: DefId) -> ty::EarlyBinder<'tcx, ty::Const<'tcx>> {
+        desc { |tcx| "computing the value for `{}`", tcx.def_path_str(def_id)  }
```
Comment (oli-obk) [inline compiler/rustc_middle/src/query/mod.rs]: computing the *type value*

or sth like that

File: compiler/rustc_middle/src/query/mod.rs [hunk 29]
```diff
@@ -293,6 +293,13 @@ rustc_queries! {
         separate_provide_extern
     }
 
+    /// Returns the const of the RHS of a const item.
```
Comment (oli-obk) [inline compiler/rustc_middle/src/query/mod.rs]: give some info about what it's used for and that it can only be used on type consts and will ICE otherwise

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/free_alias.rs [hunk 30]
```diff
@@ -30,14 +30,12 @@ where
         );
 
         let actual = if free_alias.kind(cx).is_type() {
-            cx.type_of(free_alias.def_id).instantiate(cx, free_alias.args)
+            cx.type_of(free_alias.def_id).instantiate(cx, free_alias.args).into()
         } else {
-            // FIXME(mgca): once const items are actual aliases defined as equal to type system consts
-            // this should instead return that.
-            panic!("normalizing free const aliases in the type system is unsupported");
+            cx.const_of_item(free_alias.def_id).instantiate(cx, free_alias.args).into()
```
Comment (oli-obk) [inline compiler/rustc_next_trait_solver/src/solve/normalizes_to/free_alias.rs:35]: <3 🎇 !!!!

File: compiler/rustc_trait_selection/src/traits/normalize.rs [hunk 31]
```diff
@@ -436,51 +437,40 @@ impl<'a, 'b, 'tcx> TypeFolder<TyCtxt<'tcx>> for AssocTypeNormalizer<'a, 'b, 'tcx
...
-                DefKind::Const | DefKind::AnonConst => self.normalize_free_alias(uv.into()),
-                kind => {
-                    unreachable!("unexpected `DefKind` for const alias to resolve to: {:?}", kind)
+        let uv = match ct.kind() {
+            ty::ConstKind::Unevaluated(uv) => uv,
+            _ => return ct.super_fold_with(self),
+        };
+
+        let ct = match tcx.def_kind(uv.def) {
+            DefKind::AssocConst => match tcx.def_kind(tcx.parent(uv.def)) {
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/normalize.rs:453]: explain that these are unreachable on stable without also triggering a feature gate error during parsing (typed const attr) or during lowering (path to const lowering)

File: compiler/rustc_const_eval/src/check_consts/qualifs.rs [hunk 32]
```diff
@@ -365,8 +367,14 @@ where
...
         assert!(promoted.is_none() || Q::ALLOW_PROMOTED);
 
-        // Don't peek inside trait associated constants.
-        if promoted.is_none() && cx.tcx.trait_of_assoc(def).is_none() {
+        // Avoid looking at attrs of anon consts as that will ICE
+        let is_type_const_item =
+            matches!(cx.tcx.def_kind(def), DefKind::Const | DefKind::AssocConst)
+                && find_attr!(cx.tcx.get_all_attrs(def), AttributeKind::TypeConst(_));
+
+        // Don't peak inside trait associated consatnts, also `#[type_const] const` items
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/check_consts/qualifs.rs]: typo: consatnts

File: tests/ui/const-generics/mgca/bad-type_const-syntax.rs [hunk 33]
```diff
@@ -9,8 +9,7 @@ struct S;
 
 impl Tr for S {
     #[type_const]
-    //~^ ERROR must only be applied to trait associated constants
-    //~| ERROR experimental
+    //~^ ERROR experimental
     const N: usize = 0;
 }
```
Comment (oli-obk) [inline tests/ui/const-generics/mgca/bad-type_const-syntax.rs:14]: Add a test where the trait uses type_const but the impl doesn't (and vice versa, where I guess the latter should work in monomorphic contexts?)

File: compiler/rustc_hir/src/hir.rs
Comment (oli-obk) [inline compiler/rustc_hir/src/hir.rs:1]: no test changes? 😆

File: tests/ui/associated-type-bounds/duplicate-bound-err.rs
Comment (oli-obk) [inline tests/ui/associated-type-bounds/duplicate-bound-err.rs:1]: squash this commit into the appropriate commit that requires the test change

**Review by oli-obk — APPROVED** [review]
r=me with rustdoc and some cleanups and docs

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/139558/fca2e941f86f51cd3c3254518f45e2145563f6be..f47bcbd246df3db53d2df3ebf6ef3be9a3b5c7b8)*

File: compiler/rustc_middle/src/query/mod.rs (hunk 29 above)
Comment (camelid) [reply compiler/rustc_middle/src/query/mod.rs]: As I was addressing your above comment I actually did this before I noticed it haha.

File: compiler/rustc_trait_selection/src/traits/normalize.rs (hunk 31 above)
Comment (camelid) [reply compiler/rustc_trait_selection/src/traits/normalize.rs:453]: I don't think the path to const lowering code ever triggers a feature gate error if `#[type_const]` is used on stable. It just changes the lowering slightly, but still generates a const arg. But added a comment about how parsing would've emitted an error.

File: compiler/rustc_hir/src/hir.rs
Comment (camelid) [reply compiler/rustc_hir/src/hir.rs:1]: Probably an artifact of the numerous rebases...

File: tests/ui/const-generics/mgca/bad-type_const-syntax.rs (hunk 33 above)
Comment (camelid) [reply tests/ui/const-generics/mgca/bad-type_const-syntax.rs:14]: type_const on trait but not impl causes an ice currently. I'm gonna be adding the rest of the type_const validity checks in a future PR, though we might need to use delayed_bug as well.

Comment (oli-obk) [reply tests/ui/const-generics/mgca/bad-type_const-syntax.rs:14]: OK wfm

**Comment by Mark-Simulacrum** [comment]
Marking perf regression as triaged. This is required for feature work, though it does seem a little unfortunate that we're actively regressing code that presumably doesn't use this feature. Though it's probably using adjacent stuff.
