### PR TITLE
Re-implement a type-size based limit

### LINKED ISSUE #125460: `check_type_length_limit` is broken
The function was added to prevent hangs during codegen if there are infinite expansions which result in exponential blowup. It does that by computing an estimate of the complexity of the type and checking whether it's above a limit:

https://github.com/rust-lang/rust/blob/9c8a58fdb895204cb19eeb97472a78caa1c57c19/compiler/rustc_monomorphize/src/collector.rs#L632-L641

This worked quite well, until we changed the `walk` to use caching in https://github.com/rust-lang/rust/pull/72412. It looks like nobody noticed its effect on the type length limit in this PR.

With this the type length estimate grows linearly while the "true" size of the type is still exponential, causing the limit to never be reached in the cases it's intended for. The only remaining test which hits the limit arbitrarily sets it to `8` and uses a linearly recursive type:

https://github.com/rust-lang/rust/blob/9c8a58fdb895204cb19eeb97472a78caa1c57c19/tests/ui/type_length_limit.rs#L10-L30

### PR DESCRIPTION
**Pull request by compiler-errors**
r? lcnr

This PR reintroduces the type length limit added in #37789, which was accidentally made practically useless by the caching changes to `Ty::walk` in #72412, which caused the `walk` function to no longer walk over identical elements.

Hitting this length limit is not fatal unless we are in codegen -- so it shouldn't affect passes like the mir inliner which creates potentially very large types (which we observed, for example, when the new trait solver compiles `itertools` in `--release` mode).

This also increases the type length limit from `1048576 == 2 ** 20` to `2 ** 24`, which covers all of the code that can be reached with craterbot-check. Individual crates can increase the length limit further if desired.

Perf regression is mild and I think we should accept it -- reinstating this limit is important for the new trait solver and to make sure we don't accidentally hit more type-size related regressions in the future.

Fixes #125460

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot run mode=build-and-test

**Comment by lcnr** [comment]
want to try bumping the limit x10 and rerun crater?

**Comment by lcnr** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-125507/retry-regressed-list.txt p=1

**Comment by lcnr** [comment]
down to a single failure, I am in favor of landing this though, would also be open to first trying with 2x the size or sth :thinking: ideally we keep it as long as possible without breaking too many crates

Does this need a compiler/types FCP to fix this limit again? :thinking:

**Comment by compiler-errors** [comment]
Ok let's try 2^24 then

@bors try

File: compiler/rustc_const_eval/src/const_eval/machine.rs [hunk 1]
```diff
@@ -252,6 +252,7 @@ impl<'tcx> CompileTimeEvalContext<'tcx> {
                 ty::ParamEnv::reveal_all(),
                 const_def_id,
                 instance.args,
+                Some(self.find_closest_untracked_caller_location()),
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/machine.rs:255]: Why does resolving now need the caller_location...?

If it needs the call site span, it should use `self.cur_span()`.

Comment (compiler-errors) [reply compiler/rustc_const_eval/src/const_eval/machine.rs:255]: > Why does resolving now need the caller_location...?

So we can provide a relevant span if we hit type overflow.

> If it needs the call site span, it should use self.cur_span().

Thanks. There's basically no documentation for when to use either, other than "This is the fancy version of `cur_span`", lol.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/machine.rs:255]: find_closest_untracked_caller_location is specifically honoring `#[caller_location]` to show a span in the caller instead, walking up the call stack.

File: compiler/rustc_middle/src/ty/instance.rs [hunk 2]
```diff
@@ -489,25 +513,67 @@ impl<'tcx> Instance<'tcx> {
...
-        tcx.resolve_instance(tcx.erase_regions(param_env.and((def_id, args))))
+        tcx.resolve_instance_raw(tcx.erase_regions(param_env.and((def_id, args))))
     }
 
     pub fn expect_resolve(
         tcx: TyCtxt<'tcx>,
         param_env: ty::ParamEnv<'tcx>,
         def_id: DefId,
         args: GenericArgsRef<'tcx>,
+        span: Option<Span>,
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/instance.rs:541]: Maybe use just a `Span` and pass a `DUMMY_SP` directly at the call sites that use `None`?

File: compiler/rustc_const_eval/src/interpret/terminator.rs [hunk 3]
```diff
@@ -883,13 +883,12 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
                         ty::ExistentialTraitRef::erase_self_ty(tcx, virtual_trait_ref);
                     let concrete_trait_ref = existential_trait_ref.with_self_ty(tcx, dyn_ty);
 
-                    let concrete_method = Instance::resolve_for_vtable(
+                    let concrete_method = Instance::expect_resolve_for_vtable(
```
Comment (oli-obk) [inline compiler/rustc_const_eval/src/interpret/terminator.rs:886]: maybe also pass a span into this function?

File: compiler/rustc_monomorphize/src/collector.rs [hunk 4]
```diff
@@ -1544,6 +1492,7 @@ impl<'v> RootCollector<'_, 'v> {
             ty::ParamEnv::reveal_all(),
             start_def_id,
             self.tcx.mk_args(&[main_ret_ty.into()]),
+            None,
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:1495]: Using the def span of the start item should always point to the local crate, so it seems better than `None`/`DUMMY_SP`

File: compiler/rustc_monomorphize/src/collector.rs [hunk 5]
```diff
@@ -1614,7 +1563,7 @@ fn create_mono_items_for_default_impls<'tcx>(
         // As mentioned above, the method is legal to eagerly instantiate if it
         // only has lifetime generic parameters. This is validated by
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:1564]: hmm cut off comment (preexisting)

File: compiler/rustc_monomorphize/src/collector.rs [hunk 6]
```diff
@@ -1614,7 +1563,7 @@ fn create_mono_items_for_default_impls<'tcx>(
...
         let args = trait_ref.args.extend_to(tcx, method.def_id, only_region_params);
-        let instance = ty::Instance::expect_resolve(tcx, param_env, method.def_id, args);
+        let instance = ty::Instance::expect_resolve(tcx, param_env, method.def_id, args, None);
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:1566]: while a good span could be provided here, it's hard, leave a FIXME?

File: compiler/rustc_middle/src/ty/instance.rs [hunk 7]
```diff
@@ -498,25 +522,73 @@ impl<'tcx> Instance<'tcx> {
         def_id: DefId,
         args: GenericArgsRef<'tcx>,
     ) -> Result<Option<Instance<'tcx>>, ErrorGuaranteed> {
+        // Rust code can easily create exponentially-long types using only a
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/instance.rs:525]: maybe rename this fn to `try_resolve`? :thinking:

File: compiler/rustc_middle/src/ty/instance.rs [hunk 8]
```diff
@@ -661,13 +738,13 @@ impl<'tcx> Instance<'tcx> {
     pub fn resolve_drop_in_place(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> ty::Instance<'tcx> {
         let def_id = tcx.require_lang_item(LangItem::DropInPlace, None);
         let args = tcx.mk_args(&[ty.into()]);
-        Instance::expect_resolve(tcx, ty::ParamEnv::reveal_all(), def_id, args)
+        Instance::expect_resolve(tcx, ty::ParamEnv::reveal_all(), def_id, args, DUMMY_SP)
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/instance.rs:741]: idea: if the `ty` is a local adt, use its `def_span` here :thinking:

File: tests/ui/codegen/overflow-during-mono.rs [hunk 9]
```diff
@@ -1,5 +1,4 @@
 //@ build-fail
-//~^ ERROR overflow evaluating the requirement
```
Comment (lcnr) [inline tests/ui/codegen/overflow-during-mono.rs:2]:
```suggestion
//~^ ERROR reached the type-length limit while instantiating
```
so that we don't accidentally go back to getting overflow here

File: tests/ui/iterators/issue-58952-filter-type-length.rs [hunk 10]
```diff
@@ -1,5 +1,4 @@
-//@ run-pass
-//@ ignore-compare-mode-next-solver (hangs)
+//@ build-fail
```
Comment (lcnr) [inline tests/ui/iterators/issue-58952-filter-type-length.rs:2]: same here

**Review by lcnr — COMMENTED** [review]
r=me after nits

File: tests/ui/codegen/overflow-during-mono.rs (hunk 9 above)
Comment (compiler-errors) [reply tests/ui/codegen/overflow-during-mono.rs:3]: Can't do that -- it's not pointing to this crate. Added an `error-pattern` instead.

**Comment by compiler-errors** [comment]
Should be good to go. Renamed `Instance::resolve` -> `Instance::try_resolve`, tweaked the ADT drop shim span, and added some `//@ error-pattern` annotations to make up for error annotations that disappeared.

@bors r=lcnr rollup=never

**Comment by Kobzol** [comment]
Umm, this broke the [deeply-nested-multi](https://github.com/rust-lang/rustc-perf/blob/master/collector/compile-benchmarks/deeply-nested-multi/src/lib.rs) benchmark, and it also made the `itertools` crate 26x [slower to compile](https://perf.rust-lang.org/compare.html?start=2db4ff40af2b9f93b6240dbd67ed7f2f34b19776&end=c872a1418a4be3ea84a8d5232238b60d35339ba9&stat=instructions%3Au&tab=bootstrap) during bootstrap.

@compiler-errors Was this expected? We can fix the compile time benchmark if it's needed, but the `itertools` regression seems bad.

**Comment by compiler-errors** [comment]
I'm curious if we should add itertools to the perf suite lol

**Comment by Kobzol** [comment]
Well, we already had `deeply-nested-multi` as a regression test, and this PR broke it, but it wasn't noticed and the PR was merged anyway :sweat_smile:

I tried to manually fix the `deeply-nested-multi` benchmark by adjusting the type length limit to `469762043` (bumping it by 3) and benchmarking it against nightly:
image

**Comment by compiler-errors** [comment]
When was deeply-nested-multi added? Before or after the type length limit was effectively broken?

**Comment by lcnr** [comment]
Have an idea on how to fix perf. Requiring deeply-nested-multi to increase the type length limit seems fine to me 😁

**Comment by lcnr** [comment]
that's the idea, apparently the eu2 dev desktop is very laggy rn so I won't actually open a PR for this today. Will either do later this week or let someone else take it over:
```diff
diff --git a/compiler/rustc_middle/src/ty/instance.rs b/compiler/rustc_middle/src/ty/instance.rs
index ae54411d788..c1694ecd0a8 100644
--- a/compiler/rustc_middle/src/ty/instance.rs
+++ b/compiler/rustc_middle/src/ty/instance.rs
@@ -16,6 +16,7 @@
 use rustc_span::def_id::LOCAL_CRATE;
 use rustc_span::{Span, Symbol, DUMMY_SP};
 use tracing::{debug, instrument};
+use rustc_data_structures::fx::FxHashMap;
 
 use std::assert_matches::assert_matches;
 use std::fmt;
@@ -390,11 +391,23 @@ pub fn has_polymorphic_mir_body(&self) -> bool {
 fn type_length<'tcx>(item: impl TypeVisitable<TyCtxt<'tcx>>) -> usize {
     struct Visitor {
         type_length: usize,
+        cache: FxHashSet<Ty<'tcx>, usize>,
     }
     impl<'tcx> TypeVisitor<TyCtxt<'tcx>> for Visitor {
         fn visit_ty(&mut self, t: Ty<'tcx>) {
+            if let Some(&value) = self.cache.get(&t) {
+                self.type_length += value;
+            }
+
+            let prev = self.type_length;
             self.type_length += 1;
             t.super_visit_with(self);
+
+            // We don't try to use the cache if the type
+            // is fairly small.
+            if self.type_length > 16 {
+                self.cache.insert(t, self.type_length - prev);
+            }
         }
 
         fn visit_const(&mut self, ct: ty::Const<'tcx>) {
@@ -402,7 +415,7 @@ fn visit_const(&mut self, ct: ty::Const<'tcx>) {
             ct.super_visit_with(self);
         }
     }
-    let mut visitor = Visitor { type_length: 0 };
+    let mut visitor = Visitor { type_length: 0, cache: Default::default() };
     item.visit_with(&mut visitor);
 
     visitor.type_length
```

**Comment by Kobzol** [comment]
> When was deeply-nested-multi added? Before or after the type length limit was effectively broken?

The code that has the big regression is originally from the `deeply-nested-closures` benchmark, which was added [here](https://github.com/rust-lang/rustc-perf/pull/762) in 2020. It was actually added as a regression test for https://github.com/rust-lang/rust/pull/72412.

**Comment by compiler-errors** [comment]
That's so freaking funny because that is the PR that broke type length limits lmao

**Comment by compiler-errors** [comment]
So I agree w/ lcnr that the type length limit should be manually set on that test, because it was never valid in the first place.

**Comment by Kobzol** [comment]
I guess that the PR fixed the slow compilation issue by essentially removing type size limit checking xD And since this PR re-enabled it, it re-introduced the perf. regression.

**Comment by compiler-errors** [comment]
Yes. I think we should fix it the right way, with @lcnr's proposed caching. I'll put up a PR later today unless anyone else wants to.

**Comment by Kobzol** [comment]
Posted https://github.com/rust-lang/rustc-perf/pull/1935 to make the broken benchmark warning more visible and https://github.com/rust-lang/rustc-perf/pull/1936 to increase the type length limit.

**Comment by kornelski** [comment]
This has broken real-world code for me. Here's a minimized version:

```rust
use itertools::Itertools;

pub fn blah() {
    let _ = "".split("")
        .flat_map(|l| l.split(""))
        .flat_map(|l| l.split(""))
        .flat_map(|l| l.split(""))
        .flat_map(|l| l.split(""))
        .flat_map(|l| l.split(""))
        .flat_map(|l| l.split(""))
        .join("");
}
```

**Comment by lcnr** [comment]
- related to https://github.com/rust-itertools/itertools/pull/945

Itertools ends up with very large closure types, so this fels unsurprising and intended (as these large closures significantly degrade performance during canonicalization and can easily result in defacto hangs, especially with the new solver).

I hope you're able to patch the affected crate and increase its type length limit. Alternatively it may be worth it to patch itertools to outline the relevant closure here as well, similar to the PR mentioned aboe

**Comment by kornelski** [comment]
Ok, eventually it compiled, but I had to set max type length to **1GB** (this repo function is part of another iterator…)

<details><summary>super deep stack trace</summary>

```text
<hundreds omitted>
_RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector17collect_items_rec
_RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector17collect_items_rec
_RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector17collect_items_rec
 _RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector17collect_items_rec
  _RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector17collect_items_rec
   _RNvNtCs7ECJq7gLGVa_18rustc_monomorphize9collector25collect_items_of_instance
    _RNvXs0_NtCs7ECJq7gLGVa_18rustc_monomorphize9collectorNtB5_16MirUsedCollectorNtNtNtCs6voQ6brMM63_12rustc_middle3mir5visit7Visitor16visit_terminator
     _RNvMs2_NtNtCs6voQ6brMM63_12rustc_middle2ty8instanceNtB5_8Instance14expect_resolve
      _RNvMs2_NtNtCs6voQ6brMM63_12rustc_middle2ty8instanceNtB5_8Instance11try_resolve
       _RINvXsp_NtNtCs6voQ6brMM63_12rustc_middle2ty16structural_implsNtB8_2TyINtNtCscfpqVFAc5KA_13rustc_type_ir5visit18TypeSuperVisitableNtNtB8_7context6TyCtxtE16super_visit_withNtNvNtB8_8instance11type_length7VisitorEBa_
        _RINvXsp_NtNtCs6voQ6brMM63_12rustc_middle2ty16structural_implsNtB8_2TyINtNtCscfpqVFAc5KA_13rustc_type_ir5visit18TypeSuperVisitableNtNtB8_7context6TyCtxtE16super_visit_withNtNvNtB8_8instance11type_length7VisitorEBa_
         _RINvXsp_NtNtCs6voQ6brMM63_12rustc_middle2ty16structural_implsNtB8_2TyINtNtCscfpqVFAc5KA_13rustc_type_ir5visit18TypeSuperVisitableNtNtB8_7context6TyCtxtE16super_visit_withNtNvNtB8_8instance11type_length7VisitorEBa_
          _RINvXsp_NtNtCs6voQ6brMM63_12rustc_middle2ty16structural_implsNtB8_2TyINtNtCscfpqVFAc5KA_13rustc_type_ir5visit18TypeSuperVisitableNtNtB8_7context6TyCtxtE16super_visit_withNtNvNtB8_8instance11type_length7VisitorEBa_
           _RINvXsp_NtNtCs6voQ6brMM63_12rustc_middle2ty16structural_implsNtB8_2TyINtNtCscfpqVFAc5KA_13rustc_type_ir5visit18TypeSuperVisitableNtNtB8_7context6TyCtxtE16super_visit_withNtNvNtB8_8instance11type_length7VisitorEBa_
```

</details>

**Comment by saethlin** [comment]
The attribute required to make the code in https://github.com/rust-lang/rust/issues/127346 compile is quite silly.
```rust
#![type_length_limit = "30491060267835378"]
```
Given that value is just over 2 << 53, I think we might have a deeper problem here. The type length limit is stored in a `usize` which means computing that type length will overflow on a 32-bit system, and we are getting disturbingly close to overflowing a 64-bit integer in Real Code. Peak memory usage on my system from building this crate is 1.5 GB. Given that we have a type length which is _many_ factors of 2 beyond the memory usage of the entire compiler, does anyone think that indicates some kind of flaw in the reasoning that leads to the type length calculation? I've read over the code and it looks sensible to me; the only thing I can think of is that could produce this kind of blowup is many uses to the same interned `Ty`, but still... my intuition says that alone can't get us to 2 << 53.

Here's the implementation:
https://github.com/rust-lang/rust/blob/ed7e35f3494045fa1194be29085fa73e2d6dab40/compiler/rustc_middle/src/ty/instance.rs#L391-L422

Am I missing something obvious?

**Comment by jackh726** [comment]
This seems to be causing problems for people. We should consider reverting this as we assess the impact and correctness.

**Comment by RossSmyth** [comment]
The Helix editor no longer compiles on the latest nightly. I believe it is because of this PR

**Comment by Kobzol** [comment]
This PR heavily regressed a stress test that contains very deeply nested types, but this perf. regression has since been fixed in https://github.com/rust-lang/rust/pull/127288. Regarding the performance regression itself, I consider it to be resolved.

@rustbot label: +perf-regression-triaged

**Comment by Nilstrieb** [comment]
@saethlin having 53 nested 2-element tuples is enough to reach 2<<53. That's just 53 distinct types, which, thanks to caching, is easily processed by the rest of the compiler.
