### PR TITLE
Do not shallow resolve to root var while fudging

### LINKED ISSUE #153816: 1.95 beta regression: "expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`"
Regression found by the 1.95 beta crater run.

```
[INFO] [stdout] error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`
[INFO] [stdout]    --> overengineered_hkts/src/hkt/iter.rs:575:40
[INFO] [stdout]     |
[INFO] [stdout] 564 | /             <F as Functor<'t, ReqIn, ConstBool<false>, ReqF1>>::map(
[INFO] [stdout] 565 | |                 {
[INFO] [stdout] 566 | |                     let clone_b = clone_b.clone();
[INFO] [stdout] 567 | |                     move |vec: &Vec<<TInner as Hkt<'t>>::F<'a, B>>| {
[INFO] [stdout] ...   |
[INFO] [stdout] 575 | |                 ReqF1::create_from(&f, |vec: Vec<<TInner as Hkt<'t>>::F<'a, B>>| {
[INFO] [stdout]     | |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this closure implements `FnOnce`, not `Fn`
[INFO] [stdout] ...   |
[INFO] [stdout] 578 | |                 result,
[INFO] [stdout] 579 | |             )
[INFO] [stdout]     | |_____________- the requirement to implement `Fn` derives from here
[INFO] [stdout]     |
[INFO] [stdout] note: required by a bound in `traits::Functor::map`
[INFO] [stdout]    --> overengineered_hkts/src/hkt/traits.rs:310:20
[INFO] [stdout]     |
[INFO] [stdout] 299 |     fn map<'a, A, B, F1Once, F1Mut, F1Fn, F1Clone, F1Copy>(
[INFO] [stdout]     |        --- required by a bound in this associated function
[INFO] [stdout] ...
[INFO] [stdout] 310 |         F1Fn: 'a + Fn(A) -> B,
[INFO] [stdout]     |                    ^^^^^^^^^^ required by this bound in `Functor::map`
```

https://crater-reports.s3.amazonaws.com/beta-1.95-1/beta-2026-03-05/gh/ArsenalAlex108.overengineered_hkt/log.txt

### LINKED ISSUE #153849: 1.95 beta regression: "no method named `accept` found for struct..."
Regression found by the 1.95 beta crater run.

```
[INFO] [stdout] error[E0599]: no method named `accept` found for struct `Server<{closure@src/main.rs:31:77: 31:91}>` in the current scope
[INFO] [stdout]   --> src/main.rs:37:16
[INFO] [stdout]    |
[INFO] [stdout] 37 |         server.accept(&config.server.address)?;
[INFO] [stdout]    |                ^^^^^^ method not found in `Server<{closure@src/main.rs:31:77: 31:91}>`
[INFO] [stdout]    |
[INFO] [stdout]    = note: the method was found for
[INFO] [stdout]            - `Server<T, STACK_SIZE>`
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] For more information about this error, try `rustc --explain E0599`.
```

https://crater-reports.s3.amazonaws.com/beta-1.95-3/1.95.0-beta.3/reg/url-redirect-0.3.0/log.txt

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/153869)*

Fixes https://github.com/rust-lang/rust/issues/153816 and fixes https://github.com/rust-lang/rust/issues/153849

In https://github.com/rust-lang/rust/pull/151380, I thought that whether shallow resolve to root var or not wouldn't affect the actual type inferencing, but it isn't true for the fudge, in which we discard all newly created relationships between unresolved inference variables :sweat_smile:

r? lcnr

### CODE REVIEW

**Review by lcnr — COMMENTED** [review]
I dislike these changes to `shallow_resolve` as worry that it's easy for this to have unintended sideeffects/weirdness, e.g. it also affects canonicalization in the fudging scope.

My understanding of the two regressions is as follows:

tests/ui/coercion/fudge-inference/input-ty-higher-ranked-fn-trait.rs: We have the expectation `Server<?n>` and the ret type of the function `Server<?m>` with `n < m`. We have an `?m: Fn` obligation, so if we don't relate `?n` with `?m`, but have fudging return `?n`, we lose that knowledge

tests/ui/coercion/fudge-inference/input-ty-closure-param-fn-trait-bounds.rs: not actually minimal, this is enough
```rust
struct Inv<T, U>(*mut (T, U));
fn pass_through<F>(_: F) -> Inv<F, F> { todo!() }
fn map(_: Inv<impl FnOnce(), impl Fn()>) {}
pub fn traverse() {
    map(pass_through(|| ()))
}
```
We have the same issue on stable already, if we partially constrain `F` 
```rusT
struct Inv<T, U>(*mut (T, U));
fn pass_through<F>(_: F) -> Inv<F, F> { todo!() }
fn map(_: Inv<(impl FnOnce(),), (impl Fn(),)>) {}
pub fn traverse() {
    map(pass_through((|| (),)))
}
```

I don't get why we'd actually limit the closure to only impl `FnOnce` instead of properly inferring the closure kind as we do normally. That feels like a separate issue here, would be happy for you to look into what happens if we never eagerly infer the closure kind in `deduce_closure_signature` 

Could you instead add a `fn resolve_vars_for_fudging` which has this special behavior by just ignoring the output of `shallow_resolve` if its an infer var?

I really dislike this problem :x I feel like there should be a better way to handle this sort of thing, but can't think of anything right away

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153869/fd2649988fdc91e056ddd316865d33e812f48a0e..0068ef7c2c315c64d410c8edd8b097f8fe684cd9)*

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 1]
```diff
@@ -276,12 +276,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
                     // Record all the argument types, with the args
                     // produced from the above subtyping unification.
-                    Ok(Some(
-                        formal_input_tys
-                            .iter()
-                            .map(|&ty| self.resolve_vars_if_possible(ty))
-                            .collect(),
-                    ))
+                    Ok(Some(formal_input_tys.to_vec()))
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:279]: We don't need `resolve_var_if_possible` here as we already do it in `fudge_inference_if_ok`

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 2]
```diff
@@ -1879,7 +1879,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 if !ocx.try_evaluate_obligations().is_empty() {
                     return Err(TypeError::Mismatch);
                 }
-                Ok(self.resolve_vars_if_possible(adt_ty))
+                Ok(adt_ty)
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_typeck/src/expr.rs:1882]: Same here

File: compiler/rustc_infer/src/infer/mod.rs [hunk 3]
```diff
@@ -1250,6 +1250,33 @@ impl<'tcx> InferCtxt<'tcx> {
...
+    ///
+    /// However, there is an exceptional case: *fudging*. Fudging is intended
+    /// to guide inference rather than impose hard requirements. Because of
+    /// that, different type variables should not be implicitly unified through
+    /// a shared root variable unless they are fully resolved within the fudge
+    /// scope.
+    ///
+    /// To prevent such unintended unification, we use this function inside the
+    /// fudge instead of [`InferCtxt::resolve_vars_if_possible`].
+    pub fn resolve_vars_if_possible_for_fudging<T>(&self, value: T) -> T
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/mod.rs:1269]: I would slightly reword this comment to make clear that this is *jank* 

> Because of that, different type variables should not be implicitly unified through a shared root variable unless they are fully resolved within the fudge scope.

I think this is a slightly wrong framing 🤔 I would state something like "as currently equal inference variables may not be equal outside of the fudging scope, it is observable which inference variable we resolve to. We avoid resolving to the root var for backwards compatability here, see #153869."

File: compiler/rustc_infer/src/infer/resolve.rs [hunk 4]
```diff
@@ -43,6 +51,15 @@ impl<'a, 'tcx> TypeFolder<TyCtxt<'tcx>> for OpportunisticVarResolver<'a, 'tcx> {
         } else {
             let shallow = self.infcx.shallow_resolve(t);
             let res = shallow.super_fold_with(self);
+            let res = if self.for_fudging
+                && res.is_ty_or_numeric_infer()
+                // ty vars can be instantiated with int or float vars.
+                && !(t.is_ty_var() && !res.is_ty_var())
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/resolve.rs]: what exactly is that condition? 🤔

can this simply be `res.is_ty_var()`? I think resolving to different int or float vars shouldn't matter

**Review by lcnr — COMMENTED** [review]
r=me after nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153869/f125037ccddbeb162bce09213548314988da97a6..5c9595252342dc56ead6231f692b45df1a214603)*

File: compiler/rustc_infer/src/infer/resolve.rs (hunk 4 above)
Comment (ShoyuVanilla) [reply compiler/rustc_infer/src/infer/resolve.rs]: I got an ICE from the stdlib code that a ty var is instantiatedinto an int var. But yeah, just `res.is_ty_var()` should be enough

Comment (lcnr) [reply compiler/rustc_infer/src/infer/resolve.rs]: > I got an ICE from the stdlib code that a ty var is instantiatedinto an int var. But yeah, just res.is_ty_var() should be enough

what exactly do you mean?

Comment (ShoyuVanilla) [reply compiler/rustc_infer/src/infer/resolve.rs]: I mean, at the beginning, I used the above condition only, `res.is_ty_or_numeric_infer()` with the wrong belief that *Ty, Int, Float vars cannot be root vars*.
But that was wrong, as we can instantiate Ty vars with Int/Float vars and I realized it by an ICE in a stdlib code. So I ended up modifying the condition from *Any infer vars shouldn't be root vars, unless the var is resolved from Ty var to Int/Float var* but as you said, resolving to int or float vars shouldn't matter 😅

**Comment by panstromek** [comment]
perf triage:

Regression mostly outweigh improvements. Secondary regressions in `projection-caching` and `regression-31157` seem to just undo part of the wins from https://github.com/rust-lang/rust/pull/151380, so this still seems like a net improvement overall.

@rustbot label: +perf-regression-triaged
