### PR TITLE
Suggest copying trait associated type bounds on lifetime error

### LINKED ISSUE #92033: GAT defaults to where Self: 'a code breaking report
As suggested in #87479, I'm reporting a case where the required bound breaks code.

I was writing a 3D renderer and modeling the `surface` and `swapchain` concepts using traits.

A `Surface` is something you can render to, it should produce a iterator of references to `Texture`s:

```rust
struct Texture;

trait Surface {
    type TextureIter<'a>: Iterator<Item = &'a Texture>;

    fn get_texture(&self) -> Self::TextureIter<'_>;
}
```

A `Swapchain` produces a reference to a `Surface`:

```rust
trait Swapchain {
    type Surface<'a>: Surface;

    fn get_surface(&self) -> Self::Surface<'_>;
}
```

Now a `Texture` itself can be used as a swapchain, producing reference to itself as the `Surface`.

```rust
impl<'s> Surface for &'s Texture {
    type TextureIter<'a> = std::option::IntoIter<&'a Texture>;

    fn get_texture(&self) -> Self::TextureIter<'_> {
        let option: Option<&Texture> = Some(self);
        option.into_iter()
    }
}

impl Swapchain for Texture {
    type Surface<'a> = &'a Texture;

    fn get_surface(&self) -> Self::Surface<'_> {
        self
    }
}
```

Above code compiles under `rustc 1.58.0-nightly (0d1754e8b 2021-11-05)`.

Now it doesn't with added `where Self: 'a` bound.

This is a simplified example as `Surface` and `Swapchain` have other required methods.

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (efec54529 2021-12-04
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
error[E0477]: the type `&'s Texture` does not fulfill the required lifetime
  --> src/main.rs:18:5
   |
18 |     type TextureIter<'a> = std::option::IntoIter<&'a Texture>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: type must outlive the lifetime `'a` as defined here
  --> src/main.rs:18:22
   |
18 |     type TextureIter<'a> = std::option::IntoIter<&'a Texture>;
   |                      ^^

For more information about this error, try `rustc --explain E0477`.
error: could not compile `rsplayground` due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jackh726**
Closes #92033

Kind of the most simple suggestion to make - we don't try to be fancy. Turns out, it's still pretty useful (the couple existing tests that trigger this error end up fixed - for this error - upon applying the fix).

r? @estebank 
cc @nikomatsakis

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/mod.rs [hunk 1]
```diff
@@ -64,7 +64,7 @@ impl<'cx, 'tcx> NiceRegionError<'cx, 'tcx> {
             .or_else(|| self.try_report_mismatched_static_lifetime())
     }
 
-    pub fn regions(&self) -> Option<(Span, ty::Region<'tcx>, ty::Region<'tcx>)> {
+    pub(super) fn regions(&self) -> Option<(Span, ty::Region<'tcx>, ty::Region<'tcx>)> {
```
Comment (jackh726) [inline compiler/rustc_infer/src/infer/error_reporting/nice_region_error/mod.rs:67]: Drive by change.

File: compiler/rustc_typeck/src/check/wfcheck.rs [hunk 2]
```diff
@@ -528,9 +528,7 @@ fn ty_known_to_outlive<'tcx>(
         let sup_type = ty;
         let sub_region = region;
 
-        let origin = SubregionOrigin::from_obligation_cause(&cause, || {
-            infer::RelateParamBound(cause.span, sup_type, None)
-        });
+        let origin = infer::RelateRegionParamBound(cause.span);
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/wfcheck.rs:531]: This and the one below are drive-by changes. These shouldn't ever be displayed anyways. But wanted to stop using `from_obligation_cause` (was potentially going a different direction for this PR).

File: src/test/ui/generic-associated-types/issue-88595.rs [hunk 3]
```diff
@@ -8,7 +8,7 @@ trait A<'a> {
     // FIXME(generic_associated_types): Remove one of the below bounds
     // https://github.com/rust-lang/rust/pull/90678#discussion_r744976085
     where
-        'a: 'b, Self: 'a, Self: 'b;
```
Comment (jackh726) [inline src/test/ui/generic-associated-types/issue-88595.rs:11]: This bound was required because of a bug that has since been fixed. FIXME still stands for the two remaining though.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me but I'll let @estebank do a review if he wants to

**Comment by estebank** [comment]
r=me after fixing rebase
