### PR TITLE
don't let rustdoc get confused by text "fn main" in a line comment

### LINKED ISSUE #21299: `fn main` in a comment in rustdoc breaks tests
$ cat confuse.md
    ```rust
    // pub fn mai
    ```
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... ok
    
    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
    
    $ sed -i 's/mai/main/' confuse.md
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... FAILED
    
    failures:
    
    ---- _0 stdout ----
            error: main function not found
    error: aborting due to previous error
    thread '_0' panicked at 'Box<Any>', /home/aidanhs/Desktop/rust/rust/src/libsyntax/diagnostic.rs:144
    
    
    
    failures:
        _0
    
    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
    
    thread '<unnamed>' panicked at 'Some tests failed', /home/aidanhs/Desktop/rust/rust/src/libtest/lib.rs:265
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/aidanhs/Desktop/rust/rust/src/libcore/result.rs:746

Per http://doc.rust-lang.org/rustdoc.html, "Given a code block, if it does not contain fn main, it is wrapped in fn main() { your_code }"

Can it not be "does not contain 'fn main (' outside of a comment"?

### PR DESCRIPTION
**Pull request by zackmdavis**
~~~Resolves~~~ (edited) partially addresses #21299.

![rustdoc_fn_main](https://user-images.githubusercontent.com/1076988/30630993-9aeecc4a-9d97-11e7-8e56-2b973f23f683.png)

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/test.rs [hunk 1]
```diff
@@ -348,7 +348,19 @@ pub fn make_test(s: &str,
...
+    let already_has_main = s.lines()
+        .map(|line| {
+            let comment = line.find("//");
+            if let Some(comment_begins) = comment {
+                &line[0..comment_begins]
+            } else {
+                line
+            }
+        })
+        .find(|code| code.contains("fn main")).is_some();
```
Comment (QuietMisdreavus) [inline src/librustdoc/test.rs]: Could you make this line `.any(|code| code.contains("fn main"))` instead? That's equivalent and removes one level of method chaining.

**Review by QuietMisdreavus — COMMENTED** [review]
Thanks so much, i love it! Just one little nit and this should be good to go!

File: src/librustdoc/test.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/test.rs]: This is indeed a great improvement. I just have a concern on this (or the previous check):

Imagine you wrote "fn    main" (for some reasons...). Or if you write "fn main" in a string (for some other reasons...).

Comment (QuietMisdreavus) [reply src/librustdoc/test.rs]: True, this isn't a "complete" fix, but it's still a start. A "proper" fix would involve throwing libsyntax or the like at the doctest and scanning that for a function called "main". But for now, this is much better than we have at the moment.

Comment (GuillaumeGomez) [reply src/librustdoc/test.rs]: I am thinking about a partial fix involving a stupid parser creating basic tokens and all. But still bigger than this.

Comment (Mark-Simulacrum) [reply src/librustdoc/test.rs]: I would prefer that rustdoc instead gain something like allowing `lib` where we have `rust` (i.e., in the language part after "```") today. The more work we do for the "common case" the worse rustdoc's performance on codebases with large amounts of doc tests gets.

Comment (GuillaumeGomez) [reply src/librustdoc/test.rs]: Agreed. There's no ideal solution in here.

**Comment by zackmdavis** [comment]
Force-push addresses @QuietMisdreavus's `find`/`any` comment. I regret that the Actual Parsing that would be required to fix similar edge-cases is out of scope for this pull request.

**Comment by QuietMisdreavus** [comment]
Sorry for letting this get stale! To get this put in, i won't force you to wrangle libsyntax to do Actual Parsing. I'll go ahead and accept this PR, but i want to leave https://github.com/rust-lang/rust/issues/21299 open so we can track a Proper Solution for it.

To that end, can you add a comment "`FIXME(#21299): Replace this with libsyntax-based check`" to the change?

**Comment by zackmdavis** [comment]
(updated)

**Comment by QuietMisdreavus** [comment]
@bors r+

Thanks so much! Sorry about the delay!
