### PR TITLE
MGCA: Support for tuple constructors 

### LINKED ISSUE #136379: ICE: `invalid Res for const path`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --crate-type=lib
#![feature(min_generic_const_args)]
mod m {
    pub struct Uuid(());

    impl Uuid {
        pub fn encode_buffer() -> [u8; Uuid] {
            []
        }
    }
}

````

original:
````rust
mod m {
    pub struct Uuid(());

    impl Uuid {
        pub fn encode_buffer() -> [u8; Uuid] {
            []
        }
    }
    const LENGTH: usize = 0;
}

pub use m::Uuid;

````

Version information
````
rustc 1.86.0-nightly (9e48dfe5e 2025-02-01)
binary: rustc
commit-hash: 9e48dfe5e0d5ec1b064b5d25504948ede0ec9b53
commit-date: 2025-02-01
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(min_generic_const_args) --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(min_generic_const_args)
  |         ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: struct `Uuid` is never constructed
 --> /tmp/icemaker_global_tempdir.pnE6EpSQ5yN3/rustc_testrunner_tmpdir_reporting.8KFeOkEvN674/mvce.rs:2:16
  |
2 |     pub struct Uuid(());
  |                ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: associated function `encode_buffer` is never used
 --> /tmp/icemaker_global_tempdir.pnE6EpSQ5yN3/rustc_testrunner_tmpdir_reporting.8KFeOkEvN674/mvce.rs:5:16
  |
4 |     impl Uuid {
  |     --------- associated function in this implementation
5 |         pub fn encode_buffer() -> [u8; Uuid] {
  |                ^^^^^^^^^^^^^

warning: 3 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: invalid Res for const path
 --> /tmp/icemaker_global_tempdir.pnE6EpSQ5yN3/rustc_testrunner_tmpdir_reporting.8KFeOkEvN674/mvce.rs:5:40
  |
5 |         pub fn encode_buffer() -> [u8; Uuid] {
  |                                        ^^^^
  |
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2202:27
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
         4: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg.cold
         5: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
         6: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
         7: rustc_hir_analysis::collect::lower_fn_sig_recovering_infer_ret_ty
         8: rustc_hir_analysis::collect::fn_sig
         9: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        10: <rustc_query_impl::query_impl::fn_sig::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        12: rustc_query_impl::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
        13: <rustc_hir_analysis::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item
        14: rustc_hir_analysis::check::wfcheck::check_well_formed
        15: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        17: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
        18: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        19: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        21: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        22: rustc_hir_analysis::check_crate
        23: rustc_interface::passes::run_required_analyses
        24: rustc_interface::passes::analysis
        25: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        27: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        28: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        29: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        30: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        31: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        32: std::sys::pal::unix::thread::Thread::new::thread_start
        33: <unknown>
        34: <unknown>
 --> /tmp/icemaker_global_tempdir.pnE6EpSQ5yN3/rustc_testrunner_tmpdir_reporting.8KFeOkEvN674/mvce.rs:5:40
  |
5 |         pub fn encode_buffer() -> [u8; Uuid] {
  |                                        ^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (9e48dfe5e 2025-02-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(min_generic_const_args) --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-min_generic_const_args

### LINKED ISSUE #138132: ICE: `invalid Res Def  .. for const path`
### Code

```Rust
#![feature(min_generic_const_args)]
struct b(Box<[u8; c]>);
impl b {
    fn d(self) {
        self.0.e()
    }
}
struct c<'a>(&'a u8);
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (e6af292f9 2025-03-06)
binary: rustc
commit-hash: e6af292f91f21f12ac1aab6825efb7e1e3381cbb
commit-date: 2025-03-06
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: invalid Res Def(Ctor(Struct, Fn), DefId(0:10 ~ code[1fb7]::c::{constructor#0})) for const path
 --> code.rs:2:19
  |
2 | struct b(Box<[u8; c]>);
  |                   ^
  |
note: delayed at compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2457:28
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         4: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
         5: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
         6: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_path
         7: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_ty
         8: rustc_hir_analysis::collect::type_of::type_of
         9: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        11: rustc_query_impl::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
        12: rustc_hir_analysis::outlives::inferred_outlives_crate
        13: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::inferred_outlives_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::inferred_outlives_crate::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::inferred_outlives_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        17: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        18: rustc_query_impl::query_impl::inferred_outlives_of::get_query_non_incr::__rust_end_short_backtrace
        19: rustc_hir_analysis::collect::predicates_of::predicates_of
        20: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 24]>>
        21: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        22: rustc_query_impl::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
        23: <rustc_hir_analysis::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
        24: rustc_hir_analysis::check::wfcheck::check_well_formed
        25: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        27: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
        28: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        29: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        30: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        31: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        32: rustc_hir_analysis::check_crate
        33: rustc_interface::passes::run_required_analyses
        34: rustc_interface::passes::analysis
        35: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        36: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        37: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        38: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        39: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        40: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        41: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        42: std::sys::pal::unix::thread::Thread::new::thread_start
        43: <unknown>
        44: <unknown>
 --> code.rs:2:19
  |
2 | struct b(Box<[u8; c]>);
  |                   ^

error: internal compiler error: no type-dependent def for method call
 --> code.rs:5:9
  |
5 |         self.0.e()
  |         ^^^^^^^^^^
  |
note: delayed at compiler/rustc_privacy/src/lib.rs:1237:26
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_privacy::TypePrivacyVisitor as rustc_hir::intravisit::Visitor>::visit_expr
         4: <rustc_privacy::TypePrivacyVisitor as rustc_hir::intravisit::Visitor>::visit_expr
         5: rustc_privacy::check_mod_privacy
         6: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_privacy::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
         7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
         8: rustc_query_impl::query_impl::check_mod_privacy::get_query_non_incr::__rust_end_short_backtrace
         9: rustc_interface::passes::analysis
        10: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        12: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        13: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        14: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        15: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        16: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        17: std::sys::pal::unix::thread::Thread::new::thread_start
        18: <unknown>
        19: <unknown>
 --> code.rs:5:9
  |
5 |         self.0.e()
  |         ^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/matthias/vcs/github/CRED/rustc-ice-2025-03-06T22_06_08-2195216.txt` to your bug report

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #150610: MGCA: support tuple constructor calls as a direct const argument
We currently support `Enum::Variant { field: N }` and `Struct { field: N }` as const arguments under `min_generic_const_args`. We should also support `Enum::Variant(N)` and `Struct(N)` syntax. 

```rust
#![feature(min_generic_const_args, adt_const_params)]

#[derive(Eq, PartialEq, core::marker::ConstParamTy)]
enum Option<T> {
    Some(T),
    None,
}

fn takes_option<const O: Option<u32>() {}

fn generic_caller<const N: u32>() {
    takes_option::<{ Option::<u32>::Some(N) }>();
    takes_option::<{ <Option<u32>>::Some(N) }>();
}
```

These should lower directly to a `ConstKind::Value` in HIR ty lowering

### PR DESCRIPTION
**Pull request by Kivooeo**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/150603)*

r? BoxyUwU

part of https://github.com/rust-lang/rust/issues/132980

fixes rust-lang/rust#136379
fixes rust-lang/rust#138132

fixes https://github.com/rust-lang/rust/issues/150610

this does not make const constructor like None works, just something like Some(n) 

todo: 
* ~~tests~~
* write a better description (not sure if needed)
* add more comments and FIXMEs from structs code

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2266,12 +2269,101 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        let non_adt_or_variant_res = || {
+            let e = tcx.dcx().span_err(span, "tuple constructor with invalid base path");
+            ty::Const::new_error(tcx, e)
+        };
+
+        let (ty, variant_did) = match qpath {
+            hir::QPath::Resolved(maybe_qself, path) => {
+                let opt_self_ty = maybe_qself.as_ref().map(|qself| self.lower_ty(qself));
+                let ty =
+                    self.lower_resolved_ty_path(opt_self_ty, path, hir_id, PermitVariants::Yes);
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: we would want to use `lower_resolved_const_path` here

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -2266,12 +2269,101 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                    Res::Def(DefKind::Ctor(CtorOf::Variant | CtorOf::Struct, _), ctor_did) => {
+                        tcx.parent(ctor_did)
+                    }
+                    _ => return non_adt_or_variant_res(),
+                };
+                (ty, variant_did)
+            }
+            hir::QPath::TypeRelative(hir_self_ty, segment) => {
+                let self_ty = self.lower_ty(hir_self_ty);
+                let opt_res = self.lower_type_relative_ty_path(
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: and `lower_type_relative_const_path` here

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 3]
```diff
@@ -1976,21 +1976,24 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+            Res::Def(kind, did)
+                if let DefKind::Enum
                 | DefKind::TyAlias
                 | DefKind::Struct
                 | DefKind::Union
-                | DefKind::ForeignTy,
-                did,
-            ) => {
+                | DefKind::ForeignTy
+                | DefKind::Ctor(CtorOf::Struct, _) = kind =>
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: we don't want type path lowering to give us value namespace stuff, shouldn't have to change this function

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 4]
```diff
@@ -2266,12 +2269,101 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+            ty::Const::new_error(tcx, e)
+        };
+
+        let (ty, variant_did) = match qpath {
+            hir::QPath::Resolved(maybe_qself, path) => {
+                let opt_self_ty = maybe_qself.as_ref().map(|qself| self.lower_ty(qself));
+                let ty =
+                    self.lower_resolved_ty_path(opt_self_ty, path, hir_id, PermitVariants::Yes);
+                let variant_did = match path.res {
+                    Res::Def(DefKind::Variant | DefKind::Struct, did) => did,
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: If we're using the `const_path` functions then we shouldn't have to deal with `Variant` resolutions, we should just get back resolutions involving the `Ctor`. I'm not entirely sure if `resolve_type_relative_path`  actually handles resolving to `Ctor`s right now but if it doesn't that should be updated

File: compiler/rustc_trait_selection/src/traits/normalize.rs [hunk 5]
```diff
@@ -461,7 +461,7 @@ impl<'a, 'b, 'tcx> TypeFolder<TyCtxt<'tcx>> for AssocTypeNormalizer<'a, 'b, 'tcx
                 ),
             },
             DefKind::Const => self.normalize_free_alias(uv.into()).expect_const(),
-            DefKind::AnonConst => {
+            DefKind::AnonConst | DefKind::Ctor(..) => {
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/normalize.rs]: this doesnt seem right. tuple constructors cant be evaluated with `evaluate_const`.

I think this change shouldn't be necessary for your PR. We lower tuple constructor calls to `ConstKind::Value` so we shouldn't be winding up with new cases of `ConstKind::Unevaluated` with this `DefKind`. What was the reason for making this change?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 1 above)
Comment (Kivooeo) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: it's a bit unclear to me on how to use it here, two questions

1) this function returns a const, but im creating a const myself, do you mean to not create const but use a const that was returned by this function?

2) this function explicitly rejecting `DefKind::Ctor(CtorOf::Variant | CtorOf::Struct, CtorKind::Fn)`, should i adjust this function or something?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 2 above)
Comment (Kivooeo) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: looking at this function i dont feel like its ready to be used for this

```rust
            TypeRelativePath::Variant { .. } => {
                span_bug!(span, "unexpected variant res for type associated const path")
            }
```

Comment (Kivooeo) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: maybe i can fix it, but need some time

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I don't think we actually want to resolve to variants here. We want to resolve to the Ctor

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: The lowered const here would represent the value of the function item being called- not the const const representing the full tuple constructor call. I think what you need to do is:
- Update `lower_resolved_const_path` to lower CtorKind::Fn's to ZST `ConstKind::Value`s with a type of `FnDef`
- You'll want to do a similar thing for `lower_type_relative_const_Path`. Possibly also returning a `DefKind` and `DefId` from that function like `lower_type_relative_ty_path` does, though I'm not sure if that is necessary or not.

Then instead of looking for `DefKind::Variant` and `DefKind::Struct` resolutions (which can't occur from these `_const_path` functions) you should be checking for `DefKind::Ctor(_, CtorKind::Fn)`.

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: It's important not to be using or changing `lower_resolved_ty_path` as that's logic for resolving stuff in the type namespace not the value namespace (where constructors are). With your current changes the logic for lowering type paths will now be able to resolve to constructors which is wrong.

The struct expression logic uses the ty path logic because we are actually resolving to a type (which struct or enum we're constructing). But for tuple constructor calls we're resolving to a value which is then called

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 6]
```diff
@@ -2349,12 +2289,106 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        };
+
+        let ctor_const = match qpath {
+            hir::QPath::Resolved(maybe_qself, path) => {
+                let opt_self_ty = maybe_qself.as_ref().map(|qself| self.lower_ty(qself));
+                self.lower_resolved_const_path(opt_self_ty, path, hir_id)
+            }
+            hir::QPath::TypeRelative(hir_self_ty, segment) => {
+                let self_ty = self.lower_ty(hir_self_ty);
+                match self.lower_type_relative_const_path(
```
Comment (Kivooeo) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2324]: does that fine to use `lower_ty` here?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 7]
```diff
@@ -2349,12 +2289,106 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                ) {
+                    Ok(c) => c,
+                    Err(_) => return non_adt_or_variant_res(),
+                }
+            }
+        };
+
+        let Some(value) = ctor_const.try_to_value() else {
+            return non_adt_or_variant_res();
+        };
```
Comment (Kivooeo) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2339]: not sure if the `ctor_const` is always `Value` at this point, so I decided to put this sanity check here

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 8]
```diff
@@ -314,6 +314,7 @@ pub enum PermitVariants {
 enum TypeRelativePath<'tcx> {
     AssocItem(DefId, GenericArgsRef<'tcx>),
     Variant { adt: Ty<'tcx>, variant_did: DefId },
+    Ctor { ctor_def_id: DefId, args: GenericArgsRef<'tcx> },
```
Comment (Kivooeo) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:317]: not sure if you meant this by resolving to ctor and not variant, hope its correct

**Review by Kivooeo — COMMENTED** [review]
the ci will fail, it's excepted, the reason is because there two fixed ICEs in crashes

```
    [crashes] tests/crashes/136379.rs
    [crashes] tests/crashes/138132.rs
```

they seems very irrelevant so i decided not to put them out from this directory

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150603/4c3310a6db02750ff0cfd0def09dd05c5942d723..cdcbdffb3c53221f5d903ca4e82e8cdff31b9b3d)*

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 9]
```diff
@@ -1326,6 +1334,21 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                     .iter()
                     .find(|vd| tcx.hygienic_eq(segment.ident, vd.ident(tcx), adt_def.did()));
                 if let Some(variant_def) = variant_def {
+                    if matches!(mode, LowerTypeRelativePathMode::Const)
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:1339]:
```suggestion
                    // FIXME(mgca): do we want constructor resolutions to take priority over
                    // other possible resolutions?
                    if matches!(mode, LowerTypeRelativePathMode::Const)
```

File: tests/ui/const-generics/mgca/tuple_ctor_erroneous.rs [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+
+fn test_errors() {
+    accepts_point::<{ Point(const { 1 }) }>();
+    //~^ ERROR tuple constructor has 2 arguments but 1 were provided
+
+    accepts_point::<{ Point(const { 1 }, const { 2 }, const { 3 }) }>();
+    //~^ ERROR tuple constructor has 2 arguments but 3 were provided
+
+    accepts_point::<{ Pointt(const { 1 }, const { 2 }) }>();
+    //~^ ERROR cannot find function, tuple struct or tuple variant `Pointt` in this scope
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/tuple_ctor_erroneous.rs]:
```suggestion
    accepts_point::<{ UnresolvedIdent(const { 1 }, const { 2 }) }>();
    //~^ ERROR cannot find function, tuple struct or tuple variant `UnresolvedIdent` in this scope
```

File: tests/ui/const-generics/mgca/tuple_ctor_arg_simple.rs [hunk 11]
```diff
@@ -0,0 +1,42 @@
+//@ check-pass
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/tuple_ctor_arg_simple.rs]:
```suggestion
//@ run-pass
```

check pass wont actually run your `fn main`

File: tests/ui/const-generics/mgca/tuple_ctor_complex_args.rs [hunk 12]
```diff
@@ -0,0 +1,26 @@
...
+
+fn with_point<const P: Point>() {}
+
+trait Trait {
+    #[type_const]
+    const ASSOC: u32;
+}
+
+fn test<T: Trait, const N: u32>() {
+    with_point::<{ Point(<T as Trait>::ASSOC, N) }>();
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/tuple_ctor_complex_args.rs]: as this case works can you move it into `tuple_ctor_arg_simple`

File: tests/ui/const-generics/mgca/tuple_ctor_nested.rs [hunk 13]
```diff
@@ -0,0 +1,38 @@
+//@ check-pass
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/tuple_ctor_nested.rs]:
```suggestion
//@ run-pass
```

File: tests/ui/const-generics/mgca/tuple_ctor_type_relative.rs [hunk 14]
```diff
@@ -0,0 +1,26 @@
+//@ check-pass
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/tuple_ctor_type_relative.rs]:
```suggestion
//@ run-pass
```

**Review by BoxyUwU — COMMENTED** [review]
Looks good!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150603/4c3310a6db02750ff0cfd0def09dd05c5942d723..cdcbdffb3c53221f5d903ca4e82e8cdff31b9b3d)*

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 8 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:317]: Yep that's perfect

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 7 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2339]: In theory you should be able to get non-value's here if people wrote erroneous code like `Foo<{ CONST_ITEM(N) }>`. Can you add that as a test to `tests/ui/const-generics/mgca/tuple_ctor_erroneous.rs`?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 6 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2324]: yep that's totally fine

**Comment by Kivooeo** [comment]
hm, weird because locally it's fine

**Comment by Kivooeo** [comment]
oh wow ci passed

i will take a look for const constructor a bit later, there shouldn't be much work, like basically update `lower_type_relative_const_path` and `lower_resolved_const_path`

**Review by BoxyUwU — APPROVED** [review]
thx for working on this. very cool! 

@bors r+ rollup=never

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150603/f8b1d59a81c700cb7aa25cf69e3032b3ce333150..05afcb6d26567d481119c8f6f4a58ccce225f224)*

**Comment by Kobzol** [comment]
The regressions are only on a few secondary stress tests and they are tiny, I don't think it's worth digging further.

@rustbot label: +perf-regression-triaged
