### PR TITLE
Reopen standard file descriptors when they are missing on Unix

### LINKED ISSUE #46981: 'rustc' panicked at 'failed to acquire jobserver token: ...'
This seems to be related to #42867, though not entirely the same.

I am in the process of `cargo publish`ing my crate (multiple crates in a workspace project) [imag](https://github.com/matthiasbeyer/imag) v0.5.0 (from [this commit](https://github.com/matthiasbeyer/imag/commit/c2af6c9ebe6526bc42ca0652fe9ba414c509dd11)).

Instead of a normal compile process, I got this:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0 (f3d6973f4 2017-08-27) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'failed to acquire jobserver token: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:860:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_new
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: rustc_trans::back::write::execute_work
  11: rustc_trans::back::write::run_passes
  12: rustc_driver::driver::phase_5_run_llvm_passes
  13: rustc_driver::driver::compile_input
  14: rustc_driver::run_compiler

error: Could not compile `serde_derive_internals`.
warning: build failed, waiting for other jobs to finish...
error: failed to verify package tarball

Caused by:
  build failed
```

`rustc --version --verbose`:

```
rustc 1.20.0 (f3d6973f4 2017-08-27)
binary: rustc
commit-hash: f3d6973f41a7d1fb83029c9c0ceaf0f5d4fd7208
commit-date: 2017-08-27
host: x86_64-unknown-linux-gnu
release: 1.20.0
LLVM version: 4.0
```

### LINKED ISSUE #57728: Rust programs started with closed stdio streams may corrupt files|sockets|etc
For example, if a program is started with `./foo >&-` (stdout closed, stdin and stderr open), `println!()`s fail silently (despite `strace` showing that `write(2)` clearly returns `-1` and `EBADF`). If a file is opened and _then_ a `println!()` is attempted, it silently writes into the file (which is probably not what was intended).

Example 1:
```rust
fn main() {
    println!("Hello, world!");
}
```
Invocation: `target/debug/hello-world >&-`
Expected result: panic, with an error message relating to being unable to write to stdout, exit code 101
Observed result: nothing (no output on stderr, exit code 0)

Example 2:
```rust
fn main() {
    let file = std::fs::File::create("foo").unwrap();
    println!("Hello, world!");
    drop(file);
}
```
Invocation: `target/debug/hello-file >&-`
Expected result: panic (as before), empty file `./foo`
Observed result: no panic, `./foo` contains `Hello, world!`

Rust version: 1.30.0
Platform: x86_64-unknown-linux-gnu

It looks like any Rust program which is started with one or more closed stdio streams, opens a file (or socket, or…), and subsequently tries to read|write said stdio stream will inadvertently read|write the file instead (messing up the seek position, not to mention causing data corruption). This seems like terribly bad behavior. ;-;

### LINKED ISSUE #60447: Cargo build ICE when run with closed STDIN
**How to reproduce**
```bash
cargo new any_project
cd any_project
cargo build <&-
# the &- syntax (valid in bash and zsh AFAIK)
# tells your shell to fork cargo with STDIN *closed*
```
**Actual Result**
```
thread '<unnamed>' panicked at 'failed to acquire jobserver token: early EOF on jobserver pipe', error: failed to acquire jobserver token: early EOF on jobserver pipe
src/librustc_codegen_ssa/back/write.rs:1406:29

note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

error: Could not compile `any_project`.

To learn more, run the command again with --verbose.
```

**Actual Result with full backtrace**
```
thread '<unnamed>' panicked at 'failed to acquire jobserver token: early EOF on jobserver pipe', src/librustc_codegen_ssa/back/write.rs:1406:29
error: failed to acquire jobserver token: early EOF on jobserver pipe

stack backtrace:
   0:     0x7fa5eca1ce63 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hc7b76c57e25c7d91
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7fa5eca1556b - std::sys_common::backtrace::_print::h203699a8f1b8b948
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x7fa5eca190c6 - std::panicking::default_hook::{{closure}}::h74fcb67c61dc8b92
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x7fa5eca18e44 - std::panicking::default_hook::hb2e06978a2102930
                               at src/libstd/panicking.rs:215
   4:     0x7fa5e8bb03df - rustc::util::common::panic_hook::h9fd4a470400ba35c
   5:     0x7fa5eca198b8 - std::panicking::rust_panic_with_hook::h4ac0b487eb7e54da
                               at src/libstd/panicking.rs:482
   6:     0x7fa5eca19351 - std::panicking::continue_panic_fmt::h23ca3ed77b25f368
                               at src/libstd/panicking.rs:385
   7:     0x7fa5eca1929e - std::panicking::begin_panic_fmt::he14137966dec33cc
                               at src/libstd/panicking.rs:340
   8:     0x7fa5e310477b - std::sys_common::backtrace::__rust_begin_short_backtrace::h6be5ab22ff539cca
   9:     0x7fa5e3146cad - std::panicking::try::do_call::hb93197db26b32ea9
  10:     0x7fa5eca2ab29 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  11:     0x7fa5e31105f8 - <F as alloc::boxed::FnBox<A>>::call_box::haaff0e1f36b63d07
  12:     0x7fa5eca2986d - std::sys::unix::thread::Thread::new::thread_start::h7fc2d82a3b91bc88
                               at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:759
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  13:     0x7fa5ec960a91 - start_thread
  14:     0x7fa5ec87fcd2 - __clone
  15:                0x0 - <unknown>
query stack during panic:
end of query stack
error: aborting due to previous error

error: Could not compile `any_project`.

To learn more, run the command again with --verbose.

```
**rustc --version --verbose**
```
rustc 1.34.1 (fc50f328b 2019-04-24)
binary: rustc
commit-hash: fc50f328b0353b285421b8ff5d4100966387a997
commit-date: 2019-04-24
host: x86_64-unknown-linux-gnu
release: 1.34.1
LLVM version: 8.0
```

**Expected result**
```
   Compiling any_project v0.1.0 (/tmp/any_project)
   Finished dev [unoptimized + debuginfo] target(s) in 0.33s
```

**Additional details**
Please note that the issue will go away once you succeed in building the project (probably thanks due to some compiler caching, sorry, not sure here).
A `touch` is enough to get the error back :)
```bash
touch src/main.rs
```
Thank you.

### PR DESCRIPTION
**Pull request by tmiasko**
The syscalls returning a new file descriptors generally return lowest-numbered
file descriptor not currently opened, without any exceptions for those
corresponding to stdin, sdout, or stderr.

Previously when any of standard file descriptors has been closed before starting
the application, operations on std::io::{stderr,stdin,stdout} were likely to
either succeed while being performed on unrelated file descriptor, or fail with
EBADF which is silently ignored.

Avoid the issue by using /dev/null as a replacement when the standard file
descriptors are missing.

The implementation is based on the one found in musl. It was selected among a
few others on the basis of the lowest overhead in the case when all descriptors
are already present (measured on GNU/Linux).

Closes #57728.
Closes #46981.
Closes #60447.

Benefits:
* Makes applications robust in the absence of standard file descriptors.
* Upholds IntoRawFd / FromRawFd safety contract (which was broken previously).

Drawbacks:
* Additional syscall during startup.
* The standard descriptors might have been closed intentionally.
* Requires /dev/null.

Alternatives:
* Check if stdin, stdout, stderr are opened and provide no-op substitutes in std::io::{stdin,stdout,stderr} without reopening them directly.
* Leave the status quo, expect robust applications to reopen them manually.

### CODE REVIEW

**Comment by the8472** [comment]
For windows there already is the `Maybe::Fake` implementation. Perhaps it would make sense to also apply that to unix systems when the file descriptors are not open? Then the process could keep working without needing access to `/dev/null` which might not exist in some chroot environment.

**Comment by tmiasko** [comment]
Using a no-op placeholder is definitely another option to consider. The presence of /dev/null would no longer required. The check if descriptors are valid at start-up would still be necessary. It is not immediately clear what should AsRawFd return in that case, although -1 might be an option. Furthermore if a placeholder is used it is no longer possible to customize the behaviour by changing the file descriptors directly.

AFAICS the Windows implementation no longer uses Maybe::Fake, but always obtains a fresh handle, avoiding the last issue in the process. But I don't see how this could be addressed on Unix while using placeholders, at least not without API additions.

I would like to avoid introducing a hard requirement on /dev/null, so I changed the PR to reopen the fds on the best effort basis.

File: library/std/src/sys/unix/mod.rs [hunk 1]
```diff
@@ -86,6 +96,28 @@ pub fn init() {
...
+            libc::pollfd { fd: 2, events: 0, revents: 0 },
+        ];
+        if libc::poll(pfds.as_mut_ptr(), 3, 0) == -1 {
+            return;
+        }
+        for pfd in pfds {
+            if pfd.revents & libc::POLLNVAL == 0 {
+                continue;
+            }
+            if libc::open("/dev/null\0".as_ptr().cast(), libc::O_RDWR, 0) == -1 {
```
Comment (lzutao) [inline library/std/src/sys/unix/mod.rs:113]:
```suggestion
            if libc::open(b"/dev/null\0".as_ptr().cast(), libc::O_RDWR, 0) == -1 {
```

**Comment by joshtriplett** [comment]
So, it's definitely sketchy to run a process with file descriptors 0, 1, or 2 closed, for exactly this reason: the next opened file will become one of those file descriptors, which will wreak all manner of havoc.

However, assuming the existence or accessibility of devices like `/dev/null`, as common as they are, also feels problematic.

As an alternative, which doesn't require any particular device file to exist on the filesystem, we could use a pipe:
- If file descriptor 0 doesn't exist, then open a pipe, close the write end, and set fd 0 to the read end. Any reads will then produce EOF.
- If file descriptor 1 or 2 doesn't exist, then open a pipe, close the read end, and set fd 1 or 2 (whichever doesn't exist) to that. Any writes will produce an error.

I think that will work better. It requires a little bit of care (because some of the pipes will initially become the wrong file descriptors), but the following algorithm should work:

- If fd 0 doesn't exist, then open a pipe, and the read end will always become fd 0. Just close the write end.
- Then, if fd 1 doesn't exist, open a pipe, close the read end (which will be fd 1), dup2 the write end to fd 1, close the old write end.
- Then, if fd 2 doesn't exist, open a pipe, close the read end (which will be fd 2), dup2 the write end to fd 2, close the old write end.

**Comment by the8472** [comment]
The output pipes would begin to block once they're full, wouldn't they? The advantage of `/dev/null` is that it never blocks

**Comment by joshtriplett** [comment]
No, if the other end is closed it'll error.

File: library/std/src/sys/unix/mod.rs (hunk 1 above)
Comment (joshtriplett) [inline library/std/src/sys/unix/mod.rs:113]:
```suggestion
            let mut pipe_fds = [0; 2];
            if libc::pipe(pipe_fds.as_mut_ptr()) == -1 {
```

And then before the end of the loop:
```rust
if pfd == 0 {
    // The read end of the pipe is already fd 0
    libc::close(pipe_fds[1]);
} else {
    // dup2 the write end to the desired fd (1 or 2), which will close the read end
    libc::dup2(pipe_fds[1], pfd);
    // close the old write end
    libc::close(pipe_fds[1]);
}
```
plus error handling.

**Review by joshtriplett — CHANGES_REQUESTED** [review]

**Comment by tmiasko** [comment]
I don't think a closed pipe would be a good replacement due to SIGPIPE
generated when writing it. While, the startup code does ignore SIGPIPE, the
signal disposition can be changed afterwards, and application do change it,
like rustc driver for example.

I would find receiving a SIGPIPE in this case to be highly undesirable.

**Comment by joshtriplett** [comment]
It's also undesirable to run a program without those file descriptors. And it's undesirable to require the hardcoded path `/dev/null`.

**Comment by the8472** [comment]
> And it's undesirable to require the hardcoded path /dev/null.

The current version of this PR uses them on a best-effort basis, i.e. it's not _required_.

**Comment by tmiasko** [comment]
To add another argument for /dev/null. When started in secure mode (setuid,
etc.), the mainstream libc implementations already do require the presence of
it to reopen the standard file descriptors.

But yeah, there are definitely various trade-offs to consider.

File: library/std/src/sys/unix/mod.rs (hunk 1 above)
Comment (tmiasko) [reply library/std/src/sys/unix/mod.rs:113]: When standard file descriptors are closed the stdin / stdout / stderr are
required not to panic per RFC 1014. The closed pipe variant is not an option as
proposed.

Comment (joshtriplett) [reply library/std/src/sys/unix/mod.rs:113]: Interesting. I wasn't aware of RFC 1014. Given that, I agree, this won't work. Objection withdrawn; let's go with /dev/null.

**Comment by joshtriplett** [comment]
Re-posting a review comment at the top level:
I wasn't aware of RFC 1014. Given that, I agree, the pipe idea won't work. Objection withdrawn; let's go with /dev/null.

**Comment by tmiasko** [comment]
In context of RFC 1014, I extended test to verify non-panicking behaviour.

**Comment by Dylan-DPC** [comment]
@joshtriplett any updates on this

**Comment by Amanieu** [comment]
> Check if stdin, stdout, stderr are opened and provide no-op substitutes in std::io::{stdin,stdout,stderr} without reopening them directly.

I feel that this is a better solution if it is feasible.

File: library/std/src/sys/unix/mod.rs [hunk 2]
```diff
@@ -86,6 +96,46 @@ pub fn init() {
...
+        for fd in 0..3 {
+            if libc::fcntl(fd, libc::F_GETFD) == -1 && errno() == libc::EBADF {
+                if libc::open("/dev/null\0".as_ptr().cast(), libc::O_RDWR, 0) == -1 {
+                    return;
+                }
+            }
+        }
+    }
+    #[cfg(any(target_os = "emscripten", target_os = "fuchsia", target_os = "redox"))]
+    unsafe fn sanitize_standard_fds() {}
```
Comment (Amanieu) [inline library/std/src/sys/unix/mod.rs:137]: `F_GETFD` should work on redox.

**Comment by tmiasko** [comment]
> > Check if stdin, stdout, stderr are opened and provide no-op substitutes in std::io::{stdin,stdout,stderr} without reopening them directly.
>
> I feel that this is a better solution if it is feasible.

It is definitely possible to detect closed descriptors using the same approach and disable corresponding std::io::{stderr,stdin,stdout} objects. It should avoid issues as far as access through those objects is concerned, but anything that uses file descriptors directly will still cause trouble. While an improvement, to me that still feel like incomplete solution of the problem.

@Amanieu I wonder why would you prefer that approach?

**Comment by Amanieu** [comment]
The main issue that we are trying to solve is that `Stdin`/`Stdout`/`Stderr` are unsound if the FD is closed when the program starts. Simply doing a best effort to open `/dev/null` is not enough since it can introduce unsoundness in safe code. `/dev/null` may not be available in some non-standard container or chroot environments.

**Comment by the8472** [comment]
> Simply doing a best effort to open `/dev/null` is not enough

The standard file descriptors existing is a [posix requirement](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stdout.html) though, them not being open at program entry would be a non-conforming state and defending against that is merely a defense-in-depth measure.

One could also cause unsound behavior in rust by `LD_PRELOAD` some `malloc` that violates the spec.

**Comment by tmiasko** [comment]
OK, I see your point. In that case it should be fine to attempt reopening them, but disable when that fails? I generally feel that anything short of reopening them will likely break any real application, although admittedly it will involve unsafe code.

Hmm, it might be also possible go back to earlier suggestion of using pipes, with a slight twist where they are connected wrong way around, so that read / write operations return EBADF. Though, I couldn't really tell what other consequences it could have.

**Comment by Amanieu** [comment]
Starting a program with closed file descriptors happens quite often in practice:
- You can explicitly close them in bash with `>&-`.
- Programs invoked directly by the Linux kernel as "usermode helpers" (e.g. coredump handler, driver helper programs) are started without any standard file descriptors. They are expected to log directly to /dev/kmsg.

> In that case it should be fine to attempt reopening them, but disable when that fails?

Sure, that's probably fine.

> Hmm, it might be also possible go back to earlier suggestion of using pipes, with a slight twist where they are connected wrong way around, so that read / write operations return EBADF. Though, I couldn't really tell what other consequences it could have.

You still need to disable stdin/stdout/stderr if pipe creation fails for whatever reason. Or at least explicitly abort instead of letting execution continue.

**Comment by the8472** [comment]
Well, if we consider that closed stdio is *unsound* then we may have another problem and checking this at startup isn't sufficient

* `nix::unistd::close(fd: RawFd)` is safe
* and so is `AsRawFd` (plus it just a `c_int` anyway )

So those descriptors could get closed and reused under our nose at any given time.

**Comment by tmiasko** [comment]
I implemented variant that detected closed fds and disabled corresponding Rust objects (without reopening them). That approached turned out to be insufficient to avoid problems while using various Rust applications in practice. I don't think it is worth the extra complexity. 

I would again suggest the approach already taken in this PR.

**Comment by Amanieu** [comment]
What should we do if opening `/dev/null` fails? Abort? Disable the Rust objects?

**Comment by tmiasko** [comment]
I am motivated by the cases where we can actually reopen them. I don't have strong opinion what we should do if that fails. Simply continuing or aborting, both seems fine to me.

**Comment by Amanieu** [comment]
I don't have any strong opinions either. However if we do continue then we must disable the corresponding Rust objects.

**Comment by tmiasko** [comment]
I changed the implementation to abort the process when reopening fails. In case of any bug reports with regards to this behaviour, I will revise the implementation to continue execution with Rust objects disabled.

**Comment by Amanieu** [comment]
Can you add a comment above the abort explaining why the abort is necessary? This is the first thing people will look for when they encounter this abort.

**Comment by tmiasko** [comment]
I added a comment, but also revised it shortly afterwards so it might need another r+.

File: library/std/src/sys/unix/mod.rs [hunk 3]
```diff
@@ -86,6 +93,56 @@ pub fn init() {
...
+        target_os = "redox",
+    )))]
+    unsafe fn sanitize_standard_fds() {
+        use crate::sys::os::errno;
+        let pfds: &mut [_] = &mut [
+            libc::pollfd { fd: 0, events: 0, revents: 0 },
+            libc::pollfd { fd: 1, events: 0, revents: 0 },
+            libc::pollfd { fd: 2, events: 0, revents: 0 },
+        ];
+        while libc::poll(pfds.as_mut_ptr(), 3, 0) == -1 {
```
Comment (RalfJung) [inline library/std/src/sys/unix/mod.rs:113]: Oh, this will be "interesting" to support on Miri...

Any chance we could add `cfg(miri)` to the list of exceptions above?

Comment (tmiasko) [reply library/std/src/sys/unix/mod.rs:113]: Which implementation would you like to use: `fcntl(fd, F_GETFD)` and `open("/dev/null")`, or empty one?

Comment (RalfJung) [reply library/std/src/sys/unix/mod.rs:113]: The empty on would be best. The standard FDs will always be available in Miri (and they cannot even be closed by the application as the interpreter cannot implement that behavior due to https://github.com/rust-lang/rust/issues/40032).

Comment (tmiasko) [reply library/std/src/sys/unix/mod.rs:114]: Miri should use empty implementation now.

**Comment by RalfJung** [comment]
Thanks :)
@bors r=Amanieu

**Comment by RalfJung** [comment]
```
---- [ui] ui/closed-std-fds.rs stdout ----

error: test run failed!
status: exit code: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/remote-test-client" "run" "0" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closed-std-fds/a"
stdout:
------------------------------------------
uploaded "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closed-std-fds/a", waiting for result

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'child failed with signal: 11', /checkout/src/test/ui/closed-std-fds.rs:34:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------



failures:
    [ui] ui/closed-std-fds.rs
```
on arm-linux-androideabi

**Comment by tmiasko** [comment]
The child process spawned in the test case segfaults on arm-android. I don't know why yet, but it is unrelated to the changes in std, since the same issue occurs with them.

**Comment by tmiasko** [comment]
I modified the PR to reuse an existing test case instead of adding a new one. This test case was already ignored on android for presumably the same reasons (closing any two standard streams before spawning a new process is sufficient to cause the segfault).

**Comment by RalfJung** [comment]
Something went wrong for Miri on apple targets:
```
error[E0428]: the name `sanitize_standard_fds` is defined multiple times

   --> /home/travis/.rustup/toolchains/master/lib/rustlib/src/rust/library/std/src/sys/unix/mod.rs:149:5

    |

134 |     unsafe fn sanitize_standard_fds() {

    |     --------------------------------- previous definition of the value `sanitize_standard_fds` here

...

149 |     unsafe fn sanitize_standard_fds() {}

    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `sanitize_standard_fds` redefined here

    |

    = note: `sanitize_standard_fds` must be defined only once in the value namespace of this block
```

I'll submit a PR.

**Comment by RalfJung** [comment]
Submitted https://github.com/rust-lang/rust/pull/77288

**Comment by Alphare** [comment]
I've found that this change introduced a regression in the "Rust first then fallback to Python" version of the Mercurial test suite.

I was testing if going from `1.41.1` (previous Debian stable version) to `1.48.0` broke anything, and it appears it did. [This test](https://foss.heptapod.net/octobus/mercurial-devel/-/jobs/244930#L46) checks that missing file descriptors raise an acceptable error, and this does not happen anymore. [Here](https://foss.heptapod.net/octobus/mercurial-devel/-/blob/branch/default/rust/rhg/src/main.rs#L352) is the fallback code for `rhg`, running the Python version of `hg` as a subprocess.

Here is the (somewhat convoluted) reproduction, which requires `python` be a valid Python 3 interpreter that I used with `cargo bisect-rust` (thanks @SimonSapin for the pointer on that tool btw):

```rust
//! Run the executable (not with `cargo play`, it'll eat the redirect)
//!     `myexecutable -c 'import sys; sys.stdout.write("hello")' 1>&-`
//! If compiled with 1.41.1, it will output (with an error code of 1):
//!
//! Traceback (most recent call last):
//!  File "<string>", line 1, in <module>
//!  AttributeError: 'NoneType' object has no attribute 'write'
//!
//! But with 1.48.0, it doesn't output anything and silently eats the error code, exiting with 0.

use std::process::Command;

fn main() {
    let mut args_os = std::env::args_os();
    args_os.next().expect("expected argv[0] to exist");
    let mut c = Command::new("python");
    c.args(args_os);
    let status = c.status();
    match status {
        Err(_) => (),
        Ok(s) =>  {
            if s.success() {
                std::process::exit(1);
            }
        }
    }
}
```

I'm not 100% sure what to think of it yet, but my gut feeling is that eating errors is bad; I'm reporting this now since it's fresh in my mind.

**Comment by Mark-Simulacrum** [comment]
Please file a new issue -- it's unlikely to receive much attention on a closed PR, but an issue will let us appropriately tag and track any potential fixes.
