### PR TITLE
x86: use SSE2 to pass float and SIMD types

### LINKED ISSUE #133611: Forbid disabling SSE on x86 targets that have SSE in their "baseline"
Passing `-Ctarget-feature=-sse` on an x86-64 target currently produces an ugly [LLVM error](https://rust.godbolt.org/z/3j8rnfrzP).
Doing the same on a x86-32 target leads to [unsound floating-point behavior](https://github.com/rust-lang/rust/issues/114479).

Therefore, I think we should deprecate and eventually fully forbid toggling the `sse`/`sse2` target features on x86 targets, except for those targets that do not have these features to begin with (e.g. `i586-unknown-linux-gnu`).

I am implementing some machinery [here](https://github.com/rust-lang/rust/pull/133099) that could help with that, but properly implementing this will be tricky since one can also [use `-Ctarget-cpu`](https://rust.godbolt.org/z/vaGscs6q1) to disable these target features.

Once this is implemented, we have some options for improving the Rust ABI on these targets as well:
- on x86-32, we could use SSE registers to return float values, instead of `PassMode::Indirect`
- on all x86 targets, we could pass SIMD vectors of up to 128 bits in registers rather than indirectly

[Here](https://github.com/rust-lang/rust/issues/114479#issuecomment-2082686372), compiler team triage decided "Current Tier 1 x86 targets require SSE-based floats at minimum". The concrete proposal above got MCP'd in https://github.com/rust-lang/compiler-team/issues/808.

### Open questions

How do we best implement this? It's non trivial since `-Ctarget-cpu` can alter the `sse`/`sse2` feature gates, so our usual approach of just checking which target features got toggled with `-Ctarget-feature` does not work.

To make things worse, the way we control whether `sse`/`sse2` is available in the "basline" is via the `base.cpu` field, not via the explicit list of target features, so if we want to do things "only if the baseline has SSE", that's non-trivial to implement. Maybe we should just add a `bool` field to the target spec that directly controls "use SSE registers for Rust ABI" or "requires SSE registers" or so?

Cc @bjorn3 @workingjubilee @Amanieu

### PR DESCRIPTION
**Pull request by RalfJung**
This builds on the new X86Sse2 ABI landed in https://github.com/rust-lang/rust/pull/137037 to actually make it a separate ABI from the default x86 ABI, and use SSE2 registers. Specifically, we use it in two ways: to return `f64` values in a register rather than by-ptr, and to pass vectors of size up to 128bit in a register (or, well, whatever LLVM does when passing `<4 x float>` by-val, I don't actually know if this ends up in a register).

Cc @workingjubilee 
Fixes #133611

try-job: aarch64-apple
try-job: aarch64-gnu
try-job: aarch64-gnu-debug
try-job: test-various
try-job: x86_64-gnu-nopt
try-job: dist-i586-gnu-i586-i686-musl
try-job: x86_64-msvc-1

### CODE REVIEW

File: compiler/rustc_target/src/callconv/mod.rs [hunk 1]
```diff
@@ -755,7 +771,10 @@ impl<'a, Ty> FnAbi<'a, Ty> {
                 continue;
             }
 
-            if arg_idx.is_none() && arg.layout.size > Pointer(AddressSpace::DATA).size(cx) * 2 {
+            if arg_idx.is_none()
+                && arg.layout.size > Pointer(AddressSpace::DATA).size(cx) * 2
+                && !matches!(arg.layout.backend_repr, BackendRepr::Vector { .. })
+            {
```
Comment (RalfJung) [inline compiler/rustc_target/src/callconv/mod.rs:777]: @bjorn3 this changes some apparently cranelift-motivated ABI logic; it seems a bit odd that this applies to *all* `BackendRepr` but I hope excluding `Vector` here is fine.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:777]: In fact, probably `arg.layout.backend_repr.is_aggregate()` would be the most correct check here? We shouldn't do anything here for scalars I think...

File: tests/assembly/x86-return-float.rs [hunk 2]
```diff
@@ -1,19 +1,31 @@
...
-// There's no compiletest directive to ignore a test on i586 only, so just always explicitly enable
-// SSE2.
-// Use the same target CPU as `i686` so that LLVM orders the instructions in the same order.
-//@ compile-flags: -Ctarget-feature=+sse2 -Ctarget-cpu=pentium4
+//@ revisions: sse nosse
+//@[sse] compile-flags: --target i686-unknown-linux-gnu
+//@[sse] needs-llvm-components: x86
+// We make SSE available but don't use it for the ABI.
+//@[nosse] compile-flags: --target i586-unknown-linux-gnu -Ctarget-feature=+sse2 -Ctarget-cpu=pentium4
+//@[nosse] needs-llvm-components: x86
```
Comment (RalfJung) [inline tests/assembly/x86-return-float.rs:7]: Tidy is being silly and doesn't let us set the `needs-llvm-components: x86` uniformly for all revisions.

File: tests/codegen/intrinsics/transmute-x64.rs [hunk 3]
```diff
@@ -9,9 +9,10 @@ use std::mem::transmute;
 // CHECK-LABEL: @check_sse_float_to_int(
 #[no_mangle]
 pub unsafe fn check_sse_float_to_int(x: __m128) -> __m128i {
-    // CHECK-NOT: alloca
-    // CHECK: %0 = load <4 x float>, ptr %x, align 16
-    // CHECK: store <4 x float> %0, ptr %_0, align 16
+    // FIXME: the MIR opt still works, but the ABI logic now introduces
+    // an alloca here.
+    // CHECK: alloca
+    // CHECK: store <4 x float> %x, ptr %_0, align 16
```
Comment (RalfJung) [inline tests/codegen/intrinsics/transmute-x64.rs:15]: I have no idea what this was trying to test, but it probably doesn't test that any more. The alloca is emitted by the ABI handling, and this test disables LLVM optimizations, so there's no way we can avoid the alloca.

Cc @scottmcm (who added the test in https://github.com/rust-lang/rust/commit/d757c4b904869967f1e665dc2bb9a2ca5122bc96)

File: tests/codegen/simd/packed-simd.rs [hunk 4]
```diff
@@ -1,4 +1,5 @@
 //@ revisions:opt3 noopt
+//@ only-x86_64
```
Comment (RalfJung) [inline tests/codegen/simd/packed-simd.rs:2]: This test is checking our LLVM ABI lowering as much as it is checking anything packed-simd specific, so it will be very hard to make this work uniformly across targets that use a different ABI lowering.

File: tests/codegen/simd/packed-simd.rs [hunk 5]
```diff
@@ -14,41 +15,41 @@ use core::{mem, ptr};
...
-    // CHECK: load <3 x float>
+    // noopt: alloca
+    // opt3-NOT: alloca
+    // opt3: load <3 x float>
     let x = load(x);
     // CHECK: [[VREG:%[a-z0-9_]+]] = fmul <3 x float>
-    // CHECK-NEXT: store <3 x float> [[VREG]], ptr [[RET_VREG]], [[RET_ALIGN]]
-    // CHECK-NEXT: ret void
+    // opt3-NEXT: ret <3 x float> [[VREG:%[a-z0-9_]+]]
+    // noopt: ret <3 x float> [[VREG:%[a-z0-9_]+]]
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/codegen/simd/packed-simd.rs:44]: OTOH the "noopt" test was already very odd before... the `load <3 x float>` there referred to loading the return value of `load()` which was returned into the alloca.

File: compiler/rustc_target/src/spec/mod.rs [hunk 6]
```diff
@@ -2493,6 +2524,12 @@ pub struct TargetOptions {
     /// If not provided, LLVM will infer the float ABI from the target triple (`llvm_target`).
     pub llvm_floatabi: Option<FloatAbi>,
 
+    /// Picks a specific ABI for this target. This is *not* just for "Rust" ABI functions,
+    /// it can also affect "C" ABI functions; the point is that this flag is interpreted by
+    /// rustc and not forwarded to LLVM.
+    /// So far, this is only used on x86.
+    pub rust_abi: Option<RustAbi>,
```
Comment (Noratrieb) [inline compiler/rustc_target/src/spec/mod.rs:2531]: Alternative name suggestion: `rustc_abi`

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_target/src/callconv/mod.rs:780]: > We shouldn't do anything here for scalars I think...

On 32bit targets we do need to force i128 to be returned by-ref as the other option is returning it in 4 registers, which no ABI supports. Also on Windows and s390x there is only a single return register defined by the ABI. I still need to look into if I can make Cranelift support LLVM's ABI extension to return i128 in two registers on Windows. And on s390x I need to make rustc force even i128 to be returned by-ref. And on both I need to make ScalarPair get returned by-ref.

> but I hope excluding Vector here is fine.

I think so. Cranelift should support returning values in SSE registers. I've never actually tested that though.

File: compiler/rustc_target/src/callconv/mod.rs [hunk 7]
```diff
@@ -799,48 +821,50 @@ impl<'a, Ty> FnAbi<'a, Ty> {
...
+                    // enabled but the callee does, then passing an AVX argument
+                    // across this boundary would cause corrupt data to show up.
+                    //
+                    // This problem is fixed by unconditionally passing SIMD
+                    // arguments through memory between callers and callees
+                    // which should get them all to agree on ABI regardless of
+                    // target feature sets. Some more information about this
+                    // issue can be found in #44367.
+                    //
+                    // Note that the intrinsic ABI is exempt here as tjpse are not
```
Comment (bjorn3) [inline compiler/rustc_target/src/callconv/mod.rs:857]: *those

File: compiler/rustc_target/src/callconv/mod.rs [hunk 8]
```diff
@@ -799,48 +821,50 @@ impl<'a, Ty> FnAbi<'a, Ty> {
...
+                    // real functions anyway, and LLVM expects certain types.
```
Comment (bjorn3) [inline compiler/rustc_target/src/callconv/mod.rs:858]: I would rather say that the backends expect certain types. Not all rust intrinsics get directly lowered to LLVM intrinsics. And the GCC backend is also a thing. (cg_clif is not relevant here as it doesn't use the abi adjustments for intrinsics at all. It directly reads the MIR operands for the call terminator. I want to change cg_ssa to do the same thing at some point.)

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: > On 32bit targets we do need to force i128 to be returned by-ref 

Ugh... but I had to make it check `is_aggregate` here or else returning `f128` via an SSE register breaks.

File: compiler/rustc_target/src/spec/mod.rs (hunk 6 above)
Comment (RalfJung) [reply compiler/rustc_target/src/spec/mod.rs:2531]: Yeah that would be an option. Let's see what other think.

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Why doesn't the `!matches!(arg.layout.backend_repr, BackendRepr::Vector { .. })` you had previously work?

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: The comment has to be incomplete then... in the comment it says
```
                // [...] while Cranelift will look at each IR level
                // return value independently and decide to pass it in a
                // register or not, which would result in the return value
                // being passed partially in registers and partially through a
                // return area pointer.
```
but apparently cranelift will take a single value like i128 and do something very cursed to it?

File: tests/codegen/intrinsics/transmute-x64.rs (hunk 3 above)
Comment (bjorn3) [reply tests/codegen/intrinsics/transmute-x64.rs:15]: This is a regression test for an ICE in cg_ssa: https://github.com/rust-lang/rust/pull/110021/commits/d757c4b904869967f1e665dc2bb9a2ca5122bc96

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Also, the comment later saying that for non-Rust ABIs, the ABI adjustments anyway will deal with this is definitely not true for `i128`.

Comment (bjorn3) [reply compiler/rustc_target/src/callconv/mod.rs:780]: > but apparently cranelift will take a single value like i128 and do something very cursed to it?

Yes, it splits it into register sized chunks and then assigns each one to a location. And in any case I'm trying to get rid of the implicit introduction inside Cranelift's ABI handling of a return area pointer. This happens whenever at the Cranelift IR level there is a return type which doesn't fully fit in return registers. I'm trying to remove it because this code is actively ABI violating in more ways than just returning i128 incorrectly and I simply do not see any way of fixing it. (https://github.com/bytecodealliance/wasmtime/issues/9510) The explicit introduction of a return area pointer when cg_clif sees that the PassMode is Indirect is completely fine however, which is why I'm trying to make rustc explicitly tell when the return value should be returned by-ref for the Rust ABI. For the C ABI rustc already correctly tells the backends this in all cases.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: > Why doesn't the !matches!(arg.layout.backend_repr, BackendRepr::Vector { .. }) you had previously work?

Because f128 is not a vector type.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Well for now I added a hack which makes the Rust ABI worse in LLVM for the sake for the cranelift backend. I think that's bad, but it only affects the unstable f128 type so I don't care enough to try and find a proper solution here.

Comment (bjorn3) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Ah, right. How about `!matches!(arg.layout.backend_repr, BackendRepr::Vector { .. }) && !layout.ty.is_float()`?

File: tests/codegen/intrinsics/transmute-x64.rs (hunk 3 above)
Comment (RalfJung) [reply tests/codegen/intrinsics/transmute-x64.rs:15]: But why would that be a codegen test...?

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Looking at `ty` is almost always wrong in the ABI logic.

File: compiler/rustc_target/src/callconv/x86.rs [hunk 9]
```diff
@@ -231,14 +231,17 @@ where
...
         if has_float {
             if cx.target_spec().rust_abi == Some(RustAbi::X86Sse2)
                 && fn_abi.ret.layout.backend_repr.is_scalar()
-                && fn_abi.ret.layout.size.bits() <= 128
+                && fn_abi.ret.layout.size.bits() <= 64
             {
                 // This is a single scalar that fits into an SSE register.
+                // FIXME: We cannot return 128-bit-floats this way since scalars larger than
+                // 64bit must be returned indirectly to make cranelift happy. See the comment
+                // in `adjust_for_rust_abi`.
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_target/src/callconv/x86.rs:244]: The problem is that the way the "return large things indirectly" is implemented is not great, it leads to ICEs if other adjustments have already decided the ABI for one of these return types.

IMO this is a backend bug, backends should support all scalar types as return types.

File: compiler/rustc_target/src/callconv/mod.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_target/src/callconv/mod.rs:780]: `!matches!(arg.layout.backend_repr, BackendRepr::Vector { .. } | BackendRepr::Scalar(Scalar::Initialized { value: Primitive::Float(_), ... }))` should work, right?

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:780]: Yeah but that's a terrible hack... and it would still rely on cranelift's lowering of f128 to match that of LLVM for non-x86 targets.

Comment (RalfJung) [reply compiler/rustc_target/src/callconv/mod.rs:782]: I think I can make the logic here just entirely skip arguments with `PassMode::Cast`; those had their ABI decided by the target-specific logic so we don't want to overwrite that.

File: tests/ui-fulldeps/codegen-backend/hotplug.rs [hunk 10]
```diff
@@ -6,6 +6,9 @@
 //@ normalize-stdout: "libthe_backend.dylib" -> "libthe_backend.so"
 //@ normalize-stdout: "the_backend.dll" -> "libthe_backend.so"
 
+// Pick a target that requires no target features, so that no warning is shown
+// about missing target features.
+//@ compile-flags: --target arm-unknown-linux-gnueabi
```
Comment (RalfJung) [inline tests/ui-fulldeps/codegen-backend/hotplug.rs:11]: @bjorn3 does the cranelift backend return anything for `target_features_cfg`? If not, there might be warnings now about missing target features, depending on the ABI info for the current target.

Comment (bjorn3) [reply tests/ui-fulldeps/codegen-backend/hotplug.rs:11]: Yes, it currently hard codes sse and sse2 for all x86_64 targets that are not bare-metal: https://github.com/rust-lang/rust/blob/7bb98889534d597911263d647424557b414770ec/compiler/rustc_codegen_cranelift/src/lib.rs#L179-L200

Comment (bjorn3) [reply tests/ui-fulldeps/codegen-backend/hotplug.rs:11]: tests/ui-fulldeps/codegen-backend/ doesn't actually use cg_clif. It uses the backend in tests/ui-fulldeps/codegen-backend/auxiliary/the_backend.rs. It is fine to implement `target_features_cfg` there as always returning sse and sse2. It doesn't compile anything to machine code anyway. It is just a test that `-Zcodegen-backend` with an external codegen backend functions.

File: compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs [hunk 11]
```diff
@@ -1,7 +1,12 @@
-use crate::spec::{Cc, LinkerFlavor, Lld, SanitizerSet, StackProbeType, Target, base};
+use crate::spec::{Cc, LinkerFlavor, Lld, RustAbi, SanitizerSet, StackProbeType, Target, base};
 
 pub(crate) fn target() -> Target {
     let mut base = base::linux_gnu::opts();
+    base.rust_abi = Some(RustAbi::X86Sse2);
```
Comment (workingjubilee) [inline compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs:5]: if this doesn't affect only the `extern "Rust"` ABI then it has to not be this name.

**Review by workingjubilee — CHANGES_REQUESTED** [review]
I would prefer we use the term "Rust ABI" almost-exclusively to refer to ABIs in the class of `extern "Rust"` and `extern "rust-cold"` and so on. So, I think the field name does need to be changed, even if it's just one letter of difference.

**Comment by RalfJung** [comment]
> On a meta note, should this get a blog post to alert anyone who is using this behavior? I expect this won't affect too many users but a heads up would be nice for anyone who does need it.

Yeah that might make sense... I won't have time to write one in the next 2 weeks, though. Should this be timed with the landing on nightly or the stable release? Everyone using JSON target specs has to be on nightly anyway...

File: tests/ui-fulldeps/codegen-backend/hotplug.rs (hunk 10 above)
Comment (RalfJung) [reply tests/ui-fulldeps/codegen-backend/hotplug.rs:11]: Yeah I get that. But it still seemed easiest to just use a target that doesn't require any features.

**Comment by RalfJung** [comment]
@SparrowLii should we be looking for a different reviewer or are you okay taking this one? :)

**Comment by briansmith** [comment]
> The fourth commit changes the special x86 float return handling to also make use of SSE registers where possible.

Is this change separable from the first three? It seems better to separate these two changes as changing the ABI is the most risky and most likely to be backed out.

**Comment by RalfJung** [comment]
The commit can be separated, but without that commit, `RustcAbi::X86Sse2` doesn't do what the comment says so that seems like an odd state to leave the repo in.

I could (with some effort) split this up so a first PR doesn't even add `RustcAbi::X86Sse2`.

---

Also, we haven't yet gotten any signal from our reviewer, so let's roll a new one.
r? compiler

**Comment by jieyouxu** [comment]
Won't be able to review this in the next few days, so r? compiler

**Comment by RalfJung** [comment]
That clippy lint is IMO misguided, it basically un-does match ergonomics... this will be annoying. :/

**Comment by RalfJung** [comment]
I factored out two sub-PRs:
- https://github.com/rust-lang/rust/pull/136146
- https://github.com/rust-lang/rust/pull/136147

**Comment by workingjubilee** [comment]
I doubt that the risk is so great but @briansmith's request was probably good anyways since it was much easier to review one of the factored out PRs.

But there is indeed no need to turn this PR into a 2400 year old Grecian thought experiment.

**Comment by briansmith** [comment]
What's the motivation for optimizing the calling convention for 32-bit i686 non-no_std targets? The negative consequence of this change is that no_std i686 targets and non-no_std targets will have different ABI for Rust. Already other architectures have to deal with that. But, OTOH, is anybody asking for an optimized ABI for i686?

Also, it might be worth trying to line up the calling convention with the `__vectorcall` calling convention.

**Comment by briansmith** [comment]
> This has nothing to do with no_std vs std. Not sure where you got that from. 

If there were a `i686-unknown-none` or similar target for a 32-bit OS kernel (e.g. Linux), it wouldn't be able to use this calling convention. (Redox kernel only supports i686+ CPUs because of non-SIMD features that aren't in earlier CPUs, for example.)

**Comment by RalfJung** [comment]
That's a softfloat vs hardfloat distinction, not a no_std vs std distinction. Softfloat x86 targets (32bit and 64bit) should set rustc_abi to X86Softfloat.

**Comment by briansmith** [comment]
> But I expect i686-unknown-none, if it were a hardfloat target, should enable SSE. For better or worse we use i686 to mean CPUs with SSE. We use i586 for older targets; those should indeed not use SSE.

I agree "i686" means "CPUs with SSE" but it doesn't mean "you can use SSE whenever you want." That is why we have `std::arch::is_X_feature_detected` but not `core::arch::is_X_feature_detected`. (All x86_64 CPUs have SSE, but x86_64-*-none targets don't enable SSE by default, for this reason.)

**Comment by RalfJung** [comment]
The MCP I linked above decided that we will *require* SSE for targets that have it in their baseline. That's what this PR implements.

> (All x86_64 CPUs have SSE, but x86_64-*-none targets don't enable SSE by default, for this reason.)

That's just a hardfloat vs softfloat thing. Of course softfloat targets don't enable SSE.

**Comment by briansmith** [comment]
> The main goal here is to make SSE required so people don't think they use a tier 1 target when really their configuration is more of a tier 3 target.

It makes sense to force SSE to be enabled for existing i686 targets because those existing targets specifically are for operating systems that support SSE in userspace applications.

Why it matters, more specifically: i586 doesn't have CMOV, which is critical for crypto code. So we generally require at least an i686. We provide modes where we avoid SSE (if OS is "none") but still require cmov. I believe atomics are also i686-specific and we also use atomics to cache CPUID results. So I guess we would use an `i586-*` target with those CPU features forced on.

> Using SSE for the ABI is largely an incidental benefit.

I'm not sure that this is a good justification for creating a new ABI for it.

**Comment by RalfJung** [comment]
> I'm not sure that this is a good justification for creating a new ABI for it.

The "Rust" ABI is entirely an internal implementation detail of the compiler. It seems silly to pass SSE values (or f64 return values) by-reference when we require SSE for a given target.

**Comment by briansmith** [comment]
Here is the RedoxOS target definition for its `i686-unknown-kernel`: https://gitlab.redox-os.org/redox-os/kernel/-/blob/master/targets/i686-unknown-kernel.json

```
`"llvm-target": "i686-unknown-none",`
...
`"features": "-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-3dnow,-3dnowa,-avx,-avx2,+soft-float",`
...
```
I guess this would be very similar to what one for the Linux kernel would be.

/cc @jackpot51

**Comment by RalfJung** [comment]
That is clearly a softfloat target and as such unaffected by this PR.

**Comment by briansmith** [comment]
So, in a softfloat i686-* target, or an i586- target, when I have this:

```
#[target_feature(enable = "sse2"]
fn foo(....) {
}
```

When I call `foo()`, will it also use the new calling convention?

**Comment by RalfJung** [comment]
No, softfloat targets always use the softfloat ABI. (Someone recently told me that LLVM basically entirely ignores `+sse2` when `+soft-float` is set, I did not check that, but I suspect your attribute already does basically nothing on a soft-float target. But that's a separate issue.)

**Comment by briansmith** [comment]
> No, softfloat targets always use the softfloat ABI. i586 hardfloat targets use the basic x86-32 non-SSE ABI. #[target_feature] does not affect the ABI (except in cases tracked by existing soundness issues: https://github.com/rust-lang/rust/issues/116344 and https://github.com/rust-lang/rust/issues/116558).

> (FYI, someone recently told me that LLVM basically entirely ignores +sse2 when +soft-float is set; I did not check that, but I suspect your attribute already does basically nothing on a soft-float target. But that's a separate issue.)

That will work very poorly for x86_64-unknown-none and also any similar softfloat i686 target. We really want our SIMD-enabled functions to be fully optimized (including between calls to themselves) even on targets where SIMD can only be used in specific contexts, like within OS kernels.

And the reason it's relevant to this PR is that, if we made that work, then we wouldn't need a new ABI for hardfloat x86 because the existing ABI would automatically do the right thing on a per-call basis.

**Comment by RalfJung** [comment]
> That will work very poorly for x86_64-unknown-none and also any similar softfloat i686 target. We really want our SIMD-enabled functions to be fully optimized (including between calls to themselves) even on targets where SIMD can only be used in specific contexts, like within OS kernels.

That's a pre-existing issue and has nothing to do with this PR.

> And the reason it's relevant to this PR is that, if we made that work, then we wouldn't need a new ABI for hardfloat x86 because the existing ABI would automatically do the right thing on a per-call basis.

I don't follow. ABI can never depend on `#[target_feature]`, that would be unsound.

**Comment by bjorn3** [comment]
> (FYI, someone recently told me that LLVM basically entirely ignores +sse2 when +soft-float is set; I did not check that, but I suspect your attribute already does basically nothing on a soft-float target. But that's a separate issue.)

Looks like that is indeed the case: https://rust.godbolt.org/z/PGGv3n9M6

**Comment by RalfJung** [comment]
> wouldn't need a new ABI

As I already explained, we don't *need* a new ABI for anything. What we need is to prevent people from disabling SSE on targets with a Pentium 4 baseline, as doing so would bring them outside what is supported for these targets. (See https://github.com/rust-lang/rust/issues/114479, which the compiler team [decided](https://github.com/rust-lang/compiler-team/issues/808) to fix by *requiring* SSE on the affected targets.) That's the first commit. The second commit is entirely "because we can". The second commit does nothing for softfloat targets. I have no idea what you are trying to prevent or achieve here, but I recommend you read the issues linked in the OP -- this is just the last PR in a long line of work on cleaning up our handling of how target features interact with ABI.

**Comment by RalfJung** [comment]
@workingjubilee  all the prerequisite PRs landed so this should be good to go. :)

**Comment by briansmith** [comment]
> I have no idea what you are trying to prevent or achieve here, but I recommend you read the issues linked in the OP -- this is just the last PR in a long line of work on cleaning up our handling of target features, and there is a lot of context here which you are not accounting for.

I have read the other issues. My point is that we need a better story for using SIMD usage (including optimized calling conventions) within targets that don't have SIMD target features enabled by default. Not just for x86, but for all targets. If we can solve that problem then having a new ABI for x86 makes less sense because ideally an optimized calling convention would automatically be chosen based on the type of the function being called (whether it contains FP/SIMD types in its parameters or return type).

Regardless, I don't object to this change.

**Comment by RalfJung** [comment]
That's a much wider discussion; there are several pretty tricky issues in the proposal you sketched that I don't know how to solve or how you imagine them being solved -- but please let's move this to Zulip or IRLO if you want to continue that discussion.

My personal main focus is soundness; I won't be pushing for anything beyond that myself, but I am happy to help evaluate the soundness of any proposals that are being made to improve control or performance. Given that everything in this PR is an unstable implementation detail, if it turns out that those proposals obviate the need for this separate ABI, we can just take it back -- but I don't see how that could possibly work, and even if it did work I doubt anything will actually materialize in the near future.

File: tests/codegen/intrinsics/transmute-x64.rs (hunk 3 above)
Comment (workingjubilee) [reply tests/codegen/intrinsics/transmute-x64.rs:15]: hmm @scottmcm can you explain?

File: tests/ui/sse-abi-checks.rs [hunk 12]
```diff
@@ -1,6 +1,6 @@
 //! Ensure we trigger abi_unsupported_vector_types for target features that are usually enabled
 //! on a target, but disabled in this file via a `-C` flag.
-//@ compile-flags: --crate-type=rlib --target=i686-unknown-linux-gnu -C target-feature=-sse,-sse2
+//@ compile-flags: --crate-type=rlib --target=i586-unknown-linux-gnu -C target-feature=-sse,-sse2
```
Comment (workingjubilee) [inline tests/ui/sse-abi-checks.rs:3]: Huh. Do we need to disable SSE and SSE2 on this target anymore?

File: compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs [hunk 13]
```diff
@@ -1,7 +1,13 @@
...
+use crate::spec::{Cc, LinkerFlavor, Lld, RustcAbi, SanitizerSet, StackProbeType, Target, base};
 
 pub(crate) fn target() -> Target {
     let mut base = base::linux_gnu::opts();
+    base.rustc_abi = Some(RustcAbi::X86Sse2);
+    // Dear distribution packager, if you are changing the base CPU model with the goal of removing
+    // the SSE2 requirement, make sure to also set the `rustc_abi` to `None` above or else the compiler
+    // will complain that the chosen ABI cannot be realized with the given CPU features.
+    // Also note that x86 without SSE2 is *not* considered a Tier 1 target by the Rust project, and
+    // it has some known floating-point correctness issues that can lead to unsoundness.
```
Comment (workingjubilee) [inline compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs:10]: "unsoundness" sounds vague, and the alternative can also be "unsoundness" as seen by a distro packager (i.e. programs that incorporate Rust crashing due to SIGILL on CPUs they used to run on... usually a bad sign!)

I think we can specify the double-rounding issue and sometimes value truncation, because LLVM can incorrectly handle spilling a value to the stack and then pulling it back into an FP register? So float-using code may now have corrupted values, which may lead to incorrect math or memory unsoundness if code uses a float as a key to a data structure.

File: tests/assembly/closure-inherit-target-feature.rs [hunk 14]
```diff
@@ -15,9 +15,8 @@ pub unsafe fn sse41_blend_nofeature(x: __m128, y: __m128) -> __m128 {
         // check that _mm_blend_ps is not being inlined into the closure
         // CHECK-LABEL: {{sse41_blend_nofeature.*closure.*:}}
         // CHECK-NOT: blendps
-        // CHECK: {{call .*_mm_blend_ps.*}}
+        // CHECK: {{jmp .*_mm_blend_ps.*}}
```
Comment (workingjubilee) [inline tests/assembly/closure-inherit-target-feature.rs:18]: huh, that's interesting...

File: tests/codegen/simd-intrinsic/simd-intrinsic-transmute-array.rs [hunk 15]
```diff
@@ -38,7 +38,7 @@ pub fn build_array_s(x: [f32; 4]) -> S<4> {
 #[no_mangle]
 pub fn build_array_transmute_s(x: [f32; 4]) -> S<4> {
     // CHECK: %[[VAL:.+]] = load <4 x float>, ptr %x, align [[ARRAY_ALIGN]]
-    // CHECK: store <4 x float> %[[VAL:.+]], ptr %_0, align [[VECTOR_ALIGN]]
+    // CHECK: ret <4 x float> %[[VAL:.+]]
```
Comment (workingjubilee) [inline tests/codegen/simd-intrinsic/simd-intrinsic-transmute-array.rs:41]: nice

**Review by workingjubilee — COMMENTED** [review]
some preliminary comments, mostly positive noises. looks good. I need to reread the actual compiler logic again.

File: tests/ui/sse-abi-checks.rs (hunk 12 above)
Comment (RalfJung) [reply tests/ui/sse-abi-checks.rs:3]: Ah, right, we do not... and the point here was to check that `-Ctarget-feature` disabling features is correctly checked. I guess we can't do that on x86 any more since we can't disable the relevant target features any more. Do we even still have any target that has some vector size by default which can then be disabled?

File: compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs (hunk 13 above)
Comment (RalfJung) [reply compiler/rustc_target/src/spec/targets/i686_unknown_linux_gnu.rs]: I extended the comment.

File: tests/ui/sse-abi-checks.rs (hunk 12 above)
Comment (workingjubilee) [reply tests/ui/sse-abi-checks.rs]: at least Project Make Invalid States Unrepresentable seems to be coming along nicely,  even if it costs us our tests.

**Review by workingjubilee — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/136811#issuecomment-2648346987

**Comment by RalfJung** [comment]
Ah, that test now fails on aarch64-apple-darwin... well that's annoying. :/ There's no way to branch of the target architecture in a codegen test, is there? With how target-dependent the ABI representation of LLVM is, codegen tests covering the ABI are not really portable.

**Comment by workingjubilee** [comment]
>  There's no way to branch of the target architecture in a codegen test, is there?

No, not really. There's revisions and that's pretty much it.

**Comment by RalfJung** [comment]
Hm, somehow this does not work... I would expect that it ignores the "other" revision on my system, but it gets run and then of course fails:
```
//@ revisions: x86 other
//@[x86] only-x86
//@[other] ignore-x86
```

**Comment by RalfJung** [comment]
Oh wait does "x86" mean "32bit x86" here? Argh...

**Comment by workingjubilee** [comment]
it's very fussy about spacing, it seems

**Comment by workingjubilee** [comment]
> Oh wait does "x86" mean "32bit x86" here? Argh...

yes it does, unfortunately

**Comment by workingjubilee** [comment]
Seems like it'll go.

@bors r+

**Comment by RalfJung** [comment]
I figured we could still also have the test on x86-32 (and therefore in PR CI) with yet another revision, so I added that. Tested locally with `--target i686-unknown-linux-gnu`.

@bors r=workingjubilee

**Comment by fmease** [comment]
https://github.com/rust-lang/rust/pull/136872#issuecomment-2651494566
@bors r-

File: tests/codegen/abi-x86-sse.rs [hunk 16]
```diff
@@ -0,0 +1,36 @@
...
+trait Copy {}
+
+// Ensure this type is passed without ptr indirection on targets that
+// require SSE2.
+#[repr(simd)]
+pub struct Sse([f32; 4]);
+
+// x86-64: <4 x float> @sse_id(<4 x float> {{[^,]*}})
+// x86-32: <4 x float> @sse_id(<4 x float> {{[^,]*}})
+// x86-32-nosse: void @sse_id(ptr {{[^,]*}} sret{{[^,]*}}, ptr {{[^,]*}})
```
Comment (workingjubilee) [inline tests/codegen/abi-x86-sse.rs:32]: you got ambushed by spaces... your current thing assumes two spaces, you want something more like
```suggestion
// x86-32-nosse: void @sse_id(ptr{{[^,]*}} sret{{[^,]*}}, ptr{{[^,]*}})
```

Comment (RalfJung) [reply tests/codegen/abi-x86-sse.rs:32]: Hm, I'd like to avoid matching `ptrfoobar` though. I'll play with the regex a little.

**Comment by workingjubilee** [comment]
that also works, r=me if you're happy with it

**Comment by RalfJung** [comment]
Yeah I mean obviously the i586 targets still use the old ABI... not sure how to do this, compiletest isn't flexible enough I think. :/

**Comment by RalfJung** [comment]
@workingjubilee uh, mind if I completely revert your changes to `tests/assembly/x86-return-float.rs`? I can't really figure out how to merge that with this PR, without completely re-adjusting that test from scratch. And I can't read assembly so adjusting that test for this PR was a major pain.^^

**Comment by RalfJung** [comment]
Okay I managed to update the test... @workingjubilee please have another look, I have no idea whether I am checking the right things in that assembly test.^^

@bors try

File: tests/codegen/intrinsics/transmute-x64.rs (hunk 3 above)
Comment (RalfJung) [reply tests/codegen/intrinsics/transmute-x64.rs:15]: So should I remove the test then? Or is there some way to still test what actually matters here?

Comment (RalfJung) [reply tests/codegen/intrinsics/transmute-x64.rs:15]: @scottmcm So should I remove the test then? Or is there some way to still test what actually matters here?

File: tests/assembly/x86-return-float.rs [hunk 17]
```diff
@@ -33,7 +33,7 @@ use minicore::*;
 // CHECK-LABEL: return_f32:
 #[no_mangle]
 pub fn return_f32(x: f32) -> f32 {
-    // CHECK: movl {{.*}}(%ebp), %eax
+    // CHECK: movss {{.*}}(%ebp), %xmm0
     // CHECK-NOT: ax
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/assembly/x86-return-float.rs]: Ah :)

**Comment by workingjubilee** [comment]
sorry about the exciting rebases Ralf, I think that's the last conflict. ^^;

**Comment by workingjubilee** [comment]
> @workingjubilee uh, mind if I completely revert your [changes](https://github.com/rust-lang/rust/pull/136758) to `tests/assembly/x86-return-float.rs`? I can't really figure out how to merge that with this PR, without completely re-adjusting that test from scratch. And I can't read assembly so adjusting that test for this PR was a major pain.^^

yeah basically changing it to what you've got right now is fine.

**Comment by RalfJung** [comment]
Yeah that's just hopeless. :( Either we disable the test entirely on x86-32, or we need compiletest support for distinguishing x86-32 targets based on whether they use SSE2 for the ABI or not.

**Comment by workingjubilee** [comment]
as an update for anyone following along, we have split out the first commit to https://github.com/rust-lang/rust/pull/137037

File: tests/assembly/x86-return-float.rs [hunk 18]
```diff
@@ -33,18 +33,18 @@ use minicore::*;
 // CHECK-LABEL: return_f32:
 #[no_mangle]
 pub fn return_f32(x: f32) -> f32 {
-    // CHECK: movl {{.*}}(%ebp), %eax
-    // CHECK-NOT: ax
+    // CHECK: movss {{.*}}(%ebp), %xmm0
+    // Make sure we do not move out of xmm0 again
+    // CHECK-NOT: xmm0
     // CHECK: retl
```
Comment (workingjubilee) [inline tests/assembly/x86-return-float.rs:39]: If this works, it would also be an option and better due to enforcing more strictly... I _think_ it doesn't due to the frame pointers though. Maybe we should be forcing non-leaf frame-pointers instead...
```suggestion
    // CHECK: movss {{.*}}(%ebp), %xmm0
    // CHECK-NEXT: retl
```

File: tests/assembly/x86-return-float.rs [hunk 19]
```diff
@@ -33,18 +33,18 @@ use minicore::*;
...
 
 // CHECK-LABEL: return_f64:
 #[no_mangle]
 pub fn return_f64(x: f64) -> f64 {
-    // CHECK: movl [[#%d,OFFSET:]](%ebp), %[[PTR:.*]]
-    // CHECK-NEXT: movsd [[#%d,OFFSET+4]](%ebp), %[[VAL:.*]]
-    // CHECK-NEXT: movsd %[[VAL]], (%[[PTR]])
+    // CHECK: movsd {{.*}}(%ebp), %xmm0
+    // CHECK-NOT: xmm0
     // CHECK: retl
```
Comment (workingjubilee) [inline tests/assembly/x86-return-float.rs:48]: same "if it works"
```suggestion
    // CHECK: movsd {{.*}}(%ebp), %xmm0
    // CHECK-NEXT: retl
```

**Review by workingjubilee — COMMENTED** [review]
some thoughts now that I've been staring at this test for days. mostly optional.

File: tests/assembly/x86-return-float.rs (hunk 18 above)
Comment (RalfJung) [reply tests/assembly/x86-return-float.rs:39]: There's a `popl` in between the two; I can add a CHECK-NEXT for that as well. (same for the other test.)

File: tests/codegen/intrinsics/transmute-x64.rs (hunk 3 above)
Comment (RalfJung) [reply tests/codegen/intrinsics/transmute-x64.rs]: I ended up removing the test; I can't figure out how to write a test that does not contain `alloca`. We always emit `alloca` for the implicit transmutes caused by the ABI, so there's no way to reasonably test for their absence in a test that disables LLVM opts.

@scottmcm is it worth opening an issue to track improving our codegen for the implicit ABI transmutes? It would maybe use some of the same optimizations as explicit transmutes... or maybe not, I have no idea.

**Comment by RalfJung** [comment]
Gosh this was painful... I won't attempt to do any other ABI change any time soon, that's for sure.^^

@bors try

**Comment by RalfJung** [comment]
:tada: finally :-)

@workingjubilee I'll let you have a look at the new changes in this PR -- it's mostly a bunch of diff in the f16/f128 tests confirming the exact LLVM IR we generate now. For the union-abi test, I didn't bother with a "nosse" revision, it didn't seem worth it.

File: tests/codegen/union-abi.rs [hunk 20]
```diff
@@ -88,7 +92,8 @@ pub union UnionF32F32 {
     b: f32,
 }
 
-// x86: define {{(dso_local )?}}i32 @test_UnionF32F32(float %_1)
+// x86-sse: define {{(dso_local )?}}<4 x i8> @test_UnionF32F32(float %_1)
+// x86-nosse: define {{(dso_local )?}}i32 @test_UnionF32F32(float %_1)
```
Comment (workingjubilee) [inline tests/codegen/union-abi.rs:96]: nice

File: tests/codegen/float/f128.rs [hunk 21]
```diff
@@ -60,7 +63,8 @@ pub fn f128_le(a: f128, b: f128) -> bool {
     a <= b
 }
 
-// x86-LABEL: void @f128_neg({{.*}}sret([16 x i8])
+// x86-nosse-LABEL: void @f128_neg({{.*}}sret([16 x i8])
+// x86-sse-LABEL: <16 x i8> @f128_neg(fp128
```
Comment (workingjubilee) [inline tests/codegen/float/f128.rs:67]: huh...

this... feels incorrect? yet I see how it isn't. interesting.

Comment (workingjubilee) [reply tests/codegen/float/f128.rs:67]: @tgross35 this is the correct representation, then? as a vector, to guarantee passing in xmm registers?

File: tests/codegen/union-abi.rs (hunk 20 above)
Comment (workingjubilee) [reply tests/codegen/union-abi.rs:96]: wait, this also uses the byte vector, now that I look? interesting.

**Comment by workingjubilee** [comment]
r=me.

that's an interesting development in terms of how our codegen looks but it seems correct.

File: tests/codegen/float/f128.rs (hunk 21 above)
Comment (tgross35) [reply tests/codegen/float/f128.rs:67]: From the ABI

> Arguments of types __float128, _Decimal128 and __m128 are split into two halves. The least significant ones belong to class SSE, the most significant one to class SSEUP

So passing them in the same way as __m128 seems reasonable.

Not needed here, but these tests should probably be split. I originally added them to verify we do correct lowering for operations (before they were supported enough to run tests without crashing, but still reasonably useful), but didn't really intend to check the calling convention with it. So this file could become target-agnostic and drop all types from `LABEL`, then add a separate test to check passing and returning.

Comment (RalfJung) [reply tests/codegen/float/f128.rs:67]: Our `PassMode` just lets us say "vector type of this size", we can't distinguish `<16 x i8>` from `<2 x i64>` from `<2 x f64>`. I guess we implicitly assume LLVM passes all of them the same way. So if that's not the case we have a more fundamental problem.

**Comment by RalfJung** [comment]
@bors r=workingjubilee p=1
(so many conflicts)

**Comment by RalfJung** [comment]
@bors r- retry
There's still something wrong with `tests/codegen/abi-x86-sse.rs`.

**Comment by RalfJung** [comment]
Okay, this should do it.
@bors r=workingjubilee

File: tests/assembly/closure-inherit-target-feature.rs (hunk 14 above)
Comment (RalfJung) [reply tests/assembly/closure-inherit-target-feature.rs:17]: Turns out on some targets this is still `call`. I guess I'll make it accept both and remove the `ret` check?

Comment (RalfJung) [reply tests/assembly/closure-inherit-target-feature.rs]: Actually I had a better idea: use an explicit return pointer to mimic the previously used ABI.

**Comment by workingjubilee** [comment]
lol LLVM

@bors r+
