### PR TITLE
Avoid calling `fn_sig` on closures

### LINKED ISSUE #68060: Another macro ICE
This code
```rust
fn calc(width: usize) -> Vec<usize> {
    (0..width)
        .map(
            #[target_feature(enable = "avx2")]
            |y| y,
        )
        .collect()
}

fn main() {
    println!("ICE {:?}", calc(8));
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17fc3bd5229c3a751497ef7c1ec23fb5))

Produces ICE on any channel
```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_typeck/collect.rs:1898: to get the signature of a closure, use `closure_sig()` not `fn_sig()`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:931:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0 (73528e339 2019-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `playground`.
```

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #68060

r? @petrochenkov

### CODE REVIEW

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -2877,9 +2877,16 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
         } else if attr.check_name(sym::thread_local) {
             codegen_fn_attrs.flags |= CodegenFnAttrFlags::THREAD_LOCAL;
         } else if attr.check_name(sym::track_caller) {
-            if tcx.fn_sig(id).abi() != abi::Abi::Rust {
-                struct_span_err!(tcx.sess, attr.span, E0737, "`#[track_caller]` requires Rust ABI")
+            if !tcx.is_closure(id) {
+                if tcx.fn_sig(id).abi() != abi::Abi::Rust {
```
Comment (petrochenkov) [inline src/librustc_typeck/collect.rs]: Closures are not `Abi::Rust`, so the error should likely be reported for them as well.

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -2898,13 +2905,15 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
...
         } else if attr.check_name(sym::target_feature) {
-            if tcx.fn_sig(id).unsafety() == Unsafety::Normal {
-                let msg = "`#[target_feature(..)]` can only be applied to `unsafe` functions";
-                tcx.sess
-                    .struct_span_err(attr.span, msg)
-                    .span_label(attr.span, "can only be applied to `unsafe` functions")
-                    .span_label(tcx.def_span(id), "not an `unsafe` function")
-                    .emit();
+            if !tcx.is_closure(id) {
+                if tcx.fn_sig(id).unsafety() == Unsafety::Normal {
```
Comment (petrochenkov) [inline src/librustc_typeck/collect.rs]: Closures are not `unsafe`, so the error should be reported for them as well.

File: src/librustc_typeck/collect.rs (hunk 1 above)
Comment (JohnTitor) [reply src/librustc_typeck/collect.rs]: Addressed.

File: src/librustc_typeck/collect.rs (hunk 2 above)
Comment (JohnTitor) [reply src/librustc_typeck/collect.rs]: Addressed as well.

File: src/test/compile-fail/issue-68060.rs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+#![feature(track_caller)]
```
Comment (petrochenkov) [inline src/test/compile-fail/issue-68060.rs]: Any specific reason to put this test into `compile-fail` instead of `ui`?
`compile-fail` is generally deprecated and only contains tests with not fully reproducible or heavily platform-specific output.

**Comment by petrochenkov** [comment]
r=me after moving the test to ui, if that's possible.

File: src/test/compile-fail/issue-68060.rs (hunk 3 above)
Comment (JohnTitor) [reply src/test/compile-fail/issue-68060.rs]: It requires _running_ test, not just checking to trigger ICE with `#[target_feature]`. I'm not familiar with running test with errors, any idea?

Comment (petrochenkov) [reply src/test/compile-fail/issue-68060.rs]: I don't understand, this particular test requires running or `ui` tests require running?

Comment (JohnTitor) [reply src/test/compile-fail/issue-68060.rs]: Ah sorry, this test requires running code.

Comment (petrochenkov) [reply src/test/compile-fail/issue-68060.rs]: Why?

Comment (JohnTitor) [reply src/test/compile-fail/issue-68060.rs]: To reproduce the ICE requires running code. build, check, or something doesn't show it, you can see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=54de2f854ac5cef143677ea3958047a1). I usually use `run-pass` for such this case but we cannot use here since the test has some errors. Also `run-fail` cannot be also used since the compilation will be failed. I confirmed the ICE isn't shown even without the fix when I place this test in `ui`. That's why I placed it in `compile-fail`. But I'm not familiar with ui-test fully so I may be missing something. Would you have any practice?

Comment (petrochenkov) [reply src/test/compile-fail/issue-68060.rs]: I'd recommend to trust playground less :)
Looks like it's actually doing `cargo check` on "Build".
Regular `rustc` produces an error when building this code.

UI tests also test in `check` mode by default, you have to add `// build-fail` to them to catch later codegen-time or link-time failures.

Comment (JohnTitor) [reply src/test/compile-fail/issue-68060.rs]: Oh, thanks! `build-fail` works well. Moved the test.
