### PR TITLE
Call FileEncoder::finish in rmeta encoding

### LINKED ISSUE #117254: FileEncoder delayed error reporting is still broken
https://github.com/rust-lang/rust/pull/94732 introduced a delayed error reporting scheme which was either buggy when it was merged or became buggy shortly after. The bug only surfaced as a variety of ICEs upon running out of disk space. In https://github.com/rust-lang/rust/pull/115542 I tried to fix the problem by simplifying FileEncoder so that it was harder to lose track of the delayed error.

But it looks like somehow this is still broken.

The failures I'm looking at are all in this crater run: https://github.com/rust-lang/rust/pull/104862#issuecomment-1776395116 and they all look like https://crater-reports.s3.amazonaws.com/pr-104862/master%237db4a89d49a8ed3a5f79b6cc3d555696baa1bbc3/gh/LooMaclin.test_kafka_musl/log.txt
```
[INFO] [stderr]    Compiling serde_json v1.0.39
[INFO] [stderr] thread 'rustc' panicked at /rustc/7db4a89d49a8ed3a5f79b6cc3d555696baa1bbc3/compiler/rustc_serialize/src/opaque.rs:233:42:
[INFO] [stderr] LLVM ERROR: IO failure on output stream: No space left on device
[INFO] [stderr] error: could not compile `serde` (lib)
```
We are ICEing in MemDecoder now. The delayed error reporting is supposed to report errors and halt the built when we try to finalize writing out the file where we ran into an issue, but it looks like that isn't happening. We're going ahead to decode a result which was not completely written out, and we try to access at an offset beyond the end of the mmap'd file.

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/117254

The bug here was that rmeta encoding never called FileEncoder::finish. Now it does. Most of the changes here are needed to support that, since rmeta encoding wants to finish _then_ access the File in the encoder, so finish can't move out.

I tried adding a `cfg(debug_assertions)` exploding Drop impl to FileEncoder that checked for finish being called before dropping, but fatal errors cause unwinding so this isn't really possible. If we encounter a fatal error with a dirty FileEncoder, the Drop impl ICEs even though the implementation is correct. If we try to paper over that by wrapping FileEncoder in ManuallyDrop then that just erases the fact that Drop automatically checks that we call finish on all paths.

I also changed the name of DepGraph::encode to DepGraph::finish_encoding, because that's what it does and it makes the fact that it is the path to FileEncoder::finish less confusing.

r? @WaffleLapkin

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
> I tried adding a cfg(debug_assertions) exploding Drop impl to FileEncoder that checked for finish being called before dropping, but fatal errors cause unwinding so this isn't really possible. If we encounter a fatal error with a dirty FileEncoder, the Drop impl ICEs even though the implementation is correct.

Can't we guard the assertion in Drop with [std::thread::panicking](https://doc.rust-lang.org/nightly/std/thread/fn.panicking.html), so that a fatal error just skips over the explosion?

**Comment by saethlin** [comment]
Yep I think that can be done. I'll push a change that does that in a bit.

File: compiler/rustc_interface/src/queries.rs [hunk 1]
```diff
@@ -347,6 +352,10 @@ impl Compiler {
                 .time("serialize_dep_graph", || gcx.enter(rustc_incremental::save_dep_graph));
         }
 
+        if let Err((path, error)) = queries.finish() {
+            self.session().emit_err(errors::FailedWritingFile { path: &path, error });
+        }
```
Comment (bjorn3) [inline compiler/rustc_interface/src/queries.rs:357]: Would it make sense to make `finish` consume `self` and bubble this down all the way into `DepGraph::finish_encoding()`? We shouldn't touch `GlobalCtxt` after `finish()`. This would require putting it in the context of the timer below, but would allow using `.time()` instead of `.timer()`.

Comment (saethlin) [reply compiler/rustc_interface/src/queries.rs]: I don't know. I need to steal anyway to access the DepGraph, so the move ends up being enforced at runtime anyway.

And I'm not sure how to make the code in rustc_interface work with the higher-ranked lifetime, but I think that's just because I've not used them before.

Comment (saethlin) [reply compiler/rustc_interface/src/queries.rs]: I've had no ideas on how to make this work, so I'm going to drop the commit.

**Review by WaffleLapkin — APPROVED** [review]

**Comment by WaffleLapkin** [comment]
r? WaffleLapkin
@bors r+

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 2]
```diff
@@ -2250,25 +2251,34 @@ fn encode_metadata_impl(tcx: TyCtxt<'_>, path: &Path) {
...
 
     // Encode the root position.
     let header = METADATA_HEADER.len();
-    file.seek(std::io::SeekFrom::Start(header as u64))
-        .unwrap_or_else(|err| tcx.sess.emit_fatal(FailSeekFile { err }));
-    let pos = root.position.get();
-    file.write_all(&[(pos >> 24) as u8, (pos >> 16) as u8, (pos >> 8) as u8, (pos >> 0) as u8])
-        .unwrap_or_else(|err| tcx.sess.emit_fatal(FailWriteFile { err }));
+    file.seek(std::io::SeekFrom::Start(header as u64))?;
+    file.write_all(&[(pos >> 24) as u8, (pos >> 16) as u8, (pos >> 8) as u8, (pos >> 0) as u8])?;
```
[the remark this answers is not in the document]
Comment (saethlin) [reply compiler/rustc_metadata/src/rmeta/encoder.rs:2277]: This code is very old. It could probably do with being totally rewritten, and I didn't even notice that this is another u32 position, ouch.
