### PR TITLE
Fix crate name validation

### LINKED ISSUE #122001: `#![crate_name = EXPR]` semantically allows `EXPR` to be a macro call but otherwise mostly ignores it
Contrary to `#![crate_type = EXPR]`, `#![crate_name = EXPR]` does **not** semantically reject *macro calls* inside `EXPR`.
Instead, it eagerly expands them but otherwise **ignores** the result (apart from errors).

~~I presume this regressed when #78835 (https://github.com/rust-lang/rust/labels/F-extended_key_value_attributes) was stabilized.
If so, this is a 1.53→1.54 stable-to-stable regression.~~
**Update**: It's a 1.75→1.76 stable-to-stable regression. Regressing PR: #117584.
Thanks ehuss, for the investigation! The result of the expansion used to be used!

### Examples

The following examples all pass compilation and rustc *completely* ignores the crate name that comes from the expansion. This can be observed by for example running `rustc file.rs --print=crate-name` prints `file` (the file name is assumed to be `file.rs`).

#### (A)

```rs
#![crate_name = concat!("alia", "s")] // ignored, crate name is `file`, not `alias`
fn main() {}
```

#### (B)

```rs
#![crate_name = include_str!("crate_name.txt")] // ignored, crate name is `file`, not `alias`
fn main() {}
```

where `crate_name.txt` exists and consists of `alias`.

#### (C)

```rs
#![crate_name = dep::generate!()] // ignored, crate name is `file`, not `alias`
fn main() {}
```

where we compile `file.rs` with `--extern=dep -L. --edition=2021` and where `dep.rs` is:

```rs
#[macro_export]
macro_rules! generate { () => { "alias" } }
```

### PR DESCRIPTION
**Pull request by fmease**
Reject macro calls inside attribute `#![crate_name]` like in `#![crate_name = concat!("na", "me")]`.

Prior to #117584, the result of the expansion (here: `"name"`) would actually be properly picked up by the compiler and used as the crate name. However since #117584 / on master, we extract the "value" (i.e., the *literal* string literal) of the `#![crate_name]` much earlier in the pipeline way before macro expansion and **skip**/**ignore** any `#![crate_name]`s "assigned to" a macro call. See also #122001.

T-lang has ruled to reject `#![crate_name = MACRO!(...)]` outright very similar to other built-in attributes whose value we need early like `#![crate_type]`. See accepted FCP: https://github.com/rust-lang/rust/issues/122001#issuecomment-2023203182.

Note that the check as implemented in this PR is even more "aggressive" compared to the one of `#![crate_type]` by running as early as possible in order to reject `#![crate_name = MACRO!(...)]` even in "non-normal" executions of `rustc`, namely on *print requests* (e.g., `--print=crate-name` and `--print=file-names`). If I were to move the validation step a bit further back close to the `#![crate_type]` one, `--print=crate-name` (etc.) would *not* exit fatally with an error in this kind of situation but happily report an incorrect crate name (i.e., the "crate name" as if `#![crate_name]` didn't exist / deduced from other sources like `--crate-name` or the file name) which would match the behavior on master. Again, see also #122001.

I'm mentioning this explicitly because I'm not sure if it was that clear in the FCP'ed issue. I argue that my current approach is the most reasonable one. I know (from reading the code and from past experiments) that various print requests are still quite broken (mostly lack of validation).

To the best of my knowledge, there's no print request whose output references/contains a crate *type*, so there's no "inherent need" to move `#![crate_type]`'s validation to happen earlier.

---

Fixes #122001.

https://github.com/rust-lang/rust/labels/relnotes: Compatibility. Breaking change.

### CODE REVIEW

File: compiler/rustc_interface/src/util.rs [hunk 1]
```diff
@@ -504,15 +513,14 @@ pub fn build_output_filenames(attrs: &[ast::Attribute], sess: &Session) -> Outpu
                 sess.dcx().emit_warn(errors::IgnoringOutDir);
             }
 
-            let out_filestem =
-                out_file.filestem().unwrap_or_default().to_str().unwrap().to_string();
+            let out_filestem = out_file.filestem().unwrap_or_default().to_str().unwrap();
             OutputFilenames::new(
                 out_file.parent().unwrap_or_else(|| Path::new("")).to_path_buf(),
-                crate_name.unwrap_or_else(|| out_filestem.replace('-', "_")),
+                crate_name,
```
Comment (fmease) [inline compiler/rustc_interface/src/util.rs:519]: Indeed, this is a change in behavior. On master, the "crate name" falls back to the file stem of the explicit outfile (`-o`) which is not correct (it doesn't agree with `tcx.crate_name(LOCAL_CRATE)`) (this happens since #114750). Note that this "crate name" is only used when emitting metadata files via `--emit=metadata` namely inside `libCRATE_NAME.rmeta`.

However, I couldn't actually come up with an actual reproducer as `--emit=metadata` doesn't actually emit anything if an `-o OUTPATH` is present **unless** an outpath was explicitly specified via `--emit=metadata=RMETA_OUTPATH`. So it might not be reachable at all and thus have no user-facing impact.

I don't know if `--emit=metadata -o OUTPATH` not emitting anything is intentional. Needs investigation (by me).

**Review by fmease — COMMENTED** [review]
[deleted]

File: compiler/rustc_interface/src/passes.rs [hunk 2]
```diff
@@ -1044,23 +1044,91 @@ pub(crate) fn start_codegen<'tcx>(
...
 }
+
+/// Validate *all* occurrences of the given "[value-str]" built-in attribute and return the first find.
+///
+/// This validator is intended for built-in attributes whose value needs to be known very early
+/// during compilation (namely, before macro expansion) and it mainly exists to reject macro calls
+/// inside of the attributes, such as in `#![name = expand!()]`. Normal attribute validation happens
+/// during semantic analysis via [`TyCtxt::check_mod_attrs`] which happens *after* macro expansion
+/// when such macro calls (here: `expand`) have already been expanded and we can no longer check for
+/// their presence.
```
Comment (fmease) [inline compiler/rustc_interface/src/passes.rs:1116]: and `span.from_expansion()` is not "reliable": `include_str!(…)` doesn't intro an expansion context for example.

**Comment by fmease** [comment]
I've finally added a PR description. Sorry about the delay ^^'.

**Review by wesleywiser — COMMENTED** [review]
Is the last commit still WIP?

**Comment by fmease** [comment]
> Is the last commit still WIP?

I've now dropped the WIP commit as I still need to investigate the implications of its changes. I'll submit it as a follow-up PR if everything works out.

I've adjusted the wording in the comment to no longer use the word 'currently'.

Ready for re-review. Nothing WIP left.

**Comment by fmease** [comment]
I've dropped the `tests/ui/{invalid-compile-flags → cli}/` change. See discussion in #133277.

File: compiler/rustc_interface/src/passes.rs [hunk 3]
```diff
@@ -1162,23 +1163,83 @@ pub(crate) fn start_codegen<'tcx>(
...
 
-fn get_recursion_limit(krate_attrs: &[ast::Attribute], sess: &Session) -> Limit {
-    if let Some(attr) = krate_attrs
-        .iter()
-        .find(|attr| attr.has_name(sym::recursion_limit) && attr.value_str().is_none())
+/// Compute and validate the crate name.
+pub fn get_crate_name(sess: &Session, krate_attrs: &[ast::Attribute]) -> Symbol {
+    // We unconditionally validate all `#![crate_name]`s even if a crate name was
+    // set on the command line via `--crate-name` which we prioritize over the
+    // crate attributes. We perform the validation here instead of later to ensure
```
Comment (bjorn3) [inline compiler/rustc_interface/src/passes.rs:1170]: `--crate-name` isn't prioritized. Rather it and `#![crate_name]` must match.

**Review by bjorn3 — APPROVED** [review]

**Comment by fmease** [comment]
I take the approval as an "r=me with nit addressed".
@bors r=bjorn3
