### PR TITLE
better error for bad depth parameter on macro metavar expr

### LINKED ISSUE #99060: Poor diagnostic: "length depth must be less than 0", but it mustn't
```rust
#![feature(macro_metavar_expr)]

macro_rules! metavar {
    ( $i:expr ) => {
        ${length(0)}
    };
}

const _: i32 = metavar!(0);
```

errors with:

```
error: length depth must be less than 0
 --> src/main.rs:5:10
  |
5 |         ${length(0)}
  |          ^^^^^^^^^^^
```

However, passing `-1` as the depth is rejected with:

```
error: meta-variable expression depth must be a literal
 --> src/main.rs:5:11
  |
5 |         ${length(-1)}
  |           ^^^^^^

error: expected expression, found `$`
  --> src/main.rs:5:9
   |
5  |         ${length(-1)}
   |         ^ expected expression
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #99060

### CODE REVIEW

File: src/test/ui/macros/meta-variable-depth-outside-repeat.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+#![feature(macro_metavar_expr)]
+
+macro_rules! metavar {
+    ( $i:expr ) => {
+        ${length(0)}
+        //~^ meta-variable expression `length` with depth parameter must be called inside of a macro repetition
```
Comment (petrochenkov) [inline src/test/ui/macros/meta-variable-depth-outside-repeat.rs:6]:
```suggestion
        //~^ ERROR meta-variable expression `length` with depth parameter must be called inside of a macro repetition
```
(We should remove support for "unelaborated" annotations like this from compiletest.)

File: compiler/rustc_expand/src/mbe/transcribe.rs [hunk 2]
```diff
@@ -512,7 +512,23 @@ fn out_of_bounds_err<'a>(
...
+        )
+    } else {
+        cx.struct_span_err(
+            span,
+            &format!(
+                "depth parameter on meta-variable expression `{ty}` \
+                 must be less than {max}"
+            ),
+        )
+    }
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/mbe/transcribe.rs:531]: Nit:
```rust
let msg = if max == 0 { format!("meta-variable ...") } else { format!("depth parameter") };
cx.struct_span_err(span, &msg);
```

**Comment by petrochenkov** [comment]
r=me after addressing the comments.
@rustbot author
