### PR TITLE
rustdoc: use import stability marker in display

### LINKED ISSUE #135078: rustdoc: "stable since" version is incorrect for std::ffi::CStr
Image
The documentation page for `std::ffi::CStr` says it was stabilized in 1.64.0, but it should say 1.0.0.

Applies to latest stable and nightly
https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html
https://doc.rust-lang.org/nightly/std/ffi/struct.CStr.html

This was correct back in 1.61.0
https://doc.rust-lang.org/1.61.0/std/ffi/struct.CStr.html

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #135078

### CODE REVIEW

File: tests/rustdoc/inline_local/staged-inline.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// https://github.com/rust-lang/rust/issues/135078
+#![crate_name = "foo"]
+#![feature(staged_api)]
+#![stable(feature = "v1", since="1.0.0")]
+
+#[stable(feature = "v1", since="1.0.0")]
+pub mod ffi {
+    #[stable(feature = "core_ffi", since="1.99.0")]
+    //@ matches "foo/ffi/struct.CStr.html" "//span[@class='sub-heading']/span[@class='since']" "1.99.0"
```
Comment (camelid) [inline tests/rustdoc/inline_local/staged-inline.rs:9]: Wouldn't it be better to use `has` here and below since `matches` treats the pattern as a regexp, and thus the dots in the version are not matched literally?

**Review by camelid — APPROVED** [review]
Thanks! r=me after addressing the comment on the test

**Review by camelid — APPROVED** [review]
LGTM, thanks. I do wonder whether there are cases opposite from what this fixes -- i.e. where the re-export stability is wrong and the original item is what we should use. I tested locally and found that `#[unstable]` on a re-export of a stable item is ignored by rustc.

But in the particular case this PR addresses, I think the new behavior overall makes more sense, so let's merge it.
