### PR TITLE
Fix race between block initialization and receiver disconnection

### LINKED ISSUE #121582: Occasional memory leak in mpsc channels
Running this test:
```rust
use std::sync::mpsc::channel;
use std::thread;

fn main() {
    let (tx, rx) = channel::<i32>();
    let _t = thread::spawn(move || {
        drop(rx);
    });
    let _ = thread::spawn(move || {
        tx.send(1).unwrap();
    })
    .join();
}
```
with many different seeds in Miri eventually shows:
```rust
error: memory leaked: alloc2567 (Rust heap, size: 504, align: 8), allocated here:
  --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/alloc.rs:98:9
   |
98 |         __rust_alloc(layout.size(), layout.align())
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: inside `std::alloc::alloc` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/alloc.rs:98:9: 98:52
   = note: inside `std::alloc::Global::alloc_impl` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/alloc.rs:181:73: 181:86
   = note: inside `<std::alloc::Global as std::alloc::Allocator>::allocate` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/alloc.rs:241:9: 241:39
   = note: inside `alloc::alloc::exchange_malloc` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/alloc.rs:330:11: 330:34
   = note: inside `std::boxed::Box::<std::sync::mpmc::list::Block<i32>>::new` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/boxed.rs:218:9: 218:20
   = note: inside `std::sync::mpmc::list::Channel::<i32>::start_send` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/mpmc/list.rs:209:41: 209:68
   = note: inside `std::sync::mpmc::list::Channel::<i32>::send` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/mpmc/list.rs:402:17: 402:39
   = note: inside `std::sync::mpmc::Sender::<i32>::send` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/mpmc/mod.rs:128:41: 128:61
   = note: inside `std::sync::mpsc::Sender::<i32>::send` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/mpsc/mod.rs:613:9: 613:27
note: inside closure
  --> leak.rs:10:9
   |
10 |         tx.send(1).unwrap();
   |         ^^^^^^^^^^
```
This indicates that the allocation made here does not get freed properly:
https://github.com/rust-lang/rust/blob/f0d487dce529d46ffe7925e9f8f0435781e49422/library/std/src/sync/mpmc/list.rs#L209

Specifically when running this with Miri 3fe10973bb6e9a01b280686534d0242da07f3ede, seed 139 causes the issue.

I don't think there is any way for this to be a false positive.

Cc @ibraheemdev @taiki-e @Amanieu

### PR DESCRIPTION
**Pull request by ibraheemdev**
Port of https://github.com/crossbeam-rs/crossbeam/pull/1084. Closes https://github.com/rust-lang/rust/issues/121582.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
The queue looks relatively light (once the current rollup is done) so I'll boost this one to the top

@bors r+ p=1

**Comment by klensy** [comment]
Needs beta backport?

File: library/std/src/sync/mpmc/list.rs [hunk 1]
```diff
@@ -547,7 +547,7 @@ impl<T> Channel<T> {
         }
 
         let mut head = self.head.index.load(Ordering::Acquire);
-        let mut block = self.head.block.load(Ordering::Acquire);
+        let mut block = self.head.block.swap(ptr::null_mut(), Ordering::AcqRel);
```
Comment (RalfJung) [inline library/std/src/sync/mpmc/list.rs:550]: Is this worth a comment explaining why the `swap` part is important?

Comment (ibraheemdev) [reply library/std/src/sync/mpmc/list.rs:550]: The problem with the separate load/store was not _that_ subtle, but a comment wouldn't hurt.

Comment (RalfJung) [reply library/std/src/sync/mpmc/list.rs:550]: Subtle enough that whoever wrote this code and the reviewer missed it. ;)

**Comment by m-ou-se** [comment]
We don't usually backport fixes for non-critical bugs that have already been around for a while on stable.

**Comment by m-ou-se** [comment]
We briefly discussed this in the libs team meeting. We didn't have consenesus on backporting this, due to the bug already being around for a long time on stable and the low severity of the bug (a memory leak).

File: library/std/src/sync/mpmc/list.rs (hunk 1 above)
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/list.rs:550]: Done https://github.com/rust-lang/rust/pull/121778.

**Comment by ibraheemdev** [comment]
The race occurs if the receiver half of an empty channel is dropped while a sender is trying to send, which is not very likely. I don't think this needs to be backported.
