### PR TITLE
Fix extra `non_snake_case` warning for shorthand field bindings

### LINKED ISSUE #89469: Extra `non_snake_case` warning when punning field name in pattern
Here's a minimized version of the code I'm working with:

```rust
#[derive(Clone, Copy)]
#[allow(non_snake_case)]
struct Entry {
    Δ: u16,
    _θ: u16,
    _μ: u8,
}

static TABLE: [Entry; 1] = [Entry { Δ: 0, _θ: 0, _μ: 0 }];

pub mod inner {
    pub fn f(k: usize) -> u16 {
        let super::Entry { Δ, _θ, _μ } = super::TABLE[k]; /* here */
        Δ
    }
}
```

Compiling this on stable or nightly gives a `non_snake_case` warning on the indicated line, despite the `allow(non_snake_case)` attribute on `struct Entry`. A similar issue was reported before in #66362, and addressed in a follow-up PR #66660, but it seems to be cropping up again here, maybe because a non-ASCII field name is involved. It was agreed in #66362 that punning of non-snake-case fields in patterns should not produce an additional warning, so I think this is a bona fide bug. (Incidentally, on stable the same warning appears twice in the compiler output, but this duplication seems to be fixed on nightly.)

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #89469. The problem is the innermost `if` condition here:
https://github.com/rust-lang/rust/blob/d14731cb3ced8318d7fc83cbe838f0e7f2fb3b40/compiler/rustc_lint/src/nonstandard_style.rs#L435-L452

This code runs for every `PatKind::Binding`, so if a struct has multiple fields, say A and B, and both are bound in a pattern using shorthands, the call to `self.check_snake_case()` will indeed be skipped in the `check_pat()` call for `A`; but when `check_pat()` is called for `B`, the loop will still iterate over `A`, and `field.ident (= A) != ident (= B)` will be true. I have fixed this by only looking at non-shorthand bindings, and only the binding that `check_pat()` was actually called for.

### CODE REVIEW

File: compiler/rustc_lint/src/nonstandard_style.rs [hunk 1]
```diff
@@ -437,12 +437,14 @@ impl<'tcx> LateLintPass<'tcx> for NonSnakeCase {
...
-                    for field in field_pats.iter() {
-                        if field.ident != ident {
-                            // Only check if a new name has been introduced, to avoid warning
-                            // on both the struct definition and this pattern.
-                            self.check_snake_case(cx, "variable", &ident);
-                        }
+                    if field_pats
+                        .iter()
+                        .find(|field| !field.is_shorthand && field.pat.hir_id == p.hir_id)
+                        .is_some()
```
Comment (cole-miller) [inline compiler/rustc_lint/src/nonstandard_style.rs:443]: This could be `.any(|field| !field.is_shorthand && field.pat.hir_id == p.hir_id)`
