### PR TITLE
Type-directed probing for inherent associated types

### LINKED ISSUE #104251: Inherent associated type projection does not respect `where` clauses
I tried this code:

```rust
#![feature(inherent_associated_types)]

struct Foo<T: ?Sized>(T);

impl<T> Foo<T> {
    type Bar = i32;
}

fn main() {
    let x: Foo<[u8]>::Bar = 1;
}
```

I expected to see it fail, since while `Foo<[u8]>` is WF, it does not satisfy the where-clauses of the `impl` that it's selecting the associated type `Bar` from.

### LINKED ISSUE #105305: type parameter `T/#1` (T/1) out of range when substituting, substs=[()]
### Code

```Rust
#![feature(inherent_associated_types)]
#![allow(incomplete_features)]

struct S<T>(T);

impl<T, 'a> S<T> { // Also repros with any other lifetimes such as '_  ,switching order to 'a, T also repros.
    type P = T;
}

fn main() {
    type A = S<()>::P;
}
```

Found by mutating #104240.
Seemingly the same ICE msg. 
CC @cjgillot

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (53e4b9dd7 2022-12-04)
binary: rustc
commit-hash: 53e4b9dd74c29cc9308b8d0f10facac70bb101a7
commit-date: 2022-12-04
host: x86_64-pc-windows-msvc
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

```
error: lifetime parameters must be declared prior to type and const parameters

error: internal compiler error: compiler\rustc_middle\src\ty\subst.rs:810:9: type parameter `T/#1` (T/1) out of range when substituting, substs=[()]
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: lifetime parameters must be declared prior to type and const parameters
 --> src\main.rs:6:9
  |
6 | impl<T, 'a> S<T> {
  |     ----^^- help: reorder the parameters: lifetimes, then consts and types: `<'a, T>`

error: internal compiler error: compiler\rustc_middle\src\ty\subst.rs:810:9: type parameter `T/#1` (T/1) out of range when substituting, substs=[()]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/53e4b9dd74c29cc9308b8d0f10facac70bb101a7\compiler\rustc_errors\src\lib.rs:1576:9
stack backtrace:
   0:     0x7ffd384e9e42 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7e70883c575183bf
   1:     0x7ffd3852615b - core::fmt::write::h33a76bcc6f834c12
   2:     0x7ffd384dca6a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::he6739634bf80651d
   3:     0x7ffd384e9b8b - std::sys::common::alloc::realloc_fallback::h79800d247b25f9cf
   4:     0x7ffd384ed4b9 - std::panicking::default_hook::hf73f2b3eda2ba841
   5:     0x7ffd384ed13b - std::panicking::default_hook::hf73f2b3eda2ba841
   6:     0x7ffcaaf7c72d - rustc_driver[6fdaf07c6b144b62]::describe_lints
   7:     0x7ffd384ede20 - std::panicking::rust_panic_with_hook::h026ab977c6c77b06
   8:     0x7ffcad304063 - <rustc_middle[d0f48cd9e4ec2207]::ty::query::ExternProviders as core[d9f7351a480f3995]::clone::Clone>::clone
   9:     0x7ffcad300a39 - <rustc_middle[d0f48cd9e4ec2207]::ty::query::ExternProviders as core[d9f7351a480f3995]::clone::Clone>::clone
  10:     0x7ffcad2bb7c9 - <rustc_middle[d0f48cd9e4ec2207]::ty::sty::ExistentialProjection as rustc_middle[d0f48cd9e4ec2207]::ty::context::Lift>::lift_to_tcx
  11:     0x7ffcad2d0fe9 - <rustc_middle[d0f48cd9e4ec2207]::ty::instance::InstanceDef as rustc_middle[d0f48cd9e4ec2207]::ty::context::Lift>::lift_to_tcx
  12:     0x7ffcad2ce080 - <rustc_middle[d0f48cd9e4ec2207]::ty::instance::InstanceDef as rustc_middle[d0f48cd9e4ec2207]::ty::context::Lift>::lift_to_tcx
  13:     0x7ffcad2cdb72 - <rustc_middle[d0f48cd9e4ec2207]::ty::instance::InstanceDef as rustc_middle[d0f48cd9e4ec2207]::ty::context::Lift>::lift_to_tcx
  14:     0x7ffcad2ad8c8 - <rustc_middle[d0f48cd9e4ec2207]::ty::sty::Binder<rustc_middle[d0f48cd9e4ec2207]::ty::TraitPredicate>>::print_modifiers_and_trait_path
  15:     0x7ffcad2af5b8 - rustc_middle[d0f48cd9e4ec2207]::util::bug::bug_fmt
  16:     0x7ffcad2af535 - rustc_middle[d0f48cd9e4ec2207]::util::bug::bug_fmt
  17:     0x7ffcad30ca6f - <rustc_middle[d0f48cd9e4ec2207]::ty::list::List<rustc_middle[d0f48cd9e4ec2207]::ty::subst::GenericArg>>::try_as_type_list
  18:     0x7ffcaae61bee - <rustc_middle[d0f48cd9e4ec2207]::ty::subst::SubstFolder as rustc_middle[d0f48cd9e4ec2207]::ty::fold::TypeFolder>::fold_ty
  19:     0x7ffcaa202ce8 - <dyn rustc_hir_analysis[e14abbd9f0df36ca]::astconv::AstConv>::ast_region_to_region
  20:     0x7ffcaa20a396 - <dyn rustc_hir_analysis[e14abbd9f0df36ca]::astconv::AstConv>::ast_region_to_region
  21:     0x7ffcaa218816 - <dyn rustc_hir_analysis[e14abbd9f0df36ca]::astconv::AstConv>::ty_of_fn
  22:     0x7ffcaa8e9c28 - <rustc_span[395f7c3a127106b9]::symbol::Symbol as rustc_serialize[99e1dbb5522d458d]::serialize::Encodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheEncoder>>::encode
  23:     0x7ffcaa9c39fc - <rustc_span[395f7c3a127106b9]::symbol::Symbol as rustc_serialize[99e1dbb5522d458d]::serialize::Encodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheEncoder>>::encode
  24:     0x7ffcaa2344bd - <rustc_hir_analysis[e14abbd9f0df36ca]::collect::ItemCtxt as rustc_hir_analysis[e14abbd9f0df36ca]::astconv::AstConv>::normalize_ty
  25:     0x7ffcaa255646 - rustc_hir_analysis[e14abbd9f0df36ca]::check::fn_maybe_err
  26:     0x7ffca8ebbe91 - <rustc_hir_analysis[e14abbd9f0df36ca]::check::intrinsicck::InlineAsmCtxt>::check_asm
  27:     0x7ffca9149a89 - <rustc_const_eval[cb9b3011c5bf7f16]::transform::check_consts::resolver::State as core[d9f7351a480f3995]::clone::Clone>::clone_from
  28:     0x7ffca91d3e75 - <&[(rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::ExportedSymbol, rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[99e1dbb5522d458d]::serialize::Decodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheDecoder>>::decode
  29:     0x7ffcaa9713fd - <rustc_span[395f7c3a127106b9]::symbol::Symbol as rustc_serialize[99e1dbb5522d458d]::serialize::Encodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheEncoder>>::encode
  30:     0x7ffca9325952 - <&[(rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::ExportedSymbol, rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[99e1dbb5522d458d]::serialize::Decodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ffca8ec8850 - <rustc_hir_analysis[e14abbd9f0df36ca]::check::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as rustc_middle[d0f48cd9e4ec2207]::ty::visit::TypeVisitor>::visit_ty
  32:     0x7ffca8ea2da5 - <<dyn rustc_hir_analysis[e14abbd9f0df36ca]::astconv::AstConv>::create_substs_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[e14abbd9f0df36ca]::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind
  33:     0x7ffca8e96703 - rustc_hir_analysis[e14abbd9f0df36ca]::check_crate
  34:     0x7ffca8767f65 - rustc_interface[9a86922769a86bfa]::passes::analysis
  35:     0x7ffca914c45f - <rustc_const_eval[cb9b3011c5bf7f16]::transform::check_consts::resolver::State as core[d9f7351a480f3995]::clone::Clone>::clone_from
  36:     0x7ffca91f2139 - <&[(rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::ExportedSymbol, rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[99e1dbb5522d458d]::serialize::Decodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7ffca92a1c52 - <&[(rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::ExportedSymbol, rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[99e1dbb5522d458d]::serialize::Decodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheDecoder>>::decode
  38:     0x7ffca932af3f - <&[(rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::ExportedSymbol, rustc_middle[d0f48cd9e4ec2207]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[99e1dbb5522d458d]::serialize::Decodable<rustc_query_impl[2fbc64f93e3032cd]::on_disk_cache::CacheDecoder>>::decode
  39:     0x7ffca872be44 - <unknown>
  40:     0x7ffca873cb96 - <rustc_middle[d0f48cd9e4ec2207]::ty::SymbolName as core[d9f7351a480f3995]::fmt::Display>::fmt
  41:     0x7ffca873be98 - rustc_driver[6fdaf07c6b144b62]::args::arg_expand_all
  42:     0x7ffca872cdb9 - <unknown>
  43:     0x7ffca8723e9d - <unknown>
  44:     0x7ffd385001ac - std::sys::windows::thread::Thread::new::hc3d1b043254b2748
  45:     0x7ffd9f2554e0 - BaseThreadInitThunk
  46:     0x7ffda0be485b - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (53e4b9dd7 2022-12-04) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] expanding type alias `main::A`
#1 [collect_mod_item_types] collecting item types in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `rust_test` due to previous error
```

</p>
</details>

### LINKED ISSUE #107468: Inherent associated type projections are incorrectly substituted
The following code should compile since for `Subj<(i32,)>` one has `T == i32` and thus `Subj::Un == i32`. However, the current implementation incorrectly substitutes `T` with `(i32,)` leading to a compile error after encountering the let-statement.

```rust
#![feature(inherent_associated_types)]
#![allow(incomplete_features)]

struct Subj<T>(T);

impl<T> Subj<(T,)> {
    type Un = T;
}

fn main() {
    let _: Subj::<(i32,)>::Un = 0i32;
}
```

```
error[E0308]: mismatched types
  --> src/main.rs:11:33
   |
11 |     let _: Subj::<(i32,)>::Un = 0i32;
   |            ------------------   ^^^^ expected tuple, found `i32`
   |            |
   |            expected due to this
   |
   = note: expected tuple `(i32,)`
               found type `i32`
help: use a trailing comma to create a tuple with one element
   |
11 |     let _: Subj::<(i32,)>::Un = (0i32,);
   |                                 +    ++
```

---

For comparison, the analogous program involving inherent associated *functions* successfully compiles:

```rust
struct Subj<T>(T);

impl<T: Default> Subj<(T,)> {
    fn un() -> T { T::default() }
}

fn main() {
    let _: i32 = Subj::<(i32,)>::un();
}
```

@rustbot label T-compiler requires-nightly F-inherent_associated_types
@rustbot claim

### PR DESCRIPTION
**Pull request by fmease**
When probing for inherent associated types (IATs), equate the Self-type found in the projection with the Self-type of the relevant inherent impl blocks and check if all predicates are satisfied.
Previously, we didn't look at the Self-type or at the bounds and just picked the first inherent impl block containing an associated type with the name we were searching for which is obviously incorrect.

Regarding the implementation, I basically copied what we do during method probing (`assemble_inherent_impl_probe`, `consider_probe`). Unfortunately, I had to duplicate a lot of the diagnostic code found in `rustc_hir_typeck::method::suggest` which we don't have access to in `rustc_hir_analysis`. Not sure if there is a simple way to unify the error handling. Note that in the future, `rustc_hir_analysis::astconv` might not actually be the place where we resolve inherent associated types (see https://github.com/rust-lang/rust/pull/103621#issuecomment-1304309565) but `rustc_hir_typeck` (?) in which case the duplication may naturally just disappear. While inherent associated *constants* are currently resolved during "method" probing, I did not find a straightforward way to incorporate IAT lookup into it as types and values (functions & constants) are two separate entities for which distinct code paths are taken.

Fixes #104251 (incl. https://github.com/rust-lang/rust/issues/104251#issuecomment-1338501171).
Fixes #105305.
Fixes #107468.

@rustbot label T-types F-inherent_associated_types
r? types

### CODE REVIEW

**Comment by fmease** [comment]
> Unfortunately, I had to duplicate a lot of the diagnostic code found in rustc_hir_typeck::method::suggest which we don't have access to in rustc_hir_analysis. Not sure if there is a simple way to unify the error handling. 

One makeshift solution I am thinking of is to make the subset of the error handling code that I need public definitions in `rustc_hir_analysis` and use it from `rustc_hir_typeck` to get rid of the duplication.

**Comment by jackh726** [comment]
Sorry for the delay here @fmease. I plan on getting to this by the end of the week.

**Comment by fmease** [comment]
No worries :) Thanks in advance!

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 1]
```diff
@@ -2098,15 +2095,157 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            let impl_ty = impl_ty.subst(tcx, impl_substs);
+
+            let InferOk { value: impl_ty, obligations } =
+                infcx.at(&cause, param_env).normalize(impl_ty);
+
+            // Check that the Self-types can be related.
+            let Ok(InferOk { obligations: sub_obligations, value: () }) = infcx
+                .at(&ObligationCause::dummy(), param_env)
+                .define_opaque_types(false)
+                .sup(impl_ty, self_ty)
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2137]: Does method selection use `sup`? We probably should use `eq` here, since that's what [`match_impl`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_trait_selection/traits/select/mod.rs.html#2406) does.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 2]
```diff
@@ -2098,15 +2095,157 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            let ty::Adt(_, adt_substs) = self_ty.kind() else {
+                // FIXME(inherent_associated_types)
+                bug!("unimplemented: non-adt self of inherent assoc ty");
+            };
+
+            let item_substs =
+                self.create_substs_for_associated_item(span, assoc_item, segment, adt_substs);
+            // FIXME(inherent_associated_types): Check if the obligations arising from the
+            // where-clause & the bounds on the associated type and its parameters hold.
+            let ty = tcx.bound_type_of(assoc_item).subst(tcx, item_substs);
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2191]: I wonder if astconv should turn this into a `ty::Projection` with the impl item def id, then let normalization handle projecting it onto the real type and confirming the GAT substitutions. It would fix this comment:

> Check if the obligations arising from the where-clause & the bounds on the associated type and its parameters hold.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2137]: Well, method *probing* does use `sup` but tbh I am not sure why exactly since it is `.ignoring_regions()`, too, and lifetime subtyping is the only subtyping in Rust's type system. I can definitely switch to `eq` but I wish I could understand for what deeper reason the probing code uses `sup`.

https://github.com/rust-lang/rust/blob/222d1ff68d5bfe1dc2d7f3f0c42811fe12964af9/compiler/rustc_hir_typeck/src/method/probe.rs#L1516

You likely know the following, I am just making sure I understand correctly. As far as I know method probing ignores regions since implementation-wise it uses `FnCtxt` which stores [`Inherited`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/struct.Inherited.html) whose only public ctor [`Inherited::build`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/struct.Inherited.html#method.build) constructs an `InferCtxt` `.ignoring_regions()` and since specification-wise regions are erased before codegen and they should matter for method dispatch.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 2 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2191]: That FIXME now has its own issue btw, namely #106722, and I can *try* to implement it returning a type of kind `TyKind::Alias(AliasKind::Projection, AliasTy { … })`. I faintly remember trying this before and it lead to ICEs down the line where the compiler wasn't happy that *inherent* assoc ty projections obviously lacked a trait reference. The docs of [`AliasTy.def_id`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.AliasTy.html#structfield.def_id) kind of confirm this: “The `DefId` of the `TraitItem` […] if this is a projection”. Let's see if I can find another way. I wonder if rust-lang/compiler-team#504 is relevant here.

Should I attempt this in this PR though, I wonder? I want to keep things “minimal” to make life easier for reviewers and since I don't even know if the general disposition for this PR is merging or closing as the implementation is not quite clean yet.

Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2191]: Do you think we are in need of a new `AliasKind::InherentProjection` (modulo naming)? I am not deeply familiar with the inner workings of the type system yet but as far as I understand at some point in the future we do need to map polymorphic *inherent* associated types to *placeholder projection types* for lazy normalization (?) & generally proper unification for IATs and to finally pave the way for their long-awaited stabilization. Do I get that right?

Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2326]: > Do you think we are in need of a new AliasKind::InherentProjection (modulo naming)?

I am currently investigating this approach.

File: tests/ui/associated-inherent-types/dispatch-on-self-type-0.rs [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+impl Choose<NonCopy> {
+    type Result = ();
+}
+
+fn main() {
+    let _: Select<String>::Projection = false;
+    let _: Select<u8>::Projection = ();
+
+    let _: Choose<NonCopy>::Result = ();
+    let _: Choose<&str>::Result = vec!["..."];
```
Comment (jackh726) [inline tests/ui/associated-inherent-types/dispatch-on-self-type-0.rs:34]: For followup work: it would be nice to see tests where we don't have a concrete type, but instead something from the environment.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 4]
```diff
@@ -2234,15 +2230,157 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            return Ok(Some((ty, assoc_item)));
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2327]: So, the problem here: what if multiple candidates may hold? This means we're just picking the first.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 5]
```diff
@@ -2234,15 +2230,157 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            }
+
+            // Evaluate those obligations to see if they might possibly hold.
+            for o in sub_obligations {
+                let o = infcx.resolve_vars_if_possible(o);
+                if !infcx.predicate_may_hold(&o) {
+                    matches = false;
+                    unsatisfied_predicates.push(o.predicate);
+                }
+            }
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2309]: I imagine it might make more sense to use an `ObligationCtxt` here. Just register all the obligations and then call `select_where_possible` (maybe? would have to think a bit harder about it).

Comment (jackh726) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2309]: It also has helpful operations for the some of the above.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 6]
```diff
@@ -2234,15 +2230,157 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            return Ok(Some((ty, assoc_item)));
+        }
+
+        Err(self.complain_about_inherent_assoc_type_not_found(
+            name,
+            self_ty,
+            &candidates.into_iter().map(|(impl_, _)| impl_).collect::<Vec<_>>(),
+            unsatisfied_predicates,
+            span,
+        ))
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2336]: Is it helpful to combine all unsatisfied predicates?

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 2 above)
Comment (jackh726) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2326]: I think this would be good as a followup.

**Review by jackh726 — CHANGES_REQUESTED** [review]
Sorry that this has taken so long :/

I think my comments here could be added as FIXMEs and we could land this mostly as-is. But of course, address as much as you'd like/can.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 1 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2272]: If I replace `.sup` with `.eq` here, it ices.

<details><summary>backtrace</summary>

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/rustc_infer/src/infer/region_constraints/mod.rs:459:9
stack backtrace:
   0:     0x7f6d278ebac1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hef7c34ced48956ed
   1:     0x7f6d27967fbe - core::fmt::write::hd6821393d61dbc78
   2:     0x7f6d27910171 - std::io::Write::write_fmt::h0aae2c130bb43485
   3:     0x7f6d278eb8ea - std::sys_common::backtrace::print::hefc1376ab8e30bd1
   4:     0x7f6d278eca67 - std::panicking::default_hook::{{closure}}::h133538e0d38da3d4
   5:     0x7f6d278ec895 - std::panicking::default_hook::h0f8bde92f9834261
   6:     0x7f6d282873c5 - rustc_driver[748794e2e144500f]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:     0x7f6d278ecf73 - std::panicking::rust_panic_with_hook::h6563697fa9ccd808
   8:     0x7f6d278e3089 - std::panicking::begin_panic_handler::{{closure}}::ha90000309b42d4bb
   9:     0x7f6d278e2fbc - std::sys_common::backtrace::__rust_end_short_backtrace::h13266d7b6e524bca
  10:     0x7f6d278ecb3a - rust_begin_unwind
  11:     0x7f6d278ca4e3 - core::panicking::panic_fmt::hee5867c2cd98c87f
  12:     0x7f6d278ca652 - core::panicking::panic_bounds_check::h879d026d129b4b6a
  13:     0x7f6d2a4d1938 - <rustc_infer[c33f17b4b4dc7e29]::infer::region_constraints::RegionConstraintCollector>::universe
  14:     0x7f6d2a5032bb - <rustc_infer[c33f17b4b4dc7e29]::infer::InferCtxt>::universe_of_region
  15:     0x7f6d2a43394a - <rustc_infer[c33f17b4b4dc7e29]::infer::combine::Generalizer as rustc_middle[e87e357ae1384561]::ty::relate::TypeRelation>::regions
  16:     0x7f6d2a43bca2 - rustc_middle[e87e357ae1384561]::ty::relate::super_relate_tys::<rustc_infer[c33f17b4b4dc7e29]::infer::combine::Generalizer>
  17:     0x7f6d2a4330cd - <rustc_infer[c33f17b4b4dc7e29]::infer::combine::Generalizer as rustc_middle[e87e357ae1384561]::ty::relate::TypeRelation>::tys
  18:     0x7f6d2a434592 - <rustc_infer[c33f17b4b4dc7e29]::infer::combine::CombineFields>::instantiate
  19:     0x7f6d2a47c80f - <rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate as rustc_middle[e87e357ae1384561]::ty::relate::TypeRelation>::tys
  20:     0x7f6d2a5511f6 - <rustc_middle[e87e357ae1384561]::ty::subst::GenericArg as rustc_middle[e87e357ae1384561]::ty::relate::Relate>::relate::<rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate>
  21:     0x7f6d2a57204c - <core[a759e9f1dec68147]::result::Result<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg, rustc_middle[e87e357ae1384561]::ty::error::TypeError> as rustc_type_ir[98cc6c8502f90b82]::InternIteratorElement<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg, &rustc_middle[e87e357ae1384561]::ty::list::List<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg>>>::intern_with::<core[a759e9f1dec68147]::iter::adapters::map::Map<core[a759e9f1dec68147]::iter::adapters::zip::Zip<core[a759e9f1dec68147]::iter::adapters::copied::Copied<core[a759e9f1dec68147]::slice::iter::Iter<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg>>, core[a759e9f1dec68147]::iter::adapters::copied::Copied<core[a759e9f1dec68147]::slice::iter::Iter<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg>>>, rustc_middle[e87e357ae1384561]::ty::relate::relate_substs<rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate>::{closure#0}>, <rustc_middle[e87e357ae1384561]::ty::context::TyCtxt>::mk_substs<core[a759e9f1dec68147]::iter::adapters::map::Map<core[a759e9f1dec68147]::iter::adapters::zip::Zip<core[a759e9f1dec68147]::iter::adapters::copied::Copied<core[a759e9f1dec68147]::slice::iter::Iter<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg>>, core[a759e9f1dec68147]::iter::adapters::copied::Copied<core[a759e9f1dec68147]::slice::iter::Iter<rustc_middle[e87e357ae1384561]::ty::subst::GenericArg>>>, rustc_middle[e87e357ae1384561]::ty::relate::relate_substs<rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate>::{closure#0}>>::{closure#0}>
  22:     0x7f6d2a47bac6 - <rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate as rustc_middle[e87e357ae1384561]::ty::relate::TypeRelation>::relate_item_substs
  23:     0x7f6d2a43af43 - rustc_middle[e87e357ae1384561]::ty::relate::super_relate_tys::<rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate>
  24:     0x7f6d2a510fc6 - <rustc_infer[c33f17b4b4dc7e29]::infer::InferCtxt>::super_combine_tys::<rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate>
  25:     0x7f6d2a47c5ce - <rustc_infer[c33f17b4b4dc7e29]::infer::equate::Equate as rustc_middle[e87e357ae1384561]::ty::relate::TypeRelation>::tys
  26:     0x7f6d2889837a - <rustc_infer[c33f17b4b4dc7e29]::infer::InferCtxt>::commit_if_ok::<rustc_infer[c33f17b4b4dc7e29]::infer::InferOk<()>, rustc_middle[e87e357ae1384561]::ty::error::TypeError, <rustc_infer[c33f17b4b4dc7e29]::infer::at::Trace>::eq<rustc_middle[e87e357ae1384561]::ty::Ty>::{closure#0}>
  27:     0x7f6d289d2db1 - <rustc_infer[c33f17b4b4dc7e29]::infer::at::At>::eq::<rustc_middle[e87e357ae1384561]::ty::Ty>
  28:     0x7f6d2894a509 - <dyn rustc_hir_analysis[2dedc18b32354586]::astconv::AstConv>::associated_path_to_ty::{closure#0}
  29:     0x7f6d289499fa - <dyn rustc_hir_analysis[2dedc18b32354586]::astconv::AstConv>::associated_path_to_ty
  30:     0x7f6d2894e1e8 - <dyn rustc_hir_analysis[2dedc18b32354586]::astconv::AstConv>::ast_ty_to_ty_inner
  31:     0x7f6d28657fcf - <rustc_hir_typeck[5384bad6713105a9]::fn_ctxt::FnCtxt>::to_ty
  32:     0x7f6d285febcf - <rustc_hir_typeck[5384bad6713105a9]::gather_locals::GatherLocalsVisitor>::declare
  33:     0x7f6d287c41b3 - rustc_hir[cf8f75e2b7a3e0eb]::intravisit::walk_block::<rustc_hir_typeck[5384bad6713105a9]::gather_locals::GatherLocalsVisitor>
  34:     0x7f6d286ec69d - rustc_hir_typeck[5384bad6713105a9]::check::check_fn
  35:     0x7f6d286d9dac - <rustc_hir_typeck[5384bad6713105a9]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[5384bad6713105a9]::typeck_with_fallback<rustc_hir_typeck[5384bad6713105a9]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[e87e357ae1384561]::ty::typeck_results::TypeckResults>
  36:     0x7f6d2881336a - rustc_hir_typeck[5384bad6713105a9]::typeck_with_fallback::<rustc_hir_typeck[5384bad6713105a9]::typeck::{closure#0}>
  37:     0x7f6d287399a4 - rustc_hir_typeck[5384bad6713105a9]::typeck
  38:     0x7f6d299a66f4 - rustc_query_system[a641d3afe2b8834a]::query::plumbing::try_execute_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::typeck, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt>
  39:     0x7f6d29a41b20 - rustc_query_system[a641d3afe2b8834a]::query::plumbing::get_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::typeck, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt, rustc_middle[e87e357ae1384561]::dep_graph::dep_node::DepKind>
  40:     0x7f6d297542c8 - <rustc_query_impl[2d661b98ef5c64e8]::Queries as rustc_middle[e87e357ae1384561]::ty::query::QueryEngine>::typeck
  41:     0x7f6d2877c016 - std[6161937930c6e443]::panicking::try::<(), core[a759e9f1dec68147]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[ad989cddaa07d642]::sync::par_for_each_in<&[rustc_span[67e7a4497f54abf5]::def_id::LocalDefId], <rustc_middle[e87e357ae1384561]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5384bad6713105a9]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  42:     0x7f6d28811395 - rustc_data_structures[ad989cddaa07d642]::sync::par_for_each_in::<&[rustc_span[67e7a4497f54abf5]::def_id::LocalDefId], <rustc_middle[e87e357ae1384561]::hir::map::Map>::par_body_owners<rustc_hir_typeck[5384bad6713105a9]::typeck_item_bodies::{closure#0}>::{closure#0}>
  43:     0x7f6d28739865 - rustc_hir_typeck[5384bad6713105a9]::typeck_item_bodies
  44:     0x7f6d2996323a - rustc_query_system[a641d3afe2b8834a]::query::plumbing::try_execute_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::typeck_item_bodies, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt>
  45:     0x7f6d29a141ef - rustc_query_system[a641d3afe2b8834a]::query::plumbing::get_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::typeck_item_bodies, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt, rustc_middle[e87e357ae1384561]::dep_graph::dep_node::DepKind>
  46:     0x7f6d29753d8e - <rustc_query_impl[2d661b98ef5c64e8]::Queries as rustc_middle[e87e357ae1384561]::ty::query::QueryEngine>::typeck_item_bodies
  47:     0x7f6d2892e4e8 - <rustc_session[29c6e5af3d515c5e]::session::Session>::time::<(), rustc_hir_analysis[2dedc18b32354586]::check_crate::{closure#7}>
  48:     0x7f6d2889bdae - rustc_hir_analysis[2dedc18b32354586]::check_crate
  49:     0x7f6d283c6e52 - rustc_interface[e7497e78aff66ef4]::passes::analysis
  50:     0x7f6d299a87ca - rustc_query_system[a641d3afe2b8834a]::query::plumbing::try_execute_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::analysis, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt>
  51:     0x7f6d29a41db1 - rustc_query_system[a641d3afe2b8834a]::query::plumbing::get_query::<rustc_query_impl[2d661b98ef5c64e8]::queries::analysis, rustc_query_impl[2d661b98ef5c64e8]::plumbing::QueryCtxt, rustc_middle[e87e357ae1384561]::dep_graph::dep_node::DepKind>
  52:     0x7f6d29735a5e - <rustc_query_impl[2d661b98ef5c64e8]::Queries as rustc_middle[e87e357ae1384561]::ty::query::QueryEngine>::analysis
  53:     0x7f6d2828fb05 - <rustc_interface[e7497e78aff66ef4]::passes::QueryContext>::enter::<rustc_driver[748794e2e144500f]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>
  54:     0x7f6d2829103c - <rustc_interface[e7497e78aff66ef4]::interface::Compiler>::enter::<rustc_driver[748794e2e144500f]::run_compiler::{closure#1}::{closure#2}, core[a759e9f1dec68147]::result::Result<core[a759e9f1dec68147]::option::Option<rustc_interface[e7497e78aff66ef4]::queries::Linker>, rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>
  55:     0x7f6d2826f966 - rustc_span[67e7a4497f54abf5]::with_source_map::<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_interface[e7497e78aff66ef4]::interface::run_compiler<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_driver[748794e2e144500f]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  56:     0x7f6d282933fc - <scoped_tls[535ca24a62cbd8c4]::ScopedKey<rustc_span[67e7a4497f54abf5]::SessionGlobals>>::set::<rustc_interface[e7497e78aff66ef4]::interface::run_compiler<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_driver[748794e2e144500f]::run_compiler::{closure#1}>::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>
  57:     0x7f6d2827c1aa - std[6161937930c6e443]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e7497e78aff66ef4]::util::run_in_thread_pool_with_globals<rustc_interface[e7497e78aff66ef4]::interface::run_compiler<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_driver[748794e2e144500f]::run_compiler::{closure#1}>::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>
  58:     0x7f6d282976ee - std[6161937930c6e443]::panicking::try::<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, core[a759e9f1dec68147]::panic::unwind_safe::AssertUnwindSafe<<std[6161937930c6e443]::thread::Builder>::spawn_unchecked_<rustc_interface[e7497e78aff66ef4]::util::run_in_thread_pool_with_globals<rustc_interface[e7497e78aff66ef4]::interface::run_compiler<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_driver[748794e2e144500f]::run_compiler::{closure#1}>::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
  59:     0x7f6d2828c646 - <<std[6161937930c6e443]::thread::Builder>::spawn_unchecked_<rustc_interface[e7497e78aff66ef4]::util::run_in_thread_pool_with_globals<rustc_interface[e7497e78aff66ef4]::interface::run_compiler<core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>, rustc_driver[748794e2e144500f]::run_compiler::{closure#1}>::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a759e9f1dec68147]::result::Result<(), rustc_errors[aafc41f3c6a3f30f]::ErrorGuaranteed>>::{closure#1} as core[a759e9f1dec68147]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  60:     0x7f6d279038b8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfe0a9abdbb746703
  61:     0x7f6d278f1877 - std::sys::unix::thread::Thread::new::thread_start::h84bfc89499a70691
  62:     0x7f6d276f78fd - <unknown>
  63:     0x7f6d27779a60 - <unknown>
  64:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -C codegen-units=1 -Z ui-testing -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z deduplicate-diagnostics=no -C strip=debuginfo -C prefer-dynamic -C rpath -C debuginfo=0

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</details>

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 5 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs]: I've switched to using an `ObligationCtxt` as suggested.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 6 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs]: No, it does not. Not sure what I was thinking. Fixed in the latest commit.

File: tests/ui/associated-inherent-types/dispatch-on-self-type-0.rs (hunk 3 above)
Comment (fmease) [reply tests/ui/associated-inherent-types/dispatch-on-self-type-0.rs:34]: I've added two tests to make sure we use the correct `ParamEnv`. The first one is in fn `parameterized` in `dispatch-on-self-type-0.rs` which is `check-pass` and the second one is `not-found-unsatisfied-bounds-1.rs` which is `check-fail`. I did in fact not use the correct `ParamEnv` before. Now I use the environment of `block.owner` instead of the impl block. Let me know if you'd like to see more `ParamEnv` tests (in a follow-up PR maybe).

**Comment by fmease** [comment]
I've addressed the review comments either as a fix or as a `FIXME` for follow-up PRs.

I am no longer sure if it's safe to `ignore_regions` here since I am conflating the *probe* and the *confirmation* phase. I have to think about this but it shouldn't be a blocker (?).

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 4 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2262]: I've added a FIXME. Could you give me an example where there are multiple candidates and we pick the first? I wasn't able to find such a case. Every time I tried to craft such an example, I faced error [E0592](https://doc.rust-lang.org/stable/error-index.html#E0592) (duplicate definitions). Does it require a nontrivial lifetime setup or specialized impls?

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2271]: You are right, we should probably not eagerly error here.

```
#![feature(inherent_associated_types)]
#![allow(incomplete_features)]

struct S<T>(T);

trait Tr {
    type Pr;
    const PR: Self::Pr;
}

impl<T> Tr for S<T> {
    type Pr = ();
    const PR: () = ();
}

impl S<()> {
    type Pr = i32;
    const PR: Self::Pr = 10;
}

fn main() {
    let _: () = S::<bool>::PR; // PASS (pass through) which is correct
    let _: S::<bool>::Pr = (); // FAIL (in my current patch) which is incorrect!
}
```

Okay, I will try to allow the code above while still trying to report a nice error message in case there is no fallback trait impl.
@rustbot author

Unimportant side note: You are not looking at the latest commit here (does not matter in this case tho).

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 7]
```diff
@@ -2194,6 +2188,167 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+
+            self.check_assoc_ty(assoc_item, name, def_scope, block, span);
+
+            let ty::Adt(_, adt_substs) = self_ty.kind() else {
+                // FIXME(inherent_associated_types)
+                bug!("unimplemented: non-adt self of inherent assoc ty");
+            };
+
+            let item_substs =
+                self.create_substs_for_associated_item(span, assoc_item, segment, adt_substs);
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2257]: Should this use `impl_substs`? That should fix #107468, I think.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2262]:
```
#![feature(inherent_associated_types)]

struct Wrapper<T>(T);

impl Wrapper<i32> {
    type Foo = i32;
}

impl Wrapper<()> {
    type Foo = ();
}

fn main() {
    let x: Wrapper<_>::Foo = ();
}
```

?

Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs]: Thanks for the example! I didn't think about inferred types at all since they used to crash in my patch for the longest time. I now use the `<dyn AstConv>::infer_ctxt()` if available and I've rewritten the probing & confirmation code to report an ambiguity error in such cases. :)

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 8]
```diff
@@ -2194,6 +2188,218 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                infcx_ = tcx.infer_ctxt().build();
+                &infcx_
+            }
+        };
+
+        let mut fulfillment_errors = Vec::new();
+        let mut applicable_candidates: Vec<_> = candidates
+            .iter()
+            .filter_map(|&(impl_, (assoc_item, def_scope))| {
+                infcx.probe(|_| {
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2232]: If I don't create a snapshot here with `probe`, we only get a single *applicable candidate* in `ambiguity.rs` since the inference variables are “spoiled” in the 2nd iteration. Makes sense.

For some reason, however, the snapshot creation hinders type inference. E.g. in `S<_>::P`, `_` fails to get inferred even if there is only a **single** impl containing the candidate (for example `impl S<()> { type P = (); }`).

The equivalent code with an inherent associated *const* succeeds to infer the parameter. If I get rid of the `probe` call, then `_` does get inferred to `()` in the example given above. I'm pretty sure we want to infer `_` in such a simple case. Correct?

How can I have both things?

**Comment by fmease** [comment]
I have now rebased my PR. However, most importantly I have also heavily cleaned up the history of this PR by meticulously splitting the largest commit into several finer-grained ones. It used to look quite atrocious, I have to admit! I hope this helps you :) Also, I've moved the *known-bugs* into `bugs/` as discussed on Zulip.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 8 above)
Comment (jackh726) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2234]: So, likely need the same thing as candidate assembly then confirmation, where we first assemble possible candidates (in a probe), and then actually confirm that candidate in outside of a probe.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 9]
```diff
@@ -2198,6 +2192,201 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                    let ocx = ObligationCtxt::new_in_snapshot(&infcx);
+
+                    let impl_ty = tcx.type_of(impl_);
+                    let impl_substs = self.fresh_item_substs(impl_, &infcx);
+                    let impl_ty = impl_ty.subst(tcx, impl_substs);
+                    let impl_ty = ocx.normalize(&cause, param_env, impl_ty);
+
+                    // Check that the Self-types can be related.
+                    // FIXME(fmease): Should we use `eq` here?
+                    ocx.sup(&ObligationCause::dummy(), param_env, impl_ty, self_ty).ok()?;
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2244]: I think this is the line that constrains the type inference. However, the probe causes the changes to be rolled back.

Comment (jackh726) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2244]: Though, I suppose it can generate obligations that constrain later.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 10]
```diff
@@ -2198,6 +2192,201 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                        |_, _| cause.clone(),
+                        param_env,
+                        impl_bounds,
+                    );
+
+                    ocx.register_obligations(impl_obligations);
+
+                    let errors = ocx.select_where_possible();
+                    if !errors.is_empty() {
+                        fulfillment_errors = errors;
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2262]: Okay, so we're only going to see errors for one failed candidate? Seems not ideal. I would imagine we either want to 1) show some info for each potential candidate (if the number of potential candidates is low) or 2) Only show actual fulfillment errors if there is only one candidate, otherwise just list candidates.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 11]
```diff
@@ -2198,6 +2192,201 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                        return None;
+                    }
+
+                    // FIXME(fmease): Unsolved vars can escape this InferCtxt snapshot.
+                    Some((assoc_item, def_scope, infcx.resolve_vars_if_possible(impl_substs)))
+                })
+            })
+            .collect();
+
+        if applicable_candidates.len() > 1 {
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2272]: One thing that I am not actually sure on: if there are multiple inherent impls that can apply, and we have inherent associated types, what's the expectation?

Will we always just error on use? Or do we do any kind or "coherence" like check?

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 12]
```diff
@@ -2198,6 +2192,201 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+            name,
+            self_ty,
+            candidates,
+            fulfillment_errors,
+            span,
+        ))
+    }
+
+    // FIXME(fmease): Copied from `rustc_hir_typeck::method::probe`. Deduplicate.
+    fn fresh_item_substs(&self, def_id: DefId, infcx: &InferCtxt<'tcx>) -> SubstsRef<'tcx> {
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2306]: Is there any modification? Can we just use the same method?

**Review by jackh726 — CHANGES_REQUESTED** [review]
Some thoughts

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 10 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2262]: Makes sense. I will apply your suggestion & add a test.

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 11 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2272]: > […] do we do any kind or "coherence" like check?

We do in fact do a coherence (orphan + overlap) check for inherent impls and reject (most? all?) incoherent impls you'd think of. This happens in `rustc_hir_analysis::coherence::inherent_impls_overlap`.

> Will we always just error on use?

Given the above, as far as I can tell, there will only ever be multiple applicable candidates if the Self type in the projection contains inference variables (which we don't want to / can't solve). All other cases are not errors at use site but at definition site. The analogous code for methods & assoc consts happens here:

https://github.com/rust-lang/rust/blob/eebdfb55fce148676c24555505aebf648123b2de/compiler/rustc_hir_typeck/src/method/probe.rs#L1364

---

I've just learned about the future-incompat warn-by-default lint `coherence_leak_check` #56105 while experimenting around, so it's actually possible to write **incoherent** (inherent *and* trait) impls (by exploiting a bug that is). See [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e6f3b524e4b0dd6510ec9959ba587a4e). I believe the equivalent code with inherent associated types will flag all those use sites as ambiguous (I can't test this, since we don't resolve IATs on non-ADTs like `fn()`, #106719) whereas the trait analogue picks a single candidate depending on the specific region (I don't understand the rules yet).

File: compiler/rustc_hir_analysis/src/astconv/mod.rs (hunk 12 above)
Comment (fmease) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2306]: There is no modification at all. Since `rustc_hir_typeck` depends on `rustc_hir_analysis` (and since crate dependencies have to be acyclic), I'd have to make this method on `dyn AstConv` public & use it from `rustc_hir_typeck`. Is that acceptable?

File: compiler/rustc_hir_analysis/src/astconv/mod.rs [hunk 13]
```diff
@@ -2202,6 +2196,171 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                applicable_candidates.into_iter().map(|(candidate, ..)| candidate).collect(),
+                span,
+            ));
+        }
+
+        if let Some((assoc_item, def_scope, impl_substs)) = applicable_candidates.pop() {
+            self.check_assoc_ty(assoc_item, name, def_scope, block, span);
+
+            // FIXME(inherent_associated_types): To fully *confirm* the *probed* candidate,
+            // we still need to register region obligations for regionck to prove/disprove.
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/astconv/mod.rs:2288]: You should create new fresh item substs, then relate to the self ty (as done before).

But this can be left to another time.

Comment (jackh726) [reply compiler/rustc_hir_analysis/src/astconv/mod.rs:2288]: Please add a FIXME though

**Review by jackh726 — COMMENTED** [review]
Just a few comments. I wouldn't mind leaving them as FIXMEs for now though.

File: tests/ui/associated-inherent-types/not-found-unsatisfied-bounds-in-multiple-impls.stderr [hunk 14]
```diff
@@ -0,0 +1,20 @@
...
+...
+LL |     let _: S::<Featureless, Featureless>::X;
+   |                                           ^ associated type cannot be referenced on `S<Featureless, Featureless>` due to unsatisfied trait bounds
+   |
+   = note: the following trait bounds were not satisfied:
+           `Featureless: One`
+           `Featureless: Two`
+
+error: aborting due to previous error
+
```
[the remark this answers is not in the document]
Comment (fmease) [reply tests/ui/associated-inherent-types/not-found-unsatisfied-bounds-in-multiple-impls.stderr:20]: I see. However, this shouldn't be hard to fix. I basically have to copy over the changes made in #106702. When I opened my PR, I copied over the now outdated suggestion code. Before #106702, the equivalent code with assoc fns / consts had the same diagnostic. See for yourself: [Playground (stable)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c255a23264f0ed5df1e9b5f1299557f3), [playground (nightly)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4d7e344137336308f96d1abd4ea38833).

I can update the diagnostic code once I've fixed the confirmation code.

[the remark this answers is not in the document]
Comment (jackh726) [reply tests/ui/associated-inherent-types/not-found-unsatisfied-bounds-in-multiple-impls.stderr:20]: yep, exactly the same thing actually!

**Comment by jackh726** [comment]
There is obviously followup work for this, but given it's an unstable feature, I'm fine with these being FIXMEs for now.

Sorry for the review latency here. Thanks for addressing the reviews. 

@bors r+
