### PR TITLE
Visit expressions in-order when resolving pattern bindings

### LINKED ISSUE #92100: ICE vec iter
### Code

```Rust

fn main() {
    let v = vec![0123456789];
    let mid = v.len() / 2;
    let s = &v;
    match s {
        [a..mid, mid, mid..b] => {}
        [..] => {}
    }
}
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
[edited:] Visit the pattern's sub-expressions before defining any bindings.

Otherwise, we might get into a case where a Lit/Range expression in a pattern has a qpath pointing to a Ident pattern that is defined after it, causing an ICE when lowering to HIR. I have a more detailed explanation in the issue linked.

Fixes #92100

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -1603,97 +1603,9 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
         pat_src: PatternSource,
         bindings: &mut SmallVec<[(PatBoundCtx, FxHashSet<Ident>); 1]>,
     ) {
-        self.resolve_pattern_inner(pat, pat_src, bindings);
+        ResolvePatternWalker { late: self, pat_src, bindings }.visit_pat(pat);
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1606]: Do we really need another visitor? We may risk forgetting part forwarding newly added methods between the two visitors.
Could the same results be achieved by calling `walk_pat` earlier?
Or could we have the `ResolvePatternWalker` restricted to patterns and not forwarding anything else?

Comment (compiler-errors) [reply compiler/rustc_resolve/src/late.rs]: Actually that's a very good point. We can achieve the same behavior by calling walk_pat first, then declaring the bindings. Fixed up the PR to be much simpler.

**Comment by cjgillot** [comment]
r? @cjgillot 
r=me with a comment explaining why we call `walk_pat` before the rest.
