### PR TITLE
Fix navbar click while in a search

### LINKED ISSUE #45790: [rustdoc] Some left panel links don't work on search results page
It's the first set of links that don't work; the ones that jump to specific items on the current page:

search sidebar

Clicking on them seems to just repeat the search.

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #45790.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
This does not fix the issue. The URL still swallows the `#method.something` anchor, meaning that the link still doesn't work. It's just that now the search box goes away when you click it, leading you to think that maybe something's happening, when in fact it's still busted.

**Comment by QuietMisdreavus** [comment]
So with the current change, the search properly works, and clicking a link in the sidebar will properly dismiss the search, scroll to the desired heading, and toggle the heading's "active" highlight (giving it the yellow background). However, something strange happens: The window title is not changed back from "Results for (query)", and the URL will only say `?search=query`, and the `#method.into_inner` hash will be absent from the URL. After a discussion in IRC we're not sure what's exactly going on here, but i'm not comfortable accepting this as-is with that behavior.

**Comment by frewsxcv** [comment]
not too familiar with this code, so gonna reassign

r? @QuietMisdreavus

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
Is it possible to clear out the query parameters when setting the hash? The URL now properly has the hash, but it still has the query parameters, so now it has `?search=sync#method.into_inner`. If someone accesses a link with both of these items, the query parameters take over; the hash is discarded and the search loads. For example, try [this link in a rendering of this PR](https://tonberry.quietmisdreavus.net/std-45812/std/cell/struct.Cell.html?search=sync#method.into_inner).

Also the title doesn't get set back when you click a sidebar link, so it still says "Results for sync" even though the search results were dismissed. `>_>`

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -145,6 +146,17 @@
             for (i = from; i <= to; ++i) {
                 addClass(document.getElementById(i), 'line-highlighted');
             }
+        } else if (ev !== null && search && !hasClass(search, "hidden") && ev.newURL) {
+            addClass(search, "hidden");
+            removeClass(document.getElementById("main"), "hidden");
+            var hash = ev.newURL.slice(ev.newURL.indexOf('#') + 1);
+            if (browserSupportsHistoryApi()) {
+                history.replaceState(hash, "std - Rust", "?search=#" + hash);
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static/main.js]: * Firefox ignores the title argument to `pushState`/`replaceState` anyway, so right now this is moot, but:
* Setting this unilaterally to "std - Rust" is wildly inaccurate, even within libstd, because for anything but the crate root the title is set to the path of the item. But for anything *but* libstd, this is just erroneous.

On the other hand, with the empty search param, the link is now stable, and the search box and results are still the same. If we can't change the title (in Firefox, at least) via `replaceState`, then i'll just give up on it for the time being. I'd suggest either finding some other way to set it properly or just changing this back to `""`.

**Comment by QuietMisdreavus** [comment]
With the last force-push, i'm ready to call it. There's still the issue of the page title being wrong, but at this point i'm willing to cut my losses. r=me pending travis.

**Comment by QuietMisdreavus** [comment]
Actually, the JS doesn't affect any of the tests that i know of, and it passed tidy, so let's just move along.

@bors r+ rollup
