### PR TITLE
alloc: Document panics when allocations will exceed max

### LINKED ISSUE #148598: String methods do not acknowladge isize::MAX limit like Vec methods do
### Location (URL)

https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.reserve

### Summary

All the `Vec` methods that allocate give a disclaimer about how Rust allocations can't exceed `isize::MAX` bytes, however, (most) String methods that allocate do not have the same disclaimer. 

`reserve` and `reserve_exact` are the worst here, as they actually have the *wrong* disclaimer, claiming the limit is `usize::MAX` instead!

### PR DESCRIPTION
**Pull request by leftmostcat**
Document panics in `String` and `Vec` due to capacity overflowing `isize::MAX`. Correct outdated claims of `usize::MAX` limit.

Fixes https://github.com/rust-lang/rust/issues/148598.

Ping @lolbinarycat

### CODE REVIEW

**Comment by leftmostcat** [comment]
At a glance, the build failures appear to be related to CI setup and not to these changes.

File: library/alloc/src/string.rs [hunk 1]
```diff
@@ -461,6 +461,10 @@ impl String {
     ///
     /// [`new`]: String::new
     ///
+    /// # Panics
+    ///
+    /// Panics if the new capacity exceeds `isize::MAX` _bytes_.
```
Comment (joboet) [inline library/alloc/src/string.rs]: There isn't an old capacity here.

```suggestion
    /// Panics if the capacity exceeds `isize::MAX` _bytes_.
```

**Review by joboet — CHANGES_REQUESTED** [review]
This is great, thank you!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148662/bbb6f68e2888eea989337d558b47372ecf110e08..7c84655ec35ad51e42a6d43bb06dacf195387607)*

File: library/alloc/src/string.rs (hunk 1 above)
Comment (leftmostcat) [reply library/alloc/src/string.rs]: I do prefer the suggested wording. Presently, `Vec` uses the "new capacity" phrasing; should I adjust that as well?
