### PR TITLE
fn ptr is structural match

### LINKED ISSUE #63479: Regression: Matching on function pointers fails when one of the formal params implements custom PartialEq
A contrived [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=401774c0d5d389dc0d621608553f7e99) example:

```rust
#[derive(Eq)]
struct A {
  a: i64   
}

impl PartialEq for A {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.a.eq(&other.a)
    }
}

type Fn = fn(&[A]);

fn my_fn(args: &[A]) {
  println!("hello world");
}

const TEST: Fn = my_fn;

struct B(Fn);

fn main() {
  let s = B(my_fn);
  match s {
    B(TEST) => println!("matched"),
    _ => println!("didn't match")
  };
}
```
This code will build on stable and beta, but not on nightly.

```
error: to use a constant of type `A` in a pattern, `A` must be annotated with `#[derive(PartialEq, Eq)]`
```

It looks like it's related to #62307 possibly?

### PR DESCRIPTION
**Pull request by pnkfelix**
Make fn ptr always structural match, regardless of whether the formal parameter types or return type are.
    
Fix #63479.

### CODE REVIEW

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+    fn r_sm_to(_: &SM) {}
+    fn r_not_sm_to(_: &NotSM) {}
+    fn r_to_r_sm(_: &()) -> &SM { &SM }
+    fn r_to_r_not_sm(_: &()) -> &NotSM { &NotSM }
+
+    #[derive(PartialEq, Eq)]
+    struct Wrap<T>(T);
+
+    // In the code below, we put the match input into a local so that
+    // we can assign it an explicit type that is an fn ptr instead of
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // we can assign it an explicit type that is an `fn` ptr instead of
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    // a singleton type of the fn itself that the type inference would
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // a singleton type of the `fn` itself that the type inference would
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+    // otherwise assign.
+
+    // Check that fn() is #[structural_match]
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn()` is `#[structural_match]`
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN1: Wrap<fn()> = Wrap(trivial);
+    let input: Wrap<fn()> = Wrap(trivial);
+    match Wrap(input) {
+        Wrap(CFN1) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn(T) is #[structural_match] when T is too.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn(T)` is `#[structural_match]` when `T` is too.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN2: Wrap<fn(SM)> = Wrap(sm_to);
+    let input: Wrap<fn(SM)> = Wrap(sm_to);
+    match Wrap(input) {
+        Wrap(CFN2) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn() -> T is #[structural_match] when T is too.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn() -> T` is `#[structural_match]` when `T` is too.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 6]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN3: Wrap<fn() -> SM> = Wrap(to_sm);
+    let input: Wrap<fn() -> SM> = Wrap(to_sm);
+    match Wrap(input) {
+        Wrap(CFN3) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn(T) is #[structural_match] even if T is not.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn(T)` is `#[structural_match]` even if `T` is not.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN4: Wrap<fn(NotSM)> = Wrap(not_sm_to);
+    let input: Wrap<fn(NotSM)> = Wrap(not_sm_to);
+    match Wrap(input) {
+        Wrap(CFN4) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn() -> T is #[structural_match] even if T is not.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn() -> T` is `#[structural_match]` even if `T` is not.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN5: Wrap<fn() -> NotSM> = Wrap(to_not_sm);
+    let input: Wrap<fn() -> NotSM> = Wrap(to_not_sm);
+    match Wrap(input) {
+        Wrap(CFN5) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn(&T) is #[structural_match] when T is too.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn(&T)` is `#[structural_match]` when `T` is too.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN6: Wrap<fn(&SM)> = Wrap(r_sm_to);
+    let input: Wrap<fn(&SM)> = Wrap(r_sm_to);
+    match Wrap(input) {
+        Wrap(CFN6) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn() -> &T is #[structural_match] when T is too.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn() -> &T` is `#[structural_match]` when `T` is too.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 10]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN7: Wrap<fn(&()) -> &SM> = Wrap(r_to_r_sm);
+    let input: Wrap<fn(&()) -> &SM> = Wrap(r_to_r_sm);
+    match Wrap(input) {
+        Wrap(CFN7) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn(T) is #[structural_match] even if T is not.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn(T)` is `#[structural_match]` even if `T` is not.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 11]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN8: Wrap<fn(&NotSM)> = Wrap(r_not_sm_to);
+    let input: Wrap<fn(&NotSM)> = Wrap(r_not_sm_to);
+    match Wrap(input) {
+        Wrap(CFN8) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that fn() -> T is #[structural_match] even if T is not.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that `fn() -> T` is `#[structural_match]` even if `T` is not.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 12]
```diff
@@ -0,0 +1,135 @@
...
+    const CFN9: Wrap<fn(&()) -> &NotSM> = Wrap(r_to_r_not_sm);
+    let input: Wrap<fn(&()) -> &NotSM> = Wrap(r_to_r_not_sm);
+    match Wrap(input) {
+        Wrap(CFN9) => count += 1,
+        Wrap(_) => {}
+    };
+
+    // Check that a type which has fn ptrs is `#[structural_match]`.
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Check that a type which has `fn` ptrs is `#[structural_match]`.
```

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs [hunk 13]
```diff
@@ -0,0 +1,135 @@
...
+        delta: to_sm,
+    };
+
+    let input = Foo { alpha: not_sm_to, beta: to_not_sm, gamma: sm_to, delta: to_sm };
+    match input {
+        CFOO => count += 1,
+        Foo { .. } => {}
+    };
+
+    // Final count must be 10 now if all
```
Comment (Centril) [inline src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]:
```suggestion
    // Final count must be 10 now if all is right.
```

**Review by Centril — COMMENTED** [review]
(A round of nits that you can commit as a batch)
(Was going to say r=me but @varkor was too fast...)

**Comment by fbstj** [comment]
@Centril did your nits from above get tested/committed during that rollup?

**Comment by Centril** [comment]
No, but they were nits, so I don't care a lot. :)

File: src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs (hunk 1 above)
Comment (pnkfelix) [reply src/test/ui/rfc1445/fn-ptr-is-structurally-matchable.rs]: (I'm going to resolve all these nits; it would have been nice if I had gotten around to including them before this landed, but its not worth making a separate PR for them.)

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting; approved for beta backport.
