### PR TITLE
Fix duplicate note on internal feature gates with associated issues

### LINKED ISSUE #116293: duplicate note on `platform_intrinsics` feature gate
I tried this code:

```rust
#![feature(platform_intrinsics)]

pub fn main() {}
```

note the duplicate `  = note: using it is strongly discouraged`

```
warning: the feature `platform_intrinsics` is internal to the compiler or standard library
 --> 688E28C68796BD785ADEA37D96B0DC202A82E2B0FF1F2A33B2A9C36992515DA4.rs:1:12
  |
1 | #![feature(platform_intrinsics)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

warning: 1 warning emitted
```

```
rustc 1.74.0-nightly (8ce4540bd 2023-09-29)
binary: rustc
commit-hash: 8ce4540bd6fe7d58d4bc05f1b137d61937d3cf72
commit-date: 2023-09-29
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.2
```

### PR DESCRIPTION
**Pull request by gurry**
Fixes #116293

Note sure if I should add tests because the issue occurs only for feature gates having associated issues and that set of feature gates will change unpredictably leading to an unnecessary churn in tests.

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -2273,7 +2273,7 @@ impl EarlyLintPass for IncompleteInternalFeatures {
                     cx.emit_spanned_lint(
                         INTERNAL_FEATURES,
                         span,
-                        BuiltinInternalFeatures { name, note },
+                        BuiltinInternalFeatures { name, note: None }, // Passing 'None' as 'BuiltinInternalFeatures' struct already has '#[note]' attr
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/builtin.rs:2276]:
```suggestion
                        BuiltinInternalFeatures { name },
```
If `note` is always `None`, then the corresponding field should be removed from the structure.

Comment (gurry) [reply compiler/rustc_lint/src/builtin.rs]: Thanks. Done.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+ rollup
