### PR TITLE
Issue 90702 fix: Stop treating some crate loading failures as fatal errors

### LINKED ISSUE #90702: Surface multiple "can't find crate" errors at a time
It would be nice if rustc could surface multiple "can't find crate xxxx" errors at once, instead of one at a time.

Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6a10dfbf5f9cc7dc6488fc9c3efaec70

```rust
extern crate asdf;
extern crate foobar;

fn main() {}
```

The current output is:

```
error[E0463]: can't find crate for `asdf`
 --> src/main.rs:2:1
  |
2 | extern crate asdf;
  | ^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[E0463]: can't find crate for `asdf`
 --> src/main.rs:2:1
  |
2 | extern crate asdf;
  | ^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `foobar`
 --> src/main.rs:3:1
  |
3 | extern crate foobar;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `playground` due to previous error
```

### PR DESCRIPTION
**Pull request by mjptree**
Surface mulitple `extern crate` resolution errors at a time.

This is achieved by creating a dummy crate, instead of aborting directly after the resolution error. The `ExternCrateError` has been added to allow propagating the resolution error from `rustc_metadata` crate to the `rustc_resolve` with a minimal public surface. The `import_extern_crate` function is a block that was factored out from `build_reduced_graph_for_item` for better organization. The only added functionality made to it where the added error handling in the `process_extern_crate` call. The remaining bits in this function are the same as before.

Resolves #90702

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_metadata/src/creader.rs [hunk 1]
```diff
@@ -1011,7 +1011,12 @@ impl<'a> CrateLoader<'a> {
                     CrateDepKind::Explicit
                 };
 
-                let cnum = self.resolve_crate(name, item.span, dep_kind);
+                self.used_extern_options.insert(name);
```
Comment (estebank) [inline compiler/rustc_metadata/src/creader.rs:1014]: Should the `used_extern_options` extension be included only in the error path? Otherwise we'd never complain about an `extern foo;` that exists, but is then never used, right?

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 2]
```diff
@@ -889,6 +821,104 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
+        let parent_scope = self.parent_scope;
+        let expansion = parent_scope.expansion;
+
+        let module = if orig_name.is_none() && ident.name == kw::SelfLower {
+            self.r
+                .session
+                .struct_span_err(item.span, "`extern crate self;` requires renaming")
+                .span_suggestion(
+                    item.span,
+                    "try",
```
Comment (estebank) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:843]:
```suggestion
                    "rename the `self` crate to be able to import it",
```

File: compiler/rustc_metadata/src/creader.rs (hunk 1 above)
Comment (mjptree) [reply compiler/rustc_metadata/src/creader.rs:1014]: The behaviour of this line is equivalent to what it was before, when it was still calling `resolve_crate`
```rust
fn resolve_crate<'b>(
    &'b mut self,
    name: Symbol,
    span: Span,
    dep_kind: CrateDepKind,
) -> CrateNum {
    self.used_extern_options.insert(name);
    self.maybe_resolve_crate(name, dep_kind, None).unwrap_or_else(|err| {
        let missing_core =
            self.maybe_resolve_crate(sym::core, CrateDepKind::Explicit, None).is_err();
        err.report_and_throw(&self.sess, span, missing_core)
    })
}
```
So as of now, the crate will never complain. Do I understand right, that you are saying, it should only be marked as "used", in the error case, to surpress later warnings, but it should not be added in the happy case?

Comment (estebank) [reply compiler/rustc_metadata/src/creader.rs:1014]: You got what I meant right. I now wonder why it is always silenced... That *might* be fine 🤷‍♀️

Leaving it to petrochenkov to decide whether to change that 🙂

File: compiler/rustc_metadata/src/locator.rs [hunk 3]
```diff
@@ -1208,10 +1219,25 @@ impl CrateError {
...
-        };
+        }
+    }
 
-        err.emit();
+    crate fn report(self, sess: &Session, span: Span, missing_core: bool) {
+        self.build_diag(sess, span, missing_core).emit();
+    }
+
+    crate fn report_and_throw(self, sess: &Session, span: Span, missing_core: bool) -> ! {
```
Comment (jyn514) [inline compiler/rustc_metadata/src/locator.rs:1229]: "throw" is a bad name for this, Rust doesn't have exceptions (and I think this is actually calling `process::exit` under the hood. I'd call it `report_fatal` instead.

File: compiler/rustc_metadata/src/creader.rs (hunk 1 above)
Comment (mjptree) [reply compiler/rustc_metadata/src/creader.rs:1014]: Oddly enough, I tried to come up with an example that would show the difference in error output, but it doesn't seem to make a difference. The only test that would seem to break with the change would be [`[ui] ui\unused-crate-deps\use_extern_crate_2015.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/unused-crate-deps/use_extern_crate_2015.rs).

Comment (petrochenkov) [reply compiler/rustc_metadata/src/creader.rs:1014]: This is about command line `--extern` options, not about unused `extern crate` items.
So when we resolve `extern crate foo`, then `--extern foo` gets used regardless of the resolution results.

File: src/test/ui/extern/extern-crate-path-to-missing.rs [hunk 4]
```diff
@@ -0,0 +1,6 @@
+// If `extern crate` resolution fails, subsequent resolution errors should be deduplicated
+extern crate foo; //~ ERROR can't find crate for `foo`
+
+fn main() {
+    foo::bar();
```
Comment (petrochenkov) [inline src/test/ui/extern/extern-crate-path-to-missing.rs:5]: I think this can be merged into `extern-crate-multiple-missing.rs` with both `foo::something` and `bar::something` tried.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 5]
```diff
@@ -889,6 +821,104 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
         }
     }
 
+    fn import_extern_crate(
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:824]:
```suggestion
    fn build_reduced_graph_for_extern_crate(
```

File: compiler/rustc_metadata/src/locator.rs [hunk 6]
```diff
@@ -1208,10 +1219,25 @@ impl CrateError {
...
 
-        err.emit();
+    crate fn report(self, sess: &Session, span: Span, missing_core: bool) {
+        self.build_diag(sess, span, missing_core).emit();
+    }
+
+    crate fn report_fatal(self, sess: &Session, span: Span, missing_core: bool) -> ! {
+        self.report(sess, span, missing_core);
         sess.abort_if_errors();
         unreachable!();
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:1232]: `abort_if_erros` + `unreachable` can be replaced with just `FatalError.raise()`, and I'd just remove this function after that.

File: compiler/rustc_metadata/src/creader.rs [hunk 7]
```diff
@@ -517,7 +517,7 @@ impl<'a> CrateLoader<'a> {
         self.maybe_resolve_crate(name, dep_kind, None).unwrap_or_else(|err| {
             let missing_core =
                 self.maybe_resolve_crate(sym::core, CrateDepKind::Explicit, None).is_err();
-            err.report(&self.sess, span, missing_core)
+            err.report_fatal(&self.sess, span, missing_core)
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:520]: It's preferable to return an `Option` from `resolve_crate`, so it can be used from `process_extern_crate` as well.
If you want an aborting version, you can create a new function `fn resolve_crate_or_abort` wrapping `resolve_crate` and `FatalError.raise()`-ing if it returns `None`.

**Comment by petrochenkov** [comment]
Two general comments:
- Could you move the extraction of `fn build_reduced_graph_for_extern_crate` to a separate commit that only moves code and doesn't do anything else? (It can actually be the very first commit.)
- `ExternCrateError` looks unnecessary, I'd keep the old scheme and report the error from `fn resolve_crate`.

**Comment by mjptree** [comment]
I restructered the PR into three commits grouped as thematically as possible incorporating all your suggestions. I hope this makes it easier to disambiguate.

File: src/test/ui/extern/extern-crate-multiple-missing.rs [hunk 8]
```diff
@@ -0,0 +1,8 @@
+// If multiple `extern crate` resolutions fail each of them should produce an error
+extern crate bar; //~ ERROR can't find crate for `bar`
+extern crate foo; //~ ERROR can't find crate for `foo`
+
+fn main() {
+    foo::something();
+    bar::something();
```
Comment (petrochenkov) [inline src/test/ui/extern/extern-crate-multiple-missing.rs:7]: Could you add a comment telling that these lines using the unresolved crates above are not supposed to produce extra errors?

File: compiler/rustc_metadata/src/creader.rs [hunk 9]
```diff
@@ -507,18 +508,31 @@ impl<'a> CrateLoader<'a> {
...
+        span: Span,
+        dep_kind: CrateDepKind,
+    ) -> Option<CrateNum> {
         self.used_extern_options.insert(name);
-        self.maybe_resolve_crate(name, dep_kind, None).unwrap_or_else(|err| {
-            let missing_core =
-                self.maybe_resolve_crate(sym::core, CrateDepKind::Explicit, None).is_err();
-            err.report(&self.sess, span, missing_core)
-        })
+        self.maybe_resolve_crate(name, dep_kind, None).map_or_else(
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:527]:
```suggestion
        self.maybe_resolve_crate(name, dep_kind, None).or_else(
```
Just `or_else` without `map` looks like the right fit here.

File: compiler/rustc_metadata/src/creader.rs [hunk 10]
```diff
@@ -1023,14 +1037,14 @@ impl<'a> CrateLoader<'a> {
...
-                cnum
+                Some(cnum)
             }
             _ => bug!(),
         }
     }
 
     pub fn process_path_extern(&mut self, name: Symbol, span: Span) -> CrateNum {
-        let cnum = self.resolve_crate(name, span, CrateDepKind::Explicit);
+        let cnum = self.resolve_crate_or_abort(name, span, CrateDepKind::Explicit);
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:1047]: It should be very easy to return an `Option<CrateNum>` here.
The only user of this function is `fn extern_prelude_get` and it can return `self.dummy_binding` on `None`.

File: compiler/rustc_metadata/src/creader.rs [hunk 11]
```diff
@@ -751,7 +765,7 @@ impl<'a> CrateLoader<'a> {
         };
         info!("panic runtime not found -- loading {}", name);
 
-        let cnum = self.resolve_crate(name, DUMMY_SP, CrateDepKind::Implicit);
+        let cnum = self.resolve_crate_or_abort(name, DUMMY_SP, CrateDepKind::Implicit);
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:768]: It should be fine to just return on `None` here and in `fn inject_profiler_runtime`, thus eliminating the need in `fn resolve_crate_or_abort`.

File: compiler/rustc_metadata/src/locator.rs [hunk 12]
```diff
@@ -931,8 +931,8 @@ impl fmt::Display for MetadataError<'_> {
 }
 
 impl CrateError {
-    crate fn report(self, sess: &Session, span: Span, missing_core: bool) -> ! {
-        let mut err = match self {
+    fn build_diag(self, sess: &Session, span: Span, missing_core: bool) -> DiagnosticBuilder<'_> {
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/locator.rs:934]: The introduction of `fn build_diag` looks unnecessary.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 13]
```diff
@@ -856,10 +855,32 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
-            self.r.extern_crate_map.insert(local_def_id, crate_id);
-            self.r.expect_module(crate_id.as_def_id())
+            match self.r.crate_loader.process_extern_crate(item, &self.r.definitions, local_def_id)
+            {
+                Some(crate_id) => {
+                    self.r.extern_crate_map.insert(local_def_id, crate_id);
+                    self.r.expect_module(crate_id.as_def_id())
+                }
+                _ => {
+                    let dummy_import = self.r.arenas.alloc_import(Import {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:865]: The only difference between the dummy and non-dummy import is `imported_module`, so you can do something like
```rust
let binding = match self.r.crate_loader.process_extern_crate(item, &self.r.definitions, local_def_id) {
  Some(crate_id) => { / * non-dummy binding */ }
  None => { / * dummy binding */ }
}

let import = self.r.arenas.alloc_import(Import { ... });
```

File: compiler/rustc_metadata/src/creader.rs (hunk 9 above)
Comment (mjptree) [reply compiler/rustc_metadata/src/creader.rs:527]: The return type of `CrateLoader::maybe_resolve_crate` is `Result<CrateNum, CrateError>`, but the target return type that is meant to be propagated to `CrateLoader::resolve_crate` is an `Option<CrateNum>`. `or_else` is not going to work in this case because either I'd like to map a `Ok(cnum)` to a `Some(cnum)` or in case of `Err(err)` I would like to unpack the error, emit it, and return `None`. An alternative that could work, would be
```rust
self.maybe_resolve_crate(name, dep_kind, None).or_else(|err| {
    let missing_core =
        self.maybe_resolve_crate(sym::core, CrateDepKind::Explicit, None)
            .is_err();
        err.report(&self.sess, span, missing_core);
        err
    }
).ok()
```
But to make this work I would have to change `CrateError::report(self, ...)` to `CrateError::report(&self, ...)`, which I personally would find just a bit less desirable, given that semantically I think reporting an error "should" consume it.

Or the cleanest solution may in fact be a simple `match`.

**Comment by mjptree** [comment]
I'm aware the last commit currently fails 2 tests. But I'd like you to have a look at it whether these changes are what you had in mind.

Also, if you look at the two tests [`src/test/ui/crate-loading/invalid-rlib.rs`](https://github.com/rust-lang/rust/blob/a598cc9e35f067181b4ab9e8e69b227d28364e0d/src/test/ui/rust-2018/uniform-paths/deadlock.stderr#L1-L24) and [`src/test/ui/rust-2018/uniform-paths/deadlock.rs`](https://github.com/rust-lang/rust/blob/a598cc9e35f067181b4ab9e8e69b227d28364e0d/src/test/ui/rust-2018/uniform-paths/deadlock.stderr#L1-L24) it would be helpful if you have any suggestions how my changes caused these changes in error output. I'll also continue investigating further after work today.

@rustbot label -S-waiting-on-author +S-waiting-on-review

File: compiler/rustc_metadata/src/creader.rs [hunk 14]
```diff
@@ -751,7 +755,11 @@ impl<'a> CrateLoader<'a> {
         };
         info!("panic runtime not found -- loading {}", name);
 
-        let cnum = self.resolve_crate(name, DUMMY_SP, CrateDepKind::Implicit);
+        let cnum = if let Some(cnum) = self.resolve_crate(name, DUMMY_SP, CrateDepKind::Implicit) {
+            cnum
+        } else {
+            return;
+        };
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:762]: Nit: you can use `let ... else` (#87335) here.

File: compiler/rustc_metadata/src/creader.rs [hunk 15]
```diff
@@ -791,7 +799,11 @@ impl<'a> CrateLoader<'a> {
             );
         }
 
-        let cnum = self.resolve_crate(name, DUMMY_SP, CrateDepKind::Implicit);
+        let cnum = if let Some(cnum) = self.resolve_crate(name, DUMMY_SP, CrateDepKind::Implicit) {
+            cnum
+        } else {
+            return;
+        };
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/creader.rs:806]: Nit: you can use `let ... else` (#87335) here.

File: compiler/rustc_resolve/src/imports.rs [hunk 16]
```diff
@@ -600,7 +600,7 @@ impl<'a> Resolver<'a> {
 
     // Define a "dummy" resolution containing a Res::Err as a placeholder for a
     // failed resolution
-    fn import_dummy_binding(&mut self, import: &'a Import<'a>) {
+    crate fn import_dummy_binding(&mut self, import: &'a Import<'a>) {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:603]: Visibility can be reverted back to private here.

File: compiler/rustc_resolve/src/lib.rs [hunk 17]
```diff
@@ -3288,7 +3288,13 @@ impl<'a> Resolver<'a> {
...
             } else {
                 let crate_id = if !speculative {
-                    self.crate_loader.process_path_extern(ident.name, ident.span)
+                    if let Some(crate_id) =
+                        self.crate_loader.process_path_extern(ident.name, ident.span)
+                    {
+                        crate_id
+                    } else {
+                        return Some(self.dummy_binding);
+                    }
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:3297]: Nit: you can use `let ... else` (#87335) here.

**Comment by petrochenkov** [comment]
>Also, if you look at the two tests [`src/test/ui/crate-loading/invalid-rlib.rs`](https://github.com/rust-lang/rust/blob/a598cc9e35f067181b4ab9e8e69b227d28364e0d/src/test/ui/rust-2018/uniform-paths/deadlock.stderr#L1-L24) and [`src/test/ui/rust-2018/uniform-paths/deadlock.rs`](https://github.com/rust-lang/rust/blob/a598cc9e35f067181b4ab9e8e69b227d28364e0d/src/test/ui/rust-2018/uniform-paths/deadlock.stderr#L1-L24) it would be helpful if you have any suggestions how my changes caused these changes in error output.

IIRC, imports may attempt to load crates for the second time during import validation (which we now reach due to not producing a fatal error), this looks like the reason for the `invalid-rlib.rs` change.
The extra messages in `deadlock.rs` also look like an output from import validation.

You can attempt to avoid these extra messages for already erroneous imports (the relevant code  should be somewhere inside `fn finalize_imports`), but it's a task for a separate PR.

**Comment by mjptree** [comment]
> You can attempt to avoid these extra messages for already erroneous imports (the relevant code should be somewhere inside `fn finalize_imports`), but it's a task for a separate PR.

Alright, are you saying then you would agree to just fix the tests enough to make them pass right now and change the error output in a later PR to the desired output?

I have just updated the tests accordingly and noted down 2 new issues that this PR #91045 is going to introduce when merged:

**1)** [Fix duplicate resolution error messages when using both `extern crate` and `foo`](https://github.com/rust-lang/rust/issues/90702#issuecomment-973591306).

Example:
```rust
extern crate foo;

use foo::bar;

fn main() {
    bar::baz();
}
```
Output after merging:
```
error[E0463]: can't find crate for `foo`
 --> src\main.rs:1:1
  |
1 | extern crate foo;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error[E0433]: failed to resolve: use of undeclared crate or module `bar`
 --> src\main.rs:6:5
  |
6 |     bar::buzz();
  |     ^^^ use of undeclared crate or module `bar`

Some errors have detailed explanations: E0433, E0463.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `issue-90702-fix` due to 2 previous errors
```

**2)** [Fix duplicate error unresolved import errors for missing crates (only editions 2018/2021)](https://github.com/rust-lang/rust/blob/3226a3d42cac5b2e6acabffe26368469ea12d7a5/src/test/ui/rust-2018/uniform-paths/deadlock.stderr).

Example:
```rust
use bar::foo;
use foo::bar;

fn main() {}
```
Output after merge:
```
error[E0463]: can't find crate for `bar`
 --> .\src\main.rs:1:5
  |
1 | use bar::foo;
  |     ^^^ can't find crate

error[E0463]: can't find crate for `foo`
 --> .\src\main.rs:2:5
  |
2 | use foo::bar;
  |     ^^^ can't find crate

error[E0432]: unresolved imports `bar::foo`, `foo::bar`
 --> .\src\main.rs:1:5
  |
1 | use bar::foo;
  |     ^^^^^^^^
2 | use foo::bar;
  |     ^^^^^^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0463.
For more information about an error, try `rustc --explain E0432`.
```

I would open an issue and start working on these 2, as soon as the current PR is merged, if that is ok.

**Comment by petrochenkov** [comment]
>Alright, are you saying then you would agree to just fix the tests enough to make them pass right now and change the error output in a later PR to the desired output?

Yes.

r=me after squashing the review changes into the main commits.

**Comment by mjptree** [comment]
Thanks a lot!

r=petrochenkov

**Comment by mjptree** [comment]
Thanks a lot!

@bors r=petrochenkov

**Comment by matthiaskrgr** [comment]
Mmh, this might cause this test failure here: https://github.com/rust-lang/rust/pull/91405#issuecomment-983140168
but I'm not 100% certain.
@bors rollup=iffy

**Comment by petrochenkov** [comment]
Yes, looks like this PR is the reason, `ui/extern-flag/empty-extern-arg.rs` has target-dependent output.

`ui\panic-handler\weak-lang-item.rs` is a similar test and it uses `// needs-unwind` to disable the test on targets producing different diagnostics.

**Comment by mjptree** [comment]
> `ui\panic-handler\weak-lang-item.rs` is a similar test and it uses `// needs-unwind` to disable the test on targets producing different diagnostics.

I'm trying the same fix then here, ignoring this particular test for `panic=abort` and emscripten targets.

@rustbot label -S-waiting-on-author +S-waiting-on-review
