### PR TITLE
Fix linking statics on Arm64EC

### LINKED ISSUE #138541: Linking error when compiled to `arm64ec-pc-windows-msvc`
On windows compiled to `arm64ec-pc-windows-msvc` target with `-Zbuild-std` got linking error:
```
error: linking with `link.exe` failed: exit code: 1120
  = note:    Creating library D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.lib and object D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.exp␍
          symbols.o : error LNK2001: unresolved external symbol #_RNxC3std12H7JG8fmF3Zv8 (EC Symbol)␍
          D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.exe : fatal error LNK1120: 1 unresolved externals␍
```
Rust 1.87.0-nightly (ecade534c 2025-03-14)

### PR DESCRIPTION
**Pull request by dpaoliello**
Arm64EC builds recently started to fail due to the linker not finding a symbol:
```
symbols.o : error LNK2001: unresolved external symbol #_ZN3std9panicking11EMPTY_PANIC17hc8d2b903527827f1E (EC Symbol)
          C:\Code\hello-world\target\arm64ec-pc-windows-msvc\debug\deps\hello_world.exe : fatal error LNK1120: 1 unresolved externals
```

It turns out that `EMPTY_PANIC` is a new static variable that was being exported then imported from the standard library, but when exporting LLVM didn't prepend the name with `#` (as only functions are prefixed with this character), whereas Rust was prefixing with `#` when attempting to import it.

The fix is to have Rust not prefix statics with `#` when importing.

Adding tests discovered another issue: we need to correctly mark static exported from dylibs with `DATA`, otherwise MSVC's linker assumes they are functions and complains that there is no exit thunk for them.

CI found another bug: we only apply `DllImport` to non-local statics that aren't foreign items (i.e., in an `extern` block), that is we want to use `DllImport` for statics coming from other Rust crates. However, `__rust_no_alloc_shim_is_unstable` is a static generated by the Rust compiler if required, but downstream crates consider it a foreign item since it is declared in an `extern "Rust"` block, thus they do not apply `DllImport` to it and so fails to link if it is exported by the previous crate as `DATA`. The fix is to apply `DllImport` to foreign items that are marked with the `rustc_std_internal_symbol` attribute (i.e., we assume they aren't actually foreign and will be in some Rust crate).

Fixes #138541

---
try-job: dist-aarch64-msvc
try-job: dist-x86_64-msvc
try-job: x86_64-msvc-1
try-job: x86_64-msvc-2

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]
Changes look good to me. Is it possible to write a regression test? (Either a full-scale integration test that links an exported static from one crate to another or a test that imports a static and dumps the symbol name or something?)

**Comment by dpaoliello** [comment]
> Changes look good to me. Is it possible to write a regression test? (Either a full-scale integration test that links an exported static from one crate to another or a test that imports a static and dumps the symbol name or something?)

Good call, found another bug: we need to correctly export variables as `DATA` otherwise the linker expects them to have thunks.

@rustbot ready

File: tests/run-make/crate-import-export-static/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// Test that a static can be exported from one crate and imported into another.
+//
+// This was broken for Arm64EC as only functions, not variables, should be
+// decorated with `#`.
+// See https://github.com/rust-lang/rust/issues/138541
+
+use run_make_support::rustc;
+
+fn main() {
+    rustc().input("export.rs").panic("abort").run();
```
Comment (wesleywiser) [inline tests/run-make/crate-import-export-static/rmake.rs:10]: I think you probably want to specify a target here as otherwise, this test will only be executed for Tier 1 target platforms so `arm64ec-pc-windows-msvc` will never be tested against.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @dpaoliello! 

@bors r+ rollup

Also nominating for potential beta backport as this fixes a serious issue for the Tier 2 `aarch64-pc-windows-msvc`.

**Comment by Zalathar** [comment]
Possibly failed in rollup? https://github.com/rust-lang/rust/pull/140495#issuecomment-2840742931

I'll kick off some try jobs to try to check whether this PR was the cause.

@bors r-

**Comment by dpaoliello** [comment]
I can repro this locally, will investigate.

@rustbot author

**Comment by jieyouxu** [comment]
This was discussed in [today's compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-05-01/near/515511736). The team will revisit the backport decision once the PR merges.

**Review by wesleywiser — APPROVED** [review]

**Comment by Zalathar** [comment]
This also failed in rollup in `dist-i686-mingw`: https://github.com/rust-lang/rust/pull/140690#issuecomment-2853337389

**Comment by dpaoliello** [comment]
Verified with a modified PR job: <https://github.com/rust-lang/rust/actions/runs/14870437710/job/41757432246?pr=140176>

@rustbot ready

**Review by wesleywiser — APPROVED** [review]

**Comment by zmodem** [comment]
We're hitting lld errors when building cargo after this change:

```
locally defined symbol imported: __rust_no_alloc_shim_is_unstable [...] LNK4217
```

It sounds like something is applying dllimport to __rust_no_alloc_shim_is_unstable even though it's part of the same image.

Actually, I see you're hitting the same thing in this test: https://github.com/rust-lang/rust/pull/140176/files#diff-f31e13197ab771a198513dbb749c33ae9195b4814c5a358deca1294a112adbc1

Is this intentional? And if so, do the build files need to be updated to ignore the warning?

(Our reference: https://crbug.com/417168093)

**Comment by dpaoliello** [comment]
> We're hitting lld errors when building cargo after this change:
> 
> ```
> locally defined symbol imported: __rust_no_alloc_shim_is_unstable [...] LNK4217
> ```
> 
> It sounds like something is applying dllimport to __rust_no_alloc_shim_is_unstable even though it's part of the same image.
> 
> Actually, I see you're hitting the same thing in this test: https://github.com/rust-lang/rust/pull/140176/files#diff-f31e13197ab771a198513dbb749c33ae9195b4814c5a358deca1294a112adbc1
> 
> Is this intentional? And if so, do the build files need to be updated to ignore the warning?
> 
> (Our reference: https://crbug.com/417168093)

Yes, this warning is expected: `__rust_no_alloc_shim_is_unstable` is marked as `extern "Rust"` in the standard library, but the compiler generates a definition for it.

The correct fix would be for `compiler/rustc_codegen_llvm/src/consts.rs` to know if the current crate is generating the definition or not (thus whether `dllimport` is correct or not).

It's interesting that MSVC's linker reported this as warning 4286 whereas lld is reporting it as 4217.

I'll submit a change to ignore 4217 as well.

**Comment by zmodem** [comment]
Hmm, while that fixes our build of cargo, we're now hitting the same warning when linking Chromium, and we definitely don't want to disable this warning globally.

This seems like a regression.

**Comment by dpaoliello** [comment]
@bjorn3 is this something you can help with?

There are two ways that this could be fixed without needing a warning suppression for the linker:
* Either `consts.rs` needs to be made aware of when the compiler is planning to emit the definition for `__rust_no_alloc_shim_is_unstable` and so it should not be marked as `dllimport`
* If the compiler is planning to emit the definition of `__rust_no_alloc_shim_is_unstable` it modifies the corresponding def to mark the static as being local (this needs to be done early enough that `const.rs` hasn't been called yet).

I don't know enough about the architecture of the compiler to know which of these approaches is plausible, though I would argue that the second is more "correct" (i.e., we are no longer lying to the compiler and telling it that `__rust_no_alloc_shim_is_unstable` is non-local and foreign, then emitting a definition for it).

**Comment by nico** [comment]
If it takes a while to figure out a good way forward, would it be possible to revert to green in the meantime?

**Comment by erickt** [comment]
We're also running into this issue on Fuchsia trying to build our stage0 windows rustc. If we do a revert, could we also cut a new stage0 as well?

**Comment by jieyouxu** [comment]
The beta backport nomination was rejected in the [compiler async backport thread](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Async.20backport.20nominations/near/516955136).

@rustbot label: -beta-nominated
