### PR TITLE
Emit specific error for struct literal in conditions

### LINKED ISSUE #51311: Misleading error message in case of ambiguous if blocks
For the following code, the compiler generates error [E0423](https://doc.rust-lang.org/nightly/error-index.html#E0423) on both stable and nightly in the playground:
```rust
fn main() {
    let x = MyType { y: 1, };
    
    // Fails
    if x == MyType { y: 1, } {
    }
    // Is ok
    if x == (MyType { y: 1, }) {
    }
}

#[derive(Eq, PartialEq)]
struct MyType {
    y: u64,
}
```
```
error: expected type, found `1`
 --> src/main.rs:5:25
  |
5 |     if x == MyType { y: 1, } {
  |                         ^ expecting a type here because of type ascription

error[E0423]: expected value, found struct `MyType`
 --> src/main.rs:5:13
  |
5 |     if x == MyType { y: 1, } {
  |             ^^^^^^ did you mean `MyType { /* fields */ }`?

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0423`.
```
I learned that there is a parsing ambiguity in the if-statement which fails to compile. But rather than producing an error message explaining this ambiguity, the compiler seems to assume one of the possibilities ("the first accolade belongs to the if-statement") and proceeds, encounting the error E0423 which it then displays.

It seems preferable for the compiler to stop at the point of encounting the ambiguity, with an error message explaining the problem.

### LINKED ISSUE #59962: Struct-style enum constructor gets misparsed as type ascription without suggestion
The following program
```rust
#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
enum E {
    V { field: bool }
}
fn test_E(x: E) {
    if x == E::V { field: false } {}
}
```
[shows the error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4c0451731e54cb45e36af9ebe99ee769)
```
error: expected identifier, found keyword `false`
 --> src/lib.rs:6:27
  |
6 |     if x == E::V { field: false } {}
  |                           ^^^^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
  |
6 |     if x == E::V { field: r#false } {}
  |                           ^^^^^^^

error: expected type, found keyword `false`
 --> src/lib.rs:6:27
  |
6 |     if x == E::V { field: false } {}
  |                           ^^^^^ expecting a type here because of type ascription

error[E0423]: expected value, found struct variant `E::V`
 --> src/lib.rs:6:13
  |
6 |     if x == E::V { field: false } {}
  |             ^^^^ did you mean `E::V { /* fields */ }`?

error: aborting due to 3 previous errors
```

This is not very helpful: If I replace `E::V` by a struct constructor, it suggests adding parentheses, which is the real solution (the error is still not great, but better than this). Instead "did you mean `E::V`" is leading in the totally wrong direction.

### PR DESCRIPTION
**Pull request by estebank**
Fix #59962, fix #51311.

### CODE REVIEW

File: src/librustc_resolve/error_reporting.rs [hunk 1]
```diff
@@ -409,7 +415,35 @@ impl<'a> Resolver<'a> {
             (Def::Union(..), _) |
             (Def::Variant(..), _) |
             (Def::Ctor(_, _, CtorKind::Fictive), _) if ns == ValueNS => {
-                err.span_label(span, format!("did you mean `{} {{ /* fields */ }}`?", path_str));
+                    match source {
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: This is duplicated code, could be extracted to closure/method.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -2902,6 +2904,51 @@ impl<'a> Parser<'a> {
         self.maybe_recover_from_bad_qpath(expr, true)
     }
 
+    fn should_parse_struct_expr(
+        &mut self,
+        lo: Span,
+        path: &ast::Path,
+        attrs: &ThinVec<Attribute>,
+    ) -> Option<PResult<'a, P<Expr>>> {
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: This method's logic could be cleaned up.

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -2902,6 +2904,51 @@ impl<'a> Parser<'a> {
...
+            // have false positives in the case of `if x == y { z } { a }`.
+        );
+        let mut bad_struct = false;
+        let mut parse_struct = !self.restrictions.contains(Restrictions::NO_STRUCT_LITERAL);
+        if self.restrictions.contains(Restrictions::NO_STRUCT_LITERAL) && could_be_struct {
+            // This is a struct literal, but we don't can't accept them here
+            bad_struct = true;
+            parse_struct = true;
+        }
+        if parse_struct {
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]:
```rust
let bad_struct = self.restrictions.contains(Restrictions::NO_STRUCT_LITERAL);
if !bad_struct || could_be_struct {
    ...
}
```

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -2902,6 +2904,51 @@ impl<'a> Parser<'a> {
...
     }
 
+    fn should_parse_struct_expr(
+        &mut self,
+        lo: Span,
+        path: &ast::Path,
+        attrs: &ThinVec<Attribute>,
+    ) -> Option<PResult<'a, P<Expr>>> {
+        let could_be_struct = self.look_ahead(1, |t| t.is_ident()) && (
+            self.look_ahead(2, |t| *t == token::Colon)
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Type ascription will be mis-parsed (`if x == y { z: TYPE }`).

Comment (petrochenkov) [reply src/libsyntax/parse/parser.rs]: `{ IDENT ,` is the only case where we know it's a struct literal reliably.

Comment (petrochenkov) [reply src/libsyntax/parse/parser.rs]: Additionally, we can cover cases like `{ IDENT: NOT_A_TYPE` by checking that the token following the colon is not `can_begin_type`.
This notably doesn't cover `{ x: y }` though, but covers `{ x: 1 }` or `{ x: -y }`.

Comment (petrochenkov) [reply src/libsyntax/parse/parser.rs]: We can also cover cases like `{ x: y.method() }` with a more elaborated scheme with rollback:
```
save_state()
stmt = parse_stmt() // not speculative enough, can report errors unconditionally
parse_struct = stmt.is_err()
rollback()
if parse_struct { parse_struct() }
```
, but I wouldn't go in this direction personally.

File: src/libsyntax/parse/parser.rs [hunk 5]
```diff
@@ -2902,6 +2904,51 @@ impl<'a> Parser<'a> {
         self.maybe_recover_from_bad_qpath(expr, true)
     }
 
+    fn should_parse_struct_expr(
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]:
```suggestion
    fn maybe_parse_struct_expr(
```

File: src/libsyntax/parse/parser.rs [hunk 6]
```diff
@@ -2902,6 +2904,51 @@ impl<'a> Parser<'a> {
...
+        if self.restrictions.contains(Restrictions::NO_STRUCT_LITERAL) && could_be_struct {
+            // This is a struct literal, but we don't can't accept them here
+            bad_struct = true;
+            parse_struct = true;
+        }
+        if parse_struct {
+            match self.parse_struct_expr(lo, path.clone(), attrs.clone()) {
+                Err(err) => return Some(Err(err)),
+                Ok(expr) => {
+                    if bad_struct {
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Style: this can be factored into `if let`:
```rust
let expr = self.parse_struct_expr(lo, path.clone(), attrs.clone());
if bad_struct {
    if let Ok(expr) = expr { ... }
}
return Some(expr);
```

File: src/librustc_resolve/error_reporting.rs [hunk 7]
```diff
@@ -409,7 +415,35 @@ impl<'a> Resolver<'a> {
             (Def::Union(..), _) |
             (Def::Variant(..), _) |
             (Def::Ctor(_, _, CtorKind::Fictive), _) if ns == ValueNS => {
-                err.span_label(span, format!("did you mean `{} {{ /* fields */ }}`?", path_str));
```
Comment (petrochenkov) [inline src/librustc_resolve/error_reporting.rs]: Nit: could you move `let (followed_by_brace, closing_brace) = self.followed_by_brace(span);` to here so it's not evaluated unless necessary.

File: src/librustc_resolve/error_reporting.rs (hunk 1 above)
Comment (petrochenkov) [reply src/librustc_resolve/error_reporting.rs]: Yes, that would be nice.

Comment (petrochenkov) [reply src/librustc_resolve/error_reporting.rs]: Also, 3 branches out of 4 report exactly the same `err.span_label(...)`, perhaps it can be compacted.

File: src/libsyntax/parse/parser.rs (hunk 4 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: I think another alternative would be to have a small pseudoparser that looks for multiple occurrences of `<ident>: <expr>,` until finding a closing `}`, but that is not something I'm inclined to include in this PR.

**Comment by petrochenkov** [comment]
Added one commit fixing the case with boolean literals and also improving a e s t h e t i c s.

**Comment by estebank** [comment]
@petrochenkov neat

**Comment by estebank** [comment]
@petrochenkov can you take a look at [the last commit](https://github.com/rust-lang/rust/pull/59981/commits/88e0c6a7fadbee7cda273b86580f65f95793740b)? It adds extra action at a distance to hide type check errors for struct literals that we couldn't be certain were that during parsing. Of particular interest is [the change to `coercion.rs`](https://github.com/rust-lang/rust/pull/59981/commits/88e0c6a7fadbee7cda273b86580f65f95793740b#diff-816393de5863577a8b1fcb45bcb25e1d). If you disagree with the approach I can drop that commit.

File: src/test/ui/struct-literal-variant-in-if.stderr [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+LL |     let y: usize = ();
+   |                    ^^ expected usize, found ()
+   |
+   = note: expected type `usize`
+              found type `()`
+
+error: aborting due to 7 previous errors
+
+Some errors have detailed explanations: E0308, E0423.
+For more information about an error, try `rustc --explain E0308`.
```
Comment (estebank) [inline src/test/ui/struct-literal-variant-in-if.stderr]: For comparison of the output without all of these changes: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1f4816149ca6e13ecb97d71c99675fec

```
error: expected identifier, found keyword `true`
  --> src/main.rs:14:28
   |
14 |     if x == E::I { field1: true, field2: 42 } {}
   |                            ^^^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
   |
14 |     if x == E::I { field1: r#true, field2: 42 } {}
   |                            ^^^^^^

error: expected type, found keyword `true`
  --> src/main.rs:14:28
   |
14 |     if x == E::I { field1: true, field2: 42 } {}
   |                            ^^^^ expecting a type here because of type ascription

error: expected identifier, found keyword `false`
  --> src/main.rs:16:27
   |
16 |     if x == E::V { field: false } {}
   |                           ^^^^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
   |
16 |     if x == E::V { field: r#false } {}
   |                           ^^^^^^^

error: expected type, found keyword `false`
  --> src/main.rs:16:27
   |
16 |     if x == E::V { field: false } {}
   |                           ^^^^^ expecting a type here because of type ascription

error: expected type, found `-`
  --> src/main.rs:18:27
   |
18 |     if x == E::J { field: -42 } {}
   |                           ^ expecting a type here because of type ascription

error: expected type, found `""`
  --> src/main.rs:20:27
   |
20 |     if x == E::K { field: "" } {}
   |                           ^^ expecting a type here because of type ascription

error[E0423]: expected value, found struct variant `E::V`
  --> src/main.rs:10:13
   |
10 |     if x == E::V { field } {}
   |             ^^^^ did you mean `E::V { /* fields */ }`?

error[E0423]: expected value, found struct variant `E::V`
  --> src/main.rs:12:13
   |
12 |     if x == E::V { field: field } {}
   |             ^^^^ did you mean `E::V { /* fields */ }`?

error[E0573]: expected type, found local variable `field`
  --> src/main.rs:12:27
   |
12 |     if x == E::V { field: field } {}
   |                           ^^^^^
   |                           |
   |                           not a type
   |                           expecting a type here because of type ascription

error[E0423]: expected value, found struct variant `E::I`
  --> src/main.rs:14:13
   |
14 |     if x == E::I { field1: true, field2: 42 } {}
   |             ^^^^ did you mean `E::I { /* fields */ }`?

error[E0423]: expected value, found struct variant `E::V`
  --> src/main.rs:16:13
   |
16 |     if x == E::V { field: false } {}
   |             ^^^^ did you mean `E::V { /* fields */ }`?

error[E0423]: expected value, found struct variant `E::J`
  --> src/main.rs:18:13
   |
18 |     if x == E::J { field: -42 } {}
   |             ^^^^ did you mean `E::J { /* fields */ }`?

error[E0423]: expected value, found struct variant `E::K`
  --> src/main.rs:20:13
   |
20 |     if x == E::K { field: "" } {}
   |             ^^^^ did you mean `E::K { /* fields */ }`?

error[E0658]: type ascription is experimental (see issue #23416)
  --> src/main.rs:12:20
   |
12 |     if x == E::V { field: field } {}
   |                    ^^^^^^^^^^^^

error[E0308]: mismatched types
  --> src/main.rs:10:20
   |
8  | fn test_E(x: E) {
   |                 - help: try adding a return type: `-> bool`
9  |     let field = true;
10 |     if x == E::V { field } {}
   |                    ^^^^^ expected (), found bool
   |
   = note: expected type `()`
              found type `bool`

error[E0308]: mismatched types
  --> src/main.rs:22:20
   |
22 |     let y: usize = ();
   |                    ^^ expected usize, found ()
   |
   = note: expected type `usize`
              found type `()`

error: aborting due to 16 previous errors
```

File: src/librustc_resolve/lib.rs [hunk 9]
```diff
@@ -3222,11 +3222,30 @@ impl<'a> Resolver<'a> {
...
+                if this.session.parse_sess.missing_ident_could_be_struct_literal
+                    .borrow().contains(&segment.ident.span)
+                {
+                    for sp in this.session.possible_struct_literal.borrow().iter() {
+                        if sp.overlaps(segment.ident.span) {
+                            // Ignore errors caused by likely struct literals. An error has
+                            // already been emitted suggesting surrounding struct literal with
+                            // `()` in a case like `if x == E::V { field: field } {}`
+                            report = false;
+                            break;
```
Comment (estebank) [inline src/librustc_resolve/lib.rs]: You'll want to look at this.

File: src/librustc_typeck/check/coercion.rs [hunk 10]
```diff
@@ -1110,6 +1110,21 @@ impl<'gcx, 'tcx, 'exprs, E> CoerceMany<'gcx, 'tcx, 'exprs, E>
...
+        if let Some(expr) = &expression {
+            if fcx.tcx.sess.parse_sess.missing_ident_could_be_struct_literal
+                .borrow().contains(&expr.span)
+            {
+                for sp in fcx.tcx.sess.possible_struct_literal.borrow().iter() {
+                    if sp.overlaps(expr.span) {
+                        // Ignore type errors caused by likely struct literals. An error has
+                        // already been emitted suggesting surrounding struct literal with `()` in
+                        // a case like `if x == E::V { field } {}`
+                        return;
```
Comment (estebank) [inline src/librustc_typeck/check/coercion.rs]: and this

**Review by estebank — COMMENTED** [review]
@petrochenkov I am aware of the hackiness of the approach 😬

**Comment by estebank** [comment]
Removing the changes after the review was made, rebasing to fix merge conflicts and posting follow up PR for easier review.
