### PR TITLE
skip checking supertraits in object candidate for `NormalizesTo` goal

### LINKED ISSUE #245: `thirtyfour` non-`Send` witness regression
```rust
cargo download thirtyfour@0.33.0-alpha.2
cd thirtyfour-0.33.0-alpha.2
RUSTFLAGS=-Znext-solver cargo +nightly b
```
results in 16 similar errors
```
error[E0277]: `{coroutine witness@src/extensions/query/element_query.rs:460:43: 505:6}` cannot be sent between threads safely
   --> src/components/wrapper/resolver.rs:366:9
    |
361 |             async move {
    |             ---------- within this `{async block@src/components/wrapper/resolver.rs:361:13: 361:23}`
...
366 |         Self::new_custom(base_element, resolver)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `{coroutine witness@src/extensions/query/element_query.rs:460:43: 505:6}` cannot be sent between threads safely
    |
...
```

this error is surprising. By testing with `cargo rustc -- -Ztreat-err-as-bug` the ICE does happen in `query check_coroutine_obligations` as it should. We apparently actually do a witness which previously implemented `Send` but no longer does so.

Would be good to minimize this issue to figure out what exactly is going wrong.

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/245.

r? @lcnr

### CODE REVIEW

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 1]
```diff
@@ -1499,7 +1499,11 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
         };
 
         if let ObligationCauseCode::ImplDerived(cause) = &*code {
-            try_borrowing(cause.derived.parent_trait_pred, &[])
+            // Parent trait predicate may contain regions that's already popped.
+            // We can erase them since evaluation later doesn't care about regions anyway.
+            let parent_trait_pred =
+                self.tcx.erase_and_anonymize_regions(cause.derived.parent_trait_pred);
+            try_borrowing(parent_trait_pred, &[])
```
Comment (adwinwhite) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: The old solver doesn't cause ICE because it doesn't eagerly resolve vars before canonicalizing the predicate.

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 2]
```diff
@@ -74,6 +74,8 @@ where
     /// Consider a clause specifically for a `dyn Trait` self type. This requires
     /// additionally checking all of the supertraits and object bounds to hold,
     /// since they're not implied by the well-formedness of the object type.
+    /// `NormalizesTo` overrides this to not check the supertraits, for backwards
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]:
```suggestion
    /// 
    /// `NormalizesTo` overrides this to not check the supertraits for backwards
```

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs [hunk 3]
```diff
@@ -184,6 +184,17 @@ where
         then(ecx)
     }
 
+    fn probe_and_consider_object_bound_candidate(
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:190]: please add a comment here as well that this differs from trait goals with a `FIXME(-Zhigher-ranked-assumptions)` that we should try to unify these again once we properly support binders, linking to the issue fixed by this change

File: tests/ui/traits/next-solver/normalize/skip-supertraits-in-object-candidate.rs [hunk 4]
```diff
@@ -0,0 +1,37 @@
+//@ check-pass
+//@ compile-flags: -Znext-solver
+//@ edition: 2024
+
+// A regression test for trait-system-refactor-initiative#245.
+// The old solver doesn't check the supertraits of the principal trait
+// when considering object candidate for normalization.
```
Comment (lcnr) [inline tests/ui/traits/next-solver/normalize/skip-supertraits-in-object-candidate.rs:7]: ... and the new solver previously did, resulting in a placeholder error while normalizing inside of a generator witness

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: hm, can you move this into a separate PR, makes it easier to approve the rest of this one

> The old solver doesn't cause ICE because it doesn't eagerly resolve vars before canonicalizing the predicate.

so the `parent_trait_pred` has leaking infer vars in both solvers? ah well, please move this into a separate PR, I would like to potentially fix this closer to the root of the leaked infer vars.
