### PR TITLE
Do not consider method call receiver as an argument in AST.

### LINKED ISSUE #73663: ICE: #cfg usage in a macro call
I get an ICE when trying to use `#[cfg(feature = "with_ctap2_1")]` inside a map-like macro call.

I tried this code:

https://github.com/kaczmarczyck/OpenSK/commits/internal-compiler-error
The last commit does NOT reproduce the error, but shows the 2 line diff to commit
https://github.com/kaczmarczyck/OpenSK/commit/4fec405fb5bb1b986a8fbbb518d4fe88f4dbd38f
that is reproducing the problem.

Please clone the branch above, run ./setup.sh if you want to check that everything works, then execute:
`RUST_BACKTRACE=1 cargo test --release --features std --verbose`

I expected a regular compiler error (or a successful test).

Instead, the above mentioned ICE occurred.

## Meta

`rustc --version --verbose`:

```
rustc 1.42.0-nightly (f43c34a13 2020-02-02)
binary: rustc
commit-hash: f43c34a134358471726f25fe5973b8c7e177c825
commit-date: 2020-02-02
host: x86_64-unknown-linux-gnu
release: 1.42.0-nightly
LLVM version: 9.0

Backtrace:

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_resolve/late.rs:1994:35
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:52
  15: rustc_resolve::late::LateResolutionVisitor::resolve_expr
  16: rustc_resolve::late::LateResolutionVisitor::resolve_expr
  17: <rustc_resolve::late::LateResolutionVisitor as syntax::visit::Visitor>::visit_block
  18: rustc_resolve::late::LateResolutionVisitor::resolve_expr
  19: <rustc_resolve::late::LateResolutionVisitor as syntax::visit::Visitor>::visit_local
  20: <rustc_resolve::late::LateResolutionVisitor as syntax::visit::Visitor>::visit_block
  21: <rustc_resolve::late::LateResolutionVisitor as syntax::visit::Visitor>::visit_fn
  22: syntax::visit::walk_item
  23: rustc_resolve::late::LateResolutionVisitor::resolve_item
  24: syntax::visit::walk_item
  25: rustc_resolve::late::LateResolutionVisitor::resolve_item
  26: syntax::visit::walk_item
  27: rustc_resolve::late::LateResolutionVisitor::resolve_item
  28: syntax::visit::walk_item
  29: rustc_resolve::late::LateResolutionVisitor::resolve_item
  30: syntax::visit::walk_crate
  31: rustc_resolve::Resolver::resolve_crate
  32: rustc_interface::passes::configure_and_expand_inner
  33: rustc_interface::passes::configure_and_expand::{{closure}}
  34: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  35: rustc_interface::passes::configure_and_expand
  36: rustc_interface::queries::Queries::expansion
  37: rustc_interface::interface::run_compiler_in_existing_thread_pool
  38: scoped_tls::ScopedKey<T>::set
  39: syntax::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.42.0-nightly (f43c34a13 2020-02-02) running on x86_64-unknown-linux-gnu
note: compiler flags: -C opt-level=3
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `ctap2`.
```

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/73663

### CODE REVIEW

File: compiler/rustc_ast/src/ast.rs [hunk 1]
```diff
@@ -1338,14 +1338,13 @@ pub enum ExprKind {
...
     /// The `PathSegment` represents the method name and its generic arguments
     /// (within the angle brackets).
-    /// The first element of the vector of an `Expr` is the expression that evaluates
-    /// to the object on which the method is being called on (the receiver),
-    /// and the remaining elements are the rest of the arguments.
-    /// Thus, `x.foo::<Bar, Baz>(a, b, c, d)` is represented as
+    /// The standalone `Expr` is the receiver expression.
+    /// The vector of `Expr` is the arguments.
+    /// `x.foo::<Bar, Baz>(a, b, c, d)` is represented as
     /// `ExprKind::MethodCall(PathSegment { foo, [Bar, Baz] }, [x, a, b, c, d])`.
```
Comment (fmease) [inline compiler/rustc_ast/src/ast.rs:1344]:
```suggestion
    /// `ExprKind::MethodCall(PathSegment { foo, [Bar, Baz] }, x, [a, b, c, d])`.
```

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 2]
```diff
@@ -62,15 +62,17 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
                     let hir_seg = self.arena.alloc(self.lower_path_segment(
                         e.span,
                         seg,
                         ParamMode::Optional,
                         ParenthesizedGenericArgs::Err,
                         ImplTraitContext::Disallowed(ImplTraitPosition::Path),
                     ));
-                    let args = self.lower_exprs(args);
+                    let args = self.arena.alloc_from_iter(
+                        [&*receiver].into_iter().chain(args.iter()).map(|x| self.lower_expr_mut(x)),
```
Comment (nagisa) [inline compiler/rustc_ast_lowering/src/expr.rs:74]: Given how much better the AST is from having the receiver be separate, it makes me wonder if HIR would benefit just as much…

**Review by nagisa — APPROVED** [review]
This looks great to me. r=me once this passes CI.
