### PR TITLE
Remove wasm legacy abi

### LINKED ISSUE #71871: WebAssembly ABI mismatch between clang and rust
When I compile this C code to `wasm32-wasi`:

```c
typedef struct Vector {
    int a;
    int b;
} Vector;

extern int extract_a(Vector v) {
    return v.a;
}
```

And this Rust code to `wasm32-wasi`:

```rust
#[repr(C)]
struct Vector {
    a: i32,
    b: i32,
}

extern "C" {
    fn extract_a(v: Vector) -> i32;
}

fn main() {
    unsafe {
        extract_a(Vector { a: 5, b: 4 });
    }
}
```

And try link them together, I'm getting linking errors:

```
  = note: lld: error: function signature mismatch: extract_a
          >>> defined as (i32, i32) -> i32 in /home/pierre/Projets/wasm-abi-test/target/wasm32-wasi/debug/deps/wasm_abi_test.67xpw7l331r9o5x.rcgu.o
          >>> defined as (i32) -> i32 in /home/pierre/Projets/wasm-abi-test/target/wasm32-wasi/debug/build/wasm-abi-test-9c49ce7f6c5ca031/out/libfoo.a(test.o)
```

It seems that, according to clang, passing a struct by value should inline the fields, while for Rust it should be passed by pointer.

I uploaded an example project here: https://github.com/tomaka/wasm-abi-test
It can be built with something like:
> AR_wasm32_wasi=/path/to/wasi-sdk-10.0/bin/ar CC_wasm32_wasi=/path/to/wasi-sdk-10.0/bin/clang cargo run --target=wasm32-wasi

Rust version: rustc 1.44.0-nightly (38114ff16 2020-03-21)

### LINKED ISSUE #88152: rustc disagrees with emcc about WASM struct ABI in parameters
I have the following Rust code, being compiled with `cargo +nightly build --target wasm32-unknown-unknown`

```rust
// in crate "em"

#[repr(C)]
pub struct Options {
    a: u8,
    b: u8
}

#[no_mangle]
pub extern "C" fn take_struct(o: Options) {}
```

And the following C++ code, compiled with `emcc -std=c++17 test.cpp target/wasm32-unknown-unknown/debug/libem.a -ldl -lpthread -lm -g -o main.html --emrun -sWASM=1` (using the [emscripten sdk](https://emscripten.org/docs/getting_started/downloads.html))

```cpp
# test.cpp 
extern "C" {
    typedef struct Options {
        uint8_t a;
        uint8_t b;
    } Options;
    void take_struct(Options o);
}

int main() {
    Options o;
    take_struct(o);
    return 0;
}
```

I expected to see this happen: The code would compile without warnings and run fine.

Instead, this happened:

emcc shows up the following warning:

```
wasm-ld: warning: function signature mismatch: take_struct
>>> defined as (i32) -> void in /tmp/emscripten_temp_qz2pbc3_/test_0.o
>>> defined as (i32, i32) -> void in target/wasm32-unknown-unknown/debug/libem.a(em.zb05z167nruq6bs.rcgu.o)
```

and running `main.html` in the browser throws the following error (to be expected based on the warning)

```
exception thrown: RuntimeError: unreachable,RuntimeError: unreachable
    at signature_mismatch:take_struct (http://localhost:8000/main.wasm:wasm-function[1]:0x165)
    at __original_main (http://localhost:8000/main.wasm:wasm-function[2]:0x1f1)
    at main (http://localhost:8000/main.wasm:wasm-function[3]:0x20e)
    at http://localhost:8000/main.js:1560:22
    at callMain (http://localhost:8000/main.js:2142:15)
    at doRun (http://localhost:8000/main.js:2212:23)
    at http://localhost:8000/main.js:2223:7
```

Seems like rustc believes that the signature for `fn({u8, u8})` should be `(i32, i32) -> void`, whereas emcc believes it should be `(i32) -> void`.

A lot of other function signatures work (including returning `Option`), it's specifically when such a struct is a parameter that this happens.

I'm not sure which side is at fault here, but an incompatibility between Rust and emcc means that it won't be possible to use WASM with C++ programs that embed a little Rust (or vice versa), which seems like a problem worth highlighting. I think there are other ways to compile C++ to WASM via clang that I need to check out next.

### Meta

<details>
<summary> Version info </summary>

```
$ rustc --version --verbose
rustc 1.56.0-nightly (2d2bc94c8 2021-08-15)
binary: rustc
commit-hash: 2d2bc94c8c3aa778e191f80261c726e4777439f1
commit-date: 2021-08-15
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.27 (7e538a419c3649f3a540a57beab347aa8f6c6271)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

</details>

cc @fitzgen

### LINKED ISSUE #115666: wasm32-unknown-unknown "C" ABI doesn't use proper ABI adjustments
rustc has a `PassMode` enum to declare how arguments should be passed between functions. `PassMode::Direct` is used for the simple case where we can just generate LLVM IR with an argument type that matches the usual LLVM type for this Rust type. It should only be used for types with `Scalar` or `Vector` ABI; for larger types, Rust will generate LLVM struct/union types and those
- are sometimes adjusted to obtain better code generation
- make it very hard to reason about our effective ABI, since it depends on how LLVM lowers those complex struct types into an effective ABI. In particular, this causes a huge risk of violating our ABI compatibility guarantees, e.g. for `repr(transparent)` types.

Unfortunately the compiler never had an assertion ensuring that `PassMode::Direct` is only used with `Scalar`/`Vector` types, and so one target accidentally broke this rule: wasm32-unknown-unknown. Later all wasm targets got an `extern "wasm"` ABI that has the same issue. We should find some way to fix this target, as the current situation makes life harder for anyone wanting to tweak our Rust-to-LLVM-type-mapping, and for alternative backends that have to match our effective ABI.

The issue is that last time @bjorn3 tried to fix this, it lead to https://github.com/rust-lang/rust/issues/81386 and had to be reverted. It will be basically impossible to do this change without breaking the ABI at least for some cases. I'm not sure how much ABI breakage we can get away with. This might have to be blocked on https://github.com/rust-lang/compiler-team/issues/672 which should help to implement the current effective ABI at least for types that are ABI-stable (i.e., `repr(C)` and `repr(transparent)`).

Cc https://github.com/rust-lang/rust/issues/122532

### LINKED ISSUE #122532: Tracking Issue for perma-unstable `wasm-c-abi` flag
This is a tracking issue for the MCP "perma-unstable `wasm-c-abi` flag" (https://github.com/rust-lang/compiler-team/issues/703).

For background, see https://github.com/rust-lang/compiler-team/issues/703. The short summary is that the ABI rustc uses for `extern "C"` on wasm32-unknown-unknown is not spec-compliant and exposes various unstable implementation details of rustc and LLVM. We plan to transition to the official "C" ABI for this target. This will change how non-scalar arguments are passed across this ABI boundary, so if you have code running that is built for wasm32-unknown-unknown and called directly by JavaScript, it may have to be adjusted to follow the new ABI rules. Options for how to manage the transition are still being considered; see https://github.com/rust-lang/rust/issues/138762 for further guidance.

The `-Zwasm-c-abi` flag lets you test your code with the new ABI.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the MCP (cc @rust-lang/compiler -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- ~~Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure])~~
- ~~Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])~~

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Implementation history

- https://github.com/rust-lang/rust/pull/117919
- https://github.com/rust-lang/rust/pull/117918
- https://github.com/rust-lang/rust/pull/133951
- https://github.com/rust-lang/rust/pull/138601

### Related issues
- https://github.com/rust-lang/rust/issues/115666
- https://github.com/rust-lang/rust/issues/138762

### LINKED ISSUE #129486: Wasm ABI special cases scalar pairs (against tool conventions) and is not documented
This is a bit of a hybrid bug report and documentation request. I suspect the "bug" will require a breaking change to fix so may be a non-starter.

In [Diplomat](https://github.com/rust-diplomat/diplomat) we've been writing bindings to Rust from JS/Wasm. One thing we support is passing structs over FFI, by-value.

According to the [tool conventions](https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md), multi-scalar-field structs are passed "indirectly", and single-scalar structs and scalars are passed directly by-value.

This is not what Rust does. This has previously come up in https://github.com/rust-lang/rust/issues/81386. What Rust does is that it always passes structs by-value, which on the JS side means that the struct is "splatted" across the arguments _including padding_.

For example, the following type and function

```rust
#[repr(C)]
pub struct Big {
    a: u8,
    // 1 byte padding
    b: u16,
    // 4 bytes padding
    c: u64,
}
#[no_mangle]
pub extern "C" fn big(x: Big) {}
```

gets passed over LLVM IR as 

```llvm
%Big = type { i8, [1 x i8], i16, [2 x i16], i64 }
define dso_local void @big(%Big %0) unnamed_addr #0 {...}
```

In JS, `big` needs to be called as `wasm.big(a, 0, b, 0, 0, c)`, with `0`s for the padding fields. Note that the padding fields can be different sizes, which is usually irrelevant but important here since "two i16s" and "one i32" end up meaning a different number of parameters.  As far as I can tell the padding field has the same size as the alignment of the previous "real" field, but I can't find any documentation on this or even know whether this is a choice on LLVM or Rust's side.

It gets worse, however. Rust seems to special case scalar pairs:

```rust
#[repr(C)]
pub struct Small {
  a: u8,
  // 3 bytes padding
  b: u32
}
#[no_mangle]
pub extern "C" fn small(x: Small) {}
```

```llvm
define dso_local void @small(i8 %x.0, i32 %x.1) unnamed_addr #0 {..}
```

Here, despite `Small` having padding, `small()` gets called as `wasm.small(a, b)`, because the fields got splatted out in the LLVM IR itself, without padding.

This is even stranger when comparing with the tool conventions because they have no mention of scalar pairs.

It would be really nice if Rust followed the documented tool conventions. I suspect that's not going to happen, and, besides, direct parameter passing is likely more efficient here[^1].

Failing that, it seems like it would be nice if "pairs" did not have special behavior compared to structs with more than 2 scalars in them. Ideally I'd like the scalar pair behavior to apply to all structs: always splat out structs into fields, never require padding be passed over FFI. I'm not sure if such a breaking change is possible, though.

Failing that, I think this behavior should be carefully documented. I've been discovering this by trial-and-error, and Rust's behavior contradicts the [extant documentation](https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md), which makes it even more crucial to have documentation on how Rust diverges.

As far as I can tell, this is not a problem for wasm-bindgen since wasm-bindgen doesn't pass structs over FFI by-value, though the failing test mentioned in https://github.com/rust-lang/rust/issues/81386 seems to indicate they care _some_ amount.

 [^1]: Indirect passing means that the JS side basically has to allocate a heap object each time it wishes to call such a function.

### LINKED ISSUE #138762: Tracking issue for wasm32-unknown-unknown's future-incompat warning for C ABI changes
This issue is intended to be a tracking issue for the future-incompat warning being added in https://github.com/rust-lang/rust/pull/138601. This lint is notifying users of an upcoming change to the C ABI used by the `wasm32-unknown-unknown` target, notably around passing aggregates-by-value in parameter position. An exampe of code that will change is:

```rust
#[repr(C)]
pub struct Pair {
    x: u32,
    y: u32,
}

#[unsafe(no_mangle)]
pub extern "C" fn pair_add(pair: Pair) -> u32 {
    pair.x + pair.y
}
```

where today this [generates](https://godbolt.org/z/vzKn4zoYh):

```wasm
(func $pair_add (param i32 i32) (result i32)
  local.get 1
  local.get 0
  i32.add
)
```

but in the future this will [generate](https://godbolt.org/z/E1xPd9o3T):

```wasm
(func (param i32) (result i32)
  local.get 0
  i32.load offset=4
  local.get 0
  i32.load
  i32.add
)
```

More details about this change and its history can be found in the [blog post associated with this change][blogpost]. In short though users need to do one of the following to resolve the warnings:

1. Pin to a stable compiler and don't update until the default has changed.
2. Update to nightly, pass `-Zwasm-c-abi=spec`, and then use that until the default changes. This means signatures will change immediately and work will be necessary to port external JS for example.
3. Update to nightly, pass `-Zwasm-c-abi=legacy`. This will silence the warnings but be warned that code will still break in the future when the ABI changes.
4. Update function signatures to not pass aggregates-by-value, but instead pass them by reference. This works both today and with the future ABI.

The current plan is to change the default ABI mid-summer 2025. This'll get updated with exact timelines as things happen. More background can be found in https://github.com/rust-lang/rust/issues/122532

### Implementation history

- https://github.com/rust-lang/rust/pull/138601
- https://github.com/rust-lang/rust/pull/139809
- https://github.com/rust-lang/rust/pull/139498

[blogpost]: https://blog.rust-lang.org/2025/04/04/c-abi-changes-for-wasm32-unknown-unknown.html

### PR DESCRIPTION
**Pull request by bjorn3**
Closes https://github.com/rust-lang/rust/issues/122532
Closes https://github.com/rust-lang/rust/issues/138762
Fixes https://github.com/rust-lang/rust/issues/71871
Fixes https://github.com/rust-lang/rust/issues/88152
Fixes https://github.com/rust-lang/rust/issues/115666
Fixes https://github.com/rust-lang/rust/issues/129486

### CODE REVIEW

**Comment by daxpedda** [comment]
https://github.com/rust-lang/rust/pull/129630 needs to be reverted or adjusted as well.

**Comment by bjorn3** [comment]
Removed the section in question.

File: compiler/rustc_ty_utils/src/abi.rs [hunk 1]
```diff
@@ -470,33 +470,18 @@ fn fn_abi_sanity_check<'tcx>(
...
-                        // The unstable abi `PtxKernel` also uses Direct for now.
-                        // It needs to switch to something else before stabilization can happen.
-                        // (See issue: https://github.com/rust-lang/rust/issues/117271)
-                        //
-                        // And finally the unadjusted ABI is ill specified and uses Direct for all
-                        // args, but unfortunately we need it for calling certain LLVM intrinsics.
-
-                        match spec_abi {
-                            ExternAbi::Unadjusted => {}
-                            ExternAbi::PtxKernel => {}
```
Comment (RalfJung) [inline compiler/rustc_ty_utils/src/abi.rs:489]: Is the `PtxKernel` exception not needed any more?

Comment (bjorn3) [reply compiler/rustc_ty_utils/src/abi.rs:489]: To avoid conflicts I based this PR on https://github.com/rust-lang/rust/pull/133932 which is the PR for making `extern "ptx-kernel"` have the right abi.

**Comment by alexcrichton** [comment]
Out of curiosity, @bjorn3 did you (or anyone else?) have an expected timeline of when to land this? In the [blog post](https://blog.rust-lang.org/2025/04/04/c-abi-changes-for-wasm32-unknown-unknown/) this was slated for "mid summer" which is IMO any time around now, so at least personally I'd be in support of merging this change at any point now. I'm not sure if there are other stakeholders and thoughts though so wanted to confirm.

**Comment by bjorn3** [comment]
It seems like the future incompat lint only recently started warning in dependencies, so I think we should at least wait until that change lands on stable.

**Comment by alexcrichton** [comment]
Oh? I thought that https://github.com/rust-lang/rust/pull/138601, by nature of being a future-incompat lint, would warn on dependencies too, and that is on stable with 1.87 I believe. Was there a separate change though for specifically turning on the warning for dependencies? (or do you think it'd be best to wait another stable release or so?)

**Comment by bjorn3** [comment]
It did. I think I got confused by the merge conflict caused by https://github.com/rust-lang/rust/pull/141936.

**Review by alexcrichton — APPROVED** [review]
r=me from my perspective as a maintainer of the wasm32-unknown-unknown target. I'm less certain that I have the authority to officially approve and equeue this, but I figure if no one else raises an objection or otherwise enqueues this in the next week or so I'm happy to send it to bors

**Comment by alexcrichton** [comment]
Also, would it make sense to put "Closes #138762" in the PR description too?

**Comment by bjorn3** [comment]
Added that issue and https://github.com/rust-lang/rust/issues/88152.

**Comment by alexcrichton** [comment]
Ah ok it's been awhile now, so feel free to r=me with a rebase.

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 2]
```diff
@@ -342,17 +336,6 @@ fn wasm_functype<'tcx>(tcx: TyCtxt<'tcx>, fn_abi: &FnAbi<'tcx, Ty<'tcx>>, def_id
         other => bug!("wasm pointer size cannot be {other} bits"),
     };
 
-    // FIXME: remove this once the wasm32-unknown-unknown ABI is fixed
-    // please also add `wasm32-unknown-unknown` back in `tests/assembly/wasm32-naked-fn.rs`
-    // basically the commit introducing this comment should be reverted
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:347]: The comment asks to add the target back in a test file -- which the PR does not seem to do? The test file seems to have been renamed to `tests/assembly/naked-functions/wasm32.rs`.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:347]: Opened https://github.com/rust-lang/rust/pull/142565

**Comment by Manishearth** [comment]
No, this is not the plan we agreed upon.

This changes the default at the _same time_ it removes the flag. This is not something that can be easily switched over to for code that needs to test/run on multiple Rust versions.


There was an explicit plan in https://github.com/rust-lang/rust/issues/122532#issuecomment-2729999696, and it seemed to be what everyone coalesced around:


> If you're ok with that, that seems like a reasonable plan to move forward to me, with a possible schedule looking like:
> 
> 1. Land FCW + write blog post.
> 2. Wait for FCW to hit stable
> 3. Change -Zwasm-c-abi default in nightly once FCW is on stable
> 4. Wait for new default to hit stable
> 5. Remove FCW + -Zwasm-c-abi

Admittedly, this is slightly different from what is in [the blog post](https://blog.rust-lang.org/2025/04/04/c-abi-changes-for-wasm32-unknown-unknown/), which makes no claims about when the default will switch over. I should have noticed that oversight, my bad.


The current change puts us in a situation where we cannot write code that targets multiple versions at once. This is a crucial stage in managing transitions: you start with code that only works with the old thing, and then you move to code that works with both the old and new thing, and you finally end up with code that only works with the new thing.


Personally speaking I don't need the legacy ABI to be maintained as a flag: it is sufficient for the `-Zwasm-c-abi` flag to become a singleton flag that is a no-op.

We might have workarounds for this, but it's somewhat frustrating that this is _still_ being handled in a hard-to-transition way after tedious discussions about trying not to do that.

**Comment by bjorn3** [comment]
> There was an explicit plan in https://github.com/rust-lang/rust/issues/122532#issuecomment-2729999696, and it seemed to be what everyone coalesced around:

I didn't remember that comment when I responsed to Alex's question about the status of this PR: https://github.com/rust-lang/rust/pull/133952#issuecomment-2945097465 My bad.

> Personally speaking I don't need the legacy ABI to be maintained as a flag: it is sufficient for the -Zwasm-c-abi flag to become a singleton flag that is a no-op.

I can make a PR to add back a no-op `-Zwasm-c-abi` flag with `spec` as only allowed value. Does that work for you?

**Comment by Manishearth** [comment]
@bjorn3 Yep, it works for me! Still needs some work on my side but it smooths things out and at this point I don't want to drag this out further :)

**Comment by alexcrichton** [comment]
That's my bad as well, apologies for forgetting that!

> but it's somewhat frustrating that this is still being handled in a hard-to-transition way after tedious discussions about trying not to do that.

Sorry for the frustration, but don't forget that this issue has spanned many contributors, years, and possible shapes of solutions. It's tough to keep track of things sometimes. Nevertheless thanks @bjorn3 for quickly making https://github.com/rust-lang/rust/pull/142635!

**Comment by Manishearth** [comment]
@alexcrichton Yes, I am aware, but it's a bit of a "fool me once" situation: this is not the first time this type of breakage has happened, and seeing it happen twice on the same issue _after stakeholders have been pulled in_ is super disheartening. I don't blame individuals for this, but I do think the compiler team might need to improve its processes here. Designing and following principled transition plans has been a failing of the Rust project for ages: the first edition ended up being a lot more work because we found out in the last minute that nobody had actually designed transition plans. It's a repeated problem.

Of course things are tough to keep track of; but we have special carve outs in the process to keep track of things we consider a priority. Transition plans probably should be a priority since they directly affect Rust users and affect Rust's reputation[^1].


 [^1]: When these things happen I have occasionally had to convince other people I work with to not make a big Thing out of it, but it's harder to do so as it starts to be a pattern. Like, I'm not trying to be difficult here, it's just that the more this happens the less I can do to help Rust's reputation here.

**Comment by workingjubilee** [comment]
Looking at it, I don't think there's a mystery why this PR wasn't quite what was intended in the plan. It predated the plan, as it was opened in December of 2024, months before there was decisive motion towards a more gradual migration.

**Comment by workingjubilee** [comment]
@Manishearth We have been trying to get an actual [reviewing checklist](https://github.com/rust-lang/rust-forge/blob/master/src/compiler/reviews.md#reviewing-checklist) together so that PR decisions are not based on vibes quite as much. I believe, that while there wasn't so much of a problem with the code here in terms of simple correctness, that it would not have passed
- Is the PR title and description still accurate?
- Does the PR correctly/incorrectly close relevant issues?

amongst other, more subjective criteria.

Looking at it, I think the tracking issue should have been updated immediately with a direct link to the comment containing the transition plan once it was decided on. That would be the only way, I think, that we would have been likely to have noticed it while reviewing this PR's to-be-closed issues, unless the reviewer was careful to pull sufficient context to the fore of their mind.

**Comment by Manishearth** [comment]
Thanks for the retro! I absolutely expect mistakes to happen and that's fine, but it's important to learn from them too. Glad to hear there's a checklist in the works.

> Looking at it, I don't think there's a mystery why this PR wasn't quite what was intended in the plan. It predated the plan, as it was opened in December of 2024, months before there was decisive motion towards a more gradual migration.


hah, makes sense. Didn't notice that!
