### PR TITLE
Don't suggest the use of  `impl Trait` in closure parameter

### LINKED ISSUE #138932: rustc suggests to use impl trait in closure parameter which doesn't work
### Code

```Rust
let a = |x: dyn Fn()| x();
```

### Current output

```Shell
--> src/lib.rs:14:17
   |
14 |     let a = |x: dyn Fn()| x();
   |                 ^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `(dyn Fn() + 'static)`
help: you can use `impl Trait` as the argument type
   |
14 |     let a = |x: impl Fn()| x();
   |                 ~~~~
help: function arguments must have a statically known size, borrowed types always have a known size
   |
14 |     let a = |x: &dyn Fn()| x();
   |                 +
```

### Desired output

```Shell
help: function arguments must have a statically known size, borrowed types always have a known size
   |
14 |     let a = |x: &dyn Fn()| x();
   |                 +
```

### Rationale and extra context

We start with some obviously invalid code, `rustc` makes two suggestions - pass `&dyn Trait` by reference - this works and use `impl Trait` which doesn't work.

```
error[E0562]: `impl Trait` is not allowed in closure parameters
  --> src/lib.rs:15:17
   |
15 |     let b = |x: impl Fn()| x();
   |                 ^^^^^^^^^
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

For more information about this error, try `rustc --explain E0562`.
```

Usually following compiler suggestions you get closer to having working code, but here this leads to a dead end.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: x86_64-unknown-linux-gnu
release: 1.85.0
LLVM version: 19.1.7
```

### Anything else?

Nightly makes a similar suggestion, also broken.

### PR DESCRIPTION
**Pull request by rperier**
Fixes #138932

### CODE REVIEW

**Comment by rperier** [comment]
r? rust-lang/diagnostics

File: tests/ui/traits/issue-138932.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+fn main() {
```
Comment (mejrs) [inline tests/ui/traits/issue-138932.rs:1]: If you want to reference the issue, a comment like this is the way to go
```
// issue 138932, suggestion to use impl trait in closure parameter is invalid
```

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 2]
```diff
@@ -3018,12 +3018,16 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
                             };
                             let needs_parens = traits.len() != 1;
-                            err.span_suggestion_verbose(
-                                span,
-                                "you can use `impl Trait` as the argument type",
-                                "impl ",
-                                Applicability::MaybeIncorrect,
-                            );
+                            if let Some(hir_id) = hir_id
+                                && self.tcx.parent_hir_node(hir_id).ident().is_some()
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:3022]: `.ident().is_some()` includes (and does not include) a lot of things. it's better for clarity and exhaustiveness to do something like this:

`!matches!(node, Node::Expr(Expr { kind: ExprKind::Closure(_), .. }))`

or (better) to enumerate where this suggestion *is* valid:

`matches!(node, /* everywhere impl Trait argument is valid */)`

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 3]
```diff
@@ -3018,12 +3018,16 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
                                 [] => span_bug!(ty.span, "trait object with no traits: {ty:?}"),
                             };
                             let needs_parens = traits.len() != 1;
-                            err.span_suggestion_verbose(
-                                span,
-                                "you can use `impl Trait` as the argument type",
-                                "impl ",
-                                Applicability::MaybeIncorrect,
-                            );
+                            if let Some(hir_id) = hir_id
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:3021]: please add a comment like "don't recommend impl Trait as a closure argument"

**Review by mejrs — COMMENTED** [review]
Thanks! Regarding the naming of the file, please don't name it `issue-###` , but something descriptive like `dont-suggest-impl-as-closure-arg.rs`.

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs (hunk 2 above)
Comment (rperier) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: Indeed ! I have tried to use the second (better) approach and the right type

**Comment by rperier** [comment]
Fixed and rebased onto master. Do I need to split into two commits ? One for the tests and one for the fix ? Regarding the git history some people do it some other don't. The maintainer has the last word :)  . What do you prefer ?

**Comment by mejrs** [comment]
> Do I need to split into two commits ? One for the tests and one for the fix ?

that's just my personal preference, it is not necessary
