### PR TITLE
note individual lint name in messages set via lint group attribute

### LINKED ISSUE #36846: Lint errors resulting from lint groups or "warnings" meta-lint obscure the original lint name
This has frustrated me several times. Lint errors are at their best when they tell you which lint triggered them. Example

```
fn main() { }
fn foo() { }
```

```
warning: function is never used: `foo`, #[warn(dead_code)] on by default
 --> main.rs:2:1
  |
2 | fn foo() { }
  | ^^^^^^^^^^^^
```

So now I know that if the lint is wrong I can write `allow(dead_code)`. On the other hand:

```
#![deny(warnings)]
fn main() { }
fn foo() { }
```

```
error: function is never used: `foo`
 --> main.rs:3:1
  |
3 | fn foo() { }
  | ^^^^^^^^^^^^
  |
note: lint level defined here
 --> main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^

error: aborting due to previous error
```

Now I have no idea what to write to shut the compiler up. Likewise:

```
#![deny(unused)]
fn main() { }
fn foo() { }
```

### PR DESCRIPTION
**Pull request by zackmdavis**
lint_errors_resulting_from_lint_groups_obscure

Resolves #36846.

r? @jonathandturner 

-----

***Update*** 16 December (new commits): 
lint_group_makeover_party

### CODE REVIEW

**Comment by zackmdavis** [comment]
@jonathandturner are you interested in reviewing (the reason I r?'d you is because you [seemed to express interest](https://github.com/rust-lang/rust/issues/36846#issuecomment-264069631) in the issue comments), or should we tag someone else (perhaps @brson, the issue filer)?

**Comment by jonathandturner** [comment]
@zackmdavis - sorry for the delay.  I'm currently on vacation so I haven't been doing much reviewing.

Just taking a glance, I'd move that new message to a note (without a span) possibly.  Cool that it's there now, though.

**Comment by zackmdavis** [comment]
> I'm currently on vacation so

Oh, sorry to bother you! (I can only hope that my [bad luck of accidentally bothering people on vacation](https://github.com/rust-lang/rust/pull/34084#issuecomment-228793518) does not become a trend.)

> I'd move that new message to a note (without a span)

And presumably also the `#[{}({})] on by default` message on which it is based. Yes, I can do that (on the timescale of some days; I unfortunately don't have a development environment handy right now).

**Comment by zackmdavis** [comment]
Updated:
* 9603a5f moves the `#[level(individual_lint)] on by default` and `#[level(lint_group)] implies #[level(individual_lint)]` into a span-less note, rather than being part of the main lint message, as Jonathan suggests.
* bb685b5 slightly broadens the scope of this pull request, but to a degree that I argue is entirely appropriate: it differentiates between an individual lint _vs._ a lint group having been set on the command line (analogously to the case of lints set via attributes, which inspired this endeavor)

**Comment by zackmdavis** [comment]
* and 7ba8b4d to update the UI tests because somehow `make check` weren't running them for me earlier (?!) although `./x.py test src/test/ui/` works

**Comment by aturon** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
I don't mind reviewing this. 

@zackmdavis -- I would rather expect these clarifications to appear on the "lint level defined here" note, rather than in the main heading. What do you think?

**Comment by nikomatsakis** [comment]
oh, I missed the updated pics.

File: src/test/compile-fail/lint-group-style.rs [hunk 1]
```diff
@@ -22,19 +24,27 @@ mod test {
...
 
-        fn CamelCase() {} //~ WARN function `CamelCase` should have a snake case name
+        fn CamelCase() {}
+        //~^ WARN function `CamelCase` should have a snake case name
+        //~| NOTE #[warn(bad_style)] implies #[warn(non_snake_case)]
 
-        struct snake_case; //~ WARN type `snake_case` should have a camel case name
+        struct snake_case;
+        //~^ WARN type `snake_case` should have a camel case name
+        //~| NOTE #[warn(bad_style)] implies #[warn(non_camel_case_types)]
```
Comment (nikomatsakis) [inline src/test/compile-fail/lint-group-style.rs]: I think these tests should be made into "ui" tests -- see https://github.com/rust-lang/rust/blob/master/src/test/ui/README.md for some tips on how to work with those.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks pretty good! It does seem like there are a few scenarios not tested though. Can you add UI tests for these cases:

- using command-line flags (`-W` etc) that affect a lint indirectly (and hence trigger the "implies" message)
- using each of the various settings (-W etc)

You can customize a test to include compilation flags by putting a `// compile-flags: ...` annotation in the test (ripgrep around for examples).

Thanks!

**Comment by zackmdavis** [comment]
@nikomatsakis moved make-lint-group-style.rs to be a UI test rather than a compile fail test as [you suggested](https://github.com/rust-lang/rust/pull/38103#discussion_r94460982) (b4e7128), added UI tests for command-line -A/-W/-D/-F with a lint group (fc692f5), had to merge in master to get Travis to pass (babce29, 7e50b02)

File: src/test/ui/span/multispan-import-lint.stderr [hunk 2]
```diff
@@ -1,6 +1,8 @@
-warning: unused imports: `Eq`, `Ord`, `PartialEq`, `PartialOrd`, #[warn(unused_imports)] on by default
+warning: unused imports: `Eq`, `Ord`, `PartialEq`, `PartialOrd`
   --> $DIR/multispan-import-lint.rs:11:16
    |
 11 | use std::cmp::{Eq, Ord, min, PartialEq, PartialOrd};
    |                ^^  ^^^       ^^^^^^^^^  ^^^^^^^^^^
+   |
+   = note: #[warn(unused_imports)] on by default
```
Comment (nikomatsakis) [inline src/test/ui/span/multispan-import-lint.stderr]: I'm very happy to see this moved into an auxiliary note. I've always been annoyed by having it on the main message line :)

File: src/test/ui/span/issue-24690.stderr [hunk 3]
```diff
@@ -4,6 +4,7 @@ error: unused variable: `theOtherTwo`
 20 |     let theOtherTwo = 2;
    |         ^^^^^^^^^^^
    |
+   = note: #[deny(warnings)] implies #[deny(unused_variables)]
```
Comment (nikomatsakis) [inline src/test/ui/span/issue-24690.stderr]: it feels like this should be attached to the message below (`lint level defined here`), and also that it should only appear when that message appears (meaning only once), what do you think?

File: src/test/ui/lint/command-line-lint-group-forbid.stderr [hunk 4]
```diff
@@ -0,0 +1,10 @@
+error: variable `_InappropriateCamelCasing` should have a snake case name such as `_inappropriate_camel_casing`
+  --> $DIR/command-line-lint-group-forbid.rs:14:9
+   |
+14 |     let _InappropriateCamelCasing = true;
+   |         ^^^^^^^^^^^^^^^^^^^^^^^^^
+   |
+   = note: `-F bad-style` implies `-F non-snake-case`
```
Comment (nikomatsakis) [inline src/test/ui/lint/command-line-lint-group-forbid.stderr]: I keep being surprised by the ordering here. What do you think about saying "`-F non-snake-case` implied by `-F bad-style` or something?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looking really good. =) I have a few more suggestions, curious as to your opinion.

Oh, and one other thing: can you rebase atop rust-lang/master (and squash, probably), rather than merging master into your branch? Just keeps the history a little cleaner. Thanks.

File: src/test/ui/span/issue-24690.stderr (hunk 3 above)
Comment (zackmdavis) [inline src/test/ui/span/issue-24690.stderr]: I agree that this is desirable, but doing it properly will involve addressing [the `FIXME`](https://github.com/rust-lang/rust/blob/164619a8cf/src/librustc/session/mod.rs#L322-L325) about generalizing one-time diagnostics beyond `span_note`, which looks sufficiently complicated that I'd prefer to do it in a separate PR.

(The most obvious thing to do would be to extract [the body of what is now](https://github.com/rust-lang/rust/blob/164619a8cf/src/librustc/session/mod.rs#L329-L342) `diag_span_note_once` into a more general `diag_once` that takes an enum argument to decide which method to call (`span_note` or `note` or `warn` or _&c._) on the diagnostic builder ... or are macros the way to go here? I think this is out-of-scope for this PR.)

**Comment by zackmdavis** [comment]
@nikomatsakis 

rebased and squashed previous work into 3 commits (down from 8); "implies" _vs._ "implied by" comment addressed in 5bceb47; [prefer to defer](https://github.com/rust-lang/rust/pull/38103#discussion_r94896191) the work to make implied-by-lint-group notes one-time

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@zackmdavis great! :)

**Comment by zackmdavis** [comment]
The Appveyor CI [failure](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1440/job/excc4936s1j0kiae) seems to be [in the Cargo repo](https://github.com/rust-lang/cargo/blob/40a4ce61b/tests/build.rs#L2404), not something I can fix in this pull request. Does @bors know how to "test this Rust branch against this Cargo branch, and merge them both on success", or would we have to force this and fix the Cargo test expectation immediately after?

**Comment by zackmdavis** [comment]
@nikomatsakis ^^ rust-lang/cargo#3513 should fix the Cargo test failure

**Comment by nikomatsakis** [comment]
@zackmdavis ok, I suppose we have to wait for that to land?

**Comment by zackmdavis** [comment]
Yes, but unfortunately there are [currently some yaks in the way](https://github.com/rust-lang/cargo/pull/3513#issuecomment-272097256); to be continued next week

**Comment by nikomatsakis** [comment]
@zackmdavis very good, I'll keep checking in :)

**Comment by nikomatsakis** [comment]
@zackmdavis still blocked?

**Comment by zackmdavis** [comment]
Unfortunately, I've been too distracted with other projects to attempt to extend Cargo's test infrastructure to let us weaken the test expectation to not depend on the exact compiler JSON output, while still checking the JSON that Cargo itself is responsible for. I'd be happy if there's any way to [accept my commit](https://github.com/rust-lang/cargo/pull/3513#issuecomment-271784125) to just check JSON validity in order to unblock this PR, and then leave an issue to re-strengthen the test expectation afterwards, but if that's not an option, I can try to set aside some time Saturday to look at JSON wildcarding

**Comment by nikomatsakis** [comment]
@zackmdavis hmm ok I don't know much about that other PR (which I gather is for cargo, not rust).

**Comment by zackmdavis** [comment]
(force-pushed) @nikomatsakis Ready!! :running_woman: :checkered_flag: :sparkling_heart:

**Comment by zackmdavis** [comment]
I almost want to ask if this can get p=1 just because it's been so long, but that's probably not fair

**Comment by nikomatsakis** [comment]
@zackmdavis older PRs already get priority =)

**Comment by zackmdavis** [comment]
:eyes: *glances at [queue](https://buildbot2.rust-lang.org/homu/queue/rust)*

auuugh 82e42d5 is going to collide with #36320's b7f1d7a4

:crying_cat_face: :sob: :skull: *sobs in existential despair*
