### PR TITLE
Fix vec iter zst alignment

### LINKED ISSUE #148682: `vec::IntoIter::{nth_back,advance_back_by}` creates unaligned reference for ZST with alignment greater than 1
```rust
#[repr(align(8))]
struct Thing;

fn main() {
    let v = vec![Thing, Thing];
    let _ = v.into_iter().nth_back(1);
}
```

Miri output:

```
error: Undefined Behavior: constructing invalid value: encountered an unaligned reference (required 8 byte alignment but found 1)
   --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1
    |
805 | / pub const unsafe fn drop_in_place<T: PointeeSized>(to_drop: *mut T)
806 | | where
807 | |     T: [const] Destruct,
    | |________________________^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `std::ptr::drop_in_place::<[Thing]> - shim(None)` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1: 807:25
    = note: inside `<std::vec::IntoIter<Thing> as std::iter::DoubleEndedIterator>::advance_back_by` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/into_iter.rs:417:13: 417:40
    = note: inside `<std::vec::IntoIter<Thing> as std::iter::DoubleEndedIterator>::nth_back` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/double_ended.rs:192:12: 192:35
note: inside `main`
   --> src/main.rs:6:13
    |
  6 |     let _ = v.into_iter().nth_back(1);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

The stable method `nth_back` calls the unstable method `advance_back_by`. This line inside `advance_back_by` creates an unaligned slice: https://github.com/rust-lang/rust/blob/ceb7df7e6f17c92c7d49f7e4f02df0e68bc9b38b/library/alloc/src/vec/into_iter.rs#L414

A few lines above this code, there's a comment about ZST alignment in the `next_back` method that was seemingly missed while implementing `advance_next_by`.

I have not checked if any other code has a similar problem.

### Meta

Reproducible on the playground with version `1.93.0-nightly (2025-11-07 843f8ce2ebc01d35a304)`

### PR DESCRIPTION
**Pull request by DrAsu33**
Closes rust-lang/rust#148682

### CODE REVIEW

File: tests/ui/issues/issue-zst-nthback-148682.rs
Comment (reddevilmidzy) [inline tests/ui/issues/issue-zst-nthback-148682.rs:1]: It looks like the file name needs to be changed.

https://rustc-dev-guide.rust-lang.org/tests/best-practices.html#test-naming

File: tests/ui/issues/issue-148682.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// check-pass
```
Comment (reddevilmidzy) [inline tests/ui/issues/issue-148682.rs]:
```suggestion
//@ check-pass
```

**Comment by DrAsu33** [comment]
@reddevilmidzy Thanks! Updated as requested.

File: tests/ui/issues/issue-zst-nthback-148682.rs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// @ check-pass
+//test Intolter::nth_back does not cause UB for ZSTs with high alignment
```
Comment (reddevilmidzy) [inline tests/ui/issues/issue-zst-nthback-148682.rs]: Please remove leading spaces from commands, and add a space before comments.

```suggestion
//@ check-pass
// test Intolter::nth_back does not cause UB for ZSTs with high alignment
```

File: tests/ui/issues/issue-zst-nthback-148682.rs
Comment (reddevilmidzy) [reply tests/ui/issues/issue-zst-nthback-148682.rs:1]: Instead of using the issues directory, please refer to [this](https://github.com/rust-lang/rust/blob/main/tests/ui/README.md) and choose a more appropriate location.

**Review by reddevilmidzy — COMMENTED** [review]
and please squash

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149272/42ec52babac2cbf2bb2b9d794f980cbcb3ebe413..96102b7b41fb28dd90207ec58459b6675475a47d)*

File: tests/ui/issues/issue-zst-nthback-148682.rs (hunk 2 above)
Comment (DrAsu33) [reply tests/ui/issues/issue-zst-nthback-148682.rs]: Thanks！It seems that all the CI tests are passed

File: library/alloc/src/vec/into_iter.rs [hunk 3]
```diff
@@ -411,15 +411,19 @@ impl<T, A: Allocator> DoubleEndedIterator for IntoIter<T, A> {
             // SAFETY: same as for advance_by()
             self.end = unsafe { self.end.sub(step_size) };
         }
-        let to_drop = ptr::slice_from_raw_parts_mut(self.end as *mut T, step_size);
+        let to_drop = if T::IS_ZST {
+            //ZST may cause unalignment
```
Comment (chenyukang) [inline library/alloc/src/vec/into_iter.rs]: a nit:
```suggestion
            // ZST may cause unalignment
```

File: tests/ui/iterators/ZST-nthback.rs [hunk 4]
```diff
@@ -0,0 +1,10 @@
+//@ check-pass
+// test Intolter::nth_back does not cause UB for ZSTs with high alignment
+
+#[repr(align(8))]
+struct Thing;
+
+fn main() {
+    let v = vec![Thing, Thing];
+    let _ = v.into_iter().nth_back(1);
+}
```
Comment (hkBst) [inline tests/ui/iterators/ZST-nthback.rs]: The issue shows a reproduction using Miri, so I'm wondering how this test is supposed to reproduce that. IIUC this does the equivalent of "cargo check", no, while what is needed is a miri check.

**Review by hkBst — CHANGES_REQUESTED** [review]

File: tests/ui/iterators/ZST-nthback.rs [hunk 5]
```diff
@@ -0,0 +1,10 @@
+//@ run-pass
```
Comment (workingjubilee) [inline tests/ui/iterators/ZST-nthback.rs]: This still will not be a test we run under miri, I believe.

We do run the standard library's tests under miri, however.

File: src/tools/miri/tests/fail/unaligned_pointers/zst-nthback.rs
Comment (RalfJung) [inline src/tools/miri/tests/fail/unaligned_pointers/zst-nthback.rs:1]: Please use lower-case filenames.

File: src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs [hunk 6]
```diff
@@ -0,0 +1,27 @@
+//@ compile-flags: -Zmiri-symbolic-alignment-check
+//@ run-pass
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs]:
```suggestion
//@compile-flags: -Zmiri-symbolic-alignment-check
```
Please follow the conventions of surrounding files.

File: src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+    // within Vec::IntoIter. The fix (using ptr::NonNull::dangling()) prevents the UB.
+    let mut iter = v.into_iter();
+    let _ = iter.nth_back(1);
+    
+    // Also test nth_back(0) for completeness.
+    let v2 = vec![Thing, Thing];
+    let mut iter2 = v2.into_iter();
+    let _ = iter2.nth_back(0);
+    
+    // The main assertion is that the program runs to completion without Miri reporting UB.
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs]:
```suggestion
```
This doesn't need to be explicitly stated.

File: src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs [hunk 8]
```diff
@@ -0,0 +1,27 @@
+//@ compile-flags: -Zmiri-symbolic-alignment-check
+//@ run-pass
+
+use std::ptr;
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/unaligned_pointers/ZST-nthback.rs]: What are you importing `std::ptr` for?

**Review by RalfJung — COMMENTED** [review]
Some comments for the Miri test. :)
I did not look at the libs part.

FWIW, we do run the standard library test suite in Miri. So maybe it would make more sense to add this there? We already have some tests in the standard library test suite that are primarily meant for Miri.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149272/467250ddb25a93315a8dee02dd6cc1e398be46ff..d7b95bcdee562e19b4504c60503a5434480b5963)*

File: library/alloctests/tests/vec.rs [hunk 9]
```diff
@@ -2718,21 +2718,16 @@ fn vec_null_ptr_roundtrip() {
     unsafe { new.read() };
 }
 
+// Regression test for Undefined Behavior (UB) caused by IntoIter::nth_back (#148682)
+// when dealing with high-aligned Zero-Sized Types (ZSTs).
 #[test] 
 #[cfg(miri)]
```
Comment (RalfJung) [inline library/alloctests/tests/vec.rs]: Why do you only enable this test in Miri?

Comment (DrAsu33) [reply library/alloctests/tests/vec.rs]: Sorry, I thought that the UB could only be detected by miri. I have modified that.

Comment (RalfJung) [reply library/alloctests/tests/vec.rs]: Yeah, only Miri will detect UB. But the test should still pass without Miri, and in particular this enures it gets type-checked.

**Comment by DrAsu33** [comment]
Builds are green and I've addressed all feedback (moved test to library/alloc/tests/vec.rs).

@rustbot ready

**Review by Mark-Simulacrum — CHANGES_REQUESTED** [review]
r=me with extra tests added

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149272/3c5c55864f8f441054730037bc9f9901f9151398..89b4b309b84f45901dd42a65d250549c3070e22f)*

File: library/alloctests/tests/vec.rs [hunk 10]
```diff
@@ -2717,3 +2717,17 @@ fn vec_null_ptr_roundtrip() {
     let new = roundtripped.with_addr(ptr.addr());
     unsafe { new.read() };
 }
+
+// Regression test for Undefined Behavior (UB) caused by IntoIter::nth_back (#148682)
+// when dealing with high-aligned Zero-Sized Types (ZSTs).
+#[test]
+fn zst_vec_iter_nth_back_regression() {
```
Comment (Mark-Simulacrum) [inline library/alloctests/tests/vec.rs]: Can you add tests for other collections that I suspect may well have the same bug? At the very least VecDeque, BTreeMap, HashMap, and BinaryHeap all seem likely to be potentially at risk.
