### PR TITLE
compiler_fence: fix example

### LINKED ISSUE #133014: compiler_fence example is misleading
### Location

https://doc.rust-lang.org/nightly/core/sync/atomic/fn.compiler_fence.html#examples

### Summary

> ```rust
> use std::sync::atomic::{AtomicBool, AtomicUsize};
> use std::sync::atomic::Ordering;
> use std::sync::atomic::compiler_fence;
> 
> static IMPORTANT_VARIABLE: AtomicUsize = AtomicUsize::new(0);
> static IS_READY: AtomicBool = AtomicBool::new(false);
> 
> fn main() {
>     IMPORTANT_VARIABLE.store(42, Ordering::Relaxed);
>     // prevent earlier writes from being moved beyond this point
>     compiler_fence(Ordering::Release);
>     IS_READY.store(true, Ordering::Relaxed);
> }
> 
> fn signal_handler() {
>     if IS_READY.load(Ordering::Relaxed) {
>         assert_eq!(IMPORTANT_VARIABLE.load(Ordering::Relaxed), 42);
>     }
> }
> ```

This example makes it look like there is some kind of guarantee for a release fence that isn't paired with an acquire operation or fence, which as far as I can tell, is not the case. (See the C++ docs for [regular (thread) fences](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence) that do not guarantee anything for an unpaired release fence and [compiler (signal) fences](https://en.cppreference.com/w/cpp/atomic/atomic_signal_fence) that are described as strictly weaker than thread fences.)

So in this example there is no *happens-before* relation between the store of `IMPORTANT_VARIABLE` in main and the load thereof in the signal handler and therefore the signal handler may actually observe `IS_READY == true` and `IMPORTANT_VARIABLE == 0`.

Presumably the example should have a load fence in the signal handler and explain in the prose text above that the loads can be reordered, too:

```diff
fn signal_handler() {
    if IS_READY.load(Ordering::Relaxed) {
+       // prevent later reads from being moved beyond this point
+       compiler_fence(Ordering::Acquire);
        assert_eq!(IMPORTANT_VARIABLE.load(Ordering::Relaxed), 42);
    }
}
```

related: https://github.com/rust-lang/rust/issues/129189

### PR DESCRIPTION
**Pull request by RalfJung**
The old example was wrong, an acquire fence is required in the signal handler. To make the point more clear, I changed the "data" variable to use non-atomic accesses.

Fixes https://github.com/rust-lang/rust/issues/133014

### CODE REVIEW

File: library/core/src/sync/atomic.rs [hunk 1]
```diff
@@ -3727,33 +3727,33 @@ pub fn fence(order: Ordering) {
...
 ///
-/// Without `compiler_fence`, the `assert_eq!` in following code
-/// is *not* guaranteed to succeed, despite everything happening in a single thread.
-/// To see why, remember that the compiler is free to swap the stores to
-/// `IMPORTANT_VARIABLE` and `IS_READY` since they are both
-/// `Ordering::Relaxed`. If it does, and the signal handler is invoked right
-/// after `IS_READY` is updated, then the signal handler will see
-/// `IS_READY=1`, but `IMPORTANT_VARIABLE=0`.
-/// Using a `compiler_fence` remedies this situation.
+/// Without the two `compiler_fence`, the read of `IMPORTANT_VARIABLE` in `signal_handler`
```
Comment (jhpratt) [inline library/core/src/sync/atomic.rs:3730]:
```suggestion
/// Without the two `compiler_fence` calls, the read of `IMPORTANT_VARIABLE` in `signal_handler`
```

(plus line wrapping if necessary)

File: library/core/src/sync/atomic.rs [hunk 2]
```diff
@@ -3727,33 +3727,33 @@ pub fn fence(order: Ordering) {
...
+/// is *undefined behavior* due to a data race, despite everything happening in a single thread.
+/// This is because the signal handler is considered to run concurrently with its associated
+/// thread, and explicit synchronization is required to pass data between a thread and its
+/// signal handler. The code below uses two `compiler_fence` to establish the usual
```
Comment (jhpratt) [inline library/core/src/sync/atomic.rs:3734]:
```suggestion
/// signal handler. The code below uses two `compiler_fence` calls to establish the usual
```

File: library/core/src/sync/atomic.rs [hunk 3]
```diff
@@ -3727,33 +3727,33 @@ pub fn fence(order: Ordering) {
...
+/// release-acquire synchronization pattern (see [`fence`] for an image).
 ///
 /// ```
-/// use std::sync::atomic::{AtomicBool, AtomicUsize};
+/// use std::sync::atomic::AtomicBool;
 /// use std::sync::atomic::Ordering;
 /// use std::sync::atomic::compiler_fence;
 ///
-/// static IMPORTANT_VARIABLE: AtomicUsize = AtomicUsize::new(0);
+/// static mut IMPORTANT_VARIABLE: usize = 0;
```
Comment (jhpratt) [inline library/core/src/sync/atomic.rs:3742]: Given the push (afaict) to stop using `static mut` as much as feasible, is there a better example that could be used?

Comment (RalfJung) [reply library/core/src/sync/atomic.rs:3742]: I'm not sure how using `SyncUnsafeCell` would make anything better here.

We specifically closed https://github.com/rust-lang/rust/issues/53639 since by forbidding *references* to `static mut`, we are catching most of the issue, and the rest would be just unnecessary ceremony.

Comment (jhpratt) [reply library/core/src/sync/atomic.rs:3742]: I must have missed that FCP, as I thought deprecation was still planned. That's good enough for my concern here.
