### PR TITLE
Do not print visibility in external traits

### LINKED ISSUE #81274: Wrong `pub` modifier in each function of trait documentation
The [documentation of Iterator](https://doc.rust-lang.org/1.49.0/std/iter/trait.Iterator.html#tymethod.next) trait on 1.49.0 (current stable) doesn't contain `pub` modifier in function declaration of that trait.
image
However, on [beta](https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html#tymethod.next) and nightly, there is `pub` modifier.
image

This is wrong because you cannot use `pub` modifier for each method/function in Trait definition.
Why is this important? People copy the method/function declaration in the documentation to their code
and see the compiler error: `error[E0449]: unnecessary visibility qualifier`. 

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

cc @jyn514 I think this might relate to some changes in visibility around macros ?

### PR DESCRIPTION
**Pull request by Stupremee**
This PR fixes the bug that caused traits, which were re-exported, having visibility modifiers in front of methods, which is invalid.

It would be nice to add a test for this, but I don't even know if tests with multiple crates are possible.

Resolves #81274

### CODE REVIEW

**Comment by jyn514** [comment]
> It would be nice to add a test for this, but I don't even know if tests with multiple crates are possible.

They are - search for `aux-build` and `build-aux-docs` in src/test/rustdoc (and there's also some instructions in https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts).

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -193,8 +193,20 @@ crate fn record_extern_fqn(cx: &mut DocContext<'_>, did: DefId, kind: ItemType)
...
+        .associated_items(did)
+        .in_definition_order()
+        .map(|item| {
+            // When building an external trait, the cleaned trait will have all items public,
+            // which causes methods to have a `pub` prefix, which is invalid since items in traits
+            // can not have a visibility prefix. Thus we override the visibility here manually.
+            // See https://github.com/rust-lang/rust/issues/81274
+            let mut item = item.clean(cx);
+            item.visibility = Visibility::Inherited;
+            item
```
Comment (jyn514) [inline src/librustdoc/clean/inline.rs:207]: nit: I think this looks nicer.
```suggestion
            Item { visibility: Visibility::Inherited, ..item.clean(cx) }
```

File: test.rs [hunk 2]
```diff
@@ -0,0 +1,32 @@
+type Array<T, const N: usize> = [T; N];
```
Comment (jyn514) [inline test.rs:1]: This should go in src/test/rustdoc somewhere (maybe `trait-visibility.rs` or something).

File: test.rs [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+pub type A0 = [i32; 3]; // printed correctly
+pub type A1 = Array<i32, 3>; // printed INCORRECTLY as `[i32; T]`
+pub struct B0(pub [i32; 3]); // printed correctly
+pub struct B1(pub Array<i32, 3>); // printed INCORRECTLY as `B1(pub [i32; T])`
```
Comment (jyn514) [inline test.rs:6]: Did you add this file by accident? It doesn't seem to be related to this PR.

Comment (Stupremee) [reply test.rs:6]: Yes :sweat_smile:

**Comment by jyn514** [comment]
Can you squash the commits? r=me with that done and CI passing :)

**Comment by Stupremee** [comment]
r? @jyn514 

whoops
