### PR TITLE
Fix invalid HTML escape

### LINKED ISSUE #46289: Double quote are badly generated in the sidebar.
Working on it.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #46289.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -2292,20 +2292,35 @@ fn item_function(w: &mut fmt::Formatter, cx: &Context, it: &clean::Item,
...
-           abi = AbiSpace(f.abi),
-           name = it.name.as_ref().unwrap(),
-           generics = f.generics,
-           where_clause = WhereClause { gens: &f.generics, indent: 0, end_newline: true },
-           decl = Method {
-               decl: &f.decl,
-               name_len,
-               indent: 0,
-           })?;
+    if w.alternate() {
```
Comment (ollie27) [inline src/librustdoc/html/render.rs]: What is this change for? `item_function` is only used to produce HTML.

File: src/librustdoc/html/render.rs [hunk 2]
```diff
@@ -2706,25 +2721,47 @@ fn render_assoc_item(w: &mut fmt::Formatter,
...
-                   decl: d,
-                   name_len: head_len,
-                   indent,
-               },
-               where_clause = WhereClause {
-                   gens: g,
-                   indent,
-                   end_newline,
-               })
+        if w.alternate() {
```
Comment (ollie27) [inline src/librustdoc/html/render.rs]: Again, what is this for?

File: src/librustdoc/html/render.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs]: Because in the slidebar on the left, we call these function and escape the text once again. Guess what happens when you escape a string twice?

Comment (ollie27) [reply src/librustdoc/html/render.rs]: This function isn't used for rendering the sidebar. This piece of code is rendering the `<pre>` block at the top of function pages.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs]: Yes but does it hurt to have this? Seems logical that the `alternate` handling is propagated to the children no? But if it's an issue, I'll just remove it.

Comment (ollie27) [reply src/librustdoc/html/render.rs]: `alternate` is never set so this is an issue because it's dead code.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs]: Ok, I'll just remove the update in here then.

**Comment by GuillaumeGomez** [comment]
@ollie27: You were absolutely right, the first change was completely useless. It even allowed me to see that the url encoding was incomplete. Thanks for that too! :)

File: src/librustdoc/html/render.rs (hunk 2 above)
Comment (ollie27) [reply src/librustdoc/html/render.rs]: This change still needs to be removed.
