### PR TITLE
Recover from parse errors in literal struct fields and incorrect float literals

### LINKED ISSUE #52496: Incorrect/misleading error messages after syntax errors in struct initializers
```rust
struct Foo { bar: f64, baz: i64 }
fn main() {
   let _ = Foo { bar: .5, baz: 42 };
   let bar = 1.5f32;
   let _ = Foo { bar.into(), baz: -1 };
}
```

The first struct reports missing fields, `bar` and `baz` due to the syntax error:
```rust
error: expected expression, found `.`
 --> src/main.rs:3:23
  |
3 |    let _ = Foo { bar: .5, baz: 42 };
  |            ---        ^ expected expression
  |            |
  |            while parsing this struct

error[E0063]: missing fields `bar`, `baz` in initializer of `Foo`
 --> src/main.rs:3:12
  |
3 |    let _ = Foo { bar: .5, baz: 42 };
  |            ^^^ missing `bar`, `baz`
```

The second struct reports a missing field `baz`, and suggests an obviously wrong fix for a type mismatch error:

```rust
error: expected one of `,` or `}`, found `.`
 --> src/main.rs:5:21
  |
5 |    let _ = Foo { bar.into(), baz: -1 };
  |                     ^ expected one of `,` or `}` here

error[E0308]: mismatched types
 --> src/main.rs:5:18
  |
5 |    let _ = Foo { bar.into(), baz: -1 };
  |                  ^^^ expected f64, found f32
help: you can cast an `f32` to `f64` in a lossless way
  |
5 |    let _ = Foo { bar.into().into(), baz: -1 };
  |                  ^^^^^^^^^^

error[E0063]: missing field `baz` in initializer of `Foo`
 --> src/main.rs:5:12
  |
5 |    let _ = Foo { bar.into(), baz: -1 };
  |            ^^^ missing `baz`
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #52496.

### CODE REVIEW

File: src/test/ui/issues/issue-52496.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+fn main() {
+    let _ = Foo { bar: .5, baz: 42 };
+    //~^ ERROR numeric float literals must have a significant
+    //~| ERROR missing field `bat` in initializer of `Foo`
+    //~| ERROR mismatched types
+    let bar = 1.5f32;
+    let _ = Foo { bar.into(), bat: -1, . };
+    //~^ ERROR expected one of
+    //~| ERROR mismatched types
+    //~| ERROR missing field `baz` in initializer of `Foo`
```
Comment (VirrageS) [inline src/test/ui/issues/issue-52496.rs]: Shouldn't:
```rust
//~| ERROR missing field `bat` in initializer of `Foo`
```
be also included?

Comment (VirrageS) [reply src/test/ui/issues/issue-52496.rs]: Oh right, I was looking at stderr and now realized that the order of errors is not same as the lines number (it seems more random). My apologies.

File: src/test/ui/issues/issue-52496.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+struct Foo { bar: f64, baz: i64, bat: i64 }
+
+fn main() {
+    let _ = Foo { bar: .5, baz: 42 };
+    //~^ ERROR numeric float literals must have a significant
```
Comment (theotherphil) [inline src/test/ui/issues/issue-52496.rs]: Where does this terminology come from? The error message does not make sense to me.

Comment (jonas-schievink) [reply src/test/ui/issues/issue-52496.rs]: Agreed, the term "significant" (or rather, "significand") has a specific meaning in the realm of floating-point encoding which seems misleading here. I suggest using something like "integer part" instead. The "numeric" can also be dropped since floats can't really be non-numeric (unless you count hexadecimal float literals, which aren't supported anyway).

Comment (estebank) [reply src/test/ui/issues/issue-52496.rs]: Yeah, I was having trouble coming up with a good message for this. What about "float literals must have a integer part"?

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -1988,6 +1989,32 @@ impl<'a> Parser<'a> {
...
+                    let mut err = self.diagnostic()
+                        .struct_span_err(sp, "numeric float literals must have a significant");
+                    err.span_suggestion_with_applicability(
+                        sp,
+                        "numeric float literals must have a significant",
+                        format!("0.{}", val),
+                        Applicability::MachineApplicable,
+                    );
+                    err.emit();
+                    return Ok(ast::LitKind::Float(val, ast::FloatTy::F32));
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: It'd be better if this didn't evaluate to `f32` and instead evaluated to `{float}`, to avoid knock down type errors.

File: src/test/ui/issues/issue-52496.rs (hunk 2 above)
Comment (jonas-schievink) [reply src/test/ui/issues/issue-52496.rs]: *an* integer part, but yeah that sounds good.

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (jonas-schievink) [reply src/libsyntax/parse/parser.rs]: I believe you can use `FloatUnsuffixed` for that

File: src/test/ui/issues/issue-52496.rs (hunk 2 above)
Comment (estebank) [reply src/test/ui/issues/issue-52496.rs]: done

File: src/libsyntax/parse/parser.rs (hunk 3 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: How did I not _see_ that!?

Thanks @jonas-schievink

File: src/test/ui/issues/issue-52496.stderr [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+  --> $DIR/issue-52496.rs:4:13
+   |
+LL |     let _ = Foo { bar: .5, baz: 42 };
+   |             ^^^ missing `bat`
+
+error[E0308]: mismatched types
+  --> $DIR/issue-52496.rs:8:19
+   |
+LL |     let _ = Foo { bar.into(), bat: -1, . };
+   |                   ^^^ expected f64, found f32
```
Comment (estebank) [inline src/test/ui/issues/issue-52496.stderr]: If we want to avoid these we can remove the `recovery_field` and we'll get an error about missing `bar`. That might be more reasonable than what we're doing here.

File: src/test/ui/parser/removed-syntax-with-1.rs [hunk 5]
```diff
@@ -7,5 +7,5 @@ fn main() {
     let a = S { foo: (), bar: () };
     let b = S { foo: () with a };
     //~^ ERROR expected one of `,`, `.`, `?`, `}`, or an operator, found `with`
-    //~| ERROR missing field `bar` in initializer of `main::S`
+    //~| ERROR missing fields `bar`, `foo` in initializer of `main::S`
```
Comment (oli-obk) [inline src/test/ui/parser/removed-syntax-with-1.rs]: This feels like a regression to me. The `foo` field has been given. I understand this was done deliberately (https://github.com/rust-lang/rust/pull/57779/files#diff-da9d34ca1d0f6beee2838cf02e07345cR2720) for the `S { foo.cake(), bar: () }` situation. Do you think it would be feasible to only report the field if `parse_field` parsed a shorthand field pattern? If a `:` was specified, and the field was parsed successfully, then the field isn't "missing" per se.

**Review by davidtwco — APPROVED** [review]

**Comment by michaelwoerister** [comment]
It seems like @davidtwco and @oli-obk have already taken a look at this. Feel free r+ if you think this is good to go. (Otherwise I'll take a closer look tomorrow)

File: src/test/ui/parser/removed-syntax-with-1.rs (hunk 5 above)
Comment (estebank) [reply src/test/ui/parser/removed-syntax-with-1.rs]: Done.
