### PR TITLE
rustdoc: fix intra-link for generic trait impls

### LINKED ISSUE #92662: Rustdoc: regression in intra-doc link to trait function
### Code

Example code:

```rust
#![deny(rustdoc::broken_intra_doc_links)]

use std::marker::PhantomData;

pub trait Bar<T> {
    fn bar(&self);
}

pub struct Foo<U>(PhantomData<U>);

impl<T, U> Bar<T> for Foo<U> {
    fn bar(&self) {}
}

/// link to [`Foo::bar`]
fn main() {}

```

### Version it worked on

docs build successfully on 1.57.0:
```
$ cargo +1.57.0 --version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
$ cargo +1.57.0 doc
 Documenting trait-link-example v0.1.0 (/tmp/trait-link-example)
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
```

### Version with regression
docs fail to build on 1.59.0-nightly (358e79fe5 2022-01-04):
```
$ cargo +nightly-2022-01-07 --version
cargo 1.59.0-nightly (358e79fe5 2022-01-04)
$ cargo +nightly-2022-01-07 doc
 Documenting trait-link-example v0.1.0 (/tmp/trait-link-example)
error: unresolved link to `Foo::bar`
  --> src/main.rs:15:15
   |
15 | /// link to [`Foo::bar`]
   |               ^^^^^^^^ the struct `Foo` has no field or associated item named `bar`
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![deny(rustdoc::broken_intra_doc_links)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not document `trait-link-example`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type bin --crate-name trait_link_example src/main.rs -o /tmp/trait-link-example/target/doc --error-format=json --json=diagnostic-rendered-ansi,future-incompat --document-private-items -C metadata=af2f029e3f5db9a3 -L dependency=/tmp/trait-link-example/target/debug/deps --crate-version 0.1.0` (exit status: 1)
```

</p>
</details>

The generics appear necessary for the bug. Removing them from either the type or the trait resolves the failure.

### PR DESCRIPTION
**Pull request by mdibaiee**
fixes #92662

r? @camelid

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -903,7 +903,15 @@ fn traits_implemented_by<'a>(
...
             // Fast path: if this is a primitive simple `==` will work
-            let saw_impl = impl_type == ty;
+            let saw_impl = impl_type == ty
+                || match (impl_type.kind(), ty.kind()) {
+                    (ty::Adt(def, _), ty::Adt(tydef, _)) => {
+                        debug!("adt def_id: {:?}", def.did);
+                        def.did == tydef.did
+                    }
+                    (ty::Foreign(def_id), ty::Foreign(tydef_id)) => def_id == tydef_id,
+                    _ => false,
```
Comment (mdibaiee) [inline src/librustdoc/passes/collect_intra_doc_links.rs:913]: @camelid your intuition was right: this piece was necessary, but I was not sure at the time how to compare them, but I think this is the way: if they both having matching types, we compare the `def_id` alone, this allows users to write `Foo` without the generic type parameters, and still have it match with `Foo<T>`. That's my understanding.

Regarding the `Foreign`, I'm not sure what that means to be honest, any ideas how can I test that case too to avoid regressions again?

File: src/test/rustdoc/intra-doc/generic-trait-impl.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+    fn bar(&self);
+}
+
+pub struct Foo<U>(PhantomData<U>);
+
+impl<T, U> Bar<T> for Foo<U> {
+    fn bar(&self) {}
+}
+
+// @has generic_trait_impl/fn.main.html '//a/@href' 'struct.Foo.html#method.bar'
```
Comment (camelid) [inline src/test/rustdoc/intra-doc/generic-trait-impl.rs:17]: Can you make the test the following? This'll help make sure we're testing the intra-doc link and not some other link.

```suggestion
// @has generic_trait_impl/fn.main.html '//a[@href="struct.Foo.html#method.bar"]' 'Foo::bar'
```

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs:913]: I think that explanation sounds right.

The `Foreign` is an `extern type` I believe (feature gate `#![feature(extern_types)]`; issue #43467).

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -903,7 +903,15 @@ fn traits_implemented_by<'a>(
                 ty
             );
             // Fast path: if this is a primitive simple `==` will work
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links.rs:905]: To avoid this happening again by mistake:

```suggestion
            // Fast path: if this is a primitive simple `==` will work
            // NOTE: The `match` is required; see #92662.
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -903,7 +903,15 @@ fn traits_implemented_by<'a>(
...
-            let saw_impl = impl_type == ty;
+            let saw_impl = impl_type == ty
+                || match (impl_type.kind(), ty.kind()) {
+                    (ty::Adt(def, _), ty::Adt(tydef, _)) => {
+                        debug!("adt def_id: {:?}", def.did);
+                        def.did == tydef.did
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links.rs:910]: The variable names are a bit unclear, and it'd be good to log both:

```suggestion
                    (ty::Adt(impl_def, _), ty::Adt(ty_def, _)) => {
                        debug!(?impl_def, ?ty_def);
                        impl_def.did == ty_def.did
```

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:913]: @camelid I actually realised there are already tests for Foreign, and because the `ty::Foreign` only has one field, the `def_id`, doing a `==` covers what we are doing. The tests are passing without this case in the `match`. I removed them.

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/intra-doc/extern-type.rs

**Review by GuillaumeGomez — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: That test doesn't test trait impls on extern types, though. Can you please add a test case for that?

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: > because the ty::Foreign only has one field, the def_id, doing a == covers what we are doing.

Hmm, what does having only one field have to do with it?

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: @camelid wrote tests for impl traits of extern types.

regarding the other question, `Foreign` which is a `TyKind` has derived `Eq`, and as far as I understand about derived `Eq` of algebraic data types, the implementation is just applying `Eq` to all the fields of that type. In this case, `Foreign` is a tuple with a single field, the `DefId`, so when you do `foreign1 == foreign2`, it's identical to `def_id1 == def_id2`, that's all there is to compare.

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: It's true that `TyKind` has derived `Eq`, but `Ty` manually implements it and uses pointer equality (because `Ty`s are interned).

What I was asking is why it's okay to skip manually equating `Foreign` but not `Adt`.

File: src/test/rustdoc/intra-doc/generic-trait-impl.rs [hunk 5]
```diff
@@ -0,0 +1,19 @@
+#![deny(rustdoc::broken_intra_doc_links)]
+
+// Test intra-doc links on trait implementations with generics
```
Comment (camelid) [inline src/test/rustdoc/intra-doc/generic-trait-impl.rs:3]: Can you note that this is a regression test for #92662.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: @camelid ah I see. I'm not sure then... I suppose we have the same question about all the other types, not just Foreign

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Oh 🤦 

The reason it's necessary for `Adt`s is because we want to ignore generics since the `ty` we're matching against may just have placeholders (or similar). Can you add a comment about that?

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: yes... that's what I mean with my initial comment on this piece https://github.com/rust-lang/rust/pull/92792#discussion_r782573159, I didn't get my message through well 😁

Comment (camelid) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Yeah, I think I read your message and understood partially but then got confused later 😆

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 6]
```diff
@@ -903,7 +903,15 @@ fn traits_implemented_by<'a>(
                 ty
             );
             // Fast path: if this is a primitive simple `==` will work
-            let saw_impl = impl_type == ty;
+            // NOTE: the `match` is necessary; see #92662.
+            let saw_impl = impl_type == ty
+                || match (impl_type.kind(), ty.kind()) {
+                    (ty::Adt(impl_def, _), ty::Adt(ty_def, _)) => {
```
Comment (camelid) [inline src/librustdoc/passes/collect_intra_doc_links.rs:909]:
```suggestion
                    (ty::Adt(impl_def, _), ty::Adt(ty_def, _)) => {
                        // We intentionally don't compare generics because ...
```

Comment (mdibaiee) [reply src/librustdoc/passes/collect_intra_doc_links.rs:912]: @camelid I just pushed a comment, see if that's good enough or if you have feedback

**Review by camelid — APPROVED** [review]
Thanks!

**Comment by mdibaiee** [comment]
@camelid thanks for your review!

**Comment by camelid** [comment]
Beta-nominating because the I believe the regression is on beta now.

**Comment by pnkfelix** [comment]
discussed in compiler triage meeting. backport approved.
