### PR TITLE
Give a specific lint for unsafety not being inherited

### LINKED ISSUE #94077: Confusing message when using unsafe to initialize statics
Given the following code: 

```rust
fn foo() {
    unsafe {
        static BAR: u32 = std::mem::transmute(0_i32);
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
warning: unnecessary `unsafe` block
 [--> src/lib.rs:2:5
](https://play.rust-lang.org/#)  |
2 |     unsafe {
  |     ^^^^^^ unnecessary `unsafe` block
  |
  = note: `#[warn(unused_unsafe)]` on by default

error[[E0133]](https://doc.rust-lang.org/stable/error-index.html#E0133): call to unsafe function is unsafe and requires unsafe function or block
 [--> src/lib.rs:3:27
](https://play.rust-lang.org/#)  |
3 |         static BAR: u32 = std::mem::transmute(0_i32);
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
  |
  = note: consult the function's documentation for information on how to avoid undefined behavior

For more information about this error, try `rustc --explain E0133`.
warning: `playground` (lib) generated 1 warning
error: could not compile `playground` due to previous error; 1 warning emitted
```

Ideally the output should look like:

It could suggest moving the unsafe block:

```
static BAR: u32 = unsafe { std::mem::transmute(0_i32) };
                  ^^^^^^
```
Or perhaps this should be valid? It *is* inside an unsafe block after all.

### PR DESCRIPTION
**Pull request by clubby789**
In cases like
```rs
static mut FOO: u64 = 0;
fn main() {
    unsafe {static BAR: u64 = FOO;}    
}
```
and
```rs
fn foo() {
  unsafe {
    fn bar() {
      unsafe_call();
    }
  }
}
```
Specifically inform the user that the unsafety is not inherited for the seperate enclosing items
Fixes #94077
r? compiler-errors
@rustbot label +A-diagnostics

### CODE REVIEW

File: compiler/rustc_mir_transform/src/check_unsafety.rs [hunk 1]
```diff
@@ -517,24 +518,49 @@ pub fn check_unsafety(tcx: TyCtxt<'_>, def_id: LocalDefId) {
...
-        let unsafe_fn_msg =
-            if unsafe_op_in_unsafe_fn_allowed(tcx, lint_root) { " function or" } else { "" };
-
         match kind {
             UnsafetyViolationKind::General => {
                 // once
-                struct_span_err!(
+                // Mutable statics always require an unsafe block
+                let unsafe_fn_msg = if unsafe_op_in_unsafe_fn_allowed(tcx, lint_root)
+                    && details != UnsafetyViolationDetails::UseOfMutableStatic
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/check_unsafety.rs:526]: This should really depend on what item we're currently within, not on what kind of unsafety violation this is.

File: compiler/rustc_mir_transform/src/check_unsafety.rs [hunk 2]
```diff
@@ -517,24 +518,49 @@ pub fn check_unsafety(tcx: TyCtxt<'_>, def_id: LocalDefId) {
...
-                .note(note)
-                .emit();
+                );
+                err.span_label(source_info.span, description).note(note);
+                let note_non_inherited = tcx.hir().parent_iter(lint_root).find(|(id, node)| {
+                    if let Node::Expr(block) = node
+                        && let ExprKind::Block(block, _) = block.kind
+                        && let BlockCheckMode::UnsafeBlock(_) = block.rules {
+                            true
+                        }
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/check_unsafety.rs:547]:
```suggestion
                        && let BlockCheckMode::UnsafeBlock(_) = block.rules
                    {
                        true
                    }
```

File: compiler/rustc_mir_transform/src/check_unsafety.rs [hunk 3]
```diff
@@ -517,24 +518,49 @@ pub fn check_unsafety(tcx: TyCtxt<'_>, def_id: LocalDefId) {
...
+                    else if let Some(sig) = tcx.hir().fn_sig_by_hir_id(*id)
+                        && sig.header.is_unsafe() {
+                            true
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/check_unsafety.rs:550]:
```suggestion
                        && sig.header.is_unsafe()
                    {
                        true
```

**Comment by compiler-errors** [comment]
This should be good to go after addressing that one nit and a few formatting inconsistencies!

**Comment by compiler-errors** [comment]
I think this is fine to land as-is -- if anyone has any strong opinions about the wording being made more precise or descriptive, they're welcome to open a follow-up PR.

@bors r+ rollup
