### PR TITLE
stabilize fetch_nand

### LINKED ISSUE #13226: Tracking Issue: fetch_nand
Tracking issue for `fetch_nand` on integer atomics (it's stable for `bool`).

On android, it appears that these functions give the wrong answer. See https://github.com/mozilla/rust/pull/12964#issuecomment-39075085 for some analysis, and the relevant logs are:

``` rust
    #[test]
    fn uint_nand() {
        let x = AtomicUint::new(0xf731);
        assert_eq!(x.fetch_nand(0x137f, SeqCst), 0xf731);
        assert_eq!(x.load(SeqCst), !(0xf731 & 0x137f));
    }

    #[test]
    fn int_nand() {
        let x = AtomicInt::new(0xf731);
        assert_eq!(x.fetch_nand(0x137f, SeqCst), 0xf731);
        assert_eq!(x.load(SeqCst), !(0xf731 & 0x137f));
    }
```

```
---- sync::atomics::test::int_nand stdout ----
    task 'sync::atomics::test::int_nand' failed at 'assertion failed: `(left == right) && (right == left)` (left: `78`, right: `-4914`)', /home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sync/atomics.rs:1005

---- sync::atomics::test::uint_nand stdout ----
    task 'sync::atomics::test::uint_nand' failed at 'assertion failed: `(left == right) && (right == left)` (left: `78`, right: `4294962382`)', /home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sync/atomics.rs:977  
```

### PR DESCRIPTION
**Pull request by llogiq**
This closes #13226 and makes `Atomic*.fetch_nand` stable.

### CODE REVIEW

File: src/libcore/sync/atomic.rs [hunk 1]
```diff
@@ -1555,7 +1554,7 @@ atomic_int! {
     unstable(feature = "integer_atomics", issue = "32976"),
     unstable(feature = "integer_atomics", issue = "32976"),
     unstable(feature = "integer_atomics", issue = "32976"),
-    unstable(feature = "atomic_nand", issue = "13226"),
+    stable(feature = "atomic_nand", since = "1.27.0"),
```
Comment (kennytm) [inline src/libcore/sync/atomic.rs]: I think for `AtomicU8` etc the method should remain unstable under the feature `integer_atomics`.

Comment (llogiq) [reply src/libcore/sync/atomic.rs]: Thanks, fixed.

**Comment by kennytm** [comment]
@bors r+

cc @rust-lang/libs. (FCP of this feature [has already been completed](https://github.com/rust-lang/rust/issues/13226#issuecomment-377013311)).
