### PR TITLE
rustdoc: linking to a local proc macro no longer warns

### LINKED ISSUE #91274: rustdoc: `broken_intra_doc_links` is incorrectly reported when linking to a proc macro
Rustdoc only emits a documentation page for `my_macro` as a macro; there's no function page for it.

Note that the link indeed fails to resolve.

### Code

```rust
//! Link to [`my_macro`].

#![crate_type = "proc-macro"]

extern crate proc_macro;

#[proc_macro]
pub fn my_macro(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    input
}
```

### Output

```
warning: `my_macro` is both a function and a macro
 --> foo.rs:1:15
  |
1 | //! Link to [`my_macro`].
  |               ^^^^^^^^ ambiguous link
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the function, add parentheses
  |
1 | //! Link to [`my_macro()`].
  |                       ++
help: to link to the macro, add an exclamation mark
  |
1 | //! Link to [`my_macro!`].
  |                       +

warning: 1 warning emitted
```

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes https://github.com/rust-lang/rust/issues/91274

tried to keep the fix general in case we ever have any other kind of item that occupies
multiple namespaces simultaniously.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Not sure it's a good idea to generalize it. We should only do it for items that can be in multiple namepaces at once (I can only think of macros for this case).

**Comment by lolbinarycat** [comment]
@GuillaumeGomez why? the fact that an item is in multiple namespaces is already a pretty good indication that it is able to appear in multiple namespaces.

i'm not sure why i would want write code that asks "is this item, which appears in multiple namespaces, able to appear in multiple namespaces?"

technically tuple structs also appear in multiple namespaces (their constructor is a function), but i'm not sure if rustdoc sees that currently.

**Comment by GuillaumeGomez** [comment]
It's mostly for performance reasons. We don't want to check items that are never part of multiple namespaces.

**Comment by lolbinarycat** [comment]
Well, the code I added isn't run at all on the happy path, only in cases where the lint fires today, but I'll make it so the check is only enabled in proc-macro crates, since that just requires reading a field of TyCtx, and will eliminate the check in even more cases, since linking to a non-local proc macro already works fine (they're only functions in their defining crate).

**Comment by lolbinarycat** [comment]
@GuillaumeGomez I thought of an edge case that my old solution wasn't handling, so I ended up adding a ui test and rewriting the whole thing.

Basically, instead of not emitting the error if there is proc-macro duplication, we instead deduplicate and then continue with the normal logic.  this allows us to still provide clean and accurate error messages in the rare case where there is duplication, but there is also actual ambiguity (which is the situation the ui test creates).

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -2232,15 +2232,47 @@ fn ambiguity_error(
     emit_error: bool,
 ) -> bool {
     let mut descrs = FxHashSet::default();
-    let kinds = candidates
+    // proc macros can exist in multiple namespaces at once,
+    // so we need to compare DefIds to remove
+    // the candidite in the fn namespace
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2237]:
```suggestion
    // proc macro can exist in multiple namespaces at once, so we need to compare `DefIds`
    //  to remove the candidate in the fn namespace.
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -2232,15 +2232,47 @@ fn ambiguity_error(
...
+    // we have to do it in two passes,
+    // completing the full traversal to find
+    // the possible duplicate in the macro namespace,
+    // then another full traversal to eliminate the
+    // candidite in the fn namespace.
+    // thus, we have to do an iteration after
+    // collection is finished.
+    //
+    // as an optimization, we only deduplicate if we're in a proc-macro crate,
+    // and only if we already found something that looks like a proc macro.
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2261]:
```suggestion
    // In order to properly dedup proc macros, we have to do it in two passes:
    // 1. Completing the full traversal to find the possible duplicate in the macro namespace,
    // 2. Another full traversal to eliminate the candidate in the fn namespace.
    //
    // Thus, we have to do an iteration after collection is finished.
    //
    // As an optimization, we only deduplicate if we're in a proc-macro crate,
    // and only if we already found something that looks like a proc macro.
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -2232,15 +2232,47 @@ fn ambiguity_error(
...
+    if is_proc_macro_crate && let Some(macro_id) = possible_proc_macro_id {
+        kinds.retain(|res| {
+            if let Res::Def(DefKind::Fn, fn_id) = res
+                && macro_id == *fn_id
+            {
+                false
+            } else {
+                true
+            }
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2270]: I think this could work:

```suggestion
            !matches!(res, Res::Def(DefKind::Fn, fn_id) if macro_id == *fn_id)
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -2232,15 +2232,47 @@ fn ambiguity_error(
...
-        .map(
-            |(res, def_id)| {
-                if let Some(def_id) = def_id { Res::from_def_id(cx.tcx, *def_id) } else { *res }
-            },
-        )
-        .filter(|res| descrs.insert(res.descr()))
+        .map(|(res, def_id)| {
+            let r =
+                if let Some(def_id) = def_id { Res::from_def_id(cx.tcx, *def_id) } else { *res };
+            if is_proc_macro_crate && let Res::Def(DefKind::Macro(_), id) = r {
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2245]: To prevent having this `if` called on each candidate, I tend to prefer creating two functions: one doing nothing and the other having the `let Res::Def` condition. Then based on `is_proc_macro_crate` value, you use one function or the other.

**Comment by GuillaumeGomez** [comment]
Apart from some nits, code looks better now. Making the change earlier is a very good idea. :)

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 4 above)
Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs:2244]: Hmm, that would be really tricky here for two reasons:
1. we're not doing nothing in the non proc macro case, we still have the `Res::from_def_id` logic.  This could be gotten around by adding a second `map` call, but:
2. the closure has side effects, so we would need to use a `&mut dyn FnMut`, and I'm pretty sure a vtable dispatch is going to be slower than an if statement (both would need to be done once per candidate).  The if statement should also hopefully play nice with the branch predictor.

Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:2244]: We can pass the `def_id` and `cx.tcx` as arguments. It can be plain functions, no need for closures.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 5]
```diff
@@ -2232,15 +2232,35 @@ fn ambiguity_error(
...
+    //
+    // Thus, we have to do an iteration after collection is finished.
+    //
+    // As an optimization, we only deduplicate if we're in a proc-macro crate,
+    // and only if we already found something that looks like a proc macro.
+    if is_proc_macro_crate && let Some(macro_id) = possible_proc_macro_id {
+        kinds.retain(|res| !matches!(res, Res::Def(DefKind::Fn, fn_id) if macro_id == *fn_id));
+    }
+
+    kinds.retain(|res| descrs.insert(res.descr()));
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs:2262]: It's a bit strange to modify `kinds` here considering we just need to iterate it. Why not:

```suggestion
    kinds.iter().for_each(|res| descrs.insert(res.descr()));
```

?

Comment (GuillaumeGomez) [reply src/librustdoc/passes/collect_intra_doc_links.rs:2262]: Nah nevermind, it's used below.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by lolbinarycat** [comment]
@GuillaumeGomez squashed!

**Review by GuillaumeGomez — APPROVED** [review]
