### PR TITLE
Suggest name value cfg when only value is used for check-cfg

### LINKED ISSUE #120427: Suggest name value cfg when only value is used for check-cfg
### Code

```Rust
#[cfg(linux)]
fn x() {}

fn main() {}
```

### Current output

```Shell
warning: unexpected `cfg` condition name: `linux`
 --> t.rs:1:7
  |
1 | #[cfg(linux)]
  |       ^^^^^
  |
  = help: expected names are: `debug_assertions`, `doc`, `doctest`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `unix`, `windows`
  = help: to expect this configuration use `--check-cfg=cfg(linux)`
  = note: see <https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
```

### Desired output

```Shell
= help: try `cfg(target_os = "linux")`
```

### Rationale and extra context

The user wanted something with "linux", and there is a name-value cfg that has the value "linux", so they probably wanted that.

### Other cases

```Rust
many other possible name-value cfgs...
```

### Rust Version

```Shell
rustc 1.77.0-nightly (5bd5d214e 2024-01-25)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #120427
r? @Nilstrieb

### CODE REVIEW

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 1]
```diff
@@ -187,6 +187,14 @@ pub(super) fn builtin(
         BuiltinLintDiagnostics::UnexpectedCfgName((name, name_span), value) => {
             let possibilities: Vec<Symbol> =
                 sess.parse_sess.check_config.expecteds.keys().copied().collect();
+
+            #[allow(rustc::potential_query_instability)]
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:191]: I don't think this instability can be dismissed. It's possible that two or more different cfgs have the same value that we are searching for, in which case we should either suggest both or none.

File: tests/ui/check-cfg/cfg-value-for-cfg-name.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+// #120427
+// This test checks that when a single cfg has a value for user's specified name
+// suggest to use `#[cfg(target_os = "linux")]` instead of `#[cfg(linux)]`
+//
+// check-pass
+// compile-flags: -Z unstable-options
+// compile-flags: --check-cfg=cfg(feature,values())
```
Comment (Urgau) [inline tests/ui/check-cfg/cfg-value-for-cfg-name.rs:7]: No need to specify the `feature` cfg; it's irrelevant to the test since we are only interested well known names and values.
```suggestion
// compile-flags: --check-cfg=cfg()
```

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 3]
```diff
@@ -187,6 +187,14 @@ pub(super) fn builtin(
...
+            let single_possibility =
+                sess.parse_sess.check_config.expecteds.iter().find_map(|(k, v)| match v {
+                    ExpectedValues::Some(v) if v.contains(&Some(name)) => Some(k),
+                    _ => None,
+                });
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:196]: We should collect all the possibilities and then sort.
```suggestion
            let mut names_possibilities: Vec<_> =
                sess.parse_sess.check_config.expecteds.iter().filter_map(|(k, v)| match v {
                    ExpectedValues::Some(v) if v.contains(&Some(name)) => Some(k),
                    _ => None,
                }).collect();
            names_possibility.sort();
```

File: tests/ui/check-cfg/cfg-value-for-cfg-name.rs
Comment (Urgau) [inline tests/ui/check-cfg/cfg-value-for-cfg-name.rs:1]: Can you also add a test with two cfg with the same value, something like this: `cfg(foo,values("my_value"))`, `cfg(bar,values("my_value"))` and test `#[cfg(my_value)]`.

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 4]
```diff
@@ -261,6 +269,8 @@ pub(super) fn builtin(
                 }
 
                 is_feature_cfg |= best_match == sym::feature;
+            } else if let Some(cfg_name) = single_possibility {
+                db.help(format!("try `#[cfg({} = \"{}\")]`", cfg_name, name));
             } else if !possibilities.is_empty() {
                 let mut possibilities =
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:275]: I'm not sure about the placement here. I think we should still suggest the possibilities. It's possible that the user simply actually forgot to put a value.

Maybe something like this?
```suggestion
            } else {
                if !names_possibilities.is_empty() {
                    db.help(format!("try `#[cfg({} = \"{}\")]`", cfg_name, name));
                }
                if !possibilities.is_empty() {
                    let mut possibilities =
```

File: tests/ui/check-cfg/cfg-value-for-cfg-name.stderr [hunk 5]
```diff
@@ -0,0 +1,13 @@
+warning: unexpected `cfg` condition name: `linux`
+  --> $DIR/cfg-value-for-cfg-name.rs:9:7
+   |
+LL | #[cfg(linux)]
+   |       ^^^^^
+   |
+   = help: try `#[cfg(target_os = "linux")]`
```
Comment (Urgau) [inline tests/ui/check-cfg/cfg-value-for-cfg-name.stderr:7]: We should avoid any imperative and just be more explicit. What about?
```suggestion
   = help: found config with similar value: `#[cfg(target_os = "linux")]`
```

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 6]
```diff
@@ -261,6 +269,8 @@ pub(super) fn builtin(
                 }
 
                 is_feature_cfg |= best_match == sym::feature;
+            } else if let Some(cfg_name) = single_possibility {
+                db.help(format!("try `#[cfg({} = \"{}\")]`", cfg_name, name));
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:273]: This should be an applicable suggestion. Look above for examples, but maybe something like this.
```suggestion
                db.span_suggestion(
                    name_span.to(value_span),
                    "found config with similar value",
                    format!("{cfg_name} = \"{name}\""),
                    Applicability::MaybeIncorrect,
                );
```

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 7]
```diff
@@ -187,6 +187,14 @@ pub(super) fn builtin(
         BuiltinLintDiagnostics::UnexpectedCfgName((name, name_span), value) => {
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:187]: Be aware that `value` here can be `Some(..)`, your logic should probably not trigger if it `Some(...)`.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs]: I think it will be too noisy, `possibilities` is a very long list.

File: tests/ui/check-cfg/cfg-value-for-cfg-name.rs
Comment (chenyukang) [reply tests/ui/check-cfg/cfg-value-for-cfg-name.rs:1]: Added it, thanks!

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs:191]: ah, we still need to keep `#[allow(rustc::potential_query_instability)]` to remove the warning because we use `iter()`...

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 4 above)
Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics.rs]: The length of the list is irrelevant. What is important is that we give relevant information to the user and we cannot be 100% sure that the user wanted the the `cfg_name` as a value, so we should still display the list of possibilities.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 1 above)
Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics.rs:191]: This is an unfortunate limitation of the lint, it doesn't detect the following `sort()` call. Can you add a comment explaining that this is fine since we sort the list just below.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 7 above)
Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics.rs:187]: @chenyukang To be more precise `UnexpectedCfgName` can and is fired for things like `#[cfg(target_osss = "linux")]`. So when `value.is_some()` we should not try to suggest using the name as a value since a value is already provided.

Your logic should become something like this:
```rust
    let names_possibilities = if value.is_none() {
        ...
    } else {
        None
    };
```

Please also add a test for this, `#[cfg(linux = linux)]` or something else.

Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs:187]: ah, fixed it, thanks!

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs]: I'm curious why `keys()` and `values()` don't have `potential_query_instability`, and `into_keys()`, `into_values()` have that property, according to the document, they are all in `arbitrary order`.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs]: updated it.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 1 above)
Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics.rs]: It's missing the custom rustc attribute `#[rustc_lint_query_instability]` like in the `into_keys` function: https://github.com/rust-lang/rust/blob/635124704849eeead4e3a7bb6e663c5351571d93/library/std/src/collections/hash/map.rs#L484-L486

This could added in another PR.

Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs]: yeah, I know it's missing `#[rustc_lint_query_instability]`, I was wondering if there is any special reason here, but they are actually all iter in the inner.

I will create another pr later.

File: compiler/rustc_lint/src/context/diagnostics.rs [hunk 8]
```diff
@@ -261,17 +278,30 @@ pub(super) fn builtin(
...
-            } else if !possibilities.is_empty() {
-                let mut possibilities =
-                    possibilities.iter().map(Symbol::as_str).collect::<Vec<_>>();
-                possibilities.sort();
-                let possibilities = possibilities.join("`, `");
+            } else {
+                if !names_possibilities.is_empty() {
+                    names_possibilities.sort();
+                    for cfg_name in names_possibilities.iter() {
+                        db.span_suggestion(
```
Comment (Urgau) [inline compiler/rustc_lint/src/context/diagnostics.rs:285]: We should limit the amount of spanned suggestion since I can think of real cases where the number could be huge (an example could be in the Rust-for-Linux project where someone writes `y` as cfg name, there could be hundreds, maybe thousand of valid suggestion: `CONFIG_NVME = "y"`, `CONFIG_SAS = "y"`, ...).

I would suggest making the limit at 3.
```suggestion
                if !names_possibilities.is_empty() && names_possibilities.len() <= 3 {
                    names_possibilities.sort();
                    for cfg_name in names_possibilities.iter() {
                        db.span_suggestion(
```

**Review by Urgau — COMMENTED** [review]
This looks almost perfect :)

Just one last thing to improve.

File: compiler/rustc_lint/src/context/diagnostics.rs (hunk 8 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/context/diagnostics.rs:285]: good idea.

**Review by Noratrieb — COMMENTED** [review]
Thanks, and thanks @Urgau for the review!
One last thing: Could you add a test for the >3 case?
r=Urgau,Nilstrieb then
