### PR TITLE
Normalize source when loading external foreign source into SourceMap

### LINKED ISSUE #70874: `cargo +nightly doc` panics for crates depending on gfx-backend-empty
If I create a new crate with
```bash
cargo new --lib rustdocissue
```

Then add a dependency on gfx-backend-empty version 0.5:
```toml
[dependencies]
gfx-backend-empty = "0.5"
```

Then run `cargo doc` on stable:
```bash
cargo +stable doc --lib --no-deps
```

`cargo doc` succeeds with warnings. I'm not sure if the warnings are relevant, but the warnings in `cargo +stable doc` are for some empty blocks in examples that haven't been populated, such as:
```
/// ```no_run
///
/// ```
```

Now if I run the same command on nightly (`nightly-2020-04-06`):
```bash
cargo +nightly doc --lib --no-deps
```

`cargo doc` panics with the following error:

```
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:411:31
```

The panic originates in https://github.com/rust-lang/rust/blob/1ccb0b4a020cac07a9772d0da722869096a46cef/src/librustdoc/passes/mod.rs#L411

Besides `stable` and `nightly`, I tried the `nightly-2020-03-19` toolchain which succeeds with warnings (like `stable`).

I also created a repo which reproduces the issue at https://github.com/grovesNL/rustdocissue if it's convenient to clone that instead of following the steps above.

### PR DESCRIPTION
**Pull request by arlosi**
The compiler normalizes source when reading files initially (removes BOMs, etc), but not when loading external sources.

This leads to the external source matching according to the `src_hash`, but differing internally because it was not normalized.

Fixes #70874.

### CODE REVIEW

File: src/librustc_span/lib.rs [hunk 1]
```diff
@@ -1185,7 +1185,10 @@ impl SourceFile {
             *self.external_src.borrow(),
             ExternalSource::Foreign { kind: ExternalSourceKind::AbsentOk, .. }
         ) {
-            let src = get_src();
+            let src = get_src().map(|mut src| {
+                normalize_src(&mut src, BytePos::from_usize(0));
+                src
+            });
```
Comment (eddyb) [inline src/librustc_span/lib.rs:1191]: Can you move this inside `if self.src_hash.matches(&src) {`? IIRC `src_hash` is computed pre-normalization, so we should also check it here in the same way.

**Comment by eddyb** [comment]
cc @GuillaumeGomez It might be good to add a test, but I'm not sure it's possible right now.
Maybe a `run-make` test?

File: src/librustc_span/lib.rs (hunk 1 above)
Comment (arlosi) [reply src/librustc_span/lib.rs:1191]: Good catch, it's pretty subtle. We really do need a test for this.

Comment (eddyb) [reply src/librustc_span/lib.rs:1191]: There are some tests that print snippets from other crates, I think you might be able to do a search like `rg auxiliary/ src/test/**.stderr` to find some examples.

You can then combine that with an unnormalized file, maybe we have some normalization tests?

Comment (eddyb) [reply src/librustc_span/lib.rs:1191]: That is, I think we can use an error message to print a snippet and trigger this through `rustc` instead of `rustdoc`.

Comment (arlosi) [reply src/librustc_span/lib.rs]: Oops, just saw your suggestion about how to do the test. I added one as a SourceMap test. Let me know if you'd prefer a integration-style test like you suggested, or if this is sufficient.

Comment (eddyb) [reply src/librustc_span/lib.rs]: `run-make` tests are a PITA, and your test is pretty clear, so no worries.
