### PR TITLE
Fix `#[expect(dead_code)]` liveness propagation

### LINKED ISSUE #152370: `#[expect(unused)]` false-positive `unfulfilled_lint_expectations` warning on implemented but unused traits
### Code

```Rust
#[expect(unused)]
trait UnusedTrait {}

struct UsedStruct(u32);

impl UnusedTrait for UsedStruct {}

fn main() {
    let x = UsedStruct(12);
    println!("Hello World! {}", x.0);
}
```

### Current output

```Shell
warning: this lint expectation is unfulfilled
 --> src/main.rs:1:10
  |
1 | #[expect(unused)]
  |          ^^^^^^
  |
  = note: `#[warn(unfulfilled_lint_expectations)]` on by default

warning: `playground` (bin "playground") generated 1 warning
```

### Desired output

```Shell
Compilation with no warnings
```

### Rationale and extra context

The code above throws an `unfulfilled_lint_expectations` lint even though, if it were removed, the compiler would emit a `dead_code` lint for the trait.
This only happens when the trait is implemented for some type but ultimately still ends up unused. If there are no implementations at all then `expect` suppresses the lint correctly without a warning.

### Other cases

```Rust
// If `#[expect(unused)]` is commented out:
warning: trait `UnusedTrait` is never used
 --> src/main.rs:2:7
  |
2 | trait UnusedTrait {}
  |       ^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

warning: `playground` (bin "playground") generated 1 warning
```

### Rust Version

```Shell
rustc 1.94.0-beta.2 (23a44d3c7 2026-01-25)
binary: rustc
commit-hash: 23a44d3c70448c08dc6a2fc13c1afceab49f2bb9
commit-date: 2026-01-25
host: x86_64-pc-windows-msvc
release: 1.94.0-beta.2
LLVM version: 21.1.8
```

### Anything else?

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=1d6bd45080b177104331d8968d8812b8

### PR DESCRIPTION
**Pull request by mu001999**
Fixes https://github.com/rust-lang/rust/issues/154324
Fixes https://github.com/rust-lang/rust/issues/152370 (cc @eggyal)

Previously, when traversing from a `ComesFromAllowExpect::Yes` item (i.e., with `#[allow(dead_code)]` or `#[expect(dead_code)]`), other `ComesFromAllowExpect::Yes` items reached during propagation would be updated to `ComesFromAllowExpect::No` and inserted into `live_symbols`. That caused `dead_code` lint couldn't be emitted correctly.

After this PR, `ComesFromAllowExpect::Yes` items no longer incorrectly update other `ComesFromAllowExpect::Yes` items during propagation or mark them live by mistake, then `dead_code` lint could behave as expected.

### CODE REVIEW

File: compiler/rustc_passes/src/dead.rs [hunk 1]
```diff
@@ -75,11 +75,22 @@ enum ComesFromAllowExpect {
     No,
 }
 
+#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
```
Comment (nikomatsakis) [inline compiler/rustc_passes/src/dead.rs:106]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154377/6d8bc65fc851433b0c17e5530ca68ff7eb41815c..5e34775a01a42ae36d0f400089733d42fecec8cc)*

Nit: I found this struct hard to understand, I think a doc comment that explains the role of these fields in terms of examples would be very helpful to future code readers :)

Comment (mu001999) [reply compiler/rustc_passes/src/dead.rs:106]: Added :)

**Comment by mu001999** [comment]
r? reroll

**Review by TaKO8Ki — APPROVED** [review]
Sorry. I overlooked this pr.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154377/4c4205163abcbd08948b3efab796c543ba1ea687..faa7966a5bafb7e694e56126dd39ed8faf13d09d)*

**Comment by TaKO8Ki** [comment]
r? TaKO8Ki @bors r+ rollup

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 40d0e95c2742827aa8738e0c6c6a43d7fddaaedd

**Comment by Mark-Simulacrum** [comment]
Looks like this caused some regressions, including outside incremental scenarios. I think since it's a correctness fix it's probably acceptable, marking as triaged. I suspect most of the regressions are predominantly just in instruction count based on the changes -- since we're moving slightly larger structs around that'll take a few extra instructions -- but that shouldn't take meaningfully more wall time, which aligns with minimal cycle count changes.
