### PR TITLE
Take type defaults into account in suggestions to reorder generic parameters

### LINKED ISSUE #80512: Suggestion to reorder generic parameters ignores type defaults
```rust
struct S<T = (), 'a>(&'a T);
```
results in:
```
error: lifetime parameters must be declared prior to type parameters
 --> src/lib.rs:1:18
  |
1 | struct S<T = (), 'a>(&'a T);
  |         ---------^^- help: reorder the parameters: lifetimes, then types, then consts: `<'a, T>`
```
when it should be:
```
help: reorder the parameters: lifetimes, then types, then consts: `<'a, T = ()>`
```
This should be easy to fix: just replace `ident` in the following line with an appropriate format string.
https://github.com/rust-lang/rust/blob/d107a87d34c1fc3521aaab7a2576ffbaf59cb2cb/compiler/rustc_ast_passes/src/ast_validation.rs#L1157

### PR DESCRIPTION
**Pull request by max-heller**
Fixes #80512

### CODE REVIEW

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 1]
```diff
@@ -1152,7 +1164,7 @@ impl<'a> Visitor<'a> for AstValidator<'a> {
             self.err_handler(),
             generics.params.iter().map(|param| {
                 let ident = Some(param.ident.to_string());
-                let (kind, ident) = match &param.kind {
+                let (ord_kind, ident) = match &param.kind {
```
Comment (varkor) [inline compiler/rustc_ast_passes/src/ast_validation.rs:1167]: Since we pass the `GenericParamKind` now, we can compute `ord_kind` within `validate_generic_param_order`, rather than doing it here.

File: src/test/ui/const-generics/defaults/complex-unord-param.min.stderr [hunk 2]
```diff
@@ -2,7 +2,7 @@ error: type parameters must be declared prior to const parameters
   --> $DIR/complex-unord-param.rs:8:41
    |
 LL | struct NestedArrays<'a, const N: usize, A: 'a, const M: usize, T:'a =u32> {
-   |                    ---------------------^----------------------^--------- help: reorder the parameters: lifetimes, then types, then consts: `<'a, A: 'a, T: 'a, const N: usize, const M: usize>`
+   |                    ---------------------^----------------------^--------- help: reorder the parameters: lifetimes, then types, then consts: `<'a, A: 'a, T: 'a = u32, const N: usize, const M: usize>`
```
Comment (varkor) [inline src/test/ui/const-generics/defaults/complex-unord-param.min.stderr:5]: It's a bit unfortunate that this suggestion is incorrect (at the moment type parameter defaults and const generics cannot be used together), but making this change will result in the correct diagnostic (altering the user of this fact), so I think it's okay for now.

**Review by varkor — COMMENTED** [review]
Thanks, this looks great! Could you squash your commits together? I think it's good to go after addressing the one comment.

File: compiler/rustc_ast_passes/src/ast_validation.rs (hunk 1 above)
Comment (max-heller) [reply compiler/rustc_ast_passes/src/ast_validation.rs]: I moved all of the logic done here into `validate_generic_param_order`, was there a reason we passed an iterator of a bunch of pieces of the params instead of an iterator of the `GenericParam`s themselves?

**Comment by max-heller** [comment]
Added a note about/placeholder for handling const generic param defaults if/when they are allowed. If the new commits look ok, I'll squash

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 3]
```diff
@@ -764,9 +767,16 @@ fn validate_generic_param_order<'a>(
...
-                ordered_params += &pprust::ty_to_string(default);
+            match kind {
+                GenericParamKind::Type { default: Some(default) } => {
+                    ordered_params += " = ";
+                    ordered_params += &pprust::ty_to_string(default);
+                }
+                GenericParamKind::Type { default: None } => (),
+                GenericParamKind::Lifetime => (),
+                // If/when const generic parameters are allowed to have defaults,
+                // add them to the output as is done for type defaults (above)
```
Comment (varkor) [inline compiler/rustc_ast_passes/src/ast_validation.rs:778]:
```suggestion
                // FIXME(const_generics:defaults)
```
We've been using this `FIXME` to easily search for places where changes are necessary to support const generic defaults.

Comment (varkor) [inline compiler/rustc_ast_passes/src/ast_validation.rs:778]:
```suggestion
                // FIXME(const_generics:defaults)
```
We've been using this `FIXME` to easily search for places where changes are necessary to support const generic defaults.

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 4]
```diff
@@ -720,22 +720,25 @@ impl<'a> AstValidator<'a> {
...
-    generics: impl Iterator<
-        Item = (
-            &'a GenericParamKind,
-            ParamKindOrd,
-            Option<&'a [GenericBound]>,
-            Span,
-            Option<String>,
-        ),
-    >,
+    generics: impl Iterator<Item = &'a GenericParam>,
```
Comment (varkor) [inline compiler/rustc_ast_passes/src/ast_validation.rs:723]: We could just pass a slice of `GenericParam`s instead, which would be slightly simpler.

**Review by varkor — COMMENTED** [review]
I don't remember why we passed an iterator like that instead of the generic parameters themselves. I imagine it was because the method originally looked quite different, and refactorings since then have made it make less sense. This looks good to me after the couple more comments.

**Comment by varkor** [comment]
Thanks @max-heller! If you squash your commits, I'll approve once CI passes.

**Comment by max-heller** [comment]
Done, thanks for the feedback @varkor!
