### PR TITLE
codegen: Copy to an alloca when the argument is neither by-val nor by-move for indirect pointer.

### LINKED ISSUE #155241: release-mode heap corruption with non-generic `FnOnce(Vec<usize>)`
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/155241)*

I tried this code:

```rust
#![cfg_attr(not(test), no_std)]

extern crate alloc;

use alloc::vec::Vec;

fn with(f: impl FnOnce(Vec<usize>)) {
    f(Vec::new())
}

#[test]
fn repro_len_ne_unreachable() {
    with(|mut v| v.resize(2, 1));
    with(|v| {
        if v.len() != 0 {
            unreachable!();
        }
    });
}
```

I expected to see this happen: the test should pass, because each `with` call receives a fresh empty `Vec<usize>`, so the second closure should observe `v.len() == 0` and never enter the `unreachable!()` branch.

Instead, this happened: in `--profile release`, the test process aborts due to allocator corruption.

Observed results:

```text
Windows x86_64-pc-windows-msvc:
    process aborts with 0xc0000374 (STATUS_HEAP_CORRUPTION)

Linux x86_64-unknown-linux-gnu (Docker rust:latest image):
    free(): double free detected in tcache 2
    process aborts with SIGABRT
```

Two nearby controls do not reproduce:

```rust
fn with_value<T>(f: impl FnOnce(Vec<T>)) {
    f(Vec::new())
}

#[test]
fn control_generic_helper() {
    with_value(|mut v: Vec<usize>| v.resize(2, 1));
    with_value(|v: Vec<usize>| {
        if v.len() != 0 {
            unreachable!();
        }
    });
}

#[test]
fn repro_len_ne_unreachable_unchecked() {
    with(|mut v| v.resize(2, 1));
    with(|v| {
        if v.len() != 0 {
            unsafe {
                core::hint::unreachable_unchecked();
            }
        }
    });
}
```

Commands used:

```text
cargo +nightly miri test repro_len_ne_unreachable -- --exact --nocapture
$env:CARGO_TARGET_DIR='target/report-repro'; cargo test --profile release repro_len_ne_unreachable -- --exact --nocapture
$env:CARGO_TARGET_DIR='target/report-control-generic'; cargo test --profile release control_generic_helper -- --exact --nocapture
$env:CARGO_TARGET_DIR='target/report-control-unchecked'; cargo test --profile release repro_len_ne_unreachable_unchecked -- --exact --nocapture
docker run --rm -v ${PWD}:/work -w /work rust:latest cargo test --profile release repro_len_ne_unreachable -- --exact --nocapture
```

Miri did not report UB on an earlier form of this reproducer.

Version history:

```text
stable-1.74.1: ok
stable-1.75.0: ok
stable-1.76.0: ok
stable-1.77.0: first wrong result, panics at `unreachable!()`
stable-1.85.0: still panics at `unreachable!()`
stable-1.90.0: still panics at `unreachable!()`
stable-1.91.0: first stable with STATUS_HEAP_CORRUPTION
stable-1.92.0: STATUS_HEAP_CORRUPTION
stable-1.93.0: STATUS_HEAP_CORRUPTION
stable-1.94.0: STATUS_HEAP_CORRUPTION
nightly-2026-04-12: STATUS_HEAP_CORRUPTION
```

Nightly boundaries I checked:

```text
last good nightly: nightly-2024-01-16, rustc 1.77.0-nightly (714b29a17 2024-01-15)
first bad nightly: nightly-2024-01-17, rustc 1.77.0-nightly (098d4fd74 2024-01-16), wrong panic at `unreachable!()`
earliest tested nightly with heap corruption: nightly-2024-01-18, rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)

last tested nightly with wrong panic before the later stable corruption window: nightly-2025-08-12, rustc 1.91.0-nightly (1ebbd87a6 2025-08-11)
first tested nightly with heap corruption in that window: nightly-2025-08-14, rustc 1.91.0-nightly (3672a55b7 2025-08-13)
```

So on stable, the bug first appears as an incorrect panic in 1.77.0 and becomes heap corruption in 1.91.0. On nightly, the first wrong result is between 2024-01-16 and 2024-01-17.

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0 (4a4ef493e 2026-03-02)
binary: rustc
commit-hash: 4a4ef493e3a1488c6e321570238084b38948f6db
commit-date: 2026-03-02
host: x86_64-pc-windows-msvc
release: 1.94.0
LLVM version: 21.1.8
```

Nightly also reproduces:

```text
rustc 1.97.0-nightly (14196dbfa 2026-04-12)
binary: rustc
commit-hash: 14196dbfa3eb7c30195251eac092b1b86c8a2d84
commit-date: 2026-04-12
host: x86_64-pc-windows-msvc
release: 1.97.0-nightly
LLVM version: 22.1.2
```

Linux container reproduction:

```text
running 1 test
free(): double free detected in tcache 2
error: test failed, to rerun pass `--lib`

Caused by:
    process didn't exit successfully: `/work/target/release/deps/repro_test-9864353ff121d9c3 repro_len_ne_unreachable --exact --nocapture` (signal: 6, SIGABRT: process abort signal)
```

Additional stable versions checked:

```text
rustc 1.74.1 (a28077b28 2023-12-04)
rustc 1.75.0 (82e1608df 2023-12-21)
rustc 1.76.0 (07dca489a 2024-02-04)
rustc 1.77.0 (aedd173a2 2024-03-17)
rustc 1.85.0 (4d91de4e4 2025-02-17)
rustc 1.90.0 (1159e78c4 2025-09-14)
rustc 1.91.0 (f8297e351 2025-10-28)
rustc 1.92.0 (ded5c06cf 2025-12-08)
rustc 1.93.0 (254b59607 2026-01-19)
```

<details><summary>Backtrace</summary>
<p>

```
I reran the reproducer with RUST_BACKTRACE=1, but there was still no Rust backtrace.
The process aborts immediately with:

running 1 test
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `C:\Users\akrut\repro_test\target/report-backtrace\release\deps\repro_test-1f8b8a2035f2538a.exe repro_len_ne_unreachable --exact --nocapture` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dianqk**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/155343)*

Fixes https://github.com/rust-lang/rust/issues/155241.

When a value is passed via an indirect pointer, the value needs to be copied to a new alloca. For x86_64-unknown-linux-gnu, `Thing` is the case:

```rust
#[derive(Clone, Copy)]
struct Thing(usize, usize, usize);

pub fn foo() {
    let thing = Thing(0, 0, 0);
    bar(thing);
    assert_eq!(thing.0, 0);
}

#[inline(never)]
#[unsafe(no_mangle)]
pub fn bar(mut thing: Thing) {
    thing.0 = 1;
}
```

Before passing the thing to the bar function, the thing needs to be copied to an alloca that is passed to bar.

```llvm
%0 = alloca [24 x i8], align 8
call void @llvm.memcpy.p0.p0.i64(ptr align 8 %0, ptr align 8 %thing, i64 24, i1 false)
call void @bar(ptr %0)
```

This patch applies the rule to the untupled arguments as well.

```rust
#![feature(fn_traits)]

#[derive(Clone, Copy)]
struct Thing(usize, usize, usize);

#[inline(never)]
#[unsafe(no_mangle)]
pub fn foo() {
    let thing = (Thing(0, 0, 0),);
    (|mut thing: Thing| {
        thing.0 = 1;
    }).call(thing);
    assert_eq!(thing.0.0, 0);
}
```

For this case, this patch changes from

```llvm
; call example::foo::{closure#0}
call void @_RNCNvCs15qdZVLwHPA_7example3foo0B3_(ptr ..., ptr %thing)
```

to

```llvm
%0 = alloca [24 x i8], align 8
call void @llvm.memcpy.p0.p0.i64(ptr align 8 %0, ptr align 8 %thing, i64 24, i1 false)
; call example::foo::{closure#0}
call void @_RNCNvCs15qdZVLwHPA_7example3foo0B3_(ptr ..., ptr %0)
```

However, the same rule cannot be applied to tail calls that would be unsound, because the caller's stack frame is overwritten by the callee's stack frame. Fortunately, https://github.com/rust-lang/rust/pull/151143 has already handled the special case. We must not copy again.

No copy is needed for by-move arguments, because the argument is passed to the called "in-place".

No copy is also needed for by-val arguments, because the attribute implies that a hidden copy of the pointee is made between the caller and the callee.

NOTE: The patch has a trick for tail calls that we pass by-move. We can choose to copy an alloca even for by-move arguments, but tail calls require MUST-by-move.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 1]
```diff
@@ -1293,6 +1283,8 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
             self.codegen_argument(
                 bx,
                 op,
+                // Pass by-move for an explicit tail call, which has been handled above as well.
```
Comment (dianqk) [inline compiler/rustc_codegen_ssa/src/mir/block.rs:1286]: This feels a bit awkward; perhaps the tail call handling can be moved into `codegen_argument` as well.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155343/32e4c0ecbd046aafdde22043b2fb7b205587c5f6..e744a07629be5f74ce2e73be4a397c3cd52586e9)*

File: tests/codegen-llvm/const-vector.rs [hunk 2]
```diff
@@ -74,7 +74,8 @@ pub fn do_call() {
         // CHECK: call void @test_simd(<4 x i32> <i32 2, i32 4, i32 6, i32 8>
         test_simd(const { Simd::<i32, 4>([2, 4, 6, 8]) });
 
-        // CHECK: call void @test_simd_unaligned(%"minisimd::PackedSimd<i32, 3>" %1
```
Comment (dianqk) [inline tests/codegen-llvm/const-vector.rs:77]: A redundant memcpy is skipped here.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155343/32e4c0ecbd046aafdde22043b2fb7b205587c5f6..e744a07629be5f74ce2e73be4a397c3cd52586e9)*

File: compiler/rustc_codegen_ssa/src/mir/block.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:1286]: The issue has nothing to do with tail calls, does it...?

Comment (dianqk) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:1286]: Yes. https://github.com/rust-lang/rust/pull/151143 works well.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:1286]: But this PR is changing something about tail calls...?

Maybe it's just the comment that is confusing me. Why is it okay to always to by-move for tail call arguments? Cc @folkertdev

Comment (dianqk) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:1286]: Because #151143 has done a similar thing, we don't need to copy it again. IIUC, tail call is special; the same arguments on the caller must be passed to the callee. Extra copy is UB.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs]: https://github.com/rust-lang/rust/pull/151143 says something about

> Therefore we store the argument for the callee in the corresponding caller's slot. 

So I guess there is code elsewhere establishing an invariant that the argument here is the equivalent slot and we can pass a pointer to it. The comment should explain that and point at that code.

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 3]
```diff
@@ -1331,6 +1321,7 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
             self.codegen_argument(
                 bx,
                 location,
+                false,
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/block.rs]:
```suggestion
                /* by_move */ false,
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155343/e8e4541ff19649d95afab52fdde2c2eaa6829965..9ec6be78cc8977f10856843ef673b4e468c93693)*

**Comment by RalfJung** [comment]
This makes sense to me at a high level, but I don't know the surrounding code so reviewing the exact details of the conditionals introduced here would take me more time than I can spare right now -- sorry. I hope we can find another reviewer.

maybe
r? @nikic

**Comment by nikic** [comment]
The PR description could use more words...

@bors try @rust-timer queue

**Comment by dianqk** [comment]
> The PR description could use more words...

Done. I also fixed the comment about tail calls.

File: tests/codegen-llvm/indirect-bycopy-bymove-byval.rs [hunk 4]
```diff
@@ -0,0 +1,89 @@
+//! Regression test for issue <https://github.com/rust-lang/rust/issues/155241>.
+//! Arguments passed indirectly via a hidden pointer must be copied to an alloca,
+//! except for by-val or by-move.
+//@ compile-flags: -Cno-prepopulate-passes -Copt-level=3
+//@ only-x86_64-unknown-linux-gnu
```
Comment (nikic) [inline tests/codegen-llvm/indirect-bycopy-bymove-byval.rs:5]: Can this be made a minicore test instead?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155343/93637f398f4d0d40badc6bf1ed3f241499d06f88..ecd35c12bf43b0c8a2ad40310fac4f19b9c71a9a)*

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 5]
```diff
@@ -1240,59 +1241,57 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                // Normally an indirect argument that is allocated in the caller's stack frame
+                // would be passed as a pointer into the callee's stack frame.
+                // For tail calls, that would be unsound, because the caller's
+                // stack frame is overwritten by the callee's stack frame.
+                //
+                // To handle the case, we introduce `tail_call_temporaries` to copy arguments into
+                // temporaries, then copy back to the caller's argument slots.
+                // Finally, we pass the caller's argument slots as arguments.
+                //
+                // To do that, the argument must be MUST-by-move value.
```
Comment (nikic) [inline compiler/rustc_codegen_ssa/src/mir/block.rs:1258]: What does "MUST-by-move" mean, as opposed to just by-move?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155343/93637f398f4d0d40badc6bf1ed3f241499d06f88..ecd35c12bf43b0c8a2ad40310fac4f19b9c71a9a)*

Comment (dianqk) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:1258]: I mean codegen allows copying for by-move, but not for MUST-by-move.
