### PR TITLE
Fix possibly endless loop in ReadDir iterator

### LINKED ISSUE #50619: fs::read_dir iterator loops forever on same entry
#### Bug description

There are certain directories that cause the `fs::read_dir` iterator (`ReadDir`) to loop indefinitely. While I am not sure what the exact properties of these directories are, I know that they do appear in `/proc` in the presence of zombie processes.

Consider the following Rust program ...

``` rust
use std::env;
use std::fs;

fn main() {
    let path = env::args().nth(1).unwrap();

    for entry in fs::read_dir(path).unwrap() {
        println!("{:?}", entry);
    }
}
```

... and a zombie process with process id `$ZOMBIE_PID` (see below how to create a zombie process on purpose). Running the above program with:

``` bash
cargo run -- /proc/$ZOMBIE_PID/net
```

results in an infinite loop, printing:
```
Err(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })
Err(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })
Err(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })
...
```

#### How to create a zombie process to reproduce this?

1. Copy the code from https://stackoverflow.com/a/25228579/704831 into a file called `zombie.c`
2. Compile it `gcc -o zombie zombie.c`
3. Run it: `./zombie`
4. Get the PID of the "defunct"/zombie process: `ps -ef | grep '<defunct>'`

#### Analysis

I did some debugging and I believe I found the cause of this.

When called on `/proc/$ZOMBIE_PID/net`, the `readdir_r`(3) function

``` c
int readdir_r(DIR *dirp, struct dirent *entry, struct dirent **result);
```

returns error code `22` and - *at the same time* - returns `NULL` in `*result`, signalling the end of the directory stream.

If I am reading the code in the standard library correctly, this case can not be handled properly at the moment:

Code from the `next` function of `impl Iterator for ReadDir`:

https://github.com/rust-lang/rust/blob/f25c2283b3f8a7518b2f83a252b50d29d9bfbfda/src/libstd/sys/unix/fs.rs#L252-L262

To handle this properly (without looping forever), one would probably have to check for `entry_ptr.is_null()` in the first (`Some(Err(...))`) case as well. The result (whether or not it returned a `NULL` pointer) would probably have to be stored in some internal state of the iterator. On the forthcoming `next` call, the iterator could then return `None`.

#### Meta

```
> rustc --version
rustc 1.25.0 (84203cac6 2018-03-25)

> uname -s -r -v -m -p -i -o
Linux 4.16.7-1-ARCH #1 SMP PREEMPT Wed May 2 21:12:36 UTC 2018 x86_64 unknown unknown GNU/Linux
```

### PR DESCRIPTION
**Pull request by sharkdp**
Certain directories in `/proc` can cause the `ReadDir` iterator to loop indefinitely. We get an error code (22) when calling libc's `readdir_r` on these directories, but `entry_ptr` is `NULL` at the same time, signalling the end of the directory stream.

This change introduces an internal state to the iterator such that the `Some(Err(..))` value will only be returned once when calling `next`. Subsequent calls will return `None`.

fixes #50619

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Can we add a test for this?

File: src/libstd/sys/unix/fs.rs [hunk 1]
```diff
@@ -51,6 +51,7 @@ pub struct FileAttr {
 pub struct ReadDir {
     dirp: Dir,
     root: Arc<PathBuf>,
+    end_of_stream: bool,
```
Comment (nagisa) [inline src/libstd/sys/unix/fs.rs]: I think it might be better to just wrap `Dir` into an `Option` (and mark the pointer within `Dir` as `NonZero`) as that would both be more semantically accurate, more efficient space wise and more future-proof in terms of preventing mistakes.

**Comment by nagisa** [comment]
Adding a test for this would be fairly difficult, as the original reproducer relies on a fairly specific state of the system that would be pretty hard to emulate in way that wouldn’t spuriously fail all the time.

**Comment by sharkdp** [comment]
I have updated the code to use `Option<Dir>` and `NonNull<libc::DIR>` instead of the additional `bool` flag, as per @nagisa's excellent suggestion.

However, I'm not too happy about my code changes in the `next` function. It is slightly awkward to pattern-match on `dirp: Option<Dir>` while having to mutate `dirp` at the same time. If someone has a better suggestion on how to write this function, I'd be happy to change this again.

@ishitatsuyuki Concerning tests: I would love to write a test for this, but I'm really not sure how to. I also share the same view as @nagisa. Note that there is a way to reproduce the bug in the attached ticket (#50619).

File: src/libstd/sys/unix/fs.rs [hunk 2]
```diff
@@ -251,21 +251,35 @@ impl Iterator for ReadDir {
...
-            loop {
-                if readdir64_r(self.dirp.0, &mut ret.entry, &mut entry_ptr) != 0 {
-                    return Some(Err(Error::last_os_error()))
-                }
-                if entry_ptr.is_null() {
-                    return None
-                }
-                if ret.name_bytes() != b"." && ret.name_bytes() != b".." {
-                    return Some(Ok(ret))
+        if self.dirp.is_none() {
```
Comment (sfackler) [inline src/libstd/sys/unix/fs.rs]: Don't we make this check again just below on 259?

File: src/libstd/sys/unix/fs.rs [hunk 3]
```diff
@@ -49,11 +49,11 @@ pub struct FileAttr {
 }
 
 pub struct ReadDir {
-    dirp: Dir,
+    dirp: Option<Dir>,
```
Comment (sfackler) [inline src/libstd/sys/unix/fs.rs]: Is this change related to the infinite loop issue?

File: src/libstd/sys/unix/fs.rs [hunk 4]
```diff
@@ -251,21 +251,35 @@ impl Iterator for ReadDir {
...
+                    let mut ret = DirEntry {
+                        entry: mem::zeroed(),
+                        root: self.root.clone()
+                    };
+                    let mut entry_ptr = ptr::null_mut();
+                    loop {
+                        if readdir64_r(dirp.as_mut().unwrap().0.as_mut(),
+                                       &mut ret.entry,
+                                       &mut entry_ptr) != 0 {
+                            if entry_ptr.is_null() {
```
Comment (sfackler) [inline src/libstd/sys/unix/fs.rs]: This is the actual change being made, right?

File: src/libstd/sys/unix/fs.rs (hunk 2 above)
Comment (sharkdp) [reply src/libstd/sys/unix/fs.rs]: Oh, absolutely - I will remove this `if` clause.

File: src/libstd/sys/unix/fs.rs (hunk 3 above)
Comment (sharkdp) [reply src/libstd/sys/unix/fs.rs]: Yes. `Option` is used to store whether we are at the end of the directory stream or not.

File: src/libstd/sys/unix/fs.rs (hunk 4 above)
Comment (sharkdp) [reply src/libstd/sys/unix/fs.rs]: Yes. If `readdir64_r` returns a non-empty exit code *and* signals the end of the directory stream by writing `nullptr` to `entry_ptr`, we still want to return the OS error in this iteration but `None` on the next iteration.

**Comment by pietroalbini** [comment]
Ping from triage @sfackler! The author pushed some new commits.

File: src/libstd/sys/unix/fs.rs (hunk 4 above)
Comment (sfackler) [reply src/libstd/sys/unix/fs.rs]: I think this change can be made a bit simpler by just using a null pointer instead of the whole option business. Then the diff just becomes a `if self.dirp.0.is_null() { return None; }` at the top of Next, and an `if entry_ptr.is_null() { self.dirp.0 = ptr::null_mut(); }` in the error case here.

**Comment by nagisa** [comment]
Option ensures that other areas of code properly handle the null case as
well. Both for this PR and the future changes.

**Comment by sharkdp** [comment]
> Option ensures that other areas of code properly handle the null case as well.

Exactly. Also, I'm personally fine with the solution suggested by @sfackler but I'm not sure if we should actively use `nullptr` to modify control flow ("actively" meaning that we set `dirp` to `nullptr` in cases where the `C` code does not).

Let me know whether I should go forward with @sfackler's suggestion or resolve the merge conflicts in the current version.

**Comment by nagisa** [comment]
Just rebase it, I’ll r+ it.

**Comment by sharkdp** [comment]
> Just rebase it

I tried and failed. The whole `ReadDir` (or now: `InnerReadDir`) struct has been moved inside an `Arc` (in this PR: #51050), which means that I can not mutate parts of it(?).

To be honest, I don't really understand why it has been moved into the `Arc` (Note that the underlying `DIR` pointer will still be mutated via `readdir64_r`).

As it stands, I either need some help to make this work again (my attempt at resolving the conflicts can be found here: https://gist.github.com/sharkdp/fd60040daf25630f67f095d0fa616b82 - it currently does not pass the borrow-checker) or I move forward with @sfackler's suggestion, which should still work.

**Comment by nagisa** [comment]
Well, I assume that `Dir` is now within an `Arc` specifically so that it is freed only when both `ReadDir` and all `DirEntry`ies are out of scope (as calling `metadata` on `DirEntry` requires a valid open `Dir`).

The problem is, of course, that now we have two distinct, and colliding requirements. First, we must somehow maintain information about when `Dir` has completed reading (preferably by setting the `Dir` field of `ReadDir` to `None`), but must as well keep `Dir` around until all of the `DirEntry`ies are dropped (so that `DirEntry` is able to call the `metadata` method). One option would be a 

```
struct DirEntry { 
    dir: Option<Arc<Dir>>,
    root: Arc<PathBuf>,
}
```

but that seems to increasingly stray away from what should be a 0-cost abstraction.

Quick and dirty alternative is to just add a boolean flag to the struct now, but I’d prefer not to land code like that if there’s any way to avoid it.

**Comment by TimNN** [comment]
Friendly ping from triage, @sharkdp, it looks like this PR needs some additional design / implementation work. Do you think you'll be able to look into that?

**Comment by sharkdp** [comment]
@TimNN I am happy to work on this, but I will probably need some help, as mentioned above.

I have now pushed a new commit which resolves the merge conflicts and handles the problem in the same way as in my first commit - with an additional flag. This is a rather minimal change to fix this bug, but I agree with @nagisa that it is probably not optimal. However, I don't see how the other two discussed solutions (using `Option` or `nullptr` to store the state) can still work with the new changes on `master` (where the inner part of `ReadDir` is wrapped in an `Arc`).

**Comment by pietroalbini** [comment]
Ping from triage @sfackler! The author needs a bit of help, could you check in on this?

**Comment by pietroalbini** [comment]
Ping from triage @sfackler! The author needs a bit of help, could you check in on this?

**Comment by sfackler** [comment]
Oops, sorry. This seems good to me!

@bors r+
