### PR TITLE
Feed `ErrorGuaranteed` from late lifetime resolution errors through to bound variable resolution

### LINKED ISSUE #152014: We generally emit an additional error if a trait object lifetime bound defaults to an unresolved lifetime in item signatures
If we fail to deduce a trait object lifetime default in an item signature[^1] we generally emit an error for that. More specifically, we generally do that if `TyCtxt::named_bound_var` returns `None`. For context, `named_bound_var` actually returns `None` iff RBV didn't register a mapping from a given `hir::Lifetime` to a `ResolvedArg`. Now, since RBV doesn't actually map unresolved lifetimes to `ResolvedArg::Error`, we ultimately emit two errors in certain cases (1st: unresolved lifetime, 2nd: indeterminate trait object lifetime bound).

I'm not super familiar with the early resolution of lifetimes. Therefore, I don't know if we map unresolved lifetimes to `LifetimeRes::Error` in `rustc_resolve` or not (I have a hunch we don't (possibly a remnant of the now removed feature *inband lifetimes*?)). In any case, ideally we would map unresolved lifetimes to `ResolvedArg::Error(_)` in RBV which would automatically suppress the "indeterminate trait object lifetime bound" error. 

Between AST lowering, name resolution and HIR ty lowering, we have `LifetimeRes::Error`, `hir::LifetimeKind::Error`, `ResolvedArg::Error(ErrorGuaranteed)` & `Region::Error(ErrorGuaranteed)` but none or only some are actually used for unresolved lifetimes IINM (they're mainly used for other early lifetime issues). Ideally, we'd use these for unresolved lifetimes, too, I guess (for that, ideally `LifetimeRes` and `LifetimeKind::Error` would carry an `ErrorGuaranteed`).

I've used the word "generally" a few times above, that's because in the special case of `&'undefined dyn Trait` (i.e., trait object type passed to a reference type constructor), we manually suppress the follow-up error. However, if we were to implement the scheme I'm describing above that would become unnecessary allowing us to remove this minor hack in HIR ty lowering:

https://github.com/rust-lang/rust/blob/f60a0f1bcc5a2a6dd8eb2d2021da79b40f5fbae9/compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs#L454-L464

#### Example Reproducer

```rs
fn f(_: std::cell::Ref<'undefined, dyn std::fmt::Debug>) {}
```

```
error[E0261]: use of undeclared lifetime name `'undefined`
 --> src/lib.rs:1:24
  |
1 | fn f(_: std::cell::Ref<'undefined, dyn std::fmt::Debug>) {}
  |                        ^^^^^^^^^^ undeclared lifetime
  |
help: consider introducing lifetime `'undefined` here
  |
1 | fn f<'undefined>(_: std::cell::Ref<'undefined, dyn std::fmt::Debug>) {}
  |     ++++++++++++

error[E0228]: the lifetime bound for this object type cannot be deduced from context; please supply an explicit bound
 --> src/lib.rs:1:36
  |
1 | fn f(_: std::cell::Ref<'undefined, dyn std::fmt::Debug>) {}
  |                                    ^^^^^^^^^^^^^^^^^^^
```

[^1]: aka item ctxt aka non-body

### PR DESCRIPTION
**Pull request by eggyal**
If late lifetime resolution fails for whatever reason, forward to RBV the guarantee that an error was emitted - thereby eliminating the need for a "hack" to suppress subsequent/superfluous error diagnostics.

Fixes rust-lang/rust#152014
r? fmease

### CODE REVIEW

File: tests/ui/cast/ice-cast-type-with-error-124848.rs [hunk 1]
```diff
@@ -14,5 +14,4 @@ fn main() {
     let bad_addr = &unpinned as *const Cell<Option<&'a mut MyType<'a>>> as usize;
     //~^ ERROR use of undeclared lifetime name `'a`
     //~| ERROR use of undeclared lifetime name `'a`
-    //~| ERROR casting `&MyType<'_>` as `*const Cell<Option<&mut MyType<'_>>>` is invalid
```
Comment (eggyal) [inline tests/ui/cast/ice-cast-type-with-error-124848.rs:17]: The undeclared `'unpinned` lifetime in the declaration of `MyType` results in `MyType` now having a reported error, which results in this casting error that was previously emitted during this test now being suppressed by the following pre-existing logic:

https://github.com/rust-lang/rust/blob/08ed1a18b66a68b2f3d27a3646d43984b02a15e2/compiler/rustc_hir_typeck/src/expr.rs#L1546-L1563

**Review by fmease — COMMENTED** [review]
Thanks for working on this! I won't be able to review this tonight but I'd like to note that thanks to your changes we should now be able to get rid of the minor hack in HIR ty lowering as I've mentioned in the issue:

https://github.com/rust-lang/rust/blob/f60a0f1bcc5a2a6dd8eb2d2021da79b40f5fbae9/compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_trait.rs#L454-L464

(by replacing that whole snippet with just `RegionInferReason::ObjectLifetimeDefault`)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/366a1b93e7f466ebe559477add05f064873d0c71..08ed1a18b66a68b2f3d27a3646d43984b02a15e2)*

File: tests/ui/stats/input-stats.stderr [hunk 2]
```diff
@@ -114,10 +114,10 @@ hir-stats - Type                      16 (NN.N%)             1
 hir-stats - Lifetime                  48 (NN.N%)             3
 hir-stats ExprField                 40 (NN.N%)             1            40
 hir-stats Mod                       32 (NN.N%)             1            32
-hir-stats Lifetime                  28 (NN.N%)             1            28
+hir-stats Lifetime                  32 (NN.N%)             1            32
```
Comment (eggyal) [inline tests/ui/stats/input-stats.stderr]: I confess I'm not 100% certain what these stats signify.  Of course feeding a signal that the undeclared lifetime error was previously emitted down from early name resolution to RBV could impact layouts, though I'm surprised this single bit of information (admittedly represented as at least one byte) appears to have increased *something* (a type's size?) from `28` to `32`...  especially given the enums in which it resides already have other variants carrying far more data.

I also note that the test contains the following comment:

https://github.com/rust-lang/rust/blob/08ed1a18b66a68b2f3d27a3646d43984b02a15e2/tests/ui/stats/input-stats.rs#L13-L16

However, testing locally, this update to the test output is required in both stage 1 and stage 2?

**Review by eggyal — COMMENTED** [review]
A couple of points for the review to consider.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/366a1b93e7f466ebe559477add05f064873d0c71..08ed1a18b66a68b2f3d27a3646d43984b02a15e2)*

**Comment by fmease** [comment]
Preliminary sanity perf check due to size changes.

@bors try @rust-timer queue

File: tests/ui/stats/input-stats.stderr (hunk 2 above)
Comment (nnethercote) [reply tests/ui/stats/input-stats.stderr]: That comment is a bit imprecise in the wording. It's not referring to "a single type was changed", but rather "the compiler's logic for laying out types has changed". This PR is the former.

Specifically, the size of `hir::Lifetime` has increased from 28 bytes to 32 bytes.

Comment (nnethercote) [reply tests/ui/stats/input-stats.stderr]: Following [these instructions](https://blog.mozilla.org/nnethercote/2018/11/09/how-to-get-the-size-of-rust-types-with-zprint-type-sizes/) you can get details on the type layouts. Old:
```text
print-type-size type: `rustc_hir::Lifetime`: 28 bytes, alignment: 4 bytes
print-type-size     field `.hir_id`: 8 bytes
print-type-size     field `.ident`: 12 bytes
print-type-size     field `.kind`: 4 bytes 
print-type-size     field `.syntax`: 1 bytes
print-type-size     field `.source`: 1 bytes
print-type-size     end padding: 2 bytes

print-type-size type: `rustc_hir::LifetimeKind`: 4 bytes, alignment: 4 bytes 
print-type-size     variant `Param`: 4 bytes
print-type-size         field `.0`: 4 bytes
print-type-size     variant `ImplicitObjectLifetimeDefault`: 0 bytes
print-type-size     variant `Error`: 0 bytes
print-type-size     variant `Infer`: 0 bytes
print-type-size     variant `Static`: 0 bytes
```
New:
```text
print-type-size type: `rustc_hir::Lifetime`: 32 bytes, alignment: 4 bytes
print-type-size     field `.hir_id`: 8 bytes
print-type-size     field `.ident`: 12 bytes
print-type-size     field `.kind`: 8 bytes
print-type-size     field `.syntax`: 1 bytes
print-type-size     field `.source`: 1 bytes
print-type-size     end padding: 2 bytes

print-type-size type: `rustc_hir::LifetimeKind`: 8 bytes, alignment: 4 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `Param`: 7 bytes
print-type-size         padding: 3 bytes 
print-type-size         field `.0`: 4 bytes, alignment: 4 bytes
print-type-size     variant `Error`: 1 bytes
print-type-size         field `.undeclared`: 1 bytes 
print-type-size     variant `ImplicitObjectLifetimeDefault`: 0 bytes
print-type-size     variant `Infer`: 0 bytes
print-type-size     variant `Static`: 0 bytes
```
Previously `LifetimeKind` had a single non-trivial variant, and its single field is a type with a few spare bits so the tag can be squeezed in there. But with two non-trivial variants that space optimization can no longer be used, the tag must be stored explicitly, and four byte alignment means the size goes up by 4. It's unfortunate when this kind of thing happens, especially when `Lifetime` is a type that is instantiated frequently.

Comment (nnethercote) [reply tests/ui/stats/input-stats.stderr]: You might be able to avoid the size increase if you split `Error` into two variants:
```rust
ErrorUndeclared(ErrorGuaranteed),
ErrorDeclared,
```

Comment (eggyal) [reply tests/ui/stats/input-stats.stderr]: Thanks!

File: compiler/rustc_resolve/src/late.rs [hunk 3]
```diff
@@ -3028,21 +3057,25 @@ impl<'a, 'ast, 'ra, 'tcx> LateResolutionVisitor<'a, 'ast, 'ra, 'tcx> {
...
+                    self.record_lifetime_param(param.id, LifetimeRes::Error(guar));
                     continue;
                 }
 
                 match seen_bindings.entry(ident) {
                     Entry::Occupied(entry) => {
                         let span = *entry.get();
                         let err = ResolutionError::NameAlreadyUsedInParameterList(ident, span);
-                        self.report_error(param.ident.span, err);
+                        let guar = self.r.report_error(param.ident.span, err);
```
Comment (eggyal) [inline compiler/rustc_resolve/src/late.rs]: This will unconditionally emit an error, whereas before it was suppressed in rustdoc; however I'm not sure that such suppression was correct here anyway—see the comments on `Self::should_report_error`, which don't appear to apply:

https://github.com/rust-lang/rust/blob/a5314362445be35e8d2e0291fa70d9a96daa283d/compiler/rustc_resolve/src/late.rs#L4718-L4720

In any event, this change doesn't appear to be breaking any tests...

**Review by eggyal — COMMENTED** [review]
Whereas in 08ed1a1 (now fa5cccfd)  I was only feeding `ErrorGuaranteed` through to RBV in the specific case of undeclared named lifetimes, in a531436 (now 8e83a57) I've extended the logic to feed through such an `ErrorGuaranteed` for every early lifetime resolution error.  This enables the [aforementioned "hack"](https://github.com/rust-lang/rust/pull/152076#pullrequestreview-3748225085) to be removed without giving rise to new instances of E0228 ("the lifetime bound for this object type cannot be deduced from context"), however it does also suppress a few other errors that previously were emitted—see updates to test outputs.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/794495e2b4a1353cf7b66ffc55f0e755490af2cc..a5314362445be35e8d2e0291fa70d9a96daa283d)*

I didn't squash (yet) in case you had begun reviewing and it was easier to see what has since changed.  However, these commits really ought to be squashed (with commensurate updates to the PR description and commit comments) before merging, and review may be easier combined in any event.

File: compiler/rustc_resolve/src/late.rs (hunk 3 above)
Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: Okay, it wasn't breaking `x test` locally, but clearly it's broken one in CI.

@rustbot author

Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: Actually, it appears that same test is failing on main branch irrespective of this PR (see tree closure due to latest failing rollups).  So not due to me after all.  😅

I'll rebase once the test is disabled, or the failure resolved.

Meanwhile, @rustbot ready

File: compiler/rustc_hir/src/hir.rs [hunk 4]
```diff
@@ -238,7 +238,8 @@ pub enum LifetimeKind {
 
     /// Indicates an error during lowering (usually `'_` in wrong place)
     /// that was already reported.
-    Error,
+    Error(ErrorGuaranteed),
+    NotFound,
```
Comment (fmease) [inline compiler/rustc_hir/src/hir.rs]: I'm super glad that we can obtain an `ErrorGuaranteed` in so many cases from the name resolver!

I'm not so happy about `NotFound`, we should try to fully get rid of it in favor of `Error(ErrorGuaranteed)`. Moreover, in the current state I feel like its name (plus lack of docs) would probably raise questions among anybody stumbling upon it.

As you know, we only use this variant for cases where `get_lifetime_res()` yields `None`. However, in my eyes it's a *bug* if we don't register a resolution for some lifetimes since it most likely means we forgot to visit some parts of the crate. There's one exception: If the crate is already super busted in some ways and we've already reported errors because of that, it's fine if we fail to resolve something.

Locally, I replaced the `unwrap_or(Error)` with an `unwrap()`, ran all UI tests and only found 2 ICEs because of this change: `tests/ui/lifetimes/issue-97193.rs` and `tests/ui/lifetimes/issue-97194.rs`. Minimized: `extern { fn f() { type T = &'a (); } }`. This falls under the aforementioned exception: In the name resolver, we seem to skip items nested inside foreign fns which is reasonable, after all they shouldn't have a body in the first place (but then the AST lowerer does visit it thereby leading to the 'mismatch').

Long story short, I think we should `dcx.delayed_bug(…)` / `dcx.span_delayed_bug(…)` if `get_lifetime_res` rets `None`. This would give us the wanted `ErrorGuaranteed`.

Comment (fmease) [reply compiler/rustc_hir/src/hir.rs]: However, I've seen that you no longer (eagerly) register `Error` resolutions in two `LifetimeRibKind::ElisionFailure` cases. Does that lead to more cases where `get_lifetime_res` returns `None` or do we eventually register the `Error`s? I haven't really looked that closely. If it's the former, that would be unfortunate (I mean we could always add more `delayed_bug`s…).

File: compiler/rustc_resolve/src/late.rs (hunk 3 above)
Comment (fmease) [reply compiler/rustc_resolve/src/late.rs]: Right, this change is mildly concerning. I have to investigate if this is reachable, otherwise we risk regressing crates in the ecosystem.

This made me realize that rustdoc does already report some lifetime resolution failures in bodies, I did not know this. So while `fn f() { undefined }` gets accepted intentionally by rustdoc, `fn f() { let _: &'a (); }` does not. Interesting that nobody has complained so far ^^' (and I wouldn't wanna change it actually).

**Review by fmease — COMMENTED** [review]
Thanks for working on this. I have some suggestions and questions but I'm really happy about the direction this PR is taking!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/035b01b794602d5861daa43ac792f372f8981ed7..8e83a5770aaad584341f74e3d2f3edc9c7d9fd5f)*

File: compiler/rustc_hir/src/hir.rs (hunk 4 above)
Comment (eggyal) [reply compiler/rustc_hir/src/hir.rs]: We still register the elision failures, they're just deferred until the error is emitted in `resolve_fn_signature` (as otherwise we don't have the `ErrorGuaranteed` to perform the registration); the error isn't emitted until then in order to collate all such elision failures on a function into a single diagnostic.

I totally agree with what you say about `NotFound`: I've removed it in 60ccf76a  and, as suggested, am using a deferred bug instead.  All tests are passing.  Again, this will want squashing down in due course.

File: compiler/rustc_resolve/src/late.rs (hunk 3 above)
Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: ~~Actually, I don't think it is reachable for lifetimes, which are handled in the `if let` that immediately precedes this `match`.  In da3dc124 I've reverted the unconditional diagnostic here and changed the lifetime arm to `unreachable!()`.  Again, will want squashing once reviewed.~~

I overlooked that the preceding `if let` is testing for collisions against `seen_lifetimes` from the outer scope, whereas this `match` is testing for collisions against `seen_bindings` in the current scope.

Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: Having dug into this a bit more, I think there are very few cases where this will now emit errors that weren't emitted before.

`LateResolutionVisitor::report_error`, which was used previously, suppresses errors when either:
* there is a glob error (such as `use unknown_module::*`) because it could be responsible for subsequent name resolution failures—however that isn't really relevant for these generic parameter collision errors, and since there is an error already I don't think it can be harmful to now emit another, also correct error?
* we are rustdoc and inside a function **body**, but **not a nested item**—there are very few situations where one can declare generic parameters outside of an item definition, this being one of the few I found:
    ```rust
    #![feature(closure_lifetime_binder)]

    fn foo() {
        for<'a, 'a> || -> () {};
    }
    ```

    Being behind a unstable feature gate, I don't suppose it's a problem if rustdoc starts emitting an error here where it didn't before?  I'm struggling to come up with other examples.

Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: Hm.  Okay, here's an example that doesn't require an unstable feature gate:

```rust
trait Trait {
    fn bar(&self) {}
}
impl Trait for () {}

fn foo() {
    <dyn for<'a, 'a> Trait>::bar(&());
}
```

and another :(

```rust
fn foo() {
    let _: for<'a, 'a> fn();
}
```

Comment (eggyal) [reply compiler/rustc_resolve/src/late.rs]: I suppose we could resolve cases such as these to a `LifetimeRes::RustdocSuppressedError` or something?  Not ideal, but not sure what would be better.

Implemented in 9135d8fe.

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 5]
```diff
@@ -1931,27 +1931,33 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
-            LifetimeRes::Static { .. } => {
-                assert!(matches!(ident.name, kw::StaticLifetime | kw::UnderscoreLifetime));
-                hir::LifetimeKind::Static
-            }
-            LifetimeRes::Error => hir::LifetimeKind::Error,
-            LifetimeRes::ElidedAnchor { .. } => {
-                panic!("Unexpected `ElidedAnchar` {:?} at {:?}", ident, ident.span);
-            }
-        };
+        let res = self.resolver.get_lifetime_res(id).map_or_else(
```
Comment (fmease) [inline compiler/rustc_ast_lowering/src/lib.rs]: This is a stylistic nit. I really don't like how rustfmt inflates the whole closure. Could you please replace

1. the `map_or_else` with a `match` (where `None=>` comes last) or better yet an `if let`
   * so `if let Some(…) = … { match … { … } } else { … }`
2. the `self.tcx.dcx()` with `self.dcx()`

This will get formatted a lot nicer and puts the more important happy path above the error path.

File: compiler/rustc_resolve/src/late.rs (hunk 3 above)
Comment (fmease) [reply compiler/rustc_resolve/src/late.rs]: Thanks for digging into this! It's only now that I see that this change only affects conflicting generic parameters. In that case, I consider this theoretical breakage acceptable. I can't think of a scenario where it'd be *useful* for rustdoc to suppress an error here. After all, the purpose of this is enabling users to document essentially `cfg`'ed out items.

File: compiler/rustc_resolve/src/late.rs [hunk 6]
```diff
@@ -746,7 +746,8 @@ pub(crate) struct DiagMetadata<'ast> {
 
     /// Accumulate the errors due to missed lifetime elision,
     /// and report them all at once for each function.
-    current_elision_failures: Vec<MissingLifetime>,
+    current_elision_failures:
+        Vec<(MissingLifetime, LifetimeElisionCandidate, NodeId, Option<NodeId>)>,
```
Comment (fmease) [inline compiler/rustc_resolve/src/late.rs]: I feel like the pairing `NodeId, Option<NodeId>` really obscures the fact that it represents the tagged union of exclusive ranges over `NodeId`s and single `NodeId`s.

Could you rewrite it more explicitly like so:


```suggestion
        Vec<(MissingLifetime, LifetimeElisionCandidate, Either<NodeId, Range<NodeId>>)>,
```

where `Either` comes from `rustc_data_structures::either` (a reexport of crate `either`). `rustc_resolve` already depends on `rustc_data_structures` meaning you don't need to add any new dependency to `rustc_resolve`. `Range` comes from `std::ops` obv.

The tuple should have the exact same size+alignment (i.e., size of 80 on 64bit archs, alignment of 8). [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=2d6746fe150aed3fa5c51c6a175005ad).

**Review by fmease — APPROVED** [review]
Thanks! I've just noticed that you've pushed another commit while I was in the midst of reviewing. As I've noted in [this review comment](https://github.com/rust-lang/rust/pull/152076#discussion_r2804294494) you couldn't see yet, I'm actually fine with this "breaking" rustdoc change. My initial concern is unsubstantial.

I'll put it into the queue once you've dropped the `RustdocSuppressedError` change again (I'm sorry ^^'), impl'ed my suggestions and finally squashed the commits (as you've already offered :D).

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/d7daac06d87e1252d10eaa44960164faac46beff..9135d8fed7ab8d9228458512c62aa22042c943ff)*

**Review by fmease — COMMENTED** [review]
Thanks for these kind words & thanks again for having worked on this!

@bors r+ rollup- 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152076/d7daac06d87e1252d10eaa44960164faac46beff..c43a33eec7b29a637ff8a41804d30e679092bad9)*
