### PR TITLE
Point to type argument span when used as trait

### LINKED ISSUE #35987: Wrong Error Message "Add is not a Trait"
I made a mistake while implementing Add for a type. Instead of using `+` for specifying multiple constraints, I accidentally used `,` and for some reason the compiler can't handle this very well. Instead of complaining about the `,` it says that `Add is not a Trait`

[Playground Link](https://play.rust-lang.org/?gist=fa1cbdc67f59ea33616f121ae697654a&version=nightly&backtrace=0)

``` rust
struct Okok<T: Clone>(T);

use std::ops::Add;

impl<T: Clone, Add> Add for Okok<T> {
    type Output = usize;

    fn add(self, rhs: Self) -> Self::Output {
        unimplemented!();
    }
}
...
```

```
error[E0404]: `Add` is not a trait
 --> <anon>:5:21
  |
5 | impl<T: Clone, Add> Add for Okok<T> {
  |                     ^^^ not a trait

error: cannot continue compilation due to previous error
```

This happens on both Nightly, Beta and Stable.

### PR DESCRIPTION
**Pull request by estebank**
Given the following code:

``` rust
struct Foo<T: Clone>(T);

use std::ops::Add;

impl<T: Clone, Add> Add for Foo<T> {
  type Output = usize;

  fn add(self, rhs: Self) -> Self::Output {
    unimplemented!();
  }
}
```

present the following output:

``` nocode
error[E0404]: `Add` is not a trait
 --> file3.rs:5:21
  |
5 | impl<T: Clone, Add> Add for Okok<T> {
  |                ---  ^^^ expected trait, found type parameter
  |                |
  |                type parameter defined here
```

Fixes #35987.

### CODE REVIEW

File: src/libsyntax/ast.rs [hunk 1]
```diff
@@ -399,6 +399,16 @@ impl Generics {
     pub fn is_parameterized(&self) -> bool {
         self.is_lt_parameterized() || self.is_type_parameterized()
     }
+    pub fn span_for_name(&self, name: &str) -> Option<Span> {
```
Comment (estebank) [inline src/libsyntax/ast.rs]: I'm not convinced that this is the best way of getting the type argument's span. Does anyone have a pointer as to an alternative?

Comment (GuillaumeGomez) [inline src/libsyntax/ast.rs]: I remember doing such a thing but can't find the PR. From my point of view, this is correct. However I can totally overpass a better solution.

Anything in mind @eddyb?

File: src/test/ui/span/issue-35987.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+struct Foo<T: Clone>(T);
+
+use std::ops::Add;
+
+impl<T: Clone, Add> Add for Foo<T> {
+  type Output = usize;
```
Comment (estebank) [inline src/test/ui/span/issue-35987.rs]: Fixed.

File: src/libsyntax/ast.rs [hunk 3]
```diff
@@ -399,6 +399,16 @@ impl Generics {
...
+        let mut span = None;
+        for t in &self.ty_params {
+            if &format!("{}", t.ident.name.as_str()) == name {
```
Comment (sanxiyn) [inline src/libsyntax/ast.rs]: This is redundant. You can do `&t.ident.name.as_str() == name` instead.

File: src/libsyntax/ast.rs [hunk 4]
```diff
@@ -399,6 +399,16 @@ impl Generics {
...
+                span = Some(t.span);
+                break;
```
Comment (sanxiyn) [inline src/libsyntax/ast.rs]: You can `return Some(t.span);` instead of breaking, and get rid of the local variable `span`.

File: src/libsyntax/ast.rs (hunk 1 above)
Comment (jonathandturner) [inline src/libsyntax/ast.rs]: Seems okay.  If there are duplicate type parameter names, you'll get a different error for that.

**Comment by estebank** [comment]
@jonathandturner fixed.
