### PR TITLE
Use `find_attr` instead of `attr::contains_name` in `lower_const_item_rhs`

### LINKED ISSUE #151250: ICE: `thir_body queried for type_const`
snippet:
````rust
impl S {
    #[type_const]
    const SIZE: usize;
}

````

Version information
````
rustc 1.94.0-nightly (9f6cd6def 2026-01-17)
binary: rustc
commit-hash: 9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a
commit-date: 2026-01-17
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_mir_build/src/thir/cx/mod.rs#L15-L27

Command:
`/home/matthias/.rustup/toolchains/alt-master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: associated constant in `impl` without body
 --> /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:3:5
  |
3 |     const SIZE: usize;
  |     ^^^^^^^^^^^^^^^^^-
  |                      |
  |                      help: provide a definition for the constant: `= <expr>;`

error[E0425]: cannot find type `S` in this scope
 --> /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:1:6
  |
1 | impl S {
  |      ^ not found in this scope

error[E0658]: the `#[type_const]` attribute is an experimental feature
 --> /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:2:5
  |
2 |     #[type_const]
  |     ^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = help: add `#![feature(min_generic_const_args)]` to the crate attributes to enable
  = note: this compiler was built on 2026-01-17; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:4:2
  |
4 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs`


thread 'rustc' (1785342) panicked at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_mir_build/src/thir/cx/mod.rs:21:5:
thir_body queried for type_const
stack backtrace:
   0:     0x7fb315763980 - std[9cbaf667f00ffb02]::backtrace_rs::backtrace::libunwind::trace
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x7fb315763980 - std[9cbaf667f00ffb02]::backtrace_rs::backtrace::trace_unsynchronized::<std[9cbaf667f00ffb02]::sys::backtrace::_print_fmt::{closure#1}>
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x7fb315763980 - std[9cbaf667f00ffb02]::sys::backtrace::_print_fmt
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/backtrace.rs:74:9
   3:     0x7fb315763980 - <<std[9cbaf667f00ffb02]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[e4e5e6abe2e95383]::fmt::Display>::fmt
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/backtrace.rs:44:26
   4:     0x7fb310deb38e - <core[e4e5e6abe2e95383]::fmt::rt::Argument>::fmt
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/fmt/rt.rs:152:76
   5:     0x7fb310deb38e - core[e4e5e6abe2e95383]::fmt::write
   6:     0x7fb31577c1dc - std[9cbaf667f00ffb02]::io::default_write_fmt::<std[9cbaf667f00ffb02]::sys::stdio::unix::Stderr>
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/io/mod.rs:639:11
   7:     0x7fb31577c1dc - <std[9cbaf667f00ffb02]::sys::stdio::unix::Stderr as std[9cbaf667f00ffb02]::io::Write>::write_fmt
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/io/mod.rs:1994:13
   8:     0x7fb315729316 - <std[9cbaf667f00ffb02]::sys::backtrace::BacktraceLock>::print
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/backtrace.rs:47:9
   9:     0x7fb315729316 - std[9cbaf667f00ffb02]::panicking::default_hook::{closure#0}
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:292:27
  10:     0x7fb315752ba1 - std[9cbaf667f00ffb02]::panicking::default_hook
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:319:9
  11:     0x7fb3121bcd68 - <alloc[8095fa9044f93caa]::boxed::Box<dyn for<'a, 'b> core[e4e5e6abe2e95383]::ops::function::Fn<(&'a std[9cbaf667f00ffb02]::panic::PanicHookInfo<'b>,), Output = ()> + core[e4e5e6abe2e95383]::marker::Sync + core[e4e5e6abe2e95383]::marker::Send> as core[e4e5e6abe2e95383]::ops::function::Fn<(&std[9cbaf667f00ffb02]::panic::PanicHookInfo,)>>::call
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/alloc/src/boxed.rs:2220:9
  12:     0x7fb3121bcd68 - rustc_driver_impl[6cf4454f7f4c82b8]::install_ice_hook::{closure#1}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_driver_impl/src/lib.rs:1442:17
  13:     0x7fb3121bcd68 - <alloc[8095fa9044f93caa]::boxed::Box<rustc_driver_impl[6cf4454f7f4c82b8]::install_ice_hook::{closure#1}> as core[e4e5e6abe2e95383]::ops::function::Fn<(&dyn for<'a, 'b> core[e4e5e6abe2e95383]::ops::function::Fn<(&'a std[9cbaf667f00ffb02]::panic::PanicHookInfo<'b>,), Output = ()> + core[e4e5e6abe2e95383]::marker::Sync + core[e4e5e6abe2e95383]::marker::Send, &std[9cbaf667f00ffb02]::panic::PanicHookInfo)>>::call
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/alloc/src/boxed.rs:2220:9
  14:     0x7fb3121bcd68 - std[9cbaf667f00ffb02]::panicking::update_hook::<alloc[8095fa9044f93caa]::boxed::Box<rustc_driver_impl[6cf4454f7f4c82b8]::install_ice_hook::{closure#1}>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:235:47
  15:     0x7fb315752f1a - <alloc[8095fa9044f93caa]::boxed::Box<dyn for<'a, 'b> core[e4e5e6abe2e95383]::ops::function::Fn<(&'a std[9cbaf667f00ffb02]::panic::PanicHookInfo<'b>,), Output = ()> + core[e4e5e6abe2e95383]::marker::Sync + core[e4e5e6abe2e95383]::marker::Send> as core[e4e5e6abe2e95383]::ops::function::Fn<(&std[9cbaf667f00ffb02]::panic::PanicHookInfo,)>>::call
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/alloc/src/boxed.rs:2220:9
  16:     0x7fb315752f1a - std[9cbaf667f00ffb02]::panicking::panic_with_hook
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:833:13
  17:     0x7fb31572940c - std[9cbaf667f00ffb02]::panicking::panic_handler::{closure#0}
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:691:13
  18:     0x7fb3157149b9 - std[9cbaf667f00ffb02]::sys::backtrace::__rust_end_short_backtrace::<std[9cbaf667f00ffb02]::panicking::panic_handler::{closure#0}, !>
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/backtrace.rs:182:18
  19:     0x7fb31572b43d - __rustc[34e91dcd52d96904]::rust_begin_unwind
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:689:5
  20:     0x7fb310debdbc - core[e4e5e6abe2e95383]::panicking::panic_fmt
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/panicking.rs:80:14
  21:     0x7fb313a2d868 - rustc_mir_build[f1e69c9a9818c514]::thir::cx::thir_body
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_mir_build/src/thir/cx/mod.rs:21:5
  22:     0x7fb3144b56ed - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::thir_body::dynamic_query::{closure#2}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:282:9
  23:     0x7fb3144b56ed - rustc_query_impl[b81d3a0c7e59fa52]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b81d3a0c7e59fa52]::query_impl::thir_body::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:552:18
  24:     0x7fb31491e183 - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::thir_body::dynamic_query::{closure#2}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:629:25
  25:     0x7fb31491e183 - <rustc_query_impl[b81d3a0c7e59fa52]::query_impl::thir_body::dynamic_query::{closure#2} as core[e4e5e6abe2e95383]::ops::function::FnOnce<(rustc_middle[1b95161445d16734]::ty::context::TyCtxt, rustc_span[f206bd799c057bfa]::def_id::LocalDefId)>>::call_once
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/ops/function.rs:250:5
  26:     0x7fb3145b6ed2 - <rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false> as rustc_query_system[c5d96a7986f8cdae]::query::config::QueryConfig<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>>::compute
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/lib.rs:116:9
  27:     0x7fb3145b6ed2 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:497:72
  28:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::enter_context::<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:60:9
  29:     0x7fb3145b6ed2 - <std[9cbaf667f00ffb02]::thread::local::LocalKey<core[e4e5e6abe2e95383]::cell::Cell<*const ()>>>::try_with::<rustc_middle[1b95161445d16734]::ty::context::tls::enter_context<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/local.rs:513:12
  30:     0x7fb3145b6ed2 - <std[9cbaf667f00ffb02]::thread::local::LocalKey<core[e4e5e6abe2e95383]::cell::Cell<*const ()>>>::with::<rustc_middle[1b95161445d16734]::ty::context::tls::enter_context<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/local.rs:477:20
  31:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::enter_context::<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:57:9
  32:     0x7fb3145b6ed2 - <rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:156:13
  33:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context::<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:112:9
  34:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context::<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:90:36
  35:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context_opt::<rustc_middle[1b95161445d16734]::ty::context::tls::with_context<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:79:18
  36:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context::<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:90:5
  37:     0x7fb3145b6ed2 - rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context::<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:103:5
  38:     0x7fb3145b6ed2 - <rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:142:9
  39:     0x7fb3145b6ed2 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:497:22
  40:     0x7fb3145b6ed2 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt, false>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:433:9
  41:     0x7fb3145b6ed2 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::try_execute_query::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt, false>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:376:13
  42:     0x7fb314731a8f - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:818:32
  43:     0x7fb314731a8f - stacker[bb2e07ef96ab4588]::maybe_grow::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  44:     0x7fb314731a8f - rustc_data_structures[27385a8aa36ea57]::stack::ensure_sufficient_stack::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_data_structures/src/stack.rs:21:5
  45:     0x7fb314731a8f - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:818:5
  46:     0x7fb314731a8f - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::thir_body::get_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:605:26
  47:     0x7fb313a16aa3 - rustc_middle[1b95161445d16734]::query::inner::query_get_at::<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/query/inner.rs:33:17
  48:     0x7fb313a16aa3 - <rustc_middle[1b95161445d16734]::query::plumbing::TyCtxtAt>::thir_body::<rustc_span[f206bd799c057bfa]::def_id::LocalDefId>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/query/plumbing.rs:415:31
  49:     0x7fb313a16aa3 - <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::thir_body::<rustc_span[f206bd799c057bfa]::def_id::LocalDefId>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/query/plumbing.rs:406:35
  50:     0x7fb313a16aa3 - rustc_mir_build[f1e69c9a9818c514]::check_unsafety::check_unsafety
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_mir_build/src/check_unsafety.rs:1169:32
  51:     0x7fb314495f0c - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:282:9
  52:     0x7fb314495f0c - rustc_query_impl[b81d3a0c7e59fa52]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b81d3a0c7e59fa52]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:552:18
  53:     0x7fb3148ab65b - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::check_unsafety::dynamic_query::{closure#2}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:629:25
  54:     0x7fb3148ab65b - <rustc_query_impl[b81d3a0c7e59fa52]::query_impl::check_unsafety::dynamic_query::{closure#2} as core[e4e5e6abe2e95383]::ops::function::FnOnce<(rustc_middle[1b95161445d16734]::ty::context::TyCtxt, rustc_span[f206bd799c057bfa]::def_id::LocalDefId)>>::call_once
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/ops/function.rs:250:5
  55:     0x7fb3145b4967 - <rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false> as rustc_query_system[c5d96a7986f8cdae]::query::config::QueryConfig<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>>::compute
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/lib.rs:116:9
  56:     0x7fb3145b4967 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:497:72
  57:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::enter_context::<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:60:9
  58:     0x7fb3145b4967 - <std[9cbaf667f00ffb02]::thread::local::LocalKey<core[e4e5e6abe2e95383]::cell::Cell<*const ()>>>::try_with::<rustc_middle[1b95161445d16734]::ty::context::tls::enter_context<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/local.rs:513:12
  59:     0x7fb3145b4967 - <std[9cbaf667f00ffb02]::thread::local::LocalKey<core[e4e5e6abe2e95383]::cell::Cell<*const ()>>>::with::<rustc_middle[1b95161445d16734]::ty::context::tls::enter_context<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/local.rs:477:20
  60:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::enter_context::<rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:57:9
  61:     0x7fb3145b4967 - <rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:156:13
  62:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context::<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:112:9
  63:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context::<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:90:36
  64:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context_opt::<rustc_middle[1b95161445d16734]::ty::context::tls::with_context<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:79:18
  65:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::with_context::<rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:90:5
  66:     0x7fb3145b4967 - rustc_middle[1b95161445d16734]::ty::context::tls::with_related_context::<<rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/ty/context/tls.rs:103:5
  67:     0x7fb3145b4967 - <rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt as rustc_query_system[c5d96a7986f8cdae]::query::QueryContext>::start_query::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:142:9
  68:     0x7fb3145b4967 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:497:22
  69:     0x7fb3145b4967 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::execute_job::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt, false>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:433:9
  70:     0x7fb3145b4967 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::try_execute_query::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt, false>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:376:13
  71:     0x7fb3146cc043 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:818:32
  72:     0x7fb3146cc043 - stacker[bb2e07ef96ab4588]::maybe_grow::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  73:     0x7fb3146cc043 - rustc_data_structures[27385a8aa36ea57]::stack::ensure_sufficient_stack::<rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_data_structures/src/stack.rs:21:5
  74:     0x7fb3146cc043 - rustc_query_system[c5d96a7986f8cdae]::query::plumbing::get_query_non_incr::<rustc_query_impl[b81d3a0c7e59fa52]::DynamicConfig<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[b81d3a0c7e59fa52]::plumbing::QueryCtxt>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_system/src/query/plumbing.rs:818:5
  75:     0x7fb3146cc043 - rustc_query_impl[b81d3a0c7e59fa52]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_query_impl/src/plumbing.rs:605:26
  76:     0x7fb3130a3931 - rustc_middle[1b95161445d16734]::query::inner::query_ensure::<rustc_data_structures[27385a8aa36ea57]::vec_cache::VecCache<rustc_span[f206bd799c057bfa]::def_id::LocalDefId, rustc_middle[1b95161445d16734]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[c5d96a7986f8cdae]::dep_graph::graph::DepNodeIndex>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/query/inner.rs:51:9
  77:     0x7fb3130a3931 - <rustc_middle[1b95161445d16734]::query::plumbing::TyCtxtEnsureOk>::check_unsafety::<rustc_span[f206bd799c057bfa]::def_id::LocalDefId>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/query/plumbing.rs:173:9
  78:     0x7fb3130a3931 - rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_interface/src/passes.rs:1102:33
  79:     0x7fb3130a3931 - <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_middle/src/hir/map.rs:339:79
  80:     0x7fb31312ce62 - rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in::<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_data_structures/src/sync/parallel.rs:181:30
  81:     0x7fb31312ce62 - <core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}> as core[e4e5e6abe2e95383]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/panic/unwind_safe.rs:274:9
  82:     0x7fb31312ce62 - std[9cbaf667f00ffb02]::panicking::catch_unwind::do_call::<core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:581:40
  83:     0x7fb31312ce62 - std[9cbaf667f00ffb02]::panicking::catch_unwind::<(), core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:544:19
  84:     0x7fb31312ce62 - std[9cbaf667f00ffb02]::panic::catch_unwind::<core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panic.rs:359:14
  85:     0x7fb31312ce62 - <rustc_data_structures[27385a8aa36ea57]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_data_structures/src/sync/parallel.rs:23:9
  86:     0x7fb31312ce62 - rustc_data_structures[27385a8aa36ea57]::sync::parallel::par_for_each_in::<&rustc_span[f206bd799c057bfa]::def_id::LocalDefId, &[rustc_span[f206bd799c057bfa]::def_id::LocalDefId], <rustc_middle[1b95161445d16734]::ty::context::TyCtxt>::par_hir_body_owners<rustc_interface[5e8da89e8094fa0b]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_data_structures/src/sync/parallel.rs:181:23

<snip>


 146:     0x7fb3121ab265 - <scoped_tls[f130dae970fb5eaf]::ScopedKey<rustc_span[f206bd799c057bfa]::SessionGlobals>>::set::<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>
                               at /rust/deps/scoped-tls-1.0.1/src/lib.rs:137:9
 147:     0x7fb3121ab265 - rustc_span[f206bd799c057bfa]::create_session_globals_then::<(), rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_span/src/lib.rs:144:21
 148:     0x7fb3121ab265 - rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals::<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/compiler/rustc_interface/src/util.rs:159:17
 149:     0x7fb3121ab265 - std[9cbaf667f00ffb02]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/backtrace.rs:166:18
 150:     0x7fb3121c6a73 - std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked::<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/lifecycle.rs:91:13
 151:     0x7fb3121c6a73 - <core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}> as core[e4e5e6abe2e95383]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/panic/unwind_safe.rs:274:9
 152:     0x7fb3121c6a73 - std[9cbaf667f00ffb02]::panicking::catch_unwind::do_call::<core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:581:40
 153:     0x7fb3121c6a73 - std[9cbaf667f00ffb02]::panicking::catch_unwind::<(), core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panicking.rs:544:19
 154:     0x7fb3121c6a73 - std[9cbaf667f00ffb02]::panic::catch_unwind::<core[e4e5e6abe2e95383]::panic::unwind_safe::AssertUnwindSafe<std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/panic.rs:359:14
 155:     0x7fb3121c6a73 - std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked::<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/thread/lifecycle.rs:89:26
 156:     0x7fb3121c6a73 - <std[9cbaf667f00ffb02]::thread::lifecycle::spawn_unchecked<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_with_globals<rustc_interface[5e8da89e8094fa0b]::util::run_in_thread_pool_with_globals<rustc_interface[5e8da89e8094fa0b]::interface::run_compiler<(), rustc_driver_impl[6cf4454f7f4c82b8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[e4e5e6abe2e95383]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc-dev/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/core/src/ops/function.rs:250:5
 157:     0x7fb3157607af - <alloc[8095fa9044f93caa]::boxed::Box<dyn core[e4e5e6abe2e95383]::ops::function::FnOnce<(), Output = ()> + core[e4e5e6abe2e95383]::marker::Send> as core[e4e5e6abe2e95383]::ops::function::FnOnce<()>>::call_once
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/alloc/src/boxed.rs:2206:9
 158:     0x7fb3157607af - <std[9cbaf667f00ffb02]::sys::thread::unix::Thread>::new::thread_start
                               at /rustc/9f6cd6defbd7ef13f6777aa8e43b14d69f0a830a/library/std/src/sys/thread/unix.rs:127:17
 159:     0x7fb30f29698b - <unknown>
 160:     0x7fb30f31a9cc - <unknown>
 161:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (9f6cd6def 2026-01-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [thir_body] building THIR for `<impl at /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:1:1: 1:7>::SIZE`
#1 [check_unsafety] unsafety-checking `<impl at /tmp/icemaker_global_tempdir.4br6Rvy2hukJ/rustc_testrunner_tmpdir_reporting.cPLx6JtU7TWX/mvce.rs:1:1: 1:7>::SIZE`
#2 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by mu001999**
Fixes rust-lang/rust#151250

`attr::contains_name` uses `AttributeExt::name()` to filter, but for `hir::Attribute::Parsed`, this method will return `None`, and then `attr::contains_name` will return `false` here. So that the previous logic cannot work as expected.

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -2384,7 +2384,7 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
             Some(ConstItemRhs::TypeConst(anon)) => {
                 hir::ConstItemRhs::TypeConst(self.lower_anon_const_to_const_arg_and_alloc(anon))
             }
-            None if attr::contains_name(attrs, sym::type_const) => {
+            None if find_attr!(attrs, AttributeKind::TypeConst(_)) => {
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/lib.rs:2387]: Ah good catch!

Is using `self.resolver.tcx.is_type_const` possible here? I'd like to consolidate all our type_const attr checks into calling this function if possible, but I'm not sure if ast_lowering is too early in the compiler to be utilizing that function :thinking:

Comment (mu001999) [reply compiler/rustc_ast_lowering/src/lib.rs:2387]: I will have a try

Comment (mu001999) [reply compiler/rustc_ast_lowering/src/lib.rs:2387]: > I'm not sure if ast_lowering is too early in the compiler to be utilizing that function

I tried locally. Unfortunately, it doesn't work since it's too early to call it here.
