### PR TITLE
Suggest importing macros from the crate root

### LINKED ISSUE #59764: Suggest importing macros from crate roots
Consider a directory for a crate `mycrate`:
```
src
	- lib.rs
	- foo.rs
```
`foo.rs` declares a `macro_rules! makro` macro and `#[macro_export]`s it.

In a separate crate, a user writes:
```rust
use mycrate::foo::makro; // error: cannot find macro `makro!` in this scope
```

This is because `#[macro_export]` exports the macro in the crate root [rather than the module in which it is defined](https://github.com/rust-lang/rust/issues/58914#issuecomment-469265938).

It's very difficult to debug this if you're not aware of this behaviour. It would be really helpful to have a suggestion to replace the suggestion with `use mycrate::makro;`, or have a message saying that `makro` exists in `mycrate` (ideally with some background information describing the problem).

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #59764.

r? @estebank 
cc @varkor

### CODE REVIEW

File: src/librustc_resolve/error_reporting.rs [hunk 1]
```diff
@@ -564,10 +565,291 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+        if ModuleOrUniformRoot::same_def(ModuleOrUniformRoot::Module(crate_module), module) {
+            // Don't make a suggestion if the import was already from the root of the
+            // crate.
+            return None;
+        }
+
+        let resolutions = crate_module.resolutions.borrow();
+        let resolution = resolutions.get(&(ident, MacroNS))?;
+        let binding = resolution.borrow().binding()?;
+        if let Def::Macro(_, MacroKind::Bang) = binding.def() {
```
Comment (davidtwco) [inline src/librustc_resolve/error_reporting.rs]: I would have preferred to have a better check (that the user was looking for a macro, or that the macro we suggest was what they were looking for) but couldn't work out a nice way to do so.

File: src/librustc_resolve/error_reporting.rs [hunk 2]
```diff
@@ -564,10 +565,291 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+            let suggestion = Some((
+                span,
+                String::from("a macro with this name exists at the root of the crate"),
+                correction,
+                Applicability::MaybeIncorrect,
+            ));
+            let note = vec![
+                "this could be because a macro annotated with `#[macro_export]`...".to_string(),
+                "...will be exported at the root of the crate instead of the...".to_string(),
+                "...module where it is defined".to_string(),
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: Does this really need to be three separate lines? We haven't shied away from long notes in other errors, only splitting them in this way when they can potentially have spans.

**Review by estebank — COMMENTED** [review]
It seems ok to me, but there's quite a bit of span wrangling here that makes me uneasy (but is sometimes unavoidable). I'll take a closer look at that code later. For now the only complaint I'd have is the separation of the note into 3. Relying on terminal word-wrapping is reasonable in my mind.

File: src/librustc_resolve/error_reporting.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_resolve/error_reporting.rs]: Fixed.

**Comment by davidtwco** [comment]
> It seems ok to me, but there's quite a bit of span wrangling here that makes me uneasy (but is sometimes unavoidable).

I only span-wrangled here because I couldn't see another way in this case. If you can think of an alternative, I'll happily take that approach. While I have introduced some more span-wrangling with this PR, I was able to re-use a bunch of the existing span-wrangling from a previous PR, some of the diff is just extracting that existing logic into functions.

File: src/librustc_resolve/error_reporting.rs [hunk 3]
```diff
@@ -564,10 +565,290 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+    /// the crate.
+    ///
+    /// ```
+    /// help: a macro with this name exists at the root of the crate
+    ///    |
+    /// LL | use issue_59764::makro;
+    ///    |     ^^^^^^^^^^^^^^^^^^
+    ///    |
+    ///    = note: a macro annotated with `#[macro_export]` will be exported at the...
+    ///    = note: ...root of the crate instead of the module it is defined
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: update doc

File: src/librustc_resolve/error_reporting.rs [hunk 4]
```diff
@@ -564,10 +565,290 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+                    //   ie. `use a::b::{c, d};`
+                    //                    ^^^
+                    if let Some(previous_span) = extend_span_to_previous_binding(
+                        self.resolver.session, binding_span,
+                    ) {
+                        debug!("check_for_module_export_macro: previous_span={:?}", previous_span);
+                        removal_span = removal_span.with_lo(previous_span.lo());
+                    }
+                }
+                debug!("check_for_module_export_macro: removal_span={:?}", removal_span);
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: Could all this logic since 628 be moved to its own reusable method?

File: src/librustc_resolve/error_reporting.rs [hunk 5]
```diff
@@ -564,10 +565,290 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+                }
+
+                // Calculate the number of characters into a snippet to remove the removal
+                // span.
+                let lo = removal_span.lo() - remaining_span.lo();
+                let hi = lo + (removal_span.hi() - removal_span.lo());
+                if let Ok(mut remaining) = source_map.span_to_snippet(remaining_span) {
+                    // Remove the original location of the binding.
+                    remaining.replace_range((lo.0 as usize)..(hi.0 as usize), "");
+                    correction = format!("use {}::{{{}, {}}};", module_name, import, remaining);
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: This has the potential to mangle the formatting severely, so I'd prefer a multipart suggestion for removing and adding the imports in reasonable places, instead of trying to synthesize a single span suggestion. That would still have problems though, namely having the moved imports all in the first line and keeping an empty line with all its whitespace, but I feel that we could address the later issue from the suggestion engine itself. The comments are great, but the span tweaking itself gives me pause, as I've introduced bugs doing similar things in the past.

File: src/librustc_resolve/error_reporting.rs [hunk 6]
```diff
@@ -564,10 +565,290 @@ impl<'a, 'b:'a> ImportResolver<'a, 'b> {
...
+
+    // Calculate the expected difference between the first `{` character and the start of a
+    // use statement.
+    //  ie. `use foo::{..};`
+    //       ^^^^
+    //       |   ^^^
+    //       4   |  ^^
+    //           3  |
+    //              2
+    let expected_difference = BytePos((module_name.as_str().len() + 4 + 2) as u32);
```
Comment (estebank) [inline src/librustc_resolve/error_reporting.rs]: This has a _big_ assumption baked in. I _could_ write
```
use   	     
   	     foo::{..};
```
and it's perfectly valid (note the interleaved `\t`s inside as well).

File: src/librustc_resolve/error_reporting.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_resolve/error_reporting.rs]: Fixed.

File: src/librustc_resolve/error_reporting.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_resolve/error_reporting.rs]: I don't think there's much useful logic to be extracted here after the multipart suggestion change.

File: src/librustc_resolve/error_reporting.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_resolve/error_reporting.rs]: I've changed this to a multipart suggestion.

File: src/librustc_resolve/error_reporting.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_resolve/error_reporting.rs]: I've updated the logic here to handle this case. I don't know how I missed that initially.

**Comment by estebank** [comment]
r=me once travis finishes
