### PR TITLE
Skip default methods if normalization fails

### LINKED ISSUE #23485: ICE when default method references associated type that can't be normalized
This trait causes an ICE when implemented and casted appropriately (from #23300):

```rust

trait Iterator {
    type Item;

    fn next(&mut self) -> Option<Self::Item>;

    fn cloned(self) -> Cloned<Self> where
        Self: Sized,
        Self::Item: Deref,
        <Self::Item as Deref>::Target: Clone,
    {
        Cloned { it: self }
    }
}
```

I'll attach the full test in the PR, it's a pain for me to cut-and-paste it right now :)

### PR DESCRIPTION
**Pull request by nikomatsakis**
When testing whether a default method predicates are satisfiable,
combine normalization with this check so that we also skip the
default method if normalization fails. Fixes #23485.

r? @nrc (I tried to address your nit from before as well)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm, that test actually doesn't ICE when you are not on sfackler's branch. I don't really understand why not though.

**Comment by nikomatsakis** [comment]
OK, I think I have a test that represents the issue now :)

File: src/librustc/middle/traits/object_safety.rs [hunk 1]
```diff
@@ -204,6 +205,30 @@ fn object_safety_violations_for_method<'tcx>(tcx: &ty::ctxt<'tcx>,
...
+}
+
+/// We say a method is *vtable safe* if it can be invoked on a trait
+/// object.  Note that object-safe traits can have some
+/// non-vtable-safe methods, so long as they require `Self:Sized` or
+/// otherwise ensure that they cannot be used when `Self=Trait`.
+pub fn is_vtable_safe_method<'tcx>(tcx: &ty::ctxt<'tcx>,
+                                                 trait_def_id: ast::DefId,
+                                                 method: &ty::Method<'tcx>)
+                                                 -> bool
```
Comment (nrc) [inline src/librustc/middle/traits/object_safety.rs]: indent of args

File: src/librustc_trans/trans/common.rs [hunk 2]
```diff
@@ -1068,17 +1068,30 @@ pub fn fulfill_obligation<'a, 'tcx>(ccx: &CrateContext<'a, 'tcx>,
...
-    debug!("predicates_hold(predicates={})",
+    debug!("normalize_and_test_predicates(predicates={})",
            predicates.repr(ccx.tcx()));
 
-    let infcx = infer::new_infer_ctxt(ccx.tcx());
+    let tcx = ccx.tcx();
+    let infcx = infer::new_infer_ctxt(tcx);
+    let typer = NormalizingClosureTyper::new(tcx);
+    let mut selcx = traits::SelectionContext::new(&infcx, &typer);
     let mut fulfill_cx = traits::FulfillmentContext::new();
```
Comment (nrc) [inline src/librustc_trans/trans/common.rs]: This looks like boilerplate that could be rolled up into a new constructor for `SelectionContext`, although I guess you tend to use infcx more than selcx in the next few lines. It is somewhat sad to have so many contexts floating around, I guess.

**Comment by nrc** [comment]
r+ modulo nits

File: src/librustc_trans/trans/common.rs (hunk 2 above)
Comment (nikomatsakis) [inline src/librustc_trans/trans/common.rs]: @nrc yes I am working on a refactoring (in a branch) of these contexts. Not so much for code cleanup (although that is a goal) as for improving performance and our ability to deduce things. But one of the things I think make sense is to collapse some of these contexts that don't serve much function. Still not quite sure the best way to do it.

**Comment by sfackler** [comment]
Ping?

**Comment by nikomatsakis** [comment]
@sfackler argh let me address those nits...
