### PR TITLE
fix(#141141): When expanding `PartialEq`, check equality of scalar types first.

### LINKED ISSUE #141141: #[derive(PartialEq)] does not reorder field comparisons to improve performance
#### Summary

The `#[derive(PartialEq)]` macro currently compares fields **in declaration order**, which can lead to suboptimal performance when expensive fields (like references or slices) are compared before cheap fields (like scalars).

This can cause unnecessary memory comparisons (`memcmp`/`bcmp`) to run even when a cheap field would have determined inequality early.

---

#### Reproducible Example

```rust
#[repr(C)]
#[derive(PartialEq, Eq)]
pub struct StructA<'a> {
    field_1: &'a str, // expensive to compare
    field_2: u8,      // cheap
}

#[repr(C)]
#[derive(PartialEq, Eq)]
pub struct StructB<'a> {
    field_1: u8,      // cheap
    field_2: &'a str, // expensive
}

pub fn compare_a(a: StructA, b: StructA) -> bool {
    a == b
}

pub fn compare_b(a: StructB, b: StructB) -> bool {
    a == b
}
```

#### Generated Assembly

* `compare_a` compares the string (`bcmp`) before checking the `u8`.
* `compare_b` checks the `u8` first and avoids `bcmp` on early exit.

 See Godbolt for live comparison: [https://godbolt.org/z/7a41eT3P3](https://godbolt.org/z/7a41eT3P3)

---

#### Meta

* Rust version: stable (1.##) / nightly
* Affects `#[derive(PartialEq)]` macro
* Related: optimization of derived traits

### PR DESCRIPTION
**Pull request by Sol-Ell**
Fixes rust-lang/rust#141141.

Now, `cs_eq` function of `partial_eq.rs` compares [scalar types](https://doc.rust-lang.org/rust-by-example/primitives.html#scalar-types) first.

- Add `is_scalar` field to `FieldInfo`.
- Add `is_scalar` method to `TyKind`.
- Pass `FieldInfo` via `CsFold::Combine` and refactor code relying on it.
- Implement `TryFrom<&str>` and `TryFrom<Symbol>` for FloatTy.
- Implement `TryFrom<&str>` and `TryFrom<Symbol>` for IntTy.
- Implement `TryFrom<&str>` and `TryFrom<Symbol>` for UintTy.

### CODE REVIEW

File: tests/ui/deriving/deriving-all-codegen.rs [hunk 1]
```diff
@@ -45,6 +45,23 @@ struct Big {
     b1: u32, b2: u32, b3: u32, b4: u32, b5: u32, b6: u32, b7: u32, b8: u32,
 }
 
+// `PartialEq` must reorder scalar types to be first and preserve the order of
+// non-scalar types. In contrast, `PartialOrd` must compare by order of declaration.
```
Comment (nnethercote) [inline tests/ui/deriving/deriving-all-codegen.rs:49]: The first sentence is misleading. It would be better to say something like "It is more efficient to compare scalar types before non-scalar types." Likewise for the similar comments below.

File: tests/ui/deriving/deriving-all-codegen.stdout [hunk 2]
```diff
@@ -126,7 +126,7 @@ impl ::core::marker::StructuralPartialEq for Point { }
 impl ::core::cmp::PartialEq for Point {
     #[inline]
     fn eq(&self, other: &Point) -> bool {
-        self.x == other.x && self.y == other.y
+        self.y == other.y && self.x == other.x
```
Comment (nnethercote) [inline tests/ui/deriving/deriving-all-codegen.stdout:129]: It's unfortunate that the order is "scalar fields in reverse order, then non-scalar fields in reverse order". Is it possible to do things in non-reverse order?

File: tests/ui/deriving/deriving-all-codegen.stdout [hunk 3]
```diff
@@ -419,6 +419,100 @@ impl ::core::cmp::Ord for Big {
...
+#[automatically_derived]
+impl ::core::marker::StructuralPartialEq for Reorder { }
+#[automatically_derived]
+impl ::core::cmp::PartialEq for Reorder {
+    #[inline]
+    fn eq(&self, other: &Reorder) -> bool {
+        self.b2 == other.b2 && self.b4 == other.b4 && self.b5 == other.b5 &&
+                            self.b6 == other.b6 && self.b7 == other.b7 &&
+                    self.b8 == other.b8 && self.b10 == other.b10 &&
+            (self.b1 == other.b1 && self.b3 == other.b3 && self._b == other._b
```
Comment (nnethercote) [inline tests/ui/deriving/deriving-all-codegen.stdout:445]: Can these parentheses be avoided? They're not necessary.

Comment (Sol-Ell) [reply tests/ui/deriving/deriving-all-codegen.stdout:445]: Parentheses are generated because the comparison expressions for scalar and compound fields are grouped and then combined in a single pass. As far as I understand, removing these parentheses would require iterating over the fields twice: once to collect all scalar-typed fields, and a second time to add the comparisons for compound-typed fields. Would making two passes over the fields be acceptable for this purpose?

Comment (nnethercote) [reply tests/ui/deriving/deriving-all-codegen.stdout]: Two passes sounds fine, the number of fields is always small so the performance effect should be negligible.

File: compiler/rustc_ast/src/ast.rs [hunk 4]
```diff
@@ -2452,6 +2544,21 @@ impl TyKind {
             None
         }
     }
+
+    pub fn is_scalar(&self) -> bool {
```
Comment (workingjubilee) [inline compiler/rustc_ast/src/ast.rs:2548]: My understanding of the compiler, and Rust, is that this does not actually answer if the type `is_scalar`. These symbol names can be shadowed, so it only answers if the code uses the *name* of these scalars. The function is more like `maybe_scalar`.

Mind, I don't think this invalidates the heuristic, as anyone who renames a complex type to `u8`, uses it as a field in a struct, and then derives PartialEq is pretty much asking for what they get next. I just think this function shouldn't assert with confidence something it cannot actually answer.

Comment (nnethercote) [reply compiler/rustc_ast/src/ast.rs:2548]: Yeah, that's unavoidable this early before name resolution and type checking is done, but as you say, it'll work out in the end anyway.

Comment (Sol-Ell) [reply compiler/rustc_ast/src/ast.rs:2548]: Right now, implementation doesn’t reorder fields in cases like the one below. Should we keep this behavior (where type aliases like ty::i32 aren’t treated as scalar, so the fields aren’t reordered) as a small quirk, or should we fix it?
```rust
mod ty {
    pub type i32 = i32;
}

#[derive(PartialEq)]
struct Struct {
    field_1: &'static str,
    field_2: ty::i32,
}
```
Currently, this expands to:
```rust
impl ::core::cmp::PartialEq for Struct {
    #[inline]
    fn eq(&self, other: &Struct) -> bool {
        self.field_1 == other.field_1 && self.field_2 == other.field_2
    }
}
```

File: compiler/rustc_ast/src/ast.rs [hunk 5]
```diff
@@ -2452,6 +2452,32 @@ impl TyKind {
             None
         }
     }
+
+    pub fn maybe_scalar(&self) -> bool {
+        let Some(ty_kind) = self.is_simple_path() else {
```
Comment (nnethercote) [inline compiler/rustc_ast/src/ast.rs]: `ty_sym` would be a better name than `ty_kind`. I was momentarily confused because I thought this would have `TyKind`.

File: compiler/rustc_ast/src/ast.rs [hunk 6]
```diff
@@ -2452,6 +2452,32 @@ impl TyKind {
             None
         }
     }
+
+    pub fn maybe_scalar(&self) -> bool {
```
Comment (nnethercote) [inline compiler/rustc_ast/src/ast.rs:2463]: A brief comment explaining the `maybe_` prefix would be good, i.e. that it's not perfectly accurate because of typedefs.

File: tests/ui/deriving/deriving-all-codegen.stdout [hunk 7]
```diff
@@ -419,6 +419,100 @@ impl ::core::cmp::Ord for Big {
...
+                        self.b1 == other.b1 && self.b3 == other.b3 &&
+                self._b == other._b && self.b9 == other.b9
+    }
+}
+#[automatically_derived]
+impl ::core::cmp::PartialOrd for Reorder {
+    #[inline]
+    fn partial_cmp(&self, other: &Reorder)
+        -> ::core::option::Option<::core::cmp::Ordering> {
+        match ::core::cmp::PartialOrd::partial_cmp(&self.b1, &other.b1) {
```
Comment (nnethercote) [inline tests/ui/deriving/deriving-all-codegen.stdout:454]: Scalars are being checked first for `eq`. But `partial_cmp` is still using the old field ordering. Is this intentional?

Comment (nnethercote) [reply tests/ui/deriving/deriving-all-codegen.stdout:454]: And likewise for the enum case below.

File: compiler/rustc_builtin_macros/src/deriving/cmp/partial_eq.rs [hunk 8]
```diff
@@ -113,3 +60,142 @@ pub(crate) fn expand_deriving_partial_eq(
     };
     trait_def.expand(cx, mitem, item, push)
 }
+
+/// Generates the equality expression for a struct or enum variant when deriving `PartialEq`.
+///
+/// This function generates an expression that checks if all fields of a struct or enum variant are equal.
```
Comment (nnethercote) [inline compiler/rustc_builtin_macros/src/deriving/cmp/partial_eq.rs]: A few lines exceed 100 chars, please reflow the comments.

**Review by nnethercote — COMMENTED** [review]
Looking good, just a few nits to fix. Thanks.

@rustbot author

File: tests/ui/deriving/deriving-all-codegen.stdout (hunk 7 above)
Comment (Sol-Ell) [reply tests/ui/deriving/deriving-all-codegen.stdout:454]: Optimizing `partial_cmp` while keeping its [guarantees](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#derivable) would require a separate issue. This PR focuses on the `PartialEq::eq`.

**Comment by nnethercote** [comment]
Thank you!

@bors r+
