### PR TITLE
Preserve substitutions when making trait obligations for suggestions

### LINKED ISSUE #71394: Compiler suggestions send me into an endless loop
I tried this code:

```rust
fn main() {
    let data: &[u8] = &[0; 10][..];
    let points: &[i8] = data.into();
}
```

which outputs 

```
error[E0277]: the trait bound `&[i8]: std::convert::From<&[u8]>` is not satisfied
 --> src/main.rs:3:25
  |
3 |     let points: &[i8] = data.into();
  |                         ^^^^^^^^^^^^^^^ the trait `std::convert::From<&[u8]>` is not implemented for `&[i8]`
  |
  = note: `std::convert::From<&[u8]>` is implemented for `&mut [i8]`, but not for `&[i8]`
  = note: required because of the requirements on the impl of `std::convert::Into<&[i8]>` for `&[u8]`
  = note: required by `std::convert::Into::into`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Note the suggestion
```
  = note: `std::convert::From<&[u8]>` is implemented for `&mut [i8]`, but not for `&[i8]`
```

Changing the type of `points` to `&mut [i8]` will simply swap the suggestion to say `From<&[u8]>` is not implemented for `&mut [i8]`, but it is implemented for `&[i8]`, ultimately making me chase my own tail. I have scoured the docs and came to the conclusion that `From<&[u8]>` is not implemented for either of those types, so why does the compiler suggest it is?

This behaviour occurs across stable, beta and nightly on 1.42.

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #71394.

I *think* `map_bound_ref` is correct here. In any case, I think a lot of the diagnostic code is using `skip_binder` more aggressively than it should be, so I doubt that this is worse than the status quo. The assertion that `new_self_ty` has no escaping bound vars should be enough.

r? @estebank 

cc @nikomatsakis Is the call to `skip_binder` on line 551 (and elsewhere in this file) appropriate? https://github.com/rust-lang/rust/blob/46ec74e60f238f694b46c976d6217e7cf8d4cf1a/src/librustc_trait_selection/traits/error_reporting/suggestions.rs#L537-L565

### CODE REVIEW

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -621,17 +619,16 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                    suggested_ty = inner_ty;
 
-                    let new_obligation = self.mk_obligation_for_def_id(
-                        trait_ref.def_id,
-                        trait_type,
-                        ObligationCause::dummy(),
+                    let new_obligation = self.mk_trait_obligation_with_new_self_ty(
                         obligation.param_env,
+                        trait_ref,
+                        suggested_ty,
```
Comment (estebank) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:631]: ignoring the previous obligation entirely? We used to use the same cause, right?

Is this what causes the "note: `std::convert::From<std::string::String>` is implemented for `&mut str`, but not for `&str`" to go away?

**Review by estebank — APPROVED** [review]
The code changes themselves look ok, but I am hesitant to erasing the original cause.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:631]: No. That comes from propagating substitutions correctly. `From<String>` is not implemented for any of `&mut str` or `&str`.

The cause for the existing obligation is where it originates in the source code. There is no underlying cause for the new obligation we create, since we're just trying various "self" types for diagnostic hints. From this POV, obligations that are only used speculatively should have no cause code.

**Comment by nikomatsakis** [comment]
@ecstatic-morse in answer to your question, I think this call to `skip_binder` looks wrong:

https://github.com/rust-lang/rust/blob/46ec74e60f238f694b46c976d6217e7cf8d4cf1a/src/librustc_trait_selection/traits/error_reporting/suggestions.rs#L551

really, the only *correct* way to use `skip_binder` is if you are going to be comparing or extracting some information that can't involve any bound regions/types/things. This code seems to go on to construct obligations and try to prove them:

**Comment by nikomatsakis** [comment]
Should I review this PR?

**Comment by ecstatic-morse** [comment]
@nikomatsakis That would be great! I considered implementing a `TypeFolder` for changing the self type in a trait predicate, but I'm not sure if that is the idiomatic approach. It seems maybe like overkill? I was trying to follow the approach used in this module, but I think it's also not quite right. Any tips would be much appreciated. I'm not familiar with the trait solver, although I'm trying to learn for rust-lang/rfcs#2632.

**Comment by estebank** [comment]
R? @nikomatsakis

**Comment by ecstatic-morse** [comment]
ping @nikomatsakis

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -1342,16 +1341,24 @@ impl<'a, 'tcx> InferCtxtPrivExt<'tcx> for InferCtxt<'a, 'tcx> {
...
-        output_ty: Ty<'tcx>,
-        cause: ObligationCause<'tcx>,
         param_env: ty::ParamEnv<'tcx>,
+        trait_ref: &ty::PolyTraitRef<'tcx>,
+        new_self_ty: Ty<'tcx>,
     ) -> PredicateObligation<'tcx> {
-        let new_trait_ref =
-            ty::TraitRef { def_id, substs: self.tcx.mk_substs_trait(output_ty, &[]) };
-        Obligation::new(cause, param_env, new_trait_ref.without_const().to_predicate())
+        assert!(!new_self_ty.has_escaping_bound_vars());
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs:1350]: I think we should comment this function and clarify that `new_self_ty` cannot have escaping bound variables

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -511,14 +511,13 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
         let msg = format!("use parentheses to call the {}", callable);
 
-        let obligation = self.mk_obligation_for_def_id(
-            trait_ref.def_id(),
-            output_ty.skip_binder(),
-            obligation.cause.clone(),
+        let new_obligation = self.mk_trait_obligation_with_new_self_ty(
             obligation.param_env,
+            trait_ref,
+            output_ty.skip_binder(),
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:517]: Is there a reason that we think `output_ty` cannot reference bound variables? (The assertion suggests we do, but I don't immediately see it.)

I'd prefer to see `output_ty.no_bound_vars().unwrap()` if we believe this to be true ([`no_bound_vars`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Binder.html#method.no_bound_vars) docs)

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -671,17 +669,16 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                 return;
             }
 
-            let mut trait_type = trait_ref.self_ty();
+            let mut suggested_ty = trait_ref.self_ty();
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:672]: I'm a bit confused how the types work out here. This is a `Binders<Ty>`, right?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 5]
```diff
@@ -671,17 +669,16 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
 
             for refs_remaining in 0..refs_number {
-                if let ty::Ref(_, t_type, _) = trait_type.kind {
-                    trait_type = t_type;
+                if let ty::Ref(_, inner_ty, _) = suggested_ty.kind {
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:675]: ...but I must be wrong, because how do we access the `suggested_ty.kind` then?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 6]
```diff
@@ -748,20 +745,20 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
                 };
 
-                let new_obligation = self.mk_obligation_for_def_id(
-                    trait_ref.skip_binder().def_id,
-                    trait_type,
-                    ObligationCause::dummy(),
+                let new_obligation = self.mk_trait_obligation_with_new_self_ty(
                     obligation.param_env,
+                    &trait_ref,
+                    suggested_ty,
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:756]: as above I don't 100% understand where this type is coming from or how we can be sure that it has no bound references in it -- doesn't it come from the `trait_ref`?

**Comment by nikomatsakis** [comment]
@ecstatic-morse left some questions!

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:517]: I think a function return type can indeed have late bound variables. Perhaps we should just bail out if it does? Alternatively, is there a way to preserve binding levels within `mk_trait_obligation_with_new_self_ty`?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:672]: It's a plain `Ty` if that helps.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 6 above)
Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:756]: `PolyTraitRef::self_ty` is equivalent to `self.skip_binder().substs.type_at(0)`. It seems we are assuming that the self type has no escaping bound variables. Is this assumption correct?

Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:756]: One other thing that I found confusing: According to the [docs for `TraitRef`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TraitRef.html),

> [it] introduces a level of region binding, to account for higher-ranked trait bounds like `T: for<'a> Foo<&'a U>` or higher-ranked object types.

If that's true, why do we use `PolyTraitRef` in so many places? Is it just for higher-ranked self types? If so, why is `PolyTraitRef::self_ty`, which calls `skip_binder`, correct?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (nikomatsakis) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:688]: Yes, I noticed that recently. Hiding the `skip_binder` call like that is...just so wrong. But it explains how this code *type-checks*, anyway.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 6 above)
Comment (nikomatsakis) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:772]: These docs are wrong. Binders are always represented explicitly by a `Binder` -- so `TraitRef` alone cannot account for `for<'a>`, only a `PolyTraitRef` can.

Comment (nikomatsakis) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:772]: > Is this assumption correct?

I think this is sort of what I was asking. I doubt it's correct. I think a reasonable thing to do might be to *test* the assumption by using `no_bound_vars` instead of relying on `skip_binder` (and, if the assumption is false, not generating the suggestions).

**Review by nikomatsakis — APPROVED** [review]

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 6 above)
Comment (ecstatic-morse) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:772]: It seems like we want to change `PolyTraitRef::self_ty` to return a `Binder<Ty>`. Is this correct? This will have a significant amount of fallout I think. Do you want me to open an issue to track this? I could check the result of `self_ty` for `no_bound_vars` in this PR, but we need to be doing this across all diagnostics code, not just here.

**Comment by nikomatsakis** [comment]
OK, so, I think these changes are definitely going in the right direction. I'd probably be happy to merge as-is, seems like an improvement, though I suspect we could do a bit more refactoring to avoid some potential ICEs with higher-ranked regions down the line (along the lines of using `no_bound_vars` more often).

**Comment by ecstatic-morse** [comment]
Rebased to fix merge conflict. Can I r+ this? The original intent was to fix a [rather embarrassing diagnostics bug](https://github.com/rust-lang/rust/issues/71394). I will open an issue for removing `self_ty` and replacing it with `no_bound_vars`, as well as one for auditing uses of `skip_binder` in the diagnostics code more generally.
