### PR TITLE
parser: recover on `...` as a pattern, suggesting `..`

### LINKED ISSUE #70388: diagnostic could be better whe using "..." instead of ".." when destructuring enum
````rust
enum MyEnum {
    A(i32),
    B(u32),
}

fn use_enum(e: MyEnum) {
    if let MyEnum::A(...) = e {
        println!("got enum")
    };
}
````
The problem here is that we have `if let MyEnum::A(...) = e` instead of `if let MyEnum::A(..) = e`

The compiler however points towards `)` in the error message instead of the superfluous `.`:
```
 error: unexpected token: `)`
 --> src/main.rs:7:25
  |
7 |     if let MyEnum::A(...) = e {
  |                         ^

error: aborting due to previous error
```

Fun fact: when using four dots ` MyEnum::A(....)`, it correctly points at the last dot :)
```
error: unexpected token: `.`
 --> src/main.rs:7:25
  |
7 |     if let MyEnum::A(....) = e {
  |                         ^

error: aborting due to previous error
```

This issue has been assigned to @rakshith-ravi via [this comment](https://github.com/rust-lang/rust/issues/70388#issuecomment-603783627).

### PR DESCRIPTION
**Pull request by rakshith-ravi**
Fixes #70388 

My first PR to rust. So please let me know if I'm doing something wrong.

### CODE REVIEW

File: src/librustc_parse/parser/pat.rs [hunk 1]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
             // A rest pattern `..`.
             self.bump(); // `..`
             PatKind::Rest
+        } else if self.check(&token::DotDotDot) && !self.is_pat_range_end_start(1) {
+            // A rest pattern `...`.
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
            // A typoed rest pattern `...`.
```

File: src/librustc_parse/parser/pat.rs [hunk 2]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
...
+            self.bump(); // `...`
+
+            // A ... is not expected here
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
            // The user probably mistook `...` for a rest pattern `..`.
```

File: src/librustc_parse/parser/pat.rs [hunk 3]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
...
+            self.struct_span_err(lo, "unexpected `...`")
+                .span_label(lo, "not expected here")
+                .span_suggestion(
+                    self.token.span,
+                    "Did you mean to use one fewer `.`?",
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
                    "for a rest pattern, use `..` instead of `...`",
```
(Our style is to always start lowercase and avoid posing questions.)

File: src/librustc_parse/parser/pat.rs [hunk 4]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
...
             PatKind::Rest
+        } else if self.check(&token::DotDotDot) && !self.is_pat_range_end_start(1) {
+            // A rest pattern `...`.
+            self.bump(); // `...`
+
+            // A ... is not expected here
+            self.struct_span_err(lo, "unexpected `...`")
+                .span_label(lo, "not expected here")
+                .span_suggestion(
+                    self.token.span,
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
                    lo,
```
You have already advanced the cursor, so in e.g. `... |` we would have `self.token.span` pointing at `|` and not `...`.
(For the previous span you can also use `self.prev_token.span`, but `lo` is equivalent here.)

File: src/librustc_parse/parser/pat.rs [hunk 5]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
             // A rest pattern `..`.
             self.bump(); // `..`
             PatKind::Rest
+        } else if self.check(&token::DotDotDot) && !self.is_pat_range_end_start(1) {
+            // A rest pattern `...`.
+            self.bump(); // `...`
+
+            // A ... is not expected here
+            self.struct_span_err(lo, "unexpected `...`")
+                .span_label(lo, "not expected here")
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
                .span_label(lo, "not a valid pattern")
```

File: src/librustc_parse/parser/pat.rs [hunk 6]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
...
+                .span_suggestion(
+                    self.token.span,
+                    "Did you mean to use one fewer `.`?",
+                    "..".to_owned(),
+                    Applicability::MachineApplicable,
+                )
+                .emit();
+            PatKind::Rest
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]: Let's move this into a new method `fn recover_dotdotdot_rest_pat(&mut self) -> PatKind { ... }`

File: src/librustc_parse/parser/pat.rs [hunk 7]
```diff
@@ -295,6 +295,21 @@ impl<'a> Parser<'a> {
...
             self.bump(); // `..`
             PatKind::Rest
+        } else if self.check(&token::DotDotDot) && !self.is_pat_range_end_start(1) {
+            // A rest pattern `...`.
+            self.bump(); // `...`
+
+            // A ... is not expected here
+            self.struct_span_err(lo, "unexpected `...`")
+                .span_label(lo, "not expected here")
+                .span_suggestion(
```
Comment (Centril) [inline src/librustc_parse/parser/pat.rs]:
```suggestion
                .span_suggestion_short(
```
(This should make the diagnostic avoid showing the *": `...`"* bit, which is redundant with the tweaked message.)

**Review by Centril — COMMENTED** [review]
Looks promising. I've left some bits to tweak for now.

Please also add a test in `src/test/ui/parser/issue-70388-recover-dotdotdot-rest-pat.rs` which would include the typo in e.g. `TupleStruct(...)` and a slice pattern `[x, ..., y]`. Also make sure to add something like `let _recovery_witness: () = 0; //~ ERROR mismatched types`, which we use to check that we can reach the type checking phase of the compiler (so we show there is parser recovery).

File: src/librustc_parse/parser/pat.rs (hunk 4 above)
Comment (rakshith-ravi) [reply src/librustc_parse/parser/pat.rs]: Got it. Thanks

**Comment by rakshith-ravi** [comment]
@Centril added your suggestions. Squashed them all to a single commit as well.

Pliss review.

**Comment by Centril** [comment]
Thanks. This looks fabulous! 💖 

@bors r+

**Comment by rakshith-ravi** [comment]
Yay! Thanks a ton!
