### PR TITLE
Don't print newlines in APITs

### LINKED ISSUE #207: Could not parse `event_id`. Found ASCII control character in <text>
I am not sure whether this is a rustc bug or a measureme bug so I'm reporting it here under the theory that it's more likely to be seen by the right people :)

I ran
```
x clean rustc_middle && MAGIC_EXTRA_RUSTFLAGS='-Zself-profile -Zself-profile-events=default,query-keys' x check --stage 0 rustc_middle
```
on https://github.com/rust-lang/rust/commit/ba6f5e3b4d60ea5a847cd4402cca594cd40b218f. That generated a .mm_profdata file that the measureme tools fail to parse:
```
; crox rustc_middle-2790234.mm_profdata
Could not parse `event_id`. Found ASCII control character in <text> at 112 in "erase_regions_ty^^impl for<'a, 'b> FnOnce(&'b mut DiagnosticBuilder<'a, ()>)
-> &'b mut DiagnosticBuilder<'a, ()>"
```
It looks like `FnOnce` impls are getting an extra newline generated at the end. That seems like a bug we should fix in rustc, but not such a bad bug that it should prevent measureme from generating a report - could we translated it to an ASCII space instead, maybe?

### PR DESCRIPTION
**Pull request by compiler-errors**
This is kind of a hack, but it gets the job done because the only "special" formatting that (afaict) `rustc_ast_pretty` does is break with newlines sometimes.

Fixes rust-lang/measureme#207

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -1425,7 +1425,16 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                             DefPathData::ImplTrait,
                             span,
                         );
-                        let ident = Ident::from_str_and_span(&pprust::ty_to_string(t), span);
+
+                        // HACK: pprust breaks strigns with newlines when the type
```
Comment (jyn514) [inline compiler/rustc_ast_lowering/src/lib.rs:1429]:
```suggestion
                        // HACK: pprust breaks strings with newlines when the type
```

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 2]
```diff
@@ -1425,7 +1425,16 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                        // gets too long. We don't want these to show up in compiler
+                        // output or built artifacts, so replace them here...
+                        // Perhaps we should instead format APITs more robustly.
```
Comment (jyn514) [inline compiler/rustc_ast_lowering/src/lib.rs:1432]: Can we change this in pprust instead? I don't know why we'd want it to add the newline ... if it's just for -Zunpretty=expanded that doesn't seem worth adding hacks for.

Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/lib.rs:1432]: This newline is not `impl Trait` specifically. This is just the regular line breaking that pprust does for code that is too long:

https://github.com/rust-lang/rust/blob/096309e6dc4378e175e524e963332d1a3830ed63/compiler/rustc_ast_pretty/src/pp.rs#L417-L435

I don't think we should remove pprust's ability to break lines, and I don't think it's worth it to introduce extra configurables (like breaking only with spaces). I'd rather have the hack be as localized as possible, or else rewrite this formatting code to no longer rely on pprust at all.

**Review by wesleywiser — APPROVED** [review]
