### PR TITLE
Fix the documentation for move about Fn traits implementations

### LINKED ISSUE #74997: Misdocumented `move` keyword: `move` closures are *not* “represented by the FnOnce trait”
https://doc.rust-lang.org/std/keyword.move.html states:

> `move` converts any variables captured by reference or mutable reference to owned by value variables. The three [`Fn` trait](https://doc.rust-lang.org/std/ops/trait.Fn.html)'s mirror the ways to capture variables, when `move` is used, the closures _[sic]_ is represented by the `FnOnce` trait.

The second half of the second sentence is plain wrong and [causes confusion](https://users.rust-lang.org/t/move-and-impl-fn/46660).

@rustbot modify labels: T-doc, T-libs, C-enhancement. (Is tagging T-doc [still reasonable](https://blog.rust-lang.org/inside-rust/2020/03/27/goodbye-docs-team.html)?)

This issue has been assigned to @poliorcetics via [this comment](https://github.com/rust-lang/rust/issues/74997#issuecomment-668798798).

### PR DESCRIPTION
**Pull request by poliorcetics**
Fixes #74997.

This uses the note from the [reference](https://doc.rust-lang.org/reference/types/closure.html#call-traits-and-coercions) but I can also just put a link to it or do both.

@rusbot modify labels: C-bug T-doc T-libs

### CODE REVIEW

**Comment by poliorcetics** [comment]
@rusbot modify labels: C-bug, T-doc, T-libs

File: library/std/src/keyword_docs.rs [hunk 1]
```diff
@@ -943,8 +943,12 @@ mod mod_keyword {}
 /// Capture a [closure]'s environment by value.
 ///
 /// `move` converts any variables captured by reference or mutable reference
-/// to owned by value variables. The three [`Fn` trait]'s mirror the ways to capture
-/// variables, when `move` is used, the closures is represented by the `FnOnce` trait.
+/// to owned by value variables.
+///
+/// Note: `move` closures may still implement [`Fn`] or [`FnMut`], even though
+/// they capture variables by move. This is because the traits implemented by a
```
Comment (JohnTitor) [inline library/std/src/keyword_docs.rs:949]:
```suggestion
/// they capture variables by `move`. This is because the traits implemented by a
```

Comment (poliorcetics) [reply library/std/src/keyword_docs.rs]: Thanks, done !

**Comment by jyn514** [comment]
Maybe also add the example from the forum? https://users.rust-lang.org/t/move-and-impl-fn/46660/2

Until I read that I didn't realize what this was trying to say.

**Comment by poliorcetics** [comment]
@jyn514 Done, is it clearer this way ?

**Comment by jyn514** [comment]
Yeah, that helps :) I was thinking about it as 'if it's _captured_ by value you can only use it once' but of course if you only _use_ the reference, the value isn't dropped in the closure body.

@bors r+ rollup
