### PR TITLE
Suggest `.iter()` for shared projections

### LINKED ISSUE #155365: E0599 suggests "call `.into_iter()` first" on non-mutable reference
### Code

```Rust
struct Demo {
    contents: Vec<u32>,
}

impl Demo {
    fn new() -> Self {
        Demo { contents: vec![ 1, 2, 3 ] }
    }
    
    fn count_odds(&self) -> usize {
        self.contents.filter(|v| *v % 2 == 1).count()
    }
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `filter` found for struct `Vec<u32>` in the current scope
  --> src/lib.rs:11:23
   |
11 |         self.contents.filter(|v| *v % 2 == 1).count()
   |                       ^^^^^^ `Vec<u32>` is not an iterator
   |
help: call `.into_iter()` first
   |
11 |         self.contents.into_iter().filter(|v| *v % 2 == 1).count()
   |                       ++++++++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `filter` found for struct `Vec<u32>` in the current scope
  --> src/lib.rs:11:23
   |
11 |         self.contents.filter(|v| *v % 2 == 1).count()
   |                       ^^^^^^ `Vec<u32>` is not an iterator
   |
help: call `.iter()` first
   |
11 |         self.contents.iter().filter(|v| *v % 2 == 1).count()
   |                       +++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Rationale and extra context

If `into_iter()` is added, there is a new error:

```
   Compiling playground v0.0.1 (/playground)
error[E0507]: cannot move out of `self.contents` which is behind a shared reference
   --> src/lib.rs:11:9
    |
 11 |         self.contents.into_iter().filter(|v| *v % 2 == 1).count()
    |         ^^^^^^^^^^^^^ ----------- `self.contents` moved due to this method call
    |         |
    |         move occurs because `self.contents` has type `Vec<u32>`, which does not implement the `Copy` trait
    |
note: `into_iter` takes ownership of the receiver `self`, which moves `self.contents`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:310:18
    |
310 |     fn into_iter(self) -> Self::IntoIter;
    |                  ^^^^
help: you can `clone` the value and consume it, but this might not be your desired behavior
    |
 11 |         <Vec<u32> as Clone>::clone(&self.contents).into_iter().filter(|v| *v % 2 == 1).count()
    |         ++++++++++++++++++++++++++++             +
help: consider cloning the value if the performance cost is acceptable
    |
 11 |         self.contents.clone().into_iter().filter(|v| *v % 2 == 1).count()
    |                      ++++++++

For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Other cases

For a non-method where the vector is a function parameter, `.into_iter()` works fine though, so the suggestion on

```Rust
fn count_odds(contents: &Vec<u32>) -> usize {
    contents.filter(|v| *v % 2 == 1).count()
}
```

is fine

### Rust Version

```Shell
1.94.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by qaijuang**
Fixes rust-lang/rust#155365.

### CODE REVIEW

**Comment by qaijuang** [comment]
cc @DanielEScherzer

File: tests/ui/did_you_mean/collect-without-into-iter-call.rs
Comment (DanielEScherzer) [inline tests/ui/did_you_mean/collect-without-into-iter-call.rs]: the test now does more than that

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -189,6 +190,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        for pointer_ty in place_with_id.place.deref_tys() {
+            match self.structurally_resolve_type(rcvr_expr.span, pointer_ty).kind() {
+                ty::Ref(.., Mutability::Not) => {
+                    projection_mutability = Some(Mutability::Not);
+                    break;
+                }
+                ty::Ref(.., Mutability::Mut) => {
+                    projection_mutability.get_or_insert(Mutability::Mut);
+                }
+                ty::Adt(def, ..) if def.is_box() => {}
```
Comment (DanielEScherzer) [inline compiler/rustc_hir_typeck/src/method/suggest.rs]: is this line needed? The default behavior is `{}` (from the `_` wildcard) unless the type matches, so removing this should leave behavior unchanged

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 2]
```diff
@@ -189,6 +190,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                None,
+            )
+            .is_ok()
+        };
+
+        match projection_mutability {
+            Mutability::Not => has_method(sym::iter).then_some(sym::iter),
+            Mutability::Mut => {
+                if has_method(sym::iter_mut) {
+                    Some(sym::iter_mut)
```
Comment (DanielEScherzer) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:247]: if I'm understanding correctly, this means that sometimes the suggestion is going to be to use iter_mut() - can I suggest adding a test case for that?

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 3]
```diff
@@ -189,6 +190,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         false
     }
 
+    fn preferred_iterator_method(
+        &self,
+        source: SelfSource<'tcx>,
+        rcvr_ty: Ty<'tcx>,
+    ) -> Option<Symbol> {
```
Comment (DanielEScherzer) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:199]: should this document what possible symbols are returned? Not sure what the compiler conventions are in terms of documentation

File: tests/ui/did_you_mean/collect-without-into-iter-call.rs [hunk 4]
```diff
@@ -17,3 +17,25 @@ fn process(items: impl IntoIterator<Item = String>) -> Vec<String> {
...
+
+// Regression test for https://github.com/rust-lang/rust/issues/155365
+struct Demo {
+    contents: Vec<u32>,
+}
+
+impl Demo {
+    fn count_odds(&self) -> usize {
+        self.contents.filter(|v| *v % 2 == 1).count()
+        //~^ ERROR no method named `filter` found for struct `Vec<u32>` in the current scope
```
Comment (DanielEScherzer) [inline tests/ui/did_you_mean/collect-without-into-iter-call.rs:32]: is it possible to also add the suggestion as part of the test here, rather than just the expected stderr?

```suggestion
        //~^ ERROR no method named `filter` found for struct `Vec<u32>` in the current scope
        //~| HELP: call `.iter()` first
```

same with the others

**Review by DanielEScherzer — COMMENTED** [review]
thanks for working on this - I'm not going to pretend to understand how it all works, but some suggestions/notes

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155719/d493b7c5ac637ed7edf626128b9f14796a2dad20..3fb726710fa3cb50b176ef3e2ed3476a8760ac23)*

File: tests/ui/did_you_mean/collect-without-into-iter-call.rs
Comment (qaijuang) [reply tests/ui/did_you_mean/collect-without-into-iter-call.rs]: Good catch

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 2 above)
Comment (qaijuang) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:247]: good idea.

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 5]
```diff
@@ -146,6 +146,18 @@ impl<'tcx, D: Delegate<'tcx>> Delegate<'tcx> for &mut D {
     }
 }
 
+impl<'tcx> Delegate<'tcx> for () {
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs]: Could you implement this to a new unit struct with the proper name instead of a mere unit type?

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 6]
```diff
@@ -1855,3 +1867,10 @@ impl<'tcx, Cx: TypeInformationCtxt<'tcx>, D: Delegate<'tcx>> ExprUseVisitor<'tcx
         }
     }
 }
+
+pub(crate) fn expr_place<'tcx>(
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs:1876]: I think it might be a bit inappropriate/misleading to expose this API, but I don’t see a simple alternative. Could you add a comment addressing that this should be used for diagnostics purpose only?

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs [hunk 7]
```diff
@@ -2,7 +2,7 @@
 //! normal visitor, which just walks the entire body in one shot, the
 //! `ExprUseVisitor` determines how expressions are being used.
 //!
-//! In the compiler, this is only used for upvar inference, but there
+//! In the compiler, this is primarily used for upvar inference, but there
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_typeck/src/expr_use_visitor.rs]: And also here something like "only used for upvar inference and diagnostics"

**Review by ShoyuVanilla — COMMENTED** [review]
Looks good to me modulo some nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155719/d493b7c5ac637ed7edf626128b9f14796a2dad20..4be9ca8be6fcd8222ae726aa0ef365efa8d4a0f5)*

File: compiler/rustc_hir_typeck/src/expr_use_visitor.rs (hunk 5 above)
Comment (qaijuang) [reply compiler/rustc_hir_typeck/src/expr_use_visitor.rs]: I see.

**Review by DanielEScherzer — APPROVED** [review]
I don't have r+ but this looks good to me now in terms of the results

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155719/c7fe5e9d1eb0ef8cc033961956d60f8e2e91e741..28c079ae40dbac7ab4a88ef7fe766bd9339e6857)*
