### PR TITLE
Limit read size in `File::read_to_end` loop

### LINKED ISSUE #110650: `File::read_to_end`'s unexpected performance on Windows
I came across an unexpected performance degradation on Windows when using [`File::read_to_end(&mut self, buf: &mut Vec<u8>)`](https://doc.rust-lang.org/std/fs/struct.File.html#method.read_to_end): the larger the passed in `buf` `Vec`'s capacity, the longer the call takes—regardless of actually read bytes.

```rust
let mut buffer = Vec::with_capacity(BUFFER_SIZE);
let mut file = File::open("some_1kb_file.txt").expect("opening file");

let metadata = file.metadata().expect("reading metadata");
let len = metadata.len();
assert!(len == 1024);

file.read_to_end(&mut buffer).expect("reading file");
```

With the above code, increasing `BUFFER_SIZE` will linearly increase the runtime of `read_to_end`, even if we're always reading `1024` bytes.

This doesn't seem to happen on other OSes. At first I assumed I was doing something wrong, but [with help from folks at StackOverflow](https://stackoverflow.com/questions/76055481/why-does-fileread-to-end-get-slower-the-larger-the-buffer-capacity) we realized most of the time is spent in `NtReadFile`. One can get around this by using `file.read_exact(&mut buffer[0..len])` or `file.take(len).read_to_end()` instead.

I don't know what the implication of querying for the file size and using it in `read_to_end` would have, or if it'd be possible to get around this another way, but I assume at the very worst we could have a warning in the documentation about this.

### Meta

```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-pc-windows-msvc
release: 1.68.2
LLVM version: 15.0.6
```

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #110650.

Windows file reads have perf overhead that's proportional to the buffer size. When we have a reasonable expectation that we know the file size, we can set a reasonable upper bound for the size of the buffer in one read call.

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

File: library/std/src/io/mod.rs [hunk 1]
```diff
@@ -357,17 +357,30 @@ where
...
-pub(crate) fn default_read_to_end<R: Read + ?Sized>(r: &mut R, buf: &mut Vec<u8>) -> Result<usize> {
+pub(crate) fn default_read_to_end<R: Read + ?Sized>(
+    r: &mut R,
+    buf: &mut Vec<u8>,
+    size_hint: Option<usize>,
+) -> Result<usize> {
     let start_len = buf.len();
     let start_cap = buf.capacity();
+    // Optionally limit the maximum bytes read on each iteration.
+    // This adds an arbitrary fiddle factor to allow for more data than we expect.
```
Comment (joshtriplett) [inline library/std/src/io/mod.rs:368]: Given the comment immediately above this function, I don't think we want to tack on this fiddle factor, or at least not one this large. If the file appears to be 8 bytes long, we shouldn't be adding 1024 bytes and rounding up to DEFAULT_BUF_SIZE.

**Review by joshtriplett — CHANGES_REQUESTED** [review]
Please don't add this amount of additional space when reading (for instance) an 8 byte file. If we need a bit of slack to make sure we've gotten EOF, that's fine, but let's not add 1024 bytes or more to an 8 byte read.

File: library/std/src/io/mod.rs (hunk 1 above)
Comment (ChrisDenton) [reply library/std/src/io/mod.rs:368]: Fair enough but this does not affect allocation in any way. This only has an effect if we already have a buffer that's way larger than we need. It places an upper limit on the length of the slice passed to the `read_buf` function. I figured if we already have a large buffer, then we may as well use *some* of that space if we need it.

Comment (joshtriplett) [reply library/std/src/io/mod.rs:368]: I see. And the caller can always pass a smaller buffer if it wants to, and `read_to_end` doesn't actually trigger this. OK, fair enough.

**Review by joshtriplett — APPROVED** [review]
