### PR TITLE
Fix line numbers for MIR inlined code

### LINKED ISSUE #103068: MIR inlining causes incorrect line numbers for inlined code
The following program generates a backtrace with incorrect line numbers:

```rust
#[inline(always)]
fn foo() {
    bar();  // line 3
}

#[inline(never)]
fn bar() {
    panic!();  // line 8
}

fn main() {
    foo();  // line 12
}
```

```shell
$ rustc +nightly -g --crate-name mir_inlining -O mir_inlining.rs
$ RUST_BACKTRACE=1 ./mir_inlining
thread 'main' panicked at 'explicit panic', mir_inlining.rs:8:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/6b3ede3f7bc502eba7bbd202b4b9312d812adcd7/library/std/src/panicking.rs:607:12
   1: mir_inlining::bar
             at ./mir_inlining.rs:8:5
   2: mir_inlining::foo
             at ./mir_inlining.rs:12:5
   3: mir_inlining::main
             at ./mir_inlining.rs:12:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/6b3ede3f7bc502eba7bbd202b4b9312d812adcd7/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Notice that frames 2 and 3 both indicate they come from line 12 (frame 2 should be at line 3).

This seems to be a result of MIR inlining because the LLVM IR (pre LLVM optimization) has the same issue:

```llvm
; mir_inlining::main
; Function Attrs: nonlazybind uwtable
define internal void @_ZN12mir_inlining4main17h04ea6567a81cf010E() unnamed_addr #0 !dbg !1610 {
start:
; call mir_inlining::bar
  call void @_ZN12mir_inlining3bar17hfea3a56d969a7806E(), !dbg !1611
  br label %bb1, !dbg !1611

bb1:                                              ; preds = %start
  ret void, !dbg !1614
}

!1611 = !DILocation(line: 12, column: 5, scope: !1612, inlinedAt: !1613)
!1613 = !DILocation(line: 12, column: 5, scope: !1610)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (6b3ede3f7 2022-10-13)
binary: rustc
commit-hash: 6b3ede3f7bc502eba7bbd202b4b9312d812adcd7
commit-date: 2022-10-13
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### PR DESCRIPTION
**Pull request by wesleywiser**
`should_collapse_debuginfo` detects if the specified span is part of a
macro expansion however it does this by checking if the span is anything
other than a normal (non-expanded) kind, then the span sequence is
walked backwards to the root span.

This doesn't work when the MIR inliner inlines code as it creates spans
with expansion information set to `ExprKind::Inlined` and results in the
line number being attributed to the inline callsite rather than the
normal line number of the inlined code.

Fixes #103068

### CODE REVIEW

**Comment by wesleywiser** [comment]
Comparison of panics from the test case before & after this change:

## Before

```shell
> .\mir-inlined-line-numbers.exe
thread 'main' panicked at 'explicit panic', .\src\test\codegen\mir-inlined-line-numbers.rs:8:5
stack backtrace:
   0: std::panicking::begin_panic<str>
             at /rustc/6b3ede3f7bc502eba7bbd202b4b9312d812adcd7\library\std\src\panicking.rs:607
   1: mir_inlined_line_numbers::bar
             at .\src\test\codegen\mir-inlined-line-numbers.rs:8
   2: mir_inlined_line_numbers::foo
             at .\src\test\codegen\mir-inlined-line-numbers.rs:12
   3: mir_inlined_line_numbers::main
             at .\src\test\codegen\mir-inlined-line-numbers.rs:12
   4: core::ops::function::FnOnce::call_once
             at /rustc/6b3ede3f7bc502eba7bbd202b4b9312d812adcd7\library\core\src\ops\function.rs:251
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## After

```shell
> .\mir-inlined-line-numbers.exe
thread 'main' panicked at 'explicit panic', .\src\test\codegen\mir-inlined-line-numbers.rs:8:5
stack backtrace:
   0: std::panicking::begin_panic<str>
             at .\library\std\src\panicking.rs:607
   1: mir_inlined_line_numbers::bar
             at .\src\test\codegen\mir-inlined-line-numbers.rs:8
   2: mir_inlined_line_numbers::foo
             at .\src\test\codegen\mir-inlined-line-numbers.rs:3
   3: mir_inlined_line_numbers::main
             at .\src\test\codegen\mir-inlined-line-numbers.rs:12
   4: core::ops::function::FnOnce::call_once
             at .\library\core\src\ops\function.rs:251
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

File: compiler/rustc_middle/src/ty/mod.rs [hunk 1]
```diff
@@ -2522,7 +2522,9 @@ impl<'tcx> TyCtxt<'tcx> {
             && if self.features().collapse_debuginfo {
                 span.in_macro_expansion_with_collapse_debuginfo()
```
Comment (davidtwco) [inline compiler/rustc_middle/src/ty/mod.rs:2523]: Could you check that the behaviour is correct with `#![feature(collapse_debuginfo)]` enabled?

Comment (wesleywiser) [reply compiler/rustc_middle/src/ty/mod.rs:2523]: Yeah, this already works correctly because `in_macro_expansion_with_collapse_debuginfo` already checks the `kind` field for `ExpnKind::Macro` while MIR inlining generates `ExpnKind::Inlined`

**Review by davidtwco — APPROVED** [review]

**Comment by pnkfelix** [comment]
discussed with Wesley. Unilaterally backport approving to go into 1.65 beta branch (which will be stable next week).

**Comment by wesleywiser** [comment]
@bors p=1

We're backporting this to ride the train alongside the MIR inliner being enabled by default.

**Comment by wesleywiser** [comment]
```
2022-10-28T12:51:18.7606620Z sort: write failed: 'standard output': Broken pipe
2022-10-28T12:51:18.7607419Z 257932	.
2022-10-28T12:51:18.7608062Z sort: write error
```

Seems spurious? 

@bors retry

**Comment by nnethercote** [comment]
These perf regressions look real.

**Comment by wesleywiser** [comment]
I'll spend some time investigating this week.

**Comment by wesleywiser** [comment]
The regressions are real but expected. Both [regex](https://github.com/rust-lang/rustc-perf/blob/8dfb8bf69313b79d1bd579875289969e6f77392c/collector/compile-benchmarks/regex-1.5.5/Cargo.toml#L37) and [webrender](https://github.com/rust-lang/rustc-perf/blob/8dfb8bf69313b79d1bd579875289969e6f77392c/collector/compile-benchmarks/webrender-2022/Cargo.toml#L11) enable debuginfo generation in release mode. Prior to this change, any inlined code was being incorrectly placed at the line number of the calling function which caused a reduction in the amount of debuginfo generated by LLVM (and given to LLVM by rustc). Fixing that bug causes the debuginfo to be generated with the appropriate line numbers and results in more debuginfo. cachegrind results back this up and show the biggest increases in debuginfo related LLVM functions. 

Both of these benchmarks improved considerably when MIR inlining was enabled and even with the regression caused by this fix, we're still showing net wins on these benchmarks. 

I couldn't find any other actionable items that might improve these results at this time.
