### PR TITLE
Make `into` schedule drop for the destination

### LINKED ISSUE #47949: Panics in destructors can cause the return value to be leaked
## STR

```Rust
struct NoisyDrop;
impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("dropping a NoisyDrop");
    }
}

impl NoisyDrop {
    fn new() -> Self {
        println!("creating a NoisyDrop");
        NoisyDrop
    }
}

struct PanickyDrop;
impl Drop for PanickyDrop {
    fn drop(&mut self) {
        panic!()
    }
}

fn foo() -> NoisyDrop {
    let p = PanickyDrop;
    NoisyDrop::new()
}

fn main() {
    foo();
}
```

## Expected Result

"creating a NoisyDrop" and "dropping a NoisyDrop" should appear the same number of times

## Actual Result

```
creating a NoisyDrop
thread 'main' panicked at 'explicit panic', src/main.rs:18:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The destructor is ignored.

### PR DESCRIPTION
**Pull request by matthewjasper**
closes #47949

### CODE REVIEW

File: src/librustc_mir/build/expr/stmt.rs [hunk 1]
```diff
@@ -240,16 +240,13 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                            temp, expr, this.block_context);
                     place
                 };
-                unpack!(block = this.into(&temp, block, expr));
-
-                // Attribute drops of the statement's temps to the
-                // semicolon at the statement's end.
```
Comment (pnkfelix) [inline src/librustc_mir/build/expr/stmt.rs]: wow, if I'm reading al this right, even though you got rid of all that `StatementSpan` stuff, you didn't have to change any of the tests that are testing the attribution of drops of a statement's temps to the semicolon at the statements end, right?

That's great.

**Comment by pnkfelix** [comment]
@matthewjasper the code itself looks fine to me; do you know what is up with the Travis CI failure, though?

**Comment by pnkfelix** [comment]
r=me once travis is happy.

**Comment by matthewjasper** [comment]
I think that the ICE is fixed now. I've had to change how we are checking generators for the transform. This should not affect any generator layout. cc @rust-lang/compiler 

Since this now seems quite a risky PR:
@bors rollup=never

File: src/librustc_mir/dataflow/impls/requires_storage.rs [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+            _ => (),
+        }
+    }
+
+    fn terminator_effect(&self,
+                         sets: &mut BlockSets<'_, Local>,
+                         loc: Location) {
+        match &self.mir[loc.block].terminator().kind {
+            TerminatorKind::DropAndReplace { location: _, .. } => {
+                debug_assert!(false, "Generator transform should be run after drop elaboration");
```
Comment (eddyb) [inline src/librustc_mir/dataflow/impls/requires_storage.rs]: Let's not ever do this in the compiler, if the condition is simple enough we should use `span_bug!`.

File: src/librustc_mir/dataflow/impls/requires_storage.rs [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+            }
+            TerminatorKind::Drop { location, .. } => {
+                if let Place::Base(PlaceBase::Local(l)) = *location {
+                    sets.kill(l);
```
Comment (eddyb) [inline src/librustc_mir/dataflow/impls/requires_storage.rs]: cc @RalfJung I thought you said we shouldn't disallow capture during, and reinitialization after, `Drop`?

File: src/librustc_mir/dataflow/impls/requires_storage.rs [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+///   reference uninitialized variables then that would also `gen` this.
+///   This would also be a problem if we ran the generator transform after
+///   deaggregation.
+/// * And if it hasn't had it's storage killed, or been droped.
+///
+/// Notably we don't assume that moving from a variable is not considered here.
+/// It's possible that something like the following could happen:
+///
+/// let mut x = String::new();
+/// let p = &mut x as *mut String;
```
Comment (eddyb) [inline src/librustc_mir/dataflow/impls/requires_storage.rs]: I prefer "MaybeBorrowed" be part of the analysis, as a lot of locals never are.

File: src/librustc_mir/build/block.rs [hunk 5]
```diff
@@ -30,28 +36,57 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                     let exit_block = this.cfg.start_new_block();
                     let block_exit = this.in_breakable_scope(
                         None, exit_block, destination.clone(), |this| {
-                            this.ast_block_stmts(destination, block, span, stmts, expr,
-                                                 safety_mode)
+                            // We can have multiple assignments to the
+                            // destination, so we cannot schedule drop after
+                            // each assignment. We have to rely on drop
+                            // elaboration for this.
```
Comment (eddyb) [inline src/librustc_mir/build/block.rs]: I see this comment in a few places but I am confused by it, hopefully answering these can help:
* "we can have multiple assignments" where? maybe talk about *what* can contain them?
* "so we cannot" doesn't explain why we're scheduling a drop *here*. maybe saying "so we're doing X instead" would be clearer
* and what's the "this" we rely on drop elaboration for? removing noop drops? making drops conditional? how does it relate to everything above?

File: src/librustc_mir/dataflow/impls/requires_storage.rs [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+/// point.
+///
+/// This is used to limit which locals are kept in the generator state.
+///
+/// Currently a local is consider to possibly require storage if:
+/// * Any part of it has ever been initialized - borrowck should ensure that
+///   this ends up the same as it's ever been used. If we add a way to
+///   reference uninitialized variables then that would also `gen` this.
+///   This would also be a problem if we ran the generator transform after
+///   deaggregation.
```
Comment (Zoxc) [inline src/librustc_mir/dataflow/impls/requires_storage.rs]: MIR certainly has a way to reference uninitialized variables and we do want to run the generator transform after  deaggregation.

File: src/librustc_mir/dataflow/impls/requires_storage.rs (hunk 3 above)
Comment (Zoxc) [reply src/librustc_mir/dataflow/impls/requires_storage.rs]: Yes. Only `StatementKind::StorageDead` should kill storage.

Comment (RalfJung) [reply src/librustc_mir/dataflow/impls/requires_storage.rs]: Agreed with @Zoxc.

File: src/librustc_mir/build/expr/into.rs [hunk 7]
```diff
@@ -2,20 +2,25 @@
...
 use rustc::ty;
 
 use rustc_target::spec::abi::Abi;
 
 impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
-    /// Compile `expr`, storing the result into `destination`, which
-    /// is assumed to be uninitialized.
+    /// Compile `expr`, storing the result into `destination`, which is assumed
+    /// to be uninitialized.
+    /// If a `drop_scop` is provided, `destination` is scheduled to be dropped
```
Comment (tmandry) [inline src/librustc_mir/build/expr/into.rs]: nit sp: `drop_scope`

**Comment by jonas-schievink** [comment]
Triage ping @matthewjasper, a few review comments need to be addressed and merge conflicts need to be fixed

**Comment by matthewjasper** [comment]
This is blocked on #61872 for now

**Comment by pnkfelix** [comment]
I'll be going on leave for two months, so I'm going to reassign this to @matthewjasper so that they know that they need to find a new official reviewer to take point on this.

File: src/test/ui/generator/dont-capture-for-dead-drops.rs [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+            yield;                  // The return place should not be considered live here
+            panic!();
+        } else {
+            let u = Box::new(0);
+            String::new()
+        }
+    };
+}
+
+fn uninitilized_local_is_not_live_across_yield(c: bool) {
```
Comment (lqd) [inline src/test/ui/generator/dont-capture-for-dead-drops.rs]: tiny typo
```suggestion
fn uninitialized_local_is_not_live_across_yield(c: bool) {
```

**Comment by joelpalmer** [comment]
Ping from Triage, hi @matthewjasper - any updates?

**Comment by Dylan-DPC** [comment]
can anyone from @rust-lang/compiler take over this PR? (need a reviewer but not blocked on a review)

**Comment by tmandry** [comment]
It looks like there were still some significant changes planned for this PR; see https://github.com/rust-lang/rust/issues/59123#issuecomment-501460766

**Comment by Dylan-DPC** [comment]
Yes but we still need a reviewer

**Comment by hdhoang** [comment]
Ping from Triage @matthewjasper, any update on this PR?

**Comment by JohnCSimon** [comment]
Ping from triage - @oli-obk  - this hasn't moved since you'd assigned yourself 18 days ago. 
Thanks.

**Comment by matthewjasper** [comment]
Just to provide a quick update. I'm still working on this, and I think I have a way to generate drops on precisely the paths where the value has been initialized. that I'm happy with. It will require some more refactoring of the MIR drop generation code that I'll probably pull out into a separate PR. I'll try to get that PR ready this weekend.

**Comment by JohnCSimon** [comment]
from Triage:
@matthewjasper Thanks for the update!

**Comment by JohnTitor** [comment]
Ping from triage: @matthewjasper any updates on this?

**Comment by matthewjasper** [comment]
Blocked on #64225

File: src/test/ui/async-await/async-fn-size.rs [hunk 9]
```diff
@@ -89,10 +89,10 @@ fn main() {
     assert_eq!(8, std::mem::size_of_val(&await1_level1()));
     assert_eq!(12, std::mem::size_of_val(&await2_level1()));
     assert_eq!(12, std::mem::size_of_val(&await3_level1()));
-    assert_eq!(20, std::mem::size_of_val(&await3_level2()));
-    assert_eq!(28, std::mem::size_of_val(&await3_level3()));
-    assert_eq!(36, std::mem::size_of_val(&await3_level4()));
-    assert_eq!(44, std::mem::size_of_val(&await3_level5()));
+    assert_eq!(24, std::mem::size_of_val(&await3_level2()));
```
Comment (matthewjasper) [inline src/test/ui/async-await/async-fn-size.rs]: cc @tmandry The generator transform is producing fewer `storage_conflicts` which is causing layout to pessimize from: `0: tag, 4: u16, 6: u16, 8: union { Future, Future, Future }`  to `0: tag, 4: u16, 8: union { Future, Future, (u16, Future) }`

**Comment by matthewjasper** [comment]
This is now ready for review.

I've gone back to the original approach here, since making MIR drop generation more complicated wasn't particularly great. There are a couple a changes to the generator transform was being a bit too conservative and storing never initialized locals across yields, which caused problems because such locals are now sometimes drop-live.

File: src/test/ui/generator/size-moved-locals.rs [hunk 10]
```diff
@@ -71,6 +69,6 @@ fn overlap_x_and_y() -> impl Generator<Yield = (), Return = ()>{
 fn main() {
     assert_eq!(1028, std::mem::size_of_val(&move_before_yield()));
     assert_eq!(1032, std::mem::size_of_val(&move_before_yield_with_noop()));
-    assert_eq!(2056, std::mem::size_of_val(&overlap_move_points()));
+    assert_eq!(1032, std::mem::size_of_val(&overlap_move_points()));
```
Comment (matthewjasper) [inline src/test/ui/generator/size-moved-locals.rs]: This should still be 2056 because `second` and `first` cannot overlap (the assignment is a single `llvm.memcpy`). This needs fixing before merging.

**Review by tmandry — CHANGES_REQUESTED** [review]

File: src/librustc_mir/transform/generator.rs [hunk 11]
```diff
@@ -508,10 +508,7 @@ fn locals_live_across_suspend_points(
             storage_liveness_map.insert(block, storage_liveness.clone());
 
             requires_storage_cursor.seek(loc);
-            let mut storage_required = requires_storage_cursor.get().clone();
-
-            // Mark locals without storage statements as always requiring storage
-            storage_required.union(&ignored.0);
```
[the remark this answers is not in the document]
Comment (matthewjasper) [reply src/librustc_mir/transform/generator.rs]: What args? Generators only have the `self` argument, which is special cased anyway.

[the remark this answers is not in the document]
Comment (tmandry) [reply src/librustc_mir/transform/generator.rs]: Oh true, sorry. Maybe I was thinking of upvars but those are also handled separately for now. (I'm working on a change to handle them like other locals, but it's not ready yet.)

File: src/test/ui/async-await/async-fn-size-uninit-locals.rs [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+
+async fn joined() {
+    let joiner;
+    let a = Big::new();
+    let b = Big::new();
+    let c = Big::new();
+
+    fut().await;
+    noop();
+    joiner = Joiner { a: Some(a), b: Some(b), c: Some(c) };
```
Comment (tmandry) [inline src/test/ui/async-await/async-fn-size-uninit-locals.rs]: This test sort of implicitly relies on not having NRVO. If we had it, it could be NRVO keeping the size small instead of "not storing uninitialized locals".

You could add a test that _does_ await after `joiner` is initialized so you can demonstrate that it's big, and shrinks down once the await is removed. But that's just a suggestion; I'm being a bit pedantic here.

**Review by tmandry — APPROVED** [review]
Generator changes LGTM (but see comment)

File: src/librustc_mir/build/mod.rs [hunk 13]
```diff
@@ -687,7 +689,9 @@ fn construct_const<'a, 'tcx>(
     let mut block = START_BLOCK;
     let ast_expr = &tcx.hir().body(body_id).value;
     let expr = builder.hir.mirror(ast_expr);
-    unpack!(block = builder.into_expr(&Place::return_place(), block, expr));
+    // We don't provide a scope because we can't panic in constants, so won't
```
Comment (oli-obk) [inline src/librustc_mir/build/mod.rs]: we can't unwind, though we can in fact panic (but it's always treated as abort-on-panic or in fact error-on-panic)

File: src/librustc_mir/build/expr/into.rs [hunk 14]
```diff
@@ -234,8 +252,8 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
                         is_block_tail: None,
                     });
                     let ptr_temp = Place::from(ptr_temp);
-                    let block = unpack!(this.into(&ptr_temp, block, ptr));
-                    this.into(&ptr_temp.deref(), block, val)
+                    let block = unpack!(this.into(&ptr_temp, None, block, ptr));
```
Comment (oli-obk) [inline src/librustc_mir/build/expr/into.rs]: These "no drop scopes" aren't commented, though they may be obvious enough due to raw pointers not needing drop

**Comment by lqd** [comment]
Seems spurious: a segfault installing awscli:
```
Script contents:
src/ci/install-awscli.sh
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/7e1f4ab8-5218-4d32-8794-b923dc0cf857.sh
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  python-setuptools-doc
The following NEW packages will be installed:
  python3-setuptools
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
E: Method http has died unexpectedly!
E: Sub-process http received a segmentation fault.
E: Method /usr/lib/apt/methods/http did not start correctly
##[error]Bash exited with code '100'.
##[section]Finishing: Install awscli
```

@bors retry

**Comment by nnethercote** [comment]
It appears this change was a [big regression](https://perf.rust-lang.org/compare.html?start=59a31c8c676bdc9f50490d5798b1b4e884b7d7ae&end=d304f5c1ff0b86b07f643e733f9fe2d9cd13753e&stat=instructions:u): up to 36% for many benchmarks, and over 500,000% for `deeply-nested-opt`(!)

This should be backed out, or the regression completely fixed, ASAP.

cc @rust-lang/wg-compiler-performance

**Comment by nnethercote** [comment]
#65249 backs out the part that caused the perf regression.
