### PR TITLE
Do anonymous lifetimes remapping correctly for nested rpits

### LINKED ISSUE #103141: Rust update from 1.63 to 1.64 introduce lifetime problem on build
### Code

This is an attempt to reproduce a minimal example of a regression problem (backwards compatibility not assured) from a closed-source company codebase.

I tried this code: -> https://github.com/Aboussejra/rust_compiler_1.64_update_problem

```rust
pub struct VecNumber<'s> {
    pub vec_number: Vec<Number<'s>>,
    pub auxiliary_object: &'s Vec<usize>,
}

#[derive(Clone)]
pub struct Number<'s> {
    pub number: &'s usize,
}

impl<'s> VecNumber<'s> {
    pub fn vec_number_iterable_per_item_in_auxiliary_object(
        &self,
    ) -> impl Iterator<Item = (&'s usize, impl Iterator<Item = &Number<'s>> + Clone)> {
        self.auxiliary_object.iter().map(move |n| {
            let iter_number = self.vec_number.iter();
            (n, iter_number)
        })
    }
}
```

I expected to see the code building (This code is old and was building for years on rust 1.54, and builds on rust 1.63. the code works as intended in the proprietary codebase)

Instead, this happened: 

```
error: lifetime may not live long enough
  --> src/main.rs:15:9
   |
11 |   impl<'s> VecNumber<'s> {
   |        -- lifetime `'s` defined here
12 |       pub fn vec_number_iterable_per_item_in_auxiliary_object(
13 |           &self,
   |           - let's call the lifetime of this reference `'1`
14 |       ) -> impl Iterator<Item = (&'s usize, impl Iterator<Item = &Number<'s>> + Clone)> {
15 | /         self.auxiliary_object.iter().map(move |n| {
16 | |             let iter_number = self.vec_number.iter();
17 | |             (n, iter_number)
18 | |         })
   | |__________^ associated function was supposed to return data with lifetime `'s` but it is returning data with lifetime `'1`
```

### Version it worked on

It most recently worked on: 1.63 (from my repo, commit : 4c37cdc458abdecd0baf018500bbc0611bad568f)
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```

### Version with regression

It does not work anymore on version 1.64: (from my repo, commit : 2728a5acdb645f93ef223a0bc15dd3545fd82c51)

```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

### Backtrace

Including the backtrace by setting `RUST_BACKTRACE=1` does not change anything to the error message.

I do not know why this problem occured though.

@rustbot modify labels: +regression-from-stable-to-{channel} -regression-untriaged
-->

### PR DESCRIPTION
**Pull request by spastorino**
Closes #103141

r? @cjgillot @nikomatsakis

This fixes a stable to stable regression that in my opinion is `P-critical` so, we probably want to backport it all the way up to stable.

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -545,13 +545,36 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+            // following inner impl traits.
+            //
+            // When we are processing the innermost impl trait, the one with `Item=&Number<'s>`, we
+            // would end with a generics_def_id_map like:
+            //
+            // `[[self#'_ -> impl_iterator_1#'_], [impl_iterator_1#'_ -> impl_iterator_2#'_]]`
+            //
+            // So starting with self#'_, we want to return impl_iterator_2#'_ and this is why
+            // afterwards we need to keep applying remapping forward.
+            for map in &self.generics_def_id_map {
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/lib.rs:571]: Using the same reasoning as the outer loop: why shouldn't this be in reverse order?

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 2]
```diff
@@ -545,13 +545,36 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
         // `[[fn#'b -> impl_trait#'b], [fn#'b -> impl_sized#'b]]`
```
Comment (cjgillot) [inline compiler/rustc_ast_lowering/src/lib.rs:545]: Why isn't the mapping `[[fn#'b -> impl_trait#'b], [impl_trait#'b -> impl_sized#'b]]`?

**Comment by spastorino** [comment]
@cjgillot, pushed a different change that changes the remappings to always be from the main outermost def_id, the innermost ones. That means that the remapping chain shouldn't be needed.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 2 above)
Comment (spastorino) [reply compiler/rustc_ast_lowering/src/lib.rs:548]: After my new change would always be `[[fn#'b -> impl_trait#'b], [fn#'b -> impl_sized#'b]]`

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 1 above)
Comment (spastorino) [reply compiler/rustc_ast_lowering/src/lib.rs]: This is not needed because the mapping would now also be ... `[[self#'_ -> impl_iterator_1#'_], [self#'_ -> impl_iterator_2#'_]]`

**Comment by spastorino** [comment]
@cjgillot this is ready now. I've just pushed again because I've found that's better to have the same set of "orig" methods and remapped methods, said `orig_local_def_id` and `orig_opt_local_def_id` as we have `local_def_id` and `opt_local_def_id`. That saves to `unwrap` in the call site.

**Comment by spastorino** [comment]
This was `stable-accepted` https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-20/near/305212449

@rustbot label +stable-accepted -stable-nominated

**Comment by spastorino** [comment]
@cuviper this was meant to be `stable-accepted`, unsure if you need to revisit something here.

**Comment by cuviper** [comment]
For stable backports, we wait until there's an actual stable point release in motion, but it should keep both labels until then so we know it hasn't been done.

**Comment by cuviper** [comment]
I already included this one in beta, #103316.

@rustbot label -beta-nominated
