### PR TITLE
Account for removal of multiline span in suggestion

### LINKED ISSUE #134485: Wrong coloring on "consider removing this method call"
Consider this code:

```Rust
use std::collections::{HashMap, HashSet};
fn foo() -> Vec<(bool, HashSet<u8>)> {
	let mut hm = HashMap::<bool, Vec<HashSet<u8>>>::new();
	hm.into_iter()
		.map(|(is_true, ts)| {
			ts.into_iter()
				.map(|t| (is_true, t))
				.flatten()
		})
		.flatten()
		.collect()
}
```

It gives:

```
error[E0277]: `(bool, HashSet<u8>)` is not an iterator
    --> a.rs:8:6
     |
8    |                 .flatten()
     |                  ^^^^^^^ `(bool, HashSet<u8>)` is not an iterator
     |
     = help: the trait `Iterator` is not implemented for `(bool, HashSet<u8>)`
     = note: required for `(bool, HashSet<u8>)` to implement `IntoIterator`
note: required by a bound in `flatten`
    --> src/rust/library/core/src/iter/traits/iterator.rs:1517:21
     |
1514 |     fn flatten(self) -> Flatten<Self>
     |        ------- required by a bound in this associated function
...
1517 |         Self::Item: IntoIterator,
     |                     ^^^^^^^^^^^^ required by this bound in `Iterator::flatten`
help: consider removing this method call, as the receiver has type `std::vec::IntoIter<HashSet<u8>>` and `std::vec::IntoIter<HashSet<u8>>: Iterator` trivially holds
     |
6    -             ts.into_iter()
7    -                 .map(|t| (is_true, t))
6    +             ts.into_iter()
     |

error[E0277]: `(bool, HashSet<u8>)` is not an iterator
   --> a.rs:4:2
    |
4   | /     hm.into_iter()
5   | |         .map(|(is_true, ts)| {
6   | |             ts.into_iter()
7   | |                 .map(|t| (is_true, t))
8   | |                 .flatten()
9   | |         })
    | |__________^ `(bool, HashSet<u8>)` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `(bool, HashSet<u8>)`
    = note: required for `(bool, HashSet<u8>)` to implement `IntoIterator`
note: required by a bound in `Flatten`
   --> src/rust/library/core/src/iter/adapters/flatten.rs:254:38
    |
254 | pub struct Flatten<I: Iterator<Item: IntoIterator>> {
    |                                      ^^^^^^^^^^^^ required by this bound in `Flatten`

error[E0599]: the method `collect` exists for struct `Flatten<Map<IntoIter<bool, Vec<HashSet<u8>>>, ...>>`, but its trait bounds were not satisfied
   --> a.rs:11:4
    |
4   | /     hm.into_iter()
5   | |         .map(|(is_true, ts)| {
6   | |             ts.into_iter()
7   | |                 .map(|t| (is_true, t))
...   |
10  | |         .flatten()
11  | |         .collect()
    | |         -^^^^^^^ method cannot be called due to unsatisfied trait bounds
    | |_________|
    |
    |
   ::: src/rust/library/core/src/iter/adapters/flatten.rs:254:1
    |
254 |   pub struct Flatten<I: Iterator<Item: IntoIterator>> {
    |   --------------------------------------------------- doesn't satisfy `<_ as IntoIterator>::IntoIter = _`, `<_ as IntoIterator>::Item = _`, `_: IntoIterator` or `_: Iterator`
    |
    = note: the full type name has been written to 'a.long-type-10511036807638515192.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the following trait bounds were not satisfied:
            `<Flatten<Map<std::vec::IntoIter<HashSet<u8>>, {closure@a.rs:7:10: 7:13}>> as IntoIterator>::IntoIter = _`
            which is required by `Flatten<Map<std::collections::hash_map::IntoIter<bool, Vec<HashSet<u8>>>, {closure@a.rs:5:8: 5:23}>>: Iterator`
            `<Flatten<Map<std::vec::IntoIter<HashSet<u8>>, {closure@a.rs:7:10: 7:13}>> as IntoIterator>::Item = _`
            which is required by `Flatten<Map<std::collections::hash_map::IntoIter<bool, Vec<HashSet<u8>>>, {closure@a.rs:5:8: 5:23}>>: Iterator`
            `Flatten<Map<std::vec::IntoIter<HashSet<u8>>, {closure@a.rs:7:10: 7:13}>>: IntoIterator`
            which is required by `Flatten<Map<std::collections::hash_map::IntoIter<bool, Vec<HashSet<u8>>>, {closure@a.rs:5:8: 5:23}>>: Iterator`
            `Flatten<Map<std::collections::hash_map::IntoIter<bool, Vec<HashSet<u8>>>, {closure@a.rs:5:8: 5:23}>>: Iterator`
            which is required by `&mut Flatten<Map<std::collections::hash_map::IntoIter<bool, Vec<HashSet<u8>>>, {closure@a.rs:5:8: 5:23}>>: Iterator`
```

My bug report is about the coloring in this particular suggestion:

Image

removing the red parts will [obviously make the situation worse](https://xkcd.com/859/) and cause parsing errors.

Even if you remove the entire `map` function call, it won't fix all the errors, what is needed is the removal of `flatten`. I want to make this particular issue about the wrong coloring of that red part: there is some mistake about it.

Appears on latest nightly `rustc 1.85.0-nightly (a4cb3c831 2024-12-17)` as well as beta `rustc 1.84.0-beta.4 (202008a1b 2024-12-07)`.

### PR DESCRIPTION
**Pull request by estebank**
When highlighting the removed parts of a suggestion, properly account for spans that cover more than one line.

Fix #134485.

Screenshot of the highlighted output

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? jieyouxu

File: compiler/rustc_errors/src/emitter.rs [hunk 1]
```diff
@@ -2263,13 +2268,52 @@ impl HumanEmitter {
...
+                            // lines.
+                            // FIXME: We check the number of rows because in some cases, like in
+                            // `tests/ui/lint/invalid-nan-comparison-suggestion.rs`, the rendered
+                            // suggestion will only show the first line of code being replaced. The
+                            // proper way of doing this would be to change the suggestion rendering
+                            // logic to show the whole prior snippet, but the current output is not
+                            // too bad to begin with, so we side-step that issue here.
+                            for (i, line) in snippet.lines().enumerate() {
+                                let line = normalize_whitespace(line);
+                                let row = row_num - 2 - (newlines - i - 1);
```
Comment (jieyouxu) [inline compiler/rustc_errors/src/emitter.rs:2284]: Question [OFFSETS 1/2]: what's the significance of `row_num - 2`? There's several `+/- n` in this region of code which are not immediately obvious (modulo the `- 1` cases), but this one in particular is somewhat mysterious (at least to me).

File: compiler/rustc_errors/src/emitter.rs [hunk 2]
```diff
@@ -2263,13 +2268,52 @@ impl HumanEmitter {
...
+                                    (padding as isize + span_end_pos as isize) as usize
+                                } else {
+                                    (padding as isize + line.len() as isize) as usize
+                                };
+                                buffer.set_style_range(row, start, end, Style::Removal, true);
+                            }
+                        } else {
+                            // The removed code fits all in one line.
+                            buffer.set_style_range(
+                                row_num - 2,
```
Comment (jieyouxu) [inline compiler/rustc_errors/src/emitter.rs:2310]: Question [OFFSETS 2/2]: same here, what's the significance of `row_num - 2`?

File: tests/ui/error-emitter/multiline-removal-suggestion.rs [hunk 3]
```diff
@@ -0,0 +1,53 @@
+// Make sure suggestion for removal of a span that covers multiple lines is properly highlighted.
+//@ compile-flags: --error-format=human --color=always
+//@ edition:2018
+// ignore-tidy-tab
+use std::collections::{HashMap, HashSet};
+fn foo() -> Vec<(bool, HashSet<u8>)> {
+	let mut hm = HashMap::<bool, Vec<HashSet<u8>>>::new();
```
Comment (jieyouxu) [inline tests/ui/error-emitter/multiline-removal-suggestion.rs:7]: Question: is there a specific reason why the indents in this file use tabs?

File: tests/ui/error-emitter/multiline-removal-suggestion.svg
Comment (jieyouxu) [inline tests/ui/error-emitter/multiline-removal-suggestion.svg:1]: Remark: the svg snapshots are very nice :3 The removal span highlighting does indeed look much nicer with the changes in this PR!

**Review by jieyouxu — APPROVED** [review]
Thanks! The removal highlight does indeed looks much nicer. I left a few questions, but LGTM otherwise.

File: compiler/rustc_errors/src/emitter.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_errors/src/emitter.rs:2284]: `row_num` at this point corresponds to

```
   |
LL | CODE
   | ++++  <- this row
```

in the buffer. When we have a diff format output, we end up with

```
   |
LL - OLDER
LL + NEWER
   |         <- this row
```

The `row_num - 2` is to select the buffer line that has the "old version of the diff" at that point. When the removal is a single line, `i` is `0`, `newlines` is `1` so `(newlines - i - 1)` ends up being `0`, so `row` points at `LL - OLDER`. When the removal corresponds to multiple lines, we end up with `newlines > 1` and `i` being `0..newlines - 1`.

```
   |
LL - OLDER
LL - CODE
LL - BEING
LL - REMOVED
LL + NEWER
   |         <- this row
```

How should I communicate this better in a comment?

File: compiler/rustc_errors/src/emitter.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_errors/src/emitter.rs:2310]: We can probably unify the two branches. Do note that this is the previously existing code being moved around.

File: tests/ui/error-emitter/multiline-removal-suggestion.rs (hunk 3 above)
Comment (estebank) [reply tests/ui/error-emitter/multiline-removal-suggestion.rs:7]: To ensure that the code normalization logic still kicks in correctly, given that I'm doing length calculations involving the original code. `\t` gets always replaced with `   `.

File: compiler/rustc_errors/src/emitter.rs (hunk 2 above)
Comment (jieyouxu) [reply compiler/rustc_errors/src/emitter.rs:2310]: Yeah I see that, it's just that this one was equally mysterious lol.

File: compiler/rustc_errors/src/emitter.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_errors/src/emitter.rs:2284]: Honestly? I can't think of any shorter explanation that's also unambiguous. I would just copy-pasta what you said as a comment, even at the risk of the comment being outdated. Because until you explained this to me (thank you), I don't think anyone else would've been able to interpret this without extensive local testing...

File: tests/ui/error-emitter/multiline-removal-suggestion.rs (hunk 3 above)
Comment (jieyouxu) [reply tests/ui/error-emitter/multiline-removal-suggestion.rs:7]: Could you add that as a comment in the test? I imagine someone else who looked at this test might notice the tabs and go "huh?" because other ui tests typically only use spaces for indent purposes.

**Comment by jieyouxu** [comment]
Thanks, you can r=me after some commit nits.
@rustbot author

**Comment by jieyouxu** [comment]
Thanks! The comments made the logic *much* easier to follow.

**Comment by jieyouxu** [comment]
FTR this does not fail locally on msvc for me...

**Comment by jieyouxu** [comment]
Ok nvm I know exactly what the failure is... it's #132752 that I haven't gotten around to fixing, will take a look tmrw

**Comment by estebank** [comment]
That's a great find. I can also mark the test as linux only for now.

**Comment by jieyouxu** [comment]
> Ok nvm I know exactly what the failure is...

Actually I was wrong, because I looked at the unnormalized svg... The real reason I believe this:

Screenshot 2025-01-09 060739

Screenshot 2025-01-09 060749

I believe we use different colors between Unixes and Windows (Windows have some legacy workarounds to use different bright colors and such because the cmd.exe bright colors are *ass*).

@estebank lol
