### PR TITLE
Fix tail calls to `#[track_caller]` functions

### LINKED ISSUE #144755: `cannot guarantee tail call due to mismatched parameter counts`
I tried this code:

```rust
//@ check-pass
// so this should compile.
#![expect(incomplete_features)]
#![feature(explicit_tail_calls)]

fn a(x: u32) -> u32 {
    become b(x);
}

#[track_caller]
fn b(x: u32) -> u32 { x + 42 }

fn main() {
    assert_eq!(a(128), 54);
}
```

### Meta

`rustc --version --verbose`:
```
adcb3d3b4cd3b7c4cde642f3ed537037f293738e
```

<details><summary>Backtrace</summary>
<p>

```
cannot guarantee tail call due to mismatched parameter counts
  %2 = musttail call i32 @_ZN64FF3C930F77C71A201CC3F60E04A19F24F40C416034B4A3B4054609ACB4023FA01b17h0731788d0a0410ebE(i32 %0, ptr align 8 @2)
rustc-LLVM ERROR: Broken module found, compilation aborted!
```

</p>
</details>

### PR DESCRIPTION
**Pull request by WaffleLapkin**
We want `#[track_caller]` to be semver independent, i.e. it should not be a breaking change to add or remove it. Since it changes ABI of a function (adding an additional argument) we have to be careful to preserve this property when adding tail calls.

The only way to achieve this that I can see is:
- we forbid tail calls in functions which are marked with `#[track_caller]` (already implemented)
- tail-calling a `#[track_caller]` marked function downgrades the tail-call to a normal call (or equivalently tail-calls the shim made by fn def to fn ptr cast) (this pr)

Ideally the downgrade would be performed by a MIR pass, but that requires post mono MIR opts (cc @saethlin, rust-lang/rust#131650). For now I've changed code in cg_ssa to accomodate this behaviour (+ added a hack to mono collector so that the shim is actually generated)

Additionally I added a lint, although I don't think it's strictly necessary.

Alternative to rust-lang/rust#144762 (and thus closes rust-lang/rust#144762)
Fixes https://github.com/rust-lang/rust/issues/144755

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
I do not get it, both tests pass for me locally ?_?

**Comment by WaffleLapkin** [comment]
Update: @jieyouxu figured this out. It looks like the test suite that failed was running with `--pass=check`, which caused the tests that depend on diagnostic from codegen backend to fail. I've added `//@ ignore-pass` so it should be good now

**Comment by fee1-dead** [comment]
not too familiar with tail calls but the diff looks good to me

r? compiler

**Comment by WaffleLapkin** [comment]
r? lqd maybe (since you were excited about tail calls ^^')

**Comment by lqd** [comment]
It also LGTM -- though to be clear, I'm not familiar with the `#[track_caller]` infra. I wonder if people will have questions about the wording "has no special effect", as in "will not be TCEd yet".

Also, do we have to involve t-lang for new lints?

**Comment by VorpalBlade** [comment]
> tail-calling a #[track_caller] marked function downgrades the tail-call to a normal call (or equivalently tail-calls the shim made by fn def to fn ptr cast) (this pr)

Would this be a silent downgrade? I think that would be a terrible idea, since for me the main usage of `become` is guaranteed tail calls for threaded interpreters. The tail call turning into a normal call means the code won't work and will eventually overflow the stack. This sort of implicit behaviour is the antithesis of what rust stands for.

**Comment by WaffleLapkin** [comment]
@lqd the wording is certainly not ideal, although I'm not entirely sure what would be the proper way to describe this situation. I don't think T-lang needs to be involved, since this lint is triggered only by an unstable/experimental feature (but they'll certainly have to look into the lint before stabilizing the feature).

@VorpalBlade it will not be silent, as this PR also adds a lint. However, note that functions marked with `#[track_caller]` can't tail call other functions, and as such can't participate in any tail call cycles, so you don't have any guarantees about stack exhaustion regardless.

**Comment by lqd** [comment]
Ok I wasn't aware of the procedure for new lints.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 1]
```diff
@@ -5100,3 +5100,35 @@ declare_lint! {
         report_in_deps: true,
     };
 }
+
+declare_lint! {
+    /// The `tail_call_track_caller` lint detects usage of `become` attempting to tail call
+    /// function marked with `#[track_caller]`.
```
Comment (lqd) [inline compiler/rustc_lint_defs/src/builtin.rs]: nit, "a function" or "functions"

**Review by lqd — APPROVED** [review]
👍

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 2]
```diff
@@ -5100,3 +5100,35 @@ declare_lint! {
...
+    /// {{produces}}
+    ///
+    /// ### Explanation
+    ///
+    /// Due to implementation details of tail calls and `#[track_caller]` attribute, calls to
+    /// functions marked with `#[track_caller]` cannot become tail calls. As such using `become`
+    /// is no different than a normal call (except for changes in drop order).
+    pub TAIL_CALL_TRACK_CALLER,
+    Warn,
+    "detects tail calls of functions marked with `#[track_caller]`"
```
Comment (compiler-errors) [inline compiler/rustc_lint_defs/src/builtin.rs]: Could you gate this behind the tail call feature?

I can't remember the syntax but I think it's something like `@feature = ...`.

Comment (WaffleLapkin) [reply compiler/rustc_lint_defs/src/builtin.rs]: I did not know this is something that can be done!

The syntax is apparently `@feature_gate = ident;`. I've gated the lint.

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_lint_defs/src/builtin.rs]: Fixed

**Comment by lqd** [comment]
🚀 

@bors r+
