### PR TITLE
melt the ICE when lowering an impossible range

### LINKED ISSUE #32245: ICE: "impossible range in AST" with a lone `...` (inclusive range syntax)
```rust
#![feature(inclusive_range_syntax)]

fn main() {
    ...;
}
```
```
$ RUST_BACKTRACE=1 rustc lone-incl-range.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'impossible range in AST', src/librustc_front/lowering.rs:1291
stack backtrace:
   1:     0x7f355e9a7080 - sys::backtrace::tracing::imp::write::h6cb2e6cc562f1157ajv
   2:     0x7f355e9b127f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44459
   3:     0x7f355e9b0df3 - panicking::default_handler::h60d5c200be7610ffr7z
   4:     0x7f355e9791dc - sys_common::unwind::begin_unwind_inner::h97e84635bfe5e882t7t
   5:     0x7f355b13787f - sys_common::unwind::begin_unwind::h8452793534382620991
   6:     0x7f355b1510f0 - lowering::lower_expr::_$u7b$$u7b$closure$u7d$$u7d$::closure.31555
   7:     0x7f355b13be50 - lowering::lower_expr::h65bdcc84b4cf88da2vr
   8:     0x7f355b142dd4 - vec::Vec<T>.FromIterator<T>::from_iter::h12825153023271112045
   9:     0x7f355b142bc4 - lowering::lower_block::h8dc738a2417bb8b6Mar
  10:     0x7f355b143adb - lowering::lower_item_kind::hc3b0928913e39eb6Dbr
  11:     0x7f355b148dce - lowering::lower_item::h92bd16a94ad331ab3mr
  12:     0x7f355b145e8e - lowering::ItemLowerer<'lcx, 'interner>.Visitor<'lcx>::visit_item::h5af224959762239erkr
  13:     0x7f355b14a46b - lowering::lower_crate::ha58482b99d537c2e0kr
  14:     0x7f355eeb9176 - driver::compile_input::hbe58952840e9fa26Pca
  15:     0x7f355eea81b6 - run_compiler::h43154ab0ccc9972aJPc
  16:     0x7f355eea5931 - sys_common::unwind::try::try_fn::h13700893182557476600
  17:     0x7f355e9a48fb - __rust_try
  18:     0x7f355e9a488d - sys_common::unwind::inner_try::h602712f93ad93b38v4t
  19:     0x7f355eea617a - boxed::F.FnBox<A>::call_box::h17985710921385728096
  20:     0x7f355e9af389 - sys::thread::Thread::new::thread_start::hc6901d1da7801591h4y
  21:     0x7f3557d7d9d0 - start_thread
  22:     0x7f355e6398fc - clone
  23:                0x0 - <unknown>
$ rustc --version --verbose
rustc 1.9.0-dev (211296dda 2016-03-13)
binary: rustc
commit-hash: 211296ddabb6a307a0f60af1cb93f39b85ba5bbd
commit-date: 2016-03-13
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev
```

### PR DESCRIPTION
**Pull request by durka**
Emit a fatal error instead of panicking when HIR lowering encounters a range with no `end` point.

This involved adding a method to wire up `LoweringContext::span_fatal`.

Fixes #32245 (cc @nodakai).

r? @nrc

### CODE REVIEW

**Comment by durka** [comment]
Should I define an error code and use `span_fatal_with_code` instead?

**Comment by alexcrichton** [comment]
"melt the ICE" -- this is an amazing phrase

:shaved_ice:

**Comment by durka** [comment]
Also, if `span_fatal` is for things that _shouldn't happen_... you can write a lone `...` no problem and it doesn't get caught until here. (Whereas `a...` cannot be produced without a broken syntax extension.) So should I try to catch lone `...` in the parser as well, so that it is recoverable?

**Comment by nrc** [comment]
> Should I define an error code and use span_fatal_with_code instead?

Ideally yes, but I don't think it is essential.

> Also, if span_fatal is for things that shouldn't happen... you can write a lone ... no problem and it doesn't get caught until here. (Whereas a... cannot be produced without a broken syntax extension.) So should I try to catch lone ... in the parser as well, so that it is recoverable?

span_fatal is for things we can't recover from, rather than things that shouldn't happen. It's nice if those two things align, since unrecoverable errors are not great for the user, so should be rare.

I think we should try and catch a lone `...` before here. If we can do so in the parser then that would be good. (Note that since we can recover in the parser, we won't abort compilation until lowering and we shouldn't report the error twice. Usually we have some mechanism for that - e.g., we don't emit errors that involve TyErr, but in this case we might have to do something ad hoc).

File: src/librustc/session/mod.rs [hunk 1]
```diff
@@ -336,6 +336,10 @@ impl NodeIdAssigner for Session {
     fn peek_node_id(&self) -> NodeId {
         self.next_node_id.get().checked_add(1).unwrap()
     }
+
+    fn span_fatal(&self, sp: MultiSpan, msg: &str) -> ! {
```
Comment (nrc) [inline src/librustc/session/mod.rs]: NodeIdAssigner could have a GetDiagnostic method returning Option<Diagnostic>, that avoids having error methods for every kind of error in NodeIdAssigner.

Comment (nrc) [inline src/librustc/session/mod.rs]: Or just a Diagnostic and panic if it can't be done.

**Comment by durka** [comment]
> I think we should try and catch a lone ... before here. If we can do so in the parser then that would be good. (Note that since we can recover in the parser, we won't abort compilation until lowering and we shouldn't report the error twice. Usually we have some mechanism for that - e.g., we don't emit errors that involve TyErr, but in this case we might have to do something ad hoc).

I was wondering about this. What _does_ the parser leave behind in the AST when it recovers? Does it just skip the line of code? I tried to inspect the AST, but apparently semicolon recovery isn't enough to get to `--pretty=expanded`.

File: src/librustc/session/mod.rs (hunk 1 above)
Comment (durka) [inline src/librustc/session/mod.rs]: Hmm so bring in `DiagnosticBuilder` from libsyntax?

Comment (nrc) [inline src/librustc/session/mod.rs]: syntax::errors::Handler (sorry, naming has changed somewhat); and GetHandler.

**Comment by nrc** [comment]
In the AST there isn't an 'error' node. We only recover if we can make a valid AST.

File: src/test/compile-fail/impossible_range.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+#![feature(inclusive_range_syntax)]
+
+pub fn main() {
+    ..;
+    0..;
+    ..1;
+    0..1;
+
+    ...; //~ERROR inclusive range with no end
```
Comment (durka) [inline src/test/compile-fail/impossible_range.rs]: I'm a little confused. We get to this error during lowering, so I assumed the one on the next line (which is a parse error) was recovered. But what valid AST could be left behind?

Comment (nrc) [inline src/test/compile-fail/impossible_range.rs]: A range with neither start nor end - the AST doesn't have to be well-formed (for some definition), it just must be constructable. We don't get the lowering error there because the first error was fatal. I suspect if you have a test case with just that line, you would get both a parsing and lowering error.

**Comment by durka** [comment]
> in this case we might have to do something ad hoc

Here's my plan (can't work on it until tonight): add a field to `ast::RangeLimits` (perhaps renamed to `ast::RangeKind`) which the parser sets if it emits an error while constructing a bad range. I can set this field and emit the error [in `mk_range`](https://github.com/rust-lang/rust/blob/9afa5a13cc258315d012d5e3a42740e4ac0dff2a/src/libsyntax/parse/parser.rs#L2071). Then in HIR lowering we will emit an error if this field isn't set, but if it is... abort silently? This is still a bad experience if a syntax extension sets the field by mistake though.

Anyway, this situation will probably go away when @aturon and I get around to writing that RFC to change the syntax and allow all types of ranges :)

**Comment by durka** [comment]
I added the parse error. Haven't implemented the `NodeIdAssigner` change yet.

**Comment by durka** [comment]
OK, ready for review.

File: src/librustc/session/mod.rs (hunk 1 above)
Comment (durka) [inline src/librustc/session/mod.rs]: Done (except this code path is now untested because the parse error was made fatal).

File: src/librustc/session/mod.rs [hunk 3]
```diff
@@ -336,6 +336,10 @@ impl NodeIdAssigner for Session {
     fn peek_node_id(&self) -> NodeId {
         self.next_node_id.get().checked_add(1).unwrap()
     }
+
+    fn diagnostic(&self) -> &errors::Handler {
+        self.diagnostic()
```
Comment (durka) [inline src/librustc/session/mod.rs]: Um. This looks... weird. Did I introduce an infinite recursion (I didn't see a warning) or it's OK because inherent fns take precedence over trait fns?

File: src/libsyntax/parse/parser.rs [hunk 4]
```diff
@@ -2961,15 +2968,15 @@ impl<'a> Parser<'a> {
...
+                // generalise it to the Fixity::None code.
                 //
-                // We have 2 alternatives here: `x..y` and `x..` The other two variants are
-                // handled with `parse_prefix_range_expr` call above.
+                // We have 2 alternatives here: `x..y`/`x...y` and `x..`/`x...` The other
+                // two variants are handled with `parse_prefix_range_expr` call above.
                 let rhs = if self.is_at_start_of_range_notation_rhs() {
                     let rhs = self.parse_assoc_expr_with(op.precedence() + 1,
-                                                         LhsExpr::NotYetParsed);
+                    LhsExpr::NotYetParsed);
```
Comment (nodakai) [inline src/libsyntax/parse/parser.rs]: Here and around `hi = x.span.hi;` indents seems to be wrong.

Comment (durka) [inline src/libsyntax/parse/parser.rs]: Hmm, there's a bug in rust.vim.

File: src/librustc_front/lowering.rs [hunk 5]
```diff
@@ -140,6 +141,11 @@ impl<'a, 'hir> LoweringContext<'a> {
             result
         }
     }
+
+    // panics if this LoweringContext's NodeIdAssigner is not a Session
```
Comment (nrc) [inline src/librustc_front/lowering.rs]: I think the bit about being a Session is too much detail, one could imagine implementing NodeIdAssigner with something that is not a Session but can still provide a diagnostic (also, nit, comments should start with a capital and end with a period).

File: src/libsyntax/parse/parser.rs [hunk 6]
```diff
@@ -2072,8 +2072,15 @@ impl<'a> Parser<'a> {
...
                     end: Option<P<Expr>>,
                     limits: RangeLimits)
-                    -> ast::ExprKind {
-        ExprKind::Range(start, end, limits)
+                    -> PResult<'a, ast::ExprKind> {
+        if end.is_none() && limits == RangeLimits::Closed {
+            Err(self.span_fatal_help(self.span,
+                                     "inclusive range with no end",
+                                     "currently, inclusive ranges must be bounded at the end \
+                                      (`...b` or `a...b`) -- see tracking issue #28237"))
```
Comment (nrc) [inline src/libsyntax/parse/parser.rs]: I would remove "currently" and the reference to a tracking issue

File: src/libsyntax/parse/parser.rs [hunk 7]
```diff
@@ -3003,8 +3016,7 @@ impl<'a> Parser<'a> {
                         this.parse_assoc_expr_with(op.precedence() + 1,
                             LhsExpr::NotYetParsed)
                 }),
-                // the only operator handled here is `...` (the other non-associative operators are
-                // special-cased above)
+                // no operators are currently handled here
```
Comment (nrc) [inline src/libsyntax/parse/parser.rs]: if no operators are handled, but we don't emit an error, what is this block for? (Probably the comment can be clearer).

**Comment by nrc** [comment]
looks good, r+ with the minor comments addressed

File: src/libsyntax/parse/parser.rs (hunk 6 above)
Comment (durka) [inline src/libsyntax/parse/parser.rs]: Hmm I thought people might want to chime in on the tracking issue if they have some use case for end-less ranges. I'm fine taking it out though.

File: src/libsyntax/parse/parser.rs (hunk 7 above)
Comment (durka) [inline src/libsyntax/parse/parser.rs]: AFAIK this code is dead. [Here is the comment](https://github.com/rust-lang/rust/blob/stable/src/libsyntax/parse/parser.rs#L2836-L2837) from before my original #30884. I made use of that "future convenience" since I originally didn't care to parse `a...`, but to produce a good error I had to back that out and use the same special case as `a..`.

File: src/librustc/session/mod.rs (hunk 3 above)
Comment (pnkfelix) [inline src/librustc/session/mod.rs]: yeah, inherent has precedence.

and looking more at this has made me realized that one cannot resort to UFCS as a way to try to "clarify" that the inherent method is what is intended. There's no way to say "I want an inherent impl and only an inherent impl", at least not via UFCS...

File: src/librustc_front/lowering.rs (hunk 5 above)
Comment (durka) [inline src/librustc_front/lowering.rs]: Fixed.

File: src/libsyntax/parse/parser.rs (hunk 7 above)
Comment (durka) [inline src/libsyntax/parse/parser.rs]: I restored the comment from before.

**Comment by durka** [comment]
2/3 nits addressed, 1/3 nits quibbled with.

File: src/librustc/session/mod.rs (hunk 3 above)
Comment (durka) [inline src/librustc/session/mod.rs]: I think you [can](http://is.gd/MABosu).

Comment (durka) [inline src/librustc/session/mod.rs]: > There's no way to say "I want an inherent impl and only an inherent impl"

That seems good. Then you can factor out an inherent method into a trait method without a breaking change, is that true?

File: src/libsyntax/parse/parser.rs (hunk 6 above)
Comment (nrc) [inline src/libsyntax/parse/parser.rs]: I don't think we often include issue numbers in error messages. If there is something specific we want feedback on, then it might make sense, but in that case it needs a url rather than a number and much more explanation.

Comment (durka) [inline src/libsyntax/parse/parser.rs]: Fixed.

**Comment by durka** [comment]
Should be good to go now.

**Comment by nrc** [comment]
r+, but needs a rebase

**Comment by durka** [comment]
Guh. The untry conversion broke a bunch of alignment in libsyntax. Don't know why we let that through with autoformatting.

**Comment by durka** [comment]
Rebased.

File: src/libsyntax/parse/parser.rs [hunk 8]
```diff
@@ -3095,21 +3103,23 @@ impl<'a> Parser<'a> {
...
-                                                 LhsExpr::NotYetParsed)
-            .map(|x|{
-                hi = x.span.hi;
-                x
-            })?)
+                                            LhsExpr::NotYetParsed)
+                .map(|x|{
+                    hi = x.span.hi;
+                    x
+                })?)
```
Comment (durka) [inline src/libsyntax/parse/parser.rs]: Just for the record, I think this is _much_ harder to read than the old version with `try!`. You have to parse the entire expression **backwards** from `?` to see what it applies to.
