### PR TITLE
Drop support for legacy PM with LLVM 15

### LINKED ISSUE #96072: Drop support for legacy PM with LLVM 15
Support for the legacy pass manager is being actively removed in LLVM 15. We need to make `-Z new-llvm-pass-manager=no` error with LLVM 15 (or warn and ignore), and remove references to certain FFI functions either exported by the Rust wrapper or llvm-c.

This would be at least the `LLVMRustCreate*Pass` family of functions, as well as the `LLVMPsasManagerBuilder*` family of functions. As the latter are provided by llvm-c, I guess we'd want to use weak symbols for those.

### LINKED ISSUE #96362: fix rustc build with llvm head
building rust started failing like so:

```
rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-475f372969e8d34a/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp"
   cargo:warning=llvm-wrapper/PassWrapper.cpp:124:15: error: use of undeclared identifier 'createAddressSanitizerFunctionPass'; did you mean 'createHWAddressSanitizerLegacyPassPass'?
   cargo:warning=  return wrap(createAddressSanitizerFunctionPass(CompileKernel, Recover, UseAfterScope));
   cargo:warning=              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cargo:warning=              createHWAddressSanitizerLegacyPassPass
   cargo:warning=/b/s/w/ir/cache/builder/src/third_party/llvm/llvm/include/llvm/Transforms/Instrumentation/HWAddressSanitizer.h:54:1: note: 'createHWAddressSanitizerLegacyPassPass' declared here
   cargo:warning=createHWAddressSanitizerLegacyPassPass(bool CompileKernel = false,
   cargo:warning=^
   cargo:warning=llvm-wrapper/PassWrapper.cpp:130:15: error: use of undeclared identifier 'createModuleAddressSanitizerLegacyPassPass'; did you mean 'createHWAddressSanitizerLegacyPassPass'?
   cargo:warning=  return wrap(createModuleAddressSanitizerLegacyPassPass(CompileKernel, Recover));
   cargo:warning=              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cargo:warning=              createHWAddressSanitizerLegacyPassPass
   cargo:warning=/b/s/w/ir/cache/builder/src/third_party/llvm/llvm/include/llvm/Transforms/Instrumentation/HWAddressSanitizer.h:54:1: note: 'createHWAddressSanitizerLegacyPassPass' declared here
   cargo:warning=createHWAddressSanitizerLegacyPassPass(bool CompileKernel = false,
   cargo:warning=^
   cargo:warning=llvm-wrapper/PassWrapper.cpp:136:15: error: use of undeclared identifier 'createMemorySanitizerLegacyPassPass'
   cargo:warning=  return wrap(createMemorySanitizerLegacyPassPass(
   cargo:warning=              ^
   cargo:warning=llvm-wrapper/PassWrapper.cpp:168:17: error: no member named 'populateThinLTOPassManager' in 'llvm::PassManagerBuilder'; did you mean 'populateModulePassManager'?
   cargo:warning=  unwrap(PMBR)->populateThinLTOPassManager(*unwrap(PMR));
   cargo:warning=                ^~~~~~~~~~~~~~~~~~~~~~~~~~
   cargo:warning=                populateModulePassManager
   cargo:warning=/b/s/w/ir/cache/builder/src/third_party/llvm/llvm/include/llvm/Transforms/IPO/PassManagerBuilder.h:226:8: note: 'populateModulePassManager' declared here
   cargo:warning=  void populateModulePassManager(legacy::PassManagerBase &MPM);
   cargo:warning=       ^
   cargo:warning=4 errors generated.
   exit status: 1
```

Need to update rust code to work after https://reviews.llvm.org/D124216 (createAddressSanitizerFunctionPass, createModuleAddressSanitizerLegacyPassPass removal, https://reviews.llvm.org/D123882 populateThinLTOPassManager removal).

https://github.com/rust-lang/rust/commit/6234a5694936cb0f7c9a3fb456ae4c0aeee69f11 has a related example.

@nikic Do you know if Augie (or anyone else) has a patch for this already?

@adetaylor

### PR DESCRIPTION
**Pull request by nikic**
LLVM 15 already removes some of the legacy PM APIs we're using. This patch forces use of NewPM with LLVM 15 (with `-Z new-llvm-pass-manager=no` throwing a warning) and stubs out various FFI methods with a report_fatal_error on LLVM 15.

For LLVMPassManagerBuilderPopulateLTOPassManager() I went with adding our own wrapper, as the alternative would be to muck about with weak symbols, which seems to be non-trivial as far as cross-platform support is concerned (std has `weak!` for this purpose, but only as an internal utility.)

Fixes #96072.
Fixes #96362.

### CODE REVIEW

File: src/test/codegen/panic-in-drop-abort.rs [hunk 1]
```diff
@@ -1,10 +1,12 @@
...
 // optimization.
 
-// This test uses -Z new-llvm-pass-manager=no, because the expected optimization does not happen
-// on targets using SEH exceptions (i.e. MSVC) anymore. The core issue is that Rust promises that
+// This test uses ignore-msvc, because the expected optimization does not happen on targets using
+// SEH exceptions with the new LLVM pass manager anymore, see
+// https://github.com/llvm/llvm-project/issues/51311. The core issue is that Rust promises that
 // the drop_in_place() function can't unwind, but implements it in a way that *can*, because we
 // currently go out of our way to allow longjmps, which also use the unwinding mechanism on MSVC
 // targets. We should either forbid longjmps, or not assume nounwind, making this optimization
```
[the remark this answers is not in the document]
Comment (nikic) [reply src/test/codegen/panic-in-drop-abort.rs]: Yeah, the description in this comment was not quite right. I went ahead and simply dropped this part, because the linked issue already contains an accurate description. Nothing that rustc does here is incorrect, this just isn't accurately modeled on the LLVM side right now.

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp [hunk 2]
```diff
@@ -6,6 +6,7 @@
 #include "llvm/IR/GlobalVariable.h"
 #include "llvm/IR/Instructions.h"
 #include "llvm/IR/Intrinsics.h"
+#include "llvm/IR/Mangler.h"
```
Comment (luqmana) [inline compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:9]: Nice catch, but curious why it didn't fail before.

Comment (nikic) [reply compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:9]: This happens regularly when relying on indirect header dependencies. Probably a header include was replaced with a forward declaration somewhere, so we need to explicitly include it now.

File: compiler/rustc_codegen_llvm/src/back/write.rs [hunk 3]
```diff
@@ -523,6 +523,12 @@ pub(crate) unsafe fn optimize(
     let module_name = module.name.clone();
     let module_name = Some(&module_name[..]);
 
+    if let Some(false) = config.new_llvm_pass_manager {
+        diag_handler.warn(
+            "ignoring `-Z new-llvm-pass-manager=no`, which is no longer supported with LLVM 15",
```
Comment (luqmana) [inline compiler/rustc_codegen_llvm/src/back/write.rs:528]: This message isn't actually gated on LLVM 15 here though?

Comment (nikic) [reply compiler/rustc_codegen_llvm/src/back/write.rs:528]: Yes ... we could make it a general deprecation, but with the message as written, this should indeed have a version check. Thanks!

**Comment by nagisa** [comment]
@bors r+

Seems clunky, but I think we can live with the clunk for the time being.
