### PR TITLE
fix rounding issue with exponents in fmt

### LINKED ISSUE #115737: scientific notation incorrect decimal places
I tried this code:

```rust
    assert_eq!("1.0e3", format!("{:.1e}", 1001));
    assert_eq!("1.0e3", format!("{:.1e}", 1000));
    assert_eq!("1.0e3", format!("{:.1e}", 999));
```

I expected this all to be fine.

Instead, the final assertion fails, and the formatting is done like this in the final case:
```rust
    assert_eq!("1.00e3", format!("{:.1e}", 999));
```
Not sure why 2 decimal places are returned, looks like a bug. 
This bug also exists in the beta or nightly versions, running in Rust Playground.

Discussion: https://users.rust-lang.org/t/scientific-notation-decimal-places/99682

Edit: after looking around the compiler code for the first time I think the problem is somewhere in either [format_exact](https://github.com/rust-lang/rust/blob/master/library/core/src/num/flt2dec/strategy/dragon.rs#L261) or [format_exact_opt](https://github.com/rust-lang/rust/blob/master/library/core/src/num/flt2dec/strategy/grisu.rs#L471).

### PR DESCRIPTION
**Pull request by mj10021**
fixes issue #115737 , where the decimal places are rounded incorrectly when formatting scientific notation

### CODE REVIEW

File: library/core/tests/fmt/num.rs [hunk 1]
```diff
@@ -128,30 +128,375 @@ fn test_format_int_exp_precision() {
...
+    assert_eq!(format!("{:.2e}",  1805), "1.81e3" );
+    assert_eq!(format!("{:.2e}",  1825), "1.83e3" );
+    assert_eq!(format!("{:.2e}",  1845), "1.85e3" );
+    assert_eq!(format!("{:.2e}",  1865), "1.87e3" );
+    assert_eq!(format!("{:.2e}",  1885), "1.89e3" );
+    assert_eq!(format!("{:.2e}",  1905), "1.91e3" );
+    assert_eq!(format!("{:.2e}",  1925), "1.93e3" );
+    assert_eq!(format!("{:.2e}",  1945), "1.95e3" );
+    assert_eq!(format!("{:.2e}",  1965), "1.97e3" );
+    assert_eq!(format!("{:.2e}",  1985), "1.99e3" );
```
Comment (cuviper) [inline library/core/tests/fmt/num.rs:497]: Aren't we supposed to be rounding ties toward even? So this would be "1.98e3", and many others would round down too.

Comment (mj10021) [reply library/core/tests/fmt/num.rs:497]: Is round to even spec'd in a doc?  I was trying to keep the same behavior as before using  https://doc.rust-lang.org/std/fmt/#precision as a reference for desired behavior based on the discussion here: https://users.rust-lang.org/t/scientific-notation-decimal-places/99682/5

Comment (cuviper) [reply library/core/tests/fmt/num.rs:497]: Sort of -- it's specified for operations on the [`f32`](https://doc.rust-lang.org/std/primitive.f32.html) page, and the `f64` page just references that.

> When the number resulting from a primitive operation (addition, subtraction, multiplication, or division) on this type is not exactly representable as f32, it is rounded according to the roundTiesToEven direction defined in IEEE 754-2008.

We do seem to do this for fractional formatting as well:

```rust
fn main() {
    println!("{:.2e}", 1.625);
    println!("{:.2e}", 16.25);
    println!("{:.2e}", 162.5);
    println!("{:.2e}", 1625);
    println!("{:.2e}", 16250);
}
```

Note that my choice of input values are represented precisely at all levels, so there's no ambiguity that these should be ties. The first three do round down to even, but the last two are rounding up.

```
1.62e0
1.62e1
1.62e2
1.63e3
1.63e4
```

Comment (mj10021) [reply library/core/tests/fmt/num.rs:497]: Ah, I see what you're saying.  Since the bug submitted was the number of digits expressed, would it be ok for me to take out the `assert!`s that enforce the non round-to-even behavior and then work on the rounding in a follow up PR?

Comment (cuviper) [reply library/core/tests/fmt/num.rs:497]: If you're *willing* to work on both, I'd rather do it all at once so they can land in the same release, and we only have to explain changes once. :)

Comment (mj10021) [reply library/core/tests/fmt/num.rs]: gotcha 🙂 i think what I just pushed rounds to evens on a tie correctly now

File: library/core/src/fmt/num.rs [hunk 2]
```diff
@@ -330,10 +330,17 @@ macro_rules! impl_Exp {
                 if subtracted_precision != 0 {
                     let rem = n % 10;
                     n /= 10;
+                    let last_digit_odd = (n % 10) % 2 != 0;
```
Comment (cuviper) [inline library/core/src/fmt/num.rs:333]: You don't need to isolate the last digit to know that it's odd.
```suggestion
                    let last_digit_odd = n % 2 != 0;
```

File: library/core/src/fmt/num.rs [hunk 3]
```diff
@@ -330,10 +330,17 @@ macro_rules! impl_Exp {
...
                     exponent += 1;
-                    // round up last digit
-                    if rem >= 5 {
+                    // round up last digit, round to even on a tie
+                    if rem > 5 || (rem == 5 && last_digit_odd) {
                         n += 1;
+                        // if the digit is rounded to the next power
+                        // instead adjust the exponent
+                        if n % 10 == 0 {
```
Comment (cuviper) [inline library/core/src/fmt/num.rs:340]: Hmm, doesn't this only tell you that you overflowed the least significant digit? e.g. maybe n=129 rolled up to 130, but that doesn't need any adjustment. For a new power of 10, like n=99 to 100, maybe something like `n.log10() > (n - 1).log10()` would work?

File: library/core/src/fmt/num.rs [hunk 4]
```diff
@@ -331,9 +331,15 @@ macro_rules! impl_Exp {
                     let rem = n % 10;
                     n /= 10;
                     exponent += 1;
-                    // round up last digit
-                    if rem >= 5 {
+                    // round up last digit, round to even on a tie
+                    if rem > 5 || (rem == 5 && n % 2 != 0) {
```
Comment (cuviper) [inline library/core/src/fmt/num.rs:335]: Sorry I keep noticing things, but I think we're almost there...

The check for even here is missing whether we removed any additional non-zero digits earlier. e.g., for `{:.1e}` I expect:

* 124999 => 1.2e5 (rounded down)
* 125000 => 1.2e5 (tie rounded down to even)
* 125001 => 1.3e5 (rounded up)
  * This one gets treated like a tie right now and prints 1.2e5
* 134999 1.3e5 (rounded down)
* 135000 1.4e5 (tie rounded up to even)
* 135001 1.4e5 (rounded up)

I think `subtracted_precision > 1` would account for the extra non-zero digits? Please do add these values as tests.

File: library/core/tests/fmt/num.rs [hunk 5]
```diff
@@ -128,28 +128,370 @@ fn test_format_int_exp_precision() {
...
+    assert_eq!(format!("{:.2e}",  1805), "1.80e3" );
+    assert_eq!(format!("{:.2e}",  1825), "1.82e3" );
+    assert_eq!(format!("{:.2e}",  1845), "1.84e3" );
+    assert_eq!(format!("{:.2e}",  1865), "1.86e3" );
+    assert_eq!(format!("{:.2e}",  1885), "1.88e3" );
+    assert_eq!(format!("{:.2e}",  1905), "1.90e3" );
+    assert_eq!(format!("{:.2e}",  1925), "1.92e3" );
+    assert_eq!(format!("{:.2e}",  1945), "1.94e3" );
+    assert_eq!(format!("{:.2e}",  1965), "1.96e3" );
+    assert_eq!(format!("{:.2e}",  1985), "1.98e3" );
```
Comment (cuviper) [inline library/core/tests/fmt/num.rs:494]: The more I look at this giant list of tests, the less I'm sure of its value. There are certainly some edge cases in here that we want to keep, but many are duplicating the exact same conditions. This makes it hard to see whether we actually have a test corresponding to the different pieces of the implementation.

For example, is there a test that exercises the power-of-10 overflow that we checked last time? I'm not sure.

Can we narrow it down to fewer targeted tests around different boundary conditions?

Comment (cuviper) [reply library/core/tests/fmt/num.rs:494]: Another possibility could be an exhaustive test comparing to the independent floating point implementation. Like, check *all* `i16` values compared to the same `f32` value, formatted to a few different levels of precision.

Comment (cuviper) [reply library/core/tests/fmt/num.rs:494]:
```rust
    for i in i16::MIN..=i16::MAX {
        for p in 0..=5 {
            assert_eq!(
                format!("{i:.p$e}"),
                format!("{:.p$e}", f32::from(i)),
                "integer {i} at precision {p}"
            );
        }
    }
```

**Comment by cuviper** [comment]
LGTM, thanks!

@bors r+
@rustbot label +relnotes
