### PR TITLE
Double check that hidden types match the expected hidden type

### LINKED ISSUE #113278: opaque type wf check anchor usage is unsound
see the second comment for an explanation: https://github.com/rust-lang/rust/issues/113278#issuecomment-1617700571

```rust
#![feature(trivial_bounds, type_alias_impl_trait)]
mod sus {
    pub type Sep = impl Sized;
    pub fn define_sep() -> Sep {
        String::new()
    }

    pub type Tait = impl Mk;

    pub trait Mk: Proj {
        fn mk() -> <Self as Proj>::Assoc;
    }

    impl<T> Mk for T
    where
        T: Proj<Assoc = ()>,
    {
        fn mk() -> <T as Proj>::Assoc {
            ()
        }
    }

    pub trait Proj {
        type Assoc;
    }
    impl Proj for () {
        type Assoc = Sep;
    }

    fn define() -> Tait
    where
        (): Proj<Assoc = ()>,
    {
    }
}

fn main() {
    let _ = <sus::Tait as sus::Mk>::mk();
}
```
results in
```
error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:413:18: failed to resolve instance for <() as Mk>::mk

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/37998ab508d5d9fa0d465d7b535dc673087dda8f/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
    [..]
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
```
going to minimize this further and explain why it is broken

### PR DESCRIPTION
**Pull request by oli-obk**
Fixes https://github.com/rust-lang/rust/issues/113278 specifically, but I left a TODO for where we should also add some hardening.

It feels a bit like papering over the issue, but at least this way we don't get unsoundness, but just surprising errors. Errors will be improved and given spans before this PR lands.

r? @compiler-errors @lcnr

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 1]
```diff
@@ -465,7 +468,51 @@ fn check_opaque_meets_bounds<'tcx>(
...
+            tcx,
+            ty_op: |t| t,
+            ct_op: |c| c,
+            lt_op: |l| match l.kind() {
+                RegionKind::ReVar(_) => tcx.lifetimes.re_erased,
+                _ => l,
+            },
+        });
+        let hidden_ty = tcx.type_of(key.def_id).subst(tcx, key.substs);
+        if hidden_ty != found_hidden_ty {
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/check/check.rs:502]: wwwill be fixed by making `InternalSubsts::identity_for_item(tcx, def_id.to_def_id());` use the anchor def id, instead of the opaque def id. For RPIT we make the hidden type based on the function, not the RPIT generics (which are just copies of the function generics, but with different DefIds)

File: compiler/rustc_const_eval/src/util/compare_types.rs [hunk 2]
```diff
@@ -56,8 +56,13 @@ pub fn is_subtype<'tcx>(
...
-    //
-    // It seems very unlikely that this hides any bugs.
-    let _ = infcx.take_opaque_types();
+    for (key, ty) in infcx.take_opaque_types() {
+        span_bug!(
+            ty.hidden_type.span,
+            "{}, {}",
+            tcx.type_of(key.def_id).subst(tcx, key.substs),
+            ty.hidden_type.ty
+        );
```
Comment (lcnr) [inline compiler/rustc_const_eval/src/util/compare_types.rs:65]: I feel like we should hit this bug? :thinking: or do we avoid it because we have `OpaqueCast` everywhere we would assign to/from opaques?

Comment (oli-obk) [reply compiler/rustc_const_eval/src/util/compare_types.rs:65]: I was surprised, too, but I didn't debug it.

Comment (lcnr) [reply compiler/rustc_const_eval/src/util/compare_types.rs:65]: do we run the validator before optimizations by default :sweat_smile: iirc we only do it with `-Zvalidate-mir` :thinking:

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 3]
```diff
@@ -464,11 +467,143 @@ fn check_opaque_meets_bounds<'tcx>(
...
+    let mut hidden_ty = tcx.type_of(key.def_id).instantiate(tcx, key.args);
+    if let hir::OpaqueTyOrigin::FnReturn(..) | hir::OpaqueTyOrigin::AsyncFn(..) = origin {
+        if hidden_ty != ty.ty {
+            hidden_ty = find_and_apply_rpit_substs(
+                tcx,
+                hidden_ty,
+                defining_use_anchor.to_def_id(),
+                key.def_id.to_def_id(),
+            )?;
+        }
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:518]: I am confused by this :thinking: 

so we're checking some opaque type `fn foo<'a T>() -> impl Foo + 'a` which defines some other opaque `impl Trait<T>`

if `impl Foo` is an RPIT and `type_of(impl Trait<T>).subst(T)`, we call `find_and_apply_rpit_substs` for `impl Trait<T>`. What exactly happens in that function? :thinking: it seems like it always uses a `delay_span_bug`?

do you have a concrete example where `find_and_apply_rpit_substs` is necessary?

File: tests/ui/type-alias-impl-trait/nested-rpit-with-lifetimes.rs [hunk 4]
```diff
@@ -1,6 +1,7 @@
-// check-pass
-
 // Regression test for issue #83190, triggering an ICE in borrowck.
+// ignore-tidy-linelength
```
Comment (lcnr) [inline tests/ui/type-alias-impl-trait/nested-rpit-with-lifetimes.rs:2]: now unnecessary

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 3 above)
Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/check.rs:518]: I guess the comment

> // Get the hidden type, and in case it is in a nested opaque type, find that opaque type's
>    // usage in the function signature and use the generic arguments from the usage site.
 
doesn't really make snese to me :thinking:

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:518]:
```
error: concrete type differs from previous defining opaque type use
  --> /home/ubuntu/rustc/rust2/tests/ui/type-alias-impl-trait/nested-rpit-with-lifetimes.rs:42:84
   |
LL | pub fn metric_stream_parser<'a, I>() -> impl Parser<I, Output = (), PartialState = impl Any + 'a>
   |                                                                                    ^^^^^^^^^^^^^
   |                                                                                    |
   |                                                                                    expected `Map<&ReEarlyBound(DefId(0:39 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::'a), 0, 'a) [()]>`, got `Map<&ReEarlyBound(DefId(0:43 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::{opaque#0}::'a), 2, 'a) [()]>`
   |                                                                                    this expression supplies two conflicting concrete types for the same opaque type
```

from https://github.com/rust-lang/rust/blob/2d0b97c64cdc0eaefbd76f16fb75930c90666e8c/tests/ui/type-alias-impl-trait/nested-rpit-with-lifetimes.rs

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:518]: This all happens during the check_opaque_meets_bounds of `DefId(0:42 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::{opaque#0})` (so the outer RPIT).

`type_of` of the nested opaque type correctly returns

```
Map<&ReEarlyBound(DefId(0:45 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::{opaque#0}::{opaque#0}::'a), 2, 'a) [()]>
```

but this gets then substituted with

```
[
    ReEarlyBound(DefId(0:39 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::'a), 0, 'a),
    I,
    ReEarlyBound(DefId(0:43 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::{opaque#0}::'a), 2, 'a)]
```

which is why we end up with

```
Map<&ReEarlyBound(DefId(0:45 ~ nested_rpit_with_lifetimes[8f41]::metric_stream_parser::{opaque#0}::{opaque#0}::'a), 2, 'a) [()]>
```

instead of the version that is described solely in terms of the function's generics.

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:518]: The issue is that opaque types ignore the lifetimes of the function, as they have their own copies. So the only way to get the lifetimes represented in terms of the function, is to look how they are used in the function signature (or do some other fancy recording of this mapping at hir lowering time).

Ideally we'd not have this lifetime duplication and dance, but that's a separate story.

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 5]
```diff
@@ -464,11 +467,150 @@ fn check_opaque_meets_bounds<'tcx>(
...
+fn find_and_apply_rpit_substs<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    mut hidden_ty: Ty<'tcx>,
+    function: DefId,
+    opaque: DefId,
+) -> Result<Ty<'tcx>, ErrorGuaranteed> {
+    // Find use of the RPIT in the function signature and thus find the right substs to
+    // convert it into the parameter space of the function signature. This is needed,
+    // because that's what `type_of` returns, against which we compare later.
+    let ret = tcx.fn_sig(function).instantiate_identity().output();
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:546]: that one should be `key.args` shouldn't it? but because `key` is always in the context of the function this should be equivalent to the identity substs.

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 6]
```diff
@@ -464,11 +467,150 @@ fn check_opaque_meets_bounds<'tcx>(
...
+    if hidden_ty == ty.ty {
+        Ok(())
+    } else {
+        let span = tcx.def_span(key.def_id);
+        let other = ty::OpaqueHiddenType { ty: hidden_ty, span };
+        Err(ty.report_mismatch(&other, key.def_id, tcx).emit())
+    }
+}
+
+fn find_and_apply_rpit_substs<'tcx>(
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:537]: can you add a doc comment which a minimal example of what this remapping does? something like

```rust
trait Id {
    type Assoc;
}
impl<'a> Id for &'a () {
    type Assoc = &'a ();
} 
fn func<'a>(x: &'a ()) -> impl Id<Assoc = impl Sized + 'a> { x }
// desugared to

type Outer<'a, 'aDup> = impl Id<Assoc = Inner<'a, 'aDup>>;
type Inner<'a, 'aDup> = impl Sized + 'aDup;
fn func<'a>(x: &'a () -> Outer<'a, 'a> { x }
```
- the type of the nested rpit is `&'a ()`
- when checking that `Outer` is wf, we reconstrain `Inner` to `&'aDup ()` which is different
- have to walk the signature of `func` to instantiate `'aDup` with `'a`

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 7]
```diff
@@ -464,11 +467,150 @@ fn check_opaque_meets_bounds<'tcx>(
...
+    });
+    // Get the hidden type.
+    let mut hidden_ty = tcx.type_of(key.def_id).instantiate(tcx, key.args);
+    // In case it is in a nested opaque type, find that opaque type's
+    // usage in the function signature and use the generic arguments from the usage site.
+    // We need to do because RPITs ignore the lifetimes of the function,
+    // as they have their own copies of all the lifetimes they capture.
+    // So the only way to get the lifetimes represented in terms of the function,
+    // is to look how they are used in the function signature (or do some other fancy
+    // recording of this mapping at ast -> hir lowering time).
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:515]: can you apply that comment to `find_and_apply_rpit_substs` instead?

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:546]: No, they are not equivalent to the identity substs. We end up with args like `<'static, 'static, T, U, 'a, 'b>` if the function args are `<'a, 'b, T, U>`.

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 7 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs]: done

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 6 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs]: done

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 8]
```diff
@@ -464,11 +467,173 @@ fn check_opaque_meets_bounds<'tcx>(
...
+///     type Assoc;
+/// }
+/// impl<'a> Id for &'a () {
+///     type Assoc = &'a ();
+/// }
+/// fn func<'a>(x: &'a ()) -> impl Id<Assoc = impl Sized + 'a> { x }
+/// // desugared to
+///
+/// // hidden type is `&'bDup ()`
+/// // During wfcheck the hidden type of `Inner` is `&'a ()`, but
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:550]:
```suggestion
/// // During wfcheck the hidden type of `Inner` is `&'b ()`, but
```
i feel like it is a bit weird to talk about `'bDup` if it is unclear where `'b` comes from. I prefer using `'a` and `'aDup` everywhere

**Review by lcnr — COMMENTED** [review]
r=me after final comment nits

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 8 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:550]: well... unless I double confused myself, your diff is wrong, so it's good that I made it explicit 😆

Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/check.rs:550]: how can the inner type in `wf` check be `'a` if we wf check in the scope of the opaque type which does not have a `'a` in scope? :sweat_smile:

Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs]: because RPITs aren't desugerable currently (ok I guess that's what you meant by "unclear where `'b` comes from"), they only work by construction and are cheating. I rewrote the example to be more like how it actually works, is that clearer?

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 9]
```diff
@@ -545,17 +545,23 @@ fn sanity_check_found_hidden_type<'tcx>(
 /// }
 /// fn func<'a>(x: &'a ()) -> impl Id<Assoc = impl Sized + 'a> { x }
 /// // desugared to
+/// fn func<'a>(x: &'a () -> Outer<'a, Assoc = Inner<'a>> {
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:548]:
```suggestion
/// fn func<'a>(x: &'a () -> Outer<'a, 'a> {
```
? :thinking:

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 10]
```diff
@@ -545,17 +545,23 @@ fn sanity_check_found_hidden_type<'tcx>(
...
-/// // During wfcheck the hidden type of `Inner` is `&'a ()`, but
-/// // `typeof(Inner<'b, 'bDup>) = &'bDup ()`.
-/// // So we walk the signature of `func` to find the use of `Inner<'static, 'a>`
-/// // and then use that to replace the lifetimes in the hidden type, obtaining
-/// // `&'a ()`.
-/// type Outer<'b, 'bDup> = impl Id<Assoc = Inner<'b, 'bDup>>;
-/// // hidden type is `&'cDup ()`
-/// type Inner<'c, 'cDup> = impl Sized + 'cDup;
-/// fn func<'a>(x: &'a () -> Outer<'static, 'a> { x }
+///     // hidden type is `&'aDupOuter ()`
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:552]: This feels wrong, if the hidden type of `Outer` is `&'aDupOuter ()`, shouldn't wf check of `Outer` define the hidden type of `Inner` to be `<&'aDupOuter () as Id>::Assoc` which is `&'aDupOuter ()`, so this should worK?

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 11]
```diff
@@ -545,17 +545,23 @@ fn sanity_check_found_hidden_type<'tcx>(
...
+///     // During wfcheck the hidden type of `Inner<'aDupOuter>` is `&'a ()`, but
+///     // `typeof(Inner<'aDupOuter>) = &'aDupOuter ()`.
+///     // So we walk the signature of `func` to find the use of `Inner<'a>`
+///     // and then use that to replace the lifetimes in the hidden type, obtaining
+///     // `&'a ()`.
+///     type Outer<'aDupOuter> = impl Id<Assoc = Inner<'aDupOuter>>;
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:558]: is the `'a` param of `Inner` `'a` or `'aDupOuter` here?

**Review by lcnr — COMMENTED** [review]
accurately documenting the desugaring is messy (because the desugaring is messy :3)

> because RPITs aren't desugerable currently (ok I guess that's what you meant by "unclear where 'b comes from"), they only work by construction and are cheating. I rewrote the example to be more like how it actually works, is that clearer?

idk :sweat_smile: i don't know how much of my nits are "the actual impl is a mess" and how much is "the comment is wrong/incomplete"

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 11 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:558]: `'a`, it is inherited from the function.

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 10 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/check/check.rs:552]: No, because we figure out the hidden type of `Inner` anew during wf check of `Outer`, we don't get it from `type_of`. We get the hidden type of `Outer`, which is `&'a ()`, so the id projection is also `&'a ()`

File: compiler/rustc_const_eval/src/util/compare_types.rs (hunk 2 above)
Comment (matthiaskrgr) [reply compiler/rustc_const_eval/src/util/compare_types.rs:65]: https://github.com/rust-lang/rust/issues/114121 :D
