### PR TITLE
Fix overflows in the implementation of `overflowing_literals` lint's help

### LINKED ISSUE #131849: ICE: `attempt to negate with overflow`
auto-reduced (treereduce-rust):
````rust
fn main() {
    let fail = -0x8000_0000_0000_0000_0000_0000_0000_0000;
}


````

original:
````rust
//@ check-pass
#![warn(warn)]

fn main() {
    let ok = 0b0111_1111i8; //~WARNING literal out of range for `i8`

    let ok = 0b1000_0001; //~WARNING literal out of range for `i32`
    let ok = 0b0111_1111i8; let fail = 0b1000_0001i8;

    let ok = 0b0111_1111i8; //~WARNING literal out of range for `i8`

    let warn = 0x8000_0000_0000_0000i64; //~WARNING literal out of range for `i64`

    let fail = 0x1_FFFF_FFFFu32;

    let fail: i128 = 0x8000_0000_0000_0000_0000_0000_0000_0000;
    //~^ WARNING literal out of range for `i128`

    let fail = 0x8FFF_FFFF_FFFF_FFFE; //~WARNING literal out of range for `i32`

    let fail = -0x8000_0000_0000_0000_0000_0000_0000_0000; //~WARNING literal out of range for `u32`
}

````

Version information
````
rustc 1.84.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.84.0-dev
LLVM version: 19.1.1

````

Command:
`/home/gh-matthiaskrgr/.rustup/toolchains/local-debug-assertions/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `fail`
 --> /tmp/icemaker_global_tempdir.14MW0MG84wOB/rustc_testrunner_tmpdir_reporting.OtljUIhM5gqz/mvce.rs:2:9
  |
2 |     let fail = -0x8000_0000_0000_0000_0000_0000_0000_0000;
  |         ^^^^ help: if this is intentional, prefix it with an underscore: `_fail`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at compiler/rustc_lint/src/types/literal.rs:207:60:
attempt to negate with overflow
stack backtrace:
   0:     0x741da1f14b92 - std::backtrace_rs::backtrace::libunwind::trace::h7855b9aa31a1fdd2
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x741da1f14b92 - std::backtrace_rs::backtrace::trace_unsynchronized::h03af9d11506e41ca
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x741da1f14b92 - std::sys::backtrace::_print_fmt::h762e2f7c5b14f072
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/sys/backtrace.rs:66:9
   3:     0x741da1f14b92 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd3652af949cc809e
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/sys/backtrace.rs:39:26
   4:     0x741d9cce5180 - core::fmt::rt::Argument::fmt::hfcb22cb88e74be07
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/fmt/rt.rs:177:76
   5:     0x741d9cce5180 - core::fmt::write::hdc12c85fb7bc27ae
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1186:21
   6:     0x741da1eea159 - std::io::Write::write_fmt::h33abbb15cba1432e
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1839:15
   7:     0x741da1f14a33 - std::sys::backtrace::BacktraceLock::print::h461fd87b76bb1219
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/sys/backtrace.rs:42:9
   8:     0x741da1efe08e - std::panicking::default_hook::{{closure}}::h217a27f309d4ed2b
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:268:22
   9:     0x741da1efde3f - std::panicking::default_hook::h148815ff63bbac5c
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:295:9
  10:     0x741d9e1f73ce - rustc_driver_impl[364a9b6195831db8]::install_ice_hook::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1420:17
  11:     0x741d9e1f73ce - <alloc[e90b93fd8de00acc]::boxed::Box<rustc_driver_impl[364a9b6195831db8]::install_ice_hook::{closure#0}> as core[2f0fa1be9e5c8a84]::ops::function::Fn<(&dyn for<'a, 'b> core[2f0fa1be9e5c8a84]::ops::function::Fn<(&'a std[af36d5d97cbedae8]::panic::PanicHookInfo<'b>,), Output = ()> + core[2f0fa1be9e5c8a84]::marker::Send + core[2f0fa1be9e5c8a84]::marker::Sync, &std[af36d5d97cbedae8]::panic::PanicHookInfo)>>::call
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2468:9
  12:     0x741da1efe6cf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd8dc082825511e47
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2468:9
  13:     0x741da1efe6cf - std::panicking::rust_panic_with_hook::h62bcda7ea0f3e4e4
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:809:13
  14:     0x741da1f15246 - std::panicking::begin_panic_handler::{{closure}}::h42392cc45934ee48
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:667:13
  15:     0x741da1f14ea9 - std::sys::backtrace::__rust_end_short_backtrace::h387f12e2427e0125
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/sys/backtrace.rs:170:18
  16:     0x741da1efe18e - rust_begin_unwind
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:665:5
  17:     0x741d9cd036e0 - core::panicking::panic_fmt::ha8bfcd3cb9149158
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:74:14
  18:     0x741d9cd031b0 - core::panicking::panic_const::panic_const_neg_overflow::h0ad9ccc9ba8916a7
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:181:21
  19:     0x741d9f5569ab - rustc_lint[63451d20440e469e]::types::literal::get_type_suggestion
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/types/literal.rs:207:60
  20:     0x741d9f555db8 - rustc_lint[63451d20440e469e]::types::literal::report_bin_hex_error
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/types/literal.rs:147:15
  21:     0x741d9f557641 - rustc_lint[63451d20440e469e]::types::literal::lint_literal
  22:     0x741d9f5fb7e9 - <rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass as rustc_lint[63451d20440e469e]::passes::LateLintPass>::check_expr
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/passes.rs:78:11
  23:     0x741d9f4c5984 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:44:5
  24:     0x741d9f4c5984 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  25:     0x741d9f4c5984 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:172:13
  26:     0x741d9f4c500c - stacker[5532783c75b3bb1e]::maybe_grow::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.17/src/lib.rs:55:9
  27:     0x741d9f4c500c - rustc_data_structures[60b6634d9351b86]::stack::ensure_sufficient_stack::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:21:5
  28:     0x741d9f4c500c - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:171:9
  29:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:174:17
  30:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  31:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:172:13
  32:     0x741d9f4c500c - stacker[5532783c75b3bb1e]::maybe_grow::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.17/src/lib.rs:55:9
  33:     0x741d9f4c500c - rustc_data_structures[60b6634d9351b86]::stack::ensure_sufficient_stack::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:21:5
  34:     0x741d9f4c500c - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:171:9
  35:     0x741d9f4c8fdd - rustc_hir[c4bd56b28b24e439]::intravisit::walk_local::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:632:5
  36:     0x741d9f4c8fdd - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_local::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:245:13
  37:     0x741d9f4c8fdd - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_local::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  38:     0x741d9f4c8fdd - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_local
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:243:9
  39:     0x741d9f4c6672 - rustc_hir[c4bd56b28b24e439]::intravisit::walk_stmt::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:650:37
  40:     0x741d9f4c6672 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_stmt
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:186:9
  41:     0x741d9f616bbc - rustc_hir[c4bd56b28b24e439]::intravisit::walk_block::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:642:5
  42:     0x741d9f616bbc - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_block
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:251:9
  43:     0x741d9f616bbc - rustc_hir[c4bd56b28b24e439]::intravisit::walk_expr::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:825:24
  44:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:174:17
  45:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  46:     0x741d9f4c598f - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:172:13
  47:     0x741d9f4c500c - stacker[5532783c75b3bb1e]::maybe_grow::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.17/src/lib.rs:55:9
  48:     0x741d9f4c500c - rustc_data_structures[60b6634d9351b86]::stack::ensure_sufficient_stack::<(), <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:21:5
  49:     0x741d9f4c500c - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_expr
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:171:9
  50:     0x741d9f4c36e1 - rustc_hir[c4bd56b28b24e439]::intravisit::walk_body::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:591:5
  51:     0x741d9f4c36e1 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_body
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:131:9
  52:     0x741d9f4c36e1 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_nested_body
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:114:9
  53:     0x741d9f4c6ab8 - rustc_hir[c4bd56b28b24e439]::intravisit::walk_fn::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:1020:5
  54:     0x741d9f4c6ab8 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_fn
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:203:9
  55:     0x741d9f619517 - rustc_hir[c4bd56b28b24e439]::intravisit::walk_item::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:518:24
  56:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:143:17
  57:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_param_env::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:82:9
  58:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_item::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:141:13
  59:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_item::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  60:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_item
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:140:9
  61:     0x741d9f4bd304 - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass> as rustc_hir[c4bd56b28b24e439]::intravisit::Visitor>::visit_nested_item
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:248:24
  62:     0x741d9f4cbf5c - rustc_hir[c4bd56b28b24e439]::intravisit::walk_mod::<rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_hir/src/intravisit.rs:604:5
  63:     0x741d9f4cbf5c - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::process_mod
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:88:9
  64:     0x741d9f4cbf5c - rustc_lint[63451d20440e469e]::late::late_lint_mod_inner::<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:391:12
  65:     0x741d9f4cbf5c - <rustc_lint[63451d20440e469e]::late::LateContextAndPass<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<rustc_lint[63451d20440e469e]::late::late_lint_mod_inner<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:70:9
  66:     0x741d9f4cbf5c - rustc_lint[63451d20440e469e]::late::late_lint_mod_inner::<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:385:5
  67:     0x741d9f4cbf5c - rustc_lint[63451d20440e469e]::late::late_lint_mod::<rustc_lint[63451d20440e469e]::BuiltinCombinedModuleLateLintPass>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:366:9
  68:     0x741d9f5ddb32 - rustc_lint[63451d20440e469e]::lint_mod
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/lib.rs:155:5
  69:     0x741da0abe7b4 - rustc_query_impl[d02c6541067d457]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:283:9
  70:     0x741da0abe7b4 - rustc_query_impl[d02c6541067d457]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d02c6541067d457]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:548:18
  71:     0x741da0bb15bb - rustc_query_impl[d02c6541067d457]::query_impl::lint_mod::dynamic_query::{closure#2}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:622:25
  72:     0x741da0bb15bb - <rustc_query_impl[d02c6541067d457]::query_impl::lint_mod::dynamic_query::{closure#2} as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<(rustc_middle[a748918beb6e17f]::ty::context::TyCtxt, rustc_span[c842a03fb37cf609]::def_id::LocalModDefId)>>::call_once
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  73:     0x741da09c81ba - <rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false> as rustc_query_system[7ade8590af992972]::query::config::QueryConfig<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>>::compute
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:110:9
  74:     0x741da09c81ba - rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:478:72
  75:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::enter_context::<rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  76:     0x741da09c81ba - <std[af36d5d97cbedae8]::thread::local::LocalKey<core[2f0fa1be9e5c8a84]::cell::Cell<*const ()>>>::try_with::<rustc_middle[a748918beb6e17f]::ty::context::tls::enter_context<rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:283:12
  77:     0x741da09c81ba - <std[af36d5d97cbedae8]::thread::local::LocalKey<core[2f0fa1be9e5c8a84]::cell::Cell<*const ()>>>::with::<rustc_middle[a748918beb6e17f]::ty::context::tls::enter_context<rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:260:9
  78:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::enter_context::<rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:9
  79:     0x741da09c81ba - <rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query::<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:151:13
  80:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::with_related_context::<<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:134:9
  81:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::with_context::<rustc_middle[a748918beb6e17f]::ty::context::tls::with_related_context<<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:112:36
  82:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::with_context_opt::<rustc_middle[a748918beb6e17f]::ty::context::tls::with_context<rustc_middle[a748918beb6e17f]::ty::context::tls::with_related_context<<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:101:18
  83:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::with_context::<rustc_middle[a748918beb6e17f]::ty::context::tls::with_related_context<<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:112:5
  84:     0x741da09c81ba - rustc_middle[a748918beb6e17f]::ty::context::tls::with_related_context::<<rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:125:5
  85:     0x741da09c81ba - <rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt as rustc_query_system[7ade8590af992972]::query::QueryContext>::start_query::<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:136:9
  86:     0x741da09c81ba - rustc_query_system[7ade8590af992972]::query::plumbing::execute_job_non_incr::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:478:18
  87:     0x741da09c81ba - rustc_query_system[7ade8590af992972]::query::plumbing::execute_job::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt, false>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:414:9
  88:     0x741da09c81ba - rustc_query_system[7ade8590af992972]::query::plumbing::try_execute_query::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt, false>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:357:13
  89:     0x741da0ef6859 - rustc_query_system[7ade8590af992972]::query::plumbing::get_query_non_incr::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:809:32
  90:     0x741da0ef6859 - stacker[5532783c75b3bb1e]::maybe_grow::<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::get_query_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/gh-matthiaskrgr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.17/src/lib.rs:55:9
  91:     0x741da0ef6859 - rustc_data_structures[60b6634d9351b86]::stack::ensure_sufficient_stack::<rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[7ade8590af992972]::query::plumbing::get_query_non_incr<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:21:5
  92:     0x741da0ef6859 - rustc_query_system[7ade8590af992972]::query::plumbing::get_query_non_incr::<rustc_query_impl[d02c6541067d457]::DynamicConfig<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d02c6541067d457]::plumbing::QueryCtxt>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:809:5
  93:     0x741da0ef6859 - rustc_query_impl[d02c6541067d457]::query_impl::lint_mod::get_query_non_incr::__rust_end_short_backtrace
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:598:26
  94:     0x741d9f6cdd07 - rustc_middle[a748918beb6e17f]::query::plumbing::query_ensure::<rustc_query_system[7ade8590af992972]::query::caches::DefaultCache<rustc_span[c842a03fb37cf609]::def_id::LocalModDefId, rustc_middle[a748918beb6e17f]::query::erase::Erased<[u8; 0usize]>>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:159:9
  95:     0x741d9f6cdd07 - <rustc_middle[a748918beb6e17f]::query::plumbing::TyCtxtEnsure>::lint_mod
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:194:9
  96:     0x741d9f6cdd07 - rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:452:56
  97:     0x741d9f6cdd07 - <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module::<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/hir/map/mod.rs:481:13
  98:     0x741d9f6b8abd - rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in::<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:183:34
  99:     0x741d9f6b8abd - <core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}> as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<()>>::call_once
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:272:9
 100:     0x741d9f6b8abd - std[af36d5d97cbedae8]::panicking::try::do_call::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:557:40
 101:     0x741d9f6b8abd - std[af36d5d97cbedae8]::panicking::try::<(), core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:520:19
 102:     0x741d9f6b8abd - std[af36d5d97cbedae8]::panic::catch_unwind::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panic.rs:358:14
 103:     0x741d9f6b8abd - <rustc_data_structures[60b6634d9351b86]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:29:9
 104:     0x741d9f46fdfe - rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in::<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:187:21
 105:     0x741d9f46fdfe - <core[2f0fa1be9e5c8a84]::slice::iter::Iter<rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId> as core[2f0fa1be9e5c8a84]::iter::traits::iterator::Iterator>::for_each::<rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/slice/iter/macros.rs:254:21
 106:     0x741d9f46fdfe - rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in::<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:186:17
 107:     0x741d9f46fdfe - rustc_data_structures[60b6634d9351b86]::sync::parallel::parallel_guard::<(), rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:45:15
 108:     0x741d9f46fdfe - rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::par_for_each_in::<&rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId, &[rustc_hir[c4bd56b28b24e439]::hir_id::OwnerId], <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:179:9
 109:     0x741d9f46fdfe - <rustc_middle[a748918beb6e17f]::hir::map::Map>::par_for_each_module::<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/hir/map/mod.rs:480:9
 110:     0x741d9f46fdfe - rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:452:17
 111:     0x741d9f46fdfe - <rustc_data_structures[60b6634d9351b86]::profiling::VerboseTimingGuard>::run::<(), rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:753:9
 112:     0x741d9f46fdfe - <rustc_session[e0a613f434d16234]::session::Session>::time::<(), rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:16:9
 113:     0x741d9f6cc225 - rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:450:13
 114:     0x741d9f6cc225 - <core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}> as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<()>>::call_once
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:272:9
 115:     0x741d9f6cc225 - std[af36d5d97cbedae8]::panicking::try::do_call::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:557:40
 116:     0x741d9f6cc225 - std[af36d5d97cbedae8]::panicking::try::<(), core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:520:19
 117:     0x741d9f6cc225 - std[af36d5d97cbedae8]::panic::catch_unwind::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panic.rs:358:14
 118:     0x741d9f6cc225 - <rustc_data_structures[60b6634d9351b86]::sync::parallel::ParallelGuard>::run::<(), rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:29:9
 119:     0x741d9f6cc225 - rustc_data_structures[60b6634d9351b86]::sync::parallel::disabled::join::<rustc_lint[63451d20440e469e]::late::check_crate::{closure#0}, rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}, (), ()>::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:72:21
 120:     0x741d9f6cc225 - rustc_data_structures[60b6634d9351b86]::sync::parallel::parallel_guard::<(core[2f0fa1be9e5c8a84]::option::Option<()>, core[2f0fa1be9e5c8a84]::option::Option<()>), rustc_data_structures[60b6634d9351b86]::sync::parallel::disabled::join<rustc_lint[63451d20440e469e]::late::check_crate::{closure#0}, rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}, (), ()>::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:45:15
 121:     0x741d9f6cc225 - rustc_data_structures[60b6634d9351b86]::sync::parallel::disabled::join::<rustc_lint[63451d20440e469e]::late::check_crate::{closure#0}, rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}, (), ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:70:22
 122:     0x741d9f4cd114 - rustc_data_structures[60b6634d9351b86]::sync::parallel::enabled::join::<rustc_lint[63451d20440e469e]::late::check_crate::{closure#0}, rustc_lint[63451d20440e469e]::late::check_crate::{closure#1}, (), ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:169:13
 123:     0x741d9f4cd114 - rustc_lint[63451d20440e469e]::late::check_crate
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_lint/src/late.rs:442:5
 124:     0x741d9f3d020a - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:961:29
 125:     0x741d9f3d020a - <rustc_data_structures[60b6634d9351b86]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:753:9
 126:     0x741d9f3d020a - <rustc_session[e0a613f434d16234]::session::Session>::time::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:16:9
 127:     0x741d9f3d020a - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:960:25
 128:     0x741d9f3d020a - <core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}> as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<()>>::call_once
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:272:9
 129:     0x741d9f3d020a - std[af36d5d97cbedae8]::panicking::try::do_call::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:557:40
 130:     0x741d9f3d020a - std[af36d5d97cbedae8]::panicking::try::<(), core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:520:19
 131:     0x741d9f3d020a - std[af36d5d97cbedae8]::panic::catch_unwind::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panic.rs:358:14
 132:     0x741d9f3d020a - <rustc_data_structures[60b6634d9351b86]::sync::parallel::ParallelGuard>::run::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}::{closure#2}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:29:9
 133:     0x741d9f3d020a - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:136:23
 134:     0x741d9f3d020a - rustc_data_structures[60b6634d9351b86]::sync::parallel::parallel_guard::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:45:15
 135:     0x741d9f3d020a - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:951:17
 136:     0x741d9f3d020a - <core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}> as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<()>>::call_once
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:272:9
 137:     0x741d9f3d020a - std[af36d5d97cbedae8]::panicking::try::do_call::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:557:40
 138:     0x741d9f3d020a - std[af36d5d97cbedae8]::panicking::try::<(), core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}>>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:520:19
 139:     0x741d9f3d020a - std[af36d5d97cbedae8]::panic::catch_unwind::<core[2f0fa1be9e5c8a84]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}>, ()>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/panic.rs:358:14
 140:     0x741d9f3d020a - <rustc_data_structures[60b6634d9351b86]::sync::parallel::ParallelGuard>::run::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:29:9
 141:     0x741d9f4208ea - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:135:21
 142:     0x741d9f4208ea - rustc_data_structures[60b6634d9351b86]::sync::parallel::parallel_guard::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}::{closure#1}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync/parallel.rs:45:15
 143:     0x741d9f4208ea - rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:947:9
 144:     0x741d9f4208ea - <rustc_data_structures[60b6634d9351b86]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[9426b5d1349fc209]::passes::analysis::{closure#0}>
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:753:9
 <snip>
 197:     0x741d9e2e8f9a - <std[af36d5d97cbedae8]::thread::Builder>::spawn_unchecked_::<rustc_interface[9426b5d1349fc209]::util::run_in_thread_with_globals<rustc_interface[9426b5d1349fc209]::util::run_in_thread_pool_with_globals<rustc_interface[9426b5d1349fc209]::interface::run_compiler<core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>, rustc_driver_impl[364a9b6195831db8]::run_compiler::{closure#0}>::{closure#1}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#0}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#1}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:537:30
 198:     0x741d9e2e8f9a - <<std[af36d5d97cbedae8]::thread::Builder>::spawn_unchecked_<rustc_interface[9426b5d1349fc209]::util::run_in_thread_with_globals<rustc_interface[9426b5d1349fc209]::util::run_in_thread_pool_with_globals<rustc_interface[9426b5d1349fc209]::interface::run_compiler<core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>, rustc_driver_impl[364a9b6195831db8]::run_compiler::{closure#0}>::{closure#1}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#0}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2f0fa1be9e5c8a84]::result::Result<(), rustc_span[c842a03fb37cf609]::ErrorGuaranteed>>::{closure#1} as core[2f0fa1be9e5c8a84]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
 199:     0x741da1f44f74 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf65aff6f5bc546f0
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2454:9
 200:     0x741da1f44f74 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7ce25e38e60144e6
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2454:9
 201:     0x741da1f44f74 - std::sys::pal::unix::thread::Thread::new::thread_start::heac156426d37e7c7
                               at /home/gh-matthiaskrgr/vcs/github/rust_debug_assertions/library/std/src/sys/pal/unix/thread.rs:105:17
 202:     0x741d9969ca94 - start_thread
                               at ./nptl/pthread_create.c:447:8
 203:     0x741d99729c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
 204:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.84.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 1 warning emitted


```

</p>
</details>

### LINKED ISSUE #135248: Wrong type suggested for `overflowing_literals` when the number is big
### Code

```Rust
fn main() {
    _ = 340282366920938463463374607431768211455;
}
```

### Current output

```Shell
error: literal out of range for `i32`
 --> src/main.rs:2:9
  |
2 |     _ = 340282366920938463463374607431768211455;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the literal `340282366920938463463374607431768211455` does not fit into the type `i32` whose range is `-2147483648..=2147483647`
  = help: consider using the type `i8` instead
  = note: `#[deny(overflowing_literals)]` on by default
```

### Desired output

```Shell
error: literal out of range for `i32`
 --> src/main.rs:2:9
  |
2 |     _ = 340282366920938463463374607431768211455;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the literal `340282366920938463463374607431768211455` does not fit into the type `i32` whose range is `-2147483648..=2147483647`
  = help: consider using the type `u128` instead
  = note: `#[deny(overflowing_literals)]` on by default
```

### Rationale and extra context

The help currently suggest to use a overly small type `i8` instead of the only fitting type `u128`.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by s-cerevisiae**
This PR fixes two overflow problems that cause the `overflowing_literals` lint to behave incorrectly in some edge cases.

1. When an integer literal is between `i128::MAX` and `u128::MAX`, an overflowing `as` cast can cause the suggested type to be overly small. It's fixed by using checked type conversion and returning `u128` when it's the only choice. (Fixes #135248)
2. When an integer literal is `i128::MIN` but is of a smaller type, an overflowing negation cause the compiler to panic in debug build. Fixed by checking the number size beforehand and `wrapping_neg`. (Fixes #131849)

Edit: extracted the type conversion part into a standalone function to separate the concern of overflowing.

### CODE REVIEW

File: tests/ui/lint/type-overflow.rs [hunk 1]
```diff
@@ -3,20 +3,46 @@
...
 
     let fail = 0x1_FFFF_FFFFu32; //~WARNING literal out of range for `u32`
+    //~^ HELP consider using the type `u64` instead
 
     let fail: i128 = 0x8000_0000_0000_0000_0000_0000_0000_0000;
     //~^ WARNING literal out of range for `i128`
+    //~| HELP consider using the type `u128` instead
+    //~| HELP consider using the type `u128` for the literal and cast it to `i128`
+
+    let fail = 0x8000_0000_0000_0000_0000_0000_0000_0000;
```
Comment (chenyukang) [inline tests/ui/lint/type-overflow.rs:27]: it's better to add comments to mark this case is from: 
#131849

**Comment by chenyukang** [comment]
Please add:
```
Fixes #135399 
Fixes #131849
```
in the PR description so that the two issue will be closed after PR merged.

**Comment by chenyukang** [comment]
seems we does not find the proper type for different range of number literals , for example:

```
let _ = 18446744073709551614;
```
the value is `u64::MAX - 1`, the current suggestion is:

```console
  |
3 |     let _ = 18446744073709551614;
  |             ^^^^^^^^^^^^^^^^^^^^
  |
  = note: the literal `18446744073709551614` does not fit into the type `i32` whose range is `-2147483648..=2147483647`
  = help: consider using the type `i128` instead
```

maybe better choice is suggesting `u64`.

**Comment by s-cerevisiae** [comment]
@chenyukang I preserved the original behavior which is to suggest types with the same signedness unless the value fits into an unsigned number of the same size. I was rather reluctant to change the suggestion logic in this PR, but if you feel that it's ok to do here I'll change it so that it always suggests the smallest fitting type.

File: tests/ui/lint/type-overflow.rs (hunk 1 above)
Comment (s-cerevisiae) [reply tests/ui/lint/type-overflow.rs:27]: Done, thanks for the suggestion.

**Comment by s-cerevisiae** [comment]
Done implementing that too. Hope that there was no special reason for the old, less straightforward behavior.
