### PR TITLE
`UnsafeCell` blocks niches inside its nested type from being available outside

### LINKED ISSUE #87341: Niches of `Cell` and others still not hidden
Original conversation can be found in [this IRLO thread](https://internals.rust-lang.org/t/documenting-more-layout-guarantees/15032/), including a request from @RalfJung to file a bug report.

[PR 68491](https://github.com/rust-lang/rust/pull/68491) was accepted to hide niches of types that are in an `UnsafeCell`.  However, experiments show that niches are still exposed within `Cell`, `Mutex`, and others.

[Consider this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=379bcc49bb7c097d3055426e3e2c53e6), adapted from a playground by @SkiFire13.  It currently runs on the playground without panicking and [optimizes down to a `ret` in the Godbolt explorer](https://rust.godbolt.org/z/cM9W1f335).
```rust
    assert_eq!( 8, mem::size_of::<       UnsafeCell<&()> >()); //  8
    assert_eq!(16, mem::size_of::<Option<UnsafeCell<&()>>>()); // 16 (✗ niche opt)
    assert_eq!( 8, mem::size_of::<             Cell<&()> >()); //  8
    assert_eq!( 8, mem::size_of::<Option<      Cell<&()>>>()); //  8 (✓ niche opt)
    assert_eq!(16, mem::size_of::<          RefCell<&()> >()); // 16
    assert_eq!(24, mem::size_of::<Option<   RefCell<&()>>>()); // 24 (✗ niche opt)
    assert_eq!(24, mem::size_of::<           RwLock<&()> >()); // 24
    assert_eq!(24, mem::size_of::<Option<    RwLock<&()>>>()); // 24 (✓ niche opt)
    assert_eq!(24, mem::size_of::<            Mutex<&()> >()); // 24
    assert_eq!(24, mem::size_of::<Option<     Mutex<&()>>>()); // 24 (✓ niche opt)
```

I would have expected `Option<Cell<&()>>` to not exhibit the niche-exploiting size optimization.  The `RwLock` and `Mutex` cases may or may not be problematic, depending on their platform-specific implementations.  But `Cell` in particular is a `#[repr(transparent)]` wrapper around `UnsafeCell`.

[Here is another playground by @SkiFire13](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cb794479d139acda2e3a867dafa1ac90) from which [they observed](https://internals.rust-lang.org/t/documenting-more-layout-guarantees/15032/13):
> Even more interesting, looks like the current behaviour of a type that contains an `UnsafeCell` is to allow niche optimizations only if it doesn't contains something else before the `UnsafeCell`, and that something is not a ZST. 

This indicates that the behavior is not `Cell`-specific.  And although there has been some discussion about revealing the niches for `Cell` in particular, the discussion in the PR and in [this hackmd](https://hackmd.io/7rk-0h8WTqKQgaWB6aaeaw) seem to indicate that the niches being exploited is not intentional, even for `Cell`.  [The behavior can be observed back until Rust 1.43](https://rust.godbolt.org/z/4h55adY5o) when the PR landed.

### Meta
Current playground (all versions) and Godbolt on all versions I tried from 1.43 forward.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #87341

This implements the plan by @eddyb in https://github.com/rust-lang/rust/issues/87341#issuecomment-886083646

Somewhat related PR (not strictly necessary, but that cleanup made this PR simpler): #94527

### CODE REVIEW

File: compiler/rustc_lint/src/types.rs [hunk 1]
```diff
@@ -705,7 +705,7 @@ fn ty_is_known_nonnull<'tcx>(cx: &LateContext<'tcx>, ty: Ty<'tcx>, mode: CItemKi
 
             // Types with a `#[repr(no_niche)]` attribute have their niche hidden.
```
Comment (Nilstrieb) [inline compiler/rustc_lint/src/types.rs:706]: This comment should probably be adjusted as well.

File: library/core/src/cell.rs [hunk 2]
```diff
@@ -1856,7 +1856,6 @@ impl<T: ?Sized + fmt::Display> fmt::Display for RefMut<'_, T> {
 #[lang = "unsafe_cell"]
 #[stable(feature = "rust1", since = "1.0.0")]
 #[repr(transparent)]
-#[repr(no_niche)] // rust-lang/rust#68303.
```
Comment (RalfJung) [inline library/core/src/cell.rs:1859]: Why did you decide to go for hard-coding this on `UnsafeCell`, rather than an attribute?

**Comment by RalfJung** [comment]
Please make sure this is covered by tests. https://github.com/rust-lang/rust/issues/87341 has a nice test set at the top.

**Review by eddyb — CHANGES_REQUESTED** [review]
LGTM (modulo the comment I left about handling all `Abi`s, and tests ofc).

IMO limiting this to `UnsafeCell` is more reasonable than `#[repr(no_niche)]`.

The question I ask myself is: why would anyone want `#[repr(no_niche)]` *without* the semantics of `UnsafeCell` and/or `MaybeUninit`?

I can only think of layout/ABI misuses (that would be defeated by layout randomization), I can't imagine that there's a way to have unsafe code that would *only* need `#[repr(no_niche)]` (and *nothing else*) to both have no UB, and work under layout randomization.

**Comment by RalfJung** [comment]
>      I didn't add those as we already had equivalent tests in 

That test already passed before this PR. So it cannot be testing the right thing.

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 3]
```diff
@@ -18,12 +19,23 @@ struct NoNiche<T>(UnsafeCell<T>);
...
+    assert_eq!(size_of::<Option<Transparent<N32>>>(), 4); // (✓ niche opt)
     assert_eq!(size_of::<Option<NoNiche<u32>>>(),     8);
-    assert_eq!(size_of::<Option<NoNiche<N32>>>(),     8);
+    assert_eq!(size_of::<Option<NoNiche<N32>>>(),     8); // (✗ niche opt)
 
     assert_eq!(size_of::<Option<UnsafeCell<u32>>>(),  8);
-    assert_eq!(size_of::<Option<UnsafeCell<N32>>>(),  8);
+    assert_eq!(size_of::<Option<UnsafeCell<N32>>>(),  8); // (✗ niche opt)
+
+    assert_eq!(size_of::<       UnsafeCell<&()> >(), 8);
```
Comment (RalfJung) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:31]: How does this pass on 32bit targets... :thinking:

File: compiler/rustc_middle/src/ty/layout.rs [hunk 4]
```diff
@@ -1104,23 +1102,29 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
...
-                                None
+                            if def.is_unsafe_cell() {
+                                match scalar {
+                                    Scalar::Initialized { value, valid_range } => {
+                                        *valid_range = WrappingRange::full(value.size(dl))
+                                    }
+                                    // Already doesn't have any niches
+                                    Scalar::Union { .. } => {}
+                                }
+                                st.largest_niche = None;
```
[the remark this answers is not in the document]
Comment (eddyb) [reply compiler/rustc_middle/src/ty/layout.rs]: The checks are not perfect: https://godbolt.org/z/W8o3Gxhdo.

File: compiler/rustc_middle/src/ty/layout.rs [hunk 5]
```diff
@@ -1078,6 +1076,34 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
...
+                            Abi::ScalarPair(a, b) => {
+                                fill(a);
+                                fill(b);
+                            }
+                            Abi::Vector { element, count: _ } => {
+                                // Until we support types other than floats and integers in SIMD,
+                                // `element` must already be a full for its range, so there's nothing to
+                                // do here.
+                                assert!(element.is_always_valid(dl));
+                            }
```
Comment (eddyb) [inline compiler/rustc_middle/src/ty/layout.rs:1100]: As per the other comment, all it takes is generics (https://godbolt.org/z/W8o3Gxhdo):
```rust
#[repr(simd)]
pub struct Vec4<T>([T; 4]);

pub fn ones() -> Vec4<NonZeroU8> {
    Vec4([NonZeroU8::new(1).unwrap(); 4])
}
```

File: compiler/rustc_middle/src/ty/layout.rs [hunk 6]
```diff
@@ -1078,6 +1076,34 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
 
                     let mut st = self.univariant_uninterned(ty, &variants[v], &def.repr(), kind)?;
                     st.variants = Variants::Single { index: v };
+
+                    if def.is_unsafe_cell() {
+                        let fill = |scalar: &mut _| match scalar {
```
Comment (eddyb) [inline compiler/rustc_middle/src/ty/layout.rs:1081]: Could use a comment, and/or `fill` being renamed to `hide_niches`.

File: src/test/ui/layout/unsafe-cell-hides-niche.rs (hunk 3 above)
Comment (eddyb) [reply src/test/ui/layout/unsafe-cell-hides-niche.rs:31]: Heh, yeah, the values should be replaced with e.g. `size_of::<usize>() * 3` instead of `24`.

(Could use a `const` for `size_of::<usize>()` instead of leaving it inline, tho I can't think of a good name)

Comment (RalfJung) [reply src/test/ui/layout/unsafe-cell-hides-niche.rs:31]: The thing is, CI passes on this PR, and that should run 32bit tests as well... right? Or does it just check-pass them all?

Comment (eddyb) [reply src/test/ui/layout/unsafe-cell-hides-niche.rs:31]: > Or does it just check-pass them all?

Looks like it: https://github.com/rust-lang/rust/blob/06754d8852bea286a3a76d373ccd17e66afb5a8b/src/ci/docker/host-x86_64/x86_64-gnu-llvm-12/Dockerfile#L37-L51

(theoretically we could move asserts like these from `fn main() {...}` to a `const _: () = {...};` though only by redefining `assert_eq!($a:expr, $b:expr)` to be `assert!($a == $b)`, without the value printing)

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 7]
```diff
@@ -17,34 +19,51 @@ struct Transparent<T>(T);
...
+    assert_size!(       UnsafeCell<&()> , PTR_SIZE);
+    assert_size!(Option<UnsafeCell<&()>>, PTR_SIZE * 2); // (✗ niche opt)
+    assert_size!(             Cell<&()> , PTR_SIZE);
+    assert_size!(Option<      Cell<&()>>, PTR_SIZE * 2); // (✗ niche opt)
+    assert_size!(          RefCell<&()> , PTR_SIZE * 2);
+    assert_size!(Option<   RefCell<&()>>, PTR_SIZE * 3); // (✗ niche opt)
+    assert_size!(           RwLock<&()> , if cfg!(target_pointer_width = "32") { 16 } else { 24 });
+    assert_size!(Option<    RwLock<&()>>, if cfg!(target_pointer_width = "32") { 20 } else { 32 }); // (✗ niche opt)
+    assert_size!(            Mutex<&()> , if cfg!(target_pointer_width = "32") { 12 } else { 16 });
+    assert_size!(Option<     Mutex<&()>>, if cfg!(target_pointer_width = "32") { 16 } else { 24 }); // (✗ niche opt)
```
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs]: I'm worried this is actually observing weird platform-specific details.
We might want to make a helper function that asserts `Option<T>` is larger than `T` and use it everywhere in this module *before* checking the exact sizes (do they even matter? I guess it's good to have them be tested to some extent).

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 8]
```diff
@@ -17,34 +19,51 @@ struct Transparent<T>(T);
...
+// Overwriting the runtime assertion and making it a compile-time assertion
+macro_rules! assert_size {
+    ($a:ty, $b:expr) => {{
+        const _: Size::<{$b}> = Size::<{size_of::<$a>()}>;
+    }};
+}
+
+const PTR_SIZE: usize = std::mem::size_of::<*const ()>();
+
 fn main() {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/layout/unsafe-cell-hides-niche.rs:33]: yea... initially I wanted to keep the diff small, but I have given up half way, without going all the way

**Comment by eddyb** [comment]
@RalfJung @oli-obk By [running the test on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=19343a9f8746e212d5294924d47045c7) it's possible to find out how useful it is in detecting the issues we have currently.

Only `NoNiche` and `Cell` (both of which are newtyping `UnsafeCell`) appear to be actually observing the (subtler) issue that PR fixes.

(Should `NoNiche` be named `UnsafeCellNewtype`? Or we can even use `Wrapper<UnsafeCell<T>>` heh)

So maybe wherever `UnsafeCell` is tested, `Cell` should be tested too, at least?

I can't actually get it to fail on nightly except with scalars (since turning an `Abi::Scalar` back into a niche is easier than `Abi::{ScalarPair,Vector}`, I guess), but we should probably make sure `Cell` (if not also `NoNiche`/etc.) is tested with every type `UnsafeCell` is.

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 9]
```diff
@@ -3,30 +3,73 @@
...
-    assert_eq!(size_of::<Option<Wrapper<N32>>>(),     4);
-    assert_eq!(size_of::<Option<Transparent<u32>>>(), 8);
-    assert_eq!(size_of::<Option<Transparent<N32>>>(), 4);
-    assert_eq!(size_of::<Option<NoNiche<u32>>>(),     8);
-    assert_eq!(size_of::<Option<NoNiche<N32>>>(),     8);
+struct Size<const S: usize>;
 
-    assert_eq!(size_of::<Option<UnsafeCell<u32>>>(),  8);
-    assert_eq!(size_of::<Option<UnsafeCell<N32>>>(),  8);
+// Overwriting the runtime assertion and making it a compile-time assertion
```
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:25]: Not sure about this comment.

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 10]
```diff
@@ -3,30 +3,73 @@
...
+macro_rules! assert_size_eq {
+    ($ty:ty, $size:expr) => {
+        const _: Size::<{$size}> = Size::<{size_of::<$ty>()}>;
+    };
+    ($ty:ty, $size:expr, $optioned_size:expr) => {
+        assert_size_eq!($ty, $size);
+        assert_size_eq!(Option<$ty>, $optioned_size);
+        const _: () = assert!(
+            $size == $optioned_size ||
+            size_of::<$ty>() < size_of::<Option<$ty>>()
```
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:35]: So the reason I brought this up is that this is *the only* check we can use in the cases where you added `if cfg!(target_pointer_width = `.

My understanding is that the size of e.g. `Mutex<()>` varies with *operating system*, not (just) `target_pointer_width`.

**Review by eddyb — CHANGES_REQUESTED** [review]

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 11]
```diff
@@ -3,30 +3,73 @@
...
+struct Size<const S: usize>;
 
-    assert_eq!(size_of::<Option<UnsafeCell<u32>>>(),  8);
-    assert_eq!(size_of::<Option<UnsafeCell<N32>>>(),  8);
+// Overwriting the runtime assertion and making it a compile-time assertion
+macro_rules! assert_size_eq {
+    ($ty:ty, $size:expr) => {
+        const _: Size::<{$size}> = Size::<{size_of::<$ty>()}>;
+    };
+    ($ty:ty, $size:expr, $optioned_size:expr) => {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/layout/unsafe-cell-hides-niche.rs:29]: I made the variants more explicit

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 12]
```diff
@@ -3,30 +3,68 @@
...
+check_sizes!(UnsafeCell<&[i32]> , PTR_SIZE * 2, PTR_SIZE * 3);
+check_sizes!(UnsafeCell<(&(), &())> , PTR_SIZE * 2, PTR_SIZE * 3);
+
+trait Trait {}
+check_sizes!(UnsafeCell<&dyn Trait> , PTR_SIZE * 2, PTR_SIZE * 3);
+
+#[repr(simd)]
+pub struct Vec4<T>([T; 4]);
+
+check_sizes!(UnsafeCell<Vec4<N32>> , 16, 32);
```
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:70]: Is the space before `,` intentional?

File: src/test/ui/layout/unsafe-cell-hides-niche.rs [hunk 13]
```diff
@@ -3,30 +3,68 @@
...
+
+check_sizes!(UnsafeCell<&()> , PTR_SIZE, PTR_SIZE * 2);
+check_sizes!(      Cell<&()> , PTR_SIZE, PTR_SIZE * 2);
+check_sizes!(   RefCell<&()> , PTR_SIZE * 2, PTR_SIZE * 3);
+
+check_sizes!(RwLock<&()>);
+check_sizes!(Mutex<&()>);
+
+check_sizes!(UnsafeCell<&[i32]> , PTR_SIZE * 2, PTR_SIZE * 3);
+check_sizes!(UnsafeCell<(&(), &())> , PTR_SIZE * 2, PTR_SIZE * 3);
```
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:62]: As per https://github.com/rust-lang/rust/pull/99011#issuecomment-1180467909 it would be nice to duplicate these at least for `Cell`.

File: src/test/ui/layout/unsafe-cell-hides-niche.rs (hunk 12 above)
Comment (eddyb) [inline src/test/ui/layout/unsafe-cell-hides-niche.rs:70]: As per https://github.com/rust-lang/rust/pull/99011#issuecomment-1180467909 it would be nice to duplicate this at least for `Cell`.

**Review by eddyb — CHANGES_REQUESTED** [review]
r=me after adding `Cell` versions of several testcases (as per https://github.com/rust-lang/rust/pull/99011#issuecomment-1180467909)

(and maybe fixing the commas, if they're not intentional - if you want a more distinct separator, maybe something like `=>` could work better than `,`?)
