### PR TITLE
std: Properly handle interior NULs in std::process

### LINKED ISSUE #30858: Undocumented panics in std::process on unix for strings with interior nuls
All the strings are taken as `AsRef<OsStr>` and converted to `CString` with unwrapping: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/process.rs#L83-L85

An example for `Command::new` ([playground](http://is.gd/5dGAxO)):

```
use std::process::Command;

fn main() {
    Command::new("\0");
}
```

The panic should be documented, or the conversion unwrap should be delayed until a call to one of the methods that start the process so that the error can be returned in a `Result`.

Version:
```
$ rustc --version --verbose
rustc 1.5.0 (3d7cd77e4 2015-12-04)
binary: rustc
commit-hash: 3d7cd77e442ce34eaac8a176ae8be17669498ebc
commit-date: 2015-12-04
host: x86_64-unknown-linux-gnu
release: 1.5.0
```

### LINKED ISSUE #30862: Setting process env vars with interior nuls leads to unexpected env for child
[Noticed by @talchas](https://github.com/rust-lang/rust/issues/30858#issuecomment-171048969) when discussing #30858.

The environment variables are never checked for interior nuls. This leads to very unexpected results in the child's env. Keys with interior nuls are truncated and have no values, and values are truncated at the nul:

```
use std::process::Command;

fn main() {
    Command::new("/usr/bin/env").env("a\0b", "c\0d")
                                .env("ab", "c\0d")
                                .status()
                                .unwrap();
}
```
([playground](http://is.gd/swL9IL))

Output:
```
a
ab=c
USER=rust
HOME=/home/rust
PATH=/usr/local/bin:/usr/bin:/bin
LOGNAME=rust
PWD=/home/rust
```

### PR DESCRIPTION
**Pull request by kamalmarhubi**
This reports an error at the point of calling `Command::spawn()` or one of
its equivalents.

Fixes #30858
Fixes #30862

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
I think both issues will manifest on Windows as well, but I made no changes there. The added regression tests will likely cause failures on Windows.

File: src/libstd/sys/unix/process.rs [hunk 1]
```diff
@@ -13,37 +13,157 @@
...
+//                         .env("and\0even", "in\0here")
+//                         .spawn();
+//
+// The `std::process` API only allows reporting failure at `spawn()` and
+// its equivalents; all the builder style methods others return `'&mut
+// self` for chaining. The `ValidatedCString` lets us delay the error reporting
+// to that point and report an error via a `Result` rather than by
+// panicking.
+#[derive(Debug, Clone)]
+pub enum ValidatedCString {
```
Comment (alexcrichton) [inline src/libstd/sys/unix/process.rs]: In the case that an invalid string is passed down, we don't necessarily need to store the original data, so perhaps this could just store a flag in `Command` as to whether something with a nul byte in it has been passed in? That way once we hit `spawn` we can just check the flag and return an error appropriately.

File: src/libstd/sys/windows/process.rs [hunk 2]
```diff
@@ -90,6 +90,12 @@ impl Command {
     pub fn cwd(&mut self, dir: &OsStr) {
         self.cwd = Some(dir.to_os_string())
     }
+    pub fn get_program(&self) -> &OsString {
+        &self.program
+    }
+    pub fn args_iter(&self) -> slice::Iter<OsString> {
```
Comment (alexcrichton) [inline src/libstd/sys/windows/process.rs]: Perhaps this (and unix) could just be:

```rust
pub fn arg(&self) -> &[OsString]
```

File: src/libstd/process.rs [hunk 3]
```diff
@@ -889,4 +889,42 @@ mod tests {
...
+    }
+
+    #[test]
+    fn test_interior_nul_in_args_does_not_panic() {
+        Command::new("echo").args(&["has-some-\0\0s-inside"]);
+    }
+
+    #[test]
+    fn test_interior_nul_in_current_dir_does_not_panic() {
+        Command::new("echo").current_dir("has-some-\0\0s-inside");
```
Comment (alexcrichton) [inline src/libstd/process.rs]: For this and the above tests can you assert that `spawn` will return an error?

File: src/libstd/sys/unix/process.rs (hunk 1 above)
Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: I mostly kept it so the `Debug` impl on `std::process::Command` would display something. I can change this though.

File: src/libstd/sys/windows/process.rs (hunk 2 above)
Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: I think the unix version would reqiure allocation of the slice, since the underlying storage isn't `OsStr`. This also conflicts with the naming of `arg()` for the setter.

File: src/libstd/process.rs (hunk 3 above)
Comment (kamalmarhubi) [inline src/libstd/process.rs]: Done.

File: src/libstd/sys/unix/process.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libstd/sys/unix/process.rs]: Ah that's a good point. The `Debug` impl would probably be fine to start including something like `<string-with-nul>` or something like that instead of the actual value, however. It seems relatively complicated to define a type like this *just* for a `Debug` implementation that's unlikely to ever be seen.

File: src/libstd/sys/windows/process.rs (hunk 2 above)
Comment (alexcrichton) [inline src/libstd/sys/windows/process.rs]: It may be best to delegate the `Debug` implementation to each platform's module in that case, we try to avoid differences in APIs wherever possible across the platforms.

File: src/libstd/sys/unix/process.rs (hunk 1 above)
Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: Maybe (ab)use `Option` for this?

```
pub struct Command {
    program: Option<CString>,
    args: Vec<Optrion<ValidatedCString>>,
    env: Option<HashMap<Option<CString>, Option<ValidatedCString>>>,
    cwd: Option<Option<CString>>,
    uid: Option<uid_t>,
    gid: Option<gid_t>,
    session_leader: bool,
    saw_nul: bool,
}
```

The `Debug` impl could then use `unwrap_or("<string-with-nul>")`.

This is a bit weird for env, as the hash map would lose context of how many vars were nulful. The cwd would be a bit unwieldy with the double `Option`...

File: src/libstd/sys/windows/process.rs (hunk 2 above)
Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: The public APIs are still the same. Do you mean avoid differences across the `sys` modules?

Comment (alexcrichton) [inline src/libstd/sys/windows/process.rs]: Yes, and the public APIs are a little different b/c they're in theory returning `impl Iterator<Item=OsString>` but the actual type being returned is quite different

Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: Ok, I've delegated to impls in the platform modules.

**Comment by brson** [comment]
I marked this as a regression since it changes behavior, but I'm in favor.

**Comment by kamalmarhubi** [comment]
Argh I missed the warnings and didn't realise they were errors in the build. Just pushed something that should pass. There are still a couple of open discussion points though.

File: src/libstd/sys/unix/process.rs (hunk 1 above)
Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: @alexcrichton any thoughts on how best to handle this?

Comment (alexcrichton) [inline src/libstd/sys/unix/process.rs]: Oh I wouldn't change the internal structure of `Command` much, just add a flag indicating that something with a nul byte was passed in. The `Debug` implementation only shows the program and its arguments, so if we really want we can store `CString::new("<string-with-nul>").unwrap()` in those places, but other than that we don't need to track the information elsewhere.

Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: Ok, so that means dropping this whole ValidatedCString thing, right? Shall I close this and open an new PR skipping that altogether?

Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: I also don't have a good grasp on what Windows does here. I think my tests on `std::process` will fail there, but without seeing the failures I'm not sure what to do to fix it.

Comment (alexcrichton) [inline src/libstd/sys/unix/process.rs]: Nah keeping this PR is fine (just pushing the changes to it).

I do think that the tests will fail on Windows as well, but it should be pretty straightforward (e.g. checking `encode_wide()` for zeros) and relatively the same implementation as Unix.

Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: I've changed the unix version. I'll try to make changes for Windows, but it'll be kind of fumbling in the dark.

File: src/libstd/sys/unix/process.rs [hunk 4]
```diff
@@ -31,57 +31,95 @@ use sys::{self, cvt, cvt_r};
...
-        self.args.extend(args.map(os2c));
+        let mut saw_nul = self.saw_nul;
+        self.args.extend(args.map(|arg| os2c(arg, &mut saw_nul)));
+        self.saw_nul = saw_nul;
     }
     fn init_env_map(&mut self) {
         if self.env.is_none() {
-            self.env = Some(env::vars_os().collect());
+            // Will not add NULs to env: preexisting environment will not contain any.
+            self.env = Some(env::vars_os().map(|(k, v)| (k, v)).collect());
```
Comment (alexcrichton) [inline src/libstd/sys/unix/process.rs]: I don't think that this needs to change, right?

**Comment by alexcrichton** [comment]
Looks good to me! I think the Windows implementation will just need to be tweaked and this should be good to go. If you want to test things out it and you're on Unix you may be able to use [this helper script I have](https://gist.github.com/alexcrichton/60bb61c6bf4d81a03ff6) to at least ensure the standard library itself compiles, I suspect this is a situation where "when it compiles it works" :)

File: src/libstd/sys/unix/process.rs (hunk 4 above)
Comment (kamalmarhubi) [inline src/libstd/sys/unix/process.rs]: erm yeah that's a non-perfect refactor of an intermediate stage I had.... time to apply `map id => id`...

**Comment by kamalmarhubi** [comment]
Thanks for the script!

**Comment by kamalmarhubi** [comment]
Sorry for letting this go for so long. I kept putting off learning about `OsStr` on windows. This should be done now!

File: src/libstd/sys/windows/process.rs [hunk 5]
```diff
@@ -43,13 +43,25 @@ fn mk_key(s: &OsStr) -> OsString {
     })
 }
 
+fn ensure_no_nuls<T: AsRef<OsStr>>(str: T) -> io::Result<T> {
+    let has_nul = {
+        let bytes = str.as_ref().as_inner().inner.as_inner();
```
Comment (alexcrichton) [inline src/libstd/sys/windows/process.rs]: Ah can this actually use the `.encode_wide()` method? That's what'll be passed down to the OS anyway, and is a little more reliably than looking at the internal bytes.

**Comment by alexcrichton** [comment]
Thanks @kamalmarhubi! Looks good to me modulo one nit and I'd be fine sending to bors after.

File: src/libstd/sys/windows/process.rs (hunk 5 above)
Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: The environment block is built up using `.extend()`, and I wanted to avoid the extra allocation and copy of the keys and values that would be necessary to check the `.encode_wide()` output. See https://github.com/rust-lang/rust/pull/31056/files#diff-9a0a769432651d9c59644e0a8c7f887eR353

We can avoid the repeated allocation by reusing a buffer for the conversion, but we'd still pay the extra copy cost. I'm happy to do this however you prefer, though.

**Comment by kamalmarhubi** [comment]
Yay! I'm really excited to see what the bors experience is like, so I'll try and keep this moving. :-)

File: src/libstd/sys/windows/process.rs (hunk 5 above)
Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: Oh I see what you mean. Ignore above!

Comment (kamalmarhubi) [inline src/libstd/sys/windows/process.rs]: Done!

**Comment by alexcrichton** [comment]
Thanks! Can you squash the commits down into one as well? (sorry forgot to check that last time)

**Comment by kamalmarhubi** [comment]
Done, and rebased.

**Comment by kamalmarhubi** [comment]
Fixed test and squashed. Diff: https://github.com/kamalmarhubi/rust/compare/59d070c...7c64bf1

**Comment by kamalmarhubi** [comment]
Urg pushed the wrong thing.

**Comment by kamalmarhubi** [comment]
Actually no, I pushed the right thing I just can't get the diff to display as I'd like. Here's the diff:

```diff
diff --git a/src/libstd/sys/windows/process.rs b/src/libstd/sys/windows/process.rs
index 758044c..61cf28b 100644
--- a/src/libstd/sys/windows/process.rs
+++ b/src/libstd/sys/windows/process.rs
@@ -419,11 +419,12 @@ mod tests {
     #[test]
     fn test_make_command_line() {
         fn test_wrapper(prog: &str, args: &[&str]) -> String {
-            String::from_utf16(
-                &make_command_line(OsStr::new(prog),
-                                   &args.iter()
-                                        .map(|a| OsString::from(a))
-                                        .collect::<Vec<OsString>>())).unwrap()
+            let command_line = &make_command_line(OsStr::new(prog),
+                                                  &args.iter()
+                                                       .map(|a| OsString::from(a))
+                                                       .collect::<Vec<OsString>>())
+                                    .unwrap();
+            String::from_utf16(command_line).unwrap()
         }
 
         assert_eq!(
```
