### PR TITLE
normalize in `trait_ref_is_knowable` in new solver

### LINKED ISSUE #51: Trait ref is not considered knowable due to normalization
This code fails in the new trait solver `-Ztrait-solver=next-coherence`:

```rust
use std::future::Future;
use std::pin::Pin;

struct Value;

impl<'a> std::future::IntoFuture for Pin<&'a mut Value>
{
    type Output = ();
    type IntoFuture = Pin<Box<dyn Future<Output = ()> + Send>>;

    fn into_future(self) -> Self::IntoFuture {
        todo!()
    }
}
```

Which overlaps with this implementation: https://doc.rust-lang.org/std/future/trait.Future.html#impl-Future-for-Pin%3CP%3E

We try to prove that `<&mut Value as std::ops::Deref>::Target: std::future::Future` does *not* hold, but that ends up being ambiguous because aliases are treated as non-local tys, even though we can definitely normalize `<&mut Value as std::ops::Deref>::Target` to just `Value`, which *is* a local ty.

### PR DESCRIPTION
**Pull request by lcnr**
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/51

Alternatively we could avoid normalizing the self type and do this at the end of the `assemble_candidates_via_self_ty` stack by splitting candidates into:
- applicable without normalizing self type
- applicable for aliases, even if they can be normalized
- applicable for stuff which cannot get normalized further

I don't think this would have any significant benefits and it also seems non-trivial to avoid normalizing only the self type in `trait_ref_is_knowable`. 

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_trait_selection/src/solve/assembly/mod.rs [hunk 1]
```diff
@@ -890,26 +890,43 @@ impl<'tcx> EvalCtxt<'_, 'tcx> {
...
+        };
+
+        let result = self.probe_candidate("coherence unknowable").enter(|ecx| {
+            let trait_ref = goal.predicate.trait_ref(tcx);
+
+            #[derive(Debug)]
+            enum FailureKind {
+                Overflow,
+                NoSolution(NoSolution),
+            }
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/solve/assembly/mod.rs:906]: Do you think `lazy_normalize_ty` should just return this `FailureKind`?

**Review by compiler-errors — APPROVED** [review]
r=me nit or not

File: compiler/rustc_trait_selection/src/solve/assembly/mod.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_trait_selection/src/solve/assembly/mod.rs:892]: hmm, I think it's valuable to guarantee that `trait_ref_is_knowable` always returns the outer `Ok` when used outside of the new solver

**Comment by compiler-errors** [comment]
@bors r-

looks like we're hitting that stability assertion :(

**Comment by lcnr** [comment]
that sure is a nice way to get a minimized test :sparkles:

**Comment by lcnr** [comment]
lowered the stability check to a `warn!` and accepted it with a `FIXME`. It is non-trivial to fix and by keeping it as a warn we should be able to actually keep it enabled while testing stuff.

**Comment by lcnr** [comment]
see https://github.com/rust-lang/trait-system-refactor-initiative/issues/54 for an issue tracking the evaluate goal instability bug.

@bors r=compiler-errors rollup (new solver)

File: compiler/rustc_trait_selection/src/solve/eval_ctxt.rs [hunk 2]
```diff
@@ -388,44 +388,60 @@ impl<'a, 'tcx> EvalCtxt<'a, 'tcx> {
...
+            self.check_evaluate_goal_stable_result(goal, canonical_goal, canonical_response);
+            // In case the evaluation was unstable, we manually make sure that this
+            // debug check does not influence the result of the parent goal.
+            self.search_graph.reset_encountered_overflow(from_original_evaluation);
         }
 
         Ok((has_changed, certainty, nested_goals))
     }
 
+    fn check_evaluate_goal_stable_result(
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/solve/eval_ctxt.rs:404]: This check should even when debug assertions are enabled -- otherwise, there's UI test instability between rustc w/ debug_assertions and not.

**Comment by compiler-errors** [comment]
Failed in rollup

@bors r-

https://github.com/rust-lang/rust/pull/114632#issuecomment-1670128351
