### PR TITLE
rustdoc: use focus for search navigation

### LINKED ISSUE #79872: rustdoc: Don't override system keyboard shortcuts for search results tab-switcher
Once #79862 is merged, rustdoc will be overriding the macOS system keyboard
shortcuts <kbd>Ctrl-↑</kbd> and <kbd>Ctrl-↓</kbd> (Control–Up Arrow and Control–Down Arrow).

Personally, I don't use these shortcuts, but I imagine others do. We should find
different key combinations that won't override system shortcuts.

*See the discussion around <https://github.com/rust-lang/rust/pull/79862#issuecomment-742118057>.*

cc @GuillaumeGomez @Manishearth

### LINKED ISSUE #79962: focus wrong for unchanged search after mousing over search results
This one is a relatively minor bug, since it only happens if you try to search for the same thing you are looking at, which is not a very natural thing to do.  But I thought I would report it anyway.

### Steps to reproduce

1. Go to the front page of the std results from rustdoc
2. Click in the search box at the top of the page
3. Type in `assert` (as an example search term) and hit Return
4. If your rustdoc version has the bug #79960, and you have cookies disabled or are viewing the docs via a `file://` url, click anywhere outside the help popup to dismiss it
5. See that some search results are displayed.
6. Move the mouse pointer over the search results.  A moving highlight is displayed.
7. Move the mouse pointer over the search box, and left click, to focus the search box
8. Hit return to search for the same thing again

### Expected results

The same search is performed again, so the page reloads with little change.

### Actual results

Whatever search result you last moused over, which has the highlight shown, is visited.

@rustdoc modify labels +T-rustdoc -A-rustdoc-ui

### LINKED ISSUE #84384: rustdoc: Ctrl-Enter on search result should open link in new tab
Steps to reproduce:

1. Visit a rustdoc page, e.g. https://doc.rust-lang.org/nightly/std/
2. Hit 'S' to focus search.
3. Type a search, e.g. "String"
4. Press the down arrow once to highlight a search result.
5. Hold down Ctrl (incidentally, notice that the highlighting goes away).
6. Hit enter.

Expected result:

First search result is opened in a new tab.

Actual result:

Nothing happens.

In general, Ctrl-Enter works when an `<a>` is focused. The search results are `<a>`s. I think mainly we need two things:

1. Make modifier keys (shift, ctrl, etc) not remove the highlighting of search results.
2. Make sure highlighting search results with the arrow keys also focuses them.

Reproduces in latest Chrome and Firefox on Linux.

### PR DESCRIPTION
**Pull request by jsha**
Rather than keeping track of highlighted element inside the JS, take advantage of `.focus()` and the :focus CSS pseudo-class.

This required wrapping each row of results in one big `<a>` tag (because anchors can be focused, but table rows cannot). That in turn required moving from a table layout to a div layout with float.

This makes it so Ctrl+Enter opens links in new tabs, and using the arrow keys to navigate off the bottom of the page scrolls the rest of the page into view. It also simplifies the keyboard event handling. It eliminates the need for click handlers on the search results, and for tracking mouse movements.

This changes the UI treatment of mouse hovering. A hovered element now gets a light grey background, but does not change the focus. It's possible to have two highlighted search results: one that is focused (via keyboard) and one that is hovered (via mouse). Pressing enter will activate the focused link; clicking will activate the hovered link. This matches up with how Firefox and Chrome handle suggestions in their URL bar, and avoids stray mouse movements changing the focus.

Selecting tabs is now done with left/right arrows while any search result is focused. The visibility of results on each search tab is
controlled with the "active" class, rather than by setting display: none directly. Note that the old code kept track of highlighted search element when tabbing back and forth. The new code doesn't.

Demo at https://hoffman-andrews.com/rust/focus-search-results2/std/?search=fn

Fixes #84384
Fixes #79962
Fixes #79872

### CODE REVIEW

**Comment by jsha** [comment]
@bors r? @GuillaumeGomez 

BTW I see in https://github.com/rust-lang/rust/issues/65212#issuecomment-741952935 that a desired functionality is that you can press down arrow a few times, and then type a letter key to add to your search. That doesn't work in the current revision but should be easy to restore: We can make it so that typing any letter key while the search results are highlight focuses the search input and inserts that letter.

**Comment by jsha** [comment]
Also cc @cratelyn and @Manishearth who had great feedback about keyboard navigation in #65212.

**Comment by GuillaumeGomez** [comment]
That's what I was a bit afraid of: scroll with arrows isn't working anymore, we have to use the mouse now. I'm a bit shared on this. Also: can you "restore" the previous coloring for the focused search result please?

Another important point: when we go back to the search input, can you scroll to the top too and not simply focus on the input? We add some issues about this behavior because some browsers only care if the element is in the viewport and not if it's reachable/visible (because hidden under other elements). That could be an issue on docs.rs for example.

> BTW I see in #65212 (comment) that a desired functionality is that you can press down arrow a few times, and then type a letter key to add to your search. That doesn't work in the current revision but should be easy to restore: We can make it so that typing any letter key while the search results are highlight focuses the search input and inserts that letter.

That'd be nice to keep this behaviour, indeed. Question though: what happens if we press the letter 's'? Should it only focus the search input (like it does when it's not focused) or should it also enter the letter 's'?

> Selecting tabs is now done with left/right arrows while any search result is focused. The visibility of results on each search tab is controlled with the "active" class, rather than by setting display: none directly. Note that the old code kept track of highlighted search element when tabbing back and forth. The new code doesn't.

So three things here:
 1. Being able to switch tabs when the search input is focused (using the current shortcut CTRL+up/down) would be nice, because for now it'd force to have a search result focused, which isn't super intuitive.
 2. If so, having two different shortcuts for a same behaviour seems really bad, no idea how to make it work otherwise though...
 3. Please keep track of the focused element in the other tabs.

One last point (small bug apparently): this search triggers a js error: https://hoffman-andrews.com/rust/focus-search-results2/std/?search=-%3E%20str . I was trying to check how it handled things in case the current tab was empty. The current behaviour is that it selects the first non-empty.

Also, I couldn't check but: does it keep "memory" of the last selected tab when you do another search (without selecting a result I mean, just doing another search when on search results).

**Comment by Manishearth** [comment]
> That's what I was a bit afraid of: scroll with arrows isn't working anymore, we have to use the mouse now. I'm a bit shared on this. Also: can you "restore" the previous coloring for the focused search result please?

Scroll with arrows works fine for me in this prototype? It's actually _better_ now since it's per-row instead of per-cell.

> Being able to switch tabs when the search input is focused (using the current shortcut CTRL+up/down) would be nice, because for now it'd force to have a search result focused, which isn't super intuitive.

Idk, for me it's quite intuitive, you hit the down arrow once to enter the search results, and then you can use all four arrow keys to naturally navigate. This is how most tab-based keyboard navigation works.


> Please keep track of the focused element in the other tabs.

I'm against this: this is overriding browser default focus behavior with JS and I have never seen that go well. Fine to override focus to the start of the list, but custom stuff tends to break down, and is usually bad for accessibility.

**Comment by GuillaumeGomez** [comment]
> Oh I see what you mean. That's a fair point, I guess users can use page up/page down, maybe.

I'm sad to say this but: those keys aren't available on all computers... XD (not even joking here)

**Comment by Manishearth** [comment]
> I'm sad to say this but: those keys aren't available on all computers... XD (not even joking here)

I'm aware, usually it exists behind a Fn key (Fn-arrow gives home/end/pgup/pgdn), but yeah, this isn't ideal. Not sure what the best option is here.

> I'd argue that this is not the default behavior considering that we're creating it. And also that this changes the current behaviour. Not a blocker but something we should be careful about.


Browser focus navigation continues to work, which is the default behavior people will be used to more than site-specific keyboard shortcuts.

> It's very common for me to switch between two tabs and it'd be annoying to have to go through all the items again. Not sure what the accessibility issue here would be though. More explanations please? :)

In general trying to replace existing browser features with custom JS never goes well in my experience, and ends up with things breaking. A lot of modern websites do this kind of thing a lot and it breaks down pretty quickly and is hard to keep cross-browser compatible.

**Comment by GuillaumeGomez** [comment]
> In general trying to replace existing browser features with custom JS never goes well in my experience, and ends up with things breaking. A lot of modern websites do this kind of thing a lot and it breaks down pretty quickly and is hard to keep cross-browser compatible.

The only thing the JS would do would be to re-focus the element that was previously focused in the tab when we switch between them. We are not overriding more than what we are already. We already use JS to switch tabs, so what would that change to re-focus the previously focused element in that tab?

**Comment by Manishearth** [comment]
> The only thing the JS would do would be to re-focus the element that was previously focused in the tab when we switch between them. We are not overriding more than what we are already. 

Because we're trying to keep track of focus and remember it as well, as opposed to just _setting_ it. I guess it's fine but in my experience this kind of thing doesn't go well.

I'd rather defer to @jsha on this though.

**Comment by Manishearth** [comment]
> What I see is this: search input or search results focused -> down arrow selects a result. No focus -> down arrow scrolls the page.
> 
> >

This is what I see too. I _think_ what @GuillaumeGomez is referring to is that previously you could scroll the entire search results page with the arrow key. I'm ... okay with losing that functionality when there's search focus.

**Comment by jsha** [comment]
> previously you could scroll the entire search results page with the arrow key. 

What I see on https://doc.rust-lang.org/std/?search=fn is:

 - When search is focused, you _can't_ scroll the page with the arrow keys because arrow keys highlight search results.
 - When nothing is focused (i.e. click in a blank part of the page), you can scroll the page with the arrow keys.
 
 But I can reproduce both of those behaviors on my demo.

**Comment by GuillaumeGomez** [comment]
> > Also: can you "restore" the previous coloring for the focused search result please?
> 
> Right now the focused search result gets colorful backgrounds, and the mouse hover gets gray. I'd like focus vs hover to be visually distinct. I could switch those, so hover is colorful and focus is gray. Or I could make both colorful, but hover desaturated (but I think this will produce visual confusion).

For me there is only the normal focus (border with pointed line). I'd prefer something a bit more colorful, at least enough to see it and not just the pointed border.

> > scroll with arrows isn't working anymore, we have to use the mouse now
> 
> I'm confused in the same way @Manishearth was. For me, both search result selection and page scrolling with the arrow keys works the same as on master (using FF and Chrome on Linux). Can you tell me the keystrokes you're doing that cause a page scroll on master, but don't cause a page scroll in this branch? What I see is this: search input or search results focused -> down arrow selects a result. No focus -> down arrow scrolls the page.

No sorry, you're both right. Just double checked and when the focus isn't on the search input or on one of the result, it's working as expected.

> > Being able to switch tabs when the search input is focused (using the current shortcut CTRL+up/down) would be nice, because for now it'd force to have a search result focused, which isn't super intuitive.
> > It's very common for me to switch between two tabs and it'd be annoying to have to go through all the items again.
> 
> I don't fully understand your use case here. Can you tell me more? What's an example search where you would be likely to focus an element in one tab, go to another tab, come back to the original tab and want to continue where you left off? Are these very long lists of search results?

It happens when I'm looking for a type to be both in parameters and in the returned value. It's mostly on crates composed of a lot of similar functions with hard to read signatures (someone said simd?). So not sure how common my case is.

**Comment by jsha** [comment]
> For me there is only the normal focus (border with pointed line). I'd prefer something a bit more colorful, at least enough to see it and not just the pointed border.

I can't reproduce this, on FF, Chrome, or Edge. Here's what I see:

image

In what browser are you seeing the focus without color? And what mouse clicks / keystrokes do you use to get there?

**Comment by jsha** [comment]
> Another important point: when we go back to the search input, can you scroll to the top too and not simply focus on the input? We add some issues about this behavior because some browsers only care if the element is in the viewport and not if it's reachable/visible (because hidden under other elements). That could be an issue on docs.rs for example.

The natural way to do this is with `element.scrollIntoView()`. I've tried this locally, and it has a downside: if you're already at the top of the page, it actually scrolls the page down by about a half-line so the search box is at the very tippy-top of the page.

Focusing the search box will generally do the right thing. I can see how there's an issue where a topbar obscures part of the page (like on docs.rs), but I'd rather address that in docs.rs by making the topbar doesn't overlap, but instead shrinks the scrollable part of the page. Overlapping topbars already cause problems: they make page-up / page-down / spacebar scroll by an incorrect amount.

**Comment by Nemo157** [comment]
In `ayu` theme the focus was a simple dotted blue outline, now it appears that both `dark` and `ayu` don't highlight the focused element at all.

**Comment by jsha** [comment]
I've pushed some changes and updated the demo. I went ahead and implemented "remember the focused item on the previous tab." It wasn't too complicated and I don't think it will have many unanticipated side effects.

I fixed a nasty bug where I accidentally overrode alt-left and alt-right (forward and back in browser history 😳). And another interesting bug where searching multiple times, or changing crates, would cause jumping by more than one item at a time.

All three themes should now work and show colorful highlighting.

> We can make it so that typing any letter key while the search results are highlight focuses the search input and inserts that letter.

I haven't implemented this yet. Thinking about it some more, I think it will be quite hard to get right. For JS keyboard events we just get a keycode, not an indication of whether something is a letter or punctuation. And the set of keycodes that correspond to letters and punctuation will probably change by locale. My preference right now would be that, when you are navigating through search results, you have to hit 's' to re-focus the search input. Is that okay by you @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
> I haven't implemented this yet. Thinking about it some more, I think it will be quite hard to get right. For JS keyboard events we just get a keycode, not an indication of whether something is a letter or punctuation. And the set of keycodes that correspond to letters and punctuation will probably change by locale. My preference right now would be that, when you are navigating through search results, you have to hit 's' to re-focus the search input. Is that okay by you @GuillaumeGomez ?

I am fine with it.

When I hover with the mouse, I get:

Screenshot from 2021-04-26 13-50-15

This is not great... Also: why did you update the "selected" entry color style? Wouldn't it be better to keep it as is? And finally: for the mouse hover, wouldn't it be simpler to use the same color as focus but with a lighter/darker tone instead of a completely different one?

**Comment by jsha** [comment]
> Also: why did you update the "selected" entry color style?

Do you mean the CSS selectors, like `a.result-trait:focus`? Or are you talking about different colors? I think the colors for focused items (previously "highlighted" items) are the same.

> When I hover with the mouse, I get:

Ah, looks like I need a better hover color for dark themes, thanks.

> And finally: for the mouse hover, wouldn't it be simpler to use the same color as focus but with a lighter/darker tone instead of a completely different one?

I think that would require a whole addition set of styles for the hover colors, which would add some complexity and maintenance burden. But more importantly, I think having two colorful selections, even with a lighter/darker tone, would make it confusing as to which is hovered and which is focused.

**Comment by GuillaumeGomez** [comment]
> > Also: why did you update the "selected" entry color style?
> 
> Do you mean the CSS selectors, like `a.result-trait:focus`? Or are you talking about different colors? I think the colors for focused items (previously "highlighted" items) are the same.

Nevermind, just realized that I had some "personal" style over the default one. Removed it and back to normal, my bad.

> > And finally: for the mouse hover, wouldn't it be simpler to use the same color as focus but with a lighter/darker tone instead of a completely different one?
> 
> I think that would require a whole addition set of styles for the hover colors, which would add some complexity and maintenance burden. But more importantly, I think having two colorful selections, even with a lighter/darker tone, would make it confusing as to which is hovered and which is focused.

Then why not using the same color and maybe add a "border effect" for the focused one (or not and simply use both same colors both the focus and hover)?

**Comment by GuillaumeGomez** [comment]
Before I forget: you'll also need to update the help popup. :)

**Comment by dns2utf8** [comment]
Hi, very cool changes so far

I noticed that the "no results" information on the bottom is visible twice when I search for "fs":
image

And three times if the search turns up nothing:
image

**Comment by dns2utf8** [comment]
Another small thing I noticed: when scrolling down with the arrows on firefox and chromium the target URL blocks the view to the currently selected entry.
When using the mouse, the browser moves the info box out of the way, so I am not sure if there is much to be done except maybe move the last entry one more line when at the bottom of a page?

image

**Comment by dns2utf8** [comment]
I implemented the scrolling ahead functionality [on top of your PR](https://github.com/jsha/rust/pull/1).

It scrolls ahead and prevents that the user can not see the current selection when the browser shows the target URL:
image

**Comment by dns2utf8** [comment]
Another thing I noticed:
If an entry is selected and the browser window looses focus the keyboard selection gets hidden until the window regains the focus again.
In the current stable the selection stays visible. Can we keep this behaviour or something similar?

**Comment by jsha** [comment]
@dns2utf8 Thanks for the PR! In reviewing it, I searched MDN for some scroll-related properties, and I found `scroll-margin`, which seems to do just what we want, so I pushed a commit that does that: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin. I've also updated the demo.

> If an entry is selected and the browser window looses focus the keyboard selection gets hidden until the window regains the focus again.
> In the current stable the selection stays visible. Can we keep this behaviour or something similar?

I think this would be somewhat messy. From the browser's point of view, the item is not focused if the browser is not focused, so the CSS properties for `:focus` no longer apply. We could probably hack around this by adding an `onfocus` handler that adds the `highlighted` class to search result, and an `onblur` that removes it, _but only if nothing else on the page is becoming focused. However, this seems to eliminate some of the simplicity gains we gt from using the browser's focus mechanism instead of emulating it ourselves.

**Comment by GuillaumeGomez** [comment]
@jsha The support for `scroll-margin` seems incomplete on safari. Have you tested on a mac? If not I can, please update your demo link so I can confirm. :)

**Comment by jsha** [comment]
Oops, I thought I'd updated the demo. Done now.

BTW [MDN says, under Safari support for scroll-margin](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin): 

> Scroll margin is not applied for scrolls to fragment target or scrollIntoView(), see bug 189265.

I think neither of these apply here.

**Comment by GuillaumeGomez** [comment]
I can confirm that it's working perfectly on mac. 👍

File: src/librustdoc/html/static/search.js [hunk 1]
```diff
@@ -879,106 +879,31 @@ window.initSearch = function(rawSearchIndex) {
...
-                }, 20);
-            }
-        };
-        onEachLazy(document.getElementsByClassName("search-results"), function(e) {
-            onEachLazy(e.getElementsByClassName("result"), function(i_e) {
-                i_e.onclick = click_func;
-                i_e.onmouseover = mouseover_func;
-            });
-        });
+    function tabLeft() {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/search.js:882]: Instead of having two functions to handle that, wouldn't it be simpler to give `1` or `-1` as parameter to function which would then add it to `currentTab` and then check if `< 0` or `> 2`?

Because the two functions are almost identical.

File: src/librustdoc/html/static/themes/ayu.css [hunk 2]
```diff
@@ -467,15 +460,38 @@ pre.rust .attribute .ident {}
...
+.content a.attr,.content a.derive,.content a.macro {}
 .stab.portability {}
-.content .highlighted.union {}
 .content span.primitive,.content a.primitive,.block a.current.primitive {}
 .content span.externcrate,.content span.mod,.content a.mod,.block a.current.mod {}
-.content .highlighted.type {}
 pre.rust .kw-2,pre.rust .prelude-ty {}
 .content span.trait,.content a.trait,.block a.current.trait {}
 
+.search-results a:focus {}
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/themes/ayu.css:470]: Maybe use comma instead of `{}` on every line and put the `{}` at the end?

File: src/librustdoc/html/static/themes/ayu.css [hunk 3]
```diff
@@ -467,15 +460,38 @@ pre.rust .attribute .ident {}
...
+a.result-foreigntype:focus {}
+a.result-attr:focus,
+a.result-derive:focus,
+a.result-macro:focus {}
+a.result-constant:focus,
+a.result-static:focus {}
+a.result-primitive:focus {}
+a.result-keyword:focus {}
+
+
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/themes/ayu.css:493]: Maybe remove some empty lines here? :)

File: src/librustdoc/html/static/themes/ayu.css (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/themes/ayu.css:470]: Ah nevermind, that would error. Is it normal that in ayu they're all the same?

**Comment by GuillaumeGomez** [comment]
Still not correct hover:

Screenshot 2021-04-28 at 20 08 55

File: src/librustdoc/html/static/themes/ayu.css (hunk 2 above)
Comment (jsha) [reply src/librustdoc/html/static/themes/ayu.css:470]: Yep, see the comment above (prior to FIXME; it's hidden by GitHub):

> /* rules that this theme does not need to set, here to satisfy the rule checker */

**Comment by GuillaumeGomez** [comment]
I noticed a change in behaviour: when you are on the first tab and press left, you should be put on the last one, but it's doing nothing. Same when you're on the last tab and press right.

But otherwise, I really love this change. It's so much better than the current handling. \o/

**Comment by dns2utf8** [comment]
I usually prefere a CSS over a JS solution, but the scrolling behaves very strange on my machine. 
On Firefox 88 (Arch Linux) the scroll margin lets the selection out, but it works on chromium -> is it a firefox bug or does one of my addons interfere? 

https://user-images.githubusercontent.com/739070/116457474-f9ffaf00-a852-11eb-83a0-9c8f53fa2832.mp4

**Comment by GuillaumeGomez** [comment]
Ah right, in my case on firefox, the focus is completely broken. It goes beyond the last one visible before we can see again.

**Comment by jsha** [comment]
Yeah, agreed the current solution is broken. I need to experiment a bit more with scroll-margin (negative vs positive values?) and figure out if it's the right tool for the job. It's possible the proposed JS solution is better.

**Comment by dns2utf8** [comment]
I fetched the latest firefox beta 89.0b5 and the behaviour is the same as with 88 :/

**Comment by dns2utf8** [comment]
I did open an [issue on firefoxs bugzilla #1708303](https://bugzilla.mozilla.org/show_bug.cgi?id=1708303), if you have an account please vote for the issue.

**Comment by dns2utf8** [comment]
A fix for the scroll-margin bug laded in the [Firefox Source](https://hg.mozilla.org/mozilla-central/rev/8befa6dc66fd) today.
I just tested [my minimal example](https://data.estada.ch/firefox_scroll-margin_bug/) with the latest desktop nightly build and it works. So, then in ~12 weeks the fix will be in in Firefox 90 stable.
The android nightly is still broken, I assume the fix will land there tomorrow.

**Comment by GuillaumeGomez** [comment]
This is way too recent to be used if it's broken in older versions. We'll need to find another way. :)

**Comment by dns2utf8** [comment]
What if we the JavaScript implementation and the CSS together. Adding a mark to both of them why the feature is implemented twice.
Also, I just checked [caniuse](https://caniuse.com/?search=scroll-margin) and it said that IE does not support it at all.

Currently, the JS implementation emulates `scroll-margin-bottom: 1em;` and the CSS is was at `300px`. That way browsers with (correct) support will present a smoother experience and works on scroll up as well.
Or just make a note for 2022?

**Comment by GuillaumeGomez** [comment]
We dropped IE support when we decided to use `<details>` and `<summary>`, so not a problem on that. :)

Maybe we just need to call `elem.focus()` and that would do the trick?

**Comment by jsha** [comment]
> What if we the JavaScript implementation and the CSS together.

I think the JS implementation is fine, and I don't want to take the extra complexity for two implementations of the same thing.

> Currently, the JS implementation emulates scroll-margin-bottom: 1em; and the CSS is was at 300px.

If you prefer a larger margin, I can make the JS do that. The current version was a fairly arbitrary choice.

@GuillaumeGomez, following up on your previous request to make both the hover and the focus colorful:

 > > > And finally: for the mouse hover, wouldn't it be simpler to use the same color as focus but with a lighter/darker tone instead of a completely different one?

> > I think that would require a whole addition set of styles for the hover colors, which would add some complexity and maintenance burden. But more importantly, I think having two colorful selections, even with a lighter/darker tone, would make it confusing as to which is hovered and which is focused.

> Then why not using the same color and maybe add a "border effect" for the focused one (or not and simply use both same colors both the focus and hover)?

I really think the bright colors for focus and grey for hover are the right combination. I'm partly taking an example from Firefox here:



But also my reasoning is: There's a good chance that your mouse will "accidentally" hover something because it's just sitting around; it should have a less distracting color than the keyboard focus for that reason.

**Comment by dns2utf8** [comment]
Re the scrolling, I am happy with it. Sometimes the distance to the end of the window fluctuates by a few pixels but it kepps the math simple so I would keep it simple for now :)

**Comment by jsha** [comment]
> when an item is selected, its text becomes white

Fixed!

**Comment by GuillaumeGomez** [comment]
Just realized something funny: the further down we go, the closer to the bottom of the window the focus is. Can be fixed later as it's not really a big issue, this PR has been open for long enough and I'd really like to see it merged. :D

@dns2utf8 One last check from you too please? :)

**Comment by GuillaumeGomez** [comment]
Let's go forward with this then. Really can't wait for this improvement to get merged! :)

@bors: r+
