### PR TITLE
[incremental] Don't panic if decoding the cache fails

### LINKED ISSUE #48847: rustc panic while reading incremental index
rustc crashed during compilation with:
```
$ buck test scm/mononoke/tests/integration                                                                                                             
error: could not load dep-graph from `buck-out/tmp/rust-incremental/bundle2_resolver-2xb5l9oneofqa/s-eyz77d7pz2-4k21tt-working/dep-graph.bin`: failed to fill whole buffer


thread '<unnamed>' panicked at 'index out of bounds: the len is 4194304 but the index is 4194304', rust/1.24.0/src/rust/src/libserialize/leb128.rs:59:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-dev running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Could not join with background dep_graph thread: Any', rust/src/libcore/result.rs:916:5
```

(This is a locally built rustc 1.24.0, compiled in the dev channel. It is being invoked from Buck in a custom build system, which is why the paths are atypical.)

It appears that the file is truncated, or corrupt in some way that makes it try to parse off the end of the file. This was on a machine that had been running into out-of-memory conditions, so its possible its a left-over from a previous failed compilation attempt.

I think rustc should handle corrupted incremental data by handling the error, deleting the file and compiling non-incrementally.

### PR DESCRIPTION
**Pull request by wesleywiser**
If the cached data can't be loaded from disk, just issue a warning to
the user so they know why compilation is taking longer than usual but
don't fail the entire compilation since we can recover by ignorning the
on disk cache.

In the same way, if the disk cache can't be deserialized (because it has
been corrupted for some reason), report the issue as a warning and
continue without failing the compilation. `Decodable::decode()` tends to
panic with various errors like "entered unreachable code" or "index out
of range" if the input data is corrupted. Work around this by catching
panics from the `decode()` calls and continuing without the cached data.

Fixes #48847

### CODE REVIEW

**Comment by cramertj** [comment]
Not sure who to give this to, but definitely not me, so r? @michaelwoerister

File: src/librustc_incremental/persist/load.rs [hunk 1]
```diff
@@ -168,35 +170,40 @@ pub fn load_dep_graph(sess: &Session) ->
...
+                    .expect("Error reading cached dep-graph");
+
+                LoadResult::Ok { data: PreviousDepGraph::new(dep_graph) }
             }
+        }
+    };
+
+    MaybeAsync::Async(std::thread::spawn(move || {
+        time_ext(time_passes, None, "background load prev dep-graph", move || {
+            panic::catch_unwind(load).unwrap_or_else(
```
Comment (Mark-Simulacrum) [inline src/librustc_incremental/persist/load.rs]: Do we need to catch the unwind? Can't we just handle this on thread.join() since we're paying that cost anyway?

File: src/librustc_incremental/persist/load.rs [hunk 2]
```diff
@@ -168,35 +170,40 @@ pub fn load_dep_graph(sess: &Session) ->
...
+                |_| LoadResult::Error { message: "could not decode incremental cache".into() })
```
Comment (oli-obk) [inline src/librustc_incremental/persist/load.rs]: Please emit the actual panic via a debug! or even info! call, so we can figure out what's going on without needing to rebuild the compiler.

**Comment by michaelwoerister** [comment]
Thanks for the PR, @wesleywiser! I'll take a look shortly.

File: src/librustc_incremental/persist/load.rs (hunk 1 above)
Comment (wesleywiser) [reply src/librustc_incremental/persist/load.rs]: That's a good idea! I will do some testing and see if that works.

File: src/librustc_incremental/persist/load.rs (hunk 2 above)
Comment (wesleywiser) [reply src/librustc_incremental/persist/load.rs]: I couldn't figure out a way to do this. I tried doing formatting the error into the message with `format!("could not decode incremental cache: {:?}", e)` but that just printed `"could not decode incremental cache: Any"`.

Comment (michaelwoerister) [reply src/librustc_incremental/persist/load.rs]: Maybe someone for @rust-lang/libs knows how to do this best?

File: src/librustc_incremental/persist/load.rs (hunk 1 above)
Comment (michaelwoerister) [reply src/librustc_incremental/persist/load.rs]: Yes, that's a good suggestion.

File: src/librustc_incremental/persist/load.rs (hunk 2 above)
Comment (alexcrichton) [reply src/librustc_incremental/persist/load.rs]: There's currently no easy way to get out the message of a `Box<Any>` unfortunately, but we also tend to recommend against using `catch_unwind` for error handling like this and would instead recommend returning an `Err` all the way up (which can then be printed)

Comment (wesleywiser) [reply src/librustc_incremental/persist/load.rs]: The panic handler for the thread is still running so the compiler output looks like this:

```
   Compiling webrender v0.57.0 (file:///Users/wesley/code/rust/temp3/webrender/webrender)
thread '<unnamed>' panicked at 'internal error: entered unreachable code', librustc/dep_graph/dep_node.rs:124:34
note: Run with `RUST_BACKTRACE=1` for a backtrace.
warning: could not decode incremental cache
```

**Comment by michaelwoerister** [comment]
Thanks, @wesleywiser! 

@bors r+

**Comment by wesleywiser** [comment]
Rebased

**Comment by jsgf** [comment]
Thanks for fixing this!
