### PR TITLE
use `ParamName` to track in-scope lifetimes instead of Ident

### LINKED ISSUE #52532: In-band lifetimes stop working when in a nested function
```rust
#![feature(rust_2018_preview)]

fn main() {}

struct Bar<'a>(&'a u32);

impl Bar<'a> {
    fn foo() {
        fn foo(_: &'a u32) { } // error: use of undeclared lifetime name `'a`
    }
}
```

https://play.rust-lang.org/?gist=d2b32bc0947a05fa0830a0d244dcb4fa&version=nightly&mode=debug&edition=2015

### LINKED ISSUE #63225: Error with nested async fn and anonymous lifetimes
The following breaks on nightly (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a1aabca3f0059c24f101e3a149632fbd))

```rust
#![feature(async_await)]

struct Foo<'a>(&'a ());

impl Foo<'_> {
    fn test() {
        async fn test() {}
    }
}
```

With:

```
error[E0261]: use of undeclared lifetime name `'_`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0261`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

CC: dtolnay/async-trait#18

### LINKED ISSUE #63500: async fn methods and impl `'_` elision do not interact correctly
As [reported by @cramertj](https://github.com/rust-lang/rust/issues/63225#issuecomment-519163528), this example:

```rust
#![feature(async_await)]

struct Foo<'a>(&'a u8);

impl Foo<'_> {
    async fn bar() {}
}
```
currently produces this error:
```
error[E0261]: use of undeclared lifetime name `'_`

error: aborting due to previous error
```

but it should work just fine.

### PR DESCRIPTION
**Pull request by nikomatsakis**
Also, clear in-scope lifetimes when visiting nested items.

Fixes #63500.
Fixes #63225.
Fixes #52532.

r? @cramertj

### CODE REVIEW

File: src/librustc/hir/lowering.rs [hunk 1]
```diff
@@ -865,7 +865,7 @@ impl<'a> LoweringContext<'a> {
             return;
         }
 
-        if self.in_scope_lifetimes.contains(&ident.modern()) {
+        if self.in_scope_lifetimes.contains(&ParamName::Plain(ident.modern())) {
```
Comment (cramertj) [inline src/librustc/hir/lowering.rs]: I don't think this check is correct anymore-- it's failing when it should succeed, causing lifetimes to be introduced multiple times (see the travis error). It should instead check if there is an in scope lifetime that uses the same identifier, right?

Comment (nikomatsakis) [reply src/librustc/hir/lowering.rs]: Hmm. Is it the `ident.modern()` that's causing the problem, you think?

Comment (nikomatsakis) [reply src/librustc/hir/lowering.rs]: I think I have a fix now

**Comment by nikomatsakis** [comment]
@cramertj I just pushed an additional commit with a fix for https://github.com/rust-lang/rust/issues/63225 -- can you re-review?
