### PR TITLE
rustdoc: handle cross-crate RPITITs correctly

### LINKED ISSUE #113929: rustdoc RPITIT ICE: `compiler\rustc_middle\src\ty\generic_args.rs:900:9: type parameter `impl ToString/#1` (impl ToString/1) out of range when substituting, args=[MyStruct]`
The `cargo doc` command causes an ICE error. This happens when we use the features of `#[feature(return_position_impl_trait_in_trait)]` (`impl Trait`) in different workspaces.

### Code

```toml
[workspace]
members = ["workspace-a", "workspace-b"]
resolver = "2"
```

**workspace-a**/src/lib.rs :
```Rust
use workspace_b::MyTrait;

pub struct MyStruct;

impl MyTrait for MyStruct {}
```

**workspace-b**/src/lib.rs :
```Rust
#![feature(return_position_impl_trait_in_trait)]

pub trait MyTrait {
    fn hello(_: impl ToString) -> impl Default {}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (39f42ad9e 2023-07-19)
binary: rustc
commit-hash: 39f42ad9e8430a8abb06c262346e89593278c515
commit-date: 2023-07-19
host: x86_64-pc-windows-msvc
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error: internal compiler error: compiler\rustc_middle\src\ty\generic_args.rs:900:9: type parameter `impl ToString/#1` (impl ToString/1) out of range when substituting, args=[MyStruct]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/39f42ad9e8430a8abb06c262346e89593278c515\compiler\rustc_errors\src\lib.rs:1651:9

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.73.0-nightly (39f42ad9e 2023-07-19) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [is_impossible_method] checking if `workspace_b::MyTrait::{opaque#0}` is impossible to call within `<impl at workspace-a\src\lib.rs:5:1: 5:26>`
end of query stack
error: could not document `workspace-a`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name workspace_a workspace-a\src\lib.rs -o C:\Users\PhiSyX\Labs\test\rust-doc\target\doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=103 -C metadata=3bf3f8c83c26edc0 -L dependency=C:\Users\PhiSyX\Labs\test\rust-doc\target\debug\deps --extern workspace_b=C:\Users\PhiSyX\Labs\test\rust-doc\target\debug\deps\libworkspace_b-797ce636f4eee694.rmeta --crate-version 0.1.0` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/39f42ad9e8430a8abb06c262346e89593278c515\compiler\rustc_errors\src\lib.rs:1651:9
stack backtrace:
   0:     0x7ffd1ffb812c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0dff57502b84ae55
   1:     0x7ffd1fff1e1b - core::fmt::write::h37362cd9ebacde36
   2:     0x7ffd1ffad421 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h84a5016f3ff21fcf
   3:     0x7ffd1ffb7edb - std::sys::common::alloc::realloc_fallback::hc496092f8c3f66af
   4:     0x7ffd1ffbb73a - std::panicking::default_hook::h5affd2c37c289324
   5:     0x7ffd1ffbb397 - std::panicking::default_hook::h5affd2c37c289324
   6:     0x7ffcb3bc8500 - rustc_driver_impl[64a7dfb7d520951d]::describe_lints
   7:     0x7ffd1ffbc038 - std::panicking::rust_panic_with_hook::h6db59a9929652506
   8:     0x7ffcb4d08673 - <rustc_middle[65cd754bbc6f0771]::ty::sty::ExistentialProjection as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
   9:     0x7ffcb4d06bd9 - <rustc_middle[65cd754bbc6f0771]::ty::sty::ExistentialProjection as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffcb4ce0db9 - <rustc_middle[65cd754bbc6f0771]::ty::typeck_results::UserType as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
  11:     0x7ffcb4c9e770 - <rustc_ast[5f794c73ab5b89fb]::ast::InlineAsmOptions as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
  12:     0x7ffcb4c9e54c - <rustc_ast[5f794c73ab5b89fb]::ast::InlineAsmOptions as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
  13:     0x7ffcb4cdb63d - rustc_middle[65cd754bbc6f0771]::util::bug::bug_fmt
  14:     0x7ffcb4cdb12d - rustc_middle[65cd754bbc6f0771]::traits::specialization_graph::ancestors
  15:     0x7ffcb4cdb0fa - rustc_middle[65cd754bbc6f0771]::traits::specialization_graph::ancestors
  16:     0x7ffcb4cdb532 - rustc_middle[65cd754bbc6f0771]::util::bug::bug_fmt
  17:     0x7ffcb4d63365 - <rustc_middle[65cd754bbc6f0771]::ty::generic_args::GenericArg as rustc_middle[65cd754bbc6f0771]::ty::context::Lift>::lift_to_tcx
  18:     0x7ffcb3af9595 - <rustc_middle[65cd754bbc6f0771]::ty::generic_args::ArgFolder as rustc_type_ir[bc2610c847b845b7]::fold::TypeFolder<rustc_middle[65cd754bbc6f0771]::ty::context::TyCtxt>>::fold_ty
  19:     0x7ffcb39b316e - <rustc_middle[65cd754bbc6f0771]::ty::sty::FnSig as rustc_trait_selection[343eaea0290ae000]::traits::query::type_op::normalize::Normalizable>::type_op_method
  20:     0x7ffcb391fb78 - <rustc_trait_selection[343eaea0290ae000]::traits::select::SelectionContext>::poly_select
  21:     0x7ffcb4b16084 - rustc_trait_selection[343eaea0290ae000]::traits::wf::unnormalized_obligations
  22:     0x7ffcb4568f0b - <rustc_query_impl[8cb5bda6a677e261]::plumbing::QueryCtxt as rustc_query_system[9dcbd7aa9d35dd35]::query::QueryContext>::depth_limit_error
  23:     0x7ffcb45e54d6 - <rustc_middle[65cd754bbc6f0771]::ty::generic_args::EarlyBinder<rustc_middle[65cd754bbc6f0771]::ty::Ty> as rustc_query_system[9dcbd7aa9d35dd35]::values::Value<rustc_middle[65cd754bbc6f0771]::ty::context::TyCtxt, rustc_middle[65cd754bbc6f0771]::dep_graph::dep_node::DepKind>>::from_cycle_error
  24:     0x7ffcb35c6bcf - rustc_query_impl[8cb5bda6a677e261]::query_callbacks
  25:     0x7ffcb4608a31 - <rustc_middle[65cd754bbc6f0771]::ty::generic_args::EarlyBinder<rustc_middle[65cd754bbc6f0771]::ty::Ty> as rustc_query_system[9dcbd7aa9d35dd35]::values::Value<rustc_middle[65cd754bbc6f0771]::ty::context::TyCtxt, rustc_middle[65cd754bbc6f0771]::dep_graph::dep_node::DepKind>>::from_cycle_error
  26:     0x7ff6398e3611 - <unknown>
  27:     0x7ff63993d612 - <unknown>
  28:     0x7ff639846ae5 - <unknown>
  29:     0x7ff6398dc78f - <unknown>
  30:     0x7ff6398e1496 - <unknown>
  31:     0x7ff639731ecd - <unknown>
  32:     0x7ffd1fff1e1b - core::fmt::write::h37362cd9ebacde36
  33:     0x7ff6397b4b3d - <unknown>
  34:     0x7ff639775f60 - <unknown>
  35:     0x7ff639784952 - <unknown>
  36:     0x7ff639658115 - <unknown>
  37:     0x7ff63961002b - <unknown>
  38:     0x7ff6397dfab2 - <unknown>
  39:     0x7ff6396197b9 - <unknown>
  40:     0x7ff6396ea9e6 - <unknown>
  41:     0x7ff63961591f - <unknown>
  42:     0x7ff63971766d - <unknown>
  43:     0x7ff63971abae - <unknown>
  44:     0x7ffd1ffcf6cc - std::sys::windows::thread::Thread::new::hb464be62f345c3d5
  45:     0x7ffd5d8b244d - BaseThreadInitThunk
  46:     0x7ffd5eecdf78 - RtlUserThreadStart
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fmease**
Filter out the internal associated types synthesized during the desugaring of RPITITs, they really shouldn't show up in the docs.

This also fixes #113929 since we're no longer invoking `is_impossible_associated_item` (renamed from `is_impossible_method`) which cannot handle them (leading to an ICE). I don't think it makes sense to try to make `is_impossible_associated_item` handle this exotic kind of associated type (CC original author @compiler-errors).

@ T-rustdoc reviewers, currently I'm throwing out ITIT assoc tys before cleaning assoc tys at each usage-site. I'm thinking about making `clean_middle_assoc_item` return an `Option<_>` instead and doing the check inside of it to prevent any call sites from forgetting the check for ITITs. Since I wasn't sure if you would like that approach, I didn't go through with it. Let me know what you think.

<details><summary>Explanation on why <code>is_impossible_associated_item(itit_assoc_ty)</code> leads to an ICE</summary>

Given the following code:

```rs
pub trait Trait { fn def<T>() -> impl Default {} }
impl Trait for () {}
```

The generated associated type looks something like (simplified):

```rs
type {opaque#0}<T>: Default = impl Default; // the name is actually `kw::Empty` but this is the `def_path_str` repr
```

The query `is_impossible_associated_item` goes through all predicates of the associated item – in this case `<T as Sized>` – to check if they contain any generic parameters from the (generic) associated type itself. For predicates that don't contain any *own* generics, it does further processing, part of which is instantiating the predicate with the generic arguments of the impl block (which is only correct if they truly don't contain any own generics since they wouldn't get instantiated this way leading to an ICE).

It checks if `parent_def_id(T) == assoc_ty_def_id` to get to know if `T` is owned by the assoc ty. Unfortunately this doesn't work for ITIT assoc tys. In this case, the parent of `T` is `Trait::def` (!) which is the associated function (I'm pretty sure this is very intentional) which is of course not equal to the assoc ty `Trait::{opaque#0}`.

</details>

@rustbot label A-cross-crate-reexports

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 1]
```diff
@@ -474,11 +474,14 @@ fn subst_and_check_impossible_predicates<'tcx>(
     result
 }
 
-/// Checks whether a trait's method is impossible to call on a given impl.
+/// Checks whether a trait's associated item is impossible to reference on a given impl.
 ///
 /// This only considers predicates that reference the impl's generics, and not
 /// those that reference the method's generics.
-fn is_impossible_method(tcx: TyCtxt<'_>, (impl_def_id, trait_item_def_id): (DefId, DefId)) -> bool {
+fn is_impossible_associated_item(
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/mod.rs:481]: I've renamed this since the previous name confused me quite a bit at first, I wasn't sure if the ICE happens due to the method w/ RPITIT or due to the synthetic RPITIT type. It can every kind of associated item just fine (even generic consts I assume) and rustdoc does use the query for every kind already.

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 2]
```diff
@@ -474,11 +474,14 @@ fn subst_and_check_impossible_predicates<'tcx>(
...
+    tcx: TyCtxt<'_>,
+    (impl_def_id, trait_item_def_id): (DefId, DefId),
+) -> bool {
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/mod.rs:484]: Ofc, we could just defensively check at the start if the assoc item `is_impl_trait_in_trait` and if so return `false`. Wouldn't be reachable at this point in time but it might be in the future if this query gained more users.

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/mod.rs:481]: Yeah, it used to be used during codegen to skip monomorphizing methods that have impossible to solve predicates, but now it's used for other things.

**Comment by compiler-errors** [comment]
> (I'm pretty sure this is very intentional)

Not really, ideally the GAT that we synthesize for an RPITIT should own all of its non-impl generics. That's a different story though, and is difficult to fix for its own reasons.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me. I'll let @compiler-errors have the final word though. ;)
