### PR TITLE
Fix HIR visit order

### LINKED ISSUE #61442: Broken MIR in futures generator (async/await)
## Issue
The code below causes an internal compiler error. I've provided some more details as comments.

```
error: internal compiler error: src/librustc_mir/transform/generator.rs:532: Broken MIR: generator contains type &mut std::string::String in MIR, but typeck only knows about for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7> {Update, u64, std::string::String, for<'t8> fn(std::fmt::Arguments<'t8>) -> std::string::String {std::fmt::format}, fn(&'r [&'r str], &'r [std::fmt::ArgumentV1<'r>]) -> std::fmt::Arguments<'r> {std::fmt::Arguments::<'r>::new_v1}, &'s str, str, &'t0 str, [&'t1 str; 1], &'t2 [&'t3 str; 1], &'t4 [&'t5 str; 1], &'t6 [&'t7 str], impl core::future::future::Future, ()}
  --> src/main.rs:32:41
   |
32 |   async fn perform_update(update: Update) {
   |  _________________________________________^
33 | |     if let Update::User(id) = update {
34 | |         let mut reply = String::new();
35 | |         reply += &format!("{}", get_user(id).await);
36 | |     }
37 | | }
   | |_^
```
## Code
```rust 
#![feature(async_await)]

use std::fmt;

#[derive(Default)]
struct User {
    first_name: String,
    last_name: Option<String>,
    username: Option<String>,
}

impl fmt::Display for User {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        if let Some(u) = &self.username {
            write!(f, "{}", u)
        } else if let Some(last) = &self.last_name {
            write!(f, "{} {}", self.first_name, last)
        } else {
            write!(f, "{}", self.first_name)
        }
    }
}

async fn get_user(id: u64) -> User {
    unimplemented!()
}

enum Update {
    User(u64),
}

async fn perform_update(update: Update) {
    if let Update::User(id) = update {
        let mut reply = String::new();
        //If `reply` is assigned directly to this value, the code compiles.
        reply += &format!("{}", get_user(id).await);
    }
}

fn main() {
    //Compiles when this line is omitted, using futures-preview 0.3.0-alpha.16
    futures::executor::block_on(perform_update(Update::User(Default::default())));
}
```

## Meta
rustc 1.37.0-nightly (7840a0b75 2019-05-31)
binary: rustc
commit-hash: 7840a0b753a065a41999f1fb6028f67d33e3fdd5
commit-date: 2019-05-31
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:572:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/libunwind.rs:97
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   8: std::panicking::begin_panic
   9: rustc_errors::Handler::span_bug
  10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc::ty::context::tls::with_opt::{{closure}}
  12: rustc::ty::context::tls::with_context_opt
  13: rustc::ty::context::tls::with_opt
  14: rustc::util::bug::opt_span_bug_fmt
  15: rustc::util::bug::span_bug_fmt
  16: <rustc_mir::transform::generator::StateTransform as rustc_mir::transform::MirPass>::run_pass
  17: rustc_mir::transform::run_passes::{{closure}}
  18: rustc_mir::transform::run_passes
  19: rustc_mir::transform::optimized_mir
  20: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  21: rustc::dep_graph::graph::DepGraph::with_task_impl
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  23: rustc::ty::layout::LayoutCx<rustc::ty::context::TyCtxt>::layout_raw_uncached
  24: rustc::ty::layout::layout_raw
  25: rustc::ty::query::__query_compute::layout_raw
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::layout_raw>::compute
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  29: <rustc::ty::layout::LayoutCx<rustc::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  30: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  31: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  32: rustc_mir::transform::run_passes::{{closure}}
  33: rustc_mir::transform::run_passes
  34: rustc_mir::transform::optimized_mir
  35: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  36: rustc::dep_graph::graph::DepGraph::with_task_impl
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  41: rustc::util::common::time
  42: rustc_mir::monomorphize::collector::collect_crate_mono_items
  43: rustc::util::common::time
  44: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  45: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  46: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_and_partition_mono_items>::compute
  47: rustc::dep_graph::graph::DepGraph::with_task_impl
  48: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  49: rustc_codegen_ssa::base::codegen_crate
  50: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  51: rustc::util::common::time
  52: rustc_interface::passes::start_codegen
  53: rustc::ty::context::tls::enter_global
  54: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  55: rustc_interface::passes::create_global_ctxt::{{closure}}
  56: rustc_interface::passes::BoxedGlobalCtxt::enter
  57: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  58: rustc_interface::interface::run_compiler_in_existing_thread_pool
  59: std::thread::local::LocalKey<T>::with
  60: scoped_tls::ScopedKey<T>::set
  61: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
#0 [optimized_mir] processing `perform_update::{{closure}}#0`
#1 [layout_raw] computing layout of `[static generator@src/main.rs:32:41: 37:2 update:Update for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7> {Update, u64, std::string::String, for<'t8> fn(std::fmt::Arguments<'t8>) -> std::string::String {std::fmt::format}, fn(&'r [&'r str], &'r [std::fmt::ArgumentV1<'r>]) -> std::fmt::Arguments<'r> {std::fmt::Arguments::<'r>::new_v1}, &'s str, str, &'t0 str, [&'t1 str; 1], &'t2 [&'t3 str; 1], &'t4 [&'t5 str; 1], &'t6 [&'t7 str], std::future::GenFuture<[static generator@src/main.rs:24:36: 26:2 id:u64 {}]>, ()}]`
#2 [optimized_mir] processing `perform_update`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #61442

When rustc::middle::region::ScopeTree computes its yield_in_scope
field, it relies on the HIR visitor order to properly compute which
types must be live across yield points. In order for the computed scopes
to agree with the generated MIR, we must ensure that expressions
evaluated before a yield point are visited before the 'yield'
expression.

However, the visitor order for ExprKind::AssignOp
was incorrect. The left-hand side of a compund assignment expression is
evaluated before the right-hand side, but the right-hand expression was
being visited before the left-hand expression. If the left-hand
expression caused a new type to be introduced (e.g. through a
deref-coercion), the new type would be incorrectly seen as occuring
*after* the yield point, instead of before. This leads to a mismatch
between the computed generator types and the MIR, since the MIR will
correctly see the type as being live across the yield point.

To fix this, we correct the visitor order for ExprKind::AssignOp
to reflect the actual evaulation order.

### CODE REVIEW

**Comment by matthewjasper** [comment]
The original order is correct for built-in operators. This looks like it would cause the same issue for something like `let x = &mut 0; *{ yield; x } += match String::new() { _ => 0 };`

**Comment by varkor** [comment]
Let's make sure we add a test for @matthewjasper's example.

**Comment by Aaron1011** [comment]
Unfortunately, my previous approach turned out to be completely incompatible with the fact that `AssignOp` has two possible evaluation orders. I've come up with a new solution - instead of trying to predict which evaluation order will actually be used, we compute the 'worst-case' indices, which will work whether the actual order is left-to-right or right-to-left.

**Comment by Aaron1011** [comment]
@varkor: This should be ready for review

**Comment by nikomatsakis** [comment]
@Aaron1011 Are you able to test this PR against #61579 (and maybe #61731)?

File: src/test/run-pass/issues/issue-61442.rs [hunk 1]
```diff
@@ -0,0 +1,28 @@
+#![feature(generators)]
```
Comment (Centril) [inline src/test/run-pass/issues/issue-61442.rs]: I really don't like having a bunch of numbered issues in `run-pass` (instead of `compile-pass`) with zero description of what this is supposed to test...

Comment (Centril) [reply src/test/run-pass/issues/issue-61442.rs]: I think this test should be moved to the other generator tests wherever they are.

**Comment by Zoxc** [comment]
This inconsistency seems like a bug to me. cc @rust-lang/lang

**Comment by petrochenkov** [comment]
>This inconsistency seems like a bug to me.

This is https://github.com/rust-lang/rust/issues/28160 if I'm not mistaken.
(Some discussions on internals - https://internals.rust-lang.org/t/rust-expression-order-of-evaluation/2605, https://internals.rust-lang.org/t/settling-execution-order-for/4253)

I didn't follow this closely in the last couple of years, but I expected the order to be unified together with introduction of NLL and two-phase borrows.
Apparently this didn't happen :(

**Comment by petrochenkov** [comment]
(The `a += f(a);` seems equivalent to `v.push(v.len())`, that's why I hoped for two-phase borrows to make the switch to the left-to-right order for all assignments possible.)

**Comment by msizanoen** [comment]
This PR should not be tested against https://github.com/rust-lang/rust/issues/61579 and https://github.com/rust-lang/rust/issues/61731 (see https://github.com/rust-lang/rust/issues/61731#issuecomment-501695721)

**Comment by Centril** [comment]
We discussed this on Thursday's language team meeting. Based on the understanding that:

> I've come up with a new solution - instead of trying to predict which evaluation order will actually be used, we compute the 'worst-case' indices, which will work whether the actual order is left-to-right or right-to-left.

we feel comfortable with landing this specific PR.

However, we would like discuss and settle the execution order of `AssignOp` definitively at some other juncture.

**Comment by nrc** [comment]
ping @Centril @Aaron1011 What needs to be done to land this? I'd appreciate it if you could up the priority on this one since it is an ICE which prevents compilation with no obvious workaround (and in particular, it means we can't compile one of our projects).

**Comment by cramertj** [comment]
@nrc I read all the comments above as resolved. @varkor's only comment was
> Let's make sure we add a test for @matthewjasper's example.

and a test has since been added. The [language team was okay with this going through](https://github.com/rust-lang/rust/pull/61572#issuecomment-502417122), and the [MIR ICE tests that were asked for are actually unrelated issues](https://github.com/rust-lang/rust/pull/61572#issuecomment-501704633) solved by https://github.com/rust-lang/rust/pull/61872. With that in mind, I think this  is just waiting on @varkor to r+.

**Comment by varkor** [comment]
I'm sorry, I've been very busy recently. I will get to this soon, but someone is welcome to take the review if this is urgent.

File: src/test/run-pass/issues/issue-61442.rs (hunk 1 above)
Comment (cramertj) [reply src/test/run-pass/issues/issue-61442.rs]: src/test/run-pass/generator/

**Comment by Aaron1011** [comment]
@Centril: I've moved the test as you requested.

File: src/librustc/middle/region.rs [hunk 2]
```diff
@@ -371,6 +371,19 @@ struct RegionResolutionVisitor<'tcx> {
 
     // The number of expressions and patterns visited in the current body
     expr_and_pat_count: usize,
+    // When this is 'true', we record the Scopes we encounter
+    // when processing a Yield expression. This allows us to fix
+    // up their indices.
+    pessimistic_yield: bool,
+    // Stores scopes when pessimistic_yield is true.
+    // Each time we encounter an ExprKind::AssignOp, we push
+    // a new Vec into the outermost Vec. This inner Vec is uesd
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // a new Vec into the outermost Vec. This inner Vec is used
```

File: src/librustc/middle/region.rs [hunk 3]
```diff
@@ -371,6 +371,19 @@ struct RegionResolutionVisitor<'tcx> {
 
     // The number of expressions and patterns visited in the current body
     expr_and_pat_count: usize,
+    // When this is 'true', we record the Scopes we encounter
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // When this is `true`, we record the `Scopes` we encounter
```
Generally, identifiers are surrounded in backticks in comments (here and elsewhere).

File: src/librustc/middle/region.rs [hunk 4]
```diff
@@ -371,6 +371,19 @@ struct RegionResolutionVisitor<'tcx> {
...
+    // when processing a Yield expression. This allows us to fix
+    // up their indices.
+    pessimistic_yield: bool,
+    // Stores scopes when pessimistic_yield is true.
+    // Each time we encounter an ExprKind::AssignOp, we push
+    // a new Vec into the outermost Vec. This inner Vec is uesd
+    // to store any scopes we encounter when visiting the inenr expressions
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // to store any scopes we encounter when visiting the inner expressions
```

File: src/librustc/middle/region.rs [hunk 5]
```diff
@@ -371,6 +371,19 @@ struct RegionResolutionVisitor<'tcx> {
...
+    // of the AssignOp. Once we finish visiting the inner expressions, we pop
+    // off the inner Vec, and process the Scopes it contains.
+    // This allows us to handle nested AssignOps - while a terrible idea,
```
Comment (varkor) [inline src/librustc/middle/region.rs]: (`while a terrible idea` — citation needed 😁)

File: src/librustc/middle/region.rs [hunk 6]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
         }
     }
 
+    let prev_pessimistic = visitor.pessimistic_yield;
+
+    // Ordinarily, we can rely on the visit order of HIR intravisit
+    // to correspond to the actual exectuion order of statements.
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // to correspond to the actual execution order of statements.
```

File: src/librustc/middle/region.rs [hunk 7]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+    // However, there's a weird corner case with compund assignment
+    // operators (e.g. 'a += b'). The evaluation order depends on whether
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // operators (e.g. `a += b`). The evaluation order depends on whether
```

File: src/librustc/middle/region.rs [hunk 8]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+    //    let y = &mut 0;
+    //    *{println!("LHS!"); y} += {println!("RHS!"); 1};
+    //
+    // will print:
+    //
+    // RHS!
+    // LHS!
+    //
+    // However, if the operator is used on a non-primitive type,
+    // the evaluation order will be left-to-right, since the operator
```
Comment (varkor) [inline src/librustc/middle/region.rs]: 😓

File: src/librustc/middle/region.rs [hunk 9]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+    //    *{println!("LHS String"); y} += {println!("RHS String"); "hi"};
+    //
+    // will print:
+    // LHS String
+    // RHS String
+    //
+    // To determine the actual execution order, we need to perform
+    // trait resolution. Unfortunately, we need to be able to compute
+    // yield_in_scope before type checking is even done, as it gets
+    // used by AST borrowcheck
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // used by AST borrowcheck.
```

File: src/librustc/middle/region.rs [hunk 10]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+    //
+    // Fortunately, we don't need to know the actual execution order.
+    // It sufficies to know the 'worst case' order with respect to yields.
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
    // It suffices to know the 'worst case' order with respect to yields.
```

File: src/librustc/middle/region.rs [hunk 11]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+
+
     match expr.node {
         // Manually recurse over closures, because they are the only
         // case of nested bodies that share the parent environment.
         hir::ExprKind::Closure(.., body, _, _) => {
             let body = visitor.tcx.hir().body(body);
             visitor.visit_body(body);
+        },
+        hir::ExprKind::AssignOp(_, ref left_expression, ref right_expression) => {
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
        hir::ExprKind::AssignOp(_, ref left_expr, ref right_expr) => {
```
`expr` is a common abbreviation in this kind of situation.

File: src/librustc/middle/region.rs [hunk 12]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+            debug!("resolve_expr - enabling pessimistic_yield, was previously {}",
+                   prev_pessimistic);
+
+            visitor.fixup_scopes.push(vec![]);
+            visitor.pessimistic_yield = true;
+
+            // If the actual execution order turns out to be right-to-left,
+            // then we're fine. However, if the actual execution order is left-to-right,
+            // then we'll assign too low of a count to any 'yield' expressions
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
            // then we'll assign too low a count to any `yield` expressions
```

File: src/librustc/middle/region.rs [hunk 13]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
+            // we encounter in 'right_expression' - they should really occur after all of the
+            // expressions in 'left_expression'.
+            visitor.visit_expr(&right_expression);
+
+            visitor.pessimistic_yield = prev_pessimistic;
+
+            let target_scopes = visitor.fixup_scopes.pop().unwrap();
+            debug!("resolve_expr - restoring pessimistic_yield to {}", prev_pessimistic);
+
+
```
Comment (varkor) [inline src/librustc/middle/region.rs]: (Remove this line.)

File: src/librustc/middle/region.rs [hunk 14]
```diff
@@ -1360,6 +1473,8 @@ fn region_scope_tree<'tcx>(tcx: TyCtxt<'tcx>, def_id: DefId) -> &'tcx ScopeTree
                 var_parent: None,
             },
             terminating_scopes: Default::default(),
+            pessimistic_yield: false,
+            fixup_scopes: vec![]
```
Comment (varkor) [inline src/librustc/middle/region.rs]:
```suggestion
            fixup_scopes: vec![],
```

File: src/librustc_typeck/check/generator_interior.rs [hunk 15]
```diff
@@ -28,8 +28,14 @@ impl<'a, 'tcx> InteriorVisitor<'a, 'tcx> {
...
         use syntax_pos::DUMMY_SP;
 
+        debug!("generator_interior: attempting to record type {:?} {:?} {:?} {:?}",
+               ty, scope, expr, source_span);
+
+
         let live_across_yield = scope.map(|s| {
             self.region_scope_tree.yield_in_scope(s).and_then(|yield_data| {
+
+
```
Comment (varkor) [inline src/librustc_typeck/check/generator_interior.rs]: (Remove this line.)

File: src/test/run-pass/generator/addassign-yield.rs [hunk 16]
```diff
@@ -0,0 +1,34 @@
...
+        let mut s = String::new();
+        s += { yield; "" };
+    };
+
+    let _y = static || {
+        let x = &mut 0;
+        *{ yield; x } += match String::new() { _ => 0 };
+    };
+
+    // Please don't ever actually write something like this
```
Comment (varkor) [inline src/test/run-pass/generator/addassign-yield.rs]: 😄

File: src/librustc/middle/region.rs [hunk 17]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
...
         // case of nested bodies that share the parent environment.
         hir::ExprKind::Closure(.., body, _, _) => {
             let body = visitor.tcx.hir().body(body);
             visitor.visit_body(body);
+        },
+        hir::ExprKind::AssignOp(_, ref left_expression, ref right_expression) => {
+            debug!("resolve_expr - enabling pessimistic_yield, was previously {}",
+                   prev_pessimistic);
+
+            visitor.fixup_scopes.push(vec![]);
```
Comment (varkor) [inline src/librustc/middle/region.rs]: Instead of using a `Vec<Vec<_>>`, can we use a single `Vec<_>` as a stack, and just iterate over the new `Scope`s?

Comment (varkor) [reply src/librustc/middle/region.rs]: This way, it would be easier to combine `fixup_scopes` and `pessimistic_yield` too.

File: src/librustc/middle/region.rs [hunk 18]
```diff
@@ -947,12 +960,108 @@ fn resolve_expr<'tcx>(visitor: &mut RegionResolutionVisitor<'tcx>, expr: &'tcx h
         }
     }
 
+    let prev_pessimistic = visitor.pessimistic_yield;
+
+    // Ordinarily, we can rely on the visit order of HIR intravisit
```
Comment (varkor) [inline src/librustc/middle/region.rs]: This is a very clear explanation 👍

**Review by varkor — CHANGES_REQUESTED** [review]
The general method looks reasonable to me, but I had one query about simplifying the representation (and a small handful of comment typos).

File: src/librustc/middle/region.rs (hunk 17 above)
Comment (Aaron1011) [reply src/librustc/middle/region.rs]: That would require me to also keep track of the starting index for new scopes. I think using a `Vec<Vec<_>>` makes the intention clear, and avoids any off-by-one errors that might otherwise occur.

Comment (varkor) [reply src/librustc/middle/region.rs]: We'd only need to store the starting indices in a local variable, rather than a visitor, which should make things clear, I think. I imagine it'll reduce allocation too.

**Comment by Aaron1011** [comment]
@varkor: I've eliminated the `Vec<Vec<_>>`

**Comment by Aaron1011** [comment]
@varkor: The failure appears to be an instance of https://github.com/rust-lang/rust/issues/58209
