### PR TITLE
Combine three generalizer implementations

### LINKED ISSUE #109505: No universe checks for ty/const infer vars and placeholders
rustc currently lacks any checks to ensure that relating ty/const infer vars with ty/const placeholders in higher universes fails. I am not entirely sure whether this is problematic for _stable_ rust or just `feature(non_lifetime_binders)` I think exploiting this would require us to create obligations with type/const binders. We currently create _param envs_ with `for<T>` predicates on stable for checking gat bounds, but I couldn't find anywhere that we create obligations with type/const bound vars. 

### Code

```Rust
#![feature(non_lifetime_binders)]
#![allow(incomplete_features)]

trait Other<U: ?Sized> {}

impl<U: ?Sized> Other<U> for U {}

//  - o: `for<T> T: Trait<?0>`
//    - c: `for<U> U: Trait<U>`
//      - U = ?1
//      - T = ?1
//      - ?0 = ?1

#[rustfmt::skip]
fn foo<U: ?Sized>()
where
    for<T> T: Other<U> {}

fn bar() {
    foo::<_>();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (8a73f50d8 2023-03-11)
binary: rustc
commit-hash: 8a73f50d875840b8077b8ec080fa41881d7ce40d
commit-date: 2023-03-11
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

```
```

<details><summary><strong>Backtrace</strong></summary>
<p>

no backtrace because github claims "Comment is too long" :roll_eyes: 
</p>
</details>

### LINKED ISSUE #111092: merge generalizer impls
we currently have 3 different implementations of "generalization":

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/combine/struct.Generalizer.html

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/nll_relate/struct.TypeGeneralizer.html

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/combine/struct.ConstInferUnifier.html

These 3 should have the same behavior and should be merged.

cc #109813 where we have to do the same change in each of the generalizers.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #111092
Fixes #109505

This code is a bit delicate and there were subtle changes between them, so I'll leave inline comments where further inspection is needed.

Regarding this comment from #109813 -- "add tests triggering all codepaths: at least the combine and the const generalizer", can't really do that now, and I don't really know how we'd get a higher-ranked const error since non-lifetime binders doesn't *really* support `for<const ..>` (it errors out when you try to use it).

r? @lcnr

### CODE REVIEW

File: compiler/rustc_infer/src/infer/combine.rs [hunk 1]
```diff
@@ -299,24 +292,17 @@ impl<'tcx> InferCtxt<'tcx> {
...
-            for_universe,
+        let span =
+            self.inner.borrow_mut().const_unification_table().probe_value(target_vid).origin.span;
+        let Generalization { value, needs_wf: _ } = generalize(
+            self,
+            &mut CombineDelegate { infcx: self, span, param_env },
+            ct,
             target_vid,
-        })?;
+            ty::Variance::Invariant,
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/combine.rs:304]: There's not really variance here...

File: compiler/rustc_infer/src/infer/combine.rs [hunk 2]
```diff
@@ -299,24 +292,17 @@ impl<'tcx> InferCtxt<'tcx> {
...
-                ConstVariableValue::Unknown { universe } => (universe, var_value.origin.span),
-            }
-        };
-        let value = ct.try_fold_with(&mut ConstInferUnifier {
-            infcx: self,
-            span,
-            for_universe,
+        let span =
+            self.inner.borrow_mut().const_unification_table().probe_value(target_vid).origin.span;
+        let Generalization { value, needs_wf: _ } = generalize(
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/combine.rs:299]: We perhaps should be registering WF obligation here. Previous implementation (`ConstInferUnifier`) did not, though, so this isn't breaking afaict.

File: compiler/rustc_infer/src/infer/nll_relate/mod.rs [hunk 3]
```diff
@@ -223,23 +222,10 @@ where
...
-            delegate: &mut self.delegate,
-            first_free_index: ty::INNERMOST,
-            ambient_variance: self.ambient_variance,
-            for_vid_sub_root: self.infcx.inner.borrow_mut().type_variables().sub_root_var(for_vid),
-            universe,
-        };
-
-        generalizer.relate(value, value)
+    fn generalize(&mut self, ty: Ty<'tcx>, for_vid: ty::TyVid) -> RelateResult<'tcx, Ty<'tcx>> {
+        let Generalization { value: ty, needs_wf: _ } =
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/nll_relate/mod.rs:226]: We perhaps should be registering WF obligation here. Previous implementation (`TypeGeneralizer`) did not, though, so this isn't breaking afaict.

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 4]
```diff
@@ -0,0 +1,492 @@
...
+                            let new_var_id = variable_table.new_key(ConstVarValue {
+                                origin: var_value.origin,
+                                val: ConstVariableValue::Unknown { universe: self.for_universe },
+                            });
+                            Ok(self.tcx().mk_const(new_var_id, c.ty()))
+                        }
+                    }
+                }
+            }
+            ty::ConstKind::Unevaluated(ty::UnevaluatedConst { def, substs }) => {
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/generalize.rs:432]: The old behavior of the NLL generalizer did this:

```rust
ty::ConstKind::Unevaluated(..) if self.tcx().lazy_normalization() => Ok(a),
```

Not exactly sure what's more correct here. I guess we probably shouldn't be generalizing aliases? But in that case, we need to be emitting a const vid and an alias relate (or const equate) here, right?

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 5]
```diff
@@ -0,0 +1,492 @@
...
+                Ok(if s == substs { t } else { self.tcx().mk_opaque(def_id, s) })
+            }
+            _ => relate::super_relate_tys(self, t, t),
+        }?;
+
+        self.cache.insert(t, g);
+        Ok(g)
+    }
+
+    fn regions(
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/generalize.rs:340]: The old implementation of the NLL generalizer always generalized regions -- there was some comment:

```
        // For now, we just always create a fresh region variable to
        // replace all the regions in the source type. In the main
        // type checker, we special case the case where the ambient
        // variance is `Invariant` and try to avoid creating a fresh
        // region variable, but since this comes up so much less in
        // NLL (only when users use `_` etc) it is much less
        // important.
        //
        // As an aside, since these new variables are created in
        // `self.universe` universe, this also serves to enforce the
        // universe scoping rules.
        //
        // FIXME(#54105) -- if the ambient variance is bivariant,
        // though, we may however need to check well-formedness or
        // risk a problem like #41677 again.
```

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/generalize.rs:340]: Also comment about bivariance, perhaps we should be setting `needs_wf` here too?

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 6]
```diff
@@ -0,0 +1,492 @@
...
+use rustc_middle::ty::relate::{self, Relate, RelateResult, TypeRelation};
+use rustc_middle::ty::{self, InferConst, Term, Ty, TyCtxt, TypeVisitableExt};
+use rustc_span::Span;
+
+use crate::infer::nll_relate::TypeRelatingDelegate;
+use crate::infer::type_variable::TypeVariableValue;
+use crate::infer::{InferCtxt, RegionVariableOrigin};
+
+#[derive(Copy, Clone, Eq, PartialEq, Debug)]
+pub enum TermVid<'tcx> {
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/generalize.rs:14]: I guess I should move this to `rustc_middle::ty`.

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/generalize.rs:420]: We should only get `ConstKind::Unevaluated` with subst if `generic_const_exprs` is enabled afaik so this shouldnt affect stable I think. Generalizing alias substs seems wrong but I think creating an infer var is also wrong since if the alias is underneath a binder the infer var would not be able to name any of its placeholders when we later relate the original ty with the generalised ty. Probably just doesn't matter to try and make generalizing aliases work correctly in this PR since its already not great and doing it correctly seems hard xd

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/generalize.rs:420]: Specifically if we have:
`for<'a> fn(<?0.0 as Trait<'a>>::Assoc) <: ?1.0`
we generalize the fn ptr to get `for<'a> fn(?2.0)`
and then we end up relating `for<'a> fn(<?0.0 as Trait<'a>>::Assoc) eq for<'a> fn(?2.0)`
once the binders are instantiated we'll end up with `fn(<?0.0 as Trait<'!a.1>>::Assoc) eq fn(?2.0)`
the `alias-relate(<?0.0 as Trait<'!a.1>>::Assoc, eq, ?2.0)` is kinda messed up,
- we cant instantiate `?2.0` with `'!a.1` if the alias ends up normalizing to the trait argument because of universe checks
- we cant just Err(NoSolution) as that's unsound in coherence since `for<'a> fn(<?0.0 as Trait<'a>>::Assoc) eq ?1.0` should be allowed to end up successful with inferring `?1.0 = for<'a> fn(Foo<'a>)` if that's how the alias ends up normalizing (not actually sure if the fact that this is lifetimes means this would play out differently, just sub it all for type placeholders I guess if so lol)

This whole thing just reminds me of the current "replace aliases with infer vars" hack in `project` and how it doesn't work for projections under binders.

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/generalize.rs:420]: I'm pretty sure that this just fundamentally cant work because of universes and actually we would need to be generalizing types with binders to an infer var (didnt realise this til lcnr said it, had just thought everything was doomed) and emitting a general relate obligation _not_ alias relate, so that we'd have `relate(for<'a> fn(<?0.0 as Trait<'a>>::Assoc, <:, ?1.0)`. We need `alias-relate` to be general purpose relate anyway to correctly handle occurs check and projections not being unsound in coherence (`Foo<<?0 as Trait>::Assoc> eq ?0>` would emit a `relate` instead of a `Err(NoSolution)`)

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/generalize.rs:420]: converting types with binders (trait objects and fn ptrs) into infer vars during generalization would inhibit inference probably in ways that are backwards incompatible, no idea to what extent this would be backwards compatible (or put another way: if its realistically something that can be broken). So it may be that its not a viable solution and actually we just want to accept generalization being incomplete and make occurs check and universe check into ambiguity during coherence instead of `NoSolution`

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 7]
```diff
@@ -0,0 +1,427 @@
...
+///
+/// [blog post]: https://is.gd/0hKvIr
+pub(super) struct Generalizer<'me, 'tcx, D>
+where
+    D: GeneralizerDelegate<'tcx>,
+{
+    pub infcx: &'me InferCtxt<'tcx>,
+
+    // An delegate used to abstract the behaviors of the three previous
+    // generalizer-like implementations.
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs]: this should probably mention that it abstracts away the difference between ordinary type system stuff and nll typeck?

people who actually care about this comment will tend to not know about the existence and reason for "the three previous generalizer-like implementations"

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 8]
```diff
@@ -0,0 +1,427 @@
...
+    }
+
+    fn relate_with_variance<T: Relate<'tcx>>(
+        &mut self,
+        variance: ty::Variance,
+        _info: ty::VarianceDiagInfo<'tcx>,
+        a: T,
+        b: T,
+    ) -> RelateResult<'tcx, T> {
+        debug!("Generalizer::relate_with_variance(variance={:?}, a={:?}, b={:?})", variance, a, b);
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs]: while you're at it, something something `#[instrument(level = "debug", skip(self, _info), ret)]`

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 9]
```diff
@@ -0,0 +1,427 @@
...
+            return Ok(result);
+        }
+        debug!("generalize: t={:?}", t);
+
+        // Check to see whether the type we are generalizing references
+        // any other type variable related to `vid` via
+        // subtyping. This is basically our "occurs check", preventing
+        // us from creating infinitely sized types.
+        let g = match *t.kind() {
+            ty::Infer(ty::TyVar(_)) | ty::Infer(ty::IntVar(_)) | ty::Infer(ty::FloatVar(_))
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs:242]: do we not want to ICE for fresh vars?

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 10]
```diff
@@ -0,0 +1,427 @@
...
+                         placeholder in universe {:?}",
+                        self.for_universe, placeholder.universe
+                    );
+                    Err(TypeError::Mismatch)
+                } else {
+                    Ok(t)
+                }
+            }
+
+            ty::Alias(ty::Opaque, ty::AliasTy { def_id, substs, .. }) => {
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs]: is that still needed? didn't we move all non-structural relating out of `super_relate_tys`?

also, do we want to rename `super_relate_X` to `structurally_relate_X` with a comment "relates the two X structurally, calling the relation for all nested values. any semantic equality, e.g. of projections, and inference variables have to be handled by the caller."?

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 5 above)
Comment (lcnr) [reply compiler/rustc_infer/src/infer/generalize.rs:328]: `needs_wf` is kind of a mess and mostly there to guide type inference during hir typeck. It is probably also necessary when equating user type annotations during nll typeck, but given that this happens inside of a query, the nll generalizer does not need add special wf obligations.

I believe that we should instead check that all locals in the mir body are well formed. But well 🤷 i guess lets keep the status quo in this PR.

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 11]
```diff
@@ -0,0 +1,427 @@
...
+            | ty::ReEarlyBound(..)
+            | ty::ReFree(..) => {
+                // see common code below
+            }
+        }
+
+        // If we are in an invariant context, we can re-use the region
+        // as is, unless it happens to be in some universe that we
+        // can't name. (In the case of a region *variable*, we could
+        // use it if we promoted it into our universe, but we don't
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs:360]: looking at this, "promote" feels wrong to me. 

we're pulling the inference variable out of its universe instead of promoting it into a universe (at least with how I think about it). If we have `exists<'a> forall<'b> exists<'c> 'a == 'c` that equality is movin `'c` out of the forall binder so it now can't name `'b`

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 4 above)
Comment (lcnr) [reply compiler/rustc_infer/src/infer/generalize.rs:415]: I think we shouldn't change this behavior in this PR even if it's incomplete.

However, similar to the opaque branch above, `super_relate_consts` is already purely structural, so we can remove that match arm as its equivalent to `super_relate_consts`.

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 12]
```diff
@@ -66,7 +97,7 @@ where
 /// establishes `'0: 'x` as a constraint.
 ///
 /// [blog post]: https://is.gd/0hKvIr
-pub(super) struct Generalizer<'me, 'tcx, D>
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs]: change fields to be private

File: compiler/rustc_infer/src/infer/combine.rs [hunk 13]
```diff
@@ -470,25 +470,17 @@ impl<'infcx, 'tcx> CombineFields<'infcx, 'tcx> {
...
-        let for_universe = self.infcx.probe_ty_var(for_vid).unwrap_err();
-        let for_vid_sub_root = self.infcx.inner.borrow_mut().type_variables().sub_root_var(for_vid);
-
-        trace!(?for_universe);
-        trace!(?self.trace);
-
-        Generalizer {
-            infcx: self.infcx,
-            delegate: self,
+        generalize(
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/combine.rs:462]: nit: prefer `generalize::generalize` here instead of importing the method or importing `Generalizer` and changing it to `Generalizer::generalize`. makes it clear that `generalize` is from a different file

File: compiler/rustc_infer/src/infer/combine.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_infer/src/infer/combine.rs:298]: that's only because currently there's no way to get a constant with non-invariant generic parameters, but yeah 😁

**Review by lcnr — COMMENTED** [review]
realized that nll relate does not explicitly generalize const inference vars but instead relies on `super_combine_consts` which then generalizes const inference vars using the ordinary typeck generalizer which feels like it should cause bugs if that code is ever reachable?

a few nits then r=me.

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 4 above)
Comment (aliemjay) [reply compiler/rustc_infer/src/infer/generalize.rs:415]: `super_relate_consts` is unfortuantely not structural. We are eagerly evaluating `ty::UnevaluatedConst` there. But I agree, it should be made  purely structural.

**Comment by lcnr** [comment]
?bors

@bors try

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 11 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/generalize.rs:360]: Comment was pre-existing but I can remove the parenthetical.

**Comment by lcnr** [comment]
i think perf is good enough. 3 minimal regressions to `incr-patched: println` are irrelevant imo

File: compiler/rustc_infer/src/infer/generalize.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/generalize.rs:403]: Renamed to `structurally_relate_{tys,consts}` but left a FIXME on `structurally_relate_consts` that says that it's not currently structural and that should be fixed.

**Comment by compiler-errors** [comment]
I think I addressed all the nits? I won't r=@lcnr until they take another quick look at the final diff, though no rush! 😄

**Review by lcnr — COMMENTED** [review]
some nits, r=me

File: compiler/rustc_infer/src/infer/combine.rs [hunk 14]
```diff
@@ -456,11 +442,11 @@ impl<'infcx, 'tcx> CombineFields<'infcx, 'tcx> {
     /// - `for_vid` is a "root vid"
     #[instrument(skip(self), level = "trace", ret)]
     fn generalize(
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/combine.rs:444]: I'm just gonna remove `RelationDir` lol

**Comment by nnethercote** [comment]
@compiler-errors: any idea what happened with `bitmaps` perf? It wasn't affected in the pre-merge perf run.

**Comment by compiler-errors** [comment]
No, I didn't really do anything functional in the nits/changes that lcnr requested. Just some renames and moving things around mostly.
