### PR TITLE
const_generics: Fix incorrect ty::ParamEnv::empty() usage

### LINKED ISSUE #80561: ICE when calling member function of const generic struct with associated constant as const parameter
I have recently been toying with const generics again and they are in a signifficantly better state than when I last used them.
### Code
No special flags necessary to compile
```Rust
#![feature(const_generics)]
#![feature(const_evaluatable_checked)]
pub struct SimpleStruct<const N: usize>([u8; N]);

impl<const N: usize> SimpleStruct<N> {
  pub fn new() -> Self {
    loop{}
  }
}

pub trait TraitA: Sized {
  const SIZE: usize;
  fn zero() -> Self
    where [(); Self::SIZE]:
  {
    let _: SimpleStruct<{Self::SIZE}> = SimpleStruct::<{Self::SIZE}>::new();
    loop {}
  }
}
```
This ICE stops occurring once you move new() out of the impl block. It happens regardless of the positioning of the zero() function.

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (e22670468 2020-12-30)
binary: rustc
commit-hash: e2267046859c9ceb932abc983561d53a117089f6
commit-date: 2020-12-30
host: aarch64-unknown-linux-gnu
release: 1.51.0-nightly
```
also occurs on rust playground and older nightlies
### Error output

```
error: internal compiler error: Encountered error `Unimplemented` selecting `Binder(<Self as TraitA>)` during codegen
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:68:32

error: internal compiler error: ty::ConstKind::Error constructed but no error reported.
  |
  = note: delayed at /rustc/e2267046859c9ceb932abc983561d53a117089f6/compiler/rustc_middle/src/ty/consts.rs:183:43

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (e22670468 2020-12-30) running on aarch64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `testing`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e2267046859c9ceb932abc983561d53a117089f6/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #80561

Not sure if I should keep the `debug!(..)`s or not but its the second time I've needed them so they sure seem useful lol

cc @lcnr 
r? @oli-obk

### CODE REVIEW

File: compiler/rustc_middle/src/ty/instance.rs [hunk 1]
```diff
@@ -338,6 +338,7 @@ impl<'tcx> Instance<'tcx> {
         def_id: DefId,
         substs: SubstsRef<'tcx>,
     ) -> Result<Option<Instance<'tcx>>, ErrorReported> {
+        debug!("resolve: param_env = {:?}", param_env);
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/instance.rs:341]: yeet that one, you print it again right after

File: compiler/rustc_middle/src/ty/relate.rs [hunk 2]
```diff
@@ -493,6 +493,7 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
     a: &'tcx ty::Const<'tcx>,
     b: &'tcx ty::Const<'tcx>,
 ) -> RelateResult<'tcx, &'tcx ty::Const<'tcx>> {
+    debug!("super_relate_consts: relation.param_env()={:?}", relation.param_env());
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/relate.rs:496]: same as `super_combine_consts`

File: compiler/rustc_infer/src/infer/combine.rs [hunk 3]
```diff
@@ -228,6 +228,7 @@ impl<'infcx, 'tcx> InferCtxt<'infcx, 'tcx> {
         ct: &'tcx ty::Const<'tcx>,
         vid_is_expected: bool,
     ) -> RelateResult<'tcx, &'tcx ty::Const<'tcx>> {
+        debug!("unify_const_variable: param_env={:?}", param_env);
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/combine.rs:231]: Please use `#[instrument(level=debug, skip(self))]` on the function instead of a `debug!` invocation

File: compiler/rustc_middle/src/mir/interpret/queries.rs [hunk 4]
```diff
@@ -39,6 +39,7 @@ impl<'tcx> TyCtxt<'tcx> {
         promoted: Option<mir::Promoted>,
         span: Option<Span>,
     ) -> EvalToConstValueResult<'tcx> {
+        debug!("const_eval_resolve: param_env={:?}", param_env);
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/queries.rs:42]: same here

File: compiler/rustc_middle/src/ty/instance.rs [hunk 5]
```diff
@@ -353,6 +353,7 @@ impl<'tcx> Instance<'tcx> {
         def: ty::WithOptConstParam<DefId>,
         substs: SubstsRef<'tcx>,
     ) -> Result<Option<Instance<'tcx>>, ErrorReported> {
+        debug!("resolve_opt_const_arg: param_env={:?},substs={:?}", param_env, substs);
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/instance.rs:356]: and here

File: compiler/rustc_ty_utils/src/instance.rs [hunk 6]
```diff
@@ -14,6 +14,7 @@ fn resolve_instance<'tcx>(
     tcx: TyCtxt<'tcx>,
     key: ty::ParamEnvAnd<'tcx, (DefId, SubstsRef<'tcx>)>,
 ) -> Result<Option<Instance<'tcx>>, ErrorReported> {
+    debug!("resolve_instance: key = {:?}", key);
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/instance.rs:17]: aaaand here :laughing:

File: compiler/rustc_ty_utils/src/instance.rs [hunk 7]
```diff
@@ -93,7 +94,10 @@ fn inner_resolve_instance<'tcx>(
         };
         Ok(Some(Instance { def, substs }))
     };
-    debug!("resolve(def.did={:?}, substs={:?}) = {:?}", def.did, substs, result);
+    debug!(
+        "inner_resolve_instance: resolve(def.did={:?}, substs={:?}) = {:?}",
+        def.did, substs, result
+    );
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/instance.rs:100]: after that change, you can just print the result here (though I think there's also a way to tell `#[instrument]` to do that

File: compiler/rustc_ty_utils/src/instance.rs [hunk 8]
```diff
@@ -44,7 +45,7 @@ fn inner_resolve_instance<'tcx>(
 ) -> Result<Option<Instance<'tcx>>, ErrorReported> {
     let (param_env, (def, substs)) = key.into_parts();
 
-    debug!("resolve(def={:?}, substs={:?})", def.did, substs);
+    debug!("inner_resolve_instance: key={:?}", key);
```
Comment (oli-obk) [inline compiler/rustc_ty_utils/src/instance.rs:48]: ok, this one is pre-existing, but please chnage it to `#[instrument]` while you are at it

**Review by oli-obk — CHANGES_REQUESTED** [review]
just lots of tracing changes, the actual changes lgtm
