### PR TITLE
`RepeatN`: use MaybeUninit

### LINKED ISSUE #130140: Use after free in core::iter::repeat_n
`core::iter::repeat_n` currently unconditionally derives `Clone`. However,   
it will also drop its inner object if `n` is 0, which can cause a UAF if it's cloned afterwards.

```rust
use std::rc::Rc;
fn main() {
    let mut c = [0; 100];
    let x = std::iter::repeat_n(Rc::new(0), 0);
    let y = Box::new(&mut c);
    for _ in 0..100 {
        _ = x.clone();
    }
    y.fill(0);
}
```

Running the above program segfaults:

```
Exited with signal 11 (SIGSEGV): segmentation violation
Standard Error
   Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/playground`
```

Edit: Made the segfault quicker/more reliable.

### LINKED ISSUE #130141: core::iter::repeat_n is unsound with Unique<T>
This is technically different from #130140 as there's no UAF. However, using  `core::iter::repeat_n` with `Box<T>` has undefined behavior if you use the last element and then move the iterator, since  the `Box` field has noalias properties.

```rust
fn main() {
    let mut y = std::iter::repeat_n(Box::new(0), 1);
    let x = y.next().unwrap();
    let _z = y;
    dbg!(*x);
}
```

<details><summary>Miri Backtrace</summary>
<p>

```
Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.96s
     Running `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner target/miri/x86_64-unknown-linux-gnu/debug/playground`
error: Undefined Behavior: attempting a read access using <2719> at alloc1241[0x0], but that tag does not exist in the borrow stack for this location
 --> src/main.rs:5:5
  |
5 |     dbg!(*x);
  |     ^^^^^^^^
  |     |
  |     attempting a read access using <2719> at alloc1241[0x0], but that tag does not exist in the borrow stack for this location
  |     this error occurs as part of an access at alloc1241[0x0..0x4]
  |
  = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
  = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <2719> was created by a Unique retag at offsets [0x0..0x4]
 --> src/main.rs:3:13
  |
3 |     let x = y.next().unwrap();
  |             ^^^^^^^^^^^^^^^^^
help: <2719> was later invalidated at offsets [0x0..0x4] by a Unique retag (of a reference/box inside this compound value)
 --> src/main.rs:4:14
  |
4 |     let _z = y;
  |              ^
  = note: BACKTRACE (of the first span):
  = note: inside `main` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:364:13: 364:16
  = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

</p>
</details>

Wrapping the element using `MaybeUninit` (or `MaybeDangling` once we have that) should make this sound.

### PR DESCRIPTION
**Pull request by fee1-dead**
Closes #130140. Closes #130141.

Use `MaybeUninit` instead of `ManuallyDrop` for soundness.

### CODE REVIEW

**Comment by fee1-dead** [comment]
Note that this changes the `Debug` output, the `element` field will now be wrapped inside a `Some` if count is at least 1, and will display as `None` otherwise. Previously it just printed whatever is in there (which is unsound)

File: library/core/tests/iter/sources.rs [hunk 1]
```diff
@@ -156,3 +156,14 @@ fn test_repeat_n_drop() {
     drop((x0, x1, x2));
     assert_eq!(count.get(), 3);
 }
+
+#[test]
+fn test_repeat_n_soundness() {
+    let x = std::iter::repeat_n(String::from("use after free"), 0);
```
Comment (lcnr) [inline library/core/tests/iter/sources.rs:162]: also test clone please :thinking: 

r=me afterwards

**Comment by lcnr** [comment]
cc @rust-lang/libs

File: library/core/tests/iter/sources.rs [hunk 2]
```diff
@@ -156,3 +156,27 @@ fn test_repeat_n_drop() {
...
+
+    // `repeat_n` should drop the element immediately if `count` is zero.
+    // `Clone` should then not try to clone the element.
+    let x = std::iter::repeat_n(PanicOnClone, 0);
+    x.clone();
+
+    let mut y = std::iter::repeat_n(Box::new(0), 1);
+    let x = y.next().unwrap();
+    let _z = y;
+    assert_eq(0, *x);
```
Comment (clubby789) [inline library/core/tests/iter/sources.rs:181]:
```suggestion
    assert_eq!(0, *x);
```

**Comment by fee1-dead** [comment]
oops

**Review by WaffleLapkin — COMMENTED** [review]
I think the use of `ManuallyDrop` was correct here (ignoring the UAF issue obviously), however before https://github.com/rust-lang/unsafe-code-guidelines/issues/245 is fixed, it makes sense to use `ManuallyDrop` instead.

Can you leave a `FIXME` to replace it back with `ManuallyDrop`, once it doesn't cause issues?

**Comment by antonilol** [comment]
This iterator could be implemented using minimal to no unsafe code (I used none in this example) like this:

```rust
use core::num::NonZeroUsize;

#[derive(Debug, Clone)]
pub struct RepeatN<T>(Option<(T, NonZeroUsize)>);

impl<T> RepeatN<T> {
    pub fn new(value: T, count: usize) -> Self {
        Self(NonZeroUsize::new(count).map(|count| (value, count)))
    }

    // for use in last and maybe other methods
    fn take_element(&mut self) -> Option<T> {
        self.0.take().map(|(value, _count)| value)
    }
}

impl<T: Clone> Iterator for RepeatN<T> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        let (value, count) = self.0.as_mut()?;
        if let Some(new_count) = NonZeroUsize::new(count.get() - 1) {
            *count = new_count;
            Some(value.clone())
        } else {
            // this could be unwrap_unchecked
            Some(self.0.take().unwrap().0)
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let len = self.0.as_ref().map_or(0, |(_value, count)| count.get());
        (len, Some(len))
    }

    ...
}
```

**Comment by jwong101** [comment]
That also has the advantage of interacting with dropck a bit better(although you could also use `may_dangle`):

```rust
fn src() -> String {
    // fails today, but shouldn't if you use the option approach
    let x = "foo".to_owned();
    let mut y = std::iter::repeat_n(&*x, 1);
    // use y, but don't consume it entirely
    x
}
```

**Comment by antonilol** [comment]
Does this also preserve niches from `T`? `MaybeUninit` for sure not.

**Review by scottmcm — CHANGES_REQUESTED** [review]

**Comment by cuviper** [comment]
`Option<(T, NonZeroUsize)>` would have slightly less niche space than `(ManuallyDrop<T>, usize)`, because the current layout implementation only propagates the largest niche.

* If `T` has no niche values, then the single niche in `NonZeroUsize` will be used by `Option::None`. This is the same as before with no niches available outside.
* If `T` has one niche value, then `None` may use that **or** the `NonZeroUsize` again, but the other will not be available. So this is a lost niche compared to before.
* If `T` has multiple niche values, then `None` will use one of those, and the rest will be available outside. The `NonZeroUsize` niche will not be available. This is one less niche compared to before.

**Comment by jwong101** [comment]
Tbh, it's probably best if the NonZero field is used as the niche for the option, with the Option approach, as that allows just loading that field for stuff like `size_hint`.

```rust
use std::num::NonZero;

type T = Option<(String, NonZero<usize>)>;

#[no_mangle]
pub fn src(x: &T) -> usize {
    x.as_ref().map_or(0, |a| a.1.get())
}

type U = Option<(NonZero<usize>, String)>;

#[no_mangle]
pub fn dst(x: &U) -> usize {
    x.as_ref().map_or(0, |a| a.0.get())
}

#[no_mangle]
pub fn good(x: &Option<(NonZero<usize>, std::os::fd::OwnedFd)>) -> usize {
    x.as_ref().map_or(0, |a| a.0.get())
}

#[no_mangle]
pub fn bad(x: &Option<(std::os::fd::OwnedFd, NonZero<usize>)>) -> usize {
    x.as_ref().map_or(0, |a| a.1.get())
}
```

```asm
src:                                    # @src
# %bb.0:
	xor	eax, eax
	cmp	rax, qword ptr [rdi]
	jo	.LBB0_2
# %bb.1:
	mov	rax, qword ptr [rdi + 24]

.LBB0_2:
	ret
                                        # -- End function

dst:                                    # @dst
# %bb.0:
	xor	eax, eax
	cmp	rax, qword ptr [rdi + 8]
	jo	.LBB1_2
# %bb.1:
	mov	rax, qword ptr [rdi]

.LBB1_2:
	ret
                                        # -- End function

good:                                   # @good
# %bb.0:
	mov	rax, qword ptr [rdi]
	ret
                                        # -- End function

bad:                                    # @bad
# %bb.0:
	cmp	dword ptr [rdi], -1
	je	.LBB3_1
# %bb.2:
	mov	rax, qword ptr [rdi + 8]
	ret

.LBB3_1:
	xor	eax, eax
	ret
```

The loss of the other niches mainly hurts the size of it being wrapped in iterator adapters that would wrap it in an option like `chain` or `zip`. Though I think the main regression would be losing noundef a long with Rust potentially choosing a suboptimal niche that doesn't overlap with the `NonZero<size>`.

**Comment by antonilol** [comment]
> Tbh, it's probably best if the NonZero field is used as the niche for the option, as that allows just loading that field for stuff like `size_hint`.

If the compiler doesn't know the original size, that could result in this extra branch, but if it does know, it is smart enough to figure it out (first 3 examples, compiler explorer link)

https://rust.godbolt.org/z/W8hqncT81

(How does this even produce 10x more code for 'len_5' compared to 'len_4'? That feels very counterintuitive.)

File: library/core/src/iter/sources/repeat_n.rs [hunk 3]
```diff
@@ -74,31 +73,60 @@ pub fn repeat_n<T: Clone>(element: T, count: usize) -> RepeatN<T> {
 ///
 /// This `struct` is created by the [`repeat_n()`] function.
 /// See its documentation for more.
-#[derive(Clone, Debug)]
 #[stable(feature = "iter_repeat_n", since = "1.82.0")]
 pub struct RepeatN<A> {
     count: usize,
-    // Invariant: has been dropped iff count == 0.
-    element: ManuallyDrop<A>,
```
[the remark this answers is not in the document]
Comment (WaffleLapkin) [reply library/core/src/iter/sources/repeat_n.rs:82]: Yes, `ManuallyDrop` currently doesn't work here, see https://github.com/rust-lang/rust/issues/130141 and https://github.com/rust-lang/rust/pull/130145#pullrequestreview-2289840673.

[the remark this answers is not in the document]
Comment (WaffleLapkin) [reply library/core/src/iter/sources/repeat_n.rs:82]: > Does that mean that `ManuallyDrop<Box<_>>` is just _never_ sound?

It's sound if you don't touch it in _any_ way I think (i.e. not even move). But generally yes.

To fix this we need to implement `MaybeDangling` (#118166) which would be a lang item, yes (and then wrap the only field of `ManuallyDrop` with `MaybeDangling`).

File: library/core/src/iter/sources/repeat_n.rs [hunk 4]
```diff
@@ -74,31 +73,60 @@ pub fn repeat_n<T: Clone>(element: T, count: usize) -> RepeatN<T> {
...
     /// Clears the count so it won't be dropped again later.
     #[inline]
     fn take_element(&mut self) -> Option<A> {
         if self.count > 0 {
             self.count = 0;
+            let element = mem::replace(&mut self.element, MaybeUninit::uninit());
             // SAFETY: We just set count to zero so it won't be dropped again,
             // and it used to be non-zero so it hasn't already been dropped.
-            unsafe { Some(ManuallyDrop::take(&mut self.element)) }
+            unsafe { Some(element.assume_init()) }
```
Comment (theemathas) [inline library/core/src/iter/sources/repeat_n.rs:103]: Is this the same as returning `Some(self.element.assume_init_read())`?

Comment (fee1-dead) [reply library/core/src/iter/sources/repeat_n.rs:103]: Hmm. not too sure about this.

**Comment by fee1-dead** [comment]
I'd like a definite answer on what approach I should take (e.g. fixing the use-after-free first by not changing the field type and writing manual impls but keeping the miri reported UB due to using ManuallyDrop?)

File: library/core/src/iter/sources/repeat_n.rs (hunk 4 above)
Comment (zachs18) [reply library/core/src/iter/sources/repeat_n.rs:103]: Writing `uninit()` into  `self.element` will likely be elided in release mode, but explicitly writing `uninit()` into `self.element` would let sanitizers (e.g. Miri) explicitly catch if the field is later read as initialized, even if `T: Copy`.

Compare these two functions: https://rust.godbolt.org/z/cK48E76z3 At `-Copt-level=1`, they are almost the same (notably the `mem::replace(&mut self.element, uninit())` does not actually write anything to `self.element`), and at `-Copt-level=2` or above, the two functions are compiled to the same code.

**Comment by Noratrieb** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/repeat_n.20unsoundness

**Comment by workingjubilee** [comment]
It's fun to fuss over an unsoundness issue that is also an optimization problem, but it's better to actually ship the fix. This code seems adequate to quell the soundness issue, we can fuss over improvements later.

@bors r=lcnr,workingjubilee

**Comment by cuviper** [comment]
Since this is stabilizing in 1.82:

@rustbot label beta-nominated
