### PR TITLE
fix(parse): return unpected when current token is EOF

### LINKED ISSUE #111148: internal compiler error: no errors encountered even though `delay_span_bug` issued
rustc crashes on the following input, found by [fuzz_rustc](https://github.com/dwrensha/fuzz-rustc):

```rust
fn a<<i<Y<w<>#
```
```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: expected one of `,` or `>`, found `#`
 --> bug.rs:1:14
  |
1 | fn a<<i<Y<w<>#
  |              ^ expected one of `,` or `>`
  |
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
             1: <rustc_errors::Handler>::emit_diagnostic
             2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
             3: <rustc_parse::parser::Parser>::handle_ambiguous_unbraced_const_arg
             4: <rustc_parse::parser::Parser>::parse_angle_args
             5: <rustc_parse::parser::Parser>::parse_path_inner
             6: <rustc_parse::parser::Parser>::parse_ty_common
             7: <rustc_parse::parser::Parser>::parse_angle_args
             8: <rustc_parse::parser::Parser>::parse_path_inner
             9: <rustc_parse::parser::Parser>::parse_ty_common
            10: <rustc_parse::parser::Parser>::parse_ty_common
            11: <rustc_parse::parser::Parser>::parse_ty_where_predicate
            12: <rustc_parse::parser::Parser>::parse_generic_params::{closure#0}
            13: <rustc_parse::parser::Parser>::parse_generic_params
            14: <rustc_parse::parser::Parser>::parse_item_kind
            15: <rustc_parse::parser::Parser>::parse_item_common
            16: <rustc_parse::parser::Parser>::parse_mod
            17: rustc_interface::passes::parse
            18: <rustc_interface::queries::Queries>::parse
            19: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            20: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            21: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/alloc/src/boxed.rs:1985:9
            23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/alloc/src/boxed.rs:1985:9
            24: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/unix/thread.rs:108:17
            25: start_thread
                       at ./nptl/pthread_create.c:442:8
            26: clone3
                       at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (a368898de 2023-05-02) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by bvanjoi**
close https://github.com/rust-lang/rust/issues/111148

#111148 panic occurred because [FatalError.raise()](https://github.com/bvanjoi/rust/blob/master/compiler/rustc_parse/src/parser/mod.rs#LL540C3-L540C3) was encountered which caused by `Eof` and `Pound`(the last token) had same span, when parsing `#` in `fn a<<i<Y<w<>#`.

image

There are a few ways to solve this problem:

- Change the action assign for [self.last_unexpected_token_span](https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/parser/diagnostics.rs#L592), for example, if current token is `Eof`, then return Error directly.
- Avoid triggering the `FatalError` when the current token is `Eof`.

I have chosen the second option because executing `expected_one_of_not_found` when the token is `Eof` but not in `ediable` seems reasonable.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you leave some explanation why this fixes the issue? I think I understand the corner case it's trying to avoid here, but I'm not totally sure.

**Comment by bvanjoi** [comment]
> Can you leave some explanation why this fixes the issue? I think I understand the corner case it's trying to avoid here, but I'm not totally sure.

I have included a few descriptions in this PR, and I would really appreciate your valuable suggestions and feedback, whether it pertains to the code or the descriptions themselves.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 1]
```diff
@@ -536,6 +536,8 @@ impl<'a> Parser<'a> {
         } else if inedible.contains(&self.token.kind) {
             // leave it in the input
             Ok(false)
+        } else if self.token.kind == token::Eof {
+            self.expected_one_of_not_found(edible, inedible)
         } else if self.last_unexpected_token_span == Some(self.token.span) {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/mod.rs:541]:
```suggestion
        } else if self.token.kind != token::Eof && self.last_unexpected_token_span == Some(self.token.span) {
```

I think this is better, we avoid duplicating the content of the `else` block, which is the behaviour we want.

**Review by davidtwco — CHANGES_REQUESTED** [review]
LGTM with the suggested change
