### PR TITLE
Recover from typo where == is used in place of =

### LINKED ISSUE #101477: Recover from typo where `==` is used in place of `=`
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=39a6278bf8d8f0bcb98ced9b5f321a1b)

```rust
enum test {
    a == 1,
}

fn main() {
    let x == 2;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `==`
 --> src/main.rs:2:7
  |
2 |     a == 1,
  |       ^^ expected one of `(`, `,`, `=`, `{`, or `}`

error: expected item, found `==`
 --> src/main.rs:2:7
  |
2 |     a == 1,
  |       ^^ expected item

error: could not compile `playground` due to 2 previous errors
```

Ideally the output should suggest replacing the `==` with `=` where appropriate as the suggestion for incorrect usage of `=` in place of `==` already exist.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #101477

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -957,6 +957,17 @@ impl<'a> Parser<'a> {
             }
         }
 
+        if self.token.kind == TokenKind::EqEq
+            && self.prev_token.is_ident()
+            && expected.iter().any(|tok| matches!(tok, TokenType::Token(TokenKind::Eq)))
+        {
+            // Likely typo: `=` → `==` in let expr or enum item
+            let mut err = self.struct_span_err(self.token.span, "expect `=`, found `==`");
+            err.span_suggestion_short(self.token.span, "write `=` instead of `==`", "=", appl)
```
Comment (fee1-dead) [inline compiler/rustc_parse/src/parser/diagnostics.rs:966]:
```suggestion
            let mut err = self.struct_span_err(self.token.span, "unexpected `==`");
            err.span_suggestion_short(self.token.span, "try using `=` instead", "=", appl)
```

**Review by fee1-dead — COMMENTED** [review]
Nice work! LGTM pending error message improvements. Also, could this be using SessionDiagnostics instead? cc @davidtwco

**Comment by chenyukang** [comment]
> > Also, could this be using SessionDiagnostics instead? cc @davidtwco
> 
> This could absolutely use `SessionDiagnostic`, I'd appreciate it if it did - see #100717.

I'm fixing it to use `SessionDiagnostic`, I have a question when using it:

How can I keep returning an `Err` to avoid extra useless diagnostics?
```diff
-            let mut err = self.struct_span_err(self.token.span, "unexpected `==`");
-            err.span_suggestion_short(self.token.span, "try using `=` instead `==`", "=", appl)
-                .emit();
-            return Err(err);
+            self.sess.emit_err(UseEqInstead { span: self.token.span });
+            return Ok(true);
```

I use return Ok now and there will be a extra diagnostics which I want to remove.

```diff
--- a/src/test/ui/parser/issue-101477-let.stderr
+++ b/src/test/ui/parser/issue-101477-let.stderr
@@ -2,7 +2,13 @@ error: unexpected `==`
   --> $DIR/issue-101477-let.rs:4:11
    |
 LL |     let x == 2;
-   |           ^^ help: try using `=` instead `==`
+   |           ^^ help: replace `==` with a equal symbol: `=`

-error: aborting due to previous error
+error: expected expression, found `==`
+  --> $DIR/issue-101477-let.rs:4:11
+   |
+LL |     let x == 2;
+   |           ^^ expected expression
+
+error: aborting due to 2 previous errors
```

**Comment by chenyukang** [comment]
Seems we use this struct to avoid later errors:

```rust
/// Useful type to use with `Result<>` indicate that an error has already
/// been reported to the user, so no need to continue checking.
#[derive(Clone, Copy, Debug, Encodable, Decodable, Hash, PartialEq, Eq, PartialOrd, Ord)]
#[derive(HashStable_Generic)]
pub struct ErrorGuaranteed(());
```
But `parse_let_expr` is:

```rust
 fn parse_let_expr(&mut self) -> PResult<'a, P<Expr>> {
        ...
        self.expect(&token::Eq)?;
        let expr = self.with_res(self.restrictions | Restrictions::NO_STRUCT_LITERAL, |this| {
            this.parse_assoc_expr_with(1 + prec_let_scrutinee_needs_par(), None.into())
        })?;
        let span = lo.to(expr.span);
        self.sess.gated_spans.gate(sym::let_chains, span);
        Ok(self.mk_expr(span, ExprKind::Let(pat, expr, span)))
    }
```

**Comment by chenyukang** [comment]
Got it:

```rust
  let mut err = self.sess.create_err(UseEqInstead { span: self.token.span });
            err.emit();
            return Err(err);
```

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: `SessionDiagnostic` will print the suggestion in the same line, so it will print like this:

```console
error: unexpected `==`
 --> src/test/ui/parser/issue-101477-enum.rs:6:7
  |
6 |     B == 2 //~ ERROR unexpected `==`
  |       ^^ help: try using `=` instead `==`: `=`
```

I think it's better in this format?

```console
error: unexpected `==`
 --> src/test/ui/parser/issue-101477-let.rs:4:11
  |
4 |     let x == 2; //~ ERROR unexpected `==`
  |           ^^ help: replace `==` with a equal symbol: `=`
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -957,6 +965,16 @@ impl<'a> Parser<'a> {
             }
         }
 
+        if self.token.kind == TokenKind::EqEq
+            && self.prev_token.is_ident()
+            && expected.iter().any(|tok| matches!(tok, TokenType::Token(TokenKind::Eq)))
+        {
+            // Likely typo: `=` → `==` in let expr or enum item
+            let mut err = self.sess.create_err(UseEqInstead { span: self.token.span });
+            err.emit();
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:974]: Don't emit the error here, it's being emitted later since you're returning it.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 3]
```diff
@@ -713,6 +713,14 @@ pub(crate) struct RemoveLet {
     pub span: Span,
 }
 
+#[derive(SessionDiagnostic)]
+#[diag(parser::use_eq_instead)]
+pub(crate) struct UseEqInstead {
+    #[primary_span]
+    #[suggestion(applicability = "machine-applicable", code = "=")]
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:720]: Can you use `suggestion_short` here?

File: compiler/rustc_error_messages/locales/en-US/parser.ftl [hunk 4]
```diff
@@ -153,3 +153,6 @@ parser_left_arrow_operator = unexpected token: `<-`
 
 parser_remove_let = expected pattern, found `let`
     .suggestion = remove the unnecessary `let` keyword
+
+parser_use_eq_instead = unexpected `==`
+    .suggestion = replace `==` with a equal symbol
```
Comment (compiler-errors) [inline compiler/rustc_error_messages/locales/en-US/parser.ftl:158]: I think this should be "with `=`" -- it won't be so verbose if you use suggestion_short

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Nice, thanks @compiler-errors.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Resolved with @compiler-errors with advices.
