### PR TITLE
Point at invalid utf-8 span on user's source code

### LINKED ISSUE #76869: [ER] Line number for 'stream did not contain valid UTF-8' errors
If by mistake I write code as this:

```rust
fn main() {
    println!("Hello ’world");
}
```
All I get from rustc is:
```
error: couldn't read ...\test.rs: stream did not contain valid UTF-8
```

But I'd like to receive a line number where such invalidity happens.
```
Using: rustc 1.48.0-nightly f3c923a13 2020-09-17 x86_64-pc-windows-gnu
```

### PR DESCRIPTION
**Pull request by estebank**
```
error: couldn't read `$DIR/not-utf8-bin-file.rs`: stream did not contain valid UTF-8
  --> $DIR/not-utf8-2.rs:6:5
   |
LL |     include!("not-utf8-bin-file.rs");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: byte `193` is not valid utf-8
  --> $DIR/not-utf8-bin-file.rs:2:14
   |
LL |     let _ = "�|�␂!5�cc␕␂��";
   |              ^
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
```

When we attempt to load a Rust source code file, if there is a OS file failure we try reading the file as bytes. If that succeeds we try to turn it into UTF-8. If *that* fails, we provide additional context about *where* the file has the first invalid UTF-8 character.

Fix #76869.

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/source_util.rs [hunk 1]
```diff
@@ -210,8 +210,34 @@ pub(crate) fn expand_include_str(
...
+                    let source = cx.source_map().new_source_file(path.into(), contents);
+                    let span = Span::with_root_ctxt(
+                        source.normalized_byte_pos(start as u32),
+                        source.normalized_byte_pos(start as u32),
+                    );
+                    if span.is_dummy() {
+                        err.note(note);
+                    } else {
+                        err.span_note(span, msg);
+                    }
```
Comment (jieyouxu) [inline compiler/rustc_builtin_macros/src/source_util.rs:238]: Question [EMPTY-SP 1/2]: won't this span always be empty because start == start?

File: compiler/rustc_parse/src/lib.rs [hunk 2]
```diff
@@ -74,8 +75,36 @@ pub fn new_parser_from_file<'a>(
...
+            };
+            let contents = utf8err.into_utf8_lossy();
+            let source = psess.source_map().new_source_file(path.to_owned().into(), contents);
+            let span = Span::with_root_ctxt(
+                source.normalized_byte_pos(start as u32),
+                source.normalized_byte_pos(start as u32),
+            );
+            if span.is_dummy() {
+                err.note(note);
+            } else {
```
Comment (jieyouxu) [inline compiler/rustc_parse/src/lib.rs:99]: Question [EMPTY-SP 2/2]: same here

File: compiler/rustc_builtin_macros/src/source_util.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_builtin_macros/src/source_util.rs:238]: `DUMMY_SP` is does not just have a start and end with the same value, the value of them is `0`, which is reserved for "unknown".

Also, when the start and end of a span is to the same position, then the span is said to be pointing "between" `start - 1` and `start`, like a cursor does. When rendering, we point at `start` to `start + 1`. We can give the span a width of 1, but that might fail in some cases if the following byte is a multi-byte char. Given how niche this error should be in practice I wasn't inclined to spend too much time tweaking this output, and given how... "terse" the current output was, I wanted to have something finished earlier rather than later so that we could iterate on it on main (if needed).

File: src/tools/compiletest/src/errors.rs [hunk 3]
```diff
@@ -101,6 +101,8 @@ pub fn load_errors(testfile: &Path, revision: Option<&str>) -> Vec<Error> {
 
     rdr.lines()
         .enumerate()
+        // We want to ignore utf-8 failures in tests during collection of annotations.
+        .filter(|(_, line)| line.is_ok())
```
Comment (estebank) [inline src/tools/compiletest/src/errors.rs:105]: This...

File: src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs [hunk 4]
```diff
@@ -58,7 +58,7 @@ pub fn check(tests_path: impl AsRef<Path>, bad: &mut bool) {
 
             let mut expected_revisions = BTreeSet::new();
 
-            let contents = std::fs::read_to_string(test).unwrap();
+            let Ok(contents) = std::fs::read_to_string(test) else { continue };
```
Comment (estebank) [inline src/tools/tidy/src/tests_revision_unpaired_stdout_stderr.rs:61]: ...this, and another line in `md-doc` blow up if a *test* has non-utf-8 bytes.

I ended up removing a test of "`.rs` file with invalid few utf-8 bytes" because md-docs is in a separate repo. I feel we should make the entire test suite more resilient to these, but I think I can make that test I added and removed be in `run-make`...

File: compiler/rustc_builtin_macros/src/source_util.rs [hunk 5]
```diff
@@ -210,8 +210,34 @@ pub(crate) fn expand_include_str(
                 MacEager::expr(cx.expr_str(cx.with_def_site_ctxt(bsp), interned_src))
             }
             Err(_) => {
-                let guar = cx.dcx().span_err(sp, format!("`{path}` wasn't a utf-8 file"));
-                DummyResult::any(sp, guar)
+                let mut err = cx.dcx().struct_span_err(sp, format!("`{path}` wasn't a utf-8 file"));
+                let path = PathBuf::from(path.as_str());
+                if let Ok(contents) = std::fs::read(&path)
+                    && let Err(utf8err) = String::from_utf8(contents)
```
Comment (fee1-dead) [inline compiler/rustc_builtin_macros/src/source_util.rs:216]: Is there a reason why we aren't using the `Err(_)` and `bytes` above as information for the error?

File: compiler/rustc_parse/src/lib.rs [hunk 6]
```diff
@@ -74,8 +75,36 @@ pub fn new_parser_from_file<'a>(
     sp: Option<Span>,
 ) -> Result<Parser<'a>, Vec<Diag<'a>>> {
     let source_file = psess.source_map().load_file(path).unwrap_or_else(|e| {
-        let msg = format!("couldn't read {}: {}", path.display(), e);
+        let msg = format!("couldn't read `{}`: {}", path.display(), e);
```
Comment (fee1-dead) [inline compiler/rustc_parse/src/lib.rs:78]: the error here could be an enum of an io error or a utf8 error, and store the information about the span and message to be reported, and that would probably help with deduplicating these code

File: compiler/rustc_builtin_macros/src/source_util.rs [hunk 7]
```diff
@@ -210,8 +210,34 @@ pub(crate) fn expand_include_str(
                 MacEager::expr(cx.expr_str(cx.with_def_site_ctxt(bsp), interned_src))
```
Comment (fee1-dead) [inline compiler/rustc_builtin_macros/src/source_util.rs:210]: maybe worth looking into unifying the logic here and the `rustc_parse` logic somehow?

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: compiler/rustc_builtin_macros/src/source_util.rs (hunk 5 above)
Comment (estebank) [reply compiler/rustc_builtin_macros/src/source_util.rs]: 🤦

File: compiler/rustc_builtin_macros/src/source_util.rs (hunk 7 above)
Comment (estebank) [reply compiler/rustc_builtin_macros/src/source_util.rs:210]: I moved the logic to a separate function and called it from both places.

**Review by fee1-dead — APPROVED** [review]
r=me after squashing

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/135891#issuecomment-2608097837

**Comment by estebank** [comment]
> oops wrong pr

You had me scared for a second there "oh, no! what fresh hell did this utf-8 handling cause during rollup?" XD
