### PR TITLE
Force warnings even when can_emit_warnings == false

### LINKED ISSUE #86751: Failure to update `dyn` usage in Rust 2018 to 2021 transition
To reproduce:
* Clone [`serde`](https://github.com/serde-rs/serde).
* Run `cargo +nightly fix --edition` (this updates `serde` from Rust 2015 to Rust 2018).
* Add the edition field to the Cargo.toml with "2018" and commit changes.
* Run `cargo +nightly fix --edition` (this updates `serde` from Rust 2018 to Rust 2021).
* Change the edition field to "2021" (ensure `cargo-features = ["edition2021"]` is present at the top of the Cargo.toml file)

This produces an error because some uses of bare trait objects were not updated:

```
error[E0782]: trait objects must include the `dyn` keyword
    --> serde/src/private/de.rs:1725:37
     |
1725 |         fn invalid_type(self, exp: &Expected) -> E {
     |                                     ^^^^^^^^
     |
help: add `dyn` keyword before this trait
```

Running `cargo +nightly rustc -- -Zunstable-options --force-warns rust_2021_compatibility` produces the proper warnings, but these are not picked up by cargo fix. 

```
warning: trait objects without an explicit `dyn` are deprecated
    --> serde/src/private/de.rs:1725:37
     |
1725 |         fn invalid_type(self, exp: &Expected) -> E {
     |                                     ^^^^^^^^ help: use `dyn`: `dyn Expected`
     |
     = warning: this is accepted in the current edition (Rust 2018) but is a hard error in Rust 2021!
     = note: for more information, see issue #80165 <https://github.com/rust-lang/rust/issues/80165>
```

I'm filing this in rust-lang/rust instead of in rust-lang/cargo, because I have a feeling this is a rustc issue. 

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.55.0-nightly (6d820866a 2021-06-29)
binary: rustc
commit-hash: 6d820866a27b1949e237be79b9c8c0145fe728b7
commit-date: 2021-06-29
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by rylev**
Fixes an issue mentioned in #85512 with --cap-lints overriding --force-warnings.

Fixes https://github.com/rust-lang/rust/issues/86751

r? @ehuss

### CODE REVIEW

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -795,20 +795,16 @@ impl HandlerInner {
 
     fn emit_diagnostic(&mut self, diagnostic: &Diagnostic) {
         if diagnostic.cancelled() {
+            if !self.flags.can_emit_warnings && diagnostic.has_future_breakage() {
+                (*TRACK_DIAGNOSTICS)(diagnostic);
+            }
```
Comment (ehuss) [inline compiler/rustc_errors/src/lib.rs:800]: This seems to change the behavior of `can_emit_warnings`. In particular, if there is a non-lint-based warning, it is now allowed to be emitted (that is, something that creates a warning diagnostic without going through `struct_warn`).  Those are very rare.  This seems to hobble `can_emit_warnings` such that it only impacts non-lints that use `struct_warn`, which is also very rare.

This also doesn't seem to be correct for TRACK_DIAGNOSTICS.  I believe it should only be called if the diagnostic is pushed onto `future_breakage_diagnostics` below. It is not clear to me how important it is that TRACK_DIAGNOSTICS gets called. It appears to have something to do with incremental, but what happens if it is not called?

Also, the old code seems broken to me. I don't see how it is possible for a diagnostic to have a level of Warning and `can_emit_warnings` is false (I believe the level will always be Allow with `--cap-lints=allow`).  It seems like that call to TRACK_DIAGNOSTICS would never happen.

In general, the problem seems that `emit_diagnostic` does not have enough information to know if this was a force-warns diagnostic.  Maybe DiagnosticId::Lint could add a field to indicate it was force-warn (similar to the has_future_breakage field)?

Comment (rylev) [reply compiler/rustc_errors/src/lib.rs:800]: I like the suggestion of adding this to `DiagnosticId::Lint`, but I'm going to wait for https://github.com/rust-lang/rust/pull/86009 to land before addressing this since I think how we do this will change slightly once that lands.

**Review by ehuss — APPROVED** [review]
Looks good, thanks!

I don't feel comfortable merging as I am not on the compiler team.  Maybe @estebank or someone else could take a quick look?

**Comment by rylev** [comment]
r? @nikomatsakis 

(since this is edition related, and he's been looking at a lot of these)

File: compiler/rustc_errors/src/lib.rs [hunk 2]
```diff
@@ -521,12 +521,24 @@ impl Handler {
...
 
     /// Construct a builder at the `Warning` level at the given `span` and with the `msg`.
+    /// Cancel the builder if warnings cannot be emitted
     pub fn struct_span_warn(&self, span: impl Into<MultiSpan>, msg: &str) -> DiagnosticBuilder<'_> {
         let mut result = self.struct_warn(msg);
         result.set_span(span);
         result
     }
 
+    /// Construct a builder at the `Warning` level at the given `span` and with the `msg`.
```
Comment (nikomatsakis) [inline compiler/rustc_errors/src/lib.rs:531]: I found this comment confusing-- I expected it to comment on the "force" part of the method name here.

Comment (nikomatsakis) [reply compiler/rustc_errors/src/lib.rs:531]: What does it mean to *force* a warning?

File: compiler/rustc_middle/src/lint.rs [hunk 3]
```diff
@@ -246,6 +251,9 @@ pub fn struct_lint_level<'s, 'd>(
         let has_future_breakage =
             future_incompatible.map_or(false, |incompat| incompat.future_breakage.is_some());
 
+        let is_force_warn = matches!(level, Level::ForceWarn)
+            || matches!(src, LintLevelSource::CommandLine(_, Level::ForceWarn));
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/lint.rs:255]: Why do we need the `if` here?

Comment (nikomatsakis) [reply compiler/rustc_middle/src/lint.rs:255]: Oh, I guess because the level could be *error*? Maybe add a comment about that

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_errors/src/lib.rs (hunk 2 above)
Comment (rylev) [reply compiler/rustc_errors/src/lib.rs:531]: I'll rework this. I think all these functions might need better comments.

File: compiler/rustc_middle/src/lint.rs (hunk 3 above)
Comment (rylev) [reply compiler/rustc_middle/src/lint.rs:255]: I'm not sure what you mean (this line doesn't have an `if` in it). What in particular do you not find clear?

Comment (nikomatsakis) [reply compiler/rustc_middle/src/lint.rs:255]: Oh, I meant the `||` -- like, why isn't it sufficient to just check if the level is `ForceWarn`?

Comment (nikomatsakis) [reply compiler/rustc_middle/src/lint.rs:255]: sorry, in my brain, `||` and `if` are equivalent

Comment (rylev) [reply compiler/rustc_middle/src/lint.rs:255]: haha no worries (I think if you would have said "conditional" it would have registered, but the use of backticks made it seem like you were talking about a literal `if` in the code). 

The level can be lower (e.g., warn or allow) because `--cap-lints` globally lints caps. The interaction between the global options `--cap-lints` and the per lint options `--force-warn` is a tiny bit hacky IMO, but I don't think refactoring the entire system is worth it.  A comment here should make it sufficiently clear.

Comment (rylev) [reply compiler/rustc_middle/src/lint.rs:255]: Actually, this is false. I think check of the src can be removed.

**Review by nikomatsakis — APPROVED** [review]

**Review by nikomatsakis — APPROVED** [review]
