### PR TITLE
rustc: Store metadata-in-rlibs in object files

### LINKED ISSUE #83730: macos: unable to get debug information from dylib dependencies
On macOS, the debug information for the dependencies of a dylib do not seem to be working with split-debuginfo=unpacked.

One way to demonstrate this is building rustc itself with debug enabled, and split-debuginfo as unpacked (the default). Backtraces are unable to find the source file information for anything past `rustc_query_system`.  lldb is also unable to find any debug information (it can't even find the symbols).

Example of what the backtrace looks like:

<details><summary>Backtrace</summary>
<p>

```
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::emit_diagnostic
   2: rustc_errors::Handler::emit_diagnostic
   3: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   4: rustc_resolve::late::lifetimes::LifetimeContext::resolve_lifetime_ref
   5: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_lifetime
   6: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_path
   7: rustc_hir::intravisit::walk_expr
   8: rustc_resolve::late::lifetimes::LifetimeContext::with
   9: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_nested_body
  10: rustc_resolve::late::lifetimes::LifetimeContext::visit_early_late
  11: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_item
  12: rustc_resolve::late::lifetimes::do_resolve
  13: rustc_resolve::late::lifetimes::resolve_lifetimes
  14: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::resolve_lifetimes>::compute
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::force_query_with_job
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_query_system::query::plumbing::get_query
  20: rustc_resolve::late::lifetimes::resolve_lifetimes_for
  21: core::ops::function::FnOnce::call_once
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: rustc_query_system::query::plumbing::get_query
  27: rustc_middle::ty::context::TyCtxt::named_region
  28: <dyn rustc_typeck::astconv::AstConv>::ast_region_to_region
  29: <<dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path::SubstsForAstPathCtxt as rustc_typeck::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
  30: rustc_typeck::astconv::generics::<impl dyn rustc_typeck::astconv::AstConv>::create_substs_for_generic_args
  31: <dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path
  32: <dyn rustc_typeck::astconv::AstConv>::ast_path_substs_for_ty
  33: <dyn rustc_typeck::astconv::AstConv>::ast_path_to_ty
  34: <dyn rustc_typeck::astconv::AstConv>::res_to_ty
  35: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_struct_path
  36: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  37: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  38: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::with_breakable_ctxt
  39: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  40: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  43: rustc_typeck::check::check::check_fn
  44: rustc_infer::infer::InferCtxtBuilder::enter
  45: rustc_typeck::check::inherited::InheritedBuilder::enter
  46: rustc_typeck::check::typeck_with_fallback
  47: rustc_typeck::check::typeck
  48: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  49: rustc_data_structures::stack::ensure_sufficient_stack
  50: rustc_query_system::query::plumbing::force_query_with_job
  51: rustc_query_system::query::plumbing::get_query_impl
  52: rustc_query_system::query::plumbing::get_query
  53: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  54: rustc_typeck::check::typeck_item_bodies
  55: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  56: rustc_data_structures::stack::ensure_sufficient_stack
  57: rustc_query_system::query::plumbing::force_query_with_job
  58: rustc_query_system::query::plumbing::get_query_impl
  59: rustc_query_system::query::plumbing::get_query
  60: rustc_session::utils::<impl rustc_session::session::Session>::time
  61: rustc_typeck::check_crate
  62: rustc_interface::passes::analysis
  63: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  64: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  65: rustc_data_structures::stack::ensure_sufficient_stack
  66: rustc_query_system::query::plumbing::force_query_with_job
  67: rustc_query_system::query::plumbing::get_query_impl
  68: rustc_query_system::query::plumbing::get_query
  69: rustc_middle::ty::query::TyCtxtAt::analysis
             at /Users/eric/Proj/rust/rust2/compiler/rustc_middle/src/ty/query/mod.rs:205:17
  70: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::analysis
             at /Users/eric/Proj/rust/rust2/compiler/rustc_middle/src/ty/query/mod.rs:186:17
  71: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_driver/src/lib.rs:436:59
  72: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/passes.rs:754:42
  73: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_middle/src/ty/context.rs:1726:50
  74: rustc_middle::ty::context::tls::set_tlv
             at /Users/eric/Proj/rust/rust2/compiler/rustc_middle/src/ty/context.rs:1710:9
  75: rustc_middle::ty::context::tls::enter_context
             at /Users/eric/Proj/rust/rust2/compiler/rustc_middle/src/ty/context.rs:1726:9
  76: rustc_interface::passes::QueryContext::enter
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/passes.rs:754:9
  77: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_driver/src/lib.rs:436:13
  78: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/queries.rs:422:19
  79: rustc_driver::run_compiler::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_driver/src/lib.rs:337:22
  80: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/interface.rs:208:13
  81: rustc_span::with_source_map
             at /Users/eric/Proj/rust/rust2/compiler/rustc_span/src/lib.rs:788:5
  82: rustc_interface::interface::create_compiler_and_run
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/interface.rs:202:5
  83: rustc_interface::interface::run_compiler::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/interface.rs:224:12
  84: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/util.rs:155:13
  85: scoped_tls::ScopedKey<T>::set
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  86: rustc_span::with_session_globals
             at /Users/eric/Proj/rust/rust2/compiler/rustc_span/src/lib.rs:105:5
  87: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/util.rs:153:9
  88: rustc_interface::util::scoped_thread::{{closure}}
             at /Users/eric/Proj/rust/rust2/compiler/rustc_interface/src/util.rs:128:24
```
</details>

From what I can tell, the debug information for everything directly in `rustc_driver` can be found, but anything from a dependency cannot.  Note that generic functions are part of `rustc_driver`, so that is why things like `rustc_middle` functions appear in the backtrace above.

# Minimal example

I created a simple demo project at https://github.com/ehuss/macos-dylib-debug.

This has an executable `foo` depends on dylib `driver` which depends on `somedep`.

If you build on macOS with the latest nightly (2021-03-31) which has split-debuginfo enabled by default, and run with `RUST_BACKTRACE=1`, you can see that the information is missing from the dependency:

```
   0: std::panicking::begin_panic
   1: somedep::do_something
   2: driver::run_driver
             at ./driver/src/lib.rs:2:5
   3: foo::main
             at ./src/main.rs:2:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/74874a690bc95443292496ff5df5cc5c8cb56e0b/library/core/src/ops/function.rs:227:5
```

If you disable split-debuginfo (`CARGO_PROFILE_DEV_SPLIT_DEBUGINFO=packed`), then it gets the full information:

```
   0: std::panicking::begin_panic
             at /rustc/74874a690bc95443292496ff5df5cc5c8cb56e0b/library/std/src/panicking.rs:519:12
   1: somedep::do_something
             at ./somedep/src/lib.rs:3:5
   2: driver::run_driver
             at ./driver/src/lib.rs:2:5
   3: foo::main
             at ./src/main.rs:2:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/74874a690bc95443292496ff5df5cc5c8cb56e0b/library/core/src/ops/function.rs:227:5
```

Similarly, trying to debug with lldb is unable to see anything in `somedep`.  Running lldb with a dylib is a little tricky due to system integrity protection, it is something like this:

```shell
DYLD_FALLBACK_LIBRARY_PATH=$(rustc --print=sysroot)/lib/rustlib/x86_64-apple-darwin/lib \
    /Applications/Xcode.app/Contents/Developer/usr/bin/lldb ./target/debug/foo
```

`b do_something` fails to find the symbol.  Setting a breakpoint on `run_driver` and running and then trying to step into `do_something` is unable to work.  Doing all of the above with `packed` split-debuginfo works as expected.

### Meta

`rustc 1.53.0-nightly (74874a690 2021-03-30)`

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates how rustc compiler metadata is stored in rlibs.
Previously metadata was stored as a raw file that has the same format as
`--emit metadata`. After this commit, however, the metadata is encoded
into a small object file which has one section which is the contents of
the metadata.

The motivation for this commit is to fix a common case where #83730
arises. The problem is that when rustc crates a `dylib` crate type it
needs to include entire rlib files into the dylib, so it passes
`--whole-archive` (or the equivalent) to the linker. The problem with
this, though, is that the linker will attempt to read all files in the
archive. If the metadata file were left as-is (today) then the linker
would generate an error saying it can't read the file. The previous
solution was to alter the rlib just before linking, creating a new
archive in a temporary directory which has the metadata file removed.

This problem from before this commit is now removed if the metadata file
is stored in an object file that the linker can read. The only caveat we
have to take care of is to ensure that the linker never actually
includes the contents of the object file into the final output. We apply
similar tricks as the `.llvmbc` bytecode sections to do this.

This involved changing the metadata loading code a bit, namely updating
some of the LLVM C APIs used to use non-deprecated ones and fiddling
with the lifetimes a bit to get everything to work out. Otherwise though
this isn't intended to be a functional change really, only that metadata
is stored differently in archives now.

This should end up fixing #83730 because by default dylibs will no
longer have their rlib dependencies "altered" meaning that
split-debuginfo will continue to have valid paths pointing at the
original rlibs. (note that we still "alter" rlibs if LTO is enabled to
remove Rust object files and we also "alter" for the #[link(cfg)]
feature, but that's rarely used).

Closes #83730

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/metadata.rs [hunk 1]
```diff
@@ -18,51 +19,66 @@ pub use rustc_data_structures::sync::MetadataRef;
 pub struct LlvmMetadataLoader;
 
 impl MetadataLoader for LlvmMetadataLoader {
-    fn get_rlib_metadata(&self, _: &Target, filename: &Path) -> Result<MetadataRef, String> {
+    fn get_rlib_metadata(&self, target: &Target, filename: &Path) -> Result<MetadataRef, String> {
```
Comment (alexcrichton) [inline compiler/rustc_codegen_llvm/src/metadata.rs:22]: FWIW I think it may be high time to rip out all the LLVM integration here and simply use the `object` crate (or similar) to read the object files from the archives here (maybe even use the `ar` crate!). I'm not certain about this though so I figured it was best left to a different PR. For now this continues to use all the LLVM integration we're already used to.

Put another way, I think it might be good for a future PR to explore simply lifting the probably-existing cranelift solution for this into the complier and remove the need for this to be a backend-specific trait.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/metadata.rs:22]: I tried to use the `object` crate for both object file and archive reading in https://github.com/rust-lang/rust/pull/83640, but it regressed performance a bit.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -387,8 +391,91 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+            "s390x" => Architecture::S390x,
+            "mips" => Architecture::Mips,
+            "x86_64" => Architecture::X86_64,
+
+            // This is used to handle all "other" targets. This includes targets
+            // like WebAssembly and those otherwise just not having support here
+            // at this time. For these targets the metadata file in the rlib is
+            // simply the raw metadata itself. This would break dylib
+            // compliation if it were supported, but for most of these targets
+            // dylib compilation is not supported anyway (such as WebAssembly).
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/link.rs:449]: Riscv, sparc and powerpc do support dylibs.

**Comment by bjorn3** [comment]
This will need rustc_codegen_cranelift to be updated to do the same thing. Otherwise it becomes impossible to link against a cg_llvm compiled standard library.

**Comment by alexcrichton** [comment]
@nagisa would you be up for reviewing this?

**Comment by nagisa** [comment]
r? @nagisa Will see about getting to this on Friday/weekend.

But so far a couple of remarks:

> The problem with this, though, is that the linker will attempt to read all files in the archive. If the metadata file were left as-is (today) then the linker would generate an error saying it can't read the file.

Was this radared to apple at any point? Its not unreasonable to have non-object code in archives that are used for linking. Not that it needs to block this PR of course.

---

It was convenient to some extent that rmeta stored within the rlib archive and rmeta output by `--emit=metadata` used a similar format. You could use the same tooling to inspect either without further effort. If we're doing this maybe it makes sense to adjust the `rmeta` file format to be a metadata-in-object too? If it hasn't been already, that is.

---

@bors try @rust-timer queue

**Comment by alexcrichton** [comment]
No rush of course!

I haven't reported any issues to other linkers, but AFAIK the behavior of "fail the link if anything doesn't look like an object file" is present in all linkers (`link.exe`, gnu `ld`, `lld`, macOS `ld`, etc)

As for `--emit metadata` I'm happy to implement the change for that as well, it should be easy enough. Alternatively I can document some commands to extract the metadata from the object file if you think that would be useful.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 3]
```diff
@@ -387,8 +391,91 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+    //   the `IMAGE_SCN_LNK_REMOVE` flag set which ensures that if the linker
+    //   ever sees the section it doesn't process it and it's removed.
+    //
+    // * ELF - All other targets are similar to Windows in that there's a
+    //   `SHF_EXCLUDE` flag we can set on sections in an object file to get
+    //   automatically removed from the final output.
+    //
+    // Note that this metdata format is kept in sync with
+    // `rustc_codegen_llvm/src/metadata.rs`.
+    fn create_metadata_object(sess: &Session, metadata: &[u8]) -> Vec<u8> {
```
Comment (nagisa) [inline compiler/rustc_codegen_ssa/src/back/link.rs:431]: Naming nit: since this doesn't always produce an object (wasm), this should perhaps be named `create_metadata_file` or something 'long those lines?

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (nagisa) [reply compiler/rustc_codegen_ssa/src/back/link.rs:449]: Yeah, it seems like a better solution is necessary here. I would perhaps intuitively reach for `object_format: ...` field in the target definition, but perhaps excluding just wasm here is sufficient (majority of the other targets, including the embedded ones, produce elf)

File: compiler/rustc_codegen_llvm/src/metadata.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/metadata.rs:22]: I rebased and reopened #83640.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 4]
```diff
@@ -387,8 +391,91 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+            // compliation if it were supported, but for most of these targets
+            // dylib compilation is not supported anyway (such as WebAssembly).
+            _ => return metadata.to_vec(),
+        };
+
+        if sess.target.is_like_osx {
+            let mut file = Object::new(BinaryFormat::MachO, architecture, endianness);
+
+            let section =
+                file.add_section(b"__DWARF".to_vec(), b".rustc".to_vec(), SectionKind::Debug);
```
Comment (nagisa) [inline compiler/rustc_codegen_ssa/src/back/link.rs:457]: Coming back to this, I'm somewhat worried about reusing the debug segments as a place to store our metadata. Debug info sections seems like something that toolchains may want to inspect in their own ways. AFAICT there are many kinds that are likely better suited here: `Other`, `Metadata`, `Note` etc, that are less likely to be of interest to anybody, and that don't interfere with purpose `__DWARF` or similar segments.

Comment (nagisa) [reply compiler/rustc_codegen_ssa/src/back/link.rs:457]: I can see that `Mach-O` might not have anything else suitable for our purposes, in which case its fine to use `Debug`… I guess. But concern still extends equally to other targets.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/link.rs:457]: Notes end up in the linked executable and I think only exist in ELF. For writing there are only three standard segments: text, data and debug.

https://github.com/gimli-rs/object/blob/2e0af3f6867db3482da40bd8ab1989319da56e78/src/write/macho.rs#L38

On the reading side sections are never classified as other, metadata or note by the macho reader.

https://github.com/gimli-rs/object/blob/2e0af3f6867db3482da40bd8ab1989319da56e78/src/read/macho/section.rs#L202

Comment (nagisa) [reply compiler/rustc_codegen_ssa/src/back/link.rs:457]: Is it necessary to use the `__DWARF` segment for this section? Would it work if we named it something else?

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/link.rs:457]: Maybe?

File: Cargo.lock [hunk 5]
```diff
@@ -5028,7 +5039,7 @@ dependencies = [
  "hermit-abi",
  "libc",
  "miniz_oxide",
- "object",
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply Cargo.lock:5031]: There were some fixes in 0.23  for some object file formats which are necessary to be here (otherwise the writer will panic). In `std` it will update to 0.24 when https://github.com/rust-lang/backtrace-rs/pull/421 is picked up, and this should be able to move forward at that time as well.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 4 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/link.rs:457]: I determined the `__DWARF` here by poking around in the [source of ld64 itself](https://opensource.apple.com/source/ld64/ld64-609/src/ld/parsers). I came upon [this file](https://opensource.apple.com/source/ld64/ld64-609/src/ld/parsers/macho_relocatable_file.cpp.auto.html) where if you search for `__DWARF` in that file you'll see a loop in `Parser<A>::makeSections()`. The goal was to make this loop drop the section with metadata, effectively triggering a `continue` somewhere.

I actually previously looked at this souce when LLVM bitcode was merged into object files since this confirmed that on macOS the bitcode setions were dropped from the final output. Rummaging around this loop the best way that seemed to trick the linker to not include the section in the final output was a `__DWARF` section with an unknown name, so I settled on that. The `SectionKind::Debug` and `__DWARF` name were both chosen to ensure that the branch there in the loop was hit.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/link.rs:449]: It's not that the code here claims it doesn't, nor that I intentionally ignored to add support. The `object` crate currently only supports a limited set of architectures (listed here) and support would need to be added for more architectures. If anything here is tier 2 and fails to build then I can try to find the time to send PRs to `object` myself, otherwise I was hoping others could do it.

**Comment by alexcrichton** [comment]
I'm gonna hold off on trying to fix the CI errors until https://github.com/rust-lang/rust/pull/83640 is merged.

**Comment by alexcrichton** [comment]
I went ahead and rebased on https://github.com/rust-lang/rust/pull/83640 as it fixed the errors locally. I also deleted a bunch of LLVM bindings bits which we no longer use as a result (e.g. parsing object files and dealing with memory buffers)

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (nagisa) [reply compiler/rustc_codegen_ssa/src/back/link.rs:449]: Makes sense. Can the comment above be adjusted to specify that lack of support here refers specifically to lack in the `object` crate, rather than, say, the target toolchain?

**Comment by bjorn3** [comment]
I just realized that embedding metadata in object files can improve rlib metadata load times a bit. If the metadata object contains a predictable symbol, this will end up in the symbol table of the archive. The symbol table can then be used to directly lookup the location of the metadata object without having to search through all archive entries for the right object file.

**Comment by alexcrichton** [comment]
Ok updated!

**Comment by alexcrichton** [comment]
That was a mips64 failure (expected) in that mips64 was being used to create a dylib but the metadata format was a raw file. I couldn't find a corresponding MIPS64 elf constant and the object files look like they're plain MIPS, so I now have both mips and mips64 going to the same object file format.

@bors: r=nagisa

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 6]
```diff
@@ -46,7 +47,10 @@ impl MetadataLoader for DefaultMetadataLoader {
                 let entry = entry_result
                     .map_err(|e| format!("failed to parse rlib '{}': {}", path.display(), e))?;
                 if entry.name() == METADATA_FILENAME.as_bytes() {
-                    return Ok(entry.data());
+                    let data = entry
+                        .data(data)
+                        .map_err(|e| format!("failed to parse rlib '{}': {}", path.display(), e))?;
+                    return search_for_metadata(path, data);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:53]: Isn't code to handle raw metadata files missing?

**Comment by alexcrichton** [comment]
I've fiddled with more bits, looked at some builders, and submitted https://github.com/gimli-rs/object/pull/303

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 6 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:53]: It happens just below in `search_for_metdata` which returns the original slice if `object::File` doesn't parse.

**Comment by alexcrichton** [comment]
I've pushed up what this will look like with that PR merged, but this uses `[patch]` and will probably fail tidy as a result.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 7]
```diff
@@ -385,8 +391,121 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+    //   the `IMAGE_SCN_LNK_REMOVE` flag set which ensures that if the linker
+    //   ever sees the section it doesn't process it and it's removed.
+    //
+    // * ELF - All other targets are similar to Windows in that there's a
+    //   `SHF_EXCLUDE` flag we can set on sections in an object file to get
+    //   automatically removed from the final output.
+    //
+    // Note that this metdata format is kept in sync with
+    // `rustc_codegen_llvm/src/metadata.rs`.
+    fn create_metadata_file(sess: &Session, metadata: &[u8]) -> Vec<u8> {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/link.rs:431]: Can this function be used for the dylib metadata object too? It will need to take a flag if the metadata should end up in the final linked artifact.

File: compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp [hunk 8]
```diff
@@ -1092,15 +1081,6 @@ inline section_iterator *unwrap(LLVMSectionIteratorRef SI) {
   return reinterpret_cast<section_iterator *>(SI);
```
Comment (bjorn3) [inline compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp:1081]: I just noticed that the comment above this function was outdated a bit even before this PR, but will become plain confusing after the removal of `LLVMRustGetSectionName` in this PR.

File: compiler/rustc_codegen_ssa/Cargo.toml [hunk 9]
```diff
@@ -35,6 +35,6 @@ rustc_target = { path = "../rustc_target" }
 rustc_session = { path = "../rustc_session" }
 
 [dependencies.object]
-version = "0.22.0"
+version = "0.24.0"
 default-features = false
-features = ["read_core", "elf", "macho", "pe", "unaligned", "archive"]
+features = ["read_core", "elf", "macho", "pe", "unaligned", "archive", "write"]
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/Cargo.toml:40]: Once the object dependency of backtrace is updated, this new feature will become unified with libstd resulting in binary bloat. Should we switch rustc to the version 2 resolver already?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 10]
```diff
@@ -385,8 +391,121 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+    // * COFF - Windows-like targets create an object with a section that has
+    //   the `IMAGE_SCN_LNK_REMOVE` flag set which ensures that if the linker
+    //   ever sees the section it doesn't process it and it's removed.
+    //
+    // * ELF - All other targets are similar to Windows in that there's a
+    //   `SHF_EXCLUDE` flag we can set on sections in an object file to get
+    //   automatically removed from the final output.
+    //
+    // Note that this metdata format is kept in sync with
+    // `rustc_codegen_llvm/src/metadata.rs`.
```
Comment (luqmana) [inline compiler/rustc_codegen_ssa/src/back/link.rs:430]: Did you mean `rustc_codegen_ssa/src/back/metadata.rs`?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 11]
```diff
@@ -385,8 +391,121 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+            "arm" => Architecture::Arm,
+            "aarch64" => Architecture::Aarch64,
+            "x86" => Architecture::I386,
+            "s390x" => Architecture::S390x,
+            "mips" => Architecture::Mips,
+            "mips64" => Architecture::Mips64,
+            "x86_64" => Architecture::X86_64,
+            "powerpc" => Architecture::PowerPc,
+            "powerpc64" => Architecture::PowerPc64,
+            "riscv64" => Architecture::Riscv64,
```
Comment (luqmana) [inline compiler/rustc_codegen_ssa/src/back/link.rs:446]: Add Riscv32 since you already added support for it in `object` in https://github.com/gimli-rs/object/pull/303?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 12]
```diff
@@ -385,8 +391,121 @@ fn link_rlib<'a, B: ArchiveBuilder<'a>>(
...
+            // * Targets like WebAssembly don't support dylibs, so the purpose
+            //   of putting metadata in object files, to support linking rlibs
+            //   into dylibs, is moot.
+            //
+            // In both of these cases it means that linking into dylibs will
+            // not be supported by rustc. This doesn't matter for targets like
+            // WebAssembly and for targets not supported by the `object` crate
+            // yet it means that work will need to be done in the `object` crate
+            // to add a case above.
+            _ => return metadata.to_vec(),
```
Comment (luqmana) [inline compiler/rustc_codegen_ssa/src/back/link.rs:464]: Is it worth separating out the cases of "don't support dylibs" and "no support in object"? For the former it'd be fine to return the metadata like you have now but in the latter case perhaps a `bug!` invocation to call out that this is just unimplemented.

File: compiler/rustc_codegen_ssa/Cargo.toml (hunk 9 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/Cargo.toml:40]: No libstd and rustc have separate builds, so they get separate feature sets. This won't affect libstd. Changing the resolver for Cargo also won't affect anything here.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 11 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/link.rs:446]: Yes I will add it once I re-sync after the `object` crate is published to crates.io

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 12 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/link.rs:464]: Given how rlibs are ubiquitous in Rust and there are so many custom targets everyone uses I didn't really want to start hitching "is this target supported" to some condition here. I don't want to be the one responsible for handling those regressions and tracking things down.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 7 above)
Comment (alexcrichton) [reply compiler/rustc_codegen_ssa/src/back/link.rs:431]: I think I'll leave that for a future refactoring, I don't want to take on all possible refactorings in all small changes I make...

**Comment by alexcrichton** [comment]
Looks like sparc64 still needs to be implemented in `object`, I'll leave that to a future PR.

@bors: r=nagisa

**Comment by bjorn3** [comment]
Looks like it can't find the `rustc_driver` when compiling rustc-main.

**Comment by klensy** [comment]
Currently `.rmeta` file equal `.rmeta` file inside `.rlib`, that blows `deps` folder size x2. With this change it will be 2 different `.rmeta`s?

**Comment by alexcrichton** [comment]
@bors: r=nagisa

@klensy this isn't blowing up anything by 2x. It's changing how lib.rmeta is encoded in rlibs. Nothing will change from before other than this.

**Comment by klensy** [comment]
@alexcrichton You read me wrong, i sayd that: currently rmeta's have 2 equal copy: one in rlib and one in raw rmeta file(next to rlib file).

**Comment by alexcrichton** [comment]
Er, then yes, you're right that things are changing. The two rmeta files will now be different.

**Comment by klensy** [comment]
So, why having 2 copy of the same thing, even if one of them will be encoded differently?

**Comment by bjorn3** [comment]
The standalone `.rmeta` is necessary for build pipelining. The `.rmeta` embedded in a `.rlib` file is necessary for rustc to find the metadata when linking against the `.rlib` as you can only point to either a `.rmeta` or `.rlib` for a crate, not both.

**Comment by alexcrichton** [comment]
Thanks @philipc for your help in the `object` crate to get this landed!
