### PR TITLE
Fix indeterminism in ty::TraitObject representation.

### LINKED ISSUE #36155: Link error regression on nightly
When running `cargo test` inside the `futures-cpupool` folder of https://github.com/alexcrichton/futures-rs/commit/093a63825e3a2b0f93186afdf0e9ac47f0df2cfa, I get an error looking like:

```
$ cargo +nightly test
   Compiling crossbeam v0.2.10
   Compiling libc v0.2.15
   Compiling log v0.3.6
   Compiling futures v0.1.0 (file:///home/alex/code/futures)
   Compiling num_cpus v1.0.0
   Compiling futures-cpupool v0.1.0 (file:///home/alex/code/futures/futures-cpupool)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o" "-o" "/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/alex/code/futures/futures-cpupool/target/debug/deps" "-L" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-411f48d3.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libfutures_cpupool.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libnum_cpus-f32c6a9cbd8fad0a.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libcrossbeam-2f53cae32cd2c9f1.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libfutures.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-411f48d3.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/liblibc-1bd8847afb79f283.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-411f48d3.rlib" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
  = note: /home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o: In function `futures_cpupool::{{impl}}::spawn<futures::lazy::Lazy<closure, core::result::Result<(), ()>>>':
/home/alex/code/futures/futures-cpupool/src/lib.rs:165: undefined reference to `_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Error$u3d$$LP$$RP$$C$$u20$Item$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he6071928c27d1a12'
/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o: In function `futures_cpupool::{{impl}}::spawn<Box<Future>>':
/home/alex/code/futures/futures-cpupool/src/lib.rs:165: undefined reference to `_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Error$u3d$$LP$$RP$$C$$u20$Item$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he6071928c27d1a12'
collect2: error: ld returned 1 exit status
$ rustc +nightly -vV
rustc 1.13.0-nightly (77d2cd28f 2016-08-29)
binary: rustc
commit-hash: 77d2cd28fd715d2b9751de82b14d28ce6e376728
commit-date: 2016-08-29
host: x86_64-unknown-linux-gnu
release: 1.13.0-nightly
```

I haven't had a chance to minimize this yet unfortunately, but I figure that a bug report is better than no bug report.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Make sure that projection bounds in `ty::TraitObject` are sorted in a way that is stable across compilation sessions and crate boundaries.

This PR
-  moves `DefPathHashes` up into `librustc` so it can be used there to create a stable sort key for `DefId`s,
- changes `PolyExistentialProjection::sort_key()` to take advantage of the above,
- and removes the unused `PolyProjectionPredicate::sort_key()` and `ProjectionTy::sort_key()` methods.

Fixes #36155

### CODE REVIEW

File: src/librustc/ty/context.rs [hunk 1]
```diff
@@ -1303,7 +1303,11 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
     }
 
     pub fn mk_trait(self, mut obj: TraitObject<'tcx>) -> Ty<'tcx> {
-        obj.projection_bounds.sort_by(|a, b| a.sort_key().cmp(&b.sort_key()));
+
```
Comment (arielb1) [inline src/librustc/ty/context.rs]: nit: extra whitespace

File: src/librustc/ty/sty.rs [hunk 2]
```diff
@@ -738,8 +733,16 @@ impl<'a, 'tcx, 'gcx> PolyExistentialProjection<'tcx> {
         self.0.item_name // safe to skip the binder to access a name
     }
 
-    pub fn sort_key(&self) -> (DefId, Name) {
-        (self.0.trait_ref.def_id, self.0.item_name)
+    pub fn sort_key(&self, hasher: &mut DefPathHashes) -> (u64, InternedString) {
+        // We want something here that is stable across trait boundaries.
```
Comment (arielb1) [inline src/librustc/ty/sty.rs]: *across crate boundaries. Shouldn't you store the hash on the `TraitDef` rather than recomputing it on every `mk_trait`?

File: src/librustc/ty/sty.rs [hunk 3]
```diff
@@ -738,8 +733,16 @@ impl<'a, 'tcx, 'gcx> PolyExistentialProjection<'tcx> {
...
+        // The DefId isn't but the `deterministic_hash` of the corresponding
+        // DefPath is.
+        let def_path_hash = hasher.hash(self.0.trait_ref.def_id);
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Could we use this in the `TypeId` hasher as well?

**Comment by eddyb** [comment]
@michaelwoerister I believe the extra logic in `tyencode` can be removed with this change.

**Comment by alexcrichton** [comment]
Thanks for the investigation and fix @michaelwoerister!

File: src/librustc/ty/sty.rs (hunk 3 above)
Comment (michaelwoerister) [inline src/librustc/ty/sty.rs]: I think so, it's just a hash of crate name + disambiguator and the DefPath components.

File: src/librustc/ty/sty.rs (hunk 2 above)
Comment (michaelwoerister) [inline src/librustc/ty/sty.rs]: > Perf: shouldn't you store the hash on the TraitDef rather than recomputing it on every mk_trait?

Sounds like a good idea :+1:

**Comment by michaelwoerister** [comment]
I followed @arielb1's suggestion and made TraitDef cache the DefPath hash. No need to move DefPathHashes into librustc anymore. I also removed the sorting logic from tyencode as @eddyb suggested.

**Comment by eddyb** [comment]
@michaelwoerister It might be a good idea at this point to fix [`TypeId` trait object handling](https://github.com/rust-lang/rust/blob/f81f4964d26683c9a47ff4516a97ab84095d7bc9/src/librustc/ty/util.rs#L461-L466) and the general [`TypeId` hashing of `DefId`](https://github.com/rust-lang/rust/blob/f81f4964d26683c9a47ff4516a97ab84095d7bc9/src/librustc/ty/util.rs#L419-L422) if you have a working solution, otherwise it risks staying behind and maybe causing subtle bugs.

**Comment by michaelwoerister** [comment]
@eddyb Can't we just do exactly the same as we do when computing the symbol hash? That seems to work pretty well, so far. I'll look into it tomorrow.

**Comment by eddyb** [comment]
@michaelwoerister The symbol hash is a gross hack that dumps type metadata into strings and hashes that with sha2. The new `TypeId` hasher is much simpler and more thorough.
I've successfully replaced the symbol hash with a generic version of the `TypeId` hasher in a WIP branch with no trouble, but I used a stringified version of the `DefPath` instead of a proper hash.
That part is not very relevant to this PR though.

The immediate result of this PR is that [the sorting of trait object projections](https://github.com/rust-lang/rust/blob/f81f4964d26683c9a47ff4516a97ab84095d7bc9/src/librustc/ty/util.rs#L461-L466) is no longer necessary, and since I believe that all `TyTrait` with the same principal trait have the exact same projection bounds, that whole arm can be just:
```rust
            TyTrait(ref data) => {
                self.def_id(data.principal.def_id());
                self.hash(data.builtin_bounds);
            }
```

**Comment by michaelwoerister** [comment]
I don't think it's 'gross' `:)` It's rather DRY actually (at the expense 
of some computational overhead).

Sha2 is not necessary, probably, but how is it more thorough?

**Comment by eddyb** [comment]
@michaelwoerister I only meant that the new `TypeId` hasher is more thorough than the old one, sorry.

**Comment by michaelwoerister** [comment]
@eddyb I'd be all for consolidating the various type-id/type-hash implementations we have in the compiler (and get rid of [this shit](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/debuginfo/metadata.rs#L139) for example :)

File: src/librustc/ty/util.rs [hunk 4]
```diff
@@ -453,17 +453,6 @@ impl<'a, 'gcx, 'tcx> TypeVisitor<'tcx> for TypeIdHasher<'a, 'gcx, 'tcx> {
                 // Hash region and builtin bounds.
                 data.region_bound.visit_with(self);
```
Comment (eddyb) [inline src/librustc/ty/util.rs]: This and `data.principal.visit_with(self);` above it are unnecessary because automatic recursion will hit them anyway.
