### PR TITLE
Prevent building cargo from invalidating build cache of other tools due to conditionally applied `-Zon-broken-pipe=kill` via tracked `RUSTFLAGS`

### LINKED ISSUE #130980: building cargo breaks build-cache for other tools
After https://github.com/rust-lang/rust/pull/130739 I noticed that whenever I modify `run-make` tests (on Windows), stage 1 cargo gets unnecessary rebuilt which also triggers rebuilds for other tools like stage 0 rustdoc. I'm pretty sure something in my implementation is wrong w.r.t. to properly caching, but I didn't invest time in figuring out *why* yet, hence opening this bug to track it.

The build sequence is something like stage 0 std -> stage 1 rustc -> stage 1 std -> stage 1 tool cargo -> stage 0 compiletest / run-make-support / rustdoc.

Example repro steps:
- Run `./x test run-make --stage 1` -> make sure stage 1 cargo is already built.
- Modify a `tests/run-make` rmake.rs test.
- Observe that stage 1 cargo gets rebuilt even though I didn't modify it.

### LINKED ISSUE #131059: Adjusting `-Zon-broken-pipe=kill` to only be applied to `rustc`/`rustdoc` binary wrappers break two cargo tests
In <https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Modifying.20run-make.20tests.20unnecessarily.20rebuild.20stage.201.20cargo> we identified the root cause of https://github.com/rust-lang/rust/issues/130980 (unnecessary stage 1 cargo rebuilds) being

https://github.com/rust-lang/rust/blob/e9df22f51d2f0f062d0beb83a28c8c76883d2ceb/src/bootstrap/src/core/build_steps/tool.rs#L212-L217

The other instance of this is

https://github.com/rust-lang/rust/blob/e9df22f51d2f0f062d0beb83a28c8c76883d2ceb/src/bootstrap/src/core/build_steps/compile.rs#L1058

As @onur-ozkan (thank you so much) pointed out:

> It's not just about cargo builds. If you run `x build clippy` and then `x build cargo`, the build cache for `clippy` will be broken because bootstrap sets `-Zon-broken-pipe=kill` for every invocation except for cargo. Which means building cargo will invalidate any tool build cache which was built previously.

---

I tried to limit application of `-Zon-broken-pipe=kill` to `rustc` and `rustdoc` binary wrappers in `src/bootstrap/src/bin/{rustc,rustdoc}.rs` themselves, and unfortunately this leads to two cargo test failures:

```
---- build::close_output stdout ----
thread 'build::close_output' panicked at tests/testsuite/build.rs:6680:18:

---- expected: tests/testsuite/build.rs:6682:9
++++ actual:   In-memory
   1    1 | [COMPILING] foo v0.1.0 ([ROOT]/foo)
   2    2 | hello stderr!
   3      - [ERROR] [BROKEN_PIPE]
   4      - [WARNING] build failed, waiting for other jobs to finish...

Update with SNAPSHOTS=overwrite

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cargo_command::closed_output_ok stdout ----
thread 'cargo_command::closed_output_ok' panicked at tests/testsuite/cargo_command.rs:549:5:
assertion failed: status.success()


failures:
    build::close_output
    cargo_command::closed_output_ok
```

<details>
<summary>Previous history</summary>

I'm putting up a PR (https://github.com/rust-lang/rust/pull/131060) to remove conditionally adding `-Zon-broken-pipe=kill`, and as [@saethlin pointed out](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Modifying.20run-make.20tests.20unnecessarily.20rebuild.20stage.201.20cargo/near/473489346) we expect two cargo tests to be broken with `RUSTFLAGS=-Zon-broken-pipe=kill ./x test src/tools/cargo` if that is unconditionally passed to bootstrap.

```
---- build::close_output stdout ----
thread 'build::close_output' panicked at tests/testsuite/build.rs:6680:18:

---- expected: tests/testsuite/build.rs:6682:9
++++ actual:   In-memory
   1    1 | [COMPILING] foo v0.1.0 ([ROOT]/foo)
   2    2 | hello stderr!
   3      - [ERROR] [BROKEN_PIPE]
   4      - [WARNING] build failed, waiting for other jobs to finish...

Update with SNAPSHOTS=overwrite

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cargo_command::closed_output_ok stdout ----
thread 'cargo_command::closed_output_ok' panicked at tests/testsuite/cargo_command.rs:549:5:
assertion failed: status.success()


failures:
    build::close_output
    cargo_command::closed_output_ok
```

I don't know if this breaks someone's workflow regarding to piping cargo tool tests, but in the interest of not making everyone rebuild stage1 cargo on every single invocation of `./x test run-make`, I'm considering this as "known breakage" for the time being. As @saethlin suggested:

> If someone wants to both set `-Zon-broken-pipe` and also run the Cargo test suite, I think they should file an issue and be part of a discussion about how to support that and what the costs are.

</details>

### PR DESCRIPTION
**Pull request by jieyouxu**
This PR fixes #130980 where building cargo invalidated the tool build caches of other tools (such as rustdoc) because `-Zon-broken-pipe=kill` was conditionally passed via `RUSTFLAGS` for other tools *except* for cargo. The differing `RUSTFLAGS` triggered tool build cache invalidation as `RUSTFLAGS` is a tracked env var -- any changes in `RUSTFLAGS` requires a rebuild.

`-Zon-broken-pipe=kill` is load-bearing for rustc and rustdoc to not ICE on broken pipes due to usages of raw std `println!` that panics without the flag being set, which manifests in ICEs.

I can't say I like the changes here, but it is what it is...

See detailed discussions and history of `-Zon-broken-pipe=kill` usage in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Internal.20lint.20for.20raw.20.60print!.60.20and.20.60println!.60.3F/near/474593815.

## Approach

This PR fixes the tool build cache invalidation by informing the `rustc` binary shim when to apply `-Zon-broken-pipe=kill` (i.e. when the rustc binary shim is not used to build cargo). This information is not communicated by `RUSTFLAGS`, which is an env var tracked by cargo, and instead uses an untracked env var `UNTRACKED_BROKEN_PIPE_FLAG` so we won't trigger tool build cache invalidation. We preserve bootstrap's behavior of not setting that flag for cargo by conditionally omitting setting `UNTRACKED_BROKEN_PIPE_FLAG` when building cargo.

Notably, the `-Zon-broken-pipe=kill` instance in https://github.com/rust-lang/rust/blob/1e5719bdc40bb553089ce83525f07dfe0b2e71e9/src/bootstrap/src/core/build_steps/compile.rs#L1058 is not modified because that is used to build rustc only and not cargo itself.

Thanks to @cuviper for the idea!

### Integration testing

This PR introduces a run-make test for rustc and rustdoc that checks that when they do not ICE/panic when they encounter a broken pipe of the stdout stream.

I checked this test will catch the broken pipe ICE regression for rustc on Linux (at least) by commenting out https://github.com/rust-lang/rust/blob/1e5719bdc40bb553089ce83525f07dfe0b2e71e9/src/bootstrap/src/core/build_steps/compile.rs#L1058, and the test failed because rustc ICE'd.

### Manual testing

I have manually tried:

1. `./x clean && `./x test build --stage 1` -> `rustc +stage1 --print=sysroot | false`: no ICE.
2. `./x clean` -> `./x test run-make` twice: no stage 1 cargo rebuilds.
3. `./x clean` -> `./x build rustdoc` -> `rustdoc +stage1 --version | false`: no panics.
4. `./x test src/tools/cargo`: tests pass, notably `build::close_output` and `cargo_command::closed_output_ok` do not fail which would fail if cargo was built with `-Zon-broken-pipe=kill`.

## Related discussions

Thanks to everyone who helped!
- https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Applying.20.60-Zon-broken-pipe.3Dkill.60.20flags.20in.20bootstrap.3F
- https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Modifying.20run-make.20tests.20unnecessarily.20rebuild.20stage.201.20.2E.2E.2E
- https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Internal.20lint.20for.20raw.20.60print!.60.20and.20.60println!.60.3F

Fixes https://github.com/rust-lang/rust/issues/130980
Closes https://github.com/rust-lang/rust/issues/131059

---

try-job: aarch64-apple
try-job: x86_64-msvc
try-job: x86_64-mingw

### CODE REVIEW

File: tests/run-make/broken-pipe-no-ice/rmake.rs
Comment (jieyouxu) [inline tests/run-make/broken-pipe-no-ice/rmake.rs:1]: Remark: in theory we might also check `cargo`, but cargo's test suite does catch if `cargo` was built with `-Zon-broken-pipe=kill`.

File: tests/run-make/broken-pipe-no-ice/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    // number 13 pretty consistently.
+    const SIGPIPE: i32 = 13;
+    assert_eq!(status.signal(), Some(SIGPIPE), "{name}");
+
+    assert!(stderr.is_empty(), "{name} stderr:\n{}", stderr);
+}
+
+fn main() {
+    let mut rustc = Command::new(env_var("RUSTC"));
+    rustc.arg("--print=sysroot");
```
[the remark this answers is not in the document]
Comment (Noratrieb) [reply tests/run-make/broken-pipe-no-ice/rmake.rs:44]: but if `-Zon-broken-pipe=kill` is unset, `safe_println` will still emit an IO error, right? which is wrong

**Comment by jieyouxu** [comment]
cc @rust-lang/cargo since this PR should not affect how cargo is built (i.e. cargo should still not get `-Zon-broken-pipe=kill`, would appreciate a double-check.

cc @rust-lang/rustdoc because rustdoc is also built (both before this PR and after) with `-Zon-broken-pipe=kill`, and the regression test exercises the rustdoc binary and checks that it does not panic upon broken pipe. It is not clear to me if this is the desired behavior for rustdoc, hence this FYI.

File: tests/run-make/broken-pipe-no-ice/rmake.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (jieyouxu) [reply tests/run-make/broken-pipe-no-ice/rmake.rs:44]: > but if `-Zon-broken-pipe=kill` is unset, `safe_println` will still emit an IO error, right? which is wrong

Yeah idk how specifically that will be handled, but that is left as an exercise for the future reader.

File: tests/run-make/broken-pipe-no-ice/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+use std::process::{Command, Stdio};
+
+use run_make_support::{env_var, libc};
+
+fn check_broken_pipe_handled_gracefully(name: &str, mut cmd: Command) {
+    cmd.stdout(Stdio::piped()).stderr(Stdio::piped());
+
+    let mut child = cmd.spawn().unwrap();
+    // Close stdout
+    drop(child.stdout.take());
```
Comment (ehuss) [inline tests/run-make/broken-pipe-no-ice/rmake.rs:22]: I would recommend caution with this approach, since it is inherently racey. For example, it assumes that it can close the handle before `rustc` is able to print. There can also be assumptions here about `PIPE_BUF` and other pipe behaviors. This can be unreliable on some systems. For example, on macOS, this should fail occasionally. 

That's why cargo's tests which exercise this same behavior use a proc-macro to synchronize with `rustc`. (see [here](https://github.com/rust-lang/cargo/blob/a06986cda652fb9d91ce027977d2126efa111e4f/tests/testsuite/build.rs#L6576-L6776)). That way the test can ensure that the handle is closed *before* `rustc` prints. Those tests also have some comments about the hazards of how this works.

Comment (jieyouxu) [reply tests/run-make/broken-pipe-no-ice/rmake.rs:22]: Thanks for the context, I see why that test is so complex now...

**Comment by GuillaumeGomez** [comment]
> because rustdoc is also built (both before this PR and after) with -Zon-broken-pipe=kill, and the regression test exercises the rustdoc binary and checks that it does not panic upon broken pipe. It is not clear to me if this is the desired behavior for rustdoc, hence this FYI.

I have to admit I have no idea. Being aligned with rustc seems the best course of action here.

File: src/bootstrap/src/core/build_steps/tool.rs [hunk 3]
```diff
@@ -209,11 +209,27 @@ pub fn prepare_tool_cargo(
...
+    // <https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Applying.20.60-Zon-broken-pipe.3Dkill.60.20flags.20in.20bootstrap.3F>.
+    //
+    // For the rustc discussion, see
+    // <https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Internal.20lint.20for.20raw.20.60print!.60.20and.20.60println!.60.3F>
+    // for proper solutions.
     if !path.ends_with("cargo") {
-        // If the output is piped to e.g. `head -n1` we want the process to be killed,
-        // rather than having an error bubble up and cause a panic.
-        cargo.rustflag("-Zon-broken-pipe=kill");
+        cargo.env("UNTRACKED_BROKEN_PIPE_FLAG", "-Zon-broken-pipe=kill");
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/build_steps/tool.rs:232]: Worth to add a comment that explains why we set this environment variable instead of setting a rustflag. Above there is a lot of context, but it doesn't say anything about the workaround.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/tool.rs]: I did explain this above

> We use a special env var here that is not part of `RUSTFLAGS` tracked by cargo as that will cause unnecessary tool rebuilds due to tool build cache invalidation from building e.g. cargo *without* `-Zon-broken-pipe=kill` but then rustdoc *with* `-Zon-broken-pipe=kill`.

But I appreciate the wall of text makes that harder to spot, so instead I moved the workaround explanation into its own comment next to this env var. I changed the env var to be called `FORCE_ON_BROKEN_PIPE_KILL` as suggested.

File: src/bootstrap/src/bin/rustc.rs [hunk 4]
```diff
@@ -137,6 +137,10 @@ fn main() {
         cmd.args(lint_flags.split_whitespace());
     }
 
+    if let Ok(flags) = env::var("UNTRACKED_BROKEN_PIPE_FLAG") {
+        cmd.args(flags.split_whitespace());
+    }
```
[the remark this answers is not in the document]
Comment (jieyouxu) [reply src/bootstrap/src/bin/rustc.rs]: Changed to use `is_some` and renamed env var to `FORCE_ON_BROKEN_PIPE_KILL`.

**Comment by jieyouxu** [comment]
Changes since last review:

- Renamed untracked env var from `UNTRACKED_BROKEN_PIPE_FLAG` -> `FORCE_ON_BROKEN_PIPE_KILL` as suggested, and check for env var being set then in turn set `-Zon-broken-pipe=kill` explicitly in rustc bin shim to be clearer.
- Improved clarity and locality of the comment for the untracked env var workaround.

File: src/bootstrap/src/bin/rustc.rs [hunk 5]
```diff
@@ -137,6 +137,15 @@ fn main() {
         cmd.args(lint_flags.split_whitespace());
     }
 
+    // Use an untracked env var (untracked by cargo) to pass `-Zon-broken-pipe=kill` to rustc when
+    // this shim is *not* used to build cargo itself, i.e. set `-Zon-broken-pipe=kill` only when
+    // building non-cargo tools.
```
Comment (onur-ozkan) [inline src/bootstrap/src/bin/rustc.rs:142]: We don’t need to mention `cargo` here. Rustc shim doesn’t know anything about `cargo` at this point. It’s more about where we propagate this environment variable.

Comment (jieyouxu) [reply src/bootstrap/src/bin/rustc.rs]: Dropped cargo tracking here and amended the comment to only explain why the flag is conditionally passed.

File: tests/run-make/broken-pipe-no-ice/rmake.rs (hunk 2 above)
Comment (jieyouxu) [reply tests/run-make/broken-pipe-no-ice/rmake.rs]: Adjusted the test to use anonymous pipes instead which will make sure stdout is broken before the command is spawned.

**Comment by jieyouxu** [comment]
Fixed the regression test so this should now be ready for review.

@rustbot ready

File: tests/run-make/broken-pipe-no-ice/rmake.rs [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+        assert_ne!(status.code(), Some(PANIC_ICE_EXIT_CODE), "{bin:?}");
+        // And the stderr should be empty because rustc/rustdoc should've gotten killed.
+        assert!(stderr.is_empty(), "{bin:?} stderr:\n{}", stderr);
+    }
+
+    #[cfg(windows)]
+    {
+        match bin {
+            // On Windows, rustc has a paper that propagates the panic exit code of 101 but converts
+            // broken pipe errors into fatal errors instead of ICEs.
```
Comment (ChrisDenton) [inline tests/run-make/broken-pipe-no-ice/rmake.rs:50]: You could try changing the windows hack to a `early_fatal` error: <https://github.com/rust-lang/rust/blob/cf24c73141a77db730f4b7fda69dcd7e8b113b51/compiler/rustc_driver_impl/src/lib.rs#L1412> I think that would result in the exit code being `1`.

Comment (jieyouxu) [reply tests/run-make/broken-pipe-no-ice/rmake.rs:50]: I'll do that in a follow-up, I would like to stop run-make cargo rebuilds lol

Comment (ChrisDenton) [reply tests/run-make/broken-pipe-no-ice/rmake.rs:50]: Fair!
