### PR TITLE
compiletest: add issue number param to `known-bug`

### LINKED ISSUE #98436: compiletest: known-bug should take an issue number
Basically, instead of `// known-bug`, do `// known-bug #00000` or maybe `// known-bug chalk#00`?

From: https://rust-lang.zulipchat.com/#narrow/stream/326866-t-types.2Fnominated/topic/.2398095.3A.20NLL.3A.20unsound.20verification.20of.20higher.20ranked.20outlives.E2.80.A6/near/287258738

### PR DESCRIPTION
**Pull request by davidkna**
I was getting some errors while testing this, but I'm pretty sure that was unrelated to my changes.

Closes #98436

> Basically, instead of `// known-bug`, do `// known-bug #00000` or maybe `// known-bug chalk#00`?
> 
> From: https://rust-lang.zulipchat.com/#narrow/stream/326866-t-types.2Fnominated/topic/.2398095.3A.20NLL.3A.20unsound.20verification.20of.20higher.20ranked.20outlives.E2.80.A6/near/287258738

I also added an `unknown` escape-hatch because I didn't find corresponding issues for every `// known-bug`.

The syntax also ended up being `// known-bug: `, because of `set_name_value_directive`.

### CODE REVIEW

File: src/tools/compiletest/src/header.rs [hunk 1]
```diff
@@ -395,7 +402,15 @@ impl TestProps {
                 );
                 config.set_name_directive(ln, STDERR_PER_BITWIDTH, &mut self.stderr_per_bitwidth);
                 config.set_name_directive(ln, INCREMENTAL, &mut self.incremental);
-                config.set_name_directive(ln, KNOWN_BUG, &mut self.known_bug);
+                config.set_name_value_directive(ln, KNOWN_BUG, &mut self.known_bug, |b| {
+                    match b.trim() {
+                        "unknown" => KnownBug::Unknown,
+                        bug if Regex::new(r".*#\d+").unwrap().is_match(bug) => {
```
Comment (Mark-Simulacrum) [inline src/tools/compiletest/src/header.rs:408]: This should probably pull the regex out to a lazy_static cache (I think we have some examples in this file already?) to avoid re-compiling it. Alternatively, we might consider not using a regex here; split_once('#') and asserting the second part is a number would be equivalent and likely cheaper.

File: src/tools/compiletest/src/header.rs [hunk 2]
```diff
@@ -395,7 +402,15 @@ impl TestProps {
...
+                            KnownBug::Ref(bug.to_string())
```
Comment (Mark-Simulacrum) [inline src/tools/compiletest/src/header.rs:409]: It doesn't really matter, but it seems like there's no advantage in storing this after parsing -- can we keep the known_bug field as a bool?

File: src/tools/compiletest/src/header.rs (hunk 1 above)
Comment (davidkna) [reply src/tools/compiletest/src/header.rs]: Done.

File: src/tools/compiletest/src/header.rs (hunk 2 above)
Comment (davidkna) [reply src/tools/compiletest/src/header.rs]: Done.

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed

**Comment by davidkna** [comment]
Not sure what happened with git here, but I hope this fixed it.

File: src/test/ui/generic-associated-types/bugs/issue-87735.rs [hunk 3]
```diff
@@ -1,5 +1,5 @@
 // check-fail
-// known-bug
+// known-bug: #87735, #88526
```
Comment (Mark-Simulacrum) [inline src/test/ui/generic-associated-types/bugs/issue-87735.rs:2]: Hm, I didn't notice this before. This is outside the "intended" syntax we're validating; if we want to accept it, I think we should do so intentionally -- and probably update our parser to validate the prefix before # as well (no whitespace?).

Comment (davidkna) [reply src/test/ui/generic-associated-types/bugs/issue-87735.rs:2]: I've updated the parser. I wasn't able to compiler the tests, but it seems to work as expected in the rust playground.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Thanks, I think this is OK for now, the validation isn't too critical anyway.
