### PR TITLE
Don't suggest using fields in a static method

### LINKED ISSUE #33613: Don't suggest using fields in a static method
```rust
fn f(_: bool) {}

struct Foo {
    cx: bool,
}

impl Foo {
    fn bar() {
        f(cx);
    }
}

fn main() {}
```
```
<anon>:9:11: 9:13 error: unresolved name `cx`. Did you mean `self.cx`? [E0425]
<anon>:9         f(cx);
                   ^~
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #33613.

cc @LeoTestard

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -2988,6 +3007,7 @@ impl<'a> Resolver<'a> {
                                               ResolutionError::SelfNotAvailableInStaticMethod);
                             } else {
                                 let last_name = path.segments.last().unwrap().identifier.name;
+                                let mut is_field = false;
                                 let mut msg = match self.find_fallback_in_self_type(last_name) {
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Why not `let(mut msg, mut is_field) = ...`?

File: src/librustc_resolve/lib.rs [hunk 2]
```diff
@@ -3000,7 +3020,14 @@ impl<'a> Resolver<'a> {
...
                                     }
-                                    Field => format!("`self.{}`", path_name),
+                                    Field => {
+                                        is_field = true;
+                                        if self.is_static_method == false {
+                                            format!("`self.{}`", path_name)
+                                        } else {
+                                            "".to_string()
+                                        }
+                                    }
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: I find this whole thing is a bit unclear. Basically we are trying to detect things based on what fields there are in the struct rather than in what kind of expression the error occurs. What you're doing, if I understand correctly, is that you emit the help message when trying to refer to a variable named `path_name` only if we are in a static method of a type that has a field of name `path_name`, wether we are in the context of a call expression or not (which is fine, the type could have a closure field... ).

But you don't catch the cases where the user would try to invoke a method from the type... Maybe this is the right thing to do since good reporting would require remembering that we are in a call-expression context, which may be a bit overkill. But I don't know... the thing is that if the type has both an field and a method named `foo`, then `foo(...)` will spawn the help message saying that you don't have access to the *fields*, but if you have only a method named `foo` and no such field, you will not have the message. All of this seems a bit inconsistent. But maybe it's not that much of a problem...

File: src/librustc_resolve/lib.rs [hunk 3]
```diff
@@ -1025,6 +1029,8 @@ pub struct Resolver<'a> {
     privacy_errors: Vec<PrivacyError<'a>>,
 
     arenas: &'a ResolverArenas<'a>,
+
+    is_static_method: bool,
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Rather than adding a new field to this struct, you could add a `is_static` boolean parameter to the `MethodRibKind` constructor of `RibKind`, whose goal is exactly of indicating wether we are currently inside of a method definition.

File: src/librustc_resolve/lib.rs [hunk 4]
```diff
@@ -2988,6 +3007,7 @@ impl<'a> Resolver<'a> {
                                               ResolutionError::SelfNotAvailableInStaticMethod);
                             } else {
                                 let last_name = path.segments.last().unwrap().identifier.name;
+                                let mut is_field = false;
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Why not let(mut msg, mut is_field) = ...?

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Why not let(mut msg, mut is_field) = ...?

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Why not let(mut msg, mut is_field) = ...?

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Why not let(mut msg, mut is_field) = ...?

File: src/librustc_resolve/lib.rs [hunk 5]
```diff
@@ -392,16 +392,20 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
...
                                            "unresolved name `{}`{}",
                                            path,
                                            msg);
-
             match context {
-                UnresolvedNameContext::Other => { } // no help available
+                UnresolvedNameContext::Other => {
+                    if msg.is_empty() && is_static_method && is_field {
+                        err.help("This is a static method, so you don't have access to \
+                                  this type's fields");
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Personaly I'd remove the ‶so″ in the sentence.
Plus, I'd bit a bit more careful because there will be a lot of cases where the intent of the user wouldn't have been to access the struct fields at all. Maybe stay a bit more conditional : ‶If you meant to access self.{}, you can't because this is a static method.″ Well this is poorly-written but you've got the idea.

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Personaly I'd remove the ‶so″ in the sentence.
Plus, I'd bit a bit more careful because there will be a lot of cases where the intent of the user wouldn't have been to access the struct fields at all. Maybe stay a bit more conditional : ‶If you meant to access self.{}, you can't because this is a static method.″ Well this is poorly-written but you've got the idea.

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Personaly I'd remove the ‶so″ in the sentence.
Plus, I'd bit a bit more careful because there will be a lot of cases where the intent of the user wouldn't have been to access the struct fields at all. Maybe stay a bit more conditional : ‶If you meant to access self.{}, you can't because this is a static method.″ Well this is poorly-written but you've got the idea.

Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Personaly I'd remove the ‶so″ in the sentence.
Plus, I'd bit a bit more careful because there will be a lot of cases where the intent of the user wouldn't have been to access the struct fields at all. Maybe stay a bit more conditional : ‶If you meant to access self.{}, you can't because this is a static method.″ Well this is poorly-written but you've got the idea.

File: src/librustc_resolve/lib.rs (hunk 4 above)
Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: I found it less clear in this context.

File: src/librustc_resolve/lib.rs (hunk 5 above)
Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: I see, well saw.

File: src/librustc_resolve/lib.rs (hunk 4 above)
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: I'd be better than using a mutable variable. This way you are sure that you cannot forget to specify it in any `match` case, even match cases we could add in the future.

File: src/librustc_resolve/lib.rs (hunk 2 above)
Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: Just updating the help message to include non-static methods as well would solve it I guess.

**Comment by GuillaumeGomez** [comment]
Updated.

@LeoTestard: Does the error message seem better to you or still not good?

File: src/librustc_resolve/lib.rs [hunk 6]
```diff
@@ -406,16 +406,20 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
...
                                            E0425,
                                            "unresolved name `{}`{}",
                                            path,
                                            msg);
-
             match context {
-                UnresolvedNameContext::Other => { } // no help available
+                UnresolvedNameContext::Other => {
+                    if msg.is_empty() && is_static_method && is_field {
+                        err.help("This is a static method, you don't have access to \
```
Comment (birkenfeld) [inline src/librustc_resolve/lib.rs]: messages usually start lowercase, no?

Also I remember @steveklabnik saying that "static method" is not supposed to be used, but "associated function".

Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: > messages usually start lowercase, no?

Indeed.

> Also I remember @steveklabnik saying that "static method" is not supposed to be used, but "associated function".

We'll have to wait for confirmation.

Comment (steveklabnik) [inline src/librustc_resolve/lib.rs]: Yes, any `fn` declared in an `impl` block is an associated function, and we call an associated function that takes a `self` a "method".

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/librustc_resolve/lib.rs [hunk 7]
```diff
@@ -1665,7 +1663,7 @@ impl<'a> Resolver<'a> {
                                     let type_parameters =
                                         HasTypeParameters(&sig.generics,
                                                           FnSpace,
-                                                          MethodRibKind);
+                                                          MethodRibKind(false));
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: I'm not sure if it's useful but in doubt, it's certainly more correct to tell wether the method is static here, rather than just using `false`. You have a `MethodSig` so it should be trivial.

File: src/librustc_resolve/lib.rs [hunk 8]
```diff
@@ -1998,7 +1992,7 @@ impl<'a> Resolver<'a> {
...
```
Comment (LeoTestard) [inline src/librustc_resolve/lib.rs]: Same here.

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/librustc_resolve/lib.rs [hunk 9]
```diff
@@ -148,7 +148,7 @@ enum ResolutionError<'a> {
     /// error E0424: `self` is not available in a static method
     SelfNotAvailableInStaticMethod,
     /// error E0425: unresolved name
-    UnresolvedName(&'a str, &'a str, UnresolvedNameContext<'a>),
+    UnresolvedName(&'a str, &'a str, UnresolvedNameContext<'a>, bool, bool),
```
Comment (pnkfelix) [inline src/librustc_resolve/lib.rs]: You should either:
 * document what each of these `bool`'s represents in a comment above this variant. (I know I can infer it by grepping for the other uses of `UnresolvedName`, but I don't like having to do that to make sense of this definition), OR
 * alternative 1: use a struct-style variant (i.e. named fields) instead of a tuple-style variant here, so that you can name each piece of state
 * alternative 2: encode the significance of each `bool` here in the type.
    * (there are many ways to do this, such as introducing two new two variant enums, or introducing two structs that each just wrap around `bool`, so that the name of the struct dictates its significance.)

File: src/librustc_resolve/lib.rs [hunk 10]
```diff
@@ -666,7 +670,9 @@ enum RibKind<'a> {
     // methods. Allow references to ty params that impl or trait
     // binds. Disallow any other upvars (including other ty params that are
     // upvars).
-    MethodRibKind,
+    //
+    // The boolean value represents the fact that this method is static or not.
+    MethodRibKind(bool),
```
Comment (pnkfelix) [inline src/librustc_resolve/lib.rs]: (its good you put the comment here. You *might* consider the alternatives I outlined above, to make the types self-documenting.)

**Comment by pnkfelix** [comment]
@GuillaumeGomez this code looks fine; r=me after you address my nit regarding the way you are representing the boolean state being added to each variant.

File: src/librustc_resolve/lib.rs [hunk 11]
```diff
@@ -406,16 +406,20 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
...
                                            E0425,
                                            "unresolved name `{}`{}",
                                            path,
                                            msg);
-
             match context {
-                UnresolvedNameContext::Other => { } // no help available
+                UnresolvedNameContext::Other => {
+                    if msg.is_empty() && is_static_method && is_field {
+                        err.help("this is an associated function, you don't have access to \
```
Comment (Manishearth) [inline src/librustc_resolve/lib.rs]: If I understand correctly, this is only shown if there is a field by that name?

In that case, we should instead say something like "This is a static (non-`self`) method, and does not have access to fields. If you wished to access `self.{fieldname}` you should add a `self` parameter to the method".

Comment (Manishearth) [inline src/librustc_resolve/lib.rs]: Also, in this case, we should not suggest `self.fieldname` directly -- I don't think this change makes that happen?

Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: > If I understand correctly, this is only shown if there is a field by that name?

Or a method. So what follows your comment cannot really apply.

> Also, in this case, we should not suggest `self.fieldname` directly -- I don't think this change makes that happen?

It does remove it.
