### PR TITLE
Don't suggest changing extern crate w/ alias to use.

### LINKED ISSUE #57672: unused_extern_crates: wrong suggestion for aliased crate
The following suggests converting to a `use`, but that causes it to fail to compile because `use` does not insert into the prelude.

```rust
#![warn(unused_extern_crates)]

extern crate time as time_crate;  // Suggests replacing with `use`.

pub mod m {
    pub use time_crate::Duration;   // But this will fail to compile.
}
```

Perhaps the suggestion should be removed if there is a rename?  

rustc 1.33.0-nightly (2fadb0a16 2019-01-13)
(This is after uniform-paths and the #57557 fix.)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #57672.

### CODE REVIEW

File: src/librustc_typeck/check_unused.rs [hunk 1]
```diff
@@ -158,6 +158,13 @@ fn unused_crates_lint<'tcx>(tcx: TyCtxt<'_, 'tcx, 'tcx>) {
             continue;
         }
 
+        // If the extern crate is renamed, then we cannot suggest replacing it with a use as this
+        // would not insert the new name into the prelude, where other imports in the crate may be
+        // expecting it.
+        if extern_crate.orig_name.is_some() {
+            continue;
+        }
```
Comment (davidtwco) [inline src/librustc_typeck/check_unused.rs]: I would have liked to come up with a more robust check here that would only omit the lint if there was an instance of the extern crate alias being used from the prelude, but I couldn't work out a nice way to achieve this.

Comment (Mark-Simulacrum) [reply src/librustc_typeck/check_unused.rs]: Personally that doesn't seem necessary, and somewhat out of scope for this lint -- that seems more like an "unused extern crate" lint rather than an idiom lint.

**Comment by Mark-Simulacrum** [comment]
@bors r+

This looks fine to me based on the updated tests, so I'm going to approve this. If necessary we can always revert.

r? @Mark-Simulacrum
