### PR TITLE
[mir-opt] Fix mis-optimization and other issues with the SimplifyArmIdentity pass

### LINKED ISSUE #73223: Slice index becomes wrong (beta regression)
One of my tests (`test_nested_rest`) is failing on beta (in CI and locally) but not stable (locally).

https://github.com/djc/mendes/pull/18/checks?check_run_id=759480560

Minimal reproduction:

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=e31da4955ca52b19e2131b51473bcb4e

When executed with miri, it doesn't panic. When the call to nothing() is moved before the assignment to self.prev, it also doesn't panic. Works on stable, panics on both beta and nightly-2020-06-10.

searched nightlies: from nightly-2020-04-12 to nightly-2020-06-10
regressed nightly: nightly-2020-05-15
searched commits: from https://github.com/rust-lang/rust/commit/75e1463c52aaea25bd32ed53c73797357e561cce to https://github.com/rust-lang/rust/commit/a74d1862d4d87a56244958416fd05976c58ca1a8
regressed commit: https://github.com/rust-lang/rust/commit/7c34d8d6629506a596215886e5fc4bb2b04b00ae

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start 2020-04-12 --end 2020-06-10 -- run 
```
</details>

### PR DESCRIPTION
**Pull request by wesleywiser**
This does not yet attempt re-enabling the pass, but it does resolve a number of issues with the pass.

r? @oli-obk 

I believe this closes #73223.

### CODE REVIEW

**Comment by oli-obk** [comment]
I went through the commits each by its own, but I don't see how f00b337 can have the effect that it has (basically reverting most of the MIR opt diff from ed31211). Overall the diff lgtm, but I don't think anything beyond the debug info fixes is shown in MIR diffs. Maybe add the ui test also to MIR opt?

**Comment by wesleywiser** [comment]
@oli-obk I think I forgot to re-bless the mir-opt tests after splitting this into different commits so that's probably part of the issue. I've implemented your suggestion and blessed each commit so you can see the changes.

File: src/librustc_mir/transform/simplify_try.rs [hunk 1]
```diff
@@ -397,7 +442,9 @@ impl LocalUseCounter {
 
 impl<'tcx> Visitor<'tcx> for LocalUseCounter {
     fn visit_local(&mut self, local: &Local, context: PlaceContext, _location: Location) {
-        if context.is_storage_marker() {
+        if context.is_storage_marker()
+            || context == PlaceContext::NonUse(NonUseContext::VarDebugInfo)
```
Comment (oli-obk) [inline src/librustc_mir/transform/simplify_try.rs:447]: are there any `NonUseContext` that are relevant here? The only one left that isn't covered is `AscribeUserTy`. So this could just be `if let `PlaceContext::NonUse(_) = context` I think.

File: src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/32bit/rustc.map.SimplifyLocals.diff [hunk 2]
```diff
@@ -19,9 +19,7 @@
       }
   
       bb1: {
-          _3 = move ((_1 as Some).0: std::boxed::Box<()>); // scope 0 at $DIR/simplify-locals-removes-unused-discriminant-reads.rs:4:14: 4:15
-          ((_0 as Some).0: std::boxed::Box<()>) = move _3; // scope 1 at $DIR/simplify-locals-removes-unused-discriminant-reads.rs:4:20: 4:27
-          discriminant(_0) = 1;            // scope 1 at $DIR/simplify-locals-removes-unused-discriminant-reads.rs:4:20: 4:27
+          _0 = move _1;                    // scope 1 at $DIR/simplify-locals-removes-unused-discriminant-reads.rs:4:20: 4:27
```
Comment (oli-obk) [inline src/test/mir-opt/simplify-locals-removes-unused-discriminant-reads/32bit/rustc.map.SimplifyLocals.diff]: oh now I realize how this is happening... we were missing optimizations because we were marking them as used because of debuginfo

**Comment by oli-obk** [comment]
> I've implemented your suggestion and blessed each commit so you can see the changes.

Thanks! This is absolutely great. I have one more nit, r=me with that + reblessing aftwards.

File: src/librustc_mir/transform/simplify_try.rs (hunk 1 above)
Comment (wesleywiser) [reply src/librustc_mir/transform/simplify_try.rs:447]: Hmm I guess those are unused after NLL runs right? Maybe we should have a separate pass that runs at the beginning of the optimization phase and removes all of those?

Comment (oli-obk) [reply src/librustc_mir/transform/simplify_try.rs:447]: true, and then changing this site to the general match on `NonUseContext` doesn't actually change anything, anymore, so let's do that in a separate PR

**Comment by wesleywiser** [comment]
Since this messes with mir-opt stuff, I'm going to say

@bors rollup=never

Just in case 🙂

**Comment by Manishearth** [comment]
Is the rollup=never for perf stuff or just because you think this will fail a rollup? Because I'm game for including this in a rollup, I typically include at least one iffy PR in a rollup -- if it fails we get early feedback on the PR.

**Comment by wesleywiser** [comment]
@Manishearth More out of an abundance of caution although, since this pass is disabled, it shouldn't have any effect (performance or correctness).

**Comment by Manishearth** [comment]
I'm gonna un-never it then, rollups take this kind of risk pretty typically :smile:

@bors r- rollup=maybe

**Comment by Manishearth** [comment]
@bors r=oli-obk p=0

oops

**Comment by wesleywiser** [comment]
Sounds good. Thanks @Manishearth!
