### PR TITLE
rustc_expand: improve diagnostics for non-repeatable metavars

### LINKED ISSUE #47452: macro_rules: "no syntax variables matched as repeating at this depth" fires before "unknown macro variable"
Consider the following code:

```rust
macro_rules! a {
    (begin $ard: ident end) => {
        [$arg]
    }
}

macro_rules! b {
    (begin $($ard: ident),* end) => {
        [$($arg),*]
    }
}

fn main() {
    let (m, n) = (1, 2);
    let x = a![begin m end];
    let y = b![begin n end];
}
```

This produces the following pair of error messages:

```
error: unknown macro variable `arg`
  --> src/main.rs:3:10
   |
3  |         [$arg]
   |          ^^^^
...
15 |     let x = a![begin m end];
   |             --------------- in this macro invocation

error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth
 --> src/main.rs:9:11
  |
9 |         [$($arg),*]
  |           ^^^^^^

error: Could not compile `playground`.
```

While the second error message is *correct* in principle, it is also misleading. When I get a message like that, my focus is on counting how deeply nested the variable is. I usually don't consider "wait is the syntax variable *misspelled*?" when I see that error message.

I think we could and should first check if a macro variable occurs at *any* depth (and report the first error if not) before we report anything about whether a match is found at the *current* depth (and report the second error if not).

### PR DESCRIPTION
**Pull request by Unique-Usman**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/152679)*

Fix rust-lang/rust#47452.

### CODE REVIEW

**Comment by Unique-Usman** [comment]
This is rebased on top of ->https://github.com/rust-lang/rust/pull/152679/changes/791ee3497c882b74c409454dc4d45f9d6f694c84

File: compiler/rustc_expand/src/mbe/diagnostics.rs [hunk 1]
```diff
@@ -285,6 +287,52 @@ pub(super) fn emit_frag_parse_err(
...
+        parser.bump();
+        if let token::Ident(name, _) = parser.token.kind {
+            if let Some(matched_name) = rustc_span::edit_distance::find_best_match_for_name(
+                &matched_rule_bindings_names[..],
+                name,
+                None,
+            ) {
+                e.span_suggestion_verbose(
+                    parser.token.span,
+                    "this could be a typo, there is a macro argument with similar name",
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/diagnostics.rs]:
```suggestion
                    "there is a macro metavariable with similar name",
```

File: compiler/rustc_expand/src/mbe/diagnostics.rs [hunk 2]
```diff
@@ -285,6 +287,52 @@ pub(super) fn emit_frag_parse_err(
...
+                    format!("{matched_name}"),
+                    Applicability::MaybeIncorrect,
+                );
+            } else if bindings_name.contains(&name) {
+                e.span_label(
+                    parser.token.span,
+                    format!("there is an exact macro argument in the other matcher"),
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/diagnostics.rs]:
```suggestion
                    format!("there is an macro metavariable with this name in another macro matcher"),
```

File: compiler/rustc_expand/src/mbe/diagnostics.rs [hunk 3]
```diff
@@ -285,6 +287,52 @@ pub(super) fn emit_frag_parse_err(
...
+                );
+            } else if let Some(matched_name) =
+                rustc_span::edit_distance::find_best_match_for_name(&bindings_name[..], name, None)
+            {
+                e.span_suggestion_verbose(
+                    parser.token.span,
+                    "this could be a typo, there is a macro argument with similar name in the other matcher",
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/diagnostics.rs]:
```suggestion
                    "there is a macro metavariable with a similar name in another macro matcher",
```

File: compiler/rustc_expand/src/mbe/diagnostics.rs [hunk 4]
```diff
@@ -285,6 +287,52 @@ pub(super) fn emit_frag_parse_err(
...
+            } else {
+                let msg = matched_rule_bindings_names
+                    .iter()
+                    .map(|sym| format!("${}", sym))
+                    .collect::<Vec<_>>()
+                    .join(", ");
+
+                e.span_label(
+                    parser.token.span,
+                    format!("this could be a typo, there is no macro argument with similar name, available macro arguments are: {msg}"),
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/diagnostics.rs]:
```suggestion
                    format!("macro metavariable not found"),
```

File: compiler/rustc_expand/src/mbe/diagnostics.rs [hunk 5]
```diff
@@ -285,6 +287,52 @@ pub(super) fn emit_frag_parse_err(
...
+                );
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/diagnostics.rs]:
```suggestion
                );
                if !matched_rule_bindings_names.is_empty() {
                    err.note(format!("available metavariable names are: {msg}"));
                }
```

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 6]
```diff
@@ -388,8 +404,33 @@ fn expand_macro<'cx>(
                 cx.resolver.record_macro_rule_usage(node_id, rule_index);
             }
 
+            let mut bindings = vec![];
+            for rule in rules {
+                let MacroRule::Func { lhs, .. } = rule else { continue };
+                for param in lhs {
+                    let MatcherLoc::MetaVarDecl { bind, .. } = param else { continue };
+                    tracing::info!(?bind);
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/macro_rules.rs]:
```suggestion
```

**Review by estebank — APPROVED** [review]

**Comment by Unique-Usman** [comment]
@estebank - this is ready to land. Thank you for the review.

**Comment by Kobzol** [comment]
@rust-timer build 2f7d51a313739380dbe5fa7a71454821a3a8df04

For https://github.com/rust-lang/rust/pull/153074.

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 7]
```diff
@@ -387,8 +404,32 @@ fn expand_macro<'cx>(
...
+                    let MatcherLoc::MetaVarDecl { bind, .. } = param else { continue };
+                    bindings.push(*bind);
+                }
+            }
+
+            let mut matched_rule_bindings = vec![];
+            for param in lhs {
+                let MatcherLoc::MetaVarDecl { bind, .. } = param else { continue };
+                matched_rule_bindings.push(*bind);
+            }
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:420]: Without closely looking at the lifetimes, it might be that we can pass `lhs` and `rules` to `from_tts` and move this logic to the error code path.

Comment (Unique-Usman) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:420]: Yep, I will take a look. Is there any local way to test for the regression though ?

Comment (Kobzol) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:420]: You can try `x perf` (https://rustc-dev-guide.rust-lang.org/profiling/with-rustc-perf.html), though it's hard to tell whether it will find this regression. You can try it with the serde/clap derive crates.

Comment (estebank) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:420]: This would be moved to where `diagnostics::emit_frag_parse_err` is called

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 8]
```diff
@@ -55,6 +56,8 @@ pub(crate) struct ParserAnyMacro<'a> {
     arm_span: Span,
     /// Whether or not this macro is defined in the current crate
     is_local: bool,
+    bindings: Vec<Ident>,
+    matched_rule_bindings: Vec<Ident>,
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:60]:
```suggestion
    bindings: &'a [MacroRule],
    matched_rule_bindings: &'a [MatcherLoc],
```

**Review by estebank — COMMENTED** [review]
notes from our 1:1 conversation

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152679/eeb94be79adc9df7a09ad0b2421f16e60e6d932c..93b997356aa3a006475c169db42d9279d745bf36)*
