### PR TITLE
Fix invalid silencing of parsing error

### LINKED ISSUE #123079: ICE: ` prefix is unknown`
snippet:
````rust
macro_rules! TrivialTypeTraversalImpls {
    ( ) => {
        $(
            impl<'tcx> $crate::ty::fold::<$crate::ty::TyCtxt<'tcx>> for $ty {
                fn <F: $crate::ty::fold::<$crate::ty::TyCtxtty'format_args>>> -> ::std::result::Result<Self, F::Error>

                #[inline]
                fn fold_with<F: $crate::ty::fold::TypeFolder<$crate::ty::TyCtxt<'tcx>>> -> Self
            }

            impl<'tcx> $crate::ty::visit::<$crate::ty::TyCtxt<'tcx>> for $fmt
        )+
    };
}


````

Version information
````
rustc 1.79.0-nightly (35936c483 2024-03-25)
binary: rustc
commit-hash: 35936c4839dd272646394779d151e060d0f6b3ac
commit-date: 2024-03-25
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2021 --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused macro definition: `TrivialTypeTraversalImpls`
 --> /tmp/icemaker_global_tempdir.FffekGIQB7Un/rustc_testrunner_tmpdir_reporting.U2wAqBOnvaRS/mvce.rs:1:14
  |
1 | macro_rules! TrivialTypeTraversalImpls {
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default

warning: 1 warning emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: prefix `TyCtxtty` is unknown
 --> /tmp/icemaker_global_tempdir.FffekGIQB7Un/rustc_testrunner_tmpdir_reporting.U2wAqBOnvaRS/mvce.rs:5:55
  |
5 |                 fn <F: $crate::ty::fold::<$crate::ty::TyCtxtty'format_args>>> -> ::std::result::Result<Self, F::Error>
  |                                                       ^^^^^^^^ unknown prefix
  |
  = note: prefixed identifiers and literals are reserved since Rust 2021
note: delayed at compiler/rustc_parse/src/lexer/mod.rs:724:28
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxt>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_parse::lexer::StringReader>::report_unknown_prefix
         4: <rustc_parse::lexer::tokentrees::TokenTreesReader>::bump
         5: <rustc_parse::lexer::tokentrees::TokenTreesReader>::parse_token_trees
         6: <rustc_parse::lexer::tokentrees::TokenTreesReader>::parse_token_trees
         7: <rustc_parse::lexer::tokentrees::TokenTreesReader>::parse_token_trees
         8: <rustc_parse::lexer::tokentrees::TokenTreesReader>::parse_token_trees
         9: <rustc_parse::lexer::tokentrees::TokenTreesReader>::parse_token_trees
        10: rustc_parse::maybe_file_to_stream
        11: rustc_parse::maybe_source_file_to_parser
        12: rustc_parse::new_parser_from_file
        13: rustc_interface::passes::parse
        14: <rustc_interface::queries::Queries>::parse
        15: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
        16: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        17: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/alloc/src/boxed.rs:2015:9
        19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/alloc/src/boxed.rs:2015:9
        20: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/35936c4839dd272646394779d151e060d0f6b3ac/library/std/src/sys/pal/unix/thread.rs:108:17
        21: <unknown>
        22: <unknown>
 --> /tmp/icemaker_global_tempdir.FffekGIQB7Un/rustc_testrunner_tmpdir_reporting.U2wAqBOnvaRS/mvce.rs:5:55
  |
5 |                 fn <F: $crate::ty::fold::<$crate::ty::TyCtxtty'format_args>>> -> ::std::result::Result<Self, F::Error>
  |                                                       ^^^^^^^^
help: if you meant to write a string literal, use double quotes
  |
4 ~             impl<'tcx> $crate::ty::fold::<$crate::ty::TyCtxt<"tcx>> for $ty {
5 ~                 fn <F: $crate::ty::fold::<$crate::ty::TyCtxtty"format_args>>> -> ::std::result::Result<Self, F::Error>
  |

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0-nightly (35936c483 2024-03-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by estebank**
Given

```rust
macro_rules! a {
    ( ) => {
        impl<'b> c for d {
            e::<f'g>
        }
    };
}
```

ensure an error is emitted.

Fix #123079.

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
So it turns out that this still ICEs:

```
macro_rules! a {
    ( ) => {
        impl<'b> c for f'f {}
    };
}
fn main() {}
```

Specifically, this ICE example above suggests that having an exhaustive list of tokens to disable this behavior (`self.last_lifetime = None;`) is fragile.

I think the right solution is to not delay a bug at all for this class of errors. If the redundancy is too noisy, we should instead be using diagnostic stashing to actually ensure that *at least* one error is emitted.

**Comment by compiler-errors** [comment]
Beginning to think that the right solution is just to revert ea1883d7b2207d1a0f08046f11ca493803bc8a55 -- suppressing the prefix error seems nice in theory, but perhaps not worth the complication of getting it right. Curious what @fmease thinks, since he [suggested this](https://github.com/rust-lang/rust/pull/122217#pullrequestreview-1927642744).

**Comment by fmease** [comment]
fine by me 👍

**Comment by estebank** [comment]
@compiler-errors yeah, I agree. I spend some time last night trying to come up with counter examples or alternative approcaches, but it got late enough that I convinced myself that removing the delay was likely the best thing to do.

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 1]
```diff
@@ -138,6 +138,9 @@ impl<'psess, 'src> StringReader<'psess, 'src> {
             if let rustc_lexer::TokenKind::Semi
             | rustc_lexer::TokenKind::LineComment { .. }
             | rustc_lexer::TokenKind::BlockComment { .. }
+            | rustc_lexer::TokenKind::OpenParen
+            | rustc_lexer::TokenKind::OpenBrace
+            | rustc_lexer::TokenKind::OpenBracket
```
Comment (estebank) [inline compiler/rustc_parse/src/lexer/mod.rs:143]: I'm keeping this change because we still use `last_lifetime` for string literals (this will make suggestions for `'foo (bar)'" that was meant to be a string to stop working, but that should be fine.

Comment (compiler-errors) [reply compiler/rustc_parse/src/lexer/mod.rs:143]: Why is this beneficial? The only time I could see us not want to make string lit suggestions is:
1. If the string literal has a newline in it
2. The number of delimiters are inbalanced between the start and end of the string 


But the presence of delims don't really make it any less likely you meant a string lit imo

Comment (estebank) [reply compiler/rustc_parse/src/lexer/mod.rs]: Beneficial in the sense of being more conservative, but I'm not strongly inclined either way. Removed the change.
