### PR TITLE
Disallow defaults on type GATs

### LINKED ISSUE #99205: defaults on `GATs` emit an error but function correctlyish
I tried this code: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=046796c21ebf3085d085609134bdd5f8)
```rust
#![feature(generic_associated_types)]
#![allow(invalid_type_param_default)]

trait Trait {
    type Assoc<T = u32>;
}

impl Trait for () {
    type Assoc<T = u32> = u64; 
}

impl Trait for u32 {
    type Assoc<T = u32> = T;
}

trait Other {}
impl Other for u32 {}

fn foo<T>()
where
    T: Trait<Assoc = u32>, 
    T::Assoc: Other {
        
    }
    
fn main() {
    // errors
    foo::<()>();
    // works
    foo::<u32>();
}
```

I expected to see this happen: It not work correctly as if you remove `#![allow(invalid_type_param_default)]` it shouts at you saying its unsupported and will be a hard error one day.

Instead, this happened: defaults on GATs seem to function perfectly fine

### Meta

version from playground:
```
 1.64.0-nightly
(2022-07-12 1c7b36d4db582cb47513)
```

cc @jackh726 this is probably should either be allowed or a hard error before stabilisation?

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #99205

### CODE REVIEW

**Comment by est31** [comment]
This will probably also need a beta backport for the soon to branch beta, right?

**Comment by davidtwco** [comment]
r? rust-lang/compiler

File: compiler/rustc_typeck/src/collect.rs [hunk 1]
```diff
@@ -1671,20 +1683,31 @@ fn generics_of(tcx: TyCtxt<'_>, def_id: DefId) -> ty::Generics {
...
+                    Defaults::FutureCompatDisallowed if tcx.features().default_type_parameter_fallback => {}
+                    Defaults::FutureCompatDisallowed => {
+                        tcx.struct_span_lint_hir(
+                            lint::builtin::INVALID_TYPE_PARAM_DEFAULT,
+                            param.hir_id,
+                            param.span,
+                            |lint| {
+                                lint.build(
+                                    "defaults for type parameters are only allowed in \
+                                     `struct`, `enum`, `type`, or `trait` definitions",
```
Comment (lcnr) [inline compiler/rustc_typeck/src/collect.rs:1698]: can you put that string into a const?

**Review by lcnr — COMMENTED** [review]
1 nit, then r=me

thanks :sweat_smile: :heart:

**Comment by jackh726** [comment]
@est31 should be fine, can get this in before branch

File: compiler/rustc_typeck/src/collect.rs (hunk 1 above)
Comment (est31) [reply compiler/rustc_typeck/src/collect.rs:1698]: Maybe it can be made translatable right away? E.g. like this: https://github.com/rust-lang/rust/commit/7ef610c003f8072ec4ca4ecf195922a9a44e48dd

Comment (jackh726) [reply compiler/rustc_typeck/src/collect.rs]: I'm really short on time this week. I'd rather get this in now, because don't want to miss beta cutoff.
