### PR TITLE
Access individual fields of tuples, closures and generators on drop.

### LINKED ISSUE #48623: isolate `librustc_metadata` regression using NLL
If you start from [my nll-bootstrap branch](https://github.com/rust-lang/rust/pull/48372) and try to build rustc with NLL enabled, like so:

```bash
> RUSTFLAGS_STAGE_NOT_0="-Znll -Zborrowck=mir -Ztwo-phase-borrows" ./x.py build
```

You will find that it dies here:

```
error[E0597]: `**self.ecx` does not live long enough
   --> src/librustc_metadata/index_builder.rs:128:58
    |
128 |             let mut entry_builder = IsolatedEncoder::new(self.ecx);
    |                                                          ^^^^^^^^ borrowed value does not live long enough
...
133 |         })
    |         - borrowed value only lives until here
    |
    = note: borrowed value must be valid for lifetime '_#13r...
```

It would be great if somebody were able to help isolate this into a standalone test case! This basically involves extract code from the environment until we reproduce the error. 

I took a stab at it but did not yet finish. This gist contains my intermediate results:

https://gist.github.com/nikomatsakis/f2103b4c3f4299a77e8eb472b236d985

cc @rust-lang/wg-compiler-nll -- It'd be great if somebody wanted to take this on! This is a fairly high priority item, because I would like to get the point where we are able to bootstrap rustc and hence know all of the issues that arise!

### PR DESCRIPTION
**Pull request by matthewjasper**
Fixes #48623, by extending the change in #47917 to closures. Also does this for tuples and generators for consistency.

Enums are unchanged because there is no way to borrow `*enum.field` without borrowing `enum.field` at the moment, so any error would be reported when the enum goes out of scope. Unions aren't changed because unions they don't automatically drop their fields.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -740,6 +740,30 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                    let field_ty = gcx.normalize_erasing_regions(self.param_env, *field);
+                    let place = drop_place.clone().field(Field::new(index), field_ty);
+
+                    self.visit_terminator_drop(loc, term, flow_state, &place, field_ty, span);
+                }
+            }
+            // Closures and generators also have disjoint fields, but they are only
+            // directly accessed in the body of the closure/generator.
+            ty::TyClosure(def, substs)
+            | ty::TyGenerator(def, substs, ..)
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Generators are a bit funny -- I'm not sure if `upvar_tys` is correct for that case? 

Maybe @Zoxc can comment how to get the list of fields for a generator type, else I'll dig in later.

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -740,6 +740,30 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                     self.visit_terminator_drop(loc, term, flow_state, &place, field_ty, span);
                 }
             }
+            // Same as above, but for tuples.
+            ty::TyTuple(tys) => {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Hmm, maybe we can extract a helper function here? If feels a bit silly to have basically the same code repeated so many times.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks good (modulo generators), though I keep having this nagging feeling we can refactor this another way. But this seems like it is extending the existing fix, which is fine.

File: src/librustc_mir/borrow_check/mod.rs (hunk 2 above)
Comment (matthewjasper) [reply src/librustc_mir/borrow_check/mod.rs]: Done. I preferred a closure to avoid having to pass all of the captured variables as arguments.

**Comment by pietroalbini** [comment]
Ping from triage! Could @nikomatsakis (or someone else from @rust-lang/compiler) review this?

**Review by nikomatsakis — APPROVED** [review]
