### PR TITLE
Fix Box allocator drop elaboration

### LINKED ISSUE #131082: Box sometimes forgets to drop its allocator when the Box is conditionally initialized.
I tried this code:

```rust
#![feature(allocator_api)]

use std::alloc::{Allocator, AllocError, Layout, Global};
use std::ptr::NonNull;

struct LoudDropAllocator;

unsafe impl Allocator for LoudDropAllocator {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        Global.allocate(layout)
    }
    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        Global.deallocate(ptr, layout);
    }
}
impl Drop for LoudDropAllocator {
    fn drop(&mut self) {
        println!("dropping allocator...");
    }
}

struct HasDrop;
impl Drop for HasDrop {
    fn drop(&mut self) {}
}

fn foo() {
    println!("foo()");
    let b = Box::new_in(HasDrop, LoudDropAllocator);
    if true {
        drop(*b);
    } else {
        drop(b);
    }
}

fn bar() {
    println!("bar()");
    let b = Box::new_in(HasDrop, LoudDropAllocator);
    if true {
        drop(*b);
    } else {
        // drop(b);
    }
}

fn main() {
    foo();
    bar();
}
```

I expected the program to output:
```
foo()
dropping allocator...
bar()
dropping allocator...
```

Instead it output:
```
foo()
bar()
dropping allocator...
```

Seems like there's something wrong with the drop flags.

Making `HasDrop` not implement `Drop` causes the program to behave as expected.

### Meta

Reproducible on the playground with version `1.83.0-nightly (2024-09-30 fb4aebddd18d258046dd)`

### PR DESCRIPTION
**Pull request by beepster4096**
New version of rust-lang/rust#131146.

Clearing Box's drop flag after running its destructor can cause it to skip dropping its allocator, so just don't. Its cleared by the drop ladder code afterwards already.

Unlike the last PR this also handles other types with destructors properly, in the event that we can have open drops on them in the future (by partial initialization or DerefMove or something).

Finally, I also added tests for the interaction with async drop here but I discovered rust-lang/rust#143658, so one of the tests has a `knownbug` annotation. Not sure if it should be in this PR at all though.

Fixes rust-lang/rust#131082

r? wesleywiser - prev. reviewer

### CODE REVIEW

**Comment by beepster4096** [comment]
r? compiler since wesleywiser is off rotation

**Comment by WaffleLapkin** [comment]
r? compiler

**Comment by fee1-dead** [comment]
r? compiler

**Comment by oli-obk** [comment]
lmao I should have just taken this PR when I saw it right when it was opened

File: compiler/rustc_mir_transform/src/elaborate_drop.rs [hunk 1]
```diff
@@ -761,24 +761,36 @@ where
 
         let skip_contents = adt.is_union() || adt.is_manually_drop();
         let contents_drop = if skip_contents {
-            (self.succ, self.unwind, self.dropline)
+            if adt.has_dtor(self.tcx()) {
+                // the top-level drop flag is usually cleared by open_drop_for_adt_contents
+                // types with destructors still need an empty drop ladder to clear it
+
+                // currently no rust types can trigger this path in a context where drop flags exist
+                // however, a future box-like "DerefMove" trait would allow it
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/elaborate_drop.rs]: so... should we `span_bug!` here until such a time?

Comment (beepster4096) [reply compiler/rustc_mir_transform/src/elaborate_drop.rs]: Hm, I should clarify the comment. This codepath is taken with some types today, but only with `DropShimElaborator` and not `ElaborateDropsCtxt`. It would be nice to panic here with `ElaborateDropsCtxt` only but I'm not sure how to accomplish that.

Comment (oli-obk) [reply compiler/rustc_mir_transform/src/elaborate_drop.rs]: just adjusting the comment is sufficient for me

Comment (beepster4096) [reply compiler/rustc_mir_transform/src/elaborate_drop.rs]: I remembered what I was going to do to make the span_bug work

**Comment by jieyouxu** [comment]
I believe this is missing a test change on `test-various` or is somehow different: https://github.com/rust-lang/rust/pull/144262#issuecomment-3097564785

```
---- [mir-opt] tests/mir-opt/box_conditional_drop_allocator.rs stdout ----
74   
75       bb6: {
76           StorageDead(_4);
- -         drop(_1) -> [return: bb7, unwind continue];
+ -         drop(_1) -> [return: bb7, unwind: bb13];
78 +         goto -> bb23;
79       }
80   
```

@bors r-

**Comment by beepster4096** [comment]
I think the solution is `//@ needs-unwind`, I just don't understand why `wasm32-wasip1` has this particular effect on mir generation..

**Comment by beepster4096** [comment]
It's because `RemoveNoopLandingPads` doesn't run when `panic=abort`. I wonder if we should actually do that? Its a little silly to have all these mir-opt tests with `@ needs-unwind` that don't actually need unwinding support.

**Comment by samueltardieu** [comment]
Failed while uploading artifacts to S3.
@bors retry
