### PR TITLE
fix(span): track unnormalized source len for dep-info

### LINKED ISSUE #148934: `-Zchecksum-hash-algorithm` used normalized file size in dep-info
## Problem 

`-Zchecksum-hash-algorithm` writes magic comments to dep-info files to info build tool [like Cargo](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#checksum-freshness) about source file checksum and file length

```
# checksum:{checksum_hash} file_len:{file_len} {path}
```

https://github.com/rust-lang/rust/blob/d6deffe2debecc66501e50f9573214139ab4d678/compiler/rustc_interface/src/passes.rs?plain=1#L747-L758

However, the above code uses `SourceFile.source_len` from `SourceMap` that the length of the file is normalized length (BOM-removed, newline normalized). That makes external tools harder to verify the checksum, as they need to follow all the normalizations rustc did to compute exact the same checksum

## Possible solution

Instead of using normalized file length, `SourceFile` should keep the original file length, and serialize it to dep-info file correctly.

### Meta

```
rustc 1.93.0-nightly (bd3ac0330 2025-11-01)
```

6d41834e251a65a994bf0acf415ddafd4adbf71f

Cargo issue: https://github.com/rust-lang/cargo/issues/16253

### PR DESCRIPTION
**Pull request by weihanglo**
Add `unnormalized_source_len` field to track the byte length
of source files before normalization (the original length).

`unnormalized_source_len` is for writing the correct file length
to dep-info for `-Zchecksum-hash-algorithm`

Fixes https://github.com/rust-lang/rust/issues/148934

### CODE REVIEW

File: compiler/rustc_span/src/lib.rs [hunk 1]
```diff
@@ -1765,6 +1768,7 @@ impl<S: SpanEncoder> Encodable<S> for SourceFile {
         self.checksum_hash.encode(s);
         // Do not encode `start_pos` as it's global state for this session.
         self.source_len.encode(s);
+        self.original_source_len.encode(s);
```
Comment (weihanglo) [inline compiler/rustc_span/src/lib.rs]: Not sure if this is really needed

File: compiler/rustc_interface/src/passes.rs [hunk 2]
```diff
@@ -596,7 +596,7 @@ fn write_out_deps(tcx: TyCtxt<'_>, outputs: &OutputFilenames, out_filenames: &[P
             .map(|fmap| {
                 (
                     escape_dep_filename(&fmap.name.prefer_local().to_string()),
-                    fmap.source_len.0 as u64,
+                    fmap.original_source_len as u64,
```
Comment (weihanglo) [inline compiler/rustc_interface/src/passes.rs]: This line is the goal of the entire PR

Comment (jieyouxu) [reply compiler/rustc_interface/src/passes.rs]: Suggestion: can you please add a comment to elaborate here for locality? That is,

`source_len` -> `original_source_len` is *very* subtle.

File: compiler/rustc_span/src/lib.rs [hunk 3]
```diff
@@ -1725,6 +1725,8 @@ pub struct SourceFile {
     pub start_pos: BytePos,
     /// The byte length of this source.
     pub source_len: RelativeBytePos,
+    /// The byte length of this source before normalization.
+    pub original_source_len: u32,
```
Comment (jieyouxu) [inline compiler/rustc_span/src/lib.rs]: Suggestion: I'm not sure how invasive the change is, but we can rename this pair of source lengths (better names welcome):

- `source_len` -> `normalized_source_len`
- `original_source_len` -> `unnormalized_source_len`

When reading this diff, I find that `source_len` vs `original_source_len` is really not obvious. I can appreciate if the diffs is intentionally made small to make review easier, but I would prefer if we also do a rename for the `source_len` field for consistency -- this is really not obvious.

File: compiler/rustc_span/src/lib.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_span/src/lib.rs]: I would say if the normalized source len is encoded, then unnormalized source len should also be encoded. I would imagine that if the source file changed, then well, it did materially change.

**Review by jieyouxu — COMMENTED** [review]
I'm not an expert in this part of the compiler, however the changes make sense to me. A few "cosmetic" nits.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148962/77761f314d7243da0fa3b6ca214eeecd51e956e0..00dcb1d399c7a0a347108a4129717b16f5437017)*

File: compiler/rustc_span/src/lib.rs (hunk 3 above)
Comment (weihanglo) [reply compiler/rustc_span/src/lib.rs]: Nice suggestion. Done in a separate commit.

File: compiler/rustc_interface/src/passes.rs (hunk 2 above)
Comment (weihanglo) [reply compiler/rustc_interface/src/passes.rs]: Added. Yeah it is clearer now.

**Comment by jieyouxu** [comment]
Fun. clippy is another josh subtree, so it's okay to change r-l/r side since we obviously need to change the compiler tree here.

**Comment by weihanglo** [comment]
At least Cargo doesn't have that, otherwise I'll need to do two more PRs 😬

**Review by jieyouxu — APPROVED** [review]
Thanks

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148962/f35a2bee641e88742b6de10b25c748ef57475f24..cf57b9b292a47a3f44e9c5dc56d0e24e8b07a10f)*
