### PR TITLE
get rid of some false negatives in rustdoc::broken_intra_doc_links

### LINKED ISSUE #54191: rustdoc does not warn about broken links if they contain `.` or `[]`
I got a PR yesterday that included something like this:

```rust
/// The tour de force of my career is [`foo.bar()`]
pub mod foo {
    pub fn bar() {}
}
```

In the current nightly rustdoc, `foo.bar()` neither resolves nor warns:

Our CI with `--deny warnings` did not catch this mistake (although I did 😄). I think rustdoc should trigger `intra-doc-link-resolution-failure` for this case.

### PR DESCRIPTION
**Pull request by lolbinarycat**
rustdoc will not try to do intra-doc linking if the "path" of a link looks too much like a "real url".

however, only inline links (`[text](url)`) can actually contain a url, other types of links (reference links, shortcut links) contain a *reference* which is later resolved to an actual url.

the "path" in this case cannot be a url, and therefore it should not be skipped due to looking like a url.

fixes https://github.com/rust-lang/rust/issues/54191

to minimize the number of false positives that will be introduced, the following heuristic is used:

If there's no backticks, be lenient revert to old behavior.
This is to prevent churn by linting on stuff that isn't meant to be a link.
only shortcut links have simple enough syntax that they
are likely to be written accidentlly, collapsed and reference links
need 4 metachars, and reference links will not usually use
backticks in the reference name.
therefore, only shortcut syntax gets the lenient behavior.
here's a truth table for how link kinds that cannot be urls are handled:

|              |  is shortcut link  | not shortcut link |
|--------------|--------------------|-------------------|
| has backtick |    never ignore    |    never ignore   |
| no backtick  | ignore if url-like |    never ignore   |

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -930,13 +930,18 @@ fn preprocess_link(
     ori_link: &MarkdownLink,
     dox: &str,
 ) -> Option<Result<PreprocessingInfo, PreprocessingError>> {
+    // certain link kinds cannot have their path be urls,
+    // so they should not be ignored, no matter how much they look like urls.
+    // e.g. [https://example.com/] is not a link to example.com.
+    let can_be_url = ori_link.kind == LinkType::Inline || ori_link.kind == LinkType::Autolink;
```
Comment (notriddle) [inline src/librustdoc/passes/collect_intra_doc_links.rs:936]:
```suggestion
    let can_be_url = ori_link.kind != LinkType::ShortcutUnknown &&
        ori_link.kind != LinkType::CollapsedUnknown &&
        ori_link.kind != LinkType::ReferenceUnknown;
```

File: tests/rustdoc-ui/bad-intra-doc.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+#![no_std]
+#![deny(rustdoc::broken_intra_doc_links)]
+
+// regression test for https://github.com/rust-lang/rust/issues/54191
+
+/// this is not a link to [`example.com`]
```
Comment (notriddle) [inline tests/rustdoc-ui/bad-intra-doc.rs:6]: These lines need [error annotations][]. Otherwise, they fail the test even though the stderr file matches.

[error annotations]: https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotation-examples

```suggestion
/// this is not a link to [`example.com`] //~ERROR unresolved link
```

**Review by notriddle — CHANGES_REQUESTED** [review]
This looks like a good idea, but I have found one problem. Consider a sample like this:

```markdown
//@ check-pass
#![no_std]
#![deny(rustdoc::broken_intra_doc_links)]

// regression test for https://github.com/rust-lang/rust/issues/54191
// false positives

//! This is not an intra-doc link: [`foobar`]
//!
//! [`foobar`]: /index.html
```

That test case fails, because it thinks `/index.html` is an intra-doc link. You're right that certain kinds of links aren't allowed to be URLs—that's the Unknown type links.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 1 above)
Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs:936]: ah, it seems like i underestimated the amount of preprocessing that is done before this point.  i was under the impression we were basically working with the raw event stream, before reference resolution, but ofc that's not right.

File: tests/rustdoc-ui/bad-intra-doc.rs [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+
+// regression test for https://github.com/rust-lang/rust/issues/54191
+
+/// this is not a link to [`example.com`] //~ERROR unresolved link
+///
+/// this link [`has spaces in it`].
+///
+/// attempted link to method: [`Foo.bar()`]
+///
+/// classic broken intra-doc link: [`Bar`]
```
Comment (notriddle) [inline tests/rustdoc-ui/bad-intra-doc.rs:12]: Sorry I didn't mention it, but these other lines also need error annotations on them.

**Comment by lolbinarycat** [comment]
welp, turns out the standard library itself contains several of these false negatives!

**Comment by lolbinarycat** [comment]
...or perhaps there's some deeper bug with intra-doc link generation?

there seems to be some false positives containing spaces, even though there is a matching reference definition...

I guess we can just re-enable unconditionally ignoring links with spaces?

**Comment by lolbinarycat** [comment]
Ok, this breaks a lot of ui tests.  This might actually have a pretty big impact, maybe we should do a crater run or something..?

**Comment by notriddle** [comment]
It's looks fine to me. Here's the PRs where each of these test cases were added:

| test case | PR |
|-|-|
| disambiguator-endswith-named-suffix.rs | https://github.com/rust-lang/rust/pull/127016
| weird-syntax.rs | https://github.com/rust-lang/rust/pull/112014
| redundant_explicit_links-utf8.rs | https://github.com/rust-lang/rust/pull/115070

The last two are both contrived ICE tests, and all of them are intended to be parsed as intra-doc links. Making it so that they warn seems fine to me.

r? @GuillaumeGomez do you also think this is a suitable bug fix?

**Comment by lolbinarycat** [comment]
@GuillaumeGomez what about just amending the current warning to account for other common mistakes?

honestly makes me wish we had `--explain` for lints, putting a full help message for each one could get a bit verbose.

regardless, i think that should be a separate issue, since the lint output isn't the most helpful in general (it just recommends escaping the brackets, and doesn't mention other common issues, such as misspelled link references)

**Comment by GuillaumeGomez** [comment]
> what about just amending the current warning to account for other common mistakes?

Do you have an example of before/after of what you have in mind by any chance?

**Comment by lolbinarycat** [comment]
> Do you have an example of before/after of what you have in mind by any chance?

well, the most obvious one is some sort of "consider adding a reference: `[whatever]: //some-url.example/`", but i also think trying to catch typos by comparing the edit distance of the missing reference to that of existing references could be handy.

and perhaps we should also mention surrounding code by backticks, since code snippets should generally be in `code blocks` instead of individually escaping chars.

**Comment by GuillaumeGomez** [comment]
> well, the most obvious one is some sort of "consider adding a reference: `[whatever]: //some-url.example/`", but i also think trying to catch typos by comparing the edit distance of the missing reference to that of existing references could be handy.

Sounds good to me. The distance between two items could be nice too (as a follow-up?).

**Comment by lolbinarycat** [comment]
opened https://github.com/rust-lang/rust/issues/132788 to track future improvements to this lint.

**Comment by lolbinarycat** [comment]
[This was discussed in the latest t-rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/channel/393423-t-rustdoc.2Fmeetings/topic/2025-03-10/near/504688417)

Consensus was we need some sort of additional heuristic to allow stuff like "[1, 2]" without escaping, but no consensus was reached as to what that heuristic should be.

**Comment by lolbinarycat** [comment]
This was discussed in [this month's t-rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/channel/393423-t-rustdoc.2Fmeetings/topic/2025-04-14/with/512166455), and the consensus was that reference-style intra-doc links should not be checked unless they are wrapped with backticks.

this means something like `` [`Type.method()`] `` will cause a lint to be emitted, but `[Type.method()]` will not.

**Comment by lolbinarycat** [comment]
I know @notriddle wanted to actually make the lints more generous in some cases, but the way this is currently implemented is that links that look like urls get completely ignored by the entire intra-doc link system, not just ignored by the lint.

so, the best I can do without significant overhauls is to revert to the previous buggy behavior if there are no backticks.

**Comment by lolbinarycat** [comment]
I'm quite happy with the current state of this, and think that the vast majority of new warnings created by it will be genuine mistakes.  Just waiting on code review now.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -979,7 +986,25 @@ fn preprocess_link(
...
+    //
+    // |-------------------------------------------------------|
+    // |              |  is shortcut link  | not shortcut link |
+    // |--------------|--------------------|-------------------|
+    // | has backtick |    never ignore    |    never ignore   |
+    // | no backtick  | ignore if url-like |    never ignore   |
+    // |-------------------------------------------------------|
+    let ignore_urllike =
+        can_be_url || (ori_link.kind == LinkType::ShortcutUnknown && !ori_link.link.contains('`'));
+    if ignore_urllike && should_ignore_link(path_str) {
```
Comment (notriddle) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1007]: It looks like the complete truth table is:

|              |  unknown shortcut link  | unknown reference / collapsed link |     other link     |
|--------------|-------------------------|------------------------------------|--------------------|
| has backtick |      never ignore       |            never ignore            | ignore if url-like |
| no backtick  |   ignore if url-like    |            never ignore            | ignore if url-like |

Assuming I'm understanding the logic correctly (the difference is to things like `[first](second)`).

Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1007]: That is correct.  Technically I do explicitly define the scope of the existing table with the line "here's a truth table for how **link kinds that cannot be urls** are handled:"

the line is currently 66 chars long, i should be able to fit in the other case without upsetting tidy (100 char limit), do you want me to?

**Review by notriddle — APPROVED** [review]

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 5]
```diff
@@ -931,13 +931,20 @@ fn preprocess_link(
     ori_link: &MarkdownLink,
     dox: &str,
 ) -> Option<Result<PreprocessingInfo, PreprocessingError>> {
+    // certain link kinds cannot have their path be urls,
+    // so they should not be ignored, no matter how much they look like urls.
+    // e.g. [https://example.com/] is not a link to example.com.
+    let can_be_url = ori_link.kind != LinkType::ShortcutUnknown
+        && ori_link.kind != LinkType::CollapsedUnknown
+        && ori_link.kind != LinkType::ReferenceUnknown;
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]:
```suggestion
    let can_be_url = !matches!(
        ori_link.kind,
        LinkType::ShortcutUnknown | LinkType::CollapsedUnknown | LinkType::ReferenceUnknown
    );
```

maybe?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 6]
```diff
@@ -979,7 +986,25 @@ fn preprocess_link(
         }
     };
 
-    if should_ignore_link(path_str) {
+    // If there's no backticks, be lenient revert to old behavior.
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]:
```suggestion
    // If there's no backticks, be lenient and revert to the old behavior.
```

I think?

**Review by fmease — COMMENTED** [review]
Could you please squash some of the micro/fixup commits? Thanks!

**Comment by fmease** [comment]
I think team consensus has now been reached on the poll (majority / two outstanding). Relabeled to `S-waiting-on-review` (but I've also left some minor nitpicks, didn't do a full review).

**Comment by lolbinarycat** [comment]
squashed and rebased

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Then let's go, thanks everyone!

@bors r+ rollup

**Comment by fmease** [comment]
https://github.com/rust-lang/rust/pull/144384#issuecomment-3111842112
@bors r-

**Comment by lolbinarycat** [comment]
~~weirdly the erroring code doesn't seem to exist in master or nightly source.~~

EDIT: nvm there's multiple comments referencing README.md in that file, i was looking at the wrong one.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
CI is happy so let's go!

@bors r+ rollup

**Comment by ojeda** [comment]
Did this land in 1.90 or 1.91? The rollup PR says 1.91, but this one says 1.90. I don't see it in the (current) beta branch. I guess it may have to do with the fact that it was merged right after the version bump. Thanks!
