### PR TITLE
Fix MIR lowering evaluation order and soundness bug

### LINKED ISSUE #65909: Built-in indexing doesn't ensure bounds checks stay valid
For example, the bounds check for `x[1]` in the following code is invalidated by the assignment in the next indexer.

```rust
fn modify_after_assert_slice_array(x: &[&[i32; 3]]) -> i32 {
    let mut x = x;
    let z = [1, 2, 3];
    let y = &[&z];
    // 1. checks `x[1]` is not out of bounds - OK `x.len() = 2`.
    // 2. modifies `x` so that `x == y`. Now `x.len() == 1`
    // 3. tries to read `x[1][2]` which is now out of bounds.
    x[1][{ x = y; 2}]
}
fn main() {
    println!("{}", modify_after_assert_slice_array(&[&[4, 5, 6], &[9, 10, 11]]));
}
```

### LINKED ISSUE #65910: Unexpected evaluation order of assignments
Assignment expressions where the right-hand side is a FRU or has a reborrow adjustment are not evaluated in the strict right to left order that they usually are. The following example should compile and the assertions shouldn't be triggered

```rust
fn evaluate_reborrow_before_assign() {
    let mut x = &1;
    let y = &mut &2;
    let z = &3;
    // There's an implicit reborrow of `x` on the right-hand side of the
    // assignement. Note that writing an explicit reborrow would not show this
    // bug, as now there would be two reborrows on the right-hand side and at
    // least one of them would happen before the left-hand side is evaluated.
    *{ x = z; &mut *y } = x;
    assert_eq!(*x, 3);
    assert_eq!(**y, 1);                    // 3 on stable
}

fn evaluate_fru_to_temp_before_assign_box() {
    let x = Box::new(S(0));
    let y = &mut S(1);
    *{ drop(x); &mut *y } = S { ..*x };    // error here on stable
    assert_eq!(0, y.0);
}

fn main() {
    evaluate_reborrow_before_assign();
    evaluate_fru_to_temp_before_assign_box();
}
```

### PR DESCRIPTION
**Pull request by matthewjasper**
* Fixes a soundness issue with built-in index operations
* Ensures correct evaluation order of assignment expressions where the RHS is a FRU or is a use of a local of reference type.
* Removes an unnecessary symbol to string conversion

closes #65909
closes #65910

### CODE REVIEW

File: src/librustc_mir/build/expr/as_place.rs [hunk 1]
```diff
@@ -309,4 +306,164 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+
+        let slice = place_builder.clone().into_place();
+        // bounds check:
+        let (len, lt) = (
+            self.temp(usize_ty.clone(), expr_span),
+            self.temp(bool_ty, expr_span),
+        );
+        self.cfg.push_assign(
+            block,
+            source_info, // len = len(slice)
```
Comment (Centril) [inline src/librustc_mir/build/expr/as_place.rs]: (Preexisting... but the placement of these comments suggests there's something special about `source_info` rather than what `.push_assign` is doing.)

File: src/librustc_mir/build/expr/as_place.rs [hunk 2]
```diff
@@ -309,4 +306,164 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+        let base_fake_borrow_temps = &mut Vec::new();
+        let is_outermost_index = fake_borrow_temps.is_none();
+        let fake_borrow_temps = fake_borrow_temps.unwrap_or(base_fake_borrow_temps);
+
+        let place_builder = unpack!(block = self.expr_as_place(
+                    block,
+                    lhs,
+                    mutability,
+                    Some(fake_borrow_temps),
+                ));
```
Comment (Centril) [inline src/librustc_mir/build/expr/as_place.rs]: Formatting got a tad off here.

File: src/librustc_mir/build/expr/as_place.rs [hunk 3]
```diff
@@ -309,4 +306,164 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                Operand::Copy(Place::from(idx)),
+                Operand::Copy(len.clone()),
+            ),
+        );
+
+        let msg = BoundsCheck {
+            len: Operand::Move(len),
+            index: Operand::Copy(Place::from(idx)),
+        };
+        let success = self.assert(block, Operand::Move(lt), true, msg, expr_span);
```
Comment (Centril) [inline src/librustc_mir/build/expr/as_place.rs]: Could we split the bounds check stuff from the fake-read stuff into two methods to make it clearer where each bit starts & ends?

File: src/librustc_mir/build/expr/as_place.rs [hunk 4]
```diff
@@ -309,4 +306,164 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+        } else {
+            let tcx = self.hir.tcx();
+            let place_ty = Place::ty_from(
+                &place_builder.base,
+                &place_builder.projection,
+                &self.local_decls,
+                tcx,
+            );
+            if let ty::Slice(_) = place_ty.ty.kind {
+                // We need to create fake borrows to ensure that we the bounds
```
Comment (Centril) [inline src/librustc_mir/build/expr/as_place.rs]:
```suggestion
                // We need to create fake borrows to ensure that the bounds
```

File: src/librustc_mir/build/expr/into.rs [hunk 5]
```diff
@@ -271,6 +272,100 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
             ExprKind::Use { source } => {
                 this.into(destination, block, source)
             }
+            ExprKind::Borrow { arg, borrow_kind } => {
+                // We don't do this in `as_rvalue` because we use `as_place`
+                // for borrow expressions, so we cannot create an RValue that
```
Comment (Centril) [inline src/librustc_mir/build/expr/into.rs]:
```suggestion
                // for borrow expressions, so we cannot create an `RValue` that
```

File: src/librustc_mir/build/expr/into.rs [hunk 6]
```diff
@@ -271,6 +272,100 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                // remains valid across user code. `as_rvalue` is usually called
+                // by this  method anyway, so this shouldn't cause too many
```
Comment (Centril) [inline src/librustc_mir/build/expr/into.rs]:
```suggestion
                // by this method anyway, so this shouldn't cause too many
```

File: src/librustc_mir/build/expr/as_place.rs [hunk 7]
```diff
@@ -309,4 +306,207 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                BinOp::Lt,
+                Operand::Copy(Place::from(index)),
+                Operand::Copy(len.clone()),
+            ),
+        );
+        let msg = BoundsCheck {
+            len: Operand::Move(len),
+            index: Operand::Copy(Place::from(index)),
+        };
+        // assert!(lt, "...")
```
Comment (Centril) [inline src/librustc_mir/build/expr/as_place.rs]:
```suggestion
        // assert!(lt, "...") -> bb_success
```

**Comment by matthewjasper** [comment]
Perf looks fine (almost no change). Does someone else want to review? cc @oli-obk @eddyb

**Comment by estebank** [comment]
cc @rust-lang/compiler just to make sure everyone sees it.

File: src/test/ui/borrowck/slice-index-bounds-check-invalidation.rs [hunk 8]
```diff
@@ -0,0 +1,63 @@
+// Test that we error if a slice is modified after it has been bounds checked
+// and before we actually index it.
+
+fn modify_before_assert_slice_slice(x: &[&[i32]]) -> i32 {
+    let mut x = x;
+    let z = [1, 2, 3];
+    let y = &[&z[..]];
```
Comment (pnkfelix) [inline src/test/ui/borrowck/slice-index-bounds-check-invalidation.rs]: I think some explicit types on the variables in these functions would help the reader understand and focus on the relevant differences between them. Right now I have to sort of infer it from the fn name.

File: src/test/ui/borrowck/slice-index-bounds-check-invalidation.rs [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+    let z = [1, 2, 3];
+    let y = &[&z];
+    x[1][{ x = y; 2}]               //~ ERROR cannot assign `x` in indexing expression
+}
+
+fn modify_after_assert_array_array(x: &[&[i32; 3]; 1]) -> i32 {
+    let mut x = x;
+    let z = [1, 2, 3];
+    let y = &[&z];
+    x[0][{ x = y; 2}]               // OK cannot invalidate a fixed-size array bounds check
```
Comment (pnkfelix) [inline src/test/ui/borrowck/slice-index-bounds-check-invalidation.rs]: you might as well add one more set of tests checking the case `x[0][{ x = y; 0 }][2]`, right? (As in, something where the problematic mutation doesn't happen in the last indexing expression, but rather in a middle one. At least my reading of this code is that we are planning to accept mutations of the base local in the first indexing expression, but generally you're not going to be able to mutate it in any of the indexing expressions beyond the first..)

**Comment by pnkfelix** [comment]
I've skimmed over the changes. I want another chance to go over them more carefully, especially 683d1133643451ad431be797c64c4b2d9c497de9 where it uses `into()` instead of `as_rvalue` for borrows and ... well, you say FRU, but its really for all struct-literal expressions, no?

**Comment by pnkfelix** [comment]
(also, are there separate issues filed for the bugs being fixed here? It might be useful to have a separate place to track that...)

**Comment by JohnCSimon** [comment]
Ping from triage.
@pnkfelix Can you please review this PR?
cc: @matthewjasper @Centril 

Thank you!

File: src/librustc_mir/build/expr/as_place.rs [hunk 10]
```diff
@@ -137,63 +151,40 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
             }
             ExprKind::Index { lhs, index } => {
-                let (usize_ty, bool_ty) = (this.hir.usize_ty(), this.hir.bool_ty());
-
-                let place_builder = unpack!(block = this.as_place_builder(block, lhs));
-                // Making this a *fresh* temporary also means we do not have to worry about
-                // the index changing later: Nothing will ever change this temporary.
-                // The "retagging" transformation (for Stacked Borrows) relies on this.
-                let idx = unpack!(block = this.as_temp(
+                this.lower_index_expression(
```
Comment (pnkfelix) [inline src/librustc_mir/build/expr/as_place.rs]: This commit contains a number of refactorings (such as the rewrite of the `match` expression above, and the out-of-lining of the expression into its own method here).

I like refactorings, and think these ones make sense, given the state of the code. 

But I also think my review would have been much easier (and perhaps would have had a quicker turn around time) if the refactorings were isolated into their own commit that was tagged as a refactoring with no expected semantic effect).

It’s not something that I’m going to demand of this Pull Request. It’s more of a note for the future: I think that isolating refactorings into their own commit(s) is a good habit for PR authors in general.

**Comment by pnkfelix** [comment]
Okay, I re-reviewed.

I thunk the code changes look fine.

I still want the test suite updated with the changes I noted in my earlier comments. r=me with that in place.

**Comment by matthewjasper** [comment]
I cannot reproduce the failure locally. I'm hoping that it's spurious

@bors retry rollup=never

**Comment by matthewjasper** [comment]
This appears to be a pre-existing bug. I've minimized the issue to the following this requires a rustc with llvm assertions enabled and I suspect all i686 toolchains are affected:

```rust
// Only breaks at opt-level=2 or higher.
#![crate_type="lib"]

pub fn check_overlap(ext: &i32) -> usize {
    let src_usize = &1 as *const _ as usize;
    let dst_usize = ext as *const _ as usize;
    let mut diff = src_usize.wrapping_sub(dst_usize);
    if src_usize > dst_usize {
        diff = diff.wrapping_neg();
    };

    diff
}
```

**Comment by matthewjasper** [comment]
I've pushed a work around and have opened #66315 for the CI failure.
