### PR TITLE
Fix regionck failure when converting Index to IndexMut

### LINKED ISSUE #74933: Lifetime error when indexing with borrowed index in beta but not in stable
I tried to compile this code:

```rust
use std::mem;
use std::ops::{Index, IndexMut};

pub struct FieldMap;

pub fn insert(this: &mut FieldMap, field: &Field<'_>, value: ()) -> () {
    this[field] = value;
}

pub struct Field<'a> {
    x: &'a (),
}

impl<'a> Index<&'a Field<'a>> for FieldMap {
    type Output = ();

    fn index(&self, _: &'a Field<'a>) -> &() {
        unimplemented!()
    }
}

impl<'a> IndexMut<&'a Field<'a>> for FieldMap {
    fn index_mut(&mut self, _: &'a Field<'a>) -> &mut () {
        unimplemented!()
    }
}
```
I expected the code to compile

Instead, it failed to compile with this lifetime error:

```
error[E0623]: lifetime mismatch
 --> src/lib.rs:7:5
  |
6 | pub fn insert(this: &mut FieldMap, field: &Field<'_>, value: ()) -> () {
  |                                           ----------
  |                                           |
  |                                           these two types are declared with different lifetimes...
7 |     this[field] = value;
  |     ^^^^^^^^^^^ ...but data from `field` flows into `field` here
```

### Workarounds

If I change the function in these ways it compiles.

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=ca6b8a2243d7116cb8180bb4300f6edc
```rust
pub fn insert<'a,'b,'c>(this: &'a mut FieldMap, field: &'b Field<'c>, value: ()) -> () {
    this[field as &'b Field<'b>] = value;
}
```

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=21326b3dcd6c017d0e644ef7eab89769
```rust
pub fn insert<'a,'b,'c>(this: &'a mut FieldMap, field: &'b Field<'c>, value: ()) -> () {
    *this.index_mut(field) = value;
}
```

### Meta

This **compiles successfully** on Stable Rust 1.45.0 back to 1.26.0 (when `'_` lifetimes were stabilized)

This **fails to compile** on these versions(haven't tried previous ones in the same channels):

- 1.46.0-beta.2 (2020-07-23 6f959902b3103c49ca98)
- 1.47.0-nightly (2020-07-28 a7eff79135de09a49b50)

This issue has been assigned to @nbdd0121 via [this comment](https://github.com/rust-lang/rust/issues/74933#issuecomment-666502305).

### PR DESCRIPTION
**Pull request by nbdd0121**
Fixes #74933

Consider an overloaded index expression `base[index]`. Without knowing whether it will be mutated, this will initially be desugared into `<U as Index<T>>::index(&base, index)` for some `U` and `T`. Let `V` be the `expr_ty_adjusted` of `index`.

If this expression ends up being used in any mutable context (or used in a function call with `&mut self` receiver before #72280), we will need to fix it up. The current code will rewrite it to `<U as IndexMut<V>>::index_mut(&mut base, index)`. In most cases this is fine as `V` will be equal to `T`, however this is not always true when `V/T` are references, as they may have different region.

This issue is quite subtle before #72280 as this code path is only used to fixup function receivers, but after #72280 we've made this a common path.

The solution is basically just rewrite it to `<U as IndexMut<T>>::index_mut(&mut base, index)`. `T` can retrieved in the fixup path using `node_substs`.

### CODE REVIEW

**Comment by nbdd0121** [comment]
Ideally we don't really want to do a re-infer and re-coerce because we could be able to re-use the result from immutable indexing, but somehow the existing code doesn't work...

File: src/librustc_typeck/check/place_op.rs [hunk 1]
```diff
@@ -246,15 +246,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
             match expr.kind {
                 hir::ExprKind::Index(ref base_expr, ref index_expr) => {
-                    // We need to get the final type in case dereferences were needed for the trait
-                    // to apply (#72002).
-                    let index_expr_ty = self.typeck_results.borrow().expr_ty_adjusted(index_expr);
```
Comment (nbdd0121) [inline src/librustc_typeck/check/place_op.rs:251]: Ok, I narrowed down the issue to this line. This will cause the actual type (and lifetime) of index expression to be used, rather than a supertype of it.

Comment (nbdd0121) [reply src/librustc_typeck/check/place_op.rs:251]: I am not sure if there is a way to retrieve the input_ty in try_index_step. If we could we could just use it as index_expr_ty.

File: src/test/ui/issues/issue-41742.rs [hunk 2]
```diff
@@ -21,5 +21,7 @@ impl IndexMut<u32> for H {
 }
 
 fn main() {
-    H["?"].f(); //~ ERROR mismatched types
+    H["?"].f();
+    //~^ ERROR mismatched types
+    //~| ERROR mismatched types
```
Comment (estebank) [inline src/test/ui/issues/issue-41742.rs:26]: It'd be nice to not cause this duplication of errors, but that's less important than the regression.

Instead of `demand_coerce` you could use `demand_coerce_diag` to be able to `map_err` it and `.delay_span_bug()` it. I _think_ that would be enough, but we should probably not include that in a backport.

Comment (nbdd0121) [reply src/test/ui/issues/issue-41742.rs:26]: I am currently seeking a way not to do any demand_coerce at all. If that's not possible (or would be too complex), I'll update the PR to use demand_coerce_diag.

**Comment by nbdd0121** [comment]
@nikomatsakis have you had time to go through this? The issue it fixes is P-critical and regression-from-stable-to-beta, so we'd need to address it asap and backport to beta.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

sorry. I don't 100% understand what went wrong, but this fix seems god.

**Comment by Mark-Simulacrum** [comment]
beta-nominating as a fix for for a stable-to-beta regression.

**Comment by spastorino** [comment]
Adding `T-compiler` label so this can be picked up by our automated prioritization tool and added to the following `T-compiler` weekly meeting agenda.

**Comment by spastorino** [comment]
[discussed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-08-13.20.2354818/near/206820527) in T-compiler meeting.

@rustbot modify labels: beta-accepted
