### PR TITLE
Do not emit E0277 on incorrect tuple destructured binding

### LINKED ISSUE #50333: False/Irrelevant Error E0277
On type mismatchses when using trait objects, rust emits error E0277, saying that the trait does not have a constant size known at compile-time, and that all local variables must have a statically known type. In fact, the problem lies elsewhere, and the program can be fixed without addressing the E0277 error at all.

I wrote this code:

```
trait T {}

struct A;
impl T for A {}
impl A {
    fn new() -> Self {
        Self {}
    }
}

fn main() {
    let (a, b, c) = (A::new(), A::new()); // This tuple is 2 elements, should be three
    let ts: Vec<&T> = vec![&a, &b, &c];
    println!("{}", ts.len());
}
```
The marked tuple has 2 `A::new()` copies, when it should have 3. If this is fixed, the code compiles. I would expect to see a single error pointing out this fact. Instead, four errors are returned:
```
   Compiling bug v0.1.0 (file:///home/isaac/prog/rust/bug)
error[E0308]: mismatched types
  --> src/main.rs:12:9
   |
12 |     let (a, b, c) = (A::new(), A::new());
   |         ^^^^^^^^^ expected a tuple with 2 elements, found one with 3 elements
   |
   = note: expected type `(A, A)`
              found type `(_, _, _)`

error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
  --> src/main.rs:12:10
   |
12 |     let (a, b, c) = (A::new(), A::new());
   |          ^ `T` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `T`
   = note: all local variables must have a statically known size

error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
  --> src/main.rs:12:13
   |
12 |     let (a, b, c) = (A::new(), A::new());
   |             ^ `T` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `T`
   = note: all local variables must have a statically known size

error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
  --> src/main.rs:12:16
   |
12 |     let (a, b, c) = (A::new(), A::new());
   |                ^ `T` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `T`
   = note: all local variables must have a statically known size

error: aborting due to 4 previous errors

error: Could not compile `bug`.
```
Only the first of these errors is related to the bug - the other three are all false and/or irrelevant.

## Meta

`rustc --version --verbose`:

rustc 1.25.0 (84203cac6 2018-03-25)
binary: rustc
commit-hash: 84203cac67e65ca8640b8392348411098c856985
commit-date: 2018-03-25
host: x86_64-unknown-linux-gnu
release: 1.25.0
LLVM version: 6.0

Also produced on nightly 1.27.0

### PR DESCRIPTION
**Pull request by estebank**
Fix #50333.

### CODE REVIEW

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -299,10 +299,19 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                 self.demand_eqtype(pat.span, expected, pat_ty);
-                for (i, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
-                    self.check_pat_walk(elem, &element_tys[i], def_bm, true);
+                if self.has_errors.get() {
+                    let element_tys_iter = (0..max_len).map(|_| tcx.types.err);
+                    let element_tys = tcx.mk_type_list(element_tys_iter);
+                    for (_, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
+                        self.check_pat_walk(elem, &tcx.types.err, def_bm, true);
+                    }
+                    tcx.mk_ty(ty::TyTuple(element_tys))
```
Comment (eddyb) [inline src/librustc_typeck/check/_match.rs]: Can this use `tcx.mk_tup` or something instead? It seems a bit too complex.

File: src/librustc/ty/relate.rs [hunk 2]
```diff
@@ -407,13 +407,10 @@ pub fn super_relate_tys<'a, 'gcx, 'tcx, R>(relation: &mut R,
...
-                                                       |relation| {
-                                                           relation.relate_with_variance(
-                                                               ty::Contravariant,
-                                                               a_region,
-                                                               b_region)
-                                                       })?;
+            let region_bound = relation.with_cause(
+                Cause::ExistentialRegionBound,
+                |relation| relation.relate_with_variance(ty::Contravariant, a_region, b_region),
+            )?;
```
Comment (eddyb) [inline src/librustc/ty/relate.rs]: Is this just a drive-by formatting change? I'd prefer if it wasn't included, it feels confusing.

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: Fair enough. Will change.

File: src/librustc/ty/relate.rs (hunk 2 above)
Comment (estebank) [reply src/librustc/ty/relate.rs]: Yes. If I recall correctly I was looking if I _needed_ to modify that file while exploring for a solution and left that small cleanup in because it was small enough, but I can revert it.

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: I'm just not sure how extensive the effects of `enumerate_and_adjust` and `check_pat_walk` are.

I'll try to get a compile with simplified logic, but will keep it as a separate commit in case it causes uncaught regressions.

File: src/librustc_typeck/check/_match.rs [hunk 3]
```diff
@@ -299,10 +299,18 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                 let element_tys = tcx.mk_type_list(element_tys_iter);
                 let pat_ty = tcx.mk_ty(ty::TyTuple(element_tys));
                 self.demand_eqtype(pat.span, expected, pat_ty);
-                for (i, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
-                    self.check_pat_walk(elem, &element_tys[i], def_bm, true);
+                if self.has_errors.get() {
+                    let element_tys_iter = (0..max_len).map(|_| tcx.types.err);
+                    for (_, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
+                        self.check_pat_walk(elem, &tcx.types.err, def_bm, true);
+                    }
```
Comment (estebank) [inline src/librustc_typeck/check/_match.rs]: This above is needed to properly elide the E0277 errors.

**Comment by estebank** [comment]
@eddyb ping.

**Comment by pietroalbini** [comment]
Ping from triage @eddyb! This PR needs your review.

**Comment by TimNN** [comment]
Ping from triage @eddyb / @rust-lang/compiler: This PR requires your review.

**Comment by eddyb** [comment]
Please do not assign me diagnostics PRs. r? @nikomatsakis

File: src/librustc_typeck/check/_match.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: done

File: src/librustc_typeck/check/_match.rs [hunk 4]
```diff
@@ -298,11 +298,19 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                 let element_tys = tcx.mk_type_list(element_tys_iter);
                 let pat_ty = tcx.mk_ty(ty::Tuple(element_tys));
-                self.demand_eqtype(pat.span, expected, pat_ty);
-                for (i, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
-                    self.check_pat_walk(elem, &element_tys[i], def_bm, true);
+                if let Some(mut err) = self.demand_eqtype_diag(pat.span, expected, pat_ty) {
+                    err.emit();
+                    let element_tys_iter = (0..max_len).map(|_| tcx.types.err);
+                    for (_, elem) in elements.iter().enumerate_and_adjust(max_len, ddpos) {
+                        self.check_pat_walk(elem, &tcx.types.err, def_bm, true);
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: I'd like a comment somewhere here saying:

---

```
// Walk subpatterns with an expected type of `err` in this case
```

**Review by nikomatsakis — APPROVED** [review]
r=me with a comment
