### PR TITLE
Prefer to suggest stable candidates rather than unstable ones

### LINKED ISSUE #140240: rustc does not suggest importing the old `Range` type
### Code

```Rust
const _: Range = 0..1;
```

### Current output

```
error[E0412]: cannot find type `Range` in this scope
 --> <anon>:1:10
  |
1 | const _: Range = 0..1;
  |          ^^^^^ not found in this scope
  |
help: consider importing one of these structs
  |
1 + use std::collections::btree_map::Range;
  |
1 + use std::collections::btree_set::Range;
  |
1 + use std::range::Range;
  |
1 + use std::range::legacy::Range;
  |

error: aborting due to 1 previous error
```

### Desired output

```
error[E0412]: cannot find type `Range` in this scope
 --> <anon>:1:10
  |
1 | const _: Range = 0..1;
  |          ^^^^^ not found in this scope
  |
help: consider importing one of these structs
  |
1 + use std::ops::Range;
  |
1 + use std::collections::btree_map::Range;
  |
1 + use std::collections::btree_set::Range;
  |
1 + use std::range::Range;
  |

error: aborting due to 1 previous error
```

### Rationale and extra context

It should suggests importing the stable `ops::Range`; and ideally should points that `range::Range` is unstable, and not suggest `legacy::Range` (a unstable pub reexport of a stable type) as the reexported type is available.

I.e. importing one of those types will yield an error:
```
error[E0658]: use of unstable library feature `new_range_api`
 --> <anon>:1:5
  |
1 | use std::range::Range;
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #125687 <https://github.com/rust-lang/rust/issues/125687> for more information

error[E0658]: use of unstable library feature `new_range_api`
 --> <anon>:2:5
  |
2 | use std::range::legacy::Range;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #125687 <https://github.com/rust-lang/rust/issues/125687> for more information
```

### Rust Version

```Shell
$ rustc -Vv
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-unknown-linux-gnu
release: 1.86.0
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #140240

The logic is to replace unstable suggestions if we meet a new stable one, and do nothing if any other situation. In old logic, we just use the first candidate we meet as the suggestion for the same items.

E.g., `std::range::legacy::Range` vs `std::ops::Range`, `legacy` in the former is unstable, we prefer to suggest use the latter.

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1258,6 +1263,16 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
                         candidates.remove(idx);
                     }
 
+                    let is_stable =
+                        is_stable && did.is_some() && this.is_stable(did.unwrap(), path.span);
+                    if is_stable
+                        && let Some(idx) = candidates
+                            .iter()
+                            .position(|v: &ImportSuggestion| v.did == did && !v.is_stable)
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1271]: I don't understand the logic here, what does this condition check - an unstable reexport of a stable item? Could you add a comment?
Also, there may be several such reexports, they should probably all be removed.
Also, the PR description doesn't really match this logic.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/diagnostics.rs:1279]: > 1. yes, it removes unstable ones if exist. e.g., `std::range::legacy::Range` vs `std::ops::Range`, `legacy` in the former is unstable, we prefer to suggest `use` the latter. And only do this check if current one is stable
> 2. there could only be one cause same items will only be inserted once, see [line 1284](https://github.com/rust-lang/rust/pull/140795/files#diff-0e459b4cbb41dd93274d7c68b18a2a3eab7152e9aea107839a7bddff0b4e9195R1284)
> 3. so the logic is to replace unstable suggestions if we meet a new stable one, and do nothing if any other situation, I think it matches the PR description. But I'm not a native English speaker, so maybe you have a better suggestion? ;)

An explanation like this is exactly what I'd expect to seen in the PR desctiption and code comments.
