### PR TITLE
generalize: handle occurs check failure in aliases

### LINKED ISSUE #105787: occurs check with aliases results in error, not ambiguity
*edit: this issue has been partially fixed in #117088, so any remaining incompleteness (and therefore incorrectly accepted overflow) is a lot harder to trigger. See https://github.com/rust-lang/trait-system-refactor-initiative/issues/8 for a list of known issues with generalization. Keeping this issue open as is to track this, but we should try to write a test which relies on one of the other problems of that issue, now that the problem case 2 has been fixed.*

---
```rust
// Using the higher ranked projection hack to prevent us from replacing the projection
// with an inference variable.
trait ToUnit<'a> {
    type Unit;
}

struct LocalTy;
impl<'a> ToUnit<'a> for *const LocalTy {
    type Unit = ();
}

impl<'a, T: Copy + ?Sized> ToUnit<'a> for *const T {
    type Unit = ();
}

trait Overlap<T> {
    type Assoc;
}

type Assoc<'a, T> = <*const T as ToUnit<'a>>::Unit;

impl<T> Overlap<T> for T {
    type Assoc = usize;
}

impl<T> Overlap<for<'a> fn(&'a (), Assoc<'a, T>)> for T
where
    for<'a> *const T: ToUnit<'a>,
{
    type Assoc = Box<usize>;
}

fn foo<T: Overlap<U>, U>(x: T::Assoc) -> T::Assoc {
    x
}

fn main() {
    foo::<for<'a> fn(&'a (), ()), for<'a> fn(&'a (), ())>(3usize);
}
```

`for<'a> fn(&'a (), ())>: Overlap<for<'a> fn(&'a (), ())>>` can be satisfied using both impls, ignoring a deficiency of the current normalization routine which means that right now the second impl pretty much never applies.

Currently inference constraints from equating the self type are not used to normalize the trait argument so we fail when equating `()` with `Assoc<'a, for<'a> fn(&'a (), ())>` even those these two are the same type. This will change once deferred projection equality is implemented.

## why this currently passes coherence

Coherence does a pairwise check for all relevant impls. It starts by instantiating the impl parameters with inference vars and equating the impl headers. When we do that with `Overlap<T> for T` and `Overlap<for<'a> fn(&'a (), Assoc<'a, T>)> for T` we have:

- `eq(?0: Overflap<?0>, ?1: Overlap<for<'a> fn(&'a (), <*const ?1 as ToUnit<'a>>::Unit)>)`
    - `eq(?0, ?1)` constrains `?1` to be equal to `?0`
    - `eq(?0, for<'a> fn(&'a (), <*const ?0 as ToUnit<'a>>::Unit)>)`: this now fails the occurs check

The occurs check is necessary to prevent ourselves from creating infinitely large types, e.g. `?0 = Vec<?0>`. But it does mean that coherence considers these two impls to be disjoint. Because the inference var only occurs inside of a projection, there's a way to equate these two types without resulting in an infinitely large type by normalizing the projection.

### PR DESCRIPTION
**Pull request by lcnr**
mostly fixes #105787, except for the `for<'a> fn(<<?x as OtherTrait>::Assoc as Trait<'a>>::Assoc) eq ?x` case in https://github.com/rust-lang/trait-system-refactor-initiative/issues/8.

r? @compiler-errors

### CODE REVIEW

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 1]
```diff
@@ -139,6 +153,12 @@ struct Generalizer<'me, 'tcx, D> {
 
     cache: SsoHashMap<Ty<'tcx>, Ty<'tcx>>,
 
+    /// This is set once we're generalizing the arguments of an alias. In case
+    /// we encounter an occurs check failure we generalize the alias to an
+    /// inference variable instead of erroring. This is necessary to avoid
+    /// incorrect errors when relating `?0` with `<?0 as Trait>::Assoc`.
+    in_alias: bool,
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs:160]: exists because of `<() as Trait<<?0 as Trait<()>>::Assoc>>::Assoc == ?0` have to update comment. With `Projection` goals the behavior is still broken, but I want to change it to emit `alias-relate` in the new solver in a different PR, at which point this should work.

File: compiler/rustc_infer/src/infer/generalize.rs [hunk 2]
```diff
@@ -309,6 +329,38 @@ where
...
+                            return Err(e);
+                        } else {
+                            let mut visitor = MaxUniverse::new();
+                            t.visit_with(&mut visitor);
+                            let infer_replacement_is_complete =
+                                self.for_universe.can_name(visitor.max_universe())
+                                    && !t.has_escaping_bound_vars();
+                            if !infer_replacement_is_complete {
+                                warn!("incomplete generalization of an alias type: {t:?}");
+                            }
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/generalize.rs:347]: handling this correctly is HARD. We'd have to push the infer var to the place which introduced the binder and then have a nested `Equate` goal or sth.

idk how to handle this during coherence, ideally just succeed with equating and emit an `Ambiguity` predicate?

File: compiler/rustc_infer/src/infer/nll_relate/mod.rs [hunk 3]
```diff
@@ -217,13 +217,18 @@ where
...
             self.infcx,
             &mut self.delegate,
             ty,
             for_vid,
             self.ambient_variance,
         )?;
+
+        let ty = value.may_be_infer();
+        if ty.is_ty_var() {
+            span_bug!(self.delegate.span(), "occurs check failure in MIR typeck");
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/nll_relate/mod.rs:230]: potentially reachable with user type annotations? Probably not as the actual type inferred by HIR typeck also needs to contain an inference variable? :thinking:

Comment (lcnr) [inline compiler/rustc_infer/src/infer/nll_relate/mod.rs:230]: potentially reachable with user type annotations? Probably not as the actual type inferred by HIR typeck also needs to contain an inference variable? :thinking:

File: compiler/rustc_infer/src/infer/combine.rs [hunk 4]
```diff
@@ -477,19 +481,47 @@ impl<'infcx, 'tcx> CombineFields<'infcx, 'tcx> {
...
+                // The old solver only accepts projection predicates for associated types.
+                match kind {
+                    ty::AliasKind::Projection => {}
+                    ty::AliasKind::Inherent | ty::AliasKind::Weak | ty::AliasKind::Opaque => {
+                        return Err(TypeError::CyclicTy(a_ty));
+                    }
+                }
             }
-        }?;
+            self.obligations.push(Obligation::new(
```
[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_infer/src/infer/combine.rs:504]: added a fixme

**Comment by lcnr** [comment]
@rustbot author

This PR mostly fixes generalization for aliases, fixing #105787. Equating `?x == Alias<?x>` previously failed. This is *incomplete* (and therefore allows overlaps via the implicit negative overlap check in coherence).

This PR instead delays equality in this case, emitting a `Projection` goal. This projection goal then stalls until the projection can be normalized to a rigid type, in which case the occurs check is correct, or the projection cannot be normalized and stays rigid (due to a `ParamEnv` candidate).

It is non-trivial whether we can get trait solver overflow (in the old solver) for rigid projections, e.g.
```rust
trait Unnormalizable<T> {
    type Assoc;
}

struct Inv<T>(*mut T);

fn unconstrained<T>() -> T {
    todo!()
}

fn create<T, U: Unnormalizable<T>>(
    x: &U,
) -> (Inv<T>, Inv<<U as Unnormalizable<T>>::Assoc>) {
    todo!()
}

fn foo<T: Unnormalizable<U> + Unnormalizable<V>, U, V>() {
    let q = unconstrained();
    let (mut x, y) = create::<_, _>(&q);
    x = y; // equate `?x` with `<T as Unnormalizable<?x>>::Assoc`
    drop::<T>(q);
}
```
However, projection goals only constrain the term to the projection itself if we were able to select a `ParamEnv` candidate. As we do not have non-lifetime binders, this only happens if the projection does not contain type inference variables.

You can get solver overflow with specialization, but idc :grin:

This does not fix all issues of https://github.com/rust-lang/trait-system-refactor-initiative/issues/8, however, fixing

**Comment by lcnr** [comment]
should have done perf + crater :sweat: 

@bors try @rust-timer queue

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-117088/retry-regressed-list.txt p=1

**Comment by lcnr** [comment]
coolio :3

## background

When relating an inference variable with another type we first *generalize* the type and then instantiate the inference variable with the resulting type. E.g. `?0 <: Vec<&'a ()>` first generalizes to `Vec<&'new ()>` and then instantiate `?0` with `Vec<&'new ()>`.

If we encounter a type variable itself while generalizing, e.g. `?0 <: Vec<?0>`, we fail to relate, as this would result in an infinite/cyclic type. This is called the "occurs check".

This is correct for *rigid* types, but for *aliases* this can result in incorrect errors: `?0 == <?0 as IntoIterator>::IntoIter` could hold, e.g. by constraining `?0` to `std::iter::Once<()>`. Due to eager normalization and because we replace associated types with inference variables if there is still ambiguity, this only affects associated types containing bound variables and opaque types with the old solver. In the new solver we do not eager normalize, so this issue is a lot more prevalent there.

As this is incomplete, this can result in overlapping impls passing coherence: #105787

## changes in this PR

When we get and occurs check failure while generalizing an alias type, we do not error but instead emit a delayed `Projection` obligation. This does not completely resolve all the ways generalization is incomplete, but handles the only relevant one :3 see https://github.com/rust-lang/trait-system-refactor-initiative/issues/8 for a full list of known issues with generalization, this only fully fixes the second case.

See the affected changes to see the impact of this PR.

@rfcbot fcp merge

File: tests/ui/coherence/occurs-check/opaques.rs [hunk 5]
```diff
@@ -0,0 +1,37 @@
+//revisions: old next
+//[next] compile-flags: -Ztrait-solver=next
+
+// A regression test for #105787
+
+//[old] known-bug: #105787
```
Comment (lcnr) [inline tests/ui/coherence/occurs-check/opaques.rs:6]: we do not emit projection obligations for opaque types because the old solver does not support them :grin: so this is still an issue in the old solver.

**Comment by jackh726** [comment]
@rfcbot reviewed

I am a tad wary about this, since this doesn't feel very "formalized" and I'd rather have this proven out in a-mir-formality, but I'm not going to block this PR.

**Comment by compiler-errors** [comment]
@bors r+

approver is wrong
