### PR TITLE
Remove overlapping parts of multipart suggestions

### LINKED ISSUE #106870: [ICE]: 'attempt to add with overflow', compiler/rustc_errors/src/emitter.rs:2229:17
### Code

```Rust
#![warn(explicit_outlives_requirements)]

macro_rules! tuple_impls {
    ($($name:ident)+) => {
        struct TupleInPlaceVisitor<'a, $($name: 'a,)+>(&'a ($($name,)+));
    }
}

mod ok {
    tuple_impls!(T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11);
}

mod ice {
    tuple_impls!(T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12);
}
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [ ] Current Nightly

### Rust Version

```Shell
master at c0b87359599629d69a7b37318088dac3a5d67c9c with debug assertions
```

### Current error output

```Shell
warning: struct `TupleInPlaceVisitor` is never constructed
  --> src/lib.rs:5:16
   |
5  |         struct TupleInPlaceVisitor<'a, $($name: 'a,)+>(&'a ($($name,)+));
   |                ^^^^^^^^^^^^^^^^^^^
...
10 |     tuple_impls!(T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11);
   |     --------------------------------------------------- in this macro invocation
   |
   = note: `#[warn(dead_code)]` on by default
   = note: this warning originates in the macro `tuple_impls` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: struct `TupleInPlaceVisitor` is never constructed
  --> src/lib.rs:5:16
   |
5  |         struct TupleInPlaceVisitor<'a, $($name: 'a,)+>(&'a ($($name,)+));
   |                ^^^^^^^^^^^^^^^^^^^
...
14 |     tuple_impls!(T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12);
   |     ------------------------------------------------------- in this macro invocation
   |
   = note: this warning originates in the macro `tuple_impls` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: outlives requirements can be inferred
  --> src/lib.rs:5:47
   |
5  |         struct TupleInPlaceVisitor<'a, $($name: 'a,)+>(&'a ($($name,)+));
   |                                               ^^^^
...
10 |     tuple_impls!(T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11);
   |     ---------------------------------------------------
   |     |
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |     in this macro invocation
   |
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![warn(explicit_outlives_requirements)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this warning originates in the macro `tuple_impls` (in Nightly builds, run with -Z macro-backtrace for more info)
help: remove these bounds
   |
5  -         struct TupleInPlaceVisitor<'a, $($name: 'a,)+>(&'a ($($name,)+));
5  +         struct TupleInPlaceVisitor<'a, $($name,)+>(&'a ($($name,)+));
   |
```

### Backtrace

```Shell
thread 'rustc' panicked at 'attempt to add with overflow', compiler/rustc_errors/src/emitter.rs:2225:17
stack backtrace:
   0:     0x7f20546d8cb1 - std::backtrace_rs::backtrace::libunwind::trace::h26056f81198c6594
                               at /home/lukas/code/rust/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f20546d8cb1 - std::backtrace_rs::backtrace::trace_unsynchronized::hacfb345a0c6d5bb1
                               at /home/lukas/code/rust/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f20546d8cb1 - std::sys_common::backtrace::_print_fmt::h18ea6016ac8030f3
                               at /home/lukas/code/rust/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f20546d8cb1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he35dde201d0c2d09
                               at /home/lukas/code/rust/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f205475d408 - core::fmt::write::h094ad263467a053c
                               at /home/lukas/code/rust/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f20546f9a91 - std::io::Write::write_fmt::hd47b4e2324b4d9b7
                               at /home/lukas/code/rust/library/std/src/io/mod.rs:1682:15
   6:     0x7f20546d8ada - std::sys_common::backtrace::_print::h43044162653a17fc
                               at /home/lukas/code/rust/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f20546d8ada - std::sys_common::backtrace::print::hc8605da258fa5aeb
                               at /home/lukas/code/rust/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f20546bcb27 - std::panicking::default_hook::{{closure}}::h9e37f23f75122a15
   9:     0x7f20546bc91b - std::panicking::default_hook::h602873a063f84da2
                               at /home/lukas/code/rust/library/std/src/panicking.rs:286:9
  10:     0x7f205514ce22 - <alloc[48d7b30605060536]::boxed::Box<dyn for<'a, 'b> core[672e3947e150d6c6]::ops::function::Fn<(&'a core[672e3947e150d6c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[672e3947e150d6c6]::marker::Send + core[672e3947e150d6c6]::marker::Sync> as core[672e3947e150d6c6]::ops::function::Fn<(&core[672e3947e150d6c6]::panic::panic_info::PanicInfo,)>>::call
                               at /home/lukas/code/rust/library/alloc/src/boxed.rs:2002:9
  11:     0x7f205514ce22 - rustc_driver[71f9db948e3cbeef]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_driver/src/lib.rs:1206:17
  12:     0x7f20546bd073 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfd13333ca953ae8e
                               at /home/lukas/code/rust/library/alloc/src/boxed.rs:2002:9
  13:     0x7f20546bd073 - std::panicking::rust_panic_with_hook::h45753e10264ebe7e
                               at /home/lukas/code/rust/library/std/src/panicking.rs:692:13
  14:     0x7f20546ec642 - std::panicking::begin_panic_handler::{{closure}}::h86b4a87cc250f655
                               at /home/lukas/code/rust/library/std/src/panicking.rs:577:13
  15:     0x7f20546ec5bc - std::sys_common::backtrace::__rust_end_short_backtrace::h4b5bc8ce158972b4
                               at /home/lukas/code/rust/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f20546bcbfa - rust_begin_unwind
                               at /home/lukas/code/rust/library/std/src/panicking.rs:575:5
  17:     0x7f2054695723 - core::panicking::panic_fmt::h195b27650e929019
                               at /home/lukas/code/rust/library/core/src/panicking.rs:64:14
  18:     0x7f20546957bd - core::panicking::panic::heaf5758f188e8c47
                               at /home/lukas/code/rust/library/core/src/panicking.rs:114:5
  19:     0x7f2057cc16ec - <rustc_errors[9304c724dce24edb]::emitter::EmitterWriter>::draw_code_line
  20:     0x7f2057ccceca - <rustc_errors[9304c724dce24edb]::emitter::EmitterWriter>::emit_suggestion_default
                               at /home/lukas/code/rust/compiler/rustc_errors/src/emitter.rs:1940:17
  21:     0x7f2057ccceca - <rustc_errors[9304c724dce24edb]::emitter::EmitterWriter>::emit_messages_default
                               at /home/lukas/code/rust/compiler/rustc_errors/src/emitter.rs:2131:48
  22:     0x7f2057cbfa16 - <rustc_errors[9304c724dce24edb]::emitter::EmitterWriter as rustc_errors[9304c724dce24edb]::emitter::Emitter>::emit_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_errors/src/emitter.rs:552:9
  23:     0x7f2057ca9e98 - <rustc_errors[9304c724dce24edb]::json::Diagnostic>::from_errors_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_errors/src/json.rs:353:9
  24:     0x7f2057ca8e6c - <rustc_errors[9304c724dce24edb]::json::JsonEmitter as rustc_errors[9304c724dce24edb]::emitter::Emitter>::emit_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_errors/src/json.rs:146:20
  25:     0x7f2057caf8e9 - <rustc_errors[9304c724dce24edb]::HandlerInner>::emit_diagnostic::{closure#2}
                               at /home/lukas/code/rust/compiler/rustc_errors/src/lib.rs:1364:17
  26:     0x7f205525e1f4 - rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_interface/src/callbacks.rs:41:54
  27:     0x7f205525e1f4 - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:50
  28:     0x7f205525e1f4 - rustc_middle[586537f4649200b8]::ty::context::tls::set_tlv::<rustc_middle[586537f4649200b8]::ty::context::tls::enter_context<rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1278:9
  29:     0x7f205525e1f4 - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:9
  30:     0x7f205525e1f4 - rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_interface/src/callbacks.rs:41:20
  31:     0x7f205525e1f4 - rustc_middle[586537f4649200b8]::ty::context::tls::with_context_opt::<rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:22
  32:     0x7f205525e1f4 - rustc_interface[11dfff37d5dfca39]::callbacks::track_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_interface/src/callbacks.rs:31:5
  33:     0x7f2057caeda1 - <rustc_errors[9304c724dce24edb]::HandlerInner>::emit_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_errors/src/lib.rs:1333:9
  34:     0x7f2057cadd1b - <rustc_errors[9304c724dce24edb]::Handler>::emit_diagnostic
                               at /home/lukas/code/rust/compiler/rustc_errors/src/lib.rs:1109:9
  35:     0x7f20574dfd75 - <rustc_errors[9304c724dce24edb]::diagnostic_builder::DiagnosticBuilder<()>>::emit
                               at /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic_builder.rs:452:9
  36:     0x7f20574dfd75 - rustc_middle[586537f4649200b8]::lint::struct_lint_level::struct_lint_level_impl::<rustc_error_messages[ce04712ea088a0b7]::DiagnosticMessage>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/lint.rs:459:9
  37:     0x7f20574d85cf - rustc_middle[586537f4649200b8]::lint::struct_lint_level::<rustc_error_messages[ce04712ea088a0b7]::DiagnosticMessage, <rustc_lint[5a54672088725f7b]::context::LateContext as rustc_lint[5a54672088725f7b]::context::LintContext>::emit_spanned_lint<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_lint[5a54672088725f7b]::lints::BuiltinExplicitOutlives>::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/lint.rs:461:5
  38:     0x7f20574b3514 - <rustc_middle[586537f4649200b8]::ty::context::TyCtxt>::struct_span_lint_hir::<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_error_messages[ce04712ea088a0b7]::DiagnosticMessage, <rustc_lint[5a54672088725f7b]::context::LateContext as rustc_lint[5a54672088725f7b]::context::LintContext>::emit_spanned_lint<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_lint[5a54672088725f7b]::lints::BuiltinExplicitOutlives>::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:2246:9
  39:     0x7f2057501a01 - <rustc_lint[5a54672088725f7b]::context::LateContext as rustc_lint[5a54672088725f7b]::context::LintContext>::lookup::<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_error_messages[ce04712ea088a0b7]::DiagnosticMessage, <rustc_lint[5a54672088725f7b]::context::LateContext as rustc_lint[5a54672088725f7b]::context::LintContext>::emit_spanned_lint<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_lint[5a54672088725f7b]::lints::BuiltinExplicitOutlives>::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/context.rs:1028:24
  40:     0x7f2057501a01 - <rustc_lint[5a54672088725f7b]::context::LateContext as rustc_lint[5a54672088725f7b]::context::LintContext>::emit_spanned_lint::<alloc[48d7b30605060536]::vec::Vec<rustc_span[ecc2679795d1e63]::span_encoding::Span>, rustc_lint[5a54672088725f7b]::lints::BuiltinExplicitOutlives>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/context.rs:912:9
  41:     0x7f205751c552 - <rustc_lint[5a54672088725f7b]::builtin::ExplicitOutlivesRequirements as rustc_lint[5a54672088725f7b]::passes::LateLintPass>::check_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/builtin.rs:2226:17
  42:     0x7f20574bed98 - <rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass as rustc_lint[5a54672088725f7b]::passes::LateLintPass>::check_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/passes.rs:93:13
  43:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:136:17
  44:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>>::with_param_env::<<rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_item::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:76:9
  45:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_item::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:135:13
  46:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>>::with_lint_attrs::<<rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_item::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:63:9
  47:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_item
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:134:9
  48:     0x7f205753ef9f - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass> as rustc_hir[8f7f0d2cc2801874]::intravisit::Visitor>::visit_nested_item
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:238:13
  49:     0x7f205752ca0c - rustc_hir[8f7f0d2cc2801874]::intravisit::walk_mod::<rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>>
                               at /home/lukas/code/rust/compiler/rustc_hir/src/intravisit.rs:557:9
  50:     0x7f205754440b - <rustc_lint[5a54672088725f7b]::late::LateContextAndPass<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>>::process_mod
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:82:9
  51:     0x7f205754440b - rustc_lint[5a54672088725f7b]::late::late_lint_mod_inner::<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:375:5
  52:     0x7f205754440b - rustc_lint[5a54672088725f7b]::late::late_lint_mod::<rustc_lint[5a54672088725f7b]::BuiltinCombinedModuleLateLintPass>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:358:9
  53:     0x7f20574bab2d - rustc_lint[5a54672088725f7b]::lint_mod
                               at /home/lukas/code/rust/compiler/rustc_lint/src/lib.rs:130:5
  54:     0x7f205683e3c5 - <rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:340:53
  55:     0x7f205683e3c5 - <rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps::<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:58:46
  56:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:50
  57:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::set_tlv::<rustc_middle[586537f4649200b8]::ty::context::tls::enter_context<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1278:9
  58:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:9
  59:     0x7f205683e3c5 - <rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps::<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:58:13
  60:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::with_context::<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1322:40
  61:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::with_context_opt::<rustc_middle[586537f4649200b8]::ty::context::tls::with_context<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:22
  62:     0x7f205683e3c5 - rustc_middle[586537f4649200b8]::ty::context::tls::with_context::<<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1322:9
  63:     0x7f205683e3c5 - <rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind as rustc_query_system[4faceeb05e078dd9]::dep_graph::DepKind>::with_deps::<<rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>::{closure#0}, ()>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/dep_graph/mod.rs:55:9
  64:     0x7f2056a292f2 - <rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task_impl::<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:340:22
  65:     0x7f2056a292f2 - <rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepGraph<rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[586537f4649200b8]::ty::context::TyCtxt, rustc_span[ecc2679795d1e63]::def_id::LocalDefId, ()>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:290:13
  66:     0x7f2056bc419e - rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job::<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:470:13
  67:     0x7f2056bc419e - stacker[d7498c3020ab29d6]::maybe_grow::<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  68:     0x7f2056bc419e - rustc_data_structures[c725bc8c2e090b34]::stack::ensure_sufficient_stack::<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  69:     0x7f2056bc419e - <rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query::<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:128:17
  70:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:50
  71:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::set_tlv::<rustc_middle[586537f4649200b8]::ty::context::tls::enter_context<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1278:9
  72:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::enter_context::<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1294:9
  73:     0x7f2056bc419e - <rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query::<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:127:13
  74:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::with_related_context::<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1338:13
  75:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::with_context::<rustc_middle[586537f4649200b8]::ty::context::tls::with_related_context<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1322:40
  76:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::with_context_opt::<rustc_middle[586537f4649200b8]::ty::context::tls::with_context<rustc_middle[586537f4649200b8]::ty::context::tls::with_related_context<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1311:22
  77:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::with_context::<rustc_middle[586537f4649200b8]::ty::context::tls::with_related_context<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1322:9
  78:     0x7f2056bc419e - rustc_middle[586537f4649200b8]::ty::context::tls::with_related_context::<<rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>::{closure#0}, ((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex)>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/ty/context.rs:1335:9
  79:     0x7f2056bc419e - <rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt as rustc_query_system[4faceeb05e078dd9]::query::QueryContext>::start_query::<((), rustc_query_system[4faceeb05e078dd9]::dep_graph::graph::DepNodeIndex), rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>::{closure#3}>
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:112:9
  80:     0x7f2056bc419e - rustc_query_system[4faceeb05e078dd9]::query::plumbing::execute_job::<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:458:9
  81:     0x7f2056bc419e - rustc_query_system[4faceeb05e078dd9]::query::plumbing::try_execute_query::<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:378:17
  82:     0x7f2056c685f0 - rustc_query_system[4faceeb05e078dd9]::query::plumbing::get_query::<rustc_query_impl[b9ea0aabf8fe1f88]::queries::lint_mod, rustc_query_impl[b9ea0aabf8fe1f88]::plumbing::QueryCtxt, rustc_middle[586537f4649200b8]::dep_graph::dep_node::DepKind>
                               at /home/lukas/code/rust/compiler/rustc_query_system/src/query/plumbing.rs:750:36
  83:     0x7f20569b93d5 - <rustc_query_impl[b9ea0aabf8fe1f88]::Queries as rustc_middle[586537f4649200b8]::ty::query::QueryEngine>::lint_mod::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/plumbing.rs:727:17
  84:     0x7f20569b93d5 - <rustc_query_impl[b9ea0aabf8fe1f88]::Queries as rustc_middle[586537f4649200b8]::ty::query::QueryEngine>::lint_mod
                               at /home/lukas/code/rust/compiler/rustc_query_impl/src/lib.rs:44:1
  85:     0x7f205525e9a6 - std[3330b4673efabfce]::panicking::try::do_call::<core[672e3947e150d6c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/lukas/code/rust/library/std/src/panicking.rs:483:40
  86:     0x7f205525e9a6 - std[3330b4673efabfce]::panicking::try::<(), core[672e3947e150d6c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
                               at /home/lukas/code/rust/library/std/src/panicking.rs:447:19
  87:     0x7f205529a715 - std[3330b4673efabfce]::panic::catch_unwind::<core[672e3947e150d6c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/lukas/code/rust/library/std/src/panic.rs:140:14
  88:     0x7f205529a715 - rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in::<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/sync.rs:152:33
  89:     0x7f205529a715 - <core[672e3947e150d6c6]::slice::iter::Iter<rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId> as core[672e3947e150d6c6]::iter::traits::iterator::Iterator>::for_each::<rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/lukas/code/rust/library/core/src/slice/iter/macros.rs:211:21
  90:     0x7f205529a715 - rustc_data_structures[c725bc8c2e090b34]::sync::par_for_each_in::<&[rustc_hir[8f7f0d2cc2801874]::hir_id::OwnerId], <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/sync.rs:151:13
  91:     0x7f20551fc15d - <rustc_middle[586537f4649200b8]::hir::map::Map>::par_for_each_module::<rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_middle/src/hir/map/mod.rs:651:9
  92:     0x7f20551fc15d - rustc_lint[5a54672088725f7b]::late::check_crate::<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:445:17
  93:     0x7f20551fc15d - <rustc_data_structures[c725bc8c2e090b34]::profiling::VerboseTimingGuard>::run::<(), rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/profiling.rs:723:9
  94:     0x7f20551fc15d - <rustc_session[1fdb0a5262a221b]::session::Session>::time::<(), rustc_lint[5a54672088725f7b]::late::check_crate<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_session/src/utils.rs:10:9
  95:     0x7f20551fc250 - rustc_lint[5a54672088725f7b]::late::check_crate::<rustc_lint[5a54672088725f7b]::BuiltinCombinedLateLintPass, rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_lint/src/late.rs:435:5
  96:     0x7f20551fc250 - rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}
                               at /home/lukas/code/rust/compiler/rustc_interface/src/passes.rs:963:29
  97:     0x7f20551fc250 - <rustc_data_structures[c725bc8c2e090b34]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_data_structures/src/profiling.rs:723:9
  98:     0x7f20551fc250 - <rustc_session[1fdb0a5262a221b]::session::Session>::time::<(), rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
                               at /home/lukas/code/rust/compiler/rustc_session/src/utils.rs:10:9
  99:     0x7f205525ea55 - rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2}
                               at /home/lukas/code/rust/compiler/rustc_interface/src/passes.rs:962:25
 100:     0x7f205525ea55 - <rustc_interface[11dfff37d5dfca39]::passes::analysis::{closure#5}::{closure#1}::{closure#2} as core[672e3947e150d6c6]::ops::function::FnOnce<()>>::call_once
                               at /home/lukas/code/rust/library/core/src/ops/function.rs:250:5
-- SNIP --

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [lint_mod] linting module `ice`
#1 [analysis] running analysis passes on this crate
end of query stack
```

### Anything else?

@rustbot label requires-debug-assertions

overflows here: https://github.com/rust-lang/rust/blob/4b51adf6ffa1ae2286ea436eb48cbaa8771886e6/compiler/rustc_errors/src/lib.rs#L325-L328

related: https://github.com/rust-lang/rust/issues/106044

### PR DESCRIPTION
**Pull request by lukas-code**
This PR adds a debug assertion that the parts of a single substitution cannot overlap, fixes a overlapping substitution from the testsuite, and fixes https://github.com/rust-lang/rust/issues/106870.

Note that a single suggestion can still have multiple overlapping substitutions / possible edits, we just don't suggest overlapping replacements in a single edit anymore.

I've also included a fix for an unrelated bug where rustfix for `explicit_outlives_requirements` would produce multiple trailing commas for a where clause.

### CODE REVIEW

File: compiler/rustc_errors/src/diagnostic.rs [hunk 1]
```diff
@@ -630,18 +630,27 @@ impl Diagnostic {
...
+                !part_outer.span.is_empty() || !part_outer.snippet.is_empty(),
+                "Span must not be empty and have no suggestion",
+            );
+            for part_inner in parts.iter().skip(index + 1) {
+                debug_assert!(
+                    !part_outer.span.overlaps(part_inner.span),
+                    "suggestion must not have overlapping parts:\n{part_outer:?}\n{part_inner:?}",
+                );
+            }
+        }
```
Comment (WaffleLapkin) [inline compiler/rustc_errors/src/diagnostic.rs:650]: Does it make sense to sort parts by the `span`? this way you only need to check the two adjacent ones. But, we shouldn't do this just for the debug assertions maybe...

Either way, I think it would be better to enclose this in `if cfg!(debug_assertions) {}`, so llvm has an easier time removing the useless loops.

Also, can we somehow test this assertion?

Comment (estebank) [reply compiler/rustc_errors/src/diagnostic.rs:650]: I think it is perfectly safe to always unconditionally sort here.

Comment (estebank) [inline compiler/rustc_errors/src/diagnostic.rs:650]: After sorting suggestion:

```suggestion
        let mut parts = parts.iter.peekable();
        while let Some(part) = parts.next() {
            debug_assert!(
                !partspan.is_empty() || !part.snippet.is_empty(),
                "Span must not be empty and have no suggestion",
            );
            let Some(next) = parts.peek() else { break; }
            debug_assert!(
                !part.span.overlaps(next.span),
                "suggestion must not have overlapping parts:\n{part:?}\n{next:?}",
            );
        }
```

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 2]
```diff
@@ -224,12 +223,25 @@ fn expand_macro<'cx>(
...
+            if tts.len() == rhs.tts.len() {
                 tts = tts.map_enumerated(|i, tt| {
                     let mut tt = tt.clone();
-                    let mut sp = rhs_spans[i];
-                    sp = sp.with_ctxt(tt.span().ctxt());
-                    tt.set_span(sp);
+                    let rhs_tt = &rhs.tts[i];
+                    let ctxt = tt.span().ctxt();
+                    match (&mut tt, rhs_tt) {
+                        // preserve the delim spans if able
```
Comment (estebank) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:232]: Nice

**Comment by estebank** [comment]
r=me after addressing the sorting/assertion nitpick

File: compiler/rustc_errors/src/diagnostic.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_errors/src/diagnostic.rs:650]: I think this can be written nicer with `parts.array_windows()`. Something like
```rust
debug_assert!(parts.iter().all(|part| !part.span.is_empty() || !part.snipper.is_empty()), "Span must not be empty and have no suggestion");
parts.array_windows(|[a, b]| debug_assert!(!a.span.overlaps(b.span), "suggestion must not have overlapping parts:\n{a:?}\n{b:?}"));
```

**Comment by lukas-code** [comment]
For the record, this is how this assertion looks now:
```text
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some([SubstitutionPart { span: /home/lukas/code/rust/tests/ui/parser/issues/issue-44406.rs:3:12: 3:24 (#4), snippet: " { " }, SubstitutionPart { span: /home/lukas/code/rust/tests/ui/parser/issues/issue-44406.rs:3:12: 3:24 (#4), snippet: " }" }])`: suggestion must not have overlapping parts', /home/lukas/code/rust/compiler/rustc_errors/src/diagnostic.rs:646:9
```

**Comment by matthiaskrgr** [comment]
Might break clippy tests

**Comment by WaffleLapkin** [comment]
It does look like it breaks clippy tests (diff from #107020):
```diff
-error: variables can be used directly in the `format!` string
-   |
-   |
-LL |     println!("{0} {0}", local_i32);
-   |
-help: change this to
-   |
-   |
-LL -     println!("{0} {0}", local_i32);
-LL +     println!("{local_i32} {local_i32}");
+thread 'rustc' panicked at 'assertion failed: `(left == right)`
+  left: `None`,
+  left: `None`,
+ right: `Some([SubstitutionPart { span: $DIR/uninlined_format_args.rs:78:23: 78:34 (#0), snippet: "" }, SubstitutionPart { span: $DIR/uninlined_format_args.rs:78:23: 78:34 (#0), snippet: "" }])`: suggestion must not have overlapping parts', /checkout/compiler/rustc_errors/src/diagnostic.rs:646:9
```

Not sure why clippy removes the same span twice though 🤔

**Comment by lukas-code** [comment]
I fixed the clippy failure and also changed the signature of `multipart_suggestion_*` to take `impl IntoIterator` instead of `Vec`, because I didn't like the `.into_iter().collect().into_iter().collect()`. I hope this doesn't affect compile time too much.

@rustbot ready

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 3]
```diff
@@ -825,7 +825,8 @@ fn check_object_unsafe_self_trait_by_name(tcx: TyCtxt<'_>, item: &hir::TraitItem
         if tcx.object_safety_violations(trait_def_id).is_empty() {
             return;
         }
-        let sugg = trait_should_be_self.iter().map(|span| (*span, "Self".to_string())).collect();
+        let sugg =
+            trait_should_be_self.iter().map(|span| (*span, "Self".to_string())).collect::<Vec<_>>();
```
Comment (WaffleLapkin) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:829]: Wouldn't it make more sense to remove the collect altogether?

File: compiler/rustc_lint/src/builtin.rs [hunk 4]
```diff
@@ -2223,6 +2241,8 @@ impl<'tcx> LateLintPass<'tcx> for ExplicitOutlivesRequirements {
                     Applicability::MaybeIncorrect
                 };
 
+                let lint_spans = lint_spans.into_iter().collect::<Vec<_>>();
+
                 cx.emit_spanned_lint(
                     EXPLICIT_OUTLIVES_REQUIREMENTS,
                     lint_spans.clone(),
```
Comment (WaffleLapkin) [inline compiler/rustc_lint/src/builtin.rs:2248]: Remove `collect`? also the clone seems unnecessary? Can't this just be 
```suggestion
                cx.emit_spanned_lint(
                    EXPLICIT_OUTLIVES_REQUIREMENTS,
                    lint_spans,
```

File: compiler/rustc_errors/src/diagnostic.rs [hunk 5]
```diff
@@ -625,23 +625,31 @@ impl Diagnostic {
...
         );
 
         self.push_suggestion(CodeSuggestion {
-            substitutions: vec![Substitution {
-                parts: suggestion
-                    .into_iter()
-                    .map(|(span, snippet)| SubstitutionPart { snippet, span })
-                    .collect(),
-            }],
+            substitutions: vec![Substitution { parts }],
```
Comment (WaffleLapkin) [inline compiler/rustc_errors/src/diagnostic.rs:652]: 💭  would small vec be good here?

**Review by WaffleLapkin — COMMENTED** [review]
Generally it's better to make smaller PR and separate refactorings, but this looks good overall, except for a couple of nitpicks.

**Comment by WaffleLapkin** [comment]
@bors try @rust-timer queue
Let's see if additional generics made the compiler compilation slower.

File: compiler/rustc_lint/src/builtin.rs (hunk 4 above)
Comment (lukas-code) [reply compiler/rustc_lint/src/builtin.rs:2248]: The clone is necessary, because we need one vector for the `MultiSpan` of the lint itself and one for the suggestion.

The collect is turning the `HashSet` into a `Vec` for the `MultiSpan`. But it would probably be better to just sort and dedup a vector instead of using a hash set, will change that.

**Comment by WaffleLapkin** [comment]
I assume you've removed the generic changes, so let's see what perf says @bors try @rust-timer queue

**Comment by lukas-code** [comment]
Regression is from the improvements in https://github.com/rust-lang/rust/pull/107343#issuecomment-1406299672, so probably noise.

**Comment by WaffleLapkin** [comment]
@lukas-code do you still have the commit/diff of making diagnostic functions accept `impl Interator`? I would like to experiment with this a bit

**Comment by lukas-code** [comment]
@WaffleLapkin I pulled this out of my reflog: 36d99530e2758c0099102bb9ae8e5d5cbc0bff2b https://github.com/lukas-code/rust/tree/multipart-impl-iterator

**Comment by WaffleLapkin** [comment]
@lukas-code thanks!
