### PR TITLE
fix: use git-commit-info for version information

### LINKED ISSUE #33286: A `rustc` compiled from the `rust-*-src` tarballs can't be used with the `std` binaries from s.r-l.o/dist
Originally reported [here](https://www.reddit.com/r/rust/comments/4h2ir3/the_crate_std_has_been_compiled_with_rustc_180/)

In the reported case the `rust` package provided by Arch Linux was compiled from [the `rustc-1.8.0-src.tar.gz` tarball](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rust#n14). Thus their `rustc` binary doesn't have a git commit hash encoded in it:

```
$ rustc -V
rust-1.8.0
```

And if you try to use this `rustc` to cross compile using the `std` binaries from [s.r-l.o](https://static.rust-lang.org/dist/) you get the following error:

```
$ cargo build --target=i686-pc-windows-gnu`
error: the crate `std` has been compiled with rustc 1.8.0 (db2939409 2016-04-11), which is incompatible with this version of rustc [E0514]
```

At the center of this issue is [this check](https://github.com/rust-lang/rust/blob/db2939409db26ab4904372c82492cd3488e4c44e/src/librustc_metadata/creader.rs#L261), this [rustc_version](https://github.com/rust-lang/rust/blob/db2939409db26ab4904372c82492cd3488e4c44e/src/librustc_metadata/common.rs#L245-L250) function and this [CFG_VERSION](https://github.com/rust-lang/rust/blob/master/mk/main.mk#L85) env variable which is set by the build system.

In the case of the `std` crate since it was compiled from a git checkout the value returned by `rustc_version` is `1.8.0 ($SOME_HASH $SOME_DATE)` whereas the same function just returns `1.8.0` in the case of a `rustc` that was compiled from a source tarball. The mismatch between these two strings is what causes the error reported above. But the error message is wrong because both binaries where compiled from the exact same source code and can be used together.

How to fix this? Possible solutions:
- Ask package maintaners to always build from a git checkout. This way the "rustc_version" string always contains a git commit hash.
- Tweak our build system so that building from a git checkout and from a source tarball yield the same "rustc_version" string. Two possible implementations:
  - Drop the commit hash/date part from the "rustc_version" string. This may be OK for the stable and beta channels because you can tell them apart from looking at the version number (e.g. 1.7.0 vs 1.8.0) but that's not the case for nightlies -- two consecutive nightlies would have the same version number (e.g. 1.10.0-nightly).
  - Include the commit hash part in the `rustc-*-src.tar.gz` tarballs, perhaps as a `.commit-hash` file and tweak the build system to use the contents of this file in the "rustc_version" string when one is not building from a git checkout.

Thoughts? @alexcrichton @brson

### LINKED ISSUE #86587: rustc has incomplete version information when compiling from source
When building from released sources (`https://static.rust-lang.org/dist/rustc-<version>-src.tar.xz`), the resulting rustc binary is missing detailed version information like commit hash and commit date.

Looking at the source it seems to only rely on git commands/paths to assemble this information (`https://github.com/rust-lang/rust/blob/5a7834050f3a0ebcd117b4ddf0bc1e8459594309/src/bootstrap/channel.rs#L26-L36`), but it could also be obtained/parsed from `rustc-<version>-src/version` when compiling from the released source files (and `rustc-<version>-src/git-commit-hash` if the entire commit hash is required too).

As far as I know this affects all rust releases that are not obtained via rustup (i.e. packaged by distributions or built from scratch).

Sample output of `rustc -vV`:
```
rustc 1.51.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-gnu
release: 1.51.0
LLVM version: 11.0.0
```

### PR DESCRIPTION
**Pull request by whispersofthedawn**
Fixes #33286.
Fixes #86587.

This PR changes the current `git-commit-hash` file that `./x.py` dist puts in the `rustc-{version}-src.tar.{x,g}z` to contain the hash, the short hash, and the commit date from which the tarball was created, assuming git was available when it was. It uses this for reading the version so that rustc has all the appropriate metadata.

# Testing

Testing this is kind of a pain. I did it with something like
```sh
./x.py dist # ensure that `ignore-git` is `false` in config.toml
cp ./build/dist/rustc-1.65.0-dev-src.tar.gz ../rustc-1.65.0-dev-src.tar.gz
cd .. && tar -xzf rustc-1.65.0-dev-src && cd rustc-1.65.0-dev-src
./x.py build
```

Then, the output of  `rustc -vV` with the stage1 compiler should have the `commit-hash` and `commit-date` fields filled, rather than be `unknown`. To be completely sure, you can use `rustc --sysroot` with the stdlib that the original `./x.py dist` made, which will require that the metadata matches.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, so my initial thought here is that we should probably still embed *some* indication that the rustc isn't actually being built from that git commit, since otherwise it'll be pretty confusing when a distro patch accidentally or intentionally changes behavior (even just in terms of what can link together successfully).

Can you say more about what motivates this? It looks like based on the fixed issues largely to be a case of using srlo std binaries with a distro rustc, but that feels like a pretty odd use case to me (why not just use rustup entirely at that point), and I'm wary that adding rudimentary support is enough to get people into trouble later. At the very least I'd like to know more about the desire and think about it.

**Comment by dawnofmidnight** [comment]
Hello. I do agree that using an srlo binary just for std would indeed be strange and uncommon (probably why that first issue has been open for such a long time). I do think, however, that it's better to have more complete version information for binaries compiled from the tarballs. I suppose that that could be harmful if the tarball was changed and someone assumed it was the same as the actual commit, though. Perhaps jyn514 has some other thoughts on that as well.

> Hm, so my initial thought here is that we should probably still embed some indication that the rustc isn't actually being built from that git commit

How do you think this could look, if this was done? I do agree that that's probably a good thing to have in there.

**Comment by jyn514** [comment]
> > Hm, so my initial thought here is that we should probably still embed some indication that the rustc isn't actually being built from that git commit

> How do you think this could look, if this was done? I do agree that that's probably a good thing to have in there, but I'm not sure how.

We could put this in --version --verbose maybe. I think in practice this will not be a giant deal; if distros are applying in patches, they should already be using `rust.description`.

> Can you say more about what motivates this? It looks like based on the fixed issues largely to be a case of using srlo std binaries with a distro rustc, but that feels like a pretty odd use case to me (why not just use rustup entirely at that point), and I'm wary that adding rudimentary support is enough to get people into trouble later.

"We shouldn't arbitrarily limit what people can compile". If the people build from source without patches, that's effectively the same compiler we distribute on static.rlo and there's no reason to prevent people from using it with the precompiled artifacts.

That said, I agree it's pretty strange to want to do this - would love to hear from @japaric or @Zapeth why they wanted this feature originally. (I still think it's very useful to embed the commit metadata *somehow* even if we don't guarantee metadata compatibility, though.)

**Comment by Mark-Simulacrum** [comment]
I think a reasonable compromise would be to set rust.description to include "tarball", by default, with a comment recommending how to avoid git-commit-hash being populated if building with patches. If we have that there I think that's enough for most of my concerns to be addressed.

Even building from source without patches is a little on the questionable side (e.g., there's going to be divergence in performance due to lack of PGO and other opts we run). I think building std from source is something I'm less worried about (ultimately required for many use cases and we intend to officially support that in the future), but re-compiling rustc and then loading std from srlo seems odd.

**Comment by dawnofmidnight** [comment]
@jyn514 I'm a little confused, what exactly do you mean by `rust.{version, description}`? Do you mean setting something like this: https://github.com/dawnofmidnight/rust/blob/tarball-commit-info/src/bootstrap/config.rs#L181? If so, would that show up in `rustc -vV`? Sorry, I'm not too familiar with boostrap and how it interacts with rustc.

**Comment by jyn514** [comment]
@dawnofmidnight yes, those fields in config.toml are exactly what I mean :) you can read their documentation in config.toml.example. Both show up in --version iirc, which means they also affect whether metadata can be reused between compilers.

**Comment by dawnofmidnight** [comment]
> Both show up in --version iirc, which means they also affect whether metadata can be reused between compilers.

Got it, thank you. I guess I'll append something like ` Built from a source tarball.` to the description.

**Comment by dawnofmidnight** [comment]
I've got a local branch that makes `rustc -V` look like
```
rustc 1.65.0-dev (a785176 2022-08-22) (built from a source tarball)
```
Does that look okay? I'll get it pushed once I figure out these git issues.

**Comment by jyn514** [comment]
@dawnofmidnight yes, that looks fine :) thanks!

**Comment by dawnofmidnight** [comment]
Okay, I *think* I've gotten everything figured out wrt git rebasing, but please let me know if there's something I messed up.

**Comment by dawnofmidnight** [comment]
...it appears not. That error doesn't seem to exist locally, strangely. I'll try again and make sure everything is fine.

**Comment by dawnofmidnight** [comment]
That wasn't supposed to happen. Maybe I screwed something up while rebasing.

File: src/bootstrap/config.rs [hunk 1]
```diff
@@ -1277,11 +1277,21 @@ impl Config {
...
+            channel.arg("show").arg(format!("{}:src/ci/channel", commit));
+            let channel = output(&mut channel);
+            channel.trim().to_owned()
+        } else if let Ok(channel) = fs::read_to_string(builder.src.join("src/ci/channel")) {
+            channel.trim().to_owned()
+        } else {
+            let src = builder.src.display();
+            eprintln!("error: failed to determine artifact channel");
+            eprintln!("help: either use git or ensure that {src}/src/ci/channel");
+            eprintln!("help: contains the name of the channel to use");
```
Comment (jyn514) [inline src/bootstrap/config.rs:1292]: nit: this can be a single line I think
```suggestion
            eprintln!("help: either use git or ensure that `{src}/src/ci/channel` contains the name of the channel to use");
```

File: src/bootstrap/dist.rs [hunk 2]
```diff
@@ -894,8 +894,16 @@ impl Step for PlainSourceTarball {
 
         // Create the version file
         builder.create(&plain_dst_src.join("version"), &builder.rust_version());
-        if let Some(sha) = builder.rust_sha() {
-            builder.create(&plain_dst_src.join("git-commit-hash"), &sha);
+        // If there is information for one of them, then there must be
+        // information for the rest, too.
```
Comment (jyn514) [inline src/bootstrap/dist.rs:898]: won't block on this, but would be nice to avoid the unwraps here
```suggestion
        // If there is information for one of them, then there must be
        // information for the rest, too.
        // TODO: put this in a single `Option` so we don't have to use `unwrap()`
```

File: src/bootstrap/lib.rs [hunk 3]
```diff
@@ -463,6 +463,14 @@ impl Build {
             bootstrap_out
         };
 
+        if !rust_info.is_git() {
+            config.description = if let Some(description) = config.description {
+                Some(format!("{description}, built from a source tarball"))
```
Comment (jyn514) [inline src/bootstrap/lib.rs:468]: hmm, I'm not sure this is the right behavior here. My understanding of Mark's suggestion in https://github.com/rust-lang/rust/pull/100557#issuecomment-1214874860 was:
1. If we're building from git sources, leave `description` blank by default
2. If we're building from a tarball, make `description` default to `built from a source tarball`, but allow it to be overriden
3. Add a comment to `config.toml.example` recommending that you turn off `git-commit-hash` handling when applying patches, and saying you can explicitly set `description` to an empty string so you can opt-in to using pre-compiled libstd binaries from static.rlo if you want to.

If we don't allow overriding the description in 2, then we don't actually solve https://github.com/rust-lang/rust/issues/33286 because the version will still differ from the official binaries.
```suggestion
                Some(format!("{description}"))
```

**Review by jyn514 — CHANGES_REQUESTED** [review]
You should be able to undo the cargo changes by running `git checkout HEAD~2 src/tools/cargo && git commit --amend`.

This looks mostly right to me, but I think we're no longer solving the original issue; I left a review comment.

File: src/bootstrap/channel.rs [hunk 4]
```diff
@@ -13,7 +14,10 @@ use crate::Build;
 
 pub enum GitInfo {
     /// This is not a git repository.
-    Absent,
+    ///
+    /// If `git-commit-info` can be used for commit information, this is `Some`;
+    /// otherwise, it is `None`.
+    Absent(Option<Info>),
```
[the remark this answers is not in the document]
Comment (dawnofmidnight) [reply src/bootstrap/channel.rs:20]: Hmm, could you explain the naming behind this? This is only used when it's within a tarball, so "for tarball" doesn't seem right. I'll make the change to another variant, though.

File: src/bootstrap/dist.rs (hunk 2 above)
Comment (dawnofmidnight) [reply src/bootstrap/dist.rs:898]: Perhaps instead of making the `rust_sha_short` and `rust_commit_date` methods in [lib.rs#L1336-L1344](https://github.com/dawnofmidnight/rust/blob/tarball-commit-info/src/bootstrap/lib.rs#L1336-L1344), we could just expose the inner `Option<&Info>` from [channel.rs#L90-L95](https://github.com/dawnofmidnight/rust/blob/tarball-commit-info/src/bootstrap/channel.rs#L90-L95)?

File: src/bootstrap/channel.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/bootstrap/channel.rs:20]: > This is only used when it's within a tarball, so "for tarball" doesn't seem right.

Can you explain that to me? :sweat: I think it should be "for tarball" exactly because it's in a tarball.

That said, I don't care much about the exact name, as long as it's a different variant that's fine.

File: src/bootstrap/dist.rs (hunk 2 above)
Comment (jyn514) [reply src/bootstrap/dist.rs:898]: :+1: making `Info` public seems fine to me

File: src/bootstrap/lib.rs (hunk 3 above)
Comment (dawnofmidnight) [reply src/bootstrap/lib.rs:468]: > Add a comment to config.toml.example recommending that you turn off git-commit-hash handling when applying patches, and saying you can explicitly set description to an empty string so you can opt-in to using pre-compiled libstd binaries from static.rlo if you want to.

I've made a comment doing the second locally, but how would you turn of `git-commit-info` handling? I don't think this has an option for that right now.

**Comment by bjorn3** [comment]
Could you please revert the change to the src/tools/cargo submodule?

File: src/bootstrap/lib.rs (hunk 3 above)
Comment (jyn514) [reply src/bootstrap/lib.rs:468]: That's what I meant by this second step:
> If we're building from a tarball, make description default to built from a source tarball, but allow it to be overriden

We need to make it possible for people to turn off the handling; you can do that by avoiding adding the "built from source tarball" text when `description` is non-empty.

**Comment by dawnofmidnight** [comment]
That was completely unintended, and I'm trying to fix that. I'm sorry for anyone that pinged.

**Comment by dawnofmidnight** [comment]
@rustbot -T-compiler -T-libs

> Could you please revert the change to the src/tools/cargo submodule?

I think I've got that all fixed, as well as the mir opt stuff (sorry!).

File: src/bootstrap/channel.rs [hunk 5]
```diff
@@ -18,19 +19,40 @@ pub enum GitInfo {
...
+                // If the file is malformed, just don't use it at all.
+                if sha.is_none() || short_sha.is_none() || commit_date.is_none() {
+                    return GitInfo::Absent;
+                }
+
+                return GitInfo::RecordedForTarball(Info {
+                    commit_date: commit_date.unwrap().to_owned(),
+                    sha: sha.unwrap().to_owned(),
+                    short_sha: short_sha.unwrap().to_owned(),
+                });
```
Comment (jyn514) [inline src/bootstrap/channel.rs:52]: nit: you can avoid unwrap here
```suggestion
                let info = match (commit_date, sha, short_sha) {
                    Some((date, sha, short_sha)) => Info { ... },
                    _ => return GitInfo::Absent, // If the file is malformed, just don't use it at all
               };
                return GitInfo::RecordedForTarball(info);
```

File: src/bootstrap/lib.rs [hunk 6]
```diff
@@ -1331,6 +1337,11 @@ impl Build {
         self.rust_info.sha()
     }
 
+    /// Returns the commit info.
+    fn rust_commit_info(&self) -> Option<&channel::Info> {
+        self.rust_info.info()
```
Comment (jyn514) [inline src/bootstrap/lib.rs:1342]: nit: I would rather use `builder.rust_info.info()` directly instead, I think it's more clear what's going on (and avoids people adding more wrapper functions in the future for submodules).

**Review by jyn514 — COMMENTED** [review]
This looks great :) I have two small comments, and I want to give @Mark-Simulacrum another chance to review.

Can you also please add a comment to `description` in config.toml.example explaining the new behavior? In particular, I think it's important we mention that you can opt-in to using pre-compiled .rlibs by setting `description = ''`

**Review by jyn514 — APPROVED** [review]
This looks great, thanks :) I assigned this to @Mark-Simulacrum since he had opinions on the approach earlier, but r=me if Mark doesn't have comments.

File: config.toml.example [hunk 7]
```diff
@@ -521,6 +521,9 @@ changelog-seen = 2
 # A descriptive string to be appended to `rustc --version` output, which is
 # also used in places like debuginfo `DW_AT_producer`. This may be useful for
 # supplementary build information, like distro-specific package versions.
+#
+# When building from a source tarball, this will default to "built from a source
+# tarball". To use pre-compiled libstd binaries, set this to "".
```
Comment (Mark-Simulacrum) [inline config.toml.example:526]: I'm not a fan of giving this suggestion to set this to "" -- I think the implications are worth more discussion here. Can we add something like:

The Rust compiler will differentiate between different versions of itself, including based on this string, which means that if you wish to be compatible with upstream Rust you need to set this to "". However, note that if you are not *actually* compatible -- for example if you've backported patches that change behavior -- this may lead to miscompilations or other bugs.

File: src/bootstrap/tarball.rs [hunk 8]
```diff
@@ -297,8 +297,9 @@ impl<'a> Tarball<'a> {
     fn run(self, build_cli: impl FnOnce(&Tarball<'a>, &mut Command)) -> GeneratedTarball {
         t!(std::fs::create_dir_all(&self.overlay_dir));
         self.builder.create(&self.overlay_dir.join("version"), &self.overlay.version(self.builder));
-        if let Some(sha) = self.builder.rust_sha() {
-            self.builder.create(&self.overlay_dir.join("git-commit-hash"), &sha);
+        if let Some(info) = self.builder.rust_info.info() {
+            let commit_info = format!("{}\n{}\n{}\n", info.sha, info.short_sha, info.commit_date);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/tarball.rs:301]: This format is duplicated in two places for writing, and one place for reading. Can we factor the read/write into one location (e.g., methods on a struct or similar) so that it's much easier to remember to update? This is particularly annoying since the code as written silently ignores the produced file, so we're unlikely to get bug reports (just unfortunate behavior).

Comment (dawnofmidnight) [reply src/bootstrap/tarball.rs:301]: > Can we factor the read/write into one location (e.g., methods on a struct or similar) so that it's much easier to remember to update?

I think this would fit well on the `Build` struct in `src/boostrap/lib.rs`, so I'll add methods for reading from and writing to the file.

> This is particularly annoying since the code as written silently ignores the produced file, so we're unlikely to get bug reports (just unfortunate behavior).

Do you think it'd be better to simply error if the formatting is wrong (assuming you're referring to [this code](https://github.com/dawnofmidnight/rust/blob/0561ae355cef0fa2a32b6bb09730ca03879c92f6/src/bootstrap/channel.rs#L49)).

Comment (Mark-Simulacrum) [reply src/bootstrap/tarball.rs:301]: Yes, I think so. In general, failing loudly is my preference or at least logging *something* (perhaps only in verbose mode, depending on how common it is to fail).

Comment (dawnofmidnight) [reply src/bootstrap/tarball.rs:301]: As for the former issue, I'm not sure of a good way to make a method on `Build` and then let `channel::GitInfo::new` use it if necessary. Any suggestion on that, or for a better place?

Comment (jyn514) [reply src/bootstrap/tarball.rs:301]: @dawnofmidnight make it `pub(crate)`

**Comment by dawnofmidnight** [comment]
Do I need to clean up the history (squashing, presumably) of this PR? It seems a bit messy.

@rustbot review

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed, thanks!

File: src/bootstrap/dist.rs [hunk 9]
```diff
@@ -897,12 +898,12 @@ impl Step for PlainSourceTarball {
 
         // Create the version file
         builder.create(&plain_dst_src.join("version"), &builder.rust_version());
-        if let Some(sha) = builder.rust_sha() {
-            builder.create(&plain_dst_src.join("git-commit-hash"), &sha);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/dist.rs:901]: Yeah, I overlooked this edit. I think we'll want to keep the git-commit-hash file around; it's consumed by build-manifest (https://github.com/rust-lang/rust/blob/744e397d8855f7da87d70aa8d0bd9e0f5f0b51a1/src/tools/build-manifest/src/versions.rs#L144).

We can probably also fix that code, but I think it's best to leave the file in place.

Comment (dawnofmidnight) [reply src/bootstrap/dist.rs:901]: Oh, my bad, I didn't realize other parts of code used it. Should I open a PR to add that back?

Comment (jyn514) [reply src/bootstrap/dist.rs:901]: If you could open a PR that would be great :)

Comment (dawnofmidnight) [reply src/bootstrap/dist.rs:901]: rust-lang/rust#102610 is now open :)
