### PR TITLE
Supress some lookup errors if a module contains `compile_error!`

### LINKED ISSUE #68838: Support for fatal compile_error that suppresses subsequent errors
If a crate includes something like:

```rust
#[cfg(not(target_os = "linux"))]
compile_error!("This crate only runs on Linux")
```

then it isn't helpful for rustc to report that error but then go on to emit many more cascading errors about failed `use` statements and types that don't exist and similar.

It's especially unhelpful when those additional errors scroll the initial error off the screen.

### PR DESCRIPTION
**Pull request by ogoffart**
The problem is that when a macro expand to `compile_error!` because its input is malformed, the actual error message from the `compile_error!` might be hidden in a long list of other messages about using items that should have otherwise been generated by the macro.

So suppress error about missing items in that module.

Fixes rust-lang/rust#68838

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? petrochenkov

File: compiler/rustc_resolve/src/macros.rs [hunk 1]
```diff
@@ -167,6 +167,12 @@ impl<'ra, 'tcx> ResolverExpand for Resolver<'ra, 'tcx> {
         self.invocation_parents[&id].parent_def
     }
 
+    fn mark_scope_with_compile_error(&mut self, id: NodeId) {
+        if let Some(id) = self.opt_local_def_id(id) {
+            self.mods_with_parse_errors.insert(id.to_def_id());
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:173]: Could you also check that `tcx.def_kind(id).is_module_like()`?
Otherwise you put non-module ids into the table.

File: compiler/rustc_resolve/src/ident.rs [hunk 2]
```diff
@@ -1718,7 +1718,8 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         diag_metadata: Option<&DiagMetadata<'_>>,
     ) -> PathResult<'ra> {
         let mut module = None;
-        let mut module_had_parse_errors = false;
+        let mut module_had_parse_errors = !self.mods_with_parse_errors.is_empty()
+            && self.mods_with_parse_errors.contains(&parent_scope.module.nearest_parent_mod());
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/ident.rs:1715]: Why is this necessary?
The `nearest_parent_mod()` part doesn't look right, and I'm not sure what effect this has in general, because a similar check already exists below.

Comment (ogoffart) [reply compiler/rustc_resolve/src/ident.rs:1715]: when looking for `foo::bar::baz()` the test bellow only starts when checking for `bar` in `foo`, but without this test here, we would still get the errors if `foo` is not found and that the current module contains a `compile_error!`

Comment (petrochenkov) [reply compiler/rustc_resolve/src/ident.rs:1715]: This is why I dislike random diagnostic changes like this, the added logic partially repeats a piece of logic that normally happens in an entirely different function (`resolve_ident_in_lexical_scope`/`resolve_ident_in_scope_set`).

Also, `foo` may be "not found" in multiple other locations, not just the current module (local variables, unnamed blocks, various preludes).
I guess it's ok to suppress the error if a poisoned module was found in at least one of those location during the search.
And `parent_scope.module.nearest_parent_mod()` will always be in the list.

File: compiler/rustc_resolve/src/macros.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs:173]: Also, if `compile_error!()` is written in a block, then it will not poison the block module (it doesn't have a `DefId`), but that's probably better than poisoning a wrong module (e.g. parent), which doesn't happen here.

File: compiler/rustc_resolve/src/ident.rs (hunk 2 above)
Comment (ogoffart) [reply compiler/rustc_resolve/src/ident.rs:1715]: Thanks for your review.

Indeed, the function scope are not added to the poisoned modules. (If I use invalid symbols in `error_in_this_function`, the error is not suppressed as it should)

I am not very familiar with the rustc codebase, so let me know if there is a way to solve that. (Adding non-module NodeId in the set?)

I was just re-using the existing `module_had_parse_errors` set, but maybe there is a better option?

I tried to change a bit the logic to be more robust, but I'm not sure what logic you mean is repeated.

File: compiler/rustc_resolve/src/ident.rs [hunk 3]
```diff
@@ -1866,7 +1875,19 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
                             path.len() - 1,
                         ));
                     }
-                    _ => Err(Determinacy::determined(finalize.is_some())),
+                    _ => {
+                        for rib in &ribs[ns] {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/ident.rs]: Let's just keep the previous version, it's better to have something simpler, than to copy even more logic from `resolve_ident_in_(scope_set,lexical_scope)` to here.

Comment (ogoffart) [reply compiler/rustc_resolve/src/ident.rs]: I've reverted back to the previous version. 
Note that this is less precise and doesn't suppress things likes in `super::...` anymore.

@rustbot ready
