### PR TITLE
Better user experience when attempting to call associated functions with dot notation

### LINKED ISSUE #22692: Better user experience when attempting to call associated functions with dot notation
New users might attempt to write something like this, (e.g. if they're coming from Java):

``` rust
fn main() {
    let _ = String.new();
}
```

This will not compile since they're not using `::`. This is what the compiler outputs when compiling:

```
~ $ rustc program.rs
program.rs:2:13: 2:19 error: unresolved name `String`
program.rs:2     let _ = String.new();
                         ^~~~~~
```

I find this error message pretty misleading. It'd be great if there was a lint that would check the available static methods of a struct/enum and if there's one that matches, suggest it instead (in the case above, suggest using `String::new()`).

### PR DESCRIPTION
**Pull request by dsciarra**
Closes #22692

### CODE REVIEW

**Comment by csmoe** [comment]
cc @estebank

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -3148,49 +3148,64 @@ impl<'a, 'crateloader: 'a> Resolver<'a, 'crateloader> {
...
-                                sp = cm.next_point(sp);
-                                match cm.span_to_snippet(sp) {
-                                    Ok(ref snippet) => {
-                                        if snippet.chars().any(|c| { !c.is_whitespace() }) {
-                                            break;
+                    (Def::Struct(def_id), PathSource::Expr(Some(parent))) if ns == ValueNS => {
+                        match parent.node {
+                            ExprKind::MethodCall(ref path_assignment, _)  => {
+                                err.span_label(parent.span, format!("did you mean to call static \
+                                                                    method `{}`?: `{}::{}`?",
```
Comment (zackmdavis) [inline src/librustc_resolve/lib.rs]: We're clearly not being consistent about it right _now_, but our internal documentation [advises against](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion) labels taking the form of a question. ... on the other hand, I'm having trouble thinking of a phrasing that feels unambiguously better. ("Perhaps you meant to call static method {}" sounds somewhat stilted.) I guess rewordings can always be left to future PRs.

File: src/test/ui/resolve/issue-22692.stderr [hunk 2]
```diff
@@ -0,0 +1,9 @@
+error[E0423]: expected value, found struct `String`
+  --> $DIR/issue-22692.rs:12:13
+   |
+12 |     let _ = String.new(); //~ ERROR did you mean to call static method `new`?: `String::new`
+   |             ^^^^^^---- help: did you mean to call static method `new`?: `String::new`
```
Comment (csmoe) [inline src/test/ui/resolve/issue-22692.stderr]: great. but it'll be better to have a suggestion here with https://doc.rust-lang.org/nightly/nightly-rustc/syntax/diagnostics/plugin/struct.Diagnostic.html#method.span_suggestion_with_applicability

File: src/librustc_resolve/lib.rs [hunk 3]
```diff
@@ -3148,49 +3148,64 @@ impl<'a, 'crateloader: 'a> Resolver<'a, 'crateloader> {
...
-                            // ahead for the next text to see if `span` is followed by a `{`.
-                            let cm = this.session.source_map();
-                            let mut sp = span;
-                            loop {
-                                sp = cm.next_point(sp);
-                                match cm.span_to_snippet(sp) {
-                                    Ok(ref snippet) => {
-                                        if snippet.chars().any(|c| { !c.is_whitespace() }) {
-                                            break;
+                    (Def::Struct(def_id), PathSource::Expr(Some(parent))) if ns == ValueNS => {
```
Comment (zackmdavis) [inline src/librustc_resolve/lib.rs]: The failing UI tests that [Travis reports](https://github.com/rust-lang/rust/pull/54308#issuecomment-422201051) indicate that this code isn't behaving as we expected. What happens when the second element is some variant of `PathSource` other than `Expr`?

**Review by zackmdavis — CHANGES_REQUESTED** [review]
Thanks for your contribution! Some revisions will be needed for tests to pass.

In addition to having the issue number in the commit message and PR description, a brief summary of the change (not more than [72 characters](https://chris.beams.io/posts/git-commit/#wrap-72)) is also useful for future readers of the repository history; you can edit the commit message with `git commit --amend`.

File: src/test/ui/resolve/issue-22692.stderr (hunk 2 above)
Comment (zackmdavis) [reply src/test/ui/resolve/issue-22692.stderr]: Specifically, the last argument to `span_suggestion_with_applicability` should be `Applicability::MaybeIncorrect`. (See the [diagnostics chapter of the Contributor's Guide](https://rust-lang-nursery.github.io/rustc-guide/diag.html#suggestions) and #50723 for context.)

Comment (killercup) [reply src/test/ui/resolve/issue-22692.stderr]: Please make sure to cover the correct range even when this is "MaybeIncorrect", people can in theory still apply this manually with RLS. (I.e., cover exactly `String.new` if you suggest `String::new`, or `String.new()` if you suggest `String::new()`)

Comment (estebank) [reply src/test/ui/resolve/issue-22692.stderr]: Note: I'm not sure, I would have to look at the replaced generated file, but it seems to me that the correct span is covered (the `-` underline is just covered by the `^`, as intemded).

**Comment by Centril** [comment]
Note: we don't call these "static method"s but rather "associated function"s. Methods are only those which you may call with dot notation. Therefore it may be confusing to call them "static method" in error messages.

**Comment by TimNN** [comment]
Ping from triage @dsciarra: It looks like some changes have been requested to your PR.

**Comment by dsciarra** [comment]
The build is still failing locally, it would be nice if you can have a second look ;)

File: src/librustc_resolve/lib.rs [hunk 4]
```diff
@@ -3127,6 +3127,22 @@ impl<'a, 'crateloader: 'a> Resolver<'a, 'crateloader> {
                         }
                         return (err, candidates);
                     },
+                    (Def::Struct(_), PathSource::Expr(Some(parent))) if ns == ValueNS => {
+                        match parent.node {
+                            ExprKind::MethodCall(ref path_assignment, _)  => {
+                                err.span_suggestion_with_applicability(
+                                    parent.span,
+                                    "incorrect associated function syntax",
+                                    format!("try {}::{}()?",
```
Comment (zackmdavis) [inline src/librustc_resolve/lib.rs]: @dsciarra The [third argument to the `span_suggestion_` methods](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion_with_applicability) should be a code snippet to replace the span passed as the first argument. We're going to need something more like 

```rust
err.span_suggestion_with_applicability(
    parent.span,
    "use `::` to access an associated function",
    format!("{}::{}", path_str, path_assignment.ident)
);
```

(But this probably isn't literally correct as written. In the UI test output, it looks like our span includes the call args (here, just `()`), which we don't want to replace.)

Comment (estebank) [reply src/librustc_resolve/lib.rs]: If you need to get part of the literal code, you can use `Codemap::span_to_snippet` to get it, like done here:

https://github.com/rust-lang/rust/blob/f1694eac74216da22b395a5589b8d080ccd5a2ec/src/librustc_typeck/check/demand.rs#L270

**Comment by dsciarra** [comment]
Is there a better way to write this?

File: src/librustc_resolve/lib.rs [hunk 5]
```diff
@@ -3157,16 +3157,46 @@ impl<'a, 'crateloader: 'a> Resolver<'a, 'crateloader> {
...
-                                err.span_label(
-                                    span,
-                                    format!("did you mean `{} {{ /* fields */ }}`?", path_str),
-                                );
+                            match source {
+                                PathSource::Expr(Some(parent)) => {
+                                    match parent.node {
+                                        ExprKind::MethodCall(ref path_assignment, _)  => {
+                                            err.span_suggestion_with_applicability(
+                                                parent.span,
```
Comment (estebank) [inline src/librustc_resolve/lib.rs]: Instead of `parent.span` use `source_map.start_point(parent.span).to(path_assignment.span)`. This way the span will point at `Span.new` instead of `Span.new()`.

File: src/test/ui/resolve/issue-22692.stderr [hunk 6]
```diff
@@ -0,0 +1,11 @@
+error[E0423]: expected value, found struct `String`
+  --> $DIR/issue-22692.rs:12:13
+   |
+LL |     let _ = String.new();
+   |             ^^^^^^------
```
Comment (estebank) [inline src/test/ui/resolve/issue-22692.stderr]: Notice in the underline that it includes the `()`.

**Comment by estebank** [comment]
> Is there a better way to write this?

Other than the inline comment, it seems reasonable to me.

File: src/librustc_resolve/lib.rs (hunk 5 above)
Comment (csmoe) [reply src/librustc_resolve/lib.rs]: then you can get the span through its `ident` field.

**Comment by estebank** [comment]
@bors r+ rollup

🎉🎉🎉
