### PR TITLE
Forbid casting to/from a pointer of unknown kind

### LINKED ISSUE #45730: ICE on nightly
The following code ([playground](https://play.rust-lang.org/?gist=34bc5c409fcc5683ed27fc74a713ddde&version=nightly)) crashes rustc on latest nightly `1.23.0-nightly (2be4cc040 2017-11-01)`:

```rust
fn main() {
  ::std::ptr::read_volatile(0 as _);
}
```

Current stable and beta doesn't crash.

What I see:

```
   Compiling playground v0.0.1 (file:///playground)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0-nightly (2be4cc040 2017-11-01) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'explicit panic', /checkout/src/librustc_typeck/check/cast.rs:108:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by tirr-c**
Fixes #45730.

Before, it ICE'd when `pointer_kind` encountered `TyInfer`.

### CODE REVIEW

File: src/librustc_typeck/check/cast.rs [hunk 1]
```diff
@@ -105,6 +105,9 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
             // We should really try to normalize here.
             ty::TyProjection(ref pi) => PointerKind::OfProjection(pi),
             ty::TyParam(ref p) => PointerKind::OfParam(p),
+            // Insufficient type information; this will be caught later, so just report that this
+            // is a thin pointer.
+            ty::TyInfer(_) => PointerKind::Thin,
```
Comment (tirr-c) [inline src/librustc_typeck/check/cast.rs]: Does this case occur only by lack of type information? I'm not pretty sure.

**Comment by arielb1** [comment]
@tirr-c 

It's not a good idea to assume things when encountering a `TyInfer` - trait bounds etc. can make the `TyInfer` equal to every type, so this could accidentally allow thin-to-fat pointer casts if the `_` is later made to be equal `fmt::Debug`, as in:
```Rust
use std::fmt;
fn main() {
  let x: *const _ = 0 as *const _; // we don't want to allow this if...
  let y: Option<*const fmt::Debug> = Some(x) as _;
  // ^ later, we have x = *const fmt::Debug
}

fn not_ok() {
  let x = 0 as *const i32 as *const _ as *mut _; //~ ERROR ?
}
```

Instead, you should make `fn pointer_kind` return an `Option`, and emit an error of we are casting to an unknown pointer kind..

**Comment by tirr-c** [comment]
Added a new error code for casting with unknown pointer kind.

r? @arielb1

File: src/librustc_typeck/check/cast.rs [hunk 2]
```diff
@@ -457,14 +478,20 @@ impl<'a, 'gcx, 'tcx> CastCheck<'tcx> {
         debug!("check_ptr_ptr_cast m_expr={:?} m_cast={:?}", m_expr, m_cast);
         // ptr-ptr cast. vtables must match.
 
+        let (expr_kind, cast_kind) =
```
Comment (arielb1) [inline src/librustc_typeck/check/cast.rs]: This forbids casting an `*const _` to an `*const u32`, please move the check after the if.

**Comment by tirr-c** [comment]
Updated, but I couldn't trigger the `*const _ as *const u32` case. What would the code look like?

**Comment by arielb1** [comment]
@tirr-c 

Can't you have `0 as *const u32 as *const _ as *const u32`? Or does that go through a separate code-path?

**Comment by tirr-c** [comment]
It just compiles. I'm not sure when inference occurs, but maybe `*const _` there is inferred as `*const u32`?
