### PR TITLE
Fix self profiler ICE on Windows

### LINKED ISSUE #51648: ICE rustc 1.26.2 'specified instant was later than self'
After ~2 weeks of continuously building our project without fail, our Windows build machines (2 of them) began throwing an error of this kind, while building dependencies:

``` 
thread 'rustc' panicked at 'specified instant was later than self', libcore\option.rs:916:5

 error: internal compiler error: unexpected panic
 
 note: the compiler unexpectedly panicked. this is a bug.
 
 note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
 
 note: rustc 1.26.2 (594fb253c 2018-06-01) running on i686-pc-windows-msvc
 
 note: compiler flags: -C opt-level=3 --crate-type lib
 
 note: some of the compiler flags provided by cargo are hidden
 
 error: Could not compile `ws`.
```

Each time this failure occurred it was on a different dependency of the project. It's also worth noting that this failure did not occur on every build, but it was very frequent. The failure occurs using both `i686-pc-windows-msvc` and `x86_64-pc-windows-msvc`.

A very similar issue was reported in rustc 1.23.0: https://github.com/rust-lang/rust/issues/47684

Restarting the affected build machines seems to have stopped the issue from occurring, at least temporarily.

If there's anything I can do to help diagnose/solve this problem, I'm eager to jump in.

## Meta

`rustc --version --verbose`:
rustc 1.26.2 (594fb253c 2018-06-01)
binary: rustc
commit-hash: 594fb253c2b02b320c728391a425d028e6dc7a09
commit-date: 2018-06-01
host: i686-pc-windows-msvc
release: 1.26.2
LLVM version: 6.0

Backtrace:
```
    0: <i32 as std::sys::windows::net::IsMinusOne>::is_minus_one
    1: std::panicking::take_hook
    2: std::panicking::take_hook
    3: rustc::ty::maps::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc::ty::maps::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::read_str
    4: std::panicking::begin_panic_fmt
    5: rust_begin_unwind
    6: core::panicking::panic_fmt
    7: core::option::expect_failed
    8: <std::ffi::c_str::IntoStringError as core::fmt::Debug>::fmt
    9: std::time::Instant::elapsed
   10: rustc_trans_utils::link::invalid_output_for_target
   11: rustc_trans_utils::symbol_names::provide
   12: rustc::dep_graph::graph::DepGraph::assert_ignored
   13: rustc::ty::maps::<impl rustc::ty::maps::queries::wasm_import_module_map<'tcx>>::try_get
   14: <rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx> as rustc::ty::layout::HasTyCtxt<'gcx>>::tcx
   15: rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::ensure
   16: rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::try_get
   17: rustc::ty::maps::TyCtxtAt::symbol_name
   18: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name
   19: <rustc_trans::base::ValueIter as core::iter::iterator::Iterator>::next
   20: <rustc_trans::ModuleLlvm as core::fmt::Debug>::fmt
   21: <rustc_trans::base::ValueIter as core::iter::iterator::Iterator>::next
   22: rustc::dep_graph::graph::DepGraph::assert_ignored
   23: rustc::ty::maps::<impl rustc::ty::maps::queries::wasm_import_module_map<'tcx>>::try_get
   24: <rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx> as rustc::ty::layout::HasTyCtxt<'gcx>>::tcx
   25: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::ensure
   26: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
   27: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
   28: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
   29: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
   30: rustc_driver::driver::build_output_filenames
   31: rustc_driver::driver::phase_4_translate_to_llvm
   32: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
   33: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
   34: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
   35: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
   36: rustc_driver::driver::compile_input
   37: rustc_driver::run_compiler
   38: rustc_driver::target_features::add_configuration
   39: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_impl_item
   40: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
   41: _rust_maybe_catch_panic
   42: rustc_driver::driver::build_output_filenames
   43: <<std::sys_common::remutex::ReentrantMutex<T> as core::fmt::Debug>::fmt::LockedPlaceholder as core::fmt::Debug>::fmt
   44: std::sys::windows::thread::Thread::new
   45: BaseThreadInitThunk
   46: RtlSubscribeWnfStateChangeNotification
   47: RtlSubscribeWnfStateChangeNotification
```

and the relevant output of systeminfo:
```
Host Name:                 ---
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Original Install Date:     9/8/2017, 2:59:51 PM
System Boot Time:          6/19/2018, 10:49:50 AM
System Manufacturer:       Xen
System Model:              HVM domU
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 63 Stepping 2 GenuineIntel ~2400 Mhz
BIOS Version:              Xen 4.2.amazon, 8/24/2006
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,768 MB
Available Physical Memory: 30,423 MB
Virtual Memory: Max Size:  37,632 MB
Virtual Memory: Available: 35,042 MB
Virtual Memory: In Use:    2,590 MB
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #51648

### CODE REVIEW

File: src/librustc/util/profiling.rs [hunk 1]
```diff
@@ -197,7 +197,21 @@ impl SelfProfiler {
     }
 
     fn stop_timer(&mut self) -> u64 {
-        let elapsed = self.current_timer.elapsed();
+        let elapsed =
+            if cfg!(windows) {
```
Comment (estebank) [inline src/librustc/util/profiling.rs]: Can you change the formatting to have the `if` clause in the same line as `let elapsed` and move the rest of the block one indentation level left?

File: src/librustc/util/profiling.rs [hunk 2]
```diff
@@ -197,7 +197,21 @@ impl SelfProfiler {
...
+                //On Windows, timers don't always appear to be monotonic (see #51648)
+                //which can lead to panics when calculating elapsed time.
+                //Work around this by testing to see if the current time is less than
+                //our recorded time, and if it is, just returning 0.
```
Comment (estebank) [inline src/librustc/util/profiling.rs]: Can you add one space after `//` in this block?

File: src/librustc/session/mod.rs [hunk 3]
```diff
@@ -826,8 +826,10 @@ impl Session {
     }
 
     pub fn profiler<F: FnOnce(&mut SelfProfiler) -> ()>(&self, f: F) {
-        let mut profiler = self.self_profiling.borrow_mut();
-        f(&mut profiler);
+        if self.opts.debugging_opts.self_profile {
+            let mut profiler = self.self_profiling.borrow_mut();
+            f(&mut profiler);
+        }
```
Comment (estebank) [inline src/librustc/session/mod.rs]: Was this change _needed_? (Not that it's wrong, just surprised it wasn't already the case).

**Review by estebank — APPROVED** [review]
Other than a couple of nitpicks, r=me.

**Comment by michaelwoerister** [comment]
:heart: :heart: :heart:

File: src/librustc/session/mod.rs (hunk 3 above)
Comment (wesleywiser) [reply src/librustc/session/mod.rs]: Not needed per se. It wasn't already the case because we showed a very small amount of overhead from turning on the profiler. I think it's probably best to make it opt-in though.

**Review by IntrepidPig — COMMENTED** [review]
I think there might be an error with how this workaround was applied. This is my first time delving in to rustc though so I could be way off the mark, sorry if that's the case.

Also, I just remembered: I think this issue is present on many more platforms than just windows and would be better handled by modifying the `elapsed` function in libstd or wherever it is, as well as editing the documentation and remove the statement that guarantees them to be nondecreasing.

File: src/librustc/util/profiling.rs [hunk 4]
```diff
@@ -197,7 +197,20 @@ impl SelfProfiler {
...
+        let elapsed = if cfg!(windows) {
+            // On Windows, timers don't always appear to be monotonic (see #51648)
+            // which can lead to panics when calculating elapsed time.
+            // Work around this by testing to see if the current time is less than
+            // our recorded time, and if it is, just returning 0.
+            let now = Instant::now();
+            if self.current_timer >= now {
+                Duration::new(0, 0)
+            } else {
+                self.current_timer.elapsed()
```
[the remark this answers is not in the document]
Comment (wesleywiser) [reply src/librustc/util/profiling.rs]: That seems like a reasonable change to me

**Comment by wesleywiser** [comment]
@IntrepidPig The real work around here for all platforms not just Windows was the first commit:

b319715456c08097f2cd936da309ed6e8aec2843 Disable the self-profiler unless the `-Z self-profile` flag is set 

None of the bug reports we've received so far have indicated that the user was actually trying to run the profiler, the were just trying to compile some code.
