### PR TITLE
fix path str eq

### LINKED ISSUE #146183: Checking a `&PathBuf` and a `&str` for equality leads to a stack overflow
Reproducer (nightly 1.91):

```rs
fn main() {
    _ = &std::path::PathBuf::from("x") == "-";
}
```

or

```rs
fn main() {
    _ = "-" == &std::path::PathBuf::from("x");
}
```

When run, it leads to a stack overflow. Output in debug mode (hangs in release):

```
thread 'main' (157) has overflowed its stack
fatal runtime error: stack overflow, aborting
```

`_ = std::path::Path::new("x") == "-";` does not reproduce this stack overflow.
Neither does this: `_ = &std::path::PathBuf::from("x") == std::path::Path::new("-");`.

This might be related to the recent addition of `PartialEq<str> for Path`, `PartialEq<str> for PathBuf` and friends on nightly (1.91).

---

```
rustc 1.91.0-nightly (51ff89506 2025-09-02)
binary: rustc
commit-hash: 51ff895062ba60a7cba53f57af928c3fb7b0f2f4
commit-date: 2025-09-02
host: x86_64-unknown-linux-gnu
release: 1.91.0-nightly
LLVM version: 21.1.0
```

Also reproduces on the playground (nightly).

### PR DESCRIPTION
**Pull request by bend-n**
fixes rust-lang/rust#146183
where the impl for partialeq<str> for pathbuf resulted in infinite recursion

### CODE REVIEW

File: library/std/src/path.rs [hunk 1]
```diff
@@ -2107,7 +2107,7 @@ impl PartialEq for PathBuf {
 impl cmp::PartialEq<str> for PathBuf {
     #[inline]
     fn eq(&self, other: &str) -> bool {
-        &*self == other
+        Path::eq(&self, other)
```
Comment (fmease) [inline library/std/src/path.rs]: You should be able to say

```suggestion
        Path::eq(self, other)
```

**Review by gferrate — APPROVED** [review]
