### PR TITLE
Structurally normalize types as needed in `projection_ty_core`

### LINKED ISSUE #221: redscript regression
Something due to a missing normalization when applying user type annotations or something like that.

https://crater-reports.s3.amazonaws.com/pr-133502-13/try%233cddd79d4be3c8f1e937d09ca618d192abc69373/gh/jac3km4.redscript-ide/log.txt

```rust
trait Mirror {
    type Assoc;
}
impl<T> Mirror for T {
    type Assoc = T;
}

struct Foo<'a> { f: <&'a (i32,) as Mirror>::Assoc }

impl Foo<'_> {
    fn hello(x: Self) {
        match x {
            Self { f: (i,) } => {}
        }
    }
}
```

### LINKED ISSUE #141708: Broken MIR: `relate_type_and_user_type` may receive unnormalized types
This code ICEs:

```rust
trait Foo<'a> {
    type Assoc;
}

impl<T> Foo<'_> for T {
    type Assoc = T;
}

fn foo<'b: 'b, T: for<'a> Foo<'a>, F: for<'a> Fn(<T as Foo<'a>>::Assoc)>(_: F) -> (T, F) {
    todo!()
}

fn main() {
    let (x, c): (i32, _) = foo::<'static, _, _>(|_| {});
}
```

We create a very sneaky closure type that has the signature of `for<'a> fn(<i32 as Foo<'a>>::Assoc)`. Note that this type is not normalized, because of higher-ranked normalization problems w/ the old trait solver.

We then store this type into `c` in the `let` statement, and because it's a pattern, we end up storing a user type annotation that links it to the field ascription. Since it's a pattern with a single field place elem, we end up normalizing the closure type here: 

https://github.com/rust-lang/rust/blob/6f69710780d579b180ab38da4c1384d630f7bd31/compiler/rustc_borrowck/src/type_check/mod.rs#L479

note that this is a full normalization in the old solver.

We then try to relate the unnormalized and normalized closure signatures, which fails in the old solver.

### PR DESCRIPTION
**Pull request by compiler-errors**
Introduce a `structurally_normalize` callback to `projection_ty_core`, and then use it before we match on the ty kind in `projection_ty_core`.

Previously we were only structurally normalizing the return type of the `handle_field` struct, but if we were to (e.g.) apply a deref projection to that type, then the resulting type is not guaranteed to be structurally normalized and any subsequent projections applied would ICE.

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/221

I'll leave a few comments inline to explain the changes.

r? lcnr

---

Also fixes rust-lang/rust#141708

### CODE REVIEW

File: compiler/rustc_middle/src/mir/statement.rs [hunk 1]
```diff
@@ -88,26 +88,31 @@ impl<'tcx> PlaceTy<'tcx> {
     ///
     /// Note that the resulting type has not been normalized.
     #[instrument(level = "debug", skip(tcx), ret)]
-    pub fn field_ty(self, tcx: TyCtxt<'tcx>, f: FieldIdx) -> Ty<'tcx> {
-        if let Some(variant_index) = self.variant_index {
-            match *self.ty.kind() {
+    pub fn field_ty(
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/mir/statement.rs:91]: See comment below for why I split the `self` arg up into its fields.

File: compiler/rustc_middle/src/mir/statement.rs [hunk 2]
```diff
@@ -201,17 +206,18 @@ impl<'tcx> PlaceTy<'tcx> {
...
             }
-            ProjectionElem::Field(f, fty) => PlaceTy::from_ty(handle_field(&self, f, fty)),
-            ProjectionElem::OpaqueCast(ty) => {
-                PlaceTy::from_ty(handle_opaque_cast_and_subtype(&self, ty))
-            }
-            ProjectionElem::Subtype(ty) => {
-                PlaceTy::from_ty(handle_opaque_cast_and_subtype(&self, ty))
-            }
+            ProjectionElem::Field(f, fty) => PlaceTy::from_ty(handle_field(
+                structurally_normalize(self.ty),
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/mir/statement.rs:210]: See above, here we'd need to do something like:

```
{
    self.ty = structurally_normalize(self.ty);
    PlaceTy::from(handle_field(self, f, fty))
}
```

which I think is kinda awkward.

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 3]
```diff
@@ -474,17 +474,16 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+                |ty| self.structurally_resolve(ty, locations),
+                |ty, variant_index, field, ()| PlaceTy::field_ty(tcx, ty, variant_index, field),
+                |_| unreachable!(),
             );
             curr_projected_ty = projected_ty;
         }
         trace!(?curr_projected_ty);
 
-        let ty = curr_projected_ty.ty;
+        let a = self.normalize(a, locations);
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs:485]:
```suggestion
        // Need to renormalize `a` as writeback may have failed to normalize
        // higher ranked aliases if their normalization was ambiguous. 
        let a = self.normalize(a, locations);
```

**Review by lcnr — COMMENTED** [review]
r=me after nit

**Comment by jhpratt** [comment]
still in the queue

@bors r-
