### PR TITLE
fix rebasing cycle heads when not reaching a fixpoint

### LINKED ISSUE #232: "Type mismatch resolving..." only on new trait solver
Standalone Repro: https://rust.godbolt.org/z/8eYbPzeqq

(playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=a806b35a71c5d31d715eebde4651f21e)

I will try to minimize it more if possible later, I already spent a good amount of hours on it for now tho, hehe.

The new trait solver has never worked with my (WIP) crate, it never finished compiling, even after hours of waiting. But when I updated the compiler today turns out that in the last few weeks that got fixed! But now I have 500+ error messages saying "type mismatch resolving ..." or "trait bound ... not satisfied". I am not sure that's a bug or a breaking change, but I thought I'd file an issue anyway.

### PR DESCRIPTION
**Pull request by lcnr**
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/232

annoyingly subtle, imagine the following proof tree

- A (no cycle head usages, final result Y)
  - *ignored* B (depends on A with provisional result X)
    - A (cycle, provisional result X)
- B (using the cache entry here incorrectly assumes A has final result X)

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_type_ir/src/search_graph/mod.rs [hunk 1]
```diff
@@ -927,6 +962,10 @@ impl<D: Delegate<Cx = X>, X: Cx> SearchGraph<D> {
                     return true;
                 };
 
+                let Some(new_highest_head_index) = heads.opt_highest_cycle_head_index() else {
+                    return false;
+                };
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/search_graph/mod.rs:974]: moved earlier for potential perf gains. no need to do anything more involved if we need to pop anyways

File: compiler/rustc_type_ir/src/search_graph/mod.rs [hunk 2]
```diff
@@ -941,6 +980,22 @@ impl<D: Delegate<Cx = X>, X: Cx> SearchGraph<D> {
...
+                        RebaseReason::Overflow => D::on_fixpoint_overflow(cx, input),
+                        RebaseReason::ReachedFixpoint(None) => *result,
+                        RebaseReason::ReachedFixpoint(Some(path_kind)) => {
+                            if popped_head.usages.is_single(path_kind) {
+                                *result
+                            } else {
+                                return false;
+                            }
+                        }
+                    };
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/search_graph/mod.rs]: same with mutating the result. as this can now cause us to drop the provisional result, let's do it before recomputing paths
