### PR TITLE
Parser: Recover from attributes applied to types and generic args

### LINKED ISSUE #135017: Placing an attribute on a generic argument confuses the parser
### Code

```Rust
struct Foo<T>(T);

fn main() {
    let foo: Foo<#[cfg(not(wrong))] String> = todo!();
}
```

### Current output

```Shell
error: invalid const generic expression
 --> /playground/src/main.rs:8:37
  |
8 |     let foo: Foo<#[cfg(not(wrong))] String> = todo!();
  |                                     ^^^^^^
  |
help: expressions must be enclosed in braces to be used as const generic arguments
  |
8 |     let foo: Foo<#[cfg(not(wrong))] { String }> = todo!();
```

### Desired output

```Shell
error: attributes are not allowed on generic arguments 
--> /playground/src/main.rs:8:37
  |
8 |     let foo: Foo<#[cfg(not(wrong))] String> = todo!();
  |                  ^^^^^^^^^^^^^^^^^^
  |                  attribute not allowed in this context
help: remove the attribute to allow the code to compile:
8 |     let foo: Foo<String> = todo!();
```

### Rationale and extra context

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=eaf1097ff4efa3734d3a5e3faa3cb10f

### Other cases

```Rust
If one applies the suggestion made in the current error, you get the "same" error message suggesting to add another level of brackets.
```

### Rust Version

```Shell
Build using the Nightly version: 1.85.0-nightly

(2025-01-01 45d11e51bb66c2deb63a)
```

### Anything else?

_No response_

### LINKED ISSUE #144132: Confusing diagnostic for attributes on types
### Code

```Rust
fn f() {
    let _generic: Box<#[attr] i32> = Box::new(1);
    let _assignment: #[attr] i32 = Box::new(1);
}
```

### Current output

```Shell
error: invalid const generic expression
 --> src/lib.rs:2:31
  |
2 |     let _generic: Box<#[attr] i32> = Box::new(1);
  |                               ^^^
  |
help: expressions must be enclosed in braces to be used as const generic arguments
  |
2 |     let _generic: Box<#[attr] { i32 }> = Box::new(1);
  |                               +     +

error: expected type, found `#`
 --> src/lib.rs:3:22
  |
3 |     let _assignment: #[attr] i32 = Box::new(1);
  |                    - ^ expected type
  |                    |
  |                    while parsing the type for `_assignment`
  |                    help: use `=` if you meant to assign

error[E0658]: attributes on expressions are experimental
 --> src/lib.rs:3:22
  |
3 |     let _assignment: #[attr] i32 = Box::new(1);
  |                      ^^^^^^^
  |
  = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information

error: cannot find attribute `attr` in this scope
 --> src/lib.rs:3:24
  |
3 |     let _assignment: #[attr] i32 = Box::new(1);
  |                        ^^^^
  |
help: consider importing this attribute macro
  |
1 + use rustversion::attr;
  |

error[E0423]: expected value, found builtin type `i32`
 --> src/lib.rs:3:30
  |
3 |     let _assignment: #[attr] i32 = Box::new(1);
  |                              ^^^ not a value
  |
help: consider importing one of these functions instead
  |
1 + use fastrand::i32;
  |
1 + use nom::character::complete::i32;
  |
1 + use nom::character::streaming::i32;
  |
1 + use nom::number::complete::i32;
  |
    and 2 other candidates

error[E0747]: constant provided when a type was expected
 --> src/lib.rs:2:31
  |
2 |     let _generic: Box<#[attr] i32> = Box::new(1);
  |                               ^^^
```

### Desired output

```Shell
error: attributes cannot be applied to a type
 --> src/lib.rs:2:31
  |
2 |     let _generic: Box<#[attr] i32> = Box::new(1);
  |                       ^^^^^^^ attributes are not allowed here

error: attributes cannot be applied to a type
 --> src/lib.rs:3:22
  |
3 |     let _assignment: #[attr] i32 = Box::new(1);
  |                      ^^^^^^^ attributes are not allowed here
```

### Rationale and extra context

Since function-like macros are allowed in type position, I thought attributes might work in type position as well, but apparently not. The diagnostic is pretty confusing, though. We already emit a good one when the attribute is in parameter position, e.g.

```rust
fn f(_param: #[attr] i32) {}
```

```rust
error: attributes cannot be applied to a function parameter's type
 --> src/lib.rs:1:14
  |
1 | fn f(_param: #[attr] i32) {}
  |              ^^^^^^^ attributes are not allowed here
```

...but apparently not in other type positions.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.90.0-nightly (a00149764 2025-07-14)
binary: rustc
commit-hash: a001497644bc229f1abcc5b2528733386591647f
commit-date: 2025-07-14
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.8
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kivooeo**
r? compiler

Add clearer error messages for invalid attribute usage in types or generic types

fixes rust-lang/rust#135017
fixes rust-lang/rust#144132

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -374,6 +374,27 @@ impl<'a> Parser<'a> {
...
         {
             self.parse_unsafe_binder_ty()?
+        } else if self.token == token::Pound
+            && self.look_ahead(1, |t| matches!(t.kind, token::OpenBracket))
+        {
+            let lo_attr = self.token.span;
+
+            while self.token != token::CloseBracket && self.token != token::Eof {
+                self.bump();
+            }
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: The logic here is pretty strange. 

Why wouldn't we just go through the normal parsing routine to parse an attr, then go through the normal parsing routine to parse a type?

File: compiler/rustc_parse/src/parser/ty.rs [hunk 2]
```diff
@@ -374,6 +374,27 @@ impl<'a> Parser<'a> {
...
+
+            if self.token != token::Eof {
+                self.bump(); // eat ']'
+            }
+
+            let span = lo_attr.to(self.prev_token.span);
+
+            if self.token.is_ident() {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: Specifically, this only works if the type is an ident. We have lots of other types to handle here.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/ty.rs]: Why not just try parsing an attr eagerly at the beginning of `parse_ty_common`, and then there doesn't need to be a special branch in this if chain?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors

File: compiler/rustc_parse/src/parser/ty.rs (hunk 1 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/ty.rs]: Oh, honestly didn't know about "normal parsing routine" and just go manually parsing, do you mean "parse_outer_attributes"?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/ty.rs]: Yeah probably something like that. Look at how we parse item attrs for example.

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/ty.rs]: Let's see if I'm on a right way, firstly implemented it for generic then just copied for regular type, based on tests it seems works fine

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/ty.rs]: Thinking about it now, maybe I could yeet that logic into a helper function and not duplicate code, but first need your opinion on logic itself, but I'm out for now

File: compiler/rustc_parse/src/parser/path.rs [hunk 3]
```diff
@@ -880,6 +880,25 @@ impl<'a> Parser<'a> {
...
+        if self.token == token::Pound && self.look_ahead(1, |t| *t == token::OpenBracket) {
+            let attrs_wrapper = self.parse_outer_attributes()?;
+
+            if !attrs_wrapper.is_empty() {
+                // Parse attribute.
+                let raw_attrs = attrs_wrapper.take_for_recovery(self.psess);
+
+                let attr_span = raw_attrs[0].span.to(raw_attrs.last().unwrap().span);
+
+                let ty_after_attr = self.parse_ty()?;
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]: I find it a bit odd that we're assuming a type must follow the attributes.

Since we're in `parse_generic_args`, I would expect us to simply parse attributes at the start of the function. That way, we also will emit good diagnostics for attributes on lifetimes (e.g., `#[a] 'a`) and const args (e.g., `#[a] 0`). We can simply say sth. akin to "attributes are not supported on generic arguments".

Comment (fmease) [reply compiler/rustc_parse/src/parser/path.rs]: (We do actually support attrs on const args by means of macro meta vars: `macro_rules! X { ($e:expr) => { X<$e> } }  X!(#[a] 0)` if feat `stmt_expr_attributes` is enabled but that isn't really relevant here)

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: So you suggest to parse not only types but all other generic things that could appear in generic? Just asking because I believe I could miss interpreted your message

Comment (fmease) [reply compiler/rustc_parse/src/parser/path.rs]: Right now you essentially do

```
if parse_attrs()
then parse_ty()
else parse_lifetime_or_const_arg_or_ty_or_recover()
```

 and I'm suggesting

```
parse_attrs();
parse_lifetime_or_const_arg_or_ty_or_recover_and_reject_if_we_have_attrs()
```

Ofc it would need to be robust enough that we don't end up forgetting to reject the attributes in all branches.

So yeah, I'm saying that ideally we would just expect a generic arg after the attrs because if in path `X<…>` the `…` can be any kind of generic arg, why would `X<#[a] …>` suddenly mean the `…` has to be a type arg?

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: Yes I understand that part that I'm always waiting a type because that's what I did when wrote `parse_ty()`, so ideally what I see for now is after I found an attribute in generic I will let function to continue parsing arguments and not do early return from here and only after based on what we have next will emit error, so basically will try to split error detection and error reporting. But could try only later today

**Comment by Kivooeo** [comment]
~~I'm genuinely curious about case where we have attribute in generic but don't have argument, what would ideal error in such case?~~

~~I'm not sure if we want to recover after finding a attribute, becuase it's always a wrong code and it's lead to case like this~~

Well I added a branch to handle this (you can see it in review below)

```rust
error[E0107]: struct takes 1 generic argument but 0 generic arguments were supplied
 --> src/main.rs:4:12
  |
4 |     let _: Baz<#[cfg(any())]> = todo!();
  |            ^^^ expected 1 generic argument
  |
note: struct defined here, with 1 generic parameter: `N`
 --> src/main.rs:1:8
  |
1 | struct Baz<const N: usize>(i32);
  |        ^^^ --------------
help: add missing generic argument
  |
4 |     let _: Baz<N#[cfg(any())]> = todo!();
  |                +

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0107`.
```

File: compiler/rustc_parse/src/parser/path.rs [hunk 4]
```diff
@@ -934,6 +943,10 @@ impl<'a> Parser<'a> {
             }
         } else if self.token.is_keyword(kw::Const) {
             return self.recover_const_param_declaration(ty_generics);
+        } else if let Some(attr_span) = attr_span {
+            // Handle case where attribute is present but no valid generic argument follows.
+            let guar = self.dcx().emit_err(AttributeOnEmptyGeneric { span: attr_span });
+            return Ok(Some(GenericArg::Type(self.mk_ty(attr_span, TyKind::Err(guar)))));
```
Comment (Kivooeo) [inline compiler/rustc_parse/src/parser/path.rs]: Well, figured it out, but still, need this branch to handle this case

File: tests/ui/parser/attribute-on-type.stderr [hunk 5]
```diff
@@ -0,0 +1,207 @@
...
+  --> $DIR/attribute-on-type.rs:9:18
+   |
+LL |     let foo: Foo<#[cfg(not(wrong))] String> = todo!();
+   |                  ^^^^^^^^^^^^^^^^^^ attributes are not allowed here
+   |
+help: remove attribute from here
+   |
+LL -     let foo: Foo<#[cfg(not(wrong))] String> = todo!();
+LL +     let foo: Foo<String> = todo!();
+   |
```
Comment (Kivooeo) [inline tests/ui/parser/attribute-on-type.stderr]: And as we can see from here, I decided to try approach where we suggest to user to remove attribute and leave only type or other generic thing we have in here, also if it's undesirable to have I can easily remove it and make it only point to a span without suggestion

File: tests/ui/parser/attribute-on-type.rs [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+
+    let _: Foo<#[cfg(not(wrong))]String> = todo!();
+    //~^ ERROR attributes cannot be applied to generic type arguments
+
+    let _: Bar<#[cfg(any())]       'static> = todo!();
+    //~^ ERROR attributes cannot be applied to generic type arguments
+
+    let _: Baz<#[cfg(any())]> = todo!();
+    //~^ ERROR attributes cannot be applied here
+    //~| ERROR type provided when a constant was expected
```
Comment (Kivooeo) [inline tests/ui/parser/attribute-on-type.rs]: Added more edge cases like this, with weird formatting or missing generic argument

File: compiler/rustc_parse/src/parser/attr_wrapper.rs [hunk 7]
```diff
@@ -69,6 +69,10 @@ impl AttrWrapper {
         self.attrs
     }
 
+    pub(super) fn attrs(&self) -> &AttrVec {
+        &self.attrs
+    }
```
Comment (Kivooeo) [inline compiler/rustc_parse/src/parser/attr_wrapper.rs]: Not sure about this, but made my life easier, yes I see `take_for_recovery` above but in case of missing lifetime in generic it gave me delayed bug, so I decided go with this

File: compiler/rustc_parse/src/parser/ty.rs [hunk 8]
```diff
@@ -253,6 +253,24 @@ impl<'a> Parser<'a> {
...
         let allow_qpath_recovery = recover_qpath == RecoverQPath::Yes;
         maybe_recover_from_interpolated_ty_qpath!(self, allow_qpath_recovery);
+        if self.token == token::Pound && self.look_ahead(1, |t| *t == token::OpenBracket) {
+            let attrs_wrapper = self.parse_outer_attributes()?;
+            if !attrs_wrapper.is_empty() {
+                let raw_attrs = attrs_wrapper.take_for_recovery(self.psess);
+
+                let attr_span = raw_attrs[0].span.to(raw_attrs.last().unwrap().span);
+
+                let ty_after_attr = self.parse_ty()?;
```
Comment (Kivooeo) [inline compiler/rustc_parse/src/parser/ty.rs:263]: Also wondering if we are fine with having a `parse_ty` in case of parsing type?

File: tests/ui/parser/attribute-on-type.stderr [hunk 9]
```diff
@@ -0,0 +1,225 @@
...
+LL -     let _assignment: #[attr] i32 = Box::new(1);
+LL +     let _assignment: i32 = Box::new(1);
+   |
+
+error: attributes cannot be applied here
+  --> $DIR/attribute-on-type.rs:44:22
+   |
+LL |     let _assignment: #[attr] = Box::new(1);
+   |                      ^^^^^^^ attributes are not allowed here
+
```
Comment (Kivooeo) [inline tests/ui/parser/attribute-on-type.stderr]: Also added a check for case where we have an attribute but no type was given

**Review by Kivooeo — COMMENTED** [review]
I've called out the potentially surprising bits of this implementation with explanations to help reviewers in mine this and above reviews

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed [hunk 10]
```diff
@@ -1,15 +0,0 @@
...
-    (): Sized;
-//~^^^ ERROR where clauses are not allowed before tuple struct bodies
-
-struct _Demo(pub usize, usize)
-where
-    (): Sized,
-    String: Clone;
-//~^^^^ ERROR where clauses are not allowed before tuple struct bodies
-
-fn main() {}
```
Comment (estebank) [inline tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed]: Can we split this test in two so that we can still have one that is `run-rustfix`? This guards against us accidentally breaking the machine applicable suggestion for the common case in the future.

File: tests/ui/parser/attribute-on-type.rs
Comment (estebank) [inline tests/ui/parser/attribute-on-type.rs:1]: It seems like you could make this `run-rustfix`, right?

File: tests/ui/parser/attribute-on-type.stderr (hunk 9 above)
Comment (estebank) [reply tests/ui/parser/attribute-on-type.stderr]: Ah, this is why it isn't rustfixable. Could we split the test in two?

Comment (Kivooeo) [reply tests/ui/parser/attribute-on-type.stderr]: Two parts is fixable and unfixable parts?

File: tests/ui/parser/attribute-on-type.rs
Comment (Kivooeo) [reply tests/ui/parser/attribute-on-type.rs:1]: We can do this, but I'm not entirely sure we should just go with it right away.

This suggestion wasn't part of the original issue - I added it myself because I noticed it could be implemented relatively easily. So before proceeding further, I'd like to gather some feedback on whether this addition actually makes sense.

If we agree it's a worthwhile change, I can go ahead and make it `rustfix`-able.

```
help: remove attribute from here
   |
LL -     let _: #[attr] &'static str = "123";
LL +     let _: &'static str = "123";
   |
```

File: tests/ui/parser/attribute-on-type.stderr (hunk 9 above)
Comment (estebank) [reply tests/ui/parser/attribute-on-type.stderr]: yes

File: tests/ui/parser/attribute-on-type.rs
Comment (estebank) [reply tests/ui/parser/attribute-on-type.rs:1]: Yes, it is worthwhile to have it, either as it is verbose (although I know some might disagree for cases like these where it is kind of obvious) or as "tool only" (which still produces the suggestion in the json output, making it rustfixable, but not in the terminal output).

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed (hunk 10 above)
Comment (Kivooeo) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed]: There is a problem with that test that I'm not sure about how to fix (and because of why I removed rustfix originally) 

```
failed to apply suggestions for "/rust/tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs" with rustfix: cannot replace slice of data that was already replaced
```

Maybe I somehow can tell it to apply only one fix? or something

Comment (estebank) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed]: We can't "select" a suggestion at the moment. If you have two suggestions pointing at the same piece of the file, we can't currently rustfix test those.

File: tests/ui/parser/attribute-on-type.rs [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+
+    let _: #[attr] &'static str = "123";
+    //~^ ERROR attributes cannot be applied to a type
+
+    let _: Bar<#[cfg(any())] 'static> = todo!();
+    //~^ ERROR attributes cannot be applied to generic type arguments
+
+    let _: Baz<#[cfg(any())] 42> = todo!();
+    //~^ ERROR attributes cannot be applied to generic type arguments
+    //~| ERROR type provided when a constant was expected
```
Comment (fmease) [inline tests/ui/parser/attribute-on-type.rs]: This still doesn't address https://github.com/rust-lang/rust/pull/144195#discussion_r2217997100, I would expect this to emit one error, namely `attributes cannot be applied to generic arguments`. We don't want to expect a type.

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed (hunk 10 above)
Comment (Kivooeo) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.fixed]: > If you have two suggestions pointing at the same piece of the file

Yes, this is the current problem, also I'm not sure if I can split it somehow

File: tests/ui/parser/attribute-on-type.rs (hunk 11 above)
Comment (Kivooeo) [reply tests/ui/parser/attribute-on-type.rs]: I spend last hour trying to fix this, but I don't see a solution not even close, the problem that if we are return error even early before parsing a constant, it continues parsing and go into `parse_angle_args` and if i break it from here because we return TyKind::Err from `parse_generic_arg` it goes into hir anyway... How do I hard say to parser "stop parsing and not go anywhere after this" at some point? I believe that `error.emit().raise_fatal();` is not best way here

**Comment by Kivooeo** [comment]
@fmease, I spent significant time trying to address the secondary error you mentioned. Good news: I solved it for cases where there's something inside the generic. When we have `Baz<#[cfg(any())] 42>`, we can now match on what we parsed and return the right `GenericArg` type. This eliminates the secondary error problem.

But I hit a wall with empty generics like `Baz<#[cfg(any())]>`.

The problem is `ty_generics` is always `None` during parsing. The parser hasn't done name resolution yet as far I understand that process correctly, so it doesn't know what `Baz` actually expects. When we see an empty generic with just an attribute, we have to guess whether to return type, const or lifetime.

Whatever we pick will be wrong sometimes. If I default to `GenericArg::Type`, then `Baz<#[attr]>` gives "type provided when constant expected." If I default to `GenericArg::Const`, then `Foo<#[attr]>` gives "constant provided when type expected."

I can pick a statistical default (types are most common), but some cases will still get secondary errors. Is that acceptable, or do you see another approach I'm missing?

The architectural issue seems fundamental since parsing happens before we know what types expect what kinds of generics.

File: compiler/rustc_parse/src/parser/path.rs [hunk 12]
```diff
@@ -880,6 +880,15 @@ impl<'a> Parser<'a> {
         &mut self,
         ty_generics: Option<&Generics>,
     ) -> PResult<'a, Option<GenericArg>> {
+        let mut attr_span: Option<Span> = None;
+        if self.token == token::Pound && self.look_ahead(1, |t| *t == token::OpenBracket) {
+            // Parse attribute.
+            let attrs_wrapper = self.parse_outer_attributes()?;
+            if !attrs_wrapper.is_empty() {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]: Isn't this always true since we *know* from the check above that there's a `#` followed by a `[`?

File: compiler/rustc_parse/messages.ftl [hunk 13]
```diff
@@ -71,6 +71,17 @@ parse_attr_without_generics = attribute without generic parameters
 parse_attribute_on_param_type = attributes cannot be applied to a function parameter's type
     .label = attributes are not allowed here
 
+parse_attribute_on_type = attributes cannot be applied to a type
```
Comment (fmease) [inline compiler/rustc_parse/messages.ftl]:
```suggestion
parse_attribute_on_type = attributes cannot be applied to types
```

File: compiler/rustc_parse/messages.ftl [hunk 14]
```diff
@@ -71,6 +71,17 @@ parse_attr_without_generics = attribute without generic parameters
...
+    .label = attributes are not allowed here
+    .suggestion = remove attribute from here
+
+parse_attribute_on_generic_type = attributes cannot be applied to generic type arguments
```
Comment (fmease) [inline compiler/rustc_parse/messages.ftl]:
```suggestion
parse_attribute_on_generic_arg = attributes cannot be applied to generic arguments
```

(+ renaming the diag struct)

File: compiler/rustc_parse/src/parser/path.rs (hunk 4 above)
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]: Instead of returning a *poisoned type* (which is undesirable as discussed), simply bail out.

```suggestion
            let diag = self.dcx().create_err(AttributeOnEmptyGeneric { span: attr_span });
            return Err(diag);
```

This will probably lead to the parser stopping entirely after that which is slightly sad but still absolutely acceptable. By its very nature, it flat out prevents nonsensical consequential errors like arg kind mismatches.

---

I think you tried the non-fatal `return Ok(None)` before (I might be misremembering) which led to "nonsensical" arg count mismatches, right? I don't think they're that nonsensical, after all the "slot" is basically empty. So I'd say `return Ok(None)` would be a viable alternative to `return Err(…)` (unless I'm missing something) if you prefer recovery over "surrender".

File: compiler/rustc_parse/src/parser/path.rs [hunk 15]
```diff
@@ -953,6 +966,24 @@ impl<'a> Parser<'a> {
...
+
+            return Ok(Some(match arg {
+                GenericArg::Type(_) => GenericArg::Type(self.mk_ty(attr_span, TyKind::Err(guar))),
+                GenericArg::Const(_) => {
+                    // Create error const expression
+                    let error_expr = self.mk_expr(attr_span, ExprKind::Err(guar));
+                    GenericArg::Const(AnonConst { id: ast::DUMMY_NODE_ID, value: error_expr })
+                }
+                GenericArg::Lifetime(lt) => GenericArg::Lifetime(lt), // Less common case
+            }));
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]: I don't think we need to *taint* or *poison* the arg just because it has attrs. Emitting an error is already sufficient for guaranteeing a failed compilation. This whole `return` could be removed.

**Comment by fmease** [comment]
Thanks for making an effort to address my comments, that's highly appreciated!

> I can pick a statistical default (types are most common), but some cases will still get secondary errors. Is that acceptable, or do you see another approach I'm missing?

Instead of returning a *poisoned type* (so, an `Ok(…TyKind::Err…)`) simply don't recover and bail out with a normal parse error `Err(…)`. For details, see [this review comment](https://github.com/rust-lang/rust/pull/144195#discussion_r2241464731) I just added.

File: compiler/rustc_parse/src/errors.rs [hunk 16]
```diff
@@ -1489,6 +1489,34 @@ pub(crate) struct AttributeOnParamType {
...
+    #[primary_span]
+    #[label]
+    pub span: Span,
+    #[suggestion(code = "", applicability = "machine-applicable", style = "verbose")]
+    pub fix_span: Span,
+}
+
+#[derive(Diagnostic)]
+#[diag(parse_attribute_on_empty_generic)]
+pub(crate) struct AttributeOnEmptyGeneric {
```
Comment (fmease) [inline compiler/rustc_parse/src/errors.rs]:
```suggestion
pub(crate) struct AttributeOnEmptyGenericArg {
```

File: compiler/rustc_parse/src/parser/path.rs (hunk 12 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: Originally it was added more as sanity check, but tested this a bit more I can say that yes that can be removed

File: compiler/rustc_parse/src/parser/path.rs (hunk 15 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: Surprisingly it is worked

File: compiler/rustc_parse/src/errors.rs (hunk 16 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/errors.rs]: Yes, renaming is a good idea but not `GenericArg` just because I'm using this type of error for regular types too, in cases like this `let _: #[x] = 0;`

So I'd rename it into `AttributeOnEmptyType`

File: compiler/rustc_parse/src/parser/path.rs (hunk 4 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: There is a problem with both approaches

`return Err(diag)` stops parsing after the first error, which is slightly overkill because making 5 tests for each case is fundamental wrong 

```
(first error was emitted correctly and now following ones below is not found because parser died :c)
tests/ui/parser/attribute-on-empty.rs:12:5: ERROR: attributes cannot be applied here
tests/ui/parser/attribute-on-empty.rs:15:5: ERROR: attributes cannot be applied here
tests/ui/parser/attribute-on-empty.rs:18:5: ERROR: attributes cannot be applied here
```

And it can't pass current test

`return Ok(None)` is also wrong (which I've tried but worth to mention), it gives suggestion that is makes no sense

```
error[E0107]: struct takes 1 generic argument but 0 generic arguments were supplied
  --> $DIR/attribute-on-empty.rs:12:12
   |
LL |     let _: Foo<#[cfg(not(wrong))]> = todo!();
   |            ^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `T`
  --> $DIR/attribute-on-empty.rs:4:8
   |
LL | struct Foo<T>(T);
   |        ^^^ -
help: add missing generic argument
   |
LL |     let _: Foo<T#[cfg(not(wrong))]> = todo!();
   |                +
```

File: compiler/rustc_parse/messages.ftl (hunk 14 above)
Comment (Kivooeo) [reply compiler/rustc_parse/messages.ftl]: Done

File: compiler/rustc_parse/messages.ftl (hunk 13 above)
Comment (Kivooeo) [reply compiler/rustc_parse/messages.ftl]: Done

File: tests/ui/parser/issues/issue-103143.rs
Comment (Kivooeo) [inline tests/ui/parser/issues/issue-103143.rs:1]: Removing a return with poisoned type now says this, 

```
--- reported in JSON output but not expected in test file ---
tests/ui/parser/issues/issue-103143.rs:2:13: ERROR: cannot find type `y` in this scope [E0412]
tests/ui/parser/issues/issue-103143.rs:2:17: ERROR: cannot find type `z` in this scope [E0412]
---
```

Instead of just  `cannot find value x in this scope` which small but a regression I'd say

File: compiler/rustc_parse/src/parser/path.rs (hunk 15 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: Not fully as wanted, check this https://github.com/rust-lang/rust/pull/144195#discussion_r2242675634

File: compiler/rustc_parse/src/errors.rs [hunk 17]
```diff
@@ -1489,6 +1489,34 @@ pub(crate) struct AttributeOnParamType {
...
+    pub fix_span: Span,
+}
+
+#[derive(Diagnostic)]
+#[diag(parse_attribute_on_generic_type)]
+pub(crate) struct AttributeOnGenericType {
+    #[primary_span]
+    #[label]
+    pub span: Span,
+    #[suggestion(code = "", applicability = "machine-applicable", style = "verbose")]
```
Comment (estebank) [inline compiler/rustc_parse/src/errors.rs]:
```suggestion
    #[suggestion(code = "", applicability = "machine-applicable", style = "tool-only")]
```

File: compiler/rustc_parse/src/errors.rs [hunk 18]
```diff
@@ -1489,6 +1489,34 @@ pub(crate) struct AttributeOnParamType {
     pub span: Span,
 }
 
+#[derive(Diagnostic)]
+#[diag(parse_attribute_on_type)]
+pub(crate) struct AttributeOnType {
+    #[primary_span]
+    #[label]
+    pub span: Span,
+    #[suggestion(code = "", applicability = "machine-applicable", style = "verbose")]
```
Comment (estebank) [inline compiler/rustc_parse/src/errors.rs]: Let's make the suggestions tool-only, so that they still appear as a tooltip in VSCode, but don't appear in the terminal, as "removing the attribute" is the "obvious" solution.

```suggestion
    #[suggestion(code = "", applicability = "machine-applicable", style = "tool-only")]
```

File: compiler/rustc_parse/src/parser/path.rs (hunk 4 above)
Comment (fmease) [reply compiler/rustc_parse/src/parser/path.rs]: > return Err(diag) stops parsing after the first error, which is slightly overkill because making 5 tests for each case is fundamental wrong

`return Err(diag);` is the least hacky and the simplest solution. We can always iterate from here via follow-up PRs. Three test cases are basically identical:

* `let _: Baz<#[cfg(any())]> = todo!();`,
* `let _: Foo<#[cfg(not(wrong))]> = todo!();` and
* `let _: Bar<#[cfg(any())]> = todo!();`.

They should just be combined into one. Lastly, you can move the resulting unified "empty gen arg" case to the end of the file, so rustc still emits the other errors before it bails out. No need for more test files.

To explain myself a bit more, the "empty gen args" case is a lot less likely to happen in practice compared to all the other cases where there's an arg present, so in my eyes it's absolutely justifiable that its logic is more conservative. We can rejoice, free of any headaches, since we know there won't be any invalid or weird consequential diagnostics and since the impl is simple.

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: So completly kill parser?

Comment (fmease) [reply compiler/rustc_parse/src/parser/path.rs]: Yes, indeed. That's exactly what happens for unexpected tokens, so it's completely normal. Parse error recovery is cool and all but if it's infeasible to do robustly it just doesn't make sense to force it. As I said, it can always be improved upon in the future (tweaking spans, intro'ing `GenericArg::Error`, …).

File: compiler/rustc_parse/src/errors.rs (hunk 18 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/errors.rs]: If I do `tool-only` should I still keep `rustfix` on test?

File: compiler/rustc_parse/src/parser/path.rs (hunk 4 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: Sure, then I just keep this `Err(diag)` and also check if keeping returning poisoned arg is fine there

If that's what we are fine with, then I'm pushing this last changes from @estebank and you and that's it I guess

File: compiler/rustc_parse/src/errors.rs (hunk 18 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/errors.rs]: Yeah, I've checked `.fixed` file that generating and it's contains fix, so I guess we keep it

File: tests/ui/parser/issues/issue-103143.rs
Comment (fmease) [reply tests/ui/parser/issues/issue-103143.rs:1]: It's more verbose for sure but personally I don't mind it. After all, these new diagnostics are correct. On the other hand, it's conceivable that `#[a]` is meant to refer to an attribute proc macro that replaces the path with sth. that *does* resolve (but you typoed or forgot to import), so these extra diagnostics would be noise. I'm neutral :shrug:

Comment (Kivooeo) [reply tests/ui/parser/issues/issue-103143.rs:1]: If returning this dummy types is not considered as a bad practice I'd keep it just for consistency

File: compiler/rustc_parse/src/parser/attr_wrapper.rs (hunk 7 above)
Comment (fmease) [inline compiler/rustc_parse/src/parser/attr_wrapper.rs]:
```suggestion
```

The whole point of `AttrWrapper` is to prevent raw access to the underlying `AttrVec` as its documentation states:

> This wrapper prevents direct access to the underlying `ast::AttrVec`.

This method breaks the premise. 

Please use `take_for_recovery`. I don't think https://github.com/rust-lang/rust/pull/144195/files#r2219461926 is still a problem after all the rewrites. And if it still is, it needs to be solved differently.

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs
Comment (fmease) [inline tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs:1]: Could you please keep this a run-rustfix test somehow please? When I created this test back in #106537 it didn't have that `#[allow(dead_code)]` attribute, apparently it was added in #128404. 

I want to keep/restore the original test intention. Can you remove or move the attribute or whatever needs to be done to make this rustfixable again? Thanks!

File: compiler/rustc_parse/src/errors.rs [hunk 19]
```diff
@@ -1489,6 +1489,34 @@ pub(crate) struct AttributeOnParamType {
...
+    #[primary_span]
+    #[label]
+    pub span: Span,
+    #[suggestion(code = "", applicability = "machine-applicable", style = "tool-only")]
+    pub fix_span: Span,
+}
+
+#[derive(Diagnostic)]
+#[diag(parse_attribute_on_generic_type)]
+pub(crate) struct AttributeOnGenericType {
```
Comment (fmease) [inline compiler/rustc_parse/src/errors.rs]:
```suggestion
#[diag(parse_attribute_on_generic_arg)]
pub(crate) struct AttributeOnGenericArg {
```

\+ Fluent file update

File: compiler/rustc_parse/src/parser/path.rs [hunk 20]
```diff
@@ -934,6 +941,9 @@ impl<'a> Parser<'a> {
             }
         } else if self.token.is_keyword(kw::Const) {
             return self.recover_const_param_declaration(ty_generics);
+        } else if let Some(attr_span) = attr_span {
+            let diag = self.dcx().create_err(AttributeOnEmptyType { span: attr_span });
+            return Err(diag);
         } else {
             // Fall back by trying to parse a const-expr expression. If we successfully do so,
             // then we should report an error that it needs to be wrapped in braces.
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs:948]: Two lines below, there's a preexisting `let attrs = self.parse_outer_attributes()?;`. We should be able to drop it and pass the already parsed attrs to the `parse_expr_res`. 

It's not a blocking concern tho ig and it would stop us from recovering from `///` and `/** */` on gen args. Can be done in a follow-up.

File: compiler/rustc_parse/src/parser/path.rs [hunk 21]
```diff
@@ -880,6 +880,13 @@ impl<'a> Parser<'a> {
         &mut self,
         ty_generics: Option<&Generics>,
     ) -> PResult<'a, Option<GenericArg>> {
+        let mut attr_span: Option<Span> = None;
+        if self.token == token::Pound && self.look_ahead(1, |t| *t == token::OpenBracket) {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs:884]: Thinking about it, there's no reason not to include doc comments `///…␊` and `/**…*/` here and in parse_ty (i.e., getting rid of this `if` check and relying on `!is_empty` again) but the diagnostic on master isn't that bad, so not a blocking concern and can be done in a follow-up.

File: compiler/rustc_parse/src/parser/path.rs [hunk 22]
```diff
@@ -953,6 +963,23 @@ impl<'a> Parser<'a> {
                 }
             }
         };
+
+        if let Some(attr_span) = attr_span {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs:966]: I'm a bit nervous about the fact that we emit an error for attributes below all this complex logic above which contains a lot of function exits. I've counted 7 explicit `return`s which naturally won't lead to `AttributeOnGenericType` getting emitted.

Fortunately all of them ultimately lead to parse errors getting emitted I've my eyes don't betray me. However imagine someone updating the function by adding a good (non-erroring) path. It's quite likely that this will lead to attribute unintentionally getting accepted and ignored in this new position.

We could either break up this function, so we have

```rust
fn parse_generic_arg() {
    let attrs = parse_outer_attrs()?;
    let arg = parse_generic_arg_inner()?;
    if !attrs.is_empty() { reject_attrs; }
    Ok(arg)
}
```

or we simply `span_delay_bug` *immediately* after `parse_outer_attrs` if `!attrs.is_empty()` so we at least ICE instead of incorrectly accepting more code.

File: compiler/rustc_parse/src/parser/path.rs [hunk 23]
```diff
@@ -880,6 +880,13 @@ impl<'a> Parser<'a> {
         &mut self,
         ty_generics: Option<&Generics>,
     ) -> PResult<'a, Option<GenericArg>> {
+        let mut attr_span: Option<Span> = None;
+        if self.token == token::Pound && self.look_ahead(1, |t| *t == token::OpenBracket) {
+            // Parse attribute.
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]: As is, the comment is obvious/redundant. I'd rather see sth. like "Recover from attributes (we will reject them later)." above the `if`.

File: compiler/rustc_parse/src/parser/path.rs [hunk 24]
```diff
@@ -953,6 +963,23 @@ impl<'a> Parser<'a> {
...
+
+        if let Some(attr_span) = attr_span {
+            let guar = self.dcx().emit_err(AttributeOnGenericType {
+                span: attr_span,
+                fix_span: attr_span.until(arg.span()),
+            });
+            return Ok(Some(match arg {
+                GenericArg::Type(_) => GenericArg::Type(self.mk_ty(attr_span, TyKind::Err(guar))),
+                GenericArg::Const(_) => {
+                    // Create error const expression
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/path.rs]:
```suggestion
```

redundant

**Review by fmease — CHANGES_REQUESTED** [review]
Final stretch, after that I'll approve.

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs
Comment (Kivooeo) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs:1]: I'd love to, really, but this problem https://github.com/rust-lang/rust/pull/144195#discussion_r2226182651 is very persistent

File: compiler/rustc_parse/src/parser/path.rs (hunk 23 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs]: this comment was added to follow it's function style, there below comments like "// Parse const argument." so I decided to add this one as well for consistency

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs
Comment (fmease) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs:1]: Just remove the `#[allow(dead_code)]` from the field and add `#![allow(dead_code)]` at the top of the file below the comments? Surely this will untangle the replacements?

File: compiler/rustc_parse/src/parser/path.rs (hunk 21 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs:884]: There were some problems without this check (for example it will wait `#` token in a lot of places where it shouldn't be, so this why I hide this behind this check, and not trying to parse attribute everytime is worked pretty well I'd say), and even when I had like just `if self.token == Token::Pound` it still was not fully work

File: compiler/rustc_parse/src/parser/path.rs (hunk 22 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/path.rs:966]: About the `span_delay_bug` this is already handeled by `take_for_recovery` 

```rust
    pub(super) fn take_for_recovery(self, psess: &ParseSess) -> AttrVec {
        psess.dcx().span_delayed_bug(
            self.attrs.get(0).map(|attr| attr.span).unwrap_or(DUMMY_SP),
            "AttrVec is taken for recovery but no error is produced",
        );

        self.attrs
    }
```

So I guess it's fine to keep it as it?

File: tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs
Comment (Kivooeo) [reply tests/ui/parser/recover/recover-where-clause-before-tuple-struct-body-0.rs:1]: Ok, this was simpler that I thought. The devil is in the details

**Comment by Kivooeo** [comment]
Small breakdown what I've changed according to last reviews

* Removed reduant comments
* Renamed `AttributeOnGenericType` to `AttributeOnGenericArg` (and `parse_attribute_on_generic_type` to `parse_attribute_on_generic_arg`)
* Deleted (my favourite function so far) `attrs()` 
* Use `take_for_recovery` instead of `attrs`
* Fixed `.fixed` in some test with really long name
* Exaplained on why we need this check on `#` and `[`

What I did not made

* Refactored function as it was suggested here https://github.com/rust-lang/rust/pull/144195#discussion_r2252693975, because now after changed to `take_for_recovery` it will ICE if someone make changes to this function and break control flow somehow
* Didn't accounted https://github.com/rust-lang/rust/pull/144195#discussion_r2252670758, I mean, I've tried to rewrite function to pass previosly parsed attrbute to this `else` block but then I found that *if* attribute was succesfull parsed at the start of function it will never get inside this `else` block because of `else if` above

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
Thanks a lot!
@bors r=fmease,compiler-errors rollup
