### PR TITLE
Make `lit_to_mir_constant` and `lit_to_const` infallible

### LINKED ISSUE #114317: internal compiler error for type parameter out of range when substituting
### Code

```Rust
#![feature(generic_const_exprs)]

struct A<const B: str = 1, C>;

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (db7ff98a7 2023-07-31)
binary: rustc
commit-hash: db7ff98a72f3e742b641f9cb16d0e8c285e87e9b
commit-date: 2023-07-31
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error: generic parameters with a default must be trailing
 --> 1.rs:3:16
  |
3 | struct A<const B: str = 1, C>;
  |                ^

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> 1.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:900:9: type parameter `C/#1` (C/1) out of range when substituting, args=[]


```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/compiler/rustc_errors/src/lib.rs:1645:9
stack backtrace:
   0:     0x7f7f59d564bc - std::backtrace_rs::backtrace::libunwind::trace::h00560e9152510f67
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7f59d564bc - std::backtrace_rs::backtrace::trace_unsynchronized::h0f27c3665dd0a867
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7f59d564bc - std::sys_common::backtrace::_print_fmt::h5dba0ff3e06fa698
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f7f59d564bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4debeea1996f535b
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7f59dbcbac - core::fmt::rt::Argument::fmt::h1e53d9bbf5a265dd
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/core/src/fmt/rt.rs:138:9
   5:     0x7f7f59dbcbac - core::fmt::write::hcb86202702aeaf68
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f7f59d48b1e - std::io::Write::write_fmt::h6b056feb2ab827f8
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/io/mod.rs:1714:15
   7:     0x7f7f59d562a5 - std::sys_common::backtrace::_print::h63c494f55c85c02e
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f7f59d562a5 - std::sys_common::backtrace::print::h0d84953923cd4383
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f7f59d593fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::h0ded106e3e100970
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/panicking.rs:278:22
  10:     0x7f7f59d59093 - std::panicking::panic_hook_with_disk_dump::h80545efc2b457190
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/panicking.rs:312:9
  11:     0x7f7f58b272e9 - rustc_driver_impl[953ac255d00f3c7f]::install_ice_hook::{closure#0}
  12:     0x7f7f59d59ca0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h005d394de554c94e
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/alloc/src/boxed.rs:2021:9
  13:     0x7f7f59d59ca0 - std::panicking::rust_panic_with_hook::ha35d072680b6716b
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/panicking.rs:733:13
  14:     0x7f7f59099711 - std[cfe24ee53075a1e5]::panicking::begin_panic::<rustc_errors[b1a6789dfd2ebe34]::ExplicitBug>::{closure#0}
  15:     0x7f7f59096cc6 - std[cfe24ee53075a1e5]::sys_common::backtrace::__rust_end_short_backtrace::<std[cfe24ee53075a1e5]::panicking::begin_panic<rustc_errors[b1a6789dfd2ebe34]::ExplicitBug>::{closure#0}, !>
  16:     0x7f7f590de776 - std[cfe24ee53075a1e5]::panicking::begin_panic::<rustc_errors[b1a6789dfd2ebe34]::ExplicitBug>
  17:     0x7f7f590a0594 - <rustc_errors[b1a6789dfd2ebe34]::HandlerInner>::bug::<alloc[9d71a00e6f43b08]::string::String>
  18:     0x7f7f590a0426 - <rustc_errors[b1a6789dfd2ebe34]::Handler>::bug::<alloc[9d71a00e6f43b08]::string::String>
  19:     0x7f7f5912dcec - rustc_middle[23eac342ec155d27]::util::bug::opt_span_bug_fmt::<rustc_span[c85fb125fe1c027]::span_encoding::Span>::{closure#0}
  20:     0x7f7f5912caea - rustc_middle[23eac342ec155d27]::ty::context::tls::with_opt::<rustc_middle[23eac342ec155d27]::util::bug::opt_span_bug_fmt<rustc_span[c85fb125fe1c027]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f7f5912cab8 - rustc_middle[23eac342ec155d27]::ty::context::tls::with_context_opt::<rustc_middle[23eac342ec155d27]::ty::context::tls::with_opt<rustc_middle[23eac342ec155d27]::util::bug::opt_span_bug_fmt<rustc_span[c85fb125fe1c027]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f7f5742fbc0 - rustc_middle[23eac342ec155d27]::util::bug::bug_fmt
  23:     0x7f7f590d76b5 - <rustc_middle[23eac342ec155d27]::ty::generic_args::ArgFolder>::type_param_out_of_range
  24:     0x7f7f56b7e8f6 - <alloc[9d71a00e6f43b08]::vec::Vec<rustc_middle[23eac342ec155d27]::ty::Clause> as alloc[9d71a00e6f43b08]::vec::spec_extend::SpecExtend<rustc_middle[23eac342ec155d27]::ty::Clause, core[24a2ba61524efef7]::iter::adapters::map::Map<core[24a2ba61524efef7]::slice::iter::Iter<(rustc_middle[23eac342ec155d27]::ty::Clause, rustc_span[c85fb125fe1c027]::span_encoding::Span)>, <rustc_middle[23eac342ec155d27]::ty::generics::GenericPredicates>::instantiate_into::{closure#0}>>>::spec_extend
  25:     0x7f7f56b7bc5c - <rustc_middle[23eac342ec155d27]::ty::generics::GenericPredicates>::instantiate_into
  26:     0x7f7f5713d86a - <rustc_trait_selection[eab02bee2fa61d32]::traits::wf::WfPredicates>::nominal_obligations_inner
  27:     0x7f7f57137345 - <rustc_trait_selection[eab02bee2fa61d32]::traits::wf::WfPredicates>::compute
  28:     0x7f7f56e9a3ae - <rustc_trait_selection[eab02bee2fa61d32]::traits::fulfill::FulfillProcessor as rustc_data_structures[1e82c702e6afba98]::obligation_forest::ObligationProcessor>::process_obligation
  29:     0x7f7f56e963f4 - <rustc_data_structures[1e82c702e6afba98]::obligation_forest::ObligationForest<rustc_trait_selection[eab02bee2fa61d32]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[eab02bee2fa61d32]::traits::fulfill::FulfillProcessor>
  30:     0x7f7f5724d44f - <rustc_trait_selection[eab02bee2fa61d32]::traits::engine::ObligationCtxt>::select_all_or_error
  31:     0x7f7f57548bdb - rustc_hir_analysis[2c6ebfa0ec54105a]::check::wfcheck::check_type_defn
  32:     0x7f7f57526568 - rustc_hir_analysis[2c6ebfa0ec54105a]::check::wfcheck::check_well_formed
  33:     0x7f7f56b2951c - rustc_query_impl[c1c3c70d39a20423]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1c3c70d39a20423]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 0usize]>>
  34:     0x7f7f573f0246 - rustc_query_system[85489b7677581133]::query::plumbing::try_execute_query::<rustc_query_impl[c1c3c70d39a20423]::DynamicConfig<rustc_query_system[85489b7677581133]::query::caches::VecCache<rustc_hir[ef37331cc27c2adb]::hir_id::OwnerId, rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[c1c3c70d39a20423]::plumbing::QueryCtxt, false>
  35:     0x7f7f573eff62 - rustc_query_impl[c1c3c70d39a20423]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f7f57e97bac - rustc_data_structures[1e82c702e6afba98]::sync::par_for_each_in::<&[rustc_hir[ef37331cc27c2adb]::hir::ImplItemId], <rustc_middle[23eac342ec155d27]::hir::ModuleItems>::par_impl_items<rustc_hir_analysis[2c6ebfa0ec54105a]::check::wfcheck::check_mod_type_wf::{closure#1}>::{closure#0}>
  37:     0x7f7f57e9798a - rustc_hir_analysis[2c6ebfa0ec54105a]::check::wfcheck::check_mod_type_wf
  38:     0x7f7f57865a4c - rustc_query_impl[c1c3c70d39a20423]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1c3c70d39a20423]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 0usize]>>
  39:     0x7f7f57865a2e - <rustc_query_impl[c1c3c70d39a20423]::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core[24a2ba61524efef7]::ops::function::FnOnce<(rustc_middle[23eac342ec155d27]::ty::context::TyCtxt, rustc_span[c85fb125fe1c027]::def_id::LocalDefId)>>::call_once
  40:     0x7f7f573713ff - rustc_query_system[85489b7677581133]::query::plumbing::try_execute_query::<rustc_query_impl[c1c3c70d39a20423]::DynamicConfig<rustc_query_system[85489b7677581133]::query::caches::VecCache<rustc_span[c85fb125fe1c027]::def_id::LocalDefId, rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[c1c3c70d39a20423]::plumbing::QueryCtxt, false>
  41:     0x7f7f584ad142 - rustc_query_impl[c1c3c70d39a20423]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7f7f57fdb547 - rustc_data_structures[1e82c702e6afba98]::sync::par_for_each_in::<&[rustc_hir[ef37331cc27c2adb]::hir_id::OwnerId], <rustc_middle[23eac342ec155d27]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[2c6ebfa0ec54105a]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  43:     0x7f7f57fda8fe - rustc_hir_analysis[2c6ebfa0ec54105a]::check_crate
  44:     0x7f7f57fd398a - rustc_interface[22a5bdce7fd6e981]::passes::analysis
  45:     0x7f7f58027c3a - rustc_query_impl[c1c3c70d39a20423]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1c3c70d39a20423]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 1usize]>>
  46:     0x7f7f58027c29 - <rustc_query_impl[c1c3c70d39a20423]::query_impl::analysis::dynamic_query::{closure#2} as core[24a2ba61524efef7]::ops::function::FnOnce<(rustc_middle[23eac342ec155d27]::ty::context::TyCtxt, ())>>::call_once
  47:     0x7f7f581cbfa8 - rustc_query_system[85489b7677581133]::query::plumbing::try_execute_query::<rustc_query_impl[c1c3c70d39a20423]::DynamicConfig<rustc_query_system[85489b7677581133]::query::caches::SingleCache<rustc_middle[23eac342ec155d27]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c1c3c70d39a20423]::plumbing::QueryCtxt, false>
  48:     0x7f7f581cbd37 - rustc_query_impl[c1c3c70d39a20423]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  49:     0x7f7f57da39a5 - <rustc_middle[23eac342ec155d27]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[953ac255d00f3c7f]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>
  50:     0x7f7f57da2fd2 - <rustc_interface[22a5bdce7fd6e981]::interface::Compiler>::enter::<rustc_driver_impl[953ac255d00f3c7f]::run_compiler::{closure#1}::{closure#2}, core[24a2ba61524efef7]::result::Result<core[24a2ba61524efef7]::option::Option<rustc_interface[22a5bdce7fd6e981]::queries::Linker>, rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>
  51:     0x7f7f57d9c0a8 - std[cfe24ee53075a1e5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[22a5bdce7fd6e981]::util::run_in_thread_pool_with_globals<rustc_interface[22a5bdce7fd6e981]::interface::run_compiler<core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>, rustc_driver_impl[953ac255d00f3c7f]::run_compiler::{closure#1}>::{closure#0}, core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>
  52:     0x7f7f57d9b82e - <<std[cfe24ee53075a1e5]::thread::Builder>::spawn_unchecked_<rustc_interface[22a5bdce7fd6e981]::util::run_in_thread_pool_with_globals<rustc_interface[22a5bdce7fd6e981]::interface::run_compiler<core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>, rustc_driver_impl[953ac255d00f3c7f]::run_compiler::{closure#1}>::{closure#0}, core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[24a2ba61524efef7]::result::Result<(), rustc_span[c85fb125fe1c027]::ErrorGuaranteed>>::{closure#1} as core[24a2ba61524efef7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7f7f59d64445 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h021e65daf5fb4ee0
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/alloc/src/boxed.rs:2007:9
  54:     0x7f7f59d64445 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7dda744b120f2954
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/alloc/src/boxed.rs:2007:9
  55:     0x7f7f59d64445 - std::sys::unix::thread::Thread::new::thread_start::hcffeb1067f9b6dfb
                               at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7f7f552f96db - start_thread
  57:     0x7f7f5502261f - clone
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/coding/rustc-ice-2023-08-01T01:45:42.590021771Z-10152.txt` to your bug report

query stack during panic:
#0 [check_well_formed] checking that `A` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted
```

</p>
</details>

### LINKED ISSUE #126182: ICE: wfchk: type parameter .. out of range when instantiating, args=`[{const error}]`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

trait Ret {
    type R;
}

struct Cond<const PRED: bool, U, V>(std::marker::PhantomData<U>);

struct RobinHashTable<const MAX_LENGTH: usize, CellIdx = <Cond<{}, usize, u32> as Ret>::R> {}

impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}


````

original:
````rust
#![feature(generic_const_exprs)]

trait Ret {
    type R;
}

struct Cond<const PRED: bool, U, V>(std::marker::PhantomData<U>, );

struct RobinHashTable<
    const MAX_LENGTH: usize,
    CellIdx = <Cond<{  }, usize, u32> as Ret>::R,
> {}

impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}

````

Version information
````
rustc 1.81.0-nightly (13423befc 2024-06-09)
binary: rustc
commit-hash: 13423befc40fffe23ccc6dd06868142cff9428fe
commit-date: 2024-06-09
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0405]: cannot find trait `HashMapBase` in this scope
  --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:15
   |
11 | impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}
   |               ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MAX_LENGTH` in this scope
  --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:55
   |
11 | impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}
   |                                                       ^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
11 | impl<CellIdx, MAX_LENGTH> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}
   |             ++++++++++++

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:78
   |
11 | impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}
   |                                                                              ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs`

error[E0392]: type parameter `V` is never used
 --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:7:34
  |
7 | struct Cond<const PRED: bool, U, V>(std::marker::PhantomData<U>);
  |                                  ^ unused type parameter
  |
  = help: consider removing `V`, referring to it in a field, or using a marker such as `PhantomData`
  = help: if you intended `V` to be a const parameter, use `const V: /* Type */` instead

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:9:64
  |
9 | struct RobinHashTable<const MAX_LENGTH: usize, CellIdx = <Cond<{}, usize, u32> as Ret>::R> {}
  |                                                                ^^ expected `bool`, found `()`

error[E0392]: type parameter `CellIdx` is never used
 --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:9:48
  |
9 | struct RobinHashTable<const MAX_LENGTH: usize, CellIdx = <Cond<{}, usize, u32> as Ret>::R> {}
  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unused type parameter
  |
  = help: consider removing `CellIdx`, referring to it in a field, or using a marker such as `PhantomData`
  = help: if you intended `CellIdx` to be a const parameter, use `const CellIdx: /* Type */` instead

error[E0747]: unresolved item provided when a constant was expected
  --> /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:55
   |
11 | impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<MAX_LENGTH, CellIdx> {}
   |                                                       ^^^^^^^^^^
   |
help: if this generic argument was intended as a const parameter, surround it with braces
   |
11 | impl<CellIdx> HashMapBase<CellIdx> for RobinHashTable<{ MAX_LENGTH }, CellIdx> {}
   |                                                       +            +

thread 'rustc' panicked at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/compiler/rustc_type_ir/src/binder.rs:721:9:
type parameter `CellIdx/#1` (CellIdx/#1/1) out of range when instantiating, args=[{const error}]
stack backtrace:
   0:     0x7a5d7b004f15 - std::backtrace_rs::backtrace::libunwind::trace::hc269bfc84eb36e15
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7a5d7b004f15 - std::backtrace_rs::backtrace::trace_unsynchronized::hece6c4d7a612f15c
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7a5d7b004f15 - std::sys_common::backtrace::_print_fmt::h930816c48dbbaf0d
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7a5d7b004f15 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h97d89f938a66f30a
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7a5d7b055c5b - core::fmt::rt::Argument::fmt::h24d0a17c8139d598
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/core/src/fmt/rt.rs:165:63
   5:     0x7a5d7b055c5b - core::fmt::write::ha35330775473ce1b
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/core/src/fmt/mod.rs:1168:21
   6:     0x7a5d7aff9bef - std::io::Write::write_fmt::h43aadac447ba03dc
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/io/mod.rs:1835:15
   7:     0x7a5d7b004cee - std::sys_common::backtrace::_print::h26d59bbced8ffda1
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7a5d7b004cee - std::sys_common::backtrace::print::ha970e07731260ee4
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7a5d7b007729 - std::panicking::default_hook::{{closure}}::hf9289ff1d818f2e0
  10:     0x7a5d7b0074ca - std::panicking::default_hook::h63336b0533014868
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/panicking.rs:298:9
  11:     0x7a5d777d7890 - std[6fb11aa7feb46831]::panicking::update_hook::<alloc[34e4e5571b6f83d9]::boxed::Box<rustc_driver_impl[ffae40d8b8d5c74b]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7a5d7b007e5b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf78a7244bd2d88ce
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/alloc/src/boxed.rs:2077:9
  13:     0x7a5d7b007e5b - std::panicking::rust_panic_with_hook::h0b57c3ef0581f5fb
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/panicking.rs:799:13
  14:     0x7a5d7b007bd4 - std::panicking::begin_panic_handler::{{closure}}::h3bf6c54ce49c26c2
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/panicking.rs:664:13
  15:     0x7a5d7b0053d9 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ebf041d380b46ed
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7a5d7b007907 - rust_begin_unwind
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/panicking.rs:652:5
  17:     0x7a5d7b0521f3 - core::panicking::panic_fmt::hea580bf65fedee8d
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/core/src/panicking.rs:72:14
  18:     0x7a5d778da789 - <rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::type_param_out_of_range
  19:     0x7a5d792ee2ea - <rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::fold_ty
  20:     0x7a5d792ed0a6 - <&rustc_middle[d7453cc9d163243f]::ty::list::RawList<(), rustc_middle[d7453cc9d163243f]::ty::generic_args::GenericArg> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFoldable<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>
  21:     0x7a5d79e249ae - <rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::fold_const.warm
  22:     0x7a5d792ee267 - <rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::fold_ty
  23:     0x7a5d792ed015 - <&rustc_middle[d7453cc9d163243f]::ty::list::RawList<(), rustc_middle[d7453cc9d163243f]::ty::generic_args::GenericArg> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFoldable<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::try_fold_with::<rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>
  24:     0x7a5d792ed6ac - <rustc_type_ir[f61c5ba52dab4f78]::binder::ArgFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt> as rustc_type_ir[f61c5ba52dab4f78]::fold::TypeFolder<rustc_middle[d7453cc9d163243f]::ty::context::TyCtxt>>::fold_ty
  25:     0x7a5d78f0c939 - <<dyn rustc_hir_analysis[1c7651ca8b7a2f4f]::hir_ty_lowering::HirTyLowerer>::lower_generic_args_of_path::{closure#0}::GenericArgsCtxt as rustc_hir_analysis[1c7651ca8b7a2f4f]::hir_ty_lowering::GenericArgsLowerer>::inferred_kind
  26:     0x7a5d767cdd2a - <dyn rustc_hir_analysis[1c7651ca8b7a2f4f]::hir_ty_lowering::HirTyLowerer>::lower_path
  27:     0x7a5d79199197 - <dyn rustc_hir_analysis[1c7651ca8b7a2f4f]::hir_ty_lowering::HirTyLowerer>::lower_ty_common::{closure#0}
  28:     0x7a5d7674409b - rustc_hir_analysis[1c7651ca8b7a2f4f]::collect::type_of::type_of
  29:     0x7a5d78dd0c2a - rustc_query_impl[1410ec32161e1f70]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1410ec32161e1f70]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7a5d78dcf81b - rustc_query_system[71bc59e02034b9b1]::query::plumbing::try_execute_query::<rustc_query_impl[1410ec32161e1f70]::DynamicConfig<rustc_query_system[71bc59e02034b9b1]::query::caches::DefIdCache<rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1410ec32161e1f70]::plumbing::QueryCtxt, false>
  31:     0x7a5d78dcf3bb - rustc_query_impl[1410ec32161e1f70]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7a5d78f9efcf - <rustc_hir_analysis[1c7651ca8b7a2f4f]::collect::CollectItemTypesVisitor as rustc_hir[b11a8aea6cdb8d1a]::intravisit::Visitor>::visit_item
  33:     0x7a5d7675f6c0 - rustc_hir_analysis[1c7651ca8b7a2f4f]::check::wfcheck::check_well_formed
  34:     0x7a5d791c52a9 - rustc_query_impl[1410ec32161e1f70]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1410ec32161e1f70]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7a5d791c5526 - rustc_query_system[71bc59e02034b9b1]::query::plumbing::try_execute_query::<rustc_query_impl[1410ec32161e1f70]::DynamicConfig<rustc_query_system[71bc59e02034b9b1]::query::caches::VecCache<rustc_hir[b11a8aea6cdb8d1a]::hir_id::OwnerId, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1410ec32161e1f70]::plumbing::QueryCtxt, false>
  36:     0x7a5d791c5286 - rustc_query_impl[1410ec32161e1f70]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7a5d791c6009 - rustc_hir_analysis[1c7651ca8b7a2f4f]::check::wfcheck::check_mod_type_wf
  38:     0x7a5d791c5e4f - rustc_query_impl[1410ec32161e1f70]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1410ec32161e1f70]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7a5d7972c1fa - rustc_query_system[71bc59e02034b9b1]::query::plumbing::try_execute_query::<rustc_query_impl[1410ec32161e1f70]::DynamicConfig<rustc_query_system[71bc59e02034b9b1]::query::caches::DefaultCache<rustc_span[3fc851bceb4adf61]::def_id::LocalModDefId, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1410ec32161e1f70]::plumbing::QueryCtxt, false>
  40:     0x7a5d7972bfb5 - rustc_query_impl[1410ec32161e1f70]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7a5d78ff37ea - rustc_hir_analysis[1c7651ca8b7a2f4f]::check_crate
  42:     0x7a5d791ba8be - rustc_interface[f4a2ea540be086e6]::passes::analysis
  43:     0x7a5d791ba41b - rustc_query_impl[1410ec32161e1f70]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1410ec32161e1f70]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7a5d799cdda5 - rustc_query_system[71bc59e02034b9b1]::query::plumbing::try_execute_query::<rustc_query_impl[1410ec32161e1f70]::DynamicConfig<rustc_query_system[71bc59e02034b9b1]::query::caches::SingleCache<rustc_middle[d7453cc9d163243f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1410ec32161e1f70]::plumbing::QueryCtxt, false>
  45:     0x7a5d799cdb0f - rustc_query_impl[1410ec32161e1f70]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7a5d7984f692 - rustc_interface[f4a2ea540be086e6]::interface::run_compiler::<core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>, rustc_driver_impl[ffae40d8b8d5c74b]::run_compiler::{closure#0}>::{closure#1}
  47:     0x7a5d79804f67 - std[6fb11aa7feb46831]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f4a2ea540be086e6]::util::run_in_thread_with_globals<rustc_interface[f4a2ea540be086e6]::util::run_in_thread_pool_with_globals<rustc_interface[f4a2ea540be086e6]::interface::run_compiler<core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>, rustc_driver_impl[ffae40d8b8d5c74b]::run_compiler::{closure#0}>::{closure#1}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>::{closure#0}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>
  48:     0x7a5d79804d2a - <<std[6fb11aa7feb46831]::thread::Builder>::spawn_unchecked_<rustc_interface[f4a2ea540be086e6]::util::run_in_thread_with_globals<rustc_interface[f4a2ea540be086e6]::util::run_in_thread_pool_with_globals<rustc_interface[f4a2ea540be086e6]::interface::run_compiler<core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>, rustc_driver_impl[ffae40d8b8d5c74b]::run_compiler::{closure#0}>::{closure#1}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>::{closure#0}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b05d301dbc549eb0]::result::Result<(), rustc_span[3fc851bceb4adf61]::ErrorGuaranteed>>::{closure#2} as core[b05d301dbc549eb0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7a5d7b011e4b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he97bec9b57692eb6
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/alloc/src/boxed.rs:2063:9
  50:     0x7a5d7b011e4b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5ef09d5fe1e7a265
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/alloc/src/boxed.rs:2063:9
  51:     0x7a5d7b011e4b - std::sys::pal::unix::thread::Thread::new::thread_start::h71e84f01f2e92ad3
                               at /rustc/13423befc40fffe23ccc6dd06868142cff9428fe/library/std/src/sys/pal/unix/thread.rs:108:17
  52:     0x7a5d744a6ded - <unknown>
  53:     0x7a5d7452a0dc - <unknown>
  54:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (13423befc 2024-06-09) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [type_of] computing type of `<impl at /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:1: 11:75>`
#1 [check_well_formed] checking that `<impl at /tmp/icemaker_global_tempdir.7MOg4WzJ7ybU/rustc_testrunner_tmpdir_reporting.HyzgwWnQ2tfu/mvce.rs:11:1: 11:75>` is well-formed
end of query stack
error: aborting due to 7 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0392, E0405, E0412, E0601, E0747.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### PR DESCRIPTION
**Pull request by oli-obk**
My motivation for this change is just that it's annoying to check everywhere, especially since all but one call site was just ICEing on errors anyway right there.

They can still fail, but now just return an error constant instead of having the caller handle the error.

fixes #114317 
fixes #126182

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2265,18 +2265,11 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
-                        format!("try_lower_anon_const_lit: couldn't lit_to_const {e:?}"),
-                    );
-                }
+
+            // Allow the `ty` to be an alias type, though we cannot handle it here, we just go through
+            // the more expensive anon const code path.
+            if !lit_input.ty.has_aliases() {
+                return Some(tcx.at(expr.span).lit_to_const(lit_input));
             }
         }
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2274]: cc @BoxyUwU @Jaic1 Instead of running lit_to_const and skipping the error I'm now just skipping `lit_to_const` entirely for the alias case.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -2265,18 +2265,11 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
         if let Some(lit_input) = lit_input {
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2265]: nit: can you change this to avoid explicit returns? e.g. by just using a `lit_input.filter(has_aliases).map(lit_to_const)`

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs [hunk 3]
```diff
@@ -154,20 +146,18 @@ fn lit_to_mir_constant<'tcx>(
...
-            .ok_or_else(|| {
-                LitToConstError::Reported(
-                    tcx.dcx()
-                        .delayed_bug(format!("couldn't parse float literal: {:?}", lit_input.lit)),
-                )
-            })?,
+            trunc(if neg { (n.get() as i128).overflowing_neg().0 as u128 } else { n.get() })
+        }
+        (ast::LitKind::Float(n, _), ty::Float(fty)) => {
+            parse_float_into_constval(*n, *fty, neg).unwrap()
```
Comment (lcnr) [inline compiler/rustc_mir_build/src/builder/expr/as_constant.rs:152]: delayed_bug to bug, it's unreachable I guess? :grin: though given we've got no tests for that, I don't mind merging this and reacting to a fuzzer ICE if it's reachable

**Review by lcnr — COMMENTED** [review]
gamer

r=me after nits

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs (hunk 3 above)
Comment (oli-obk) [reply compiler/rustc_mir_build/src/builder/expr/as_constant.rs:152]: yea, I looked into this before the holidays and if memory serves right the parser ensures we don't get anything that could fail here.

**Comment by matthiaskrgr** [comment]
@bors r-
 needs rebase
