### PR TITLE
Infer type in irrefutable slice patterns with fixed length as array 

### LINKED ISSUE #76342: Irrefutable slice patterns should be inferred as arrays of that length
Simple demo <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5b0acd8b21c773c9c4a3ff73bc7a030e>:
```rust
#![allow(unused_variables)]
struct Zeroes;
impl Into<[usize; 2]> for Zeroes {
    fn into(self) -> [usize; 2] { [0; 2] }
}
impl Into<[usize; 3]> for Zeroes {
    fn into(self) -> [usize; 3] { [0; 3] }
}
impl Into<[usize; 4]> for Zeroes {
    fn into(self) -> [usize; 4] { [0; 4] }
}
fn main() {
    let [a, b, c] = Zeroes.into(); // ERROR: type annotations needed
    let [d, e, f]: [_; 3] = Zeroes.into(); // Works great
}
```

This is presumably not happening because slice patterns in refutable patterns can be more than just an array of that exact size, but there's no other option for **ir**refutable patterns.

This would be particularly helpful as we're getting more and more `[T; N]: TryFrom<_>` implementations with const generics.  See the example in https://github.com/rust-lang/rust/pull/76310 for the place I first noticed this not working the way I'd hoped.

Zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Type.20inferrence.20.26.20irrefutable.20slice.20patterns/near/209052937

### PR DESCRIPTION
**Pull request by b-naber**
Fixes https://github.com/rust-lang/rust/issues/76342

In irrefutable slice patterns with a fixed length, we can infer the type as an array type. We now choose to prefer some implementations over others, e.g. in:

``` 
struct Zeroes;

const ARR: [usize; 2] = [0; 2];
const ARR2: [usize; 2] = [2; 2];

impl Into<&'static [usize; 2]> for Zeroes {
    fn into(self) -> &'static [usize; 2] {
        &ARR
    }
}

impl Into<&'static [usize]> for Zeroes {
    fn into(self) -> &'static [usize] {
        &ARR2
    }
}

fn main() {
    let &[a, b] = Zeroes.into();
}
```

We now prefer the impl candidate `impl Into<&'static [usize; 2]> for Zeroes`, it's not entirely clear to me that this is correct, but given that the slice impl would require a type annotation anyway, this doesn't seem unreasonable.

r? @lcnr

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -1941,6 +1966,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         expected: Ty<'tcx>,
         def_bm: BindingMode,
         ti: TopInfo<'tcx>,
+        decl_ctxt: Option<DeclContext>,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:1969]: can these three arguments be merged into a shared struct? I think they get mostly passed down together and we're at a point where the argument list is quite hard to read

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 2]
```diff
@@ -2022,6 +2049,63 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    ///    fn main() {
+    ///        let &[a, b]: &[usize] = Zeroes.into() else {
+    ///           ..
+    ///        };
+    ///    }
+    /// ```
+    ///
+    /// If we're in an irrefutable pattern we prefer the array impl candidate given that
+    /// the slice impl candidate would be be rejected anyway (if no ambiguity existed).
+    fn decl_allows_array_type_infer(&self, decl_ctxt: Option<DeclContext>) -> bool {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:2101]: it feels like this should be named the more general `fn is_irrefutable_pattern`?

File: compiler/rustc_hir_typeck/src/gather_locals.rs [hunk 3]
```diff
@@ -19,19 +37,28 @@ pub(super) struct Declaration<'a> {
     pub span: Span,
     pub init: Option<&'a hir::Expr<'a>>,
     pub els: Option<&'a hir::Block<'a>>,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/gather_locals.rs:39]: feels like `els` should be part of `Origin` instead of being a separate field

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 4]
```diff
@@ -135,30 +143,27 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-    fn check_pat(
-        &self,
-        pat: &'tcx Pat<'tcx>,
-        expected: Ty<'tcx>,
-        def_bm: BindingMode,
-        ti: TopInfo<'tcx>,
-    ) {
+    #[instrument(level = "debug", skip(self, pat_info))]
+    fn check_pat(&self, pat: &'tcx Pat<'tcx>, expected: Ty<'tcx>, pat_info: PatInfo<'tcx, '_>) {
+        let PatInfo { binding_mode: def_bm, top_info: ti, decl_origin } = pat_info;
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:166]: please don't destructure `pat_info` if you then rebuild it for nested calls

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 5]
```diff
@@ -581,9 +623,10 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         var_id: HirId,
         sub: Option<&'tcx Pat<'tcx>>,
         expected: Ty<'tcx>,
-        def_bm: BindingMode,
-        ti: TopInfo<'tcx>,
+        pat_info: PatInfo<'tcx, '_>,
     ) -> Ty<'tcx> {
+        let PatInfo { binding_mode: def_bm, top_info: ti, decl_origin } = pat_info;
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:628]: same here

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 6]
```diff
@@ -841,17 +888,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         fields: &'tcx [hir::PatField<'tcx>],
         has_rest_pat: bool,
         expected: Ty<'tcx>,
-        def_bm: BindingMode,
-        ti: TopInfo<'tcx>,
+        pat_info: PatInfo<'tcx, '_>,
     ) -> Ty<'tcx> {
+        let PatInfo { binding_mode: def_bm, top_info: ti, decl_origin } = pat_info;
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:893]: and here

**Review by lcnr — COMMENTED** [review]
happy with the changes to allow arrays, the changes with `PatInfo` feel like they're only halfway '^^

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 4 above)
Comment (b-naber) [reply compiler/rustc_hir_typeck/src/pat.rs:166]: Note that we create a new `def_bm` in this method later.

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/pat.rs:166]: can you in this case instead shaddow `pat_info` after we have the new `def_bm`?

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 7]
```diff
@@ -2022,6 +2060,64 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    ///        };
+    ///    }
+    /// ```
+    ///
+    /// If we're in an irrefutable pattern we prefer the array impl candidate given that
+    /// the slice impl candidate would be be rejected anyway (if no ambiguity existed).
+    fn pat_is_irrefutable(&self, decl_origin: Option<DeclOrigin<'_>>) -> bool {
+        if let Some(decl_origin) = decl_origin {
+            decl_origin.try_get_else().is_none()
+                && matches!(decl_origin, DeclOrigin::LocalDecl { .. })
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:2115]:
```suggestion
           match decl_origin {
               DeclOrigin::LocalDecl { els: None } => true,
               DeclOrigin::LOcalDecl { else: Some(_) } | DeclOrigin::LetExpr => false,
           }
```

File: tests/ui/array-slice-vec/slice-pat-type-mismatches.rs [hunk 8]
```diff
@@ -15,22 +15,24 @@ fn main() {
...
-        [] => {}
+    match does_not_exist {
+        //~^ ERROR cannot find value `does_not_exist` in this scope
+        [] => {} // ERROR cannot find value `does_not_exist` in this scope
     };
 }
 
 fn another_fn_to_avoid_suppression() {
-    match Default::default()
+    match Default
```
Comment (lcnr) [inline tests/ui/array-slice-vec/slice-pat-type-mismatches.rs:33]: why this change?

File: tests/ui/pattern/issue-76342.rs [hunk 9]
```diff
@@ -0,0 +1,22 @@
+// check-pass
```
Comment (lcnr) [inline tests/ui/pattern/issue-76342.rs:1]:
```suggestion
// check-pass

// Test that we infer the expected type of a pattern to an array of the given length.
```

File: tests/ui/pattern/slice-pattern-refutable.rs [hunk 10]
```diff
@@ -0,0 +1,34 @@
+#![allow(unused_variables)]
+
```
Comment (lcnr) [inline tests/ui/pattern/slice-pattern-refutable.rs:2]:
```suggestion
// Test that we do not infer the expected types of patterns to an array
// if we're in a refutable pattern.
```

File: tests/ui/pattern/slice-patterns-ambiguity.rs [hunk 11]
```diff
@@ -0,0 +1,47 @@
+#![allow(unused_variables)]
+
+struct Zeroes;
```
Comment (lcnr) [inline tests/ui/pattern/slice-patterns-ambiguity.rs:3]: not sure whether this test tests anything specific :thinking: might make snese to only have this as a check-pass test for irrefutable let?

please add the test separately where we incompletely a pattern as an array even though it should be a slice https://github.com/rust-lang/rust/issues/76342#issuecomment-1578787870

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 12]
```diff
@@ -2039,9 +2135,19 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         slice: Option<&'tcx Pat<'tcx>>,
         after: &'tcx [Pat<'tcx>],
         expected: Ty<'tcx>,
-        def_bm: BindingMode,
-        ti: TopInfo<'tcx>,
+        pat_info: PatInfo<'tcx, '_>,
     ) -> Ty<'tcx> {
+        // If the pattern is irrefutable and `expected` is an infer ty, we try to equate it
+        // to an array if the given pattern allows it. See issue #76342
+        if self.pat_is_irrefutable(pat_info.decl_origin) && expected.is_ty_var() {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:2142]: please move this `if` until after the `structurally_resolve_type` as it can otherwise miss info about the type of expected.

Comment (b-naber) [reply compiler/rustc_hir_typeck/src/pat.rs:2117]: The new tests previously failed because `structurally_resolve_type` returned an inference error.

File: tests/ui/pattern/slice-patterns-ambiguity.rs (hunk 11 above)
Comment (b-naber) [reply tests/ui/pattern/slice-patterns-ambiguity.rs:3]: > please add the test separately where we incompletely a pattern as an array even though it should be a slice https://github.com/rust-lang/rust/issues/76342#issuecomment-1578787870

Sorry, I don't understand what you're to say here. The quote does not seem to relate to the comment you link to.

Comment (lcnr) [reply tests/ui/pattern/slice-patterns-ambiguity.rs:3]: this test:
```rust
struct Foo(u32);
struct Bar;
impl Into<&'static Foo> for Bar {
    fn into(self) -> &'static Foo { &Foo(1) }
}
impl Into<Foo> for Bar {
    fn into(self) -> Foo { Foo(1) }
}

fn ty<T>(_: T) {
    println!("{}", std::any::type_name::<T>());
}

fn main() {
    let Foo(i) = Bar.into();
    ty(i); // u32
    let Foo(j) = <Bar as Into<&'static Foo>>::into(Bar);
    ty(j); // &u32
    let Foo(k): Foo = Bar.into();
    ty(k); // u32
    let Foo(l): &Foo = Bar.into();
    ty(l); // &u32
}
```

Comment (lcnr) [reply tests/ui/pattern/slice-patterns-ambiguity.rs:3]: woops, replacing `Foo` with an array :sweat:
```rust
#![allow(unused_variables)]
struct Zeroes;
impl Into<&'static [usize; 3]> for Zeroes {
    fn into(self) -> &'static [usize; 3] { &[0; 3] }
}
impl Into<[usize; 3]> for Zeroes {
    fn into(self) -> [usize; 3] { [0; 3] }
}
fn main() {
    let [a, b, c] = Zeroes.into();
    let [d, e, f] = <Zeroes as Into<&'static [usize; 3]>::into();
    let &[g, h, i] = Zeroes.into();
    let [j, k, l]: [usize; _] = Zeroes.into();
    let [m, n, o]: &[usize; _] = Zeroes.into();

}
```

File: tests/ui/pattern/issue-76342.rs [hunk 13]
```diff
@@ -0,0 +1,25 @@
...
+
```
Comment (lcnr) [inline tests/ui/pattern/issue-76342.rs:2]: ah, two more things:

- can you rename this file to `slice-patterns-irrefutable.rs`?
- can you add the following function to this test
```rust
use std::array::TryFromSliceError;
fn array_try_from(x: &[usize]) -> Result<usize, TryFromSliceError> {
    let [a, b] = x.try_into()?;
    Ok(a + b)
}
```

**Comment by lcnr** [comment]
This PR infers the type of slice pattern in irrefutable positions, i.e. let bindings, to an array with the length of the pattern. This inference incompletely assumes that no match ergonomics are taking place and the type of the pattern is an array, not a reference to an array. This matches the behavior of other patterns: https://github.com/rust-lang/rust/issues/76342#issuecomment-1578787870.

This behavior is generally desirable when using `TryFrom`, i.e. `let [a, b] = slice.try_into()?;`

```rust
#![allow(unused_variables)]
struct Zeroes;
impl Into<&'static [usize; 3]> for Zeroes {
    fn into(self) -> &'static [usize; 3] { &[0; 3] }
}
impl Into<[usize; 3]> for Zeroes {
    fn into(self) -> [usize; 3] { [0; 3] }
}
fn main() {
    let [a, b, c] = Zeroes.into();
    let [d, e, f] = <Zeroes as Into<&'static [usize; 3]>::into();
    let &[g, h, i] = Zeroes.into();
    let [j, k, l]: [usize; _] = Zeroes.into();
    let [m, n, o]: &[usize; _] = Zeroes.into();

    // check the binding mode of these patterns:
    let _: &[usize] = &[a, b, c, g, h, i, j, k, l];
    let _: &[&usize] = &[d, e, f, m, n, o];

}
```

Given that this is a detail of type inference, I think this is full t-types, cc @rust-lang/lang 

@rfcbot fcp merge

File: tests/ui/pattern/slice-patterns-ambiguity.rs (hunk 11 above)
Comment (b-naber) [reply tests/ui/pattern/slice-patterns-ambiguity.rs:3]: > `let [d, e, f] = <Zeroes as Into<&'static [usize; 3]>::into();`

Again not sure what you're trying to do here. This doesn't look like valid rust code to me. `into` takes a receiver.

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 12 above)
Comment (b-naber) [reply compiler/rustc_hir_typeck/src/pat.rs:2117]: I'm not convinced this is necessary. We only get into the `demand_eqtype` call when the pattern is irrefutable, how exactly would trying to structurally resolve the type help here? Afaict either there's a type annotation and we ignore all the logic introduced in this PR or there is none, in which case `expected` is just an unresolvable type variable afaict. Since we have to resolve the type after the `demand_eqtype` call anyway (since we still have to resolve the inner type after hinting that we're looking for `[_; n]`) I don't see why we want `try_structurally_resolve_type` first. Can you explain why that would be helpful/necessary?

File: tests/ui/pattern/slice-patterns-ambiguity.rs (hunk 11 above)
Comment (lcnr) [reply tests/ui/pattern/slice-patterns-ambiguity.rs:3]: it can be valid by adding `Zeroes` as a receiver

```rust
    let [d, e, f] = <Zeroes as Into<&'static [usize; 3]>>::into(Zeroes);
```

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 12 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/pat.rs:2117]: we get into the `demand_eqtype` call when the pattern is irrefutable **and** the expected type is an inference variable. Whether the expected type is an inference variable can depend on structrally resolving it.

I can't imagine how you'd get to a point where it matters, but generally looking at the `kind()` of a type and then using `structurally_resolve` or `shallow_resolve` or whatever  is always sus. Either the `resolve` is a noop, in which case it should be removed, or it can change the `kind()` of the type, in which case looking at the type before the resovle call is buggy.

Ah, nearly forgot: can you add tests for destructing assignments, i.e. what happens with the following
```rust
fn main() {
    let a: i32;
    let b;
    [a, b] = Default::default();
}
```

we should treat these as also being irrefutable and this example should compile i think

**Comment by lcnr** [comment]
final nits, then r=me

**Comment by pietroalbini** [comment]
@bors retry

Yield priority to https://github.com/rust-lang/rust/pull/114410
