### PR TITLE
transmutability: uninit transition matches unit byte only

### LINKED ISSUE #140337: transmutability: unexpected behaviour when both init and uninit transitions are present
```rust
#![feature(transmutability)]
use std::mem::{Assume, MaybeUninit, TransmuteFrom};

pub fn is_transmutable<Src, Dst>() where Dst: TransmuteFrom<Src, { Assume::SAFETY }>{}

#[derive(Copy, Clone)]
#[repr(u8)]
enum B0 { Value = 0 }

#[derive(Copy, Clone)]
#[repr(u8)]
enum B1 { Value = 1 }

fn main() {
    is_transmutable::<(B0, B0), MaybeUninit<(B0, B0)>>(); // ok
    is_transmutable::<(B0, B0), MaybeUninit<(B0, B1)>>(); // unexpected error: `(B0, B0)` cannot be safely transmuted into `MaybeUninit<(B0, B1)>`
    is_transmutable::<(B0, B0), MaybeUninit<(B1, B0)>>(); // ok
    is_transmutable::<(B0, B0), MaybeUninit<(B1, B1)>>(); // ok
}
```

cc @jswrenn

### PR DESCRIPTION
**Pull request by tmiasko**
The previous implementation was inconsistent about transitions that
apply for an init byte. For example, when answering a query, an init
byte could use corresponding init transition. Init byte could also use
uninit transition, but only when the corresponding init transition was
absent. This behaviour was incompatible with DFA union construction.

Define an uninit transition to match an uninit byte only and update
implementation accordingly. To describe that `Tree::uninit` is valid
for any value, build an automaton that accepts any byte value.

Additionally, represent byte ranges uniformly as a pair of integers to
avoid special case for uninit byte.

Fixes #140337.
Fixes https://github.com/rust-lang/rust/pull/140168#discussion_r2061609691.

r? @jswrenn @joshlf

### CODE REVIEW

File: compiler/rustc_transmute/src/layout/dfa.rs [hunk 1]
```diff
@@ -334,95 +325,31 @@ where
...
-        // DFA, these must be non-overlapping with one another.
-        runs: SmallVec<[Run<S>; 1]>,
-        // The edge labeled with the uninit byte, if any.
+        // A sequence of byte edges with contiguous byte values and a common
+        // destination is stored as a single run.
         //
-        // FIXME(@joshlf): Make `State` a `NonZero` so that this is NPO'd.
-        uninit: Option<S>,
+        // Runs are non-empty, non-overlapping, and stored in ascending order.
+        runs: SmallVec<[(Byte, S); 1]>,
```
Comment (joshlf) [inline compiler/rustc_transmute/src/layout/dfa.rs:339]: Can you investigate the performance implication of this change? I worry that, for large types, storing runs as pairs of `u16`s rather than as pairs of `u8`s may degrade performance by worsening cache locality.

If that's problematic, another option would be to store `u8`s and have some nonsense sentinal value be used to represent uninit (e.g. `(start: 1, end: 0)`).

File: compiler/rustc_transmute/src/layout/dfa.rs [hunk 2]
```diff
@@ -334,95 +325,31 @@ where
...
     }
 
     impl<S> EdgeSet<S> {
-        pub(crate) fn new(byte: Byte, dst: S) -> Self {
-            match byte.range() {
-                Some(range) => Self { runs: smallvec![Run::new(range, dst)], uninit: None },
-                None => Self { runs: SmallVec::new(), uninit: Some(dst) },
+        pub(crate) fn new(range: Byte, dst: S) -> Self {
+            let mut this = Self { runs: SmallVec::new() };
+            if !range.is_empty() {
```
Comment (joshlf) [inline compiler/rustc_transmute/src/layout/dfa.rs:345]: We could also add the invariant to `Byte` that it never stores an empty range, and then we could avoid this check.

File: compiler/rustc_transmute/src/layout/dfa.rs [hunk 3]
```diff
@@ -478,95 +385,105 @@ mod edge_set {
...
 
-                if idx >= s_end {
-                    s = s_rest;
+        let ret;
+        match (self.xs.peek_mut(), self.ys.peek_mut()) {
+            (None, None) => {
+                ret = None;
+            }
+            (Some(x), None) => {
+                ret = Some((x.0, (Some(x.1), None)));
```
Comment (joshlf) [inline compiler/rustc_transmute/src/layout/dfa.rs:444]: Style nit to make this a bit more readable (so you don't have to consult the types above to see what `.0` and `.1` are):

```suggestion
            (Some((byte, state)), None) => {
                ret = Some((byte, (Some(state), None)));
```

Same suggestion in in the `(None, Some(_))` and `(Some(_), Some(_))` arms below.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs [hunk 4]
```diff
@@ -153,230 +148,136 @@ where
...
-                if let Some(dst_state_prime) = self.dst.get_uninit_edge_dst(dst_state) {
-                    self.answer_memo(cache, src_state, dst_state_prime)
-                } else {
-                    Answer::No(Reason::DstIsTooBig)
-                }
+            let answer = self.answer_impl(cache, src_state, dst_state);
+            if let Some(..) = cache.insert((src_state, dst_state), answer.clone()) {
+                panic!("failed to correctly cache transmutability")
+            }
+            answer
```
Comment (joshlf) [inline compiler/rustc_transmute/src/maybe_transmutable/mod.rs:155]: What is the point of factoring `answer_impl` out into a separate function? It works, of course, but I'm curious what the motivation is.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs [hunk 5]
```diff
@@ -153,230 +148,136 @@ where
...
+            //   }
+            // ...if `refs_answer` was computed lazily. The below early
+            // returns can be deleted without impacting the correctness of
+            // the algorithm; only its performance.
+            debug!(?bytes_answer);
+            match bytes_answer {
+                Answer::No(_) if !self.assume.validity => return bytes_answer,
+                Answer::Yes if self.assume.validity => return bytes_answer,
+                _ => {}
+            };
```
Comment (joshlf) [inline compiler/rustc_transmute/src/maybe_transmutable/mod.rs:241]: Does this behave correctly when there are no byte transitions in the source type? It would need to reach the `_` arm. In particular, `Answer::Yes` would be invalid since `assume.validity` is supposed to only return yes when there is at least one source value which can be transmuted.

IIUC, this code path is unreachable for uninhabited types (we handle those elsewhere), so if you get to this point in the code and find no byte transitions, then there must be at least one ref transition. That implies that transmutability should solely be a function of the ref transitions, and so bailing early with `Answer::Yes` (when `self.assume.validity`) is invalid.

**Review by joshlf — CHANGES_REQUESTED** [review]
Thanks so much for doing this! I am curious to see how this affects performance, but I really like how much simpler a lot of the code is.

**Comment by joshlf** [comment]
Following up on [this thread](https://github.com/rust-lang/rust/pull/140168#discussion_r2061609691):

> Previously, when assuming validity, query nevertheless ensured that there exists a value that is valid for both src and dst:
> 
> ```rust
> #![feature(transmutability)]
> use std::mem::{Assume, TransmuteFrom};
> 
> pub fn is_transmutable<Src, Dst>()
> where
>     Dst: TransmuteFrom<Src, { Assume::VALIDITY }>,
> {
> }
> 
> pub union MaybeUninitByte {
>     pub uninit: (),
>     pub byte: u8,
> }
> 
> fn main() {
>     is_transmutable::<MaybeUninitByte, [u8; 2]>(); // previously rejected, now accepted
> }
> ```

---

> I'd expect this to hit the `Answer::No(Reason::DstIsTooBig)` branch here:
> 
> https://github.com/rust-lang/rust/blob/4326a44e6f0859077b7789d42416b9291b0ff4d1/compiler/rustc_transmute/src/maybe_transmutable/mod.rs#L180-L187
> 
> ...but that's clearly not happening. cc @joshlf

This PR fixes this bug, but I don't understand why. Can you articulate what the bug was, and how this PR fixes it? I generally feel comfortable with this PR, but I would feel more comfortable if I understood what the bug was and why this is a correct fix for it.

File: compiler/rustc_transmute/src/layout/mod.rs [hunk 6]
```diff
@@ -6,62 +6,61 @@ pub(crate) mod tree;
...
+        let val: u16 = val.into();
+        Byte { start: val, end: val + 1 }
     }
 
-    pub(crate) fn uninit() -> Byte {
-        Byte { range: None }
+    #[inline]
+    fn all() -> Byte {
+        Byte { start: 0, end: Self::UNINIT + 1 }
     }
```
[the remark this answers is not in the document]
Comment (jswrenn) [reply compiler/rustc_transmute/src/layout/mod.rs:43]: Talking it over with Josh, I think we came to a premature conclusion in https://github.com/rust-lang/project-safe-transmute/issues/19. `MaybeUninit::zeroed` being safe is a strong argument that answer to the first question posed in the example in https://github.com/rust-lang/unsafe-code-guidelines/issues/555 is *no* — it's not insta-UB to do that transmute.

The question of what you can actually *do* with that transmuted value remains open, but that's a problem for writing a safety comment on `MaybeUninit::assume_init`; not a problem for `TransmuteFrom`.

Given this, I think this means we *don't* need to treat unions differently depending on whether they appear in source or destination position.

[the remark this answers is not in the document]
Comment (joshlf) [reply compiler/rustc_transmute/src/layout/mod.rs:43]: I would expect `D -> C` (with `Assume::VALIDITY`) to be allowed. In particular, we want the following code to be permitted:

```rust
fn d_to_c<'a>(d: &'a mut D) -> &'a mut C
where
    &'a mut C: TransmuteFrom<&'a mut D, { Assume::SAFETY.and(Assume::VALIDITY) }>,
{
    let d: *mut D = d;
    let c = d.cast::<C>();
    // Initialize padding byte
    unsafe { core::ptr::write(c.cast::<u8>().add(1), 0) };
    unsafe { &mut *c }
}
```

This stems from the fact that the `rustc_transmute` machinery is used to determine both whether by-value transmutes are sound *and* whether by-reference transmutes are sound (the latter is implemented in terms of the former). We could in principle say that they have different semantics, but that would lead to a more confusing mental model for users and would make implementation more complex, as we'd need to special-case reference transmutes more than we already do.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs (hunk 4 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/maybe_transmutable/mod.rs]: Gotcha, sounds good. I'd definitely support a separate (parent or child) commit in a separate PR which does this refactor.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs (hunk 5 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/maybe_transmutable/mod.rs]: Can we add a test for this, both for `self.assume.validity` and `!self.assume.validity`?

I realize now why this is the case - it bottoms out at `Quantifier::empty`. But IMO it's confusing to bottom out that way because this `match` is effectively written in a way that relies on the specific implementation of `empty`.

Maybe we could instead modify `Quantifier::apply` to take a default `Answer` that is used if the provided `iter` is empty? IMO that would make this usage here clearer.

**Comment by joshlf** [comment]
> > This PR fixes this bug, but I don't understand why. Can you articulate what the bug was, and how this PR fixes it?
> 
> For an uninit transition in the source, the previous implementation returned `Answer::Yes`:
> 
> https://github.com/rust-lang/rust/blob/4326a44e6f0859077b7789d42416b9291b0ff4d1/compiler/rustc_transmute/src/maybe_transmutable/mod.rs#L247
> 
> With assumed validity that immediately terminates the computation with answer `Answer::Yes`.

Gotcha that makes sense.

File: compiler/rustc_transmute/src/layout/dfa.rs (hunk 1 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/layout/dfa.rs:336]: > That being said, I think there are other aspects of the implementation that
> make transmutability query exponential in the input size, so that would be
> something to tackle first.

Can you give examples? I'm not aware of any aspect of the current algorithm that is exponential in its input.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs (hunk 5 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/maybe_transmutable/mod.rs]: Okay sounds good. Feel free to follow up with that change in a separate PR.

File: compiler/rustc_transmute/src/layout/dfa.rs (hunk 3 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/layout/dfa.rs:441]: Ah gotcha. I don't feel strongly about it, so keeping it as-is is fine.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs [hunk 7]
```diff
@@ -197,122 +193,20 @@ where
...
-                                    accum.sum += 1 + usize::from(end.saturating_sub(start));
-                                } else {
-                                    accum.found_uninit = true;
+                    union(self.src.bytes_from(src_state), self.dst.bytes_from(dst_state))
+                        .filter_map(|(_range, (src_state_prime, dst_state_prime))| {
+                            match (src_state_prime, dst_state_prime) {
+                                // No matching transitions in `src`. Skip.
+                                (None, _) => None,
+                                // No matching transitions in `dst`. Fail.
+                                (Some(_), None) => Some(Answer::No(Reason::DstIsBitIncompatible)),
```
[the remark this answers is not in the document]
Comment (joshlf) [reply compiler/rustc_transmute/src/maybe_transmutable/mod.rs:203]: I disagree - while it's unreachable, if this were `(None, None)`, then it would actually be a valid transmute. IMO it's better to have the match's semantics be a function of the structure of the arms and not a function of the order in which they appear in the source code.

File: compiler/rustc_transmute/src/layout/dfa.rs [hunk 8]
```diff
@@ -478,95 +382,105 @@ mod edge_set {
...
+) -> UnionIter<X, Y> {
+    UnionIter { xs: xs.peekable(), ys: ys.peekable() }
+}
+
+pub(crate) struct UnionIter<X: Iterator, Y: Iterator> {
+    xs: Peekable<X>,
+    ys: Peekable<Y>,
+}
+
+impl<S: Copy, X: Iterator<Item = (Byte, S)>, Y: Iterator<Item = (Byte, S)>> Iterator
```
Comment (jswrenn) [inline compiler/rustc_transmute/src/layout/dfa.rs:427]: Add a `// FIXME` noting we'd likely benefit from specializing `try_fold` here. No need to actually write that specialization in this PR.

File: compiler/rustc_transmute/src/maybe_transmutable/mod.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (jswrenn) [reply compiler/rustc_transmute/src/maybe_transmutable/mod.rs:203]: Yeah, that's convincing!

File: compiler/rustc_transmute/src/layout/mod.rs [hunk 9]
```diff
@@ -6,62 +6,61 @@ pub(crate) mod tree;
...
 }
 
 impl fmt::Debug for Byte {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
-        match self.range {
-            None => write!(f, "uninit"),
-            Some((lo, hi)) => write!(f, "{lo}..={hi}"),
-        }
+        write!(f, "{}..{}", self.start, self.end)
```
[the remark this answers is not in the document]
Comment (jswrenn) [reply compiler/rustc_transmute/src/layout/mod.rs:58]: @tmiasko Can you do this one too? Happy to merge after that.

File: compiler/rustc_transmute/src/layout/dfa.rs (hunk 1 above)
Comment (joshlf) [reply compiler/rustc_transmute/src/layout/dfa.rs:336]: Ooooh okay yeah that is not good. One thing we're eventually hoping to do is to optimize the array representation so that arrays are represented in the DFA as a DFA tagged with a length rather than `N` copies of the DFA stitched together back-to-back. This is tricky because there are a lot of edge cases (e.g., what happens when the source and destination type have arrays which partially overlap?). That said, the problem you've identified here would be the same if you just had a struct with 10 `U` fields, so there are other issues to address. Completely running out of memory certainly makes me suspect that there's something exponential(ish) going on here.

> I think we should start by adding a perf rust.lang.org benchmark to track progress.

Do you know how to do that?
