### PR TITLE
rust-lld: add rpath entry to the correct `lib` folder

### LINKED ISSUE #80703: rust-lld doesn't work on Linux unless executed with rustup wrapper
I noticed that some CI builds started breaking over winter break with the 1.49.0 release of rustc. It looks like this is the behavior I'm running into:

```
$ echo 'fn main() {}' > foo.rs
$ rustc foo.rs --target wasm32-unknown-unknown
$ `rustup which rustc` foo.rs --target wasm32-unknown-unknown
error: linking with `rust-lld` failed: exit code: 127
  |
  = note: "rust-lld" "-flavor" "wasm" "--rsp-quoting=posix" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--fatal-warnings" "--no-demangle" "--export-dynamic" "--no-entry" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/self-contained" "foo.foo.7rcbfp3g-cgu.0.rcgu.o" "foo.foo.7rcbfp3g-cgu.1.rcgu.o" "foo.foo.7rcbfp3g-cgu.2.rcgu.o" "foo.foo.7rcbfp3g-cgu.3.rcgu.o" "foo.foo.7rcbfp3g-cgu.4.rcgu.o" "foo.foo.7rcbfp3g-cgu.5.rcgu.o" "-o" "foo.wasm" "--export" "main" "--export=__heap_base" "--export=__data_end" "foo.belfx9afw9cmv8.rcgu.o" "--gc-sections" "-O0" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-57520f873e4386ea.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libpanic_abort-2bb76cd91836cd74.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-2362cd2b752fe8cf.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/librustc_demangle-4e35388d2cf809d9.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libhashbrown-7528bb1d1a92d729.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/librustc_std_workspace_alloc-46e1c6d1138ee9b3.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libunwind-ffe09f2236ae74f5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcfg_if-f26ee661ae55669e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liblibc-0476900897b6039b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liballoc-b0c04b53f6ac3156.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/librustc_std_workspace_core-50344da360c5e489.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcore-0b67ff3e00a8bf99.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-5ca68120625f03c4.rlib"
  = note: rust-lld: error while loading shared libraries: libLLVM-11-rust-1.49.0-stable.so: cannot open shared object file: No such file or directory


error: aborting due to previous error
```

This appears to work with 1.48.0. It looks like in Rust 1.48.0 the `rust-lld` executable had libLLVM statically linked and now it has it dynamically linked. Unless the rustup wrapper is executed though (which munges `LD_LIBRARY_PATH` I believe) the executable no longer works (e.g. if you execute the rustc binary directly).

I think this is a case where the `-rpath` business may need to get involved? Ideally `rust-lld` would know that its libraries, when installed, are a few layers up.

### PR DESCRIPTION
**Pull request by lqd**
An explanation, for our linux rustup toolchain:
- `lld` / `rust-lld` is built as a regular LLVM tool, but is not distributed via the `llvm-tools` component. It's distributed by default, like a regular rust binary, like cargo and rustc. The general expected setup is: binaries in `bin` and libraries in `lib`, so the rpath we use for a `bin/$executable` is `$ORIGIN/../lib`.
- However, `rust-lld` is _not_ in the same location as our other executables (`$root/bin`), it's in `$root/lib/rustlib/$host/bin/`. The current rpath thus expects the LLVM's shared library to be in `$root/lib/rustlib/$host/lib/`. 
- That .so is only present in `$root/lib`, causing #80703. (LLVM's shared library is also copied to `$root/lib/rustlib/$host/lib/` with the `llvm-tools` component, so it also was [a workaround for the issue](https://github.com/rust-lang/rust/issues/80703#issuecomment-1574788504))

rustup's `LD_LIBRARY_PATH` overrides made this discrepancy invisible when we switched to `llvm.link-shared = true`, and this only showed up when running `rustc` or `rust-lld`'s executables directly.

To fix this we could: 
- copy the .so to this expected location all the time, but that seems wasteful.
- or, add an rpath entry when building LLD, which seems preferable to me (but I don't know if it could cause issues). 

This PR does the latter, tweaking how bootstrap builds LLD to point to the expected directory, and fixes #80703.

(Since this is related to P-high issues about switching to lld by default, I'll cc @petrochenkov to keep them updated.)

### CODE REVIEW

**Comment by lqd** [comment]
The issue is fixed on my local builds, and linking the wasm example works fine, but I was hoping we could get a `wasm32-unknown-unknown` target on try builds. It appears not to be the case, so we can't reproduce the issue exactly, but we can simulate it. 

On the `try` parent (`1e17cef9e29961636db63730784caea4b7d47ff5`), the wasm linking issue is the same as the following:

```console
$ readelf -d ~/.rustup/toolchains/1e17cef9e29961636db63730784caea4b7d47ff5/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld | grep PATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/lib]

$ ldd ~/.rustup/toolchains/1e17cef9e29961636db63730784caea4b7d47ff5/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld | grep LLVM
 libLLVM-16-rust-1.72.0-nightly.so => not found

$ ~/.rustup/toolchains/1e17cef9e29961636db63730784caea4b7d47ff5/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
.../rust-lld: error while loading shared libraries: libLLVM-16-rust-1.72.0-nightly.so: cannot open shared object file: No such file or directory
```
while on this PR's `6d05280785ea61c31f635fbfb61e8f988212a58b` try:

```console
$ readelf -d ~/.rustup/toolchains/6d05280785ea61c31f635fbfb61e8f988212a58b/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld | grep PATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../../:$ORIGIN/../lib:/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/lib]

$ ldd ~/.rustup/toolchains/6d05280785ea61c31f635fbfb61e8f988212a58b/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld | grep LLVM
 libLLVM-16-rust-1.72.0-nightly.so => /home/lqd/.rustup/toolchains/6d05280785ea61c31f635fbfb61e8f988212a58b/lib/rustlib/x86_64-unknown-linux-gnu/bin/../../../libLLVM-16-rust-1.72.0-nightly.so (0x00007fffeea00000)

$ ~/.rustup/toolchains/6d05280785ea61c31f635fbfb61e8f988212a58b/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
```

so we should be good to go here.

r? bootstrap

File: src/bootstrap/llvm.rs [hunk 1]
```diff
@@ -834,6 +834,30 @@ impl Step for Lld {
...
+        // needs is distributed at "$root/lib". The default rpath of "$ORIGIN/../lib" points at the
+        // lib path for LLVM tools, not the one for rust binaries.
+        //
+        // (The `llvm-tools` component copies the .so there for the other tools, and with that
+        // component installed, one can successfully invoke `rust-lld` directly without rustup's
+        // `LD_LIBRARY_PATH` overrides)
+        //
+        if builder.config.rust_rpath
+            && builder.config.llvm_link_shared()
+            && target.contains("linux")
```
Comment (Mark-Simulacrum) [inline src/bootstrap/llvm.rs:850]: I think we probably want a slightly more complex condition rather than just rust_rpath here, at least conditional on the specific target we're building for?

See https://github.com/rust-lang/rust/blob/1e17cef9e29961636db63730784caea4b7d47ff5/src/bootstrap/builder.rs#L1629 for what we do for regular rustc/std/etc.

I'm also wondering whether we need this on Apple targets.

Comment (lqd) [reply src/bootstrap/llvm.rs:850]: I believe we don’t use link-shared on mac ? (at least not on my M1)

Comment (lqd) [reply src/bootstrap/llvm.rs:851]: > I think we probably want a slightly more complex condition rather than just rust_rpath here, at least conditional on the specific target we're building for?

Yes absolutely, good call. I've pushed a commit to add the more complex condition.
