### PR TITLE
Regression test for undefined `__chkstk` on `aarch64-unknown-uefi`

### LINKED ISSUE #98254: error: undefined symbol: __chkstk on aarch64-unknown-uefi
I tried this code:

```rust
// in #[entry] fn main()
let memory_map = get_mem_map(bt);

// in library
pub fn get_mem_map(bt: &BootServices) -> AlignToMemoryDescriptor {
    let mut memory_map = AlignToMemoryDescriptor {
        0: [0 as u8; MAX_MEMORY_MAP_SIZE],
    };
    {
        let res = bt.memory_map(&mut memory_map.0);

        match res {
            Ok(r) => {
                info!("Retrieved Memory Map!");
                info!("Memory Map Key = {:?}", &r.0);
                let iterator_item = r.1;
                iterator_item.for_each(|i| info!("Memory Descriptor = {i:?}"));
            }
            Err(err) => panic!("Could not get memory map. Error: {err:?}"),
        }
    }

    memory_map
}
```

I expected to see this happen: No link error cause it is sound code.

Instead, this happened: I got an undefined symbol error, which seems to be a problem with the compiler/linker being unable to know if Im going to overflow the stack

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (60e50fc1c 2022-04-04)
binary: rustc
commit-hash: 60e50fc1cfe0bb693a5f4f93eb83ef70854531e3
commit-date: 2022-04-04
host: aarch64-apple-darwin
release: 1.62.0-nightly
LLVM version: 14.0.0
```

<details><summary>Backtrace</summary>
<p>

```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "link" "/NOLOGO" "/entry:efi_main" "/subsystem:efi_application" "/machine:arm64" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.10860la7lg9m5zn1.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.12gi8jn8zywdxv6h.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.12mds7eapchfjvfh.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.1ikw55eou1bf3eg1.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.1mx424kmmbsalcic.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.1t9doq35s6sx7lcj.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.237grgsvhid7fpts.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.23hlvne6yrypuu9l.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.2ek71ldjh4fw9mnr.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.2p1np39se4rg1en1.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.35qfhcfezhjjhjq8.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.3bki6fhvzt8tce2g.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.3hssll7pzpq4wngd.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.3iq51mcpjmgqqxcp.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.474t401uuawr9pjp.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.4f2py4q0c58oopcl.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.4l0fy6cj8w3oiywi.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.4r9nhovccm037jyi.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.51j5lxe7enjgraji.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.5a7llcm4ivz0mg9m.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.ap4qa7cl5w7xkk4.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.hj8i0u6yntu4dkf.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.hnpm1zs9s81xv4g.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.jy7nxdsjlj6pv75.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.qh1nrbt29xb0vkn.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.zs6cy23jktqio5w.rcgu.o" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.4lgs7981ret5znjw.rcgu.o" "/LIBPATH:/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps" "/LIBPATH:/Users/jasonq/Documents/GitHub/Arcboot/target/debug/deps" "/LIBPATH:/Users/jasonq/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-unknown-uefi/lib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libarcboot-3b698ac8d3c398e2.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/liblinked_list_allocator-75bb8ba81fc768db.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libspinning_top-2aa0acbdfe0c659c.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libaarch64-705062cb4f6b687d.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libcortex_a-39e702517f9b69f2.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libtock_registers-57c8d8f19f0b66ee.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libqemu_exit-c7972f030686e4ec.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/liblazy_static-6ca79388e5285dbe.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libspin-1d4a8bf93c0fa00f.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libspin-60f5af8ab53b5555.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/liblock_api-9f9389295b3faafd.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libscopeguard-2bd0414a3c1a160c.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libacpi-e04bf978a602b9e2.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/librsdp-3ca0eea8681ddda1.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libuefi-668ad71a18d6f50e.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libbitflags-39e5d6ea55f39b47.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libucs2-ffe6747d48dde65d.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libbit_field-6814482675aaa2e6.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/liballoc-ec155d3e116d2a14.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/liblog-bbb3b5c8bc5d1d68.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libcfg_if-8866ce721cb8a40e.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/librustc_std_workspace_core-dc84e73fe987a0ca.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libcore-a8ff4b8ed128c50e.rlib" "/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/libcompiler_builtins-42e14f5c94945cb2.rlib" "/NXCOMPAT" "/LIBPATH:/Users/jasonq/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-unknown-uefi/lib" "/OUT:/Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.efi" "/OPT:REF,NOICF" "/DEBUG" "/NODEFAULTLIB"
  = note: rust-lld: error: undefined symbol: __chkstk
          >>> referenced by /Users/jasonq/Documents/GitHub/Arcboot/src/main.rs:56
          >>>               /Users/jasonq/Documents/GitHub/Arcboot/target/aarch64-unknown-uefi/debug/deps/arcboot_main-3791f8b9a1c81533.3iq51mcpjmgqqxcp.rcgu.o:(efi_main)
          

warning: `arcboot_main` (bin "arcboot_main") generated 12 warnings
error: could not compile `arcboot_main` due to previous error; 12 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Jamesbarford**
Adds a test for compiling a block of code with target `aarch64-unknown-uefi`.

Closes https://github.com/rust-lang/rust/issues/98254

### CODE REVIEW

File: src/tools/compiletest/src/directives/directive_names.rs [hunk 1]
```diff
@@ -190,6 +190,7 @@ pub(crate) const KNOWN_DIRECTIVE_NAMES: &[&str] = &[
     "only-aarch64",
     "only-aarch64-apple-darwin",
     "only-aarch64-unknown-linux-gnu",
+    "only-aarch64-unknown-uefi",
```
Comment (jieyouxu) [inline src/tools/compiletest/src/directives/directive_names.rs:193]: Problem: this gating will mean that this test does not run in this repo's CI, since `aarch64-unknown-uefi` is not a Tier 1 target, nor does this target have a host std, and this is not one of the limited Tier 2 targets tested on cross-compile scenarios. Basically, I can't accept a test that never runs in rust-lang/rust CI.

Comment (Jamesbarford) [reply src/tools/compiletest/src/directives/directive_names.rs:193]: That's reasonable. Does this github action run; https://github.com/rust-lang/rust/blob/f2bae990e89bf696e86706b524ac32ab72945438/src/ci/github-actions/jobs.yml#L259 ?

As the docker image looks like it _may_ potentially run the test in this Dockerfile; https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/dist-various-2/Dockerfile. Though I'm not terribly familiar with the setup.

Comment (jieyouxu) [reply src/tools/compiletest/src/directives/directive_names.rs:193]: Yes, but that's intended *only* for distribution of the pre-built rustc and such, not for running tests (Tier 2 targets are guarantee to build by this repo's CI, but not pass tests). https://github.com/rust-lang/rust/blob/f2bae990e89bf696e86706b524ac32ab72945438/src/ci/docker/host-x86_64/dist-various-2/Dockerfile#L141

Generally speaking, Tier 2 target maintainers might maintain additional test suites out-of-tree.

**Comment by davidtwco** [comment]
>  Basically, I can't accept a test that never runs in rust-lang/rust CI.

Why? I appreciate that it isn't especially useful if it isn't being tested, but it is still useful for people who work on these targets locally to have tests in tree, and even if it gets forgotten and years later we discover it never passes, it's still a useful indication of intent. (If this is a standard policy we have that I'm unaware of, do let me know)

File: src/tools/compiletest/src/directives/directive_names.rs (hunk 1 above)
Comment (jieyouxu) [reply src/tools/compiletest/src/directives/directive_names.rs:193]: (Please disregard, I'm thinking of other tests that are genuinely problematic, Tier 2 target tests seem okay even if they don't run in r-l/r CI, considering they are target-specific.)

File: tests/ui/issues/issue-98254.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+//@ build-pass
+//@ only-aarch64-unknown-uefi
+//@ compile-flags: -Cpanic=abort
+//@compile-flags: -Clinker=rust-lld
```
Comment (jieyouxu) [inline tests/ui/issues/issue-98254.rs]: Nit: can you use a consistent whitespace here?

File: tests/ui/stack-probes/aarch64-unknown-uefi-chkstk-98254.rs
Comment (jieyouxu) [inline tests/ui/stack-probes/aarch64-unknown-uefi-chkstk-98254.rs:1]: Suggestion: can you please move this test to a more meaningful subdirectory e.g. `tests/ui/stack-probes/`? It's fine if you need to create one.

Comment (jieyouxu) [inline tests/ui/stack-probes/aarch64-unknown-uefi-chkstk-98254.rs:1]: Suggestion: can you also call this something more meaningful, like `undefined-chkstk-98254`?

Comment (jieyouxu) [inline tests/ui/stack-probes/aarch64-unknown-uefi-chkstk-98254.rs:1]: Nit: and can you leave a breadcrumb here for context, i.e.

```rs
//! Regression test for #98254, missing `__chkstk` symbol on `aarch64-unknown-uefi`.
```

**Review by jieyouxu — COMMENTED** [review]
A few nits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148437/f2bae990e89bf696e86706b524ac32ab72945438..10986bd119db16d5ca085c60566f7a74b86dfe01)*

**Review by jieyouxu — APPROVED** [review]
Thanks, waiting for basic CI on directives.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148437/35ebdf9ba1414456dfe1cb6a6b13ebae80e99734..1bc898e2535a5751f2abf2f9b98331086087bdc7)*
