### PR TITLE
Recover from using `;` as separator between fields

### LINKED ISSUE #101440: Add help suggestion for semicolon used inside struct declaration
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5824f90029ac83289d17598d474a12b5)

```rust
struct Num {
    a: i32;
}

fn main() {
 
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected `,`, or `}`, found `;`
 --> src/main.rs:2:11
  |
2 |     a: i32;
  |           ^

error: could not compile `playground` due to previous error
```

Ideally the output should suggest replacing the `;` with `,` since a suggestion already exist for an incorrect semicolon usage at the end of the struct declaration (after the closing brace).

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Partially fixes #101440 (only for record structs).

Doing that for tuple structs is harder as their parsing passes through a bunch of helper functions. I don't know how to do that. But [their error message is better anyway](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cc6ee8bb2593596c0cea89d49e79bcb4) and suggests using a comma, even if it doesn't suggest replacing the semicolon with it.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1526,6 +1526,12 @@ impl<'a> Parser<'a> {
         if self.token == token::Comma {
             seen_comma = true;
         }
+        if self.eat(&token::Semi) {
+            let sp = self.prev_token.span;
+            let mut err = self.struct_span_err(sp, format!("{adt_ty} fields are separated by `,`"));
+            err.span_suggestion(sp, "replace `;` with `,`", ",", Applicability::MachineApplicable);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1532]: `span_suggestion_short` here will render like "help: replace `;` with `,`" which i think is cleaner

**Comment by leonardo-m** [comment]
Rustc gets better and better

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -1526,6 +1526,17 @@ impl<'a> Parser<'a> {
...
+        if self.eat(&token::Semi) {
+            let sp = self.prev_token.span;
+            let mut err = self.struct_span_err(sp, format!("{adt_ty} fields are separated by `,`"));
+            err.span_suggestion_short(
+                sp,
+                "replace `;` with `,`",
+                ",",
+                Applicability::MachineApplicable,
+            );
+            return Err(err);
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/item.rs:1538]: Ideally this would have recovered as if a `,` had been found (emitting this error instead of returning it and calling `self.bump()`)...
