### PR TITLE
Gracefully handle mistyping -> as => in function return type

### LINKED ISSUE #77019: Give a better error message for `=>` in a return type
Spot the difference ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2fb595a9d8f1d089fcd5842f67250815)):
```rust
fn f() -> usize {
    0
}

fn g() => usize {
    0
}
```
```
error: expected `;` or `{`, found `=>`
 --> src/lib.rs:5:8
  |
5 | fn g() => usize {
  |        ^^ expected `;` or `{`
```
Notice how this gives a hard parse error and doesn't even mention return types. Instead, it should suggest `g() -> usize`.

### PR DESCRIPTION
**Pull request by mibac138**
Fixes #77019

### CODE REVIEW

File: src/test/ui/fn/fn-fat-arrow-return.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+fn g() => usize { 0 }
+//~^ ERROR return types are denoted using `->`
```
Comment (jyn514) [inline src/test/ui/fn/fn-fat-arrow-return.rs:2]: Could you also test `cargo fix`?
```suggestion
// run-rustfix
fn g() => usize { 0 }
//~^ ERROR return types are denoted using `->`
```
and then run `x.py test src/test/ui --bless --test-args fat-arrow-return`

**Comment by lzutao** [comment]
Might want a crater check if we want make sure it introduce no regressions.

**Comment by jyn514** [comment]
@lzutao what does crater have to do with this? All this does is improve a diagnostic for code that was already broken.

**Comment by lzutao** [comment]
I mean, to be sure. But I'm not a parser devs so it's up to them to decide.

**Comment by jyn514** [comment]
If every pull request went through crater, we'd never get anything merged, it would take weeks for the smallest change.

**Comment by lzutao** [comment]
Is is a parser change, not every PR is of the same kind. 
I see it is a good improvement too. But not a high priority one. 
And parser changes really need to be cared.
They could introduce side-effect and allow undesired behaviours.
However I didn't say that this PR has any of those things.

File: src/test/ui/fn/fn-fat-arrow-return.rs [hunk 2]
```diff
@@ -0,0 +1,4 @@
+fn g() => usize { 0 }
```
Comment (lzutao) [inline src/test/ui/fn/fn-fat-arrow-return.rs:1]: Could you add a test for multiple `=>` ?

```rust
fn foo() => Fn() => bool {
    unimplemented!()
}
```

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -92,6 +92,15 @@ impl<'a> Parser<'a> {
             // FIXME(Centril): Can we unconditionally `allow_plus`?
             let ty = self.parse_ty_common(allow_plus, recover_qpath, AllowCVariadic::No)?;
             FnRetTy::Ty(ty)
+        } else if self.token == token::FatArrow {
+            // Don't `eat` to prevent `=>` from being added as an expected token which isn't
+            // actually expected and could only confuse users
+            self.bump();
+            self.struct_span_err(self.prev_token.span, "return types are denoted using `->`")
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/ty.rs:99]: I'd suggest that you add a `recover_fat_arrow` argument and only perform this recovery when the caller requests it - in particular, where `parse_ret_ty` is used in parsing path segments, this recovery shouldn't happen.

I expect that this example, which currently compiles, would no longer parse with the change as it exists currently (but would with my prior suggestion):

```rust
fn bar(_: u32) {}

fn baz() -> *const dyn Fn(u32) { unimplemented!() }

fn foo() {
    match () {
        _ if baz() == &bar as &dyn Fn(u32) => (),
        () => (),
    }
}
```

Please add the above as a test too.

**Review by davidtwco — CHANGES_REQUESTED** [review]
Some changes are required but this is definitely an improvement. Please resolve all of the review comments that have been left so far. 

You'll also need to run `./x.py fmt` to run rustfmt and pass CI.

**Comment by bugaevc** [comment]
> return types are denoted using `->`

Would also be cool to emit this upon encountering

```rust
fn foo(_arg: i32): i32 {
    ...
}
```

which is how you'd define the return type in Scala and Kotlin.

**Comment by LeSeulArtichaut** [comment]
> > return types are denoted using `->`
> 
> Would also be cool to emit this upon encountering
> 
> ```rust
> fn foo(_arg: i32): i32 {
>     ...
> }
> ```
> 
> which is how you'd define the return type in Scala and Kotlin.

Opened #77115 as a separate issue for this

File: src/test/ui/fn/fn-fat-arrow-return.rs (hunk 2 above)
Comment (pickfire) [reply src/test/ui/fn/fn-fat-arrow-return.rs:1]: And also `=>` in arguments.
```rust
fn foo(bar: impl Fn() => bool) {
    unimplemented!()
}
```

Comment (davidtwco) [reply src/test/ui/fn/fn-fat-arrow-return.rs:1]: I don't think either of these could be supported without hitting the same ambiguity as described in [my other comment](https://github.com/rust-lang/rust/pull/77035#discussion_r492621515). Worth checking, but that's my expectation.

**Comment by JohnCSimon** [comment]
Ping from triage:
@mibac138 can you please address the feedback and broken build.

**Comment by crlf0710** [comment]
@mibac138 Ping from triage, it seems your last edits didn't fix the CI error. Would you mind rebasing and fixing it?

**Comment by JohnCSimon** [comment]
@mibac138 Ping from triage, can you please resolve the merge conflicts?

**Comment by mibac138** [comment]
Fixed the build and rebased.
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

File: compiler/rustc_parse/src/parser/ty.rs [hunk 4]
```diff
@@ -102,6 +169,7 @@ impl<'a> Parser<'a> {
         allow_plus: AllowPlus,
         recover_qpath: RecoverQPath,
         allow_c_variadic: AllowCVariadic,
+        recover_return_sign: RecoverReturnSign,
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/ty.rs:172]: nit: can you re-order the arguments to this function so that the `allow_` arguments come before the `recover_` arguments?

File: compiler/rustc_parse/src/parser/ty.rs [hunk 5]
```diff
@@ -43,6 +43,23 @@ pub(super) enum RecoverQPath {
     No,
 }
 
+#[derive(Copy, Clone, PartialEq)]
+pub(super) enum RecoverReturnSign {
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/ty.rs:47]: I'd like to find a better name for this enum but I'm struggling to come up with anything.

Also, could you add doc comments to this enum, its variants and the `can_recover` method?

**Review by davidtwco — COMMENTED** [review]
LGTM, thanks! Sorry for the delay in getting back to this review.

I'm going to do a crater run for this because - as observed by case [from my previous review](https://github.com/rust-lang/rust/pull/77035/files#r492621515) - changes like these in the parser can be tricky and change what code we accept.

**Comment by davidtwco** [comment]
@craterbot check

**Comment by davidtwco** [comment]
@craterbot check

**Comment by davidtwco** [comment]
@mibac138 Great, no regressions, once the review comments are resolved then we can land this!

**Comment by mibac138** [comment]
@davidtwco Glad to hear! I have now addressed your review comments, so I think this should be good to go now?

**Comment by davidtwco** [comment]
Thanks!

@bors r+

File: src/test/ui/fn/fn-recover-return-sign.fixed [hunk 6]
```diff
@@ -0,0 +1,28 @@
+// run-rustfix
+#![allow(unused)]
+fn a() -> usize { 0 }
+//~^ ERROR return types are denoted using `->`
+
+fn b()-> usize { 0 }
```
Comment (pickfire) [inline src/test/ui/fn/fn-recover-return-sign.fixed:6]: How come rustfix does not add a space here?

Comment (jyn514) [reply src/test/ui/fn/fn-recover-return-sign.fixed:6]: Rustfmt doesn't run on the test suite (and shouldn't, because sometimes the tests are for the parser, and the parser should be whitespace-independent).

Comment (pickfire) [reply src/test/ui/fn/fn-recover-return-sign.fixed:6]: Isn't this the output of rustfix? Shouldn't rustfix code output be sightly formatted (at least not as good as rustfmt)?

Comment (jyn514) [reply src/test/ui/fn/fn-recover-return-sign.fixed:6]: Oh! I missed that this is a `.fixed` file. This happens because the original doesn't have a space before the `:`:

```
fn b(): usize { 0 }
//~^ ERROR return types are denoted using `->`
```
Ideally the suggestion would add its own space, yeah.
