### PR TITLE
Pass vendored sources from bootstrap to generate-copyright

### LINKED ISSUE #136955: `GenerateCopyright` attempts to vendor sources during installation
Gentoo Linux builds are primarily performed in a sandbox that prevents network activity after sources are fetched.

Unfortunately this leaves us unable to package `nightly` as `GenerateCopyright` is invoked by `x.py install`, which attempts to vendor crates into the build directory.

 1. `GenerateCopyright` should only be run when generating the source tarball, or should at the very least at least be a separate step from `Rustc`
2. `src/tools/generate-copyright` should respect `config.vendor`

I tried this:

```console
`x.py install ...
```

I expected to see this happen:

A successful installation into `DESTDIR`

Instead, this happened:

```
running: cd "/var/tmp/portage/dev-lang/rust-9999/work/rust-9999" && CARGO="/opt/rust-bin-9999/bin/cargo" DEST="/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build/COPYRIGHT.html" DEST_LIBSTD="/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build/COPYRIGHT-library.html" LD_LIBRARY_PATH="/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/opt/rust-bin-9999/lib" LICENSE_METADATA="/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/license-metadata.json" OUT_DIR="/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build" RUSTC="/opt/rust-bin-9999/bin/rustc" "/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build/x86_64-unknown-linux-gnu/stage0-tools-bin/generate-copyright" (failure_mode=Exit) (created at src/bootstrap/src/core/build_steps/tool.rs:1211:23, executed at src/bootstrap/src/core/build_steps/run.rs:224:13)
Vendoring deps into /var/tmp/portage/dev-lang/rust-9999/work/rust-9999/build/vendor...
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to get `tikv-jemalloc-sys` as a dependency of package `rustc-main v0.0.0 (/var/tmp/portage/dev-lang/rust-9999/work/rust-9999/compiler/rustc)`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [6] Could not resolve hostname (Could not resolve host: index.crates.io)
Error: Failed to complete cargo vendor
```

[rust-9999:20250213-003653.log.xz.txt](https://github.com/user-attachments/files/18776077/rust-9999.20250213-003653.log.xz.txt)

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (92bedea1c 2025-02-11)
binary: rustc
commit-hash: 92bedea1c51e3a969d60972be854506ffd8c5cb6
commit-date: 2025-02-11
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

```

### PR DESCRIPTION
**Pull request by emilyalbini**
In addition to doing the vendoring in bootstrap, this PR also loads the list of manifests to parse from bootstrap (instead of hardcoding a smaller list in generate-copyright). This is best reviewed commit-by-commit.

Fixes https://github.com/rust-lang/rust/issues/136955

### CODE REVIEW

File: src/tools/generate-copyright/src/cargo_metadata.rs [hunk 1]
```diff
@@ -58,10 +54,6 @@ pub fn get_metadata_and_notices(
 ) -> Result<BTreeMap<Package, PackageMetadata>, Error> {
```
Comment (Kobzol) [inline src/tools/generate-copyright/src/cargo_metadata.rs:54]: The doc comment above this function is now outdated.

**Review by Kobzol — COMMENTED** [review]
Awesome, I wanted to do commit 2 some time ago, but forgot about it. Left some comments.

**Comment by pietroalbini** [comment]
Will address the rest of the feedback on monday.

File: src/tools/generate-copyright/src/cargo_metadata.rs (hunk 1 above)
Comment (pietroalbini) [reply src/tools/generate-copyright/src/cargo_metadata.rs:52]: Fixed!

File: src/bootstrap/src/core/build_steps/run.rs [hunk 2]
```diff
@@ -212,11 +213,38 @@ impl Step for GenerateCopyright {
...
+            .into_iter()
+            .map(|(path, _submodules)| path.to_str().unwrap().to_string())
+            .inspect(|path| assert!(!path.contains(','), "{path} contains a comma in its name"))
+            .collect::<Vec<_>>()
+            .join(",");
+
+        let vendored_sources = if let Some(path) = builder.vendored_crates_path() {
+            path
+        } else {
+            let cache_dir = builder.out.join("vendor");
```
[the remark this answers is not in the document]
Comment (pietroalbini) [reply src/bootstrap/src/core/build_steps/run.rs]: Whoops, good catch! Fixed.

**Comment by pietroalbini** [comment]
Addressed all review feedback. While I was at it, I also updated the plain source tarball step to use the `Vendor` step, merging all uses of vendoring inside of bootstrap into the `Vendor` step!

**Comment by Kobzol** [comment]
Looks great, nice simplification! You can r=me once CI is green.

**Comment by erickt** [comment]
@pietroalbini  - it seems this patch has broken our Rust mirror for Fuchsia. We've had to exclude `rustc-perf` from our local mirror since it has a pretty complicated licensing story. Rust previously built fine for us since we weren't running the performance tests, but with this patch we're now getting this error:

```
submodule src/tools/rustc-perf does not appear to be checked out, but it is required for this step
Consider setting `build.submodules = true` or manually initializing the submodules.
```

Is there any way we could work around this, or add a flag where we could skip this check?

**Comment by jieyouxu** [comment]
> @pietroalbini  - it seems this patch has broken our Rust mirror for Fuchsia. We've had to exclude `rustc-perf` from our local mirror since it has a pretty complicated licensing story. Rust previously built fine for us since we weren't running the performance tests, but with this patch we're now getting this error:
> 
> ```
> submodule src/tools/rustc-perf does not appear to be checked out, but it is required for this step
> Consider setting `build.submodules = true` or manually initializing the submodules.
> ```
> 
> Is there any way we could work around this, or add a flag where we could skip this check?

This is missing a require_submodule somewhere, could you share the slecific invocation you used so I can double-check (maybe in its own issue)?

**Comment by jieyouxu** [comment]
Discussed and beta backport approved [on zulip](https://rust-lang.zulipchat.com/#narrow/channel/326414-t-infra.2Fbootstrap/topic/Beta-backport.20nomination.20for.20.23137020/near/501386222).

@rustbot label: +beta-accepted
