### PR TITLE
Prevent failure in case no space left on device in rustdoc

### LINKED ISSUE #59703: Unexpected panic while using `cargo doc` command with nom 4.2.2.
After a simple `git clone`, I tried to generate the crate documentation. I really don't know why I get this error.

The problem seems to be here but what's wrong? ^^'

```rust
// file: src/nom.rs

/// Recognizes big endian unsigned 3 byte integer
#[inline]
pub fn be_u24(i: &[u8]) -> IResult<&[u8], u32> {
  if i.len() < 3 {
    need_more(i, Needed::Size(3))
  } else {
    let res = ((i[0] as u32) << 16) + ((i[1] as u32) << 8) + (i[2] as u32);
    Ok((&i[3..], res))
  }
}
```

The source is on glitch: https://glitch.com/edit/#!/nom-fork?path=nom/README.md:1:0

## Meta

```
$ cargo doc
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading memchr v2.2.0                                                      
 Downloading libc v0.2.51                                                       
 Downloading version_check v0.1.5                                               
   Compiling libc v0.2.51                                                       
   Compiling memchr v2.2.0
   Compiling version_check v0.1.5
 Documenting libc v0.2.51
   Compiling nom v4.2.2 (file:///app/nom)
 Documenting memchr v2.2.0
 Documenting nom v4.2.2 (file:///app/nom)
thread '<unnamed>' panicked at 'failed to generate documentation: Error { file: "/app/nom/target/doc/nom/fn.be_u24.html", error: Os { code: 28, kind: Other, message: "No space left on device" } }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0 (9634041f0 2018-07-30) running on x86_64-unknown-linux-gnu

error: Could not document `nom`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name nom src/lib.rs -o /app/nom/target/doc --cfg feature="alloc" --cfg feature="default" --cfg feature="memchr" --cfg feature="std" -L dependency=/app/nom/target/debug/deps --extern memchr=/app/nom/target/debug/deps/libmemchr-b2cd595b80edfc3d.rmeta --cfg stable_i128` (exit code: 101)
```

Feel free to ping me if you need to ask me more!

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #59703.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -1452,11 +1454,12 @@ impl<'a> SourceCollector<'a> {
         let mut href = String::new();
         clean_srcpath(&self.scx.src_root, &p, false, |component| {
             cur.push(component);
-            fs::create_dir_all(&cur).unwrap();
+            fs::create_dir_all(&cur)?;
```
Comment (ollie27) [inline src/librustdoc/html/render.rs]: `fs::create_dir_all(&cur)?;` can be moved to after the call to `clean_srcpath` because `create_dir_all` works recursively anyway. That means that `clean_srcpath` itself doesn't need to be modified.

**Comment by Dylan-DPC** [comment]
ping from triage @GuillaumeGomez you need to address the review left by ollie above.

**Comment by GuillaumeGomez** [comment]
Indeed! I'll do it as soon as possible.

**Comment by GuillaumeGomez** [comment]
Updated (thanks for the great suggestion @ollie27!).

**Comment by ollie27** [comment]
Looks good.

@bors r+ rollup
