### PR TITLE
syntax: allow negative integer literal expression to be interpolated as pattern

### LINKED ISSUE #42820: The macro_rules treat `-1` as not a pattern
I need a enum which is deserialized with `serde` from number: `-1`, `0` and `1`.
When I try to use `enum_number` macro from official `serde` documentation I get this:
```

error: expected pattern, found `-1`
  --> src/serde_utils.rs:37:32
   |
37 |                             $( $value => Ok($name::$variant), )*
   |                                ^^^^^^

error: aborting due to previous error
```

The code is very simple:

```
enum_number!(Change {
    Down = -1,
    None = 0,
    Up = 1,
});
```

```
macro_rules! enum_number {
    ($name:ident { $($variant:ident = $value:expr, )* }) => {
        #[allow(missing_docs)]
        #[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
        pub enum $name {
            $($variant = $value,)*
        }

        impl serde::Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
                where S: serde::Serializer
            {
                // Serialize the enum as a i64.
                serializer.serialize_i64(*self as i64)
            }
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
                where D: serde::Deserializer<'de>
            {
                struct Visitor;

                impl<'de> serde::de::Visitor<'de> for Visitor {
                    type Value = $name;

                    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                        formatter.write_str("signed 64-bit integer")
                    }

                    fn visit_i64<E>(self, value: i64) -> Result<$name, E>
                        where E: serde::de::Error
                    {
                        // Rust does not come with a simple way of converting a
                        // number to an enum, so use a big `match`.
                        match value {
                            $( $value => Ok($name::$variant), )*
                            _ => Err(E::custom(
                                format!("unknown {} value: {}",
                                stringify!($name), value))),
                        }
                    }
                }

                // Deserialize the enum from a i64.
                deserializer.deserialize_i64(Visitor)
            }
        }
    }
}
```

If I change `-1` to a positive number it compiles okay. I think it is a problem.

### PR DESCRIPTION
**Pull request by durka**
Fixes #42820.

r? @jseyfried

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -1661,6 +1661,8 @@ impl<'a> Parser<'a> {
 
     /// matches '-' lit | lit
     pub fn parse_pat_literal_maybe_minus(&mut self) -> PResult<'a, P<Expr>> {
+        maybe_whole_expr!(self);
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: This line permits much more that just negative integer literals, now `PatKind::Lit` and `PatKind::Range` can contain arbitrary expressions.
I'm not sure that later compilation stages are prepared to deal with them, but there's a chance that it will "just work" and passing an arbitrary expression through `expr` matcher will be equivalent to passing it through a constant.

There are two ways to proceed, I think:
- Conservative way: add a check to `ast_validation` ensuring that only paths, literals and literals with minus are accepted in `PatKind::Lit` and `PatKind::Range`.
- Non-conservative way: extend the language and permit passing arbitrary expressions to literal/range patterns through `expr` matchers, make sure it doesn't cause ICEs etc, make @rust-lang/lang aware of this change.

In any case tests for passing arbitrary expressions are required.

Comment (durka) [inline src/libsyntax/parse/parser.rs]: Indeed it causes ICEs. Conservative approach sounds good to me for this patch.

Comment (durka) [inline src/libsyntax/parse/parser.rs]: Should the check be in `ast_validation` or right here in `parse_pat_literal_maybe_minus`?

Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: These kinds of things are usually checked in `ast_validation` because AST fragments can be produced by procedural macros as well (and parser checks won't help in this case).

Comment (durka) [inline src/libsyntax/parse/parser.rs]: Ack.

Comment (durka) [inline src/libsyntax/parse/parser.rs]: @petrochenkov OK, not quite sure what to do. I added the check to `ast_validation` but I am hitting [this ICE in a lint](https://github.com/rust-lang/rust/blob/fc9ccfdbe02f4cf3e3ea60ee4412f00d29ef7f53/src/librustc_lint/builtin.rs#L692) before it even gets there.

Should I just remove the ICE, letting any expression through that lint and have validation catch it later, or add the validation check here (does procedural macro generated code go through lints?)?

**Comment by durka** [comment]
I added the check to `ast_validation` and a test that `1+1` doesn't slip through. Just to make sure the user doesn't miss the message, it prints the error twice and an unrelated one from typeck as well (but seriously [wtf is going on](https://github.com/rust-lang/rust/pull/42886/files#diff-6f1e620e714456095f49b90836b62faeR30)).

File: src/librustc_passes/ast_validation.rs [hunk 2]
```diff
@@ -93,6 +93,17 @@ impl<'a> AstValidator<'a> {
             }
         }
     }
+
+    /// matches '-' lit | lit (cf. parser::Parser::parse_pat_literal_maybe_minus)
+    fn check_expr_within_pat(&self, expr: &Expr) {
+        match expr.node {
+            ExprKind::Lit(_) => {}
+            ExprKind::Unary(UnOp::Neg, ref inner)
+                if match inner.node { ExprKind::Lit(_) => true, _ => false } => {}
```
Comment (petrochenkov) [inline src/librustc_passes/ast_validation.rs]: `ExprKind::Path` is permitted as well, Travis fails due to this.

**Comment by durka** [comment]
Some dependency edges must be missing since I was able to rebuild locally.

File: src/test/compile-fail/patkind-litrange-no-expr.rs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+            }
+        }
+    }
+}
+
+enum_number!(Change {
+    Pos = 1,
+    Neg = -1,
+    Arith = 1 + 1, //~ ERROR arbitrary expressions aren't allowed in patterns
+                   //~^ ERROR arbitrary expressions aren't allowed in patterns
```
Comment (est31) [inline src/test/compile-fail/patkind-litrange-no-expr.rs]: cc @arielb1 -- you wanted to get pinged when I find duplicated error messages.

**Comment by durka** [comment]
Sorry, I just realized it isn't really a duplicated message. It's generated
twice because the macro generates two patterns containing $value.

**Comment by jseyfried** [comment]
Reviewed, r=me unless anyone objects.
Eventually, I think we should consider the negative to be part of the literal (cc @eddyb).

File: src/test/compile-fail/patkind-litrange-no-expr.rs (hunk 3 above)
Comment (arielb1) [inline src/test/compile-fail/patkind-litrange-no-expr.rs]: Nah this is caused by there being 2 uses of `value`.
