### PR TITLE
rustdoc-json: Add assoc type ICE regression test

### LINKED ISSUE #98547: rustdoc-json: ICE with associated type in trait
Minimal reproducer with `1.64.0-nightly (20a6f3a8a 2022-06-25)`:

```rust
// src/lib.rs

pub trait Trait {
    type AssocType;
}

impl<T> Trait for T {
    type AssocType = Self;
}

pub struct S;
```

```bash
% RUSTDOCFLAGS='-Z unstable-options --output-format json' cargo +nightly doc --lib --no-deps  
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:7:1558"), crate_id: 0, name: Some("AssocType"), span: Some(Span { filename: "src/lib.rs", begin: (8, 4), end: (8, 26) }), visibility: Default, docs: None, links: {}, attrs: [], deprecation: None, inner: Typedef(Typedef { type_: Generic("Self"), generics: Generics { params: [], where_predicates: [] } }) }`,
 right: `Item { id: Id("0:7:1558"), crate_id: 0, name: Some("AssocType"), span: Some(Span { filename: "src/lib.rs", begin: (8, 4), end: (8, 26) }), visibility: Default, docs: None, links: {}, attrs: [], deprecation: None, inner: Typedef(Typedef { type_: Generic("T"), generics: Generics { params: [], where_predicates: [] } }) }`', src/librustdoc/json/mod.rs:234:21
```

PR with a fix proposal: https://github.com/rust-lang/rust/pull/98548

@rustbot labels +A-rustdoc-json +I-ICE +T-rustdoc

### PR DESCRIPTION
**Pull request by Enselic**
Closes #98547

This fix is a natural extension of #98053.

r? @notriddle

(Since you reviewed the other PR.)

CC @GuillaumeGomez 

@rustbot labels +A-rustdoc-json +T-rustdoc

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Why ignoring typedef items?

**Comment by Enselic** [comment]
I'm not sure I'm following. I could ask the same about  `types::ItemEnum::Method(_) | types::ItemEnum::AssocConst { .. } | types::ItemEnum::AssocType { .. } | types::ItemEnum::PrimitiveType(_)`, couldn't I?

Anyway,  I just read that https://github.com/rust-lang/rust/pull/98577 fixes this ICE too. Once that PR lands, I will verify, and if the ICE indeed is fixed, I will close this PR.

**Comment by GuillaumeGomez** [comment]
The regression test definitely makes sense. Once my PR is fixed, please update yours then I'll approve it.

File: src/test/rustdoc-json/assoc_type.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+pub trait Trait {
+    type AssocType;
+}
+
+impl<T> Trait for T {
+    type AssocType = Self;
+}
+
+pub struct S;
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-json/assoc_type.rs:16]: To be sure about the "conflict", can you add another `struct` please?

Comment (Enselic) [reply src/test/rustdoc-json/assoc_type.rs:16]: I will do whatever changes you like, but I want to make sure I understand them first, and I don't understand what you mean, so could you clarify please? What do you mean with "conflict"? Before the fix, if we remove `pub struct S;`, the ICE stops from happening. Why don't we want this to be a minimal reproducer? Why do we want to add irrelevant code?

Comment (GuillaumeGomez) [reply src/test/rustdoc-json/assoc_type.rs:16]: Sure, let me explain then: because of the blanket impl (`impl<T> Trait for T {`), all items will implement `Trait` and the `DefId` of `AssocType` will be the same for all types. In this case, it means `S` implements it. I was asking you to add another `struct` to be 100% sure that the `DefId` conflict would appear because there are multiple impl with the same `DefId` for `AssocType`.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Comment by Enselic** [comment]
Thanks for the help with fixing #98547! You had a better fix :)

**Comment by GuillaumeGomez** [comment]
Sorry I didn't see your PR sooner... I would have helped you go through.
