### PR TITLE
Fix #53820

### LINKED ISSUE #53820: Stack overflow compiling slice pattern for big array
The following fails with a stack overflow:
```rust
#![feature(slice_patterns)]

fn main() {
    match [0u8; 16*1024] {
        [..] => {}
    }
}
```
I see tests failing on miri's CI on Windows when the size is just `1024`, so my suspicion is that this code will fail to compile on Windows with a smaller slice -- but I do not have a Windows machine to test that.

### PR DESCRIPTION
**Pull request by Nadrieril**
This fixes ICE #53820 by being more clever when matching large arrays with slice patterns.
In particular, it avoids treating large arrays like large tuples, and instead reuses the `VarLenSlice` constructor behaviour to only consider as little values as needed.
As a side-effect, such matches also get improved diagnostics, by reporting `[true, ..]` missing instead of `[true, _, _, _, _, _, _, _]`.

### CODE REVIEW

File: src/librustc_mir/hair/pattern/_match.rs [hunk 1]
```diff
@@ -582,6 +583,114 @@ impl<'a, 'tcx> MatchCheckCtxt<'a, 'tcx> {
...
+    }
+
+    /// Returns a collection of slices that spans the values covered by `self`, subtracted by the
+    /// values covered by `other`: i.e., `self \ other` (in set notation).
+    fn subtract(self, other: Self) -> SmallVec<[Self; 1]> {
+        // Remember, `VarLen(i, j)` covers the union of `FixedLen` from `i + j` to infinity.
+        // Naming: we remove the "neg" constructors from the "pos" ones.
+        match self {
+            FixedLen(pos_len) => {
+                if other.covers_length(pos_len) {
```
Comment (Centril) [inline src/librustc_mir/hair/pattern/_match.rs]: Might be nicer as a guard?

File: src/librustc_mir/hair/pattern/_match.rs [hunk 2]
```diff
@@ -582,6 +583,114 @@ impl<'a, 'tcx> MatchCheckCtxt<'a, 'tcx> {
...
+                    smallvec![]
+                } else {
+                    smallvec![self]
+                }
+            }
+            VarLen(pos_prefix, pos_suffix) => {
+                let pos_len = pos_prefix + pos_suffix;
+                match other {
+                    FixedLen(neg_len) => {
+                        if neg_len < pos_len {
```
Comment (Centril) [inline src/librustc_mir/hair/pattern/_match.rs]: Maybe a guard here too?

File: src/test/ui/pattern/issue-53820-slice-pattern-large-array.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+// check-pass
```
Comment (Centril) [inline src/test/ui/pattern/issue-53820-slice-pattern-large-array.rs]:
```suggestion
// check-pass

// This used to cause a stack overflow in the compiler.

```

File: src/librustc_mir/hair/pattern/_match.rs [hunk 4]
```diff
@@ -884,15 +963,29 @@ impl<'tcx> Constructor<'tcx> {
...
+                }
+                VarLen(prefix, _) => {
+                    let mut prefix: Vec<_> = subpatterns.by_ref().take(prefix as usize).collect();
+                    let mut suffix: Vec<_> = subpatterns.collect();
+                    if slice.array_len.is_some() {
+                        // Improves diagnostics a bit: if the type is a known-size array, instead
+                        // of reporting `[x, _, .., _, y]`, we prefer to report `[x, .., y]`.
+                        // This is incorrect if the size is not known, since `[_, ..]` captures
+                        // arrays of lengths `>= 1` whereas `[..]` captures any length.
+                        while !suffix.is_empty() && suffix.first().unwrap().is_wildcard() {
```
Comment (Centril) [inline src/librustc_mir/hair/pattern/_match.rs]: Continually removing from the front of the vector seems like it could regress perf (tho the number of elements is likely small...)? Perhaps amortize the cost by first calculating the number of elements from the front to remove and then using `.drain(...)`. Alternatively, use `.skip_while(...)` when computing `suffix` (with a fast path for `slice.array_len.is_none()`) -- conversely, you can use `.take_while(...)` for `prefix` but that will need to go over everything until the first wildcard.

**Comment by varkor** [comment]
Implementation looks good! r=me, but I'll give you some time to consider @Centril's suggestions.

File: src/librustc_mir/hair/pattern/_match.rs (hunk 2 above)
Comment (Nadrieril) [reply src/librustc_mir/hair/pattern/_match.rs]: I liked the symmetry between the different cases, do you have a string opinion on using a guard here ?

Comment (Centril) [reply src/librustc_mir/hair/pattern/_match.rs]: No it's just a minor suggestion :)

Comment (Nadrieril) [reply src/librustc_mir/hair/pattern/_match.rs]: Then I'd rather keep it like this :)

**Comment by Nadrieril** [comment]
Reviews have been adressed !
