### PR TITLE
Downgrade unit struct match via S(..) warnings to errors

### LINKED ISSUE #30379: beta regression matching unit-like structs with ..
This code

```rust
struct Empty;

match Empty {
    Empty(..) => {}
}
```

compiles on stable 1.5 (no RFC 218 warning) but fails on beta 1.6 with E0164.

### PR DESCRIPTION
**Pull request by pnkfelix**
Downgrade unit struct match via S(..) warnings to errors

The error signalling was introduced in #29383

It was noted as a warning-cycle-less regression in #30379

Fix #30379

### CODE REVIEW

**Comment by pnkfelix** [comment]
r? @nikomatsakis 

(This is high priority regression fix)

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -659,6 +659,12 @@ pub fn check_pat_enum<'a, 'tcx>(pcx: &pat_ctxt<'a, 'tcx>,
     let report_bad_struct_kind = |is_warning| {
         bad_struct_kind_err(tcx.sess, pat.span, path, is_warning);
         if is_warning {
+            // Boo! Too painful to attach this to the actual warning,
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: Hmm, I think we should modify `bad_struct_kind_err` to look at `is_warning` and add a lint in the case of `is_warning == true`. This will also require adding a new lint corresponding to this future incompatibility. That said, I was going to do a quick PR to improve that tooling so as to address https://github.com/rust-lang/rust/issues/30746, so maybe I could just roll that change into that.

Comment (pnkfelix) [inline src/librustc_typeck/check/_match.rs]: I debated about doing this but decided I was better off keeping this PR minimal to ease backporting to beta... what do you think?

**Comment by pnkfelix** [comment]
@nikomatsakis Okay I think this is what you want w.r.t. the lint structure. How does this look to you?

**Comment by nikomatsakis** [comment]
Looks great!

@bors r+

**Comment by pnkfelix** [comment]
```
failures:

    [compile-fail] compile-fail/match-pattern-field-mismatch-2.rs

    [compile-fail] compile-fail/pattern-error-continue.rs

```

hmm, why did that arise on the travis build

**Comment by pnkfelix** [comment]
@bors r-

i need to look at the two failure cases

**Comment by pnkfelix** [comment]
@bors p=1

(upping priority for regression fixing or beta-nominated PR's)

**Comment by pnkfelix** [comment]
@nikomatsakis  I added #30724 to the beta-nominated set because it seemed like a natural candidate for a back port to beta (and also because 40a2ec2 in this PR depends on infrastructure added by that PR)

however,  given that the beta is going to be cut very soon,  perhaps back porting, PR #30724 would be unwise, and thus I should make a separate PR against beta branch that only goes up to 8aed830  (inclusive)

Thoughts? 

Cc @brson @rust-lang/compiler

File: src/librustc_typeck/check/_match.rs (hunk 1 above)
Comment (pnkfelix) [inline src/librustc_typeck/check/_match.rs]: (I think I should have pushed back harder here.   But then again I didn't expect bors to take four days to get to this)

**Comment by nikomatsakis** [comment]
@pnkfelix and I discussed on IRC -- seems like best thing is to backport this PR and just the (very few) bits of infrastructure needed to make it work.
