### PR TITLE
don't ICE on higher ranked hidden types

### LINKED ISSUE #97098: ICE with GAT + higher-ranked TAIT
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=79716e12fc3dad407ef9acb6d40392c1)

```rust
#![feature(type_alias_impl_trait)]
#![feature(generic_associated_types)]

pub trait Trait {
    type Assoc<'a>;
}

pub type Foo = impl for<'a> Trait<Assoc<'a> = FooAssoc<'a>>;
pub type FooAssoc<'a> = impl Sized;

struct Struct;
impl Trait for Struct {
    type Assoc<'a> = &'a u32;
}

const FOO: Foo = Struct;
```

```rust
error: internal compiler error: compiler/rustc_trait_selection/src/opaque_types.rs:326:17: unexpected region kind in opaque type: RePlaceholder(Placeholder { universe: U1, name: BrNamed(DefId(0:8 ~ playground[9145]::Foo::{opaque#0}::'a), 'a) })

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/compiler/rustc_errors/src/lib.rs:1335:9
stack backtrace:
   0:     0x7f5f8516ff8d - std::backtrace_rs::backtrace::libunwind::trace::h67b1c8cf8ce320d0
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5f8516ff8d - std::backtrace_rs::backtrace::trace_unsynchronized::hd715d6ee36d01457
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5f8516ff8d - std::sys_common::backtrace::_print_fmt::h86f2d6902c17b72b
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5f8516ff8d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2f28719fc9d49991
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5f851cbc1c - core::fmt::write::h58d80b2387526c14
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f5f85161661 - std::io::Write::write_fmt::h51e24b646b1d9dea
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/io/mod.rs:1654:15
   6:     0x7f5f85172ca5 - std::sys_common::backtrace::_print::h08306e60302c2601
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5f85172ca5 - std::sys_common::backtrace::print::h8bee5b1ce7ed0828
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5f85172ca5 - std::panicking::default_hook::{{closure}}::h0135f80d264aa3cb
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:295:22
   9:     0x7f5f85172919 - std::panicking::default_hook::haf57ee52e612f636
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:314:9
  10:     0x7f5f85938b21 - rustc_driver[52a5108fb431eaec]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f5f85173476 - std::panicking::rust_panic_with_hook::h4cd397120086e208
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:702:17
  12:     0x7f5f869c26a1 - std[6756e547c62c76a1]::panicking::begin_panic::<rustc_errors[a3b3cd9ac4cd0404]::ExplicitBug>::{closure#0}
  13:     0x7f5f869bc886 - std[6756e547c62c76a1]::sys_common::backtrace::__rust_end_short_backtrace::<std[6756e547c62c76a1]::panicking::begin_panic<rustc_errors[a3b3cd9ac4cd0404]::ExplicitBug>::{closure#0}, !>
  14:     0x7f5f86951aa6 - std[6756e547c62c76a1]::panicking::begin_panic::<rustc_errors[a3b3cd9ac4cd0404]::ExplicitBug>
  15:     0x7f5f86907306 - std[6756e547c62c76a1]::panic::panic_any::<rustc_errors[a3b3cd9ac4cd0404]::ExplicitBug>
  16:     0x7f5f86903575 - <rustc_errors[a3b3cd9ac4cd0404]::HandlerInner>::bug::<&alloc[37b6f05715a7cc80]::string::String>
  17:     0x7f5f86902f80 - <rustc_errors[a3b3cd9ac4cd0404]::Handler>::bug::<&alloc[37b6f05715a7cc80]::string::String>
  18:     0x7f5f869cb05d - rustc_middle[98c7c48ec55f2d30]::ty::context::tls::with_opt::<rustc_middle[98c7c48ec55f2d30]::util::bug::opt_span_bug_fmt<rustc_span[6ccf8f5ca5317a27]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7f5f869cb3d6 - rustc_middle[98c7c48ec55f2d30]::util::bug::opt_span_bug_fmt::<rustc_span[6ccf8f5ca5317a27]::span_encoding::Span>
  20:     0x7f5f869cb353 - rustc_middle[98c7c48ec55f2d30]::util::bug::bug_fmt
  21:     0x7f5f88183fd2 - <rustc_trait_selection[6e50549df9c71920]::opaque_types::ReverseMapper as rustc_middle[98c7c48ec55f2d30]::ty::fold::TypeFolder>::fold_region
  22:     0x7f5f88188465 - <rustc_middle[98c7c48ec55f2d30]::ty::Ty as rustc_middle[98c7c48ec55f2d30]::ty::fold::TypeFoldable>::super_fold_with::<rustc_trait_selection[6e50549df9c71920]::opaque_types::ReverseMapper>
  23:     0x7f5f881542fe - <rustc_infer[91e6494644033aa9]::infer::InferCtxt as rustc_trait_selection[6e50549df9c71920]::opaque_types::InferCtxtExt>::infer_opaque_definition_from_instantiation
  24:     0x7f5f872199f0 - <rustc_borrowck[7ebf6aea16ae1e27]::region_infer::RegionInferenceContext>::infer_opaque_types
  25:     0x7f5f871830f4 - rustc_borrowck[7ebf6aea16ae1e27]::nll::compute_regions
  26:     0x7f5f871eea2e - rustc_borrowck[7ebf6aea16ae1e27]::do_mir_borrowck
  27:     0x7f5f871e76b9 - rustc_borrowck[7ebf6aea16ae1e27]::mir_borrowck
  28:     0x7f5f871e4420 - <rustc_borrowck[7ebf6aea16ae1e27]::provide::{closure#0} as core[696ac347caa2bd44]::ops::function::FnOnce<(rustc_middle[98c7c48ec55f2d30]::ty::context::TyCtxt, rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId)>>::call_once
  29:     0x7f5f87414d50 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId, &rustc_middle[98c7c48ec55f2d30]::mir::query::BorrowCheckResult>>
  30:     0x7f5f873dfeea - <rustc_query_impl[571ef98d1fbb149a]::Queries as rustc_middle[98c7c48ec55f2d30]::ty::query::QueryEngine>::mir_borrowck
  31:     0x7f5f85d2ea50 - <rustc_typeck[bf5d8a66ba319940]::collect::type_of::find_opaque_ty_constraints::ConstraintLocator>::check
  32:     0x7f5f85d2e5b8 - <rustc_typeck[bf5d8a66ba319940]::collect::type_of::find_opaque_ty_constraints::ConstraintLocator as rustc_hir[c624ea387cefbc39]::intravisit::Visitor>::visit_item
  33:     0x7f5f85d2aed5 - <rustc_typeck[bf5d8a66ba319940]::collect::type_of::find_opaque_ty_constraints::ConstraintLocator as rustc_hir[c624ea387cefbc39]::intravisit::Visitor>::visit_nested_item
  34:     0x7f5f85c55c57 - rustc_hir[c624ea387cefbc39]::intravisit::walk_mod::<rustc_typeck[bf5d8a66ba319940]::collect::type_of::find_opaque_ty_constraints::ConstraintLocator>
  35:     0x7f5f85d2e300 - rustc_typeck[bf5d8a66ba319940]::collect::type_of::find_opaque_ty_constraints
  36:     0x7f5f86f32bb2 - rustc_typeck[bf5d8a66ba319940]::collect::type_of::type_of
  37:     0x7f5f8745b517 - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::type_of, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  38:     0x7f5f86f3bc95 - rustc_typeck[bf5d8a66ba319940]::check::check::check_item_type
  39:     0x7f5f86f411fb - rustc_typeck[bf5d8a66ba319940]::check::check::check_mod_item_types
  40:     0x7f5f87416d70 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId, ()>>
  41:     0x7f5f87f6aae3 - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::check_mod_item_types, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  42:     0x7f5f87c8685d - <rustc_middle[98c7c48ec55f2d30]::hir::map::Map>::for_each_module::<rustc_typeck[bf5d8a66ba319940]::check_crate::{closure#6}::{closure#0}>
  43:     0x7f5f87c64668 - <rustc_session[abce4e7f97e3a707]::session::Session>::time::<(), rustc_typeck[bf5d8a66ba319940]::check_crate::{closure#6}>
  44:     0x7f5f87c4ce68 - rustc_typeck[bf5d8a66ba319940]::check_crate
  45:     0x7f5f879e6e87 - rustc_interface[f634dffaf1f1ed4]::passes::analysis
  46:     0x7f5f87f38574 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<(), core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>>
  47:     0x7f5f87f79c7e - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::analysis, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  48:     0x7f5f879c78e7 - <rustc_interface[f634dffaf1f1ed4]::passes::QueryContext>::enter::<rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  49:     0x7f5f879b2938 - <rustc_interface[f634dffaf1f1ed4]::interface::Compiler>::enter::<rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}::{closure#2}, core[696ac347caa2bd44]::result::Result<core[696ac347caa2bd44]::option::Option<rustc_interface[f634dffaf1f1ed4]::queries::Linker>, rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  50:     0x7f5f879db02f - rustc_span[6ccf8f5ca5317a27]::with_source_map::<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_interface[f634dffaf1f1ed4]::interface::create_compiler_and_run<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#1}>
  51:     0x7f5f879b35a4 - rustc_interface[f634dffaf1f1ed4]::interface::create_compiler_and_run::<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>
  52:     0x7f5f879b0e42 - <scoped_tls[5bcfd69aea41704b]::ScopedKey<rustc_span[6ccf8f5ca5317a27]::SessionGlobals>>::set::<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  53:     0x7f5f879c7f6f - std[6756e547c62c76a1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f634dffaf1f1ed4]::util::run_in_thread_pool_with_globals<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  54:     0x7f5f879c80a9 - <<std[6756e547c62c76a1]::thread::Builder>::spawn_unchecked_<rustc_interface[f634dffaf1f1ed4]::util::run_in_thread_pool_with_globals<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#1} as core[696ac347caa2bd44]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7f5f8517d393 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h14e46baa6d22d347
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/alloc/src/boxed.rs:1872:9
  56:     0x7f5f8517d393 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ebfb42aa2b9da7a
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/alloc/src/boxed.rs:1872:9
  57:     0x7f5f8517d393 - std::sys::unix::thread::Thread::new::thread_start::hff1811d6a35504cb
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7f5f850ad609 - start_thread
  59:     0x7f5f84fc6133 - clone
  60:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (42e1761c7 2022-05-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `FOO`
#1 [type_of] computing type of `Foo::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
```

rustc 1.63.0-nightly (42e1761c7 2022-05-15)

### LINKED ISSUE #97099: ICE with higher-ranked nested RPIT
I arrived at this by trying to make #97098 work on stable. I don't know if the root cause is the same, since the ICE message is different I'm  posting it anyway.

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dc1d284651b1e4456e691a39adb780e1)

```rust
pub trait Trait<'a> {
    type Assoc;
}

struct Struct;
impl<'a> Trait<'a> for Struct {
    type Assoc = &'a u32;
}

fn blah() -> impl for<'a> Trait<'a, Assoc = impl Sized> {
    Struct
}
```

It fails to build in stable (I think it should build though..?)

```
error: implementation of `Trait` is not general enough
  --> src/lib.rs:10:14
   |
10 | fn blah() -> impl for<'a> Trait<'a, Assoc = impl Sized> {
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Trait` is not general enough
   |
   = note: `Struct` must implement `Trait<'0>`, for any lifetime `'0`...
   = note: ...but it actually implements `Trait<'1>`, for some specific lifetime `'1`
```

but It ICEs in latest nightly

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:708:9
stack backtrace:
   0:     0x7f078620ef8d - std::backtrace_rs::backtrace::libunwind::trace::h67b1c8cf8ce320d0
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f078620ef8d - std::backtrace_rs::backtrace::trace_unsynchronized::hd715d6ee36d01457
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f078620ef8d - std::sys_common::backtrace::_print_fmt::h86f2d6902c17b72b
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f078620ef8d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2f28719fc9d49991
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f078626ac1c - core::fmt::write::h58d80b2387526c14
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f0786200661 - std::io::Write::write_fmt::h51e24b646b1d9dea
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/io/mod.rs:1654:15
   6:     0x7f0786211ca5 - std::sys_common::backtrace::_print::h08306e60302c2601
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f0786211ca5 - std::sys_common::backtrace::print::h8bee5b1ce7ed0828
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f0786211ca5 - std::panicking::default_hook::{{closure}}::h0135f80d264aa3cb
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:295:22
   9:     0x7f0786211919 - std::panicking::default_hook::haf57ee52e612f636
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:314:9
  10:     0x7f07869d7b21 - rustc_driver[52a5108fb431eaec]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f0786212476 - std::panicking::rust_panic_with_hook::h4cd397120086e208
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:702:17
  12:     0x7f0786212239 - std::panicking::begin_panic_handler::{{closure}}::hf500f2fbd8a1acc4
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:586:13
  13:     0x7f078620f444 - std::sys_common::backtrace::__rust_end_short_backtrace::h67b4e62db9dc2797
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f0786211fa9 - rust_begin_unwind
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/panicking.rs:584:5
  15:     0x7f07861d7223 - core::panicking::panic_fmt::h99ba80b725ad2949
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/core/src/panicking.rs:142:14
  16:     0x7f07861d70ed - core::panicking::panic::hfa244e9d3623fb7d
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/core/src/panicking.rs:48:5
  17:     0x7f07882bc4b8 - <rustc_borrowck[7ebf6aea16ae1e27]::region_infer::RegionInferenceContext>::solve
  18:     0x7f0788222077 - rustc_borrowck[7ebf6aea16ae1e27]::nll::compute_regions
  19:     0x7f078828da2e - rustc_borrowck[7ebf6aea16ae1e27]::do_mir_borrowck
  20:     0x7f07882866b9 - rustc_borrowck[7ebf6aea16ae1e27]::mir_borrowck
  21:     0x7f0788283420 - <rustc_borrowck[7ebf6aea16ae1e27]::provide::{closure#0} as core[696ac347caa2bd44]::ops::function::FnOnce<(rustc_middle[98c7c48ec55f2d30]::ty::context::TyCtxt, rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId)>>::call_once
  22:     0x7f07884b3d50 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId, &rustc_middle[98c7c48ec55f2d30]::mir::query::BorrowCheckResult>>
  23:     0x7f078847eeea - <rustc_query_impl[571ef98d1fbb149a]::Queries as rustc_middle[98c7c48ec55f2d30]::ty::query::QueryEngine>::mir_borrowck
  24:     0x7f0787fd0d80 - rustc_typeck[bf5d8a66ba319940]::collect::type_of::type_of
  25:     0x7f07884fa517 - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::type_of, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  26:     0x7f0787fdac95 - rustc_typeck[bf5d8a66ba319940]::check::check::check_item_type
  27:     0x7f0787fe01fb - rustc_typeck[bf5d8a66ba319940]::check::check::check_mod_item_types
  28:     0x7f07884b5d70 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<rustc_span[6ccf8f5ca5317a27]::def_id::LocalDefId, ()>>
  29:     0x7f0789009ae3 - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::check_mod_item_types, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  30:     0x7f0788d2585d - <rustc_middle[98c7c48ec55f2d30]::hir::map::Map>::for_each_module::<rustc_typeck[bf5d8a66ba319940]::check_crate::{closure#6}::{closure#0}>
  31:     0x7f0788d03668 - <rustc_session[abce4e7f97e3a707]::session::Session>::time::<(), rustc_typeck[bf5d8a66ba319940]::check_crate::{closure#6}>
  32:     0x7f0788cebe68 - rustc_typeck[bf5d8a66ba319940]::check_crate
  33:     0x7f0788a85e87 - rustc_interface[f634dffaf1f1ed4]::passes::analysis
  34:     0x7f0788fd7574 - rustc_query_system[202e2af03b29f868]::query::plumbing::try_execute_query::<rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt, rustc_query_system[202e2af03b29f868]::query::caches::DefaultCache<(), core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>>
  35:     0x7f0789018c7e - rustc_query_system[202e2af03b29f868]::query::plumbing::get_query::<rustc_query_impl[571ef98d1fbb149a]::queries::analysis, rustc_query_impl[571ef98d1fbb149a]::plumbing::QueryCtxt>
  36:     0x7f0788a668e7 - <rustc_interface[f634dffaf1f1ed4]::passes::QueryContext>::enter::<rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  37:     0x7f0788a51938 - <rustc_interface[f634dffaf1f1ed4]::interface::Compiler>::enter::<rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}::{closure#2}, core[696ac347caa2bd44]::result::Result<core[696ac347caa2bd44]::option::Option<rustc_interface[f634dffaf1f1ed4]::queries::Linker>, rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  38:     0x7f0788a7a02f - rustc_span[6ccf8f5ca5317a27]::with_source_map::<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_interface[f634dffaf1f1ed4]::interface::create_compiler_and_run<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#1}>
  39:     0x7f0788a525a4 - rustc_interface[f634dffaf1f1ed4]::interface::create_compiler_and_run::<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>
  40:     0x7f0788a4fe42 - <scoped_tls[5bcfd69aea41704b]::ScopedKey<rustc_span[6ccf8f5ca5317a27]::SessionGlobals>>::set::<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  41:     0x7f0788a66f6f - std[6756e547c62c76a1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f634dffaf1f1ed4]::util::run_in_thread_pool_with_globals<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>
  42:     0x7f0788a670a9 - <<std[6756e547c62c76a1]::thread::Builder>::spawn_unchecked_<rustc_interface[f634dffaf1f1ed4]::util::run_in_thread_pool_with_globals<rustc_interface[f634dffaf1f1ed4]::interface::run_compiler<core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>, rustc_driver[52a5108fb431eaec]::run_compiler::{closure#1}>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#0}, core[696ac347caa2bd44]::result::Result<(), rustc_errors[a3b3cd9ac4cd0404]::ErrorGuaranteed>>::{closure#1} as core[696ac347caa2bd44]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f078621c393 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h14e46baa6d22d347
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/alloc/src/boxed.rs:1872:9
  44:     0x7f078621c393 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ebfb42aa2b9da7a
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/alloc/src/boxed.rs:1872:9
  45:     0x7f078621c393 - std::sys::unix::thread::Thread::new::thread_start::hff1811d6a35504cb
                               at /rustc/42e1761c704f074b7b8c7ff8a7433acfd65d2ee9/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7f078614c609 - start_thread
  47:     0x7f0786065133 - clone
  48:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (42e1761c7 2022-05-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `blah`
#1 [type_of] computing type of `blah::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
```

### LINKED ISSUE #100818: Compiler crash with type_alias_impl_trait on the very latest version
### Code

```Rust
#![feature(type_alias_impl_trait)]
use std::future::Future;

fn main() {
    type SomeFuture<'t> = impl 't + Future<Output = ()>;
    type SomeClosure = impl for<'t> FnOnce(&'t str) -> SomeFuture<'t>;
    fn coerce_closure(f: SomeClosure) {}
    coerce_closure(|x: &str| async move {});
}
```

This crashes with the very latest version (`cargo +nightly-2022-08-19 run`), but not with the previous version (`cargo +nightly-2022-08-18 run`)

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (e1b28cd2f 2022-08-19)
binary: rustc
commit-hash: e1b28cd2f16bd5b832183d7968cae3bb9213e78d
commit-date: 2022-08-19
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### Error output

```
   Compiling testing_stuff v0.1.0 (/tmp/testing_stuff)
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:718:9
stack backtrace:
   0:     0x7f09ef36e6d0 - std::backtrace_rs::backtrace::libunwind::trace::h850ff1a0c3d9fdd7
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f09ef36e6d0 - std::backtrace_rs::backtrace::trace_unsynchronized::hb027726a633b9940
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f09ef36e6d0 - std::sys_common::backtrace::_print_fmt::h5caab733d2f6988a
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f09ef36e6d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdde469ef2c900889
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f09ef3c976e - core::fmt::write::h652f9c882cd915d6
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f09ef35f5d5 - std::io::Write::write_fmt::hc86f310f58407a21
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/io/mod.rs:1672:15
   6:     0x7f09ef371393 - std::sys_common::backtrace::_print::he3151b9612f2cb1c
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f09ef371393 - std::sys_common::backtrace::print::h4ec5b0bf2cf6801f
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f09ef371393 - std::panicking::default_hook::{{closure}}::h0eea56e2b7a0583d
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:295:22
   9:     0x7f09ef37107f - std::panicking::default_hook::h9faf2b89120c3ca0
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:314:9
  10:     0x7f09f1bab494 - rustc_driver[8170f2effe76d0b1]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f09ef371bcd - std::panicking::rust_panic_with_hook::h41881d4c2e288663
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:702:17
  12:     0x7f09ef3719e1 - std::panicking::begin_panic_handler::{{closure}}::h7434a1ed3ac56100
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:586:13
  13:     0x7f09ef36ebdc - std::sys_common::backtrace::__rust_end_short_backtrace::hbf29cadbfa104d7f
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f09ef371742 - rust_begin_unwind
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:584:5
  15:     0x7f09ef3c6283 - core::panicking::panic_fmt::hb36dfafe85614116
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/core/src/panicking.rs:142:14
  16:     0x7f09ef3c60cd - core::panicking::panic::hd4b68b0dd41a23c9
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/core/src/panicking.rs:48:5
  17:     0x7f09f09940e4 - <rustc_borrowck[3abe5495380e92d7]::region_infer::RegionInferenceContext>::solve
  18:     0x7f09f09675b9 - rustc_borrowck[3abe5495380e92d7]::nll::compute_regions
  19:     0x7f09f090cb16 - rustc_borrowck[3abe5495380e92d7]::do_mir_borrowck
  20:     0x7f09f153f85c - rustc_borrowck[3abe5495380e92d7]::mir_borrowck
  21:     0x7f09f153f011 - <rustc_borrowck[3abe5495380e92d7]::provide::{closure#0} as core[ca3ac0430488f954]::ops::function::FnOnce<(rustc_middle[f312dfbcb803dd41]::ty::context::TyCtxt, rustc_span[3aa3f8a4aae1164f]::def_id::LocalDefId)>>::call_once
  22:     0x7f09f0f3053d - <rustc_query_system[c671b936ad850e7d]::dep_graph::graph::DepGraph<rustc_middle[f312dfbcb803dd41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f312dfbcb803dd41]::ty::context::TyCtxt, rustc_span[3aa3f8a4aae1164f]::def_id::LocalDefId, &rustc_middle[f312dfbcb803dd41]::mir::query::BorrowCheckResult>
  23:     0x7f09f0f2f80d - rustc_query_system[c671b936ad850e7d]::query::plumbing::try_execute_query::<rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt, rustc_query_system[c671b936ad850e7d]::query::caches::DefaultCache<rustc_span[3aa3f8a4aae1164f]::def_id::LocalDefId, &rustc_middle[f312dfbcb803dd41]::mir::query::BorrowCheckResult>>
  24:     0x7f09f1ab060a - <rustc_query_impl[f43bacc242a2796b]::Queries as rustc_middle[f312dfbcb803dd41]::ty::query::QueryEngine>::mir_borrowck
  25:     0x7f09f1f66e42 - <rustc_typeck[3f43e31030e845d6]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
  26:     0x7f09f1f667be - rustc_typeck[3f43e31030e845d6]::collect::type_of::find_opaque_ty_constraints_for_tait
  27:     0x7f09f181cc6d - rustc_typeck[3f43e31030e845d6]::collect::type_of::type_of
  28:     0x7f09f0f99177 - <rustc_query_system[c671b936ad850e7d]::dep_graph::graph::DepGraph<rustc_middle[f312dfbcb803dd41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f312dfbcb803dd41]::ty::context::TyCtxt, rustc_span[3aa3f8a4aae1164f]::def_id::DefId, rustc_middle[f312dfbcb803dd41]::ty::Ty>
  29:     0x7f09f0f971eb - rustc_query_system[c671b936ad850e7d]::query::plumbing::get_query::<rustc_query_impl[f43bacc242a2796b]::queries::type_of, rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt>
  30:     0x7f09f149edcb - rustc_typeck[3f43e31030e845d6]::check::check::check_item_type
  31:     0x7f09f149b10e - rustc_typeck[3f43e31030e845d6]::check::check::check_mod_item_types
  32:     0x7f09f0a8c8f1 - <rustc_query_system[c671b936ad850e7d]::dep_graph::graph::DepGraph<rustc_middle[f312dfbcb803dd41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f312dfbcb803dd41]::ty::context::TyCtxt, rustc_span[3aa3f8a4aae1164f]::def_id::LocalDefId, ()>
  33:     0x7f09f0a8b992 - rustc_query_system[c671b936ad850e7d]::query::plumbing::try_execute_query::<rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt, rustc_query_system[c671b936ad850e7d]::query::caches::DefaultCache<rustc_span[3aa3f8a4aae1164f]::def_id::LocalDefId, ()>>
  34:     0x7f09f15f2b13 - rustc_query_system[c671b936ad850e7d]::query::plumbing::get_query::<rustc_query_impl[f43bacc242a2796b]::queries::check_mod_item_types, rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt>
  35:     0x7f09f188e24c - <rustc_middle[f312dfbcb803dd41]::hir::map::Map>::for_each_module::<rustc_typeck[3f43e31030e845d6]::check_crate::{closure#6}::{closure#0}>
  36:     0x7f09f1582b15 - rustc_typeck[3f43e31030e845d6]::check_crate
  37:     0x7f09f1582557 - rustc_interface[3d10aad4a167cf18]::passes::analysis
  38:     0x7f09f1943452 - <rustc_query_system[c671b936ad850e7d]::dep_graph::graph::DepGraph<rustc_middle[f312dfbcb803dd41]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f312dfbcb803dd41]::ty::context::TyCtxt, (), core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>
  39:     0x7f09f1942bd7 - rustc_query_system[c671b936ad850e7d]::query::plumbing::try_execute_query::<rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt, rustc_query_system[c671b936ad850e7d]::query::caches::DefaultCache<(), core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>>
  40:     0x7f09f19426ce - rustc_query_system[c671b936ad850e7d]::query::plumbing::get_query::<rustc_query_impl[f43bacc242a2796b]::queries::analysis, rustc_query_impl[f43bacc242a2796b]::plumbing::QueryCtxt>
  41:     0x7f09f12c6d5e - <rustc_interface[3d10aad4a167cf18]::passes::QueryContext>::enter::<rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>
  42:     0x7f09f12c2e1e - <rustc_interface[3d10aad4a167cf18]::interface::Compiler>::enter::<rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}::{closure#2}, core[ca3ac0430488f954]::result::Result<core[ca3ac0430488f954]::option::Option<rustc_interface[3d10aad4a167cf18]::queries::Linker>, rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>
  43:     0x7f09f12be91c - rustc_span[3aa3f8a4aae1164f]::with_source_map::<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_interface[3d10aad4a167cf18]::interface::create_compiler_and_run<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}>::{closure#1}>
  44:     0x7f09f12be302 - rustc_interface[3d10aad4a167cf18]::interface::create_compiler_and_run::<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}>
  45:     0x7f09f12bcea1 - <scoped_tls[a31a4b7c7b1b4a01]::ScopedKey<rustc_span[3aa3f8a4aae1164f]::SessionGlobals>>::set::<rustc_interface[3d10aad4a167cf18]::interface::run_compiler<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}>::{closure#0}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>
  46:     0x7f09f12bcb8f - std[6176ebdb849c2141]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3d10aad4a167cf18]::util::run_in_thread_pool_with_globals<rustc_interface[3d10aad4a167cf18]::interface::run_compiler<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}>::{closure#0}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>::{closure#0}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>
  47:     0x7f09f19d42c9 - <<std[6176ebdb849c2141]::thread::Builder>::spawn_unchecked_<rustc_interface[3d10aad4a167cf18]::util::run_in_thread_pool_with_globals<rustc_interface[3d10aad4a167cf18]::interface::run_compiler<core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>, rustc_driver[8170f2effe76d0b1]::run_compiler::{closure#1}>::{closure#0}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>::{closure#0}, core[ca3ac0430488f954]::result::Result<(), rustc_errors[28a60eca1a08eed5]::ErrorGuaranteed>>::{closure#1} as core[ca3ac0430488f954]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f09ef37b9c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20aa7f83790b6d6c
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/alloc/src/boxed.rs:1935:9
  49:     0x7f09ef37b9c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h082931b1ec2f572d
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/alloc/src/boxed.rs:1935:9
  50:     0x7f09ef37b9c3 - std::sys::unix::thread::Thread::new::thread_start::h5e56cc2c93616735
                               at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f09ef087b27 - <unknown>
  52:     0x7f09ef10a78c - <unknown>
  53:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (e1b28cd2f 2022-08-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [type_of] computing type of `main::SomeFuture::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `testing_stuff`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling testing_stuff v0.1.0 (/tmp/testing_stuff)
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:718:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/core/src/panicking.rs:48:5
   3: <rustc_borrowck::region_infer::RegionInferenceContext>::solve
   4: rustc_borrowck::nll::compute_regions
   5: rustc_borrowck::do_mir_borrowck
   6: rustc_borrowck::mir_borrowck
   7: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   8: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
   9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  11: <rustc_typeck::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
  12: rustc_typeck::collect::type_of::find_opaque_ty_constraints_for_tait
  13: rustc_typeck::collect::type_of::type_of
  14: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::Ty>
  15: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>
  16: rustc_typeck::check::check::check_item_type
  17: rustc_typeck::check::check::check_mod_item_types
  18: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  20: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
  21: <rustc_middle::hir::map::Map>::for_each_module::<rustc_typeck::check_crate::{closure#6}::{closure#0}>
  22: rustc_typeck::check_crate
  23: rustc_interface::passes::analysis
  24: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  26: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  27: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  28: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  29: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  30: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  31: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (e1b28cd2f 2022-08-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [type_of] computing type of `main::SomeFuture::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `testing_stuff`

```

</p>
</details>

### LINKED ISSUE #103186: Crash on latest rustup update
Seems similar to this bug: https://github.com/rust-lang/rust/issues/100818, and the affected toolchain seems to be the same:
> This crashes with the very latest version (cargo +nightly-2022-08-19 run), but not with the previous version (cargo +nightly-2022-08-18 run)

### Code
https://github.com/douglas-raillard-arm/lisa/tree/_rust_bug0

git repo: https://github.com/douglas-raillard-arm/lisa.git
branch: _rust_bug0

This is a regular cargo project hosted at:
```
git clone https://github.com/douglas-raillard-arm/lisa.git -b _rust_bug0 
cd lisa/tools/analysis
cargo +nightly build
```

I unfortunately don't have the bandwidth to make a shorter reproducer, but I'll leave this branch untouched so that I don't accidentally remove the condition that triggers the bug.

### Meta

`rustc --version --verbose`:
```
$ rustc +nightly --version --verbose
rustc 1.66.0-nightly (06f049a35 2022-10-17)
binary: rustc
commit-hash: 06f049a35535d26d5c8426d4f782f78277b41aa1
commit-date: 2022-10-17
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2

```

### Error output

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:721:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:721:9
stack backtrace:
   0:     0x7f4c0d4566e0 - std::backtrace_rs::backtrace::libunwind::trace::hf5399c1603f092ca
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f4c0d4566e0 - std::backtrace_rs::backtrace::trace_unsynchronized::hc6fc34f5dc1c74f7
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4c0d4566e0 - std::sys_common::backtrace::_print_fmt::h7d798828e39235a8
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4c0d4566e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h12c08aa7a7a9a2af
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4c0d4b25fe - core::fmt::write::h221fbc267beb0404
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f4c0d446955 - std::io::Write::write_fmt::hf386ea1c52540785
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/io/mod.rs:1682:15
   6:     0x7f4c0d4564a5 - std::sys_common::backtrace::_print::h10c29fc0c250a606
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4c0d4564a5 - std::sys_common::backtrace::print::h37193727d9081e19
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4c0d4592af - std::panicking::default_hook::{{closure}}::h2fbe4b072bd77d72
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/panicking.rs:267:22
   9:     0x7f4c0d458fea - std::panicking::default_hook::h47c73d4904e75e7d
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/panicking.rs:286:9
  10:     0x7f4c0fd8db24 - <rustc_driver[181439583fe95c08]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[6ac417be692c67ad]::ops::function::FnOnce<(&core[6ac417be692c67ad]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4c0d459ad9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4421887e5c0b518b
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/alloc/src/boxed.rs:2001:9
  12:     0x7f4c0d459ad9 - std::panicking::rust_panic_with_hook::h1d0c42788e12b152
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/panicking.rs:692:13
  13:     0x7f4c0d459811 - std::panicking::begin_panic_handler::{{closure}}::h0792a0845aaba9b3
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/panicking.rs:577:13
  14:     0x7f4c0d456b8c - std::sys_common::backtrace::__rust_end_short_backtrace::haa99739b7e05bfed
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f4c0d459572 - rust_begin_unwind
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/panicking.rs:575:5
  16:     0x7f4c0d4aefe3 - core::panicking::panic_fmt::h85ad9577e85cebac
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/core/src/panicking.rs:65:14
  17:     0x7f4c0d4af0bd - core::panicking::panic::hb183d5e113ec83d0
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/core/src/panicking.rs:115:5
  18:     0x7f4c0ecd8261 - <rustc_borrowck[a1c5727b44b0e31b]::region_infer::RegionInferenceContext>::solve
  19:     0x7f4c0ec7974d - rustc_borrowck[a1c5727b44b0e31b]::nll::compute_regions
  20:     0x7f4c0ec4d218 - rustc_borrowck[a1c5727b44b0e31b]::do_mir_borrowck
  21:     0x7f4c0ec4bb40 - rustc_borrowck[a1c5727b44b0e31b]::mir_borrowck
  22:     0x7f4c0ec4b4d1 - <rustc_borrowck[a1c5727b44b0e31b]::provide::{closure#0} as core[6ac417be692c67ad]::ops::function::FnOnce<(rustc_middle[795a42170b3d99e3]::ty::context::TyCtxt, rustc_span[28f29e83648bb1dc]::def_id::LocalDefId)>>::call_once
  23:     0x7f4c0f215553 - <rustc_query_system[8ada4aed46307517]::dep_graph::graph::DepGraph<rustc_middle[795a42170b3d99e3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[795a42170b3d99e3]::ty::context::TyCtxt, rustc_span[28f29e83648bb1dc]::def_id::LocalDefId, &rustc_middle[795a42170b3d99e3]::mir::query::BorrowCheckResult>
  24:     0x7f4c0f214781 - rustc_query_system[8ada4aed46307517]::query::plumbing::try_execute_query::<rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt, rustc_query_system[8ada4aed46307517]::query::caches::DefaultCache<rustc_span[28f29e83648bb1dc]::def_id::LocalDefId, &rustc_middle[795a42170b3d99e3]::mir::query::BorrowCheckResult>>
  25:     0x7f4c0fc54a8e - <rustc_query_impl[420a61a611c5dd58]::Queries as rustc_middle[795a42170b3d99e3]::ty::query::QueryEngine>::mir_borrowck
  26:     0x7f4c0fff384d - <rustc_hir_analysis[4e2e3bda43d4c09a]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
  27:     0x7f4c0ffec691 - <rustc_hir_analysis[4e2e3bda43d4c09a]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator as rustc_hir[5ffb9d7504f637db]::intravisit::Visitor>::visit_nested_item
  28:     0x7f4c100348d9 - rustc_hir[5ffb9d7504f637db]::intravisit::walk_item::<rustc_hir_analysis[4e2e3bda43d4c09a]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>
  29:     0x7f4c0fff3174 - rustc_hir_analysis[4e2e3bda43d4c09a]::collect::type_of::find_opaque_ty_constraints_for_tait
  30:     0x7f4c0fa1532f - rustc_hir_analysis[4e2e3bda43d4c09a]::collect::type_of::type_of
  31:     0x7f4c0f22a293 - <rustc_query_system[8ada4aed46307517]::dep_graph::graph::DepGraph<rustc_middle[795a42170b3d99e3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[795a42170b3d99e3]::ty::context::TyCtxt, rustc_span[28f29e83648bb1dc]::def_id::DefId, rustc_middle[795a42170b3d99e3]::ty::Ty>
  32:     0x7f4c0f228716 - rustc_query_system[8ada4aed46307517]::query::plumbing::get_query::<rustc_query_impl[420a61a611c5dd58]::queries::type_of, rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt>
  33:     0x7f4c0f400d1a - rustc_hir_analysis[4e2e3bda43d4c09a]::check::check::check_mod_item_types
  34:     0x7f4c0f3ed4e3 - <rustc_query_system[8ada4aed46307517]::dep_graph::graph::DepGraph<rustc_middle[795a42170b3d99e3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[795a42170b3d99e3]::ty::context::TyCtxt, rustc_span[28f29e83648bb1dc]::def_id::LocalDefId, ()>
  35:     0x7f4c0f3ec57b - rustc_query_system[8ada4aed46307517]::query::plumbing::try_execute_query::<rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt, rustc_query_system[8ada4aed46307517]::query::caches::DefaultCache<rustc_span[28f29e83648bb1dc]::def_id::LocalDefId, ()>>
  36:     0x7f4c0f7b3b59 - rustc_query_system[8ada4aed46307517]::query::plumbing::get_query::<rustc_query_impl[420a61a611c5dd58]::queries::check_mod_item_types, rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt>
  37:     0x7f4c0fa75ccc - <rustc_middle[795a42170b3d99e3]::hir::map::Map>::for_each_module::<rustc_hir_analysis[4e2e3bda43d4c09a]::check_crate::{closure#6}::{closure#0}>
  38:     0x7f4c0f7748f5 - rustc_hir_analysis[4e2e3bda43d4c09a]::check_crate
  39:     0x7f4c0f774427 - rustc_interface[41d053c15137b84f]::passes::analysis
  40:     0x7f4c0fb1d476 - <rustc_query_system[8ada4aed46307517]::dep_graph::graph::DepGraph<rustc_middle[795a42170b3d99e3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[795a42170b3d99e3]::ty::context::TyCtxt, (), core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>
  41:     0x7f4c0fb1c816 - rustc_query_system[8ada4aed46307517]::query::plumbing::try_execute_query::<rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt, rustc_query_system[8ada4aed46307517]::query::caches::DefaultCache<(), core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>>
  42:     0x7f4c0fb1c2f7 - rustc_query_system[8ada4aed46307517]::query::plumbing::get_query::<rustc_query_impl[420a61a611c5dd58]::queries::analysis, rustc_query_impl[420a61a611c5dd58]::plumbing::QueryCtxt>
  43:     0x7f4c0ead95d3 - <rustc_interface[41d053c15137b84f]::passes::QueryContext>::enter::<rustc_driver[181439583fe95c08]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>
  44:     0x7f4c0ead23f8 - rustc_interface[41d053c15137b84f]::interface::create_compiler_and_run::<core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>, rustc_driver[181439583fe95c08]::run_compiler::{closure#1}>
  45:     0x7f4c0ead1222 - <scoped_tls[b19fcb3c094ee1b2]::ScopedKey<rustc_span[28f29e83648bb1dc]::SessionGlobals>>::set::<rustc_interface[41d053c15137b84f]::interface::run_compiler<core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>, rustc_driver[181439583fe95c08]::run_compiler::{closure#1}>::{closure#0}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>
  46:     0x7f4c0ead06ff - std[1a5ff7869c816d02]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[41d053c15137b84f]::util::run_in_thread_pool_with_globals<rustc_interface[41d053c15137b84f]::interface::run_compiler<core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>, rustc_driver[181439583fe95c08]::run_compiler::{closure#1}>::{closure#0}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>::{closure#0}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>
  47:     0x7f4c0fba569f - <<std[1a5ff7869c816d02]::thread::Builder>::spawn_unchecked_<rustc_interface[41d053c15137b84f]::util::run_in_thread_pool_with_globals<rustc_interface[41d053c15137b84f]::interface::run_compiler<core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>, rustc_driver[181439583fe95c08]::run_compiler::{closure#1}>::{closure#0}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>::{closure#0}, core[6ac417be692c67ad]::result::Result<(), rustc_errors[c8e62c7c8f965cff]::ErrorGuaranteed>>::{closure#1} as core[6ac417be692c67ad]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f4c0d4635f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2ca88d58e081c26e
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/alloc/src/boxed.rs:1987:9
  49:     0x7f4c0d4635f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfd67fbb55bd279bb
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/alloc/src/boxed.rs:1987:9
  50:     0x7f4c0d4635f3 - std::sys::unix::thread::Thread::new::thread_start::h57c955ceb7a2ded2
                               at /rustc/06f049a35535d26d5c8426d4f782f78277b41aa1/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f4c0d31b609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  52:     0x7f4c0d23e133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  53:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (06f049a35 2022-10-17) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `analysis::both`
#1 [type_of] computing type of `analysis::BothUpdateFn::{opaque#0}`
#2 [check_mod_item_types] checking item types in module `analysis`
#3 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

### LINKED ISSUE #104196: Compiler crash: 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT'
This appears to be the same assertion as #100818, #97099, and #103186 (though I'm unclear if the cause is the same) occurring on both stable rust 1.65.0 and nightly 1.67.0. The below reproduction is as minimal as I could get it. Worth noting that I don't believe this code would compile even without the ICE.

### Code

```Rust
use core::future::Future;

pub struct Struct<C, Fu, F>
where
    F: Fn(&C) -> Fu,
    Fu: Future,
{
    handler: F,
    context: C,
}

impl<C, Fu, R, F> Struct<C, Fu, F>
where
    F: Fn(&C) -> Fu,
    Fu: Future<Output = R>,
{
    pub const fn new(handler: F, context: C) -> Self {
        Self { handler, context }
    }
}

type TestC = &'static usize;
type TestFu = impl Future;
type TestF = impl Fn(&TestC) -> TestFu;
type TestStruct = Struct<TestC, TestFu, TestF>;

async fn test_handler(context: &TestC) -> () {
    ()
}

fn get_test_struct() -> &'static TestStruct {
    static test_actor: TestStruct = TestStruct::new(test_handler, &0);
    &test_actor
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler\rustc_borrowck\src\region_infer\mod.rs:721:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ffa62ca8fb2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1086ecfa86360858
   1:     0x7ffa62ce40db - core::fmt::write::hbadbc3de7beb6abb
   2:     0x7ffa62c9b8aa - <std::io::IoSlice as core::fmt::Debug>::fmt::hb7e33fb242ec9ac1
   3:     0x7ffa62cac5b4 - std::panicking::default_hook::hb8b3ce065b661264
   4:     0x7ffa62cac1ea - std::panicking::default_hook::hb8b3ce065b661264
   5:     0x7ffa3abe25ee - rustc_driver[c6471a3a75cc3305]::describe_lints
   6:     0x7ffa62cacfb2 - std::panicking::rust_panic_with_hook::h33e40e3f5d3be1f3
   7:     0x7ffa62caccfa - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h5aceb4e60531e534
   8:     0x7ffa62ca9cbf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1086ecfa86360858
   9:     0x7ffa62caca00 - rust_begin_unwind
  10:     0x7ffa62d19905 - core::panicking::panic_fmt::h0af4781e6a0c54d3
  11:     0x7ffa62d197ac - core::panicking::panic::hd1f6d7a0e46f29da
  12:     0x7ffa3a3f7435 - <rustc_infer[3acbbff32055c339]::infer::InferCtxt as rustc_borrowck[7ffb48d475d38a4e]::universal_regions::InferCtxtExt>::replace_late_bound_regions_with_nll_infer_vars
  13:     0x7ffa3a3ea95e - <rustc_borrowck[7ffb48d475d38a4e]::constraints::OutlivesConstraintSet as core[8087a2e8d825f5e1]::ops::index::Index<rustc_borrowck[7ffb48d475d38a4e]::constraints::OutlivesConstraintIndex>>::index
  14:     0x7ffa3a2e31a8 - <rustc_middle[12c473a188441910]::ty::adjustment::AutoBorrowMutability as rustc_mir_build[236c88af9e57eadb]::thir::cx::expr::ToBorrowKind>::to_borrow_kind
  15:     0x7ffa3a2db836 - <rustc_middle[12c473a188441910]::ty::adjustment::AutoBorrowMutability as rustc_mir_build[236c88af9e57eadb]::thir::cx::expr::ToBorrowKind>::to_borrow_kind
  16:     0x7ffa3a2dae38 - <rustc_middle[12c473a188441910]::ty::adjustment::AutoBorrowMutability as rustc_mir_build[236c88af9e57eadb]::thir::cx::expr::ToBorrowKind>::to_borrow_kind
  17:     0x7ffa38f76ba8 - <rustc_query_impl[9648f954f060bbf5]::queries::is_reachable_non_generic as rustc_query_system[658c00a88212f6cf]::query::config::QueryDescription<rustc_query_impl[9648f954f060bbf5]::plumbing::QueryCtxt>>::execute_query
  18:     0x7ffa390cffbe - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  19:     0x7ffa3a60b7a3 - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  20:     0x7ffa3a54a875 - <rustc_query_impl[9648f954f060bbf5]::Queries as rustc_middle[12c473a188441910]::ty::query::QueryEngine>::as_any
  21:     0x7ffa3c24ad66 - <rustc_typeck[49c87e7593e195a8]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator as rustc_hir[fcc301f55e55bb6a]::intravisit::Visitor>::visit_trait_item    
  22:     0x7ffa3c23da23 - <rustc_typeck[49c87e7593e195a8]::check::method::suggest::SelfSource as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  23:     0x7ffa3c2c7f7b - <rustc_typeck[49c87e7593e195a8]::check::upvar::MigrationWarningReason as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  24:     0x7ffa3c23d9e3 - <rustc_typeck[49c87e7593e195a8]::check::method::suggest::SelfSource as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  25:     0x7ffa3c2d0048 - <rustc_typeck[49c87e7593e195a8]::check::upvar::MigrationWarningReason as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  26:     0x7ffa3c23da2e - <rustc_typeck[49c87e7593e195a8]::check::method::suggest::SelfSource as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  27:     0x7ffa3c2cc649 - <rustc_typeck[49c87e7593e195a8]::check::upvar::MigrationWarningReason as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  28:     0x7ffa3c24a5c9 - <rustc_typeck[49c87e7593e195a8]::check::PlaceOp as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  29:     0x7ffa3a116700 - <rustc_typeck[49c87e7593e195a8]::check::UnsafetyState>::recurse
  30:     0x7ffa3a69f389 - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ffa3a67c76a - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  32:     0x7ffa3aaae51c - <rustc_middle[12c473a188441910]::ty::context::TyCtxt>::bound_type_of
  33:     0x7ffa3a9508d0 - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::evaluate_root_obligation
  34:     0x7ffa3a936ad6 - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::evaluate_root_obligation
  35:     0x7ffa3a95dadb - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::select
  36:     0x7ffa3a936bf5 - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::evaluate_root_obligation
  37:     0x7ffa3a95dadb - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::select
  38:     0x7ffa3a9359ca - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::select::SelectionContext>::evaluate_root_obligation
  39:     0x7ffa3a41f836 - <regex[c10d5b7862cb2dbf]::re_bytes::CaptureNames as core[8087a2e8d825f5e1]::iter::traits::iterator::Iterator>::size_hint
  40:     0x7ffa3a40b925 - <rustc_infer[3acbbff32055c339]::infer::InferCtxt as rustc_borrowck[7ffb48d475d38a4e]::universal_regions::InferCtxtExt>::replace_late_bound_regions_with_nll_infer_vars
  41:     0x7ffa3a6953d2 - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7ffa3a668608 - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7ffa3a54f9a6 - <rustc_query_impl[9648f954f060bbf5]::Queries as rustc_middle[12c473a188441910]::ty::query::QueryEngine>::as_any
  44:     0x7ffa3a916be1 - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::fulfill::FulfillProcessor as rustc_data_structures[1b20f7c7eb90dc04]::obligation_forest::ObligationProcessor>::process_obligation 
  45:     0x7ffa3a9c6f9f - <rustc_middle[12c473a188441910]::ty::Predicate as rustc_trait_selection[51ac1f8d3e2d292c]::traits::query::type_op::normalize::Normalizable>::type_op_method
  46:     0x7ffa3a90cc4b - <rustc_trait_selection[51ac1f8d3e2d292c]::traits::engine::ObligationCtxt>::select_all_or_error
  47:     0x7ffa38d4f3ca - <rustc_typeck[49c87e7593e195a8]::expr_use_visitor::ExprUseVisitor>::consume_body
  48:     0x7ffa38d2db00 - <<rustc_typeck[49c87e7593e195a8]::check::method::confirm::ConfirmContext>::instantiate_method_substs::MethodSubstsCtxt as rustc_typeck[49c87e7593e195a8]::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind
  49:     0x7ffa39fe4bc3 - <<rustc_typeck[49c87e7593e195a8]::check::method::confirm::ConfirmContext>::instantiate_method_substs::MethodSubstsCtxt as rustc_typeck[49c87e7593e195a8]::astconv::CreateSubstsForGenericArgsCtxt>::args_for_def_id
  50:     0x7ffa38f75a98 - <rustc_query_impl[9648f954f060bbf5]::queries::is_reachable_non_generic as rustc_query_system[658c00a88212f6cf]::query::config::QueryDescription<rustc_query_impl[9648f954f060bbf5]::plumbing::QueryCtxt>>::execute_query
  51:     0x7ffa390d3a9e - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  52:     0x7ffa3a61066a - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  53:     0x7ffa3a54e0c8 - <rustc_query_impl[9648f954f060bbf5]::Queries as rustc_middle[12c473a188441910]::ty::query::QueryEngine>::as_any
  54:     0x7ffa3a11b89f - rustc_typeck[49c87e7593e195a8]::check::rvalue_scopes::resolve_rvalue_scopes
  55:     0x7ffa38d2f6f5 - <<rustc_typeck[49c87e7593e195a8]::check::method::confirm::ConfirmContext>::instantiate_method_substs::MethodSubstsCtxt as rustc_typeck[49c87e7593e195a8]::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind
  56:     0x7ffa38f75a98 - <rustc_query_impl[9648f954f060bbf5]::queries::is_reachable_non_generic as rustc_query_system[658c00a88212f6cf]::query::config::QueryDescription<rustc_query_impl[9648f954f060bbf5]::plumbing::QueryCtxt>>::execute_query
  57:     0x7ffa390d3a9e - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  58:     0x7ffa3a61066a - <&[(rustc_middle[12c473a188441910]::ty::Predicate, rustc_span[335b190b38ec46cb]::span_encoding::Span)] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode
  59:     0x7ffa390b89bc - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  60:     0x7ffa38d9b975 - <rustc_typeck[49c87e7593e195a8]::check::cast::CastCheck>::check
  61:     0x7ffa38dab74b - rustc_typeck[49c87e7593e195a8]::check::dropck::check_drop_impl
  62:     0x7ffa38d8848a - <rustc_typeck[49c87e7593e195a8]::check::fn_ctxt::FnCtxt>::write_user_type_annotation
  63:     0x7ffa38d34819 - rustc_typeck[49c87e7593e195a8]::check_crate
  64:     0x7ffa3945a63f - rustc_interface[9c167b8dd5fe1201]::passes::analysis
  65:     0x7ffa38f7830e - <rustc_query_impl[9648f954f060bbf5]::queries::is_reachable_non_generic as rustc_query_system[658c00a88212f6cf]::query::config::QueryDescription<rustc_query_impl[9648f954f060bbf5]::plumbing::QueryCtxt>>::execute_query
  66:     0x7ffa390ed9c3 - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  67:     0x7ffa39070ca7 - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  68:     0x7ffa390c10b6 - <&[rustc_type_ir[1421f89e31f06786]::Variance] as rustc_serialize[5ba6e6ef117c5717]::serialize::Decodable<rustc_query_impl[9648f954f060bbf5]::on_disk_cache::CacheDecoder>>::decode  
  69:     0x7ffa3855c9d9 - rustc_driver[c6471a3a75cc3305]::args::arg_expand_all
  70:     0x7ffa3852a3a8 - rustc_driver[c6471a3a75cc3305]::main
  71:     0x7ffa3855e32a - <rustc_middle[12c473a188441910]::ty::SymbolName as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  72:     0x7ffa38545e60 - rustc_driver[c6471a3a75cc3305]::main
  73:     0x7ffa3855d7d7 - <rustc_middle[12c473a188441910]::ty::SymbolName as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  74:     0x7ffa3854e109 - rustc_driver[c6471a3a75cc3305]::main
  75:     0x7ffa3854e56d - rustc_driver[c6471a3a75cc3305]::main
  76:     0x7ffa62cbd7cc - std::sys::windows::thread::Thread::new::h742bb0c6405f02e2
  77:     0x7ffb262b7034 - BaseThreadInitThunk
  78:     0x7ffb27c826a1 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `get_test_struct::test_actor`
#1 [type_of] computing type of `TestF::{opaque#0}`
#2 [evaluate_obligation] evaluating trait selection obligation `Struct<&'static usize, TestFu, TestF>: core::marker::Sync`
#3 [check_well_formed] checking that `get_test_struct::test_actor` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in top-level module
#5 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #108399: ICE: assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT
### Code

```Rust
#![feature(type_alias_impl_trait)]

use std::future::Future;

type FutNothing<'a> = impl 'a + Future<Output = ()>;

async fn operation(x: &mut ()) -> () {
    ()
}

async fn indirect() {
    call(operation).await
}

async fn call<F>(mut f: F)
where
    for<'any> F: FnMut(&'any mut ()) -> FutNothing<'any>,
{
    f(&mut ()).await
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

required flags: `--edition=2021 --crate-type lib`

Nightly `rustc 1.69.0-nightly (fdbc4329c 2023-02-22)`

````
error: unconstrained opaque type
 --> 103348.rs:5:23
  |
5 | type FutNothing<'a> = impl 'a + Future<Output = ()>;
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `FutNothing` must be used in combination with a concrete type within the same module
````

master rustc `rustc 1.69.0-nightly (07c993eba 2023-02-23)`:

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:792:9
stack backtrace:
   0:     0x7f38a316aaba - std::backtrace_rs::backtrace::libunwind::trace::h0cd32959c646dd58
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f38a316aaba - std::backtrace_rs::backtrace::trace_unsynchronized::h3b2629401c061fcd
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f38a316aaba - std::sys_common::backtrace::_print_fmt::h39e74da7196fd373
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f38a316aaba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8078aeef1fb809f3
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f38a31caa3e - core::fmt::write::hfc052c4fbedc81c6
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f38a315ae65 - std::io::Write::write_fmt::h1de78f6bbfa1f9b4
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/io/mod.rs:1684:15
   6:     0x7f38a316a885 - std::sys_common::backtrace::_print::hed82c65090f5ecac
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f38a316a885 - std::sys_common::backtrace::print::ha75a593988590c58
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f38a316d5ff - std::panicking::default_hook::{{closure}}::h889859cf66b4c9e0
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/panicking.rs:271:22
   9:     0x7f38a316d33b - std::panicking::default_hook::h880efa6ec073db9c
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/panicking.rs:290:9
  10:     0x7f38a646b555 - rustc_driver_impl[f83b883832371c75]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f38a316de3d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1b7815fffd467b2d
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/alloc/src/boxed.rs:2002:9
  12:     0x7f38a316de3d - std::panicking::rust_panic_with_hook::h4e7f28681abccfd5
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/panicking.rs:696:13
  13:     0x7f38a316db72 - std::panicking::begin_panic_handler::{{closure}}::h90911033b946dbe6
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/panicking.rs:581:13
  14:     0x7f38a316af26 - std::sys_common::backtrace::__rust_end_short_backtrace::h798238d1ce7e9895
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f38a316d8c2 - rust_begin_unwind
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/panicking.rs:579:5
  16:     0x7f38a31c73e3 - core::panicking::panic_fmt::h24144ffb3f3163ea
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/core/src/panicking.rs:64:14
  17:     0x7f38a31c747d - core::panicking::panic::h2a2cd64c1c1612ff
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/core/src/panicking.rs:114:5
  18:     0x7f38a53bc3f9 - <rustc_borrowck[e32dba551d3cd843]::region_infer::RegionInferenceContext>::solve
  19:     0x7f38a537ada6 - rustc_borrowck[e32dba551d3cd843]::nll::compute_regions
  20:     0x7f38a535d42c - rustc_borrowck[e32dba551d3cd843]::do_mir_borrowck
  21:     0x7f38a534ada3 - rustc_borrowck[e32dba551d3cd843]::mir_borrowck
  22:     0x7f38a4dc50ab - rustc_query_system[5752648da2a9c81a]::query::plumbing::try_execute_query::<rustc_query_impl[5767a176057dc243]::queries::mir_borrowck, rustc_query_impl[5767a176057dc243]::plumbing::QueryCtxt>
  23:     0x7f38a5e7451d - <rustc_query_impl[5767a176057dc243]::Queries as rustc_middle[48afdec4b3d5af25]::ty::query::QueryEngine>::mir_borrowck
  24:     0x7f38a544760f - <rustc_borrowck[e32dba551d3cd843]::type_check::TypeChecker>::prove_closure_bounds
  25:     0x7f38a5425cc8 - <rustc_borrowck[e32dba551d3cd843]::type_check::TypeChecker>::typeck_mir
  26:     0x7f38a538e558 - rustc_borrowck[e32dba551d3cd843]::type_check::type_check
  27:     0x7f38a537a9c5 - rustc_borrowck[e32dba551d3cd843]::nll::compute_regions
  28:     0x7f38a535d42c - rustc_borrowck[e32dba551d3cd843]::do_mir_borrowck
  29:     0x7f38a534ada3 - rustc_borrowck[e32dba551d3cd843]::mir_borrowck
  30:     0x7f38a4dc50ab - rustc_query_system[5752648da2a9c81a]::query::plumbing::try_execute_query::<rustc_query_impl[5767a176057dc243]::queries::mir_borrowck, rustc_query_impl[5767a176057dc243]::plumbing::QueryCtxt>
  31:     0x7f38a5e7451d - <rustc_query_impl[5767a176057dc243]::Queries as rustc_middle[48afdec4b3d5af25]::ty::query::QueryEngine>::mir_borrowck
  32:     0x7f38a65f7491 - <rustc_hir_analysis[3040e81d56faed42]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>::check
  33:     0x7f38a65f4352 - <rustc_hir_analysis[3040e81d56faed42]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator as rustc_hir[ce80dd10cd19e57d]::intravisit::Visitor>::visit_nested_item
  34:     0x7f38a65ca9b8 - rustc_hir[ce80dd10cd19e57d]::intravisit::walk_mod::<rustc_hir_analysis[3040e81d56faed42]::collect::type_of::find_opaque_ty_constraints_for_tait::ConstraintLocator>
  35:     0x7f38a65f6bc1 - rustc_hir_analysis[3040e81d56faed42]::collect::type_of::find_opaque_ty_constraints_for_tait
  36:     0x7f38a5ae41f9 - rustc_hir_analysis[3040e81d56faed42]::collect::type_of::type_of
  37:     0x7f38a4ede91e - rustc_query_system[5752648da2a9c81a]::query::plumbing::get_query::<rustc_query_impl[5767a176057dc243]::queries::type_of, rustc_query_impl[5767a176057dc243]::plumbing::QueryCtxt, rustc_middle[48afdec4b3d5af25]::dep_graph::dep_node::DepKind>
  38:     0x7f38a4fc9f78 - rustc_hir_analysis[3040e81d56faed42]::check::check::check_mod_item_types
  39:     0x7f38a5a562bf - rustc_query_system[5752648da2a9c81a]::query::plumbing::try_execute_query::<rustc_query_impl[5767a176057dc243]::queries::check_mod_item_types, rustc_query_impl[5767a176057dc243]::plumbing::QueryCtxt>
  40:     0x7f38a5e73b0d - <rustc_query_impl[5767a176057dc243]::Queries as rustc_middle[48afdec4b3d5af25]::ty::query::QueryEngine>::check_mod_item_types
  41:     0x7f38a49dbaf7 - <rustc_session[c35ef6b175fc9185]::session::Session>::time::<(), rustc_hir_analysis[3040e81d56faed42]::check_crate::{closure#6}>
  42:     0x7f38a49d95a8 - rustc_hir_analysis[3040e81d56faed42]::check_crate
  43:     0x7f38a49ceef2 - rustc_interface[fa0b2b03ae23a7ba]::passes::analysis
  44:     0x7f38a5c8a672 - rustc_query_system[5752648da2a9c81a]::query::plumbing::try_execute_query::<rustc_query_impl[5767a176057dc243]::queries::analysis, rustc_query_impl[5767a176057dc243]::plumbing::QueryCtxt>
  45:     0x7f38a5e6d75a - <rustc_query_impl[5767a176057dc243]::Queries as rustc_middle[48afdec4b3d5af25]::ty::query::QueryEngine>::analysis
  46:     0x7f38a5ada266 - <rustc_middle[48afdec4b3d5af25]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[f83b883832371c75]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>
  47:     0x7f38a56e194c - <rustc_interface[fa0b2b03ae23a7ba]::interface::Compiler>::enter::<rustc_driver_impl[f83b883832371c75]::run_compiler::{closure#1}::{closure#2}, core[5b2b83b4efe70cd5]::result::Result<core[5b2b83b4efe70cd5]::option::Option<rustc_interface[fa0b2b03ae23a7ba]::queries::Linker>, rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>
  48:     0x7f38a56dfa24 - rustc_span[da5d5abcbe0cb70f]::with_source_map::<core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>, rustc_interface[fa0b2b03ae23a7ba]::interface::run_compiler<core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>, rustc_driver_impl[f83b883832371c75]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  49:     0x7f38a56def8c - std[195e6cd746373230]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fa0b2b03ae23a7ba]::util::run_in_thread_pool_with_globals<rustc_interface[fa0b2b03ae23a7ba]::interface::run_compiler<core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>, rustc_driver_impl[f83b883832371c75]::run_compiler::{closure#1}>::{closure#0}, core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>
  50:     0x7f38a56de9ba - <<std[195e6cd746373230]::thread::Builder>::spawn_unchecked_<rustc_interface[fa0b2b03ae23a7ba]::util::run_in_thread_pool_with_globals<rustc_interface[fa0b2b03ae23a7ba]::interface::run_compiler<core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>, rustc_driver_impl[f83b883832371c75]::run_compiler::{closure#1}>::{closure#0}, core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5b2b83b4efe70cd5]::result::Result<(), rustc_errors[6785960a74f5dba1]::ErrorGuaranteed>>::{closure#1} as core[5b2b83b4efe70cd5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:     0x7f38a3177cc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h533fa800d0f50b92
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/alloc/src/boxed.rs:1988:9
  52:     0x7f38a3177cc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4ed7863a7d2ef51a
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/alloc/src/boxed.rs:1988:9
  53:     0x7f38a3177cc3 - std::sys::unix::thread::Thread::new::thread_start::h975090723601c6b9
                               at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/sys/unix/thread.rs:108:17
  54:     0x7f38a2f07bb5 - <unknown>
  55:     0x7f38a2f89d90 - <unknown>
  56:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (07c993eba 2023-02-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
#0 [mir_borrowck] borrow-checking `indirect::{closure#0}`
#1 [mir_borrowck] borrow-checking `indirect`
#2 [type_of] computing type of `FutNothing::{opaque#0}`
#3 [check_mod_item_types] checking item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #113481: ICE when attempting to return `for<'y> Trait<AssocType<'y> = impl Whatever>`
### Code

```Rust
trait Foo {
    type Bar<'x>
    where
        Self: 'x;
}

fn baz() -> impl for<'y> Foo<Bar<'y> = impl ToString> {
    42
}

impl Foo for i32 {
    type Bar<'x> = &'x str;
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=795395ac04289bbbcb23dbb642116c1f

### Meta
`rustc --version --verbose`:
```
I only did this on the playground, but it happens there on all of
* stable 1.70
* beta 1.71.0-beta.5 (2023-07-06 f06c1b82f231401543bb)
* nightly 1.72.0-nightly (2023-07-06 85bf07972a1041b9e253)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:811:9
stack backtrace:
   0:     0x7f3911733a71 - std::backtrace_rs::backtrace::libunwind::trace::h83338e21cbc3510e
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3911733a71 - std::backtrace_rs::backtrace::trace_unsynchronized::h1663b95366fea7e1
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3911733a71 - std::sys_common::backtrace::_print_fmt::hcb919a5390faff94
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f3911733a71 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8e8379de0738990
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3911799d7f - core::fmt::rt::Argument::fmt::h12cd44e59c3e03f4
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/fmt/rt.rs:138:9
   5:     0x7f3911799d7f - core::fmt::write::h0d2b2a94b10f259a
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f39117264b7 - std::io::Write::write_fmt::hf16cae54d031f42c
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/io/mod.rs:1714:15
   7:     0x7f3911733885 - std::sys_common::backtrace::_print::h7c194ea6232bf362
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f3911733885 - std::sys_common::backtrace::print::hca89cc4c64fa92f2
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f3911736663 - std::panicking::default_hook::{{closure}}::hba1423900118f107
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:269:22
  10:     0x7f39117363f4 - std::panicking::default_hook::hf4868ae8eb550432
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:288:9
  11:     0x7f3914a4d65b - rustc_driver_impl[5fd2fff4e2ab1b68]::install_ice_hook::{closure#0}
  12:     0x7f3911736e8e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2d28fdec3189af27
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/alloc/src/boxed.rs:2024:9
  13:     0x7f3911736e8e - std::panicking::rust_panic_with_hook::hdb6e4003315ae50a
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:709:13
  14:     0x7f3911736bd1 - std::panicking::begin_panic_handler::{{closure}}::h05675051fb0f9296
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:595:13
  15:     0x7f3911733ed6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9866f6ab4fcd5803
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7f3911736962 - rust_begin_unwind
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:593:5
  17:     0x7f3911795fd3 - core::panicking::panic_fmt::h1490cb3aae65fe17
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:67:14
  18:     0x7f3911796063 - core::panicking::panic::hfba00d56e7941e8b
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:117:5
  19:     0x7f3913a9ecd2 - <rustc_borrowck[4725ebfa67e64d94]::region_infer::RegionInferenceContext>::solve
  20:     0x7f3913a8a79e - rustc_borrowck[4725ebfa67e64d94]::nll::compute_regions
  21:     0x7f3913a69a15 - rustc_borrowck[4725ebfa67e64d94]::do_mir_borrowck
  22:     0x7f3913a67c57 - rustc_borrowck[4725ebfa67e64d94]::mir_borrowck
  23:     0x7f3912a48e9e - rustc_query_impl[a5debbf18c9cda01]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a5debbf18c9cda01]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 8usize]>>
  24:     0x7f3912a48e6e - <rustc_query_impl[a5debbf18c9cda01]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[bcc6c1a0d905112a]::ops::function::FnOnce<(rustc_middle[6a835cc3e0a555e0]::ty::context::TyCtxt, rustc_span[330d20617ff3531a]::def_id::LocalDefId)>>::call_once
  25:     0x7f3912b6e14d - rustc_query_system[9a6651a6b626ed91]::query::plumbing::try_execute_query::<rustc_query_impl[a5debbf18c9cda01]::DynamicConfig<rustc_query_system[9a6651a6b626ed91]::query::caches::VecCache<rustc_span[330d20617ff3531a]::def_id::LocalDefId, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a5debbf18c9cda01]::plumbing::QueryCtxt, false>
  26:     0x7f39143c53e1 - rustc_query_impl[a5debbf18c9cda01]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7f3913b93885 - rustc_hir_analysis[ac41804801612bf5]::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
  28:     0x7f3913b90593 - rustc_hir_analysis[ac41804801612bf5]::collect::type_of::type_of
  29:     0x7f3912b923b3 - rustc_query_impl[a5debbf18c9cda01]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a5debbf18c9cda01]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f3912b92370 - <rustc_query_impl[a5debbf18c9cda01]::query_impl::type_of::dynamic_query::{closure#2} as core[bcc6c1a0d905112a]::ops::function::FnOnce<(rustc_middle[6a835cc3e0a555e0]::ty::context::TyCtxt, rustc_span[330d20617ff3531a]::def_id::DefId)>>::call_once
  31:     0x7f3912a48795 - rustc_query_system[9a6651a6b626ed91]::query::plumbing::try_execute_query::<rustc_query_impl[a5debbf18c9cda01]::DynamicConfig<rustc_query_system[9a6651a6b626ed91]::query::caches::DefaultCache<rustc_span[330d20617ff3531a]::def_id::DefId, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a5debbf18c9cda01]::plumbing::QueryCtxt, false>
  32:     0x7f39143b4cf3 - rustc_query_impl[a5debbf18c9cda01]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f3913888d42 - rustc_middle[6a835cc3e0a555e0]::query::plumbing::query_get_at::<rustc_query_system[9a6651a6b626ed91]::query::caches::DefaultCache<rustc_span[330d20617ff3531a]::def_id::DefId, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 8usize]>>>
  34:     0x7f391388295a - rustc_hir_analysis[ac41804801612bf5]::check::check::check_mod_item_types
  35:     0x7f39136b78ac - rustc_query_impl[a5debbf18c9cda01]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a5debbf18c9cda01]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 0usize]>>
  36:     0x7f39136b788e - <rustc_query_impl[a5debbf18c9cda01]::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core[bcc6c1a0d905112a]::ops::function::FnOnce<(rustc_middle[6a835cc3e0a555e0]::ty::context::TyCtxt, rustc_span[330d20617ff3531a]::def_id::LocalDefId)>>::call_once
  37:     0x7f39130bbf0f - rustc_query_system[9a6651a6b626ed91]::query::plumbing::try_execute_query::<rustc_query_impl[a5debbf18c9cda01]::DynamicConfig<rustc_query_system[9a6651a6b626ed91]::query::caches::VecCache<rustc_span[330d20617ff3531a]::def_id::LocalDefId, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[a5debbf18c9cda01]::plumbing::QueryCtxt, false>
  38:     0x7f39143b8144 - rustc_query_impl[a5debbf18c9cda01]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f3913e6e1b7 - <rustc_middle[6a835cc3e0a555e0]::hir::map::Map>::for_each_module::<rustc_hir_analysis[ac41804801612bf5]::check_crate::{closure#6}::{closure#0}>
  40:     0x7f3913e6d5ed - <rustc_session[ab778da52d62d91c]::session::Session>::time::<(), rustc_hir_analysis[ac41804801612bf5]::check_crate::{closure#6}>
  41:     0x7f3913e6c277 - rustc_hir_analysis[ac41804801612bf5]::check_crate
  42:     0x7f3913e632ea - rustc_interface[99b7bac6f3a68274]::passes::analysis
  43:     0x7f3913efd80a - rustc_query_impl[a5debbf18c9cda01]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a5debbf18c9cda01]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7f3913efd7f9 - <rustc_query_impl[a5debbf18c9cda01]::query_impl::analysis::dynamic_query::{closure#2} as core[bcc6c1a0d905112a]::ops::function::FnOnce<(rustc_middle[6a835cc3e0a555e0]::ty::context::TyCtxt, ())>>::call_once
  45:     0x7f391407ba98 - rustc_query_system[9a6651a6b626ed91]::query::plumbing::try_execute_query::<rustc_query_impl[a5debbf18c9cda01]::DynamicConfig<rustc_query_system[9a6651a6b626ed91]::query::caches::SingleCache<rustc_middle[6a835cc3e0a555e0]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a5debbf18c9cda01]::plumbing::QueryCtxt, false>
  46:     0x7f391407b869 - rustc_query_impl[a5debbf18c9cda01]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7f3913c38a05 - <rustc_middle[6a835cc3e0a555e0]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>
  48:     0x7f3913c38032 - <rustc_interface[99b7bac6f3a68274]::interface::Compiler>::enter::<rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}::{closure#2}, core[bcc6c1a0d905112a]::result::Result<core[bcc6c1a0d905112a]::option::Option<rustc_interface[99b7bac6f3a68274]::queries::Linker>, rustc_span[330d20617ff3531a]::ErrorGuaranteed>>
  49:     0x7f3913c2ed45 - rustc_span[330d20617ff3531a]::set_source_map::<core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>, rustc_interface[99b7bac6f3a68274]::interface::run_compiler<core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>, rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  50:     0x7f3913c2e7b6 - <scoped_tls[df29aac8beac7397]::ScopedKey<rustc_span[330d20617ff3531a]::SessionGlobals>>::set::<rustc_interface[99b7bac6f3a68274]::interface::run_compiler<core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>, rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}>::{closure#0}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>
  51:     0x7f3913c2dd7c - std[6f71ef261950bfb1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[99b7bac6f3a68274]::util::run_in_thread_pool_with_globals<rustc_interface[99b7bac6f3a68274]::interface::run_compiler<core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>, rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}>::{closure#0}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>
  52:     0x7f3913c2db45 - <<std[6f71ef261950bfb1]::thread::Builder>::spawn_unchecked_<rustc_interface[99b7bac6f3a68274]::util::run_in_thread_pool_with_globals<rustc_interface[99b7bac6f3a68274]::interface::run_compiler<core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>, rustc_driver_impl[5fd2fff4e2ab1b68]::run_compiler::{closure#1}>::{closure#0}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[bcc6c1a0d905112a]::result::Result<(), rustc_span[330d20617ff3531a]::ErrorGuaranteed>>::{closure#1} as core[bcc6c1a0d905112a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7f3911741305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hee94a9b600b92b27
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/alloc/src/boxed.rs:2010:9
  54:     0x7f3911741305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb557fd709dd3520f
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/alloc/src/boxed.rs:2010:9
  55:     0x7f3911741305 - std::sys::unix::thread::Thread::new::thread_start::h726c141aa23b2e83
                               at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7f3911608609 - start_thread
  57:     0x7f391152b133 - clone
  58:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (85bf07972 2023-07-06) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `baz`
#1 [type_of] computing type of `baz::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: self.scc_universes[scc] == ty::UniverseIndex::ROOT', compiler/rustc_borrowck/src/region_infer/mod.rs:811:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:117:5
   3: <rustc_borrowck::region_infer::RegionInferenceContext>::solve
   4: rustc_borrowck::nll::compute_regions
   5: rustc_borrowck::do_mir_borrowck
   6: rustc_borrowck::mir_borrowck
   7: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
   8: rustc_hir_analysis::collect::type_of::type_of
   9: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  10: rustc_hir_analysis::check::check::check_mod_item_types
  11: <rustc_middle::hir::map::Map>::for_each_module::<rustc_hir_analysis::check_crate::{closure#6}::{closure#0}>
  12: <rustc_session::session::Session>::time::<(), rustc_hir_analysis::check_crate::{closure#6}>
  13: rustc_hir_analysis::check_crate
  14: rustc_interface::passes::analysis
  15: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  16: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  17: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  18: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (85bf07972 2023-07-06) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `baz`
#1 [type_of] computing type of `baz::{opaque#0}`
#2 [check_mod_item_types] checking item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by aliemjay**
This shouldn't allow more code to compile, only replaces the ICE with a nicer error message.

Fixes https://github.com/rust-lang/rust/issues/97098.
Fixes https://github.com/rust-lang/rust/issues/97099.
Fixes #108399
Fixes #104196
Fixes #113481
Fixes #103186
Fixes #100818

r? @lcnr (because you showed interest in #100503 :)

### CODE REVIEW

**Comment by compiler-errors** [comment]
ci is broken for unrelated reasons 😓

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 1]
```diff
@@ -791,6 +791,9 @@ impl<'tcx> RegionInferenceContext<'tcx> {
         member_constraint_index: NllMemberConstraintIndex,
         choice_regions: &[ty::RegionVid],
     ) -> bool {
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:793]: two thoughts:

- the `bool` is unused by the only caller, can change the return type to `()`.
- can you add a comment that this only adds the member constraints to the region graph and that we don't check them here but instead in `check_member_constraints` after the region graph has been computed?

**Review by lcnr — COMMENTED** [review]
r=me after rebase

**Comment by oli-obk** [comment]
I rebased, blessed and addressed the review comment

@bors r=lcnr
