### PR TITLE
fix "X is not a member of trait Y" span labels

### LINKED ISSUE #36428: not a member of trait `Foo` error label in trait impl of different name for associated types
```
trait Peach {}

impl Peach for bool { 
    type Banana = ();
}
```

results in

```
error[E0437]: type `Banana` is not a member of trait `Peach`
 --> <anon>:5:5
  |
5 |     type Banana = ();
  |     ^^^^^^^^^^^^^^^^^ not a member of trait `Foo`
```

cc @jonathandturner

### PR DESCRIPTION
**Pull request by durka**
Fixes #36428.

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -257,7 +257,7 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
                              "type `{}` is not a member of trait `{}`",
                              type_,
                              trait_);
-            err.span_label(span, &format!("not a member of trait `Foo`"));
```
Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: Why removing "trait"? I actually find this better with it.

File: src/librustc_resolve/lib.rs [hunk 2]
```diff
@@ -267,7 +267,7 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
                              "const `{}` is not a member of trait `{}`",
                              const_,
                              trait_);
-            err.span_label(span, &format!("not a member of trait `Foo`"));
```
Comment (GuillaumeGomez) [inline src/librustc_resolve/lib.rs]: Same as above.

File: src/librustc_resolve/lib.rs [hunk 3]
```diff
@@ -257,7 +257,7 @@ fn resolve_struct_error<'b, 'a: 'b, 'c>(resolver: &'b Resolver<'a>,
                              "type `{}` is not a member of trait `{}`",
                              type_,
                              trait_);
-            err.span_label(span, &format!("not a member of trait `Foo`"));
+            err.span_label(span, &format!("not a member of `{}`", trait_));
```
Comment (jonathandturner) [inline src/librustc_resolve/lib.rs]: This removes `trait` designation.  Definitely would like to see the fix, but not sure if we need to change the wording also...

Comment (durka) [inline src/librustc_resolve/lib.rs]: Heh, you and @GuillaumeGomez made the same comment at the same time.

@nagisa and I talked about it on IRC -- the same error for methods already doesn't say "trait" in the label. Either way they should be consistent. I'm fine with putting it back in -- I thought we should err on the side of shorter span labels. Note that the main error message _does_ include the word "trait".

Comment (jonathandturner) [inline src/librustc_resolve/lib.rs]: I agree being consistent is preferred.

The reason I say we might want to keep `trait` in is because, in general, we want to shoot for labels that can be read and understood on their own without having to read the error title.  They're one of the first things people see, so if we can give them enough information to fix the bug, they'll be able to fix it that much faster.

In this case, saying `trait` in the label will jog their memory of "oh wait, this must have something to do with traits".  For me, without it, I had to read the label a couple times to get to that point.

We may want also update the other method error, too...

Comment (durka) [inline src/librustc_resolve/lib.rs]: Okay, I can add "trait" to all three labels. Wish Github had a way to squash commits in the web interface...

**Comment by durka** [comment]
Travis passed, so I squashed the commits.

**Comment by GuillaumeGomez** [comment]
All good for me!

**Comment by durka** [comment]
bogus
