### PR TITLE
use implied bounds when checking opaque types

### LINKED ISSUE #95922: TAIT regression: requires unnecessary explicit lifetime bound
I tried this code:

```rust
#![feature(type_alias_impl_trait)]
use core::future::Future;

trait Service<'a, Req> {
    type Future: Future;
    fn call(req: &'a Req) -> Self::Future;
}

impl<'a, Req> Service<'a, Req> for u8 {
    type Future = impl Future;
    fn call(req: &'a Req) -> Self::Future {
        async move { let x = req; }
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3b4c470458a245ff1f8a032101641de2))

This code used to compile fine prior to #95519. It now requires an explicit lifetime bound `Req: 'a` to the impl.

Unfortunately, adding a lifetime bound may not be an option when used with HRTBS due to bugs like #95921. This caused a major breakage on my part.

### Meta

regressed in the nightly version `1.62.0-nightly (f4a7ce997 2022-04-08)`

<details><summary>Error Output</summary>
<p>

```
   Compiling rust-ci v0.1.0 (/home/runner/work/rust-ci/rust-ci)
error[E0309]: the parameter type `Req` may not live long enough
Error:   --> src/lib.rs:10:19
   |
10 |     type Future = impl Future;
   |                   ^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `Req: 'a`...
   = note: ...so that the reference type `&'a Req` does not outlive the data it points at

For more information about this error, try `rustc --explain E0309`.
error: could not compile `rust-ci` due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by aliemjay**
During opaque type inference, we check for the well-formedness of the hidden type in the opaque type's own environment, not the one of the defining site, which are different in the case of TAIT.

However in the case of associated-type-impl-trait, we don't use implied bounds from the impl header. This caused us to reject the following:
```rust
trait Service<Req> {
    type Output;
    fn call(req: Req) -> Self::Output;
}

impl<'a, Req> Service<&'a Req> for u8 {
    type Output= impl Sized; // we can't prove WF of hidden type  `WF(&'a Req)` although it's implied by the impl
    //~^ ERROR type parameter Req doesn't live long enough
    fn call(req: &'a Req) -> Self::Output {
        req
    }
}
```

although adding an explicit bound would make it pass:
```diff
- impl<'a, Req> Service<&'a Req> for u8 {
+ impl<'a, Req> Service<&'a Req> for u8  where Req: 'a, {
```

I believe it should pass as we already allow the concrete type to be used:
```diff
impl<'a, Req> Service<&'a Req> for u8 {
-    type Output= impl Sized;
+    type Output= &'a Req;
```

Fixes #95922

Builds on #105982

cc @lcnr (because implied bounds)

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
the TAIT part lgtm. The implied bounds part, too, but I don't know that part well enough.

@lcnr do you want to have a look?

@aliemjay please rebase and rebless

@rustbot author

File: src/test/ui/type-alias-impl-trait/wf-nested-pass.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+trait Trait<In> {
+    type Out;
+}
+impl<T> Trait<&'static T> for () {
+    type Out = IsStatic<T>;
+}
+
+type OuterOpaque<T> = impl Trait<&'static T, Out = impl Sized>;
+fn define<T>() -> OuterOpaque<T> {}
```
Comment (lcnr) [inline src/test/ui/type-alias-impl-trait/wf-nested-pass.rs:20]: can you add a test which checks that this errors when `define` is used with a type which is not `'static`

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 2]
```diff
@@ -466,12 +470,29 @@ fn check_opaque_meets_bounds<'tcx>(
     match origin {
         // Checked when type checking the function containing them.
         hir::OpaqueTyOrigin::FnReturn(..) | hir::OpaqueTyOrigin::AsyncFn(..) => {}
+        // Nested opaque types occur only in associated types:
+        // ` type Opaque<T> = impl Trait<&'static T, AssocTy = impl Nested>; `
+        // They can only be referenced as `<Opaque<T> as Trait<&'static T>>::AssocTy`.
+        // We don't have to check them here because their well-formedness follows from the WF of
+        // the projection input types in the defining- and use-sites.
+        hir::OpaqueTyOrigin::TyAlias
+            if let DefKind::OpaqueTy = tcx.def_kind(tcx.parent(def_id.to_def_id())) => {}
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/check.rs:479]: that makes me a bit unhappy. Can you not instead add the type of the parent opaque type as an assumed wf type?

**Review by lcnr — COMMENTED** [review]
2 nits, otherwise r=me on the second commit.

blocked on #105982

File: src/test/ui/type-alias-impl-trait/wf-nested-pass.rs (hunk 1 above)
Comment (aliemjay) [reply src/test/ui/type-alias-impl-trait/wf-nested-pass.rs]: I've added a one in `pass_sound` revision. Note that it relies on #99217 for soundness.

File: compiler/rustc_hir_analysis/src/check/check.rs (hunk 2 above)
Comment (aliemjay) [reply compiler/rustc_hir_analysis/src/check/check.rs]: We should not only include the type of the parent opaque type in assumed_wf_types, but also all other types that appear in the trait inputs (e.g `&'static T` in `impl Trait<&'static T, Assoc=impl Nested>`). The implementation can get easily complicated if we consider multiple levels of nesting and binders like:
```rust
impl Fn<(&'static T,), Output = impl for<'a> Fn<(&'a T,), Output = impl Sized + 'a>>
```

I think the current implementation strikes a balance between simplicity and completeness. That being said, if you feel strongly about it, I'm happy to implement the limited version of including only the parent opaque type. Note that we would reject the test `wf-nested.rs`.

**Comment by aliemjay** [comment]
no longer blocked.
@rustbot ready
