### PR TITLE
Suggest removing `let` if `const let` or `let const` is used

### LINKED ISSUE #99910: Suggest removing ```let``` if ```const let``` or ```let const``` is used
Given the following code:

```rust
fn main() {
    const let foo = 123;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected identifier, found keyword `let`
 --> src/main.rs:2:11
  |
2 |     const let foo = 123;
  |           ^^^ expected identifier, found keyword

error: expected one of `:`, `;`, or `=`, found `foo`
 --> src/main.rs:2:15
  |
2 |     const let foo = 123;
  |               ^^^ expected one of `:`, `;`, or `=`

error: missing type for `const` item
 --> src/main.rs:2:11
  |
2 |     const let foo = 123;
  |           ^^^ help: provide a type for the item: `r#let: <type>`

error: could not compile `playground` due to 3 previous errors
```

Ideally the output should inform the user that ```let``` and ```const``` are mutually exclusive and suggest the user remove the ```let```.

### PR DESCRIPTION
**Pull request by obeis**
Closes #99910

### CODE REVIEW

File: compiler/rustc_parse/src/parser/stmt.rs [hunk 1]
```diff
@@ -247,6 +247,21 @@ impl<'a> Parser<'a> {
     /// Parses a local variable declaration.
     fn parse_local(&mut self, attrs: AttrVec) -> PResult<'a, P<Local>> {
         let lo = self.prev_token.span;
+
+        if self.eat_keyword(kw::Const) {
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/stmt.rs:251]: `let const { expression } = ...` must be accepted. The `const {}` there is an inline const pattern.

Comment (obeis) [reply compiler/rustc_parse/src/parser/stmt.rs]: Fixed!
