### PR TITLE
Fixed ICEs with pattern matching in const expression

### LINKED ISSUE #29093: Global const expr with macro causes compiler panic
I would like to have compile-time evaluation of my const values
from the environment variables.
I wonder whether I had some grammar mistakes, however the compiler panics.
This occurs all stable, beta, and nightly versions (from play.rust-lang.org).

I tried this code:

```
const DEFAULT_PACKET_BUFFER_SIZE : usize = 2048;

pub const PACKET_BUFFER_SIZE : usize = match option_env!("PACKET_BUFFER_SIZE") {
    None => DEFAULT_PACKET_BUFFER_SIZE,
    Some(num_str) => {
        match num_str.parse::<usize>() {
            Ok(num) => {
                match num.is_power_of_two() {
                    true => num,
                    _ => DEFAULT_PACKET_BUFFER_SIZE,
                }
                },
            _ => { DEFAULT_PACKET_BUFFER_SIZE },
        }
    }
};

fn main()
{
    println!("{}",DEFAULT_PACKET_BUFFER_SIZE);
}
```

I expected to see this happen: 
compiles with environment variables, statically evaluated.

Instead, this happened:
compiler panic.
## Meta

```
PS C:\workspace\git\FPS\src> cargo build --verbose
       Fresh winapi v0.2.4
       Fresh rustc-serialize v0.3.16
       Fresh libc v0.1.10
       Fresh winapi-build v0.1.1
       Fresh advapi32-sys v0.1.2
       Fresh rand v0.3.11
       Fresh num v0.1.27
   Compiling FPS v0.0.0 (file:///C:/workspace/git/FPS)
     Running `rustc lib.rs --crate-name fps --crate-type lib -g --out-dir C:\workspace\git\FPS\target\debug --emit=dep-i
nfo,link -L dependency=C:\workspace\git\FPS\target\debug -L dependency=C:\workspace\git\FPS\target\debug\deps --extern i
log2=C:\workspace\git\FPS\target\debug\deps\libilog2-d6c9b6aa20d924f8.rlib`
       Fresh ilog2 v0.2.2
N\env.rs:5:10: 5:17 error: internal compiler error: no enclosing scope found for scope: Misc(13)
N\env.rs:5     Some(num_str) => {
                    ^~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax\diagnostic.rs:176


Could not compile `FPS`.

Caused by:
  Process didn't exit successfully: `rustc lib.rs --crate-name fps --crate-type lib -g --out-dir C:\workspace\git\FPS\ta
rget\debug --emit=dep-info,link -L dependency=C:\workspace\git\FPS\target\debug -L dependency=C:\workspace\git\FPS\targe
t\debug\deps --extern ilog2=C:\workspace\git\FPS\target\debug\deps\libilog2-d6c9b6aa20d924f8.rlib` (exit code: 101)
PS C:\workspace\git\FPS\src>
```

```
PS C:\workspace\git\FPS\src> rustc --version --verbose
rustc 1.3.0 (9a92aaf19 2015-09-15)
binary: rustc
commit-hash: 9a92aaf19a64603b02b4130fe52958cc12488900
commit-date: 2015-09-15
host: x86_64-pc-windows-gnu
release: 1.3.0
```

http://puu.sh/kM1Yo/036518bf32.png

### LINKED ISSUE #31577: Internal compiler error when creating a static constant
I'm trying to create static or constant from matching the env::home_dir:

```
use std::env;
static home: String = match env::home_dir() {
    Some(ref p) => p.to_str().unwrap().to_owned(),
    None => "./".to_string(),
};

```

But I'm getting a compiler bug:

> src/main.rs:15:8: 15:13 error: internal compiler error: no enclosing scope found for scope: CodeExtent(346/Misc(20))
> src/main.rs:15          Some(ref p) => p.to_str().unwrap().to_owned(),
>                              ^~~~~
> note: the compiler unexpectedly panicked. this is a bug.
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> note: run with `RUST_BACKTRACE=1` for a backtrace
> thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:175

I know that my code is broken but compiller should not crush anyway.

rustc 1.6.0 (c30b771ad 2016-01-19)
binary: rustc
commit-hash: c30b771ad9d44ab84f8c88b80c25fcfde2433126
commit-date: 2016-01-19
host: x86_64-unknown-linux-gnu
release: 1.6.0

### LINKED ISSUE #38199: Compiler unexpectedly panicked - pattern matching to set const
I am setting a const on runtime (probably a bad idea)

I tried this code:

```rust
const DEV_MODE: bool = match env::var("GITLINKS_DEV_MODE") {
     Ok(something) => true,
     Err(e) => false
};
```
This is easily reproducible in the [rust-playground](https://is.gd/oErMYK): 

I expected to see this happen: Compilation/error

Instead, this happened: The compiler panicked
```
   Compiling hermes-rust-ci v0.1.0 (file:///Users/nicolas/Code/Gitlinks/hermes-rust-ci)
error: internal compiler error: ../src/librustc_typeck/check/dropck.rs:275: no enclosing scope found for scope: CodeExtent(928/Misc(NodeId(89)))
  --> src/main.rs:47:12
   |
47 |         Ok(something) => true,
   |            ^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace
```

## Meta

`rustc --version --verbose`:
```
rustc 1.13.0 (2c6933acc 2016-11-07)
binary: rustc
commit-hash: 2c6933acc05c61e041be764cb1331f6281993f3f
commit-date: 2016-11-07
host: x86_64-apple-darwin
release: 1.13.0
```
Backtrace:
```
   1:        0x10c378138 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10c3858ff - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10c382dad - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10c383446 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x108f7702b - std::panicking::begin_panic::hf3c77cb5fd5814c4
   6:        0x1090a1ba3 - rustc::session::opt_span_bug_fmt::{{closure}}::hf0e25c590c479ec5
   7:        0x108fbc6e9 - rustc::session::span_bug_fmt::h42d4c0a219d5e4ec
   8:        0x108fe1b5b - rustc_typeck::check::dropck::check_safety_of_destructor_if_necessary::hb235377900186746
   9:        0x108fb4ede - rustc::hir::Pat::walk_::h4efc10712dfc4116
  10:        0x108fb500e - rustc::hir::Pat::walk_::h4efc10712dfc4116
  11:        0x108fb46dc - rustc::hir::intravisit::walk_expr::he86193ca4385dfe8
  12:        0x108ff5597 - <rustc_typeck::check::regionck::RegionCtxt<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_expr::h8c3b7edd059225ea
  13:        0x108ff1dd0 - rustc_typeck::check::regionck::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::regionck_expr::hea9fefa930b3b048
  14:        0x10903d8d0 - rustc_typeck::check::check_const_with_type::hde9362004e8817d1
  15:        0x109037bc5 - rustc_typeck::check::check_item_type::h465806f7c36cce01
  16:        0x109031a8e - <rustc_typeck::check::CheckItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h232a101fa871d7c6
  17:        0x1090336d1 - rustc_typeck::check::check_item_types::h051b17d53935a164
  18:        0x10909d7a7 - rustc_typeck::check_crate::h54ff5b2dd08c0691
  19:        0x1087f070c - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h4091eeab6f271a29
  20:        0x1087cc956 - rustc_driver::driver::phase_3_run_analysis_passes::hff1c31d493acfd09
  21:        0x1087ba76a - rustc_driver::driver::compile_input::hef221f9f618e92f5
  22:        0x1087e2848 - rustc_driver::run_compiler::h7dddd4089f8330b4
  23:        0x108724340 - std::panicking::try::do_call::h1e3ece12e3f812df
  24:        0x10c385eba - __rust_maybe_catch_panic
  25:        0x108743004 - <F as alloc::boxed::FnBox<A>>::call_box::h05b222e46803eb30
  26:        0x10c382064 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  27:     0x7fffd1eb3aaa - _pthread_body
  28:     0x7fffd1eb39f6 - _pthread_start
```

### LINKED ISSUE #40012: ICE: Implement discriminant const qualify
Currently, the compiler will ICE if you have a `match` on an enum within a `const` function. If this isn't implemented, it should at least warn the user instead of showing an ICE.

Example here: https://is.gd/r4d3MB

### PR DESCRIPTION
**Pull request by ryan-scott-dev**
Fixed 2 ICEs with when pattern matching inside a constant expression.

Both of these ICEs now resolve to an appropriate compiler error.

1. ICE was caused by a compiler bug to implement discriminant const qualify.

    I removed this intentionally thrown bug and changed it to a FIXME as the unimplemented expression type is handled as a compiler error elsewhere.

2. ICE was caused during a drop check when checking if a variable lifetime outlives the current scope if there was no parent scope .

    I've changed it to stop checking if there is no parent scope for the current scope. It is valid syntax for a const variable to be assigned a match expression with no enclosing scope.

    The ICE seemed to mainly be used as a defensive check for bugs elsewhere.

Fixes #38199.
Fixes #31577.
Fixes #29093.
Fixes #40012.

### CODE REVIEW

File: src/librustc_mir/transform/qualify_consts.rs [hunk 1]
```diff
@@ -722,11 +722,9 @@ impl<'a, 'tcx> Visitor<'tcx> for Qualifier<'a, 'tcx, 'tcx> {
             }
 
             Rvalue::Discriminant(..) => {
-                // FIXME discriminant
+                // FIXME implement discriminant const qualify
                 self.add(Qualif::NOT_CONST);
-                if self.mode != Mode::Fn {
-                    bug!("implement discriminant const qualify");
-                }
+                // Discriminants in consts will error elsewhere as an unimplemented expression type
```
Comment (arielb1) [inline src/librustc_mir/transform/qualify_consts.rs]: You are not calling `.not_const()` because we report an error for the `SwitchInt` terminator too?

**Comment by arielb1** [comment]
r+ if you make `Rvalue::Discriminant` a valid const, even if you don't impl it in trans.

**Comment by brson** [comment]
Awesome fixes for old ices @Archytaus!

**Comment by Archytaus** [comment]
> r+ if you make Rvalue::Discriminant a valid const, even if you don't impl it in trans.

@arielb1 To clarify, do you mean making it valid by removing `self.add(Qualif::NOT_CONST);` and the comments?

I wouldn't mind trying to implement it in trans, but I would be taking my time learning how that part of the compiler works. So I would want to do that in another PR if possible.

**Comment by arielb1** [comment]
@Archytaus 

Yup. Remove the `self.add(Qualif::NOT_CONST);`. We should have MIRI soon enough, so you don't really need to implement it in trans.
