### PR TITLE
Fix invalid `mut T` suggestion for `&mut T` in missing lifetime error

### LINKED ISSUE #150077: E0106: help diagonistic suggests invalid syntax `mut T`
### Code

```Rust
fn foo(_f: impl Fn() -> &mut ()) {}
```

### Current output

```Shell
error[E0106]: missing lifetime specifier
 --> bad.rs:1:25
  |
1 | fn foo(_f: impl Fn() -> &mut ()) {}
  |                         ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
  |
1 | fn foo(_f: impl Fn() -> &'static mut ()) {}
  |                          +++++++
help: instead, you are more likely to want to return an owned value
  |
1 - fn foo(_f: impl Fn() -> &mut ()) {}
1 + fn foo(_f: impl Fn() -> mut ()) {}
  |
```

### Desired output

```Shell
error[E0106]: missing lifetime specifier
 --> bad.rs:1:25
  |
1 | fn foo(_f: impl Fn() -> &mut ()) {}
  |                         ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
  |
1 | fn foo(_f: impl Fn() -> &'static mut ()) {}
  |                          +++++++
help: instead, you are more likely to want to return an owned value
  |
1 - fn foo(_f: impl Fn() -> &mut ()) {}
1 + fn foo(_f: impl Fn() -> ()) {}
  |
```

### Rationale and extra context

In type annotations for closure return types, the help diagnostic suggests returning an owned value instead of a reference. However, it suggests the invalid syntax `mut T`, only removing the `&` instead of the full `&mut`. It should most likely suggest changing `&mut T` into `T` instead.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.92.0 (ded5c06cf 2025-12-08)
binary: rustc
commit-hash: ded5c06cf21d2b93bffd5d884aa6e96934ee4234
commit-date: 2025-12-08
host: aarch64-pc-windows-msvc
release: 1.92.0
LLVM version: 21.1.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by reddevilmidzy**
close: rust-lang/rust#150077

When suggesting to return an owned value instead of a borrowed one, the diagnostic was only removing `&` instead of `&mut `, resulting in invalid syntax like `mut T`. This PR fixes the span calculation to properly cover the entire `&mut ` prefix.

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -3937,6 +3938,13 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
                             }
                         }
                         if owned_sugg {
+                            if !sugg_is_str_to_string {
```
Comment (fee1-dead) [inline compiler/rustc_resolve/src/late/diagnostics.rs]: Can you add a test for `&mut str`?

Comment (fee1-dead) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Would be nice to use let chains if possible here.

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 1 above)
Comment (reddevilmidzy) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: > Can you add a test for &mut str?

Okay! In the existing code, `&mut str` was suggesting `str`.
`sugg_is_str_to_string` was handling only the case for the return type, so I fixed this part.

> Would be nice to use let chains if possible here.

cool! I've applied your suggestion
