### PR TITLE
fix dead link for method in trait of blanket impl from third party crate

### LINKED ISSUE #86620: rustdoc links to the wrong method anchor
I tried this code: https://github.com/laysakura/serde-encrypt/commit/b46c11860bf83845e6b8053d04525cb44295e510

I expected to see this happen: All links rustdoc generates are valid.

Instead, this happened: `In impl<V: Multilane, T> VZip for T`, on `encrypt/encrypted_message/struct.EncryptedMessage.html`, the function vzip links to #tymethod.vzip, but the proper link is #method.vzip. This causes the anchor to go nowhere.

### Meta

`rustdoc --version`: rustdoc 1.53.0 (53cb7b09b 2021-06-17)

This is also present on rustdoc 1.55.0-nightly (7c3872e6b 2021-06-24).

### PR DESCRIPTION
**Pull request by mockersf**
fix #86620

* changes `href` method to raise the actual error it had instead of an `Option`
* set the href link correctly in case of an error

I did not manage to make a small reproducer, I think it happens in a situation where
* crate A expose a trait with a blanket impl
* crate B use the trait from crate A
* crate C use types from crate B
* building docs for crate C without dependencies

r? @jyn514

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -921,7 +923,7 @@ fn render_assoc_item(
         w.reserve(header_len + "<a href=\"\" class=\"fnname\">{".len() + "</a>".len());
         write!(
             w,
-            "{indent}{vis}{constness}{asyncness}{unsafety}{defaultness}{abi}fn <a href=\"{href}\" class=\"fnname\">{name}</a>\
+            "{indent}{vis}{constness}{asyncness}{unsafety}{defaultness}{abi}fn <a {href} class=\"fnname\">{name}</a>\
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:926]: Are you sure this is correct? I don't think it's valid to have a link without an href.

File: src/librustdoc/html/format.rs [hunk 2]
```diff
@@ -456,15 +456,26 @@ impl clean::GenericArgs {
     }
 }
 
-crate fn href(did: DefId, cx: &Context<'_>) -> Option<(String, ItemType, Vec<String>)> {
+// Possible errors when computing href link source for a `DefId`
+crate enum HrefError {
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:460]: This would help quite a lot with https://github.com/rust-lang/rust/pull/82014 I think :) good idea.

**Review by jyn514 — COMMENTED** [review]
I would like to find a test for the other crate before merging this; I'll try to do that this afternoon. I don't yet understand why your fix works.

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (mockersf) [reply src/librustdoc/html/render/mod.rs:926]: It's not the prettiest, but according to https://www.w3schools.com/tags/att_a_href.asp it's valid.

**Comment by jyn514** [comment]
Can you add the MCVE from the issue as a test? I'll review this in the meantime and see if I understand it better now.

File: src/librustdoc/html/format.rs [hunk 3]
```diff
@@ -456,15 +456,26 @@ impl clean::GenericArgs {
...
+    // `DefId` is in an unknown location. This seems to happen when building without dependencies
+    // but a trait from a dependency is still visible
+    UnknownLocation,
+    // Unavailable because private
+    Unavailable,
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:465]: That implies this should never be hit with --document-private-items, right?
```suggestion
    /// This can only happen for non-local items when `--document-private-items` is not passed.
    Private,
```

File: src/librustdoc/html/format.rs [hunk 4]
```diff
@@ -456,15 +456,26 @@ impl clean::GenericArgs {
     }
 }
 
-crate fn href(did: DefId, cx: &Context<'_>) -> Option<(String, ItemType, Vec<String>)> {
+// Possible errors when computing href link source for a `DefId`
+crate enum HrefError {
+    // `DefId` is in an unknown location. This seems to happen when building without dependencies
+    // but a trait from a dependency is still visible
+    UnknownLocation,
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:463]: This happens when `cache.extern_locations[&did.krate]` is `ExternLocation::Unknown`. That has nothing to do with traits, it can happen for any item from a crate without documentation built.
```suggestion
    /// This item is known to rustdoc, but from a crate that does not have documentation generated.
    ///
    /// This can only happen for non-local items.
    DocumentationNotBuilt,
```

File: src/librustdoc/html/format.rs [hunk 5]
```diff
@@ -456,15 +456,26 @@ impl clean::GenericArgs {
...
+}
+
+crate fn href(did: DefId, cx: &Context<'_>) -> Result<(String, ItemType, Vec<String>), HrefError> {
     let cache = &cx.cache();
     let relative_to = &cx.current;
     fn to_module_fqp(shortty: ItemType, fqp: &[String]) -> &[String] {
         if shortty == ItemType::Module { &fqp[..] } else { &fqp[..fqp.len() - 1] }
     }
 
     if !did.is_local() && !cache.access_levels.is_public(did) && !cache.document_private {
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:477]: So, `!is_local` looks correct to me, but for a non-trivial reason - the `strip_private` pass should get rid of private local items before they ever get here. Can you change this to an assert instead?
```suggestion
    if did.is_local() {
        // Private items should have already been stripped.
        assert!(cache.access_levels.is_public(did) || cache.document_private);
    }
    if !cache.access_levels.is_public(did) && !cache.document_private {
```
(I know this is unrelated to your change - I can make a separate PR for this if you like.)

File: src/librustdoc/html/format.rs [hunk 6]
```diff
@@ -456,15 +456,26 @@ impl clean::GenericArgs {
...
-        return None;
+        return Err(HrefError::Unavailable);
     }
 
     let (fqp, shortty, mut url_parts) = match cache.paths.get(&did) {
```
Comment (jyn514) [inline src/librustdoc/html/format.rs:481]: Oof, having this be different from `exact_paths` is very concerning. There's a lot of cleanup rustdoc needs to do here :sweat_smile: not related to your PR though

File: src/librustdoc/html/render/mod.rs [hunk 7]
```diff
@@ -884,9 +884,11 @@ fn render_assoc_item(
...
                 };
 
-                href(did.expect_real(), cx)
-                    .map(|p| format!("{}#{}.{}", p.0, ty, name))
-                    .unwrap_or_else(|| format!("#{}.{}", ty, name))
+                match href(did.expect_real(), cx) {
+                    Ok(p) => Some(format!("{}#{}.{}", p.0, ty, name)),
+                    Err(HrefError::UnknownLocation) => None,
+                    Err(_) => Some(format!("#{}.{}", ty, name)),
+                }
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:891]: This does not look like the right fix. I expect if you change `cargo doc --no-deps` to `cargo doc` you'll still run into the same issue (you can test with `cargo deadlinks --dir target/doc`).

The proper fix is probably to use `#tymethod` for external methods and `#method` for local ones? *Something* about the if on line 881 looks wrong, I'm not sure exactly what.

**Review by jyn514 — CHANGES_REQUESTED** [review]
This is not the right fix, see below.

File: src/librustdoc/html/format.rs (hunk 5 above)
Comment (mockersf) [reply src/librustdoc/html/format.rs:477]: adding this assert made the following test fail:
```
failures:
    [rustdoc] rustdoc/all.rs
    [rustdoc] rustdoc/async-fn.rs
    [rustdoc] rustdoc/blanket-reexport-item.rs
    [rustdoc] rustdoc/impl-trait-alias.rs
    [rustdoc] rustdoc/inline_cross/renamed-via-module.rs
    [rustdoc] rustdoc/inline_local/glob-private-no-defaults.rs
    [rustdoc] rustdoc/inline_local/glob-private.rs
    [rustdoc] rustdoc/inline_local/issue-28537.rs
    [rustdoc] rustdoc/inline_local/issue-32343.rs
    [rustdoc] rustdoc/inline_local/trait-vis.rs
    [rustdoc] rustdoc/intra-doc/cross-crate/hidden.rs
    [rustdoc] rustdoc/issue-34473.rs
    [rustdoc] rustdoc/issue-35488.rs
    [rustdoc] rustdoc/issue-46767.rs
    [rustdoc] rustdoc/namespaces.rs
    [rustdoc] rustdoc/redirect-map.rs
    [rustdoc] rustdoc/redirect-rename.rs
    [rustdoc] rustdoc/redirect.rs
    [rustdoc] rustdoc/search-index.rs
    [rustdoc] rustdoc/struct-arg-pattern.rs
    [rustdoc] rustdoc/synthetic_auto/complex.rs
    [rustdoc] rustdoc/synthetic_auto/project.rs
```

**Comment by mockersf** [comment]
> Can you add the MCVE from the issue as a test? I'll review this in the meantime and see if I understand it better now.

I think I added the MCVE with the correct annotations. The test is working with this PR, and not without

File: src/librustdoc/html/render/mod.rs (hunk 7 above)
Comment (mockersf) [reply src/librustdoc/html/render/mod.rs]: I tried building docs with and without dependencies for `serde-encrypt`, no deadlinks on `vzip`.

Yes, `#method` is for the link on the local method, and is available on the mouse over anchor. `#tymethod` would be the link to the trait definition, on the function name, but it's not available here and this fix removes it.

File: src/librustdoc/html/render/mod.rs [hunk 8]
```diff
@@ -884,9 +884,11 @@ fn render_assoc_item(
                     ItemType::TyMethod
                 };
 
-                href(did.expect_real(), cx)
-                    .map(|p| format!("{}#{}.{}", p.0, ty, name))
-                    .unwrap_or_else(|| format!("#{}.{}", ty, name))
+                match href(did.expect_real(), cx) {
+                    Ok(p) => Some(format!("{}#{}.{}", p.0, ty, name)),
+                    Err(HrefError::DocumentationNotBuilt) => None,
```
Comment (jyn514) [inline src/librustdoc/html/render/mod.rs:889]: Ok, I think I see why I was confused - rustdoc can never be missing the documentation for the current crate, because it's building it right now.

Can you add an assert that `ty == ItemType::TyMethod` with a comment that TyMethods only appear for extern crates?

Comment (mockersf) [reply src/librustdoc/html/render/mod.rs]: This assert makes [this test](https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/extern-default-method.rs) fail (with [this include](https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/auxiliary/rustdoc-extern-default-method.rs)).

It seems it's possible to have a `ItemType::Method` when reexporting a struct with a method for which doc has not been built. I changed this PR to still allow this link as it's valid

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (jyn514) [reply src/librustdoc/html/render/mod.rs:909]: Ok. Can you add that link as a comment?

File: src/librustdoc/html/format.rs (hunk 5 above)
Comment (jyn514) [reply src/librustdoc/html/format.rs:494]: ahhhh of course it did :( I'll open an issue

File: src/librustdoc/html/format.rs (hunk 6 above)
Comment (jyn514) [reply src/librustdoc/html/format.rs:498]: Opened https://github.com/rust-lang/rust/issues/86798 which is not exactly the same issue but sort of cloes.

File: src/librustdoc/html/render/mod.rs (hunk 8 above)
Comment (jyn514) [reply src/librustdoc/html/render/mod.rs]: Do you happen to know why the test didn't fail without the assert? It seems to be testing that the `method.` link is generated - maybe it also needs to test that a `tymethod.` link is generated too?

**Comment by jyn514** [comment]
I don't really understand why this works, but I also won't have time to look into it in the near future and the tests seem about right, so r=me with both comments addressed.

File: src/librustdoc/html/format.rs (hunk 5 above)
Comment (jyn514) [reply src/librustdoc/html/format.rs:494]: Oh, I was just confused: the proper assert is
```
        assert!(cache.access_levels.is_public(did) || cache.document_private || cache.paths.get(&did).is_none(), "{:?}", did);
```

Comment (jyn514) [reply src/librustdoc/html/format.rs:494]: well, there was a bug after all: https://github.com/rust-lang/rust/issues/87048

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (mockersf) [reply src/librustdoc/html/render/mod.rs:909]: added 👍

File: src/librustdoc/html/render/mod.rs (hunk 8 above)
Comment (mockersf) [reply src/librustdoc/html/render/mod.rs]: As we are importing and using the struct in the current crate, we are importing its impl with its method, but the source is in the dependency and the doc is not built there...

The existing assertion was not on the link itself, but on the presence of the function in the doc. I added assertions on the links generated

**Comment by mockersf** [comment]
r=jyn514

**Comment by mockersf** [comment]
Thank you for your reviews, I think I addressed the two comments

r? @jyn514

**Comment by jyn514** [comment]
Looks good to me, but I want to wait for CI to pass.

@bors delegate=mockersf (please use r=jyn514)
