### PR TITLE
CFI: Fix cfi with async: transform_ty: unexpected GeneratorWitness(Bi…

### LINKED ISSUE #111184: ICE: cfi with async: `transform_ty: unexpected GeneratorWitness(Binder..`
### Code
`rustc  treereduce.out  --edition=2021 -Zsanitizer=cfi  -Zsanitizer-cfi-normalize-integers -Clto`
```Rust
use std::future::Future;

async fn data_moved_async() {}

fn run_fut<T>(fut: impl Future<Output = T>) -> T {
    loop {}
}

fn main() {
    run_fut(data_moved_async());
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (6f8c0557e 2023-05-04)
binary: rustc
commit-hash: 6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c
commit-date: 2023-05-04
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:881:13: transform_ty: unexpected `GeneratorWitness(Binder([], []))`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/compiler/rustc_errors/src/lib.rs:1643:9
stack backtrace:
   0:     0x7f9d9d369441 - std::backtrace_rs::backtrace::libunwind::trace::ha1124e3c4b659eb5
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f9d9d369441 - std::backtrace_rs::backtrace::trace_unsynchronized::h3a8d622ec81b6cb5
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9d9d369441 - std::sys_common::backtrace::_print_fmt::h2128e938c7086b6e
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f9d9d369441 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc50c3543d0b1b52f
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9d9d3ca0df - core::fmt::rt::Argument::fmt::h84c36e9580f5b71f
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/core/src/fmt/rt.rs:138:9
   5:     0x7f9d9d3ca0df - core::fmt::write::h326e01f7a9aa5dd9
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f9d9d35c4f1 - std::io::Write::write_fmt::h71f0f6281149b8c8
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/io/mod.rs:1712:15
   7:     0x7f9d9d369255 - std::sys_common::backtrace::_print::h6b9c2111a065fb89
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f9d9d369255 - std::sys_common::backtrace::print::hf8d0af7625f66057
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f9d9d36bee7 - std::panicking::default_hook::{{closure}}::h630fe7740556559d
  10:     0x7f9d9d36bcd4 - std::panicking::default_hook::h337047625b381696
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/panicking.rs:288:9
  11:     0x7f9da0571715 - rustc_driver_impl[f38315262de66e12]::DEFAULT_HOOK::{closure#0}::{closure#0}
  12:     0x7f9d9d36c607 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1ac669e77ecf459f
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/alloc/src/boxed.rs:1999:9
  13:     0x7f9d9d36c607 - std::panicking::rust_panic_with_hook::h22ef26cea64ec65c
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/panicking.rs:695:13
  14:     0x7f9da0a39901 - std[2e06b57a958d7603]::panicking::begin_panic::<rustc_errors[5778b576bff5e43e]::ExplicitBug>::{closure#0}
  15:     0x7f9da0a392a6 - std[2e06b57a958d7603]::sys_common::backtrace::__rust_end_short_backtrace::<std[2e06b57a958d7603]::panicking::begin_panic<rustc_errors[5778b576bff5e43e]::ExplicitBug>::{closure#0}, !>
  16:     0x7f9da0a5fca6 - std[2e06b57a958d7603]::panicking::begin_panic::<rustc_errors[5778b576bff5e43e]::ExplicitBug>
  17:     0x7f9da0a5d114 - <rustc_errors[5778b576bff5e43e]::HandlerInner>::bug::<alloc[3df6c3833cdafa3e]::string::String>
  18:     0x7f9da0a5ce46 - <rustc_errors[5778b576bff5e43e]::Handler>::bug::<alloc[3df6c3833cdafa3e]::string::String>
  19:     0x7f9da0ae52cc - rustc_middle[9b03ef73197c8750]::util::bug::opt_span_bug_fmt::<rustc_span[e5d9edf586a8e474]::span_encoding::Span>::{closure#0}
  20:     0x7f9da0ae4afa - rustc_middle[9b03ef73197c8750]::ty::context::tls::with_opt::<rustc_middle[9b03ef73197c8750]::util::bug::opt_span_bug_fmt<rustc_span[e5d9edf586a8e474]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f9da0ae4aca - rustc_middle[9b03ef73197c8750]::ty::context::tls::with_context_opt::<rustc_middle[9b03ef73197c8750]::ty::context::tls::with_opt<rustc_middle[9b03ef73197c8750]::util::bug::opt_span_bug_fmt<rustc_span[e5d9edf586a8e474]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f9d9ec50ccd - rustc_middle[9b03ef73197c8750]::util::bug::bug_fmt
  23:     0x7f9da0fc9752 - rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_ty
  24:     0x7f9da0fc5613 - <&mut rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_substs::{closure#0} as core[351080cb3919538e]::ops::function::FnOnce<(rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg,)>>::call_once
  25:     0x7f9da0fd4beb - <smallvec[163c2c57480b45e5]::SmallVec<[rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg; 8usize]> as core[351080cb3919538e]::iter::traits::collect::Extend<<[rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg; 8usize] as smallvec[163c2c57480b45e5]::Array>::Item>>::extend::<core[351080cb3919538e]::iter::adapters::map::Map<core[351080cb3919538e]::iter::adapters::copied::Copied<core[351080cb3919538e]::slice::iter::Iter<rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg>>, rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_substs::{closure#0}>>
  26:     0x7f9da0fcf19e - <rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg as rustc_type_ir[2476610ddda7a73]::CollectAndApply<rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg, &rustc_middle[9b03ef73197c8750]::ty::list::List<rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg>>>::collect_and_apply::<core[351080cb3919538e]::iter::adapters::map::Map<core[351080cb3919538e]::iter::adapters::copied::Copied<core[351080cb3919538e]::slice::iter::Iter<rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg>>, rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_substs::{closure#0}>, <rustc_middle[9b03ef73197c8750]::ty::context::TyCtxt>::mk_substs_from_iter<core[351080cb3919538e]::iter::adapters::map::Map<core[351080cb3919538e]::iter::adapters::copied::Copied<core[351080cb3919538e]::slice::iter::Iter<rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg>>, rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_substs::{closure#0}>, rustc_middle[9b03ef73197c8750]::ty::subst::GenericArg>::{closure#0}>
  27:     0x7f9da0fc91c5 - rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::transform_ty
  28:     0x7f9da0fc9db1 - rustc_symbol_mangling[1bf499ff7f75842a]::typeid::typeid_itanium_cxx_abi::typeid_for_fnabi
  29:     0x7f9d9eb7059f - <rustc_codegen_llvm[d78081c433bf4e31]::context::CodegenCx as rustc_codegen_ssa[7c934ba332e0ab85]::traits::declare::PreDefineMethods>::predefine_fn
  30:     0x7f9d9fa1a0dd - rustc_codegen_llvm[d78081c433bf4e31]::base::compile_codegen_unit::module_codegen
  31:     0x7f9d9fa18fb0 - rustc_codegen_llvm[d78081c433bf4e31]::base::compile_codegen_unit
  32:     0x7f9d9fc5c416 - rustc_codegen_ssa[7c934ba332e0ab85]::base::codegen_crate::<rustc_codegen_llvm[d78081c433bf4e31]::LlvmCodegenBackend>
  33:     0x7f9d9fc5bce2 - <rustc_codegen_llvm[d78081c433bf4e31]::LlvmCodegenBackend as rustc_codegen_ssa[7c934ba332e0ab85]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7f9d9f7ff8e0 - rustc_interface[32f66f6c15b482f4]::passes::start_codegen
  35:     0x7f9d9f7facc7 - <rustc_middle[9b03ef73197c8750]::ty::context::GlobalCtxt>::enter::<<rustc_interface[32f66f6c15b482f4]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[351080cb3919538e]::result::Result<alloc[3df6c3833cdafa3e]::boxed::Box<dyn core[351080cb3919538e]::any::Any>, rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>
  36:     0x7f9d9f7fa2a8 - <rustc_interface[32f66f6c15b482f4]::queries::Queries>::ongoing_codegen
  37:     0x7f9d9f7f99e3 - <rustc_interface[32f66f6c15b482f4]::interface::Compiler>::enter::<rustc_driver_impl[f38315262de66e12]::run_compiler::{closure#1}::{closure#2}, core[351080cb3919538e]::result::Result<core[351080cb3919538e]::option::Option<rustc_interface[32f66f6c15b482f4]::queries::Linker>, rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>
  38:     0x7f9d9f7f714f - std[2e06b57a958d7603]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[32f66f6c15b482f4]::util::run_in_thread_pool_with_globals<rustc_interface[32f66f6c15b482f4]::interface::run_compiler<core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>, rustc_driver_impl[f38315262de66e12]::run_compiler::{closure#1}>::{closure#0}, core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>
  39:     0x7f9d9fe58a1e - <<std[2e06b57a958d7603]::thread::Builder>::spawn_unchecked_<rustc_interface[32f66f6c15b482f4]::util::run_in_thread_pool_with_globals<rustc_interface[32f66f6c15b482f4]::interface::run_compiler<core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>, rustc_driver_impl[f38315262de66e12]::run_compiler::{closure#1}>::{closure#0}, core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[351080cb3919538e]::result::Result<(), rustc_span[e5d9edf586a8e474]::ErrorGuaranteed>>::{closure#1} as core[351080cb3919538e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7f9d9d376ad5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4e640066a72afb4
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/alloc/src/boxed.rs:1985:9
  41:     0x7f9d9d376ad5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6a43b4ec147b3dd9
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/alloc/src/boxed.rs:1985:9
  42:     0x7f9d9d376ad5 - std::sys::unix::thread::Thread::new::thread_start::h8c269a865bc351fb
                               at /rustc/6f8c0557e0b73c73a8a7163a15f4a5a3feca7d5c/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7f9d9d112bb5 - <unknown>
  44:     0x7f9d9d194d90 - <unknown>
  45:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (6f8c0557e 2023-05-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=cfi -Z sanitizer-cfi-normalize-integers -C lto

query stack during panic:
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by rcvalle**
Fixes https://github.com/rust-lang/rust/issues/111184 by encoding ty::Generator parent substs only.

### CODE REVIEW

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 1]
```diff
@@ -739,7 +747,12 @@ fn transform_ty<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>, options: TransformTyOptio
     let mut ty = ty;
 
     match ty.kind() {
-        ty::Float(..) | ty::Char | ty::Str | ty::Never | ty::Foreign(..) => {}
+        ty::Float(..)
+        | ty::Char
+        | ty::Str
+        | ty::Never
+        | ty::Foreign(..)
+        | ty::GeneratorWitness(..) => {}
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:755]: Why aren't you transforming any of the types *within* the generator?

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 2]
```diff
@@ -306,7 +306,15 @@ fn encode_substs<'tcx>(
                     s.push_str(&encode_region(tcx, region, dict, options));
                 }
                 GenericArgKind::Type(ty) => {
-                    s.push_str(&encode_ty(tcx, ty, dict, options));
+                    match *ty.kind() {
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:309]: Why not just change the way we encode `ty::Generator` so that we never encounter `GeneratorWitness` when encoding types?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:755]: Neither the generator types nor their substs need to be transformed, just encoded. `transform_ty` coalesces types that have the same encoding into a single entity (e.g., c_void into unit), normalizes, and generalizes types before handing them to encode_ty. It greatly simplifies the encoding and compression/substitution logic.

Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:755]: What if a generator captures a `c_void` across an await point? Why are all the other transformations in this fn happening structurally except for generators? Still not sure if I understand.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:309]: Do you have an example of what you mean? I don't think we don't want to encounter a ty::GeneratorWitness but want to encode it correctly as part of substs as specified by the encoding.

File: tests/ui/issues/issue-111184.rs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+// run-pass
```
[the remark this answers is not in the document]
Comment (rcvalle) [reply tests/ui/issues/issue-111184.rs:1]: Would tests/ui/issues/sanitizer/issue-111184.rs be a good place for it?

[the remark this answers is not in the document]
Comment (compiler-errors) [reply tests/ui/issues/issue-111184.rs:1]: `sanitizer/cfi`? idk. Also, I would probably give the test a more descriptive name that says what it's actually testing.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:309]: I would walk up the call tree and modify the code that's responsible for encoding generators to handle the generator witness there (see https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/list/struct.List.html#method.as_generator) rather than doing it here.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:755]: Ahh, indeed. You're right. I should traverse the ty::GeneratorWitness substs looking for types that need to be transformed--I'll fix it. Thanks for pointing that out!

File: tests/ui/issues/issue-111184.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (compiler-errors) [reply tests/ui/issues/issue-111184.rs:1]: > I see tidy is still complaining about this path.

Can you be more specific?

**Comment by bjorn3** [comment]
Can't you encode `ty::Generator` as just the `DefId` + the `parent_substs()` part of the `GeneratorSubsts`? The witness and upvars should be uniquely determined by those two afaik.

File: tests/ui/issues/issue-111184.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nilstrieb) [reply tests/ui/issues/issue-111184.rs:1]: `tests/ui/sanitizer/cfi/generators.rs` sounds like a good place. Although I'm not sure where you put other cfi ui tests if they exist already, they should all be together

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:309]: Done.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: Done.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:309]: Are you suggesting to encode `ty::GeneratorWitness` in `encode_ty`? The reason why it's encoded in `encode_substs` and not in `encode_ty` is because it should never occur as a standalone type in `encode_ty`, and if so, it should trigger an unexpected ty bug.

File: tests/ui/issues/issue-111184.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (rcvalle) [reply tests/ui/issues/issue-111184.rs]: The reason I'm keeping this test separate (e.g., from https://github.com/rust-lang/rust/blob/master/tests/codegen/sanitizer-cfi-emit-type-metadata-id-itanium-cxx-abi.rs) is because it requires ` --edition=2021` and I didn't want to switch the other CFI tests to it just yet. (Maybe I can come up with an example that doesn't use async and doesn't require it.)

[the remark this answers is not in the document]
Comment (Nilstrieb) [reply tests/ui/issues/issue-111184.rs]: i don't think having the edition be consistent is very important. using 2021 (or 2018) here but not for the other tests sounds reasonable

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: After chatting with @bjorn3 and @bjorn3 explaining me the `ty::GeneratorWitness` in more detail, we decided that we don't want to encode `ty::GeneratorWitness`. So I just changed these changes to expect but not encode it.

File: tests/ui/issues/issue-111184.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (rcvalle) [reply tests/ui/issues/issue-111184.rs]: I moved it to tests/ui/sanitize/issue-111184-generator-witness.rs alongside the currently existing tests/ui/sanitize/issue-72154-lifetime-markers.rs and following the same format used. Let me know if there is anything else I should change.

**Comment by bjorn3** [comment]
@compiler-errors do you think the new implementation makes sense?

**Review by compiler-errors — COMMENTED** [review]
Hmm, this doesn't implement either mine or @bjorn3's suggestions, does it? I think we need to split out the branch for `ty::Generator` in `encode_ty`, and either:

* As bjorn3 suggested, only encode the def-id and parent substs
* As I suggested, "skip" the generator witness by destructuring the generator witness so we never encounter `ty::GeneratorWitness` in `encode_ty` at all.

**Comment by compiler-errors** [comment]
For the record, @bjorn3's suggestion is probably easier to implement. Generators can't be polymorphic so they are totally uniquely determined by their def path + parent substs.

**Comment by rcvalle** [comment]
I *think* it implements @bjorn3's suggestion by just skipping encoding `ty::GeneratorWitness`, which will happen only as a `ty::Generator` substitution, but the parent DefId and substitutions (other than the `ty::GeneratorWitness` will be encoded when encoding the `ty::Generator` itself.  Does it sound right to you?

**Comment by compiler-errors** [comment]
No, that's not exactly right. You need to get the generator substs and explicitly extract *just* the parent substitutions from that.

`substs`[`.as_generator()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/list/struct.List.html#method.as_generator)[`.split()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.GeneratorSubsts.html#method.split)[`.parent_substs`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.GeneratorSubstsParts.html#structfield.parent_substs) and then pass *that* to `encode_substs`.

The current implementation is still encoding all the other substs except for the witness in `GeneratorSubstsParts` (https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.GeneratorSubstsParts.html#structfield.resume_ty).

**Comment by rcvalle** [comment]
Oh, I see. There are other substitutions besides the parent and the witness, and skipping just the witness will still include other substitutions besides the parent that we don't want. Thanks for pointing it out! I'll fix it.

**Comment by rcvalle** [comment]
Done. Let me know if it looks good to you!

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 4]
```diff
@@ -853,7 +853,16 @@ fn transform_ty<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>, options: TransformTyOptio
         }
 
         ty::Generator(def_id, substs, movability) => {
-            ty = tcx.mk_generator(*def_id, transform_substs(tcx, substs, options), *movability);
+            // Encode parent substs only
+            ty = tcx.mk_generator(
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: This is not a valid generator type -- you probably should be handling the `substs.as_generator().parent_substs()` part in `encode_ty`, not `transform_ty`.

Here, you should just be splitting the generator substs into its parts, transforming the parent substs, and then reconstructing the generator ty from that.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: Humm, I don't quite understand. The DefId and substs are the only values used in encoding--it doesn't need to be a valid type. (We do the same for other types.) Am I missing something?

The generators also need to match in the substitution dictionary, so transforming this way here ensures they'll be all the same in the dictionary.

Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: > We do the same for other types.

That's not great. You should not be constructing types that are invalid. If you really need to collapse types into some minimal representation to use in some dictionary, you shouldn't be using `Ty<'tcx>` at all, to be honest.

Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: Sorry, to be clear, you shouldn't be constructing types that are invalid because the compiler has hard-coded assumptions about the structure of these types, and you should be following those. I'm actually gonna probably make these assumptions even more hard coded in #112189.

For example, that CI failure that just occurred (https://github.com/rust-lang/rust/pull/111914#issuecomment-1572877008) is because you're misusing the `ty::Generator` variant, which you should not be doing.

That's a risk because:
1. it introduces more ways for the compiler to crash
2. it makes it harder to review and refactor this code in the future

Among other reasons.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: Makes sense. Thanks for the explanation! I may still need to create/transform these generators in encode_ty for the substitution dictionary though, but I'll ensure they're are structurally valid. (I'll need some time to think and work on refactoring it if we decide to use something other than `Ty<'tcx>` in the substitution dictionary in the future.)

Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: I guess let's compromise here -- you can transform the substs normally, but add a no-op branch for `ty::GeneratorWitness` in `transform_ty`. 

Then in `encode_ty`, you should continue to ICE if you encounter `ty::GeneratorWitness`, but you shouldn't ever hit it because you'll do the parent substs-only encoding as suggested above.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:857]: Sounds good to me! Will do it.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs]: Done. Let me know if it looks good to you!

**Review by compiler-errors — APPROVED** [review]

**Comment by rcvalle** [comment]
Thank you again for your time and for your help on this, @compiler-errors! Much appreciated.
