### PR TITLE
Remove 'elided' from lifetime resolution error

### LINKED ISSUE #29094: Ambiguous elided lifetime error claims non-elided lifetime is elided
``` rust
struct Thing<'a>(&'a ());

fn func1<'a>(_arg: &'a Thing) -> &() { unimplemented!() }
fn func2<'a>(_arg: &Thing<'a>) -> &() { unimplemented!() }
```

gives

```
test.rs:3:34: 3:37 error: missing lifetime specifier [E0106]
test.rs:3 fn func1<'a>(_arg: &'a Thing) -> &() { unimplemented!() }
                                           ^~~
test.rs:3:34: 3:37 help: run `rustc --explain E0106` to see a detailed explanation
test.rs:3:34: 3:37 help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 elided lifetimes it is borrowed from
test.rs:4:35: 4:38 error: missing lifetime specifier [E0106]
test.rs:4 fn func2<'a>(_arg: &Thing<'a>) -> &() { unimplemented!() }
                                            ^~~
test.rs:4:35: 4:38 help: run `rustc --explain E0106` to see a detailed explanation
test.rs:4:35: 4:38 help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 elided lifetimes it is borrowed from
error: aborting due to 2 previous errors
```

Each time it refers to "`_arg`'s 2 elided lifetimes", but in both cases only one of `_arg`'s lifetimes is elided.

### PR DESCRIPTION
**Pull request by stephen-lazaro**
Removes 'elided' from lifetime resolution errors
Removes 'elided' from relevant error messaging tests

This PR resolves https://github.com/rust-lang/rust/issues/29094

r? @Mark-Simulacrum

### CODE REVIEW

File: src/test/compile-fail/issue-30255.rs [hunk 1]
```diff
@@ -17,19 +17,19 @@ struct S<'a> {
 
 fn f(a: &S, b: i32) -> &i32 {
 //~^ ERROR missing lifetime specifier [E0106]
-//~^^ HELP does not say which one of `a`'s 2 elided lifetimes it is borrowed from
+//~^^ HELP does not say which one of `a`'s 2 lifetimes it is borrowed from
```
Comment (frewsxcv) [inline src/test/compile-fail/issue-30255.rs]: in my opinion, in this instance, the help message is clearer here with the word 'elided'

Comment (Mark-Simulacrum) [inline src/test/compile-fail/issue-30255.rs]: Yeah, I'm not sure if we can detect this case though.

**Comment by Mark-Simulacrum** [comment]
cc @estebank, you've worked with diagnostics quite a bit -- do you think removing elided is the best approach here or should we try to put more code in to deal with more cases?

**Comment by arielb1** [comment]
@bors r+ rollup

@nikomatsakis is trying to change how elision works, but this should work for now.

**Comment by estebank** [comment]
> you've worked with diagnostics quite a bit -- do you think removing elided is the best approach here or should we try to put more code in to deal with more cases?

@Mark-Simulacrum, I believe we don't track elided lifetimes, which would make for a much bigger PR in order to track that (I might be wrong about this though).

I'm ok with this change (and it's been already +1'd) as long as we keep a ticket around to expand on this in the future. For example, in [the cases presented](https://is.gd/jqhZoE) in [the original ticket](https://github.com/rust-lang/rust/issues/29094), it should mention `'a` as one of the possible lifetimes.
