### PR TITLE
Don't dynamically link LLVM tools unless rustc is too

### LINKED ISSUE #76698: rust-lld broken on latest x86_64-apple-darwin nightly
The bundled `rust-lld` linker seems to be broken on macOS on the latest nightly (2020-09-13). The following error occurs:

```
error: linking with `rust-lld` failed: signal: 6
  |
  = note: "rust-lld" "-flavor" "gnu" "--eh-frame-hdr" […]
  = note: dyld: Library not loaded: @rpath/libLLVM.dylib
            Referenced from: /Users/runner/work/x86_64/x86_64/testing/target/sysroot/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
            Reason: image not found
```

It worked fine with yesterdays nightly (2020-09-12). The exact version numbers are listed below.

Judging from the [diff between these two nightlies](https://github.com/rust-lang/rust/compare/dbb73f8f79ab176a897d5a95e696adb71b957cbe...7402a394471a6738a40fea7d4f1891666e5a80c5), this might be caused by https://github.com/rust-lang/rust/pull/76349. cc @Mark-Simulacrum 

### Meta

Failed on:

> rustc 1.48.0-nightly (7402a3944 2020-09-13)
binary: rustc
commit-hash: 7402a394471a6738a40fea7d4f1891666e5a80c5
commit-date: 2020-09-13
host: x86_64-apple-darwin
release: 1.48.0-nightly
LLVM version: 11.0
cargo 1.48.0-nightly (875e01232 2020-09-08)
release: 1.48.0
commit-hash: 875e0123259b0b6299903fe4aea0a12ecde9324f
commit-date: 2020-09-08

Worked on:

> rustc 1.48.0-nightly (dbb73f8f7 2020-09-12)
binary: rustc
commit-hash: dbb73f8f79ab176a897d5a95e696adb71b957cbe
commit-date: 2020-09-12
host: x86_64-apple-darwin
release: 1.48.0-nightly
LLVM version: 11.0
cargo 1.48.0-nightly (875e01232 2020-09-08)
release: 1.48.0
commit-hash: 875e0123259b0b6299903fe4aea0a12ecde9324f
commit-date: 2020-09-08

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This PR initially tried to support link-shared on all of our target platforms (other than Windows), but ran into a number of difficulties:
 * LLVM doesn't really support a shared link on macOS (llvm-config runs into problems with the version suffix)
 * LLVM doesn't seem to support a shared link when cross-compiling (the libLLVM.so ends up empty and symbols are not found)

So, this PR has now been revised such that we don't attempt to dynamically link LLVM tools (even if that would, otherwise, be supported) on targets where LLVM is statically linked to rustc. Currently that's basically everything except for x86_64-unknown-linux-gnu (where we dynamically link to avoid rerunning ThinLTO in each stage).

Follow-up to #76708.
Fixes #76698.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never

I suspect the original PR had essentially no effect as a result of this "bug" so we'll want the no-rolling policy here too.

**Comment by jyn514** [comment]
```
running: "ar" "crs" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/libllvm-wrapper.a" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/llvm-wrapper/PassWrapper.o" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/llvm-wrapper/RustWrapper.o" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/llvm-wrapper/ArchiveWrapper.o" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/llvm-wrapper/CoverageMappingWrapper.o" "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out/llvm-wrapper/Linker.o"
  exit code: 0
  cargo:rustc-link-lib=static=llvm-wrapper
  cargo:rustc-link-search=native=/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0-rustc/x86_64-apple-darwin/release/build/rustc_llvm-7998fe2b8433c8ac/out
  cargo:rerun-if-env-changed=LLVM_LINK_SHARED

  --- stderr
  llvm-config: error: libLLVM-11-rust-1.48.0-nightly.dylib is missing
  thread 'main' panicked at 'command did not execute successfully: "/Users/runner/work/1/s/build/x86_64-apple-darwin/llvm/build/bin/llvm-config" "--link-shared" "--libs" "--system-libs" "aarch64" "arm" "asmparser" "avr" "bitreader" "bitwriter" "coverage" "hexagon" "instrumentation" "ipo" "linker" "lto" "mips" "msp430" "nvptx" "powerpc" "riscv" "sparc" "systemz" "webassembly" "x86"
  expected success, got: exit code: 1', src/build_helper/lib.rs:139:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
[RUSTC-TIMING] indexmap test:false 0.940
[RUSTC-TIMING] serde test:false 9.905
error: build failed
command did not execute successfully: "/Users/runner/work/1/s/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-Zbinary-dep-depinfo" "-j" "4" "--release" "--locked" "--color" "always" "--features" "jemalloc llvm max_level_info" "--manifest-path" "/Users/runner/work/1/s/compiler/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /Users/runner/work/1/s/build/bootstrap/debug/bootstrap dist
```

**Comment by Mark-Simulacrum** [comment]
r? @alexcrichton -- for context, this is "just" a continuation of https://github.com/rust-lang/rust/pull/76708 which essentially is just a re-implementation of that PR. The first commit fixes the enabling of link-shared and the second fixes builds with link-shared on macOS.

My impression is that before we landed https://github.com/rust-lang/rust/pull/76349 (e.g., on current stable) rustc_driver and rustc in general statically linked to LLVM, but we still shipped a libLLVM.dylib, and tools (like rust-lld) linked to that. After #76349 changed the logic to say "if llvm.link-shared is false, don't put the LLVM dylib in the sysroot," this broke tools like rust-lld on macOS. This PR, then, enables shared linking of LLVM to the rustc binary/rustc_driver, and fixes the LLVM build on macOS to support shared linking.

This provides us with two benefits:
 * Likely (though I haven't tested) the "download-ci-llvm" is now possible on macOS since we now support linking to a llvm dylib
 * We avoid shipping LLVM in both librustc_driver and libLLVM.dylib

We could explore an alternative which tries to statically link llvm tools, like we do on Windows, but we'd then likely not be able to support the CI-built LLVM locally, which seems unfortunate.

This PR is not something I'm personally a fan of -- I guess the "proper" thing to do is probably to try and talk to LLVM build system maintainers to try and work out why the macOS shared linking story is so oddly constructed with various parts of LLVM creating and doing different things (see commit message and comments for details). I tried to do some git history searching and googling but wasn't able to find anything that hinted at answers.

**Comment by alexcrichton** [comment]
Oh dear, so when we build LLVM with a custom version suffix, everything *but* `llvm-config` links to `libLLVM.dylib`, but `llvm-config` somehow gets linked (or at runtime expects?) `libLLVM-$our_version.dylib`, and so `llvm-config` fails? If so that sounds nasty...

We don't really have any options other than working around that though so seems reasonable enough, but yeah if someone is familiar with LLVM build sources this seems like a good thing to straighten out upstream.

**Comment by Mark-Simulacrum** [comment]
Yep, that's basically my impression. I tried to convince everything to use versioned suffixes, but it seems like there's some bits of code ... somewhere (it's a mess of CMake definitions) that's just ignoring the version. I also considered *not* setting the version suffix environment variable, but that also doesn't work because llvm-config still includes the major version, which isn't in the path on disk.

File: src/bootstrap/native.rs [hunk 1]
```diff
@@ -321,6 +310,38 @@ impl Step for Llvm {
...
+        // unversioned libLLVM.dylib and versioned
+        // `libLLVM-$MAJOR_VERSION-$VERSION_SUFFIX.dylib`. This is necessary for
+        // llvm-config to work, for example. Unfortunately, LLVM itself does not
+        // currently produce the versioned library name despite llvm-config
+        // expecting it, so for now just manually create it.
+        if target.contains("apple-darwin") && builder.config.llvm_link_shared {
+            let libdir = out_dir.join("lib");
+            let llvm_dylib_path = libdir.join("libLLVM.dylib");
+            if let Some(suffix) = crate::native::llvm_version_suffix(builder) {
+                let mut cmd = Command::new(&build_llvm_config);
```
Comment (alexcrichton) [inline src/bootstrap/native.rs:323]: I'm not sure I understand what's going on here. It seems like you're running `llvm-config` successfully here? But then you also need to copy around dylibs to make it run successfully? How does this work out?

File: src/bootstrap/native.rs [hunk 2]
```diff
@@ -321,6 +310,38 @@ impl Step for Llvm {
...
+                let version = output(cmd.arg("--version"));
+                let mut parts = version.split('.').take(2).filter_map(|s| s.parse::<u32>().ok());
+                if let Some(major) = parts.next() {
+                    builder.copy(
+                        &llvm_dylib_path,
+                        &libdir.join(&format!("libLLVM-{}{}.dylib", major, suffix)),
```
Comment (alexcrichton) [inline src/bootstrap/native.rs:329]: Can you explain a bit more what depends on this? How would a binary depend on a library that doesn't exist as part of the build process?

File: src/bootstrap/native.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/native.rs:323]: llvm-config can run with --version but will either not run or report "incorrect" information with other options. It isn't actually "linked" to libLLVM.dylib or the versioned dylib, it just does some directory traversal to find them beside itself at runtime with some commands, erroring out if it can't. If we don't do this we get the error in https://github.com/rust-lang/rust/pull/76810#issuecomment-693795808.

File: src/bootstrap/native.rs (hunk 2 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/native.rs:332]: llvm-config when run with --link-shared will look for this dylib and report an error if it doesn't exist (https://github.com/rust-lang/rust/pull/76810#issuecomment-693795808 has a snapshot of what the error looks like). That error isn't really accurate in the sense that the linker will resolve the `-lLLVM-11-rust-dev` it gets passed to libLLVM.dylib happily in my testing. I don't really understand quite how that works, though I suspect some of the macOS-specific install_name_tool logic.

I think it's plausible that we could just "touch" this file here rather than copying over the LLVM dylib, but I suspect that somewhere down the line something will want to read pieces of this file... (I haven't tested just touching it).

**Comment by Mark-Simulacrum** [comment]
I also pushed up some amendments to the documentation on the --version running, mostly duplicated with what I said here on github, but seems good to preserve that without having to follow git blame in the future. (I will squash it in before we merge)

**Comment by NateLing** [comment]
plz, I cannot build in production env!

**Comment by alexcrichton** [comment]
@bors: r+

Man something really weird is going on here. I don't think I fully understand it but you've answered enough questions of mine that I'm confident you have a better understanding than me, and this seems fine as a fix for now!

**Comment by jyn514** [comment]
```
  --- stderr
  llvm-config: error: libLLVM-11-rust-1.48.0-nightly.so is missing
  thread 'main' panicked at 'command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-musl/llvm/build/bin/llvm-config" "--link-shared" "--libs" "--system-libs" "aarch64" "arm" "asmparser" "avr" "bitreader" "bitwriter" "coverage" "hexagon" "instrumentation" "ipo" "linker" "lto" "mips" "msp430" "nvptx" "powerpc" "riscv" "sparc" "systemz" "webassembly" "x86"
  expected success, got: exit code: 1', src/build_helper/lib.rs:139:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jyn514** [comment]
```
[2312/2616] Linking CXX executable bin/llvm-itanium-demangle-fuzzer
FAILED: : && /x-tools/x86_64-unknown-netbsd/bin/x86_64--netbsd-g++-sysroot   -ffunction-sections -fdata-sections -fPIC -m64 -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-allow-shlib-undefined    -Wl,-rpath-link,/checkout/obj/build/x86_64-unknown-netbsd/llvm/build/./lib  -Wl,-O3 -Wl,--gc-sections tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o  -o bin/llvm-ar  lib/libLLVM-11-rust-1.48.0-nightly.so -lpthread -Wl,-rpath,"\$ORIGIN/../lib" && :
tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o: In function `llvm::detail::provider_format_adapter<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&>::format(llvm::raw_ostream&, llvm::StringRef)':
llvm-ar.cpp:(.text._ZN4llvm6detail23provider_format_adapterIRNSt6chrono10time_pointINS2_3_V212system_clockENS2_8durationIlSt5ratioILl1ELl1000000000EEEEEEE6formatERNS_11raw_ostreamENS_9StringRefE[_ZN4llvm6detail23provider_format_adapterIRNSt6chrono10time_pointINS2_3_V212system_clockENS2_8durationIlSt5ratioILl1ELl1000000000EEEEEEE6formatERNS_11raw_ostreamENS_9StringRefE]+0x5): undefined reference to `llvm::format_provider<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, void>::format(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&, llvm::raw_ostream&, llvm::StringRef)'
tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o: In function `llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul, 128ul>::~BumpPtrAllocatorImpl()':
llvm-ar.cpp:(.text._ZN4llvm20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EED2Ev[_ZN4llvm20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EED5Ev]+0x2d): undefined reference to `llvm::deallocate_buffer(void*, unsigned long, unsigned long)'
llvm-ar.cpp:(.text._ZN4llvm20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EED2Ev[_ZN4llvm20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EED5Ev]+0x7d): undefined reference to `llvm::deallocate_buffer(void*, unsigned long, unsigned long)'
tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.o: In function `getDefaultForHost()':
```
and a whole slew of other linker errors following.

**Comment by Mark-Simulacrum** [comment]
r? @alexcrichton since the latest update represents a pretty major change to this PR

I've given up on trying to make link-shared work well across the board -- see PR description and the last few CI failures -- it seems link LLVM is just not ready for a shared link on macOS or when cross-compiling, which excludes almost all of our builders :)

That said, this took the approach of disabling the shared LLVM link if we're not doing so with rustc, but it could also take the approach of editing dist.rs to distribute [libLLVM.dylib](https://github.com/Mark-Simulacrum/rust/blob/03e5e457f499d20d8aac8507ada8d43b75fdd227/src/bootstrap/dist.rs#L2397) (or the platform equivalent) whenever we're dynamically linking LLVM tools. I think I personally prefer to statically link -- we're likely to have slightly smaller aritfacts as a result and overall statically linking things is just much simpler. But I'm happy to do whichever, though I've not tested.

I'm currently building this in docker and on a mac, but given that this approach is much simpler, I'm pretty confident in it working out.

**Comment by Mark-Simulacrum** [comment]
I've confirmed that the latest commit seems to fix things on macOS (link-shared still errors, now explicitly rather than opaquely).

**Comment by NateLing** [comment]
@Mark-Simulacrum Is there a temporary solution? I tried to compile with the stable version and the same problem occurred. This problem has been bothering me for a week, our team cannot proceed to the next step.

**Comment by Mark-Simulacrum** [comment]
Stable and beta branches should not be affected by this bug: if you're seeing a bug there, please file a new issue with a description of how to reproduce what you're seeing and cc me.

**Comment by NateLing** [comment]
@Mark-Simulacrum sorry, my bad. i hadn't restart the terminal. now i'm using the stable version. but some api just run on nightly version.

**Comment by alexcrichton** [comment]
@bors: r+

Longer-term I do think it's best to get back to a point where we're consistently doing the same thing for LLVM across all our platforms. It's been the case for quite some time that LLVM is built with ThinLTO on Linux but nowhere else. Differing in linkage is also unfortunate across the major platforms too. It seems good though to get things working again at least...
