### PR TITLE
Fix two variable binding issues in lint let_underscore

### LINKED ISSUE #119696: let_underscore_drop should not trigger on function parameters
### Code

```Rust
#![warn(let_underscore_drop)]
fn main() {
    let _ = foo();
}

async fn from_config(_: Config) {}

async fn foo() {
    from_config(Config {
        nickname: None,
        ..Default::default()
    })
    .await;
}

#[derive(Default)]
struct Config {
    nickname: Option<Box<u8>>,
}
```

### Current output

```Shell
warning: non-binding let on a type that implements `Drop`
 --> src/main.rs:3:5
  |
3 |     let _ = foo();
  |     ^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![warn(let_underscore_drop)]
  |         ^^^^^^^^^^^^^^^^^^^
help: consider binding to an unused variable to avoid immediately dropping the value
  |
3 |     let _unused = foo();
  |         ~~~~~~~
help: consider immediately dropping the value
  |
3 |     drop(foo());
  |     ~~~~~     +

warning: non-binding let on a type that implements `Drop`
 --> src/main.rs:6:22
  |
6 | async fn from_config(_: Config) {}
  |                      ^
  |
help: consider binding to an unused variable to avoid immediately dropping the value
  |
6 | async fn from_config(_unused: Config) {}
  |                      ~~~~~~~
help: consider immediately dropping the value
  |
6 | async fn from_config(drop(_): Config) {}
  |                      +++++ +
```

### Desired output

_No response_

### Rationale and extra context

The `async fn from_config(drop(_): Config) {}` suggestion does not make sense, this will fail when applied with rustfix.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.77.0-nightly (87e143089 2024-01-07)
binary: rustc
commit-hash: 87e1430893d55001034bd76c5dbe832d80bc50c3
commit-date: 2024-01-07
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Anything else?

_No response_

### LINKED ISSUE #119697: let_underscore_drop hallunicates variable binding
### Code

```Rust
#![warn(let_underscore_drop)]
#![feature(type_alias_impl_trait)]

pub struct Foo {
    /// This type must have nontrivial drop glue
    field: String,
}

pub type Tait = impl Sized;

pub fn ice_cold(beverage: Tait) {
    // Must destructure at least one field of `Foo`
    let Foo { field } = beverage;
    // boom
    _ = field;
}


pub fn main() {}
```

### Current output

```Shell
warning: non-binding let on a type that implements `Drop`
  --> src/main.rs:15:5
   |
15 |     _ = field;
   |     ^^^^^^^^^
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![warn(let_underscore_drop)]
   |         ^^^^^^^^^^^^^^^^^^^
help: consider binding to an unused variable to avoid immediately dropping the value
   |
15 |     _unused = field;
   |     ~~~~~~~
help: consider immediately dropping the value
   |
15 |     drop(field);
   |     ~~~~~     +

warning: `drop` (bin "drop") generated 1 warning (run `cargo fix --bin "drop"` to apply 1 suggestion)
```

### Desired output

```Shell
We should suggest `let _unused = filed` since there is no `_unused` in scope.
```

### Rationale and extra context

Otherwise it will fail to cargo-fix:
```
error[E0425]: cannot find value `_unused` in this scope
  --> src/main.rs:15:5
   |
15 |     _unused = field;
   |     ^^^^^^^
   |
help: you might have meant to introduce a new binding
   |
15 |     let _unused = field;
   |     +++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0425`.
Original diagnostics will follow.

warning: `drop` (bin "drop" test) generated 1 warning (1 duplicate)
```

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.77.0-nightly (87e143089 2024-01-07)
binary: rustc
commit-hash: 87e1430893d55001034bd76c5dbe832d80bc50c3
commit-date: 2024-01-07
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #119696
Fixes #119697

### CODE REVIEW

File: compiler/rustc_lint/src/lints.rs [hunk 1]
```diff
@@ -960,10 +961,11 @@ impl AddToDiagnostic for NonBindingLetSub {
             rustc_errors::SubdiagnosticMessage,
         ) -> rustc_errors::SubdiagnosticMessage,
     {
+        let prefix = if self.default_binding_mode { "" } else { "let " };
```
Comment (Nilstrieb) [inline compiler/rustc_lint/src/lints.rs:964]: the comment on `default_binding_mode` says
>  At present, this is false only for destructuring assignment.

I don't like how that doesn't strongly imply that this truly is for destructuring assignment. This makes the code a bit harder to understand and potentially breaks in the future. I'm not sure what the nicest way to address this would be. If you agree.

This is also wrong and broken for non-trivial patterns like `(_, _) = (Droppy, Droppy)`, but oh well, those don't even lint today, so Not Your Problem. I'm gonna try fixing these missing lints myself, so I think it's fine to merge this as-is.

**Review by Noratrieb — APPROVED** [review]
If you think relying on `default_binding_mode` like this is fine, r=me. If you want to change it, then do that and I'll take another look.

File: compiler/rustc_lint/src/lints.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_lint/src/lints.rs]: update the code to use `assign_desugar`, maybe a better choice?

Comment (chenyukang) [reply compiler/rustc_lint/src/lints.rs]: This pr seems forget to update comments for `AssignDesugar`
https://github.com/chenyukang/rust/commit/8cf35643106bba09b5d6c71ceac74dc58573f371

File: tests/ui/lint/issue-119696-err-on-fn.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+// edition: 2021
```
Comment (Nilstrieb) [inline tests/ui/lint/issue-119696-err-on-fn.rs:1]: there's a let_underscore_drop directory, let's put it there

**Review by Noratrieb — APPROVED** [review]
that's nicer :)
r=me after moving the test
