### PR TITLE
Fix MaybeUninit codegen using GVN

### LINKED ISSUE #139355: Creating a nested MaybeUninit array unnecessarily calls memset
This function calls `memset`:
```rs
fn create_uninit_array() -> [[MaybeUninit<u8>; 4]; 200] {
    [[MaybeUninit::<u8>::uninit(); 4]; 200]
}
```
and this one doesn't:
```rs
fn create_uninit_array_fast() -> [MaybeUninit<u8>; 800] {
    [MaybeUninit::<u8>::uninit(); 800]
}
```
I would have expected the same assembly to be generated for both cases.

[See on Godbolt](https://godbolt.org/z/xcT7dMhvM)

### PR DESCRIPTION
**Pull request by saethlin**
This is an alternative to https://github.com/rust-lang/rust/pull/142837, based on https://github.com/rust-lang/rust/pull/146355#discussion_r2421651968.

The general approach I took here is to aggressively propagate anything that is entirely uninitialized. GVN generally takes the approach of only synthesizing small types, but we need to generate large consts to fix the codegen issue.

I also added a special case to MIR dumps for this where now an entirely uninit const is printed as `const <uninit>`, because otherwise we end up with extremely verbose dumps of the new consts.

After GVN though, we still end up with a lot of MIR that looks like this:
```
StorageLive(_1);
_1 = const <uninit>;
_2 = &raw mut _1;
```
Which will break tests/codegen-llvm/maybeuninit-rvo.rs with the naive lowering. I think the ideal fix here is to somehow omit these `_1 = const <uninit>` assignments that come directly after a StorageLive, but I'm not sure how to do that. For now at least, ignoring such assignments (even if they don't come right after a StorageLive) in codegen seems to work.

Note that since GVN is based on synthesizing a `ConstValue`  which has a defined layout, this scenario still gets deoptimized by LLVM. 
```rust
#![feature(rustc_attrs)]
#![crate_type = "lib"]
use std::mem::MaybeUninit;

#[unsafe(no_mangle)]
pub fn oof() -> [[MaybeUninit<u8>; 8]; 8] {
    #[rustc_no_mir_inline]
    pub fn inner<T: Copy>() -> [[MaybeUninit<T>; 8]; 8] {
        [[MaybeUninit::uninit(); 8]; 8]
    }

    inner()
}
```
This case can be handled correctly if enough inlining has happened, or it could be handled by post-mono GVN. Synthesizing `UnevaluatedConst` or some other special kind of const seems dubious.

### CODE REVIEW

**Comment by scottmcm** [comment]
> Note that since GVN is based on synthesizing a ConstValue which has a defined layout, this scenario still gets deoptimized by LLVM.

I think once we move transmute to being union semantics we'll have more options here, can we can rewrite those repeats to `transmute(())` even in generic MIR (hopefully).

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 1]
```diff
@@ -24,6 +24,12 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
     ) {
         match *rvalue {
             mir::Rvalue::Use(ref operand) => {
+                if let mir::Operand::Constant(const_op) = operand {
+                    let val = self.eval_mir_constant(&const_op);
+                    if val.all_bytes_uninit(self.cx.tcx()) {
+                        return;
```
Comment (scottmcm) [inline compiler/rustc_codegen_ssa/src/mir/rvalue.rs:30]: pondering: I wonder if there's any places that are intentionally writing uninit somewhere to tell LLVM that the value doesn't matter.  It might be interesting to (outside of debug) write `undef` to the place for the situations where LLVM *doesn't* do the bad behaviour of copying a constant for that (such as `*p = undef;` for `*p` being `Scalar` or `ScalarPair`).

But I don't think that would need to be in *this* PR.

File: compiler/rustc_middle/src/mir/pretty.rs [hunk 2]
```diff
@@ -1861,6 +1861,13 @@ fn pretty_print_const_value_tcx<'tcx>(
         return Ok(());
     }
 
+    // Printing [MaybeUninit<u8>::uninit(); N] or any other aggregate where all fields are uninit
+    // becomes very verbose. This special case makes the dump terse and clear.
```
Comment (scottmcm) [inline compiler/rustc_middle/src/mir/pretty.rs:1876]: :+1:

File: tests/codegen-llvm/uninit-consts.rs [hunk 3]
```diff
@@ -11,21 +11,17 @@ pub struct PartiallyUninit {
...
 // CHECK: [[UNINIT_PADDING_HUGE:@.*]] = private unnamed_addr constant [32768 x i8] c"{{.+}}", align 4
 
-// CHECK: [[FULLY_UNINIT_HUGE:@.*]] = private unnamed_addr constant [16384 x i8] undef
-
 // CHECK-LABEL: @fully_uninit
 #[no_mangle]
 pub const fn fully_uninit() -> MaybeUninit<[u8; 10]> {
     const M: MaybeUninit<[u8; 10]> = MaybeUninit::uninit();
-    // CHECK: call void @llvm.memcpy.{{.+}}(ptr align 1 %_0, ptr align 1 {{.*}}[[FULLY_UNINIT]]{{.*}}, i{{(32|64)}} 10, i1 false)
+    // CHECK: ret void
```
Comment (scottmcm) [inline tests/codegen-llvm/uninit-consts.rs]: fix: this updated test would still pass without the fix from the PR (since there was already a `ret void` in it), so you need to change the test somehow.

Perhaps something like
```suggestion
    // returning uninit doesn't need to do anything to the return place at all
    // CHECK: start:
    // CHECK-NEXT: ret void
```

File: tests/codegen-llvm/uninit-consts.rs [hunk 4]
```diff
@@ -49,6 +45,6 @@ pub const fn uninit_padding_huge() -> [(u32, u8); 4096] {
 #[no_mangle]
 pub const fn fully_uninit_huge() -> MaybeUninit<[u32; 4096]> {
     const F: MaybeUninit<[u32; 4096]> = MaybeUninit::uninit();
-    // CHECK: call void @llvm.memcpy.{{.+}}(ptr align 4 %_0, ptr align 4 {{.*}}[[FULLY_UNINIT_HUGE]]{{.*}}, i{{(32|64)}} 16384, i1 false)
+    // CHECK: ret void
```
Comment (scottmcm) [inline tests/codegen-llvm/uninit-consts.rs]: (ditto here)

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 5]
```diff
@@ -24,6 +24,12 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                    }
+                }
                 let cg_operand = self.codegen_operand(bx, operand);
                 // Crucially, we do *not* use `OperandValue::Ref` for types with
                 // `BackendRepr::Scalar | BackendRepr::ScalarPair`. This ensures we match the MIR
```
Comment (scottmcm) [inline compiler/rustc_codegen_ssa/src/mir/rvalue.rs:35]: annoyingly it won't let me comment on the actual line, but I think the FIXME on line 43 below might be updatable now?

File: compiler/rustc_codegen_ssa/src/mir/rvalue.rs [hunk 6]
```diff
@@ -24,6 +24,12 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
     ) {
         match *rvalue {
             mir::Rvalue::Use(ref operand) => {
+                if let mir::Operand::Constant(const_op) = operand {
+                    let val = self.eval_mir_constant(&const_op);
+                    if val.all_bytes_uninit(self.cx.tcx()) {
+                        return;
+                    }
+                }
                 let cg_operand = self.codegen_operand(bx, operand);
```
Comment (scottmcm) [inline compiler/rustc_codegen_ssa/src/mir/rvalue.rs:33]: Actually, would it make sense for `codegen_operand` to do the `all_bytes_uninit` check and just emit some kind of `OperandRef::uninit(ty)` as the operand?  `store i32 undef, ptr %foo` feels like it must be handled fine in LLVM...

Hmm, no, that's non-trivial isn't it, because there's nothing good to make `OperandValue::Ref` from if this isn't a Scalar or ScalarPair.  Never mind then.

**Review by scottmcm — APPROVED** [review]
r=me with the tests fixed to be able to catch regressions.  Other comments up to you.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147827/4ddbb6051271237f4192333e06b8129148995eef..177e9fcffe17b6cc6b55c688631d997df83a2f31)*

File: tests/codegen-llvm/uninit-consts.rs (hunk 4 above)
Comment (saethlin) [reply tests/codegen-llvm/uninit-consts.rs]: Done

File: tests/codegen-llvm/uninit-consts.rs (hunk 3 above)
Comment (saethlin) [reply tests/codegen-llvm/uninit-consts.rs]: Done
