### PR TITLE
Trying to address an incremental compilation issues

### LINKED ISSUE #107226: ICE: called `Option::unwrap()` on a `None` value at def_path_hash_map.rs:23:85
reporting as requested.

```rust
➜  i18n git:(develop) rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/coliny/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2022-06-14-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.60.0-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-pc-windows-gnu

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

`RUST_BACKTRACE=1`
```rust
   Compiling i18n v0.1.0 (/Users/coliny/Dev/com.qfi.health/src/rust/i18n)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:85
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::def_path_hash_to_def_id
   4: <rustc_middle::ty::context::TyCtxt>::def_path_hash_to_def_id
   5: <rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind> as rustc_middle::dep_graph::dep_node::DepNodeExt>::extract_def_id
   6: rustc_query_impl::query_callbacks::type_of::force_from_dep_node
   7: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
   8: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   9: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  11: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  12: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  13: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  14: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  15: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::infer::canonical::Canonical<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Predicate>>, core::result::Result<rustc_middle::traits::select::EvaluationResult, rustc_middle::traits::select::OverflowError>>
  16: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::evaluate_obligation, rustc_query_impl::plumbing::QueryCtxt>
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
  18: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  19: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  20: <rustc_trait_selection::traits::fulfill::FulfillProcessor>::process_trait_obligation
  21: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
  22: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor, rustc_data_structures::obligation_forest::Outcome<rustc_trait_selection::traits::fulfill::PendingPredicateObligation, rustc_infer::traits::FulfillmentErrorCode>>
  23: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  24: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error
  25: <rustc_infer::infer::InferCtxtBuilder>::enter::<core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_middle::traits::CodegenObligationError>, rustc_trait_selection::traits::codegen::codegen_fulfill_obligation::{closure#0}>
  26: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
  27: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (rustc_middle::ty::ParamEnv, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::TraitRef>), core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_middle::traits::CodegenObligationError>>::{closure#0}, core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_middle::traits::CodegenObligationError>>
  28: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (rustc_middle::ty::ParamEnv, rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::TraitRef>), core::result::Result<&rustc_middle::traits::ImplSource<()>, rustc_middle::traits::CodegenObligationError>>
  29: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::codegen_fulfill_obligation, rustc_query_impl::plumbing::QueryCtxt>
  30: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::codegen_fulfill_obligation
  31: rustc_ty_utils::instance::inner_resolve_instance
  32: rustc_ty_utils::instance::resolve_instance
  33: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorGuaranteed>>
  34: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<(rustc_span::def_id::DefId, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>)>, core::result::Result<core::option::Option<rustc_middle::ty::instance::Instance>, rustc_errors::ErrorGuaranteed>>
  35: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt>
  36: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  37: <rustc_middle::ty::instance::Instance>::resolve_opt_const_arg
  38: <rustc_middle::ty::instance::Instance>::resolve
  39: <rustc_monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  40: rustc_monomorphize::collector::collect_neighbours
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: rustc_monomorphize::collector::collect_items_rec
  49: rustc_monomorphize::collector::collect_items_rec
  50: rustc_monomorphize::collector::collect_items_rec
  51: rustc_monomorphize::collector::collect_items_rec
  52: rustc_monomorphize::collector::collect_items_rec
  53: rustc_monomorphize::collector::collect_items_rec
  54: rustc_monomorphize::collector::collect_items_rec
  55: rustc_monomorphize::collector::collect_items_rec
  56: rustc_monomorphize::collector::collect_items_rec
  57: rustc_monomorphize::collector::collect_items_rec
  58: rustc_monomorphize::collector::collect_items_rec
  59: rustc_monomorphize::collector::collect_items_rec
  60: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
  61: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>
  62: rustc_data_structures::sync::par_for_each_in::<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  63: <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}>
  64: rustc_monomorphize::collector::collect_crate_mono_items
  65: rustc_monomorphize::partitioning::collect_and_partition_mono_items
  66: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>
  67: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>>
  68: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::collect_and_partition_mono_items, rustc_query_impl::plumbing::QueryCtxt>
  69: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
  70: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  71: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  72: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  73: <rustc_interface::queries::Queries>::ongoing_codegen
  74: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  75: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  76: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on x86_64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `warp::filter::and_then::AndThenFuture<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>: core::marker::Send`
#1 [codegen_fulfill_obligation] checking if `core::future::into_future::IntoFuture` fulfills its obligations
#2 [resolve_instance] resolving instance `<tracing_futures::Instrumented<futures_util::future::future::Map<hyper::server::Server<hyper::server::tcp::AddrIncoming, hyper::service::make::MakeServiceFn<[closure@warp::server::Server<warp::filter::or::Or<warp::filter::or::Or<warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:23:14: 23:21]>, warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:25:76: 25:78]>>, warp::filter::and_then::AndThen<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>>>::bind_ephemeral<std::net::addr::SocketAddr>::{closure#1}::{closure#0}]>>, [closure@warp::server::Server<warp::filter::or::Or<warp::filter::or::Or<warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:23:14: 23:21]>, warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:25:76: 25:78]>>, warp::filter::and_then::AndThen<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>>>::bind_ephemeral<std::net::addr::SocketAddr>::{closure#0}]>> as core::future::into_future::IntoFuture>::into_future`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```
`RUST_BACKTRACE=full`:
```rust
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:85
stack backtrace:
   0:        0x109aa45c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7d80e14dd19335c9
   1:        0x109afc68b - core::fmt::write::h1709d0255080e28a
   2:        0x109a96fe8 - std::io::Write::write_fmt::hecc56b5639d319e7
   3:        0x109aa789d - std::panicking::default_hook::{{closure}}::had4d1cd22a173020
   4:        0x109aa75ee - std::panicking::default_hook::h42aa124509888735
   5:        0x11221c73a - rustc_driver[b232a614d5c482d6]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x109aa7f0b - std::panicking::rust_panic_with_hook::h2b231e816574a23a
   7:        0x109aa7d4a - std::panicking::begin_panic_handler::{{closure}}::h9da8d88b7a4c9d5e
   8:        0x109aa4a47 - std::sys_common::backtrace::__rust_end_short_backtrace::h10dbf1377dfaf877
   9:        0x109aa7a5a - _rust_begin_unwind
  10:        0x109b27943 - core::panicking::panic_fmt::hde1544b10dc8b4d3
  11:        0x109b27827 - core::panicking::panic::h73607a325a777129
  12:        0x115f717d9 - <rustc_metadata[6e15ed64399eb477]::creader::CStore as rustc_session[3f62dfdbb5354e46]::cstore::CrateStore>::def_path_hash_to_def_id
  13:        0x11675c8fe - <rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x1166ce09e - <rustc_query_system[923812efe1d06df6]::dep_graph::dep_node::DepNode<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind> as rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  15:        0x115c09f7a - rustc_query_impl[1fb0f992e528a50]::query_callbacks::type_of::force_from_dep_node
  16:        0x11673ef9c - <rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt as rustc_query_system[923812efe1d06df6]::dep_graph::DepContext>::try_force_from_dep_node
  17:        0x115ad77db - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  18:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  19:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  20:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  21:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  22:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  23:        0x115ad7798 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  24:        0x1158ebac7 - rustc_query_system[923812efe1d06df6]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt, rustc_middle[77b05d97adc105c3]::infer::canonical::Canonical<rustc_middle[77b05d97adc105c3]::ty::ParamEnvAnd<rustc_middle[77b05d97adc105c3]::ty::Predicate>>, core[ccfd6f2964525339]::result::Result<rustc_middle[77b05d97adc105c3]::traits::select::EvaluationResult, rustc_middle[77b05d97adc105c3]::traits::select::OverflowError>>
  25:        0x115939334 - rustc_query_system[923812efe1d06df6]::query::plumbing::get_query::<rustc_query_impl[1fb0f992e528a50]::queries::evaluate_obligation, rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  26:        0x115c07339 - <rustc_query_impl[1fb0f992e528a50]::Queries as rustc_middle[77b05d97adc105c3]::ty::query::QueryEngine>::evaluate_obligation
  27:        0x116453546 - <rustc_infer[daf5aaa74dbe2ea7]::infer::InferCtxt as rustc_trait_selection[5b0b3e5dfe8e4329]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  28:        0x116453653 - <rustc_infer[daf5aaa74dbe2ea7]::infer::InferCtxt as rustc_trait_selection[5b0b3e5dfe8e4329]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  29:        0x1164e456d - <rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  30:        0x1164e3f62 - <rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::FulfillProcessor as rustc_data_structures[9d9aca487cd3f5bb]::obligation_forest::ObligationProcessor>::process_obligation
  31:        0x116560602 - <rustc_data_structures[9d9aca487cd3f5bb]::obligation_forest::ObligationForest<rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::FulfillProcessor, rustc_data_structures[9d9aca487cd3f5bb]::obligation_forest::Outcome<rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::PendingPredicateObligation, rustc_infer[daf5aaa74dbe2ea7]::traits::FulfillmentErrorCode>>
  32:        0x1164dcfad - <rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::FulfillmentContext as rustc_infer[daf5aaa74dbe2ea7]::traits::engine::TraitEngine>::select_where_possible
  33:        0x1164dce80 - <rustc_trait_selection[5b0b3e5dfe8e4329]::traits::fulfill::FulfillmentContext as rustc_infer[daf5aaa74dbe2ea7]::traits::engine::TraitEngine>::select_all_or_error
  34:        0x11641d1f5 - <rustc_infer[daf5aaa74dbe2ea7]::infer::InferCtxtBuilder>::enter::<core[ccfd6f2964525339]::result::Result<&rustc_middle[77b05d97adc105c3]::traits::ImplSource<()>, rustc_middle[77b05d97adc105c3]::traits::CodegenObligationError>, rustc_trait_selection[5b0b3e5dfe8e4329]::traits::codegen::codegen_fulfill_obligation::{closure#0}>
  35:        0x116527bf1 - rustc_trait_selection[5b0b3e5dfe8e4329]::traits::codegen::codegen_fulfill_obligation
  36:        0x1159a58d4 - <rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind as rustc_query_system[923812efe1d06df6]::dep_graph::DepKind>::with_deps::<<rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt, (rustc_middle[77b05d97adc105c3]::ty::ParamEnv, rustc_middle[77b05d97adc105c3]::ty::sty::Binder<rustc_middle[77b05d97adc105c3]::ty::sty::TraitRef>), core[ccfd6f2964525339]::result::Result<&rustc_middle[77b05d97adc105c3]::traits::ImplSource<()>, rustc_middle[77b05d97adc105c3]::traits::CodegenObligationError>>::{closure#0}, core[ccfd6f2964525339]::result::Result<&rustc_middle[77b05d97adc105c3]::traits::ImplSource<()>, rustc_middle[77b05d97adc105c3]::traits::CodegenObligationError>>
  37:        0x115b18742 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt, (rustc_middle[77b05d97adc105c3]::ty::ParamEnv, rustc_middle[77b05d97adc105c3]::ty::sty::Binder<rustc_middle[77b05d97adc105c3]::ty::sty::TraitRef>), core[ccfd6f2964525339]::result::Result<&rustc_middle[77b05d97adc105c3]::traits::ImplSource<()>, rustc_middle[77b05d97adc105c3]::traits::CodegenObligationError>>
  38:        0x115950327 - rustc_query_system[923812efe1d06df6]::query::plumbing::get_query::<rustc_query_impl[1fb0f992e528a50]::queries::codegen_fulfill_obligation, rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  39:        0x115c06270 - <rustc_query_impl[1fb0f992e528a50]::Queries as rustc_middle[77b05d97adc105c3]::ty::query::QueryEngine>::codegen_fulfill_obligation
  40:        0x114f87689 - rustc_ty_utils[fa5a1d9038bce425]::instance::inner_resolve_instance
  41:        0x114f86125 - rustc_ty_utils[fa5a1d9038bce425]::instance::resolve_instance
  42:        0x1159a4138 - <rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind as rustc_query_system[923812efe1d06df6]::dep_graph::DepKind>::with_deps::<<rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt, rustc_middle[77b05d97adc105c3]::ty::ParamEnvAnd<(rustc_span[dadb10719d06531]::def_id::DefId, &rustc_middle[77b05d97adc105c3]::ty::list::List<rustc_middle[77b05d97adc105c3]::ty::subst::GenericArg>)>, core[ccfd6f2964525339]::result::Result<core[ccfd6f2964525339]::option::Option<rustc_middle[77b05d97adc105c3]::ty::instance::Instance>, rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>::{closure#0}, core[ccfd6f2964525339]::result::Result<core[ccfd6f2964525339]::option::Option<rustc_middle[77b05d97adc105c3]::ty::instance::Instance>, rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  43:        0x115addb80 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt, rustc_middle[77b05d97adc105c3]::ty::ParamEnvAnd<(rustc_span[dadb10719d06531]::def_id::DefId, &rustc_middle[77b05d97adc105c3]::ty::list::List<rustc_middle[77b05d97adc105c3]::ty::subst::GenericArg>)>, core[ccfd6f2964525339]::result::Result<core[ccfd6f2964525339]::option::Option<rustc_middle[77b05d97adc105c3]::ty::instance::Instance>, rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  44:        0x115931c92 - rustc_query_system[923812efe1d06df6]::query::plumbing::get_query::<rustc_query_impl[1fb0f992e528a50]::queries::resolve_instance, rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  45:        0x115c07834 - <rustc_query_impl[1fb0f992e528a50]::Queries as rustc_middle[77b05d97adc105c3]::ty::query::QueryEngine>::resolve_instance
  46:        0x116855d10 - <rustc_middle[77b05d97adc105c3]::ty::instance::Instance>::resolve_opt_const_arg
  47:        0x1168554d6 - <rustc_middle[77b05d97adc105c3]::ty::instance::Instance>::resolve
  48:        0x1148970e3 - <rustc_monomorphize[a406f6b04befd1b4]::collector::MirNeighborCollector as rustc_middle[77b05d97adc105c3]::mir::visit::Visitor>::visit_terminator
  49:        0x11489f0c5 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_neighbours
  50:        0x11489c30d - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  51:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  52:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  53:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  54:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  55:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  56:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  57:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  58:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  59:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  60:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  61:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  62:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  63:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  64:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  65:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  66:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  67:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  68:        0x11489c9a6 - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_items_rec
  69:        0x1148ad534 - <core[ccfd6f2964525339]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9d9aca487cd3f5bb]::sync::par_for_each_in<alloc[a79849253dbb7549]::vec::Vec<rustc_middle[77b05d97adc105c3]::mir::mono::MonoItem>, rustc_monomorphize[a406f6b04befd1b4]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> as core[ccfd6f2964525339]::ops::function::FnOnce<()>>::call_once
  70:        0x1148c4150 - std[2c17b0a3fe477be8]::panicking::try::<(), core[ccfd6f2964525339]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9d9aca487cd3f5bb]::sync::par_for_each_in<alloc[a79849253dbb7549]::vec::Vec<rustc_middle[77b05d97adc105c3]::mir::mono::MonoItem>, rustc_monomorphize[a406f6b04befd1b4]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>>
  71:        0x1148c657f - rustc_data_structures[9d9aca487cd3f5bb]::sync::par_for_each_in::<alloc[a79849253dbb7549]::vec::Vec<rustc_middle[77b05d97adc105c3]::mir::mono::MonoItem>, rustc_monomorphize[a406f6b04befd1b4]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  72:        0x1148b28aa - <rustc_session[3f62dfdbb5354e46]::session::Session>::time::<(), rustc_monomorphize[a406f6b04befd1b4]::collector::collect_crate_mono_items::{closure#1}>
  73:        0x11489976a - rustc_monomorphize[a406f6b04befd1b4]::collector::collect_crate_mono_items
  74:        0x1148a4022 - rustc_monomorphize[a406f6b04befd1b4]::partitioning::collect_and_partition_mono_items
  75:        0x115b2d4d8 - <rustc_query_system[923812efe1d06df6]::dep_graph::graph::DepGraph<rustc_middle[77b05d97adc105c3]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[77b05d97adc105c3]::ty::context::TyCtxt, (), (&std[2c17b0a3fe477be8]::collections::hash::set::HashSet<rustc_span[dadb10719d06531]::def_id::DefId, core[ccfd6f2964525339]::hash::BuildHasherDefault<rustc_hash[e8dfd47c01bdec5e]::FxHasher>>, &[rustc_middle[77b05d97adc105c3]::mir::mono::CodegenUnit])>
  76:        0x1158c260c - rustc_query_system[923812efe1d06df6]::query::plumbing::try_execute_query::<rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt, rustc_query_system[923812efe1d06df6]::query::caches::DefaultCache<(), (&std[2c17b0a3fe477be8]::collections::hash::set::HashSet<rustc_span[dadb10719d06531]::def_id::DefId, core[ccfd6f2964525339]::hash::BuildHasherDefault<rustc_hash[e8dfd47c01bdec5e]::FxHasher>>, &[rustc_middle[77b05d97adc105c3]::mir::mono::CodegenUnit])>>
  77:        0x115956d1f - rustc_query_system[923812efe1d06df6]::query::plumbing::get_query::<rustc_query_impl[1fb0f992e528a50]::queries::collect_and_partition_mono_items, rustc_query_impl[1fb0f992e528a50]::plumbing::QueryCtxt>
  78:        0x115c07017 - <rustc_query_impl[1fb0f992e528a50]::Queries as rustc_middle[77b05d97adc105c3]::ty::query::QueryEngine>::collect_and_partition_mono_items
  79:        0x1123f2adc - <rustc_codegen_llvm[72a00bab46809736]::LlvmCodegenBackend as rustc_codegen_ssa[a7c95725fcbf9efd]::traits::backend::CodegenBackend>::codegen_crate
  80:        0x1122c5dc2 - <rustc_session[3f62dfdbb5354e46]::session::Session>::time::<alloc[a79849253dbb7549]::boxed::Box<dyn core[ccfd6f2964525339]::any::Any>, rustc_interface[f8b8cf4f770498c1]::passes::start_codegen::{closure#0}>
  81:        0x1122c3c7c - <rustc_interface[f8b8cf4f770498c1]::passes::QueryContext>::enter::<<rustc_interface[f8b8cf4f770498c1]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[ccfd6f2964525339]::result::Result<alloc[a79849253dbb7549]::boxed::Box<dyn core[ccfd6f2964525339]::any::Any>, rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  82:        0x11233e6f9 - <rustc_interface[f8b8cf4f770498c1]::queries::Queries>::ongoing_codegen
  83:        0x1121ad424 - <rustc_interface[f8b8cf4f770498c1]::interface::Compiler>::enter::<rustc_driver[b232a614d5c482d6]::run_compiler::{closure#1}::{closure#2}, core[ccfd6f2964525339]::result::Result<core[ccfd6f2964525339]::option::Option<rustc_interface[f8b8cf4f770498c1]::queries::Linker>, rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  84:        0x112202398 - rustc_span[dadb10719d06531]::with_source_map::<core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>, rustc_interface[f8b8cf4f770498c1]::interface::create_compiler_and_run<core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>, rustc_driver[b232a614d5c482d6]::run_compiler::{closure#1}>::{closure#1}>
  85:        0x1121ae039 - <scoped_tls[48db78d854efead3]::ScopedKey<rustc_span[dadb10719d06531]::SessionGlobals>>::set::<rustc_interface[f8b8cf4f770498c1]::interface::run_compiler<core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>, rustc_driver[b232a614d5c482d6]::run_compiler::{closure#1}>::{closure#0}, core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  86:        0x1121d0b99 - std[2c17b0a3fe477be8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f8b8cf4f770498c1]::util::run_in_thread_pool_with_globals<rustc_interface[f8b8cf4f770498c1]::interface::run_compiler<core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>, rustc_driver[b232a614d5c482d6]::run_compiler::{closure#1}>::{closure#0}, core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>::{closure#0}, core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>
  87:        0x1121d13c1 - <<std[2c17b0a3fe477be8]::thread::Builder>::spawn_unchecked_<rustc_interface[f8b8cf4f770498c1]::util::run_in_thread_pool_with_globals<rustc_interface[f8b8cf4f770498c1]::interface::run_compiler<core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>, rustc_driver[b232a614d5c482d6]::run_compiler::{closure#1}>::{closure#0}, core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>::{closure#0}, core[ccfd6f2964525339]::result::Result<(), rustc_errors[7d8f39c483a9ccdf]::ErrorGuaranteed>>::{closure#1} as core[ccfd6f2964525339]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  88:        0x109ab1457 - std::sys::unix::thread::Thread::new::thread_start::h76e6c1c658a39a87
  89:     0x7ff807362259 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on x86_64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `warp::filter::and_then::AndThenFuture<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>: core::marker::Send`
#1 [codegen_fulfill_obligation] checking if `core::future::into_future::IntoFuture` fulfills its obligations
#2 [resolve_instance] resolving instance `<tracing_futures::Instrumented<futures_util::future::future::Map<hyper::server::Server<hyper::server::tcp::AddrIncoming, hyper::service::make::MakeServiceFn<[closure@warp::server::Server<warp::filter::or::Or<warp::filter::or::Or<warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:23:14: 23:21]>, warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:25:76: 25:78]>>, warp::filter::and_then::AndThen<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>>>::bind_ephemeral<std::net::addr::SocketAddr>::{closure#1}::{closure#0}]>>, [closure@warp::server::Server<warp::filter::or::Or<warp::filter::or::Or<warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:23:14: 23:21]>, warp::filter::map::Map<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::get::{closure#0}]>::{closure#0}]>, warp::filters::path::Exact<warp::filters::path::internal::Opaque<&str>>>, [closure@i18n/src/web.rs:25:76: 25:78]>>, warp::filter::and_then::AndThen<warp::filter::and::And<warp::filter::and::And<warp::filter::FilterFn<[closure@warp::filters::method::method_is<[closure@warp::filters::method::post::{closure#0}]>::{closure#0}]>, warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaque<web::start::{closure#0}::__StaticPath>>>, warp::filter::FilterFn<[closure@warp::filters::path::end::{closure#0}]>>>, warp::filters::multipart::FormOptions>, fn(warp::filters::multipart::FormData) -> impl core::future::future::Future<Output = core::result::Result<impl warp::reply::Reply, warp::reject::Rejection>> {web::handle_upload}>>>::bind_ephemeral<std::net::addr::SocketAddr>::{closure#0}]>> as core::future::into_future::IntoFuture>::into_future`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

### LINKED ISSUE #125367: ICE in `uv` when doing a rebuild after code change
### Code

Unfortunately this is nowhere near a minimal example, but it was a tricky one to figure out how to reliably reproduce. Here are the steps:

```
$ git clone git@github.com:astral-sh/uv uv-ice
$ cd uv-ice
$ git checkout 44fe0f6749249a223646baa87f9d7ce40b2e40f3
$ cargo b -p uv
$ git checkout eac8221718aaa3444d5bfc8099f4bdb0c3ef2f97
$ cargo b -p uv
```

### Meta

```
$ rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)
$ cargo --version
cargo 1.78.0 (54d8815d0 2024-03-26)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x70e9ff589892 - std::backtrace_rs::backtrace::libunwind::trace::he4ee80166a02c846
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x70e9ff589892 - std::backtrace_rs::backtrace::trace_unsynchronized::h476faccf57e88641
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x70e9ff589892 - std::sys_common::backtrace::_print_fmt::h430c922a77e7a59c
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x70e9ff589892 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x70e9ff5daa6c - core::fmt::rt::Argument::fmt::hf3df69369399bfa9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/rt.rs:142:9
   5:     0x70e9ff5daa6c - core::fmt::write::hd9a8d7d029f9ea1a
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/mod.rs:1153:17
   6:     0x70e9ff57e78f - std::io::Write::write_fmt::h0e1226b2b8d973fe
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/io/mod.rs:1843:15
   7:     0x70e9ff589664 - std::sys_common::backtrace::_print::hd2df4a083f6e69b8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x70e9ff589664 - std::sys_common::backtrace::print::he907f6ad7eee41cb
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x70e9ff58c35b - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
  10:     0x70e9ff58c0b3 - std::panicking::default_hook::h25ba2457dea68e65
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:292:9
  11:     0x70e9fc22845d - std[e4dfbc2c3f4b09f1]::panicking::update_hook::<alloc[1adba907b9db1888]::boxed::Box<rustc_driver_impl[24a943716c49befe]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x70e9ff58cac0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h022ca2c0d8c21c9e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  13:     0x70e9ff58cac0 - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
  14:     0x70e9ff58c7c9 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:649:13
  15:     0x70e9ff589d66 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x70e9ff58c534 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
  17:     0x70e9ff5d6f85 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
  18:     0x70e9ff5d7043 - core::panicking::panic::h8ddd58dc57c2dc00
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
  19:     0x70e9ff5d6d16 - core::option::unwrap_failed::hf59153bb1e2fc334
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1985:5
  20:     0x70e9fd4f7b11 - <rustc_query_system[475239fef39bf53f]::dep_graph::dep_node::DepNode as rustc_middle[fda44fdb505d3e7f]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  21:     0x70e9fe046e60 - rustc_query_impl[e4152ad88c3d6c78]::plumbing::force_from_dep_node::<rustc_query_impl[e4152ad88c3d6c78]::DynamicConfig<rustc_query_system[475239fef39bf53f]::query::caches::DefIdCache<rustc_middle[fda44fdb505d3e7f]::query::erase::Erased<[u8; 8usize]>>, false, false, false>>
  22:     0x70e9fe046d2d - <rustc_query_impl[e4152ad88c3d6c78]::plumbing::query_callback<rustc_query_impl[e4152ad88c3d6c78]::query_impl::type_of::QueryType>::{closure#0} as core[836963c7c1decc11]::ops::function::FnOnce<(rustc_middle[fda44fdb505d3e7f]::ty::context::TyCtxt, rustc_query_system[475239fef39bf53f]::dep_graph::dep_node::DepNode)>>::call_once
  23:     0x70e9fd429055 - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  24:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  25:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  26:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  27:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  28:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  29:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  30:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  31:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  32:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  33:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  34:     0x70e9fd428fbd - <rustc_query_system[475239fef39bf53f]::dep_graph::graph::DepGraphData<rustc_middle[fda44fdb505d3e7f]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt>
  35:     0x70e9fd598c90 - rustc_query_system[475239fef39bf53f]::query::plumbing::try_execute_query::<rustc_query_impl[e4152ad88c3d6c78]::DynamicConfig<rustc_query_system[475239fef39bf53f]::query::caches::DefaultCache<rustc_middle[fda44fdb505d3e7f]::ty::ParamEnvAnd<(rustc_middle[fda44fdb505d3e7f]::ty::instance::Instance, &rustc_middle[fda44fdb505d3e7f]::ty::list::List<rustc_middle[fda44fdb505d3e7f]::ty::Ty>)>, rustc_middle[fda44fdb505d3e7f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[e4152ad88c3d6c78]::plumbing::QueryCtxt, true>
  36:     0x70e9fd597aea - rustc_query_impl[e4152ad88c3d6c78]::query_impl::fn_abi_of_instance::get_query_incr::__rust_end_short_backtrace
  37:     0x70e9faeed3d3 - <rustc_codegen_llvm[f0cd90d441c72ba4]::context::CodegenCx as rustc_codegen_ssa[efaff1afc8f87053]::traits::declare::PreDefineMethods>::predefine_fn
  38:     0x70e9fe072d22 - rustc_codegen_llvm[f0cd90d441c72ba4]::base::compile_codegen_unit::module_codegen
  39:     0x70e9fe06f57d - <rustc_codegen_llvm[f0cd90d441c72ba4]::LlvmCodegenBackend as rustc_codegen_ssa[efaff1afc8f87053]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  40:     0x70e9fe2f8a57 - <rustc_codegen_llvm[f0cd90d441c72ba4]::LlvmCodegenBackend as rustc_codegen_ssa[efaff1afc8f87053]::traits::backend::CodegenBackend>::codegen_crate
  41:     0x70e9fe1b418f - rustc_interface[ba2b6dc4c96cb491]::passes::start_codegen
  42:     0x70e9fe1b39c8 - <rustc_interface[ba2b6dc4c96cb491]::queries::Queries>::codegen_and_build_linker
  43:     0x70e9fdffc86f - rustc_interface[ba2b6dc4c96cb491]::interface::run_compiler::<core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>, rustc_driver_impl[24a943716c49befe]::run_compiler::{closure#0}>::{closure#0}
  44:     0x70e9fe33eb6e - std[e4dfbc2c3f4b09f1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ba2b6dc4c96cb491]::util::run_in_thread_with_globals<rustc_interface[ba2b6dc4c96cb491]::interface::run_compiler<core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>, rustc_driver_impl[24a943716c49befe]::run_compiler::{closure#0}>::{closure#0}, core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>>
  45:     0x70e9fe33e9ca - <<std[e4dfbc2c3f4b09f1]::thread::Builder>::spawn_unchecked_<rustc_interface[ba2b6dc4c96cb491]::util::run_in_thread_with_globals<rustc_interface[ba2b6dc4c96cb491]::interface::run_compiler<core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>, rustc_driver_impl[24a943716c49befe]::run_compiler::{closure#0}>::{closure#0}, core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[836963c7c1decc11]::result::Result<(), rustc_span[a4517f2b2e65298c]::ErrorGuaranteed>>::{closure#1} as core[836963c7c1decc11]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x70e9ff596145 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h19b9e642d37e7272
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
  47:     0x70e9ff596145 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h97265befc434d3ae
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
  48:     0x70e9ff596145 - std::sys::pal::unix::thread::Thread::new::thread_start::h420dad5cf01a9f35
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/thread.rs:108:17
  49:     0x70e9f92aa1cf - <unknown>
  50:     0x70e9f932b6ec - <unknown>
  51:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0 (9b00956e5 2024-04-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `core::ptr::drop_in_place::<pubgrub::internal::partial_solution::PartialSolution<uv_resolver::dependency_provider::UvDependencyProvider>> - shim(Some(pubgrub::internal::partial_solution::PartialSolution<uv_resolver::dependency_provider::UvDependencyProvider>))`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 TraitSelect(55b8bee41a82e7c2-3a3e4d970e182545)
#1 TraitSelect(fa461f6d08d7dac4-e3befb3fa9cf797c)
#2 TraitSelect(4c00df648c347e83-3928b82f8f6e1ebf)
#3 TraitSelect(87bbbd51f6c2b1e7-5dac3f95440f7b31)
#4 TraitSelect(dfca409466fe9d60-c26dddb72c38ee7c)
#5 TraitSelect(84a9bc21b8ec357c-99ce74e5b76965fa)
#6 TraitSelect(960ad83381f93f02-7a9702a22a3f1b1d)
#7 TraitSelect(a87950bb1d902f9c-16fc745dd9e5eec5)
#8 TraitSelect(46412be99ebee7ac-293a8bf0f6e155a9)
#9 evaluate_obligation(ac0d9b43f463712d-cff58f98bac66ee0)
#10 is_unpin_raw(4c7531628bad62fa-664363cdb9b0d317)
#11 fn_abi_of_instance(ce984a7457c3d0f5-31b85a4f0be94126)
end of try_mark_green dep node stack
error: could not compile `uv` (bin "uv")
```

This also happens with current nightly too:

```
$ rustc +nightly --version
rustc 1.80.0-nightly (b92758a9a 2024-05-20)
$ cargo +nightly --version
cargo 1.80.0-nightly (0de7f2ec6 2024-05-17)
```

And here's the error from nightly:

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x75c590e8e7f5 - std::backtrace_rs::backtrace::libunwind::trace::h5b560bab72e6154b
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x75c590e8e7f5 - std::backtrace_rs::backtrace::trace_unsynchronized::h4ee8ec99b43d8706
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x75c590e8e7f5 - std::sys_common::backtrace::_print_fmt::h6e8289aafa4fb13e
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x75c590e8e7f5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed32d0ff2aa0fdf1
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x75c590edd91b - core::fmt::rt::Argument::fmt::hca3a538408b6d3ca
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/core/src/fmt/rt.rs:165:63
   5:     0x75c590edd91b - core::fmt::write::h0c46818975380aad
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/core/src/fmt/mod.rs:1169:21
   6:     0x75c590e8357f - std::io::Write::write_fmt::h5ea3db9efd501baa
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/io/mod.rs:1835:15
   7:     0x75c590e8e5ce - std::sys_common::backtrace::_print::h27ff758d37d9e119
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x75c590e8e5ce - std::sys_common::backtrace::print::hafc6b0d8efbd24ba
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x75c590e90fc9 - std::panicking::default_hook::{{closure}}::ha573ac73171c717b
  10:     0x75c590e90d0d - std::panicking::default_hook::h8ed95b009f156527
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/panicking.rs:298:9
  11:     0x75c58d8e5cf0 - std[8dfc48a2846f20c1]::panicking::update_hook::<alloc[9143b4602d1c6346]::boxed::Box<rustc_driver_impl[475ad1987d1f8ff4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x75c590e916fb - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h462bfb4e4b1a66a0
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/alloc/src/boxed.rs:2036:9
  13:     0x75c590e916fb - std::panicking::rust_panic_with_hook::h086afbf37fa35871
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/panicking.rs:799:13
  14:     0x75c590e9143b - std::panicking::begin_panic_handler::{{closure}}::ha322428a7efae35f
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/panicking.rs:656:13
  15:     0x75c590e8ecb9 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc043f4d06966d4a
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x75c590e911a7 - rust_begin_unwind
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/panicking.rs:652:5
  17:     0x75c590ed9ee3 - core::panicking::panic_fmt::h6d75522ebd7efdf2
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/core/src/panicking.rs:72:14
  18:     0x75c590ed9f8c - core::panicking::panic::h6eb78686f8ac2d4f
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/core/src/panicking.rs:146:5
  19:     0x75c590ed9c69 - core::option::unwrap_failed::h034406070afbd7bc
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/core/src/option.rs:1984:5
  20:     0x75c58ecc4339 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::dep_node::DepNode as rustc_middle[2f8362f7e89cbd68]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  21:     0x75c58f8296e0 - rustc_query_impl[8c69df15749cef02]::plumbing::force_from_dep_node::<rustc_query_impl[8c69df15749cef02]::DynamicConfig<rustc_query_system[6d97f4d71951f3fa]::query::caches::DefIdCache<rustc_middle[2f8362f7e89cbd68]::query::erase::Erased<[u8; 8usize]>>, false, false, false>>
  22:     0x75c58f8295ad - <rustc_query_impl[8c69df15749cef02]::plumbing::query_callback<rustc_query_impl[8c69df15749cef02]::query_impl::type_of::QueryType>::{closure#0} as core[fcbeababeaec86fe]::ops::function::FnOnce<(rustc_middle[2f8362f7e89cbd68]::ty::context::TyCtxt, rustc_query_system[6d97f4d71951f3fa]::dep_graph::dep_node::DepNode)>>::call_once
  23:     0x75c58ec2b222 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  24:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  25:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  26:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  27:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  28:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  29:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  30:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  31:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  32:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  33:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  34:     0x75c58ec2b199 - <rustc_query_system[6d97f4d71951f3fa]::dep_graph::graph::DepGraphData<rustc_middle[2f8362f7e89cbd68]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt>
  35:     0x75c58f0d6b74 - rustc_query_system[6d97f4d71951f3fa]::query::plumbing::try_execute_query::<rustc_query_impl[8c69df15749cef02]::DynamicConfig<rustc_query_system[6d97f4d71951f3fa]::query::caches::DefaultCache<rustc_middle[2f8362f7e89cbd68]::ty::ParamEnvAnd<(rustc_middle[2f8362f7e89cbd68]::ty::instance::Instance, &rustc_middle[2f8362f7e89cbd68]::ty::list::RawList<(), rustc_middle[2f8362f7e89cbd68]::ty::Ty>)>, rustc_middle[2f8362f7e89cbd68]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[8c69df15749cef02]::plumbing::QueryCtxt, true>
  36:     0x75c58f0d58da - rustc_query_impl[8c69df15749cef02]::query_impl::fn_abi_of_instance::get_query_incr::__rust_end_short_backtrace
  37:     0x75c58c048bb9 - <rustc_codegen_llvm[e7e620d8e1cab7f0]::context::CodegenCx as rustc_codegen_ssa[5a60f71214b3522a]::traits::declare::PreDefineMethods>::predefine_fn
  38:     0x75c58f846127 - rustc_codegen_llvm[e7e620d8e1cab7f0]::base::compile_codegen_unit::module_codegen
  39:     0x75c58f842786 - <rustc_codegen_llvm[e7e620d8e1cab7f0]::LlvmCodegenBackend as rustc_codegen_ssa[5a60f71214b3522a]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  40:     0x75c58fb51b9d - rustc_codegen_ssa[5a60f71214b3522a]::base::codegen_crate::<rustc_codegen_llvm[e7e620d8e1cab7f0]::LlvmCodegenBackend>
  41:     0x75c58f9d750c - <rustc_codegen_llvm[e7e620d8e1cab7f0]::LlvmCodegenBackend as rustc_codegen_ssa[5a60f71214b3522a]::traits::backend::CodegenBackend>::codegen_crate
  42:     0x75c58f9d6e9f - rustc_interface[a8c97089be6b2131]::passes::start_codegen
  43:     0x75c58f9d651a - <rustc_interface[a8c97089be6b2131]::queries::Queries>::codegen_and_build_linker
  44:     0x75c58f7d88ae - rustc_interface[a8c97089be6b2131]::interface::run_compiler::<core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>, rustc_driver_impl[475ad1987d1f8ff4]::run_compiler::{closure#0}>::{closure#1}
  45:     0x75c58f7c47c9 - std[8dfc48a2846f20c1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a8c97089be6b2131]::util::run_in_thread_with_globals<rustc_interface[a8c97089be6b2131]::util::run_in_thread_pool_with_globals<rustc_interface[a8c97089be6b2131]::interface::run_compiler<core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>, rustc_driver_impl[475ad1987d1f8ff4]::run_compiler::{closure#0}>::{closure#1}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>::{closure#0}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>
  46:     0x75c58f7c4576 - <<std[8dfc48a2846f20c1]::thread::Builder>::spawn_unchecked_<rustc_interface[a8c97089be6b2131]::util::run_in_thread_with_globals<rustc_interface[a8c97089be6b2131]::util::run_in_thread_pool_with_globals<rustc_interface[a8c97089be6b2131]::interface::run_compiler<core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>, rustc_driver_impl[475ad1987d1f8ff4]::run_compiler::{closure#0}>::{closure#1}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>::{closure#0}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fcbeababeaec86fe]::result::Result<(), rustc_span[9025529b6308a21f]::ErrorGuaranteed>>::{closure#2} as core[fcbeababeaec86fe]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:     0x75c590e9b4db - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h374c54d7ba58fd8d
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/alloc/src/boxed.rs:2022:9
  48:     0x75c590e9b4db - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h55df67e9d227fa0c
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/alloc/src/boxed.rs:2022:9
  49:     0x75c590e9b4db - std::sys::pal::unix::thread::Thread::new::thread_start::hc81f9fd5796eb668
                               at /rustc/b92758a9aef1cef7b79e2b72c3d8ba113e547f89/library/std/src/sys/pal/unix/thread.rs:108:17
  50:     0x75c58a6aa1cf - <unknown>
  51:     0x75c58a72b6ec - <unknown>
  52:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/andrew/astral/uv-ice/rustc-ice-2024-05-21T14_45_20-3821143.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `core::ptr::drop_in_place::<pubgrub::internal::partial_solution::PartialSolution<uv_resolver::dependency_provider::UvDependencyProvider>> - shim(Some(pubgrub::internal::partial_solution::PartialSolution<uv_resolver::dependency_provider::UvDependencyProvider>))`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 TraitSelect(b2ffe6aa4d6aa869-fcda8a0c413d1f76)
#1 TraitSelect(63263e15d71e08e3-206c3741085b77d3)
#2 TraitSelect(6a1af11da2f0e187-ff8aaf5459647263)
#3 TraitSelect(70396034be467119-c209d1ef56e52b1b)
#4 TraitSelect(3d32eb9629f97d20-d2caf3eaeedb71d7)
#5 TraitSelect(a67e54cc5c94f375-6312aa96b0e30db)
#6 TraitSelect(5d74d97952e2192c-ed1bafafe8c755d3)
#7 TraitSelect(362c3a049bbeab34-e4ac4a3efd7d86ac)
#8 TraitSelect(4f2c17975a95f7e-ebc2abbb1eb7d60e)
#9 evaluate_obligation(cc97e22fafe75b69-cd605ca39378ed2e)
#10 is_unpin_raw(4e8850f6268054bc-5f22f25f70f74138)
#11 fn_abi_of_instance(b7fc7b91e6594d2a-8133696373d5192b)
end of try_mark_green dep node stack
error: could not compile `uv` (bin "uv")
```

Unfortunately it's hard to say which version of Rust introduced this error since `uv` tracks the latest stable version of Rust.

One possible way to narrow this down is that not all changes to the code seem to provoke the ICE. For example, if you checkout `223980e4bc22ec17b4d79b8e5f3f00b38c144c1a`, do `cargo b -p uv` and then checkout `44fe0f6749249a223646baa87f9d7ce40b2e40f3` and build that too, then it works fine. So I wonder if there is something about https://github.com/astral-sh/uv/commit/eac8221718aaa3444d5bfc8099f4bdb0c3ef2f97 that is provoking the problem.

### LINKED ISSUE #127794: ICE: "Failed to extract DefId" in macro `diesel::table`
The error cleared up when I cleared out /target/ and I couldn't make a minimal example, but I thought I'd post the panic message anyway in case its helpful.

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
j@Js-MacBook-Pro landeed % cargo check
   Compiling landeed v0.1.0 (/Users/j/landeed/rust_api/landeed)
thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", def_kind, PackedFingerprint(Fingerprint(15298384670303234344, 1108908725942386211)))
stack backtrace:
   0:        0x101665750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
   2:        0x10165ba1c - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1016655a8 - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x101667b2c - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x101667820 - std::panicking::default_hook::h24535936bc1f51de
   6:        0x10ab33828 - <alloc[d07bc629de031c28]::boxed::Box<rustc_driver_impl[17630cf877ef70bb]::install_ice_hook::{closure#0}> as core[fca7800875c611c6]::ops::function::Fn<(&dyn for<'a, 'b> core[fca7800875c611c6]::ops::function::Fn<(&'a core[fca7800875c611c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[fca7800875c611c6]::marker::Sync + core[fca7800875c611c6]::marker::Send, &core[fca7800875c611c6]::panic::panic_info::PanicInfo)>>::call
   7:        0x101668524 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   8:        0x101667f2c - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   9:        0x101665bd8 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
  10:        0x101667c9c - _rust_begin_unwind
  11:        0x1016c4140 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  12:        0x10eb96984 - <rustc_hir[8f63456841fca8c8]::definitions::Definitions>::local_def_path_hash_to_def_id::err
  13:        0x10b520450 - <rustc_middle[e187904418cf7088]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x10bd3ba28 - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::def_kind::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  15:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  16:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  17:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  18:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  19:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  20:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  21:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  22:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  23:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  24:        0x10bcdb140 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::DefaultCache<rustc_type_ir[a6f4416129910f14]::canonical::Canonical<rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_middle[e187904418cf7088]::ty::ParamEnvAnd<rustc_middle[e187904418cf7088]::ty::predicate::Predicate>>, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  25:        0x10bde3e20 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  26:        0x10c42a6f4 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  27:        0x10c42a9c8 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  28:        0x10c35bd10 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  29:        0x10c35b44c - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor as rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationProcessor>::process_obligation
  30:        0x10c35d8c8 - <rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationForest<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>
  31:        0x10c353d74 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillmentContext as rustc_infer[88fe184f288a0526]::traits::engine::TraitEngine>::select_where_possible
  32:        0x10ae54ad8 - rustc_hir_analysis[c1c0f42cf391c6f]::check::compare_impl_item::compare_impl_method
  33:        0x10ae81e1c - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_impl_items_against_trait
  34:        0x10ae7d108 - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_item_type
  35:        0x10adedb14 - rustc_hir_analysis[c1c0f42cf391c6f]::check::wfcheck::check_well_formed
  36:        0x10bd6675c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  37:        0x10be34384 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_hir[8f63456841fca8c8]::hir_id::OwnerId)>>::call_once
  38:        0x10bd0f488 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  39:        0x10bcb9c28 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::force_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  40:        0x10bd2deac - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  41:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  42:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  43:        0x10bcbcae4 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::ensure_must_run::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  44:        0x10bdca388 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  45:        0x10ae14820 - std[e84bc52996b8b382]::panicking::try::<(), core[fca7800875c611c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  46:        0x10ad6d4fc - rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in::<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>
  47:        0x10ae8b81c - rustc_hir_analysis[c1c0f42cf391c6f]::check_crate
  48:        0x10b28de3c - rustc_interface[617d4417f0fbb0b3]::passes::analysis
  49:        0x10bd6989c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  50:        0x10be37bf4 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, ())>>::call_once
  51:        0x10bccf194 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::SingleCache<rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  52:        0x10bdbca94 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  53:        0x10ab24e38 - <rustc_middle[e187904418cf7088]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}::{closure#3}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  54:        0x10aaf7a88 - <rustc_interface[617d4417f0fbb0b3]::interface::Compiler>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}, core[fca7800875c611c6]::result::Result<core[fca7800875c611c6]::option::Option<rustc_interface[617d4417f0fbb0b3]::queries::Linker>, rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  55:        0x10ab3b85c - <scoped_tls[710a08ee67d076ea]::ScopedKey<rustc_span[984a238feadb13f5]::SessionGlobals>>::set::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  56:        0x10aaf71d8 - rustc_span[984a238feadb13f5]::create_session_globals_then::<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  57:        0x10ab10400 - std[e84bc52996b8b382]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  58:        0x10ab43808 - <<std[e84bc52996b8b382]::thread::Builder>::spawn_unchecked_<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:        0x101670edc - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
  60:        0x181e1bfa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `diesel::query_builder::select_statement::SelectStatement<diesel::query_builder::from_clause::FromClause<schema::payments_razorpayorder::table>>: diesel::associations::HasTable`  |  = note: this failure-note originates in the macro `diesel::table` (in Nightly builds, run with -Z macro-backtrace for more info)

#1 [check_well_formed] checking that `schema::payments_razorpayorder::<impl at src/schema.rs:987:1: 1009:2>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 representability(1c40f99ab9ada40f-1156139eaba22993)
#1 adt_sized_constraint(thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", adt_sized_constraint, PackedFingerprint(Fingerprint(15298384670303234344, 1108908725942386211)))
stack backtrace:
   0:        0x101665750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
   2:        0x10165ba1c - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1016655a8 - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x101667b2c - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x101667820 - std::panicking::default_hook::h24535936bc1f51de
   6:        0x10ab33828 - <alloc[d07bc629de031c28]::boxed::Box<rustc_driver_impl[17630cf877ef70bb]::install_ice_hook::{closure#0}> as core[fca7800875c611c6]::ops::function::Fn<(&dyn for<'a, 'b> core[fca7800875c611c6]::ops::function::Fn<(&'a core[fca7800875c611c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[fca7800875c611c6]::marker::Sync + core[fca7800875c611c6]::marker::Send, &core[fca7800875c611c6]::panic::panic_info::PanicInfo)>>::call
   7:        0x101668524 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   8:        0x101667f2c - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   9:        0x101665bd8 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
  10:        0x101667c9c - _rust_begin_unwind
  11:        0x1016c4140 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  12:        0x10eb96984 - <rustc_hir[8f63456841fca8c8]::definitions::Definitions>::local_def_path_hash_to_def_id::err
  13:        0x10b520450 - <rustc_middle[e187904418cf7088]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x10b27fee0 - rustc_interface[617d4417f0fbb0b3]::callbacks::dep_node_debug
  15:        0x10bf34920 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode as core[fca7800875c611c6]::fmt::Debug>::fmt
  16:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
  17:        0x101659c18 - <&std::io::stdio::Stderr as std::io::Write>::write_fmt::h66c915205785d7e5
  18:        0x10165a59c - std::io::stdio::_eprint::h7dd5e64a516fb053
  19:        0x10eca2f38 - rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::print_markframe_trace::<rustc_middle[e187904418cf7088]::dep_graph::DepsType>
  20:        0x10bd901a0 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  21:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  22:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  23:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  24:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  25:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  26:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  27:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  28:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  29:        0x10bcdb140 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::DefaultCache<rustc_type_ir[a6f4416129910f14]::canonical::Canonical<rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_middle[e187904418cf7088]::ty::ParamEnvAnd<rustc_middle[e187904418cf7088]::ty::predicate::Predicate>>, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  30:        0x10bde3e20 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  31:        0x10c42a6f4 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  32:        0x10c42a9c8 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  33:        0x10c35bd10 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  34:        0x10c35b44c - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor as rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationProcessor>::process_obligation
  35:        0x10c35d8c8 - <rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationForest<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>
  36:        0x10c353d74 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillmentContext as rustc_infer[88fe184f288a0526]::traits::engine::TraitEngine>::select_where_possible
  37:        0x10ae54ad8 - rustc_hir_analysis[c1c0f42cf391c6f]::check::compare_impl_item::compare_impl_method
  38:        0x10ae81e1c - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_impl_items_against_trait
  39:        0x10ae7d108 - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_item_type
  40:        0x10adedb14 - rustc_hir_analysis[c1c0f42cf391c6f]::check::wfcheck::check_well_formed
  41:        0x10bd6675c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  42:        0x10be34384 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_hir[8f63456841fca8c8]::hir_id::OwnerId)>>::call_once
  43:        0x10bd0f488 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  44:        0x10bcb9c28 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::force_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  45:        0x10bd2deac - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  46:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  47:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  48:        0x10bcbcae4 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::ensure_must_run::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  49:        0x10bdca388 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  50:        0x10ae14820 - std[e84bc52996b8b382]::panicking::try::<(), core[fca7800875c611c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  51:        0x10ad6d4fc - rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in::<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>
  52:        0x10ae8b81c - rustc_hir_analysis[c1c0f42cf391c6f]::check_crate
  53:        0x10b28de3c - rustc_interface[617d4417f0fbb0b3]::passes::analysis
  54:        0x10bd6989c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  55:        0x10be37bf4 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, ())>>::call_once
  56:        0x10bccf194 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::SingleCache<rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  57:        0x10bdbca94 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  58:        0x10ab24e38 - <rustc_middle[e187904418cf7088]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}::{closure#3}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  59:        0x10aaf7a88 - <rustc_interface[617d4417f0fbb0b3]::interface::Compiler>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}, core[fca7800875c611c6]::result::Result<core[fca7800875c611c6]::option::Option<rustc_interface[617d4417f0fbb0b3]::queries::Linker>, rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  60:        0x10ab3b85c - <scoped_tls[710a08ee67d076ea]::ScopedKey<rustc_span[984a238feadb13f5]::SessionGlobals>>::set::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  61:        0x10aaf71d8 - rustc_span[984a238feadb13f5]::create_session_globals_then::<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  62:        0x10ab10400 - std[e84bc52996b8b382]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  63:        0x10ab43808 - <<std[e84bc52996b8b382]::thread::Builder>::spawn_unchecked_<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  64:        0x101670edc - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
  65:        0x181e1bfa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `diesel::query_builder::select_statement::SelectStatement<diesel::query_builder::from_clause::FromClause<schema::payments_razorpayorder::table>>: diesel::associations::HasTable`  |  = note: this failure-note originates in the macro `diesel::table` (in Nightly builds, run with -Z macro-backtrace for more info)

#1 [check_well_formed] checking that `schema::payments_razorpayorder::<impl at src/schema.rs:987:1: 1009:2>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 check_mod_type_wf(landeed[d44e]::schema::payments_razorpayorder)
end of try_mark_green dep node stack
thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", def_kind, PackedFingerprint(Fingerprint(15298384670303234344, 11329740790109027053)))
stack backtrace:
   0:        0x101665750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
   2:        0x10165ba1c - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1016655a8 - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x101667b2c - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x101667820 - std::panicking::default_hook::h24535936bc1f51de
   6:        0x10ab33828 - <alloc[d07bc629de031c28]::boxed::Box<rustc_driver_impl[17630cf877ef70bb]::install_ice_hook::{closure#0}> as core[fca7800875c611c6]::ops::function::Fn<(&dyn for<'a, 'b> core[fca7800875c611c6]::ops::function::Fn<(&'a core[fca7800875c611c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[fca7800875c611c6]::marker::Sync + core[fca7800875c611c6]::marker::Send, &core[fca7800875c611c6]::panic::panic_info::PanicInfo)>>::call
   7:        0x101668524 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   8:        0x101667f2c - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   9:        0x101665bd8 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
  10:        0x101667c9c - _rust_begin_unwind
  11:        0x1016c4140 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  12:        0x10eb96984 - <rustc_hir[8f63456841fca8c8]::definitions::Definitions>::local_def_path_hash_to_def_id::err
  13:        0x10b520450 - <rustc_middle[e187904418cf7088]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x10bd3ba28 - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::def_kind::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  15:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  16:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  17:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  18:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  19:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  20:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  21:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  22:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  23:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  24:        0x10bcdb140 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::DefaultCache<rustc_type_ir[a6f4416129910f14]::canonical::Canonical<rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_middle[e187904418cf7088]::ty::ParamEnvAnd<rustc_middle[e187904418cf7088]::ty::predicate::Predicate>>, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  25:        0x10bde3e20 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  26:        0x10c42a6f4 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  27:        0x10c42a9c8 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  28:        0x10c35bd10 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  29:        0x10c35b44c - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor as rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationProcessor>::process_obligation
  30:        0x10c35d8c8 - <rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationForest<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>
  31:        0x10c353d74 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillmentContext as rustc_infer[88fe184f288a0526]::traits::engine::TraitEngine>::select_where_possible
  32:        0x10ae54ad8 - rustc_hir_analysis[c1c0f42cf391c6f]::check::compare_impl_item::compare_impl_method
  33:        0x10ae81e1c - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_impl_items_against_trait
  34:        0x10ae7d108 - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_item_type
  35:        0x10adedb14 - rustc_hir_analysis[c1c0f42cf391c6f]::check::wfcheck::check_well_formed
  36:        0x10bd6675c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  37:        0x10be34384 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_hir[8f63456841fca8c8]::hir_id::OwnerId)>>::call_once
  38:        0x10bd0f488 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  39:        0x10bcb9c28 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::force_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  40:        0x10bd2deac - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  41:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  42:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  43:        0x10bcbcae4 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::ensure_must_run::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  44:        0x10bdca388 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  45:        0x10ae14820 - std[e84bc52996b8b382]::panicking::try::<(), core[fca7800875c611c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  46:        0x10ad6d4fc - rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in::<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>
  47:        0x10ae8b81c - rustc_hir_analysis[c1c0f42cf391c6f]::check_crate
  48:        0x10b28de3c - rustc_interface[617d4417f0fbb0b3]::passes::analysis
  49:        0x10bd6989c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  50:        0x10be37bf4 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, ())>>::call_once
  51:        0x10bccf194 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::SingleCache<rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  52:        0x10bdbca94 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  53:        0x10ab24e38 - <rustc_middle[e187904418cf7088]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}::{closure#3}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  54:        0x10aaf7a88 - <rustc_interface[617d4417f0fbb0b3]::interface::Compiler>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}, core[fca7800875c611c6]::result::Result<core[fca7800875c611c6]::option::Option<rustc_interface[617d4417f0fbb0b3]::queries::Linker>, rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  55:        0x10ab3b85c - <scoped_tls[710a08ee67d076ea]::ScopedKey<rustc_span[984a238feadb13f5]::SessionGlobals>>::set::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  56:        0x10aaf71d8 - rustc_span[984a238feadb13f5]::create_session_globals_then::<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  57:        0x10ab10400 - std[e84bc52996b8b382]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  58:        0x10ab43808 - <<std[e84bc52996b8b382]::thread::Builder>::spawn_unchecked_<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:        0x101670edc - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
  60:        0x181e1bfa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `diesel::query_builder::select_statement::SelectStatement<diesel::query_builder::from_clause::FromClause<schema::payments_workinghoursconfig::table>>: diesel::associations::HasTable`  |  = note: this failure-note originates in the macro `diesel::table` (in Nightly builds, run with -Z macro-backtrace for more info)

#1 [check_well_formed] checking that `schema::payments_workinghoursconfig::<impl at src/schema.rs:1046:1: 1058:2>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 representability(70ec2409c6c1a63-7496e9d101cb54a4)
#1 adt_sized_constraint(thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", adt_sized_constraint, PackedFingerprint(Fingerprint(15298384670303234344, 11329740790109027053)))
stack backtrace:
   0:        0x101665750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
   2:        0x10165ba1c - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1016655a8 - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x101667b2c - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x101667820 - std::panicking::default_hook::h24535936bc1f51de
   6:        0x10ab33828 - <alloc[d07bc629de031c28]::boxed::Box<rustc_driver_impl[17630cf877ef70bb]::install_ice_hook::{closure#0}> as core[fca7800875c611c6]::ops::function::Fn<(&dyn for<'a, 'b> core[fca7800875c611c6]::ops::function::Fn<(&'a core[fca7800875c611c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[fca7800875c611c6]::marker::Sync + core[fca7800875c611c6]::marker::Send, &core[fca7800875c611c6]::panic::panic_info::PanicInfo)>>::call
   7:        0x101668524 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   8:        0x101667f2c - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   9:        0x101665bd8 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
  10:        0x101667c9c - _rust_begin_unwind
  11:        0x1016c4140 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  12:        0x10eb96984 - <rustc_hir[8f63456841fca8c8]::definitions::Definitions>::local_def_path_hash_to_def_id::err
  13:        0x10b520450 - <rustc_middle[e187904418cf7088]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x10b27fee0 - rustc_interface[617d4417f0fbb0b3]::callbacks::dep_node_debug
  15:        0x10bf34920 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode as core[fca7800875c611c6]::fmt::Debug>::fmt
  16:        0x1016a8470 - core::fmt::write::heedef092c8c0962e
  17:        0x101659c18 - <&std::io::stdio::Stderr as std::io::Write>::write_fmt::h66c915205785d7e5
  18:        0x10165a59c - std::io::stdio::_eprint::h7dd5e64a516fb053
  19:        0x10eca2f38 - rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::print_markframe_trace::<rustc_middle[e187904418cf7088]::dep_graph::DepsType>
  20:        0x10bd901a0 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  21:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  22:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  23:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  24:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  25:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  26:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  27:        0x10bd8f80c - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  28:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  29:        0x10bcdb140 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::DefaultCache<rustc_type_ir[a6f4416129910f14]::canonical::Canonical<rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_middle[e187904418cf7088]::ty::ParamEnvAnd<rustc_middle[e187904418cf7088]::ty::predicate::Predicate>>, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  30:        0x10bde3e20 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  31:        0x10c42a6f4 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  32:        0x10c42a9c8 - <rustc_infer[88fe184f288a0526]::infer::InferCtxt as rustc_trait_selection[67ea6c3922506dc7]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  33:        0x10c35bd10 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  34:        0x10c35b44c - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor as rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationProcessor>::process_obligation
  35:        0x10c35d8c8 - <rustc_data_structures[d96e6b3ae716122c]::obligation_forest::ObligationForest<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillProcessor>
  36:        0x10c353d74 - <rustc_trait_selection[67ea6c3922506dc7]::traits::fulfill::FulfillmentContext as rustc_infer[88fe184f288a0526]::traits::engine::TraitEngine>::select_where_possible
  37:        0x10ae54ad8 - rustc_hir_analysis[c1c0f42cf391c6f]::check::compare_impl_item::compare_impl_method
  38:        0x10ae81e1c - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_impl_items_against_trait
  39:        0x10ae7d108 - rustc_hir_analysis[c1c0f42cf391c6f]::check::check::check_item_type
  40:        0x10adedb14 - rustc_hir_analysis[c1c0f42cf391c6f]::check::wfcheck::check_well_formed
  41:        0x10bd6675c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  42:        0x10be34384 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_hir[8f63456841fca8c8]::hir_id::OwnerId)>>::call_once
  43:        0x10bd0f488 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  44:        0x10bcb9c28 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::force_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  45:        0x10bd2deac - <rustc_query_impl[a9dcee21c1ea9187]::plumbing::query_callback<rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_well_formed::QueryType>::{closure#0} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, rustc_query_system[3fe282a48bd1d9e8]::dep_graph::dep_node::DepNode)>>::call_once
  46:        0x10bd8f7c8 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  47:        0x10bd8f588 - <rustc_query_system[3fe282a48bd1d9e8]::dep_graph::graph::DepGraphData<rustc_middle[e187904418cf7088]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  48:        0x10bcbcae4 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::ensure_must_run::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::VecCache<rustc_hir[8f63456841fca8c8]::hir_id::OwnerId, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt>
  49:        0x10bdca388 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  50:        0x10ae14820 - std[e84bc52996b8b382]::panicking::try::<(), core[fca7800875c611c6]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  51:        0x10ad6d4fc - rustc_data_structures[d96e6b3ae716122c]::sync::parallel::disabled::par_for_each_in::<&[rustc_hir[8f63456841fca8c8]::hir_id::OwnerId], <rustc_middle[e187904418cf7088]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[c1c0f42cf391c6f]::check_crate::{closure#1}::{closure#0}>::{closure#0}>
  52:        0x10ae8b81c - rustc_hir_analysis[c1c0f42cf391c6f]::check_crate
  53:        0x10b28de3c - rustc_interface[617d4417f0fbb0b3]::passes::analysis
  54:        0x10bd6989c - rustc_query_impl[a9dcee21c1ea9187]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>
  55:        0x10be37bf4 - <rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::dynamic_query::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<(rustc_middle[e187904418cf7088]::ty::context::TyCtxt, ())>>::call_once
  56:        0x10bccf194 - rustc_query_system[3fe282a48bd1d9e8]::query::plumbing::try_execute_query::<rustc_query_impl[a9dcee21c1ea9187]::DynamicConfig<rustc_query_system[3fe282a48bd1d9e8]::query::caches::SingleCache<rustc_middle[e187904418cf7088]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a9dcee21c1ea9187]::plumbing::QueryCtxt, true>
  57:        0x10bdbca94 - rustc_query_impl[a9dcee21c1ea9187]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  58:        0x10ab24e38 - <rustc_middle[e187904418cf7088]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}::{closure#3}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  59:        0x10aaf7a88 - <rustc_interface[617d4417f0fbb0b3]::interface::Compiler>::enter::<rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}::{closure#1}, core[fca7800875c611c6]::result::Result<core[fca7800875c611c6]::option::Option<rustc_interface[617d4417f0fbb0b3]::queries::Linker>, rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  60:        0x10ab3b85c - <scoped_tls[710a08ee67d076ea]::ScopedKey<rustc_span[984a238feadb13f5]::SessionGlobals>>::set::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  61:        0x10aaf71d8 - rustc_span[984a238feadb13f5]::create_session_globals_then::<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  62:        0x10ab10400 - std[e84bc52996b8b382]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>
  63:        0x10ab43808 - <<std[e84bc52996b8b382]::thread::Builder>::spawn_unchecked_<rustc_interface[617d4417f0fbb0b3]::util::run_in_thread_with_globals<rustc_interface[617d4417f0fbb0b3]::interface::run_compiler<core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>, rustc_driver_impl[17630cf877ef70bb]::run_compiler::{closure#0}>::{closure#1}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fca7800875c611c6]::result::Result<(), rustc_span[984a238feadb13f5]::ErrorGuaranteed>>::{closure#2} as core[fca7800875c611c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  64:        0x101670edc - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
  65:        0x181e1bfa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `diesel::query_builder::select_statement::SelectStatement<diesel::query_builder::from_clause::FromClause<schema::payments_workinghoursconfig::table>>: diesel::associations::HasTable`  |  = note: this failure-note originates in the macro `diesel::table` (in Nightly builds, run with -Z macro-backtrace for more info)

#1 [check_well_formed] checking that `schema::payments_workinghoursconfig::<impl at src/schema.rs:1046:1: 1058:2>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 check_mod_type_wf(landeed[d44e]::schema::payments_workinghoursconfig)
end of try_mark_green dep node stack
error: could not compile `landeed` (lib)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by pacak**
This pull request contains two independent changes, one makes it so when `try_force_from_dep_node` fails to recover a query - it marks the node as "red" instead of "green" and the second one makes Debug impl for `DepNode` less panicky if it encounters something from the previous compilation that doesn't map to anything in the current one.

I'm not 100% confident that this is the correct approach, but so far I managed to find a bunch of comments suggesting that some things are allowed to fail in a certain way and changes I made are allowing for those things to fail this way and it fixes all the small reproducers I managed to find.

Compilation panic this pull request avoids is caused by an automatically generated code on an associated type and it is not happening if something else marks it as outdated first (or close like that, but scenario is quite obscure).

Fixes https://github.com/rust-lang/rust/issues/107226
Fixes https://github.com/rust-lang/rust/issues/125367

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks for the PR, @pacak! I'll take a look asap.

**Comment by pacak** [comment]
Looking at https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3AA-incr-comp - I think this pull request should help to close quite a few of open incremental compilation issues. I'll go though the list later.

**Comment by michaelwoerister** [comment]
The `try_force_from_dep_node` issue definitely looks like a bug that has been introduced in the commit that you point to. That's an awesome find, @pacak! Thanks for investigating this.

I'm wondering if there is an obvious way to write a test for this.

File: compiler/rustc_query_system/src/dep_graph/mod.rs [hunk 1]
```diff
@@ -56,15 +56,15 @@ pub trait DepContext: Copy {
...
-                    print_markframe_trace(self.dep_graph(), frame);
+            match panic::catch_unwind(panic::AssertUnwindSafe(|| f(self, dep_node))) {
+                Err(value) => {
+                    if !value.is::<rustc_errors::FatalErrorMarker>() {
+                        print_markframe_trace(self.dep_graph(), frame);
+                    }
+                    panic::resume_unwind(value)
                 }
-                panic::resume_unwind(value)
+                Ok(val) => val,
```
Comment (michaelwoerister) [inline compiler/rustc_query_system/src/dep_graph/mod.rs:66]:
```suggestion
                Ok(query_has_been_forced) => query_has_been_forced,
```

File: compiler/rustc_query_system/src/dep_graph/mod.rs [hunk 2]
```diff
@@ -56,15 +56,15 @@ pub trait DepContext: Copy {
     fn try_force_from_dep_node(self, dep_node: DepNode, frame: Option<&MarkFrame<'_>>) -> bool {
```
Comment (michaelwoerister) [inline compiler/rustc_query_system/src/dep_graph/mod.rs:56]: Can you add something like this to the doc comment:

> Returns `true` if the query has actually been forced. It is valid that a query fails to be forced, e.g. when the query key cannot be reconstructed from the dep-node or when the query kind outright does not support it.

**Comment by michaelwoerister** [comment]
Your test case from https://github.com/rust-lang/rust/issues/107226#issuecomment-2159004254 seems good to add.

Making the `DefPathHash -> (Local)DefId` mappings return an `Option` seems good, especially with respect to not crashing the `DepNode` debug impl.

I'm wondering about some of the error stack traces though, e.g. [here](https://github.com/rust-lang/rust/issues/125945#issue-2332227862). Normally, we should not encounter a removed `DefPathHash` during red-green-marking because at that point we should have come upon a red node signifying the removal and thus stopped going any further. But in these backtraces we do encounter these nodes and  the query traces all have something with trait-solving in them. Trait-solving is the only area where we do manual dependency tracking and I'm wondering if this points to a bug in that manual tracking or if gracefully failing to reconstruct the dep-node is the valid way to handle this.

**Comment by pacak** [comment]
There's probably a bug sitting somewhere, but not having random panic when
you try to print stuff makes sense. If anything - we can look into adding
an assertion that traversed nodes are safe with some better error if they
are not.

**Comment by michaelwoerister** [comment]
> but not having random panic when you try to print stuff makes sense.

Agreed 🙂

**Comment by pacak** [comment]
I rebased on top of master, addressed your suggestions to naming/comments, added a test and confirmed that the test fails before changes to `try_force_from_dep_node` and passes after.

At some point I'll look into requests in trait solving code, but it might take time.

File: compiler/rustc_hir/src/definitions.rs [hunk 3]
```diff
@@ -377,22 +377,12 @@ impl Definitions {
     }
 
     #[inline(always)]
-    pub fn local_def_path_hash_to_def_id(
-        &self,
-        hash: DefPathHash,
-        err_msg: &dyn std::fmt::Debug,
-    ) -> LocalDefId {
+    pub fn local_def_path_hash_to_def_id(&self, hash: DefPathHash) -> Option<LocalDefId> {
```
Comment (michaelwoerister) [inline compiler/rustc_hir/src/definitions.rs:380]: Please add a doc string:
```rust
/// Returns `None` if the `DefPathHash` does not correspond to a `LocalDefId` 
/// in the current compilation session. This can legitimately happen if the 
/// `DefPathHash` is from a `DefId` in an upstream crate or, during incr. comp.,
/// if the `DefPathHash` is from a previous compilation session and
/// the def-path does not exist anymore.
```

**Review by michaelwoerister — COMMENTED** [review]
Thank you, @pacak, this is a great find! Would you mind adding the doc comment suggested below? Then we can merge this.

**Comment by michaelwoerister** [comment]
> At some point I'll look into requests in trait solving code, but it might take time.

Thank you! That would be great. Please ping me when you do so.

File: compiler/rustc_hir/src/definitions.rs (hunk 3 above)
Comment (pacak) [reply compiler/rustc_hir/src/definitions.rs:385]: Done.

**Comment by pacak** [comment]
> Would you mind adding the doc comment suggested below? Then we can merge this.

Done. I believe this pull request should close a lot of existing incremental compilation tickets, I listed two of them but there's more and they don't have reproducers so I wasn't able to test them. Do you think they can be closed as well? I don't have a concrete list, but going though tickets labeled with incremental compilation ICEs and looking at stack traces shows them. 

> Thank you! That would be great. Please ping me when you do so.

Sure.

**Comment by michaelwoerister** [comment]
> Do you think they can be closed as well?

Let's merge the PR and once it is in nightly, ask for confirmation on the respective issues.

**Comment by michaelwoerister** [comment]
Let's not roll this up, for better bisectability.
@bors r+ rollup=never
