### PR TITLE
Make `char::DecodeUtf16::size_hist` more precise

### LINKED ISSUE #88762: Incorrect upper bound for `size_hint` of `char::DecodeUtf16`
```rs
use std::char::decode_utf16;

fn main() {
    let x = [0xD834, 0x006d];
    let mut d = decode_utf16(x);
    d.next();
    let (_, u) = d.size_hint();
    let c = d.count();
    println!("upper bound: {:?}, actual length {}", u, c);
    assert!(u.unwrap() >= c);
}
```
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
     Running `target/debug/playground`
thread 'main' panicked at 'assertion failed: u.unwrap() >= c', src/main.rs:10:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Standard Output
upper bound: Some(0), actual length 1
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a5d9936c6fc80c3e466c4b0124c4c85))

### PR DESCRIPTION
**Pull request by WaffleLapkin**
New implementation takes into account contents of `self.buf` and rounds lower bound up instead of down.

Fixes #88762
Revival of #88763

### CODE REVIEW

File: library/core/src/char/decode.rs [hunk 1]
```diff
@@ -120,9 +120,21 @@ impl<I: Iterator<Item = u16>> Iterator for DecodeUtf16<I> {
...
+        // on lower and upper bound.
+        let addition_from_buf = self.buf.is_some() as usize;
+
+        // `self.iter` could contain entirely valid surrogates (2 elements per
+        // char), or entirely non-surrogates (1 element per char).
+        //
+        // On odd lower bound, at least one element must stay unpaired
+        // (with other elements from `self.iter`), so we round up.
+        let low = low.div_ceil(2) + addition_from_buf;
+        let high = high.and_then(|h| h.checked_add(addition_from_buf));
```
Comment (the8472) [inline library/core/src/char/decode.rs:135]: Was `high` wrong before? Otherwise adding something to it would make it less precise.

Comment (WaffleLapkin) [reply library/core/src/char/decode.rs:135]: it was, see the linked issue

File: library/core/src/char/decode.rs [hunk 2]
```diff
@@ -120,9 +120,21 @@ impl<I: Iterator<Item = u16>> Iterator for DecodeUtf16<I> {
     #[inline]
     fn size_hint(&self) -> (usize, Option<usize>) {
         let (low, high) = self.iter.size_hint();
-        // we could be entirely valid surrogates (2 elements per
-        // char), or entirely non-surrogates (1 element per char)
-        (low / 2, high)
+
+        // `self.buf` will never contain the first part of a surrogate,
```
Comment (dtolnay) [inline library/core/src/char/decode.rs:124]: Why? It doesn't seem to me like that's the case.

For example the following would fail the test below.

```rust
check(&[0xD800, 0xD800, 0xDC00]);
```

```console
thread 'char::test_decode_utf16_size_hint' panicked at 'lower = 2, upper = Some(2)', library/core/tests/char.rs:320:13
```

**Review by dtolnay — CHANGES_REQUESTED** [review]

File: library/core/src/char/decode.rs (hunk 2 above)
Comment (WaffleLapkin) [reply library/core/src/char/decode.rs]: It was a wrong assumption from the original PR that I haven't checked 😅 

I pushed a fix that checks the contents of the buf.

**Review by dtolnay — CHANGES_REQUESTED** [review]
`check(&[0xD800, 0xD800, 0x0])` fails your test.

```console
thread 'char::test_decode_utf16_size_hint' panicked at 'lower = 1, count = 2, upper = Some(1)', library/core/tests/char.rs:320:13
```

**Comment by WaffleLapkin** [comment]
@dtolnay I fixed this edge case too. I wander if I still missed something 😄

**Review by dtolnay — APPROVED** [review]
Thanks, looks good.
