### PR TITLE
dont provide fwd declared params to cg defaults

### LINKED ISSUE #83938: ICE using const_generics_defaults
### Code

```Rust
#![crate_type = "lib"]
#![feature(const_evaluatable_checked, const_generics, const_generics_defaults)]
#![allow(incomplete_features)]

type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];

pub fn push<T, const N: usize>(_: [T; N], _: T)
    -> NpOne<T, N>
{
    todo!()
}

```
([Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=69c97be3247f805358d8f924eabfe383))

I'm not sure how to treat this. It seems that we can sneakily misuse defaults in type definitions to insert a dependent computation on a const parameter which definitely should be forbidden at the moment.

### Meta

`rustc --version --verbose`:
```
 rustc 1.53.0-nightly (d32238532 2021-04-05) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: broken MIR in DefId(0:9 ~ playground[e970]::push) (LocalDecl { mutability: Mut, local_info: None, internal: false, is_block_tail: None, ty: [type error], user_ty: None, source_info: SourceInfo { span: src/lib.rs:5:1: 6:19 (#0), scope: scope[0] } }): bad type [type error]
 --> src/lib.rs:5:1
  |
5 | / pub fn push<T, const N: usize>(_: [T; N], _: T)
6 | |     -> NpOne<T, N>
  | |__________________^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1018:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary>Backtrace</summary><p>

```  Compiling playground v0.0.1 (/playground)
warning: the feature `const_generics_defaults` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics_defaults)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: 1 warning emitted

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/expr.rs:473:21

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:154:49

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:868:53

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/project.rs:710:28

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_infer/src/infer/sub.rs:124:31

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/coercion.rs:1261:42

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:714:27

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:652:60

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at /rustc/d32238532138485c80db4f2cd596372bce214e00/compiler/rustc_middle/src/ty/relate.rs:334:59

error: internal compiler error: cat_expr Errd
 --> src/lib.rs:3:49
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                 ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_typeck/src/check/regionck.rs:402:31

error: internal compiler error: cat_expr Errd
 --> src/lib.rs:3:50
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                  ^^^^^^^^
  |
  = note: delayed at compiler/rustc_typeck/src/check/regionck.rs:402:31

error: internal compiler error: cat_expr Errd
 --> src/lib.rs:3:50
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                  ^
  |
  = note: delayed at compiler/rustc_typeck/src/check/regionck.rs:402:31

error: internal compiler error: ty::ConstKind::Error constructed but no error reported.
  |
  = note: delayed at /rustc/d32238532138485c80db4f2cd596372bce214e00/compiler/rustc_middle/src/ty/consts.rs:184:43

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at /rustc/d32238532138485c80db4f2cd596372bce214e00/compiler/rustc_trait_selection/src/opaque_types.rs:1007:32

error: internal compiler error: cat_expr Errd
 --> src/lib.rs:7:1
  |
7 | / {
8 | |     todo!()
9 | | }
  | |_^
  |
  = note: delayed at compiler/rustc_typeck/src/check/regionck.rs:402:31

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_mir_build/src/build/mod.rs:742:18

error: internal compiler error: mir_const_qualif: MIR had errors
 --> src/lib.rs:3:49
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                 ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/transform/mod.rs:237:18

error: internal compiler error: PromoteTemps: MIR had errors
 --> src/lib.rs:3:49
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                 ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/transform/promote_consts.rs:55:22

error: internal compiler error: broken MIR in DefId(0:7 ~ playground[e970]::NpOne::{constant#0}) ("return type"): bad type [type error]
 --> src/lib.rs:3:49
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                 ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

error: internal compiler error: TyKind::Error constructed but no error reported
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:721:20

error: internal compiler error: broken MIR in DefId(0:7 ~ playground[e970]::NpOne::{constant#0}) (LocalDecl { mutability: Mut, local_info: None, internal: false, is_block_tail: None, ty: [type error], user_ty: None, source_info: SourceInfo { span: src/lib.rs:3:49: 3:59 (#0), scope: scope[0] } }): bad type [type error]
 --> src/lib.rs:3:49
  |
3 | type NpOne<T, const N: usize, const NP: usize = {N+1usize}> = [T; NP];
  |                                                 ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

error: internal compiler error: PromoteTemps: MIR had errors
 --> src/lib.rs:5:1
  |
5 | / pub fn push<T, const N: usize>(_: [T; N], _: T)
6 | |     -> NpOne<T, N>
  | |__________________^
  |
  = note: delayed at compiler/rustc_mir/src/transform/promote_consts.rs:55:22

error: internal compiler error: broken MIR in DefId(0:9 ~ playground[e970]::push) ("return type"): bad type [type error]
 --> src/lib.rs:5:1
  |
5 | / pub fn push<T, const N: usize>(_: [T; N], _: T)
6 | |     -> NpOne<T, N>
  | |__________________^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

error: internal compiler error: broken MIR in DefId(0:9 ~ playground[e970]::push) (LocalDecl { mutability: Mut, local_info: None, internal: false, is_block_tail: None, ty: [type error], user_ty: None, source_info: SourceInfo { span: src/lib.rs:5:1: 6:19 (#0), scope: scope[0] } }): bad type [type error]
 --> src/lib.rs:5:1
  |
5 | / pub fn push<T, const N: usize>(_: [T; N], _: T)
6 | |     -> NpOne<T, N>
  | |__________________^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1018:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (d32238532 2021-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #83938

```rust
#![feature(const_evaluatable_checked, const_generics, const_generics_defaults)]
#![allow(incomplete_features)]

pub struct Bar<const N: usize, const M: usize = { N + 1 }>;
pub fn foo<const N1: usize>() -> Bar<N1> { loop {} }

fn main() {}
```
This PR makes this code no longer ICE, it was ICE'ing previously because when building substs for `Bar<N1>` we would subst the anon ct: `ConstKind::Unevaluated({N + 1}, substs: [N, M])` with substs of `[N1]`. the anon const has forward declared params supplied though so we end up trying to substitute the provided `M` param which causes the ICE.

This PR doesn't handle the predicates of the const so
```rust
trait Foo<const N: usize> { const Assoc: usize; }
pub struct Bar<const N: usize = { <()>::Assoc }> where (): Foo<N>;
```
Resolves to `<() as Foo<N>>::Assoc` which can allow for using fwd declared params indirectly.

```rust
trait Foo<const N: usize> {}
struct Bar<const N: usize = { 2 + 3 }> where (): Foo<N>;
```
This code also ICEs under this PR because instantiating the default's predicates causes an ICE as predicates_of contains predicates with fwd declared params 

PR was briefly discussed [in this zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/evil.20preds.20in.20param.20env.20.2386580)

### CODE REVIEW

**Review by lcnr — APPROVED** [review]
while this does work for now, we probably want to implement these changes in `generics_of` instead to deal with the `ParamEnv`. We will need to do that to deal with unused substs in general.

I don't have a strong opinion on whether to merge this as is, so r=me if you think that it's desirable

**Comment by BoxyUwU** [comment]
(this PR needs the code to be wrapped in a `if tcx.lazy_normalization()` or wahtever so that we dont provide these generics without const_generics/const_evaluatable_checked feature gates)

File: compiler/rustc_typeck/src/collect.rs [hunk 1]
```diff
@@ -1441,6 +1441,32 @@ fn generics_of(tcx: TyCtxt<'_>, def_id: DefId) -> ty::Generics {
...
             } else if tcx.lazy_normalization() {
+                // Only provide backwards declared generics to cg defaults (#83938)
+                if let Node::GenericParam(GenericParam {
+                    hir_id: param_id,
+                    kind: GenericParamKind::Const { .. },
+                    ..
+                }) = tcx.hir().get(tcx.hir().get_parent_node(hir_id))
+                {
+                    let item_id = tcx.hir().get_parent_node(*param_id);
+                    let item_def_id = tcx.hir().local_def_id(item_id);
```
Comment (lcnr) [inline compiler/rustc_typeck/src/collect.rs:1452]: you can use `parent_def_id` here

File: compiler/rustc_typeck/src/collect.rs [hunk 2]
```diff
@@ -1441,6 +1441,25 @@ fn generics_of(tcx: TyCtxt<'_>, def_id: DefId) -> ty::Generics {
                 // of a const parameter type, e.g. `struct Foo<const N: usize, const M: [u8; N]>` is not allowed.
                 None
             } else if tcx.lazy_normalization() {
+                // Only provide backwards declared generics to cg defaults (#86580)
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect.rs:1444]: It would be great to expand this with a code example. Something like

```rust
fn foo<const N, const M: usize = { N + 1 }>
```

and then explain that, when invoked on the `{N + 1}` constant, we extract the prefix `[N]`

File: compiler/rustc_typeck/src/collect.rs [hunk 3]
```diff
@@ -2404,6 +2424,16 @@ fn explicit_predicates_of(tcx: TyCtxt<'_>, def_id: DefId) -> ty::GenericPredicat
             }
         }
     } else {
+        if matches!(def_kind, DefKind::AnonConst) && tcx.lazy_normalization() {
+            // Provide predicates of parent item of cg defaults manually as `generics_of`
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/collect.rs:2428]: Again, can you give an example where there are some where clauses and show what is going on here in terms of the Rust code?

File: compiler/rustc_typeck/src/outlives/mod.rs [hunk 4]
```diff
@@ -20,6 +20,17 @@ pub fn provide(providers: &mut Providers) {
 fn inferred_outlives_of(tcx: TyCtxt<'_>, item_def_id: DefId) -> &[(ty::Predicate<'_>, Span)] {
     let id = tcx.hir().local_def_id_to_hir_id(item_def_id.expect_local());
 
+    if matches!(tcx.def_kind(item_def_id), hir::def::DefKind::AnonConst) && tcx.lazy_normalization()
+    {
+        // Provide predicates of parent item of cg defaults manually as `generics_of`
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/outlives/mod.rs:25]: As above

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
