### PR TITLE
parser: recover on nested ADTs as enum variants

### LINKED ISSUE #66127: Gracefully recover from incorrectly nested items
The parser currently only attempts to parse items and sub-items based on what the parent item is and pretty much gives up if, for example, a trait item is inside of an ADT, or an ADT is defined inside an ADT. The parser could try exhausting all the valid possible parses, and if it fails start trying to parse other cases that are invalid there and explain why it is not allowed and supply guidance on what to do instead. For example, a case taken from https://www.reddit.com/r/rust/comments/5tnjt8/question_regarding_nested_enum/:

```
enum Foo {
    enum Bar {
         Baz,
     },
    Bat,
}
```

gives

```
error: expected identifier, found keyword `enum`
 --> src/lib.rs:2:5
  |
2 |     enum Bar {
  |     ^^^^ expected identifier, found keyword
  |
help: you can escape reserved keywords to use them as identifiers
  |
2 |     r#enum Bar {
  |     ^^^^^^

error: missing comma
 --> src/lib.rs:2:9
  |
2 |     enum Bar {
  |         ^ help: missing comma

error: expected `:`, found `,`
 --> src/lib.rs:3:13
  |
3 |          Baz,
  |             ^ expected `:`
```

when instead it could give a single error saying `enum definitions cannot be nested`, or something to that effect.

### PR DESCRIPTION
**Pull request by VirrageS**
Closes: https://github.com/rust-lang/rust/issues/66127

### CODE REVIEW

File: src/librustc_parse/parser/item.rs [hunk 1]
```diff
@@ -1740,6 +1742,26 @@ impl<'a> Parser<'a> {
         ).emit();
     }
 
+    /// Checks if current token is keyword that is currently being parsed and reports an error if it is.
+    fn report_nested_keyword(&mut self, kw: Symbol) -> PResult<'a, ()> {
+        if self.token.is_keyword(kw) {
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]: Instead of taking in `kw: Symbol`, I think it would be better to check whether the current token is one of `kw::Enum`, `kw::Struct`, or `kw::Union`, use `let item = self.parse_item()?;` to parse the full nested `enum`, `struct`, or `union`, and then finally use `item.span`.

You can use `self.token.clone()` + `pprust::token_to_string` as a substitute for `kw` in the `format!(...)`s below.

File: src/librustc_parse/parser/item.rs [hunk 2]
```diff
@@ -1740,6 +1742,26 @@ impl<'a> Parser<'a> {
...
+                &format!("`{}` definitions cannot be nested", kw),
+            );
+
+            err.span_suggestion(
+                self.token.span,
+                &format!("consider creating a new `{}` definition instead of nesting", kw),
+                String::new(),
+                Applicability::MaybeIncorrect,
+            );
+            err.emit();
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]: You don't need to `return Err(err)` if you use recovery. Once you've done that, you can `.emit()` and `.span_suggestion()` can be chained here.

File: src/test/ui/enum/nested-enum.rs [hunk 3]
```diff
@@ -0,0 +1,8 @@
+enum Foo {
+    enum Bar { //~ ERROR `enum` definitions cannot be nested
+        Baz,
+    },
```
Comment (Centril) [inline src/test/ui/enum/nested-enum.rs]:
```suggestion
    },
    struct Quux { field: u8 }, //~ ERROR `struct` definitions cannot be nested
    union Wibble { field: u8 }, //~ ERROR `union` definitions cannot be nested
```

**Review by Centril — CHANGES_REQUESTED** [review]

File: src/librustc_parse/parser/item.rs [hunk 4]
```diff
@@ -1740,6 +1742,26 @@ impl<'a> Parser<'a> {
         ).emit();
     }
 
+    /// Checks if current token is keyword that is currently being parsed and reports an error if it is.
+    fn report_nested_keyword(&mut self, kw: Symbol) -> PResult<'a, ()> {
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
    fn report_nested_adt_item(&mut self) -> PResult<'a, ()> {
```

File: src/librustc_parse/parser/item.rs [hunk 5]
```diff
@@ -1340,6 +1340,8 @@ impl<'a> Parser<'a> {
             let vlo = self.token.span;
 
             self.eat_bad_pub();
+
+            self.check_nested(kw::Enum)?;
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
            self.report_nested_adt_item()?;
```

File: src/librustc_parse/parser/item.rs (hunk 1 above)
Comment (VirrageS) [reply src/librustc_parse/parser/item.rs]: The problem with doing `let item = self.parse_item()?;` is that we can have a case:
```rust
enum Foo {
    enum, // someone forgot to capitalize 
    bar,
}
```
and this could potentially produce errors which are not really relevant to the code.

File: src/librustc_parse/parser/item.rs (hunk 2 above)
Comment (VirrageS) [reply src/librustc_parse/parser/item.rs]: I've decided to return error here to prevent any more errors to appear. Otherwise, user is flooded with 4 different errors and I thought it can be overwhelming.

Should I just stick with `emit`?

File: src/librustc_parse/parser/item.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_parse/parser/item.rs]: Parser recovery is all about making educated guesses as what to what the user meant. It's unlikely that the user really wanted to name a variant `enum` -- if you truly want to catch that case, you can look-ahead 1 token for `token::Comma` and avoid doing `self.parse_item()?;` but I think it's not worth the extra complexity.

Meanwhile, doing `self.parse_item()?` makes for better recovery in the common case because you turn fatal parser errors into recoverable ones so that compilation can continue to e.g. type checking and so on.

File: src/librustc_parse/parser/item.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_parse/parser/item.rs]: More errors shouldn't appear if you use `self.parse_item()?;`. ;)

File: src/librustc_parse/parser/item.rs [hunk 6]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
         ).emit();
     }
 
+    /// Checks if current token is one of tokens which cannot be nested like `kw::Enum`. In case
+    /// it is, we try to parse the item and report error about nested types.
+    fn recover_nested_adt_item(&mut self, keyword: Symbol) -> PResult<'a, bool> {
+        if self.token.is_keyword(kw::Enum) ||
+            self.token.is_keyword(kw::Struct) ||
+            self.token.is_keyword(kw::Union)  {
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
            self.token.is_keyword(kw::Union)
        {
```

File: src/librustc_parse/parser/item.rs [hunk 7]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+
+            let prev_token = self.token.clone();
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
            let kw_token = self.token.clone();
            let kw_str = pprust::token_to_string(&kw_token);
```

File: src/librustc_parse/parser/item.rs [hunk 8]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+            let item = self.parse_item()?;
+            if self.token == token::Comma {
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
            self.eat(&token::Comma);
```

File: src/librustc_parse/parser/item.rs [hunk 9]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+                self.bump();
+            }
+
+            let mut err = self.struct_span_err(
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
            let err = self.struct_span_err(
```

File: src/librustc_parse/parser/item.rs [hunk 10]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+                prev_token.span,
+                &format!("`{}` definition cannot be nested inside `{}`", pprust::token_to_string(&prev_token), keyword),
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
                &format!("`{}` definition cannot be nested inside `{}`", kw_str, keyword),
```

File: src/librustc_parse/parser/item.rs [hunk 11]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+            self.token.is_keyword(kw::Union)  {
+
+            let prev_token = self.token.clone();
+            let item = self.parse_item()?;
+            if self.token == token::Comma {
+                self.bump();
+            }
+
+            let mut err = self.struct_span_err(
+                prev_token.span,
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
                kw_token.span,
```

File: src/librustc_parse/parser/item.rs [hunk 12]
```diff
@@ -1742,6 +1747,36 @@ impl<'a> Parser<'a> {
...
+                &format!("`{}` definition cannot be nested inside `{}`", pprust::token_to_string(&prev_token), keyword),
+            );
+            err.span_suggestion(
+                item.unwrap().span,
+                &format!("consider creating a new `{}` definition instead of nesting", pprust::token_to_string(&prev_token)),
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
                &format!("consider creating a new `{}` definition instead of nesting", kw_str),
```

File: src/librustc_parse/parser/item.rs (hunk 8 above)
Comment (VirrageS) [reply src/librustc_parse/parser/item.rs]: I kind don't like that we manually eat the `token::Comma` here even though we have code which deals with that: https://github.com/rust-lang/rust/blob/master/src/librustc_parse/parser/item.rs#L1380-L1394 

But the alternative would be either to move this to function and call it:
```rust
            if !self.recover_nested_adt_item(kw::Enum)? {
                // Item already parsed, we need to skip this variant.
                check_variant_comma();
                continue
            }
            ...
            check_variant_comma();
```

or wrap the code into `if`:
```rust
            if self.recover_nested_adt_item(kw::Enum)? {
                let ident = self.parse_ident()?;
    
                let struct_def = if self.check(&token::OpenDelim(token::Brace)) {
                    // Parse a struct variant.
                    let (fields, recovered) = self.parse_record_struct_body()?;
                    VariantData::Struct(fields, recovered)
                } else if self.check(&token::OpenDelim(token::Paren)) {
                    VariantData::Tuple(
                        self.parse_tuple_struct_body()?,
                        DUMMY_NODE_ID,
                    )
                } else {
                    VariantData::Unit(DUMMY_NODE_ID)
                };
                ...
            }

            if !self.eat(&token::Comma) {
                if self.token.is_ident() && !self.token.is_reserved_ident() {
                    let sp = self.sess.source_map().next_point(self.prev_span);
                    self.struct_span_err(sp, "missing comma")
                        .span_suggestion_short(
                            sp,
                            "missing comma",
                            ",".to_owned(),
                            Applicability::MaybeIncorrect,
                        )
                        .emit();
                } else {
                    break;
                }
            }
```

Comment (Centril) [reply src/librustc_parse/parser/item.rs]: I think adding that much code as in the second snippet wouldn't be worth the added complexity. The issue with the manual eating of `token::Comma` should be fixed by using `self.parse_delim_comma_seq(...)`, but let's leave that for another time.

Comment (VirrageS) [reply src/librustc_parse/parser/item.rs]: Yeah, the complexity is not good either. Should I leave some note/todo comment?

Comment (Centril) [reply src/librustc_parse/parser/item.rs]: Sure, leaving a FIXME to consider `parse_delim_comma_seq` would be great.

File: src/librustc_parse/parser/item.rs [hunk 13]
```diff
@@ -1336,11 +1337,17 @@ impl<'a> Parser<'a> {
     /// Parses the part of an enum declaration following the `{`.
     fn parse_enum_def(&mut self, _generics: &Generics) -> PResult<'a, EnumDef> {
         let mut variants = Vec::new();
+        // FIXME: Consider using `parse_delim_comma_seq` - we then could remove eating `token::Comma`
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
        // FIXME: Consider using `parse_delim_comma_seq`.
        // We could then remove eating comma in `recover_nested_adt_item`.
```

File: src/librustc_parse/parser/item.rs [hunk 14]
```diff
@@ -1336,11 +1337,17 @@ impl<'a> Parser<'a> {
...
+        // in `recover_nested_adt_item`.
```
Comment (Centril) [inline src/librustc_parse/parser/item.rs]:
```suggestion
```

**Comment by Centril** [comment]
Thanks! @bors r+
