### PR TITLE
fix Zip unsoundness (again)

### LINKED ISSUE #137255: Panic-safety issue with `Zip` specializations
while trying to come up with a more precise formulation of `TrustedRandomAccess` properties, I wondered
* what should `size_hint`’s behavior be on subsequent `next_back` calls?
  * answer: probably it should keep decrementing `size` by 1 for each call; i.e. length changes at the back via `next_back` are tracked in the `size` information, but `__iterator_get_unchecked` has no impact on the size
* then… what should be the `size_hint`/`size`/`len` change when `next_back` is called but *panics*!?

That’s where I took a detour reviewing all the relevant code that uses it. And sure enough, this case wasn’t consistently handled.

---

E.g. this section

https://github.com/rust-lang/rust/blob/f44efbf9e11b1b6bba77c046d7dd150de37e0e0f/library/core/src/iter/adapters/zip.rs#L374-L398

containing in particular

https://github.com/rust-lang/rust/blob/f44efbf9e11b1b6bba77c046d7dd150de37e0e0f/library/core/src/iter/adapters/zip.rs#L386-L387

_– whilst being conditional’d under logic based on `self.a.size()` –_
for sure looks like it assumes that a panicking `next_back` call *will* always at least decrement the size.

But – funnily enough – the *very same* code section lives in a `next_back` impl – at the beginning of that impl – being code that **can panic** but up to this point nothing happened that would touch `self.index` or `self.len`, the information in `Zip` that determines `size_hint`.

https://github.com/rust-lang/rust/blob/f44efbf9e11b1b6bba77c046d7dd150de37e0e0f/library/core/src/iter/adapters/zip.rs#L335-L338

So okay… this is potentially bad… well… it in fact **is bad**:

---

```rust
use std::{
    iter::zip,
    panic::{catch_unwind, resume_unwind, AssertUnwindSafe},
};

fn main() {
    let mut panic = true;
    let a = [42, 1337];
    let a2 = zip(
        a.iter().map(|i| {
            println!("reading item {i:>11} from slice");
            if panic {
                panic = false;
                resume_unwind(Box::new(()))
            }
        }),
        &[(); 1],
    ); // inner `zip` of length `1`, but `a` has length `2`:
    // so here inner.len == 1, inner.a_len == 2, inner.a.size() == 2

    let mut i = zip(a2, &[(); 0]); // outer `zip` of length `0`, but `a2` has length `1`
    // so here outer.len == 0, outer.a_len == 1, outer.a.size() == 1

    catch_unwind(AssertUnwindSafe(|| i.next_back())).ok(); // outer’s `next_back` tries to shorten outer.a by 1 element first
    // based on outer.a.size() == inner.size() == 1 > 0 == outer.len
    // which decrements `outer.a_len from 1 to 0`, then recurses into `inner`:

    // inner’s `next_back` tries to shorten inner.a by 1 element first
    // based on inner.a.size() == 2 > 1 == inner.len
    // which which decrements `inner.a_len from 2 to 1`, then calls `next_back` on the `Map<slice::Iter>`
    // shortening the slice iterator by 1 element, now `inner.a.size()` is 1
    // then panicking from the `Map`

    // panic is caught. NEW STATE:
    // ===========================
    // inner.len == 1, inner.a_len == 1, inner.a.size() == 1
    // outer.len == 0, outer.a_len == 0, outer.a.size() == … well … inner.len == 1

    // (note that all .index fields are untouched and still 0, else more accurately
    // the formula would be outer.a.size() == inner.len - inner.index)

    // the IMPORTANT effect: outer.a.size() is unchanged, still larger than outer.len.

    i.next_back(); // <- next line of code, one more `next_back`, no more `panic` necessary…
    // outer’s `next_back` tries to shorten outer.a by 1 element first
    // based on outer.a.size() == inner.size() == 1 > 0 == outer.len
    //                                         !!!!!!!!!!!!!!!!!!!!
    // which decrements `outer.a_len from 0 to …INTEGER UNDERFLOWS… to usize::MAX`, then recurses into `inner`:
    //                                         !!!!!!!!!!!!!!!!!!!!

    // inner’s `next_back` needs no further shortening, based on inner.a.size() == 1 == inner.b.size()
    // (which is the so-far untouched iterator over &[(); 1],)
    // so we reach the main logic which decrements inner.len (1 -> 0) and inner.a_len (1 -> 0),
    // and successfully reads the items at position 0

    // NEW STATE:
    // ==========
    // inner.len == 0, inner.a_len == 0, inner.a.size() == 1 [inner.b.size() == 1]
    // outer.len == 0, outer.a_len == usize::MAX, outer.a.size() == inner.len == 0

    // now … the `Zip` is empty (`outer.len == 0`) – okay really it was never not empty but anyway
    // we poll it from the front now, reaching the side-effects simulation code (linked below)

    println!("-----------------------------------");
    i.next(); // each of these now does the action of
/*          self.index += 1;
            self.len += 1;
            // match the base implementation's potential side effects
            // SAFETY: we just checked that `i` < `self.a.len()`
            unsafe {
                self.a.__iterator_get_unchecked(i); // `i` is previous value of `.index`
            }
*/  // which means for the first call, we get outer.len (0 -> 1) and outer.index(0 -> 1)
    // notably, this code is always executed since the overflow we had
    // disarmed the `self.index < self.a_len` conditional – which is always true with `outer.a_len == usize::MAX`
    // so this time we access `__iterator_get_unchecked(0)` which accesses the 42 again

    i.next(); // and this time it accesses `__iterator_get_unchecked(1)` which accesses the 1337 again
    i.next(); // and this time it accesses `__iterator_get_unchecked(2)` which is out of bounds for the slice :-/
}
```

(side-effect simulation code mentioned above)

https://github.com/rust-lang/rust/blob/f44efbf9e11b1b6bba77c046d7dd150de37e0e0f/library/core/src/iter/adapters/zip.rs#L318-L329

output:
```
reading item        1337 from slice
reading item          42 from slice
-----------------------------------
reading item          42 from slice
reading item        1337 from slice
reading item   957756800 from slice
```

And [here is a playground version](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14bf7a016f410203bdab0237c748c458) that runs this `i.next()` in a longer loop up to segfault

@rustbot label T-libs, A-iterators, A-specialization, I-unsound

### PR DESCRIPTION
**Pull request by the8472**
Some history: The Zip TrustedRandomAccess specialization has tried to emulate the side-effects of the naive implementation for a long time, including backwards iteration. #82292 tried to fix unsoundness (#82291) in that side-effect-preservation code, but this introduced some panic-safety unsoundness (#86443), but the fix #86452 didn't fix it for nested Zip iterators (#137255).

Rather than piling yet another fix ontop of this heap of fixes this PR reduces the number of cases in which side-effects will be preserved; the necessary API guarantee change was approved in #83791 but we haven't made use of that so far.

fixes #137255

### CODE REVIEW

**Comment by workingjubilee** [comment]
exciting!

File: library/coretests/tests/iter/adapters/zip.rs [hunk 1]
```diff
@@ -275,6 +271,41 @@ fn test_double_ended_zip() {
...
+        e.1.fetch_add(1, Ordering::Relaxed);
+        if panic {
+            panic = false;
+            resume_unwind(Box::new(()))
+        }
+        e.0
+    });
+    let b = [1, 2, 3, 4].as_slice().iter().copied();
+    let c = [5, 6, 7].as_slice().iter().copied();
+    let ab = zip(a, b);
```
Comment (workingjubilee) [inline library/coretests/tests/iter/adapters/zip.rs]:
```suggestion
    // The actual case we are testing: this Zip gets nested in the next, and
    // `a` forces a premature unwind from Zip's iterator-driving code.
    let ab = zip(a, b);
```

File: library/coretests/tests/iter/adapters/zip.rs [hunk 2]
```diff
@@ -275,6 +271,41 @@ fn test_double_ended_zip() {
...
+
+    let mut abc = zip(ab, c);
```
Comment (workingjubilee) [inline library/coretests/tests/iter/adapters/zip.rs:306]: Is this correct?
```suggestion
    // This outer Zip could drive the inner Zip in ways that resulted in unsoundness
    let mut abc = zip(ab, c);
```

File: library/coretests/tests/iter/adapters/zip.rs [hunk 3]
```diff
@@ -275,6 +271,41 @@ fn test_double_ended_zip() {
...
+
+    assert_eq!(abc.len(), 3);
+    catch_unwind(AssertUnwindSafe(|| abc.next_back())).ok();
```
Comment (workingjubilee) [inline library/coretests/tests/iter/adapters/zip.rs:314]: ...feels like there should probably be a comment here also, maybe on the incorrectness we used to encounter from doing this?

**Review by workingjubilee — CHANGES_REQUESTED** [review]
Could you either commit these comments or, if they're wrong (and that seems reasonably likely), correct them? The description of the issue so far is... a bit in-the-weeds. Tests are a valuable opportunity to spend time describing the actual issues we are trying to avoid.

**Comment by the8472** [comment]
@rustbot ready

The issue is complicated, so I don't think those few suggested comments would a good job, so I tried to add some more instead.

**Comment by the8472** [comment]
@workingjubilee will you take another look at it or should I reroll?

File: library/core/src/iter/adapters/zip.rs [hunk 4]
```diff
@@ -371,36 +357,42 @@ where
...
-            let sz_b = self.b.size();
-            // Adjust a, b to equal length, make sure that only the first call
-            // of `next_back` does this, otherwise we will break the restriction
-            // on calls to `self.next_back()` after calling `get_unchecked()`.
-            if sz_a != sz_b {
+        // No effects when the iterator is exhausted, to reduce the number of
+        // cases the unsafe code has to handle.
+        // See #137255 for a case where where too many epicycles lead to unsoundness.
+        if self.index < self.len {
+            let old_len = self.len;
```
Comment (workingjubilee) [inline library/core/src/iter/adapters/zip.rs:364]: We record the original length we are working with...

File: library/core/src/iter/adapters/zip.rs [hunk 5]
```diff
@@ -371,36 +357,42 @@ where
...
+
+            // since get_unchecked and the side-effecting code can execute user code
+            // which can panic we decrement the counter beforehand
+            // so that the same index won't be accessed twice, as required by TrustedRandomAccess.
+            // Additionally this will ensure that the side-effects code won't run a second time.
+            self.len -= 1;
```
Comment (workingjubilee) [inline library/core/src/iter/adapters/zip.rs:370]: So now, if we somehow arrive in this code again, `old_len` will be the lower `self.len` value, preventing the rerun...

File: library/core/src/iter/adapters/zip.rs [hunk 6]
```diff
@@ -371,36 +357,42 @@ where
...
+                        for _ in 0..sz_a - old_len {
+                            self.a.next_back();
+                        }
                     }
+                    if B::MAY_HAVE_SIDE_EFFECT && sz_b > old_len {
+                        for _ in 0..sz_b - old_len {
+                            self.b.next_back();
+                        }
+                    }
+                    debug_assert_eq!(self.a.size(), self.b.size());
```
Comment (workingjubilee) [inline library/core/src/iter/adapters/zip.rs:393]: So we're calling `next_back` a bunch of times just to run side-effects of the closure, which becomes observable. Right?

It feels kinda weird that we potentially `next_back` a bunch of times here. This allows using `next_back` to force running side effects that would not be encountered if we only drove using `next`, right?

File: library/core/src/iter/adapters/zip.rs [hunk 7]
```diff
@@ -371,36 +357,42 @@ where
...
+                // otherwise we will break the restriction on calls to `self.next_back()`
+                // after calling `get_unchecked()`.
+                if sz_a != sz_b && (old_len == sz_a || old_len == sz_b) {
+                    if A::MAY_HAVE_SIDE_EFFECT && sz_a > old_len {
+                        for _ in 0..sz_a - old_len {
+                            self.a.next_back();
+                        }
                     }
+                    if B::MAY_HAVE_SIDE_EFFECT && sz_b > old_len {
+                        for _ in 0..sz_b - old_len {
```
Comment (workingjubilee) [inline library/core/src/iter/adapters/zip.rs:389]: The subtlety here that we are catching is that the `len` of the zip-iter (zipter?) is the lesser of the two sizes.

File: library/core/src/iter/adapters/zip.rs (hunk 6 above)
Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:393]: The regular, non-`TrustedRandomAccess`-specialized `next_back` naturally performs this tail-trimming because it needs to bring the two inner iterators down to the same length (known through `ExactSizeIterator`) before it can pop off a tail element at the same index.

It's the side-effects of the trimming that we try to emulate here because otherwise it'd look like we're jumping into the middle of the iterator.

Personally I'd prefer if we just did the jumping, but some people like their cute liddle closure side-effects and are sad if they don't get to run.

File: library/core/src/iter/adapters/zip.rs (hunk 5 above)
Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:370]: yep

File: library/core/src/iter/adapters/zip.rs (hunk 7 above)
Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:389]: It's hopefully less surprising if one starts with the regular implementation and only then looks at the specialized one.

Comment (workingjubilee) [reply library/core/src/iter/adapters/zip.rs:389]: you mean the `default fn` implementation?

Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:389]: yes

File: library/core/src/iter/adapters/zip.rs (hunk 6 above)
Comment (workingjubilee) [reply library/core/src/iter/adapters/zip.rs:393]: Hm. It's not obvious to me that this sort of behavior is guaranteed or even expected according to the contract of `core::iter::zip`. Nonetheless, I suppose this is fine for now, since this is the current behavior.

**Comment by workingjubilee** [comment]
Alright, sorry for taking so long to review this. It's quite painful to reason about. I'm satisfied with it.

@bors r+

File: library/core/src/iter/adapters/zip.rs (hunk 6 above)
Comment (the8472) [reply library/core/src/iter/adapters/zip.rs:393]: There's just no stable way skip in the middle of an iterator and elide its side-effects. So people might try to reason from its public interface as-if things were implemented by `next()`.
