### PR TITLE
Handle str literals written with `'` lexed as lifetime

### LINKED ISSUE #119685: Diagnostics could be more helpful when confusing character and string literals
### Code

```Rust
fn main() {
    println!('hello world');
}
```

### Current output

```Shell
error: prefix `world` is unknown
 --> src/main.rs:4:21
  |
4 |     println!('hello world');
  |                     ^^^^^ unknown prefix
  |
  = note: prefixed identifiers and literals are reserved since Rust 2021
help: consider inserting whitespace here
  |
4 |     println!('hello world ');
  |                          +

error[E0762]: unterminated character literal
 --> src/main.rs:4:26
  |
4 |     println!('hello world');
  |                          ^^^
```

### Desired output

```Shell
error: format argument must be a string literal
 --> src/main.rs:2:14
  |
4 |     println!('hello world');
  |              ^^^^^^^^^^^^^
  |
help: you might have intended a string literal
  |
4 |     println!("hello world");
  |              +++++++++++++
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
Given `'hello world'` and `'1 str', provide a structured suggestion for a valid string literal:

```
error[E0762]: unterminated character literal
  --> $DIR/lex-bad-str-literal-as-char-3.rs:2:26
   |
LL |     println!('hello world');
   |                          ^^^^
   |
help: if you meant to write a `str` literal, use double quotes
   |
LL |     println!("hello world");
   |              ~           ~
```
```
error[E0762]: unterminated character literal
  --> $DIR/lex-bad-str-literal-as-char-1.rs:2:20
   |
LL |     println!('1 + 1');
   |                    ^^^^
   |
help: if you meant to write a `str` literal, use double quotes
   |
LL |     println!("1 + 1");
   |              ~     ~
```

Fix #119685.

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler

**Review by fmease — COMMENTED** [review]
Looks good overall, thanks! I have a couple of minor suggestions and a question. And of course, the negative overflow needs to be fixed.

If I follow the code correctly, for `r'hello world'` (a meant-to-be *raw* string literal), we will still emit two errors (`` prefix `r` is unknown `` & `unterminated character literal`). It's probably fine as-is but we could also think about suppressing the unknown prefix error if feasible :thinking:

File: tests/ui/lexer/lex-bad-str-literal-as-char-3.rs
[the remark this answers is not in the document]
Comment (estebank) [reply tests/ui/lexer/lex-bad-str-literal-as-char-3.rs:1]: That is indeed the case. I didn't want to further complicate this PR with an attempt to deduplicate the errors.

File: tests/ui/lexer/lex-bad-str-literal-as-char-2.rs
[the remark this answers is not in the document]
Comment (estebank) [reply tests/ui/lexer/lex-bad-str-literal-as-char-2.rs:1]: The closest one to duplicating this case is the `println!('●●')` one, but I feel that having one for an unicode char and another for a whitespace is worthwhile keeping. Also, these are all separate files because lexer errors are early enough that the swallow later errors (so earlier lexer errors would silence later ones).

File: tests/ui/lexer/lex-bad-str-literal-as-char-3.rs
[the remark this answers is not in the document]
Comment (estebank) [reply tests/ui/lexer/lex-bad-str-literal-as-char-3.rs:1]: Done: added logic to silence the redundant case.

File: tests/ui/lexer/lex-bad-str-literal-as-char-3.rs [hunk 1]
```diff
@@ -1,4 +1,8 @@
-//@ run-rustfix
+//@ revisions: rust2015 rust2018 rust2021
+//@[rust2018] edition:2018
+//@[rust2021] edition:2021
 fn main() {
-    println!('hello world'); //~ ERROR unterminated character literal
+    println!('hello world');
+    //[rust2015,rust2018,rust2021]~^ ERROR unterminated character literal
```
Comment (fmease) [inline tests/ui/lexer/lex-bad-str-literal-as-char-3.rs:6]: Could be simplified to

```suggestion
    //~^ ERROR unterminated character literal
```

but not blocking.

File: compiler/rustc_lexer/src/cursor.rs [hunk 2]
```diff
@@ -59,6 +59,15 @@ impl<'a> Cursor<'a> {
         iter.next().unwrap_or(EOF_CHAR)
     }
 
+    /// Peeks the third symbol from the input stream without consuming it.
+    pub fn third(&self) -> char {
```
Comment (fmease) [inline compiler/rustc_lexer/src/cursor.rs:63]: Since `second` and `third` are exclusively used in the error path if I'm not mistaken (haven't double-checked), perf shouldn't matter that much and we can maybe avoid introducing those helpers? Idk, do we have access to `self.chars` in the parser? If so, we could just use `.clone().nth(N)`, right?

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 3]
```diff
@@ -715,7 +719,12 @@ impl<'psess, 'src> StringReader<'psess, 'src> {
             } else {
                 None
             };
-            self.dcx().emit_err(errors::UnknownPrefix { span: prefix_span, prefix, sugg });
+            let err = errors::UnknownPrefix { span: prefix_span, prefix, sugg };
+            if silence {
+                self.dcx().create_err(err).delay_as_bug();
+            } else {
+                self.dcx().emit_err(err);
+            }
```
Comment (fmease) [inline compiler/rustc_parse/src/lexer/mod.rs:727]: I would probably structure it a bit differently, namely `let err = create_err(); if silence { err.delay_as_bug() } else { err.emit() }` but that's just a difference in taste. Definitely not blocking.

File: compiler/rustc_parse/src/lexer/unescape_error_reporting.rs [hunk 4]
```diff
@@ -95,7 +95,7 @@ pub(crate) fn emit_unescape_error(
                     }
                     escaped.push(c);
                 }
-                if escaped.len() != lit.len() {
+                if escaped.len() != lit.len() || full_lit_span.is_empty() {
```
Comment (fmease) [inline compiler/rustc_parse/src/lexer/unescape_error_reporting.rs:98]: I understand that this prevents the negative overflow & that makes sense but why wasn't this an issue before? Don't have the time to dig deep into the code myself.

**Review by fmease — APPROVED** [review]
I have two questions, otherwise r=me with or without nits addressed at your convenience. Sorry for the delay :| and thanks for taking this on! :)

File: compiler/rustc_lexer/src/cursor.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_lexer/src/cursor.rs:63]: `self.chars` is private to the lexer. I initially made it public, but given it is used only in one place it felt better to introduce the method. But then we could instead just have an `nth` method that expands to `.clone().nth(N)` instead.

File: compiler/rustc_parse/src/lexer/unescape_error_reporting.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_parse/src/lexer/unescape_error_reporting.rs:98]: Before we were replacing the full span with the new string (instead of doing `BytePos` math). We just end up with an invalid suggestion that won't be displayed.

**Comment by fmease** [comment]
Okay, seems fine as is.

@bors r+ rollup
