### PR TITLE
rustdoc: Preserve rendering of macro_rules matchers when possible

### LINKED ISSUE #92331: rustdoc: Regression in whitespacing inside macro_rules matchers
```rust
#[macro_export]
macro_rules! repro {
    ($e:expr, std::path) => {};
}
```

### Before:

This preserves the spacing in the way that the macro author wrote, and exactly the way that they intend for the macro user to write those spaces on their end.

Screenshot from 2021-12-27 13-13-25

### After:

The person calling the macro needs to reverse engineer where to add/delete spaces in order to get a readable result.

Screenshot from 2021-12-27 13-13-46

I haven't bisected but it seems likely from skimming the implementation that this is related to #86282. Overall I think #86282 would tend to be net negative for the vast majority of macros. @camelid @jyn514 is there perhaps some other way to deal with the edge cases that didn't have proper source code for rustdoc to copy?

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #92331. This approach restores the behavior prior to #86282 **if** the matcher token held by the compiler **and** the matcher token found in the source code are identical TokenTrees. Thus #86208 remains fixed, but without regressing formatting for the vast majority of macros which are not macro-generated.

### CODE REVIEW

**Comment by jyn514** [comment]
I'm on vacation, @camelid is a good reviewer for this.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! Since @camelid wrote the original fix, I'll let them approve it to ensure I didn't miss something.

File: src/librustdoc/clean/utils.rs [hunk 1]
```diff
@@ -484,20 +486,67 @@ crate const DOC_RUST_LANG_ORG_CHANNEL: &str = env!("DOC_RUST_LANG_ORG_CHANNEL");
...
+        rustc_ast_pretty::pprust::tt_to_string(matcher)
+    }
+}
+
+/// Find the source snippet for this token's Span, reparse it, and return the
+/// snippet if the reparsed TokenTree matches the argument TokenTree.
+fn snippet_equal_to_token(cx: &DocContext<'_>, matcher: &TokenTree) -> Option<String> {
+    // Find what rustc thinks is the source snippet.
+    // This may not actually be anything meaningful if this matcher was itself
+    // generated by a macro.
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:516]: Can you add a test for what the output looks like with a macro generated by a macro?

File: src/librustdoc/clean/utils.rs [hunk 2]
```diff
@@ -484,20 +486,67 @@ crate const DOC_RUST_LANG_ORG_CHANNEL: &str = env!("DOC_RUST_LANG_ORG_CHANNEL");
...
+    if let Some(snippet) = snippet_equal_to_token(cx, matcher) {
+        snippet
+    } else {
+        rustc_ast_pretty::pprust::tt_to_string(matcher)
+    }
+}
+
+/// Find the source snippet for this token's Span, reparse it, and return the
+/// snippet if the reparsed TokenTree matches the argument TokenTree.
+fn snippet_equal_to_token(cx: &DocContext<'_>, matcher: &TokenTree) -> Option<String> {
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:513]: Can you make this take just a `TyCtxt`?

Comment (dtolnay) [reply src/librustdoc/clean/utils.rs]: :+1: fixed in 544a6bb7e72c907f05881ae7f461005cc5f92759.

File: src/librustdoc/clean/utils.rs (hunk 1 above)
Comment (dtolnay) [reply src/librustdoc/clean/utils.rs:516]: Yep, added 0f8415b8e1d93de7b6673298c9f10c709742d9ab. I have another PR coming up to make that look nicer too.

**Comment by camelid** [comment]
Looks like the bors try run was cancelled by the new commits.

@bors try @rust-timer queue

**Comment by camelid** [comment]
Perf looks neutral, which is good. I was concerned that the extra parsing would cause slowdowns, but it doesn't seem to.

File: src/librustdoc/clean/utils.rs [hunk 3]
```diff
@@ -484,20 +486,67 @@ crate const DOC_RUST_LANG_ORG_CHANNEL: &str = env!("DOC_RUST_LANG_ORG_CHANNEL");
...
+fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String> {
+    // Find what rustc thinks is the source snippet.
+    // This may not actually be anything meaningful if this matcher was itself
+    // generated by a macro.
+    let source_map = tcx.sess.source_map();
+    let span = matcher.span();
+    let snippet = source_map.span_to_snippet(span).ok()?;
+
+    // Create a Parser.
+    let sess = ParseSess::new(FilePathMapping::empty());
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:522]: Should we be inheriting the `FilePathMapping` that was originally used by rustc? Are there any negative side effects of using an empty file path mapping?

**Review by camelid — APPROVED** [review]
This looks good to me. The only real issues I can think of are
- that it won't fix the rendering of macros in the standard library since the lack of sources there triggered the switch to pretty-printing in the first place
- that it could include comments within the matcher that aren't meant to be user-visible (e.g., `($x:ident, /* my comment */ $y:ident) => {{ ... }}`).

But the first one doesn't make this change not worthwhile, and the second seems very unlikely to be an issue in practice, especially since rustdoc used to unconditionally display the source snippet.

File: src/librustdoc/clean/utils.rs (hunk 3 above)
Comment (dtolnay) [reply src/librustdoc/clean/utils.rs:522]: `FilePathMapping` has to do with rustc's `--remap-path-prefix FROM=TO` flag, which says that the real source files are located under FROM but compile-time diagnostics and run-time backtraces and std::panic::Location::caller().file() should all replace that prefix with TO instead. This lets you produce reproducible binaries from heterogeneous environments, and integrate certain kinds of code generators better.

None of that is relevant to this code, since we deliberately do not emit any diagnostics from this and only look at the real source files.

**Comment by camelid** [comment]
> that it could include comments within the matcher that aren't meant to be user-visible (e.g., `($x:ident, /* my comment */ $y:ident) => {{ ... }}`).

Do we think this is an issue? If not, `r=camelid,GuillaumeGomez`.

@GuillaumeGomez what do you think?

**Comment by dtolnay** [comment]
My opinion:

- Has anyone raised concern about that in the many years that rustdoc has worked this way? As I understand it, the change which resulted in concealing the comments was motivated by something else, and concealing the comments was just a side effect.

- I don't know that "aren't meant to be user-visible" is a supported use case. If the solution involves making the macro matchers rendered by rustdoc less readable or less copyable into a macro invocation with idiomatic spacing as intended by the macro author, then readers of the rustdoc will just click the \[src\] link to find the more readable original form, and will encounter the comment there anyway.

**Comment by camelid** [comment]
Ok, seems good to me then.

@bors r=camelid,GuillaumeGomez rollup=iffy
