### PR TITLE
Fix `range_covered_by_constructor` for exclusive ranges.

### LINKED ISSUE #43253: Wrong compiler warning with exclusive_range_pattern feature
```
#![feature(exclusive_range_pattern)]

fn main() {
    let a: u8 = 11;
    match a {
        1..11 => println!("1 to 10"),
        11 => println!("11"),          // warning: unreachable pattern
        _ => println!("else"),        
    };
}
```
With rust nightly compiler, the result on the screen is `11` even though the compiler warning that 11 case is unreachable.

Link to rust playground: https://play.rust-lang.org/?gist=a3c8f0a3cfa3209a52992aedf9220720&version=nightly

### PR DESCRIPTION
**Pull request by feadoor**
This resolves #43253

### CODE REVIEW

File: src/librustc_const_eval/_match.rs [hunk 1]
```diff
@@ -835,7 +835,7 @@ fn slice_pat_covered_by_constructor(_tcx: TyCtxt, _span: Span,
     Ok(true)
 }
 
-fn range_covered_by_constructor(tcx: TyCtxt, span: Span,
+fn constructor_covered_by_range(tcx: TyCtxt, span: Span,
                                 ctor: &Constructor,
                                 from: &ConstVal, to: &ConstVal,
```
Comment (nikomatsakis) [inline src/librustc_const_eval/_match.rs]: Nit: pre-existing, can you can make this one argument per line?

**Review by nikomatsakis — APPROVED** [review]
Looks good. =)
