### PR TITLE
Save/restore more items in cache with incremental compilation

### LINKED ISSUE #88829: --emit=llvm-bc in workspaces
```
$ export CARGO_INCREMENTAL=1
$ cargo clean
$ cargo rustc -p header -- --emit=llvm-bc
   Compiling header v0.1.0 (/media/media/rust/plugins3/header)
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
$ cargo rustc -p plugin -- --emit=llvm-bc
   Compiling header v0.1.0 (/media/media/rust/plugins3/header)
   Compiling plugin v0.1.0 (/media/media/rust/plugins3/plugin)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
$ cargo rustc -p header -- --emit=llvm-bc
   Compiling header v0.1.0 (/media/media/rust/plugins3/header)
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
$ cargo rustc -p plugin -- --emit=llvm-bc
   Compiling header v0.1.0 (/media/media/rust/plugins3/header)
   Compiling plugin v0.1.0 (/media/media/rust/plugins3/plugin)
error: could not copy "/media/media/rust/plugins3/target/debug/deps/plugin-b8dfbf0a2496ce43.1qo0jbf99rserog8.rcgu.bc" to "/media/media/rust/plugins3/target/debug/deps/plugin-b8dfbf0a2496ce43.bc": No such file or directory (os error 2)

error: could not compile `plugin` due to previous error
$ rustc --version
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```

I have a git repo that can easily demonstrate this issue; see `incr-test` in [this repo](https://github.com/purpleposeidon/plugins3/commit/f1f9106a23757dba2e88a240c1aba65abf11fc9f).

It doesn't happen w/o incremental compilation.

(Search terms: --emit emit --emit=llvm-bc --emit=llvm-ir llvm-bc llvm-ir)

### LINKED ISSUE #89149: Failure on subsequent builds when `--emit asm` used without `-C save-temps`.
I tried this code:

(see attached project)
[buildfailure-1.zip](https://github.com/rust-lang/rust/files/7204014/buildfailure-1.zip)

```
cargo build --bin=nucleof446re --target=thumbv7m-none-eabi --features="dep-stm32f446" -vv
...
cargo build --bin=nucleof446re --target=thumbv7m-none-eabi --features="dep-stm32f446" -vv
```

I expected to see this happen:

build the first time, build the second time.

Instead, this happened: *explanation*

On the first build, success.
On the second build
```
error: could not copy "D:\\Users\\Hydra\\Documents\\dev\\playground\\rust\\buildfailure-1\\crates\\boards\\target\\thumbv7m-none-eabi\\debug\\deps\\boards-381a71c28462db46.19nwjvde6m7mbrbk.rcgu.s" to "D:\\Users\\Hydra\\Documents\\dev\\playground\\rust\\buildfailure-1\\crates\\boards\\target\\thumbv7m-none-eabi\\debug\\deps\\boards-381a71c28462db46.s": The system cannot find the file specified. (os error 2)
```

See log (attached)

[log.txt](https://github.com/rust-lang/rust/files/7204018/log.txt)

Upon investigation it appears that the rustflags (in the cargo configuration) `--emit asm` cause the subsequent build failure, but only when `-C save-temps` is *NOT* used.

i.e:

savetemps | emit asm | result
----------- | --------- | ------
disabled | disabled | success
enabled | disabled | success
disabled | enabled | failure
enabled | enabled | success

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (5ecc8ad84 2021-09-19)
binary: rustc
commit-hash: 5ecc8ad8462574354a55162a0c16b10eb95e3e70
commit-date: 2021-09-19
host: x86_64-pc-windows-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by pacak**
Right now they don't play very well together, consider a simple example:

```
$ export RUSTFLAGS="--emit asm"
$ cargo new --lib foo
     Created library `foo` package
$ cargo build -q
$ touch src/lib.rs
$ cargo build
error: could not copy 
  "/path/to/foo/target/debug/deps/foo-e307cc7fa7b6d64f.4qbzn9k8mosu50a5.rcgu.s" 
  to "/path/to/foo/target/debug/deps/foo-e307cc7fa7b6d64f.s": 
  No such file or directory (os error 2)
```

Touch triggers the rebuild, incremental compilation detects no changes (yay) and everything explodes while trying to copy files were they should go.

This pull request fixes it by copying and restoring more files in the incremental compilation cache

Fixes https://github.com/rust-lang/rust/issues/89149
Fixes https://github.com/rust-lang/rust/issues/88829

Related: https://internals.rust-lang.org/t/interaction-between-incremental-compilation-and-emit/20551

### CODE REVIEW

**Comment by Nadrieril** [comment]
r? compiler

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 1]
```diff
@@ -96,6 +108,10 @@ pub struct CompiledModule {
     pub object: Option<PathBuf>,
     pub dwarf_object: Option<PathBuf>,
     pub bytecode: Option<PathBuf>,
+
+    /// items created to satisfy --emit
+    pub asm: Option<PathBuf>, // --emit=asm
+    pub llvm: Option<PathBuf>, // --emit=llvm-ir, llvm-bc is in bytecode
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/lib.rs:114]: Maybe call this field llvm_ir instead?

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 2]
```diff
@@ -96,6 +108,10 @@ pub struct CompiledModule {
     pub object: Option<PathBuf>,
     pub dwarf_object: Option<PathBuf>,
     pub bytecode: Option<PathBuf>,
+
+    /// items created to satisfy --emit
+    pub asm: Option<PathBuf>, // --emit=asm
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/lib.rs:113]: Maybe call this field assembly instead?

File: tests/run-make/asm-incr-cache/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,30 @@
+//@ only-x86_64-unknown-linux-gnu
```
Comment (bjorn3) [inline tests/run-make/asm-incr-cache/rmake.rs:1]: Why is this limited to x86_64 linux? Nothing in this test looks to be platform dependent.

File: tests/run-make/asm-incr-cache/rmake.rs [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    rustc()
+        .input("lib.rs")
+        .arg("--emit=obj,asm,dep-info,link,mir,llvm-ir,llvm-bc")
+        .arg("--crate-type=lib")
+        .arg(format!("-Cincremental={inc_dir:?})").as_str())
+        .run();
+
+    {
+        let lib = std::fs::File::options().write(true).open("lib.rs").expect("No lib.rs");
+        lib.set_modified(std::time::SystemTime::now());
```
Comment (bjorn3) [inline tests/run-make/asm-incr-cache/rmake.rs:19]: Rustc doesn't look at the mtime. Only cargo does.

Comment (pacak) [reply tests/run-make/asm-incr-cache/rmake.rs:19]: Good to know. I only copied what existing test did (along with deprecated Makefile) and it was necessary to replicate the bug using cargo.

File: compiler/rustc_codegen_ssa/src/lib.rs (hunk 1 above)
Comment (pacak) [reply compiler/rustc_codegen_ssa/src/lib.rs]: Done, and `assembly` as well.

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 3 above)
Comment (pacak) [reply tests/run-make/asm-incr-cache/rmake.rs]: Good question, probably from the test I adopted. Removed, let's see.

File: tests/run-make/asm-incr-cache/rmake.rs [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+
+use run_make_support::{rustc, tmp_dir};
+
+fn main() {
+    let inc_dir = tmp_dir();
+
+    for _ in 0..=1 {
+        rustc()
+            .input("lib.rs")
+            .arg("--emit=obj,asm,dep-info,link,mir,llvm-ir,llvm-bc")
```
Comment (jieyouxu) [inline tests/run-make/asm-incr-cache/rmake.rs:11]: Consider introducing some helpers:

```rs
rustc()
    .emit("obj,asm,...")
    .crate_type("lib")
    .incremental(inc_dir) // takes a <P: AsRef<Path>>
```

Comment (pacak) [reply tests/run-make/asm-incr-cache/rmake.rs:11]: I added helpers here - https://github.com/rust-lang/rust/pull/122597 so it will be fixed after it is merged.

File: tests/run-make/asm-incr-cache/rmake.rs [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+            .arg("--crate-type=lib")
+            .arg(format!("-Cincremental={}", inc_dir.to_str().expect("temp dir?")).as_str())
```
Comment (fmease) [inline tests/run-make/asm-incr-cache/rmake.rs:13]: Could we float the `to_str().expect()` out of the loop? Furthermore, could you change the panic message to say sth. akin to “tmpdir path isn't valid utf-8”.

Ideally, `run-make-support`'s `.arg()` would take `impl AsRef<OsStr>` instead of `&str` so we won't panic on machines where the `TMPDIR` is not valid UTF-8 (unlikely but not impossible). @jieyouxu what do you think?

File: compiler/rustc_codegen_ssa/src/back/write.rs [hunk 7]
```diff
@@ -533,7 +533,15 @@ fn copy_all_cgu_workproducts_to_incr_comp_cache_dir(
...
         }
-
+        if let Some(path) = &module.assembly {
+            files.push(("s", path.as_path()));
+        }
+        if let Some(path) = &module.llvm_ir {
+            files.push(("ll", path.as_path()));
+        }
+        if let Some(path) = &module.bytecode {
+            files.push(("bc", path.as_path()));
```
Comment (fmease) [inline compiler/rustc_codegen_ssa/src/back/write.rs:543]: Minor style nit:

```suggestion
            files.push((OutputType::Assembly.extension(), path.as_path()));
        }
        if let Some(path) = &module.llvm_ir {
            files.push((OutputType::LlvmAssemble.extension(), path.as_path()));
        }
        if let Some(path) = &module.bytecode {
            files.push((OutputType::Bitcode.extension(), path.as_path()));
```

I know that we currently don't use `OutputType::Object.extension()` for the `object_file_path` but well ^^

File: compiler/rustc_codegen_ssa/src/back/write.rs [hunk 8]
```diff
@@ -937,12 +945,47 @@ fn execute_copy_from_cache_work_item<B: ExtraBackendMethods>(
             load_from_incr_comp_dir(dwarf_obj_out, saved_dwarf_object_file)
         });
 
+    let assembly = module_config
+        .emit_asm
+        .then(|| {
+            module.source.saved_files.get("s").as_ref().and_then(|saved_asm_file| {
```
Comment (fmease) [inline compiler/rustc_codegen_ssa/src/back/write.rs:951]: same here and the cases below, we could use `OutputType::TYPE.extension()`

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 6 above)
Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:13]: > Ideally, `run-make-support`'s `.arg()` would take `impl AsRef<OsStr>` instead of `&str` so we won't panic on machines where the `TMPDIR` is not valid UTF-8 (unlikely but not impossible).

I think that makes sense yes. But in this case, we should also provide convenience APIs to avoid annoying `OsString` constructions methinks.

So if we change `arg`, we should also change `args`

```rs
impl Rustc {
    pub fn arg<S: AsRef<OsStr>>(&mut self, val: S) -> &mut Self { ... }
    pub fn args<S: AsRef<OsStr>>(&mut self, val: &[S]) -> &mut Self { ... }
}
```

and provide a convenience method for incremental here that constructs the suitable `-Cincremental={}` with `OsString` so the test-writer doesn't have to:

```rs
impl Rustc {
    pub fn incremental<P: AsRef<Path>>(&mut self, path: P) -> &mut Self {
        let mut arg = OsString::new();
        arg.push("-Cincremental=");
        arg.push(path.as_ref())
        self.cmd.arg(&arg);
        self
    }
}
```

With this API, this test can just write

```rs
rustc()
    // lines omitted
    .incremental(&tmp_dir())
```

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 9]
```diff
@@ -96,6 +109,10 @@ pub struct CompiledModule {
     pub object: Option<PathBuf>,
     pub dwarf_object: Option<PathBuf>,
     pub bytecode: Option<PathBuf>,
+
+    /// items created to satisfy --emit
```
Comment (fmease) [inline compiler/rustc_codegen_ssa/src/lib.rs:113]: This doc comment only documents the first field, not both. Either turn this into a normal comment or drop it entirely (it's not *super* useful imho).

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 6 above)
Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:13]: > Could we float the `to_str().expect()` out of the loop? Furthermore, could you change the panic message to say sth. akin to “tmpdir path isn't valid utf-8”.

Also, with the `incremental()` API, we don't need the `expect()` or `to_str()` at all.

File: tests/run-make/asm-incr-cache/lib.rs
Comment (fmease) [inline tests/run-make/asm-incr-cache/lib.rs:1]: the name `asm-incr-cache` is a bit misleading since we're not just testing the tracking of `--emit=asm`.

**Review by fmease — APPROVED** [review]
Thanks! Overall looks good. I have a couple of minor nitpicks

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 6 above)
Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:13]: Actually I realized that @pacak *did* introduce `incremental()` helper -- in another PR #122597 (mentioned in previous resolved comment <https://github.com/rust-lang/rust/pull/123221#discussion_r1546824858>). IIUC, @pacak wanted to merge this PR first? So if we could move the helper to this PR and change the `arg`/`args` signatures, that'd be great ^^

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 5 above)
Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:11]: Actually, can you move those helper into this PR, as IIUC you would like this PR to be merged before #122597?

File: tests/run-make/asm-incr-cache/rmake.rs [hunk 10]
```diff
@@ -0,0 +1,16 @@
+extern crate run_make_support;
```
Comment (jieyouxu) [inline tests/run-make/asm-incr-cache/rmake.rs:1]: Could you add a comment and some references for this test? I think you added in the other PR which depends on this to get merged first?

```
// rustc should be able to emit required files (asm, llvm-*, etc) during incremental
// compilation on the first pass by running the code gen as well as on subsequent runs -
// extracting them from the cache
//
// Fixes: rust-lang/rust#89149
// Fixes: rust-lang/rust#88829
// Also see discussion at <https://internals.rust-lang.org/t/interaction-between-incremental-compilation-and-emit/20551>.
```

This helps anyone who's trying to debug test failures out a ton.

**Review by jieyouxu — APPROVED** [review]
The run-make test and support library changes look good to me, just left some minor nits 👍

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 5 above)
Comment (pacak) [reply tests/run-make/asm-incr-cache/rmake.rs:11]: > Actually, can you move those helper into this PR, as IIUC you would like this PR

Correct, this PR fixes a bug, #122597 introduces new behavior that relies on this bug being fixed. I also asked if new helpers should go somewhere else :) But sure, will move along with all the suggested changes to the API.

Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:11]: > I also asked if new helpers should go somewhere else :)

My bad, I thought in the dependent PR by "a separate PR" you meant *yet another PR* and not *this* PR, which is why I said it's fine to keep it in the dependent PR.

File: tests/run-make/asm-incr-cache/lib.rs
Comment (pacak) [reply tests/run-make/asm-incr-cache/lib.rs:1]: We are testing if asm can be produced during incremental compilation from cache. I'm open to renaming if you have any suggestions. FWIW original version tested just asm, but then https://github.com/rust-lang/rust/issues/123234 happened, so now it emits all the things.

Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/lib.rs:1]: Would "artifacts" be accurate instead of asm here?

File: tests/run-make/asm-incr-cache/rmake.rs (hunk 6 above)
Comment (pacak) [reply tests/run-make/asm-incr-cache/rmake.rs:13]:
```rust
impl Rustc {
    pub fn arg<S: AsRef<OsStr>>(&mut self, val: S) -> &mut Self { ... }
    pub fn args<S: AsRef<OsStr>>(&mut self, val: &[S]) -> &mut Self { ... }
}
```

I'm about to do some black magic to ensure this assert still works with `OsStr`
```rust
        assert!(                                                                                                                                                                                                                               
            !(["-Z", "-C"].contains(&arg) || arg.starts_with("-Z ") || arg.starts_with("-C ")),                                                                                                                                                
            "use `-Zarg` or `-Carg` over split `-Z` `arg` or `-C` `arg`"                                                                                                                                                                       
        );                                                                                   
```

Comment (jieyouxu) [reply tests/run-make/asm-incr-cache/rmake.rs:13]: Can you just remove that assert? Just make sure the recommendation is documented on the method.

File: src/tools/run-make-support/src/rustc.rs [hunk 11]
```diff
@@ -94,13 +121,7 @@ impl Rustc {
...
 
     /// Generic command argument provider. Use `.arg("-Zname")` over `.arg("-Z").arg("arg")`.
-    /// This method will panic if a plain `-Z` or `-C` is passed, or if `-Z <name>` or `-C <name>`
-    /// is passed (note the space).
-    pub fn arg(&mut self, arg: &str) -> &mut Self {
-        assert!(
-            !(["-Z", "-C"].contains(&arg) || arg.starts_with("-Z ") || arg.starts_with("-C ")),
-            "use `-Zarg` or `-Carg` over split `-Z` `arg` or `-C` `arg`"
-        );
+    pub fn arg<S: AsRef<>(&mut self, arg: S) -> &mut Self {
```
Comment (jieyouxu) [inline src/tools/run-make-support/src/rustc.rs:124]: Typo :3

Comment (pacak) [reply src/tools/run-make-support/src/rustc.rs]: Not having proper rust-analyzer running all the time and slow `./x check` is painful.

**Comment by pacak** [comment]
:tada:

**Comment by fmease** [comment]
Thanks!

@bors r=fmease,jieyouxu
