### PR TITLE
Consider methods on fundamental `impl` when method is not found on numeric type

### LINKED ISSUE #47759: Mediocre error message for f32/f64 ambiguity
I have this code:
```
    let _ = |x: f64| x * 2.0.exp();
```
https://play.rust-lang.org/?gist=58e23173aec4b798d8021af0ead25bbd&version=nightly

I get this error message:
```
error[E0599]: no method named `exp` found for type `{float}` in the current scope
```

I can work around by:
```
    let _ = |x: f64| x * 2.0f64.exp();
```

The world would be a better place if:
* Type inference could just figure out 2.0 has to be f64 given the type on `x`
* Failing that, an error message indicating the problem is f32 vs f64 ambiguity rather than this mysterious `{float}` thing

### PR DESCRIPTION
**Pull request by estebank**
Fix #47759.

### CODE REVIEW

File: src/librustc_typeck/check/method/suggest.rs [hunk 1]
```diff
@@ -271,11 +271,35 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                     let mut candidates = all_traits(self.tcx).into_iter().filter_map(|info| {
                         self.associated_item(info.def_id, item_name, Namespace::ValueNS)
                     });
-                    if let (true, false, SelfSource::MethodCall(expr), Some(_)) = (
+                    // There are methods that are defined on the fundamental types and won't be
```
Comment (matthewjasper) [inline src/librustc_typeck/check/method/suggest.rs:274]:
```suggestion
                    // There are methods that are defined on the primitive types and won't be
```
I was initially confused thinking that this was about `#[fundamental]`

**Review by matthewjasper — COMMENTED** [review]
r=me with terminology changed
