### PR TITLE
Suggest `pin!()` instead of `Pin::new()` when appropriate

### LINKED ISSUE #57994: Unhelpful error message when using bad receiver type
Consider the following piece of code:
```rust
use std::pin::Pin;

trait Test {
    fn test(self: Pin<&mut Self>);
}

fn foo(t: impl Test) {
    t.test()
}
```
The error here is that `test` can only be called on `Pin<&mut Self>`, so `t.test` does not work. But the error message is less than helpful:
```
error[E0599]: no method named `test` found for type `impl Test` in the current scope
 --> src/lib.rs:8:7
  |
8 |     t.test()
  |       ^^^^
  |
  = help: items from traits can only be used if the trait is implemented and in scope
  = note: the following trait defines an item `test`, perhaps you need to implement it:
          candidate #1: `Test`
```
It suggests I import a trait that is already in scope.  This leads down the totally wrong path -- not showing the "help" and "note" at all would be better than this.  Ideally it could point out the receiver type mismatch.

### PR DESCRIPTION
**Pull request by estebank**
When encountering a type that needs to be pinned but that is `!Unpin`, suggest using the `pin!()` macro.

Fix #57994.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -2532,6 +2547,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         }
                     }
                 }
+                // We special case the situation where `Pin::new` wouldn't work, and isntead
```
Comment (davidtwco) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2550]: It's obviously pre-existing, but could you move some of these individual suggestions into their own functions, there's _a lot_ going on in this one function.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 2]
```diff
@@ -2532,6 +2547,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                // suggest using the `pin!()` macro instead.
+                if let Some(new_rcvr_t) = Ty::new_lang_item(self.tcx, *rcvr_ty, LangItem::Pin)
+                    && !alt_rcvr_sugg
+                    && !unpin
+                    && sym::as_ref != item_name.name
+                    && *pin_call != ""
```
Comment (davidtwco) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2556]: Could you add some comments for these conditions justifying them? 

Saves future readers having to work out why some of these checks are necessary for the suggestion - e.g.
"check the item isn't `as_ref`, it wouldn't make sense with that because..."

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 3]
```diff
@@ -2448,10 +2448,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             // Try alternative arbitrary self types that could fulfill this call.
             // FIXME: probe for all types that *could* be arbitrary self-types, not
             // just this list.
-            for (rcvr_ty, post) in &[
-                (rcvr_ty, ""),
-                (Ty::new_mut_ref(self.tcx, self.tcx.lifetimes.re_erased, rcvr_ty), "&mut "),
-                (Ty::new_imm_ref(self.tcx, self.tcx.lifetimes.re_erased, rcvr_ty), "&"),
+            for (rcvr_ty, post, pin_call) in &[
```
Comment (davidtwco) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2451]: Could `pin_call` be `Option<&'static str>` rather than checking for `""` below?

**Review by davidtwco — CHANGES_REQUESTED** [review]
I like this change, left a handful of comments :)

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: I'll try to clean this method up in a few days.

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Apologies for taking so long to get back to this.

@bors r+
