### PR TITLE
syntax: Make parsing of paths whitespace agnostic + some other changes

### LINKED ISSUE #14109: `use super :: A` does not parse
```rust
pub struct A;

mod test {
    use super :: A;
}
```

```
foo.rs:4:9: 4:14 error: found `super` in ident position                               
foo.rs:4     use super :: A;                                                          
                 ^~~~~                                                                
error: aborting due to previous error                                                 
```

### PR DESCRIPTION
**Pull request by petrochenkov**
Paths are mostly parsed without taking whitespaces into account, e.g. `std :: vec :: Vec :: new ()` parses successfully, however, there are some special cases involving keywords `super`, `self` and `Self`. For example, `self::` is considered a path start only if there are no spaces between `self` and `::`. These restrictions probably made sense when `self` and friends weren't keywords, but now they are unnecessary.

The first two commits remove this special treatment of whitespaces by removing `token::IdentStyle` entirely and therefore fix https://github.com/rust-lang/rust/issues/14109.
This change also affects naked `self` and `super` (which are not tightly followed by `::`, obviously) they can now be parsed as paths, however they are still not resolved correctly in imports (cc @jseyfried, see `compile-fail/use-keyword.rs`), so https://github.com/rust-lang/rust/issues/29036 is not completely fixed.

The third commit also makes `super`, `self`, `Self` and `static` keywords nominally (before this they acted as keywords for all purposes) and removes most of remaining "special idents".

The last commit (before tests) contains some small improvements - some qualified paths with type parameters are parsed correctly, `parse_path` is not used for parsing single identifiers, imports are sanity checked for absence of type parameters - such type parameters can be generated by syntax extensions or by macros when https://github.com/rust-lang/rust/issues/10415 is fixed (~~soon!~~already!).

This patch changes some pretty basic things in `libsyntax`, like `token::Token` and the keyword list, so it's a plugin-[breaking-change].

r? @eddyb

### CODE REVIEW

File: src/libsyntax/parse/token.rs [hunk 1]
```diff
@@ -436,122 +383,85 @@ macro_rules! last {
...
-        (super::SELF_TYPE_KEYWORD_NAME_NUM, type_self,       "Self");
-        (11,                         prelude_import,         "prelude_import");
-        (12,                         DEFAULT,                "default");
+        // Special identifiers
+        (0,                          Invalid,        "");
+        (1,                          __Unused1,      "<__unused1>");
+        (2,                          __Unused2,      "<__unused2>");
+        (3,                          __Unused3,      "<__unused3>");
+        (4,                          __Unused4,      "<__unused4>");
+        (5,                          __Unused5,      "<__unused5>");
```
Comment (eddyb) [inline src/libsyntax/parse/token.rs]: Can we remove all of these? And replace `special_idents` with "non-strict keywords"?

Comment (petrochenkov) [inline src/libsyntax/parse/token.rs]: Yeah, I just wanted to leave some free space so the diff is not messed up on every new contextual keyword, but it's not so important I suppose.
Also, naming is hard, what is the short and obvious name to use instead of `special_idents`? `weak_keywords` maybe? Also, `""` doesn't even look like a keyword!

Comment (eddyb) [inline src/libsyntax/parse/token.rs]: Well, I wouldn't even have a name. I'd just put all of them in the same bag, and just auto-generate the `STRICT_KEYWORD_{START,END}` from the list, with `'strict` still there.

**Comment by petrochenkov** [comment]
@eddyb 
I've updated the PR.
Keywords and special idents are merged together and the keyword generating macro is simplified.
The "bounds" for strict/reserved keywords are written manually now, but I'd say it's less error prone than the previous macro shenanigans.
The second commit contains some other small changes, see the commit message for description.

**Comment by eddyb** [comment]
LGTM, very nice! @nrc @erickt @Manishearth, any objections?

**Comment by nrc** [comment]
Should be breaking-batch, rather than being landed directly. But I think we should try to land it soon so it doesn't rot. cc @Manishearth

**Comment by nrc** [comment]
LGTM

**Comment by Manishearth** [comment]
We don't have any other breaking-batch changes queued up, but this is large enough that it can be landed directly. Let's wait a few days for the stakeholders to prepare for this, and land it then.

(In the meantime, if you have any breaking changes planned, now is the time to make PRs!)

**Comment by Manishearth** [comment]
Left a comment on #31645, feel free to land in a few days

**Comment by Manishearth** [comment]
Please land this simultaneously with https://github.com/rust-lang/rust/pull/31414 . I'll do it myself in a day or two if both get approved.

**Comment by petrochenkov** [comment]
I've pushed one more commit.
It makes `is_path_start` precise and fixes some error message regression caused by that.

**Comment by Manishearth** [comment]
Is this ready to land? (two LGTMs, seems good) Just mention r=me, don't actually tell bors to approve it.

**Comment by nrc** [comment]
@Manishearth  r=me

**Comment by petrochenkov** [comment]
@Manishearth 
I've rebased this PR, added https://github.com/rust-lang/rust/pull/33157 to it and regenerated the failing keyword parsing tests.
