### PR TITLE
Fix ICE with unresolved associated items in closures (fixes #28971)

### LINKED ISSUE #28971: ICE after error in associated item resolution
```rust
enum Foo {
    Bar(u8)
}
fn main(){
    foo(|| {
        match Foo::Bar(1) {
            Foo::Baz(..) => (), //~ ERROR no associated
            _ => (),
        }
    });
}

fn foo<F>(f: F) where F: FnMut() {
    f();
}
```

on `rustc 1.5.0-nightly (9d3e79ad3 2015-10-10)` gives an ICE:

```
 rustc on-the-rocks.rs 
on-the-rocks.rs:7:13: 7:25 error: no associated item named `Baz` found for type `Foo` in the current scope
on-the-rocks.rs:7             Foo::Baz(..) => (), //~ ERROR no associated
                              ^~~~~~~~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: DefIndex(4) => Foo }, true), last_private: LastMod(AllPublic), depth: 1 }', ../src/librustc/middle/def.rs:83
```

I'm working on a fix.

### PR DESCRIPTION
**Pull request by Manishearth**
r? @eddyb or @nrc

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm not sure if this is the right approach. Copying over my comment from the issue:

Either we need to abort_if_errors when creating the closure EUV in typeck/check/upvar.rs, in analyze_closure(), OR we need to abort in check_path_enum in _match.rs.

abort_if_errors means that it may not finish checking the whole crate, so the errors will get cut off. We need to determine where it's acceptable to cut it off.

Is there a smarter way to handle this? Perhaps by propagating a TyError or something?

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -586,9 +586,13 @@ pub fn check_pat_enum<'a, 'tcx>(pcx: &pat_ctxt<'a, 'tcx>,
...
                                                                 pat.span, pat.id) {
         Some(resolution) => resolution,
-        // Error handling done inside resolve_ty_and_def_ufcs, so if
-        // resolution fails just return.
-        None => {return;}
+        None => {
+            // Error handling done inside resolve_ty_and_def_ufcs
+            // Later parts of typeck need everything to be fully resolved,
+            // if it isn't, we should bail
+            tcx.sess.abort_if_errors();
```
Comment (eddyb) [inline src/librustc_typeck/check/_match.rs]: I don't like this. Can't we do better?
