### PR TITLE
Extend format arg help for simple tuple index access expression

### LINKED ISSUE #122535: Unclear error message when using . in format string
I tried this code:

```rust
    let x = (1, 2, 3);
    println!("{x.0}",);
```

I expected to see this happen: printing of the value 1.

Instead, this happened: it gave the following error:

> invalid format string: expected `'}'`, found `'.'`
if you intended to print `{`, you can escape it using `{{`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fhome%2FalonPc%2FDesktop%2Fprojects%2FRustLearning%2Fvariables%2Fsrc%2Fmain.rs)

### Meta

`rustc --version --verbose`:
```
1.76.0
```

### PR DESCRIPTION
**Pull request by jieyouxu**
The help is only applicable for simple field access `a.b` and (with this PR) simple tuple index access expressions `a.0`.

Closes #122535.

### CODE REVIEW

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -925,6 +925,18 @@ impl<'a> Parser<'a> {
                             suggestion: Suggestion::UsePositional,
                         },
                     );
+                } else if let ArgumentIs(_) = field.position {
```
Comment (compiler-errors) [inline compiler/rustc_parse_format/src/lib.rs:928]: Can you make this into an exhaustive match on `field.position` rather than two `if let`s?

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse_format/src/lib.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_parse_format/src/lib.rs]: Changed it to use match.
