### PR TITLE
Suggest parentheses when a struct literal needs them

### LINKED ISSUE #47360: Confusing error when using a struct literal as an iterator
```rust
fn main() {
    for _ in std::ops::Range { start: 0, end: 10 } {}
}

// error: expected type, found `0`
//  --> src/main.rs:2:39
//   |
// 2 |     for _ in std::ops::Range { start: 0, end: 10 } {}
//   |                                       ^ expecting a type here because of type ascription

// error[E0423]: expected value, found struct `std::ops::Range`
//  --> src/main.rs:2:14
//   |
// 2 |     for _ in std::ops::Range { start: 0, end: 10 } {}
//   |              ^^^^^^^^^^^^^^^ did you mean `std::ops::Range { /* fields */ }`?
```

It's confusing here, as it suggests using exactly what the user has typed. It should instead suggest the user parenthesise the struct literal.
(There's probably a reason this doesn't parse as-is, but if not, it seems like a nice case to handle.)

### PR DESCRIPTION
**Pull request by estebank**
When writing a struct literal in an expression that expects a block to
be started afterwards (like an `if` statement), do not suggest using the
same struct literal:

```
did you mean `S { /* fields * /}`?
```

Instead, suggest surrounding the expression with parentheses:

```
did you mean `(S { /* fields * /})`?
```

Fix #47360, #50090. Leaving #42982 open to come back to this problem with a better solution.

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -2934,8 +2934,38 @@ impl<'a> Resolver<'a> {
                                                               here due to private fields"));
                             }
                         } else {
-                            err.span_label(span, format!("did you mean `{} {{ /* fields */ }}`?",
-                                                         path_str));
+                            // HACK(estebank): find a better way to figure out that this was a
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: This is .. certainly a hack. I don't know what would be the best way to handle it, though; we have an `id`, so if we had the AST on hand we could find the context for this path by -- at worst -- walking through it. I'm not sure if there is a "map" for the AST that lets you find out (e.g.) the parent node?

That said, this function is invoked (iirc) via a visit walk, so perhaps we could add some kind of "context" parameter and thread the information down.

Comment (estebank) [reply src/librustc_resolve/lib.rs]: The problem is that the AST is already incorrect. I would like to modify the parser to accept struct literals in these positions to minimize errors being shown and include the suggestion then, but wanted to have a quick solution until then as this is a problem I've seen crop up multiple times on the issue tracker and in the forums.

Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: Well, my point regarding hack was not the approach of making a suggestion, which makes sense to me, but rather using the spans etc.

Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: OK, re-reading this diff, I see I was a bit confused about what was going on. This now seems more reasonable than I thought at first. =)

File: src/test/ui/error-codes/E0423.stderr [hunk 2]
```diff
@@ -1,9 +1,48 @@
...
+   |                                       ^ expecting a type here because of type ascription
+
 error[E0423]: expected function, found struct `Foo`
   --> $DIR/E0423.rs:14:13
    |
 LL |     let f = Foo(); //~ ERROR E0423
-   |             ^^^ did you mean `Foo { /* fields */ }`?
+   |             ^^^
+   |             |
+   |             did you mean `foo`?
```
Comment (nikomatsakis) [inline src/test/ui/error-codes/E0423.stderr]: I find this new test confusing -- it seems to combine a bunch of stuff that's hard to sort out. It took me a while to see that, by adding `foo`, you triggered a new suggestion here, for example. Perhaps it'd be better to make a new test file (or even multiple new files)? (Or did you intentionally want to demonstrate this interaction / cover all these cases simultaneously?)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Maybe break up the test? r=me either way
