### PR TITLE
[NLL] Get Polonius borrow check to work in simple cases

### LINKED ISSUE #54212: polonius liveness facts not implemented yet
when compiling unicode-xid v0.1.0 with `rustc 1.30.0-nightly (7061b2775 2018-08-28)` and compiler flags: `-Z external-macro-backtrace -Z borrowck=mir -Z polonius`, the compiler panicked.

```
error: internal compiler error: librustc_mir/borrow_check/nll/type_check/liveness/trace.rs:531: polonius liveness facts not implemented yet

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: <rustc::ty::fold::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::any_free_region_meets::RegionVisitor<F> as rustc::ty::fold::TypeVisitor<'tcx>>::visit_region
  15: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_visit_with
  16: rustc_mir::borrow_check::nll::type_check::liveness::generate
  17: rustc_mir::borrow_check::nll::type_check::type_check
  18: rustc_mir::borrow_check::nll::compute_regions
  19: rustc_mir::borrow_check::do_mir_borrowck
  20: rustc::ty::context::GlobalCtxt::enter_local
  21: rustc_mir::borrow_check::mir_borrowck
  22: rustc::ty::query::__query_compute::mir_borrowck
  23: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  27: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  28: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  29: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  30: rustc::util::common::time
  31: rustc::ty::context::tls::enter_context
  32: <std::thread::local::LocalKey<T>>::with
  33: rustc::ty::context::TyCtxt::create_and_enter
  34: rustc_driver::driver::compile_input
  35: rustc_driver::run_compiler_with_pool
  36: <scoped_tls::ScopedKey<T>>::set
  37: rustc_driver::run_compiler
  38: syntax::with_globals
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  40: rustc_driver::run
  41: rustc_driver::main
  42: std::rt::lang_start::{{closure}}
  43: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  45: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  46: main
  47: __libc_start_main
  48: <unknown>
query stack during panic:
#0 [mir_borrowck] processing `tables::bsearch_range_table`
end of query stack
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by matthewjasper**
* Restores the generation of outlives facts from subtyping.
* Restore liveness facts.
* Generate invalidates facts at the start point of each location,
  where we check for errors.
* Add a small test for simple cases (previously these cases have compiled, and more recently ICEd).

Closes #54212
cc #53142 (will need test)

### Known limitations

* Two phase borrows aren't implemented for Polonius yet
* Invalidation facts haven't been updated for some of the recent changes to make `Drop` terminators access fewer things.
* Fact generation is not as optimized as it could be.
* Around 30 tests fail in compare mode, often tests that are ignored in nll compare mode

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/nll/invalidation.rs [hunk 1]
```diff
@@ -553,7 +553,7 @@ impl<'cg, 'cx, 'tcx, 'gcx> InvalidationGenerator<'cg, 'cx, 'tcx, 'gcx> {
 
     /// Generate a new invalidates(L, B) fact
     fn generate_invalidates(&mut self, b: BorrowIndex, l: Location) {
-        let lidx = self.location_table.mid_index(l);
+        let lidx = self.location_table.start_index(l);
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/invalidation.rs]: Why did you change this from the mid point to the start point?

File: src/librustc_mir/borrow_check/nll/type_check/constraint_conversion.rs [hunk 2]
```diff
@@ -186,6 +169,23 @@ impl<'a, 'gcx, 'tcx> ConstraintConversion<'a, 'gcx, 'tcx> {
             sub,
             sup,
         });
+
+        // In the new analysis, all outlives relations etc
+        // "take effect" at the mid point of the statement
+        // that requires them, so ignore the `at_location`.
+        if let Some(all_facts) = &mut self.all_facts {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/constraint_conversion.rs]: Maybe it would be better if we just iterated over the `outlives_constraints` that we build up at the end? I forget though if there are outlives constraints we don't need for polonius.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 3]
```diff
@@ -1112,6 +1112,17 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
                             .constraints
                             .liveness_constraints
                             .add_element(region_vid, term_location);
+
+                        if let Some(facts) = borrowck_context.all_facts {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: These facts I believe are not needed in polonius — pretty sure I excluded them intentionally. We only care about the "transitive relations" that are formed via these late-bound regions. Did you find they were needed in particular?

File: src/librustc_mir/borrow_check/nll/type_check/relate_tys.rs [hunk 4]
```diff
@@ -266,7 +266,19 @@ impl<'cx, 'bccx, 'gcx, 'tcx> TypeRelating<'cx, 'bccx, 'gcx, 'tcx> {
                     locations: self.locations,
                 });
 
-            // FIXME all facts!
+            if let Some(all_facts) = borrowck_context.all_facts {
+                if let Some(from_location) = self.locations.from_location() {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/relate_tys.rs]: this would it seems be caught better by just inspecting the final outlives relations and convering them (as I mentioned earlier), then we wouldn't have to repeat this code

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Nice! Left a few comments.

File: src/librustc_mir/borrow_check/nll/invalidation.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir/borrow_check/nll/invalidation.rs]: Because that's what we use here:

https://github.com/rust-lang/rust/blob/31789a658bb6b6c78da1f2b99a5f169e4e8b983b/src/librustc_mir/borrow_check/mod.rs#L959

I'm changing this in the invalidation facts, and not here, because we use the incoming borrow in the current implementation.

**Comment by matthewjasper** [comment]
Comments addressed

File: src/librustc_mir/borrow_check/nll/invalidation.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/invalidation.rs]: OK. I don't actually think it matters much either way, because all the loans that are live on entry are also live at the mid point; I think though that we usually generate facts to "take effect" on the midpoint. (Conceptually, the mid-point is where the statement "has its effects", so that's the point that is doing the invalidation, but it's also valid to say that if -- on entry to the statement -- there are any borrows that it will mess up, that's en error.) Seems fine.

**Comment by matthewjasper** [comment]
rebased

**Review by nikomatsakis — APPROVED** [review]
