### PR TITLE
Custom lifetime error for `impl` item doesn't conform to `trait`

### LINKED ISSUE #40900: Error message for inferred lifetime failure isn't great
This code does not work:
```rust
use std::borrow::Borrow;

struct S;
trait T {}
impl T for S {}

impl Borrow<T> for S {
    fn borrow(&self) -> &T {
        self as &T
    }
}

fn main() {
    let s = S;
    let _t: &T = s.borrow();
}
```
The error message I get is:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter in generic type due to conflicting requirements
  --> <anon>:8:5
   |
8  |       fn borrow(&self) -> &T {
   |  _____^ starting here...
9  | |         self as &T
10 | |     }
   | |_____^ ...ending here
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the body at 8:27...
  --> <anon>:8:28
   |
8  |       fn borrow(&self) -> &T {
   |  ____________________________^ starting here...
9  | |         self as &T
10 | |     }
   | |_____^ ...ending here
note: ...so that method type is compatible with trait (expected fn(&S) -> &T + 'static, found fn(&S) -> &T)
  --> <anon>:8:5
   |
8  |       fn borrow(&self) -> &T {
   |  _____^ starting here...
9  | |         self as &T
10 | |     }
   | |_____^ ...ending here
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that method type is compatible with trait (expected fn(&S) -> &T + 'static, found fn(&S) -> &T)
  --> <anon>:8:5
   |
8  |       fn borrow(&self) -> &T {
   |  _____^ starting here...
9  | |         self as &T
10 | |     }
   | |_____^ ...ending here

error: aborting due to previous error
```

This code does work:
```rust
use std::borrow::Borrow;

struct S;
trait T {}
impl T for S {}

impl<'a> Borrow<T + 'a> for S {
    fn borrow(&self) -> &(T + 'a) {
        self as &T
    }
}

fn main() {
    let s = S;
    let _t: &T = s.borrow();
}
```
The only clue I got was this note:
```
note: ...so that method type is compatible with trait (expected fn(&S) -> &T + 'static, found fn(&S) -> &T)
```
which even then I wasn't clear if my change would make a difference or not. Is there some change we could make to the output that would make the solution clearer?

### PR DESCRIPTION
**Pull request by estebank**
Partly addresses #42706, #41343, fix #40900.

### CODE REVIEW

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+                _sup,
+            ) = error.clone() {
+                match (&sup_origin, &sub_origin) {
+                    (&Subtype(ref sup_trace), &Subtype(ref sub_trace)) => {
+                        if let (
+                            ValuePairs::Types(sub_expected_found),
+                            ValuePairs::Types(sup_expected_found),
+                        ) = (&sub_trace.values, &sup_trace.values) {
+                            if sup_expected_found == sub_expected_found {
+                                let sp = var_origin.span();
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Consider moving this out to a free function to avoid so much rightward indent.

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+                                let mut err = self.tcx().sess.struct_span_err(
+                                    sp,
+                                    "`impl` item doesn't match `trait` item"
```
Comment (Centril) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]:
```suggestion
                                    "`impl` item signature doesn't match `trait` item signature"
```

File: src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+                _sup,
+            ) = error.clone() {
+                match (&sup_origin, &sub_origin) {
+                    (&Subtype(ref sup_trace), &Subtype(ref sub_trace)) => {
+                        if let (
+                            ValuePairs::Types(sub_expected_found),
+                            ValuePairs::Types(sup_expected_found),
+                        ) = (&sub_trace.values, &sup_trace.values) {
+                            if sup_expected_found == sub_expected_found {
+                                let sp = var_origin.span();
```
Comment (estebank) [inline src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Is there a way of getting the original trait item's span here? That way we could point at both to make the discrepancy clearer.

Comment (nikomatsakis) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Hmm. I think that these variables are created in/around this code here:

https://github.com/rust-lang/rust/blob/8c7b921feb5b100b1825ad54d46a8cca575b35b3/src/librustc_typeck/check/compare_method.rs#L234-L238

If that's correct, one option might be to pack more information into the "variable origin". However, that code is *also* using an obligation cause that contains all the information we need:

https://github.com/rust-lang/rust/blob/8c7b921feb5b100b1825ad54d46a8cca575b35b3/src/librustc_typeck/check/compare_method.rs#L93-L101

This is threaded to "subtype" code here:

https://github.com/rust-lang/rust/blob/8c7b921feb5b100b1825ad54d46a8cca575b35b3/src/librustc_typeck/check/compare_method.rs#L290-L294

However, that seems to get lost when converting to a subregion obligation. There is some code tries to preserve it

https://github.com/rust-lang/rust/blob/8c7b921feb5b100b1825ad54d46a8cca575b35b3/src/librustc/infer/mod.rs#L1743-L1765

so I'm not 100% sure what's going on. Would have to dump some logs.

Comment (estebank) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Should we merge the work done so far and get back to it with more time to add the extra information? The original tickets would remain open.

Comment (estebank) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: The reason is because the failing obligation is of code `ReferenceOutlivesReferent`, not `CompareImplMethodObligation`. We really need to add a new variant to chain obligations together and recover the original problem.

Comment (estebank) [reply src/librustc/infer/error_reporting/nice_region_error/trait_impl_difference.rs]: Scratch that, figured it out.

File: src/test/ui/reject-specialized-drops-8142.stderr [hunk 4]
```diff
@@ -89,27 +89,16 @@ note: Use same sequence of generic type and region parameters that is on the str
...
-  --> $DIR/reject-specialized-drops-8142.rs:17:15
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found W<'_, '_>
    |
-LL | struct W<'l1, 'l2> { x: &'l1 i8, y: &'l2 u8 }
-   |               ^^^
-   = note: ...so that the types are compatible:
-           expected W<'l1, 'l2>
-              found W<'_, '_>
+   = note: expected `W<'l1, 'l2>`
+              found `W<'_, '_>`
```
Comment (estebank) [inline src/test/ui/reject-specialized-drops-8142.stderr]: This is coming from a `MiscObligation`, which is why it doesn't have a span pointing to the original struct.

**Comment by JohnCSimon** [comment]
Ping from triage: 

@nikomatsakis  Can you please review this PR? Thanks
CC: @estebank

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

nice patch, @estebank

**Comment by estebank** [comment]
@bors r=nikomatsakis

Made that test ignore x86 targets to get around different platform output discrepancies when a `std` span isn't found. There's a ticket open for that already.
