### PR TITLE
Fix `VecDeque::shrink_to` and add tests.

### LINKED ISSUE #108453: undefined behavior after calling VecDeque::shrink_to
I tried this code:

```rust
use std::collections::VecDeque;

fn main() {
    let mut deque = VecDeque::with_capacity(10);
    
    deque.push_back(1u8);
    deque.push_back(2);
    deque.push_back(3);

    deque.push_front(10);
    deque.push_front(9);
    
    deque.shrink_to(9);
    
    assert_eq!(deque.into_iter().collect::<Vec<_>>(), vec![9, 10, 1, 2, 3]);
}
```

I expected to see this happen: no error

Instead, this happened:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[9, 1, 2, 3, 0]`,
 right: `[9, 10, 1, 2, 3]`', src/main.rs:15:5
 ```
note: no zero was pushed, this is reading an undefined byte.
 
### Meta

`rustc --version --verbose`:
```
rustc 1.67.0 (fc594f156 2023-01-24)
binary: rustc
commit-hash: fc594f15669680fa70d255faec3ca3fb507c3405
commit-date: 2023-01-24
host: x86_64-unknown-linux-gnu
release: 1.67.0
LLVM version: 15.0.6
```

### Additional information

I believe this happens because the following case is not handled in `shrink_to`
```
//  H := head
//  L := last element
//  start:
//        L       H
//   [1 2 3 . . . 9 10 ]
//  expected (tail shifted):
//        L     H
//   [1 2 3 . . 9 10 ]
//  actual result (tail truncated):
//          L     H
//   [1 2 3 . . . 9 ]
```
In this case, `self.head < target_cap`, so two of the "cases of interest" are not a match, and `tail_outside == false`, so the last case isn't matched either.

### PR DESCRIPTION
**Pull request by Sp00ph**
Fixes #108453.

Also adds both a specific test with the code from #108453 and an exhaustive test that checks all possible head positions, lengths and target capacities for deques with capacity 16.

cc @trinity-1686a @scottmcm

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 1]
```diff
@@ -944,65 +944,72 @@ impl<T, A: Allocator> VecDeque<T, A> {
...
 
-        if target_cap < self.capacity() {
-            // There are three cases of interest:
-            //   All elements are out of desired bounds
-            //   Elements are contiguous, and head is out of desired bounds
-            //   Elements are discontiguous, and tail is out of desired bounds
+        // There are three cases of interest:
+        //   All elements are out of desired bounds
+        //   Elements are contiguous, and tail is out of desired bounds
+        //   Elements are discontiguous, and head is out of desired bounds
```
Comment (trinity-1686a) [inline library/alloc/src/collections/vec_deque/mod.rs:950]:
```suggestion
        //   Elements are discontiguous
```

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 2]
```diff
@@ -944,65 +944,72 @@ impl<T, A: Allocator> VecDeque<T, A> {
...
+            unsafe {
+                self.copy_nonoverlapping(target_cap, 0, len);
             }
-
-            self.buf.shrink_to_fit(target_cap);
-
-            debug_assert!(self.head < self.capacity() || self.capacity() == 0);
-            debug_assert!(self.len <= self.capacity());
+        } else if !self.is_contiguous() {
+            // Head is out of bounds, tail is in bounds.
```
Comment (trinity-1686a) [inline library/alloc/src/collections/vec_deque/mod.rs:990]: this is inaccurate: tail is in bound, but head can be either. In fact, not handling the case where head is in bound (but what follows isn't) is the bug getting fixed.

Comment (Sp00ph) [reply library/alloc/src/collections/vec_deque/mod.rs:990]: Hm, I was thinking of `Head` as the entire head slice in this case, but yea it can be interpreted both ways. I'll edit the comment to make it clearer.

File: library/alloc/src/collections/vec_deque/tests.rs [hunk 3]
```diff
@@ -748,6 +748,48 @@ fn test_drain() {
...
+fn test_shrink_to() {
+    // test deques with capacity 16 with all possible head positions, lengths and target capacities.
+    let cap = 16;
+
+    for len in 0..cap {
+        for head in 0..cap {
+            let expected = (1..=len).collect::<VecDeque<_>>();
+
+            for target_cap in len..cap {
+                let mut deque = VecDeque::with_capacity(16);
```
Comment (thomcc) [inline library/alloc/src/collections/vec_deque/tests.rs:777]: nit
```suggestion
                let mut deque = VecDeque::with_capacity(cap);
```

**Review by thomcc — APPROVED** [review]
This looks fine.

**Comment by thomcc** [comment]
Looks great. Thanks for the fix.

@bors r+

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 4]
```diff
@@ -944,65 +944,72 @@ impl<T, A: Allocator> VecDeque<T, A> {
             return;
         }
 
-        if target_cap < self.capacity() {
```
Comment (scottmcm) [inline library/alloc/src/collections/vec_deque/mod.rs:947]: Oh, heh, guess this wasn't ever doing anything, after the check on 943.
