### PR TITLE
Point at path segment on module not found

### LINKED ISSUE #43040: "Could not find <module> in <module>" uses wrong span when {...} are involved
The following program: ([Playpen](https://is.gd/ZIODvp))
```rust
use std::bar::{foo1, foo2};

fn main() {
    println!("Hello, world!");
}
```

Produces these errors:
```
error[E0432]: unresolved import `std::bar::foo1`
 --> <anon>:1:16
  |
1 | use std::bar::{foo1, foo2};
  |                ^^^^ Could not find `bar` in `std`

error[E0432]: unresolved import `std::bar::foo2`
 --> <anon>:1:22
  |
1 | use std::bar::{foo1, foo2};
  |                      ^^^^ Could not find `bar` in `std`
```

Notice how the `^` put the blame on the part inside the curly brace, where really, they should point at the `bar` (or at the entire `std::...`, which is what happens when no curly braces are involved).

### PR DESCRIPTION
**Pull request by estebank**
Point at the correct path segment on a import statement where a module
doesn't exist.

New output:

```rust
error[E0432]: unresolved import `std::bar`
 --> <anon>:1:10
  |
1 | use std::bar::{foo1, foo2};
  |          ^^^ Could not find `bar` in `std`
```

instead of:

```rust
error[E0432]: unresolved import `std::bar::foo1`
 --> <anon>:1:16
  |
1 | use std::bar::{foo1, foo2};
  |                ^^^^ Could not find `bar` in `std`

error[E0432]: unresolved import `std::bar::foo2`
 --> <anon>:1:22
  |
1 | use std::bar::{foo1, foo2};
  |                      ^^^^ Could not find `bar` in `std`
```

Fix #43040.

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -297,12 +298,12 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver,
...
-            let msg = match name {
-                Some((n, _)) => format!("unresolved import `{}`", n),
-                None => "unresolved import".to_owned(),
+            let (span, msg) = match name {
+                Some((sp, n, _)) => (sp, format!("unresolved import `{}`", n)),
+                None => (span, "unresolved import".to_owned()),
             };
-            let mut err = struct_span_err!(resolver.session, span, E0432, "{}", msg);
-            if let Some((_, p)) = name {
+            let mut err = struct_span_err!(resolver.session, span, E0432, "{}", msg);;;;
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: >;;;;

Hmmm

Comment (estebank) [inline src/librustc_resolve/lib.rs]: Fixed.
