### PR TITLE
NVPTX target specification

### LINKED ISSUE #38786: NVPTX: No "undefined reference" error is raised when it should be
### STR

```
$ cargo new --lib kernel && cd $_

$ edit src/lib.rs && cat $_
```

``` rust
#![no_std]

extern {
    fn bar();
}

fn foo() {
    unsafe {
        bar()
    }
}
```

```
$ cat nvptx64-nvidia-cuda.json
```

``` js
{
  "arch": "nvptx64",
  "cpu": "sm_20",
  "data-layout": "e-i64:64-v16:16-v32:32-n16:32:64",
  "llvm-target": "nvptx64-nvidia-cuda",
  "max-atomic-width": 0,
  "os": "cuda",
  "panic-strategy": "abort",
  "target-endian": "little",
  "target-pointer-width": "64"
}
```

```
$ edit Cargo.toml && cat $_
```

``` toml
[profile.dev]
debug = false  # cf. rust-lang/rust#38785
```

```
$ cargo install xargo --vers 0.3.0 || true

$ xargo rustc --target nvptx64-nvidia-cuda -- --emit=asm
```

```
$ cat $(find target/nvptx64-nvidia-cuda/debug -name '*.s')
.version 3.2
.target sm_20
.address_size 64

.extern .func bar
()
;

.func _ZN6kernel3foo17h9be095784726d4d0E()
{


        bra.uni         LBB0_1;
LBB0_1:
        { // callseq 0
        .reg .b32 temp_param_reg;
        call.uni
        bar,
        (
        );
        } // callseq 0
        bra.uni         LBB0_2;
LBB0_2:
        ret;
}
```

Note that `bar` is called by `foo` but it's not defined in the PTX module. Trying to load this PTX module, with `cuModuleLoadData`, generates a runtime error: `CUDA_ERROR_NO_BINARY_FOR_GPU`.

### Expected behavior

Other targets that produce an executable would fail to compile this with an "undefined reference" error which is actually raised by the linker. The NVPTX targets don't involve a linker but they shouldn't produce incomplete PTX modules like the one above; instead the should raise an error like the other targets do.

### LINKED ISSUE #38787: NVPTX: non-inlined functions can't be used cross crate
Or all functions should be "inlined" for the nvptx targets

### STR

```
$ cargo new --lib lib

$ edit lib/src/lib.rs && cat $_
```

``` rust
#![no_std]

pub fn foo() -> i32 {
    42
}
```

```
$ cargo new --lib kernel && cd $_

$ edit src/lib.rs && cat $_
```

``` rust
#![no_std]

extern crate lib;

fn bar() -> i32 {
    lib::foo()
}
```

```
$ edit Cargo.toml && tail -n5 $_
```

``` toml
[dependencies]
lib = "../lib"

[profile.dev]
debug = false  # cf. rust-lang/rust#38785
```

```
$ edit nvptx64-nvidia-cuda.json && cat $_
```

``` js
{
  "arch": "nvptx64",
  "cpu": "sm_20",
  "data-layout": "e-i64:64-v16:16-v32:32-n16:32:64",
  "llvm-target": "nvptx64-nvidia-cuda",
  "max-atomic-width": 0,
  "os": "cuda",
  "panic-strategy": "abort",
  "target-endian": "little",
  "target-pointer-width": "64"
}
```

```
$ cargo install xargo --vers 0.3.0 || true

$ xargo rustc --target nvptx64-nvidia-cuda -- --emit=asm

$ cat $(find target/nvptx64-nvidia-cuda/debug -name '*.s')
.version 3.2
.target sm_20
.address_size 64

.extern .func  (.param .b32 func_retval0) _ZN3lib3foo17h3feefc42e145764bE
()
;

.func  (.param .b32 func_retval0) _ZN6kernel3bar17h7b762ababaef9f36E()
{
        .reg .s32       %r<2>;

        bra.uni         LBB0_1;
LBB0_1:
        { // callseq 0
        .reg .b32 temp_param_reg;
        .param .b32 retval0;
        call.uni (retval0),
        _ZN3lib3foo17h3feefc42e145764bE,
        (
        );
        ld.param.b32    %r1, [retval0+0];
        } // callseq 0
        bra.uni         LBB0_2;
LBB0_2:
        st.param.b32    [func_retval0+0], %r1;
        ret;
}
```

Note that `foo` appears as undefined (`.extern .func`) in the PTX module.

### Workaround

Mark `lib::foo` as `#[inline]`. Then you'll get the translation of `foo` in the final PTX module:

```
.version 3.2
.target sm_20
.address_size 64


.func  (.param .b32 func_retval0) _ZN3lib3foo17h3feefc42e145764bE()
{
        .reg .s32       %r<2>;

        bra.uni         LBB0_1;
LBB0_1:
        mov.u32         %r1, 42;
        st.param.b32    [func_retval0+0], %r1;
        ret;
}

.func  (.param .b32 func_retval0) _ZN6kernel3bar17h7b762ababaef9f36E()
{
        .reg .s32       %r<2>;

        bra.uni         LBB1_1;
LBB1_1:
        { // callseq 0
        .reg .b32 temp_param_reg;
        .param .b32 retval0;
        call.uni (retval0),
        _ZN3lib3foo17h3feefc42e145764bE,
        (
        );
        ld.param.b32    %r1, [retval0+0];
        } // callseq 0
        bra.uni         LBB1_2;
LBB1_2:
        st.param.b32    [func_retval0+0], %r1;
        ret;
}
```

### PR DESCRIPTION
**Pull request by denzp**
This change adds a built-in `nvptx64-nvidia-cuda` GPGPU no-std target specification and a basic PTX assembly smoke tests. 

The approach is taken here and the target spec is based on `ptx-linker`, a project started about 1.5 years ago. Key feature: bitcode object files being linked with LTO into the final module on the linker's side.

Prior to this change, the linker used a `ld` linker-flavor, but I think, having the special CLI convention is a more reliable way.

Questions about further progress on reliable CUDA workflow with Rust:
1. Is it possible to create a test suite `codegen-asm` to verify end-to-end integration with LLVM backend?
1. How would it be better to organise no-std `compile-fail` tests: add `#![no_std]` where possible and mark others as `ignore-nvptx` directive, or alternatively, introduce `compile-fail-no-std` test suite?
1. Can we have the `ptx-linker` eventually be integrated as `rls` or `clippy`? Hopefully, this should allow to statically link against LLVM used in Rust and get rid of the [current hacky solution](https://github.com/denzp/rustc-llvm-proxy).
1. Am I missing some methods from `rustc_codegen_ssa::back::linker::Linker` that can be useful for bitcode-only linking?

Currently, there are no major public CUDA projects written in Rust I'm aware of, but I'm expecting to have a built-in target will create a solid foundation for further experiments and awesome crates.

Related to #38789
Fixes #38787
Fixes #38786

### CODE REVIEW

File: src/librustc_codegen_utils/symbol_names.rs [hunk 1]
```diff
@@ -398,12 +400,24 @@ impl ItemPathBuffer for SymbolPathBuffer {
     }
 }
 
+// Manual Debug implementation to omit non-Debug `tcx` field.
+impl fmt::Debug for SymbolPathBuffer<'_, '_> {
+    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
+        fmt.debug_struct("SymbolPathBuffer")
+            .field("result", &self.result)
```
Comment (nagisa) [inline src/librustc_codegen_utils/symbol_names.rs]: Do not omit the `tcx` field entirely, just give it some dummy value such as `_`.

File: src/librustc_codegen_utils/symbol_names.rs [hunk 2]
```diff
@@ -398,12 +400,24 @@ impl ItemPathBuffer for SymbolPathBuffer {
...
+
 // Name sanitation. LLVM will happily accept identifiers with weird names, but
 // gas doesn't!
 // gas accepts the following characters in symbols: a-z, A-Z, 0-9, ., _, $
+// NVPTX assembly has more strict naming rules than gas, so additionally, dots
+// are replaced with '$' there.
 //
 // returns true if an underscore must be added at the start
-pub fn sanitize(result: &mut String, s: &str) -> bool {
+pub fn sanitize(result: &mut String, s: &str, tcx: TyCtxt<'a, 'tcx, 'tcx>) -> bool {
```
Comment (nagisa) [inline src/librustc_codegen_utils/symbol_names.rs]: It seems to me that a better approach would be to just put `has_strict_asm_symbol_naming()` value into some sanitizer context and have this function to become a method of said context, rather than trying to string through `tcx` and other possibly desirable global contexts until here.

File: src/librustc_target/spec/nvptx64_nvidia_cuda.rs [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+
+        options: TargetOptions {
+            // The linker can be installed from `crates.io`.
+            linker: Some("rust-ptx-linker".to_string()),
+
+            // With `ptx-linker` approach, it can be later overriden via link flags.
+            cpu: "sm_20".to_string(),
+
+            // TODO(denzp): create tests for the atomics.
+            max_atomic_width: Some(64),
```
Comment (peterhj) [inline src/librustc_target/spec/nvptx64_nvidia_cuda.rs]: BTW I did a few basic tests, and it turns out the the `atomic_xadd` rust-intrinsic seems to already generate correct PTX when doing atomic adds on `u32` and `u64`. Hurray! I didn't test too many other atomic ops or sizes though.

(Sadly, `atomic_xadd` only supports integers and doesn't compile for `f32` and `f64` types.)

File: src/test/run-make/nvptx-binary-crate/Makefile [hunk 4]
```diff
@@ -0,0 +1,9 @@
+-include ../../run-make-fulldeps/tools.mk
+
+ifeq ($(TARGET),nvptx64-nvidia-cuda)
+all:
+	$(RUSTC) main.rs -Clink-arg=--arch=sm_60 --crate-type="bin" -O --target $(TARGET)
+	FileCheck main.rs --input-file $(TMPDIR)/main.ptx
```
Comment (nagisa) [inline src/test/run-make/nvptx-binary-crate/Makefile]: Hmm, it feels like codegen test infrastructure should be used. At very least this is trying to use the `FileCheck` in `$PATH`, which is not correct.

File: src/librustc_target/spec/nvptx64_nvidia_cuda.rs [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+        target_endian: "little".to_string(),
+        target_pointer_width: "64".to_string(),
+        target_c_int_width: "32".to_string(),
+
+        options: TargetOptions {
+            // The linker can be installed from `crates.io`.
+            linker: Some("rust-ptx-linker".to_string()),
+
+            // With `ptx-linker` approach, it can be later overriden via link flags.
+            cpu: "sm_20".to_string(),
```
Comment (peterhj) [inline src/librustc_target/spec/nvptx64_nvidia_cuda.rs]: Recent CUDA versions (at least since 10.0) have dropped support for compute capabilities less than 3.x. In other words `ptxas` won't compile this. I would recommend changing the minimum target-cpu to "sm_30".

File: src/librustc_codegen_ssa/back/link.rs [hunk 6]
```diff
@@ -149,6 +149,7 @@ pub fn linker_and_flavor(sess: &Session) -> (PathBuf, LinkerFlavor) {
                 LinkerFlavor::Ld => "ld",
                 LinkerFlavor::Msvc => "link.exe",
                 LinkerFlavor::Lld(_) => "lld",
+                LinkerFlavor::PtxLinker => "rust-ptx-linker",
```
Comment (nagisa) [inline src/librustc_codegen_ssa/back/link.rs]: Hmm… so we are depending on external project by default here. Something that users are very unlikely to have installed by default.

I wonder what the error looks like when `rust-ptx-linker` is not in `$PATH`. Perhaps it would make sense to ship `rust-ptx-linker` as part of rustlib like we do with e.g. `lld` component for some targets...

File: src/librustc_target/spec/nvptx64_nvidia_cuda.rs (hunk 5 above)
Comment (peterhj) [reply src/librustc_target/spec/nvptx64_nvidia_cuda.rs]: Hmmm, actually `ptxas` _will_ compile this as long as you don't specify args `-arch sm_20`, but then setting "sm_20" in the PTX may not be doing what we think it is doing if `ptxas` is emitting code for at least "sm_30" anyway.

**Review by nagisa — COMMENTED** [review]
For now comments are as is. I find tests somewhat sketchy, but I understand that the hand may be forced due to inadequate flexibility of other test suites.

File: src/librustc_codegen_ssa/back/link.rs (hunk 6 above)
Comment (denzp) [reply src/librustc_codegen_ssa/back/link.rs]: That's true. On the other hand, to get started with CUDA development in Rust, users will follow either docs or tutorials, where it should be mentioned how to setup the environment.

The error message is, currently:
```
error: linker `rust-ptx-linker` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error
```

Personally, I would love to have the linker to be shipped via rustup. But perhaps, it will be preferable to implement this as a separate PR?

File: src/test/run-make/nvptx-binary-crate/Makefile (hunk 4 above)
Comment (denzp) [reply src/test/run-make/nvptx-binary-crate/Makefile]: Interesting, at first I was afraid it will use system-wide `FileCheck` but on my env, either `bootstrap` or `compiletest` add a correct `$PATH`. So, the tests pass no matter the system-wide binary exist or not.

File: src/librustc_codegen_ssa/back/linker.rs [hunk 7]
```diff
@@ -1080,3 +1084,124 @@ fn exported_symbols(tcx: TyCtxt, crate_type: CrateType) -> Vec<String> {
...
+    fn add_object(&mut self, path: &Path) {
+        self.cmd.arg("--bitcode").arg(path);
+    }
+
+    fn args(&mut self, args: &[String]) {
+        self.cmd.args(args);
+    }
+
+    fn optimize(&mut self) {
+        self.cmd.arg(match self.sess.opts.optimize {
```
[the remark this answers is not in the document]
Comment (denzp) [reply src/librustc_codegen_ssa/back/linker.rs]: I followed args pattern from other linkers here. 
At the moment the linker runs both LTO and optimisation passes over the final (complete) module when `-O{1,2,3}` is specified.

Does Rust runs optimisations before emitting bitcode object files? If yes, it can be avoided on linker's side then.

**Comment by denzp** [comment]
@nagisa @peterhj thanks for reviewing!

I can agree about tests - normally these 3 `run-make` cases should be divided into many smaller ones. That's the reason why I call them "smoke tests" - they verify only basic functionality. The reason why I decided to condense the test cases is to avoid much similar boilerplate `Makefile` code that needs to be maintained.

How can I use `codegen` tests to assert assembly output? Also, how can I deal with the fact that the target is no-std and existing tests there often rely on `libstd`?

That's why I had an idea about introducing `codegen-asm` with mandatory target specification for each test case.

File: src/librustc_codegen_ssa/back/linker.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (nagisa) [reply src/librustc_codegen_ssa/back/linker.rs]: > Does Rust runs optimisations before emitting bitcode object files?

Yes it does.

> I followed args pattern from other linkers here.

I’m not sure what these flags mean for ptx-linker, but for `gcc` and/or `clang` optimization flags during linkage mean very little if anything at all AFAIK. It definitely does not invoke some sort of global program re-optimisation, which is what happens with ptx-linker, it seems.

Now such global-program optimisation is what `lto` would usually do, which is why I suggested that perhaps that flag is what should be accounted for :)

That could be left as a future endeavour as well, but invoking “LTO” just from `-Copt-level` feels wrong.

File: src/test/run-make/nvptx-binary-crate/Makefile (hunk 4 above)
Comment (nagisa) [reply src/test/run-make/nvptx-binary-crate/Makefile]: Okay then. Still feels suspect, but I’m fine with that explanation :)

**Comment by nagisa** [comment]
> How can I use codegen tests to assert assembly output?

Currently, AFAIK there is no way. Minor changes to compiletest are necessary to make it possible. For now it is fine to keep these tests as make-tests. We will figure out how to migrate them once compiletest is improved to support such use-case.

File: src/librustc_codegen_ssa/back/link.rs (hunk 6 above)
Comment (nagisa) [reply src/librustc_codegen_ssa/back/link.rs]: > But perhaps, it will be preferable to implement this as a separate PR?

Sure.

**Comment by alexcrichton** [comment]
Thanks for this!

The only comment I'd add is that we unfortunately don't have resources for another image to run on Travis right now, but could this be folded into an existing builder that's already performing well under 2h on average?

File: src/librustc_codegen_ssa/back/linker.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (denzp) [reply src/librustc_codegen_ssa/back/linker.rs]: Thanks for the explanation and suggestion, I overlooked `Session::lto(&self)` before!

I've also changed `ptx-linker` to not perform final global optimisation - indeed it didn't affect much.

**Comment by denzp** [comment]
@alexcrichton I can see that `wasm-unknown` image is usually [runs pretty fast](https://travis-ci.com/rust-lang/rust/builds/98843135) compared to other non-`dist` images. 

Can I add NVPTX tests there? The only thing, it feels like the image should be renamed then. Do you have suggestions about the naming?

**Comment by alexcrichton** [comment]
@denzp sure yeah so long as it still runs in under 2 hrs should be fine to add! It should be fine to rename it to something like `test-various` perhaps?

File: src/test/run-make/nvptx-binary-crate/Makefile [hunk 8]
```diff
@@ -0,0 +1,9 @@
+-include ../../run-make-fulldeps/tools.mk
+
+ifeq ($(TARGET),nvptx64-nvidia-cuda)
+all:
+	$(RUSTC) main.rs -Clink-arg=--arch=sm_60 --crate-type="bin" -O --target $(TARGET)
```
Comment (gnzlbg) [inline src/test/run-make/nvptx-binary-crate/Makefile]: Does `RUSTFLAGS=-C target-cpu=sm_60` achieve the same effect here as passing the link flags ?

Comment (denzp) [reply src/test/run-make/nvptx-binary-crate/Makefile]: Thanks, that's a nice catch.
I've addressed this providing `target_cpu` via `--fallback-arch` arg to the linker in the latest commit.

**Comment by denzp** [comment]
@alexcrichton thanks, I've merged the images as suggested!

**Comment by alexcrichton** [comment]
👍

**Comment by nagisa** [comment]
The compiler bits look good to me. I’ll assume that Alex’s :+1: is an approval for the infra changes.

@bors r+

**Comment by gnzlbg** [comment]
Thank you @denzp !
