### PR TITLE
Fix doctest compilation time display

### LINKED ISSUE #146960: Merged doctest compilation time is not reported if all doctests are merged
I tested this code:

```rust
/// ```
/// playground::foo();
/// ```
pub fn foo() {}
```

I expected to see this happen: As per closed issue #144270 and PR #144308, the time spent compiling the doctests should be reported.

Instead, this happened: The compilation time is not reported (all visible timestamps are `0.00 s`), *unless* at least one doctest in the crate is compiled separately for any reason (e.g. <code>\`\`\`compile_fail</code>).

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (4645a7988 2025-09-17)
binary: rustc
commit-hash: 4645a7988177c286f61609cc667ecae4c571a2e8
commit-date: 2025-09-17
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.1
```

@rustbot label A-doctests A-libtest
cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#146960.

Small corner case that happened in case everything went fine and there was only merged doctests.

r? lolbinarycat

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Added the missing normalizations.

**Comment by GuillaumeGomez** [comment]
I keep discovering more tests that were actually buggy. ^^'

Anyway, fixed the `run-make` one as well.

**Comment by GuillaumeGomez** [comment]
CI passed. \o/

File: tests/run-make/doctests-compilation-time-info/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,119 @@
+//@ ignore-cross-compile (needs to run doctests)
+
+use run_make_support::rfs::write;
+use run_make_support::{cwd, rustdoc};
+
+fn check_present_of_compilation_time_report(
```
Comment (lolbinarycat) [inline tests/run-make/doctests-compilation-time-info/rmake.rs]:
```suggestion
fn assert_presence_of_compilation_time_report(
```

`check` -> `assert` since this function asserts directly instead of returning a bool.

`present` -> `presence` for grammaticality.

File: tests/run-make/doctests-compilation-time-info/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    // Checking with only successful merged doctests.
+    check_present_of_compilation_time_report(
+        "\
+//! ```
+//! let x = 12;
+//! ```",
+        true,
+        true,
+    );
+    // Checking with only fainling merged doctests.
```
Comment (lolbinarycat) [inline tests/run-make/doctests-compilation-time-info/rmake.rs]:
```suggestion
    // Checking with only failing merged doctests.
```

**Review by lolbinarycat — COMMENTED** [review]
There's a few typos and improvable names, but other than that it looks good!

r=me with typos fixed and CI passing

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147032/7ac0330c6d684d86d6f86fabe601a3defdc3b234..1e458ea2519f6f78099a58d7a8be437c7216d7c8)*
