### PR TITLE
Fix TAIT & ATPIT feature gating in the presence of anon consts

### LINKED ISSUE #139055: Can not use argument impl Trait in type alias
I tried this code:

```rust
type X = [(); {
    
    fn hello(x: impl Clone) {
        
    }
    
    3
}];
```
I expect this to compile, but instead i get this error.

```
error[E0658]: `impl Trait` in type aliases is unstable
 --> src/lib.rs:3:17
  |
3 |     fn hello(x: impl Clone) {
  |                 ^^^^^^^^^^
  |
```

### Meta

Bug also reproduces on nightly.

`rustc --version --verbose`:
```
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: x86_64-unknown-linux-gnu
release: 1.85.1
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by fmease**
Fixes #139055 (https://github.com/rust-lang/rust/issues/119924#issuecomment-1928659690).

r? oli-obk or anybody else

### CODE REVIEW

File: tests/ui/feature-gates/feature-gate-type_alias_impl_trait.rs [hunk 1]
```diff
@@ -1,38 +1,42 @@
-//@ check-pass
-#![feature(type_alias_impl_trait)]
```
Comment (oli-obk) [inline tests/ui/feature-gates/feature-gate-type_alias_impl_trait.rs:2]: whoops

**Comment by fmease** [comment]
(Fixed commit message >.<)

@bors r=oli-obk

**Comment by oli-obk** [comment]
> (Fixed commit message >.<)

just came here because I saw the cross-link from the other PR and was confused 😆

**Comment by fmease** [comment]
Smol tweak. Can't help myself @bors r=oli-obk
