### PR TITLE
Reject `?Trait` bounds in various places where we unconditionally warned since 1.0

### LINKED ISSUE #135730: ICE could not unify `!` with revealed type
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024
fn foo() -> impl ?Future<Output = impl Send> {
    ()
}

fn main() {}

````

original:
````rust
fn foo() -> impl ?Future<Output = impl Send> {
    //~^ ERROR the size for values of type `impl ?Sized` cannot be known at compilation time
    ()
}

fn main() {}

````

Version information
````
rustc 1.86.0-nightly (678e669cc 2025-01-19)
binary: rustc
commit-hash: 678e669cc4aab51e3c3fff0660d45362fb830ebd
commit-date: 2025-01-19
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: relaxing a default bound only does something for `?Sized`; all other traits are not bound by default
 --> /tmp/icemaker_global_tempdir.qzKHRUKhhL4b/rustc_testrunner_tmpdir_reporting.uYhpe96WGOAh/mvce.rs:1:18
  |
1 | fn foo() -> impl ?Future<Output = impl Send> {
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function `foo` is never used
 --> /tmp/icemaker_global_tempdir.qzKHRUKhhL4b/rustc_testrunner_tmpdir_reporting.uYhpe96WGOAh/mvce.rs:1:4
  |
1 | fn foo() -> impl ?Future<Output = impl Send> {
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: could not unify `()` with revealed type:
                                expected opaque type, found `()`
 --> /tmp/icemaker_global_tempdir.qzKHRUKhhL4b/rustc_testrunner_tmpdir_reporting.uYhpe96WGOAh/mvce.rs:1:35
  |
1 | fn foo() -> impl ?Future<Output = impl Send> {
  |                                   ^^^^^^^^^
  |
note: delayed at compiler/rustc_hir_analysis/src/check/check.rs:396:34
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         4: rustc_hir_analysis::check::check::check_item_type
         5: rustc_hir_analysis::check::wfcheck::check_well_formed
         6: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
         7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
         8: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
         9: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, ()>
        10: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        13: rustc_query_impl::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
        14: rustc_hir_analysis::check_crate
        15: rustc_interface::passes::run_required_analyses
        16: rustc_interface::passes::analysis
        17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
        18: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        19: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        20: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        21: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        22: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        23: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        24: std::sys::pal::unix::thread::Thread::new::thread_start
        25: <unknown>
        26: <unknown>
 --> /tmp/icemaker_global_tempdir.qzKHRUKhhL4b/rustc_testrunner_tmpdir_reporting.uYhpe96WGOAh/mvce.rs:1:35
  |
1 | fn foo() -> impl ?Future<Output = impl Send> {
  |                                   ^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (678e669cc 2025-01-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

### LINKED ISSUE #135809: relaxing a non-`Sized` bounds is a hard-warning
https://github.com/rust-lang/rust/blob/b605c65b6eb5fa71783f8e26df69975f9f1680ee/compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs#L97-L111

```rust
fn foo() -> impl ?Send {}
```

```
warning: relaxing a default bound only does something for `?Sized`; all other traits are not bound by default
 --> src/lib.rs:1:18
  |
1 | fn foo() -> impl ?Send {}
  |                  ^^^^^
```

This should either be a (future-compat) lint or a hard-error.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #135730
fixes #135809

Also a breaking change, so let's see what crater says.

This has been an unconditional warning since *before* 1.0

### CODE REVIEW

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
Hi @rust-lang/types, it turns out we've accepted `?Trait` bounds in various places since 1.0 and just emitted an unconditional warning. I have been unable to find the reason for it, but since it doesn't do anything and emitted a warning, it seems no one actually wrote this (crater shows no regressions when turning it into a hard error). Therefor I propose to just turn it into a hard error and subsequently make our lives easier because we don't need to patch situations everywhere in the compiler.

One common source of problems with such bounds is that they can have generics or associated types/consts and all of these just get dropped on the floor and never evaluated, normalized, or otherwise processed in the type system. This leads to fun bugs like not evaluating constants or just ICEing because opaque types never got defined.

@rfcbot fcp merge

**Comment by lcnr** [comment]
cc @rust-lang/lang for info

I think this is fine as a pure types team FCP. Allowing these bounds is causing bugs without any benefit.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs [hunk 1]
```diff
@@ -103,7 +103,7 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                 continue;
             }
             // There was a `?Trait` bound, but it was not `?Sized`; warn.
```
Comment (cyrgani) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs:105]: the last word is now outdated

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs [hunk 2]
```diff
@@ -102,8 +102,8 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                 seen_sized_unbound = true;
                 continue;
             }
-            // There was a `?Trait` bound, but it was not `?Sized`; warn.
-            self.dcx().span_warn(
+            // There was a `?Trait` bound, but it was not `?Sized`
+            self.dcx().span_err(
                 unbound.span,
                 "relaxing a default bound only does something for `?Sized`; \
                 all other traits are not bound by default",
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs:109]: I don't want to block this PR on surface level things like phrasing, so feel free to ignore this and I'll submit this as a follow-up. I've never liked how this specific diagnostic is formulated, it's super verbose.

Now with this being a hard error this sentence doesn't quite make sense anymore. I'd rather see a message that's straight to the point like `` `?` can only be applied to `Sized` `` (similar to `` `~const` can only be applied to `#[const_trait]` traits `` or `` `async` bound modifier only allowed on `Fn`/`FnMut`/`FnOnce` traits ``) and defer any further explanations to diagnostic note/help messages if at all (cc error codes).

If we want to feel fancy we could provide a structured suggestion for removing the entire bound.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/bounds.rs:109]: How about we do this as a follow-up

**Review by fmease — COMMENTED** [review]
Note that this PR doesn't catch all occurrences of `?Trait`, `Trait`≠`Sized` because performing the validation in `add_sized_bound` is super backwards and because we don't reject maybe-bounds in ATB position (#135229).

Meaning the following code still compiles successfully and without warnings:

```rs
fn _f(_: impl Iterator<Item: ?Copy>) {}
```

I'll rewrite the way we validate and handle maybe-bounds because I wanted to do that anyway for the longest time (fixing #136944 in the process).

(Lastly, I'll make it so we don't error at all if the internal feature `more_maybe_bounds` (#121676) is enabled; while I'm personally not in favor of that internal feature, this PR did partially regress it)

(Re. ATBs / #135229, the crater run didn't show any regressions but GH search revealed users using them (mistakenly), so I'll either make it a FCW or hard error regardless (in yet another PR))
