### PR TITLE
Fix rustdoc duplicated blanket impls

### LINKED ISSUE #96036: rustdoc: Many times the same `From<!> for T` impl for the `!` type
https://doc.rust-lang.org/nightly/std/primitive.never.html#blanket-implementations

image

All pointing to the same impl:

image

@rustbot label +T-rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #96036.

I think it'll not be great performance-wise but I couldn't find another way to prevent that unfortunately...

r? @notriddle

### CODE REVIEW

**Comment by vacuus** [comment]
I don't actually know that this works, but can't you use a `FxHashSet<DefId>` for `impl_ids`? You don't seem to check which set `did` maps to, just whether it's contained within that set, so the nesting seems unnecessary.

**Comment by GuillaumeGomez** [comment]
Unfortunately, no. The `DefId` in the `FxHashMap` is the item and it lists all its implementations. So we cannot only have one level, otherwise we'd have much less implementations.

For the fun fact: I also thought the same as you first. The tests disagreed strongly. :laughing:

File: src/librustdoc/formats/mod.rs [hunk 1]
```diff
@@ -40,4 +40,8 @@ impl Impl {
     crate fn trait_did(&self) -> Option<DefId> {
         self.inner_impl().trait_.as_ref().map(|t| t.def_id())
     }
+
+    crate fn def_id(&self) -> clean::ItemId {
```
Comment (notriddle) [inline src/librustdoc/formats/mod.rs:44]: Referring to something as `def_id` when it isn't actually a `DefId` seems bad. I know there are other spots in rustdoc where this is done; those are technical debt, and I'd like to see them go away over time, instead of perpetuating the confusion.

File: src/librustdoc/formats/cache.rs [hunk 2]
```diff
@@ -127,9 +127,27 @@ crate struct Cache {
...
+    impl_ids: FxHashMap<DefId, FxHashSet<DefId>>,
     tcx: TyCtxt<'tcx>,
 }
 
+/// This function is used to extract a `DefId` to be used as a key for the `Cache::impls` field.
+///
+/// It allows to prevent having duplicated implementations showing up (the biggest issue was with
+/// blanket impls).
+#[inline]
+fn expect_def_id(item_id: ItemId) -> DefId {
```
Comment (notriddle) [inline src/librustdoc/formats/cache.rs:140]: This function is a landmine, because its type signature is a lie. You can't just go from `ItemId -> DefId`, you need to know what you're looking at.

* If we know that your `Impl::def_id` function will always return something that actually has a `DefId`, then this function shouldn't be necessary. Make that other function actually return a `DefId`.
* If you don't know that, have this function return an `Option` instead, and everywhere it's called, add a comment justifying why, in that particular spot, you know that primitives will never show up.
* If you really can't come up with a good justification, then it's fine. `ItemId` implements `Hash`, so you can just make it an `FxHashMap<DefId, FxHashSet<ItemId>>` instead.

**Review by notriddle — CHANGES_REQUESTED** [review]

File: src/librustdoc/formats/cache.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/formats/cache.rs:140]: > * If we know that your `Impl::def_id` function will always return something that actually has a `DefId`, then this function shouldn't be necessary. Make that other function actually return a `DefId`.

This is a good point. That'll remove one level.

>     * If you really can't come up with a good justification, then it's fine. `ItemId` implements `Hash`, so you can just make it an `FxHashMap<DefId, FxHashSet<ItemId>>` instead.

That's what I went with originally and it didn't work because the `for` was always different, even though it was the same impl ID. It's the very root of this bug.

File: src/librustdoc/formats/mod.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/formats/mod.rs:44]: Indeed, I'll do that then.

**Comment by notriddle** [comment]
Overall the *approach* is okay to me. It's just nitpicking about specifics: why so much of the moral equivalent of `unwrap`?

**Comment by GuillaumeGomez** [comment]
It's not that I don't want `unwrap` equivalents but more than I actually thought it would turn out better this way. Let's see how it'll go in the other way around. :)

**Comment by GuillaumeGomez** [comment]
Applied @notriddle's suggestions. :)

**Comment by GuillaumeGomez** [comment]
Needs to be rebased.

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

* The main hit is to externs, which I'm rejecting as ignorable this week due to extant noise.

@rustbot label: +perf-regression-triaged
