### PR TITLE
const-eval: always do mem-to-mem copies if there might be padding involved

### LINKED ISSUE #148470: Partial pointers in padding can make const-eval fail
I'm not sure if this is a bug or not.
```rust
#![allow(unused)]

#[repr(C, align(16))]
#[derive(Clone, Copy)]
struct Thing {
    x: u128,
    y: u64,
    // Replace the above line with the below line to make it stop compiling
    // y: std::mem::MaybeUninit<u64>,
    // 8 bytes of padding here
}
#[derive(Clone, Copy)]
union PreservePad {
    thing: Thing,
    bytes: [u8; 32],
}

const A: Thing = unsafe {
    let mut buffer = [PreservePad { bytes: [0u8; 32] }; 2];
    (&raw mut buffer).cast::<&i32>().byte_add(28).write_unaligned(&1);
    buffer[0].thing
};

fn main() {}
```

The above code compiles fine, even in Miri. However, changing the `y: u64`line to `y: std::mem::MaybeUninit<u64>` causes the following compile error:

```
error[E0080]: unable to read parts of a pointer from memory at alloc4
  --> src/main.rs:21:5
   |
21 |     buffer[0].thing
   |     ^^^^^^^^^^^^^^^ evaluation of `A` failed here
   |
   = help: this code performed an operation that depends on the underlying bytes representing a pointer
   = help: the absolute address of a pointer is not known at compile-time, so such operations are not supported

For more information about this error, try `rustc --explain E0080`.
```

It seems that copying `Thing` in consteval discards the padding if `y` is a `u64`, but copies the padding if `y` is a `MaybeUninit<u64>`. This is implemented in the compiler [here](https://github.com/rust-lang/rust/blob/90b65889799733f21ebdf59d96411aa531c5900a/compiler/rustc_const_eval/src/interpret/place.rs#L880) and [here](https://github.com/rust-lang/rust/blob/90b65889799733f21ebdf59d96411aa531c5900a/compiler/rustc_const_eval/src/interpret/operand.rs#L593).

Normally, this implementation detail is observable in user code only by, say, printing padding bytes after doing a copy, which is UB. However, the compiler also cares about the contents of padding bytes potentially containing pointer fragments, making the implementation detail observable in user code without invoking UB.

cc @RalfJung

Somewhat related to https://github.com/rust-lang/rust/issues/147959 and https://github.com/rust-lang/rust/pull/148259, but this issue doesn't depend on those two issues.

### Meta

Reproducible on the playground with stable rust version 1.91.0

### PR DESCRIPTION
**Pull request by RalfJung**
This is the final piece of the puzzle for https://github.com/rust-lang/rust/issues/148470: when copying data of a type that has padding, always do a mem-to-mem copy, so that we always preserve the source padding exactly. That prevents rustc implementation choices from leaking into user-visible behavior.

This is technically a breaking change: the example at the top of https://github.com/rust-lang/rust/issues/148470 no longer compiles with this. However, it seems very unlikely that anyone would have depended on this. My main concern is not backwards compatibility, it is performance.

Fixes rust-lang/rust#148470

---

> Actually that seems to be entirely fine, it even helps with some benchmarks! I guess the mem-to-mem codepath is actually faster than the scalar pair codepath for the copy itself. It can slow things down later since now we have to do everything bytewise, but that doesn't show up in our benchmarks and might not be very relevant after all (in particular, it only affects types with padding, so the rather common wide pointers still always use the efficient scalar representation).
> 
> So that would be my proposal to for resolving this issue then: to make const-eval behavior consistent, we always copy the padding from the source to the target. IOW, potentially pre-existing provenance in the target always gets overwritten (that part is already in https://github.com/rust-lang/rust/pull/148259), and potentially existing provenance in padding in the source always gets carried over (that's https://github.com/rust-lang/rust/pull/148967). If there's provenance elsewhere in the source our existing handling is fine:
> - If it's in an integer, that's UB during const-eval so we can do whatever.
> - If it's in a pointer, the the fragments must combine back together to a pointer or else we have UB.
> - If it's in a union we just carry it over unchanged.
> 
> @traviscross we should check that this special const-eval-only UB is properly reflected in the reference. Currently we have [this](https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html#r-undefined.const-transmute-ptr2int) but that only talks about int2ptr, not about invalid pointer fragments at pointer type. I also wonder if this shouldn't rather be part of ["invalid values"](https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html#r-undefined.validity) to make it clear that this applies recursively inside fields as well.
> EDIT: Reference PR is up at https://github.com/rust-lang/reference/pull/2091. 

 _Originally posted by @RalfJung in [#148470](https://github.com/rust-lang/rust/issues/148470#issuecomment-3538447283)_

> Worth noting that this does not resolve the concerns @theemathas had about `-Zextra-const-ub-checks` sometimes causing *more* code to compile. Specifically, with that flag, the behavior changes to "potentially existing provenance in padding in the source never gets carried over". However, it's a nightly-only flag (used by Miri) so while the behavior is odd, I don't think this is a problem. 

 _Originally posted by @RalfJung in [#148470](https://github.com/rust-lang/rust/issues/148470#issuecomment-3538450164)_

---

Related:

- https://github.com/rust-lang/rust/issues/148470
- https://github.com/rust-lang/reference/pull/2091

### CODE REVIEW

**Comment by saethlin** [comment]
That "regression" is between 0.15% and 0.06%. Since the effect is so miniscule my guess is that's the overhead of the new check itself.

However, it would be bad science to give this level of attention to the regressions while ignoring the improvements. A real understanding should be able to explain both.

The juice isn't worth the squeeze.

**Comment by RalfJung** [comment]
> Since the effect is so miniscule my guess is that's the overhead of the new check itself.

Yeah, that's my guess too. Maybe we could have a fast-path for reference types as we know those never have padding.

**Comment by RalfJung** [comment]
@bors try
@rust-timer queue

File: compiler/rustc_const_eval/src/interpret/place.rs [hunk 1]
```diff
@@ -885,10 +885,36 @@ where
...
+                false
+            }
+            BackendRepr::ScalarPair(left, right) => {
+                let left_size = left.size(self);
+                let right_size = right.size(self);
+                // We have padding if the sizes don't add up to the total.
+                left_size + right_size != src.layout().size
+            }
+            // Everything else can only exist in memory anyway.
+            _ => true,
```
Comment (JonathanBrouwer) [inline compiler/rustc_const_eval/src/interpret/place.rs]: Nit: In these kind of cases I like still explicitly listing all the variants so if new variants are added we get an error here that forces us to think about the case. 

Side question: Is a `SimdVector` always memory only during const eval, even if they are small? From reading the code I think it is, but would like to verify as I'm not super familiar with this code

**Review by JonathanBrouwer — APPROVED** [review]
Code looks good to me with one nit/question.
We need to wait for crater & lang team

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148967/e1a2ec605124d9f9b0095435faef70bd4bd3f128..4ba01da4a6bb60b7a4fa6a621520dfd497f61479)*

File: compiler/rustc_const_eval/src/interpret/place.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/place.rs]: > Nit: In these kind of cases I like still explicitly listing all the variants so if new variants are added we get an error here that forces us to think about the case.

Sure, I can add them. Note that in this case, `true` is the safe choice, so it'd never be wrong even if a new variant is added.

> Side question: Is a SimdVector always memory only during const eval, even if they are small? From reading the code I think it is, but would like to verify as I'm not super familiar with this code

Yeah, the interpreter always puts SimdVector in memory, we don't have an immediate representation for them.

**Comment by RalfJung** [comment]
In terms of those 6 regressions
- There's an ICE that seems unrelated ("no resolution for an import")
- "unable to start container"
- "unable to get packages from source"
- A build failure in a C/C++ dependency

So, those all seem spurious too.

**Comment by RalfJung** [comment]
I guess here is another way to frame it:

Generally, it is correct for a Rust implementation to implement a typed copy via an untyped copy. That just reduces how much UB there is. The const-eval interpreter, at the moment, performs something very close to proper typed copies for types that happen to get `Scalar` or `ScalarPair` layout -- but that's not a stable guarantee, so this does not leak the arbitrary layout choices in a meaningful way.

However, for types with padding, due to the "no pointer fragments in final value" check, whether we do a typed copy or not becomes actually observable in UB-free code. This can go both ways: there are cases where doing the typed copy makes more code compile (because we avoid copying pointer fragments in padding that later cause problems), and there are cases where doing the typed copy makes less code compile (because the pointer fragments in padding that we copy can combine with other pointer fragments to form a full pointer which satisfies the "no pointer fragments" check). So to make things behave consistently, I propose we have const-eval always fall back to an untyped copy when there is padding. This means we miss some UB, but it ensures behavior is independent of rustc layout choices.

**Comment by RalfJung** [comment]
After some more discussion with @Nadrieril, let me try to phrase this in terms of what we might say in the reference (instead of phrasing this in terms of breaking changes, which is what I did so far). I will assume that we do want to keep supporting pointer fragments (since they make low-level unsafe code during const-eval behave more like at runtime). First, a recap of some relevant facts:
- We rely on linkers to deal with pointers in the final values of consts, and linkers don't support pointer fragments.
- The result of a single const-eval query is more than just one value. It can be multiple allocations, and we don't have type information for all of them. Today we could probably get type information for all of them if we tried hard enough (multiple allocations can only arise due to temporary lifetime extension so we could use the type of that temporary). In the future however, we want to allow heap allocations during const-eval and turning those allocations into global memory that can be accessed at runtime, and there's no natural way to get type information for these heap allocations. We could make the "carry alloc to runtime" operation typed, but that would feel quite strange.

As a consequence, we can't know which bytes in the result are padding, and if we see a pointer fragment, we have to hard error.  For the Language Reference, we seem to have two choices:
- We fully nail down when which byte of a const-eval result is a pointer fragment. That would mean specifying and then never changing the exact implementation strategy of typed copies: which exact bytes get copied from where to where, even when that cannot be observed in the AM (since it would be UB for the program to check, since those bytes are nominally uninitialized).
- We say that basically any uninit byte in the result may actually end up being a pointer fragment. This means the compiler could legally fail to compile any time there's an uninit byte in the result -- which of course it won't, but we make no hard stable guarantees for when exactly this will or will not fail. It's kind of a cop-out but also avoids us having to nail down details of the const-eval interpreter that cannot be observed in the AM.

**Comment by traviscross** [comment]
Thanks for running those numbers.  Does caching/memoizing come into play for optimizing this (and are we doing any now)?  (Is that hard here?)  As described ("doing a full traversal"), it seems the sort of thing that would be at risk of traversing the same path repeatedly, e.g. as a final value is built up from parts.  Without memoizing, it's easy to see how this would go `O(N^2)`.

**Comment by RalfJung** [comment]
There's currently no caching of any sort. Also, adding caching is not trivial... the naive option of "here's some pairs of types and raw byte lists for which we can skip validation in the future" would quickly consume huge amounts of RAM caching values we'll never need again. Representing raw byte lists (including uninit and provenance) is itself non-trivial, and even just checking the cache would be expensive.

Or alternatively we build a system where we remember "the bytes at offset O in allocation A have been validated for type T" -- but  we'd have to be really sure we catch all codepaths where memory gets changed so that we can invalidate the cache. Also, Rust moves values around a lot, so this alone wouldn't suffice; we'd also want this information to be preserved when copying things from one place to another. This could be an interesting student project to speed up Miri, but it's not going to happen short-term.

**Comment by Nadrieril** [comment]
I find these perf results rather encouraging actually, given that this was a naive implementation. Noticeable regressions are on a limited set of tests, all of them stress-tests. I don't mind the currently-proposed lang decision so that we can get this merged, but if anyone with enough const-eval knowledge could try a non-naive version I'd be keen to revisit this.

**Comment by tmandry** [comment]
@rfcbot reviewed

Ok, the proposal on the table sounds reasonable. Options I can see for having a more satisfying story in the future:

1. Uninitialize padding on typed copy (if we can improve the performance enough).
2. Tracking type information + Ralf's suggestion in https://github.com/rust-lang/rust/pull/148967#issuecomment-3591914653 for a typed "carry alloc to runtime" operation – that sounds like it would be very visible to end-users. I could imagine making optional to users for more precise tracking if this error becomes a problem for them.

The second brings to mind a more general typed allocator API, which also would have to be optional. Then we could have typed/untyped allocations just as we have typed/untyped copies. That could be useful e.g. for heap profiling applications, among other things.

I'm certain I'm not the first to think of this though. I guess the reasons not to go down this path are some combination of the following; are there others?

1. Not wanting added monomorphization; needing a TypeId mechanism that works for non-`'static` types to avoid it
2. Not being usable in 100% of applications
3. Prior art
4. Lack of need

**Comment by theemathas** [comment]
Turns out that there is already some code in the wild that depends on how exactly we do typed copies in consteval, according to [crater](https://github.com/rust-lang/rust/pull/149901#issuecomment-3691427153) on the PR implementing an alternative to this PR.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by RalfJung** [comment]
Based on [earlier review](https://github.com/rust-lang/rust/pull/148967#pullrequestreview-3474402545):
@bors r=JonathanBrouwer
