### PR TITLE
Do not consider match/let/ref of place that evaluates to `!` to diverge, disallow coercions from them too

### LINKED ISSUE #117288: incorrect UB when when a `!` place is constructed (but not loaded!)
This code shouldn't have UB but Miri reports UB and rustc generates a SIGILL:
```rust
#![feature(never_type)]
fn main() {
    unsafe {
        let x = 3u8;
        let x: *const ! = &x as *const u8 as *const _;
        let _ = *x;
    }
}
```

Thanks to @Nadrieril for finding this.

[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Soundness.20issues.20around.20.60let.20_.60.20and.20.60!.60)

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #117288.

This PR implements a heuristic which disables two things that are currently being performed on the HIR when we have **expressions that involve place-like expressions that point to `!`**. Specifically, it will (in certain cases explained below):

### (1.) Disable the `NeverToAny` coercion we implicitly insert for `!`.

Which fixes this inadvertent, sneaky unsoundness:

```
unsafe {
    let x: *const ! = &0 as *const u8 as *const !;
    let _: () = *x;
}
```

which is UB because currently rust emits an *implicit* NeverToAny coercion even though we really shouldn't be, since there's no read of the value pointed by `x`.

### (2.) Disable the logic which considers expression which evaluate to `!` to diverge, which affects the type returned by the containing block.

Which fixes this unsoundness:

```
fn make_up_a_value<T>() -> T {
    unsafe {
        let x: *const ! = &0 as *const u8 as *const !;
        let _ = *x;
    }
}
```

We disable these two operations **if** the expression is a place-like expression (locals, statics, field projections, index operations, and deref operations), and if the parent expression is either:
(1.) the LHS of an assignment
(2.) AddrOf
(3.) A match or let **unless** all of the *patterns consitute a read*, which is explained below:

And finally, a pattern currently is considered to constitute a read **unless** it is a wildcard, or an OR pattern. An OR pattern is considered to constitute a read if all of its subpatterns constitute a read, to remain as conservative as possible in cases like `_ | subpat` or `subpat | _`. 

All other patterns are considered currently to constitute a read. Specifically, because `NeverToAny` is a coercion performed on a *value* and not a *place*, `Struct { .. }` on a `!` type must be a coercion currently, and we currently rely on this behavior to allow us to perform coercions like `let _: i32 = x;` where `x: !`.

This is already considered UB by [miri](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=daf3a2246433fe43fdc07d1389c276c9), but also means it does not affect the preexisting UB in this case:

```
let Struct { .. } = *never_ptr;
```

Even though it's likely up for debate since we're not actually reading any data out of the struct, it almost certainly causes inference changes which I do *NOT* want to fix in this PR.

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot crates=https://gist.githubusercontent.com/compiler-errors/4a09d64cd15dc3dca50edeea26cc9938/raw/b4181c225709e120a11d91cce69d0d4da3e652d0/regressed.txt

**Comment by traviscross** [comment]
@craterbot p=1

(Bump priority is this will run quickly.)

**Comment by compiler-errors** [comment]
yippee

File: tests/ui/never_type/diverging-place-match.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#![feature(never_type)]
+
+fn make_up_a_value<T>() -> T {
+    unsafe {
+    //~^ ERROR mismatched types
+        let x: *const ! = 0 as _;
+        let _: ! = *x;
```
Comment (RalfJung) [inline tests/ui/never_type/diverging-place-match.rs:7]: It's probably on your radar, but it would be good to have more tests:
- also test `let _` without type annotations (that has sometimes behavior differently)
- also test `match *x { _ => {} }`
- also test the case where a field projection is involved, not just a deref: `x: *const (!, ())`, and then do `(*x).0`.

Comment (compiler-errors) [reply tests/ui/never_type/diverging-place-match.rs:7]: Thanks. I appreciate making sure this is thorough -- I'll have to rewrite this history and clean up the PR, but I'll be certain to include the tests.

**Comment by compiler-errors** [comment]
OK, I think this is actually ready. Anyone can chime in on what needs better explanation.

@rustbot ready
r? types

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 2]
```diff
@@ -1018,8 +1029,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         debug!("coercion::can_with_predicates({:?} -> {:?})", source, target);
 
         let cause = self.cause(DUMMY_SP, ObligationCauseCode::ExprAssignable);
-        // We don't ever need two-phase here since we throw out the result of the coercion
-        let coerce = Coerce::new(self, cause, AllowTwoPhase::No);
+        // We don't ever need two-phase here since we throw out the result of the coercion.
+        // We also just always set `coerce_never` to true, since this is a heuristic.
+        let coerce = Coerce::new(self, cause, AllowTwoPhase::No, true);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/coercion.rs:1034]: hmm, that means we can end up with `can_coerce` returning false and then coercing failing. I'd have to look at how this is used to check whether it may be a problem (or you tell me)

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: Well firstly, `can_coerce` is called on arbitrary types that are not associated with values or places, so getting this 100% right is literally intractible.

`can_coerce` is used like `can_eq`, where it is *heuristic*. It should never be used for *correctness*, since it also records no adjustments and has no side-effects.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 3]
```diff
@@ -257,6 +260,80 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        // "syntactic" place exprs since if the base of a field projection is
+        // not a place then it would've been UB to read from it anyways since
+        // that constitutes a read.
+        if !expr.is_syntactic_place_expr() {
+            return true;
+        }
+
+        // If this expression has any adjustments applied after the place expression,
+        // they may constitute reads.
+        if !self.typeck_results.borrow().expr_adjustments(expr).is_empty() {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:289]: is this incorrect for `Deref` adjustments? 🤔

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:289]: A deref adjustment of a place expr would constitute a read, no? We'd then be derefing the place which requires a value.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: yes, I wanted to know whether we use it anywhere to decide "yes, this is a coercion" only to later error. i.e. whether this results in unintended errors

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: Yeah, I checked and there is none. Only in suggestion code or clippy.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:289]: Although It's kinda moot -- we wouldn't ever be applying a deref adjustment to a place of type `!` anyways. The only adjustment we apply to `!` is `NeverToAny`. I could adjust this to check for just that I guess.

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/expr.rs:289]: but isn't this about the final type of an expr? i.e. in the `ty.is_never() && self.expr_constitutes_read(expr)` check in `check_expr_with_expectation_and_args`.

if you have some expr `foo()` of type `&!` which is implicitly deref'd to `!` (which probably can't happen), then we check whether the type *after adjustments* is `!` and whether that is the type of a place or value? I.e. it doesn't matter whether  `foo()` itself got converted to a value, it's whether the result after adjustments is a value 🤔

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 4]
```diff
@@ -257,6 +260,80 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                kind: hir::ExprKind::Let(hir::LetExpr { init: target, pat, .. }),
+                ..
+            }) if expr.hir_id == target.hir_id && !pat_does_read(*pat) => false,
+            hir::Node::Expr(hir::Expr { kind: hir::ExprKind::Match(target, arms, _), .. })
+                if expr.hir_id == target.hir_id
+                    && !arms.iter().any(|arm| pat_does_read(arm.pat)) =>
+            {
+                false
+            }
+            _ => true,
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:333]: given that returning `true` may introduce coercions (and returning `false` is always correct), i'd like to use an exhaustive match here

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 5]
```diff
@@ -277,6 +278,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             }
         };
 
+        // All other patterns constitute a read, which causes us to diverge
+        // if the type is never.
+        if ty.is_never() && !matches!(pat.kind, PatKind::Wild | PatKind::Never | PatKind::Or(_)) {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:283]: same here, not diverging is always correct, incorrectly diverging is unsound. So please exhaustively match the "does diverge" variants

**Review by lcnr — COMMENTED** [review]
r=me after types FCP (and review comments)

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:289]: Yeah, in which case I feel like it's most conservative to just remove this check.

File: src/tools/miri/tests/pass/uninhabited_not_read.rs
Comment (RalfJung) [inline src/tools/miri/tests/pass/uninhabited_not_read.rs:1]: Instead of adding a new test, can you add this to tests/pass/underscore_pattern.rs ?

File: src/tools/miri/tests/pass/uninhabited_not_read.rs [hunk 6]
```diff
@@ -0,0 +1,24 @@
+//@ edition: 2021
+// In ed 2021 and below, we don't fallback `!` to `()`.
+// This would introduce a `! -> ()` coercion which would
+// be UB if we didn't disallow this explicitly.
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/uninhabited_not_read.rs:4]: I don't understand the comment... does that mean we should test with two revisions, edition 2021 and 2024? Neither should be UB here, right?

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs:4]: Not necessary to test in 2024 but I could add it just for completeness. 2024 should be equivalent to the explicitly ascribed `: !` case.

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs:4]: So it seems that miri tests don't seem to allow editions and the fallback behavior doesn't *really* matter since I've got UI tests for that, and I'd rather not block this fix on tweaking miri testing infra lol.

Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: We usually set the edition via `@compile-flags: --edition <num>`, I think.

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Can you point me to a test that actually does that in the miri test suite? I didn't see any, and I got errors saying that the edition was being set twice when I tried that.

Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Ah no, we set an edition for all tests by default. Yeah...
You can still add the fallback code as a test, right? Currently we use the 2021 edition so it does test the right thing. (And then we should have a Miri issue to track letting tests set the edition themselves.)

Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: OTOH [this](https://github.com/rust-lang/rust/blob/f7c938aaf0f497bb23e7338156435c3bf261e052/src/tools/miri/tests/ui.rs#L77) looks like ui_test understands editions so per-file and even per-revision edition should be possible. We are on a quite old version of ui_test though so maybe that's why it did not work?
Cc @oli-obk

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: I cannot write the test that would force fallback to `()` since that's a compile error now. I added the test as-is from the issue, though.

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Anyways, I kinda don't want to tangle this up into this PR since I wrote sufficient UI tests to exercise this behavior, so perhaps file an issue to separate this? :D

Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: > I cannot write the test that would force fallback to `()` since that's a compile error now. I added the test as-is from the issue, though.

You added a test wanting edition 2021, and the edition Miri uses is 2021, so the test you originally intended should still be possible?

Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Opened an issue: https://github.com/rust-lang/miri/issues/3860

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: https://github.com/rust-lang/rust/pull/129392/files#diff-bad0427000dea00ae1fca50f869219d25310d8b2f4165c987e14041c4576e18aR102-R117

This is what I wanted to test.

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Nothing else needs to be done here unless you specifically want to see something exercised, otherwise I think we are just going in circles here lol

**Comment by compiler-errors** [comment]
Anyways I believe this is ready for FCP.

@rfcbot fcp merge

File: src/tools/miri/tests/pass/underscore_pattern.rs [hunk 7]
```diff
@@ -65,7 +91,27 @@ fn invalid_let_type_annotation() {
...
+// Regression test from <https://github.com/rust-lang/rust/issues/117288>.
+fn never() {
+    unsafe {
+        let x = 3u8;
+        let x: *const ! = &x as *const u8 as *const _;
+        let _: ! = *x;
+    }
+
+    // Without a type annotation, make sure we don't implicitly coerce `!` to `()`
+    // when we do the noop `*x`.
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/underscore_pattern.rs:111]:
```suggestion
    // when we do the noop `*x` (as that would require a `!` *value*, creating which is UB).
```

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 8]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        }
+    }
+
+    /// Whether this pattern constitutes a read of value of the scrutinee that
+    /// it is matching against.
+    ///
+    /// See above for the nuances of what happens when this returns true.
+    pub(super) fn pat_constitutes_read(&self, pat: &hir::Pat<'_>) -> bool {
+        let mut does_read = false;
+        pat.walk(|pat| {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:408]: general style review. Should `Pat::walk` use `ControlFlow` instead of a `bool`?

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 9]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    ExprKind::Assign(lhs, _, _) => {
+                        // Only the LHS does not constitute a read
+                        expr.hir_id != lhs.hir_id
+                    }
+
+                    // If we have a subpattern that performs a read, we want to consider this
+                    // to diverge for compatibility to support something like `let x: () = *never_ptr;`.
+                    ExprKind::Match(scrutinee, arms, _) => {
+                        assert_eq!(scrutinee.hir_id, expr.hir_id);
+                        arms.iter().any(|arm| self.pat_constitutes_read(arm.pat))
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:307]: `any` vs `all`?

I am a bit confused by how this is supposed to work, i.e. whether we want to treat this as a 'proper soundness issue' and be conservative with what we allow, or whether it's fine to allow some code to introduce reads evne though they aren't strictly necessary :thinking: 

this allows the following, where afaik the first branch does not read from `*x` but is still treated as unreachable
```rust
#![feature(never_type)]
fn foo<'a>(x: *const !) -> ! {
    unsafe {
        match *x {
            _ => {
                let y: &'a () = &();
                let z: &'static () = y;
                return *x;
            },
            value => loop {}
        }
    }
}
```

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:307]: Well the correct way of doing this would be to implement some sort of covering algorithm with unreachable pattern arms, or at least an approximation with `_` and `!` patterns. Especially bc we only care about when the _ pattern is reading the `!` part of a complex lvalue like `(T, !)`.

Kinda think that what is implemented here is at least better than the status quo tho.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: Well ideally it only returns false negatives since we introduce coercions when it returns true. 

But right now it's only more correct than the status quo, and not 100% sound. e.g. in cases where matches may or may not read, like `(_ | 1)` in a pattern.

Comment (RalfJung) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: That pattern never reads, right? In left-to-right order, `_` always matches, so we never reach the `1`.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: right, but to detect such cases we need to consider arbitrarily complex patterns.

Comment (RalfJung) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: So what is the consequence of not doing that? You said it's unsound -- could you give an example?

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 9 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/expr.rs:307]: I totally agree this is an improvement over the status quo. While I understand the difficulties in implementing this correctly, I do not understand why we err on the side of inserting *unsound* coercions instead of incorrectly errororing in very rare cases by preventing coercions which could be allowed.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:307]: Presumably because changing the *existing* behavior (recall that we unconditionally insert these coercions today) is going to break existing code that relies on these coercions. I can try to just make a version that requires all sub patterns to be reads, and see what that breaks I guess.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 10]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    /// coercion for values of type `!`.
+    ///
+    /// This function generally returns `false` if the expression is a place
+    /// expression and the *parent* expression is the scrutinee of a match or
+    /// the pointee of an `&` addr-of expression, since both of those parent
+    /// expressions take a *place* and not a value.
+    ///
+    /// This function is unfortunately a bit heuristical, though it is certainly
+    /// far sounder than the prior status quo: <https://github.com/rust-lang/rust/issues/117288>.
+    pub(super) fn expr_constitutes_read(&self, expr: &'tcx hir::Expr<'tcx>) -> bool {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:280]:
```suggestion
    pub(super) fn expr_guaranteed_to_constitute_read(&self, expr: &'tcx hir::Expr<'tcx>) -> bool {
```
ideally

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 11]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        self.pat_constitutes_read(*pat)
+                    }
+
+                    // Any expression child of these expressions constitute reads.
+                    ExprKind::Array(_)
+                    | ExprKind::Call(_, _)
+                    | ExprKind::MethodCall(_, _, _, _)
+                    | ExprKind::Tup(_)
+                    | ExprKind::Binary(_, _, _)
+                    | ExprKind::Unary(_, _)
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:320]: can you exhaustively match on `UnOp` here

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 12]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                unreachable!("no sub-expr expected for {parent_node:?}")
+            }
+        }
+    }
+
+    /// Whether this pattern constitutes a read of value of the scrutinee that
+    /// it is matching against.
+    ///
+    /// See above for the nuances of what happens when this returns true.
+    pub(super) fn pat_constitutes_read(&self, pat: &hir::Pat<'_>) -> bool {
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:406]:
```suggestion
    pub(super) fn pat_guaranteed_to_constitute_read(&self, pat: &hir::Pat<'_>) -> bool {
```
I just want a name which makes sure that if this returns `true`, then it's definitely a read.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 13]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+    /// if the expression evaluates to `!`, and if we should insert a `NeverToAny`
+    /// coercion for values of type `!`.
+    ///
+    /// This function generally returns `false` if the expression is a place
+    /// expression and the *parent* expression is the scrutinee of a match or
+    /// the pointee of an `&` addr-of expression, since both of those parent
+    /// expressions take a *place* and not a value.
+    ///
+    /// This function is unfortunately a bit heuristical, though it is certainly
+    /// far sounder than the prior status quo: <https://github.com/rust-lang/rust/issues/117288>.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:279]: hopefully outdated (if crater with the overly restrictive impl succeeds)

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 9 above)
Comment (WaffleLapkin) [reply compiler/rustc_hir_typeck/src/expr.rs:307]: I don't think there will be basically any breakage, this requires you to match on a value of type `!` and bind it via `_`, and use incorrect assumptions we've made in the past. Seems quite unlikely, although only actual tests can tell.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 13 above)
Comment (WaffleLapkin) [reply compiler/rustc_hir_typeck/src/expr.rs:279]: It would still maybe make sense to make the check precise rather than overly restrictive in the future though?

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 14]
```diff
@@ -257,6 +263,175 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+
+    /// Whether this pattern constitutes a read of value of the scrutinee that
+    /// it is matching against.
+    ///
+    /// See above for the nuances of what happens when this returns true.
+    pub(super) fn pat_constitutes_read(&self, pat: &hir::Pat<'_>) -> bool {
+        let mut does_read = false;
+        pat.walk(|pat| {
+            match pat.kind {
+                hir::PatKind::Wild | hir::PatKind::Never | hir::PatKind::Or(_) => {
```
[the remark this answers is not in the document]
Comment (WaffleLapkin) [reply compiler/rustc_hir_typeck/src/expr.rs:410]: Yes. See examples from the tracking issue #118155 and [WIP RFC](https://hackmd.io/XPZfEzcGRy2P7woORHUOcQ#Guide-level-explanation), the latter specifically has cases which do not work with `Err(_)` (which doesn't cause a read of `!`) but do with `Err(!)` (which seems to do a read). But @Nadrieril just to be sure.,

[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_hir_typeck/src/expr.rs:410]: Yeah, the point of the `!` pattern is to actually witness the impossibility of the current execution -- it should compile down to a `GetDiscriminant` on an enum without variants, which is equivalent to `Unreachable`. I guess we also allow it for `!`, where it should behave correspondingly.

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 15]
```diff
@@ -277,6 +278,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             }
         };
 
+        // All other patterns constitute a read, which causes us to diverge
+        // if the type is never.
+        if ty.is_never() && self.pat_constitutes_read(pat) {
+            self.diverges.set(self.diverges.get() | Diverges::always(pat.span));
+        }
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/pat.rs:285]: It's just a leftover comment.

[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/pat.rs:285]: We need it if we read `!` out of a field of a pattern, though. Consider:

```
struct Foo {
    pat: !,
}

fn uwu(f: Foo) {
    let Foo { pat } = f;
}
```

which should diverge.

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 16]
```diff
@@ -1193,7 +1209,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         // probably aren't processing function arguments here and even if we were,
         // they're going to get autorefed again anyway and we can apply 2-phase borrows
         // at that time.
-        let mut coerce = Coerce::new(self, cause.clone(), AllowTwoPhase::No);
+        let mut coerce = Coerce::new(self, cause.clone(), AllowTwoPhase::No, true);
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1212]: `CoerceMany` only ever operates on values.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1034]: > You said it's unsound

Because the pattern does not read but we consider it to read because one of the subpatterns reads, inserting a `NeverToAny` coercion is unsound.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 8 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:408]: Should file that as a separate issue, seems like a good beginner issue.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 11 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:320]: Remember that we're matching on the *parent* node here, not the child node

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 12 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs]: I renamed this to `pat_guaranteed_to_constitute_read_of_never` since we consider patterns like `Struct { .. }` to read even though (unless they're enum variants) they don't technically *need* to, but they do insert `NeverToAny` coercions.

If we wanted to consider the full set of patterns and their readability we'd need to recurse on things like struct and tuple subpatterns, derefs, etc. and I think that's somewhat past the scope of this PR.

File: tests/mir-opt/uninhabited_enum.rs
[the remark this answers is not in the document]
Comment (compiler-errors) [reply tests/mir-opt/uninhabited_enum.rs:1]: Yeah, I changed it and restored the old comment.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 9 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs]: A side-effect of `all` is that `match *never_ptr {}` is considered to be a diverging read of `*never_ptr`, which I actually think is correct behavior (since it's effectively like a read of an empty enum's discriminant).

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 11 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/expr.rs:320]: > Why? All unops are reads. We're not exhaustively matching on binops either.

`&` is also an unary operation (but currently a different expr kind), so I am not convinced that this will stay that way forever. I would also like an exhaustive match for binops but am less worried that we'll ever end up with a non-reading binop

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 17]
```diff
@@ -400,36 +400,45 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     }
 
     /// Whether this pattern constitutes a read of value of the scrutinee that
-    /// it is matching against.
+    /// it is matching against. This is used to determine whether we should
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/expr.rs:403]: ... and consider pattern reads to diverge.

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/pat.rs]: Well, we don't handle `Ok(whatever) | Err(!)` correctly if we consider this to diverge. I don't think it's strictly necessary.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (Nadrieril) [reply compiler/rustc_hir_typeck/src/expr.rs]: Yep, confirmed

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: Right but what does that mean? In terms of the surface language? That's why I asked for an example. :)

Following the other threads here, it seems there's actually quite a bit of design space. When this is done, could you write a spec of what got implemented -- i.e., which patterns in `let pat = *ptr` actually cause a value to be manifest?

FWIW I would expect `let (_, _) = *ptr;` on a pair to be equivalent to `let _`, so I am a bit surprised when you said that `Struct { .. }` is considered to produce a value. In fact things can get more subtle than value vs no value -- with enums, it's really about which operations do we actually perform on them? In `match`, we might do a discriminant read but then not read any of the fields; the same could presumably happen here?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: Frankly I do not have the energy or want to put in any effort to fix this any further.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: Like, I literally don't care about the cases which are up for debate or which may or may not produce a read depending on the MIR, because these checks are performed on the HIR and I do not have the time or energy to make these checks more complicated than they are now. I am setting out in this PR to fix the egregiously unsound cases ONLY, and improving these semantics further can be done as a follow-up.

Comment (RalfJung) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: I don't even know which cases you're talking about, is the problem.^^ I don't know HIR. So I don't even know what the questions are, which cases you consider "egregiously unsound", and which "not-so-egregiously unsound". That's why I asked, once this PR lands, for an explanation of what even got implemented.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: This PR implements a heuristic which disables two things that are currently being performed on the HIR when we have expressions that involve place-like expressions that point to `!`. Specifically, it will:

1. Disable the `NeverToAny` coercion we implicitly insert.
2. Disable the logic which considers the expression to diverge, which affects the type returned by the containing block.

We do those IF the expression is a place-like expression, and the parent expression is either:
1. the LHS of an assignment
2. AddrOf
3. A match or let IF all of the *patterns consitute a read*

And finally, a pattern currently is considered to constitute a read UNLESS it is a wildcard or a OR of wildcards. All other patterns are considered currently to constitute a read. Specifically, because `NeverToAny` is a coercion performed on a *value* and not a *place*, `Struct { .. }` on a `!` type must be a coercion currently. This is already considered UB by [miri](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=daf3a2246433fe43fdc07d1389c276c9).


That means it does not affect the preexisting UB in this case:

```
let Struct { .. } = *never_ptr;
```

Even though it's likely up for debate, it almost certainly causes inference changes which I do *NOT* want to fix in this PR.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: The "not so egregiously unsound" case is basically the last example I gave, since that is arguably *not* even unsound but just regular UB because users already need to accept that they're doing sketchy stuff by wrapping their code in `unsafe {}`, and the fact that the coercion there is implicitly occurring is kinda just 🤷.

Recall that I'm primarily motivated by trying to make `&raw` sound, and none of this affects that. The only stuff that's "up for debate" here is just the semantics surrounding pattern matching, which I think are probably incredibly rare, already *more* UB than they are than after this PR, and are easily refined later.

**Comment by compiler-errors** [comment]
@craterbot check

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: I do want to apologize though, my earlier comment here was a bit dramatic since I have (not the fault of the reviewers, of course) been a bit overwhelmed by the process of carrying out this work with fixing never+place exprs in the HIR, especially since my original desire was just to fix the simplest cases of this (e.g. the AddrOf case).

I do agree that there is a lot of design space for how we treat patterns, and I wasn't clear that when I said I didn't really want to further work on this, I really meant I didn't want to tweak this PR in cases that are presumably more "up for debate" like struct patterns that do not read, especially given how the compiler treats them on nightly. 

I can certainly document where this PR ends up if and when it does actually land, though I am not too certain where that documentation would actually live.

**Comment by compiler-errors** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-129392-1/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
I think all of the crater failures are spurious, including qroc which does look like it's failing for some reason but it doesn't seem to be due to any never type dereferencing 🤔 https://crater-reports.s3.amazonaws.com/pr-129392-1/try%2319c032689f1eaa3070436eefb48228917adf58fa/reg/qroc-0.1.0/log.txt

If it shows up again in the failure list after this retry, then I'll look a bit more into it.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1039]: > But here *ptr does not have type ! and IIUC the special behavior that triggers the coercion is specific to !, it does not apply to all uninhabited types?

Correct. We only perform this behavior of `!` and no other uninhabited types. That's partly why I renamed this function to `..._guaranteed_to_constitute_read_for_never`, since it only really is tuned for `!`.

File: src/tools/miri/tests/pass/uninhabited_not_read.rs (hunk 6 above)
Comment (RalfJung) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: FWIW once https://github.com/rust-lang/rust/pull/130467 lands, `//@edition` should work in Miri's ui tests, so if you want you can extend the test with revisions to run in both editions, or something like that.

Comment (compiler-errors) [reply src/tools/miri/tests/pass/uninhabited_not_read.rs]: Cool, thanks

**Comment by compiler-errors** [comment]
I believe this is ready for review. I will open an issue as requested by @RalfJung on further tightening of what cases we allow `NeverToAny` coercions for places of type `!`.

@rustbot ready

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 18]
```diff
@@ -257,6 +263,184 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            // can lead to unsoundness.
+            hir::PatKind::Or(subpats) => {
+                subpats.iter().all(|pat| self.pat_guaranteed_to_constitute_read_for_never(pat))
+            }
+
+            // Does constitute a read, since it is equivalent to a discriminant read.
+            hir::PatKind::Never => true,
+
+            // All of these constitute a read, or match on something that isn't `!`,
+            // which would require a `NeverToAny` coercion.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:428]: is that right?

A binding pattern `let ref q = *ref_to_never;` does not read from `ref_to_never`. I don't think this needs any FCP changes or another crater run.

All the other ones look good to me. I am unsure whether it's possible to write a test for that rn as I think we don't coerce there rn? 

I guess please extend the tests/ui/never_type/diverging-place-match.rs to also test `let ref x: () = *ptr_to_never`;`

**Review by lcnr — COMMENTED** [review]
final nit, then r=me

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 18 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:428]: Sure, and I can add it to the issue I opened too.

**Comment by compiler-errors** [comment]
Rebased to add a match arm for new node type.

@bors r=lcnr

**Comment by matthiaskrgr** [comment]
@bors retry 
yielding to #131320
