### PR TITLE
Reject `CVarArgs` in `parse_ty_for_where_clause`

### LINKED ISSUE #125847: ICE:  `TyKind::CVarArgs` should have been handled elsewhere
auto-reduced (treereduce-rust):
````rust
trait Trait<Input> {}

async fn walk2<F: 'static>(filter: F)
where
    for<'a> F: Trait<&'a u32> + 'a,
    for<'a> ...: 'a,
{
}

fn main() {}


````

original:
````rust
//@ edition:2018
//@ check-pass

trait Trait<Input> {
    type Output;
}

async fn walk<F>(filter: F)
where
    for<'a> F: Trait<&'a u32> + 'a,
    for<'a> <F as Trait<&'a u32>>::Output: 'a,
{
}

async fn walk2<F: 'static>(filter: F)
where
    for<'a> F: Trait<&'a u32> + 'a,
    for<'a> ...: 'a,
{
}

fn main() {}

````

Version information
````
rustc 1.80.0-nightly (20be84a7e 2024-05-31)
binary: rustc
commit-hash: 20be84a7e62af0a623af4bfb75df6d30cb39d6d0
commit-date: 2024-05-31
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zunstable-options --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `filter`
 --> /tmp/icemaker_global_tempdir.rDpA1ZHdMkLV/rustc_testrunner_tmpdir_reporting.yF5KcAa0ogWF/mvce.rs:3:28
  |
3 | async fn walk2<F: 'static>(filter: F)
  |                            ^^^^^^ help: if this is intentional, prefix it with an underscore: `_filter`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: trait `Trait` is never used
 --> /tmp/icemaker_global_tempdir.rDpA1ZHdMkLV/rustc_testrunner_tmpdir_reporting.yF5KcAa0ogWF/mvce.rs:1:7
  |
1 | trait Trait<Input> {}
  |       ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function `walk2` is never used
 --> /tmp/icemaker_global_tempdir.rDpA1ZHdMkLV/rustc_testrunner_tmpdir_reporting.yF5KcAa0ogWF/mvce.rs:3:10
  |
3 | async fn walk2<F: 'static>(filter: F)
  |          ^^^^^

warning: 3 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: `TyKind::CVarArgs` should have been handled elsewhere
 --> /tmp/icemaker_global_tempdir.rDpA1ZHdMkLV/rustc_testrunner_tmpdir_reporting.yF5KcAa0ogWF/mvce.rs:6:13
  |
6 |     for<'a> ...: 'a,
  |             ^^^
  |
note: delayed at compiler/rustc_ast_lowering/src/lib.rs:1471:39 - disabled backtrace
 --> /tmp/icemaker_global_tempdir.rDpA1ZHdMkLV/rustc_testrunner_tmpdir_reporting.yF5KcAa0ogWF/mvce.rs:6:13
  |
6 |     for<'a> ...: 'a,
  |             ^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (20be84a7e 2024-05-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by fmease**
Fixes #125847. This regressed in #77035 where the `parse_ty` inside `parse_ty_where_predicate` was replaced with the at the time new `parse_ty_for_where_clause` which incorrectly stated it would permit CVarArgs (maybe a copy/paste error).

r? parser

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me when green

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -344,8 +344,9 @@ impl<'a> Parser<'a> {
             match allow_c_variadic {
                 AllowCVariadic::Yes => TyKind::CVarArgs,
                 AllowCVariadic::No => {
-                    // FIXME(Centril): Should we just allow `...` syntactically
+                    // FIXME(c_variadic): Should we just allow `...` syntactically
                     // anywhere in a type and use semantic restrictions instead?
+                    // NOTE: This may regress certain MBE calls if done incorrectly.
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/ty.rs:349]: Drive-by update to this FIXME.

`c_variadic` is a better fit here. It can be revisited before its stabilization.

The disclaimer concerns code like

```rs
macro_rules! ck { ($ty:ty) => { compile_error!(""); }; (...) => {}; }
ck!(...);
```

which we don't want to regress. This can easily happen if `can_begin_type` gets updated. If we do want accept `...` given `$ty:ty`, this should probably happen as part of a new edition (cf. fragment specifier `expr_2021`, and `inline_const` in Rust 2024).

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/ty.rs:349]: i feel like `...` is not a real type and we shouldn't treat it like one lol

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/ty.rs:349]: Do u want to add a regression test?

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:349]: Yeah, can do.

Comment (fmease) [reply compiler/rustc_parse/src/parser/ty.rs:349]: > i feel like `...` is not a real type and we shouldn't treat it like one in macros lol

Yeah, I feel the same >.<

**Comment by fmease** [comment]
Ah, I forgot to mention that we're technically regressing stable code like `#[cfg(any())] fn f3() where for<> ...: {}` here. However, the likelihood that anybody relies on it is astronomically low (it requires a `for<...>` in front of it because `...` can't actually begin a type officially).

The MBE example I gave above is also unlikely to occur in practice but the chances are still way higher (ppl's DSLs are crazy sometimes, cc #115785).

@bors r=compiler-errors
