### PR TITLE
Suggestion to wrap inner types using 'allocator_api' in tuple

### LINKED ISSUE #83250: Hint for Vec<String, String>
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5f472854b25b6ccce15820ca0dd45c19

```rust
fn foo() {
    let _z: Vec<String, String> = vec![]; // A vector of string pairs, right?
}
```

The current output is:

```
error[E0658]: use of unstable library feature 'allocator_api'
 --> src/lib.rs:2:25
  |
2 |     let _z: Vec<String, String> = vec![]; // A vector of string pairs, right?
  |                         ^^^^^^
  |
  = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information

error[E0277]: the trait bound `String: Allocator` is not satisfied
   --> src/lib.rs:2:13
    |
2   |     let _z: Vec<String, String> = vec![]; // A vector of string pairs, right?
    |             ^^^^^^^^^^^^^^^^^^^ the trait `Allocator` is not implemented for `String`

error[E0308]: mismatched types
 --> src/lib.rs:2:35
  |
2 |     let _z: Vec<String, String> = vec![]; // A vector of string pairs, right?
  |             -------------------   ^^^^^^ expected struct `String`, found struct `std::alloc::Global`
  |             |
  |             expected due to this
  |
  = note: expected struct `Vec<String, String>`
             found struct `Vec<_, std::alloc::Global>`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors
```

Ideally the output should look like:

The above, plus:

```
hint: for a Vec of String pairs, try Vec<(String, String)>
```

Rationale: The current error messages assume that users know `Vec` has a second type param, which is rarely used. A vector of pairs is a fairly common type, and I suspect a lot of people make the mistake of forgetting the parentheses.

### PR DESCRIPTION
**Pull request by ken-matsui**
This PR provides a suggestion to wrap the inner types in tuple when being along with 'allocator_api'.

Closes https://github.com/rust-lang/rust/issues/83250

```rust
fn main() {
    let _vec: Vec<u8, _> = vec![]; //~ ERROR use of unstable library feature 'allocator_api'
}
```

```diff
 error[E0658]: use of unstable library feature 'allocator_api'
   --> $DIR/suggest-vec-allocator-api.rs:2:23
    |
 LL |     let _vec: Vec<u8, _> = vec![];
-   |                       ^
+   |                   ----^
+   |                   |
+   |                   help: consider wrapping the inner types in tuple: `(u8, _)`
    |
    = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information
    = help: add `#![feature(allocator_api)]` to the crate attributes to enable
```

### CODE REVIEW

**Comment by leonardo-m** [comment]
I don't understand what it's suggesting. Perhaps to replace Vec<u8, _> with Vec<u8, (_, _)> ?

**Comment by fbstj** [comment]
> I don't understand what it's suggesting. Perhaps to replace `Vec<u8, _>` with `Vec<u8, (_, _)>` ?

looking at #83250 makes it more obvious that it is suggesting `Vec<(u8, _)>`; ie not passing anything as the second (allocator) type to avoid the `alocator_api` entirely. maybe the generated `help:` should attempt to represent the expected output rather than the `<(_,_)>` which is confusing

File: compiler/rustc_middle/src/middle/stability.rs [hunk 1]
```diff
@@ -116,8 +117,12 @@ pub fn report_unstable(
         if is_soft {
             soft_handler(SOFT_UNSTABLE, span, &msg)
         } else {
-            feature_err_issue(&sess.parse_sess, feature, span, GateIssue::Library(issue), &msg)
-                .emit();
+            let mut err =
+                feature_err_issue(&sess.parse_sess, feature, span, GateIssue::Library(issue), &msg);
+            if using_vec_allocator_api {
+                err.help("consider wrapping the inner types in tuple: `<(_, _)>`");
```
Comment (fbstj) [inline compiler/rustc_middle/src/middle/stability.rs:123]: maybe this error should reconstruct the type aka `Vec<(u8,_)>` in the test below

File: compiler/rustc_middle/src/middle/stability.rs [hunk 2]
```diff
@@ -271,7 +283,13 @@ pub enum EvalResult {
     Allow,
     /// We cannot use the item because it is unstable and we did not provide the
     /// corresponding feature gate.
-    Deny { feature: Symbol, reason: Option<Symbol>, issue: Option<NonZeroU32>, is_soft: bool },
+    Deny {
+        feature: Symbol,
+        reason: Option<Symbol>,
+        issue: Option<NonZeroU32>,
+        is_soft: bool,
+        using_vec_allocator_api: bool,
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:291]: I'd prefer that we avoid adding feature gate-specific fields here, like `using_vec_allocator_api`, and instead add some generic fields like `suggestion: Option<Span, String, Applicability>`.

File: compiler/rustc_middle/src/middle/stability.rs [hunk 3]
```diff
@@ -116,8 +117,19 @@ pub fn report_unstable(
...
         } else {
-            feature_err_issue(&sess.parse_sess, feature, span, GateIssue::Library(issue), &msg)
-                .emit();
+            let mut err =
+                feature_err_issue(&sess.parse_sess, feature, span, GateIssue::Library(issue), &msg);
+            if using_vec_allocator_api {
+                if let Ok(snippet) =
+                    sm.span_to_snippet(sm.span_extend_to_prev_char(span, '<', true))
+                {
+                    err.help(&format!(
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:126]: We should emit a suggestion here rather than a help. See [`Diagnostic::span_suggestion`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_errors/diagnostic/struct.Diagnostic.html#method.span_suggestion).

File: compiler/rustc_middle/src/middle/stability.rs [hunk 4]
```diff
@@ -406,7 +424,10 @@ impl<'tcx> TyCtxt<'tcx> {
                     }
                 }
 
-                EvalResult::Deny { feature, reason, issue, is_soft }
+                let using_vec_allocator_api = "std::vec::Vec::A"
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:427]: Can a diagnostic item be used here instead of this string comparison?

**Review by davidtwco — CHANGES_REQUESTED** [review]

File: compiler/rustc_middle/src/middle/stability.rs (hunk 4 above)
Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
Thank you so much for your review!
I applied your two above suggestions, but I am not sure how to implement this suggestion.

When checking stability for 'allocator_api', the span position has already moved to `Vec`'s second parameter, meaning nothing to indicate `Vec`. I could confirm that `Vec` appears before iteration of the `eval_stability` function, but I do not think it is better to preserve it only for 'allocator_api' with `Vec`.

Could you please tell me if there is a way to detect `Vec`, such as getting the parent type of generics? (If given `i16` from `Vec<i8, i16>`, reconstruct `Vec`.)

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
What about showing this help on all use of unstable ‘allocator_api’ without focusing only on `Vec`?

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: You should be able to do this with a [diagnostic item](https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-items.html) - try placing a diagnostic item attribute on relevant generic arguments that indicate use of `allocator_api` and then checking if `def_id` has that item. You should be able to extend this approach to other uses of `allocator_api` without much difficulty.

I'd recommend moving the logic for this suggestion into a function that you invoke, just to keep the `eval_stability` function tidy.

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
I was able to implement your suggestion with the diagnostic item! I appreciate your kind advice.

File: compiler/rustc_middle/src/middle/stability.rs [hunk 5]
```diff
@@ -292,6 +303,32 @@ fn skip_stability_check_due_to_privacy(tcx: TyCtxt<'_>, def_id: DefId) -> bool {
...
 }
 
+// See issue #83250.
+fn get_sugg_for_allocator_api(
+    tcx: TyCtxt<'_>,
+    def_id: DefId,
+    span: Span,
+    feature: Symbol,
+) -> Option<(Span, String, String, Applicability)> {
+    if feature == Symbol::intern("allocator_api") {
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:313]: You should be able to pre-intern this string by adding it to this macro:

https://github.com/rust-lang/rust/blob/a2a7683e8f321e3c0b9d648ae480827b5ab70e1d/compiler/rustc_span/src/symbol.rs#L124

It should then be available as `sym::allocator_api` (or something like that).

File: compiler/rustc_middle/src/middle/stability.rs [hunk 6]
```diff
@@ -292,6 +303,32 @@ fn skip_stability_check_due_to_privacy(tcx: TyCtxt<'_>, def_id: DefId) -> bool {
...
+        if let Some(trait_) = tcx.parent(def_id) {
+            if tcx.is_diagnostic_item(sym::Vec, trait_) {
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:315]: I was more thinking that you could add a new diagnostic item to the `A` generic parameter itself and then check if `def_id` had that diagnostic item, rather than check if `def_id`'s parent is a `Vec`. I'm not entirely sure that we *can* do that, might not be able to put the attribute on the parameter, but worth a try. If you added diagnostic items like that to any `allocator_api` generic parameter then you can just check if any of them match here, and we'd be providing a suggestion for non-`Vec` cases too.

File: compiler/rustc_middle/src/middle/stability.rs [hunk 7]
```diff
@@ -292,6 +303,32 @@ fn skip_stability_check_due_to_privacy(tcx: TyCtxt<'_>, def_id: DefId) -> bool {
     }
 }
 
+// See issue #83250.
+fn get_sugg_for_allocator_api(
```
Comment (davidtwco) [inline compiler/rustc_middle/src/middle/stability.rs:307]:
```suggestion
fn suggestion_for_allocator_api(
```
We don't need to abbreviate suggestion here :)

**Review by davidtwco — CHANGES_REQUESTED** [review]
This is looking much better, thanks for addressing those comments, a few more changes.

File: src/test/ui/stability-attribute/suggest-vec-allocator-api.rs [hunk 8]
```diff
@@ -0,0 +1,9 @@
+fn main() {
```
Comment (davidtwco) [inline src/test/ui/stability-attribute/suggest-vec-allocator-api.rs:1]: Could we use `// run-rustfix` on this test to check that the suggestion makes the test pass?

File: compiler/rustc_middle/src/middle/stability.rs (hunk 6 above)
Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs:315]: @davidtwco 
Thank you so much for the additional reviews :)

In my understanding, we have the `feature` variable there, so we can just put only the first if-condition in case we'd suggest all type cases. Accordingly, we can omit an additional diagnostic item and def_id's parent checks. Is it correct that we'd like to expand the Vec suggestion to any other types on `allocator_api`? Or is there another purpose in adding a new diagnostic item?

File: src/test/ui/stability-attribute/suggest-vec-allocator-api.rs (hunk 8 above)
Comment (ken-matsui) [reply src/test/ui/stability-attribute/suggest-vec-allocator-api.rs:1]: @davidtwco 
Umm... The test used `// run-rustfix` could not be successfully finished.
The test showed a type mismatch error.

Comment (davidtwco) [reply src/test/ui/stability-attribute/suggest-vec-allocator-api.rs:1]: I guess that's because the suggestion doesn't work for the `let _boxed: Box<u32, _> = Box::new(10);` case? We can just leave this without `// run-rustfix` then.

File: compiler/rustc_middle/src/middle/stability.rs (hunk 6 above)
Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
I updated the commit with my understanding. Could you please take a look?

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: I just think it would be neater to check that `def_id` is the specific allocator generic argument rather assume that if we have a stability error with `allocator_api` and the parent type is a `Vec` then it must be because of the allocator generic argument (in practice, this would probably be fine, but if we can be more precise then I think that would be preferable).

Either approach can be extended to other types where this sort of suggestion would make sense.

File: src/test/ui/stability-attribute/suggest-vec-allocator-api.rs (hunk 8 above)
Comment (ken-matsui) [reply src/test/ui/stability-attribute/suggest-vec-allocator-api.rs:1]: Aha, thank you. I removed `// run-rustfix`.

File: compiler/rustc_middle/src/middle/stability.rs (hunk 6 above)
Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
Ah, I see. That indeed would be precise. I'd do some research on it. Thank you :)

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
I've put a new diagnostic item on the [`Allocator` trait](https://github.com/rust-lang/rust/blob/934624fe5f66ce3fb8abf0597a6deb079783335f/library/core/src/alloc/mod.rs#L100) that indicates the allocator generic argument, but it seems types that don't have impl of the trait such as `_` won't have its item. In my view, this way cannot be used here.

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: What if you put the attribute on the allocator generic argument of the `Vec` type?

https://github.com/rust-lang/rust/blob/faea820643f9acec1bb787941063393f9508a775/library/alloc/src/vec/mod.rs#L400

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
That also shows the same behavior...
Just in case, could you confirm that the following way I've tried is correct?

`rust/library/alloc/src/vec/mod.rs`

```diff
- pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
+ pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] #[rustc_diagnostic_item = "VecAllocator"] A: Allocator = Global> {
```

`rust/compiler/rustc_span/src/symbol.rs`

```diff
  Vec,
+ VecAllocator,
  VecDeque,
```

`rust/compiler/rustc_middle/src/middle/stability.rs`

```diff
fn suggestion_for_allocator_api(
...
) -> Option<(Span, String, String, Applicability)> {
+    println!("type: {}", tcx.is_diagnostic_item(sym::VecAllocator, def_id));
+    if let Some(trait_did) = tcx.trait_of_item(def_id) {
+        println!("trait: {}", tcx.is_diagnostic_item(sym::VecAllocator, trait_did));
+    }
+
    if feature == sym::allocator_api {
```

Compiler Output:

```
type: false
```

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: That's surprising, I would have expected that to work. I don't mind if you would want to revert to checking the parent is a `Vec` and land this change with that implementation, but you could also look into what `is_diagnostic_item` is doing, we could probably get it to work in this case.

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
Do you mean `is_diagnostic_item` doesn't work correctly? If so, I would like to inspect `is_diagnostic_item` and make it work as we expected rather than reverting.

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: I think if we could make `is_diagnostic_item` return `true` for this case (which seems like a reasonable thing for it to do, if other attributes, like those for stability, work in this position), then that would probably be a neater solution, so feel free to do some investigation.

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
Thank you for the clarification. I would work on it, but I will split this PR into two if it becomes much complicated.

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs]: @davidtwco 
Since I do not have enough time anymore to work on this problem, I would like to finish this pull request and open a new pull request when I can.

> I don't mind if you would want to revert to checking the parent is a `Vec` and land this change with that implementation

Also, just to confirm, are you sure you want me to revert it as well? I mean, I thought you already confirmed that we apply this suggestion for all types, including `Vec`. I think the current change satisfies this PR's aim.

If you would like me to revert to restrict the suggestion for only `Vec`, I will revert it.

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/stability.rs]: It's just that the current version only checks if the feature is `allocator_api` - I'm not sure if there are other cases where `allocator_api`  might produce a stability error that isn't related to generic parameters where this suggestion wouldn't be applicable. Ideally we'd at least additionally check that `def_id` was a generic parameter or something like that.

Comment (ken-matsui) [reply compiler/rustc_middle/src/middle/stability.rs:315]: @davidtwco 
I see. Thank you.
I've reverted to check the parent is `Vec`. I'd like to implement your idea on another PR additionally.

**Review by davidtwco — APPROVED** [review]
Looks good, thanks for your work on this.

**Comment by damccull** [comment]
Awesome. Thanks for getting to this even before I found out lol. Rust team is awesome.
