### PR TITLE
[NLL] Mutability errors

### LINKED ISSUE #46629: MIR borrowck: AST error message refers to kind of item that can't be borrowed
e.g. in E0596:

```Rust
fn main() {
    let x = 1;
    let y = &mut x; //[ast]~ ERROR [E0596]
                    //[mir]~^ ERROR [E0596]
}
```

AST borrowck knows that `x` is an "immutable local variable", but MIR semi-inaccurately calls it an immutable item:
```
error[E0596]: cannot borrow immutable local variable `x` as mutable (Ast)
  --> /home/ariel/Rust/rust-master/src/test/compile-fail/E0596.rs:16:18
   |
15 |     let x = 1;
   |         - consider changing this to `mut x`
16 |     let y = &mut x; //[ast]~ ERROR [E0596]
   |                  ^ cannot borrow mutably

error[E0596]: cannot borrow immutable item `x` as mutable (Mir)
  --> /home/ariel/Rust/rust-master/src/test/compile-fail/E0596.rs:16:13
   |
16 |     let y = &mut x; //[ast]~ ERROR [E0596]
   |             ^^^^^^ cannot borrow as mutable

error: aborting due to 2 previous errors
```

The AST code for doing that is actually in `mem_categorization`, and should be ported to MIR borrowck:
https://github.com/rust-lang/rust/blob/02b4d3ddfb7cd9f1caf8ed90f18f8e798a1f4b05/src/librustc/middle/mem_categorization.rs#L1450

### PR DESCRIPTION
**Pull request by matthewjasper**
cc #51028
cc #51170
cc #46559 
Closes #46629

* Better explain why the place is immutable ("immutable item" is gone)
* Distinguish &T and *const T
* Use better spans when a mutable borrow is for a closure capture

r? @pnkfelix

### CODE REVIEW

**Comment by pnkfelix** [comment]
This is great.

File: src/test/ui/borrowck/mutability-errors.rs [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// All the possible mutability error cases.
```
Comment (pnkfelix) [inline src/test/ui/borrowck/mutability-errors.rs]: I personally am a little overwhelmed by the number of cases covered in this file.

I originally wanted to suggest that you break it up into separate files. But I can see from reading the source itself that there is a specific pattern that you are maintaining in the source, and so there is value in keeping all these cases co-located...

**Comment by pnkfelix** [comment]
okay, r=me once you've resolved the merge conflict.
