### PR TITLE
Check types of const param defaults

### LINKED ISSUE #139643: Defaulted const generic parameters no longer have the const arg's type checked
### Code

I tried this code:

```rust
struct Foo<const N: u32, const M: u64 = N>;
```

I expected to see this happen: It fail to compile like it uised to

Instead, this happened: it compile :>

Probably regressed in #125915 where we started lowering const arguments to `ConstArgKind::Path` instead of `ConstArgKind::Anon` so there is no longer implicitly an anon const with an expected type of `u64` with an expr typed as `u32`.

We *could* probably special case handling of types of defaulted const generics in wfcheck to be done even when generics are involved. Or just accept this as working code which is consistent with things like `struct Foo<T, U = <T as Iterator>::Item>(T, U);` 🤷‍♀ would need a types fcp for that tho

I don't believe this to be a soundness bug

### PR DESCRIPTION
**Pull request by lcnr**
fixes rust-lang/rust#139643 by checking that the type of a const parameter default matches the type of the parameter as long as both types are fully concrete

r? @BoxyUwU

### CODE REVIEW

**Comment by lcnr** [comment]
This PR causes `struct Foo<const N: u32, const M: u64 = N>;` to error on the definition site instead of when first using it with defaulted params.

I personally feel like it's a clear bugfix and don't expect any fallout (nor do I care about any if such were to exist), so I didn't run crater here. Any breakage will be caught by the beta crater run and this is trivial to revert if necessary. 

@rfcbot fcp merge

**Comment by BoxyUwU** [comment]
This makes sense to me, unlike "normal" cases where some possible instantiation of the generic parameter could result in things being wf, it is not possible for any well formed argument to `N` to make a valid default for `M`.

I feel somewhat :thinking: about not cratering this, as a general policy i don't think its great to say "we can just look at the results of the beta crater run" as it's putting more work on the release team. I imagine a crater run would finish before the FCP 10 day period ends so I don't think there's any harm in just starting a try run and doing a crater run afterwards?

I'm fine to not crater this though if noone else on the team thinks its worthwhile

**Comment by lcnr** [comment]
@craterbot check

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 1]
```diff
@@ -1488,6 +1488,42 @@ fn check_where_clauses<'tcx>(wfcx: &WfCheckingCtxt<'_, 'tcx>, span: Span, def_id
...
+                        wfcx.body_def_id,
+                        ObligationCauseCode::WellFormed(None),
+                    );
+                    wfcx.register_obligation(Obligation::new(
+                        tcx,
+                        cause,
+                        wfcx.param_env,
+                        ty::PredicateKind::Clause(ty::ClauseKind::ConstArgHasType(
+                            ct,
+                            tcx.type_of(param.def_id).instantiate_identity(),
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1523]:
```suggestion
                            param_ty,
```

**Review by BoxyUwU — COMMENTED** [review]
add stable affecting test?

**Comment by lcnr** [comment]
> add stable affecting test?

as in, move the stable test from tests/ui/const-generics/defaults/concrete-const-param-type.rs into a separate file?

**Comment by BoxyUwU** [comment]
@bors r+

thanks gamer

**Comment by tgross35** [comment]
@bors retry

put this in a rollup five minutes too late
