### PR TITLE
Detect when user is trying to create a lending `Iterator` and give a custom explanation

### LINKED ISSUE #125337: Detect when user tries to write `Iterator` that incorrectly borrows from `Self` and would need GATs
### Code

```Rust
struct Data {
    v: Vec<i32>,
}

impl Iterator for Data {
    type Item = &[i32];
    fn next(&mut self) -> Option<Self::Item> {
        let mut a = 0;
        let mut b = 0;
        Some(&self.v[a..b])
    }
}

fn main() {}
```

### Current output

```Shell
error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> src/main.rs:6:17
  |
6 |     type Item = &[i32];
  |                 ^ explicit lifetime name needed here
```

### Desired output

```Shell
error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> src/main.rs:6:17
  |
6 |     type Item = &[i32];
  |                 ^ explicit lifetime name needed here
note: associated type `Iterator::Item` is declared without lifetime parameters, so using a borrowed type for them requires that lifetime to come from the implemented type, so `Data` should be declared with a lifetime
note: you can't create an `Iterator` that borrows each `Item` from itself, as it doesn't use Generic Associated Types, but you can instead create a new type that borrows `Data` and implement `Iterator` for that type: <LINK TO EXAMPLE>
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
1.78.0
```

### Anything else?

Taken from https://users.rust-lang.org/t/lifetime-error-from-iterator-with-its-item-as-a-reference/108863

### PR DESCRIPTION
**Pull request by pacak**
The scope for this diagnostic is to detect lending iterators specifically and it's main goal is to help beginners to understand that what they are trying to implement might not be possible for `Iterator` trait specifically.

I ended up to changing the wording from originally proposed in the ticket because it might be misleading otherwise: `Data` might have a lifetime parameter but it can be unrelated to items user is planning to return.

Fixes https://github.com/rust-lang/rust/issues/125337

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -1703,10 +1703,28 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+
+                        // Is it caused by user trying to implement a lending iterator?
+                        if !self.in_func_body
+                            && let Some((module, _)) = &self.current_trait_ref
+                            && let Some(ty) = &self.diag_metadata.current_self_type
+                            && let crate::ModuleKind::Def(DefKind::Trait, trait_id, _) = module.kind
+                            && def_id_matches_path(
+                                self.r.tcx,
+                                trait_id,
+                                &["core", "iter", "traits", "iterator", "Iterator"],
```
Comment (jackh726) [inline compiler/rustc_resolve/src/late.rs:1715]: Can this be extended to all non-generic associated types?

Comment (pacak) [reply compiler/rustc_resolve/src/late.rs:1715]: Which part specifically?

Comment (pnkfelix) [reply compiler/rustc_resolve/src/late.rs:1715]: I think Jack is saying that this PR has been tailored to just `Iterator` (and `Iterator::Item`), and is then posing the thought exercise of whether the logic here (and the associated diagnostic output) could be generalized, so that it would cover all associated types lacking a parameter (i.e. "non-generic").

I.e., instead of specializing this check to `trait Iterator { type Item; ... }`, can it be extended to `trait <AnyTraitNameHere> { type AnyAssociatedTypeHere; ... // but not GATs }` ?

Comment (pacak) [reply compiler/rustc_resolve/src/late.rs:1715]: Possibly, but I think this would be a separate diagnostic. I've seen people trying to implement lending iterators, I even tried to implement it myself years ago before I understood how it works :) So note about iterators is the main part and I want to keep it.

I can try to make the check more generic and add an error message about using non-GAT associated type.

Comment (pacak) [reply compiler/rustc_resolve/src/late.rs:1721]: Rebased, added a better error message for general case of non-GAT associated type, left the error for iterators as is.

Comment (pacak) [reply compiler/rustc_resolve/src/late.rs:1721]: And I'm open to any suggestions on wording/formatting/etc.

**Comment by pnkfelix** [comment]
sorry for the delay. I agree that the proposed experiment, while potentially interesting, need not block landing this.

@bors r+ rollup

**Comment by pacak** [comment]
> sorry for the delay. I agree that the proposed experiment, while potentially interesting, need not block landing this.

No worries. I did implemented more general case as well FWIW in addition to custom error for iterators. Are you okay with the wording/terminology?
