### PR TITLE
Recover from missing comma between enum variants and from bad `pub` kw

### LINKED ISSUE #56473: On places that `pub` would be "reasonable" but incorrect, provide better errors
When trying to [incorrectly specify a pub `fn` in a trait](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=59e7db92931e36737764386927600cd0), the error message just complains about the incorrect token:

```
trait T {
    pub fn foo(&self);
}
```

Ideally the compiler would explain that individual trait methods' visibility can't be modified, only the trait itself, and continue parsing the AST as if it were correct, possibly suggesting the following, if appropriate:

```
pub trait T {
    fn foo(&self);
}
```

### LINKED ISSUE #56579: Gracefully handle missing comma between struct style enum variants
The following code should gracefully recover from parse error, provide an appropriate suggestion and continue to typechk:

```
enum Foo {
    Bar {
    }
    /// doc
    Qux {
    }
    Quz,
}
fn main() {
    let x: usize = Foo::Quz;
}
```

```
error: expected one of `,` or `}`, found `/// doc`
 --> src/lib.rs:4:5
  |
3 |     }
  |      - help: missing comma here
4 |     /// doc
  |     ^^^^^^^ unexpected token

error: expected one of `,` or `}`, found `Quz`
 --> src/lib.rs:7:5
  |
6 |     }
  |      - help: missing comma here
7 |     Quz,
  |     ^^^ unexpected token

error[E0308]: mismatched types
  --> src/main.rs:10:20
   |
10 |     let x: usize = Foo::Quz;
   |                    ^^^^^^^^ expected usize, found enum `Foo`
   |
   = note: expected type `usize`
              found type `Foo`
```

---

If this could be generalized to all "unexpected token" cases, even better, but that might get tricky.

CC https://github.com/rust-lang/rust/issues/48724.

### PR DESCRIPTION
**Pull request by estebank**
Fix #56579. Fix #56473.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -7696,11 +7696,29 @@ impl<'a> Parser<'a> {
             };
             variants.push(respan(vlo.to(self.prev_span), vr));
 
-            if !self.eat(&token::Comma) { break; }
+            if !self.eat(&token::Comma) {
+                if self.token.is_ident() &&
+                    !self.token.is_special_ident() &&
+                    !self.token.is_used_keyword() &&
+                    !self.token.is_unused_keyword()
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: These three `is_` can be replaced with `!self.token.is_reserved_ident()`.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -8587,6 +8588,17 @@ impl<'a> Parser<'a> {
             }
         }
     }
+
+    /// Recover from `pub` keyword in places where it seems _reasonable_ but isn't valid.
+    fn eat_bad_pub(&mut self) {
+        if self.token.is_keyword(keywords::Pub) {
+            self.bump();
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: It probably makes sense to parse the whole visibility (`pub(...)`) and discard it rather than discard the `pub` only.
