### PR TITLE
Fix EII function aliases eliminated by LTO

### LINKED ISSUE #153645: Externally Implementable Items: `error: undefined symbol` when opt-level >= 1
Cross-crate EII fails to link with `error: undefined symbol` when `opt-level >= 1`.

### Reproduction

Multi-crate workspace — cannot be reduced to a single file.

Repo with a test script: https://github.com/AsakuraMizu/eii-playground

`decl1/src/lib.rs`:
```rust
#![feature(extern_item_impls)]

#[eii]
pub fn decl1();
```

`impl1/src/lib.rs`:
```rust
#[decl1::decl1]
pub fn impl1() {
    println!("Hello, world!");
}
```

`src/main.rs`:
```rust
extern crate impl1;

fn main() {
    decl1::decl1();
}
```

```
$ CARGO_PROFILE_DEV_OPT_LEVEL=1 cargo run
error: linking with `cc` failed: exit status: 1
  = note: rust-lld: error: undefined symbol: decl1::decl1
```

Works with any of:
- `opt-level = 0`
- `codegen-units = 1`
- `lto = "off"`

So the EII shim function appears to be eliminated during thin-local LTO.

### Meta

`rustc --version --verbose`:
```
rustc 1.96.0-nightly (2d76d9bc7 2026-03-09)
binary: rustc
commit-hash: 2d76d9bc76f27b03b4899e72ce561c7ac2c5cf6b
commit-date: 2026-03-09
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0
```

Possibly related: #151271

Tracking issue: #125418

### PR DESCRIPTION
**Pull request by AsakuraMizu**
Add EII function aliases to `llvm.compiler.used` so that LLVM's LTO passes do not eliminate them.

Fixes rust-lang/rust#153645

Tracking issue: https://github.com/rust-lang/rust/issues/125418

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/symbol_export.rs [hunk 1]
```diff
@@ -199,6 +199,22 @@ fn exported_non_generic_symbols_provider_local<'tcx>(
...
     }
 
+    symbols.extend(sorted.iter().flat_map(|&(&def_id, &info)| {
+        tcx.codegen_fn_attrs(def_id).foreign_item_symbol_aliases.iter().map(
+            move |&(foreign_item, _linkage, _visibility)| {
+                (
+                    ExportedSymbol::NonGeneric(foreign_item),
+                    SymbolExportInfo {
+                        level: info.level,
+                        kind: SymbolExportKind::Text,
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/symbol_export.rs]: This needs to be `SymbolExportKind::Data` if the alias points to a data object.

Comment (AsakuraMizu) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs]: Updated :)

File: compiler/rustc_codegen_ssa/src/back/symbol_export.rs [hunk 2]
```diff
@@ -199,6 +199,14 @@ fn exported_non_generic_symbols_provider_local<'tcx>(
         }))
     }
 
+    symbols.extend(sorted.iter().flat_map(|&(&def_id, &info)| {
+        tcx.codegen_fn_attrs(def_id).foreign_item_symbol_aliases.iter().map(
+            move |&(foreign_item, _linkage, _visibility)| {
+                (ExportedSymbol::NonGeneric(foreign_item), info)
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/symbol_export.rs:205]: I think the `rustc_std_internal_symbol` field of `info` needs to be set to true. Otherwise the symbol may not end up in `symbols.o`, which is required for cyclic dependencies between crates to work.

Comment (AsakuraMizu) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs:205]: I think `info.rustc_std_internal_symbol` is guaranteed to be `true` here by invariant:
- In `reachable_non_generics_provider`, `rustc_std_internal_symbol` is set to true when `EXTERNALLY_IMPLEMENTABLE_ITEM` is present: https://github.com/rust-lang/rust/blob/d1ee5e59a964a419b84b760812a35075034f4861/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L128-L133
- In `process_builtin_attrs`, when processing `EiiImpls`, `EXTERNALLY_IMPLEMENTABLE_ITEM` is always set alongside `foreign_item_symbol_aliases` entries: https://github.com/rust-lang/rust/blob/d1ee5e59a964a419b84b760812a35075034f4861/compiler/rustc_codegen_ssa/src/codegen_attrs.rs#L259-L264

That said, this invariant is somewhat non-obvious and could silently break if either location is changed in the future. Would you prefer I explicitly force `rustc_std_internal_symbol: true` here instead of relying on the inherited value, for clarity and defensiveness?

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs:205]: In that case it is fine to keep this code as is.
