### PR TITLE
Enforce that layout size fits in isize in Layout

### LINKED ISSUE #95334: {Rc,Arc}::{new_uninit_slice,from_iter} create too large references
See https://github.com/rust-lang/rust/pull/95252, https://github.com/rust-lang/rust/pull/95295 and [the discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Layout.20Isn't.20Enforcing.20The.20isize.3A.3AMAX.20Rule) for details. I just figured we should also have an issue to track this.

The following code:
```rust
#![feature(new_uninit)]
use std::rc::Rc;

fn main() {
    let p = Rc::<[u8]>::new_uninit_slice(isize::MAX as usize + 1);
    p.last();
}
```
fails in Miri (on a 32bit target) with
```
error: Undefined Behavior: invalid metadata in wide pointer: slice is bigger than largest supported object
    --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/rc.rs:1326:24
     |
1326 |             ptr::write(&mut (*inner).strong, Cell::new(1));
     |                        ^^^^^^^^^^^^^^^^^^^^ invalid metadata in wide pointer: slice is bigger than largest supported object
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
             
     = note: inside `std::rc::Rc::<[std::mem::MaybeUninit<u8>]>::try_allocate_for_layout::<[closure@std::rc::Rc<[std::mem::MaybeUninit<u8>]>::allocate_for_slice::{closure#0}], [closure@std::rc::Rc<[std::mem::MaybeUninit<u8>]>::allocate_for_slice::{closure#1}]>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/rc.rs:1326:24
     = note: inside `std::rc::Rc::<[std::mem::MaybeUninit<u8>]>::allocate_for_layout::<[closure@std::rc::Rc<[std::mem::MaybeUninit<u8>]>::allocate_for_slice::{closure#0}], [closure@std::rc::Rc<[std::mem::MaybeUninit<u8>]>::allocate_for_slice::{closure#1}]>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/rc.rs:1295:13
     = note: inside `std::rc::Rc::<[std::mem::MaybeUninit<u8>]>::allocate_for_slice` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/rc.rs:1375:13
     = note: inside `std::rc::Rc::<[u8]>::new_uninit_slice` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/rc.rs:691:31
note: inside `main` at rc.rs:5:13
    --> rc.rs:5:13
     |
5    |     let p = Rc::<[u8]>::new_uninit_slice(isize::MAX as usize + 1);
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
In fact it fails even without the `+1` since the `RcBox` is still too big.

On a 64bit target it would fail the same way if creating that huge allocation would not already lead Miri to abort earlier. ;)

### PR DESCRIPTION
**Pull request by CAD97**
As it turns out, enforcing this _in APIs that already enforce `usize` overflow_ is fairly trivial. `Layout::from_size_align_unchecked` continues to "allow" sizes which (when rounded up) would overflow `isize`, but these are now declared as library UB for `Layout`, meaning that consumers of `Layout` no longer have to check this before making an allocation.

(Note that this is "immediate library UB;" IOW it is valid for a future release to make this immediate "language UB," and there is an extant patch to do so, to allow Miri to catch this misuse.)

See also #95252, [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Layout.20Isn't.20Enforcing.20The.20isize.3A.3AMAX.20Rule).
Fixes https://github.com/rust-lang/rust/issues/95334

Some relevant quotes:

@eddyb, https://github.com/rust-lang/rust/pull/95252#issuecomment-1078513769

> [B]ecause of the non-trivial presence of both of these among code published on e.g. crates.io:
> 
>   1. **`Layout` "producers" / `GlobalAlloc` "users"**: smart pointers (including `alloc::rc` copies with small tweaks), collections, etc.
>   2. **`Layout` "consumers" / `GlobalAlloc` "providers"**: perhaps fewer of these, but anything built on top of OS APIs like `mmap` will expose `> isize::MAX` allocations (on 32-bit hosts) if they lack extra checks
> 
> IMO the only responsible option is to enforce the `isize::MAX` limit in `Layout`, which:
> 
>   * makes `Layout` _sound_ in terms of only ever allowing allocations where `(alloc_base_ptr: *mut u8).offset(size)` is never UB
>   * frees both "producers" and "consumers" of `Layout` from manually reimplementing the checks
>     * manual checks can be risky, e.g. if the final size passed to the allocator isn't the one being checked
>     * this applies retroactively, fixing the overall soundness of existing code with zero transition period or _any_ changes required from users (as long as going through `Layout` is mandatory, making a "choke point")
> 
> 
> Feel free to quote this comment onto any relevant issue, I might not be able to keep track of developments.

@Gankra, https://github.com/rust-lang/rust/pull/95252#issuecomment-1078556371

> As someone who spent way too much time optimizing libcollections checks for this stuff and tried to splatter docs about it everywhere on the belief that it was a reasonable thing for people to manually take care of: I concede the point, it is not reasonable. I am wholy spiritually defeated by the fact that _liballoc_ of all places is getting this stuff wrong. This isn't throwing shade at the folks who implemented these Rc features, but rather a statement of how impractical it is to expect anyone out in the wider ecosystem to enforce them if _some of the most audited rust code in the library that defines the very notion of allocating memory_ can't even reliably do it.
> 
> We need the nuclear option of Layout enforcing this rule. Code that breaks this rule is _deeply_ broken and any "regressions" from changing Layout's contract is a _correctness_ fix. Anyone who disagrees and is sufficiently motivated can go around our backs but the standard library should 100% refuse to enable them.

cc also @RalfJung @rust-lang/wg-allocators. Even though this technically supersedes #95252, those potential failure points should almost certainly still get nicer panics than just "unwrap failed" (which they would get by this PR).

It might additionally be worth recommending to users of the `Layout` API that they should ideally use `.and_then`/`?` to complete the entire layout calculation, and then `panic!` from a single location at the end of `Layout` manipulation, to reduce the overhead of the checks and optimizations preserving the exact location of each `panic` which are conceptually just one failure: allocation too big.

Probably deserves a T-lang and/or T-libs-api FCP (this technically solidifies the [objects must be no larger than `isize::MAX`](https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html#isize-and-usize) rule further, and the UCG document says this hasn't been RFCd) and a crater run. Ideally, no code exists that will start failing with this addition; if it does, it was _likely_ (but not certainly) causing UB.

Changes the raw_vec allocation path, thus deserves a perf run as well.

I suggest hiding whitespace-only changes in the diff view.

### CODE REVIEW

**Comment by CAD97** [comment]
Let's see if I remember how to do this...

@rustbot label: +A-allocators +A-layout +needs-fcp +T-lang +T-libs-api 

(I think those are all relevant, feel free to fix up)

**Comment by eddyb** [comment]
> Ideally, no code exists that will start failing with this addition;

Sadly, I don't think we can spot this on crater, isn't it x86_64-only?
(I first suspected something like this on 32-bit targets, but I could never come up with an exploit)

**Comment by CAD97** [comment]
So... we currently _don't enforce the `isize::MAX` limit_ in `raw_vec` for 64+ bit platforms, and instead just rely on the platform allocator failing:

https://github.com/rust-lang/rust/blob/661e8beec1fa5f3c58bf6e4362ae3c3fe0b4b1bd/library/alloc/tests/string.rs#L696-L699

https://github.com/rust-lang/rust/blob/661e8beec1fa5f3c58bf6e4362ae3c3fe0b4b1bd/library/alloc/src/raw_vec.rs#L494-L510

**Comment by CAD97** [comment]
This changes the allocation path in raw_vec, so is thus perf-sensitive.

@bors rollup=never

**Comment by CAD97** [comment]
I'm done tweaking this for the time being, but if this does turn out to be a perf impact, this can possibly be improved by changing

```rust
let new_layout = Layout::array::<T>(cap);
finish_grow(new_layout, self.current_memory(), &mut self.alloc);
```

to

```rust
let t_layout = Layout::<T>::new();
finish_grow(t_layout, cap, self.current_memory(), &mut self.alloc);
```

and doing `Layout::repeat` inside `finish_grow`, to move all of the dynamic alloc size checks inside the non-generic path.

**Comment by CAD97** [comment]
(Also noting this here, not just in the Zulip: [`GlobalAlloc::realloc`](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#method.realloc) and [`alloc_realloc`](https://doc.rust-lang.org/std/alloc/fn.realloc.html) do not put an `isize` maximum on `new_size`. All other allocation APIs go through `Layout` and inherit it's requirements. I also don't see an explicit requirement that sizes are padded to alignment anywhere.)

**Comment by eddyb** [comment]
Noticed this comment in the snippets above:

> ```rust
> // ... On 32-bit and 16-bit we need to add 
> // an extra guard for this in case we're running on a platform which can use 
> // all 4GB in user-space, e.g., PAE or x32.
> ```

AFAIK this is a bit off, these are the distinctions I'm aware of:
* x86_32 kernel
  * x86_32 userspace
    * Linux: [has a 3GiB/1GiB userspace/kernel split](https://www.kernel.org/doc/html/latest/vm/highmem.html), IIUC even without PAE
    * Windows: [has either 2GiB/2GiB or 3GiB/1GiB](https://docs.microsoft.com/en-us/windows/win32/memory/virtual-address-space#default-virtual-address-space-for-32-bit-windows)
  * PAE: increases the amount of physical memory *the whole system* can address
    * without it, there is less than 4GiB of total RAM (as some physical addresses are MMIO)
    * maybe some kernels do not give userspace more than 2GiB unless PAE is available? not sure
* x86_64 kernel
  * x86_32 userspace
    * Linux: userspace gets nearly 4GiB, AFAICT (easier to see with musl than glibc)
      * experimentally, with musl, you only lose ~256MiB:
        * lowest ~128MiB: static executable mapped at `0x08000000` (can probably lower that?)
        * highest ~128MiB: vDSO and the main thread's stack are mapped there
      * with fragmentation you can use more of the gaps, but a contiguous allocation is going to cap out at around ~3.75GiB (and closer to ~2.5GiB for glibc but that's mostly the ASLR worsening fragmentation AFAICT, so it's more of a gamble)
    * Windows: according to [the 4GT ("4GiB Tuning") docs](https://docs.microsoft.com/en-us/windows/win32/memory/4-gigabyte-tuning):
      > On 64-bit editions of Windows, 32-bit applications marked with the [IMAGE_FILE_LARGE_ADDRESS_AWARE](https://docs.microsoft.com/en-us/windows/desktop/api/dbghelp/ns-dbghelp-loaded_image) flag have 4 GB of address space available.
  * x86_64 userspace
    * by default, you get 64-bit address space
      * however, for a long time the hardware was limited to 48-bit, and some (most?) kernels split that into two halves, leaving 47-bit for userspace
    * "x32" is a Linux x86_64 ABI that uses the bottom 4GiB of the 64-bit address space, relying on x86 addressing modes to enjoy the smaller pointers
    <sup>(I wonder if you could go as low as 16-bit addresses while still having 64-bit registers, heh)</sup>
      * compilers support this as an ABI with 32-bit pointers "by default" (think "near" pointers)
      * Linux x86_64 syscalls have [a bit (in the syscall number)](https://unix.stackexchange.com/a/499106) indicating whether the kernel should account for x32 variations, like smaller `struct` sizes/fields offsets, not returning pointers above 4GiB (e.g. from `mmap`), etc.
      * x86_64 syscalls and 64-bit pointers can be used simultaneously with x32 if enough care is taken (either through FFI, or a compiler that allows specifying "far" pointers in x32 mode)

So AFAICT, PAE isn't really relevant and x32 is more of a "pointer compression trick" than a "fundamentally" 32-bit userspace.
<sup>(efficiency and lack of OS support are the only things stopping someone from making up a pseudo-Harvard ABI, on any platform, with smaller <sub>(even as small as 8-bit)</sub> data pointers, that only need to address statics, maybe some heap, and the stack)</sup>

Taking into account that "can use all 4GB" should be "can use more than 2GiB", I think we can just say that:
* 32-bit (userspace) programs would mainly be kept away from 2GiB by available memory in the system
* 64-bit (userspace) programs, on the other hand, will likely never have more than 63 bits for each of the kernel and userspace, even if 64-bit virtual addresses finally get implemented in hardware (because that's the most convenient way to split the two, AFAIK)

That leaves bare-metal/kernel 64-bit code on some future CPU (that could still be targeted just fine by an existing Rust version!), unaccounted for. And probably only bare-metal without an userspace, because you wouldn't have an allocation crossing the kernel/userspace split even if you could see the entire 64-bit address space at once.

I guess that could justify skipping the checks in those cases, but I would feel more comfortable with something like `cfg!(any(unix, windows))` to rule out long-term-plausible weird configurations.

**Comment by Gankra** [comment]
fwiw all the fiddly shit in RawVec is *largely* an aesthetic vanity project of my own making because the entire premise of saving an add/comparison is ridiculous when entering RawVec's code implies you are about to do a dynamic call to the allocator and do O(n) work.

**Comment by RalfJung** [comment]
Relatedly, we also have wording like this in our `offset` methods:

> Most platforms fundamentally can’t even construct such an allocation [meaning one that exceeds `isize::MAX`]. For instance, no known 64-bit platform can ever serve a request for 2^63 bytes due to page-table limitations or splitting the address space. However, some 32-bit and 16-bit platforms may successfully serve a request for more than isize::MAX bytes with things like Physical Address Extension. As such, memory acquired directly from allocators or memory mapped files may be too large to handle with this function.

Not sure if that will be affected by this change though. Does LLVM consider it okay to (somehow) have a larger-than-isize::MAX allocation and use `wrapping_offset` to move more than isize::MAX inside it?

**Comment by Gankra** [comment]
C has a rule that you can't stride such an allocation in one step, and instead have to do it in two steps. Presumably llvm supports this semantic. As I understand it, there was also vaguely a period where C tried to insist that there should actually be a 1-bit difference between some of the integer types to accommodate the issue with signed offsets, which was completely wild and no implementation actually did.

Long ago before even like 1.0 we all agreed "that's all a fucking nightmare" (and I seriously doubt almost any C/C++ code actually supports detecting and handling any of that) and concluded that the only sound solution (in the sense that all code wouldn't have subtle UB) was to mandate everything be restricted to isize::MAX. I believe modern versions of glibc and jemalloc also actually just silently enforce this because again, anything else is completely broken.

(I am told that gcc also hardcodes this limitation, and it's not just an llvm thing)

**Comment by RalfJung** [comment]
> (I am told that gcc also hardcodes this limitation, and it's not just an llvm thing)

That is very surprising. To me the entire thing looks wholly unnecessary and motivated entirely by the fact that LLVM's `getelementptr` is a really odd API that interprets the total effective offset as *signed*. If LLVM had proper unsigned offsetting, and if we used that for field and array accesses and so on, there would be no issue. (Negative offsets are exceedingly rare and could be delegated to special methods.)

Why does GCC have a similar limitation?

**Comment by Gankra** [comment]
Because it's a C limitation and they're both riddled with C semantics.

**Comment by tavianator** [comment]
Here's some pointers for GCC:

- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63303#c5
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999#c5

**Comment by Gankra** [comment]
So yeah basically this is a *defacto* restriction that all programming languages must conform to (if only for C interop), and which doesn't actually matter on 64-bit because it's unobservable. Anyone who wants to Be Clever on 32/16-bit gets to reach for mmap and go around the language's back and be very careful / hope they don't get miscompiled.

**Comment by RalfJung** [comment]
Wow computers truly are terrible. :'-(

**Comment by RalfJung** [comment]
> [GlobalAlloc::realloc](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#method.realloc) and [alloc_realloc](https://doc.rust-lang.org/std/alloc/fn.realloc.html) do not put an isize maximum on new_size

So what's the plan for those two? Impose a requirement on `GlobalAlloc` implementations that reallocation MUST fail if `new_size > isize::MAX`? It is an `unsafe trait`, so implementation requirements are possible, but this is technically a breaking change.

**Comment by Lokathor** [comment]
It's technically breaking, but it's also for soundness.

**Comment by CAD97** [comment]
The limit to `Layout::size` maximum of `isize::MAX` is also a technically breaking change for soundness reasons. So my recommended change would be to make `realloc` require `new_size <= isize::MAX` (and not to put that burden onto the allocator).

Note that the unstable `Allocator` trait's `grow`/`shrink` take `(old: Layout, new: Layout)`, so implicitly inherit `Layout`'s requirements.

**Comment by RalfJung** [comment]
> So my recommended change would be to make realloc require new_size <= isize::MAX (and not to put that burden onto the allocator).

You mean the caller has to ensure this?

That seems inconsistent, since for the other methods the caller does not have to check anything. I expect there to be more callers to `realloc` than implementors so it seems preferable to put the burden on the latter.

**Comment by CAD97** [comment]
If we're putting the `isize::MAX` into `Layout`, then the caller is guaranteeing that `Layout.size() <= isize::MAX`. The [unstable `Allocator` trait](https://doc.rust-lang.org/nightly/std/alloc/trait.Allocator.html) uses `Layout` for `grow`/`shrink` (i.e. realloc), so also requires `isize::MAX`. `realloc`'s `new_size` would be the odd one out here.

But that also said, `Allocator::allocate` says

> Returning `Err` indicates that either memory is exhausted _or layout does not meet allocator’s size or alignment constraints_ [emphasis mine,]

so maybe having `GlobalAlloc` allocators check this is not so bad? But at the same time, `Allocator` is supposed to support "allocating" at size zero, whereas `GlobalAlloc` is a "rawer" API that doesn't support "allocating" zero bytes. But `GlobalAloc` also has similar wording:

> Returning a null pointer indicates that either memory is exhausted _or layout does not meet this allocator’s size or alignment constraints_ [emphasis mine].

I thought that `GlobalAlloc` had a requirement for input layouts to be padded to a multiple of alignment, but I don't see this as an input requirement, so allocators are required to handle (though not necessarily to successfully allocate) when `size % align != 0`.

Still, I'd _personally_ rather require that `new_size` (rounded up to a multiple of `align`) `<= isize::MAX` as the caller's responsibility (and get that automatically checked for the consumer once `Allocator` is used more than `GlobalAlloc`) than to require `GlobalAlloc` providers to add a check to return null for such. It seems inconsistent (to me) with all of the other APIs checking size on the consumer side (if this change to `Layout` is made).

But I've never worked on the provider side of the alloc API, so I'll defer to others here.

**Comment by RalfJung** [comment]
> If we're putting the isize::MAX into Layout, then the caller is guaranteeing that Layout.size() <= isize::MAX.

No, the caller has to do nothing. It's all encoded in the types that have been picked by the callee.

But indeed conveniently with `Layout`, the callee also has to do nothing. We can't have the same luxury with `realloc`. However, as far as I am concerned the conclusion of this bug is that putting the burden on the caller *does not work*. After all, that's what we used to say also for `alloc` (the caller has to check), and that approach failed. Why would it work any better for `realloc`? I don't think it would. Hence we should put the burden on the callee.

**Comment by scottmcm** [comment]
Nominated for lang to get a hopefully-uncontroversial confirmation that this rule is expected.

**Comment by eddyb** [comment]
> I guess that could justify skipping the checks in those cases, but I would feel more comfortable with something like `cfg!(any(unix, windows))` to rule out long-term-plausible weird configurations.

We can do better, I suppose, by adding an `effective_alloc_size_bits` to target specs - though because of how the opt-ins function on Linux (dummy `mmap` requesting an address not representable in the old 47-bit userspace, as opposed to being e.g. an ELF field), we can't really set that to anything lower than `63` right now.

There's other stuff I was thinking of with such configurable target properties, like having a separate one for the *shapes of valid addresses* (imagine if we could add a massive niche space on all 64-bit targets running under an OS, heh).

**Comment by Amanieu** [comment]
Running a perf test since `Layout` is a hot path in the `Vec` internals.

@bors try @rust-timer queue

**Comment by Gankra** [comment]
Thanks for fixing this!!

**Comment by CAD97** [comment]
I've pushed the [potential micro-optimization I spotted](https://github.com/rust-lang/rust/pull/95295#issuecomment-1078688856) to push a little more of the `raw_vec` realloc path into the non-generic-over-`T` path. This is at least somewhat notable because it puts the impacted checks in the non-generic path. However, it also means using `Layout::repeat` instead of `Layout::array`, which [was targeted to optimize to not use `repeat` previously](https://github.com/rust-lang/rust/pull/91246), so the impact of that change is a toss-up.

This code is very sensitive to trivial changes causing perf impacts (e.g. #72189 #79827), so intuition on perf impact is basically useless in this area.

Humbly requesting another perf run with bf0bc2b to see if it has a positive/negative impact on the perf impact.

cc @nnethercote the perf wizard for any insights

**Comment by nnethercote** [comment]
When it comes to the raw_vec code, my hard-earned conclusion is that intuition is not to be trusted, measurements are king, even more so than usual. Having said that, the micro-optimization seems plausible, so let's measure it:

@bors try @rust-timer queue

**Comment by CAD97** [comment]
bf0bc2b4e8d1f5c4d2bf727c0ae7bc55bcf383b0 turned out to be a wash, so I've force-pushed it back out of existence.

> 7b58193f90185a5730732a727362576a9bdca26b => bf0bc2b4e8d1f5c4d2bf727c0ae7bc55bcf383b0
> - Arithmetic mean of relevant regressions: 0.6% => 0.7%
> - Arithmetic mean of relevant improvements: -0.3% => -0.3%
> - Arithmetic mean of all relevant changes: 0.1% => 0.3%
> - Largest improvement in instruction counts: -0.5% => -0.6%
> - Largest regression in instruction counts: 1.6% => 1.9%

So to be clear, [these are the appropriate perf results](https://github.com/rust-lang/rust/pull/95295#issuecomment-1083707873).

Regression justification: this is a change to ensure soundness of emitted code, by enforcing the restriction that "rust allocations" cannot be larger than `isize::MAX` via `Layout`'s constructors. Some of this can potentially be won back by finding locations which perform an allocation size check which no longer has to happen (or, mayhaps, doing the cute "don't check on 64 bit targets and rely on allocation failing" trick again), but I'm not the person to do that hunt.

**Comment by scottmcm** [comment]
We briefly discussed this in the lang meeting today, and everyone was in agreement that it's a lang rule that objects cannot be larger than `isize::MAX`.  Niko pointed out https://github.com/rust-lang/rust/issues/18726, suggesting that this has effectively been the rule for over 6 years now.

**Comment by DemiMarie** [comment]
> Because it's a C limitation and they're both riddled with C semantics.

Why not fix this in GCC and LLVM?  I doubt Cranelift would have a problem with this for example.

**Comment by eddyb** [comment]
> > Because it's a C limitation and they're both riddled with C semantics.
> 
> Why not fix this in GCC and LLVM? I doubt Cranelift would have a problem with this for example.

@DemiMarie It's not just GCC and LLVM (not that those would be easy to fix either), it's any platform with C support where e.g. `ptrdiff_t` is 32 bits and the address space is also 32 bits.
In order to support the full range of 32-bit C "object" (i.e. "allocation") sizes, `ptrdiff_t` would have to be **33 bits** (or, more plausibly, equivalent to `int64_t`).

Otherwise only Rust in isolation *might* be sound (assuming no unsafe code using signed offsets, which basically reproduces the `ptrdiff_t` issue anyway), *not* Rust doing FFI to C libraries.

**Comment by CAD97** [comment]
(triaging my open PRs)

Still needs FCP; requesting nomination for this.

T-lang signoff: confirming that we do have the `isize::MAX` limit on (at a minimum) "rust allocated object" sizes. I *think* this was already signed off on elsewhere, but I don't have the receipts to prove it.

T-libs-api signoff: We enforce `size <= isize::MAX` at the `Layout` level (returning a layout error when this is not the case). This PR does not make a decision about `realloc`. This is a insta-stable technically breaking change (maybe should get a crater run? the failure case is quite exotic...) that in *most* cases converts UB into a runtime error (or a runtime error into a slightly earlier runtime error), but also theoretically breaks code which creates a too-large `Layout` but does not use that `Layout` for an allocation. The alternative is to require `Allocator`/`GlobalAlloc` providers check/ensure that `size <= isize::MAX` on their side of the allocation bridge. This is also a breaking change, but this time one that turns providers that thought they were conforming into nonconforming UB time bombs, and in a way that asks all allocator providers to remember to check `size <= isize::MAX` on pain of UB rather than checking it in one centralized location. (This alternative would also mean that just plumbing the Rust interface to an existing allocator would be unsound if that allocator doesn't enforce `size <= isize::MAX`, even if it would otherwise be sound.)

The third alternative: stick with the status quo, and it's the responsibility of anyone doing manual allocation to know that the `size <= isize::MAX` rule exists and enforce it themselves. [Everybody dislikes this.]

Note also that this PR closes a *known soundness hole in std* (https://github.com/rust-lang/rust/issues/95334). Manually remembering to check `size <= isize::MAX` has proven too difficult for some of the most well-reviewed Rust code (std collections) to get right in all cases.

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by Amanieu** [comment]
@rfcbot fcp cancel

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by CAD97** [comment]
> We briefly discussed this in the lang meeting today, and everyone was in agreement that it's a lang rule that objects cannot be larger than `isize::MAX`.  Niko pointed out https://github.com/rust-lang/rust/issues/18726, suggesting that this has effectively been the rule for over 6 years now.

https://github.com/rust-lang/rust/pull/95295#issuecomment-1097011792

.... I should read my own PR thread. T-lang already did sign off on the `isize::MAX` limit -- in this thread at that.

@rustbot modify labels -I-lang-nominated

Mea culpa 🙃

File: library/core/src/alloc/layout.rs [hunk 1]
```diff
@@ -382,8 +391,10 @@ impl Layout {
     #[unstable(feature = "alloc_layout_extra", issue = "55724")]
     #[inline]
     pub fn repeat_packed(&self, n: usize) -> Result<Self, LayoutError> {
-        let size = self.size().checked_mul(n).ok_or(LayoutError)?;
-        Layout::from_size_align(size, self.align())
+        // Size manipulation is done in isize space to avoid overflowing isize.
+        let n = isize::try_from(n).map_err(|_| LayoutError)?;
```
Comment (scottmcm) [inline library/core/src/alloc/layout.rs:395]: Is this check correct?  It looks like it would fail on `Layout::new::<()>().repeat_packed(usize::MAX)`, but I think that should be fine, since repeating a ZST wouldn't overflow `isize` *bytes*.

File: library/core/src/alloc/layout.rs [hunk 2]
```diff
@@ -405,7 +418,9 @@ impl Layout {
     #[stable(feature = "alloc_layout_manipulation", since = "1.44.0")]
     #[inline]
     pub fn array<T>(n: usize) -> Result<Self, LayoutError> {
-        let array_size = mem::size_of::<T>().checked_mul(n).ok_or(LayoutError)?;
+        // Size manipulation is done in isize space to avoid overflowing isize.
+        let n = isize::try_from(n).map_err(|_| LayoutError)?;
```
Comment (scottmcm) [inline library/core/src/alloc/layout.rs:422]: ditto here: 
```rust
Layout::array::<()>(usize::MAX).unwrap() = Layout {
    size: 0,
    align: 1 (1 << 0),
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=74580b2cdf9e4c3eac2a23b763f1b245

Comment (CAD97) [reply library/core/src/alloc/layout.rs:422]: This one can add a const collapsible `if size_of::<T>() == 0` to handle this.

File: library/core/src/alloc/layout.rs (hunk 1 above)
Comment (CAD97) [reply library/core/src/alloc/layout.rs:395]: You're correct that it incorrectly fails here.

I'm not sure how better to write this function, though; this could either be written as a `usize` `checked_mul` and an additional `< isize::MAX` check,

Comment (scottmcm) [reply library/core/src/alloc/layout.rs:395]: I don't know; it would probably depend greatly on what information is available at the callsites.  (Whether the `self.size` or the `n` is more likely to be constant.)

Hmm, this might be too cute, but what about:
```rust
let n = (self.size << 1).checked_mul(n).ok_or(LayoutError)? >> 1;
```
along with a whole bunch of tests, of course.

(The shift can't overflow because `self.size` always has the high bit zero, so the unsigned overflow stops at the right place, and the shift back down at the end just shifts out a low-bit zero to fix the scale.)

File: library/core/src/alloc/layout.rs [hunk 3]
```diff
@@ -299,14 +300,21 @@ impl Layout {
...
         // This cannot overflow. Quoting from the invariant of Layout:
         // > `size`, when rounded up to the nearest multiple of `align`,
-        // > must not overflow (i.e., the rounded value must be less than
-        // > `usize::MAX`)
+        // > must not overflow isize (i.e., the rounded value must be
+        // > less than or equal to `isize::MAX`)
         let padded_size = self.size() + self.padding_needed_for(self.align());
-        let alloc_size = padded_size.checked_mul(n).ok_or(LayoutError)?;
+        // Size manipulation is done in isize space to avoid overflowing isize.
+        let n = isize::try_from(n).map_err(|_| LayoutError)?;
```
Comment (CAD97) [inline library/core/src/alloc/layout.rs:307]: This also improperly fails by @scottmcm's note, and should be solved the same way

File: library/core/src/alloc/layout.rs (hunk 1 above)
Comment (CAD97) [reply library/core/src/alloc/layout.rs:395]: Godbolt comparison: https://rust.godbolt.org/z/a3sb3v3sK

Observation putting this together: we don't have to check `isize:MAX` here; `from_size_align` will of course now do that for us, meaning the implementation *does not change* from `HEAD`, since it was using the safe `from_size_align` already.

The size check when nothing is known is fairly clearly the worst option of the correct ones (3 jumps vs 1). Strangely enough, it looks like doing the check that way is potentially *better* than the `isize::checked_mul` (1 jump vs 2); based on staring at Godbolt it looks like this is because with the `usize` mul we get an overflow check error return and handle `from_size_align` with `cmov`s, whereas with the `isize` mul we need to insert a check and bail for an input high bit first, then do the same thing.

I think reverting this to HEAD beats out the bit tricks by obviousness of implementation alone, given the minimal output difference, but it also looks to me like the bit twiddling impl ends up executing all the same assembly instructions but with an additional two to shl and shr, such that an overflow occurs sooner. If anything, this nano-optimizes for the overflowing case, which we expect to be the less likely case anyway.

File: library/core/src/alloc/layout.rs [hunk 4]
```diff
@@ -383,7 +383,8 @@ impl Layout {
     #[inline]
     pub fn repeat_packed(&self, n: usize) -> Result<Self, LayoutError> {
         let size = self.size().checked_mul(n).ok_or(LayoutError)?;
-        Layout::from_size_align(size, self.align())
+        // The safe constructor is called here to enforce the isize size limit.
+        Layout::from_size_align(size as usize, self.align())
```
Comment (scottmcm) [inline library/core/src/alloc/layout.rs:387]: nit: I think you can remove the the `as usize` too, so it's just a comment addition.

File: library/core/src/alloc/layout.rs (hunk 1 above)
Comment (scottmcm) [reply library/core/src/alloc/layout.rs]: I like the plan of just using `from_size_align`.  As you say, the obvious correctness is hugely valuable, and if nothing's clearly better right now, we can always μoptimize later. 👍 

(I still plan to make a #95361-like change for the size, which might help optimize `Layout` without needing to drop to `unsafe`, by moving more of the checks to the type system.)

File: library/core/src/alloc/layout.rs (hunk 4 above)
Comment (CAD97) [reply library/core/src/alloc/layout.rs:387]: ... whoops, I thought I did 🙃 
```suggestion
        Layout::from_size_align(size, self.align())
```

**Comment by CAD97** [comment]
I just pushed a fix for repeating ZST layouts more than `isize::MAX` times, which should work but was incorrectly prevented by this PR previously.

This incidentally partially reverts [a previous optimization](https://github.com/rust-lang/rust/pull/91246) by @nnethercote to `Layout::array` for a more obviously correct implementation. Because `Layout::array::<T>` is instantiated a lot (e.g. by `Vec::push`), this might be a perf regression, or it might not be, it is fully impossible to guess in such touchy code. @nnethercote, re-optimizing `Layout::array` after this PR might be fruitful. However, the overflow check can no longer just be trivially elided, so it's unclear what implementation would put the least pressure on LLVM. [Here's a Godbolt comparison of three options.](https://rust.godbolt.org/z/bjzq6jv1W)

**Comment by CAD97** [comment]
How `GlobalAlloc` should handle the `isize::MAX` limit was discussed previously. Of note, the default implementation currently puts the `size: usize` directly into `Layout::from_size_align_unchecked`:

https://github.com/rust-lang/rust/blob/acdcdfb61b7b472bfacbb8bb889bdf3204827f2e/library/core/src/alloc/global.rs#L259-L262

so we should either say "`GlobalAlloc::realloc`'s implementation needs to check" and use the safe constructor there as well as document that requirement on implementers, or say "`GlobalAlloc::realloc`'s caller needs to check" and document *that* requirement.

My personal bias is to [provide a `GlobalAlloc::realloc` replacement that takes `Layout`](https://github.com/rust-lang/wg-allocators/issues/102) and deprecate `GlobalAlloc::realloc` with a requirement the caller respect the `isize::MAX` limit.

**Comment by DemiMarie** [comment]
@CAD97 I would rather the overflow check be pushed into the memory allocator, as the check can be further pushed into various slow paths.

**Comment by CAD97** [comment]
@DemiMarie does this apply just to `realloc`, or to `alloc` as well? The problem at hand is that with the `GlobalAlloc` API as stabilized, it currently *is* the case that the caller is in charge of checking the `isize::MAX` size limit. This is not in small part because the `GlobalAlloc` APIs were designed to be hooked up to the system [`aligned_alloc`](https://en.cppreference.com/w/c/memory/aligned_alloc)/[`free`](https://en.cppreference.com/w/c/memory/free) with minimal required gluing. On 32-bit targets, this means *today* that allocations of `>isize::MAX` can succeed. On 64-bit targets, it's at least a somewhat reasonable assumption that an allocation of 4+ exbibytes would fail, but this may not be the case forever. (32 bits was enough until it wasn't.)

It's also important to note that the plan is still to one day deprecate the [`GlobalAlloc`](https://doc.rust-lang.org/nightly/std/alloc/trait.GlobalAlloc.html) trait and use the [`Allocator`](https://doc.rust-lang.org/nightly/std/alloc/trait.Allocator.html) trait instead. It's already the case that all of std collections use `Allocator`, and thus call `realloc` through APIs which pass layout as `Layout` and (with this PR) check the `isize::MAX` limit on this side of `GlobalAlloc`.

Plus, looking at the godbolt links in this PR, it's been shown that `Layout` tracking the `isize::MAX` limit instead of a `usize::MAX` limit is [*practically free*](https://rust.godbolt.org/z/e4ahTb4sj); either way it still has to check for overflow.

<details><summary>No, really, it's <em>free</em>!</summary>

```diff
-repeat_packed_usize_max:
+repeat_packed_isize_max:
         mov     rax, rsi
         mul     qword ptr [rdi]
         jno     .LBB_2
         xor     edx, edx
         ret
 .LBB_2:
         mov     rcx, qword ptr [rdi + 8]
-        mov     rdx, rcx
+        movabs  rdx, -9223372036854775808
-        neg     rdx                                ; rdx <- 0x0000000000000000 - rcx
+        sub     rdx, rcx                           ; rdx <- 0x8000000000000000 - rcx
         xor     esi, esi
-        cmp     rax, rdx
+        cmp     rdx, rax
         mov     rdx, rcx
-        cmova   rdx, rsi
+        cmovb   rdx, rsi
         lea     rdi, [rcx - 1]
         test    rcx, rdi
         cmovne  rdx, rsi
         test    rcx, rcx
         cmove   rdx, rcx
         ret
```

Calculating `0 - align` might be microops faster than `0x8000000000000000 - align`, sure. But that's *literally* the only change here. (The other change is just a polarity flip.)

For `repeat`, it's [slightly less free](https://rust.godbolt.org/z/8j4MY6Wjj) (version without returning stride to make codegen easier to understand), but it's still basically free. The only functional change is adding a `rdx <- 0x8000000000000000 - rcx`, everything else is just slightly different register allocation.

</details>

The experience in the standard library does show that all allocation code respecting the `isize::MAX` limit is untenable. This PR chooses to automatically add `isize::MAX` enforcement to all layout calculation code. Asking all `GlobalAlloc` implementers to enforce the `isize::MAX` limit is at least *somewhat* reasonable (as they necessarily are already checking for *some* max), *but*

- hooking up an existing allocator (e.g. the system allocator) which *doesn't* provide a guarantee that allocations don't exceed `isize::MAX` bytes requires inserting the check separately, before hitting the real allocator to duplicate the size check anyway, and
- this makes *basically all* existing `GlobalAlloc` implementers *subtly* unsound in a rare edge case, and in a way likely to look like it's working until it just doesn't one day for *completely* inscrutable reasons.

The choice to enforce the `isize::MAX` limit in `Layout` wasn't done without reason. It's guaranteed effective and surprisingly cheap. The reason to have `GlobalAlloc::realloc` enforce the limit on the provider side would not be a performance one, it would be to avoid callers having to remember to check it. But there's an easier solution there: just deprecate `realloc` and use an API which takes `Layout`.

**Comment by CAD97** [comment]
I just filed [an API Change Proposal for how to handle `realloc`](https://github.com/rust-lang/libs-team/issues/61).

**Comment by scottmcm** [comment]
With this FCP completely, this looks good to go!  The current version is a nice staight-forward diff -- just the change to the threshold in one spot, and some unsafe constructors replaced with safe ones.

@bors r=scottmcm rollup=never

(`GlobalAlloc::realloc` can be left for a future PR.)

**Comment by CAD97** [comment]
These resuluts look similar to the [previous results](https://github.com/rust-lang/rust/pull/95295#issuecomment-1083707873).

The regression here is justified for being a soundness fix. Additionally, the diff here deliberately prefers an obviously correct smaller change over a more complicated change to combat perf impact.

Due to the number of instantiations of layout code, perf is extremely sensitive to seemingly inconsequential changes.

A follow-up PR could/should investigate if some perf can be recovered by doing manual inlining of `?` and option/result combinators to reduce the amount of IR that LLVM has to cut through (https://github.com/rust-lang/rust/issues/99117).

@rustbot label: +perf-regression-triaged
