### PR TITLE
Fix range misleading field access

### LINKED ISSUE #131471: {integer}..unresolved_ident suggests field access
### Code

```Rust
fn main() {
    let width = 10;
    // ...
    for _ in 0..w {
        
    }
}
```

### Current output

```
error[E0425]: cannot find value `w` in this scope
 --> src/main.rs:4:17
  |
4 |     for _ in 0..w {
  |                 ^ not found in this scope
  |
help: you might have meant to write `.` instead of `..`
  |
4 -     for _ in 0..w {
4 +     for _ in 0.w {
  |
```

### Desired output

```
error[E0425]: cannot find value `w` in this scope
 --> src/main.rs:4:17
  |
4 |     for _ in 0..w {
  |                 ^ not found in this scope
  |
```

### Rationale and extra context

Since integer literals do not have fields, it's odd to suggest field access.
It just confuses the user, rather than helping.

### Other cases

_No response_

### Rust Version

```
rustc 1.83.0-nightly (6f4ae0f34 2024-10-08)
binary: rustc
commit-hash: 6f4ae0f34503601e54680a137c1db0b81b56cc3d
commit-date: 2024-10-08
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hirschenberger**
Fixes #131471 by checking if the range-start is a literal.

### CODE REVIEW

File: tests/ui/range/missleading-field-access-hint.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// Check if rustc still displays the missleading hint to write `.` instead of `..`
```
Comment (davidtwco) [inline tests/ui/range/missleading-field-access-hint.rs:1]:
```suggestion
// Check if rustc still displays the misleading hint to write `.` instead of `..`
```

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Please fix the comment and squash this into one commit. Otherwise, looks fine and I can approve.

File: tests/ui/range/misleading-field-access-hint.stderr [hunk 2]
```diff
@@ -0,0 +1,9 @@
+error[E0425]: cannot find value `w` in this scope
+  --> $DIR/misleading-field-access-hint.rs:6:17
```
Comment (compiler-errors) [inline tests/ui/range/misleading-field-access-hint.stderr:2]: This line number needs to be updated or re-bless the test.
