### PR TITLE
Fix exponential projection complexity on nested types

### LINKED ISSUE #38528: Nonlinear compile time blow-up with deeply nested types
Compiling the postgres-tokio crate at https://github.com/sfackler/rust-postgres/commit/d27518ba76d76ccaa59b3ccd63e981bd8bd0ef33 goes from 5 seconds to 45 seconds on nightly if the two `.boxed()` calls in the middle of this call chain are removed: https://github.com/sfackler/rust-postgres/blob/d27518ba76d76ccaa59b3ccd63e981bd8bd0ef33/postgres-tokio/src/lib.rs#L342-L408.

Looks like 15 seconds is spent in translation item collection, and 39 seconds is spent in translation:

```
time: 0.004	parsing
time: 0.005	recursion limit
time: 0.000	crate injection
time: 0.001	plugin loading
time: 0.000	plugin registration
time: 0.238	expansion
time: 0.000	maybe building test harness
time: 0.000	maybe creating a macro crate
time: 0.000	checking for inline asm in case the target doesn't support it
time: 0.000	complete gated feature checking
time: 0.008	early lint checks
time: 0.000	AST validation
time: 0.005	name resolution
time: 0.004	lowering ast -> hir
time: 0.002	indexing hir
time: 0.000	attribute checking
time: 0.001	language item collection
time: 0.001	lifetime resolution
time: 0.000	looking for entry point
time: 0.000	looking for plugin registrar
time: 0.001	region resolution
time: 0.000	loop checking
time: 0.000	static item recursion checking
time: 0.005	compute_incremental_hashes_map
time: 0.000	load_dep_graph
time: 0.000	stability index
time: 0.001	stability checking
time: 0.011	type collecting
time: 0.000	variance inference
time: 0.000	impl wf inference
time: 0.021	coherence checking
time: 0.008	wf checking
time: 0.003	item-types checking
time: 0.500	item-bodies checking
time: 0.000	drop-impl checking
time: 0.003	const checking
time: 0.001	privacy checking
time: 0.000	intrinsic checking
time: 0.000	effect checking
time: 0.001	match checking
time: 0.000	liveness checking
time: 0.002	rvalue checking
time: 0.014	MIR dump
  time: 0.001	SimplifyCfg
  time: 0.002	QualifyAndPromoteConstants
  time: 0.002	TypeckMir
  time: 0.000	SimplifyBranches
  time: 0.001	SimplifyCfg
time: 0.006	MIR cleanup and validation
time: 0.006	borrow checking
time: 0.000	reachability checking
time: 0.000	death checking
time: 0.000	unused lib feature checking
time: 1.366	lint checking
time: 0.000	resolving dependency formats
  time: 0.000	NoLandingPads
  time: 0.001	SimplifyCfg
  time: 0.001	EraseRegions
  time: 0.000	AddCallGuards
  time: 0.008	ElaborateDrops
  time: 0.000	NoLandingPads
  time: 0.001	SimplifyCfg
  time: 0.001	InstCombine
  time: 0.000	Deaggregator
  time: 0.000	CopyPropagation
  time: 0.001	SimplifyLocals
  time: 0.000	AddCallGuards
  time: 0.000	PreTrans
time: 0.015	MIR optimisations
  time: 0.001	write metadata
  time: 15.086	translation item collection
  time: 0.020	codegen unit partitioning
  time: 0.022	internalize symbols
time: 39.376	translation
time: 0.000	assert dep graph
time: 0.000	serialize dep graph
  time: 0.089	llvm function passes [0]
  time: 0.037	llvm module passes [0]
  time: 2.148	codegen passes [0]
  time: 0.001	codegen passes [0]
time: 2.432	LLVM passes
time: 0.000	serialize work products
time: 0.084	linking
```

Things are significantly worse on 1.13 - 2 minutes in translation!

Some discussion in IRC: https://botbot.me/mozilla/rust-internals/2016-12-22/?msg=78294648&page=1

cc @aturon

------

UPDATE: #40280 was closed as a duplicate of this. It had the following sample code:

```rust
let &(first, B, C, D, E, F, G, H) = self;
let iter = first.buffers_list();
let iter = iter.chain(B.buffers_list());
let iter = iter.chain(C.buffers_list());
let iter = iter.chain(D.buffers_list());
let iter = iter.chain(E.buffers_list());
let iter = iter.chain(F.buffers_list());
let iter = iter.chain(G.buffers_list());
let iter = iter.chain(H.buffers_list());
Box::new(iter)
``` 

--nmatsakis

### LINKED ISSUE #39684: Compiler hangs during recursive monomorphisation
```Rust
use std::iter;

fn silly<I: Iterator<Item=()>>(it: I) {
    silly(it.chain(iter::empty()))
}

fn main() {
    println!("Start");
    silly(iter::empty());
    println!("Done");
}
```

This code causes compiler to be stuck wasting CPU cycles, instead of printing some kind of recursion limit error.

### LINKED ISSUE #43757: rustc/compiler deadlock when process recursive function
rustc/compiler deadlock when compile recursive function

I tried this code:

```
$ RUST_BACKTRACE=full RUST_LOG=trace LLVM_SYS_40_PREFIX=/usr/local/opt/llvm LLVM_SYS_40_FFI_WORKAROUND=1 cargo test
```

https://github.com/flier/rust-jit/blob/develop/llvm-jit/examples/kaleidoscope-chapter2.rs#L67

I expected to see this happen: **compile code or show error**

Instead, this happened: **rustc hang (CPU 100%)**

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0 (0ade33941 2017-07-17)
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-apple-darwin
release: 1.19.0
LLVM version: 4.0
```
Backtrace:
> INFO:rustc::traits::trans: Cache miss: Binder(<std::iter::TakeWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::str::Chars, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:62:57: 62:88]> as std::iter::Iterator>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), node: DefIndex(1866) => core/f813f38::iter[0]::{{impl}}[56] }, substs=Slice([std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::str::Chars, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:62:57: 62:88]]), nested=[(), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ()])

> INFO:rustc::traits::trans: Cache miss: Binder(<std::iter::TakeWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::str::Chars, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:53:61: 53:84]> as std::iter::IntoIterator>) => VtableImpl(impl_def_id=DefId { krate: CrateNum(2), node: DefIndex(1675) => core/f813f38::iter[0]::traits[0]::{{impl}}[0] }, substs=Slice([std::iter::TakeWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::iter::SkipWhile<std::iter::Peekable<std::iter::SkipWhile<&mut std::str::Chars, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:67:48: 67:75]>, [closure@examples/kaleidoscope-chapter2.rs:48:40: 48:61]>>, [closure@examples/kaleidoscope-chapter2.rs:53:61: 53:84]>]), nested=[(), ()])

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This implements solution 1 from https://github.com/rust-lang/rust/issues/38528#issuecomment-366263076.

The code quality was extremely poor, but  it has improved during review.

Blocking issues:

- we probably don't want a quadratic deduplication for obligations.
- is there an alternative to deduplication?

Based on #48315.

Needs changelog. Noticable improvement on compile time is expected.

Fix #38528
Close #39684
Close #43757

### CODE REVIEW

File: src/librustc/traits/project.rs [hunk 1]
```diff
@@ -818,55 +822,74 @@ fn project_type<'cx, 'gcx, 'tcx>(
                                        &obligation_trait_ref,
                                        &mut candidates);
 
+    let decide_commit = |candidates: &mut ProjectionTyCandidateSet<'tcx>| {
```
Comment (ishitatsuyuki) [inline src/librustc/traits/project.rs]: I have no way but to reorder this before the error handling. It looks non intuitive.

File: src/librustc/traits/project.rs [hunk 2]
```diff
@@ -818,55 +822,74 @@ fn project_type<'cx, 'gcx, 'tcx>(
...
+        if candidates.vec.len() > 1 {
+            debug!("retaining param-env candidates only from {:?}", candidates.vec);
+            candidates.vec.retain(|c| match *c {
+                ProjectionTyCandidate::ParamEnv(..) => true,
+                ProjectionTyCandidate::TraitDef(..) |
+                ProjectionTyCandidate::Select(..) => false,
+            });
+            debug!("resulting candidate set: {:?}", candidates.vec);
+            if candidates.vec.len() != 1 {
+                candidates.ambiguous = true;
```
Comment (ishitatsuyuki) [inline src/librustc/traits/project.rs]: This is nearly a hack.

File: src/librustc/traits/project.rs [hunk 3]
```diff
@@ -1014,19 +1044,19 @@ fn assemble_candidates_from_impls<'cx, 'gcx, 'tcx>(
             Err(e) => {
                 debug!("assemble_candidates_from_impls: selection error {:?}",
                        e);
-                return Err(e);
+                return Err(NoImplCandidateError::SelectionError(e));
             }
         };
 
-        match vtable {
+        match vtable.clone() {
```
Comment (ishitatsuyuki) [inline src/librustc/traits/project.rs]: This copy can be avoided.

**Review by ishitatsuyuki — COMMENTED** [review]
Here are some self-reminders.

**Comment by ishitatsuyuki** [comment]
The other part of the blowup (typeck related) is yet to be solved, but I think the code is ready for a round of review. I have removed whitespace changes and clarified the description.

**Comment by ishitatsuyuki** [comment]
@kennytm A reminder for you to change the review labels.

**Comment by kennytm** [comment]
@bors try

Let’s do a perf check while we’re waiting for review :)

**Comment by kennytm** [comment]
@ishitatsuyuki please remove the `[wip]` from the PR title if it is ready for review.

**Comment by ishitatsuyuki** [comment]
Well, I'm currently tackling another part of the exponential issue (so this is WIP), but I need comments on improving the code organization.

**Comment by ishitatsuyuki** [comment]
By deduplicating the obligations the issue is completely resolved. I'm not sure if this approach is the best way though, and I copied the dumb deduplication becuase I didn't want to implement Ord everywhere. I will fix them later.

**Comment by ishitatsuyuki** [comment]
@kennytm I need another try.

**Comment by ishitatsuyuki** [comment]
@Mark-Simulacrum can you queue a perf run?

**Comment by Mark-Simulacrum** [comment]
Perf run started.

**Comment by kennytm** [comment]
@ishitatsuyuki great! The `servo-style-opt` `clean incremental-opt` test is regressed a lot though, could you investigate this?

**Comment by ishitatsuyuki** [comment]
@kennytm that one is spurious, check out the graph and you will see that fluctuating.
(The perf instance is currently down, try later)

File: src/librustc/traits/select.rs [hunk 4]
```diff
@@ -3293,6 +3293,17 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
                     predicate: predicate.value
                 }))
         }).collect();
+        if predicates.len() > 1 {
```
Comment (ishitatsuyuki) [inline src/librustc/traits/select.rs]: This is not only quadratic but also breaks the order assumption. We need to locate the root cause.

**Comment by nikomatsakis** [comment]
I'm reading and building locally. Thanks @ishitatsuyuki for this exploration =)

**Comment by nikomatsakis** [comment]
Unfortunately running out of time today to dig more deeply but will do more tomorrow

**Comment by nikomatsakis** [comment]
@ishitatsuyuki 

> This is not only quadratic but also breaks the order assumption. We need to locate the root cause.

Can you elaborate on this sentence? Root cause of what exactly?

File: src/librustc/traits/project.rs [hunk 5]
```diff
@@ -818,55 +819,57 @@ fn project_type<'cx, 'gcx, 'tcx>(
                                        &obligation_trait_ref,
                                        &mut candidates);
```
Comment (nikomatsakis) [inline src/librustc/traits/project.rs]: This core idea here seems great, but -- as you said -- this setup feels a bit awkward to read. I think we can make the code flow much nicer, however. Perhaps we should change the "candidate set" data structure into something like this:

```rust
enum ProjectionTyCandidateSet<'tcx> {
    None,
    Single(ProjectionTyCandidate<'tcx>),
    Ambiguous,
}

impl<'tcx> ProjectionTyCandidateSet<'tcx> {
    fn mark_ambiguous(&mut self) {
        *self = ProjectionTyCandidateSet::Ambiguous;
    }

    // Returns true if the push was successful, or false if the candidate
    // was discarded -- this could be because of ambiguity, or because
    // a higher-priority candidate is already there.
    fn push_candidate(&mut self, candidate: ProjectionTyCandidate<'tcx>) -> bool {
        match self {
            ProjectionTyCandidateSet::None => {
                *self = ProjectionTyCandidateSet::Single(candidate);
                true
            }

            ProjectionTyCandidateSet::Single(ProjectionTyCandidate::ParamEnv(..)) => {
                if let ProjectionTyCandidate::ParamEnv(..) = candidate {
                    *self = ProjectionTyCandidateSet::Ambiguous;
                }
                false
            }

            ProjectionTyCandidateSet::Single(..) => {
                *self = ProjectionTyCandidateSet::Ambiguous;
                false
            }

            ProjectionTyCandidateSet::Ambiguous => {
                false
            }
        }
    }
}
```

Then, each time that we now "push onto the set", we can instead invoke `push_candidate`. This lets us drop the closure -- instead we use the return value of this method to decide whether to "keep" the snapshot.

File: src/librustc/traits/project.rs [hunk 6]
```diff
@@ -818,55 +819,57 @@ fn project_type<'cx, 'gcx, 'tcx>(
...
 
-    // Drop duplicates.
-    //
-    // Note: `candidates.vec` seems to be on the critical path of the
-    // compiler. Replacing it with an HashSet was also tried, which would
-    // render the following dedup unnecessary. The original comment indicated
-    // that it was 9% slower, but that data is now obsolete and a new
-    // benchmark should be performed.
-    candidates.vec.sort_unstable();
-    candidates.vec.dedup();
```
Comment (nikomatsakis) [inline src/librustc/traits/project.rs]: Indeed I can't really see how duplicates would appear in here right now -- unless there were duplicates in the param-env etc, but the elaboration step removes those right now, so I think that shouldn't happen. Maybe add an assertion in the `push_candidate` step above -- when we push a candidate but still have an old one, they should never be the same.

File: src/librustc/traits/select.rs (hunk 4 above)
Comment (nikomatsakis) [reply src/librustc/traits/select.rs]: I don't quite know what you're saying here. However, you could instead de-duplicate by accumulating into a hashset:

```rust
let mut hashset = HashSet::new();
predicates.retain(|&i| hashset.insert(i));
```

This is -- in theory -- O(1) and preserves ordering.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Comment by nikomatsakis** [comment]
Sorry for taking a few days to review! Wanted to give this the time it deserves. Nice insight!

**Review by ishitatsuyuki — COMMENTED** [review]
Thanks for the comprehensive review. I will implement the changes later.

File: src/librustc/traits/select.rs (hunk 4 above)
Comment (stjepang) [reply src/librustc/traits/select.rs]: Another option is:

```rust
predicates.sort_unstable(); 
predicates.dedup();
```

Comment (ishitatsuyuki) [reply src/librustc/traits/select.rs]: No. First of all this doesn't preserve order, and second implement Ord on all transitively contained types is a frustrating thing.

**Comment by ishitatsuyuki** [comment]
Ready for review.

**Comment by ishitatsuyuki** [comment]
r? @nikomatsakis

Please change the label...

File: src/librustc/traits/project.rs [hunk 7]
```diff
@@ -1129,10 +1135,18 @@ fn assemble_candidates_from_impls<'cx, 'gcx, 'tcx>(
...
+        if eligible {
+            if candidate_set.push_candidate(ProjectionTyCandidate::Select(vtable)) {
+                Ok(())
+            } else {
+                Err(())
+            }
+        } else {
+            Err(())
+        }
+    });
```
Comment (nikomatsakis) [inline src/librustc/traits/project.rs]: I like the change to push errors into the candidate set. This is less confusing this way.

File: src/librustc/traits/select.rs [hunk 8]
```diff
@@ -3293,6 +3293,13 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
                     predicate: predicate.value
                 }))
         }).collect();
+        // We are performing deduplication here to avoid exponential blowups
+        // (#38528) from happening, but the real cause of the duplication is
+        // unknown. What we know is that the deduplication avoids exponential
+        // amount of predicates being propogated when processing deeply nested
+        // types.
+        let mut seen = FxHashSet();
```
Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: Oh, it seems like duplicates could come from many sources -- in particular, normalization might introduce the same obligation a few times.

**Review by nikomatsakis — APPROVED** [review]
Looks great =)

File: src/librustc/traits/project.rs (hunk 7 above)
Comment (ishitatsuyuki) [reply src/librustc/traits/project.rs]: I'm not sure if I understand. I already handle SelectionError above, and these Ok and Err is the return value to `commit_if_ok`.

**Comment by nikomatsakis** [comment]
@bors r+

@ishitatsuyuki -- it'd be great to add at least one of these exponential blow-up cases to the perf website so we can monitor for regressions. Perhaps @Mark-Simulacrum can walk you through it.
