### PR TITLE
MGCA: Const constructors support

### LINKED ISSUE #132985: Support `ConstArgKind::Path`s for const struct/variant constructors
Requires encoding const ctors in MIR metadata (not currently done for some reason). May affect perf. cc #131081.

### LINKED ISSUE #136138: Rustc crashes at compiler/rustc_middle/src/ty/instance.rs, caused by assertion `left matches right` failed
### Code

Note that if we remove the first line `#![feature(min_generic_const_args)]`, the panic disappeares.

```Rust
#![feature(min_generic_const_args)]
struct U;
struct S<const N: U>()
where
    S<{ U }>:;
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.86.0-nightly (f85c6de55 2025-01-26)
binary: rustc
commit-hash: f85c6de55206dbee5ffedfd821df1503a7b92346
commit-date: 2025-01-26
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7
```

### Error output

```
arning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> 1.rs:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default


thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:531:9:
assertion `left matches right` failed: `Instance::try_resolve` should only be used to resolve instances of functions, statics, and consts; to resolve associated types, use `try_normalize_erasing_regions`.
  left: Ctor(Struct, Const)
 right: DefKind::Fn | DefKind::AssocFn | DefKind::Const | DefKind::AssocConst |
DefKind::AnonConst | DefKind::InlineConst | DefKind::Static { .. } |
DefKind::Ctor(_, CtorKind::Fn) | DefKind::Closure |
DefKind::SyntheticCoroutineBody
stack backtrace:
   0:     0x7fa280d3c210 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hec9bc6463e252640
   1:     0x7fa2815acee6 - core::fmt::write::h962cad0079919c7e
   2:     0x7fa2824aac51 - std::io::Write::write_fmt::h081e59591f35f868
   3:     0x7fa280d3c072 - std::sys::backtrace::BacktraceLock::print::he0deffbd85e9a2c5
   4:     0x7fa280d3e4f2 - std::panicking::default_hook::{{closure}}::h99776b3a5456e866
   5:     0x7fa280d3e37a - std::panicking::default_hook::hcad38b9ed4b5517d
   6:     0x7fa27fef3279 - std[cc940dec3ff43b12]::panicking::update_hook::<alloc[5f7a888829935c2b]::boxed::Box<rustc_driver_impl[af2bdb3744899392]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7fa280d3f073 - std::panicking::rust_panic_with_hook::hbfeeff1ab3569ba1
   8:     0x7fa280d3ed6a - std::panicking::begin_panic_handler::{{closure}}::h32c93c4f5d28ab99
   9:     0x7fa280d3c6e9 - std::sys::backtrace::__rust_end_short_backtrace::h1884c239824d44f7
  10:     0x7fa280d3ea2d - rust_begin_unwind
  11:     0x7fa27d9d1bd0 - core::panicking::panic_fmt::he58927c3c03479ba
  12:     0x7fa27f915586 - core::panicking::assert_failed_inner::hfb3c935e17727acd
  13:     0x7fa28049b942 - core[c1de5c9ad145c0db]::panicking::assert_matches_failed::<rustc_hir[2d8a80fbfdaaf69c]::def::DefKind>
  14:     0x7fa2817a1f93 - <rustc_middle[ea35cf57050946b4]::ty::instance::Instance>::try_resolve
  15:     0x7fa282284cf1 - <rustc_middle[ea35cf57050946b4]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  16:     0x7fa282284a77 - rustc_trait_selection[9f2c8c71993b8584]::traits::try_evaluate_const
  17:     0x7fa282284513 - <rustc_trait_selection[9f2c8c71993b8584]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[de1b3d84f3386c16]::fold::TypeFolder<rustc_middle[ea35cf57050946b4]::ty::context::TyCtxt>>::fold_const
  18:     0x7fa281dd0361 - <rustc_trait_selection[9f2c8c71993b8584]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[de1b3d84f3386c16]::fold::FallibleTypeFolder<rustc_middle[ea35cf57050946b4]::ty::context::TyCtxt>>::try_fold_binder::<rustc_type_ir[de1b3d84f3386c16]::predicate_kind::PredicateKind<rustc_middle[ea35cf57050946b4]::ty::context::TyCtxt>>
  19:     0x7fa2819bcdb8 - rustc_trait_selection[9f2c8c71993b8584]::traits::normalize::normalize_with_depth_to::<rustc_middle[ea35cf57050946b4]::ty::predicate::Predicate>
  20:     0x7fa2819bbb57 - rustc_trait_selection[9f2c8c71993b8584]::traits::wf::clause_obligations
  21:     0x7fa2819c0388 - rustc_hir_analysis[ce12ae6d63b57b8a]::check::wfcheck::check_where_clauses
  22:     0x7fa281bd5e00 - rustc_hir_analysis[ce12ae6d63b57b8a]::check::wfcheck::check_type_defn
  23:     0x7fa281bcf821 - rustc_hir_analysis[ce12ae6d63b57b8a]::check::wfcheck::check_well_formed
  24:     0x7fa281bce247 - rustc_query_impl[52b9445d4dcf70be]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[52b9445d4dcf70be]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 1usize]>>
  25:     0x7fa281bcdce9 - rustc_query_system[b5c6449b7ccd2566]::query::plumbing::try_execute_query::<rustc_query_impl[52b9445d4dcf70be]::DynamicConfig<rustc_data_structures[aef26e4d10f0fc6d]::vec_cache::VecCache<rustc_span[d5a27b28009c9e0]::def_id::LocalDefId, rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[b5c6449b7ccd2566]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[52b9445d4dcf70be]::plumbing::QueryCtxt, false>
  26:     0x7fa281bcd746 - rustc_query_impl[52b9445d4dcf70be]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7fa281bcb36c - rustc_hir_analysis[ce12ae6d63b57b8a]::check::wfcheck::check_mod_type_wf
  28:     0x7fa281bcb18b - rustc_query_impl[52b9445d4dcf70be]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[52b9445d4dcf70be]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7fa2824b2ac8 - rustc_query_system[b5c6449b7ccd2566]::query::plumbing::try_execute_query::<rustc_query_impl[52b9445d4dcf70be]::DynamicConfig<rustc_query_system[b5c6449b7ccd2566]::query::caches::DefaultCache<rustc_span[d5a27b28009c9e0]::def_id::LocalModDefId, rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[52b9445d4dcf70be]::plumbing::QueryCtxt, false>
  30:     0x7fa2824b2870 - rustc_query_impl[52b9445d4dcf70be]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fa2819371e6 - rustc_hir_analysis[ce12ae6d63b57b8a]::check_crate
  32:     0x7fa281933aa2 - rustc_interface[d0d5d02e7a56d74f]::passes::run_required_analyses
  33:     0x7fa2824a635e - rustc_interface[d0d5d02e7a56d74f]::passes::analysis
  34:     0x7fa2824a632f - rustc_query_impl[52b9445d4dcf70be]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[52b9445d4dcf70be]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 0usize]>>
  35:     0x7fa282493315 - rustc_query_system[b5c6449b7ccd2566]::query::plumbing::try_execute_query::<rustc_query_impl[52b9445d4dcf70be]::DynamicConfig<rustc_query_system[b5c6449b7ccd2566]::query::caches::SingleCache<rustc_middle[ea35cf57050946b4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[52b9445d4dcf70be]::plumbing::QueryCtxt, false>
  36:     0x7fa28249304e - rustc_query_impl[52b9445d4dcf70be]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7fa2824b9429 - rustc_interface[d0d5d02e7a56d74f]::passes::create_and_enter_global_ctxt::<core[c1de5c9ad145c0db]::option::Option<rustc_interface[d0d5d02e7a56d74f]::queries::Linker>, rustc_driver_impl[af2bdb3744899392]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  38:     0x7fa282504213 - rustc_interface[d0d5d02e7a56d74f]::interface::run_compiler::<(), rustc_driver_impl[af2bdb3744899392]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7fa282400eb5 - std[cc940dec3ff43b12]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d0d5d02e7a56d74f]::util::run_in_thread_with_globals<rustc_interface[d0d5d02e7a56d74f]::util::run_in_thread_pool_with_globals<rustc_interface[d0d5d02e7a56d74f]::interface::run_compiler<(), rustc_driver_impl[af2bdb3744899392]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  40:     0x7fa282400b99 - <<std[cc940dec3ff43b12]::thread::Builder>::spawn_unchecked_<rustc_interface[d0d5d02e7a56d74f]::util::run_in_thread_with_globals<rustc_interface[d0d5d02e7a56d74f]::util::run_in_thread_pool_with_globals<rustc_interface[d0d5d02e7a56d74f]::interface::run_compiler<(), rustc_driver_impl[af2bdb3744899392]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[c1de5c9ad145c0db]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fa28240032b - std::sys::pal::unix::thread::Thread::new::thread_start::hb22e947f5885a296
  42:     0x7fa27c756609 - start_thread
                               at /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8
  43:     0x7fa27c67b353 - clone
                               at /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95:0
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### LINKED ISSUE #139596: ICE: `Instance::try_resolve` should only be used to resolve instances of functions, statics, and consts; to resolve associated types, use `try_normalize_erasing_regions`
auto-reduced (treereduce-rust):
````rust
#![feature(min_generic_const_args)]
enum Colour {
    R,
    G,
    B,
    W,
}

struct Led<const C: Colour> {}

impl Led<C> {
    pub fn new() -> Led {
        Led::<{ Colour::W }> {}
    }
}

````

original:
````rust
#![feature(adt_const_params)]
#![feature(generic_const_exprs)]
#![feature(generic_arg_infer)]

#[derive(PartialEq, Eq)]
#[allow(dead_code)]
enum Colour {
    R,
    G,
    B,
    W,
}

struct Led<const C: Colour> {}

impl<const C: Colour> Led<C> {
    pub fn new() -> Led<{ Colour::W }> {
        Led::<{ Colour::W }> {}
    }
}

fn main() {
    let l = Led::<_>::new();
}

````

Version information
````
rustc 1.88.0-nightly (48f89e765 2025-04-09)
binary: rustc
commit-hash: 48f89e7659678f91a68c0c2d868180a0036ab32d
commit-date: 2025-04-09
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/48f89e7659678f91a68c0c2d868180a0036ab32d/compiler/rustc_middle/src/ty/instance.rs#L482-L494

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(min_generic_const_args)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `C` in this scope
  --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:10:10
   |
10 | impl Led<C> {
   |          ^ not found in this scope
   |
help: you might be missing a type parameter
   |
10 | impl<C> Led<C> {
   |     +++

warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(min_generic_const_args)
  |         ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:14:2
   |
14 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs`

error: `Colour` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:8:21
  |
8 | struct Led<const C: Colour> {}
  |                     ^^^^^^
  |
  = note: the only supported types are integers, `bool`, and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
  |
1 + #![feature(adt_const_params)]
  |

error[E0747]: unresolved item provided when a constant was expected
  --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:10:10
   |
10 | impl Led<C> {
   |          ^
   |
help: if this generic argument was intended as a const parameter, surround it with braces
   |
10 | impl Led<{ C }> {
   |          +   +

error[E0107]: missing generics for struct `Led`
  --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:11:21
   |
11 |     pub fn new() -> Led {
   |                     ^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `C`
  --> /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:8:8
   |
8  | struct Led<const C: Colour> {}
   |        ^^^ ---------------
help: add missing generic argument
   |
11 |     pub fn new() -> Led<C> {
   |                        +++


thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:488:9:
assertion `left matches right` failed: `Instance::try_resolve` should only be used to resolve instances of functions, statics, and consts; to resolve associated types, use `try_normalize_erasing_regions`.
  left: Ctor(Variant, Const)
 right: DefKind::Fn | DefKind::AssocFn | DefKind::Const | DefKind::AssocConst |
DefKind::AnonConst | DefKind::InlineConst | DefKind::Static { .. } |
DefKind::Ctor(_, CtorKind::Fn) | DefKind::Closure |
DefKind::SyntheticCoroutineBody
stack backtrace:
   0:     0x7ca5f569a5f3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbda7938ad91daa71
   1:     0x7ca5f5e06091 - core::fmt::write::hfcac35951f31bfd5
   2:     0x7ca5f7221911 - std::io::Write::write_fmt::h69d457bf709d3faa
   3:     0x7ca5f569a452 - std::sys::backtrace::BacktraceLock::print::h05237cc9fabaf381
   4:     0x7ca5f569df3a - std::panicking::default_hook::{{closure}}::hc30470ec32c9e61a
   5:     0x7ca5f569dabf - std::panicking::default_hook::h1a06328d8fcb4b65
   6:     0x7ca5f46f3be3 - std[5a1f1ac0881987ae]::panicking::update_hook::<alloc[80a1e000ee70d0ff]::boxed::Box<rustc_driver_impl[3e4c5d0d05c5c229]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7ca5f569e7b3 - std::panicking::rust_panic_with_hook::ha54ddc764a9f2927
   8:     0x7ca5f569e4aa - std::panicking::begin_panic_handler::{{closure}}::h766080f7c8e9eb7a
   9:     0x7ca5f569aac9 - std::sys::backtrace::__rust_end_short_backtrace::haf576155c2de2f94
  10:     0x7ca5f569e16d - __rustc[10dcd0340a2c482b]::rust_begin_unwind
  11:     0x7ca5f2082630 - core::panicking::panic_fmt::h005ce51f4b5ab7a3
  12:     0x7ca5f40c5fba - core::panicking::assert_failed_inner::h4b65bb9eccf86241
  13:     0x7ca5f4d00a84 - core[4dde9abed1c5489b]::panicking::assert_matches_failed::<rustc_hir[9c43573b07d67dbb]::def::DefKind>
  14:     0x7ca5f62125ef - <rustc_middle[a8ce42bc99515a22]::ty::instance::Instance>::try_resolve
  15:     0x7ca5f68e1695 - <rustc_middle[a8ce42bc99515a22]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  16:     0x7ca5f68e11cc - rustc_trait_selection[9b8f5593c6c1191c]::traits::try_evaluate_const
  17:     0x7ca5f68e0c83 - <rustc_trait_selection[9b8f5593c6c1191c]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[f99837588d296a38]::fold::TypeFolder<rustc_middle[a8ce42bc99515a22]::ty::context::TyCtxt>>::fold_const
  18:     0x7ca5f6250ef7 - <rustc_middle[a8ce42bc99515a22]::ty::Ty as rustc_type_ir[f99837588d296a38]::fold::TypeSuperFoldable<rustc_middle[a8ce42bc99515a22]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection[9b8f5593c6c1191c]::traits::normalize::AssocTypeNormalizer>
  19:     0x7ca5f60a0a85 - <rustc_hir_typeck[7cddd7bac5f9e6c7]::fn_ctxt::FnCtxt>::normalize::<rustc_middle[a8ce42bc99515a22]::ty::Ty>
  20:     0x7ca5f60dc6df - <rustc_hir_typeck[7cddd7bac5f9e6c7]::fn_ctxt::FnCtxt>::check_struct_path
  21:     0x7ca5f697b00e - <rustc_hir_typeck[7cddd7bac5f9e6c7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:     0x7ca5f69703f7 - <rustc_hir_typeck[7cddd7bac5f9e6c7]::fn_ctxt::FnCtxt>::check_expr_block
  23:     0x7ca5f6977dfe - <rustc_hir_typeck[7cddd7bac5f9e6c7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x7ca5f60b5084 - rustc_hir_typeck[7cddd7bac5f9e6c7]::check::check_fn
  25:     0x7ca5f60a259a - rustc_hir_typeck[7cddd7bac5f9e6c7]::typeck_with_inspect::{closure#0}
  26:     0x7ca5f60a12b6 - rustc_query_impl[304b34704ffb34a2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[304b34704ffb34a2]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a8ce42bc99515a22]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7ca5f607c66c - rustc_query_system[9941410aea4cdd96]::query::plumbing::try_execute_query::<rustc_query_impl[304b34704ffb34a2]::DynamicConfig<rustc_data_structures[7aca4433282a48ef]::vec_cache::VecCache<rustc_span[a10dda05a280b721]::def_id::LocalDefId, rustc_middle[a8ce42bc99515a22]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[9941410aea4cdd96]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[304b34704ffb34a2]::plumbing::QueryCtxt, false>
  28:     0x7ca5f607c0cb - rustc_query_impl[304b34704ffb34a2]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7ca5f607ac7e - rustc_hir_analysis[6987030d2b35bee6]::check_crate
  30:     0x7ca5f68277e3 - rustc_interface[145e5df1fb885f40]::passes::run_required_analyses
  31:     0x7ca5f6e2f09e - rustc_interface[145e5df1fb885f40]::passes::analysis
  32:     0x7ca5f6e2f073 - rustc_query_impl[304b34704ffb34a2]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[304b34704ffb34a2]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a8ce42bc99515a22]::query::erase::Erased<[u8; 0usize]>>
  33:     0x7ca5f6dc42fd - rustc_query_system[9941410aea4cdd96]::query::plumbing::try_execute_query::<rustc_query_impl[304b34704ffb34a2]::DynamicConfig<rustc_query_system[9941410aea4cdd96]::query::caches::SingleCache<rustc_middle[a8ce42bc99515a22]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[304b34704ffb34a2]::plumbing::QueryCtxt, false>
  34:     0x7ca5f6dc3ff8 - rustc_query_impl[304b34704ffb34a2]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7ca5f714f54b - rustc_interface[145e5df1fb885f40]::passes::create_and_enter_global_ctxt::<core[4dde9abed1c5489b]::option::Option<rustc_interface[145e5df1fb885f40]::queries::Linker>, rustc_driver_impl[3e4c5d0d05c5c229]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  36:     0x7ca5f6f49c39 - rustc_interface[145e5df1fb885f40]::interface::run_compiler::<(), rustc_driver_impl[3e4c5d0d05c5c229]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7ca5f6f1f945 - std[5a1f1ac0881987ae]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[145e5df1fb885f40]::util::run_in_thread_with_globals<rustc_interface[145e5df1fb885f40]::util::run_in_thread_pool_with_globals<rustc_interface[145e5df1fb885f40]::interface::run_compiler<(), rustc_driver_impl[3e4c5d0d05c5c229]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  38:     0x7ca5f6f2022b - <<std[5a1f1ac0881987ae]::thread::Builder>::spawn_unchecked_<rustc_interface[145e5df1fb885f40]::util::run_in_thread_with_globals<rustc_interface[145e5df1fb885f40]::util::run_in_thread_pool_with_globals<rustc_interface[145e5df1fb885f40]::interface::run_compiler<(), rustc_driver_impl[3e4c5d0d05c5c229]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[4dde9abed1c5489b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7ca5f6f21637 - std::sys::pal::unix::thread::Thread::new::thread_start::hd9ac46f49686eea4
  40:     0x7ca5f0c4e70a - <unknown>
  41:     0x7ca5f0cd2aac - <unknown>
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (48f89e765 2025-04-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(min_generic_const_args) -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `<impl at /tmp/icemaker_global_tempdir.z28WUAJGFSOZ/rustc_testrunner_tmpdir_reporting.d34pcMyh8VAF/mvce.rs:10:1: 10:12>::new`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0107, E0412, E0601, E0747.
For more information about an error, try `rustc --explain E0107`.

```

</p>
</details>

@rustbot label  +F-min_generic_const_args

### PR DESCRIPTION
**Pull request by Kivooeo**
part of https://github.com/rust-lang/rust/issues/132980

fixes rust-lang/rust#132985
fixes rust-lang/rust#136138
fixes rust-lang/rust#139596

r? BoxyUwU

### CODE REVIEW

**Review by BoxyUwU — COMMENTED** [review]
awesome! Can you add a test for const constructors using generic parameters, e.g. `Option::None::<T>` or `Struct::<T>`

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150704/b7bcaa5c715ed07af2d74dac7ddb8786abeb4299..c61bfa7bc8b48950fa43975437d12ac4f41d5588)*

File: tests/ui/const-generics/mgca/const-ctor.rs [hunk 1]
```diff
@@ -0,0 +1,37 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/139596>
+//!                     <https://github.com/rust-lang/rust/issues/136138>
+//!                     <https://github.com/rust-lang/rust/issues/132985>
+//!                     <https://github.com/rust-lang/rust/issues/105952>
+
+//@ check-pass
+
+#![feature(min_generic_const_args, associated_const_equality, adt_const_params)]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/const-ctor.rs]: This will conflict with #150640 so I'll wait for that to land before merging this

File: tests/ui/const-generics/mgca/const-ctor-with-error.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// to ensure it does not ices like before
```
Comment (Kivooeo) [inline tests/ui/const-generics/mgca/const-ctor-with-error.rs:1]: it's vague but there is not open issue for this so... or maybe there does, i actually don't know :D

Comment (BoxyUwU) [reply tests/ui/const-generics/mgca/const-ctor-with-error.rs:1]: ah I meant something a bit different but this is a good test to have too! I meant something like:
```rust
#![feature(generic_const_parameter_types, min_generic_const_args, adt_const_params, unsized_const_params)]

use core::marker::{ConstParamTy, ConstParamTy_};

#[derive(Eq, PartialEq, ConstParamTy);
struct Foo<const N: usize>;
#[derive(Eq, PartialEq, ConstParamTy);
enum Bar<T>() { Dataless, Other(T) }

fn accepts_foo<const N: usize, const M: Foo<N>>() {}
fn accepts_bar<T: ConstParamTy_, const N: Bar<T>>() {}

fn test<T: ConstParamTy_, const N: usize>() {
    accepts_foo::<N, { Foo::<N> }>();
    accepts_bar::<T, { Bar::Dataless::<T> }>();
}
```

Comment (Kivooeo) [reply tests/ui/const-generics/mgca/const-ctor-with-error.rs:1]: I added test with enum to check-pass test 

```rust 
pass_enum::<{ MyOption::None::<u32> }>();
```
and with struct to error test since it's something that I couldn't make compile sadly

```rust
accepts_foo::<N, { Foo::<{ N }> }>();
```

Comment (BoxyUwU) [reply tests/ui/const-generics/mgca/const-ctor-with-error.rs:1]: > `pass_enum::<{ MyOption::None::<u32> }>();`

this isn't what I wanted you to test, I want to test that `MyOption::None::<T>` works.

> `accepts_foo::<N, { Foo::<{ N }> }>();`

to make this work you need to enable `feature(generic_const_parameter_types)`

**Review by BoxyUwU — APPROVED** [review]
r=me once #150640 lands

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150704/bd33b83cfdbac9bffa3b04aaef95ec97827909a9..e4c04159b480cedc38c964bdda3fd0ee628fd29b)*

File: tests/crashes/mgca/ace-with-const-ctor.rs [hunk 3]
```diff
@@ -1,16 +0,0 @@
-//@ known-bug: #132980
-// Originally a rustdoc test. Should be moved back there with @has checks
```
Comment (BoxyUwU) [inline tests/crashes/mgca/ace-with-const-ctor.rs:2]: oh this was originally a rustdoc test you need to put it back where it used to be, not as a ui test

Comment (BoxyUwU) [reply tests/crashes/mgca/ace-with-const-ctor.rs:2]: https://github.com/rust-lang/rust/commit/5171e42cec2635a2d34a64b5da0b18070d334305

Comment (Kivooeo) [reply tests/crashes/mgca/ace-with-const-ctor.rs:2]: like this? https://github.com/rust-lang/rust/pull/150704/changes#diff-cb33f35c19a32a17853438e3e56fa966e1cbcd9c0a79e92d13682d880c89fdc5

Comment (BoxyUwU) [reply tests/crashes/mgca/ace-with-const-ctor.rs:2]: not quite, you need to add the `//@ hasraw` annotations like it originally had, and can you put it back in the same directory with the same name?

Comment (Kivooeo) [reply tests/crashes/mgca/ace-with-const-ctor.rs:2]: yep, should be better now

Comment (Kivooeo) [reply tests/crashes/mgca/ace-with-const-ctor.rs:2]: also removed a link from `const-ctor.rs` test

**Comment by BoxyUwU** [comment]
@bors r+ rollup

cool!
