### PR TITLE
Change the order of imports suggestions

### LINKED ISSUE #83564: Rustc suggests both std and core imports at times
rustc often offers a help to import something from std and core:

```rust
error[E0433]: failed to resolve: use of undeclared type `NonZeroU32`
  --> ...\test.rs:20:33
   |
20 | ...                   NonZeroU32::new(5).unwrap(),
   |                       ^^^^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
6  | use core::num::NonZeroU32;
   |
6  | use std::num::NonZeroU32;
   |
```

Perhaps in such situations rustc could use an heuristic to suggest only one of the two imports.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #83564

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1707,6 +1707,12 @@ crate fn show_candidates(
         candidates.iter().map(|c| path_names_to_string(&c.path)).collect();
 
     path_strings.sort();
+    let core_path_strings =
+        path_strings.iter().filter(|p| p.starts_with("core::")).cloned().collect::<Vec<String>>();
+    if !core_path_strings.is_empty() {
+        path_strings.retain(|p| !p.starts_with("core::"));
```
Comment (joshtriplett) [inline compiler/rustc_resolve/src/diagnostics.rs:1713]: This is minor, and we don't need to worry too much about the performance of generating suggestions, but it feels like this ought to be doable in one pass, removing and moving the elements matching `core::`.

This would be a good use case for the (currently unstable) `drain_filter` method.

Comment (TaKO8Ki) [reply compiler/rustc_resolve/src/diagnostics.rs]: Thank you for your advice! I fixed it.

**Comment by camelid** [comment]
Does this change need a regression test for the diagnostic?
