### PR TITLE
Make operational semantics of pattern matching independent of crate and module

### LINKED ISSUE #4778: match on an enum with a single inhabited variant does not read discriminant
Examples by @meithecatte; Cc @Nadrieril 
The following code should likely trigger UB, but currently Miri raises no error:
```rust
#![feature(never_type)]

#[repr(C)]
#[allow(dead_code)]
enum E {
  V1, // discriminant: 0
  V2(!), // 1
}

fn main() {
    assert_eq!(std::mem::size_of::<E>(), 4);

    let val = 1u32;
    let ptr = (&raw const val).cast::<E>();
    let r = unsafe { &*ptr };
    match r { //~ we'd probably want ERROR: read discriminant of an uninhabited enum variant
        E::V1 => {}
        E::V2(_) => {}
    }
}
```
The same goes for this variant that adds a closure (to check interactions with https://github.com/rust-lang/rust/pull/138961):
```rust
#![feature(never_type)]

#[repr(C)]
#[allow(dead_code)]
enum E {
  V0, // discriminant: 0
  V2(!), // 2
}

fn main() {
    assert_eq!(std::mem::size_of::<E>(), 4);

    let val = 2u32;
    let ptr = (&raw const val).cast::<E>();
    let r = unsafe { &*ptr };
    let f = || {
        // After rust-lang/rust#138961, constructing the closure performs a reborrow of r.
        // Nevertheless, the discriminant is only actually inspected when the closure
        // is called.
        match r { //~ ERROR: read discriminant of an uninhabited enum variant
            E::V0 => {}
            E::V2(_) => {}
        }
    };

    f();
}
```

### LINKED ISSUE #142394: `match` on uninhabited type does not trigger UB in Miri
I tried this code:

```rust
#![allow(deref_nullptr)]

enum Never {}

fn main() {
    unsafe {
        match *std::ptr::null::<Result<Never, Never>>() {
            Ok(_) => {
                lol();
            }
            Err(_) => {
                wut();
            }
        }
    }
}

fn lol() {
    println!("lol");
}

fn wut() {
    println!("wut");
}
```

I expected to see this happen: Running this with Miri detects undefined behavior.

Instead, this happened: Running this with Miri outputs "lol", and program exits successfully.

It seems like rustc is discarding the second match arm entirely in the MIR?

<details>
<summary>MIR</summary>

```
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
// HINT: See also -Z dump-mir for MIR at specific points during compilation.
fn main() -> () {
    let mut _0: ();
    let mut _1: *const std::result::Result<Never, Never>;
    let _2: ();

    bb0: {
        _1 = null::<Result<Never, Never>>() -> [return: bb1, unwind continue];
    }

    bb1: {
        _2 = lol() -> [return: bb2, unwind continue];
    }

    bb2: {
        return;
    }
}

// MIR for lol() and wut() omitted for brevity
```

</details>

### Meta

Reproducible on the playground with `1.89.0-nightly (2025-06-10 1677d46cb128cc8f285d)`

@rustbot labels +A-patterns

### LINKED ISSUE #146590: Uninhabited types have strange borrow-checking behavior, even behind references
I'm not sure if this is a bug or not.

```rust
enum Never {}

fn works(x: &mut Result<Never, String>) {
    match x {
        &mut Ok(ref mut y) => match x {
            &mut Err(ref mut z) => {
                let _y = y;
                let _z = z;
            }
            _ => {}
        },
        _ => {}
    };
}

fn fails(x: &mut Result<String, String>) {
    match x {
        &mut Ok(ref mut y) => match x {
            &mut Err(ref mut z) => {
                let _y = y;
                let _z = z;
            }
            _ => {}
        },
        _ => {}
    };
}
```

I expected either both functions to compile or both functions to fail to compile. Instead, only the `fails` function gives the following error:

```
error[E0503]: cannot use `*x` because it was mutably borrowed
  --> src/lib.rs:18:37
   |
18 |         &mut Ok(ref mut y) => match x {
   |                 ---------           ^ use of borrowed `x.0`
   |                 |
   |                 `x.0` is borrowed here
19 |             &mut Err(ref mut z) => {
20 |                 let _y = y;
   |                          - borrow later used here

For more information about this error, try `rustc --explain E0503`.
```

In my understanding, whether `&mut Never` is uninhabited is undecided. Therefore, since I'm only creating references to `Never` (as opposed to actually creating `Never` values) I would think that I wouldn't get any special casing for uninhabited types. Thus, the current behavior seems wrong to me.

### Meta

Reproducible on the playground with version `1.92.0-nightly (2025-09-14 52618eb338609df44978)`

### LINKED ISSUE #146803: Adding generics affect whether code has UB or not, according to Miri
I tried this code:

```rust
enum Never {}

#[repr(u64, C)]
#[allow(dead_code)]
enum Thing<T> {
    Never(T) = 0,
    Inhabited = 1,
}

fn main() {
    assert_eq!(size_of::<Thing<Never>>(), 8);
    let data = 0u64;
    // Discriminant is 0, so we should have Thing::Never
    let thing_ref = unsafe { &*(&raw const data).cast::<Thing<Never>>() };
    // This is fine
    concrete(thing_ref);
    // This has UB
    generic::<Never>(thing_ref);
}

fn concrete(x: &Thing<Never>) {
    match x {
        &Thing::Inhabited => {
            println!("Inhabited");
        }
        _ => {
            println!("Never");
        }
    };
}

fn generic<T>(x: &Thing<T>) {
    match x {
        &Thing::Inhabited => {
            println!("Inhabited");
        }
        _ => {
            println!("Never");
        }
    };
}
```

I expected the `concrete` and `generic::<1>` calls to behave identically. Instead, Miri detects UB only for the `generic::<1>` call:

```
error: Undefined Behavior: read discriminant of an uninhabited enum variant
  --> src/main.rs:33:11
   |
33 |     match x {
   |           ^ Undefined Behavior occurred here
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `generic::<Never>` at src/main.rs:33:11: 33:12
note: inside `main`
  --> src/main.rs:18:5
   |
18 |     generic::<Never>(thing_ref);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```

It seems that, in `generic`, `T` is treated as inhabited, even if the `T` is later set to `Never` (which makes the type uninhabited in `concrete`). Whether the `Thing::Never` variant is inhabited then affects whether the enum discriminant is checked in the MIR.

Note that, when I tried executing the program (in either debug mode or release mode), it printed `Inhabited`, then printed `Never`. That is, the difference between the two functions can actually be observed outside of Miri.

Probably related to #142394 and #146590, which involves uninhabited types affecting MIR generation.

See also #146430, where generics can affect MIR-building.

### Meta

Reproducible on the playground with rust version `1.92.0-nightly (2025-09-19 0be8e16088894483a701)` and Miri version `0.1.0 (2025-09-19 0be8e16088)`

### PR DESCRIPTION
**Pull request by meithecatte**
The question of "when does matching an enum against a pattern of one of its variants read its discriminant" is currently an underspecified part of the language, causing weird behavior around borrowck, drop order, and UB.

Of course, in the common cases, the discriminant must be read to distinguish the variant of the enum, but currently the following exceptions are implemented:

1. If the enum has only one variant, we currently skip the discriminant read.
     - This has the advantage that single-variant enums behave the same way as structs in this regard.
     - However, it means that if the discriminant exists in the layout, we can't say that this discriminant being invalid is UB. This makes me particularly uneasy in its interactions with niches – consider the following example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=5904a6155cbdd39af4a2e7b1d32a9b1a)), where miri currently doesn't detect any UB (because the semantics don't specify any):

        <details><summary>Example 1</summary>

        ```rust
        #![allow(dead_code)]
        use core::mem::{size_of, transmute};
        
        #[repr(u8)]
        enum Inner {
            X(u8),
        }
        
        enum Outer {
            A(Inner),
            B(u8),
        }
        
        fn f(x: &Inner) {
            match x {
                Inner::X(v) => {
                    println!("{v}");
                }
            }
        }
        
        fn main() {
            assert_eq!(size_of::<Inner>(), 2);
            assert_eq!(size_of::<Outer>(), 2);
            let x = Outer::B(42);
            let y = &x;
            f(unsafe { transmute(y) });
        }
        ```

      </details>

2. For the purpose of the above, enums with marked with `#[non_exhaustive]` are always considered to have multiple variants when observed from foreign crates, but the actual number of variants is considered in the current crate.
    - This means that whether code has UB can depend on which crate it is in: https://github.com/rust-lang/rust/issues/147722
    - In another case of `#[non_exhaustive]` affecting the runtime semantics, its presence or absence can change what gets captured by a closure, and by extension, the drop order: https://github.com/rust-lang/rust/issues/147722#issuecomment-3674554872
    - Also at the above link, there is an example where removing `#[non_exhaustive]` can cause borrowck to suddenly start failing in another crate.
3. Moreover, we currently make a more specific check: we only read the discriminant if there is more than one *inhabited* variant in the enum.
    - This means that the semantics can differ between `foo<!>`, and a copy of `foo` where `T` was manually replaced with `!`: rust-lang/rust#146803
    - Moreover, due to the privacy rules for inhabitedness, it means that the semantics of code can depend on the *module* in which it is located.
    - Additionally, this inhabitedness rule is even uglier due to the fact that closure capture analysis needs to happen before we can determine whether types are uninhabited, which means that whether the discriminant read happens has a different answer specifically for capture analysis.
    - For the two above points, see the following example ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=a07d8a3ec0b31953942e96e2130476d9)):

        <details><summary>Example 2</summary>

        ```rust
        #![allow(unused)]
        
        mod foo {
            enum Never {}
            struct PrivatelyUninhabited(Never);
            pub enum A {
                V(String, String),
                Y(PrivatelyUninhabited),
            }
            
            fn works(mut x: A) {
                let a = match x {
                    A::V(ref mut a, _) => a,
                    _ => unreachable!(),
                };
                
                let b = match x {
                    A::V(_, ref mut b) => b,
                    _ => unreachable!(),
                };
            
                a.len(); b.len();
            }
            
            fn fails(mut x: A) {
                let mut f = || match x {
                    A::V(ref mut a, _) => (),
                    _ => unreachable!(),
                };
                
                let mut g = || match x {
                    A::V(_, ref mut b) => (),
                    _ => unreachable!(),
                };
            
                f(); g();
            }
        }
        
        use foo::A;
        
        fn fails(mut x: A) {
            let a = match x {
                A::V(ref mut a, _) => a,
                _ => unreachable!(),
            };
            
            let b = match x {
                A::V(_, ref mut b) => b,
                _ => unreachable!(),
            };
        
            a.len(); b.len();
        }
        
        
        fn fails2(mut x: A) {
            let mut f = || match x {
                A::V(ref mut a, _) => (),
                _ => unreachable!(),
            };
            
            let mut g = || match x {
                A::V(_, ref mut b) => (),
                _ => unreachable!(),
            };
        
            f(); g();
        }
        ```

        </details>

In light of the above, and following the discussion at rust-lang/rust#138961 and rust-lang/rust#147722, this PR ~~makes it so that, operationally, matching on an enum *always* reads its discriminant.~~ introduces the following changes to this behavior:

 - matching on a `#[non_exhaustive]` enum will always introduce a discriminant read, regardless of whether the enum is from an external crate
 - uninhabited variants now count just like normal ones, and don't get skipped in the checks

As per the discussion below, the resolution for point (1) above is that it should land as part of a separate PR, so that the subtler decision can be more carefully considered.

Note that this is a breaking change, due to the aforementioned changes in borrow checking behavior, new UB (or at least UB newly detected by miri), as well as drop order around closure captures. However, it seems to me that the combination of this PR with rust-lang/rust#138961 should have smaller real-world impact than rust-lang/rust#138961 by itself.

Fixes rust-lang/rust#142394 
Fixes rust-lang/rust#146590
Fixes rust-lang/rust#146803 (though already marked as duplicate)
Fixes parts of rust-lang/rust#147722
Fixes rust-lang/miri#4778

r? @Nadrieril @RalfJung 

@rustbot label +A-closures +A-patterns +T-opsem +T-lang

### CODE REVIEW

**Comment by RalfJung** [comment]
I'm also not really on the review rotation, so I won't be able to do the lead review here -- sorry. I'll try to take a look at the parts relevant to Miri, but the match lowering itself is outside my comfort zone.

@rustbot reroll

File: compiler/rustc_mir_build/src/builder/matches/match_pair.rs [hunk 1]
```diff
@@ -308,22 +308,14 @@ impl<'tcx> MatchPairTree<'tcx> {
                 }
             }
 
-            PatKind::Variant { adt_def, variant_index, args, ref subpatterns } => {
+            PatKind::Variant { adt_def, variant_index, ref subpatterns, .. } => {
```
Comment (Zalathar) [inline compiler/rustc_mir_build/src/builder/matches/match_pair.rs]: Nit: Please use `args: _` instead of `..` so that the fields are still matched exhaustively.

Comment (meithecatte) [reply compiler/rustc_mir_build/src/builder/matches/match_pair.rs]: Makes sense! FWIW I only wrote that because I found three preexisting instances of `..` in the very same `match`, but I suppose it might be that in those cases the amount of fields getting ignored is more unwieldy.

Regardless, suggestion applied.

Comment (Zalathar) [reply compiler/rustc_mir_build/src/builder/matches/match_pair.rs]: Also please squash the “fixup” commits into their base commits, as it's a hassle for later investigation if the fixups end up getting merged into real history.

Comment (meithecatte) [reply compiler/rustc_mir_build/src/builder/matches/match_pair.rs]: Oh, definitely. Do you include fiddling with the tests in that? At least one of them would probably benefit from being separate for review, purely to make it more noticeable (the `codegen-llvm` one is the one I have in mind, but the changes to the FileCheck directives could probably also use a once-over...)

Comment (Zalathar) [reply compiler/rustc_mir_build/src/builder/matches/match_pair.rs]: I'm mainly thinking of squashing the non-test fixups.

Test changes are more of a judgement call. 🤷‍♂️

File: src/tools/miri/tests/fail/match/only_inhabited_variant.rs
Comment (RalfJung) [inline src/tools/miri/tests/fail/match/only_inhabited_variant.rs:1]: The "validity" folder is about validity invariants, which is not what these tests are about.

I'd say let's make a new folder "match" for these tests. And probably the "closures" tests should all go there since really they are about pattern matching on closure captures.

**Review by Nadrieril — APPROVED** [review]
Quite in favor of this change, I've been wanting to fix this for a long time. PR looks good to me.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150681/451b7b6c775a2378fd18d2560bbfb31c3695d1cc..2ef0ade1b3d59112154f6ba2629dc7fd6bac8e6e)*

**Comment by traviscross** [comment]
We talked about this in the lang call today.

For my part, to move this along, I'm interested in separating this into two:

1. Removing the same-crate/different-crate distinction on non-exhaustive enums: matching on a non-exhaustive enum should always do a discriminant read.
2. Doing a discriminant read when matching on an exhaustive enum with one non-empty variant.

The worst flaw of the current behavior is that the opsem is crate dependent.  Doing the first thing fixes that.  And it makes sense conceptually.  Marking an enum as non-exhaustive should cause the enum to act *as if* there may be other variants.  There's no good reason this *as if* rule shouldn't apply to the defining crate too.

The second one, for me, is less of a clear call.  If an enum is exhaustive, then its structure has been committed to (even if not exported, this amounts to an internal commitment, for the moment, within the crate).  There's a reasonableness to the programmer and the compiler relying on the details of this structure.  And relying on this structure allows for more code that morally should compile to compile due to how this affects borrow checker behavior.

This does then unfortunately mean that removing `#[non_exhaustive]` from a public enum is a breaking change.  That indeed could be a bit surprising, but we have a number of surprising SemVer hazards.  Maybe what we buy in trade for this is worth it.

In any case, I'd like to break these questions apart so we can consider them separately.

**Comment by RalfJung** [comment]
> The second one, for me, is less of a clear call. If an enum is exhaustive, then its structure has been committed to (even if not exported, this amounts to an internal commitment, for the moment, within the crate). There's a reasonableness to the programmer and the compiler relying on the details of this structure. And relying on this structure allows for more code that morally should compile to compile due to how this affects borrow checker behavior.

I don't see a good motivation for having such a special case for single-variant enums. People can just convert the enum to a struct if that's the behavior they want. Having fewer special cases is generally a good thing IMO. :)

Note that the current code also exempts 0-variant enums in a similar way, though I am not entirely sure what the consequences of that are.

**Comment by RalfJung** [comment]
Oh, and furthermore the logic in `compiler/rustc_mir_build/src/builder/matches/match_pair.rs` that this PR changes currently causes us to violate the substitution principle: in generic code, a discriminant read will be omitted, but when the types become concrete and an enum variant turns out to he uninhabited, then there is no longer a discriminant read.

**Comment by meithecatte** [comment]
Yup, as well as some github-only projects. All of the failures are for matching on a single-variant enum without any fields, that typically seems to not implement `Copy` simply because the need hasn't arisen yet.

One particularly interesting case is one where the match is being done on a value that has already been moved. Minimized:

```rust
enum NonCopy {
    Meow,
}

fn f(x: NonCopy) {
    drop(x);
    match x {
        NonCopy::Meow => (),
    }
}
```

**Comment by traviscross** [comment]
Thanks for the elaboration in the PR description.  That's helpful.

> 3\. Moreover, we currently make a more specific check: we only read the discriminant if there is more than one _inhabited_ variant in the enum

This conflicts with what we documented in the Reference for https://github.com/rust-lang/rust/pull/138961 in https://github.com/rust-lang/reference/pull/1837.  In [type.closure.capture.precision.discriminants.uninhabited-variants](https://doc.rust-lang.org/nightly/reference/types/closure.html#r-type.closure.capture.precision.discriminants.uninhabited-variants), we say:

> r[type.closure.capture.precision.discriminants.uninhabited-variants]
> Even if all variants but the one being matched against are uninhabited, making the pattern [irrefutable][patterns.refutable], the discriminant is still read if it otherwise would be.

As you point out, this is treated as true for closure capture analysis, but as documented, we said something stronger than that.

For my part, I think we should indeed make that true.

I'd still like to separate out your item number 1 (one-variant rule) from numbers 2 (local non-exhaustive exception) and 3 (one-inhabited-variant partial exception).  Basically, I think it's really clear that we should do 2 and 3, and I want to move those forward.  I'd propose FCP merge immediately on this PR restricted to 2 and 3.

For item number 1, I'd prefer to see that as a separate proposal with a self-standing motivation after 2 and 3 are fixed.  Otherwise, it's too easy for the closer-call item to skate by on the compelling motivation of the easier calls.  In my own head, evaluating this issue, I'm feeling the pull of that bleed-over myself.  Maybe in the end it will turn out to be the right thing to do, but I see stronger reasons to be skeptical of that one, and so I'd prefer to consider it as a second step.

As I understand the crater results, separating it in this way would also have the virtue of avoiding, for the moment, the observed breakage.

**Comment by RalfJung** [comment]
> It seems to me that the behavior here is specifically for "what happens if we match an enum against one of its variants", and therefore it simply cannot affect 0-variant enums.

Hm... we should however still emit some sort of code for the implicit `!` pattern when matching on 0-variant enums. But that's a separate discussion.

> One particularly interesting case is one where the match is being done on a value that has already been moved. Minimized:

Wow, a fun example. Seems unlikely we ever actually intended that to be accepted.^^

So I feel fairly strongly that we want to do step 1 as well. But it doesn't all have to be in the same PR of course.

**Comment by scottmcm** [comment]
@rfcbot reviewed 

---

In particular, I'm a fan of `non_exhaustive` being about *semver* not *opsem*.  That makes a ton of sense to me -- it affects whether things compile, but not what things *do*.

---

I do like like CAD's note in https://github.com/rust-lang/rust/pull/150681#issuecomment-3756715296 -- it looks like
```rust
#[repr(u32)]
enum Foo {
    Bar,
}
```
is still [`Variants::Multiple`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_abi/enum.Variants.html#variant.Multiple), so a follow-up to only elide the read for `Variants::Single` might be reasonable, but that's something we can think about in another discussion.  (Among other things, that's a layout question so isn't necessarily available at MIR building time, so might not be the right rule at all.)

**Comment by theemathas** [comment]
@scottmcm I believe that the current iteration of the PR has #[non_exhaustive] also affect opsem. It just affects both external crates and the same crate equally.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I would personally do 1, 2, and 3, but I am in favor of 2 and 3 on their own as well.

**Comment by traviscross** [comment]
@JakobDegen @saethlin @digama0: Heads-up that you have the remaining unchecked boxes on this proposed FCP [here](https://github.com/rust-lang/rust/pull/150681#issuecomment-3756511490).

**Comment by meithecatte** [comment]
The way #138961 comes up as a breaking change in practice is when it causes closure captures to be more granular, and as a result some values get borrowed when previously they would get moved together with the enum they were contained in. The change this forces to the user's code is typically very simple, see e.g. https://github.com/tryandromeda/andromeda/pull/43/changes

With the initial, full version of the current PR, we would again be capturing the entire enum in these cases, thus avoiding any similar instances of that breakage that happened to not get caught by crater.

However, the cut down version of this PR, which only affects enums containing uninhabited variants or marked non-exhaustive, this effect is less likely to occur (I can imagine the non-exhaustive case happening in real code, but it essentially limits it to when the code pattern in question happens to be matching on an enum that's part of the public API of the crate being compiled).

Either way, I think this is not worth backporting, because user code the previous PR broke should be really easy to fix, while this PR also has practical breakage of its own.

**Comment by traviscross** [comment]
> (I'll unsubcribe from this PR, when this is ready for T-compiler review, feel free to ping or reroll)

@JonathanBrouwer: The FCP is complete.  The Reference PR is ready.  This is good to go as far as lang is concerned.

**Comment by Kobzol** [comment]
A few small regressions across the board, mainly in `doc` builds, the rest of the profiles are a wash. Given the change made here, I suppose the perf. regression is expected.

@rustbot label: +perf-regression-triaged
