### PR TITLE
Remove invalid suggestion involving `Fn` trait bound

### LINKED ISSUE #85735: odd diagnostic with multiple where clauses that only differ by lifetimes
Given the following [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2a2d7d8fd6b612f63ff3738d11b7a2d9):

```rust
trait Foo {}
impl<'a, 'b, T> Foo for T
where
    T: FnMut(&'a ()),
    T: FnMut(&'b ()), {

    }
```

The current output is:

```
error[E0283]: type annotations needed
   --> src/lib.rs:4:8
    |
4   |       T: FnMut(&'a ()),
    |          ^^^^^^^^^^^^^ cannot infer type for type parameter `T`
    |
    = note: cannot satisfy `T: FnMut<(&'a (),)>`
help: consider specifying the type arguments in the function call
    |
4   |     T: FnMut(&'a ())::<Self, Args>,
    |                     ^^^^^^^^^^^^^^

error: aborting due to previous error
```

Ideally the output should look like:

/shrug I expected this to compile but at the very least it shouldn't suggest writing code that doesnt even parse lol

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request closes #85735. The actual issue is a duplicate of #21974, but #85735 contains a further problem, which is an invalid suggestion if `Fn`/`FnMut`/`FnOnce` trait bounds are involved: The suggestion code checks whether the trait bound ends with `>` to determine whether it has any generic arguments, but the `Fn*` traits have a special syntax for generic arguments that doesn't involve angle brackets. The example given in #85735:
```rust
trait Foo {}
impl<'a, 'b, T> Foo for T
where
    T: FnMut(&'a ()),
    T: FnMut(&'b ()), {

    }
```
currently produces:
```
error[E0283]: type annotations needed
   --> src/lib.rs:4:8
    |
4   |       T: FnMut(&'a ()),
    |          ^^^^^^^^^^^^^ cannot infer type for type parameter `T`
    |
    = note: cannot satisfy `T: FnMut<(&'a (),)>`
help: consider specifying the type arguments in the function call
    |
4   |     T: FnMut(&'a ())::<Self, Args>,
    |                     ^^^^^^^^^^^^^^

error: aborting due to previous error
```
which is incorrect, because there is no function call, and applying the suggestion would lead to a parse error. With my changes, I get:
```
error[E0283]: type annotations needed
   --> test.rs:4:8
    |
4   |     T: FnMut(&'a ()),
    |        ^^^^^^^^^^^^^ cannot infer type for type parameter `T`
    | 
   ::: [...]/library/core/src/ops/function.rs:147:1
    |
147 | pub trait FnMut<Args>: FnOnce<Args> {
    | ----------------------------------- required by this bound in `FnMut`
    |
    = note: cannot satisfy `T: FnMut<(&'a (),)>`

error: aborting due to previous error
```
i.e. I have added a check to prevent the invalid suggestion from being issued for `Fn*` bounds, while the underlying issue #21974 remains for now.

### CODE REVIEW

File: src/test/ui/traits/issue-85735.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// Regression test for the invalid suggestion in #85735 (the
+// underlying issue #21974 still exists here).
+
+#![crate_type="lib"]
```
Comment (LeSeulArtichaut) [inline src/test/ui/traits/issue-85735.rs:4]: Nit: I guess we usually just put an empty `fn main() {}` instead of changing the crate type, but I don't think it really matters

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -1561,6 +1561,12 @@ impl<'a, 'tcx> InferCtxtPrivExt<'tcx> for InferCtxt<'a, 'tcx> {
                     let generics = self.tcx.generics_of(*def_id);
                     if generics.params.iter().any(|p| p.name != kw::SelfUpper)
                         && !snippet.ends_with('>')
+                        && ![
+                            self.tcx.lang_items().fn_trait(),
+                            self.tcx.lang_items().fn_mut_trait(),
+                            self.tcx.lang_items().fn_once_trait(),
+                        ]
+                        .contains(&Some(*def_id))
```
Comment (LeSeulArtichaut) [inline compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1569]: I'm surprised there isn't a function for this. I guess there is
```suggestion
                        && self.tcx.fn_trait_kind_from_lang_item(*def_id).is_some()
```
which feels a little bit cleaner to me. But it looks like both are used in the compiler, and I don't have a strong opinion anyway.

**Review by LeSeulArtichaut — APPROVED** [review]
Looks good to me, but I don't feel too comfortable approving, so I'll delegate to @estebank. Left two potential nitpicks

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1569]: Changing it to use `fn_trait_kind_from_lang_item` feels appropriate.

**Review by estebank — APPROVED** [review]
r=me after addressing @LeSeulArtichaut's comments.

File: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs (hunk 2 above)
Comment (FabianWolff) [reply compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs]: Fixed. This is ready for review again @estebank!
