### PR TITLE
Avoid overflow in GVN constant indexing.

### LINKED ISSUE #118992: assertion failed: offset < min_length in GVN
```rust
fn main() {
    let slf = "f".as_bytes();
    let _n = slf[slf.len() - 2];
}
```
Compile with
```
-Zmir-opt-level=1 -Zmir-enable-passes=+GVN -Zinline-mir
```

### LINKED ISSUE #119008: Attempt to add with overflow in GVN when building chrono-tz
https://github.com/chronotope/chrono-tz on commit `97d1680189e61fbd66fcb1c52f6d51b55389919e`

```
RUSTFLAGS="-Zinline-mir -Zmir-opt-level=1 -Zmir-enable-passes=+GVN -Zcross-crate-inline-threshold=yes -Copt-level=1" cargo +master-stage1 build
```
Where `master-stage1` is a toolchain build with debug assertions.

```
   Compiling chrono-tz v0.8.4 (/home/ben/chrono-tz/chrono-tz)
thread 'rustc' panicked at compiler/rustc_mir_transform/src/gvn.rs:650:37:
attempt to add with overflow
stack backtrace:
```

[rustc-ice-2023-12-16T04_53_09-27142.txt](https://github.com/rust-lang/rust/files/13691407/rustc-ice-2023-12-16T04_53_09-27142.txt)

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/118992
Fixes https://github.com/rust-lang/rust/issues/119008

### CODE REVIEW

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 1]
```diff
@@ -644,12 +644,10 @@ impl<'body, 'tcx> VnState<'body, 'tcx> {
...
                     && let Ok(offset) = self.ecx.read_target_usize(offset)
+                    && let Some(min_length) = offset.checked_add(1)
                 {
-                    projection.to_mut()[i] = ProjectionElem::ConstantIndex {
-                        offset,
-                        min_length: offset + 1,
-                        from_end: false,
-                    };
+                    projection.to_mut()[i] =
+                        ProjectionElem::ConstantIndex { offset, min_length, from_end: false };
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/gvn.rs:650]: Do you know why `ConstantIndex` stores `min_length` instead of, e.g., the "max index" of the last value?

Comment (compiler-errors) [reply compiler/rustc_mir_transform/src/gvn.rs:650]: Well I guess it doesn't make sense to index at `usize::MAX` anyways.

**Review by compiler-errors — APPROVED** [review]

File: compiler/rustc_mir_transform/src/gvn.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_mir_transform/src/gvn.rs:650]: `min_length` comes from slice match. I supposed it's easier to compute from the length of the pattern.
