### PR TITLE
Unescaped command-line arguments for Windows

### LINKED ISSUE #29494: Command does not escape arguments as expected on windows
Currently the windows implementation of Command will automatically attempt to escape arguments before concatenating them into a single command line string to be passed to CreateProcess. However, the escaping method used doesn't work for many windows command-line tools, including `cmd`, `msiexec` and others.

As an example, it is impossible to specify arguments like this:
`ARG="some parameter with spaces"`
because Command will try to quote the entire thing, whereas msiexec expects only the value to be quoted.

What's required is a way to pass arguments through unchanged: I suggest an `arg_raw` or `arg_unescaped` method be added to Command. This function can either be a windows-specific extension, or a no-op on other platforms. The advantage of the latter is that it avoids the need to `cfg` out code that relies on it at compile time.

### PR DESCRIPTION
**Pull request by kornelski**
Some Windows commands, expecially `cmd.exe /c`, have unusual quoting requirements which are incompatible with default rules assumed for `.arg()`.

This adds `.unquoted_arg()` to `Command` via Windows `CommandExt` trait.

Fixes #29494

### CODE REVIEW

**Comment by kornelski** [comment]
There's an existing unstable feature `force_quotes()` that is the opposite of this feature — used to quote args that have `*` which aren't quoted by default in `.arg()`. 

I went for `.unquoted_arg()` approach, because it's more flexible. A single `.unquoted_arg()` can be used to build an arbitrary command-line, but also can be mixed with regular `.arg()`, so that users who need only some arguments with special syntax don't have to reinvent their own quoting implementation for the rest (the escaping rules for Windows are very weird, so it's better not to have to do it).

I think `.force_quotes(true)` could be replaced by `.quoted_arg(val)` to have both features with consistent interface, but I'm leaving it out of scope of this PR.

**Comment by dgrunwald** [comment]
I haven't tried this branch; but if I read the diff correctly, `unquoted_arg` will still perform escaping?
`Quote::Never` doesn't add quotes around the argument, but it still escapes those within the argument.

You don't have any test cases where escaping would trigger (only when the argument contains `"`).

**Comment by dgrunwald** [comment]
Also, isn't there a bug where `Quote::Auto` ends up discarding trailing backslashes from the argument if the argument doesn't contain any whitespace?

**Comment by kornelski** [comment]
There is a test verifying that there's no escaping applied to the unquoted args:

https://github.com/rust-lang/rust/pull/85832/files#diff-a426d649b902b742a112ec5836a040041fc4ba3dd4abc9a3927a901df46f2e36R12

**Comment by kornelski** [comment]
I've disabled inner escaping for unquoted arg.

I haven't changed escaping logic. I think it's fine — the rules of CommandLineToArgvW that it uses are just very counter-intuitive.

**Comment by dgrunwald** [comment]
Try a test case with `Arg::Quoted(OsString::from("c:\\")),` (without force_quotes).
I think it'll end up passing `c:` without the trailing backslash to the target program. That's because `backslashes` is non-zero at the end, but gets ignored when the `if quote` is not taken.

**Comment by yaahc** [comment]
Why'd you go with calling it `quoted_arg` instead of `raw_arg` as suggested in the source issue?

**Comment by kornelski** [comment]
That's because I've noticed that there's `force_quotes`, and wanted to use a similar teminology. However, you're right that this makes escaping ambiguous. I've changed back to `raw_arg`

File: library/std/src/sys/windows/process.rs [hunk 1]
```diff
@@ -97,6 +97,14 @@ pub struct StdioPipes {
     pub stderr: Option<AnonPipe>,
 }
 
+#[derive(Debug)]
+enum Arg {
+    /// Add quotes (if needed)
+    Regular(OsString),
```
Comment (rivy) [inline library/std/src/sys/windows/process.rs:103]:
```suggestion
    AutoQuote(OsString),
```

maybe? It adds semantic meaning.

**Comment by yaahc** [comment]
> Try a test case with `Arg::Quoted(OsString::from("c:\\")),` (without force_quotes).
> I think it'll end up passing `c:` without the trailing backslash to the target program. That's because `backslashes` is non-zero at the end, but gets ignored when the `if quote` is not taken.

@kornelski have you tried the test case suggested by @dgrunwald, I'm curious to know if this is an issue.

File: library/std/src/os/windows/process.rs [hunk 2]
```diff
@@ -125,6 +126,13 @@ pub trait CommandExt: Sealed {
     /// [2]: <https://msdn.microsoft.com/en-us/library/17w5ykft.aspx>
     #[unstable(feature = "windows_process_extensions_force_quotes", issue = "82227")]
     fn force_quotes(&mut self, enabled: bool) -> &mut process::Command;
+
+    /// Append literal text to the command line without any quoting or escaping.
+    ///
+    /// This is useful for passing arguments to `cmd.exe /c`, which doesn't follow
+    /// `CommandLineToArgvW` escaping rules.
+    #[unstable(feature = "windows_process_extensions_raw_arg", issue = "29494")]
+    fn raw_arg(&mut self, text_to_append_as_is: &OsStr) -> &mut process::Command;
```
Comment (ChrisDenton) [inline library/std/src/os/windows/process.rs:135]: The signature of [`Command::arg`](https://doc.rust-lang.org/std/process/struct.Command.html#method.arg) uses the generic `AsRef<OsStr>` for the type. This should probably match that?

Comment (kornelski) [reply library/std/src/os/windows/process.rs]: I've added it. I'm not sure if `CommandExt` was supposed to be object-safe tho.

File: library/std/src/sys/windows/process.rs (hunk 1 above)
Comment (kornelski) [reply library/std/src/sys/windows/process.rs:167]: I think it's fine as-is. It's for the regular `arg`, not `arg_auto` or such.

**Comment by kornelski** [comment]
@yaahc I've added tests cases for the issue raised. They're fine, because escaping rules on Windows don't double the number of backslashes, only number of backslashes before a quote (the syntax is illogical like that by design).

**Comment by ChrisDenton** [comment]
To recap, a backslash is treated literally unless they are directly followed by a double quote. When a double quote is encountered the rules are:
* Any directly preceding backslashes are counted (represented here by `n`).
    * If `n` is even then replace with `n/2` backslashes and toggle "quote mode".
    * If `n` is odd then replace with `(n-1)/2` backslashes and add a literal `"`.

For example, the string `C:\Program Files\Rust` can be encoded in an argument in several ways:

`"C:\Program Files\Rust"`
`C:\"Program Files"\Rust`
`C:\"Program Files\\"Rust`

These rules are based on the old 80's DOS shell and can't be changed too much due to backwards compatibility. However, some applications do use their own rules, hence the need for `raw_arg`.

**Comment by dgrunwald** [comment]
I misread the code; I missed that the first copy of the `\` is already inserted by the loop.
So the code works fine, but thanks for adding the test.

Yeah the rules are weird. Fun fact: the interpretation of double double-quotes `""` is another (undocumented) special case where the behavior changed in the 2008 update of the Microsoft C runtime. But that doesn't matter for us as we never emit those. This site has the full story: http://daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULES

**Comment by yaahc** [comment]
Sounds like everyone is happy with the PR in it's current state ^_^

@bors r+

**Comment by ChrisDenton** [comment]
Is that just homu acting up?

**Comment by kornelski** [comment]
@yaahc bors needs a retry

**Comment by kornelski** [comment]
I think mingw uses debug output in tests? I've changed debug output to look exactly like before, and rebased.  

I can't test mingw, because I don't know how to make x.py use it instead of msvc.

**Comment by yaahc** [comment]
I'm not really familiar with windows at all so I can't really help with the mingw/msvc setup. For now though I can delegate bors permissions so you can restart the build as needed

@bors delegate+
@bors r+

**Comment by Xaeroxe** [comment]
What's the path for stabilizing this feature? The unstable attribute for it doesn't point at a tracking issue.

**Comment by kornelski** [comment]
@Xaeroxe There haven't been any objections to this feature, so I think you could make a tracking issue and make a PR to stabilize this feature.

**Comment by Xaeroxe** [comment]
Tracking issue: https://github.com/rust-lang/rust/issues/92939
