### PR TITLE
Suggest underscore when using dashes in crate name

### LINKED ISSUE #48437: Better error for `extern crate accidental-hyphen`
AIUI currently the standard is for crate names to be hyphenated, but the module name (not sure on the correct terminology) must be underscored.

For example you add `bit-vec` to the `Cargo.toml`, but `extern crate bit_vec;` to `src/lib.rs`.

image

```bash
cargo new rust-foo && cd rust-foo
cargo add bit_vec
sed -i '1s/^/extern crate bit-vec;\n/' src/lib.rs
cat src/lib.rs
cargo build
sed -i 's/bit-vec/bit_vec/' src/lib.rs
cargo build
```

So instead of this error, it would be great if the compiler could suggest `extern crate bit_vec;`.

```rust
cargo build                                                                                                                                                                       ~/tmp/rust-foo (!✦)
   Compiling foo v0.1.0 (file:///Users/gib/tmp/rust-foo)
error: expected one of `;` or `as`, found `-`
 --> src/lib.rs:1:17
  |
1 | extern crate bit-vec;
  |                 ^ expected one of `;` or `as` here

error: aborting due to previous error

error: Could not compile `foo`.

To learn more, run the command again with --verbose.
```

Came from a discussion with @nrc on twitter: https://twitter.com/gibfahn/status/966755092383739904

I couldn't find an existing issue for this, sorry if it's a duplicate.

### PR DESCRIPTION
**Pull request by estebank**
Fix #48437.

### CODE REVIEW

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -6519,11 +6553,15 @@ impl<'a> Parser<'a> {
                                visibility: Visibility,
                                attrs: Vec<Attribute>)
                                -> PResult<'a, P<Item>> {
-        let orig_name = self.parse_ident()?;
+        // Accept `extern crate name-like-this` for better diagnostics
+        let ident = self.parse_crate_name_with_dashes(
+            "crate name using dashes are not valid in `extern crate` statements",
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: typo: name -> names

Nit 1: could you keep `orig_name` instead of `ident`, this is a point of confusion because the meaning of optional identifier in `ItemKind::ExternCrate` is a bit counter-intuitive.

Nit 2: The messages can be moved into `parse_crate_name_with_dashes`.

**Comment by petrochenkov** [comment]
r=me with comment addressed
