### PR TITLE
BTreeMap: fix pointer provenance rules

### LINKED ISSUE #78477: BTree's `insert_fit` breaks pointer provenance rules
This code violates pointer provenance rules:
```rust
    fn insert_fit(&mut self, key: K, val: V) -> *mut V {
        debug_assert!(self.node.len() < CAPACITY);

        unsafe {
            slice_insert(self.node.keys_mut(), self.idx, key);
            slice_insert(self.node.vals_mut(), self.idx, val);
            self.node.as_leaf_mut().len += 1;

            self.node.val_mut_at(self.idx)
        }
    }
```
Specifically, `self.node.keys_mut()` returns a slice covering the previously existing elements of this node, but it is used to also access the new element one-past-the-end of the previous slice.

Either `slice_insert` needs to be passed a slice covering all the memory it needs to access (of type `&mut [MaybeUninit<_>]`), or else it needs to be passed a raw pointer (that may access the entire buffer) and a length. But `keys_mut`/`vals_mut` can only be used to access elements that already exist, not to initialize new elements.

Cc @ssomers

### PR DESCRIPTION
**Pull request by ssomers**
Fixes #78477 and includes #78476

r? @Mark-Simulacrum

### CODE REVIEW

File: library/alloc/src/collections/btree/node.rs [hunk 1]
```diff
@@ -613,11 +613,11 @@ impl<'a, K: 'a, V: 'a> NodeRef<marker::Mut<'a>, K, V, marker::Leaf> {
     fn push_front(&mut self, key: K, val: V) {
         assert!(self.len() < CAPACITY);
 
+        self.as_leaf_mut().len += 1;
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:616]: I considered this solution, but... it's not great. Specifically, this means `self.keys_mut()` now returns a slice to memory that is not initialized. This is UB right now (even though I am in favor of not making this UB).

How bad would it be if `keys_mut`/`vals_mut` returned raw pointer slices instead of references? Or at least, if there also was a raw-pointer version for the insert case? (The reference version is still fine for all the other cases I think.)

File: library/alloc/src/collections/btree/node.rs [hunk 2]
```diff
@@ -1610,7 +1609,7 @@ unsafe fn slice_insert<T>(slice: &mut [T], idx: usize, val: T) {
     unsafe {
         let len = slice.len();
         let slice_ptr = slice.as_mut_ptr();
-        ptr::copy(slice_ptr.add(idx), slice_ptr.add(idx + 1), len - idx);
+        ptr::copy(slice_ptr.add(idx), slice_ptr.add(idx + 1), len - idx - 1);
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:1612]: Maybe add a comment explaining that this is the *new* `len` and hence we have to subtract one more.

File: library/alloc/src/collections/btree/node.rs (hunk 1 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:616]: > memory that is not initialized

Great, so MaybeUninit memory has to be initialized, `MaybeUninit::uninit_array` is not ehough to do that? You excel pulling the rug from under all my beliefs!

> How bad would it be

Well, I sure have no idea. I can (hopefully) write, compile and test it, but I don't even know how to run Miri at the moment, and I thought the [CI failing](https://github.com/rust-lang/miri) status meant I wasn't supposed to know.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:616]: > Great, so MaybeUninit memory has to be initialized, MaybeUninit::uninit_array is not enough to do that? You excel at pulling the rug from under all my beliefs!

The type of the involved function is
```rust
    fn keys_mut(&mut self) -> &mut [K]
```
So, there is no `MaybeUninit` here. Memory in a `MaybeUninit` indeed does not have to be initialized, but this one is not in a `MaybeUninit` (as far as the return type is concerned).

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:616]: Miri's CI will pass again once https://github.com/rust-lang/rust/pull/78446 lands. But you can always use the Miri from rustup; see https://rust-lang.github.io/rustup-components-history/ to find a nightly that comes with a working Miri.

However, to test if this fixes https://github.com/rust-lang/rust/issues/78477, https://github.com/rust-lang/miri/pull/1603 will have to land first (or you'll have to build Miri from that branch yourself).

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:616]: > So, there is no `MaybeUninit` here.

Right, I understand. I guess inserting into a slice of genuine values is a bad idea, because there is no way for them to know how to expand their footprint.

I do use Miri from rustup, but sometimes and right now it doesn't swallow the code in the Rust master branch. Until a day or two later, rustup finds an update and all is right again. I managed to build Miri in the past, but never figured out how to apply that in a x.py build.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:616]: > Right, I understand. I guess inserting into a slice of genuine values is a bad idea, because there is no way for a slice to know how to expand its footprint.

Exactly. However, making those functions return a slice of `MaybeUninit` is probably the best solution (assuming this is not too hard on other callers). Then the slice no longer claims to be fully initialized. (However this means the function needs to be made `unsafe` as it relies on the caller not doing weird stuff like putting a `MaybeUninit::uninit` into one of the existing slice elements.)

> I do use Miri from rustup, but sometimes and right now it doesn't swallow the code in the Rust master branch. Until a day or two later, rustup finds an update and all is right again. I managed to build Miri in the past, but never figured out how to apply that in a x.py build.

Since you just need the standard library from an x.py build, something like this should work:
* Clone [this branch](https://github.com/RalfJung/miri/tree/track-raw)
* check rust-version file, and use that commit as your basis for the rustc PR
* in Miri, `XARGO_RUST_SRC=/path/to/rustc/library ./miri run tests/run-pass/btreemap.rs -Zmiri-track-raw-pointers`

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:628]: I get past this upheaval when establishing the slice using a safe `&mut keys[..len]`. But not using `slice::from_raw_parts_mut(keys.get_unchecked_mut(0), len)`. -Zmiri-track-pointer-tag says:

```
527 |             slice::from_raw_parts_mut(self.as_leaf_mut().vals.get_unchecked_mut(0), self.len())
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ created tag 14820
```

As if Miri ignores the slice function and the resulting `&mut [MaybeUninit<K>]` and clings onto the first &mut it saw at that address.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:628]: Because Miri says that's the parent tag that does not have an appropriate item in the borrow stack.

This is the original error I get, using 17cc9b6256c95c31944591aec683884fead4e3b6: "Undefined Behavior: trying to reborrow for Unique at alloc1903+0x20, but parent tag <5115> does not have an appropriate item in the borrow stack". That stays the same for the code I parked here, with that `slice::from_raw_parts_mut(keys.get_unchecked_mut(0), len)`, except that the tag lowers to 5083.

Defining `keys_mut` as `&mut keys[..len]` (just for keys, not values and edges), that problem disappears, but obviously the same error occurs for values, with tag 14820.

It also disappears when defining `keys_mut` as:
```
let data = &mut self.as_leaf_mut().keys as *mut _ as *mut MaybeUninit<K>;
unsafe { slice::from_raw_parts_mut(data, self.len()) }
```

Though that's not the end of this: when I do the same for values and edges, there's another problem elsewhere.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:628]: > Because Miri says that's the parent tag that does not have an appropriate item in the borrow stack.

But where does that error occur?

`self.as_leaf_mut().vals.get_unchecked_mut(0)` doesn't make much sense -- this is a reference *to the first element*, it must not be used to access later elements.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:628]: To get a pointer that is usable for the entire slice, to `self.as_leaf_mut().as_mut_ptr().add(idx)`. (Something like `get_unchecked_mut(..len)` might also work.)

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:628]: > But where does that error occur?

Oh right, sorry, that was indeed in the same statement, and not way later in the `slice_insert` function.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:620]: > Something like `get_unchecked_mut(0..len)`

indeed works too.

File: library/alloc/src/collections/btree/node.rs [hunk 3]
```diff
@@ -342,28 +342,36 @@ impl<BorrowType, K, V, Type> NodeRef<BorrowType, K, V, Type> {
     /// # Safety
     /// The node has more than `idx` initialized elements.
     pub unsafe fn key_at(&self, idx: usize) -> &K {
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:344]: This function is not even used any more in this file... is it even worth keeping (as opposed to expecting the caller to handle `MaybeUninit`?

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:344]: Well it's there for `search_linear`?

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:344]: At first I found it weird to have a function returning a reference to something that you can only use assuming it's initialized. But it's there because I didn't know how else to copy/write a slice into uninitialized elements. And it's somewhat nice to have functions that only do one thing.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:344]: > Well it's there for search_linear? in search.rs

If that's the only user, it can just to `assume_init_ref` itself though?

> At first I found it weird to have a function returning a reference to something that you can only use assuming it's initialized. But it's there because I didn't know how else to copy/write a slice into uninitialized elements. And it's somewhat nice to have functions that only do one thing.

Well, I do not understand this code enough to suggest other APIs here, or to tell how many of these callers call this function on uninit elements.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:344]: Actually, it doesn't seem useful to change `key_at` after all. To copy a slice from one node to another, miri-track-raw-pointers wants the source pointer to point something it can read entirely, not just the first element. Which is sensible and easy to do, but it leaves `key_at` only useful to read a key.

The next problem, to which I don't see a way out at the moment, is `as_internal_mut()`:

```
302 |         unsafe { &mut *(self.node.as_ptr() as *mut InternalNode<K, V>) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for Unique at alloc22839+0x140, but parent tag <58889> does not have an appropriate item in the borrow stack
    |
```

We disguise a `*mut InternalNode` as a `*mut LeafNode` to squeeze it into `BoxedNode`, and there's no way around that. Now how do we unpack such a party pooper and convince Miri that this is an InternalNode?

-Zmiri-track-pointer-tag tracks the tag to the creator, `BoxedNode::from_internal`:
```
BoxedNode { ptr: Unique::from(&mut Box::leak(node).data) }
```

It does not help to make the reference raw:
```
`BoxedNode { ptr: unsafe { Unique::new_unchecked(&raw mut Box::leak(node).data) } }
```

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:347]: > Actually, it doesn't seem useful to change key_at after all. To copy a slice from one node to another, miri-track-raw-pointers wants the source pointer to point something it can read entirely, not just the first element. Which is sensible and easy to do, but it leaves key_at only useful to read a key.

Makes sense.

> We disguise a *mut InternalNode as a *mut LeafNode to squeeze it into BoxedNode, and there's no way around that. Now how do we unpack such a party pooper and convince Miri that this is an InternalNode?

Everything along the line needs to be raw pointers.

> -Zmiri-track-pointer-tag tracks the tag to the creator, BoxedNode::from_internal:

Does it make any difference if you cherry-pick https://github.com/rust-lang/rust/pull/78446? I think it should not, but the error points at the same place...

> -Zmiri-track-pointer-tag tracks the tag to the creator, BoxedNode::from_internal:

Could you show the full output with pointer tracking, i.e. all the tracking messages and the final error?

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:347]: > Everything along the line needs to be raw pointers.

It seems to work when casting in both directions. I thought I'd made things more clear by avoiding that cast, but clarity steered Miri up the wrong alley.

> Does it make any difference if you cherry-pick #78446?

I'm doing this on Miri's current rust-version, before the allocator upheaval, with your #78476 rebased. I don't understand how you seem to let Miri digest the latest std. Perhaps you just glance over the code in your head and project those issues, I wouldn't be surprised.

**Comment by ssomers** [comment]
[This particular test case](https://github.com/RalfJung/miri/blob/track-raw/tests/run-pass/btreemap.rs) now passes, and I cleaned up a bit. Now over to the standard test cases…

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: > I'm doing this on Miri's current rust-version, before the allocator upheaval, with your #78476 rebased.

Oh right, then that is no concern.

> I don't understand how you seem to let Miri digest the latest std.

At least for some of these investigations I ended up building Miri against a locally built rustc toolchain (as I was patching the core Miri engine to help debugging... it didn't end up helping though^^).

**Comment by RalfJung** [comment]
> This particular test case now passes, and I cleaned up a bit.

That's great! Maybe we should review and land this then? It clearly improves the situation.

> Now over to the standard test cases…

FWIW, I didn't even try to run any parts of the stdlib test suite with `-Zmiri-track-raw-pointers`, so you might run into plenty of problems that way.^^ If the error talks about "untagged" pointers, that is a false positive -- this means a int-ptr cast lost provenance, and in this mode Miri is not equipped to deal with that.

File: library/alloc/src/collections/btree/node.rs [hunk 4]
```diff
@@ -120,11 +119,11 @@ struct BoxedNode<K, V> {
 
 impl<K, V> BoxedNode<K, V> {
     fn from_leaf(node: Box<LeafNode<K, V>>) -> Self {
-        BoxedNode { ptr: Box::into_unique(node) }
+        BoxedNode { ptr: Unique::from(Box::leak(node)) }
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:122]: This should not be needed with the fixed `into_unique`.

File: library/alloc/src/collections/btree/node.rs [hunk 5]
```diff
@@ -473,72 +499,87 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
+    unsafe fn val_area_mut_at(&mut self, idx: usize) -> &mut MaybeUninit<V> {
+        unsafe { self.reborrow_mut().into_val_area_mut_at(idx) }
     }
 
-    fn keys_mut(&mut self) -> &mut [K]
+    /// Borrows a reference to a stretch of key storage area in the node.
+    ///
+    /// # Safety
+    /// - The node has more than `idx` initialized elements.
+    fn keys_mut(&mut self, start: usize) -> &mut [MaybeUninit<K>]
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:536]: This function is safe but has a safety comment?

Also, the function is actually not safe, as I can do awful things like
```rust
foo.keys_mut()[0] = MaybeUninit::uninit();
```

File: library/alloc/src/collections/btree/node.rs (hunk 4 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:122]: But the unstable note on `into_unique` says that's what we should use? The `.into()` also works in this case, but not for `from_internal`.

In any case, it clearly does not help to avoid the change to unique.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:536]: I fixed that already, wait a second...

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: > It seems to work when casting in both directions. I thought I'd made things more clear by avoiding that cast, but clarity steered Miri up the wrong alley.

What is the alternative to casting?

**Comment by ssomers** [comment]
I really don't know how to Miri the other test cases, other than writing each one as a standalone program (for those not peeking into internals). So I cleaned up some more.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: Is there any caller that does *not* use 0 for `start`? I don't entirely understand why you added that parameter.

File: library/alloc/src/collections/btree/node.rs (hunk 4 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:122]: > But the unstable note on into_unique says that's what we should use?

Oh, I didn't know that. Sure then.

**Comment by RalfJung** [comment]
> I really don't know how to Miri the other test cases,

I can write instructions for this, but it is probably easier to wait until the things that we currently have in the pipeline have landed.

File: library/alloc/src/collections/btree/node.rs [hunk 6]
```diff
@@ -280,26 +279,28 @@ unsafe impl<K: Send, V: Send, Type> Send for NodeRef<marker::Owned, K, V, Type>
...
 }
 
 impl<'a, K, V> NodeRef<marker::Mut<'a>, K, V, marker::Internal> {
-    /// Exposes the data of an internal node for reading,
-    /// when we know we have exclusive access.
-    fn as_internal(&mut self) -> &InternalNode<K, V> {
+    /// Exposes the data of an internal node for reading.
+    ///
+    /// # Safety
+    /// We have exclusive access to the node (and not just to the `NodeRef`).
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:292]: Isn't there supposed to be an invariant that a `NodeRef<marker::Mut` always has exclusive access to the node?

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: > Also, the function is actually not safe, as I can do awful things like

But that's basically what `slice_remove` does, and what MaybeUninit is for, so is that really unsafe? It's only unsafe when you later `assume_init` it, right?

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: The concern about the return type remains -- functions returning `&mut MaybeUninit` are rarely safe because they allow the caller to *de-initialize* the given memory.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: > But that's basically what slice_remove does, and what MaybeUninit is for, so is that really unsafe? It's only unsafe when you later assume_init it, right?

Doesn't de-initializing violate the invariant of the node? The idea of a safe function is that safe clients can do what they want with it without violating any safety invariants.

IOW, it *will* be assume_init'ed later by safe code doing a map lookup.

File: library/alloc/src/collections/btree/node.rs (hunk 6 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:292]: Somewhat, but with at least these exceptions:
- temporary ones with `reborrow_mut`
- temporary one with `ptr::read` in `remove_kv_tracking` (I have a PR queued to use `reborrow_mut` instead)
- just realized today, the pointer returned by `insert_fit`

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: Yes it violates the invariant, but internal code has to do that to change pretty much anything.

I understand your concern, but that has applied to other internal functions like `as_leaf` for a long time? As it happens, I tagged that unsafe now, but not because of the mess you can cause using its return value, but because it might stump on other references.

**Comment by ssomers** [comment]
> > I really don't know how to Miri the other test cases,

That wasn't entirely true. I can Miri at any point, by rebasing the btree code on an older master, which I already did. But I can't -Zmiri-track-raw-pointers it.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: I agree that for internal functions it can be less clear-cut who is responsible for upholding which invariant.

> but because it might stump on other references.

it doesn't do anything odd with lifetimes though? So that seems more like something the caller needs to be aware of regardless to me.^^

But in the end it is somewhat arbitrary, so as long as it is properly documented I can live with any of these choices here.

**Comment by RalfJung** [comment]
You are using https://github.com/RalfJung/miri-test-libstd, right? So that would be something like
```
RUST_SRC=/path/to/rustc MIRIFLAGS="-Zmiri-track-raw-pointers" ./run-test.sh alloc btree
```
But be aware that I have never tried this; even the libtest harness might already be breaking pointer provenance rules for all we know... in fact, until https://github.com/rust-lang/rust/pull/78484 lands, many uses of `HashMap` will break with raw ptr tracking.

File: library/alloc/src/collections/btree/node.rs (hunk 6 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:292]: > temporary ones with reborrow_mut

Oh, reborrow_mut doesn't use some lifetimes to make sure only one of the two ptrs can be used?
But then I'd say it is reborrow_mut that should be unsafe, with the safety invariant being "do not use the original ref until you stopped using the reborrowed one". (Somewhat like dorman-mut-ref actually...)

**Comment by ssomers** [comment]
> You are using https://github.com/RalfJung/miri-test-libstd, right?

No, never heard of that. I normally did `cargo miri test` in library/alloc. Or actually, on a symbolic copy with a lot of non-btree tests stripped out.

**Comment by RalfJung** [comment]
> I normally did cargo miri test in library/alloc. Or actually, on a symbolic copy with a lot of non-btree tests stripped out.

Wow, I had no idea that that would even work.^^

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: > What is the alternative to casting?

Like the code above: access the first member `.data` of this `repr(C)` struct.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: >  I tagged that unsafe now

No I didn't. I forgot to tag `as_leaf_mut`, and if I try that, the avalanche means you're tempted to make all bodies unsafe.

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: Ah I see. The problem wasn't with the member access, the problem was with the `&mut`. That violates the "only use raw pointers" rule it creates a reference.

Using `core::ptr::raw_mut!(something.data)` instead should also work.

File: library/alloc/src/collections/btree/node.rs (hunk 6 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:292]: Well  `reborrow_mut` _is_ unsafe, with ample warning, and I think the borrow checker makes sure you can only use the top one, but you can still use it to deallocate the node that the original one refers to, and that's not cool…

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: But that looks suspiciously like the `&raw mut something.data` I tried above in "It does not help to make the reference raw". I just tried it again, and get the same complaint. The pointer tracking says it all:
```
126 |         BoxedNode { ptr: unsafe { Unique::new_unchecked(ptr::raw_mut!(Box::leak(node).data)) } }
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ created tag 58937
    |
```
It's remembering the data. Or actually, it's just #74679 again?

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: Nope. Given 
```rust
    fn from_internal(node: Box<InternalNode<K, V>>) -> Self {
        let whole = ptr::raw_mut!(*Box::leak(node));
        let part = unsafe { ptr::raw_mut!((*whole).data) };
        BoxedNode { ptr: unsafe { Unique::new_unchecked(part) } }
    }
```
the tag of the internal pointer still refers to:
```
    |
127 |         let part = unsafe { ptr::raw_mut!((*whole).data) };
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ created tag 58938
```

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: That is strange, I will have to investigate.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: It does remind me of [a much simpler example](https://users.rust-lang.org/t/why-does-raw-field-pointer-access-trigger-miri-to-pop-a-unique/50449) I've been trying to unravel.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: Same behaviour with this example:
```rust
#![feature(ptr_internals, raw_ref_macros)]
use std::ptr::{self, NonNull, Unique};

struct Part {
    _lame: i32,
}

#[repr(C)]
struct Whole {
    part: Part,
    extra: i32,
}

fn main() {
    let it = Box::new(Whole { part: Part { _lame: 0 }, extra: 42 });
    let whole = ptr::raw_mut!(*Box::leak(it));
    let part = unsafe { ptr::raw_mut!((*whole).part) };
    let unique = unsafe { Unique::new_unchecked(part) };
    let raw = NonNull::from(unique);
    let typed = unsafe { &mut *(raw.as_ptr() as *mut Whole) };
    assert!(typed.extra == 42);
}
```
It also disappears by removing the _lame field.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: So I made the `as_X` methods safe again, and made the ones returning `MaybeUninit` references and slices unsafe. It doesn't make much sense, since you can access the `MaybeUninit` array directly and safely. But you need an unsafe block to do use them anyway.

Maybe the fields shouldn't be open to the entire node code, and the methods returning `MaybeUninit` stuff should be members of `LeafNode`/`InternalNode` instead of `NodeRef`. I fenced off the `BoxedNode` field just to see what the reviewer(s) will say.

**Comment by ssomers** [comment]
>  even the libtest harness might already be breaking pointer provenance rules for all we know

It's not that bad, but of the further two test cases I converted manually, one failed miserably on the `.sort()` of a simple `Vec<u32>`, before getting to anything btree.

Anyway, it seems this is about the best I can get out of it. Doesn't fail with the normal Miri based on ffa2e7ae8fbf9bad.

File: library/alloc/src/collections/btree/node.rs (hunk 3 above)
Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: Yeah this is a Miri / Stacked Borrows problem, good catch! See https://github.com/rust-lang/miri/issues/1608.

**Comment by RalfJung** [comment]
Okay so I guess this is ready for review by @Mark-Simulacrum then. :)

> marked this pull request as ready for review 28 minutes ago

GH unfortunately doesn't send notifications for this so a reviewer would not notice such a status change.

**Comment by Mark-Simulacrum** [comment]
It's S-waiting-on-review, so I'll see it on my next round of reviews :) Probably this weekend or tomorrow, not sure yet.

**Comment by ssomers** [comment]
One more point I forgot to make: think of the pointer provenance rules what you want, the current code is conceptually wrong in common places such as the ubiquitous `push`: it does `assume_init_mut` on uninitialized memory. It always continues to `ptr::write` over it, but still…

**Comment by RalfJung** [comment]
> it does assume_init_mut on uninitialized memory

Oh, yeah, it should not do that... could you add FIXMEs in the code pointing that out?

**Comment by ssomers** [comment]
> add FIXMEs in the code pointing that out?

With "current" I mean the current and past master. I added fixes, hopefully enough of them.

File: library/alloc/src/collections/btree/node.rs (hunk 5 above)
Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs]: One class of methods that has been very clear to me from the start, is those on a plain `self` like `first_edge`, `left_kv`: they simply return the same ownership, borrowship, or whatever you call it.

Next to the easy ones are those on a plain `self` called `into_X` (where I think the unwritten rule is that X is a part of the original, not a neighbour). Some of them return an `'a`  lifetime, which stems from the `NodeRef`'s `marker::Immut<'a>`/`ValMut<'a>`/`Mut<'a>`. It didn't understand what that implied for a long time, but they didn't look daunting either, thanks to the plain `self`.

I now understand why there is both `into_key_at` and `key_at`: because the former profits from the lifetime incorporated into `marker::Immut<'a>`/`ValMut<'a>`/`Mut<'a>`, and the latter is defined and used for all 3 of those, and the only way to do that is to define it over some `BorrowType` without lifetime. Therefore you can write the latter using the former, but not the other way around. `into_key_at` is easy enough and more sophisticated.

Therefore I turned all the new/changed function into the `into_X` class, and I like it.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs]: If there's a good place to document that structure with a comment in the code, that seems like it could be helpful. :)

**Comment by ssomers** [comment]
I've been fidgeting with the BoxedNode definition and now stripped that out because it doesn't belong here.

**Comment by ssomers** [comment]
I realized it's easy enough to draw in more test cases, and some still fail. So this does not yet fix pointer provenance rules entirely.

**Comment by ssomers** [comment]
It turns out that only one area of the code causes the remaining complaints by Miri, and I had straightened that out already (just waiting for other PRs to trickle through). Now built on top of this PR and published, #78631 completes the pointer provenance proceedings.

File: library/alloc/src/collections/btree/node.rs [hunk 7]
```diff
@@ -120,11 +121,11 @@ struct BoxedNode<K, V> {
 
 impl<K, V> BoxedNode<K, V> {
     fn from_leaf(node: Box<LeafNode<K, V>>) -> Self {
-        BoxedNode { ptr: Box::into_unique(node).0 }
+        BoxedNode { ptr: Unique::from(Box::leak(node)) }
     }
 
     fn from_internal(node: Box<InternalNode<K, V>>) -> Self {
-        BoxedNode { ptr: Unique::from(&mut Box::leak(node).data) }
+        BoxedNode { ptr: Unique::from(Box::leak(node)).cast() }
```
Comment (RalfJung) [inline library/alloc/src/collections/btree/node.rs:128]: https://github.com/rust-lang/rust/pull/78597 landed, so `ptr::raw_mut!` should work now.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:128]: But I can't confirm that until #77611 lands (or you backport #78597 into miri's raw-retag branch), right?

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:128]: This is a rustc-only change that does not require a change on the Miri side. (Also miri's raw-retag branch landed.)

So you should be able to confirm this by using the Miri from today's nightly, and your extract btree test case (the latter is still needed to avoid https://github.com/rust-lang/rust/pull/77611).

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:128]: Oh right, I didn't realize these extracted btree test cases are truly stand-alone.

But I don't see any improvement. With Miri's nightly and the latest master, even the [miri #1608](https://github.com/rust-lang/miri/issues/1608) example still fails the same way.

Comment (ssomers) [reply library/alloc/src/collections/btree/node.rs:128]: I guess you mean today's upcoming nightly, not the 2020-11-02 out there at the moment.

Comment (RalfJung) [reply library/alloc/src/collections/btree/node.rs:128]: The latest one out there at the moment is 2020-11-03. I meant 2020-11-04 which for some reason does not exist... (this is the rustup toolchain version, which is always one day ahead of what `rustc` reports -- rustc reports the day the merge commit was created, rustup reports the day the nightly was created)

File: library/alloc/src/collections/btree/node.rs [hunk 8]
```diff
@@ -473,139 +518,157 @@ impl<'a, K, V, Type> NodeRef<marker::Mut<'a>, K, V, Type> {
...
+    fn set_parent_link(&mut self, parent: NonNull<InternalNode<K, V>>, parent_idx: usize) {
+        let leaf = Self::as_leaf_ptr(self);
+        unsafe { (*leaf).parent = Some(parent) };
+        unsafe { (*leaf).parent_idx.write(parent_idx as u16) };
+    }
+
+    /// Clear the node's link to its parent edge, freeing it from its tree.
+    /// This only makes sense when there are no other references to the node.
+    /// Technically it is a waste of time, because we will either insert the
+    /// node elsewhere and correct its parent link, or destroy it.
```
Comment (ssomers) [inline library/alloc/src/collections/btree/node.rs:655]: This part of the comment is in the wrong spot, it only applies to two callers.

**Comment by Mark-Simulacrum** [comment]
I'm not sure if there's a few nits from Ralf and yourself left to fix - long discussions feel a bit unresolved - but this looks good to me. r=me with those nits fixed (in particular, I note https://github.com/rust-lang/rust/pull/78480#discussion_r518380920)

**Comment by ssomers** [comment]
The only open nit, aside from comments, is that originally I tried to avoid the cast that was always there, by changing this expression:

```Unique::from(Box::leak(node)).cast()```

to (what eventually became):

```unsafe { Unique::new_unchecked(ptr::raw_mut!(Box::leak(node).data)) }```

I'm not sure that's such a great improvement, and we can still do it later.

**Comment by Mark-Simulacrum** [comment]
Okay. Seems fine.

@bors r+

**Comment by ssomers** [comment]
It seems we get a conflict over the same commit, rebased here on a newer master than the original.

@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author
