### PR TITLE
Fix Miri sysroot for `x run`

### LINKED ISSUE #126233: "./x.py run miri --stage 1" no longer works
This used to work fine at some point, but now leads to some strange errors:
```
$ ./x.py run miri --stage 1 -- src/tools/miri/tests/pass/hello.rs
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.02s
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.07s
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.11s
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building stage0 tool lld-wrapper (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.06s
Building tool miri (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.07s
Building tool cargo-miri (stage0 -> stage1, x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.07s
Building stage1 miri sysroot (x86_64-unknown-linux-gnu)
A sysroot for Miri is already available in `/home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/miri-sysroot`.
    Finished `release` profile [optimized + debuginfo] target(s) in 0.07s
     Running `build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/miri --target x86_64-unknown-linux-gnu src/tools/miri/tests/pass/hello.rs`
error[E0786]: found invalid metadata files for crate `std`
  |
  = note: corrupt metadata encountered in /home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e9d12b2c234bc463.rlib
  = note: corrupt metadata encountered in /home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e9d12b2c234bc463.so
  = note: corrupt metadata encountered in /home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-ec2a734cf29b8414.rlib

error: cannot find macro `eprintln` in this scope
 --> src/tools/miri/tests/pass/hello.rs:3:5
  |
3 |     eprintln!("Hello, error!");
  |     ^^^^^^^^

error: cannot find macro `println` in this scope
 --> src/tools/miri/tests/pass/hello.rs:2:5
  |
2 |     println!("Hello, world!");
  |     ^^^^^^^

error: requires `sized` lang_item

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0786`.
Build completed unsuccessfully in 0:00:01
```

### PR DESCRIPTION
**Pull request by Noratrieb**
Miri no longer (after https://github.com/rust-lang/miri/pull/3411) respects `MIRI_SYSROOT` and wants to be treated like a REAL rustc, with `--sysroot`. \*pats Miri\* sure Miri, just for you :3.

fixes #126233

r? RalfJung (or whoever else feels like it)

### CODE REVIEW

**Comment by RalfJung** [comment]
Doesn't the --sysroot need to go after the `--`?

**Comment by Nilstrieb** [comment]
oh, it probably does. I had it after at first and tested that, and didn't test the reordering >.<

File: src/bootstrap/src/core/build_steps/run.rs [hunk 1]
```diff
@@ -154,7 +154,7 @@ impl Step for Miri {
         miri.args(builder.config.args());
 
         // miri tests need to know about the stage sysroot
-        miri.env("MIRI_SYSROOT", &miri_sysroot);
+        miri.arg("--sysroot").arg(miri_sysroot);
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/run.rs:157]: This should go before the `builder.config.args()`, so that the user can do something like `./x.py run miri -- flags-for-miri -- flags-for-the-program`. Your approach adds the `--sysroot`  at the end, but due to the `--` that doesn't work properly.

Comment (Nilstrieb) [reply src/bootstrap/src/core/build_steps/run.rs:155]: right. i cannot be trusted with passing arguments.

**Comment by RalfJung** [comment]
Thanks. :)

@bors r+ rollup

**Comment by lqd** [comment]
(cc https://github.com/rust-lang/rust/issues/126430 on that last PR CI failure)

**Comment by lqd** [comment]
it's *PR* CI @Nilstrieb :3 not bors tests

**Comment by Nilstrieb** [comment]
just because i have bors perms does not mean i can read
