### PR TITLE
Recover parse gracefully from `<const N>`

### LINKED ISSUE #84327: Provide const generics hints when a token is forgotten
Ideally, `rustc` should guide the user towards producing const generics code, even if they forget the `const`, the type, or both.

Given the following code:

```rust
// forgot type
impl<T, const N> From<[T; N]> for VecWrapper<T>
where
    T: Clone,
{
    fn from(slice: [T; N]) -> Self {
        VecWrapper(slice.to_vec())
    }
}
```

(All examples are in https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4a11f9dad9f8069e70f2aea6cb4084ad )

The current output is:

```
error: expected `:`, found `>`
  --> src/lib.rs:25:16
   |
25 | impl<T, const N> From<[T; N]> for VecWrapper<T>
   |                ^ expected `:`
```

Ideally the output should look like:
- expected `: Type`
- maybe a hint for the `usize` type, because that's the type of `N` in `[T; N]`

Similarly:
```rust
// Forgot const 
impl<T, N: usize> From<[T; N]> for VecWrapper<T>
where
    T: Clone,
{
    fn from(slice: [T; N]) -> Self {
        VecWrapper(slice.to_vec())
    }
}
```

Produces:
```
error[E0423]: expected value, found type parameter `N`
  --> src/lib.rs:15:28
   |
15 | impl<T, N: usize> From<[T; N]> for VecWrapper<T>
   |                            ^ not a value

error[E0404]: expected trait, found builtin type `usize`
  --> src/lib.rs:15:12
   |
15 | impl<T, N: usize> From<[T; N]> for VecWrapper<T>
   |            ^^^^^ not a trait

error[E0423]: expected value, found type parameter `N`
  --> src/lib.rs:19:24
   |
19 |     fn from(slice: [T; N]) -> Self {
   |                        ^ not a value
```

And:
```rust
// forgot const and type
impl<T, N> From<[T; N]> for VecWrapper<T>
where
    T: Clone,
{
    fn from(slice: [T; N]) -> Self {
        VecWrapper(slice.to_vec())
    }
}
```

Produces:
```
error[E0423]: expected value, found type parameter `N`
  --> src/lib.rs:25:21
   |
25 | impl<T, N> From<[T; N]> for VecWrapper<T>
   |                     ^ not a value

error[E0423]: expected value, found type parameter `N`
  --> src/lib.rs:29:24
   |
29 |     fn from(slice: [T; N]) -> Self {
   |                        ^ not a value
```

```sh
$ rustc --version
rustc 1.53.0-nightly (392ba2ba1 2021-04-17)
```

### PR DESCRIPTION
**Pull request by estebank**
When a const param doesn't have a `: Type`, recover the parser state and provide a structured suggestion. This not only provides guidance on what was missing, but it also makes subsuequent errors to be emitted that would otherwise be silenced.

```
error: expected `:`, found `>`
  --> $DIR/incorrect-const-param.rs:26:16
   |
LL | impl<T, const N> From<[T; N]> for VecWrapper<T>
   |                ^ expected `:`
   |
help: you might have meant to write the type of the const parameter here
   |
LL | impl<T, const N: /* Type */> From<[T; N]> for VecWrapper<T>
   |                ++++++++++++
```

r? @fmease

Follow up to rust-lang/rust#151077. Fix rust-lang/rust#84327.

### CODE REVIEW

File: tests/ui/const-generics/incorrect-const-param.rs [hunk 1]
```diff
@@ -0,0 +1,45 @@
+// #84327
```
Comment (fmease) [inline tests/ui/const-generics/incorrect-const-param.rs:1]: I get that it's nice to group all 3 cases from the issue but is it really necessary? We already have tests in separate files for the other 2 cases we've already addressed (in your PR: #151077, and in mine: #120570).

This doesn't increase test coverage unless I've missed sth. and the added test cases exercise things the preexisting tests don't.

**Review by fmease — APPROVED** [review]
Nice, thanks! r=me rollup with nitpick addressed in one way or another

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151099/8c52f735abd1af9a73941b78fe7ed2ab08b9c0dd..92db7b2b5ab89a37a2d7bdd9c8a25fd8be31e303)*

File: tests/ui/const-generics/incorrect-const-param.rs (hunk 1 above)
Comment (estebank) [reply tests/ui/const-generics/incorrect-const-param.rs:1]: It exercises that the parser recovers correctly besides just providing the suggestion. I tend to group related checks either in the same file when possible, or with files with similar naming. I considered only having this case in the test and then a type error, but felt that having all of them (even if redundant because individual cases are already tested) would help in the future if someone makes changes that incidentally touches these to notice that there are similarly handled cases.
