### PR TITLE
fix autodiff macro on generic functions

### LINKED ISSUE #140032: autodiff on generic functions fails
I tried this code:

```rust
#![feature(autodiff)]

use std::autodiff::autodiff;

    #[autodiff(d_square, Reverse, Duplicated, Active)]
    fn square<T: std::ops::Mul<Output = T> + Copy>(x: &T) -> T {
        *x * *x
    }

    fn main() {
        let xf32: f32 = 3.0;
        let xf64: f64 = 3.0;
        let outputf32 = square::<f32>(&xf32);
        let outputf64 = square::<f64>(&xf64);
        assert_eq!(9.0, outputf32);
        assert_eq!(9.0, outputf64);

        let mut df_dxf32: f32 = 0.0;
        let mut df_dxf64: f64 = 0.0;
        let output_f32 = d_square::<f32>(&xf32, &mut df_dxf32, 1.0);
        let output_f64 = d_square::<f64>(&xf64, &mut df_dxf64, 1.0);
        assert_eq!(outputf32, output_f32);
        assert_eq!(outputf64, output_f64);
        assert_eq!(6.0, df_dxf32);
        assert_eq!(6.0, df_dxf64);
    }
```

I expected to see this happen: works.

Instead, this happened:
```bash
error[E0412]: cannot find type `T` in this scope
 --> src/main.rs:6:56
  |
6 |     fn square<T: std::ops::Mul<Output = T> + Copy>(x: &T) -> T {
  |                                                        ^ not found in this scope
  |
help: you might be missing a type parameter
  |
1 | <T>#![feature(autodiff)]
  | +++
```

### Meta

`rustc --version --verbose`:
```
build from source
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

Solution: TBA

### PR DESCRIPTION
**Pull request by haenoe**
heloo there!
This short PR allows applying the `autodiff` macro to generic functions like this one. 
It only touches the frontend part, since the `rustc_autodiff` macro can already handle generics.
```rust
#[autodiff(d_square, Reverse, Duplicated, Active)]
fn square<T: std::ops::Mul<Output = T> + Copy>(x: &T) -> T {
    *x * *x
}
```
Thanks to Manuel for creating an issue on this. For more information on this see #140032 
r? @ZuseZ4 

As always: thanks for any piece of feedback!!

Fixes: #140032
Tracking issue for autodiff: https://github.com/rust-lang/rust/issues/124509

### CODE REVIEW

**Comment by haenoe** [comment]
> ...
> The source function square is fine, but d_square has to change. We need to copy the generic bounds. We might also want to specify the bounds in the body (the `::<T>`), but I'm not sure if that's ever needed, so we could also skip it in the beginning. 
> ```rs
> #[rustc_autodiff(Reverse, 1, Duplicated, Active)]
> #[inline(never)]
> fn d_square<T: std::ops::Mul<Output = T> + Copy>(x: &T, dx_0: &mut T, dret: T) -> T {
>     unsafe {
>         asm!("NOP", options(pure, nomem));
>     };
>     ::core::hint::black_box::<T>(square(x));
>     ::core::hint::black_box((dx_0, dret));
>     ::core::hint::black_box::<T>(square(x))
> }
> ``` 

 _Originally posted by @ZuseZ4 in [#140032](https://github.com/rust-lang/rust/issues/140032#issuecomment-2816617933)_

As mentioned by Manuel here, it may also be interesting to specify the type bounds in the generated body.
Should we implement this as a preliminary step? Happy about any input on this!

**Comment by ZuseZ4** [comment]
That were few lines of code, nice. Can you also add a test to `tests/codegen/autodiff` to make sure that we keep handling monomorphization correctly? Especially, please add a test where you call d_square with a type which you haven't used when calling square, to make sure that just calling d_square will already force the correct instantiation of square.


Also, can you please add the turbofish when calling the functions in the body? 
@kpreid just gave a good example of when it would be needed. If foo is defined with some generic that isn't used on neither inputs, nor the return type, then rustc won't infer it if we call foo. So it would be good to specify it and add a test for that.

File: compiler/rustc_builtin_macros/src/autodiff.rs [hunk 1]
```diff
@@ -674,8 +678,10 @@ mod llvm_enzyme {
         span: Span,
         primal: Ident,
         idents: &[Ident],
+        generics: &Generics,
```
Comment (haenoe) [inline compiler/rustc_builtin_macros/src/autodiff.rs:681]: Passing this through 3x is a bit ugly :/

File: compiler/rustc_builtin_macros/src/autodiff.rs [hunk 2]
```diff
@@ -674,8 +678,10 @@ mod llvm_enzyme {
...
     ) -> P<ast::Expr> {
         let has_self = idents.len() > 0 && idents[0].name == kw::SelfLower;
+
         if has_self {
```
Comment (haenoe) [inline compiler/rustc_builtin_macros/src/autodiff.rs:685]: Right now, I left the code only in the lower branch.
@ZuseZ4 could you quickly explain why we have this explicit branching here?

File: compiler/rustc_builtin_macros/src/autodiff.rs [hunk 3]
```diff
@@ -684,7 +690,46 @@ mod llvm_enzyme {
...
-            let primal_call_expr = ecx.expr_path(ecx.path_ident(span, primal));
+            let mut primal_path = ecx.path_ident(span, primal);
+
+            if let Some(function) = primal_path.segments.last_mut() {
+                let primal_generic_types = generics
+                    .params
+                    .iter()
+                    .filter(|param| matches!(param.kind, ast::GenericParamKind::Type { .. }));
+
+                let generated_generic_types = primal_generic_types
```
Comment (haenoe) [inline compiler/rustc_builtin_macros/src/autodiff.rs:701]: There probably is some helper functions available in `ExtCtxt` make this less ugly? ^^'

File: tests/pretty/autodiff_forward.pp [hunk 4]
```diff
@@ -39,7 +39,7 @@
 #[inline(never)]
 pub fn df1(x: &[f64], bx_0: &[f64], y: f64) -> (f64, f64) {
     unsafe { asm!("NOP", options(pure, nomem)); };
-    ::core::hint::black_box(f1(x, y));
+    ::core::hint::black_box(f1::<>(x, y));
```
Comment (haenoe) [inline tests/pretty/autodiff_forward.pp:42]: Do we want the `::<>` in non generic functions, or just emit it fully?

**Comment by haenoe** [comment]
Left some of the things I though about while writing -- will head to bed now! Thanks for any tips!

File: tests/pretty/autodiff_forward.pp (hunk 4 above)
Comment (ZuseZ4) [reply tests/pretty/autodiff_forward.pp:42]: I'd probably skip it in non-generic functions. I don't think too many people will look at it, but I still try to keep the function somewhat simple.

File: compiler/rustc_builtin_macros/src/autodiff.rs (hunk 1 above)
Comment (ZuseZ4) [reply compiler/rustc_builtin_macros/src/autodiff.rs:681]: There is a discussion about fully dropping the function body and just generating a declaration using `#[rustc_intrinsic]` ^^ [#wg-autodiff > Placeholder function design @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/390790-wg-autodiff/topic/Placeholder.20function.20design/near/510446645)
This would make the frontend trivial, but complicate things a bit in the middle or backend. I think it's still an overall win, but I haven't looked into it.

File: compiler/rustc_builtin_macros/src/autodiff.rs (hunk 2 above)
Comment (ZuseZ4) [reply compiler/rustc_builtin_macros/src/autodiff.rs:685]: I assume it's for methods, e.g. https://github.com/rust-lang/rust/issues/139557
But we don't have tests in `tests/pretty/` using self, and as per issue I also broke support for it at some point, so .. that checks out. 

I think that this code handles calling another method in the dummy body, so instead of generating
`bench_black_box(d_psi(self, j, 1.0));` we'd generate `bench_black_box(self.d_psi(j, 1.0));`

Comment (haenoe) [reply compiler/rustc_builtin_macros/src/autodiff.rs:685]: Since the `impl` PR is already being rolled up I will try to fix it as part of this PR after I have rebased

**Comment by haenoe** [comment]
> That were few lines of code, nice. Can you also add a test to `tests/codegen/autodiff` to make sure that we keep handling monomorphization correctly? Especially, please add a test where you call d_square with a type which you haven't used when calling square, to make sure that just calling d_square will already force the correct instantiation of square.

@ZuseZ4 do I understand correctly, that when I call `d_square::<f64>` without having called `square::<f64>` before, then `square::<f64>` should be generated? Or should the last "square" in your statement be in fact "d_square"?

**Comment by haenoe** [comment]
Sorry, wrong rebase xD

**Comment by ZuseZ4** [comment]
Yes exactly, the macro should internally generate the primal call and force instantiation. So that should be tested by not manually calling the primal.

**Comment by haenoe** [comment]
Okay! I can now better explain why I was confused. I copied the test parameters from one of the other codegen tests (which included `opt-level=3`.
[This gist](https://gist.github.com/haenoe/f426109f6c8e31985284dd8127acd459) shows the LLVM-IR output of the test I added
1. with `opt-level=0`
2. with `opt-level=3`

When searching for `generic::square` the `opt-level=0` version, you can see that indeed, the macro has caused the compiler to generate two versions of the function (one which takes `float`, and another which takes `double`).
In the `opt-level=3` output however, the function is only generated once for `float`.

Is the compiler smart enough to find out that `square::<f64>` is _actually_ not needed or could this pose a problem for us?
Thanks for you help!

**Comment by ZuseZ4** [comment]
Due to our macro generating a call to the primal function, ristc will instantiate it. Then we run Enzyme and differentiate the primal, and replace the placeholder body with the actual derivative code. That means that the call to our primal, which enzyme generated, is gone. We run another opt pipeline after AD, so llvm will recognize the now unused primal and delete it under O3.
If you run optlevel=3 with NoPostopt flag (might be in my PR which is currently in the merge queue), them you should still see the primal in the codegen test (I didn't try it, so correct me if I'm wrong)

File: tests/codegen/autodiff/generic.rs [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+fn main() {
+    let xf32: f32 = std::hint::black_box(3.0);
+    let xf64: f64 = std::hint::black_box(3.0);
+
+    // Ensure that `square::<f32>` is generated.
+    //
+    //              f32
+    //             | | |
+    //             V V V
+    // CHECK: fmul float %{{.+}}, %{{.+}}
```
Comment (ZuseZ4) [inline tests/codegen/autodiff/generic.rs:22]: This is too generic, as it can match an arbitrary float multiplication anywhere in the rust std lib (since we use fat-lto). You can check some of the other codegen tests for example.
A more reliable setup would be
1) CHECK the debug name of the function 
2) CHECK-NEXT: the beginning of the function header (ignore anything after the closing bracket after the last arg)
3) CHECK-NOT: ret
4) CHECK: fmul float ...
Step 3 is to make sure that we haven't seen a return statement yet, and thus that the fmul is still part of the same function.

(and do that for both cases). I'd also move the CHECK's out of the main function just so that they are at the outermost level. I'm not sure if it's required by other tooling, but that's the convention I've usually seen (correct me if you saw some other examples).

Comment (ZuseZ4) [reply tests/codegen/autodiff/generic.rs:22]: ping @haenoe, do you have some time to look into it, or do you prefer it if I write the tests?

Comment (haenoe) [reply tests/codegen/autodiff/generic.rs:22]: Heyy Manuel!
Sorry, had a lot going on. I will look at it tomorrow at the latest.
One thing that felt kind of weird was matching the debug name, which are random characters the name and then some more random chars.

Do you think a `.*name.*` is sufficient?

Comment (ZuseZ4) [reply tests/codegen/autodiff/generic.rs:22]: No worries, I can always take over, even partial PRs are helpful. I just want to make sure that this one doesn't end up stalled because people seem to be excited to differentiate generic functions.

Yes it's sufficient because we print the debug name as a comment above the function. In LLVM-IR, you can start a comment with `;`, it's not the `//` from C++ or Rust. So in our LLVM-IR we have

```llvm
; moduleName::functionName
define mangledFnName(...)
```
So you wouldn't match the mangled name, but the real name above. With `CHECK-NEXT` you then make sure that you match the real function on the following line.

**Comment by haenoe** [comment]
Hey thanks a lot for your patience and esp. your assistance :D

**Comment by ZuseZ4** [comment]
(I'm currently at rustweek, but also want to look at the full generated llvm-ir before merging, so I might take a few days longer to review this time)

**Comment by ZuseZ4** [comment]
Thanks! Yes it was nice, hopefully you get a chance to join next year.
Ok, during my flight home I finally got to build it locally and check the IR, lgtm.

@bors r+ rollup
