### PR TITLE
Inherit overflow checks for sum and product

### LINKED ISSUE #35807: Investigate panic behavior of sum
Originally reported on HN: https://news.ycombinator.com/item?id=12316209

Basically, the docs for [`Iterator::sum`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.sum) say

> # Panics
> 
> When calling sum and a primitive integer type is being returned, this method will panic if the computation overflows.

Is this a special behavior of `sum`, or is this just the regular behavior of arithmetic? If it's the latter, then these docs are probably wrong / unnecessary.

I am not sure, but am willing to bet that this might just be out of date. To resolve this ticket, either the behavior should be confirmed, or the docs should be updated.

### PR DESCRIPTION
**Pull request by sfackler**
We have previously documented the fact that these will panic on overflow, but I think this behavior is what people actually want/expect. `#[rustc_inherit_overflow_checks]` didn't exist when we discussed these for stabilization.

r? @alexcrichton 

Closes #35807

### CODE REVIEW

File: src/libcore/iter/traits.rs [hunk 1]
```diff
@@ -581,13 +582,15 @@ pub trait Product<A = Self>: Sized {
...
+// NB: explicitly use Add and Mul here to inherit overflow checks
 macro_rules! integer_sum_product {
     ($($a:ident)*) => ($(
         #[stable(feature = "iter_arith_traits", since = "1.12.0")]
         impl Sum for $a {
+            #[rustc_inherit_overflow_checks]
             fn sum<I: Iterator<Item=$a>>(iter: I) -> $a {
                 iter.fold(0, |a, b| {
-                    a.checked_add(b).expect("overflow in sum")
+                    Add::add(a, b)
```
Comment (eddyb) [inline src/libcore/iter/traits.rs]: This is not what I meant, although it would work (even without any added `rustc_inherit_overflow_checks`).
The intention was to replace the closure, i.e. `iter.fold(0, Add::add)`.

Comment (sfackler) [inline src/libcore/iter/traits.rs]: I seem to remember that at one point that syntax decayed to function pointers - is that not the case anymore?

Comment (eddyb) [inline src/libcore/iter/traits.rs]: That hasn't been the case since some time before 1.0, at the type level, and since March or so this year as far as the low-level representation and optimizations go.

Comment (sfackler) [inline src/libcore/iter/traits.rs]: Ah, awesome, updated.

File: src/libcore/iter/traits.rs [hunk 2]
```diff
@@ -581,41 +582,35 @@ pub trait Product<A = Self>: Sized {
     fn product<I: Iterator<Item=A>>(iter: I) -> Self;
 }
 
+// NB: explicitly use Add and Mul here to inherit overflow checks
 macro_rules! integer_sum_product {
     ($($a:ident)*) => ($(
         #[stable(feature = "iter_arith_traits", since = "1.12.0")]
         impl Sum for $a {
+            #[rustc_inherit_overflow_checks]
```
Comment (eddyb) [inline src/libcore/iter/traits.rs]: Pretty sure you can remove the attribute now (not that it ever worked, AFAICT).

**Comment by alexcrichton** [comment]
Is this something we actually want to guarantee? I thought MIR made it so that we *couldn't* do this and there's a "weird hack" to get it to work in some circumstances that we want to remove at some point.

**Comment by eddyb** [comment]
@alexcrichton The only way to remove the hack IMO is to have separate builds of libstd, with and without debug assertions.

Either way the version of sum and product here won't change behavior if such a change occurs.

**Comment by alexcrichton** [comment]
@eddyb could you clarify what you mean by "won't change behavior if such a change occurs"?

I was under the impression that we don't want to proliferate the semantics of `#[rustc_inherit_overflow_checks]` and would instead prefer to direct energy toward multiple builds of std.

**Comment by eddyb** [comment]
@alexcrichton This PR (except for a line that should've been removed) doesn't need the attribute and solely relies on the ops traits (Add and Mul) for builtin types having the right semantics.

If this was a larger patch I'd agree, but I don't see how this one would pose a problem.
Probably better to wait for discussion by the libs team either way.

**Comment by alexcrichton** [comment]
Right yeah this'll be sufficient without propagating the attributes themselves, but it propagates the semantics which we're unsure about.

I was personally under the impression that #35807 is already a closed bug in that the semantics are exactly as documented, the iterator adaptors panic on overflow. We can and probably should discuss in @rust-lang/libs though!

**Comment by alexcrichton** [comment]
Discussed at libs triage the decision was to merge. @sfackler could you remove the attribute here and I'll merge?

The point which swayed me was that the actual interface to this, `cargo build` and `cargo build --release` will not change eventually once we ship debug builds of libstd, so this seems reasonable in the interim.

File: src/libcore/iter/traits.rs (hunk 2 above)
Comment (sfackler) [inline src/libcore/iter/traits.rs]: Oops, yeah, just missed this one.

**Comment by sfackler** [comment]
Updated

**Comment by cuviper** [comment]
> once we ship debug builds of libstd

BTW, is there a tracking issue for this?  It will affect us distro packagers...
