### PR TITLE
Fix overflow error in thread::sleep

### LINKED ISSUE #34330: std::thread::sleep(Duration::new(u64::MAX, 0)) panics with EINVAL
```
$ cargo version
cargo 0.10.0-nightly (10ddd7d 2016-04-08)

$ rustc --version --verbose
rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-apple-darwin
release: 1.9.0

$ export RUST_BACKTRACE=1 cargo clean && cargo run
     Running `target/debug/sleeptest`
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `22`, right: `4`)', ../src/libstd/sys/unix/thread.rs:137
stack backtrace:
   1:        0x10f6c4058 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x10f6c55c5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x10f6c51fe - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x10f6c01c6 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10f6c095e - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:        0x10f6bf79c - std::thread::sleep::ha8d8975d57b519ae
   7:        0x10f6bf242 - sleeptest::main::hda16ced47dcbd1e7
   8:        0x10f6c4df2 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
   9:        0x10f6c343b - __rust_try
  10:        0x10f6c4c34 - std::rt::lang_start::h5b0863080165c75e
  11:        0x10f6bf309 - main
error: Process didn't exit successfully: `target/debug/sleeptest` (exit code: 101)

$ cat src/main.rs
use std::time::Duration;
use std::u64;

fn main() {
    std::thread::sleep(Duration::new(u64::MAX, 0));
}

$ 
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #34330

I added a test to have a more clear error inside the function. Since `time_t` is `i64` and we expect `u64`, maybe we should changed the awaited type?

### CODE REVIEW

**Comment by nagisa** [comment]
Rather than a test we should just iteratate and call sleep multiple times with duration of up-to the required amount.

File: src/libstd/sys/unix/thread.rs [hunk 1]
```diff
@@ -125,8 +126,10 @@ impl Thread {
     }
 
     pub fn sleep(dur: Duration) {
+        let secs = dur.as_secs();
+        assert!(secs <= (u64::MAX >> 1), "secs number is too big");
```
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: The error happens because “The rqtp argument specified a nanosecond value less than zero or greater than or equal to 1000 million.” `u64::MAX >> 1` is not 1000 million.

**Comment by nagisa** [comment]
Also needs a regression test. You should either mock-out the nanosleep function or invoke a new thread/process and catch a signal of some sort sent to it by the parent.

File: src/libstd/sys/unix/thread.rs (hunk 1 above)
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: Oh wait, my bad. Disregard me.

Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: I think it still would be more clear if you did something like:

```
let secs = dur.as_secs() as libc::time_t;
assert!(secs.is_positive(), "...");
```

Your current approach won’t catch the cases where `time_t` is `i32` (some versions of windows, mips linux etc)

File: src/libstd/sys/unix/thread.rs [hunk 2]
```diff
@@ -125,16 +125,32 @@ impl Thread {
     }
 
     pub fn sleep(dur: Duration) {
+        fn get_secs(secs: &mut u64) -> libc::time_t {
+            if *secs >= libc::time_t::max_value() as u64 {
+                *secs -= libc::time_t::max_value() as u64 - 1;
+                libc::time_t::max_value() - 1
```
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: Why `- 1` here and above this line?

**Comment by nagisa** [comment]
r=me with `-1` thing explained as a code comment or removed.

**Comment by nagisa** [comment]
cc @alexcrichton

File: src/libstd/sys/unix/thread.rs (hunk 2 above)
Comment (GuillaumeGomez) [inline src/libstd/sys/unix/thread.rs]: It fails if >= 1000000. So I put the max minus one.

File: src/libstd/sys/unix/thread.rs [hunk 3]
```diff
@@ -125,16 +125,32 @@ impl Thread {
     }
 
     pub fn sleep(dur: Duration) {
+        fn get_secs(secs: &mut u64) -> libc::time_t {
+            if *secs > libc::time_t::max_value() as u64 {
```
Comment (alexcrichton) [inline src/libstd/sys/unix/thread.rs]: Perhaps this could be:

```rust
let amt = cmp::min(libc::time_t::max_value() as u64, *secs);
*secs -= amt;
amt
```

File: src/libstd/sys/unix/thread.rs [hunk 4]
```diff
@@ -125,16 +125,32 @@ impl Thread {
...
         };
 
         // If we're awoken with a signal then the return value will be -1 and
         // nanosleep will fill in `ts` with the remaining time.
         unsafe {
-            while libc::nanosleep(&ts, &mut ts) == -1 {
-                assert_eq!(os::errno(), libc::EINTR);
+            while secs > 0 {
+                ts.tv_sec = get_secs(&mut secs);
+                if libc::nanosleep(&ts, &mut ts) == -1 {
```
Comment (alexcrichton) [inline src/libstd/sys/unix/thread.rs]: I think that this'll need to be a loop of some form to correctly handle EINTR. The `nanosleep` function will automatically update `ts` with the remaining time when `EINTR` is returned, and I think on success as well. Basically we'll need to repeatedly call `nanosleep` until it succeeds.

**Comment by GuillaumeGomez** [comment]
@nagisa: I prefer let you r+ directly (don't know if your comment still applies since you asked @alexcrichton).

File: src/libstd/sys/unix/thread.rs [hunk 5]
```diff
@@ -125,16 +125,32 @@ impl Thread {
...
+                *secs = 0;
+                copy as libc::time_t
+            }
+        }
+
+        let mut secs = dur.as_secs();
         let mut ts = libc::timespec {
-            tv_sec: dur.as_secs() as libc::time_t,
+            tv_sec: 0,
             tv_nsec: dur.subsec_nanos() as libc::c_long,
```
Comment (alexcrichton) [inline src/libstd/sys/unix/thread.rs]: Oh this'll want to be 0 so long as `secs > 0` because otherwise an extra number of nanoseconds is going to be slept each time. I think that to be robust you may just want to move creation of this `timespec` into the loop below to avoid having to re-initialize these fields and have a value leak from one iteration of the loop to the next.

File: src/libstd/sys/unix/thread.rs (hunk 4 above)
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: It is still in a loop, so this is correct. It will simply recalculate the second count on each iteration.

File: src/libstd/sys/unix/thread.rs (hunk 3 above)
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: This seems like a right thing to do.

File: src/libstd/sys/unix/thread.rs (hunk 4 above)
Comment (GuillaumeGomez) [inline src/libstd/sys/unix/thread.rs]: It'll be super precise! :smiley_cat:

File: src/libstd/sys/unix/thread.rs [hunk 6]
```diff
@@ -125,16 +125,33 @@ impl Thread {
...
+            while secs > 0 || nsecs > 0 {
+                let mut ts = libc::timespec {
+                    tv_sec: get_secs(&mut secs),
+                    tv_nsec: nsecs,
+                };
+                if libc::nanosleep(&ts, &mut ts) == -1 {
+                    assert_eq!(os::errno(), libc::EINTR);
+                }
+                secs += ts.tv_sec as u64;
+                nsecs = ts.tv_nsec;
```
Comment (nagisa) [inline src/libstd/sys/unix/thread.rs]: Interestingly, documentation for nanosleep does not specify what `ts` contains after a successful call, therefore, in order to be on the safe side, you want to only do this in case the nanosleep call fails and set these fields to 0 otherwise.

Comment (GuillaumeGomez) [inline src/libstd/sys/unix/thread.rs]: Nice idea!

**Comment by alexcrichton** [comment]
@bors: r-

Ah there's still a loop that's needed, I'll comment to it.

**Comment by alexcrichton** [comment]
@bors: r+ 

oh nvmd I see, just had to think for a second...

**Comment by GuillaumeGomez** [comment]
Ah, `ualarm` isn't defined on android. Do I ignore this platform as well?

**Comment by nagisa** [comment]
What about `setitimer` which is a newer alternative to the `ualarm`?

**Comment by alexcrichton** [comment]
Or... spawn a thread which sleeps for a smaller amount of time and then exits?

**Comment by GuillaumeGomez** [comment]
@alexcrichton: I take your solution! :)

**Comment by GuillaumeGomez** [comment]
Updated.

File: src/test/run-pass/sleep.rs [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// ignore-windows
+
+#![feature(libc)]
+
+extern crate libc;
```
Comment (alexcrichton) [inline src/test/run-pass/sleep.rs]: I think this and `feature` and `// ignore` above can all be removed

File: src/libstd/sys/unix/thread.rs [hunk 8]
```diff
@@ -125,16 +125,30 @@ impl Thread {
...
     pub fn sleep(dur: Duration) {
-        let mut ts = libc::timespec {
-            tv_sec: dur.as_secs() as libc::time_t,
-            tv_nsec: dur.subsec_nanos() as libc::c_long,
-        };
+        fn get_secs(secs: &mut u64) -> libc::time_t {
+            let amt = cmp::min(libc::time_t::max_value() as u64, *secs);
+            *secs -= amt;
+            amt as libc::time_t
+        }
```
Comment (alexcrichton) [inline src/libstd/sys/unix/thread.rs]: This is small enough and only called in one location that this can probably be inlined directly below

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
```
------------------------------------------
stderr:
------------------------------------------
<anon>:11:1: 11:19 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
<anon>:11 extern crate libc;
          ^~~~~~~~~~~~~~~~~~
<anon>:11:1: 11:19 help: add #![feature(libc)] to the crate attributes to enable
error: aborting due to previous error
```

I put back the feature.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
Actually `libc` was completely useless, I just removed it.
