### PR TITLE
Remove bounds check when array is indexed by enum

### LINKED ISSUE #102303: Array indexed by enum cast to usize no longer has bounds check eliminated
Rust compiler fails to eliminate bounds check when array is indexed by an enum cast to usize
Compiler explorer: https://godbolt.org/z/4o5cqT1eK

### Code

```rust
pub enum Enum {
    A, B, C
}

pub fn func(inbounds: Enum, array: &[i16; 3]) -> i16 {
    array[inbounds as usize]
}
```
I expected the compiler to remove the bounds checks like it did previously however it failed to do so.

### Version it worked on

It most recently worked on: Rust 1.63.0

### Version with regression

```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by ouz-a**
As the title says, this reverts the behavior introduced with 1.64.

Fixes #102303

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_mir_transform/src/check_unsafety.rs [hunk 1]
```diff
@@ -106,7 +106,7 @@ impl<'tcx> Visitor<'tcx> for UnsafetyChecker<'_, 'tcx> {
             }
 
             // Move to above list once mir construction uses it.
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/check_unsafety.rs:108]: Please do what the comment says ^^

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 2]
```diff
@@ -197,16 +198,42 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
                         block,
                         source_info,
                         discr,
                         Rvalue::Discriminant(temp.into()),
                     );
+                    let (op,ty) = (Operand::Move(discr), discr_ty);
+
+                    if let Abi::Scalar(scalar) = layout.unwrap().abi{
+                        if let Primitive::Int(..) = scalar.primitive(){
+                           let end_range = scalar.valid_range(&this.tcx).end;
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:214]: If the range start is larger than the end, that means we have a wraparound range. In that case the assume will be wrong. Either check for that case or generalize the logic to handle range start, too, as well as wraparound ranges.

Should probably add a test for it, too

**Review by oli-obk — CHANGES_REQUESTED** [review]
Please do some manual rustfmting since rustfmt is broken on this file

File: src/test/codegen/enum-bounds-check-derived-idx.rs [hunk 3]
```diff
@@ -13,7 +13,7 @@ pub enum Bar {
 #[no_mangle]
 pub fn lookup_inc(buf: &[u8; 5], f: Bar) -> u8 {
     // FIXME: panic check can be removed by adding the assumes back after https://github.com/rust-lang/rust/pull/98332
```
Comment (jackh726) [inline src/test/codegen/enum-bounds-check-derived-idx.rs:15]: This and the next test can get their FIXMEs removed.

**Comment by ouz-a** [comment]
> Please do some manual rustfmting since rustfmt is broken on this file

Formatted some more, let me know if it's still bad.

File: compiler/rustc_mir_transform/src/check_unsafety.rs (hunk 1 above)
Comment (ouz-a) [reply compiler/rustc_mir_transform/src/check_unsafety.rs]: I completely removed statement match as it no longer has any use

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 4]
```diff
@@ -196,17 +197,64 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                                    Rvalue::BinaryOp(BinOp::Ge, Box::new(((lit_op),(Operand::Copy(discr)))))
+                                );
+                                this.cfg.push(
+                                    block,
+                                    Statement {
+                                        source_info,
+                                        kind: StatementKind::Intrinsic(Box::new(NonDivergingIntrinsic::Assume(Operand::Copy(is_ge)))) },
+                                );
+                                if signed && range.end != max_size{
+                                    let range_start = ConstantKind::from_bits(this.tcx,range.end, ty::ParamEnv::empty().and(discr_ty));
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:236]: I don't get the `range.end` being used as `range_start` logic.

I think you can just use `range.start` and not have the above condition at all, just always encode a start `assume`

File: compiler/rustc_mir_transform/src/check_unsafety.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_mir_transform/src/check_unsafety.rs]: Oh but it does ^^ it makes sure when we add new variants that we address them here

**Comment by oli-obk** [comment]
> Formatted some more, let me know if it's still bad.

it is

you can just copy your added code into the playground and rustfmt it there and copy it back, I think that should work

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs (hunk 4 above)
Comment (ouz-a) [reply compiler/rustc_mir_build/src/build/expr/as_rvalue.rs]: good catch :sweat_smile:

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 5]
```diff
@@ -197,16 +198,71 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                                this.cfg.push(
+                                    block,
+                                    Statement {
+                                        source_info,
+                                        kind: StatementKind::Intrinsic(Box::new(NonDivergingIntrinsic::Assume(
+                                            Operand::Copy(is_ge),
+                                        ))),
+                                    },
+                                );
+                                if signed {
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:236]: I think we can do this for unsigned ints, too.

File: compiler/rustc_mir_transform/src/check_unsafety.rs [hunk 6]
```diff
@@ -91,23 +91,6 @@ impl<'tcx> Visitor<'tcx> for UnsafetyChecker<'_, 'tcx> {
 
     fn visit_statement(&mut self, statement: &Statement<'tcx>, location: Location) {
         self.source_info = statement.source_info;
-        match statement.kind {
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/check_unsafety.rs:94]: Keep this match around as a canary for when we add new variants

File: src/test/codegen/enum-bounds-check-derived-idx.rs [hunk 7]
```diff
@@ -12,15 +12,13 @@ pub enum Bar {
...
-    // FIXME: panic check can be removed by adding the assumes back after https://github.com/rust-lang/rust/pull/98332
-    // CHECK: panic_bounds_check
+    // CHECK-NOT: panic_bounds_check
     buf[f as usize + 1]
 }
 
 // CHECK-LABEL: @lookup_dec
 #[no_mangle]
 pub fn lookup_dec(buf: &[u8; 5], f: Bar) -> u8 {
-    // FIXME: panic check can be removed by adding the assumes back after https://github.com/rust-lang/rust/pull/98332
```
Comment (oli-obk) [inline src/test/codegen/enum-bounds-check-derived-idx.rs:23]: This hasn't been fixed.. it will be fixed when the range start is being used

File: src/test/codegen/mem-replace-direct-memcpy.rs [hunk 8]
```diff
@@ -17,8 +17,8 @@ pub fn replace_byte(dst: &mut u8, src: u8) -> u8 {
 
 // CHECK-NOT: call void @llvm.memcpy
 // CHECK: ; core::mem::replace
-// CHECK-NOT: call void @llvm.memcpy
```
Comment (oli-obk) [inline src/test/codegen/mem-replace-direct-memcpy.rs:20]: What happened here? These should not be changed

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 9]
```diff
@@ -197,16 +198,71 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
                 // create all the steps directly in MIR with operations all backends need to support anyway.
                 let (source, ty) = if let ty::Adt(adt_def, ..) = source.ty.kind() && adt_def.is_enum() {
                     let discr_ty = adt_def.repr().discr_type().to_ty(this.tcx);
-                    let temp = unpack!(block = this.as_temp(block, scope, source, Mutability::Not));
+                    let layout = this.tcx.layout_of(this.param_env.and(source.ty));
                     let discr = this.temp(discr_ty, source.span);
+                    let temp = unpack!(block = this.as_temp(block, scope, source, Mutability::Not));
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:203]: Move this back up to keep the diffssimpler

File: src/test/codegen/enum-bounds-check-derived-idx.rs (hunk 7 above)
Comment (ouz-a) [reply src/test/codegen/enum-bounds-check-derived-idx.rs:23]: should I add back it now ?

File: src/test/codegen/mem-replace-direct-memcpy.rs (hunk 8 above)
Comment (ouz-a) [reply src/test/codegen/mem-replace-direct-memcpy.rs:20]: The test was failing, changed it again, but I am not sure why this test is getting affected by this code

File: src/test/codegen/enum-bounds-check-derived-idx.rs (hunk 7 above)
Comment (oli-obk) [reply src/test/codegen/enum-bounds-check-derived-idx.rs:23]: No, it is now fixed after all ^^

File: src/test/codegen/enum-bounds-check.rs [hunk 10]
```diff
@@ -22,6 +22,6 @@ pub enum Bar {
 #[no_mangle]
 pub fn lookup_unmodified(buf: &[u8; 5], f: Bar) -> u8 {
     // FIXME: panic check can be removed by adding the assumes back after https://github.com/rust-lang/rust/pull/98332
```
Comment (oli-obk) [inline src/test/codegen/enum-bounds-check.rs:24]: This FIXME can now be removed

File: src/test/codegen/mem-replace-direct-memcpy.rs (hunk 8 above)
Comment (oli-obk) [reply src/test/codegen/mem-replace-direct-memcpy.rs:20]: I don't think it is. Try reverting all the changes to this file

Comment (ouz-a) [reply src/test/codegen/mem-replace-direct-memcpy.rs]: okay I reverted everything..

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 11]
```diff
@@ -198,15 +199,68 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
                         source_info,
                         discr,
                         Rvalue::Discriminant(temp.into()),
                     );
+                    let (op,ty) = (Operand::Move(discr), discr_ty);
+
+                    if let Abi::Scalar(scalar) = layout.unwrap().abi{
+                        if let Primitive::Int(..) = scalar.primitive(){
+                            let range = scalar.valid_range(&this.tcx);
+                            if range.end >= range.start {
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:215]: Leave a FIXME for implementing wraparound assumes, too.

File: compiler/rustc_mir_build/src/build/expr/as_rvalue.rs [hunk 12]
```diff
@@ -198,15 +199,68 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                                let range_end =
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:216]: You showed me tests on zulip that I think would require sign extension here, too. Please add these tests.

To simplify this logic here, maybe put it into a closure and call it twice, once for start and once for end. That way the logic only exists once and you avoid such bugs.

**Review by oli-obk — CHANGES_REQUESTED** [review]
After the comments have been addressed, squash all commits

**Comment by oli-obk** [comment]
@bors delegate+

r=me with commits squashed

**Review by oli-obk — APPROVED** [review]
