### PR TITLE
handle elision in async fn correctly

### LINKED ISSUE #63388: `&self` lifetime elision with two parameters does not work with `async fn`
Originally reported in https://github.com/rust-lang/rust/pull/63383#discussion_r312128268.

```rust
#![feature(async_await)]

#![feature(nll)]
// Without it you also get //~^ ERROR cannot infer an appropriate lifetime

struct A;

impl A {
    async fn foo(&self, f: &u32) -> &A {
        self
    }
}
```

should compile (it does if you remove `async` or write `async fn foo<'a, 'b>(&'a self, f: &'b u32) -> &'a A`) but does not ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=650e36b5d1b5874f4b8e8309e27b1e52)):

```rust
error[E0106]: missing lifetime specifier
 --> src/lib.rs:7:37
  |
7 |     async fn foo(&self, f: &u32) -> &A {
  |                                     ^
  |
  = note: return-position elided lifetimes require exactly one input-position elided lifetime, found multiple.
```

This seems like a rather serious usability bug as compared to what you expect from normal Rust.

cc https://github.com/rust-lang/rust/pull/63209
cc @nikomatsakis @cramertj

### PR DESCRIPTION
**Pull request by nikomatsakis**
We now always make fresh lifetimne parameters for all elided
lifetimes, whether they are in the inputs or outputs. But then
we generate `'_` in the case of elided lifetimes from the outputs.

Example:

```rust
async fn foo<'a>(x: &'a u32) -> &u32 { .. }
```

becomes

```rust
type Foo<'a, 'b> = impl Future<Output = &'b u32>;
fn foo<'a>(x: &'a u32) -> Foo<'a, '_>
```

Fixes #63388

### CODE REVIEW

File: src/test/ui/self/elision/ref-self-async.rs [hunk 1]
```diff
@@ -21,13 +21,14 @@ impl<T, P> Deref for Wrap<T, P> {
...
-    async fn ref_self(&self, f: &u32) -> &u32 {
-        //~^ ERROR missing lifetime specifier
-        //~| ERROR cannot infer an appropriate lifetime
+    async fn ref_self(&self, f: &u32) -> &u32 { //~ ERROR lifetime mismatch
         f
     }
 
     // Test using `&Self` explicitly:
+    //
+    // FIXME(#63388). This behavior *ought* to, but does not,
```
Comment (cramertj) [inline src/test/ui/self/elision/ref-self-async.rs]: ick, that's pretty gnarly, though I suppose backwards-compatible (since we just disallow it, rather than misinterpreting it)

File: src/librustc/hir/lowering.rs [hunk 2]
```diff
@@ -2529,12 +2529,57 @@ impl<'a> LoweringContext<'a> {
...
             // lifetimes based on the elided lifetime parameters introduced in the args.
-            let lt_replacement = get_elided_lt_replacement(
-                &self.lifetimes_to_define[lifetime_count_before_args..]
-            );
+            let lt_replacement = match implicit_self {
+                // If this is `async fn foo(&self, ...)`, then use the
+                // lifetime from `&self` (same for `&mut self`). This
+                // will always be the first one we define.
+                hir::ImplicitSelfKind::ImmRef | hir::ImplicitSelfKind::MutRef =>
+                    get_elided_lt_replacement(
```
Comment (cramertj) [inline src/librustc/hir/lowering.rs]: IMO this call is somewhat cleaner when inlined:

```rust
let (_span, param) = self.lifetimes_to_define[lifetime_count_before_args];
LtReplacement::Some(param)
```

File: src/test/ui/self/elision/ref-self-async.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/test/ui/self/elision/ref-self-async.rs]: Yeah...roughly what I was thinking. Not entirely sure this PR is the right thing to do. I'm just assuming that a more correct fix will take more time -- but I think we should definitely not just leave the code like this long term.

**Comment by cramertj** [comment]
r=me. This is... not wonderful, but it seems like a clear and simple fix for the most common case.

**Comment by nikomatsakis** [comment]
I'm seeing some test failures that suggest that my assumption that `&self` implies at least one lifetime is wrong =)

**Comment by Centril** [comment]
Could you please also include the test in #63388:
```rust
// check-pass

struct A;

impl A {
    async fn foo(&self, f: &u32) -> &A { self }
}
```
so we have some positive evidence that it works (and not just by "well the negative case errors in the way we expect")?

**Comment by nikomatsakis** [comment]
@cramertj this is ready for re-review

File: src/test/ui/self/arbitrary_self_types_pin_lifetime_impl_trait-async.nll.stderr [hunk 3]
```diff
@@ -0,0 +1,14 @@
+error: lifetime may not live long enough
```
Comment (jackh726) [inline src/test/ui/self/arbitrary_self_types_pin_lifetime_impl_trait-async.nll.stderr]: Is this file outdated? It doesn't match the actual file.

File: src/librustc/hir/lowering.rs [hunk 4]
```diff
@@ -2678,19 +2635,53 @@ impl<'a> LoweringContext<'a> {
...
+                GenericArg::Lifetime(hir::Lifetime {
+                    hir_id: self.next_id(),
+                    span,
+                    name: hir::LifetimeName::Implicit,
+                })
+            })
+        );
 
-        let opaque_ty_ref = hir::TyKind::Def(hir::ItemId { id: opaque_ty_id }, generic_args);
+        // Create the `Foo<...>` refernece itself. Note that the `type
```
Comment (jackh726) [inline src/librustc/hir/lowering.rs]:
```suggestion
        // Create the `Foo<...>` reference itself. Note that the `type
```

File: src/test/ui/self/elision/README.md [hunk 5]
```diff
@@ -61,15 +61,15 @@ Legends:
 | `struct-async.rs`| ✓ | ✓ | N/A |
 | `alias-async.rs`| ✓ | ✓ | N/A |
 | `assoc-async.rs`| ✓ | ✓ | N/A |
-| `ref-self-async.rs` | X | X | α ⟶ β + γ |
```
Comment (Centril) [inline src/test/ui/self/elision/README.md]: Nit (as noted on Zulip): The cases that have `α ⟶ β + γ` as opposed to `✓ ⟶ β + γ` should still (and are indeed actually) be `X` in the `Pass?` column since that is how the non-`async fn` tests behave.

File: src/librustc/hir/lowering.rs [hunk 6]
```diff
@@ -2622,9 +2570,18 @@ impl<'a> LoweringContext<'a> {
 
         self.allocate_hir_id_counter(opaque_ty_node_id);
 
+        let input_lifetimes_count = self.in_scope_lifetimes.len() + self.lifetimes_to_define.len();
```
Comment (cramertj) [inline src/librustc/hir/lowering.rs]: This is pretty clever and probably deserves a comment-- that `in_scope_lifetimes` contains all the non-elided lifetime names in scope, and `lifetimes_to_define` says how many lifetimes we have been paired with `CreateParameter`, so the last `lifetime_params.len() - (in_scope_lifetimes + lifetimes_to_define)` elements of `lifetime_params` are all elided lifetimes. Obviously the way I just worded it is probably even more confusing than just reading the code, but I think some explanation would be helpful.

**Comment by cramertj** [comment]
r=me with comment-- this seems better than the `Replace` hack that I introduced and is certainly more correct. I personally found it a bit more confusing to understand, but I think with a comment it's not too bad.

**Comment by nikomatsakis** [comment]
@cramertj is that comment roughly what you had in mind?

File: src/test/ui/self/elision/README.md (hunk 5 above)
Comment (nikomatsakis) [reply src/test/ui/self/elision/README.md]: I think I fixed this @Centril

**Comment by cramertj** [comment]
Looks great, thanks!

@bors r+

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/63515#issuecomment-520805965, @bors r- 
(`--bless --compare-mode=nll` should be enough to make it work.)
