### PR TITLE
Unused variable suggestions apply on all patterns.

### LINKED ISSUE #56685: Suggestion for unused variables can sometimes be incorrect
[First reported upstream](https://github.com/rust-lang/cargo/issues/6413) this code:

```rust
fn main() {
    enum E {
        A(i32,),
        B(i32,),
    }
    match E::A(1) {
        E::A(x) | E::B(x) => {}
    }
}
```

[when compiled yields a suggestion of](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7dc96eb9dd2818fcd4b14381a51cf65e)

```
warning: unused variable: `x`
 --> src/main.rs:7:14
  |
7 |         E::A(x) | E::B(x) => {}
  |              ^ help: consider using `_x` instead
  |
  = note: #[warn(unused_variables)] on by default

warning: variant is never constructed: `B`
 --> src/main.rs:4:9
  |
4 |         B(i32),
  |         ^^^^^^
  |
  = note: #[warn(dead_code)] on by default
```

but the suggestion is not correct! Both instances of the `x` binding need to be renamed in order for the code to be automatically fixed.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #56685.

This PR extends existing suggestions to prefix unused variable bindings in match arms with an underscore so that it applies to all patterns in a match arm.

r? @estebank 
cc @alexcrichton (since you filed the issue)

### CODE REVIEW

File: src/test/ui/issues/issue-56685.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+        C(i32, i32,),
+    }
+
+    let _ = match F::A(1, 2) {
+        F::A(x, y) | F::B(x, y) => { y },
+        //~^ ERROR unused variable: `x`
+        F::C(a, b) => { 3 }
+        //~^ ERROR unused variable: `a`
+        //~^^ ERROR unused variable: `b`
+    };
```
Comment (Centril) [inline src/test/ui/issues/issue-56685.rs]: I'd also exercise `if let` and `while let` since they too permit patterns as well as or-patterns.

File: src/librustc/middle/liveness.rs [hunk 2]
```diff
@@ -1455,12 +1456,29 @@ fn check_local<'a, 'tcx>(this: &mut Liveness<'a, 'tcx>, local: &'tcx hir::Local)
...
+    // the same bindings, and we also consider the first pattern to be the "authoritative" set of
+    // ids. However, we should take the spans of variables with the same name from the later
+    // patterns so the suggestions to prefix with underscores will apply to those too.
+    let mut vars: FxHashMap<String, (LiveNode, Variable, HirId, Vec<Span>)> = Default::default();
+
+    for pat in &arm.pats {
+        this.arm_pats_bindings(Some(&*pat), |this, ln, var, sp, id| {
+            let name = this.ir.variable_name(var);
+            vars.entry(name)
+                .and_modify(|(_, _, _, spans)| {
```
Comment (Centril) [inline src/librustc/middle/liveness.rs]:
```suggestion
                .and_modify(|(.., spans)| {
```
(a nit... feel free to ignore if you disagree...)

**Review by Centril — CHANGES_REQUESTED** [review]

File: src/test/ui/issues/issue-56685.stderr [hunk 3]
```diff
@@ -0,0 +1,40 @@
+error: unused variable: `x`
+  --> $DIR/issue-56685.rs:14:14
+   |
+LL |         E::A(x) | E::B(x) => {}
+   |              ^
```
Comment (estebank) [inline src/test/ui/issues/issue-56685.stderr]: Could we update the primary span to also point at all the individual bindings?

Comment (davidtwco) [reply src/test/ui/issues/issue-56685.stderr]: Fixed.

File: src/librustc/middle/liveness.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc/middle/liveness.rs]: Fixed.

File: src/test/ui/issues/issue-56685.rs (hunk 1 above)
Comment (davidtwco) [reply src/test/ui/issues/issue-56685.rs]: Added these.

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
@estebank Bors just likes me more =P

**Comment by Centril** [comment]
Rollup fairness, @bors p=1

**Comment by Centril** [comment]
Failed in rollup, https://github.com/rust-lang/rust/pull/57930#issuecomment-457886919

@bors r- retry

**Comment by Centril** [comment]
Failed in rollup, https://github.com/rust-lang/rust/pull/57938#issuecomment-457969173.

@bors r- retry

**Comment by estebank** [comment]
```

failures:
---- [ui] ui\lint\issue-47390-unused-variable-in-struct-pattern.rs stdout ----
diff of stderr:
29	LL |     let (mut var, unused_var) = (1, 2);
30	   |                   ^^^^^^^^^^ help: consider prefixing with an underscore: `_unused_var`
31	
-	warning: unused variable: `corridors_of_light`
-	  --> $DIR/issue-47390-unused-variable-in-struct-pattern.rs:37:26
-	   |
-	LL |     if let SoulHistory { corridors_of_light,
-	   |                          ^^^^^^^^^^^^^^^^^^ help: try ignoring the field: `corridors_of_light: _`
-	
38	warning: variable `hours_are_suns` is assigned to, but never used
39	  --> $DIR/issue-47390-unused-variable-in-struct-pattern.rs:38:30
40	   |
42	   |                              ^^^^^^^^^^^^^^
43	   |
44	   = note: consider using `_hours_are_suns` instead
+	
+	warning: unused variable: `corridors_of_light`
+	  --> $DIR/issue-47390-unused-variable-in-struct-pattern.rs:37:26
+	   |
+	LL |     if let SoulHistory { corridors_of_light,
+	   |                          ^^^^^^^^^^^^^^^^^^ help: try ignoring the field: `corridors_of_light: _`
45	
46	warning: value assigned to `hours_are_suns` is never read
47	  --> $DIR/issue-47390-unused-variable-in-struct-pattern.rs:40:9
The actual stderr differed from the expected stderr.
```

**Comment by Centril** [comment]
@estebank  `--bless` your heart ;)
