### PR TITLE
Fix never-type rvalue ICE

### LINKED ISSUE #43061: Rust 1.20.0-nightly ICE with never_type: Broken MIR
The following error results from dereferencing a `*const !` as in this code: [https://is.gd/SsSDiG](https://is.gd/SsSDiG)

```
rustc 1.20.0-nightly (734c83642 2017-07-03)
error: internal compiler error: broken MIR (_3 = ()): bad assignment (! = ()): Sorts(ExpectedFound { expected: !, found: () })
 --> <anon>:4:5
  |
4 | /     unsafe {
5 | |         *x;
6 | |     }
  | |_____^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (734c83642 2017-07-03) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:426:8
```

### PR DESCRIPTION
**Pull request by varkor**
This fixes #43061.
r? @nikomatsakis

A small post-mortem as a follow-up to our investigations in https://github.com/rust-lang/rust/pull/47291:
The problem as I understand it is that when `NeverToAny` coercions are made, the expression/statement that is coerced may be enclosed in a block. In our case, the statement `x;` was being transformed to something like: `NeverToAny( {x;} )`. Then, `NeverToAny` is transformed into an expression:
https://github.com/rust-lang/rust/blob/000fbbc9b8f88adc6a417f1caef41161f104250f/src/librustc_mir/build/expr/into.rs#L52-L59
Which ends up calling `ast_block_stmts` on the block `{x;}`, which triggers this condition:
https://github.com/rust-lang/rust/blob/000fbbc9b8f88adc6a417f1caef41161f104250f/src/librustc_mir/build/block.rs#L141-L147
In our case, there is no return expression, so `push_assign_unit` is called. But the block has already been recorded as _diverging_, meaning the result of the block will be assigned to a location of type `!`, rather than `()`. This causes the MIR error.
I'm assuming the `NeverToAny` coercion code is doing what it's supposed to (there don't seem to be any other problems), so fixing the issue simply consists of checking that the destination for the return value actually _is_ supposed to be a unit. (If no return value is given, the only other possible type for the return value is `!`, which can just be ignored, as it will be unreachable anyway.)

I checked the other cases of `push_assign_unit`, and it didn't look like they could be affected by the divergence issue (blocks are kind of special-cased in this regard as far as I can tell), so this should be sufficient to fix the issue.

### CODE REVIEW

File: src/librustc_mir/build/block.rs [hunk 1]
```diff
@@ -143,7 +143,13 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
         if let Some(expr) = expr {
             unpack!(block = this.into(destination, block, expr));
         } else {
-            this.cfg.push_assign_unit(block, source_info, destination);
+            let tcx = this.hir.tcx();
+            let ty = destination.ty(&this.local_decls, tcx).to_ty(tcx);
+            if ty.is_nil() {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/block.rs]: Just to be sure I understand, the premise here is that the type is either `()` or else the block must diverge, since any other type would have yielded a compilation error?

Comment (varkor) [reply src/librustc_mir/build/block.rs]: Yeah, with the current semantics, any other type should be impossible (i.e. any other type must be explicit and go through the `Some(expr)` branch instead) , because the only implicit return types are `()` and `!`.

Comment (nikomatsakis) [reply src/librustc_mir/build/block.rs]: Could we have a comment? That's a bit non-obvious. (If the code were like `if ty.is_never()` it'd be more obvious...)

Comment (varkor) [reply src/librustc_mir/build/block.rs]: Sure. (The reason I opted for `ty.is_nil()` rather than `ty.is_never()` here is because it seemed less contextual — it's always true that we only want to assign a unit if the type is unit. One alternative to make it absolutely explicit would be to check for `!ty.is_never()` in an `else` clause and throw a warning there that it should be impossible, but this seems like overkill.)
