### PR TITLE
Fix the example in document for WaitTimeoutResult::timed_out

### LINKED ISSUE #110045: Documentation mismatch for WaitTimeoutResult::timed_out
### Location

Standard library documentation for  `WaitTimeoutResult::timed_out` 
(https://doc.rust-lang.org/std/sync/struct.WaitTimeoutResult.html#method.timed_out)

### Summary

The example of the document does not mention the timed_out method, it is not clear how to use it.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #110045

### CODE REVIEW

File: library/std/src/sync/condvar.rs [hunk 1]
```diff
@@ -49,14 +49,12 @@ impl WaitTimeoutResult {
...
     ///     // Let's put a timeout on the condvar's wait.
-    ///     let result = cvar.wait_timeout(started, Duration::from_millis(10)).unwrap();
-    ///     // 10 milliseconds have passed, or maybe the value changed!
-    ///     started = result.0;
-    ///     if *started == true {
-    ///         // We received the notification and the value has been updated, we can leave.
+    ///     let result = cvar.wait_timeout(lock.lock().unwrap(), Duration::from_millis(10)).unwrap();
+    ///     // 10 milliseconds have passed
+    ///     if result.1.timed_out() {
+    ///         //timeout now and we can leave.
```
Comment (JohnTitor) [inline library/std/src/sync/condvar.rs:57]: nit:

```suggestion
    ///     // 10 milliseconds have passed.
    ///     if result.1.timed_out() {
    ///         // timed out now and we can leave.
```

**Review by JohnTitor — APPROVED** [review]

**Comment by chenyukang** [comment]
r? libs

**Comment by chenyukang** [comment]
r? libs

File: library/std/src/sync/condvar.rs [hunk 2]
```diff
@@ -21,11 +21,11 @@ impl WaitTimeoutResult {
     ///
     /// # Examples
     ///
-    /// This example spawns a thread which will update the boolean value and
-    /// then wait 100 milliseconds before notifying the condvar.
+    /// This example spawns a thread which will sleep 20 milliseconds before
+    /// updating the condvar and then notify.
```
Comment (workingjubilee) [inline library/std/src/sync/condvar.rs:25]: Where you're going seems like a good direction but currently it ends up at... "and then notify"... notify what?

File: library/std/src/sync/condvar.rs [hunk 3]
```diff
@@ -21,11 +21,11 @@ impl WaitTimeoutResult {
...
     ///
-    /// The main thread will wait with a timeout on the condvar and then leave
-    /// once the boolean has been updated and notified.
+    /// The main thread will wait with a timeout with only 10 milliseconds on the condvar
+    /// and will leave once timeout
```
Comment (workingjubilee) [inline library/std/src/sync/condvar.rs:28]: "with a timeout with"... This could be constructed more like "with a 10 millisecond timeout".

And what is the thread "leaving"? The loop, right? But it could be clearer.

**Comment by workingjubilee** [comment]
@rustbot author
r? workingjubilee

File: library/std/src/sync/condvar.rs [hunk 4]
```diff
@@ -21,11 +21,11 @@ impl WaitTimeoutResult {
     ///
     /// # Examples
     ///
-    /// This example spawns a thread which will update the boolean value and
-    /// then wait 100 milliseconds before notifying the condvar.
+    /// This example spawns a thread which will sleep 20 milliseconds before
+    /// updating boolean value and then notify the condvar.
```
Comment (workingjubilee) [inline library/std/src/sync/condvar.rs:25]:
```suggestion
    /// updating a boolean value and then notifying the condvar.
```

File: library/std/src/sync/condvar.rs [hunk 5]
```diff
@@ -21,11 +21,11 @@ impl WaitTimeoutResult {
...
     ///
-    /// The main thread will wait with a timeout on the condvar and then leave
-    /// once the boolean has been updated and notified.
+    /// The main thread will wait with a 10 millisecond timeout on the condvar
+    /// and will leave the loop once timeout.
```
Comment (workingjubilee) [inline library/std/src/sync/condvar.rs:28]:
```suggestion
    /// and will leave the loop upon timeout.
```

**Review by workingjubilee — COMMENTED** [review]
Much better! Just a little bit more?

**Comment by workingjubilee** [comment]
Side thought: It'd be _cute_ if this example showed that the condvar's timeout and notification status can differ, but that's not a requirement. This still addresses the concern in question.

File: library/std/src/sync/condvar.rs (hunk 5 above)
Comment (chenyukang) [reply library/std/src/sync/condvar.rs]: Fixed, thanks!
