### PR TITLE
fix: don't suggest similar method when unstable

### LINKED ISSUE #109177: rustc suggests unstable library method on stable
### Code

```Rust
fn main() {
    let v = vec![1,2,3,4];
    for pair in v.chunk(2) {
        println!("{}, {}", pair[0], pair[1]);
    }
}
```

### Current output

```Shell
error[E0599]: no method named `chunk` found for struct `Vec<{integer}>` in the current scope
 --> src/main.rs:3:19
  |
3 |     for pair in v.chunk(2) {
  |                   ^^^^^ help: there is a method with a similar name: `as_chunks`

For more information about this error, try `rustc --explain E0599`.
```

### Desired output

```Shell
error[E0599]: no method named `chunk` found for struct `Vec<{integer}>` in the current scope
 --> src/main.rs:3:19
  |
3 |     for pair in v.chunk(2) {
  |                   ^^^^^ help: there is a method with a similar name: `chunks`

For more information about this error, try `rustc --explain E0599`.
```

### Rationale and extra context

It would be more helpful to suggest the `chunks` method for the typo rather than a nightly-only symbol which isn't actually available.

1. Following the suggestion doesn't work.
2. The `chunks()` method is actually available on a `std::slice`.
3. The `chunks()` method has been stable since 1.0.0.
4. I had trouble noticing the difference between `.chunk()` and `.chuncks()` and could have used the compiler's help.

### Other cases

_No response_

### Anything else?

Reproduced with 1.68.0 stable and 1.70 nightly.

### PR DESCRIPTION
**Pull request by Ezrashaw**
Fixes #109177

Don't display typo suggestions for unstable things, unless the feature flag is enabled.

AFAIK, there are two places this occurs:
- `rustc_resolve`: before type checking, effectively just `FnCtxt::Free`.
- `rustc_hir_typck`: during type checking, for `FnCtxt::Assoc(..)`s.

The linked issue is about the latter, obviously the issue is applicable to both.

r? @estebank

### CODE REVIEW

**Comment by Ezrashaw** [comment]
Big problems with the `rustc_resolve` half, not entirely sure why. I'll have to deal with this tomorrow.

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 1]
```diff
@@ -1027,6 +1027,15 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
                     true
                 }
             })
+            // ensure that we don't suggest unstable methods
+            .filter(|candidate| {
+                // note that `DUMMY_SP` is ok here because it is only used for
+                // suggestions and macro stuff which isn't applicable here.
+                !matches!(
+                    self.tcx.eval_stability(candidate.item.def_id, None, DUMMY_SP, None),
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1035]: I think this call might be introducing a cycle, which manifests as an `.unwrap()` ICE. Can you check if calling `tcx.lookup_stability(def_id)` also hits it?

**Comment by Ezrashaw** [comment]
@estebank The offending code is in `compiler/rustc_middle/src/middle/stability.rs:417`:
```rust
let is_staged_api = self.lookup_stability(def_id.krate.as_def_id()).is_some();
if !is_staged_api {
    return EvalResult::Allow;
}
```
The `lookup_stability` query requires it's `DefId` arg to be a `LocalDefId`, however it caches stuff to disk and I think that's where we are getting stuck; a query is not cached for a non-local crate and then it's trying to create that information and recursing. (I'm newish to the compiler and thus have a *very* loose grasp on the query system)

**Comment by estebank** [comment]
Let's land the typeck part of this for now and keep investigating the resolve version. It's likely we'll have to add some tracking to `Resolve` for local stabilities and check that. In the meantime, only unstable methods coming from the crate the user wrote will be suggested, which means the author would have enough context to deal with the situation.

**Comment by Ezrashaw** [comment]
@estebank Sure, I'm happy to land just the typeck part, I'll be looking into the resolve part a bit (not sure the fix is easy).
