### PR TITLE
Handle macro invocation in attribute during parse

### LINKED ISSUE #146325: `#[deprecated(note = concat!("a", "b"))]` suggestion gets nowhere
### Code

```Rust
#[deprecated(note = concat!("a", "b"))]
struct X;
```

### Current output

```Shell
error: expected a literal (`1u8`, `1.0f32`, `"string"`, etc.) here, found `concat`
 --> src/main.rs:1:21
  |
1 | #[deprecated(note = concat!("a", "b"))]
  |                     ^^^^^^
  |
help: surround the identifier with quotation marks to make it into a string literal
  |
1 | #[deprecated(note = "concat"!("a", "b"))]
  |                     +      +
```

### Desired output

```Shell
error: expected a literal (`1u8`, `1.0f32`, `"string"`, etc.) here, found macro invocation
help: macros cannot be used here
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.91.0-nightly (1ed3cd703 2025-09-06)
binary: rustc
commit-hash: 1ed3cd7030718935a5c5e5c8f6581f36d8be179f
commit-date: 2025-09-06
host: x86_64-unknown-linux-gnu
release: 1.91.0-nightly
LLVM version: 21.1.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
```
error: expected a literal (`1u8`, `1.0f32`, `"string"`, etc.) here, found macro `concat`
  --> $DIR/macro-in-attribute.rs:4:21
   |
LL | #[deprecated(note = concat!("a", "b"))]
   |                     ^^^^^^^^^^^^^^^^^ macros are not allowed here
```

Fix rust-lang/rust#146325.

### CODE REVIEW

File: compiler/rustc_attr_parsing/src/parser.rs [hunk 1]
```diff
@@ -484,20 +485,37 @@ impl<'a, 'sess> MetaItemListParserContext<'a, 'sess> {
         if self.parser.prev_token == token::Eq
             && let token::Ident(..) = self.parser.token.kind
         {
-            let before = self.parser.token.span.shrink_to_lo();
-            while let token::Ident(..) = self.parser.token.kind {
-                self.parser.bump();
+            if self.parser.look_ahead(1, |t| matches!(t.kind, token::TokenKind::Bang)) {
```
Comment (mu001999) [inline compiler/rustc_attr_parsing/src/parser.rs]: What if we meet:
```rust
#[deprecated(note = a!=b)]
struct X;
```

Comment (estebank) [reply compiler/rustc_attr_parsing/src/parser.rs]: Silly me, I organized things thinking of only parsing a macro and not a statement. I think that `parse_stmt_without_recovery` will fail because of a lack of `;`, but I can look at the `stmt.kind` instead. It should give the error with no note or structured suggestion.

Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/parser.rs]: I'll wait with further review for this

Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/parser.rs]: generally looking good though :)

Comment (estebank) [reply compiler/rustc_attr_parsing/src/parser.rs]: Addressed

File: tests/ui/parser/attribute/attr-bad-meta-4.stderr [hunk 2]
```diff
@@ -1,8 +1,8 @@
-error: expected a literal (`1u8`, `1.0f32`, `"string"`, etc.) here, found `-`
+error: expected a literal (`1u8`, `1.0f32`, `"string"`, etc.) here, found expression
   --> $DIR/attr-bad-meta-4.rs:11:17
    |
 LL | #[cfg(feature = -1)]
-   |                 ^
+   |                 ^^ expressions are not allowed here
```
Comment (mu001999) [inline tests/ui/parser/attribute/attr-bad-meta-4.stderr:5]: literals are also expressions, should this desc be more precise? like non-literal expression

File: compiler/rustc_ast/src/ast.rs [hunk 3]
```diff
@@ -1235,6 +1235,19 @@ pub enum StmtKind {
...
 
+impl StmtKind {
+    pub fn descr(&self) -> &'static str {
+        match self {
+            StmtKind::Let(_) => "local",
+            StmtKind::Item(_) => "item",
+            StmtKind::Expr(_) => "expression",
+            StmtKind::Semi(_) => "statement",
+            StmtKind::Empty => "semicolon",
+            StmtKind::MacCall(_) => "macro",
```
Comment (mu001999) [inline compiler/rustc_ast/src/ast.rs]: `"macro call"` intead of `"macro"`?

File: tests/ui/parser/attribute/attr-bad-meta-4.stderr (hunk 2 above)
Comment (jdonszelmann) [reply tests/ui/parser/attribute/attr-bad-meta-4.stderr:5]: I think there are many other diagnostics talking about literals vs expressions. I guess the text should be "complex expressions" or "non-literal expressions" which doesn't feel better?

File: tests/ui/parser/attribute/attr-bad-meta-4.stderr [hunk 4]
```diff
@@ -1,8 +1,8 @@
...
    |
 help: negative numbers are not literals, try removing the `-` sign
```
Comment (jdonszelmann) [inline tests/ui/parser/attribute/attr-bad-meta-4.stderr:7]: @mu001999 the help here clarifies a lot I think

File: compiler/rustc_ast/src/ast.rs (hunk 3 above)
Comment (jdonszelmann) [reply compiler/rustc_ast/src/ast.rs]: I agree, macro calls feel more appropriate

**Review by mu001999 — APPROVED** [review]

**Comment by Kobzol** [comment]
@rust-timer build baf3ab6a192292c14b4e9d83e9b01ca038e61d9c

Trying if this regressed perf. in https://github.com/rust-lang/rust/pull/149818 (although quite unlikely).
