### PR TITLE
Fix #54822 and associated faulty tests

### LINKED ISSUE #54822: Erroneous compilation failure with associated constant
EDIT: To anyone coming to this from the This Week in Rust CFP: This is currently an unsolved issue, so the first step to tackling this is to figure out where the bug is! That alone would be a huge help. If you want to implement a fix, that'd be great too :)

=====

The following program should compile on stable, but doesn't:

```rust
trait ConstDefault {
    const Default: Self;
}

trait Foo: Sized {}

trait FooExt: Foo {
    type T: ConstDefault;
}

trait Bar<F: FooExt> {
    const T: F::T;
}

impl<F: FooExt> Bar<F> for () {
    const T: F::T = <F::T as ConstDefault>::Default;
}
```

It [fails to compile](https://play.rust-lang.org/?gist=c63d74102061b3112ab08cc8669801e4&version=stable&mode=debug&edition=2015) with the following error:

```text
error[E0277]: the trait bound `F: FooExt` is not satisfied
  --> src/lib.rs:16:5
   |
16 |     const T: F::T = <F::T as ConstDefault>::Default;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FooExt` is not implemented for `F`
   |
   = help: consider adding a `where F: FooExt` bound
```

Note that if we amend as either of the following, [it works](https://play.rust-lang.org/?gist=dfecdceea6b470631e786a1f44bad1c0&version=stable&mode=debug&edition=2015) (credit to @ezrosent for figuring this out):

```rust
trait Bar<T: ConstDefault, F: FooExt<T=T>> {
    const C: T;
}

impl<T: ConstDefault, F: FooExt<T=T>> Bar<T, F> for () {
    const C: T = F::T::Default;
    const C: T = T::Default;
}
```

### PR DESCRIPTION
**Pull request by kyren**
Type checking associated constants can require trait bounds, but an empty
parameter environment was provided to the trait solver.  Providing an
appropriate parameter environment seems to fix #54822 and also make one of the
cases in src/test/ui/nll/trait-associated-constant.rs that should compile
successfully do so.  It also (slightly) improves the error message in
src/test/ui/associated-const/associated-const-generic-obligations.rs

### CODE REVIEW

**Comment by kyren** [comment]
**This PR is highly likely to be wrong**, there's an enormous amount of subtlety in type checking that I don't yet understand, but it was suggested that I start with a PR so it could be discussed.

I haven't checked yet, but if this ever previously worked, it probably stopped working around #42189.

File: src/test/ui/nll/trait-associated-constant.rs [hunk 1]
```diff
@@ -26,7 +26,6 @@ struct FailStruct2 { }
 
 impl<'a: 'b, 'b> Anything<'a, 'b> for FailStruct2 {
```
Comment (varkor) [inline src/test/ui/nll/trait-associated-constant.rs]: It probably makes sense to rename this to `SuccessStruct` or something now :)

**Comment by varkor** [comment]
This change looks completely sensible to me. In fact, I'm confused at the second test case (i.e. `FailStruct2` for `trait-associated-constant.rs`, which seems like it should never have been included in the test (or otherwise, it should have had an associated `FIXME`).

If you could just change the struct name in the test to make it less confusing, everything looks good!

**Review by varkor — APPROVED** [review]

**Comment by kyren** [comment]
How's that, would you like me to collapse it into a single commit?

**Comment by varkor** [comment]
That's great — thank you for looking into this issue!

@bors r+ rollup
