### PR TITLE
Validate error patterns and error annotation in ui tests when present

### LINKED ISSUE #56277: compiletest: `//~ ERROR` annotations are ignored in `compile-pass` tests
Reproduction:
```rust
// compile-pass

fn main() {} //~ ERROR any misleading message
```
The test passes despite the incorrect `//~ ERROR` annotation.

Tests often have these annotations while they are WIP, but then everything is good, the test passes and is marked as `// compile-pass`, but stray `//~ ERROR` annotations may remain confusing the reader.

### PR DESCRIPTION
**Pull request by tmiasko**
Previously, when compilation succeeded, neither error patterns nor error
annotation would be validated. Additionally, when compilation failed,
only error patterns would be validated if both error patterns and error
annotation were present.

Now both error patterns and error annotation are validated when present,
regardless of compilation status. Furthermore, for test that should run,
the error patterns are matched against executable output, which is what
some of tests already expect to happen, and when #65506 is merged even
more ui tests will.

Fixes #56277

### CODE REVIEW

**Comment by petrochenkov** [comment]
Thanks a lot.
This PR fixes the issue #56277.

There's a similar (but opposite) issue (#55596) about `//~ ERROR` annotations not being required in UI tests with errors, perhaps you can look into it as well?

File: src/tools/compiletest/src/runtest.rs [hunk 1]
```diff
@@ -3137,21 +3137,24 @@ impl<'test> TestCx<'test> {
                     self.fatal_proc_rec("test run succeeded!", &proc_res);
                 }
             }
+            if !self.props.error_patterns.is_empty() {
+                // "// error-pattern" comments
+                self.check_error_patterns(&proc_res.stderr, &proc_res);
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs]: It's a bit weird that this is checked in two places - first in `should_run` and then in `!should_run` below.
I think, we should run `check_expected_errors` and `check_error_patterns` together under the same conditions.

Comment (petrochenkov) [reply src/tools/compiletest/src/runtest.rs]: Also, could you try to remove the `!explicit && self.config.compare_mode.is_none()` condition as well?
I'm not sure what will happen, but perhaps we can check annotations in those modes as well?

Comment (tmiasko) [reply src/tools/compiletest/src/runtest.rs]: After fixing the first bug, i.e., no validation being performed when
compilation succeeds, some test cases started to fail because they expected
error patterns to be matched against program output. 

To address that issue, in the should_run case the error patterns are matched
against the program output, and otherwise the errors patterns are matched
against compiler output as before. This is why they are checked in two places.

Comment (tmiasko) [reply src/tools/compiletest/src/runtest.rs]: The `explicit` tests are those that use `--error-format` flag. They are
generally incompatible with error annotations, since there is only json error
parser. I also got two failures after removing this check, on `missing-type.rs`
and `unused_parens_remove_json_suggestion.rs`.

I am not familiar with compare mode, so I would rather not touch
`self.config.compare_mode.is_none()` condition either.

Comment (petrochenkov) [reply src/tools/compiletest/src/runtest.rs]: >some test cases started to fail because they expected
error patterns to be matched against program output.

I see.
I'm pretty sure that was a misuse of the `// error-pattern` annotation.
We have a separate annotation for checking the runtime output - `// check-run-results`.

File: src/tools/compiletest/src/runtest.rs [hunk 2]
```diff
@@ -3137,21 +3137,24 @@ impl<'test> TestCx<'test> {
...
-                    self.check_error_patterns(&proc_res.stderr, &proc_res);
-                } else {
-                    // "//~ERROR comments"
-                    self.check_expected_errors(expected_errors, &proc_res);
-                }
+            if !self.should_run() && !self.props.error_patterns.is_empty() {
+                // "// error-pattern" comments
+                self.check_error_patterns(&proc_res.stderr, &proc_res);
+            }
+            if !expected_errors.is_empty() {
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs]: Looks like the removal of this condition should fix https://github.com/rust-lang/rust/issues/55596.

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (tmiasko) [reply src/tools/compiletest/src/runtest.rs]: Indeed, right now there are only handful of test in ui that use error-pattern
for matching executable results, so they could be presumably migrated to use
check-run-results.

At the same time, the changes are party motivated as help with #65506 which
moves run-fails tests to ui. For those tests such use of error-pattern is quite
typical.

Which is why I think we should allow for such use of error-pattern, at least
until all those tests are migrated if check-run-results is preferred variant.

File: src/tools/compiletest/src/runtest.rs (hunk 2 above)
Comment (tmiasko) [reply src/tools/compiletest/src/runtest.rs]: The fallout from making annotations for errors and warnings mandatory is
quite substantial, so I would rather not fix that issue in this PR.

Comment (petrochenkov) [reply src/tools/compiletest/src/runtest.rs]: Ok.

File: src/tools/compiletest/src/runtest.rs (hunk 1 above)
Comment (petrochenkov) [reply src/tools/compiletest/src/runtest.rs]: @tmiasko
Could you make an issue for migrating run-fail tests to `// check-run-results` and restoring the compile-time meaning of `// error-pattern` in them?

**Comment by tmiasko** [comment]
Failed in rollup due to a target dependent error message, which didn't match
the error annotation (previously silently ignored because test case also
contains error patterns). Pushed a fix that removes target dependent part of
the message.

**Comment by petrochenkov** [comment]
One more test needs to be updated.

**Comment by tmiasko** [comment]
Another target specific failure, this time on `wasm32-unknown-unknown`.

Question is why those tests used to work when they were in `run-fail`?
Apparently the answer is that `run-fail` tests are not run for wasm target
(which I suppose makes sense if panic is unsupported):
```
ENV WASM_TARGETS=wasm32-unknown-unknown
ENV WASM_SCRIPT python2.7 /checkout/x.py test --target $WASM_TARGETS \
  src/test/run-make \
  src/test/ui \
  src/test/compile-fail \
  src/test/mir-opt \
  src/test/codegen-units \
  src/libcore
```

I think `check-pass` would be fine those particular tests, and changed them
accordingly. Let me know if would prefer something else, .e.g., ignore test on
wasm.

**Comment by petrochenkov** [comment]
Yeah, that test looks like check-pass.
@bors r+

**Comment by petrochenkov** [comment]
NLL versions of tests can be run by adding `--compare-mode nll` to the `x.py` command line.

**Comment by tmiasko** [comment]
Amended the commit changing `continue-after-missing-main.rs` to additionally update nll compare output.
