### PR TITLE
Only apply `no_mangle_const_items`'s suggestion to plain const items

### LINKED ISSUE #149511: `no_mangle_const_items`: `const` -> `pub static` suggestion causes syntax error
Using the following flags

`--force-warn no_mangle_const_items`

this code:

```rust
//! Test that nonsense bounds prevent consts from being evaluated at all.
//@ check-pass

#![feature(generic_const_items)]
#![allow(incomplete_features)]
trait Trait {
    const ASSOC: u32;
}

// rustfmt eats the where bound
#[unsafe(no_mangle)]
const ASSOC: u32 = <&'static ()>::ASSOC where for<'a> &'a (): Trait;

fn main() {}

```

caused the following diagnostics:

```
    Checking _23d74b92f51a14cefeb40f5cad7a397b39971b5d v0.1.0 (/tmp/icemaker_global_tempdir.fzTw1TOrsbiL/icemaker_clippyfix_tempdir.xP3b20GgdVBR/_23d74b92f51a14cefeb40f5cad7a397b39971b5d)
warning: const items should never be `#[no_mangle]`
  --> src/main.rs:12:1
   |
12 | const ASSOC: u32 = <&'static ()>::ASSOC where for<'a> &'a (): Trait;
   | -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | help: try a static value: `pub static`
   |
   = note: requested on the command line with `--force-warn no-mangle-const-items`

warning: `_23d74b92f51a14cefeb40f5cad7a397b39971b5d` (bin "_23d74b92f51a14cefeb40f5cad7a397b39971b5d") generated 1 warning (run `cargo clippy --fix --bin "_23d74b92f51a14cefeb40f5cad7a397b39971b5d" -p _23d74b92f51a14cefeb40f5cad7a397b39971b5d` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s

```

However after applying these diagnostics, the resulting code:

```rust
//! Test that nonsense bounds prevent consts from being evaluated at all.
//@ check-pass

#![feature(generic_const_items)]
#![allow(incomplete_features)]
trait Trait {
    const ASSOC: u32;
}

// rustfmt eats the where bound
#[unsafe(no_mangle)]
pub static ASSOC: u32 = <&'static ()>::ASSOC where for<'a> &'a (): Trait;

fn main() {}

```
no longer compiled:

```
    Checking _23d74b92f51a14cefeb40f5cad7a397b39971b5d v0.1.0 (/tmp/icemaker_global_tempdir.fzTw1TOrsbiL/icemaker_clippyfix_tempdir.xP3b20GgdVBR/_23d74b92f51a14cefeb40f5cad7a397b39971b5d)
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, or an operator, found keyword `where`
  --> src/main.rs:12:46
   |
12 | pub static ASSOC: u32 = <&'static ()>::ASSOC where for<'a> &'a (): Trait;
   |                                              ^^^^^ expected one of 7 possible tokens

error: could not compile `_23d74b92f51a14cefeb40f5cad7a397b39971b5d` (bin "_23d74b92f51a14cefeb40f5cad7a397b39971b5d") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `_23d74b92f51a14cefeb40f5cad7a397b39971b5d` (bin "_23d74b92f51a14cefeb40f5cad7a397b39971b5d" test) due to 1 previous error

```

Version:
```
rustc 1.93.0-nightly (f40a70d2b 2025-11-30)
binary: rustc
commit-hash: f40a70d2bcd830a4f1f8c7ca1a7f93f1d9d703d6
commit-date: 2025-11-30
host: x86_64-unknown-linux-gnu
release: 1.93.0-nightly
LLVM version: 21.1.5

```

### PR DESCRIPTION
**Pull request by reddevilmidzy**
resolve: rust-lang/rust#149511

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -997,8 +997,11 @@ impl<'tcx> LateLintPass<'tcx> for InvalidNoMangleItems {
...
-            hir::ItemKind::Const(..) => {
-                if find_attr!(attrs, AttributeKind::NoMangle(..)) {
+            hir::ItemKind::Const(_, generics, ..) => {
+                if find_attr!(attrs, AttributeKind::NoMangle(..))
+                    && generics.params.is_empty
+                    && !generics.has_where_clause_predicates
+                {
                     // account for "pub const" (#45562)
                     let start = cx
                         .tcx
```
Comment (fmease) [inline compiler/rustc_lint/src/builtin.rs]: (unrelated) This `cx.tcx.sess.source_map().span_to_snippet(it.span).map(|snippet| snippet.find("const").unwrap_or(0)).unwrap_or(0) as u32; let suggestion = it.span.with_hi(BytePos(it.span.lo().0 + start + 5));` can probably be made more robust (accounting for source code comments for example) & simplified by changing it to `let suggestion = item.vis_span.to(ident.span);` (at least I think that's what it's computing).

File: compiler/rustc_lint/src/builtin.rs [hunk 2]
```diff
@@ -997,8 +997,11 @@ impl<'tcx> LateLintPass<'tcx> for InvalidNoMangleItems {
                     self.check_no_mangle_on_generic_fn(cx, attr_span, it.owner_id.def_id);
                 }
             }
-            hir::ItemKind::Const(..) => {
-                if find_attr!(attrs, AttributeKind::NoMangle(..)) {
```
Comment (fmease) [inline compiler/rustc_lint/src/builtin.rs:1001]: We still want to emit the lint, we just want to suppress the suggestion. So make the suggestion in `BuiltinConstNoMangle` `Option`al and set it to `None` if there are params or a where-clause.

**Review by fmease — CHANGES_REQUESTED** [review]

File: tests/ui/consts/const-with-nonsense-where-bound.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
+//! Test that nonsense bounds prevent consts from being evaluated at all.
```
Comment (bjorn3) [inline tests/ui/consts/const-with-nonsense-where-bound.rs]: This is not what this test file tests. Also please give the test a better name and location.

File: compiler/rustc_lint/src/builtin.rs (hunk 2 above)
Comment (reddevilmidzy) [reply compiler/rustc_lint/src/builtin.rs:1001]: Yes! I fixed it

File: tests/ui/consts/const-with-nonsense-where-bound.rs (hunk 3 above)
Comment (reddevilmidzy) [reply tests/ui/consts/const-with-nonsense-where-bound.rs]: Moved tests to `tests\ui\lint\force-warn\no-mangle-const-suggestion-suppressed.rs`

File: compiler/rustc_lint/src/builtin.rs (hunk 1 above)
Comment (reddevilmidzy) [reply compiler/rustc_lint/src/builtin.rs]: I tried making the changes you suggested, but when I only used `it.vis_span.to(ident.span);` , the variable names in the `tests\ui\lint\suggestions.rs` disappeared. like
```
-	    #[no_mangle] pub static VETAR: bool = true;
+	    #[no_mangle] pub static: bool = true;
```
 So I added `shrink_to_lo()` and added a space after "pub static." This caused the cursors (^) in other tests to be pushed back one by one.

Is it okay to push them one by one like this? Or is there another way?

**Review by reddevilmidzy — COMMENTED** [review]
Thanks for the review :)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149544/a4cfac7093a1c1c7fbdb6bc75d6b6dc4d385fc69..708732f9fd14265ffadd39819e9d596dc3350c2a)*

File: tests/ui/lint/force-warn/no-mangle-const-suggestion-suppressed.rs [hunk 4]
```diff
@@ -0,0 +1,21 @@
+//! Ensure the `no_mangle_const_items` lint triggers but does not offer a `pub static`
+//! suggestion for consts that have generics or a where-clause.
+//! regression test for <https://github.com/rust-lang/rust/issues/149511>
+//@ check-pass
+//@ compile-flags: --force-warn no_mangle_const_items
```
Comment (bjorn3) [inline tests/ui/lint/force-warn/no-mangle-const-suggestion-suppressed.rs]: Please use `#![deny(no_mangle_const_items)]` instead.

File: tests/ui/lint/lint-unexported-no-mangle.stderr [hunk 5]
```diff
@@ -31,7 +31,7 @@ error: const items should never be `#[no_mangle]`
   --> $DIR/lint-unexported-no-mangle.rs:9:1
    |
 LL | const FOO: u64 = 1;
-   | -----^^^^^^^^^^^^^^
+   | ------^^^^^^^^^^^^^
```
Comment (bjorn3) [inline tests/ui/lint/lint-unexported-no-mangle.stderr:34]: I think this breaks the suggestion. I think applying the suggestion will now result in `pub staticFOO: u64 = 1;` with the space missing.

File: compiler/rustc_lint/src/builtin.rs [hunk 6]
```diff
@@ -997,18 +997,15 @@ impl<'tcx> LateLintPass<'tcx> for InvalidNoMangleItems {
...
-                        .source_map()
-                        .span_to_snippet(it.span)
-                        .map(|snippet| snippet.find("const").unwrap_or(0))
-                        .unwrap_or(0) as u32;
-                    // `const` is 5 chars
-                    let suggestion = it.span.with_hi(BytePos(it.span.lo().0 + start + 5));
+                    let suggestion =
+                        if generics.params.is_empty() && !generics.has_where_clause_predicates {
+                            // account for "pub const" (#45562)
+                            Some(it.vis_span.to(ident.span.shrink_to_lo()))
```
Comment (fmease) [inline compiler/rustc_lint/src/builtin.rs]: My bad, I didn't look carefully enough. We actually want to include the span of the existing visibility if any since we're not suggesting `static` but `pub static` regardless of the original visibility which makes sense, of course.

```suggestion
                            Some(it.span.until(ident.span))
```

With `pub static ` (trailing space) as the replacement string. Again, take that with a pinch of salt, I'm yet again reviewing from my phone.

Thanks for impl'ing my optional suggestion. If this doesn't work out feel free to revert back to the preexisting code.

File: tests/ui/lint/force-warn/no-mangle-const-suggestion-suppressed.rs (hunk 4 above)
Comment (reddevilmidzy) [reply tests/ui/lint/force-warn/no-mangle-const-suggestion-suppressed.rs]: Yes, I fixed it! I also moved it back to `tests/ui/lint/no-mangle-const-suggestion-suppressed.rs`

File: tests/ui/lint/lint-unexported-no-mangle.stderr (hunk 5 above)
Comment (reddevilmidzy) [reply tests/ui/lint/lint-unexported-no-mangle.stderr:34]: Because I added a space after "pub static" in `compiler/rustc_lint/src/lints.rs`, the output of rustfix is ​​reflected as `pub static FOO: u64 = 1;`

https://github.com/rust-lang/rust/blob/main/tests/ui/lint/suggestions.fixed I also checked that this test works.

https://github.com/rust-lang/rust/pull/149544#discussion_r2584302114 
I added a space after "pub static" to reflect this review. Is there another way?

File: tests/ui/lint/no-mangle-generic-const-suggestion-suppressed.rs
Comment (fmease) [inline tests/ui/lint/no-mangle-generic-const-suggestion-suppressed.rs:1]: Could you potentially rename it to something like `tests/ui/lint/no-mangle-generic-const-suggestion-suppressed.rs` (i.e., adding `generic`, otherwise the name is too ~~generic~~ nondescript)?

File: compiler/rustc_lint/src/builtin.rs [hunk 7]
```diff
@@ -997,18 +997,15 @@ impl<'tcx> LateLintPass<'tcx> for InvalidNoMangleItems {
...
-                        .tcx
-                        .sess
-                        .source_map()
-                        .span_to_snippet(it.span)
-                        .map(|snippet| snippet.find("const").unwrap_or(0))
-                        .unwrap_or(0) as u32;
-                    // `const` is 5 chars
-                    let suggestion = it.span.with_hi(BytePos(it.span.lo().0 + start + 5));
+                    let suggestion =
+                        if generics.params.is_empty() && !generics.has_where_clause_predicates {
```
Comment (fmease) [inline compiler/rustc_lint/src/builtin.rs]: (minor) I'm afraid checking `generics.has_where_clause_predicates` doesn't account for the case where there's a `where` token but no predicates … which would still lead to an invalid suggestion. Consider:

```rs
#![feature(generic_const_items)]
#[no_mangle]
const _: () = () where;
```

Doing it like that should account for that:

```suggestion
                        if generics.params.is_empty() && generics.where_clause_span.is_empty() {
```

**Review by fmease — APPROVED** [review]
two small nits, then I'll send it off

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149544/672388edbee9e93c35e5fdf7dac818a6612a5103..dab5a15e1b7add5f1f8a4e2056d31edd694f5a81)*

File: compiler/rustc_lint/src/builtin.rs (hunk 7 above)
Comment (reddevilmidzy) [reply compiler/rustc_lint/src/builtin.rs]: Thanks for checking! I've updated the code as you suggested and added the test cases you mentioned :)
