### PR TITLE
rustdoc: use stability, instead of features, to decide what to show

### LINKED ISSUE #124635: Doc for std contains broken links in the implementors sections
https://doc.rust-lang.org/std/clone/trait.Clone.html for example lists implementations of `Clone` in `gimli`, which aren't visible anyway and the links are also broken.

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #124635

To decide if internal items should be inlined in a doc page, check if the crate is itself internal, rather than if it has the rustc_private feature flag. The standard library uses internal items, but is not itself internal and should not show internal items on its docs pages.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Thanks for taking care of this!

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -444,24 +445,32 @@ pub(crate) fn build_impl(
 
     let associated_trait = tcx.impl_trait_ref(did).map(ty::EarlyBinder::skip_binder);
 
+    // Do not inline compiler-internal items unless we're a compiler-internal crate.
+    let is_compiler_internal = |did| {
+        if let Some(stab) = tcx.lookup_stability(did) {
```
Comment (fmease) [inline src/librustdoc/clean/inline.rs:450]: (style) `is_some_and` maybe?

File: src/librustdoc/clean/inline.rs [hunk 2]
```diff
@@ -444,24 +445,32 @@ pub(crate) fn build_impl(
...
+            stab.is_unstable() && stab.feature == sym::rustc_private
+        } else {
+            false
+        }
+    };
+    let document_compiler_internal = is_compiler_internal(LOCAL_CRATE.as_def_id());
+    let is_directly_public = |cx: &mut DocContext<'_>, did| {
+        if !cx.cache.effective_visibilities.is_directly_public(tcx, did) {
```
Comment (fmease) [inline src/librustdoc/clean/inline.rs:458]: (style) `||` instead of 2 ifs maybe?

File: src/librustdoc/clean/inline.rs [hunk 3]
```diff
@@ -444,24 +445,32 @@ pub(crate) fn build_impl(
...
     if !did.is_local()
         && let Some(traitref) = associated_trait
+        && !is_directly_public(cx, traitref.def_id)
     {
-        let did = traitref.def_id;
-        if !cx.cache.effective_visibilities.is_directly_public(tcx, did) {
-            return;
-        }
-
-        if !tcx.features().rustc_private && !cx.render_options.force_unstable_if_unmarked {
```
Comment (fmease) [inline src/librustdoc/clean/inline.rs:457]: quick question, why wouldn't the following be a potential solution:

```rs
if !cx.render_options.force_unstable_if_unmarked {
```

(just removing the F-rustc_private check)

File: tests/rustdoc/inline_cross/issue-76736-2.rs [hunk 4]
```diff
@@ -1,16 +1,18 @@
...
+
 #![crate_name = "foo"]
 #![feature(rustc_private)]
 
 extern crate issue_76736_1;
 extern crate issue_76736_2;
 
 // @has foo/struct.Foo.html
-// @has - '//*[@class="impl"]//h3[@class="code-header"]' 'MaybeResult'
+// @!has - '//*[@class="impl"]//h3[@class="code-header"]' 'MaybeResult'
```
Comment (fmease) [inline tests/rustdoc/inline_cross/issue-76736-2.rs:13]: I don't know, couldn't this impl be useful? The user is explicitly opting into using internal APIs with `#![feature(rustc_private)]`, then why should we refuse them access to potential useful information (here: “`impl MaybeResult for Foo`” via the upstream blanket impl, which they can indeed make use of)

**Review by GuillaumeGomez — APPROVED** [review]

File: tests/rustdoc/inline_cross/issue-76736-2.rs (hunk 4 above)
Comment (fmease) [reply tests/rustdoc/inline_cross/issue-76736-2.rs:13]: Well, the std library doesn't contain `#[feature(rustc_internal)]` directly as you probably know but yeah.

There are other users of `rustc_internal`. I' on mobile rn but yesterday I grepped through `compiler/` and saw the feature being enabled for one of the alternate backends (cranelift or gcc, I don't remember) and I assume `rustfmt` enables it too for `rustc_{parse,ast}`?

I'm just nitpicking but I don't wanna block

**Review by fmease — APPROVED** [review]
The approach looks fine, although I still have some doubts as elaborated in my other comments.

I wonder if the tests should use `//@ compile-flags: -Zforce-unstable-if-unmarked` instead of `#![feature(rustc_internals)]` to be “closer to reality” but eh, not pressing.

**Comment by fmease** [comment]
Does this need backporting?

@bors r+ rollup

**Comment by fmease** [comment]
Backport to beta approved as per [Zulip poll](https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/beta-nominated.3A.20.23124864/near/437718070).

@rustbot label beta-accepted
