### PR TITLE
Disallow shebang in `--cfg` and `--check-cfg` arguments

### LINKED ISSUE #146130: Frontmatter inside `--cfg` and `--check-cfg` is not feature-gated
The following invocation compiles since 1.88 (or PR #140035):

```sh
rustc /dev/null --crate-type lib --cfg '---
---
key'
```

while it shouldn't because unstable feature `frontmatter` isn't enabled anywhere.

For context, in 1.87, it yielded the following error:

```
error: invalid `--cfg` argument: `---
       ---
       key` (expected `key` or `key="value"`)
```

The same applies to `--check-cfg`.

### PR DESCRIPTION
**Pull request by Urgau**
This PR is similar to https://github.com/rust-lang/rust/issues/146130, where we disallowed frontmatter in `--cfg` and `--check-cfg` arguments. While fixing the other one we also discovered that shebang `#!/usr/bin/shebang` are currently also allowed in `--cfg` and `--check-cfg` arguments.

Allowing shebang in them (which are just ignored) was never intended, this PR fixes that by not stripping shebang for `--cfg` and `--check-cfg` arguments.

This is technically a breaking-change, although I don't expect anyone to actually rely on this unintended behavior.

Fixes https://github.com/rust-lang/rust/issues/146130#issuecomment-3246299499
r? fmease

### CODE REVIEW

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 1]
```diff
@@ -44,19 +44,39 @@ pub(crate) struct UnmatchedDelim {
     pub candidate_span: Option<Span>,
 }
 
+/// Which tokens should be stripped before when leking the tokens
```
Comment (fmease) [inline compiler/rustc_parse/src/lexer/mod.rs]:
```suggestion
/// Which tokens should be stripped before lexing the tokens.
```

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 2]
```diff
@@ -44,19 +44,39 @@ pub(crate) struct UnmatchedDelim {
...
-    frontmatter_allowed: FrontmatterAllowed,
+    strip_tokens: StripTokens,
 ) -> Result<TokenStream, Vec<Diag<'psess>>> {
-    // Skip `#!`, if present.
-    if let Some(shebang_len) = rustc_lexer::strip_shebang(src) {
-        src = &src[shebang_len..];
-        start_pos = start_pos + BytePos::from_usize(shebang_len);
+    match strip_tokens {
+        StripTokens::Shebang | StripTokens::ShebangAndFrontmatter => {
+            // Skip `#!`, if present.
```
Comment (fmease) [inline compiler/rustc_parse/src/lexer/mod.rs]:
```suggestion
```

(preexisting) (1) factually wrong, it also skips the rest of the line (2) redundant / self-evident

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 3]
```diff
@@ -44,19 +44,39 @@ pub(crate) struct UnmatchedDelim {
     pub candidate_span: Option<Span>,
 }
 
+/// Which tokens should be stripped before when leking the tokens
+pub(crate) enum StripTokens {
+    /// Strip both shebang and frontmatter
+    ShebangAndFrontmatter,
+    /// Strip shebang but errors on frontmatter
+    Shebang,
+    /// Strip nothing, errors on shebang and frontmatter
```
Comment (fmease) [inline compiler/rustc_parse/src/lexer/mod.rs]:
```suggestion
    /// Strip both shebang and frontmatter.
    ShebangAndFrontmatter,
    /// Strip the shebang but not frontmatter.
    Shebang,
    /// Strip nothing.
```

regarding

> errors on frontmatter

that's not accurate; it just means we interpret the `---` etc. according to the "normal" lexical rules of Rust which doesn't necessarily imply "erroneous" as it all depends on the subsequent parser. See https://github.com/rust-lang/rust/issues/145945#issuecomment-3229690712 for example where `include!("file.rs")` in expression contexts and `file.rs` containing `---␊---␊1` is actually legal (once https://github.com/rust-lang/rust/issues/145945 is fixed again) and means a sixfold negated `1`.

Similarly, this applies to the "errors on shebang" case.

Comment (fmease) [reply compiler/rustc_parse/src/lexer/mod.rs]: Not sure how to best word it but if you want to clarify it, maybe sth. akin to:

```suggestion
    /// Strip both shebang and frontmatter.
    ShebangAndFrontmatter,
    /// Strip the shebang but not frontmatter (i.e., char sequences looking like frontmatter are simply interpreted as regular Rust lexemes).
    Shebang,
    /// Strip nothing (i.e., char sequences looking like a shebang or frontmatter are simply interpreted as regular Rust lexemes).
```

or lexemes → tokens.
or char sequences → strings.

**Review by fmease — APPROVED** [review]

**Comment by jieyouxu** [comment]
> Okay, so process-wise I'm not quite sure how to proceed. An MCP is overkill and a T-compiler FCP is also slightly overkill.

Honestly I'd say just do this, shebang was never intended to be supported in `--cfg/check-cfg`, and if someone was somehow relying on this, I rather break them ASAP than let this become more relied upon (intentionally or unintentionally).
