### PR TITLE
Correct regression in type-inference 

### LINKED ISSUE #26952: Stable regression in nightly
Type inference broke, or something. Hard to see why, as the file (broadcast.rs) is probably one of the simpler cases.

Easiest repro to is clone the repo (it is also up on crates, though as an earlier version)

```
% git clone https://github.com/frankmcsherry/timely-dataflow
Cloning into 'timely-dataflow'...
remote: Counting objects: 1959, done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 1959 (delta 32), reused 0 (delta 0), pack-reused 1889
Receiving objects: 100% (1959/1959), 596.67 KiB | 741.00 KiB/s, done.
Resolving deltas: 100% (1393/1393), done.
Checking connectivity... done.
% cd timely-dataflow 
% multirust override stable
multirust: using existing install for 'stable'
multirust: override toolchain for '/Users/mcsherry/timely-dataflow' set to 'stable'
% cargo build
    Updating git repository `https://github.com/frankmcsherry/abomonation`
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling byteorder v0.3.11
   Compiling libc v0.1.8
   Compiling abomonation v0.1.0 (https://github.com/frankmcsherry/abomonation#6bdf392c)
   Compiling log v0.3.1
   Compiling getopts v0.2.11
   Compiling timely v0.0.7 (file:///Users/mcsherry/timely-dataflow)
% multirust override nightly
multirust: using existing install for 'nightly'
multirust: override toolchain for '/Users/mcsherry/timely-dataflow' set to 'nightly'
% cargo build               
   Compiling abomonation v0.1.0 (https://github.com/frankmcsherry/abomonation#6bdf392c)
   Compiling libc v0.1.8
   Compiling byteorder v0.3.11
   Compiling log v0.3.1
   Compiling getopts v0.2.11
   Compiling timely v0.0.7 (file:///Users/mcsherry/timely-dataflow)
src/progress/broadcast.rs:31:51: 31:70 error: the type of this value must be known in this context
src/progress/broadcast.rs:31                 while let Some((update, delta)) = recv_messages.pop() {
                                                                               ^~~~~~~~~~~~~~~~~~~
note: in expansion of while let expansion
src/progress/broadcast.rs:31:17: 33:55 note: expansion site
note: in expansion of while let expansion
src/progress/broadcast.rs:30:13: 37:14 note: expansion site
src/progress/broadcast.rs:34:51: 34:70 error: the type of this value must be known in this context
src/progress/broadcast.rs:34                 while let Some((update, delta)) = recv_internal.pop() {
                                                                               ^~~~~~~~~~~~~~~~~~~
note: in expansion of while let expansion
src/progress/broadcast.rs:34:17: 36:55 note: expansion site
note: in expansion of while let expansion
src/progress/broadcast.rs:30:13: 37:14 note: expansion site
error: aborting due to 2 previous errors
Could not compile `timely`.

To learn more, run the command again with --verbose.
% cargo --version
cargo 0.4.0-nightly (15b497b 2015-07-08) (built 2015-07-08)
% rustc --version
rustc 1.3.0-nightly (16f64c388 2015-07-09)
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Correct regression in type-inference caused by failing to reconfirm that
the object trait matches the required trait during trait selection.  The
existing code was checking that the object trait WOULD match (in a
probe), but never executing the match outside of a probe.

This corrects various regressions observed in the wild, including
issue #26952. Fixes #26952.

r? @eddyb 
cc @frankmcsherry

### CODE REVIEW

File: src/librustc/middle/traits/select.rs [hunk 1]
```diff
@@ -2310,31 +2314,36 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                    self.match_poly_trait_ref(obligation, upcast_trait_ref)
-                }).is_ok())
-            });
-        let mut upcast_trait_ref = None;
-        let mut vtable_base = 0;
+        // Collect the full set of supertraitrefs.
+        let upcast_trait_refs: Vec<_> = util::supertraits(self.tcx(), poly_trait_ref).collect();
+
+        // Find the first one that matches; this is what we are upcasting to.
+        let index =
```
Comment (arielb1) [inline src/librustc/middle/traits/select.rs]: nit: I think this iterator salad would actually be clearer as a for-loop

File: src/librustc/middle/traits/select.rs [hunk 2]
```diff
@@ -1367,11 +1367,15 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             // correct trait, but also the correct type parameters.
             // For example, we may be trying to upcast `Foo` to `Bar<i32>`,
             // but `Foo` is declared as `trait Foo : Bar<u32>`.
-            let upcast_trait_refs = util::supertraits(self.tcx(), poly_trait_ref)
```
Comment (arielb1) [inline src/librustc/middle/traits/select.rs]: Just a reformatting?

**Comment by arielb1** [comment]
r? modulo nit

File: src/librustc/middle/traits/select.rs [hunk 3]
```diff
@@ -2310,31 +2314,36 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-        let mut upcast_trait_refs = util::supertraits(self.tcx(), poly_trait_ref)
-            .map(|upcast_trait_ref| {
-                (upcast_trait_ref.clone(), self.infcx.probe(|_| {
-                    self.match_poly_trait_ref(obligation, upcast_trait_ref)
-                }).is_ok())
-            });
-        let mut upcast_trait_ref = None;
-        let mut vtable_base = 0;
+        // Collect the full set of supertraitrefs.
+        let upcast_trait_refs: Vec<_> = util::supertraits(self.tcx(), poly_trait_ref).collect();
```
Comment (eddyb) [inline src/librustc/middle/traits/select.rs]: Couldn't this be done without collecting?

File: src/librustc/middle/traits/select.rs [hunk 4]
```diff
@@ -2310,31 +2314,36 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                upcast_trait_ref = Some(supertrait);
-                break;
-            }
-            vtable_base += util::count_own_vtable_entries(self.tcx(), supertrait);
-        }
-        assert!(upcast_trait_refs.all(|(_, matches)| !matches));
+        // Now that we found the correct trait ref, we have to match again outside
+        // the probe to confirm the effects.
+        let upcast_trait_ref = upcast_trait_refs[index].clone();
+        self.match_poly_trait_ref(obligation, upcast_trait_ref.clone()).unwrap();
```
Comment (eddyb) [inline src/librustc/middle/traits/select.rs]: I think it would be enough to just add this and keep the non-allocating loop.

**Comment by nikomatsakis** [comment]
@eddyb updated

File: src/librustc/middle/ty.rs [hunk 5]
```diff
@@ -1898,7 +1898,7 @@ impl<'tcx> PolyTraitRef<'tcx> {
 /// erase, or otherwise "discharge" these bound regions, we change the
 /// type from `Binder<T>` to just `T` (see
 /// e.g. `liberate_late_bound_regions`).
-#[derive(Clone, PartialEq, Eq, Hash, Debug)]
+#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
 pub struct Binder<T>(pub T);
```
Comment (eddyb) [inline src/librustc/middle/ty.rs]: Time to remove a thousand clone calls :P.
@huonw @Manishearth How about a lint against calling `.clone()` on a `Copy` type?

Comment (Manishearth) [inline src/librustc/middle/ty.rs]: Sounds good to me.
