### PR TITLE
Fix issues with const argument inference

### LINKED ISSUE #60724: Type which uses const generics leads to ICE when using Derive
This code

```rust
#![feature(const_generics)]

#[derive(Debug)]
struct X<const N: usize> {
    a: [u32; N],
}
```

leads to

```
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^

error[E0107]: wrong number of const arguments: expected 1, found 0

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `[type error]`,
 right: `usize`', src/librustc/ty/sty.rs:2279:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

It doesn't seem `Debug` related, since the same happens for deriving `Copy`.

### LINKED ISSUE #61346: Const generics: Incorrect error "wrong number of const arguments" with struct constructor
this works fine:
```rust
#![feature(const_generics)]
pub struct Array<T, const N: usize> ([T; {N}]);
impl <T, const N: usize> Array<T, {N}> {
    #[inline]
    pub fn cap(&self) -> usize {
        {N}
    }
}

fn main() {
    let arr = Array([0u32; 8]);

    println!("{}", arr.cap());
}
```
but this fails to compile:
```rust
#![feature(const_generics)]
pub struct Array<T, const N: usize> {
    data: [T; {N}]
}
impl <T, const N: usize> Array<T, {N}> {
    #[inline]
    pub fn cap(&self) -> usize {
        {N}
    }
}

fn main() {
    let arr = Array { data: [0u32; 8] };

    println!("{}", arr.cap());
}
```
here is the error:
```
error[E0107]: wrong number of const arguments: expected 1, found 0
  --> src/main.rs:28:15
   |
28 |     let arr = Array { data: [0u32; 8] };
   |               ^^^^^ expected 1 const argument

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/60724.
Fixes https://github.com/rust-lang/rust/issues/61346.

r? @eddyb

### CODE REVIEW

File: src/test/ui/const-generics/incorrect-number-of-const-args.rs [hunk 1]
```diff
@@ -6,6 +6,6 @@ fn foo<const X: usize, const Y: usize>() -> usize {
 }
 
 fn main() {
-    foo::<0>(); //~ ERROR wrong number of const arguments: expected 2, found 1
```
Comment (varkor) [inline src/test/ui/const-generics/incorrect-number-of-const-args.rs]: I'm not sure what's going on here. Having too few type arguments still results in an error, and as far as I can tell, type arguments use the same code path as const arguments. It might be that a separate issue is suppressing this error, or I might simply have missed something.

**Comment by yodaldevoid** [comment]
Did you mean to edit `Cargo.lock` and change the commits of `src/tools/miri` and `src/tools/clippy`?

**Comment by varkor** [comment]
@yodaldevoid: whoops, no, must have messed up the rebase. I'll address that soon.

**Review by eddyb — APPROVED** [review]
