### PR TITLE
Resolve lifetime parameters for foreign functions.

### LINKED ISSUE #26587: Weird "use of undeclared lifetime" with foreign function
```rust
extern {
   pub fn life<'a>(x:&'a i32);
}
fn main() {}
```
```
<anon>:2:23: 2:25 error: use of undeclared lifetime name `'a` [E0261]
<anon>:2    pub fn life<'a>(x:&'a i32);
                               ^~
error: aborting due to previous error
playpen: application terminated with error code 101
```

### PR DESCRIPTION
**Pull request by eefriedman**
Pretty straightforward; just need to make sure to explicitly handle
the generic parameters of each ast::ForeignItemFn.

Fixes #26587.

### CODE REVIEW

File: src/librustc/middle/resolve_lifetime.rs [hunk 1]
```diff
@@ -151,6 +151,29 @@ impl<'a, 'v> Visitor<'v> for LifetimeContext<'a> {
         replace(&mut self.labels_in_fn, saved);
     }
 
+    fn visit_foreign_item(&mut self, item: &ast::ForeignItem) {
+        // Items save/restore the set of labels. This way innner items
```
Comment (oli-obk) [inline src/librustc/middle/resolve_lifetime.rs]: innner -> inner

File: src/test/compile-fail/generic-extern-lifetime.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+extern {
+   pub fn life<'a>(x:&'a i32);
+   pub fn life2<'b>(x:&'a i32, y:&'b i32); //~ ERROR use of undeclared lifetime name `'a`
```
Comment (oli-obk) [inline src/test/compile-fail/generic-extern-lifetime.rs]: how are lifetimes in return values treated?

**Comment by eefriedman** [comment]
Amended to address review comments.

**Comment by eefriedman** [comment]
Ping?

**Comment by eefriedman** [comment]
Ping^2.

File: src/test/compile-fail/generic-extern-lifetime.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+   pub fn life3<'a>(x:&'a i32, y:&i32) -> &'a i32;
```
Comment (nrc) [inline src/test/compile-fail/generic-extern-lifetime.rs]: Could you add lines to this test which test for bad lifetimes deeply nested in an argument type and in the return type please?

Also add a comment to the top of the test stating what is being tested.

File: src/test/compile-fail/generic-extern-lifetime.rs [hunk 4]
```diff
@@ -0,0 +1,16 @@
+// Copyright 2014 The Rust Project Developers. See the COPYRIGHT
```
Comment (nrc) [inline src/test/compile-fail/generic-extern-lifetime.rs]: nit: 2015

**Comment by nrc** [comment]
Couple of minor things in the test, otherwise r=me

**Comment by eefriedman** [comment]
@nrc Updated test.
