### PR TITLE
std: sys: random: uefi: Provide rdrand based fallback

### LINKED ISSUE #138252: `HashMap::new()` panics inside UEFI environments that don't support RNG protocol
When you construct a HashMap inside a UEFI environment that does not support the RNG protocol, there will be a panic.

Here is a repo containing a minimal working repro of this issue: https://github.com/ifd3f/uefi-hashmap-panic-repro

I modified the [uefi-std-example](https://github.com/rust-osdev/uefi-rs/tree/13c1c2be2b17edd73a9565d89431a9266273f8a8/uefi-std-example) from the uefi-rs repo to construct a hashmap:

```rust
#![feature(uefi_std)]

use std::os::uefi as uefi_std;
use std::collections::HashMap;
use uefi::runtime::ResetType;
use uefi::{boot, Handle, Status};

/// Performs the necessary setup code for the `uefi` crate.
fn setup_uefi_crate() {
    let st = uefi_std::env::system_table();
    let ih = uefi_std::env::image_handle();

    // Mandatory setup code for `uefi` crate.
    unsafe {
        uefi::table::set_system_table(st.as_ptr().cast());

        let ih = Handle::from_ptr(ih.as_ptr().cast()).unwrap();
        uefi::boot::set_image_handle(ih);
    }
}

fn main() {
    println!("Hello World from uefi_std");
    setup_uefi_crate();
    println!("UEFI-Version is {}", uefi::system::uefi_revision());

    // Attach panic hook so we can actually read the errors
    std::panic::set_hook(Box::new(|p| {
        let backtrace = std::backtrace::Backtrace::capture();
        println!("{p}");
        println!("{backtrace}");
        loop {
            boot::stall(1_000_000_000)
        }
    }));

    let map = HashMap::<String, String>::new();

    println!("Successfully constructed a hashmap! {map:?}");
    loop {
        boot::stall(1_000_000_000)
    }
}
```

Running this in QEMU with OVMF firmware, instead of constructing the HashMap and printing it, it produces the following output:

```
BdsDxe: loading Boot0001 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Primary,Master,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Primary,Master,0x0)
Hello World from uefi_std
                         UEFI-Version is 2.7
                                            panicked at library/std/src/sys/random/uefi.rs:7:53:
                                                                                                failed to generate random data: Os { code: 9223372036854775822, kind: NotFound, message: "The item was not found." }
                                                                                                       disabled backtrace
```

Based on the panic, my understanding is that this happens because:
1. HashMap uses RandomState to randomly seed itself with the environment's secure RNG
2. The RNG implementation delegates to the UEFI environment's RNG protocol
3. ~~OVMF (or perhaps the way I set up QEMU) does not provide an RNG protocol~~ The VM does not have an RNG, so the EFI environment does not advertise any RNG protocols. Adding `-device virtio-rng-pci` to the QEMU invocation does allow this code to work.

This is the set of commands used to set up ESP using a virtual VFAT partition, and to launch QEMU with that ESP:

```bash
cargo build --target x86_64-unknown-uefi --release
rm -rf esp
mkdir -p esp/efi/boot
cp -r target/x86_64-unknown-uefi/release/uefi-std-example.efi esp/efi/boot/bootx64.efi

qemu-system-x86_64 \
    -D ./qemu.log \
    -drive if=pflash,format=raw,readonly=on,file=./OVMF_CODE.fd \
    -drive if=pflash,format=raw,readonly=on,file=./OVMF_VARS.fd \
    -drive format=raw,file=fat:rw:esp
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (f5a1ef712 2025-03-07)
binary: rustc
commit-hash: f5a1ef7121ad661b5a21a1d02941c8064d54ee0b
commit-date: 2025-03-07
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

Backtrace: I could not produce a backtrace. Setting `RUST_BACKTRACE=1` doesn't exactly work the same way in UEFI after all :)

### PR DESCRIPTION
**Pull request by Ayush1325**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/141324)*

Some UEFI systems based on American Megatrends Inc. v3.3 do not provide RNG support [1]. So fallback to rdrand in such cases.

[1]: https://github.com/rust-lang/rust/issues/138252#issuecomment-2891270323

Fixes https://github.com/rust-lang/rust/issues/138252

cc @seijikun

### CODE REVIEW

**Comment by joboet** [comment]
Unfortunately, the `rdrand` and `rdseed` instructions are not always safe or secure to use and thus require some checks ([see the getrandom crate's backend for some of the issues](https://github.com/rust-random/getrandom/blob/master/src/backends/rdrand.rs)). So `std` should either perform those checks or alternatively only use `rdrand` for generating hashmap keys (which would resolve the reported issue).

**Comment by Ayush1325** [comment]
> Unfortunately, the `rdrand` and `rdseed` instructions are not always safe or secure to use and thus require some checks ([see the getrandom crate's backend for some of the issues](https://github.com/rust-random/getrandom/blob/master/src/backends/rdrand.rs)). So `std` should either perform those checks or alternatively only use `rdrand` for generating hashmap keys (which would resolve the reported issue).

@seijikun Can you check if your hardware passes the checks in getrandom rand backend?

**Comment by Ayush1325** [comment]
> > Can you check if your hardware passes the checks in getrandom rand backend?
> 
> @Ayush1325 Sure! I don't have access to it at the moment, unfortunately - but I will do it monday morning. You probably mean `is_rdrand_good()` and `self_test()`, right?

`is_rdrand_good` calls `self_test`, so yup.

**Comment by Ayush1325** [comment]
> @Ayush1325 Looks good: image

Great, I will update the PR soon

**Comment by Ayush1325** [comment]
> @Ayush1325 There is currently still a bug in the implementation. UEFI's `locate_handles` function has one very weird quirk. When the resulting list is empty (as in my case), it doesn't return an empty list but instead fails with `EFI_NOT_FOUND`. That's an error I have stumbled over more than I'd like to admit...

Thanks for reporting this. I have updated the PR (and also done some refactoring).

**Comment by seijikun** [comment]
Just tested against the newest commit: 5c59ba84f046879f63878edd2e69ca9592bf3682
Works :heavy_check_mark:

**Comment by Ayush1325** [comment]
@joboet Does it look fine now?

File: library/std/src/sys/random/uefi.rs [hunk 1]
```diff
@@ -1,27 +1,156 @@
-use r_efi::protocols::rng;
+pub fn fill_bytes(bytes: &mut [u8]) {
+    // Try EFI_RNG_PROTOCOL
```
Comment (joboet) [inline library/std/src/sys/random/uefi.rs:7]: A zero-byte request should always succeed, but will currently panic if `rdrand` is not available as the UEFI protocol will return `EFI_INVALID_PARAMETER`.
```suggestion
    if bytes.is_empty() {
        return;
    }

    // Try EFI_RNG_PROTOCOL
```

File: library/std/src/sys/random/uefi.rs [hunk 2]
```diff
@@ -1,27 +1,156 @@
...
+
+        // SAFETY: We have already checked that rdrand is available.
+        unsafe { self_test() }
     }
 
-    panic!("failed to generate random data");
+    unsafe fn rdrand_exact(dest: &mut [u8]) -> Option<()> {
+        // We use chunks_exact_mut instead of chunks_mut as it allows almost all
+        // calls to memcpy to be elided by the compiler.
+        let mut chunks = dest.chunks_exact_mut(size_of::<Word>());
```
Comment (joboet) [inline library/std/src/sys/random/uefi.rs]: You could also use [`array_chunks_mut`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.array_chunks_mut) to eliminate the `copy_from_slice`.

**Review by joboet — CHANGES_REQUESTED** [review]
This looks fine to me, only the zero-request case is handled incorrectly.

File: library/std/src/sys/random/uefi.rs (hunk 1 above)
Comment (Ayush1325) [reply library/std/src/sys/random/uefi.rs:7]: Done

File: library/std/src/sys/random/uefi.rs (hunk 2 above)
Comment (Ayush1325) [reply library/std/src/sys/random/uefi.rs]: Done

**Review by phip1611 — APPROVED** [review]
I'm here via your [review request](https://rust-lang.zulipchat.com/#narrow/channel/219381-t-libs/topic/Improving.20review.20latency.20for.20UEFI.20PRs/near/524128864). I looked through the code and followed the discussion — it looks good to me. Just a heads-up: I'm not an experienced contributor to Rust itself.

**Comment by Ayush1325** [comment]
ping @joboet

**Comment by joboet** [comment]
Looks good!
@bors r+
