### PR TITLE
bootstrap: Allow building individual crates

### LINKED ISSUE #44293: x.py can't build individual crates
I'm trying to test building just `librustc_llvm` for the purposes of git bisecting, but am getting the following error:
```
./x.py build --stage 1 src/librustc_llvm
Warning: no rules matched /home/jessicah/rust/src/librustc_llvm
```

### PR DESCRIPTION
**Pull request by jyn514**
This aims to be as unintrusive as possible, but did still require adding a new `tail_args` field to all `Rustc` and `Std` steps.

New library and compiler crates are added to the sysroot as they are built, since it's useful to have e.g. just alloc and not std.

Fixes https://github.com/rust-lang/rust/issues/44293.

### CODE REVIEW

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -517,6 +517,95 @@ impl Step for StartupObjects {
...
+
+        run_cargo(
+            builder,
+            cargo,
+            vec![],
+            &stamp,
+            vec![],
+            false,
+        );
+    }
```
Comment (jyn514) [inline src/bootstrap/compile.rs:606]: hmm, in retrospect I think all this is wrong, because it doesn't include the logic from `Std::run` and `Rustc::run` :/ I can move those out into functions maybe? have to think about this more.

Comment (jyn514) [reply src/bootstrap/compile.rs:606]: Ok, how about this - I can change `Std` to use `krates()` instead of `all_krates()` and add a bunch of `-p core` arguments to the `tail_args` that get passed to `run_cargo` here. That should have exactly the same effect without having to introduce much code at all. The only downside is it requires adding a bunch of `tail_args: vec![]` calls all over the place where `Std` is constructed.

File: src/bootstrap/compile.rs [hunk 2]
```diff
@@ -29,10 +29,11 @@ use crate::util::{exe, is_debug_info, is_dylib, output, symlink_dir, t, up_to_da
 use crate::LLVM_TOOLS;
 use crate::{CLang, Compiler, DependencyType, GitRepo, Mode};
 
-#[derive(Debug, PartialOrd, Ord, Copy, Clone, PartialEq, Eq, Hash)]
+#[derive(Debug, PartialOrd, Ord, Clone, PartialEq, Eq, Hash)]
 pub struct Std {
     pub target: TargetSelection,
     pub compiler: Compiler,
+    pub tail_args: Vec<String>,
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:36]: Am I reading this right -- only ever used with `-p=$crate`? If so, then I think it probably makes sense to just use a `Option<Interned<String>>` here as an explicit crate field, rather than going with tail_args and needing to drop Copy bounds and be more general than necessary.

It might also be worth adding an explicit constructor to Std (builder.std or Std::new) so that we can avoid awkwardly specifying None for the krate field all over the place (or tail_args).

**Comment by Mark-Simulacrum** [comment]
I am generally OK with moving ahead with this PR. I think my main concern is that we'll get into a situation where there's some dependencies on particular crates which can (in the long run) mean more Cargo invocations, which both adds noise and could decrease available parallelism. In theory, what we want to do is probably some kind of "coalescing" where we know that the build as a whole will request up to X crate and then we build up to X. But that is (a) quite complicated to get right and (b) likely not terribly worth it, at this juncture.

That said, I think temporarily we should add a comment onto the krate field (if we refactor per my comment) that it shouldn't be used within rustbuild itself -- i.e., only the user can request building a subset of the full crate list for std or rustc, not some other rustbuild step. I think if we want to start doing that at some point we'll need to think about the coalescing behavior I suggest in the previous paragraph, or we might get confusing UI (where you see lints from core multiple times, for example) and in general hurt ourselves more than help.

> New compiler crates are not added, since they're not useful unless you have the whole compiler. That second bit might not technically be true for things like rustfmt, etc, I'm open to reconsidering.

It looks like this is currently special cased in the code, but I don't think it makes sense to add any special casing here. We should just always copy I think.

---

One question -- going back to my coalescing point -- we can with just this PR already see some somewhat odd behavior, right? For example, a build like `x.py build library/core compiler/rustc_middle` will probably see 2 cargo invocations for the libtest-rooted crate graph, which means that libcore is "built" twice (only invoked once via rustc), which means that lints get emitted twice.

I think it might make sense to at least for now add an assert that we're not invoking the Std/Rustc steps with different tail_args/krate parameters across the x.py invocation, modulo stage/compiler parameters. (i.e., for a given stage + compiler, we should only invoke these steps once). This can be relaxed if it proves to be a problem, but I think it'll make it easier for us to comprehend what's going on and presents a clearer interface to users in some sense (a clear panic vs. potentially odd builds, which might lead to spurious rebuilds, too, depending on how you order step definitions in builder.rs maybe?).

**Comment by jyn514** [comment]
> > New compiler crates are not added, since they're not useful unless you have the whole compiler. That second bit might not technically be true for things like rustfmt, etc, I'm open to reconsidering.

> It looks like this is currently special cased in the code, but I don't think it makes sense to add any special casing here. We should just always copy I think.

:+1: sounds good, will remove the special casing.

> That said, I think temporarily we should add a comment onto the krate field (if we refactor per my comment) that it shouldn't be used within rustbuild itself -- i.e., only the user can request building a subset of the full crate list for std or rustc, not some other rustbuild step. 

:+1: will do - I was actually looking locally into separating this into `CrateStd` and `Std`, where "Std" has the existing behavior and "CrateStd" can build / move to sysroot individual crates. That naturally avoids doing the wrong thing without changes elsewhere in bootstrap.

---

> For example, a build like x.py build library/core compiler/rustc_middle will probably see 2 cargo invocations for the libtest-rooted crate graph, which means that libcore is "built" twice (only invoked once via rustc), which means that lints get emitted twice.

This is true and a great point. To some extent I wonder how much it matters across "parts" of the tree (is anyone going to try and build both library and compiler crates individually in the same invocation?) but it's *definitely* confusing within a part - `x build core std` will show the lints for core twice. I don't think that's inherent to the problem, though - if we could invoke cargo as `build -p core -p std` it will show the lints at most once:
```
$ cargo c -q -p inner --message-format short
/home/jnelson/rust-lang/test-rust/src/lib.rs:1:4: warning: function is never used: `unused`
$ cargo c -q -p outer --message-format short
/home/jnelson/rust-lang/test-rust/src/lib.rs:1:4: warning: function is never used: `unused`
$ cargo c -q -p inner -p outer --message-format short
/home/jnelson/rust-lang/test-rust/src/lib.rs:1:4: warning: function is never used: `unused`
```
Is that a reasonable solution? Or do you think it's important to solve it for the `build core rustc_middle` case as well?

If it is a reasonable solution, one way to implement it is by changing `ShouldRun::krate` to invoke the `Step` only once, with *all* paths, rather than re-rerunning it for each path that matches. That will make some other things nicer as well, like only copying to the sysroot once rather than for each crate.

>  I think my main concern is that we'll get into a situation where there's some dependencies on particular crates which can (in the long run) mean more Cargo invocations, which both adds noise and could decrease available parallelism.

If cargo is rebuilding multiple crates on `cargo build -p core -p std`, that seems like a cargo bug and we should fix it there. I agree that `cargo build -p core; cargo build -p std` could potentially build more than necessary - I guess the concern is that `x build library/core; x build library` will do extra work? I don't see a way to fix that unfortunately :( but I can certainly avoid spurious rebuilds within a single invocation of bootstrap.

**Comment by Mark-Simulacrum** [comment]
I would be very happy to see us pass -p multiple times, as you suggest, presuming that works. (It very well may).

I imagine that'll also help with build parallelism in the per-crate test runs, which currently suffer from this "run cargo N times" problem.

I think the approach you suggest generally sounds right - we've built up a good bit of legacy code/design with the path specifications for steps (e.g., --exclude handling, some logic around defaults iirc) and I think this would continue to move us in the right direction. It might make sense to split into a separate PR, or at least commit, though - I imagine it's a hopefully orthogonal change from this PRs work. Either way is ok with me though.

**Comment by jyn514** [comment]
Amazing! I'll implement that (one call to Step for all paths, plus proper handling of multiple `-p` crates) in a separate PR then :) so we can make sure it works well for `test::CrateLibrustc` and `doc::Rustc`.

**Comment by Mark-Simulacrum** [comment]
To add to my comment, since I didn't say it explicitly: I don't think we need to solve multiple invocations of x.py, but I do want us to be careful around in-x.py usage: it can be tempting to build as little as necessary for the step you're doing (e.g., building tidy doesn't need libtest) but if you're going to end up building libtest (e.g., for compiletest) you should do that upfront.

I think that problem is largely solved within a single invocation by just not trying to get fancy with optimizing - at least initially - and having both tidy and compiletest depend on the full std and test.

I think that'll cover most cases, but probably not an invocation that on the command line specifies core and then compiletest. We have no (trivial) way of knowing about compiletest while building core, so this will lead to core being built twice (cargo run twice) under what we've designed/described so far. I'm not sure on the best way to solve this - maybe we should find some time to chat live (maybe poke on Zulip) if you don't have ideas here.

**Comment by jyn514** [comment]
(Zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/bootstrap.20.2B.20building.20individual.20crates.20.2395503)

**Review by jyn514 — COMMENTED** [review]
Ok, I implemented this on top of the changes from https://github.com/rust-lang/rust/pull/96501, and added a comment that it shouldn't be used from other steps, only from the top-level `make_run`.

(I have some thoughts around how to make this usable within rustbuild, but I think even if we never get that working this is a good change.)

File: src/bootstrap/compile.rs [hunk 3]
```diff
@@ -532,13 +595,18 @@ impl Step for Rustc {
     const DEFAULT: bool = false;
 
     fn should_run(run: ShouldRun<'_>) -> ShouldRun<'_> {
-        run.never()
+        // NOTE: doesn't use rustc-main to avoid conflicting with `compiler/rustc` in `Assemble`.
+        // If you add a new *direct* dependency to rustc-main, please also update this function.
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:599]: It seems like it should be possible for us to do this here by calling in_tree_crates ourselves or adding a helper (krate_deps(...)).

File: src/bootstrap/compile.rs [hunk 4]
```diff
@@ -532,13 +595,18 @@ impl Step for Rustc {
...
+        run.krate("rustc_smir").krate("rustc_driver").krate("rustc_codegen_ssa")
+        // run.never()
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:601]: nit: stray comment

**Comment by jyn514** [comment]
Ok, this should be ready to go (except for squash / merge).

@rustbot ready

File: src/bootstrap/compile.rs [hunk 5]
```diff
@@ -532,13 +572,25 @@ impl Step for Rustc {
     const DEFAULT: bool = false;
 
     fn should_run(run: ShouldRun<'_>) -> ShouldRun<'_> {
-        run.never()
+        // NOTE: doesn't use rustc-main to avoid conflicting with `compiler/rustc` in `Assemble`.
+        // If you add a new *direct* dependency to rustc-main, please also update this function.
+        // run.crate_or_deps("rustc_smir").crate_or_deps("rustc_driver").crate_or_deps("rustc_codegen_ssa")
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:577]: nit: outdated commented code

**Review by Mark-Simulacrum — COMMENTED** [review]
Looks like this is failing to compile as well.

**Comment by jyn514** [comment]
Got tired of copy-pasting impls and switched this to using generics. I know you've mentioned in the past we should emphasize readability over being concise, but I think the new code is honestly easier to read than trying to see the differences between the old impls.

**Comment by jyn514** [comment]
> Got tired of copy-pasting impls and switched the cache to using generics.

I'll split this into a separate commit to make it easier to review, I didn't realize how big the diff was.

File: src/bootstrap/cache.rs [hunk 6]
```diff
@@ -210,16 +164,36 @@ pub struct Interner {
...
     }
     pub fn intern_string(&self, s: String) -> Interned<String> {
-        self.strs.lock().unwrap().intern(s)
+        s.intern()
     }
 
     pub fn intern_path(&self, s: PathBuf) -> Interned<PathBuf> {
-        self.paths.lock().unwrap().intern(s)
+        s.intern()
     }
```
Comment (jyn514) [inline src/bootstrap/cache.rs:204]: this is a little weird because it takes `self` just to ignore it, but `INTERNER` is the only public item of its type, so I think it's ok

File: src/bootstrap/cache.rs [hunk 7]
```diff
@@ -208,18 +162,49 @@ impl<T: Hash + Clone + Eq> TyIntern<T> {
...
+        &INTERNER.lists
+    }
 }
 
 impl Interner {
     pub fn intern_str(&self, s: &str) -> Interned<String> {
         self.strs.lock().unwrap().intern_borrow(s)
     }
     pub fn intern_string(&self, s: String) -> Interned<String> {
-        self.strs.lock().unwrap().intern(s)
```
Comment (Mark-Simulacrum) [inline src/bootstrap/cache.rs:218]: This doesn't seem right; I would expect this code to remain the same, calling self.strs... or self.paths.. for the other methods, and the trait intern(self) would call INTERNER.intern_x rather than splitting out intern_cache and intern(self) methods.

Comment (jyn514) [reply src/bootstrap/cache.rs:218]: `intern_cache` is needed for the generic methods, e.g. https://github.com/rust-lang/rust/blob/d50583eaecdf88b5ee59e1d77fe3b4a8d87cbe6e/src/bootstrap/cache.rs#L112-L117
Without making that part of the trait, there's no way to be generic over the type, since the only available method is for interning, not retrieving.

I do agree this diff in particular is kind of strange, though - I've reverted it back to make it more clear rather than being maximally concise.

Comment (jyn514) [reply src/bootstrap/cache.rs]: If you like I can remove `intern_cache` and add a `Internable::get` method. But not sure that any of these are more clear than others; they all seem about the same to me.

Comment (Mark-Simulacrum) [reply src/bootstrap/cache.rs]: I'm happy with the diff in the latest form; I think there's possibly a refactor to the interning that we could do (maybe even just leaking everything...) but definitely doesn't need to block this.
