### PR TITLE
Fix for #62691: use the largest niche across all fields

### LINKED ISSUE #62691: Suboptimal niche usage within the fields of a variant.
On x86_64, this prints the values in comments:
```rust
pub enum Option2<A, B> {
    Some(A, B),
    None
}

fn main() {
    use std::mem::size_of;
    
    dbg!(size_of::<Option<Option<(bool, &())>>>()); // = 16
    dbg!(size_of::<Option<Option<(&(), bool)>>>()); // = 16
    dbg!(size_of::<Option<Option2<bool, &()>>>()); // = 16
    dbg!(size_of::<Option<Option2<&(), bool>>>()); // = 24
}
```

What's happening here is that when we pick the niche to represent `None` of `Option<T>`, we pick *the largest* (or "roomiest") of the niches in `T`, so that further enums *around* `Option<T>` have more optimization opportunities themselves.

(Why just one niche? That has to do with the fact that in an `enum`, the only part of the representation guaranteed to be always initialized and valid is the tag / niche, but no other variant fields)

For `Option2<A, B>`, however, we just pick the best niche in `A` and only look at `B` if `A` has *no niches at all*, so if `B` has a better niche, we miss it.

This is a small oversight in the code itself, and arguably it will be slightly nicer once this is fixed, but I wanted to open this issue first, before I have a chance to fix it myself (if someone else doesn't get there first).

cc @Gankra @nox

### PR DESCRIPTION
**Pull request by ogoffart**
fixes #62691

(The second commit is a small optimization but it makes the code less pretty and i don't know if it is worth it.)

### CODE REVIEW

File: src/librustc/ty/layout.rs [hunk 1]
```diff
@@ -907,14 +907,25 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
...
+                                if ns <= niche_size {
+                                    return acc;
+                                }
+                                match niche.reserve(self, count) {
+                                    Some(pair) => {
+                                        niche_size = ns;
+                                        Some((j, niche, pair.0, pair.1))
+                                    }
+                                    None => acc,
+                                }
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: You don't need this complication, just have `.max_by_key(|(_, niche, _)| niche.available(dl))` before `.and_then(|(_, niche)| Some((i, niche, niche.reserve(self, count)?)))`.

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -907,18 +907,15 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
...
-
+                        if let Some((field_index, niche, (niche_start, niche_scalar))) = variants[i]
+                            .iter()
+                            .enumerate()
+                            .filter_map(|(i, &field)| {
+                                let niche = field.largest_niche.as_ref()?;
+                                Some((i, niche, niche.reserve(self, count)?))
+                            })
+                            .max_by_key(|(_, niche, _)| niche.available(dl))
+                        {
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: I really like how readable this is!

File: src/librustc/ty/layout.rs [hunk 3]
```diff
@@ -907,18 +907,26 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
...
+                                if ns <= niche_size {
+                                    return acc;
+                                }
+                                match niche.reserve(self, count) {
+                                    Some(pair) => {
+                                        niche_size = ns;
+                                        Some((j, niche, pair.0, pair.1))
+                                    }
+                                    None => acc,
+                                }
```
Comment (Centril) [inline src/librustc/ty/layout.rs]: Consider sprinkling some comments here btw, and/or extracting functions :)

Comment (eddyb) [reply src/librustc/ty/layout.rs]: Hopefully we can keep something close to the first commit, as it's more functional and way easier to explain as "find the largest niche among the fields" + "make sure it can fit our variant `count`".

File: src/librustc/ty/layout.rs (hunk 1 above)
Comment (ogoffart) [reply src/librustc/ty/layout.rs]: I wanted to do that but that's not exactly the same thing. If it fails for the largest niche, but would have succeeded for a smaller niche, we would end up with None instead of using the smaller niche.
Now, maybe this cannot succeed for a smaller niche and fail for a bigger one so in that case that would be indeed best.

Comment (eddyb) [reply src/librustc/ty/layout.rs]: > Now, maybe this cannot succeed for a smaller niche and fail for a bigger one so in that case that would be indeed best.

Yeah, that's why we want bigger niches in general: they succeed strictly more often.

Comment (ogoffart) [reply src/librustc/ty/layout.rs]: This is what i've done now.

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
r=me after https://github.com/rust-lang/rust/pull/70411#discussion_r398210971 is addressed (which should be easier now, with the more functional approach - if you want, you can extract some of that into a variable that you then take apart using e.g. `if let Some(...) = niche_candidate`, instead of having everything in the RHS of the `if let`).

File: src/librustc/ty/layout.rs (hunk 1 above)
Comment (ogoffart) [reply src/librustc/ty/layout.rs]: But looking at the code of Niche::reserve, it seems it can still fail if `valid_range_contains` despite being the largest niche while a smaller niche would work.  or is that really unlikely?

Comment (eddyb) [reply src/librustc/ty/layout.rs]: The calculations are equivalent, I think I even double-checked them using bruteforce for small bitwidths.

`niche.reserve(count)` is checking `niche.available() >= count` but using values it has to compute anyway (i.e. the remaining validity range), instead of actually using `available`.

**Comment by ogoffart** [comment]
Updated.
