### PR TITLE
Defer repeat expr `Copy` checks to end of type checking

### LINKED ISSUE #110443: inferred repeat expression length unnecessarily needs `Copy`
```rust
#![feature(generic_arg_infer)]
struct NotCopy;

fn with_len<T, const N: usize>(_: [T; N]) {}

fn main() {
    let x = [NotCopy; _];
    with_len::<NotCopy, 0>(x)
}
```
results in the following error:
```rust
error[[E0277]](https://doc.rust-lang.org/nightly/error_codes/E0277.html): the trait bound `NotCopy: Copy` is not satisfied
 --> src/main.rs:7:14
  |
7 |     let x = [NotCopy; _];
  |              ^^^^^^^ the trait `Copy` is not implemented for `NotCopy`
  |
  = note: the `Copy` trait is required because this value will be copied for each element of the array
help: consider annotating `NotCopy` with `#[derive(Copy)]`
  |
2 + #[derive(Copy)]
3 | struct NotCopy;
  |
```

we should be able to solve that by using marker traits (potentially waiting until they're stable)
```rust
#[marker]
trait RepeatExprMayCopyValue {}
impl<T: Copy, const N: usize> RepeatExprMayCopyValue for [T; N] {}
impl<T> RepeatExprMayCopyValue for [T; 0] {}
impl<T> RepeatExprMayCopyValue for [T; 1] {}
```
and then change hir typeck to require `RepeatExprMayCopyValue` for the array instead of optionally requiring `Copy` for the value.

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #110443

Defers repeat expr checks that the element type is `Copy` when the length is > 1 (or generic) to end of typeck so that under `generic_arg_infer` repeat exprs are able to have an inferred count, e.g. `let a: [_; 1] = [String::new(); _];`.

Currently the deferring is gated under `generic_arg_infer` though I intend to separately types FCP deferring the checks even outside of `generic_arg_infer` if we wind up not going with an alternative.

### CODE REVIEW

File: tests/ui/repeat-expr/infer-eager.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+}
+impl Copy for Foo<u8> {}
+
+fn extract<T, const N: usize>(_: [Foo<T>; N]) -> T {
+    loop {}
+}
+
+fn main() {
+    let x = [Foo(PhantomData); 2];
+    //~^ ERROR: type annotations needed
```
Comment (BoxyUwU) [inline tests/ui/repeat-expr/infer-eager.rs:18]: always deferring the check is a breaking change in cases where the `Copy` impl has inference constraints that are then used in order to perform method lookup (or any other kind of hir typeck check that relies on matching on a type).

want to crater this to see how breaking it is but it would be very easy to just not break this and think that is my preference :3

**Comment by BoxyUwU** [comment]
@craterbot check

**Comment by BoxyUwU** [comment]
(all spurrious)

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 2]
```diff
@@ -1510,6 +1513,32 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        self.body_id,
+                        sp,
+                        ct.into(),
+                        TypeAnnotationNeeded::E0282,
+                        true,
+                    )
+                    .emit()
+            });
+            // FIXME: Infer `?ct = {const error}`?
+            ty::Const::new_error(self.tcx, e)
```
Comment (BoxyUwU) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1538]: There's no `fcx.demand_subtype` for consts yet.

File: compiler/rustc_hir_typeck/src/lib.rs [hunk 3]
```diff
@@ -194,6 +194,15 @@ fn typeck_with_inspect<'tcx>(
         fcx.write_ty(id, expected_type);
     };
 
+    // Whether to check repeat exprs before/after inference fallback is somewhat arbitrary of a decision
+    // as neither option is strictly more permissive than the other. However, we opt to check repeat exprs
+    // first as errors from not having inferred array lengths yet seem less confusing than errors from inference
+    // fallback arbitrarily inferring something incompatible with `Copy` inference side effects.
+    //
+    // This should also be forwards compatible with moving repeat expr checks to a custom goal kind or using
```
Comment (BoxyUwU) [inline compiler/rustc_hir_typeck/src/lib.rs:202]: I feel somewhat hesitant to add a custom goal kind for repeat expr checks but I do think it would be "optimal" behaviour-wise as the goals could stall on the repeat count infer var and be deferred ~as long as necessary while also not delaying inference constraints from them any later than is needed.

File: tests/ui/repeat-expr/infer-eager.rs (hunk 1 above)
Comment (BoxyUwU) [reply tests/ui/repeat-expr/infer-eager.rs]: I think my preference now is actually to either always defer and eat the breaking change or do a less-hacky attempt to avoid the breaking change by introducing a new goal kind for repeat expr checks that can be deferred exactly as long as is necessary and no furthur

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
lgtm, r=me with or without applying the nit; i think it may not be needed b/c all it's gonna do is *slightly* improve duplicated/unnecessary errors.

**Comment by BoxyUwU** [comment]
(rebased)

@bors r=compiler-errors
