### PR TITLE
Improve and fix diagnostics of exhaustiveness checking

### LINKED ISSUE #56379: E0005; should all constructors be listed?
See https://github.com/rust-lang/rust/pull/56362#discussion_r237904889 for context.

cc @estebank @petrochenkov @varkor

### PR DESCRIPTION
**Pull request by Nadrieril**
Primarily, this fixes https://github.com/rust-lang/rust/issues/56379. This also fixes incorrect interactions between or-patterns and slice patterns that I discovered while working on #56379. Those two examples show the incorrect diagnostics:

```rust
match &[][..] {
    [true] => {}
    [true // detected as unreachable but that's not true
        | false, ..] => {}
    _ => {}
}
match (true, None) {
    (true, Some(_)) => {}
    (false, Some(true)) => {}
    (true | false, None | Some(true // should be detected as unreachable
                               | false)) => {}
}
```

I did not measure any perf impact. However, I suspect that [`616ba9f`](https://github.com/rust-lang/rust/pull/80104/commits/616ba9f9f7f5845777a36e1a41a515e6c33a8776) should have a negative impact on large or-patterns. I'll see what the perf run says; I have optimization ideas up my sleeve if needed.

EDIT: I initially had a noticeable perf impact that I thought unavoidable. I then proceeded to avoid it x)

r? @varkor
@rustbot label +A-exhaustiveness-checking

### CODE REVIEW

**Comment by Nadrieril** [comment]
Oh well, that's why I should push a PR just before sleep ^^. I thought a perf impact was unavoidable but it wasn't. I've edited the OP to reflect that.

**Comment by jyn514** [comment]
.6% regression on instructions for match-stress-enum-check (in check_match, as expected). Personally I think the diagnostic improvements are worth it.

File: src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs [hunk 1]
```diff
@@ -49,9 +49,9 @@ fn main() {
         _ => {}
     }
     match [0; 2] {
-        [0
+        [0 //.
```
Comment (varkor) [inline src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs:52]: What's with the `//.`s?

Comment (Nadrieril) [reply src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs:52]: Ah I can remove them, it's because my editor runs rustfmt on save and that merged the lines. Except I broke the lines that way to ensure the error was located correctly

Comment (Nadrieril) [reply src/test/ui/or-patterns/exhaustiveness-unreachable-pattern.rs:52]: Fixed

**Comment by varkor** [comment]
Looks good, thanks!

@bors r+

**Comment by varkor** [comment]
Looks spurious to me.

@bors retry
