### PR TITLE
Suggest fixes and add error recovery for `use foo::self`

### LINKED ISSUE #63741: Suggest removing `self` import when not in a list
```rust
use std::self; // error[E0429]: `self` imports are only allowed within a { } list
```
we should offer the suggestion to remove `::self`, as this is likely what the user intended.

This issue has been assigned to @mibac138 via [this comment](https://github.com/rust-lang/rust/issues/63741#issuecomment-623142619).

### PR DESCRIPTION
**Pull request by mibac138**
Fixes #63741.
I have implemented 2 suggestions on how to fix a `use foo::self` import, however I feel like showing them both might be too verbose. 

Additionally, I have also implemented error recovery as [menitoned](https://github.com/rust-lang/rust/issues/63741#issuecomment-602391091) by @comex. 

I believe r? @estebank deals with diagnostics.

### CODE REVIEW

File: src/librustc_resolve/diagnostics.rs [hunk 1]
```diff
@@ -300,13 +300,40 @@ impl<'a> Resolver<'a> {
...
+                    "`self` imports are only allowed within a { } list"
+                );
+
+                // None of the suggestions below would help with a case like `use self`.
+                if !root {
+                    // use foo::bar::self        -> foo::bar
+                    // use foo::bar::self as abc -> foo::bar as abc
+                    err.span_suggestion(
+                        span,
+                        "Remove `::self`..",
```
Comment (estebank) [inline src/librustc_resolve/diagnostics.rs:318]: The style guide for text in diagnostics asks for lowercase leading sentences without periods at the end.
```suggestion
                        "consider importing the module directly",
```

File: src/librustc_resolve/diagnostics.rs [hunk 2]
```diff
@@ -300,13 +300,40 @@ impl<'a> Resolver<'a> {
...
+                    );
+
+                    // use foo::bar::self        -> foo::bar::{self}
+                    // use foo::bar::self as abc -> foo::bar::{self as abc}
+                    let braces = vec![
+                        (span_with_rename.shrink_to_lo(), "{".to_string()),
+                        (span_with_rename.shrink_to_hi(), "}".to_string()),
+                    ];
+                    err.multipart_suggestion(
+                        "..or add braces around `self`",
```
Comment (estebank) [inline src/librustc_resolve/diagnostics.rs:330]:
```suggestion
                        "alternatively, use the multi-path `use` syntax to import `self`",
```

**Review by estebank — APPROVED** [review]
Love the changes! I have one nitpick about the wording, but after addressing that, r=me.

**Comment by estebank** [comment]
Also, apologies for the delay in the review, this dropped from my radar until now.

**Comment by mibac138** [comment]
@estebank No worries, I have changed the wording.
