### PR TITLE
Don't normalize in AstConv

### LINKED ISSUE #54940: user type annotations are captured post normalization
This example compiles but should not. Haven't investigated deeply.

```rust
#![feature(nll)]

trait Foo { 
    type Item;
}

impl<'a, u32> Foo for &'a u32 {
    type Item = &'a i32;
}

fn main() {
    let a = 22_i32;
    let x: <&'static u32 as Foo>::Item = &a;
}
```

cc https://github.com/rust-lang/rust/issues/47184

### LINKED ISSUE #101350: ignored regions constraints when normalizing user-provided types
This compiles after full NLL (>= 1.64) but it shouldn't:
```rust
trait Trait {
    type Ty;
}

impl Trait for &'static () {
    type Ty = ();
}

fn extend<'a>() {
    None::<<&'a () as Trait>::Ty>;
}
```

HIR typeck unconditionally normalizes user-provided types modulo regions, so it's not NLL's fault this time :)

@rustbot label regression-from-stable-to-stable T-compiler T-types

### PR DESCRIPTION
**Pull request by aliemjay**
See individual commits.

Fixes #101350
Fixes #54940

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 1]
```diff
@@ -279,19 +278,39 @@ impl<'a, 'tcx> AstConv<'tcx> for FnCtxt<'a, 'tcx> {
...
 
-    fn normalize_ty(&self, span: Span, ty: Ty<'tcx>) -> Ty<'tcx> {
-        if ty.has_escaping_bound_vars() {
-            ty // FIXME: normalization and escaping regions
-        } else {
-            self.normalize_associated_types_in(span, ty)
+    fn probe_adt(&self, span: Span, ty: Ty<'tcx>) -> Option<ty::AdtDef<'tcx>> {
+        match ty.kind() {
+            ty::Adt(adt_def, _) => Some(*adt_def),
+            // FIXME: We should normalize even with escaping bound vars.
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:284]: no, we shouldn't imo

imo we should have never relied on normalization during ast lowering. We won't be able to remove the existing normalization due to backwards compatibility. I think we should just live with the existing inconsistency, potentially even linting when normalization is required to remove it 2030 or whatever

File: src/test/ui/associated-types/bound-region-variant-resolution.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// This is a bug!
```
Comment (lcnr) [inline src/test/ui/associated-types/bound-region-variant-resolution.rs:1]: can you open an issue for that? You can then add `// known-bug: #<issuenum>` to this file

**Comment by lcnr** [comment]
Thanks :heart: 

As this is a breaking change, going to run crater and then go through a t-types FCP. r=me on the impl after some nits

@bors try

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs (hunk 1 above)
Comment (aliemjay) [reply compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:284]: I tend to agree. The fact that path resolution depends on normalization may be an unintended behavior.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 3]
```diff
@@ -1187,7 +1161,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             .unwrap_or(false);
 
         let (res, self_ctor_substs) = if let Res::SelfCtor(impl_def_id) = res {
-            let ty = self.normalize_ty(span, tcx.at(span).type_of(impl_def_id));
+            let ty = tcx.at(span).type_of(impl_def_id);
+            let ty = self.normalize_associated_types_in(span, ty);
```
[the remark this answers is not in the document]
Comment (aliemjay) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1141]: `SelfCtor` type is already checked by item `wfcheck`, so I don't think we will miss region obligations when normalizing.

**Comment by Dylan-DPC** [comment]
@craterbot check crates=list:https://crater-reports.s3.amazonaws.com/pr-101947/retry-regressed-list.txt

**Comment by Dylan-DPC** [comment]
@craterbot check

**Comment by lcnr** [comment]
I think https://crates.io/crates/abstract-add-on/0.2.0-beta.2 might be the only actual regression? :thinking: I can't find the source for that crate. Considering that this version has less than 50 downloads this breakage feels acceptable. cc @CyberHoward

Would be good for someone else to also have a look at the crater results as only having 1 regression is actually pretty surprising to me, would have expected a bigger impact.

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:286]: cc @rust-lang/types I generally don't think we should normalize during astconv to resolve stuff like `Self::A` if `Self` is a projection. Examples include
```rust
trait Identity {
    type Id;
}
impl<T> Identity for T {
    type Id = T;
}

enum Foo {
    A,
    B,
}

trait Trait {
    fn return_a() -> Self;
}

impl Trait for <Foo as Identity>::Id {
    fn return_a() -> Self {
        Self::A
    }
}

fn main() {
    let x = <<Foo as Identity>::Id>::A;
}
```
We do have to keep supporting this for backwards compatibility however.

I therefore think that we should 1) remove the FIXME here and add a comment for "we cannot normalize inside of a binder" 2) rename this method to `probe_adt_normalize_for_backcompat` to prevent us from at least adding further uses of that method.

**Comment by CyberHoward** [comment]
Thanks for the cc. Could you share any resources on why my code shouldn't have compiled in the first place?

**Comment by aliemjay** [comment]
> Would be good for someone else to also have a look at the crater results as only having 1 regression is actually pretty surprising to me, would have expected a bigger impact.

@lcnr I think the impact is not as big as you expect because we're still not doing WF-checks on  user annotations prior to normalization, so this code is still accepted:
```rust
trait Trait { type Ty; }
impl<T> Trait for T { type Ty = (); }
fn test<T>() {
    let _: <&'static T as Trait>::Ty = ();
}
```

I consider this a different issue than #101350 because it is a more long-standing problem and not strictly an NLL regression.

**Comment by aliemjay** [comment]
> Thanks for the cc. Could you share any resources on why my code shouldn't have compiled in the first place?

@CyberHoward you can take a look at the error message: https://crater-reports.s3.amazonaws.com/pr-101947-1/try%23fbef200192438a84822be119ec8070ded9a19487/reg/abstract-add-on-0.2.0-beta.2/log.txt

In `impl ExecuteEndpoint for AddonContract<E>` you have a bound `E: 'static` but it's not present at the error site.

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs (hunk 1 above)
Comment (aliemjay) [reply compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs]: This looks like T-lang issue. Can we open a new issue and nominate it for t-lang?

Anyway  I toned down the FIXME comment and opened a new ticket for it #104767. See also #103640.

**Comment by lcnr** [comment]
While this PR unblocks future work, it's only user-facing impact is that we now check the constraints used **to** normalize projections in user-types during borrowck. We do not yet check that the types used in projections themselves are well-formed.

That is implemented #104746 which needs a separate crater run. We found a single regression on crater as stated in https://github.com/rust-lang/rust/pull/101947#issuecomment-1321915979.

```rust
trait Trait {
    type Ty;
}

impl Trait for &'static () {
    type Ty = ();
}
impl<'a, 'b> Trait for &'a &'b () {
    type Ty = ();
}

fn ok_to_err<'a>() {
    None::<<&'a () as Trait>::Ty>;
    //~^ ERROR lifetime may not live long enough
}

fn still_accepted<'a>() {
    None::<<&'a &'static () as Trait>::Ty>;
    // The `'a: 'static` bound is part of the WF requirements
    // of `&'a &'static ()`, not a bound on the impl.
}
```

@rfcbot fcp merge

File: compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs [hunk 4]
```diff
@@ -282,19 +281,38 @@ impl<'a, 'tcx> AstConv<'tcx> for FnCtxt<'a, 'tcx> {
...
+///
+/// This is a bridge between the interface of `AstConv`, which outputs a raw `Ty`,
+/// and the API in this module, which expect `Ty` to be fully normalized.
+#[derive(Clone, Copy, Debug)]
+pub struct RawTy<'tcx> {
+    pub raw: Ty<'tcx>,
+
+    /// The normalized form of `raw`, stored here for efficiency.
+    pub normalized: Ty<'tcx>,
+}
```
Comment (aliemjay) [inline compiler/rustc_hir_typeck/src/fn_ctxt/mod.rs:318]:
```suggestion
struct RawTy<'tcx> {
    raw: Ty<'tcx>,

    /// The normalized form of `raw`, stored here for efficiency.
    normalized: Ty<'tcx>,
}
```

File: src/test/ui/nll/user-annotations/normalization-2.rs [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    Struct {},
+    Dumb(T),
+}
+
+impl<T> MyTy<T> {
+    fn method<X>() {}
+    fn method2<X>(&self) {}
+}
+
+type Ty<'a> = <&'a () as Trait>::Assoc;
```
Comment (aliemjay) [inline src/test/ui/nll/user-annotations/normalization-2.rs:30]: add a similar test for inherent associated types. cc #105315.
```suggestion
type Ty<'a> = CustomTy::<'a>::Assoc;
```

**Comment by aliemjay** [comment]
The FCP has been stale for a while, going to nominate it for further discussion
@rustbot label I-types-nominated

**Comment by aliemjay** [comment]
needs a rebase and some minor tweaks
@rustbot author

**Comment by aliemjay** [comment]
@rust-timer queue

**Comment by lqd** [comment]
@rust-timer build abb2387f077f4fc60458a49b60eefae2def2b46d

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (aliemjay) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs]: This was indeed problematic. I have fixed it in https://github.com/rust-lang/rust/pull/101947/commits/e05158d6c8b0ca62888140195a93a3487572b028.
