### PR TITLE
Fix borrow checker unsoundness with unions 

### LINKED ISSUE #45157: Borrow checker unsoundness with unions
```rust
#![allow(unused)]

#[derive(Clone, Copy, Default)]
struct S {
    a: u8,
    b: u8,
}
#[derive(Clone, Copy, Default)]
struct Z {
    c: u8,
    d: u8,
}

union U {
    s: S,
    z: Z,
}

fn main() { unsafe {
    let mut u = U { s: Default::default() };
    
    let mref = &mut u.s.a;
    let err = &u.z.c; // This line compiles, but it certainly shouldn't ...
    drop(mref); // ... (at least if `mref` is used after `err`)
}}
```

"Cousins" of borrowed union sub-fields (and their further children) are not marked as borrowed.
~~The same bug should happen with move checking as well, but I haven't made an example yet.~~

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #45157. After discussion with @nikomatsakis on Gitter, this PR only adds a test since the original issue was resolved elsewhere.

r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
Renamed this to be "WIP" since I've seen it fail some `compile-fail` errors that I'll need to look into.

File: src/test/ui/issue-45157.rs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    s: S,
+    z: Z,
+}
+
+fn main() {
+    unsafe {
+        let mut u = U { s: Default::default() };
+
+        let mref = &mut u.s.a; //~ ERROR cannot assign twice to immutable variable `mref` [E0384]
+        let err = &u.z.c; //~ ERROR cannot assign twice to immutable variable `err` [E0384]
```
Comment (matthewjasper) [inline src/test/ui/issue-45157.rs]: The code as is should compile with nll. There needs to be a second use of mref to keep the borrow active for the second assignment.

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -1635,9 +1635,19 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                            // different locals from a union
+                            debug!("place_element_conflict: STUCK-UNION-LOCAL");
+                            Overlap::Arbitrary
+                        },
+                        _ => {
+                            // different locals - base case, disjoint
+                            debug!("place_element_conflict: DISJOINT-LOCAL");
+                            Overlap::Disjoint
+                        },
+                    }
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: I think this is not quite right. Local variables should always be disjoint from one another. For example, borrowing `x` while `y` is borrowed should never be an error, no matter the type of `x`.

**Comment by davidtwco** [comment]
Going to modify this PR to add a test to handle the case @nikomatsakis mentioned in the issue since whichever problem this issue originally referred to is now being handled.

File: src/test/ui/issue-45157.stderr [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+  --> $DIR/issue-45157.rs:37:20
+   |
+34 |         let mref = &mut u.s.a;
+   |                    ---------- mutable borrow occurs here
+...
+37 |         let nref = &u.z.c;
+   |                    ^^^^^^ immutable borrow occurs here
+
+error[E0502]: cannot borrow `u.s.a` as mutable because it is also borrowed as immutable
+  --> $DIR/issue-45157.rs:39:27
```
Comment (nikomatsakis) [inline src/test/ui/issue-45157.stderr]: This second error is a bit surprising. I don't quite understand what it is saying, it looks a bit fishy.

cc @pnkfelix -- agreed?

Comment (pnkfelix) [reply src/test/ui/issue-45157.stderr]: Are you saying that there should be no error here at all? Or just that the error should be focused on prefixes of the field projections it is currently highlighting?

Comment (nikomatsakis) [reply src/test/ui/issue-45157.stderr]: I do not think there should be an error at all, and certainly not with these spans. Usually something like this:

```rust
let mut a = 2;
let mref = &mut a;
let nref = &a;
println("{}{}", mref, nref);
```

gives only one error, right?

i.e., one borrow comes first, and it "wins"

Comment (nikomatsakis) [reply src/test/ui/issue-45157.stderr]: Example: https://play.rust-lang.org/?gist=695ae34722e06a4060c38df82a45c92d&version=nightly

Comment (davidtwco) [reply src/test/ui/issue-45157.stderr]: So, looking into this a little bit, here's what I know - this error is reported in the function below:

Comment (davidtwco) [reply src/test/ui/issue-45157.stderr]: So, looking into this a little bit, here is what I've figured out:

https://github.com/rust-lang/rust/blob/fd0f29237c9562efef25fb30f03df24edb1e2042/src/librustc_mir/util/borrowck_errors.rs#L225-L247

The error is reported in the above function. That is called by the following function:

https://github.com/rust-lang/rust/blob/fdecb0564b86f6876124903a05e590e929532039/src/librustc_mir/borrow_check/error_reporting.rs#L259-L272

This is quite similar to the work done for #47607, in that PR, I added a set that contains the place/span of any errors reported so that they aren't reported again. In this case, the span on line 37 on the below error (that we want) would be in this set:

```
error[E0502]: cannot borrow `u.z.c` as immutable because it is also borrowed as mutable
  --> src/main.rs:37:20
   |
34 |         let mref = &mut u.s.a; //~ ERROR cannot assign twice to immutable variable `mref` [E0384]
   |                    ---------- mutable borrow occurs here
...
37 |         let nref = &u.z.c; //~ ERROR cannot assign twice to immutable variable `err` [E0384]
   |                    ^^^^^^ immutable borrow occurs here
```

I'm not entirely sure what the unintended side effects of the following might be, but we could check if the `issued_span` is in the set (in the above example, that is the error on line 34, but in the second unintended error, that would refer to the same location as above on line 37) and if it is, skip this error. It would essentially silence errors that overlap where the second borrow location of the first error is the first borrow location in subsequent errors. Thoughts?

Comment (nikomatsakis) [reply src/test/ui/issue-45157.stderr]: @davidtwco do you think you could gist the output from `-Zdump-mir=nll` for this function?

Comment (davidtwco) [reply src/test/ui/issue-45157.stderr]: @nikomatsakis is this what you're looking for?

Comment (nikomatsakis) [reply src/test/ui/issue-45157.stderr]: yep but I was hoping for a gist :) kind of hard to digest inline...

Comment (nikomatsakis) [reply src/test/ui/issue-45157.stderr]: updated your comment =)

Comment (davidtwco) [reply src/test/ui/issue-45157.stderr]: Here is a [gist](https://gist.github.com/davidtwco/22dafecab494c823e94661743aa966a6) with some logging added in `access_place` and `check_access_for_conflict` that should show the variable values.

**Comment by pietroalbini** [comment]
@nikomatsakis ping from triage!

**Comment by nikomatsakis** [comment]
So I did a bit of digging here, IIRC, and found that the strange errors arose from two-phase borrows. I did not however get far enough to decide if this was a distinct bug or what.

**Comment by pietroalbini** [comment]
@nikomatsakis and @rust-lang/compiler, can we get a review on this?

**Comment by nikomatsakis** [comment]
I was still hoping that @pnkfelix would weigh in. But I still hope to carve out some time to dig in to the two-phase borrow logic and try to understand *just why* it's triggering in the way that it is and how we can improve it.

**Comment by pnkfelix** [comment]
@nikomatsakis oh, sorry, I didn't know you were still waiting on further input from me

**Comment by nikomatsakis** [comment]
@pnkfelix so I think the problem was that whenever we saw a Gen bit for an activation, we treated that as an activation that needs checking. I think that should only be required for loans that are not already activated. I made that change in the most recent commit. Can you review it?

**Comment by nikomatsakis** [comment]
hmm, in [gitter just now](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5a8d89007685a046389bd65f), @pnkfelix and I were saying we had some concern about the possibility of an activation being overlooked due to an activation from a previous loop

**Comment by nikomatsakis** [comment]
So it seems like what we need is some way to know when one activation is dominated by another (in which case it can be ignored). Because activations are "unioned" on control-flow join, we don't get that for free. Annoying. We could make  a "must be activated" dataflow, but it feels like overkill to me.

**Comment by nikomatsakis** [comment]
That said, this seems orthogonal from the original PR. Why don't we do this -- I'll peel off my last two commits and we'll open up a separate issue to discuss the extra errors resulting from two-phase borrows. Then we can land this PR, which fixes a legit problem.

**Comment by nikomatsakis** [comment]
I opened #48418
