### PR TITLE
Autodiff flags

### LINKED ISSUE #139471: autodiff fails when differentiating two identical functions
I tried this code:

```rust
#![feature(autodiff)]

    use std::autodiff::autodiff;

    #[autodiff(d_square, Reverse, Duplicated, Active)]
    fn square(x: &f64) -> f64 {
        x * x
    }

    #[autodiff(d_square2, Reverse, Duplicated, Active)]
    fn square2(x: &f64) -> f64 {
        x * x
    }

fn main() {
    let x = 3.0;
    let mut dx = 1.0;
    d_square(&x, &mut dx, 1.0);
    d_square2(&x, &mut dx, 1.0);
}

```

I expected to see this happen: `d_square` and `d_square2` should both compute the derivative of x*x, thus 2.0 * x. However, LLVM (or something earlier?) recognizes that square and square2 are identical, and fuses them (ReplaceAllUsesWith, or RAUW for LLVM). autodiff then is missing a (source) function to differentiate, giving the following error. This is often happening in our test cases, where we just test the same dummy functions in a lot of different configurations.

Instead, this happened: 
```
error: failed to prepare autodiff: src: _ZN2ad7square217h920417192f1e5f52E, target: _ZN2ad9d_square217he1a6ffbcf6ea74f2E, could not find source function

```

### Meta

`rustc --version --verbose`:
```
build from source
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

Tracking:

- https://github.com/rust-lang/rust/issues/124509

### PR DESCRIPTION
**Pull request by ZuseZ4**
Interestingly, it seems that some other projects have conflicts with exactly the same LLVM optimization passes as autodiff. 
At least `LLVMRustOptimize` has exactly the flags that we need to disable problematic opt passes.

This PR enables us to compile code where users differentiate two identical functions in the same module. This has been especially common in test cases, but it's not impossible to encounter in the wild. 

It also enables two new flags for testing/debugging. I consider writing an MCP to upgrade PrintPasses to be a standalone -Z flag, since it is *not* the same as `-Z print-llvm-passes`, which IMHO gives less useful output. A discussion can be found here: [#t-compiler/llvm > Print llvm passes. @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/187780-t-compiler.2Fllvm/topic/Print.20llvm.20passes.2E/near/511533038)

Finally, it improves `PrintModBefore` and `PrintModAfter`. They used to work reliable, but now we just schedule enzyme as part of an existing ModulePassManager (MPM). Since Enzyme is last in the MPM scheduling, PrintModBefore became very inaccurate. It used to print the input module, which we gave to the Enzyme and was great to create llvm-ir reproducer. However, lately the MPM would run the whole `default<O3>` pipeline, which heavily modifies the llvm module, before we pass it to Enzyme. That made it impossible to use the flag to create llvm-ir reproducers for Enzyme bugs. We now schedule a PrintModule pass just before Enzyme, solving this problem.

Based on the PrintPass output, it also _seems_ like changing `registerEnzymeAndPassPipeline(PB, true);` to `registerEnzymeAndPassPipeline(PB, false);` has no effect. In theory, the bool should tell Enzyme to schedule some helpful passes in the PassBuilder. However, since it doesn't do anything and I'm not 100% sure anymore on whether we really need it, I'll just disable it for now and postpone investigations. 

r? @oli-obk 

closes #139471

Tracking:

- https://github.com/rust-lang/rust/issues/124509

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/back/write.rs [hunk 1]
```diff
@@ -576,12 +577,14 @@ pub(crate) unsafe fn llvm_optimize(
     // optimizations until after differentiation. Our pipeline is thus: (opt + enzyme), (full opt).
     // We therefore have two calls to llvm_optimize, if autodiff is used.
     if consider_ad && autodiff_stage != AutodiffStage::PostAD {
+        merge_functions = false;
```
Comment (oli-obk) [inline compiler/rustc_codegen_llvm/src/back/write.rs:585]: is there a way to do this on a per-function basis with some llvm attribute?

Comment (ZuseZ4) [reply compiler/rustc_codegen_llvm/src/back/write.rs:585]: Ok, after some experimenting I think it's not worth the cost here. Setting hasExternalLinkage will cause our body to be dropped (since it should be linked externally), so we drop/delete the function which we want to differentiate. That's a very effective way of preventing merging, but kind of problematic if we want to differentiate it. I could insert a random intrinsic and generate some arguments for it and add the Distinct metadata to one of the arguments, but I think the body of our dummy functions is already messy enough and I'd rather spend time towards moving to the declaration, which will sidestep this problem.
