### PR TITLE
fix #124714 str.to_lowercase sigma handling

### LINKED ISSUE #124714: Sometimes 'Σ' is not handled correctly in str.to_lowercase()
Hello,
Due to the optimization introduced with #97046, the `to_lowercase` conversion of some `str` containing the `Σ` char is incorrect.

Simple example:
```rust
fn main(){
    println!("{}", "aΣ".to_lowercase());
    println!("{}", "abcdefghijklmnopΣ".to_lowercase());
}
```
output:
```
aς
abcdefghijklmnopσ
```
The first conversion is correct while the second is not and should be `abcdefghijklmnopς`.

More generally, this happens when 'Σ' follows a `2 * USIZE_SIZE * K` number of chars
```rust
use std::mem;

const USIZE_SIZE_BY_2: usize = 2 * mem::size_of::<usize>();
const K: usize = 1;

fn main() {
    let bug_string = "a".repeat(USIZE_SIZE_BY_2 * K) + "Σ";

    println!("{}", bug_string.to_lowercase());
}
```

### PR DESCRIPTION
**Pull request by Marcondiro**
Hello,
This PR fixes issue #124714 about 'Σ' handling in `str.to_lowercase()`.
The fix consists in considering the full original string during 'Σ' handling instead of considering just the substring left after the optimized ascii handling.
A new test is added to avoid regression.
Thanks!

### CODE REVIEW

File: library/alloc/src/str.rs [hunk 1]
```diff
@@ -368,21 +368,17 @@ impl str {
...
 
-        // Safety: we know this is a valid char boundary since
-        // out.len() is only progressed if ascii bytes are found
-        let rest = unsafe { self.get_unchecked(out.len()..) };
-
         // Safety: We have written only valid ASCII to our vec
         let mut s = unsafe { String::from_utf8_unchecked(out) };
 
-        for (i, c) in rest[..].char_indices() {
+        for (i, c) in self.char_indices().skip(s.len()) {
```
[the remark this answers is not in the document]
Comment (Marcondiro) [reply library/alloc/src/str.rs]: Good point, fixed thanks!
In the new version, since `out` is moved, I recompute `out.len()` from `self.len() - rest.len()`. The 'Σ' case is unlikely so I chose not to copy `out.len()`. But if you think it is preferable to make a copy of `out.len()` before moving instead I'll change that.

File: library/alloc/src/str.rs [hunk 2]
```diff
@@ -400,13 +402,13 @@ impl str {
...
-        fn map_uppercase_sigma(from: &str, i: usize, to: &mut String) {
+        fn map_uppercase_sigma(from: &str, i: usize) -> char {
             // See https://www.unicode.org/versions/Unicode7.0.0/ch03.pdf#G33992
             // for the definition of `Final_Sigma`.
             debug_assert!('Σ'.len_utf8() == 2);
             let is_word_final = case_ignorable_then_cased(from[..i].chars().rev())
                 && !case_ignorable_then_cased(from[i + 2..].chars());
-            to.push_str(if is_word_final { "ς" } else { "σ" });
+            if is_word_final { 'ς' } else { 'σ' }
         }
```
Comment (joboet) [inline library/alloc/src/str.rs:412]: Actually, I think the old version is better here, as it avoid having to encode the `char` to UTF-8 and can simply do a memory store. Would you mind going back the the old version or returning a `&'static str` instead?

Comment (Marcondiro) [reply library/alloc/src/str.rs:412]: I had a look to the assembly and actually the compiler produces a very optimized code tailored to the only 2 possible values returned by the function, it all boils down to a `or` and two `move` to memory
If you wish you can have a look here at a short example https://godbolt.org/z/3vrq6114q

Comment (joboet) [reply library/alloc/src/str.rs:412]: Yeah, you're right! In that case, this is fine (and perhaps even a bit neater).

**Review by joboet — APPROVED** [review]
Very cool, thank you!
@bors r+

**Comment by Marcondiro** [comment]
Maybe bors missed the command

@bors r=joboet

**Comment by joboet** [comment]
Let's try again then!
@bors r+
