### PR TITLE
rustc_typeck: correctly compute `Substs` for `Res::SelfCtor`.

### LINKED ISSUE #61882: With a generic struct, `Self(x)` works where `x` is of the wrong type argument
In particular, we can write:

```rust
struct A<T>(T);

impl A<bool> {
    const B: A<u8> = Self(0); // OK but shouldn't be?

    const C: A<u8> = Self { 0: 0 }; // Correctly rejected.
}
```

This can lead to the following interesting situation:
```rust
struct A<T>(T);

impl A<bool> {
    const B: Self = Self(0); // Rejected, so `Self(..)` is not of type `Self`?
}
```

cc @petrochenkov, @varkor, @eddyb, and @alexreg 

This does seem like a bug to me... In particular, `type_alias_enum_variants` does not allow `Self::Some(transform(x))` where `Self == Option<T>` but where `Option<U>` is expected.

cc @rust-lang/lang

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #61882.

r? @petrochenkov cc @varkor

### CODE REVIEW

File: src/test/ui/issues/issue-61882.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+struct A<T>(T);
+
+impl A<bool> {
+    const B: A<u8> = Self(0);
+    //~^ ERROR mismatched types
+    //~| ERROR mismatched types
```
Comment (Centril) [inline src/test/ui/issues/issue-61882.rs]: Would be good to add the `const B: Self = Self(0);` case also for some redundancy?

I don't know what an interesting test for `A<&'static T>` would be... I have:

```rust
impl A<&'static u8> {
    fn f() -> Self {
        let x = 0;
        Self(&x)
    }
}
```

it fails with "cannot return value referencing local variable `x`".

Comment (eddyb) [reply src/test/ui/issues/issue-61882.rs]: You can't return it. Try `Self(&x);` - that should still error, even if you're not returning it.

Comment (Centril) [reply src/test/ui/issues/issue-61882.rs]: Ah good call; it doesn't error:
```rust
struct A<T>(T);

impl A<&'static u8> {
    fn f() {
        let x = 0;
        Self(&x);
    }
}
```
so you can add that to the test file.

**Comment by petrochenkov** [comment]
r=me with tests requested by Centril

File: src/test/ui/issues/issue-61882.rs (hunk 1 above)
Comment (Centril) [reply src/test/ui/issues/issue-61882.rs]: Decided to check your branch out to help speed things up... but `Self(&x);` for `impl A<&'static u8> {` still does not error.

Comment (eddyb) [reply src/test/ui/issues/issue-61882.rs]: It does error, but it needs to be in a separate test because it doesn't borrow-check `A::f` if `A::B` doesn't type-check (we should probably remove this limitation and keep going? cc @estebank)

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. accepting for beta-backport.

**Comment by pietroalbini** [comment]
@eddyb there are conflicts applying this to the beta branch. Is this partial diff for `src/librustc_typeck/check/mod.rs` correct?

```diff
@@ -5255,12 +5209,8 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
 
         let tcx = self.tcx;
 
-        let res = match self.rewrite_self_ctor(res, span) {
-            Ok(res) => res,
-            Err(ErrorReported) => return (tcx.types.err, res),
-        };
         let path_segs = match res {
-            Res::Local(_) | Res::Upvar(..) => Vec::new(),
+            Res::Local(_) | Res::Upvar(..) | Res::SelfCtor(_) => vec![],
             Res::Def(kind, def_id) =>
                 AstConv::def_ids_for_value_path_segments(self, segments, self_ty, kind, def_id),
             _ => bug!("instantiate_value_path on {:?}", res),

```

**Comment by eddyb** [comment]
@pietroalbini Yes, that seems correct. I could take a look at a backported PR, or open a backport PR myself if you prefer that.
