### PR TITLE
fix(resolve): update the ambiguity glob binding as warning recursively

### LINKED ISSUE #47525: Ambiguous name after glob import is not an error
User `mattscode` from irc reported that the following code compiles, and seems to pick a favourite between identical names. We agree we expect this to be a compile error:

[(playground link)](https://play.rust-lang.org/?gist=bb2eb7e2ceb32cc64c0c4509aef7445a&version=stable)
```rust
fn main() {
    use a::*;
    x();
    // a::x(); // This fails to compile due to an ambiguous x
}

mod a {
    mod b {
        pub fn x() { println!(module_path!()); }
    }
    mod c {
        pub fn x() { println!(module_path!()); }
    }
    
    pub use self::b::*;
    pub use self::c::*;
}
```

It compiles, and when run it outputs:

```
playground::a::b
```

Note that `x()` is not an error and picks `b::x` as the preferred `x`. Calling `a::x()` is an ambiguity error, as expected.

This bug exists in at least:

* rustc 1.23.0
* rustc 1.25.0-nightly (da569fa9d 2018-01-16)

### LINKED ISSUE #56593: Wildcard import fails to resolve if a derive is present
The following snippet fails to compile with the error `[E0412]: cannot find type Foo in this scope`

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d954ef6f84f0d1df4e5c4791c7716da9

```rust=
struct Foo;          // line 1

mod foo {
    use super::*;    // line 4
    
    // Commenting out the Debug derive makes it work
    #[derive(Debug)] // line 7
    pub struct Foo;
}

mod bar {
    use super::foo::*;
    
    fn bar(_: Foo) {}
}
```

Expected result: code compiles without issues

I can get it to compile by doing one of those:
* by removing `use super::*` on line 4
* by commenting `#[derive(Debug)]` at line 7
* by renaming `struct Foo` on line 1 to `Foo2`
* and curiously, by copy-pasting the generated Debug impl obtained with --pretty=expanded instead of using `#[derive(Debug)]`

The same issue happens with other derives (Clone,Eq,etc.). Seems like `#[derive()]` is confused when an item with the same name is visible?

### LINKED ISSUE #98467: Order of glob imports affects whether an ambiguity is reported
The following code (2015 edition, a subset of [/src/test/ui/imports/duplicate.rs](https://github.com/rust-lang/rust/blob/fdca237d5194bf8a1c9b437ebd2114d1c2ba6195/src/test/ui/imports/duplicate.rs), [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=2ea93b416ad1ddc421e04be07754301b)) compiles:

```rust
mod a {
    pub fn foo() {}
}

mod b {
    pub fn foo() {}
}

mod f {
    pub use a::*;
    pub use b::*;
}

mod g {
    pub use a::*;
    pub use f::*;
}

fn main() {
    g::foo();
}
```

If you reorder the glob imports in `g`, it does not compile ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=3c8f81eaa9631599bb796cec5d22283)):

```
error[E0659]: `foo` is ambiguous
  --> src/main.rs:20:8
   |
20 |     g::foo();
   |        ^^^ ambiguous name
   |
   = note: ambiguous because of multiple glob imports of a name in the same module
note: `foo` could refer to the function imported here
  --> src/main.rs:10:13
   |
10 |     pub use a::*;
   |             ^^^^
   = help: consider adding an explicit import of `foo` to disambiguate
note: `foo` could also refer to the function imported here
  --> src/main.rs:11:13
   |
11 |     pub use b::*;
   |             ^^^^
   = help: consider adding an explicit import of `foo` to disambiguate
```

Both versions failed to compile prior to 1.32.0.

I found this while looking at #97584/#47525, which looks very related, but regressed earlier (1.15) - I have a WIP fix for that issue, but it fails on the linked UI test because it makes this error again. I'm mostly opening this to double-check that this change wasn't deliberate (since [the change to the UI test's output was blessed](https://github.com/rust-lang/rust/pull/57199/files#diff-b63ad8afd26349ed288a7f39c920eb5ee9dd08897934cd0655fb0f5446549163)).

@rustbot label C-bug T-compiler A-resolve regression-from-stable-to-stable

### LINKED ISSUE #105235: Type is not exported if type with same name is introduced via use
I'm seeing a strange issue where a type is not being exported from a module if that module imports a type with the same name. Here is an example that demonstrates this issue:

```rust
mod abc {
    pub struct Beeblebrox;
    pub struct Zaphod;
}

mod foo {
    pub mod bar {
        use crate::abc::*;
        
        #[derive(Debug)]
        pub enum Zaphod {
            Whale,
            President,
        }
    }

    pub use bar::*;
}
mod baz {
    pub fn do_something() {
        println!("{:?}", crate::foo::Zaphod::Whale);
    }
}

fn main() {
    baz::do_something();
}
```

In module `bar`, we're importing `abc::Zaphod`, and then defining a type of the same name. When exporting everything from `bar` via `pub use bar::*`, the `Zaphod` type is not exported. Is this expected behavior? It seems wrong to me.

I would have expected the type that's actually declared in `bar` to take precedence and be exported. Either that, or the compiler should emit a useful error describing the collision. At present, the type is silently omitted.

### Meta

```
rustc 1.67.0-nightly (215e3cd21 2022-11-03)
binary: rustc
commit-hash: 215e3cd218b83b8a3152d84d92f17109253c25e1
commit-date: 2022-11-03
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

<details><summary>Backtrace</summary>
<p>

```
Compiling playground v0.0.1 (/playground)
error[[E0433]](https://doc.rust-lang.org/nightly/error-index.html#E0433): failed to resolve: could not find `Zaphod` in `foo`
  --> src/main.rs:20:38
   |
20 |         println!("{:?}", crate::foo::Zaphod::Whale);
   |                                      ^^^^^^ could not find `Zaphod` in `foo`

warning: unused import: `crate::abc::*`
 --> src/main.rs:8:13
  |
8 |         [use crate::abc::*;](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1980019cec4c271a2bfddb14e2f016f0#)
  |             ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
warning: `playground` (bin "playground") generated 1 warning
error: could not compile `playground` due to previous error; 1 warning emitted
```

</p>
</details>

### LINKED ISSUE #112713: Ambiguous item error fails to trigger when use is declared before the source
With the following code:
```rust
pub fn foo() -> u32 {
    use sub::*;
    C
}

mod sub {
    mod mod1 { pub const C: u32 = 1; }
    mod mod2 { pub const C: u32 = 2; }

    pub use mod1::*;
    pub use mod2::*;
}
```

We expected to see [this compiler error](https://doc.rust-lang.org/stable/error_codes/E0659.html).

Instead, the compiler accepts it and `foo()` returns `1`. We found that if you move `foo` below `sub`, you do get the expected error. @ComputerDruid and I took a while to repro this, because we assumed that the order in which you define functions/modules shouldn't change the semantics. It appears that glob re-exports are also necessary for this behavior to occur. If you change it to:
```rust
    pub use mod1::*;
    pub use mod2::C;
```
The explicit one will shadow the glob regardless of where `foo` is defined, and if you make both explicit, it'll trigger [this error](https://doc.rust-lang.org/stable/error_codes/E0252.html).

You can see the difference if you uncomment the bottom function in [this playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f1bc7130c5c3b6e9020052ef1fff06c9). Even changing the import within `foo` to `use sub::C` will make it trigger the expected ambiguous item error, so both of the re-exports _and_ the import have to be globs to see the weird behavior.

This may be a separate issue, but in the accepted code if you swap the order of the glob re-exports in `sub`, `foo()` will return `2`, suggesting that whichever one is re-exported first "wins".

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
```
(same behavior on nightly)

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #47525
Fixes #56593, but ﻿`issue-56593-2.rs` is not fixed to ensure backward compatibility.
Fixes #98467
Fixes #105235
Fixes #112713

This PR had added a field called `warn_ambiguous` in `NameBinding` which is only for back compatibly reason and used for lint.

More details: https://github.com/rust-lang/rust/pull/112743

r? @petrochenkov

### CODE REVIEW

File: tests/ui/resolve/issue-56593-2.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    Foo,
+}
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn test_thing() {
+        let thing = Thing::Foo;
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-56593-2.rs:16]: break change:
- before: `root::Thing` refers to `root::thing::Thing`
- after this PR: `root::Thing` refers to `root::Thing`

**Comment by petrochenkov** [comment]
Meta: not sure why new PR, we could continue in https://github.com/rust-lang/rust/pull/112743, but it's fine too.

File: compiler/rustc_resolve/src/lib.rs [hunk 2]
```diff
@@ -660,6 +660,8 @@ impl<'a> fmt::Debug for ModuleData<'a> {
 struct NameBinding<'a> {
     kind: NameBindingKind<'a>,
     ambiguity: Option<(&'a NameBinding<'a>, AmbiguityKind)>,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:662]:
```suggestion
    ambiguity: Option<(&'a NameBinding<'a>, AmbiguityKind, bool)>,
```
The warning flag only makes sense if there is ambiguity.

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (petrochenkov) [inline tests/ui/resolve/issue-56593-2.rs:16]: This code is not tested due `#[cfg(test)]` and `#[test]`, it's better to remove both, they are not needed here.

Comment (petrochenkov) [inline tests/ui/resolve/issue-56593-2.rs:16]:
```suggestion
        let thing: crate::Thing = Thing::Foo;
```
To make sure the types match.

**Comment by bvanjoi** [comment]
> not sure why new PR

Ahh, just because I feel there are some differences in the way they are implemented, perhaps the new PR can provide a clearer message. Of course, this matter is not important, and we don't need to dwell on it.

File: tests/ui/resolve/issue-112743.stderr [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+   |
+LL |     id();
+   |     ^^ ambiguous name
+   |
+   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+   = note: ambiguous because of multiple glob imports of a name in the same module
+note: `id` could refer to the function imported here
+  --> $DIR/issue-112743.rs:23:5
+   |
+LL | use openssl::*;
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply tests/ui/resolve/issue-112743.stderr:12]: @petrochenkov What are your thoughts on this? Should we explore a method to remove the extra `﻿alloc_name_binding`?

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 4]
```diff
@@ -120,6 +122,20 @@ fn reduce_impl_span_to_impl_keyword(sm: &SourceMap, impl_span: Span) -> Span {
     sm.span_until_whitespace(impl_span)
 }
 
+struct AmbiguousErrorDiag {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:125]:
```suggestion
struct AmbiguityErrorDiag {
```
For naming consistency.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 5]
```diff
@@ -120,6 +122,20 @@ fn reduce_impl_span_to_impl_keyword(sm: &SourceMap, impl_span: Span) -> Span {
...
+    name: String,
+    sp: Span,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:127]:
```suggestion
    span: Span,
```

File: compiler/rustc_lint_defs/src/lib.rs [hunk 6]
```diff
@@ -540,6 +540,18 @@ pub enum BuiltinLintDiagnostics {
         /// Span where the same name is also re-exported.
         duplicate_reexport_span: Span,
     },
+    AmbiguousUpdatedGlob {
+        sp: Span,
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/lib.rs:544]:
```suggestion
        diag: AmbiguityErrorDiag,
```

File: compiler/rustc_lint/src/context.rs [hunk 7]
```diff
@@ -952,6 +952,18 @@ pub trait LintContext: Sized {
...
+                    db.span_label(label_span, label_msg);
+                    db.note(note_msg);
+                    db.span_note(b1_span, b1_note_msg);
+                    for help_msg in b1_help_msgs {
+                        db.help(help_msg);
+                    }
+                    db.span_note(b2_span, b2_note_msg);
+                    for help_msg in b2_help_msgs {
+                        db.help(help_msg);
+                    }
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/context.rs:965]: All this logic can be shared between `fn report_ambiguity_error` and this place.
(It can be put into a method on `AmbiguityErrorDiag`, for example.)

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 8]
```diff
@@ -1581,15 +1617,50 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                        format!("{}{}", or, help_msg)
+                    })
+                    .collect::<Vec<_>>(),
+            )
         };
+        let (b1_span, b1_note_msg, b1_help_msgs) = could_refer_to(b1, misc1, "");
+        let (b2_span, b2_note_msg, b2_help_msgs) = could_refer_to(b2, misc2, " also");
+
+        AmbiguousErrorDiag {
+            name: ident.name.to_ident_string(),
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1637]:
```suggestion
            name: ident.to_string(),
```

File: compiler/rustc_resolve/src/imports.rs [hunk 9]
```diff
@@ -327,6 +328,15 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                         } else if !old_binding.vis.is_at_least(binding.vis, this.tcx) {
                             // We are glob-importing the same item but with greater visibility.
                             resolution.binding = Some(binding);
+                        } else if binding.is_ambiguity() && !binding.warning_ambiguity {
+                            resolution.binding =
+                                Some(self.arenas.alloc_name_binding(NameBinding {
+                                    ambiguity: Some((binding, AmbiguityKind::GlobVsGlob)),
+                                    warning_ambiguity: true,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:335]: Looks like `warning_ambiguity` should be set to true in all cases where `old_binding.is_some()`, not just here.

**Comment by petrochenkov** [comment]
Could you also move all the new tests from `ui/resolve` to `ui/imports`?

File: tests/ui/resolve/issue-112743.stderr (hunk 3 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply tests/ui/resolve/issue-112743.stderr:12]: I don't really understand what the new logic is doing and why it inherits from `old_binding`.

If we didn't have to provide backward compatibility we'd just do
```rust
resolution.binding = Some(binding);
```
, if we have to provide backward compatibility it turns into something equivalent to
```rust
resolution.binding = Some(NameBinding { warning_ambiguity: true, ..binding });
```

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs:16]: I found it will throw an ambiguity error after remove `#[cfg(test)]`, it's a bug and I should fix it firstly.

Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs:16]: This problem caused by `use thing::*` arises because `root::Thing`(referencing to `root::thing::Thing`) is defined before expanding `#[derive(Debug)] pub enum Thing { Foo }`. This leads to an ambiguity error when resolve `super::*` in `tests`.  

To solve this issue, I want to introduce a check logic to skip binding as follows: 

```rs
// fn resolve_glob_imports
for (mut key, binding) in bindings {
  // ...
  if import.parent_scope.module.unexpand_invocation.any(|item| item.xxx.ident.name.eq(key.itent.name))  {
    continue ;
  }
  // then try_defined(module, key, binding)
}
```

I want to ask a question: Is there this method correctly? If yes, how can I find the `item.name` from `module.unexpand_inovation`?

Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs:16]: Which ambiguity is reported exactly, `GlobVsExpanded`? `MoreExpandedVsOuter`?

Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs:16]: `GlobVsGlob`

Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs:16]: This error happens after remove `_ if old_binding.is_some() => return t`

For `tests::Foo`, it meets 

```rs
// in clouser of update_resolution
if res != old_binding.res() {
      resolution.binding = Some(this.ambiguity(
          AmbiguityKind::GlobVsGlob,
          old_binding,
          binding,
      ));
  }
```

and `binding` refers to `root::Thing`, `old_binding` refers to `root::thing::Thing`.

Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs:16]: Could you push the code with this error, and without the fix mentioned in https://github.com/rust-lang/rust/pull/113099#discussion_r1248119357?
I'll check it tomorrow.

Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs]: Added, and I have included `issue-56593-3.rs` for comparison.

File: compiler/rustc_resolve/src/imports.rs [hunk 10]
```diff
@@ -297,6 +297,29 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         })
     }
 
+    /// find the nearest ambiguity and update it to warning
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:300]: Ah, that's why you originally placed the flag into `NameBinding`, it applied not just to the current `NameBinding` but to the whole import chain starting from it.
It was a better decision, let's revert to that.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 11]
```diff
@@ -1581,15 +1591,51 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                        format!("{}{}", or, help_msg)
+                    })
+                    .collect::<Vec<_>>(),
+            )
         };
+        let (b1_span, b1_note_msg, b1_help_msgs) = could_refer_to(b1, misc1, "");
+        let (b2_span, b2_note_msg, b2_help_msgs) = could_refer_to(b2, misc2, " also");
+
+        AmbiguityErrorDiag {
+            name: ident.to_string(),
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1611]:
```suggestion
            msg: format!("`{ident}` is ambiguous"),
```
The main message wording is shared between lint and non-lint versions of the diagnostic.

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs]: Let's address all the other comments first, and leave this to the end.
Maybe the issue will resolve itself, like https://github.com/rust-lang/rust/pull/113099#discussion_r1243807278 did.

File: compiler/rustc_resolve/src/imports.rs (hunk 9 above)
Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:334]: I don't understand why it's related to `old_binding`, can you explain it in detail?

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs]: Now let's address this problem: This removal of `_ if old_binding.is_some() => return t` had caused an impact, affecting not only the error in `issue-56593-2.rs` but also the correct behavior in `issue-56593-1.rs` and `issue-105235.rs`.

## Why did `issue-56593-2.rs` work before?

Previously, `tests::Thing` pointed to `root::thing::Thing` because the expansion of the `#[derive(Debug)] enum Thing { Foo }` was postponed until the next stage after resolve `thing::Thing`. This prevented redefinition due to the presence of `_ if old_binding.is_some() => return t`. However, with the removal of this statement, an `GlobVsGlob` error because do `tests::Thing` is defined through `use super::*`,  and it does not know reference `root::Thing` or `root::thing::Thing`.

## How to avoid this problem

I think there are two possible solutions:

### First
Only update the ambiguity error when `old_binding.is_some()`, this code might look like:

```rs
fn update_ambiguity(&self, binding: NameBinding) {
   self.update_resolution(|module,key, (this, resolution)| {
       if let Some(old_binding) = resolution.binding {
           if old_binding.is_glob_import() && binding.is_glob_import() && binding.is_ambiguity() {
                resolution.binding = binding_with_warning_ambiguity;
            }
       }
   });
}

// fn update_resolution
match resolution.binding {
    _ if old_binding.is_some() => {
        for import in module.glob_importers.borrow_mut().iter() {
            let imported_binding = self.import(binding, import);
            let _ = self.update_ambiguity(import.parent_scope.module, key, imported_binding);
        }
        return t
    }
    ...
}
```

This method addresses the fixes for #112713, but does not resolve #56593 and #105235. Furthermore, it may create gaps in the current architecture. But it brings less breaking change.

### Second

Delay the definition of a binding that has the same name in the `unexpand_inovation` under the module. The logic could be as [above comment](https://github.com/rust-lang/rust/pull/113099#discussion_r1248119357)

File: compiler/rustc_lint/src/context.rs (hunk 7 above)
Comment (petrochenkov) [reply compiler/rustc_lint/src/context.rs:966]: This comment wasn't addressed.

**Comment by petrochenkov** [comment]
I think we should drop the https://github.com/rust-lang/rust/pull/113240 part from this PR for now, and focus on the https://github.com/rust-lang/rust/pull/113242 part first.

File: compiler/rustc_resolve/src/imports.rs (hunk 9 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:334]: Because the update mechanism fix is responsible for majority of the regressions, not new glob-vs-glob ambiguities added here.

**Comment by bvanjoi** [comment]
I will try to split this PR to two commit:
1. first commit will use the logic in https://github.com/rust-lang/rust/pull/113242 and try to solve `isuee-56593-x`.
2. second commit will introduce ambiguous warning as the PR describe.

> then figure out why this error is reported for tests/ui/imports/issue-56593-2.rs but not for tests/ui/imports/issue-56593-3.rs.

see https://github.com/rust-lang/rust/pull/113099#discussion_r1248894912, it caused by remove `_ if old_binding.is_some() => return t`.

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs]: >`GlobVsGlob` error because do `tests::Thing` is defined through `use super::*`,  and it does not know reference `root::Thing` or `root::thing::Thing`.

But there's no glob-vs-glob ambiguity there, `root::Thing` is not a glob.
Why is it considered a glob in `issue-56593-2.rs`, but not in `issue-56593-3.rs`?

Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs]: > Why is it considered a glob in issue-56593-2.rs, but not in issue-56593-3.rs?

Due to the presence of `#[derive(Debug)] `.

In `issue-56593-2.rs`, the `resolve_importers` is executed twice. The first execution occurs before macro expand, where `root::Thing` is defined, referring to `root::thing::Thing`. Then, during the second execution of `resolve_importers` during macro expansion, `root::Thing` is resolved again. 
When updating the binding of `(Mod(root::tests), Key(Thing))`, the `binding`(which comes from `super::*`) pointed to `root::Thing`(which comes from the second execution of `resolve_importers`), while the `old_binding` refers to `root::thing::Thing`(which comes from the first execution of `resolve_importers`). Due to this conflicting situation, ambiguity error occurs. 

But in `issue-56593-3.rs`, all resolutions are completed during the first execution of `resolve_importers`.

Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs]: Ok, I see it now.
When the binding in root changes from `root::thing::Thing` to `root::Thing`, glob importers add a *new* binding to `root::tests` instead of replacing the previous one.

Comment (petrochenkov) [reply tests/ui/resolve/issue-56593-2.rs]: Skipping the glob importers part until both `single_imports` and `unresolved_invocations` are empty should be fine, although it's possible that name resolution will stuck and make no progress more often with this scheme, we'll need to test.

In this case we'll still miss glob -> glob updates happening due to `!old_binding.vis.is_at_least(binding.vis, this.tcx)` and `binding.is_ambiguity()` (but it will still be an improvement).

Instead of waiting for `single_imports` / `unresolved_invocations` we could *replace* bindings in glob importers on updates in the source module, it will cover the glob -> glob updates as well.
I'm not sure what effect it will have on some other places returning `Determinacy` values though, like `resolve_ident_in_module_unadjusted_ext`.

File: tests/ui/resolve/issue-112831.rs [hunk 12]
```diff
@@ -10,6 +9,7 @@ use zeroable::*;
 mod pod {
     use super::*;
     pub trait Pod: Zeroable {}
+    //~^ ERROR expected trait, found derive macro `Zeroable`
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-112831.rs:12]: Next, we should address this breaking change.

File: tests/ui/imports/issue-98467.rs [hunk 13]
```diff
@@ -0,0 +1,23 @@
+// check-pass
```
Comment (bvanjoi) [inline tests/ui/imports/issue-98467.rs:1]: FIXME: this should be thrown error

File: tests/ui/resolve/issue-112713.rs [hunk 14]
```diff
@@ -0,0 +1,17 @@
+// edition: 2021
+// check-pass
```
Comment (bvanjoi) [inline tests/ui/resolve/issue-112713.rs:2]: FIXME: this should be thrown error

File: tests/ui/imports/issue-47525.rs [hunk 15]
```diff
@@ -0,0 +1,18 @@
+// check-pass
+
+fn main() {
```
Comment (bvanjoi) [inline tests/ui/imports/issue-47525.rs:3]: FIXME: this should be thrown error

File: tests/ui/imports/issue-112743.rs [hunk 16]
```diff
@@ -0,0 +1,27 @@
+// check-pass
+
+// https://github.com/rust-lang/rust/pull/112743#issuecomment-1601986883
+
+macro_rules! m {
```
Comment (bvanjoi) [inline tests/ui/imports/issue-112743.rs:5]: FIXME: this should be thrown error

File: compiler/rustc_lint/src/context.rs (hunk 7 above)
Comment (bvanjoi) [reply compiler/rustc_lint/src/context.rs]: > shared between fn report_ambiguity_error and this place.

This poses a small issue because `﻿AmbiguityErrorDiag` is defined in ﻿rustc_lint_defs and cannot directly use ﻿`DiagnosticBuilder`. To resolve this, we would need to introduce additional dependencies for ﻿`rustc_lint_defs`. Do you believe it is worthwhile to do so?

File: compiler/rustc_resolve/src/imports.rs [hunk 17]
```diff
@@ -316,11 +316,17 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                 match (old_binding.is_glob_import(), binding.is_glob_import()) {
                     (true, true) => {
                         if res != old_binding.res() {
-                            resolution.binding = Some(this.ambiguity(
-                                AmbiguityKind::GlobVsGlob,
-                                old_binding,
-                                binding,
-                            ));
+                            if let NameBindingKind::Import { import: old_import, .. } = old_binding.kind
+                            && let NameBindingKind::Import { import: current_import, .. } = binding.kind
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:320]:
```suggestion
                                && let NameBindingKind::Import { import, .. } = binding.kind
```

**Comment by bvanjoi** [comment]
> Or the FIXMEs above are just due to https://github.com/rust-lang/rust/pull/113240 being omitted from this PR?

Yes, we can address these by reintroducing the warning for ambiguity.  

> Have you tried the strategy with waiting for single_imports and unresolved_invocations?  

I have tried that:  
```rs 
// fn resolve_glob_import() {  
if module.is_trait() {
    self.tcx.sess.create_err(ItemsInTraitsAreNotImportable { span: import.span }).emit();
    return 0;
} else if ptr::eq(module, import.parent_scope.module) {
    return 0;
} else if is_prelude {
    self.prelude = Some(module);
    return 0;
}  else if import.parent_scope.module.unresolved_invocations.len() > 0 {      
return 3; // means Indeterminate
}
// xxxxx
return 0;
```
And I have made the change to `return self.resolve_glob_importer()` instead of  `self.resolve_glob_importer(); return 0` in the `resolve_import` function.  
 The result is that `stage1` compiled successfully, but some test cases have failed.

**Comment by petrochenkov** [comment]
>Yes, we can address these by reintroducing the warning for ambiguity.

Ah, great, then then first two questions are no longer relevant.

File: compiler/rustc_resolve/src/imports.rs [hunk 18]
```diff
@@ -316,11 +316,17 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                            && ptr::eq(old_import, current_import) {
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:321]: > This condition should be checked first

After moving it to the first position, I discovered that some tests have failed.

- `issue-47525.rs`
- `issue-112743.rs`
- `issue-112713.rs`

They all throw a `﻿GlobVsGlob` error, as expected. However, this is a breaking change.

[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs]: Yes, let's do this change, then run crater.

File: tests/ui/imports/issue-56593-2.rs [hunk 19]
```diff
@@ -0,0 +1,24 @@
...
+#[derive(Debug)]
+pub enum Thing {
+    Foo
+}
+
+mod tests {
+    use super::*;
+
+    fn test_thing() {
+        let thing: crate::Thing = Thing::Foo;
```
Comment (bvanjoi) [inline tests/ui/imports/issue-56593-2.rs:14]: breaking change

File: tests/ui/imports/issue-112713.rs [hunk 20]
```diff
@@ -0,0 +1,17 @@
+// edition: 2021
+
+pub fn foo() -> u32 {
+    use sub::*;
+    C
+    //~^ERROR `C` is ambiguous [E0659]
```
Comment (bvanjoi) [inline tests/ui/imports/issue-112713.rs:6]: breaking change

**Comment by bvanjoi** [comment]
> The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5467068809/jobs/9952897100) [(plain)](https://github.com/rust-lang/rust/commit/ebf2e54b7c6aca620c72c421b3e2f151be1b1b47/checks/14802112101/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)

There was just a positional error in the snapshot. Please ignore it.

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by bvanjoi** [comment]
It appears that we need two lints:
1. `OUTDATED_BINDING`: for `﻿issue-112831.rs` and ﻿`issue-56593-2.rs`.
2. `AMBIGUOUS_GLOB_IMPORTS`

**Comment by bvanjoi** [comment]
Hi @petrochenkov, could you please re-run the regression test to assess the impact of the breaking change in `issue-56593-2.rs`

File: compiler/rustc_resolve/src/imports.rs [hunk 21]
```diff
@@ -308,7 +309,20 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                 }
                 match (old_binding.is_glob_import(), binding.is_glob_import()) {
                     (true, true) => {
-                        if res != old_binding.res() {
+                        if binding.is_ambiguity() {
+                            resolution.binding =
+                                Some(self.arenas.alloc_name_binding(NameBindingData {
+                                    warn_ambiguity: true,
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:315]: maybe not. 

For example, in ﻿`issue-47525.rs`, there is a scenario where an error should be thrown but is not in the master. And it will generate a warning after this PR. The corresponding code is as follows:

```rs
fn main() {
    use a::*;
    x();    // should warning here
}

mod a {
    mod b {
        pub fn x() {  }
    }
    mod c {
        pub fn x() { }
    }

    pub use self::b::*;
    pub use self::c::*;
}
```

The order of ﻿`update_resolution` for the `﻿x` in the diff module is as follows:

| order| `module` | `old_binding` | `binding` |  `binding` after update |
| - | - | - | - | - |
| 1 | `root::a::b` | None |   `root::a::b::x` | same as left |
| 2 | `root::a::c` | None |   `root::a::c::x` | same as left |
| 3 | `root::a`     | None |  `root::a::b::x`  | same as left |
| 4 | `root`         | None |  `root::a::b::x`  | same as left |  
| 5 | `root::a`     | `root::a:b::x` |  `root::a::c::x`  |`root::a:b::x` with ambiguity error |
| 6| `root`          | `root::a::b::x` without error |  `root::a:b::x` with ambiguity error |  ? | 

Focus on this last line:

- if the first condition is `if binding.is_ambiguity() { xxx }` is will generator a warning for ambiguity.
- However, if the first condition is ` xxx && old_import == import { xx }`, it will update `Mod(root), Ident(x)` to the `root::a:b::x` with ambiguity error, resulting in an eventual error being thrown.

[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/imports.rs:315]: >it will update `Mod(root), Ident(x)` to the `root::a:b::x` with ambiguity error, resulting in an eventual error being thrown.

Why will the error be thrown?
`warn_ambiguity: true` should turn that error into a warning.

[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:315]: For this case, it will never allocate a binding with a warning for ambiguity.
Nevertheless, I have updated this code, and it now appears more reasonable.

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
We need to add a back-compat hack for `openssl`, even if a new fixed version of it is released we'll still get a lot of breakage from pinned `openssl` versions from 0.10.39 to 0.10.54.

In `fn finalize_resolutions_in` ambiguous bindings with `warn_ambiguity` should still be pushed to `module_children` (after reporting `ambiguous_glob_imports`).

Also there are some new ICE regressions from `actix-http`.

@rustbot author

**Comment by bvanjoi** [comment]
reduced of `rust-openssl`:

```rs
// issue-113099-1-extern.rs

macro_rules! m {
    () => {
      pub fn id() {}
    };
}

mod openssl {
    pub use self::evp::*;
    pub use self::handwritten::*;

    mod evp {
        m! {}
    }
    mod handwritten {
        m! {}
    }
}

pub use openssl::*;

// ----
// main.rs
// aux-build: issue-113099-1-extern.rs

extern crate issue_113099_1_extern;

fn main() {
    issue_113099_1_extern::id();
}
```

**Comment by petrochenkov** [comment]
Could you check whether `ambiguous_glob_reexports` lint is reported for the openssl reproduction?

If it is reported, then we probably don't need to do this part

> (after reporting `ambiguous_glob_imports`).

**Comment by bvanjoi** [comment]
> Could you check whether ambiguous_glob_reexports lint is reported for the openssl reproduction?

yes, it's reported

File: tests/ui/resolve/issue-56593-2.rs (hunk 1 above)
Comment (bvanjoi) [reply tests/ui/resolve/issue-56593-2.rs]: > replace bindings in glob importers on updates in the source module

This approach causes an ice in `﻿actix-http`, as mentioned in this [comment](https://github.com/rust-lang/rust/pull/113099#issuecomment-1633574396). We need to reconsider this solution.

**Comment by petrochenkov** [comment]
Can we keep the `binding.res() != old_binding.res()` case unfixed for now?

The fix for it will include treating the bindings from globs as not-yet-determinate in more cases when `unexpanded_invocations` are non-empty (either in `resolve_ident_in_module_unadjusted_ext` or in `update_resolution`), but it can be done separately.

**Comment by bvanjoi** [comment]
> Can we keep the binding.res() != old_binding.res() case unfixed for now?

Yes, I agree. We can avoid these breaking changes (the ice in ﻿`actix-http` and ﻿`issue-56593-2.rs`) by making the following change:

```rs
if !binding.is_ambiguity()
    && let NameBindingKind::Import { import: old_import, .. } = old_binding.kind
    && let NameBindingKind::Import { import, .. } = binding.kind 
    && old_import == import { 
        resolution.binding = Some(old_binding); // before is `Some(binding)`
} else if res != old_binding.res() {
   xxxxx
}
```

But I'm concerned that it might break ﻿`tools/miri`. I will test it to ensure compatibility.

**Comment by bvanjoi** [comment]
I have made the following changes:
- change `resolution.binding()` from `resolution.binding` in `update_resolution` and `resolve_glob_import`.
- used `Some(old_binding)` instead of `Some(binding)` when updating the glob binding for the same importer case.


And I have tested ﻿`rust-openssl` and `﻿actix-http` locally, and they compiled successfully.

And there were reports of some ambiguous errors in the regression report. I will investigate and check them.

**Comment by petrochenkov** [comment]
> - change `resolution.binding()` from `resolution.binding` in `update_resolution` and `resolve_glob_import`.
> - used `Some(old_binding)` instead of `Some(binding)` when updating the glob binding for the same importer case.

Why?
This is basically reverting most of the fixes in this PR.

That's not what I meant in https://github.com/rust-lang/rust/pull/113099#issuecomment-1635885482 at all.
I just wanted to skip the `old_import == import` updates in cases when `binding.res() != old_binding.res()` to avoid inconsistent resolution ICEs.

**Comment by petrochenkov** [comment]
Are the new changes a strict subset of the previous changes at least (at the point of the crater run)?
Or we need to run a full crater run again?
I'm losing the track of the changes now.

**Comment by bvanjoi** [comment]
> This is basically reverting most of the fixes in this PR.

Allow me to provide further details on my thoughts:

Currently, we are facing two problems:

1.	We are encountering some errors that should be reported but are not being thrown, such as #112713. One way to address this is by removing ﻿`_ if old_binding.is_some() => return t` and adding ﻿`xxx && old_import === import { resolution.binding = Some(old_binding) }` which aims to prevent `﻿issue-56593-2.rs` from throwing ambiguities. Additionally, this fix resolves a missing reference issue in ﻿`issue-56593-1.rs`.

2.	There are incorrect references in `﻿issue-56593-2.rs`, which can be resolved by changing it to `﻿xxx && old_import === import { resolution.binding = Some(binding) }.` This fix addresses the issues in `﻿issue-113242-2.rs` and ﻿`issue-56593-2.rs`, but it unexpectedly triggered a panic in ﻿`actix-http`. A better solution for these issues might involve differentiating error-determined bindings in ﻿`resolve_glob_importer`, and relying solely on processing in ﻿`update_resolution` may not be the ideal approach.

Additionally, `issue-113242-2.rs` and ﻿`issue-56593-2.rs` exhibit the same behavior as the master branch.

Therefore, the current PR focuses on addressing problem 1 while postponing the resolution of problem 2.

In addition, the modifications made to ﻿`resolution.binding` and ﻿`resolution.binding()` in ﻿`update_resolution` are leading to build failures in ﻿`src/tools/miri`. Therefore, I believe it would be better to address that after resolving issue 2.

> Are the new changes a strict subset of the previous changes at least (at the point of the crater run)?

Yes, I think that. Maybe we should primarily focus on testing the packages that are affected

**Comment by petrochenkov** [comment]
Okay, CI is green, let's rerun crater of the subset that failed previously.
@bors try

TODO: `@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-113099-1/retry-regressed-list.txt`

**Comment by petrochenkov** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-113099-1/retry-regressed-list.txt

**Comment by petrochenkov** [comment]
@craterbot check p=1 crates=https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/8bd3140e395ae5a116644c89c5a40231deeb716e/gistfile1.txt

**Comment by bvanjoi** [comment]
reduced of `openssl@0.10.41`:

```rs
// issue-113099-4-extern.rs
macro_rules! m {
    () => {
      pub fn id() {}
    };
}

pub use self::evp::*;
pub use self::handwritten::*;

mod evp {
    use *;
    m! {}
}
mod handwritten {
    use *;
    m! {}
}

// issue-113099-4.rs
// aux-build:issue-113099-4-extern.rs

extern crate issue_113099_4_extern;

fn main() {
    issue_113099_4_extern::id();
}

```

**Comment by bvanjoi** [comment]
I have marked ﻿`GlobVsGlob` as a warning if it occurs in the update stage in the latest commit.

By the way, I think rerunning the regression test based on https://github.com/rust-lang/rust/pull/112743#issuecomment-1601428757. If everything looks fine, we are ready to proceed with the merge.

@rustbot ready

**Comment by petrochenkov** [comment]
@craterbot check p=1 crates=https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/8bd3140e395ae5a116644c89c5a40231deeb716e/gistfile1.txt

**Comment by bvanjoi** [comment]
reduced of `rust-openssl`:

```rs
pub use evp::*;
pub use handwritten::*;

macro_rules! m {
    () => {
        pub fn id()  {}
    };
}
mod evp {
    use *;
    m!();
}

mod handwritten {
    pub use handwritten::evp::*;
    mod evp {
        use *;
        m!();
    }
}

fn main() {
    id();
}
```

**Comment by bvanjoi** [comment]
The latest commit brings two change:
- I made `update` variable update recursively and treat the binding as `warn_ambigous` when `old_binding` is ambiguous meanwhile.
- I used `try_borrow_mut` for `module.glob_importers`, and returned if it failed.

@rustbot ready

**Comment by petrochenkov** [comment]
@craterbot check p=1 crates=https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/8bd3140e395ae5a116644c89c5a40231deeb716e/gistfile1.txt

**Comment by bvanjoi** [comment]
> remaining 2 regressions

They are caused by `﻿#![deny_warnings]`

**Comment by petrochenkov** [comment]
Excellent.
Then I'll review the code style today-tomorrow and we'll be able to merge this.
@rustbot review

**Comment by bvanjoi** [comment]
But I'm not sure why it causes some "build OOM" cases. Is that common?

**Comment by petrochenkov** [comment]
> But I'm not sure why it causes some "build OOM" cases. Is that common?

Yes, that's common, that's they are marked as spurious and moved to a separate category.

**Comment by bvanjoi** [comment]
Could you please rerun the regression test based on https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/cc4e227ef0fe8d65cc5d107ed84847d7b6bd5a94/gistfile1.txt ? I would like to know if all tests can pass.

**Comment by petrochenkov** [comment]
Looks like a new `@bors try` is not needed.

@craterbot check p=1 crates=https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/cc4e227ef0fe8d65cc5d107ed84847d7b6bd5a94/gistfile1.txt

**Comment by petrochenkov** [comment]
@craterbot check p=1 crates=https://gist.githubusercontent.com/petrochenkov/78c5487fedf991fad040ff42a8a36e69/raw/09f189235571d8fc7111622de9e6136a63b261a4/gistfile1.txt

**Comment by bvanjoi** [comment]
reduced of `holochain`:

```rs
// e.rs
mod a {
  pub mod error {}
}
pub use a::*;

mod b {
  pub mod error {}
}
pub use b::*;

mod c {
  pub mod error {}
}
pub use c::*;

// code.rs
// edition: 2021
// aux-build: e.rs
extern crate e;
pub mod b {
  mod s {
    pub mod error {
      #![allow(missing_docs)]
      use e::*;
    }
  }
  use s::*;
  use e::*;
  use error::*;
}

fn main() {}

```

**Comment by bvanjoi** [comment]
Seems like this case should also throw an ambiguous error, but neither the master branch nor this PR does. We can consider treating them as separate case:

```rs
// e.rs
mod a {
  pub mod error {}
}
pub use a::*;

mod b {
  pub mod error {}
}
pub use b::*;

// code.rs
// edition: 2021
// aux-build: e.rs
extern crate e;
pub mod b {
  mod s {
    pub mod error {
      #![allow(missing_docs)]
      use e::*;
    }
  }
  use s::*;
  use e::*;
  use error::*;
}

fn main() {}
```

**Comment by petrochenkov** [comment]
@bvanjoi 
This example looks like it's related to https://github.com/rust-lang/rust/issues/36837.
Ambiguity items are simply skipped when we encoding module children for other crates (it's what happens in `finalize_resolutions_in`).

So `use e::*` imports nothing (everything is skipped) and doesn't conflict with `use s::*`.
My current stance of https://github.com/rust-lang/rust/issues/36837 is that the current behavior is wrong, and we should encode ambiguities into metadata somehow.

**Comment by bvanjoi** [comment]
> we should encode ambiguities into metadata somehow.

It seems we can easily achieve that by changing the condition from ﻿if `res != def::Res::Err && !binding.is_ambiguity()` to ﻿if `res != def::Res::Err`. However, this change would also be considered a breaking change.

And under this condition, the expected output is to emit an ambiguous error (or warning) for https://github.com/rust-lang/rust/pull/113099#issuecomment-1643974121.

**Comment by bvanjoi** [comment]
I understand why an error was thrown in https://github.com/rust-lang/rust/pull/113099#issuecomment-1643974121. It was caused by relaxed restrictions on the ﻿`update` value set in `﻿resolve_glob_imports`, and the correct value of `update` here should be `false`.  You can find code [here]( https://github.com/rust-lang/rust/pull/113099/files#diff-54ebaa0715c94a2acf974077e838aa584186e187f3d01edb1791fd71c78408caR1394-R1395).

---

Now, let's consider a scenario(reduced of `otter`):

```rs
// extern-file.rs
mod t2 {
  #[derive(Debug)]
  pub enum Error {}

  mod s {
    pub trait Error: Sized {}
  }

  use self::s::*;
}

pub use t2::*;


// code.rs
// aux-build: extern-file.rs
extern crate extern_file;
mod s {
  pub trait Error {}
}

use s::*;
use extern_file::*;
fn a<E: Error>(_: E) {}

fn main() {}
```

This code will compile successfully in the master branch because `﻿(Mod(extern_file), Error)` refers to a private trait that is not exported, resulting in `﻿(Mod(root), Error)` referring to ﻿`root::s::Error`.

But after this PR, something has changed. The ﻿`(Mod(extern_file), Error)` refers to `﻿extern_file::t2::Error` finally due to the resolution being updated multiple times. This change causes ﻿`(Mod(root), Error)` to be marked with an ambiguous tag. Unfortunately, this case will not mark it with a warning because it bypasses the recursive ﻿`update_resolution` process.

**Comment by bvanjoi** [comment]
I have added the ﻿`update` field in `﻿ModChild` to ensure backward compatibility in the latest commit.

@rustbot ready

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/113099/commits/9817992ff6a23853fd37f2a06cbec6419a119c50 isn't worth the complexity, we already reduced the breakage to acceptable range (just one remaining regression), and https://github.com/rust-lang/rust/issues/36837 is better fixed separately.

I suggest removing the last commit (the new tests can stay).
@rustbot author

**Comment by bvanjoi** [comment]
The latest commit removed an [**error** checking logic](https://github.com/rust-lang/rust/pull/113099/commits/9a60f3bbe487a905ad8dee6f1b704f5120fd7a31#diff-54ebaa0715c94a2acf974077e838aa584186e187f3d01edb1791fd71c78408caR1394-R1395) that was previously added from https://github.com/rust-lang/rust/pull/113099/commits/9a60f3bbe487a905ad8dee6f1b704f5120fd7a31. This logic ensured the successful compilation of `otter`([reported here](https://crater-reports.s3.amazonaws.com/pr-113099-3/try%2390ace2a7d7527b6b58cf4aa658dc2a3318774825/reg/otter-1.2.1/log.txt)) compile success.

So, I think a better choice would be to revert the latest commit, remove the error logic, and allow ﻿otter to throw an error.

**Comment by bvanjoi** [comment]
I have reset to commit `﻿9817992` and fixed the logic of the `﻿update` value. Now, ﻿`issue-113099-11-1.rs` (a reduced version of ﻿otter) will throw an error.

@rustbot ready

File: compiler/rustc_resolve/src/lib.rs [hunk 22]
```diff
@@ -1684,18 +1695,36 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+            Some(binding)
+        } else {
+            match binding.kind {
+                NameBindingKind::Import { binding, .. } => self.nearest_ambiguity_binding(binding),
+                _ => None,
+            }
+        }
+    }
+
     fn record_use(&mut self, ident: Ident, used_binding: NameBinding<'a>, is_lexical_scope: bool) {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1709]:
```suggestion
    fn record_use_inner(&mut self, ident: Ident, used_binding: NameBinding<'a>, is_lexical_scope: bool, warn_ambiguity: bool) {
```
No need to do the recursion with `nearest_ambiguity_binding` here, `record_use` is already called recursively below.

It would be simpler to pass the right `warn_ambiguity` to it as an additional argument.
Then do `fn record_use(&mut self, ident: Ident, used_binding: NameBinding<'a>, is_lexical_scope: bool) { self.record_use_inner(ident, used_binding, is_lexical_scope, false) }` for the top level `record_use` for convenience.

File: compiler/rustc_resolve/src/imports.rs [hunk 23]
```diff
@@ -388,15 +439,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
 
             let t = f(self, resolution);
 
-            if old_binding.is_none() && let Some(binding) = resolution.binding() {
+            update = is_update || old_binding.is_some();
+
+            if let Some(binding) = resolution.binding()
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:444]:
```suggestion
            if let Some(binding) = resolution.binding() && old_binding == Some(binding) {
```

File: compiler/rustc_resolve/src/imports.rs [hunk 24]
```diff
@@ -374,12 +405,32 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+        is_update: bool,
+        f: F,
+    ) -> T
     where
         F: FnOnce(&mut Resolver<'a, 'tcx>, &mut NameResolution<'a>) -> T,
     {
+        let update: bool;
         // Ensure that `resolution` isn't borrowed when defining in the module's glob importers,
         // during which the resolution might end up getting re-defined via a glob cycle.
         let (binding, t) = {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:436]:
```suggestion
        let (binding, t, update) = {
```

File: compiler/rustc_resolve/src/imports.rs [hunk 25]
```diff
@@ -388,15 +439,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
 
             let t = f(self, resolution);
 
-            if old_binding.is_none() && let Some(binding) = resolution.binding() {
+            update = is_update || old_binding.is_some();
+
+            if let Some(binding) = resolution.binding()
+            && !old_binding.is_some_and(|old| old == binding) {
                 (binding, t)
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:446]:
```suggestion
                (binding, t, is_update || old_binding.is_some())
```

File: compiler/rustc_resolve/src/imports.rs [hunk 26]
```diff
@@ -388,15 +439,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
 
             let t = f(self, resolution);
 
-            if old_binding.is_none() && let Some(binding) = resolution.binding() {
+            update = is_update || old_binding.is_some();
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:442]: Isn't `old_binding` *always* `Some` when `is_update` is passed?

Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:442]: Yes, in most cases, `﻿is_update` is originally set to ﻿false, and we require ﻿`old_binding.is_some()` to set ﻿update to ﻿true.

By the way, `﻿is_update` was introduced in ﻿`issue-113099-10.rs` to handle a specific scenario where we need to set ﻿update as ﻿true, even if `﻿old_binding` is `﻿None` due to a recursive update.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 27]
```diff
@@ -4380,3 +4381,44 @@ declare_lint! {
     "effective visibility of a type is larger than the area in which it can be named",
     @feature_gate = sym::type_privacy_lints;
 }
+
+declare_lint! {
+    /// The `ambiguous_glob_imports` lint detects the updated glob ambiguous.
```
[the remark this answers is not in the document]
Comment (bvanjoi) [reply compiler/rustc_lint_defs/src/builtin.rs:4386]: Do you think we need to open an issue entitled "tracking issue for `ambiguous_glob_imports`" and include a link to it?

**Comment by bvanjoi** [comment]
Thanks for your review. @rustbot ready

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_lint_defs/src/builtin.rs]: Yes, at least the issue will need to be created sooner or later.

File: compiler/rustc_resolve/src/imports.rs [hunk 28]
```diff
@@ -284,39 +284,69 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
                     (true, true) => {
-                        if res != old_binding.res() {
-                            resolution.binding = Some(this.ambiguity(
-                                AmbiguityKind::GlobVsGlob,
-                                old_binding,
-                                binding,
-                            ));
+                        // FIXME: remove `!binding.is_ambiguity()` after delete the warning ambiguity.
+                        if !binding.is_ambiguity()
+                        && let NameBindingKind::Import { import: old_import, .. } = old_binding.kind
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:316]:
```suggestion
                            && let NameBindingKind::Import { import: old_import, .. } = old_binding.kind
```
Bad formatting (not currently fixed by rustfmt due to `if let` chains).

File: compiler/rustc_resolve/src/imports.rs [hunk 29]
```diff
@@ -374,29 +404,53 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
-        let (binding, t) = {
+        let (binding, t, update) = {
             let resolution = &mut *self.resolution(module, key).borrow_mut();
             let old_binding = resolution.binding();
 
             let t = f(self, resolution);
 
-            if old_binding.is_none() && let Some(binding) = resolution.binding() {
-                (binding, t)
+            if let Some(binding) = resolution.binding()
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:440]:
```suggestion
            if let Some(binding) = resolution.binding() && old_binding != Some(binding) {
```
Bad formatting (not currently fixed by rustfmt due to `if let` chains).

File: compiler/rustc_resolve/src/imports.rs [hunk 30]
```diff
@@ -284,39 +284,69 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
     }
 
     /// Define the name or return the existing binding if there is a collision.
+    /// `update` indicates if the definition is a redefinition of an existing binding.
     pub(crate) fn try_define(
         &mut self,
         module: Module<'a>,
         key: BindingKey,
         binding: NameBinding<'a>,
+        update: bool,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:301]:
```suggestion
        warn_ambiguity: bool,
```
This flag doesn't mean an update anymore (in that case it would always be equal to `old_import == import` and implied `old_binding.is_some()`).
Now it's a flag that is used for downgrading errors into warning, and meaningless otherwise (or has a very convoluted meaning).

Comment (bvanjoi) [reply compiler/rustc_resolve/src/imports.rs:301]: I will both change `update` or `is_update` to `warn_ambiguity`

**Comment by bvanjoi** [comment]
CI is green

@bors r=@petrochenkov

**Comment by petrochenkov** [comment]
It's better to report this to stdarch, but in meantime `ambiguous_glob_reexports` can be allowed on `mod core_arch`.
@rustbot author

**Comment by bvanjoi** [comment]
I have added `﻿#[allow(ambiguous_glob_reexports)]` f ﻿`mod core_arch`.

@rustbot ready

**Comment by bvanjoi** [comment]
As the next step, I will attempt to address the issue at https://github.com/rust-lang/rust/issues/113834.

**Comment by nnethercote** [comment]
Minor regressions for `unused-warnings`, but that is an extreme stress tests that exists mostly to detect catastrophic regressions in error handling, so it's no big deal.

@rustbot label: +perf-regression-triaged

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 31]
```diff
@@ -4405,3 +4406,46 @@ declare_lint! {
...
+    ///
+    /// This is a [future-incompatible] lint to transition this to a
+    /// hard error in the future.
+    ///
+    /// [future-incompatible]: ../index.md#future-incompatible-lints
+    pub AMBIGUOUS_GLOB_IMPORTS,
+    Warn,
+    "detects certain glob imports that require reporting an ambiguity error",
+    @future_incompatible = FutureIncompatibleInfo {
+        reason: FutureIncompatibilityReason::FutureReleaseError,
```
Comment (RalfJung) [inline compiler/rustc_lint_defs/src/builtin.rs:4448]: FWIW this FutureIncompatibilityReason will make the warning only show up in locally built crates, but *not* in cargo's future breakage report that also shows warnings from dependencies. Just making sure that this is a deliberate choice and not an accident. :)

Comment (petrochenkov) [reply compiler/rustc_lint_defs/src/builtin.rs:4448]: I just assumed all future incompatibility lints are reported for dependencies during review.

Comment (RalfJung) [reply compiler/rustc_lint_defs/src/builtin.rs:4448]: No, that's not the case. https://github.com/rust-lang/rust/pull/116049 should help clarify (but doesn't change the behavior of any existing lint).

File: compiler/rustc_resolve/src/imports.rs [hunk 32]
```diff
@@ -284,39 +284,69 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                            && let NameBindingKind::Import { import: old_import, .. } = old_binding.kind
+                            && let NameBindingKind::Import { import, .. } = binding.kind
+                            && old_import == import {
+                            // We should replace the `old_binding` with `binding` regardless
+                            // of whether they has same resolution or not when they are
+                            // imported from the same glob-import statement.
+                            // However we currently using `Some(old_binding)` for back compact
+                            // purposes.
+                            // This case can be removed after once `Undetermined` is prepared
+                            // for glob-imports.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:325]: Sigh, this case was supposed to produce `ambiguous_glob_imports` lint for years, but it never did, so we cannot remove it now.
I've noticed it just now...
