### PR TITLE
bootstrap: handle worktrees in warn_old_master_branch

### LINKED ISSUE #130111: Outdated master branch detection doesn't work with worktrees
When running any bootstrap command, it complains that it can't figure out whether my master branch is outdated.
Of course it does, as it just YOLOs into `.git`, which is just a file and not a directory for worktrees:
https://github.com/rust-lang/rust/blob/adf8d168af9334a8bf940824fcf4207d01e05ae5/src/tools/build_helper/src/git.rs#L177

it should probably not do that (i don't have a suggestion on what to do instead)

regressed by #129584 @lolbinarycat @albertlarsan68

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes #130111

### CODE REVIEW

File: src/tools/build_helper/src/git.rs [hunk 1]
```diff
@@ -167,29 +167,59 @@ pub fn get_git_untracked_files(
...
+}
+
+pub fn warn_old_master_branch_(
+    config: &GitConfig<'_>,
+    git_dir: &Path,
+    updated_master: &mut String,
+) -> Result<bool, Box<dyn std::error::Error>> {
+    use std::time::Duration;
+    *updated_master = updated_master_branch(config, Some(git_dir))?;
+    let branch_path = git_dir.join(".git/refs/remotes").join(&updated_master);
```
Comment (RalfJung) [inline src/tools/build_helper/src/git.rs:202]: Isn't there a way to avoid directly looking at git's data format? Breaking the abstraction like this is not a good idea.

If you must use the .git folder, please use `git rev-parse --git-dir` to determine its location, rather than assuming that it is `.git`. That will then also work with worktrees.

Comment (RalfJung) [reply src/tools/build_helper/src/git.rs:202]: Ah, I see you already found `--git-common-dir`... which is indeed the right location, `--git-dir` is wrong. Let me quickly fix some faulty logic I recently wrote elsewhere, then... ;)

File: src/tools/build_helper/src/git.rs [hunk 2]
```diff
@@ -167,29 +167,59 @@ pub fn get_git_untracked_files(
...
+    const WARN_AFTER: Duration = Duration::from_secs(60 * 60 * 24 * 10);
+    let meta = match std::fs::metadata(&branch_path) {
+        Ok(meta) => meta,
+        Err(err) => {
+            let gcd = git_common_dir(&git_dir)?;
```
[the remark this answers is not in the document]
Comment (lolbinarycat) [reply src/tools/build_helper/src/git.rs:207]: i'm trying not to have much of a performance impact over such a niche lint. i'm stuck on an hdd system for the time being, so `git` can take almost half a second to query basic information if it isn't in the I/O cache.. compared to a single `stat` syscall, which is always nearly instant.

yes, this does give slightly worse performance in the worktree case, but worktrees are already nearly unusable on a slow hdd system, so i'm not too concerned about that.

[the remark this answers is not in the document]
Comment (RalfJung) [reply src/tools/build_helper/src/git.rs:207]: I'm concerned about maintainability of this codebase and how much we're willing to carry difficult-to-test fallback paths in code that is proven to be error-prone and not covered by CI. There's a global cost to every hack like this, and at some point making a slow system a bit slower is an okay way to keep the rest of the project productive -- the time spent figuring out why my worktrees now show this warning is time not spent working on rustc itself, after all.

In the end this will be up to the bootstrap team to decide though, these are just my thoughts.

File: src/tools/build_helper/src/git.rs (hunk 1 above)
Comment (lolbinarycat) [reply src/tools/build_helper/src/git.rs:202]: i suppose i overestimated:
1. how many people use worktrees
2. how much people dislike incorrect warnings

waiting on a second opinion, i'll rewrite the code if that's the consensus preference.

Comment (RalfJung) [reply src/tools/build_helper/src/git.rs:202]: The incorrect warning already led to incorrect diagnosis of an unrelated issue in https://github.com/rust-lang/rust/issues/130144. So it's not just about dislike, it's about the real costs of an incorrect warning.

Comment (lolbinarycat) [reply src/tools/build_helper/src/git.rs:202]: yeah, i see that pretty clearly now, there's a reason i started writing this PR as soon as i was made aware of the issue.

i know the current PR works, and my main worry is that if i need to totally rewrite it, that might introduce even more bugs (this situation has happened to me many times), and this would be even worse with something that is so tedious for me to test (spinning up worktrees is not fast on a hdd system)

Comment (RalfJung) [reply src/tools/build_helper/src/git.rs:202]: > i started writing this PR as soon as i was made aware of the issue.

Thanks for spinning up a fix so quickly!

**Comment by albertlarsan68** [comment]
I am r+'ing the code because it is good and because it is a fix for a rather important issue, but I'd like to see only Git being used (isn't there a way to ask it the timestamp of the latest commit of a branch directly and compare that instead of an mtime?)
@bors r+ p=1
