### PR TITLE
Fix rustdoc const computed value

### LINKED ISSUE #85088: Strange hexadecimal comment at the end of a const in documentation
1. Create a new crate.
2. Put for instance `const HOUR_IN_SECONDS: u64 = 60 * 60;` into `src/main.rs`.
3. `cargo doc --open`.
4. Navigate to the constant.
5. See `pub(crate) const HOUR_IN_SECONDS: u64 = 60 * 60; // 0x0_000_000_000_000_e10u64`.

There is a long and very hard to read commented hexadecimal number at the end, 3600 in decimal. Why is it there and how is it useful to the documentation reader? Shouldn't it at least be in decimal?
Is this perhaps a bug?

I also can't find any documentation or sources on this behavior like in https://doc.rust-lang.org/rustdoc/.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #85088.

It looks like this now (instead of hexadecimal):

Screenshot from 2022-02-17 17-55-39

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 1]
```diff
@@ -159,6 +159,14 @@ pub struct Pointer<Tag = AllocId> {
 
 static_assert_size!(Pointer, 16);
 
+// We want the `Debug` output to be readable as it is used by `derive(Debug)` for
+// all the Miri types.
+impl<Tag: Provenance> fmt::Display for Pointer<Tag> {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        Provenance::fmt(self, f)
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs:166]: Instead of duplicating the code, please make one of `Display` and `Debug` dispatch to the other (not sure which way makes more sense, but with the existing comment it probably makes most sense to have `Debug` call `Display`)

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:164]: Well, we won't need two different ones, so forwarding makes it easier for future readers to see that they are the same

Comment (GuillaumeGomez) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:164]: Ok. Now I have a question: do you to have instead for `Debug`:

```rust
write!(f, "{}", self)
```

?

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:164]: I would have assumed `fmt::Display::fmt(self, f)`

Tho now we have to decide whether this is actually what we wanted, as ui tests changed. The hex dumps were somewhat on purpose there.

File: compiler/rustc_middle/src/mir/interpret/value.rs [hunk 2]
```diff
@@ -152,8 +152,8 @@ impl<Tag: Provenance> fmt::Debug for Scalar<Tag> {
 impl<Tag: Provenance> fmt::Display for Scalar<Tag> {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         match self {
-            Scalar::Ptr(ptr, _size) => write!(f, "pointer to {:?}", ptr),
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/value.rs:155]: This causes the ui test fallout. Please make sure the code that prints ui tests uses the debug formatting then

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:164]: That works too!

File: compiler/rustc_middle/src/mir/interpret/value.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply compiler/rustc_middle/src/mir/interpret/value.rs:155]: :+1:

**Comment by GuillaumeGomez** [comment]
@oli-obk: I'm actually wondering: is there any reason why we display in hex instead of decimal? The error messages look simpler to me this way.

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:164]: > It allows to have two different formatting depending on what you need like that.

The issue is that it is entirely unclear which style is used where -- both debug and display end up being user-visible in various situations, and when changing the code it becomes extremely hard to predict which one will change which output. IOW we can't actually meaningfully make them different, currently, since the consequences are so unclear. That is why I entirely *removed* many of the `Display` implementations -- then at least there is no ambiguity over which kind of formatting is used.

This PR adds back some of those instances which I removed; if that cannot be avoided I won't block it but then we can at least consistently use the pattern of forwarding one to the other.

**Comment by RalfJung** [comment]
> is there any reason why we display in hex instead of decimal? The error messages look simpler to me this way.

For large values, hex becomes more readable - in particular things close to INT_MAX.

**Comment by oli-obk** [comment]
These scalars are not necessarily integers. We're printing them as hex, because that's essentially the memory representation. Anything the layout algorithm decides is a `Scalar` will use this representation.

Also: We can certainly open a discussion on the diagnostics of CTFE failures, but not as a drive by change of something unrelated.

**Comment by RalfJung** [comment]
> Using _ like rustdoc does for const wouldn't be better in this case if it's for readability?

Not really -- it's still pretty hard to recognize 0xffff_ffff when written in decimal, even if the thousands are separated via `_`.

**Comment by GuillaumeGomez** [comment]
It was a nightmare to get through all the changes and find out what was broken so I took the easy way out and simply made a smaller change in rustdoc and in the `Debug` implementation for `Scalar`. :)

**Comment by GuillaumeGomez** [comment]
Which broke things in a completely different way...

**Comment by RalfJung** [comment]
Hm, but that leaves us with 3 ways to print a Scalar, and it also means rustdoc has to break the `Scalar` abstraction.

I think `impl Display for ScalarInt` is definitely better than adding a `display` method. But the interesting question is what to do with `Scalar` itself -- that one already supports `Debug` and `Display`, and they differ in how pointers are rendered. Maybe we should do something similar to `ScalarInt`, and `impl LowerHex for Scalar`, to give whoever prints a scalar the choice between hex and decimal output? That means we would have to change the existing users to explicitly opt into hex, but those users should be easy to find if one *first* replaces the current `impl Display for Scalar` by `impl LowerHex`, fixes the fallout, and *then* adds the new `impl Display` that uses decimal rendering.

**Comment by GuillaumeGomez** [comment]
Considering the complexity of it, I'd much rather do it in another PR.

**Comment by RalfJung** [comment]
Well, if Rust had private enums then this PR wouldn't even work... quoting from the `Scalar` docs

> These variants would be private if there was a convenient way to achieve that in Rust. Do not match on a Scalar! Use the various to_* methods instead.

**Comment by GuillaumeGomez** [comment]
True but I don't really care about the value inside, just want to display it. I can use `to_u128` though to cover every possible case if it's better?

**Comment by RalfJung** [comment]
Then you won't be able to print pointer values. Pointers and integers are very different beasts and neither subsumes the other. That's why we have the display impls in that module...

I don't think changing the current `impl Display for Scalar` to an `impl LowerHex` will be a lot of work (`./x.py check` will literally point you to the places where you have to add a `:x`), but if you think that is easier then alternatively you could add a `fn rustdoc_display` to `Scalar` that uses the `impl Display for ScalarInt`, with a FIXME describing the plan I sketched above.

**Comment by GuillaumeGomez** [comment]
Sounds like a plan!

**Comment by GuillaumeGomez** [comment]
Updated! I added a FIXME comment too as you asked. Once this is merged, I think I'll give it a try.
