### PR TITLE
rustc: Add `_imp_` symbols later in compilation

### LINKED ISSUE #45347: ThinLTO breaks MSVC `_imp_` symbols
I believe this is a minimization of [this reported issue](https://internals.rust-lang.org/t/help-test-out-thinlto/6017/51?u=alexcrichton):

```
$ cat bar.rs
pub static A: u32 = 43;

pub mod a {
    pub static A: u32 = 43;
}
$ cat foo.rs
extern crate bar;

fn main() {
    println!("{}", bar::A);
}
$ rustc +nightly bar.rs -C prefer-dynamic -Z thinlto -C codegen-units=1000 --crate-type dylib,rlib -O
$ rustc +nightly foo.rs -L . -Z thinlto -Z print-link-args
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "foo.foo0-8cd878b7c8d78940dfe6697baf5b88ec-exe.rs.rust-cgu.o" "foo.foo1-8cd878b7c8d78940dfe6697baf5b88ec-exe.rs.rust-cgu.o" "/OUT:foo.exe" "foo.crate.allocator.rust-cgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:." "/LIBPATH:C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\msys64\\code\\rustfmt\\libbar.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-2c973d468aa52913.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-10dcb2bb73715353.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-eac2a22c7ef68dc5.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-6232007b55cca9f2.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-968b8d6a8dcae5d4.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-bba7ff6cfd33a952.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_unicode-6001d57e726caccd.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-d98f06e2ac3721a9.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-15daeee4c05dda88.rlib" "C:\\Users\\alex\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-b02255a955089c1d.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: foo.foo0-8cd878b7c8d78940dfe6697baf5b88ec-exe.rs.rust-cgu.o : error LNK2019: unresolved external symbol __imp__ZN3bar1A17h8c3f932ba2a49b51E referenced in function _ZN3foo4main17hd45fff29dc617b3fE.llvm.C758FA11
          foo.exe : fatal error LNK1120: 1 unresolved externals


error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by alexcrichton**
On MSVC targets rustc will add symbols prefixed with `_imp_` to LLVM modules to
"emulate" dllexported statics as that workaround is still in place after #27438
hasn't been solved otherwise. These statics, however, were getting gc'd by
ThinLTO accidentally which later would cause linking failures.

This commit updates the location we add such symbols to happen just before
codegen to ensure that (a) they're not eliminated by the optimizer and (b) the
optimizer doesn't even worry about them.

Closes #45347

### CODE REVIEW

File: src/test/run-pass/thinlto/msvc-imp-present.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// Copyright 2017 The Rust Project Developers. See the COPYRIGHT
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
```
Comment (michaelwoerister) [inline src/test/run-pass/thinlto/msvc-imp-present.rs]: Could you add a comment what this is all about? Otherwise one might be a little lost when this test fails.

**Review by michaelwoerister — COMMENTED** [review]
Thanks, @alexcrichton! 

r=me with the comment in the test case added.

**Comment by kennytm** [comment]
The test against `xsv` failed on `check-aux x86_64-pc-windows-msvc`

<details>

```
[01:08:09] failures:
[01:08:09] 
[01:08:09] ---- test_frequency::prop_frequency stdout ----
[01:08:09] 	[C:\projects\rust\build\ct\xsv\target\debug\xit\prop_frequency\test-821]: "C:\\projects\\rust\\build\\ct\\xsv\\target\\debug\\xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[01:08:09] [C:\projects\rust\build\ct\xsv\target\debug\xit\prop_frequency\test-823]: "C:\\projects\\rust\\build\\ct\\xsv\\target\\debug\\xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
...
[01:08:09] [C:\projects\rust\build\ct\xsv\target\debug\xit\prop_frequency\test-957]: "C:\\projects\\rust\\build\\ct\\xsv\\target\\debug\\xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[01:08:09] thread 'test_frequency::prop_frequency' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (CsvData { data: [[[239, 187, 191]], [[]]] })
[01:08:09] Error: "called `Option::unwrap()` on a `None` value"', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-0.4.1\src\tester.rs:147:27
[01:08:09] 
[01:08:09] 
[01:08:09] failures:
[01:08:09]     test_frequency::prop_frequency
[01:08:09] 
[01:08:09] test result: FAILED. 420 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:08:09] 
[01:08:09] error: test failed, to rerun pass '--test tests'
```

</details>

**Comment by alexcrichton** [comment]
wut

**Comment by alexcrichton** [comment]
That test failure is a quickcheck-based test, and otherwise this PR should only affect linkage (not runtime), so I'm going to retry assuming it's spurious. If this lands I'll open an issue upstream.

@bors: retry
