### PR TITLE
Unsized tuple coercions

### LINKED ISSUE #32702: Tuple should probably be unsizable by last argument
Currently tuples can contain unsized types, but cannot be coerced.
It contrasts with behavior of tuple structs and probably should be changed.

I can see two options here:
a) Forbid tuples with unsized types completely.
b) Forbid tuples with unsized types on any but last position and allow DST coercions.

``` rust
struct S;
trait T {}
impl T for S {}

struct Wrapper<TT: ?Sized>(i32, TT);

fn main() {
    let sw: Wrapper<S> = Wrapper(0, S);
    let tw: &Wrapper<T> = &sw; // unsizes just fine

    let st: (i32, S) = (0, S);
    let tt: &(i32, T) = &st; // fails to unsize, even though it could
}

// on a side note, why is it a legal type?
// as far as I can tell there is no way to get 
// an instance of this type right now
type Why = (T, i32);
```

### PR DESCRIPTION
**Pull request by qnighy**
Part of #18469. Fixes #32702.

#37685 and #34451 might also be related.

This PR does the following:

- Introduce explicit `Sized` constraints on tuple initializers, similar to that of record-struct initializers. Not much relevant to the main contribution but I noticed this when making tests for unsized tuple coercions.
- Implement `(.., T): Unsize<(.., U)>` where `T: Unsize<U>`.
- Assume `(.., T)` is MaybeUnsizedUnivariant.
- Modify `src/librustc/ty/util.rs` and `src/librustc_trans/glue.rs` so that tuples and structs are uniformly traversed when translating.

### CODE REVIEW

**Comment by qnighy** [comment]
[Travis failed](https://travis-ci.org/rust-lang/rust/builds/240666299), but I suppose it is spurious.

**Comment by oli-obk** [comment]
You can close and reopen the PR to restart travis

**Comment by qnighy** [comment]
@oli-obk Thank you!

**Comment by carols10cents** [comment]
Friendly ping @arielb1 to keep this on your radar!

**Comment by arielb1** [comment]
Don't we want to feature-gate this somehow? Pinging @rust-lang/lang.

File: src/librustc/traits/select.rs [hunk 1]
```diff
@@ -2612,6 +2617,37 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
                     &[inner_target]));
             }
 
+            // (.., T) -> (.., U).
+            (&ty::TyTuple(tys_a, _), &ty::TyTuple(tys_b, _)) => {
```
Comment (arielb1) [inline src/librustc/traits/select.rs]: I'll prefer to merge this with the ADT code somehow.

File: src/test/compile-fail/dst-bad-assign-3.rs [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+#[derive(PartialEq,Eq)]
+struct Bar;
+
+#[derive(PartialEq,Eq)]
+struct Bar1 {
+    f: isize
+}
+
+trait ToBar {
```
Comment (arielb1) [inline src/test/compile-fail/dst-bad-assign-3.rs]: Why these extra methods?

File: src/test/run-pass-valgrind/dst-dtor-1.rs [hunk 3]
```diff
@@ -28,7 +28,8 @@ struct Fat<T: ?Sized> {
 
 pub fn main() {
     {
-        let _x: Box<Fat<Trait>> = Box::<Fat<Foo>>::new(Fat { f: Foo });
+        let _x: Box<(i32, Fat<Trait>)> =
```
Comment (arielb1) [inline src/test/run-pass-valgrind/dst-dtor-1.rs]: can you have this in addition to the original test?

File: src/test/run-pass-valgrind/dst-dtor-2.rs [hunk 4]
```diff
@@ -25,7 +25,8 @@ struct Fat<T: ?Sized> {
 
 pub fn main() {
     {
-        let _x: Box<Fat<[Foo]>> = Box::<Fat<[Foo; 3]>>::new(Fat { f: [Foo, Foo, Foo] });
+        let _x: Box<(Fat<[Foo]>,)> =
```
Comment (arielb1) [inline src/test/run-pass-valgrind/dst-dtor-2.rs]: can you have this in addition to the original test?

**Comment by arielb1** [comment]
I'm generally ok with these changes modulo `select` cleanup and a feature gate.

File: src/librustc/traits/select.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: I've thought before that we should have an "infinite family" of tuple ADTs. One complication is that ADTs have def-ids...

File: src/test/compile-fail/dst-bad-assign-3.rs (hunk 2 above)
Comment (qnighy) [inline src/test/compile-fail/dst-bad-assign-3.rs]: Just because it was copied from `dst-bad-assign.rs`.

File: src/librustc/traits/select.rs (hunk 1 above)
Comment (qnighy) [inline src/librustc/traits/select.rs]: The code above `mk_adt` largely depends on def-ids and type parameters, so I doubt I can merge this part with tuple's. The codes below `mk_adt`/`mk_tup` are similar, but I don't think its worth merging...

File: src/test/run-pass-valgrind/dst-dtor-1.rs (hunk 3 above)
Comment (qnighy) [inline src/test/run-pass-valgrind/dst-dtor-1.rs]: Done.

File: src/test/run-pass-valgrind/dst-dtor-2.rs (hunk 4 above)
Comment (qnighy) [inline src/test/run-pass-valgrind/dst-dtor-2.rs]: Done.

**Comment by arielb1** [comment]
Hi @qnighy. We don't want this change to be insta-stable, so we need to add a feature gate and a tracking issue.

File: src/librustc/traits/select.rs [hunk 5]
```diff
@@ -2614,6 +2619,37 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
...
+                // The last field of the tuple has to exist.
+                let (a_last, a_mid) = if let Some(x) = tys_a.split_last() {
+                    x
+                } else {
+                    return Err(Unimplemented);
+                };
+                let b_last = tys_b.last().unwrap();
+
+                // Check that the source tuple with the target's
+                // last element is a subtype of the target.
```
Comment (arielb1) [inline src/librustc/traits/select.rs]: nit: comment should not say "subtype" but rather "has the same type". Yes I know this is a copy of another comment that says "subtype". Both are wrong. The code does a type equality, and subtyping would be unsound (#40288).

So this comment should be
```Rust
// Check that the source tuple with the target's
// last element is equal to the target.
```

And the other one
```Rust
// Check that the source struct with the target's
// unsized parameters equal to the target.
```

We should probably be comparing all other type parameters instead of doing this hack. Feel free to do that (in both places), but I'm not going to block this PR on that.

File: src/librustc_typeck/check/coercion.rs [hunk 6]
```diff
@@ -520,14 +521,24 @@ impl<'f, 'gcx, 'tcx> Coerce<'f, 'gcx, 'tcx> {
...
+
         // Keep resolving `CoerceUnsized` and `Unsize` predicates to avoid
         // emitting a coercion in cases like `Foo<$1>` -> `Foo<$2>`, where
         // inference might unify those two inner type variables later.
         let traits = [coerce_unsized_did, unsize_did];
         while let Some(obligation) = queue.pop_front() {
             debug!("coerce_unsized resolve step: {:?}", obligation);
             let trait_ref = match obligation.predicate {
-                ty::Predicate::Trait(ref tr) if traits.contains(&tr.def_id()) => tr.clone(),
+                ty::Predicate::Trait(ref tr) if traits.contains(&tr.def_id()) => {
```
Comment (arielb1) [inline src/librustc_typeck/check/coercion.rs]: this is... ok.

**Comment by arielb1** [comment]
r+ modulo comment

**Review by arielb1 — CHANGES_REQUESTED** [review]
r+ modulo comment. Nice PR!

File: src/librustc/traits/select.rs (hunk 5 above)
Comment (qnighy) [inline src/librustc/traits/select.rs]: Fixed, thanks!

**Review by arielb1 — APPROVED** [review]
