### PR TITLE
make x look for x.py if shell script does not exist

### LINKED ISSUE #107907: `src/tools/x` doesn't work on old checkouts of the compiler
Since https://github.com/rust-lang/rust/pull/105844, src/tools/x unconditionally looks for the shell scripts when running. That's good in most cases because it avoids having to run python. However, on old checkouts the shell scripts don't exist and it needs to fall back to using python.

cc @albertlarsan68, do you have time to fix this?

### PR DESCRIPTION
**Pull request by zephaniahong**
Fixes #107907

Manually tested by doing the following after changes were made:
1. `cargo install --path src/tools/x`
2. checked out old version:  commit hash `775c3c0` from https://github.com/rust-lang/rust/pull/99992
3. Ran `x --help` and it works. Previously, it was giving the error `x.py not found`

### CODE REVIEW

**Comment by jyn514** [comment]
Thanks! Can you also bump the version of x in Cargo.toml so people get a warning if they're using an old version?

**Comment by jyn514** [comment]
(I need to set up a rustbot ping comment that posts that automatically...)

**Comment by zephaniahong** [comment]
Do i bump it to 0.1.1? or 0.2.0?

**Comment by zephaniahong** [comment]
> (I need to set up a rustbot ping comment that posts that automatically...)
If you could give me some details about your requirements, I could give it a shot!(👍

**Comment by jyn514** [comment]
> No problem! Do i bump it to 0.1.1? or 0.2.0?

0.1.1 seems fine, in practice tidy is just checking if the version increased or not.

**Comment by jyn514** [comment]
> > (I need to set up a rustbot ping comment that posts that automatically...)
> 
> If you could give me some details about your requirements, I could give it a shot! 👍

That would be great, thanks! You'd just add a line around https://github.com/rust-lang/rust/blob/5348a89a77a49f6f57c13c0edf7f493fd410159a/triagebot.toml#L463 that posts a message if src/tools/x is modified.

File: src/tools/x/src/main.rs [hunk 1]
```diff
@@ -72,26 +108,45 @@ fn main() {
...
+
+                let result = exec_or_status(&mut python);
+
+                match result {
+                    Err(error) => {
+                        eprintln!("Failed to invoke `{}`: {}", candidate.display(), error);
+                    }
+                    Ok(status) => {
+                        process::exit(status.code().unwrap_or(1));
+                    }
```
Comment (albertlarsan68) [inline src/tools/x/src/main.rs:141]: There is quite a bit of duplication here, maybe you can factor out a function?

File: src/tools/x/src/main.rs [hunk 2]
```diff
@@ -72,26 +108,45 @@ fn main() {
...
-    eprintln!(
-        "x.py not found. Please run inside of a checkout of `https://github.com/rust-lang/rust`."
-    );
+        eprintln!(
+            "x.py not found. Please run inside of a checkout of `https://github.com/rust-lang/rust`."
+        );
 
-    process::exit(1);
+        process::exit(1);
+    }
```
Comment (albertlarsan68) [inline src/tools/x/src/main.rs:151]: This changes the behaviour, it now fails immediatly, without searching the parent directories.

**Review by albertlarsan68 — CHANGES_REQUESTED** [review]
And you can squash your commits after the changes requested.
Thanks!

File: src/tools/x/src/main.rs (hunk 1 above)
Comment (zephaniahong) [reply src/tools/x/src/main.rs]: Done!(:
Thank you!

**Comment by albertlarsan68** [comment]
Seems good.
Thanks for the PR!
@bors r+
