### PR TITLE
compiletest: rename `add-core-stubs`/`core-stubs-compile-flags` to `add-minicore`/`minicore-compile-flags`

### LINKED ISSUE #148282: Tracking issue for MCP 930: Rename `//@ add-core-stubs` to `//@ add-minicore`
This is a tracking issue for MCP "Rename `//@ add-core-stubs` to `//@ add-minicore`" (rust-lang/compiler-team#930).

> [!NOTE]
> Tracking issues are used to record the overall progress of implementation.
> They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
>
> A tracking issue is however *not* meant for large scale discussion, questions, or bug reports.
> Instead, open a dedicated issue for the specific matter, link to this tracking issue and ping the MCP author.
> Alternatively, post in the Zulip stream linked from the MCP.
>
> Discussion comments will get marked as off-topic or deleted.
> Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [ ] Implement the MCP
- [ ] Adjust documentation
  - [ ] In the [Rust Compiler Development Guide] if applicable (e.g., for refactorings)
  - [ ] In the [Rust Forge] if applicable (e.g., for policy changes)
  - [ ] In the [rustc book] if applicable (e.g., for target tier or CLI changes)

[Rust Compiler Development Guide]: https://rustc-dev-guide.rust-lang.org/
[Rust Forge]: https://forge.rust-lang.org/compiler/index.html
[rustc book]: https://doc.rust-lang.org/rustc/index.html

### Unresolved questions

*None so far.*

### Implementation history

*Empty so far.*

---

@RalfJung, consider `@rustbot claim`'ing the work.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/148282

### CODE REVIEW

File: tests/codegen-llvm/abi-win64-zst.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
-//@ add-core-stubs
+//@ add-minicore
 //@ compile-flags: -Z merge-functions=disabled
-//@ add-core-stubs
+//@ add-minicore
```
Comment (wesleywiser) [inline tests/codegen-llvm/abi-win64-zst.rs]: pre-existing but do we actually need this annotation twice?

File: tests/ui/target-feature/tied-features.rs [hunk 2]
```diff
@@ -1,8 +1,8 @@
-//@ add-core-stubs
+//@ add-minicore
 //@ compile-flags: --crate-type=rlib --target=aarch64-unknown-linux-gnu
 //@ needs-llvm-components: aarch64
 //@ ignore-backends: gcc
-//@ add-core-stubs
+//@ add-minicore
```
Comment (wesleywiser) [inline tests/ui/target-feature/tied-features.rs]: here as well?

**Review by wesleywiser — APPROVED** [review]
Looks good to me but I'll let @jieyouxu review as well before r+'ing

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148305/8205e6b75ec656305ac235d4726d2c7a1ddcef14..25efd5e920c6e7b0b9194617e0b86469ec1fe899)*

File: tests/codegen-llvm/abi-win64-zst.rs (hunk 1 above)
Comment (RalfJung) [reply tests/codegen-llvm/abi-win64-zst.rs]: No, we don't...

File: tests/ui/cmse-nonsecure/cmse-nonsecure-entry/return-via-stack.rs [hunk 3]
```diff
@@ -1,7 +1,7 @@
-//@ add-core-stubs
+//@ add-minicore
 //@ compile-flags: --target thumbv8m.main-none-eabi --crate-type lib
 //@ needs-llvm-components: arm
-//@ add-core-stubs
+//@ add-minicore
```
Comment (jieyouxu) [inline tests/ui/cmse-nonsecure/cmse-nonsecure-entry/return-via-stack.rs]: Nit: duplicate directive

(compiletest should error on this, #148359)

File: tests/ui/panic-runtime/need-immediate-abort-got-abort.rs [hunk 4]
```diff
@@ -2,7 +2,7 @@
 //@ aux-build:needs-immediate-abort.rs
 //@ compile-flags:-C panic=abort
 //@ no-prefer-dynamic
-//@ add-core-stubs
+//@ add-minicore
 //@ core-stubs-compile-flags: -Zunstable-options -Cpanic=immediate-abort
```
Comment (jieyouxu) [inline tests/ui/panic-runtime/need-immediate-abort-got-abort.rs]: Problem: I realized that Saethlin recently added `//@ core-stubs-compile-flags` for overriding the flags used to build minicore. We should also rename this, but I'll do it in a follow-up, tracked in #148360.

**Review by jieyouxu — APPROVED** [review]
Thanks, one nit, you can r=Wesley and me after.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148305/8205e6b75ec656305ac235d4726d2c7a1ddcef14..5dc60fb6118e5992bcb62825447059d3791496f5)*

**Review by jieyouxu — APPROVED** [review]
Thanks, r=us after PR CI is green.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148305/bd3ac0330018c23b111bbee176f32c377be7b319..e6f0ef06030d158f4a47c042312101b9f3c38ac5)*

**Comment by RalfJung** [comment]
I... didn't change that code?
@bors retry
