### PR TITLE
make `llvm::is_ci_llvm_modified` logic more precise

### LINKED ISSUE #131303: download_ci_llvm test failure when updating LLVM
From https://github.com/rust-lang/rust/pull/131293#issuecomment-2395118995:

```
2024-10-05T14:07:30.4627940Z failures:
2024-10-05T14:07:30.4628774Z 
2024-10-05T14:07:30.4629533Z ---- core::config::tests::download_ci_llvm stdout ----
2024-10-05T14:07:30.4630298Z thread 'core::config::tests::download_ci_llvm' panicked at src/core/config/tests.rs:33:5:
2024-10-05T14:07:30.4630892Z assertion `left == right` failed
2024-10-05T14:07:30.4631199Z   left: true
2024-10-05T14:07:30.4632659Z  right: false
2024-10-05T14:07:30.4632897Z 
2024-10-05T14:07:30.4632913Z 
2024-10-05T14:07:30.4633046Z failures:
2024-10-05T14:07:30.4633383Z     core::config::tests::download_ci_llvm
```

Variants of this issue appear with surprising regularity, this is probably already the tenth time that bootstrap tests fail if and only if the LLVM submodule is updated.

We probably need a CI job that adds a dummy commit to the submodule and verifies that bootstrap tests still pass after that.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Fixes #131303.

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/llvm.rs [hunk 1]
```diff
@@ -242,15 +242,30 @@ pub(crate) fn is_ci_llvm_available(config: &Config, asserts: bool) -> bool {
...
-            output(helpers::git(Some(&config.src)).arg("rev-parse").arg("HEAD").as_command_mut());
-        let head_sha = head_sha.trim();
-        llvm_sha == head_sha
+    // If not running in a CI environment, return false.
+    if !CiEnv::is_ci() {
+        return false;
+    }
+
+    // In rust-lang/rust managed CI, ensure the LLVM submodule is present.
+    if CiEnv::is_rust_lang_managed_ci_job() {
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/llvm.rs:251]: Is this needed/is this expected to fix anything? We forcefully checkout all submodules at the beginning of each CI job :thinking:

Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/llvm.rs:251]: Yes, I am aware of that. This is just a way to ensure that it will be available before proceeding with the change check. But now I think it might be better to assert its existence instead.

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/llvm.rs:251]: I think that would be clearer, because this was a bit confusing to me ("ensure something that is already ensured somewhere else").

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/llvm.rs:251]: I almost wonder if ensuring the LLVM submodule is checked out or is otherwise available should be its own `Step`

**Comment by Kobzol** [comment]
The new logic looks good, but I don't understand how it fixes the issue. What specifically has changed which would cause it to work properly now?

**Comment by onur-ozkan** [comment]
https://github.com/rust-lang/rust/blob/690332a251329e603d1a38bc70a4f6a45ac30bc2/src/bootstrap/src/core/config/tests.rs#L22-L27

The test above supposed to skip when there is a change in the LLVM submodule in CI. However, as reported in https://github.com/rust-lang/rust/issues/131303, it isn't behaving as expected. I suspect this is related to the `CiEnv::is_rust_lang_managed_ci_job()` logic (maybe some pipelines do not have [this env variables](https://github.com/onur-ozkan/rust/blob/5840d8791c1fc464e0aeca0690bff95274ddacd7/src/tools/build_helper/src/ci.rs#L23-L30) set together?), though I'm not entirely certain.

**Comment by onur-ozkan** [comment]
I will test it with try build later today.

@rustbot author

**Comment by Kobzol** [comment]
These two variables should be indeed set unconditionally for all CI jobs. So I suspect that the erorr might have been in [this logic](https://github.com/rust-lang/rust/pull/131305/files#diff-5619a6d255831761bb2df44dab32512c58e42e5430f949cc3a0086d72299d9d0R264) instead.

**Comment by onur-ozkan** [comment]
Probably, will debug that and fix it.

**Comment by onur-ozkan** [comment]
It didn't happen in CI; maybe it was something else or the first attempt already fixed it. Either way, I made the function even better.

@rustbot ready

**Comment by onur-ozkan** [comment]
Tested and it's fixed https://github.com/rust-lang/rust/pull/131448#issuecomment-2402741793 issue in https://github.com/rust-lang/rust/pull/131455.

File: src/bootstrap/src/core/build_steps/llvm.rs [hunk 2]
```diff
@@ -242,15 +242,40 @@ pub(crate) fn is_ci_llvm_available(config: &Config, asserts: bool) -> bool {
...
+    }
+
+    let commit = t!(get_closest_merge_commit(Some(&config.src), &config.git_config(), &[]));
+
+    #[allow(clippy::let_and_return)] // makes it look more clear
+    let is_modified = !t!(helpers::git(Some(&config.src))
+        .args(["diff-index", "--quiet", &commit])
+        .arg("--")
+        .args([
+            config.src.join("src/llvm-project"),
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/llvm.rs:269]: Could you please unify these three files with the same filelist used in `detect_llvm_sha`?

Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/llvm.rs]: It's no longer necessary.

File: src/bootstrap/src/core/config/tests.rs [hunk 3]
```diff
@@ -20,29 +20,21 @@ fn parse(config: &str) -> Config {
...
-    assert!(parse_llvm("rust.channel = \"stable\""));
-    assert_eq!(parse_llvm("build.build = \"x86_64-unknown-linux-gnu\""), if_unchanged);
-    assert_eq!(
-        parse_llvm(
-            "llvm.assertions = true \r\n build.build = \"x86_64-unknown-linux-gnu\" \r\n llvm.download-ci-llvm = \"if-unchanged\""
-        ),
-        if_unchanged
-    );
-    assert!(!parse_llvm(
-        "llvm.assertions = true \r\n build.build = \"aarch64-apple-darwin\" \r\n llvm.download-ci-llvm = \"if-unchanged\""
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/config/tests.rs:44]: `if-unchanged` is not default since https://github.com/rust-lang/rust/pull/130529. These didn’t fail before because if there are no changes (which is ensured [here](https://github.com/rust-lang/rust/blob/df1b5d3cc2117f1ee96abca25678bc5f5604d450/src/bootstrap/src/core/config/tests.rs#L24-L27)), both `download-ci-llvm=if-unchanged` and `true` will behave the same.

File: src/bootstrap/src/core/build_steps/llvm.rs [hunk 4]
```diff
@@ -242,15 +241,29 @@ pub(crate) fn is_ci_llvm_available(config: &Config, asserts: bool) -> bool {
...
+            config.in_tree_llvm_info.is_managed_git_subrepository(),
+            "LLVM submodule must be fetched in rust-lang/rust managed CI builders."
+        );
     }
+    // If LLVM submodule isn't present, skip the change check as it won't work.
+    else if !config.in_tree_llvm_info.is_managed_git_subrepository() {
+        return false;
+    }
+
+    let llvm_sha = detect_llvm_sha(config, true);
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/llvm.rs:261]: I think that this is wrong, and [this](https://github.com/rust-lang/rust/pull/131305#discussion_r1794717517) code (which was in a previous commit) should be used instead.

Or at the very least, we should change the documentation of `get_closest_merge_commit`. Because `detect_llvm_sha` uses `get_closest_merge_commit`, which is supposed to return the latest **upstream** merge commit (that modified LLVM). In that case, it can by definition never return `HEAD` on CI (because `HEAD` is definitely not *upstream*).

However, we know that currently `get_closest_merge_commit` is bugged and probably just returns `HEAD` on CI, so we should probably first resolve https://github.com/rust-lang/rust/pull/131358 before continuing with this PR.

Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/llvm.rs:261]: This PR unblocks LLVM update PRs and it doesn't do anything other than improving current logic. I don't think #131358 should block this.

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/llvm.rs:261]: Ok, let's fix the `download_ci_llvm` test for now to unblock the update PRs. But the logic is still wrong, https://github.com/rust-lang/rust/pull/131358 should hopefully fix it later.
