### PR TITLE
DestinationPropagation: avoid creating overlapping assignments.

### LINKED ISSUE #146383: Miscompile in DestinationPropagation?
Reduced example from rustlantis, which is accepted by Miri using Tree Borrows without optimizations enabled:

```rust
#![feature(custom_mir, core_intrinsics)]
#![allow(internal_features)]

use std::intrinsics::mir::*;

fn dump_var<T>(_: T) {}

#[custom_mir(dialect = "runtime")]
fn main() {
    mir!{
        let _1: (u8,);
        let _2: (u8,);
        let _3: (u8,);
        let _4: (u8,);
        let _5: ();
        {
            _3.0 = 0;
            _1 = _3;
            _4 = (_1.0, );
            _1 = _4;
            Call(_5 = dump_var(_1), ReturnTo(bb1), UnwindUnreachable())
        }
        bb1 = {
            Return()
        }
    }
}
```
I'm sure this is caused by DestinationPropagation, because
```
cargo +nightly miri run
```
accepts this code, but
```
MIRIFLAGS=-Zmir-enable-passes=+DestinationPropagation cargo +nightly miri run
```
reports UB (ignore the span, it's confusing because the source code that's displayed is the pre-optimization MIR):
```
error: Undefined Behavior: reading memory at alloc125[0x0..0x1], but memory is uninitialized at [0x0..0x1], and this operation requires initialized memory
  --> src/main.rs:19:13
   |
19 |             _4 = (_1.0, );
   |             ^^^^^^^^^^^^^ Undefined Behavior occurred here
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `main` at src/main.rs:19:13: 19:26
```

The errant transformation rewrite the entire body:
```diff
-// MIR for `main` before DestinationPropagation
+// MIR for `main` after DestinationPropagation
 
 fn main() -> () {
     let mut _0: ();
     let mut _1: (u8,);
     let mut _2: (u8,);
     let mut _3: (u8,);
     let mut _4: (u8,);
     let mut _5: ();
 
     bb0: {
-        (_3.0: u8) = const 0_u8;
-        _1 = copy _3;
-        _4 = (copy (_1.0: u8),);
-        _1 = copy _4;
-        _5 = dump_var::<(u8,)>(copy _1) -> [return: bb1, unwind unreachable];
+        (_4.0: u8) = const 0_u8;
+        nop;
+        _4 = (copy (_4.0: u8),);
+        nop;
+        _5 = dump_var::<(u8,)>(copy _4) -> [return: bb1, unwind unreachable];
     }
 
     bb1: {
         return;
     }
 }
```

This is probably https://github.com/rust-lang/rust/pull/145541 cc @cjgillot @Amanieu

### PR DESCRIPTION
**Pull request by cjgillot**
r? @Amanieu 

Fixes https://github.com/rust-lang/rust/issues/146383

### CODE REVIEW

File: compiler/rustc_mir_transform/src/dest_prop.rs [hunk 1]
```diff
@@ -590,13 +576,20 @@ fn save_as_intervals<'tcx>(
             append_at(&mut values, &state, twostep);
             // Ensure we have a non-zero live range even for dead stores. This is done by marking
             // all the written-to locals as live in the second half of the statement.
-            VisitPlacesWith(|place, ctxt| match DefUse::for_place(place, ctxt) {
-                DefUse::Def | DefUse::PartialWrite => {
-                    if let Some(relevant) = relevant.shrink[place.local] {
-                        values.insert(relevant, twostep);
+            let is_simple_assignment =
```
Comment (Amanieu) [inline compiler/rustc_mir_transform/src/dest_prop.rs]: This could use an explanatory comment: overlaps aren't allowed so we can only treat the source and destination of an assignment as disjoint if they are "simple" and in a form we can later eliminate at the end of this pass.

File: compiler/rustc_mir_transform/src/dest_prop.rs [hunk 2]
```diff
@@ -588,15 +590,26 @@ fn save_as_intervals<'tcx>(
...
-                    if let Some(relevant) = relevant.shrink[place.local] {
-                        values.insert(relevant, twostep);
+            // Like terminators, ensure we have a non-zero live range even for dead stores.
+            // Some rvalues interleave reads and writes, for instance `Rvalue::Aggregate`, see
+            // https://github.com/rust-lang/rust/issues/146383. By precaution, treat statements
+            // as behaving so by default.
+            // We make an exception for simple assignments `_a.stuff = {copy|move} _b.stuff`,
+            // as marking `_b` live here would prevent unification.
+            let is_simple_assignment =
+                matches!(stmt.kind, StatementKind::Assign(box (_, Rvalue::Use(_))));
```
Comment (Amanieu) [inline compiler/rustc_mir_transform/src/dest_prop.rs]: I think this needs to be stricter: the projections on the source and destination also need to be identical. Otherwise the merge would fail and we could end up with a statement like `_1.foo = _1.bar` which is invalid if `foo` and `bar` are union fields.
