### PR TITLE
Shift no characters when using raw string literals

### LINKED ISSUE #104142: Error in raw string
### Code

```Rust

fn main() {
    println!(r#"
    \"\'}､"#);
}

```

### Meta

`rustc --version --verbose`:
```
<version>
rustc 1.65.0 (897e37553 2022-11-02)
```
~sorry in advance, i don't check if this issue is also in beta or nightly versions.~  i did.
### Error output

```
<output>
❯ RUST_BACKTRACE=1 cargo run
   Compiling cat v0.1.0 (/mnt/c/Users/user/cats/cat)
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1704:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: <rustc_span::SourceFile>::lookup_file_pos
   4: <rustc_span::source_map::SourceMap>::lookup_char_pos
   5: <rustc_errors::emitter::EmitterWriter>::get_multispan_max_line_num
   6: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: <rustc_errors::json::Diagnostic>::from_errors_diagnostic
   8: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   9: <rustc_errors::HandlerInner>::emit_diagnostic
  10: <rustc_errors::Handler>::emit_diagnostic
  11: <rustc_errors::ErrorGuaranteed as rustc_errors::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  12: rustc_builtin_macros::format::expand_preparsed_format_args
  13: rustc_builtin_macros::format::expand_format_args_impl
  14: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  15: <rustc_expand::expand::MacroExpander>::expand_crate
  16: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
  17: rustc_interface::passes::configure_and_expand
  18: <rustc_interface::queries::Queries>::expansion
  19: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cat`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
❯ RUST_BACKTRACE=full cargo build
   Compiling cat v0.1.0 (/mnt/c/Users/user/cats/cat)
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1704:17
stack backtrace:
   0:     0x7f86837e2d40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f86837e2d40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f86837e2d40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f86837e2d40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f868383dbfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f86837d3935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7f86837e59f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f86837e59f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f86837e59f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7f86837e56df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x7f86860132e1 - rustc_driver[cfb34b1539811fe8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f86837e622d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7f86837e6041 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  13:     0x7f86837e31ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f86837e5da2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  15:     0x7f868383a7d3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  16:     0x7f868383a61d - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  17:     0x7f8685083e7d - <rustc_span[8f00505efff112e2]::SourceFile>::lookup_file_pos
  18:     0x7f8685083420 - <rustc_span[8f00505efff112e2]::source_map::SourceMap>::lookup_char_pos
  19:     0x7f8685d5ce19 - <rustc_errors[f77a66b68db622d5]::emitter::EmitterWriter>::get_multispan_max_line_num
  20:     0x7f8685d54719 - <rustc_errors[f77a66b68db622d5]::emitter::EmitterWriter as rustc_errors[f77a66b68db622d5]::emitter::Emitter>::emit_diagnostic
  21:     0x7f8685d50f51 - <rustc_errors[f77a66b68db622d5]::json::Diagnostic>::from_errors_diagnostic
  22:     0x7f8685d4f07e - <rustc_errors[f77a66b68db622d5]::json::JsonEmitter as rustc_errors[f77a66b68db622d5]::emitter::Emitter>::emit_diagnostic
  23:     0x7f8684a99c41 - <rustc_errors[f77a66b68db622d5]::HandlerInner>::emit_diagnostic
  24:     0x7f8684a99581 - <rustc_errors[f77a66b68db622d5]::Handler>::emit_diagnostic
  25:     0x7f868546655d - <rustc_errors[f77a66b68db622d5]::ErrorGuaranteed as rustc_errors[f77a66b68db622d5]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  26:     0x7f86857862d0 - rustc_builtin_macros[ed6672b6594e80a4]::format::expand_preparsed_format_args
  27:     0x7f868577f550 - rustc_builtin_macros[ed6672b6594e80a4]::format::expand_format_args_impl
  28:     0x7f86856be572 - <rustc_expand[e850aec5fc2c767b]::expand::MacroExpander>::fully_expand_fragment
  29:     0x7f8684f08ae3 - <rustc_expand[e850aec5fc2c767b]::expand::MacroExpander>::expand_crate
  30:     0x7f8684f07cf3 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<core[8c92e53db3fc2eaa]::result::Result<rustc_ast[86c44c57e50afb70]::ast::Crate, rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_interface[3182dd864eff9d7d]::passes::configure_and_expand::{closure#1}>
  31:     0x7f8684ecff23 - rustc_interface[3182dd864eff9d7d]::passes::configure_and_expand
  32:     0x7f8684ec6805 - <rustc_interface[3182dd864eff9d7d]::queries::Queries>::expansion
  33:     0x7f8684ec319c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  34:     0x7f8684ec1ac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  35:     0x7f8684ec17af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  36:     0x7f8685e76d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f86837f0003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  38:     0x7f86837f0003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  39:     0x7f86837f0003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f86836bc609 - start_thread
  41:     0x7f86835df133 - clone
  42:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cat`

```
</p>
</details>

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #104142

Given the following code:

```rust
fn main() {
    println!(r#"\'\'\'\'\'\'\'\'\'\'\'\'\'\'}"#);
}
```

The current output is:

```
error: invalid format string: unmatched `}` found
 --> src/main.rs:2:59
  |
2 |     println!(r#"\'\'\'\'\'\'\'\'\'\'\'\'\'\'}"#); //~ ERROR invalid format string: unmatched `}` found
  |                                                           ^ unmatched `}` in format string
  |
  = note: if you intended to print `}`, you can escape it using `}}`

error: could not compile `debug_playground` due to previous error
```

The output should look like:

```
error: invalid format string: unmatched `}` found
 --> src/main.rs:2:45
  |
2 |     println!(r#"\'\'\'\'\'\'\'\'\'\'\'\'\'\'}"#); //~ ERROR invalid format string: unmatched `}` found
  |                                             ^ unmatched `}` in format string
  |
  = note: if you intended to print `}`, you can escape it using `}}`

error: could not compile `debug_playground` due to previous error
```

This pull request fixes the wrong span for `invalid format string` error and also solves the ICE.

### CODE REVIEW

File: compiler/rustc_parse_format/src/lib.rs [hunk 1]
```diff
@@ -819,12 +819,15 @@ fn find_skips_from_snippet(
     };
 
     fn find_skips(snippet: &str, is_raw: bool) -> Vec<usize> {
+        if is_raw {
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:822]: Can you pull this branch outside of the call to `find_skips`?
BTW, why do we need a `find_skips` function, can it be inlined into the caller?

Comment (TaKO8Ki) [reply compiler/rustc_parse_format/src/lib.rs]: I fixed that.

File: compiler/rustc_parse_format/src/lib.rs [hunk 2]
```diff
@@ -813,101 +813,101 @@ fn find_skips_from_snippet(
     snippet: Option<string::String>,
     str_style: Option<usize>,
 ) -> (Vec<usize>, bool) {
+    if str_style.is_some() {
+        return (vec![], true);
+    }
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:818]: Should this be below the next block to keep the same behaviour for the returned `bool`?

File: compiler/rustc_parse_format/src/lib.rs [hunk 3]
```diff
@@ -813,101 +813,101 @@ fn find_skips_from_snippet(
...
-                    for _ in 0..3 {
-                        // consume `\xAB` literal
-                        if let Some((pos, _)) = s.next() {
-                            skips.push(pos);
-                        } else {
-                            break;
-                        }
+    let r_start = str_style.map_or(0, |r| r + 1);
+    let r_end = str_style.unwrap_or(0);
+    let snippet = &snippet[r_start + 1..snippet.len() - r_end - 1];
```
Comment (cjgillot) [inline compiler/rustc_parse_format/src/lib.rs:827]:
```suggestion
    // The first and last characters are the double quotes.
    let snippet = &snippet[1..snippet.len() - 1];
```
We know that `str_style` is `None`.
