### PR TITLE
Add `--no-undefined-version` link flag and fix associated breakage

### LINKED ISSUE #105967: `libtest` fails to link with `lld` at main
Building Rust toolchain using latest [`lld`](https://github.com/llvm/llvm-project/tree/6443c0ee02c7785bc917fcf508f4cc7ded38487a/lld) linker at hash [`6443c0ee02c7785bc917fcf508f4cc7ded38487a`](https://github.com/llvm/llvm-project/tree/6443c0ee02c7785bc917fcf508f4cc7ded38487a/lld) leads to an error when compiling libtest at stage0:
```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling cc v1.0.76
   Compiling core v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/core)
   Compiling libc v0.2.138
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/std)
   Compiling compiler_builtins v0.1.85
   Compiling unwind v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/unwind)
   Compiling profiler_builtins v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/profiler_builtins)
   Compiling rustc-std-workspace-core v1.99.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/alloc)
   Compiling cfg-if v1.0.0
   Compiling adler v1.0.2
   Compiling rustc-demangle v0.1.21
   Compiling rustc-std-workspace-alloc v1.99.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/rustc-std-workspace-alloc)
   Compiling panic_abort v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/panic_abort)
   Compiling panic_unwind v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/panic_unwind)
   Compiling gimli v0.26.1
   Compiling miniz_oxide v0.5.3
   Compiling std_detect v0.1.5 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/stdarch/crates/std_detect)
   Compiling hashbrown v0.12.3
   Compiling object v0.29.0
   Compiling addr2line v0.17.0
   Compiling rustc-std-workspace-std v1.99.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/rustc-std-workspace-std)
   Compiling proc_macro v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/proc_macro)
   Compiling unicode-width v0.1.10
   Compiling getopts v0.2.21
   Compiling test v0.0.0 (/b/s/w/ir/x/w/fuchsia-third_party-rust/library/test)
error: linking with `/b/s/w/ir/x/w/cipd/bin/clang++` failed: exit status: 1
  |
  = note: "/b/s/w/ir/x/w/cipd/bin/clang++" "-Wl,--version-script=/b/s/w/ir/x/t/rustctgpUpK/list" "-m64" "/b/s/w/ir/x/t/rustctgpUpK/symbols.o" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/test-3bd20e94ef73cd68.test.d3d4ef93-cgu.0.rcgu.o" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/test-3bd20e94ef73cd68.1w1vzuec12odskdf.rcgu.rmeta" "-Wl,--as-needed" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/release/deps" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-1f459caf2b14046b/out" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/profiler_builtins-a255468473e62d4f/out" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libgetopts-023b5f868ec7a238.rlib" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libunicode_width-e0099b6d5dcba458.rlib" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/librustc_std_workspace_std-8f7f1564c2f2e122.rlib" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps" "-Wl,-Bdynamic" "-lstd-77833ca844ade20f" "-Wl,-Bstatic" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcompiler_builtins-63346244df871953.rlib" "-Wl,-Bdynamic" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/b/s/w/ir/x/w/staging/build/fuchsia-build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libtest-3bd20e94ef73cd68.so" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs" "--target=x86_64-unknown-linux-gnu" "--sysroot=/b/s/w/ir/x/w/cipd/linux" "-fuse-ld=lld" "-Wl,-z,origin" "-Wl,-rpath,$ORIGIN/../lib"
  = note: ld.lld: error: version script assignment of 'global' to symbol '__rust_alloc' failed: symbol not defined
          ld.lld: error: version script assignment of 'global' to symbol '__rust_alloc_error_handler_should_panic' failed: symbol not defined
          ld.lld: error: version script assignment of 'global' to symbol '__rust_alloc_zeroed' failed: symbol not defined
          ld.lld: error: version script assignment of 'global' to symbol '__rust_dealloc' failed: symbol not defined
          ld.lld: error: version script assignment of 'global' to symbol '__rust_realloc' failed: symbol not defined
          clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
          
error: could not compile `test` due to previous error
```

Error is coming from https://reviews.llvm.org/D135402 (Enable --no-undefined-version by default.), with the description indicating that our version scripts were not correct.

Local workaround is to pass `-Clink-arg=-Wl,--undefined-version` in Rustflags.

### PR DESCRIPTION
**Pull request by chbaker0**
LLVM upstream sets `--no-undefined-version` by default in lld: https://reviews.llvm.org/D135402.

Due to a bug in how version scripts are generated, this breaks the `dylib` output type for most crates. See https://github.com/rust-lang/rust/issues/105967#issuecomment-1428671533 for details.

This PR adds the flag to gcc flavor linkers in anticipation of this LLVM change rolling in, and patches `rustc` to not attempt to export `__rust_*` allocator symbols when they weren't generated.

Fixes #105967

### CODE REVIEW

File: compiler/rustc_middle/src/query/mod.rs [hunk 1]
```diff
@@ -1805,6 +1805,13 @@ rustc_queries! {
         eval_always
         desc { "alloc error handler kind for the current crate" }
     }
+    /// Which allocator kind to codegen. If `Some(_)` this will be the same as
+    /// `allocator_kind`, but it may return `None` in more cases (e.g. if using
+    /// allocator definitions from a dylib dependency).
+    query codegen_allocator_kind(_: ()) -> Option<AllocatorKind> {
+        eval_always
```
Comment (Nilstrieb) [inline compiler/rustc_middle/src/query/mod.rs:1812]: This `eval_always` can be removed as the query doesn't depend on untracked state but only on other queries (`dependency_formats` and `allocator_kind`). I'm not sure whether this makes sense to have as a query in the first place or whether it should just be a normal helper function. I think a normal function would make more sense as the output of this will usually change when the inputs (`dependency_formats` and `allocator_kind`) change and it's also pretty cheap to compute and only called twice.

**Review by chbaker0 — COMMENTED** [review]
Sorry for the delay, I replied but didn't submit it

**Comment by chbaker0** [comment]
Hi, just checking in again

File: compiler/rustc_middle/src/query/mod.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_middle/src/query/mod.rs:1812]: Maybe compiler/rustc_codegen_ssa/src/base.rs? It doesn't quite fit, but I don't know a better place.

Comment (chbaker0) [reply compiler/rustc_middle/src/query/mod.rs]: OK, I moved the logic to a function there

**Comment by chbaker0** [comment]
Ready for another review

File: compiler/rustc_codegen_ssa/src/base.rs [hunk 2]
```diff
@@ -615,20 +633,7 @@ pub fn codegen_crate<B: ExtraBackendMethods>(
...
-    // one instead. If nothing exists then it's our job to generate the
-    // allocator!
-    let any_dynamic_crate = tcx.dependency_formats(()).iter().any(|(_, list)| {
-        use rustc_middle::middle::dependency_format::Linkage;
-        list.iter().any(|&linkage| linkage == Linkage::Dynamic)
-    });
-    let allocator_module = if any_dynamic_crate {
-        None
-    } else if let Some(kind) = tcx.allocator_kind(()) {
+    if let Some(kind) = allocator_kind_for_codegen(tcx) {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/base.rs:636]: A minor request but could you update https://github.com/rust-lang/rust/blob/313219c0b6bacabe0fc72a8eb3912b8fc08b9bdb/compiler/rustc_codegen_cranelift/src/allocator.rs#L16-L22 too?

**Review by bjorn3 — APPROVED** [review]
LGTM, thanks! I got a minor request to avoid some code duplication, but r=me either way.

File: compiler/rustc_codegen_ssa/src/base.rs (hunk 2 above)
Comment (chbaker0) [reply compiler/rustc_codegen_ssa/src/base.rs:636]: Done

**Comment by chbaker0** [comment]
Thanks!

@bors r+

extra changes are exactly as requested

**Review by bjorn3 — APPROVED** [review]

**Comment by JohnTitor** [comment]
Failed

**Comment by Nilstrieb** [comment]
Looks like the MacOS ld doesn't understand the flag.

**Comment by chbaker0** [comment]
Makes sense; I guess `--no-undefined-version` only makes sense for a linker that calls this a "version script"

I moved it under the appropriate condition.

Not sure if the delegate earlier is sticky, but I'll try:

@bors r+
