### PR TITLE
Compute variances for lazy type aliases

### LINKED ISSUE #114221: lazy_type_alias causes lifetime error
I tried this code:
`tests/ui/regions/regions-scope-chain-example.rs`
```rust
// run-pass
#![allow(dead_code)]
#![allow(unused_variables)]
// This is an example where the older inference algorithm failed. The
// specifics of why it failed are somewhat, but not entirely, tailed
// to the algorithm. Ultimately the problem is that when computing the
// mutual supertype of both sides of the `if` it would be faced with a
// choice of tightening bounds or unifying variables and it took the
// wrong path. The new algorithm avoids this problem and hence this
// example typechecks correctly.

// pretty-expanded FIXME #23616

enum ScopeChain<'a> {
    Link(Scope<'a>),
    End
}

type Scope<'a> = &'a ScopeChain<'a>;

struct OuterContext;

struct Context<'a> {
    foo: &'a OuterContext
}

impl<'a> Context<'a> {
    fn foo(&mut self, scope: Scope) {
        let link = if 1 < 2 {
            let l = ScopeChain::Link(scope);
            self.take_scope(&l);
            l
        } else {
            ScopeChain::Link(scope)
        };
        self.take_scope(&link);
    }

    fn take_scope(&mut self, x: Scope) {
    }
}

fn main() { }
```

without  `-Zcrate-attr=feature(lazy_type_alias)´: no warnings

with `-Zcrate-attr=feature(lazy_type_alias)`:

```
error[E0597]: `l` does not live long enough
  --> tests/ui/regions/regions-scope-chain-example.rs:31:29
   |
28 |     fn foo(&mut self, scope: Scope) {
   |                       ----- has type `Scope<'1>`
29 |         let link = if 1 < 2 {
30 |             let l = ScopeChain::Link(scope);
   |                 - binding `l` declared here
31 |             self.take_scope(&l);
   |             ----------------^^-
   |             |               |
   |             |               borrowed value does not live long enough
   |             argument requires that `l` is borrowed for `'1`
32 |             l
33 |         } else {
   |         - `l` dropped here while still borrowed

error[E0505]: cannot move out of `l` because it is borrowed
  --> tests/ui/regions/regions-scope-chain-example.rs:32:13
   |
28 |     fn foo(&mut self, scope: Scope) {
   |                       ----- has type `Scope<'1>`
29 |         let link = if 1 < 2 {
30 |             let l = ScopeChain::Link(scope);
   |                 - binding `l` declared here
31 |             self.take_scope(&l);
   |             -------------------
   |             |               |
   |             |               borrow of `l` occurs here
   |             argument requires that `l` is borrowed for `'1`
32 |             l
   |             ^ move out of `l` occurs here

error[E0597]: `link` does not live long enough
  --> tests/ui/regions/regions-scope-chain-example.rs:36:25
   |
28 |     fn foo(&mut self, scope: Scope) {
   |                       ----- has type `Scope<'1>`
29 |         let link = if 1 < 2 {
   |             ---- binding `link` declared here
...
36 |         self.take_scope(&link);
   |         ----------------^^^^^-
   |         |               |
   |         |               borrowed value does not live long enough
   |         argument requires that `link` is borrowed for `'1`
37 |     }
   |     - `link` dropped here while still borrowed

error: aborting due to 3 previous errors
```

````
rustc 1.73.0-nightly (04abc370b 2023-07-28)
binary: rustc
commit-hash: 04abc370b9f3855b28172b65a7f7d5a433f41412
commit-date: 2023-07-28
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
````

### PR DESCRIPTION
**Pull request by fmease**
Fixes #114221.

CC @oli-obk
r? types

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/variance/constraints.rs [hunk 1]
```diff
@@ -252,10 +261,18 @@ impl<'a, 'tcx> ConstraintContext<'a, 'tcx> {
...
                 self.add_constraints_from_invariant_args(current, data.args, variance);
             }
 
+            ty::Alias(ty::Weak, ref data) => {
+                if self.tcx().features().lazy_type_alias {
+                    self.add_constraints_from_args(current, data.def_id, data.args, variance);
+                } else {
+                    self.add_constraints_from_invariant_args(current, data.args, variance);
+                }
+            }
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/variance/constraints.rs:274]: I'm not sure if this is correct if the `ty` comes from an external crate. Ideally (?) we'd use `add_constraints_from_args` for *any* weak projection.

**Comment by fmease** [comment]
I'm pretty sure that all occurrences of `tcx.features().lazy_type_alias` should actually be `tcx.features().lazy_type_alias || tcx.type_of(def_id).subst_identity().has_opaque_types()` to consolidate (lazy) type aliases and TAITs.

I tried that locally and all UI tests succeeded except for

1. a single TAIT test, namely `type-alias-impl-trait/obligation_ice.rs` (pass → fail): for some reason, the type parameter `A` on type alias `I` gets flagged as unused / bivariant leading to an error. it likely has to something to do with the way variances are computed for opaques (`I` contains one)
2. several inherent associated type tests (pass / fail → cycle error): since their currently implementation is makeshift, the breakage isn't that noteworthy I'd say

I don't think I know enough about TAITs to attempt to fix it.

@rustbot ready

File: compiler/rustc_hir_analysis/src/variance/constraints.rs [hunk 2]
```diff
@@ -127,11 +131,16 @@ impl<'a, 'tcx> ConstraintContext<'a, 'tcx> {
...
 
             ty::Error(_) => {}
+
             _ => {
-                span_bug!(
-                    tcx.def_span(def_id),
-                    "`build_constraints_for_item` unsupported for this item"
-                );
+                if tcx.features().lazy_type_alias && let DefKind::TyAlias = tcx.def_kind(def_id) {
+                    self.add_constraints_from_ty(current_item, ty, self.covariant);
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/variance/constraints.rs:137]: Leave a comment explaining that we need to check the `DefKind`, because `type_of(def_id)` returns the type behind the alias, not `ty::Alias(ty::Weak, ..)`

**Comment by oli-obk** [comment]
> 1. a single TAIT test, namely `type-alias-impl-trait/obligation_ice.rs` (pass → fail): For some reason, the type parameter `A` on type alias `I` gets flagged as unused / bivariant leading to an error. Maybe it has something to do with the way variances are computed for opaques (`I` does contain one).

you could dump the variance (`RUSTC_LOG=[crate_variances]`) and the hidden type (`RUSTC_LOG=[type_of]`) to collect some more information on this. It seems like the right approach that you're doing.

Note that that test's RPIT equivalent does not compile (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b00a68250b843d20bfa300f35fc7c29c) without also adding a `where 'b: 'a` bound to the function. So something is fishy here anyway

File: tests/rustdoc-json/type/inherent_associated_type_bound.rs
Comment (oli-obk) [inline tests/rustdoc-json/type/inherent_associated_type_bound.rs:1]: why is this test affected? It has neither opaque types nor the lazy type alias feature gate

**Comment by fmease** [comment]
Note that inherent associated types bound to type aliases now lead to cycle errors as previously touched upon. In the relevant UI tests I've replaced type aliases with functions wherever possible.

Superficially the cycles are caused by the added `type_of` calls in `variances_of` but more fundamentally the current implementation of inherent associated types (written by me) is prone to such errors since selection (which tries to acquire a (normalized) `ParamEnv`) happens in `astconv`.

I'm pretty sure those regressions are unavoidable at the present time. I plan on attempting an IAT rewrite at some point of which I'm not sure if it will pan out or not.
