### PR TITLE
rustdoc: Replaces fn main search and extern crate search with proper parsing during doctests.

### LINKED ISSUE #21299: `fn main` in a comment in rustdoc breaks tests
$ cat confuse.md
    ```rust
    // pub fn mai
    ```
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... ok
    
    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
    
    $ sed -i 's/mai/main/' confuse.md
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... FAILED
    
    failures:
    
    ---- _0 stdout ----
            error: main function not found
    error: aborting due to previous error
    thread '_0' panicked at 'Box<Any>', /home/aidanhs/Desktop/rust/rust/src/libsyntax/diagnostic.rs:144
    
    
    
    failures:
        _0
    
    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
    
    thread '<unnamed>' panicked at 'Some tests failed', /home/aidanhs/Desktop/rust/rust/src/libtest/lib.rs:265
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/aidanhs/Desktop/rust/rust/src/libcore/result.rs:746

Per http://doc.rust-lang.org/rustdoc.html, "Given a code block, if it does not contain fn main, it is wrapped in fn main() { your_code }"

Can it not be "does not contain 'fn main (' outside of a comment"?

### LINKED ISSUE #33731: Usage of `extern crate` fails doc tests
If a doc test attempts to import any types declared in it's own crate, including the phrase `extern crate` anywhere in the code will cause the test to not compile, throwing a "unresolved import" error at the attempted import. For example, if we have struct `Foo` in crate `bar`, with the crate `baz` declared under `dev_dependencies`, these tests will all fail to compile when there's no reason for them not to:

```rust
/// ```
/// extern crate baz;
/// use bar::Foo;
/// ```
pub struct Foo{}
```

```rust
/// ```
/// // The phrase "extern crate" breaks this!
/// use bar::Foo;
/// ```
pub struct Foo{}
```

```rust
/// ```
/// use bar::Foo;
/// let string = "extern crate";
/// ```
pub struct Foo{}
```

The following error log is given by `cargo test`:

```
running 1 test
test Foo_0 ... FAILED

failures:

---- Foo_0 stdout ----
        <anon>:2:9: 2:12 error: unresolved import `bar::Foo`. Maybe a missing `extern crate bar`? [E0432]
<anon>:2     use bar::Foo;
                 ^~~
error: aborting due to previous error(s)
thread 'Foo_0' panicked at 'Box<Any>', ../src/librustc\session/mod.rs:153
stack backtrace:
   0:         0x61cc34dc - strncmp
   1:         0x61cc2b5c - strncmp
   2:         0x61c84d6f - strncmp
   3:         0x67f193ba - strncmp
   4:         0x67f96c9b - strncmp
   5:         0x6ca6943d - strncmp
   6:         0x6ca6e301 - strncmp
   7:         0x661e3803 - strncmp
   8:         0x61caf9ba - strncmp
   9:         0x661e3bba - strncmp
  10:         0x61cc1209 - strncmp
  11:     0x7fff457f8101 - strncmp


failures:
    Foo_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Rust version:
```
rustc 1.8.0 (db2939409 2016-04-11)
binary: rustc
commit-hash: db2939409db26ab4904372c82492cd3488e4c44e
commit-date: 2016-04-11
host: x86_64-pc-windows-gnu
release: 1.8.0
```

### PR DESCRIPTION
**Pull request by repnop**
Fixes #21299.
Fixes #33731.

Let me know if there's any additional changes you'd like made!

### CODE REVIEW

**Comment by rep-nop** [comment]
@QuietMisdreavus any idea what's going on there? all of the `librustdoc` tests passed when I ran them so I'm not sure what all that is about.

**Comment by TimNN** [comment]
Thanks for your PR! You should hear from someone from @QuietMisdreavus or someone else on the Rustdoc team soon.

r? @QuietMisdreavus

**Comment by GuillaumeGomez** [comment]
Wo, nice one!

**Comment by rep-nop** [comment]
Should hopefully have time either towards the end of the week or the weekend to get this PR fixed up and ready to go :ok_hand:

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus: This PR requires your review.

**Comment by QuietMisdreavus** [comment]
Looks like the parsing errors are still being printed, though it's not causing rustdoc to fail:

```
[00:43:51] error: expected item after attributes
[00:43:51]  --> <anon>:1:31
[00:43:51]   |
[00:43:51] 1 | #[feature(exhaustive_patterns)]
[00:43:51]   |                               ^
[00:43:51] 
[00:43:51] error: macros that expand to items must either be surrounded with braces or followed by a semicolon
[00:43:51]  --> <anon>:2:15
[00:43:51]   |
[00:43:51] 2 | compile_error!("Either feature \"foo\" or \"bar\" must be enabled for this crate.")
[00:43:51]   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:43:51] 
[00:43:51] error: unexpected token: `...`
[00:43:51]   --> <anon>:10:26
[00:43:51]    |
[00:43:51] 10 |         _mm256_add_epi64(...);
[00:43:51]    |                          ^^^
[00:43:51] help: use `..` for an exclusive range
[00:43:51]    |
[00:43:51] 10 |         _mm256_add_epi64(..);
[00:43:51]    |                          ^^
[00:43:51] help: or `..=` for an inclusive range
[00:43:51]    |
[00:43:51] 10 |         _mm256_add_epi64(..=);
[00:43:51]    |                          ^^^
[00:43:51] 
[00:43:51] error[E0586]: inclusive range with no end
[00:43:51]   --> <anon>:10:29
[00:43:51]    |
[00:43:51] 10 |         _mm256_add_epi64(...);
[00:43:51]    |                             ^
[00:43:51]    |
[00:43:51]    = help: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)
[00:43:51] 
[00:43:51] error: unexpected token: `...`
[00:43:51]   --> <anon>:20:22
[00:43:51]    |
[00:43:51] 20 |     _mm256_add_epi64(...);
[00:43:51]    |                      ^^^
[00:43:51] help: use `..` for an exclusive range
[00:43:51]    |
[00:43:51] 20 |     _mm256_add_epi64(..);
[00:43:51]    |                      ^^
[00:43:51] help: or `..=` for an inclusive range
[00:43:51]    |
[00:43:51] 20 |     _mm256_add_epi64(..=);
[00:43:51]    |                      ^^^
[00:43:51] 
[00:43:51] error[E0586]: inclusive range with no end
[00:43:51]   --> <anon>:20:25
[00:43:51]    |
[00:43:51] 20 |     _mm256_add_epi64(...);
[00:43:51]    |                         ^
[00:43:51]    |
[00:43:51]    = help: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)
```

However, it looks like what actually caused the failure was the error index generator? There's a new batch of errors at the end of the travis log:

```
[00:44:34] error: only foreign functions are allowed to be variadic
[00:44:34]  --> <anon>:5:15
[00:44:34]   |
[00:44:34] 5 | fn foo(x: u8, ...) {}
[00:44:34]   |               ^^^
[00:44:34] 
[00:44:34] error[E0178]: expected a path on the left-hand side of `+`, not `&'a Foo`
[00:44:34]  --> <anon>:4:8
[00:44:34]   |
[00:44:34] 4 |     w: &'a Foo + Copy,   // error, use &'a (Foo + Copy)
[00:44:34]   |        ^^^^^^^^^^^^^^ help: try adding parentheses: `&'a (Foo + Copy)`
[00:44:34] 
[00:44:34] error[E0178]: expected a path on the left-hand side of `+`, not `&'a Foo`
[00:44:34]  --> <anon>:5:8
[00:44:34]   |
[00:44:34] 5 |     x: &'a Foo + 'a,     // error, use &'a (Foo + 'a)
[00:44:34]   |        ^^^^^^^^^^^^ help: try adding parentheses: `&'a (Foo + 'a)`
[00:44:34] 
[00:44:34] error[E0178]: expected a path on the left-hand side of `+`, not `&'a mut Foo`
[00:44:34]  --> <anon>:6:8
[00:44:34]   |
[00:44:34] 6 |     y: &'a mut Foo + 'a, // error, use &'a mut (Foo + 'a)
[00:44:34]   |        ^^^^^^^^^^^^^^^^ help: try adding parentheses: `&'a mut (Foo + 'a)`
[00:44:34] 
[00:44:34] error[E0178]: expected a path on the left-hand side of `+`, not `fn() -> Foo`
[00:44:34]  --> <anon>:7:8
[00:44:34]   |
[00:44:34] 7 |     z: fn() -> Foo + 'a, // error, use fn() -> (Foo + 'a)
[00:44:34]   |        ^^^^^^^^^^^^^^^^ perhaps you forgot parentheses?
[00:44:34] 
[00:44:34] error: unexpected close delimiter: `}`
[00:44:34]  --> <anon>:5:1
[00:44:34]   |
[00:44:34] 5 | }
[00:44:34]   | ^ unexpected close delimiter
```

I need to look closer to see why the error-index generator is running into problems, but that's at least the source of the current travis failure.

**Comment by rep-nop** [comment]
Odd that the errors are still being printed, I didn't experience that doing a local doc build. But yeah, those hard errors are what have caused me to get kind of stuck :( I tried a bunch of different things locally, from how I was handling the errors, to trying different ways of cancelling -- all to no avail. If you have any hints on the cause I should hopefully have time this weekend to fix it up and then maybe, _just maybe_, the PR will finally build 😄

**Comment by QuietMisdreavus** [comment]
The reason the error-index generator is running through your code is because it uses rustdoc's Markdown parsing code to output HTML, and the Markdown parsing uses the test generator to create playground links for code samples.

I also looked into libsyntax, and i think i know why it's still emitting the errors: the parser code doesn't bubble up every error it creates. For example, here's the spot in the parser that corresponds to the first error from the error-index:

https://github.com/rust-lang/rust/blob/de9666f123e800d5fc34210f23127aa6a5d6e4ef/src/libsyntax/parse/parser.rs#L5363-L5366

Since the parser considers it an error but wants to continue parsing the function to emit any other errors, it immediately emits the error and carries on. To truly silence errors from the parser, it looks like we'll need to go through this parsing code and figure out a way to silence them, but only for this one location.

I also found why it failed entirely: any errors that come out of the conversion to a TokenStream (done during the creation of the Parser) that are immediately thrown as a fatal error. This includes the "unexpected close delimiter" at the end of the error index's errors. I'm having trouble finding the specific example that is causing the issue, though, since so many samples are *supposed* to fail compiling. There's also the possibility that something about the `partition_source` implementation is causing malformed code to be sent to the parser. I'll try digging a little more.

**Comment by QuietMisdreavus** [comment]
Update: I found it! I had to wire `env_logger` into the error-index generator so i could print logs from rustdoc, but i eventually found out that the program that was failing looked like this:

image

The comment on the crate line absorbs the opening delimiter for the module that the test defines, because there was no line break between them, even though that line break existed in the original. I'm rebuilding now, but you should add `crates.push_str("\n");` to your addition to `partition_source`, so that this can properly parse.

That just leaves the errors being printed. I'm investigating using an error emitter that sends information to an `io::sink()` instead of stdout, so that the messages get ignored entirely. It requires a lot more setup, and it'll probably require adding a method to libsyntax so that we can parse a TokenStream without printing or emitting an error from its first token.

**Comment by QuietMisdreavus** [comment]
I wound up writing the fix in myself, so i'm going to swap in a new reviewer:

r? @GuillaumeGomez 

I'd also like someone from @rust-lang/compiler to take a look since i'm adding a few new methods in libsyntax and i want to make sure i'm not stepping on anyone's toes.

File: src/libsyntax/parse/mod.rs [hunk 1]
```diff
@@ -174,14 +174,25 @@ pub fn parse_stream_from_source_str(name: FileName, source: String, sess: &Parse
     source_file_to_stream(sess, sess.source_map().new_source_file(name, source), override_span)
 }
 
-// Create a new parser from a source string
+/// Create a new parser from a source string
```
Comment (estebank) [inline src/libsyntax/parse/mod.rs]: Shouldn't this use `maybe_new_parser_from_source_str` and emit the buffered errors? That would also allow removing `source_file_to_parser`, I think.

File: src/libsyntax/parse/lexer/mod.rs [hunk 2]
```diff
@@ -175,6 +175,16 @@ impl<'a> StringReader<'a> {
         self.fatal_errs.clear();
     }
 
+    pub fn buffer_fatal_errors(&mut self) -> Vec<Diagnostic> {
```
Comment (estebank) [inline src/libsyntax/parse/lexer/mod.rs]: Was this was the only API addition you needed?

Comment (QuietMisdreavus) [reply src/libsyntax/parse/lexer/mod.rs]: This and the `new_or_buffered_errs` constructor. I needed a way to "handle" the errors without prematurely emitting them (in this case, to cancel them), and this felt like a natural way to get the content of `self.fatal_errs` without just exposing the Vec directly. Since both `new` and `new_without_err` emitted the errors directly, i added this instead.

File: src/libsyntax/parse/mod.rs (hunk 1 above)
Comment (QuietMisdreavus) [reply src/libsyntax/parse/mod.rs]: How deep do you want me to go? Should i reimplement each existing function in terms of its new `maybe_` variant?

File: src/libsyntax/parse/lexer/mod.rs (hunk 2 above)
Comment (estebank) [reply src/libsyntax/parse/lexer/mod.rs]: I'm not against it, I'm surprised at how little you needed to add :)

File: src/libsyntax/parse/mod.rs (hunk 1 above)
Comment (estebank) [reply src/libsyntax/parse/mod.rs]: If you have the time, that'd be great. I just want to minimize code duplication. Whenever I add a fallible version of an existing method, I rewrite the callees if under a dozen, or I rewrite the infallible version to call the fallible version.

Comment (QuietMisdreavus) [reply src/libsyntax/parse/mod.rs]: Makes sense. I've got the change written locally, i'll push once i finish my current build.

File: src/libsyntax/parse/lexer/mod.rs (hunk 2 above)
Comment (QuietMisdreavus) [reply src/libsyntax/parse/lexer/mod.rs]: Yup! I just needed a version that wouldn't immediately crash the process if it ran into a problem in the first token. One thing i will ask is whether the current implementation with `buffer()` is appropriate, since plain Diagnostics don't have the destructor bomb that full `DiagnosticBuilder`s have. (Since they need a `Handler` to be emitted, they don't have the same ability to forcibly print themselves.) The alternative would be to swap out the Vec entirely and return the full DiagnosticBuilder, and since the `ParseSess` isn't local the lifetimes would work out.

**Comment by QuietMisdreavus** [comment]
Whoops, wrote `new_parser_from_source_str` wrong. I amended the last commit and force-pushed.

**Comment by estebank** [comment]
It seems to have failed again with the same error

```
[01:32:52] error: expected identifier, found keyword `return`
[01:32:52]  --> bogofile:1:13
[01:32:52]   |
[01:32:52] 1 | ::abc::def::return
[01:32:52]   |             ^^^^^^ expected identifier, found keyword
[01:32:52] 
[01:32:52] ..........................F...........................................................
[01:32:52] failures:
[01:32:52] 
[01:32:52] ---- parse::tests::out_of_line_mod stdout ----
[01:32:52] thread 'parse::tests::out_of_line_mod' panicked at 'called `Result::unwrap()` on an `Err` value: Diagnostic { level: Error, message: [("file not found for module `this_does_not_exist`", NoStyle)], code: Some(Error("E0583")), span: MultiSpan { primary_spans: [Span { lo: BytePos(24), hi: BytePos(43), ctxt: #0 }], span_labels: [] }, children: [SubDiagnostic { level: Help, message: [("name the file either this_does_not_exist.rs or this_does_not_exist/mod.rs inside the directory \"foo\"", NoStyle)], span: MultiSpan { primary_spans: [], span_labels: [] }, render_span: None }], suggestions: [] }', libcore/result.rs:1009:5
[01:32:52] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:32:52] 
[01:32:52] 
[01:32:52] failures:
[01:32:52]     parse::tests::out_of_line_mod
[01:32:52] 
[01:32:52] test result: FAILED. 85 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by QuietMisdreavus** [comment]
That message about `::abc::def::return` is normal, that's printed even on successful runs.

But the panic message... that passes locally, so i have no idea what it's running into! `o_O` Let me try to run a clean build and see if it still fails.

**Comment by QuietMisdreavus** [comment]
Oh hey, my bluff about just forcing travis to try again seems to have worked! CI is green now.

File: src/libsyntax/parse/lexer/mod.rs (hunk 2 above)
Comment (eddyb) [reply src/libsyntax/parse/lexer/mod.rs]: cc @petrochenkov
