### PR TITLE
Normalize both arguments of `equate_normalized_input_or_output`

### LINKED ISSUE #90612: ICE: broken MIR in DefId (equate_normalized_input_or_output failed with NoSolution)
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=86aaa0d4d2768f39a07115e1703e0728):

```rust
#![feature(generic_associated_types)]

use std::marker::PhantomData;

trait Family: Sized {
    type Item<'a>;
    
    fn apply_all<F>(&self, f: F)
    where
        F: FamilyItemFn<Self> { }
}

struct Array<T>(PhantomData<T>);

impl<T: 'static> Family for Array<T> {
    type Item<'a> = &'a T;
}

trait FamilyItemFn<T: Family> {
    fn apply(&self, item: T::Item<'_>);
}

impl<T, F> FamilyItemFn<T> for F
where 
    T: Family,
    for<'a> F: Fn(T::Item<'a>)
{
    fn apply(&self, item: T::Item<'_>) {
        (*self)(item);
    }
}

fn process<T: 'static>(array: Array<T>) {
    // Works
    array.apply_all(|x: &T| { });
    
    // ICE: NoSolution
    array.apply_all(|x: <Array<T> as Family>::Item<'_>| { });
}
```
This should compile and work, but instead it ICEs.

It doesn't ICE if I remove the generic parameter from `Array` or use `array.apply_all(|x: &T| { });`

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (1f12ac872 2021-10-17)
binary: rustc
commit-hash: 1f12ac87296ac61ec002e0243e7ad5a50364da35
commit-date: 2021-10-17
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0

```

<details><summary>Backtrace</summary>
<p>

```
error: internal compiler error: broken MIR in DefId(0:30 ~ test[68ae]::process::{closure#1}) (bb0[0]): equate_normalized_input_or_output: `&[closure@test.rs:46:21: 46:60]==&[closure@test.rs:46:21: 46:60]` failed with `NoSolution`
  --> test.rs:46:60
   |
46 |     array.apply_all(|x: <Array<T> as Family>::Item<'_>| { });
   |                                                            ^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:330:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1165:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1f12ac87296ac61ec002e0243e7ad5a50364da35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/1f12ac87296ac61ec002e0243e7ad5a50364da35/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_display
   3: rustc_errors::HandlerInner::flush_delayed
   4: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   6: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   8: rustc_span::with_source_map
   9: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
```

</p>
</details>

### LINKED ISSUE #90638: ICE: Broken MIR equate_normalized_input_or_output: failed with `NoSolution`
This is related to https://github.com/rust-lang/rust/issues/89196 and https://github.com/rust-lang/rust/issues/85636 ; but is not the same issue: https://github.com/rust-lang/rust/issues/85636 is already resolved and  https://github.com/rust-lang/rust/issues/89196 is dealing with a more complex case where _inference_ is lacking.

Also perhaps related to https://github.com/rust-lang/rust/issues/56556

I'm filing an ICE because that's what I'm hitting as I try to reduce it, however I have a related bug where the workaround from https://github.com/rust-lang/rust/issues/85636 doesn't actually work. I wonder if fixing the ICE will make this code compile or if it will hit code that needs to be worked around (My unreduced code is at https://github.com/Manishearth/icu4x/tree/rm-rcstruct , `cd provider/core && cargo check --all-features`)

### Code

<details> <summary> Code </summary>

```rust
trait Yokeable<'a>: 'static {
    type Output: 'a;
}

trait IsCovariant<'a> {}

struct Yoke<Y: for<'a> Yokeable<'a>> {
    data: Y,
}


impl<Y: for<'a> Yokeable<'a>> Yoke<Y> {
    fn project<Y2: for<'a> Yokeable<'a>>(&self, f: for<'a> fn(<Y as Yokeable<'a>>::Output, &'a ()) -> <Y2 as Yokeable<'a>>::Output) -> Yoke<Y2> {
        unimplemented!()
    }
}

fn upcast<Y>(x: Yoke<Y>) -> Yoke<Box<dyn IsCovariant<'static> + 'static>> where
    Y: for<'a> Yokeable<'a>,
    for<'a> <Y as Yokeable<'a>>::Output: IsCovariant<'a>
    {
    x.project(|data, _| {
        Box::new(data)
    })
}


impl<'a> Yokeable<'a> for Box<dyn IsCovariant<'static> + 'static> {
    type Output = Box<dyn IsCovariant<'a> + 'a>;
}

// this impl is mostly an example and unnecessary for the pure repro
use std::borrow::Cow;
impl<'a, T: Clone> Yokeable<'a> for Cow<'static, T> {
    type Output = Cow<'a, T>;
}
impl<'a, T: Clone> IsCovariant<'a> for Cow<'a, T> {}
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

</details>

[playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=eb6d04a862fa7d83917673c8f1582897)

### Error output

```
error: internal compiler error: broken MIR in DefId(0:23 ~ test[68ae]::upcast::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@test.rs:23:15: 25:6]==&[closure@test.rs:23:15: 25:6]` failed with `NoSolution`
  --> test.rs:23:15
   |
23 |       x.project(|data, _| {
   |  _______________^
24 | |         Box::new(data)
25 | |     })
   | |_____^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:319:27
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: broken MIR in DefId(0:23 ~ test[68ae]::upcast::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@test.rs:23:15: 25:6]==&[closure@test.rs:23:15: 25:6]` failed with `NoSolution`
  --> test.rs:23:15
   |
23 |       x.project(|data, _| {
   |  _______________^
24 | |         Box::new(data)
25 | |     })
   | |_____^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:319:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1166:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_display
   3: rustc_errors::HandlerInner::flush_delayed
   4: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   6: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   8: rustc_span::with_source_map
   9: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

```

</p>
</details>

cc @jackh726 @eddyb

### PR DESCRIPTION
**Pull request by b-naber**
Fixes https://github.com/rust-lang/rust/issues/90638
Fixes https://github.com/rust-lang/rust/issues/90612

Temporary fix for a more complex underlying problem stemming from an inability to normalize closure substs during typecheck.

r? @jackh726

### CODE REVIEW

**Comment by b-naber** [comment]
Don't understand why this fails to build in CI, compiles locally. Is `Lrc` not the same as `Rc`? Why is `Arc` expected in the error?

**Comment by hkratz** [comment]
> Don't understand why this fails to build in CI, compiles locally. Is `Lrc` not the same as `Rc`? Why is `Arc` expected in the error?

Quoting the doc: `Lrc` is an alias of `Arc` if cfg!(parallel_compiler) is true, `Rc` otherwise. 

`TypeOpOutput::constraints` is always `Option<Rc<QueryRegionConstraints<'tcx>>>`

File: compiler/rustc_borrowck/src/type_check/input_output.rs [hunk 1]
```diff
@@ -207,4 +206,39 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
             }
         }
     }
+
+    pub(crate) fn normalize_and_add_constraints<'b>(
+        &mut self,
+        t: Ty<'tcx>,
+        constraints: &'b mut Vec<Lrc<QueryRegionConstraints<'tcx>>>,
+    ) -> Fallible<Ty<'tcx>> {
```
Comment (jackh726) [inline compiler/rustc_borrowck/src/type_check/input_output.rs:214]: Why not just return both the Ty and constraints together?

File: compiler/rustc_borrowck/src/type_check/input_output.rs [hunk 2]
```diff
@@ -207,4 +206,39 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
+
+        let mut arg_constraints = constraints_args.into_iter().collect();
+        constraints.append(&mut arg_constraints);
+
+        Ok(norm_ty)
+    }
+
+    pub(crate) fn add_constraints(
+        &mut self,
+        constraints: &mut Vec<Lrc<QueryRegionConstraints<'tcx>>>,
```
Comment (jackh726) [inline compiler/rustc_borrowck/src/type_check/input_output.rs:228]: And just take constraints by value.

File: compiler/rustc_borrowck/src/type_check/input_output.rs (hunk 1 above)
Comment (jackh726) [reply compiler/rustc_borrowck/src/type_check/input_output.rs:214]: Or better...just add the constraints here because we have self.

File: src/test/ui/generic-associated-types/issue-90612.rs [hunk 3]
```diff
@@ -0,0 +1,43 @@
+// check-pass
+
+#![feature(generic_associated_types)]
```
Comment (jackh726) [inline src/test/ui/generic-associated-types/issue-90612.rs:3]: I think both these tests would be better with the other normalize under binder tests. This one uses GATs, but is not a GATs issue. The other doesn't even use GATs.

File: src/test/ui/generic-associated-types/issue-90638.rs [hunk 4]
```diff
@@ -0,0 +1,38 @@
+//check-pass
+
+#![feature(generic_associated_types)]
+#![allow(incomplete_features)]
```
Comment (jackh726) [inline src/test/ui/generic-associated-types/issue-90638.rs:4]: Doesn't need incomplete.

**Review by jackh726 — CHANGES_REQUESTED** [review]

**Comment by b-naber** [comment]
> > Don't understand why this fails to build in CI, compiles locally. Is `Lrc` not the same as `Rc`? Why is `Arc` expected in the error?
> 
> Quoting the doc: `Lrc` is an alias of `Arc` if cfg!(parallel_compiler) is true, `Rc` otherwise. `TypeOpOutput::constraints` is always `Option<Rc<QueryRegionConstraints<'tcx>>>` The mingw-check CI runs with the `parallel-compiler` turned on.

Thanks for the answer.

**Comment by b-naber** [comment]
@jackh726 thanks for the review, addressed your comments.

File: src/test/ui/associated-types/issue-90612.rs [hunk 5]
```diff
@@ -0,0 +1,43 @@
+// check-pass
+
+#![feature(generic_associated_types)]
```
Comment (jackh726) [inline src/test/ui/associated-types/issue-90612.rs:3]: Sorry, for the location I meant `src/test/ui/higher-rank-trait-bounds/normalize-under-binder`

File: compiler/rustc_borrowck/src/type_check/input_output.rs [hunk 6]
```diff
@@ -207,4 +200,27 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
             }
         }
     }
+
+    pub(crate) fn normalize_and_add_constraints(&mut self, t: Ty<'tcx>) -> Fallible<Ty<'tcx>> {
+        let TypeOpOutput { output: norm_ty, constraints, .. } =
```
Comment (jackh726) [inline compiler/rustc_borrowck/src/type_check/input_output.rs:205]: I forget, what are we not destructoring? For a bit, I thought we were ignoring obligations, but then I realized we switched to using a TypeOp (good idea).

**Review by jackh726 — CHANGES_REQUESTED** [review]

File: compiler/rustc_borrowck/src/type_check/input_output.rs (hunk 6 above)
Comment (b-naber) [reply compiler/rustc_borrowck/src/type_check/input_output.rs:205]: `canonicalized_query: Option<Canonical<'tcx, Op>>`, which is only used for diagnostics purposes.

**Comment by jackh726** [comment]
@bors r+ 

Thanks @b-naber
