### PR TITLE
Emit suggestion when trying to write exclusive ranges as `..<`

### LINKED ISSUE #112254: Diagnostic when trying to write exclusive ranges as `..<`
### Code

```Rust
fn foo() {
    0..=10; // OK
    0..<10; // error (valid in Swift)
}
```

### Current output

```Shell
error: expected type, found `10`
 --> src/lib.rs:3:9
  |
3 |     0..<10; // error (valid in Swift)
  |         ^^ expected type
```

### Desired output

Suggest `0..10`.

### Rationale and extra context

The syntax `..=` for inclusive ranges seems to suggest `..<` for exclusive ranges, especially since Swift uses `..<` for exclusive ranges.

(Though, Swift doesn't use `..=` for inclusive ranges, but rather `…`.)

I initially thought this would be easy to diagnose since `..<` is never legal syntax, but actually it can be legal as part of an exclusive range where the upper bound is an UFCS call:
```rust
0..<A>::b(); // OK
```

Oh well.

### PR DESCRIPTION
**Pull request by sjwang05**
Closes #112254

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? compiler
I'm overloaded with reviews.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -448,11 +448,16 @@ impl<'a> Parser<'a> {
             })
         }
 
-        let mut expected = edible
+        self.expected_tokens.extend(
+            edible
+                .iter()
+                .map(|x| TokenType::Token(x.clone()))
+                .chain(inedible.iter().map(|x| TokenType::Token(x.clone()))),
+        );
```
Comment (sjwang05) [inline compiler/rustc_parse/src/parser/diagnostics.rs:456]: This is necessary because otherwise `token::Gt` won't show up in `expected_tokens` when we check for it when emitting the diagnostic.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @sjwang05, this looks great to me!

@bors r+
