### PR TITLE
Fix early lints inside an async desugaring

### LINKED ISSUE #81531: internal compiler error: failed to process buffered lint here
### Code

I don't have a minimal example yet, but here's [the code](https://cs.opensource.google/fuchsia/fuchsia/+/master:src/sys/pkg/lib/omaha-client/src/state_machine.rs;l=539;drc=135c122764c96cb5132d4d1bbb51bb75b2f12a92). Sample:

```Rust
    async fn report_check_interval(&mut self, install_source: InstallSource) {
        let now = self.time_source.now();

        match self.context.schedule.last_update_check_time {
            Some(PartialComplexTime::Wall(t)) => match now.wall_duration_since(t) {
                Ok(interval) => self.report_metrics(Metrics::UpdateCheckInterval {
                    interval,
                    clock: ClockType::Wall,
                    install_source,
                }),
                Err(e) => warn!("Last check time is in the future: {}", e),  // <-- ICE
            },

            Some(PartialComplexTime::Complex(t)) => match now.mono.checked_duration_since(t.mono) {
                Some(interval) => self.report_metrics(Metrics::UpdateCheckInterval {
                    interval,
                    clock: ClockType::Monotonic,
                    install_source,
                }),
                None => error!("Monotonic time in the past"),  // <-- ICE
            },

            _ => {}
        }

        self.context.schedule.last_update_check_time = now.into();
    }
```

The ICE happens on the `warn!` and `error!` macros, which are both from the `log` crate.

### Meta

This began with commit 74500b99783d126e330184f0392a78f8b93b73ef.

### Error output

```
error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:539:27
    |
539 |                 Err(e) => warn!("Last check time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:552:25
    |
552 |                 None => error!("Monotonic time in the past"),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:997:27
    |
997 |                 Err(e) => warn!("Update first seen time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 RUST_BACKTRACE=1 ../../prebuilt/third_party/rust/linux-x64/bin/rustc --color=always --crate-name omaha_client ../../src/sys/pkg/lib/omaha-client/src/lib.rs --crate-type rlib --emit=dep-info=obj/sr…
error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:539:27
    |
539 |                 Err(e) => warn!("Last check time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:552:25
    |
552 |                 None => error!("Monotonic time in the past"),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:997:27
    |
997 |                 Err(e) => warn!("Update first seen time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /b/s/w/ir/x/w/rust/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /b/s/w/ir/x/w/rust/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (b12290861 2021-01-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dep-info-omit-d-target -Z allow-features= -Z panic_abort_tests -C linker=/b/s/w/ir/x/w/fuchsia/prebuilt/third_party/clang/linux-x64/bin/lld -C link-arg=--sysroot=gen/zircon…

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #81531

When we buffer an early lint for a macro invocation,
we need to determine which NodeId to take the lint level from.
Currently, we use the NodeId of the closest def parent. However, if
the macro invocation is inside the desugared closure from an `async fn`
or async closure, that NodeId does not actually exist in the AST.

This commit uses the parent of a desugared closure when computing
`lint_node_id`, which is something that actually exists in the AST (an
`async fn` or async closure).

### CODE REVIEW

File: compiler/rustc_resolve/src/macros.rs [hunk 1]
```diff
@@ -346,9 +347,23 @@ impl<'a> ResolverExpand for Resolver<'a> {
     fn lint_node_id(&mut self, expn_id: ExpnId) -> NodeId {
         // FIXME - make this more precise. This currently returns the NodeId of the
         // nearest closing item - we should try to return the closest parent of the ExpnId
-        self.invocation_parents
-            .get(&expn_id)
-            .map_or(ast::CRATE_NODE_ID, |id| self.def_id_to_node_id[*id])
+        if let Some(mut def_id) = self.invocation_parents.get(&expn_id).copied() {
+            // If a closure resuls from an async desugaring, then it doesn't actually exist in the AST
```
Comment (henryboisdequin) [inline compiler/rustc_resolve/src/macros.rs:351]: Little spelling mistake: resuls

**Comment by varkor** [comment]
I see @petrochenkov assigned themselves, so I'll defer the review to them. (@petrochenkov: feel free to reassign me if you don't want to take it.)

**Comment by petrochenkov** [comment]
@varkor I mostly wanted to be aware of the changes in this area and assigned myself to not forget.

File: compiler/rustc_resolve/src/macros.rs [hunk 2]
```diff
@@ -346,9 +347,23 @@ impl<'a> ResolverExpand for Resolver<'a> {
...
+            // Lint at its parent instead, which is an actual AST node
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:352]: Is it possible to determine that this def-id is "special" without introducing a new table for async closures specifically?
E.g. does it have an entry in `def_id_to_node_id`? Is that entry `DUMMY_NODE_ID`? Or it's just a regular def-id indiscernible from those presenting in AST?

Comment (Aaron1011) [reply compiler/rustc_resolve/src/macros.rs:352]: Unfortunately, it's just a regular `DefId`, and is actually used during AST lowering and typeck.

An alternative would be to modify the early lint to explicitly check for `Async::Yes` - however, that would make it the only case where we lint a `NodeId` that doesn't really exist in the AST.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs:352]: >An alternative would be to modify the early lint pass to explicitly check for Async::Yes

I think this may actually be a better solution.
The node ids do exist in AST as a part of the `Async::Yes` node, that node is just not yet transformed into a closure.

**Comment by Aaron1011** [comment]
@petrochenkov: I've updated the PR explicitly handle `Async::Yes` during linting.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Comment by Aaron1011** [comment]
This bug has been affecting a lot of users (see https://github.com/rust-lang/rust/issues/81531)

@bors p=1
