### PR TITLE
Remove the unhelpful let binding diag comes from FormatArguments

### LINKED ISSUE #114374: borrow error gives unhelpful let binding suggestion
### Code

```Rust
fn bar<'a>(_: std::fmt::Arguments<'a>) {
    
}

fn main() {
    let foo = format_args!("{}", "hi");
    
    bar(foo);
}
```

### Current output

```Shell
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:6:15
  |
6 |     let foo = format_args!("{}", "hi");
  |               ^^^^^^^^^^^^^^^^^^^^^^^^- temporary value is freed at the end of this statement
  |               |
  |               creates a temporary value which is freed while still in use
7 |     
8 |     bar(foo);
  |         --- borrow later used here
  |
  = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using a `let` binding to create a longer lived value
  |
6 ~     let binding = format_args!("{}", "hi");
7 ~     let foo = binding;
  |

For more information about this error, try `rustc --explain E0716`.
```

### Desired output

```Shell
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:6:15
  |
6 |     let foo = format_args!("{}", "hi");
  |               ^^^^^^^^^^^^^^^^^^^^^^^^- temporary value is freed at the end of this statement
  |               |
  |               creates a temporary value which is freed while still in use
7 |     
8 |     bar(foo);
  |         --- borrow later used here
  |
  = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Rationale and extra context

The binding suggestion is not helpful, attempting to use it will just create the same error with the same suggestion.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #114374

### CODE REVIEW

**Comment by fee1-dead** [comment]
Not entirely sure if this is what should happen.

r? compiler

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -2130,21 +2130,27 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                    fn visit_block(&mut self, block: &'tcx hir::Block<'tcx>) {
                         self.current += 1;
                         walk_block(self, block);
                         self.current -= 1;
                     }
-                    fn visit_expr(&mut self, expr: &hir::Expr<'tcx>) {
+                    fn visit_expr(&mut self, expr: &'tcx hir::Expr<'tcx>) {
                         if self.span == expr.span.source_callsite() {
                             self.found = self.current;
+                            if self.prop_expr.is_none() {
```
Comment (b-naber) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2151]: What if we have nested `format_args` expressions?

Do we only care about the case where we assign the result of `format_args!`? If so, why can't we just check for `stmt` being an assignment where the rhs expr `is_format_args_item`?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -2162,9 +2168,23 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                        let is_format_arguments_item =
+                            if let Some(expr_ty) = expr_ty
+                               && let ty::Adt(adt, _) = expr_ty.kind() {
+                                    self.infcx.tcx.lang_items().get(LangItem::FormatArguments) == Some(adt.did())
+                               } else {
+                                   false
+                               };
+
                         if visitor.found == 0
+                            && !is_format_arguments_item
```
Comment (b-naber) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2187]: If we already special-case for `FormatArguments`, can't we also provide a more helpful diagnostic, which explains why this fails, instead of just getting rid of the binding suggestion? Note that we also still have this note: `= note: consider using a `let` binding to create a longer lived value`, so it might make sense to special case this.

Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: Good point!
I add a special note for `format_args!`, I'm not sure whether the words are accurate enough, seems it's hard to explain 😂 , so I added a link to the document.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2151]: the `if self.span == expr.span.source_callsite()` guarantee we find out the expr we're intrested in, the code goes here means a borrow(mostly binding) happens, I think use span to find expr is mostly enough for suggestions.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 3]
```diff
@@ -2162,22 +2168,40 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                                err.multipart_suggestion_verbose(
+                                    msg,
+                                    vec![
+                                        (stmt.span.shrink_to_lo(), addition),
+                                        (proper_span, "binding".to_string()),
+                                    ],
+                                    Applicability::MaybeIncorrect,
+                                );
+                            } else {
+                                err.note("`format_args!` avoids heap allocations, you may use it as parameter in `format!` or other formatting macros directly");
```
Comment (b-naber) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2202]: This compiles though:

```
#![allow(dead_code)]
fn bar<'a>(_: std::fmt::Arguments<'a>) {}

fn main() {
    let foo = format_args!("hi");
    //~^ ERROR temporary value dropped while borrowed

    bar(foo);
}
```

Maybe instead write that the result of `format_args!` can only be assigned directly if no placeholders are used or something like that?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 1 above)
Comment (b-naber) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2151]: What does your branch output on something like this: `let x = format_args!("a {} {} {}.", 1, format_args!("b{}!", 2), 3)`? Can you maybe add this to your test?

Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:2151]: this is valid code, the output is:
```console
warning: unused variable: `x`
 --> tests/ui/borrowck/issue-114374-invalid-help-fmt-args.rs:5:9
  |
5 |     let x = format_args!("a {} {} {}.", 1, format_args!("b{}!", 2), 3);
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default
```
if we use `_x` the code will compile successfully.
This means this code will not get into the code path in this PR.
I added it to the test case.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: make sense, updated the suggestion words.
