### PR TITLE
Use verbose span suggestion for type const

### LINKED ISSUE #154214: Diagnosis improvement in cases where type is not written in mGCA
### Code

```Rust
#![feature(min_generic_const_args)]

fn foo<const N: usize>() {}

const X: usize = 1;

fn main() {
    foo::<X>();
}
```

### Current output

```Shell
error: use of `const` in the type system not defined as `type const`
 --> src/main.rs:8:11
  |
5 | const X: usize = 1;
  | - help: add `type` before `const` for `X`: `type`
...
8 |     foo::<X>();
  |           ^
```

### Desired output

```Shell
error: use of `const` in the type system not defined as `type const`
 --> src/main.rs:8:11
  |
5 | const X: u32 = 1;
  | - help: add `type` before `const` for `X`: `usize` // instead of `type`
                                                       // or just "add `type` before `const`"
...
8 |     foo::<X>();
  |           ^
```

### Rationale and extra context

It says "help: add `type` before `const` for `X`: `type`", but the `type` in add `type` is the string `type` as is, whereas the `type` in `const` for `X`: `type` refers to the type of `X`.

I think the two could be confusing.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.96.0-nightly (1e2183119 2026-03-15)
binary: rustc
commit-hash: 1e2183119f0ee19cc26df899e26b04ad0de3475d
commit-date: 2026-03-15
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by reddevilmidzy**
close: https://github.com/rust-lang/rust/issues/154214

r? fmease

### CODE REVIEW

File: tests/ui/const-generics/mgca/missing-type-const.rs
Comment (fmease) [inline tests/ui/const-generics/mgca/missing-type-const.rs:1]: Ignoring the `.stderr` file, this test also passes on branch main including `rustfix`, so it's easy for someone else to accidentally `--bless` your changes away again the future, so it's not a super robust regression test. I'm inclined to say that this test isn't really necessary.

As you know the main reason we're changing this from an inline to a verbose suggestion is avoiding the help message `` add `type` before `const` for `X`: `type` `` as it looks confusingly similar to `` add `type` before `const X: type` `` IIUC.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2947,7 +2947,7 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             );
             if def_id.is_local() {
                 let name = tcx.def_path_str(def_id);
-                err.span_suggestion(
+                err.span_suggestion_verbose(
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2950]: Instead of a regression test, if you want to you can a short comment explaining why the suggestion is meant to be verbose (but you really don't need to).

In case you do want to a add a comment: I'm thinking of sth. like

```suggestion
                // Verbose since an inline suggestion would look too confusing. See #154214.
                err.span_suggestion_verbose(
```

File: tests/ui/const-generics/mgca/missing-type-const.rs
Comment (reddevilmidzy) [reply tests/ui/const-generics/mgca/missing-type-const.rs:1]: Got it, that makes sense.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 1 above)
Comment (reddevilmidzy) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2950]: Thanks! I’ll skip the comment for now since the change is pretty small and clear.

**Review by fmease — APPROVED** [review]
Thanks! @bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154293/0312931d8c0ba1a28268a12c06202b68cbc65f76..e03983878f36f6568acccd09778ddbb917cf3b20)*
