### PR TITLE
trans: don't declare symbols that were already imported.

### LINKED ISSUE #32740: Can't compile the nix library since da66431
I wish I could have a better title :neutral_face: 

A few days ago, I came across a compiler issue when I tried to compile [nix](https://github.com/nix-rust/nix).

# Steps to reproduce

1. `git clone https://github.com/nix-rust/nix.git`
1. `cd nix`
1. `cargo build`

# Results 
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
error: Could not compile `nix`.
```

https://github.com/nix-rust/nix/issues/339 was filed to track it. With @pnkfelix 's help, I got [some debug traces](https://gist.github.com/JohanLorenzo/18826350c7a2a9fe7156c196e26dfae0#file-nix_compile_debug-log). However, it didn't really help knowing which function of nix was impacted. 

# Regression window 
[A bisection](https://gist.github.com/JohanLorenzo/18826350c7a2a9fe7156c196e26dfae0#file-bisect-log) narrowed down the issue to #32080, and more precisely [these commits](https://github.com/rust-lang/rust/compare/b918e37eb3e393c5a5b0408430e146c0b66ec7ed...da66431d06b961efd323f25978964df54d44d3c4). I have not been able to bisect down further, because none of these commits compile on my machine.

# Investigation
In the meantime, @pnkfelix found the function likely impacted. You can see the results of [his investigation](https://github.com/nix-rust/nix/issues/339#issuecomment-205407123).

@eddyb, what information would you think we need to isolate the problem?

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #32740 by checking for a declaration before attempting a new one.
Before, `LLVMGetOrInsertFunction` was called for a existing import, but with a different type.
The returned value was a cast function pointer instead of a declaration, and we gave this
value to `llvm::SetFunctionCallConv` & friends , which triggered an LLVM assertion.

### CODE REVIEW

File: src/librustc_trans/declare.rs [hunk 1]
```diff
@@ -158,15 +158,22 @@ pub fn get_defined_value(ccx: &CrateContext, name: &str) -> Option<ValueRef> {
         debug!("get_defined_value: {:?} value is null", name);
         None
```
Comment (dotdash) [inline src/librustc_trans/declare.rs]: Should say `get_declared_value`

File: src/librustc_trans/declare.rs [hunk 2]
```diff
@@ -158,15 +158,22 @@ pub fn get_defined_value(ccx: &CrateContext, name: &str) -> Option<ValueRef> {
...
     } else {
+        debug!("get_defined_value: {:?} => {:?}", name, Value(val));
```
Comment (dotdash) [inline src/librustc_trans/declare.rs]: Should say `get_declared_value`

**Comment by eddyb** [comment]
Added the testcase to an existing duplicated FFI import test and confirmed that the snapshot compiler segfaults (because it has LLVM assertions turned off) and an older stage2 build I had laying around triggers the LLVM assertion, while stage1 passes the test.

**Comment by dotdash** [comment]
@bors p=1

Probably unblocks servo/servo#10173

**Comment by JohanLorenzo** [comment]
I confirm that I don't get the [compilation error](32740) anymore, with this patch. Thanks @eddyb :smiley:

**Comment by Manishearth** [comment]
@bors-servo p=20

rollum shmollup this is more important
