### PR TITLE
Ensure copy* intrinsics also perform the static self-init checks

### LINKED ISSUE #142532: std::ptr::copy() can read from uninitialized statics (unsound)
It is possible to create references to statics while you're still initializing it. Normally, attempting to read from such a reference will cause a compile-time error, with the message "encountered static that tried to initialize itself with itself". However, reading from such a reference with `std::ptr::copy()` does not cause this error. For example:

```rust
use std::mem::MaybeUninit;

pub static X: (i32, MaybeUninit<i32>) = (1, foo(&X.0));

const fn foo(x: &i32) -> MaybeUninit<i32> {
    let mut temp = MaybeUninit::<i32>::uninit();
    unsafe {
        std::ptr::copy(x, temp.as_mut_ptr(), 1);
    }
    temp
}
```

This code compiles fine, and leaves `X.1` as an uninitialized value.

This can cause supposedly-sound API using unsafe code to become unsound. For example:

<details>
<summary>Example unsoundness</summary>

```rust
mod module {
    use std::mem::MaybeUninit;
    
    // SAFETY invariant: The MaybeUninit is always initialized
    pub struct YesInit(MaybeUninit<i32>);
    
    impl YesInit {
        pub const fn new(x: &i32) -> Self {
            let ptr = &raw const *x;
            let mut temp = MaybeUninit::<i32>::uninit();
            unsafe {
                // SAFETY: We're reading from a reference into a local variable.
                // So, both pointers are valid.
                std::ptr::copy(ptr, temp.as_mut_ptr(), 1);
            }
            // SAFETY: We just initialized it from a reference, which must be initialized
            Self(temp)
        }
        
        pub fn to_inner(&self) -> i32 {
            unsafe {
                // SAFETY: Guaranteed by safety invariant
                self.0.assume_init()
            }
        }
    }
}

use module::YesInit;

static X: (i32, YesInit) = (1, YesInit::new(&X.0));

fn main() {
    println!("{}", X.1.to_inner());
}
```

</details>

In this code, the `YesInit` type exposes an API that I think should be sound. However, the weirdness with `std::ptr::copy` means that this API can be used to cause undefined behavior. Running this code with Miri reports: "error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory".

See also #142404 for shenanigans with uninitialized statics.

### Meta

Reproducible on the playground with `1.89.0-nightly (2025-06-11 e703dff8fe220b78195c)`

@rustbot labels +I-unsound +A-const-eval

### PR DESCRIPTION
**Pull request by oli-obk**
fixes rust-lang/rust#142532

r? @RalfJung

### CODE REVIEW

**Comment by oli-obk** [comment]
Adding relnotes as this will break stable code if someone wrote such code in the last year, but there is absolutely no reason to do so, so not even gonna crater it.

**Comment by workingjubilee** [comment]
It's a soundness fix and is only reachable by having incorrect unsafe code that should be rejected by const eval anyway, right? Then we're justified in "break first, figure out how to migrate smoothly later".

**Comment by theemathas** [comment]
In theory, this could also affect code where there's correct unsafe code in one crate, and there's incorrect safe code in another crate misusing the first crate.

File: compiler/rustc_const_eval/src/interpret/memory.rs [hunk 1]
```diff
@@ -1401,6 +1401,11 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
         let src_parts = self.get_ptr_access(src, size)?;
         let dest_parts = self.get_ptr_access(dest, size * num_copies)?; // `Size` multiplication
 
+        // And our own "do not read from static items while initializing them" checks
+        if let Ok((alloc_id, ..)) = self.ptr_try_get_alloc_id(src, size.bytes() as i64) {
+            M::before_alloc_read(self, alloc_id)?;
+        }
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/memory.rs]: Is it possible to move this to right before the `before_memory_read` below so that we handle both hooks together?

File: tests/ui/statics/read_before_init.rs
Comment (RalfJung) [inline tests/ui/statics/read_before_init.rs:1]: Please add a comment explaining what this is testing and referencing the issue.

File: compiler/rustc_const_eval/src/interpret/memory.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/memory.rs]: jup, works just fine

File: compiler/rustc_const_eval/src/interpret/memory.rs [hunk 2]
```diff
@@ -1412,6 +1412,12 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
         let src_range = alloc_range(src_offset, size);
         assert!(!self.memory.validation_in_progress.get(), "we can't be copying during validation");
+
+        // Do our own "do not read from static items while initializing them" checks
+        if let Ok((alloc_id, ..)) = self.ptr_try_get_alloc_id(src, size.bytes() as i64) {
+            M::before_alloc_read(self, alloc_id)?;
+        }
+
         // For the overlapping case, it is crucial that we trigger the read hook
         // before the write hook -- the aliasing model cares about the order.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/memory.rs]:
```suggestion
        // Trigger read hooks.
        // For the overlapping case, it is crucial that we trigger the read hooks
        // before the write hook -- the aliasing model cares about the order.
        if let Ok((alloc_id, ..)) = self.ptr_try_get_alloc_id(src, size.bytes() as i64) {
            M::before_alloc_read(self, alloc_id)?;
        }
```
The core interpreter doesn't know what the hook does, so it seems odd to refer to to the static item recursion check.

**Review by RalfJung — COMMENTED** [review]
r=me with comment tweaks
