### PR TITLE
Remove existing AFIDT implementation

### LINKED ISSUE #136286: ICE: `expected async fn in trait to return an RPITIT`
snippet:
````rust
//@compile-flags: --edition=2024
#![feature(async_fn_in_dyn_trait)]
trait A {
    async fn b(self: A);
}

````

Version information
````
rustc 1.86.0-nightly (e6f12c8b7 2025-01-30)
binary: rustc
commit-hash: e6f12c8b7d8d5c821c32fb2739ea01d1d874c58a
commit-date: 2025-01-30
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/e6f12c8b7d8d5c821c32fb2739ea01d1d874c58a/compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs#L907-L919

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `async_fn_in_dyn_trait` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.7pZXHQ7HZKbf/rustc_testrunner_tmpdir_reporting.rOKT2kZqYC9F/mvce.rs:1:12
  |
1 | #![feature(async_fn_in_dyn_trait)]
  |            ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #133119 <https://github.com/rust-lang/rust/issues/133119> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.7pZXHQ7HZKbf/rustc_testrunner_tmpdir_reporting.rOKT2kZqYC9F/mvce.rs:4:2
  |
4 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.7pZXHQ7HZKbf/rustc_testrunner_tmpdir_reporting.rOKT2kZqYC9F/mvce.rs`

error: internal compiler error: compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs:913:17: expected async fn in trait to return an RPITIT


thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs:913:17:
Box<dyn Any>
stack backtrace:
   0:     0x7b4b4522d410 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h32b76eca82481332
   1:     0x7b4b45a138e6 - core::fmt::write::h6aab99975a3e1e0d
   2:     0x7b4b46904bd1 - std::io::Write::write_fmt::h07e3041152301b92
   3:     0x7b4b4522d272 - std::sys::backtrace::BacktraceLock::print::h11198f536c423f0e
   4:     0x7b4b4522f6f2 - std::panicking::default_hook::{{closure}}::hedf2549fe54c612d
   5:     0x7b4b4522f57a - std::panicking::default_hook::h5cafcda49fcb475d
   6:     0x7b4b44389e99 - std[65c60797a113df8d]::panicking::update_hook::<alloc[26d4a3e3ec5433a5]::boxed::Box<rustc_driver_impl[88e265ae9927f55c]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7b4b45230273 - std::panicking::rust_panic_with_hook::h9e0ce671ec08e8dc
   8:     0x7b4b443c4c21 - std[65c60797a113df8d]::panicking::begin_panic::<rustc_errors[23526cdfd16e48c4]::ExplicitBug>::{closure#0}
   9:     0x7b4b443b9b26 - std[65c60797a113df8d]::sys::backtrace::__rust_end_short_backtrace::<std[65c60797a113df8d]::panicking::begin_panic<rustc_errors[23526cdfd16e48c4]::ExplicitBug>::{closure#0}, !>
  10:     0x7b4b443b67ed - std[65c60797a113df8d]::panicking::begin_panic::<rustc_errors[23526cdfd16e48c4]::ExplicitBug>
  11:     0x7b4b443ceb71 - <rustc_errors[23526cdfd16e48c4]::diagnostic::BugAbort as rustc_errors[23526cdfd16e48c4]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7b4b449b1ba3 - rustc_middle[c95cf357e72e9a85]::util::bug::opt_span_bug_fmt::<rustc_span[cb34d841a75ac9bc]::span_encoding::Span>::{closure#0}
  13:     0x7b4b4499ab0a - rustc_middle[c95cf357e72e9a85]::ty::context::tls::with_opt::<rustc_middle[c95cf357e72e9a85]::util::bug::opt_span_bug_fmt<rustc_span[cb34d841a75ac9bc]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7b4b4499a99b - rustc_middle[c95cf357e72e9a85]::ty::context::tls::with_context_opt::<rustc_middle[c95cf357e72e9a85]::ty::context::tls::with_opt<rustc_middle[c95cf357e72e9a85]::util::bug::opt_span_bug_fmt<rustc_span[cb34d841a75ac9bc]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7b4b42c3df80 - rustc_middle[c95cf357e72e9a85]::util::bug::bug_fmt
  16:     0x7b4b46556623 - rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::virtual_call_violations_for_method
  17:     0x7b4b45fef6ed - rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::dyn_compatibility_violations_for_assoc_item
  18:     0x7b4b45fef590 - <core[b38de05c6bab522f]::iter::adapters::flatten::FlatMap<core[b38de05c6bab522f]::iter::adapters::map::Map<core[b38de05c6bab522f]::iter::adapters::map::Map<core[b38de05c6bab522f]::slice::iter::Iter<(rustc_span[cb34d841a75ac9bc]::symbol::Symbol, rustc_middle[c95cf357e72e9a85]::ty::assoc::AssocItem)>, <rustc_data_structures[9c6ee9e9e5334c83]::sorted_map::index_map::SortedIndexMultiMap<u32, rustc_span[cb34d841a75ac9bc]::symbol::Symbol, rustc_middle[c95cf357e72e9a85]::ty::assoc::AssocItem>>::iter::{closure#0}>, <rustc_middle[c95cf357e72e9a85]::ty::assoc::AssocItems>::in_definition_order::{closure#0}>, alloc[26d4a3e3ec5433a5]::vec::Vec<rustc_middle[c95cf357e72e9a85]::traits::DynCompatibilityViolation>, rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::dyn_compatibility_violations_for_trait::{closure#0}::{closure#0}> as core[b38de05c6bab522f]::iter::traits::iterator::Iterator>::next
  19:     0x7b4b46543d60 - <core[b38de05c6bab522f]::iter::adapters::flatten::FlatMap<core[b38de05c6bab522f]::iter::sources::from_fn::FromFn<rustc_type_ir[6a899794ba15143]::elaborate::supertrait_def_ids<rustc_middle[c95cf357e72e9a85]::ty::context::TyCtxt>::{closure#0}>, alloc[26d4a3e3ec5433a5]::vec::Vec<rustc_middle[c95cf357e72e9a85]::traits::DynCompatibilityViolation>, rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::dyn_compatibility_violations::{closure#0}> as core[b38de05c6bab522f]::iter::traits::iterator::Iterator>::next
  20:     0x7b4b46543984 - <core[b38de05c6bab522f]::iter::adapters::flatten::FlatMap<core[b38de05c6bab522f]::iter::sources::from_fn::FromFn<rustc_type_ir[6a899794ba15143]::elaborate::supertrait_def_ids<rustc_middle[c95cf357e72e9a85]::ty::context::TyCtxt>::{closure#0}>, alloc[26d4a3e3ec5433a5]::vec::Vec<rustc_middle[c95cf357e72e9a85]::traits::DynCompatibilityViolation>, rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::dyn_compatibility_violations::{closure#0}> as core[b38de05c6bab522f]::iter::traits::iterator::Iterator>::collect::<smallvec[ec8755ed03ba0f13]::SmallVec<[rustc_middle[c95cf357e72e9a85]::traits::DynCompatibilityViolation; 8usize]>>
  21:     0x7b4b465434dd - rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::dyn_compatibility_violations
  22:     0x7b4b465433e2 - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::dyn_compatibility_violations::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 16usize]>>
  23:     0x7b4b465433c9 - <rustc_query_impl[a79c5430108c0b60]::query_impl::dyn_compatibility_violations::dynamic_query::{closure#2} as core[b38de05c6bab522f]::ops::function::FnOnce<(rustc_middle[c95cf357e72e9a85]::ty::context::TyCtxt, rustc_span[cb34d841a75ac9bc]::def_id::DefId)>>::call_once
  24:     0x7b4b45e8840a - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  25:     0x7b4b45ff1338 - rustc_query_impl[a79c5430108c0b60]::query_impl::dyn_compatibility_violations::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7b4b45ff162f - rustc_middle[c95cf357e72e9a85]::query::plumbing::query_get_at::<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 16usize]>>>
  27:     0x7b4b45ff1427 - rustc_trait_selection[d3a832fb8e061b24]::traits::dyn_compatibility::is_dyn_compatible
  28:     0x7b4b45ff13e9 - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::is_dyn_compatible::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7b4b45d6c3eb - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  30:     0x7b4b4630eca6 - rustc_query_impl[a79c5430108c0b60]::query_impl::is_dyn_compatible::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7b4b463b7200 - rustc_middle[c95cf357e72e9a85]::query::plumbing::query_get_at::<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>>
  32:     0x7b4b46b1cd85 - <dyn rustc_hir_analysis[52c5e5868dd20650]::hir_ty_lowering::HirTyLowerer>::prohibit_or_lint_bare_trait_object_ty
  33:     0x7b4b4634256f - <dyn rustc_hir_analysis[52c5e5868dd20650]::hir_ty_lowering::HirTyLowerer>::lower_ty
  34:     0x7b4b46339e7e - <dyn rustc_hir_analysis[52c5e5868dd20650]::hir_ty_lowering::HirTyLowerer>::lower_fn_ty
  35:     0x7b4b4634f4a0 - rustc_hir_analysis[52c5e5868dd20650]::collect::fn_sig
  36:     0x7b4b45cb60ed - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 24usize]>>
  37:     0x7b4b45cb60ad - <rustc_query_impl[a79c5430108c0b60]::query_impl::fn_sig::dynamic_query::{closure#2} as core[b38de05c6bab522f]::ops::function::FnOnce<(rustc_middle[c95cf357e72e9a85]::ty::context::TyCtxt, rustc_span[cb34d841a75ac9bc]::def_id::DefId)>>::call_once
  38:     0x7b4b45cb8f87 - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  39:     0x7b4b45cb85e2 - rustc_query_impl[a79c5430108c0b60]::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7b4b460794bc - rustc_middle[c95cf357e72e9a85]::query::plumbing::query_get_at::<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefIdCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 24usize]>>>
  41:     0x7b4b46a38049 - rustc_hir_analysis[52c5e5868dd20650]::check::check::check_item_type
  42:     0x7b4b460655c6 - rustc_hir_analysis[52c5e5868dd20650]::check::wfcheck::check_well_formed
  43:     0x7b4b46064187 - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7b4b46063c29 - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_data_structures[9c6ee9e9e5334c83]::vec_cache::VecCache<rustc_span[cb34d841a75ac9bc]::def_id::LocalDefId, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[ff51b95ecba2cb21]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  45:     0x7b4b46063686 - rustc_query_impl[a79c5430108c0b60]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7b4b460612ac - rustc_hir_analysis[52c5e5868dd20650]::check::wfcheck::check_mod_type_wf
  47:     0x7b4b460610cb - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>
  48:     0x7b4b46985948 - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_query_system[ff51b95ecba2cb21]::query::caches::DefaultCache<rustc_span[cb34d841a75ac9bc]::def_id::LocalModDefId, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  49:     0x7b4b469856f0 - rustc_query_impl[a79c5430108c0b60]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  50:     0x7b4b45da10e6 - rustc_hir_analysis[52c5e5868dd20650]::check_crate
  51:     0x7b4b45d9dc64 - rustc_interface[3e4af95fb941106a]::passes::run_required_analyses
  52:     0x7b4b469002de - rustc_interface[3e4af95fb941106a]::passes::analysis
  53:     0x7b4b469002af - rustc_query_impl[a79c5430108c0b60]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a79c5430108c0b60]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 0usize]>>
  54:     0x7b4b468ec015 - rustc_query_system[ff51b95ecba2cb21]::query::plumbing::try_execute_query::<rustc_query_impl[a79c5430108c0b60]::DynamicConfig<rustc_query_system[ff51b95ecba2cb21]::query::caches::SingleCache<rustc_middle[c95cf357e72e9a85]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[a79c5430108c0b60]::plumbing::QueryCtxt, false>
  55:     0x7b4b468ebd4e - rustc_query_impl[a79c5430108c0b60]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  56:     0x7b4b46a0be69 - rustc_interface[3e4af95fb941106a]::passes::create_and_enter_global_ctxt::<core[b38de05c6bab522f]::option::Option<rustc_interface[3e4af95fb941106a]::queries::Linker>, rustc_driver_impl[88e265ae9927f55c]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  57:     0x7b4b4695a498 - rustc_interface[3e4af95fb941106a]::interface::run_compiler::<(), rustc_driver_impl[88e265ae9927f55c]::run_compiler::{closure#0}>::{closure#1}
  58:     0x7b4b46875f35 - std[65c60797a113df8d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3e4af95fb941106a]::util::run_in_thread_with_globals<rustc_interface[3e4af95fb941106a]::util::run_in_thread_pool_with_globals<rustc_interface[3e4af95fb941106a]::interface::run_compiler<(), rustc_driver_impl[88e265ae9927f55c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  59:     0x7b4b46875c19 - <<std[65c60797a113df8d]::thread::Builder>::spawn_unchecked_<rustc_interface[3e4af95fb941106a]::util::run_in_thread_with_globals<rustc_interface[3e4af95fb941106a]::util::run_in_thread_pool_with_globals<rustc_interface[3e4af95fb941106a]::interface::run_compiler<(), rustc_driver_impl[88e265ae9927f55c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[b38de05c6bab522f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  60:     0x7b4b468753ab - std::sys::pal::unix::thread::Thread::new::thread_start::h7b9c2e4fdae6f3c1
  61:     0x7b4b40aa339d - <unknown>
  62:     0x7b4b40b2849c - <unknown>
  63:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (e6f12c8b7 2025-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [dyn_compatibility_violations] determining dyn-compatibility of trait `A`
#1 [is_dyn_compatible] checking if trait `A` is dyn-compatible
#2 [fn_sig] computing function signature of `A::b`
#3 [check_well_formed] checking that `A` is well-formed
#4 [check_mod_type_wf] checking that types are well-formed in top-level module
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-async_fn_in_dyn_trait

### LINKED ISSUE #137706: ICE: expected binder to have 2 projections, but it has 1
auto-reduced (treereduce-rust):
````rust
trait A {
    fn b() -> impl IntoIterator<Item = ()>;
}

impl A<()> for dyn A {}

````

original:
````rust
trait A {
    fn b() -> impl IntoIterator<Item = ()>;
}

impl A<()> for dyn A {}

pub fn main() {}

````

Version information
````
rustc 1.87.0-dev
binary: rustc
commit-hash: 85abb276361c424d64743c0965242dd0e7b866d1
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.87.0-dev
LLVM version: 20.1.0

````

### LINKED ISSUE #137895: ICE: `assertion failed: !eps.is_empty()`
snippet:
````rust
trait A {
    fn b() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
}

impl A<()> for dyn A {}

````

Version information
````
rustc 1.87.0-nightly (7c4a55c2a 2025-03-02)
binary: rustc
commit-hash: 7c4a55c2ac6497629c273ccd00e185583542f0d2
commit-date: 2025-03-02
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/7c4a55c2ac6497629c273ccd00e185583542f0d2/compiler/rustc_middle/src/ty/context.rs#L2836-L2848

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0261]: use of undeclared lifetime name `'a`
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:2:33
  |
2 |     fn b() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
  |                                 ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
2 |     fn b() -> impl for<'a> IntoIterator<'a, Out = impl ?Sized + 'a>;
  |                    +++++++
help: consider introducing lifetime `'a` here
  |
2 |     fn b<'a>() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
  |         ++++
help: consider introducing lifetime `'a` here
  |
1 | trait A<'a> {
  |        ++++

error[E0261]: use of undeclared lifetime name `'a`
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:2:57
  |
2 |     fn b() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
  |                                                         ^^ undeclared lifetime
  |
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
2 |     fn b() -> impl for<'a> IntoIterator<'a, Out = impl ?Sized + 'a>;
  |                    +++++++
help: consider introducing lifetime `'a` here
  |
2 |     fn b<'a>() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
  |         ++++
help: consider introducing lifetime `'a` here
  |
1 | trait A<'a> {
  |        ++++

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:5:24
  |
5 | impl A<()> for dyn A {}
  |                        ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs`

error[E0107]: trait takes 0 generic arguments but 1 generic argument was supplied
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:5:6
  |
5 | impl A<()> for dyn A {}
  |      ^---- help: remove the unnecessary generics
  |      |
  |      expected 0 generic arguments
  |
note: trait defined here, with 0 generic parameters
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:1:7
  |
1 | trait A {
  |       ^

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:2:20
    |
2   |     fn b() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
    |                    ^^^^^^^^^^^^---------------------------- help: remove the unnecessary generics
    |                    |
    |                    expected 0 lifetime arguments
    |
note: trait defined here, with 0 lifetime parameters
   --> /home/matthias/.rustup/toolchains/master/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:285:11
    |
285 | pub trait IntoIterator {
    |           ^^^^^^^^^^^^

error[E0220]: associated type `Out` not found for `IntoIterator`
 --> /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:2:37
  |
2 |     fn b() -> impl IntoIterator<'a, Out = impl ?Sized + 'a>;
  |                                     ^^^ associated type `Out` not found


thread 'rustc' panicked at compiler/rustc_middle/src/ty/context.rs:2842:9:
assertion failed: !eps.is_empty()
stack backtrace:
   0:     0x7a4a4b1bef14 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hc495f1899fa849d6
   1:     0x7a4a4ba057e2 - core::fmt::write::h39ac2b6780eacb0b
   2:     0x7a4a4cde5291 - std::io::Write::write_fmt::hce3ca50e4f9c3d70
   3:     0x7a4a4b1bed72 - std::sys::backtrace::BacktraceLock::print::h6721b52240ac06b8
   4:     0x7a4a4b1c1652 - std::panicking::default_hook::{{closure}}::h7fd0541ed74fb3ce
   5:     0x7a4a4b1c1244 - std::panicking::default_hook::hccc7d640d5ba2811
   6:     0x7a4a4a318a87 - std[673d9073d68e8c5f]::panicking::update_hook::<alloc[956ce29f8aa768f9]::boxed::Box<rustc_driver_impl[6af4072765422930]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7a4a4b1c1ec3 - std::panicking::rust_panic_with_hook::h0da458b51069d3a7
   8:     0x7a4a4b1c1b86 - std::panicking::begin_panic_handler::{{closure}}::ha16ec4ccc9cec913
   9:     0x7a4a4b1bf3d9 - std::sys::backtrace::__rust_end_short_backtrace::h2aacb06ecfcbe368
  10:     0x7a4a4b1c187d - rust_begin_unwind
  11:     0x7a4a47e5b930 - core::panicking::panic_fmt::h41765f7bbf5784a9
  12:     0x7a4a488bc44c - core::panicking::panic::h9beefec10d0ae431
  13:     0x7a4a4bb6f565 - <rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>::mk_poly_existential_predicates
  14:     0x7a4a4a92d692 - <rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>::item_bounds_to_existential_predicates
  15:     0x7a4a4bdd09c1 - rustc_trait_selection[7cd3b6c2e2dd783b]::traits::project::opt_normalize_projection_term
  16:     0x7a4a4bdbfd4c - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[7c82fdb37256d6e0]::fold::TypeFolder<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>::fold_ty
  17:     0x7a4a4bdb2e00 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[7c82fdb37256d6e0]::fold::FallibleTypeFolder<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>::try_fold_binder::<rustc_type_ir[7c82fdb37256d6e0]::predicate_kind::PredicateKind<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>
  18:     0x7a4a4bb865f5 - rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::normalize_with_depth_to::<rustc_middle[149f66fe1de159a6]::ty::predicate::Clause>
  19:     0x7a4a4bc0cdf2 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::confirm_candidate
  20:     0x7a4a4c9df13e - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  21:     0x7a4a4bbd0714 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::poly_select::{closure#0}
  22:     0x7a4a4bdc1f95 - rustc_trait_selection[7cd3b6c2e2dd783b]::traits::project::opt_normalize_projection_term
  23:     0x7a4a4bdbfd4c - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[7c82fdb37256d6e0]::fold::TypeFolder<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>::fold_ty
  24:     0x7a4a4bdb2d7e - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[7c82fdb37256d6e0]::fold::FallibleTypeFolder<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>::try_fold_binder::<rustc_type_ir[7c82fdb37256d6e0]::predicate_kind::PredicateKind<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt>>
  25:     0x7a4a4bb865f5 - rustc_trait_selection[7cd3b6c2e2dd783b]::traits::normalize::normalize_with_depth_to::<rustc_middle[149f66fe1de159a6]::ty::predicate::Clause>
  26:     0x7a4a4bc0cdf2 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::confirm_candidate
  27:     0x7a4a4bb7777e - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::evaluate_candidate::{closure#0}::{closure#0}
  28:     0x7a4a4bb84475 - <alloc[956ce29f8aa768f9]::vec::into_iter::IntoIter<rustc_middle[149f66fe1de159a6]::traits::select::SelectionCandidate> as core[fd72b707659d9093]::iter::traits::iterator::Iterator>::try_fold::<(), core[fd72b707659d9093]::iter::adapters::map::map_try_fold<rustc_middle[149f66fe1de159a6]::traits::select::SelectionCandidate, core[fd72b707659d9093]::result::Result<core[fd72b707659d9093]::option::Option<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>, rustc_middle[149f66fe1de159a6]::traits::SelectionError>, (), core[fd72b707659d9093]::ops::control_flow::ControlFlow<core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>>, <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::candidate_from_obligation_no_cache::{closure#1}, core[fd72b707659d9093]::iter::adapters::map::map_try_fold<core[fd72b707659d9093]::result::Result<core[fd72b707659d9093]::option::Option<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>, rustc_middle[149f66fe1de159a6]::traits::SelectionError>, core[fd72b707659d9093]::option::Option<core[fd72b707659d9093]::result::Result<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate, rustc_middle[149f66fe1de159a6]::traits::SelectionError>>, (), core[fd72b707659d9093]::ops::control_flow::ControlFlow<core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>>, <core[fd72b707659d9093]::result::Result<core[fd72b707659d9093]::option::Option<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>, rustc_middle[149f66fe1de159a6]::traits::SelectionError>>::transpose, core[fd72b707659d9093]::iter::adapters::flatten::try_flatten_one<core[fd72b707659d9093]::option::Option<core[fd72b707659d9093]::result::Result<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate, rustc_middle[149f66fe1de159a6]::traits::SelectionError>>, (), core[fd72b707659d9093]::ops::control_flow::ControlFlow<core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>>, <core[fd72b707659d9093]::iter::adapters::GenericShunt<core[fd72b707659d9093]::iter::adapters::flatten::FlatMap<core[fd72b707659d9093]::iter::adapters::map::Map<alloc[956ce29f8aa768f9]::vec::into_iter::IntoIter<rustc_middle[149f66fe1de159a6]::traits::select::SelectionCandidate>, <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::candidate_from_obligation_no_cache::{closure#1}>, core[fd72b707659d9093]::option::Option<core[fd72b707659d9093]::result::Result<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate, rustc_middle[149f66fe1de159a6]::traits::SelectionError>>, <core[fd72b707659d9093]::result::Result<core[fd72b707659d9093]::option::Option<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>, rustc_middle[149f66fe1de159a6]::traits::SelectionError>>::transpose>, core[fd72b707659d9093]::result::Result<core[fd72b707659d9093]::convert::Infallible, rustc_middle[149f66fe1de159a6]::traits::SelectionError>> as core[fd72b707659d9093]::iter::traits::iterator::Iterator>::try_fold<(), core[fd72b707659d9093]::iter::traits::iterator::Iterator::try_for_each::call<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate, core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>, core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>::Break>::{closure#0}, core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>>::{closure#0}>::{closure#0}>::{closure#0}>::{closure#0}, core[fd72b707659d9093]::ops::control_flow::ControlFlow<core[fd72b707659d9093]::ops::control_flow::ControlFlow<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::EvaluatedCandidate>>>
  29:     0x7a4a4bb81eb6 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}
  30:     0x7a4a4bb795b0 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  31:     0x7a4a4bb8b54a - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::select::SelectionContext>::evaluate_root_obligation
  32:     0x7a4a4bb89cfe - rustc_traits[7fff9634386093f8]::evaluate_obligation::evaluate_obligation
  33:     0x7a4a4bb897e9 - rustc_query_impl[ad7e806203de0335]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad7e806203de0335]::query_impl::evaluate_obligation::dynamic_query::{closure#2}::{closure#0}, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 2usize]>>
  34:     0x7a4a4bb88c48 - rustc_query_system[30512ec7f96497de]::query::plumbing::try_execute_query::<rustc_query_impl[ad7e806203de0335]::DynamicConfig<rustc_query_system[30512ec7f96497de]::query::caches::DefaultCache<rustc_type_ir[7c82fdb37256d6e0]::canonical::CanonicalQueryInput<rustc_middle[149f66fe1de159a6]::ty::context::TyCtxt, rustc_middle[149f66fe1de159a6]::ty::ParamEnvAnd<rustc_middle[149f66fe1de159a6]::ty::predicate::Predicate>>, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[ad7e806203de0335]::plumbing::QueryCtxt, false>
  35:     0x7a4a4bb8885e - rustc_query_impl[ad7e806203de0335]::query_impl::evaluate_obligation::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7a4a4c2dad51 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::fulfill::FulfillProcessor as rustc_data_structures[c5d5d3efdb2e4cc2]::obligation_forest::ObligationProcessor>::process_obligation
  37:     0x7a4a4ba074e9 - <rustc_data_structures[c5d5d3efdb2e4cc2]::obligation_forest::ObligationForest<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::fulfill::FulfillProcessor>
  38:     0x7a4a4bea0887 - <rustc_trait_selection[7cd3b6c2e2dd783b]::traits::fulfill::FulfillmentContext<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::FulfillmentError> as rustc_infer[eba90bd19780a5a9]::traits::engine::TraitEngine<rustc_trait_selection[7cd3b6c2e2dd783b]::traits::FulfillmentError>>::select_all_or_error
  39:     0x7a4a4c1fcec3 - rustc_hir_analysis[21d9bf831ff42857]::check::wfcheck::check_well_formed
  40:     0x7a4a4c1fb80d - rustc_query_impl[ad7e806203de0335]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad7e806203de0335]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7a4a4c1fb2c4 - rustc_query_system[30512ec7f96497de]::query::plumbing::try_execute_query::<rustc_query_impl[ad7e806203de0335]::DynamicConfig<rustc_data_structures[c5d5d3efdb2e4cc2]::vec_cache::VecCache<rustc_span[8b0dd42cecff55ed]::def_id::LocalDefId, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[30512ec7f96497de]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[ad7e806203de0335]::plumbing::QueryCtxt, false>
  42:     0x7a4a4c1fad7f - rustc_query_impl[ad7e806203de0335]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7a4a4c1f859d - rustc_hir_analysis[21d9bf831ff42857]::check::wfcheck::check_mod_type_wf
  44:     0x7a4a4c1f839f - rustc_query_impl[ad7e806203de0335]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad7e806203de0335]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7a4a4ca8b896 - rustc_query_system[30512ec7f96497de]::query::plumbing::try_execute_query::<rustc_query_impl[ad7e806203de0335]::DynamicConfig<rustc_query_system[30512ec7f96497de]::query::caches::DefaultCache<rustc_span[8b0dd42cecff55ed]::def_id::LocalModDefId, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ad7e806203de0335]::plumbing::QueryCtxt, false>
  46:     0x7a4a4ca8b63f - rustc_query_impl[ad7e806203de0335]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7a4a4bdf9f8f - rustc_hir_analysis[21d9bf831ff42857]::check_crate
  48:     0x7a4a4bdf3c9c - rustc_interface[d8c24ebf2384fa83]::passes::run_required_analyses
  49:     0x7a4a4c93efba - rustc_interface[d8c24ebf2384fa83]::passes::analysis
  50:     0x7a4a4c93ef99 - rustc_query_impl[ad7e806203de0335]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad7e806203de0335]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 0usize]>>
  51:     0x7a4a4caabf8b - rustc_query_system[30512ec7f96497de]::query::plumbing::try_execute_query::<rustc_query_impl[ad7e806203de0335]::DynamicConfig<rustc_query_system[30512ec7f96497de]::query::caches::SingleCache<rustc_middle[149f66fe1de159a6]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ad7e806203de0335]::plumbing::QueryCtxt, false>
  52:     0x7a4a4caabc79 - rustc_query_impl[ad7e806203de0335]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  53:     0x7a4a4c972efd - rustc_interface[d8c24ebf2384fa83]::passes::create_and_enter_global_ctxt::<core[fd72b707659d9093]::option::Option<rustc_interface[d8c24ebf2384fa83]::queries::Linker>, rustc_driver_impl[6af4072765422930]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  54:     0x7a4a4cb11220 - rustc_interface[d8c24ebf2384fa83]::interface::run_compiler::<(), rustc_driver_impl[6af4072765422930]::run_compiler::{closure#0}>::{closure#1}
  55:     0x7a4a4c953cc8 - std[673d9073d68e8c5f]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d8c24ebf2384fa83]::util::run_in_thread_with_globals<rustc_interface[d8c24ebf2384fa83]::util::run_in_thread_pool_with_globals<rustc_interface[d8c24ebf2384fa83]::interface::run_compiler<(), rustc_driver_impl[6af4072765422930]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  56:     0x7a4a4c9545b4 - <<std[673d9073d68e8c5f]::thread::Builder>::spawn_unchecked_<rustc_interface[d8c24ebf2384fa83]::util::run_in_thread_with_globals<rustc_interface[d8c24ebf2384fa83]::util::run_in_thread_pool_with_globals<rustc_interface[d8c24ebf2384fa83]::interface::run_compiler<(), rustc_driver_impl[6af4072765422930]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[fd72b707659d9093]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  57:     0x7a4a4c9559b7 - std::sys::pal::unix::thread::Thread::new::thread_start::hb86ea38ca4860a5f
  58:     0x7a4a46aa370a - <unknown>
  59:     0x7a4a46b27aac - <unknown>
  60:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (7c4a55c2a 2025-03-02) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `(dyn A + 'a): A`
#1 [check_well_formed] checking that `<impl at /tmp/icemaker_global_tempdir.5tICGURnV2T4/rustc_testrunner_tmpdir_reporting.9pGZJg4ZyXaF/mvce.rs:5:1: 5:21>` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors

Some errors have detailed explanations: E0107, E0220, E0261, E0601.
For more information about an error, try `rustc --explain E0107`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
This experiment will need to be reworked differently; I don't think we'll be going with the `dyn* Future` approach that is currently implemented.

r? oli-obk

Fixes #136286 
Fixes #137706 
Fixes #137895

Tracking:
* #133119

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_compatibility.rs [hunk 1]
```diff
@@ -176,7 +176,7 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                                 .in_definition_order()
                                 // We only care about associated types.
                                 .filter(|item| item.kind == ty::AssocKind::Type)
-                                // No RPITITs -- even with `async_fn_in_dyn_trait`, they are implicit.
+                                // No RPITITs -- they're not dyn-compatible for nwo.
```
Comment (fbstj) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/dyn_compatibility.rs:179]: typo
```suggestion
                                // No RPITITs -- they're not dyn-compatible for now.
```

**Comment by Kobzol** [comment]
@rust-timer build 130a33ab8fd3d91728da6ef74c691ab69c22880e
