### PR TITLE
Avoid ICE when include! is used by stdin crate

### LINKED ISSUE #63900: ICE having include! in code from stdin when calling rustc
to reproduce the fault this can be used: 
`echo 'include!("auxiliary/empty.rs"); pub fn main(){}' | rustc - `

will result in this ICE:

`thread 'rustc' panicked at 'cannot resolve relative path in non-file source ', src/libsyntax/ext/source_util.rs:189:22 note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.36.0 (a53f9df 2019-07-03) running on x86_64-unknown-linux-gnu`

the question is what is the path that shall be used when the code is from stdin maybe some temp file name in the currrent working dir.

### PR DESCRIPTION
**Pull request by mystor**
This should hopefully also eliminate the ICE when using `include_bytes!`, `include_str!` and `#[doc(include = "...")]` with a stdio input.

I couldn't see a clear way to write a compile-fail test using compiletest with a stdio input, so I haven't written any tests for this change.

Fixes #63900

### CODE REVIEW

File: src/libsyntax_expand/base.rs [hunk 1]
```diff
@@ -1072,7 +1072,8 @@ impl<'a> ExtCtxt<'a> {
     /// This unifies the logic used for resolving `include_X!`, and `#[doc(include)]` file paths.
     ///
     /// Returns an absolute path to the file that `path` refers to.
-    pub fn resolve_path(&self, path: impl Into<PathBuf>, span: Span) -> PathBuf {
+    pub fn resolve_path(&self, path: impl Into<PathBuf>, span: Span)
+                        -> Result<PathBuf, DiagnosticBuilder<'a>> {
```
Comment (Centril) [inline src/libsyntax_expand/base.rs]: Please use the same formatting as the method below.

Comment (mystor) [reply src/libsyntax_expand/base.rs]: OK. Wasn't sure what style to use, so copied from this method: https://github.com/rust-lang/rust/blob/0b97ef8d5f78ea7144dbc2afb0ff3e055fb5056a/src/libsyntax_expand/base.rs#L1126-L1127
