### PR TITLE
Impls and impl items inherit `dead_code` lint level of the corresponding traits and trait items

### LINKED ISSUE #144060: Lint regression: `dead_code` ignores `#[allow(dead_code)]` on traits
### Code

```rust
#[allow(dead_code)]
trait Foo {
    const FOO: u32;
}

impl Foo for u32 {
    const FOO: u32 = roundtrip(0);
}

const fn roundtrip(x: u32) -> u32 {
    x
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=1991c4121122ea00f92d73867bb5f048

### Current output

```text
warning: function `roundtrip` is never used
  --> src/lib.rs:10:10
   |
10 | const fn roundtrip(x: u32) -> u32 {
   |          ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

### Desired output

No lint

### Rationale and extra context

`roundtrip` is used in an instance of `trait Foo` so it isn't dead. `Foo` isn't used, but with it being `allow`ed I don't think the check should propagate back elsewhere.

E.g. `bar` doesn't get a lint in this case:

```rust
#[allow(dead_code)]
const X: u32 = bar(0);

const fn bar(x: u32) -> u32 {
    x
}
```

This regressed in https://github.com/rust-lang/rust/pull/143519, cc @mu001999

### Rust Version

searched nightlies: from nightly-2025-05-31 to nightly-2025-07-15
regressed nightly: nightly-2025-07-14
searched commit range: https://github.com/rust-lang/rust/compare/bfc046a4b8d6b57db02540182466e989a9b0fb40...e9182f195b8505c87c4bd055b9f6e114ccda0981
regressed commit: https://github.com/rust-lang/rust/commit/56835d7ac14da9f966e1ff39fd9ffd2e29b764d1

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.10</summary>

Host triple: aarch64-apple-darwin
Reproduce with:

cargo bisect-rustc --start 2025-05-31 --end 2025-07-15 --without-cargo --script=rustc -- a.rs

</details>

### PR DESCRIPTION
**Pull request by mu001999**
https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/dead.rs#L360-L361 won't insert assoc items into the live set, so that impl items cannot be marked live.

This PR lets impls and impl items can inherit lint levels of the corresponding traits and trait items.

Fixes rust-lang/rust#144060

r? @petrochenkov

### CODE REVIEW

File: tests/ui/lint/dead-code/allow-unused-trait.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+#![deny(dead_code)]
+
+#[allow(dead_code)]
+trait Foo {
+    const FOO: u32;
+}
+
+impl Foo for u32 {
+    const FOO: u32 = bar(0);
```
Comment (compiler-errors) [inline tests/ui/lint/dead-code/allow-unused-trait.rs:21]: This test should probably also demonstrate the analogous behavior for `fn` items. And do we lint for unused structs in associated items?

**Review by compiler-errors — COMMENTED** [review]
This behavior seems really non-local and pretty broad. `#[allow(dead_code)]` on a trait definition suppresses all dead code warnings in all impls with this change?

**Comment by mu001999** [comment]
> #[allow(dead_code)] on a trait definition suppresses all dead code warnings in all impls with this change?

@compiler-errors yes, and I think this makes sense. We would have only one trait definition but many impls, letting `#[allow(dead_code)]` on traits propagate to impls is convenient. Otherwise we need to add `#[allow(dead_code)]` also on each impls which use unused items.

**Comment by petrochenkov** [comment]
Hmm, why did rustbot assign it to me again?
I'll just block this on https://github.com/rust-lang/rust/pull/144863 now.
@rustbot blocked

**Comment by mu001999** [comment]
> Hmm, why did rustbot assign it to me again?

I tried reassigning, but rustbot didn’t respond after waiting a while, so I deleted the comment. 😂

**Comment by mu001999** [comment]
> How does what's proposed in this PR compare with @nikomatsakis' model in [#144060 (comment)](https://github.com/rust-lang/rust/issues/144060#issuecomment-3356966585)?

For examples given by @nikomatsakis:

```rust
pub trait Foo { }
impl Foo for u32 { }

struct PrivateType;
impl Foo for PrivateType { } // <-- warns as dead, even though Foo is public

struct AnotherPrivateType;
impl Foo for AnotherPrivateType; { } // <-- warns as dead, even though Foo is public
```
works like before.

```rust
#[allow(dead_code)]
pub trait Foo { }
impl Foo for u32 { }

struct PrivateType;
impl Foo for PrivateType { } // <-- no warning, trait is "allowed"

struct AnotherPrivateType;
impl Foo for AnotherPrivateType; { } // <-- no warning, trait is "allowed"
```
This one is related to this PR. And it will work as expected after this PR.

```rust
pub trait Foo { }
impl Foo for u32 { }

struct PrivateType;
#[allow(dead_code)]
impl Foo for PrivateType { } // <-- no warning, impl is allowed

struct AnotherPrivateType;
impl Foo for AnotherPrivateType; { } // <-- warns as dead, even though Foo is public
```
works like before.

**Comment by traviscross** [comment]
Thanks.  OK.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

Nice work @mu001999 !

**Comment by mu001999** [comment]
@wesleywiser I think the lable `S-blocked` can be removed now, right?

**Comment by tgross35** [comment]
> @wesleywiser I think the lable `S-blocked` can be removed now, right?
>
> And friendly ping @cjgillot

Fyi you can use `@rustbot label -S-blocked` to adjust labels yourself. `@rustbot reroll` allows you to ask for a new reviewer given it's been a while (but give Camille another week or two since they self-assigned and I just adjusted the labels now.)

**Comment by wesleywiser** [comment]
r? compiler
