### PR TITLE
Rebased: Mark drop calls in landing pads cold instead of noinline

### LINKED ISSUE #46515: Missing optimization around __rust_alloc and unknown functions if panic=unwind
The following code gets optimized as expected:
```rust
pub fn test() -> bool {
    let x = &*Box::new(0);
    let y = &*Box::new(0);
    
    if x as *const _ == y as *const _ {
        return true;
    }
    return false;
}
```
[becomes](https://godbolt.org/g/fkwdR5)
```
; example::test
; Function Attrs: nounwind uwtable
define zeroext i1 @example::test() unnamed_addr #0 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality !dbg !18 {
  ret i1 false, !dbg !22
}
```

However, if I let the code call an unknown function instead of return, the optimization disappears:
```rust
pub fn test(f: fn()) {
    let x = &*Box::new(0);
    let y = &*Box::new(0);
    
    if x as *const _ == y as *const _ {
        f();
    }
}

```
[becomes](https://godbolt.org/g/y5acAz)
```
; example::test
; Function Attrs: uwtable
define void @example::test(void ()* nocapture nonnull %f) unnamed_addr #1 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality !dbg !36 {
  %err.i.i.i10 = alloca %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", align 8
  %_5.i.i.i.i11 = alloca %"alloc::allocator::AllocErr", align 8
  %err.i.i.i = alloca %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", align 8
  %_5.i.i.i.i = alloca %"alloc::allocator::AllocErr", align 8
  %_9.sroa.9.i.i = alloca [16 x i8], align 8
  %_9.sroa.9.0.sroa_idx9.i.i = getelementptr inbounds [16 x i8], [16 x i8]* %_9.sroa.9.i.i, i64 0, i64 0, !dbg !38
  call void @llvm.lifetime.start(i64 16, i8* nonnull %_9.sroa.9.0.sroa_idx9.i.i), !dbg !38
  %0 = getelementptr inbounds %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>"* %err.i.i.i, i64 0, i32 0, i64 0, !dbg !48
  call void @llvm.lifetime.start(i64 24, i8* nonnull %0) #6, !dbg !48, !noalias !52
  %1 = call i8* @__rust_alloc(i64 4, i64 4, i8* nonnull %0) #6, !dbg !55, !noalias !52
  %2 = icmp eq i8* %1, null, !dbg !57
  br i1 %2, label %bb3.i.i.i, label %"_ZN35_$LT$alloc..boxed..Box$LT$T$GT$$GT$3new17he6f20be442f24a38E.exit", !dbg !61

[snip]
```

That seems wrong, why should the optimization stop kicking in? The corresponding C++ code does not have any problem:
```C++
#include <memory>

void test(void (*f)()) {
    auto x = std::make_unique<int>(0);
    auto y = std::make_unique<int>(0);

    if (&*x == &*y) {
        f();
    }
}
```
[becomes](https://godbolt.org/g/NqnDcd)
```
; Function Attrs: uwtable
define void @test(void (*)())(void ()* nocapture) local_unnamed_addr #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) !dbg !1204 {
  tail call void @llvm.dbg.value(metadata void ()* %0, i64 0, metadata !1208, metadata !1211), !dbg !1212
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1210, metadata !1213), !dbg !1215
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1210, metadata !1213), !dbg !1215
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  ret void, !dbg !1216
}
```
(I briefly thought maybe unwinding is the problem, but C++ should have the same kind of unwinding here.)

### LINKED ISSUE #87055: Unable to optimize out branches in drop function in unwind landing pad
In [this code](https://godbolt.org/z/4Wrsb4z5f):
```rust
pub fn foo(g: fn()) {
    let _var: Option<Box<i32>> = None;
    g();
}
```

Assembly:
```asm
core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<i32>>>:
        mov     rdi, qword ptr [rdi]
        test    rdi, rdi
        je      .LBB0_1
        mov     esi, 4
        mov     edx, 4
        jmp     qword ptr [rip + __rust_dealloc@GOTPCREL]
.LBB0_1:
        ret

example::foo:
        push    rbx
        sub     rsp, 16
        mov     qword ptr [rsp + 8], 0
        call    rdi
        add     rsp, 16
        pop     rbx
        ret
        mov     rbx, rax
        lea     rdi, [rsp + 8]
        call    core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<i32>>>
        mov     rdi, rbx
        call    _Unwind_Resume@PLT
        ud2

DW.ref.rust_eh_personality:
        .quad   rust_eh_personality
```

`_var` is known to be `None` so the deallocation is optimized away in the normal flow. But in landing pad for unwinding, it still generates a branch to check if `_var` is null. But it's a local variable which is not able to be modified in anywhere else and should be known to be null.

I'm expecting the `drop` of `_var` should be completely elided so that `g()` can be a tail call.

### LINKED ISSUE #97217: Codegen/allocator regression from 1.60
In 1.60 the following code causes no allocations:

```rust
pub fn main() -> i32 {
    let v1 = vec![5, 6, 7];
    let v1_iter = v1.iter();
    let total: i32 = v1_iter.sum();
    println!("{}",total);
    total
}
```

However in nightly there is an allocation, see: https://godbolt.org/z/cq9b1Pnva

EDIT:

Appears there is also a problem with 1.60 and opt-level 2 vs 3: https://godbolt.org/z/8MWjEvPbh

### PR DESCRIPTION
**Pull request by InnovativeInventor**
I noticed that certain inlining optimizations were missing while staring at some compiled code output. I'd like to see this relanded, so I rebased the PR from @erikdesjardins (PR #94823).

This PR reapplies https://github.com/rust-lang/rust/pull/92419, which was reverted in https://github.com/rust-lang/rust/pull/94402 due to https://github.com/rust-lang/rust/issues/94390.

Fixes https://github.com/rust-lang/rust/issues/46515, fixes https://github.com/rust-lang/rust/issues/87055.

Update: fixes #97217.

### CODE REVIEW

**Comment by nagisa** [comment]
Please adjust the PR description to include the motivation (@nikic’s comment) explaining _why_ it is okay to reapply the patch.

r=me otherwise.

File: compiler/rustc_codegen_gcc/src/builder.rs [hunk 1]
```diff
@@ -1253,8 +1253,9 @@ impl<'a, 'gcc, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'gcc, 'tcx> {
         self.cx
     }
 
-    fn do_not_inline(&mut self, _llret: RValue<'gcc>) {
+    fn apply_attrs_to_cleanup_callsite(&mut self, _llret: RValue<'gcc>) {
         // FIXME(bjorn3): implement
+        unimplemented!();
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_gcc/src/builder.rs:1258]: This `unimplemented!()` shouldn't be reintroduced; it was removed in https://github.com/rust-lang/rust/commit/3888aafe3a4a030341fc21f9ac731e1a3bb108f0#diff-e4f794ca308aa712cbad31feb714df7cada1bbe453a30e232e45891571430263L1407-R1255, to work towards proper unwinding support in `rustc_codegen_gcc`.

Doing nothing is a correct (if suboptimal) implementation of this function, since it just adds optimization hints, and doesn't change the semantics of the call.

**Comment by nikic** [comment]
Probably fixes #97217 as well.

**Comment by Kobzol** [comment]
We should also check perf. before relanding. (I don't know if this PR is ready for that, so I didn't schedule it yet to avoid spam).

**Comment by lqd** [comment]
Did anything change in serde since last time, or are we accepting that merging this will "reopen" https://github.com/rust-lang/rust/issues/94390 (it's not closed, but supposedly fixed) -- does https://github.com/MarkDDR/long_compile_rustc_1.59.0 still build slowly with this PR compared to nightly ?

**Comment by nikic** [comment]
@lqd I don't know if anything changed in serde, but the intention here is indeed to potentially regress compile-time for certain types of excessively large machine-generated code in favor of fixing a class of common optimization failures.

**Comment by lqd** [comment]
It would be reassuring to have an idea on how common these excessively large cases are, but I don't think we have such data. It feels like it should be rare to me, and worth the better codegen.

Because of the tradeoff, do we know if that's a call that t-compiler should make (at their next meeting) or is wg-llvm signoff enough ?

**Comment by nagisa** [comment]
Looking at the perf results, it seems like the one-off regressions are LLVM doing more stuff in some instances. Not super much more, but also quite expected given that LLVM now has a free pass to inline a bunch more code.

**Comment by the8472** [comment]
It also results in binary size improvements.

**Comment by nagisa** [comment]
cc @pcwalton you were looking into something similar from your zulip comments. Just letting you know this is sort-of ready to land.

@InnovativeInventor would you have some time to rebase this change to master?

File: compiler/rustc_codegen_gcc/src/builder.rs (hunk 1 above)
Comment (InnovativeInventor) [reply compiler/rustc_codegen_gcc/src/builder.rs]: Ok, I just pushed a commit that removes the unimplemented call.

File: compiler/rustc_codegen_gcc/src/builder.rs [hunk 2]
```diff
@@ -1253,8 +1253,7 @@ impl<'a, 'gcc, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'gcc, 'tcx> {
         self.cx
     }
 
-    fn do_not_inline(&mut self, _llret: RValue<'gcc>) {
-        // FIXME(bjorn3): implement
+    fn apply_attrs_to_cleanup_callsite(&mut self, _llret: RValue<'gcc>) {
```
[the remark this answers is not in the document]
Comment (InnovativeInventor) [reply compiler/rustc_codegen_gcc/src/builder.rs:1256]: Ok!

**Comment by erikdesjardins** [comment]
@nagisa looks like bors missed your comment? I actually don't see this in the queue [at all](https://bors.rust-lang.org/queue/rust), which is weird

**Comment by nikic** [comment]
Hm, we should probably configure FileCheck to display more context for failures, the interesting part is cut off here.

**Comment by nagisa** [comment]
Would be awesome if that’s actually possible.

**Comment by apiraino** [comment]
Hello - checking progress. Anything blocking this PR? Seems to be approved by the reviewer. Thanks for an update.

cc: @InnovativeInventor

**Comment by InnovativeInventor** [comment]
Sorry about the delay -- I just fixed the failing test and rebased off of master.

File: tests/codegen/unwind-landingpad-inline.rs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    }
+}
+
+// Without inlining, the compiler can't tell that
+// dropping an empty string (in a landing pad) does nothing.
+// With inlining, the landing pad should be optimized out.
+// See https://github.com/rust-lang/rust/issues/87055
+// CHECK-LABEL: @check_eliminate_noop_drop
+// CHECK: start:
+// CHECK-NEXT: invoke void %g()
```
Comment (nikic) [inline tests/codegen/unwind-landingpad-inline.rs:31]: But that means the drop isn't actually getting eliminated, right? Do you have the full output for this one?

Comment (InnovativeInventor) [reply tests/codegen/unwind-landingpad-inline.rs]: Oh, good point. You're right -- the drop isn't actually getting eliminated if `invoke void %g()` is generated. I just reverted the commit. 

Somehow reverting the commit fixes this failing test?

**Comment by InnovativeInventor** [comment]
@nikic you were right about this fixing #97217. I just added this regression test, which passes:
```rust
pub fn issue97217() -> i32 {
    // drop_in_place should be inlined and never appear
    // CHECK-NOT: drop_in_place

    // __rust_alloc should be optimized out
    // CHECK-NOT: __rust_alloc

    let v1 = vec![5, 6, 7];
    let v1_iter = v1.iter();
    let total: i32 = v1_iter.sum();
    println!("{}",total);
    total
}
```
Just to make sure it functions as a regression test: I tried out this regression test with the latest commit on master (with none of the changes made in this PR) and it fails as expected.

File: tests/codegen/unwind-landingpad-cold.rs [hunk 4]
```diff
@@ -0,0 +1,15 @@
+// no-system-llvm: needs #92110
```
Comment (nikic) [inline tests/codegen/unwind-landingpad-cold.rs:1]:
```suggestion
// min-llvm-version: 14.0.0
```

File: tests/codegen/unwind-landingpad-inline.rs [hunk 5]
```diff
@@ -0,0 +1,37 @@
+// no-system-llvm: needs #92110 + patch for Rust alloc/dealloc functions
```
Comment (nikic) [inline tests/codegen/unwind-landingpad-inline.rs:1]:
```suggestion
// min-llvm-version: 15.0.0
```

File: tests/codegen/unwind-landingpad-inline.rs [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+    }
+}
+
+// Without inlining, the compiler can't tell that
+// dropping an empty string (in a landing pad) does nothing.
+// With inlining, the landing pad should be optimized out.
+// See https://github.com/rust-lang/rust/issues/87055
+// CHECK-LABEL: @check_eliminate_noop_drop
+// CHECK: start:
+// CHECK-NEXT: call void %g()
```
Comment (nikic) [inline tests/codegen/unwind-landingpad-inline.rs:31]: Okay, it looks like this indeed doesn't optimize as expected. From the IR dump, it should be eligible for inlining, but it still doesn't happen for some reason. We should use `CHECK-NOT: call void %g()` here and add a TODO, and not mark that issue as as fixed.

Comment (InnovativeInventor) [reply tests/codegen/unwind-landingpad-inline.rs:31]: Is there any way I can run the CI enviroment locally? This is what my `unwind-landingpad-inline.ll` file looks like:
```
; ModuleID = 'unwind_landingpad_inline.8bb05d3a-cgu.0'
source_filename = "unwind_landingpad_inline.8bb05d3a-cgu.0"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nonlazybind uwtable
define void @check_no_escape_in_landingpad(ptr nocapture noundef nonnull readonly %f) unnamed_addr #0 personality ptr @rust_eh_personality {
start:
  ret void
}

; Function Attrs: nonlazybind uwtable
define void @check_eliminate_noop_drop(ptr nocapture noundef nonnull readonly %g) unnamed_addr #0 personality ptr @rust_eh_personality {
start:
  tail call void %g()
  ret void
}

; Function Attrs: nonlazybind uwtable
declare noundef i32 @rust_eh_personality(i32, i32 noundef, i64, ptr, ptr) unnamed_addr #0

attributes #0 = { nonlazybind uwtable "probe-stack"="__rust_probestack" "target-cpu"="x86-64" }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 7, !"PIC Level", i32 2}
!1 = !{i32 2, !"RtLibUseGOT", i32 1}
```

Comment (nikic) [reply tests/codegen/unwind-landingpad-inline.rs:31]: `src/ci/docker/run.sh x86_64-gnu-stable` should reproduce the CI environment.

Sometimes codegen tests are affected by libstd being compiled with debug assertions, which I believe is also the case for `x86_64-gnu-stable`. If that's the issue, adding `ignore-debug` should fix it.

Comment (InnovativeInventor) [reply tests/codegen/unwind-landingpad-inline.rs:31]: Hmm, I'm getting
```
+ python3 ../x.py --stage 2 test
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.02s
error: could not find commit hash for downloading LLVM
help: maybe your repository history is too shallow?
help: consider disabling `download-ci-llvm`
help: or fetch enough history to include one upstream commit
thread 'main' panicked at 'explicit panic', native.rs:166:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
== clock drift check ==
  local time: Sat Feb  4 18:07:25 UTC 2023
  network time: Sat, 04 Feb 2023 18:07:25 GMT
== end clock drift check ==
```
when I try to run ` sh src/ci/docker/run.sh x86_64-gnu` (stable cannot be found).

**Comment by InnovativeInventor** [comment]
I'm not sure what's happening here. Why does linking fail? How do I interpret the build log?

**Comment by erikdesjardins** [comment]
That error occurred while building LLVM itself, so it's spurious and not caused by your changes

**Comment by InnovativeInventor** [comment]
> 💔 Test failed - [checks-actions](https://github.com/rust-lang-ci/rust/actions/runs/4187336571/jobs/7258264343)

If I am reading this right, this looks like it's still a spurious issue (a different spurious issue, though).

**Comment by slanterns** [comment]
Checked https://github.com/rust-lang/rust/blob/af3c8b27266e290cf65704284f6862d0f90ee4fc/tests/ui/issues/issue-68696-catch-during-unwind.rs, confused about why will it be considered "foreign". Does it have anything to do with the implementation in https://github.com/rust-lang/rust/pull/102721?

**Comment by apiraino** [comment]
Switching to waiting on author to take action on the failing checks (spurious failures?). Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

**Comment by slanterns** [comment]
Opened an issue for it: https://github.com/rust-lang/rust/issues/110282

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 7]
```diff
@@ -1229,9 +1231,19 @@ impl<'a, 'll, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
...
-        attributes::apply_to_callsite(llret, llvm::AttributePlace::Function, &[noinline]);
+    fn apply_attrs_to_cleanup_callsite(&mut self, llret: &'ll Value) {
+        let mut attrs = SmallVec::<[_; 2]>::new();
+
+        // Cleanup is always the cold path.
+        attrs.push(llvm::AttributeKind::Cold.create_attr(self.llcx));
+
+        // LLVM 14 contains fixes for catastrophic inlining behavior, without which
+        // inlining drop glue can lead to exponential size blowup, see #41696 and #92110.
+        if llvm_util::get_version() < (14, 0, 0) {
```
Comment (nikic) [inline compiler/rustc_codegen_llvm/src/builder.rs:1242]: This check can be dropped: We no longer support versions older than LLVM 14.

File: tests/codegen/issue-97217.rs [hunk 8]
```diff
@@ -0,0 +1,22 @@
+// min-llvm-version: 14.0.0
```
Comment (nikic) [inline tests/codegen/issue-97217.rs:1]: Can drop this as well.

File: tests/codegen/unwind-landingpad-cold.rs [hunk 9]
```diff
@@ -0,0 +1,15 @@
+// min-llvm-version: 14.0.0
```
Comment (nikic) [inline tests/codegen/unwind-landingpad-cold.rs:1]: And this.

**Comment by Dylan-DPC** [comment]
@InnovativeInventor any updates on this?

**Comment by InnovativeInventor** [comment]
Yep: I think I addressed all the feedback (from @nikic ) and it should be ready now.

**Comment by the8472** [comment]
codegen tests are unlikely to be spurious failures. have you tried reproducing it by running the docker CI script for that job locally?

**Comment by Dylan-DPC** [comment]
@InnovativeInventor any update on this?

**Comment by nikic** [comment]
I've rebased and fixed the codegen test failures on test-various. I'll re-approve tomorrow to make sure this doesn't go into the same nightly as the LLVM 17 update.

**Comment by nikic** [comment]
Improvements on check builds. Opt builds are mixed, with LLVM spending more time to optimize in some cases. This is expected and the overall impact is pretty much neutral.

@bors r+ rollup=never

**Comment by nikic** [comment]
Okay, we're back to the "Rust cannot catch foreign exceptions" failure on i686-msvc, which we already saw in a previous attempt.

**Comment by the8472** [comment]
Can we exclude that platform?

**Comment by nikic** [comment]
We could exclude platforms with SEH exceptions, but that seems fishy without understanding what causes this.

I poked around at the IR a bit, but at least the changes for the test itself look sensible to me, so the issue is probably on the libstd/panic_unwind side.

Someone with access to an MSVC system needs to debug this.

**Comment by nikic** [comment]
@wesleywiser Could you please recommend someone who can look into the MSVC issue here? We don't seem to document who the target maintainers for MSVC targets are.

**Comment by erikdesjardins** [comment]
I've spent some time looking into this, and I can't tell what the cause of the problem is. But there's definitely something wrong here.

What I can tell is:

`_CxxThrowException`, [here](https://github.com/rust-lang/rust/blob/26f4b7272428b181e0a88ad075e5c8f09dcb0e5c/library/panic_unwind/src/seh.rs#L322), gets called with a valid pointer to an `Exception` object (`throw_ptr`).

The `cleanup` function, [here](https://github.com/rust-lang/rust/blob/26f4b7272428b181e0a88ad075e5c8f09dcb0e5c/library/panic_unwind/src/seh.rs#L322), instead of getting passed `throw_ptr`, is called with some unrelated nonsensical pointer, henceforth referred to as `foo`. The first four bytes that `foo` points to are always zero, so [this load](https://github.com/rust-lang/rust/blob/26f4b7272428b181e0a88ad075e5c8f09dcb0e5c/library/panic_unwind/src/seh.rs#L332) returns zero, which of course is not the correct canary value, triggering the "foreign rust exception" error.

I cannot tell how `foo` ends up as the argument to `cleanup`, but it seems like a miscompile, since `foo` points to (what seems to be) a deallocated object (see below). `cleanup` is called via a bunch of convoluted MSVC unwinding code, which I am trying to reverse engineer.

Setting memory breakpoints on the memory pointed to by `foo`, these are the operations that occur (in pseudo-rust):

```rs
struct Foo {
  a: AtomicU32,
  b: AtomicU32,
  inner: *const Inner
}

struct Inner {
	a: AtomicU32,
	...
}
```

```rs
// ...things happen...

foo = alloc(Foo)
*foo = <stack data> // something like `*foo = Foo { 1, 1, *const Inner { 1 } }`

// ...other things happen...

panic(...) // calls `_CxxThrowException(throw_ptr)`

// ...other things happen...

if decrement(foo.a) != 0 { goto other code; }
if decrement(foo->inner.a) != 0 { goto other code; }
if decrement(foo.b) != 0 { goto other code; }
dealloc(foo)

// ... other things happen...

cleanup(foo) // at this point, due to the decrements, foo points to `Foo { 0, 0, *const Inner { 0 } }`
```

This behavior, with two atomic counters getting decremented to zero before it's deallocated, makes me think `Foo` is `Arc`, although `Arc` isn't nested like that (maybe it's `Arc<Arc<T>>`...). Not that this really helps us understand why `foo` is getting passed to `cleanup` instead of the correct value...

**Comment by erikdesjardins** [comment]
Minimized repro:

```rs
// run-pass
// edition:2021
// needs-unwind

use std::panic::catch_unwind;
use std::sync::Arc;

struct DecrementOnDrop(*const ());

impl Drop for DecrementOnDrop {
    fn drop(&mut self) {
        unsafe { Arc::decrement_strong_count(self.0); }
    }
}

fn block_on() {
    let _waker = DecrementOnDrop(Arc::into_raw(Arc::new(())));

    panic!();
}

#[inline(never)]
#[no_mangle]
fn panicked_at() {
    _ = catch_unwind(|| block_on());
}

fn main() {
    panicked_at();
}

```

**Comment by oxalica** [comment]
I found there's a patch https://reviews.llvm.org/D150989 in LLVM 17 which claims to fix the mutual inlining explosion. If that's the case, does it mean we don't need cold/noinline on landing pads anymore at all?

Unfortunately I couldn't find any recent enough test to verify. #94390 seems irrelevant to this inlining explosion since their example is still slow to compile on current nightly 68c2f5ba0ffb6f7f0724dd62c7562daa634caaec (with noinline) for me. This ancient comment https://github.com/rust-lang/rust/issues/41696#issuecomment-302137694 also cannot reproduce.

**Comment by erikdesjardins** [comment]
@oxalica I'm confused what you're responding to. I don't think anyone is in doubt that the exponential inlining issues are fixed, that's the reason this PR removes `noinline`.

We want `cold`, since panicking paths are cold, pretty much by definition.

**Comment by oxalica** [comment]
> @oxalica I'm confused what you're responding to. I don't think anyone is in doubt that the exponential inlining issues are fixed, that's the reason this PR removes `noinline`.
> 
> We want `cold`, since panicking paths are cold, pretty much by definition.

My bad, I misunderstood it to be all drop calls. Yeah, landing pads should be cold.

**Comment by nikic** [comment]
If I'm understanding things correctly here, a reduced example would be:
```llvm
@type_info = external global ptr

define void @test(ptr %arg) personality ptr @__CxxFrameHandler3 {
bb:
  %a1 = alloca ptr, align 4
  %a2 = alloca ptr, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %a2)
  invoke void @throw()
          to label %bb14 unwind label %bb8

bb8:                                              ; preds = %bb7
  %i9 = cleanuppad within none []
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %a1)
  store ptr %arg, ptr %a1, align 4
  call fastcc void @foo(ptr %a1) [ "funclet"(token %i9) ]
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %a1)
  cleanupret from %i9 unwind label %bb15

bb14:                                             ; preds = %bb7
  unreachable

bb15:                                             ; preds = %bb13, %bb5
  %cs = catchswitch within none [label %bb17] unwind to caller

bb17:                                             ; preds = %bb15
  %cp = catchpad within %cs [ptr @type_info, i32 8, ptr %a2]
  %p = load ptr, ptr %a2, align 4
  call fastcc void @cleanup(ptr %p) [ "funclet"(token %cp) ]
  catchret from %cp to label %exit

exit:
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %a2)
  ret void
}

declare i32 @__CxxFrameHandler3(...)
declare void @throw()
declare void @cleanup(ptr)
declare void @foo(ptr)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
```

Here `%a1` and `%a2` get allocated to the same stack slot.

Something I don't fully understand is at which point precisely the exception object `%a2` gets written. For the stack slot reuse to be problematic, this must happen before the `cleanuppad` runs, rather than before the `catchswitch`/`catchpad` runs. Is that what happens? Is there any documentation (or open-source implementation) for this anywhere?

**Comment by nikic** [comment]
I've filed https://github.com/llvm/llvm-project/issues/66984 upstream.

Some helpful references on C++ SEH: https://www.codeproject.com/Articles/2126/How-a-C-compiler-implements-exception-handling and https://gitlab.winehq.org/wine/wine/-/blob/ee17400c05d88fa29d0b895fa01902adfc91ba7f/dlls/msvcrt/except_x86_64.c#L513

**Comment by nikic** [comment]
The WinEH issue should be fixed now. We can try this again with a condition for LLVM >= 17.0.2.

**Comment by nikic** [comment]
I've limited this to LLVM >= 17.0.2. Fingers crossed that i686-msvc works after the LLVM fix.

@bors r+

**Comment by nikic** [comment]
Looks spurious:
```
2023-10-02T15:06:15.1832520Z [0m[0m[1m[32m    Updating[0m crates.io index
2023-10-02T15:56:43.8689800Z ##[error]The operation was canceled.
```

@bors retry

**Comment by rylev** [comment]
@nikic @InnovativeInventor - I'm doing the perf triage. Looks like the results are on average an improvement - the one concern I have is the very large regression in ripgrep opt. I suppose this is to be expected with LLVM doing more (which is backed up by the detailed perf results which show more time spent in LLVM). I just wanted to make sure that my interpretation is indeed correct, and the regressions we're seeing are both expected and acceptable.

**Comment by Kobzol** [comment]
The regex search runtime benchmark (which is usually quite stable) saw some improvement from this change - https://perf.rust-lang.org/compare.html?start=5333b878c8bc1c4267a67ea3682663629e47541a&end=2e5a9dd6c9eaa42f0684b4b760bd68fc27cbe51b&stat=instructions%3Au&tab=runtime. It uses the `regex` crate (which is also used by `ripgrep`) internally. I wouldn't make much of it, but could be a hint that indeed regex optimizes slightly better thanks to this.

**Comment by nikic** [comment]
> @nikic @InnovativeInventor - I'm doing the perf triage. Looks like the results are on average an improvement - the one concern I have is the very large regression in ripgrep opt. I suppose this is to be expected with LLVM doing more (which is backed up by the detailed perf results which show more time spent in LLVM). I just wanted to make sure that my interpretation is indeed correct, and the regressions we're seeing are both expected and acceptable.

Yes, that's right. As the change allows more inlining, LLVM will spend more time optimizing in some cases, but also producing better code. (Which is why we're seeing improvements on check builds.)

**Comment by InnovativeInventor** [comment]
> The regex search runtime benchmark (which is usually quite stable) saw some improvement from this change - https://perf.rust-lang.org/compare.html?start=5333b878c8bc1c4267a67ea3682663629e47541a&end=2e5a9dd6c9eaa42f0684b4b760bd68fc27cbe51b&stat=instructions%3Au&tab=runtime. It uses the `regex` crate (which is also used by `ripgrep`) internally. I wouldn't make much of it, but could be a hint that indeed regex optimizes slightly better thanks to this.

This is not surprising -- the compiled code output that I was looking at that initially led me to submit this PR was in `ripgrep`.
