### PR TITLE
Detailed panic messages for Vec functions

### LINKED ISSUE #70524: Improve panic messages for Vec methods
I've spotted, that `remove()` panic message could've provided details on what values led to this panic, instead of mentioning condition only. Generally speaking this and some other `assert!`s in Vec could've been more detailed. If it's okay to step in, I'd like to offer my help.  

In case of `remove` I'd suggest calling this instead
```rust
assert!(index < len, "removal index {} should be less than length {}", index, len); 
```

I find this more informative than `assertion failed: index < len`

Candidates for improval:

aforementioned `remove`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1034

`insert`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L994

`drain`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1292-L1293

`split_off`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1383

### PR DESCRIPTION
**Pull request by IgorPerikov**
pass indexes to insert, remove, drain, and split_off panic messages

closes #70524

### CODE REVIEW

File: src/liballoc/vec.rs [hunk 1]
```diff
@@ -992,7 +992,7 @@ impl<T> Vec<T> {
     #[stable(feature = "rust1", since = "1.0.0")]
     pub fn insert(&mut self, index: usize, element: T) {
         let len = self.len();
-        assert!(index <= len);
+        assert!(index <= len, "index out of bounds: the len is {} but the index is {}", len, index);
```
Comment (RalfJung) [inline src/liballoc/vec.rs]: Given that the bounds check for `insert` functions is different from indexing (`<=` rather than `<`), I wonder if it makes sense to also make the error different?

Comment (RalfJung) [reply src/liballoc/vec.rs]: Also, if we want to be *really* sure this behaves like indexing, we could make `core::panicking::panic_bounds_check` public and call it (though until the next bootstrap bump, that requires conditional compilation unfortunately).

I am not sure if that's worth it, though.

File: src/liballoc/vec.rs [hunk 2]
```diff
@@ -1290,8 +1290,8 @@ impl<T> Vec<T> {
             Excluded(&n) => n,
             Unbounded => len,
         };
-        assert!(start <= end);
-        assert!(end <= len);
+        assert!(start <= end, "start {} should be less than or equal to end {}", start, end);
+        assert!(end <= len, "index out of bounds: the len is {} but the end is {}", len, end);
```
Comment (RalfJung) [inline src/liballoc/vec.rs]:
```suggestion
        assert!(end <= len, "end out of bounds: the len is {} but the end is {}", len, end);
```

File: src/liballoc/vec.rs (hunk 1 above)
Comment (IgorPerikov) [reply src/liballoc/vec.rs]: > Given that the bounds check for insert functions is different from indexing (<= rather than <), I wonder if it makes sense to also make the error different?

I was thinking on how to check all three boxes: 
- don't fall into bloated error message
- introduce argument values
- keep it consistent with everything else (basically `[]` call)

Other than that, I think bringing both conditions and parameters might work better. However, if we want to add some human-readable explanation, it gets really big, like that 
```rust
assert!("index out of bounds, index should be <= len, got {} <= {}", index, len);
```

Comment (IgorPerikov) [reply src/liballoc/vec.rs]: Well, now I'm thinking that is has an appropriate size, but then it will require `core::panicking::panic_bounds_check` to be updated, to bring condition there too

Comment (RalfJung) [reply src/liballoc/vec.rs]: No the condition would have to stay here.

Comment (IgorPerikov) [reply src/liballoc/vec.rs]: Can you elaborate? I think I didn't get the context

Comment (RalfJung) [reply src/liballoc/vec.rs]: I'm just saying that function must not change.

But in the end it probably is better to just do what you did, and not try to literally share the message with indexing... I was just bringing up the possibility.

**Comment by IgorPerikov** [comment]
@RalfJung I've decided to follow approach of having detailed message so it's easy to understand:
- what kind of index is that
- what was the passed values
- what assertion should be satisfied

**Review by LukasKalbertodt — COMMENTED** [review]
Thanks for your PR! I have two main comments:

---

I don't quite like the second part of your error messages. The first part (stating the condition) is nice. But the second part is not explicit enough for me. For example, instead of 

> `insertion index should be <= len, got {} <= {}", index, len`

... I would write something like this:

> `insertion index should be <= len, but the insertion index is {} and len is {}", index, len`

This, of course, is not a particularly nice English as we will repeat the names (indices/len) a lot. I think clarity and explicitness in these error messages is more important than nice English, but maybe we can improve it still. How about one of these?

- ```"assertion `index <= len` failed: insertion index is {} and len is {}"```
- ```"index out of bounds: insertion index is {} and len is {}, but `index <= len` should hold"```

---

My second concern is performance. These are methods potentially called in hot loops. Panicking with a static string generates way less code than using the fmt machinery. And making those methods larger influences icache and inlining behavior, having a potentially large impact on performance. This could be (at least partially) mitigated by created special `#[cold]` functions that simply panic. In any case, I'd like to check with `@rust-timer`.

**Comment by LukasKalbertodt** [comment]
Ok, let's try talking to a new bot ^_^

@bors try @rust-timer queue

**Comment by IgorPerikov** [comment]
I prefer first one among options you mentioned - it's more concise and as informative as second. 
> "assertion `index <= len` failed: insertion index is {} and len is {}"


I've been thinking about another approach as well: 
`removal index {} should be < len {}`
and maybe add extra parentheses around parameter values

I saw this idiom somewhere outside Rust ecosystem and I like it, what are your thoughts about it?

**Comment by LukasKalbertodt** [comment]
Slightly modified? 

`removal index (is {}) should be < len (is {})`

I think the "is" make it slightly clearer. What do you think? I'd be fine with that.

**Comment by IgorPerikov** [comment]
> I think the "is" make it slightly clearer. What do you think? I'd be fine with that.

I like it either, it's that I used to the template w/o 'is', but I agree that would be better in general. 

> this one isn't clearly stating a problem

Isn't the fact that panic occurred states it? Maybe a bit implicit, but still

**Comment by LukasKalbertodt** [comment]
> Isn't the fact that panic occurred states it? Maybe a bit implicit, but still

Just to be clear, this is just nitpicking on my side. I'm fine with the version I posted in my last comment (with "is"). Just take any of the ones I labeled as "fine" ^_^

**Comment by IgorPerikov** [comment]
Ok, got it ^^
How rust-timer went? I can't understand the outcome of comparison from the result page

**Comment by LukasKalbertodt** [comment]
> How rust-timer went? I can't understand the outcome of comparison from the result page

I just noticed it already shows results. I would have expected another comment of the bot here, telling us the comparison is done. Anyway...

The results don't look too good I think. Basically every test case slowed down by between 0.1% and 0.8%. While this sounds minor, if this change is really caused by this change, I'm not particularly comfortable merging this as is. To put the numbers in perspective: PRs that improve compile times by half a percent across all test cases are rare and a really great achievement. 

Now I'm not sure if this change could also be caused by something else. I will ask someone :)

**Comment by RalfJung** [comment]
A possible experiment would be go back to my weird idea from earlier, and call `panic_bounds_check` (which is already optimized for being called in hot loops).

So the checks would become something like
```rust
if index >= len { panic_bounds_check(index, len) }
```
Except this will only work on `not(bootstrap)` builds... the next bootstrap bump should happen around end of April, this will become easier then.

**Comment by LukasKalbertodt** [comment]
I just talked to `@Centril` and they also think it's a pretty clear regression, performance wise. 

@IgorPerikov Could you rewrite this so that the formatting is done in a separate `#[cold]` function? For example, for `insert`, replace the `assert!(...)` with:
```rust
#[cold]
#[inline(never)]  // <-- probably implied by `#[cold]` but no one knows for sure...
fn assert_failed(index: usize, len: usize) -> ! {
    panic!("insertion index (is {}) should be <= len (is {})", index, len);
}

if index > len {
    assert_failed(index, len);
}
```

(The `assert_failed` definition within the `insert` function.)

With that changed for all methods, we can run the perf test again to see if that improved things.

**Comment by RalfJung** [comment]
@LukasKalbertodt potentially `assert_failed` should have `#[track_caller]` for better panic locations.

**Comment by LukasKalbertodt** [comment]
@RalfJung Good idea!

As we posted the previous comments at the same time: your suggestion with `panic_bounds_check` is also just a `#[cold]` function, right? So by writing custom functions we can provide better error messages, right?

**Comment by RalfJung** [comment]
> As we posted the previous comments at the same time: your suggestion with panic_bounds_check is also just a #[cold] function, right? So by writing custom functions we can provide better error messages, right?

Exactly. Specifically, this is the cold function that is used to raise the panic on out-of-bounds slice/array/vector access. So it makes sense to call that whenever the error message should be exactly the same as for indexing.

**Comment by IgorPerikov** [comment]
I definitely lack a lot of fundamental knowledge about how Rust works under the hood. One of the things I don't understand is this statement:

> and call 'panic_bounds_check' (which is already optimized for being called in hot loops).

How is that possible if `#[cold]` means [suggests that the attributed function is unlikely to be called](https://doc.rust-lang.org/reference/attributes/codegen.html#the-cold-attribute)? So attribute name and its description implies reverse. 

I also don't get it, how can we reuse `panic_bounds_check` for cases, where we:
- check that `<=` instead of `<`, decreasing/increasing one of the parameters before passing in would ruin panic message
- want customized message, like for drain, where start and end are being compared, not the length, and also mentioning removal/insertion instead of generic `Out of bounds`

Maybe it's getting too hard for a novice like me 🤷‍♂

**Comment by LukasKalbertodt** [comment]
> I don't understand is this statement:
>
> > and call 'panic_bounds_check' (which is already optimized for being called in hot loops).

I think what @RalfJung was saying is: it is optimized to be *inside* hot loops without being actually called at runtime. 

Let me explain `#[cold]` a bit more. It's a hint for the optimizer with the goal of making *the code surrounding* the call to a cold function faster. We specifically do not optimize the speed of calling the cold function. In fact, we most certainly make calling that function slower, but that's ok for us because it is called so rarely. So optimizing the surrounding code is more important. This is achieved in mainly two ways:

- The cold function won't get inlined. This means that the calling function (e.g. `insert`) gets smaller. (By "smaller", I mean that it contains fewer instructions in the resulting machine code.) That in turn is important for the instruction cache (icache) and more importantly, it makes the calling function more likely to get inlined itself.
- The assembly is laid out differently in the calling function (usually placing the `call` to the cold function at the very end).

> I also don't get it, how can we reuse `panic_bounds_check` for cases, where we: ...

Yes, it would just be useful for the cases with the exact behavior and error message we want, which is only `remove`, I think. That's why I suggested we write out own cold functions to panic.

> Maybe it's getting too hard for a novice like me :man_shrugging:

Nah, don't worry, you got this. Just ask if anything is unclear. For now, just do what I described [in this comment](https://github.com/rust-lang/rust/pull/70573#issuecomment-607370303). If anything about that is unclear, just ask. Also feel free to contact me via Zulip or Discord.

**Comment by RalfJung** [comment]
> I think what @RalfJung was saying is: it is optimized to be inside hot loops without being actually called at runtime.

Indeed I do, sorry for not being clearer.

**Comment by IgorPerikov** [comment]
@LukasKalbertodt Thanks for a thorough explanation, I got the point, but have broken some test. Will investigate it tomorrow.

**Review by LukasKalbertodt — CHANGES_REQUESTED** [review]
Two main things:

- Please move the definitions of the `assert_failed` functions inside of the other methods. In case you aren't aware, Rust allows function definitions within functions. For example:

    ```rust
    fn foo() {
        fn bar() { println!("hi"); }
    
        bar();
    }
    ```

    That way, you can also give all of those functions the same name. And you don't need the `Vec::<T>::` prefix to call the function.

- You have to insert all conditions. The `assert` has the condition that *should be `true`*, where as your `if _ { failed() }` needs to have the condition that *should be `false`*. This is what's causing the CI to report an error.

**Comment by IgorPerikov** [comment]
Oh, right, I rushed it and forgot about inverting it. Thanks for the tips on functions too. 

I'll try to launch rust-timer

@bors try @rust-timer queue

**Review by LukasKalbertodt — APPROVED** [review]
Looks good! Let's see what rust-timer says.

(Just for the protocol: I thought about switching the two parameters of the cold functions as I suspected that to generate slightly better assembly because of register assignment. In particular, in `insert`, the index is passed via `rsi` (2nd parameter). I thought making `index` the second parameter of ´assert_failed` would be beneficial, but it turns out it doesn't matter. LLVM does some stuff with the registers beforehand anyway. I checked both versions and with `index` as second parameter, it even has one additional instruction. Additionally, `insert` is larger than I expected, so saving one or two instructions isn't that important anyway.)

**Comment by LukasKalbertodt** [comment]
Well that is looking way better. Mostly 0.0%, some 0.1%. But there are a couple with changes as high as 0.7%. @RalfJung I'd be interested in your interpretation of those results as you have way more experience in that than I have.

**Comment by RalfJung** [comment]
Hm, some go up to 2.4%. I'm afraid I can also just guess here.

**Comment by IgorPerikov** [comment]
> goes up 2.4%

it means improvement?

**Comment by RalfJung** [comment]
No, runtime goes up by 2.5%.

**Comment by LukasKalbertodt** [comment]
@nnethercote @eddyb @zoxc Could someone of you maybe help us interpret these perf results? So I guess if we have any measurable regression, we probably don't want to merge this. We are just not sure if this is a regression.

**Comment by eddyb** [comment]
Regression with "clean" but not "baseline incremental" is likely noise, incremental should be *strictly* slower, and the regression in `regression-31157-opt` is also likely noise (it's entirely within LLVM).

If I had to guess, this PR doesn't observably change the performance of `rustc`.

**Comment by nnethercote** [comment]
The 2.6% `html5ever-opt-clean` regression is the only thing that concerns me. It might be real, it might be noise, but it's not enough to block landing, IMO.

**Comment by eddyb** [comment]
@nnethercote That's the one I was saying I don't believe is real because I would expect "baseline incremental" to regress in the same way as "clean", and it doesn't.

**Comment by RalfJung** [comment]
My PR changing `swap_remove` landed; could you rebase this and make its panic handling consistent with the rest?

**Comment by LukasKalbertodt** [comment]
Concerning performance: I guess we can land this PR then. If it turns out to have a notably speed decrease in practice, we can still revert or tweak it. Coincidentally, a while back, I wrote a few benchmarks that make heavy use of `Vec::insert`. I can run those benchmarks once this PR is released as nightly.

**Comment by RalfJung** [comment]
Agreed, but let's also do @bors rollup=never for easier bisecting.

**Comment by IgorPerikov** [comment]
> My PR changing swap_remove landed; could you rebase this and make its panic handling consistent with the rest?

Sure, will do!

**Comment by IgorPerikov** [comment]
Soo.. I've messed up something. Tbh got used to strategy of merging whatever I need and then squash-merging into master

**Comment by LukasKalbertodt** [comment]
> I guess it'd be easier to create new pr against master with needed changes and link to this for discussions history, @LukasKalbertodt are u agree?

I'd be fine with that.

**Comment by eddyb** [comment]
@IgorPerikov Just run `git pull --rebase https://github.com/rust-lang/rust master`, it should auto-fix everything.

**Comment by IgorPerikov** [comment]
> Just run git pull --rebase https://github.com/rust-lang/rust master, it should auto-fix everything.

This didn't work out as I was forced to resolve all the conflicts, solving them and continuing didn't help, so I skipped and force-pushed. I suppose it should be fine now

**Comment by eddyb** [comment]
Ah, hmm, if you had duplicated history compared to `master` then it could cause conflicts.
`git rebase -i upstream/master` (wasn't sure what your remote name is though) is the better alternative because it lets you remove redundant commits (which I guess you did with `--skip`).

Anyway I'm glad the PR is saved :).

**Comment by LukasKalbertodt** [comment]
@IgorPerikov I know this isn't the best time to ask this (as you just had lots of git trouble), but you could squash your commits into one or two? Currently there are many commits that don't compile. This makes the git history somewhat meh. If you need help with squashing, be sure to ask, we can help. (I'm pretty busy right now, but I can provide more information later, if you want.)

**Comment by IgorPerikov** [comment]
@LukasKalbertodt no-no It's okay for sure :) I can do it manually, but isn't squash and merge (in github merge pr dropdown menu) would solve it too?

**Comment by RalfJung** [comment]
Yeah but we don't merge via that button. We have a bot that makes sure CI passes on the merged state *before* putting anything to master.

That bot unfortunately has no auto-squashing ability.

**Review by LukasKalbertodt — APPROVED** [review]

**Comment by LukasKalbertodt** [comment]
Looks good to me. Thanks a bunch for squashing and updating the PR :)

@bors r+ rollup=never

**Comment by IgorPerikov** [comment]
Thanks everyone for all the valuable tips and infos. Your support was one in a kind actually

**Comment by LukasKalbertodt** [comment]
>  Coincidentally, a while back, I wrote a few benchmarks that make heavy use of `Vec::insert`. I can run those benchmarks once this PR is released as nightly.

Finally managed to do this. I compared nightly-2020-04-05 and nightly 2020-04-10. I couldn't see any differences in my benchmark apart from noise. So that's another hint that this change doesn't cause a notable performance regression.
