### PR TITLE
[std] fix the presentation of `split_off_mut` and `split_off` documentation

### LINKED ISSUE #141107: Misleading description of range in split_off() and split_off_mut()
### Location

In the second example of each of these: 

- [`<[T]>::split_off`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.split_off)
- [`<[T]>::split_off_mut`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.split_off_mut)

### Summary

The second example of these two APIs are described as follows: 

> Splitting off the last two elements of **a** slice:

```rust
let mut slice: &[_] = &['a', 'b', 'c', 'd'];
let mut tail = slice.split_off(2..).unwrap();

assert_eq!(slice, &['a', 'b']);
assert_eq!(tail, &['c', 'd']);
```

I believe this is intended as a simple description of what the example is doing, which isn't wrong. 
-> However, it is **only correct if the slice is 4 elements** total. 

Suggested correction: 
"Splitting off a slice from the third element to the last:"

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #141107 

r? libs

### CODE REVIEW

**Review by chenyukang — APPROVED** [review]

File: library/core/src/slice/mod.rs [hunk 1]
```diff
@@ -4383,7 +4383,7 @@ impl<T> [T] {
     /// assert_eq!(first_three, &['a', 'b', 'c']);
     /// ```
     ///
-    /// Splitting off the last two elements of a slice:
+    /// Splitting off a slice from the third element to the last:
```
Comment (workingjubilee) [inline library/core/src/slice/mod.rs:4386]: Another option is to make the document comment *correct* by complicating the code with `slice.len()`... but that seems a bit much.

Comment (xizheyin) [reply library/core/src/slice/mod.rs:4386]: You mean `slice.split_off(slice.len()-2..)`?

This is logically feasible, but as a code example, we should probably keep the code simple, otherwise people who read the code will need to do extra arithmetic calculations.

Comment (workingjubilee) [reply library/core/src/slice/mod.rs:4386]: Agreed. The new wording does feel _slightly_ awkward. Do you think "starting with the third element" would be good?

Comment (xizheyin) [reply library/core/src/slice/mod.rs:4386]: That's a good expression. :)

**Comment by workingjubilee** [comment]
nice!
@bors r+ rollup
