### PR TITLE
Only disable cache if predicate has opaques within it

### LINKED ISSUE #132064: regression: crate compiles much slower with 1.82
Our project takes much longer to compile with Rust 1.82 compared to previous versions. To reproduce, git clone `https://github.com/LemmyNet/lemmy.git` and run `cargo check` (also happens with build or lint). The problem happens specifically with the crate [lemmy_db_views](https://github.com/LemmyNet/lemmy/tree/main/crates/db_views).

cargo check with 1.82: 6m 19s

cargo check with 1.81: 1m 22s

### Version it worked on

It most recently worked on:1.81

### Version with regression

`rustc --version --verbose`:
```
cargo 1.82.0 (8f40fc59f 2024-08-21)
release: 1.82.0
commit-hash: 8f40fc59fb0c8df91c97405785197f3c630304ea
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Manjaro 24.1.1 (Xahea) [64-bit]
```

@rustbot modify labels: +regression-from-stable-to-1.82 -regression-untriaged

### PR DESCRIPTION
**Pull request by compiler-errors**
This is an alternative to https://github.com/rust-lang/rust/pull/132075. 

This refines the check implemented in https://github.com/rust-lang/rust/pull/126024 to only disable the global cache if the predicate being considered has opaques in it. This is still theoretically unsound, since goals can indirectly rely on opaques in the defining scope, but we're much less likely to hit it.

It doesn't totally fix https://github.com/rust-lang/rust/issues/132064: for example, `lemmy` goes from 1:29 (on rust 1.81) to 9:53 (on nightly) to 4:07 (after this PR). But I think it's at least *more* sound than a total revert :/

r? lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
while this isn't entirely correct if an opaque is not directly referenced by the obligation but ends up being used: as the return type of an `FnDef` or via an impl referencing a TAIT, I don't worry much about this causing issues on stable and we can look into more involved fixes (e.g. track the defined opaques in the global cache key instead) before stabilizing TAIT.






so r=me after updating the description + src to not just be `HACK: hack`

**Comment by lqd** [comment]
> I don't worry much about this causing issues on stable

would reverting #126024 cause issues on stable? (because of the reported 4x-10x regressions to compilation times)

**Comment by lcnr** [comment]
> > I don't worry much about this causing issues on stable
> 
> would reverting #126024 cause issues on stable? (I ask because of the reported 4x-10x regressions to compilation times it caused)

in theory the incorrect caching should be triggered a lot more easily when reverting #126024 compared to the approach in this PR. It should still be fairly hard to trigger. I do have an idea on how to hopefully fully fix the regression

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -1494,7 +1498,10 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             TypingMode::Coherence => false,
             // Avoid using the global cache when we're defining opaque types
             // as their hidden type may impact the result of candidate selection.
-            TypingMode::Analysis { defining_opaque_types } => defining_opaque_types.is_empty(),
+            // HACK: hack
+            TypingMode::Analysis { defining_opaque_types } => {
+                defining_opaque_types.is_empty() || !pred.has_opaque_types()
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1503]: given that we use `can_use_global_caches` both on access and on write, could we change this to instead check that `pred` does not contain an opaque from `defining_opaque_types`, i.e. it only contains rigid opaque types

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1503]: I actually tested that and it doesn't improve perf very much lol

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1503]: yeah perf only goes from 4:07 to 4:04 when i implement a simple visitor to check if it contains an opaque in the defines list

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -1494,7 +1498,15 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
             TypingMode::Coherence => false,
             // Avoid using the global cache when we're defining opaque types
             // as their hidden type may impact the result of candidate selection.
-            TypingMode::Analysis { defining_opaque_types } => defining_opaque_types.is_empty(),
+            //
+            // HACK: This is still theoretically unsound. Goals can indirectly rely
+            // on opaquesvin the defining scope, and it's easier to do so with TAIT.
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1503]:
```suggestion
            // on opaques in the defining scope, and it's easier to do so with TAIT.
```

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1503]: meow

File: compiler/rustc_trait_selection/src/traits/select/mod.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:1508]: > yeah perf only goes from 4:07 to 4:04 when i implement a simple visitor to check if it contains an opaque in the defines list

that seems weird to me :thinking: what's causing the exponential blowup then, reuse between different MIR borrowck queries?

**Comment by apiraino** [comment]
Beta and stable backports accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-11-14/near/482416654). A backport PR will be authored by the release team at the end of the current development cycle.

Stable backport also approved, though we don't see this alone as a reason to open a dot release.

@rustbot label +beta-accepted +stable-accepted
