### PR TITLE
Fix some loop block coercion diagnostics

### LINKED ISSUE #150850: Rustc suggest `break` with value inside `while`
### Code

```Rust
pub fn a() {
    let a = while false {
        some_function()
    };
}

fn some_function() -> i32 {
    1
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> <source>:3:9
  |
2 |       let a = while false {
  |  _____________-
3 | |         some_function()
  | |         ^^^^^^^^^^^^^^^ expected `()`, found `i32`
4 | |     };
  | |_____- expected this to be `()`
  |
help: consider using a semicolon here
  |
3 |         some_function();
  |                        +
help: consider using a semicolon here
  |
4 |     };;
  |      +
help: you might have meant to break the loop with this value
  |
3 |         break some_function();
  |         +++++                +
```

### Desired output

```Shell
error[E0308]: mismatched types
 --> <source>:3:9
  |
2 |       let a = while false {
  |  _____________-
3 | |         some_function()
  | |         ^^^^^^^^^^^^^^^ expected `()`, found `i32`
4 | |     };
  | |_____- `while` loops can't produce a non-trivial (i.e. not `()`) value
  |
help: consider using a semicolon here
  |
3 |         some_function();
  |                        +
```

### Rationale and extra context

The suggestion to add a second semicolon after the loop is evidently wrong, and the suggestion to replace the expression with a `break` expression may mislead the user into thinking that will solve the problem. I can see how it may be debatable how likely confusion from said second point is, but the compiler knows from the fact that it's in a `while` loop that adding `break` won't do anything, so I don't see a good reason not to change it.

### Other cases

```Rust
If the expression inside the block is not a function call, the suggestions to add a semicolon disappear.
```

### Rust Version

```Shell
rustc 1.92.0 (ded5c06cf 2025-12-08)
binary: rustc
commit-hash: ded5c06cf21d2b93bffd5d884aa6e96934ee4234
commit-date: 2025-12-08
host: x86_64-unknown-linux-gnu
release: 1.92.0
LLVM version: 21.1.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eggyal**
Fixes rust-lang/rust#150850

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 1]
```diff
@@ -1828,10 +1828,7 @@ impl<'tcx> CoerceMany<'tcx> {
                 // If the block is from an external macro or try (`?`) desugaring, then
                 // do not suggest adding a semicolon, because there's nowhere to put it.
                 // See issues #81943 and #87051.
-                && matches!(
-                    cond_expr.span.desugaring_kind(),
-                    None | Some(DesugaringKind::WhileLoop)
-                )
+                && cond_expr.span.desugaring_kind().is_none()
```
Comment (dianne) [inline compiler/rustc_hir_typeck/src/coercion.rs:1833]: Could you update the comment to account for this change?

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -1170,23 +1170,23 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
         let found = self.resolve_vars_if_possible(found);
 
-        let in_loop = self.is_loop(id)
+        let in_breakable_loop = self.is_loop_breakable_with_value(id)
```
Comment (dianne) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Nit: `in_breakable_loop` feels slightly misleading as the name for the variable, since `for` and `while` loops are breakable too. Maybe something about `loop` expressions would make sense without being as verbose as `in_loop_breakable_with_value`? Not sure.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -1170,23 +1170,23 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             || self
                 .tcx
                 .hir_parent_iter(id)
                 .take_while(|(_, node)| {
                     // look at parents until we find the first body owner
                     node.body_id().is_none()
                 })
-                .any(|(parent_id, _)| self.is_loop(parent_id));
+                .any(|(parent_id, _)| self.is_loop_breakable_with_value(parent_id));
```
Comment (dianne) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: If you have a `while`/`for` nested inside a `loop`, wouldn't this still suggest adding a `break` that targets the inner loop?

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 1 above)
Comment (eggyal) [reply compiler/rustc_hir_typeck/src/coercion.rs:1833]: Actually, per the commit message on 9e08f7da1bcd89f44176b13ba1eb1024daca321f, this change merely reverts an erroneous part of 67ea84d97a49434431b45a5b34f867df18f33116 (from #88175); the code comment was not updated at that time, and it remains/is more correct now that that erroneous change is reverted.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 3 above)
Comment (eggyal) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Ah good catch!  Resolved in 48741c2dd77c1db8c4ae7530ebe23f290f2aa44c.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 2 above)
Comment (eggyal) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Renamed to `can_break_with_value` in 48741c2dd77c1db8c4ae7530ebe23f290f2aa44c.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 1 above)
Comment (dianne) [reply compiler/rustc_hir_typeck/src/coercion.rs:1833]: I saw the commit message, and I agree that your change brings it in line with the original intent, but I think it's worth noting that we're specifically not giving the suggestion for desugared loops (in addition to external macros and desugared try blocks, which the comment already points out).

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 4]
```diff
@@ -1170,23 +1170,29 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         }
         let found = self.resolve_vars_if_possible(found);
 
-        let in_loop = self.is_loop(id)
-            || self
-                .tcx
+        let innermost_loop = self.is_loop(id).then(|| self.tcx.hir_node(id)).or_else(|| {
```
Comment (dianne) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Nit: this would probably be clearer as an `if` expression.

**Review by dianne — APPROVED** [review]
I've left a reply clarifying what I meant about the incomplete comment. Apart from that and a small style thing, this looks good to me. @rustbot author

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150872/1191620b8c4a93074796408afa538e086acf38c7..48741c2dd77c1db8c4ae7530ebe23f290f2aa44c)*

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 1 above)
Comment (eggyal) [reply compiler/rustc_hir_typeck/src/coercion.rs:1833]: Added in 7c7cf45dcf6f84937faddf18f55b625f76012a3c.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 4 above)
Comment (eggyal) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: Changed in 5674be29fa5819cf5d1578f5a53f7a9603a38d90.
