### PR TITLE
Fix some E-needstest issues.

### LINKED ISSUE #30355: assertion failed: st.sized && offset <= st.size
``` rust
pub struct X([u8]);

pub static Y: &'static X = {
    const Y: &'static [u8] = b"";
    &X(*Y)
};

fn main() { }
```

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: st.sized && offset <= st.size', ../src/librustc_trans/trans/adt.rs:1307
```

### LINKED ISSUE #33241: tuples with unsized tails cause an error when compiled
## STR

``` Rust
use std::fmt;

// CoerceUnsized is not implemented for tuples. You can still create
// an unsized tuple by transmuting a trait object.
fn any<T>() -> T { unreachable!() }

fn main() {
    let t: &(u8, fmt::Debug) = any();
    println!("{:?}", &t.1);
}
```
## Actual Results

Before #32939, this caused an LLVM error

```
Stored value type does not match pointer operand type!
  store i8 %17, void (i8*)*** %18
 void (i8*)**LLVM ERROR: Broken function found, compilation aborted!
```

Afterwards, this causes an ICE (the rustc size is the correct one):

```
error: internal compiler error: ../src/librustc_trans/type_of.rs:142: size differs (rustc: 1, llvm: 24) for type `(u8, std::fmt::Debug + 'static)` / Univariant {
    variant: Struct {
        align: Align {
            raw: 48
        },
        packed: false,
        sized: false,
        offset_after_field: [
            Size {
                raw: 1
            },
            Size {
                raw: 1
            }
        ]
    },
    non_zero: false
}
```

### LINKED ISSUE #36400: Error for mut borrow of a immut Box should point to where the Box was bound
This code:

``` rust
fn f(x: &mut u32) { }

fn main() {
    let x = 3;
    f(&mut x);
}
```

produces a helpful error message:

```
error: cannot borrow immutable local variable `x` as mutable
 --> <anon>:5:12
  |
4 |     let x = 3;
  |         - use `mut x` here to make mutable
5 |     f(&mut x);
  |            ^ cannot borrow mutably
```

But the analogous code using a `Box`:

``` rust
fn f(x: &mut u32) { }

fn main() {
    let x = Box::new(3);
    f(&mut *x);
}
```

gives an error which doesn't point at the binding `x`:

```
error: cannot borrow immutable `Box` content `*x` as mutable
 --> <anon>:5:12
  |
5 |     f(&mut *x);
  |            ^^
```

### LINKED ISSUE #37887: Apparent infinite loop in AST validation with nested extern crate declaration
This program

```rust
fn main() {
    extern crate libc;
    use libc::*;
}
```

seems to cause the compiler too loop endlessly in AST validation, allocating more and more memory:

```
$ rustc -Z time-passes oom.rs 
warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details

time: 0.000; rss: 31MB  parsing
time: 0.000; rss: 31MB  recursion limit
time: 0.000; rss: 31MB  crate injection
time: 0.000; rss: 31MB  plugin loading
time: 0.000; rss: 31MB  plugin registration
time: 0.024; rss: 51MB  expansion
time: 0.000; rss: 51MB  maybe building test harness
time: 0.000; rss: 51MB  maybe creating a macro crate
time: 0.000; rss: 51MB  checking for inline asm in case the target doesn't support it
time: 0.000; rss: 51MB  complete gated feature checking
time: 0.000; rss: 51MB  collecting defs
time: 0.000; rss: 51MB  early lint checks
time: 0.000; rss: 51MB  AST validation
^C
$ rustc --version
rustc 1.13.0
```

### LINKED ISSUE #44578: 'rustc' panicked at 'Box<Any>', when const expr evaluation panics
After seeing this [amusing workaround](https://github.com/rust-lang/rfcs/issues/322#issuecomment-263056187) for conditions in const expr, I decided to try it out. Then I was wondering what would happen if I caused index out-of-bounds. That led me to [this code](https://play.rust-lang.org/?gist=dd415f8327763b943a20fcfc7e1e87e4&version=stable).

While it correctly points to the error, it also says "the compiler unexpectedly panicked. this is a bug." and asks for reporting, so I'm reporting here.

### PR DESCRIPTION
**Pull request by MaloJaffre**
Also ignore `attr-on-trait` test on stage-1 to keep `./x.py test --stage 1` successful.

Fixes #30355.
Fixes #33241.
Fixes #36400.
Fixes #37887.
Fixes #44578.

### CODE REVIEW

File: src/test/run-pass-fulldeps/proc-macro/attr-on-trait.rs [hunk 1]
```diff
@@ -9,6 +9,7 @@
 // except according to those terms.
 
 // aux-build:attr-on-trait.rs
+// ignore-stage1
```
Comment (estebank) [inline src/test/run-pass-fulldeps/proc-macro/attr-on-trait.rs]: why was this needed?

**Review by estebank — APPROVED** [review]
r=me after verifying comment.

File: src/test/compile-fail/issue-33241.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+#![feature(rustc_attrs)]
+
+use std::fmt;
+
+// CoerceUnsized is not implemented for tuples. You can still create
+// an unsized tuple by transmuting a trait object.
+fn any<T>() -> T { unreachable!() }
+
+#[rustc_error]
+fn main() { //~ ERROR compilation successful
```
Comment (estebank) [inline src/test/compile-fail/issue-33241.rs]: Can you, instead of forcing the failure, make a `run-pass` test?

Comment (MaloJaffre) [reply src/test/compile-fail/issue-33241.rs]: This test panics when running, because of the `unreachable!()`.

Do you want me to move it to `run-fail`?

File: src/test/run-pass-fulldeps/proc-macro/attr-on-trait.rs (hunk 1 above)
Comment (MaloJaffre) [reply src/test/run-pass-fulldeps/proc-macro/attr-on-trait.rs]: This is the only test that fails on my machine (`x86_64-unknown-linux-gnu` with `./x.py test --stage 1`), and because it is in `run-pass-fulldeps`, running it only in `stage 2` doesn't seem a problem, because other tests in this directory are ignored on `stage 1`.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!
