### PR TITLE
fix Miri assignment sanity check

### LINKED ISSUE #70804: Miri comparison sanity check is wrong
The following ICEs (example by @eddyb):
```rust
#![feature(const_fn)]

const fn nested(x: (for<'a> fn(&'a ()), String)) -> (fn(&'static ()), String) {
    x
}

pub const TEST: (fn(&'static ()), String) = nested((|_x| (), String::new()));

fn main() {}
```
shows
```
thread 'rustc' panicked at 'type mismatch when copying!
src: (for<'r> fn(&'r ()), std::string::String),
dest: (fn(&()), std::string::String)', /rustc/853c4774e26ea97b45fe74de9a6f68e526784323/src/libstd/macros.rs:16:9
```

This means that [the check here](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/interpret/eval_context.rs#L215-L234) is wrong. It might be possible to also trigger this without nightly features through const_prop.

### PR DESCRIPTION
**Pull request by RalfJung**
Thanks @eddyb for pointing me to the right APIs!

r? @eddyb
Fixes https://github.com/rust-lang/rust/issues/70804

### CODE REVIEW

File: src/librustc_mir/interpret/eval_context.rs [hunk 1]
```diff
@@ -213,30 +213,50 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> LayoutOf for InterpCx<'mir, 'tcx, M> {
...
+        // Layout differs, definitely not equal.
+        // We do this here because Miri would *do the wrong thing* if we allowed layout-changing
+        // assignments.
+        return false;
     }
+
+    // Type-changing assignments can happen for (at least) two reasons:
+    // 1. `&mut T` -> `&T` gets optimized from a reborrow to a mere assignment.
+    // 2. Subtyping is used. While all normal lifetimes are erased, higher-ranked lifetime
+    //    bounds with their late-bound regions are still around and can lead to type differences.
```
Comment (eddyb) [inline src/librustc_mir/interpret/eval_context.rs:234]: "higher-ranked lifetime bounds" -> "higher-ranked types" (`fn` types and `dyn Trait` types are "higher-ranked" because they can "forall"-bind lifetimes - this is what the `Binder` wrapper indicates)

**Review by eddyb — APPROVED** [review]
r=me with comment tweaked

File: src/librustc_mir/interpret/eval_context.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/eval_context.rs]: Done. I also replaced "regions" by "lifetimes".

**Review by eddyb — APPROVED** [review]
