### PR TITLE
NLL Diagnostic Review 3: Unions not reinitialized after assignment into field 

### LINKED ISSUE #55651: NLL Diagnostic Review 3: Unions not reinitialized after assignment into field
@pnkfelix's review comments:
> ui/borrowck/borrowck-union-move-assign.nll.stderr rejecting sound uses of unions; it reports 3 errors when only one expected. We should make a run-pass test from the two cases we expect to accept.

For the record, here's the relevant part of the test in question ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d379adbbd3f8e54cf8352a824bd2adf1)):

```rust
#![feature(untagged_unions)]
struct A;
struct B;
union U {
    a: A,
    b: B,
}
fn main() {
    unsafe {
        {
            let mut u = U { a: A };
            let _a = u.a;
            u.a = A;
            let _a = u.a; // OK
        }
        {
            let mut u = U { a: A };
            let _a = u.a;
            u.b = B;
            let _a = u.a; // OK
        }
    }
}
```

### LINKED ISSUE #55652: NLL Diagnostic Review 3: Diagnostic mentions lack of initialization instead of incorrect mutability
@pnkfelix's review comments: 
> ui/borrowck/reassignment_immutable_fields_overlapping.nll.stderr AST-borrowck complains about the local being immutable. NLL complains about lack of initialization. This is probably expected, but we should double-check.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #55651, #55652.

This PR makes two changes:

First, it updates the dataflow builder to add an init for the place
containing a union if there is an assignment into the field of
that union.

Second, it stops a "use of uninitialized" error occuring when there is an
assignment into the field of an uninitialized union that was previously
initialized. Making this assignment would re-initialize the union, as
tested in `src/test/ui/borrowck/borrowck-union-move-assign.nll.stderr`.
The check for previous initialization ensures that we do not start
supporting partial initialization yet (cc #21232, #54499, #54986).

This PR also fixes #55652 which was marked as requiring investigation 
as the changes in this PR add an error that was previously missing 
(and mentioned in the review comments) and confirms that the error
that was present is correct and a result of earlier partial 
initialization changes in NLL.

r? @pnkfelix (due to earlier work with partial initialization)
cc @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/mod.rs [hunk 1]
```diff
@@ -1776,6 +1777,22 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
             if let Some((prefix, mpi)) = shortest_uninit_seen {
+                // Check for a reassignment into a uninitialized field of a union (for example,
+                // after a move out). In this case, do not report a error here. There is an
+                // exception, if this is the first assignment into the union (that is, there is
+                // no move out from an earlier location) then this is an attempt at initialization
+                // of the union - we should error in that case.
+                let tcx = this.infcx.tcx;
+                if let ty::TyKind::Adt(def, _) = base.ty(this.mir, tcx).to_ty(tcx).sty {
+                    let moved_before_this = this.move_data.path_map[mpi].iter().any(|moi| {
+                        this.move_data.moves[*moi].source < context.loc
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/mod.rs]: .... is the `<` comparison here always going to reflect the control flow... ?

I would have guessed that our `PartialOrd`/`Ord` implementation is based around the numbers assigned to basic blocks, which I suspect often but *not always* correspond to control flow order...

**Comment by pnkfelix** [comment]
I think it would be a good idea to make a run-pass test adapted from the two parts of the test that do not error, checking that the state of the union is set up in the expected manner.

File: src/librustc_mir/borrow_check/mod.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: Yeah, I wasn't too sure about this either. I couldn't think of anything better at the time. I'll spend some time thinking about a way I could break this and see if I can't work out a more robust check.

Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: I've pushed a commit that changes this to look at the predecessors for a location - as I understand it, this should now correctly consider the cases where a straight comparison of the location would have failed.

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -1776,6 +1777,22 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
             if let Some((prefix, mpi)) = shortest_uninit_seen {
+                // Check for a reassignment into a uninitialized field of a union (for example,
+                // after a move out). In this case, do not report a error here. There is an
+                // exception, if this is the first assignment into the union (that is, there is
+                // no move out from an earlier location) then this is an attempt at initialization
+                // of the union - we should error in that case.
+                let tcx = this.infcx.tcx;
+                if let ty::TyKind::Adt(def, _) = base.ty(this.mir, tcx).to_ty(tcx).sty {
+                    let moved_before_this = this.move_data.path_map[mpi].iter().any(|moi| {
+                        this.move_data.moves[*moi].source.is_predecessor_of(context.loc, this.mir)
```
Comment (pnkfelix) [inline src/librustc_mir/borrow_check/mod.rs]: the `is_predecessor_of` call is O(N) time (where N is the number of locations in the MIR), right? And then you're invoking it here on every path associated with `mpi`... all to compute this boolean which is only used if `def.is_union()`...

I think it would be better (in terms of compiler slowness) for you to delay the computation of `moved_before_this` to only take place *after* you've determined `def.is_union()`.

File: src/test/ui/nll/issue-55651.rs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// run-pass
```
Comment (pnkfelix) [inline src/test/ui/nll/issue-55651.rs]: Hmm. I know I asked for this to be a `// run-pass` test, but I was at the time thinking of something that would actually do some sort of runtime validation of the resulting state...

I cannot off the top of my head come up with an obviously good change to this to make it validate its state at runtime.

So lets just make this a `// compile-pass` test instead. That will accomplish my main goal of insuring that this code will continue to compile regardess of how the diagnostic output changes.

File: src/librustc_mir/borrow_check/mod.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/mod.rs]: Ah, that's a good point. Thinking about this a little more, the check I've added here is way overkill and checks lots of locations when it doesn't need to. I've updated it so that it does the following:

- If `self` is in the same block as `other`, then check if `self` has a smaller statement index than `other`. If it does, `self` is a predecessor and we can return `true`.
- If `self` is in a different block than other, then all we need to do is check if `self.block` is one of the predecessor blocks of `other`. If it is, return `true`.

This is now linear over the no. of predecessor basic blocks rather than predecessor locations, if I'm not mistaken.

File: src/test/ui/nll/issue-55651.rs (hunk 3 above)
Comment (davidtwco) [reply src/test/ui/nll/issue-55651.rs]: Fixed.

File: src/librustc_mir/borrow_check/mod.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_mir/borrow_check/mod.rs]: great, thanks for your diligence on this!

**Comment by pnkfelix** [comment]
I accidentally beta-nominated this.

But for the record, It does *not* need to be backported, for two reasons:

 1. NLL migration mode means that NLL-complete things (apart from ICEs) should not cause problems for the 2018 edition
 2. It is a bug with how we were dealing with unions. But `untagged_unions` are not stabilized, so bugs with our treatment of them should not affect stable code.
