### PR TITLE
 Do not suggest incorrect syntax on pattern type error due to borrow

### LINKED ISSUE #55174: Error message help suggests type ascription on pattern binding
Here's the minimal reproduction:

```rust
fn main() {
    let x = vec![1i32];
    match &x[..] {
        [&v] => {},
        _ => {},
    }
}
```

This produces the following error:

```
error[E0308]: mismatched types
 --> src/main.rs:4:10
  |
4 |         [&v] => {},
  |          ^^ expected i32, found reference
  |
  = note: expected type `i32`
             found type `&_`
  = help: did you mean `v: &i32`?
```

The error rightly points out that we are matching a reference when we actually have the full value itself.

The problem is the help message at the bottom:

```
help: did you mean `v: &i32`?
```

You can't annotate the type of a variable bound in a pattern, so trying this ends up with a syntax error:

```
error: expected one of `,`, `..`, or `@`, found `:`
 --> src/main.rs:4:12
  |
4 |         [&v: &i32] => {},
  |            ^ expected one of `,`, `..`, or `@` here

error: aborting due to previous error
```

That help message should probably not show up in patterns at all.

### PR DESCRIPTION
**Pull request by estebank**
Fix #55174.

### CODE REVIEW

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                        }) |
+                                        hir::Node::ForeignItem(hir::ForeignItem {
+                                            node: hir::ForeignItemKind::Fn(..), ..
+                                        }) |
+                                        hir::Node::TraitItem(hir::TraitItem {
+                                            node: hir::TraitItemKind::Method(..), ..
+                                        }) |
+                                        hir::Node::ImplItem(hir::ImplItem {
+                                            node: hir::ImplItemKind::Method(..), ..
+                                        }) => { // this pat is likely an argument
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: The comment is easy to miss here; I'd suggest putting it either inside the block (move down) or before the arm itself.

File: src/librustc_typeck/check/_match.rs [hunk 2]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                            if let Ok(snippet) = tcx.sess.source_map()
+                                                .span_to_snippet(inner.span)
+                                            { // FIXME: turn into structured suggestion, will need
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: That you had to put the comment in this way suggests that the indentation is too high...

File: src/librustc_typeck/check/_match.rs [hunk 3]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                             // `fn foo(foo: &u32)`
                             if let Some(mut err) = err {
                                 if let PatKind::Binding(..) = inner.node {
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: Everything from here...

File: src/librustc_typeck/check/_match.rs [hunk 4]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                            {
+                                                err.span_suggestion(
+                                                    pat.span,
+                                                    "you can probaly remove the explicit borrow",
+                                                    snippet,
+                                                    Applicability::MaybeIncorrect,
+                                                );
+                                            }
+                                        }
+                                        _ => {} // don't provide suggestions in other cases #55175
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: ...to here should imo be extracted into a separate function.

File: src/librustc_typeck/check/_match.rs [hunk 5]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                                );
+                                            }
+                                        }
+                                        hir::Node::Pat(_) => {  // nested `&&pat`
+                                            if let Ok(snippet) = tcx.sess.source_map()
+                                                .span_to_snippet(inner.span)
+                                            {
+                                                err.span_suggestion(
+                                                    pat.span,
+                                                    "you can probaly remove the explicit borrow",
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]:
```suggestion
                                                    "you can probably remove the explicit borrow",
```

File: src/librustc_typeck/check/_match.rs [hunk 6]
```diff
@@ -378,12 +378,61 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                              // a span that also includes the the arg's type.
+                                                err.help(&format!(
+                                                    "did you mean `{}: &{}`?",
+                                                    snippet,
+                                                    expected,
+                                                ));
+                                            }
+                                        }
+                                        hir::Node::Expr(hir::Expr {
+                                            node: hir::ExprKind::Match(..), ..
```
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: Presumably this will also impact `if let`... if so, can you extend the tests below to account for that?

File: src/librustc_typeck/check/_match.rs (hunk 4 above)
Comment (Centril) [inline src/librustc_typeck/check/_match.rs]: I'd also put the comment here on the arm since that looks more readable when scrolling down.

File: src/librustc_typeck/check/_match.rs (hunk 6 above)
Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: `if let` desugars to `hir::ExprKind::Match`, so it is handled here.

Comment (Centril) [reply src/librustc_typeck/check/_match.rs]: Sure; [I know](https://github.com/rust-lang/rust/pull/59288) ;) -- but I didn't see any test that exercised the behavior for `if let`. I think it's not a good testing methodology to assume the implementation strategy (e.g. that `if let` is desugared to `match`) in your tests. It is entirely possible that `if let` stops being desugared to `match` one day if e.g. we have `hir::ExprKind::Let` + `hir::ExprKind::If`.

Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: I read too quickly and I thought you meant it wasn't handled, my bad ^_^

Added in last commit.

Comment (Centril) [reply src/librustc_typeck/check/_match.rs]: Hehe =P Thanks!

File: src/test/ui/suggestions/match-ergonomics.stderr [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+
+error[E0308]: mismatched types
+  --> $DIR/match-ergonomics.rs:29:9
+   |
+LL |         &v => {},
+   |         ^^ expected i32, found reference
+   |
+   = note: expected type `i32`
+              found type `&_`
+help: you can rely on match ergonomics and remove the explicit borrow
```
Comment (oli-obk) [inline src/test/ui/suggestions/match-ergonomics.stderr]: this hint seems odd to me. `y` is an `i32`, so that match will not be doing any match ergonomics. This could just have the same suggestion as the other places with too many references ("you can probably remove the explicit borrow")

Comment (estebank) [reply src/test/ui/suggestions/match-ergonomics.stderr]: Done
