### PR TITLE
Use `EvaluatedToOkModuloRegions` whenever we erase regions

### LINKED ISSUE #80691: Trait predicate evaluation cache incorrectly handles EvaluatedToOk
Split out from the discussion in https://github.com/rust-lang/rust/issues/80336. See https://github.com/rust-lang/rust/issues/80336#issuecomment-750832566 for the original comments.

------

The issue is caused by the way that we handle regions in the evaluation cache. When we insert a result into the evaluation cache (either `infcx.evaluation_cache` or `tcx.evaluation_cache`, we use a 'freshened' version of the original `TraitPredicate` as the key. The 'freshened' `TraitPredicate` has all non-late-bound regions erased.

Unfortunately, this can lead to issues if we try to evaluate the following two predicates:

```rust
impl SomeTrait for SomeType<'static>

SomeType<'static> as SomeTrait
SomeType<'#_r> as SomeTrait
```

When we evaluate `SomeType<'static> as SomeTrait`, we'll get `EvaluatedToOk`, since the region parameter in our trait ref is known to match the impl. We will then cache the result as `<SomeType<'erased> as SomeTrait> -> EvaluatedToOk`.

If we later try to evaluate `SomeType<'#_r> as SomeTrait`, we will end up matching the evaluation cache entry, giving us a result of `EvaluatedToOk`. However, we *should* have gotten a result of `EvaluatedToOkModuloRegions`, since we don't know that `'#_r == 'static` holds.

This is really difficult to observe in practice, for a number of reasons:

* The relevant trait predicates need to get *evaluated*, not just registered in a `FulfillmentContext`.
* Trait evaluation usually goes through the `evaluate_obligation` query, which canonicalizes the regions in the input trait ref. To end up trying to evaluate `SomeType<'static> as SomeTrait`, we need to end up calling `evaluate_predicate_recursively` on it, with a *different* original trait ref used in the original query.
* Using `EvaluatedToOkModuloRegions` instead of `EvaluatedToOk` only seems to cause an error when it results in the incremental hash changing (I don't know if it's possible to weaponize this into extending a lifetime).

As a result, I haven't been able to minimize this.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #80691

When we evaluate a trait predicate, we convert an
`EvaluatedToOk` result to `EvaluatedToOkModuloRegions` if we erased any
regions. We cache the result under a region-erased 'freshened'
predicate, so `EvaluatedToOk` may not be correct for other predicates
that have the same cache key.

### CODE REVIEW

**Comment by Aaron1011** [comment]
cc @nikomatsakis @eddyb @matthewjasper

**Comment by jackh726** [comment]
This makes sense to me. Am I correct in that this should only cause us to not be able to cache things that we were before? (I.e. we could be more conservative here than we need and its fine; it's only going the other way that we have to be extra careful). I haven't really looked at this code, so I don't know what the effect of module regions or not.

**Comment by Aaron1011** [comment]
> Am I correct in that this should only cause us to not be able to cache things that we were before?

We still cache *something* in every case where we were previously caching - however, we now store `EvaluatedToOkModuloRegions` in some cases where we previously would have stored `EvaluatedToOk`.

> I.e. we could be more conservative here than we need and its fine

That's my understanding, though I'd like to get someone more familiar with this code to confirm that. IIUC, it would be sound to delete `EvaluatedToOk` entirely, and only ever use `EvaluatedToOkModuloRegions` - however, that would be less efficient.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -819,7 +819,27 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                // our result to be correct by *any* choice of original lifetimes,
+                // not just the lifetime choice for this particular (non-erased)
+                // predicate.
+                // See issue #80691
+                let unbound_input_lifetimes = stack
+                    .fresh_trait_ref
+                    .skip_binder()
+                    .substs
+                    .regions()
+                    .any(|r| matches!(r, ty::RegionKind::ReErased));
```
Comment (eddyb) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:837]: Can't types or consts also have erased regions nested in them? Ideally I feel like this should check a type flag - but @nikomatsakis / @matthewjasper would know better.

Comment (Aaron1011) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:837]: That seems right - we would want to catch something like `T as MyTrait<MyType<'erased>>`

**Comment by nikomatsakis** [comment]
Performance seems reasonable.

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -819,7 +819,21 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
         }
 
         match self.candidate_from_obligation(stack) {
-            Ok(Some(c)) => self.evaluate_candidate(stack, &c),
+            Ok(Some(c)) => {
+                let mut res = self.evaluate_candidate(stack, &c)?;
+                // If we erased any lifetimes, then we want to use
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:824]: Two things are holding me up on this PR:

1. Is this the right place for this, as opposed to (say) within `evaluate_candidate`?
2. Do we not have a test case?

Comment (Aaron1011) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:824]: This is the only place that calls `evaluate_candidate`, so I think either places could work.

@ld has [done some work on minimizing this](https://github.com/rust-lang/rust/issues/83226#issuecomment-803064019), but AFAIK we don't yet have a standalone test for this.

Comment (lqd) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:824]: I've since then [reduced chalk](https://github.com/rust-lang/rust/issues/83115#issuecomment-803686837): it's shorter than that one, and without dependencies

Comment (nikomatsakis) [reply compiler/rustc_trait_selection/src/traits/select/mod.rs:824]: Can you move it to `evaluate_candidate` then? I can't imagine who would call `evaluate_candidate` and *not* want this change made. Also, @lqd's minimized issue seems small enough to include. r=me with those changes.

**Comment by rylev** [comment]
@nikomatsakis @Aaron1011 Can you talk a bit more about why the performance regression seems reasonable? A performance hit of 2.8%, while not terrible, is certainly something we would want to discuss before writing off.

**Comment by nikomatsakis** [comment]
@rylev fair! Perhaps my thresholds are off. 

I was motivated to land this mainly because it seemed reasonable and there were a number of problems being reported that it aims to address. However I'd be ok to revert and dig a bit deeper to see if there's an alternate solution with less performance impact.

One question I do have is that I'm not sure what gave rise to those problems, as this doesn't seem to be related to any new change (i.e., this caching logic etc has been in place a long time).

**Comment by Aaron1011** [comment]
> One question I do have is that I'm not sure what gave rise to those problems, as this doesn't seem to be related to any new change (i.e., this caching logic etc has been in place a long time).

I think this issue has always exited - when https://github.com/rust-lang/rust/pull/83007 landed, we started getting ICEs for a lot of issues that were silently causing results to change in incremental compilation.

**Comment by Mark-Simulacrum** [comment]
Yeah, as a correctness fix I think hit here is OK

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust/issues/83115 is now on stable, so nominating this for backport

**Comment by Aaron1011** [comment]
@jonas-schievink: I think the issue people are hitting on stable is https://github.com/rust-lang/rust/issues/83538 (but I'm not sure).

**Comment by jonas-schievink** [comment]
Yeah, I'm also hitting the issue on beta...
