### PR TITLE
Provide suggestions for some moved value errors

### LINKED ISSUE #62112: "use of moved value" diagnostic could suggest reborrow when passing `&mut` to `&mut`
Spawned off of #45142

Consider the following code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f7bb96b5960bb3a6fdaa0c207038f954)):

```rust


struct Events<R>(R);

struct Other;

pub trait Trait<T> { 
    fn handle(value: T) -> Self;
}

// Blanket impl. (If you comment this out, compiler figures out that it
// is passing an `&mut` to a method that must be expecting an `&mut`,
// and injects an auto-reborrow.)
impl<T, U> Trait<U> for T where T: From<U> {
    fn handle(_: U) -> Self { unimplemented!() }
}

impl<'a, R> Trait<&'a mut Events<R>> for Other {
    fn handle(_: &'a mut Events<R>) -> Self { unimplemented!() }
}

fn this_compiles<'a, R>(value: &'a mut Events<R>) {
    for _ in 0..3 {
        Other::handle(&mut *value);
    }
}

fn this_does_not<'a, R>(value: &'a mut Events<R>) {
    for _ in 0..3 {
        Other::handle(      value);
    }
}

fn main() {}
```

Today, this yields the diagnostic:

```
error[E0382]: use of moved value: `value`
  --> src/main.rs:30:29
   |
28 | fn this_does_not<'a, R>(value: &'a mut Events<R>) {
   |                         ----- move occurs because `value` has type `&mut Events<R>`, which does not implement the `Copy` trait
29 |     for _ in 0..3 {
30 |         Other::handle(      value);
   |                             ^^^^^ value moved here, in previous iteration of loop
```

We could do better. For example, the diagnostic could additionally say: 

```
consider writing `Other::handle(&mut *value)` to create a fresh reborrow of `value`.
```

----

Background:

The compiler tries hard to auto-inject `&mut`-reborrows when it makes sense; as a way to create a fresh `&mut` reference to pass into the method invocation, and avoid moving the pre-existing `&mut` reference.

But there are times, often involving generic code, when it cannot automatically inject a reborrow. (After all, there are cases where the intent *is* to move the borrow into some place whose dynamic extent outlives that of the method invocation itself; and the static analysis cannot tell if this was the case at the point where it is deciding whether to insert an `&mut`-reborrow or not.)

This can lead to a diagnostic for the user telling them that they have a used of a moved value.

But new-comers to Rust do not always know about the option of putting in a `&mut`-reborrow themselves.

Our diagnostics could help them here. Even though we choose to not attempt to auto-inject the auto-reborrow in the compiler itself, our diagnostics have enough information about the method signature and the invocation to suggest to the user that they write out the `&mut *value` themselves.

### LINKED ISSUE #63988: Suggest borrowing when doing `if let Some(_)` from non-Copy ADT
Just got this error:

```
error[E0382]: borrow of moved value: `x`
    --> src/librustc_mir/hair/pattern/_match.rs:1614:53
     |
1611 |                         if let Some(range) = x {
     |                                     ----- value moved here
...
1614 |                         debug!("intersection {:?}", x);
     |                                                     ^ value borrowed here after partial move
     |
     = note: move occurs because value has type `hair::pattern::_match::IntRange<'_>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

It should suggest to borrow `x`.

### PR DESCRIPTION
**Pull request by estebank**
When encountering an used moved value where the previous move happened
in a `match` or `if let` pattern, suggest using `ref`. Fix #63988.

When encountering a `&mut` value that is used in multiple iterations of
a loop, suggest reborrowing it with `&mut *`. Fix #62112.

### CODE REVIEW

File: src/librustc_mir/borrow_check/diagnostics/mod.rs [hunk 1]
```diff
@@ -772,7 +776,13 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
         }
 
-        let normal_ret = OtherUse(stmt.source_info.span);
+        let normal_ret = if let [ProjectionElem::Downcast(..), ProjectionElem::Field(_, _)] =
+            moved_place.projection
+        {
+            PatUse(stmt.source_info.span)
+        } else {
+            OtherUse(stmt.source_info.span)
+        };
```
Comment (estebank) [inline src/librustc_mir/borrow_check/diagnostics/mod.rs:785]: I'm really unsure about this, but worked as a placeholder way of accomplishing my goal. If there's a more reliable way of detecting that the move occurs in a pattern, I can change this.

Comment (matthewjasper) [reply src/librustc_mir/borrow_check/diagnostics/mod.rs:785]: The correct (or at least more correct) way to check if this is a pattern binding is to check that:

- This location is an `StatementKind::Assign` of an `Rvalue::Use`
- The assignment is to a user defined local (i.e. `self.body.local_decls[target].is_user_variable()` is true
- The ever initialized flow is false at this point.

Unfortunately the flows aren't available here currently, and changing things so that they are would be a fairly large change (#73552).

I think that if this is going to use an imperfect heuristic that would be fine with a fixme referencing that issue. The condition should be `moved_place.projection.iter().any(|p| matches!(p, ProjectionElem::Downcast)`.

Comment (estebank) [reply src/librustc_mir/borrow_check/diagnostics/mod.rs:785]: Changed to use the imperfect heuristic.

File: src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -212,6 +212,19 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
                             &mut err,
                             format!("variable moved due to use{}", move_spans.describe()),
                         );
+                        if let UseSpans::PatUse(span) = move_spans {
+                            err.span_suggestion_verbose(
+                                span.shrink_to_lo(),
+                                &format!(
+                                    "borrow this field in the pattern to avoid moving {}",
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_mir/borrow_check/diagnostics/conflict_errors.rs:219]: It works correctly with the long field pattern syntax. It does the right thing for `mut x`, but applying the suggestion will cause knock down errors requiring dereferencing `x`. This is fine, but we can't test that with `run-rustfix`. Added tests for these.

**Comment by estebank** [comment]
@bors r=matthewjasper

rebased
