### PR TITLE
delay expand macro bang when there has indeterminate path

### LINKED ISSUE #98291: Adding an attribute to a `macro_export`ed macro and reexporting it incorrectly triggers the macro_expanded_macro_exports_accessed_by_absolute_paths error
I tried this code:

```rust
#[rustfmt::skip]
#[macro_export]
macro_rules! _a {
    () => {
        "Hello world"
    };
}

pub use _a as a;

fn main() {
    println!(a!());
}
```

(https://gist.github.com/jakobrs/8bcaf3448431126005e16ac678f769c5)

I expected to see this happen: The code should compile successfully.

Instead, this happened: The `macro_expanded_macro_exports_accessed_by_absolute_paths` error is triggered.

<details>
<summary>Full error message</summary>

```
error: cannot determine resolution for the macro `a`
  --> ./b.rs:12:14
   |
12 |     println!(a!());
   |              ^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
 --> ./b.rs:9:9
  |
9 | pub use _a as a;
  |         ^^^^^^^
  |
  = note: `#[deny(macro_expanded_macro_exports_accessed_by_absolute_paths)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #52234 <https://github.com/rust-lang/rust/issues/52234>
note: the macro is defined here
 --> ./b.rs:3:1
  |
3 | / macro_rules! _a {
4 | |     () => {
5 | |         "Hello world"
6 | |     };
7 | | }
  | |_^

error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
  --> ./b.rs:12:14
   |
12 |     println!(a!());
   |              ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #52234 <https://github.com/rust-lang/rust/issues/52234>
note: the macro is defined here
  --> ./b.rs:3:1
   |
3  | / macro_rules! _a {
4  | |     () => {
5  | |         "Hello world"
6  | |     };
7  | | }
   | |_^

error: aborting due to 3 previous errors
```
</details>

### Meta
This happens with Rust 1.60, 1.61 and nightly (bb8c2f411 2022-06-19)
`rustc --version --verbose`:
```
# Nightly

rustc 1.63.0-nightly (bb8c2f411 2022-06-19)
binary: rustc
commit-hash: bb8c2f41174caceec00c28bc6c5c20ae9f9a175c
commit-date: 2022-06-19
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5

# Stable

rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Related #98291

I will attempt to clarify the root problem through several examples:

Firstly, 

```rs
// rustc code.rs --edition=2018

macro_rules! wrap {
    () => {
        macro_rules! _a {
            () => {
                "Hello world"
            };
        }
    };
}

wrap!();

use _a as a;

fn main() {
    format_args!(_a!());
}
```

The above case will compile successfully because `_a` is defined after the `wrap` expaned, ensuring `_a` can be resolved without any issues.

And,

```rs
// rustc code.rs --edition=2018

macro_rules! wrap {
    () => {
        macro_rules! _a {
            () => {
                "Hello world"
            };
        }
    };
}

wrap!();

use _a as a;

fn main() {
    format_args!("{}", a!());
}
```

The above example will also compile successfully because the `parse_args` in `expand_format_args_impl` will return a value `MacroInput { fmtstr: Expr::Lit::Str, args: [Expr::MacroCall]}`. Since the graph for `args` will be build lately, `a` will eventually be resolved.

However, in the case of:

```rs
// rustc code.rs --edition=2018

macro_rules! wrap {
    () => {
        macro_rules! _a {
            () => {
                "Hello world"
            };
        }
    };
}

wrap!();

use _a as a;

fn main() {
    format_args!(a!());
}
```

The result of `parse_args` is `MacroInput {fmtstr: Expr::Lit::Macro, args: [] }`, we attempt to expand `fmtstr` **eagerly** within `expr_to_spanned_string`. Although we have recorded `(root, _a)` into resolutions, `use _a as a` is an indeterminate import, which will not try to resolve under the conditions of `expander.monotonic = false`.

Therefore, I've altered the strategy for resolving indeterminate imports, ensuring it will also resolve during eager expansion. This could be a significant change to the resolution infra. However, I think it's acceptable if the goal of avoiding resolution under eager expansion is to save time.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
The right strategy here is for `println!` (and other similar macros) to do what `#[cfg_accessible(path)]` currently does
- Attempt to resolve `a` (or rather attempt to expand `a!()`)
- If the attempt returns indeterminacy, then `println!` should return indeterminacy as well (`ExpandResult::Retry`)
- After that `println!` will return into the queue of unexpanded macros and we will try to expand it again some time later, when the resolution for `use _a as a` may already be available.

**Comment by petrochenkov** [comment]
What this PR does may be helpful too, but it's sort of luck based.
We try to resolve imports one last time just before eagerly expanding a macro, and if it helps, then it helps, but if it's not (the necessary import is not yet read) then we are back to the same issue.

Let's actually try to benchmark this solution.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
So, the current approach clearly won't work.
@rustbot author

**Comment by bvanjoi** [comment]
Update: It will retry expand for `macro_rules!` when an indeterminate path is encountered

**Comment by bvanjoi** [comment]
ci is green. @rustbot ready

File: compiler/rustc_builtin_macros/src/compile_error.rs [hunk 1]
```diff
@@ -1,22 +1,28 @@
 // The compiler code necessary to support the compile_error! extension.
 
 use rustc_ast::tokenstream::TokenStream;
-use rustc_expand::base::{get_single_str_from_tts, DummyResult, ExtCtxt, MacResult};
+use rustc_expand::base::{
+    get_single_str_from_tts, DummyResult, ExpandResult, ExtCtxt, MacroExpanderResult,
+};
```
Comment (petrochenkov) [inline compiler/rustc_builtin_macros/src/compile_error.rs:6]: Style nit: could you keep the single-line import style here and in other places?

File: compiler/rustc_builtin_macros/src/format.rs [hunk 2]
```diff
@@ -160,54 +161,61 @@ fn make_format_args(
...
-                                _ => format!("{}{{}}", "{} ".repeat(args.explicit_args().len())),
-                            };
-                            err.span_suggestion(
-                                unexpanded_fmt_span.shrink_to_lo(),
-                                "you might be missing a string literal to format with",
-                                format!("\"{sugg_fmt}\", "),
-                                Applicability::MaybeIncorrect,
-                            );
+    let (fmt_str, fmt_style, fmt_span) = {
+        let ExpandResult::Ready(mac) = expr_to_spanned_string(ecx, efmt.clone(), msg) else {
```
Comment (petrochenkov) [inline compiler/rustc_builtin_macros/src/format.rs:171]: Why is it inside the block?

File: compiler/rustc_builtin_macros/src/cfg.rs [hunk 3]
```diff
@@ -8,17 +8,17 @@ use rustc_ast::token;
...
 pub fn expand_cfg(
     cx: &mut ExtCtxt<'_>,
     sp: Span,
     tts: TokenStream,
-) -> Box<dyn MacResult + 'static> {
+) -> MacroExpanderResult<'static> {
     let sp = cx.with_def_site_ctxt(sp);
 
-    match parse_cfg(cx, sp, tts) {
+    let res = match parse_cfg(cx, sp, tts) {
```
Comment (petrochenkov) [inline compiler/rustc_builtin_macros/src/cfg.rs:21]:
```suggestion
    ExpandResult::Ready(match parse_cfg(cx, sp, tts) {
```
Style nit: can just wrap whole matches into this, without separate variables, this shouldn't change formatting.
This is relevant here and in many other places.

File: compiler/rustc_builtin_macros/src/log_syntax.rs [hunk 4]
```diff
@@ -1,14 +1,14 @@
...
 use rustc_ast_pretty::pprust;
-use rustc_expand::base;
+use rustc_expand::base::{self, ExpandResult};
 
 pub fn expand_log_syntax<'cx>(
     _cx: &'cx mut base::ExtCtxt<'_>,
     sp: rustc_span::Span,
     tts: TokenStream,
-) -> Box<dyn base::MacResult + 'cx> {
+) -> base::MacroExpanderResult<'cx> {
```
Comment (petrochenkov) [inline compiler/rustc_builtin_macros/src/log_syntax.rs:9]:
```suggestion
) -> MacroExpanderResult<'cx> {
```
Could you import `ExpandResult` and `MacroExpanderResult` consistently in all places?

File: compiler/rustc_expand/src/base.rs [hunk 5]
```diff
@@ -1264,17 +1287,23 @@ pub fn expr_to_spanned_string<'a>(
...
+    if let ast::ExprKind::MacCall(m) = &expr.kind
+        && !cx.force_mode
+        && cx.resolver.cfg_accessible(cx.current_expansion.id, &m.path).is_err()
+    {
+        return ExpandResult::Retry(());
+    }
+
     // Perform eager expansion on the expression.
     // We want to be able to handle e.g., `concat!("foo", "bar")`.
     let expr = cx.expander().fully_expand_fragment(AstFragment::Expr(expr)).make_expr();
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/base.rs:1300]: Ideally, the whole `fully_expand_fragment` would return Ready/Retry, but that's probably a much larger change.
The logic above is a good enough approximation.

File: compiler/rustc_expand/src/base.rs [hunk 6]
```diff
@@ -1264,17 +1287,23 @@ pub fn expr_to_spanned_string<'a>(
...
     expr: P<ast::Expr>,
     err_msg: &'static str,
-) -> Result<
-    (Symbol, ast::StrStyle, Span),
-    Result<(Diag<'a>, bool /* has_suggestions */), ErrorGuaranteed>,
-> {
+) -> ExpandResult<ExprToSpannedStringResult<'a>, ()> {
+    if let ast::ExprKind::MacCall(m) = &expr.kind
+        && !cx.force_mode
+        && cx.resolver.cfg_accessible(cx.current_expansion.id, &m.path).is_err()
```
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_expand/src/base.rs:1293]: `cfg_accessible` will search `m.path` in all namespaces, but we only need the macro namespace, so `cfg_accessible` may return `Ok` in more cases than we need.

File: compiler/rustc_expand/src/base.rs [hunk 7]
```diff
@@ -1264,17 +1287,23 @@ pub fn expr_to_spanned_string<'a>(
     cx: &'a mut ExtCtxt<'_>,
     expr: P<ast::Expr>,
     err_msg: &'static str,
-) -> Result<
-    (Symbol, ast::StrStyle, Span),
-    Result<(Diag<'a>, bool /* has_suggestions */), ErrorGuaranteed>,
-> {
+) -> ExpandResult<ExprToSpannedStringResult<'a>, ()> {
+    if let ast::ExprKind::MacCall(m) = &expr.kind
+        && !cx.force_mode
```
Comment (petrochenkov) [inline compiler/rustc_expand/src/base.rs:1292]: Nit: cheaper condition usually goes first.

File: compiler/rustc_builtin_macros/src/format.rs (hunk 2 above)
Comment (bvanjoi) [reply compiler/rustc_builtin_macros/src/format.rs:171]: It aims to bypass the borrow checker. [﻿Diag<'a>](https://github.com/rust-lang/rust/blob/master/compiler/rustc_expand/src/base.rs#L1269) will borrow the `﻿&mut exc`, which will be used later, thus allowing this block to manage the drop.

File: compiler/rustc_resolve/src/macros.rs [hunk 8]
```diff
@@ -960,4 +935,46 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         let ItemKind::MacroDef(def) = &item.kind else { unreachable!() };
         MacroData { ext: Lrc::new(ext), rule_spans, macro_rules: def.macro_rules }
     }
+
+    fn accessible(
+        &mut self,
+        expn_id: LocalExpnId,
+        path: &ast::Path,
+        namespaces: &[Namespace],
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:943]: I think it would be fine to add this argument to `cfg_accessible` instead of introducing a new separate function.

Just need to rename it to something like `path_accessible`.

**Comment by petrochenkov** [comment]
r=me with https://github.com/rust-lang/rust/pull/121589#discussion_r1521886941 addressed.

File: compiler/rustc_resolve/src/macros.rs (hunk 8 above)
Comment (bvanjoi) [reply compiler/rustc_resolve/src/macros.rs]: These changes have had some impact: both `﻿rustc_builtin_macros` and ﻿`rustc_expand` had to incorporate `﻿rustc_hir`, where ﻿`enum Namespace` is located.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs]: Ah, *that*'s why there were two methods, I see.

I'd rather move `enum Namespace` to some common dependency of `rustc_expand` and `rustc_hir`, but I don't see a good place for it.
Let's keep two methods then, dependency on `rustc_hir` will slow down pipelined builds.

File: compiler/rustc_resolve/src/macros.rs [hunk 9]
```diff
@@ -422,42 +422,43 @@ impl<'a, 'tcx> ResolverExpand for Resolver<'a, 'tcx> {
...
         path: &ast::Path,
+        namespaces: &[Namespace],
     ) -> Result<bool, Indeterminate> {
         let span = path.span;
         let path = &Segment::from_path(path);
         let parent_scope = self.invocation_parent_scopes[&expn_id];
 
         let mut indeterminate = false;
-        for ns in [TypeNS, ValueNS, MacroNS].iter().copied() {
+        for ns in namespaces.iter().copied() {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:440]:
```suggestion
        for &ns in namespaces {
```

**Comment by petrochenkov** [comment]
Thanks!
Fixing this was in my todo list for quite some time.
@bors r+
