### PR TITLE
error on alignments greater than `isize::MAX`

### LINKED ISSUE #131122: ICE: "Unsigned value 0x10000 does not fit in 16 bits" with `#[repr(align(65536))]` on 16-bit target in release mode, different ICE in debug mode.
### Code

```Rust
// lib.rs
#![no_std]

#[repr(align(65536))]
struct Hello;

pub fn bar() -> usize { core::mem::align_of::<Hello>() }
```

Compile with `cargo +nightly build -Z build-std=core --target avr-unknown-gnu-atmega328 --release` (basically the same results with `--target msp430-none-elf`, also a 16-bit tier 3 target)

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (fb4aebddd 2024-09-30)
binary: rustc
commit-hash: fb4aebddd18d258046ddb51fd41589295259a0fa
commit-date: 2024-09-30
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

[rustc-ice-2024-10-02T01_00_03-507058.txt](https://github.com/user-attachments/files/17218528/rustc-ice-2024-10-02T01_00_03-507058.txt)

```
$ cargo +nightly build -Z build-std=core --target avr-unknown-gnu-atmega328 --release
   Compiling compiler_builtins v0.1.130
   Compiling core v0.0.0 (/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling avr-testing v0.1.0 (/tmp/avr-testing)
error: internal compiler error: /rustc/fb4aebddd18d258046ddb51fd41589295259a0fa/compiler/rustc_middle/src/mir/interpret/value.rs:139:32: Unsigned value 0x10000 does not fit in 16 bits

thread 'rustc' panicked at /rustc/fb4aebddd18d258046ddb51fd41589295259a0fa/compiler/rustc_middle/src/mir/interpret/value.rs:139:32:
Box<dyn Any>
stack backtrace:
   0:     0x7b30d60dbf7a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h700a654fe77e1f9c
   1:     0x7b30d68033e6 - core::fmt::write::ha8ac3a5009e0941e
   2:     0x7b30d79bcb51 - std::io::Write::write_fmt::h280500187b8ab992
   3:     0x7b30d60dbdd2 - std::sys::backtrace::BacktraceLock::print::h5b5702bc7edef58d
   4:     0x7b30d60de2f1 - std::panicking::default_hook::{{closure}}::h7c4c08203556436f
   5:     0x7b30d60de124 - std::panicking::default_hook::h4a5c0931e8301a2f
   6:     0x7b30d51a2d7f - std[170610031590a965]::panicking::update_hook::<alloc[66d4c008c69e86cd]::boxed::Box<rustc_driver_impl[26aaba0b9f674e85]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7b30d60dea08 - std::panicking::rust_panic_with_hook::hf9da426777cf33fb
   8:     0x7b30d51dcf11 - std[170610031590a965]::panicking::begin_panic::<rustc_errors[2b9f4ebbc725b026]::ExplicitBug>::{closure#0}
   9:     0x7b30d51cffb6 - std[170610031590a965]::sys::backtrace::__rust_end_short_backtrace::<std[170610031590a965]::panicking::begin_panic<rustc_errors[2b9f4ebbc725b026]::ExplicitBug>::{closure#0}, !>
  10:     0x7b30d51cb499 - std[170610031590a965]::panicking::begin_panic::<rustc_errors[2b9f4ebbc725b026]::ExplicitBug>
  11:     0x7b30d51e67a1 - <rustc_errors[2b9f4ebbc725b026]::diagnostic::BugAbort as rustc_errors[2b9f4ebbc725b026]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7b30d580cbd4 - rustc_middle[1155dac776b01d50]::util::bug::opt_span_bug_fmt::<rustc_span[d0163105bd3f350c]::span_encoding::Span>::{closure#0}
  13:     0x7b30d57f295a - rustc_middle[1155dac776b01d50]::ty::context::tls::with_opt::<rustc_middle[1155dac776b01d50]::util::bug::opt_span_bug_fmt<rustc_span[d0163105bd3f350c]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7b30d57f27eb - rustc_middle[1155dac776b01d50]::ty::context::tls::with_context_opt::<rustc_middle[1155dac776b01d50]::ty::context::tls::with_opt<rustc_middle[1155dac776b01d50]::util::bug::opt_span_bug_fmt<rustc_span[d0163105bd3f350c]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7b30d2dcd620 - rustc_middle[1155dac776b01d50]::util::bug::bug_fmt
  16:     0x7b30d72213ae - <rustc_mir_transform[de8989103c0dc9d3]::gvn::VnState>::insert
  17:     0x7b30d721479c - <rustc_mir_transform[de8989103c0dc9d3]::gvn::VnState>::simplify_rvalue
  18:     0x7b30d3ed1674 - <rustc_mir_transform[de8989103c0dc9d3]::gvn::GVN as rustc_mir_transform[de8989103c0dc9d3]::pass_manager::MirPass>::run_pass
  19:     0x7b30d680b98d - rustc_mir_transform[de8989103c0dc9d3]::pass_manager::run_passes_inner
  20:     0x7b30d71c8262 - rustc_mir_transform[de8989103c0dc9d3]::optimized_mir
  21:     0x7b30d71c6b1d - rustc_query_impl[180b75f2ddc39270]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[180b75f2ddc39270]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 8usize]>>
  22:     0x7b30d682f438 - rustc_query_system[9f857c887a67b714]::query::plumbing::try_execute_query::<rustc_query_impl[180b75f2ddc39270]::DynamicConfig<rustc_query_system[9f857c887a67b714]::query::caches::DefIdCache<rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[180b75f2ddc39270]::plumbing::QueryCtxt, false>
  23:     0x7b30d682e9f3 - rustc_query_impl[180b75f2ddc39270]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7b30d6831816 - rustc_middle[1155dac776b01d50]::query::plumbing::query_get_at::<rustc_query_system[9f857c887a67b714]::query::caches::DefIdCache<rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 8usize]>>>
  25:     0x7b30d3f7c414 - rustc_mir_transform[de8989103c0dc9d3]::cross_crate_inline::cross_crate_inlinable
  26:     0x7b30d6b85005 - rustc_query_impl[180b75f2ddc39270]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[180b75f2ddc39270]::query_impl::cross_crate_inlinable::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 1usize]>>
  27:     0x7b30d6b833cb - rustc_query_system[9f857c887a67b714]::query::plumbing::try_execute_query::<rustc_query_impl[180b75f2ddc39270]::DynamicConfig<rustc_query_system[9f857c887a67b714]::query::caches::DefIdCache<rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[180b75f2ddc39270]::plumbing::QueryCtxt, false>
  28:     0x7b30d6b82f8a - rustc_query_impl[180b75f2ddc39270]::query_impl::cross_crate_inlinable::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7b30d71beb04 - rustc_passes[7a90872e0502ca71]::reachable::recursively_reachable
  30:     0x7b30d696b537 - rustc_passes[7a90872e0502ca71]::reachable::reachable_set
  31:     0x7b30d76808b8 - rustc_query_impl[180b75f2ddc39270]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[180b75f2ddc39270]::query_impl::reachable_set::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7b30d767f2b9 - rustc_query_system[9f857c887a67b714]::query::plumbing::try_execute_query::<rustc_query_impl[180b75f2ddc39270]::DynamicConfig<rustc_query_system[9f857c887a67b714]::query::caches::SingleCache<rustc_middle[1155dac776b01d50]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[180b75f2ddc39270]::plumbing::QueryCtxt, false>
  33:     0x7b30d767fade - rustc_query_impl[180b75f2ddc39270]::query_impl::reachable_set::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7b30d6f5e2a8 - <rustc_metadata[a1e01f1b85ceac18]::rmeta::encoder::EncodeContext>::encode_crate_root
  35:     0x7b30d7812393 - rustc_metadata[a1e01f1b85ceac18]::rmeta::encoder::encode_metadata
  36:     0x7b30d781a814 - rustc_metadata[a1e01f1b85ceac18]::fs::encode_and_write_metadata
  37:     0x7b30d7819603 - <rustc_interface[67c5fa7b03b13b84]::queries::Linker>::codegen_and_build_linker
  38:     0x7b30d750950b - rustc_interface[67c5fa7b03b13b84]::interface::run_compiler::<core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>, rustc_driver_impl[26aaba0b9f674e85]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7b30d7629650 - std[170610031590a965]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[67c5fa7b03b13b84]::util::run_in_thread_with_globals<rustc_interface[67c5fa7b03b13b84]::util::run_in_thread_pool_with_globals<rustc_interface[67c5fa7b03b13b84]::interface::run_compiler<core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>, rustc_driver_impl[26aaba0b9f674e85]::run_compiler::{closure#0}>::{closure#1}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>::{closure#0}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>
  40:     0x7b30d7629cba - <<std[170610031590a965]::thread::Builder>::spawn_unchecked_<rustc_interface[67c5fa7b03b13b84]::util::run_in_thread_with_globals<rustc_interface[67c5fa7b03b13b84]::util::run_in_thread_pool_with_globals<rustc_interface[67c5fa7b03b13b84]::interface::run_compiler<core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>, rustc_driver_impl[26aaba0b9f674e85]::run_compiler::{closure#0}>::{closure#1}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>::{closure#0}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d68a251df926a28b]::result::Result<(), rustc_span[d0163105bd3f350c]::ErrorGuaranteed>>::{closure#1} as core[d68a251df926a28b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7b30d762a0ab - std::sys::pal::unix::thread::Thread::new::thread_start::h5cf1ac2878833c32
  42:     0x7b30d189ca94 - start_thread
                               at ./nptl/pthread_create.c:447:8
  43:     0x7b30d1929c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  44:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/avr-testing/rustc-ice-2024-10-02T01_00_03-507058.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C strip=debuginfo -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `bar`
#1 [cross_crate_inlinable] whether the item should be made inlinable across crates
end of query stack
error: could not compile `avr-testing` (lib)

Caused by:
  process didn't exit successfully: `/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name avr_testing --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=180 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=10bbcaf4572e942c -C extra-filename=-10bbcaf4572e942c --out-dir /home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps --target avr-unknown-gnu-atmega328 -C strip=debuginfo -L dependency=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps -L dependency=/home/zachary/opt_mount/zachary/cargo-target/release/deps --extern 'noprelude:compiler_builtins=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps/libcompiler_builtins-7fd167500327228b.rmeta' --extern 'noprelude:core=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps/libcore-fa3c34da63eafa79.rmeta' -Z unstable-options` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo +nightly build -Z build-std=core --target avr-unknown-gnu-atmega328 --release
   Compiling compiler_builtins v0.1.130
   Compiling core v0.0.0 (/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling avr-testing v0.1.0 (/tmp/avr-testing)
error: internal compiler error: /rustc/fb4aebddd18d258046ddb51fd41589295259a0fa/compiler/rustc_middle/src/mir/interpret/value.rs:139:32: Unsigned value 0x10000 does not fit in 16 bits

thread 'rustc' panicked at /rustc/fb4aebddd18d258046ddb51fd41589295259a0fa/compiler/rustc_middle/src/mir/interpret/value.rs:139:32:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: <rustc_mir_transform::gvn::VnState>::insert
   7: <rustc_mir_transform::gvn::VnState>::simplify_rvalue
   8: <rustc_mir_transform::gvn::GVN as rustc_mir_transform::pass_manager::MirPass>::run_pass
   9: rustc_mir_transform::pass_manager::run_passes_inner
  10: rustc_mir_transform::optimized_mir
      [... omitted 1 frame ...]
  11: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
  12: rustc_mir_transform::cross_crate_inline::cross_crate_inlinable
      [... omitted 1 frame ...]
  13: rustc_passes::reachable::recursively_reachable
  14: rustc_passes::reachable::reachable_set
      [... omitted 1 frame ...]
  15: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  16: rustc_metadata::rmeta::encoder::encode_metadata
  17: rustc_metadata::fs::encode_and_write_metadata
  18: <rustc_interface::queries::Linker>::codegen_and_build_linker
  19: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/avr-testing/rustc-ice-2024-10-02T01_02_44-507394.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C strip=debuginfo -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `bar`
#1 [cross_crate_inlinable] whether the item should be made inlinable across crates
#2 [reachable_set] reachability
end of query stack
error: could not compile `avr-testing` (lib)

Caused by:
  process didn't exit successfully: `/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name avr_testing --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=180 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=10bbcaf4572e942c -C extra-filename=-10bbcaf4572e942c --out-dir /home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps --target avr-unknown-gnu-atmega328 -C strip=debuginfo -L dependency=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps -L dependency=/home/zachary/opt_mount/zachary/cargo-target/release/deps --extern 'noprelude:compiler_builtins=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps/libcompiler_builtins-7fd167500327228b.rmeta' --extern 'noprelude:core=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/release/deps/libcore-fa3c34da63eafa79.rmeta' -Z unstable-options` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

</p>
</details>

-----

If you remove `--release` (and do `[profile.dev.packages."*"] opt-level = 3` to make `core` not run out of registers when compiling), then you get a different ICE:

[rustc-ice-2024-10-02T01_15_57-511791.txt](https://github.com/user-attachments/files/17218621/rustc-ice-2024-10-02T01_15_57-511791.txt)
<details><summary><strong>Error output</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo +nightly build -Z build-std=core --target avr-unknown-gnu-atmega328 
   Compiling avr-testing v0.1.0 (/tmp/avr-testing)
thread 'rustc' panicked at compiler/rustc_codegen_llvm/src/common.rs:170:13:
assertion failed: i < (1 << bit_size)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_codegen_ssa::mir::FunctionCx<rustc_codegen_llvm::builder::Builder>>::codegen_rvalue_operand
   4: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::Builder>
   5: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   6: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
   7: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
   8: <rustc_interface::queries::Linker>::codegen_and_build_linker
   9: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/avr-testing/rustc-ice-2024-10-02T01_15_57-511791.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `avr-testing` (lib)

Caused by:
  process didn't exit successfully: `/home/zachary/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name avr_testing --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=180 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=ee58599ee021bb48 -C extra-filename=-ee58599ee021bb48 --out-dir /home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/debug/deps --target avr-unknown-gnu-atmega328 -C incremental=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/debug/incremental -L dependency=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/debug/deps -L dependency=/home/zachary/opt_mount/zachary/cargo-target/debug/deps --extern 'noprelude:compiler_builtins=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/debug/deps/libcompiler_builtins-c8a0592a6a11b0cd.rmeta' --extern 'noprelude:core=/home/zachary/opt_mount/zachary/cargo-target/avr-unknown-gnu-atmega328/debug/deps/libcore-3761d8d6676445dc.rmeta' -Z unstable-options` (exit status: 101)
```

</details>

-----

Note that if you remove `pub fn bar` or make it non-`pub` it compiles.

`#[repr(align(1 << N))]` or higher should probably just give an unconditional error on (<N)-bit targets (or maybe just anything that would determine its layout could error, similar to how `core::mem::size_of::<[u8; 0x1_0000_0000_0000]>()` fails to compile with "values of the type `[u8; 281474976710656]` are too big for the current architecture" on x86_64-unknown-linux-gnu, but `type T = [u8; 0x1_0000_0000_0000];` alone is Fine™).

### PR DESCRIPTION
**Pull request by asquared31415**
Fixes #131122

On zulip someone had a concern that it was legal to create a type with alignment `isize::MAX + 1`, but I do not believe this should be allowed for `repr(align)`, as `repr(align)` also increases the *size* of the type, and that would be larger than the maximum allowed size of objects.

(cc @workingjubilee #131276)

### CODE REVIEW

File: compiler/rustc_passes/src/check_attr.rs [hunk 1]
```diff
@@ -1796,6 +1797,22 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
                             );
                         }
                     }
+
+                    // UNWRAP: parsing the attribute already ensured that it had a name and integer value
+                    // that is a power of 2 and less than 2^29
+                    let (_, value) = hint.singleton_lit_list().unwrap();
```
Comment (jieyouxu) [inline compiler/rustc_passes/src/check_attr.rs:1803]: Suggestion:

```rs
let Some((_, value)) = hint.singleton_lit_list() else {
    bug!("parsing already checked for pow(2) and < 2^29");
};
```

Comment (asquared31415) [reply compiler/rustc_passes/src/check_attr.rs:1803]: turns out this code *is* reachable after all, not sure why i didn't hit it in testing locally.  i can just ignore cases where it's malformed though, as an error will have already been emitted.

**Comment by asquared31415** [comment]
"test compilation failed even though it shouldn't"... but it's a `build-fail` test???

**Comment by jieyouxu** [comment]
> "test compilation failed even though it shouldn't"... but it's a `build-fail` test???

https://github.com/rust-lang/rust/issues/130894

**Comment by zachs18** [comment]
> as `repr(align)` also increases the size of the type, and that would be larger than the maximum allowed size of objects.

`repr(align)` can be applied to unit/ZST structs without increasing their size, so `#[repr(align(32768))] struct ZST;` is possible on 16-bit targets and currently does not error. (though it might be enough of an edge case to disallow anyway).

```rs
#![no_std]

#[repr(align(32768))]
struct Hello;

pub fn foo() -> usize { core::mem::align_of::<Hello>() }
``` 

This currently compiles fine with `cargo +nightly build -Z build-std=core --target avr-unknown-gnu-atmega328 --release`, but fails on this branch with

```rs
error[E0589]: alignment must not be greater than `isize::MAX` bytes
 --> src/lib.rs:4:8
  |
4 | #[repr(align(32768))]
  |        ^^^^^^^^^^^^
  |
  = note: `isize::MAX` is 32767 for the current target

For more information about this error, try `rustc --explain E0589`.
```

**Comment by workingjubilee** [comment]
cc @Patryk27 as prospective maintainer for AVR
cc @cr1901 because you're the one who comes to mind re: MSP430

Do you think this `#[repr(align(32768))] struct Hello16BitAlign;` has any real use-case on AVR?

Note that you are the **only** targets affected by this, as all other targets have a bound that is already below `isize::MAX`, functionally imposed by our codegen backends.

**Comment by asquared31415** [comment]
ah i see, i was under the impression `repr(align)` increased the size for structs that would otherwise be 1-ZSTs, i can probably add an exception if it's needed then? i do think this is a slightly weird use case, but i'm mostly neutral on this, and dont work with any 16 bit targets for rust to know what they might need.

**Comment by cr1901** [comment]
I've never used Rust on an MSP430 with more than 10kB (8+2kB) of RAM. MSP430's max out at 512kB ROM and 66kB RAM. 

However, from what [I can gather](https://e2e.ti.com/support/microcontrollers/msp-low-power-microcontrollers-group/msp430/f/msp-low-power-microcontroller-forum/406886/reserving-ram-space-beyond-64k/1442521#1442521), actual existing MSP430s top out at 18kB (16+2kB) of RAM without relying on stuff unsupported by LLVM. Given such constraints, `#[repr(align(32768))]` isn't useful in practice.

If LLVM gets these features to access 20-bit addresses, I don't see how I'd use such functionality for RAM; you only have 64kB continguous RAM anyway- the other 2kB is a ~~marketing gimmick~~ "bonus" if you're not using the USB peripheral, at a much lower address than the rest of RAM. And having 20 ZSTs 32kB apart in ROM doesn't seem that useful either.

**Comment by Patryk27** [comment]
> Do you think this `#[repr(align(32768))] struct Hello16BitAlign;` has any real use-case on AVR? Even a somewhat silly one?

I don't think so - I mean, I think ideally we'd throw this error on instantiating the struct, so that a mere fact of such type existing wasn't a failure (as in @zachs18's example), but I think there's no point in doing more complex analysis considering it's already quite an edge case.

**Comment by workingjubilee** [comment]
Okay!

Then if people using the targets cannot think of a good reason for us to support an alignment greater than `isize::MAX`, zero-sized type or no: let us not, and keep the rule consistent.

**Comment by workingjubilee** [comment]
Unfortunately I don't know that this is the right place to emit this check, so having determined that, its implementation seems correct, but it would be good if someone with experience with `rustc_passes` could actually weigh in.

**Comment by workingjubilee** [comment]
hmm, recent history (and a coinflip) says...

r? @jieyouxu

**Comment by asquared31415** [comment]
> Unfortunately I don't know that this is the right place to emit this check...

I explored an alternative approach doing the error in the same location that the `2^64` check was emitted in `rustc_attr::builtin::parse_alignment`, but was unsatisfied with how the `&'static str` error type was being used and changing the call sites seemed non-trivial because it is used for `repr(packed)` as well.

... on further thought, should this `isize::MAX` check be done for `repr(packed(N))`?  Since `repr(packed)` can only lower alignment, it's probably not necessary?

File: compiler/rustc_passes/src/check_attr.rs [hunk 2]
```diff
@@ -1793,6 +1794,30 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
...
+                                .signed_int_max() as u64;
+                            if val > max {
+                                self.dcx().emit_err(errors::InvalidReprAlignForTarget {
+                                    span: hint.span(),
+                                    size: max,
+                                });
+                            }
+                        }
+                    }
                 }
```
Comment (jieyouxu) [inline compiler/rustc_passes/src/check_attr.rs:1821]: Suggestion: can you please extract this into a helper fn? We should keep the top-level check attr visitor more of an "orchestrator" and delegate non-trivial check details to helpers.

File: compiler/rustc_passes/src/check_attr.rs [hunk 3]
```diff
@@ -1793,6 +1794,30 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
...
+                        _,
+                        MetaItemLit {
+                            kind: ast::LitKind::Int(literal, ast::LitIntType::Unsuffixed),
+                            ..
+                        },
+                    )) = hint.singleton_lit_list()
+                    {
+                        let val = literal.get() as u64;
+                        // ignore values greater than 2^29, a different error will be emitted
+                        if val <= 2_u64.pow(29) {
```
Comment (jieyouxu) [inline compiler/rustc_passes/src/check_attr.rs:1810]: Problem: please use a [`self.dcx().delayed_bug("...")`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.DiagCtxtHandle.html#method.delayed_bug) here to assert that an error is emitted

> This is a strange one: lets you register an error without emitting it. If compilation ends without any other errors occurring, this will be emitted as a bug. Otherwise, it will be silently dropped. I.e. “expect other errors are emitted” semantics. Useful on code paths that should only be reached when compiling erroneous code.
>
> -- <https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.Level.html#variant.DelayedBug>

**Review by jieyouxu — COMMENTED** [review]
This is a reasonable place to check the attribute. I have some nits, but looks good otherwise.

> should this `isize::MAX` check be done for `repr(packed(N))`?  Since `repr(packed)` can only lower alignment, it's probably not necessary?

That should be in a follow-up if that is determined desirable.

**Comment by asquared31415** [comment]
@rustbot ready

will open a zulip thread about the potential follow up PR for `repr(align)`, though personally i don't think it's necessary

File: tests/ui/repr/repr_align_greater_usize.rs [hunk 4]
```diff
@@ -0,0 +1,26 @@
+//@ revisions: msp430 aarch32
+//@[msp430] check-fail
```
Comment (jieyouxu) [inline tests/ui/repr/repr_align_greater_usize.rs:2]: Suggestion: this is redundant for ui tests, ui tests are `check-fail` by default.

**Review by jieyouxu — APPROVED** [review]
Thanks, one tiny nit then r=me.

**Comment by jieyouxu** [comment]
Dropped the redundant `check-fail`, no other changes.
@bors r+ rollup=iffy

File: compiler/rustc_passes/src/check_attr.rs (hunk 3 above)
Comment (jieyouxu) [reply compiler/rustc_passes/src/check_attr.rs]: Turns out this is good, actually. The delayed bug caught the fact that we didn't even properly check the attr on certain targets in the first place, lmao.
