### PR TITLE
Kill the storage for all locals on returning terminators

### LINKED ISSUE #45704: MIR-borrowck: locals (and thread locals) can remain borrowed after the function ends
e.g. this does not give a MIR borrowck error:

```Rust
#![feature(thread_local)]

#[thread_local]
static FOO: u8 = 3;

fn assert_static(_t: &'static u8) {}
fn main() {
     assert_static(&FOO);
}
```

This is a problem because, as #17954 shows, thread locals end when the current thread ends. AST borrowck currently makes it an error when thread locals are borrowed for more than the current function.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #45704.

### CODE REVIEW

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 1]
```diff
@@ -233,6 +233,21 @@ impl<'a, 'gcx, 'tcx> BitDenotation for Borrows<'a, 'gcx, 'tcx> {
...
+            mir::TerminatorKind::Resume |
+            mir::TerminatorKind::Return |
+            mir::TerminatorKind::GeneratorDrop => {
+                for (borrow_index, borrow_data) in self.borrows.iter_enumerated() {
+                    if let ReScope(..) = borrow_data.region {
+                        sets.kill(&borrow_index);
+                    }
+                }
+            }
+            _ => {}
```
Comment (nikomatsakis) [inline src/librustc_mir/dataflow/impls/borrows.rs]: Nit: I'd prefer to see the variants here written out exhaustively. My rule of thumb: if a new terminator kind is added, what is the change this code might want to change? If it is not "rather low", make it exhaustive. I rate this chance as "moderate".

File: src/librustc_mir/dataflow/impls/borrows.rs [hunk 2]
```diff
@@ -233,6 +233,21 @@ impl<'a, 'gcx, 'tcx> BitDenotation for Borrows<'a, 'gcx, 'tcx> {
...
                          sets: &mut BlockSets<BorrowIndex>,
                          location: Location) {
+        let block = &self.mir.basic_blocks().get(location.block).unwrap_or_else(|| {
+            panic!("could not find block at location {:?}", location);
+        });
+        match block.terminator().kind {
+            mir::TerminatorKind::Resume |
+            mir::TerminatorKind::Return |
+            mir::TerminatorKind::GeneratorDrop => {
+                for (borrow_index, borrow_data) in self.borrows.iter_enumerated() {
```
Comment (nikomatsakis) [inline src/librustc_mir/dataflow/impls/borrows.rs]: This would be a good place for a comment. Something like:

```
// When we return from the function, then all `ReScope`-style regions are guaranteed to have ended.
// Normally, there would be `EndRegion` statements that come before, and hence most of these loans
// will already be dead -- but, in some cases like unwind paths, we do not always emit `EndRegion`
// statements, so we add some kills here as a "backup" and to avoid spurious error messages.
```

File: src/librustc_mir/borrow_check.rs [hunk 3]
```diff
@@ -373,10 +373,19 @@ impl<'cx, 'gcx, 'tcx> DataflowResultsConsumer<'cx, 'tcx> for MirBorrowckCtxt<'cx
                                      Consume, (value, span), flow_state);
             }
 
-            TerminatorKind::Goto { target: _ } |
             TerminatorKind::Resume |
             TerminatorKind::Return |
-            TerminatorKind::GeneratorDrop |
+            TerminatorKind::GeneratorDrop => {
+                for local in self.mir.local_decls.indices() {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Good place for a comment, me thinks.

```
// Returning from the function implicitly kills storage for all locals.
// Often, the storage will already have been killed by an explicit
// StorageDead, but we don't always emit those (notably on unwind paths),
// so this "extra check" serves as a kind of backup.
```

File: src/librustc_mir/borrow_check.rs [hunk 4]
```diff
@@ -373,10 +373,19 @@ impl<'cx, 'gcx, 'tcx> DataflowResultsConsumer<'cx, 'tcx> for MirBorrowckCtxt<'cx
...
+                    self.access_lvalue(
+                        ContextKind::StorageDead.new(loc),
+                        (&Lvalue::Local(local), span),
+                        (Shallow(None), Write(WriteKind::StorageDeadOrDrop)),
+                        flow_state
+                    );
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: This PR is also aiming to check for in-scope loans of "thread-local statics" and report an error. It may be that it already prevents those. To check, can you add the following test as `src/test/compile-fail/borrowck/thread-local-static-borrow-outlives-fn.rs` (I don't believe we have any such test already):

```rust
// Test that borrows of `#[thread_local]` statics cannot
// outlive the function. See also #17954.

// revisions: ast mir

#![feature(thread_local)]

#[thread_local]
static FOO: u8 = 3;

fn assert_static(_t: &'static u8) {}
fn main() {
     assert_static(&FOO);
}
```

This currently gives a [somewhat obscure error about the lifetime of a temporary value](https://play.rust-lang.org/?gist=a66257a3be6b7fdccdfa8fb257de8062&version=nightly), which makes me think that it will likely generate an error under your PR as well, presuming MIR introduces a temporary at the same spot. I'm actually a bit unsure just *why* we are generating a temporary here -- presumably something to do with how we lower access to `#[thread_local]` statics. Anyway, let's add the test. If it gets an error in both checkers, great, otherwise, we'll have to add a bit of code right around here I think to check for outstanding borrows of `#[thread_local]` statics.

File: src/test/run-fail/borrowck-local-borrow.rs [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+// error-pattern:panic 1
+
+// revisions: ast mir
+//[mir]compile-flags: -Z emit-end-regions -Z borrowck-mir
+
+fn main() {
+    let x = 2;
+    let y = &x;
+    panic!("panic 1");
+}
```
Comment (nikomatsakis) [inline src/test/run-fail/borrowck-local-borrow.rs]: Can you also add the test that @arielb1 added to the issue and check that it generates two errors (one for each function) -- both in AST and MIR mode? [A quick test with play *seems* to suggest that it does not generate two errors today](https://play.rust-lang.org/?gist=9fab9b5b24c24187f27b72b6f380aa55&version=nightly), but it'd be good to verify that your test is not working before your patch, and works after while you are at it.

```rust
fn cplusplus_mode(x: isize) -> &'static isize { &x }

fn cplusplus_mode_exceptionally_unsafe(x: &mut Option<&'static mut isize>) {
    let z = 0;
    *x = Some(&mut z);
    panic!("catch me for a dangling pointer!")
}
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks nice! I left a few minor nits as well as a request for some new tests.

**Comment by KiChjang** [comment]
Ok, so I added two tests, both of which are failing; `borrowck-local-borrow-outlives-fn.rs` fails because the MIR borrowck error message differs from AST borrowck, whereas `borrowck-local-static-borrow-outlives-fn.rs` fails because MIR borrowck is actually **not** catching the borrow correctly for static locals.

**Comment by KiChjang** [comment]
The latest force-push contains changes to the logic in checking for `StorageDead`s; instead of looping through the local declarations, we loop through the borrows. This is because it's much easier to get the span of the borrow for error reporting purposes.

File: src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+    &x //[ast]~ ERROR `x` does not live long enough
+       //[mir]~^ ERROR `x` does not live long enough (Ast)
+       //[mir]~| ERROR borrowed value does not live long enough (Mir)
+}
+
+fn cplusplus_mode_exceptionally_unsafe(x: &mut Option<&'static mut isize>) {
+    let mut z = 0;
+    *x = Some(&mut z); //[ast]~ ERROR `z` does not live long enough
+                       //[mir]~^ ERROR `z` does not live long enough (Ast)
+                       //[mir]~| ERROR `z` does not live long enough (Mir)
```
Comment (KiChjang) [inline src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs]: The only problem left here now is this - MIR borrowck doesn't generate an error for this.

File: src/librustc_mir/borrow_check.rs [hunk 7]
```diff
@@ -373,10 +373,41 @@ impl<'cx, 'gcx, 'tcx> DataflowResultsConsumer<'cx, 'tcx> for MirBorrowckCtxt<'cx
...
+                    let root_lvalue = self.prefixes(
+                        &borrow.lvalue,
+                        PrefixSet::All
+                    ).last().unwrap();
+                    match root_lvalue {
+                        Lvalue::Static(_) => {
+                            self.access_lvalue(
+                                ContextKind::StorageDead.new(loc),
+                                (&root_lvalue, self.mir.source_info(borrow.location).span),
+                                (Deep, Write(WriteKind::StorageDeadOrDrop)),
```
Comment (KiChjang) [inline src/librustc_mir/borrow_check.rs]: The other thing I'm not sure about is whether this should be a shallow write instead.

File: src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs (hunk 6 above)
Comment (arielb1) [reply src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs]: The problem here is `TerminatorKind::Call` with a `None` unwind terminator, which just means that the call immediately jumps to a resume.

I feel it's a good idea to have MIR construction instead link all `None` call terminators to a resume block, and have a later pass (e.g. `SimplifyBranches`) clean up unwind paths that don't actually do anything so they won't choke LLVM.

Comment (arielb1) [reply src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs]: I suppose you can remove this test and I'll handle the change myself.

File: src/librustc_mir/borrow_check.rs (hunk 7 above)
Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: This should be a drop - basically a shallow write for structs without a destructor, and a deep write for structs without one.

Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: Ah so this code only runs for thread-locals. In that case, I suppose there won't be much harm from it remaining a deep write.

**Comment by arielb1** [comment]
r=me with the cplusplus_mode_exceptionally_unsafe test removed - I'll fix it myself.

**Review by nikomatsakis — APPROVED** [review]

**Comment by kennytm** [comment]
`mir-opt/nll/region-liveness-drop-no-may-dangle.rs` failed on `i686-musl`. The test doesn't seem 32-bit- or musl-specific though, so the failure is probably affected by recent merges. Try rebase on the latest master. 

<details>

```
[00:54:59] failures:
[00:54:59] 
[00:54:59] ---- [mir-opt] mir-opt/nll/region-liveness-drop-no-may-dangle.rs stdout ----
[00:54:59] 	
[00:54:59] error: compilation failed!
[00:54:59] status: exit code: 101
[00:54:59] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/mir-opt/nll/region-liveness-drop-no-may-dangle.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt" "--target=i686-unknown-linux-musl" "-Zdump-mir=all" "-Zmir-opt-level=3" "-Zdump-mir-exclude-pass-number" "-Zdump-mir-dir=/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/nll/region-liveness-drop-no-may-dangle" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/nll/region-liveness-drop-no-may-dangle.stage2-i686-unknown-linux-musl" "-Crpath" "-O" "-Lnative=/checkout/obj/build/i686-unknown-linux-musl/native/rust-test-helpers" "-Clinker=/musl-i686/bin/musl-gcc" "-Znll" "-Zverbose" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/nll/region-liveness-drop-no-may-dangle.stage2-i686-unknown-linux-musl.aux"
[00:54:59] stdout:
[00:54:59] ------------------------------------------
[00:54:59] 
[00:54:59] ------------------------------------------
[00:54:59] stderr:
[00:54:59] ------------------------------------------
[00:54:59] error[E0597]: borrowed value does not live long enough (Mir)
[00:54:59]   --> /checkout/src/test/mir-opt/nll/region-liveness-drop-no-may-dangle.rs:25:51
[00:54:59]    |
[00:54:59] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:331:21
[00:54:59] 24 |     let mut v = [1, 2, 3];
[00:54:59]    |         ----- temporary value created here
[00:54:59] 25 |     let p: Wrap<& /* R1 */ usize> = Wrap { value: &v[0] };
[00:54:59]    |                                                   ^^^^^ temporary value dropped here while still borrowed
[00:54:59]    |
[00:54:59]    = note: consider using a `let` binding to increase its lifetime
[00:54:59] 
[00:54:59] error: aborting due to previous error
[00:54:59] 
[00:54:59] 
[00:54:59] ------------------------------------------
[00:54:59] 
[00:54:59] thread '[mir-opt] mir-opt/nll/region-liveness-drop-no-may-dangle.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2570:8
[00:54:59] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

</details>

**Comment by KiChjang** [comment]
Rebased.

**Comment by KiChjang** [comment]
Same error as above - I wonder if my patch is causing the temporary rvalue to be dropped too soon...

**Comment by kennytm** [comment]
@KiChjang rebasing won't fix the problem, it just exposes the problem on the CI early on instead of wait until `bors r+` (ensure the CI status is truly red instead of falsely green).

File: src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs [hunk 8]
```diff
@@ -0,0 +1,20 @@
...
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// revisions: ast mir
+//[mir]compile-flags: -Z emit-end-regions -Z borrowck-mir
```
Comment (est31) [inline src/test/compile-fail/borrowck/borrowck-local-borrow-outlives-fn.rs]: You don't need the emit-end-regions flag any more btw, thanks to this very nice PR: #44717. My PR #46106 is removing them everywhere but I guess I should start spreading the word so that the line doesn't keep getting added :p.

The comment applies to the other places where you have -Z emit-end-regions as well, but I won't comment on each of them.

**Comment by arielb1** [comment]
@KiChjang 

How are you doing debugging this? Should I check in and try to get this working?
