### PR TITLE
Prevent compiler stack overflow for deeply recursive code

### LINKED ISSUE #32594: parser stack overflow with very deeply nested items
Trying to compile this code, which contains 492 nested `loop` blocks: http://pastie.org/private/blihpoctk64fvv9yvwkp5g

causes rustc to unceremoniously segfault.  I feel like this is basic enough (unavoidable other than with diagnostics?) that there should be an existing issue for it, but I can't find one, so here's a new report. 

For the record, this is stripped down from real (generated) code.  I have been using labeled `break` as a substitute for `goto` - in my real code the `loop` blocks are labeled; after each `loop` is the code for that case, followed by a `return`.  Inside all the nested `loop`s is a decoder which `break`s to one of the labels, consisting of a number of nested `match` statements, within which a single label can appear several times.  (Normally I would use functions instead of labels, like `return handle_foo(...)`, and in fact this might 'just work', but I can't guarantee that each helper function (1) is inlined, but (2) is inlined _only once_, after the calls are merged into one basic block, rather than separately for each time it's mentioned.)

Partial backtrace:

```
  * frame #0: 0x0000000101cdd01a libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_item_::h7cfdc3a522ccefe4 + 26
    frame #1: 0x0000000101cdcfd3 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::with_res::hca18e2b367aac45a + 83
    frame #2: 0x0000000101cda76d libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_stmt_::h2ef05e1acf23b3ee + 2749
    frame #3: 0x0000000101cc2685 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_block_tail::h850fd6dee5511129 + 181
    frame #4: 0x0000000101ca33da libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_inner_attrs_and_block::h758cb08b805a3c04 + 1274
    frame #5: 0x0000000101cc1f10 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_loop_expr::he95eef038af4df5c + 48
    frame #6: 0x0000000101cb9304 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_bottom_expr::hdb91d7fed291df76 + 11332
    frame #7: 0x0000000101cc45b6 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_dot_or_call_expr::hd6b49bfb09b97ce0 + 438
    frame #8: 0x0000000101cce364 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_prefix_expr::h696f8c3b5de4ed7a + 3812
    frame #9: 0x0000000101ccfbe8 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_assoc_expr_with::h437ac6f395ba7253 + 232
    frame #10: 0x0000000101ccfaec libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_assoc_expr::h6d60b59a50fe4e9b + 92
    frame #11: 0x0000000101ccf6f6 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_expr_res::he5eaa4701a507b69 + 86
    frame #12: 0x0000000101cdae2a libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_stmt_::h2ef05e1acf23b3ee + 4474
    frame #13: 0x0000000101cc2685 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_block_tail::h850fd6dee5511129 + 181
    frame #14: 0x0000000101ca33da libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_inner_attrs_and_block::h758cb08b805a3c04 + 1274
    frame #15: 0x0000000101cc1f10 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_loop_expr::he95eef038af4df5c + 48
    frame #16: 0x0000000101cb9304 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_bottom_expr::hdb91d7fed291df76 + 11332
    frame #17: 0x0000000101cc45b6 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_dot_or_call_expr::hd6b49bfb09b97ce0 + 438
    frame #18: 0x0000000101cce364 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_prefix_expr::h696f8c3b5de4ed7a + 3812
    frame #19: 0x0000000101ccfbe8 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_assoc_expr_with::h437ac6f395ba7253 + 232
[..]
    frame #2399: 0x0000000101ccfbe8 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_assoc_expr_with::h437ac6f395ba7253 + 232
    frame #2400: 0x0000000101ccfaec libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_assoc_expr::h6d60b59a50fe4e9b + 92
    frame #2401: 0x0000000101ccf6f6 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_expr_res::he5eaa4701a507b69 + 86
    frame #2402: 0x0000000101cdae2a libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_stmt_::h2ef05e1acf23b3ee + 4474
    frame #2403: 0x0000000101cc2685 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_block_tail::h850fd6dee5511129 + 181
    frame #2404: 0x0000000101ca33da libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_inner_attrs_and_block::h758cb08b805a3c04 + 1274
    frame #2405: 0x0000000101cf77fa libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_item_fn::hce3de4303f5d8ba2 + 1674
    frame #2406: 0x0000000101cdf539 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_item_::h7cfdc3a522ccefe4 + 9529
    frame #2407: 0x0000000101c7a1e4 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_item::h436e395dd151cc52 + 484
    frame #2408: 0x0000000101d068ea libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_mod_items::hea97d1b94833eb22 + 186
    frame #2409: 0x0000000101c78112 libsyntax-18402db3.dylib`syntax::parse::parser::Parser::parse_crate_mod::h8c61b50923a69031 + 466
    frame #2410: 0x0000000101c77d9b libsyntax-18402db3.dylib`syntax::parse::parse_crate_from_file::h2bec29ecacefb78e + 171
    frame #2411: 0x0000000100058780 librustc_driver-18402db3.dylib`rustc_driver::driver::phase_1_parse_input::_$u7b$$u7b$closure$u7d$$u7d$::hf7d19c22fe6fc59c + 176
    frame #2412: 0x000000010002cc5a librustc_driver-18402db3.dylib`rustc_driver::driver::phase_1_parse_input::hddc8900dc2500ee4 + 250
    frame #2413: 0x0000000100019500 librustc_driver-18402db3.dylib`rustc_driver::driver::compile_input::hb8958b270f32a505 + 144
    frame #2414: 0x00000001000091d0 librustc_driver-18402db3.dylib`rustc_driver::run_compiler::h146dabfc96bf3a5a + 4000
    frame #2415: 0x0000000100006673 librustc_driver-18402db3.dylib`std::sys_common::unwind::try::try_fn::h847694ac14db1c2b + 467
    frame #2416: 0x000000010487b25c libstd-18402db3.dylib`__rust_try + 12
    frame #2417: 0x000000010487b1e4 libstd-18402db3.dylib`std::sys_common::unwind::inner_try::h790ed072af125c7c + 116
    frame #2418: 0x0000000100006f0a librustc_driver-18402db3.dylib`_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h64418c3ccdc3072e + 394
    frame #2419: 0x0000000104888ef9 libstd-18402db3.dylib`std::sys::thread::Thread::new::thread_start::hdaf9c8e3f2f1c46e + 57
    frame #2420: 0x00007fff893ee9b1 libsystem_pthread.dylib`_pthread_body + 131
    frame #2421: 0x00007fff893ee92e libsystem_pthread.dylib`_pthread_start + 168
    frame #2422: 0x00007fff893ec385 libsystem_pthread.dylib`thread_start + 13
```

### LINKED ISSUE #34844: ICE on extremely deeply nested syntax
The following shell scripts all cause a stack overflow in the compiler:

``` sh
python -c 'print("("*100000 + ")"*100000)'| rustc /dev/fd/0
python -c 'print("{"*100000 + "}"*100000)'| rustc /dev/fd/0
python -c 'print("{("*100000 + "})"*100000)'| rustc /dev/fd/0
```

This should be fixed (perhaps by making the parser non-recursive, or by setting an explicit recursion limit).

### LINKED ISSUE #40161: Deep recursion issues in the compiler
As suggested by @abonander, this is an issue to track deep recursion issues in the compiler.

- **Recursion in HIR expression lowering may lead to stack overflow**
    Related issue(s): #40119 

- **Taking too many references to a value causes compiler stack overflow**
    Related issue(s): #40253 
    Note: pending, is that actually an issue or a desired behavior?

### LINKED ISSUE #41884: Use stacker to prevent stack overflow from depth-first query evaluation.
[`stacker`](https://docs.rs/stacker) is:
> A library to help grow the stack when it runs out of space.
>
> This is an implementation of manually instrumented segmented stacks where points in a program's control flow are annotated with "maybe grow the stack here". Each point of annotation indicates how far away from the end of the stack it's allowed to be, plus the amount of stack to allocate if it does reach the end.
>
> Once a program has reached the end of its stack, a temporary stack on the heap is allocated and is switched to for the duration of a closure.

Recent PRs that might be relevant: #41625 (MIR inlining) and #41676 (macro expansion).

Also related: https://github.com/rust-lang/rust/issues/40161, a meta issue for places where deep recursion arise.

cc @rust-lang/compiler

### LINKED ISSUE #55471: regression: stack overflow on macosx with xcode 6.4
The `build.rs` of `mach-test` in the `mach` crate commit https://github.com/fitzgen/mach/commit/d31c809c22724c5dad198037ad03bfec7906e016 crashes on MacOS X with a stack overflow when `xcode` 6.4 is used. This used to work, but is now failing on nightly, so this stack overflow is a regression. I don't have access to a MacOSX system with xcode 6.4 but travis reproduces this reliably. The PR in mach that works around this is: https://github.com/fitzgen/mach/pull/49

### PR DESCRIPTION
**Pull request by oli-obk**
I was unable to write a test that

1. runs in under 1s
2. overflows on my machine without this patch

The following reproduces the issue, but I don't think it's sensible to include a test that takes 30s to compile. We can now easily squash newly appearing overflows by the strategic insertion of calls to `ensure_sufficient_stack`.

```rust
// compile-pass

#![recursion_limit="1000000"]

macro_rules! chain {
    (EE $e:expr) => {$e.sin()};
    (RECURSE $i:ident $e:expr) => {chain!($i chain!($i chain!($i chain!($i $e))))};
    (Z $e:expr) => {chain!(RECURSE EE $e)};
    (Y $e:expr) => {chain!(RECURSE Z $e)};
    (X $e:expr) => {chain!(RECURSE Y $e)};
    (A $e:expr) => {chain!(RECURSE X $e)};
    (B $e:expr) => {chain!(RECURSE A $e)};
    (C $e:expr) => {chain!(RECURSE B $e)};
    // causes overflow on x86_64 linux
    // less than 1 second until overflow on test machine
    // after overflow has been fixed, takes 30s to compile :/
    (D $e:expr) => {chain!(RECURSE C $e)};
    (E $e:expr) => {chain!(RECURSE D $e)};
    (F $e:expr) => {chain!(RECURSE E $e)};
    // more than 10 seconds
    (G $e:expr) => {chain!(RECURSE F $e)};
    (H $e:expr) => {chain!(RECURSE G $e)};
    (I $e:expr) => {chain!(RECURSE H $e)};
    (J $e:expr) => {chain!(RECURSE I $e)};
    (K $e:expr) => {chain!(RECURSE J $e)};
    (L $e:expr) => {chain!(RECURSE L $e)};
}


fn main() {
    let x = chain!(D 42.0_f32);
}
```

fixes #55471
fixes #41884
fixes #40161
fixes #34844
fixes #32594

cc @alexcrichton @rust-lang/compiler 

I looked at all code that checks the recursion limit and inserted stack growth calls where appropriate.

### CODE REVIEW

**Comment by nagisa** [comment]
With this, lets drop the default stack size down from 16MB to something more reasonable (8MB or even 4MB).

https://github.com/rust-lang/rust/blob/master/src/librustc_driver/driver.rs#L94

https://github.com/rust-lang/rust/blob/master/src/librustc_driver/lib.rs#L1473

With that change and reduced growth factor (i.e. growing stack by something like 1MB rather than 16MB) crater should be very capable at answering whether we put the `guarantee_one_mb_stack_left` in all the necessary places.

File: src/librustc/middle/recursion_limit.rs [hunk 1]
```diff
@@ -8,18 +8,32 @@
...
 
+const RED_ZONE: usize = 1024*1024; // 1MB
+const STACK_PER_RECURSION: usize = 8 * 1024 * 1024; // 8MB
+
+/// Grows the stack on demand to prevent stack overflow. Call this in strategic locations
+/// to "break up" recursive calls. E.g. almost any call to `visit_expr` or equivalent can benefit
+/// from this.
+///
+/// Should not be sprinkled around carelessly, as it causes a little bit of overhead.
+pub fn guarantee_one_mb_stack_left<R, F: FnOnce() -> R>(
```
Comment (nagisa) [inline src/librustc/middle/recursion_limit.rs]: Lets not claim this function guarantees exactly one `MB` of stack (since that can easily change based on the constants). Some better options would be `guarantee_sufficient_stack`, `ensure_sufficient_stack` and similar that do not necessarily claim any specific amount of stack.

File: src/librustc/Cargo.toml [hunk 2]
```diff
@@ -34,6 +34,7 @@ byteorder = { version = "1.1", features = ["i128"]}
 chalk-engine = { version = "0.8.0", default-features=false }
 rustc_fs_util = { path = "../librustc_fs_util" }
 smallvec = { version = "0.6.5", features = ["union"] }
+stacker = "0.1.3"
```
Comment (alexcrichton) [inline src/librustc/Cargo.toml]: I'm not sure `stacker` is necessarily rustc-ready right now, but that doesn't mean that it can't be! Some issues I can think of are:

* It only has support for x86 platforms basically, and only Windows/Mac/Linux. It should be easy enough to "add support" for other platforms by basically doing nothing. Full support could be added over time as necessary
* I don't think `stacker` does anything with guard pages, but ideally it'd also be sure to allocate guard pages for larger segments to protect agains accidental stack overflow
* I'm not entirely sure how well panics and such work? It should be relatively easy to `catch_unwind` and `resume_unwind` though when necessary (just needs to be done)

These are all pretty minor, but I'd want to be sure to handle them before merging if possible!

File: src/librustc/ty/query/plumbing.rs [hunk 3]
```diff
@@ -540,7 +540,7 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
             p.record_query(Q::CATEGORY);
         });
 
-        let res = job.start(self, |tcx| {
+        let res = ::middle::recursion_limit::ensure_sufficient_stack(|| job.start(self, |tcx| {
```
Comment (eddyb) [inline src/librustc/ty/query/plumbing.rs]: Could the `ensure_sufficient_stack` call be moved into the `Job::start` method?

File: src/librustc_driver/lib.rs [hunk 4]
```diff
@@ -1460,6 +1460,8 @@ fn parse_crate_attrs<'a>(sess: &'a Session, input: &Input) -> PResult<'a, Vec<as
     }
 }
 
+const STACK_SIZE: usize = 4 * 1024 * 1024; // 4MB
```
Comment (eddyb) [inline src/librustc_driver/lib.rs]: Maybe make this dependent on whether `stacker` *actually works*?

Comment (oli-obk) [reply src/librustc_driver/lib.rs]: How's that relevant? When stacker doesn't work, these values don't matter, because they don't do anything

Comment (eddyb) [reply src/librustc_driver/lib.rs]: I thought this was the default thread stack size, unrelated to stacker. My bad if that's not the case.

Comment (oli-obk) [reply src/librustc_driver/lib.rs]: I'm gonna rename the constant to be clearer about this

File: src/librustc/ty/query/plumbing.rs (hunk 3 above)
Comment (michaelwoerister) [reply src/librustc/ty/query/plumbing.rs]: Yes, that would probably be a good idea.

**Comment by michaelwoerister** [comment]
Let's do a perf run.
@bors try

**Comment by oli-obk** [comment]
@rust-timer build 2b10b3db7f22fca8db44c0e9511a16542edcede1

**Comment by michaelwoerister** [comment]
Makes sense that the `clean-incremental` cases don't see a difference since they hardly execute any of the changed code. The other regressions are rather unfortunate though. Can we optimize this?

**Comment by oli-obk** [comment]
Well, this is an operation we now run on every single query (not every call, just every evaluation). There are loads of queries. It seems logical that this introduces some regression that we can't get rid of.

**Comment by michaelwoerister** [comment]
But
- do we need to run the operation really for every query invocation?
- can we make the operation less expensive, especially in the case where the stack doesn't have to be grown?

**Comment by eddyb** [comment]
I feel like the actual stack check shouldn't be noticeable compared to hashing and looking up a key in a hashmap. Maybe we're growing the stack more often than we need to?

**Comment by nikic** [comment]
Looking at the stacker implementation, a possible issue might be that we're sitting somewhere close to the stack limit and regularly go over it and below it again. This will allocate and deallocate a new stack every time. Maybe retaining the last allocation would help to reduce the performance impact?

**Comment by nagisa** [comment]
My initial proposal separately mentioned that we should only grow the stack
and never bother redicing its size. I made that call with performance in
mind. I didn't realise stacker was deallocating stack fragments, though now
that I think about it, *that* is the obvious implementation for the stacker
approach.

**Comment by oli-obk** [comment]
@rust-timer build 50090422044f60a331c227348157f4a963bb5c21

**Comment by oli-obk** [comment]
Looks like only half as many tests are regressing in performance now.

@nagisa do you want a crater run with this version and then we bump the default stack sizes back up to saner defaults and run perf again? Or do you first want to see the perf with the original stack sizes?

**Comment by nagisa** [comment]
Don't care much about perf results, honestly. Having the bug fixed is the
first priority, making it faster can be done later and needn't block the
bug fix at all.

Let's go with just a crater run.

**Comment by oli-obk** [comment]
@craterbot run start=master#485397e49a02a3b7ff77c17e4a3f16c653925cb3 end=try#50090422044f60a331c227348157f4a963bb5c21 mode=check-only

**Comment by oli-obk** [comment]
Only one regression (guessing spurious as it's something about a feature gate missing) :tada:

**Comment by nagisa** [comment]
Seems like all regressions and fixes are accidental/spurious. All the
crates that regressed complain about some feature missing, while the fixed
crates complained about that same feature previously and compiled fine this
time around.

**Comment by michaelwoerister** [comment]
OK, so crater looks good. Performance looks better than before. Do we know where the remaining performance regressions come from? Is it still thrashing? Or is it just that the initial stack size isn't sufficient for those cases? (I doubt that the actual check is costly). 

Is anything else to be done here? (MSVC?)

**Comment by oli-obk** [comment]
> Do we know where the remaining performance regressions come from?

Nope.

> Is it still thrashing?

Maybe, see below

>  Or is it just that the initial stack size isn't sufficient for those cases? (I doubt that the actual check is costly).

I'm assuming it has to do with stack switching happening often, because it definitely can't be the amount of allocations anymore. We are probably hitting a bad case where the initial stack size is small and unfortunately falls directly on a space where were're crossing the stack size often.

This assumption should be fairly easy to check by increasing the limits again. I'll start another perf run with that

**Comment by pietroalbini** [comment]
Ping! What's the status? Release is approaching.

**Comment by oli-obk** [comment]
The real fix (https://github.com/alexcrichton/stacker/pull/8) is nontrivial and I don't think I'll be able to be confident in a near term solution. I can create a version that works for mac and linux, but will keep overflowing on windows.

**Comment by oli-obk** [comment]
@rust-timer build d1556fad65feee73bb4add671e23adfe97087b29

**Comment by oli-obk** [comment]
cc @rust-lang/infra the `comparison URL` link says "commit not found" even though `rust-timer` is finished.

**Comment by kennytm** [comment]
@oli-obk: The commit missing the one in the master branch. It is still being queued. See https://perf.rust-lang.org/status.html for the complete queue.

**Comment by Mark-Simulacrum** [comment]
We're waiting for the parent commit to finish benchmarking; the bot (correctly) indicated that we finished the try commit, if a bit misleadingly.

https://perf.rust-lang.org/status.html if you want to follow along

**Comment by mati865** [comment]
Perf results [are up](https://perf.rust-lang.org/compare.html?start=9fe5cb5342244a716055fa0162e795deabd4985c&end=d1556fad65feee73bb4add671e23adfe97087b29) :tada:

**Comment by nagisa** [comment]
> I was unable to write a test that
>
> runs in under 1s
> overflows on my machine without this patch

It would be fine to add a test that runs for longer, but given that compiler changes all the time I don’t see that test serving its purpose for any extent of the time, I expect there to be very many different locations in the compiler where many stack frames could be created at once.

**Comment by Dylan-DPC** [comment]
ping from triage @oli-obk you have pending conflicts to resolve.

**Comment by Dylan-DPC** [comment]
ping from triage @oli-obk what's the update on this?

**Comment by oli-obk** [comment]
I think this is still blocked on @nagisa's stacker backend rewrite.

**Comment by nagisa** [comment]
I have released stacker 0.1.6 based on psm. It now supports a large number of different architectures and targets, and so should be suitable for inclusion to the compiler.

We can look into reviving this PR now. There are a couple of ideas I’ve come up during last week: first, only call into `stacker` every couple dozen recursions we see in the compiler. When we eventually do recurse, ask stacker to allocate us a large stack (i.e. not 1MiB, but 4MiB or 8MiB). This follows from an observation that we will rarely recurse very deep, but when we do, we are very likely to recurse very deeply.

This could be achieved by holding a thread-local variable incrementing/decrementing it in the `ensure_sufficient_stack`, and only calling into stacker when the value is modulo N.

**Comment by nagisa** [comment]
FWIW I still anticipate to look into implementing alternative stack allocation strategies with a stacker-like API, but given that it took me ~a year to complete integration of `psm` with `stacker`, I do not anticipate that to materialize very soon.

**Comment by nagisa** [comment]
Also, @oli-obk, let me know if you are unavailable to rebase this PR, I'm willing to dedicate a weekend or two of my own if necessary.

**Comment by Dylan-DPC** [comment]
@oli-obk @nagisa is this still blocked?

**Comment by oli-obk** [comment]
@nagisa I rebased, but am now hitting

```
error: couldn't load codegen backend "/home/oli/rustc/rust8/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so": "/home/oli/rustc/rust8/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so: undefined symbol: rust_psm_stack_direction"
```

Any idea what's up with that? Is this due to the codegen backends being in dylibs?

**Comment by bjorn3** [comment]
Could it be that rustc decides that `rust_psm_stack_direction` should not be exported from `librustc_driver.so`?

File: src/tools/tidy/src/deps.rs [hunk 5]
```diff
@@ -158,6 +158,7 @@ const WHITELIST: &[Crate<'_>] = &[
     Crate("serde_derive"),
     Crate("smallvec"),
     Crate("stable_deref_trait"),
+    Crate("stacker"),
```
Comment (mati865) [inline src/tools/tidy/src/deps.rs]: Tidy gives error because `psm` is not whitelisted.

**Comment by nagisa** [comment]
@oli-obk I’ll build rustc and look at this. Thanks for taking time to rebase!

**Comment by nagisa** [comment]
I think @bjorn3’s inference is pretty much spot-on, the codegen backend ends up having dependencies on

```
                 U rust_psm_on_stack
                 U rust_psm_stack_direction
```

and they are present in rustc_driver, but private:

```
0000000002d7b050 t rust_psm_on_stack
0000000002d7b05e t .rust_psm_on_stack_end
0000000002d7b040 t rust_psm_replace_stack
0000000002d7b046 t .rust_psm_replace_stack_end
0000000002d7b020 t rust_psm_stack_direction
0000000002d7b023 t .rust_psm_stack_direction_end
0000000002d7b030 t rust_psm_stack_pointer
0000000002d7b036 t .rust_psm_stack_pointer_end
```

Compiling stacker or psm as a shared library will reveal this kind of issue as well. I think this will be related to interactions between `inline(always)` and "private" `extern { ...}` stuff. Will try to minimize.

**Comment by nagisa** [comment]
This is caused by a regression from 1.36 to 1.37 (see the issue referenced just above this comment). Marking as I-blocked for now.

**Comment by nagisa** [comment]
@oli-obk I released psm 0.1.6 and the compiler builds with it now after I run `cargo update -p psm` from rust repository root.

**Comment by mati865** [comment]
@rustbot modify labels: -S-blocked +S-waiting-on-author

cc @oli-obk

**Comment by joelpalmer** [comment]
Ping from Triage:  any updates @oli-obk?

**Comment by Dylan-DPC** [comment]
@joelpalmer oli is on vacation so we can triage this again in a few weeks

**Comment by oli-obk** [comment]
> oli is on vacation so we can triage this again in a few weeks

Nope I just kept pushing this PR off to "tomorrow". It should be fixed now, running the full test stage 2 test suite locally, but I already pushed

**Comment by nagisa** [comment]
@rust-lang/compiler lets r=somebody this and put an end to recursive const fns running out of stack!

I would r=me it myself, but given that a sizable part of this has some of my involvement, I’d rather have somebody less partial do the call.

**Comment by Zoxc** [comment]
I'd like to see a recent perf run for this.

@nagisa Does this use fibers to extend the stack on Windows?

**Comment by RalfJung** [comment]
> and put an end to recursive const fns running out of stack!

Recursive const fns do not grow the *compiler* stack at all; the *interpreter* stack is stored on the compiler's heap. So I don't think this will help there at all.

**Comment by oli-obk** [comment]
@rust-timer build ef09365df7400052b8d7614870df8a70eb782251

**Comment by nagisa** [comment]
@Zoxc yes, fibers are still the implementation used for Windows targets.

**Comment by oli-obk** [comment]
I'm not sure where the failure is coming from. I'm building on x86_64 linux and I can't repro, so my setup must be different $somehow. Likely the problem is just a missing `ensure_sufficient_stack` at a good location, but without running gdb I can't find that location.

Currently comparing my setup to the alt builder setup

**Comment by joelpalmer** [comment]
Ping from Triage: any updates @oli-obk?

**Comment by oli-obk** [comment]
I am unable to reproduce this and unable to properly run the same setup as the alt builders. The only difference that I can see is that I'm not using thin-lto which I can't seem to use locally because my clang does not appear to support it.

**Comment by joelpalmer** [comment]
Ping from Triage:  Closing due to inactivity. Please re-open with updates. Thanks! @oli-obk

**Comment by Dylan-DPC** [comment]
Keeping this open since it is being worked on and not trivial to not be in an inactive state :)

**Comment by nagisa** [comment]
I went ahead and rebased the work done here onto current master. I did not seek out the newly added recursion points in the code-base, though.

Running the `try` job again to see if the issue we saw in the past can still be reproduced by replicating the CI environment.

**Comment by nagisa** [comment]
Well, so the question now is, do we land it being aware of a danger that this might cause issues for an unknown number of users (and can be worked around to an extent by setting an environment variable), or would we rather not land this at all, until I, or somebody else, manages to reproduce it at some point in some distant future?

How about we land this early in the next nightly cycle (i.e. sometime early after March 12th?) and see how things go?

**Comment by nagisa** [comment]
@rust-timer build da7afee7291aa98252282828c03ef6712f276bfb

(just to make sure the perf regression remains palatable)

**Comment by nikomatsakis** [comment]
Perf results look pretty reasonable (a few percentage points down on some tests).

**Comment by joelpalmer** [comment]
Triaged

File: src/librustc/middle/recursion_limit.rs [hunk 6]
```diff
@@ -13,6 +13,24 @@ use syntax::ast;
...
+// Ony the first stack that is pushed, grows exponentially (2^n * STACK_PER_RECURSION) from then
+// on. This flag has performance relevant characteristics. Don't set it too high.
+const STACK_PER_RECURSION: usize = 1 * 1024 * 1024; // 1MB
+
+/// Grows the stack on demand to prevent stack overflow. Call this in strategic locations
+/// to "break up" recursive calls. E.g. almost any call to `visit_expr` or equivalent can benefit
+/// from this.
+///
+/// Should not be sprinkled around carelessly, as it causes a little bit of overhead.
+pub fn ensure_sufficient_stack<R, F: FnOnce() -> R>(f: F) -> R {
```
Comment (Centril) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
pub fn ensure_sufficient_stack<R>(f: impl FnOnce() -> R) -> R {
```

File: src/librustc_ast_lowering/expr.rs [hunk 7]
```diff
@@ -175,37 +207,14 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-        };
 
-        hir::Expr {
-            hir_id: self.lower_node_id(e.id),
-            kind,
-            span: e.span,
-            attrs: e.attrs.iter().map(|a| self.lower_attr(a)).collect::<Vec<_>>().into(),
+            ExprKind::ForLoop(..) | ExprKind::Paren(_) => {
+                span_bug!(e.span, "Should be handled by `lower_expr`")
+            }
```
Comment (Centril) [inline src/librustc_ast_lowering/expr.rs]: This seems arbitrary; how was this chosen? (Also leave a comment about it in the code.)

File: src/librustc_ast_lowering/pat.rs [hunk 8]
```diff
@@ -74,11 +85,9 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                 // If we reach here the `..` pattern is not semantically allowed.
                 self.ban_illegal_rest_pat(p.span)
             }
-            PatKind::Paren(ref inner) => return self.lower_pat(inner),
-            PatKind::Mac(_) => panic!("Shouldn't exist here"),
-        };
-
-        self.pat_with_node_id_of(p, node)
+            PatKind::Paren(_) => span_bug!(p.span, "Should be handled by `lower_pat`"),
```
Comment (Centril) [inline src/librustc_ast_lowering/pat.rs]: Here also.

File: src/librustc/middle/limits.rs [hunk 9]
```diff
@@ -13,6 +13,24 @@ use rustc_span::symbol::{sym, Symbol};
 
 use rustc_data_structures::sync::Once;
 
+// This is the amount of bytes that need to be left on the stack before increasing the size.
+// It must be at least as large as the stack required by any code that does not call
+// `ensure_sufficient_stack`.
+const RED_ZONE: usize = 100 * 1024; // 100k
+
+// Ony the first stack that is pushed, grows exponentially (2^n * STACK_PER_RECURSION) from then
```
Comment (spastorino) [inline src/librustc/middle/limits.rs]: typo Ony -> Only

Comment (spastorino) [inline src/librustc/middle/limits.rs]:
```suggestion
// Only the first stack that is pushed, grows exponentially (2^n * STACK_PER_RECURSION) from then
```

File: src/librustc_ast_lowering/expr.rs (hunk 7 above)
Comment (nagisa) [reply src/librustc_ast_lowering/expr.rs]: @oli-obk may be able to answer this better. My guess is that this was done to heuristically reduce number of calls to `ensure_sufficient_stack`. Though at at least unrolling of the `ExprKind::Paren` structure is still recursive so not sure if it makes the sense to extract it anymore.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/70109#issuecomment-600711429, @bors r-

File: src/librustc_ast_lowering/expr.rs [hunk 10]
```diff
@@ -175,37 +207,13 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
-            ExprKind::MacCall(_) => panic!("Shouldn't exist here"),
-        };
-
-        hir::Expr {
-            hir_id: self.lower_node_id(e.id),
-            kind,
-            span: e.span,
-            attrs: e.attrs.iter().map(|a| self.lower_attr(a)).collect::<Vec<_>>().into(),
+            ExprKind::ForLoop(..) | ExprKind::Paren(_) => {
+                span_bug!(e.span, "Should have been handled by `lower_expr`")
```
Comment (Centril) [inline src/librustc_ast_lowering/expr.rs]: Instead of the `span_bug!` here, it would be nice to rename this method to `lower_expr_mut_inner` and keep the parens/for-loop logic here.

File: src/librustc_ast_lowering/pat.rs [hunk 11]
```diff
@@ -74,11 +85,9 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                 // If we reach here the `..` pattern is not semantically allowed.
                 self.ban_illegal_rest_pat(p.span)
             }
-            PatKind::Paren(ref inner) => return self.lower_pat(inner),
-            PatKind::MacCall(_) => panic!("Shouldn't exist here"),
-        };
-
-        self.pat_with_node_id_of(p, node)
+            PatKind::Paren(_) => span_bug!(p.span, "Should have been handled by `lower_pat`"),
```
Comment (Centril) [inline src/librustc_ast_lowering/pat.rs]: Same re. this `span_bug!`.

**Comment by oli-obk** [comment]
@bors retry

Not sure what happened there. It shows up as @alexcrichton cancelling the builds?

**Comment by Dylan-DPC** [comment]
That's how the CI is setup. It shows the message for all failures

**Comment by kennytm** [comment]
@bors retry 

```
error: failed to get `cc` as a dependency of package `bootstrap v0.0.0 (D:\a\1\s\src\bootstrap)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error inflating zlib stream; class=Zlib (5)
```

**Comment by mati865** [comment]
@oli-obk it failed twice due to network issue.
The error:
> failed to fetch `https://github.com/rust-lang/crates.io-index`

**Comment by mark-i-m** [comment]
I think it cancels remaining builds once the first one fails (to avoid wasting resources). But I guess we are still using Alex's token or something...

**Comment by Dylan-DPC** [comment]
> I think it cancels remaining builds once the first one fails (to avoid wasting resources). But I guess we are still using Alex's token or something...

yep

**Comment by Dylan-DPC** [comment]
seems to be spurious again, probably let's wait a while before retrying

**Comment by nagisa** [comment]
Lovely.

**Comment by nagisa** [comment]
@bors r=oli-obk,nagisa

This is getting slightly annoying, especially because there’s a merge conflict _every week_ and its always the same. Can this land already?

**Comment by nagisa** [comment]
Probably another instance of https://github.com/rust-lang/rust/issues/65610.

**Comment by matthiaskrgr** [comment]
```
[RUSTC-TIMING] rustdoc test:false 140.381
   Compiling rustdoc-tool v0.0.0 (D:\a\1\s\src\tools\rustdoc)
error: linking with `i686-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "i686-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "D:\\a\\1\\s\\mingw32\\i686-w64-mingw32\\lib\\crt2.o" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "D:\\a\\1\\s\\mingw32\\i686-w64-mingw32\\lib" "-L" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\rustdoc_tool_binary-4a701c699db92005.rustdoc_tool_binary.9keciky1-cgu.0.rcgu.o" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\rustdoc_tool_binary-4a701c699db92005.rustdoc_tool_binary.9keciky1-cgu.1.rcgu.o" "-o" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\rustdoc_tool_binary-4a701c699db92005.exe" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps" "-L" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1-tools\\release\\deps" "-L" "C:\\Users\\VssAdministrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-i686-pc-windows-gnu-0.4.0\\lib" "-L" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librustdoc-623df451d692c611.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libminifier-bd4c960ed52f1173.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libmacro_utils-ec34bc42a299c630.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libserde_json-df521ec41d6a723f.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libryu-884847625d6fbb01.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libitoa-407b7b901ba98b92.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librustc_rayon-dca742f5a27ff2c8.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librustc_rayon_core-97bb15b697c83493.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libnum_cpus-703c92a94d2627b6.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libcrossbeam_queue-07a1f91568f38347.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libcrossbeam_deque-4ca79d5571a75e16.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libcrossbeam_epoch-69e2753acba79dc0.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libscopeguard-daff162d85229a12.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libmemoffset-9bcd823932e9add6.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libcrossbeam_utils-ca3d388f9997f4cd.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\liblazy_static-6d98e02a2890d6c4.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libarrayvec-3ac7e30890f8899c.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libnodrop-d2ba2a229bcbb1e2.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libtempfile-b0cc751d22927afa.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librand-60b7d01b0be20fd4.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librand_chacha-b4ad63d319444c17.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libc2_chacha-d531dd0cfaae93de.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libppv_lite86-1f813bf42dc44749.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\librand_core-bc6cd2f72d27fb7e.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libgetrandom-7953e1d40dfb9e57.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libremove_dir_all-c8d593b654421206.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libwinapi-eaad9938d6d6e9ba.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libcfg_if-4c39dd61bc99fa84.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libpulldown_cmark-78dd0a8dab7bd73f.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libmemchr-4b9386f100988f48.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libunicase-92588fb26315b3bf.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libbitflags-b3bccdd94dba6b1b.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libserde-c80a814ef8f4021a.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libitertools-9dff643707bfde60.rlib" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1-tools\\i686-pc-windows-gnu\\release\\deps\\libeither-e34075adc9e63284.rlib" "-L" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bdynamic" "-lrustc_driver-1bb37de52fedc11d" "-L" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-ltest-cf7386e25c6ce3eb" "-Wl,--start-group" "-L" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-lstd-19954c573cc69ebe" "-Wl,--end-group" "-Wl,-Bstatic" "C:\\MORE_SPACE\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builtins-4d676b26a7a37ff3.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lwinapi_advapi32" "-lwinapi_cfgmgr32" "-lwinapi_kernel32" "-lwinapi_user32" "-lpsapi" "-lshell32" "-lole32" "-ladvapi32" "-lstdc++" "-luuid" "-ladvapi32" "-ladvapi32" "-lole32" "-loleaut32" "-lkernel32" "-ladvapi32" "-lcfgmgr32" "-lgdi32" "-lkernel32" "-lmsimg32" "-lopengl32" "-lpsapi" "-lsynchronization" "-luser32" "-lwinspool" "-ladvapi32" "-lws2_32" "-luserenv" "-lmingwex" "-lmingw32" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "-lgcc_s" "-lgcc" "-lkernel32" "D:\\a\\1\\s\\build\\i686-pc-windows-gnu\\stage1\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x1eb): undefined reference to `@rust_psm_stack_pointer@0'

          C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x360): undefined reference to `@rust_psm_stack_pointer@0'

          C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x52b): undefined reference to `@rust_psm_stack_pointer@0'

          C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x69b): undefined reference to `@rust_psm_stack_pointer@0'

          C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x810): undefined reference to `@rust_psm_stack_pointer@0'

          C:\MORE_SPACE\i686-pc-windows-gnu\stage1-tools\i686-pc-windows-gnu\release\deps\librustdoc-623df451d692c611.rlib(rustdoc-623df451d692c611.rustdoc.4bpp01ec-cgu.11.rcgu.o):rustdoc.4bpp01ec-c:(.text+0x9f0): more undefined references to `@rust_psm_stack_pointer@0' follow

          collect2.exe: error: ld returned 1 exit status

          

error: aborting due to previous error

[RUSTC-TIMING] rustdoc_tool_binary test:false 2.325
error: could not compile `rustdoc-tool`.

To learn more, run the command again with --verbose.


```

**Comment by mati865** [comment]
@oli-obk do you need help with debugging the error?

**Comment by oli-obk** [comment]
Nope, it's clear what the issue is (https://github.com/rust-lang/stacker/issues/30) even if I'm unclear on how to fix it (because I haven't looked into it at all yet). I'm looking into it now.

**Comment by mati865** [comment]
Rebased: https://github.com/mati865/rust/tree/stacker-wip

**Comment by oli-obk** [comment]
on top of your rebase, we also need to bump stacker to 0.1.8, right?

**Comment by mati865** [comment]
@oli-obk yes, I had patched `Cargo.toml` to local checkout for testing.

**Comment by oli-obk** [comment]
I gave you access to my repo so you can push directly to this PR if you want.

**Comment by mati865** [comment]
Done.

**Comment by oli-obk** [comment]
Ok, let's give this another shot

@bors r=nagisa,oli-obk

**Comment by Mark-Simulacrum** [comment]
cc @XAMPPRocky I tagged this with relnotes-perf but it's not really perf so much as "hey this fixes a longstanding problem, would be cool to mention"
