### PR TITLE
Rustdoc render async function re-export

### LINKED ISSUE #63710: rustdoc renders re-exported `async fn`s incorrectly
Relates to #58027, but this is the case where an async fn is re-exported by another crate. The docs for the original function shows `async fn` but the re-export shows `fn -> impl Future`.

Example:

- [Original function](https://docs.rs/tokio-sync/0.2.0-alpha.2/tokio_sync/mpsc/struct.Receiver.html#method.recv)
- [Re-exported](https://docs.rs/tokio/0.2.0-alpha.2/tokio/sync/mpsc/struct.Receiver.html#method.recv)

### PR DESCRIPTION
**Pull request by csmoe**
Closes #63710 
r? @nikomatsakis

### CODE REVIEW

**Comment by Centril** [comment]
Won't this still render with `-> impl Trait`?

**Comment by csmoe** [comment]
@Centril fixing associate_method, `build_external_function` seems not the one to blame.

**Comment by nikomatsakis** [comment]
@csmoe the ICE results from not having installed a provider function for local crates. In my write-up, I pointed to the `is_const_fn_raw` provider here:

https://github.com/rust-lang/rust/blob/3287a65fc05028dce3b521765f4643384ebc4346/src/librustc/ty/constness.rs#L71-L84

which is installed here into the providers struct

https://github.com/rust-lang/rust/blob/3287a65fc05028dce3b521765f4643384ebc4346/src/librustc/ty/constness.rs#L110-L115

I'm not sure where's the best place to add similar code for `is_async_fn` though

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -217,7 +217,11 @@ fn build_external_function(cx: &DocContext<'_>, did: DefId) -> clean::Function {
     } else {
         hir::Constness::NotConst
     };
-
+    let asyncness =  if cx.tcx.is_async_fn(did) {
```
Comment (nikomatsakis) [inline src/librustdoc/clean/inline.rs]: Nit: it might be nicer to have the query return `hir::IsAsync` directly? e.g., `cx.tcx.asyncness(did)` -- I think almost everything else in this PR would be the same.

File: src/librustdoc/clean/mod.rs [hunk 2]
```diff
@@ -2403,6 +2403,11 @@ impl Clean<Item> for ty::AssocItem {
                     } else {
                         hir::Constness::NotConst
                     };
+                    let asyncness = if cx.tcx.is_async_fn(self.def_id) {
```
Comment (nikomatsakis) [inline src/librustdoc/clean/mod.rs]: also here, code would be cleaner

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks great, thanks @csmoe!

One question: can we adjust the query to be `fn asyncness()` instead of `fn is_async_fn()`?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Oh, one other thing:

We don't have any test for this! Can you add a test?

Here is an example of such a test for async-fn (crate-local only, obviously):

https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/async-fn.rs

and this is an example testing the cross-crate case specifically:

https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/cross-crate-links.rs

but maybe @QuietMisdreavus can give some better examples of *just* the tests we want in this case.

(This is for the bug around async fn across crates, @QuietMisdreavus)

File: src/test/rustdoc/inline_cross/auxiliary/impl_trait_aux.rs [hunk 3]
```diff
@@ -11,8 +13,16 @@ pub fn func3(_x: impl Iterator<Item = impl Iterator<Item = u8>> + Clone) {}
...
 
 impl Foo {
     pub fn method<'a>(_x: impl Clone + Into<Vec<u8>> + 'a) {}
 }
+
+pub struct Bar;
+
+impl Bar {
+    pub async fn async_foo(&self) {}
+}
```
Comment (lzutao) [inline src/test/rustdoc/inline_cross/auxiliary/impl_trait_aux.rs]: Missing newline!

**Comment by csmoe** [comment]
@nikomatsakis I added the tests into https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/inline_cross/impl_trait.rs as it covers bare function and impl re-exports.

File: src/librustc/ty/mod.rs [hunk 4]
```diff
@@ -3349,13 +3349,29 @@ fn issue33140_self_ty(tcx: TyCtxt<'_>, def_id: DefId) -> Option<Ty<'_>> {
     }
 }
 
+/// Check if a function is async.
+fn asyncness(tcx: TyCtxt<'_>, def_id: DefId) -> hir::IsAsync {
+    if let Some(hir_id) = tcx.hir().as_local_hir_id(def_id) {
+        let node = tcx.hir().get(hir_id);
+        if let Some(fn_like) = hir::map::blocks::FnLikeNode::from_node(node) {
```
Comment (nikomatsakis) [inline src/librustc/ty/mod.rs]: Similarly here I would probably just `unwrap` the result, as this query really ought to only be invoked for fn-like def-ids:

```rust
let fn_like = hir::map::blocks::FnLikeNode::from_node(node).unwrap_or_else(|| {
    bug!("asyncness: expected fn-like node but got `{:?}`", def_id);
});
```

File: src/librustc_metadata/decoder.rs [hunk 5]
```diff
@@ -1208,6 +1208,14 @@ impl<'a, 'tcx> CrateMetadata {
         constness == hir::Constness::Const
     }
 
+    pub fn asyncness(&self, id: DefIndex) -> hir::IsAsync {
+         match self.entry(id).kind {
+            EntryKind::Fn(data) => data.decode(self).asyncness,
+            EntryKind::Method(data) => data.decode(self).fn_data.asyncness,
+            _ => hir::IsAsync::NotAsync,
```
Comment (nikomatsakis) [inline src/librustc_metadata/decoder.rs]: I'd probably `bug!` out here, too.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
@csmoe great, thanks! I left a few more (quite small) nits. 

r=me once fixed

**Comment by nikomatsakis** [comment]
I'm assuming this will not make the 1.39 beta cutoff. If so, I think we should consider backporting it, as it resolves a "quality" issue for async await. Basically, the rustdoc for library facades that make use of `async fn` looks bad (it doesn't show that they are async fn). I wouldn't ordinarily nominate such a thing for backport, I don't think, but since async fn is a high priority feature, we can expect a lot of eyes on it, so I think it might be worth considering.

**Comment by Centril** [comment]
Yep, this won't make it to the cutoff as @Mark-Simulacrum is branching master to beta in an hour or so. Backporting this seems rather safe so it is reasonable I'd say.

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. Approved for beta backport.
