### PR TITLE
Include type name in symbol for methods

### LINKED ISSUE #30260: Symbol names with <impl> are too obscure
Symbol names of methods don't include the type name, instead they use the string `<impl>`.

Obscure symbol names makes reading backtraces, profiling and debugging harder.

Examples:

- `_$LT$impl$GT$::with_capacity::h1e508e0577f260f2tka` for `Vec::with_capacity`.
- `isomorphism::_$LT$impl$GT$::new::new::h10192896492405891948` 
for an item named `isomorphism::Vf2State::new`; with the type name gone, it's 
hard to directly understand which method it is

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #30260.

### CODE REVIEW

**Comment by bluss** [comment]
Nice! :balloon:

File: src/librustc/front/map/definitions.rs [hunk 1]
```diff
@@ -212,10 +213,6 @@ impl DefPathData {
                 InternedString::new("?")
             }
 
-            Impl => {
-                InternedString::new("<impl>")
-            }
-
```
Comment (eddyb) [inline src/librustc/front/map/definitions.rs]: I was hoping this could be combined with the actual type info to produce the full name.
Right now, the `ast::Item` name for impls is a hacky composition of the pretty-printed AST type and trait and I wish we could get rid of it.
