### PR TITLE
The const propagator cannot trace references.

### LINKED ISSUE #73609: ConstProp miscompilation around references
https://github.com/rust-lang/rust/pull/71911 introduced a (nightly-to-nightly) regression in mir-opt-level=3: since that landed, [this assertion](https://github.com/rust-lang/miri/blob/31ad5f6b2b93f78d3366c0654609f4b685043ec9/tests/run-pass/union.rs#L21) fails when running the test in Miri.

### PR DESCRIPTION
**Pull request by oli-obk**
Thus we avoid propagation of a local the moment we encounter references to it.

fixes #73609 

cc @RalfJung 

r? @wesleywiser

### CODE REVIEW

File: src/librustc_mir/transform/const_prop.rs [hunk 1]
```diff
@@ -578,6 +578,13 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
             Rvalue::Ref(_, _, place_ref) => {
                 trace!("skipping Ref({:?})", place_ref);
 
+                // This may be creating mutable refernces or immutable references to cells.
+                // If that happens, the pointed to value could be mutated via that reference.
+                // Since we aren't tracking references, the const propagator loses track off what
```
Comment (jonas-schievink) [inline src/librustc_mir/transform/const_prop.rs:583]:
```suggestion
                // Since we aren't tracking references, the const propagator loses track of what
```

File: src/librustc_mir/transform/const_prop.rs [hunk 2]
```diff
@@ -578,6 +578,13 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+                // value the local has right now.
+                // Thus we preemptively erase any local that has its reference taken.
+                Self::remove_const(&mut self.ecx, place_ref.local);
```
Comment (RalfJung) [inline src/librustc_mir/transform/const_prop.rs:586]: `Rvalue::AddrOf` should likely do something similar?

**Comment by RalfJung** [comment]
Given how big and fundamental this flaw is, I wonder how it was possible that this even landed? I am starting to be increasingly worried about the correctness of our optimizations.^^ Any bug here is critical, and the code is easy to get wrong.

File: src/test/ui/const_prop_miscompile.rs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+// run-pass
+
+fn main() {
+    let mut u = (1,);
+    *&mut u.0 = 5;
```
Comment (RalfJung) [inline src/test/ui/const_prop_miscompile.rs:5]: Please also add a test with `&raw mut`.

File: src/test/ui/const_prop_miscompile.rs [hunk 4]
```diff
@@ -0,0 +1,7 @@
+// run-pass
```
Comment (RalfJung) [inline src/test/ui/const_prop_miscompile.rs:1]: Is the root `ui` folder really the best place for this test?

Comment (oli-obk) [reply src/test/ui/const_prop_miscompile.rs:1]: We don't have an appropriate folder for this in `ui`.

**Comment by oli-obk** [comment]
> Given how big and fundamental this flaw is, I wonder how it was possible that this even landed?

An oversight on my side. I put most of the time in that review into the other `NoPropagation` -> `OnlyPropagateInto` change, and assumed the other change was benign.

File: src/test/ui/const_prop_miscompile.rs (hunk 4 above)
Comment (RalfJung) [reply src/test/ui/const_prop_miscompile.rs:1]: What about creating a mir-opt folder or so?

**Comment by RalfJung** [comment]
I guess more constructively said: is there something we can do -- with types or tests or whatever -- to reduce the likelihood of such oversights? In Miri we have a couple of safety nets in place because the code is so tricky; this here is arguably even trickier so it is not very surprising that mistakes happen.

File: src/librustc_mir/transform/const_prop.rs [hunk 5]
```diff
@@ -578,6 +578,13 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
             Rvalue::Ref(_, _, place_ref) => {
                 trace!("skipping Ref({:?})", place_ref);
 
+                // This may be creating mutable refernces or immutable references to cells.
```
Comment (lcnr) [inline src/librustc_mir/transform/const_prop.rs:581]:
```suggestion
                // This may be creating mutable references or immutable references to cells.
```

File: src/test/ui/const_prop_miscompile.rs (hunk 4 above)
Comment (wesleywiser) [reply src/test/ui/const_prop_miscompile.rs:1]: There is a `mir` folder https://github.com/rust-lang/rust/tree/master/src/test/ui/mir

Comment (oli-obk) [reply src/test/ui/const_prop_miscompile.rs]: I moved it to `mir-opt`

**Comment by oli-obk** [comment]
> I guess more constructively said: is there something we can do -- with types or tests or whatever -- to reduce the likelihood of such oversights?

Idk, there's some research work on proving the correctness of optimizations, but that's likely either impossible for us here or too slow in practice since we'd have to write the optimizations in some scheme that allows running proofs on it.

The typical const prop bug (propping something it should not) will likely be eliminated for good once we move to dataflow based const propping, because then we're using a single scheme that we can verify which isn't entangled with the actual individual const propping logic, which is much easier to check for correctness.

**Comment by RalfJung** [comment]
> Idk, there's some research work on proving the correctness of optimizations, but that's likely either impossible for us here or too slow in practice since we'd have to write the optimizations in some scheme that allows running proofs on it.

Wanted: Alive2 for MIR. ;) (see [this blog post](https://blog.regehr.org/archives/1737))

File: src/test/mir-opt/const_prop/bad_op_unsafe_oob_for_slices/64bit/rustc.main.ConstProp.diff [hunk 6]
```diff
@@ -46,22 +46,8 @@
                                            // mir::Constant
                                            // + span: $DIR/bad_op_unsafe_oob_for_slices.rs:7:23: 7:24
                                            // + literal: Const { ty: usize, val: Value(Scalar(0x0000000000000003)) }
--         _7 = Len((*_1));                 // scope 2 at $DIR/bad_op_unsafe_oob_for_slices.rs:7:18: 7:25
```
Comment (oli-obk) [inline src/test/mir-opt/const_prop/bad_op_unsafe_oob_for_slices/64bit/rustc.main.ConstProp.diff:49]: this is "fallout" of checking for `Rvalue::AddressOf`. I think we should exhaustively match every enum in const prop to prevent such things from falling through.

File: src/librustc_mir/transform/const_prop.rs [hunk 7]
```diff
@@ -575,8 +575,16 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
+            Rvalue::AddressOf(_, place) | Rvalue::Ref(_, _, place) => {
+                trace!("skipping AddressOf | Ref for {:?}", place);
+
+                // This may be creating mutable references or immutable references to cells.
+                // If that happens, the pointed to value could be mutated via that reference.
+                // Since we aren't tracking references, the const propagator loses track of what
+                // value the local has right now.
+                // Thus, all locals that have their reference taken
+                // must not take part in propagation.
+                Self::remove_const(&mut self.ecx, place.local);
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs:587]: I tried simply asserting here, but that won't work for

* zsts or
* locals that got a reference assigned from a constant instead of an `Rvalue::Ref` and are now hitting this `Rvalue::Ref` because the reference is getting reborrowed. This is basically `Projection::Deref` biting us again
* arguments, because they don't get marked as `NoPropagation`

File: src/librustc_mir/transform/const_prop.rs [hunk 8]
```diff
@@ -781,7 +792,9 @@ impl<'tcx> Visitor<'tcx> for CanConstProp {
                         // end of the block anyway, and inside the block we overwrite previous
                         // states as applicable.
                         ConstPropMode::OnlyInsideOwnBlock => {}
-                        other => {
+                        ConstPropMode::NoPropagation => {}
+                        ConstPropMode::OnlyPropagateInto => {}
+                        other @ ConstPropMode::FullConstProp => {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs:797]: Part of exhaustively matching on things, but also part of the bugfix, because we don't go from `NoPropagation` to `OnlyPropagateInto` anymore.

File: src/librustc_mir/transform/const_prop.rs [hunk 9]
```diff
@@ -813,7 +826,7 @@ impl<'tcx> Visitor<'tcx> for CanConstProp {
             | MutatingUse(MutatingUseContext::Borrow)
             | MutatingUse(MutatingUseContext::AddressOf) => {
                 trace!("local {:?} can't be propagaged because it's used: {:?}", local, context);
-                self.can_const_prop[local] = ConstPropMode::OnlyPropagateInto;
+                self.can_const_prop[local] = ConstPropMode::NoPropagation;
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs:829]: Main part of the bugfix, while we can do things for borrows, this is super hard to reason about and I don't think we should do it without dataflow

File: src/librustc_mir/transform/const_prop.rs [hunk 10]
```diff
@@ -858,19 +871,22 @@ impl<'mir, 'tcx> MutVisitor<'tcx> for ConstPropagator<'mir, 'tcx> {
...
-                            place.local
-                        );
-                        self.locals_of_current_block.insert(place.local);
-                    }
-
-                    if can_const_prop == ConstPropMode::OnlyPropagateInto {
-                        trace!("can't propagate into {:?}", place);
-                        if place.local != RETURN_PLACE {
-                            Self::remove_const(&mut self.ecx, place.local);
+                    match can_const_prop {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs:874]: more exhaustively matching.

File: src/librustc_mir/transform/const_prop.rs [hunk 11]
```diff
@@ -890,6 +906,12 @@ impl<'mir, 'tcx> MutVisitor<'tcx> for ConstPropagator<'mir, 'tcx> {
                     );
                     Self::remove_const(&mut self.ecx, place.local);
                 }
+            } else {
```
Comment (oli-obk) [inline src/librustc_mir/transform/const_prop.rs:909]: This arm didn't exist before, it's the `else` for the `layout_of` check. If we can't compute the layout, erase anything that's in that local, even if I don't think that it can actually happen that there's something in the local.

**Comment by wesleywiser** [comment]
Looks like ui tests just need to be blessed.

**Comment by oli-obk** [comment]
blessed ui tests

**Comment by wesleywiser** [comment]
Now the 32-bit MIR tests need to be blessed. r=me with that.

**Review by wesleywiser — APPROVED** [review]

**Comment by RalfJung** [comment]
Critical codegen bug.
@bors p=1

**Comment by Dylan-DPC** [comment]
bumping priority 
@bors p=3

File: src/librustc_mir/transform/const_prop.rs [hunk 12]
```diff
@@ -575,8 +575,16 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
             }
 
             // Do not try creating references (#67862)
-            Rvalue::Ref(_, _, place_ref) => {
-                trace!("skipping Ref({:?})", place_ref);
+            Rvalue::AddressOf(_, place) | Rvalue::Ref(_, _, place) => {
```
Comment (RalfJung) [inline src/librustc_mir/transform/const_prop.rs:578]: Maybe this `match` should also be made exhaustive? It currently has a fallback case, basically assuming "every rvalue I don't know will definitely be harmless". That seems like a rather strong assumption.

**Comment by jonas-schievink** [comment]
Looks like this missed the beta cutoff, so the miscompilation is now on stable https://github.com/rust-lang/rust/issues/74739

**Comment by mlindner** [comment]
How did stable ever get released with this bug?

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting; stable-accepted

**Comment by cuviper** [comment]
This made it to stable in 1.45.1 via #74746.
