### PR TITLE
alloc_system: Handle failure properly

### LINKED ISSUE #32993: liballoc_system's unix __rust_reallocate doesn't handle allocation failures for over-aligned types
The Unix implementation of `__rust_reallocate` in `liballoc_system` boils down to:

```rust
    pub unsafe fn reallocate(ptr: *mut u8, old_size: usize, size: usize, align: usize) -> *mut u8 {
        if align <= MIN_ALIGN {
            libc::realloc(ptr as *mut libc::c_void, size as libc::size_t) as *mut u8
        } else {
            let new_ptr = allocate(size, align);
            ptr::copy(ptr, new_ptr, cmp::min(size, old_size));
            deallocate(ptr, old_size, align);
            new_ptr
        }
    }
```

The `else` branch of the conditional doesn't properly handle the case where `allocate` fails.  For comparison's sake, the Windows implementation says:

```rust
    pub unsafe fn reallocate(ptr: *mut u8, _old_size: usize, size: usize, align: usize) -> *mut u8 {
        if align <= MIN_ALIGN {
            HeapReAlloc(GetProcessHeap(), 0, ptr as LPVOID, size as SIZE_T) as *mut u8
        } else {
            let header = get_header(ptr);
            let new = HeapReAlloc(GetProcessHeap(),
                                  0,
                                  header.0 as LPVOID,
                                  (size + align) as SIZE_T) as *mut u8;
            if new.is_null() {
                return new;
            }
            align_ptr(new, align)
        }
    }
```

### PR DESCRIPTION
**Pull request by alexcrichton**
The Unix implementation was incorrectly handling failure for reallocation of
over-aligned types by not checking for NULL.

Closes #32993

### CODE REVIEW

File: src/liballoc_system/lib.rs [hunk 1]
```diff
@@ -96,8 +96,10 @@ mod imp {
             libc::realloc(ptr as *mut libc::c_void, size as libc::size_t) as *mut u8
         } else {
             let new_ptr = allocate(size, align);
-            ptr::copy(ptr, new_ptr, cmp::min(size, old_size));
-            deallocate(ptr, old_size, align);
+            if !new_ptr.is_null() {
+                ptr::copy(ptr, new_ptr, cmp::min(size, old_size));
+                deallocate(ptr, old_size, align);
```
Comment (nagisa) [inline src/liballoc_system/lib.rs]: We should `deallocate` this memory despite of failure in allocating new_ptr.

**Comment by nagisa** [comment]
r=me with comment fixed.

File: src/liballoc_system/lib.rs (hunk 1 above)
Comment (nagisa) [inline src/liballoc_system/lib.rs]: Oh, never mind me.

The manual for `realloc` says:

> If the area pointed to was moved, a free(ptr) is done.

So it is required for memory to not get moved if move fails.
