### PR TITLE
Fix outdated doc comment

### LINKED ISSUE #138572: rustdoc::clean::types::Type::is_doc_subtype_of has outdated example, and arguments are flipped
it seems weird (and likely a mistake) to say `T` is a subtype of `u8`.  the example refers to the function as `is_same`, so perhaps the name was changed without thinking if the semantics make sense?

### PR DESCRIPTION
**Pull request by Kivooeo**
This updates the documentation comment for `Type::is_doc_subtype_of` to more accurately describe its purpose as a subtyping check, rather than equality

fixes rust-lang/rust#138572

r? @tgross35

### CODE REVIEW

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -1534,10 +1534,10 @@ impl Type {
         matches!(self, Type::Path { path: Path { res: Res::Def(DefKind::TyAlias, _), .. } })
     }
 
-    /// Check if two types are "the same" for documentation purposes.
+    /// Check if this type is a subtype of another type for documentation purposes.
```
Comment (lolbinarycat) [inline src/librustdoc/clean/types.rs:1537]: I feel like the current behavior of the function is closer to checking if another type is a subtype of this type (this was the argument flipping I mentioned in the original issue). 

Maybe my intuition is backwards, so I would wait for a second opinion before renaming the function or anything, but at the very least it should at least have a not of how generics are handled.

File: src/librustdoc/clean/types.rs [hunk 2]
```diff
@@ -1534,10 +1534,10 @@ impl Type {
...
     ///
     /// This is different from `Eq`, because it knows that things like
-    /// `Placeholder` are possible matches for everything.
+    /// `Placeholder` and generics have special subtyping rules.
```
Comment (lolbinarycat) [inline src/librustdoc/clean/types.rs]:
```suggestion
    /// `Infer` and generics have special subtyping rules.
```

I'm assuming this enum variant got renamed at some point.

Comment (Kivooeo) [reply src/librustdoc/clean/types.rs]: I did small research about this, and found this place, do you think it also will be reasonable to replace `Placeholder` with `Infer` here?

https://github.com/rust-lang/rust/blob/e1b9081e699065badfc1a9419ec9566e5c8615c4/src/librustdoc/clean/types.rs#L1589-L1590

Comment (lolbinarycat) [reply src/librustdoc/clean/types.rs]: that would make the comment less helpful IMO, as the name of the type is clear from the following line anyways.  It's also using "Placeholders" as just a regular word, since there's no inline code block, unlike in the doc comment.  The doc comment should make sense without the context of the code, this only needs to make sense in context.

**Comment by Kivooeo** [comment]
Changed `Placeholder` with `Infer` in doc comment for now

File: src/librustdoc/clean/types.rs (hunk 1 above)
Comment (Kivooeo) [reply src/librustdoc/clean/types.rs:1537]: It seems to me that function is working exactly like `self.is_doc_subtype_of(other)` and example in doc comment showing it 

```
let generic = Type::Generic(rustc_span::symbol::sym::Any);
let unit = Type::Primitive(PrimitiveType::Unit);
assert!(unit.is_doc_subtype_of(&generic, &cache));
```

it reads like "unit is subtype of generic" which is true, or am I missing something?

**Comment by tgross35** [comment]
> r? @tgross35

Why me? This is a rustdoc change

r? rustdoc

**Comment by Kivooeo** [comment]
For some reasons I thought that you are in rustdoc and was like "I guess rustbot will assign Trevor anyway" 😅

**Comment by tgross35** [comment]
Even if I was, anybody on the relevant teams can do doc reviews :)
