### PR TITLE
Only instantiate binder during dyn's built-in trait candidate probe once

### LINKED ISSUE #117602: Nightly 65e297d1e 2023-11-03 fails to infer auto traits
The type `aho_corasick::AhoCorack` is not inferred to be `Send + Sync` by the above mentioned nightly release, c.f. https://github.com/quickwit-oss/tantivy/actions/runs/6759263517/job/18371750242?pr=2239 Using the stable, the code compiles with out issue.

EDIT: It seems to be related to GAT, i.e. a more minimal reproducer is:

```rust
trait SomethingSomething: Send {}

struct Wrapper<T> {
    something: Box<dyn SomethingSomething>,
    other: T,
}

trait HasSend {
    type IsSend<T: Send>: Send;
}

impl<T> HasSend for Wrapper<T> {
    type IsSend<S: Send> = Wrapper<S>;
}
```

which similarly fails on nightly and builds on stable.

<details>
<summary>More details</summary>

```console
> rustc --crate-type=lib nightly-auto-trait.rs 
error[E0277]: `(dyn SomethingSomething + 'static)` cannot be sent between threads safely
   --> nightly-auto-trait.rs:13:28
    |
13  |     type IsSend<S: Send> = Wrapper<S>;
    |                            ^^^^^^^^^^ `(dyn SomethingSomething + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn SomethingSomething + 'static)`
    = note: required for `Unique<(dyn SomethingSomething + 'static)>` to implement `Send`
note: required because it appears within the type `Box<dyn SomethingSomething>`
   --> /home/adam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:195:12
    |
195 | pub struct Box<
    |            ^^^
note: required because it appears within the type `Wrapper<S>`
   --> nightly-auto-trait.rs:3:8
    |
3   | struct Wrapper<T> {
    |        ^^^^^^^
note: required by a bound in `HasSend::IsSend`
   --> nightly-auto-trait.rs:9:27
    |
9   |     type IsSend<T: Send>: Send;
    |                           ^^^^ required by this bound in `HasSend::IsSend`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

on the above-mentioned nightly version whereas stable is happy

```console
> rustc +stable --crate-type=lib nightly-auto-trait.rs 
warning: fields `something` and `other` are never read
 --> nightly-auto-trait.rs:4:5
  |
3 | struct Wrapper<T> {
  |        ------- fields in this struct
4 |     something: Box<dyn SomethingSomething>,
  |     ^^^^^^^^^
5 |     other: T,
  |     ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted
```

Simply asserting that `Wrapper` is `Send + Sync` via e.g. `fn is_send_sync<T: Send + Sync>(_: T) {}` works on stable and nightly.

</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
See UI test for demonstration of the issue.

This was "caused" by #117131, but only because we're using the `normalize_param_env` (which has been augmented with a projection clause used to normalize GATs) which features non-lifetime bound vars in it.

Fixes #117602 technically, though that's also fixed by #117542.

r? types

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 1]
```diff
@@ -628,7 +628,10 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
         }
 
         self.infcx.probe(|_snapshot| {
-            if obligation.has_non_region_late_bound() {
+            // FIXME(non_lifetime_binders): Really, we care only to check that we don't
+            // have any non-region *escaping* bound vars, but that's hard to check and
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:632]: Can't we just augment `HasEscapingVarsVisitor` with the bound var kind we are looking for and create `TypeVisitableExt::has_escaping_non_lifetime_bound_vars` ?

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:632]: I'm not certain how that would work given the implementation of the visitor, since outer_exclusive_binder returns a debruijn index and does no additional walking

Comment (fmease) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:632]: Hmm, I guess you are right. It's more involved than I thought.

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 2]
```diff
@@ -628,7 +628,10 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+            // we shouldn't really ever encounter those anyways.
+            if obligation.self_ty().has_non_region_late_bound() {
```
Comment (aliemjay) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:634]: I think this is reachable in the code below. If so, please either remove the comment or update it to refer a new issue or to a known-bug ui test.
```rust
// known-bug
#![feature(non_lifetime_binders)]

fn trivial<A>()
where
    for<'a> dyn Fn(A, &'a u8): Fn(A, &'a u8),
{
}

fn main() {
    trivial::<u8>(); //~ ERROR
}
```

**Review by aliemjay — COMMENTED** [review]
r=me with the nit

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs (hunk 2 above)
Comment (aliemjay) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:634]: *updated the example

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:634]: Sorry, I should've been more clear in this comment. I will add a known-bug and update the comment to say it's not reachable **without `feature(non_lifetime_binders)`**.

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:634]: Wait, why don't I just fix this the right way? 😆

**Comment by compiler-errors** [comment]
Fixed this the *right* way by not instantiating the binder twice, but only once during the probe.
