### PR TITLE
Suggest `#[derive(Default)]` to enums with `#[default]`

### LINKED ISSUE #95226: #[default] without #[derive(Default)] could suggest adding #[derive(Default)]
Given the following code: https://gist.github.com/cbe5d4fb00ed34650d2873725eefbc67

```rust
pub enum Test {
    #[default]
    First,
    Second,
}
```

The current output is:

```
error: cannot find attribute `default` in this scope
 --> src/lib.rs:2:7
  |
2 |     #[default]
  |       ^^^^^^^
```

Ideally the output should suggest adding a `#[derive(Default)]` attribute to the enum. Bonus points if it detects an existing `derive` attribute and merely adds to the list, rather than adding a new attribute.

Note that this depends on the `derive_default_enum` feature, which will soon be stabilised as of the FCP in #87517.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
fixes #95226

### CODE REVIEW

File: compiler/rustc_resolve/src/macros.rs [hunk 1]
```diff
@@ -769,6 +769,15 @@ impl<'a> Resolver<'a> {
                     let expected = kind.descr_expected();
                     let msg = format!("cannot find {} `{}` in this scope", expected, ident);
                     let mut err = self.session.struct_span_err(ident.span, &msg);
+                    if ident.to_string() == "default"
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/macros.rs:772]: (nit: you could also do `ident.name == kw::default` to avoid the `to_string` by comparing just `Symbol`s)

File: compiler/rustc_resolve/src/macros.rs [hunk 2]
```diff
@@ -769,6 +769,15 @@ impl<'a> Resolver<'a> {
...
+                        && let ModuleKind::Def(DefKind::Enum, def_id, _) = parent_scope.module.kind
+                        && let Some(span) = self.opt_span(def_id)
+                    {
+                        err.span_help(
+                            self.session.source_map().guess_head_span(span),
+                            "consider adding `#[derive(Default)]` to this enum"
+                        );
+                    }
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/macros.rs:780]: Can you put this into `unresolved_macro_suggestions` fn below, since this seems like an unresolved macro suggestion?

File: compiler/rustc_resolve/src/macros.rs [hunk 3]
```diff
@@ -769,6 +769,15 @@ impl<'a> Resolver<'a> {
...
                     let msg = format!("cannot find {} `{}` in this scope", expected, ident);
                     let mut err = self.session.struct_span_err(ident.span, &msg);
+                    if ident.to_string() == "default"
+                        && let ModuleKind::Def(DefKind::Enum, def_id, _) = parent_scope.module.kind
+                        && let Some(span) = self.opt_span(def_id)
+                    {
+                        err.span_help(
+                            self.session.source_map().guess_head_span(span),
+                            "consider adding `#[derive(Default)]` to this enum"
+                        );
```
Comment (fee1-dead) [inline compiler/rustc_resolve/src/macros.rs:779]: This should ideally be `span_suggestion` using `span_to_snippet` on the source map.

File: src/test/ui/enum/suggest-default-attribute.rs [hunk 4]
```diff
@@ -0,0 +1,7 @@
+pub enum Test {
+    #[default] //~ ERROR cannot find attribute `default` in this scope
```
Comment (fee1-dead) [inline src/test/ui/enum/suggest-default-attribute.rs:2]: nit: you should also include `//^ HELP consider adding...`

File: src/test/ui/enum/suggest-default-attribute.rs [hunk 5]
```diff
@@ -0,0 +1,7 @@
+pub enum Test {
```
Comment (fee1-dead) [inline src/test/ui/enum/suggest-default-attribute.rs:1]: We should also suggest changing the attribute to `derive(Default)` if they meant it by annotating a `struct` or `enum` with `#[default]`, although this does not need to be in this PR. could be a followup.

**Review by fee1-dead — APPROVED** [review]
LGTM, I will prepare a follow-up.
