### PR TITLE
fix incorrect path resolution in tidy

### LINKED ISSUE #122202: x.py test --bless tidy step does not work outside of root dir
I tried this: In a subdirectory `root/objdir/`, after a successful build, I then did `../x.py test --stage 1 --bless`

I expected to see this happen: *The test files that need updating get updated."

Instead, this happened: *tidy panicked*

```
[...]
tidy check
thread 'ui_tests (tests)' panicked at src/tools/tidy/src/ui_tests.rs:191:77:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/tools/tidy/src/main.rs:55:61:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

I believe this is because of this code, which seems to contain an assumption that the current_dir will be the root of the source tree, which is not true in general for `x.py`:

https://github.com/rust-lang/rust/blob/74acabe9b042ea8c42862ee29aca2a8b7d333644/src/tools/tidy/src/ui_tests.rs#L187

### PR DESCRIPTION
**Pull request by onur-ozkan**
Previously, reading the current path from the environment led to failure when invoking x from outside the source root. This change fixes this issue by passing the already resolved root path into `ui_tests::check`.

Fixes #122202

### CODE REVIEW

File: src/tools/tidy/src/ui_tests.rs [hunk 1]
```diff
@@ -184,7 +185,7 @@ pub fn check(path: &Path, bless: bool, bad: &mut bool) {
 */
 [
 "#;
-        let tidy_src = std::env::current_dir().unwrap().join("src/tools/tidy/src");
+        let tidy_src = PathBuf::from(env::args_os().nth(1).unwrap()).join("src/tools/tidy/src");
```
Comment (compiler-errors) [inline src/tools/tidy/src/ui_tests.rs:188]: This solution is really unnecessarily cryptic, imo. A better solution would be to pass in the `root_path` here rather than the `tests_path`:

https://github.com/rust-lang/rust/blob/a655e648a9f94d74263108366b83e677af56e35d/src/tools/tidy/src/main.rs#L105

And then adjust the rest of this file to operate from the root, rather than the test dir.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: src/tools/tidy/src/issues.txt [hunk 2]
```diff
@@ -183,8 +183,8 @@
 "ui/async-await/issue-67651.rs",
 "ui/async-await/issue-67765-async-diagnostic.rs",
 "ui/async-await/issue-68112.rs",
-"ui/async-await/issue-68523.rs",
 "ui/async-await/issue-68523-start.rs",
+"ui/async-await/issue-68523.rs",
```
Comment (klensy) [inline src/tools/tidy/src/issues.txt:187]: PR shouldn't affect ordering here, why it changed?

Comment (compiler-errors) [reply src/tools/tidy/src/issues.txt:187]: preexisting: these weren't sorted, see https://github.com/rust-lang/rust/pull/122161#discussion_r1517107993

Comment (workingjubilee) [reply src/tools/tidy/src/issues.txt:187]: @onur-ozkan Can you rebase this? It should remove these diffs since master should contain the relevant fix.
