### PR TITLE
Fix rendering 'const' in header for intrinsics

### LINKED ISSUE #99398: `core::mem::transmute` doesn't list `const` in the signature
`core::mem::transmute` and `std::mem::transmute` are **both** listed as const in 1.56 according to the "since" info on the right, but **only** the `std` version lists `const` in the actual signature.

core:
```
pub unsafe extern "rust-intrinsic" fn transmute<T, U>(e: T) -> U
```

std:
```
pub const unsafe extern "rust-intrinsic" fn transmute<T, U>(e: T) -> U
```

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #99398

### CODE REVIEW

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -676,15 +676,23 @@ impl Item {
...
                 hir::FnHeader {
                     unsafety: if abi == Abi::RustIntrinsic {
                         intrinsic_operation_unsafety(tcx, self.item_id.as_def_id().unwrap())
                     } else {
                         hir::Unsafety::Unsafe
                     },
                     abi,
-                    constness: hir::Constness::NotConst,
+                    constness: if abi == Abi::RustIntrinsic
+                        && tcx.is_const_fn(def_id)
```
Comment (clubby789) [inline src/librustdoc/clean/types.rs:689]: Not sure if `"rust-intrinsic"` can ever be `const fn` or if they can only be `const` via `rustc_const_stable`

**Review by GuillaumeGomez — APPROVED** [review]
Apart from your question, looks good to me. Thanks!

File: src/librustdoc/clean/types.rs (hunk 1 above)
Comment (clubby789) [reply src/librustdoc/clean/types.rs:689]: Coming back to this, `is_const_fn` must be true since it's working in a chain of `&&`. It looks like `is_const_fn` takes account of raw const functions and const stable ones.

Comment (Amanieu) [reply src/librustdoc/clean/types.rs:689]: We do have some const intrinsics like [`transmute`](https://doc.rust-lang.org/nightly/std/intrinsics/fn.transmute.html).

File: src/librustdoc/clean/types.rs [hunk 2]
```diff
@@ -676,15 +676,23 @@ impl Item {
...
+                let abi = tcx.fn_sig(def_id).abi();
                 hir::FnHeader {
                     unsafety: if abi == Abi::RustIntrinsic {
                         intrinsic_operation_unsafety(tcx, self.item_id.as_def_id().unwrap())
                     } else {
                         hir::Unsafety::Unsafe
                     },
                     abi,
-                    constness: hir::Constness::NotConst,
+                    constness: if abi == Abi::RustIntrinsic
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/types.rs:688]: Just realized it but: why the `abi` check?

Comment (clubby789) [reply src/librustdoc/clean/types.rs:688]: Mostly to mirror the above check. I'm assuming that "rust-intrinsic" is the only kind of `ForeignFunctionItem` which can be const so it seemed best to be conservative and only do the const checks for that kind.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:688]: Makes sense!
