### PR TITLE
Do not emit help when shorthand from macro when suggest `?` or `expect`

### LINKED ISSUE #140659: Malformed suggestion for E0308 when macros are involved
I don't have the time to minimize this right now so I've committed the intermediate state that produces a pretty weird suggestion that's invalid:

```
error[E0308]: mismatched types
    --> crates/wasm-encoder/src/reencode.rs:1727:9
     |
1727 |         wasmparser::for_each_operator!(translate)
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `Result<u32, <T as Reencode>::Error>`
     |
     = note: expected type `u32`
                found enum `core::result::Result<u32, <T as Reencode>::Error>`
     = note: this error originates in the macro `wasmparser::for_each_operator` (in Nightly builds, run with -Z macro-backtrace for more info)
help: use the `?` operator to extract the `core::result::Result<u32, <T as Reencode>::Error>` value, propagating a `Result::Err` value to the caller
     |
1727 |         wasmparser::for_each_operator!(translate): tag_index?
     |                                                  ++++++++++++
```

You can find the reproducing code at https://github.com/nagisa/wasm-tools/tree/weird-diagnostic and running `cargo check --all-features`.

Reproduces both on stable and nightly:

```
cargo 1.88.0-nightly (7918c7eb5 2025-04-27)
release: 1.88.0-nightly
commit-hash: 7918c7eb59614c39f1c4e27e99d557720976bdd7
commit-date: 2025-04-27
host: x86_64-unknown-linux-gnu
libgit2: 1.9.0 (sys:0.20.0 vendored)
libcurl: 8.12.1-DEV (sys:0.4.80+curl-8.12.1 vendored ssl:OpenSSL/3.4.1)
ssl: OpenSSL 3.4.1 11 Feb 2025
os: NixOS 25.5.0 [64-bit]
```

```
cargo 1.86.0 (adf9b6ad1 2025-02-28)
release: 1.86.0
commit-hash: adf9b6ad14cfa10ff680d5806741a144f7163698
commit-date: 2025-02-28
host: x86_64-unknown-linux-gnu
libgit2: 1.9.0 (sys:0.20.0 vendored)
libcurl: 8.12.0-DEV (sys:0.4.79+curl-8.12.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: NixOS 25.5.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #140659 

I didn't fully minimize the original bug, but I found a similar test case, and they have perhaps the same root cause. For the bug mentioned in #140659 , I also tested it locally and passed it.

Jieyou has worked on this part before, maybe r? @jieyouxu

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -2034,8 +2034,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         };
 
         let sugg = match self.tcx.hir_maybe_get_struct_pattern_shorthand_field(expr) {
+            Some(_) if expr.span.from_expansion() => return false,
```
Comment (chenyukang) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2037]: I think we can remove more invalid suggestions if we add:

```rust
     if expr.span.from_expansion() {
            return false;
        }
```

at the start of `suggest_missing_unwrap_expect`.

**Comment by jieyouxu** [comment]
r? chenyukang (since you're already looking at it, but I can take the review back if you're busy)

File: tests/ui/typeck/macro-shorthand-issue-140659.rs
Comment (jieyouxu) [inline tests/ui/typeck/macro-shorthand-issue-140659.rs:1]: Question: I *feel like* there's a `suggestion/` folder somewhere, but maybe I'm remembering another subfolder?

File: tests/ui/typeck/macro-shorthand-issue-140659.rs [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+                    // KEY POINT: Using field shorthand syntax where the compiler gets confused
+                    // Here tag_index is a Result<u32, E> but we're using it where u32 is expected
+                    Instruction::Suspend { tag_index } //~ ERROR mismatched types [E0308]
+                }
+            }
+        };
+    }
+
+    // This should give the specific error message with the wrong help suggestion
```
Comment (jieyouxu) [inline tests/ui/typeck/macro-shorthand-issue-140659.rs:48]: Question: do you mean "this previously gave the wrong help suggestion"? Or what do you mean by this comment?

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2037]: never mind, seems the above suggestion of https://github.com/rust-lang/rust/pull/141070/files#diff-a188fa3dba59dd225d4a65e08961d2937f6418bc6126716e001303bf946d6ee3R2018 could be valid for macro, such as https://github.com/chenyukang/rust/blob/c79bbfab78dcb0a72aa3b2bc35c00334b58bfe2e/tests/ui/typeck/question-mark-operator-suggestion-span.rs#L18

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 3]
```diff
@@ -2034,8 +2034,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             Some(ident) => format!(": {ident}{sugg}"),
-            None => sugg.to_string(),
+            _ => sugg.to_string(),
```
Comment (chenyukang) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2039]: No need to change this line here?

File: tests/ui/typeck/macro-shorthand-issue-140659.rs (hunk 2 above)
Comment (xizheyin) [reply tests/ui/typeck/macro-shorthand-issue-140659.rs:48]: lol...This is the comment I added in the first commit, but I forgot to delete it in the second commit.

File: tests/ui/typeck/macro-shorthand-issue-140659.rs
Comment (jieyouxu) [reply tests/ui/typeck/macro-shorthand-issue-140659.rs:1]: I don't mean `tests/ui/suggestions/` (IMO that's a really bad folder because it's so generic), I thought there was a `tests/ui/typeck/suggestions/` but maybe I was thinking of another folder.

File: tests/ui/typeck/suggestions/macro-shorthand-issue-140659.rs [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+
+                    // KEY POINT: Using field shorthand syntax where the compiler gets confused
+                    // Here tag_index is a Result<u32, E> but we're using it where u32 is expected
+                    Instruction::Suspend { tag_index } //~ ERROR mismatched types [E0308]
+                }
+            }
+        };
+    }
+
+    for_each_operator!(translate)
```
Comment (xizheyin) [inline tests/ui/typeck/suggestions/macro-shorthand-issue-140659.rs:48]: I delete the unused comment.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 5]
```diff
@@ -2034,6 +2034,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         };
 
         let sugg = match self.tcx.hir_maybe_get_struct_pattern_shorthand_field(expr) {
+            Some(_) if expr.span.from_expansion() => return false,
             Some(ident) => format!(": {ident}{sugg}"),
             None => sugg.to_string(),
```
Comment (xizheyin) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:2039]: Here remains unchanged.

File: tests/ui/typeck/suggestions/suggest-adding-missing-zero-to-floating-point-number.fixed
Comment (xizheyin) [inline tests/ui/typeck/suggestions/suggest-adding-missing-zero-to-floating-point-number.fixed:1]: I create `tests/ui/typeck/suggestions/` amd move some testcases to it.
