### PR TITLE
skip dyn keyword lint under macros

### LINKED ISSUE #56327: edition compatibility lints: Warning about `dyn` in a macro incorrectly
This code:

```rust
#![warn(rust_2018_compatibility)]

macro_rules! foo {
    () => {
        fn _foo() {
            let _x: Box<dyn Drop>;
        }
    }
}

foo!();
```

[when compiled](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015&gist=675981bcb1aa7b8745ab8367da524a05) under 2015 edition yields:

```
warning: `dyn` is a keyword in the 2018 edition
 --> src/lib.rs:6:25
  |
6 |             let _x: Box<dyn Drop>;
  |                         ^^^ help: you can use a raw identifier to stay compatible: `r#dyn`
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![warn(rust_2018_compatibility)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  = note: #[warn(keyword_idents)] implied by #[warn(rust_2018_compatibility)]
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
  = note: for more information, see issue #49716 <https://github.com/rust-lang/rust/issues/49716>
```

but the warning and suggestion are incorrect!

First reported at https://github.com/rust-lang/cargo/issues/6359

This also applies to [macro invocations](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015&gist=576740ac5638033d4eb302095c45eca6)

### PR DESCRIPTION
**Pull request by pnkfelix**
This PR is following my own intuition that `rustfix` should never inject bugs into working code (even if that comes at the expense of it failing to fix things that will become bugs).

Fix #56327

### CODE REVIEW

File: src/test/ui/dyn-keyword/dyn-2015-idents-in-macros-unlinted.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+mod outer_mod {
+    pub mod r#dyn {
+        pub struct r#dyn;
+    }
+}
+
+macro_rules! defn_has_dyn_idents {
+    ($arg:ident) => { ::outer_mod::dyn::dyn }
+}
```
Comment (Centril) [inline src/test/ui/dyn-keyword/dyn-2015-idents-in-macros-unlinted.rs]: Extend tests for macros 2.0?

Comment (pnkfelix) [reply src/test/ui/dyn-keyword/dyn-2015-idents-in-macros-unlinted.rs]: okay, I added src/test/ui/dyn-keyword/dyn-2015-idents-in-decl-macros-unlinted.rs for that
