### PR TITLE
bugfix: finalize resolutions of macros in trait positions 

### LINKED ISSUE #40845: Nonexisting macro is silently accepted in trait definition block
This compiles successfully on beta and nightly, but it should be an error.

```rust
trait Trait {
    wut!{ }
}

fn main() {
}
```
[(playground link)](https://play.rust-lang.org/?gist=c77a24bd3f8d440c5808dd348a0793f1&version=nightly&backtrace=0)

### Actual Result:

The program compiles successfully.

### Expected Result:

Compilation error (Rust 1.16 does this correctly)

```rust
rustc 1.16.0 (30cf806ef 2017-03-10)
error: macro undefined: 'wut!'
```

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #40845.
r? @nrc

### CODE REVIEW

File: src/librustc_resolve/macros.rs [hunk 1]
```diff
@@ -172,7 +172,6 @@ impl<'a> base::Resolver for Resolver<'a> {
             expansion: mark,
         };
         expansion.visit_with(&mut visitor);
-        self.current_module.unresolved_invocations.borrow_mut().remove(&mark);
```
Comment (jseyfried) [inline src/librustc_resolve/macros.rs]: unrelated: remove duplicated line (always a no-op)

**Comment by nikomatsakis** [comment]
Accepting for beta. Small patch, regression.

cc @rust-lang/compiler
