### PR TITLE
rustdoc: Call `initSidebarItems` in root module of crate

### LINKED ISSUE #85301: `cargo doc` no longer generates a nav list of all dependencies in the sidebar
Since i don't know which version, when running `cargo doc` on a project, the left sidebar of the docs no longer has a nav for all crates in the dependency graph. However, the documentation for all dependencies is still compiled.

### Steps to reproduce

1. Pick a Rust project with a few dependencies.
2. Run `cargo doc --open`
3. Expected: Left sidebar has a list of all dependencies, linking to each crate's local docs.
4. Got: No such thing.

### Version it worked on

It most recently worked on: I honestly don't remember. I update my nightly before every dev session. Allegedly that bug is 27 days old.

### Version with regression

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (ca82264ec 2021-05-09)
binary: rustc
commit-hash: ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by Stupremee**
r? @jsha 

Resolves #85301

### CODE REVIEW

File: src/librustdoc/html/render/mod.rs [hunk 1]
```diff
@@ -1746,8 +1746,7 @@ fn print_sidebar(cx: &Context<'_>, it: &clean::Item, buffer: &mut Buffer) {
         path = relpath
     );
     if parentlen == 0 {
-        // There is no sidebar-items.js beyond the crate root path
-        // FIXME maybe dynamic crate loading can be merged here
+        write!(buffer, "<script defer src=\"top-level-sidebar-items.js\"></script>",);
     } else {
         write!(buffer, "<script defer src=\"{path}sidebar-items.js\"></script>", path = relpath);
     }
```
Comment (jsha) [inline src/librustdoc/html/render/mod.rs:1752]: I think what we really want here, rather than generating a file with a different name, is to generate a file named `sidebar-items.js` in the doc root, and unconditionally write a script tag that loads it. So these two `if` branches would get collapsed into one.

File: src/librustdoc/html/render/context.rs [hunk 2]
```diff
@@ -623,6 +623,9 @@ impl<'tcx> FormatRenderer<'tcx> for Context<'tcx> {
             let js_dst = self.dst.join("sidebar-items.js");
             let v = format!("initSidebarItems({});", serde_json::to_string(&items).unwrap());
             scx.fs.write(&js_dst, &v)?;
+
+            let js_dst = self.dst.join("top-level-sidebar-items.js");
+            scx.fs.write(&js_dst, "initSidebarItems({});")?;
```
Comment (jsha) [inline src/librustdoc/html/render/context.rs:628]: I'm a little confused... reading the code above this: if the added code works to add a file at the top level, there should already be a sidebar-items.js at the top level.

Comment (Stupremee) [reply src/librustdoc/html/render/context.rs:628]: the `top-level` does not mean the top-level of the generated documentation, but is just an alternative name to distinguish between `initSidebarItems({})` and `initSidebarItems({ /* some items */})`

File: src/librustdoc/html/render/mod.rs (hunk 1 above)
Comment (Stupremee) [reply src/librustdoc/html/render/mod.rs:1752]: That's better yeah

**Comment by jsha** [comment]
Specifically by "top level" I'm thinking of e.g. https://doc.rust-lang.org/std/. But I'm now realizing there's also a per-module index.html that we need to fix up, and that's what you've fixed up so far. Am I on the right track here?

And we need to generate a separate top-level-sidebar-items.js because for the per-module index.html, we specifically _don't_ want to list all the extra stuff that's in the real sidebar-items.js?

**Comment by Stupremee** [comment]
No, the `index.html` that changes, is now the root-module, aka the crate itself.  https://doc.rust-lang.org/std/ is just a smart redirect of the web server and is the same as https://doc.rust-lang.org/std/index.html. Inside other modules we do not need to care, because inside a module the crates are not even shown, instead all items and stuff.

I think the new `sidebar-items.js` can also be put into the root of the documentation (`target/doc/sidebar-items.js`) because the root modules are created at `target/doc/std` so adding a `../` to the path will lead to `target/doc/sidebar-items.js`. This would also only create one file per doc build instead of putting a new file into every crate.

**Comment by Stupremee** [comment]
I pushed the changes that I meant in my last message. Maybe that helps to understand.

**Comment by jsha** [comment]
This is looking good! But when I build locally and visit file:///home/jsha/rust/rust/build/x86_64-unknown-linux-gnu/doc/std/index.html, I get a JS console error:

    Loading failed for the <script> with source “file:///home/jsha/rust/rust/build/x86_64-unknown-linux-gnu/doc/sidebar-items.js”.
    
And indeed that file doesn't exist. But `build/x86_64-unknown-linux-gnu/doc/sidebar-items1.54.0.js` does exist.

**Comment by Stupremee** [comment]
Does `write_minify` can append a toolchain version to the file? I can't reproduce it locally but that was my guess

**Comment by Stupremee** [comment]
Apparently, it does. Should the file just be written as an unversichert file or adjust the script tag to include the version?

**Comment by Nemo157** [comment]
It needs the version number if it's a cross-crate shared file (mostly for docs.rs purposes).

**Comment by Stupremee** [comment]
Ah, that makes sense. Do you think the `sidebar-items.js` should be toolchain specific? I would assume yes because then it can change between rustdoc versions without breaking existing docs, right?

**Comment by GuillaumeGomez** [comment]
Strangely, your fix looks very different than the one I wrote in https://github.com/rust-lang/rust/pull/84834/commits/4e22b32315dce11b241bd8d9a2ce53cff06d9d74

**Comment by jsha** [comment]
I think sidebar-items.js should not have a version number at the crate root, because it doesn't have a version number in other places, and it would confusing.

@GuillaumeGomez sorry I didn't realize there was already a fix in progress. I think we should plan on landing this one to fix the regression since it's much smaller.

**Comment by jsha** [comment]
Looks good to me in a local test. Thanks for working so quickly to fix.

@bors r+

**Comment by Nemo157** [comment]
If it's going to be unversioned, then it needs to be not in the shared files, otherwise docs.rs will have issues if the JS API ever changes. docs.rs can handle unversioned unshared files at the root of the doc-folder now, but I don't think doc.rust-lang.org can just by looking at the existing docs it hosts.

**Comment by Stupremee** [comment]
Alright. Then I will just revert my last commit!

**Comment by Stupremee** [comment]
I messed up the rebase. Whoops

File: src/librustdoc/html/render/mod.rs [hunk 3]
```diff
@@ -1745,12 +1745,17 @@ fn print_sidebar(cx: &Context<'_>, it: &clean::Item, buffer: &mut Buffer) {
...
-        // There is no sidebar-items.js beyond the crate root path
-        // FIXME maybe dynamic crate loading can be merged here
+        write!(
+            buffer,
+            "<script defer src=\"{}sidebar-items{}.js\"></script>",
+            relpath, cx.shared.resource_suffix
+        );
     } else {
-        write!(buffer, "<script defer src=\"{path}sidebar-items.js\"></script>", path = relpath);
+        write!(buffer, "<script defer src=\"{}sidebar-items.js\"></script>", relpath);
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:1756]: There is no need for this `else`. The `else` block is the same as the `if` but invalid: it needs to use `resource_suffix`.

File: src/librustdoc/html/render/write_shared.rs [hunk 4]
```diff
@@ -225,6 +225,8 @@ pub(super) fn write_shared(
     )?;
     write_minify("search.js", static_files::SEARCH_JS)?;
     write_minify("settings.js", static_files::SETTINGS_JS)?;
+    write_minify("sidebar-items.js", static_files::sidebar::ITEMS)?;
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/write_shared.rs:228]: Why this add? It shouldn't be needed.

File: src/librustdoc/html/render/mod.rs (hunk 3 above)
Comment (Nemo157) [reply src/librustdoc/html/render/mod.rs:1756]: No, the else block is loading the per-module one which is unsuffixed.

File: src/librustdoc/html/static/sidebar-items.js [hunk 5]
```diff
@@ -0,0 +1 @@
+initSidebarItems({});
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/sidebar-items.js:1]: Ah ok I see. Sorry but it's unneeded here. Please remove this file and all the linked code.

File: src/librustdoc/html/static_files.rs [hunk 6]
```diff
@@ -130,4 +130,7 @@ crate mod source_code_pro {
 crate mod sidebar {
     /// File script to handle sidebar.
     crate static SOURCE_SCRIPT: &str = include_str!("static/source-script.js");
+
+    /// Top Level sidebar items script which will load a sidebar without items.
+    crate static ITEMS: &str = include_str!("static/sidebar-items.js");
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static_files.rs:135]: Unneeded.

File: src/librustdoc/html/render/mod.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/mod.rs:1756]: Ah right, because this approach is like this... Ok, I think globally, this is just the wrong approach, I'll comment about it.

File: src/librustdoc/html/static/sidebar-items.js (hunk 5 above)
Comment (Nemo157) [reply src/librustdoc/html/static/sidebar-items.js:1]: Why is it uneeded? There needs to be this call _somewhere_, it doesn't currently exist in any JS.

**Comment by GuillaumeGomez** [comment]
So, the original issue is stating that we need to put back the crate list. Except that we don't need to do that per-module at all. I think this approach is very wrong. It adds a new file at every module level for information we already have.

**Comment by Stupremee** [comment]
It does not add a new file at every module :thinking: 
Only one shared `sidebar-items.js` which is loaded by the root module

File: src/librustdoc/html/static/sidebar-items.js (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/sidebar-items.js:1]: Because we already have the crate list stored and it's already accessible. I fixed it in #84834 without needing any of this.

**Comment by Nemo157** [comment]
This approach adds a single new _shared_ file, not even per-crate. This seems by far the simplest minimal change I can see to get backported onto beta to fix it there. It may be possible to simplify it as part of #84834 or other fixes in nightly, but we need to get something that can be backported first.

**Comment by GuillaumeGomez** [comment]
I can make #84834 much shorter by only putting back the crate list if you want in another PR. But I'm strongly against adding a new unneeded file.

**Comment by Stupremee** [comment]
I can also change this PR to use another fix. I just thought this is an easy way to call the `initSidebarItems` function and it would be fine.

**Comment by GuillaumeGomez** [comment]
@Stupremee: Sorry that you're in the middle of this. :-/ I should have included @jsha on my other PR's discussion, that would have prevented all the problems in here...

**Comment by Nemo157** [comment]
The only way I can see to do this without a new file (or some more major refactoring of how `main.js` generates the sidebar) is by adding an inline-script.

Testing #84834 locally it has an additional change in behaviour that it shows children instead of siblings in the sidebar.

**Comment by GuillaumeGomez** [comment]
Yes, this is what I said, I have two changes in my PR. I can extract the fix for the crate listing in another PR to keep the one under debate if you want.

**Comment by Stupremee** [comment]
> @Stupremee: Sorry that you're in the middle of this. :-/

No problem!

> Yes, this is what I said, I have two changes in my PR. I can extract the fix for the crate listing in another PR to keep the one under debate if you want.

That works too and might be the fastest solution.

**Comment by Nemo157** [comment]
We discussed [on discord](https://discord.com/channels/442252698964721669/459149231702278154/843194951320076318) and decided to go ahead with this as a first fix.

@bors r+

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/21853weekly2021052054818.html#239602893)

@rustbot label +beta-accepted
