### PR TITLE
when Miri tests are not passing, do not add Miri component

### LINKED ISSUE #60301: miri component gets shipped even though the tests fail
Looking at https://rust-lang.github.io/rustup-components-history/, it seems like Miri is getting shipped as a rustup component even though the tests fail. Unfortunately, Miri is currently entirely usable, so it'd probably be better if it did not get shipped in this state. Is that something we can do?

Cc @oli-obk

### PR DESCRIPTION
**Pull request by RalfJung**
Second attempt, this time based on the JSON files that exist since https://github.com/rust-lang/rust/pull/65274.

Fixes https://github.com/rust-lang/rust/issues/60301
r? @pietroalbini @alexcrichton

### CODE REVIEW

File: src/tools/build-manifest/src/main.rs [hunk 1]
```diff
@@ -375,6 +378,25 @@ impl Builder {
         }
     }
 
+    /// If a tool does not pass its tests, don't ship it.
+    /// Right now, we do this only for Miri.
+    fn check_toolstate(&mut self) {
+        let toolstates: Option<HashMap<String, String>> = try {
+            let toolstates = File::open(self.input.join("toolstates-linux.json")).ok()?;
+            serde_json::from_reader(&toolstates).ok()?
+        };
```
Comment (pietroalbini) [inline src/tools/build-manifest/src/main.rs]: Do we need an unstable feature just for that? It can be rewritten to:

```rust
File::open(self.input.join("toolstates-linux.json")).ok()
    .and_then(|toolstates| serde_json::from_reader(&toolstates).ok());
```

File: src/tools/build-manifest/src/main.rs [hunk 2]
```diff
@@ -375,6 +378,25 @@ impl Builder {
...
+        let toolstates = toolstates.unwrap_or_else(|| {
+            println!("WARNING: `toolstates-linux.json` missing; assuming all tools failed");
+            HashMap::default() // Use empty map if anything went wrong.
```
Comment (pietroalbini) [inline src/tools/build-manifest/src/main.rs]: Why did you choose this behavior instead of not doing anything if the file is missing/malformed?

**Review by emilyalbini — CHANGES_REQUESTED** [review]

File: src/tools/build-manifest/src/main.rs (hunk 1 above)
Comment (pietroalbini) [reply src/tools/build-manifest/src/main.rs]: To expand a bit on why I'd prefer not to use unstable features in this tool: the tool is not ran or tested by CI, but just by `promote-release` on central station. If there is a breaking change in try blocks or they get stabilized the release process would break until we notice nightlies are missing.

Comment (RalfJung) [reply src/tools/build-manifest/src/main.rs]: I just really like `try` blocks. ;)
But sure, I can refactor this.

File: src/tools/build-manifest/src/main.rs (hunk 2 above)
Comment (RalfJung) [reply src/tools/build-manifest/src/main.rs]: If we don't do anything we'll probably never notice that reading the file failed. This seemed like the safer default.

Comment (pietroalbini) [reply src/tools/build-manifest/src/main.rs]: That's fair.

**Comment by pietroalbini** [comment]
@bors r+

Thanks! If Alex has comments feel free to r-.
