### PR TITLE
Fix weird rustdoc output when single and glob reexport conflict on a name

### LINKED ISSUE #143107: [rustdoc] adding docs on a reexport that shadows a glob reexport does not work properly
# Code

```rust
mod raw {
    pub fn foo() {}
}

/// Foobar
///
/// Baz
pub use raw::foo;

pub use raw::*;
```

# Reproduction Steps

1. `cargo doc --open`
2. click on the link to `foo`

# Expected Outcome

The "foobaz bar" docs show up.

# Actual Output

No docs on `fn.foo.html`

Image

# Version

rustdoc 1.88.0 (6b00bc388 2025-06-23)

# Additional Details
Oddly, the module summary contains the correct docs.

Image

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#143107.

The problem was that the second reexport would overwrite the first, leading to having unexpected results. To fix it, I now group items by their original `DefId` and their name and keep tracks of all imports for this item (should very rarely be more than one though, and even less often more than 2).

cc @lolbinarycat

### CODE REVIEW

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -152,8 +152,12 @@ pub(crate) fn try_inline(
     };
 
     cx.inlined.insert(did.into());
+    let import_def_ids: &[LocalDefId] = match import_def_id {
```
Comment (lolbinarycat) [inline src/librustdoc/clean/inline.rs]: can't Option::as_slice be used here?

File: src/librustdoc/visit_ast.rs [hunk 2]
```diff
@@ -32,11 +32,28 @@ pub(crate) struct Module<'hir> {
...
+    /// }
+    ///
+    /// /// Foobar
+    /// pub use raw::foo;
+    ///
+    /// pub use raw::*;
+    /// ```
+    ///
+    /// So in this case, we don't want to have two items but just one with attributes from both
+    /// imports to be merged.
```
Comment (lolbinarycat) [inline src/librustdoc/visit_ast.rs]: is merging the attributes correct? i thought that [per the reference](https://doc.rust-lang.org/reference/items/use-declarations.html#r-items.use.glob.shadowing), only items not shadowed by non-glob imports would actually be shadowed.  i guess that doesn't exactly say what happens when you shadow a glob import with an identical item...

not that i see putting docs on glob imports to be a common usecase, i think much more common is docs on the regular import and no docs on the glob import.

**Comment by GuillaumeGomez** [comment]
Ah bad luck. A function I modified was used in a more up-to-date version. ^^'

Anyway, rebased and fixed the CI failure.

**Review by lolbinarycat — COMMENTED** [review]
some things could use clarification.  i don't entirely understand if things are getting merged or overwritten.  the unit test comment is confusing: all glob attrs are ignored, or just those on shadowed items? this should be clarified.

the test could also include coverage for the case where an item is renamed to itself.  also what happens if an item is renamed then renamed back to the original name in a chain?

File: src/librustdoc/clean/inline.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/inline.rs]: Wow, much better, thanks!

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/visit_ast.rs]: Oops, the comment is wrong: we never merge attributes from glob reexports.

Comment (GuillaumeGomez) [reply src/librustdoc/visit_ast.rs]: It's also tested in the added test (that glob reexports attributes are ignored). ^^'

**Comment by GuillaumeGomez** [comment]
> some things could use clarification. i don't entirely understand if things are getting merged or overwritten. the unit test comment is confusing: all glob attrs are ignored, or just those on shadowed items? this should be clarified.

Attributes on glob reexports are always ignored. The comment I added was misleading so I fixed it.

> the test could also include coverage for the case where an item is renamed to itself. also what happens if an item is renamed then renamed back to the original name in a chain?

What matters is the duo name+DefId. So if the name is different, then rustdoc considers it's a different item. And if the item as renamed as itself, then nothing happens either. But I'm gonna add a test for this second case just in case.

**Comment by GuillaumeGomez** [comment]
Applied suggestions, added test and clarified comment.

**Comment by lolbinarycat** [comment]
> What matters is the duo name+DefId. 

non-renamed items have name field of None, and there's special logic to make this work with things renamed to themself, so I want there to be a test that makes sure any refactoring of this logic doesn't mess up this edge case.

**Comment by lolbinarycat** [comment]
Looks like you rebased and responded to review in the the same force push, which was a bit confusing when I clicked on the "Compare" button and saw a bunch of unrelated changes.

Anyways, it looks mostly correct, although if nothing is getting merged in the unit test, maybe it shouldn't have `merge` in the name? Or maybe it should just also exercise the case where attributes are actually merge.. is there a case where attributes are actually merged?

Also, I think it would be nice to also test what shows on the module docs, since apparently that can get out of sync with the actual item's docs, as shown in the original issue.

**Comment by GuillaumeGomez** [comment]
> Anyways, it looks mostly correct, although if nothing is getting merged in the unit test, maybe it shouldn't have `merge` in the name? Or maybe it should just also exercise the case where attributes are actually merge.. is there a case where attributes are actually merged?

The two reexports are getting merged. They are merged in case of reexport chain:

```rust
mod foo {
    mod bar {
        /// C
        pub struct A;
    }
    /// B
    pub use self::bar::A;
}

/// A
pub use self::foo::A;
```

The `A` struct doc will have `A`, `B` and `C`.

> Also, I think it would be nice to also test what shows on the module docs, since apparently that can get out of sync with the actual item's docs, as shown in the original issue.

Good idea.

**Comment by GuillaumeGomez** [comment]
Extended test as suggested.

**Comment by lolbinarycat** [comment]
Maybe I should clarify: I think the actual contents of the summary/description lines on the module docs need to be tested, since that's what got out of sync in the first hand, not the amount of items.

We don't want to somehow get an inversion of this bug, where the item docs are fine, but the module docs are getting messed up by the glob.

**Comment by GuillaumeGomez** [comment]
Ah I see. Added a check for short docs on module page.

**Review by lolbinarycat — APPROVED** [review]
