### PR TITLE
Properly check the defining scope of existential types

### LINKED ISSUE #52632: Existential type can have inconsistent concrete type
```rust
#![feature(existential_type)]

use std::fmt::Debug;

// Parser workaround. https://github.com/rust-lang/rust/issues/52631
macro_rules! this_is_an_item {
    ($i:item) => { $i };
}

fn main() {
    this_is_an_item! {
        existential type Existential: Debug;
    }

    fn _unused() -> Existential { String::new() }

    let null = || -> Existential { 0 };
    println!("{:?}", null());
}
```

```
Segmentation fault (core dumped)
```

Mentioning the existential types tracking issue https://github.com/rust-lang/rust/issues/34511
Mentioning @oli-obk and @cramertj

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #52632

Existential types (soon to be 'impl trait' aliases) can either be
delcared at a top-level crate/module scope, or within another item such
as an fn. Previously, we were handling the second case incorrectly when
recursively searching for defining usages - we would check children of
the item, but not the item itself. This lead to us missing closures
that consituted a defining use of the existential type, as their opaque
type instantiations are stored in the TypeckTables of their parent
function.

This commit ensures that we explicitly visit the defining item itself,
not just its children.

### CODE REVIEW

**Comment by Aaron1011** [comment]
While I don't make any behavior changes to `src/librustc/infer/opaque_types/mod.rs`, the modified `trace~ was helpful in tracking down the cause of the ICE.

File: src/test/ui/existential-type/issue-52843.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#![feature(existential_type)]
```
Comment (Centril) [inline src/test/ui/existential-type/issue-52843.rs]: Can you also add some comments to this file and rename it to `issue-52843-$description`?

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -1703,9 +1706,21 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
     } else {
         debug!("find_existential_constraints: scope={:?}", tcx.hir().get(scope));
         match tcx.hir().get(scope) {
-            Node::Item(ref it) => intravisit::walk_item(&mut locator, it),
-            Node::ImplItem(ref it) => intravisit::walk_impl_item(&mut locator, it),
-            Node::TraitItem(ref it) => intravisit::walk_trait_item(&mut locator, it),
+            // We explicitly call 'visit_*' methods, instead of using intravisit::walk_* methods
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]:
```suggestion
            // We explicitly call `visit_*` methods, instead of using `intravisit::walk_*` methods
```

File: src/librustc_typeck/collect.rs [hunk 3]
```diff
@@ -1703,9 +1706,21 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+            // This allows our visitor to process the defining item itself, causing
+            // it to pick up any 'sibling' defining uses.
+            //
+            // For example, this code:
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]:
```suggestion
            // For example, this code:
            // ```
```

File: src/librustc_typeck/collect.rs [hunk 4]
```diff
@@ -1703,9 +1706,21 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+            // fn foo() {
+            //     existential type Blah: Debug;
+            //     let my_closure = || -> Blah { true };
+            // }
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]:
```suggestion
            // }
            // ```
```

File: src/librustc_typeck/collect.rs [hunk 5]
```diff
@@ -1703,9 +1706,21 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+            //
+            // requires us to explicitly process 'foo()' in order
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]:
```suggestion
            // requires us to explicitly process `foo()` in order
```

File: src/librustc_typeck/collect.rs [hunk 6]
```diff
@@ -1703,9 +1706,21 @@ fn find_existential_constraints(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
...
+            // to notice the defining usage of 'Blah'
```
Comment (Centril) [inline src/librustc_typeck/collect.rs]:
```suggestion
            // to notice the defining usage of `Blah`.
```

**Review by Centril — COMMENTED** [review]
nits

**Comment by Centril** [comment]
cc @oli-obk @cramertj @varkor

**Comment by Aaron1011** [comment]
@Centril fixed

File: src/test/ui/existential-type/issue-52843-closure-constrain.rs [hunk 7]
```diff
@@ -0,0 +1,12 @@
+// Checks to ensure that we properly detect when a closure constrains an existential type
+#![feature(existential_type)]
+
+use std::fmt::Debug;
+
+fn main() {
+    existential type Existential: Debug;
+    fn _unused() -> Existential { String::new() }
+    //~^ ERROR: concrete type differs from previous defining existential type use
```
Comment (oli-obk) [inline src/test/ui/existential-type/issue-52843-closure-constrain.rs]: moderately confusing to have the first item (textually) talk about "previous". Maybe we should reword "previous" to "other"
