### PR TITLE
CFI: Fix encode_ty: unexpected Param(B/#1)

### LINKED ISSUE #111510: ICE: cfi:  encode_ty: unexpected `Param(B/#1)`
### Code
`rustc  -Clto -Zsanitizer=cfi`
```Rust
trait Stream { type Item; }
impl<'a> Stream for &'a str { type Item = u8; }
fn f<'s>(s: &'s str) -> (&'s str, <&'s str as Stream>::Item) {
    (s, 42)
}

fn main() {
    let fx = f as for<'t> fn(&'t str) -> (&'t str, <&'t str as Stream>::Item);
    assert_eq!(fx("hi"), ("hi", 42));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (0b795044c 2023-05-12)
binary: rustc
commit-hash: 0b795044c6f0854445f1f2bb6443e87848e150d1
commit-date: 2023-05-12
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:685:13: encode_ty: unexpected `Param(B/#1)`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7fefb9d99051 - std::backtrace_rs::backtrace::libunwind::trace::h8527a3f03df0a61a
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fefb9d99051 - std::backtrace_rs::backtrace::trace_unsynchronized::h0aaca58cee921b32
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fefb9d99051 - std::sys_common::backtrace::_print_fmt::h0efde94c0da8ae75
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fefb9d99051 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h487008f99113fc35
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fefb9df94af - core::fmt::rt::Argument::fmt::h32427ee229785148
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/core/src/fmt/rt.rs:138:9
   5:     0x7fefb9df94af - core::fmt::write::h37fc0c420456bb2a
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fefb9d8c2b1 - std::io::Write::write_fmt::h10050ce881b9433e
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/io/mod.rs:1712:15
   7:     0x7fefb9d98e65 - std::sys_common::backtrace::_print::h1849728c8f69838c
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fefb9d98e65 - std::sys_common::backtrace::print::h2b9d83ab5fd2b3c1
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fefb9d9bae7 - std::panicking::default_hook::{{closure}}::h456ad7230e87fd49
  10:     0x7fefb9d9b8d4 - std::panicking::default_hook::h4bd0ac69f4bb5afd
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/panicking.rs:288:9
  11:     0x7fefb8bd848b - rustc_driver_impl[e01bc88cbd7260b1]::install_ice_hook::{closure#0}
  12:     0x7fefb9d9c207 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5bd3902ddfec8c34
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1999:9
  13:     0x7fefb9d9c207 - std::panicking::rust_panic_with_hook::h898b161712d46c7f
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/panicking.rs:695:13
  14:     0x7fefb90c8891 - std[1b2081d79e1ebece]::panicking::begin_panic::<rustc_errors[babc6850844c6359]::ExplicitBug>::{closure#0}
  15:     0x7fefb90c6416 - std[1b2081d79e1ebece]::sys_common::backtrace::__rust_end_short_backtrace::<std[1b2081d79e1ebece]::panicking::begin_panic<rustc_errors[babc6850844c6359]::ExplicitBug>::{closure#0}, !>
  16:     0x7fefb90c60b6 - std[1b2081d79e1ebece]::panicking::begin_panic::<rustc_errors[babc6850844c6359]::ExplicitBug>
  17:     0x7fefb90c0dd4 - <rustc_errors[babc6850844c6359]::HandlerInner>::bug::<alloc[9568966325a797fe]::string::String>
  18:     0x7fefb90c0b06 - <rustc_errors[babc6850844c6359]::Handler>::bug::<alloc[9568966325a797fe]::string::String>
  19:     0x7fefb914b23c - rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt::<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}
  20:     0x7fefb914b07a - rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_opt::<rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fefb914b04a - rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_context_opt::<rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_opt<rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fefb6e1eabd - rustc_middle[d3ff4cf6a844744d]::util::bug::bug_fmt
  23:     0x7fefb96488ec - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  24:     0x7fefb9646877 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_substs
  25:     0x7fefb96462b3 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_predicates
  26:     0x7fefb964796b - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  27:     0x7fefb9647cfe - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  28:     0x7fefb964a434 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::typeid_for_fnabi
  29:     0x7fefb9649cfa - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::typeid_for_instance
  30:     0x7fefb6fb1b2a - <rustc_codegen_llvm[bcfa1192a27ad023]::context::CodegenCx as rustc_codegen_ssa[30f9578d8620702e]::traits::declare::PreDefineMethods>::predefine_fn
  31:     0x7fefb804ceb1 - rustc_codegen_llvm[bcfa1192a27ad023]::base::compile_codegen_unit::module_codegen
  32:     0x7fefb804be48 - rustc_codegen_llvm[bcfa1192a27ad023]::base::compile_codegen_unit
  33:     0x7fefb829f42f - rustc_codegen_ssa[30f9578d8620702e]::base::codegen_crate::<rustc_codegen_llvm[bcfa1192a27ad023]::LlvmCodegenBackend>
  34:     0x7fefb829ecc0 - <rustc_codegen_llvm[bcfa1192a27ad023]::LlvmCodegenBackend as rustc_codegen_ssa[30f9578d8620702e]::traits::backend::CodegenBackend>::codegen_crate
  35:     0x7fefb7dda6a0 - rustc_interface[c52f2741c22e4719]::passes::start_codegen
  36:     0x7fefb7dd61e7 - <rustc_middle[d3ff4cf6a844744d]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c52f2741c22e4719]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<alloc[9568966325a797fe]::boxed::Box<dyn core[dc8d3ccf7968c02]::any::Any>, rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  37:     0x7fefb7dd595d - <rustc_interface[c52f2741c22e4719]::queries::Queries>::ongoing_codegen
  38:     0x7fefb7dd4df3 - <rustc_interface[c52f2741c22e4719]::interface::Compiler>::enter::<rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}::{closure#2}, core[dc8d3ccf7968c02]::result::Result<core[dc8d3ccf7968c02]::option::Option<rustc_interface[c52f2741c22e4719]::queries::Linker>, rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  39:     0x7fefb7dd244b - std[1b2081d79e1ebece]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c52f2741c22e4719]::util::run_in_thread_pool_with_globals<rustc_interface[c52f2741c22e4719]::interface::run_compiler<core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>, rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}>::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  40:     0x7fefb7dd1bb5 - <<std[1b2081d79e1ebece]::thread::Builder>::spawn_unchecked_<rustc_interface[c52f2741c22e4719]::util::run_in_thread_pool_with_globals<rustc_interface[c52f2741c22e4719]::interface::run_compiler<core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>, rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}>::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#1} as core[dc8d3ccf7968c02]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fefb9da66b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b5dbfc0ed60a15c
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1985:9
  42:     0x7fefb9da66b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h655e48a786f980ed
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1985:9
  43:     0x7fefb9da66b5 - std::sys::unix::thread::Thread::new::thread_start::h3084f73fcc2ce462
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7fefb589ebb5 - <unknown>
  45:     0x7fefb5920d90 - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (0b795044c 2023-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C lto -Z sanitizer=cfi

query stack during panic:error: internal compiler error: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:685:13: encode_ty: unexpected `Param(B/#1)`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7fefb9d99051 - std::backtrace_rs::backtrace::libunwind::trace::h8527a3f03df0a61a
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fefb9d99051 - std::backtrace_rs::backtrace::trace_unsynchronized::h0aaca58cee921b32
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fefb9d99051 - std::sys_common::backtrace::_print_fmt::h0efde94c0da8ae75
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fefb9d99051 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h487008f99113fc35
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fefb9df94af - core::fmt::rt::Argument::fmt::h32427ee229785148
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/core/src/fmt/rt.rs:138:9
   5:     0x7fefb9df94af - core::fmt::write::h37fc0c420456bb2a
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fefb9d8c2b1 - std::io::Write::write_fmt::h10050ce881b9433e
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/io/mod.rs:1712:15
   7:     0x7fefb9d98e65 - std::sys_common::backtrace::_print::h1849728c8f69838c
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fefb9d98e65 - std::sys_common::backtrace::print::h2b9d83ab5fd2b3c1
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fefb9d9bae7 - std::panicking::default_hook::{{closure}}::h456ad7230e87fd49
  10:     0x7fefb9d9b8d4 - std::panicking::default_hook::h4bd0ac69f4bb5afd
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/panicking.rs:288:9
  11:     0x7fefb8bd848b - rustc_driver_impl[e01bc88cbd7260b1]::install_ice_hook::{closure#0}
  12:     0x7fefb9d9c207 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5bd3902ddfec8c34
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1999:9
  13:     0x7fefb9d9c207 - std::panicking::rust_panic_with_hook::h898b161712d46c7f
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/panicking.rs:695:13
  14:     0x7fefb90c8891 - std[1b2081d79e1ebece]::panicking::begin_panic::<rustc_errors[babc6850844c6359]::ExplicitBug>::{closure#0}
  15:     0x7fefb90c6416 - std[1b2081d79e1ebece]::sys_common::backtrace::__rust_end_short_backtrace::<std[1b2081d79e1ebece]::panicking::begin_panic<rustc_errors[babc6850844c6359]::ExplicitBug>::{closure#0}, !>
  16:     0x7fefb90c60b6 - std[1b2081d79e1ebece]::panicking::begin_panic::<rustc_errors[babc6850844c6359]::ExplicitBug>
  17:     0x7fefb90c0dd4 - <rustc_errors[babc6850844c6359]::HandlerInner>::bug::<alloc[9568966325a797fe]::string::String>
  18:     0x7fefb90c0b06 - <rustc_errors[babc6850844c6359]::Handler>::bug::<alloc[9568966325a797fe]::string::String>
  19:     0x7fefb914b23c - rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt::<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}
  20:     0x7fefb914b07a - rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_opt::<rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fefb914b04a - rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_context_opt::<rustc_middle[d3ff4cf6a844744d]::ty::context::tls::with_opt<rustc_middle[d3ff4cf6a844744d]::util::bug::opt_span_bug_fmt<rustc_span[9947208badf4d870]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fefb6e1eabd - rustc_middle[d3ff4cf6a844744d]::util::bug::bug_fmt
  23:     0x7fefb96488ec - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  24:     0x7fefb9646877 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_substs
  25:     0x7fefb96462b3 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_predicates
  26:     0x7fefb964796b - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  27:     0x7fefb9647cfe - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::encode_ty
  28:     0x7fefb964a434 - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::typeid_for_fnabi
  29:     0x7fefb9649cfa - rustc_symbol_mangling[ca35103f5927fe83]::typeid::typeid_itanium_cxx_abi::typeid_for_instance
  30:     0x7fefb6fb1b2a - <rustc_codegen_llvm[bcfa1192a27ad023]::context::CodegenCx as rustc_codegen_ssa[30f9578d8620702e]::traits::declare::PreDefineMethods>::predefine_fn
  31:     0x7fefb804ceb1 - rustc_codegen_llvm[bcfa1192a27ad023]::base::compile_codegen_unit::module_codegen
  32:     0x7fefb804be48 - rustc_codegen_llvm[bcfa1192a27ad023]::base::compile_codegen_unit
  33:     0x7fefb829f42f - rustc_codegen_ssa[30f9578d8620702e]::base::codegen_crate::<rustc_codegen_llvm[bcfa1192a27ad023]::LlvmCodegenBackend>
  34:     0x7fefb829ecc0 - <rustc_codegen_llvm[bcfa1192a27ad023]::LlvmCodegenBackend as rustc_codegen_ssa[30f9578d8620702e]::traits::backend::CodegenBackend>::codegen_crate
  35:     0x7fefb7dda6a0 - rustc_interface[c52f2741c22e4719]::passes::start_codegen
  36:     0x7fefb7dd61e7 - <rustc_middle[d3ff4cf6a844744d]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c52f2741c22e4719]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<alloc[9568966325a797fe]::boxed::Box<dyn core[dc8d3ccf7968c02]::any::Any>, rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  37:     0x7fefb7dd595d - <rustc_interface[c52f2741c22e4719]::queries::Queries>::ongoing_codegen
  38:     0x7fefb7dd4df3 - <rustc_interface[c52f2741c22e4719]::interface::Compiler>::enter::<rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}::{closure#2}, core[dc8d3ccf7968c02]::result::Result<core[dc8d3ccf7968c02]::option::Option<rustc_interface[c52f2741c22e4719]::queries::Linker>, rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  39:     0x7fefb7dd244b - std[1b2081d79e1ebece]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c52f2741c22e4719]::util::run_in_thread_pool_with_globals<rustc_interface[c52f2741c22e4719]::interface::run_compiler<core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>, rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}>::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>
  40:     0x7fefb7dd1bb5 - <<std[1b2081d79e1ebece]::thread::Builder>::spawn_unchecked_<rustc_interface[c52f2741c22e4719]::util::run_in_thread_pool_with_globals<rustc_interface[c52f2741c22e4719]::interface::run_compiler<core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>, rustc_driver_impl[e01bc88cbd7260b1]::run_compiler::{closure#1}>::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc8d3ccf7968c02]::result::Result<(), rustc_span[9947208badf4d870]::ErrorGuaranteed>>::{closure#1} as core[dc8d3ccf7968c02]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fefb9da66b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b5dbfc0ed60a15c
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1985:9
  42:     0x7fefb9da66b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h655e48a786f980ed
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/alloc/src/boxed.rs:1985:9
  43:     0x7fefb9da66b5 - std::sys::unix::thread::Thread::new::thread_start::h3084f73fcc2ce462
                               at /rustc/0b795044c6f0854445f1f2bb6443e87848e150d1/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7fefb589ebb5 - <unknown>
  45:     0x7fefb5920d90 - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (0b795044c 2023-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C lto -Z sanitizer=cfi

query stack during panic:
end of query stack
error: aborting due to previous error
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by rcvalle**
Fixes #111510 and complements #106547 by adding support for encoding type parameters and also by transforming trait objects' traits into their identities before emitting type checks.

### CODE REVIEW

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 1]
```diff
@@ -673,14 +673,21 @@ fn encode_ty<'tcx>(
             typeid.push_str(&s);
         }
 
+        // Type parameters
+        ty::Param(..) => {
+            // u5param as vendor extended type
+            let mut s = String::from("u5param");
+            compress(dict, DictKey::Ty(ty, TyQ::None), &mut s);
+            typeid.push_str(&s);
+        }
```
Comment (bjorn3) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:682]: Without `-Zpolymorphize` this shouldn't happen unless a monomorphization is missing I think.

**Comment by bjorn3** [comment]
I'm not entirely confident that the `ty::Param` encoding is correct, but I think it makes anything worse either.

@bors r+
