### PR TITLE
Try to suggest dereferences on trait selection failed

### LINKED ISSUE #39029: Suggest dereference operations when a deref coercion won't work
Deref coercions are tricky. `&x` will coerce to `&***x` if used in a place that expects a value of the type of `&***x`, however, this does not work for trait-bound generics.

The example that came up recently was:

```rust
use std::net::TcpListener;
let owned = "foobar".to_string(); // owned string came from somewhere
let works = TcpListener::bind("some string");
let doesn't = TcpListener::bind(&owned);
```

This errors with

```text
error[E0277]: the trait bound `std::string::String: std::net::ToSocketAddrs` is not satisfied
 --> <anon>:5:18
  |
5 |     let listen = TcpListener::bind(&owned);
  |                  ^^^^^^^^^^^^^^^^^ the trait `std::net::ToSocketAddrs` is not implemented for `std::string::String`
  |
  = note: required because of the requirements on the impl of `std::net::ToSocketAddrs` for `&std::string::String`
  = note: required by `std::net::TcpListener::bind`
```

because while `&owned` would usually coerce to an `&str`, in this case it doesn't because even though `TcpListener::bind` would accept a `&str`, it doesn't accept _only_ that type and the deref coercion won't work.

Programmers should not have to know these details to get their code to work. It would be nice if deref coercions worked in places where a generic bound type is expected, but there are other issues there (what happens if the trait gets implemented on `String`?) so it's not a clear win and would need an rfc anyway.

At the very least, we should suggest the usage of a dereference operator here.

The heuristics are:
 
 - you have a trait bound error
 - The error is on a reference expression `&x`
 - The expression is used in one of the allowed places for deref coercions (may not be necessary, really)
 - The trait isn't implemented by `&x`
 - The trait _is_ implemented by `&***x` for some amount of `*` operations

then, suggest the correct thing with the dereference operators.

cc @jonathandturner @GuillaumeGomez

### LINKED ISSUE #62530: Account for coercions in trait resolution?
This came up in https://github.com/rust-lang/rust/pull/62528, see “Joining strings with `char`”.

Reduced test case:

```rust
fn takes_str(_x: &str) {}

fn takes_type_parameter<T>(_x: T) where T: SomeTrait {}

trait SomeTrait {}
impl SomeTrait for &'_ str {}
impl SomeTrait for char {}

fn main() {
    let string = String::new();
    takes_str(&string);  // Ok
    takes_type_parameter(&string);  // Error
}
```

Output: (Identical in rustc 1.36.0 (a53f9df32 2019-07-03) and rustc 1.38.0-nightly (78ca1bda3 2019-07-08).)

```rust
error[E0277]: the trait bound `&std::string::String: SomeTrait` is not satisfied
  --> a.rs:12:5
   |
12 |     takes_type_parameter(&string);  // Error
   |     ^^^^^^^^^^^^^^^^^^^^ the trait `SomeTrait` is not implemented for `&std::string::String`
   |
note: required by `takes_type_parameter`
  --> a.rs:3:1
   |
3  | fn takes_type_parameter<T>(_: T) where T: SomeTrait {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

In the `takes_str(&string)` call, the type of the `_x` parameter is known to be `&str`. `&String` can be coerced through auto-deref.

In the `takes_type_parameter(&string)` call, I imagine that trait resolution finds two solution (the `_x` parameter is either `&str` or `char`) but neither of them match with `&string` directly, so trait resolution emits an error. Presumably, coercion are only attempted in a later phase of compilation.

Is there a language design reason it has to be this way, or could we make programs like the above valid? (It then “only” be a matter of compiler implementation.)

### PR DESCRIPTION
**Pull request by ldm0**
Fixes #39029 Fixes #62530
This PR consists of two parts:
1. Decouple `Autoderef` with `FnCtxt` and move `Autoderef` to `librustc_trait_selection`.
2. Try to suggest dereferences when trait selection failed.

The first is needed because:
1. For suggesting dereferences, the struct `Autoderef` should be used. But before this PR, it is placed in `librustc_typeck`, which depends on `librustc_trait_selection`. But trait selection error emitting happens in `librustc_trait_selection`, if we want to use `Autoderef` in it, dependency loop is inevitable. So I moved the `Autoderef` to `librustc_trait_selection`.
2. Before this PR, `FnCtxt` is coupled to `Autoderef`, and `FnCtxt` only exists in `librustc_typeck`. So decoupling is needed.

After this PR, we can get suggestion like this:
```
error[E0277]: the trait bound `&Baz: Happy` is not satisfied
  --> $DIR/trait-suggest-deferences-multiple.rs:34:9
   |
LL | fn foo<T>(_: T) where T: Happy {}
   |                          ----- required by this bound in `foo`
...
LL |     foo(&baz);
   |         ^^^^
   |         |
   |         the trait `Happy` is not implemented for `&Baz`
   |         help: consider adding dereference here: `&***baz`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

r? @estebank

### CODE REVIEW

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -450,6 +459,60 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+        let span = obligation.cause.span;
+        let real_trait_ref = if let ObligationCauseCode::ImplDerivedObligation(cause)
+        | ObligationCauseCode::DerivedObligation(cause)
+        | ObligationCauseCode::BuiltinDerivedObligation(cause) =
+            &obligation.cause.code
+        {
+            &cause.parent_trait_ref
+        } else {
+            trait_ref
+        };
```
Comment (estebank) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:487]: Nitpick: I feel a match would have looked better here.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -450,6 +459,60 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                        // often and user will not expect autoderef happens.
+                        if src.starts_with("&") {
+                            let derefs = "*".repeat(steps);
+                            err.span_suggestion(
+                                span,
+                                "consider adding dereference here",
+                                format!("&{}{}", derefs, &src[1..]),
+                                Applicability::MachineApplicable,
+                            );
+                        }
```
Comment (estebank) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:509]: Can we add a test for the `&mut` case? I fear that we might end up suggestion `&***mut foo` by accident.

**Review by estebank — APPROVED** [review]
Apologies for the delay on reviewing this. I have a couple of nitpicks. Could you address them as you rebase? Other than that, I'm happy with the changes!

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 2 above)
Comment (ldm0) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Oops, I forget to exclude the `&mut` situation. Fixed.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (ldm0) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Yep, changed.

**Comment by ldm0** [comment]
Rebase done, nitpicks applied.
