### PR TITLE
Greatly improve rustdoc rendering speed issues

### LINKED ISSUE #55900: [tracking-ish issue] Doc pages are very slow to render
Message from [discord](https://discordapp.com/channels/442252698964721669/443492145567891458):

> the https://doc.rust-lang.org/std/iter/trait.Iterator.html page(and only that page?) seems to have a broken search bar that manifests as infinite? loading and high CPU usage in both Chrome and firefox, across stable, beta, nightly, and local versions.

Related:

- [x] [Minification makes JS parsing slower](https://github.com/rust-lang/rust/issues/57754)
- [ ] [Open
search-index.js slows down documentation browsing](https://github.com/rust-lang/rust/issues/56545)
- [ ] Others?

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #55900.

So a few improvements here:

* we're switching to `DOMTokenList` API when available providing a replacement if it isn't (should only happen on safari and IE I think...)
* hide doc sections by default to allow the whole HTML generation to happen in the background to avoid triggering DOM redraw all the times (which killed the performances)

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I feel like this doesn't optimize the load time on my system (Chrome, Windows 7) enough to warrant *displaying practically nothing* while it loads. The total loss of information while it processes is way too much of a regression for not enough of a fix. I agree with @ollie27 that a better fix would be to render less information on the page to begin with, use less items that need processing, somehow make it so that the JS doesn't need to create all these elements, something like that.

**Comment by GuillaumeGomez** [comment]
The problem is mostly on the DOM manipulation, not the JS execution. I can add a bit of text but I clearly prefer to wait 3 seconds rather than having a laggy page for 30 seconds. This also fixes the issue about the fact that the docs started while being expanded when it was expected that they were collapsed.

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus Okay, I was able to make it **a lot** faster: Going from 13 seconds to 0.5 seconds for JS execution. I guess we're good now?

**Review by QuietMisdreavus — COMMENTED** [review]
While i don't see the dramatic speedup you're seeing (and my Firefox's dev tools won't cooperate to let me profile the code on the Iterator page), i can at least see some speedup. This is probably fine after these comments, but i'm going to try to summon more eyes on this to make sure we fully understand the ramifications here.

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc to get more eyes on this PR; the transformations here all *look* straightforward, but i'm not too familiar with JS so i'd like to get another review pass on it.

I also want to ping @rust-lang/docs about what i think is the biggest problem with the PR. The idea is that by hiding everything to begin with, all the DOM changes we do to add fold-toggle elements won't trigger a bunch of repainting, speeding up the JS execution. However, this leads to the unfortunate consequence where generated docs require JavaScript to look at anything any more.

Based on [a totally informal and non-authoritative Twitter poll](https://twitter.com/QuietMisdreavus/status/1068991510258114562), at least some people browse the internet, including Rust docs, with JS turned off, so we will be leaving some people behind here. Whether we're okay with that, i'm not willing to call by myself.

**Comment by alercah** [comment]
I'm pretty strongly of the opinion that we should support noscript browsers or users who run with JS disabled, unless and until someone demonstrates that there is no value to it.

**Comment by steveklabnik** [comment]
> unless and until someone demonstrates that there is no value to it.

The issue here is not that it doesn't have value. It certainly does. The issue is that if it has too much *downside*. We already make a number of choices, historically, that harm the average user, in order to support this use-case.

The question isn't about value, it's about balancing the pros and cons of different approaches that have different values.

**Comment by QuietMisdreavus** [comment]
After some discussion on Discord, we've added a couple new features to this:

- Thanks to a new CSS file loaded with a `<noscript>` tag, we won't hide anything for people who turn JavaScript off. This solves that hangup for me, and also allows us to provide some extra help to these users in the future.
- While the "startup" JS is running, there is a new "Loading content..." message printed in the docs:

image

This at least provides some notice to the user that the page is taking extra time to process. For the most part, this only shows up on pages with tons of content like `Iterator` - most pages don't have enough elements with fold toggles that need to be generated, and the initial page processing happens quickly enough that the real content gets shown before the user gets a chance to see the "loading" message.

Now that it has these changes, this PR looks good to me. Would like to see what the others (and travis) think before i r+ though.

**Comment by GuillaumeGomez** [comment]
Rebased.

**Comment by GuillaumeGomez** [comment]
Rebased.

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus travis is happy and we are getting new issues about this. Do you want to wait a bit longer or do you think it's ready to go?

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc @rust-lang/docs to take another look. Does the new support of NoScript users and the new "loading" message make this PR mergeable?

File: src/librustdoc/html/static_files.rs [hunk 1]
```diff
@@ -23,6 +23,9 @@ pub static RUSTDOC_CSS: &'static str = include_str!("static/rustdoc.css");
 /// The file contents of `settings.css`, responsible for the items on the settings page.
 pub static SETTINGS_CSS: &'static str = include_str!("static/settings.css");
 
+/// The file contents of the `noscript.css` file, used in case JS isn't supported or is disabled.
+pub static NOSCRIPT_CSS: &'static str = include_str!("static/noscript.css");
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/static_files.rs]: Just realized: New static file, need to update docs.rs when this is merged.

**Comment by QuietMisdreavus** [comment]
Given the rousing lack of comment, i'm going to go ahead and push this one out.

@bors r+

**Comment by TimNN** [comment]
I haven't looked at this in detail yet, but I think that this PR made the experience of browsing e.g. the `Iterator` docs much more annoying.

Compare:

* https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html
* https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html

On Chrome / macOS (with cache):

* `beta` shows some content almost instantly.
* `nightly` the pages loads for what feels like forever, without _any_ useful content. Additionally, the browser seems to hang while it does so (e.g. changing the url does not immediately trigger an navigation).

**Comment by DianaNites** [comment]
Currently, it'll be slow and the browser doesn't handle it well. but you can atleast scroll the page and read the docs you need while it loads, even jump to the method you want. At least on chrome

After this change, you have to wait the full (slightly shorter) loading time to see anything at all, not really ideal.
