### PR TITLE
Operand::extract_field: only cast llval if it's a pointer and replace bitcast w/ pointercast.

### LINKED ISSUE #105439: ICE due to generating LLVM bitcast vec -> array
Found here: https://github.com/rust-lang/rust/issues/105344#issuecomment-1341560536

Code:

```rust
#![feature(portable_simd)]
fn main() {
    use core::simd::Simd;
    let a = Simd::from_array([0, 4, 1, 5]);
    let b = Simd::from_array([2, 6, 3, 7]);
    let (x, y) = a.deinterleave(b);
    assert_eq!(x.to_array(), [0, 1, 2, 3]);
    assert_eq!(y.to_array(), [4, 5, 6, 7]);
}
```

Invocation:
 ```sh
$ rustc +nightly --version
rustc 1.67.0-nightly (e1d819583 2022-12-05)
binary: rustc
commit-hash: e1d819583f0bf13b016b119c1c2c43e6d3979450
commit-date: 2022-12-05
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
Compiler returned: 0
$ rustc +nightly --edition 2021 -C opt-level=3 -Zmir-opt-level=3 -C no-prepopulate-passes
```

Causes an LLVM ICE: 
```
Invalid bitcast
  %27 = bitcast <4 x i32> %22 to [4 x i32], !dbg !268
Invalid bitcast
  %31 = bitcast <4 x i32> %26 to [4 x i32], !dbg !280
in function _ZN7example4main17h82e1f57aed922fc8E
LLVM ERROR: Broken function found, compilation aborted!
Compiler returned: 101
```

This reproduces easily [on Godbolt](https://godbolt.org/z/x3x9faMGE).

The invalid bitcast is introduced by codgen for the MIR statement `_1 = (_25.0: [i32; 4]);` on [line 151](https://godbolt.org/z/8c4KhWosT).

Local `_25` has type `std::simd::Simd<i32, 4>`. I believe the bitcast is introduced [here](https://github.com/rust-lang/rust/blob/01fbc5ae789fc0c7a2da71d3cd908451f175e4eb/compiler/rustc_codegen_ssa/src/mir/operand.rs#L227), but I don't think this path is even intended to handle Simd types. I'm not exactly sure what the bug here is either, ie I have no idea how this was supposed to be codegened.

@rustbot label +A-codegen +A-llvm +I-ICE +T-compiler

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #105439.

Also cc @erikdesjardins, looks like another place to cleanup as part of #105545

### CODE REVIEW

File: src/test/ui/simd/issue-105439.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// This is used to ICE with MIR inlining enabled due to an invalid bitcast.
+// run-pass
+// compile-flags: -O -Zmir-opt-level=3
```
Comment (tmiasko) [inline src/test/ui/simd/issue-105439.rs:3]: Perhaps a smaller test would capture the essence of the issue without requiring MIR optimizations:

```rust
#![feature(repr_simd)]
#![feature(platform_intrinsics)]

#[allow(non_camel_case_types)]
#[derive(Clone, Copy)]
#[repr(simd)]
pub struct i32x4([i32; 4]);

pub fn f(a: i32x4) -> [i32; 4] {
    let b = a;
    b.0
}
```

```console
$ rustc --crate-type=lib a.rs -Zverify-llvm-ir
Invalid bitcast
  %4 = bitcast <4 x i32> %3 to [4 x i32]
LLVM ERROR: Broken module found, compilation aborted!
```

Comment (luqmana) [reply src/test/ui/simd/issue-105439.rs]: Sure, updated test.

File: compiler/rustc_codegen_ssa/src/mir/operand.rs [hunk 2]
```diff
@@ -224,15 +225,24 @@ impl<'a, 'tcx, V: CodegenObject> OperandRef<'tcx, V> {
                 // Bools in union fields needs to be truncated.
                 *llval = bx.to_immediate(*llval, field);
                 // HACK(eddyb) have to bitcast pointers until LLVM removes pointee types.
-                *llval = bx.bitcast(*llval, bx.cx().immediate_backend_type(field));
+                let ty = bx.cx().immediate_backend_type(field);
+                if bx.type_kind(ty) == TypeKind::Pointer {
+                    *llval = bx.pointercast(*llval, ty);
+                }
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_ssa/src/mir/operand.rs:231]: This removes the illegal `bitcast <4 x i32> to [4 x i32]`, which is good--but it doesn't replace that illegal conversion with a legal one, so we end up returning a value of type `<4 x i32>` when extracting a field of type `[4 x i32]`.

The repro example happens to work anyways because the next instruction is a store, and both `store <4 x i32>` and `store [4 x i32]` have the same effect. But it won't work if we use that value by value. (This may never happen, because I don't think we ever pass LLVM array types by value, but it's technically incorrect.)

To handle this fully, I think you'd have to special-case this kind of newtype field extraction (self `Abi::Vector`, field `Abi::Aggregate`) and roundtrip the vector through memory (alloca, `store <4 x i32>`, `load [4 x i32]`).

(I thought there might be [endianness concerns](https://llvm.org/docs/LangRef.html#vector-type), but it seems like that's [only a problem](https://godbolt.org/z/18o6nEcv5) for not-a-multiple-of-i8 types like i4)

Comment (luqmana) [reply compiler/rustc_codegen_ssa/src/mir/operand.rs]: Good point! Split out the case for newtype of simd array

**Comment by nagisa** [comment]
I had started reviewing it a while before, but clearly I’m not getting back to this anytime soon. I'll keep this tab open still, maybe I’ll find some time.

r? rust-lang/compiler

File: compiler/rustc_codegen_ssa/src/mir/operand.rs [hunk 3]
```diff
@@ -220,19 +221,53 @@ impl<'a, 'tcx, V: CodegenObject> OperandRef<'tcx, V> {
...
                 // Bools in union fields needs to be truncated.
                 *llval = bx.to_immediate(*llval, field);
                 // HACK(eddyb) have to bitcast pointers until LLVM removes pointee types.
-                *llval = bx.bitcast(*llval, bx.cx().immediate_backend_type(field));
+                let ty = bx.cx().immediate_backend_type(field);
+                if bx.type_kind(ty) == TypeKind::Pointer {
+                    *llval = bx.pointercast(*llval, ty);
+                } else {
+                    *llval = bx.bitcast(*llval, ty);
+                }
```
Comment (Nilstrieb) [inline compiler/rustc_codegen_ssa/src/mir/operand.rs:236]: Maybe it makes sense to have a more generic cast method that does the check itself?

**Comment by oli-obk** [comment]
considering how subtle this case is, what's your opinion on adding a codegen test?

File: compiler/rustc_codegen_ssa/src/mir/operand.rs (hunk 3 above)
Comment (erikdesjardins) [reply compiler/rustc_codegen_ssa/src/mir/operand.rs:236]: We basically only generate pointer casts, so I don't think such an operation would be very widely used. (All existing usage of `bitcast` that I have seen was intended to convert between pointer types, and almost all can be removed after opaque pointers, e.g. https://github.com/rust-lang/rust/pull/105412/commits/68cabc0c87fe4f89ab3a6434b5adc7d5ddf77b87)

Excluding pointer types, the only other things that can be `bitcast`ed in LLVM are differently-typed vectors `<4 x i8> to <2 x i16>` and between vectors and integers `<4 x i8> to i32`. This would probably only be used in `transmute`. (We currently codegen such transmutes as roundtrips through memory: https://godbolt.org/z/M6fr1af8z.)

I don't think we support either of those operations as part of a field extraction, so I suspect the `else` here isn't necessary. @luqmana did you encounter code that still needs the `bitcast`?

**Comment by erikdesjardins** [comment]
(I don't think you're asking me but) A codegen test could be useful, although the proper codegen is just a store/load which isn't too interesting.

Whether or not we add a codegen test, I'd suggest changing the existing test to `run-pass`, and add some additional code and assertions to make sure our codegen behaves properly at runtime. (e.g. generate an `i32x4` with some interesting values, call the function to convert it to `[i32; 4]`, and assert that the array elements are correct)

**Comment by JohnCSimon** [comment]
@luqmana Ping from triage:  Can you post your status on this PR? This has sat idle for a few months.

File: compiler/rustc_codegen_ssa/src/mir/operand.rs (hunk 3 above)
Comment (luqmana) [reply compiler/rustc_codegen_ssa/src/mir/operand.rs]: I did not. Updated to just the pointercasts.

**Comment by luqmana** [comment]
Ok, rebased this and addressed review comments. Also switched the test back to run-pass:

```console
# Fails on latest nightly
$ rustc +nightly -vV
rustc 1.71.0-nightly (74c482104 2023-05-04)
binary: rustc
commit-hash: 74c4821045c68d42bb8b8a7c998bdb5c2a72bd0d
commit-date: 2023-05-04
host: aarch64-apple-darwin
release: 1.71.0-nightly
LLVM version: 16.0.2
$ rustc +nightly -O -Zverify-llvm-ir issue-105439.rs
Invalid bitcast
  %16 = bitcast <4 x i32> %15 to [4 x i32]
LLVM ERROR: Broken module found, compilation aborted!

# Passes with PR
$ rustc +stage1 -O -Zverify-llvm-ir issue-105439.rs
$ ./issue-105439 && echo $?
0
```



@rustbot ready
