### PR TITLE
E0131 updated to new format

### LINKED ISSUE #35257: E0131 needs to be updated to new format
From: 

Error E0131 needs a span_label, updating it from:

```
error[E0131]: main function is not allowed to have type parameters
  --> src/test/compile-fail/E0131.rs:11:1
   |
11 | fn main<T>() { //~ ERROR E0131
   | ^
```

To:

```
error[E0131]: main function is not allowed to have type parameters
  --> src/test/compile-fail/E0131.rs:11:1
   |
11 | fn main<T>() { //~ ERROR E0131
   | ^ main cannot have type parameters
```

Bonus: underline the type parameters directly

```
error[E0131]: main function is not allowed to have type parameters
  --> src/test/compile-fail/E0131.rs:11:1
   |
11 | fn main<T>() { //~ ERROR E0131
   |        ^^^ main cannot have type parameters
```

### PR DESCRIPTION
**Pull request by Limeth**
Changes

```
error[E0131]: main function is not allowed to have type parameters
  --> src/test/compile-fail/E0131.rs:11:1
   |
11 | fn main<T>() { //~ ERROR E0131
   | ^
```

to

```
error[E0131]: main function is not allowed to have type parameters
  --> src/test/compile-fail/E0131.rs:11:1
   |
11 | fn main<T>() { //~ ERROR E0131
   |        ^^^ main cannot have type parameters
```

Fixes #35257. Part of #35233.
r? @jonathandturner

### CODE REVIEW

File: src/librustc_typeck/lib.rs [hunk 1]
```diff
@@ -211,11 +211,18 @@ fn check_main_fn_ty(ccx: &CrateCtxt,
             match tcx.map.find(main_id) {
                 Some(hir_map::NodeItem(it)) => {
                     match it.node {
-                        hir::ItemFn(_, _, _, _, ref ps, _)
-                        if ps.is_parameterized() => {
-                            span_err!(ccx.tcx.sess, main_span, E0131,
-                                      "main function is not allowed to have type parameters");
-                            return;
+                        hir::ItemFn(_, _, _, _, ref generics, _) => {
+                            let gen_span = generics.span();
```
Comment (Keats) [inline src/librustc_typeck/lib.rs]: Not sure if i can comment but:

```rust
if let Some(gen_span) = generics.span() {
// struct_span_err!..
}
```
No need for the `return` too I think

Comment (Limeth) [inline src/librustc_typeck/lib.rs]: I didn't add it, it was there originally.

File: src/librustc_typeck/lib.rs [hunk 2]
```diff
@@ -211,11 +211,18 @@ fn check_main_fn_ty(ccx: &CrateCtxt,
...
+
+                            if gen_span.is_some() {
```
Comment (jonathandturner) [inline src/librustc_typeck/lib.rs]: Rust actually as a cool way of doing this pattern:

```
if let Some(gen_span_unwrapped) = gen_span { ... }
```

**Comment by jonathandturner** [comment]
Thanks for the PR!

I put a code style comment in, which will help others read the code better.

One other thing: please include a unit test that tests for this new label.  You can either update the `src/test/compile-fail/E0131.rs` test with the new NOTE (I show how in the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html)).  Even better than that, though, is to add a new test in `src/test/ui`.  Here you can actually test the new label span.  If you look through the directory, specifically `src/test/ui/codemap_tests` you can see how it's done.  Just a simple test and then a corresponding .stderr file.  This is just a copy/paste from the compiler output.

File: src/librustc_typeck/lib.rs (hunk 2 above)
Comment (jonathandturner) [inline src/librustc_typeck/lib.rs]: I missed @Keats already mentioned that.  Oops :)

**Comment by Limeth** [comment]
Should be good to go, thanks for the patience!

**Comment by jonathandturner** [comment]
@Limeth - great, thanks for fixing it.  One last thing, can you squash your 7 commits down to 1 commit?

**Comment by Limeth** [comment]
Cloned a fresh repository, copied over the changes and compiled it again. Took a while, but here it is. I don't know if there is a faster way.

**Comment by jonathandturner** [comment]
Phew, yeah, that's probably the hard way.  The easier way is to do something like [this](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).  I tend to do it after I've done a rebase, so my changes are at the top, I do a `git reset` to the commit before my changes, then I can `git commit -a -m "<my one commit comment>" ` all my changes together.  

Thanks for squashing it.

@bors r+ rollup
