### PR TITLE
Fix bug in shebang handling

### LINKED ISSUE #70528: #! (shebang) stripping doesn't account for spaces.
A file containing only this [correctly errors](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1d3380c63f1f1b66e5a74f386dfbaaa):
```rust
#![bad_attribute]
```

But this [doesn't error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7fab91b933ff640d6c0f627b3def6b5e), as it's stripped the same way [`#!/usr/bin/env ...` (i.e. "shebang")](https://en.wikipedia.org/wiki/Shebang_(Unix)) would be:
```rust
#! [bad_attribute]
```

In this third example, it also strips just the `#!`, [breaking the attribute](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=559a1136c52c2a255bf15e6e113dbb29):
```rust
#!
[bad_attribute]
```

The code responsible is this: https://github.com/rust-lang/rust/blob/8045865873f7cdbb864d0f66ef5ecb0d3ad847b2/src/librustc_lexer/src/lib.rs#L156-L160

It doesn't seem to account for any whitespace between the `!` and `[`.
I believe that we should allow any characters `c` where `c != '\n' && is_whitespace(c)` after the `#!`, and determine whether this is a shebang, by the next character on the same line:
* if there are no non-whitespace characters, it's not a valid shebang
* if the next character is `[`, this is the start of an inner comment
* otherwise, it's probably a shebang

I have no idea what to do for Rust comment syntax (`#!//...` and `#!/*...`), however.

And, of course, at the end of the day, this might be a backwards-incompatible change to make.

cc @matklad @petrochenkov

This issue has been assigned to @rcoh via [this comment](https://github.com/rust-lang/rust/issues/70528#issuecomment-626237132).

### PR DESCRIPTION
**Pull request by rcoh**
Shebang handling was too agressive in stripping out the first line in cases where it is actually _not_ a shebang, but instead, valid rust (#70528). This is a second attempt at resolving this issue (the first attempt was reverted, for, among other reasons, causing an ICE in certain cases (#71372, #71471).

The behavior is now codified by a number of UI tests, but simply:
For the first line to be a shebang, the following must all be true:
1. The line must start with `#!`
2. The line must contain a non-whitespace character after `#!`
3. The next character in the file, ignoring comments & whitespace must not be `[`

I believe this is a strict superset of what we used to allow, so perhaps a crater run is unnecessary, but probably not a terrible idea.

Fixes #70528

### CODE REVIEW

**Comment by rcoh** [comment]
cc @petrochenkov this also fixes your comments on the previous PR (only the first name is whitespace-stripped, uses the correct is_whitespace function, & addresses the `#!\n[...]` case)

File: src/tools/tidy/src/style.rs [hunk 1]
```diff
@@ -174,6 +174,11 @@ pub fn check(path: &Path, bad: &mut bool) {
 
         let can_contain =
             contents.contains("// ignore-tidy-") || contents.contains("# ignore-tidy-");
+        // Enable testing ICE's that require specific (untidy)
+        // file formats easily eg. `issue-1234-ignore-tidy.rs`
+        if filename.contains("ignore-tidy") {
+            return;
+        }
```
Comment (estebank) [inline src/tools/tidy/src/style.rs:181]: This is a hack in the best meaning of the word.

**Review by estebank — APPROVED** [review]

File: src/tools/tidy/src/style.rs (hunk 1 above)
Comment (spastorino) [reply src/tools/tidy/src/style.rs:181]: We could also place these kind of tests in a specific directory and filter those out?

Comment (petrochenkov) [reply src/tools/tidy/src/style.rs:181]: The filename opt out looks good to me.
It seems better to keep tests in directories where they actually belong to.

File: src/librustc_lexer/src/lib.rs [hunk 2]
```diff
@@ -28,6 +28,7 @@ use std::convert::TryInto;
 /// Parsed token.
 /// It doesn't contain information about data that has been parsed,
 /// only the type of the token and its size.
+#[derive(Debug)]
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:31]: Looks like this was temporary and can be removed now.

File: src/librustc_lexer/src/lib.rs [hunk 3]
```diff
@@ -235,16 +236,19 @@ pub enum Base {
 /// Line won't be skipped if it represents a valid Rust syntax
 /// (e.g. "#![deny(missing_docs)]").
 pub fn strip_shebang(input: &str) -> Option<usize> {
-    debug_assert!(!input.is_empty());
-    let s: &str = &remove_whitespace(input);
-    if !s.starts_with("#!") || s.starts_with("#![") {
-        return None;
+    if let Some(first_line) = input.lines().next() {
+        let s: &str = &remove_whitespace(first_line);
+        if !s.starts_with("#!") || s.starts_with("#![") {
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:241]: No need to convert to strings here, `starts_with` works on `[char]` slices equally well.
`remove_whitespace` can also be inlined.

File: src/librustc_lexer/src/lib.rs [hunk 4]
```diff
@@ -235,16 +236,19 @@ pub enum Base {
...
+            return None;
+        }
+        Some(input.find('\n').unwrap_or(input.len()))
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:244]:
```suggestion
        Some(first_line.len())
```
?

File: src/librustc_lexer/src/lib.rs (hunk 3 above)
Comment (rcoh) [reply src/librustc_lexer/src/lib.rs:241]: there's no way around `collect()` ing a `Vec` instead thought, right?

Comment (petrochenkov) [reply src/librustc_lexer/src/lib.rs]: Well, you can do
```rust
        let chars = first_line.chars().filter(|c| !is_whitespace(*c));
        let three_chars = [chars.next(), chars.next(), chars.next()];
```
and then analyze characters individually, it's just inconvenient.

File: src/librustc_lexer/src/lib.rs [hunk 5]
```diff
@@ -235,16 +235,15 @@ pub enum Base {
 /// Line won't be skipped if it represents a valid Rust syntax
 /// (e.g. "#![deny(missing_docs)]").
 pub fn strip_shebang(input: &str) -> Option<usize> {
-    debug_assert!(!input.is_empty());
-    let s: &str = &remove_whitespace(input);
-    if !s.starts_with("#!") || s.starts_with("#![") {
-        return None;
+    if let Some(first_line) = input.lines().next() {
+        let prefix = first_line.chars().filter(|c| !is_whitespace(*c)).collect::<Vec<_>>();
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:239]:
```suggestion
        let prefix = first_line.chars().filter(|c| !is_whitespace(*c)).take(3).collect::<Vec<_>>();
```

Comment (petrochenkov) [reply src/librustc_lexer/src/lib.rs:239]: You could also turn `if let Some(first_line) = input.lines().next() { ... }` into `input.lines().next().and_then(|first_line| ...)` here.

File: src/tools/tidy/src/style.rs (hunk 1 above)
Comment (eddyb) [reply src/tools/tidy/src/style.rs:181]: cc @Mark-Simulacrum

File: src/librustc_lexer/src/lib.rs [hunk 6]
```diff
@@ -235,16 +235,15 @@ pub enum Base {
...
+        if !prefix.starts_with(&['#', '!']) || prefix.starts_with(&['#', '!', '[']) {
```
Comment (eddyb) [inline src/librustc_lexer/src/lib.rs:240]: Wait, this seems to allow a space between `#` and `!` or even *before* `#`, but AFAIK the only place where space is allowed is *after* the `!`.

So all of this seems overcomplicated. Maybe we should revert to the original version, before the last PR, and make the smallest change necessary?

**Comment by eddyb** [comment]
I believe an empty `#!` shouldn't be considered a valid shebang, e.g.:
```rust
#!
[foo]
```

The important thing, IMO, is to not treat valid Rust syntax (starting with `#!`, so only inner attributes) as shebangs. Comments would be the only exception, although we should take the conservative route and error if `/*` or `//` are found on the shebang line, instead of picking a behavior.

Having just wrangled C preprocessing (which has a similar problem with comment starting inside the header name of `#include <...>` directives, being implementation-defined), I'm more than ever of the belief that when two syntaxes clash (here, shebangs and Rust), we should only allow *disjoint* cases, where only one possible interpretation is valid, and error on any overlaps.

**Comment by eddyb** [comment]
This PR should probably also add missing UI tests for #71372.

File: src/librustc_lexer/src/lib.rs (hunk 6 above)
Comment (rcoh) [reply src/librustc_lexer/src/lib.rs:240]: Maybe I misunderstand, but `# ! [attrib(...) ]` is valid rust? Do you mean that shebangs can't have a space there?

**Comment by rcoh** [comment]
On Monday, I will simplify & add UI tests.

**Comment by petrochenkov** [comment]
Ok, I guess we need to precisely define what is considered a shebang then (regardless of ambiguities with Rust).

No spaces, then `#`, then `!`, then what?

File: src/librustc_lexer/src/lib.rs (hunk 6 above)
Comment (eddyb) [reply src/librustc_lexer/src/lib.rs:240]: I mean that shebangs can't have a space  there.

**Comment by rcoh** [comment]
After a surprisingly large amount of thought for this seemingly simple situation, I believe there is actually no solution that both accepts all valid rust programs and all valid shebangs other than attempting to parse the file and falling back to deleting the shebang line if it doesn't parse :roll_eyes: (which I don't think we should do).

After a quick search, I don't _think_ we'd break people if we were slightly stricter in how we handle shebangs, but I think _that_ is the biggest risk with changing anything here. Most of these weird cases _don't_ compile as is on stable so we won't break anyone by continuing to not have them compile.

My proposed change:
Shebangs are lines that:
1. Have at least 3 non whitespace characters
2. Begin with `#!`
3. Have a third character (after stripping whitespace) that isn't `[`

Notably this doesn't handle the case with `//`. I think that's OK. 

## Justification
My initial approach is defining shebangs as equivalent to the following regex: `#![^\[\s]`. But this suffers from this case:
```
#!// tricked you I'm a comment
[attribute(...)]
```

(which _really_ looks like a shebang until you get to the 4th character)

But in terms of actual shebang acceptance, 
` #!//bin/bash` is a totally valid shebang (and works fine on my laptop). This is sort of a problem because the first line can be _both_ a shebang but also part of a valid program :joy: 

```rust
#!//bin/bash
[foo]
```
But just as well this could be
```rust
#!//bin/bash
pub fn not_a_sneaky_attribute() -> {
  println!("Because everything sucks here, that was actually a shebang. Good luck figuring that out.");
}
```

It's worth noting this doesn't currently compile: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a0603ad05e578e7eaf118d540e8bcd49 (but I think it should)

And also, `#!   /bin/bash` is a valid shebang according https://unix.stackexchange.com/questions/276751/is-space-allowed-between-and-bin-bash-in-shebang/276753 (so a space after shebang is actually allowed).

And regardless of theoretical validity, `    #!   /bin/bash` works fine as a shebang.

**But**, `#!` and nothing else is invalid, which I think is what we need to check for.

**Comment by eddyb** [comment]
Note that a Rust module cannot start with `[`, so `#!` followed by whitespace/comments followed by `[` could not be a shenang followed by Rust module.

My suggestion was to disallow any potential overlap and error if `//` or `/*` are found in the shebang. We could also ban `\`, `$` or `!`, which could have meaning in the future, and maybe `'`/`"` because of char/string literals. But it's perhaps getting into the weeds.

IMO we should do this properly. I'll prepare a PR reverting the previous PR so that we can crater-run this one.

**Comment by petrochenkov** [comment]
>I believe there is actually no solution that both accepts all valid rust programs and all valid shebangs other than attempting to parse the file and falling back to deleting the shebang line if it doesn't parse :roll_eyes: (which I don't think we should do).

We only need lexing, not parsing, and we only need to run the lexer loop until we encounter a first non-whitespace token. Seems pretty realistic :)

This will also allow to avoid processing things like `//` or `/*` manually. (Comments are whitespace *tokens*.)

Pseudocode:
```
fn is_shebang = first_line.starts_with("#!") && first_line[2..].contains(non_whitespace_character)

fn is_rust = non_whitespace_tokens.starts_with(#, !, [)
```

If it's only `is_shebang` or only `is_rust`, then the choice is clear.
It it's both, choose rust or produce an error.

**Comment by petrochenkov** [comment]
@eddyb 
>We could also ban `\`, `$` or `!`, which could have meaning in the future, and maybe `'`/`"` because of char/string literals. But it's perhaps getting into the weeds.

Future-proofing shebang of all things? Yep, that's weeds.

**Comment by rcoh** [comment]
I need to finish adding more UI tests, but I've updated the code with @petrochenkov's suggestions. Namely:

1. If the file begins with (ignore whitespace) `#![` we will never call it a shebang.
2. If the file begins with `#! something else` we will strip the shebang.

**Comment by petrochenkov** [comment]
Ha, you actually did this.

**Comment by petrochenkov** [comment]
It's great that the lexer loop can be run just as simple as this.
I'll look in more detail tomorrow.

File: src/librustc_parse/lexer/mod.rs [hunk 7]
```diff
@@ -71,6 +70,10 @@ impl<'a> StringReader<'a> {
         }
     }
 
+    pub fn get_pos(&self) -> BytePos {
```
Comment (petrochenkov) [inline src/librustc_parse/lexer/mod.rs:73]:
```suggestion
    pub fn pos(&self) -> BytePos {
```
https://rust-lang.github.io/api-guidelines/naming.html?highlight=getter#getter-names-follow-rust-convention-c-getter

File: src/librustc_lexer/src/lib.rs [hunk 8]
```diff
@@ -249,7 +274,8 @@ pub fn first_token(input: &str) -> Token {
 }
 
 /// Creates an iterator that produces tokens from the input string.
-pub fn tokenize(mut input: &str) -> impl Iterator<Item = Token> + '_ {
+pub fn tokenize(input: &str) -> impl Iterator<Item = Token> + '_ {
+    let mut input = input;
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:278]: Nit: unnecessary change?

File: src/librustc_lexer/src/lib.rs [hunk 9]
```diff
@@ -229,17 +229,42 @@ pub enum Base {
...
+pub enum InvalidShebang {
+    ContainsComment,
+}
+
+#[derive(Debug, PartialEq, Eq, Clone, Copy)]
+pub enum Shebang {
+    DefinitelyShebang(usize),
+    /// The input must start with a shebang (it is invalid Rust otherwise)
+    NotAShebang,
+}
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:242]: These two enums are not used.

File: src/librustc_lexer/src/lib.rs [hunk 10]
```diff
@@ -229,17 +229,42 @@ pub enum Base {
...
+    let first_line = input.lines().next()?;
+    // A shebang is intentionally loosely defined as `#! [non whitespace]` on the first line.
+    let could_be_shebang =
+        first_line.starts_with("#!") && first_line[2..].contains(|c| !is_whitespace(c));
+    if !could_be_shebang {
         return None;
     }
-    Some(input.find('\n').unwrap_or(input.len()))
+    let non_whitespace_tokens = tokenize(input).map(|tok| tok.kind).filter(|tok| match tok {
+        TokenKind::LineComment | TokenKind::BlockComment { .. } | TokenKind::Whitespace => false,
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:255]: `.filter(|tok| !matches!(tok.kind, TokenKind::LineComment | TokenKind::BlockComment { .. } | TokenKind::Whitespace))`

File: src/librustc_lexer/src/lib.rs [hunk 11]
```diff
@@ -229,17 +229,42 @@ pub enum Base {
...
+        _ => true,
+    });
+    let prefix = [TokenKind::Pound, TokenKind::Not, TokenKind::OpenBracket];
+    let starts_with_attribute = non_whitespace_tokens.take(3).eq(prefix.iter().map(|c| *c));
```
Comment (petrochenkov) [inline src/librustc_lexer/src/lib.rs:259]:
```suggestion
    let starts_with_attribute = non_whitespace_tokens.take(3).eq(prefix.iter().copied());
```

**Comment by petrochenkov** [comment]
Could you also squash all the commits after addressing the comments?

File: src/librustc_lexer/src/lib.rs (hunk 8 above)
Comment (rcoh) [reply src/librustc_lexer/src/lib.rs:278]: without this change, I couldn't call it with a str that isn't mut, but maybe I messed something up

**Comment by rcoh** [comment]
cleaned up, added some more tests, pushed, squashed.

**Review by petrochenkov — APPROVED** [review]

**Comment by petrochenkov** [comment]
I'm happy with the result.
r? @eddyb

**Comment by rcoh** [comment]
(just to clarify, AFAIK, not actually S-waiting-on-author ATM)

**Comment by petrochenkov** [comment]
I'm going to approve this due to the other reviewer's inactivity.

r? @petrochenkov 
@bors r+

**Comment by rcoh** [comment]
Looks like someone else fixed the same `#FIXME` 
```
error[E0201]: duplicate definitions with name `pos`:
   --> src/librustc_parse/lexer/mod.rs:423:5
    |
74  | /     pub fn pos(&self) -> BytePos {
75  | |         self.pos
76  | |     }
    | |_____- previous definition of `pos` here
...
423 | /     pub fn pos(&self) -> BytePos {
424 | |         self.pos
425 | |     }
    | |_____^ duplicate definition

error: aborting due to previous error

For more information about this error, try `rustc --explain E0201`.
error: could not compile `rustc_parse`.
```
