### PR TITLE
UdpSocket: document `recv/recv_from` differences

### LINKED ISSUE #149392: UdpSocket: recv() and recv_from() behave differently for zero sized buffers
With a zero length buffer  UdpSocket recv() behaves differently from recv_from().

(Only tested on MacOS M1 processor)

recv_from() returns the following error: 

Err(Error { kind: InvalidInput, message: "invalid argument" })

recv() instantly returns with Ok(0), even though no UDP packet has been received 

I would expect both to return Err(Error { kind: InvalidInput, message: "invalid argument" })

### Importance

The api is different for similar functions, I believe they should behave the same way.

I encountered the bug when using 

let mut buf=Vec::with_capacity(MTU);

Which could be an easy to overlook mistake.

Also recv() is returning even though no UDP packet has been received, in my case this led to a thread consuming 100% of a CPU.

## Test case:

```rust

#[cfg(test)]
mod tests {
    use std::net::{Ipv4Addr, UdpSocket};

    use super::*;

    #[test]
    fn test_rx_from() {
        let mut buf = [0; 0];
        let socket = UdpSocket::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
        let res = socket.recv_from(&mut buf);
        println!("{res:?}");
        assert!(res.is_err());
    }

    #[test]
    fn test_rx() {
        let mut buf = [0; 0];
        let socket = UdpSocket::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
        let res = socket.recv(&mut buf);
        println!("{res:?}");
        assert!(res.is_err());
    }
}

```

## Expected 

I expected to see this happen: 

I would expect both to return Err(Error { kind: InvalidInput, message: "invalid argument" })

I would not expect that recv instantly return an Ok(0) even though no UDP packet has been received.

## Actual 

Instead, this happened: 

```
running 2 tests
Err(Error { kind: InvalidInput, message: "invalid argument" })
Ok(0)

thread 'tests::test_rx' (15944916) panicked at src/main.rs:24:9:
assertion failed: res.is_err()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::test_rx_from ... ok
test tests::test_rx ... FAILED

failures:

failures:
    tests::test_rx

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

### Meta

`rustc --version --verbose`:
```
rustc 1.93.0-nightly (80d8f292d 2025-11-25)
binary: rustc
commit-hash: 80d8f292d82d735f83417221dd63b0dd2bbb8dd2
commit-date: 2025-11-25
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.5
```

`OS uname -a`

```
Darwin xxxxxx 25.0.0 Darwin Kernel Version 25.0.0: Mon Aug 25 21:17:45 PDT 2025; root:xnu-12377.1.9~3/RELEASE_ARM64_T8103 arm64
```

## Related 

Possibly related #55794 #123222

### PR DESCRIPTION
**Pull request by nia-e**
Per libs-api consensus, fixes rust-lang/rust#149392 by documenting possible platform-specific behavior in `UdpSocket`.

r? libs

### CODE REVIEW

File: library/std/src/net/udp.rs [hunk 1]
```diff
@@ -129,6 +129,10 @@ impl UdpSocket {
     /// hold the message bytes. If a message is too long to fit in the supplied buffer,
     /// excess bytes may be discarded.
     ///
+    /// Refer to the platform-specific documentation on this function; it is considered
+    /// correct for its behavior to differ from [`UdpSocket::recv`] if the underlying system
+    /// call does so.
```
Comment (Mark-Simulacrum) [inline library/std/src/net/udp.rs:134]: This sounds fine, but we don't tell people what this does under the hood, so I'm not sure they *can* refer to platform-specific documentation easily. Maybe we can add a section on what the underlying libc/syscall made is (with a link to https://doc.rust-lang.org/nightly/std/io/index.html#platform-specific-behavior)?

**Review by Mark-Simulacrum — CHANGES_REQUESTED** [review]
r=me with nit applied or if you don't feel its warranted (people can guess based on the name) we can leave it to a future PR

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154266/13e2abaac846b2680ae93e1b3bd9fe7fe1b9a7fe..d873e1f49cee7afc220dbb2c9b34d6bbdc941e05)*

File: library/std/src/net/udp.rs (hunk 1 above)
Comment (nia-e) [reply library/std/src/net/udp.rs:134]: Discussed this in the libs-api meeting; we intentionally don't guarantee this right now, but most platforms have an "obvious" choice (e.g. recvfrom on linux)
