### PR TITLE
Fix issue: Global paths in `use` directives can begin with `super` or `self` #32225 

### LINKED ISSUE #32225: Global paths in `use` directives can begin with `super` or `self`
For example,
```rust
mod foo {
    fn f() {}
    
    fn g() {
        use ::super::foo::f; // This is currently allowed,
        ::super::foo::f(); // but this is not.
    }
}
```

### PR DESCRIPTION
**Pull request by vlastachu**
This PR fixes #32225 by warning on `use ::super::...` and `use ::self::...` on `resolve`.

Current changes is the most minimal and ad-hoc.

### CODE REVIEW

**Comment by petrochenkov** [comment]
This should probably be checked after macro expansion and not in parser (due to macros) + for all paths and not only for imports.
AFAIK, we don't have a dedicated "sanity check" post-expansion visitor in libsyntax, so `lower_path`/`lower_view_path` in `librustc_front/lowering.rs` may be the most appropriate place for this check.

**Comment by vlastachu** [comment]
@petrochenkov Okay, would try to remake in near future

**Comment by jseyfried** [comment]
@petrochenkov I believe this already checks macro expanded code since macro expanded code is parsed just like other code.

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -1774,6 +1776,7 @@ impl<'a> Parser<'a> {
         })
     }
 
+
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: There's no need for these added newlines

File: src/libsyntax/parse/token.rs [hunk 2]
```diff
@@ -323,6 +323,22 @@ impl Token {
...
+    #[allow(non_upper_case_globals)]
+    pub fn is_special_ident_in_modname(&self) -> bool {
+        match *self {
+            Ident(sid, ModName) => {
+                let n = sid.name;
+
+                   n == SELF_KEYWORD_NAME
+                || n == STATIC_KEYWORD_NAME
+                || n == SUPER_KEYWORD_NAME
+                || n == SELF_TYPE_KEYWORD_NAME
```
Comment (jseyfried) [inline src/libsyntax/parse/token.rs]: I would prefer we just check `SUPER_KEYWORD_NAME` and `SELF_KEYWORD_NAME` here so the errors are as consistent as possible with other paths.

File: src/libsyntax/parse/parser.rs [hunk 3]
```diff
@@ -6024,7 +6027,13 @@ impl<'a> Parser<'a> {
 
         // Allow a leading :: because the paths are absolute either way.
         // This occurs with "use $crate::..." in macros.
-        self.eat(&token::ModSep);
+        let is_global = self.eat(&token::ModSep);
+
+        // Checking that there is no `self` or `super` in global context
+        if is_global && self.token.is_special_ident_in_modname() {
+            return Err(self.fatal(&format!("expected identifier, found keyword `{}`",
+                                       self.this_token_to_string())));
```
Comment (jseyfried) [inline src/libsyntax/parse/parser.rs]: nit: this line should start at the same column as the third `(` in the above line

**Comment by jseyfried** [comment]
@vlastachu Thanks for the PR! I like this implementation.

Could you squash the existing commits and add a `compile-fail` test? Something like
```
use ::super::foo; //~ ERROR expected identifier, found keyword `super`
```

Also, the initial comment should be a summary of the PR (something like "This fixes #32225 by forbidding `use ::super::...` and `use ::self::...` in the parser").

**Comment by jseyfried** [comment]
@alexcrichton could you grep through the crates.io code for `use ::self` or `use ::super` to assess breakage?

File: src/libsyntax/parse/token.rs (hunk 2 above)
Comment (vlastachu) [inline src/libsyntax/parse/token.rs]: Sure. But than name of function will be incorrect. Is it ok to rename to `is_self_or_super_in_modname`.
Or move this checking to parser? In first commit this function was meaningful, now it's function for one call.

Comment (jseyfried) [inline src/libsyntax/parse/token.rs]: > Or move this checking to parser?

I think that would be best.

**Comment by alexcrichton** [comment]
A cursory grep yielded:

* https://github.com/farseerfc/ydcv-rs/blob/55c267923994027edea64028d594cb315680d1bb/src/formatters.rs#L118
* https://github.com/andelf/rust-algs4/blob/fb9ff77df4b1cd7ca1eff5749eff7b216a9db1f1/src/sorting/mod.rs#L53-L64
* https://github.com/maidsafe/crust/blob/master/src/config_handler.rs (in version 0.8.0 of the crate, not the current version)

**Comment by petrochenkov** [comment]
@jseyfried 
> I believe this already checks macro expanded code since macro expanded code is parsed just like other code.

I meant something like
```
macro_rules! m {
    ($i: ident) => (::$i)
}

m!(self)
```
I'm not exactly sure if it's reparsed or not. (but `m!(self)` doesn't compile because `self` here isn't considered an `ident` for some reason). Anyway, there are procedural macros, they still can generate such paths.
This is also a semantic check and not syntactic, something like `::super::self::Self::super` is a perfectly grammatical path and parsing can continue (this PR makes parsing stop after this error). IMO, such paths would be better rejected by resolve or a some other post-expansion sanity check pass, but it's not a blocker, at least this patch covers the common case.

**Comment by vlastachu** [comment]
@petrochenkov I can't reproduce successful compilation with macro. Looks like there is additional checking for keywords. Probably any way to cheat parser and give `super` to macro is existing. But I'm not found. I was trying to replace the `ident` type with something else.

> `::super::self::Self::super` is a perfectly grammatical path 

I don't get it. May be I don't understand this sentence right. Anyway global `super` is wrong. Probably there should be more general rule like "`super`, `self` or `Self` is appearing only at begin of global path" (the real rule may be more complicated) which should be checked before search of crates and modules. And such rule cancels necessity of my changes.
Are you about that?

**Comment by vlastachu** [comment]
@jseyfried 

> add a compile-fail test

done

> Could you squash the existing commits

When all discussions will completed and last changes reviewed.

**Comment by jseyfried** [comment]
@petrochenkov 
> Anyway, there are procedural macros, they still can generate such paths.

Good point. I believe the path from your example is re-parsed but it doesn't really matter given procedural macros. Also, I agree that this should be a semantic rather than a syntactic error.

@vlastachu Reviewed all commits, the test looks good.

I think it would be best to have the check [here](https://github.com/rust-lang/rust/blob/65ec4dfe61a70de869c2b62948af7d172c8ee612/src/librustc_resolve/build_reduced_graph.rs#L140), in the `build_reduced_graph` phase of `resolve`.

Since it won't add much complexity, I think we should do a warning cycle. [This commit](https://github.com/rust-lang/rust/pull/31362/commits/5172745da761842a40a625c804f5e0360586996d) is an example of starting a warning cycle.

**Comment by vlastachu** [comment]
@jseyfried 

> I think it would be best to have the check here, in the build_reduced_graph phase of resolve.

Can you explain more about this? Am I remove all checking from parser and write similiar to pointed function? Then I  should write it in single style with `ResolutionError::SelfImportCanOnlyAppearOnceInTheList`, `ResolutionError::SelfImportOnlyInImportListWithNonEmptyPrefix`.

At first I thought that it is necessary to make warnings  and  stopped  on that I can't make similiar warning in parser session. If I should save current parser checking than could you help  with `add_lint`  for warning in parser context  (probably  there is should be any macro like span_warn!).

**Comment by jseyfried** [comment]
Yeah, there should be no checking in the parser, only in `build_reduced_graph.rs`.

I wouldn't write a helper function (I think this is what you mean by pointed function) but you can if you want. Also, I wouldn't bother with the `ResolutionError` enum.

[Here](https://github.com/rust-lang/rust/blob/213d57983d1640d22bd69e7351731fd1adcbf9b2/src/librustc_resolve/lib.rs#L3516) is an example of a warning in `resolve`.

**Comment by jseyfried** [comment]
@vlastachu would you like to work on moving the check to `build_reduced_graph.rs` and making it a warning? If not, I can take it from here.

**Comment by vlastachu** [comment]
@jseyfried Yes, I would. Sory for silence. I was planning to do this at weekend. But for some reason I did not find the time. I will try to finish everything before the end of the week, or will notify you that I can not.

**Comment by jseyfried** [comment]
Thanks, no hurry!

**Comment by vlastachu** [comment]
@jseyfried [here](https://github.com/rust-lang/rust/blob/65ec4dfe61a70de869c2b62948af7d172c8ee612/src/librustc_resolve/build_reduced_graph.rs#L145) `fullpath.global` and [here](https://github.com/rust-lang/rust/blob/65ec4dfe61a70de869c2b62948af7d172c8ee612/src/librustc_resolve/build_reduced_graph.rs#L155) `module_ident_path.global` is always false.

[Comments](https://github.com/rust-lang/rust/blob/65ec4dfe61a70de869c2b62948af7d172c8ee612/src/librustc_front/hir.rs#L155) says that this flag works as expected.

**Comment by jseyfried** [comment]
Good point. I believe you can fix the flag by changing [this line](https://github.com/rust-lang/rust/blob/a11129701c873d96fe0816e4c8b55510efebe96e/src/libsyntax/parse/parser.rs#L6133) to
```rust
let is_global = self.eat(&token::ModSep);
```
and then replacing `global: false` with `global: is_global` (four times).

**Comment by vlastachu** [comment]
1.  Checking may be made simpler if it necessary (like it was made before at parser)
```
if is_global && (name == SELF_KEYWORD_NAME || name == SUPER_KEYWORD_NAME)
```
Without unusual  loop. 

2. Now I see unresolved conflicts. Am I need to `git rebase master` ?

File: src/librustc/lint/builtin.rs [hunk 4]
```diff
@@ -154,6 +154,12 @@ declare_lint! {
     "transmute from function item type to pointer-sized type erroneously allowed"
 }
 
+declare_lint! {
+    pub SUPER_OR_SELF_IN_GLOBAL_MODNAME,
+    Warn,
+    "detects super or self keywords in begin of global path"
```
Comment (jseyfried) [inline src/librustc/lint/builtin.rs]: nit: "detects super or self keywords at the beginning of global paths"

**Comment by jseyfried** [comment]
@vlastachu Nice, looks good!

> Checking may be made simpler if it necessary

I would prefer the simpler checking you described, at least until the warning becomes a hard error.

> Now I see unresolved conflicts. Do I need to `git rebase master`?

Yeah, I would also squash all your commits into a single commit first, both for cleaner history and easier rebasing.

File: src/librustc/lint/builtin.rs [hunk 5]
```diff
@@ -179,6 +179,12 @@ declare_lint! {
     "lints that have been renamed or removed"
 }
 
+declare_lint! {
+    pub SUPER_OR_SELF_IN_GLOBAL_MODNAME,
```
Comment (jseyfried) [inline src/librustc/lint/builtin.rs]: nit: rename to `SUPER_OR_SELF_IN_GLOBAL_PATH`

File: src/test/compile-fail/use-super-global-path.rs [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![feature(rustc_attrs)]
+
+mod foo {
+    pub fn g() {
+        use ::super::main; //~ WARN expected identifier, found keyword `super`, #[warn(super_or_self_in_global_modname)] on by default
```
Comment (jseyfried) [inline src/test/compile-fail/use-super-global-path.rs]: You can use a substring of the error message here (e.g. ``//~ WARN expected identifier, found keyword `super` ``) to avoid the long line tidy error.

File: src/librustc_resolve/build_reduced_graph.rs [hunk 7]
```diff
@@ -137,6 +141,18 @@ impl<'b, 'tcx:'b> Resolver<'b, 'tcx> {
...
 
+                // Checking for special identifiers in path
+                // prevent `self` or `supper` at beginning of global path
+                if is_global && (module_path.first() == Some(&SELF_KEYWORD_NAME) ||
+                                 module_path.first() == Some(&SUPER_KEYWORD_NAME)) {
+                    self.session.add_lint(
+                        lint::builtin::SUPER_OR_SELF_IN_GLOBAL_MODNAME,
+                        item.id,
+                        item.span,
+                        format!("expected identifier, found keyword `{}`",
```
Comment (jseyfried) [inline src/librustc_resolve/build_reduced_graph.rs]: (there is a tidy error due to a trailing space on this line)

**Comment by jseyfried** [comment]
@vlastachu Excellent!

In your initial comment, could you change "forbidding" to "warning on" and "during parsing" to "in `resolve`" and also remove the part about the failed tests?

r=me with that edit and with the nits addressed.

File: src/librustc_resolve/build_reduced_graph.rs [hunk 8]
```diff
@@ -137,6 +141,18 @@ impl<'b, 'tcx:'b> Resolver<'b, 'tcx> {
                     }
                 };
 
+                // Checking for special identifiers in path
+                // prevent `self` or `supper` at beginning of global path
```
Comment (jseyfried) [inline src/librustc_resolve/build_reduced_graph.rs]: nit: `` .. or `super` at .. ``

**Comment by vlastachu** [comment]
@jseyfried Complete.
