### PR TITLE
compiletest: include stage0-sysroot libstd dylib in recipe dylib search path

### LINKED ISSUE #135373: run-make tests no longer work at stage 0 at all
this is useful for run-make tests that actually test tools or the standard library, and not the compiler itself, however it now seems to just result in a linker error.

command: `COMPILETEST_FORCE_STAGE0=1 ./x test tests/run-make/rustdoc-default-output/`

error:
```
[run-make] tests/run-make/rustdoc-default-output ... F


failures:

---- [run-make] tests/run-make/rustdoc-default-output stdout ----

error: rmake recipe failed to complete
status: exit status: 127
command: cd "/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/test/run-make/rustdoc-default-output/rmake_out" && env -u RUSTFLAGS AR="ar" CARGO="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" CC="gcc" CC_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" CXX="g++" CXX_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" HOST_RPATH_DIR="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/lib" LD_LIBRARY_PATH="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/lib:/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin:/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" LD_LIB_PATH_ENVVAR="LD_LIBRARY_PATH" LLVM_COMPONENTS="" LLVM_FILECHECK="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/ci-llvm/bin/FileCheck" NODE="/nix/store/k5inwzpp6a0295pd3nfckk9hq8wmifhz-nodejs-20.15.1/bin/node" PYTHON="/home/binarycat/.nix-inst-profile/bin/python3" RUSTC="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" RUSTDOC="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustdoc" SOURCE_ROOT="/home/binarycat/src/rs/rust" TARGET="x86_64-unknown-linux-gnu" TARGET_RPATH_DIR="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" TARGET_RPATH_ENV="/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/test/run-make/rustdoc-default-output/rmake_out:/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/stage0/lib" "/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/test/run-make/rustdoc-default-output/rmake"
stdout: none
--- stderr -------------------------------
/home/binarycat/src/rs/rust/build/x86_64-unknown-linux-gnu/test/run-make/rustdoc-default-output/rmake: error while loading shared libraries: libstd-96b6fb01dfb1a1ef.so: cannot open shared object file: No such file or directory
------------------------------------------



failures:
    [run-make] tests/run-make/rustdoc-default-output

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 382 filtered out; finished in 1.97s
```

### PR DESCRIPTION
**Pull request by jieyouxu**
To fix some of the failures in `COMPILETEST_FORCE_STAGE0=1 ./x test run-make --stage 0`. Specifically,

```
COMPILETEST_FORCE_STAGE0=1 ./x test tests/run-make/rustdoc-default-output/ --stage 0
```

should now pass.

Fixes #135373. (As in, make *some* of the `run-make` tests pass, other `run-make` tests fail for various reasons against stage0, and generally `run-make` tests are not guaranteed to pass at stage 0.)

cc @lolbinarycat 

r? bootstrap

### CODE REVIEW

**Comment by lolbinarycat** [comment]
weirdly, i just got *bootstrap itself* failing due to not being able to find libstd (i was just trying to run `x fmt`)

i don't really know how to repro, maybe it has something to do with switching branches, or maybe there was some change to rpath calculation that needs to be reverted.

also one time i had the opposite problem, where there were two possible versions of libstd, and bootstrap (or was it rustc?) couldn't decide which to use.

**Comment by jieyouxu** [comment]
Sometimes between compiler bumps and bootstrap changes you may need to `./x clean`.

**Comment by lolbinarycat** [comment]
that's a command implemented in the rust side of bootstrap, *which i cannot build*.

i think i need to rebuild everything, which probably isn't happening today.

**Comment by lolbinarycat** [comment]
yeah removing `build/` and rebuilding everything seemed to fix it.

File: src/tools/compiletest/src/runtest/run_make.rs [hunk 1]
```diff
@@ -373,6 +373,14 @@ impl TestCx<'_> {
         // Compute dynamic library search paths for recipes.
         let recipe_dylib_search_paths = {
             let mut paths = base_dylib_search_paths.clone();
+
+            // For stage 0, we need to explicitly include the stage0-sysroot libstd dylib.
```
Comment (onur-ozkan) [inline src/tools/compiletest/src/runtest/run_make.rs:377]:
```suggestion
            // For stage 0, we need to explicitly include the stage0-sysroot libstd dylib.
            // See https://github.com/rust-lang/rust/issues/135373
```

**Review by onur-ozkan — APPROVED** [review]
Seems good to me other than a nit

File: src/tools/compiletest/src/runtest/run_make.rs (hunk 1 above)
Comment (jieyouxu) [reply src/tools/compiletest/src/runtest/run_make.rs:377]: Added link.

**Comment by jieyouxu** [comment]
Addressed the nit.
@bors r=@onur-ozkan rollup
