### PR TITLE
Track devirtualized filenames

### LINKED ISSUE #70924: 'rustc' panicked at 'failed to lookup `SourceFile` in new context'
Hi.
I did cargo build and suddenly this goes to my console:
```   Compiling hard v0.1.0 (/home/manio/IdeaProjects/hard)
error: cannot find attribute `get` in this scope
  --> src/webserver.rs:15:3
   |
15 | #[get("/<name>/<age>")]
   |   ^^^

warning: unused import: `rocket`
 --> src/webserver.rs:4:5
  |
4 | use rocket;
  |     ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (6dee5f112 2020-04-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `hard`.

To learn more, run the command again with --verbose.
```

I gave it another try and this is the backtrace:
https://pastebin.com/JLQy9Ear

I am using today nightly. It was compiling fine before... anyway as I believe that the problem is with panic - I am reporting this bug.

### PR DESCRIPTION
**Pull request by pnkfelix**
Split payload of FileName::Real to track both real and virtualized paths.

(Such splits arise from metadata refs into libstd; the virtualized paths look like `/rustc/1.45.0/src/libstd/io/cursor.rs` rather than `/Users/felixklock/Dev/Mozilla/rust.git/src/libstd/io/cursor.rs`)

This way, we can emit the virtual name into things like the like the StableSourceFileId (as was done back before PR #70642) that ends up in incremental build artifacts, while still using the devirtualized file path when we want to access the file.

Fix #70924

### CODE REVIEW

**Comment by pnkfelix** [comment]
cc @eddyb @Mark-Simulacrum

File: src/librustc_interface/passes.rs [hunk 1]
```diff
@@ -568,14 +568,13 @@ fn write_out_deps(
...
                     let source = resolver.cstore().crate_source_untracked(cnum);
-                    if let Some((path, _)) = source.dylib {
-                        files.push(escape_dep_filename(&FileName::Real(path)));
-                    }
-                    if let Some((path, _)) = source.rlib {
-                        files.push(escape_dep_filename(&FileName::Real(path)));
-                    }
-                    if let Some((path, _)) = source.rmeta {
-                        files.push(escape_dep_filename(&FileName::Real(path)));
+                    match source {
```
Comment (pnkfelix) [inline src/librustc_interface/passes.rs:571]: Oh! I just reaized tha this change was incorrect. (At least, I assume we can have scenarios where the paths here are different, and we need to make multiples calls to `files.push`!) Sorry!

Comment (pnkfelix) [reply src/librustc_interface/passes.rs]: (fixed by removing the erroneous refactoring and living with some resulting ugly code duplication.)

**Comment by pnkfelix** [comment]
A note on the lack of a regression test for #70924: I don't have a regression test as part of the PR, because I'm not sure how to make one. my local replication relies on either adding/removing the rust-src component in rustup , or actually renaming the rustlib/src/rust subdirectory in my build directory.

(Either of these options don't seem to lend themselves to a test in our infrastructure, no?)

**Comment by pnkfelix** [comment]
I'm going to unilaterally tag this as beta-accepted, based on the [conversation in today's T-compiler meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/94984steeringmeetingroadmap20200529compilerteam287.html#199157775)

However, as noted in my recent [chat](https://zulip-archive.rust-lang.org/131828tcompiler/31508ICEfailedtolookupSourceFileinnewcontext70924.html#199236384) with @Mark-Simulacrum: please do wait until after this has been reviewed before backporting it into beta and/or stable. I don't want my unilateral beta-backport approval to inadvertently sidestep the review process entirely.

File: src/librustc_span/lib.rs [hunk 2]
```diff
@@ -81,11 +81,58 @@ impl Globals {
...
+    Named(PathBuf),
+    /// For de-virtualized paths (namely paths into libstd that have been mapped
+    /// to the appropriate spot on the local host's file system),
+    Devirtualized {
+        /// `local_path` is the (host-dependent) local path to the file.
+        local_path: PathBuf,
+        /// `virtual_name` is the stable path rustc will store internally within
+        /// build artifacts.
+        virtual_name: PathBuf,
+    },
```
Comment (eddyb) [inline src/librustc_span/lib.rs:97]: I didn't consider this but I guess it makes sense. If we're willing to do this, we can just remove the `/rustc/.../` hack of encoding it as a path and just rely on this `enum`. (You can open an issue about this and/or leave a FIXME in the code if you want)

**Review by eddyb — APPROVED** [review]
r=me with or without extra long-term/low-priority FIXME (for removing the `/rustc/.../` encoding into paths altogether)

File: src/librustc_span/lib.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_span/lib.rs:97]: Great! I was musing about such a change in my head, so I'm glad to hear you had similar thoughts. I'll add the FIXME; there's already so many others in this PR, another won't hurt.

**Comment by pnkfelix** [comment]
@bors rollup=never

(this change is subtle and hard to test, and I want to maximize our ability to bisect to it if necessary.)

**Comment by pnkfelix** [comment]
@bors p=1

this is a bugfix to a subtle incremental compilation bug that I have seen come up in my own workflow for building rustc itself (ironically, it happened while I was double-checking the intermediate commits of this PR itself were buildable). So I am upping the priority slightly, but not more than the PR's that have also had their priorities increased.

**Comment by pnkfelix** [comment]
> A note on the lack of a regression test for #70924: I don't have a regression test as part of the PR, because I'm not sure how to make one. my local replication relies on either adding/removing the rust-src component in rustup , or actually renaming the rustlib/src/rust subdirectory in my build directory.
> 
> (Either of these options don't seem to lend themselves to a test in our infrastructure, no?)

I just realized that I *might* be able to test this by invoking rustc while overriding the sysroot via `--sysroot`. I'll look into that, and if it bears fruit, then I'll make a regression test for #70924 in a separate PR.

File: src/librustc_span/source_map.rs [hunk 3]
```diff
@@ -95,14 +97,21 @@ impl StableSourceFileId {
...
 
-        name.hash(&mut hasher);
+        if let FileName::Real(real_name) = name {
+            // rust-lang/rust#70924: Use the stable (virtualized) name when
+            // available. (We do not want artifacts from transient file system
+            // paths for libstd to leak into our build artifacts.)
+            real_name.stable_name().hash(&mut hasher)
+        } else {
+            name.hash(&mut hasher);
+        }
```
Comment (eddyb) [inline src/librustc_span/source_map.rs:114]: I just noticed a problem with this (although it's unlikely to cause issues in practice): the hashed data could overlap.
A better approach might be to hash tuples that are `(0u8, ...)` in the first case and `(1u8, ...)` in the second one.

If we had an `Either` enum around, producing a value of that and hashing *it* would be even better (since there would be a single hash call).
