### PR TITLE
Fix signature by adding parens when needed

### LINKED ISSUE #42299: Missing parentheses around trait object in rustdoc
```rust
pub fn f(_: &(ToString + 'static)) {}
```

This function is documented as:

> selection_055

The parentheses are missing and the function would not compile without them:

```
error[E0178]: expected a path on the left-hand side of `+`, not `&ToString`
 --> src/main.rs:1:13
  |
1 | pub fn f(_: &ToString + 'static) {}
  |             ^^^^^^^^^^^^^^^^^^^ help: try adding parentheses: `&(ToString + 'static)`
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #42299.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Looks good, though I think you'll wind up racing #42286 to the merge since you both mess with the signature of `fmt_type`.

**Review by QuietMisdreavus — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I'll improve the priority a bit then.

@bors: p=1

File: src/librustdoc/html/format.rs [hunk 1]
```diff
@@ -788,14 +797,14 @@ fn fmt_type(t: &clean::Type, f: &mut fmt::Formatter, use_absolute: bool,
                 _ => {
```
Comment (ollie27) [inline src/librustdoc/html/format.rs]: I think it would be better to add a case for `ResolvedPath` here to render the parenthesis rather than passing bool parameters everywhere.

File: src/librustdoc/html/format.rs [hunk 2]
```diff
@@ -534,7 +535,7 @@ fn resolved_path(w: &mut fmt::Formatter, did: DefId, path: &clean::Path,
             } else {
                 format!("{}", HRef::new(did, &last.name))
             };
-            write!(w, "{}{}", path, last.params)?;
+            write!(w, "{}{}{}", if need_paren { "(" } else { "" }, path, last.params)?;
```
Comment (ollie27) [inline src/librustdoc/html/format.rs]: This is missing the `print_all` and `w.alternate()` cases above although that won't be an issue if you render the parenthesis in `fmt_type` itself like I suggest.

**Review by ollie27 — CHANGES_REQUESTED** [review]

File: src/librustdoc/html/format.rs (hunk 1 above)
Comment (GuillaumeGomez) [inline src/librustdoc/html/format.rs]: I'm not sure it'd be better. But don't hesitate to do it if you think it can be improved.
