### PR TITLE
Check for known but incorrect attributes

### LINKED ISSUE #43988: Known but incorrect attributes over statements/expressions are ignored.
I tried to look for this, but I couldn't find an existing issue. Or is this expected behaviour?

Putting attributes that exist (though the arguments can be bogus) seem to be ignored when one would expect an error, or at least a warning. E.g like this: 
```rust
#[repr(bogus_statement)]
let x = 0;
```

or 
```rust
#[inline(bogus_statement)]
let x = 0;
```

This seems to be the case on stable, beta and nightly.

More examples here: https://play.rust-lang.org/?gist=b48bfc076d29c770d8d2c81f2f99f0bb

### PR DESCRIPTION
**Pull request by tejom**
fixes #43988

- Change nested_visit_map so it will recursively check functions

- Add visit_stmt and visit_expr for impl Visitor for CheckAttrVisitor and check for incorrect
inline and repr attributes on staements and expressions

- Add regression test for issue #43988

### CODE REVIEW

**Comment by tejom** [comment]
r? @petrochenkov 

@abonander

**Comment by abonander** [comment]
@tejom so that PR was a rollup which added code for another attribute to `CheckAttrVisitor`: https://github.com/rust-lang/rust/pull/49308/files#diff-a7a4db27e720b5572001d15719153b54

The preferred approach is to rebase on top of master (`git rebase upstream/master` where `upstream` is `rust-lang/rust`) and then resolve the merge conflict that comes up.

**Comment by tejom** [comment]
Alright cool. The commit doesn't look to crazy to deal with. Thanks!

File: src/librustc/hir/check_attr.rs [hunk 1]
```diff
@@ -189,17 +194,85 @@ impl<'a, 'tcx> CheckAttrVisitor<'a, 'tcx> {
...
+    }
+
+    fn check_expr_attributes(&self, expr: &hir::Expr) {
+        use hir::Expr_::*;
+        match expr.node {
+            // Assignments, Calls and Structs were handled by Items and Statements
+            ExprCall(..) |
+            ExprAssign(..) |
+            ExprMethodCall(..) |
+            ExprStruct(..) => return,
```
Comment (petrochenkov) [inline src/librustc/hir/check_attr.rs]: I don't understand what is the logic here.
How attributes on `#[attr] my_fn_call()` could be handles by items or statements?

**Comment by petrochenkov** [comment]
LGTM beside one comment (also needs rebase).

File: src/librustc/hir/check_attr.rs (hunk 1 above)
Comment (tejom) [reply src/librustc/hir/check_attr.rs]: I think I got confused reading the comments on the `Expr_` enum. I think only `ExprAssign`  overlaps with statements then.

`let a = 1` seems to be both an expression and statement?

I can take this section out and everything seems to work fine still. The error that appears for 
```rust 
#[repr]
let _y = "123";
```
 is `attribute should not be applied to statements` with and without this match.

Comment (petrochenkov) [reply src/librustc/hir/check_attr.rs]: `let a = 1` is not an expression, `ExprAssign` is `a = b`.

If you have a statement with one expression, like
```
a = b;
```
then it's represented roughly like `StmtExpr(ExprAssign)` and attributes are attached to the outer statement and not inner expression.

File: src/librustc/hir/check_attr.rs [hunk 2]
```diff
@@ -250,7 +250,7 @@ impl<'a, 'tcx> CheckAttrVisitor<'a, 'tcx> {
                     self.emit_repr_error(
                         attr.span,
                         stmt.span,
-                        &format!("attribute should not be applied to statements"),
+                        &format!("attribute should not be applied a statement"),
```
Comment (petrochenkov) [inline src/librustc/hir/check_attr.rs]: Missing "to".

File: src/test/compile-fail/issue-43988.rs [hunk 3]
```diff
@@ -32,5 +31,12 @@ fn main() {
...
     let _y = "123";
-    //~^^ ERROR attribute should not be applied to statements
+    //~^^ ERROR attribute should not be applied a statement
+
+
+    fn foo() {}
+
+    #[inline(ABC)]
+    foo();
+    //~^^ ERROR attribute should be applied to function
```
Comment (petrochenkov) [inline src/test/compile-fail/issue-43988.rs]: All the tests are for statements, could you add a test for an expression too?
Something like `let x = #[repr] y;`

**Comment by petrochenkov** [comment]
r=me after addressing comments

File: src/librustc/hir/check_attr.rs (hunk 1 above)
Comment (tejom) [reply src/librustc/hir/check_attr.rs]: Oh Ok. I see. Thanks for the clarification.

File: src/test/compile-fail/issue-43988.rs (hunk 3 above)
Comment (tejom) [reply src/test/compile-fail/issue-43988.rs]: I added this example. I needed to add a feature in the tests to get it to actually run.

Otherwise `error[E0658]: attributes on non-item statements and expressions are experimental. (see issue #15701)` stopped all of the tests early.

**Comment by kivikakk** [comment]
Hey there, I'm investigating https://github.com/pest-parser/pest/issues/218, where pest fails to build on nightly 2018-03-29; it looks like this merge is the change that did it.

I'm not sure exactly why, but one suspicion is that `#[inline]` as applied to a lambda is now being disallowed? Take this example:

```rust
fn main() {
	#[inline] || { };
}
```

This compiles without any warning or error on e5277c145 2018-03-28, but on ae544ee1c 2018-03-29:

```console
$ rustc test.rs
error[E0518]: attribute should be applied to function
 --> test.rs:2:2
  |
2 |     #[inline] || { };
  |     ^^^^^^^^^ ------ not a function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0518`.
```

Is this intentional?

**Comment by petrochenkov** [comment]
>Is this intentional?

Yes, `#[inline]` never had any effect on lambdas.
(IIRC, operator `()` on lambdas is automatically marked as inline by the compiler.)

**Comment by Amanieu** [comment]
Actually, `#[inline(always)]` **does** have an effect on closures. This doesn't work any more and I have some code that relies on inline for optimizations.

**Comment by Amanieu** [comment]
The generated LLVM IR (in debug builds) for this example is different if you remove `#[inline(always)]`:
```rust
 #![feature(stmt_expr_attributes)] 
 #![crate_type="rlib"]

pub fn main() {
    let x = #[inline(always)] || {};
    x();
}
```

**Comment by tejom** [comment]
It looks like the code generated for your example with `-O` option is the same for both? That's what I saw with the stable build.

**Comment by Amanieu** [comment]
That's because the closure is inlined anyways in release builds. You only notice the difference in debug builds where inline hint are ignored unless they are forced.

My point is that `#[inline(always)]` **does** have an effect on code generation when applied to closures, and this change is a regression since it now disallows this (though technically not a break change since `stmt_expr_attributes` is still unstable anyways).

**Comment by tejom** [comment]
I'm just asking because I'm curious, would this be bug with the compiler not inlining closures when not using one of the higher optimization levels? Seems like that is what the expected behavior was?

**Comment by Amanieu** [comment]
The inlining works fine. The bug is that your PR is too strict: `#[inline]` should be allowed on closures as well as functions.
