### PR TITLE
Fix sysroot on macOS when cross-compiling and SDKROOT is set

### LINKED ISSUE #7283: Build scripts fail on macOS if the target SDK is not the same as the host
**Problem**

Invoking `cargo build` from an Xcode project targeting iOS or iOS Simulator fails to build any crate with a custom build script, because the wrong linker is invoked for the custom build script. This is because Xcode sets `SDKROOT` for the target platform (the build script must be built for the host platform instead)

**Steps**

1. `git clone git@github.com:rust-lang/libc.git && cd libc`
2. ```SDKROOT=`xcrun --sdk iphonesimulator --show-sdk-path` cargo +nightly build --target x86_64-apple-ios -vv```
    *or*
    ```SDKROOT=`xcrun --sdk iphoneos --show-sdk-path` cargo +nightly build --target x86_64-apple-ios -vv```
3. The custom build script is built with the iPhoneSimulator SDK linker instead of the MacOSX SDK linker, which causes the build to fail with undefined symbols

**Possible Solution(s)**

Invoking `rustc` for the custom build script should always use the SDK for the host platform instead of the target platform (that is, ignore the `SDKROOT` environment variable set by the user or Xcode). This can be achieved, for example, by Cargo prepending the `rustc` invocation with `SDKROOT=""`

**Notes**

Output of `cargo version`: cargo 1.37.0 (9edd08916 2019-08-02)

### PR DESCRIPTION
**Pull request by ghost**
Fixes rust-lang/cargo#7283
Closes rust-lang/cargo#7284

r? @alexcrichton

### CODE REVIEW

File: src/librustc_target/spec/apple_base.rs [hunk 1]
```diff
@@ -51,3 +51,46 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+    // Like Clang, allow the SDKROOT environment variable used by Xcode to define the sysroot
+    if let Some(sdk_root) = env::var("SDKROOT").ok() {
+        let sdk_root_p = Path::new(&sdk_root);
+        // Ignore SDKROOT if it's not a valid path
+        if !sdk_root_p.is_absolute() || sdk_root_p == Path::new("/") || !sdk_root_p.exists() {
+            return Ok(actual_sdk_path);
+        }
+        // Ignore SDKROOT if it's clearly set for the wrong platform, which may occur when we're
+        // compiling a custom build script while targeting iOS for example
+        match sdk {
```
Comment (Centril) [inline src/librustc_target/spec/apple_base.rs]:
```suggestion
        return Ok(match sdk {
```

File: src/librustc_target/spec/apple_base.rs [hunk 2]
```diff
@@ -51,3 +51,46 @@ pub fn macos_llvm_target(arch: &str) -> String {
     let (major, minor) = macos_deployment_target();
     format!("{}-apple-macosx{}.{}.0", arch, major, minor)
 }
+
+pub fn sysroot(sdk: &str) -> Result<String, String> {
+    let actual_sdk_path = sdk_path(sdk)?;
+    // Like Clang, allow the SDKROOT environment variable used by Xcode to define the sysroot
```
Comment (Centril) [inline src/librustc_target/spec/apple_base.rs]:
```suggestion
    // Like Clang, allow the SDKROOT environment variable used by Xcode to define the sysroot.
```

File: src/librustc_target/spec/apple_base.rs [hunk 3]
```diff
@@ -51,3 +51,46 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+    if let Some(sdk_root) = env::var("SDKROOT").ok() {
+        let sdk_root_p = Path::new(&sdk_root);
+        // Ignore SDKROOT if it's not a valid path
```
Comment (Centril) [inline src/librustc_target/spec/apple_base.rs]:
```suggestion
        // Ignore `SDKROOT` if it's not a valid path.
```

File: src/librustc_target/spec/apple_base.rs [hunk 4]
```diff
@@ -51,3 +51,46 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+        if !sdk_root_p.is_absolute() || sdk_root_p == Path::new("/") || !sdk_root_p.exists() {
+            return Ok(actual_sdk_path);
+        }
+        // Ignore SDKROOT if it's clearly set for the wrong platform, which may occur when we're
```
Comment (Centril) [inline src/librustc_target/spec/apple_base.rs]:
```suggestion
        // Ignore `SDKROOT` if it's clearly set for the wrong platform, which may occur when we're
```

File: src/librustc_target/spec/apple_base.rs [hunk 5]
```diff
@@ -51,3 +51,46 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+        // compiling a custom build script while targeting iOS for example
```
Comment (Centril) [inline src/librustc_target/spec/apple_base.rs]:
```suggestion
        // compiling a custom build script while targeting iOS for example.
```

File: src/librustc_target/spec/apple_base.rs [hunk 6]
```diff
@@ -51,3 +51,63 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+            "macosx" | "macosx10.15" if sdk_root.contains("iPhoneOS.platform")
+                || sdk_root.contains("iPhoneSimulator.platform") => actual_sdk_path,
+            _ => sdk_root,
+        }))
+    }
+    Ok(None)
+}
+
+// `xcrun` is only available on macOS.
+#[cfg(not(target_os = "macos"))]
```
Comment (alexcrichton) [inline src/librustc_target/spec/apple_base.rs]: None of the changes here are using macOS-specific APIs in the binary, so could `#[cfg]` be avoided here and instead `if cfg!(...)` used instead? I think we'll want to gracefully handle errors from `xcrun` regardless

File: src/librustc_target/spec/apple_base.rs [hunk 7]
```diff
@@ -51,3 +51,63 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+            "iphoneos" if sdk_root.contains("iPhoneSimulator.platform")
+                || sdk_root.contains("MacOSX.platform") => actual_sdk_path,
+            "iphonesimulator" if sdk_root.contains("iPhoneOS.platform")
+                || sdk_root.contains("MacOSX.platform") => actual_sdk_path,
+            "macosx" | "macosx10.15" if sdk_root.contains("iPhoneOS.platform")
+                || sdk_root.contains("iPhoneSimulator.platform") => actual_sdk_path,
+            _ => sdk_root,
+        }))
+    }
+    Ok(None)
```
Comment (alexcrichton) [inline src/librustc_target/spec/apple_base.rs]: I think this is changing the behavior from before where now the sdkroot is only set if `SDKROOT` is set, but previously it was inferred automatically if the env var wasn't set?

File: src/librustc_target/spec/x86_64_apple_darwin.rs [hunk 8]
```diff
@@ -6,6 +6,12 @@ pub fn target() -> TargetResult {
     base.max_atomic_width = Some(128); // core2 support cmpxchg16b
     base.eliminate_frame_pointer = false;
     base.pre_link_args.insert(LinkerFlavor::Gcc, vec!["-m64".to_string()]);
+    if let Some(sysroot) = super::apple_base::sysroot("macosx")? {
+        base.pre_link_args.insert(
+            LinkerFlavor::Gcc,
+            vec!["-isysroot".to_string(), sysroot.clone(), "-Wl,-syslibroot".to_string(), sysroot],
```
Comment (alexcrichton) [inline src/librustc_target/spec/x86_64_apple_darwin.rs]: Do you know what the expected impact will be from setting these flags? I'm not sure if this is likely to cause issues or perhaps cause misconfigurations on some systems.

File: src/librustc_target/spec/apple_base.rs [hunk 9]
```diff
@@ -51,3 +51,63 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+        .arg("--show-sdk-path")
+        .arg("-sdk")
+        .arg(sdk_name)
+        .output()
+        .and_then(|output| {
+            if output.status.success() {
+                Ok(String::from_utf8(output.stdout).unwrap())
+            } else {
+                let error = String::from_utf8(output.stderr);
+                let error = format!("process exit with error: {}", error.unwrap());
```
Comment (alexcrichton) [inline src/librustc_target/spec/apple_base.rs]: I see that this was just copied from before, but could this `.unwrap` and the one above be avoided by using `from_utf8_lossy` instead?

File: src/librustc_target/spec/apple_base.rs [hunk 10]
```diff
@@ -51,3 +51,63 @@ pub fn macos_llvm_target(arch: &str) -> String {
...
+        let sdk_root_p = Path::new(&sdk_root);
+        // Ignore `SDKROOT` if it's not a valid path.
+        if !sdk_root_p.is_absolute() || sdk_root_p == Path::new("/") || !sdk_root_p.exists() {
+            return Ok(Some(actual_sdk_path));
+        }
+        // Ignore `SDKROOT` if it's clearly set for the wrong platform, which may occur when we're
+        // compiling a custom build script while targeting iOS for example.
+        return Ok(Some(match sdk {
+            "iphoneos" if sdk_root.contains("iPhoneSimulator.platform")
+                || sdk_root.contains("MacOSX.platform") => actual_sdk_path,
```
Comment (alexcrichton) [inline src/librustc_target/spec/apple_base.rs]: I'm sort of surprised by this logic, I'd sort of suspect something along the lines of:

* If `SDKROOT` is set, only return it if the actual compiler target looks like it's part of `SDKROOT`
* Otherwise, for ios/etc platforms, use `xcrun` to auto-find a root.
* Otherwise if SDKROOT is set and the target is `{x86_64,i686}-apple-darwin`, ensure that `SDKROOT` is removed from linker commands
* Otherwise, return `None`.

I think this would assuage my concern below about passing `SDKROOT` arguments to all rustc invocations for x86_64/i686 by default. That seems susceptible to breakage I fear. Additionally `xcrun` isn't executed if `SDKROOT` is configured, and for cross compilations we'd scrub `SDKROOT` from the environment when executing the linker for the host.

**Comment by aleksijuvani** [comment]
Thank you for bearing with me as I rework this. I've gotten rid of the `-isysroot` flag on `*-apple-darwin`, and we're now only modifying the linker environment variables if they are set incorrectly. This seems significantly better to me and should address your concerns.

The reason I went with `-isysroot` in the first place was that I figured it was better always explicitly to set the sysroot, but you're right, I'm not sure what the full impact of this would've been. It ought to be better not to touch it when we don't need to. It was also unclear to me how to solve this with just environment variables, because this did not seem to fully solve the problem, but it turns out there was a missing piece—we also need to unset `IPHONEOS_DEPLOYMENT_TARGET`.

File: src/librustc_target/spec/apple_base.rs [hunk 11]
```diff
@@ -51,3 +51,19 @@ pub fn macos_llvm_target(arch: &str) -> String {
     let (major, minor) = macos_deployment_target();
     format!("{}-apple-macosx{}.{}.0", arch, major, minor)
 }
+
+pub fn macos_link_env() -> Vec<(String, String)> {
```
Comment (alexcrichton) [inline src/librustc_target/spec/apple_base.rs]: This seems a bit of an odd interface since it actually only returns env vars which should be cleared out, not env vars which should be set. Do we know what the various tools will behave right when set to blank values which effectively disables them? The alternative would be to extend `link_env` with the ability to delete env vars as well (e.g. `env_remove`).

Additionally, it seems like this would also want to encompass the ios targets perhaps? For example if you set `SDKROOT` for osx or `MACOSX_DEPLOYMENT_TARGET`, should those values be automatically cleared out for ios compliation in addition to macos compilation?

Comment (aleksijuvani) [reply src/librustc_target/spec/apple_base.rs]: > This seems a bit of an odd interface since it actually only returns env vars which should be cleared out, not env vars which should be set. Do we know what the various tools will behave right when set to blank values which effectively disables them? The alternative would be to extend `link_env` with the ability to delete env vars as well (e.g. `env_remove`).

If the variable is set to an empty string, the linker behaves as if the environment variable wasn't set. We can rework this to remove environment variables instead if that feels better.

> Additionally, it seems like this would also want to encompass the ios targets perhaps? For example if you set `SDKROOT` for osx or `MACOSX_DEPLOYMENT_TARGET`, should those values be automatically cleared out for ios compliation in addition to macos compilation?

Yes, this makes sense. We should clear `SDKROOT` if it's set to the wrong platform when targeting iOS. The value of `MACOSX_DEPLOYMENT_TARGET` doesn't appear to be meaningful in the same way that `IPHONEOS_DEPLOYMENT_TARGET` is (i.e. it doesn't appear to be used by the linker to infer the target platform), so perhaps we don't need to clear this one.
