### PR TITLE
Make rust-intrinsic ABI unwindable

### LINKED ISSUE #2839: Miri reports UB in the `core` lib
Started getting this error with recent miri builds:

```
test arrayvec::traits::index::testing::test_range_index_mut_panics - should panic ... error: Undefined Behavior: unwinding past a stack frame that does not allow unwinding
  --> /home/runner/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:70:9
   |
70 |         const_eval_select((index, len), slice_end_index_len_fail_ct, slice_end_index_len_fail_rt)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unwinding past a stack frame that does not allow unwinding
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `core::slice::index::slice_end_index_len_fail` at /home/runner/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:70:9: 70:98
   = note: inside `<std::ops::Range<usize> as std::slice::SliceIndex<[u64]>>::index_mut` at /home/runner/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:422:13: 422:60
   = note: inside `core::slice::index::<impl std::ops::IndexMut<std::ops::Range<usize>> for [u64]>::index_mut` at /home/runner/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:31:9: **31:30**
```

Is there a real UB in the `core` lib?

### LINKED ISSUE #104451: Unwinding intrinsics use non-unwinding ABI
There are intrinsics like `assert_inhabited`, which can unwind, but use `rust-intrinsic` ABI that never unwinds:

https://github.com/rust-lang/rust/blob/6d651a295e0e0c331153288b10b78344a4ede20b/compiler/rustc_middle/src/ty/layout.rs#L1091-L1093

An example demonstrating the issue. The argument passed to function `f` is never dropped, when `assert_inhabited` unwinds:

```rust
#![feature(core_intrinsics)]
#![feature(never_type)]

struct NoisyDrop(&'static str);

impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

pub fn f<A, B>(_: A) {
    core::intrinsics::assert_inhabited::<B>()
}

fn main() {
    let _a = NoisyDrop("1");
    f::<NoisyDrop, !>(NoisyDrop("2"));
}

$ rustc a.rs && ./a
thread 'main' panicked at 'attempted to instantiate uninhabited type `!`', a.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
1
```

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #104451, fix https://github.com/rust-lang/miri/issues/2839

r? @RalfJung

### CODE REVIEW

File: library/core/src/intrinsics.rs [hunk 1]
```diff
@@ -2063,18 +2276,22 @@ extern "rust-intrinsic" {
     /// takes the data pointer and a pointer to the target-specific exception
     /// object that was caught. For more information see the compiler's
     /// source as well as std's catch implementation.
+    #[rustc_nounwind]
     pub fn r#try(try_fn: fn(*mut u8), data: *mut u8, catch_fn: fn(*mut u8, *mut u8)) -> i32;
```
Comment (Amanieu) [inline library/core/src/intrinsics.rs:2280]: Actually the `catch_fn` passed to `try` could unwind, which will unwind out of the `try` intrinsic. However this is a somewhat theoretical concern since our current implementation doesn't call any functions that unwind in the catch callback.

**Comment by RalfJung** [comment]
Sorry, I'm too busy currently to be primary reviewer... @JakobDegen @wesleywiser ?

File: library/core/src/intrinsics.rs (hunk 1 above)
Comment (nbdd0121) [reply library/core/src/intrinsics.rs:2280]: This is an attribute on the signature, which correctly states that we cannot unwind out from the try intrinsic.

Comment (Amanieu) [reply library/core/src/intrinsics.rs:2280]: If `catch_fn` unwinds, then the exception will also unwind out of the `try` intrinsic. Only unwinds from `try_fn` are caught.

File: tests/mir-opt/issue_104451.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
+#![feature(core_intrinsics)]
```
[the remark this answers is not in the document]
Comment (JakobDegen) [reply tests/mir-opt/issue_104451.rs:3]: And please also describe the topic in two words in the name of the test file. `issue_NNNNN.rs` names are a massive anti-pattern
