### PR TITLE
Fix linker detection for linker (drivers) with a version postfix (e.g. clang-12 instead of clang)

### LINKED ISSUE #106454: Linking with clang-XX fails
I tried this code:

main.rs:
```rust
#![no_std]
#![no_main]
use core::panic::PanicInfo;

fn main() {
    loop {}
}

#[panic_handler]
pub fn lib_panic(_: &PanicInfo) -> ! {
    loop {}
}
```

compilation without specifying a linker works (uses rust-lld):

```bash
cargo +nightly rustc --target=aarch64-unknown-none -- -Clink-arg=-nostdlib
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
```

compilation while specifying clang as a linker-driver works:

```bash
CARGO_TARGET_AARCH64_UNKNOWN_NONE_LINKER=/usr/bin/clang cargo +nightly rustc --target=aarch64-unknown-none -- -Clink-arg=--target=aarch64-linux-gnu -Clink-arg=-fuse-ld=lld -Clink-arg=-nostdlib
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
```

linking with `clang-13` (or any other `clang-xx` version) fails:
```bash
$ CARGO_TARGET_AARCH64_UNKNOWN_NONE_LINKER=/usr/bin/clang-13 cargo +nightly rustc --target=aarch64-unknown-none -- -Clink-arg=--target=aarch64-linux-gnu -Clink-arg=-fuse-ld=lld -Clink-arg=-nostdlib

error: linking with `/usr/bin/clang-13` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/jschwender/.local/bin:/home/jschwender/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/remote-cli:/home/jschwender/.local/bin:/home/jschwender/.local/bin:/home/jschwender/.local/bin:/home/jschwender/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jschwender/.dotnet/tools" VSLANG="1033" "/usr/bin/clang-13" "-flavor" "gnu" "/tmp/rustc2MlvQb/symbols.o" "/home/jschwender/xxx/test_linker/target/aarch64-unknown-none/debug/deps/test_linker-d064d105ad8c7d65.364uq591xu04qgaj.rcgu.o" "--as-needed" "-L" "/home/jschwender/xxx/test_linker/target/aarch64-unknown-none/debug/deps" "-L" "/home/jschwender/xxx/test_linker/target/debug/deps" "-L" "/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none/lib" "-Bstatic" "/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none/lib/librustc_std_workspace_core-f455852cb746dc8f.rlib" "/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none/lib/libcore-ca53c4fff67da7f4.rlib" "/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none/lib/libcompiler_builtins-bf82cb7204be09eb.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "/home/jschwender/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none/lib" "-o" "/home/jschwender/xxx/test_linker/target/aarch64-unknown-none/debug/deps/test_linker-d064d105ad8c7d65" "--gc-sections" "--target=aarch64-linux-gnu" "-fuse-ld=lld" "-nostdlib"
  = note: clang: error: unsupported option '--as-needed'
          clang: error: unsupported option '--eh-frame-hdr'
          clang: error: unsupported option '--gc-sections'
          clang: error: unknown argument: '-flavor'
          clang: error: unknown argument: '-znoexecstack'
          clang: error: no such file or directory: 'gnu'
          

warning: `test_linker` (bin "test_linker") generated 1 warning
error: could not compile `test_linker` due to previous error; 1 warning emitted
```
I expected to see this happen: If linking with `clang` works, linking with `clang-13` or `clang-14` etc. should also work.

Instead, this happened: Linking failed with `clang-13`. It looks like the detection of the linker failed and `-Wl,` was not added in some flags rust added.

### Meta

Rust 1.65 and latest nigthly

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (c7572670a 2023-01-03)
binary: rustc
commit-hash: c7572670a1302f5c7e245d069200e22da9df0316
commit-date: 2023-01-03
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### PR DESCRIPTION
**Pull request by jschwe**
Linker (drivers) such as clang / gcc or lld often have a version postfix matching the regex "-\d+$".
Previously, linker detection did not account for the possible version postfix and the fallback value was used, which can cause linker errors due to wrong arguments.
Also remove the check for `-clang`, since there are no architecture specific variants of clang (to my knowledge).

Fixes #106454

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -1231,13 +1231,13 @@ pub fn linker_and_flavor(sess: &Session) -> (PathBuf, LinkerFlavor) {
                     sess.emit_fatal(errors::LinkerFileStem);
                 });
 
+                // Find and strip any version postfix (e.g. `-12` in `clang-12`)
+                let version_postfix = Regex::new(r"-\d+$").unwrap();
```
Comment (oli-obk) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1235]: If we're using a regex anyway, I'd prefer to have a regex for `^clang(-\d+)?$` and replace `stem == "clang"` with a regex match.

Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1235]: It's not just clang that can have a version postfix though. I also have `gcc-xx` and `lld-xx` on my system for example.

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1235]: I think we can avoid regexes here and use `"clang" || startwith("clang-") || endswith("-clang")` (and same for gcc), because if it says clang then it's probably clang regardless of digits.

Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1235]: For gcc we would have to add `contains("-gcc-")` in addition to startswith and endswith or directly match on `contains("gcc") to also catch variants like `aarch64-linux-gnu-gcc-11` without a regex. If that is the preferred way, then I can adjust the PR.

Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1235]: I think it may be better to use the regex after all. `stem.starts_with("lld-")` will not only match for `lld-12` but also for `lld-link`. Of course if we match for `lld-link` first and the for `stem.starts_with("lld-")` it will work fine, but in my opinion this would be much more fragile than using the regex to check for digits at the end.

Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: I pushed a commit which does not use regex and instead uses `starts_with` as suggested. For `lld` it additionally checks if the characters after `lld-` are digits in order to not match against `lld-link`. The CI failure is because I used `is_some_and`. Should we proceed with this approach or roll-back to the regex approach?

Comment (oli-obk) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: I have no strong opinion.

**Comment by jschwe** [comment]
Would it make sense to add detection for `g++` and `clang++`  (which should be treated the same as gcc/clang) in this PR, or should that be a seperate PR?

**Comment by petrochenkov** [comment]
@jschwe 
>Would it make sense to add detection for `g++` and `clang++`  (which should be treated the same as gcc/clang) in this PR, or should that be a seperate PR?

Yeah, these can also be added.
This stuff is not *strictly* necessary because `-C linker-flavor` can be added explicitly if it's not inferred correctly, so not everything is added, but adding obvious cases like `g++` or `clang++` should be fine.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -1231,25 +1231,38 @@ pub fn linker_and_flavor(sess: &Session) -> (PathBuf, LinkerFlavor) {
...
+                } else if stem == "lld-link" || stem.starts_with("lld-link-") {
                     LinkerFlavor::Msvc(Lld::Yes)
-                } else if stem == "lld" || stem == "rust-lld" {
+                } else if stem == "lld"
+                    || stem
+                        .strip_prefix("lld-")
+                        .filter(|x| x.chars().all(char::is_numeric))
+                        .is_some()
+                    || stem == "rust-lld"
+                {
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1265]: Did you actually encounter the versioned variants of lld in practice?

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1265]: FWIW, lld's own flavor detection logic can be found in https://github.com/llvm/llvm-project/blob/main/lld/tools/lld/lld.cpp#L110-L122

**Comment by jschwe** [comment]
> This stuff is not strictly necessary because -C linker-flavor can be added explicitly if it's not inferred correctly

This requires using either `RUSTFLAGS` (or one of the other ways to modify the rustflags for the crate and ALL dependencies) or `cargo rustc` right? I.e. there is no way to set `-C linker-flavor` for `cargo test` without also setting the flag for all dependencies (where it might not be wanted).

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1265]: > Did you actually encounter the versioned variants of lld in practice?

Yes, e.g. on ubuntu lld with the version postfix is part of the [llvm-toolchain-xx](https://packages.ubuntu.com/source/jammy/llvm-toolchain-12) package. Since different people on our team are using different versions of ubuntu or other distributions, we generally prefer using tools with an explicit version postfix (in CI) to make it clear which version of a tool is known to be working.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 1 above)
Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: >  because if it says clang then it's probably clang regardless of digits.

Actually, this is problematic because [`clang-cl`](https://clang.llvm.org/docs/UsersManual.html#clang-cl) exists which mimics the `cli` interface of `cl.exe` and is thus definitely not gnu.

Comment (petrochenkov) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: We don't support using `clang-cl` as a linker, so specifying it in `-Clinker` won't result in anything good regardless of whether the guessing in `fn linker_and_flavor` is successful or not.

(If we ever support it then placing `clang-cl` before `clang` in the if-else chain will solve the problem trivially.)

Comment (jschwe) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Thanks, that's good to know! Does the same also apply for `cl.exe`, i.e. linking for MSVC is only supported via `link` and `lld-link`?

**Comment by jschwe** [comment]
I pushed a commit which strips the possible version postfix, but without using a regex this time. This makes the matching a bit nicer.

**Comment by petrochenkov** [comment]
Ok, let's just land this as is.
r=me after squashing commits.
@rustbot author

**Comment by jschwe** [comment]
Rebased, squashed and adjusted the commit message.

 @rustbot label -S-waiting-on-author +S-waiting-on-review
