### PR TITLE
rustc_session: allow overriding lint level of individual lints from a group

### LINKED ISSUE #4091: -A should override -W when it appears later on the command line
When more than one -A, -D, or -W option in a clippy invocation refers to the same lint, either directly or indirectly, whichever one came last on the command line should win.  The most important reason for this is so you can enable a category of warnings that's off by default, but then turn some of them back off again.  For example, suppose `src/demo.rs` is this:

```rust
pub fn demo() -> &'static str {
    "παράδειγμα"
}
```

then this invocation should _not_ complain about the non-ASCII characters in the string literal, but currently it does:

```
$ cargo clippy -- -W clippy::pedantic -A clippy::non-ascii-literal
warning: literal non-ASCII character detected
 --> src/demo.rs:2:5
  |
2 |     "παράδειγμα"
  |     ^^^^^^^^^^^^
  |
  = note: `-W clippy::non-ascii-literal` implied by `-W clippy::pedantic`
...
```

One might also want to be able to do `-D warnings -A clippy::something_specific` or `-W clippy::all -D clippy::particular_bad_thing`.

Version information:

```
$ cargo clippy -V
clippy 0.0.212 (726176e 2019-04-18)
```

### LINKED ISSUE #4778: -A --allow should take precedence over -D --deny in CLI
I have a weird issue, where I cannot disable a single lint via command line.

Running the following
```bash
cargo +beta clippy --all -- -D clippy::pedantic -D warnings \
	                    -A clippy::must_use_candidate
```
still results in lint being applied:
```
error: this method could have a `#[must_use]` attribute
  --> crates/tracerr/src/trace.rs:50:5
   |
50 |     fn deref(&self) -> &Vec<Frame> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add the attribute: `#[must_use] fn deref(&self) -> &Vec<Frame>`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate
```

Changing the order of the CLI arguments doesn't affect anything.

While disabling lint via `!#[allow(clippy::must_use_candidate)]` attribute in crate's root works OK, as expected.

I suggest that things listed in `allow` (no matter where) as a _white list_ should take precedence over `deny` as a _black list_.

```bash
❯ cargo +beta clippy -- --version
clippy 0.0.212 (c8e3cfbd 2019-10-28)
```

### LINKED ISSUE #58211: Allowing a lint in a deny'd group via cli flags
Hello.

So at first I thought this was a Clippy issue as can be seen here: https://github.com/rust-lang/rust-clippy/issues/3745.

Turns out this is a RustC issue. So the problem is, that we have a lot of smaller projects that are not in a workspace but still want a unified list of lints that are denied or allowed. Adding this list to every `lib.rs` or `main.rs` is not viable as this would require constant updating of all lint lists in case we can deny an allowed lint that is forbidden in a group after fixing the cause.

We're using protobuf in one of the projects and this allows me to test this bug with
`RUSTFLAGS="--deny rust-2018-idioms --allow elided-lifetimes-in-paths" cargo check`. The anonymous lifetime lint still pops up even though it should be allowed.

Having
```
#[deny(rust_2018_idioms)]
#[allow(elided_lifetimes_in_paths)]
```
in the `lib.rs`/`main.rs` works as expected.

Is this indeed a bug or expected behaviour?

EDIT: Oh and I nearly forgot, here's my `rustc --version --verbose` output:
```
rustc 1.32.0 (9fda7c223 2019-01-16)
binary: rustc
commit-hash: 9fda7c2237db910e41d6a712e9a2139b352e558b
commit-date: 2019-01-16
host: x86_64-unknown-linux-gnu
release: 1.32.0
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by tobithiel**
Fixes #58211 and fixes rust-lang/rust-clippy#4778 and fixes rust-lang/rust-clippy#4091

Instead of hard-coding the lint level preferences (from lowest to highest precedence: `lint::Allow -> lint::Warn -> lint::Deny -> lint::Forbid`), the position of the argument in the command line gets taken into account.

Examples:
1. Passing `-D unused -A unused-variables` denies everything in the lint group `unused` **except** `unused-variables` which is explicitly allowed.
1. Passing `-A unused-variables -D unused` denies everything in the lint group `unused` **including** `unused-variables` since the allow is specified before the deny (and therefore overridden by the deny).

This matches the behavior that is already being used when specifying `allow`/`deny` in the source code.

### CODE REVIEW

**Comment by matthewjasper** [comment]
cc @rust-lang/compiler for opinions on this change
cc @Mark-Simulacrum for the compiletest changes

**Comment by Mark-Simulacrum** [comment]
compiletest changes look fine to me; I guess since CI is passing we weren't relying on the unused to override custom flags (which is good! :)

I personally think this change also makes sense in general -- I think I've wanted something like it in the past, even. We should make sure that Clippy folks are on board (cc @Manishearth -- do you know who all to ping inside dev tools?)

**Comment by petrochenkov** [comment]
I'm generally for command line options being overridable by later command line options, because the need to set them hierarchically like #58211 describes arise in various contexts.

**Comment by oli-obk** [comment]
cc @rust-lang/wg-diagnostics @rust-lang/clippy

**Comment by Manishearth** [comment]
Clippy is happy with this we've wanted this to work well forever :smile:

**Comment by Mark-Simulacrum** [comment]
Could someone from the compiler team kick off FCP here? Even though no objections have been raised yet, and indeed everyone seems enthusiastically on board, seems like we should do so as a stable API change.

File: src/tools/compiletest/src/runtest.rs [hunk 1]
```diff
@@ -1951,6 +1956,13 @@ impl<'test> TestCx<'test> {
             rustc.arg("-Ctarget-feature=-crt-static");
         }
 
+        match allow_unused {
+            AllowUnused::Yes => {
```
Comment (Centril) [inline src/tools/compiletest/src/runtest.rs]: Use `if let` here.

**Comment by oli-obk** [comment]
This change unifies the behaviour between the command line lint level flags and the in source lint level attributes in the presence of conflicting flags. The last flag is now always the one that makes the decision, overriding previous flags.

@rfcbot merge

**Comment by nikomatsakis** [comment]
Seems reasonable to me, but I would ask that we document it in the rustc book -- @tobithiel can you update https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/command-line-arguments.md to explain this behavior? (And perhaps add suitable note into https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/lints/index.md or elsewhere as you see fit)

**Comment by tobithiel** [comment]
@nikomatsakis I added some examples to the documentation where it seemed to fit well. Let me know if you had other locations in mind as well. I'm not very familiar with the different documentations.

**Comment by nikomatsakis** [comment]
Thanks @tobithiel, that looks great.

**Comment by goffrie** [comment]
ping @Zoxc @estebank @nagisa @pnkfelix in case you missed this :)

**Comment by Mark-Simulacrum** [comment]
@bors r+

Let's merge this in! I've double checked the implementation and it looks good to me. Also tagging as relnotes, though this change will not be observable to most Rust users (as Cargo hides rustc's CLI by default).

**Comment by RalfJung** [comment]
I think this PR caused the regression in https://github.com/rust-lang/rust/issues/70819.
