### PR TITLE
When encountering an Item in a pat context, point at the item def

### LINKED ISSUE #48062: Type mismatch when pattern matching to a unit struct could really use some better diagnostics
I've answered a question like this every day for the past 3 days... https://users.rust-lang.org/t/how-to-create-a-new-option-serde-json-value-value/15466

The problem is with code like this:

```
struct foo;

let foo = 1;
```

Typically the let binding and the struct definition are much more separated, and the struct definition comes from a glob import. The error received is:

```
error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
4 |     let foo = 1;
  |         ^^^ expected integral variable, found struct `main::foo`
  |
  = note: expected type `{integer}`
             found type `main::foo`
```

This error isn't *wrong*, and I'm not even proposing that we remove it. However, in the specific case where the match is on a unit struct, I do think it would be incredibly helpful to add a `help` diagnostic pointing at the span where `foo` was brought into scope, stating that a struct with zero fields named `foo` was imported. E.g.

```
 --> src/main.rs:2:4
  |
2 |     struct foo;
  |     ^^^^^^^^^^ note: A struct named `foo` with zero fields was brought into scope here.
  |
```

I have purposely biased this error message towards `use` vs definition, because I think the overwhelmingly common case is going to be from `use` not definition (though the error is still reasonable when pointing at the definition).

I'd be happy to implement this if it'd be accepted, though I think I'll probably need a bit of help.

### LINKED ISSUE #55631: Handle unit struct with same name as field in pattern destructuring
Given the following code
```
struct foo;
struct Thing { foo: String }

fn example(t: Thing) {
    let Thing { foo } = t;
}
```

generate the following error

```
error[E0530]: let bindings cannot shadow tuple structs
 --> src/lib.rs:5:17
  |
1 | struct foo;
  | ------------- a unit struct `foo` is defined here
...
5 |     let Thing { foo } = t;
  |                 ^^^ cannot be named the same as a unit struct

```
instead of
```
error[E0308]: mismatched types
 --> src/lib.rs:5:17
  |
5 |     let Thing { foo } = t;
  |                 ^^^ expected struct `std::string::String`, found struct `foo`
  |
  = note: expected type `std::string::String`
             found type `foo`
```

### PR DESCRIPTION
**Pull request by estebank**
```
error[E0308]: mismatched types
  --> $DIR/const-in-struct-pat.rs:8:17
   |
LL | struct foo;
   | ----------- `foo` defined here
...
LL |     let Thing { foo } = t;
   |                 ^^^ expected struct `std::string::String`, found struct `foo`
   |
   = note: `foo` is interpreted as a unit struct, not a new binding
help: you can bind the struct field to a different name
   |
LL |     let Thing { foo: other_foo } = t;
   |                 ^^^^^^^^^^^^^^
```
```
error[E0308]: mismatched types
  --> $DIR/const.rs:14:9
   |
LL | const FOO: Foo = Foo{bar: 5};
   | ----------------------------- constant defined here
...
LL |         FOO => {},
   |         ^^^
   |         |
   |         expected `&Foo`, found struct `Foo`
   |         `FOO` is interpreted as a constant, not a new binding
   |         help: use different name to introduce a new binding: `other_foo`
```

Fix #55631, fix #48062, cc #42876.

### CODE REVIEW

File: src/librustc_typeck/check/pat.rs [hunk 1]
```diff
@@ -614,8 +618,40 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+
+        let path = hir::print::to_string(tcx.hir(), |s| s.print_qpath(qpath, false));
+        if let Some(mut e) = self.demand_suptype_diag(pat.span, expected, pat_ty) {
+            if let Some(span) =
+                pat_res.opt_def_id().and_then(|def_id| self.tcx.hir().span_if_local(def_id))
+            {
+                e.span_label(span, &format!("`{}` defined here", path));
+                if segments.len() == 1 {
+                    e.note(&format!(
+                        "`{}` is interpreted as a {}, not a new binding",
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: Would be good to make the logic uniform with `check_match::const_not_var` (and below) to the extent possible.

File: src/librustc_typeck/check/pat.rs [hunk 2]
```diff
@@ -1146,7 +1181,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         } else {
             (tcx.types.err, tcx.types.err)
         };
-        self.check_pat(&inner, inner_ty, def_bm, discrim_span);
+        self.check_pat(&inner, inner_ty, def_bm, discrim_span, None);
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: I'm not yet sold on the use of `None` and `Some(pat)`. For example, I don't see why e.g. `let box bar` or `let &bar` cannot also receive the new enhanced diagnostics. In fact, in what circumstance is `Some(pat)` unambiguously wrong?

On the side, I've been thinking that we could pass a trace to the top level pattern (all the way to `check_top_pat`) + the expected type via a stack-based linked list (which should incur no allocation and thus negligible cost).

File: src/test/ui/issues/issue-33504.stderr [hunk 3]
```diff
@@ -1,8 +1,16 @@
...
    |
+LL | struct Test;
+   | ------------ `Test` defined here
+...
 LL |         let Test = 1;
-   |             ^^^^ expected integer, found struct `Test`
+   |             ^^^^
+   |             |
+   |             expected integer, found struct `Test`
+   |             help: use different name to introduce a new binding: `other_Test`
```
Comment (Centril) [inline src/test/ui/issues/issue-33504.stderr]:
```suggestion
   |             help: use different name to introduce a new binding: `other_test`
```
(See https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/hair/pattern/check_match/fn.const_not_var.html)

File: src/test/ui/suggestions/const-in-struct-pat.rs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+#![allow(non_camel_case_types)]
```
Comment (Centril) [inline src/test/ui/suggestions/const-in-struct-pat.rs]:
```suggestion
#[allow(non_camel_case_types)]
```

**Review by Centril — CHANGES_REQUESTED** [review]
Looks promising, but needs some changes.

Also, I'd like for https://github.com/rust-lang/rust/pull/67730 to land first cause that one will be harder to rebase.

File: src/librustc_typeck/check/pat.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_typeck/check/pat.rs]: That sounds reasonable but I wanted to tackle the struct field case first and see into expanding the uses if parent_oat afterwards.

**Comment by estebank** [comment]
I'm away for a week. I'll incorporate the feedback once I'm back.

File: src/test/ui/rfc-2005-default-binding-mode/const.stderr [hunk 5]
```diff
@@ -1,8 +1,16 @@
...
    |
+LL | const FOO: Foo = Foo{bar: 5};
+   | ----------------------------- `FOO` defined here
+...
 LL |         FOO => {},
-   |         ^^^ expected `&Foo`, found struct `Foo`
+   |         ^^^
+   |         |
+   |         expected `&Foo`, found struct `Foo`
+   |         help: use different name to introduce a new binding: `other_foo`
```
Comment (estebank) [inline src/test/ui/rfc-2005-default-binding-mode/const.stderr]: Should this also suggest `other_foo if other_foo == FOO => {}`?

File: src/librustc_typeck/check/pat.rs [hunk 6]
```diff
@@ -668,14 +681,61 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                e.span_label(
+                    pat_span,
+                    &format!(
+                        "`{}` is interpreted as {} {}, not a new binding",
+                        path,
+                        res.article(),
+                        res.descr(),
+                    ),
+                );
+                if let Some(Pat { kind: hir::PatKind::Struct(..), .. }) = parent_pat {
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]:
```suggestion
                let (msg, sugg) = match parent_pat {
```
extract out the common parts, including `ident.as_str().to_lowercase()`.

File: src/test/ui/rfc-2005-default-binding-mode/const.stderr (hunk 5 above)
Comment (Centril) [reply src/test/ui/rfc-2005-default-binding-mode/const.stderr]: The diff seems to be gone so I don't have the context to answer, but this seems invasive to suggest a guard due to the way pattern type checking is setup, so I'd say no for now.

File: src/librustc_typeck/check/pat.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_typeck/check/pat.rs]: I would prefer to do it now because I think the in-between situation complicates the code, and I suspect not really for a good reason, and also it should be easy to just remove the `Option<_>` layer and unconditionally pass the parent. A few tests might need to be added but it might also already be exercised.

File: src/librustc_typeck/check/pat.rs [hunk 7]
```diff
@@ -65,6 +65,9 @@ struct TopInfo<'tcx> {
     ///              found type `std::result::Result<_, _>`
     /// ```
     span: Option<Span>,
+    /// When the current pattern being evaluated is a subpattern, we pass this borrow to its parent
+    /// for use to differentiate between struct field sub-patterns when suggesting renaming them.
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_typeck/check/pat.rs]: Everywhere where `TopInfo` is passed in would require this argument. I reduced the number of places where it is modified and the output hasn't changed.

File: src/librustc_typeck/check/pat.rs [hunk 8]
```diff
@@ -65,6 +65,8 @@ struct TopInfo<'tcx> {
     ///              found type `std::result::Result<_, _>`
     /// ```
     span: Option<Span>,
+    // This refers to the parent pattern, if any, in the case of a struct field pattern.
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: You changed things so it doesn't just apply to struct patterns, right? So this comment is outdated.

File: src/librustc_typeck/check/pat.rs [hunk 9]
```diff
@@ -143,13 +146,16 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                self.check_pat_path(pat, path_resolution.unwrap(), qpath, expected, ti.parent_pat)
             }
             PatKind::Struct(ref qpath, fields, etc) => {
                 self.check_pat_struct(pat, qpath, fields, etc, expected, def_bm, ti)
             }
             PatKind::Or(pats) => {
+                let parent_pat = &pat;
                 for pat in pats {
+                    let mut ti = ti;
+                    ti.parent_pat = Some(parent_pat);
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: Nit / general note: I think it would be slightly more readable to use FRU instead, `TopInfo { parent_pat: Some(&pat), ..ti }` (with a binding, or not, if it fits in the same line as the `.check_pat`).

**Review by Centril — COMMENTED** [review]
r=me with these comments addressed

File: src/librustc_typeck/check/pat.rs [hunk 10]
```diff
@@ -670,14 +679,57 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        &self,
+        mut e: DiagnosticBuilder<'_>,
+        pat_span: Span,
+        res: Res,
+        pat_res: Res,
+        qpath: &hir::QPath<'_>,
+        segments: &'b [hir::PathSegment<'b>],
+        parent_pat: Option<&Pat<'_>>,
+    ) {
+        let path = hir::print::to_string(self.tcx.hir(), |s| s.print_qpath(qpath, false));
```
Comment (Centril) [inline src/librustc_typeck/check/pat.rs]: btw, looking at this some more, could we get a snippet span instead of using HIR pretty? I would like to remove the HIR pretty printer soon-ish.

**Comment by Centril** [comment]
Ping @estebank :)

**Comment by estebank** [comment]
Rebased and addressed all coments, I believe.

**Comment by Centril** [comment]
Excellent! I'll follow up with a PR on my own to polish a bit, but this is great.

@bors r+
