### PR TITLE
rustbuild: avoid trying to inversely cross-compile for build triple from host triples

### LINKED ISSUE #76333: 1.47 beta cross-compiling broken: tries to run the reverse cross-compile
config.toml:

~~~~
[..]
build = "x86_64-unknown-linux-gnu"
host = ["armv5te-unknown-linux-gnueabi"]
target = ["armv5te-unknown-linux-gnueabi"]
[..]
~~~~

build log tail:

~~~~
RUST_BACKTRACE=1 python3 src/bootstrap/bootstrap.py build --config debian/config.toml -vvv --on-fail env
[..]
Dirty - /<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1-std
  c Sysroot { compiler: Compiler { stage: 1, host: TargetSelection { triple: "armv5te-unknown-linux-gnueabi", file: None } } }
Building stage1 std artifacts (armv5te-unknown-linux-gnueabi -> x86_64-unknown-linux-gnu)
running: "/usr/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "4" "-v" "-v" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "/<<PKGBUILDDIR>>/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
warning: config profiles require the `-Z config-profile` command-line option (found profile `release` in environment variable `CARGO_PROFILE_RELEASE`)
warning: Patch `backtrace v0.3.50 (/<<PKGBUILDDIR>>/library/backtrace)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
error: process didn't exit successfully: `/<<PKGBUILDDIR>>/build/bootstrap/debug/rustc -vV` (exit code: 101)
--- stderr
rustc command: "LD_LIBRARY_PATH"="/<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1/lib" "/<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1/bin/rustc" "-vV" "-Wrust_2018_idioms" "-Wunused_lifetimes" "-Dwarnings" "-Clinker=arm-linux-gnueabi-gcc" "--remap-path-prefix" "/<<PKGBUILDDIR>>=/usr/src/rustc-1.47.0" "-Z" "force-unstable-if-unmarked"
sysroot: "/<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1"
libdir: "/<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1/lib"
thread 'main' panicked at '
Failed to run:
"/<<PKGBUILDDIR>>/build/armv5te-unknown-linux-gnueabi/stage1/bin/rustc" "-vV" "-Wrust_2018_idioms" "-Wunused_lifetimes" "-Dwarnings" "-Clinker=arm-linux-gnueabi-gcc" "--remap-path-prefix" "/<<PKGBUILDDIR>>=/usr/src/rustc-1.47.0" "-Z" "force-unstable-if-unmarked"
-------------: Os { code: 8, kind: Other, message: "Exec format error" }', src/bootstrap/bin/rustc.rs:152:22
stack backtrace:
[.. etc ..]
~~~~

That line `Building stage1 std artifacts (armv5te-unknown-linux-gnueabi -> x86_64-unknown-linux-gnu)` does not look like it should be there.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This changes rustbuild's cross compilation logic to better match what users expect,
particularly, avoiding trying to inverse cross-compile for the build triple from host triples.
That is, if build=A, host=B, target=B, we do not want to try and compile for A from B.
Indeed, the only "known to run" triple when cross-compiling is the build triple A.
When testing for a particular target we need to be able to run binaries compiled for
that target though.

The last commit also modifies the default set of host/target triples to avoid producing
needless artifacts for the build triple:

The new behavior is to respect --host and --target when passed as the *only*
configured triples (no triples are implicitly added). The default for --host is
the build triple, and the default for --target is the host triple(s), either
configured or the default build triple.

Fixes #76333

r? @alexcrichton if possible, otherwise we'll need to hunt down a reviewer

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@infinity0 -- would appreciate your thoughts on this change to defaults. I hope that it moves us closer to doing what you expect from a build system :)

**Comment by infinity0** [comment]
Thanks! Yes this sounds great, and hopefully will shorten cross-compile times too.

File: src/bootstrap/builder.rs [hunk 1]
```diff
@@ -87,11 +87,16 @@ pub trait Step: 'static + Clone + Debug + PartialEq + Eq + Hash {
...
 pub struct RunConfig<'a> {
     pub builder: &'a Builder<'a>,
-    pub host: TargetSelection,
     pub target: TargetSelection,
     pub path: PathBuf,
 }
 
+impl RunConfig<'_> {
+    pub fn build_triple(&self) -> TargetSelection {
+        self.builder.build.build
```
Comment (alexcrichton) [inline src/bootstrap/builder.rs:96]: build, build, build, 🔧 🏗️

File: src/bootstrap/builder.rs [hunk 2]
```diff
@@ -178,16 +182,9 @@ impl StepDescription {
...
-                    builder,
-                    path: pathset.path(builder),
-                    host: *host,
-                    target: *target,
-                };
-                (self.make_run)(run);
-            }
+        for target in targets {
+            let run = RunConfig { builder, path: pathset.path(builder), target: *target };
+            (self.make_run)(run);
```
Comment (alexcrichton) [inline src/bootstrap/builder.rs:187]: IIRC this previous logic matches the ancient logic of the makefiles, but I don't think it ever fully made sense. The main thing to worry about here is the impact on all the builders on CI, since some of them may accidentally be relying on the previous behavior. Everything is so specific nowadays though it may be unlikely. In any case, just something to watch out for.

**Review by alexcrichton — APPROVED** [review]
Seems reasonable to me! We've trended over time towards just having one target triple specified in most steps which makes sense to me, and the build triple is just implicit anywhere as what you're actually running rustc for to produce things. It might be worthwhile to take a gander at some of the cross-compiled docker and testing builds though and make sure they're still working as expected.

**Comment by Mark-Simulacrum** [comment]
er, @bors r- r=alexcrichton

**Comment by tmandry** [comment]
@bors retry
Yielding to rollup
