### PR TITLE
Expect pipe symbol after closure parameter list

### LINKED ISSUE #44021: nightly ICE: panicked at 'index out of bounds: the len is 0 but the index is 1', /checkout/src/liballoc/vec.rs:1564:14
The test also causes 1.18 and 1.19 to loop indefinitely.

```bash
$ rustc-nightly --version
rustc 1.21.0-nightly (8c303ed87 2017-08-20)
$ 
$ rustc-nightly tmp.rs
error: expected expression, found `}`
 --> tmp.rs:4:1
  |
4 | } 
  | ^

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (8c303ed87 2017-08-20) running on i686-unknown-linux-gnu

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 1', /checkout/src/liballoc/vec.rs:1564:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ 
$ cat tmp.rs
impl Struct
{ 
  fn static_meth_struct () -> Struct {|} 
} 
$ 
```

### PR DESCRIPTION
**Pull request by tirr-c**
Fixes #44021.

---

Originally, the parser just called `bump` to discard following token after parsing closure parameter list, because it assumes `|` is following. However, the following code breaks the assumption:

```rust
struct MyStruct;
impl MyStruct {
   fn f() {|x, y}
}
```

Here, the parameter list is `x, y` and the following token is `}`. The parser discards `}`, and then we have a curly bracket mismatch.

Indeed, this code has a syntax error. On current nightly, the compiler emits an syntax error, but with incorrect message and span, followed by an ICE.

```
error: expected expression, found `}`
 --> 44021.rs:4:1
  |
4 | }
  | ^

error: internal compiler error: unexpected panic
```

Even worse, on current stable(1.20.0), the compiler falls into an infinite loop.

This pull request fixes this problem. Now the compiler emits correct error message and span, and does not ICE.

```
error: expected one of `:`, `@`, or `|`, found `}`
 --> 44021.rs:3:20
  |
3 |     fn foo() {|x, y}
  |                    ^ expected one of `:`, `@`, or `|` here
```

### CODE REVIEW

**Comment by arielb1** [comment]
Does your patch fix the ICE even if there *is* a curly bracket mismatch:
```Rust
struct MyStruct;
impl MyStruct {
   fn f() {|x, y}
```

**Comment by tirr-c** [comment]
It doesn't ICE. It seems that the ICE was caused by the untracked consuming of `CloseDelim`.

```
error: this file contains an un-closed delimiter
 --> /home/tirr/coding/rust/44021.rs:3:19
  |
3 |    fn f() {|x, y}
  |                   ^
  |
help: did you mean to close this delimiter?
 --> /home/tirr/coding/rust/44021.rs:2:15
  |
2 | impl MyStruct {
  |               ^

error: expected one of `:`, `@`, or `|`, found `}`
 --> /home/tirr/coding/rust/44021.rs:3:17
  |
3 |    fn f() {|x, y}
  |                 ^ expected one of `:`, `@`, or `|` here
```

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -4699,7 +4699,7 @@ impl<'a> Parser<'a> {
                     SeqSep::trailing_allowed(token::Comma),
                     |p| p.parse_fn_block_arg()
                 );
-                self.bump();
+                self.expect(&token::BinOp(token::Or))?;
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser.rs]: Hmm, `token::OrOr` should be possible here as well in theory, e.g. 
```rust
#![allow(unused)]

fn main() {
    let x = |x, y| |a, b| 0; // Legal
    x(1, 2)(3, 4);
}
```
, but `|x, y||a, b| 0` (without space) doesn't parse on stable/beta/nightly already.
Worth fixing as well!

**Comment by petrochenkov** [comment]
r=me unless you want to fix https://github.com/rust-lang/rust/pull/44332#discussion_r137405320

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (tirr-c) [reply src/libsyntax/parse/parser.rs]: I'm trying to fix this. Should I work on this double-closure parsing bug in a new PR?
