### PR TITLE
Emit delayed bug during wfck for stranded opaque

### LINKED ISSUE #235: `find_opaque_ty_constraints_for_rpit` ICE for stranded opaques
- tests/ui/impl-trait/opt-out-bound-not-satisfied.rs
- tests/ui/impl-trait/stranded-opaque.rs
```rust
use std::future::Future;
fn foo() -> impl ?Future<Output = impl Send> {
    //~^ ERROR: bound modifier `?` can only be applied to `Sized`
    //~| ERROR: bound modifier `?` can only be applied to `Sized`
    ()
}
```
results in
```
error: bound modifier `?` can only be applied to `Sized`
 --> src/main.rs:5:18
  |
5 | fn foo() -> impl ?Future<Output = impl Send> {
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs:253:17:
assertion failed: !tcx.next_trait_solver_globally()
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/788da80fcfcef3f34c90def5baa32813e39a1a41/library/core/src/panicking.rs:145:5
   3: find_opaque_ty_constraints_for_rpit
             at /home/lcnr/rust/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs:253:17
   4: type_of_opaque_hir_typeck
             at /home/lcnr/rust/compiler/rustc_hir_analysis/src/collect/type_of.rs:415:13
```

so does
```rust
trait Trait {}
impl Trait for i32 {}

// Since `Assoc` doesn't actually exist, it's "stranded", and won't show up in
// the list of opaques that may be defined by the function. Make sure we don't
// ICE in this case.
fn produce<T>() -> impl Trait<Assoc = impl Trait> {
    //~^ ERROR associated type `Assoc` not found for `Trait`
    //~| ERROR associated type `Assoc` not found for `Trait`
    16
}
```

### PR DESCRIPTION
**Pull request by tiif**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/235

## Problem

The fundamental issue here is ``OpaqueTypeCollector`` operates on ``rustc_middle::Ty``, but ``check_type_wf`` operates on HIR. 

Since [check_type_wf](https://github.com/rust-lang/rust/blob/2f7620a5ccfea7d59d1f500e2a2e59cf1c867a1b/compiler/rustc_hir_analysis/src/check/wfcheck.rs#L2262) operates on HIR, it can see the stranded opaque and tries to infer it's hidden type. But ``OpaqueTypeCollector`` operates on ``rustc_middle::Ty``, so the ``OpaqueTypeCollector`` can no longer see a stranded opaque, hence its hidden type could not be inferred. 

As a result, the tests ICE'ed at https://github.com/rust-lang/rust/blob/34a8c7368c84fc699fc83a8851a02f93fd655931/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs#L253

## Proposed solution

This PR detects stranded opaque types during wf check and emit a delayed bug for it.

## Alternative solution

@BoxyUwU and I had considered rewriting ``OpaqueTypeCollector`` to be a HIR visitor instead of a ``rustc_middle::Ty`` visitor, but we believe a HIR-based ``OpaqueTypeCollector`` will not work and might not worth the cost of rewriting.
  
## Acknowledgement

This PR is a joint effort with @BoxyUwU :3

### CODE REVIEW

File: tests/ui/traits/next-solver/opaques/stranded_opaque.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+trait Trait {}
+impl Trait for i32 {}
+
+fn produce() -> impl Trait<Assoc = impl Trait> {
+    //~^ ERROR associated type `Assoc` not found for `Trait`
+    //~| ERROR associated type `Assoc` not found for `Trait`
+    16
+}
+
```
Comment (BoxyUwU) [inline tests/ui/traits/next-solver/opaques/stranded_opaque.rs:26]: can you add a test case for something like `-> String<impl Trait>` which should also be another way of getting stranded opaques

Comment (tiif) [reply tests/ui/traits/next-solver/opaques/stranded_opaque.rs:26]: okay, done :)

File: tests/ui/traits/next-solver/opaques/stranded_opaque.rs [hunk 2]
```diff
@@ -0,0 +1,33 @@
+//@ compile-flags: -Znext-solver
+
+// Test for https://github.com/rust-lang/trait-system-refactor-initiative/issues/235
+
+// These are cases where an opaque types become "stranded" due to
+// some errors. Make sure we don't ICE in either case.
+
+// Case 1: `impl Send` is stranded
```
Comment (BoxyUwU) [inline tests/ui/traits/next-solver/opaques/stranded_opaque.rs:10]: can u also make equivalent tests for all these cases using a TAIT instead of an RPIT. I don't think they were ICEing but good to test anyway

Comment (tiif) [reply tests/ui/traits/next-solver/opaques/stranded_opaque.rs:10]: I thought of making the outer opaque type of TAIT constrained by having

```rust
type Foo = impl ?Future<Output = impl Send>;

#[define_opaque(Foo)]
fn define_foo() -> Foo {
    ()
}
```

but on second thought, it feels very much like the RPIT test above, so I just removed it. Let me know if you prefer this though.
