### PR TITLE
incr. comp.: Take spans into account for ICH

### LINKED ISSUE #32753: Some data is not hashed by the SVH that ought to be
**New summary:**

I think we've all agreed by now that we will focus on the ICH (incremental compilation hash) and revisit the question of a SVH (stable version hash, used to detect ABI-incompatible changes) at some future date. The "original summary" (below) goes into some of the discussion.

I've thus repurposed this issue to target addressing the shortcomings of the existing hash for the purposes of incremental compilation. The following checklist is derived from [@michaelwoerister's comment](https://github.com/rust-lang/rust/issues/32753#issuecomment-233073399):

- [x] incorporate results of name resolution pass, since name resolution is not tracked
- [ ] incorporate spans, when needed (#33888)
- [x] ignore nested items, since the use of items is tracked independently
    - note that `visit_stmt()` and `visit_decl()` by themselves should not change the hash, since they could just represent a nested item (which we either want to ignore completely or handle in a position independent way).
- [ ] the `CaptureClause` of closures should not be ignored
- [ ] `walk_generics()` in `visit_variant()` and `visit_variant_data()` are redundant; this is already handled by `visit_item()`
- [ ] explicitly hashing the label names in `ExprLoop`, `ExprBreak`, and `ExprAgain` is redundant, `visit_name()` is called for those anyway (as already done for `ExprWhile`)

There are also optional refinements:

- [ ] do not hash the actual names of local variables etc, but just map them to unique identifiers or something like that; seems challenging to get something that is both deterministic, however, and also independent from the name itself.

------

**Original summary:**

In https://github.com/rust-lang/rust/pull/32016, I (ab)used the SVH to serve as a hash for the purposes of incremental compilation. This is simply wrong, because the SVH intentionally omits some details that do not affect the ABI, but which very much affect whether code needs to be recompiled (e.g., the value of a constant). This needs to be fixed, but in one of two ways:

- Create an alternative incremental compilation hash (ICH), keeping the existing consumers of the SVH.
- Convert the SVH (in place) into the ICH, and make the existing consumers use that.

At this point, there are really very few users of the SVH:

- Each crate stores the SVH in its metadata, which the compiler then uses to detect transitive mismatches, where you compile crate B with some version of crate A, but you are now compiling C (which uses B) with a distinct version of crate A in scope.
- Debuginfo uses it for some reason or other.
- There is no third use. (I think)

The second use is unnecessary. The first use is interesting. It's unclear how flexible this check is. But if we used the *ICH* for this purpose, it would basically be equivalent to the SVH today (the SVH today *is* looser, as I wrote in the beginning, but *effectively* any change will cause the SVH to change, with very few exceptions). 

Moreover, I claim that even if, someday, we wanted to modify the check to be true ABI compatibility, we probably wouldn't want a single SVH hash. We'd probably want each function hash to include information about the way the argument types are represented, so that we can detect mismatches on a fine-grained level, rather than just "some fn, which you may not even call, changed". But I'm not sure.

One problem with using the ICH everywhere, though, is that we must be careful about endianness. We'd prefer if cross-compiling did not affect the ICH.

I guess I've wasted more time writing this paragraph than it really merits. End of the day, the choice is:

- Keep the SVH around, weird as it is.
- Kill the SVH and just ICH, which should be stricter.

cc @michaelwoerister

### LINKED ISSUE #33888: Incremental compilation: Be smart about hashing spans
The way the code-map is currently set up, all source files of a crate and its dependencies are layout into one big "address space", e.g:
```
    a.rs         b.rs           c.rs
|----------|--------------|--------------|
0         100            220            340 bytes
```
That means that adding a byte to `a.rs` will change all addresses in `b.rs` and `c.rs`. Consequently, were we to incorporate the verbatim `BytePos` values in the `Spans` contained in the AST, small changes would cause recompilations of seemingly unrelated files.

Thus, we need to find a more stable way of hashing spans, like expanding them to `file-name:line:col` (or not hash them at all, if we don't compile with debuginfo). 

cc @nikomatsakis

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes the ICH (incr. comp. hash) take spans into account when debuginfo is enabled.

A side-effect of this is that the SVH (which is based on the ICHs of all items in the crate) becomes sensitive to the tiniest change in a code base if debuginfo is enabled. Since we are not trying to model ABI compatibility via the SVH anymore (this is done via the crate disambiguator now), this should be not be a problem.

Fixes #33888.
Fixes #32753.

### CODE REVIEW

File: src/librustc_incremental/calculate_svh/svh_visitor.rs [hunk 1]
```diff
@@ -13,43 +13,172 @@
...
+}
+
+struct CachedCodemapView<'tcx> {
+    codemap: &'tcx CodeMap,
+    // Format: (line number, line-start, line_end, file)
+    line_cache: [(usize, BytePos, BytePos, Rc<FileMap>); 4],
+    eviction_index: usize,
+}
+
+impl<'tcx> CachedCodemapView<'tcx> {
```
Comment (michaelwoerister) [inline src/librustc_incremental/calculate_svh/svh_visitor.rs]: TODO: Rename this to `CachingCodemapView`.

File: src/librustc_incremental/calculate_svh/svh_visitor.rs [hunk 2]
```diff
@@ -13,43 +13,172 @@
...
+        let (file1, line1, col1) = self.codemap.byte_pos_to_line_and_col(span.lo);
+        let (file2, line2, col2) = self.codemap.byte_pos_to_line_and_col(span_hi);
+
+        let expansion_kind = match span.expn_id {
+            NO_EXPANSION => SawSpanExpnKind::NoExpansion,
+            COMMAND_LINE_EXPN => SawSpanExpnKind::CommandLine,
+            _ => SawSpanExpnKind::SomeExpansion,
+        };
+
+        expansion_kind.hash(self.st);
```
Comment (michaelwoerister) [inline src/librustc_incremental/calculate_svh/svh_visitor.rs]: TODO: Remove this line. The expansion kind is already hashed later as field of `SawSpan`.

File: src/librustc_incremental/calculate_svh/svh_visitor.rs [hunk 3]
```diff
@@ -13,43 +13,172 @@
...
+            }
+        }
+
+        // No cache hit ...
+        let file_index = self.codemap.lookup_filemap_idx(pos);
+        let file = self.codemap.files.borrow()[file_index].clone();
+        let line_index = file.lookup_line(pos).unwrap();
+        let (line_start, line_end) = file.line_bounds(line_index);
+
+        // Just overwrite some cache entry. If we got this for, all of them
```
Comment (michaelwoerister) [inline src/librustc_incremental/calculate_svh/svh_visitor.rs]: "this for" -> "this far"

**Comment by michaelwoerister** [comment]
This is ready for review now.

File: src/librustc_incremental/calculate_svh/svh_visitor.rs [hunk 4]
```diff
@@ -17,24 +17,99 @@ use self::SawExprComponent::*;
...
+                                                      "rustc_clean",
+                                                      "rustc_dirty"];
+
 pub struct StrictVersionHashVisitor<'a, 'hash: 'a, 'tcx: 'hash> {
     pub tcx: TyCtxt<'hash, 'tcx, 'tcx>,
     pub st: &'a mut SipHasher,
     // collect a deterministic hash of def-ids that we have seen
     def_path_hashes: &'a mut DefPathHashes<'hash, 'tcx>,
     hash_spans: bool,
+    codemap: CachedCodemapView<'tcx>,
```
Comment (nikomatsakis) [inline src/librustc_incremental/calculate_svh/svh_visitor.rs]: Nit: I think it would be better if this lived one level up, next to the `DefPathHashes`, so that we can cache across items.

File: src/librustc_incremental/calculate_svh/svh_visitor.rs [hunk 5]
```diff
@@ -17,24 +17,99 @@ use self::SawExprComponent::*;
...
+            if pos >= file.start_pos && pos < file.end_pos {
+                let line_index = file.lookup_line(pos).unwrap();
+                let (line_start, line_end) = file.line_bounds(line_index);
+
+                // Update the cache entry in place
+                *line = line_index + 1;
+                *start = line_start;
+                *end = line_end;
+
+                return (file.clone(), line_index + 1, pos - line_start);
```
Comment (nikomatsakis) [inline src/librustc_incremental/calculate_svh/svh_visitor.rs]: I think this strategy will lead to you re-using the same cache line over and over (e.g., if you have just 1 file, you'll load some data into slot 0, then update slot 0 to be the next line and the next...). I'm not sure this is optimal. Probably in many use cases you never use a line once we've moved past it, but macro expansion changes that calculus some also.

**Comment by nikomatsakis** [comment]
r=me modulo comments about span hashing

**Comment by michaelwoerister** [comment]
@bors r=nikomatsakis

rebased.

**Comment by michaelwoerister** [comment]
@bors r-

Want to take a look at the failed test on travis first...

**Comment by michaelwoerister** [comment]
@bors retry

Couldn't reproduce the test failure.

**Comment by michaelwoerister** [comment]
Can reproduce, will investigate...

**Comment by nikomatsakis** [comment]
r=me on the last commit
