### PR TITLE
Fix unused_parens issue when cast is followed LT

### LINKED ISSUE #117142: suggestion in `unused_parens` diagnostic when cast is followed by less-than produces broken code
### Code

```Rust
fn main() {
    let a: i32 = 1;
    let b: i64 = 1;
    if b - a as (i64) < 0 {
        println!(":D");
    }
}
```

### Current output

```Shell
warning: unnecessary parentheses around type
 --> src/main.rs:4:17
  |
4 |     if b - a as (i64) < 0 {
  |                 ^   ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
4 -     if b - a as (i64) < 0 {
4 +     if b - a as i64 < 0 {
  |

warning: `playground` (bin "playground") generated 1 warning (run `cargo fix --bin "playground"` to apply 1 suggestion)
```

### Desired output

```Shell
--no output--
```

### Rationale and extra context

The code uses a cast followed by a less-than operator. When parens are removed, the compiler errors:
```
error: `<` is interpreted as a start of generic arguments for `i64`, not a comparison
 --> src/main.rs:4:21
  |
4 |     if b - a as i64 < 0 {
  |                     ^ --- interpreted as generic arguments
  |                     |
  |                     not interpreted as comparison
  |
help: try comparing the cast value
  |
4 |     if b - (a as i64) < 0 {
  |            +        +
```

This is not a particularly problematic issue as the suggestion given in this output does not produce any wrong diagnostics, but the help given in the problematic output does cause a compiler error which was not present previously, so I think it's an incorrect warning.

Using parens like in the example does feel like bad style, but it should not generate this particular warning.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #117142 

The original check only checks `a as (i32) < 0`, this fix extends it to handle `b + a as (i32) < 0`.

A better way is maybe we suggest `(a as i32) < 0` instead of suppressing the warning, maybe following PR could improve it.

### CODE REVIEW

File: tests/ui/lint/unused/issue-117142-invalid-remove-parens.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// check-pass
+#![allow(unused_variables)]
```
Comment (petrochenkov) [inline tests/ui/lint/unused/issue-117142-invalid-remove-parens.rs:2]: Isn't this already the default for UI tests (all unused warnings are suppressed)?

File: compiler/rustc_lint/src/unused.rs [hunk 2]
```diff
@@ -1053,17 +1053,31 @@ impl UnusedParens {
             self.emit_unused_delims(cx, value.span, spans, "pattern", keep_space, false);
         }
     }
+
+    fn cast_followed_by_lt(&self, e: &ast::Expr) -> Option<ast::NodeId> {
+        if let ExprKind::Binary(op, lhs, _rhs) = &e.kind
+            && (op.node == ast::BinOpKind::Lt || op.node == ast::BinOpKind::Shl)
+        {
+            let rhs_of_lhs = match &lhs.kind {
+                ExprKind::Binary(_, _, rhs) => rhs,
```
Comment (petrochenkov) [inline compiler/rustc_lint/src/unused.rs:1062]: Ideally, this should probably be a recursion, to cover cases like `a + b * c as (u8) < 10` and further.

Comment (chenyukang) [reply compiler/rustc_lint/src/unused.rs:1062]: yeah, fixed and add a test case.
