### PR TITLE
Don't inline tainted MIR bodies

### LINKED ISSUE #122909: ICE: ` Closure arguments are not passed as a tuple`
auto-reduced (treereduce-rust):
````rust
use std::sync::{Arc, Context, Weak};

pub struct WeakOnce<T>();
impl<T> WeakOnce<T> {
    extern "rust-call" fn try_get(&self) -> Option<Arc<T>> {}

    pub fn get(&self) -> Arc<T> {
        self.try_get()
            .unwrap_or_else(|| panic!("Singleton {} not available", std::any::type_name::<T>()))
    }
}


````

original:
````rust
use std::sync::{Arc,Weak,Context};

pub struct WeakOnce<T>(OnceLock<Weak<T>>);
impl<T> WeakOnce<T> {
    pub const fn new() -> Self { WeakOnce(OnceLock::new()) }

    pub fn init(&self, val:T)->Arc<Str> {
        let val = Arc::new(val);
        self.0.set(Arc::downgrade(&val)).unwrap();
        val
    }

    extern "rust-call" fn try_get(&self)->Option<Arc<T>> {
        self.0.get().and_then(Weak::upgrade)
    }

    pub fn get(&self)->Arc<T> {
        self.try_get().unwrap_or_else(|| panic!("Singleton {} not available", std::any::type_name::<T>()))
    }
}

pub(crate) static ONCE: WeakOnce<Context> = WeakOnce::new();
pub struct Context {
    pub x: String,
}

impl Context {
    pub fn init(x: String)->Arc<Self> {
        let ctx = ONCE.init(Context {x});
        std::thread::spawn(|| {
            while Some(ctx) = ONCE.try_get() {

            }
        });
        ctx
    }
}

````

Version information
````
rustc 1.79.0-nightly (b3df0d7e5 2024-03-22)
binary: rustc
commit-hash: b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87
commit-date: 2024-03-22
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zpolymorphize=on -Zinline-mir=yes`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0432]: unresolved import `std::sync::Context`
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:1:22
  |
1 | use std::sync::{Arc, Context, Weak};
  |                      ^^^^^^^ no `Context` in `sync`
  |
  = help: consider importing this struct instead:
          std::task::Context

error[E0658]: rust-call ABI is subject to change
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:5:12
  |
5 |     extern "rust-call" fn try_get(&self) -> Option<Arc<T>> {}
  |            ^^^^^^^^^^^
  |
  = note: see issue #29625 <https://github.com/rust-lang/rust/issues/29625> for more information
  = help: add `#![feature(unboxed_closures)]` to the crate attributes to enable
  = note: this compiler was built on 2024-03-22; consider upgrading it if it is out of date

warning: unused import: `Weak`
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:1:31
  |
1 | use std::sync::{Arc, Context, Weak};
  |                               ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs`

error[E0392]: type parameter `T` is never used
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:3:21
  |
3 | pub struct WeakOnce<T>();
  |                     ^ unused type parameter
  |
  = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`
  = help: if you intended `T` to be a const parameter, use `const T: /* Type */` instead

error: functions with the "rust-call" ABI must take a single non-self tuple argument
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:5:35
  |
5 |     extern "rust-call" fn try_get(&self) -> Option<Arc<T>> {}
  |                                   ^^^^^

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:5:45
  |
5 |     extern "rust-call" fn try_get(&self) -> Option<Arc<T>> {}
  |                           -------           ^^^^^^^^^^^^^^ expected `Option<Arc<T>>`, found `()`
  |                           |
  |                           implicitly returns `()` as its body has no tail or `return` expression
  |
  = note:   expected enum `Option<Arc<T>>`
          found unit type `()`

error: internal compiler error: compiler/rustc_mir_transform/src/inline.rs:255:17: Closure arguments are not passed as a tuple

thread 'rustc' panicked at compiler/rustc_mir_transform/src/inline.rs:255:17:
Box<dyn Any>
stack backtrace:
   0:     0x75bc9bb63fa5 - std::backtrace_rs::backtrace::libunwind::trace::h4515e3e00f57996f
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x75bc9bb63fa5 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e64ac1112175e4e
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x75bc9bb63fa5 - std::sys_common::backtrace::_print_fmt::h182160b5ad873150
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x75bc9bb63fa5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h432843f19f8b2b6d
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x75bc9bbb4feb - core::fmt::rt::Argument::fmt::hb59bbd21accf1885
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/core/src/fmt/rt.rs:142:9
   5:     0x75bc9bbb4feb - core::fmt::write::haf243cf4605e411d
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/core/src/fmt/mod.rs:1153:17
   6:     0x75bc9bb58d3f - std::io::Write::write_fmt::hd8c8c68b4f5b8f11
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/io/mod.rs:1843:15
   7:     0x75bc9bb63d7e - std::sys_common::backtrace::_print::h0ec933d6103e5515
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x75bc9bb63d7e - std::sys_common::backtrace::print::h55136fa64edb86e6
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x75bc9bb669f9 - std::panicking::default_hook::{{closure}}::h28cbeefc01b40f52
  10:     0x75bc9bb66763 - std::panicking::default_hook::h15e904210c67a3ca
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/panicking.rs:292:9
  11:     0x75bc983cb6bf - std[48784e9e46568672]::panicking::update_hook::<alloc[590c7545ac68a568]::boxed::Box<rustc_driver_impl[9e9e6466696ec967]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x75bc9bb67150 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::had664932fcaf7f86
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2029:9
  13:     0x75bc9bb67150 - std::panicking::rust_panic_with_hook::h9f23cc8a1f418825
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/panicking.rs:783:13
  14:     0x75bc983fbaa4 - std[48784e9e46568672]::panicking::begin_panic::<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>::{closure#0}
  15:     0x75bc983f86f6 - std[48784e9e46568672]::sys_common::backtrace::__rust_end_short_backtrace::<std[48784e9e46568672]::panicking::begin_panic<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>::{closure#0}, !>
  16:     0x75bc983f3c06 - std[48784e9e46568672]::panicking::begin_panic::<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>
  17:     0x75bc98404f31 - <rustc_errors[85c3c7ac8d959a53]::diagnostic::BugAbort as rustc_errors[85c3c7ac8d959a53]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x75bc9889754c - rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt::<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}
  19:     0x75bc9887abca - rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_opt::<rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x75bc9887aa4b - rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_context_opt::<rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_opt<rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x75bc96450b50 - rustc_middle[cfd7f582085b2efd]::util::bug::bug_fmt
  22:     0x75bc99f93fad - <rustc_mir_transform[b03574829d5a714c]::inline::Inliner>::try_inlining
  23:     0x75bc99f8bd3a - <rustc_mir_transform[b03574829d5a714c]::inline::Inliner>::process_blocks
  24:     0x75bc99f8758d - <rustc_mir_transform[b03574829d5a714c]::inline::Inline as rustc_middle[cfd7f582085b2efd]::mir::MirPass>::run_pass
  25:     0x75bc99801a0d - rustc_mir_transform[b03574829d5a714c]::pass_manager::run_passes_inner
  26:     0x75bc99f79285 - rustc_mir_transform[b03574829d5a714c]::optimized_mir
  27:     0x75bc99f7845f - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 8usize]>>
  28:     0x75bc999e5059 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::DefIdCache<rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  29:     0x75bc999e479e - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  30:     0x75bc99b3029e - rustc_middle[cfd7f582085b2efd]::query::plumbing::query_get_at::<rustc_query_system[ee3912bf2a9f33a7]::query::caches::DefIdCache<rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x75bc99ca6187 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::unused_generic_params::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 4usize]>>
  32:     0x75bc99ca5959 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::DefaultCache<rustc_middle[cfd7f582085b2efd]::ty::instance::InstanceDef, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  33:     0x75bc99ca5660 - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::unused_generic_params::get_query_non_incr::__rust_end_short_backtrace
  34:     0x75bc99ca1156 - rustc_interface[7ddcde71cf02e108]::passes::analysis
  35:     0x75bc99c9fe51 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>
  36:     0x75bc9a5eb4a5 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::SingleCache<rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  37:     0x75bc9a5eb209 - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x75bc9a4870d9 - rustc_interface[7ddcde71cf02e108]::interface::run_compiler::<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}
  39:     0x75bc9a552399 - std[48784e9e46568672]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_with_globals<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_pool_with_globals<rustc_interface[7ddcde71cf02e108]::interface::run_compiler<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>
  40:     0x75bc9a5521c6 - <<std[48784e9e46568672]::thread::Builder>::spawn_unchecked_<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_with_globals<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_pool_with_globals<rustc_interface[7ddcde71cf02e108]::interface::run_compiler<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#1} as core[b4a1350c838fc0f9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x75bc9bb70919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3e016c41180ed802
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2015:9
  42:     0x75bc9bb70919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf0716ba35a33b0c
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2015:9
  43:     0x75bc9bb70919 - std::sys::pal::unix::thread::Thread::new::thread_start::hd585680968d21553
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys/pal/unix/thread.rs:108:17
  44:     0x75bc9b91055a - <unknown>
  45:     0x75bc9b98da3c - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0-nightly (b3df0d7e5 2024-03-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polymorphize=on -Z inline-mir=yes -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<impl at /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:4:1: 4:20>::get`
#1 [unused_generic_params] determining which generic parameters are unused by `<impl at /tmp/icemaker_global_tempdir.U4RMRfRYZr3K/rustc_testrunner_tmpdir_reporting.1on215cjbFAS/mvce.rs:4:1: 4:20>::get`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 7 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0392, E0432, E0601, E0658.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

### LINKED ISSUE #128601: ICE: `mentioned_items for DefId(..) have not yet been set`
auto-reduced (treereduce-rust):
````rust
trait Supertrait<'a, 'b> {
    fn cast(&self, x: &'a str) -> &'b str;
}

trait Subtrait<'a, 'b> {}

impl<'a> Subtrait<'a, 'a> for () {}
fn unsound(x: &dyn for<'a> Subtrait<'a, 'a>) -> &dyn for<'a, 'b> Supertrait<'a, 'b> {
    x
}

fn transmute<'a, 'b>(x: &'a str) -> &'b str {
    unsound(&()).cast(x)
}

fn main() {
    let x;
}


````

original:
````rust
//@ revisions: current next
//@ ignore-compare-mode-next-solver (explicit revisions)
//@[next] compile-flags: -Znext-solver

// We previously wrongly instantiated binders during trait upcasting,
// allowing the super trait to be more generic than the sub trait.
// This was unsound.
#![feature(trait_upcasting)]
trait Supertrait<'a, 'b> {
    fn cast(&self, x: &'a str) -> &'b str;
}

trait Subtrait<'a, 'b>: Supertrait<'a, 'b> {}

impl<'a> Supertrait<'a, 'a> for () {
    fn cast(&self, x: &'a str) -> &'a str {
        x
    }
}
impl<'a> Subtrait<'a, 'a> for () {}
fn unsound(x: &dyn for<'a> Subtrait<'a, 'a>) -> &dyn for<'a, 'b> Supertrait<'a, 'b> {
    x //~ ERROR mismatched types
    //[current]~^ ERROR mismatched types
}

fn transmute<'a, 'b>(x: &'a str) -> &'b str {
    unsound(&()).cast(x)
}

fn main() {
    let x;
    {
        let mut temp = String::from("hello there");
        x = transmute(temp.as_str());
    }
    println!("{x}");
}

````

Version information
````
rustc 1.82.0-nightly (a6043039a 2024-08-03)
binary: rustc
commit-hash: a6043039ad3aef48e08d72a3e32545accdee427a
commit-date: 2024-08-03
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zpolymorphize=on -Zinline-mir=yes`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.dUSfrojZPx4C/rustc_testrunner_tmpdir_reporting.EwjPSPXsHytl/mvce.rs:9:5
  |
8 | fn unsound(x: &dyn for<'a> Subtrait<'a, 'a>) -> &dyn for<'a, 'b> Supertrait<'a, 'b> {
  |                                                 ----------------------------------- expected `&dyn for<'a, 'b> Supertrait<'a, 'b>` because of return type
9 |     x
  |     ^ expected trait `Supertrait`, found trait `Subtrait`
  |
  = note: expected reference `&dyn for<'a, 'b> Supertrait<'a, 'b>`
             found reference `&dyn for<'a> Subtrait<'a, 'a>`

error[E0282]: type annotations needed
  --> /tmp/icemaker_global_tempdir.dUSfrojZPx4C/rustc_testrunner_tmpdir_reporting.EwjPSPXsHytl/mvce.rs:17:9
   |
17 |     let x;
   |         ^
   |
help: consider giving `x` an explicit type
   |
17 |     let x: /* Type */;
   |          ++++++++++++

thread 'rustc' panicked at compiler/rustc_mir_transform/src/inline.rs:762:55:
mentioned_items for DefId(0:12 ~ mvce[bf43]::unsound) have not yet been set
stack backtrace:
   0:     0x791e38f7b14d - std::backtrace_rs::backtrace::libunwind::trace::hc7f3b1787ccec24c
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x791e38f7b14d - std::backtrace_rs::backtrace::trace_unsynchronized::h3ac8bf18e083abb5
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x791e38f7b14d - std::sys::backtrace::_print_fmt::h2ada41eeab55a2b9
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/sys/backtrace.rs:66:9
   3:     0x791e38f7b14d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb6c5c8d07df5f480
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/sys/backtrace.rs:39:26
   4:     0x791e38fcb68b - core::fmt::rt::Argument::fmt::hf1e86b9645197f7e
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/core/src/fmt/rt.rs:173:76
   5:     0x791e38fcb68b - core::fmt::write::hc2704cd8a6bcd97b
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/core/src/fmt/mod.rs:1178:21
   6:     0x791e38f6eff3 - std::io::Write::write_fmt::hfa63a6d0a89b48eb
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/io/mod.rs:1823:15
   7:     0x791e38f7d942 - std::sys::backtrace::BacktraceLock::print::h467544d02c484049
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/sys/backtrace.rs:42:9
   8:     0x791e38f7d942 - std::panicking::default_hook::{{closure}}::hbbe4bd165b770857
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/panicking.rs:266:22
   9:     0x791e38f7d5ae - std::panicking::default_hook::h19d0acffcc7587aa
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/panicking.rs:293:9
  10:     0x791e354a1ab7 - std[1358c80ea0ee25f9]::panicking::update_hook::<alloc[fc99ae95686e7268]::boxed::Box<rustc_driver_impl[22665ae70ed8ccbd]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x791e38f7e332 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb10bb815e69ea3b5
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/alloc/src/boxed.rs:2162:9
  12:     0x791e38f7e332 - std::panicking::rust_panic_with_hook::h4c925c406498cc96
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/panicking.rs:805:13
  13:     0x791e38f7dfe7 - std::panicking::begin_panic_handler::{{closure}}::h064272ef2b4b11a8
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/panicking.rs:671:13
  14:     0x791e38f7b639 - std::sys::backtrace::__rust_end_short_backtrace::h5bdc82f1592642e9
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/sys/backtrace.rs:170:18
  15:     0x791e38f7dc74 - rust_begin_unwind
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/panicking.rs:662:5
  16:     0x791e38fc7ce3 - core::panicking::panic_fmt::hff5cbc88cdd98a80
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/core/src/panicking.rs:74:14
  17:     0x791e3755162c - <rustc_mir_transform[2dcb45b9d41b4ce4]::inline::Inliner>::try_inlining
  18:     0x791e37549a2b - <rustc_mir_transform[2dcb45b9d41b4ce4]::inline::Inliner>::process_blocks
  19:     0x791e37548f26 - <rustc_mir_transform[2dcb45b9d41b4ce4]::inline::Inline as rustc_middle[7c76cb5d6cd23d2c]::mir::MirPass>::run_pass
  20:     0x791e36a01d35 - rustc_mir_transform[2dcb45b9d41b4ce4]::pass_manager::run_passes_inner
  21:     0x791e37521d61 - rustc_mir_transform[2dcb45b9d41b4ce4]::optimized_mir
  22:     0x791e3750c95b - rustc_query_impl[23f344df433961bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[23f344df433961bb]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 8usize]>>
  23:     0x791e36b8c25f - rustc_query_system[32179918e569ee98]::query::plumbing::try_execute_query::<rustc_query_impl[23f344df433961bb]::DynamicConfig<rustc_query_system[32179918e569ee98]::query::caches::DefIdCache<rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[23f344df433961bb]::plumbing::QueryCtxt, false>
  24:     0x791e36b8ba33 - rustc_query_impl[23f344df433961bb]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  25:     0x791e36cd01d9 - rustc_middle[7c76cb5d6cd23d2c]::query::plumbing::query_get_at::<rustc_query_system[32179918e569ee98]::query::caches::DefIdCache<rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 8usize]>>>
  26:     0x791e36f9d2cf - rustc_query_impl[23f344df433961bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[23f344df433961bb]::query_impl::unused_generic_params::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 4usize]>>
  27:     0x791e36f9caaf - rustc_query_system[32179918e569ee98]::query::plumbing::try_execute_query::<rustc_query_impl[23f344df433961bb]::DynamicConfig<rustc_query_system[32179918e569ee98]::query::caches::DefaultCache<rustc_middle[7c76cb5d6cd23d2c]::ty::instance::InstanceKind, rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[23f344df433961bb]::plumbing::QueryCtxt, false>
  28:     0x791e36f9c790 - rustc_query_impl[23f344df433961bb]::query_impl::unused_generic_params::get_query_non_incr::__rust_end_short_backtrace
  29:     0x791e36f97f62 - rustc_interface[14ef9f95200544e8]::passes::analysis
  30:     0x791e36f96d5b - rustc_query_impl[23f344df433961bb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[23f344df433961bb]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 1usize]>>
  31:     0x791e37987cee - rustc_query_system[32179918e569ee98]::query::plumbing::try_execute_query::<rustc_query_impl[23f344df433961bb]::DynamicConfig<rustc_query_system[32179918e569ee98]::query::caches::SingleCache<rustc_middle[7c76cb5d6cd23d2c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[23f344df433961bb]::plumbing::QueryCtxt, false>
  32:     0x791e37987a4f - rustc_query_impl[23f344df433961bb]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  33:     0x791e37895f23 - rustc_interface[14ef9f95200544e8]::interface::run_compiler::<core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>, rustc_driver_impl[22665ae70ed8ccbd]::run_compiler::{closure#0}>::{closure#1}
  34:     0x791e37839189 - std[1358c80ea0ee25f9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[14ef9f95200544e8]::util::run_in_thread_with_globals<rustc_interface[14ef9f95200544e8]::util::run_in_thread_pool_with_globals<rustc_interface[14ef9f95200544e8]::interface::run_compiler<core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>, rustc_driver_impl[22665ae70ed8ccbd]::run_compiler::{closure#0}>::{closure#1}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>::{closure#0}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>
  35:     0x791e37838f32 - <<std[1358c80ea0ee25f9]::thread::Builder>::spawn_unchecked_<rustc_interface[14ef9f95200544e8]::util::run_in_thread_with_globals<rustc_interface[14ef9f95200544e8]::util::run_in_thread_pool_with_globals<rustc_interface[14ef9f95200544e8]::interface::run_compiler<core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>, rustc_driver_impl[22665ae70ed8ccbd]::run_compiler::{closure#0}>::{closure#1}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>::{closure#0}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6131bd0837d0c6a6]::result::Result<(), rustc_span[2926b480c67984a3]::ErrorGuaranteed>>::{closure#1} as core[6131bd0837d0c6a6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x791e38f8804b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0070e5d6a91d758e
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/alloc/src/boxed.rs:2148:9
  37:     0x791e38f8804b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h030f2f846d85cb19
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/alloc/src/boxed.rs:2148:9
  38:     0x791e38f8804b - std::sys::pal::unix::thread::Thread::new::thread_start::h42ce99086fa2e763
                               at /rustc/a6043039ad3aef48e08d72a3e32545accdee427a/library/std/src/sys/pal/unix/thread.rs:105:17
  39:     0x791e31ea6ded - <unknown>
  40:     0x791e31f2a0dc - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (a6043039a 2024-08-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polymorphize=on -Z inline-mir=yes -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `transmute`
#1 [unused_generic_params] determining which generic parameters are unused by `transmute`
end of query stack
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0282, E0308.
For more information about an error, try `rustc --explain E0282`.

```

</p>
</details>

@rustbot label +F-trait_upcasting

### PR DESCRIPTION
**Pull request by compiler-errors**
Don't inline MIR bodies that are tainted, since they're not necessarily well-formed.

Fixes #128601 (I didn't add a new test, just copied one from the crashes, since they're the same root cause).
Fixes #122909.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/inline.rs [hunk 1]
```diff
@@ -209,6 +209,9 @@ impl<'tcx> Inliner<'tcx> {
 
         let callee_body = try_instance_mir(self.tcx, callsite.callee.def)?;
         self.check_mir_body(callsite, callee_body, callee_attrs, cross_crate_inlinable)?;
+        if let Some(_) = callee_body.tainted_by_errors {
+            return Err("Body is tainted");
+        }
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/inline.rs:214]: Should this go at the beginning of check_mir_body ?

**Comment by compiler-errors** [comment]
r? cjgillot

File: compiler/rustc_mir_transform/src/inline.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_mir_transform/src/inline.rs:214]: Oh, hey, exactly the person who I was looking for. 

Yeah, I can do that

**Comment by matthiaskrgr** [comment]
also fixes #122909 ?

**Comment by cjgillot** [comment]
R=me after rebase

**Comment by rvolgers** [comment]
This is perhaps a dumb question, but why are any optimizations performed at all when errors are present?

**Comment by compiler-errors** [comment]
When *all* errors are present? Because we don't want global state to affect local computations, iirc.
