### PR TITLE
Point out the known type when field doesn't satisfy bound

### LINKED ISSUE #23286: Very confusing error on attempt to pass `path::Path` by value
``` rust
use std::path::Path;

fn f(p: Path) { }
```

produces

```
foo.rs:3:6: 3:7 error: the trait `core::marker::Sized` is not implemented for the type `[u8]` [E0277]
foo.rs:3 fn f(p: Path) { }
              ^
foo.rs:3:6: 3:7 note: `[u8]` does not have a constant size known at compile-time
foo.rs:3 fn f(p: Path) { }
              ^
```

We should give an explicit hint that `Path` should be passed by reference. Also the error does not mention `Path` and the type `u8` does not appear in the program.

**UPDATE:** The message now includes a full stack trace of types, but it would be better to start out with the type the user knows about (`Path`, in this case) and only discuss `[u8]` last. -- @nikomatsakis

### PR DESCRIPTION
**Pull request by estebank**
For file

```rust
use std::path::Path;

fn f(p: Path) { }
```

provide the following error

```nocode
error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied in `std::path::Path`
 --> file.rs:3:6
  |
3 | fn f(p: Path) { }
  |      ^ within `std::path::Path`, the trait `std::marker::Sized` is not implemented for `[u8]`
  |
  = note: `[u8]` does not have a constant size known at compile-time
  = note: required because it appears within the type `std::path::Path`
  = note: all local variables must have a statically known size
```

Fix #23286.

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -487,13 +487,30 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
-                                    "the trait bound `{}` is not satisfied",
-                                    trait_ref.to_predicate());
-                                err.span_label(span, &format!("the trait `{}` is not implemented \
-                                                               for `{}`",
-                                                              trait_ref,
-                                                              trait_ref.self_ty()));
+                                let (post_message, pre_message) =
+                                    if let ObligationCauseCode::BuiltinDerivedObligation(ref data)
+                                        = obligation.cause.code
+                                {
```
Comment (GuillaumeGomez) [inline src/librustc/traits/error_reporting.rs]: This brace should be on the previous line.

Comment (estebank) [inline src/librustc/traits/error_reporting.rs]: Done

File: src/librustc/traits/error_reporting.rs [hunk 2]
```diff
@@ -487,13 +487,29 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
-                                    "the trait bound `{}` is not satisfied",
-                                    trait_ref.to_predicate());
-                                err.span_label(span, &format!("the trait `{}` is not implemented \
-                                                               for `{}`",
-                                                              trait_ref,
-                                                              trait_ref.self_ty()));
+                                let (post_message, pre_message) =
+                                    if let ObligationCauseCode::BuiltinDerivedObligation(ref data)
+                                        = obligation.cause.code {
+                                    let parent_trait_ref = self.resolve_type_vars_if_possible(
```
Comment (GuillaumeGomez) [inline src/librustc/traits/error_reporting.rs]: Missing an indent level here.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
All good for me. I'm not sure I'm supposed to merge this so I'll wait for others' opinion.

cc @jonathandturner

File: src/librustc/traits/error_reporting.rs (hunk 2 above)
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: one better way might be using `match` :)

```rust
let (post_message, pre_message) = match obligation.cause.code {
    ObligationCauseCode::BuiltinDerivedObligation(ref data) => {
        let parent_trait_ref = self.resolve_type_vars_if_possible(
        ...
    }
    _ => {
        (String::new(), String::new())
    }
};

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -487,13 +487,29 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                                        &data.parent_trait_ref);
+                                    (format!(" in `{}`", parent_trait_ref.0.self_ty()),
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: One concern I have is that this only goes up one level, but there are similar cases where multiple levels are needed. For example, it'd be nice if this patch addressed this example: https://is.gd/BZjfP6

The current output is 

```
error[E0277]: the trait bound `*const u8: std::marker::Send` is not satisfied
  --> <anon>:16:5
   |
16 |     is_send::<Foo>();
   |     ^^^^^^^^^^^^^^ trait `*const u8: std::marker::Send` not satisfied
   |
   = note: `*const u8` cannot be sent between threads safely
   = note: required because it appears within the type `Baz`
   = note: required because it appears within the type `Bar`
   = note: required because it appears within the type `Foo`
   = note: required by `is_send`
```

and I think your suggested approach would be a big improvement:

```
error[E0277]: within `Foo`, the trait bound `*const u8: std::marker::Send` is not satisfied
  --> <anon>:16:5
   |
16 |     is_send::<Foo>();
   |     ^^^^^^^^^^^^^^ trait `*const u8: std::marker::Send` not satisfied
   |
   = note: `*const u8` cannot be sent between threads safely
   = note: required because it appears within the type `Baz`
   = note: required because it appears within the type `Bar`
   = note: required because it appears within the type `Foo`
   = note: required by `is_send`
```

But I believe your patch as is will print "within `Baz`" instead.

should be easy enough though -- just have to iterate on the cause chain rather than just going up one level.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Review by nikomatsakis — APPROVED** [review]
