### PR TITLE
cg: split dwarf for crate dependencies

### LINKED ISSUE #81024: split dwarf doesn't work with crate dependencies
As reported in https://github.com/rust-lang/rust/pull/77117#issuecomment-752872709 (cc @philipc), Split DWARF currently fails when compiling a crate with a dependency. 

To reproduce this, compile  `backtrace-rs` with the following command:

```shell-session
$ RUSTFLAGS="-Z split-dwarf=split" cargo +nightly --verbose build
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #81024.

- In #79570, `-Z split-dwarf-kind={none,single,split}` was replaced by `-C split-debuginfo={off,packed,unpacked}`. `-C split-debuginfo`'s packed and unpacked aren't exact parallels to single and split, respectively.

  On Unix, `-C split-debuginfo=packed` will put debuginfo in object files and package debuginfo into a DWARF package file (`.dwp`) and `-C split-debuginfo=unpacked` will put debuginfo in dwarf object files and won't package it.

  In the initial implementation of Split DWARF, split mode wrote sections which did not require relocation into a DWARF object (`.dwo`) file which was ignored by the linker and then packaged those DWARF objects into DWARF packages (`.dwp`). In single mode, sections which did not require relocation were written into object files but ignored by the linker and were not packaged. However, both split and single modes could be packaged or not, the primary difference in behaviour was where the debuginfo sections that did not require link-time relocation were written (in a DWARF object or the object file).

  In the first commit of this PR, I re-introduce a `-Z split-dwarf-kind` flag, which can be used to pick between split and single modes when `-C split-debuginfo` is used to enable Split DWARF (either packed or unpacked).
- Split DWARF packaging requires all of the object files to exist, including those in dependencies. ~~Therefore, the second commit of this PR makes rustc keep all objects or dwarf objects for unpacked mode and if the crate is a dependency in packed mode (determined by heuristic: if no linking is taking place), then objects or dwarf objects are kept. Objects are kept if `-Z split-dwarf-kind` is `SplitDwarfKind::Single`, and dwarf objects if `SplitDwarfKind::Split`.~~

  ~~There are other approaches that could be taken to supporting packed Split DWARF with crate dependencies but this seemed like the least complicated and was contained to only rustc. Other potential approaches are described in https://github.com/rust-lang/rust/issues/81024#issuecomment-760478223, I'm happy to change the approach I've taken here if it isn't what we're looking for.~~ See https://github.com/rust-lang/rust/pull/89819#issuecomment-985671867 for the current approach.
- ~~There's still a dependency on `llvm-dwp` after this change, which [we probably want to move away from](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/llvm-dwp.20is.20not.20recommended) but that seems out-of-scope for this PR. Ideally, Split DWARF (in packed or unpacked modes) will be usable on nightly after this lands. If there aren't any bugs reported then it's possible we could allow Split DWARF to be used on stable after this change, it depends whether or not switching away from `llvm-dwp` later would break any guarantees, or whether we'd want to change how we handle this cross-crate case in future.~~ See https://github.com/rust-lang/rust/pull/89819#issuecomment-985671867.

r? @nagisa
cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think I'm probably missing something, but could you reiterate why a new compiler option is needed? Dealing with the matrix of `-Csplit-debuginfo` and `-Zsplit-dwarf-kind` seems hairy and difficult to manage, and the discussion for `-Csplit-debuginfo` was in theory all about not requiring a separate option for split-dwarf on Unix.

**Comment by davidtwco** [comment]
> Hm so I was under the impression that the 4 options for dwarf were:
> 
> * Nothing, no debug info
> * Debuginfo in `*.o` files themselves, then also linked into final executable
> * Debuginfo split out into `*.dwo` files and nothing else
> * Debuginfo "linked" into `*.dwp` from all the `*.dwo` files
> 
> That corresponds to `-Cdebuginfo=0`, `-Csplit-debuginfo={off,unpacked,packed}`. Does split-dwarf have more options we need to encompass though? (sorry I feel like I'm missing something obvious you've probably already explained but on rereading I keep getting confused...)

As I understand it, it would be:

- Nothing, no debuginfo.
- Debuginfo in object files, linked into the final executable.
  - `-g -Cdebuginfo=2 -Csplit-debuginfo=off` 
- Debuginfo in object files, but in such a way that the linker skips it, not in the final executable - **single mode**
  - `-g -Cdebuginfo=2 -Csplit-debuginfo=unpacked -Zsplit-dwarf-kind=single`
- Debuginfo in object files, but in such a way that the linker skips it, not in the final executable, debuginfo from object files linked into dwarf package - **single mode, with packaging**
  - `-g -Cdebuginfo=2 -Csplit-debuginfo=packed -Zsplit-dwarf-kind=single`
- Debuginfo in dwarf object files, not in the final executable - **split mode**
  - `-g -Cdebuginfo=2 -Csplit-debuginfo=unpacked` (uses the default of `-Zsplit-dwarf-kind=split`)
- Debuginfo in dwarf object files, not in the final executable, debuginfo from object files linked into dwarf package - **split mode, with packaging**
  - `-g -Cdebuginfo=2 -Csplit-debuginfo=packed` (uses the default of `-Zsplit-dwarf-kind=split`)

I've described this in an [earlier comment](https://github.com/rust-lang/rust/pull/77117#issuecomment-739836394) which phrases it differently, that might help. I don't know what the specific use-cases for single vs split mode are for split dwarf, I just noticed that these were the variants provided by C++ compilers and so implemented both in rustc.

**Comment by davidtwco** [comment]
Noticed there's still a bug in this somewhere, trying to build rustc with packed split dwarf will fail with an error about a duplicate DWO ID, should work fine for smaller crates, haven't been able to produce a small reproduction but I didn't spend too much time on it.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -1252,17 +1246,44 @@ pub fn linker_and_flavor(sess: &Session) -> (PathBuf, LinkerFlavor) {
     bug!("Not enough information provided to determine how to invoke the linker");
 }
 
-/// Returns a boolean indicating whether we should preserve both object and dwarf object files on
-/// the filesystem for their debug information. This is often useful with split-dwarf like schemes.
-fn preserve_temps_for_their_debuginfo(sess: &Session) -> bool {
+/// Returns a `(bool, bool)` tuple of indicating whether we should preserve object and dwarf object
+/// files (respectively) on the filesystem for their debug information. This is often useful with
+/// split-dwarf like schemes.
+fn preserve_temps_for_their_debuginfo(sess: &Session) -> (bool, bool) {
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Fixed with recent push using [davidtwco/thorin](https://github.com/davidtwco/thorin).

**Comment by davidtwco** [comment]
I've pushed a big change to this PR, which takes an entirely different approach than before: 

Instead of keeping temporaries around longer so that dwarf objects from dependencies are available to `llvm-dwp` invocations in the binary crate, we now put dwarf objects into rlibs and use `thorin` rather than `llvm-dwp`. `thorin` is a DWARF packaging utility that I've been working on for exactly this purpose, written in Rust using gimli and object. We wanted to switch away from `llvm-dwp` eventually because the author said it wasn't recommended, so it seemed reasonable to implement our own DWARF packaging utility (binutils' `dwp` and `llvm-dwp` both support DWARF 5 now, so there's no difference in compatibility, just whether or not they can read an rlib and are written in Rust).

There's still some things to do here, but it's a good step forward:

- [ ] `thorin` doesn't have tests yet, I need to add some - it passes the important tests from `llvm-dwp`, the failing tests differ on diagnostics or the checks we perform (e.g. I don't check for duplicate `DWO_ID` like `llvm-dwp` does, I just skip the duplicate). I just haven't added tests to `thorin` itself yet.
- [ ] `thorin` will need to be published on crates.io, and presumably we'll want to move it to the rust-lang organization if it's a part of the compiler.
- [ ] I haven't checked the performance of `thorin` compared to the alternatives (performance is probably similar), but we might want to do that.

I'd appreciate any reviews or contributions to `thorin` if you can see anything that needs improved.

**Comment by khuey** [comment]
>     * [ ]  `thorin` will need to be published on crates.io, and presumably we'll want to move it to the rust-lang organization if it's a part of the compiler.

gimli is "part of the compiler" and not in the rust-lang org.

**Comment by davidtwco** [comment]
> > ```
> > * [ ]  `thorin` will need to be published on crates.io, and presumably we'll want to move it to the rust-lang organization if it's a part of the compiler.
> > ```
> 
> gimli is "part of the compiler" and not in the rust-lang org.

As far as I can tell, for compiler-team maintained crates, it's preferred that they live in `rust-lang`:

> #### Can existing out-of-tree crates from personal accounts or other organizations be transferred?
> Yes, this is encouraged. In order to do this, discuss this with the team and familiarize yourself with the GitHub documentation for repository transfers and then arrange to perform the transfer. Once a transfer is complete, a redirect will exist in the original account or organization and this will conflict with the names of any new forks of the transferred repository - an email to GitHub is required to resolve this.

([source](https://rust-lang.github.io/compiler-team/procedures/crates/#can-existing-out-of-tree-crates-from-personal-accounts-or-other-organizations-be-transferred))

**Comment by bjorn3** [comment]
Putting it in the gimli-rs organization may make sense too. That is where object, gimli and addr2line live too.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -635,57 +653,33 @@ fn escape_stdout_stderr_string(s: &[u8]) -> String {
...
-
-            if !dwp_not_found {
-                err.note(&format!("{:?}", &cmd));
-            }
-
-            err.emit();
+            sess.struct_err("linking dwarf objects with thorin failed")
+                .note(&format!("{:?}", e))
+                .emit();
+            info!("linker err:\n{}", format!("{:?}", e));
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/link.rs:682]: I don't think there is a need for this given that there is already an error with the exact same information.

File: src/bootstrap/dist.rs [hunk 3]
```diff
@@ -398,12 +398,12 @@ impl Step for Rustc {
...
 
-            let src_dir = builder.sysroot_libdir(compiler, host).parent().unwrap().join("bin");
-            let dst_dir = image.join("lib/rustlib").join(&*host.triple).join("bin");
-            t!(fs::create_dir_all(&dst_dir));
-
             // Copy over lld if it's there
             if builder.config.lld_enabled {
+                let src_dir = builder.sysroot_libdir(compiler, host).parent().unwrap().join("bin");
+                let dst_dir = image.join("lib/rustlib").join(&*host.triple).join("bin");
+                t!(fs::create_dir_all(&dst_dir));
```
Comment (bjorn3) [inline src/bootstrap/dist.rs:405]: Other things may end up in the bin dir too in the future, so maybe keep unconditionally creating it?

File: compiler/rustc_session/src/config.rs [hunk 4]
```diff
@@ -231,6 +231,37 @@ pub enum DebugInfo {
...
+/// Some debug-information requires link-time relocation and some does not. LLVM can partition
+/// the debuginfo into sections depending on whether or not it requires link-time relocation. Split
+/// DWARF provides a mechanism which allows the linker to skip the sections which don't require
+/// link-time relocation - either by putting those sections in DWARF object files, or by keeping
+/// them in the object file in such a way that the linker will skip them.
+#[derive(Clone, Copy, Debug, PartialEq, Hash)]
+pub enum SplitDwarfKind {
+    /// Sections which do not require relocation are written into object file but ignored by the
+    /// linker.
+    Single,
```
Comment (bjorn3) [inline compiler/rustc_session/src/config.rs:247]: What is the advantage of using this when using `-Csplit-debuginfo=unpacked/packed`?

Comment (davidtwco) [reply compiler/rustc_session/src/config.rs:247]: > Looks like the motivation is primarily to retain compatability with tools that only understand object files ([source](https://reviews.llvm.org/D52296#1242164)):
> 
> > To summarise:
> > 
> > * It shares most of the benefits with the .dwo solution.
> > * Unlike .dwo, there is no need to split the file and it is friendlier to other tools (ccache, distcc, etc)
> > * But unlike .dwo a distributed build system has to copy larger .o files.

(https://github.com/rust-lang/rust/pull/89819#issuecomment-949515345)

I don't think there's any advantage to using this with `-Csplit-debuginfo=packed`, but it might be useful with `-Csplit-debuginfo=unpacked`.

Comment (bjorn3) [reply compiler/rustc_session/src/config.rs:247]: For `-Csplit-debuginfo=unpacked` we don't tell the build system where to find the debuginfo, so I don't think ccache or distcc can be safely used with `-Csplit-debuginfo=unpacked` if they were to cache dylibs or executables. For rlibs the `.dwo` files would be in the `.rlib` the build system knows about anyway, so it doesn't matter. With `-Csplit-debuginfo=unpacked` the only way to distinguish between debuginfo files for different if by assuming a specific filename scheme (and are indistinguishable if multiple crates have the same name, even if they have different `-Cmetadata`). Also with `-Csplit-debuginfo=unpacked` there would still be only a single kind of file left over after compilation. The object files are deleted after linking and the debuginfo files are kept for consumption by a debugger or other tools. Another thing is that `-Csplit-debuginfo=unpacked` produces multiple files anyway. One file for each cgu.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 2 above)
Comment (davidtwco) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Fixed!

File: src/bootstrap/dist.rs (hunk 3 above)
Comment (davidtwco) [reply src/bootstrap/dist.rs]: Fixed!

**Comment by bjorn3** [comment]
If this is ready for review you can comment `@rustbot ready`. This will flip the label from S-waiting-on-author to S-waiting-on-review.

**Comment by davidtwco** [comment]
> If this is ready for review you can comment `@rustbot ready`. This will flip the label from S-waiting-on-author to S-waiting-on-review.

Thanks, had forgot to check the labels.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 5]
```diff
@@ -514,57 +525,87 @@ fn escape_stdout_stderr_string(s: &[u8]) -> String {
...
 }
 
-const LLVM_DWP_EXECUTABLE: &'static str = "rust-llvm-dwp";
-
-/// Invoke `llvm-dwp` (shipped alongside rustc) to link `dwo` files from Split DWARF into a `dwp`
-/// file.
-fn link_dwarf_object<'a>(sess: &'a Session, executable_out_filename: &Path) {
-    info!("preparing dwp to {}.dwp", executable_out_filename.to_str().unwrap());
-
+/// Invoke `thorin` (rust implementation of a dwarf packaging utility) to link DWARF objects into a
```
Comment (nagisa) [inline compiler/rustc_codegen_ssa/src/back/link.rs:528]: Nit: “Invoke” evokes an interpretation of starting an external process. “Use” would probably be more accurate.

File: compiler/rustc_session/src/config.rs (hunk 4 above)
Comment (nagisa) [reply compiler/rustc_session/src/config.rs:247]: Since this flag is a `-Z`, I'm comfortable with landing the implementation as is, but we should definitely revisit the concern if we ever end up considering the stabilization of the behaviour this flag exposes.

**Review by nagisa — APPROVED** [review]

**Comment by nagisa** [comment]
r=me once the conflicts are resolved.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 5 above)
Comment (davidtwco) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: Oops, this is just a leftover from when we were invoking an external process. Fixed!

**Comment by davidtwco** [comment]
> r=me once the conflicts are resolved.

Fixed the conflicts (this adds a tiny amount of additional logic to `link_dwarf_object`), and also consolidated some of the split dwarf testing while I was at it.

Before landing this, I think we [might need an FCP here](https://rust-lang.github.io/compiler-team/procedures/crates/) to approve the new dependency; we might want to move the repository; and make sure that the compiler team can publish new versions.

**Comment by davidtwco** [comment]
> > r=me once the conflicts are resolved.
> 
> Fixed the conflicts (this adds a tiny amount of additional logic to `link_dwarf_object`), and also consolidated some of the split dwarf testing while I was at it.
> 
> Before landing this, I think we [might need an FCP here](https://rust-lang.github.io/compiler-team/procedures/crates/) to approve the new dependency; we might want to move the repository; and make sure that the compiler team can publish new versions.

`thorin` now lives at https://github.com/rust-lang/thorin and the compiler team are owners on crates.io.

**Comment by lqd** [comment]
Looks like an apple runner issue ? let's @bors retry
