### PR TITLE
linker: Allow MSVC to use import libraries following the Meson/MinGW convention

### LINKED ISSUE #122455: Rust can detect GNU/Meson style named libraries but the MSVC linker backend ignores them
Hi all,

I'm coming from https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/1495#note_2324261 to report an inconsistency in how Rust passes library names to Visual Studio's `LINK.EXE`. In the `gst-plugins-rs` project, which is driven through Meson, I expected all libraries to be found correctly. Instead, I get an error of library not found at linking time.

This is caused by the following snippet of code.

https://github.com/rust-lang/rust/blob/3cbb93223f33024db464a4df27a13c7cce870173/compiler/rustc_codegen_ssa/src/back/linker.rs#L828-L837

The above snippet hardcodes the `xxx.lib` convention when passing import or static libraries' names. However, this is not consistent with [Meson's import library naming policy](https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa), which is already handled *correctly* in a separate portion of the Rust compiler:

https://github.com/rust-lang/rust/blob/3cbb93223f33024db464a4df27a13c7cce870173/compiler/rustc_metadata/src/native_libs.rs#L31-L40

The result of the above is that Rust, under MSVC, will happily put together `staticlibs` and `rlibs`, but will fail utterly when a `dylib` is demanded under the present set of circumstances.

This is the other half required to completely address the issue in https://github.com/gdesmott/system-deps/pull/77 -- I tried working around this by inserting `static:+verbatim` plus setting the correct file name, as shown in https://github.com/amyspark/system-deps/commit/10b342e57a48918927b825ecd7ddabe0fae3990e, but it returns an error:

```
   Compiling gstreamer-webrtc-sys v0.23.0 (https://gitlab.freedesktop.org/gstreamer/gstreamer-rs?branch=main#3246f4fb)
error: overriding linking modifiers from command line is not supported

error: could not compile `glib-sys` (lib) due to previous error
```

This is already known and was never addressed: https://github.com/rust-lang/rust/issues/95575#issuecomment-1086740589

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-msvc
release: 1.76.0
LLVM version: 17.0.6
```

<details><summary>Backtrace of the big linker error</summary>
<p>

```
error: linking with `link` failed: exit code: 1181
  |
  = note: "link" "/DEF:C:\\Users\\Amalia\\AppData\\Local\\Temp\\rustctTM4aY\\lib.def" "/NOLOGO" "C:\\Users\\Amalia\\AppData\\Local\\Temp\\rustctTM4aY\\symbols.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.17wz7xqkdhzcev1x.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1a8x2dtlxqing4e8.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1co7be2ni4utuxr9.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1je055do5g5iahua.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1l76n9fb2lvw298p.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1omqbmldb4s0sdt2.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1pu9xlpvi3og510m.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1ql1cp84pma28cu1.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1t9sx9bf4w1rj3jz.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.1vkt09ufbgf8t8cn.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.211hdkz22vb3msle.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.22gxtpmibtapjqo6.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.2jxus968qvlsdcau.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.2rggsjrye60wv3q8.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.2snszquag18oxnl5.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.2xstm66ca62kfllj.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.2y9hy9p4wamjs345.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.33ufwptus1u4qljn.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.35v7wapiwokmbtms.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.367prtivrl49f0kg.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3hj6xzklwcijholy.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3m9sutf3qpue5i0c.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3macqza9z0tl7fni.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3p6tdvg17sizgudi.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3vorgw1nt7nk2coy.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3xytnu9th3i3w2mi.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.3ye61sx47y3v47o7.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4bcrgwpqnddcause.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4bxyusslt3whyqwk.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4cim2y013oyck969.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4gat637njsvz09j.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4j9j51lizuerd5g8.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4l37kggiox28n9gr.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4n4er75klgsdn0k9.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4o647pts3glcowdo.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4pzz2ktuaa659d1u.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4wyiibbg66mp2jd8.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.4x9rp223xph7gwlr.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.54vws7lrv4at7ki3.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.565pgth8vo73c9wz.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.57oeti8uf49moolg.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.59xih176kvw2bkca.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.5gq2l3t75adsf7kg.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.9wh7zpzonplr3yw.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.j82tnopls5ioips.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.le1kv276f4jqb6e.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.ly4tdz2hqnaj53o.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.pnytrg8nckyohji.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.rn3k7w4ougmplbc.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.rwloceih1pgkwx1.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.xsyxbi1vuzp34yr.rcgu.o" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.41jhnr01nzx8uob.rcgu.o" "/LIBPATH:E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps" "/LIBPATH:E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\debug\\deps" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gio" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/zlib-1.2.13" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gobject" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/libffi/src" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gmodule" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gobject" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/libffi/src" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gobject" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/libffi/src" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:C:\\Users\\Amalia\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_msvc-0.52.4\\lib" "/LIBPATH:E:/gstreamer/build/subprojects/gstreamer/gst" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gobject" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/libffi/src" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gmodule" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:E:/gstreamer/build/subprojects/gstreamer/libs/gst/base" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/gstreamer/gst" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gobject" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/libffi/src" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/gmodule" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/glib-2.78.3/glib" "/LIBPATH:E:/gstreamer/build/subprojects/proxy-libintl" "/LIBPATH:E:/gstreamer/build/subprojects/pcre2-10.42" "/LIBPATH:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgstreamer_base-45037631e0ff1fce.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libatomic_refcell-a281618e8e7db238.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgstreamer_base_sys-1787b32c8cf84409.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\liburl-6bd60e7095eb4beb.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libidna-7772261202f0e54a.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libunicode_normalization-1b073f57909edbea.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libtinyvec-94b8c2bd85cda91f.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libtinyvec_macros-9549bb5648c2b1fa.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libunicode_bidi-1072a203c50bff4e.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libform_urlencoded-956660cd245b2d84.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libpercent_encoding-2f0376e7cd999742.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgstreamer-21bfdadf150da19d.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libcfg_if-f71af3f919aee094.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\liboption_operations-cda10743559ebedc.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libmuldiv-62b46e4a52da0f63.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libitertools-9eaa9c4264cb7657.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libeither-0bca8e86cc33fa07.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libnum_rational-a861fe609c8331ad.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libnum_integer-5cfd532259c1e482.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libnum_traits-5aa867b4ecf1ee79.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libonce_cell-80b87a6e1d2aa422.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libglib-a62c530b9fd0b5e9.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_executor-5bdbe86a7f79ac72.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libsmallvec-a1638065646cd3b9.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgio_sys-1a52cb560d974307.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libwindows_sys-d28a4c7ed1351593.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libwindows_targets-a050c2c8c5662fa1.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libthiserror-4ce702dcc9040def.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_util-8e4b31e435f33f82.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libmemchr-8812170d14d5d3de.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_io-b9c0d6c314e11bf6.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libslab-1cd8f3a279dd7951.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libpin_project_lite-a6cb5de165fd284e.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libpin_utils-0978a60699ab7dc3.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_task-cb647a19b3488fff.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_channel-3435817acfcaccaf.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_sink-af7131941b8034f6.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libfutures_core-342118864540fc9b.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libbitflags-be59e2918babb64f.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgstreamer_sys-720f7b1223bb3166.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libgobject_sys-5bafd4162484a53d.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\libglib_sys-e1b9a39aa9c22c38.rlib" "E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\liblibc-208bc620f8f9a2d1.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-e493bcbfdc66a475.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-467acea86c440d1f.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-8bcec20f8d868561.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-e75d865d889e433e.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-cd24a5810f58b720.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-44b4ecbbc95939b2.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-ff93d2b34eb6aecc.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-17346c417f0e9166.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-ff5a06ebf4571d10.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-cb2478631e21007b.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-58d59322b34f2b51.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-c192803e6895f627.rlib" "C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-20106e86b5dab94f.rlib" "ws2_32.lib" "winmm.lib" "gobject-2.0.lib" "shlwapi.lib" "dnsapi.lib" "iphlpapi.lib" "ws2_32.lib" "winmm.lib" "windows.0.52.0.lib" "ws2_32.lib" "winmm.lib" "ws2_32.lib" "winmm.lib" "ws2_32.lib" "winmm.lib" "legacy_stdio_definitions.lib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "ntdll.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.dll" "/OPT:REF,ICF" "/DLL" "/IMPLIB:E:\\gstreamer\\build\\subprojects\\gst-plugins-rs\\target\\x86_64-pc-windows-msvc\\debug\\deps\\gstrsfile.dll.lib" "/DEBUG" "/NATVIS:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Amalia\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : fatal error LNK1181: cannot open input file 'gobject-2.0.lib'


error: could not compile `gst-plugin-file` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

</p>
</details>

### PR DESCRIPTION
**Pull request by amyspark**
Hi all,

This PR implements support for `MsvcLinker` to use import libraries following Meson and the MinGW toolchain's naming convention. Meson [follows the `libfoo.dll.a` naming convention](https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa) to disambiguate between static and import libraries.

This support already existed for static libraries (see #100101), but not for dynamic libraries. The latter case was added by duplicating the logic in `native_libs::find_native_static_library`, but a separate case was added in `link_dylib_by_name` for the Windows CRT libraries which must be handled by the linker itself.

See for prerequisites #129366, #126094, and #128370.

All feedback is appreciated!

Fixes #122455

cc @sdroege @nirbheek

### CODE REVIEW

**Comment by mati865** [comment]
Sorry for the offtpic but I'm curious whether there weren't compatibility issues regarding Meson decision.
Unlike import libraries and DLLs, static libraries are basically incompatible between MSVC and MinGW. So using the same extension for them is risky.

That said, making dylibs consistent with ribs and static libs sounds like a good idea.

**Comment by nirbheek** [comment]
> Meson [follows the `libfoo.dll.a` naming convention](https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa)

typo: `libfoo.a` naming convention for static libraries.

> Sorry for the offtpic but I'm curious whether there weren't compatibility issues regarding Meson decision.
> Unlike import libraries and DLLs, static libraries are basically incompatible between MSVC and MinGW. So using the same extension for them is risky.

This is not accurate, we wrote the [above-linked Meson FAQ](https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa) because it's a common misconception. I'll repeat and expand the relevant bits here for the benefit of everyone reading:

1. MSVC and MinGW toolchains both use the `ar` format for static libraries (and also for import libraries, but that's a separate matter), so the file format is compatible.
2. [MSVC](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/) and [MinGW](https://mingwpy.github.io/ucrt.html) have also been using UCRT for quite some time now. MSYS2 has a [UCRT64 variant that is the recommended variant](https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt).
3. You should not mix static libraries built with different CRTs, but that is true regardless of which toolchain you are using. You will get exactly the same problems if you link MSVC static libraries built with MSVCRT with MSVC static libraries built with UCRT.
    - In the current implementation, this configuration is considered user error, and outside of the purview of the linker.

In summation: there is no reason to treat MinGW-built and MSVC-built static libraries as incompatible. In fact, at GStreamer we have been linking them together for 5 years with no adverse effects, since everything is using UCRT.

FWIW, as of recently, CMake also accepts `libfoo.a` static libraries via pkg-config when building with an MSVC toolchain.

An important quality-of-life change for users there is to ignore static libraries presented by Strawberry Perl's pkg-config[1](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9375)[2](https://github.com/mesonbuild/meson/pull/9384) (which is [unconditionally added to `PATH`](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/11) and must not be used as a MinGW distribution), since [Strawberry Perl is included in `PATH` in Github CI images by default](https://github.com/actions/runner-images/issues/5459), and there is no way to turn it off.

Similar to CMake and Meson, this needs to be handled in pkg-config-rs, and I have [filed an issue about it](https://github.com/rust-lang/pkg-config-rs/issues/164).

**Comment by amyspark** [comment]
> typo: libfoo.a naming convention for static libraries.

@nirbheek I was thinking of the particular case of import libraries (libfoo.dll.a) for which I already experienced such a clash elsewhere: https://aomedia-review.googlesource.com/c/aom/+/173603

**Comment by compiler-errors** [comment]
r? @wesleywiser

sorry, not the best person to review this

**Comment by mati865** [comment]
@nirbheek at MSYS2 we've had many reports of broken builds when using static libraries made with MSVC in mingw-w64 based toolchains and we always referred to what I think was original MinGW (not mingw-w64) webpage or some mailing list message that said DLLs are the only supported interface between MSVC and MinGW.
Maintainer of mingw-w64 stuff at LLVM says the same thing: https://github.com/mstorsjo/llvm-mingw/issues/305#issuecomment-1264255400
It's true UCRT fixed many of the issues but I doubt any mingw-w64 developer would claim static libraries to be fully compatible. I don't mean it doesn't work, it's just unsupported and shouldn't be considered as a bug if compatibly breaks.

Some of the issues on top of my head:
- MSVCRT toolchains basically required `__USE_MINGW_ANSI_STDIO` to have working stdio but it's not compatible with MSVC (MSYS2 still enables it for all packages, even UCRT ones)
- GCC (and IIRC Clang to match it) uses x87 for f64/double on 32-bit targets
- Dwarf-2 debuginfo used by 32-bit toolchains is definitely not compatible with MSVC, IIRC SEH used by 64-bit toolchains is also somewhat different from MSVC
- there used to be (maybe still is?) some discrepancy between MSVC and GCC/Clang at registers usage in edge cases, cannot recall the details after all those years, could be related to varargs
- C and C++ libraries not distinguishable by the linker and accidental inclusion of any C++ library is a guaranteed broken build

> MSVC and MinGW toolchains both use the ar format for static libraries (and also for import libraries, but that's a separate matter), so the file format is compatible.

File format is not the problem here but since `lib<name>.a` is typically associated with MinGW/mingw-w64 toolchains this might be confusing for users when mingw-w64 GCC/Clang created static library breaks their build, like infamous strawberry perl that you've mentioned.

> [MSVC](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/) and [MinGW](https://mingwpy.github.io/ucrt.html) have also been using UCRT for quite some time now. MSYS2 has a [UCRT64 variant that is the recommended variant](https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt).

Unfortunately there are still many vendors providing MSVCRT toolchain as the default one, especially when cross-compiling.

> You should not mix static libraries built with different CRTs, but that is true regardless of which toolchain you are using.

OFC, we've been telling it at MSYS2 for years, it's also mentioned at MSYS2 webpage.

> In summation: there is no reason to treat MinGW-built and MSVC-built static libraries as incompatible. In fact, at GStreamer we have been linking them together for 5 years with no adverse effects, since everything is using UCRT.

This is refreshing to hear things are getting better but I still worry those are either too simple libraries to exhibit incompatibility issues or was not tested deeply enough.

> FWIW, as of recently, [CMake also accepts libfoo.a static libraries](https://gitlab.kitware.com/cmake/cmake/-/issues/23975) via pkg-config when building with an MSVC toolchain.

Oh, I didn't know about it yet.

---

Regarding Meson's FAQ
> Both Clang and GNU compilers can search for libfoo.a when specifying a library as -lfoo. This does not work for alternative naming schemes for static libraries such as libfoo.lib.

Both ld.bfd and LLD search for `<name>.lib` (notice missing `lib`) which is MSVC naming convention, but `.dll.a` and `.a` libs are higher priority.

> Projects built with the MinGW compiler are fully compatible with MSVC as long as they use the same CRT (e.g. UCRT with MSYS2).

Meson is free to support it (and workaround eventual issues) but this is not officially supported by GNU nor LLVM mingw-w64 based toolchains.

**Comment by petrochenkov** [comment]
I have a general concern about turning `linker library_by_name` invocations into `linker /full/path/library_by_name` invocations, where the `library_by_name` -> `/full/path/library_by_name` conversion is done by rustc.

In the first case, the search directories are determined by the linker and may include some system directories, specific to a distribution directory layout, or controlled by some default linker config, or something else outside of rustc's purview.
In the second case the search paths will only include directories inside rustc toolchain, or directories explicitly passed with `-L` options.

`find_native_static_library` is currently used when the library actually needs to be processed by rustc itself (not by linker), e.g. to pack it into a rlib.
In that case you don't have a choice but to use rustc's search directories without looking at the system (unless explicitly asked by user).
(Other 2 uses of `find_native_static_library` in linker.rs are for options that apparently don't support linker search by name at all.)

What system directories we can lose when replacing linker search with rustc search on windows-(msvc,gnu) targetes?

**Comment by petrochenkov** [comment]
If we just fully switched to rustc-based library search everywhere, then I suspect we'd fail to find libc on like half of Unix-like systems.

**Comment by nirbheek** [comment]
@mati865 Thanks for the detailed explanation of MinGW and MSVC compatibility. My point was primarily that the two are not "incompatible" as was stated, but that they are indeed compatible in many cases, and people have been using it for years.

You've given many more cases, such as C++ static libraries, where there is incompatibility even with static libraries produced by the same toolchain, which IMO supports the argument that this is not the linker's job. It's up to the user and the build system.

> This is refreshing to hear things are getting better but I still worry those are either too simple libraries to exhibit incompatibility issues or was not tested deeply enough.

We build [100 projects](https://gitlab.freedesktop.org/gstreamer/cerbero/-/tree/main/recipes), most of which used to be built with Autotools/MinGW and have been slowly ported over to Meson.

> Regarding Meson's FAQ
> > Both Clang and GNU compilers can search for libfoo.a when specifying a library as -lfoo. This does not work for alternative naming schemes for static libraries such as libfoo.lib.
> Both ld.bfd and LLD search for <name>.lib (notice missing lib) which is MSVC naming convention, but .dll.a and .a libs are higher priority.

The point is that `foo.lib` is already an import library, so we can't use that because it causes a filename collision. One other option is `libfoo.lib` which is used in some places, but Clang and GNU compilers do not pick it up when specifying a library as `-lfoo`, so it had to be rejected.

**Comment by nirbheek** [comment]
> I have a general concern about turning `linker library_by_name` invocations into `linker /full/path/library_by_name` invocations, where the `library_by_name` -> `/full/path/library_by_name` conversion is done by rustc.

It gets worse, as I understand it, Rust is also converting absolute paths into `-Ldir/ -lfoo` pairs first, and then applying this conversion to convert it back to an absolute path. This can be very wrong in cases where you're picking up libraries from multiple `-L` paths, or if there are multiple options and the user prefers one.

**Comment by amyspark** [comment]
> What system directories we can lose when replacing linker search with rustc search on windows-(msvc,gnu) targetes?

@petrochenkov If I understand you correctly, by `rustc` search you mean resolving and baking in the libraries' path, right? I'd definitely prefer this approach, it'll make error logs noisier because of the command length, but it'll definitely tell us which files are going to be linked.

Rebase pushed to address bors's detection too.

**Comment by petrochenkov** [comment]
Reviewing this requires from me doing some additional research, so I won't get to it until I return from vacation.

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 1]
```diff
@@ -784,6 +785,38 @@ pub struct MsvcLinker<'a> {
...
+            for (prefix, suffix) in &formats {
+                let test = path.dir.join(format!("{prefix}{name}{suffix}"));
+                if test.exists() {
+                    return OsString::from(test);
+                }
+            }
+        }
+
+        // Allow the linker to find CRT libs itself
+        OsString::from(format!("{}{}", name, if verbatim { "" } else { ".lib" }))
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:816]: So the semantics are that rustc first searches the rustc-controlled directories, and then falls back to linker-controlled search if it finds nothing.

That may be a good way forward for the problem from https://github.com/rust-lang/rust/pull/123436#issuecomment-2048093837.
Just need to make sure that the `sess.target_filesearch(PathKind::Native).search_paths()` paths and the paths passed to the linker with `-L` (`include_path`) are the same paths in the same order.

**Comment by petrochenkov** [comment]
Relevant code from LLD:
https://github.com/llvm/llvm-project/blob/main/lld/MinGW/Driver.cpp#L138-L169

File: compiler/rustc_codegen_ssa/src/back/linker.rs (hunk 1 above)
Comment (amyspark) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:816]: I think you mean this code in particular? If so then we should be good to go: https://github.com/rust-lang/rust/commit/cae3c936eb963cedc6523baeeaa9a58d13fa4c2e#diff-862130c0af71054886913befc8084094485fa7d764d95f55644e033e34acd126R2397-R2408

**Comment by petrochenkov** [comment]
I'm going to take over this work at least partially and land some pre-requisites first.
Blocked on https://github.com/rust-lang/rust/pull/126094.
@rustbot blocked

**Comment by amyspark** [comment]
@seerich It is ready for testing, though @petrochenkov said there were some preliminaries on their end that needed to be addressed (https://github.com/rust-lang/rust/pull/123436#issuecomment-2153249460)

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/128370.
@rustbot blocked

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 2]
```diff
@@ -834,6 +835,38 @@ pub struct MsvcLinker<'a> {
     sess: &'a Session,
 }
 
+impl MsvcLinker<'_> {
+    // FIXME this duplicates rustc_metadata::find_native_static_library,
+    // as the Meson/MinGW suffix for import libraries can differ
+    fn find_native_dynamic_library(name: &str, verbatim: bool, sess: &Session) -> OsString {
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:841]: Could you put this logic into `native_libs.rs` next to `fn try_find_native_static_library` (and generally mirror that function)?

**Comment by amyspark** [comment]
@seerich I'm following the steps [here](https://rustc-dev-guide.rust-lang.org/building/quickstart.html), I think it's just a matter of linking the `stage1` toolchain as described and then issuing `rustup default stage1`.

**Comment by amyspark** [comment]
@seerich looks like you need to update VS: https://users.rust-lang.org/t/error-could-not-compile-rustc-driver-lib-due-to-1-previous-error/113278/2, I've not run into it because I daily drive 2022 Preview.

File: compiler/rustc_metadata/src/native_libs.rs [hunk 3]
```diff
@@ -109,11 +109,59 @@ pub fn try_find_native_static_library(
...
+        }
+    }
+}
+
 pub fn find_native_static_library(name: &str, verbatim: bool, sess: &Session) -> PathBuf {
     try_find_native_static_library(sess, name, verbatim)
         .unwrap_or_else(|| sess.dcx().emit_fatal(errors::MissingNativeLibrary::new(name, verbatim)))
 }
 
+pub fn find_native_dynamic_library(name: &str, verbatim: bool, sess: &Session) -> PathBuf {
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/native_libs.rs:160]: This function is unused and can be removed.

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 4]
```diff
@@ -878,15 +885,22 @@ impl<'a> Linker for MsvcLinker<'a> {
...
     }
 
     fn link_dylib_by_path(&mut self, path: &Path, _as_needed: bool) {
         // When producing a dll, MSVC linker may not emit an implib file if the dll doesn't export
         // any symbols, so we skip linking if the implib file is not present.
-        let implib_path = path.with_extension("dll.lib");
-        if implib_path.exists() {
-            self.link_or_cc_arg(implib_path);
+        let formats = [".dll.lib", ".dll.a"];
+        for extension in formats {
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:898]:
```suggestion
        for extension in ["dll.lib", "dll.a"] {
```
The dots are [unnecessary](https://doc.rust-lang.org/std/path/struct.Path.html#method.with_extension) (and maybe incorrect), also unnecessary local variable.

File: compiler/rustc_metadata/src/native_libs.rs [hunk 5]
```diff
@@ -109,11 +109,59 @@ pub fn try_find_native_static_library(
...
+                        return ControlFlow::Break(test);
+                    }
+                }
+            }
+            ControlFlow::Continue(())
+        },
+    )
+    .break_value();
+
+    match path {
```
Comment (petrochenkov) [inline compiler/rustc_metadata/src/native_libs.rs:145]: Could you mirror what `try_find_native_static_library` does here? (I.e. no fall back in this function.)

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 6]
```diff
@@ -854,6 +856,11 @@ pub struct MsvcLinker<'a> {
     sess: &'a Session,
 }
 
+impl MsvcLinker<'_> {
+    // FIXME this duplicates rustc_metadata::find_native_static_library,
+    // as the Meson/MinGW suffix for import libraries can differ
+}
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:862]: This can be removed now.

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 7]
```diff
@@ -878,15 +885,22 @@ impl<'a> Linker for MsvcLinker<'a> {
     }
 
     fn link_dylib_by_name(&mut self, name: &str, verbatim: bool, _as_needed: bool) {
-        self.link_arg(format!("{}{}", name, if verbatim { "" } else { ".lib" }));
+        // On MSVC-like targets rustc supports static libraries using alternative naming
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:888]:
```suggestion
        // On MSVC-like targets rustc supports import libraries using alternative naming
```

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 8]
```diff
@@ -878,15 +885,22 @@ impl<'a> Linker for MsvcLinker<'a> {
...
+        self.link_arg(path);
     }
 
     fn link_dylib_by_path(&mut self, path: &Path, _as_needed: bool) {
         // When producing a dll, MSVC linker may not emit an implib file if the dll doesn't export
         // any symbols, so we skip linking if the implib file is not present.
-        let implib_path = path.with_extension("dll.lib");
-        if implib_path.exists() {
-            self.link_or_cc_arg(implib_path);
+        let formats = [".dll.lib", ".dll.a"];
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:897]: Ah, this part is actually unnecessary.
`link_dylib_by_path` is only used for Rust dylib crates, and those always use the `dll.lib` extension (see `fn set_output_kind` above).

File: compiler/rustc_metadata/src/native_libs.rs (hunk 3 above)
Comment (amyspark) [reply compiler/rustc_metadata/src/native_libs.rs:160]: This function is used in linker.rs (`link_dylib_by_name`).

File: compiler/rustc_codegen_ssa/src/back/linker.rs (hunk 4 above)
Comment (amyspark) [reply compiler/rustc_codegen_ssa/src/back/linker.rs:898]: Marking as resolved in light of https://github.com/rust-lang/rust/pull/123436#discussion_r1744137224

File: compiler/rustc_metadata/src/native_libs.rs (hunk 5 above)
Comment (amyspark) [reply compiler/rustc_metadata/src/native_libs.rs:145]: This is not possible. The code path here also handles the CRT libraries, without fallback I get:

```
Building stage1 library artifacts {alloc, core, panic_abort, panic_unwind, proc_macro, std, sysroot, test, unwind} (x86_64-pc-windows-msvc)
   Compiling compiler_builtins v0.1.123
   Compiling core v0.0.0 (E:\rust\library\core)
   Compiling std v0.0.0 (E:\rust\library\std)
   Compiling windows-targets v0.0.0 (E:\rust\library\windows_targets)
   Compiling rustc-std-workspace-core v1.99.0 (E:\rust\library\rustc-std-workspace-core)
   Compiling alloc v0.0.0 (E:\rust\library\alloc)
   Compiling cfg-if v1.0.0
   Compiling rustc-demangle v0.1.24
   Compiling unwind v0.0.0 (E:\rust\library\unwind)
   Compiling rustc-std-workspace-alloc v1.99.0 (E:\rust\library\rustc-std-workspace-alloc)
   Compiling panic_abort v0.0.0 (E:\rust\library\panic_abort)
   Compiling panic_unwind v0.0.0 (E:\rust\library\panic_unwind)
   Compiling std_detect v0.1.5 (E:\rust\library\stdarch\crates\std_detect)
   Compiling hashbrown v0.14.5
error: could not find native static library `kernel32`, perhaps an -L flag is missing?
```

File: compiler/rustc_metadata/src/native_libs.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_metadata/src/native_libs.rs:160]: `try_find_native_dynamic_library` should be used there instead, please mirror the similar logic for static libraries.

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 9]
```diff
@@ -878,7 +880,14 @@ impl<'a> Linker for MsvcLinker<'a> {
...
 
     fn link_dylib_by_name(&mut self, name: &str, verbatim: bool, _as_needed: bool) {
-        self.link_arg(format!("{}{}", name, if verbatim { "" } else { ".lib" }));
+        // On MSVC-like targets rustc supports import libraries using alternative naming
+        // scheme (`libfoo.a`) unsupported by linker, search for such libraries manually.
+        if let Some(path) = try_find_native_dynamic_library(self.sess, name, verbatim) {
+            self.link_arg(path);
+        } else {
+            let crtlib = PathBuf::from(format!("{}{}", name, if verbatim { "" } else { ".lib" }));
+            self.link_arg(crtlib);
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/linker.rs:889]:
```suggestion
            self.link_arg(format!("{}{}", name, if verbatim { "" } else { ".lib" }));
```

**Comment by petrochenkov** [comment]
The code looks good to me now, but I'll need to re-read the thread and the linked materials to understand *why* we are doing this (probably today or tomorrow).

**Comment by petrochenkov** [comment]
Sorry for the delay, I'll 100% get to this tomorrow.
In the meantime the PR description needs to be updated.

**Comment by petrochenkov** [comment]
Table of supported extensions on Windows (in priority order).

**LLD:**

native staticlib windows-gnu: libname.a, name.lib
native dylib import lib windows-gnu: libname.dll.a, name.dll.a, libname.a, name.lib, libname.dll, name.dll
rust dylib import lib windows-gnu: N/A

native staticlib windows-msvc: N/A
native dylib import lib windows-msvc: N/A
rust dylib import lib windows-msvc: N/A

**rustc (with this PR):**

native staticlib windows-gnu: libname.a
native dylib import lib windows-gnu: N/A
rust dylib import lib windows-gnu: libname.dll.a

native staticlib windows-msvc: name.lib, libname.a
native dylib import lib windows-msvc: name.lib, libname.dll.a, libname.a
rust dylib import lib windows-msvc: name.dll.lib

The MSVC naming in this PR is generally consistent with the GNU naming (with the order mostly reversed).

We may want to add more naming variants in the future for better compatibility between rustc and lld, and better consistency between gnu and msvc.
It may also make sense to change naming for Rust dylib crates from `name.dll(.lib)` to `libname.dll(.a)` since we fully control them.

**Review by petrochenkov — APPROVED** [review]

**Comment by amyspark** [comment]
Doesn't look like an error in the PR, was that a race condition?

**Comment by ChrisDenton** [comment]
That looks like a problem we've been having with CI lately. GitHub are looking into it.

@bors retry
