### PR TITLE
Fix macro_metavar_expr_concat behavior with nested repetitions

### LINKED ISSUE #150002: macro_metavar_expr_concat broken when combining repeats and optionals
I tried this code:

```rust
#![feature(macro_metavar_expr_concat)]
macro_rules! define_ioctl_data {
    (struct $s:ident {
        $($field:ident: $ty:ident $([$opt:ident])?,)*
    }) => {
        pub struct $s {
            $($field: $ty,)*
        }

        impl $s {
            $($(
                fn ${concat(get_, $field)}(&self) -> $ty {
                    let _ = $opt;
                    todo!()
                }
            )?)*
        }
    };
}

define_ioctl_data! {
    struct Foo {
        a: A [aa],
        b: B [bb],
    }
}
```

I expected to see this happen: Expands to

```rust
pub struct Foo {
    a: A,
    b: B,
}
impl Foo {
    fn get_a(&self) -> A {
        let _ = aa;

        ::core::panicking::panic("not yet implemented")
    }
    fn get_b(&self) -> B {
        let _ = bb;
        ::core::panicking::panic("not yet implemented")
    }
}
```

Instead, this happened: Expands to

```rust
pub struct Foo {
    a: A,
    b: B,
}
impl Foo {
    fn get_a(&self) -> A {
        let _ = aa;

        ::core::panicking::panic("not yet implemented")
    }
    fn get_a(&self) -> B {
        let _ = bb;
        ::core::panicking::panic("not yet implemented")
    }
}
```

which defines `get_a` twice.

### Meta

`rustc --version --verbose`:
```
1.94.0-nightly (2025-12-13 430d8297c712ca7e8a48)
```

### PR DESCRIPTION
**Pull request by Delta17920**
**The Bug**: The `${concat(...)}` expression was using the wrong loop index when inside nested repetitions (like optional groups), causing it to get "stuck" on the first element and generate duplicate code.

**The Fix**: Updated `metavar_expr_concat` in `transcribe.rs` to correctly search the repetition stack (`tscx.repeats`) for the target variable instead of blindly using the last index.

**Tests**:
    Added `tests/ui/macros/concat-nested-repetition.rs.`

Fixes rust-lang/rust#150002

### CODE REVIEW

**Comment by Delta17920** [comment]
r? compiler

File: compiler/rustc_expand/src/mbe/transcribe.rs [hunk 1]
```diff
@@ -558,26 +558,29 @@ fn metavar_expr_concat<'tx>(
...
-                        let Some((curr_idx, _)) = tscx.repeats.last() else {
-                            return Err(dcx.struct_span_err(dspan.entire(), "invalid syntax"));
-                        };
-                        match &named_matches[*curr_idx] {
-                            // FIXME(c410-f3r) Nested repetitions are unimplemented
-                            MatchedSeq(_) => {
+                let mut matched = matched_from_ident(dcx, *ident, tscx.interp)?;
+                let mut repeats_iter = tscx.repeats.iter();
+
+                loop {
```
Comment (jdonszelmann) [inline compiler/rustc_expand/src/mbe/transcribe.rs]: This kind of loop seems to be similar to what's already implemented in `lookup_cur_matched`. I don't quite understand why we need to do this logic again here. Maybe that function is not applicable, but I expect there already being code for getting the right variable to repetition conversion somewhere else. That's (to my admittedly slightly limited understanding) what `lookup_cur_matched` tries to do. Can you explain why this logic needs to be redone here?

Comment (Delta17920) [reply compiler/rustc_expand/src/mbe/transcribe.rs]: Thanks for the suggestion. You are right my implementation handles the descent manually, but since I'm just looking for the specific match at the current depth (and erroring otherwise), `lookup_cur_matched` covers this exact use case. I'll update it to use that existing function to avoid duplication
