### PR TITLE
Deduplicate `::` -> `:` typo errors

### LINKED ISSUE #70382: Incorrect suggestion after #70074
https://github.com/rust-lang/rust/blob/02046a5d402c789c006d0da7662f800fe3c45faf/src/test/ui/type/ascription/issue-47666.stderr#L16-L27

https://github.com/rust-lang/rust/blob/02046a5d402c789c006d0da7662f800fe3c45faf/src/test/ui/type/ascription/issue-47666.stderr#L29-L43

### PR DESCRIPTION
**Pull request by estebank**
Deduplicate errors caused by the same type ascription typo, including
ones suggested during parsing that would get reported again during
resolve. Fix #70382.

### CODE REVIEW

File: src/librustc_resolve/late/diagnostics.rs [hunk 1]
```diff
@@ -225,13 +226,31 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
...
                 self.r.lookup_import_candidates(ident, ns, &self.parent_scope, is_enum_variant);
-            let mut enum_candidates = enum_candidates
-                .iter()
-                .map(|suggestion| import_candidate_to_enum_paths(&suggestion))
-                .collect::<Vec<_>>();
-            enum_candidates.sort();
 
             if !enum_candidates.is_empty() {
+                if let (PathSource::Type, Some(Expr { kind: ExprKind::Type(expr, ty), .. })) =
+                    (source, self.diagnostic_metadata.current_expr)
```
Comment (petrochenkov) [inline src/librustc_resolve/late/diagnostics.rs:232]: As I mentioned in https://github.com/rust-lang/rust/pull/74211#discussion_r453065411 `current_expr` as it's calculated now can be arbitrarily far from the resolved path, so it's not suitable for this check assuming the immediate parent expression.

File: src/librustc_parse/parser/diagnostics.rs [hunk 2]
```diff
@@ -331,6 +331,7 @@ impl<'a> Parser<'a> {
                         Applicability::MachineApplicable
                     },
                 );
+                self.sess.type_ascription_path_suggestions.borrow_mut().insert(sp);
```
Comment (petrochenkov) [inline src/librustc_parse/parser/diagnostics.rs:334]: What happens if the `err` is cancelled and never emitted?
Will we get an ICE from `delay_as_bug` in the worst case?

File: src/librustc_resolve/late/diagnostics.rs [hunk 3]
```diff
@@ -484,10 +503,25 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
             let (followed_by_brace, closing_brace) = self.followed_by_brace(span);
             let mut suggested = false;
             match source {
-                PathSource::Expr(Some(parent)) => {
+                PathSource::Expr(Some(
+                    parent @ Expr { kind: ExprKind::Field(..) | ExprKind::MethodCall(..), .. },
```
Comment (petrochenkov) [inline src/librustc_resolve/late/diagnostics.rs:507]: I think I've seen this in a different PR.
(I'll wait for rebase.)

File: src/librustc_parse/parser/diagnostics.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_parse/parser/diagnostics.rs:334]: Correct.

File: src/librustc_resolve/late/diagnostics.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs:505]: Coincidentally was just doing so.

File: src/librustc_resolve/late/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs]: I changed the approach to use the already present `current_type_ascription`. Let me know what you think.

**Comment by estebank** [comment]
I made some indentation changes in a block, so you might prefer to [ignore whitespace in the diff](https://github.com/rust-lang/rust/pull/74210/files?diff=split&w=1).

**Comment by estebank** [comment]
(@petrochenkov I can remove the last commit and not handle those cases in this PR)

File: src/test/ui/type/ascription/issue-47666.stderr [hunk 4]
```diff
@@ -12,5 +32,11 @@ LL |     let _ = Option:Some(vec![0, 1]);
    = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 
-error: aborting due to previous error
+error: expected `::`, found `:`
+  --> $DIR/issue-47666.rs:7:16
+   |
+LL |     let _ = Foo:A;
+   |                ^ help: write a path separator instead: `::`
+
```
Comment (estebank) [inline src/test/ui/type/ascription/issue-47666.stderr:40]: For reference, [this is the current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d6fb7838fd8c2c722d91313f22ac73be):

```
error: expected type, found `2`
 --> src/main.rs:6:19
  |
6 |     let _ = Foo:B(2); //~ ERROR expected type
  |                -  ^ expected type
  |                |
  |                help: maybe write a path separator here: `::`
  |
  = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`

error: expected one of `!`, `(`, `.`, `::`, `;`, `<`, or `?`, found `{`
 --> src/main.rs:9:19
  |
9 |     let _ = Foo:C { x: 1 }; //~ ERROR expected one of
  |                -  ^ expected one of 7 possible tokens
  |                |
  |                help: maybe write a path separator here: `::`
  |
  = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`

error: expected type, found reserved keyword `box`
 --> src/main.rs:2:25
  |
2 |     let _ = Option:Some(vec![0, 1]); //~ ERROR expected type, found
  |                   -     ^^^^^^^^^^
  |                   |     |
  |                   |     expected type
  |                   |     in this macro invocation
  |                   |     this macro call doesn't expand to a type
  |                   help: maybe write a path separator here: `::`
  |
  = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0423]: expected value, found enum `Option`
 --> src/main.rs:2:13
  |
2 |     let _ = Option:Some(vec![0, 1]); //~ ERROR expected type, found
  |             ^^^^^^
  |
help: try using one of the enum's variants
  |
2 |     let _ = std::option::Option::None:Some(vec![0, 1]); //~ ERROR expected type, found
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
2 |     let _ = std::option::Option::Some:Some(vec![0, 1]); //~ ERROR expected type, found
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider importing one of these items instead
  |
1 | use serde::de::Unexpected::Option;
  |
1 | use serde_value::Unexpected::Option;
  |
1 | use serde_value::Value::Option;
  |

error[E0573]: expected type, found variant `Some`
 --> src/main.rs:2:20
  |
2 |     let _ = Option:Some(vec![0, 1]); //~ ERROR expected type, found
  |                    ^^^^^^^^^^^^^^^^ not a type
  |
help: try using the variant's enum
  |
2 |     let _ = Option:core::option::Option; //~ ERROR expected type, found
  |                    ^^^^^^^^^^^^^^^^^^^^
2 |     let _ = Option:futures_core::core_reexport::option::Option; //~ ERROR expected type, found
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 |     let _ = Option:futures_util::core_reexport::option::Option; //~ ERROR expected type, found
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 |     let _ = Option:lzw::Bits; //~ ERROR expected type, found
  |                    ^^^^^^^^^
    and 5 other candidates
help: maybe you meant to write a path separator here
  |
2 |     let _ = Option::Some(vec![0, 1]); //~ ERROR expected type, found
  |                   ^^

error[E0423]: expected value, found enum `Foo`
 --> src/main.rs:5:13
  |
5 |     let _ = Foo:A; //~ ERROR expected `::`, found `:`
  |             ^^^
  |
help: try using one of the enum's variants
  |
5 |     let _ = Foo::A:A; //~ ERROR expected `::`, found `:`
  |             ^^^^^^
5 |     let _ = Foo::B:A; //~ ERROR expected `::`, found `:`
  |             ^^^^^^
5 |     let _ = Foo::C:A; //~ ERROR expected `::`, found `:`
  |             ^^^^^^

error[E0412]: cannot find type `A` in this scope
 --> src/main.rs:5:17
  |
5 |     let _ = Foo:A; //~ ERROR expected `::`, found `:`
  |                 ^ not found in this scope
  |
help: there is an enum variant `crate::Foo::A`; try using the variant's enum
  |
5 |     let _ = Foo:crate::Foo; //~ ERROR expected `::`, found `:`
  |                 ^^^^^^^^^^
help: maybe you meant to write a path separator here
  |
5 |     let _ = Foo::A; //~ ERROR expected `::`, found `:`
  |                ^^
help: you might be missing a type parameter
  |
4 | fn qux<A>() {
  |       ^^^
```

**Comment by petrochenkov** [comment]
> (@petrochenkov I can remove the last commit and not handle those cases in this PR)

Yes, could you split the changes, then I'll get a chance to r+ one of the parts before the return from vacation.

**Comment by estebank** [comment]
I'm offline until Monday, but can do so then. Should I rebase to single commit or into smaller logical changes?

**Comment by estebank** [comment]
Rebased onto a single commit.

File: src/librustc_resolve/late.rs [hunk 5]
```diff
@@ -2160,8 +2160,10 @@ impl<'a, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
                     self.resolve_expr(argument, None);
                 }
             }
-            ExprKind::Type(ref type_expr, _) => {
-                self.diagnostic_metadata.current_type_ascription.push(type_expr.span);
+            ExprKind::Type(ref type_expr, ref ty) => {
+                self.diagnostic_metadata
+                    .current_type_ascription
+                    .push(type_expr.span.between(ty.span));
```
Comment (petrochenkov) [inline src/librustc_resolve/late.rs:2166]: The setup here is very subtle and needs a comment.
`ParseSess::type_ascription_path_suggestions` keeps spans of colon tokens in type ascription.
Here we are trying to retrieve the span of the colon token as well, but only if it's written without spaces `expr:Ty` and therefore confusable with `expr::Ty`, only in this case it will match the span from `type_ascription_path_suggestions`.

File: src/librustc_resolve/late/diagnostics.rs [hunk 6]
```diff
@@ -830,77 +873,79 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
...
-                                .map(|s| s == " ")
-                                .unwrap_or(false)
+                            show_label = false;
+                            if self
+                                .r
+                                .session
+                                .parse_sess
+                                .type_ascription_path_suggestions
+                                .borrow()
+                                .contains(&colon_sp)
```
Comment (petrochenkov) [inline src/librustc_resolve/late/diagnostics.rs:908]: We can check the result of `insert` below instead of doing this `contains` check.
