### PR TITLE
Fix global search

### LINKED ISSUE #46021: [rustdoc] Search regressions
The quality of search results is significantly worse on nightly compared to stable:

### Stable:
str_stable

### Nightly:
str_nightly

### Stable:
thread_stable

### Nightly:
thread_nightly

### Stable:
assert_stable

### Nightly:
assert_nightly

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #46021.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems like it messes with generics.

**Comment by GuillaumeGomez** [comment]
Ok, generics are working again. Added comments to avoid removing the same code again.

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -374,7 +375,7 @@
             var valLower = query.query.toLowerCase(),
                 val = valLower,
                 typeFilter = itemTypeFromName(query.type),
-                results = {},
+                results = {}, results_in_args = {}, results_returned = {},
```
Comment (Havvy) [inline src/librustdoc/html/static/main.js]: Not really an issue with this PR, but I don't like how there's inconsistent `var` styles being used with some functions having one `var` per line, and others using commas like they're going out of style.

File: src/librustdoc/html/static/main.js [hunk 2]
```diff
@@ -385,6 +386,127 @@
                 }
             }
 
+            function transformResults(results, isType) {
+                var out = [];
+                for (i = 0; i < results.length; ++i) {
+                    if (results[i].id > -1) {
+                        var added = false;
+                        var obj = searchIndex[results[i].id];
```
Comment (Havvy) [inline src/librustdoc/html/static/main.js]: What kind of obj is this?

File: src/librustdoc/html/static/main.js [hunk 3]
```diff
@@ -385,6 +386,127 @@
...
+                        obj.lev = results[i].lev;
+                        if (isType !== true || obj.type) {
```
Comment (Havvy) [inline src/librustdoc/html/static/main.js]: Also not really an issue with this PR, but the `isType !== true` in an if thing really isn't saving you any speed of `!isType`.

File: src/librustdoc/html/static/main.js [hunk 4]
```diff
@@ -385,6 +386,127 @@
                 }
             }
 
+            function transformResults(results, isType) {
+                var out = [];
+                for (i = 0; i < results.length; ++i) {
+                    if (results[i].id > -1) {
+                        var added = false;
```
Comment (Havvy) [inline src/librustdoc/html/static/main.js]: This line seems like it was left behind by accident.

File: src/librustdoc/html/static/main.js (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Don't care. In principle it's faster since the comparison is explicit.

File: src/librustdoc/html/static/main.js (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: The same as anywhere else in the code using `searchIndex`? :p How would you name it?

File: src/librustdoc/html/static/main.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: I grouped them by "theme". But if you want I can put each on a line.

File: src/librustdoc/html/static/main.js (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: Good catch!

**Comment by GuillaumeGomez** [comment]
Rebased.

File: src/librustdoc/html/static/main.js [hunk 5]
```diff
@@ -423,14 +545,14 @@
...
                                 elems.splice(lev.pos, 1);
                                 lev_distance = Math.min(lev.lev, lev_distance);
+                                total += lev.lev;
+                                done += 1;
                             } else {
                                 return MAX_LEV_DISTANCE + 1;
                             }
                         }
-                        return lev_distance;
+                        return lev_distance;//Math.ceil(total / done);
```
[the remark this answers is not in the document]
Comment (QuietMisdreavus) [reply src/librustdoc/html/static/main.js]: I can see how returning the average would be better, but i'm not sure how effective it will be. A user would need to search for something with multiple generics (which i'm not sure works right now? a search for `Result<File, Error>` returns a lot of bad lev results before any of the functions that return that type show up) before the difference will even show up. I think we can leave this as-is for now and investigate it in the future.

**Comment by kennytm** [comment]
I suggest we backport this (and possibly #46081 as well) to 1.23-beta, as search is broken on beta as well.

**Comment by QuietMisdreavus** [comment]
I agree - if possible, i'd rather not break the search for docs that show up on stable.

File: src/librustdoc/html/static/main.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/main.js]: I'll leave the comment just in case then if you don't mind.

**Comment by GuillaumeGomez** [comment]
Let's move up the priority then.

@bors: p=10

**Comment by alexcrichton** [comment]
Looks like we forgot to backport this to 1.23.0 (sorry about that!) so removing beta tags

**Comment by alexcrichton** [comment]
Er sorry looks like this was backported in https://github.com/rust-lang/rust/pull/46886
