### PR TITLE
Fix diagnostic when using = instead of : in let binding

### LINKED ISSUE #133713: Poor diagnostic when using = instead of : in let bindings
### Code

```Rust
1.

let last = u64 = 0;

2.

let val = u64;
```

### Current output

```Shell
1

error[E0423]: expected value, found builtin type `u64`
  --> src/main.rs:21:24
   |
21 |         let last = u64 = 0;
   |                        ^^^
   |
help: you might have meant to introduce a new binding
   |
21 |         let last = let u64 = 0;
   |                        +++


2. 

error[E0423]: expected value, found builtin type `u64`
  --> src/main.rs:21:20
   |
21 |         let last = u64;
   |                    ^^^ not a value
```

### Desired output

```Shell
1:

error[E0423]: expected value, found builtin type `u64`
  --> src/main.rs:21:24
   |
21 |         let last = u64 = 0;
   |                        ^^^
   |
help: you might have meant to use `:` instead of `=`
   |
21 |         let last:  u64 = 0;
   |                 +
note: type annotations use `:` instead of `=` (https://doc.rust-lang.org/reference/statements.html#expression-statements)

2. 

error[E0423]: expected value, found builtin type `u64`
  --> src/main.rs:21:20
   |
21 |         let last = u64;
   |                    ^^^ not a value
help: you might have meant to use `:` instead of `=`
note: type annotations use `:` instead of `=` (https://doc.rust-lang.org/reference/statements.html#expression-statements)
```

### Rationale and extra context

This is a silly mistake to make and also simple to detect and autofix.

### Other cases

```Rust

```

### Rust Version

```Shell
1.85.0-nightly (4c39aaff6 2024-11-25)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #133713

r? @estebank

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -2347,26 +2347,47 @@ impl<'ast, 'ra: 'ast, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
...
+                );
+                return true;
+            } else {
+                // a special case for #133713
+                // '=' maybe a typo of `:`, which is a type annotation instead of assignment
+                if err.code == Some(E0423)
+                    && let Some((let_span, _, _)) = self.diag_metadata.current_let_binding
+                    && let span = let_span.shrink_to_hi().to(ident_span.shrink_to_lo())
+                    && let Ok(code) = self.r.tcx.sess.source_map().span_to_snippet(span)
+                    && code.trim() == "="
```
Comment (estebank) [inline compiler/rustc_resolve/src/late/diagnostics.rs:2380]: Is there no alternative way of doing this? We don't have info on the expression/AST node? Wouldn't `self.diag_metadata.current_let_binding.2` point at the space after the `=`, which could be compared against the span you already have?

Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: you means checking the `ident_span` is starting point of `current_let_binding.2.span`?
I updated the code.

**Comment by workingjubilee** [comment]
sequences with another PR

@bors p=1
