### PR TITLE
coverage: Overhaul validation of the `#[coverage(..)]` attribute

### LINKED ISSUE #126658: Inconsistent handling of `#[coverage(..)]` attributes that are malformed or misplaced
*(Note: The coverage attribute is currently unstable; see #84605.)*

While writing tests for `#[coverage(..)]` for #84605, I encountered various inconsistencies in diagnostics for using the attribute with incorrect syntax or on inappropriate items.

For example:
- Bare `#[coverage]` is silently permitted in various situations, even though it should never be legal.
  - E.g. on modules, on `impl` blocks, on `trait`, and on `impl Trait`.
- Using name-value syntax `#[coverage = "off"]` results in different error messages than other kinds of incorrect syntax, and sometimes results in multiple errors for the same attribute.
  - The error message also claims that bare `#[coverage]` is permitted, which is incorrect.
- Using `#[coverage(off)]` or `#[coverage(on)]` on things other than functions/methods/closures sometimes results in an error, and sometimes only a warning.
  - It seems to be an error on inappropriate items, but only a warning on (non-closure) expressions, even though it would have no effect in either case.
- There is no diagnostic for attaching multiple otherwise legal coverage annotations to a single item, even though it's unclear which one would prevail.

### PR DESCRIPTION
**Pull request by Zalathar**
This PR makes sweeping changes to how the (currently-unstable) coverage attribute is validated:
- Multiple coverage attributes on the same item/expression are now treated as an error.
- The attribute must always be `#[coverage(off)]` or `#[coverage(on)]`, and the error messages for this are more consistent.
  -  A trailing comma is still allowed after off/on, since that's part of the normal attribute syntax.
- Some places that silently ignored a coverage attribute now produce an error instead.
  - These cases were all clearly bugs.
- Some places that ignored a coverage attribute (with a warning) now produce an error instead.
  - These were originally added as lints, but I don't think it makes much sense to knowingly allow new attributes to be used in meaningless places.
  - Some of these errors might soon disappear, if it's easy to extend recursive coverage attributes to things like modules and impl blocks.

---

One of the goals of this PR is to lay a more solid foundation for making the coverage attribute recursive, so that it applies to all nested functions/closures instead of just the one it is directly attached to.

Fixes #126658.

This PR incorporates #126659, which adds more tests for validation of the coverage attribute.

@rustbot label +A-code-coverage

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler

File: tests/ui/coverage-attr/word-only.rs [hunk 1]
```diff
@@ -0,0 +1,50 @@
+#![feature(coverage_attribute)]
+//@ edition: 2021
+
+// Demonstrates the diagnostics produced when using the syntax `#![coverage]`,
+// which should not be allowed.
```
Comment (lcnr) [inline tests/ui/coverage-attr/word-only.rs:5]: That test description seems wrong? Isn't it more about applying the attribute to the wrong item?

File: compiler/rustc_parse/src/validate_attr.rs [hunk 2]
```diff
@@ -149,7 +149,9 @@ pub fn check_builtin_meta_item(
 ) {
     // Some special attributes like `cfg` must be checked
     // before the generic check, so we skip them here.
-    let should_skip = |name| name == sym::cfg;
+    // Coverage attributes are checked by the `check_attr` pass, which gives
+    // better error messages.
+    let should_skip = |name| name == sym::cfg || name == sym::coverage;
```
Comment (lcnr) [inline compiler/rustc_parse/src/validate_attr.rs:154]: this feels undesirable to me 🤔 I feel like skipping attributes here can easily result in accidentally not checking something if the builtin attr definition ever changes.

I feel like if the error message isn't good enough with the automatic meta item check, that check should be improved/customizeable instead of disabling it and writing it by hand.

File: tests/ui/coverage-attr/word-only.rs (hunk 1 above)
Comment (Zalathar) [reply tests/ui/coverage-attr/word-only.rs:5]: This particular test is mainly about testing the error for `#[coverage]` in a variety of scenarios, most of which also happen to not permit coverage attributes of any kind.

It's motivated by the fact that the existing implementation was very inconsistent about how it handled this particular error case, giving different error messages in different places, and in some cases not issuing an error at all.

(Side note: I notice that I have an extra `!` that shouldn't be here.)

File: compiler/rustc_parse/src/validate_attr.rs (hunk 2 above)
Comment (Zalathar) [reply compiler/rustc_parse/src/validate_attr.rs:154]: That's fair.

Currently the syntax is still checked in `check_attr`, and is covered by tests, but I can look into what it would take to give good checking/errors directly in the parse layer.

**Comment by Zalathar** [comment]
Tweaked test comments [(diff)](https://github.com/rust-lang/rust/compare/435eb301292250a6960b585d103ae06cb120ed8b..01954ad55498b615242318abbfc5ede6f0a4d590).

**Comment by Zalathar** [comment]
Switched to checking the off/on syntax in `validate_attr` [(diff)](https://github.com/rust-lang/rust/compare/01954ad55498b615242318abbfc5ede6f0a4d590..4150ce6193e31d10d16ba35c94214bab766c87ae).

I think the error messages are a bit worse, but it's better integrated into the existing attribute syntax-checking, so I'm content to leave further improvements for later.

File: compiler/rustc_parse/src/validate_attr.rs [hunk 3]
```diff
@@ -132,9 +133,13 @@ pub(super) fn check_cfg_attr_bad_delim(psess: &ParseSess, span: DelimSpan, delim
 
 /// Checks that the given meta-item is compatible with this `AttributeTemplate`.
 fn is_attr_template_compatible(template: &AttributeTemplate, meta: &ast::MetaItemKind) -> bool {
+    let is_one_allowed_subword = |items: &[NestedMetaItem]| match items {
+        [item] => template.one_of.iter().any(|&word| item.is_word() && item.has_name(word)),
```
Comment (lcnr) [inline compiler/rustc_parse/src/validate_attr.rs:137]:
```suggestion
        [item] => item.is_word() && template.one_of.iter().any(|&word| item.has_name(word)),
```
r=me after nit

**Comment by Zalathar** [comment]
Addressed nit [(diff)](https://github.com/rust-lang/rust/compare/9ea27b1c90c5e6ef5a1296fb36c8fca6669b94df..1f4c57b948459da108f221096ae238fbf7edb539).

(I haven't been able to construct a test that actually *requires* the `is_word` check, since `#[coverage(off(foo))]` seems to be rejected even without it, but I'll err on the side of caution and leave it in.)

**Comment by Zalathar** [comment]
Rebased after conflict; no changes.

**Comment by lcnr** [comment]
thanks

@bors r+ rollup
