### PR TITLE
Replace fragile erroneous const sys

### LINKED ISSUE #67191: Replace our fragile safety scheme around erroneous constants
Discussion: https://github.com/rust-lang/rust/pull/67134#discussion_r355899976

The situation is as follows:

1. Sometimes code relies on a failing constant for safety (see https://github.com/rust-lang/rust/issues/67083)
2. Those failing constants may have a ZST type (e.g. `()`)
3. A MIR optimization may see the constant and optimize it out (this happened: https://github.com/rust-lang/rust/pull/66216)
4. The constant not showing up in MIR can cause it to never get evaluated, thus never reporting its error
5. The runtime code relying on safety by having a hard error during const eval is now being executed even though it's unsound

The proposed solution is to gather all unevaluated constants in a MIR right after mir building and put them in a `Vec<(DefId, SubstsRef<'tcx>, Promoted)>` (or maybe a `HashSet`?). This should be placed on the `mir::Body` and inlining should also carry it down to the function that its being inlined into (and adjust substitutions on the `SubstsRef`). In the end, instead of having the collector go through the MIR to find constants to evaluate, we go through the vector and evaluate all of them.

This will require more memory and some additional evaluation time, but it would be significantly less fragile than the current setup which relies on optimizations not removing even guaranteed dead code containing constants.

cc @RalfJung @wesleywiser

### PR DESCRIPTION
**Pull request by spastorino**
Closes #67191

r? @oli-obk

### CODE REVIEW

File: src/librustc_codegen_ssa/mir/mod.rs [hunk 1]
```diff
@@ -190,6 +191,18 @@ pub fn codegen_mir<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>>(
 
     fx.per_local_var_debug_info = fx.compute_per_local_var_debug_info();
 
+    for const_ in &mir.uneval_consts {
```
Comment (Centril) [inline src/librustc_codegen_ssa/mir/mod.rs:194]: Assuming this PR is addressing https://github.com/rust-lang/rust/issues/67191, it seems like the way this PR is setup, then `cargo check` (`--emit metadata`) would not trigger an error here but it should. In other words, erroneous live constants should be caught in *analysis* before optimizations.

File: src/librustc_mir/transform/uneval_const_set.rs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+struct UnevalConstSetVisitor<'a, 'tcx> {
+    tcx: TyCtxt<'tcx>,
+    uneval_consts: &'a mut Vec<Constant<'tcx>>,
+}
+
+impl<'a, 'tcx> UnevalConstSetVisitor<'a, 'tcx> {
+    pub fn new(tcx: TyCtxt<'tcx>, uneval_consts: &'a mut Vec<Constant<'tcx>>) -> Self {
+        UnevalConstSetVisitor { tcx, uneval_consts }
+    }
+}
```
Comment (Centril) [inline src/librustc_mir/transform/uneval_const_set.rs:26]: Seems unnecessary; I'd just inline the construction here since it's used once.

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: yea, we need to go through this list in the collector, too, just like we're doing with in-MIR constants right now. This may get solved automatically by extending the mir visitors to go through the constants in the list via `visit_const`

Comment (spastorino) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: Added this here https://github.com/rust-lang/rust/pull/70820/commits/2f8c3b5c9ed83f704505804bb6f44a810184cd08

File: src/librustc_mir/transform/uneval_const_set.rs (hunk 2 above)
Comment (spastorino) [reply src/librustc_mir/transform/uneval_const_set.rs:26]: Do you meant me to remove the function and move the construction of the visitor above?. I can do that, it's more or less the same to me :).

**Comment by spastorino** [comment]
@oli-obk I'm not sure if this https://github.com/rust-lang/rust/pull/70820/commits/6b158c6f75f75e19221952ea24c43725b856a34e is all the stuff we need to cleanup or there's more.

File: src/librustc_mir/monomorphize/collector.rs [hunk 3]
```diff
@@ -511,6 +512,15 @@ impl<'a, 'tcx> MirNeighborCollector<'a, 'tcx> {
 }
 
 impl<'a, 'tcx> MirVisitor<'tcx> for MirNeighborCollector<'a, 'tcx> {
+    fn visit_body(&mut self, body: &Body<'tcx>) {
+        for const_ in &body.uneval_consts {
+            let location = mir::START_BLOCK.start_location();
```
Comment (oli-obk) [inline src/librustc_mir/monomorphize/collector.rs:517]: this may cause some diagnostics regressions, not sure.

Comment (oli-obk) [reply src/librustc_mir/monomorphize/collector.rs:517]: can you check all implementors of `visit_constant` and how they use `location`? We may be able to remove the argument (separate PR in that case) or we'll have to start storing the location together with the constant in the vector.

File: src/librustc_mir/transform/simplify.rs [hunk 4]
```diff
@@ -371,16 +371,8 @@ impl<'a, 'tcx> Visitor<'tcx> for DeclMarker<'a, 'tcx> {
...
-                                // Keep assignments from unevaluated constants around, since the
-                                // evaluation may report errors, even if the use of the constant
-                                // is dead code.
-                                ty::ConstKind::Unevaluated(..) => {}
-                                _ => {
-                                    trace!("skipping store of const value {:?} to {:?}", c, dest);
-                                    return;
-                                }
-                            }
+                            trace!("skipping store of const value {:?} to {:?}", c, dest);
```
Comment (oli-obk) [inline src/librustc_mir/transform/simplify.rs:374]: cc @wesleywiser Do you remember if we have any other hacks like this?

File: src/librustc_mir/transform/uneval_const_set.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_mir/transform/uneval_const_set.rs:26]: Yes, that. :)

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: @oli-obk I don't follow how this was resolved. The code was added to monomorphization logic, but presumably that never runs if we don't reach codegen?

File: src/librustc_mir/transform/simplify.rs (hunk 4 above)
Comment (wesleywiser) [reply src/librustc_mir/transform/simplify.rs:374]: This is the only one I know of.

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: I don't see how `cargo check` can trigger an error on these *without* monomorphization. If you look at the test that we're doing all these changes for (https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/assoc_const_generic_impl.rs) you see that without monomorphization we can't possibly report anything. This is inherently a monomorphization time thing.

Comment (oli-obk) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: this applies to all other lints reported during mir optimizations, too. Const prop lints for example aren't triggered reliably from `cargo check`. Only if the `optimized_mir` query is called for a function, will const prop lints actually get reported. We could add `optimized_mir` runs for all functions to the analysis query though. In that case we'd also do a best effort evaluation of all constants

Comment (oli-obk) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: Note that I feel that running `optimized_mir` on all functions for `analysis` is an orthogonal discussion to this PR and we should probably move it to an issue if you think this is a useful thing to do at all (it will make `cargo check` take more time as optimizations are run)

Comment (Centril) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: Well this is all very unfortunate... I had neglected associated constants. With them in mind, the options as I see them are:

1. Error differently for polymorphic and monomorphic constants, doing the former post-monomorphization, and the latter pre-monomorphization (inconsistent).

2. Error for both post-monomorphization. (I consider all post-monomorphization errors to be language design bugs.)

3. Error for neither and insert a trap in codegen, but @RalfJung [would probably be even more unhappy about that](https://github.com/rust-lang/rust/pull/67134#discussion_r355697861).

4. Only insert a trap for polymorphic constants (inconsistent).

File: src/librustc_mir/monomorphize/collector.rs (hunk 3 above)
Comment (spastorino) [reply src/librustc_mir/monomorphize/collector.rs:517]: I've added a "fake" location because if I'm not wrong it's not used.
See https://github.com/rust-lang/rust/pull/70820/files#diff-d583e4efe1a72516e274158e53223633L592

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: We are doing 1. right now. Erroring post monomorphization for associated constants is what we do to keep our APIs sane. Otherwise we'd need integer range bounds and more just to be able to do simple addition of associated constants inside other associated constants.

I don't like 3 and 4 and am not even sure that 2. is implementable :rofl: 

What we could do at some point in the future is to create a lint that tells you about sites where post monomorphization errors could occur depending on the generic parameters that were given, but that would require symbolic execution of constants and some sort of solver (not necessarily SAT) for them. While that is something we need for more advanced const generics trickeries anyway, I think we can just stay with option 1 until we address post monomorphization errors in general.

File: src/librustc_mir/monomorphize/collector.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc_mir/monomorphize/collector.rs:517]: in that case we can remove the argument from the visitor :)

Comment (spastorino) [reply src/librustc_mir/monomorphize/collector.rs:517]: I meant that is not used in this particular implementation of the visitor. There are cases like https://github.com/rust-lang/rust/blob/6b158c6f75f75e19221952ea24c43725b856a34e/src/librustc_mir/borrow_check/type_check/mod.rs#L297 that uses the location.

File: src/librustc_mir/transform/uneval_const_set.rs (hunk 2 above)
Comment (spastorino) [reply src/librustc_mir/transform/uneval_const_set.rs]: Done

File: src/librustc_codegen_ssa/mir/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_codegen_ssa/mir/mod.rs:194]: > We are doing 1. right now. Erroring post monomorphization for associated constants is what we do to keep our APIs sane. Otherwise we'd need integer range bounds and more just to be able to do simple addition of associated constants inside other associated constants.

Yea, this is going to be ungreat for the language spec and inconsistent, but of the bad choices I suppose it's the least bad (😭), so do your thing. :)

File: src/librustc_mir/monomorphize/collector.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc_mir/monomorphize/collector.rs:517]: oh. I completely failed to realize that this is not the `walk_body` method. I think we should/must run this for all visitors by default. So you should move this impl to the `Visitor` trait impl

Comment (bjorn3) [reply src/librustc_mir/monomorphize/collector.rs:517]: If the constant references a static, that static shouldn't be codegened, only evaluated.

File: src/librustc_mir/transform/inline.rs [hunk 5]
```diff
@@ -125,6 +125,13 @@ impl Inliner<'tcx> {
                     continue;
                 };
 
+                // Copy unevaluated constants
+                let mut callee_uneval_consts = callee_body.uneval_consts.clone();
+                callee_uneval_consts.retain(|&constant| {
+                    matches!(constant.literal.val, ConstKind::Unevaluated(_, _, _))
+                });
+                caller_body.uneval_consts.extend(callee_uneval_consts);
```
Comment (bjorn3) [inline src/librustc_mir/transform/inline.rs:133]:
```suggestion
                caller_body.uneval_consts.extend(callee_body.uneval_consts.iter().copied().filter(|&constant| {
                    matches!(constant.literal.val, ConstKind::Unevaluated(_, _, _))
                });
```

File: src/librustc_mir/transform/mod.rs [hunk 6]
```diff
@@ -280,6 +281,8 @@ fn run_optimization_passes<'tcx>(
             &remove_noop_landing_pads::RemoveNoopLandingPads,
             &cleanup_post_borrowck::CleanupNonCodegenStatements,
             &simplify::SimplifyCfg::new("early-opt"),
+            // Gather Unevaluated consts to evaluate them regardless of being optimized out
+            &uneval_const_set::UnevalConstSet,
```
Comment (bjorn3) [inline src/librustc_mir/transform/mod.rs:285]: The previous passes can remove constants from unreachable blocks, right?

File: src/librustc_mir/transform/inline.rs (hunk 5 above)
Comment (spastorino) [reply src/librustc_mir/transform/inline.rs]: Thanks, I've done a rebase on my branch and applied this.

File: src/librustc_mir/transform/mod.rs (hunk 6 above)
Comment (spastorino) [reply src/librustc_mir/transform/mod.rs]: You're right but at the same time I've removed that code :).

File: src/librustc_mir/transform/simplify.rs (hunk 4 above)
Comment (spastorino) [reply src/librustc_mir/transform/simplify.rs]: I've applied only this to the way the code looks now ...

File: src/librustc_mir/monomorphize/collector.rs (hunk 3 above)
Comment (spastorino) [reply src/librustc_mir/monomorphize/collector.rs:521]: Going to resolve this conversation too because this code is not in the PR anymore.

**Comment by spastorino** [comment]
Once working and accepted this should not be rolled up.

@bors rollup=never

**Comment by wesleywiser** [comment]
Let's do a perf run just to make sure this doesn't have any negative effects (and hopefully some positive ones).

@bors try @rust-timer queue

File: src/librustc_middle/mir/mod.rs [hunk 7]
```diff
@@ -155,6 +155,9 @@ pub struct Body<'tcx> {
     /// A span representing this MIR, for error reporting.
     pub span: Span,
 
+    /// Unevaluated consts to evaluate them regardless of being optimized out
+    pub uneval_consts: Vec<Constant<'tcx>>,
```
Comment (RalfJung) [inline src/librustc_middle/mir/mod.rs:159]: Is "unevaluated" really accurate here? Aren't these just all the constants used in this function? (That is a scheme we considered in https://github.com/rust-lang/rust/issues/67191, and then maybe making consts inside the body refer to this `Vec` by index.)

Comment (RalfJung) [reply src/librustc_middle/mir/mod.rs:159]: Oh I see, we collect all `ConstKind::Unevaluated` into this.
Is there a good way to say in terms of surface Rust which constants these are? Like, does it include all uses of `const` items, but *not* include literals as in `1`?

Comment (spastorino) [reply src/librustc_middle/mir/mod.rs:159]: @RalfJung from what you've said I ended thinking it would be great if we can document each of those `ConstKind` things. To be honest I can't answer 100% clear about each of the different constants, I know that Unevaluated are the ones left unevaluated until post monomorphization, the rest are already evaluated so not related to this issue.

Anyway cc @oli-obk, would be great if we can document this data structure with examples and also other data structures :).

File: src/librustc_mir/monomorphize/collector.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc_mir/monomorphize/collector.rs:521]: Imo this code addition should be in `super_body` in the generic visitor and not in the collector.

Comment (spastorino) [reply src/librustc_mir/monomorphize/collector.rs:521]: :+1:

File: src/test/mir-opt/retain-never-const/rustc.no_codegen.PreCodegen.after.mir [hunk 8]
```diff
@@ -2,20 +2,10 @@
...
-        _1 = const PrintName::<T>::VOID; // bb0[1]: scope 0 at $DIR/retain-never-const.rs:19:13: 19:33
-                                         // ty::Const
-                                         // + ty: !
-                                         // + val: Unevaluated(DefId(0:9 ~ retain_never_const[317d]::{{impl}}[0]::VOID[0]), [T], None)
-                                         // mir::Constant
-                                         // + span: $DIR/retain-never-const.rs:19:13: 19:33
-                                         // + user_ty: UserType(0)
-                                         // + literal: Const { ty: !, val: Unevaluated(DefId(0:9 ~ retain_never_const[317d]::{{impl}}[0]::VOID[0]), [T], None) }
-        unreachable;                     // bb0[2]: scope 0 at $DIR/retain-never-const.rs:19:13: 19:33
+        unreachable;                     // bb0[0]: scope 0 at $DIR/retain-never-const.rs:19:13: 19:33
```
Comment (wesleywiser) [inline src/test/mir-opt/retain-never-const/rustc.no_codegen.PreCodegen.after.mir:9]: This test should probably be renamed.

File: src/librustc_middle/mir/mod.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc_middle/mir/mod.rs:159]: That entirely depends on the point where you are in the optimization pipeline. Ideally we'd only have constants that are too generic to be evaluated, but at this point we include all non-literal constants.

Comment (RalfJung) [reply src/librustc_middle/mir/mod.rs:159]: "this point" is not anywhere in the pipeline, this is the data structure that is used throughout the pipeline. Optimizations don't remove entries from here even when they optimize MIR to contain evaluated consts, right?

Maybe `referred_consts` or so would be a better name? There's no type for the `(DefId, SubstsRef<'tcx>, Option<Promoted>)` triple that we could use here to ensure that this only stores unevaluated consts, is there?

Comment (oli-obk) [reply src/librustc_middle/mir/mod.rs:159]: `so_far_unevaluable_constants` is what it is supposed to be. We can remove any constants at any point where they are evaluable.

I don't want to use that triple, as ideally some day in the future we can do the MIR 2.0 change of making this an `IndexVec` and referring to all constants indirectly via index instead of storing them inline in the MIR datastructures.

Comment (RalfJung) [reply src/librustc_middle/mir/mod.rs:159]: > `so_far_unevaluable_constants`

More like `unevaluated`? Still, that's it very informative.

What about `required_const`, with doc comment  like "constants that are required to evaluated successfully for this MIR to be well-formed".

> I don't want to use that triple,

Fair.

File: src/test/mir-opt/retain-never-const/rustc.no_codegen.PreCodegen.after.mir (hunk 8 above)
Comment (spastorino) [reply src/test/mir-opt/retain-never-const/rustc.no_codegen.PreCodegen.after.mir]: Done!

File: src/librustc_middle/mir/mod.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc_middle/mir/mod.rs:159]: > What about required_consts, with a doc comment like "constants that are required to evaluate successfully for this MIR to be well-formed".

I like that

Comment (spastorino) [reply src/librustc_middle/mir/mod.rs]: Done

File: src/librustc_mir/transform/inline.rs [hunk 9]
```diff
@@ -123,6 +123,13 @@ impl Inliner<'tcx> {
                     continue;
                 };
 
+                // Copy unevaluated constants
+                caller_body.required_consts.extend(
+                    callee_body.required_consts.iter().copied().filter(|&constant| {
+                        matches!(constant.literal.val, ConstKind::Unevaluated(_, _, _))
```
Comment (RalfJung) [inline src/librustc_mir/transform/inline.rs:129]: We never add anything non-`Unevaluated` in there, do we?

Comment (spastorino) [reply src/librustc_mir/transform/inline.rs]: Fixed.

Comment (oli-obk) [reply src/librustc_mir/transform/inline.rs]: No, but the above `subst_and_normalize_erasing_regions` may be able to evaluate a constant now. So after that we don't need to add it.

Comment (spastorino) [reply src/librustc_mir/transform/inline.rs]: Right I wasn't remembering why I've added that check, good to also add a comment explaining that.

**Comment by spastorino** [comment]
CI error is because of Github issues, closing and opening the issue to fire CI again.

**Comment by spastorino** [comment]
Rebased again.

@bors r=oli-obk

**Comment by nnethercote** [comment]
This was a major perf win for `ctfe-stress-4`, both for [wall time (best of -34%)](https://perf.rust-lang.org/compare.html?start=ce93331e2cf21ac4b72a53854b105955919114e7&end=0286d6e53b827433713c635f0b76d9d03ccb9ba0&stat=wall-time) and even more for [max-rss (best of -69%)](https://perf.rust-lang.org/compare.html?start=ce93331e2cf21ac4b72a53854b105955919114e7&end=0286d6e53b827433713c635f0b76d9d03ccb9ba0&stat=max-rss)

**Comment by RalfJung** [comment]
Interesting. @oli-obk @spastorino  Is that expected or does this indicate we are failing to do some work now that we should be doing?

**Comment by oli-obk** [comment]
That's very curious. I wouldn't have thought this to have any impact on perf. We're not doing the optimizations yet that would have a positive perf impact, so idk what's going on here. I'm doing another review round now with this in mind

**Comment by oli-obk** [comment]
Ok so I thought what's happening:

1. All assignments of `()` type get removed from MIR
2. The inliner eagerly evaluates all constants while inlining
3. These eagerly evaluated constants don't cause more calls to the `const_eval` query.

But then I wondered how this would reduce just the *time* `const_eval_raw` takes, instead of the number of times it is executed. Then I remembered that there are many many `const fn` in those stress tests. So what we've managed to do is reduce the amount of work done by CTFE when evaluating a constant that calls a `const fn` that has loads of variables of `()` type that are assigned from constants.

Looking at https://github.com/rust-lang/rustc-perf/blob/master/collector/benchmarks/ctfe-stress-4/src/lib.rs I believe this is a resonable explanation.
