### PR TITLE
Fail relating constants of different types

### LINKED ISSUE #121585: ICE: `FloatToFloat/FloatToInt cast: source type usize is not a float type`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

trait Trait {}

struct HasCastInTraitImpl<const N: usize, const M: u128>;
impl<const O: f64> Trait for HasCastInTraitImpl<O, { O as u128 }> {}

pub fn use_trait_impl() {
    fn assert_impl<T: Trait>() {}

    assert_impl::<HasCastInTraitImpl<13, 13>>();
}


````

original:
````rust
//@ check-pass
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

trait Trait {}
pub struct EvaluatableU128<const N: u128>;

struct HasCastInTraitImpl<const N: usize, const M: u128>;
impl<const O: f64> Trait for HasCastInTraitImpl<O, { O as u128 }> {}

pub fn use_trait_impl<const N: usize>() where EvaluatableU128<{N as u128}>:, {
    fn assert_impl<T: Trait>() {}

    assert_impl::<HasCastInTraitImpl<N, { N as u128 }>>();
    assert_impl::<HasCastInTraitImpl<N, { N as _ }>>();
    assert_impl::<HasCastInTraitImpl<12, { 12 as u128 }>>();
    assert_impl::<HasCastInTraitImpl<13, 13>>();
}
pub fn use_trait_impl_2<const N: usize>() where EvaluatableU128<{N as _}>:, {
    fn assert_impl<T: Trait>() {}

    assert_impl::<HasCastInTraitImpl<N, { N as u128 }>>();
    assert_impl::<HasCastInTraitImpl<N, { N as _ }>>();
    assert_impl::<HasCastInTraitImpl<12, { 12 as u128 }>>()const NUM: u8 = xyz();
    assert_impl::<HasCastInTraitImpl<13, 13>>();
}


fn main() {}

````

Version information
````
rustc 1.78.0-nightly (2ae1bb671 2024-02-24)
binary: rustc
commit-hash: 2ae1bb671183a072b54ed8ed39abfcd72990a3e7
commit-date: 2024-02-24
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:12:2
   |
12 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs`

error: the constant `O` is not of type `usize`
 --> /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:6:30
  |
6 | impl<const O: f64> Trait for HasCastInTraitImpl<O, { O as u128 }> {}
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `f64`
  |
note: required by a bound in `HasCastInTraitImpl`
 --> /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:5:27
  |
5 | struct HasCastInTraitImpl<const N: usize, const M: u128>;
  |                           ^^^^^^^^^^^^^^ required by this bound in `HasCastInTraitImpl`

error: `f64` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:6:15
  |
6 | impl<const O: f64> Trait for HasCastInTraitImpl<O, { O as u128 }> {}
  |               ^^^
  |
  = note: the only supported types are integers, `bool` and `char`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/cast.rs:190:17: Can't cast 'Float' type into u128

thread 'rustc' panicked at compiler/rustc_middle/src/util/bug.rs:35:44:
Box<dyn Any>
stack backtrace:
   0:     0x7f325cd8caf6 - std::backtrace_rs::backtrace::libunwind::trace::h78e1beabc241470d
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f325cd8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::hcf0e3276676937a9
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f325cd8caf6 - std::sys_common::backtrace::_print_fmt::h97e735845ccdd467
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f325cd8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8e5712cf7013f6fb
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f325cddda7c - core::fmt::rt::Argument::fmt::heb6e69b80afbd30f
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/core/src/fmt/rt.rs:142:9
   5:     0x7f325cddda7c - core::fmt::write::hdc6decd8b058c5bd
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f325cd8142f - std::io::Write::write_fmt::h842bc593311134e9
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/io/mod.rs:1846:15
   7:     0x7f325cd8c8a4 - std::sys_common::backtrace::_print::h943a0b890de28a0e
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f325cd8c8a4 - std::sys_common::backtrace::print::hb82258756379bede
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f325cd8f5eb - std::panicking::default_hook::{{closure}}::h19d49c5a8abcf1fa
  10:     0x7f325cd8f339 - std::panicking::default_hook::h0b641f1f8c9de2bf
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/panicking.rs:292:9
  11:     0x7f325fc8bcdc - std[1167999404bd111b]::panicking::update_hook::<alloc[530719d21e18248f]::boxed::Box<rustc_driver_impl[221cda1307b92b70]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f325cd8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9256970e3d77e3fc
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/alloc/src/boxed.rs:2030:9
  13:     0x7f325cd8fd50 - std::panicking::rust_panic_with_hook::hd08646cb5d109a5b
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/panicking.rs:783:13
  14:     0x7f325fcb87f4 - std[1167999404bd111b]::panicking::begin_panic::<rustc_errors[430cc2d97f9a0eb3]::ExplicitBug>::{closure#0}
  15:     0x7f325fcb5446 - std[1167999404bd111b]::sys_common::backtrace::__rust_end_short_backtrace::<std[1167999404bd111b]::panicking::begin_panic<rustc_errors[430cc2d97f9a0eb3]::ExplicitBug>::{closure#0}, !>
  16:     0x7f325fcb0c06 - std[1167999404bd111b]::panicking::begin_panic::<rustc_errors[430cc2d97f9a0eb3]::ExplicitBug>
  17:     0x7f325fcc21e1 - <rustc_errors[430cc2d97f9a0eb3]::diagnostic::BugAbort as rustc_errors[430cc2d97f9a0eb3]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f326009a8bc - <rustc_errors[430cc2d97f9a0eb3]::DiagCtxt>::bug::<alloc[530719d21e18248f]::string::String>
  19:     0x7f326013f55b - rustc_middle[2fef699d51b04cde]::util::bug::opt_span_bug_fmt::<rustc_span[dca1c35612e9799e]::span_encoding::Span>::{closure#0}
  20:     0x7f3260122daa - rustc_middle[2fef699d51b04cde]::ty::context::tls::with_opt::<rustc_middle[2fef699d51b04cde]::util::bug::opt_span_bug_fmt<rustc_span[dca1c35612e9799e]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f3260122c48 - rustc_middle[2fef699d51b04cde]::ty::context::tls::with_context_opt::<rustc_middle[2fef699d51b04cde]::ty::context::tls::with_opt<rustc_middle[2fef699d51b04cde]::util::bug::opt_span_bug_fmt<rustc_span[dca1c35612e9799e]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f325e55e940 - rustc_middle[2fef699d51b04cde]::util::bug::bug_fmt
  23:     0x7f3261ef5e68 - rustc_const_eval[e5663af8bd04b20a]::const_eval::eval_queries::eval_body_using_ecx::{closure#0}
  24:     0x7f3261e76723 - rustc_const_eval[e5663af8bd04b20a]::const_eval::eval_queries::eval_in_interpreter
  25:     0x7f32613f6572 - rustc_const_eval[e5663af8bd04b20a]::const_eval::eval_queries::eval_to_allocation_raw_provider
  26:     0x7f32613f6340 - rustc_query_impl[2d7a486b3b483e50]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d7a486b3b483e50]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 24usize]>>
  27:     0x7f3261a0fed1 - rustc_query_system[cca60478b9b5cf0a]::query::plumbing::try_execute_query::<rustc_query_impl[2d7a486b3b483e50]::DynamicConfig<rustc_query_system[cca60478b9b5cf0a]::query::caches::DefaultCache<rustc_middle[2fef699d51b04cde]::ty::ParamEnvAnd<rustc_middle[2fef699d51b04cde]::mir::interpret::GlobalId>, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[2d7a486b3b483e50]::plumbing::QueryCtxt, false>
  28:     0x7f3261a0faac - rustc_query_impl[2d7a486b3b483e50]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f3261a119d4 - rustc_const_eval[e5663af8bd04b20a]::const_eval::valtrees::eval_to_valtree
  30:     0x7f3261a117e2 - <rustc_const_eval[e5663af8bd04b20a]::provide::{closure#0} as core[2d5c3c55c032a2b6]::ops::function::FnOnce<(rustc_middle[2fef699d51b04cde]::ty::context::TyCtxt, rustc_middle[2fef699d51b04cde]::ty::ParamEnvAnd<rustc_middle[2fef699d51b04cde]::mir::interpret::GlobalId>)>>::call_once
  31:     0x7f3261a117b6 - rustc_query_impl[2d7a486b3b483e50]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d7a486b3b483e50]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 24usize]>>
  32:     0x7f3261a11773 - <rustc_query_impl[2d7a486b3b483e50]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[2d5c3c55c032a2b6]::ops::function::FnOnce<(rustc_middle[2fef699d51b04cde]::ty::context::TyCtxt, rustc_middle[2fef699d51b04cde]::ty::ParamEnvAnd<rustc_middle[2fef699d51b04cde]::mir::interpret::GlobalId>)>>::call_once
  33:     0x7f3261a0ffac - rustc_query_system[cca60478b9b5cf0a]::query::plumbing::try_execute_query::<rustc_query_impl[2d7a486b3b483e50]::DynamicConfig<rustc_query_system[cca60478b9b5cf0a]::query::caches::DefaultCache<rustc_middle[2fef699d51b04cde]::ty::ParamEnvAnd<rustc_middle[2fef699d51b04cde]::mir::interpret::GlobalId>, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[2d7a486b3b483e50]::plumbing::QueryCtxt, false>
  34:     0x7f3261a0f8ac - rustc_query_impl[2d7a486b3b483e50]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f3261a0f0be - rustc_middle[2fef699d51b04cde]::query::plumbing::query_get_at::<rustc_query_system[cca60478b9b5cf0a]::query::caches::DefaultCache<rustc_middle[2fef699d51b04cde]::ty::ParamEnvAnd<rustc_middle[2fef699d51b04cde]::mir::interpret::GlobalId>, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 24usize]>>>
  36:     0x7f3261a0ed19 - <rustc_middle[2fef699d51b04cde]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  37:     0x7f3261a0e4d4 - <rustc_middle[2fef699d51b04cde]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  38:     0x7f325ff8c889 - <rustc_infer[afeca00818b462f4]::infer::InferCtxt>::const_eval_resolve
  39:     0x7f3262670a2e - rustc_trait_selection[c8b9aadbf50bfac0]::traits::const_evaluatable::is_const_evaluatable.cold.0
  40:     0x7f325e095097 - <rustc_trait_selection[c8b9aadbf50bfac0]::traits::fulfill::FulfillProcessor as rustc_data_structures[40c8b2a1ba3a6075]::obligation_forest::ObligationProcessor>::process_obligation
  41:     0x7f326101bc60 - <rustc_data_structures[40c8b2a1ba3a6075]::obligation_forest::ObligationForest<rustc_trait_selection[c8b9aadbf50bfac0]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[c8b9aadbf50bfac0]::traits::fulfill::FulfillProcessor>
  42:     0x7f3261b20d45 - <rustc_hir_typeck[aabe17c5e1176325]::fn_ctxt::FnCtxt>::check_argument_types
  43:     0x7f32619757c7 - <rustc_hir_typeck[aabe17c5e1176325]::fn_ctxt::FnCtxt>::check_call
  44:     0x7f3261a604e3 - <rustc_hir_typeck[aabe17c5e1176325]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  45:     0x7f32615e3e5b - <rustc_hir_typeck[aabe17c5e1176325]::fn_ctxt::FnCtxt>::check_block_with_expected
  46:     0x7f3261a609c6 - <rustc_hir_typeck[aabe17c5e1176325]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  47:     0x7f3261913288 - rustc_hir_typeck[aabe17c5e1176325]::check::check_fn
  48:     0x7f32611385f1 - rustc_hir_typeck[aabe17c5e1176325]::typeck
  49:     0x7f326113789f - rustc_query_impl[2d7a486b3b483e50]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d7a486b3b483e50]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 8usize]>>
  50:     0x7f32612bf7f0 - rustc_query_system[cca60478b9b5cf0a]::query::plumbing::try_execute_query::<rustc_query_impl[2d7a486b3b483e50]::DynamicConfig<rustc_query_system[cca60478b9b5cf0a]::query::caches::VecCache<rustc_span[dca1c35612e9799e]::def_id::LocalDefId, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[2d7a486b3b483e50]::plumbing::QueryCtxt, false>
  51:     0x7f32612bf30c - rustc_query_impl[2d7a486b3b483e50]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7f32619cd512 - <rustc_middle[2fef699d51b04cde]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[f9243b092bfd4bc4]::check_crate::{closure#6}>::{closure#0}
  53:     0x7f32619cbddd - rustc_hir_analysis[f9243b092bfd4bc4]::check_crate
  54:     0x7f3261c0f1af - rustc_interface[3211d57ef7b44dc5]::passes::analysis
  55:     0x7f3261c0ee19 - rustc_query_impl[2d7a486b3b483e50]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d7a486b3b483e50]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 1usize]>>
  56:     0x7f3261d2b5a5 - rustc_query_system[cca60478b9b5cf0a]::query::plumbing::try_execute_query::<rustc_query_impl[2d7a486b3b483e50]::DynamicConfig<rustc_query_system[cca60478b9b5cf0a]::query::caches::SingleCache<rustc_middle[2fef699d51b04cde]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[2d7a486b3b483e50]::plumbing::QueryCtxt, false>
  57:     0x7f3261d2b309 - rustc_query_impl[2d7a486b3b483e50]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  58:     0x7f3261d3a7d6 - rustc_interface[3211d57ef7b44dc5]::interface::run_compiler::<core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>, rustc_driver_impl[221cda1307b92b70]::run_compiler::{closure#0}>::{closure#0}
  59:     0x7f3261fccec5 - std[1167999404bd111b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3211d57ef7b44dc5]::util::run_in_thread_with_globals<rustc_interface[3211d57ef7b44dc5]::util::run_in_thread_pool_with_globals<rustc_interface[3211d57ef7b44dc5]::interface::run_compiler<core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>, rustc_driver_impl[221cda1307b92b70]::run_compiler::{closure#0}>::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>
  60:     0x7f3261fcccf2 - <<std[1167999404bd111b]::thread::Builder>::spawn_unchecked_<rustc_interface[3211d57ef7b44dc5]::util::run_in_thread_with_globals<rustc_interface[3211d57ef7b44dc5]::util::run_in_thread_pool_with_globals<rustc_interface[3211d57ef7b44dc5]::interface::run_compiler<core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>, rustc_driver_impl[221cda1307b92b70]::run_compiler::{closure#0}>::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2d5c3c55c032a2b6]::result::Result<(), rustc_span[dca1c35612e9799e]::ErrorGuaranteed>>::{closure#1} as core[2d5c3c55c032a2b6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  61:     0x7f325cd99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha029642ca6390740
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/alloc/src/boxed.rs:2016:9
  62:     0x7f325cd99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf1943d8b8c84814b
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/alloc/src/boxed.rs:2016:9
  63:     0x7f325cd99725 - std::sys::pal::unix::thread::Thread::new::thread_start::h01e9562ca32060df
                               at /rustc/2ae1bb671183a072b54ed8ed39abfcd72990a3e7/library/std/src/sys/pal/unix/thread.rs:108:17
  64:     0x7f325cb8055a - <unknown>
  65:     0x7f325cbfda3c - <unknown>
  66:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (2ae1bb671 2024-02-24) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `<impl at /tmp/icemaker_global_tempdir.VPrjJPuc2PMX/rustc_testrunner_tmpdir_reporting.xXOE8jUXEYZD/mvce.rs:6:1: 6:66>::{constant#0}`
#1 [eval_to_valtree] evaluating type-level constant
#2 [typeck] type-checking `use_trait_impl`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #121858: ICE: `invalid asymmetric binary op`
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

struct Outer<const A: i64, const B: usize>();
impl<const A: usize, const B: usize> Outer<A, B>
where
    [(); A + (B * 2)]:,
{
    fn o() -> Union {}
}

fn main() {
    Outer::<1, 1>::o();
}


````

original:
````rust
#![allow(named_arguments_used_positionally)]
#![feature(generic_const_exprs)]
struct Inner<const N: usize, const M: usize>;
impl<const N: usize, const M: usize> Inner<N, M> where [(); N + M]: {
    fn i() -> Self {
        Self
    }
}

struct Outer<const A: i64, const B: usize>(Inner<A, { B * 2 }>) where [(); A + (B * 2)]:;
impl<const A: usize, const B: usize> Outer<A, B> where [(); A + (B * 2)]: {
    fn o() -> Union {
        Self(Inner::i())
    }
}

fn main() {
    Outer::<1, 1>::o();
}

````

Version information
````
rustc 1.78.0-nightly (6db96de66 2024-03-01)
binary: rustc
commit-hash: 6db96de66c2c0ea3f4f2f348ed1a83c2c507687d
commit-date: 2024-03-01
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `Union` in this scope
 --> /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:8:15
  |
8 |     fn o() -> Union {}
  |               ^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
3 + use std::collections::btree_set::Union;
  |
3 + use std::collections::hash_set::Union;
  |

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: the constant `A` is not of type `i64`
 --> /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:4:38
  |
4 | impl<const A: usize, const B: usize> Outer<A, B>
  |                                      ^^^^^^^^^^^ expected `i64`, found `usize`
  |
note: required by a bound in `Outer`
 --> /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:3:14
  |
3 | struct Outer<const A: i64, const B: usize>();
  |              ^^^^^^^^^^^^ required by this bound in `Outer`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/operator.rs:210:13: invalid asymmetric binary op Add: 1 (i64), 2 (usize)
 --> /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:6:10
  |
6 |     [(); A + (B * 2)]:,
  |          ^^^^^^^^^^^

thread 'rustc' panicked at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/compiler/rustc_middle/src/util/bug.rs:34:50:
Box<dyn Any>
stack backtrace:
   0:     0x7f2c0518cc16 - std::backtrace_rs::backtrace::libunwind::trace::he3d6c5089063d4a9
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f2c0518cc16 - std::backtrace_rs::backtrace::trace_unsynchronized::hb4187c1b8bf03927
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2c0518cc16 - std::sys_common::backtrace::_print_fmt::h032943506f752449
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2c0518cc16 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h45b49318deec2f5f
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2c051dd9ec - core::fmt::rt::Argument::fmt::h20093cf29d976e59
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2c051dd9ec - core::fmt::write::h05c62b38f0b0c787
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f2c0518142f - std::io::Write::write_fmt::h888bd67f4a2fd807
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/io/mod.rs:1846:15
   7:     0x7f2c0518c9c4 - std::sys_common::backtrace::_print::h6e2869c486d8d5ed
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2c0518c9c4 - std::sys_common::backtrace::print::h19dd2422e12d01dd
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2c0518f6fb - std::panicking::default_hook::{{closure}}::h9559cc38c2efb44d
  10:     0x7f2c0518f457 - std::panicking::default_hook::h78ced15c08986523
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/panicking.rs:292:9
  11:     0x7f2c0809cc3c - std[820a48f693f20e10]::panicking::update_hook::<alloc[1081ffb5169edabc]::boxed::Box<rustc_driver_impl[b991ea38ec43aa33]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f2c0518fe60 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfc6f63ee5a91af0a
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/alloc/src/boxed.rs:2030:9
  13:     0x7f2c0518fe60 - std::panicking::rust_panic_with_hook::he1b19f1a9fc3113c
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/panicking.rs:783:13
  14:     0x7f2c080c9024 - std[820a48f693f20e10]::panicking::begin_panic::<rustc_errors[1ce4b89642471e3d]::ExplicitBug>::{closure#0}
  15:     0x7f2c080c5f46 - std[820a48f693f20e10]::sys_common::backtrace::__rust_end_short_backtrace::<std[820a48f693f20e10]::panicking::begin_panic<rustc_errors[1ce4b89642471e3d]::ExplicitBug>::{closure#0}, !>
  16:     0x7f2c080c5c26 - std[820a48f693f20e10]::panicking::begin_panic::<rustc_errors[1ce4b89642471e3d]::ExplicitBug>
  17:     0x7f2c080d2531 - <rustc_errors[1ce4b89642471e3d]::diagnostic::BugAbort as rustc_errors[1ce4b89642471e3d]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f2c08023ac0 - rustc_middle[3adc827ec22eacf1]::util::bug::opt_span_bug_fmt::<rustc_span[5453344853d8237f]::span_encoding::Span>::{closure#0}
  19:     0x7f2c08023cda - rustc_middle[3adc827ec22eacf1]::ty::context::tls::with_opt::<rustc_middle[3adc827ec22eacf1]::util::bug::opt_span_bug_fmt<rustc_span[5453344853d8237f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f2c0801a9a8 - rustc_middle[3adc827ec22eacf1]::ty::context::tls::with_context_opt::<rustc_middle[3adc827ec22eacf1]::ty::context::tls::with_opt<rustc_middle[3adc827ec22eacf1]::util::bug::opt_span_bug_fmt<rustc_span[5453344853d8237f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f2c0764c324 - rustc_middle[3adc827ec22eacf1]::util::bug::span_bug_fmt::<rustc_span[5453344853d8237f]::span_encoding::Span>
  22:     0x7f2c0a31fce2 - rustc_const_eval[7b794d8b5a78f829]::const_eval::eval_queries::eval_body_using_ecx::{closure#0}
  23:     0x7f2c0a2a039d - rustc_const_eval[7b794d8b5a78f829]::const_eval::eval_queries::eval_in_interpreter
  24:     0x7f2c098180e8 - rustc_const_eval[7b794d8b5a78f829]::const_eval::eval_queries::eval_to_allocation_raw_provider
  25:     0x7f2c09817eb6 - rustc_query_impl[1c358578e72853c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c358578e72853c]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 24usize]>>
  26:     0x7f2c09dd6891 - rustc_query_system[43ffd4ba2a1029a6]::query::plumbing::try_execute_query::<rustc_query_impl[1c358578e72853c]::DynamicConfig<rustc_query_system[43ffd4ba2a1029a6]::query::caches::DefaultCache<rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::mir::interpret::GlobalId>, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[1c358578e72853c]::plumbing::QueryCtxt, false>
  27:     0x7f2c09dd646c - rustc_query_impl[1c358578e72853c]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f2c09dd8399 - rustc_const_eval[7b794d8b5a78f829]::const_eval::valtrees::eval_to_valtree
  29:     0x7f2c09dd81a2 - <rustc_const_eval[7b794d8b5a78f829]::provide::{closure#0} as core[64077830e178c27b]::ops::function::FnOnce<(rustc_middle[3adc827ec22eacf1]::ty::context::TyCtxt, rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::mir::interpret::GlobalId>)>>::call_once
  30:     0x7f2c09dd8176 - rustc_query_impl[1c358578e72853c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c358578e72853c]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 24usize]>>
  31:     0x7f2c09dd812f - <rustc_query_impl[1c358578e72853c]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[64077830e178c27b]::ops::function::FnOnce<(rustc_middle[3adc827ec22eacf1]::ty::context::TyCtxt, rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::mir::interpret::GlobalId>)>>::call_once
  32:     0x7f2c09dd696c - rustc_query_system[43ffd4ba2a1029a6]::query::plumbing::try_execute_query::<rustc_query_impl[1c358578e72853c]::DynamicConfig<rustc_query_system[43ffd4ba2a1029a6]::query::caches::DefaultCache<rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::mir::interpret::GlobalId>, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[1c358578e72853c]::plumbing::QueryCtxt, false>
  33:     0x7f2c09dd626c - rustc_query_impl[1c358578e72853c]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f2c09dd5a77 - rustc_middle[3adc827ec22eacf1]::query::plumbing::query_get_at::<rustc_query_system[43ffd4ba2a1029a6]::query::caches::DefaultCache<rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::mir::interpret::GlobalId>, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 24usize]>>>
  35:     0x7f2c09dd56c5 - <rustc_middle[3adc827ec22eacf1]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  36:     0x7f2c09dd4e68 - <rustc_middle[3adc827ec22eacf1]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  37:     0x7f2c0839ca49 - <rustc_infer[afafe7e786f933ba]::infer::InferCtxt>::const_eval_resolve
  38:     0x7f2c0aa77da0 - rustc_trait_selection[64a4fdc6eaf70758]::traits::const_evaluatable::is_const_evaluatable.cold.0
  39:     0x7f2c0993ad29 - <rustc_infer[afafe7e786f933ba]::infer::InferCtxt>::probe::<core[64077830e178c27b]::result::Result<rustc_middle[3adc827ec22eacf1]::traits::select::EvaluationResult, rustc_middle[3adc827ec22eacf1]::traits::select::OverflowError>, <rustc_trait_selection[64a4fdc6eaf70758]::traits::select::SelectionContext>::evaluation_probe<<rustc_trait_selection[64a4fdc6eaf70758]::traits::select::SelectionContext>::evaluate_root_obligation::{closure#0}>::{closure#0}>
  40:     0x7f2c0962ac96 - rustc_traits[ed16f9613e303d6c]::evaluate_obligation::evaluate_obligation
  41:     0x7f2c0962a620 - rustc_query_impl[1c358578e72853c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c358578e72853c]::query_impl::evaluate_obligation::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 2usize]>>
  42:     0x7f2c09629b89 - rustc_query_system[43ffd4ba2a1029a6]::query::plumbing::try_execute_query::<rustc_query_impl[1c358578e72853c]::DynamicConfig<rustc_query_system[43ffd4ba2a1029a6]::query::caches::DefaultCache<rustc_type_ir[969cbadcba052c4e]::canonical::Canonical<rustc_middle[3adc827ec22eacf1]::ty::context::TyCtxt, rustc_middle[3adc827ec22eacf1]::ty::ParamEnvAnd<rustc_middle[3adc827ec22eacf1]::ty::predicate::Predicate>>, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[1c358578e72853c]::plumbing::QueryCtxt, false>
  43:     0x7f2c09629811 - rustc_query_impl[1c358578e72853c]::query_impl::evaluate_obligation::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f2c06a62d71 - <rustc_infer[afafe7e786f933ba]::infer::InferCtxt as rustc_trait_selection[64a4fdc6eaf70758]::traits::query::evaluate_obligation::InferCtxtExt>::predicate_may_hold
  45:     0x7f2c09b93b81 - <rustc_hir_typeck[18b72d79248d5cb2]::method::probe::ProbeContext>::consider_probe::{closure#0}
  46:     0x7f2c09b8ff2b - <rustc_hir_typeck[18b72d79248d5cb2]::method::probe::ProbeContext>::pick_all_method
  47:     0x7f2c06a46f31 - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::probe_for_name
  48:     0x7f2c09950f8c - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::resolve_fully_qualified_call
  49:     0x7f2c0994e5cc - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::check_expr_path
  50:     0x7f2c09d2c9fb - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::check_call
  51:     0x7f2c09e72e63 - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  52:     0x7f2c0997fcdb - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::check_block_with_expected
  53:     0x7f2c09e73346 - <rustc_hir_typeck[18b72d79248d5cb2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  54:     0x7f2c09b99a2d - rustc_hir_typeck[18b72d79248d5cb2]::check::check_fn
  55:     0x7f2c0958d646 - rustc_hir_typeck[18b72d79248d5cb2]::typeck
  56:     0x7f2c0958c94f - rustc_query_impl[1c358578e72853c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c358578e72853c]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 8usize]>>
  57:     0x7f2c0959d730 - rustc_query_system[43ffd4ba2a1029a6]::query::plumbing::try_execute_query::<rustc_query_impl[1c358578e72853c]::DynamicConfig<rustc_query_system[43ffd4ba2a1029a6]::query::caches::VecCache<rustc_span[5453344853d8237f]::def_id::LocalDefId, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1c358578e72853c]::plumbing::QueryCtxt, false>
  58:     0x7f2c0959d24c - rustc_query_impl[1c358578e72853c]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  59:     0x7f2c09caf812 - <rustc_middle[3adc827ec22eacf1]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[23a44e406cf6738f]::check_crate::{closure#6}>::{closure#0}
  60:     0x7f2c09cae0dd - rustc_hir_analysis[23a44e406cf6738f]::check_crate
  61:     0x7f2c0a0540ef - rustc_interface[35191de142c3c403]::passes::analysis
  62:     0x7f2c0a053d59 - rustc_query_impl[1c358578e72853c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1c358578e72853c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 1usize]>>
  63:     0x7f2c0a1689e5 - rustc_query_system[43ffd4ba2a1029a6]::query::plumbing::try_execute_query::<rustc_query_impl[1c358578e72853c]::DynamicConfig<rustc_query_system[43ffd4ba2a1029a6]::query::caches::SingleCache<rustc_middle[3adc827ec22eacf1]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1c358578e72853c]::plumbing::QueryCtxt, false>
  64:     0x7f2c0a168749 - rustc_query_impl[1c358578e72853c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  65:     0x7f2c0a172136 - rustc_interface[35191de142c3c403]::interface::run_compiler::<core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>, rustc_driver_impl[b991ea38ec43aa33]::run_compiler::{closure#0}>::{closure#0}
  66:     0x7f2c0a3d5a23 - std[820a48f693f20e10]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[35191de142c3c403]::util::run_in_thread_with_globals<rustc_interface[35191de142c3c403]::util::run_in_thread_pool_with_globals<rustc_interface[35191de142c3c403]::interface::run_compiler<core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>, rustc_driver_impl[b991ea38ec43aa33]::run_compiler::{closure#0}>::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>
  67:     0x7f2c0a3d5850 - <<std[820a48f693f20e10]::thread::Builder>::spawn_unchecked_<rustc_interface[35191de142c3c403]::util::run_in_thread_with_globals<rustc_interface[35191de142c3c403]::util::run_in_thread_pool_with_globals<rustc_interface[35191de142c3c403]::interface::run_compiler<core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>, rustc_driver_impl[b991ea38ec43aa33]::run_compiler::{closure#0}>::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[64077830e178c27b]::result::Result<(), rustc_span[5453344853d8237f]::ErrorGuaranteed>>::{closure#1} as core[64077830e178c27b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  68:     0x7f2c051997d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5b26ba5fb371c34b
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/alloc/src/boxed.rs:2016:9
  69:     0x7f2c051997d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea01b48bf7b68085
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/alloc/src/boxed.rs:2016:9
  70:     0x7f2c051997d5 - std::sys::pal::unix::thread::Thread::new::thread_start::h6a37d9a0a27ffad7
                               at /rustc/6db96de66c2c0ea3f4f2f348ed1a83c2c507687d/library/std/src/sys/pal/unix/thread.rs:108:17
  71:     0x7f2c04f8155a - <unknown>
  72:     0x7f2c04ffea3c - <unknown>
  73:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (6db96de66 2024-03-01) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `<impl at /tmp/icemaker_global_tempdir.7CH3ww2pcPid/rustc_testrunner_tmpdir_reporting.MChzaBFXjkIL/mvce.rs:4:1: 6:24>::{constant#0}`
#1 [eval_to_valtree] evaluating type-level constant
#2 [evaluate_obligation] evaluating trait selection obligation `the constant `A + (B * 2)` can be evaluated`
#3 [typeck] type-checking `main`
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0412`.

```

</p>
</details>

### LINKED ISSUE #124151: ICE: `tried to combine ConstKind::Infer/ConstKind::Infer(InferConst::Var)`
snippet:
````rust
#![feature(generic_const_exprs)]

use std::ops::Add;

pub struct Dimension;

pub struct Quantity<S, const D: Dimension>(S);

impl<const D: Dimension, LHS, RHS> Add<LHS, D> for Quantity<LHS, { Dimension }> {}

pub fn add<const U: Dimension>(x: Quantity<f32, U>) -> Quantity<f32, U> {
    x + y
}


````

Version information
````
rustc 1.79.0-nightly (13e63f749 2024-04-19)
binary: rustc
commit-hash: 13e63f7490109eecf905fa51190eacbe8051aefd
commit-date: 2024-04-19
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `y` in this scope
  --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:12:9
   |
11 | pub fn add<const U: Dimension>(x: Quantity<f32, U>) -> Quantity<f32, U> {
   |                  - similarly named const parameter `U` defined here
12 |     x + y
   |         ^ help: a const parameter with a similar name exists: `U`

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:13:2
   |
13 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs`

error: `Dimension` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:7:33
  |
7 | pub struct Quantity<S, const D: Dimension>(S);
  |                                 ^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
  |
3 + #![feature(adt_const_params)]
  |

error[E0107]: trait takes at most 1 generic argument but 2 generic arguments were supplied
  --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:9:36
   |
9  | impl<const D: Dimension, LHS, RHS> Add<LHS, D> for Quantity<LHS, { Dimension }> {}
   |                                    ^^^ expected at most 1 generic argument
   |
note: trait defined here, with at most 1 generic parameter: `Rhs`
  --> /home/matthias/.rustup/toolchains/master/lib/rustlib/src/rust/library/core/src/ops/arith.rs:77:11
   |
77 | pub trait Add<Rhs = Self> {
   |           ^^^ ----------

error[E0207]: the type parameter `RHS` is not constrained by the impl trait, self type, or predicates
 --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:9:31
  |
9 | impl<const D: Dimension, LHS, RHS> Add<LHS, D> for Quantity<LHS, { Dimension }> {}
  |                               ^^^ unconstrained type parameter

error: `Dimension` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:9:15
  |
9 | impl<const D: Dimension, LHS, RHS> Add<LHS, D> for Quantity<LHS, { Dimension }> {}
  |               ^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
  |
3 + #![feature(adt_const_params)]
  |

error: `Dimension` is forbidden as the type of a const generic parameter
  --> /tmp/icemaker_global_tempdir.238HcpoyMYrj/rustc_testrunner_tmpdir_reporting.djwOrNP1QTCg/mvce.rs:11:21
   |
11 | pub fn add<const U: Dimension>(x: Quantity<f32, U>) -> Quantity<f32, U> {
   |                     ^^^^^^^^^
   |
   = note: the only supported types are integers, `bool` and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
   |
3  + #![feature(adt_const_params)]
   |

error: internal compiler error: compiler/rustc_infer/src/infer/relate/combine.rs:218:17: tried to combine ConstKind::Infer/ConstKind::Infer(InferConst::Var): ?0e: bool and ?0c: Dimension

thread 'rustc' panicked at compiler/rustc_infer/src/infer/relate/combine.rs:218:17:
Box<dyn Any>
stack backtrace:
   0:     0x70f2a720ba75 - std::backtrace_rs::backtrace::libunwind::trace::ha8c9b07da08ff29f
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x70f2a720ba75 - std::backtrace_rs::backtrace::trace_unsynchronized::h88b77157367fcdbe
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x70f2a720ba75 - std::sys_common::backtrace::_print_fmt::hea56b38e54fb92e3
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x70f2a720ba75 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd602b1809ea2b2a5
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x70f2a725aceb - core::fmt::rt::Argument::fmt::h62340eb90b1c87a5
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/core/src/fmt/rt.rs:165:63
   5:     0x70f2a725aceb - core::fmt::write::hd8cf97ba7b2f9e9b
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/core/src/fmt/mod.rs:1157:21
   6:     0x70f2a72005ff - std::io::Write::write_fmt::h6c685f4679b9e915
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/io/mod.rs:1832:15
   7:     0x70f2a720b84e - std::sys_common::backtrace::_print::hd9c2ac426a3dbd1c
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x70f2a720b84e - std::sys_common::backtrace::print::h7bbdd9953597c8e0
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x70f2a720e1b9 - std::panicking::default_hook::{{closure}}::hde25fbbdd81a41c5
  10:     0x70f2a720defd - std::panicking::default_hook::h4ad8db4b2d78fdfd
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/panicking.rs:291:9
  11:     0x70f2a3c0bb0c - std[3a7515f9f343dc41]::panicking::update_hook::<alloc[4812e9b6fdfe5c0f]::boxed::Box<rustc_driver_impl[7e01e62ceaa0f3bd]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x70f2a720e8b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha867ea15cf1ece79
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/alloc/src/boxed.rs:2036:9
  13:     0x70f2a720e8b6 - std::panicking::rust_panic_with_hook::h38462a8904eacfd3
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/panicking.rs:792:13
  14:     0x70f2a3c3be14 - std[3a7515f9f343dc41]::panicking::begin_panic::<rustc_errors[342f12710b53d715]::ExplicitBug>::{closure#0}
  15:     0x70f2a3c38a96 - std[3a7515f9f343dc41]::sys_common::backtrace::__rust_end_short_backtrace::<std[3a7515f9f343dc41]::panicking::begin_panic<rustc_errors[342f12710b53d715]::ExplicitBug>::{closure#0}, !>
  16:     0x70f2a3c38776 - std[3a7515f9f343dc41]::panicking::begin_panic::<rustc_errors[342f12710b53d715]::ExplicitBug>
  17:     0x70f2a3c44d31 - <rustc_errors[342f12710b53d715]::diagnostic::BugAbort as rustc_errors[342f12710b53d715]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x70f2a40ee87c - rustc_middle[9f70d05f0880cb49]::util::bug::opt_span_bug_fmt::<rustc_span[5b895301fccec34d]::span_encoding::Span>::{closure#0}
  19:     0x70f2a40d6f6a - rustc_middle[9f70d05f0880cb49]::ty::context::tls::with_opt::<rustc_middle[9f70d05f0880cb49]::util::bug::opt_span_bug_fmt<rustc_span[5b895301fccec34d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x70f2a40d6e0b - rustc_middle[9f70d05f0880cb49]::ty::context::tls::with_context_opt::<rustc_middle[9f70d05f0880cb49]::ty::context::tls::with_opt<rustc_middle[9f70d05f0880cb49]::util::bug::opt_span_bug_fmt<rustc_span[5b895301fccec34d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x70f2a2488730 - rustc_middle[9f70d05f0880cb49]::util::bug::bug_fmt
  22:     0x70f2a51c09c6 - <rustc_infer[d392145922f729ae]::infer::InferCtxt>::super_combine_consts::<rustc_infer[d392145922f729ae]::infer::relate::type_relating::TypeRelating>
  23:     0x70f2a576b128 - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::match_impl::{closure#0}
  24:     0x70f2a1cd6401 - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::assemble_candidates_from_impls
  25:     0x70f2a1cae490 - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  26:     0x70f2a24ac0b6 - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::candidate_from_obligation
  27:     0x70f2a574f61d - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  28:     0x70f2a5747392 - <rustc_trait_selection[907d3d2a5430c87]::traits::select::SelectionContext>::evaluate_root_obligation
  29:     0x70f2a57457d1 - rustc_traits[53e42f50b8e79099]::evaluate_obligation::evaluate_obligation
  30:     0x70f2a5745169 - rustc_query_impl[1d56237bde1e3cf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1d56237bde1e3cf]::query_impl::evaluate_obligation::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 2usize]>>
  31:     0x70f2a5744699 - rustc_query_system[8dca229a75e3ed4f]::query::plumbing::try_execute_query::<rustc_query_impl[1d56237bde1e3cf]::DynamicConfig<rustc_query_system[8dca229a75e3ed4f]::query::caches::DefaultCache<rustc_type_ir[74778dcbd53ce3ac]::canonical::Canonical<rustc_middle[9f70d05f0880cb49]::ty::context::TyCtxt, rustc_middle[9f70d05f0880cb49]::ty::ParamEnvAnd<rustc_middle[9f70d05f0880cb49]::ty::predicate::Predicate>>, rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[1d56237bde1e3cf]::plumbing::QueryCtxt, false>
  32:     0x70f2a57442da - rustc_query_impl[1d56237bde1e3cf]::query_impl::evaluate_obligation::get_query_non_incr::__rust_end_short_backtrace
  33:     0x70f2a2aff393 - <rustc_infer[d392145922f729ae]::infer::InferCtxt as rustc_trait_selection[907d3d2a5430c87]::traits::query::evaluate_obligation::InferCtxtExt>::predicate_may_hold
  34:     0x70f2a55b2576 - <rustc_hir_typeck[939ad14c3525d91d]::fn_ctxt::FnCtxt>::lookup_method_in_trait
  35:     0x70f2a558b0f3 - <rustc_hir_typeck[939ad14c3525d91d]::fn_ctxt::FnCtxt>::check_overloaded_binop
  36:     0x70f2a5b101f2 - <rustc_hir_typeck[939ad14c3525d91d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:     0x70f2a5b08886 - <rustc_hir_typeck[939ad14c3525d91d]::fn_ctxt::FnCtxt>::check_block_with_expected
  38:     0x70f2a5b0ebf6 - <rustc_hir_typeck[939ad14c3525d91d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  39:     0x70f2a522f02a - rustc_hir_typeck[939ad14c3525d91d]::check::check_fn
  40:     0x70f2a52242e1 - rustc_hir_typeck[939ad14c3525d91d]::typeck
  41:     0x70f2a5223c95 - rustc_query_impl[1d56237bde1e3cf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1d56237bde1e3cf]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 8usize]>>
  42:     0x70f2a52115b1 - rustc_query_system[8dca229a75e3ed4f]::query::plumbing::try_execute_query::<rustc_query_impl[1d56237bde1e3cf]::DynamicConfig<rustc_query_system[8dca229a75e3ed4f]::query::caches::VecCache<rustc_span[5b895301fccec34d]::def_id::LocalDefId, rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1d56237bde1e3cf]::plumbing::QueryCtxt, false>
  43:     0x70f2a520ff8c - rustc_query_impl[1d56237bde1e3cf]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x70f2a520fb5a - <rustc_middle[9f70d05f0880cb49]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[156b0fa72c4118da]::check_crate::{closure#4}>::{closure#0}
  45:     0x70f2a520e84d - rustc_hir_analysis[156b0fa72c4118da]::check_crate
  46:     0x70f2a55d4bfa - rustc_interface[54c114a5fe2550b3]::passes::analysis
  47:     0x70f2a55d4755 - rustc_query_impl[1d56237bde1e3cf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1d56237bde1e3cf]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 1usize]>>
  48:     0x70f2a5da0765 - rustc_query_system[8dca229a75e3ed4f]::query::plumbing::try_execute_query::<rustc_query_impl[1d56237bde1e3cf]::DynamicConfig<rustc_query_system[8dca229a75e3ed4f]::query::caches::SingleCache<rustc_middle[9f70d05f0880cb49]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1d56237bde1e3cf]::plumbing::QueryCtxt, false>
  49:     0x70f2a5da04c9 - rustc_query_impl[1d56237bde1e3cf]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  50:     0x70f2a5c04a19 - rustc_interface[54c114a5fe2550b3]::interface::run_compiler::<core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>, rustc_driver_impl[7e01e62ceaa0f3bd]::run_compiler::{closure#0}>::{closure#1}
  51:     0x70f2a5bec6a7 - std[3a7515f9f343dc41]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[54c114a5fe2550b3]::util::run_in_thread_with_globals<rustc_interface[54c114a5fe2550b3]::util::run_in_thread_pool_with_globals<rustc_interface[54c114a5fe2550b3]::interface::run_compiler<core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>, rustc_driver_impl[7e01e62ceaa0f3bd]::run_compiler::{closure#0}>::{closure#1}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>::{closure#0}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>
  52:     0x70f2a5bec46a - <<std[3a7515f9f343dc41]::thread::Builder>::spawn_unchecked_<rustc_interface[54c114a5fe2550b3]::util::run_in_thread_with_globals<rustc_interface[54c114a5fe2550b3]::util::run_in_thread_pool_with_globals<rustc_interface[54c114a5fe2550b3]::interface::run_compiler<core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>, rustc_driver_impl[7e01e62ceaa0f3bd]::run_compiler::{closure#0}>::{closure#1}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>::{closure#0}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[19d803e10bedb259]::result::Result<(), rustc_span[5b895301fccec34d]::ErrorGuaranteed>>::{closure#2} as core[19d803e10bedb259]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x70f2a721878b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h86765e31d66056c2
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/alloc/src/boxed.rs:2022:9
  54:     0x70f2a721878b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he77e1cc2b11985d8
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/alloc/src/boxed.rs:2022:9
  55:     0x70f2a721878b - std::sys::pal::unix::thread::Thread::new::thread_start::h478135d5001d4398
                               at /rustc/13e63f7490109eecf905fa51190eacbe8051aefd/library/std/src/sys/pal/unix/thread.rs:108:17
  56:     0x70f2a0aa955a - <unknown>
  57:     0x70f2a0b26a3c - <unknown>
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (13e63f749 2024-04-19) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `Quantity<f32, U>: ~const core::ops::arith::Add<^1_0>`
#1 [typeck] type-checking `add`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 8 previous errors; 1 warning emitted

Some errors have detailed explanations: E0107, E0207, E0425, E0601.
For more information about an error, try `rustc --explain E0107`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #121585
fixes #121858 
fixes #124151

I gave this several attempts before, but we lost too many important diagnostics until I managed to make compilation never bail out early. We have reached this point, so now we can finally fix all those ICEs by bubbling up an error instead of continueing when we encounter a bug.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I don't think I'm a good reviewer for this.
r? types

File: compiler/rustc_infer/src/infer/relate/combine.rs [hunk 1]
```diff
@@ -178,18 +178,15 @@ impl<'tcx> InferCtxt<'tcx> {
...
                 ));
-                // We treat these constants as if they were of the same type, so that any
-                // such constants being used in impls make these impls match barring other mismatches.
-                // This helps with diagnostics down the road.
-            });
-        });
-
+                TypeError::Mismatch
+            })
+        })?;
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/relate/combine.rs:189]: I wonder if we should actually just do...

```
self.at(...).equate(a.ty(), b.ty())?;
```

...here, rather than reimplementing that behavior in a query that just approximates if types are equal. I don't think I'm convinced about:

```
// This probe is probably not strictly necessary but it seems better to be safe and not accidentally find
// ourselves with a check to find bugs being required for code to compile because it made inference progress.
```

since I believe the only case where this may occur is GCE[^1], and if we make inference-breaking changes to GCE, then like... it's nightly? :laughing:

[^1]: Though I guess we should check that this doesn't interact poorly with associated consts or something, though I'm not certain where we'd ever have a case where equating the types of two consts causes inference guidance that we *don't* want...

**Review by compiler-errors — APPROVED** [review]
^

**Review by compiler-errors — CHANGES_REQUESTED** [review]
oops meant to request changes, see comment i left

File: compiler/rustc_infer/src/infer/relate/combine.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_infer/src/infer/relate/combine.rs:189]: oh 🤦 yea, at this point we should just equate them

Comment (oli-obk) [reply compiler/rustc_infer/src/infer/relate/combine.rs]: Apparently under GCE it does cause something I haven't debugged further, and just turned the test into a known-bug.

**Review by compiler-errors — APPROVED** [review]
Diagnostics changes here are meh, but I think we should fix those on the diagnostics side. Maybe we can relate a different `TypeError` kind for const kind mismatches that signal something is wrong in the source.

**Comment by BoxyUwU** [comment]
I don't feel great that we have this as a real `eq` now, it should not be necessary for soundness as types of consts being correct is checked elsewhere. Could you explain more about exactly why this should be necessary. It seems like in all test cases there _are_ error messages so the delayed bug should not cause any ICE?

**Comment by BoxyUwU** [comment]
Can we just remove this `eq` entirely? The assertion _was_ getting pretty convoluted and should not be required at all

**Comment by oli-obk** [comment]
Without the check here, we'll end up not tainting the MIR and subsequently the MIR interpreter, causing the ICEs we've seen. The issue is that the only place that checks that the types are valid is wfcheck, and we can't make other code depend on wfcheck, as wfcheck itself will try to evaluate constants and prove predicates, causing cycles.

We can move some checks like the type checks out of wfcheck to typeck, then we may be able to remove this again, but it's not obvious yet to me how to do this in a way that isn't error prone

**Comment by oli-obk** [comment]
Also https://github.com/rust-lang/rust/blob/d5eb7a71b3c869eb9e15f10da6eb92303b96dfb5/tests/ui/const-generics/issues/issue-105821.rs#L13 suddenly passes if I just remove the `eq` check entirely. So even the wfchecks aren't waterproof.
