### PR TITLE
Qualify `panic!` as `core::panic!` in non-built-in `core` macros

### LINKED ISSUE #78333: error: cannot find macro `panic` in this scope
I tried this code:

```rust
#![no_implicit_prelude]

fn main() {
    ::std::todo!();
    ::std::unimplemented!();
}

```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=113238e679e145566f844adf9c51b0a1))

I expected to see this happen:
Successful compilation

Instead, this happened:
```
   Compiling playground v0.0.1 (/playground)
error: cannot find macro `panic` in this scope
 --> src/main.rs:4:5
  |
4 |     ::std::todo!();
  |     ^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `panic` in this scope
 --> src/main.rs:5:5
  |
5 |     ::std::unimplemented!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### Meta

~~`rustc --version --verbose`~~ Playground Stable Version:
```
1.47.0
```

The macros should be using `$crate::panic!`, instead of `panic!`.

### PR DESCRIPTION
**Pull request by camelid**
Fixes #78333.

-----

Otherwise code like this

    #![no_implicit_prelude]

    fn main() {
        ::std::todo!();
        ::std::unimplemented!();
    }

will fail to compile, which is unfortunate and presumably unintended.

This changes many invocations of `panic!` in a `macro_rules!` definition
to invocations of `$crate::panic!`, which makes the invocations hygienic.

Note that this does not make the built-in macro `assert!` hygienic.

### CODE REVIEW

**Comment by camelid** [comment]
I would like to write a test for this, but I'm not sure where to put it. Where are library compiletests put?

**Comment by camelid** [comment]
Tested locally and it seems to work.

### stderr (compiling)

```rust
warning: unreachable statement
 --> issue-78333.rs:5:5
  |
4 |     ::std::todo!();
  |     --------------- any code following this expression is unreachable
5 |     ::std::unimplemented!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
  |
  = note: `#[warn(unreachable_code)]` on by default
  = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 1 warning emitted
```

### stderr (running)

```
thread 'main' panicked at 'not yet implemented', issue-78333.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jyn514** [comment]
> I would like to write a test for this, but I'm not sure where to put it. Where are library compiletests put?

`src/test/ui/macros/` seems fine.

**Comment by petrochenkov** [comment]
This PR reroutes majority of code that previously called `std::panic` to `core::panic`.
We can only do this if `core::panic` and `std::panic` have identical interface and behavior in all case affected by the PR.
cc @RalfJung @m-ou-se

**Comment by RalfJung** [comment]
Seems fine to me, and actually with @m-ou-se's recent changes the two macros are now more similar than before.

**Comment by m-ou-se** [comment]
For all cases of the form `panic!(format, one or more args ..)`, they do exactly the same, which covers almost all cases in this PR.

The other cases in this PR are of the form `panic!("just a literal")`, which used to work differently, but that was fixed just a few hours ago by #78119.

However, two important notes:

1. You used to be able to 'intercept' `panic!()` from these macros by adding your own custom `panic!` macro. This is not a guarantee made anywhere in the documentation, so I think it's fine to break that.

2. This PR changes `assert_eq!` and `assert_ne!`, but doesn't change `assert!`. (`assert!` is not a macro_rules, but it's implemented in `compiler/rustc_builtin_macros/src/assert.rs`.) `assert!(expr, args ..)` has the same problem this PR is fixing: it also expands to just `panic!(args ..)` without `$crate::`. However, that one does expose the forms of `{std,core}::panic!` that are different:

```rust
assert!(1 + 1 == 3, 123); // ok with std, error with core
assert!(1 + 1 == 3, &String::from("hello")); // ok with core, error with std
```

I think it's fine to merge this PR as is, and fix `assert!()` later if possible. I already have a PR open that fixes this problem for `assert!(expr)`, but not for `assert!(expr, args ..)`: https://github.com/rust-lang/rust/pull/78088/commits/049f2f2a603135bbb3b2507b6a13782888e499e1. The second form probably has to wait for `std::panic!()` and `core::panic!()` to become completely identical in behaviour, which will probably only happen in Rust 2021 to avoid breakage.

**Comment by RalfJung** [comment]
> `assert!(1 + 1 == 3, 123); // ok with std, error with core`

I doubt this was ever intended to work, and even for people using `panic!` with a custom payload, this seems like a stretch. It would be worth a crater run to see how often this actually occurs in practice.

**Comment by m-ou-se** [comment]
> > `assert!(1 + 1 == 3, 123); // ok with std, error with core`
> 
> I doubt this was ever intended to work, and even for people using `panic!` with a custom payload, this seems like a stretch. It would be worth a crater run to see how often this actually occurs in practice.

I'm all for just breaking `assert!(.., 123)` (and `panic!(123)`). But most discussions about this came to the conclusion that this should probably be gated on the next edition.

I'll turn [my notes about this](https://hackmd.io/@kQlAmwdASwqEXB8JsIkvyw/H1V0MKFvw) into an RFC today (and also add something about `assert!()`), so we can make a final decision about how to go forward with `panic!()` (and `assert!()` (and `debug_assert!()`)).

**Comment by RalfJung** [comment]
> I'm all for just breaking assert!(.., 123) (and panic!(123)). But most discussions about this came to the conclusion that this should probably be gated on the next edition.

For `panic!` I agree the change is too invasive, but for `assert!` I am less sure.

> I'll turn my notes about this into an RFC today (and also add something about assert!()), so we can make a final decision about how to go forward with panic!() (and assert!() (and debug_assert!())).

Okay, great. :)  (But some of this will likely require further data, in particular for `assert!` I think it would be really good to know how wide-spread such non-string uses are.)

**Comment by m-ou-se** [comment]
> I'll turn my notes about this into an RFC today

[Here it is](https://github.com/fusion-engineering-forks/rfcs/blob/panic/text/0000-panic-plan.md)

The proposed steps include this PR and the problem it solves. See the second to last step under 'Proposed solution'.

**Comment by Mark-Simulacrum** [comment]
I'm going to r? @m-ou-se here, I'm not sure what the right path is -- would need to think about it -- but you seem to have a better handle on it than I :)

**Comment by camelid** [comment]
Yeah, this is much more complicated than I thought!

File: compiler/rustc_builtin_macros/src/assert.rs [hunk 1]
```diff
@@ -41,7 +38,15 @@ pub fn expand_assert<'cx>(
...
-        path: Path::from_ident(Ident::new(sym::panic, sp)),
+        path: Path {
+            span: DUMMY_SP,
+            segments: vec![
+                PathSegment::from_ident(Ident::with_dummy_span(kw::PathRoot)),
+                PathSegment::from_ident(Ident::with_dummy_span(sym::core)),
+                PathSegment::from_ident(Ident::new(sym::panic, sp)),
+            ],
+            tokens: None,
+        },
```
Comment (camelid) [inline compiler/rustc_builtin_macros/src/assert.rs:49]: I tried to qualify this, but got the error:

```
error[E0433]: failed to resolve: could not find `core` in `{{root}}`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `core`
```

It seems like the issue is that expanding as `core` doesn't work inside `core`. How should I do it instead?

Comment (m-ou-se) [reply compiler/rustc_builtin_macros/src/assert.rs:49]: It should be possible to use something like this for the first path element:
```rust
Ident::new(kw::DollarCrate, cx.with_def_site_ctxt(DUMMY_SP)) // `$crate`
```

**Comment by m-ou-se** [comment]
Now that you're also updating `assert!`, this PR is a good candidate for a crater run to see if anyone relies on being able to intercept `panic!()`s from those macros, or uses non-string messages for `assert!` (e.g. `assert!(false, 123)`).

File: compiler/rustc_builtin_macros/src/assert.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_builtin_macros/src/assert.rs:49]: Built-in macros use a function called `std_path` for paths pointing to the standard library, no need to hand-roll it.

**Comment by camelid** [comment]
Yeah, I think I'll have to adjust the code if we're going to go forward with updating `assert!`, because it no longer allows you to use `String` as the assert message :/

```
error[E0308]: mismatched types
  --> /Users/nlroscoemeow/rust/src/test/ui/macros/assert-macro-owned.rs:6:20
   |
LL |     assert!(false, "test-assert-owned".to_string());
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                    |
   |                    expected `&str`, found struct `String`
   |                    help: consider borrowing here: `&"test-assert-owned".to_string()`
```

**Comment by m-ou-se** [comment]
Yup. But we can still use this to do a crater run. Curious to see if anything other than this unit test fails.

@bors try

**Comment by m-ou-se** [comment]
Heh, we didn't even need a crater run for that. The try run already fails directly while trying to compile `clap`:

https://github.com/clap-rs/clap/blob/0c7da9f5b32bcd6968a70258a4868d439fbc1fc3/src/app/parser.rs#L181-L184

Well I guess that also gives an answer as to whether this is used in the wild.

**Comment by RalfJung** [comment]
That's annoying. :/ There is not even a good reason to use `format!` here...

**Comment by m-ou-se** [comment]
Let's just leave `assert!()` as it is in this PR. The `assert!(expr)` case without message can be fixed, but I already have an open PR that does that. (https://github.com/rust-lang/rust/pull/78088/commits/5c5232afe716f49183f22ccb8afac25292932f5f).

Gating the changes for `assert!(expr, message)` on Rust 2021 is something for a later PR, as that edition doesn't even exist in the compiler code yet.

**Comment by m-ou-se** [comment]
> That's annoying. :/ There is not even a good reason to use `format!` here...

Yup. Quite a few of the breaking `panic!()`s are also just `panic!(format!(..))`.

**Comment by camelid** [comment]
Perhaps we could also do some kind of special-casing in `assert!` so that it can accept `String` if `std` is available? Not sure if that's possible, but wanted to throw it out.

**Comment by camelid** [comment]
I'll remove the `assert!` changes from this PR.

**Comment by m-ou-se** [comment]
> Perhaps we could also do some kind of special-casing in `assert!` so that it can accept `String` if `std` is available? Not sure if that's possible, but wanted to throw it out.

The plan is to just throw out the possibility of using anything other than a formatting string in Rust 2021. See the last two steps in the proposed solution in [RFC 3007](https://github.com/fusion-engineering-forks/rfcs/blob/panic/text/0000-panic-plan.md). (The lang team discussed it about an hour ago, and was in favour of this plan.) So I don't think it's worth making breaking changes in Rust 2018 that only partially fix things, such as making it work specifically for String but no other types.

**Comment by camelid** [comment]
By "formatting string" I assume you mean "formatting string *literal*", right?

**Comment by m-ou-se** [comment]
> By "formatting string" I assume you mean "formatting string _literal_", right?

Yes. (Although I heard some things about a potential `const fn` version of `format_args!()` in the future that could use a non-literal (but constant) formatting string.)

**Comment by camelid** [comment]
> (Although I heard some things about a potential `const fn` version of `format_args!()` in the future that could use a non-literal (but constant) formatting string.)

Yeah, I just tried that with `println!` and it didn't work. Seems like it would be nice to have!

**Comment by jyn514** [comment]
```
not found errors (from test file): [
    Error {
        line_num: 16,
        kind: Some(
            Error,
        ),
        msg: "cannot find macro `panic` in this scope",
    },
]
thread '[ui] ui/hygiene/no_implicit_prelude.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:1490:13
```
I think it should be used to a different part of the prelude instead, maybe `dbg!`?

**Comment by camelid** [comment]
Already fixed it :)

**Comment by camelid** [comment]
Looks like I need to bless mir-opt tests...

**Comment by camelid** [comment]
Rebased.

**Comment by camelid** [comment]
Perhaps someone knowledgeable with mir-opts should double-check the change in output? I just want to make sure nothing broke :)

File: src/test/ui/hygiene/no_implicit_prelude.rs [hunk 2]
```diff
@@ -1,7 +1,7 @@
 #![feature(decl_macro)]
 
 mod foo {
-    pub macro m() { Vec::new(); ().clone() }
+    pub macro m() { Vec::<i32>::new(); ().clone() }
```
Comment (camelid) [inline src/test/ui/hygiene/no_implicit_prelude.rs:4]: We don't *need* this qualification per se, but it will avoid type inference errors if some parts of the code successfully compile in the future. I can remove it if you want though.

**Comment by jonas-schievink** [comment]
Assuming the intended change here is to make `assert_eq` et al invoke `core::panic!` instead of `std::panic!` when the assertion fails, the MIR changes look expected. That seems like a bigger change than just qualifying a name though.

**Comment by m-ou-se** [comment]
`core::panic!` uses `some_internal_function(format_args!(..))`, whereas `std::panic!` uses `some_internal_function(&format_args!(..))` (note the `&`). So that explains the MIR changes.

> That seems like a bigger change than just qualifying a name though.

Both panic macros behave the same in all situations that this PR touches.

**Comment by camelid** [comment]
Note: I'd like to squash this before we merge.

**Comment by camelid** [comment]
Hm, why is CI failing? It shows the MIR opt test output has changed but it works fine locally.

**Comment by m-ou-se** [comment]
The CI checks the result of merging this PR with the main branch, not just this PR's head commit by itself. Maybe something changed there?

**Comment by camelid** [comment]
I rebased just a few hours ago...

**Comment by camelid** [comment]
> The CI checks the result of merging this PR with the main branch, not just this PR's head commit by itself.

It does? I thought only bors did that.

**Comment by m-ou-se** [comment]
If you look at the `checkout` step, you see it pulls `refs/remotes/pull/78343/merge`, not `refs/remotes/pull/78343/head`. (Not sure if GitHub documents these refs anywhere, but `/merge` is the result of merging with the target branch.)

**Comment by camelid** [comment]
It seems like there was only one small change that shouldn't have even affected this that has been merged since the base of my PR, but I rebased just in case that fixes it.

**Comment by camelid** [comment]
Hmm, `src/test/mir-opt/issue-73223.rs` is still failing on CI, but it *seems* to work fine on my machine. Maybe it's some kind of platform-specific thing.

**Comment by jyn514** [comment]
@camelid the only difference I can think of is that CI runs `--stage 2`, maybe try that locally?

**Comment by camelid** [comment]
Finished a stage 2 build. It still passes.

@jonas-schievink do you know why this might be happening?

**Comment by RalfJung** [comment]
Notice the target architecture:

> Check compiletest suite=mir-opt mode=mir-opt (x86_64-unknown-linux-gnu -> armv5te-unknown-linux-gnueabi)

This is the 32bit test which we run with an ARM target (ad 32bit x86 is broken in some older LLVM).

**Comment by camelid** [comment]
Ah, I missed that. Should I just apply the patch generated by CI then?

**Comment by RalfJung** [comment]
Depending on your host platform, you should be able to use `test src/test/mir-opt --target <...> --bless` with a 32bit target to generate the expected output.

**Comment by camelid** [comment]
Hmm, I tried that with several different platforms (including Apple ones since I'm on macOS), but all of them failed with various linker errors :/

I also tried copy-pasting the CI diff, but `patch` complains that it got "only garbage input". Any ideas?

**Comment by RalfJung** [comment]
Ah, macOS is tricky as Apple discontinued 32bit support so there might not be a compatible 32bit target. :/

@oli-obk is there any trick to update the 32bit reference files on macOS? If necessary I can also do it and push to this branch...

**Comment by camelid** [comment]
Or I could do something hacky :)

1. Modify compiletest to print out real patches
2. Push that up
3. Wait for CI to finish, then copy the patch and apply it locally
4. Then remove the compiletest mod

**Comment by m-ou-se** [comment]
> Modify compiletest to print out real patches

Or modify it to run `--bless` and commit and push the changes it to this branch. ;)

**Comment by camelid** [comment]
> Or modify it to run --bless and commit and push the changes it to this branch. ;)

Yeah, that might be more error-prone, but it could work ;)

I just realized that the test file does not seem to ignore x64. Am I misinterpreting the directives?

```rust
fn main() {
    let split = match Some(1) {
        Some(v) => v,
        None => return,
    };

    let _prev = Some(split);
    assert_eq!(split, 1);
}

// EMIT_MIR_FOR_EACH_BIT_WIDTH
// EMIT_MIR issue_73223.main.SimplifyArmIdentity.diff
// EMIT_MIR issue_73223.main.PreCodegen.diff
```

**Comment by m-ou-se** [comment]
> `// EMIT_MIR_FOR_EACH_BIT_WIDTH`

This means it's run for both 64-bit and 32-bit targets. You already updated the output file for 64-bit, but the 32-bit one still needs updating.

**Comment by m-ou-se** [comment]
I ran `--bless` for 32-bit:
```
git pull --ff https://github.com/fusion-engineering-forks/rust macros-qualify-panic
```

**Comment by camelid** [comment]
Thanks!

**Comment by m-ou-se** [comment]
I found two cases of people relying on these macros not qualifying the `panic!()` call:

1. https://github.com/gamozolabs/orange_slice/blob/master/bootloader/src/main.rs#L16-L18
2. https://github.com/japaric/utest/blob/master/README.md#testing-on-an-emulated-cortex-m-processor

**Comment by m-ou-se** [comment]
Hm, looks like `rust/compiler-builtins`' test crate also relies on it: https://github.com/rust-lang/compiler-builtins/blob/master/testcrate/tests/aeabi_memclr.rs

**Comment by camelid** [comment]
That's unfortunate :/

It *is* an implementation detail, but ideally we wouldn't break so much without providing a solution. Maybe we could provide some kind of attribute that you apply to override the implementation of `panic!`? Pseudo-code:

```rust
#[panic_macro]
macro_rules! mypanic { /* ... */ }
```

But that doesn't feel like a great solution. What can we do about this?

**Comment by RalfJung** [comment]
The "proper" solution is `#[panic_handler]`. It might just be that that code predates stabilization of this attribute?

**Comment by m-ou-se** [comment]
There's already an attribute to implement custom panicking behaviour: `#[panic_handler]`.

I think it's fine to break those few cases. It came up in the lang team meeting yesterday, and people agreed this is just fixing a hygiene bug.

**Comment by camelid** [comment]
> The "proper" solution is [`#[panic_handler]`](https://doc.rust-lang.org/reference/runtime.html). It might just be that that code predates stabilization of this attribute?

Yeah, I was wondering if that was relevant.

**Comment by camelid** [comment]
Maybe we could print some kind of warning (or have a lint) if someone defines their own `panic!` macro that encourages them to use `#[panic_handler]`? I'm just wondering if there could be any false-positives.

**Comment by m-ou-se** [comment]
The first case only matches `panic!()` and `panic!(expr)` and no other forms, so would already break anyway with `assert_eq`. The comment only talks about `assert!()`, which this PR does not change.

As for the other two: [one of the last commits](https://github.com/japaric/utest/commit/3ca883dfdf92f51a028e940c7c2050a6ca114cd6) to μtest was in 2017, working around another change in Rust that broke the way it was overriding `panic!()`. :upside_down_face:

**Comment by camelid** [comment]
Squashed!

**Comment by camelid** [comment]
@m-ou-se Ready for a new `r+` :)

**Comment by lzutao** [comment]
So we don't need FCP for this change?

**Comment by jyn514** [comment]
@lzutao see https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Potential.20very.20small.20breakage.20by.20qualifying.20panic for discussion.

**Comment by jyn514** [comment]
```
 ---- [ui] ui/iterators/iter-count-overflow-ndebug.rs stdout ----
normalized stderr:
warning: unused import: `std::panic`
  --> $DIR/iter-count-overflow-ndebug.rs:5:5
   |
LL | use std::panic;
   |     ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

 stderr:
------------------------------------------
warning: unused import: `std::panic`
  --> /checkout/src/test/ui/iterators/iter-position-overflow-ndebug.rs:5:5
   |
LL | use std::panic;
   |     ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted
```

**Comment by lzutao** [comment]
> see https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Potential.20very.20small.20breakage.20by.20qualifying.20panic for discussion.

Thank you. But I haven't seen other lib team members comment about this change.
Consider that this PR causes a breaking change (even very small), I would expect all members
of lib team acknowledge and sign off for it.

**Comment by m-ou-se** [comment]
Many changes to the standard library can technically break something that relies on an implementation detail. Considering: - this is just a hygiene bug fix; - it does not break any documented/stable behaviour; - we already investigated potential breakage; - we discussed this on Zulip; - we discussed this here; - it was discussed in the lang team meeting; - the RFC this is part of was discussed in the libs meeting; - the beta crater run will catch anything we might have missed; and - it's trivial to revert in case it does break something, I don't think we need to be any more careful with this change than we already are. It's not worth waiting for the entire team to sign off small bug fixes. That just unecessarily delays PRs like this. FCPs are mostly important for changes that are not easily undone, such as stabilizing a new function.

**Comment by lzutao** [comment]
Thank you for addressing my personal concerns. 
I've seen lib team merged PRs without waiting for 10 days for final comment period,
so the delay will be smaller if most team members agree for the change.

Anyway, since you've addressed my personal concerns, I don't have anything to add.
To be honest, I really like this bug fix.

**Comment by m-ou-se** [comment]
@bors delegate+

If you just remove those two `use std::panic;`s, use `@bors r=m-ou-se` afterwards.

**Comment by m-ou-se** [comment]
Apparently bors reacts to stuff between backticks too?

@bors r-

**Comment by m-ou-se** [comment]
Looks like Clippy no longer sees `unimplemented!(..)` (etc.) as a panic?

**Comment by camelid** [comment]
Asked on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/question.20re.20PR

**Comment by m-ou-se** [comment]
Apparently Clippy doesn't detect `core::panic!()`, only `std::panic!()`. Marking this as blocked on that issue. :(

**Comment by camelid** [comment]
I'm hoping to get to this soon :)

**Comment by camelid** [comment]
@flip1995 This ready for your review of the Clippy changes :)

**Review by camelid — COMMENTED** [review]
There were several spots in Clippy that were only matching on `begin_panic`. All of those have been changed to match on `begin_panic`, `begin_panic_fmt`, `panic_any`, `panicking::panic`, `panicking::panic_fmt`, or `panicking::panic_str`. Let me know if they were intentionally only matching on `begin_panic`, and if so what I should change them to!

File: src/tools/clippy/clippy_lints/src/utils/mod.rs [hunk 3]
```diff
@@ -1230,6 +1230,27 @@ pub fn match_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId, syms: &[&str]) -
     cx.match_def_path(did, &syms)
 }
 
+pub fn match_panic_call<'tcx>(
+    cx: &LateContext<'tcx>,
+    expr: &'tcx Expr<'_>,
+) -> Option<&'tcx [Expr<'tcx>]> {
+    match_function_call(cx, begin_panic_call, &paths::BEGIN_PANIC)
```
Comment (flip1995) [inline src/tools/clippy/clippy_lints/src/utils/mod.rs:1237]:
```rust
    match_function_call(cx, begin_panic_call, &paths::BEGIN_PANIC)
    //                      ^^^^^^^^^^^^^^^^ this does not exist
```

File: src/tools/clippy/clippy_lints/src/panic_unimplemented.rs [hunk 4]
```diff
@@ -96,8 +96,7 @@ impl<'tcx> LateLintPass<'tcx> for PanicUnimplemented {
         if_chain! {
             if let ExprKind::Block(ref block, _) = expr.kind;
             if let Some(ref ex) = block.expr;
-            if let Some(params) = match_function_call(cx, ex, &paths::BEGIN_PANIC)
-                .or_else(|| match_function_call(cx, ex, &paths::BEGIN_PANIC_FMT));
+            if let Some(params) = match_panic_call(cx, ex, &paths::BEGIN_PANIC);
```
Comment (flip1995) [inline src/tools/clippy/clippy_lints/src/panic_unimplemented.rs:99]:
```suggestion
            if let Some(params) = match_panic_call(cx, ex);
```

File: src/tools/clippy/clippy_lints/src/utils/mod.rs [hunk 5]
```diff
@@ -1230,6 +1230,27 @@ pub fn match_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId, syms: &[&str]) -
...
+        .or_else(|| match_function_call(cx, begin_panic_call, &paths::BEGIN_PANIC_FMT))
+        .or_else(|| match_function_call(cx, begin_panic_call, &paths::PANIC_ANY))
+        .or_else(|| match_function_call(cx, begin_panic_call, &paths::PANICKING_PANIC))
+        .or_else(|| match_function_call(cx, begin_panic_call, &paths::PANICKING_PANIC_FMT))
+        .or_else(|| match_function_call(cx, begin_panic_call, &paths::PANICKING_PANIC_STR))
```
Comment (flip1995) [inline src/tools/clippy/clippy_lints/src/utils/mod.rs:1242]:
```suggestion
    match_function_call(cx, expr, &paths::BEGIN_PANIC)
        .or_else(|| match_function_call(cx, expr, &paths::BEGIN_PANIC_FMT))
        .or_else(|| match_function_call(cx, expr, &paths::PANIC_ANY))
        .or_else(|| match_function_call(cx, expr, &paths::PANICKING_PANIC))
        .or_else(|| match_function_call(cx, expr, &paths::PANICKING_PANIC_FMT))
        .or_else(|| match_function_call(cx, expr, &paths::PANICKING_PANIC_STR))
```

I think this should be.

File: src/tools/clippy/clippy_lints/src/utils/mod.rs [hunk 6]
```diff
@@ -1230,6 +1230,27 @@ pub fn match_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId, syms: &[&str]) -
...
+}
+
+pub fn match_panic_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId) -> bool {
```
Comment (flip1995) [inline src/tools/clippy/clippy_lints/src/utils/mod.rs:1245]: NIT:

```suggestion
pub fn match_panic_def_id<'tcx>(cx: &LateContext<'tcx>, did: DefId) -> bool {
```

would be the better name here IMO

**Review by flip1995 — COMMENTED** [review]
> Let me know if they were intentionally only matching on `begin_panic`, and if so what I should change them to!

Don't know if they were intentional. If they were, I hope the ui tests will show.

Please make sure that `./x.py test src/tools/clippy` passes for you locally. Most of my review is me playing the compiler 😉

**Comment by camelid** [comment]
Oops, thanks for the playing the compiler ;)

**Comment by m-ou-se** [comment]
Can you put the clippy changes in a separate PR? Makes it easier to have those changes reviewed and approved separately.

**Comment by camelid** [comment]
I don't think there's a good way to do that because Clippy output is changed by this PR if you skip the Clippy changes.

**Comment by flip1995** [comment]
> Can you put the clippy changes in a separate PR?

Nope, Clippy is gated by bors and will soon be in PR CI. This is intentional to never have a broken Clippy in a nightly. (That's the main reason we use `git subtree` for Clippy and most recently also for cg_clif)

**Comment by m-ou-se** [comment]
Well, yes, the clippy PR will have to be merged first. There you can just add a test that it now reacts to `core::panic!` too.

With all changes in a single PR this gets a bit unwieldy. There's no no single person who can approve the PR as a whole, as it is both a libs and a clippy change. The clippy change should be entirely independent, right?

**Comment by camelid** [comment]
Oh, I see what you mean :)

That sounds fine. I'll drop the clippy commit and mark this as blocked, and then I'll open a new PR that has the clippy changes.

**Comment by flip1995** [comment]
> There's no no single person who can approve the PR as a whole, as it is both a libs and a clippy change. The clippy change should be entirely independent, right?

Is this a problem though? We can both separately approve this PR and then `bors r=m-ou-se,flip1995`. The process for Clippy/`subtree`s is to fix it right in the PR that breaks it, to _not_ have to do separate Clippy PRs to unbreak it.

**Comment by m-ou-se** [comment]
The discussion on this PR is already over a hundred comments long. I rather not also add the discussion about the clippy changes as well. That'd make it even harder to find any information back about this PR and the reasoning behind the changes.

More importantly, the clippy changes fix an independent bug that clippy already had: that it doesn't react to `core::panic`. It doesn't fix anything that was broken by this PR, it just fixes a pre-existing bug that was uncovered by this PR.

**Comment by camelid** [comment]
Rebased.

**Comment by camelid** [comment]
Rebased to get the changes this was blocked on!

**Comment by m-ou-se** [comment]
Nice! `r=me` when the checks pass.

**Comment by camelid** [comment]
Looks like Git included conflict markers in the MIR-opt test output... Blessing.

**Comment by camelid** [comment]
@m-ou-se Could you bless the tests? I think it's the whole architecture-specific tests issue we had before.

**Comment by Aaron1011** [comment]
Added the `relnotes` tag - the fact that you can no longer 'intercept' certain calls to `panic!` seems worth mentioning in the compatibility notes.

**Comment by camelid** [comment]
Note to whoever writes the relnotes for this: You can no longer 'intercept' `panic!`; instead you should probably use `#[panic_handler]`.

**Comment by camelid** [comment]
It seems like Clippy tests need to be blessed?

**Comment by m-ou-se** [comment]
> It seems like Clippy tests need to be blessed?

How come the output changed? Shouldn't it stay the same as before?

**Comment by camelid** [comment]
I'm not fully sure; it seems like Clippy is picking up on more things now?

**Comment by m-ou-se** [comment]
@flip1995 ^

**Comment by camelid** [comment]
@m-ou-se Also see the [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/blessing.20clippy.20tests.20in-tree).

**Comment by flip1995** [comment]
Don't bless the tests, just allow them in the affected test files. Those files aren't meant for testing this lint anyway.

The patch to apply:

```diff
diff --git a/tests/ui/logic_bug.rs b/tests/ui/logic_bug.rs
index b4163d776..a01c6ef99 100644
--- a/src/tools/clippy/tests/ui/logic_bug.rs
+++ b/src/tools/clippy/tests/ui/logic_bug.rs
@@ -1,4 +1,4 @@
-#![allow(unused, clippy::many_single_char_names)]
+#![allow(unused, clippy::many_single_char_names, clippy::diverging_sub_expression)]
 #![warn(clippy::logic_bug)]
 
 fn main() {
diff --git a/tests/ui/nonminimal_bool.rs b/tests/ui/nonminimal_bool.rs
index 7ea154cb9..971be2627 100644
--- a/src/tools/clippy/tests/ui/nonminimal_bool.rs
+++ b/src/tools/clippy/tests/ui/nonminimal_bool.rs
@@ -1,4 +1,4 @@
-#![allow(unused, clippy::many_single_char_names)]
+#![allow(unused, clippy::many_single_char_names, clippy::diverging_sub_expression)]
 #![warn(clippy::nonminimal_bool)]
 
 fn main() {
diff --git a/tests/ui/nonminimal_bool_methods.rs b/tests/ui/nonminimal_bool_methods.rs
index 4de48cd08..907587402 100644
--- a/src/tools/clippy/tests/ui/nonminimal_bool_methods.rs
+++ b/src/tools/clippy/tests/ui/nonminimal_bool_methods.rs
@@ -1,4 +1,4 @@
-#![allow(unused, clippy::many_single_char_names)]
+#![allow(unused, clippy::many_single_char_names, clippy::diverging_sub_expression)]
 #![warn(clippy::nonminimal_bool)]
 
 fn methods_with_negation() {
diff --git a/tests/ui/wildcard_enum_match_arm.fixed b/tests/ui/wildcard_enum_match_arm.fixed
index 4f8754a93..b1e5742b7 100644
--- a/src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed
+++ b/src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed
@@ -7,7 +7,7 @@
     dead_code,
     clippy::single_match,
     clippy::wildcard_in_or_patterns,
-    clippy::unnested_or_patterns
+    clippy::unnested_or_patterns, clippy::diverging_sub_expression
 )]
 
 use std::io::ErrorKind;
diff --git a/tests/ui/wildcard_enum_match_arm.rs b/tests/ui/wildcard_enum_match_arm.rs
index 5e66644ce..cd3ec3ea8 100644
--- a/src/tools/clippy/tests/ui/wildcard_enum_match_arm.rs
+++ b/src/tools/clippy/tests/ui/wildcard_enum_match_arm.rs
@@ -7,7 +7,7 @@
     dead_code,
     clippy::single_match,
     clippy::wildcard_in_or_patterns,
-    clippy::unnested_or_patterns
+    clippy::unnested_or_patterns, clippy::diverging_sub_expression
 )]
 
 use std::io::ErrorKind;

**Comment by camelid** [comment]
Thanks for providing that patch :)

File: src/test/ui/hygiene/no_implicit_prelude.stderr [hunk 7]
```diff
@@ -1,8 +1,8 @@
 error: cannot find macro `panic` in this scope
   --> $DIR/no_implicit_prelude.rs:16:9
    |
-LL |         assert_eq!(0, 0);
-   |         ^^^^^^^^^^^^^^^^^
+LL |         assert!(true);
+   |         ^^^^^^^^^^^^^^
```
Comment (m-ou-se) [inline src/test/ui/hygiene/no_implicit_prelude.stderr:5]: This test now fails, because `assert!(expr)` was fixed very recently on the main branch to call into `core::` directly.

The history of this test is interesting:

It was originally a `println!()` to check that on edition 2015 macros still get imported even without the prelude. Then `println!()` started calling `print!()` without hygiene, which broke this test. That was simply --blessed, such that it started to test for the failure of not finding `print!()` instead.

Then when `println!()` became hygienic and started working again, the test was not fixed and changed back, but instead changed to `assert_eq!(0, 0)`, probably because the person making the change assumed this test was supposed to test for this error. (:

So the original intention was not to check that this fails, but to check that this works. So this test should probably be blessed to restore the original intention.

Comment (camelid) [reply src/test/ui/hygiene/no_implicit_prelude.stderr:5]: What should I do given that the test passes locally but fails on CI?

Comment (jyn514) [reply src/test/ui/hygiene/no_implicit_prelude.stderr:5]: > This test now fails, because assert!(expr) was fixed very recently on the main branch to call into core:: directly.

That sounds like you need to rebase over master.

Comment (camelid) [reply src/test/ui/hygiene/no_implicit_prelude.stderr:5]: Thanks! You're probably right. I forgot that CI merges 'master' into the branch 🤦

**Comment by camelid** [comment]
Rebased.

**Comment by camelid** [comment]
CI *should* pass now.

File: src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed [hunk 8]
```diff
@@ -7,7 +7,8 @@
     dead_code,
     clippy::single_match,
     clippy::wildcard_in_or_patterns,
-    clippy::unnested_or_patterns
+    clippy::unnested_or_patterns,
+    clippy::diverging_sub_expression
```
Comment (flip1995) [inline src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed:11]: With this change you have to adapt the `stderr` file, because every error moved one line. You could either +1 every line number in the `stderr` file or change this to
```suggestion
    clippy::unnested_or_patterns, clippy::diverging_sub_expression
```

and we'll fix the formatting during sync.

File: src/tools/clippy/tests/ui/wildcard_enum_match_arm.rs [hunk 9]
```diff
@@ -7,7 +7,8 @@
     dead_code,
     clippy::single_match,
     clippy::wildcard_in_or_patterns,
-    clippy::unnested_or_patterns
+    clippy::unnested_or_patterns,
+    clippy::diverging_sub_expression
```
Comment (flip1995) [inline src/tools/clippy/tests/ui/wildcard_enum_match_arm.rs:11]:
```suggestion
    clippy::unnested_or_patterns, clippy::diverging_sub_expression
```

Also leaving this comment here, so you could use GitHubs UI to make this change, if you want.

File: src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed (hunk 8 above)
Comment (camelid) [reply src/tools/clippy/tests/ui/wildcard_enum_match_arm.fixed:11]: I just squeezed it onto the same line so that we can get this merged :)

**Comment by camelid** [comment]
Squashed.

**Comment by m-ou-se** [comment]
🎉  Thanks for making this happen, @camelid!

**Comment by camelid** [comment]
Thanks for helping me with this, @m-ou-se and @flip1995!
