### PR TITLE
GVN: Only propagate borrows from SSA locals

### LINKED ISSUE #141313: GVN misunderstands aliasing, can create overlapping assignments (again)
This looks very similar to https://github.com/rust-lang/rust/issues/141038, but the compiler that found this has the patch that was linked to that issue.

Reduced example from rustlantis, which is accepted by Miri without optimizations enabled:
```rust
#![feature(custom_mir, core_intrinsics)]
#![allow(internal_features)]

use std::intrinsics::mir::*;

#[custom_mir(dialect = "runtime")]
fn main() {
    mir!{
        let _1;
        let _2;
        let _3;
        {
            place!(Field(Variant(_1, 1), 0)) = 0u8;
            _3 = &_1;
            _2 = Field(Variant(*_3, 1), 0);
            _1 = Adt::Some(_2);
            Return()
        }
    }
}

#[allow(dead_code)]
enum Adt {
    None,
    Some(u8),
}
```

If I run this under Miri with `-Zmir-enable-passes=+GVN`, I see:
```
error: Undefined Behavior: `copy_nonoverlapping` called on overlapping ranges
  --> 4243580941269764965.rs:16:13
   |
16 |             _1 = Adt::Some(_2);
   |             ^^^^^^^^^^^^^^^^^^ `copy_nonoverlapping` called on overlapping ranges
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `main` at 4243580941269764965.rs:16:13: 16:31
```

The MIR diff for GVN is:
```diff
-// MIR for `main` before GVN
+// MIR for `main` after GVN
 
 fn main() -> () {
     let mut _0: ();
     let mut _1: Adt;
     let mut _2: u8;
     let mut _3: &Adt;
 
     bb0: {
         ((_1 as variant#1).0: u8) = const 0_u8;
         _3 = &_1;
         _2 = copy (((*_3) as variant#1).0: u8);
-        _1 = Adt::Some(copy _2);
+        _1 = copy (*_3);
         return;
     }
 }
```

```
rustc 1.89.0-nightly (60dabef95 2025-05-19)
binary: rustc
commit-hash: 60dabef95a3de3ec974dcb50926e4bfe743f078f
commit-date: 2025-05-19
host: aarch64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.5
```

### PR DESCRIPTION
**Pull request by dianqk**
Fixes https://github.com/rust-lang/rust/issues/141313. This is a more principled fix than https://github.com/rust-lang/rust/pull/147886.

Using a reference that is not a borrowing of an SSA local at a new location may be UB.

The PR has two major changes.

The first one, when introducing a new dereference at a new location, is that the reference must point to an SSA local or be an immutable argument. `dereference_address` has handled SSA locals.

The second one, if we cannot guard to the reference point to an SSA local in `visit_assign`, we have to rewrite the value to opaque. This avoids unifying the following dereferences that also are references:

```rust
let b: &T = *a;
// ... `a` is allowed to be modified. `c` and `b` have different borrowing lifetime.
// Unifying them will extend the lifetime of `b`.
let c: &T = *a; 
```

See also https://github.com/rust-lang/rust/issues/130853.

This still allows unifying non-reference dereferences:

```rust
let a: &T = ...;
let b: T = *a;
// ... a is NOT allowed to be modified.
let c: T = *a; 
```

r? @cjgillot

### CODE REVIEW

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 1]
```diff
@@ -541,18 +538,6 @@ impl<'body, 'a, 'tcx> VnState<'body, 'a, 'tcx> {
...
-        self.derefs.push(value);
-        value
-    }
-
-    fn invalidate_derefs(&mut self) {
-        for deref in std::mem::take(&mut self.derefs) {
-            self.values.forget(deref);
-        }
-    }
-
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs:555]: Glad to see this gone.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 2]
```diff
@@ -473,6 +466,10 @@ impl<'body, 'a, 'tcx> VnState<'body, 'a, 'tcx> {
             projection.next();
             AddressBase::Deref(base)
         } else {
+            // Only propagate the pointer of the SSA local.
+            if !self.ssa.is_ssa(place.local) {
+                return None;
+            }
             AddressBase::Local(place.local)
         };
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]:
```suggestion
        } else if self.ssa.is_ssa(place.local) {
            // Only propagate the pointer of the SSA local.
            AddressBase::Local(place.local)
        } else {
            return None;
        };
```

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 3]
```diff
@@ -818,7 +803,13 @@ impl<'body, 'a, 'tcx> VnState<'body, 'a, 'tcx> {
...
                     // An immutable borrow `_x` always points to the same value for the
                     // lifetime of the borrow, so we can merge all instances of `*_x`.
-                    return Some((projection_ty, self.insert_deref(projection_ty.ty, value)));
+                    return Some((
+                        projection_ty,
+                        self.insert(
+                            projection_ty.ty,
+                            Value::Projection(value, ProjectionElem::Deref),
+                        ),
+                    ));
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]:
```suggestion
                    let deref = self.insert(
                        projection_ty.ty,
                        Value::Projection(value, ProjectionElem::Deref),
                    );
                    return Some((projection_ty, deref));
```

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 4]
```diff
@@ -1142,13 +1133,48 @@ impl<'body, 'a, 'tcx> VnState<'body, 'a, 'tcx> {
...
+                        break;
+                    }
+                    return None;
+                }
+                _ => {
+                    return None;
+                }
+            }
+        }
+
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]: Should this go in `try_as_place`?

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 5]
```diff
@@ -1906,14 +1923,34 @@ impl<'tcx> MutVisitor<'tcx> for VnState<'_, '_, 'tcx> {
...
+                | Value::BinaryOp(..)
+                | Value::Cast { .. } => {}
+                Value::Aggregate(..)
+                | Value::Union(..)
+                | Value::Repeat(..)
+                | Value::Discriminant(..)
+                | Value::RuntimeChecks(..)
+                | Value::UnaryOp(..) => unreachable!(),
+            }
         }
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]: I don't understand what this does. Why are some values unreachable? A constant and a cast can be a reference, can't it?

Comment (dianqk) [reply compiler/rustc_mir_transform/src/gvn.rs]: They are not marked as unreachable. The new change should be clearer.

File: compiler/rustc_mir_transform/src/gvn.rs (hunk 4 above)
Comment (dianqk) [reply compiler/rustc_mir_transform/src/gvn.rs]: Done. This introduces a small regression that reborrows cannot be propagated, but I think ReferencePropagation has done this.
And `&(*_2)` can be `copy _2`, since reborrows extend the lifetime of borrows. This can be a subsequent PR if needed.

File: tests/mir-opt/dont_reset_cast_kind_without_updating_operand.test.GVN.32bit.panic-abort.diff [hunk 6]
```diff
@@ -144,12 +143,10 @@
...
           _2 = &_3;
           _1 = &(*_2);
--         StorageDead(_2);
+          StorageDead(_2);
 -         StorageLive(_5);
--         _10 = copy (*_1);
-+         nop;
 +         nop;
-+         _10 = copy (*_2);
+          _10 = copy (*_1);
```
Comment (dianqk) [inline tests/mir-opt/dont_reset_cast_kind_without_updating_operand.test.GVN.32bit.panic-abort.diff:149]: Can be `_10 = copy (*_2);`.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 7]
```diff
@@ -1906,14 +1921,35 @@ impl<'tcx> MutVisitor<'tcx> for VnState<'_, '_, 'tcx> {
...
+        // For instance, we cannot unify two pointers that dereference same local, because they may
+        // have different lifetimes.
+        if rvalue_ty.is_ref()
+            && let Some(index) = value
+        {
+            match self.get(index) {
+                Value::Projection(..) => {
+                    value = None;
+                }
+                Value::Opaque(_)
```
Comment (dianqk) [inline compiler/rustc_mir_transform/src/gvn.rs]: The latest change allows the opaque value to be propagated. For `let a: &T = b;`, `a` extends the lifetime of `b`.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 8]
```diff
@@ -1834,6 +1814,45 @@ impl<'tcx> VnState<'_, '_, 'tcx> {
         let mut projection = SmallVec::<[PlaceElem<'tcx>; 1]>::new();
         loop {
             if let Some(local) = self.try_as_local(index, loc) {
+                if projection.last() == Some(&PlaceElem::Deref) {
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]: Can this be moved as a case `if let Value::Projection(pointer, ProjectionElem::Deref) = self.get(index)` below? That would be the only way to get a deref as last place.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 9]
```diff
@@ -1834,6 +1814,45 @@ impl<'tcx> VnState<'_, '_, 'tcx> {
...
+                                deref_root = base;
+                            }
+                            Value::Address {
+                                base,
+                                projection,
+                                kind: AddressKind::Ref(BorrowKind::Shared),
+                                ..
+                            } if projection.iter().all(ProjectionElem::is_stable_offset) => {
+                                match base {
+                                    AddressBase::Local(_) => {
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]: Should we debug_assert that this local is SSA?

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 10]
```diff
@@ -1834,6 +1814,45 @@ impl<'tcx> VnState<'_, '_, 'tcx> {
         let mut projection = SmallVec::<[PlaceElem<'tcx>; 1]>::new();
         loop {
             if let Some(local) = self.try_as_local(index, loc) {
+                if projection.last() == Some(&PlaceElem::Deref) {
+                    // We can introduce a new dereference if the source value cannot be changed in the body.
+                    let mut deref_root = index;
+                    loop {
+                        let ty = self.ty(deref_root);
+                        match self.get(deref_root) {
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/gvn.rs]: The different cases in this match deserve a few comments.

File: tests/mir-opt/pre-codegen/slice_filter.variant_a-{closure#0}.PreCodegen.after.mir [hunk 11]
```diff
@@ -3,101 +3,107 @@
...
-        // DBG: _16 = &((*_3).3: usize);
-        StorageLive(_6);
-        // DBG: _17 = &_13;
-        // DBG: _18 = &?;
-        _4 = copy ((*_3).0: usize);
-        _5 = copy ((*_3).2: usize);
-        _6 = Le(copy _4, copy _5);
-        switchInt(move _6) -> [0: bb2, otherwise: bb1];
+        // DBG: _16 = &((*_3).0: usize);
+        _4 = copy (*_2);
```
Comment (cjgillot) [inline tests/mir-opt/pre-codegen/slice_filter.variant_a-{closure#0}.PreCodegen.after.mir:72]: Why does this stop unifying with `_3`?

**Review by cjgillot — COMMENTED** [review]
~Do you mind pre-commiting the new tests? This will make the changes easier to review.~ EDIT: Sorry, I misread.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150485/eda76d9d1d133effbf7facb28168fd78d75fd434..30561d92498fc154039b825ce4e44cd2781c9d9f)*

File: compiler/rustc_mir_transform/src/gvn.rs (hunk 10 above)
Comment (dianqk) [reply compiler/rustc_mir_transform/src/gvn.rs]: The new change should be more understandable. Those cases may not be necessary. https://github.com/rust-lang/rust/compare/30561d92498fc154039b825ce4e44cd2781c9d9f..810907c29e64ac6149b6672714f92b6c02abb441

File: tests/mir-opt/pre-codegen/slice_filter.variant_a-{closure#0}.PreCodegen.after.mir (hunk 11 above)
Comment (dianqk) [reply tests/mir-opt/pre-codegen/slice_filter.variant_a-{closure#0}.PreCodegen.after.mir:72]: This is what I mention as the second change. And it is the same as https://github.com/rust-lang/rust/issues/130853. We cannot unify the dereferences if they are also references because they can extend the lifetime of references.

Comment (dianqk) [reply tests/mir-opt/pre-codegen/slice_filter.variant_a-{closure#0}.PreCodegen.after.mir:72]: I modified the description some.

File: compiler/rustc_mir_transform/src/gvn.rs [hunk 12]
```diff
@@ -815,10 +799,24 @@ impl<'body, 'a, 'tcx> VnState<'body, 'a, 'tcx> {
...
+                    // have different lifetimes.
+                    // ```
+                    // let b: &T = *a;
+                    // ... `a` is allowed to be modified. `c` and `b` have different borrowing lifetime.
+                    // Unifying them will extend the lifetime of `b`.
+                    // let c: &T = *a;
+                    // ```
+                    if projection_ty.ty.is_ref() {
+                        return None;
+                    }
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/gvn.rs:813]: I do not understand how this check is enough. What if we have a `&(&T,)` type? Then the projection_ty is a tuple, not a reference, but it *contains* a reference and that could still lead to the same problems, couldn't it?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/150485/930ecbcdf8905c5c8549056c73fcabdd8d6e1b3d..9c029d2102b76ea1bab41062a26d144e342a4713)*
