### PR TITLE
Tighten the 'introduce new binding' suggestion

### LINKED ISSUE #104086: Tighten "introduce new binding" suggestion
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9c41f6b7b4e29f2c340c5fcc95bd815b)

```rust
fn main() {
    x = x = x;
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `x` in this scope
 --> src/main.rs:2:5
  |
2 |     x = x = x;
  |     ^
  |
help: you might have meant to introduce a new binding
  |
2 |     let x = x = x;
  |     +++

error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `x` in this scope
 --> src/main.rs:2:9
  |
2 |     x = x = x;
  |         ^
  |
help: you might have meant to introduce a new binding
  |
2 |     x = let x = x;
  |         +++

error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `x` in this scope
 --> src/main.rs:2:13
  |
2 |     x = x = x;
  |             ^
  |
help: you might have meant to introduce a new binding
  |
2 |     x = x = let x;
  |             +++

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to 3 previous errors
```

Ideally the output should first check the RHS, before suggest adding `let`. It should also avoid suggesting when code is invalid. Thanks.

Something like this should also not suggest adding `let`: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=16a2ed0829546a6134c0e598ddb5cc71)
```rust
fn main() {
    x = i32
}
```
```
Compiling playground v0.0.1 (/playground)
error[[E0425]](https://doc.rust-lang.org/nightly/error-index.html#E0425): cannot find value `x` in this scope
 --> src/main.rs:2:5
  |
2 |     x = i32
  |     ^
  |
help: you might have meant to introduce a new binding
  |
2 |     let x = i32
  |     +++

error[[E0423]](https://doc.rust-lang.org/nightly/error-index.html#E0423): expected value, found builtin type `i32`
 --> src/main.rs:2:9
  |
2 |     x = i32
  |         ^^^ not a value
  |
help: consider importing one of these items instead
  |
1 | [use fastrand::i32;](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)
  |
1 | [use nom::character::complete::i32;](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)
  |
1 | [use nom::character::streaming::i32;](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)
  |
1 | [use nom::number::complete::i32;](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)
  |
    and 1 other candidate

Some errors have detailed explanations: E0423, E0425.
For more information about an error, try `rustc --explain E0423`.
error: could not compile `playground` due to 2 previous errors
```

cc @chenyukang

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #104086

### CODE REVIEW

File: src/test/ui/suggestions/issue-104086-suggest-let.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// error-pattern: not found in this scope
```
Comment (oli-obk) [inline src/test/ui/suggestions/issue-104086-suggest-let.rs:1]: Please use `//~^` style patterns instead of `// error-pattern`

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -1810,18 +1810,27 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
 
-    fn let_binding_suggestion(&self, err: &mut Diagnostic, ident_span: Span) -> bool {
+    fn let_binding_suggestion(&mut self, err: &mut Diagnostic, ident_span: Span) -> bool {
         // try to give a suggestion for this pattern: `name = 1`, which is common in other languages
         let mut added_suggestion = false;
-        if let Some(Expr { kind: ExprKind::Assign(lhs, _rhs, _), .. }) = self.diagnostic_metadata.in_assignment &&
-            let ast::ExprKind::Path(None, _) = lhs.kind {
+        if let Some(Expr { kind: ExprKind::Assign(lhs, rhs, _), .. }) =
+            self.diagnostic_metadata.in_assignment
+        {
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1818]: slightly odd formatting. Will rustfmt accept it if it is all in one line?

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1810,18 +1810,27 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+            let is_rhs_assign = match rhs.kind {
+                ExprKind::Assign(..) => true,
+                _ => false,
+            };
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1822]:
```suggestion
            let is_rhs_assign = matches!(rhs.kind, ExprKind::Assign(..));
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 4]
```diff
@@ -1810,18 +1810,27 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
-                // HACK(chenyukang): make sure ident_name is at the starting of the line to protect against macros
-                if sm
-                    .span_to_snippet(line_span)
-                    .map_or(false, |s| s.trim().starts_with(&ident_name))
+                // HACK(chenyukang): make sure ident_name is at the starting of the line to protect against macros,
+                // and avoid some special cases like `x = x = x`
+                if let Ok(line) = sm.span_to_snippet(line_span) &&
+                    let stripped = line.split_whitespace().collect::<String>() &&
+                    stripped.trim().starts_with(&ident_name) &&
+                    stripped.matches(&format!("{}=", &ident_name)).count() == 1
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1833]: is this really necessary? We could just propose the `let` everywhere.

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1829]: This is weird 😂
image

Comment (oli-obk) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1829]: I think we should avoid the entire `source_map` usage. It is very fragile. Maybe try using `tcx.hir().get_parent_node(hir_id)` and check if that is an assignment and bail out then.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 5]
```diff
@@ -1810,18 +1810,23 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
-    fn let_binding_suggestion(&self, err: &mut Diagnostic, ident_span: Span) -> bool {
+    fn let_binding_suggestion(&mut self, err: &mut Diagnostic, ident_span: Span) -> bool {
         // try to give a suggestion for this pattern: `name = 1`, which is common in other languages
         let mut added_suggestion = false;
-        if let Some(Expr { kind: ExprKind::Assign(lhs, _rhs, _), .. }) = self.diagnostic_metadata.in_assignment &&
-            let ast::ExprKind::Path(None, _) = lhs.kind {
+        if let Some(Expr { kind: ExprKind::Assign(lhs, rhs, _), .. }) =
+            self.diagnostic_metadata.in_assignment
+        {
+            let is_rhs_assign = matches!(rhs.kind, ExprKind::Assign(..));
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1819]: does this actually have any effect?

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1829]: It's name resolving phase here, we haven't built `hir` related data structures...

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 5 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1819]: Yes, it will avoid this:

```rust
help: you might have meant to introduce a new binding
   |
13 |     let x = y = y;
   |     +++
```

Comment (oli-obk) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1819]: that seems fine I think?

Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1819]: It's fine in syntax, the `x` will be `()`.
But maybe not the intention of users, it's Ok if you think we could suggest it.

Comment (oli-obk) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1819]: Yea, it keeps the logic here simpler, so let's just do that for now.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 4 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1829]: As far as I know, we have `parent_scope`.
To make life easier for diagnostics, we have this to store some info when walking the AST.

https://github.com/rust-lang/rust/blob/0aaad9e757207657064d70bf9e6c1e6eb327bf15/compiler/rustc_resolve/src/late.rs#L490

It's common to use `source_map` in diagnostics in parsing and resolving phase, but we should limited it for the usage of reducing some false tip or useless diagnostics.

Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: I tried to introduced a new variable `is_assign_rhs`, it works as expected.

But we still can not avoid `source_map` totally, for example this code:

```rust
 while x = blah {
 ....
}
```

We don't want to suggest to `while let x = blah`.

And diagnostics reporting is on error handling path, but add `is_assign_rhs` is on normal code path, so I'm not sure whether it's worth.

Maybe we should tolerate ugly code for better performance? 😁
Anyway, we are handling this kind of special werid case:
`x = x = x = y`

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 6]
```diff
@@ -1810,19 +1810,17 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+    fn let_binding_suggestion(&mut self, err: &mut Diagnostic, ident_span: Span) -> bool {
         // try to give a suggestion for this pattern: `name = 1`, which is common in other languages
         let mut added_suggestion = false;
-        if let Some(Expr { kind: ExprKind::Assign(lhs, _rhs, _), .. }) = self.diagnostic_metadata.in_assignment &&
+        if let Some(Expr { kind: ExprKind::Assign(lhs, .. ), .. }) = self.diagnostic_metadata.in_assignment &&
             let ast::ExprKind::Path(None, _) = lhs.kind {
                 let sm = self.r.session.source_map();
                 let line_span = sm.span_extend_to_line(ident_span);
                 let ident_name = sm.span_to_snippet(ident_span).unwrap();
                 // HACK(chenyukang): make sure ident_name is at the starting of the line to protect against macros
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1821]: does something like `ident_span.from_expansion()` also work instead of checking the snippet?

Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1821]: Just find we have a API `span.can_be_used_for_suggestions`, maybe suitable for this.
And the snippet also used to avoid:

```rust
while x = blah {
 ....
}
```

Any better solution?

Comment (chenyukang) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Got it, this code is also a `desugaring`, nice!
Updated the code.

**Comment by oli-obk** [comment]
Thanks!

@bors r+ rollup

File: compiler/rustc_resolve/src/late.rs [hunk 7]
```diff
@@ -3963,10 +3964,15 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
-                let old = self.diagnostic_metadata.in_assignment.replace(expr);
-                visit::walk_expr(self, expr);
-                self.diagnostic_metadata.in_assignment = old;
+            ExprKind::Assign(ref lhs, ref rhs, _) => {
+                if !self.diagnostic_metadata.is_assign_rhs {
+                    self.diagnostic_metadata.in_assignment = Some(expr);
+                }
+                self.visit_expr(lhs);
+                self.diagnostic_metadata.is_assign_rhs = true;
+                self.diagnostic_metadata.in_assignment = None;
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:3973]: Should we reinstate the overwritten value, instead of putting `None` in all cases?

Comment (chenyukang) [reply compiler/rustc_resolve/src/late.rs:3973]: we only care about the `lhs` of assignment.

Comment (chenyukang) [reply compiler/rustc_resolve/src/late.rs:3973]: And the backup state is not important, the check logic is invoked by `visit_expr`.
