### PR TITLE
in which we decline to suggest the anonymous lifetime in declarations

### LINKED ISSUE #61124: Bad lint suggestion: `'_` in type definition
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=af7140af40052d9c78faf8897ce19525

```rust
#![deny(rust_2018_idioms)]

struct Bar<'a> { x: &'a u8 }

struct Foo(Bar);
```

```txt
error: hidden lifetime parameters in types are deprecated
 --> src/lib.rs:6:12
  |
6 | struct Foo(Bar);
  |            ^^^- help: indicate the anonymous lifetime: `<'_>`
  |
```

Except that using `'_` is not allowed in the type definition...

### PR DESCRIPTION
**Pull request by zackmdavis**
The elided-lifetimes-in-path lint (part of our suite of Rust 2018 idiom lints which we are hoping to promote to Warn status) was firing with an illegal suggestion to write an anonymous lifetime in a
struct/item declaration (where we don't allow it). The linting code was already deciding whether to act on the basis of a `ParamMode` enum, indicating whether the present path-segment was part of an
expression, or anywhere else. The present case seemed to be part of the "anywhere else", and yet meriting different rules as far as the lint was concerned, so it seemed expedient to introduce a new enum member. We yank out `TyKind::Path` arm into its own method so that we can call it with our new `ParamMode` specifically when lowering struct fields—one would have hoped to think of something more elegant than this, but it definitely beats changing the signature of `lower_ty` to take a `ParamMode`!

Resolves #61124.

cc @memoryruins 
r? @oli-obk

### CODE REVIEW

File: src/librustc/hir/lowering.rs [hunk 1]
```diff
@@ -274,6 +274,8 @@ pub fn lower_crate(
 enum ParamMode {
     /// Any path in a type context.
     Explicit,
+    /// Path in a type definition, where the anonymous lifetime '_ is not allowed.
```
Comment (Centril) [inline src/librustc/hir/lowering.rs]:
```suggestion
    /// Path in a type definition, where the anonymous lifetime `'_` is not allowed.
```

**Review by Centril — CHANGES_REQUESTED** [review]

File: src/librustc/hir/lowering.rs [hunk 2]
```diff
@@ -1534,12 +1553,7 @@ impl<'a> LoweringContext<'a> {
                 return self.lower_ty_direct(ty, itctx);
             }
             TyKind::Path(ref qself, ref path) => {
-                let id = self.lower_node_id(t.id);
-                let qpath = self.lower_qpath(t.id, qself, path, ParamMode::Explicit, itctx);
-                let ty = self.ty_path(id, t.span, qpath);
-                if let hir::TyKind::TraitObject(..) = ty.node {
-                    self.maybe_lint_bare_trait(t.span, t.id, qself.is_none() && path.is_global());
-                }
+                let ty = self.lower_path_ty(t, qself, path, ParamMode::Explicit, itctx);
```
Comment (oli-obk) [inline src/librustc/hir/lowering.rs]: nit: directly return here instead of using an intermediate variable

File: src/librustc/hir/lowering.rs [hunk 3]
```diff
@@ -3085,6 +3099,18 @@ impl<'a> LoweringContext<'a> {
...
+            let t = self.lower_path_ty(
+                &f.ty,
+                qself,
+                path,
+                ParamMode::ExplicitNamed, // no `'_` in declarations (Issue #61124)
+                ImplTraitContext::disallowed()
+            );
+            P(t)
+        } else {
+            self.lower_ty(&f.ty, ImplTraitContext::disallowed())
```
Comment (oli-obk) [inline src/librustc/hir/lowering.rs]: alternatively you could add a `ParamMode` argument to `lower_ty`, not sure if that is better though

**Comment by oli-obk** [comment]
r=me with nits addressed

File: src/librustc/hir/lowering.rs (hunk 3 above)
Comment (zackmdavis) [reply src/librustc/hir/lowering.rs]: That was my first idea, but I decided against it, because it seemed inelegant to change the signature when _most_ of the `TyKind` match arm bodies don't concern themselves with `ParamMode`.
