### PR TITLE
rustc_builtin_macros: rename bench parameter to avoid collisions with user-defined function names

### LINKED ISSUE #148275: Can't `#[bench]` a function named `b`
```rust
#![feature(test)]

extern crate test;

#[bench]
fn b(_: &mut test::bench::Bencher) {}
```

I should be able to run this as a benchmark, but I got the following error:

```
error[E0308]: mismatched types
 --> src/lib.rs:6:1
  |
5 | #[bench]
  | -------- in this attribute macro expansion
6 | fn b(_: &mut test::bench::Bencher) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | |
  | expected `&mut Bencher`, found `TestDescAndFn`
  | expected due to this
  | constant defined here
  | `b` is interpreted as a constant, not a new binding
  | help: introduce a new binding instead: `other_b`

error[E0308]: mismatched types
 --> src/lib.rs:6:1
  |
5 | #[bench]
  | -------- in this attribute macro expansion
6 | fn b(_: &mut test::bench::Bencher) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | |
  | expected `&mut Bencher`, found `TestDescAndFn`
  | arguments to this function are incorrect
  |
note: function defined here
 --> src/lib.rs:6:4
  |
6 | fn b(_: &mut test::bench::Bencher) {}
  |    ^ ----------------------------

For more information about this error, try `rustc --explain E0308`.
```

It seems that the macro expansion of `#[bench]` has a name collision with a variable named `b`. https://github.com/rust-lang/rust/blob/292be5c7c05138d753bbd4b30db7a3f1a5c914f7/compiler/rustc_builtin_macros/src/test.rs#L210-L218

### Meta

Reproducible on the playground with version `1.93.0-nightly (2025-10-28 278a90913daf77077910)` (click on the three dots on top left -> "test")

### PR DESCRIPTION
**Pull request by IntegralPilot**
Resolves rust-lang/rust#148275 by preventing name collisions in the `#[bench]` macro.

Previously, a user-defined function named "b" could not be benchmarked because
the macro-generated lambda identity collided with the same name. We now generate
the lambda ident as `__bench_<function_name>`, ensuring it is always distinct
from the user’s function.

Because the prefix is applied recursively (e.g. benchmarking `__bench_b`
produces a lambda ident `__bench___bench_b`), there is no possible function
name that can equal its corresponding lambda ident. This guarantees that
the user can safely bench a function of any valid name without risk of
identifier collision.

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/test.rs [hunk 1]
```diff
@@ -207,9 +207,9 @@ pub(crate) fn expand_test_or_bench(
     };
 
     let test_fn = if is_bench {
-        // A simple ident for a lambda
-        let b = Ident::from_str_and_span("b", attr_sp);
-
+        // A simple ident for a lambda, using the user's function name within it to avoid collisions.
+        let param_name = format!("__bench_{}", fn_.ident.name);
+        let bencher_param = Ident::new(Symbol::intern(&param_name), attr_sp);
```
Comment (oli-obk) [inline compiler/rustc_builtin_macros/src/test.rs]: why did you change it from `from_str_and_span` to `new` + `intern`?

Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: It’s mostly a style preference, @oli-obk. Since `format!` gives us a `String` (unlike the old `str`), we still need either a conversion or an interning step - `from_str_and_span` would need a `.as_str()` call, while `new` needs a `Symbol::intern` call.  So `from_str_and_span` doesn’t really simplify anything, and I think the explicit intern call makes it flow a bit clearer and cleaner than a conversion, and also separates the logical steps of building the string and then interning it. That said, if you’d rather keep `from_str_and_span` and just add `.as_str()` for consistency, I’m good with that too, I really don't mind. Thank you for your time in reviewing! 🙂

Comment (hkBst) [reply compiler/rustc_builtin_macros/src/test.rs]: Could you use `&format...`?

Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: That could work to as well I think, I considered that but preferred the explicit intern style. I'm fine with whatever everyone else wants to go for. :)

Comment (hkBst) [reply compiler/rustc_builtin_macros/src/test.rs]: Since the helper function exists it's probably a good idea to keep using it...

**Review by hkBst — CHANGES_REQUESTED** [review]
LGTM except for a small style nit as mentioned above.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148279/292be5c7c05138d753bbd4b30db7a3f1a5c914f7..ebe155a549c24dd04a532e1edcc1736d46488549)*

File: compiler/rustc_builtin_macros/src/test.rs [hunk 2]
```diff
@@ -209,7 +209,7 @@ pub(crate) fn expand_test_or_bench(
     let test_fn = if is_bench {
         // A simple ident for a lambda, using the user's function name within it to avoid collisions.
         let param_name = format!("__bench_{}", fn_.ident.name);
-        let bencher_param = Ident::new(Symbol::intern(&param_name), attr_sp);
+        let bencher_param = Ident::from_str_and_span(&param_name, attr_sp);
```
Comment (hkBst) [inline compiler/rustc_builtin_macros/src/test.rs]: I'd probably also inline param_name...

**Review by hkBst — CHANGES_REQUESTED** [review]

File: compiler/rustc_builtin_macros/src/test.rs [hunk 3]
```diff
@@ -207,9 +207,9 @@ pub(crate) fn expand_test_or_bench(
     };
 
     let test_fn = if is_bench {
-        // A simple ident for a lambda
-        let b = Ident::from_str_and_span("b", attr_sp);
-
+        // A simple ident for a lambda, using the user's function name within it to avoid collisions.
```
Comment (hkBst) [inline compiler/rustc_builtin_macros/src/test.rs]: Arguably this ident is now no longer simple, but rather... collision-resistant?

**Review by hkBst — CHANGES_REQUESTED** [review]

File: compiler/rustc_builtin_macros/src/test.rs (hunk 1 above)
Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: done! :)

File: compiler/rustc_builtin_macros/src/test.rs (hunk 2 above)
Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: done! :)

File: compiler/rustc_builtin_macros/src/test.rs (hunk 3 above)
Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: done! :)

File: compiler/rustc_builtin_macros/src/test.rs [hunk 4]
```diff
@@ -207,30 +207,30 @@ pub(crate) fn expand_test_or_bench(
     };
 
     let test_fn = if is_bench {
-        // A simple ident for a lambda
-        let b = Ident::from_str_and_span("b", attr_sp);
-
+        // A collision-resistant ident for a lambda, using the user's function name within it to avoid collisions.
```
Comment (hkBst) [inline compiler/rustc_builtin_macros/src/test.rs]: this is now repeating "collision", and should probably also link to the bug this solves.
```suggestion
        // try to avoid name collisions, see bug #148275
```

**Review by hkBst — CHANGES_REQUESTED** [review]

File: compiler/rustc_builtin_macros/src/test.rs (hunk 4 above)
Comment (IntegralPilot) [reply compiler/rustc_builtin_macros/src/test.rs]: Resolved! In the change I just pushed, I did this but also used absolute language rather then "try" as this avoids all possible collisions and makes any collisions impossible and added a summary of how we avoid collisions (using the function name in the ident) to the comment. :)

**Review by hkBst — APPROVED** [review]

**Comment by IntegralPilot** [comment]
@hkBst, just squashed the commits! Thanks again for your review & help :)
