### PR TITLE
Remove the `ty` field from type system `Const`s

### LINKED ISSUE #122908: ICE: `Unexpected node Synthetic`
auto-reduced (treereduce-rust):
````rust
trait Trait<const module_path: Trait = bar> {
    async fn handle<F>(slf: &F) {}
}


````

original:
````rust
trait Trait<const module_path: Trait = bar> {
    async fn handle<F>(slf: &F)
where
    F: Fn(&()) -> &mut (dyn Future<Output = ()> + Unpin),
{
    (slf)(&()).await;
}
}

fn main() {}

````

Version information
````
rustc 1.79.0-nightly (b3df0d7e5 2024-03-22)
binary: rustc
commit-hash: b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87
commit-date: 2024-03-22
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zunstable-options --edition=2024`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `bar` in this scope
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:40
  |
1 | trait Trait<const module_path: Trait = bar> {
  |                                        ^^^ not found in this scope

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs`

error[E0391]: cycle detected when computing type of `Trait::module_path`
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:32
  |
1 | trait Trait<const module_path: Trait = bar> {
  |                                ^^^^^
  |
  = note: ...which immediately requires computing type of `Trait::module_path` again
note: cycle used when computing explicit predicates of trait `Trait`
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:1
  |
1 | trait Trait<const module_path: Trait = bar> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when computing type of `Trait::module_path`
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:13
  |
1 | trait Trait<const module_path: Trait = bar> {
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which immediately requires computing type of `Trait::module_path` again
note: cycle used when computing explicit predicates of trait `Trait`
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:1
  |
1 | trait Trait<const module_path: Trait = bar> {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0038]: the trait `Trait` cannot be made into an object
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:32
  |
1 | trait Trait<const module_path: Trait = bar> {
  |                                ^^^^^ `Trait` cannot be made into an object
  |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:2:14
  |
1 | trait Trait<const module_path: Trait = bar> {
  |       ----- this trait cannot be made into an object...
2 |     async fn handle<F>(slf: &F) {}
  |              ^^^^^^ ...because associated function `handle` has no `self` parameter
help: consider turning `handle` into a method by giving it a `&self` argument
  |
2 |     async fn handle<F>(&self, slf: &F) {}
  |                        ++++++
help: alternatively, consider constraining `handle` so it does not apply to trait objects
  |
2 |     async fn handle<F>(slf: &F) where Self: Sized {}
  |                                 +++++++++++++++++

error[E0038]: the trait `Trait` cannot be made into an object
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:13
  |
1 | trait Trait<const module_path: Trait = bar> {
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Trait` cannot be made into an object
  |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:2:14
  |
1 | trait Trait<const module_path: Trait = bar> {
  |       ----- this trait cannot be made into an object...
2 |     async fn handle<F>(slf: &F) {}
  |              ^^^^^^ ...because associated function `handle` has no `self` parameter
help: consider turning `handle` into a method by giving it a `&self` argument
  |
2 |     async fn handle<F>(&self, slf: &F) {}
  |                        ++++++
help: alternatively, consider constraining `handle` so it does not apply to trait objects
  |
2 |     async fn handle<F>(slf: &F) where Self: Sized {}
  |                                 +++++++++++++++++

error: `(dyn Trait<{const error}> + 'static)` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:32
  |
1 | trait Trait<const module_path: Trait = bar> {
  |                                ^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`

error: internal compiler error: compiler/rustc_hir_analysis/src/hir_wf_check.rs:176:25: Unexpected node Synthetic

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_wf_check.rs:176:25:
Box<dyn Any>
stack backtrace:
   0:     0x7364225c2fa5 - std::backtrace_rs::backtrace::libunwind::trace::h4515e3e00f57996f
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7364225c2fa5 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e64ac1112175e4e
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7364225c2fa5 - std::sys_common::backtrace::_print_fmt::h182160b5ad873150
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7364225c2fa5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h432843f19f8b2b6d
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x736422613feb - core::fmt::rt::Argument::fmt::hb59bbd21accf1885
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/core/src/fmt/rt.rs:142:9
   5:     0x736422613feb - core::fmt::write::haf243cf4605e411d
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/core/src/fmt/mod.rs:1153:17
   6:     0x7364225b7d3f - std::io::Write::write_fmt::hd8c8c68b4f5b8f11
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/io/mod.rs:1843:15
   7:     0x7364225c2d7e - std::sys_common::backtrace::_print::h0ec933d6103e5515
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7364225c2d7e - std::sys_common::backtrace::print::h55136fa64edb86e6
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7364225c59f9 - std::panicking::default_hook::{{closure}}::h28cbeefc01b40f52
  10:     0x7364225c5763 - std::panicking::default_hook::h15e904210c67a3ca
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/panicking.rs:292:9
  11:     0x73641edcb6bf - std[48784e9e46568672]::panicking::update_hook::<alloc[590c7545ac68a568]::boxed::Box<rustc_driver_impl[9e9e6466696ec967]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7364225c6150 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::had664932fcaf7f86
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2029:9
  13:     0x7364225c6150 - std::panicking::rust_panic_with_hook::h9f23cc8a1f418825
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/panicking.rs:783:13
  14:     0x73641edfbaa4 - std[48784e9e46568672]::panicking::begin_panic::<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>::{closure#0}
  15:     0x73641edf86f6 - std[48784e9e46568672]::sys_common::backtrace::__rust_end_short_backtrace::<std[48784e9e46568672]::panicking::begin_panic<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>::{closure#0}, !>
  16:     0x73641edf3c06 - std[48784e9e46568672]::panicking::begin_panic::<rustc_errors[85c3c7ac8d959a53]::ExplicitBug>
  17:     0x73641ee04f31 - <rustc_errors[85c3c7ac8d959a53]::diagnostic::BugAbort as rustc_errors[85c3c7ac8d959a53]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x73641f29754c - rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt::<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}
  19:     0x73641f27abca - rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_opt::<rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x73641f27aa4b - rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_context_opt::<rustc_middle[cfd7f582085b2efd]::ty::context::tls::with_opt<rustc_middle[cfd7f582085b2efd]::util::bug::opt_span_bug_fmt<rustc_span[9e6cb2d6f72e9bb4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x73641ce50b50 - rustc_middle[cfd7f582085b2efd]::util::bug::bug_fmt
  22:     0x73641ef048aa - rustc_hir_analysis[595b5ec1edcfd0c3]::hir_wf_check::diagnostic_hir_wf_check
  23:     0x73641f60bd64 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::diagnostic_hir_wf_check::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 8usize]>>
  24:     0x73641f5f02cb - <rustc_query_impl[82a63e1d7cdec9a7]::query_impl::diagnostic_hir_wf_check::dynamic_query::{closure#2} as core[b4a1350c838fc0f9]::ops::function::FnOnce<(rustc_middle[cfd7f582085b2efd]::ty::context::TyCtxt, (rustc_middle[cfd7f582085b2efd]::ty::predicate::Predicate, rustc_middle[cfd7f582085b2efd]::traits::WellFormedLoc))>>::call_once
  25:     0x73641f571f4b - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::DefaultCache<(rustc_middle[cfd7f582085b2efd]::ty::predicate::Predicate, rustc_middle[cfd7f582085b2efd]::traits::WellFormedLoc), rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  26:     0x73641f636410 - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::diagnostic_hir_wf_check::get_query_non_incr::__rust_end_short_backtrace
  27:     0x73641f8fe7ae - <rustc_infer[be9aceac34789818]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[dc9d16cead07ba55]::traits::error_reporting::type_err_ctxt_ext::TypeErrCtxtExt>::report_selection_error
  28:     0x73641f912571 - <rustc_infer[be9aceac34789818]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[dc9d16cead07ba55]::traits::error_reporting::type_err_ctxt_ext::InferCtxtPrivExt>::report_fulfillment_error
  29:     0x73641f8fbd6d - <rustc_infer[be9aceac34789818]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[dc9d16cead07ba55]::traits::error_reporting::type_err_ctxt_ext::TypeErrCtxtExt>::report_fulfillment_errors
  30:     0x736420849cab - rustc_hir_analysis[595b5ec1edcfd0c3]::check::wfcheck::check_associated_item
  31:     0x73642085b1d4 - rustc_hir_analysis[595b5ec1edcfd0c3]::check::wfcheck::check_well_formed
  32:     0x736420857b07 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>
  33:     0x736420857280 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::VecCache<rustc_hir[a67f1a97fc26ff83]::hir_id::OwnerId, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  34:     0x736420856fff - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  35:     0x736420856f50 - <rustc_middle[cfd7f582085b2efd]::hir::ModuleItems>::par_trait_items::<rustc_hir_analysis[595b5ec1edcfd0c3]::check::wfcheck::check_mod_type_wf::{closure#2}>::{closure#0}
  36:     0x73642085521e - rustc_hir_analysis[595b5ec1edcfd0c3]::check::wfcheck::check_mod_type_wf
  37:     0x736420854d61 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>
  38:     0x736420cc2930 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::DefaultCache<rustc_span[9e6cb2d6f72e9bb4]::def_id::LocalModDefId, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  39:     0x736420cc26db - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7364203f907b - rustc_hir_analysis[595b5ec1edcfd0c3]::check_crate
  41:     0x7364206a02ea - rustc_interface[7ddcde71cf02e108]::passes::analysis
  42:     0x73642069fe51 - rustc_query_impl[82a63e1d7cdec9a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[82a63e1d7cdec9a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>
  43:     0x736420feb4a5 - rustc_query_system[ee3912bf2a9f33a7]::query::plumbing::try_execute_query::<rustc_query_impl[82a63e1d7cdec9a7]::DynamicConfig<rustc_query_system[ee3912bf2a9f33a7]::query::caches::SingleCache<rustc_middle[cfd7f582085b2efd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[82a63e1d7cdec9a7]::plumbing::QueryCtxt, false>
  44:     0x736420feb209 - rustc_query_impl[82a63e1d7cdec9a7]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  45:     0x736420e870d9 - rustc_interface[7ddcde71cf02e108]::interface::run_compiler::<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}
  46:     0x736420f52399 - std[48784e9e46568672]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_with_globals<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_pool_with_globals<rustc_interface[7ddcde71cf02e108]::interface::run_compiler<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>
  47:     0x736420f521c6 - <<std[48784e9e46568672]::thread::Builder>::spawn_unchecked_<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_with_globals<rustc_interface[7ddcde71cf02e108]::util::run_in_thread_pool_with_globals<rustc_interface[7ddcde71cf02e108]::interface::run_compiler<core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>, rustc_driver_impl[9e9e6466696ec967]::run_compiler::{closure#0}>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b4a1350c838fc0f9]::result::Result<(), rustc_span[9e6cb2d6f72e9bb4]::ErrorGuaranteed>>::{closure#1} as core[b4a1350c838fc0f9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7364225cf919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3e016c41180ed802
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2015:9
  49:     0x7364225cf919 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf0716ba35a33b0c
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/alloc/src/boxed.rs:2015:9
  50:     0x7364225cf919 - std::sys::pal::unix::thread::Thread::new::thread_start::hd585680968d21553
                               at /rustc/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/std/src/sys/pal/unix/thread.rs:108:17
  51:     0x73642236f55a - <unknown>
  52:     0x7364223eca3c - <unknown>
  53:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0-nightly (b3df0d7e5 2024-03-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -Z dump-mir-dir=dir

query stack during panic:
#0 [diagnostic_hir_wf_check] performing HIR wf-checking for predicate `Binder { value: ObjectSafe(DefId(0:3 ~ mvce[230a]::Trait)), bound_vars: [] }` at item `Ty(DefId(0:12 ~ mvce[230a]::Trait::{synthetic#0}))`
#1 [check_well_formed] checking that `Trait::handle` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error[E0782]: trait objects must include the `dyn` keyword
 --> /tmp/icemaker_global_tempdir.pLv5S1PJhcgC/rustc_testrunner_tmpdir_reporting.vqm2wcW7QHJ8/mvce.rs:1:32
  |
1 | trait Trait<const module_path: Trait = bar> {
  |                                ^^^^^
  |
help: add `dyn` keyword before this trait
  |
1 | trait Trait<const module_path: dyn Trait = bar> {
  |                                +++

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0038, E0391, E0425, E0601, E0782.
For more information about an error, try `rustc --explain E0038`.

```

</p>
</details>

### LINKED ISSUE #125556: ICE: coherence: `assertion failed: obligations.is_empty()` / `unexpected infer in QueryInput `
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

mod v20 {

    pub type v11 = [[usize; v4]; v4];

    const v0: [[usize; v4]; v4] = v6(v8);
    pub struct v17<const v10: usize, const v7: v11> {
        _p: (),
    }

    impl v17<512, v0> {
        pub const fn v21() -> v18 {}
    }

    impl v17<v10, v2> {
        pub const fn v21() -> v18 {}
    }
}


````

original:
````rust
#![feature(generic_const_exprs)]

mod v20 {
    const v0: usize = 512;
    pub type v11 = [[usize; v4]; v4];
    const v2: v11 = [[256; v4]; v4];

    const v0: [[usize; v4]; v4] = v6(v8);
    pub struct v17<const v10: usize, const v7: v11> {
        _p: (),
    }

    impl v17<512, v0> {
        pub const fn v21() -> v18 {}
    }

    impl<const v10: usize> v17<v10, v2> {
        pub const fn v21() -> v18 {
            v18 { _p: () }
        }
    }
}
pub use v20::{v13, v17};
fn main() {}

````

Version information
````
rustc 1.80.0-nightly (48f00110d 2024-05-25)
binary: rustc
commit-hash: 48f00110d0dae38b3046a9ac05d20ea321fd6637
commit-date: 2024-05-25
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Znext-solver=coherence`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `v4` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:5:29
  |
5 |     pub type v11 = [[usize; v4]; v4];
  |                             ^^ help: a constant with a similar name exists: `v0`
6 |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |     ------------------------------------- similarly named constant `v0` defined here

error[E0425]: cannot find value `v4` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:5:34
  |
5 |     pub type v11 = [[usize; v4]; v4];
  |                                  ^^ help: a constant with a similar name exists: `v0`
6 |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |     ------------------------------------- similarly named constant `v0` defined here

error[E0425]: cannot find value `v4` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:7:24
  |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |                        ^^ not found in this scope

error[E0425]: cannot find value `v4` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:7:29
  |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |                             ^^ not found in this scope

error[E0425]: cannot find value `v8` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:7:38
  |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |                                      ^^ not found in this scope

error[E0412]: cannot find type `v18` in this scope
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:13:31
   |
5  |     pub type v11 = [[usize; v4]; v4];
   |     --------------------------------- similarly named type alias `v11` defined here
...
13 |         pub const fn v21() -> v18 {}
   |                               ^^^ help: a type alias with a similar name exists: `v11`

error[E0412]: cannot find type `v10` in this scope
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:16:14
   |
5  |     pub type v11 = [[usize; v4]; v4];
   |     --------------------------------- similarly named type alias `v11` defined here
...
16 |     impl v17<v10, v2> {
   |              ^^^
   |
help: a type alias with a similar name exists
   |
16 |     impl v17<v11, v2> {
   |              ~~~
help: you might be missing a type parameter
   |
16 |     impl<v10> v17<v10, v2> {
   |         +++++

error[E0412]: cannot find type `v2` in this scope
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:16:19
   |
16 |     impl v17<v10, v2> {
   |                   ^^ not found in this scope
   |
help: you might be missing a type parameter
   |
16 |     impl<v2> v17<v10, v2> {
   |         ++++

error[E0412]: cannot find type `v18` in this scope
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:17:31
   |
5  |     pub type v11 = [[usize; v4]; v4];
   |     --------------------------------- similarly named type alias `v11` defined here
...
17 |         pub const fn v21() -> v18 {}
   |                               ^^^ help: a type alias with a similar name exists: `v11`

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: type `v11` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:5:14
  |
5 |     pub type v11 = [[usize; v4]; v4];
  |              ^^^ help: convert the identifier to upper camel case (notice the capitalization): `V11`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: type `v17` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:8:16
  |
8 |     pub struct v17<const v10: usize, const v7: v11> {
  |                ^^^ help: convert the identifier to upper camel case (notice the capitalization): `V17`

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:19:2
   |
19 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs`

error[E0425]: cannot find function `v6` in this scope
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:7:35
  |
7 |     const v0: [[usize; v4]; v4] = v6(v8);
  |                                   ^^ not found in this scope

error: `[[usize; v4]; v4]` is forbidden as the type of a const generic parameter
 --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:8:48
  |
8 |     pub struct v17<const v10: usize, const v7: v11> {
  |                                                ^^^
  |
  = note: the only supported types are integers, `bool` and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
  |
3 + #![feature(adt_const_params)]
  |

error[E0747]: unresolved item provided when a constant was expected
  --> /tmp/icemaker_global_tempdir.iEGYn0XYvA4f/rustc_testrunner_tmpdir_reporting.rHVhnk0l6xFH/mvce.rs:16:14
   |
16 |     impl v17<v10, v2> {
   |              ^^^
   |
help: if this generic argument was intended as a const parameter, surround it with braces
   |
16 |     impl v17<{ v10 }, v2> {
   |              +     +

thread 'rustc' panicked at compiler/rustc_trait_selection/src/solve/eval_ctxt/canonical.rs:354:13:
assertion failed: obligations.is_empty()
stack backtrace:
   0:     0x786ef26b3075 - std::backtrace_rs::backtrace::libunwind::trace::h42aea1e7bd0a8d0f
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x786ef26b3075 - std::backtrace_rs::backtrace::trace_unsynchronized::hf3ac14f94797a8ff
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x786ef26b3075 - std::sys_common::backtrace::_print_fmt::hfdeb6f5ed3f5afaa
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x786ef26b3075 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3a3bab3a7e07f684
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x786ef270218b - core::fmt::rt::Argument::fmt::h827eaf91b0235e22
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/core/src/fmt/rt.rs:165:63
   5:     0x786ef270218b - core::fmt::write::h3c9de6e4b056660b
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/core/src/fmt/mod.rs:1172:21
   6:     0x786ef26a7dcf - std::io::Write::write_fmt::h4989c38cc46ac4a9
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/io/mod.rs:1835:15
   7:     0x786ef26b2e4e - std::sys_common::backtrace::_print::hf88b29e9f4397d20
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x786ef26b2e4e - std::sys_common::backtrace::print::ha9d7657d2fccb9ae
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x786ef26b5879 - std::panicking::default_hook::{{closure}}::hc05689f1cbee5d27
  10:     0x786ef26b561a - std::panicking::default_hook::hd873922dd239ed0b
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/panicking.rs:298:9
  11:     0x786eef0f9eef - std[f497e4f3b89fc98e]::panicking::update_hook::<alloc[98811ad6430038c6]::boxed::Box<rustc_driver_impl[54b05657baa3450f]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x786ef26b5fab - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf701087af7d36f49
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/alloc/src/boxed.rs:2077:9
  13:     0x786ef26b5fab - std::panicking::rust_panic_with_hook::haff0763df51daf39
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/panicking.rs:799:13
  14:     0x786ef26b5ceb - std::panicking::begin_panic_handler::{{closure}}::hc16ab47bd0d35526
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/panicking.rs:656:13
  15:     0x786ef26b3539 - std::sys_common::backtrace::__rust_end_short_backtrace::h65417fe81de7a832
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x786ef26b5a57 - rust_begin_unwind
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/panicking.rs:652:5
  17:     0x786ef26fe753 - core::panicking::panic_fmt::h94f1edd420c4d371
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/core/src/panicking.rs:72:14
  18:     0x786ef26fe7fc - core::panicking::panic::h3e16a54ff7079537
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/core/src/panicking.rs:146:5
  19:     0x786ef08bcc27 - <rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::unify_query_var_values
  20:     0x786ef10acf5e - <rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::evaluate_goal_raw
  21:     0x786ef10b17c0 - <rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::try_evaluate_added_goals
  22:     0x786ef10b9f43 - <rustc_trait_selection[63ce0d138858f6da]::solve::search_graph::SearchGraph<rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::with_new_goal::<<rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>::{closure#2}
  23:     0x786ef10b2f46 - <rustc_trait_selection[63ce0d138858f6da]::solve::search_graph::SearchGraph<rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::with_new_goal::<<rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::evaluate_canonical_goal::{closure#0}::{closure#0}::{closure#0}>
  24:     0x786ef10ac904 - <rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::EvalCtxt<rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt, rustc_middle[8d1200f20c5736b5]::ty::context::TyCtxt>>::evaluate_goal_raw
  25:     0x786ef10abc11 - <rustc_infer[4c65ead5c75e00e7]::infer::InferCtxt as rustc_trait_selection[63ce0d138858f6da]::solve::eval_ctxt::InferCtxtEvalExt>::evaluate_root_goal
  26:     0x786ef10ab560 - <rustc_trait_selection[63ce0d138858f6da]::solve::fulfill::FulfillmentCtxt as rustc_infer[4c65ead5c75e00e7]::traits::engine::TraitEngine>::select_where_possible
  27:     0x786ef06d5a7a - <rustc_trait_selection[63ce0d138858f6da]::traits::engine::ObligationCtxt>::select_all_or_error
  28:     0x786ef08be83d - rustc_trait_selection[63ce0d138858f6da]::traits::coherence::overlap
  29:     0x786ef13cd078 - rustc_trait_selection[63ce0d138858f6da]::traits::coherence::overlapping_impls
  30:     0x786ef13cc479 - <rustc_hir_analysis[773f5f9066629b08]::coherence::inherent_impls_overlap::InherentOverlapChecker>::check_for_overlapping_inherent_impls
  31:     0x786ef0a66c1b - rustc_hir_analysis[773f5f9066629b08]::coherence::inherent_impls_overlap::crate_inherent_impls_overlap_check
  32:     0x786ef0a664e7 - rustc_query_impl[f809864b4f0d0f3d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f809864b4f0d0f3d]::query_impl::crate_inherent_impls_overlap_check::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8d1200f20c5736b5]::query::erase::Erased<[u8; 1usize]>>
  33:     0x786ef11553a5 - rustc_query_system[7155d4f1ed1184a2]::query::plumbing::try_execute_query::<rustc_query_impl[f809864b4f0d0f3d]::DynamicConfig<rustc_query_system[7155d4f1ed1184a2]::query::caches::SingleCache<rustc_middle[8d1200f20c5736b5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f809864b4f0d0f3d]::plumbing::QueryCtxt, false>
  34:     0x786ef115518f - rustc_query_impl[f809864b4f0d0f3d]::query_impl::crate_inherent_impls_overlap_check::get_query_non_incr::__rust_end_short_backtrace
  35:     0x786ef07acbb7 - rustc_hir_analysis[773f5f9066629b08]::check_crate
  36:     0x786ef078d07e - rustc_interface[58067e46342fbaaa]::passes::analysis
  37:     0x786ef078cbd5 - rustc_query_impl[f809864b4f0d0f3d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f809864b4f0d0f3d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8d1200f20c5736b5]::query::erase::Erased<[u8; 1usize]>>
  38:     0x786ef11553a5 - rustc_query_system[7155d4f1ed1184a2]::query::plumbing::try_execute_query::<rustc_query_impl[f809864b4f0d0f3d]::DynamicConfig<rustc_query_system[7155d4f1ed1184a2]::query::caches::SingleCache<rustc_middle[8d1200f20c5736b5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f809864b4f0d0f3d]::plumbing::QueryCtxt, false>
  39:     0x786ef115510f - rustc_query_impl[f809864b4f0d0f3d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  40:     0x786ef0fcac5c - rustc_interface[58067e46342fbaaa]::interface::run_compiler::<core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>, rustc_driver_impl[54b05657baa3450f]::run_compiler::{closure#0}>::{closure#1}
  41:     0x786ef0fb6d09 - std[f497e4f3b89fc98e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[58067e46342fbaaa]::util::run_in_thread_with_globals<rustc_interface[58067e46342fbaaa]::util::run_in_thread_pool_with_globals<rustc_interface[58067e46342fbaaa]::interface::run_compiler<core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>, rustc_driver_impl[54b05657baa3450f]::run_compiler::{closure#0}>::{closure#1}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>::{closure#0}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>
  42:     0x786ef0fb6ac8 - <<std[f497e4f3b89fc98e]::thread::Builder>::spawn_unchecked_<rustc_interface[58067e46342fbaaa]::util::run_in_thread_with_globals<rustc_interface[58067e46342fbaaa]::util::run_in_thread_pool_with_globals<rustc_interface[58067e46342fbaaa]::interface::run_compiler<core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>, rustc_driver_impl[54b05657baa3450f]::run_compiler::{closure#0}>::{closure#1}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>::{closure#0}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e093d3f8342b0aab]::result::Result<(), rustc_span[f743e6227e8610a7]::ErrorGuaranteed>>::{closure#2} as core[e093d3f8342b0aab]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x786ef26bfd8b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h07c51d08fbe7b366
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/alloc/src/boxed.rs:2063:9
  44:     0x786ef26bfd8b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59743c0df790be85
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/alloc/src/boxed.rs:2063:9
  45:     0x786ef26bfd8b - std::sys::pal::unix::thread::Thread::new::thread_start::h35133497d39238f8
                               at /rustc/48f00110d0dae38b3046a9ac05d20ea321fd6637/library/std/src/sys/pal/unix/thread.rs:108:17
  46:     0x786eebeaa1cf - <unknown>
  47:     0x786eebf2b6ec - <unknown>
  48:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (48f00110d 2024-05-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z next-solver=coherence -Z dump-mir-dir=dir

query stack during panic:
#0 [crate_inherent_impls_overlap_check] check for overlap between inherent impls defined in this crate
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 13 previous errors; 3 warnings emitted

Some errors have detailed explanations: E0412, E0425, E0601, E0747.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #125556
Fixes #122908

Part of the work on `adt_const_params`/`generic_const_param_types`/`min_generic_const_exprs`/generally making the compiler nicer. cc rust-lang/project-const-generics#44

Please review commit-by-commit otherwise I wasted a lot of time not just squashing this into a giant mess (and also it'll be SO much nicer because theres a lot of fluff changes mixed in with other more careful changes if looking via File Changes

---

Why do this? 
- The `ty` field keeps causing ICEs and weird behaviour due to it either being treated as "part of the const" or it being forgotten about leading to ICEs. 
- As we move forward with `adt_const_params` and a potential `min_generic_const_exprs` it's going to become more complex to actually lower the correct `Ty<'tcx>`
- It muddles the idea behind how we check `Const` arguments have the correct type. By having the `ty` field it may seem like we ought to be relating it when we relate two types, or that its generally important information about the `Const`.
- Brings the compiler more in line with `a-mir-formality` as that also tracks the type of type system `Const`s via `ConstArgHasType` bounds in the env instead of on the `Const` itself.
- A lot of stuff is a lot nicer when you dont have to pass around the type of a const lol. Everywhere we construct `Const` is now significantly nicer :sweat_smile: 

See #125671's description for some more information about the `ty` field

---

General summary of changes in this PR:

- Add `Ty` to `ConstKind::Value` as otherwise there is no way to implement `ConstArgHasType` to ensure that const arguments are correctly typed for the parameter when we stop creating anon consts for all const args. It's also just incredibly difficult/annoying to thread the correct `Ty` around to a bunch of ctfe functions otherwise.
-  Fully implement `ConstArgHasType` in both the old and new solver. Since it now has no reliance on the `ty` field it serves its originally intended purpose of being able to act as a double check that trait vs impls have correctly typed const parameters. It also will now be able to be responsible for checking types of const arguments to parameters under `min_generic_const_exprs`.
- Add `Ty` to `mir::Const::Ty`. I dont have a great understanding of why mir constants are setup like this to be honest. Regardless they need to be able to determine the type of the const and the easiest way to make this happen was to simply store the `Ty` along side the `ty::Const`. Maybe we can do better here in the future but I'd have to spend way more time looking at everywhere we use `mir::Const`.
- rustdoc has its own `Const` which also has a `ty` field. It was relatively easy to remove this. 

---

r? @lcnr @compiler-errors

### CODE REVIEW

File: src/rustdoc-json-types/lib.rs [hunk 1]
```diff
@@ -8,7 +8,7 @@ use serde::{Deserialize, Serialize};
 use std::path::PathBuf;
 
 /// rustdoc format-version.
-pub const FORMAT_VERSION: u32 = 29;
```
Comment (BoxyUwU) [inline src/rustdoc-json-types/lib.rs:11]: :)

File: src/rustdoc-json-types/lib.rs [hunk 2]
```diff
@@ -8,7 +8,7 @@ use serde::{Deserialize, Serialize};
...
+pub const FORMAT_VERSION: u32 = 30;
```
Comment (BoxyUwU) [inline src/rustdoc-json-types/lib.rs:11]: :)

**Comment by RalfJung** [comment]
> SMIR represents mir consts and ty consts using the same Const type. This... does not work at all anymore so I have split them into two different types in SMIR and it seems to make everything a lot nicer regardless of this PR.

Cc https://github.com/rust-lang/project-stable-mir/issues/71

File: compiler/rustc_trait_selection/src/solve/mod.rs [hunk 3]
```diff
@@ -208,22 +208,58 @@ impl<'a, 'tcx> EvalCtxt<'a, InferCtxt<'tcx>> {
...
+            ),
+            ty::ConstKind::Param(_) => {
+                unreachable!("`ConstKind::Param` should have been canonicalized to `Placeholder`")
+            }
+            ty::ConstKind::Bound(_, _) => bug!("escaping bound vars in {:?}", ct),
+            ty::ConstKind::Value(ty, _) => ty,
+            ty::ConstKind::Placeholder(placeholder) => {
+                let mut candidates = goal.param_env.caller_bounds().iter().filter_map(|clause| {
+                    // `ConstArgHasType` are never desugared to be higher ranked.
+                    match clause.kind().skip_binder() {
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/solve/mod.rs:238]: use `no_bound_vars().unwrap()` in that case

File: compiler/rustc_trait_selection/src/traits/fulfill.rs [hunk 4]
```diff
@@ -438,29 +438,53 @@ impl<'a, 'tcx> ObligationProcessor for FulfillProcessor<'a, 'tcx> {
...
-                                    SelectionError::Unimplemented,
-                                )),
-                            }
+                        ty::ConstKind::Value(ty, _) => ty,
+                        ty::ConstKind::Unevaluated(uv) => self
+                            .selcx
+                            .infcx
+                            .tcx
+                            .type_of(uv.def)
+                            .instantiate(self.selcx.infcx.tcx, uv.args),
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/fulfill.rs:461]: maybe the `Unevaluated` struct should have a `type_of` method, this invocation seems to be recurring

File: compiler/rustc_trait_selection/src/traits/fulfill.rs [hunk 5]
```diff
@@ -438,29 +438,53 @@ impl<'a, 'tcx> ObligationProcessor for FulfillProcessor<'a, 'tcx> {
...
+                        // FIXME(generic_const_exprs): we should construct an alias like
+                        // `<lhs_ty as Add<rhs_ty>>::Output` when this is an `Expr` representing
+                        // `lhs + rhs`.
+                        ty::ConstKind::Expr(_) => {
+                            return ProcessResult::Changed(mk_pending(vec![]));
+                        }
+                        // FIXME(BoxyUwU): this doesnt seem right
+                        ty::ConstKind::Placeholder(_) => {
+                            return ProcessResult::Changed(mk_pending(vec![]));
                         }
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/fulfill.rs:471]: will this just always stall? Is this even reachable? (and why don't we do the same as the new solver and look it up in the param env?

**Review by oli-obk — CHANGES_REQUESTED** [review]
partial review

File: compiler/rustc_trait_selection/src/solve/mod.rs (hunk 3 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/solve/mod.rs:238]: cant it'll ICE, we call this _before_ checking this clause is a `ConstArgHasType`, so this might actually be a clause with bound vars- but if it is we ignore it anyway because its not a `ConstArgHasType`

File: compiler/rustc_trait_selection/src/traits/fulfill.rs (hunk 4 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/fulfill.rs:461]: I wanted to do this but the struct is defined somewhere we dont have access to the `type_of` query

File: compiler/rustc_trait_selection/src/traits/fulfill.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/fulfill.rs:471]: In the new solver we canonicalize `ConstKind::Param` to `ConstKind::Placeholder` so we turn param env's with `ConstArgHasType(T/#0, usize)` into `ConstArgHasType(!0, usize)` so we will actually have candidate for placeholders. (But we still wont have any in the new solver for higher ranked consts, i.e. `for<const N: usize>`) after instantiating the binder with placeholders)

File: compiler/rustc_trait_selection/src/solve/mod.rs (hunk 3 above)
Comment (oli-obk) [reply compiler/rustc_trait_selection/src/solve/mod.rs:238]: ah 🤦

Comment (oli-obk) [reply compiler/rustc_trait_selection/src/solve/mod.rs:238]: you could match in a `map_bound` closure and `no_bound_vars()` it at the end, but your assertion seems fine, too

File: compiler/rustc_trait_selection/src/traits/fulfill.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/fulfill.rs:471]: I think also this won't stall it will just succeed (i.e. equivalent `Ok(Certainty::Yes)` in the new solver)

Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/fulfill.rs:471]: So I think this is probably unreachable because the only way we should get placeholders is via instantiating a binder such as `for<const N: usize.`. Those are only writeable via `feature(non_lifetime_binders)` and that feature is super unstable (i.e. it doesn't really matter if it's a bit broken here). `compare_impl_item` artificially creates a `ParamEnv` with `for<const N: usize>` however since its  a `ParamEnv` we're only ever going to end up instantiating that binder with inference variables. (we dont seem to normalize this env afaict).

I think I should probably just turn this into an `unreachable!()` so worst case we hit an ICE here instead of unsoundness.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs [hunk 6]
```diff
@@ -141,9 +141,8 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
                         // `trait_object_dummy_self`, so check for that.
                         let references_self = match pred.skip_binder().term.unpack() {
                             ty::TermKind::Ty(ty) => ty.walk().any(|arg| arg == dummy_self.into()),
-                            ty::TermKind::Const(c) => {
-                                c.ty().walk().any(|arg| arg == dummy_self.into())
-                            }
+                            // FIXME(associated_const_equality): We should walk the const instead of not doing anything
+                            ty::TermKind::Const(_) => false,
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/object_safety.rs:145]: Yes, indeed. You can leave it as is. I need to work on assoc const eq inside trait obj tys anyway. Adding one more FIXME is fine.

I've been meaning to fix `trait_object_dummy_self` getting leaked via const projections (* #123456, #123140, #125957) for a while now (but it's ugly).

File: compiler/rustc_middle/src/ty/consts/kind.rs [hunk 7]
```diff
@@ -40,14 +40,125 @@ impl<'tcx> ty::UnevaluatedConst<'tcx> {
...
+            }
+            _ => bug!("Invalid args for `Cast` expr {self:?}"),
+        }
+    }
+
+    pub fn new(kind: ExprKind, args: ty::GenericArgsRef<'tcx>) -> Self {
+        Self { kind, args }
+    }
+
+    pub fn args(&self) -> ty::GenericArgsRef<'tcx> {
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/consts/kind.rs:158]:
```suggestion
pub fn args(self) -> ty::GenericArgsRef<'tcx> {
```
may resolve in a later PR, but why is that a method instead of just accessing the field?

File: compiler/rustc_middle/src/ty/consts/kind.rs [hunk 8]
```diff
@@ -40,14 +40,125 @@ impl<'tcx> ty::UnevaluatedConst<'tcx> {
...
+            [ty, ct] => (ty.expect_ty(), ct.expect_const()),
+            _ => bug!("Invalid args for `UnOp` expr {self:?}"),
+        }
+    }
+
+    pub fn new_call(
+        tcx: TyCtxt<'tcx>,
+        func_ty: Ty<'tcx>,
+        func_expr: Const<'tcx>,
+        arguments: impl Iterator<Item = Const<'tcx>>,
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/consts/kind.rs:107]:
```suggestion
        arguments: impl IntoIterator<Item = Const<'tcx>>,
```

File: compiler/rustc_ty_utils/src/consts.rs [hunk 9]
```diff
@@ -148,17 +148,24 @@ fn recurse_build<'tcx>(
             for &id in args.iter() {
                 new_args.push(recurse_build(tcx, body, id, root_span)?);
             }
-            let new_args = tcx.mk_const_list(&new_args);
-            ty::Const::new_expr(tcx, Expr::FunctionCall(fun, new_args), node.ty)
+            ty::Const::new_expr(
+                tcx,
+                Expr::new_call(tcx, fun.ty(), fun, new_args.into_iter()),
```
Comment (lcnr) [inline compiler/rustc_ty_utils/src/consts.rs]:
```suggestion
                Expr::new_call(tcx, fun.ty(), fun, new_args),
```

File: compiler/rustc_middle/src/ty/relate.rs [hunk 10]
```diff
@@ -652,18 +652,17 @@ pub fn structurally_relate_consts<'tcx, R: TypeRelation<'tcx>>(
         // and is the better alternative to waiting until `generic_const_exprs` can
         // be stabilized.
         (ty::ConstKind::Unevaluated(au), ty::ConstKind::Unevaluated(bu)) if au.def == bu.def => {
-            assert_eq!(a.ty(), b.ty());
+            let a_ty = tcx.type_of(au.def).instantiate(tcx, au.args);
+            let b_ty = tcx.type_of(bu.def).instantiate(tcx, bu.args);
+            assert_eq!(a_ty, b_ty);
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/relate.rs:657]:
```suggestion
            if cfg!(debug_assertions) {
                let a_ty = tcx.type_of(au.def).instantiate(tcx, au.args);
                let b_ty = tcx.type_of(bu.def).instantiate(tcx, bu.args);
                assert_eq!(a_ty, b_ty);
            }
```

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 11]
```diff
@@ -2409,7 +2409,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         min_len: u64,
     ) -> (Option<Ty<'tcx>>, Ty<'tcx>) {
         let len = match len.eval(self.tcx, self.param_env, span) {
-            Ok(val) => val
+            Ok((_, val)) => val
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:2412]: debug assert that the type is `usize`?

File: compiler/rustc_middle/src/ty/consts.rs [hunk 12]
```diff
@@ -311,7 +307,7 @@ impl<'tcx> Const<'tcx> {
         tcx: TyCtxt<'tcx>,
         param_env: ParamEnv<'tcx>,
         span: Span,
-    ) -> Result<ValTree<'tcx>, ErrorHandled> {
+    ) -> Result<(Ty<'tcx>, ValTree<'tcx>), ErrorHandled> {
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/consts.rs:310]:
```suggestion
    ) -> Result<(ValTree<'tcx>, Ty<'tcx>)>, ErrorHandled>
```

or tbh, maybe add

```rust
struct ConstValue {
    data: ValTree<'tcx>,
    ty: Ty<'tcx>,
}
```
would be open to leave that for a separate PR though, we should merge this fairly quickly as it's quite prone to merge conflicts

File: compiler/rustc_middle/src/mir/consts.rs [hunk 13]
```diff
@@ -204,7 +204,7 @@ pub enum Const<'tcx> {
     /// Any way of turning `ty::Const` into `ConstValue` should go through `valtree_to_const_val`;
     /// this ensures that we consistently produce "clean" values without data in the padding or
     /// anything like that.
-    Ty(ty::Const<'tcx>),
+    Ty(Ty<'tcx>, ty::Const<'tcx>),
```
Comment (lcnr) [inline compiler/rustc_middle/src/mir/consts.rs:207]: I think we should do a bigger change and not add this `Ty<'tcx>`. We should always be able to recompute it should either be used with a `ParamEnv` or is a value.

This is for a separate PR though, so please add a fixme for now.
```suggestion
    // FIXME: Remove this `Ty<'tcx>` again and look up the type for params
    // in the `param_env` instead.
    Ty(Ty<'tcx>, ty::Const<'tcx>),
```

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 14]
```diff
@@ -2204,19 +2195,20 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
                                 _ => {
                                     let err = tcx
                                         .dcx()
                                         .emit_err(crate::errors::NonConstRange { span: expr.span });
-                                    ty::Const::new_error(tcx, err, ty)
+                                    (ty::Const::new_error(tcx, err), Ty::new_error(tcx, err))
                                 }
                             };
-                            self.record_ty(expr.hir_id, c.ty(), expr.span);
+                            self.record_ty(expr.hir_id, c_ty, expr.span);
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2209]: :thinking: what is this used for, when do we access the type of constants in the `TypeckResults`?

not something we have to look at in this PR

File: compiler/rustc_middle/src/traits/mod.rs [hunk 15]
```diff
@@ -616,6 +616,8 @@ pub enum SelectionError<'tcx> {
     /// We can thus not know whether the hidden type implements an auto trait, so
     /// we should not presume anything about it.
     OpaqueTypeAutoTraitLeakageUnknown(DefId),
+    /// Error for a `ConstArgHasType` goal
+    ConstArgHasWrongType(ty::Const<'tcx>, Ty<'tcx>, Ty<'tcx>),
```
Comment (lcnr) [inline compiler/rustc_middle/src/traits/mod.rs:620]:
```suggestion
    ConstArgHasWrongType {
       ct: ty::Const<'tcx>,
       expected_ty: Ty<'tcx>,
       actual_ty: Ty<'tcx>
    },
```
or sth

File: compiler/rustc_trait_selection/src/solve/mod.rs [hunk 16]
```diff
@@ -206,21 +208,58 @@ impl<'a, 'tcx> EvalCtxt<'a, InferCtxt<'tcx>> {
...
+            ty::ConstKind::Expr(_) => unimplemented!(
+                "`feature(generic_const_exprs)` is not supported in the new trait solver"
+            ),
+            ty::ConstKind::Param(_) => {
+                unreachable!("`ConstKind::Param` should have been canonicalized to `Placeholder`")
+            }
+            ty::ConstKind::Bound(_, _) => bug!("escaping bound vars in {:?}", ct),
+            ty::ConstKind::Value(ty, _) => ty,
+            ty::ConstKind::Placeholder(placeholder) => {
+                let mut candidates = goal.param_env.caller_bounds().iter().filter_map(|clause| {
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/solve/mod.rs:236]: 1. This should also be a function on `PlaceholderConst`, similar to `ParamConst`
2. This likely ICE's with `non_lifetime_binders`, as it should (for now)

File: compiler/rustc_trait_selection/src/traits/fulfill.rs [hunk 17]
```diff
@@ -438,28 +438,52 @@ impl<'a, 'tcx> ObligationProcessor for FulfillProcessor<'a, 'tcx> {
...
+                        ty::ConstKind::Placeholder(_) => {
+                            bug!("placeholder const {:?} in old solver", ct)
                         }
+                        ty::ConstKind::Bound(_, _) => bug!("escaping bound vars in {:?}", ct),
+                        ty::ConstKind::Param(param_ct) => {
+                            param_ct.find_ty_from_env(obligation.param_env)
+                        }
+                    };
+
+                    match self.selcx.infcx.at(&obligation.cause, obligation.param_env).eq(
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/fulfill.rs:477]:
```suggestion
                    match infcx.at(&obligation.cause, obligation.param_env).eq(
```

File: compiler/rustc_type_ir/src/canonical.rs [hunk 18]
```diff
@@ -169,13 +169,13 @@ pub enum CanonicalVarKind<I: Interner> {
...
 
     /// Effect variable `'?E`.
     Effect,
 
     /// A "placeholder" that represents "any const".
-    PlaceholderConst(I::PlaceholderConst, I::Ty),
+    PlaceholderConst(I::PlaceholderConst),
 }
 
 impl<I: Interner> PartialEq for CanonicalVarKind<I> {
```
Comment (lcnr) [inline compiler/rustc_type_ir/src/canonical.rs:181]: this should be a `derivative(PartialEq(bound = ""))`

**Review by lcnr — COMMENTED** [review]
there are a lot of future cleanups here, which include (but are not limited to)

- stuff that computes a `ValTree` should return a `Ty<'tcx>` as well, given that this type has already been used to compute the `ValTree`. I would like to move `ValTree + Ty` into a `struct ConstValue` which is returned instead of `ValTree`s themself.

- it's questionable that mir constants store a `Ty` for type system constants. This should be necessary and they should also fetch their actual type from the env

all in all, some nits and future cleanups, but I am very happy about this PR. Mostly ignored the `stable_mir` changes, but they didn't look obviously wrong, going to delegate that to @oli-obk

r=me after handling my nits

File: src/rustdoc-json-types/lib.rs [hunk 19]
```diff
@@ -256,7 +254,12 @@ pub enum ItemEnum {
 
     TypeAlias(TypeAlias),
     OpaqueTy(OpaqueTy),
-    Constant(Constant),
+    Constant {
+        #[serde(rename = "type")]
+        type_: Type,
+        #[serde(rename = "const")]
+        const_: Constant,
```
Comment (aDotInTheVoid) [inline src/rustdoc-json-types/lib.rs:261]: This is fine for now, but once this lands, I'd like to look into using seperate type for `Item::Constant` and `Term::Constant`/`GenericArgKind::Constant`, so this can be flattened again. But this shoudn't block this PR.

**Review by aDotInTheVoid — COMMENTED** [review]
rustdoc-json side looks good to me. 6d22d767645c0cd30e9b5a9f9dd90368bbafc686 contains the fix to `jsondoclint`. kinda concerning that rustdoc-json has no tests for this 😅

File: src/rustdoc-json-types/lib.rs (hunk 19 above)
Comment (obi1kenobi) [reply src/rustdoc-json-types/lib.rs:261]: As `cargo-semver-checks` maintainer, I'd love it if it's possible to make all the proposed representation changes quickly so that the separated representation is not the one that makes it into the next beta in ~9 days time.

If it goes into beta and then becomes stable, then I'll have to support both the separated representation and the newer form, and `cargo-semver-checks` will have to compile one more crate than otherwise — both negatives on my end.

If it's not possible to do that, and in your opinion it's better for the overall Rust community if I draw the short straw here, that's okay — I can handle it. I just would like to ask that it be a considered, intentional decision and not just unfortunate happenstance.

File: compiler/rustc_next_trait_solver/src/canonicalizer.rs [hunk 20]
```diff
@@ -386,47 +386,37 @@ impl<Infcx: InferCtxtLike<Interner = I>, I: Interner> TypeFolder<I>
     }
 
     fn fold_const(&mut self, c: I::Const) -> I::Const {
-        // We could canonicalize all consts with static types, but the only ones we
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/canonicalizer.rs:389]: 😺

File: compiler/rustc_type_ir/src/const_kind.rs [hunk 21]
```diff
@@ -51,7 +51,7 @@ impl<I: Interner> PartialEq for ConstKind<I> {
             (Bound(l0, l1), Bound(r0, r1)) => l0 == r0 && l1 == r1,
             (Placeholder(l0), Placeholder(r0)) => l0 == r0,
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_type_ir/src/const_kind.rs:52]: Similarly here

[the remark this answers is not in the document]
Comment (lcnr) [reply compiler/rustc_type_ir/src/const_kind.rs:52]: let's not do that in this PR then

File: compiler/rustc_middle/src/ty/consts/kind.rs (hunk 7 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/ty/consts/kind.rs:158]: originally I just _didnt_ want to give access to the args since they're always in a specific format and the `GenericArgsRef` loses that information. turned out I needed it for `structurally_relate_tys` and now I just sort of kept it because all the _other_ ways of accessing the args go through a method so,,

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 11 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/pat.rs:2412]: I think this will probably ICE under `adt_const_params` since we can have aliases for the `type_of` of anon consts which we sometimes use as the `Ty` here. (which I think is a bit gross but lol this PR was huge already)

Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/pat.rs:2412]: Added a `FIXME` I'll try get to this soon

File: compiler/rustc_middle/src/mir/consts.rs (hunk 13 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:209]: Agreed, not really happy with how this basically just skips out on not storing `Ty` for `ty::Const` for this part of the compiler. Will look into `mir::Const::Ty` more after this PR lands

File: compiler/rustc_middle/src/ty/consts.rs (hunk 12 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/ty/consts.rs:310]: nods will follow up with this

File: src/rustdoc-json-types/lib.rs (hunk 19 above)
Comment (workingjubilee) [reply src/rustdoc-json-types/lib.rs:261]: Further discussion should go to #125974

File: tests/debuginfo/function-names.rs [hunk 22]
```diff
@@ -76,7 +76,7 @@
 // Const generic parameter
 // cdb-command:x a!function_names::const_generic_fn*
 // cdb-check:[...] a!function_names::const_generic_fn_bool<false> (void)
-// cdb-check:[...] a!function_names::const_generic_fn_non_int<CONST$ad91263f6d2dd96e> (void)
+// cdb-check:[...] a!function_names::const_generic_fn_non_int<CONST#[...]> (void)
```
Comment (compiler-errors) [inline tests/debuginfo/function-names.rs:79]:
```suggestion
// cdb-check:[...] a!function_names::const_generic_fn_non_int<CONST$[...]> (void)
```

**Comment by compiler-errors** [comment]
@bors r=lcnr

One more time!!!

**Comment by BoxyUwU** [comment]
Holy fuck

**Comment by workingjubilee** [comment]
cursed you say?
@bors p=13

**Comment by BoxyUwU** [comment]
...

**Comment by compiler-errors** [comment]
praying

@bors r=lcnr

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs [hunk 23]
```diff
@@ -85,7 +88,10 @@ fn encode_args<'tcx>(
                     s.push_str(&encode_ty(tcx, ty, dict, options));
                 }
                 GenericArgKind::Const(c) => {
-                    s.push_str(&encode_const(tcx, c, dict, options));
+                    let n = n + (has_erased_self as usize);
+                    let ct_ty =
+                        tcx.type_of(def_generics.param_at(n, tcx).def_id).instantiate_identity();
```
Comment (rcvalle) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:93]: Could this ty resolution be done in encode_const?

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs [hunk 24]
```diff
@@ -231,15 +238,21 @@ fn encode_predicate<'tcx>(
...
             let _ = write!(s, "u{}{}", name.len(), &name);
-            s.push_str(&encode_args(tcx, projection.args, dict, options));
+            s.push_str(&encode_args(tcx, projection.args, projection.def_id, true, dict, options));
             match projection.term.unpack() {
                 TermKind::Ty(ty) => s.push_str(&encode_ty(tcx, ty, dict, options)),
-                TermKind::Const(c) => s.push_str(&encode_const(tcx, c, dict, options)),
+                TermKind::Const(c) => s.push_str(&encode_const(
+                    tcx,
+                    c,
+                    tcx.type_of(projection.def_id).instantiate(tcx, projection.args),
```
Comment (rcvalle) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:252]: Could this ty resolution also be done in encode_const?

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs [hunk 25]
```diff
@@ -99,6 +105,7 @@ fn encode_args<'tcx>(
 fn encode_const<'tcx>(
     tcx: TyCtxt<'tcx>,
     c: Const<'tcx>,
+    ct_ty: Ty<'tcx>,
```
Comment (rcvalle) [inline compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:108]: Could Const and Ty be rebundled in a struct (e.g., ConstAndTy)  just for this file for consistency a with other methods?

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs (hunk 23 above)
Comment (workingjubilee) [reply compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:93]: This instantiation is different.

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs (hunk 24 above)
Comment (workingjubilee) [reply compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:252]: This instantiation is different from the other instantiation.

File: compiler/rustc_pattern_analysis/src/rustc.rs [hunk 26]
```diff
@@ -737,7 +737,7 @@ impl<'p, 'tcx: 'p> RustcPatCtxt<'p, 'tcx> {
                 // this). We show this to the user as `usize::MAX..` which is slightly incorrect but
                 // probably clear enough.
                 let c = ty.numeric_max_val(cx.tcx).unwrap();
-                let value = mir::Const::from_ty_const(c, cx.tcx);
+                let value = mir::Const::from_ty_const(c, self.tcx.types.usize, cx.tcx);
```
Comment (Nadrieril) [inline compiler/rustc_pattern_analysis/src/rustc.rs:740]: This is incorrect, we can also get `isize` here.
```suggestion
                let value = mir::Const::from_ty_const(c, ty, cx.tcx);
```

Comment (Nadrieril) [reply compiler/rustc_pattern_analysis/src/rustc.rs:740]: What's weird is that there are tests for the `isize` case in `tests/ui/pattern/usefulness/integer-ranges/pointer-sized-int.rs`. Do you use that type argument atm?

Comment (BoxyUwU) [reply compiler/rustc_pattern_analysis/src/rustc.rs:740]: shit thanks

File: compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs (hunk 25 above)
Comment (BoxyUwU) [reply compiler/rustc_sanitizers/src/cfi/typeid/itanium_cxx_abi/encode.rs:108]: Realistically this ty ought to be unnecessary, theres no reason cfi should be having to deal with `ConstKind::Param`. I want to land that separately after this PR incase it turns out to cause ICE

**Comment by BoxyUwU** [comment]
I've just removed the failing windows debug info tests:
```
// cdb-check:[...] a!function_names::const_generic_fn_non_int<CONST$a70c39591cb5f53d> (void)
// cdb-check:[...] a!function_names::const_generic_fn_unsigned_int<14> (void)
// cdb-check:[...] a!function_names::const_generic_fn_signed_int<-7> (void)
 ```

due to the fact that this PR is immensely bitrotty and also its giving error messages like "could not find X" despite it also saying "X" _is_ in the output:


```
error: check directive(s) from `C:\a\rust\rust\tests\debuginfo\function-names.rs` not found in debugger output. errors:
(function-names.rs:80) `[...] a!function_names::const_generic_fn_unsigned_int<14> (void)`
(function-names.rs:81) `[...] a!function_names::const_generic_fn_signed_int<-7> (void)`
```

Then when it does the natvis dump:

```
2024-06-05T11:30:21.9147565Z 00007ff6`37f21170 a!function_names::main (void)
2024-06-05T11:30:21.9147982Z 0:000> x a!function_names::generic_func<*
2024-06-05T11:30:21.9148429Z 00007ff6`37f21350 a!function_names::generic_func<i32> (int)
2024-06-05T11:30:21.9148901Z 0:000> x a!function_names::*::impl_function*
2024-06-05T11:30:21.9149458Z 00007ff6`37f21310 a!function_names::impl$2::impl_function::closure$0<i32,i32> (void)
2024-06-05T11:30:21.9150153Z 00007ff6`37f212d0 a!function_names::Mod1::TestStruct2::impl_function (void)
2024-06-05T11:30:21.9150787Z 00007ff6`37f212b0 a!function_names::TestStruct1::impl_function (void)
2024-06-05T11:30:21.9151488Z 00007ff6`37f212f0 a!function_names::GenericStruct<i32,i32>::impl_function<i32,i32> (void)
2024-06-05T11:30:21.9152078Z 0:000> x a!function_names::*::trait_function*
2024-06-05T11:30:21.9152587Z 00007ff6`37f21320 a!function_names::impl$3::trait_function<i32> (void)
2024-06-05T11:30:21.9153202Z 00007ff6`37f21340 a!function_names::impl$6::trait_function<i32,1> (void)
2024-06-05T11:30:21.9153799Z 00007ff6`37f212c0 a!function_names::impl$1::trait_function (void)
2024-06-05T11:30:21.9154484Z 00007ff6`37f21330 a!function_names::impl$5::trait_function3<function_names::TestStruct1> (void)
2024-06-05T11:30:21.9155190Z 00007ff6`37f212e0 a!function_names::Mod1::impl$1::trait_function (void)
2024-06-05T11:30:21.9155685Z 0:000> x a!function_names::*::closure*
2024-06-05T11:30:21.9156220Z 00007ff6`37f21310 a!function_names::impl$2::impl_function::closure$0<i32,i32> (void)
2024-06-05T11:30:21.9156824Z 00007ff6`37f21220 a!function_names::main::closure$0 (void)
2024-06-05T11:30:21.9157383Z 00007ff6`37f213a0 a!function_names::generic_func::closure$0<i32> (void)
2024-06-05T11:30:21.9157884Z 0:000> x a!function_names::*::coroutine*
2024-06-05T11:30:21.9158341Z 00007ff6`37f21230 a!function_names::main::coroutine$1 (void)
2024-06-05T11:30:21.9158815Z 0:000> x a!function_names::const_generic_fn*
2024-06-05T11:30:21.9159334Z 00007ff6`37f213b0 a!function_names::const_generic_fn_bool<false> (void)
2024-06-05T11:30:21.9159965Z 00007ff6`37f213e0 a!function_names::const_generic_fn_unsigned_int<14> (void)
2024-06-05T11:30:21.9160758Z 00007ff6`37f213d0 a!function_names::const_generic_fn_signed_int<-7> (void)
2024-06-05T11:30:21.9161467Z 00007ff6`37f213c0 a!function_names::const_generic_fn_non_int<CONST$a70c39591cb5f53d> (void)
2024-06-05T11:30:21.9162060Z 0:000> qq
```

**Comment by workingjubilee** [comment]
I wonder if the test is ordering-sensitive.

File: tests/crashes/122908.rs [hunk 27]
```diff
@@ -1,4 +0,0 @@
-//@ known-bug: #122908
-trait Trait<const module_path: Trait = bar> {
-    async fn handle<F>(slf: &F) {}
-}
```
Comment (matthiaskrgr) [inline tests/crashes/122908.rs:4]: .

**Comment by BoxyUwU** [comment]
would you maybe like to specify a reason

File: tests/crashes/125556.rs [hunk 28]
```diff
@@ -1,14 +0,0 @@
...
-
-pub struct A<const z: [usize; x]> {}
-
-impl A<2> {
-    pub const fn B() {}
-}
-
-impl A<2> {
-    pub const fn B() {}
-}
```
Comment (matthiaskrgr) [inline tests/crashes/125556.rs:14]: these should be marked as "fixed" via the if they are no longer crashing and tests have been added.

**Review by matthiaskrgr — CHANGES_REQUESTED** [review]
