### PR TITLE
Display ?Sized, const, and lifetime parameters in trait item suggestions across a crate boundary

### LINKED ISSUE #146404: "not all trait items implemented" error doesn't print const params
I think this function fundamentally works the wrong way (not ur fault, it's prexisting).

It seems to:
1. Iterate over the list of where clauses on an item
2. Look at where clauses that are either `Type<...>: Trait<..>` or `Type<...>: Trait<..., Assoc<...> = ...>`
3. Collect a map (`types`) of all those `Type<...>` to the trait on the rhs of the `:`. e.g. if we have `where u32: Trait, u64: OtherTrait, T: Trait + OtherTrait`, we'd wind up with `[u32 => Trait, u64 => OtherTrait, T => { Trait, OtherTrait }]`
4. We then iterate that map filtering to only keys that are type parameters, and use that to reconstruct the list of generic parameters defined on the item.

this is *completely* incoherent. it assumes multiple things that aren't true:
- Type parameters are the only kind of generic parameters. You can't have `const N: usize` as the self type of a trait bound, so it never winds up in `types` so we'll never wind up putting const generics in the final `generics` string. [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=8a6c6789c3123f616aeca43dd7e0383e) (run `test`)
- Type parameters are *always* used in the self type of a trait bound. This was not true on stable until *very* recently when we made `T: ?Sized` be sugar for `T: MetaSized`. You can still observe this with the `rustc_no_implicit_bounds` attr: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=01c4cb4acbb2d87af6a805e9d9fd3ba3) (run `test`). Also this means that right now `T: ?Sized` on stable gets re-sugared as `T: MetaSized` which is wrong

---

Instead, we should *unconditionally* accept an `AssocItem` so that we can *always* call `generics_of` to get the list of generic parameters defined on the item.

You can then independently construct the `types_str` by iterating over the generic parameters from `generics_of` and fetching any bounds on them from the `types` map.

The existing for loop over `types` can be left mostly as-is, just removing the parts of it that mutate types_str. 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145929/94722cabf4983abcbe5088c1b8e81517ba2a7126..ac15a624b1c5a772fdb91af7a6e896625a086c2d)*

_Originally posted by @BoxyUwU in https://github.com/rust-lang/rust/pull/145929#pullrequestreview-3194503887_

### PR DESCRIPTION
**Pull request by Qelxiros**
context: rust-lang/rust#145929

This fixes the MetaSized issue and adds const generics and early bound lifetimes. Late bound lifetimes are harder because they aren't returned by `generics_of`. I'm going to look into it, but there's no guarantee I'll be successful.

Fixes https://github.com/rust-lang/rust/issues/146404.

r? @BoxyUwu

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 1]
```diff
@@ -351,65 +353,101 @@ fn bounds_from_generic_predicates<'tcx>(
...
-                    for projection in &projections {
-                        let p = projection.skip_binder();
-                        if bound == tcx.parent(p.projection_term.def_id)
-                            && p.projection_term.self_ty() == ty
-                        {
-                            let name = tcx.item_name(p.projection_term.def_id);
-                            projections_str.push(format!("{} = {}", name, p.term));
+        .filter(|p| !matches!(p.kind, GenericParamDefKind::Type { synthetic: true, .. }))
+        .map(|p| match tcx.mk_param_from_def(p) {
+            x if let Some(ty) = x.as_type() => {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
        .map(|p| match tcx.mk_param_from_def(p).kind() {
            ty::GenericArgKind::Type(ty) => {
```
and for the const/region arms too, then you can get rid of the unreachable branches

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 2]
```diff
@@ -351,65 +353,101 @@ fn bounds_from_generic_predicates<'tcx>(
...
-                for bound in bounds.iter().copied() {
-                    let mut projections_str = vec![];
-                    for projection in &projections {
-                        let p = projection.skip_binder();
-                        if bound == tcx.parent(p.projection_term.def_id)
-                            && p.projection_term.self_ty() == ty
-                        {
-                            let name = tcx.item_name(p.projection_term.def_id);
-                            projections_str.push(format!("{} = {}", name, p.term));
+        .filter(|p| !matches!(p.kind, GenericParamDefKind::Type { synthetic: true, .. }))
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
        .filter(|p| !p.kind().is_synthetic())
```

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 3]
```diff
@@ -351,65 +353,101 @@ fn bounds_from_generic_predicates<'tcx>(
...
+        .map(|p| match tcx.mk_param_from_def(p) {
+            x if let Some(ty) = x.as_type() => {
+                if let Some(bounds) = types.get(&ty) {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
                let bounds = types.get(&ty).unwrap_or(Vec::new);
```
removes some indentation and generally should make things a bit cleaner

**Review by BoxyUwU — COMMENTED** [review]
late bound lifetimes seem... very difficult to implement here, and also somewhat interesting because we don't actually require the set of late bound lifetimes on the impl to exactly match the set on the trait definition. so I think it doesn't make sense to list them :thinking: 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146442/76c5ed2847cdb26ef2822a3a165d710f6b772217..f336c238c5cdfc2164da917a31fa6e4b6051f961)*

File: compiler/rustc_hir_analysis/src/check/mod.rs [hunk 4]
```diff
@@ -393,23 +402,44 @@ fn bounds_from_generic_predicates<'tcx>(
...
-            );
+            where_clauses.extend(bounds.into_iter().map(|bound| {
+                format!(
+                    "{}: {}",
+                    ty,
+                    if tcx.is_lang_item(bound, LangItem::MetaSized) {
+                        String::from("?Sized")
+                    } else {
+                        tcx.def_path_str(bound)
+                    }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/mod.rs]:
```suggestion
                    tcx.def_path_str(bound)
```
`: ?Sized` syntax only makes sense on type parameters. for all other types that have a `MetaSized` bound it really should just be that syntax. Can you add a test that has `where Foo<T>: MetaSized`?
