### PR TITLE
Warn against calls which mutate an interior mutable `const`-item

### LINKED ISSUE #40543: Produce a warning when using `const` with interior mutability
Originally reported in https://users.rust-lang.org/t/broken-atomics-puzzle/9533

Consider this code

```rust
use std::sync::atomic::{AtomicBool, Ordering};

pub const A: AtomicBool = AtomicBool::new(false);

fn main() {
    A.compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst);
    println!("A = {}", A.load(Ordering::SeqCst));
}
```
[Playground](https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=8f714787458e6a0a7eb96591cd0ce6b1)

It compiles and runs cleanly, but produces unexpected results because `const` is used instead of `static`. 

It would be nice to somehow give a warning for `.compare_and_swap` call, but I am not sure it is possible.

### LINKED ISSUE #132028: Silent failure of std::sync::Once when in const variable
I tried this code [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e872d18e2c2ee6a806f7872052fbd744):

```rust
use std::sync::Once;

const INIT: Once = Once::new();

fn main() {
    INIT.call_once(|| {
        println!("Global Once::call_once first call");
    });
    INIT.call_once(|| {
        println!("Global Once::call_once second call");
    });
}
```

The problem is that my Once is in a `const` and not a `static`. However, I would expect a compile error or a runtime error instead of broken behavior here. The same behavior is exhibited in `std::sync::LazyLock` and probably `std::sync::OnceLock`, due to using a Once internally.

Thanks for considering this!

### Meta
Checked on 1.82.0 and on nightly.

### PR DESCRIPTION
**Pull request by Urgau**
## `const_item_interior_mutations`

~~`interior_mutable_const_item_mutations`~~

~~`suspicious_mutation_of_interior_mutable_consts`~~

*warn-by-default*

The `const_item_interior_mutations` lint checks for calls which mutates an interior mutable const-item.

### Example

```rust
use std::sync::Once;

const INIT: Once = Once::new(); // using `INIT` will always create a temporary and
                                // never modify it-self on use, should be a `static`
                                // instead for shared use

fn init() {
    INIT.call_once(|| {
        println!("Once::call_once first call");
    });
}
```

```text
warning: mutation of an interior mutable `const` item with call to `call_once`
  --> a.rs:11:5
   |
11 |       INIT.call_once(|| {
   |       ^---
   |       |
   |  _____`INIT` is a interior mutable `const` item of type `std::sync::Once`
   | |
12 | |         println!("Once::call_once first call");
13 | |     });
   | |______^
   |
   = note: each usage of a `const` item creates a new temporary
   = note: only the temporaries and never the original `const INIT` will be modified
   = help: for more details on interior mutability see <https://doc.rust-lang.org/reference/interior-mutability.html>
   = note: `#[warn(const_item_interior_mutations)]` on by default
help: for a shared instance of `INIT`, consider making it a `static` item instead
   |
 6 - const INIT: Once = Once::new(); // using `INIT` will always create a temporary and
 6 + static INIT: Once = Once::new(); // using `INIT` will always create a temporary and
   |
```

### Explanation

Calling a method which mutates an interior mutable type has no effect as const-item are essentially inlined wherever they are used, meaning that they are copied directly into the relevant context when used rendering modification through interior mutability ineffective across usage of that const-item.

The current implementation of this lint only warns on significant `std` and `core` interior mutable types, like `Once`, `AtomicI32`, ... this is done out of prudence and may be extended in the future.

----

This PR is an targeted alternative to rust-lang/rust#132146. It avoids false-positives by adding an internal-only attribute `#[rustc_should_not_be_called_on_const_items]` on methods and functions that mutates an interior mutale type through a shared reference (mutable refrences are already linted by the `const_item_mutation` lint).

It should also be noted that this is NOT an uplift of the more general [`clippy::borrow_interior_mutable_const`](https://rust-lang.github.io/rust-clippy/master/index.html#/borrow_interior_mutable_const) lint, which is a much more general lint regarding borrow of interior mutable types, but has false-positives that are completly avoided by this lint.

A simple [GitHub Search](https://github.com/search?q=lang%3Arust+%2F%28%3F-i%29const+%5Ba-zA-Z0-9_%5D*%3A+Once%2F&type=code) reveals many instance where the user probably wanted to use a `static`-item instead.

----

@rustbot labels +I-lang-nominated +T-lang
cc @traviscross
r? compiler

Fixes [IRLO - Forbidding creation of constant mutexes, etc](https://internals.rust-lang.org/t/forbidding-creation-of-constant-mutexes-etc/19005)
Fixes https://github.com/rust-lang/rust/issues/132028
Fixes https://github.com/rust-lang/rust/issues/40543

### CODE REVIEW

**Comment by traviscross** [comment]
Makes sense to me.  I propose we do this.

@rfcbot fcp merge

**Comment by camsteffen** [comment]
For naming, `s/interior mutable item mutations/item interior mutations`.

**Comment by nikomatsakis** [comment]
I prefer @camsteffen's proposed name. The lint makes sense to me.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

File: compiler/rustc_attr_parsing/src/attributes/lint_helpers.rs [hunk 1]
```diff
@@ -38,6 +38,17 @@ impl<S: Stage> NoArgsAttributeParser<S> for PassByValueParser {
     const CREATE: fn(Span) -> AttributeKind = AttributeKind::PassByValue;
 }
 
+pub(crate) struct RustcShouldNotBeCalledOnConstItems;
+impl<S: Stage> NoArgsAttributeParser<S> for RustcShouldNotBeCalledOnConstItems {
+    const PATH: &[Symbol] = &[sym::rustc_should_not_be_called_on_const_items];
+    const ON_DUPLICATE: OnDuplicate<S> = OnDuplicate::Error;
+    const ALLOWED_TARGETS: AllowedTargets = AllowedTargets::AllowList(&[
+        Allow(Target::Method(MethodKind::Inherent)),
+        Allow(Target::Method(MethodKind::TraitImpl)),
```
Comment (JonathanBrouwer) [inline compiler/rustc_attr_parsing/src/attributes/lint_helpers.rs:47]: Should this be allowed on `Target::Method(MethodKind::Trait { body: true })` and `Target::Method(MethodKind::Trait { body: false })`  too?
Doesn't really matter that much because this is an unstable attribute and we can always change it later, but I think adding that makes sense

Comment (Urgau) [reply compiler/rustc_attr_parsing/src/attributes/lint_helpers.rs:47]: I don't know how the code will react to those. I suspect the call to [`type_dependent_def_id`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TypeckResults.html#method.type_dependent_def_id) will give us the `DefId` of the implementation, not the `DefId` of the method definition in the trait.

I think it's better to wait until we have an actual use-case.

File: tests/ui/lint/const-item-interior-mutations-const-atomics.stderr [hunk 2]
```diff
@@ -0,0 +1,816 @@
...
+   |              `A` is a interior mutable `const` item of type `AtomicBool`
+   |
+   = note: each usage of a `const` item creates a new temporary
+   = note: only the temporaries and never the original `const A` will be modified
+   = help: for more details on interior mutability see <https://doc.rust-lang.org/reference/interior-mutability.html>
+   = note: `#[warn(const_item_interior_mutations)]` on by default
+help: for a shared instance of `A`, consider making it a `static` item instead
+   |
+LL -     const A: AtomicBool = AtomicBool::new(false);
+LL +     static A: AtomicBool = AtomicBool::new(false);
```
Comment (JonathanBrouwer) [inline tests/ui/lint/const-item-interior-mutations-const-atomics.stderr]: It's definitely a bit strange to call load on a const atomic, but I think the lint would be confusing because it is not a mutation.

Specifically the sentence `mutation of an interior mutable const item with call to load` is not technically correct

I think either:
- The lint should not specifically accuse of "mutation"
- We should remove this case

I'm leaning towards removing the case but I'm open to both solutions.

**Review by JonathanBrouwer — CHANGES_REQUESTED** [review]

File: compiler/rustc_attr_parsing/src/attributes/lint_helpers.rs (hunk 1 above)
Comment (JonathanBrouwer) [reply compiler/rustc_attr_parsing/src/attributes/lint_helpers.rs:47]: I think it should give the method definition in the trait, at least in generic contexts, but I'm happy to wait for a use-case, sounds reasonable.

File: tests/ui/lint/const-item-interior-mutations-const-atomics.stderr (hunk 2 above)
Comment (Urgau) [reply tests/ui/lint/const-item-interior-mutations-const-atomics.stderr]: Good point. Removed the linting on `Atomic::load`.
