### PR TITLE
mGCA: Validate const literal against expected type

### LINKED ISSUE #133966: ICE: `expected wide pointer extra data (e.g. slice length or trait object vtable)`
snippet:
````rust
pub struct Data([[&str]; 5_i32]);
const _: &'static Data = unsafe { &*(&[] as *const Data) };

````

Version information
````
rustc 1.85.0-nightly (acf48426b 2024-12-06)
binary: rustc
commit-hash: acf48426b64d24f372d534f634072de1f4c7e588
commit-date: 2024-12-06
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.5

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/acf48426b64d24f372d534f634072de1f4c7e588/compiler/rustc_const_eval/src/interpret/place.rs#L30-L42

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0106]: missing lifetime specifier
 --> /tmp/icemaker_global_tempdir.aSYe5Is2GJl3/rustc_testrunner_tmpdir_reporting.gKjFHYgJOJDL/mvce.rs:1:19
  |
1 | pub struct Data([[&str]; 5_i32]);
  |                   ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 | pub struct Data<'a>([[&'a str]; 5_i32]);
  |                ++++    ++

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.aSYe5Is2GJl3/rustc_testrunner_tmpdir_reporting.gKjFHYgJOJDL/mvce.rs:2:60
  |
2 | const _: &'static Data = unsafe { &*(&[] as *const Data) };
  |                                                            ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.aSYe5Is2GJl3/rustc_testrunner_tmpdir_reporting.gKjFHYgJOJDL/mvce.rs`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/place.rs:36:17: expected wide pointer extra data (e.g. slice length or trait object vtable)

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/place.rs:36:17:
Box<dyn Any>
stack backtrace:
   0:     0x7ad09f54895a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h69edfa39ad21a03a
   1:     0x7ad09fc13e26 - core::fmt::write::h54afaacea6c2c9e2
   2:     0x7ad0a0bf3ad1 - std::io::Write::write_fmt::h00e73f8f3070368c
   3:     0x7ad09f5487b2 - std::sys::backtrace::BacktraceLock::print::h2b0900033e71643f
   4:     0x7ad09f54acca - std::panicking::default_hook::{{closure}}::h325b3b03f2ea7a39
   5:     0x7ad09f54ab13 - std::panicking::default_hook::haaf25a6e7afde799
   6:     0x7ad09e6c1238 - std[85c61899f894cf29]::panicking::update_hook::<alloc[98b3c20953f4fbe5]::boxed::Box<rustc_driver_impl[45224e78b6d2fe59]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7ad09f54b488 - std::panicking::rust_panic_with_hook::hdc045113cf0fafba
   8:     0x7ad09e6f6771 - std[85c61899f894cf29]::panicking::begin_panic::<rustc_errors[2297728cd06420b6]::ExplicitBug>::{closure#0}
   9:     0x7ad09e6eb916 - std[85c61899f894cf29]::sys::backtrace::__rust_end_short_backtrace::<std[85c61899f894cf29]::panicking::begin_panic<rustc_errors[2297728cd06420b6]::ExplicitBug>::{closure#0}, !>
  10:     0x7ad09e6eb6d3 - std[85c61899f894cf29]::panicking::begin_panic::<rustc_errors[2297728cd06420b6]::ExplicitBug>
  11:     0x7ad09e700711 - <rustc_errors[2297728cd06420b6]::diagnostic::BugAbort as rustc_errors[2297728cd06420b6]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7ad09ece86d3 - rustc_middle[2b65deb07cad4442]::util::bug::opt_span_bug_fmt::<rustc_span[267b34eb586afd37]::span_encoding::Span>::{closure#0}
  13:     0x7ad09ecd0c0a - rustc_middle[2b65deb07cad4442]::ty::context::tls::with_opt::<rustc_middle[2b65deb07cad4442]::util::bug::opt_span_bug_fmt<rustc_span[267b34eb586afd37]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7ad09ecd0a9b - rustc_middle[2b65deb07cad4442]::ty::context::tls::with_context_opt::<rustc_middle[2b65deb07cad4442]::ty::context::tls::with_opt<rustc_middle[2b65deb07cad4442]::util::bug::opt_span_bug_fmt<rustc_span[267b34eb586afd37]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7ad09ce2a8d0 - rustc_middle[2b65deb07cad4442]::util::bug::bug_fmt
  16:     0x7ad0a07da666 - <rustc_const_eval[c1d2b202d9973a02]::interpret::validity::ValidityVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine> as rustc_const_eval[c1d2b202d9973a02]::interpret::visitor::ValueVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine>>::visit_value
  17:     0x7ad0a07d8eeb - <rustc_const_eval[c1d2b202d9973a02]::interpret::validity::ValidityVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine> as rustc_const_eval[c1d2b202d9973a02]::interpret::visitor::ValueVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine>>::visit_value
  18:     0x7ad0a07d86fe - <rustc_const_eval[c1d2b202d9973a02]::interpret::validity::ValidityVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine> as rustc_const_eval[c1d2b202d9973a02]::interpret::visitor::ValueVisitor<rustc_const_eval[c1d2b202d9973a02]::const_eval::machine::CompileTimeMachine>>::visit_value
  19:     0x7ad0a0808a9c - rustc_const_eval[c1d2b202d9973a02]::const_eval::eval_queries::eval_to_allocation_raw_provider
  20:     0x7ad0a08079be - rustc_query_impl[31526c927efa8eec]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[31526c927efa8eec]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 24usize]>>
  21:     0x7ad0a07efc22 - rustc_query_system[8b7296974754ceb3]::query::plumbing::try_execute_query::<rustc_query_impl[31526c927efa8eec]::DynamicConfig<rustc_query_system[8b7296974754ceb3]::query::caches::DefaultCache<rustc_middle[2b65deb07cad4442]::ty::PseudoCanonicalInput<rustc_middle[2b65deb07cad4442]::mir::interpret::GlobalId>, rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[31526c927efa8eec]::plumbing::QueryCtxt, false>
  22:     0x7ad0a07ef781 - rustc_query_impl[31526c927efa8eec]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7ad0a07f18f9 - rustc_const_eval[c1d2b202d9973a02]::const_eval::eval_queries::eval_to_const_value_raw_provider
  24:     0x7ad0a07f1702 - rustc_query_impl[31526c927efa8eec]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[31526c927efa8eec]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 24usize]>>
  25:     0x7ad0a07efbd9 - rustc_query_system[8b7296974754ceb3]::query::plumbing::try_execute_query::<rustc_query_impl[31526c927efa8eec]::DynamicConfig<rustc_query_system[8b7296974754ceb3]::query::caches::DefaultCache<rustc_middle[2b65deb07cad4442]::ty::PseudoCanonicalInput<rustc_middle[2b65deb07cad4442]::mir::interpret::GlobalId>, rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[31526c927efa8eec]::plumbing::QueryCtxt, false>
  26:     0x7ad0a07ef689 - rustc_query_impl[31526c927efa8eec]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7ad0a003a154 - <rustc_middle[2b65deb07cad4442]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[4e6fa7c2cad24599]::check_crate::{closure#3}>::{closure#0}
  28:     0x7ad0a0037b37 - rustc_hir_analysis[4e6fa7c2cad24599]::check_crate
  29:     0x7ad0a0042584 - rustc_interface[51c1904b6ef58290]::passes::run_required_analyses
  30:     0x7ad0a0bd88de - rustc_interface[51c1904b6ef58290]::passes::analysis
  31:     0x7ad0a0bd88af - rustc_query_impl[31526c927efa8eec]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[31526c927efa8eec]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 1usize]>>
  32:     0x7ad0a0baf7ba - rustc_query_system[8b7296974754ceb3]::query::plumbing::try_execute_query::<rustc_query_impl[31526c927efa8eec]::DynamicConfig<rustc_query_system[8b7296974754ceb3]::query::caches::SingleCache<rustc_middle[2b65deb07cad4442]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[31526c927efa8eec]::plumbing::QueryCtxt, false>
  33:     0x7ad0a0baf48e - rustc_query_impl[31526c927efa8eec]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7ad0a0c503eb - rustc_interface[51c1904b6ef58290]::interface::run_compiler::<core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>, rustc_driver_impl[45224e78b6d2fe59]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7ad0a0b41ca1 - std[85c61899f894cf29]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[51c1904b6ef58290]::util::run_in_thread_with_globals<rustc_interface[51c1904b6ef58290]::util::run_in_thread_pool_with_globals<rustc_interface[51c1904b6ef58290]::interface::run_compiler<core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>, rustc_driver_impl[45224e78b6d2fe59]::run_compiler::{closure#0}>::{closure#1}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>::{closure#0}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>
  36:     0x7ad0a0b41948 - <<std[85c61899f894cf29]::thread::Builder>::spawn_unchecked_<rustc_interface[51c1904b6ef58290]::util::run_in_thread_with_globals<rustc_interface[51c1904b6ef58290]::util::run_in_thread_pool_with_globals<rustc_interface[51c1904b6ef58290]::interface::run_compiler<core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>, rustc_driver_impl[45224e78b6d2fe59]::run_compiler::{closure#0}>::{closure#1}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>::{closure#0}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ce4f568dace374e]::result::Result<(), rustc_span[267b34eb586afd37]::ErrorGuaranteed>>::{closure#1} as core[ce4f568dace374e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7ad0a0b4107b - std::sys::pal::unix::thread::Thread::new::thread_start::h6f16c939ae6ab66d
  38:     0x7ad09aea339d - <unknown>
  39:     0x7ad09af2849c - <unknown>
  40:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.85.0-nightly (acf48426b 2024-12-06) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `_`
#1 [eval_to_const_value_raw] simplifying constant for the type system `_`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0106, E0601.
For more information about an error, try `rustc --explain E0106`.

```

</p>
</details>

### LINKED ISSUE #150983: ICE: `ty::ConstKind::Error constructed but no error reported`
original:
````rust
#![feature(
    generic_const_items,
    min_generic_const_args,
    generic_const_parameter_types,
    unsized_const_params
)]
use std::marker::ConstParamTy_;
struct Foo<T> {
    field: T,
}
#[type_const]
const WRAP<T : ConstParamTy_> : T = {
      Foo::<T>{field : 1}
    };
fn main() {}

````

Version information
````
rustc 1.94.0-nightly (b68e16cfc 2026-01-11)
binary: rustc
commit-hash: b68e16cfc0e9f8b29c9ec41bfa6ab0a637eff19c
commit-date: 2026-01-11
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_items` is incomplete and may not be safe to use and/or cause compiler crashes
 --> code.rs:2:5
  |
2 |     generic_const_items,
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #113521 <https://github.com/rust-lang/rust/issues/113521> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> code.rs:3:5
  |
3 |     min_generic_const_args,
  |     ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information

warning: the feature `generic_const_parameter_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> code.rs:4:5
  |
4 |     generic_const_parameter_types,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #137626 <https://github.com/rust-lang/rust/issues/137626> for more information

warning: the feature `unsized_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> code.rs:5:5
  |
5 |     unsized_const_params
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #95174 <https://github.com/rust-lang/rust/issues/95174> for more information

warning: struct `Foo` is never constructed
 --> code.rs:8:8
  |
8 | struct Foo<T> {
  |        ^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

warning: constant `WRAP` is never used
  --> code.rs:12:7
   |
12 | const WRAP<T : ConstParamTy_> : T = {
   |       ^^^^

warning: 6 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: ty::ConstKind::Error constructed but no error reported
  |
  = note: delayed at /rustc-dev/b68e16cfc0e9f8b29c9ec41bfa6ab0a637eff19c/compiler/rustc_mir_build/src/thir/constant.rs:90:21
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
             4: <rustc_middle::ty::consts::Const>::new_misc_error
             5: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::lit_to_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
             6: <rustc_query_impl::query_impl::lit_to_const::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::mir::interpret::LitToConstInput)>>::call_once
             7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::mir::interpret::LitToConstInput, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
             8: rustc_query_impl::query_impl::lit_to_const::get_query_non_incr::__rust_end_short_backtrace
             9: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
            10: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
            11: rustc_hir_analysis::collect::const_of_item
            12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::const_of_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            14: rustc_query_impl::query_impl::const_of_item::get_query_non_incr::__rust_end_short_backtrace
            15: rustc_hir_analysis::check::wfcheck::check_type_const
            16: rustc_hir_analysis::check::check::check_item_type
            17: rustc_hir_analysis::check::wfcheck::check_well_formed
            18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            20: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
            21: rustc_hir_analysis::check::wfcheck::check_type_wf
            22: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            23: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            24: rustc_query_impl::query_impl::check_type_wf::get_query_non_incr::__rust_end_short_backtrace
            25: rustc_hir_analysis::check_crate
            26: rustc_interface::passes::analysis
            27: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
            28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            29: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
            30: <rustc_interface::passes::create_and_enter_global_ctxt<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core::ops::function::FnOnce<(&rustc_session::session::Session, rustc_middle::ty::context::CurrentGcx, alloc::sync::Arc<rustc_data_structures::jobserver::Proxy>, &std::sync::once_lock::OnceLock<rustc_middle::ty::context::GlobalCtxt>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_middle::arena::Arena>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_hir::Arena>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
            31: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
            32: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
            33: <std::thread::lifecycle::spawn_unchecked<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            34: <std::sys::thread::unix::Thread>::new::thread_start
            35: <unknown>
            36: <unknown>


error: internal compiler error: failed to report fulfillment errors
  |
  = note: delayed at /rustc-dev/b68e16cfc0e9f8b29c9ec41bfa6ab0a637eff19c/compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:286:47
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             3: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             4: <rustc_trait_selection::error_reporting::TypeErrCtxt>::report_fulfillment_errors
             5: rustc_hir_analysis::check::check::check_item_type
             6: rustc_hir_analysis::check::wfcheck::check_well_formed
             7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
             8: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 1]>, rustc_query_system::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
             9: rustc_query_impl::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
            10: rustc_hir_analysis::check::wfcheck::check_type_wf
            11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            13: rustc_query_impl::query_impl::check_type_wf::get_query_non_incr::__rust_end_short_backtrace
            14: rustc_hir_analysis::check_crate
            15: rustc_interface::passes::analysis
            16: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
            17: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            18: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
            19: <rustc_interface::passes::create_and_enter_global_ctxt<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core::ops::function::FnOnce<(&rustc_session::session::Session, rustc_middle::ty::context::CurrentGcx, alloc::sync::Arc<rustc_data_structures::jobserver::Proxy>, &std::sync::once_lock::OnceLock<rustc_middle::ty::context::GlobalCtxt>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_middle::arena::Arena>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_hir::Arena>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
            20: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
            21: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
            22: <std::thread::lifecycle::spawn_unchecked<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            23: <std::sys::thread::unix::Thread>::new::thread_start
            24: <unknown>
            25: <unknown>


note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/matthias/vcs/github/CRED/rustc-ice-2026-01-11T23_33_03-360561.txt` to your bug report

note: rustc 1.94.0-nightly (b68e16cfc 2026-01-11) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #151625: [ICE]: `ty::ConstKind::Error constructed but no error reported`
### Code

```Rust
#![feature(min_generic_const_args, adt_const_params, unsized_const_params)]

fn foo<const X: (bool, i32)>() {
}

fn main() {
    foo::<{(1, 2)}>();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.95.0-nightly (d222ddc4d 2026-01-23)
binary: rustc
commit-hash: d222ddc4d90743dfc1e53b610be8fc9d95893d2c
commit-date: 2026-01-23
host: x86_64-pc-windows-msvc
release: 1.95.0-nightly
LLVM version: 21.1.8
```

### Error output

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> .\src\main.rs:1:12
  |
1 | #![feature(min_generic_const_args, adt_const_params, unsized_const_params)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `unsized_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> .\src\main.rs:1:54
  |
1 | #![feature(min_generic_const_args, adt_const_params, unsized_const_params)]
  |                                                      ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #95174 <https://github.com/rust-lang/rust/issues/95174> for more information

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: ty::ConstKind::Error constructed but no error reported
  |
  = note: delayed at /rustc-dev/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/compiler\rustc_mir_build\src\thir\constant.rs:90:21
             0: std::backtrace_rs::backtrace::win64::trace
                       at /rustc/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
             1: std::backtrace_rs::backtrace::trace_unsynchronized
                       at /rustc/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
             2: std::backtrace::Backtrace::create
                       at /rustc/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/library\std\src\backtrace.rs:331
             3: std::backtrace::Backtrace::capture
                       at /rustc/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/library\std\src\backtrace.rs:296
             4: <rustc_errors::DiagCtxtHandle>::has_errors_excluding_lint_errors
             5: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             6: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             7: <rustc_serialize::opaque::mem_encoder::MemEncoder>::panic_invalid_write::<5>
             8: <rustc_middle::ty::consts::Const>::new_misc_error
             9: <rustc_lint::builtin::SpecialModuleName as rustc_lint::passes::EarlyLintPass>::check_crate
            10: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
            11: RINvNtNtCs34QVAf2vBYO_18rustc_query_system5query8plumbing17try_execute_queryINtCsbiVmqBw8rRZ_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheNtNtNtCshTwDMUac5Aa_12rustc_middle3mir9interpret15LitToConstInputINtNtNtB2z_5query5erase6ErasedAhj8_E
            12: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
            13: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
            14: <dyn rustc_hir_analysis::hir_ty_lowering::HirTyLowerer>::lower_const_arg
            15: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path::CtorGenericArgsCtxt as rustc_hir_analysis::hir_ty_lowering::GenericArgsLowerer>::provided_kind
            16: rustc_hir_typeck::typeck
            17: rustc_hir_typeck::typeck
            18: rustc_hir_typeck::typeck
            19: rustc_hir_typeck::typeck
            20: rustc_hir_typeck::typeck
            21: rustc_hir_typeck::typeck
            22: rustc_hir_typeck::typeck
            23: rustc_hir_typeck::intrinsicck::check_transmutes
            24: <hashbrown::raw::RawTable<usize>>::reserve_rehash::<indexmap::inner::get_hash<(rustc_middle::ty::predicate::Predicate, rustc_middle::traits::ObligationCause), ()>::{closure#0}>
            25: rustc_hir_typeck::typeck
            26: RINvMs6_NtCsbbqP6BDAd6w_9hashbrown3rawINtB6_8RawTableTTNtNtNtCshTwDMUac5Aa_12rustc_middle2ty8instance8InstanceNtNtNtBX_3mir4mono14CollectionModeETINtNtNtBX_5query5erase6ErasedAhj20_ENtNtNtCs34QVAf2vBYO_18rustc_query_system9dep_graph5graph12DepNodeIndexEEE1
            27: RINvNtNtCs34QVAf2vBYO_18rustc_query_system5query8plumbing17try_execute_queryINtCsbiVmqBw8rRZ_16rustc_query_impl13DynamicConfigINtNtCsiQLuZhbz1Vm_21rustc_data_structures9vec_cache8VecCacheNtNtCseevRozILHse_10rustc_span6def_id10LocalDefIdINtNtNtCshTwDMUac5Aa
            28: rustc_query_impl::plumbing::query_key_hash_verify_all
            29: rustc_hir_analysis::check_crate
            30: rustc_interface::passes::analysis
            31: <rustc_lint::builtin::SpecialModuleName as rustc_lint::passes::EarlyLintPass>::check_crate
            32: RINvNtNtCs34QVAf2vBYO_18rustc_query_system5query8plumbing17try_execute_queryINtCsbiVmqBw8rRZ_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCshTwDMUac5Aa_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
            33: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
            34: std::sys::backtrace::__rust_begin_short_backtrace::<std::thread::lifecycle::spawn_unchecked<ctrlc::set_handler_inner<rustc_driver_impl::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
            35: RINvNtNtCseh1I7LLxQdL_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCsjlLTVv95Pas_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCs8VUKmtCNrP1_17rustc_driver_i
            36: std::sys::backtrace::__rust_begin_short_backtrace::<std::thread::lifecycle::spawn_unchecked<ctrlc::set_handler_inner<rustc_driver_impl::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
            37: std::sys::thread::windows::impl$0::new::thread_start
                       at /rustc/d222ddc4d90743dfc1e53b610be8fc9d95893d2c/library\std\src\sys\thread\windows.rs:58
            38: BaseThreadInitThunk
            39: RtlUserThreadStart


note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `~\zed\ps\rustc-ice-2026-01-25T01_49_27-14540.txt` to your bug report

note: rustc 1.95.0-nightly (d222ddc4d 2026-01-23) running on x86_64-pc-windows-msvc

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by reddevilmidzy**
close: rust-lang/rust#151625 
close: rust-lang/rust#150983

also fix: https://github.com/rust-lang/rust/issues/133966 (moved crashes test)

### CODE REVIEW

File: tests/ui/const-generics/mgca/literal-type-mismatch.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+use std::marker::ConstParamTy_;
+
+struct Foo<T> {
+    field: T,
+}
+
+#[type_const]
+const WRAP<T : ConstParamTy_> : T = { //~ ERROR: generic const items are experimental
+    Foo::<T>{field : 1} //~ ERROR: expected `T`, found {integer}
+};
```
Comment (reddevilmidzy) [inline tests/ui/const-generics/mgca/literal-type-mismatch.rs]: When I removed `generic_const_parameter_types` and added `generic_const_items`, ICE did not reproduce.

Comment (reddevilmidzy) [reply tests/ui/const-generics/mgca/literal-type-mismatch.rs]: Ah, I tried adding both in one file, but when I place them together, the ICE doesn't work. haha, 
I'll fix it.

https://godbolt.org/z/1xEjGYTvo

Comment (reddevilmidzy) [reply tests/ui/const-generics/mgca/literal-type-mismatch.rs]: Oh, I was mistaken. The reason ICE didn't occur wasn't because I merged the two, but because I didn't add `adt_const_params`.

Still, I think it's better to separate the two, so I'll do that.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -2807,10 +2807,70 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        if !self.const_lit_matches_ty(kind, ty, false) {
+            let found = self.const_lit_description(kind);
+            let e = tcx.dcx().span_err(span, format!("expected `{}`, found `{found}`", ty));
+            return ty::Const::new_error(tcx, e);
+        }
         let input = LitToConstInput { lit: *kind, ty, neg: false };
         tcx.at(span).lit_to_const(input)
     }
 
+    fn const_lit_matches_ty(&self, kind: &LitKind, ty: Ty<'tcx>, neg: bool) -> bool {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I think in most cases we actually don't want to emit errors during HIR ty lowering for type mismatches here. E.g. if we have a `true` literal it doesn't really matter if the expected type is `u32`, we can still lower to a `0x1` valtree of type `bool` and then get a type checking error later.

Separately from this, we already do these checks in `fn lit_to_const` (just ICEing if they don't hold instead of a proper error) so it probably doesn't make sense to duplicate them here too 🤔

I think it would make sense for `lit_to_const` to return an `Option<ty::Value<'tcx>>` and stop ICEing/erroring altogether.

You could then:
- Move `const_lit_matches_ty` to THIR building for patterns (the only place other than const-generics that calls `lit_to_const`) and create a `ty::ConstKind::Error` if it's `false` (or if `lit_to_const` returns `None`)
- Here in HIR ty lowering we can emit a proper error about needing more type information for the literal if `lit_to_const` returns `None`. And we can entirely ignore the possibility of type mismatches because type checking should take care of that for us

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 3]
```diff
@@ -2832,7 +2841,11 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             // Allow the `ty` to be an alias type, though we cannot handle it here, we just go through
             // the more expensive anon const code path.
             .filter(|l| !l.ty.has_aliases())
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]:
```suggestion
```
this should be unnecessary now

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 4]
```diff
@@ -68,27 +66,25 @@ pub(crate) fn lit_to_const<'tcx>(
...
         }
         (ast::LitKind::Bool(b), ty::Bool) => ty::ValTree::from_scalar_int(tcx, b.into()),
         (ast::LitKind::Float(n, _), ty::Float(fty)) => {
-            let bits = parse_float_into_scalar(n, *fty, neg).unwrap_or_else(|| {
-                tcx.dcx().bug(format!("couldn't parse float literal: {:?}", lit_input.lit))
-            });
+            let bits = parse_float_into_scalar(n, *fty, neg)?;
             ty::ValTree::from_scalar_int(tcx, bits)
         }
         (ast::LitKind::Char(c), ty::Char) => ty::ValTree::from_scalar_int(tcx, c.into()),
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs]: can you change most of the type patterns to be `_`
```suggestion
        (ast::LitKind::Char(c), _) => ty::ValTree::from_scalar_int(tcx, c.into()),
```

I think we should produce a valtree regardless of the expected type if we can. i think the only arms that actually need to know the expected type would be unsuffixed integer literals. ah I guess byte strings also care

each arm should also return a `Ty` for what the type of the valtree is. I think we should rename the `ty` local to `expected_ty` or something to make it clear it could be different from the type of the valtree once you change this

**Comment by reddevilmidzy** [comment]
Haha, ICE occurs in other tests...

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 5]
```diff
@@ -745,6 +745,15 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
                             }
+                            if preceding_args.is_empty()
+                                && tcx.type_of(param.def_id).skip_binder().has_param()
+                            {
+                                let guar = self.lowerer.dcx().span_delayed_bug(
+                                    self.span,
+                                    "default type has params but no args",
+                                );
+                                return Ty::new_error(tcx, guar).into();
+                            }
```
Comment (reddevilmidzy) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: Added logic to avoid ICE in https://github.com/rust-lang/rust/blob/main/tests/ui/const-generics/generic_const_exprs/lit_type_mismatch.rs

The change in `compiler/rustc_trait_selection/src/traits/wf.rs` is for the same reason.


```rust

#![feature(adt_const_params)]
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

struct A<const B: () = 1, C>(C);
//~^ ERROR: generic parameters with a default must be trailing
//~| ERROR: mismatched types

struct Cond<const B: bool>;

struct Thing<T = Cond<0>>(T);
//~^ ERROR: mismatched types

impl Thing {}

fn main() {}
```

File: tests/ui/const-generics/mgca/type_const-mismatched-types.rs [hunk 6]
```diff
@@ -7,7 +7,6 @@ const FREE: u32 = 5_usize;
 
 #[type_const]
 const FREE2: isize = FREE;
-//~^ ERROR the constant `5` is not of type `isize`
```
Comment (reddevilmidzy) [inline tests/ui/const-generics/mgca/type_const-mismatched-types.rs]: I'm not sure if this error will go away.

**Review by reddevilmidzy — COMMENTED** [review]
Thanks for your quick review. 😊

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152001/8c5605e130081cbff57f505c56466538039346b1..ca77eab0c9f16cc201cceb4c770b0b46e90ee14a)*

File: tests/ui/const-generics/generic_const_exprs/enum-const-generic-default-param.rs [hunk 7]
```diff
@@ -0,0 +1,23 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/116554>
```
Comment (reddevilmidzy) [inline tests/ui/const-generics/generic_const_exprs/enum-const-generic-default-param.rs]: This issue was closed; is there a need to add further testing?

File: tests/crashes/101036.rs [hunk 8]
```diff
@@ -1,14 +0,0 @@
-//@ known-bug: #101036
-#![feature(generic_const_exprs)]
-
```
Comment (reddevilmidzy) [inline tests/crashes/101036.rs:3]: ~~#101036 was a duplicate of #119824.~~

edit: This test is no longer associated with this PR.

**Review by reddevilmidzy — COMMENTED** [review]
In ten crash tests, the ICE disappeared; however, in [‎`tests/crashes/117460.rs`](https://github.com/reddevilmidzy/rust/blob/75e7e183df5ee3a5a62230229b25aafc14170779/tests/crashes/117460.rs), [`tests/crashes/114212-2.rs`](https://github.com/reddevilmidzy/rust/blob/75e7e183df5ee3a5a62230229b25aafc14170779/tests/crashes/114212-2.rs) and [`tests/crashes/114212.rs`](https://github.com/reddevilmidzy/rust/blob/75e7e183df5ee3a5a62230229b25aafc14170779/tests/crashes/114212.rs),  adding the main function caused the ICE to occur again.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152001/8c5605e130081cbff57f505c56466538039346b1..75e7e183df5ee3a5a62230229b25aafc14170779)*

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 9]
```diff
@@ -2828,11 +2856,15 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
         };
 
-        lit_input
-            // Allow the `ty` to be an alias type, though we cannot handle it here, we just go through
-            // the more expensive anon const code path.
-            .filter(|l| !l.ty.has_aliases())
-            .map(|l| tcx.at(expr.span).lit_to_const(l))
+        lit_input.and_then(|l| {
+            tcx.at(expr.span).lit_to_const(l).and_then(|value| {
+                if value.ty == ty {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I think it should be okay to do `ty::Const::new_value` unconditionally, and if not it'd be good to know why and add a comment :3

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 10]
```diff
@@ -29,66 +28,76 @@ pub(crate) fn lit_to_const<'tcx>(
...
     };
 
-    let valtree = match (lit, ty.kind()) {
-        (ast::LitKind::Str(s, _), ty::Ref(_, inner_ty, _)) if inner_ty.is_str() => {
+    let (valtree, valtree_ty) = match (lit, expected_ty.kind()) {
+        (ast::LitKind::Str(s, _), _) => {
             let str_bytes = s.as_str().as_bytes();
-            ty::ValTree::from_raw_bytes(tcx, str_bytes)
-        }
-        (ast::LitKind::Str(s, _), ty::Str) if tcx.features().deref_patterns() => {
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs:40]: you've deleted the logic here for string literals being of type `str` under `deref_patterns`. I don't know why there's no test that cares about this though 🤔

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 11]
```diff
@@ -29,66 +28,76 @@ pub(crate) fn lit_to_const<'tcx>(
...
+                ty::ValTree::from_branches(tcx, [ty::Const::new_value(tcx, bytes, cstr_ty)]);
+            let valtree_ty = Ty::new_imm_ref(tcx, tcx.lifetimes.re_static, cstr_ty);
+            (valtree, valtree_ty)
+        }
+        (ast::LitKind::Int(n, ast::LitIntType::Unsigned(ui)), _) if !neg => {
+            let scalar_int = trunc(n.get(), ui)?;
+            (ty::ValTree::from_scalar_int(tcx, scalar_int), Ty::new_uint(tcx, ui))
+        }
+        (ast::LitKind::Int(_, ast::LitIntType::Unsigned(_)), _) if neg => return None,
+        (ast::LitKind::Int(n, ast::LitIntType::Signed(i)), _) => {
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs:77]: you can merge the branches for unsuffixed with type hint, and suffixed with OR patterns:

```suggestion
        (ast::LitKind::Int(n, ast::LitIntoType::Unsuffixed), ty::Int(i))
        | (ast::LitKind::Int(n, ast::LitIntType::Signed(i)), _) => {
```
can do the same for handling of unsuffixed vs unsigned too

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 12]
```diff
@@ -29,66 +28,76 @@ pub(crate) fn lit_to_const<'tcx>(
...
             // which gets the result we want without additional casts.
             let scalar_int =
-                trunc(if neg { u128::wrapping_neg(n.get()) } else { n.get() }, i.to_unsigned());
-            ty::ValTree::from_scalar_int(tcx, scalar_int)
+                trunc(if neg { u128::wrapping_neg(n.get()) } else { n.get() }, i.to_unsigned())?;
+            (ty::ValTree::from_scalar_int(tcx, scalar_int), Ty::new_int(tcx, *i))
         }
-        (ast::LitKind::Bool(b), ty::Bool) => ty::ValTree::from_scalar_int(tcx, b.into()),
+        (ast::LitKind::Bool(b), _) => (ty::ValTree::from_scalar_int(tcx, b.into()), tcx.types.bool),
         (ast::LitKind::Float(n, _), ty::Float(fty)) => {
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs]: there's no handling of suffixed floats here, should handle `1.0_f32` similar to how you do suffixed vs unsuffixed integer literals

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 13]
```diff
@@ -1006,8 +1006,20 @@ impl<'a, 'tcx> TypeVisitor<TyCtxt<'tcx>> for WfPredicates<'a, 'tcx> {
                         self.add_wf_preds_for_inherent_projection(uv.into());
                         return; // Subtree is handled by above function
                     } else {
-                        let obligations = self.nominal_obligations(uv.def, uv.args);
-                        self.out.extend(obligations);
+                        if uv.args.is_empty()
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/wf.rs]: you can undo this change, it makes the code worse and it's not important to avoid regressing GCE

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I would revert this. This is almost certainly masking a GCE-only bug rather than fixing anything in GCE. It's not important to avoid regressing GCE so even if not doing this makes less things compile in GCE thats ok

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 14]
```diff
@@ -2798,8 +2807,27 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
     ) -> Const<'tcx> {
         let tcx = self.tcx();
+        if let LitKind::Err(guar) = *kind {
+            return ty::Const::new_error(tcx, guar);
+        }
         let input = LitToConstInput { lit: *kind, ty, neg };
-        tcx.at(span).lit_to_const(input)
+        match tcx.at(span).lit_to_const(input) {
+            Some(value) => {
+                if value.ty == ty {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I don't think you need this check either. Later parts of the compiler (namely, wf checks) will handle checking the type of the value is correct for the parameter its an argument to. You should be able to always do `ty::Const::new_value` if it returns `Some`

File: tests/ui/const-generics/generic_const_exprs/enum-const-generic-default-param.rs (hunk 7 above)
Comment (BoxyUwU) [reply tests/ui/const-generics/generic_const_exprs/enum-const-generic-default-param.rs]: unsure, I will look over all the GCE tests (outside of this PR) at some point soon and see which ones are worth keeping

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 14 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: or in other words, we already validate literals' types in the compiler elsewhere, this PR is actually about *not* validating the type during HIR ty lowering

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs [hunk 15]
```diff
@@ -696,9 +695,61 @@ impl<'tcx> PatCtxt<'tcx> {
...
+                            self.tcx,
+                            expr.span,
+                            "literal does not match expected type",
+                        )
+                    }
+                };
+                let constant = if self.const_lit_matches_ty(&lit.node, pat_ty, *negated) {
+                    match self.tcx.at(expr.span).lit_to_const(lit_input) {
+                        Some(value) => {
+                            let const_ty = if value.ty == pat_ty { value.ty } else { pat_ty };
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/pattern/mod.rs]: this logic is equivalent to just using `pat_ty`. either they're equal in which case `value.ty` is just `pat_ty`, or they're not, and we're using `pat_ty`. we already check `const_lit_matches_ty` above so we shouldn't need to do any kind of checks here anyway

File: compiler/rustc_mir_build/src/thir/constant.rs [hunk 16]
```diff
@@ -29,66 +28,76 @@ pub(crate) fn lit_to_const<'tcx>(
         trace!("trunc result: {}", result);
 
         ScalarInt::try_from_uint(result, width)
-            .unwrap_or_else(|| bug!("expected to create ScalarInt from uint {:?}", result))
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/constant.rs:32]: does keeping this ICEing cause any problems? I would expect this to be ok to not remove

Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/constant.rs:32]: Ah, there wasn't really any problem. I put it back again.

File: compiler/rustc_mir_build/src/thir/constant.rs (hunk 10 above)
Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/constant.rs:40]: The existing `(ast::LitKind::Str(s, _), ty::Ref(_, inner_ty, _)) if inner_ty.is_str()` and `(ast::LitKind::Str(s, _), ty::Str) if tcx.features().deref_patterns()` had identical processing logic, so I've enabled both patterns to be handled as `(ast::LitKind::Str(s, _), _)` !

File: compiler/rustc_trait_selection/src/traits/wf.rs (hunk 13 above)
Comment (reddevilmidzy) [reply compiler/rustc_trait_selection/src/traits/wf.rs]: yes, I've reverted it

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs (hunk 15 above)
Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/pattern/mod.rs]: Oh, great! I just changed it to use `pat_ty`.

File: compiler/rustc_mir_build/src/thir/constant.rs (hunk 12 above)
Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/constant.rs]: fixed: https://github.com/rust-lang/rust/pull/152001/changes/c34021c00fe0e27bc84324d0b363901811a96a2b

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 9 above)
Comment (reddevilmidzy) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: This seems like leftover code from an experiment 😅
Removed branch

File: compiler/rustc_mir_build/src/thir/constant.rs (hunk 11 above)
Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/constant.rs:77]: I tried the code you suggested, but it failed to compile because each type was different. 😢

I'll see if I can handle this with a more fancy pattern.

**Comment by reddevilmidzy** [comment]
In my current code, an ICE will occur in the `tests/ui/const-generics/generic_const_exprs/lit_type_mismatch.rs` test.

Looking at the stacktrace and log, it appears that after returning `None` due to a type mismatch, the path continues without stopping at `hir_ty_lowering`, which then instantiates the default value. This causes an ICE error as instantiate is called with an empty preceding_args.

How would you recommend handling this situation?

**Comment by reddevilmidzy** [comment]
> cool! sorry for a lot of comments but this is looking really good :)

No worries at all — I really appreciate the detailed feedback. Thanks for taking the time to review (_ _)

File: compiler/rustc_mir_build/src/thir/constant.rs (hunk 10 above)
Comment (BoxyUwU) [reply compiler/rustc_mir_build/src/thir/constant.rs:40]: Hmm yeah you're right about the actual ValTree structure :thinking:  I think there *is* a behaviour difference now though. Previously if there was an expected type of `str` the valtree's type would be `str` whereas now its always `&str`.

If that doesn't actually affect anything in practice then I guess we should just... always have the `&str` type and then maybe one day when it breaks something we can get a test

File: compiler/rustc_mir_build/src/thir/constant.rs (hunk 11 above)
Comment (BoxyUwU) [reply compiler/rustc_mir_build/src/thir/constant.rs:77]: ah if that pattern doesn't "just work" then it seems fine to keep it as is :)

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 17]
```diff
@@ -2833,11 +2842,11 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
         };
 
-        lit_input
-            // Allow the `ty` to be an alias type, though we cannot handle it here, we just go through
-            // the more expensive anon const code path.
-            .filter(|l| !l.ty.has_aliases())
-            .map(|l| tcx.at(expr.span).lit_to_const(l))
+        lit_input.and_then(|l| {
+            tcx.at(expr.span)
+                .lit_to_const(l)
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: so we now get a bunch of extra errors I think because this succeeds in more cases and results in duplication between the type checking errors of the anon const this was derived from, and type checking errors for the const arg matching the thing its a parameter to.

I think it would probably make sense (for diagnostics reasons) to do like `.filter(|| const_lit_matches_ty())` so that we only do this fast path if the types are ok 🤔

Comment (reddevilmidzy) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: Oh, that was the problem!! Added filtering

Comment (reddevilmidzy) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: and `const_lit_matches_ty()` is used in two places: `compiler/rustc_mir_build/src/thir/pattern/mod.rs` and `compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs`. I was going to create a function for each, but I ended up creating a function in `compiler/rustc_middle/src/mir/interpret/mod.rs`.

EDIT: it's in `rustc_middle/src/ty/consts/lit.rs`

File: tests/ui/const-generics/generic_const_exprs/lit_type_mismatch.rs
Comment (reddevilmidzy) [inline tests/ui/const-generics/generic_const_exprs/lit_type_mismatch.rs:1]: Removed tests related to `generic_const_args` that were causing crashes.

File: tests/ui/const-generics/mgca/nonsensical-negated-literal.rs [hunk 18]
```diff
@@ -0,0 +1,26 @@
...
+    foo::<{ Foo { field: { -1_usize } } }>();
+    //~^ ERROR: complex const arguments must be placed inside of a `const` block
+    foo::<{ Foo { field: -true } }>();
+    //~^ ERROR: the constant `true` is not of type `isize`
+    foo::<{ Foo { field: { -true } } }>();
+    //~^ ERROR: complex const arguments must be placed inside of a `const` block
+    foo::<{ Foo { field: -"<3" } }>();
+    //~^ ERROR: the constant `"<3"` is not of type `isize`
+    foo::<{ Foo { field: { -"<3" } } }>();
+    //~^ ERROR: complex const arguments must be placed inside of a `const` block
```
Comment (reddevilmidzy) [inline tests/ui/const-generics/mgca/nonsensical-negated-literal.rs:25]: Added the test mentioned in #152139.

File: compiler/rustc_middle/src/mir/interpret/mod.rs [hunk 19]
```diff
@@ -84,6 +84,44 @@ pub struct LitToConstInput<'tcx> {
     pub neg: bool,
 }
 
+pub fn const_lit_matches_ty<'tcx>(
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/mod.rs]: This does not seem like a great place for this function -- it doesn't really have anything to do with the interpreter, does it?

I guess you put it next to `LitToConstInput`, but that type also doesn't belong here either IMO. It has very little to do with everything else in this module.

Comment (reddevilmidzy) [reply compiler/rustc_middle/src/mir/interpret/mod.rs]: Oh, yes, I placed it here to place it in the same place as `LitToConstInput`.
I'll look for something more meaningful! LitToConstInput too.

Comment (reddevilmidzy) [reply compiler/rustc_middle/src/mir/interpret/mod.rs]: I created `rustc_middle/src/ty/consts/lit.rs` and moved it there. Does it look okay?

https://github.com/rust-lang/rust/pull/152001/commits/4f93ae73e7bfdeab03e51ea543104a0c68919fc7

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs [hunk 20]
```diff
@@ -696,7 +696,25 @@ impl<'tcx> PatCtxt<'tcx> {
...
+                    if let Some(guar) = self.typeck_results.tainted_by_errors {
+                        ty::Const::new_error(self.tcx, guar)
+                    } else {
+                        ty::Const::new_error_with_message(
+                            self.tcx,
+                            expr.span,
+                            "literal does not match expected type",
+                        )
+                    }
+                };
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/pattern/mod.rs]:
```suggestion
                    ty::Const::new_error_with_message(
                        self.tcx,
                        expr.span,
                        "literal does not match expected type",
                    )
                };
```
i would simplify this as its currently taking up a lot of space for a path that should never actually be hit

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs [hunk 21]
```diff
@@ -696,7 +696,25 @@ impl<'tcx> PatCtxt<'tcx> {
...
+                let constant = if const_lit_matches_ty(self.tcx, &lit.node, pat_ty, *negated) {
+                    match self.tcx.at(expr.span).lit_to_const(lit_input) {
+                        Some(value) => ty::Const::new_value(self.tcx, value.valtree, pat_ty),
+                        None => error_const(),
+                    }
+                } else {
+                    error_const()
+                };
```
Comment (BoxyUwU) [inline compiler/rustc_mir_build/src/thir/pattern/mod.rs]: does something like this work?
```suggestion
                let constant = 
                    const_lit_matches_ty(self.tcx, &lit.node, pat_ty, *negated)
                        .then(|| self.tcx.at(expr.span).lit_to_const(lit_input))
                        .map(|v| ty::Const::new_value(self.tcx, value.valtree, pat_ty)
                        .unwrap_or_else(|| error_const());
```

File: compiler/rustc_middle/src/mir/interpret/mod.rs (hunk 19 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/interpret/mod.rs]: that seems ok to me, we might wind up getting more logic for this as mGCA progresses so seems nice to have a module :thinking:

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs (hunk 21 above)
Comment (reddevilmidzy) [reply compiler/rustc_mir_build/src/thir/pattern/mod.rs]: cool!!
I removed `error_const()` and changed it to feel more like functional programming😄

```rust
let constant = const_lit_matches_ty(self.tcx, &lit.node, pat_ty, *negated)
    .then(|| self.tcx.at(expr.span).lit_to_const(lit_input))
    .flatten()
    .map(|v| ty::Const::new_value(self.tcx, v.valtree, pat_ty))
    .unwrap_or_else(|| {
        ty::Const::new_error_with_message(
        self.tcx,
        expr.span,
        "literal does not match expected type",
        )
    });
self.const_to_pat(constant, pat_ty, expr.hir_id, lit.span)
```

File: tests/ui/const-generics/mgca/nonsensical-negated-literal.rs [hunk 22]
```diff
@@ -0,0 +1,26 @@
...
+    field: isize
+}
+
+fn foo<const F: Foo>() {}
+
+fn main() {
+    foo::<{ Foo { field: -1_usize } }>();
+    //~^ ERROR: type annotations needed for the literal
+    foo::<{ Foo { field: { -1_usize } } }>();
+    //~^ ERROR: complex const arguments must be placed inside of a `const` block
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/nonsensical-negated-literal.rs:17]: This error message implies we handle negated literals incorrectly during ast lowering I think. `lower_expr_to_const_arg_direct` is presumably not handling `{ -1_usize }` even though it should (I think probably there is no reason for the arm for blocks to match on what kind of expr is being wrapped).

If you'd be interested, once this PR lands would you be interested in fixing that and #152246 in a followup PR?

Comment (BoxyUwU) [reply tests/ui/const-generics/mgca/nonsensical-negated-literal.rs:17]: I think we probably also handle `fn foo<const F: &str>() { foo::<{ -"hi" }>(); }` wrong (i.e. we accept it?). I think this is also a problem with ast lowering and we should be checking there that the literal is an integer. Could also do that in a followup PR if you like?

File: compiler/rustc_mir_build/src/thir/pattern/mod.rs (hunk 21 above)
Comment (BoxyUwU) [reply compiler/rustc_mir_build/src/thir/pattern/mod.rs]: awesome!

File: tests/ui/const-generics/mgca/nonsensical-negated-literal.rs (hunk 22 above)
Comment (reddevilmidzy) [reply tests/ui/const-generics/mgca/nonsensical-negated-literal.rs:17]: Yes, I'd be happy to work on that in a follow-up PR! I'll take a closer look at the AST lowering behavior you mentioned.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 23]
```diff
@@ -2809,8 +2802,17 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
         let tcx = self.tcx();
+        if let LitKind::Err(guar) = *kind {
+            return ty::Const::new_error(tcx, guar);
+        }
         let input = LitToConstInput { lit: *kind, ty, neg };
-        tcx.at(span).lit_to_const(input)
+        match tcx.at(span).lit_to_const(input) {
+            Some(value) => ty::Const::new_value(tcx, value.valtree, value.ty),
+            None => {
+                let e = tcx.dcx().span_err(span, "type annotations needed for the literal");
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2812]: This is the cause of the ICEs you're seeing I think. You need to do `self.dcx()` to make sure that the lowering context gets tainted

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152001/f403dee04e6a801fe0f49a9c351fcd2ae8edd37c..01d48c62a5e6219f2893ac8eed40cf8ae38a7282)*
