### PR TITLE
fix: clarify suggestion that `&T` must refer to `T: Sync` for `&T: Send`

### LINKED ISSUE #86507: suggestion that &T requires Sync to be Send could be clearer
Given the following code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b682c04656c59d9231718cee5c529f66)

```rust
use async_trait::async_trait; // 0.1.50
use serde::Serialize;

#[async_trait]
trait Foo {
    async fn bar(x: &(impl Serialize + Send));
}

#[async_trait]
impl Foo for () {
    async fn bar(x: &(impl Serialize + Send)) {
    }
}

fn main() { }
```

The current output is:

```
error: future cannot be sent between threads safely
  --> src/main.rs:11:47
   |
11 |       async fn bar(x: &(impl Serialize + Send)) {
   |  _______________________________________________^
12 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send`
  --> src/main.rs:11:18
   |
11 |     async fn bar(x: &(impl Serialize + Send)) {
   |                  ^ has type `&impl Serialize + Send` which is not `Send`
   = note: required for the cast to the object type `dyn Future<Output = ()> + Send`
help: consider further restricting this bound
   |
11 |     async fn bar(x: &(impl Serialize + Send + std::marker::Sync)) {
   |                                             ^^^^^^^^^^^^^^^^^^^
```

The compiler helpfully points out that `Sync` is required, but nonetheless @chazkiker2 and I both got confused by this error for some time before we noticed it. The suggestion was kind of buried by all the other details.

### PR DESCRIPTION
**Pull request by chazkiker2**
### Description

- [x] fix #86507 
- [x] add UI test for relevant code from issue
- [x] change `rustc_trait_selection/src/traits/error_reporting/suggestions.rs` to include a more clear suggestion when `&T` fails to satisfy `Send` bounds due to the fact that `T` fails to implement `Sync`
- [x] update UI test in Clippy: `src/tools/tests/ui/future_not_send.stderr`

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -1858,11 +1862,23 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
                 let mut span = MultiSpan::from_span(upvar_span);
-                span.push_span_label(
-                    upvar_span,
-                    format!("has type `{}` which {}", target_ty, trait_explanation),
-                );
+                match target_ty.kind() {
+                    ty::Ref(_, ref_ty, _) => {
+                        span.push_span_label(
+                            upvar_span,
+                            // TODO: we need the equivalent of `trait_explanation` for the `ref_ty`
```
Comment (chazkiker2) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1869]: need to figure out how to get the equivalent of `trait_explanation` for the `ref_ty` -- i.e., the type of the reference. 

When `target_ty` is of type `&T` and `T: Sync` is not satisfied, we need to be able to say 

`refers to type 'T' which 'is not Sync'`

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -1857,12 +1857,40 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                let refers_to_non_sync = match target_ty.kind() {
+                    ty::Ref(_, ref_ty, _) => match self.evaluate_obligation(&obligation) {
+                        Ok(eval) => {
+                            if eval.may_apply() {
+                                None
+                            } else {
+                                Some(ref_ty)
+                            }
+                        }
+                        _ => None,
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1870]:
```suggestion
                        Ok(eval) if !eval.may_apply() => Some(ref_ty),
                        _ => None,
```

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -1857,12 +1857,40 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                match refers_to_non_sync {
+                    Some(ref_ty) => {
+                        span.push_span_label(
+                            upvar_span,
+                            format!(
+                                "has type `{}` -- refers to `{}` which is not `Sync`",
+                                target_ty, ref_ty
+                            ),
+                        );
+                        err.span_note(span, &format!("captured value {} because `&` references cannot be sent unless their referent is `Sync`", trait_explanation));
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1884]: You'll need to run `./x.py fmt` to make this line <100 columns.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -1857,12 +1857,40 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
-                );
-                err.span_note(span, &format!("captured value {}", trait_explanation));
+                match refers_to_non_sync {
+                    Some(ref_ty) => {
+                        span.push_span_label(
+                            upvar_span,
+                            format!(
+                                "has type `{}` -- refers to `{}` which is not `Sync`",
+                                target_ty, ref_ty
+                            ),
```
Comment (estebank) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:1882]:
```suggestion
                            format!(
                                "has type `{}` which is not `Send`, because `{}` is not `Sync`",
                                target_ty,
                                ref_ty,
                            ),
```

**Review by estebank — COMMENTED** [review]
Left some small action items. Could you also squash your commits before we merge this?

**Comment by JohnTitor** [comment]
Failed on rollup: https://github.com/rust-lang/rust/pull/87399#issuecomment-885541731
@bors r-

Needs to update Clippy.

**Comment by chazkiker2** [comment]
need to update UI test in Clippy: https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/future_not_send.stderr

**Comment by JohnTitor** [comment]
Thanks!
@bors r=estebank
