### PR TITLE
ensure we always print all --print options in help

### LINKED ISSUE #137853: `rustc --help` does not show all available flags of `rustc --print`
`rustc --print` with an invalid name, for example, `x`, shows:

```txt
error: unknown print request: `x`
  |
  = help: valid print requests are: `all-target-specs-json`, `calling-conventions`, `cfg`, `check-cfg`, `code-models`, `crate-name`, `deployment-target`, `file-names`, `host-tuple`, `link-args`, `native-static-libs`, `relocation-models`, `split-debuginfo`, `stack-protector-strategies`, `sysroot`, `target-cpus`, `target-features`, `target-libdir`, `target-list`, `target-spec-json`, `tls-models`

```

This seems correct, but `rustc --help`'s description of `--print` is:

```txt
        --print [crate-name|file-names|sysroot|target-libdir|cfg|check-cfg|calling-conventions|target-list|target-cpus|target-features|relocation-models|code-models|tls-models|target-spec-json|all-target-specs-json|native-static-libs|stack-protector-strategies|link-args|deployment-target]
                        Compiler information to print on stdout
```

This list does **not** contain

- `host-tuple`
- `split-debuginfo`

### Maybe related

- https://github.com/rust-lang/rust/pull/125579 : This added `--print host-tuple`, but it seems not applied to `rustc --help` at this point

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (794c12416 2025-02-21)
binary: rustc
commit-hash: 794c12416b2138064af1f2746646973fafd9419d
commit-date: 2025-02-21
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### PR DESCRIPTION
**Pull request by mtoner23**
Closes #137853
Refactors the PRINT_KINDS map into a public const so we always print every option for print. the list is quite long now, and idk if long term we want to keep printing all these options from --help.

### CODE REVIEW

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -1508,6 +1534,13 @@ The default is {DEFAULT_EDITION} and the latest stable edition is {LATEST_STABLE
     )
 });
```
Comment (Noratrieb) [inline compiler/rustc_session/src/config.rs:1536]: can you make this a local variable instead?

Comment (mtoner23) [reply compiler/rustc_session/src/config.rs:1536]: Sure, just remove pub or put it in some function?

Comment (Noratrieb) [reply compiler/rustc_session/src/config.rs:1536]: Actually, when reading the code a bit, I see that this same thing is needed in the `collect_print_requests` function as well. In that case it makes sense to share it at the global scope, but I'd prefer a `fn print_kinds_string() -> String` function over a lazy lock.

File: compiler/rustc_session/src/config.rs [hunk 2]
```diff
@@ -42,6 +42,32 @@ mod cfg;
...
+    ("relocation-models", PrintKind::RelocationModels),
+    ("split-debuginfo", PrintKind::SplitDebuginfo),
+    ("stack-protector-strategies", PrintKind::StackProtectorStrategies),
+    ("sysroot", PrintKind::Sysroot),
+    ("target-cpus", PrintKind::TargetCPUs),
+    ("target-features", PrintKind::TargetFeatures),
+    ("target-libdir", PrintKind::TargetLibdir),
+    ("target-list", PrintKind::TargetList),
+    ("target-spec-json", PrintKind::TargetSpec),
+    ("tls-models", PrintKind::TlsModels),
```
Comment (Noratrieb) [inline compiler/rustc_session/src/config.rs:67]: If you want to make another PR improving `--print`, I'd suggest adding a third tuple field that indicates whether the print request is stable or not instead of the custom checks in `collect_print_requests`.

Comment (mtoner23) [reply compiler/rustc_session/src/config.rs:67]: good idea, I'll consider it. adding some more helper functions for the PrintKinds enum seem appropriate.

File: compiler/rustc_session/src/config.rs (hunk 1 above)
Comment (mtoner23) [reply compiler/rustc_session/src/config.rs:1536]: sounds good i'll make come up with a func somehwere.

Comment (mtoner23) [reply compiler/rustc_session/src/config.rs:1536]: extracting to a function makes this all worse than a lazy lock imo. the reason theres a lazy lock is because make_opt expects your format string to be static lifetime. and its possible theres some way to craft a `const fn print_kinds_str()` that uses some const things and for loops to iterate over this list but it all seems overly complicated for this simple print code.

so can we stick with lazy lock? it follows the pattern of `EDITION_STRING` already there.

**Comment by nnethercote** [comment]
LGTM

@bors r+

File: compiler/rustc_session/src/config.rs (hunk 1 above)
Comment (Noratrieb) [reply compiler/rustc_session/src/config.rs:1536]: ah, okay. it's fine then, I wasn't aware of the static lifetime requirement.
