### PR TITLE
Round generator sizes to a multiple of their alignment

### LINKED ISSUE #62658: ICE: assertion failed: `(left == right)` in type_of.rs
I just ran into this ICE:

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Size { raw: 404 }`,
 right: `Size { raw: 400 }`', src/librustc_codegen_llvm/type_of.rs:148:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (71f9384e3 2019-07-12) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/type_of.rs#L148

I can't share the code but here are some observations:

* The ICE occurs in debug mode as well.
* It does *not* occur when running `cargo check`.
* It does *not* occur on my MacBook (same nightly, different architecture).

### PR DESCRIPTION
**Pull request by tmandry**
Fixes #62658.

r? @cramertj 
cc @eddyb

### CODE REVIEW

File: src/test/ui/async-await/issue-62658.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+#![feature(async_await)]
+
+async fn noop() {}
+
+async fn foo() {
+    // This suspend should be the largest variant.
+    {
+        let x = [0u8; 17];
+        noop().await;
+        println!("{:?}", x);
```
Comment (hellow554) [inline src/test/ui/async-await/issue-62658.rs]: Instead of `println` you could use either `drop` is define a `fn dummy<T>(_: T) {}` and use that
