### PR TITLE
Don't ICE on missing `Unsize` impl

### LINKED ISSUE #71036: Compiler panics while trying to implement `DispatchFromDyn`
I was playing with `DisplatchFromDyn` while I encountered a
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1'
```

The simplest example I have producing the bug is
```rust
#![feature(unsize, dispatch_from_dyn)]

use std::marker::Unsize;
use std::ops::DispatchFromDyn;

struct Inner<'a, T: ?Sized> {
	value: &'a T
}

impl<'a, T: ?Sized + Unsize<U>, U: ?Sized> DispatchFromDyn<Inner<'a, U>> for Inner<'a, T> {}

impl<'a, T: ?Sized> Inner<'a, T> {
	fn new(value: &'a T) -> Inner<'a, T> {
		Inner {
			value
		}
	}
}

pub struct Local<'a, T: ?Sized> {
	inner: &'a Inner<'a, T>
}

impl<'a, T: ?Sized + Unsize<U>, U: ?Sized> DispatchFromDyn<Local<'a, U>> for Local<'a, T> {}

impl<'a, T: ?Sized> Local<'a, T> {
	fn new(inner: &'a Inner<'a, T>) -> Local<'a, T> {
		Local {
			inner
		}
	}
}
```
Here is [a link to the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4fa9dca4a55ee714d9ba07fb0f01607f).
It works if I remove the `Inner` struct and put the `&'a T` directly in `Local`.

The complete backtrace is
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/librustc_middle/ty/subst.rs:333:43
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  15: rustc_trait_selection::traits::select::SelectionContext::assemble_candidates
  16: rustc_trait_selection::traits::select::SelectionContext::candidate_from_obligation_no_cache
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task
  18: rustc_trait_selection::traits::select::SelectionContext::candidate_from_obligation
  19: rustc_trait_selection::traits::select::SelectionContext::evaluate_stack
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task
  21: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively
  22: rustc_infer::infer::InferCtxt::probe
  23: rustc_trait_selection::traits::select::SelectionContext::evaluate_root_obligation
  24: rustc_middle::ty::context::GlobalCtxt::enter_local
  25: rustc_traits::evaluate_obligation::evaluate_obligation
  26: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::evaluate_obligation>::compute
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_query_system::query::plumbing::get_query
  29: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  30: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  31: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::suggestions::InferCtxtExt>::suggest_change_mut
  32: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_selection_error
  33: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  34: rustc_middle::ty::context::GlobalCtxt::enter_local
  35: rustc_typeck::coherence::builtin::check_trait
  36: rustc_typeck::coherence::coherent_trait
  37: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::coherent_trait>::compute
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_query_system::query::plumbing::get_query
  40: rustc_query_system::query::plumbing::ensure_query
  41: rustc_session::session::Session::track_errors
  42: rustc_typeck::check_crate
  43: rustc_interface::passes::analysis
  44: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  46: rustc_query_system::query::plumbing::get_query
  47: rustc_middle::ty::context::tls::enter_global
  48: rustc_interface::interface::run_compiler_in_existing_thread_pool
  49: scoped_tls::ScopedKey<T>::set
  50: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (94d346360 2020-04-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `&mut T: std::marker::Unsize`
#1 [coherent_trait] coherence checking all impls of trait `std::ops::DispatchFromDyn`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0601`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/71036#issuecomment-626384616).

### PR DESCRIPTION
**Pull request by cofibrant**
Previously code of the form 

```rust
#![feature(unsize, dispatch_from_dyn)]

use std::marker::Unsize;
use std::ops::DispatchFromDyn;

pub struct Foo<'a, T: ?Sized> {
    _inner: &'a &'a T,
}

impl<'a, T: ?Sized + Unsize<U>, U: ?Sized> DispatchFromDyn<Foo<'a, U>> for Foo<'a, T> {}
```

would generate an ICE due to the missing `Unsize` impl being run through the `suggest_change_mut` suggestion. This PR adds an early exit and a pointer to the appropriate docs regarding `Unsize` instead:

```
error[E0277]: the trait bound `&'a T: std::marker::Unsize<&'a U>` is not satisfied
  --> src/test/ui/issues/issue-71036.rs:11:1
   |
11 | impl<'a, T: ?Sized + Unsize<U>, U: ?Sized> DispatchFromDyn<Foo<'a, U>> for Foo<'a, T> {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Unsize<&'a U>` is not implemented for `&'a T`
   |
   = note: all implementations of `Unsize` are provided automatically by the compiler, see <https://doc.rust-lang.org/stable/std/marker/trait.Unsize.html> for more information
   = note: required because of the requirements on the impl of `std::ops::DispatchFromDyn<&'a &'a U>` for `&'a &'a T`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

r? @estebank 

Resolves #71036

### CODE REVIEW

**Comment by doctorn** [comment]
cc @Centril

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 1]
```diff
@@ -283,6 +283,11 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                             .unwrap_or(false);
                         let is_from = format!("{}", trait_ref.print_only_trait_path())
                             .starts_with("std::convert::From<");
+                        let is_unsize = {
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs:286]: you can test whether something is the unsize trait by using the "lang items" -- you can use [`tcx.lang_items()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.lang_items) to access them and then invoke [`unsize_trait`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/lang_items/struct.LanguageItems.html#method.unsize_trait). Then compare if `Some(trait_ref.def_id) == tcx.lang_Items().unsize_trait()`.

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 2]
```diff
@@ -404,6 +409,20 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                             err.emit();
                             return;
                         }
+                        if is_unsize {
```
Comment (nikomatsakis) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs:412]: This code seems fine, though I'm not sure if it's the best approach, versus modifying the tips below not to fire. I guess it seems fine. 

Nit: I'd put a blank line before the `if`

Comment (doctorn) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs:410]: I think I agree - I've moved the if-guard onto the tip that's causing the ICE and updated the comments

File: src/librustc_trait_selection/traits/error_reporting/mod.rs (hunk 1 above)
Comment (doctorn) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs]: I hadn't spotted I was in an `InferCtxt` so I didn't realise I had lang items available to me. Thanks for catching this!

File: src/librustc_trait_selection/traits/error_reporting/mod.rs (hunk 2 above)
Comment (doctorn) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs:410]: This added an extra note to the diagnostic (which I think is a good thing) and I've updated the test accordingly

File: src/librustc_trait_selection/traits/error_reporting/mod.rs [hunk 3]
```diff
@@ -283,6 +283,8 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
                             .unwrap_or(false);
                         let is_from = format!("{}", trait_ref.print_only_trait_path())
                             .starts_with("std::convert::From<");
+                        let is_unsize =
+                            { Some(trait_ref.def_id()) == self.tcx.lang_items().unsize_trait() };
```
Comment (estebank) [inline src/librustc_trait_selection/traits/error_reporting/mod.rs:287]: Are the braces needed? Have you ran `x.py fmt`?

**Review by estebank — APPROVED** [review]
Looks good to me after niko's requests!

File: src/librustc_trait_selection/traits/error_reporting/mod.rs (hunk 3 above)
Comment (doctorn) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs:287]: Not strictly necessary, but I ran `./x.py fmt`

Comment (doctorn) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs:287]: I can remove if you think that's better?

Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/mod.rs:287]: Na, if it's fine with fmt it's fine with me.
