### PR TITLE
Check node kind to avoid ICE in `check_expr_return()`

### LINKED ISSUE #86721: ICE: compiler/rustc_middle/src/hir/map/mod.rs:744:18: expected item, found assoc constant T in T::T (hir_id=HirId { owner: DefId(0:4 ~ mutant[317d]::T::T), local_id: 0 })
### Code

```Rust
trait T {
    const T: usize = return;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (a435b49e8 2021-06-28)
binary: rustc
commit-hash: a435b49e86d16e98dcc6595dd471f95e823f41aa
commit-date: 2021-06-28
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error[E0601]: `main` function not found in crate `mutant`
 --> mutant.rs:1:1
  |
1 | / trait T {
2 | |     const T: usize = return;
3 | | }
  | |_^ consider adding a `main` function to `mutant.rs`

error: internal compiler error: compiler/rustc_middle/src/hir/map/mod.rs:744:18: expected item, found assoc constant T in T::T (hir_id=HirId { owner: DefId(0:4 ~ mutant[317d]::T::T), local_id: 0 })

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1007:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (a435b49e8 2021-06-28) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `T::T`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

error[E0601]: `main` function not found in crate `mutant`
 --> mutant.rs:1:1
  |
1 | / trait T {
2 | |     const T: usize = return;
3 | | }
  | |_^ consider adding a `main` function to `mutant.rs`

error: internal compiler error: compiler/rustc_middle/src/hir/map/mod.rs:744:18: expected item, found assoc constant T in T::T (hir_id=HirId { owner: DefId(0:4 ~ mutant[317d]::T::T), local_id: 0 })

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1007:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_middle::hir::map::Map::expect_item
   8: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   9: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_typeck::check::typeck
  12: rustc_query_system::query::plumbing::get_query_impl
  13: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  14: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  15: rustc_typeck::check::typeck_item_bodies
  16: rustc_query_system::query::plumbing::get_query_impl
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  18: rustc_session::utils::<impl rustc_session::session::Session>::time
  19: rustc_typeck::check_crate
  20: rustc_interface::passes::analysis
  21: rustc_query_system::query::plumbing::get_query_impl
  22: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  23: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  24: rustc_span::with_source_map
  25: rustc_interface::interface::create_compiler_and_run
  26: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (a435b49e8 2021-06-28) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `T::T`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
This PR fixes #86721. The ICE described there is apparently due to a misunderstanding:
https://github.com/rust-lang/rust/blob/e98897e5dc9898707bf4331c43b2e76ab7e282fe/compiler/rustc_typeck/src/check/expr.rs#L684-L685

Intuitively, one would think that calling `expect_item()` after `get_parent_item()` should succeed, but as it turns out, `get_parent_item()` can also return foreign, trait, and impl items as well as crates, whereas `expect_item()` specifically expects a `Node::Item`. I have therefore added an extra check to prevent this ICE.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/expr.rs [hunk 1]
```diff
@@ -682,23 +682,27 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             let encl_item_id = self.tcx.hir().get_parent_item(expr.hir_id);
-            let encl_item = self.tcx.hir().expect_item(encl_item_id);
 
-            if let hir::ItemKind::Fn(..) = encl_item.kind {
-                // We are inside a function body, so reporting "return statement
-                // outside of function body" needs an explanation.
+            // Somewhat confusingly, get_parent_item() does not necessarily return an
+            // item -- it can also return a Foreign-/Impl-/TraitItem or a Crate (see
+            // issue #86721). If it does, we still report the same error.
+            if let Some(hir::Node::Item(encl_item)) = self.tcx.hir().find(encl_item_id) {
```
Comment (LeSeulArtichaut) [inline compiler/rustc_typeck/src/check/expr.rs:689]: IIUC this doesn't cover associated/trait functions, does it?

So here's another idea I have: instead of matching on all kinds of body owner, can we check that the parent is a body owner (`tcx.hir().maybe_body_owned_by(encl_item_id).is_some()`) and if it is, get its span with `tcx.hir().span(encl_item_id)`?

Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/expr.rs]: Thanks for the suggestion, but I don't think that this is what we want here. The `if` block is responsible for adding the following explanatory note to the error message:
```
error[E0572]: return statement outside of function body
 --> test.rs:2:10
  |
1 | / fn foo() {
2 | |     [(); return];
  | |          ^^^^^^ the return is part of this body...
3 | | }
  | |_- ...not the enclosing function body
```
Without it, or if the enclosing item is not a function, the same error is emitted, just without the extra note:
```
error[E0572]: return statement outside of function body
 --> test.rs:1:25
  |
1 | const N: usize = { [(); return]; };
  |                         ^^^^^^
```
The intention is that the note should explain why the `return` is outside of a function body, if it _appears_ to be inside one. But it only makes sense to issue such a note if the enclosing item actually _is_ a function.

You are right in that the check should also cover functions in trait and impl items, which I have fixed now.

Comment (LeSeulArtichaut) [reply compiler/rustc_typeck/src/check/expr.rs]: Okay, sounds good.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 2]
```diff
@@ -682,23 +682,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             };
 
             let encl_item_id = self.tcx.hir().get_parent_item(expr.hir_id);
-            let encl_item = self.tcx.hir().expect_item(encl_item_id);
 
-            if let hir::ItemKind::Fn(..) = encl_item.kind {
-                // We are inside a function body, so reporting "return statement
-                // outside of function body" needs an explanation.
+            if self.tcx.hir().maybe_body_owned_by(encl_item_id).is_some() {
```
Comment (LeSeulArtichaut) [inline compiler/rustc_typeck/src/check/expr.rs:686]: Isn't this check redundant with the following `if let`?

File: src/test/ui/typeck/issue-86721-return-expr-ice.rs [hunk 3]
```diff
@@ -0,0 +1,17 @@
+// Regression test for the ICE described in #86721.
+
+// revisions: rev1 rev2
```
Comment (LeSeulArtichaut) [inline src/test/ui/typeck/issue-86721-return-expr-ice.rs:3]: If we want to check that no ICE occurs having those two cases in a single test with no revisions should be fine

**Review by LeSeulArtichaut — COMMENTED** [review]
Looks good, left some nits

File: compiler/rustc_typeck/src/check/expr.rs (hunk 2 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/expr.rs:686]: No, because a trait method does not have a body if it does not have a default implementation, but it can still contain a misplaced return expression, e.g.:
```rust
fn foo(a: [(); return]);
```

File: src/test/ui/typeck/issue-86721-return-expr-ice.rs (hunk 3 above)
Comment (FabianWolff) [reply src/test/ui/typeck/issue-86721-return-expr-ice.rs:3]: I thought so, too, but for some reason, the type checker aborts after the first error here, so I have had to split this into two revisions to make sure both traits are type checked.

File: compiler/rustc_typeck/src/check/expr.rs (hunk 2 above)
Comment (LeSeulArtichaut) [reply compiler/rustc_typeck/src/check/expr.rs:686]: What about matching on `hir::TraitItemKind::Fn(_, hir::TraitFn::Provided(_))`?

Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/expr.rs]: Yes, that should also work. Fixed.

**Review by LeSeulArtichaut — APPROVED** [review]
Okay, looks good to me, thanks for the PR!
