### PR TITLE
Make `const_eval_select` a real intrinsic

### LINKED ISSUE #100696: panic msg for slicing used to contain path to user's code, now contains path to core
I just noticed this regression from 1.60 to 1.61 because TRPL reasons.

### Code

I tried this code:

```rust
fn main() {
    let s = "ü";
    println!("{}", &s[0..1]);
}
```

I expected to see a panic with this message, pointing to the line in my code that caused the panic, which is what I see if I run `cargo +1.60 run`:

```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ü' (bytes 0..2) of `ü`', 
src/main.rs:3:21
```

Instead, if I run `cargo +1.61 run`, I see a panic with a message pointing to a path in core:

```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ü' (bytes 0..2) of `ü`', 
library/core/src/str/mod.rs:127:5
```

For clearer viewing:

```diff
- [...] it is inside 'ü' (bytes 0..2) of `ü`', src/main.rs:3:21
+ [...] it is inside 'ü' (bytes 0..2) of `ü`', library/core/src/str/mod.rs:127:5
```

The core path is still what I see with `cargo +1.63 run`.

### Version it worked on

It most recently worked on: Rust 1.60.0

### Version with regression

It stopped working with 1.61.0

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: aarch64-apple-darwin
release: 1.61.0
LLVM version: 14.0.0
```

## Other info

What's fun is because of the infrastructure I have with the book, I can see that Rust 1.47 was the first version to point to the user's code; [before then it pointed to core as well](https://github.com/rust-lang/book/commit/2567c35e8491df127657100196679e5a22f485fb#diff-f3aba0b18739fa5f2507cf1e05726db411dd7c99bf83a2302be2df7ca4761915).

This does NOT seem to occur with all panics coming from core; for example, trying to `unwrap` a `None` points to main:

```rust
fn main() {
    None.unwrap()
}
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:2:10
```

*Indexing* out of bounds of an array points to main:

```rust
use rand;

fn main() {
    let index: usize = rand::random(); // to get around the compile-time catch of out-of-bound constants
    let foo = [1, 2, 3][index];
}
```

```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 13912094962097789605', 
src/main.rs:5:15
```

Interestingly, *slicing* out of bounds of an array points to core (that is, this is the same issue):

```rust
use rand;

fn main() {
    let index: usize = rand::random(); // to get around the compile-time catch of out-of-bound constants
    let foo = &[1, 2, 3][index..index + 1];
}
```

```
thread 'main' panicked at 'range end index 17812862265448483785 out of range for slice of length 3', 
library/core/src/slice/index.rs:73:5
```

so it doesn't appear to be a problem with panic messages in general, but something specific about slicing panics in particular.

### PR DESCRIPTION
**Pull request by fee1-dead**
This fixes issues where `track_caller` functions do not have nice panic
messages anymore when there is a call to the function, and uses the
MIR system to replace the call instead of dispatching via lang items.

Fixes #100696.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/mir/block.rs [hunk 1]
```diff
@@ -732,6 +731,109 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
...
+                if intrinsic == sym::const_eval_select {
+                    let place = match &args[2] {
+                        mir::Operand::Copy(place) | mir::Operand::Move(place) => Some(place),
+                        mir::Operand::Constant(_) => None,
+                    };
+                    if let Some(place) = place {
+                        let ty = self.mir.local_decls[place.local].ty;
+                        match ty.kind() {
+                            ty::FnDef(..) | ty::FnPtr(..) => {}
+                            ty::Closure(_, substs) => {
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/block.rs:743]: Is this even reachable? AFAIK `Closure` disappears long before MIR reaches codegen.

Why does the interpreter only need a `FnDef` but this needs more cases?

Comment (fee1-dead) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:743]: Because the ctfe interpreter does not need to handle closures? Does `ty::Closure` really disappear?

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:743]: Mir never sees `ty::Closure`. So I assume neither does codegen. Closures become `FnDef` calls by the time they reach this stage of compilation.

There is still `FnPtr` support in codegen though and not in CTFE. That should also be made consistent - either by removing `FnPtr` support in codegen, or by implementing it in both of them *and ensuring we have tests for it*.

Comment (fee1-dead) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:743]: > Closures become `FnDef` calls by the time they reach this stage of compilation.

But the problem here is that the MIR is passing a closure as an argument, and not actually calling it. So I guess there is no MIR transformation for that?

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:743]: But even then, there is no good reason for this to differ between codegen and CTFE, I think. Also having to do a bunch of complicated extra stuff for closures is somewhat surprising. There is probably another API that avoids this problem.

For example, I think we could require both arguments to be `FnDef`, and then implement a wrapper like
```rust
const_eval_select_inner<I, C, R, O>(
  arg: I,
  arg_const: C,
  arg_runtime: R,
  fn_const: impl FnOnce(I, C) -> O, // must be a FnDef type (but we don't have a trait for that)
  fn_runtime: impl FnOnce(I, R) -> O, // must be a FnDef type (but we don't have a trait for that)
) -> R;

fn const_eval_select<I, F_C: FnOnce(I) -> O, F_R: impl FnOnce(I) -> O, O>(arg: I, c: F_C, r: F_R) -> O {
  fn call_it<I, F: FnOnce(I) -> O, O>(arg: I, f: F) -> O { f(arg) }

  const_eval_select_inner(
    arg,
    c,
    r,
    call_it::<I, F_C, O>,
    call_it::<I, F_R, O>,
  )
}
```

Comment (fee1-dead) [reply compiler/rustc_codegen_ssa/src/mir/block.rs:743]: That won't fix #100696 and would just be equivalent to the current code. I'm going to remove the logic around closures and see what I can do.

Comment (RalfJung) [reply compiler/rustc_codegen_ssa/src/mir/block.rs]: Oh I see.

But if slicing directly used `const_eval_select_inner`, then that could fix https://github.com/rust-lang/rust/issues/100696, couldn't it?

**Comment by RalfJung** [comment]
Another possible implementation plan would be to exploit that we have separate MIR for CTFE and runtime, and implement the intrinsic via lowering to a regular function call some place in the MIR pipeline. That would make supporting `track_caller` trivial. It'd also share the code to do that between codegen and CTFE.

**Comment by fee1-dead** [comment]
> Another possible implementation plan would be to exploit that we have separate MIR for CTFE and runtime

Yes, but AFAIK there is no separate query for runtime-only MIR, right? Implementing it that way would require adding such a query and rewiring runtime MIR usage to that.

**Comment by RalfJung** [comment]
The optimized_mir query is only used for runtime MIR, I think. But maybe that changed again. The hierarchy of MIR queries is historically an underdocumented mess, not sure if it improved over the last year.

But I am pretty sure that there is a fork in the road somewhere for MIR, and we should be able to use that here.

**Comment by RalfJung** [comment]
Yeah looks like `mir_drops_elaborated_and_const_checked` is the last MIR that is shared, and then `mir_for_ctfe` clones that while `optimized_mir` steals it.

**Comment by RalfJung** [comment]
It is kind of a crude hack to have 'implementation' passes in optimized_mir, but it might be the best solution for this particular intrinsic.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 2]
```diff
@@ -827,10 +823,30 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MirNeighborCollector<'a, 'tcx> {
...
-            mir::TerminatorKind::Call { ref func, .. } => {
+            mir::TerminatorKind::Call { ref func, ref args, .. } => {
                 let callee_ty = func.ty(self.body, tcx);
                 let callee_ty = self.monomorphize(callee_ty);
-                visit_fn_use(self.tcx, callee_ty, true, source, &mut self.output);
+                if let ty::FnDef(def_id, _) = callee_ty.kind()
+                        && self.tcx.fn_sig(*def_id).skip_binder().abi == RustIntrinsic
+                            && self.tcx.item_name(*def_id) == sym::const_eval_select
+                    {
+                        // mark the third arg as this function's neighbor.
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:833]: don't we also need the second arg for CTFE?

File: compiler/rustc_monomorphize/src/collector.rs [hunk 3]
```diff
@@ -827,10 +823,30 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MirNeighborCollector<'a, 'tcx> {
 
         let tcx = self.tcx;
         match terminator.kind {
-            mir::TerminatorKind::Call { ref func, .. } => {
+            mir::TerminatorKind::Call { ref func, ref args, .. } => {
                 let callee_ty = func.ty(self.body, tcx);
                 let callee_ty = self.monomorphize(callee_ty);
-                visit_fn_use(self.tcx, callee_ty, true, source, &mut self.output);
+                if let ty::FnDef(def_id, _) = callee_ty.kind()
+                        && self.tcx.fn_sig(*def_id).skip_binder().abi == RustIntrinsic
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:830]:
```suggestion
                        && self.tcx.is_intrinsic(*def_id)
```

File: compiler/rustc_monomorphize/src/collector.rs [hunk 4]
```diff
@@ -827,10 +823,30 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MirNeighborCollector<'a, 'tcx> {
...
+                            && self.tcx.item_name(*def_id) == sym::const_eval_select
+                    {
+                        // mark the third arg as this function's neighbor.
+                        let callee_ty = args[2].ty(self.body, tcx);
+                        let mut callee_ty = self.monomorphize(callee_ty);
+                        if let ty::Closure(_, substs) = callee_ty.kind() {
```
Comment (oli-obk) [inline compiler/rustc_monomorphize/src/collector.rs:836]: why is this checking for closures when compiler/rustc_typeck/src/check/fn_ctxt/checks.rs checks for FnDef and rejects anything else?

File: compiler/rustc_mir_transform/src/lib.rs [hunk 5]
```diff
@@ -137,6 +142,65 @@ pub fn provide(providers: &mut Providers) {
...
 
+fn remap_mir_for_const_eval_select<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    mut body: Body<'tcx>,
+    context: hir::Constness,
+) -> Body<'tcx> {
+    for bb in body.basic_blocks.as_mut().iter_mut() {
+        let terminator = bb.terminator.as_mut().expect("invalid terminator");
+        // temporarily replace it with a dummy kind.
+        match std::mem::replace(&mut terminator.kind, TerminatorKind::Unreachable) {
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/lib.rs:153]: you could just mutably match on the terminator instead and `std::mem::take` the fields you want to move out of. You're only going to replace it with a `Call` terminator again anyway.

**Review by oli-obk — CHANGES_REQUESTED** [review]
yea, I like this variant of doing it on the MIR

File: compiler/rustc_mir_transform/src/lib.rs (hunk 5 above)
Comment (fee1-dead) [reply compiler/rustc_mir_transform/src/lib.rs]: Done

**Comment by fee1-dead** [comment]
that was only a rebase - no amends happened

File: compiler/rustc_monomorphize/src/collector.rs [hunk 6]
```diff
@@ -112,12 +112,6 @@
 //! method in operand position, we treat it as a neighbor of the current
 //! mono item. Calls are just a special case of that.
 //!
-//! #### Closures
-//! In a way, closures are a simple case. Since every closure object needs to be
-//! constructed somewhere, we can reliably discover them by observing
-//! `RValue::Aggregate` expressions with `AggregateKind::Closure`. This is also
-//! true for closures inlined from other crates.
```
Comment (RalfJung) [inline compiler/rustc_monomorphize/src/collector.rs:119]: Why did this get removed, it seems unrelated to const_eval_select?

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs [hunk 7]
```diff
@@ -259,6 +264,30 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 return Compatibility::Incompatible(coerce_error);
             }
 
+            // Check that second and third argument of `const_eval_select` must be `FnDef`.
+            //
+            // This is here because there is currently no way to express a trait bound for `FnDef` types only.
```
Comment (RalfJung) [inline compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:269]: Also the first argument needs to be a tuple, right?

Comment (RalfJung) [reply compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:269]: Also the comment doesn't mention that the 2nd argument is additionally checked for `const`.

File: library/core/src/intrinsics.rs [hunk 8]
```diff
@@ -2095,6 +2097,65 @@ extern "rust-intrinsic" {
...
+    /// replaced with a call to `called_at_rt` otherwise.
+    ///
+    /// # Type Requirements
+    ///
+    /// The two functions must be both function items. They cannot be function
+    /// pointers or closures.
+    ///
+    /// `arg` will be the arguments that will be passed to either one of the
+    /// two functions, therefore, both functions must accept the same type of
+    /// arguments. Both functions must return RET.
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2114]: `arg` must be a tuple, right?

File: library/core/src/intrinsics.rs [hunk 9]
```diff
@@ -2119,18 +2180,20 @@ extern "rust-intrinsic" {
 /// the occasional mistake, and this check should help them figure things out.
 #[allow_internal_unstable(const_eval_select)] // permit this to be called in stably-const fn
 macro_rules! assert_unsafe_precondition {
-    ($e:expr) => {
+    ($([$($tt:tt)*])?($($i:ident:$ty:ty),*$(,)?) => $e:expr) => {
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2183]: The documentation should be adjusted to explain the new syntax for this macro.

File: library/core/src/intrinsics.rs [hunk 10]
```diff
@@ -2472,6 +2485,7 @@ pub const unsafe fn write_bytes<T>(dst: *mut T, val: u8, count: usize) {
 #[rustc_const_unstable(feature = "const_eval_select", issue = "none")]
 #[lang = "const_eval_select"]
 #[rustc_do_not_const_check]
+#[track_caller]
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2488]: Does this do anything? The intrinsic disappears before the attribute has any effect, I think.
```suggestion
// The function is compiled away, so track_caller has no effect, but merely
// serves as documentation that caller location information is propagated.
#[track_caller]
```

File: library/core/src/intrinsics.rs (hunk 9 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2183]: > Using `[...]` for type argument is rather strange, can't this be `<...>`?

Angled brackets are not group tokens and `>` is ambiguous with `$tt:tt`.

File: library/core/src/intrinsics.rs (hunk 8 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2114]: Yes, but that is enforced by the function signature where `F: FnOnce<ARG>`.

File: library/core/src/intrinsics.rs (hunk 10 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2488]: I left it while debugging. there is `cfg(bootstrap)` above as we have now switched to the intrinsic so I am not worried about this

File: compiler/rustc_typeck/src/check/fn_ctxt/checks.rs (hunk 7 above)
Comment (fee1-dead) [reply compiler/rustc_typeck/src/check/fn_ctxt/checks.rs]: added explanation.

File: library/core/src/intrinsics.rs (hunk 8 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs]: docs updated.

File: library/core/src/intrinsics.rs (hunk 9 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2188]: macro docs updated.

File: library/core/src/intrinsics.rs (hunk 10 above)
Comment (RalfJung) [reply library/core/src/intrinsics.rs:2493]: Oh, I didn't realize this is the old function.

Seems better not to change it, then. Who knows if that breaks something...
```suggestion
```

**Comment by RalfJung** [comment]
LGTM! Probably could use some squashing though.

**Comment by fee1-dead** [comment]
Squashed
@rustbot ready

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/100997#issuecomment-1227468237
@bors r- rollup=iffy

**Comment by fee1-dead** [comment]
Huh. The CI logs say otherwise:

image

**Comment by RalfJung** [comment]
But the LLVM IR diff in alloc-optimization definitely looks like it's about const_eval_select:
```
         8: start: 
         9: ; call core::mem::valid_align::ValidAlign::new_unchecked::runtime 
        10:  tail call void @_ZN4core3mem11valid_align10ValidAlign13new_unchecked7runtime17hb98b1e4b3c334143E(i64 4) 
        11: ; call core::mem::valid_align::ValidAlign::new_unchecked::runtime 
        12:  tail call void @_ZN4core3mem11valid_align10ValidAlign13new_unchecked7runtime17hb98b1e4b3c334143E(i64 4) 
        13:  ret void 
next:10      !~~~~~~~  error: match on wrong line
```
It passing on PR CI just means that the tests pass in one configuration; full bors CI uses plenty of different configurations and one of them seemingly does not work.

In particular this is a no-system-llvm test, and the PR CI runner might use system LLVM (not sure about this). @fee1-dead did you try `./x.py test src/test/codegen` locally (and using a rustc LLVM build)?

**Comment by fee1-dead** [comment]
I didn't. I will do that now. Thanks for the info

File: library/core/src/intrinsics.rs [hunk 11]
```diff
@@ -2119,18 +2185,20 @@ extern "rust-intrinsic" {
...
 #[allow_internal_unstable(const_eval_select)] // permit this to be called in stably-const fn
 macro_rules! assert_unsafe_precondition {
-    ($e:expr) => {
+    ($([$($tt:tt)*])?($($i:ident:$ty:ty),*$(,)?) => $e:expr) => {
         if cfg!(debug_assertions) {
-            // Use a closure so that we can capture arbitrary expressions from the invocation
-            let runtime = || {
+            // allow non_snake_case to allow capturing const generics
+            #[allow(non_snake_case)]
+            fn runtime$(<$($tt)*>)?($($i:$ty),*) {
```
Comment (RalfJung) [inline library/core/src/intrinsics.rs:2192]: Maybe try adding `inline(always)` here?

Comment (RalfJung) [reply library/core/src/intrinsics.rs:2192]: Also shouldn't this be `track_caller` to actually fix https://github.com/rust-lang/rust/issues/100696?

**Comment by fee1-dead** [comment]
The error is now

```
error: verification with 'FileCheck' failed
status: exit status: 1
command: "/home/gh-fee1-dead/rust/build/x86_64-unknown-linux-gnu/ci-llvm/bin/FileCheck" "--input-file" "/home/gh-fee1-dead/rust/build/x86_64-unknown-linux-gnu/test/codegen/mem-replace-direct-memcpy/mem-replace-direct-memcpy.ll" "/home/gh-fee1-dead/rust/src/test/codegen/mem-replace-direct-memcpy.rs" "--allow-unused-prefixes" "--check-prefixes" "CHECK,NONMSVC"
stdout: none
--- stderr -------------------------------
/home/gh-fee1-dead/rust/src/test/codegen/mem-replace-direct-memcpy.rs:20:11: error: CHECK: expected string not found in input
// CHECK: call void @llvm.memcpy.{{.+}}({{i8\*|ptr}} align 1 %{{.*}}, {{i8\*|ptr}} align 1 %dest, i{{.*}} 1, i1 false)
          ^
/home/gh-fee1-dead/rust/build/x86_64-unknown-linux-gnu/test/codegen/mem-replace-direct-memcpy/mem-replace-direct-memcpy.ll:47:21: note: scanning from here
; core::mem::replace
                    ^
/home/gh-fee1-dead/rust/build/x86_64-unknown-linux-gnu/test/codegen/mem-replace-direct-memcpy/mem-replace-direct-memcpy.ll:129:2: note: possible intended match here
 call void @llvm.memcpy.p0.p0.i64(ptr align 1 %_4, ptr align 1 %src, i64 1, i1 false)
 ^

Input file: /home/gh-fee1-dead/rust/build/x86_64-unknown-linux-gnu/test/codegen/mem-replace-direct-memcpy/mem-replace-direct-memcpy.ll
Check file: /home/gh-fee1-dead/rust/src/test/codegen/mem-replace-direct-memcpy.rs

-dump-input=help explains the following input dump
```

Which I don't know how to fix.

File: library/core/src/intrinsics.rs (hunk 11 above)
Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2194]: Yeah, added.

**Comment by fee1-dead** [comment]
The problem is none of the functions called by `mem::replace` use `const_eval_select`, so I fail to see how that might be related..

**Comment by RalfJung** [comment]
Could you try using `--stage 2`? I think I've seen this `%src` vs `%dest` difference before... ah here it is: https://github.com/rust-lang/rust/issues/99619

**Comment by RalfJung** [comment]
Actually if it's that problem, `--stage 2` will probably not help.

`mem-replace-direct-memcpy.rs` is not one of the ones that failed on CI, so if this is the *only* failing list now you are probably good.

File: library/core/src/intrinsics.rs (hunk 11 above)
Comment (RalfJung) [reply library/core/src/intrinsics.rs:2194]: But this means the PR doesn't have a test for https://github.com/rust-lang/rust/issues/100696. Please always add a test when closing an issue.

Comment (fee1-dead) [reply library/core/src/intrinsics.rs:2194]: It does: https://github.com/rust-lang/rust/pull/100759/files#diff-14c656686badef9cc39ce6cf394aa18a0f61ccfe3d8c9e1c53b8cb9f1e791c57

It is just that that issue isn't caused by this one not having track_caller.

File: compiler/rustc_mir_transform/src/lib.rs [hunk 12]
```diff
@@ -537,7 +600,7 @@ fn inner_optimized_mir(tcx: TyCtxt<'_>, did: LocalDefId) -> Body<'_> {
 
     debug_assert!(!body.has_free_regions(), "Free regions in optimized MIR");
 
-    body
+    remap_mir_for_const_eval_select(tcx, body, hir::Constness::NotConst)
```
Comment (bjorn3) [inline compiler/rustc_mir_transform/src/lib.rs:603]: Could this run before the optimizations? That would allow inlining the non-const callee, making `const_eval_select` pretty much zero-cost even if the backend doesn't support inlining.

Comment (fee1-dead) [reply compiler/rustc_mir_transform/src/lib.rs:603]: > Could this run before the optimizations?

Maybe, but it could create unnecessary memory in query system storage as we now have to pass a `bool` to indicate whether we want the const version or not, right?

Comment (RalfJung) [reply compiler/rustc_mir_transform/src/lib.rs:603]: You can just do it at the beginning of `inner_optimized_mir` rather than at the end, can't you?

Comment (bjorn3) [reply compiler/rustc_mir_transform/src/lib.rs:603]: What @RalfJung suggested is exactly what I meant.

**Comment by fee1-dead** [comment]
I spent some time installing a cross-compiler only to realize that I cannot run arm on my machine without an elaborate qemu/chroot setup.. Still have no idea why the error would only occur on that arch.

**Comment by bjorn3** [comment]
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcompiler_builtins-72be9a347ae6a81c.rlib(compiler_builtins-72be9a347ae6a81c.compiler_builtins.8b5aa9ec-cgu.139.rcgu.o): in function `__aeabi_f2ulz':
compiler_builtins.8b5aa9ec-cgu.139:(.text.__aeabi_f2ulz+0x8): undefined reference to `core::f32::<impl f32>::to_bits::rt_f32_to_u32'
```

The `__aeabi_*` symbols only exist on arm. The issue seems to be that the const_eval_select call in f32::to_bits no longer causes rt_f32_to_u32 to be codegened, despite it being called. Also you shouldn't need qemu to reproduce this error. You only need a linker capable of linking for arm and then passing `--target arm-unknown-linux-gnueabihf` to `./x.py build` and then compile this test with `--target arm-unknown-linux-gnueabihf` on the host.

File: library/core/src/num/f32.rs [hunk 13]
```diff
@@ -1034,6 +1034,7 @@ impl f32 {
             }
         }
 
+        #[inline(always)]
```
Comment (bjorn3) [inline library/core/src/num/f32.rs:1037]: I don't think this is the right fix. I think the collector needs to handle these functions even without `#[inline(always)]`.

Comment (fee1-dead) [reply library/core/src/num/f32.rs:1037]: The collector runs on `instance_mir` which runs on the shim mir or `optimized_mir`, which should already have the const_eval_select calls rewired.

Comment (bjorn3) [reply library/core/src/num/f32.rs:1037]: Yeah, no clue why it fails to work properly.

Comment (fee1-dead) [reply library/core/src/num/f32.rs:1037]: I've tested with the arm target compiler and this is indeed a fix, so I guess this should be some ghost bug that people who add `const_eval_select` to library functions worry about in the future.

Comment (Mark-Simulacrum) [reply library/core/src/num/f32.rs:1037]: I don't think that's a sufficiently satisfying answer; the bug is at minimum exposed by these changes. We should understand why (even if we don't necessarily fix it here) and track fixing it.

Comment (tmiasko) [reply library/core/src/num/f32.rs:1037]: The undefined reference is from compiler-builtins, which shouldn't have any link time dependencies on the core. We have been using inline to avoid this issue so far, so that seems fine to me, although personally I would prefer approach proposed in rust-lang/compiler-builtins#472.

Comment (bjorn3) [reply library/core/src/num/f32.rs:1037]: Right, forgot about that.

Comment (fee1-dead) [reply library/core/src/num/f32.rs]: I created an issue and linked to it from this attribute.

**Comment by RalfJung** [comment]
@bors delegate+

`bors r=oli-obk,RalfJung` once CI is green

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

Many of the reported regressions are being classified as noise from recently arising bimodalities in certain benchmarks.

* The regression to ripgrep does look like it might be legitimate, at least from skimming its [graph](https://perf.rust-lang.org/index.html?start=2022-08-06&end=c84083b08e2db69fcf270c4045837fa02663a3bf&benchmark=ripgrep-13.0.0&profile=opt&scenario=full&stat=instructions:u) and zooming in.

**Comment by oli-obk** [comment]
ripgrep only regressed in LLVM, a bit later it got improved (in llvm) by a targetted placement of `#[inline]`. So maybe this is just inlining noise and we can get the perf back by sprinkling `#[inline]` at the functions modified in this PR
