### PR TITLE
Don't ICE if TAIT-defining fn contains a closure with `_` in return type

### LINKED ISSUE #119916: `nightly-20240112` regression: ICE: delayed span bug: inferring return types and opaque types do not mix well
### Code

https://github.com/risingwavelabs/risingwave

(not minimized yet)

https://github.com/risingwavelabs/risingwave/blob/7c3edb1ff2d64f9c0e50eacfca09ea5ce112ca2d/src/stream/src/executor/dispatch.rs#L382-L412

### Error output

```
error: internal compiler error: no errors encountered even though `span_delayed_bug` issued

error: internal compiler error: inferring return types and opaque types do not mix well
   --> src/stream/src/executor/dispatch.rs:382:9
    |
382 |         #[try_stream]
    |         ^^^^^^^^^^^^^
    |
note: delayed at compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs:140:43
         0: std::backtrace::Backtrace::create
         1: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         2: <rustc_errors::DiagCtxt>::emit_diagnostic
         3: <rustc_errors::diagnostic_builder::DiagnosticBuilder>::emit_producing_error_guaranteed
         4: <rustc_hir_analysis::collect::type_of::opaque::TaitConstraintLocator>::check
         5: rustc_hir::intravisit::walk_expr::<rustc_hir_analysis::collect::type_of::opaque::TaitConstraintLocator>
         6: rustc_hir::intravisit::walk_impl_item::<rustc_hir_analysis::collect::type_of::opaque::TaitConstraintLocator>
         7: rustc_hir::intravisit::walk_item::<rustc_hir_analysis::collect::type_of::opaque::TaitConstraintLocator>
         8: rustc_hir_analysis::collect::type_of::opaque::find_opaque_ty_constraints_for_tait
         9: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        10: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        12: rustc_query_impl::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
        13: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
        14: rustc_hir_analysis::collect::type_of::type_of
        15: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        16: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
        17: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        18: rustc_query_impl::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
        19: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
        20: <rustc_privacy::EmbargoVisitor as rustc_hir::intravisit::Visitor>::visit_item
        21: <rustc_middle::hir::map::Map>::visit_all_item_likes_in_crate::<rustc_privacy::EmbargoVisitor>
        22: rustc_privacy::effective_visibilities
        23: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::effective_visibilities::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        24: <rustc_query_impl::query_impl::effective_visibilities::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        26: rustc_query_impl::query_impl::effective_visibilities::get_query_incr::__rust_end_short_backtrace
        27: rustc_hir_analysis::check::compare_impl_item::refine::check_refining_return_position_impl_trait_in_trait
        28: rustc_hir_analysis::check::compare_impl_item::compare_impl_method
        29: rustc_hir_analysis::check::check::check_item_type
        30: rustc_hir_analysis::check::wfcheck::check_well_formed
        31: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        32: <rustc_query_impl::query_impl::check_well_formed::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_hir::hir_id::OwnerId)>>::call_once
        33: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_hir::hir_id::OwnerId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        34: rustc_query_impl::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
        35: rustc_middle::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system::query::caches::VecCache<rustc_hir::hir_id::OwnerId, rustc_middle::query::erase::Erased<[u8; 1]>>>
        36: <rustc_middle::hir::ModuleItems>::par_items::<rustc_hir_analysis::check::wfcheck::check_mod_type_wf::{closure#0}>
        37: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
        38: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        39: <rustc_query_impl::query_impl::check_mod_type_wf::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
        40: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalModDefId, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        41: rustc_query_impl::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
        42: <rustc_middle::hir::map::Map>::try_par_for_each_module::<rustc_hir_analysis::check_crate::{closure#4}::{closure#0}>::{closure#0}
        43: rustc_hir_analysis::check_crate
        44: rustc_interface::passes::analysis
        45: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        46: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        47: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
        48: rustc_query_impl::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
        49: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}::{closure#3}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        50: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
        51: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
        52: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        53: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}>
        54: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        55: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        56: std::sys::unix::thread::Thread::new::thread_start
        57: __pthread_joiner_wake
   --> src/stream/src/executor/dispatch.rs:382:9
    |
382 |         #[try_stream]
    |         ^^^^^^^^^^^^^
    = note: this error: internal compiler error originates in the attribute macro `try_stream` (in Nightly builds, run with -Z macro-backtrace for more info)

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/Users/xxchan/Projects/risingwave/rustc-ice-2024-01-13T06_41_26-98452.txt` to your bug report

note: compiler flags: --crate-type lib -C lto=off -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED] -C link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

### Bisect

searched nightlies: from nightly-2024-01-11 to nightly-2024-01-13
regressed nightly: nightly-2024-01-12
searched commit range: https://github.com/rust-lang/rust/compare/a2d9d73e608f1b24eba840c4fd2d68dbe3b65e01...62d7ed4a6775c4490e493093ca98ef7c215b835b
regressed commit: https://github.com/rust-lang/rust/commit/65b323b168daa6c723a8a5b4ddf939f3b12e0329

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>

Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start 2024-01-11 -- check -p risingwave_stream
```
</details>

### PR DESCRIPTION
**Pull request by lukas-code**
The `delay_span_bug` got added in https://github.com/rust-lang/rust/pull/119803/commits/0e82aaeb6799041991c54fb9ff37b5c20a5c6146 to reduce the amount of errors emitted for functions that have `_` in their return type, because inference doesn't apply to function items. But this logic shouldn't apply to closures, because their return types *can* be inferred.

Fixes https://github.com/rust-lang/rust/issues/119916.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs [hunk 1]
```diff
@@ -135,18 +135,18 @@ impl TaitConstraintLocator<'_> {
...
-                );
-                self.found = Some(ty::OpaqueHiddenType {
-                    span: DUMMY_SP,
-                    ty: Ty::new_error(self.tcx, guar),
-                });
-                return;
-            }
+        // Function items with `_` in their return type already emit an error, skip any
+        // "non-defining use" errors for them.
+        if let Some(hir_sig) = self.tcx.hir_node_by_def_id(item_def_id).fn_sig()
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs:140]: Can you change this to manually match on node kind, and only look for `Node::Item`/`Node::TraitItem`/`Node::ImplItem`/`Node::ForeignItem`?

The difference between when `Node::fn_sig` and `Node::fn_decl` return `Some(_)` is extremely subtle. It took me quite some time to even realize that's what changed in this PR.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by compiler-errors** [comment]
@rustbot author

r=me after that tho

File: compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs (hunk 1 above)
Comment (lukas-code) [reply compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs]: For `Node::ForeignItem` this isn't necessary because we already skip them here: https://github.com/rust-lang/rust/blob/30dfb9e046aeb878db04332c74de76e52fb7db10/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs#L262

I've added a test to ensure that is the case and we don't emit any extra errors for them.

Without `Node::ForeignItem`, the manual match is now just `Node::fn_sig` manually inlined and I don't think that's a lot better. The real problem here is the ambigous naming of `FnSig` vs `FnDecl`, where `FnSig` = `FnDecl` + `FnHeader` and `FnHeader` = effects (`const`/`aync`/`unsafe`) + call abi.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs]: What about renaming it to `fn_item_sig` or `fn_sig_of_item` or something? Something that distinguishes that it's grabbing just the signature of an item.

Comment (lukas-code) [reply compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs]: For `fn_item_sig` I'd expect it to also include foreign function items, which `fn_sig` does not.

Comment (lukas-code) [reply compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs]: I've updated the comment regarding `fn_sig` vs `fn_decl` and added a `debug_assert!` to hopefully make it more clear what's happening here.

And I'd rather not bikeshed a new name for `fn_sig` in this PR, so with that,
@rustbot review

For the record, here is the manual match version, which is literally just inlined `fn_sig`: https://github.com/rust-lang/rust/commit/79b8fa577579a4c7beeaa683a24326c1519d56e5

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs]: I prefer the manual match version, but whatever
