### PR TITLE
Provide structured suggestions when finding structs when expecting a trait

### LINKED ISSUE #45817: Wrong error when lifetime is appended to associated type
```rust
error[E0404]: expected trait, found enum `std::result::Result`
   --> src/imessage/db.rs:216:44
    |
216 | fn unwrap_iter<'a,T,E>(iter: Iterator<Item=std::result::Result<T,E> + 'a>) -> Result<Vec<T>>
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ not a trait

```

In the code fragment above, the problem is not that `Item` needs to point to a trait (is that even acceptable?) but rather that `+ 'a` can only come after a trait.

Ideally, this should actually be a different error ("lifetime specification here is not valid" or something along those lines) with the source of the error being the presence of `'a` and not the definition of `Item`, but if it remains E0404 then at least a hint should be provided along the lines of 

>`+ 'a` can only follow a trait, but `std::result::Result<...>` is a type

### LINKED ISSUE #75829: Suggest Stream<Item = String> when specifying the item using the trait syntax.
This issue describes a suggestion I wish the compiler made. Given the following code:
```rust
use futures::stream::Stream;

struct Foo<T>
where
    T: Stream,
    <T as Stream>::Item: String,
{
    t: T,
}
```
The compiler produces this error:
```
error[E0404]: expected trait, found struct `String`
    --> src/lib.rs:6:26
     |
6    |       <T as Stream>::Item: String,
     |                            ^^^^^^ help: a trait with a similar name exists: `ToString`
```
It would be nice if the compiler suggested changing it to
```rust
use futures::stream::Stream;

struct Foo<T>
where
    T: Stream<Item = String>,
{
    t: T,
}
```
The same applies to impl blocks, that also don't produce the suggestion.

### PR DESCRIPTION
**Pull request by estebank**
When finding an ADT in a trait object definition provide some solutions. Fix #45817.
Given `<Param as Trait>::Assoc: Ty` suggest `Param: Trait<Assoc = Ty>`. Fix #75829.

### CODE REVIEW

**Comment by estebank** [comment]
Screen Shot 2020-09-23 at 11 04 20 PM

vs

Screen Shot 2020-09-23 at 11 04 26 PM

and

Screen Shot 2020-09-23 at 11 06 05 PM

vs

Screen Shot 2020-09-23 at 11 05 48 PM

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -438,27 +439,205 @@ impl<'a> LateResolutionVisitor<'a, '_, '_> {
...
+                true,
+                CrateLint::No,
+            ) {
+                partial_res
+            } else {
+                return false;
+            };
+            if !(matches!(
+                partial_res.base_res(),
+                hir::def::Res::Def(hir::def::DefKind::AssocTy, _)
```
Comment (matthewjasper) [inline compiler/rustc_resolve/src/late/diagnostics.rs:572]: Why is this needed. This suggestion would also make sense for `<&T as Trait>::Assoc: String`

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:577]: I think you might have meant to point at the next `matches` check, as this one just verifies that we are trying to constrain an associated type. The last commit now accounts for references. I have these checks because I want to avoid incorrect suggestions, as that is more harmful than not providing a suggestion we could have.

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:577]: For future reference, this will _not_ help for a case like `<(T, T) as Trait>::Assoc: String`.
