### PR TITLE
suppress field expr with generics error message if it's a method

### LINKED ISSUE #67680: Confusing hint on missing parentheses after collect<>
The following code produces a quite unhelpful error from the compiler:

```rust
use std::io;                                               
use std::fs;
use std::path::{Path, PathBuf};

pub fn build<P: AsRef<Path>>(path: P) -> Result<Vec<PathBuf>, io::Error> {
    let entries = fs::read_dir(path)?;

    let filevec = entries.map(| res | res.map(| e | e.path()))
                         .collect::<Result<Vec<_>, io::Error>>?;

    Ok(filevec)
}
```
The error in question being `.collect::<Result<Vec<_>, io::Error>>?;` instead of `.collect::<Result<Vec<_>, io::Error>>()?;`.

Compiler output:

```
   Compiling playground v0.0.1 (/playground)
error: field expressions may not have generic arguments
 --> src/lib.rs:9:36
  |
9 |                          .collect::<Result<Vec<_>, io::Error>>?;
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
It's quite a simple mistake, but I got confused by the error message and tried different type-related fixes which didn't work (obviously).

This might be related to #54521

### PR DESCRIPTION
**Pull request by oriongonza**
Don't emit "field expressions may not have generic arguments" if it's a method call without `()`

r? estebank
Fixes #67680

Is this the best way to go? It's by far the simplest I could come up with.

### CODE REVIEW

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -576,6 +576,7 @@ pub enum StashKey {
     UndeterminedMacroResolution,
     /// Used by `Parser::maybe_recover_trailing_expr`
     ExprInPat,
+    GenericInFieldExpr,
```
Comment (compiler-errors) [inline compiler/rustc_errors/src/lib.rs:579]: Pls put a comment on this to explain when it's used

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 2]
```diff
@@ -3055,7 +3055,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             err.help("methods are immutable and cannot be assigned to");
         }
 
-        err.emit()
+        self.dcx().try_steal_replace_and_emit_err(expr.span, StashKey::GenericInFieldExpr, err)
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/expr.rs:3058]: Leave a comment here explaining why the error we emit is worse than this one

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/expr.rs:3058]: Also, can you stash using the span of the field instead?

File: compiler/rustc_parse/src/parser/expr.rs [hunk 3]
```diff
@@ -1369,11 +1369,13 @@ impl<'a> Parser<'a> {
             ))
         } else {
             // Field access `expr.f`
+            let span = lo.to(self.prev_token.span);
             if let Some(args) = seg.args {
-                self.dcx().emit_err(errors::FieldExpressionWithGeneric(args.span()));
+                self.dcx()
+                    .create_err(errors::FieldExpressionWithGeneric(args.span()))
+                    .stash(span, StashKey::GenericInFieldExpr);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/expr.rs:1376]: re: comment above

> Also, can you stash using the span of the field instead?

Then you can use `.stash(seg.ident.span` here instead. Using span logic (`.to`) sometimes plays weirdly with macros, so keeping the span simpler is better.

**Review by compiler-errors — APPROVED** [review]
Please address the nits, then I can approve.

And also fix the test file to not mention "issue". It's redundant -- leave a comment inside saying `// Regression test for <...>` if you want.

**Comment by compiler-errors** [comment]
Also please give this a more descriptive error message. This is approximately the most generic message that could exist currently 😆

**Comment by compiler-errors** [comment]
Whoops I misspoke in the last comment--I meant that this needs a better PR title :)

**Comment by dev-ardi** [comment]
Oh I was actually changing the error message :P

**Comment by dev-ardi** [comment]
Now that I'm on it, do you think that 
`"attempted to access `{field}` on type `{expr_t} as a field when it's a method`",`
is better than
`"attempted to access field `{field}` on type `{expr_t}`",`
?

**Comment by compiler-errors** [comment]
I think the error message is fine as-is
