### PR TITLE
[const-prop] Fix ICE calculating enum discriminant

### LINKED ISSUE #66787: Compiler panic while building crate with tokio, rocket, and snafu
# Summary

I'm trying to build my crate on nightly, and I'm getting a compiler panic.

I bisected several nightly builds to try and narrow down when the problem started.

The last known good nightly was `nightly-2019-11-10-x86_64-unknown-linux-gnu`, and the first failing was `nightly-2019-11-11-x86_64-unknown-linux-gnu`

The panic also occurs in `nightly-2019-11-26-x86_64-unknown-linux-gnu`.

The crates causing the panic are available here: https://github.com/quilt/simulation/tree/bug-report

# Build Output

```
sam@sam-XPS-15-9570:~/Code/notion/notion-server$ RUST_BACKTRACE=1 cargo build
   Compiling notion-server v0.1.0 (/home/sam/Code/notion/notion-server)
warning: unused variable: `handle`
  --> notion-server/src/api/mod.rs:12:12
   |
12 | pub fn run(handle: Handle) -> Result<()> {
   |            ^^^^^^ help: consider prefixing with an underscore: `_handle`
   |
   = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'overflow computing relative variant idx', src/libcore/option.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/3fc30d884ae0c988d98452a06737705cfe34806a/src/liballoc/boxed.rs:956
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/3fc30d884ae0c988d98452a06737705cfe34806a/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  14: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  15: rust_begin_unwind
             at src/libstd/panicking.rs:302
  16: core::panicking::panic_fmt
             at src/libcore/panicking.rs:141
  17: core::option::expect_failed
             at src/libcore/option.rs:1187
  18: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
  19: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  20: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  21: rustc_mir::transform::run_passes
  22: rustc_mir::transform::run_optimization_passes
  23: rustc_mir::transform::optimized_mir
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  33: rustc::util::common::time
  34: rustc_mir::monomorphize::collector::collect_crate_mono_items
  35: rustc::util::common::time
  36: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  37: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
  41: rustc::ty::query::__query_compute::exported_symbols
  42: rustc::dep_graph::graph::DepGraph::with_task_impl
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  44: rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root
  45: rustc::ty::context::tls::with_context::{{closure}}
  46: rustc_metadata::rmeta::encoder::encode_metadata
  47: rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  48: rustc::ty::context::TyCtxt::encode_metadata
  49: rustc_interface::passes::start_codegen::{{closure}}
  50: rustc_interface::passes::start_codegen
  51: rustc::ty::context::tls::enter_global
  52: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  53: rustc_interface::passes::create_global_ctxt::{{closure}}
  54: rustc_interface::passes::BoxedGlobalCtxt::enter
  55: rustc_interface::queries::Query<T>::compute
  56: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  57: rustc_interface::interface::run_compiler_in_existing_thread_pool
  58: std::thread::local::LocalKey<T>::with
  59: scoped_tls::ScopedKey<T>::set
  60: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (3fc30d884 2019-11-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `<error::Api as snafu::IntoError<error::Error>>::into_error`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
#2 [exported_symbols] exported_symbols
end of query stack
error: could not compile `notion-server`.

To learn more, run the command again with --verbose
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #66787

Different approach than #66857 

r? @oli-obk 
cc @RalfJung @eddyb

### CODE REVIEW

File: src/librustc_mir/interpret/place.rs [hunk 1]
```diff
@@ -1040,21 +1040,18 @@ where
     ) -> InterpResult<'tcx> {
         let variant_scalar = Scalar::from_u32(variant_index.as_u32()).into();
 
+        if dest.layout.for_variant(self, variant_index).abi.is_uninhabited() {
+            throw_ub!(InvalidDiscriminant(variant_scalar));
```
Comment (eddyb) [inline src/librustc_mir/interpret/place.rs]: So I think this is a misuse of `InvalidDiscriminant`, because there's no discriminant being *read* (which is why I assume it takes a `Scalar`).

I would prefer a different error for "tried to create uninhabited variant" (which could contain the type and variant index, let's say), which should generally be impossible outside of dead code.

And keep `InvalidDiscriminant` for something that can totally happen with unsafe code.

Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: > which should generally be impossible outside of dead code.

Should it be `InvalidProgram` then in terms of error category, instead of `UndefinedBehavior`?

File: src/librustc_mir/interpret/place.rs [hunk 2]
```diff
@@ -1040,21 +1040,18 @@ where
...
+        }
+
         match dest.layout.variants {
-            layout::Variants::Single { index } => {
-                if index != variant_index {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: Please keep that check (as an `assert!` is possible)

File: src/librustc_mir/interpret/place.rs [hunk 3]
```diff
@@ -1040,21 +1040,18 @@ where
...
+            layout::Variants::Single { .. } => { }
             layout::Variants::Multiple {
                 discr_kind: layout::DiscriminantKind::Tag,
                 discr: ref discr_layout,
                 discr_index,
                 ..
             } => {
-                if !dest.layout.ty.variant_range(*self.tcx).unwrap().contains(&variant_index) {
-                    throw_ub!(InvalidDiscriminant(variant_scalar));
-                }
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: Same, please keep that check.

File: src/librustc_mir/interpret/place.rs [hunk 4]
```diff
@@ -1077,9 +1074,6 @@ where
                 discr_index,
                 ..
             } => {
-                if !variant_index.as_usize() < dest.layout.ty.ty_adt_def().unwrap().variants.len() {
-                    throw_ub!(InvalidDiscriminant(variant_scalar));
-                }
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: Same, please keep that check.

File: src/librustc_mir/interpret/place.rs [hunk 5]
```diff
@@ -1040,21 +1040,18 @@ where
     ) -> InterpResult<'tcx> {
         let variant_scalar = Scalar::from_u32(variant_index.as_u32()).into();
 
+        if dest.layout.for_variant(self, variant_index).abi.is_uninhabited() {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: I am very unhappy with directly depending on `is_uninhabited`. We don't otherwise do such a check and rely on validation instead.

But it looks like this is otherwise the cleanest solution. Is there a short explanation for why the code below makes no sense for uninhabited variants?

File: src/librustc_mir/interpret/place.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: Or maybe UB actually makes sense (rustc just happens to not allow the user to write such MIR). But the issue is that layout code doesn't actually provide a layout for uninhabited variants, so there's no reasonable way to implement `SetDiscriminant`. So maybe `throw_ub!(Unreachable)`? I assume codegen also emits an "unreachable" for LLVM here.

Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: > I assume codegen also emits an "unreachable" for LLVM here.

No, it does nothing, `unreachable` might make more sense though.

Actually, I'm not sure how right I am about the dead code part, since the MIR creating that uninhabited variant is still left around.

Presumably it requires a call that returns an uninhabited type, but not `!` (which typeck would know about).

So it's "dynamically dead" code, in that the function could never return, but this is not encoded in the CFG.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: > Is there a short explanation for why the code below makes no sense for uninhabited variants?

Uninhabited variants don't get a tag/niche encoding, so there's nothing that could be written, other than undef perhaps.

File: src/librustc_mir/interpret/place.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: These checks are both impossible to trip (`for_variant` above or anywhere else would cause an out of bounds panic) and not even consistent with eachother (presumably `variant_range` is the "more correct" one).

Note that this is `VariantIdx` and *not* some arbitrary integer. It's more akin to a `DefId` in its expected validity, except cheaper to work with.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: > Uninhabited variants don't get a tag/niche encoding

IOW, layout code uses the *same* check to set up the niche/tag? As long as we can keep that in sync, that seems good to me. Might be best to have two comments (here and in layout) referencing each other to ensure that this is the case.

File: src/librustc_mir/interpret/place.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: I may have suggested this too, as codegen does have an `assert_eq!(index, variant_index)` here IIRC.

File: src/librustc_mir/interpret/place.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: > No, it does nothing, unreachable might make more sense though.

Yeah I'd be in favor of keeping Miri and codegen in sync here.

File: src/librustc_mir/interpret/place.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: `VariantIdx` is pretty easy to get from a `u32` so that doesn't really reassure me.

We mostly have these because it seems inconsistent to check for `Single` and not check for `Multiple`.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: > IOW, layout code uses the *same* check to set up the niche/tag?

Yeah, *exactly* uninhabited variants are ignored when computing the `niche_variants` range or the possible tag values.

I don't think there's anything to keep in sync since there's no possible optimization to make here (uninhabited variants are *by definition* the unrepresented variants), and it might make more sense to keep this code in sync with codegen instead (including e.g. emitting an `unreachable` in codegen instead of just `return`-ing).

I was also suggesting to @oli-obk that this sort of code should be the prime candidate for some sort of "elaborator" that expands MIR into lower-level operations (detailed enough to work for both miri and codegen).

File: src/librustc_mir/interpret/place.rs (hunk 2 above)
Comment (wesleywiser) [reply src/librustc_mir/interpret/place.rs]: Ah, yes. You're correct

https://github.com/rust-lang/rust/blob/fe969f4ec67a5bd317818cbc7a648c5795af15fa/src/librustc_codegen_ssa/mir/place.rs#L339-L341

File: src/librustc_mir/interpret/place.rs (hunk 1 above)
Comment (wesleywiser) [reply src/librustc_mir/interpret/place.rs]: I will change this to `throw_ub!(Unreachable)` then.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: > I don't think there's anything to keep in sync since there's no possible optimization to make here (uninhabited variants are by definition the unrepresented variants)

Well layout could switch to some other way of checking inhabitedness.
Is this the relevant call?

https://github.com/rust-lang/rust/blob/2da942f32802c8233a09744024dfbc34431adf65/src/librustc/ty/layout.rs#L1037

There's also this but that takes ZST into account as well:

https://github.com/rust-lang/rust/blob/2da942f32802c8233a09744024dfbc34431adf65/src/librustc/ty/layout.rs#L816-L818

This seems quite odd, looks like at least the "single-variant enum has struct-like layout" only applies of all the other variants are uninhabited *and* ZST?

File: src/librustc_mir/interpret/place.rs (hunk 4 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: `Single` has a pre-selected variant, hence the check (which codegen also has), but `Multiple` holds *all* the variants, so any of them is a valid index.

> `VariantIdx` is pretty easy to get from a `u32` so that doesn't really reassure me.

Okay (well that applies to any ID in the compiler, but that's besides the point) but `for_variant` would still panic here:
https://github.com/rust-lang/rust/blob/2da942f32802c8233a09744024dfbc34431adf65/src/librustc/ty/layout.rs#L2063-L2065

Going through *some other* information to check the `VariantIdx` doesn't make much sense to me.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: > This seems quite odd, looks like at least the "single-variant enum has struct-like layout" only applies of all the other variants are uninhabited and ZST?

That fixed the bug where you would partially initialize an uninhabited variant and that would leave the bounds of the `enum` and overwrite something else, before getting to the field that actually makes it uninhabited (and therefore would require a panic/infinite loop to attempt to initialize).

> Well layout could switch to some other way of checking inhabitedness.

`for_variant(variant_idx).is_uninhabited()` is *the result* of layout checking inhabitedness for a given variant, *not* the input it uses in doing so.

`.iter().any(|f| f.abi.is_uninhabited())` iterates over the *fields* of the variant (hence the name `f`).

File: src/librustc_mir/interpret/place.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: I'm always a fan of double-checking such things (but I agree the inconsistency between the two checks should be fixed).

However, I am also fine replacing them by a comment saying that `for_variant` already checked the variants existence.

File: src/librustc_mir/interpret/place.rs (hunk 5 above)
Comment (RalfJung) [reply src/librustc_mir/interpret/place.rs]: > That fixed the bug where you would partially initialize an uninhabited variant and that would leave the bounds of the enum and overwrite something else, before getting to the field that actually makes it uninhabited (and therefore would require a panic/infinite loop to attempt to initialize).

Ah, I keep forgetting that in MIR we can have partial initialization of enums.
(Might be worth having a comment explaining that?)

> for_variant(variant_idx).is_uninhabited() is the result of layout checking inhabitedness for a given variant, not the input it uses in doing so.

Oh I see. All right then.

**Comment by wesleywiser** [comment]
I've pushed changes which I believe addresses all of the feedback so far. This is ready for review.

File: src/librustc_mir/interpret/place.rs [hunk 6]
```diff
@@ -1038,23 +1038,23 @@ where
         variant_index: VariantIdx,
         dest: PlaceTy<'tcx, M::PointerTag>,
     ) -> InterpResult<'tcx> {
-        let variant_scalar = Scalar::from_u32(variant_index.as_u32()).into();
+        if dest.layout.for_variant(self, variant_index).abi.is_uninhabited() {
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: Please add a comment explaining what eddyb explained to me: that layout computation entirely excludes `is_uninhabited` variants from consideration, so that there just isn't a way to even represent their discriminant.

File: src/librustc_mir/interpret/place.rs [hunk 7]
```diff
@@ -1038,23 +1038,23 @@ where
...
                 discr_kind: layout::DiscriminantKind::Tag,
                 discr: ref discr_layout,
                 discr_index,
                 ..
             } => {
-                if !dest.layout.ty.variant_range(*self.tcx).unwrap().contains(&variant_index) {
-                    throw_ub!(InvalidDiscriminant(variant_scalar));
-                }
+                // No need to validate the discriminant here because the `TyLayout::for_variant()`
+                // call earlier already checks the variant is valid.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]:
```suggestion
                // call earlier already checks that the variant is valid.
```

File: src/librustc_mir/interpret/place.rs [hunk 8]
```diff
@@ -1077,9 +1077,9 @@ where
                 discr_index,
                 ..
             } => {
-                if !variant_index.as_usize() < dest.layout.ty.ty_adt_def().unwrap().variants.len() {
-                    throw_ub!(InvalidDiscriminant(variant_scalar));
-                }
+                // No need to validate the discriminant here because the `TyLayout::for_variant()`
+                // call earlier already checks the variant is valid.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]:
```suggestion
                // call earlier already checks that the variant is valid.
```

**Comment by RalfJung** [comment]
Let's fix those typos before landing.

@bors r-

File: src/librustc_mir/interpret/place.rs [hunk 9]
```diff
@@ -1038,23 +1038,26 @@ where
         variant_index: VariantIdx,
         dest: PlaceTy<'tcx, M::PointerTag>,
     ) -> InterpResult<'tcx> {
-        let variant_scalar = Scalar::from_u32(variant_index.as_u32()).into();
+
+        // Layout computation excludes uninhabited variants from consideration
+        // so this checks that the `variant_index` is valid.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/place.rs]: The key point is that there's no alternative: there's no way to represent those variants in the given layout.

Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: I feel like there's been a lot of muddying the waters on "`variant_index` validity".

It's always valid, it's always in range, it's impossible for it to not be a variant (despite what has been said wrt the comments lower down).
Also, for `Multiple`, the `variants` vec *always* includes *all* variants declared in the `enum`.

What needs to be handled *here* is "the variant is uninhabited" i.e. *unrepresented*.
This means *two* things, not just one (another source of confusion):
* there is no tag/niche allocated for it, so the best you could do is write undef over the tag/niche
* fully initializing (which is what `SetDiscriminant` means) an uninhabited variant should never be reachable, as another uninhabited `Operand` *must've been* evaluated for *at least* one of the fields, so this should be some sort of error (I think @RalfJung is right that this is technically an "invalid program" situation)

Comment (eddyb) [reply src/librustc_mir/interpret/place.rs]: (of course the PR was updated while I was trying to post that comment, heh)

I think the new form of the comment seems fine, but I'd wait until @RalfJung also agrees, to proceed.
