### PR TITLE
interpret: fix TypeId pointers being considered data pointers

### LINKED ISSUE #4477: std::fmt::Debug for TypeId triggers false positive UB warning
Likely related to this recent change: https://github.com/rust-lang/rust/pull/142789.
When run with nightly MIRI, this code errors with "Undefined Behavior: accessing alloc258 which contains a `TypeId`".

```rust
fn main() {
    println!("{:?}", std::any::TypeId::of::<u64>());
}
```

From the rust playground ([link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=3c3d9855b771b99c0e3d91835238da31)), with version 1.90.0-nightly (2025-07-17 e4662966273ed58b51f9):

<details>
<summary>Expand for the full error message</summary>

```
error: Undefined Behavior: accessing alloc258 which contains a `TypeId`
   --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:208:9
    |
208 |         self.cast::<()>() as usize
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `std::ptr::const_ptr::<impl *const ()>::expose_provenance` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:208:9: 208:35
    = note: inside `std::any::TypeId::as_u128` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/any.rs:786:25: 786:50
    = note: inside `<std::any::TypeId as std::fmt::Debug>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/any.rs:822:39: 822:53
    = note: inside `core::fmt::rt::Argument::<'_>::fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs:173:76: 173:95
    = note: inside `std::fmt::write` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:1469:21: 1469:44
    = note: inside `std::io::default_write_fmt::<std::io::StdoutLock<'_>>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:639:11: 639:40
    = note: inside `<std::io::StdoutLock<'_> as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/mod.rs:1954:13: 1954:42
    = note: inside `<&std::io::Stdout as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:834:9: 834:36
    = note: inside `<std::io::Stdout as std::io::Write>::write_fmt` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:808:9: 808:33
    = note: inside `std::io::stdio::print_to::<std::io::Stdout>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:1164:21: 1164:47
    = note: inside `std::io::_print` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:1275:5: 1275:37
note: inside `main`
   --> src/main.rs:2:5
    |
2   |     println!("{:?}", std::any::TypeId::of::<u64>());
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

</details>

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/miri/issues/4477
r? @oli-obk

### CODE REVIEW

File: library/core/src/any.rs [hunk 1]
```diff
@@ -783,7 +783,7 @@ impl TypeId {
 
         // This is a provenance-stripping memcpy.
         for (i, chunk) in self.data.iter().copied().enumerate() {
-            let chunk = chunk.expose_provenance().to_ne_bytes();
+            let chunk = chunk.addr().to_ne_bytes();
```
Comment (RalfJung) [inline library/core/src/any.rs:786]: This change is not required, but since we want to strip the provenance anyway there's no reason to expose it.
