### PR TITLE
fix: improve the suggestion on future not awaited

### LINKED ISSUE #80658: Note when opaque future from `async fn` is involved in a type mismatch is unclear
```rust
fn foo() -> u8 {
    async fn async_fn() -> () {}
    
    async_fn()
}
```
emits
```
error[E0308]: mismatched types
 --> src/lib.rs:4:5
  |
1 | fn foo() -> u8 {
  |             -- expected `u8` because of return type
2 |     async fn async_fn() -> () {}
  |                            -- the `Output` of this `async fn`'s found opaque type
3 |
4 |     async_fn()
  |     ^^^^^^^^^^ expected `u8`, found opaque type
  |
  = note:     expected type `u8`
          found opaque type `impl Future`
```

The note "the `Output` of this `async fn`'s found opaque type" is kind of hard to understand. If the return type of `async_fn` isn't explicitly given, it doesn't even point at a type:
```
2 |     async fn async_fn() {}
  |                         - the `Output` of this `async fn`'s found opaque type
```

Perhaps the note should instead look like this:

```
2 |     async fn async_fn() {}
  |     ----- the found opaque type is the `impl Future` returned by this `async fn`
```

@rustbot label A-async-await A-diagnostics D-confusing T-compiler

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Considering the following code

```rust
fn foo() -> u8 {
    async fn async_fn() -> u8 {  22 }

    async_fn()
}

fn main() {}
```

the error generated before this commit from the compiler is

```
➜  rust git:(macros/async_fn_suggestion) ✗ rustc test.rs --edition 2021
error[E0308]: mismatched types
 --> test.rs:4:5
  |
1 | fn foo() -> u8 {
  |             -- expected `u8` because of return type
...
4 |     async_fn()
  |     ^^^^^^^^^^ expected `u8`, found opaque type
  |
  = note:     expected type `u8`
          found opaque type `impl Future<Output = u8>`
help: consider `await`ing on the `Future`
  |
4 |     async_fn().await
  |               ++++++

error: aborting due to previous error
```

In this case the error is nor perfect, and can confuse the user that do not know that the opaque type is the future.

So this commit will propose (and conclude the work start in https://github.com/rust-lang/rust/issues/80658)
to change the string `opaque type` to `future` when applicable and also remove the Expected vs Received note by adding a more specific one regarding the async function that return a future type.

So the new error emitted by the compiler is

```
error[E0308]: mismatched types
 --> test.rs:4:5
  |
1 | fn foo() -> u8 {
  |             -- expected `u8` because of return type
...
4 |     async_fn()
  |     ^^^^^^^^^^ expected `u8`, found future
  |
note: calling an async function returns a future
 --> test.rs:4:5
  |
4 |     async_fn()
  |     ^^^^^^^^^^
help: consider `await`ing on the `Future`
  |
4 |     async_fn().await
  |               ++++++

error: aborting due to previous error
```

Fixes https://github.com/rust-lang/rust/issues/80658

It remains to rework the case described in the following issue https://github.com/rust-lang/rust/issues/107899 but I think this deserves its own PR after we discuss a little bit how to handle these kinds of cases.

r? @eholk 

@rustbot label +I-async-nominated

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 1]
```diff
@@ -283,6 +268,20 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
         }
     }
 
+    pub fn suggest_await_on_future(
+        &self,
+        diag: &mut Diagnostic,
+        sp: Span,
+        _cause: &ObligationCause<'tcx>,
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:275]: Why does this take a cause if it's not used?

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 2]
```diff
@@ -1783,14 +1783,19 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
-                            &expected_label,
-                            expected,
-                            &found_label,
-                            found,
-                            &sort_string(values.expected, exp_p),
-                            &sort_string(values.found, found_p),
-                        );
+                        if let Some(ExpectedFound { found: found_ty, .. }) = exp_found {
+                            let is_future = self.tcx.ty_is_opaque_future(found_ty);
+                            if !is_future {
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:1788]: What is this doing? Please leave a comment that explains why we're not nothing this if it's a future.

----

nit: this is equally as readable.

```suggestion
                            if !self.tcx.ty_is_opaque_future(found_ty) {
```

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 3]
```diff
@@ -2853,7 +2858,8 @@ impl IntoDiagnosticArg for ObligationCauseAsDiagArg<'_> {
 #[derive(Clone, Copy, PartialEq, Eq, Hash)]
 pub enum TyCategory {
     Closure,
-    Opaque,
+    /// Boolan flag set to true means that the opaque type is a future
+    Opaque(bool),
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2862]: Can we just make this a different ty category, like `OpaqueFuture`?

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 4]
```diff
@@ -1,3 +1,4 @@
+use crate::errors::SuggAddLetForLetChains;
```
Comment (compiler-errors) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:1]: why did you move this?

File: tests/ui/async-await/generator-desc.stderr [hunk 5]
```diff
@@ -17,12 +17,10 @@ error[E0308]: mismatched types
...
 LL |     fun(one(), two());
-   |     ---        ^^^^^ expected opaque type, found a different opaque type
+   |     ---        ^^^^^ expected future, found a different future
    |     |
    |     arguments to this function are incorrect
    |
-   = note: expected opaque type `impl Future<Output = ()>` (opaque type at <$DIR/generator-desc.rs:5:16>)
-              found opaque type `impl Future<Output = ()>` (opaque type at <$DIR/generator-desc.rs:6:16>)
    = help: consider `await`ing on both `Future`s
    = note: distinct uses of `impl Trait` result in different opaque types
```
Comment (compiler-errors) [inline tests/ui/async-await/generator-desc.stderr:25]: Maybe this message should also be specialized for futures.

```suggestion
   = note: each `async fn` produces a future that is a unique type
```

That message sucks but something like that.

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs (hunk 4 above)
Comment (vincenzopalazzo) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs:1]: ./x fmt did, I guess?

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs:1]: I'm surprised if `x fmt` would do this, since otherwise CI would've been broken on tidy before this PR. Anyways, can you revert it? Just a nitpick.

**Comment by eholk** [comment]
@bors r? compiler-errors

(since he's already adding comments on it)

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs (hunk 1 above)
Comment (vincenzopalazzo) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs:275]: just a refused, thanks!

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 2 above)
Comment (vincenzopalazzo) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:1788]: Since the Future is a special opaque type that in most of the time the user will not touch directly, print a mismatch type is not so helpful for some target user.

The example in this PR is
```
 |     async_fn()
  |     ^^^^^^^^^^ expected `u8`, found opaque type
  |
  = note:     expected type `u8`
          found opaque type `impl Future<Output = u8>`
```

Where the Future type is never mentioned in the following code

```
fn foo() -> u8 {
    async fn async_fn() -> u8 {  22 }
    
    async_fn()
}
```

I think this will help to improve the errors with async programming for new users, for this reason this diff is skipping the suggestion if it is a future type

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs (hunk 4 above)
Comment (vincenzopalazzo) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs:1]: of course

File: tests/ui/async-await/generator-desc.stderr (hunk 5 above)
Comment (vincenzopalazzo) [reply tests/ui/async-await/generator-desc.stderr:25]: I agree with you, but this suggestion looks unrelated to this PR? maybe the right position is a followup PR?

**Comment by eholk** [comment]
We discussed this in triage today. We think saying "future" rather than "opaque type" is an improvement. The only caveat we had was that we should try to do that only when you're calling an `async fn` rather than an `-> impl Future`. Suggesting `.await` is good too, but we should try to do that only when it fixes the issue (i.e. you're in an async context and the future resolves to a type that coerces to the return type).
