### PR TITLE
Clarify the match ergonomics 2024 migration lint's output

### LINKED ISSUE #133854: "patterns are not allowed to reset the default binding mode" suggestion means nothing to me
### Code

```Rust
use std::collections::BTreeMap;

fn demo(map: BTreeMap<(usize, usize), char>) {
    map.iter().filter(|(&(_x, _y), &_c)| false);
}
```

### Current output

```
error: patterns are not allowed to reset the default binding mode in edition 2024
 --> src/lib.rs:4:24
  |
4 |     map.iter().filter(|(&(_x, _y), &_c)| false);
  |                        -^^^^^^^^^^^^^^^
  |                        |
  |                        help: desugar the match ergonomics: `&`
```

### Desired output

```
error: patterns are not allowed to reset the default binding mode in edition 2024
 --> src/lib.rs:4:24
  |
4 |     map.iter().filter(|(&(_x, _y), &_c)| false);
  |                        -^^^^^^^^^^^^^^^
  |                        |
  |                        help: add an `&` at the beginning of this pattern
```

### Rationale and extra context

Presented with this error, I was completely stumped. I have no idea what the suggestion is attempting to get me to do. 

I do not think the word "desugar" is useful here because it's not obvious to me (a) that there *was* sugar and (b) *what* the sugaring was. Without that knowledge, the suggestion is non-actionable.

After minutes of reading/reducing/reproducing the problem, I finally realized that that the `-` part of the `-^^^^^^^^^^^^^^^` was pointing to the parenthesis and not to the `&`, so I tried adding it and it compiled.

Additionally, I worry that "default binding mode" is not an established / well-known terminology so there's not much meat from that message for me to go on either. 

### Rust Version

```Shell
rustc 1.85.0-nightly (c44b3d50f 2024-12-03)
binary: rustc
commit-hash: c44b3d50fea96a3e0417e8264c16ea21a0a3fca2
commit-date: 2024-12-03
host: aarch64-apple-darwin
release: 1.85.0-nightly
LLVM version: 19.1.4
```

### PR DESCRIPTION
**Pull request by dianne**
This makes a few changes:
- Rather than using the whole pattern as a span for the lint, this collects spans for each problematic default binding mode reset and labels them with why they're problems.
- The lint's suggestions are now verbose-styled, so that it's clear what's being suggested vs. what's problematic.
- The wording is now less technical, and the hard error version of this diagnostic now links to the same reference material as the lint (currently an unwritten page of the edition guide).

I'm not totally confident in the wording or formatting, so I'd appreciate feedback on that in particular. I tried to draw a connection with word choice between the labels and the suggestion, but it might be imprecise, unclear, or cluttered. If so, it might be worth making the labels more terse and adding notes that explain them, but that's harder to read in a way too.

cc @Nadrieril @Jules-Bertholet

Closes #133854. For reference, the error from that issue becomes:
```
error: pattern uses features incompatible with edition 2024
  --> $DIR/remove-me.rs:6:25
   |
LL |     map.iter().filter(|(&(_x, _y), &_c)| false);
   |                         ^          ^ cannot implicitly match against multiple layers of reference
   |                         |
   |                         cannot implicitly match against multiple layers of reference
   |
help: make the implied reference pattern explicit
   |
LL |     map.iter().filter(|&(&(_x, _y), &_c)| false);
   |                        +
```

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -2630,4 +2630,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        } else {
+            detailed_label
+        };
+
+        self.typeck_results
+            .borrow_mut()
+            .rust_2024_migration_desugared_pats_mut()
+            .entry(pat_id)
+            .or_default()
+            .push((trimmed_span, desc.to_owned()));
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/pat.rs:2664]: I'm not totally certain if the span logic is resilient enough to ensure that a trimmed/modified span will always have the same edition as one of the input spans. In this case, `pat_span` may be from edition 2024 and `inner_span` may be from 2021.

To avoid worrying about this subtle change in behavior, could you record the `pat_span` or perhaps just its edition in this table too, so we don't implicitly rely on `trimmed_span`'s edition which may be totally random depending on the impl of `Span::until` and `SourceMap::span_extend_prev_while`.

File: compiler/rustc_mir_build/messages.ftl [hunk 2]
```diff
@@ -285,7 +285,7 @@ mir_build_pointer_pattern = function pointers and raw pointers not derived from
 
 mir_build_privately_uninhabited = pattern `{$witness_1}` is currently uninhabited, but this variant contains private fields which may become inhabited in the future
 
-mir_build_rust_2024_incompatible_pat = patterns are not allowed to reset the default binding mode in edition 2024
+mir_build_rust_2024_incompatible_pat = pattern uses features incompatible with edition 2024
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/messages.ftl:288]: maybe we should say "this pattern relies on behavior which may change in edition 2024" ?

**Comment by dianne** [comment]
Rebased: #134368 changed the migration lint's reference link to point to the edition guide, so this now uses that.

That's the only change to the initial commit, but I've added some additional commits as well. They're each fairly small, so I can squash them if they look good.
- When determining whether we should emit a hard error, ensure we check the editions of the subpattern(s) we've found issues with.
- Improve the primary message for the diagnostic.
- Since the edition guide seems good to link to when emitting an error as well, I've added the reference note from the lint to it.

There's a few other changes I'm considering, but which I'm less sure about, so they're not included:
- Currently, if any of the migration's suggested changes point to spans within an expansion, its applicability is downgraded to `MaybeIncorrect`. I'm wondering if there should be any other indication; applicability is a bit subtle from a user's perspective. This may be more of a diagnostic infra issue, though.
- The emitter already adds a note if an error originates within a macro expansion, so it may be apparent that if you get such an error in editions ≤ 2021 it's because of the macro's edition. I'm not sure, though; it may warrant another note explaining that (though think the ordering would be a bit awkward unless it can somehow be added after or as part of the emitter's note).
- If multiple subpatterns of a macro expansion reset the default binding mode, this will produce multiple instances of the "default binding mode is reset within expansion" label appearing to point to the macro's call site. It's not hard to filter the duplicates out, but they *are* distinct within the expansion; if you're compiling with `-Z macro-backtrace` on nightly it would only show the first one. Changing the diagnostic's output based on that option feels too subtle, but the current compromise is less than ideal in either case. I think the ideal for viewing the macro backtrace would be to keep the labels separate and use the more specific label wordings that get applied to spans not from expansions. Maybe that would be fine always, given the emitter's note pointing to the error being within the macro expansion? But labeling the call site with references to its internals without `-Z macro-backtrace` feels a bit awkward. Is there any precedent for a particular approach here?

File: compiler/rustc_mir_build/messages.ftl (hunk 2 above)
Comment (dianne) [reply compiler/rustc_mir_build/messages.ftl]: done; I like that wording. at first I was unsure about using it for hard errors too, but I think it works there (until exactly what's happening with patterns in edition 2024 gets sorted out, but it'll need changing regardless then)

File: compiler/rustc_hir_typeck/src/pat.rs (hunk 1 above)
Comment (dianne) [reply compiler/rustc_hir_typeck/src/pat.rs:2666]: ah, yeah. good point. I've opted to re-add the syntax context from `pat.span` to the trimmed span, to avoid needing a separate span or boolean field (and thus a tuple or struct). using `Span::trim_end` would be a less roundabout way of doing this, since it just uses `SpanData::with_hi` to do the trimming, but that would rely on `Span::trim_end` keeping this behavior. we could also inline it to use `with_hi` directly, but that's less readable.

**Comment by compiler-errors** [comment]
this looks pretty good to me. i don't have much feedback regarding the follow-ups (i'm recovering from an illness so i'd rather just r+ this now; feel free to put up additional changes separately).

@bors r+ rollup

**Comment by jieyouxu** [comment]
> * Currently, if any of the migration's suggested changes point to spans within an expansion, its applicability is downgraded to `MaybeIncorrect`. I'm wondering if there should be any other indication; applicability is a bit subtle from a user's perspective. This may be more of a diagnostic infra issue, though.

AFAIK applicability is mostly intended for tooling, especially rustfix, in relation to what suggestions can be automatically applied. To a user, this distinction should not matter -- the user won't get *automatic* suggestion application, which is a *good* thing, as it warrants user manual review and intervention.

> * The emitter already adds a note if an error originates within a macro expansion, so it may be apparent that if you get such an error in editions ≤ 2021 it's because of the macro's edition. I'm not sure, though; it may warrant another note explaining that (though think the ordering would be a bit awkward unless it can somehow be added after or as part of the emitter's note).

I think this is fine. If there are follow-up reports that this is still confusing, we can address those separately. This PR as-is is already a nice improvement.

> * If multiple subpatterns of a macro expansion reset the default binding mode, this will produce multiple instances of the "default binding mode is reset within expansion" label appearing to point to the macro's call site. It's not hard to filter the duplicates out, but they _are_ distinct within the expansion; if you're compiling with `-Z macro-backtrace` on nightly it would only show the first one. Changing the diagnostic's output based on that option feels too subtle, but the current compromise is less than ideal in either case. I think the ideal for viewing the macro backtrace would be to keep the labels separate and use the more specific label wordings that get applied to spans not from expansions. Maybe that would be fine always, given the emitter's note pointing to the error being within the macro expansion? But labeling the call site with references to its internals without `-Z macro-backtrace` feels a bit awkward. Is there any precedent for a particular approach here?

I seem to recall that being tricky. If you really want to pursue that, you may have to do some fancy span ancestor searching, which, when combined with macros (which can be from other macros), usually has a whole bunch of edge cases.
