### PR TITLE
Stabilize `unsigned_abs`

### LINKED ISSUE #74913: Tracking Issue for `fn unsigned_abs`
This is a tracking issue for `fn unsigned_abs` on signed integral types.
The feature gate for the issue is `#![feature(unsigned_abs)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history
First implemented in #74759

### PR DESCRIPTION
**Pull request by jhpratt**
Resolves #74913.

This PR stabilizes the `i*::unsigned_abs()` method, which returns the absolute value of an integer _as its unsigned equivalent_. This has the advantage that it does not overflow on `i*::MIN`.

I have gone ahead and used this in a couple locations throughout the repository.

### CODE REVIEW

File: library/core/src/num/dec2flt/mod.rs [hunk 1]
```diff
@@ -332,7 +332,7 @@ fn bound_intermediate_digits(decimal: &Decimal<'_>, e: i64) -> u64 {
         // It tries to find a positive number k such that `f << k / 10^e` is an in-range
         // significand. This will result in about `2^53 * f * 10^e` < `10^17 * f * 10^e`.
         // One input that triggers this is 0.33...33 (375 x 3).
-        f_len + (e.abs() as u64) + 17
+        f_len + (e.unsigned_abs()) + 17
```
Comment (lcnr) [inline library/core/src/num/dec2flt/mod.rs:335]:
```suggestion
        f_len + e.unsigned_abs() + 17
```

Comment (jhpratt) [reply library/core/src/num/dec2flt/mod.rs]: Fixed.

**Comment by KodrAus** [comment]
@rfcbot fcp merge

This stabilizes `i*.unsigned_abs()`, which returns a `u*` instead of an `i*` and avoids a nasty little edge-case where `i*::MIN.abs() == i*::MIN` due to wrapping. It encapsulates a few dubious looking operations in a nice safe way.

**Comment by Mark-Simulacrum** [comment]
It'd be great to call out in abs() documentation that unsigned_abs is probably what you want.

I also think the name unsigned_abs is a bit unfortunate; it feels like the return type being unsigned is not what I want to call out here - I don't know that we have better options though unfortunately.

**Comment by KodrAus** [comment]
Yeh, I think it is worth calling out this sets a precedent for operations that swap the signness (is that a word?) of the value.

I’d wondered about calling out `unsigned_abs` in the docs for `abs`, but thought it might lead to naive code like:

```rust
let abs = some_i32.unsigned_abs() as i32 // but I still need a i32
```

which wraps like `abs` but also doesn’t panic in debug. But that’s not really exclusive to `abs`.

**Comment by jhpratt** [comment]
IMO that's where clippy is useful, and lints for those type of things already exist.

**Comment by jhpratt** [comment]
Failure is unrelated to this PR.
