### PR TITLE
Override `StepBy::{try_fold, try_rfold}`

### LINKED ISSUE #57517: Iterating with step_by(1) is much slower than without
Greetings!

I'd like to report that I get some significant (negative) performance impact when calling `step_by(1)` on an iterator. I created a repository with a detailed description of the issue and benchmarks to reproduce it: https://github.com/mvlabat/step_by_one

These are the functions I tested:
```rust
pub fn iter_default_step(mut arr: Vec<i32>) -> Vec<i32> {
    for e in arr.iter_mut() {
        *e = e.wrapping_add(3);
    }
    arr
}

pub fn iter_step(mut arr: Vec<i32>, iter_step: usize) -> Vec<i32> {
    for e in arr.iter_mut().step_by(iter_step) {
        *e = e.wrapping_add(3);
    }
    arr
}
```

Calling `iter_step(vec![1; LARGE_ENOUGH], 1)` computes 1.75x slower than `iter_default_step(vec![1; LARGE_ENOUGH])`
with `const LARGE_ENOUGH: usize = 10_000_000;`.

I'm running Macbook Pro 2015 with Intel i5-5257U CPU (2.70GHz).

My rustc version: `1.33.0-nightly (c2d381d39 2019-01-10)`.

These are the exact benchmark results I got:
```
running 4 tests
test tests::bench_iter_default_step ... bench:   8,702,963 ns/iter (+/- 1,648,782)
test tests::bench_iter_step_1       ... bench:  15,267,083 ns/iter (+/- 1,236,220)
test tests::bench_iter_step_16      ... bench:   9,053,772 ns/iter (+/- 380,422)
test tests::bench_iter_step_64      ... bench:   8,711,169 ns/iter (+/- 327,562)
```

In the [repository README](https://github.com/mvlabat/step_by_one) there are also links to the generated asm code of these two functions.

### PR DESCRIPTION
**Pull request by timvermeulen**
Previous PR: https://github.com/rust-lang/rust/pull/51435

The previous PR was closed in favor of https://github.com/rust-lang/rust/pull/51601, which was later reverted. I don't think these implementations will make it harder to specialize `StepBy<Range<_>>` later, so we should be able to land this without any consequences.

This should fix https://github.com/rust-lang/rust/issues/57517 – in my benchmarks `iter` and `iter.step_by(1)` now perform equally well, provided internal iteration is used.

### CODE REVIEW

File: src/libcore/iter/adapters/mod.rs [hunk 1]
```diff
@@ -541,6 +541,21 @@ impl<I> Iterator for StepBy<I> where I: Iterator {
...
+        R: Try<Ok = Acc>,
+    {
+        if self.first_take {
+            self.first_take = false;
+            match self.iter.next() {
+                None => return Try::from_ok(acc),
+                Some(x) => acc = f(acc, x)?,
+            }
+        }
+        from_fn(|| self.iter.nth(self.step)).try_fold(acc, f)
```
Comment (scottmcm) [inline src/libcore/iter/adapters/mod.rs]: Can you just use a `while let Some(x) = self.iter.nth(self.step)` loop here instead?  It'll do the same thing, but without introducing a new closure that would regress https://github.com/rust-lang/rust/pull/62429.

**Review by scottmcm — CHANGES_REQUESTED** [review]
Thanks for the PR!  This definitely seems like one that needs try_fold (though I wish LLVM would just peel it).  One minor change and it'll be good to go.

File: src/libcore/iter/adapters/mod.rs (hunk 1 above)
Comment (timvermeulen) [reply src/libcore/iter/adapters/mod.rs]: Thanks, I forgot about that. I turned the closures into functions instead, that should have the same benefits, correct? I figured this will make it easier to potentially undo these changes in the future.
