### PR TITLE
Mark drop calls in landing pads `cold` instead of `noinline`

### LINKED ISSUE #46515: Missing optimization around __rust_alloc and unknown functions if panic=unwind
The following code gets optimized as expected:
```rust
pub fn test() -> bool {
    let x = &*Box::new(0);
    let y = &*Box::new(0);
    
    if x as *const _ == y as *const _ {
        return true;
    }
    return false;
}
```
[becomes](https://godbolt.org/g/fkwdR5)
```
; example::test
; Function Attrs: nounwind uwtable
define zeroext i1 @example::test() unnamed_addr #0 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality !dbg !18 {
  ret i1 false, !dbg !22
}
```

However, if I let the code call an unknown function instead of return, the optimization disappears:
```rust
pub fn test(f: fn()) {
    let x = &*Box::new(0);
    let y = &*Box::new(0);
    
    if x as *const _ == y as *const _ {
        f();
    }
}

```
[becomes](https://godbolt.org/g/y5acAz)
```
; example::test
; Function Attrs: uwtable
define void @example::test(void ()* nocapture nonnull %f) unnamed_addr #1 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality !dbg !36 {
  %err.i.i.i10 = alloca %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", align 8
  %_5.i.i.i.i11 = alloca %"alloc::allocator::AllocErr", align 8
  %err.i.i.i = alloca %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", align 8
  %_5.i.i.i.i = alloca %"alloc::allocator::AllocErr", align 8
  %_9.sroa.9.i.i = alloca [16 x i8], align 8
  %_9.sroa.9.0.sroa_idx9.i.i = getelementptr inbounds [16 x i8], [16 x i8]* %_9.sroa.9.i.i, i64 0, i64 0, !dbg !38
  call void @llvm.lifetime.start(i64 16, i8* nonnull %_9.sroa.9.0.sroa_idx9.i.i), !dbg !38
  %0 = getelementptr inbounds %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>", %"core::mem::ManuallyDrop<alloc::allocator::AllocErr>"* %err.i.i.i, i64 0, i32 0, i64 0, !dbg !48
  call void @llvm.lifetime.start(i64 24, i8* nonnull %0) #6, !dbg !48, !noalias !52
  %1 = call i8* @__rust_alloc(i64 4, i64 4, i8* nonnull %0) #6, !dbg !55, !noalias !52
  %2 = icmp eq i8* %1, null, !dbg !57
  br i1 %2, label %bb3.i.i.i, label %"_ZN35_$LT$alloc..boxed..Box$LT$T$GT$$GT$3new17he6f20be442f24a38E.exit", !dbg !61

[snip]
```

That seems wrong, why should the optimization stop kicking in? The corresponding C++ code does not have any problem:
```C++
#include <memory>

void test(void (*f)()) {
    auto x = std::make_unique<int>(0);
    auto y = std::make_unique<int>(0);

    if (&*x == &*y) {
        f();
    }
}
```
[becomes](https://godbolt.org/g/NqnDcd)
```
; Function Attrs: uwtable
define void @test(void (*)())(void ()* nocapture) local_unnamed_addr #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) !dbg !1204 {
  tail call void @llvm.dbg.value(metadata void ()* %0, i64 0, metadata !1208, metadata !1211), !dbg !1212
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1210, metadata !1213), !dbg !1215
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1210, metadata !1213), !dbg !1215
  tail call void @llvm.dbg.value(metadata %"class.std::unique_ptr"* undef, i64 0, metadata !1209, metadata !1213), !dbg !1214
  ret void, !dbg !1216
}
```
(I briefly thought maybe unwinding is the problem, but C++ should have the same kind of unwinding here.)

### LINKED ISSUE #87055: Unable to optimize out branches in drop function in unwind landing pad
In [this code](https://godbolt.org/z/4Wrsb4z5f):
```rust
pub fn foo(g: fn()) {
    let _var: Option<Box<i32>> = None;
    g();
}
```

Assembly:
```asm
core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<i32>>>:
        mov     rdi, qword ptr [rdi]
        test    rdi, rdi
        je      .LBB0_1
        mov     esi, 4
        mov     edx, 4
        jmp     qword ptr [rip + __rust_dealloc@GOTPCREL]
.LBB0_1:
        ret

example::foo:
        push    rbx
        sub     rsp, 16
        mov     qword ptr [rsp + 8], 0
        call    rdi
        add     rsp, 16
        pop     rbx
        ret
        mov     rbx, rax
        lea     rdi, [rsp + 8]
        call    core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<i32>>>
        mov     rdi, rbx
        call    _Unwind_Resume@PLT
        ud2

DW.ref.rust_eh_personality:
        .quad   rust_eh_personality
```

`_var` is known to be `None` so the deallocation is optimized away in the normal flow. But in landing pad for unwinding, it still generates a branch to check if `_var` is null. But it's a local variable which is not able to be modified in anywhere else and should be known to be null.

I'm expecting the `drop` of `_var` should be completely elided so that `g()` can be a tail call.

### PR DESCRIPTION
**Pull request by erikdesjardins**
Now that deferred inlining has been disabled in LLVM (#92110), this shouldn't cause catastrophic size blowup.

I confirmed that the test cases from https://github.com/rust-lang/rust/issues/41696#issuecomment-298696944 still compile quickly (<1s) after this change. ~Although note that I wasn't able to reproduce the original issue using a recent rustc/llvm with deferred inlining enabled, so those tests may no longer be representative. I was also unable to create a modified test case that reproduced the original issue.~ (edit: I reproduced it on CI by accident--the first commit timed out on the LLVM 12 builder, because I forgot to make it conditional on LLVM version)

r? @nagisa
cc @arielb1 (this effectively reverts #42771 "mark calls in the unwind path as !noinline")
cc @RalfJung (fixes #46515)

edit: also fixes #87055

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 1]
```diff
@@ -1201,8 +1201,15 @@ impl<'a, 'll, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
...
 
-    fn do_not_inline(&mut self, llret: &'ll Value) {
-        llvm::Attribute::NoInline.apply_callsite(llvm::AttributePlace::Function, llret);
+    fn apply_attrs_to_cleanup_callsite(&mut self, llret: &'ll Value) {
+        // Cleanup is always the cold path.
+        llvm::Attribute::Cold.apply_callsite(llvm::AttributePlace::Function, llret);
+
+        // In LLVM versions with deferred inlining (currently, system LLVM < 14),
+        // inlining drop glue can lead to exponential size blowup, see #41696 and #92110.
+        if !llvm_util::is_rust_llvm() && llvm_util::get_version() < (14, 0, 0) {
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_llvm/src/builder.rs:1210]: Checking for non-system llvm feels a bit hacky, not sure if I should just wait for the LLVM 14 release.

(this code is also assuming that https://reviews.llvm.org/D115497 won't be reverted upstream before then)

Comment (nagisa) [reply compiler/rustc_codegen_llvm/src/builder.rs:1210]: This seems sufficiently reasonable thing to do to me _if_ this does in fact yield any significant benefits. I wouldn't want to land changes that potentially significantly affect performance at some time in the future as it would make those other changes non-representative on their own merits.

**Comment by nagisa** [comment]
Looks like where there are benefits they are both in the LLVM spending less time optimizing the IR (i.e. the IR is simpler) as well as rustc itself running faster (e.g. spending less time in typeck when checking keccak crate). Naturally the first class of changes have mean some regressions such as the beforementioned ripgrep.

The overall shape is very positive though.

@bors r+

**Comment by lqd** [comment]
And the benchmarks are 99.9% green :)

@bors retry #92000

**Comment by pnkfelix** [comment]
These results are consistent with what was [flagged in the PR run](https://github.com/rust-lang/rust/pull/92419#issuecomment-1003435331), and so I think @nagisa's [analysis with justification](https://github.com/rust-lang/rust/pull/92419#issuecomment-1003436337) still applies.

@rustbot label: +perf-regression-triaged
