### PR TITLE
Use proper impl self type for alias impl in rustdoc

### LINKED ISSUE #111420: Incorrect signature in documentation for implementation of generic alias
I tried this code:

```rust
// Cross Product
impl<T: Copy> Vector<T, 3> {
   // ✂️ snip ✂️ 
}
```

where `Vector` is

```rust
pub type Vector<T, const N: usize> = Matrix<T, N, 1>;
```

In the docs, this shows` impl<T: Copy)> Matrix<T, N, 1>` even though `N` no longer exists in this context, its been concretized to 3
image

If I change the implementation to use `Matrix` instead of the `Vector` alias, I see what I would expect. no more `N`

image

Project is [here](https://github.com/drewcassidy/vector-victor/tree/f697db6d35147366b52d78b6df6107eb838ccd36), with the specific impl [here](https://github.com/drewcassidy/vector-victor/blob/f697db6d35147366b52d78b6df6107eb838ccd36/src/matrix.rs#L336)

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: aarch64-apple-darwin
release: 1.69.0
LLVM version: 15.0.7

```

<details><summary>Backtrace</summary>
<p>

```
I don't seem to get anything and I don't know why
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
We don't want to use `type_of(type_alias)`, we want to use `type_of(impl)` -- this will give us the self type of the impl *properly substituted* in the case that it's an alias.

Fixes #111420

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -2414,14 +2414,15 @@ fn clean_impl<'tcx>(
     }
 
     let for_ = clean_ty(impl_.self_ty, cx);
-    let type_alias = for_.def_id(&cx.cache).and_then(|did| match tcx.def_kind(did) {
-        DefKind::TyAlias => Some(clean_middle_ty(
-            ty::Binder::dummy(tcx.type_of(did).subst_identity()),
```
Comment (compiler-errors) [inline src/librustdoc/clean/mod.rs:2419]: I guess alternatively we *could* keep using `type_of(alias_def_id)` here if we were passing it the right substs, but I don't think rustdoc needs to go through the whole effort of computing the correct substitutions for a type alias here, considering generic defaults and stuff like that.

Astconv does that for us by just calling `type_of(impl_def_id)`...
