### PR TITLE
Fix transmute::<T, U> where T requires a bigger alignment than U

### LINKED ISSUE #32947: Segmentation fault when transmuting simd vector temporary
This is a pretty subtle interaction of several things that produces code which causes a segmentation fault:
- A struct with `#[repr(simd)]`.
- A struct with a member.
- A method on that struct.
- Transmuting the result of a method call.

``` rust
#![feature(repr_simd)]

#[repr(simd)] // Without #[repr(simd)], it works fine.
pub struct Mu64(pub u64, pub u64, pub u64, pub u64);

pub struct Trouble {
    state: Mu64, // Without this field, it works fine.
}

impl Trouble {
    pub fn new() -> Trouble {
        Trouble {
            state: Mu64(1, 2, 3, 4),
        }
    }

    fn next(&self) -> Mu64 {
        Mu64(1, 2, 3, 4)
    }

    pub fn invoke_doom(&self) -> [u32; 8] {
        use std::mem::transmute;
        // transmute(Mu64(1, 2, 3, 4)) instead of transmute(self.next()) works
        // fine.
        unsafe { transmute(self.next()) }
    }
}

#[test]
fn this_causes_sigsegv() {
    let mut trouble = Trouble::new();
    println!("{}", trouble.invoke_doom()[0]);
}
```

Now `cargo test` crashes with a segmentation fault. (The test program that is, not Cargo.) `cargo test --release` runs fine. It could be that this is working as intended, and this is what I get for using unsafe code, but it certainly surprises me.

Workaround for now: use `transmute_copy` instead of `transmute`.

Version: rustc 1.9.0-nightly (a43eb4e77 2016-04-12). It also happened on an older nightly.

### PR DESCRIPTION
**Pull request by dotdash**
For transmute::<T, U> we simply pointercast the destination from a U
pointer to a T pointer, without providing any alignment information,
thus LLVM assumes that the destination is aligned to hold a value of
type T, which is not necessarily true. This can lead to LLVM emitting
machine instructions that assume said alignment, and thus cause aborts.

To fix this, we need to provide the actual alignment to store_operand()
and in turn to store() so they can set the proper alignment information
on the stores and LLVM can emit the proper machine instructions.

Fixes #32947

### CODE REVIEW

File: src/librustc_trans/base.rs [hunk 1]
```diff
@@ -523,26 +523,21 @@ pub fn call_memcpy<'a, 'tcx>(b: &Builder<'a, 'tcx>,
...
-    if t.is_structural() {
-        let llty = type_of::type_of(ccx, t);
-        let llsz = llsize_of(ccx, llty);
-        let llalign = type_of::align_of(ccx, t);
-        call_memcpy(bcx, dst, src, llsz, llalign as u32);
-    } else if common::type_is_fat_ptr(bcx.ccx, t) {
-        let (data, extra) = load_fat_ptr(bcx, src, t);
-        store_fat_ptr(bcx, data, extra, dst, t);
-    } else {
-        store_ty(bcx, load_ty(bcx, src, t), dst, t);
```
Comment (eddyb) [inline src/librustc_trans/base.rs]: Are these two other cases unreachable through MIR trans? Are they useless/problematic?

**Comment by eddyb** [comment]
r=me with an explanation on the simplification of `memcpy_ty`.

File: src/librustc_trans/base.rs (hunk 1 above)
Comment (dotdash) [inline src/librustc_trans/base.rs]: I might have overlooked a corner case in `coerce_unsized_into`, but I can't figure out how to actually trigger that code path. Using `Rc` seems not to go to memcpy_ty, and I somehow failed to make a custom type that allows unsized coercions. Will try next year

Comment (pnkfelix) [inline src/librustc_trans/base.rs]: @eddyb in your r=me remark, you're saying that you want something like a comment right here saying "there used to be other cases handled here, see discussion at #38670 ?)

Comment (eddyb) [inline src/librustc_trans/base.rs]: I don't think a comment is necessary (as opposed to the case where special cases would be added). The change makes sense if the other cases are not reachable due to how MIR trans would be structured, I just wanted to make sure we're certain that's the case.

Comment (dotdash) [inline src/librustc_trans/base.rs]: There are two places where `memcpy_ty` is used. One is `store_operand`, which I think should never hit anything but the memcpy case here, because the other two are handled via `Immediate` and `Pair` operands. The other is `coerce_unsized_into` which may call this with arbitrary types, but I think that's a pretty uncommon operation to begin with, and keeping those two cases here means adding align parameters to at more places.
