### PR TITLE
Deny capturing late-bound ty/const params in nested opaques

### LINKED ISSUE #131535: ICE: `WellFormed .. has escaping bound vars, so it cannot be wrapped in a dummy binder.`
auto-reduced (treereduce-rust):
````rust
#![feature(non_lifetime_binders)]
trait v0<> {}
fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}


````

original:
````rust
#![feature(non_lifetime_binders)]
trait v0<> {}
fn kind  :(v0<'_, v2 = impl v0<v4> + '_> impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}

````

Version information
````
rustc 1.83.0-nightly (0321e73d1 2024-10-11)
binary: rustc
commit-hash: 0321e73d1cb3f739caa806927344eca6f96257b5
commit-date: 2024-10-11
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: missing parameters for function definition
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:8
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |        ^
  |
help: add a parameter list
  |
3 | fn kind()  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |        ++

error: return types are denoted using `->`
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:10
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |          ^
  |
help: use `->` instead
  |
3 | fn kind -> (v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |         ~~

error: expected one of `!`, `)`, `+`, `,`, or `::`, found keyword `impl`
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:21
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                    -^^^^ expected one of `!`, `)`, `+`, `,`, or `::`
  |                    |
  |                    help: missing `,`

error[E0106]: missing lifetime specifiers
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:15
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |               ^^                    ^^                     ^^ expected named lifetime parameter
  |               |                     |
  |               |                     expected named lifetime parameter
  |               expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
  |
3 | fn kind  :(v0<'static, > impl for<v4> v0<'static, v2 = impl v0<v4> + 'static>) {}
  |               ~~~~~~~                    ~~~~~~~                     ~~~~~~~

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:1:12
  |
1 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: trait `v0` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^ help: convert the identifier to upper camel case (notice the capitalization): `V0`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: type parameter `v4` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:30
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                              ^^ help: convert the identifier to upper camel case (notice the capitalization): `V4`

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:67
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                                                   ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs`

warning: trait objects without an explicit `dyn` are deprecated
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:12
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |            ^^^^^^^^
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
  = note: `#[warn(bare_trait_objects)]` on by default
help: if this is a dyn-compatible trait, use `dyn`
  |
3 | fn kind  :(dyn v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |            +++

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:12
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |            ^^------ help: remove the unnecessary generics
  |            |
  |            expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:34
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                  ^^--------------------------- help: remove the unnecessary generics
  |                                  |
  |                                  expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^

error[E0220]: associated type `v2` not found for `v0`
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:41
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                         ^^ associated type `v2` not found

error[E0107]: trait takes 0 generic arguments but 1 generic argument was supplied
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:3:51
  |
3 | fn kind  :(v0<'_, > impl for<v4> v0<'_, v2 = impl v0<v4> + '_>) {}
  |                                                   ^^---- help: remove the unnecessary generics
  |                                                   |
  |                                                   expected 0 generic arguments
  |
note: trait defined here, with 0 generic parameters
 --> /tmp/icemaker_global_tempdir.iM3UDTgNb65b/rustc_testrunner_tmpdir_reporting.HNNM9m0OzIzi/mvce.rs:2:7
  |
2 | trait v0<> {}
  |       ^^

thread 'rustc' panicked at compiler/rustc_middle/src/ty/predicate.rs:489:9:
`WellFormed(^2_"v4")` has escaping bound vars, so it cannot be wrapped in a dummy binder.
stack backtrace:
   0:     0x7ad8ec3de57a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h0c0d2e67483a7ce1
   1:     0x7ad8ecc034a6 - core::fmt::write::h19fbfdd1fd25c23b
   2:     0x7ad8edec4091 - std::io::Write::write_fmt::hf8ab2da8ebc932a0
   3:     0x7ad8ec3de3d2 - std::sys::backtrace::BacktraceLock::print::h3d864635116d695a
   4:     0x7ad8ec3e08a6 - std::panicking::default_hook::{{closure}}::h2aa94d113a45cc15
   5:     0x7ad8ec3e06f0 - std::panicking::default_hook::h97fbe8692dbb54b4
   6:     0x7ad8eb4331df - std[b2c81c0a9485f2e4]::panicking::update_hook::<alloc[c9d20cda7901ded3]::boxed::Box<rustc_driver_impl[8c3cd927c140555]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7ad8ec3e0fb8 - std::panicking::rust_panic_with_hook::hc4ff1f67175d51bb
   8:     0x7ad8ec3e0d8a - std::panicking::begin_panic_handler::{{closure}}::h064adafafa3d3d91
   9:     0x7ad8ec3dea29 - std::sys::backtrace::__rust_end_short_backtrace::hfd346037bc0f3979
  10:     0x7ad8ec3e0a4c - rust_begin_unwind
  11:     0x7ad8e9e4cd00 - core::panicking::panic_fmt::hcd11b748a515a987
  12:     0x7ad8ee656148 - <rustc_middle[3ffb7b0bf421448c]::ty::predicate::Predicate as rustc_type_ir[89eb6eb643500842]::upcast::UpcastFrom<rustc_middle[3ffb7b0bf421448c]::ty::context::TyCtxt, rustc_type_ir[89eb6eb643500842]::predicate_kind::PredicateKind<rustc_middle[3ffb7b0bf421448c]::ty::context::TyCtxt>>>::upcast_from.cold
  13:     0x7ad8eb4fe177 - <rustc_infer[e8941da21ab8c6f3]::traits::Obligation<rustc_middle[3ffb7b0bf421448c]::ty::predicate::Predicate>>::with_depth::<rustc_type_ir[89eb6eb643500842]::predicate_kind::PredicateKind<rustc_middle[3ffb7b0bf421448c]::ty::context::TyCtxt>>
  14:     0x7ad8eb6171fe - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_ty
  15:     0x7ad8eb5c9bed - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_generic_args
  16:     0x7ad8eb526bb0 - rustc_hir[a68747c3d7069c6f]::intravisit::walk_poly_trait_ref::<rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck>
  17:     0x7ad8eb61778e - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_ty
  18:     0x7ad8eb5c9ce4 - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_generic_args
  19:     0x7ad8eb526bb0 - rustc_hir[a68747c3d7069c6f]::intravisit::walk_poly_trait_ref::<rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck>
  20:     0x7ad8eb61778e - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_ty
  21:     0x7ad8eb6174d1 - <rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check::HirWfCheck as rustc_hir[a68747c3d7069c6f]::intravisit::Visitor>::visit_ty
  22:     0x7ad8eb616b8e - rustc_hir_analysis[94092c3b015c4ea3]::hir_wf_check::diagnostic_hir_wf_check
  23:     0x7ad8ebed55cc - rustc_query_impl[fa1174e4896087c1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fa1174e4896087c1]::query_impl::diagnostic_hir_wf_check::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 8usize]>>
  24:     0x7ad8ebeba6c3 - <rustc_query_impl[fa1174e4896087c1]::query_impl::diagnostic_hir_wf_check::dynamic_query::{closure#2} as core[15204f05ba262a1b]::ops::function::FnOnce<(rustc_middle[3ffb7b0bf421448c]::ty::context::TyCtxt, (rustc_middle[3ffb7b0bf421448c]::ty::predicate::Predicate, rustc_middle[3ffb7b0bf421448c]::traits::WellFormedLoc))>>::call_once
  25:     0x7ad8ebe341ba - rustc_query_system[3cba1a04b5b15b8a]::query::plumbing::try_execute_query::<rustc_query_impl[fa1174e4896087c1]::DynamicConfig<rustc_query_system[3cba1a04b5b15b8a]::query::caches::DefaultCache<(rustc_middle[3ffb7b0bf421448c]::ty::predicate::Predicate, rustc_middle[3ffb7b0bf421448c]::traits::WellFormedLoc), rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[fa1174e4896087c1]::plumbing::QueryCtxt, false>
  26:     0x7ad8ebf15af5 - rustc_query_impl[fa1174e4896087c1]::query_impl::diagnostic_hir_wf_check::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7ad8ec206ac9 - <rustc_trait_selection[9580d8cfdaacc399]::error_reporting::TypeErrCtxt>::report_selection_error
  28:     0x7ad8ec28809b - <rustc_trait_selection[9580d8cfdaacc399]::error_reporting::TypeErrCtxt>::report_fulfillment_error
  29:     0x7ad8ec24f277 - <rustc_trait_selection[9580d8cfdaacc399]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
  30:     0x7ad8ecdf114d - <rustc_trait_selection[9580d8cfdaacc399]::traits::engine::ObligationCtxt<rustc_trait_selection[9580d8cfdaacc399]::traits::FulfillmentError>>::assumed_wf_types_and_report_errors
  31:     0x7ad8ed380ef5 - rustc_hir_analysis[94092c3b015c4ea3]::check::wfcheck::check_item_fn
  32:     0x7ad8ea5c061f - rustc_hir_analysis[94092c3b015c4ea3]::check::wfcheck::check_well_formed
  33:     0x7ad8ed5cee6b - rustc_query_impl[fa1174e4896087c1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fa1174e4896087c1]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7ad8ed5ce5d1 - rustc_query_system[3cba1a04b5b15b8a]::query::plumbing::try_execute_query::<rustc_query_impl[fa1174e4896087c1]::DynamicConfig<rustc_query_system[3cba1a04b5b15b8a]::query::caches::VecCache<rustc_span[6af75d8d312d6eec]::def_id::LocalDefId, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fa1174e4896087c1]::plumbing::QueryCtxt, false>
  35:     0x7ad8ed5ce250 - rustc_query_impl[fa1174e4896087c1]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7ad8ed5cf0ff - rustc_hir_analysis[94092c3b015c4ea3]::check::wfcheck::check_mod_type_wf
  37:     0x7ad8ed5cef25 - rustc_query_impl[fa1174e4896087c1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fa1174e4896087c1]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7ad8ed9b7b7b - rustc_query_system[3cba1a04b5b15b8a]::query::plumbing::try_execute_query::<rustc_query_impl[fa1174e4896087c1]::DynamicConfig<rustc_query_system[3cba1a04b5b15b8a]::query::caches::DefaultCache<rustc_span[6af75d8d312d6eec]::def_id::LocalModDefId, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fa1174e4896087c1]::plumbing::QueryCtxt, false>
  39:     0x7ad8ed9b792d - rustc_query_impl[fa1174e4896087c1]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7ad8ed0340fb - rustc_hir_analysis[94092c3b015c4ea3]::check_crate
  41:     0x7ad8ed030e57 - rustc_interface[b91e754c6773c007]::passes::run_required_analyses
  42:     0x7ad8ed71fb1e - rustc_interface[b91e754c6773c007]::passes::analysis
  43:     0x7ad8ed71faf1 - rustc_query_impl[fa1174e4896087c1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fa1174e4896087c1]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>
  44:     0x7ad8edb26dae - rustc_query_system[3cba1a04b5b15b8a]::query::plumbing::try_execute_query::<rustc_query_impl[fa1174e4896087c1]::DynamicConfig<rustc_query_system[3cba1a04b5b15b8a]::query::caches::SingleCache<rustc_middle[3ffb7b0bf421448c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fa1174e4896087c1]::plumbing::QueryCtxt, false>
  45:     0x7ad8edb26a8f - rustc_query_impl[fa1174e4896087c1]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7ad8ed94edde - rustc_interface[b91e754c6773c007]::interface::run_compiler::<core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>, rustc_driver_impl[8c3cd927c140555]::run_compiler::{closure#0}>::{closure#1}
  47:     0x7ad8eda32d10 - std[b2c81c0a9485f2e4]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[b91e754c6773c007]::util::run_in_thread_with_globals<rustc_interface[b91e754c6773c007]::util::run_in_thread_pool_with_globals<rustc_interface[b91e754c6773c007]::interface::run_compiler<core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>, rustc_driver_impl[8c3cd927c140555]::run_compiler::{closure#0}>::{closure#1}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>::{closure#0}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>
  48:     0x7ad8eda333d7 - <<std[b2c81c0a9485f2e4]::thread::Builder>::spawn_unchecked_<rustc_interface[b91e754c6773c007]::util::run_in_thread_with_globals<rustc_interface[b91e754c6773c007]::util::run_in_thread_pool_with_globals<rustc_interface[b91e754c6773c007]::interface::run_compiler<core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>, rustc_driver_impl[8c3cd927c140555]::run_compiler::{closure#0}>::{closure#1}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>::{closure#0}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[15204f05ba262a1b]::result::Result<(), rustc_span[6af75d8d312d6eec]::ErrorGuaranteed>>::{closure#1} as core[15204f05ba262a1b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7ad8eda342c1 - std::sys::pal::unix::thread::Thread::new::thread_start::h4694c2beab690665
  50:     0x7ad8ef1c739d - <unknown>
  51:     0x7ad8ef24c49c - <unknown>
  52:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (0321e73d1 2024-10-11) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [diagnostic_hir_wf_check] performing HIR wf-checking for predicate `Binder { value: TraitPredicate(<dyn v0 as core::marker::Sized>, polarity:Positive), bound_vars: [] }` at item `Param { function: DefId(0:4 ~ mvce[ff9f]::kind), param_idx: 0 }`
#1 [check_well_formed] checking that `kind` is well-formed
end of query stack
error: aborting due to 9 previous errors; 4 warnings emitted

Some errors have detailed explanations: E0106, E0107, E0220, E0601.
For more information about an error, try `rustc --explain E0106`.

```

</p>
</details>

@rustbot label +F-non_lifetime_binders

### LINKED ISSUE #131637: ICE: `Normalizing Binder  .. without wrapping in a Binder`
snippet:
````rust
#![feature(non_lifetime_binders)]
trait Trait<Type> {
    type Type;

    fn method(&self) -> impl for<T> Trait<impl Trait<T>>;
}

````

Version information
````
rustc 1.83.0-nightly (ef4e8259b 2024-10-12)
binary: rustc
commit-hash: ef4e8259b5016d85e261587b605028b2ff06c13d
commit-date: 2024-10-12
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(non_lifetime_binders)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0666]: nested `impl Trait` is not allowed
 --> /tmp/icemaker_global_tempdir.FSJ0vzRiWJPZ/rustc_testrunner_tmpdir_reporting.H5iY5qnka74L/mvce.rs:4:43
  |
4 |     fn method(&self) -> impl for<T> Trait<impl Trait<T>>;
  |                         ------------------^^^^^^^^^^^^^-
  |                         |                 |
  |                         |                 nested `impl Trait` here
  |                         outer `impl Trait`

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(non_lifetime_binders)
  |         ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.FSJ0vzRiWJPZ/rustc_testrunner_tmpdir_reporting.H5iY5qnka74L/mvce.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.FSJ0vzRiWJPZ/rustc_testrunner_tmpdir_reporting.H5iY5qnka74L/mvce.rs`

thread 'rustc' panicked at /rustc/ef4e8259b5016d85e261587b605028b2ff06c13d/compiler/rustc_trait_selection/src/traits/normalize.rs:152:9:
Normalizing Binder { value: TraitPredicate(<impl Trait<T> as Trait<T>>, polarity:Positive), bound_vars: [] } without wrapping in a `Binder`
stack backtrace:
   0:     0x71709b5d1a1a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb71c2cbac72cdb5b
   1:     0x71709be034a6 - core::fmt::write::heb09cf10dd28415d
   2:     0x71709d01d551 - std::io::Write::write_fmt::he7930bf346a8968a
   3:     0x71709b5d1872 - std::sys::backtrace::BacktraceLock::print::h0a899fd0a1901c8e
   4:     0x71709b5d3d46 - std::panicking::default_hook::{{closure}}::h18bcfec0b7bcc716
   5:     0x71709b5d3b90 - std::panicking::default_hook::h55fad4ebc08cd150
   6:     0x71709a628e7f - std[2d7f46ec46e78cda]::panicking::update_hook::<alloc[e7629bc0fb789452]::boxed::Box<rustc_driver_impl[3fef95598012341d]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x71709b5d4458 - std::panicking::rust_panic_with_hook::h1948796bede27b1d
   8:     0x71709b5d422a - std::panicking::begin_panic_handler::{{closure}}::h0990fea1223f6893
   9:     0x71709b5d1ec9 - std::sys::backtrace::__rust_end_short_backtrace::hf37c728b4c065dea
  10:     0x71709b5d3eec - rust_begin_unwind
  11:     0x7170982ec730 - core::panicking::panic_fmt::h44a7f0c2b4452277
  12:     0x71709cd02233 - rustc_trait_selection[8ec19655a831e168]::traits::normalize::normalize_with_depth_to::<rustc_middle[36f32f9ecfcbfe2]::ty::predicate::Clause>::{closure#0}
  13:     0x71709cd01ca4 - <rustc_trait_selection[8ec19655a831e168]::traits::engine::ObligationCtxt<rustc_trait_selection[8ec19655a831e168]::traits::FulfillmentError>>::normalize::<rustc_middle[36f32f9ecfcbfe2]::ty::predicate::Clause>
  14:     0x71709cd01aad - <rustc_hir_analysis[32b0d2be82dc9eb]::check::wfcheck::WfCheckingCtxt>::normalize::<rustc_middle[36f32f9ecfcbfe2]::ty::predicate::Clause>
  15:     0x71709c5e6103 - rustc_hir_analysis[32b0d2be82dc9eb]::check::wfcheck::check_associated_item
  16:     0x71709977e4a6 - rustc_hir_analysis[32b0d2be82dc9eb]::check::wfcheck::check_well_formed
  17:     0x71709c8428fd - rustc_query_impl[2ff63d9f917ec697]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2ff63d9f917ec697]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>
  18:     0x71709c84205f - rustc_query_system[82bc41041ee47c07]::query::plumbing::try_execute_query::<rustc_query_impl[2ff63d9f917ec697]::DynamicConfig<rustc_query_system[82bc41041ee47c07]::query::caches::VecCache<rustc_span[3e9061d2e044f211]::def_id::LocalDefId, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[2ff63d9f917ec697]::plumbing::QueryCtxt, false>
  19:     0x71709c841cd0 - rustc_query_impl[2ff63d9f917ec697]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  20:     0x71709c84297d - rustc_middle[36f32f9ecfcbfe2]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[82bc41041ee47c07]::query::caches::VecCache<rustc_span[3e9061d2e044f211]::def_id::LocalDefId, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>, ()>
  21:     0x71709c842edc - rustc_hir_analysis[32b0d2be82dc9eb]::check::wfcheck::check_mod_type_wf
  22:     0x71709c8429a5 - rustc_query_impl[2ff63d9f917ec697]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2ff63d9f917ec697]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>
  23:     0x71709c83c27b - rustc_query_system[82bc41041ee47c07]::query::plumbing::try_execute_query::<rustc_query_impl[2ff63d9f917ec697]::DynamicConfig<rustc_query_system[82bc41041ee47c07]::query::caches::DefaultCache<rustc_span[3e9061d2e044f211]::def_id::LocalModDefId, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[2ff63d9f917ec697]::plumbing::QueryCtxt, false>
  24:     0x71709c83c02d - rustc_query_impl[2ff63d9f917ec697]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  25:     0x71709c26da3b - rustc_hir_analysis[32b0d2be82dc9eb]::check_crate
  26:     0x71709c26a797 - rustc_interface[2b62aadc68a12e2c]::passes::run_required_analyses
  27:     0x71709cc8c39e - rustc_interface[2b62aadc68a12e2c]::passes::analysis
  28:     0x71709cc8c371 - rustc_query_impl[2ff63d9f917ec697]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2ff63d9f917ec697]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>
  29:     0x71709ccca16e - rustc_query_system[82bc41041ee47c07]::query::plumbing::try_execute_query::<rustc_query_impl[2ff63d9f917ec697]::DynamicConfig<rustc_query_system[82bc41041ee47c07]::query::caches::SingleCache<rustc_middle[36f32f9ecfcbfe2]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[2ff63d9f917ec697]::plumbing::QueryCtxt, false>
  30:     0x71709ccc9e4f - rustc_query_impl[2ff63d9f917ec697]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:     0x71709cb32c1b - rustc_interface[2b62aadc68a12e2c]::interface::run_compiler::<core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>, rustc_driver_impl[3fef95598012341d]::run_compiler::{closure#0}>::{closure#1}
  32:     0x71709cc02f14 - std[2d7f46ec46e78cda]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[2b62aadc68a12e2c]::util::run_in_thread_with_globals<rustc_interface[2b62aadc68a12e2c]::util::run_in_thread_pool_with_globals<rustc_interface[2b62aadc68a12e2c]::interface::run_compiler<core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>, rustc_driver_impl[3fef95598012341d]::run_compiler::{closure#0}>::{closure#1}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>::{closure#0}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>
  33:     0x71709cc03328 - <<std[2d7f46ec46e78cda]::thread::Builder>::spawn_unchecked_<rustc_interface[2b62aadc68a12e2c]::util::run_in_thread_with_globals<rustc_interface[2b62aadc68a12e2c]::util::run_in_thread_pool_with_globals<rustc_interface[2b62aadc68a12e2c]::interface::run_compiler<core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>, rustc_driver_impl[3fef95598012341d]::run_compiler::{closure#0}>::{closure#1}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>::{closure#0}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5b4c807c5a0efff6]::result::Result<(), rustc_span[3e9061d2e044f211]::ErrorGuaranteed>>::{closure#1} as core[5b4c807c5a0efff6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x71709cc03deb - std::sys::pal::unix::thread::Thread::new::thread_start::h67d76ed3602b4ec2
  35:     0x71709e3f339d - <unknown>
  36:     0x71709e47849c - <unknown>
  37:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (ef4e8259b 2024-10-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(non_lifetime_binders) -Z dump-mir-dir=dir

query stack during panic:
#0 [check_well_formed] checking that `Trait::method` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0601, E0666.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-non_lifetime_binders

### LINKED ISSUE #132530: ICE: `escaping bound type during canonicalization`
snippet:
````rust
#![feature(non_lifetime_binders)]

trait Trait<'a, A, B> {
    type Assoc<'a> = i32;
}

fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
    16
}

````

Version information
````
rustc 1.84.0-nightly (588a42035 2024-11-02)
binary: rustc
commit-hash: 588a4203508ed7c76750c96b482641261630ed36
commit-date: 2024-11-02
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/588a4203508ed7c76750c96b482641261630ed36/compiler/rustc_infer/src/infer/canonical/canonicalizer.rs#L413-L425

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:4:16
  |
3 | trait Trait<'a, A, B> {
  |             -- first declared here
4 |     type Assoc<'a> = i32;
  |                ^^ lifetime `'a` already in scope

error[E0106]: missing lifetime specifiers
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:7:34
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                                  ^                      ^ expected named lifetime parameter
  |                                  |
  |                                  expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
  |
7 | fn produce() -> impl for<T> Trait<'static, (), Assoc = impl Trait<'static, T>> {
  |                                   ++++++++                        ++++++++

error[E0658]: associated type defaults are unstable
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:4:5
  |
4 |     type Assoc<'a> = i32;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #29661 <https://github.com/rust-lang/rust/issues/29661> for more information
  = help: add `#![feature(associated_type_defaults)]` to the crate attributes to enable
  = note: this compiler was built on 2024-11-02; consider upgrading it if it is out of date

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:1:12
  |
1 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:9:2
  |
9 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs`

error[E0107]: trait takes 2 generic arguments but 1 generic argument was supplied
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:7:29
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                             ^^^^^ -- supplied 1 generic argument
  |                             |
  |                             expected 2 generic arguments
  |
note: trait defined here, with 2 generic parameters: `A`, `B`
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:3:7
  |
3 | trait Trait<'a, A, B> {
  |       ^^^^^     -  -
help: add missing generic argument
  |
7 | fn produce() -> impl for<T> Trait<(), B, Assoc = impl Trait<T>> {
  |                                     +++

error[E0107]: missing generics for associated type `Trait::Assoc`
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:7:39
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                                       ^^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'_`
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:4:10
  |
4 |     type Assoc<'a> = i32;
  |          ^^^^^ --
help: add missing lifetime argument
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc<'_> = impl Trait<T>> {
  |                                            ++++

error[E0107]: trait takes 2 generic arguments but 1 generic argument was supplied
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:7:52
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T>> {
  |                                                    ^^^^^ - supplied 1 generic argument
  |                                                    |
  |                                                    expected 2 generic arguments
  |
note: trait defined here, with 2 generic parameters: `A`, `B`
 --> /tmp/icemaker_global_tempdir.zyPSUovK6G46/rustc_testrunner_tmpdir_reporting.xCCgbBIdqPg5/mvce.rs:3:7
  |
3 | trait Trait<'a, A, B> {
  |       ^^^^^     -  -
help: add missing generic argument
  |
7 | fn produce() -> impl for<T> Trait<(), Assoc = impl Trait<T, B>> {
  |                                                           +++

error: internal compiler error: compiler/rustc_infer/src/infer/canonical/canonicalizer.rs:419:21: escaping bound type during canonicalization

thread 'rustc' panicked at compiler/rustc_infer/src/infer/canonical/canonicalizer.rs:419:21:
Box<dyn Any>
stack backtrace:
   0:     0x7c70fd05720a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb6cd0a6bac89b6a6
   1:     0x7c70fd8040ca - core::fmt::write::haf33c0c90f8a330f
   2:     0x7c70fe7de991 - std::io::Write::write_fmt::h8e68b0ac6f9ed075
   3:     0x7c70fd057062 - std::sys::backtrace::BacktraceLock::print::hfcb510b62adfb854
   4:     0x7c70fd059566 - std::panicking::default_hook::{{closure}}::h04e002fdca100125
   5:     0x7c70fd0593b0 - std::panicking::default_hook::h4e6c1c73a1b39936
   6:     0x7c70fc0dcc49 - std[938f00e4f3f8ec0a]::panicking::update_hook::<alloc[f5b601f10d0c9e52]::boxed::Box<rustc_driver_impl[f21e318f0b376187]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7c70fd059c78 - std::panicking::rust_panic_with_hook::h7c34462f21943817
   8:     0x7c70fc116421 - std[938f00e4f3f8ec0a]::panicking::begin_panic::<rustc_errors[3e6fc96cf6e3ecf4]::ExplicitBug>::{closure#0}
   9:     0x7c70fc1093f6 - std[938f00e4f3f8ec0a]::sys::backtrace::__rust_end_short_backtrace::<std[938f00e4f3f8ec0a]::panicking::begin_panic<rustc_errors[3e6fc96cf6e3ecf4]::ExplicitBug>::{closure#0}, !>
  10:     0x7c70fc10918e - std[938f00e4f3f8ec0a]::panicking::begin_panic::<rustc_errors[3e6fc96cf6e3ecf4]::ExplicitBug>
  11:     0x7c70fc11fff1 - <rustc_errors[3e6fc96cf6e3ecf4]::diagnostic::BugAbort as rustc_errors[3e6fc96cf6e3ecf4]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7c70fc7994f3 - rustc_middle[b1d1e394adbcd929]::util::bug::opt_span_bug_fmt::<rustc_span[d3d4eeacb399f824]::span_encoding::Span>::{closure#0}
  13:     0x7c70fc77faea - rustc_middle[b1d1e394adbcd929]::ty::context::tls::with_opt::<rustc_middle[b1d1e394adbcd929]::util::bug::opt_span_bug_fmt<rustc_span[d3d4eeacb399f824]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7c70fc77f97b - rustc_middle[b1d1e394adbcd929]::ty::context::tls::with_context_opt::<rustc_middle[b1d1e394adbcd929]::ty::context::tls::with_opt<rustc_middle[b1d1e394adbcd929]::util::bug::opt_span_bug_fmt<rustc_span[d3d4eeacb399f824]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7c70fa8cdf10 - rustc_middle[b1d1e394adbcd929]::util::bug::bug_fmt
  16:     0x7c70fe045364 - <rustc_infer[4c18d0e6e4ed5823]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[9c2cdde8392b485]::fold::TypeFolder<rustc_middle[b1d1e394adbcd929]::ty::context::TyCtxt>>::fold_ty
  17:     0x7c70fb32c660 - <rustc_trait_selection[f44409a29212fa61]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  18:     0x7c70fdbda7df - <rustc_trait_selection[f44409a29212fa61]::traits::fulfill::FulfillProcessor as rustc_data_structures[8ffdaab02f4582f3]::obligation_forest::ObligationProcessor>::process_obligation
  19:     0x7c70fd80f3ad - <rustc_data_structures[8ffdaab02f4582f3]::obligation_forest::ObligationForest<rustc_trait_selection[f44409a29212fa61]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[f44409a29212fa61]::traits::fulfill::FulfillProcessor>
  20:     0x7c70fd8d7849 - <rustc_hir_typeck[64dee917abf8f083]::fn_ctxt::FnCtxt>::coerce
  21:     0x7c70fe565dc7 - <rustc_hir_typeck[64dee917abf8f083]::fn_ctxt::FnCtxt>::check_block_with_expected
  22:     0x7c70fe56be70 - <rustc_hir_typeck[64dee917abf8f083]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:     0x7c70fdae945b - rustc_hir_typeck[64dee917abf8f083]::check::check_fn
  24:     0x7c70fdadef35 - rustc_hir_typeck[64dee917abf8f083]::typeck
  25:     0x7c70fdade8d3 - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7c70fdeaa4c1 - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::VecCache<rustc_span[d3d4eeacb399f824]::def_id::LocalDefId, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  27:     0x7c70fdea898d - rustc_query_impl[a29eb052c37ab918]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7c70fe1b892b - rustc_middle[b1d1e394adbcd929]::query::plumbing::query_get_at::<rustc_query_system[3c80327c1b2e9be7]::query::caches::VecCache<rustc_span[d3d4eeacb399f824]::def_id::LocalDefId, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>>
  29:     0x7c70fe8197be - rustc_hir_analysis[4467b4076426cba3]::collect::type_of::type_of_opaque
  30:     0x7c70fe819711 - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7c70fd9b26aa - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::DefIdCache<rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  32:     0x7c70fea0f2b5 - rustc_query_impl[a29eb052c37ab918]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7c70fdd5c500 - rustc_middle[b1d1e394adbcd929]::query::plumbing::query_get_at::<rustc_query_system[3c80327c1b2e9be7]::query::caches::DefIdCache<rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>>
  34:     0x7c70fac14889 - rustc_hir_analysis[4467b4076426cba3]::collect::type_of::type_of
  35:     0x7c70fd9b3a2a - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>
  36:     0x7c70fd9b26aa - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::DefIdCache<rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  37:     0x7c70fd9b223f - rustc_query_impl[a29eb052c37ab918]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7c70fdd5c500 - rustc_middle[b1d1e394adbcd929]::query::plumbing::query_get_at::<rustc_query_system[3c80327c1b2e9be7]::query::caches::DefIdCache<rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 8usize]>>>
  39:     0x7c70fe8296c4 - rustc_hir_analysis[4467b4076426cba3]::check::check::check_item_type
  40:     0x7c70fb1fcba3 - rustc_hir_analysis[4467b4076426cba3]::check::wfcheck::check_well_formed
  41:     0x7c70fe3acb07 - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>
  42:     0x7c70fe3ac258 - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::VecCache<rustc_span[d3d4eeacb399f824]::def_id::LocalDefId, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  43:     0x7c70fe3abed0 - rustc_query_impl[a29eb052c37ab918]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7c70fe3acb87 - rustc_middle[b1d1e394adbcd929]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[3c80327c1b2e9be7]::query::caches::VecCache<rustc_span[d3d4eeacb399f824]::def_id::LocalDefId, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>, ()>
  45:     0x7c70fe3ad134 - rustc_hir_analysis[4467b4076426cba3]::check::wfcheck::check_mod_type_wf
  46:     0x7c70fe3acbaf - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>
  47:     0x7c70fe3a61bd - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::DefaultCache<rustc_span[d3d4eeacb399f824]::def_id::LocalModDefId, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  48:     0x7c70fe3a5f58 - rustc_query_impl[a29eb052c37ab918]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  49:     0x7c70fdea6265 - rustc_hir_analysis[4467b4076426cba3]::check_crate
  50:     0x7c70fdd4324a - rustc_interface[71aa3b1bf0e9b32c]::passes::run_required_analyses
  51:     0x7c70fe5f709e - rustc_interface[71aa3b1bf0e9b32c]::passes::analysis
  52:     0x7c70fe5f706f - rustc_query_impl[a29eb052c37ab918]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a29eb052c37ab918]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>
  53:     0x7c70fe788e2e - rustc_query_system[3c80327c1b2e9be7]::query::plumbing::try_execute_query::<rustc_query_impl[a29eb052c37ab918]::DynamicConfig<rustc_query_system[3c80327c1b2e9be7]::query::caches::SingleCache<rustc_middle[b1d1e394adbcd929]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a29eb052c37ab918]::plumbing::QueryCtxt, false>
  54:     0x7c70fe788b0e - rustc_query_impl[a29eb052c37ab918]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  55:     0x7c70fe67421d - rustc_interface[71aa3b1bf0e9b32c]::interface::run_compiler::<core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>, rustc_driver_impl[f21e318f0b376187]::run_compiler::{closure#0}>::{closure#1}
  56:     0x7c70fe6f3010 - std[938f00e4f3f8ec0a]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[71aa3b1bf0e9b32c]::util::run_in_thread_with_globals<rustc_interface[71aa3b1bf0e9b32c]::util::run_in_thread_pool_with_globals<rustc_interface[71aa3b1bf0e9b32c]::interface::run_compiler<core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>, rustc_driver_impl[f21e318f0b376187]::run_compiler::{closure#0}>::{closure#1}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>::{closure#0}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>
  57:     0x7c70fe6f342b - <<std[938f00e4f3f8ec0a]::thread::Builder>::spawn_unchecked_<rustc_interface[71aa3b1bf0e9b32c]::util::run_in_thread_with_globals<rustc_interface[71aa3b1bf0e9b32c]::util::run_in_thread_pool_with_globals<rustc_interface[71aa3b1bf0e9b32c]::interface::run_compiler<core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>, rustc_driver_impl[f21e318f0b376187]::run_compiler::{closure#0}>::{closure#1}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>::{closure#0}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[87cd10b3002d899c]::result::Result<(), rustc_span[d3d4eeacb399f824]::ErrorGuaranteed>>::{closure#1} as core[87cd10b3002d899c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7c70fe6f3ef9 - std::sys::pal::unix::thread::Thread::new::thread_start::h2150c7c4a48ccbb3
  59:     0x7c70ffef939d - <unknown>
  60:     0x7c70fff7e49c - <unknown>
  61:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.84.0-nightly (588a42035 2024-11-02) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `produce`
#1 [type_of_opaque] computing type of opaque `produce::{opaque#0}`
end of query stack
error: aborting due to 8 previous errors; 1 warning emitted

Some errors have detailed explanations: E0106, E0107, E0496, E0601, E0658.
For more information about an error, try `rustc --explain E0106`.

```

</p>
</details>

@rustbot label +F-non_lifetime_binders

### PR DESCRIPTION
**Pull request by compiler-errors**
First, this reverts a7f609504c92c9912b61025ae26a5404d3ee4311. I can't exactly remember why I approved this specific bit of https://github.com/rust-lang/rust/pull/132466; specifically, I don't know that the purpose of that commit is, and afaict we will never have an opaque that captures late-bound params through a const because opaques can't be used inside of anon consts. Am I missing something @cjgillot? Since I can't see a case where this matters, and no tests seem to fail.

The second commit adds a `deny_late_regions: bool` to distinguish `Scope::LateBoundary` which should deny *any* late-bound params or just ty/consts. Then, when resolving opaques we wrap ourselves in a `Scope::LateBoundary { deny_late_regions: false }` so that we deny late-bound ty/const, which fixes a bunch of ICEs that all vaguely look like `impl for<T> Trait<Assoc = impl OtherTrait<T>>`.

I guess this could be achieved other ways; for example, with a different scope kind, or maybe we could just reuse `Scope::Opaque`. But this seems a bit more verbose. I'm open to feedback anyways.

Fixes #131535
Fixes #131637
Fixes #132530 

I opted to remove those crashes tests ^ without adding them as regular tests, since they're basically triggering uninteresting late-bound ICEs far off in the trait solver, and the reason that existing tests such as `tests/ui/type-alias-impl-trait/non-lifetime-binder-in-constraint.rs` don't ICE are kinda just coincidental (i.e. due to a missing impl block). I don't really feel motivated to add random permutations to tests just to exercise non-lifetime binders.

r? cjgillot

### CODE REVIEW

File: tests/ui/type-alias-impl-trait/non-lifetime-binder.rs [hunk 1]
```diff
@@ -5,6 +5,7 @@ trait Trait<T> {}
 
 fn f() -> impl for<T> Trait<impl Trait<T>> {}
 //~^ ERROR nested `impl Trait` is not allowed
-//~| ERROR the trait bound `(): Trait<impl Trait<T>>` is not satisfied
+//~| ERROR the trait bound `(): Trait<impl Trait<{type error}>>` is not satisfied
```
Comment (compiler-errors) [inline tests/ui/type-alias-impl-trait/non-lifetime-binder.rs:8]: This error message sucks, but also it's the same error message we'd get from something like `impl Trait<impl Trait<Missing>>`, and really has nothing to do with this test other than now we begin resolving the late-bound `T` to error since it crosses a late-bound scope. 

The predicate itself doesn't reference errors, but when we render an opaque using its bounds, we'll render `{type error}`. We could suppress it, but also I don't think it needs to be fixed here.

**Comment by cjgillot** [comment]
For https://github.com/rust-lang/rust/commit/a7f609504c92c9912b61025ae26a5404d3ee4311, I merely reasoned by symmetry with `resolve_lifetime_ref`. I couldn't convinced myself that a `LateBoundary` was impossible, so I preventively wrote that commit.

But your solution looks cleaner.

@bors r+
