### PR TITLE
rustdoc: Fix doctest heuristic for main fn wrapping

### LINKED ISSUE #140412: Regression in doctest compile_fail detection with global_asm!
~~~markdown
```rust,compile_fail
fn main() {}
core::arch::global_asm!("", in(reg) 5);
```
~~~

I expected to see this happen: This should pass `rustdoc --test` because the example generates an error ``  the `in` operand cannot be used with `global_asm!` ``

Instead, this happened: This fails with `rustdoc --test` because the example is erroneously being treated as compiling successfully.

This appears to be a regression due to https://github.com/rust-lang/rust/pull/140220
cc @GuillaumeGomez 

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (25cdf1f67 2025-04-28)
binary: rustc
commit-hash: 25cdf1f67463c9365d8d83778c933ec7480e940b
commit-date: 2025-04-28
host: x86_64-apple-darwin
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### PR DESCRIPTION
**Pull request by fmease**
Fixes #140412 which regressed in #140220 that I reviewed. As mentioned in https://github.com/rust-lang/rust/pull/140220#issuecomment-2837061779, at the time I didn't have the time to re-review its latest changes and should've therefore invalided my previous "r=me" and blocked the PR on another review given the fragile nature of the doctest impl. This didn't happen which is my fault.

Contains some other small changes. Diff best reviewed modulo whitespace.
r? @GuillaumeGomez

### CODE REVIEW

File: src/librustdoc/doctest/make.rs [hunk 1]
```diff
@@ -339,9 +338,6 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
         *prev_span_hi = hi;
     }
 
-    // Recurse through functions body. It is necessary because the doctest source code is
-    // wrapped in a function to limit the number of AST errors. If we don't recurse into
-    // functions, we would thing all top-level items (so basically nothing).
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:344]: Outdated since #138104 when I suggested to remove the recursion in https://github.com/rust-lang/rust/pull/138104#discussion_r2015246273.

File: src/librustdoc/doctest/make.rs [hunk 2]
```diff
@@ -351,8 +347,6 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
         }
         match item.kind {
             ast::ItemKind::Fn(ref fn_item) if !info.has_main_fn => {
-                // We only push if it's the top item because otherwise, we would duplicate
-                // its content since the top-level item was already added.
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:355]: Outdated since #138104 when I suggested to remove the recursion in https://github.com/rust-lang/rust/pull/138104#discussion_r2015246273.

File: src/librustdoc/doctest/make.rs [hunk 3]
```diff
@@ -412,44 +406,38 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
                     }
-                    _ => {
+                    StmtKind::Expr(ref expr) => {
+                        if matches!(expr.kind, ast::ExprKind::Err(_)) {
+                            reset_error_count(&psess);
+                            return Err(());
+                        }
                         has_non_items = true;
                     }
+                    StmtKind::Let(_) | StmtKind::Semi(_) | StmtKind::Empty => has_non_items = true,
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:440]: Replaced wildcard with exhaustive matching to prevent silently dropping non-items ever again (context: https://github.com/rust-lang/rust/pull/140220#issuecomment-2832657466).

File: src/librustdoc/doctest/make.rs [hunk 4]
```diff
@@ -412,44 +406,38 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
+                                    info.has_main_fn = true;
                                 }
-                            {
-                                info.has_main_fn = true;
-                                break;
                             }
                         }
                     }
-                    _ => {
+                    StmtKind::Expr(ref expr) => {
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:433]: Moved this one closer to the other non-items.

File: src/librustdoc/doctest/make.rs [hunk 5]
```diff
@@ -412,44 +406,38 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
-                                && let TokenKind::Ident(name, _) = token.kind
-                                && name == kw::Fn
-                                && let Some(TokenTree::Token(fn_token, _)) = iter.peek()
-                                && let TokenKind::Ident(fn_name, _) = fn_token.kind
-                                && fn_name == sym::main
-                                && let Some(TokenTree::Delimited(_, _, Delimiter::Parenthesis, _)) = {
-                                    iter.next();
-                                    iter.peek()
+                        if !info.has_main_fn {
+                            // For backward compatibility, we look for the token sequence `fn main(…)`
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:415]: Re-added the historical context that was dropped in #138104 (I rephrased it).

File: src/librustdoc/doctest/make.rs [hunk 6]
```diff
@@ -412,44 +406,38 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
-                        has_non_items = true;
+                        is_extern_crate = check_item(item, &mut info, crate_name);
                     }
                     // We assume that the macro calls will expand to item(s) even though they could
-                    // expand to statements and expressions. And the simple fact that we're trying
-                    // to retrieve a `main` function inside it is a terrible idea.
+                    // expand to statements and expressions.
                     StmtKind::MacCall(ref mac_call) => {
-                        if info.has_main_fn {
-                            continue;
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:429]: This was the culprit that led to #140412: The `continue` skips the entire span-to-string processing happening below the `match` which lead to the (compilefail) `global_asm!(…);` getting dropped right on the floor / not even appearing in the generated crate.

File: src/librustdoc/doctest/make.rs [hunk 7]
```diff
@@ -412,44 +406,38 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
+                            // wrapper macro". For the record, this is a horrible heuristic!
+                            // See <https://github.com/rust-lang/rust/issues/56898>.
+                            let mut iter = mac_call.mac.args.tokens.iter();
+                            while let Some(token) = iter.next() {
+                                if let TokenTree::Token(token, _) = token
+                                    && let TokenKind::Ident(kw::Fn, _) = token.kind
+                                    && let Some(TokenTree::Token(ident, _)) = iter.next()
+                                    && let TokenKind::Ident(sym::main, _) = ident.kind
+                                    && let Some(TokenTree::Delimited(.., Delimiter::Parenthesis, _)) =
+                                        iter.next()
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:426]: Unrelated drive-by change (should probably be dropped from this PR): Don't use `peek()` at all (it's needless complexity):

Once we've seen `fn NOT_AN_IDENT` we now advance immediately (=> we longer recognize `fn fn main(…)` (sic!) as a main fn which is fine).

On master, we already have to advance anyway to check for parentheses meaning `fn main NOT_PARENS` will also advance (to `main`). Now, we no longer recognize `fn main fn main(…)` (sic!) as a main fn which is fine).

File: tests/rustdoc-ui/doctest/macro-after-main.rs
Comment (fmease) [inline tests/rustdoc-ui/doctest/macro-after-main.rs:1]: This doctest should definitely not pass! It never used to pass until the PR that added it. It's not a proper minimization of the diesel cargotest smoke test.

We're in an item context since there's a main fn and all three statements are considered items by us which is expected. Therefore, the `eprintln!();` which is only valid in expression contexts will and should lead to an error down the line.

File: src/librustdoc/doctest/make.rs [hunk 8]
```diff
@@ -412,44 +406,40 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
+                                    && let Some(TokenTree::Delimited(.., Delimiter::Parenthesis, _)) = {
+                                        iter.next();
+                                        iter.peek()
+                                    }
+                                {
+                                    info.has_main_fn = true;
                                 }
-                            {
-                                info.has_main_fn = true;
-                                break;
```
Comment (GuillaumeGomez) [inline src/librustdoc/doctest/make.rs:446]: Why removing this `break`?

**Comment by GuillaumeGomez** [comment]
Nah, not your fault. All tests passed and the "try" command was happy was well so I (wrongly) assumed that it was all good.

File: tests/rustdoc-ui/doctest/macro-after-main.rs
Comment (GuillaumeGomez) [reply tests/rustdoc-ui/doctest/macro-after-main.rs:1]: The problem I identified was that the `MacCall` pattern was skipped if we already found a `main` function, making all other items "non function items", leading to the regression. My change was to instead always enter in this arm and inside it check if there is a `main` function only if we didn't find one yet.

The code does seem valid to me considering that you can generate items with macros inside a function.

File: src/librustdoc/doctest/make.rs (hunk 8 above)
Comment (fmease) [reply src/librustdoc/doctest/make.rs:446]: I was tired and thought it would `break` to the outer `for`. Reverted.

File: tests/rustdoc-ui/doctest/macro-after-main.rs
Comment (fmease) [reply tests/rustdoc-ui/doctest/macro-after-main.rs:1]: Right, that was a real regression, I'm not refuting that. As I wrote in https://github.com/rust-lang/rust/pull/140420#discussion_r2065150533, the problem was the `continue` you added as a fix which skipped the entire span-to-string logic dropping certain things on the floor.

With my PR applied, the `ParseSourceInfo.everything_else` contains:

```rs
include!("./auxiliary/macro-after-main.rs");

fn main() {}
eprintln!();
```

Which is entirely reasonable (we consider all macro calls as item macro calls which is the only sensible thing to do with all the constraints we have).

However, on master (which `continue`s) it contains:

```rs
include!("./auxiliary/macro-after-main.rs");

fn main() {}
```

Notice how we dropped the `eprintln!();`! That's why ehuss's doctest in #140412 is no longer `compile_fail`: On master, it simply drops the malformed `global_asm!(…);`! That's what I'm fixing here.

Comment (GuillaumeGomez) [reply tests/rustdoc-ui/doctest/macro-after-main.rs:1]: Yes your new fix is good. However, this doctest should compile as it should be wrapped in a function since there are expressions (making the `main` function potentially generated by the macro not run).

Comment (fmease) [reply tests/rustdoc-ui/doctest/macro-after-main.rs:1]: > However, this doctest should compile as it should be wrapped in a function since there are expressions 

I still disagree. That's impossible without performing macro expansion, we *have* to assume that all macro calls expand to items as previously discussed. There are no expressions as far as I'm concerned, `include!(…);`, `fn main() {}` and `println!(…);` could all be items. We can't wrap it in a function because `include!(…)` isn't allowed in functions contexts, similarly `global_asm!(…)`. We don't know that `println!(…);` expands to an expression, not without macro expansion.

What you're asking is not possible, we still need to keep #140412 compiling.

Comment (GuillaumeGomez) [reply tests/rustdoc-ui/doctest/macro-after-main.rs:1]: Hum, I see. Yeah that makes sense. We should likely expand macros at some point. Saving that for a later time. :')

**Comment by fmease** [comment]
Added tests. Ready.

**Comment by fmease** [comment]
Wait? Are the fake line numbers of doctests unstable across reruns? I keep re-blessing and they change. Oh no!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by fmease** [comment]
Beta backport accepted as per [#t-rustdoc > beta-nominated: #140420 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/beta-nominated.3A.20.23140420/near/515526323).

**Comment by ehuss** [comment]
Thanks for the quick fix!
