### PR TITLE
privacy: no nominal visibility for assoc fns 

### LINKED ISSUE #113860: ICE: `DefId() reachable Restricted(DefId()) > nominal Restricted(DefId())`
### Code

```Rust
#![feature(staged_api)]

mod m {
    pub trait Trait {}

    impl Trait for Trait {
        pub(in m) fn fun() {
        }
    }
}

```

### Meta

`rustc --version --verbose`:
```
d3515155216e98c23440ea92c3f49c6a0d7101fc
```

### Error output

```
error[E0449]: visibility qualifiers are not permitted here
 --> 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB.rs:7:9
  |
7 |         pub(in m) fn fun() {
  |         ^^^^^^^^^
  |
  = note: trait items always share the visibility of their trait

error[E0407]: method `fun` is not a member of trait `Trait`
 --> 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB.rs:7:9
  |
7 | /         pub(in m) fn fun() {
8 | |         }
  | |_________^ not a member of trait `Trait`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/middle/privacy.rs:184:21: DefId(0:6 ~ 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB[84ee]::m::{impl#0}::fun): reachable Restricted(DefId(0:0 ~ 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB[84ee])) > nominal Restricted(DefId(0:3 ~ 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB[84ee]::m))
 --> 2ADE1D81260D3693369475F8E44705B98C856AF4C95A97FA647CC1D10C596BBB.rs:7:9
  |
7 |         pub(in m) fn fun() {
  |         ^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<dyn Any>', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:995:33
stack backtrace:
   0:     0x7f1b34c81286 - std::backtrace_rs::backtrace::libunwind::trace::h30fa42aa2db88158
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1b34c81286 - std::backtrace_rs::backtrace::trace_unsynchronized::h2b9cc808f86f85f7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1b34c81286 - std::sys_common::backtrace::_print_fmt::h268804fe13f30210
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1b34c81286 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h692ee2dd29cb6a32
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1b34d56be7 - core::fmt::rt::Argument::fmt::h1dc8855cf0be02de
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/rt.rs:138:9
   5:     0x7f1b34d56be7 - core::fmt::write::h35c6f281391d7802
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f1b34cdac25 - std::io::Write::write_fmt::h5f9eeb8695999550
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1714:15
   7:     0x7f1b34c81085 - std::sys_common::backtrace::_print::h0b343769d5ca97ef
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1b34c81085 - std::sys_common::backtrace::print::h1a9dcf70c9d72f51
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1b34cd476c - std::panicking::default_hook::{{closure}}::h84517d6843a8b8eb
  10:     0x7f1b34cd443c - std::panicking::default_hook::h9d050be456d2e865
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:288:9
  11:     0x7f1b36b2c73b - <alloc[86fc1011f0da8be9]::boxed::Box<dyn for<'a, 'b> core[1cc32ee8b476061a]::ops::function::Fn<(&'a core[1cc32ee8b476061a]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[1cc32ee8b476061a]::marker::Sync + core[1cc32ee8b476061a]::marker::Send> as core[1cc32ee8b476061a]::ops::function::Fn<(&core[1cc32ee8b476061a]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2021:9
  12:     0x7f1b36b2c73b - rustc_driver_impl[7b0fb63d2c5f7d71]::install_ice_hook::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1339:13
  13:     0x7f1b34cd4f55 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9913b6eac17b3933
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2021:9
  14:     0x7f1b34cd4f55 - std::panicking::rust_panic_with_hook::hd3dcfd82aa6687cf
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:709:13
  15:     0x7f1b37bf8733 - std[aeffd6322052592a]::panicking::begin_panic::<rustc_errors[4a72a762f26cae1d]::ExplicitBug>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:626:9
  16:     0x7f1b37bf7f16 - std[aeffd6322052592a]::sys_common::backtrace::__rust_end_short_backtrace::<std[aeffd6322052592a]::panicking::begin_panic<rustc_errors[4a72a762f26cae1d]::ExplicitBug>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:151:18
  17:     0x7f1b35961966 - std[aeffd6322052592a]::panicking::begin_panic::<rustc_errors[4a72a762f26cae1d]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:625:12
  18:     0x7f1b37bf4191 - std[aeffd6322052592a]::panic::panic_any::<rustc_errors[4a72a762f26cae1d]::ExplicitBug>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:63:5
  19:     0x7f1b37bf4191 - <rustc_errors[4a72a762f26cae1d]::HandlerInner>::span_bug::<rustc_span[8fc2bc2477ece13]::span_encoding::Span, alloc[86fc1011f0da8be9]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1589:9
  20:     0x7f1b37bf3411 - <rustc_errors[4a72a762f26cae1d]::Handler>::span_bug::<rustc_span[8fc2bc2477ece13]::span_encoding::Span, alloc[86fc1011f0da8be9]::string::String>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:995:9
  21:     0x7f1b37a4e7ae - rustc_middle[6d3884defc02ee9d]::util::bug::opt_span_bug_fmt::<rustc_span[8fc2bc2477ece13]::span_encoding::Span>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:34:40
  22:     0x7f1b37a4e304 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_opt::<rustc_middle[6d3884defc02ee9d]::util::bug::opt_span_bug_fmt<rustc_span[8fc2bc2477ece13]::span_encoding::Span>::{closure#0}, !>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:154:36
  23:     0x7f1b37a4e2a0 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context_opt::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_opt<rustc_middle[6d3884defc02ee9d]::util::bug::opt_span_bug_fmt<rustc_span[8fc2bc2477ece13]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  24:     0x7f1b3595e1c5 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_opt::<rustc_middle[6d3884defc02ee9d]::util::bug::opt_span_bug_fmt<rustc_span[8fc2bc2477ece13]::span_encoding::Span>::{closure#0}, !>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:154:5
  25:     0x7f1b3595e1c5 - rustc_middle[6d3884defc02ee9d]::util::bug::opt_span_bug_fmt::<rustc_span[8fc2bc2477ece13]::span_encoding::Span>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:31:5
  26:     0x7f1b3595e1c5 - rustc_middle[6d3884defc02ee9d]::util::bug::span_bug_fmt::<rustc_span[8fc2bc2477ece13]::span_encoding::Span>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/util/bug.rs:22:5
  27:     0x7f1b37c010b1 - <rustc_middle[6d3884defc02ee9d]::middle::privacy::EffectiveVisibilities>::check_invariants
  28:     0x7f1b384e677a - rustc_privacy[ea98290f4f72dc93]::effective_visibilities
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_privacy/src/lib.rs:2277:5
  29:     0x7f1b3861ae61 - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::effective_visibilities::dynamic_query::{closure#2}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:582:47
  30:     0x7f1b3861ae61 - rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::effective_visibilities::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:506:18
  31:     0x7f1b38652157 - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::effective_visibilities::dynamic_query::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:578:25
  32:     0x7f1b38652157 - <rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::effective_visibilities::dynamic_query::{closure#2} as core[1cc32ee8b476061a]::ops::function::FnOnce<(rustc_middle[6d3884defc02ee9d]::ty::context::TyCtxt, ())>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  33:     0x7f1b3853f200 - <rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false> as rustc_query_system[6af0a3b9967eef64]::query::config::QueryConfig<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:116:9
  34:     0x7f1b3853f200 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:481:72
  35:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  36:     0x7f1b3853f200 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::try_with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:270:16
  37:     0x7f1b3853f200 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:246:9
  38:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:9
  39:     0x7f1b3853f200 - <rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:149:13
  40:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context::<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:133:9
  41:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:36
  42:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context_opt::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
  43:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:5
  44:     0x7f1b3853f200 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context::<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:124:5
  45:     0x7f1b3853f200 - <rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:134:9
  46:     0x7f1b3853f200 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:481:18
  47:     0x7f1b3853f200 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt, false>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:414:9
  48:     0x7f1b3853f200 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::try_execute_query::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt, false>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:359:13
  49:     0x7f1b387e295c - rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:811:32
  50:     0x7f1b387e295c - stacker[13632619fe1702]::maybe_grow::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  51:     0x7f1b387e295c - rustc_data_structures[ce0cbe122e78aa38]::stack::ensure_sufficient_stack::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  52:     0x7f1b387e295c - rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:811:5
  53:     0x7f1b387e295c - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::effective_visibilities::get_query_non_incr::__rust_end_short_backtrace
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:556:26
  54:     0x7f1b3842a5dd - rustc_middle[6d3884defc02ee9d]::query::plumbing::query_get_at::<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 8usize]>>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:155:17
  55:     0x7f1b3842a5dd - <rustc_middle[6d3884defc02ee9d]::query::plumbing::TyCtxtAt>::effective_visibilities
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/mod.rs:2202:1
  56:     0x7f1b3842a5dd - <rustc_middle[6d3884defc02ee9d]::ty::context::TyCtxt>::effective_visibilities
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:376:35
  57:     0x7f1b3842a5dd - rustc_passes[93c8a891cb00d455]::stability::check_unused_or_stable_features
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_passes/src/stability.rs:937:43
  58:     0x7f1b375e0b3d - rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:773:21
  59:     0x7f1b375e0b3d - <rustc_data_structures[ce0cbe122e78aa38]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:752:9
  60:     0x7f1b375e0b3d - <rustc_session[b37908bbd82c022d]::session::Session>::time::<(), rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:11:9
  61:     0x7f1b375e0b3d - rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:772:17
  62:     0x7f1b375e0b3d - <rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2} as core[1cc32ee8b476061a]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  63:     0x7f1b375e0b3d - <core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}> as core[1cc32ee8b476061a]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  64:     0x7f1b375e0b3d - std[aeffd6322052592a]::panicking::try::do_call::<core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:500:40
  65:     0x7f1b375e0b3d - std[aeffd6322052592a]::panicking::try::<(), core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:464:19
  66:     0x7f1b3768ca0e - std[aeffd6322052592a]::panic::catch_unwind::<core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}::{closure#2}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:142:14
  67:     0x7f1b3768ca0e - rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync.rs:199:37
  68:     0x7f1b3768ca0e - <rustc_data_structures[ce0cbe122e78aa38]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:752:9
  69:     0x7f1b3768ca0e - <rustc_session[b37908bbd82c022d]::session::Session>::time::<(), rustc_interface[934f6e358140c59d]::passes::analysis::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:11:9
  70:     0x7f1b3762cfb9 - rustc_interface[934f6e358140c59d]::passes::analysis
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:751:5
  71:     0x7f1b38627221 - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:582:47
  72:     0x7f1b38627221 - rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:506:18
  73:     0x7f1b38659357 - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::analysis::dynamic_query::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:578:25
  74:     0x7f1b38659357 - <rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::analysis::dynamic_query::{closure#2} as core[1cc32ee8b476061a]::ops::function::FnOnce<(rustc_middle[6d3884defc02ee9d]::ty::context::TyCtxt, ())>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  75:     0x7f1b3853bdd9 - <rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false> as rustc_query_system[6af0a3b9967eef64]::query::config::QueryConfig<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:116:9
  76:     0x7f1b3853bdd9 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:481:72
  77:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  78:     0x7f1b3853bdd9 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::try_with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:270:16
  79:     0x7f1b3853bdd9 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:246:9
  80:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:9
  81:     0x7f1b3853bdd9 - <rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:149:13
  82:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context::<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:133:9
  83:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:36
  84:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context_opt::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
  85:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_context::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:5
  86:     0x7f1b3853bdd9 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::with_related_context::<<rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:124:5
  87:     0x7f1b3853bdd9 - <rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt as rustc_query_system[6af0a3b9967eef64]::query::QueryContext>::start_query::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:134:9
  88:     0x7f1b3853bdd9 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:481:18
  89:     0x7f1b3853bdd9 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::execute_job::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt, false>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:414:9
  90:     0x7f1b3853bdd9 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::try_execute_query::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt, false>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:359:13
  91:     0x7f1b386bed22 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:811:32
  92:     0x7f1b386bed22 - stacker[13632619fe1702]::maybe_grow::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  93:     0x7f1b386bed22 - rustc_data_structures[ce0cbe122e78aa38]::stack::ensure_sufficient_stack::<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  94:     0x7f1b386bed22 - rustc_query_system[6af0a3b9967eef64]::query::plumbing::get_query_non_incr::<rustc_query_impl[4dcbb0eb2fff6f8b]::DynamicConfig<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4dcbb0eb2fff6f8b]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:811:5
  95:     0x7f1b386bed22 - rustc_query_impl[4dcbb0eb2fff6f8b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:556:26
  96:     0x7f1b36aedf40 - rustc_middle[6d3884defc02ee9d]::query::plumbing::query_get_at::<rustc_query_system[6af0a3b9967eef64]::query::caches::SingleCache<rustc_middle[6d3884defc02ee9d]::query::erase::Erased<[u8; 1usize]>>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:155:17
  97:     0x7f1b36aedf40 - <rustc_middle[6d3884defc02ee9d]::query::plumbing::TyCtxtAt>::analysis
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/mod.rs:2202:1
  98:     0x7f1b36aedf40 - <rustc_middle[6d3884defc02ee9d]::ty::context::TyCtxt>::analysis
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/query/plumbing.rs:376:35
  99:     0x7f1b36aedf40 - rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:434:52
 100:     0x7f1b36aedf40 - <rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:588:37
 101:     0x7f1b36aedf40 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<<rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
 102:     0x7f1b36aedf40 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::try_with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<<rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:270:16
 103:     0x7f1b36aedf40 - <std[aeffd6322052592a]::thread::local::LocalKey<core[1cc32ee8b476061a]::cell::Cell<*const ()>>>::with::<rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context<<rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:246:9
 104:     0x7f1b36aedf40 - rustc_middle[6d3884defc02ee9d]::ty::context::tls::enter_context::<<rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:9
 105:     0x7f1b36aedf40 - <rustc_middle[6d3884defc02ee9d]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:588:9
 106:     0x7f1b36af4644 - rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:434:13
 107:     0x7f1b36af4644 - <rustc_interface[934f6e358140c59d]::interface::Compiler>::enter::<rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}::{closure#2}, core[1cc32ee8b476061a]::result::Result<core[1cc32ee8b476061a]::option::Option<rustc_interface[934f6e358140c59d]::queries::Linker>, rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:389:19
 108:     0x7f1b36acb7dd - rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:375:22
 109:     0x7f1b36acb7dd - rustc_interface[934f6e358140c59d]::interface::run_compiler::<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:337:21
 110:     0x7f1b36acb7dd - rustc_span[8fc2bc2477ece13]::set_source_map::<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1037:5
 111:     0x7f1b36b41c5c - rustc_interface[934f6e358140c59d]::interface::run_compiler::<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:331:13
 112:     0x7f1b36b41c5c - <scoped_tls[63aa9906a2b9d3f0]::ScopedKey<rustc_span[8fc2bc2477ece13]::SessionGlobals>>::set::<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
 113:     0x7f1b36ad7613 - rustc_span[8fc2bc2477ece13]::create_session_globals_then::<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:120:5
 114:     0x7f1b36ad7613 - rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals::<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:161:38
 115:     0x7f1b36ad7613 - std[aeffd6322052592a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:135:18
 116:     0x7f1b36af1cd5 - <std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_::<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:529:17
 117:     0x7f1b36af1cd5 - <core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<<std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[1cc32ee8b476061a]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
 118:     0x7f1b36af1cd5 - std[aeffd6322052592a]::panicking::try::do_call::<core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<<std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:500:40
 119:     0x7f1b36af1cd5 - std[aeffd6322052592a]::panicking::try::<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<<std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:464:19
 120:     0x7f1b36af1cd5 - std[aeffd6322052592a]::panic::catch_unwind::<core[1cc32ee8b476061a]::panic::unwind_safe::AssertUnwindSafe<<std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:142:14
 121:     0x7f1b36af1cd5 - <std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_::<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:528:30
 122:     0x7f1b36af1cd5 - <<std[aeffd6322052592a]::thread::Builder>::spawn_unchecked_<rustc_interface[934f6e358140c59d]::util::run_in_thread_pool_with_globals<rustc_interface[934f6e358140c59d]::interface::run_compiler<core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>, rustc_driver_impl[7b0fb63d2c5f7d71]::run_compiler::{closure#1}>::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1cc32ee8b476061a]::result::Result<(), rustc_span[8fc2bc2477ece13]::ErrorGuaranteed>>::{closure#1} as core[1cc32ee8b476061a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
 123:     0x7f1b34ce5b89 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h878296a20baf385f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2007:9
 124:     0x7f1b34ce5b89 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h765f691d0781ffe6
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2007:9
 125:     0x7f1b34c8aef5 - std::sys::unix::thread::Thread::new::thread_start::h4b8556bc7501ac26
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
 126:     0x7f1b34e9d44b - <unknown>
 127:     0x7f1b34f20e40 - <unknown>
 128:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.73.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [effective_visibilities] checking effective visibilities
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors; 1 warning emitted

Some errors have detailed explanations: E0407, E0449, E0601.
For more information about an error, try `rustc --explain E0407`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #113860.

When `staged_api` is enabled, effective visibilities are computed earlier and this can trigger an ICE in some cases.

In particular, if a impl of a trait method has a visibility then an error will be reported for that, but when privacy invariants are being checked, the effective visibility will still be greater than the nominal visbility and that will trigger a `span_bug!`.

However, this invariant - that effective visibilites are limited to nominal visibility - doesn't make sense for associated functions.

### CODE REVIEW

**Comment by petrochenkov** [comment]
I'd like too look in more detail why the invariant is broken in this scenario, maybe it can affect non-erroneous cases too.
r? @petrochenkov

**Comment by petrochenkov** [comment]
Minimized reproduction:
```rust
#![feature(staged_api)]

pub trait Trait {
    fn fun() {}
}

impl Trait for u8 {
    pub(self) fn fun() {}
}

fn main() {}
```

>When `staged_api` is enabled, effective visibilities are computed for a greater number of items

That shouldn't be the case, from what I remember the `effective_visibilities` query just runs at a different (earlier) point in compilation in this case.

File: compiler/rustc_middle/src/middle/privacy.rs [hunk 1]
```diff
@@ -181,12 +181,15 @@ impl EffectiveVisibilities {
             if !matches!(tcx.def_kind(def_id), DefKind::Impl { .. }) {
```
Comment (petrochenkov) [inline compiler/rustc_middle/src/middle/privacy.rs:181]: This exception should be extended to associated items in trait impls, because nominal visibility doesn't make sense for them as well.

Comment (davidtwco) [reply compiler/rustc_middle/src/middle/privacy.rs]: Fixed!

Comment (petrochenkov) [reply compiler/rustc_middle/src/middle/privacy.rs]: Right now the ICE will still occur for associated constants and types, and we should keep the check for associated items in inherent impls, because there nominal visibilities make sense.

File: tests/ui/privacy/issue-113860-1.rs [hunk 2]
```diff
@@ -0,0 +1,16 @@
+#![feature(staged_api)]
+//~^ module has missing stability attribute
```
Comment (petrochenkov) [inline tests/ui/privacy/issue-113860-1.rs:2]:
```suggestion
//~^ ERROR module has missing stability attribute
```
(And in other places.)

File: tests/ui/privacy/issue-113860.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+//~^ ERROR module has missing stability attribute
+#![feature(staged_api)]
+
+// See #113860.
+
+mod m {
+    pub trait Trait {}
+
+    impl Trait for Trait {
+        //~^ ERROR the object type `(dyn Trait + 'static)` automatically implements the trait `Trait` [E0371]
```
Comment (petrochenkov) [inline tests/ui/privacy/issue-113860.rs:11]: Do you think it's important to keep the original reproduction?
I don't like it due to the "off-topic" errors like this, the minimized test is probably enough.

File: compiler/rustc_middle/src/middle/privacy.rs (hunk 1 above)
Comment (davidtwco) [reply compiler/rustc_middle/src/middle/privacy.rs]: Fixed!

File: tests/ui/privacy/issue-113860-1.rs (hunk 2 above)
Comment (davidtwco) [reply tests/ui/privacy/issue-113860-1.rs]: Oops, fixed!

File: tests/ui/privacy/issue-113860.rs (hunk 3 above)
Comment (davidtwco) [reply tests/ui/privacy/issue-113860.rs]: I suppose not - I've removed it.
