### PR TITLE
Do not re-parse function signatures to suggest generics

### LINKED ISSUE #100875: thread 'rustc' panicked at 'no label after fn'
### Code

```Rust
use std::cell::UnsafeCell;

struct Foo<T> {}

impl<T> Foo<T> {
    thread_local! {
        static TL: UnsafeCell<Vec<T>> = UnsafeCell::new(Vec::new());
    }
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5

```

### Error output

```
/Users/x/.cargo/bin/cargo +stable build --color=always --message-format=json-diagnostic-rendered-ansi --package rust_hello_world --bin rust_hello_world
   Compiling rust_hello_world v0.1.0 (/Users/x/CLionProjects/rust_hello_world)
thread 'rustc' panicked at 'no label after fn', compiler/rustc_span/src/source_map.rs:972:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: <rustc_span::source_map::SourceMap>::generate_fn_name_span
   6: <rustc_resolve::Resolver>::into_struct_error
   7: <rustc_resolve::Resolver>::report_error
   8: <rustc_resolve::Resolver>::resolve_ident_in_lexical_scope
   9: <rustc_resolve::Resolver>::resolve_path_with_ribs
  10: <rustc_resolve::late::LateResolutionVisitor>::smart_resolve_path_fragment
  11: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_ty
  12: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_generic_arg
  13: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_path_segment
  14: rustc_ast::visit::walk_ty::<rustc_resolve::late::LateResolutionVisitor>
  15: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_ty
  16: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_generic_arg
  17: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_path_segment
  18: rustc_ast::visit::walk_ty::<rustc_resolve::late::LateResolutionVisitor>
  19: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_ty
  20: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn
  21: rustc_ast::visit::walk_item::<rustc_resolve::late::LateResolutionVisitor>
  22: <rustc_resolve::late::LateResolutionVisitor>::resolve_item
  23: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_item
  24: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_block
  25: <rustc_resolve::late::LateResolutionVisitor>::resolve_expr
  26: <rustc_resolve::late::LateResolutionVisitor>::resolve_impl_item
  27: <rustc_resolve::late::LateResolutionVisitor>::resolve_item
  28: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_item
  29: <rustc_resolve::Resolver>::late_resolve_crate
  30: <rustc_session::session::Session>::time::<(), <rustc_resolve::Resolver>::resolve_crate::{closure#0}>
  31: rustc_interface::passes::configure_and_expand
  32: <rustc_interface::queries::Queries>::expansion
  33: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  34: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  35: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.63.0 (4b91a6ea7 2022-08-08) running on x86_64-apple-darwin
note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `rust_hello_world`
Process finished with exit code 101

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
This PR uses the existing resolution rib infrastructure to channel the correct span information to suggest generic parameters.  This allows to avoid re-parsing a function's source code.

Drive-by cleanup: this removes useless `FnItemRibKind` from late resolution ribs.  All the use cases are already covered by `ItemRibKind` and `AssocItemRibKind` which have more precise semantics.

### CODE REVIEW

**Comment by cjgillot** [comment]
Re-rolling the dice.
r? compiler

**Comment by cjgillot** [comment]
nagisa is on vacation.
r? compiler

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -536,40 +536,37 @@ impl<'a> Resolver<'a> {
...
-                            "try adding a local generic parameter in this method instead",
-                        );
+                    let name = self.opt_name(def_id).unwrap_or(sym::T);
+                    let (span, snippet) = if span.is_empty() {
+                        let snippet = format!("<{}>", name);
+                        (span, snippet)
                     } else {
-                        err.help("try using a local generic parameter instead");
-                    }
+                        let span = sm.span_through_char(span, '<').shrink_to_hi();
```
Comment (fee1-dead) [inline compiler/rustc_resolve/src/diagnostics.rs:564]: Is this going to work if there are lifetime parameters?

File: src/test/ui/error-codes/E0401.stderr [hunk 2]
```diff
@@ -4,9 +4,9 @@ error[E0401]: can't use generic parameters from outer function
 LL | fn foo<T>(x: T) {
    |        - type parameter from outer function
 LL |     fn bfnr<U, V: Baz<U>, W: Fn()>(y: T) {
-   |        ---------------------------    ^ use of generic parameter from outer function
-   |        |
-   |        help: try using a local generic parameter instead: `bfnr<U, V: Baz<U>, W: Fn(), T>`
+   |             -                         ^ use of generic parameter from outer function
+   |             |
+   |             help: try using a local generic parameter instead: `T,`
```
Comment (fee1-dead) [inline src/test/ui/error-codes/E0401.stderr:9]: It looks like the space gets trimmed. Should we re-emit the whole generics so that it is more accurate?

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 3]
```diff
@@ -536,40 +536,37 @@ impl<'a> Resolver<'a> {
...
+                        let snippet = format!("{}, ", name);
+                        (span, snippet)
+                    };
+                    // Suggest the modification to the user
+                    err.span_suggestion(span, sugg_msg, snippet, Applicability::MachineApplicable);
```
Comment (fee1-dead) [inline compiler/rustc_resolve/src/diagnostics.rs:569]: I've been noticing a lot of suggestions that are `MachineApplicable` but shouldn't be. I guess this is one of them? cc @compiler-errors

Comment (compiler-errors) [reply compiler/rustc_resolve/src/diagnostics.rs:569]: Yeah, I guess this really should be `MaybeIncorrect`, esp b/c the generic `T` may conflict I think.

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_resolve/src/diagnostics.rs:564]: It won't. I'll file an issue to track this (the former implementation did not support this either).

File: src/test/ui/error-codes/E0401.stderr (hunk 2 above)
Comment (cjgillot) [reply src/test/ui/error-codes/E0401.stderr:9]: I already find this suggestion quite verbose as it is. Forcing a verbose diagnostic may be a bit too much, wouldn't it?

**Review by fee1-dead — APPROVED** [review]

File: src/test/ui/error-codes/E0401.stderr (hunk 2 above)
Comment (estebank) [reply src/test/ui/error-codes/E0401.stderr:9]: This output is fine. At most, we should make it a `span_suggestion_verbose` to get the diff output which I find clearer for these kind of additions, instead of modifying the span/suggestion to make it work better with the inline suggestion.

File: src/test/ui/generics/issue-98432.stderr [hunk 4]
```diff
@@ -5,9 +5,9 @@ LL | impl<T> Struct<T> {
    |      - type parameter from outer function
 LL |     const CONST: fn() = || {
 LL |         struct _Obligation where T:;
-   |                                  ^ use of generic parameter from outer function
-   |
-   = help: try using a local generic parameter instead
+   |                           -      ^ use of generic parameter from outer function
+   |                           |
+   |                           help: try using a local generic parameter instead: `<T>`
```
Comment (estebank) [inline src/test/ui/generics/issue-98432.stderr:10]: This is an unfortunate case.
