### PR TITLE
Test NLL fix of bad lifetime inference for reference captured in closure.

### LINKED ISSUE #93203: Tracking Issue for scoped threads
Feature gate: `#![feature(scoped_threads)]`

This is a tracking issue for scoped threads.

RFC: https://rust-lang.github.io/rfcs/3151-scoped-threads.html

**Note:** Right now, some usage patterns might need a `#![feature(nll)]` to avoid lifetime errors. (This is probably stable soon.)

### Example usage

```rust
let local_var = vec![1, 2, 3];

thread::scope(|s| {
    s.spawn(|| println!("borrowed from thread #1: {:?}", local_var));
    s.spawn(|| println!("borrowed from thread #2: {:?}", local_var));
    println!("borrowed from the main thread: {:?}", local_var);
});
```

### Public API

Documentation: https://doc.rust-lang.org/nightly/std/thread/fn.scope.html

```rust
// std::thread

pub fn scope<'env, F, T>(f: F) -> T
where
    F: for<'scope> FnOnce(&'scope Scope<'scope, 'env>) -> T;

pub struct Scope<'scope, 'env: 'scope> { ... }

impl<'scope, 'env> Scope<'scope, 'env> {
    pub fn spawn<F, T>(&'scope self, f: F) -> ScopedJoinHandle<'scope, T>
    where
        F: FnOnce() -> T + Send + 'scope,
        T: Send + 'scope;
}

impl Builder {
    pub fn spawn_scoped<'scope, 'env, F, T>(
        self,
        scope: &'scope Scope<'env>,
        f: F,
    ) -> io::Result<ScopedJoinHandle<'scope, T>>
    where
        F: FnOnce() -> T + Send + 'scope,
        T: Send + 'scope;
}

pub struct ScopedJoinHandle<'scope, T> { ... }

impl<'scope, T> ScopedJoinHandle<'scope, T> {
    pub fn join(self) -> Result<T>;
    pub fn thread(&self) -> &Thread;
    pub fn is_finshed(&self) -> bool;
}
```

### Steps / History

- [x] RFC attempt 1: https://github.com/rust-lang/rfcs/pull/2647
- [x] RFC attempt 2: https://github.com/rust-lang/rfcs/pull/3151
- [x] Implementation: https://github.com/rust-lang/rust/pull/92555
- [x] Change signatures a bit to remove the argument to the spawn closures: https://github.com/rust-lang/rust/pull/94559
- [x] Fix soundness issue in implementation: https://github.com/rust-lang/rust/pull/94644
- [x] Document lifetimes: https://github.com/rust-lang/rust/pull/94763
- [x] Final comment period (FCP): https://github.com/rust-lang/rust/issues/93203#issuecomment-1075284811
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/97992

### Unresolved Questions

- [x] Can we omit the `&Scope` argument to the functions given to `.spawn()`? That is, `scope.spawn(|| ..)` rather than `scope.spawn(|_| ..)`.
  - It's already possible by forcing the user to use `move || ..` instead, but that's not great. Maybe the language could be subtly changed to capture references or certain `Copy` types by value rather than by reference(-to-reference).
  - See also [this comment](https://github.com/rust-lang/rfcs/pull/3151#issuecomment-883251161) and the collapsed section in [the comment below](https://github.com/rust-lang/rust/issues/93203#issuecomment-1019293467).
  - Mostly answered in [this comment](https://github.com/rust-lang/rust/issues/93203#issuecomment-1040720703).
  - Working idea in [this comment](https://github.com/rust-lang/rust/issues/93203#issuecomment-1040798286).
  - Implementation in https://github.com/rust-lang/rust/pull/94559
- [x] How to document the `'env` and `'scope` lifetimes clearly without scaring people away.
  - https://github.com/rust-lang/rust/pull/94763

### PR DESCRIPTION
**Pull request by steffahn**
This came up as a use-case for `thread::scope` API that only compiles successfully since `feature(nll)` got stabilized recently.

Closes #93203 which had been re-opened for tracking this very test case to be added.

### CODE REVIEW

File: library/std/src/thread/tests.rs [hunk 1]
```diff
@@ -316,3 +316,9 @@ fn test_scoped_threads_drop_result_before_join() {
     });
     assert!(actually_finished.load(Ordering::Relaxed));
 }
+
+fn _test_scoped_threads_nll(x: &u8) {
```
Comment (joshtriplett) [inline library/std/src/thread/tests.rs:320]:
```suggestion
#[test]
fn test_scoped_threads_nll(x: &u8) {
```

Comment (steffahn) [reply library/std/src/thread/tests.rs:320]: I believe this change would produce a warning for the function being unused. We're only testing whether the thing compiles here, not actually running it.

Comment (steffahn) [reply library/std/src/thread/tests.rs:320]: Ah, wait, you also added `#[test]`. Those don't support function arguments though.

Comment (joshtriplett) [reply library/std/src/thread/tests.rs:320]: Ah, right.

Could you nest it within a `#[test]` function that calls it? I think there's value in actually running this to see if it smokes anything out. We have other similar tests that do compile and run.
