### PR TITLE
For E0277 suggest adding `Result` return type for function when using QuestionMark `?` in the body.

### LINKED ISSUE #125997: Suggest changing `main`s return type on E0277 (`?` / `from_residual`)
### Code

```Rust
use std::fs::File;
use std::io::prelude::*;

fn main() {
    let mut file = File::create("foo.txt")?;
    file.write_all(b"Hello, world!")?;
}
```

### Current output

```Shell
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that
implements `FromResidual`)
 --> cargo-14007.rs:5:43
  |
4 | fn main() {
  | --------- this function should return `Result` or `Option` to accept `?`
5 |     let mut file = File::create("foo.txt")?;
  |                                           ^ cannot use the `?` operator in a function that returns `()`
  |
  = help: the trait `FromResidual<Result<Infallible, std::io::Error>>` is not implemented for `()`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that
implements `FromResidual`)
 --> cargo-14007.rs:6:37
  |
4 | fn main() {
  | --------- this function should return `Result` or `Option` to accept `?`
5 |     let mut file = File::create("foo.txt")?;
6 |     file.write_all(b"Hello, world!")?;
  |                                     ^ cannot use the `?` operator in a function that returns `()`
  |
  = help: the trait `FromResidual<Result<Infallible, std::io::Error>>` is not implemented for `()`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `cargo-14007` (bin "cargo-14007") due to 2 previous errors
```
```


### Desired output

```Shell
To suggest the following change

fn main() -> Result<(), Box<dyn Error> {
    // ...
    Ok(())
}
```

### Rationale and extra context

In rust-lang/cargo#14007, concern was raised over people generating a trivial `fn main() {}` with `cargo new` and copy/pasting example code that uses `?` (which is encouraged in API guidelines).  Regardless of the decision made for `cargo new`, this applies just as well to users hand writing a trivial `fn main() {}`.  These are likely new users who would be intimidated by the current message and wouldn't know what next steps to take

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2
```
```


### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by surechen**
Adding suggestions for following function in E0277.

```rust
fn main() {
    let mut _file = File::create("foo.txt")?;
}
```

to

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut _file = File::create("foo.txt")?;

    return Ok(());
}
```

According to the issue #125997, only the code examples in the issue are targeted, but the issue covers a wider range of situations.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -4586,6 +4586,58 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                vec![(ret_span, " -> Result<(), Box<dyn std::error::Error>>".to_string())];
+
+            if let hir::ExprKind::Block(b, _) = body.value.kind
+                && b.expr.is_none()
+                && let Some(s) = b.stmts.last()
+                && !is_ret_expr(s)
+            {
+                sugg_spans.push((
+                    s.span.shrink_to_hi().until(body.value.span.shrink_to_hi()),
+                    "\n\n    return Ok(());\n}".to_string(),
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4621]:
```suggestion
                    "\n    return Ok(());\n}".to_string(),
```

we don't need to create perfect formatting. Even the spaces are going to be wrong for anything with a higher indentation

Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4621]: Also, why not `Ok(())` as a trailing expression?

File: tests/ui/return/return-from-residual-sugg-issue-125997.stderr [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+LL | fn test1() {
+   | ---------- this function should return `Result` or `Option` to accept `?`
+LL |     let mut _file = File::create("foo.txt")?;
+   |                                            ^ cannot use the `?` operator in a function that returns `()`
+   |
+   = help: the trait `FromResidual<Result<Infallible, std::io::Error>>` is not implemented for `()`
+help: consider adding return type
+   |
+LL ~ fn test1() -> Result<(), Box<dyn std::error::Error>> {
+LL ~     let mut _file = File::create("foo.txt")?;
```
Comment (oli-obk) [inline tests/ui/return/return-from-residual-sugg-issue-125997.stderr:13]: why does this line appear as modified?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -4586,6 +4586,58 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+        trait_ref: ty::PolyTraitRef<'tcx>,
+    ) {
+        if ObligationCauseCode::QuestionMark != *obligation.cause.code().peel_derives() {
+            return;
+        }
+
+        let node = self.tcx.hir_node_by_def_id(obligation.cause.body_id);
+        if let hir::Node::Item(item) = node
+            && let hir::ItemKind::Fn(sig, _, body_id) = item.kind
+            && let hir::FnRetTy::DefaultReturn(ret_span) = sig.decl.output
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4603]: may want to keep the issue open to support returning different types

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -4586,6 +4586,58 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+            && trait_ref.skip_binder().args.len() == 2
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4604]: what is this check for? This will accept any trait with 2 generic params? I think you should check it against `tcx.lang_items().try_trait()`

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 5]
```diff
@@ -4586,6 +4586,58 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+            && self.tcx.is_diagnostic_item(sym::Result, def.did())
+        {
+            let body = self.tcx.hir().body(body_id);
+            let mut sugg_spans =
+                vec![(ret_span, " -> Result<(), Box<dyn std::error::Error>>".to_string())];
+
+            if let hir::ExprKind::Block(b, _) = body.value.kind
+                && b.expr.is_none()
+                && let Some(s) = b.stmts.last()
+                && !is_ret_expr(s)
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4617]: what is the `is_ret_expr` check for?

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4621]: > Also, why not `Ok(())` as a trailing expression?

Thank you.
I just want to make sure there is no return stmt at the end of the function. In this case, don't suggest adding `return Ok(());`

File: tests/ui/return/return-from-residual-sugg-issue-125997.stderr (hunk 2 above)
Comment (surechen) [reply tests/ui/return/return-from-residual-sugg-issue-125997.stderr:13]: > why does this line appear as modified?

I think this is because the span I used when suggesting `return Ok(());` is not quite precise.
I use `s.span.shrink_to_hi().until(body.value.span.shrink_to_hi()),`  to give return suggestion, `s` is the end Stmt of the block, in this code, `s` is `let mut _file = File::create("foo.txt")?;`

Comment (surechen) [reply tests/ui/return/return-from-residual-sugg-issue-125997.stderr:13]: Is there any better way here? Thank you.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 6]
```diff
@@ -4586,6 +4586,58 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+            {
+                sugg_spans.push((
+                    s.span.shrink_to_hi().until(body.value.span.shrink_to_hi()),
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4620]: Yea I think this erases all the code after the `?` using statement (try adding a dummy `println!();` after the `?` using statement to test this.).

I would have expected for `b.span.shrink_to_high()` to suffice, but that may be after the `}`, so you may need to look for the last statement in the block (we know there must be one, as there's a `?`)

Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4620]: if that span does not contain the `}`, please document it on the `span` field, so future readers immediately know what the span means.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 1 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: > Also, why not `Ok(())` as a trailing expression?

Done. Thank you.

File: tests/ui/return/return-from-residual-sugg-issue-125997.stderr (hunk 2 above)
Comment (surechen) [reply tests/ui/return/return-from-residual-sugg-issue-125997.stderr]: Done. Thank you.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 4 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: Done. Thank you.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4603]: Done. Thank you.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 5 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: Remove this function.  Thank you.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 6 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: > Yea I think this erases all the code after the `?` using statement (try adding a dummy `println!();` after the `?` using statement to test this.).
> 
> I would have expected for `b.span.shrink_to_high()` to suffice, but that may be after the `}`, so you may need to look for the last statement in the block (we know there must be one, as there's a `?`)

Thank you very much. When I adding `println!();` as the last stmt of the block, I find the span of the stmt is `rust\library\std\src\macros.rs:83:23: 85:6`, so I think only use the span of the block is more appropriate.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 7]
```diff
@@ -4586,6 +4586,47 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+            && self.tcx.is_diagnostic_item(sym::Result, def.did())
+        {
+            let body = self.tcx.hir().body(body_id);
+            let mut sugg_spans =
+                vec![(ret_span, " -> Result<(), Box<dyn std::error::Error>>".to_string())];
+
+            if let hir::ExprKind::Block(b, _) = body.value.kind
+                && b.expr.is_none()
+            {
+                // The span will point to the closing curly brace `}` of the block.
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4617]: Please add this information as a doc comment to the `span` field.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 8]
```diff
@@ -4586,6 +4586,47 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                sugg_spans.push((
+                    b.span.shrink_to_hi().with_lo(b.span.hi() - BytePos(1)),
```
Comment (oli-obk) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4619]: since we know there must be at least one statement, you can instead do `b.stmts.last().unwrap().span.shrink_to_hi()`, this way you'll get a span right after the last statement.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 7 above)
Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4617]: Add documentation to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/struct.Block.html#structfield.span stating that this span includes the squirly brackets around the block

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs (hunk 8 above)
Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4619]: > since we know there must be at least one statement, you can instead do `b.stmts.last().unwrap().span.shrink_to_hi()`, this way you'll get a span right after the last statement.

Thank you. I tried this way. But when the last stmt is a macro call like  `println!();`, it's span will point to std 
 like: `D:\source\rust\rust\library\std\src\macros.rs:85:6: 85:6 (#8)`.

Comment (oli-obk) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4619]: ah indeed. hmm... Maybe we should change the value of `Block::span` to not include the brackets around it. We can already obtain the "with brackets" span by taking the span of the outer expression. That's a bit more involved though, as you'd probably need to touch the parser.

I don't think the `- BytePos(1)` will work in case the block itself is created by a macro or other expansion. Please add some tests for async functions, which should show us any problematic behaviour. And try to generate an entire function with a macro and see how your suggestion behaves on that.

Comment (surechen) [reply compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs:4619]: > ah indeed. hmm... Maybe we should change the value of `Block::span` to not include the brackets around it. We can already obtain the "with brackets" span by taking the span of the outer expression. That's a bit more involved though, as you'd probably need to touch the parser.
> 
> I don't think the `- BytePos(1)` will work in case the block itself is created by a macro or other expansion. Please add some tests for async functions, which should show us any problematic behaviour. And try to generate an entire function with a macro and see how your suggestion behaves on that.

Hello, thank you very much.
 I tried async and declaring macros and it handles the case of declaring macros correctly.
For async functions, now the current logic will skip it. I added the corresponding conditions and check a async function like: 

```rust
async fn test2() {
    let mut file = File::create("foo.txt")?;
    println!();
}
```

The fix result will be :
```rust
async fn test2() -> Result<(), Box<dyn std::error::Error>> {
    Ok(())
}
```

The span seems point to the body correct. But after fixed the expr `let mut file = File::create("foo.txt")?;` and `println!();` in the body will be overwriten. 

Because the current logic does not handle the closure situation, and I have not thought of an effective way to repair the closure, I think we can skip it in this PR.

**Comment by oli-obk** [comment]
Thanks for looking into the details!

@bors r+ rollup
