### PR TITLE
Use tcx.symbol_name when determining clashing extern declarations.

### LINKED ISSUE #79581: Overeager warning for clashing external declarations in different wasm import modules
Rustc 1.48.0 gives an incorrect warning about an external symbol being redeclared with a different signature, when the external symbols are in different `wasm_import_module` namespaces.

I tried this code:

```rust
pub mod a {
    #[link(wasm_import_module = "a")]
    extern "C" {
        pub fn foo();
    }
}

pub mod b {
    #[link(wasm_import_module = "b")]
    extern "C" {
        pub fn foo() -> usize;
    }
}
```

I expected to see this happen: Compile without warnings

Instead, this happened:

```
warning: `foo` redeclared with a different signature
  --> src/lib.rs:11:9
   |
4  |         pub fn foo();
   |         ------------- `foo` previously declared here
...
11 |         pub fn foo() -> usize;
   |         ^^^^^^^^^^^^^^^^^^^^^^ this signature doesn't match the previous declaration
   |
   = note: `#[warn(clashing_extern_declarations)]` on by default
   = note: expected `unsafe extern "C" fn()`
              found `unsafe extern "C" fn() -> usize`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```
The same behavior exists on nightly as well:
```
rustc 1.50.0-nightly (825637983 2020-11-18)
binary: rustc
commit-hash: 8256379832b5ecb7f71e8c5e2018446482223c12
commit-date: 2020-11-18
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #79581.

r? @alexcrichton

### CODE REVIEW

File: compiler/rustc_lint/src/builtin.rs [hunk 1]
```diff
@@ -2626,16 +2627,17 @@ impl ClashingExternDeclarations {
...
         let hid = fi.hir_id;
 
-        let name =
-            &tcx.codegen_fn_attrs(tcx.hir().local_def_id(hid)).link_name.unwrap_or(fi.ident.name);
-
-        if self.seen_decls.contains_key(name) {
+        let local_did = tcx.hir().local_def_id(fi.hir_id);
+        let did = local_did.to_def_id();
+        let instance = Instance::new(did, ty::List::identity_for_item(tcx, did));
+        let name = tcx.symbol_name(instance).name.to_string();
```
Comment (nagisa) [inline compiler/rustc_lint/src/builtin.rs:2633]: Could avoid allocating the string here for the `contains_key` and `get` calls.

The if condition below is preexisting but could also be written as:

```rust
if let Some(val) = self.seen_decls.get(name) {
    Some(val)
} else {
    // insert/allocate here.
}
```

It could also use the `HashMap::entry` API to avoid the double-lookup (though it would need to allocate the string unconditionally I believe).

File: compiler/rustc_lint/src/builtin.rs [hunk 2]
```diff
@@ -2595,7 +2596,7 @@ declare_lint! {
 }
 
 pub struct ClashingExternDeclarations {
-    seen_decls: FxHashMap<Symbol, HirId>,
+    seen_decls: FxHashMap<String, HirId>,
```
Comment (nagisa) [inline compiler/rustc_lint/src/builtin.rs:2599]: In theory this could just store `&'tcx str` without an issue, but `impl_lint_pass` does not support lints parametric over a lifetime T_T.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

File: compiler/rustc_lint/src/builtin.rs (hunk 2 above)
Comment (jumbatm) [reply compiler/rustc_lint/src/builtin.rs:2604]: > could just store &'tcx str without an issue

Yeah, you're right -- that would let me avoid the allocation completely.

> the impl_lint_pass! macro does not support lints parametric over a lifetime T_T

I don't think I'll address this in this PR --  I've just added a FIXME note for now,  until `impl_lint_pass!` can take lifetimes.

**Comment by jumbatm** [comment]
This should be good for re-review once green.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by jumbatm** [comment]
Not sure why it failed the first time. @alexcrichton -- can you re-approve?

**Comment by Mark-Simulacrum** [comment]
Ah, @bors r=alexcrichton - the prior approval wouldn't have worked I expect since commits have been pushed since then.

**Comment by rylev** [comment]
@jumbatm @nagisa This was the cause of a minor [perf regression](https://perf.rust-lang.org/compare.html?start=704e47f78b4c8801a3c76f235a5a152e1b60b300&end=7a9b552cb1621c9c57898d147228aab32b65a7c3&stat=instructions:u). I wonder how much of it is the allocation of the symbol name string vs the call `tcx.symbol_name`.

**Comment by jumbatm** [comment]
Thanks for the heads-up. I'll have a look into this.
