### PR TITLE
Detect incorrect vtable alignment during const eval

### LINKED ISSUE #86132: ICE: 'called `Result::unwrap()` on an `Err` value: "`7` is not a power of 2"', compiler/rustc_mir/src/interpret/traits.rs:168:62
### Code

```Rust
use std::mem;
trait Trait {}
const TRAIT_OBJ_UNALIGNED_VTABLE: &Trait =
    unsafe { mem::transmute((&92u8, &[0b_______001_11i128; 128])) };
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (35fff69d0 2021-06-06)
binary: rustc
commit-hash: 35fff69d043b1c0f5c29894e7f4b0da8b039c131
commit-date: 2021-06-06
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
warning: trait objects without an explicit `dyn` are deprecated
 --> mutant.rs:3:36
  |
3 | const TRAIT_OBJ_UNALIGNED_VTABLE: &Trait =
  |                                    ^^^^^ help: use `dyn`: `dyn Trait`
  |
  = note: `#[warn(bare_trait_objects)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2021 edition!
  = note: for more information, see issue #80165 <https://github.com/rust-lang/rust/issues/80165>

warning: constant is never used: `TRAIT_OBJ_UNALIGNED_VTABLE`
 --> mutant.rs:3:1
  |
3 | / const TRAIT_OBJ_UNALIGNED_VTABLE: &Trait =
4 | |     unsafe { mem::transmute((&92u8, &[0b_______001_11i128; 128])) };
  | |____________________________________________________________________^
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "`7` is not a power of 2"', compiler/rustc_mir/src/interpret/traits.rs:168:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (35fff69d0 2021-06-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3 -Z new-llvm-pass-manager=yes -Z unsound-mir-opts=yes -Z polonius=yes -Z polymorphize=yes -C debuginfo=2 -C opt-level=3 --crate-type staticlib

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `TRAIT_OBJ_UNALIGNED_VTABLE`
#1 [eval_to_const_value_raw] simplifying constant for the type system `TRAIT_OBJ_UNALIGNED_VTABLE`
end of query stack
warning: 2 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: trait objects without an explicit `dyn` are deprecated
 --> mutant.rs:3:36
  |
3 | const TRAIT_OBJ_UNALIGNED_VTABLE: &Trait =
  |                                    ^^^^^ help: use `dyn`: `dyn Trait`
  |
  = note: `#[warn(bare_trait_objects)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2021 edition!
  = note: for more information, see issue #80165 <https://github.com/rust-lang/rust/issues/80165>

warning: constant is never used: `TRAIT_OBJ_UNALIGNED_VTABLE`
 --> mutant.rs:3:1
  |
3 | / const TRAIT_OBJ_UNALIGNED_VTABLE: &Trait =
4 | |     unsafe { mem::transmute((&92u8, &[0b_______001_11i128; 128])) };
  | |____________________________________________________________________^
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "`7` is not a power of 2"', compiler/rustc_mir/src/interpret/traits.rs:168:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/35fff69d043b1c0f5c29894e7f4b0da8b039c131/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/35fff69d043b1c0f5c29894e7f4b0da8b039c131/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/35fff69d043b1c0f5c29894e7f4b0da8b039c131/library/core/src/result.rs:1355:5
   3: rustc_mir::interpret::traits::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::read_size_and_align_from_vtable
   4: rustc_mir::interpret::eval_context::InterpCx<M>::size_and_align_of
   5: rustc_mir::interpret::place::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::deref_operand
   6: rustc_mir::interpret::place::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_place
   7: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
   8: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
   9: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
  10: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_allocation_raw>::compute
  11: rustc_query_system::query::plumbing::get_query_impl
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw
  13: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  14: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute
  15: rustc_query_system::query::plumbing::get_query_impl
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
  17: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  18: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute
  19: rustc_query_system::query::plumbing::get_query_impl
  20: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
  21: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  22: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
  23: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  24: rustc_hir::intravisit::Visitor::visit_nested_item
  25: rustc_hir::intravisit::walk_crate
  26: rustc_lint::late::late_lint_crate
  27: rustc_data_structures::sync::join
  28: std::panic::catch_unwind
  29: rustc_interface::passes::analysis
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  32: rustc_interface::passes::QueryContext::enter
  33: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (35fff69d0 2021-06-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3 -Z new-llvm-pass-manager=yes -Z unsound-mir-opts=yes -Z polonius=yes -Z polymorphize=yes -C debuginfo=2 -C opt-level=3 --crate-type staticlib

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `TRAIT_OBJ_UNALIGNED_VTABLE`
#1 [eval_to_const_value_raw] simplifying constant for the type system `TRAIT_OBJ_UNALIGNED_VTABLE`
#2 [eval_to_const_value_raw] simplifying constant for the type system `TRAIT_OBJ_UNALIGNED_VTABLE`
#3 [analysis] running analysis passes on this crate
end of query stack
warning: 2 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by lqd**
This PR fixes #86132 by detecting invalid alignment values for trait objects in the interpreter, and emitting an error about this conversion failure, to avoid the ICE.

I've noticed that the error emitted at https://github.com/rust-lang/rust/blob/a50d72158e08e02cfc051b863017bdbd2c45b637/compiler/rustc_mir/src/interpret/traits.rs#L163-L166 doesn't seem to be present in the const-ub tests, so I've tried adding a test that triggers both of these cases: one for the invalid size, and another for the invalid alignment that #86132 tracks (I have found different magic values triggering different `Align::from_bytes` errors than the "power of 2" one, if need be).

However, when doing that, I *cannot* for the life of me figure out the correct incantation to make these 2 errors trigger with the "it is undefined behavior to use this value" message rather than the "any use of this value will cause an error" lint.

I've tried Oli's suggestions of different values, tuples and arrays, using the transparent wrapper trick from the other tests and I was only able to trigger the regular const-ub errors about the size of the vtable, or that the drop pointer was invalid. Maybe these "type validation failed" errors happen before this part of the interpreter is reached and there just needs some magic incorrect values to bypass them, I don't know.

Since this fixes an ICE, and if the constants are indeed used, these 2 tests will turn into a hard error, I thought I'd open the PR anyways. And if @RalfJung you know of a way I could manage that (if you think that these tests are worth checking that the `throw_ub_format!` does indeed create const-ub errors as we expect) I'd be grateful.

For that reason, r? @RalfJung and cc @oli-obk.

### CODE REVIEW

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+// - a similar test that triggers a previously-untested const UB error: emitted close to the above
+//   error, it checks the correctness of the size
+
+trait Trait {}
+
+// invalid vtable alignment: `1000` is not a power of 2
+const INVALID_VTABLE_ALIGNMENT: &dyn Trait =
+    unsafe { std::mem::transmute((&92u8, &[0usize, 1usize, 1000usize])) };
+//~^ ERROR any use of this value will cause an error
+//~| WARNING this was previously accepted by the compiler
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/ub-incorrect-vtable.rs:13]:
```suggestion
//~| WARNING this was previously accepted by the compiler
//~| invalid vtable: alignment `1000` is not a power of 2
```
should let you test against the error message

**Comment by RalfJung** [comment]
> However, when doing that, I cannot for the life of me figure out the correct incantation to make these 2 errors trigger with the "it is undefined behavior to use this value" message rather than the "any use of this value will cause an error" lint.

This is the error I expected -- it is a UB message coming from regular execution, not part of validation. If you can trigger this bug in validation that will likely ICE as the `read_size_and_align_from_vtable` call currently does not catch these UB messages...

I think what happens is that already during interning (or even earlier), we try to read the vtable and hence run into the "lint" error path. This means we never even reach validation where we would show a hard error and a different message. You could try to set `RUSTC_CTFE_BACKTRACE=1` to see where in the CTFE engine the error originates; the backtrace should tell you which pass of const-evaluation is triggering this.

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs (hunk 1 above)
Comment (lqd) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.rs:13]: it does indeed, thanks a bunch

File: compiler/rustc_mir/src/interpret/traits.rs [hunk 2]
```diff
@@ -158,13 +158,15 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         let size = u64::try_from(self.force_bits(size, pointer_size)?).unwrap();
         let align = vtable.read_ptr_sized(pointer_size * 2)?.check_init()?;
         let align = u64::try_from(self.force_bits(align, pointer_size)?).unwrap();
+        let align = Align::from_bytes(align)
+            .map_err(|e| err_ub_format!("invalid vtable alignment: {}", e))?;
```
[the remark this answers is not in the document]
Comment (lqd) [reply compiler/rustc_mir/src/interpret/traits.rs]: Done

**Comment by lqd** [comment]
> I think what happens is that already during interning (or even earlier), we try to read the vtable and hence run into the "lint" error path. This means we never even reach validation where we would show a hard error and a different message. You could try to set `RUSTC_CTFE_BACKTRACE=1` to see where in the CTFE engine the error originates; the backtrace should tell you which pass of const-evaluation is triggering this.

I'm not super versed in miri traces but there's indeed a difference that seems to match your intuition:
- the UB error message added by this PR seems triggered by what I believe I would call "regular const evaluation" ^^ ([full trace here](https://gist.github.com/lqd/56402a83dd5f3a4526d608e9121b91b8#file-lint-trace-txt))
- while the hard errors -- which I believe are the ones with actual `UndefinedBehaviorInfo`s -- happen during validation ([full trace here](https://gist.github.com/lqd/56402a83dd5f3a4526d608e9121b91b8#file-error-trace-txt))

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs (hunk 1 above)
Comment (lqd) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.rs:12]: I probably also could have used the `error-pattern`, but your idea is a lot better

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+trait Trait {}
+
+const INVALID_VTABLE_ALIGNMENT: &dyn Trait =
+    unsafe { std::mem::transmute((&92u8, &[0usize, 1usize, 1000usize])) };
+//~^ ERROR any use of this value will cause an error
+//~| WARNING this was previously accepted by the compiler
+//~| invalid vtable: alignment `1000` is not a power of 2
+
+const INVALID_VTABLE_SIZE: &dyn Trait =
+    unsafe { std::mem::transmute((&92u8, &[1usize, usize::MAX, 0usize])) };
```
Comment (RalfJung) [inline src/test/ui/consts/const-eval/ub-incorrect-vtable.rs:16]: You might want to use `1usize` as alignment here to make sure that it is actually a valid alignment.

**Comment by RalfJung** [comment]
> while the hard errors -- which I believe are the ones with actual UndefinedBehaviorInfos -- happen during validation 

Their distinguishing factor is that they are `UndefinedBehaviorInfo::ValidationFailure`, are raised during a second phase, after actual const-evalaution, which handles errors differently.

> the UB error message added by this PR seems triggered by what I believe I would call "regular const evaluation"

Yeah, looks like something is dereferencing this reference; I assume there is an implicit reborrow happening somewhere.

I think you should totally keep these testcases, but here's an idea for another one that might trigger a `ValidationFailure`:
```rust
#[repr(transparent)]
struct W<T>(T);

const INVALID_VTABLE_SIZE: W<&dyn Send> =
    unsafe { std::mem::transmute((&92u8, &[1usize, usize::MAX, 0usize])) };
```

In fact, here's how to cause an ICE since this kind of error is not handled properly :joy: 
```rust
#[repr(transparent)]
struct W<T>(T);

// The drop fn is checked before size/align are, so get ourselves a "sufficiently valid" drop fn
fn drop_me(_: *mut usize) {}

const INVALID_VTABLE_SIZE: W<&dyn Send> =
    unsafe { std::mem::transmute((&92u8, &(drop_me as fn(*mut usize), usize::MAX, 1usize))) };
```

**Comment by lqd** [comment]
> I think you should totally keep these testcases, but here's an idea for another one that might trigger a `ValidationFailure`:
> 
> ```rust
> #[repr(transparent)]
> struct W<T>(T);
> 
> const INVALID_VTABLE_SIZE: W<&dyn Send> =
>     unsafe { std::mem::transmute((&92u8, &[1usize, usize::MAX, 0usize])) };
> ```
> 
> The wrapping `W` prevents the compiler from introducing reborrows, which avoids erroring early during evalutaion, so instead now we error late during validation. We error due to a bad drop pointer though, as you said -- which is correct, `1usize` is indeed a bad drop pointer. ;)

yes absolutely, this is what I was alluding to (very obscurely) in the OP: I've seen this "transparent wrapper trick" to prevent reborrows in the `ub-wide-ptr.rs` test. With the test cases above triggering the lint errors, I had tried using `W` and it does indeed create validation failures. I was unfortunately trying to get a validation failure with the lint mesgs -- and that seems more easily doable with the ICE you've found 😂.

I didn't end up adding a test case like this one because invalid drop pointers seemed [well tested](https://github.com/rust-lang/rust/blob/eab201df7028ebb6812c0b1a01702ac6ecfcceed/src/test/ui/consts/const-eval/ub-wide-ptr.rs#L115-L120).

File: src/test/ui/consts/const-eval/ub-incorrect-vtable.rs (hunk 3 above)
Comment (lqd) [reply src/test/ui/consts/const-eval/ub-incorrect-vtable.rs]: very true, I've updated it

**Comment by lqd** [comment]
At least validation is honest about why it ICEs :) https://github.com/rust-lang/rust/blob/eab201df7028ebb6812c0b1a01702ac6ecfcceed/compiler/rustc_mir/src/interpret/validity.rs#L949-L954

**Comment by RalfJung** [comment]
Right, so we should fix that ICE and I can give you some hints for how to do that, but independent of that I think we can first land this one here. Thanks for the patch!

@bors r+ rollup
