### PR TITLE
Extend invalid floating point literal suffix suggestion

### LINKED ISSUE #100527: Extend invalid floating point literal suffix suggestion
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cd25f4d8995bdd3aec09ca788408a2f6)

```rust
fn main() {
    let a = 12.f;
    let b = 34.F;
    let c = 56.l;
    let d = 78.L;
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0610]](https://doc.rust-lang.org/nightly/error-index.html#E0610): `{integer}` is a primitive type and therefore doesn't have fields
 --> src/main.rs:2:16
  |
2 |     let a = 12.f;
  |                ^

error[[E0610]](https://doc.rust-lang.org/nightly/error-index.html#E0610): `{integer}` is a primitive type and therefore doesn't have fields
 --> src/main.rs:3:16
  |
3 |     let b = 34.F;
  |                ^

error[[E0610]](https://doc.rust-lang.org/nightly/error-index.html#E0610): `{integer}` is a primitive type and therefore doesn't have fields
 --> src/main.rs:4:16
  |
4 |     let c = 56.l;
  |                ^

error[[E0610]](https://doc.rust-lang.org/nightly/error-index.html#E0610): `{integer}` is a primitive type and therefore doesn't have fields
 --> src/main.rs:5:16
  |
5 |     let d = 78.L;
  |                ^

For more information about this error, try `rustc --explain E0610`.
error: could not compile `playground` due to 4 previous errors
```

Ideally for all the above invalid ways to writing a floating point literal, the complier should highlight that there are only 2 valid floating point literal suffix "f32" and "f64". Additionally, it may also include a note informing the user that a trailing '0' must be present in floating point literals.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #100527

### CODE REVIEW

**Comment by chenyukang** [comment]
r? @compiler-errors 
Help me review this trivial PR 😁

File: compiler/rustc_typeck/src/check/expr.rs [hunk 1]
```diff
@@ -2184,20 +2184,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 let suffix = chars.collect::<String>();
                 suffix.is_empty() || suffix == "f32" || suffix == "f64"
             };
+            let is_likely_suffix = |fist_chars: &[char], field: &str| {
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2187]:
```suggestion
            let is_likely_suffix = |first_chars: &[char], field: &str| {
```

File: compiler/rustc_typeck/src/check/expr.rs [hunk 2]
```diff
@@ -2184,20 +2184,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 && !base.span.from_expansion()
-                && is_valid_suffix(field_name)
             {
-                err.span_suggestion_verbose(
-                    field.span.shrink_to_lo(),
-                    "If the number is meant to be a floating point number, consider adding a `0` after the period",
-                    '0',
-                    Applicability::MaybeIncorrect,
-                );
+                let msg = "If the number is meant to be a floating point number, consider adding a `0` after the period";
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2199]:
```suggestion
                let msg = "if a floating point literal was intended, consider adding a `0` after the period";
```
pre-existing, but diagnostics shouldn't start with uppercase letters

File: compiler/rustc_typeck/src/check/expr.rs [hunk 3]
```diff
@@ -2184,20 +2184,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        field.span.shrink_to_lo(),
+                        msg,
+                        '0',
+                        Applicability::MaybeIncorrect,
+                    );
+                } else if is_likely_suffix(&['f', 'l'], &field_name) {
+                    err.span_suggestion_verbose(
+                        field.span,
+                        format!("{}, valid float format are `f32` and `f64`", msg),
+                        "0f32",
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2211]: Ideally we would check if the `f` or the `l` case got us here and suggest `f32` or `f64` as appropriate.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 4]
```diff
@@ -2184,20 +2184,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    err.span_suggestion_verbose(
+                        field.span.shrink_to_lo(),
+                        msg,
+                        '0',
+                        Applicability::MaybeIncorrect,
+                    );
+                } else if is_likely_suffix(&['f', 'l'], &field_name) {
+                    err.span_suggestion_verbose(
+                        field.span,
+                        format!("{}, valid float format are `f32` and `f64`", msg),
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2210]:
```suggestion
                        format!("if intended to be a floating point literal, add a `0` after the period and a `{correct_suffix}` suffix"),
```

Maybe we should have a different message for the `is_likely_suffix` case that only mentions the suffix we are suggesting.

**Review by davidtwco — CHANGES_REQUESTED** [review]
This is a good change, I've left some comments.

**Comment by chenyukang** [comment]
Thanks reviewing! @davidtwco

File: compiler/rustc_typeck/src/check/expr.rs [hunk 5]
```diff
@@ -2184,20 +2184,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 && !base.span.from_expansion()
-                && is_valid_suffix(field_name)
             {
-                err.span_suggestion_verbose(
-                    field.span.shrink_to_lo(),
-                    "If the number is meant to be a floating point number, consider adding a `0` after the period",
-                    '0',
-                    Applicability::MaybeIncorrect,
-                );
+                let msg = "if a floating point literal was intended, consider adding a `0` after the period";
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2204]: We can just use this string literal in the argument directly, instead of having this variable, now that it is only used once.

Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2204]:
```suggestion
                let msg = "if intended to be a floating point literal, consider adding a `0` after the period";
```
Just for consistency with the other message.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 6]
```diff
@@ -2184,20 +2184,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 let suffix = chars.collect::<String>();
                 suffix.is_empty() || suffix == "f32" || suffix == "f64"
             };
+            let is_likely_suffix = |first_chars: &[char], field: &str| -> Option<&str> {
+                if field.len() >= 1
+                    && field.to_lowercase().starts_with(first_chars)
+                    && field[1..].chars().all(|c| c.is_ascii_digit())
+                {
+                    if field.to_lowercase().starts_with(['f']) { Some("f32") } else { Some("f64") }
```
Comment (davidtwco) [inline compiler/rustc_typeck/src/check/expr.rs:2192]: With the addition of this condition, the `is_likely_suffix` is a bit less useful because it really only makes sense if `first_chars` is `f` or `l`, so maybe we could just do away with that parameter?

**Review by davidtwco — COMMENTED** [review]
Great! A couple more comments then this should be good.

File: compiler/rustc_typeck/src/check/expr.rs (hunk 6 above)
Comment (chenyukang) [reply compiler/rustc_typeck/src/check/expr.rs:2192]: Sounds reasonable.

Comment (davidtwco) [reply compiler/rustc_typeck/src/check/expr.rs:2192]: I'd probably rename the function to indicate its new specificity if making this change, like `maybe_partial_suffix`/`maybe_likely_suffix` or something?

Comment (chenyukang) [reply compiler/rustc_typeck/src/check/expr.rs:2193]: Updated it!

**Review by davidtwco — APPROVED** [review]

**Comment by chenyukang** [comment]
Forgetted updating a testcase.
