### PR TITLE
Fix for ICE: eii: fn / macro rules None in find_attr()

### LINKED ISSUE #149981: ICE: eii: fn / macro rules  `None` in find_attr()
snippet:
````rust
macro_rules! foo_impl {}
#[eii]
fn foo_impl() {}

````

Version information
````
rustc 1.94.0-nightly (3f4dc1e02 2025-12-14)
binary: rustc
commit-hash: 3f4dc1e02d759aa3c3807d4efc1f7f6e293536a5
commit-date: 2025-12-14
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.5

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/3f4dc1e02d759aa3c3807d4efc1f7f6e293536a5/compiler/rustc_metadata/src/eii.rs#L28-L40

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: macros must contain at least one rule
 --> /tmp/icemaker_global_tempdir.H7kAaxdihhDG/rustc_testrunner_tmpdir_reporting.S9gL24J8ZiLI/mvce.rs:1:1
  |
1 | macro_rules! foo_impl {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature `extern_item_impls`
 --> /tmp/icemaker_global_tempdir.H7kAaxdihhDG/rustc_testrunner_tmpdir_reporting.S9gL24J8ZiLI/mvce.rs:2:3
  |
2 | #[eii]
  |   ^^^
  |
  = note: see issue #125418 <https://github.com/rust-lang/rust/issues/125418> for more information
  = help: add `#![feature(extern_item_impls)]` to the crate attributes to enable
  = note: this compiler was built on 2025-12-14; consider upgrading it if it is out of date

warning: unused macro definition: `foo_impl`
 --> /tmp/icemaker_global_tempdir.H7kAaxdihhDG/rustc_testrunner_tmpdir_reporting.S9gL24J8ZiLI/mvce.rs:1:14
  |
1 | macro_rules! foo_impl {}
  |              ^^^^^^^^
  |
  = note: `#[warn(unused_macros)]` (part of `#[warn(unused)]`) on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.H7kAaxdihhDG/rustc_testrunner_tmpdir_reporting.S9gL24J8ZiLI/mvce.rs:3:17
  |
3 | fn foo_impl() {}
  |                 ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.H7kAaxdihhDG/rustc_testrunner_tmpdir_reporting.S9gL24J8ZiLI/mvce.rs`


thread 'rustc' (3711046) panicked at compiler/rustc_metadata/src/eii.rs:34:106:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f791af90173 - <<std[e49fa185a119b89b]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[17865207963548b5]::fmt::Display>::fmt
   1:     0x7f791b610648 - core[17865207963548b5]::fmt::write
   2:     0x7f791afa67c6 - <std[e49fa185a119b89b]::sys::stdio::unix::Stderr as std[e49fa185a119b89b]::io::Write>::write_fmt
   3:     0x7f791af66938 - std[e49fa185a119b89b]::panicking::default_hook::{closure#0}
   4:     0x7f791af84043 - std[e49fa185a119b89b]::panicking::default_hook
   5:     0x7f7919f741d7 - std[e49fa185a119b89b]::panicking::update_hook::<alloc[756b9f94e2773738]::boxed::Box<rustc_driver_impl[e1c4671be5271ce8]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f791af84322 - std[e49fa185a119b89b]::panicking::panic_with_hook
   7:     0x7f791af66a2a - std[e49fa185a119b89b]::panicking::panic_handler::{closure#0}
   8:     0x7f791af5dab9 - std[e49fa185a119b89b]::sys::backtrace::__rust_end_short_backtrace::<std[e49fa185a119b89b]::panicking::panic_handler::{closure#0}, !>
   9:     0x7f791af685ad - __rustc[df3bb69314ad135f]::rust_begin_unwind
  10:     0x7f791826df0c - core[17865207963548b5]::panicking::panic_fmt
  11:     0x7f7917775122 - core[17865207963548b5]::panicking::panic
  12:     0x7f7918767e39 - core[17865207963548b5]::option::unwrap_failed
  13:     0x7f791c77747e - rustc_metadata[2002d9e21ce78884]::eii::collect
  14:     0x7f791c77759e - rustc_query_impl[462c6a5584cea8d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[462c6a5584cea8d4]::query_impl::externally_implementable_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 8usize]>>
  15:     0x7f791bad7a77 - rustc_query_system[5be0c069f6d5c539]::query::plumbing::try_execute_query::<rustc_query_impl[462c6a5584cea8d4]::DynamicConfig<rustc_data_structures[30161969bbcb553f]::vec_cache::VecCache<rustc_span[ce53af16555a42ff]::def_id::CrateNum, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5be0c069f6d5c539]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[462c6a5584cea8d4]::plumbing::QueryCtxt, false>
  16:     0x7f791bad0f49 - rustc_query_impl[462c6a5584cea8d4]::query_impl::externally_implementable_items::get_query_non_incr::__rust_end_short_backtrace
  17:     0x7f791bad02ba - rustc_passes[9766a5655bde9e6]::eii::check_externally_implementable_items
  18:     0x7f791bad022f - rustc_query_impl[462c6a5584cea8d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[462c6a5584cea8d4]::query_impl::check_externally_implementable_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 0usize]>>
  19:     0x7f791c7725a6 - rustc_query_system[5be0c069f6d5c539]::query::plumbing::try_execute_query::<rustc_query_impl[462c6a5584cea8d4]::DynamicConfig<rustc_query_system[5be0c069f6d5c539]::query::caches::SingleCache<rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[462c6a5584cea8d4]::plumbing::QueryCtxt, false>
  20:     0x7f791c77238e - rustc_query_impl[462c6a5584cea8d4]::query_impl::check_externally_implementable_items::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7f791b6ec481 - rustc_interface[50af632e35c6bce3]::passes::analysis
  22:     0x7f791b6ec2e5 - rustc_query_impl[462c6a5584cea8d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[462c6a5584cea8d4]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 0usize]>>
  23:     0x7f791c7725a6 - rustc_query_system[5be0c069f6d5c539]::query::plumbing::try_execute_query::<rustc_query_impl[462c6a5584cea8d4]::DynamicConfig<rustc_query_system[5be0c069f6d5c539]::query::caches::SingleCache<rustc_middle[7055997c00c0bb98]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[462c6a5584cea8d4]::plumbing::QueryCtxt, false>
  24:     0x7f791c772176 - rustc_query_impl[462c6a5584cea8d4]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7f791c92cdd4 - <rustc_interface[50af632e35c6bce3]::passes::create_and_enter_global_ctxt<core[17865207963548b5]::option::Option<rustc_interface[50af632e35c6bce3]::queries::Linker>, rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[17865207963548b5]::ops::function::FnOnce<(&rustc_session[307f8e7a4263bd4]::session::Session, rustc_middle[7055997c00c0bb98]::ty::context::CurrentGcx, alloc[756b9f94e2773738]::sync::Arc<rustc_data_structures[30161969bbcb553f]::jobserver::Proxy>, &std[e49fa185a119b89b]::sync::once_lock::OnceLock<rustc_middle[7055997c00c0bb98]::ty::context::GlobalCtxt>, &rustc_data_structures[30161969bbcb553f]::sync::worker_local::WorkerLocal<rustc_middle[7055997c00c0bb98]::arena::Arena>, &rustc_data_structures[30161969bbcb553f]::sync::worker_local::WorkerLocal<rustc_hir[5d00f225b65c0257]::Arena>, rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  26:     0x7f791c7c19da - rustc_interface[50af632e35c6bce3]::interface::run_compiler::<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}
  27:     0x7f791c731d8e - std[e49fa185a119b89b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[50af632e35c6bce3]::util::run_in_thread_with_globals<rustc_interface[50af632e35c6bce3]::util::run_in_thread_pool_with_globals<rustc_interface[50af632e35c6bce3]::interface::run_compiler<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  28:     0x7f791c731b60 - <std[e49fa185a119b89b]::thread::lifecycle::spawn_unchecked<rustc_interface[50af632e35c6bce3]::util::run_in_thread_with_globals<rustc_interface[50af632e35c6bce3]::util::run_in_thread_pool_with_globals<rustc_interface[50af632e35c6bce3]::interface::run_compiler<(), rustc_driver_impl[e1c4671be5271ce8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[17865207963548b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7f791c7374f8 - <std[e49fa185a119b89b]::sys::thread::unix::Thread>::new::thread_start
  30:     0x7f79160969cb - <unknown>
  31:     0x7f791611aa0c - <unknown>
  32:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.94.0-nightly (3f4dc1e02 2025-12-14) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [externally_implementable_items] looking up the externally implementable items of a crate
#1 [check_externally_implementable_items] check externally implementable items
#2 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by jdonszelmann**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/150822)*

Closes rust-lang/rust#149981

This used to ICE:
```rust
macro_rules! foo_impl {}
#[eii]
fn foo_impl() {}
```

`#[eii]` generates a macro (called `foo_impl`) and a default impl. So the partial expansion used to roughly look like the following:

```rust
macro_rules! foo_impl {} // actually resolves here

extern "Rust" {
    fn foo_impl();
}

#[eii_extern_target(foo_impl)]
macro foo_impl {
    () => {};
}

const _: () = {
    #[implements_eii(foo_impl)] // assumed to name resolve to the macro v2 above
    fn foo_impl() {}
};
```

Now, shadowing rules for macrov2 and macrov1 are super weird! Take a look at this: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=23f21421921360478b0ec0276711ad36

So instead of resolving to the macrov2, we resolve the macrov1 named the same thing.

A regression test was added to this, and some span_delayed_bugs were added to make sure we catch this in the right places. But that didn't fix the root cause.

To make sure this simply cannot happen again, I made it so that we don't even need to do a name resolution for the default. In other words, the new partial expansion looks more like:

```rust
macro_rules! foo_impl {}

extern "Rust" {
    fn foo_impl(); // resolves to here now!!!
}

#[eii_extern_target(foo_impl)]
macro foo_impl {
    () => {};
}

const _: () = {
    #[implements_eii(known_extern_target=foo_impl)] // still name resolved, but directly to the foreign function. 
    fn foo_impl() {}
};
```

The reason this helps is that name resolution for non-macros is much more predictable. It's not possible to have two functions like that with the same name in scope.

We used to key externally implementable items off of the defid of the macro, but now the unique identifier is the foreign function's defid which seems much more sane.

Finally, I lied a tiny bit because the above partial expansion doesn't actually work.
```rust
extern "Rust" {
    fn foo_impl(); // not to here
}

const _: () = {
    #[implements_eii(known_extern_target=foo_impl)] // actually resolves to this function itself
    fn foo_impl() {} // <--- so to here
};
```

So the last few commits change the expansion to actually be this:

```rust
macro_rules! foo_impl {}

extern "Rust" {
    fn foo_impl(); // resolves to here now!!!
}

#[eii_extern_target(foo_impl)]
macro foo_impl {
    () => {};
}

const _: () = {
    mod dflt { // necessary, otherwise `super` doesn't work
        use super::*;
        #[implements_eii(known_extern_target=super::foo_impl)] // now resolves to outside the `dflt` module, so the foreign item.
        fn foo_impl() {}
    }
};
```

I apologize to whoever needs to review this, this is very subtle and I hope this makes it clear enough :sob:.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/codegen_attrs.rs [hunk 1]
```diff
@@ -285,15 +287,22 @@ fn process_builtin_attrs(
...
+                                    tcx.dcx().span_delayed_bug(
+                                        i.span,
+                                        "resolved to something that's not an EII",
+                                    );
+                                    continue;
+                                };
+                                extern_item
+                            }
+                            EiiImplResolution::Known(decl, _) => decl.eii_extern_target,
+                            EiiImplResolution::Error(_eg) => continue,
```
Comment (Kivooeo) [inline compiler/rustc_codegen_ssa/src/codegen_attrs.rs:305]: was this `_eg` a leftover from some logic here? i see the same pattern in many places (where you match for error), could you explain this a little, cuz it's not really obvious to me why we want to skip errors 

also it would be nice to clean up this unusable variables a bit

Comment (jdonszelmann) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs:305]: no, it's just a good reminder that if we get there, we're allowed to skip it because an error is already emitted.
I tried to separate out the logic of this, but I don't think I prefer it. A method on EiiImplResolution would make sense, but we need the tcx which we don't have in rustc_hir, so the signature would be super awkward, requiring an FnOnce to be passed in or something to get the attributes. I really did consider it but I personally believe this is nicest

Comment (jdonszelmann) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs:305]: And yea, the eg is technically never used. I just wanted to make sure for myself I wouldn't accidentally skip EIIs without having a very good reason for it

Comment (Kivooeo) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs:305]: yeah, that makes sense, will continue looking into this pr, not sure how much time it will take, i hopefully might finish it later today (it's a jan 9th and it's a bit late at my place)

i dit a quick glance a first 4-5 commits, looks fine overall

**Comment by Kivooeo** [comment]
r? me

File: compiler/rustc_codegen_ssa/src/codegen_attrs.rs (hunk 1 above)
Comment (jdonszelmann) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs:305]: thanks kivoo! You're amazing

File: compiler/rustc_builtin_macros/src/eii.rs [hunk 2]
```diff
@@ -236,18 +252,66 @@ fn generate_default_impl(
...
                                 vis: ast::Visibility {
-                                    span: eii_attr_span,
+                                    span: item_span,
                                     kind: ast::VisibilityKind::Inherited,
                                     tokens: None
                                 },
-                                kind: ItemKind::Fn(Box::new(default_func)),
+                                kind: ItemKind::Mod(
+                                    ast::Safety::Default,
+                                    Ident::from_str_and_span("dflt", item_span),
```
Comment (Kivooeo) [inline compiler/rustc_builtin_macros/src/eii.rs:265]: wondering what is `dflt` stands for, is that kinda acronym?

Comment (jdonszelmann) [reply compiler/rustc_builtin_macros/src/eii.rs:265]: Default, but couldn't call it that

Comment (jdonszelmann) [reply compiler/rustc_builtin_macros/src/eii.rs:265]: This module contains the default implementation

File: compiler/rustc_builtin_macros/src/eii.rs [hunk 3]
```diff
@@ -236,18 +252,66 @@ fn generate_default_impl(
...
+                                    ast::ModKind::Loaded(
+                                        thin_vec![
+                                            Box::new(ast::Item {
+                                                attrs: thin_vec![ecx.attr_nested_word(
+                                                    sym::allow,
+                                                    sym::unused_imports,
+                                                    item_span
+                                                ),],
```
Comment (Kivooeo) [inline compiler/rustc_builtin_macros/src/eii.rs:273]: oh, and this is interesting too

looking at example from pr description i don't see this attribute here

```rust
const _: () = {
    mod dflt { // necessary, otherwise `super` doesn't work
        use super::*;
        #[implements_eii(known_extern_target=super::foo_impl)] // now resolves to outside the `dflt` module, so the foreign item.
        fn foo_impl() {}
    }
};
```

there are some cases where `super` could be potentially unused?

Comment (jdonszelmann) [reply compiler/rustc_builtin_macros/src/eii.rs:273]: Indeed, I left it out of the description. Super is unused in the test for example. When we don't use any type or name from the surrounding scope

Comment (jdonszelmann) [reply compiler/rustc_builtin_macros/src/eii.rs:273]: In almost all cases it is used of course, but I didn't want warnings generated by a to the user invisible import. To the user it should be as if the default function actually lives in the surrounding scope.
