### PR TITLE
fix a crash in rustdoc merge finalize without input file

### LINKED ISSUE #146646: rustdoc crashes when running --merge=finalize without an input crate root
### Repro

```sh
WHICH_RUSTDOC=rustdoc

"$WHICH_RUSTDOC" --version

rm -rf repro
mkdir repro

# make an empty crate (the source code doesn't matter)
touch repro/base.rs 

# get doc.parts for this crate
"$WHICH_RUSTDOC" \
    --out-dir repro/doc \
    -Zunstable-options \
    --merge=none \
    --parts-out-dir repro/doc.parts/base \
    repro/base.rs

# try to run --merge=finalize without an input crate
"$WHICH_RUSTDOC" \
    --out-dir repro/merged \
    -Zunstable-options \
    --merge=finalize \
    --include-parts-dir repro/doc.parts/base
```

### Output

```
rustdoc 1.92.0-nightly (a454fccb0 2025-09-15)

thread 'main' (503139) panicked at /rust/deps/scoped-tls-1.0.1/src/lib.rs:168:9:
cannot access a scoped thread local variable without calling `set` first
stack backtrace:
   0:     0x7f7af5a4bdf3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h830fbe15fbab381b
   1:     0x7f7af6201b58 - core::fmt::write::hf661a9e75db120a3
   2:     0x7f7af5a00d71 - std::io::Write::write_fmt::he76c5adbbdfd1600
   3:     0x7f7af5a11d22 - std::sys::backtrace::BacktraceLock::print::hb87325f2dc6d4dfe
   4:     0x7f7af5a17c69 - std::panicking::default_hook::{{closure}}::h5e01ba9de3335cc4
   5:     0x7f7af5a17793 - std::panicking::default_hook::h47934e1f610fefc5
   6:     0x7f7af4a08797 - std[c207121dba9f4102]::panicking::update_hook::<alloc[fbc11b1b12ed36cd]::boxed::Box<rustc_driver_impl[d9438a736
c8997f5]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f7af5a1808f - std::panicking::panic_with_hook::hfee0edaf348ac547
   8:     0x7f7af5a1763c - std::panicking::begin_panic::{{closure}}::hfab281f595fe6b8e
   9:     0x7f7af5a11e59 - std::sys::backtrace::__rust_end_short_backtrace::h18cba0a351de3087
  10:     0x7f7af3117d14 - std::panicking::begin_panic::h3e51ad6bf38ddb4a
  11:     0x7f7af63e62fd - <rustc_span[acd9e562735339de]::symbol::Symbol>::intern
  12:     0x5607faf93963 - rustdoc[de4b4e234c0ac729]::html::render::write_shared::write_rendered_cross_crate_info
  13:     0x5607faf8f90a - rustdoc[de4b4e234c0ac729]::html::render::write_shared::write_not_crate_specific
  14:     0x5607fae3f8ad - rustdoc[de4b4e234c0ac729]::main_args
  15:     0x5607fae39e34 - rustdoc[de4b4e234c0ac729]::main
  16:     0x5607fb09b943 - std[c207121dba9f4102]::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  17:     0x5607fb09b959 - std[c207121dba9f4102]::rt::lang_start::<()>::{closure#0}
  18:     0x7f7af73fb8a5 - std::rt::lang_start_internal::h78f37f9ccd5c4fa5
  19:     0x5607fb09b9a8 - main
  20:     0x7f7af0c33ca8 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7f7af0c33d65 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  22:     0x5607fab45ec4 - <unknown>
  23:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/usr/local/google/home/ethanws/rustdoc-investigation/rustc-ice-2025-09-16T16_34_16-503139.txt` to your bu
g report

note: compiler flags: -Z unstable-options

query stack during panic:
end of query stack
```

### Motivation

Being able to run rustdoc without an input crate root in the --merge=finalize mode is a core workflow described in [RFC 3662](https://rust-lang.github.io/rfcs/3662-mergeable-rustdoc-cross-crate-info.html), "This flag may be used with or without an input crate root, in which case it only links crates included via --include-parts-dir."

The commit 8511e40e7294e1efcc64b81d43969b6bf0f14c2d seems to have introduced the call to Symbol::intern that appears in the above backtrace.

### Calling rustdoc --merge=finalize with a crate root causes no crash

```sh
WHICH_RUSTDOC=rustdoc

"$WHICH_RUSTDOC" --version

rm -rf repro
mkdir repro

# make an empty crate (the source code doesn't matter)
touch repro/base.rs 

# get doc.parts for this crate
"$WHICH_RUSTDOC" \
    --out-dir repro/doc \
    -Zunstable-options \
    --merge=none \
    --parts-out-dir repro/doc.parts/base \
    repro/base.rs

# Add crate root
touch repro/input.rs

"$WHICH_RUSTDOC" \
    --out-dir repro/merged \
    -Zunstable-options \
    --merge=finalize \
    --include-parts-dir repro/doc.parts/base \
    repro/input.rs # crate root
```

### PR DESCRIPTION
**Pull request by el-ev**
- Closes rust-lang/rust#146646 

`SerializedSearchIndex::union` calls `Symbol::intern`, requiring `SESSION_GLOBALS` to be set.

### CODE REVIEW

**Comment by el-ev** [comment]
I tried but couldn't write a test. The test utility automatically passes the current file path to `rustdoc`, so there's always an input file and it won't crash. I would appreciate any help with this.

**Comment by GuillaumeGomez** [comment]
You can create a `run-make` tests like `tests/run-make/rustdoc-map-file/rmake.rs`.

File: tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        .arg("--parts-out-dir=parts")
+        .arg("--merge=none")
+        .run();
+
+    rustdoc()
+        .arg("-Zunstable-options")
+        .arg("--include-parts-dir=parts")
+        .arg("--merge=finalize")
+        .out_dir("out")
+        .run();
```
Comment (GuillaumeGomez) [inline tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: Please add a check to the output to ensure it doesn't crash.

Also, since you don't create a `parts` folder, I'm pretty sure it actually doesn't test the error:

```
error: --include-parts-dir expected parts/crate-info to be a file
```

So you need to create the folder and also the `crate-info` file into it too, and not empty too apparently otherwise we get:

```
error: could not write merged cross-crate info: "parts/crate-info": EOF while parsing a value at line 1 column 0
```

Comment (el-ev) [reply tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: > Also, since you don't create a parts folder, I'm pretty sure it actually doesn't test the error

It doesn't test the error, it tests an ICE described in the linked issue.

> So you need to create the folder and also the crate-info file into it too.

They should be created in the previous step by setting `--parts-out-dir=parts`.

Comment (GuillaumeGomez) [reply tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: Hum then it's surprising because I can't seem to reproduce it with latest nightly:

```
rustdoc 1.92.0-nightly (9f32ccf35 2025-09-21)
```

Comment (el-ev) [reply tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: That's strange. I can still reproduce it:

```
❯ rustdoc -vV
rustdoc 1.92.0-nightly (9f32ccf35 2025-09-21)
binary: rustdoc
commit-hash: 9f32ccf35fb877270bc44a86a126440f04d676d0
commit-date: 2025-09-21
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.1
❯ touch test.rs
❯ rustdoc test.rs -Zunstable-options --parts-out-dir=/tmp/parts_tmp --merge=none
❯ rustdoc -Zunstable-options --include-parts-dir=/tmp/parts_tmp --merge=finalize

thread 'main' (4343049) panicked at /rust/deps/scoped-tls-1.0.1/src/lib.rs:168:9:
```

Comment (GuillaumeGomez) [reply tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: Ah yes, got it. So two things missing: please check that the first command succeeded and created the expected files. And then check that the second command output doesn't contain the string `error: internal compiler error:`.

Comment (el-ev) [reply tests/run-make/rustdoc-merge-no-input-finalize/rmake.rs:26]: Updated. `.run()` already implies a successful exit check.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup
