### PR TITLE
Make dataflow-based const qualification the canonical one

### LINKED ISSUE #66167: ICE in const fn evaluation - Disagreement between legacy and dataflow-based const validators when a const fn takes &mut self
### Error

```rust
error[E0493]: destructors cannot be evaluated at compile-time
   --> cargo/azul-core/../../azul-core/dom.rs:895:69
    |
895 |     pub const fn set_node_type(&mut self, node_type: NodeType<T>) { self.node_type = node_type; }
    |                                                                     ^^^^^^^^^^^^^^ constant functions cannot evaluate destructors

error[E0019]: constant function contains unimplemented expression type
   --> cargo/azul-core/../../azul-core/dom.rs:895:69
    |
895 |     pub const fn set_node_type(&mut self, node_type: NodeType<T>) { self.node_type = node_type; }
    |                                                                     ^^^^^^^^^^^^^^

[ERROR rustc_mir::transform::qualify_consts] old validator: [(cargo/azul-core/../../azul-core/dom.rs:895:69: 895:83, "LiveDrop"), (cargo/azul-core/../../azul-core/dom.rs:895:69: 895:83, "MutDeref")]
[ERROR rustc_mir::transform::qualify_consts] new validator: [(cargo/azul-core/../../azul-core/dom.rs:895:69: 895:83, "MutDeref"), (cargo/azul-core/../../azul-core/dom.rs:895:69: 895:83, "LiveDrop")]
error: internal compiler error: src/librustc_mir/transform/qualify_consts.rs:1986: Disagreement between legacy and dataflow-based const validators.
    After filing an issue, use `-Zsuppress-const-validation-back-compat-ice` to compile your code.
   --> cargo/azul-core/../../azul-core/dom.rs:895:5
    |
895 |     pub const fn set_node_type(&mut self, node_type: NodeType<T>) { self.node_type = node_type; }
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Backtrace

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:890:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_context_opt
  18: rustc::ty::context::tls::with_opt
  19: rustc::util::bug::opt_span_bug_fmt
  20: rustc::util::bug::span_bug_fmt
  21: rustc_mir::transform::qualify_consts::Checker::check_const
  22: <rustc_mir::transform::qualify_consts::QualifyAndPromoteConstants as rustc_mir::transform::MirPass>::run_pass
  23: rustc_mir::transform::run_passes
  24: rustc_mir::transform::mir_validated
  25: rustc::ty::query::__query_compute::mir_validated
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_validated>::compute
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  29: rustc_mir::borrow_check::mir_borrowck
  30: rustc::ty::query::__query_compute::mir_borrowck
  31: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  32: rustc::dep_graph::graph::DepGraph::with_task_impl
  33: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  34: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  35: rustc_interface::passes::analysis
  36: rustc::ty::query::__query_compute::analysis
  37: rustc::dep_graph::graph::DepGraph::with_task_impl
  38: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  39: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  40: rustc_interface::passes::create_global_ctxt::{{closure}}
  41: rustc_interface::passes::BoxedGlobalCtxt::enter
  42: rustc_interface::interface::run_compiler_in_existing_thread_pool
  43: std::thread::local::LocalKey<T>::with
  44: scoped_tls::ScopedKey<T>::set
  45: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (1423bec54 2019-11-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type rlib --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_validated] processing `dom::NodeData::<T>::set_node_type`
#1 [mir_borrowck] processing `dom::NodeData::<T>::set_node_type`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (1423bec54 2019-11-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type rlib --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0019, E0493.
For more information about an error, try `rustc --explain E0019`.
error: could not compile `azul-core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Code

https://github.com/maps4print/azul/tree/rust-const-ice 

Commit https://github.com/maps4print/azul/commit/b38fb1bc3476ee47d313e891642f7673092e080b

Changed here: https://github.com/maps4print/azul/commit/b38fb1bc3476ee47d313e891642f7673092e080b#diff-ce9aead5dc9a44d99879f251fc571013R897

Code: https://github.com/maps4print/azul/blob/b38fb1bc3476ee47d313e891642f7673092e080b/azul-core/dom.rs#L895

### Reproducing the bug

```shell
rustup update
git clone https://github.com/maps4print/azul
git checkout rust-const-ice
cargo check
```

### Description

I was trying to turn a couple of functions that take a `&mut self` into const fns - which should technically work:

```rust
struct Dom { a: usize }

impl Dom {
    const fn do_thing(&mut self, a: usize) { self.a = a; }
}
```

As far as I can see, only the ordering of liveness-checking is wrong, the old liveness checker reports `["LiveDrop", "MutDeref"]` while the new liveness checker reports `["MutDeref", "LiveDrop"]`. Should be an easy (?) bug to fix (famous last words).

### Rust version:
```
rustc 1.40.0-nightly (1423bec54 2019-11-05)
binary: rustc
commit-hash: 1423bec54cf2db283b614e527cfd602b481485d1
commit-date: 2019-11-05
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by ecstatic-morse**
For over a month, dataflow-based const qualification has been running in parallel with `qualify_consts` to check the bodies of `const` and `static`s. This PR removes the old qualification pass completely in favor of the dataflow-based one.

**edit:**
This PR also stops checking `QUALIF_ERROR_BIT` during promotion. This check appears to no longer serve a purpose now that the CTFE engine is more robust.

As a side-effect, this resolves #66167.

r? @eddyb

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Marking as draft since this depends on #66170.

**Comment by ecstatic-morse** [comment]
`Unpromotable` is added to `QualifSet` to preserve the existing behavior of code [such as the following](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2916b8be73622e5ae1f1347f75474319), where `&X` is not promotd:

```rust
#![feature(const_panic)]
#![allow(const_err)]

const X: u32 = panic!();

fn main() {
    let x: &'static _ = &X;
}
```

File: src/librustc_mir/transform/check_consts/qualifs.rs [hunk 1]
```diff
@@ -5,26 +5,67 @@ use rustc::mir::interpret::ConstValue;
...
 use super::{ConstKind, Item as ConstCx};
 
-#[derive(Clone, Copy)]
-pub struct QualifSet(u8);
+#[derive(Clone, Copy, Default)]
+pub struct QualifSet(pub u8);
 
 impl QualifSet {
-    fn contains<Q: ?Sized + Qualif>(self) -> bool {
+    pub const UNPROMOTABLE: Self = QualifSet(1 << Unpromotable::IDX);
```
Comment (eddyb) [inline src/librustc_mir/transform/check_consts/qualifs.rs]: Can we stop using this hack, btw?

File: src/librustc_mir/transform/mod.rs [hunk 2]
```diff
@@ -185,6 +184,41 @@ pub fn run_passes(
...
+
+    // N.B., this `borrow()` is guaranteed to be valid (i.e., the value
+    // cannot yet be stolen), because `mir_validated()`, which steals
+    // from `mir_const(), forces this query to execute before
+    // performing the steal.
+    let body = &tcx.mir_const(def_id).borrow();
+
+    if body.return_ty().references_error() {
+        tcx.sess.delay_span_bug(body.span, "mir_const_qualif: MIR had errors");
+        return check_consts::QualifSet::UNPROMOTABLE.into();
```
Comment (eddyb) [inline src/librustc_mir/transform/mod.rs]: Does anything break if you use `QualifSet::default()` here?

File: src/librustc_mir/transform/check_consts/qualifs.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/qualifs.rs]: There's only two places it can appear now. One is where you left a comment below, which doesn't seem to break anything. The other is when a `const` panics unconditionally, which is just a hack to approximate the existing behavior. I'll try removing it completely.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/qualifs.rs]: I've removed `UNPROMOTABLE`. Let's see what happens with CI.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/qualifs.rs]: We pass all the tests, and I've tried the following example locally and no ICE occurs, just an error pointing to `X` saying that const evaluation failed.

```rust
#![feature(const_panic)]
#![allow(const_err)]

const X: u32 = panic!();

fn main() {
    let x: &'static _ = &X;
}
```

File: src/librustc_mir/transform/mod.rs (hunk 2 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/mod.rs]: Apparently not :smiley:

File: src/librustc_mir/transform/mod.rs [hunk 3]
```diff
@@ -185,6 +185,41 @@ pub fn run_passes(
     body.phase = mir_phase;
 }
 
+fn mir_const_qualif(tcx: TyCtxt<'_>, def_id: DefId) -> u8 {
```
Comment (Centril) [inline src/librustc_mir/transform/mod.rs]: A doc comment would be good especially for the return type.

File: src/librustc_mir/transform/check_consts/validation.rs [hunk 4]
```diff
@@ -264,6 +314,25 @@ impl Validator<'a, 'mir, 'tcx> {
...
+        bb: BasicBlock,
+        block: &BasicBlockData<'tcx>,
+    ) {
+        trace!("visit_basic_block_data: bb={:?} is_cleanup={:?}", bb, block.is_cleanup);
+
+        // Just as the old checker did, we skip const-checking basic blocks on the unwind path.
+        // These blocks often drop locals that would otherwise be returned from the function.
+        //
+        // FIXME: This shouldn't be unsound since a panic at compile time will cause a compiler
+        // error anyway, but maybe we should do more here?
```
Comment (Centril) [inline src/librustc_mir/transform/check_consts/validation.rs]: "If you have to ask..."? ;)

File: src/test/ui/consts/miri_unleashed/enum_discriminants.rs [hunk 5]
```diff
@@ -1,6 +1,9 @@
-// compile-flags: -Zunleash-the-miri-inside-of-you
+// compile-flags: -Zunleash-the-miri-inside-of-you -Awarnings
```
Comment (Centril) [inline src/test/ui/consts/miri_unleashed/enum_discriminants.rs]: I would prefer not to do this so that we can see changes in diffs and whatnot.

File: src/test/ui/consts/const-eval/issue-65394.rs [hunk 6]
```diff
@@ -1,7 +1,10 @@
-// Test for absence of validation mismatch ICE in #65394
+// This test originated from #65394. We conservatively assume that `x` is still `LiveDrop` even
+// after it has been moved because a mutable reference to it exists at some point in the const body.
+//
+// We will likely have to change this behavior vefore we allow `&mut` in a `const`.
```
Comment (matthewjasper) [inline src/test/ui/consts/const-eval/issue-65394.rs]: s/vefore/before/

File: src/librustc_mir/transform/mod.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_mir/transform/mod.rs]: I think we can replace it now with:
```rust
struct ConstQualif {
    has_mut_interior: bool,
    needs_drop: bool,
}
```

Comment (eddyb) [reply src/librustc_mir/transform/mod.rs]: I think we can replace it now with:
```rust
struct ConstQualif {
    has_mut_interior: bool,
    needs_drop: bool,
}
```

File: src/test/ui/consts/miri_unleashed/enum_discriminants.rs (hunk 5 above)
Comment (ecstatic-morse) [reply src/test/ui/consts/miri_unleashed/enum_discriminants.rs]: The "const check ignored" annotations were only added last week since they are now mandatory in all UI tests. They are unrelated to the actual purpose of the test, they just add noise (to both the test itself and PRs that work on const qualification). Ignoring warnings was explicitly mentioned as an opt-out path for tests like this.

**Comment by ecstatic-morse** [comment]
Rebased to fix merge conflicts. The latest version moves `QualifSet` into `rustc::mir` and uses it everywhere.

File: src/librustc_mir/transform/mod.rs (hunk 3 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/mod.rs]: This change was made in the latest version.

File: src/librustc/mir/mod.rs [hunk 7]
```diff
@@ -2769,6 +2769,13 @@ pub struct BorrowCheckResult<'tcx> {
     pub used_mut_upvars: SmallVec<[Field; 8]>,
 }
 
+/// The result of the `mir_const_qualif` query.
+#[derive(Clone, Copy, Debug, Default, RustcEncodable, RustcDecodable, HashStable)]
+pub struct QualifSet {
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: I don't think "set" is relevant anymore, the bitset was really just an optimization.
`ConstQualifs` might be better. Or `ValueQualifs`?

File: src/librustc/mir/mod.rs [hunk 8]
```diff
@@ -2769,6 +2769,13 @@ pub struct BorrowCheckResult<'tcx> {
...
+    pub has_mut_interior: bool,
+    pub needs_drop: bool,
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: I wonder if these two fields should have similar doc comments to the `HasMutInterior` and `NeedsDrop` types in `rustc_mir::transform::check_consts`.

File: src/librustc/query/mod.rs [hunk 9]
```diff
@@ -93,7 +93,7 @@ rustc_queries! {
         /// Maps DefId's that have an associated `mir::Body` to the result
         /// of the MIR qualify_consts pass. The actual meaning of
         /// the value isn't known except to the pass itself.
```
Comment (eddyb) [inline src/librustc/query/mod.rs]: This doc comment should be updated.

File: src/librustc/mir/mod.rs (hunk 8 above)
Comment (ecstatic-morse) [reply src/librustc/mir/mod.rs]: Would a link to the `Qualif` implementers suffice? I don't wanna copy-paste lest they get out of sync.

File: src/librustc/mir/mod.rs (hunk 7 above)
Comment (ecstatic-morse) [reply src/librustc/mir/mod.rs]: I would lean towards `ConstQualifs` since `IsNotPromotable` is no longer, but either is fine.

File: src/librustc_metadata/rmeta/mod.rs [hunk 10]
```diff
@@ -295,7 +295,7 @@ enum EntryKind<'tcx> {
 /// Additional data for EntryKind::Const and EntryKind::AssocConst
 #[derive(Clone, Copy, RustcEncodable, RustcDecodable)]
 struct ConstQualif {
```
Comment (eddyb) [inline src/librustc_metadata/rmeta/mod.rs]: I don't think there's a point in having this newtype.

File: src/librustc/mir/mod.rs (hunk 8 above)
Comment (eddyb) [reply src/librustc/mir/mod.rs]: Oh I wasn't thinking copy-pasting, maybe a few words and a link (or even just the `rustc_mir::...::HasMutInterior` etc. path).

Comment (ecstatic-morse) [reply src/librustc/mir/mod.rs]: I added a note on `ConstQualifs` that points the user to `librustc_mir/transform/check_consts/qualifs.rs`. Lemme know if you want something more here.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 4 above)
Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/validation.rs]: @eddyb I was hoping someone could authoritatively tell me we don't need to do anything for cleanup blocks. I'm pretty sure we don't.

**Comment by ecstatic-morse** [comment]
@eddyb I believe I've resolved all your posted concerns. Let me know what else needs to be done.

**Review by eddyb — APPROVED** [review]
