### PR TITLE
E0599 suggestions and elision of generic argument if no canditate is found

### LINKED ISSUE #81576: Elide generic arguments in "no method found" errors if they're irrelevant
Inspired by this question on discord:
> no method named extend found for struct Map<std::iter::Chain<Map<Windows<'_, Point<f64>>, [closure@src\graphics\slider.rs:39:22: 47:18]>, std::iter::Once<Point<f64>>>, [closure@src\graphics\slider.rs:49:22: 49:60]> in the current scope
>
> how does map not have .extend

Repro: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e270ca9a0ae009a8f34af6bc31c0ce90
```rust
fn main() {
    let v = vec![1_i32, 2, 3];
    v.iter().map(|x| x * x).extend(std::iter::once(100));
}
```
Error:
```
error[E0599]: no method named `extend` found for struct `Map<std::slice::Iter<'_, i32>, [closure@src/main.rs:3:18: 3:27]>` in the current scope
 --> src/main.rs:3:29
  |
3 |     v.iter().map(|x| x * x).extend(std::iter::once(100));
  |                             ^^^^^^ method not found in `Map<std::slice::Iter<'_, i32>, [closure@src/main.rs:3:18: 3:27]>`
```

It would be nice if rustc could notice that `Map<T>` *never* has `extend` for any `T`, and use that information to simplify the error message to just 
```
error[E0599]: no method named `extend` found for struct `Map<_>` in the current scope
```
in order to focus the user better on the relevant part.

Can the name resolution engine do that?  (It can for a generic parameter, of course, but then it's only looking at the known trait bounds, which is a little different.)

### PR DESCRIPTION
**Pull request by ABouttefeux**
fixes #81576
changes: In error E0599 (method not found) generic argument are eluded if the method was not found anywhere. If the method was found in another inherent implementation suggest that it was found elsewhere.

Example
```rust


struct Wrapper<T>(T);

struct Wrapper2<T> {
    x: T,
}

impl Wrapper2<i8> {
    fn method(&self) {}
}

fn main() {
    let wrapper = Wrapper(i32);
    wrapper.method();
    let wrapper2 = Wrapper2{x: i32};
    wrapper2.method();
}
```

```
Error[E0599]: no method named `method` found for struct `Wrapper<_>` in the current scope
....
error[E0599]: no method named `method` found for struct `Wrapper2<i32>` in the current scope
...
   = note: The method was found for Wrapper2<i8>.

```
I am not very happy with the ```no method named `test` found for struct `Vec<_, _>` in the current scope```. I think it might be better to show only one generic argument `Vec<_>` if there is a default one. But I haven't yet found a way to do that,

### CODE REVIEW

**Comment by ABouttefeux** [comment]
I change it to show ``` no method named `test` found for struct `Vec` in the current scope ``` instead of `Vec<_, _>`

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                        false
+                                    }
+                                })
+                                .collect::<Vec<_>>();
+                            if inherent_impls_candidate.len() > 0 {
+                                inherent_impls_candidate.sort();
+                                inherent_impls_candidate.dedup();
+                                // number of type to shows at most.
+                                const LIMIT: usize = 3;
+                                let mut note = format!("The {item_kind} was found for");
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:524]:
```suggestion
                                let mut note = format!("the {item_kind} was found for");
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 2]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                if inherent_impls_candidate.len() > 1 {
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:525]: I think it might be better to make a list of items instead of enumerating them in text, because that is easier to scan when reading the error.

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 3]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                    .type_of(*inherent_impls_candidate.last().unwrap());
+                                note = format!("{} {}", note, impl_ty);
+                                if inherent_impls_candidate.len() > LIMIT {
+                                    note = format!(
+                                        "{} and {} more",
+                                        note,
+                                        inherent_impls_candidate.len() - LIMIT
+                                    );
+                                }
+                                err.note(&format!("{}.", note));
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:553]: We don't capitalize or have a final period on sentences. We only break that convention if we have long text with multiple sentences, but it is heavily frown upon.

File: src/test/ui/methods/method-not-found-generic-arg-elision.stderr [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+error[E0599]: no method named `method` found for struct `Wrapper2<'_, bool, 3_usize>` in the current scope
+  --> $DIR/method-not-found-generic-arg-elision.rs:83:13
+   |
+LL | struct Wrapper2<'a, T, const C: usize> {
+   | -------------------------------------- method `method` not found for this
+...
+LL |     wrapper.method();
+   |             ^^^^^^ method not found in `Wrapper2<'_, bool, 3_usize>`
+   |
+   = note: The method was found for Wrapper2<'a, i8, C>, Wrapper2<'a, i32, C> and Wrapper2<'a, i32, C>.
```
Comment (estebank) [inline src/test/ui/methods/method-not-found-generic-arg-elision.stderr:56]: Looking at this I am concerned about some trait bounds I've seen that generate huge types, but I don't know how we'd present these in a better way 🤷‍♂️

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 5]
```diff
@@ -383,6 +383,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         return None;
                     } else {
                         span = item_name.span;
+
+                        // issue #81576, elision of generic argument when no methode can be found in any implementation
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:387]:
```suggestion
                        // Don't show generic arguments when the method can't be found in any implementation (#81576).
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 6]
```diff
@@ -383,6 +383,39 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                                .count()
+                                        } else {
+                                            0
+                                        }
+                                    })
+                                    .sum();
+                                if candidate_numbers == 0 && unsatisfied_predicates.is_empty() {
+                                    if let Some((path_string, _)) = ty_str.split_once('<') {
+                                        ty_str_reported = path_string.to_string();
+                                    }
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:414]: Ideally we'd just take the name ident of the type and use that. I think `item_name.to_string()` would  work here.

String operations are brittle and can break as things change in the codebase.

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 7]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                .tcx
+                                .inherent_impls(adt.did)
+                                .iter()
+                                .copied()
+                                .filter(|def_id| {
+                                    if let Some(assoc) =
+                                        self.associated_item(*def_id, item_name, Namespace::ValueNS)
+                                    {
+                                        // Check for both mode is the same so we avoid suggesting
+                                        // incorect associated item.
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:496]:
```suggestion
                                        // incorrect associated item.
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 8]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                                    self.tcx.at(span).type_of(*def_id) != actual
+                                                        && self.tcx.at(span).type_of(*def_id)
+                                                            != rcvr_ty
+                                                } else {
+                                                    false
+                                                }
+                                            }
+                                            (Mode::Path, false) => true,
+                                            _ => false,
+                                        }
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:513]:
```suggestion
                                        match (mode, assoc.fn_has_self_parameter, source) {
                                            (Mode::MethodCall, true, SelfSource::MethodCall(_)) => {
                                                // We check that the suggest type is actually
                                                // different from the received one
                                                // So we avoid suggestion method with Box<Self>
                                                // for instance
                                                self.tcx.at(span).type_of(*def_id) != actual
                                                    && self.tcx.at(span).type_of(*def_id)
                                                        != rcvr_ty
                                            }
                                            (Mode::Path, false, _) => true,
                                            _ => false,
                                        }
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 9]
```diff
@@ -449,6 +482,77 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                    } else {
+                                        false
+                                    }
+                                })
+                                .collect::<Vec<_>>();
+                            if inherent_impls_candidate.len() > 0 {
+                                inherent_impls_candidate.sort();
+                                inherent_impls_candidate.dedup();
+                                // number of type to shows at most.
+                                const LIMIT: usize = 3;
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:523]: We usually show 4 elements when it is a list, I think 3 when they are part of a sentence, like here.

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/method/suggest.rs:525]: This might work better as well in the case of really long type names with lots of type parameters (that we see in the wild).

File: src/test/ui/methods/method-not-found-generic-arg-elision.stderr (hunk 4 above)
Comment (ABouttefeux) [reply src/test/ui/methods/method-not-found-generic-arg-elision.stderr:56]: The case where trait bounds are not met are manage by another part of the code, therefore we should not see long trait bounds. I have added a test for this case.

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 6 above)
Comment (ABouttefeux) [reply compiler/rustc_typeck/src/check/method/suggest.rs:414]: `item_name` is the method we are looking to call. I did not find a way to print the type without the generic parameter otherwise. Do you know a way to do it ?

File: src/test/ui/methods/method-not-found-generic-arg-elision.stderr [hunk 10]
```diff
@@ -0,0 +1,93 @@
+error[E0599]: no method named `distance` found for struct `Point<i32>` in the current scope
+  --> $DIR/method-not-found-generic-arg-elision.rs:82:23
+   |
+LL | struct Point<T> {
+   | --------------- method `distance` not found for this
```
Comment (estebank) [inline src/test/ui/methods/method-not-found-generic-arg-elision.stderr:5]: Looking at this with fresh eyes in context, it might make sense to expand this label to be `method distance not found for Point when T is i32, but it is found when T is f64`, but maybe that's too verbose.

File: src/test/ui/methods/method-not-found-generic-arg-elision.stderr [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+LL | struct Wrapper<T>(T);
+   | --------------------- method `method` not found for this
+...
+LL |     wrapper.method();
+   |             ^^^^^^ method not found in `Wrapper<bool>`
+   |
+   = note: the method was found for Wrapper<i8>
+   = note: the method was found for Wrapper<i16>
+   = note: the method was found for Wrapper<i32>
+   = note: the method was found for 3 more types
```
Comment (estebank) [inline src/test/ui/methods/method-not-found-generic-arg-elision.stderr:39]: Ideally this would be a single note:

```
   = note: the method `method` was found for
           - `Wrapper<i8>`
           - `Wrapper<i16>`
           - `Wrapper<i32>`
           - `Wrapper<u8>`
           and 2 more types

File: src/test/ui/issues/issue-30123.stderr [hunk 12]
```diff
@@ -3,6 +3,8 @@ error[E0599]: no function or associated item named `new_undirected` found for st
    |
 LL |     let ug = Graph::<i32, i32>::new_undirected();
    |                                 ^^^^^^^^^^^^^^ function or associated item not found in `issue_30123_aux::Graph<i32, i32>`
+   |
+   = note: the function or associated item was found for issue_30123_aux::Graph<N, E, Undirected>
```
Comment (estebank) [inline src/test/ui/issues/issue-30123.stderr:7]: This would ideally talk about `Graph<i32, i32, Undirected>`, potentially mentioning the `Ty` default of `Directed`. No need to tackle this now.

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 13]
```diff
@@ -449,6 +485,55 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                .collect::<Vec<_>>();
+                            if inherent_impls_candidate.len() > 0 {
+                                inherent_impls_candidate.sort();
+                                inherent_impls_candidate.dedup();
+                                let type_candidates = inherent_impls_candidate
+                                    .iter()
+                                    .map(|impl_item| self.tcx.at(span).type_of(*impl_item))
+                                    .collect::<Vec<_>>();
+                                // number of type to shows at most.
+                                let limit = if type_candidates.len() == 4 { 4 } else { 3 };
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:525]:
```suggestion
                                let limit = if type_candidates.len() == 5 { 5 } else { 4 };
```

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 14]
```diff
@@ -449,6 +485,55 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                for ty in type_candidates.iter().take(limit) {
+                                    err.note(&format!("the {item_kind} was found for {}", ty));
+                                }
+                                if type_candidates.len() > limit {
+                                    err.note(&format!(
+                                        "the {item_kind} was found for {} more types",
+                                        type_candidates.len() - limit
+                                    ));
+                                }
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/suggest.rs:534]: Instead of emitting a note on each iteration, construct a single string to be emitted.

**Review by estebank — APPROVED** [review]
Left some nitpicks, but this is close to being merged. 😄

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 6 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/method/suggest.rs:417]: What is the type of `item_name` from which you get `span` from?

https://github.com/rust-lang/rust/pull/84221/files/6efa14b3add08188c5322db8694a8cbbea7851e5#diff-e8458f9222609acec4270bb72dcf235e7aa575268adff217d113052c3751c53cL385

I think that might have a string representation, and if not a field that is only the name with type `Ident`, which has a string representation of _only_ the identifier.

Comment (ABouttefeux) [reply compiler/rustc_typeck/src/check/method/suggest.rs:417]: Yes it is an Ident, but this does not represent the type. This is the indent of the method

For instance it is used here: 
https://github.com/ABouttefeux/rust/blob/120691c590c4309fda31994931b9a561b4249c33/compiler/rustc_typeck/src/check/method/suggest.rs#L422-L431
