### PR TITLE
Suggest `extern crate alloc` when using undeclared module `alloc`

### LINKED ISSUE #90136: Suggest `extern crate alloc;` when using undeclared module `alloc`
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ae9e67981e817e2a887ea8a532b2868a)

```rust
use alloc::rc::Rc;
```

The current output is:

```
error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
 --> src/lib.rs:2:5
  |
2 | use alloc::rc::Rc;
  |     ^^^^^ use of undeclared crate or module `alloc`

```

Ideally the output should look like:

```
error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
 --> src/lib.rs:2:5
  |
2 | use alloc::rc::Rc;
  |     ^^^^^ use of undeclared crate or module `alloc`
help: add `extern crate alloc` to use the buildin `alloc` module
```

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #90136

### CODE REVIEW

File: compiler/rustc_resolve/src/lib.rs [hunk 1]
```diff
@@ -2523,19 +2523,29 @@ impl<'a> Resolver<'a> {
...
-                                )
-                                .map(|sugg| {
-                                    (
-                                        vec![(ident.span, sugg.to_string())],
+                                if ident.name == sym::alloc {
+                                    Some((
+                                        vec![],
                                         String::from(
-                                            "there is a crate or module with a similar name",
+                                            "add `extern crate alloc` to use the builtin `alloc` module",
```
Comment (PatchMixolydic) [inline compiler/rustc_resolve/src/lib.rs:2530]:
```suggestion
                                            "add `extern crate alloc` to use the `alloc` crate",
```
I'm not sure if "builtin" is accurate since `alloc` is separate from the compiler (as far as I'm aware, at least). Alternative phrasings (aside from the one suggested here) might include "the standard `alloc` crate" or "the `alloc` crate in the sysroot".

Comment (TaKO8Ki) [reply compiler/rustc_resolve/src/lib.rs]: Thank you. I applied your suggestion.

**Comment by joshtriplett** [comment]
This seems reasonable and helpful, as an improvement to the error message. :+1: for making this change.

But also, I wonder if we could arrange to always make `alloc` available, the way that `std` and `core` are always available, so that this error doesn't arise in the first place?

**Comment by jackh726** [comment]
@bors r+ rollup

I think making alloc available like std or core would be nice, but should be a followup.

**Comment by TaKO8Ki** [comment]
@jackh726 
Is there any particular reason why alloc is not available like std or core?

If not, should you add a new issue about making core available?

**Comment by jackh726** [comment]
@TaKO8Ki I'm not sure :)

**Comment by PatchMixolydic** [comment]
Pulling in `alloc` in a `no_std` binary seems like it requires a global memory allocator to be present ([example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=513df6270e3ed3465498e57836c4ac1f)), which might be impossible in memory-constrained environments.

**Comment by jackh726** [comment]
In no_std, yes. But when std is available, alloc should be, probably.
