### PR TITLE
Tighten span when suggesting lifetime on path

### LINKED ISSUE #92324: Broken help message for missing lifetime when using <_ as Trait> syntax in type alias
I tried this code:

```rust
use std::marker::PhantomData;
use std::rc::Rc;

trait Machine<'a> {
    type Datum;
}

#[derive(Default)]
struct LuaMachine<'a> {
    _phantom: PhantomData<fn(&'a ()) -> &'a ()>,
}

struct LuaDatum<'a> {
    _machine: Rc<LuaMachine<'a>>,
}

impl<'a> Machine<'a> for LuaMachine<'a> {
    type Datum = LuaDatum<'a>;
}

type M<'a> = LuaMachine<'a>;
type D<'a> = <M<'a> as Machine>::Datum;

fn main() {}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a0a2e0bf578cc6667805e2c13c6cfa64))

I expected to see this happen (which works correctly with rustc 1.57.0 stable):

```text
help: consider using the `'a` lifetime
   |
22 | type D<'a> = <M<'a> as Machine<'a>>::Datum;
   |                        ~~~~~~~~~~~
```

But with `rustc 1.59.0-nightly (f8abed9ed 2021-12-26)`, I get:

```text
help: consider using the `'a` lifetime
   |
22 | type D<'a> = <M<'a> as Machine>::Datum<'a>;
   |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (f8abed9ed 2021-12-26)
binary: rustc
commit-hash: f8abed9ed48bace6be0087bcd44ed534e239b8d8
commit-date: 2021-12-26
host: x86_64-unknown-freebsd
release: 1.59.0-nightly
LLVM version: 13.0.0
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
This is kind of a hack. 

Really the issue here is that we want to suggest the segment's span if the path resolves to something defined outside of the macro, and the macro's span if it resolves to something defined within.. I'll look into seeing if we can do something like that. 

Fixes #92324

r? @cjgillot

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/path.rs [hunk 1]
```diff
@@ -277,7 +277,9 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
             // See rustc_resolve::late::lifetimes::LifetimeContext::add_missing_lifetime_specifiers_label
             let elided_lifetime_span = if generic_args.span.is_empty() {
                 // If there are no brackets, use the identifier span.
-                path_span
+                // HACK: we use find_ancestor_inside to associate to properly suggest elided spans
+                //  in paths originating from macros.
```
Comment (BGR360) [inline compiler/rustc_ast_lowering/src/path.rs:281]: nit: grammar

also, what do macros have to do with this?

Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/path.rs:281]: so macros have nothing to #92324. But [`src/test/ui/in-band-lifetimes/elided-lifetimes.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/in-band-lifetimes/elided-lifetimes.rs#L63) regresses if we don't return a subspan of the `path_span`.

Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/path.rs:281]: That's presumably why `segment.ident.span` was changed to `path_span` in #90446, but we still need a span that points to _just_ the segment, not the whole path. 

So this finds the segment's span inside of any macro if `path_span` inside of one.

**Comment by cjgillot** [comment]
Thanks @compiler-errors!
@bors r+ rollup
