### PR TITLE
Detect calls to .clone() on T: !Clone types on borrowck errors

### LINKED ISSUE #48677: Unintentionally cloning references can lead to confusing borrow checker errors
(Note from pnkfelix: I have updated the example to continue illustrating the issue even in the presence of NLL.)

This issue is a result of all references implementing Clone. The following code will not compile:

```rust
fn foo<T: Default>(list: &mut Vec<T>) {
    let mut cloned_items = Vec::new();
    for v in list.iter() {
        cloned_items.push(v.clone())
    }
    list.push(T::default());
    drop(cloned_items);
}
```
producing the misleading error message:
```rust
error[E0502]: cannot borrow `*list` as mutable because it is also borrowed as immutable
 --> src/main.rs:6:5
  |
3 |     for v in list.iter() {
  |              ---- immutable borrow occurs here
...
6 |     list.push(T::default());
  |     ^^^^ mutable borrow occurs here
7 |     drop(cloned_items);
  |          ------------ immutable borrow later used here
  | - immutable borrow ends here
```

Because Clone is not a trait bound on T, where you'd expect `v.clone()` to return a cloned T it's actually returning a cloned &T. The type of `cloned_items` is inferred to be `Vec<&T>`, and the lifetime of the `list` immutable borrow is extended to the lifetime of `cloned_items`. This is hard to figure out from the error message. The solution is to add Clone as a trait bound to T. The following code builds:
```rust
fn foo<T: Default + Clone>(list: &mut Vec<T>) {
    let mut cloned_items = Vec::new();
    for v in list.iter() {
        cloned_items.push(v.clone())
    }
    list.push(T::default());
}
```

If you give cloned_items an explicit type
```rust
let mut cloned_items: Vec<T> = Vec::new();
```
it gives an error that more clearly explains what you're doing wrong:
```rust
error[E0308]: mismatched types
 --> src/main.rs:4:27
  |
4 |         cloned_items.push(v.clone())
  |                           ^^^^^^^^^ expected type parameter, found &T
  |
  = note: expected type `T`
             found type `&T`
```

I'm not sure what my proposed fix would be. I don't know if there are any use cases for explicitly cloning a reference. Ideally you'd get a warning on cloning a reference to a type that doesn't implement Clone.

### PR DESCRIPTION
**Pull request by estebank**
When encountering a lifetime error on a type that *holds* a type that doesn't implement `Clone`, explore the item's body for potential calls to `.clone()` that are only cloning the reference `&T` instead of `T` because `T: !Clone`. If we find this, suggest `T: Clone`.

```
error[E0502]: cannot borrow `*list` as mutable because it is also borrowed as immutable
  --> $DIR/clone-on-ref.rs:7:5
   |
LL |     for v in list.iter() {
   |              ---- immutable borrow occurs here
LL |         cloned_items.push(v.clone())
   |                             ------- this call doesn't do anything, the result is still `&T` because `T` doesn't implement `Clone`
LL |     }
LL |     list.push(T::default());
   |     ^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
LL |
LL |     drop(cloned_items);
   |          ------------ immutable borrow later used here
   |
help: consider further restricting this bound
   |
LL | fn foo<T: Default + Clone>(list: &mut Vec<T>) {
   |                   +++++++
```
```
error[E0505]: cannot move out of `x` because it is borrowed
  --> $DIR/clone-on-ref.rs:23:10
   |
LL | fn qux(x: A) {
   |        - binding `x` declared here
LL |     let a = &x;
   |             -- borrow of `x` occurs here
LL |     let b = a.clone();
   |               ------- this call doesn't do anything, the result is still `&A` because `A` doesn't implement `Clone`
LL |     drop(x);
   |          ^ move out of `x` occurs here
LL |
LL |     println!("{b:?}");
   |               ----- borrow later used here
   |
help: consider annotating `A` with `#[derive(Clone)]`
   |
LL + #[derive(Clone)]
LL | struct A;
   |
```

Fix #48677.

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -1215,10 +1220,107 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
         self.suggest_using_local_if_applicable(&mut err, location, issued_borrow, explanation);
+        self.suggest_copy_for_type_in_cloned_ref(&mut err, place);
 
         err
     }
 
+    fn suggest_copy_for_type_in_cloned_ref(&self, err: &mut Diag<'tcx>, place: Place<'tcx>) {
+        let tcx = self.infcx.tcx;
+        let hir = tcx.hir();
+        if let Some(body_id) = tcx.hir_node(self.mir_hir_id()).body_id() {
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:1231]:
```suggestion
        let Some(body_id) = tcx.hir_node(self.mir_hir_id()).body_id() else { return };
```

just for making the function easier to read top to bottom (so I don't have to remember we're in a scope)

**Review by oli-obk — APPROVED** [review]

**Comment by estebank** [comment]
@oli-obk I'll take your ✅ as r+

@bors r=oli-obk
