### PR TITLE
Get all (but one) of debuginfo tests to pass with MIR codegen.

### LINKED ISSUE #31005: [MIR] Implement debug info
Currently we do not emit any debuginfo from the MIR translator.

It doesn’t seem like there should be many issues implementing support, other than `DebugLoc` wanting a `ast::NodeId`, which eventually gets passed down to `trans::debuginfo::metadata::scope_metadata`.

Precondition to this work is to either decouple `trans::debuginfo` and its DIScope-building-related functionality from the `NodeId` or create a independent code for MIR’s use.

### LINKED ISSUE #32790: MIR match bindings have the scope of the match instead of the arm.
Reduced from a debuginfo test failing with an implementation of #31005:
```rust
fn main() {
    match Ok::<(), ()>(()) {
        Ok(a) => zzz(),
        Err(a) => zzz()
    }
}

fn zzz() {}
```
```rust
fn main() -> () {
    let var0: (); // a in Scope(3) at test2.rs:3:12: 3:13
    let var1: (); // a in Scope(3) at test2.rs:4:13: 4:14
    let mut tmp0: std::result::Result<(), ()>;
    let mut tmp1: ();

    bb0: {
        tmp1 = (); // Scope(5) at test2.rs:2:24: 2:26
        tmp0 = std::prelude::v1::Ok<(), ()>(tmp1,); // Scope(4) at test2.rs:2:11: 2:27
        switch(tmp0) -> [Ok: bb4, Err: bb5]; // Scope(3) at test2.rs:3:9: 3:14
    }

    bb1: {
        return; // Scope(0) at test2.rs:1:1: 6:2
    }

    bb2: {
        return = zzz() -> bb1; // Scope(7) at test2.rs:3:18: 3:23
    }

    bb3: {
        return = zzz() -> bb1; // Scope(10) at test2.rs:4:19: 4:24
    }

    bb4: {
        var0 = ((tmp0 as Ok).0: ()); // Scope(3) at test2.rs:3:12: 3:13
        goto -> bb2; // Scope(3) at test2.rs:3:9: 3:14
    }

    bb5: {
        var1 = ((tmp0 as Err).0: ()); // Scope(3) at test2.rs:4:13: 4:14
        goto -> bb3; // Scope(3) at test2.rs:4:9: 4:15
    }
    Scope(0) {
        Scope(1) {
            Parent: Scope(0)
            Scope(2) {
                Parent: Scope(1)
                Scope(3) {
                    Parent: Scope(2)
                    Scope(4) {
                        Parent: Scope(3)
                        Scope(5) {
                            Parent: Scope(4)
                    Scope(6) {
                        Parent: Scope(3)
                        Scope(7) {
                            Parent: Scope(6)
                            Scope(8) {
                                Parent: Scope(7)
                    Scope(9) {
                        Parent: Scope(3)
                        Scope(10) {
                            Parent: Scope(9)
                            Scope(11) {
                                Parent: Scope(10)
}
```

You can see that both `a` bindings and their assignments share the scope of the match, `Scope(3)`.

This appears to be intentional in the implementation of pattern-matching:
```rust
        // Before we do anything, create uninitialized variables with
        // suitable extent for all of the bindings in this match. It's
        // easiest to do this up front because some of these arms may
        // be unreachable or reachable multiple times.
        let var_scope_id = self.innermost_scope_id();
        for arm in &arms {
            self.declare_bindings(var_scope_id, &arm.patterns[0]);
        }
```

However, this breaks debugging (as both variables appear declared at the same time) and potentially MIR-based region/borrow checking, in the future.

### PR DESCRIPTION
**Pull request by eddyb**
I didn't get much feedback in #31005 so I went ahead and implemented something simple.
Closes #31005, as MIR debuginfo should work now for most usecases.
#32949 tracks remaining shadowing problems that break `function-prologue-stepping-no-stack-check`.

The `no-debug-attribute` test no longer assumes variables are in scope of `return`.
We might also want to revisit that in #32949, but the test is more reliable now either way.

In order to get one last function in the `associated-type` test pass, this PR also fixes #32790.

### CODE REVIEW

**Comment by eddyb** [comment]
I expect the lldb part in `debuginfo/function-prologue-stepping-no-stack-check` to work, but I couldn't get the automated testing to work locally.
cc @michaelwoerister

**Comment by alexcrichton** [comment]
*swoon*

File: src/test/debuginfo/function-prologue-stepping-no-stack-check.rs [hunk 1]
```diff
@@ -37,100 +37,79 @@
 // gdb-command:run
 
 // IMMEDIATE ARGS
-// gdb-command:print a
-// gdb-check:$1 = 1
-// gdb-command:print b
-// gdb-check:$2 = true
-// gdb-command:print c
-// gdb-check:$3 = 2.5
+// gdb-command:info args
```
Comment (michaelwoerister) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: I'm a bit hesitant about using `info args` for debuginfo tests. A `gdb-check` instruction just verifies that the argument can be found *somewhere* in the output, so without the numbering it's possible to overlook errors. For example, given the following program...
```rust
let x = 1;
breakpoint();
{
    let x = 2;
    breakpoint();
}
breakpoint();
```
... we get a correct result with `print`:
```
gdb-command:print x
gdb-command:continue
gdb-command:print x
gdb-command:continue
gdb-command:print x
gdb-check:$1 = 1
gdb-check:$2 = 2
gdb-check:$3 = 2

produces:
$1 = 1
$2 = 2
$3 = 2 // let's say there's a bug in scoping and x still refers to wrong address
```
The error will be detected because there is not `$3 = 1` in the output. But with `info`, the overlapping names might hide the error:
```
gdb-command:info locals
gdb-command:continue
gdb-command:info locals
gdb-command:continue
gdb-command:info locals
gdb-check:x = 1
gdb-check:x = 2
gdb-check:x = 1 // <-- this is actually redundant

produces:
x = 1
x = 2
x = 2 // the test would still pass, because `x = 1` can be found in the output.
```

File: src/librustc_trans/mir/mod.rs [hunk 2]
```diff
@@ -327,10 +327,78 @@ fn arg_value_refs<'bcx, 'tcx>(bcx: &BlockAndBuilder<'bcx, 'tcx>,
...
+                     llvm::LLVMDIBuilderCreateOpPlus(),
+                     byte_offset_of_var_in_env as i64,
+                     llvm::LLVMDIBuilderCreateOpDeref()]
+                };
+
+                // The environment and the capture can each be indirect.
+
+                // FIXME(eddyb) see above why we have to keep
+                // a pointer in an alloca for debuginfo atm.
+                let mut ops = if env_ref || true { &ops[..] } else { &ops[1..] };
```
Comment (michaelwoerister) [inline src/librustc_trans/mir/mod.rs]: `|| true` ?

Comment (eddyb) [inline src/librustc_trans/mir/mod.rs]: See the `FIXME` there and above.

File: src/librustc/mir/visit.rs [hunk 3]
```diff
@@ -248,6 +248,7 @@ macro_rules! make_mir_visitor {
                     ref $($mutability)* var_decls,
                     ref $($mutability)* arg_decls,
                     ref $($mutability)* temp_decls,
+                    upvar_decls: _,
```
Comment (michaelwoerister) [inline src/librustc/mir/visit.rs]: It would be nice to provide a `visit_upvar_decl` method, just for completeness.

File: src/test/debuginfo/function-prologue-stepping-no-stack-check.rs (hunk 1 above)
Comment (eddyb) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: That's certainly a problem. I don't think I can get this test to work without either this workaround or a generalized solution for #32949.
I'm not entirely sure the test makes any sense anymore, btw, a the whole `morestack` stuff is gone.

I'd rather have a test that only makes sure the backtrace contains the argument names and their values, and it wouldn't need the myriad of cases found here.

File: src/librustc_trans/mir/mod.rs (hunk 2 above)
Comment (michaelwoerister) [inline src/librustc_trans/mir/mod.rs]: Ah ok, now I see.

File: src/librustc/mir/visit.rs (hunk 3 above)
Comment (eddyb) [inline src/librustc/mir/visit.rs]: I didn't want it to be part of MIR itself, really - initially I had `upvar_names: Vec<Name>` but realized that I also needed to know if they're by-ref, that's the only reason it's a `struct`.

File: src/test/debuginfo/function-prologue-stepping-no-stack-check.rs (hunk 1 above)
Comment (michaelwoerister) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: If the `morestack` stuff is gone for good, then this test should deleted, but `function-prologue-stepping-regular.rs` should then also handle GDB. I'm surprised that `info args` and `print` give different results here...

**Comment by michaelwoerister** [comment]
r? @michaelwoerister
I'll review this if nobody minds.

File: src/test/debuginfo/function-prologue-stepping-no-stack-check.rs (hunk 1 above)
Comment (eddyb) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: Because of #32949, there isn't actually a point for the debugger to break on where the variables for arguments are not in scope, and the first point where it would stop is *before* those variables are actually initialized, so you get garbage locals shadowing the perfectly good args.

Comment (michaelwoerister) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: Shouldn't there just be the arguments? I.e. do we have separate DWARF entries for the arguments and some later incarnation of the arguments in stack frame?

Comment (eddyb) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: Yes, because they are distinct lvalues in MIR. Even if we might skip building allocas for arguments (which would require us using `llvm.dbg.value` instead) and/or elide their moves to variables, we'd still need a notion of "call arguments" (e.g. what shows up in the backtrace) different from pattern bindings.

Comment (michaelwoerister) [inline src/test/debuginfo/function-prologue-stepping-no-stack-check.rs]: OK, makes sense. However, this is exactly what these test cases are for: That `print arg` will print the correct value when setting a function breakpoint. So using `info args` is a bit like cheating `:P`

**Comment by arielb1** [comment]
Why is there a `spread` flag that inverts the point of the `rust-call` ABI?

**Comment by eddyb** [comment]
@arielb1 It's pretty much how it works in old trans as well.
The flag is there so the MIR can be manipulated independently from the ABI, e.g. if the type is a known tuple, we can spread it into its components (which would not have the `spread` flag on, *unless* we get VG and it's some `(A, B, Tail...)` type).
We also would need a similar mechanism on tuple ADT rvalues and calls, but this is getting offtopic.

**Comment by michaelwoerister** [comment]
Excellent work, @eddyb!
I would suggest that you ignore the `function-prologue-stepping-no-stack-check.rs` with a FIXME for now and we'll take care of it when we have a good solution for #32949.

**Comment by eddyb** [comment]
@michaelwoerister Rebased and updated title & description.

**Comment by michaelwoerister** [comment]
Thanks, @eddyb!
