### PR TITLE
Merge crossbeam-channel into `std::sync::mpsc`

### LINKED ISSUE #39364: Panic in Receiver::recv()
I'm having a problem using a channel to send notifications to a background thread... As I understand it, this shouldn't be possible? Receiver::recv() is not supposed to panic, is it? I'm not doing anything unsafe...

Mentioned this on [reddit](https://www.reddit.com/r/rust/comments/5qnxmz/panic_in_mpscchannel_receiverrecv/) and [burntsushi](https://www.reddit.com/user/burntsushi) has confirmed that this looks like a bug. I will try and produce some simpler code to reproduce this but don't have time at the moment. (edit - please nag me if i don't produce an example, I have a vague idea what will do it)

I've tried this with stable (1.14) and nightly and get the same result.

A copy of the code which generates the error is available here:

https://github.com/jamespharaoh/rust-output/tree/channel_recv_panic

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', ../src/libstd/sync/mpsc/mod.rs:879
stack backtrace:
   1:     0x55ab04830c1a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55ab0483672f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x55ab04834666 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x55ab04834d17 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55ab045b4d73 - std::panicking::begin_panic::h634e2b37a96f78d4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x55ab045b9ce0 - <std::sync::mpsc::Receiver<T>>::recv::h59b94a6df5881f84
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/macros.rs:44
   7:     0x55ab045e5ff3 - output::output_state::OutputState::background_thread::h8aaba65c8ed499f1
                        at /home/james/projects/storage/rust-output/src/output_state.rs:261
   8:     0x55ab045ea743 - output::output_state::OutputState::new::{{closure}}::hf69a0505c40cdaf3
                        at /home/james/projects/storage/rust-output/src/output_state.rs:79
   9:     0x55ab045dfeda - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hb24d824e514ccbad
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:295
  10:     0x55ab045b53d7 - std::panicking::try::do_call::h3a6460a838b6cf70
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  11:     0x55ab0483e20a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  12:     0x55ab045b4eb6 - std::panicking::try::h3133aaaba181f2ff
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  13:     0x55ab045b389e - std::panic::catch_unwind::h0d4cf58b5fb1c352
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
  14:     0x55ab045ea000 - std::thread::Builder::spawn::{{closure}}::h4fae90249c97a5c1
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:287
  15:     0x55ab045ce9fe - <F as alloc::boxed::FnBox<A>>::call_box::hef839d7658cc4ef9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
  16:     0x55ab04833d64 - std::sys::imp::thread::Thread::new::thread_start::ha102a6120fc52763
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  17:     0x7fc0c43506b9 - start_thread
  18:     0x7fc0c3e7082c - clone
  19:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by ibraheemdev**
This PR copies the [`crossbeam-channel`](https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel#crossbeam-channel) crate into the standard library as a private module, `sync::mpmc`. `sync::mpsc` is now implemented as a thin wrapper around `sync::mpmc`. The primary purpose of this PR is to resolve https://github.com/rust-lang/rust/issues/39364, so there are no public API changes.

The reason https://github.com/rust-lang/rust/issues/39364 has not been fixed in over 5 years is that the current channel is *incredibly* complex. It was written many years ago and has sat mostly untouched since. `crossbeam-channel` has become the most popular alternative on crates.io, amassing over 30 million downloads. While crossbeam's channel is also complex, like all fast concurrent data structures, it avoids some of the major issues with the current implementation around dynamic flavor upgrades. The new implementation decides on the datastructure to be used when the channel is created, and the channel retains that structure until it is dropped.

Replacing `sync::mpsc` with a simpler, less performant implementation has been discussed as an alternative. However, Rust touts itself as enabling fearless concurrency, and having the standard library feature a subpar implementation of a core concurrency primitive doesn't feel right. The argument is that slower is better than broken, but this PR shows that we can do better.

As mentioned before, the primary purpose of this PR is to fix https://github.com/rust-lang/rust/issues/39364, and so the public API intentionally remains the same. *After* that problem is fixed, the fact that `sync::mpmc` now exists makes it easier to fix a limitation of `mpsc`, the fact that it only supports a single consumer. spmc and mpmc are two other common concurrency patterns, and this change enables a path to deprecating `mpsc` and exposing a general `sync::channel` module that supports multiple consumers. It also implements other useful methods such as `send_timeout`. That said, exposing MPMC and other new functionality is mostly out of scope for this PR and it would be helpful if discussion stays on topic :)

For what it's worth, the new implementation has also been shown to be more performant in [some basic benchmarks](https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel/benchmarks#results). 

cc @taiki-e

r? rust-lang/libs

### CODE REVIEW

**Comment by joshtriplett** [comment]
Thanks for working on this!

I'd like to avoid adding any new public API (like mpmc) in the course of fixing mpsc, even if it's unstable. Let's focus on making mpsc less broken.

Also, the phrasing of the PR seems unfortunate; crossbeam channel has lots of users, but that doesn't make it "the defacto replacement".

**Comment by ibraheemdev** [comment]
> I'd like to avoid adding any new public API (like mpmc) in the course of fixing mpsc, even if it's unstable. Let's focus on making mpsc less broken.

`sync::mpmc` is private. Avoiding any public API changes is an explicit goal of this PR.

> Also, the phrasing of the PR seems unfortunate; crossbeam channel has lots of users, but that doesn't make it "the defacto replacement".

True, I just meant to say it is the *most popular* replacement. I'll update the description.

**Comment by jyn514** [comment]
> This PR imports the crossbeam-channel crate into the standard library as a private module, sync::mpmc. 

Rather than copying the whole crate, you can add it as an internal dependency and re-export it; that will make it easier to update in the future. See `hashbrown` in `library/std/src/collections/hash/map.rs` for an example.

**Comment by ibraheemdev** [comment]
@jyn514 The problem with that is `crossbeam-channel` depends on `crossbeam-utils`, which depends on `lazy_static` and includes many utilities that we doesn't need. `sync::mpmc` doesn't contain the entire crate, only the parts necessary to bounded, unbounded, and rendezvous channels. This could work if a `crossbeam-channel-core` crate is created that we depend on, but we discussed this before and would like to see if the libs team is generally in support of this change before worrying about integration details.

**Comment by bjorn3** [comment]
Crossbeam-channel also directly depends on libstd for getting the current thread id: https://github.com/crossbeam-rs/crossbeam/blob/85d0bdc95cdac6450ac1ba4ed587f362a5235e60/crossbeam-channel/src/waker.rs#L274 It probably also depends on other parts of libstd to wake up the right thread.

**Comment by the8472** [comment]
There is a UI test (src/test/ui/threads-sendsync/mpsc_stress.rs) that is partially disabled. This PR should enable it. And make sure that it still detects the bug (red-green).

**Comment by SimonSapin** [comment]
`sync::mpmc` contains a couple thousands lines of code and is effectively of fork of (part of) crossbeam-channel. What is the plan for both of their maintenance? Should bug fixes in one be manually ported to the other? Or is the intent that some plan will be made at a later date to go back to a single "source of truth" in terms of source code repositories?

If the latter, would it make sense for `rust-lang/rust` would be the source of truth for some pieces of code that are both *used* in the standard library (but not exposed, so no API stability requirement) and separately published to crates.io (where semver-breaking version numbers can be used as needed) ?

This could be a way to resolve the conflict between: the `std` crate wants to use something from crates.io, but that crate needs API (like thread IDs) that’s only exposed publicly by `std`.

File: library/std/src/sync/mpmc/utils.rs [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+    fn deref_mut(&mut self) -> &mut T {
+        &mut self.value
+    }
+}
+
+const SPIN_LIMIT: u32 = 6;
+const YIELD_LIMIT: u32 = 10;
+
+/// Performs exponential backoff in spin loops.
+pub struct Backoff {
```
Comment (thomcc) [inline library/std/src/sync/mpmc/utils.rs:98]: If we keep this code in the tree, please indicate that this shouldn't be used or emulated elsewhere in libstd?

File: library/std/src/sync/mpmc/list.rs [hunk 2]
```diff
@@ -0,0 +1,648 @@
...
+
+    /// The state of the slot.
+    state: AtomicUsize,
+}
+
+impl<T> Slot<T> {
+    /// Waits until a message is written into the slot.
+    fn wait_write(&self) {
+        let backoff = Backoff::new();
+        while self.state.load(Ordering::Acquire) & WRITE == 0 {
```
Comment (thomcc) [inline library/std/src/sync/mpmc/list.rs:48]: This was deeeply concerning at first, but in practice *I think* you'd expect this to never need to go into the loop given where it's called? Still...

File: library/std/src/sync/mpmc/list.rs [hunk 3]
```diff
@@ -0,0 +1,648 @@
...
+                    }
+
+                    token.list.block = block as *const u8;
+                    token.list.offset = offset;
+                    return true;
+                },
+                Err(h) => {
+                    head = h;
+                    block = self.head.block.load(Ordering::Acquire);
+                    backoff.spin();
```
Comment (thomcc) [inline library/std/src/sync/mpmc/list.rs:356]: Same thing i said about spinning in compare_exchange_weak applies here.

File: library/std/src/sync/mpmc/utils.rs [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+
+    /// Returns `true` if exponential backoff has completed and blocking the thread is advised.
+    #[inline]
+    pub fn is_completed(&self) -> bool {
+        self.step.get() > YIELD_LIMIT
+    }
+}
+
+/// A simple spinlock.
+pub(crate) struct Spinlock<T> {
```
Comment (thomcc) [inline library/std/src/sync/mpmc/utils.rs:147]: This should be a real mutex 🙀!

**Review by thomcc — COMMENTED** [review]
I'm surprised this code does as much dubious spinning as it does. In practice most of it you'd expect not to hurt that badly (which matches my experience with crossbeam), but on some arches a few of the placements of `backoff.spin()` could have bad behavior.

The spinlock was a surprise though. I had no idea crossbeam had one.

**Comment by thomcc** [comment]
All that said, this code is vastly easier for me to follow than `std::sync::mpsc` — most of my complaints are relatively minor or easily fixed problems.

File: library/std/src/sync/mpmc/array.rs [hunk 5]
```diff
@@ -0,0 +1,523 @@
...
+                ) {
+                    Ok(_) => {
+                        // Prepare the token for the follow-up call to `read`.
+                        token.array.slot = slot as *const Slot<T> as *const u8;
+                        token.array.stamp = head.wrapping_add(self.one_lap);
+                        return true;
+                    }
+                    Err(h) => {
+                        head = h;
+                        backoff.spin();
```
[the remark this answers is not in the document]
Comment (jonhoo) [reply library/std/src/sync/mpmc/array.rs:255]: As an aside, this is _great_ advice and something I haven't seen very well documented anywhere. Any chance you'd consider writing this up as a blog post, or better yet, find a way to add it to the `std` docs?

**Comment by m-ou-se** [comment]
This PR was briefly discussed in the library API meeting last week. We didn't reach any conclusion about future *API* changes like deprecation or adding an mpmc channel. That can be discussed separately if someone wants to put in the time and energy. We see this PR itself basically as a bugfix, requiring no FCP. A crater run might be useful though, and it's probably good if there's more than one reviewer. (Thanks @thomcc for helping out with reviewing!)

**Comment by saethlin** [comment]
@ibraheemdev You're asking people for review on the community Discord; I'm not really qualified to review this but I can offer some feedback.

In internal codebases, we make extensive use of crossbeam channels to communicate between well-named threads. This has the nice benefit that you can run `top -H -p PID` to get a very quick and very dirty visualization of what's taking up time in a running system. The downside is that crossbeam spins _a lot_, so certain components spend most of their time on CPU according to `top` spinning for messages. And therefore, the codebases are littered with this pattern:

```rust
loop {
    match rx.try_recv() {
        Ok(msg) => process(msg),
        Err(TryRecvError::Empty) => sleep(std::time::Duration::from_millis(1)),
        Err(TryRecvError::Disconnected) => break,        
    }
}
```
I've seen this pattern drop the `top`-reported CPU usage of a thread from 20% to 5%. But it is not at all clear whether this is beneficial for the behavior of the application. I can certainly imagine how this would result in throughput bubbles as objects accumulate in the channel over the course of the sleep.

I'm concerned that putting a spinny channel implementation that does awesome on bechmarks into `std` where it will hopefully be used by a lot of beginners will cause said beginners to mis-assess the resource utilization/requirements of their code. "I upgraded to Rust 1.61 and my CPU usage doubled" is not a Reddit post I want to see. Perhaps even worse would be comments suggesting this sleep-on-empty pattern.

**Comment by saethlin** [comment]
I was asked for a reproducer of the above. I thought this would be hard but... it's not? Here's a ~25x reduction in CPU usage from the sleepy pattern over crossbeam defaults:
```rust
fn main() {
    let (tx, rx) = crossbeam_channel::unbounded();
    for _ in 0..100 {
        std::thread::Builder::new()
            .name("worker".to_string())
            .spawn({
                let tx = tx.clone();
                move || {
                    for i in 0..usize::MAX {
                        tx.send(i).unwrap();
                        std::thread::sleep(std::time::Duration::from_millis(1));
                    }
                }
            })
            .unwrap();
    }

    let mut sum = 0usize;

    // This impl uses ~26% of a core in top
    for v in rx.iter() {
        sum = sum.wrapping_add(v);
    }

    // This impl uses ~0.9% of a core in top
    /*
    loop {
        match rx.try_recv() {
            Ok(v) => {
                sum = sum.wrapping_add(v);
            }
            Err(crossbeam_channel::TryRecvError::Empty) => {
                std::thread::sleep(std::time::Duration::from_millis(1));
            }
            Err(crossbeam_channel::TryRecvError::Disconnected) => {
                break;
            }
        }
    }
    */

    println!("{}", sum);
}
```

**Comment by kpreid** [comment]
> I'm concerned that putting a spinny channel implementation that does awesome on bechmarks into `std` where it will hopefully be used by a lot of beginners and may cause said beginners to mis-assess the resource utilization/requirements of their code. "I upgraded to Rust 1.61 and my CPU usage doubled" is not a Reddit post I want to see. Perhaps even worse would be comments suggesting this sleep-on-empty pattern.

Any applications which are more concerned with energy usage than throughput (which could include something as non-specialized as Rust in WASM in a web page that happens to be opened on a smartphone, as well as embedded applications) would _correctly_ prefer to sleep rather than spin. This seems like an area where `std` should not be choosing the other option — users looking for high throughput can easily benchmark wall-time and choose to use a different implementation, but energy usage is harder to measure, and more often overlooked.

(Disclaimer: I'm not an expert in optimizing for _either_ of the above; I've just heard a few things, and am trying to make sure this consideration isn't entirely overlooked.)

**Comment by ibraheemdev** [comment]
Making crossbeam less spinny is just a matter of tweaking `Backoff::spin/snooze`. All the spin loops fall back to a blocking path eventually. As @kpreid mentioned, there is a tradeoff regarding how soon to fallback to that path, but I just wanted to note that tweaking that would be straightforward.

**Comment by m-ou-se** [comment]
Assigning @Amanieu and myself to review this, since we're both used to working with concurrency/atomics.

File: library/std/src/sync/mpmc/array.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (Amanieu) [reply library/std/src/sync/mpmc/array.rs:255]: There is actually a good reason for spinning on CAS failure: if a thread encounters a lot of CAS failures then it means that the atomic it is trying to access is heavily contended. In such a situation where multiple threads are trying to access the same cacheline, you can significantly improve throughput by backing off and letting a single thread access the atomic at a time.

Essentially the access patterns go from:
```
Thread A
Thread B
Thread A
Thread B
Thread A
Thread B
Thread A
Thread B
```
to:
```
Thread A
Thread A
Thread A
Thread A
Thread B
Thread B
Thread B
Thread B
```

This improves throughput since the cacheline stays on the same CPU across multiple accesses.

This optimization looks good in benchmarks (I do something similar in parking_lot) but it is unclear how much impact it has on real world programs. I don't even know where to begin measuring this.

**Comment by Dylan-DPC** [comment]
@ibraheemdev if you can resolve the conflicts we can push this further

**Comment by alygin** [comment]
What do you think about [such data races](https://github.com/crossbeam-rs/crossbeam/issues/838) that present in both crossbeam-channel and `sync::mpsc` at the moment? Shouldn't channels provide a better synchronization in such cases? It may be [fixed rather simply](https://github.com/crossbeam-rs/crossbeam/pull/839/files#diff-b21bf9cfd25f5671c4003684497224ee113851cf7d2448ba4e57839a6421281a) in this PR.

**Comment by ibraheemdev** [comment]
@alygin see @kprotty's comment on the issue, that is a false positive from thread sanitizer, not a data race.

**Comment by alygin** [comment]
@kprotty, @ibraheemdev, ok, thanks for the explanation.

**Comment by JohnCSimon** [comment]
ping from triage:
@ibraheemdev 
Returning to you to address merge conflicts.


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot author

File: library/std/src/sync/mpmc/utils.rs (hunk 4 above)
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/utils.rs]: Removed in 4ab5ecf2379f01865e3cf982a1885a9b63c68752.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@ibraheemdev what is the status of this PR?

**Comment by ibraheemdev** [comment]
@JohnCSimon There are a couple of concerns about spinning behavior that I can address, but still waiting for a full review.

**Comment by JohnCSimon** [comment]
@ibraheemdev if it's ready for review use 

As a reminder: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

File: library/std/src/sync/mpmc/array.rs [hunk 6]
```diff
@@ -0,0 +1,523 @@
...
+        } else {
+            Err(TryRecvError::Empty)
+        }
+    }
+
+    /// Receives a message from the channel.
+    pub(crate) fn recv(&self, deadline: Option<Instant>) -> Result<T, RecvTimeoutError> {
+        let token = &mut Token::default();
+        loop {
+            // Try receiving a message several times.
```
[the remark this answers is not in the document]
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/array.rs]: Removed in https://github.com/rust-lang/rust/pull/93563/commits/0ebf752a8398df2a7a1be85d62d309a691e3ea56.

File: library/std/src/sync/mpmc/array.rs [hunk 7]
```diff
@@ -0,0 +1,523 @@
...
+
+    /// Sends a message into the channel.
+    pub(crate) fn send(
+        &self,
+        msg: T,
+        deadline: Option<Instant>,
+    ) -> Result<(), SendTimeoutError<T>> {
+        let token = &mut Token::default();
+        loop {
+            // Try sending a message several times.
```
[the remark this answers is not in the document]
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/array.rs:322]: @thomcc agreed that a small amount of spinning seems reasonable, I removed the thread::yield's in this loop in https://github.com/rust-lang/rust/pull/93563/commits/e4e98e2451efaca0881204e78cf15ca1570d490b.

File: library/std/src/sync/mpmc/array.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/array.rs:254]: Updated the code to reload the head after spinning to reduce the likelihood of it being stale (https://github.com/rust-lang/rust/pull/93563/commits/0ae5d535fd1c19f20e650f4ef859046c5211bd0f).

File: library/std/src/sync/mpmc/list.rs (hunk 3 above)
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/list.rs:354]: Same fix as above.

File: library/std/src/sync/mpmc/utils.rs [hunk 8]
```diff
@@ -0,0 +1,191 @@
...
+    }
+}
+
+impl<T> DerefMut for CachePadded<T> {
+    fn deref_mut(&mut self) -> &mut T {
+        &mut self.value
+    }
+}
+
+const SPIN_LIMIT: u32 = 6;
```
[the remark this answers is not in the document]
Comment (ibraheemdev) [reply library/std/src/sync/mpmc/utils.rs:93]: Changed the code to use quadratic instead of exponential backoff (https://github.com/rust-lang/rust/pull/93563/commits/437ea347be00b51dd8e4506aec54421319bb6e82). The fallback to thread::yield is only in blocking loops, where there isn't really any other option..

**Comment by Amanieu** [comment]
You need to delete `LICENSES/BSD-2-Clause.txt`.

**Comment by Amanieu** [comment]
We discussed this in the libs meeting today, and we're happy to merge this as it is. Could you please rebase one more time to address the merge conflicts.

Thank you very much @ibraheemdev for your effort and patience in getting this through!

**Comment by Manishearth** [comment]
@bors r-

unclear why bors still thinks this is in queue

**Comment by thomcc** [comment]
Changes look fine.

@bors r=Amanieu

**Comment by nnethercote** [comment]
There is a smattering of regressions and improvements, nothing really notable or concerning.

@rustbot label: +perf-regression-triaged

**Comment by RalfJung** [comment]
As part of [this diff](https://github.com/rust-lang/rust/compare/6284998a2...e631891f7), a memory leak was introduced, at least according to Miri when running the std tests filtered for `time:: sync:: thread:: env::`. The most likely candidate is this PR.

Is this expected (some kind of management memory that is deliberately not being deallocated) or something to look into? See [here](https://github.com/rust-lang/miri-test-libstd/actions/runs/3458094781/jobs/5772169505#step:5:295) for the contents of the leaked memory.

**Comment by joboet** [comment]
> As part of [this diff](https://github.com/rust-lang/rust/compare/6284998a2...e631891f7), a memory leak was introduced, at least according to Miri when running the std tests filtered for `time:: sync:: thread:: env::`. The most likely candidate is this PR.
> 
> Is this expected (some kind of management memory that is deliberately not being deallocated, or a test that deliberately leaks) or something to look into? See [here](https://github.com/rust-lang/miri-test-libstd/actions/runs/3458094781/jobs/5772169505#step:5:295) for the contents of the leaked memory.

I think this is expected, [the test](https://github.com/rust-lang/rust/blob/f90a4ff26c9743abf612f015c4398d7158b646b6/library/std/src/sync/mpsc/tests.rs#L710-L722) for #39364 leaks a `Sender`.

**Comment by RalfJung** [comment]
Is there a way to write that test to clean up afterwards?

We could disable the leak checker in Miri, but then we'd miss accidental leaks in other tests.

**Comment by joboet** [comment]
> Is there a way to write that test to clean up afterwards?
> 
> We could disable the leak checker in Miri, but then we'd miss accidental leaks in other tests. I'm thinking of [something like this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b24d288905bb368714000e983f4aba4b) but I am not sure if that test still tests what it is supposed to test. It panics on stable though so I guess it does?

If I understand the issue correctly, that test would still catch it.

**Comment by jonhoo** [comment]
This feels like it'd be worth a `relnotes` tag?

File: library/std/src/sync/mpsc/mod.rs [hunk 9]
```diff
@@ -1016,15 +745,14 @@ impl<T> SyncSender<T> {
...
-        SyncSender::new(self.inner.clone())
+        SyncSender { inner: self.inner.clone() }
     }
 }
 
 #[stable(feature = "rust1", since = "1.0.0")]
 impl<T> Drop for SyncSender<T> {
     fn drop(&mut self) {
-        self.inner.drop_chan();
+        let _ = self.inner;
```
Comment (superobertking) [inline library/std/src/sync/mpsc/mod.rs:755]: Just curious, does this line do anything? In my understanding, we cannot move out of mutable reference, but Rust compiler will treat this line as no-op since it sees `let _`. The actual drop for inner is inserted by compiler somewhere else. This won't affect the code generation, but just a little confusing to me.

Comment (riking) [reply library/std/src/sync/mpsc/mod.rs:755]: `self.inner` becomes a statement temporary, and the drop glue is inserted at the end of the statement instead of the end of the function.

Comment (ibraheemdev) [reply library/std/src/sync/mpsc/mod.rs:755]: You're right that impl doesn't actually do anything, but removing it would break `T: Drop` bounds, which I think would be a breaking change?

Comment (RalfJung) [reply library/std/src/sync/mpsc/mod.rs:755]: `let _ = self.inner;` is basically obfuscated code for `drop(self.inner);` Wouldn't that be a more readable line of code to use here?

Comment (RalfJung) [reply library/std/src/sync/mpsc/mod.rs:755]: However actually I think @riking you are wrong. `let _ = *ptr;` is a NOP. `let _ = expr;` is only equivalent to `drop(expr)` when `expr` is not a pure place expression.

If you want a destructor to be executed, just call `drop`.

Comment (superobertking) [reply library/std/src/sync/mpsc/mod.rs:755]: > So `let _ = self.inner;` is basically obfuscated code for `drop(self.inner);`? Wouldn't that be a more readable line of code to use here?

@RalfJung I think the problem is `drop(self.inner)` won't compile because `self.inner` cannot be moved out of a reference. The following code won't compile.

```rust
struct A { inner: String }
impl Drop for A {
    fn drop(&mut self) {
        drop(self.inner);
    }
}
fn main() {
    let _x = A { inner: "".to_string() };
}
```

In practice, `drop` for inner don't need to be explicitly called, and the compiler will insert it automatically. `let _ = self.inner;` can just be omitted, and leave the drop function an empty body.

Comment (RalfJung) [reply library/std/src/sync/mpsc/mod.rs:755]: >  I think the problem is drop(self.inner) won't compile because self.inner cannot be moved out of a reference. The following code won't compile.


This demonstrates that `let _ = self.inner;` is indeed a NOP, and should be removed IMO.

Comment (superobertking) [reply library/std/src/sync/mpsc/mod.rs:755]: > This demonstrates that `let _ = self.inner;` is indeed a NOP, and should be removed IMO.

Agree

Comment (RalfJung) [reply library/std/src/sync/mpsc/mod.rs:755]: Opened https://github.com/rust-lang/rust/pull/105243

**Comment by HaiyangXu** [comment]
do we include this in the rust edition 2021 ?

**Comment by slanterns** [comment]
It has nothing to do with edition. Just use rustx >= 1.67 and you'll get it.
