### PR TITLE
Fix the unsoundness in the `early_otherwise_branch` mir opt pass

### LINKED ISSUE #78496: EarlyOtherwiseBranch transformation is incorrect
For details see https://github.com/rust-lang/rust/pull/77163#issuecomment-703251270, opening an issue since PR was closed:

```rust
pub enum E<'a> {
    Empty,
    Some(&'a E<'a>),
}

fn f(e: &E) -> u32 {
   if let E::Some(E::Some(_)) = e { 1 } else { 2 }
}

fn main() {
   println!("{:?}", f(&E::Empty));
}
```

```
rustc b.rs -Zmir-opt-level=2 && ./b
"./b" terminated by signal SIGSEGV (Address boundary error)
```

### PR DESCRIPTION
**Pull request by JakobDegen**
Closes #78496 .

This change is a significant rewrite of much of the pass. Exactly what it does is documented in the source file (with ascii art!), and all the changes that are made to the MIR that are not trivially sound are carefully documented. That being said, this is my first time touching MIR, so there are probably some invariants I did not know about that I broke.

This version of the optimization is also somewhat more flexible than the original; for example, we do not care how or where the value on which the parent is switching is computed. There is no requirement that any types be the same. This could be made even more flexible in the future by allowing a wider range of statements in the bodies of `BBC, BBD` (as long as they are all the same of course). This should be a good first step though.

Probably needs a perf run.

r? @oli-obk who reviewed things the last time this was touched

### CODE REVIEW

File: compiler/rustc_mir_transform/src/early_otherwise_branch.rs [hunk 1]
```diff
@@ -167,201 +224,170 @@ impl<'tcx> MirPass<'tcx> for EarlyOtherwiseBranch {
...
+            // where such an invalidated reference may appear:
+            //  - In `Q`: Not possible since `Q` is used as the operand of a `SwitchInt` and so
+            //    cannot contain referenced data.
+            //  - In `BBU`: Not possible since that block contains only the `unreachable` terminator
+            //  - In `BBC.2, BBD.2`: Not possible, since `discriminant(P)` was computed prior to
+            //    reaching that block in the input to our transformation, and so any data
+            //    invalidated by that computation could not have been used there.
+            //  - In `BB9`: Not possible since control flow might have reached `BB9` via the
+            //    `otherwise` branch in `BBC, BBD` in the input to our transformation, which would
+            //    have invalidated the data when computing `discriminant(P)`
```
Comment (JakobDegen) [inline compiler/rustc_mir_transform/src/early_otherwise_branch.rs:244]: I realize now that depending on the MIR semantics, this may be incorrect. In particular, we can imagine BB9 doing something like this:
```
if Q == otherwise {
    use reference invalidated by P
}
```
This would have been correct before this pass, since `P` is only computed if `Q` does not take the `otherwise` branch; it's obviously no longer correct after the pass. That being said, this kind of a pattern can't ever pass borrowck (since borrowck will not consider that the conditions in the branch in BB1 and BB9 are the same). Is this a legal transformation for other optimizations to make? Or must the validity of all references (whenever they're used) in the MIR always follow only from the control flow? (hopefully I explained myself accurately there)

**Comment by oli-obk** [comment]
Will review some time this week

@bors try @rust-timer queue

File: compiler/rustc_mir_transform/src/early_otherwise_branch.rs [hunk 2]
```diff
@@ -15,144 +15,201 @@ use super::simplify::simplify_cfg;
...
+/// This is only correct for some `P`, since `P` is now computed outside the original `switchInt`.
+/// The filter on which `P` are allowed (together with discussion of its correctness) is found in
+/// `may_hoist`.
 pub struct EarlyOtherwiseBranch;
 
 impl<'tcx> MirPass<'tcx> for EarlyOtherwiseBranch {
     fn is_enabled(&self, sess: &rustc_session::Session) -> bool {
-        //  FIXME(#78496)
-        sess.opts.debugging_opts.unsound_mir_opts && sess.mir_opt_level() >= 3
+        sess.mir_opt_level() >= 3
```
Comment (simonvandel) [inline compiler/rustc_mir_transform/src/early_otherwise_branch.rs:98]: I'm pretty sure the opt level gate needs to be lowered to see useful perf results. Reducing it to 1 should do the trick.

**Comment by JakobDegen** [comment]
This is causing issues with incremental and there are other things I want to look at too before this gets merged. I can close and re-open instead if that's preferable

**Comment by JakobDegen** [comment]
I've dropped the MIR-opt-level requirement to 2 so that this actually runs. Also fixed an ICE and made a couple of other adjustments. This is still a draft because it's [causing issues with incremental](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/MIR.20opt.20setting.20off.20inconsistent.20fingerprint.20check.20failures/near/264841102), but besides that I think it should be ready for review.

**Comment by JakobDegen** [comment]
Realize I forgot to comment on this: There had been a suggestion on the original version of this pass to do a `BitAnd`, thereby avoiding the extra branch and bb, but that's unfortunately not correct if `0` is one of the values that gets switched on. I could special case in a check for that, but I'm not sure the complexity is warranted.

**Comment by oli-obk** [comment]
> I also did local perf runs of this and it was a flat zero across the board, so I'm not expecting this to bring many benefits. Having the opt be sound should be a good step forward regardless though.

Indeed, I just wanted to make sure we don't regress anything. I also agree with the "spurious noise" assessment on the one regression

**Comment by JakobDegen** [comment]
@oli-obk will you get a chance to review this, or is there someone else I should ask? If there's no review capacity right now, I can close this until there is if that's preferable

**Comment by oli-obk** [comment]
Sorry, didn't get to this properly before Christmas. I'll get back to reviewing complex things like this mid January

**Comment by camelid** [comment]
triage: friendly ping @oli-obk :)

File: compiler/rustc_mir_transform/src/early_otherwise_branch.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_mir_transform/src/early_otherwise_branch.rs:244]: Great explanation, thanks. Unfortunately I don't have a good answer. MIR semantics are very underdocumented. As far as I know there is no opt that could cause such a pattern right now, but I'm wondering if we could write it with raw pointers and intrinsics

**Comment by oli-obk** [comment]
Hmm I reviewed this before but obviously never wrote any conclusions. Well, third time's the charm. The opt is really well documented and structured and I feel confident it actually catches all the cases where it shouldn't run.

@bors r+ rollup=never
