### PR TITLE
Fix scoping for let chains in match guards

### LINKED ISSUE #118593: `if_let_guard` + `let_chains`: used binding is possibly-uninitialized
I tried this code:

```rust
#![feature(if_let_guard, let_chains)]

fn main() {
    let opt = Some(1);
    match 1 {
        1 | 2
            if let Some(x) = opt
                && true =>
        {
            x;
        }
        _ => {}
    }
}
```

I expected to see this happen: the code compiles. 

Instead, this happened: it doesn't compile.
```
error[E0381]: used binding `x` is possibly-uninitialized
  --> y.rs:10:13
   |
7  |             if let Some(x) = opt
   |                         -
   |                         |
   |                         binding initialized here in some conditions
   |                         binding declared here but left uninitialized
...
10 |             x;
   |             ^ `x` used here but it is possibly-uninitialized
```
If I remove the `&& true`, it does compile.

### Meta
`rustc --version --verbose`:
```
rustc 1.76.0-nightly (87e1447aa 2023-11-30)
binary: rustc
commit-hash: 87e1447aadaa2899ff6ccabe1fa669eb50fb60a1
commit-date: 2023-11-30
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### PR DESCRIPTION
**Pull request by matthewjasper**
If let guards were previously represented as a different type of guard in HIR and THIR. This meant that let chains in match guards were not handled correctly because they were treated exactly like normal guards.

- Remove `hir::Guard` and `thir::Guard`.
- Make the scoping different between normal guards and if let guards also check for let chains.

closes #118593

### CODE REVIEW

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -1258,7 +1258,7 @@ pub struct Arm<'hir> {
     /// If this pattern and the optional guard matches, then `body` is evaluated.
     pub pat: &'hir Pat<'hir>,
     /// Optional guard clause.
-    pub guard: Option<Guard<'hir>>,
```
Comment (compiler-errors) [inline compiler/rustc_hir/src/hir.rs:1261]: Ah, I've always been so confused why this was represented differently in HIR. This was also what caused the bug fixed by #119402, for example.

Comment (matthewjasper) [reply compiler/rustc_hir/src/hir.rs:1261]: I think if_let_guards was implemented before let chains were ready. But it's definitely outstayed its usefulness.

File: compiler/rustc_mir_build/src/build/matches/mod.rs [hunk 2]
```diff
@@ -2034,21 +2069,16 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
-                    }
+                self.in_if_then_scope(match_scope, guard_span, |this| {
+                    guard_span = this.thir[guard].span;
+                    this.then_else_break(
+                        block,
+                        guard,
+                        None,
+                        match_scope,
+                        this.source_info(arm.span),
+                        false,
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/build/matches/mod.rs:2080]: Can you explain a bit about this `declare_bindings: bool` arg here? I feel like it's kind of subtle, and I can't see any explanation about when it's supposed to be true or false.

**Review by compiler-errors — COMMENTED** [review]
One question below.

**Review by compiler-errors — APPROVED** [review]
