### PR TITLE
fix ICE in `const_c_variadic` when passing ZSTs

### LINKED ISSUE #153351: [ICE]: `callee_abis.next().is_none()`
auto-reduced (treereduce-rust):
````rust
#![feature(const_c_variadic)]
#![feature(const_destruct)]

const unsafe extern "C" fn read_n<const N: usize>(_: ...) {}

unsafe fn read_too_many() {
    const { read_n::<0>(read_as::<u32>) }
}

fn read_as<T>() -> () {}

````

original:
````rust
#![feature(const_c_variadic)]
#![feature(const_destruct)]
#![feature(c_variadic)]

const unsafe extern "C" fn read_n<const N: usize>(_: ...) {}

unsafe fn read_too_many() {
    const { read_n::<0>(read_as::<u32>) }
}

const unsafe extern "C" fn read_as<T>() -> () {}

fn main() {}

````

Version information
````
rustc 1.96.0-nightly (1b7d722f4 2026-03-03)
binary: rustc
commit-hash: 1b7d722f429f09c87b08b757d89c689c6cf7f6e7
commit-date: 2026-03-03
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/1b7d722f429f09c87b08b757d89c689c6cf7f6e7/compiler/rustc_const_eval/src/interpret/stack.rs#L649-L661

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: C-variadic functions are unstable
 --> /tmp/icemaker_global_tempdir.6DbyeX1z5eEj/rustc_testrunner_tmpdir_reporting.Whwgd9ZBnBHB/mvce.rs:4:1
  |
4 | const unsafe extern "C" fn read_n<const N: usize>(_: ...) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #44930 <https://github.com/rust-lang/rust/issues/44930> for more information
  = help: add `#![feature(c_variadic)]` to the crate attributes to enable
  = note: this compiler was built on 2026-03-03; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.6DbyeX1z5eEj/rustc_testrunner_tmpdir_reporting.Whwgd9ZBnBHB/mvce.rs:10:25
   |
10 | fn read_as<T>() -> () {}
   |                         ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.6DbyeX1z5eEj/rustc_testrunner_tmpdir_reporting.Whwgd9ZBnBHB/mvce.rs`

error[E0617]: can't pass a function item to a variadic function
 --> /tmp/icemaker_global_tempdir.6DbyeX1z5eEj/rustc_testrunner_tmpdir_reporting.Whwgd9ZBnBHB/mvce.rs:7:25
  |
7 |     const { read_n::<0>(read_as::<u32>) }
  |                         ^^^^^^^^^^^^^^
  |
  = help: a function item is zero-sized and needs to be cast into a function pointer to be used in FFI
  = note: for more information on function items, visit https://doc.rust-lang.org/reference/types/function-item.html
help: use a function pointer instead
  |
7 |     const { read_n::<0>(read_as::<u32> as fn()) }
  |                                        +++++++


thread 'rustc' (256474) panicked at /rustc-dev/1b7d722f429f09c87b08b757d89c689c6cf7f6e7/compiler/rustc_const_eval/src/interpret/stack.rs:655:9:
assertion failed: callee_abis.next().is_none()
stack backtrace:
   0:     0x7f2156d5860b - <<std[284bc44e398d798e]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[c88c01294d6d5abc]::fmt::Display>::fmt
   1:     0x7f2157422908 - core[c88c01294d6d5abc]::fmt::write
   2:     0x7f2156d6f616 - <std[284bc44e398d798e]::sys::stdio::unix::Stderr as std[284bc44e398d798e]::io::Write>::write_fmt
   3:     0x7f2156d2e6e8 - std[284bc44e398d798e]::panicking::default_hook::{closure#0}
   4:     0x7f2156d4ba73 - std[284bc44e398d798e]::panicking::default_hook
   5:     0x7f2155d3984c - std[284bc44e398d798e]::panicking::update_hook::<alloc[53dcbfea654489fb]::boxed::Box<rustc_driver_impl[b9925340d7eb0d08]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f2156d4bd52 - std[284bc44e398d798e]::panicking::panic_with_hook
   7:     0x7f2156d2e7da - std[284bc44e398d798e]::panicking::panic_handler::{closure#0}
   8:     0x7f2156d22cf9 - std[284bc44e398d798e]::sys::backtrace::__rust_end_short_backtrace::<std[284bc44e398d798e]::panicking::panic_handler::{closure#0}, !>
   9:     0x7f2156d3020d - __rustc[81a9f9e8ca82058f]::rust_begin_unwind
  10:     0x7f21538cafac - core[c88c01294d6d5abc]::panicking::panic_fmt
  11:     0x7f21533fe232 - core[c88c01294d6d5abc]::panicking::panic
  12:     0x7f21578d97d8 - <rustc_const_eval[f53a2e14d882bd28]::interpret::eval_context::InterpCx<rustc_const_eval[f53a2e14d882bd28]::const_eval::machine::CompileTimeMachine>>::init_stack_frame
  13:     0x7f21578cf3c7 - <rustc_const_eval[f53a2e14d882bd28]::interpret::eval_context::InterpCx<rustc_const_eval[f53a2e14d882bd28]::const_eval::machine::CompileTimeMachine>>::init_fn_call
  14:     0x7f21584e3984 - rustc_const_eval[f53a2e14d882bd28]::const_eval::eval_queries::eval_to_allocation_raw_provider
  15:     0x7f21584e2556 - rustc_query_impl[f8080f5464e40736]::query_impl::eval_to_allocation_raw::invoke_provider_fn::__rust_begin_short_backtrace
  16:     0x7f215811a9c3 - rustc_query_impl[f8080f5464e40736]::execution::try_execute_query::<rustc_middle[8b92c1aa48f9158]::query::caches::DefaultCache<rustc_middle[8b92c1aa48f9158]::ty::PseudoCanonicalInput<rustc_middle[8b92c1aa48f9158]::mir::interpret::GlobalId>, rustc_middle[8b92c1aa48f9158]::query::erase::ErasedData<[u8; 24usize]>>, false>
  17:     0x7f215811a37f - rustc_query_impl[f8080f5464e40736]::query_impl::eval_to_allocation_raw::execute_query_non_incr::__rust_end_short_backtrace
  18:     0x7f215811bf71 - rustc_const_eval[f53a2e14d882bd28]::const_eval::eval_queries::eval_to_const_value_raw_provider
  19:     0x7f215811bae8 - rustc_query_impl[f8080f5464e40736]::query_impl::eval_to_const_value_raw::invoke_provider_fn::__rust_begin_short_backtrace
  20:     0x7f215811a8c7 - rustc_query_impl[f8080f5464e40736]::execution::try_execute_query::<rustc_middle[8b92c1aa48f9158]::query::caches::DefaultCache<rustc_middle[8b92c1aa48f9158]::ty::PseudoCanonicalInput<rustc_middle[8b92c1aa48f9158]::mir::interpret::GlobalId>, rustc_middle[8b92c1aa48f9158]::query::erase::ErasedData<[u8; 24usize]>>, false>
  21:     0x7f215811a43f - rustc_query_impl[f8080f5464e40736]::query_impl::eval_to_const_value_raw::execute_query_non_incr::__rust_end_short_backtrace
  22:     0x7f2157dff3e9 - <rustc_middle[8b92c1aa48f9158]::ty::context::TyCtxt>::const_eval_resolve
  23:     0x7f2157d40a96 - <rustc_mir_transform[d63848adec2d2e5f]::known_panics_lint::ConstPropagator as rustc_middle[8b92c1aa48f9158]::mir::visit::Visitor>::visit_assign
  24:     0x7f2157d3c939 - <rustc_mir_transform[d63848adec2d2e5f]::known_panics_lint::ConstPropagator as rustc_middle[8b92c1aa48f9158]::mir::visit::Visitor>::visit_body
  25:     0x7f2157d39cdf - <rustc_mir_transform[d63848adec2d2e5f]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[d63848adec2d2e5f]::pass_manager::MirLint>::run_lint
  26:     0x7f215740ceea - rustc_mir_transform[d63848adec2d2e5f]::run_analysis_to_runtime_passes
  27:     0x7f2158210ec4 - rustc_mir_transform[d63848adec2d2e5f]::mir_drops_elaborated_and_const_checked
  28:     0x7f2158210921 - rustc_query_impl[f8080f5464e40736]::query_impl::mir_drops_elaborated_and_const_checked::invoke_provider_fn::__rust_begin_short_backtrace
  29:     0x7f21574689ca - rustc_query_impl[f8080f5464e40736]::execution::try_execute_query::<rustc_data_structures[bb16df1a7a653477]::vec_cache::VecCache<rustc_span[f1d8e5cad33ca5f]::def_id::LocalDefId, rustc_middle[8b92c1aa48f9158]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[8b92c1aa48f9158]::dep_graph::graph::DepNodeIndex>, false>
  30:     0x7f2157468103 - rustc_query_impl[f8080f5464e40736]::query_impl::mir_drops_elaborated_and_const_checked::execute_query_non_incr::__rust_end_short_backtrace
  31:     0x7f2157466488 - <rustc_middle[8b92c1aa48f9158]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface[8c1386fdb9c77e28]::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  32:     0x7f2157465875 - rustc_interface[8c1386fdb9c77e28]::passes::analysis
  33:     0x7f215862f59c - rustc_query_impl[f8080f5464e40736]::execution::try_execute_query::<rustc_middle[8b92c1aa48f9158]::query::caches::SingleCache<rustc_middle[8b92c1aa48f9158]::query::erase::ErasedData<[u8; 0usize]>>, false>
  34:     0x7f215862f2fb - rustc_query_impl[f8080f5464e40736]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
  35:     0x7f21585fd42d - rustc_interface[8c1386fdb9c77e28]::interface::run_compiler::<(), rustc_driver_impl[b9925340d7eb0d08]::run_compiler::{closure#0}>::{closure#1}
  36:     0x7f21585e1b3e - std[284bc44e398d798e]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8c1386fdb9c77e28]::util::run_in_thread_with_globals<rustc_interface[8c1386fdb9c77e28]::util::run_in_thread_pool_with_globals<rustc_interface[8c1386fdb9c77e28]::interface::run_compiler<(), rustc_driver_impl[b9925340d7eb0d08]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x7f21585e21a0 - <std[284bc44e398d798e]::thread::lifecycle::spawn_unchecked<rustc_interface[8c1386fdb9c77e28]::util::run_in_thread_with_globals<rustc_interface[8c1386fdb9c77e28]::util::run_in_thread_pool_with_globals<rustc_interface[8c1386fdb9c77e28]::interface::run_compiler<(), rustc_driver_impl[b9925340d7eb0d08]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[c88c01294d6d5abc]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f21585e302c - <std[284bc44e398d798e]::sys::thread::unix::Thread>::new::thread_start
  39:     0x7f215205e98b - <unknown>
  40:     0x7f21520e2a0c - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (1b7d722f4 2026-03-03) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `read_too_many::{constant#0}`
#1 [eval_to_const_value_raw] simplifying constant for the type system `read_too_many::{constant#0}`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `read_too_many`
#3 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0601, E0617, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-const_c_variadic +F-const_destruct +F-c_variadic

### PR DESCRIPTION
**Pull request by folkertdev**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/153398)*

fixes https://github.com/rust-lang/rust/issues/153351
r? RalfJung 

There was a mismatch between the caller and callee ABI where the caller does not pass ZST arguments, but the callee does expect them. Because ZSTs don't implement `VaArgSafe` the program must already be invalid if this comes up.

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/stack.rs [hunk 1]
```diff
@@ -638,6 +638,9 @@ impl<'a, 'tcx: 'a, M: Machine<'tcx>> InterpCx<'tcx, M> {
         I: Iterator<Item = (&'a FnArg<'tcx, M::Provenance>, &'a ArgAbi<'tcx, Ty<'tcx>>)>,
         J: Iterator<Item = (usize, &'a ArgAbi<'tcx, Ty<'tcx>>)>,
     {
+        // Arguments that are ignored (ZSTs) are not passed by the caller.
+        let mut callee_abis = callee_abis.filter(|(_, abi)| !abi.is_ignore());
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/stack.rs]: I think it'd be better to do this in `call.rs` where this function is called; that's closer to the other logic for skipping ignored arguments.

File: tests/ui/consts/const-eval/c-variadic-ignored-argument.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+// Regression test for when a c-variadic argument is `mode: Ignore`. The caller won't pass the
+// argument, but the callee ABI does have the argument. Ensure that const-eval is able to handle
+// this case, even though it only comes up in programs that would error anyway because ZSTs do not
+// implement VaArgSafe.
+
+const unsafe extern "C" fn read_n<const N: usize>(_: ...) {}
+
+unsafe fn read_too_many() {
+    const { read_n::<0>(read_as::<u32>, 1i32) }
+    //~^ ERROR can't pass a function item to a variadic function
```
Comment (RalfJung) [inline tests/ui/consts/const-eval/c-variadic-ignored-argument.rs]: Wait, we are executing this const even though it has a type error? That seems very wrong.

File: compiler/rustc_const_eval/src/interpret/stack.rs (hunk 1 above)
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/stack.rs]: Can you add a test in `src/tools/miri/tests/pass/c-variadic.rs` where the caller passes `i32, (), i32` and then I guess the callee only sees the two integers?  That does seem strange though, arguably the callee needs to fetch the `()` argument or else it's UB, no?

File: compiler/rustc_const_eval/src/interpret/stack.rs [hunk 3]
```diff
@@ -638,12 +638,29 @@ impl<'a, 'tcx: 'a, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
+                && callee_abi.is_ignore()
+            {
+                let mplace = self.allocate(callee_abi.layout, MemoryKind::Stack)?;
+                varargs.push(mplace);
+                let _ = callee_abis.next();
+            }
+
+            let Some((fn_arg, caller_abi)) = caller_args.next() else {
+                break;
+            };
```
Comment (folkertdev) [inline compiler/rustc_const_eval/src/interpret/stack.rs]: a bit weird, but this needs a do-while loop

**Comment by RalfJung** [comment]
If I remember correctly that ignored arguments are fully gone on the LLVM IR level, the patch IMO should be something like this
```diff
diff --git a/compiler/rustc_const_eval/src/interpret/call.rs b/compiler/rustc_const_eval/src/interpret/call.rs
index b8205bda685..26d42b8c60f 100644
--- a/compiler/rustc_const_eval/src/interpret/call.rs
+++ b/compiler/rustc_const_eval/src/interpret/call.rs
@@ -480,7 +480,13 @@ pub fn init_stack_frame(
 
                     // Consume the remaining arguments by putting them into the variable argument
                     // list.
-                    let varargs = self.allocate_varargs(&mut caller_args, &mut callee_args_abis)?;
+                    let varargs = self.allocate_varargs(
+                        &mut caller_args,
+                        // "Ignored" arguments aren't actually passed, so the callee should also
+                        // ignore them. (`pass_argument` does this for regular arguments.)
+                        (&mut callee_args_abis)
+                            .filter(|(_idx, abi)| !matches!(abi.mode, PassMode::Ignore)),
+                    )?;
                     // When the frame is dropped, these variable arguments are deallocated.
                     self.frame_mut().va_list = varargs.clone();
                     let key = self.va_list_ptr(varargs.into());
diff --git a/compiler/rustc_const_eval/src/interpret/stack.rs b/compiler/rustc_const_eval/src/interpret/stack.rs
index 6da6ed2ec75..b0f34264ad8 100644
--- a/compiler/rustc_const_eval/src/interpret/stack.rs
+++ b/compiler/rustc_const_eval/src/interpret/stack.rs
@@ -631,8 +631,8 @@ impl<'a, 'tcx: 'a, M: Machine<'tcx>> InterpCx<'tcx, M> {
     /// of variadic arguments. Return a list of the places that hold those arguments.
     pub(crate) fn allocate_varargs<I, J>(
         &mut self,
-        caller_args: &mut I,
-        callee_abis: &mut J,
+        caller_args: I,
+        mut callee_abis: J,
     ) -> InterpResult<'tcx, Vec<MPlaceTy<'tcx, M::Provenance>>>
     where
         I: Iterator<Item = (&'a FnArg<'tcx, M::Provenance>, &'a ArgAbi<'tcx, Ty<'tcx>>)>,
```

**Comment by folkertdev** [comment]
Ah, wait, I guess you meant to just sort of pass the arguments, but never read them. That should work regardless of the platform.

**Comment by RalfJung** [comment]
No you are right, the test has to be `ignore-msvc` (I think that's the only target where ZST arguments are not skipped).

File: compiler/rustc_const_eval/src/interpret/call.rs [hunk 4]
```diff
@@ -480,7 +480,10 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
 
                     // Consume the remaining arguments by putting them into the variable argument
                     // list.
-                    let varargs = self.allocate_varargs(&mut caller_args, &mut callee_args_abis)?;
+                    let varargs = self.allocate_varargs(
+                        &mut caller_args,
+                        &mut (&mut callee_args_abis).filter(|(_, abi)| !abi.is_ignore()),
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/call.rs]: You ignored half of the diff I posted:
- there's a redundant `&mut` here
- there should be a comment explaining why we do this

Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/call.rs]: If you are using `is_ignore` here, then please also use it elsewhere in this file where we check for `PassMode::Ignore`. Let's avoid being inconsistent about how we check this within a single file.

File: src/tools/miri/tests/pass/c-variadic.rs [hunk 5]
```diff
@@ -105,11 +105,20 @@ fn various_types() {
     }
 }
 
+fn pass_zst() {
+    unsafe extern "C" fn variadic(_: ...) {}
+
+    // Some platforms ignore ZSTs, meaning that the argument is not passed, even though it is part
+    // of the callee's ABI. Test that const eval handles this correctly.
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/c-variadic.rs]: This is a miri test, not a const eval test.

File: tests/ui/consts/const-eval/c-variadic-ignored-argument.rs (hunk 2 above)
Comment (RalfJung) [reply tests/ui/consts/const-eval/c-variadic-ignored-argument.rs]: Seems better to update this test to use `()` as the ZST rather than a fn item.

**Comment by RalfJung** [comment]
Ah... looks like powerpc, s390x, and sparc also don't ignore ZST. I had forgotten about that. (Given that C does not have ZST I have no idea what this is even about.)
