### PR TITLE
Don't prefix 0x for each segments in `dbg!(Ipv6)`

### LINKED ISSUE #81182: dbg! on Ipv6Addr should not show leading '0x'
[prior discussion](https://users.rust-lang.org/t/why-does-dbg-of-ipv6addr-show-leading-0x/54364)
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=385e6c132ab24c4e7086f9f52332badb)

---

I tried this code:

```rust
let ip = Ipv6Addr::new(123, 0, 3, 0, 0, 0, 36, 2);
dbg!(&ip);
```

I expected to see this happen: It prints `7b:0:3::24:2`

Instead, this happened: It prints `0x7b:0x0:0x3::0x24:0x2`

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by tesuji**
Fixes #81182

### CODE REVIEW

**Comment by lzutao** [comment]
Somehow all my PRs have been assigned to Jake recently.
r? @Amanieu

File: library/std/src/net/ip.rs [hunk 1]
```diff
@@ -1610,11 +1610,11 @@ impl fmt::Display for Ipv6Addr {
...
                 fn fmt_subslice(f: &mut fmt::Formatter<'_>, chunk: &[u16]) -> fmt::Result {
-                    if let Some(first) = chunk.first() {
-                        fmt::LowerHex::fmt(first, f)?;
-                        for segment in &chunk[1..] {
+                    if let Some((first, tail)) = chunk.split_first() {
+                        write!(f, "{:x}", first)?;
+                        for segment in tail {
                             f.write_char(':')?;
-                            fmt::LowerHex::fmt(segment, f)?;
+                            write!(f, "{:x}", segment)?;
```
Comment (pickfire) [inline library/std/src/net/ip.rs:1617]:
```rust
                             write!(f, ":{:x}", segment)?;
```
Should we perhaps do this instead?

Comment (Amanieu) [reply library/std/src/net/ip.rs:1617]: I don't think it makes much difference since the formatting code will call `write_str` on the `":"` separately anyways.

Comment (lzutao) [reply library/std/src/net/ip.rs:1617]: I am more concern about the style. However, I don't have a strong opinion on this.

Comment (pickfire) [reply library/std/src/net/ip.rs:1617]: I just wonder if there is a performance impact. Both works for me.
