### PR TITLE
Turn `#[global_allocator]` into a regular attribute macro

### LINKED ISSUE #44113: global_allocator can not not be defined inside module
When trying define a global allocator inside a module, you get a weird error message: `[E0432]: unresolved import super`. The global_allocator is expanded to code containing `use super::<varname>` but I don't know why rustc fails to resolve that in this case. Happens with both inline and file modules. 

Looks like the module that is created by expanding global_allocator thinks its parent is the root crate despite being in the `breaks` module.

Example:
```rust
#![feature(global_allocator, allocator_api)]                                                                                                                                                                       
                                                                                                                                                                                                                   
struct TAlloc;                                                                                                                                                                                                     
                                                                                                                                                                                                                   
unsafe impl<'a> std::heap::Alloc for &'a TAlloc{                                                                                                                                                                   
    unsafe fn alloc(&mut self, _layout: std::heap::Layout) -> std::result::Result<*mut u8, std::heap::AllocErr> {                                                                                                  
        return Err(std::heap::AllocErr::Unsupported{details: "Stub allocator"});                                                                                                                                   
    }                                                                                                                                                                                                              
    unsafe fn dealloc(&mut self, _ptr: *mut u8, _layout: std::heap::Layout) {                                                                                                                                      
    }                                                                                                                                                                                                              
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
mod breaks{                                                                                                                                                                                                        
    #[global_allocator]                                                                                                                                                                                            
    static ALLOCATOR: ::TAlloc = ::TAlloc;                                                                                                                                                                         
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
pub fn main() {                                                                                                                                                                                                    
}
```
causes:
```
error[E0432]: unresolved import `super`
  --> alloc.rs:15:5
   |
15 |     static ALLOCATOR: ::TAlloc = ::TAlloc;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ALLOCATOR` in the root
```

### LINKED ISSUE #58072: ICE when static global allocator is defined in main function
While writing some doctests for a custom allocator this popped up. Easy fix for the doc test, just add `# fn main() {}` after the static.

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0e1bac12dee35ccbe3d90ef002d90e52)

```rust
fn main() {
    #[global_allocator]
    static A: usize = 0;
}
```

```
Compiling playground v0.0.1 (/playground)
error[E0432]: unresolved import `super::A`
 --> src/main.rs:3:5
  |
3 |     static A: usize = 0;
  |     ^^^^^^^^^^^^^^^^^^^^ no `A` in the root

thread 'rustc' panicked at 'assertion failed: prev.is_none()', src/librustc/middle/region.rs:442:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::begin_panic
   7: <rustc::middle::region::RegionResolutionVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_stmt
   8: <rustc::middle::region::RegionResolutionVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
   9: rustc::middle::region::resolve_expr
  10: <rustc::middle::region::RegionResolutionVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  11: rustc::middle::region::region_scope_tree
  12: rustc::ty::query::__query_compute::region_scope_tree
  13: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::region_scope_tree<'tcx>>::compute
  14: rustc::dep_graph::graph::DepGraph::with_task_impl
  15: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with
  16: rustc_typeck::check::regionck::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::regionck_item
  17: rustc::ty::context::GlobalCtxt::enter_local
  18: rustc_typeck::check::wfcheck::check_item_well_formed
  19: rustc::ty::query::__query_compute::check_item_well_formed
  20: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_item_well_formed<'tcx>>::compute
  21: rustc::dep_graph::graph::DepGraph::with_task_impl
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  24: rustc::hir::Crate::visit_all_item_likes
  25: rustc::util::common::time
  26: rustc_typeck::check_crate
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc::ty::context::TyCtxt::create_and_enter
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler_with_pool
  31: <scoped_tls::ScopedKey<T>>::set
  32: rustc_driver::run_compiler
  33: <scoped_tls::ScopedKey<T>>::set
query stack during panic:
#0 [region_scope_tree] processing `main`
#1 [check_item_well_formed] processing `main`
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.0-nightly (852701ad6 2019-02-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by petrochenkov**
It was a 99% macro with exception of some diagnostic details.

As a result of the change, `#[global_allocator]` now works in nested modules and even in nameless blocks.

Fixes https://github.com/rust-lang/rust/issues/44113
Fixes https://github.com/rust-lang/rust/issues/58072

### CODE REVIEW

**Comment by eddyb** [comment]
r=me but I'd also check with @alexcrichton

File: src/libsyntax_ext/lib.rs [hunk 1]
```diff
@@ -150,6 +151,12 @@ pub fn register_builtins(resolver: &mut dyn syntax::ext::base::Resolver,
             SyntaxExtensionKind::LegacyAttr(Box::new(test::expand_bench)), edition
         )
     });
+    register(sym::global_allocator, SyntaxExtension {
+        allow_internal_unstable: Some([sym::rustc_attrs][..].into()),
+        ..SyntaxExtension::default(
+            SyntaxExtensionKind::LegacyAttr(Box::new(global_allocator::expand)), edition
```
Comment (alexcrichton) [inline src/libsyntax_ext/lib.rs]: I think in theory there's no need for this to be a legacy extension, but is this done for other reasons? I could imagine, for example:

* A bit faster since everything is already parsed
* Guaranteed good error messages since spans are always right
* Other builtin attributes still seem to be using legacy attributes

Just wanted to but sure this was intentional!

File: src/test/ui/feature-gate/issue-43106-gating-of-test.stderr [hunk 2]
```diff
@@ -1,7 +1,13 @@
+error: malformed `test` attribute input
+  --> $DIR/issue-43106-gating-of-test.rs:10:1
+   |
+LL | #![test                    = "4200"]
```
Comment (alexcrichton) [inline src/test/ui/feature-gate/issue-43106-gating-of-test.stderr]: Did we previously silently allow this? If so we may want to do this in a separate PR since the age of `#[test]` means that this could be likely for causing accidental regressions.

File: src/tools/tidy/src/features.rs [hunk 3]
```diff
@@ -344,7 +344,7 @@ fn get_and_check_lib_features(base_src_path: &Path,
                 Ok((name, f)) => {
                     let mut check_features = |f: &Feature, list: &Features, display: &str| {
                         if let Some(ref s) = list.get(name) {
-                            if f.tracking_issue != s.tracking_issue {
+                            if f.tracking_issue != s.tracking_issue && f.level != Status::Stable {
```
Comment (alexcrichton) [inline src/tools/tidy/src/features.rs]: To confirm, was this change intended to be included here?

**Review by alexcrichton — COMMENTED** [review]
Thanks @petrochenkov!

Definitely agree this should have been a macro from the start!

This makes me wonder if we can make `#[proc_macro]` and friends macros...

File: src/libsyntax_ext/lib.rs (hunk 1 above)
Comment (petrochenkov) [reply src/libsyntax_ext/lib.rs]: Well, it's legacy because everything built-in is still on legacy (aka AST-based).
We don't have good quasi-quoting that can be used internally to conveniently generate token streams, there are some unresolved issues with error recovery, but the long term plan is to migrate to tokens, yes.

But right now I simply took the existing code from `rustc_allocator` having signature `fn(ast::Item) -> Vec<ast::Item>` and wrapped it into the corresponding AST-based `SyntaxExtensionKind`.

File: src/tools/tidy/src/features.rs (hunk 3 above)
Comment (petrochenkov) [reply src/tools/tidy/src/features.rs]: Yes, the libcore change doesn't pass tidy without it.
Tidy expected a tracking issue in a `#[stable(...)]` attribute to coincide with something, but the problem is that `#[stable(...)]` doesn't support issue numbers - `#[stable(..., issue = "...")]` is not a valid attribute.

File: src/test/ui/feature-gate/issue-43106-gating-of-test.stderr (hunk 2 above)
Comment (petrochenkov) [reply src/test/ui/feature-gate/issue-43106-gating-of-test.stderr]: Yes, this was previously allowed.
I don't want to wait for a separate crater run for this, since I don't expect *this* kind of misuse to be common after seeing the statistics from https://github.com/rust-lang/rust/pull/57321.

I think I'll just demote this error to [this lint](https://github.com/rust-lang/rust/issues/57571) for `#[test]` and `#[bench]`.

**Comment by petrochenkov** [comment]
>This makes me wonder if we can make `#[proc_macro]` and friends macros...

Right now the proc macro harness generated for `--crate-type proc-macro` looks like this:
```rust
#[doc(hidden)]
pub mod decls {
    extern crate proc_macro;
    #[rustc_proc_macro_decls]
    pub static _DECLS: &[proc_macro::bridge::client::ProcMacro] =
        &[proc_macro::bridge::client::ProcMacro::custom_derive("MyDerive",
                                                               &[],
                                                               crate::my_derive),
          proc_macro::bridge::client::ProcMacro::attr("my_attr",
                                                      crate::my_attr),
          proc_macro::bridge::client::ProcMacro::bang("my_macro",
                                                      crate::my_macro)];
}
```
So, it cannot be generated by individual `#[proc_macro*]` attributes without a rework of the proc macro crate ABI.

File: src/libsyntax_ext/lib.rs (hunk 1 above)
Comment (alexcrichton) [reply src/libsyntax_ext/lib.rs]: Ok that's what I figured, thanks!

File: src/tools/tidy/src/features.rs (hunk 3 above)
Comment (alexcrichton) [reply src/tools/tidy/src/features.rs]: 👍

**Comment by alexcrichton** [comment]
Ok r=me if you're confident `#[test]` won't cause much breakage, it's easy to back out anyway. If you'd like to change it to wire up to a lint r=me also on that.

**Comment by eddyb** [comment]
@petrochenkov That's interesting, so proc macros and tests could use a common "gather" infrastructure? Then again, we could just store all the symbol names, and other information like attributes, entirely in crate metadata, and have `rustc_metadata` load it all based on that?

The only catch is that the symbol name can't be of the function itself, but of a wrapper around it (which could live in a hidden static next to the function).

**Comment by petrochenkov** [comment]
@eddyb 
>so proc macros and tests could use a common "gather" infrastructure? Then again, we could just store all the symbol names, and other information like attributes, entirely in crate metadata, and have rustc_metadata load it all based on that?

These two are similar, after the recent refactorings they are the only passes that
- cannot be represented as individual macros
- must run after the usual expansion is complete (this causes most of hacks and issues)

I didn't thought about the proc macro infra much, but regarding the test harness, it has to jump through so many hoops, and has so many silly restrictions, that it certainly comes to mind that it operates at the wrong time on the wrong data.

Perhaps it shouldn't construct all those imports on top of the already converged system and attempt to resolve them, but rather work e.g. at HIR lowering time and directly build some structures specialized for testing from available AST and `Res`olutions.
Yes, that would move some knowledge about the `--test` mode to HIR, but it could make test harness more reliable, and working in more scenarios, and hopefully less hacky.

**Comment by eddyb** [comment]
@petrochenkov So @Manishearth and someone else (I forget who now, sorry) were discussing the test harness stuff and the solution that seemed most reasonable was to add one `const` item per test (with whatever type `libtest` wants), that the compiler than gathers into a const slice at the top of the crate (even if the individual constants are inaccessible to imports).
That mechanism is pretty general and could work with whatever types a harness needed.
