### PR TITLE
Fix try_print_visible_def_path for Rust 2018

### LINKED ISSUE #56175: Private types suggested when not using extern crate
If I do:
```
extern crate regex;
fn main() {
    let s: String = regex::Regex::new("...").unwrap();
}
```

I get (as expected) an error (E0308 mismatched types) saying ... found type `regex::Regex`.

However, if I instead do:
```
use regex;
fn main() {
    let s: String = regex::Regex::new("...").unwrap();
}
```

I get an error saying ... found type `regex::re_unicode::Regex`.

But regex::re_unicode is private.

Observed with rustc 1.32.0-nightly (2018-11-15) with edition = "2018" and dependency of regex = "1.0".regex = "1.0"

#21934 is tracking work on not exposing private types. Feel free to dupe against that if you like, but I thought I'd raise this separately since although not technically a regression (I was using the same compiler), it feels like the experience of using the newer 2018 style is worse for this particular case.

### PR DESCRIPTION
**Pull request by da-x**
The recursive check of `try_print_visible_def_path` did not properly handle the Rust 2018 case of crate-paths without 'extern crate'. Instead, it returned a "not found" via (false, self).

 This fixes #56175.

### CODE REVIEW

File: src/librustc_middle/ty/print/pretty.rs [hunk 1]
```diff
@@ -282,26 +282,27 @@ pub trait PrettyPrinter<'tcx>:
...
+                        return Ok((
+                            if !span.is_dummy() {
+                                self.print_def_path(def_id, &[])?
+                            } else {
+                                self.path_crate(cnum)?
+                            },
+                            true,
+                        ));
+                    }
+                    (ExternCrateSource::Path, LOCAL_CRATE) if self.tcx().sess.rust_2018() => {
```
Comment (petrochenkov) [inline src/librustc_middle/ty/print/pretty.rs:297]: Why are Rust 2015 and Rust 2018 treated differently here?

Referring to extern crates without `extern crate` items is supported on both editions.

Comment (da-x) [reply src/librustc_middle/ty/print/pretty.rs]: Indeed, I forgot about it.

**Comment by petrochenkov** [comment]
Failed build and no output. Weird.
@bors retry

**Comment by oli-obk** [comment]
I believe this PR has caused https://github.com/rust-lang/rust/issues/74081(see backtrace: https://gist.github.com/Mark-Simulacrum/c1fd825658ba202c9d7f8be9293f62bc#file-gistfile1-txt-L39)
