### PR TITLE
Fix incorrect suggestion for extra `&` in pattern

### LINKED ISSUE #106182: Incorrect suggestion for extra `&` in pattern
Given the following code: 

```rust
struct S(u32, Vec<i32>);

fn foo(x: &S) {
    match x {
        S(& (mut y), v) => {
        }
    }
}
```

The current output is:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/lib.rs:5:11
  |
4 |     match x {
  |           - this expression has type `&S`
5 |         S(& (mut y), v) => {
  |           ^^^^^^^^^ expected `u32`, found reference
  |
  = note:   expected type `u32`
          found reference `&_`
help: consider removing `&` from the pattern
  |
5 -         S(& (mut y), v) => {
5 +         S(mut y), v) => {
  |
```
Note that the suggestion is wrong, it removes the `(` but left in the matching `)`. Applying that suggestion leads to invalid code:
```rust
struct S(u32, Vec<i32>);

fn foo(x: &S) {
    match x {
        S(mut y), v) => {
        }
    }
}
```
It should instead suggest
```
5 -         S(& (mut y), v) => {
5 +         S(mut y, v) => {
```

### PR DESCRIPTION
**Pull request by obeis**
Closes #106182

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -758,6 +758,28 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         err.span_note(sp, format!("{msg}: `{sugg}`"));
                     }
                 }
+                hir::Node::Pat(pt) if let PatKind::TupleStruct(_, pat_arr, _) = pt.kind => {
+                    for i in pat_arr.iter() {
+                        if let PatKind::Ref(the_ref, _) = i.kind {
+                            if let PatKind::Binding(mt, _, ident, _) = the_ref.kind {
+                                let hir::BindingAnnotation(_, mtblty) = mt;
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/pat.rs:765]: can you use let-chains here?

```
if let ...
    && let ...
    && let ...
{
    ..
}
```

Might make the code a bit easier to read

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 2]
```diff
@@ -758,6 +758,28 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                let ss = match mtblty {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/pat.rs:766]: I think you can just use https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/enum.Mutability.html#method.ref_prefix_str here
