### PR TITLE
Some promotion cleanup

### LINKED ISSUE #75586: Treat `const fn` like `fn` for promotion.
https://github.com/rust-lang/const-eval/issues/19 gives many arguments for why we should not promote `const fn` calls. However, we currently *do* promote `const fn` calls in `const fn`, even though that has all the same problems. This fails to compile, but really we shouldn't make this a hard error:
```rust
#![allow(unconditional_panic, const_err)]

const fn foo() { [()][42] }
pub const fn do_something(b: bool) -> i32 {
    if b {
        let _x = &foo();
    }
    13
}
```
This does not just apply to `const fn` calls; *all* promotion inside `const fn` should be treated like inside `fn`.

Cc @rust-lang/wg-const-eval

### PR DESCRIPTION
**Pull request by RalfJung**
Based on top of both https://github.com/rust-lang/rust/pull/75502 and https://github.com/rust-lang/rust/pull/75585, this does some cleanup of the promotion code. The last 2 commits are new.

* Remove the remaining cases where `const fn` is treated different from `fn`. This means no longer promoting ptr-to-int casts, raw ptr operations, and union field accesses in `const fn` -- or anywhere, for that matter. These are all unstable in const-context so this should not break any stable code. Fixes https://github.com/rust-lang/rust/issues/75586.
* ~~Promote references to statics even outside statics (i.e., in functions) for consistency.~~
* Promote `&mut []` everywhere, not just in non-`const` functions, for consistency.
* Explain why we do not promote deref's of statics outside statics. ~~(This is the only remaining direct user of `const_kind`.)~~

This can only land once the other two PRs land; I am mostly putting this up already because I couldn't wait ;) and to get some feedback from @rust-lang/wg-const-eval .

### CODE REVIEW

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 1]
```diff
@@ -315,74 +326,17 @@ impl<'tcx> Validator<'_, 'tcx> {
                             BorrowKind::Shallow | BorrowKind::Unique => return Err(Unpromotable),
                         }
 
-                        // We can only promote interior borrows of promotable temps (non-temps
-                        // don't get promoted anyway).
+                        // We only actually promote the projection base, so only that is further validated.
+                        // Make sure it does not need dropping!
```
Comment (RalfJung) [inline compiler/rustc_mir/src/transform/promote_consts.rs:330]: I *think* this is correct, based on the fact that we can promote this:
```rust
const ALL_THE_NUMS: [u32; 1] = [
    1
];

#[inline(never)]
fn array(i: usize) -> &'static u32 {
    return &ALL_THE_NUMS[i];
}
```
But maybe we are even more clever, and promote those projections that we can, stopping at `Index`?

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 2]
```diff
@@ -623,6 +629,7 @@ impl<'tcx> Validator<'_, 'tcx> {
 
             Rvalue::NullaryOp(NullOp::Box, _) => return Err(Unpromotable),
 
+            // FIXME(RalfJung): the rest is *implicitly considered promotable*... that seems dangerous.
```
Comment (oli-obk) [inline compiler/rustc_mir/src/transform/promote_consts.rs:630]: yea, we should totally exhaustively match here

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 3]
```diff
@@ -297,6 +297,17 @@ impl std::ops::Deref for Validator<'a, 'tcx> {
 struct Unpromotable;
 
 impl<'tcx> Validator<'_, 'tcx> {
+    //! Determines if this code could be executed at runtime and thus is subject to codegen.
+    //! That means even unused constants need to be evaluated.
+    //!
+    //! `const_kind` should not be used in this file other than through this method!
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:303]: I think these should be `///` in fact, I meant a normal doc comment... wll fix.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 4]
```diff
@@ -579,13 +537,6 @@ impl<'tcx> Validator<'_, 'tcx> {
             // `validate_rvalue` upon access.
             Operand::Constant(c) => {
                 if let Some(def_id) = c.check_static_ptr(self.tcx) {
-                    // Only allow statics (not consts) to refer to other statics.
-                    // FIXME(eddyb) does this matter at all for promotion?
-                    let is_static = matches!(self.const_kind, Some(hir::ConstContext::Static(_)));
-                    if !is_static {
-                        return Err(Unpromotable);
-                    }
-
```
Comment (ecstatic-morse) [inline compiler/rustc_mir/src/transform/promote_consts.rs:588]: Why do we want to promote `&STATIC`? The resulting reference is already `'static`, no? Is this doing something else that I'm not seeing? I would have expected us to go the other way and make statics ineligible for promotion in all contexts for now.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 5]
```diff
@@ -597,22 +548,67 @@ impl<'tcx> Validator<'_, 'tcx> {
...
+            return Err(Unpromotable);
+        }
+
+        Ok(())
+    }
+
     fn validate_rvalue(&self, rvalue: &Rvalue<'tcx>) -> Result<(), Unpromotable> {
         match *rvalue {
-            Rvalue::Cast(CastKind::Misc, ref operand, cast_ty) if self.const_kind.is_none() => {
+            Rvalue::Cast(CastKind::Misc, ref operand, cast_ty) if self.maybe_runtime() => {
```
Comment (ecstatic-morse) [inline compiler/rustc_mir/src/transform/promote_consts.rs:598]: Pointer to int casts are not allowed in any const context. We should never promote these.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 6]
```diff
@@ -597,22 +548,67 @@ impl<'tcx> Validator<'_, 'tcx> {
...
-                        // in normal functions, mark such casts as not promotable
+                        // ptr-to-int casts are not promotable
                         return Err(Unpromotable);
                     }
                     _ => {}
                 }
             }
 
-            Rvalue::BinaryOp(op, ref lhs, _) if self.const_kind.is_none() => {
+            Rvalue::BinaryOp(op, ref lhs, _) if self.maybe_runtime() => {
```
Comment (ecstatic-morse) [inline compiler/rustc_mir/src/transform/promote_consts.rs:611]: Pointer comparison/offset is not stable in any const context. We should never promote these.

Comment (ecstatic-morse) [reply compiler/rustc_mir/src/transform/promote_consts.rs:611]: Also missing here is floating point arithmetic, so we currently promote e.g. `&(42.0 * 55.1)`. This is actually okay, because the IEEE spec mandates the precision for simple arithmetic operations, so there shouldn't be a difference between the run-time and compile-time result. I wonder if this was a conscious choice way way back, or just a happy accident.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 7]
```diff
@@ -701,32 +674,7 @@ impl<'tcx> Validator<'_, 'tcx> {
                 }
```
Comment (ecstatic-morse) [inline compiler/rustc_mir/src/transform/promote_consts.rs:674]: `place` gets mutated here, so your refactor has changed the logic in ways that's difficult to predict.

**Review by ecstatic-morse — COMMENTED** [review]
I don't think we should be doing non-trivial refactors of this code without crater runs. I think this PR should just be the two crater-tested changes coupled with the removal of the `const_kind` check for things that are forbidden in a const-context anyways and promotion of `&mut []`. We just don't have good enough test coverage here, although I appreciate that you're trying to rectify that.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 4 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:588]: This enables `let _val: &'static [&'static u32] = &[&FOO2];` in a `fn`.

> I would have expected us to go the other way and make statics ineligible for promotion in all contexts for now.

I'm all in for restricting promotion but I doubt this one can be taken back -- and then it seems strange to not promote this in `fn`.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 6 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:611]: It probably was an accident.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:598]: I can remove it, but in the review comment you said you preferred not changing behavior without a crater run so I am not sure now what you'd prefer me to do.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 7 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:674]: Place gets rebound here, yeah... but on the second time reading this I agree I don't understand this code well enough. It removes a top-level `*` but only if the thing right below it is a reference... but that changes its type?!?

I'll move the `validate_ref` change to a separate PR once https://github.com/rust-lang/rust/pull/75585 lands.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:630]: I'll make that a separate PR with the other refactoring, as there is a big risk of regression there.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 5 above)
Comment (ecstatic-morse) [reply compiler/rustc_mir/src/transform/promote_consts.rs:598]: To me, this change is trivial, while the `validate_ref` refactor is not.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 4 above)
Comment (ecstatic-morse) [reply compiler/rustc_mir/src/transform/promote_consts.rs:588]: I think this should remain the same for now. Promoting `&STATIC` will cause us to generate more useless promoted MIR bodies for little benefit.

>  I doubt this one can be taken back.

Perhaps, but I would like some time to consider before committing to this in all contexts. `&STATIC` already works everywhere. `static OTHER: &[&u32] = &[&STATIC];` should work without promotion due to the "top-level scope" rule, so promotion is only helpful in very narrow circumstances.

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:588]: > Promoting &STATIC will cause us to generate more useless promoted MIR bodies for little benefit.

That's an argument against most promotion though...
My point is, there is absolutely no reason to do this promotion only in statics. That just makes no sense. And also I was hoping to make this a PR that doesn't require its own crater run with associated 2-3 weeks of waiting.

> static OTHER: &[&u32] = &[&STATIC]; should work without promotion due to the "top-level scope" rule, so promotion is only helpful in very narrow circumstances.

But `TupleStruct(&[&STATIC])` won't work without this. That might be narrow but not more narrow than many other cases here.

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:588]: But, I guess we can do baby steps for now. I'm just not very patient now that I finally see an endgame for this long-standing problem.^^

File: src/test/ui/consts/promotion.rs [hunk 8]
```diff
@@ -1,4 +1,4 @@
-// run-pass
+// check-pass
```
Comment (RalfJung) [inline src/test/ui/consts/promotion.rs:1]: There's not actually any code here to run, so I made this check-only.

File: src/test/ui/statics/static-promotion.rs [hunk 9]
```diff
@@ -1,4 +1,4 @@
-// check-pass
+// run-pass
```
Comment (RalfJung) [inline src/test/ui/statics/static-promotion.rs:1]: This actually contains assertions so I figure we should run it.

File: compiler/rustc_mir/src/transform/promote_consts.rs [hunk 10]
```diff
@@ -545,7 +558,7 @@ impl<'tcx> Validator<'_, 'tcx> {
                     }
 
                     ProjectionElem::Field(..) => {
-                        if self.const_kind.is_none() {
+                        if self.maybe_runtime() {
```
Comment (ecstatic-morse) [inline compiler/rustc_mir/src/transform/promote_consts.rs:561]: I didn't realize this in my first round of comments, but this means that we currently promote union field accesses in constants and statics but not `fn`, which is somewhat weird. Union field accesses are currently unstable in `const fn`, so this doesn't change anything for stable users, but if the goal is to normalize promotion across all const contexts, we need to figure out what to do here eventually.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 4 above)
Comment (ecstatic-morse) [reply compiler/rustc_mir/src/transform/promote_consts.rs]: I'm happy to discuss this change as part of its own PR. If I were consistent I suppose I would have demanded that the `&mut []` change be split out as well, but I'm less concerned about that one since promotion actually does lifetime extension and it fits better into my (pipe) dream of requiring that all promotable expressions be valid patterns.

**Comment by ecstatic-morse** [comment]
I think FCPs are 7 days long, so the one on #75502 has concluded even though the bot didn't leave a comment. Is this correct? This is a better abstraction than the one in #75502, so there's no need to wait for that one to filter through the queue unless we're worried about bisection. @RalfJung, do you wanna wait or squash this and add the title of #75502 to the PR summary?

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 10 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs:561]: Yes, I mentioned this in https://github.com/rust-lang/const-eval/issues/53.

We cannot accept them in `fn` as union field access are a fallible operation -- they can cause UB. So either we keep them const/static-only, or we never promote them. In my follow-up PR that needs crater anyway, I intend to reject promoting them to see what the fallout of that would be.

**Comment by RalfJung** [comment]
> I think FCPs are 7 days long

FCPs are 10 days long, so it should finish today or tomorrow. It seems confusing to not land the FCP's PR land (confusing to someone browsing through the history in the future to see what was done why). So I'd just let #75502 land.

File: compiler/rustc_mir/src/transform/promote_consts.rs (hunk 4 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/promote_consts.rs]: `&mut []` is also widely used, there is no taking it back, so it seems just odd to reject it in `const fn`/`const`/`static`.
