### PR TITLE
Replace the default branch with an unreachable branch If it is the last variant

### LINKED ISSUE #110097: missed optimization for `if let`, even though equivalent match is optimized
I tried this code:

```rust
pub fn change_value(val: Result<i32, ()>) -> Result<i32, ()> {
    if let Ok(x) = val {
        Ok(x * 2)
    } else {
        Err(())
    }
}

pub fn change_value2(val: Result<i32, ()>) -> Result<i32, ()> {
    match val {
        Ok(x) => Ok(x * 2),
        Err(()) => Err(())
    }
}
```

I expected to see this happen: 
in release build this code would translated into exact the same assembly/llvm-ir

Instead, this happened: 

```
change_value:
	xorl	%eax, %eax
	testl	%edi, %edi
	setne	%al
	leal	(%rsi,%rsi), %edx
	retq
change_value2:
	movl	%edi, %eax
	leal	(%rsi,%rsi), %edx
	retq
```

and the llvm-ir is different:

```
define { i32, i32 } @_ZN10playground12change_value17h0230bd4091fd6529E(i32 noundef %0, i32 %1) unnamed_addr #0 {
start:
  %2 = icmp eq i32 %0, 0
  %_4 = shl i32 %1, 1
  %not. = xor i1 %2, true
  %.sroa.0.0 = zext i1 %not. to i32
  %.sroa.3.0 = select i1 %2, i32 %_4, i32 undef
  %3 = insertvalue { i32, i32 } undef, i32 %.sroa.0.0, 0
  %4 = insertvalue { i32, i32 } %3, i32 %.sroa.3.0, 1
  ret { i32, i32 } %4
}
```

```
define { i32, i32 } @_ZN10playground13change_value217h3302fbc2853d0a41E(i32 noundef %0, i32 %1) unnamed_addr #0 {
start:
  %switch = icmp eq i32 %0, 0
  %_4 = shl i32 %1, 1
  %.sroa.3.0 = select i1 %switch, i32 %_4, i32 undef
  %2 = insertvalue { i32, i32 } undef, i32 %0, 0
  %3 = insertvalue { i32, i32 } %2, i32 %.sroa.3.0, 1
  ret { i32, i32 } %3
}
```

### Meta

I tried thin in rust-playground for 1.68.2, beta and nightly.

See also https://internals.rust-lang.org/t/why-match-is-better-then-if/18636

### LINKED ISSUE #119520: Wrapper generates more instructions for simple integer operations
### Code

I tried this code ([godbolt](https://godbolt.org/z/4dn9Tr7T1)):

```rust
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Int(u32);

const A: Int = Int(201);
const B: Int = Int(270);
const C: Int = Int(153);

#[inline(never)]
#[rustfmt::skip]
pub fn wrapped(x: Int) -> bool {
    (x >= A && x <= B)
        || x == C
}

#[inline(never)]
#[rustfmt::skip]
pub fn primitive(x: Int) -> bool {
    (x.0 >= A.0 && x.0 <= B.0)
        || x.0 == C.0
}
```

I expected to see this happen: both functions compile to identical assembly

Instead, this happened: `wrapped` contains way more instructions:

```gas
example::wrapped:
        cmp     edi, 201
        jb      .LBB0_3
        xor     eax, eax
        cmp     edi, 270
        mov     ecx, 255
        setne   al
        cmovae  ecx, eax
        mov     al, 1
        test    cl, cl
        je      .LBB0_4
        movzx   ecx, cl
        cmp     ecx, 255
        jne     .LBB0_3
.LBB0_4:
        ret
.LBB0_3:
        cmp     edi, 153
        sete    al
        ret

example::primitive:
        lea     eax, [rdi - 201]
        cmp     eax, 70
        setb    cl
        cmp     edi, 153
        sete    al
        or      al, cl
        ret
```

### Version it worked on

It most recently worked on: 1.64

### Version with regression

`rustc --version --verbose`:
```
rustc 1.77.0-nightly (e51e98dde 2023-12-31)
binary: rustc
commit-hash: e51e98dde6a60637b6a71b8105245b629ac3fe77
commit-date: 2023-12-31
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

I have bisected it to between 1.64 and 1.65 on Godbolt, and then further with `cargo bisect-rustc` which points to `nightly-2022-08-17` (https://github.com/rust-lang/rust/compare/40336865fe7d4a01139a3336639c6971647e885c...86c6ebee8fa0a5ad1e18e375113b06bd2849b634):

```
Regression in nightly-2022-08-17
...
looking for regression commit between 2022-08-16 and 2022-08-17
...
found 8 bors merge commits in the specified range
  commit[0] 2022-08-15: Auto merge of #100595 - matthiaskrgr:rollup-f1zur58, r=matthiaskrgr
  commit[1] 2022-08-15: Auto merge of #100007 - ChrisDenton:dtor-inline-never, r=michaelwoerister
  commit[2] 2022-08-16: Auto merge of #100237 - cjgillot:no-special-hash-hir, r=nagisa
  commit[3] 2022-08-16: Auto merge of #100611 - matthiaskrgr:rollup-rxj10ur, r=matthiaskrgr
  commit[4] 2022-08-16: Auto merge of #100441 - nnethercote:shrink-ast-Attribute, r=petrochenkov
  commit[5] 2022-08-16: Auto merge of #99612 - yanchen4791:issue-95079-fix, r=compiler-errors
  commit[6] 2022-08-16: Auto merge of #100626 - Dylan-DPC:rollup-mwbm7kj, r=Dylan-DPC
  commit[7] 2022-08-16: Auto merge of #100644 - TaKO8Ki:rollup-n0o6a1t, r=TaKO8Ki
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

@rustbot modify labels: +I-slow +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #119520. Fixes #110097.

LLVM currently has limited ability to eliminate dead branches in switches, even with the patch of https://github.com/llvm/llvm-project/issues/73446.

The main reasons are as follows:

- Additional costs are required to calculate the range of values, and there exist many scenarios that cannot be analyzed accurately.
- Matching values by bitwise calculation cannot handle odd branches, nor can it handle values like `-1, 0, 1`. See [SimplifyCFG.cpp#L5424](https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L5424) and https://llvm.godbolt.org/z/qYMqhvMa8
- The current range information is continuous, even if the metadata for the range is submitted. See [ConstantRange.cpp#L1869-L1870](https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/llvm/lib/IR/ConstantRange.cpp#L1869-L1870).
- The metadata of the range may be lost in passes such as SROA. See https://rust.godbolt.org/z/e7f87vKMK.

Although we can make improvements, I think it would be more appropriate to put this issue to rustc first. After all, we can easily know the possible values.

Note that we've currently found a slow compilation problem in the presence of unreachable branches. See 
https://github.com/llvm/llvm-project/issues/78578.

r? compiler

### CODE REVIEW

File: compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs [hunk 1]
```diff
@@ -103,20 +104,29 @@ impl<'tcx> MirPass<'tcx> for UninhabitedEnumBranching {
...
+                if !allowed_variants.remove(&val) {
                     removable_switchs.push((bb, index));
                 }
             }
 
-            if reachable_count == allowed_variants.len() {
+            if allowed_variants.is_empty() {
                 removable_switchs.push((bb, targets.iter().count()));
+            } else if allowed_variants.len() == 1 {
+                #[allow(rustc::potential_query_instability)]
```
Comment (oli-obk) [inline compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:116]: Try using an IndexSet instead of picking a random item. If perf is happy with it, too, we'll go that route.

Comment (cjgillot) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:116]: There is a single item, so that's not random. Still deserves a comment to justify the attribute.

Comment (oli-obk) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:116]: 🤦 yea was so focussed on the creation of the set, I forgot that there is this one valid use for it 😆

File: tests/mir-opt/uninhabited_enum_branching.rs [hunk 2]
```diff
@@ -55,6 +63,80 @@ fn custom_discriminant() {
...
+    // CHECK: switchInt(move [[discr]]) -> [0: bb2, 1: bb3, 2: bb4, 3: bb1, otherwise: bb6];
+    // CHECK: bb6: {
+    // CHECK-NEXT: unreachable;
+    match Test4::C {
+        Test4::A(_) => "A(i32)",
+        Test4::B(_) => "B(i32)",
+        Test4::C => "C",
+        _ => "D",
+    };
+}
```
Comment (cjgillot) [inline tests/mir-opt/uninhabited_enum_branching.rs:124]: Does this still work if `Test4` holds a generic type instead of an `i32`? Should it be made so?

File: tests/mir-opt/uninhabited_enum_branching.rs [hunk 3]
```diff
@@ -42,6 +49,7 @@ fn simple() {
     };
 }
 
+
```
Comment (cjgillot) [inline tests/mir-opt/uninhabited_enum_branching.rs:52]: Nit: stray newline.

File: tests/mir-opt/uninhabited_enum_branching.rs [hunk 4]
```diff
@@ -55,6 +63,80 @@ fn custom_discriminant() {
...
+    // CHECK: switchInt(move [[discr]]) -> [0: bb2, 1: bb3, otherwise: bb1];
+    // CHECK: bb1: {
+    // CHECK-NOT: unreachable;
+    // CHECK: }
+    match Test4::C {
+        Test4::A(_) => "A(i32)",
+        Test4::B(_) => "B(i32)",
+        _ => "CD",
+    };
+}
```
Comment (cjgillot) [inline tests/mir-opt/uninhabited_enum_branching.rs:139]: Nit: missing newline.

File: tests/mir-opt/uninhabited_enum_branching.rs (hunk 2 above)
Comment (DianQK) [reply tests/mir-opt/uninhabited_enum_branching.rs:129]: If I understand correctly, this will be split into multiple `switchInt`. So I expect generic type to get the same result. But the test case is not happening, so I should be missing something.

File: compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs (hunk 1 above)
Comment (DianQK) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:116]: I can convert to `Vec`, but I'm not sure if that makes sense.

Comment (oli-obk) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:116]: nah, this was just me not getting it. a comment is totally sufficient

File: tests/mir-opt/uninhabited_enum_branching.rs (hunk 2 above)
Comment (DianQK) [reply tests/mir-opt/uninhabited_enum_branching.rs:130]: I added support for generic type.

**Comment by DianQK** [comment]
Based on the discussion in [zulipchat](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/.E2.9C.94.20The.20MIR.20outputs.20for.20bless.20and.20test.20are.20different.20.23120268), I have changed `src/bootstrap/src/core/build_steps/test.rs`.

**Comment by DianQK** [comment]
Hmm, I just remembered a possible regression issue, but I don't think that should affect merging this PR. Because we're on the road to a better outcome.

```rust
#![crate_type = "lib"]

pub enum Bar {
    Foo = 1,
    Bar = 2,
    Baz = 3
}

#[no_mangle]
pub fn lookup(v: Bar) -> i32 {
    match v {
        Bar::Foo => 8,
        Bar::Bar => 9,
        Bar::Baz => 3,
    }
}

#[no_mangle]
pub fn compare(v: Bar) -> i32 {
    match v {
        Bar::Foo => 8,
        Bar::Bar => 9,
        _ => 3,
    }
}

#[no_mangle]
pub fn lookup2(v: Bar) -> i32 {
    match v {
        Bar::Foo => 1,
        Bar::Bar => 2,
        Bar::Baz => 3,
    }
}

#[no_mangle]
pub fn compare2(v: Bar) -> i32 {
    match v {
        Bar::Foo => 1,
        Bar::Bar => 2,
        _ => 3,
    }
}
```

GodBolt: https://rust.godbolt.org/z/55dq6zbjd

The `lookup` function will create a lookup table with a load instruction. I'm not sure which is better, compared to the `compare`. See [SimplifyCFG.cpp#L6410](https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L6410).
But most of the scenarios should get better as we provide new `unreachable` facts, such as `lookup2` and `compare2`.

**Comment by DianQK** [comment]
Some targets are set to abort. It makes no sense to simply change the position of `run(target);`? Instead, I should consider using `EMIT_MIR_FOR_EACH_PANIC_STRATEGY`.

**Comment by DianQK** [comment]
> Some targets are set to abort. It makes no sense to simply change the position of `run(target);`? Instead, I should consider using `EMIT_MIR_FOR_EACH_PANIC_STRATEGY`.

Done. I changed the commit order.

**Comment by DianQK** [comment]
```
llvm/include/llvm/CodeGen/MachineOperand.h:370: Register llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
```

A LLVM backend issue.

**Comment by DianQK** [comment]
Fixing the upstream issue in progress.

@rustbot author

**Comment by nikic** [comment]
@bors r-

Probably someone performed a bors synchronize and this got back into the queue.

**Comment by nikic** [comment]
Do you think it's safe to do this, given the TailDuplicator compile-time issue that we ran into with the two LLVM patches that tried to do something like this?

**Comment by DianQK** [comment]
> Do you think it's safe to do this, given the TailDuplicator compile-time issue that we ran into with the two LLVM patches that tried to do something like this?

I'm not sure. But rustc always submits unreachable for the full match statement, which should make it easier to run into that problem?

**Comment by DianQK** [comment]
The latest commit adds generic support.

@bors try @rust-timer queue

**Comment by DianQK** [comment]
It's amazing how the previous improvements (mostly checks and debugs) disappeared. The test case did not hit the `TailDuplicator` issue. But I think it makes sense to address the `TailDuplicator` issue first.

**Comment by DianQK** [comment]
I pushed three times. The first one was just conflict resolution. [The second one](https://github.com/rust-lang/rust/compare/3661b42a6856f1b8c95276398de7ea3abcd703e8..b61a3267c82dcdb05f815ee71daa5018c390ad73) is just a little revision. The third one is a major change.

I'm not sure when https://github.com/llvm/llvm-project/issues/78578 could be fixed. Based on these issues fixed by this PR, I think it makes sense to add a workaround.

@bors try @rust-timer queue

**Comment by DianQK** [comment]
Fixed.
@bors try @rust-timer queue

**Comment by DianQK** [comment]
> Do you think it's safe to do this, given the TailDuplicator compile-time issue that we ran into with the two LLVM patches that tried to do something like this?

I added a workaround. As much as I don't want to.

@rustbot ready

File: tests/codegen/enum/uninhabited_enum_default_branch.rs
Comment (RalfJung) [inline tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: There is no uninhabited enum anywhere in this test... how does the test filename make sense?

File: compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs [hunk 5]
```diff
@@ -92,46 +95,73 @@ impl<'tcx> MirPass<'tcx> for UninhabitedEnumBranching {
...
+                {
+                    return false;
+                };
+                true
             }
+            let otherwise_is_last_variant = !otherwise_is_empty_unreachable
+                && allowed_variants.len() == 1
+                && check_successors(&body.basic_blocks, targets.otherwise());
+            let replace_otherwise_to_unreachable = otherwise_is_last_variant
+                || !otherwise_is_empty_unreachable && allowed_variants.is_empty();
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:143]: This could use a few more comments explaining what happens here -- why all these checks are needed and why they are combined in exactly the way they are.

Also, `a || b && c` could use parentheses, so precedence is currently unclear.

Comment (DianQK) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:143]: Hmm, testing has started, `r-` or I'll add a PR subsequently?

File: tests/codegen/enum/uninhabited_enum_default_branch.rs
Comment (RalfJung) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: But again there's no uninhabited enums anywhere, so (a) what does the test content have to do with the filename, and (b) what does it have to do with this PR?

File: compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_mir_transform/src/uninhabited_enum_branching.rs:143]: Subsequent PR is fine.

File: tests/codegen/enum/uninhabited_enum_default_branch.rs
Comment (RalfJung) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: Reading the code a bit more, I think the MIR pass (and associated test) are misnamed. This is no longer just about uninhabited variants, it is now also about exploiting that `Discriminant` will never return something that isn't a variant index. I am a bit surprised that this is done as a MIR transform rather than during MIR building but the MIR transform is correct according to our current understanding of MIR semantics. Just the name is misleading after this PR.

Comment (DianQK) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: (a) I can change the file name to `issue-119520.rs`.
(b) https://rust.godbolt.org/z/za5c5hzoY When I reduce the issue's case, I found out that it uses `Ordering` after inlining. It implies the enum. I also hope that this test case will not lose optimization due to other changes in the future.

Comment (DianQK) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: Yes. I'm considering updating the name. (It’s just that I didn’t think of a suitable name.)
Maybe I can change it to `UnreachabledEnumBranching`.

> I am a bit surprised that this is done as a MIR transform rather than during MIR building but the MIR transform is correct according to our current understanding of MIR semantics. Just the name is misleading after this PR.

It better for me to have MIR building match the structure of the code itself where possible. (This purpose may not matter either?)

Comment (RalfJung) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: > It better for me to have MIR building match the structure of the code itself where possible. (This purpose may not matter either?)

Ah, I may have misunderstood where this optimization kicks in. I thought even this would just use fallback for the last variant:
```rust
    match c {
        Less => -5,
        Equal => 0,
        Greater => 42,
    }
```

But already on stable that becomes `switchInt(move _2) -> [255: bb3, 0: bb4, 1: bb1, otherwise: bb2]`.

> I can change the file name to issue-119520.rs.

Once we have a better name for the pass, it can use that name. (Though it would also be good to mention the issue either in the file name or file contents. It's always good to add more cross-references and those are otherwise much harder to reconstruct in the future.)

> Maybe I can change it to UnreachableEnumBranching.

I like it. :) The module-level comment in that file should then explain the two ways that "unreachable" is determined.

Comment (DianQK) [reply tests/codegen/enum/uninhabited_enum_default_branch.rs:1]: > Ah, I may have misunderstood where this optimization kicks in. I thought even this would just use fallback for the last variant:
> 
> ```rust
>     match c {
>         Less => -5,
>         Equal => 0,
>         Greater => 42,
>     }
> ```
> 
> But already on stable that becomes `switchInt(move _2) -> [255: bb3, 0: bb4, 1: bb1, otherwise: bb2]`.

This is something `UninhabitedEnumBranching` has already done.

This PR transforms following codes

```rust
    match c {
        Less => -5,
        Equal => 0,
        _ => 42,
    }
```

to

```rust
    match c {
        Less => -5,
        Equal => 0,
        Greater => 42,
    }
```
.

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

@DianQK the 1.8% regression to cargo opt-full is concerning to me. But from looking at the early rust-timer invocations, I saw it come up only once, not every time. So its not clear to me how much it was anticipated in your developments here.

Do you have any idea where the cargo opt-full regression is arising? Is it somehow connected to https://github.com/llvm/llvm-project/issues/78578 ?

(not marking as triaged not yet.)

**Comment by DianQK** [comment]
I don't think this is a regression. This is the result of previous try:  
https://github.com/rust-lang/rust/pull/120268#issuecomment-1985036234. I don't see cargo related regressions.
I made another attempt by revert this PR: https://github.com/rust-lang/rust/pull/122414. I can only see cranelift-codegen restoring the previous result.

Or maybe I'm missing something.
Usually, I think adding a fact may provide more opportunities for optimization. We need more work to optimize. This may be a desired result.

**Comment by DianQK** [comment]
> Is it somehow connected to [llvm/llvm-project#78578](https://github.com/llvm/llvm-project/issues/78578) ?

I don't think it's relevant. I should see the output size increase because `early-tailduplication` will duplicate instructions. But the actual result is `-0.38%`.

**Comment by pnkfelix** [comment]
We discussed the cargo opt-full a little at T-compiler meeting today ([zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-03-14/near/426558533))

Decided that this does seem, from the chart, that it was subsequently resolved, potentially by PR #120985

@rustbot label: +perf-regression-triaged
