### PR TITLE
Experimentally add *heterogeneous* `try` blocks

### LINKED ISSUE #149025: Possible try blocks regression in nightly
### Code

I tried this code (requires anyhow):

```rust
#![feature(try_blocks)]

fn main() {
    let _config: Result<String, anyhow::Error> = try {
        std::str::from_utf8(&std::fs::read("")?)?.to_string()
    };
}
```

<details><summary>If you prefer example without external dependencies</summary>
<p>

```rust
#![feature(try_blocks)]

struct Error {
}

impl From<std::io::Error> for Error {
    fn from(_: std::io::Error) -> Self {
        Self{}
    }
}

impl From<std::str::Utf8Error> for Error {
    fn from(_: std::str::Utf8Error) -> Self {
        Self{}
    }
}

fn main() {
    let _config: Result<String, Error> = try {
        std::str::from_utf8(&std::fs::read("")?)?.to_string()
    };
}
```

</p>
</details>

I expected to see this happen: successful compilation (which was the case up to (including) nighly-2025-11-14)

Instead, this happened: compilation failure
```
   Compiling anyhow v1.0.100
   Compiling dtmphaaYkobK v0.1.0 (/tmp/dtmphaaYkobK)
error[E0308]: mismatched types
   --> src/main.rs:5:30
    |
  5 |         std::str::from_utf8(&std::fs::read("")?)?.to_string()
    |                              ^^^^^^^^^^^^^^^^^^ expected `Result<String, Error>`, found `Result<_, Error>`
    |
    = note: `std::io::Error` and `anyhow::Error` have similar names, but are actually distinct types
note: `std::io::Error` is defined in crate `std`
   --> /rustc/b6d7ff3aa71e48e2901b0900f8b5d98126b537ed/library/std/src/io/error.rs:65:0
note: `anyhow::Error` is defined in crate `anyhow`
   --> /home/marakasov/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.100/src/lib.rs:394:1
    |
394 | pub struct Error {
    | ^^^^^^^^^^^^^^^^
help: consider using `Result::expect` to unwrap the `Result<_, std::io::Error>` value, panicking if the value is a `Result::Err`
    |
  5 |         std::str::from_utf8(&std::fs::read("")?.expect("REASON"))?.to_string()
    |                                                +++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `dtmphaaYkobK` (bin "dtmphaaYkobK") due to 1 previous error
```

### Version it worked on

It most recently worked on: `rustc 1.93.0-nightly (2286e5d22 2025-11-13)`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.93.0-nightly (b6d7ff3aa 2025-11-14)
binary: rustc
commit-hash: b6d7ff3aa71e48e2901b0900f8b5d98126b537ed
commit-date: 2025-11-14
host: x86_64-unknown-linux-gnu
release: 1.93.0-nightly
LLVM version: 21.1.5
```

### PR DESCRIPTION
**Pull request by scottmcm**
rust-lang/rust#148725 moved the default to being homogeneous; this adds heterogeneous ones back under an obvious-bikeshed syntax so people can experiment with that as well.

Essentially resolves rust-lang/rust#149025 by letting them move to this syntax instead.

New tracking issue: rust-lang/rust#149488
Related RFC: https://github.com/rust-lang/rfcs/pull/3721#issuecomment-3208342727 (specifically about experimenting)

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -416,6 +417,14 @@ enum AstOwner<'a> {
     ForeignItem(&'a ast::ForeignItem),
 }
 
+#[derive(Copy, Clone, Debug)]
+enum TryBlockScope {
+    /// There isn't a `try` block, so the scope is the function or closure or ...
```
Comment (nnethercote) [inline compiler/rustc_ast_lowering/src/lib.rs]: It took me a few reads to understand this comment. Can it be rephrased? What other possibilities are there?

File: compiler/rustc_ast/src/ast.rs [hunk 2]
```diff
@@ -1806,8 +1806,9 @@ pub enum ExprKind {
     /// A use expression (`x.use`). Span is of use keyword.
     Use(Box<Expr>, Span),
 
-    /// A try block (`try { ... }`).
-    TryBlock(Box<Block>),
+    /// A try block (`try { ... }`), if the type is `None`, or
+    /// A try block (`try bikeshed Ty { ... }`) if the type is `Some`.
```
Comment (nnethercote) [inline compiler/rustc_ast/src/ast.rs:1810]: Nowhere in the PR is an explanation that `bikeshed` is deliberately ridiculous placeholder syntax. (I assume that's what it is.) Probably worth mentioning at least once. This might be a good spot for it.

**Review by nnethercote — APPROVED** [review]

**Comment by nnethercote** [comment]
Standard plumbing, mostly, seems fine.

r=me with the nits addressed.

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 3]
```diff
@@ -423,6 +424,18 @@ enum AstOwner<'a> {
...
 }
 
+#[derive(Copy, Clone, Debug)]
+enum TryBlockScope {
+    /// There isn't a `try` block, so a `?` will use `return`.
+    Function,
+    /// We're inside a `try { … }` block, so a `?` will block-break
+    /// from that block using a type depending only on the argument.
+    Homogeneous(HirId),
+    /// We're inside a `try as _ { … }` block, so a `?` will block-break
```
Comment (nxsaken) [inline compiler/rustc_ast_lowering/src/lib.rs:434]:
```suggestion
    /// We're inside a `try bikeshed _ { … }` block, so a `?` will block-break
```

File: compiler/rustc_ast/src/visit.rs [hunk 4]
```diff
@@ -1048,8 +1048,8 @@ macro_rules! common_visitor_and_walkers {
                     visit_visitable!($($mut)? vis, kind),
                 ExprKind::Try(subexpression) =>
                     visit_visitable!($($mut)? vis, subexpression),
-                ExprKind::TryBlock(body) =>
-                    visit_visitable!($($mut)? vis, body),
+                ExprKind::TryBlock(body, optional_type) =>
+                    visit_visitable!($($mut)? vis, body, optional_type),
```
Comment (nxsaken) [inline compiler/rustc_ast/src/visit.rs:1052]:
```suggestion
                ExprKind::TryBlock(body, opt_ty) =>
                    visit_visitable!($($mut)? vis, body, opt_ty),
```

(For simpler searching, since other places use `opt_ty`.)
