### PR TITLE
Revamp `// run-fail` wrt. `--pass` & support `// build-fail` & `// check-fail`

### LINKED ISSUE #66929: `./x.py test --pass check` fails
The following command fails on master:
```
./x.py -j4 test --stage 1 src/test/ui --test-args issue-65419 --pass check
```
says
```
[...]
---- [ui] ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs stdout ----

error: error pattern ' thread 'main' panicked at '`async fn` resumed after panicking'' not found!
status: exit code: 0
command: "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/r/src/rust/rustc.2/src/test/ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/test/ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018" "-L" "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/test/ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic/auxiliary" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------




failures:
    [ui] ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-completion.rs
    [ui] ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs
    [ui] ui/async-await/issues/issue-65419/issue-65419-generator-resume-after-completion.rs
```
Omitting the `--pass check` fixes that.  The offending tests are all `run-fail` tests with an `error-pattern`, looks like those don't work properly with `--pass check`?

Cc @Mark-Simulacrum

### LINKED ISSUE #67128: `rustdoc-ui` tests fail when `x.py` is run with `--pass check`
E.g. `./x.py test --bless --stage 1 --pass check src/test/rustdoc-ui`.

Errors look like this:
```
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: Unrecognized option: 'emit'


------------------------------------------
```

It prevents running `rustdoc-ui` tests together with other tests suites for which `--pass check` makes sense.
Usually test suites ignore this option if they cannot work with it.

### PR DESCRIPTION
**Pull request by Centril**
Revamp how `// run-fail` tests work internally by having a separate `FailMode` that does not interfere with `PassMode`. In particular, `--pass check` will now have no effect on `// *-fail` tests. Moreover, new test annotations `// check-fail` (the default) and `// build-fail` are added. The latter is useful to distinguish post-monomorphization failures from pre-monomorphization failures as seen throughout the PR. Finally, ensure that non-`Ui` tests do not listen to `--pass check` such that the flag can be used with e.g. `./x.py test --pass check` directly.

Fixes #66929.
Fixes #67128.

r? @petrochenkov 
cc @RalfJung @ninjasource

### CODE REVIEW

**Comment by Centril** [comment]
I wrote this PR directly from the GH UI since I'm working on a different PR, so I've only reasoned my way to this diff for now.

File: src/tools/compiletest/src/header.rs [hunk 1]
```diff
@@ -637,7 +637,11 @@ impl TestProps {
     pub fn pass_mode(&self, config: &Config) -> Option<PassMode> {
         if !self.ignore_pass {
             if let (mode @ Some(_), Some(_)) = (config.force_pass_mode, self.pass_mode) {
-                return mode;
+                if self.pass_mode != PassMode::RunFail {
```
Comment (RalfJung) [inline src/tools/compiletest/src/header.rs]: `self.pass_mode` is of type `Option<PassMode>` so I doubt this will work.

Comment (Centril) [reply src/tools/compiletest/src/header.rs]: Fixed, I hope

File: src/tools/compiletest/src/header.rs [hunk 2]
```diff
@@ -636,8 +636,12 @@ impl TestProps {
 
     pub fn pass_mode(&self, config: &Config) -> Option<PassMode> {
         if !self.ignore_pass {
-            if let (mode @ Some(_), Some(_)) = (config.force_pass_mode, self.pass_mode) {
-                return mode;
+            if let (mode @ Some(_), Some(pm_file)) = (config.force_pass_mode, self.pass_mode) {
+                if pm_file != PassMode::RunFail {
+                    // HACK(Centril): See #66929. Ensure that `--pass check`
```
Comment (petrochenkov) [inline src/tools/compiletest/src/header.rs]: `PassMode::RunFail`? O_O
cc https://github.com/rust-lang/rust/pull/64158
@tmandry, run-*fail* tests are clearly not pass tests and should not be affected by `--pass` options at all, similarly to other tests failing at compile time.

Can we get a proper solution instead of hacks?
It's not super urgent and the tests can be moved into the run-fail directory in the meantime if we need to wait for more than a ~week.

Comment (Centril) [reply src/tools/compiletest/src/header.rs]: I was thinking the same thing, but I wanted to write a quick hack to make `--pass check` work again, which seemed the higher order priority. Practically speaking this implementation does achieve run-fail not being affected by the `--pass` option but I would agree that there's a cleaner way to do it code-wise. Perhaps we should file an issue for improving the impl for now?

Comment (petrochenkov) [reply src/tools/compiletest/src/header.rs]: I'm personally ok with the issue being unfixed for a week, which should be enough for the improved version.
If someone wants it sooner, feel free to r+.

**Comment by ninjasource** [comment]
@Centril and @petrochenkov, there is a preexisting (and passing) ```run-fail``` unit test in ```ui``` called ```src/test/ui/test-panic-abort.rs``` which has the following header comments:

```
// compile-flags: --test -Cpanic=abort -Zpanic_abort_tests
// run-flags: --test-threads=1
// run-fail
// check-run-results
// exec-env:RUST_BACKTRACE=0

// ignore-wasm no panic or subprocess support
// ignore-emscripten no panic or subprocess support
```

It may be worthwhile adding the relevant flags above to the offending async run-fail tests. However, I'm not sure if this test gets any special treatment and I cannot reproduce the failures locally.

File: src/tools/compiletest/src/header.rs (hunk 2 above)
Comment (tmandry) [reply src/tools/compiletest/src/header.rs]: Sorry for misunderstanding, I was actually interpreting "pass" more in the sense of "compiler pass." As in this is a "test pass" of a certain category of tests.

Comment (tmandry) [reply src/tools/compiletest/src/header.rs]: Or in the specific test case (which I probably had in mind here), "this test passes only when we run this program and it fails."

**Comment by Centril** [comment]
@petrochenkov I've rewritten the approach from scratch to something more useful and principled. :)

File: src/tools/compiletest/src/runtest.rs [hunk 3]
```diff
@@ -1377,7 +1376,7 @@ impl<'test> TestCx<'test> {
     fn check_error_patterns(&self, output_to_check: &str, proc_res: &ProcRes) {
         debug!("check_error_patterns");
         if self.props.error_patterns.is_empty() {
-            if self.pass_mode().is_some() {
+            if self.props.fail_mode != Some(FailMode::Run) {
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs]: Could you add a FIXME for https://github.com/rust-lang/rust/issues/65865 here?

File: src/tools/compiletest/src/runtest.rs [hunk 4]
```diff
@@ -2029,7 +2028,9 @@ impl<'test> TestCx<'test> {
             }
         }
 
-        if let Some(PassMode::Check) = self.pass_mode() {
+        if let (Some(PassMode::Check), ..) | (_, Some(FailMode::Check), Ui)
+            = (self.pass_mode(), self.props.fail_mode, self.config.mode)
+        {
             rustc.args(&["--emit", "metadata"]);
```
Comment (petrochenkov) [inline src/tools/compiletest/src/runtest.rs]: Apparently the `!is_rustdoc` condition should be here as well, because `rustdoc` doesn't understand `--emit metadata` - https://github.com/rust-lang/rust/issues/67128.

File: src/test/ui/asm/issue-51431.rs [hunk 5]
```diff
@@ -1,3 +1,4 @@
+// build-fail
```
Comment (petrochenkov) [inline src/test/ui/asm/issue-51431.rs]: I don't see how this is checked.
Looks like if the test starts failing at the "check" phase it will still pass with the `// build-fail` annotation.

Why are such annotations useful then?

Comment (petrochenkov) [reply src/test/ui/asm/issue-51431.rs]: Also, how the `// build-fail` test set was collected?
This can be done by introducing some kind of analogue of `--pass check`, but for failing tests, but I don't see it in this PR.

Comment (Centril) [reply src/test/ui/asm/issue-51431.rs]: >  Looks like if the test starts failing at the "check" phase it will still pass with the `// build-fail` annotation.

Ouch; Didn't think of that. To fix it, I think we'd need to compile the test twice, once as `check-pass` and once as `build-fail`.

> Also, how the `// build-fail` test set was collected?

A set of tests started failing because they did not fail with `--emit metadata`.

>  This can be done by introducing some kind of analogue of `--pass check`, but for failing tests, but I don't see it in this PR.

Didn't feel necessary, but I can add `--fail` if you think it's useful.

Comment (petrochenkov) [reply src/test/ui/asm/issue-51431.rs]: >but I can add --fail if you think it's useful.

No, no, just running twice would probably be preferable, the number of such tests is not too large, but we need to measure.
This is material for another PR anyway.

Comment (Centril) [reply src/test/ui/asm/issue-51431.rs]: I think I fixed it, but I had to refactor things to get rid of some implicit state to make it work. I think things should be less brittle & more understandable now. Let's see what the CI builder says. :)

**Comment by Centril** [comment]
PR builder is happy at last. 🎉

**Comment by Centril** [comment]
Fixed the 32-bit-only tests wrt. build-fail.

@bors r=petrochenkov
