### PR TITLE
Fix missing explanation of where the borrowed reference is used when the same borrow occurs multiple times due to loop iterations

### LINKED ISSUE #99824: Borrow checker gives E0499 in loops with mutable borrows, but it is misleading
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6a4dbffaa1c7bfe6e167b40eacaca921
The current output is:

```
error[E0499]: cannot borrow `decoder` as mutable more than once at a time
  --> src/main.rs:15:29
   |
15 |     while let Some(frame) = decoder.read_next_frame().unwrap() {
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^ `decoder` was mutably borrowed here in the previous iteration of the loop
```

It looks like the error is pointing to the wrong spot in the code and is quite misleading.
Ideally the output should mention that `decoder` is still mutably borrowed because it holds a reference to `frame` between loops. Or something, im not actually sure :P

I have confirmed that this occurs in both the latest stable (1.62.1) and nightly (`1.64.0-nightly 4d6d601c8 2022-07-26`)

### PR DESCRIPTION
**Pull request by yanchen4791**
Fix #99824.

Problem of the issue:
If a borrow occurs in a loop, the borrowed reference could be invalidated at the same place at next iteration of the loop. When this happens, the point where the borrow occurs is the same as the intervening point that might invalidate the reference in the loop. This causes a problem for the current code finding the point where the resulting reference is used, so that the explanation of the cause will be missing. As the second point of "explain all errors in terms of three points" (see [leveraging intuition framing errors in terms of points"](https://rust-lang.github.io/rfcs/2094-nll.html#leveraging-intuition-framing-errors-in-terms-of-points), this explanation is very helpful for user to understand the error.

In the current implementation, the searching region for finding the location where the borrowed reference is used is limited to between the place where the borrow occurs and the place where the reference is invalidated. If those two places happen to be the same, which indicates that the borrow and invalidation occur at the same place in a loop, the search will fail.

One solution to the problem is when these two places are the same,  find the terminator of the loop, and then use the location of the loop terminator instead of the location of the borrow for the region to find the place where the borrowed reference is used.

### CODE REVIEW

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 1]
```diff
@@ -2236,6 +2236,38 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+        let scc = self.constraint_sccs.scc(r.to_region_vid());
+        let elements = self.scc_values.locations_outlived_by(scc).map(RegionElement::Location);
+        for element in elements {
+            match element {
+                RegionElement::Location(loc) => {
+                    let bb = &body[loc.block];
+                    match &bb.terminator {
+                        Some(terminator) => {
+                            match terminator.kind {
+                                // terminator of a loop should be TerminatorKind::FalseUnwind
```
Comment (chenyukang) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:2256]: Use `if let` will make these pattern match easier:

```rust
if let Some(terminator) = bb.terminator &&
   let TerminatorKind::FalseUnwind { .. } = terminator.kind {
   ... blah ...
  }
}
```

File: src/test/ui/borrowck/two-phase-across-loop.stderr [hunk 2]
```diff
@@ -2,7 +2,21 @@ error[E0499]: cannot borrow `foo` as mutable more than once at a time
...
+help: try adding a local storing this...
+  --> $DIR/two-phase-across-loop.rs:17:22
+   |
+LL |         strings.push(foo.get_string());
+   |                      ^^^^^^^^^^^^^^^^
+help: ...and then using that local here
+  --> $DIR/two-phase-across-loop.rs:17:9
+   |
+LL |         strings.push(foo.get_string());
+   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (chenyukang) [inline src/test/ui/borrowck/two-phase-across-loop.stderr:19]: Not quite understand this help message, seems a little bit confusing, it's suggesting to fix code like this?

```rust
 let x = foo.get_string().to_string();
 strings.push(x); 
```

But we can fix it like this:
```rust
 strings.push(foo.get_string().to_string()); 
```

File: src/test/ui/borrowck/two-phase-across-loop.stderr [hunk 3]
```diff
@@ -2,7 +2,21 @@ error[E0499]: cannot borrow `foo` as mutable more than once at a time
   --> $DIR/two-phase-across-loop.rs:17:22
    |
 LL |         strings.push(foo.get_string());
-   |                      ^^^^^^^^^^^^^^^^ `foo` was mutably borrowed here in the previous iteration of the loop
+   |         -------------^^^^^^^^^^^^^^^^-
+   |         |            |
+   |         |            `foo` was mutably borrowed here in the previous iteration of the loop
+   |         first borrow later used here
```
Comment (davidtwco) [inline src/test/ui/borrowck/two-phase-across-loop.stderr:8]: I think these labels could probably be special-cased for this case to provide a better diagnostic, something like:

```suggestion
   |         -------------^^^^^^^^^^^^^^^^-
   |         |            |
   |         |            `foo` is mutably borrowed here in a loop iteration..
   |         ..and that borrow lives into the next loop iteration, preventing another mutable borrow
```

But I'm not sure how well a label like that would work for every case that this changes.

File: src/test/ui/borrowck/two-phase-across-loop.stderr (hunk 2 above)
Comment (yanchen4791) [reply src/test/ui/borrowck/two-phase-across-loop.stderr]: Yes, this is bit confusing. Since this is a generic suggestion, not fit for this case. I have taken it out for the case.

File: src/test/ui/borrowck/two-phase-across-loop.stderr (hunk 3 above)
Comment (yanchen4791) [reply src/test/ui/borrowck/two-phase-across-loop.stderr]: Agreed. For preserving the wording for other cases and not changing too many code, I changed explanation part for this case using your suggested wording with a small modification 
```
 LL |         strings.push(foo.get_string());
-   |                      ^^^^^^^^^^^^^^^^ `foo` was mutably borrowed here in the previous iteration of the loop
+   |         -------------^^^^^^^^^^^^^^^^-
+   |         |            |
+   |         |            `foo` was mutably borrowed here in the previous iteration of the loop
+   |         that borrow lives into the next loop iteration, preventing another mutable borrow because the borrow later used here
```
Any comments?

File: src/test/ui/nll/closures-in-loops.stderr [hunk 4]
```diff
@@ -13,17 +13,21 @@ error[E0499]: cannot borrow `x` as mutable more than once at a time
...
    |
 LL |         v.push(|| x = String::new());
-   |                ^^ - borrows occur due to use of `x` in closure
-   |                |
-   |                `x` was mutably borrowed here in the previous iteration of the loop
+   |         -------^^-------------------
+   |         |      |  |
+   |         |      |  borrows occur due to use of `x` in closure
+   |         |      `x` was mutably borrowed here in the previous iteration of the loop
+   |         that borrow lives into the next loop iteration, preventing another mutable borrow because the borrow later used here
```
Comment (davidtwco) [inline src/test/ui/nll/closures-in-loops.stderr:20]: This isn't gramatically correct, it should be `preventing another mutable borrow because that borrow is later used here`

File: src/test/ui/borrowck/two-phase-across-loop.stderr (hunk 3 above)
Comment (davidtwco) [reply src/test/ui/borrowck/two-phase-across-loop.stderr]: I think you should feel free to thread some `IsInLoop::Yes`-type context into `explain_why_borrow_contains_point` so that you can adjust the message rather than adding to the string, since that's harder to do with diagnostic translation (#100717) anyway.

**Review by davidtwco — COMMENTED** [review]
A few more comments..

File: src/test/ui/borrowck/two-phase-across-loop.stderr (hunk 3 above)
Comment (yanchen4791) [reply src/test/ui/borrowck/two-phase-across-loop.stderr]: I found in the original code, `BorrowExplanation::UsedLaterInLoop` in `explain_why_borrow_contains_point` is never being used, since the function `is_use_in_later_iteration_of_loop` will never return `true`. I suspect that since we are using NLL now, this portion of the code is not being relevant anymore.
I modified the code by reusing `BorrowExplanation::UsedLaterInLoop` for the case, and removed 125 line of code which related to the unused `is_use_in_later_iteration_of_loop` function. This gives use more freedom to adjust the message for "used later in loop" case only and not affect other cases.

File: src/test/ui/nll/closures-in-loops.stderr (hunk 4 above)
Comment (yanchen4791) [reply src/test/ui/nll/closures-in-loops.stderr]: Corrected.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs [hunk 5]
```diff
@@ -1,8 +1,8 @@
 //! Print diagnostics to explain why values are borrowed.
 
-use std::collections::VecDeque;
+//use std::collections::VecDeque;
 
-use rustc_data_structures::fx::FxHashSet;
+//use rustc_data_structures::fx::FxHashSet;
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:5]: Can you remove the commented out code?

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs [hunk 6]
```diff
@@ -359,19 +359,38 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
 
-        match find_use::find(body, regioncx, tcx, region_sub, location) {
+        let mut use_location = location;
+        let mut use_in_later_iteration_of_loop = false;
+
+        if region_sub == borrow_region_vid {
+            // when region_sub is the same as borrow_region_vid, which means that the location where
+            // borrow issued is the same location that invalidates the reference, and this likely
+            // heppens in a loop iteration. Using the loop terminator location instead for 'location'
+            // to for find_sub_region_live_at(..)
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:372]:
```suggestion
            // When `region_sub` is the same as `borrow_region_vid` (the location where
            // the borrow is issued is the same location that invalidates the reference),
            // this is likely a loop iteration - in this case, try using the loop 
            // terminator location in `find_sub_region_live_at`.
```

You might need to fix the line wrapping.

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 7]
```diff
@@ -2236,6 +2236,29 @@ impl<'tcx> RegionInferenceContext<'tcx> {
     pub(crate) fn universe_info(&self, universe: ty::UniverseIndex) -> UniverseInfo<'tcx> {
         self.universe_causes[&universe].clone()
     }
+
+    /// Tries to find the terminator of the loop in which the region r resides.
```
Comment (davidtwco) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:2240]:
```suggestion
    /// Tries to find the terminator of the loop in which the region `r` resides.
```

File: src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.stderr [hunk 8]
```diff
@@ -25,7 +25,10 @@ error[E0499]: cannot borrow `x` as mutable more than once at a time
   --> $DIR/borrowck-mut-borrow-linear-errors.rs:12:30
    |
 LL |             _ => { addr.push(&mut x); }
-   |                              ^^^^^^ `x` was mutably borrowed here in the previous iteration of the loop
+   |                    ----------^^^^^^-
+   |                    |         |
+   |                    |         `x` was mutably borrowed here in the previous iteration of the loop
+   |                    that borrow lives into the next loop iteration, preventing another mutable borrow because that borrow is used here
```
Comment (davidtwco) [inline src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.stderr:31]:
```suggestion
   |                    that borrow lives into the next loop iteration, preventing another mutable borrow
```
I think the end of this label just increases verbosity and isn't more instructive.

**Review by davidtwco — CHANGES_REQUESTED** [review]
Some more changes, going to re-assign this to double-check it because it's been a while since I've worked on the borrow checker.

File: src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.stderr (hunk 8 above)
Comment (yanchen4791) [reply src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.stderr:31]: I think the use of the mutable borrow is reason of that borrow lives into the next iteration. If the borrow is not used, or is used only for read, there will be no problem at the next iteration. So I think that we need to point out that "that borrow is used here" is the reason of the real problem (the reference is used here so that it cannot be invalidated at next iteration), not because of the borrow over loop iteration. This can give the user more clear hint how to fix the error.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 7 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/region_infer/mod.rs]: Modified as suggested.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 6 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs]: Modified as suggested.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 5 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs]: Done.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 9]
```diff
@@ -911,6 +919,9 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
         issued_borrow: &BorrowData<'tcx>,
         explanation: BorrowExplanation<'tcx>,
     ) {
+        if matches!(explanation, BorrowExplanation::UsedLaterInLoop(..)) {
+            return;
+        }
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:924]: Isn't the test with `used_in_call` sufficient?

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs [hunk 10]
```diff
@@ -102,14 +99,14 @@ impl<'tcx> BorrowExplanation<'tcx> {
             BorrowExplanation::UsedLaterInLoop(later_use_kind, var_or_use_span, path_span) => {
                 let message = match later_use_kind {
                     LaterUseKind::TraitCapture => {
-                        "borrow captured here by trait object, in later iteration of loop"
+                        "borrow is captured here by trait object, in later iteration of loop"
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:102]: Adding a verb is inconsistent with the current phrasing of the messages in the previous branch.  I'd rather have this change in a specific PR, to ensure consistency there.

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 11]
```diff
@@ -2236,6 +2236,29 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+
+    /// Tries to find the terminator of the loop in which the region 'r' resides.
+    /// Returns the location of the terminator if found.
+    pub(crate) fn find_loop_terminator_location(
+        &self,
+        r: RegionVid,
+        body: &Body<'_>,
+    ) -> Option<Location> {
+        let scc = self.constraint_sccs.scc(r.to_region_vid());
+        let elements = self.scc_values.locations_outlived_by(scc).map(RegionElement::Location);
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:2248]: Why wrap in a `RegionElement::Location` to test it just below?

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 12]
```diff
@@ -2236,6 +2236,29 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+        for element in elements {
+            if let RegionElement::Location(loc) = element {
+                let bb = &body[loc.block];
+                if let Some(terminator) = &bb.terminator {
+                    // terminator of a loop should be TerminatorKind::FalseUnwind
+                    if let TerminatorKind::FalseUnwind { .. } = terminator.kind {
+                        return Some(Location { block: loc.block, statement_index: 0 });
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:2255]: Why not the terminator location?

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs [hunk 13]
```diff
@@ -359,19 +356,37 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
         debug!(?region_sub);
 
-        match find_use::find(body, regioncx, tcx, region_sub, location) {
+        let mut use_location = location;
+        let mut use_in_later_iteration_of_loop = false;
+
+        if region_sub == borrow_region_vid {
+            // When `region_sub` is the same as `borrow_region_vid` (the location where the borrow is
+            // issued is the same location that invalidates the reference), this is likely a loop iteration
+            // - in this case, try using the loop terminator location in `find_sub_region_live_at`.
```
Comment (cjgillot) [inline compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:368]: The code suggests that we can only have a loop iteration if `region_sub == borrow_region_vid`.  Could you explain this assumption?

**Review by cjgillot — COMMENTED** [review]
Thanks @yanchen4791.  The simplification looks good.  I have a few questions.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 13 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:368]: The assumption might be explained intuitively using the hypothetical logic of the following problem:
Given point `A`, find point `B` such that there is a path from point `A` to point `B`. If `B` equals `A`, the path is a cycle.

Likewise, consider the line in question:
```
let mut region_sub = self.regioncx.find_sub_region_live_at(borrow_region_vid, location);
```
based on the implementation of the function `find_sub_region_live_at`:
```
/// Finds some region R such that `fr1: R` and `R` is live at `elem`.
find_sub_region_live_at(&self, fr1: RegionVid, elem: Location) -> RegionVid
    self.find_constraint_paths_between_regions(fr1, |r| {
        // First look for some `r` such that `fr1: r` and `r` is live at `elem`
        self.liveness_constraints.contains(r, elem)
    })
    .map(|(_path, r)| r)
    .unwrap()
}
```
The function can be rephrased to the following problem:
Given region fr1 (`A`), find region R to which 'elem' belongs (`B`) so that there is a constraint path from region fr1 (`A`) to region R (`B`).  
If R (`B`) equals fr1 (`A`), then the constraint path is a loop.

Therefor, if region_sub (corresponding to `B`) equals to borrow_region_vid (corresponding to `A`), it is in a loop.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 12 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:2255]: Sure, just use loc with `return Some(loc);' will be simpler.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 10 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:102]: Sure.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 9 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:924]: This is for not providing user a suggestion how to fix the problem when UsedLaterInLoop case.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 11 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:2248]: Sure, loc can be used for returning the terminator location.

File: src/test/ui/nll/closures-in-loops.stderr [hunk 14]
```diff
@@ -13,17 +13,21 @@ error[E0499]: cannot borrow `x` as mutable more than once at a time
   --> $DIR/closures-in-loops.rs:13:16
    |
 LL |         v.push(|| x = String::new());
-   |                ^^ - borrows occur due to use of `x` in closure
-   |                |
-   |                `x` was mutably borrowed here in the previous iteration of the loop
+   |         -------^^-------------------
```
Comment (cjgillot) [inline src/test/ui/nll/closures-in-loops.stderr:16]: The spans are a bit unfortunate.  Is there anything to do here?

File: src/test/ui/nll/closures-in-loops.stderr [hunk 15]
```diff
@@ -13,17 +13,21 @@ error[E0499]: cannot borrow `x` as mutable more than once at a time
...
    |
 LL |         v.push(|| *x = String::new());
-   |                ^^ -- borrows occur due to use of `x` in closure
-   |                |
-   |                closures are constructed here in different iterations of loop
+   |         -------^^--------------------
+   |         |      |  |
+   |         |      |  borrows occur due to use of `x` in closure
+   |         |      closures are constructed here in different iterations of loop
+   |         that borrow lives into the next loop iteration, preventing another mutable borrow because that borrow is used here
```
Comment (cjgillot) [inline src/test/ui/nll/closures-in-loops.stderr:30]: I think the current message `borrow used here, in later iteration of loop` would be enough here, no need to change it.

File: compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs (hunk 13 above)
Comment (cjgillot) [reply compiler/rustc_borrowck/src/diagnostics/explain_borrow.rs:368]: Thanks for the explanation.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 9 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: Yes, it's redundant, removed.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 11 above)
Comment (yanchen4791) [reply compiler/rustc_borrowck/src/region_infer/mod.rs]: Got it, thanks. Removed.

File: src/test/ui/nll/closures-in-loops.stderr (hunk 15 above)
Comment (yanchen4791) [reply src/test/ui/nll/closures-in-loops.stderr]: Sure.

File: src/test/ui/nll/closures-in-loops.stderr (hunk 14 above)
Comment (yanchen4791) [reply src/test/ui/nll/closures-in-loops.stderr:16]: You mean the format of using "-------^^-------------------" is not clear?

Comment (cjgillot) [reply src/test/ui/nll/closures-in-loops.stderr:16]: I just realised: the longer `---` is meant to point to `loop_terminator_location`.  It should point to some `}` below, shouldn't it?

**Comment by yanchen4791** [comment]
@cjgillot Any other comments?

**Comment by cjgillot** [comment]
Sorry for the wait @yanchen4791. It took me a bit of time to understand why this PR was doing the right thing.
@bors r+
