### PR TITLE
Emit a single error when importing a path with `_`

### LINKED ISSUE #142662: Leading underscore in path makes rust suggest to add a crate named `_` with edition >= 2018
### Code

```Rust
use _::a;
use _::*;

fn main() {
    use _::a;
    use _::*;
}
```

### Current output

```Shell
⣿
Errors

Exited with status 101

Standard Error

   Compiling playground v0.0.1 (/playground)
error: expected identifier, found reserved identifier `_`
 --> src/main.rs:1:5
  |
1 | use _::a;
  |     ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:2:5
  |
2 | use _::*;
  |     ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:5:9
  |
5 |     use _::a;
  |         ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:6:9
  |
6 |     use _::*;
  |         ^ expected identifier, found reserved identifier

error[E0432]: unresolved import `_`
 --> src/main.rs:2:5
  |
2 | use _::*;
  |     ^ use of unresolved module or unlinked crate `_`
  |
  = help: if you wanted to use a crate named `_`, use `cargo add _` to add it to your `Cargo.toml`

error[E0432]: unresolved import `_`
 --> src/main.rs:1:5
  |
1 | use _::a;
  |     ^ use of unresolved module or unlinked crate `_`
  |
  = help: if you wanted to use a crate named `_`, use `cargo add _` to add it to your `Cargo.toml`

error[E0432]: unresolved import `_`
 --> src/main.rs:5:9
  |
5 |     use _::a;
  |         ^ use of unresolved module or unlinked crate `_`
  |
  = help: if you wanted to use a crate named `_`, use `cargo add _` to add it to your `Cargo.toml`

error[E0432]: unresolved import `_`
 --> src/main.rs:6:9
  |
6 |     use _::*;
  |         ^ use of unresolved module or unlinked crate `_`
  |
  = help: if you wanted to use a crate named `_`, use `cargo add _` to add it to your `Cargo.toml`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `playground` (bin "playground") due to 8 previous errors

Standard Output
```

### Desired output

```Shell
⣿
Errors

Exited with status 101

Standard Error

   Compiling playground v0.0.1 (/playground)
error: expected identifier, found reserved identifier `_`
 --> src/main.rs:1:5
  |
1 | use _::a;
  |     ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:2:5
  |
2 | use _::*;
  |     ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:5:9
  |
5 |     use _::a;
  |         ^ expected identifier, found reserved identifier

error: expected identifier, found reserved identifier `_`
 --> src/main.rs:6:9
  |
6 |     use _::*;
  |         ^ expected identifier, found reserved identifier

For more information about this error, try `rustc --explain E0432`.
error: could not compile `playground` (bin "playground") due to 8 previous errors

Standard Output
```

### Rationale and extra context

crates cannot be named `_` in Rust. Note this only happens with edition 2018 and beyond.

This was discovered by the ferrocene team while running the test suite with edition 2018, specifically with the test `tests/ui/underscore-imports/issue-110164.rs` output changing and showing this regression.

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.87.0 (17067e9ac 2025-05-09)
binary: rustc
commit-hash: 17067e9ac6d7ecb70e50f92c1944e545188d2359
commit-date: 2025-05-09
host: x86_64-unknown-linux-gnu
release: 1.87.0
LLVM version: 20.1.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When encountering `use _;`, `use _::*'` or similar, do not emit two errors for that single mistake. This also side-steps the issue of resolve errors suggesting adding a crate named `_` to `Cargo.toml`.

Fix rust-lang/rust#142662.

### CODE REVIEW

File: compiler/rustc_resolve/src/imports.rs [hunk 1]
```diff
@@ -711,6 +711,12 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
 
         let mut diag = struct_span_code_err!(self.dcx(), span, E0432, "{msg}");
 
+        if errors.iter().all(|(_, err)| err.segment == Some(kw::Underscore)) {
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/imports.rs]: This leads to inconsistent behavior in code like `use {_, a}`. I'd rather we filter out the errors mentioning `_` like we're doing with that `errors.retain` call above.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_resolve/src/imports.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_resolve/src/imports.rs]: And while we're at it, we probably should delay a bug in the:

```
if errors.is_empty() {
    return;
}
```

on 691.

File: tests/ui/underscore-imports/issue-110164.rs
Comment (Kivooeo) [inline tests/ui/underscore-imports/issue-110164.rs:1]: Since this pr touches this test, could we also rename it with some more descriptive name and put a small comment with a link on an issue related to this instead?

File: compiler/rustc_resolve/src/imports.rs [hunk 2]
```diff
@@ -683,38 +685,50 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
             // Skip `use` errors for `use foo::Bar;` if `foo.rs` has unrecovered parse errors.
             Some(def_id) if self.mods_with_parse_errors.contains(&def_id) => false,
-            _ => true,
+            // If we've encountered something like `use _;`, we've already emitted an error stating
+            // that `_` is not a valid identifier, so we silence the resolve error.
+            _ => err.segment != Some(kw::Underscore),
         });
+
         if errors.is_empty() {
+            struct_span_code_err!(self.dcx(), span, E0432, "{msg}").delay_as_bug();
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/imports.rs]: Please revert that `let span_and_message` and just emit a span bug with no span and a generic error message; it should never be seen by users, after all.  It just needs to exist to make sure we're not accidentally filtering out a resolver error that should have been reported.

Comment (compiler-errors) [reply compiler/rustc_resolve/src/imports.rs]: Also, no need to use `struct_span_code_err!` macro, just use `dcx().delayed_bug`.

File: compiler/rustc_resolve/src/imports.rs [hunk 3]
```diff
@@ -683,38 +685,50 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
...
+
+        let (span, msg) = span_and_message(&errors);
+
         errors.retain(|(_import, err)| match err.module {
             // Skip `use` errors for `use foo::Bar;` if `foo.rs` has unrecovered parse errors.
             Some(def_id) if self.mods_with_parse_errors.contains(&def_id) => false,
-            _ => true,
+            // If we've encountered something like `use _;`, we've already emitted an error stating
+            // that `_` is not a valid identifier, so we silence the resolve error.
+            _ => err.segment != Some(kw::Underscore),
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/imports.rs]: Could you split this out into two `retain` calls? This is on the error path after all, and I think it's easier to understand since these two match arms have nothing to do with each other.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_resolve/src/imports.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_resolve/src/imports.rs]: I've encountered delayed bugs in the past where not having any additional info beyond the fact that a bug occurred made things harder to debug, so I added that additional context, but can change it.

Comment (compiler-errors) [reply compiler/rustc_resolve/src/imports.rs]: I'd prefer if you remove it. I think that the extra logic you added to compute the message is pretty confusing to parse, and hopefully unnecessary.

File: compiler/rustc_resolve/src/imports.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_resolve/src/imports.rs]: ping

**Comment by compiler-errors** [comment]
Please add a test for the case that I asked for:

> This leads to inconsistent behavior in code like `use {_, a}`. I'd rather we filter out the errors mentioning `_` like we're doing with that errors.retain call above.

File: compiler/rustc_resolve/src/imports.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_resolve/src/imports.rs]: Ah, you meant two retain calls, not two branches in the same match, gotcha
