### PR TITLE
Some more pattern cleanup and bugfixing

### LINKED ISSUE #22933: Compiler panic: "Path not fully resolved" when passing reference to impl function
I'm getting a compiler error about a "path not fully resolved":

    thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: 204 }, false), last_private: LastMod(AllPublic), depth: 1 }'

I tried this code:

    fn is_whitespace(c: char) -> bool {
        c == ' ' || c == '\n'
    }

    fn consume_whitespace(&mut self) -> Parse<()> {
        //Ok(())
        self.consume_while(&(CNFParser::is_whitespace))
    }

    fn consume_while(&mut self, p: &Fn(char) -> bool) -> Parse<()> {
        while p(self.token) {
            let take = self.take();
            if take.is_err() { return take }
        }
        Ok(())
    }    

I expected to see this happen:
the code should compile, it did somewhere after 1.0 alpha and stopped in the last week (I think)

Instead, this happened:
I got this unexpected panic. It has something to do with passing the reference to `CNFParser::is_whitespace`

## Meta

`rustc --version --verbose`:

```
    rustc 1.0.0-nightly (890293655 2015-02-28) (built 2015-03-01)
    binary: rustc
    commit-hash: 890293655251c372ea99694c0c9f0795e2663286
    commit-date: 2015-02-28
    build-date: 2015-03-01
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly
```

Backtrace:
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: 204 }, false), last_private: LastMod(AllPublic), depth: 1 }', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/def.rs:79

stack backtrace:
   1:         0xde628c4f - sys::backtrace::write::hb08af03691eab78a5kA
   2:         0xde651782 - panicking::on_panic::h37164609ca1c02afBnJ
   3:         0xde59163a - rt::unwind::begin_unwind_inner::h24d5e7492198457b43I
   4:         0xde591d24 - rt::unwind::begin_unwind_fmt::hee1a09c48e390d87H2I
   5:         0xdc4856b1 - middle::ty::resolve_expr::h65338d27a12ebb460A6
   6:         0xdc5eac40 - middle::ty::expr_kind::hcac269a238fc506fAC6
   7:         0xdc5eaf7b - middle::ty::expr_kind::hcac269a238fc506fAC6
   8:         0xdc5ea94a - middle::ty::expr_is_lval::h485f36669a19d1a13B6
   9:         0xdd3bee84 - check::check_expr_with_unifier::h329803007416623423
  10:         0xdd3983a8 - check::check_argument_types::h6d28a2012d7e49afNsp
  11:         0xdd399d34 - check::check_method_argument_types::hf1decc93718710207pp
  12:         0xdd3cc071 - check::check_expr_with_unifier::check_method_call::hb126ebcd08adeb94z4p
  13:         0xdd3d6ae2 - check::check_expr_with_unifier::h8581770403589055324
  14:         0xdd3ad396 - check::check_block_with_expected::haa14a0695c08d2a6V0r
  15:         0xdd3908d5 - check::check_fn::ha741703a74959edd8kn
  16:         0xdd3aa0d2 - check::check_bare_fn::hdc3a9af5b372582fOan
  17:         0xdd3adbbb - check::check_method_body::h49a550c880bfd87dnIn
  18:         0xdd3a3864 - check::check_item::h203d9fc30afbd381stn
  19:         0xdd3a85c2 - visit::walk_item::h11360223606861997271
  20:         0xdd46df2e - check_crate::closure.35032
  21:         0xdd469207 - check_crate::h6ce4a57b1730f0fdDXB
  22:         0xdeca908e - driver::phase_3_run_analysis_passes::h55e7e7af941f4089xFa
  23:         0xdec8e411 - driver::compile_input::hee81c045ab46c74fIba
  24:         0xded58e6e - run_compiler::h875c1e123fe4ae2cF5b
  25:         0xded56a1c - thunk::F.Invoke<A, R>::invoke::h12424714292252424185
  26:         0xded55770 - rt::unwind::try::try_fn::h4021821266450575721
  27:         0xde6bcfe8 - rust_try_inner
  28:         0xde6bcfd5 - rust_try
  29:         0xded55e5c - thunk::F.Invoke<A, R>::invoke::h8199562432922027576
  30:         0xde63d2d5 - sys::thread::thread_start::h1b1bb1e7ac08d3a6yRE
  31:         0xd8378373 - start_thread
  32:         0xde21927c - __clone
  33:         0xffffffff - <unknown>
```

### LINKED ISSUE #34209: Internal compiler error when matching non-existant enum case (PathResolution)
Compiling the following program yields an internal compiler error:
```
enum S {
    A,
}

fn bug(l: S) {
    match l {
        S::B{ } => { },
    }
}

fn main () {}
```

```
$ rustc --version
rustc 1.11.0-nightly (7d2f75a95 2016-06-09)
$ rustc bug.rs
error: internal compiler error: ../src/librustc/hir/def.rs:77: path not fully resolved: PathResolution { base_def: Enum(DefId { krate: 0, node: DefIndex(4) => S }), depth: 1 }
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:584
stack backtrace:
   1:     0x7fe96e1cc62f - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7fe96e1da26b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7fe96e1d9e08 - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7fe96e1a016e - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x7fe96938d887 - std::panicking::begin_panic::hf9f206df23a555af
   6:     0x7fe96938d1ee - syntax::errors::Handler::bug::hd25802f012f6858b
   7:     0x7fe96a5b0134 - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::h083e19915ee66466
   8:     0x7fe96a5aff3d - rustc::session::opt_span_bug_fmt::h157ddeb5b4622d22
   9:     0x7fe96a5ca8b6 - rustc::session::bug_fmt::h166f9667daf4dd54
  10:     0x7fe96a5afdaf - rustc::ty::_<impl rustc..ty..context..TyCtxt<'a, 'gcx, 'tcx>>::expect_def::h1bba3da31e27b082
  11:     0x7fe96cd4c2a4 - rustc_typeck::check::_match::_<impl rustc_typeck..check..FnCtxt<'a, 'gcx, 'tcx>>::check_pat_struct::hb2aac908ea2f3898
  12:     0x7fe96ccebad2 - rustc_typeck::check::_match::_<impl rustc_typeck..check..FnCtxt<'a, 'gcx, 'tcx>>::check_pat::hb68aedceeb2eae7b
  13:     0x7fe96cd36ec2 - rustc_typeck::check::_match::_<impl rustc_typeck..check..FnCtxt<'a, 'gcx, 'tcx>>::check_match::he1e7f5ae9b0c3187
  14:     0x7fe96cd126cf - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::hc65ba746f75e2d76
  15:     0x7fe96ccedc3d - rustc_typeck::check::FnCtxt::check_block_with_expected::h66a8dcc154a53b83
  16:     0x7fe96cce4d7e - rustc_typeck::check::check_fn::h74a0e95f02904d77
  17:     0x7fe96cce1e6e - rustc_typeck::check::check_bare_fn::h7683dfd1c7fc31d1
  18:     0x7fe96ccdd5c2 - rustc_typeck::check::check_item_body::h33cafe2320cee00a
  19:     0x7fe96ccd50ce - rustc_typeck::check::check_item_bodies::h0649c58896094a63
  20:     0x7fe96cccaec6 - rustc_typeck::check_crate::h9ad81a238efa1992
  21:     0x7fe96e6ff7cc - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hd565ad56c5876a16
  22:     0x7fe96e6fd8b9 - rustc::ty::context::TyCtxt::create_and_enter::habef58c7230d34f9
  23:     0x7fe96e6c7d7f - rustc_driver::driver::compile_input::hfd60b020f6d0208d
  24:     0x7fe96e6b3cc4 - rustc_driver::run_compiler::h884d01d12eb76bbb
  25:     0x7fe96e6b0d9e - std::panicking::try::call::hd72cf79141f67e60
  26:     0x7fe96e1e872b - __rust_try
  27:     0x7fe96e1e86ce - __rust_maybe_catch_panic
  28:     0x7fe96e6b1884 - _<F as alloc..boxed..FnBox<A>>::call_box::h589d2091babf223a
  29:     0x7fe96e1d8394 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  30:     0x7fe965b1f473 - start_thread
  31:     0x7fe96de2769c - clone
  32:                0x0 - <unknown>

return code: 101
```

### PR DESCRIPTION
**Pull request by petrochenkov**
The next part of https://github.com/rust-lang/rust/pull/34095

The most significant fixed mistake is definitions for partially resolved associated types not being updated after full resolution.

```
fn f<T: Fn()>(arg: T::Output) { .... } // <- the definition of T::Output was not updated in def_map
```

For this reason unstable associated types of stable traits, like `FnOnce::Output`, could be used in stable code when written in unqualified form. Now they are properly checked, this is a **[breaking-change]** (pretty minor one, but a crater run would be nice). The fix is not to use unstable library features in stable code, alternatively `FnOnce::Output` can be stabilized.

Besides that, paths in struct patterns and expressions `S::A { .. }` are now fully resolved as associated types. Such types cannot be identified as structs at the moment, i.e. the change doesn't make previously invalid code valid, but it improves error diagnostics.

Other changes: `Def::Err` is supported better (less chances for ICEs for erroneous code), some incorrect error messages are corrected, some duplicated error messages are not reported, ADT definitions are now available through constructor IDs, everything else is cleanup and code audit.

Fixes https://github.com/rust-lang/rust/issues/34209
Closes https://github.com/rust-lang/rust/issues/22933 (adds tests)

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
cc @nrc @nikomatsakis

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -1039,15 +1039,17 @@ fn convert_struct_def<'a, 'tcx>(ccx: &CrateCtxt<'a, 'tcx>,
...
-    ccx.tcx.intern_adt_def(did, ty::AdtKind::Struct,
-        vec![convert_struct_variant(ccx, ctor_id, it.name, ConstInt::Infer(0), def)])
+    // Use separate constructor id for unit/tuple structs and reuse did for braced structs.
+    let ctor_id = if !def.is_struct() { Some(ccx.tcx.map.local_def_id(def.id())) } else { None };
+    let variants = vec![convert_struct_variant(ccx, ctor_id.unwrap_or(did), it.name,
+                                               ConstInt::Infer(0), def)];
+    let adt = ccx.tcx.intern_adt_def(did, ty::AdtKind::Struct, variants);
+    if let Some(ctor_id) = ctor_id {
+        // Make adt definition available through constructor id as well.
+        ccx.tcx.insert_adt_def(ctor_id, adt);
```
Comment (eddyb) [inline src/librustc_typeck/collect.rs]: Why was this done?

Comment (petrochenkov) [inline src/librustc_typeck/collect.rs]: So you can go directly from `Def::Struct` to ADT definition regardless of where this `Def::Struct` is used - in a pattern, expression or a type. Sometimes `Def::Struct` denotes a type and sometimes a constructor and previously `lookup_adt_def` worked only with `Def::Struct` in type context and panicked otherwise, so workarounds had to be used.

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -1619,62 +1619,32 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
-        if variant.kind == ty::VariantKind::Struct ||
-           variant.kind == ty::VariantKind::Unit {
-            Some((adt, variant))
-        } else {
-            None
-        }
+        let ty_substituted = self.instantiate_type_scheme(path.span, substs, &type_scheme.ty);
+        self.write_ty(node_id, ty_substituted);
+        self.write_substs(node_id, ty::ItemSubsts {
+            substs: substs
```
Comment (petrochenkov) [inline src/librustc_typeck/check/mod.rs]: Hm, this is probably a mistake and regression. The substs written are substs before `instantiate_type_scheme`, not after.
I.e. for
```
type Alias<T> = S<T, u16>;
// Inside match
Alias::<u8> { .. }
```
only `u8` is written, not `[u8, u16]`.
However, `instantiate_path` does the same mistake(?) even without this PR.

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -1619,64 +1619,32 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
-            Some((adt, variant))
-        } else if var_kind == ty::VariantKind::Unit {
-             Some((adt, variant))
-         } else {
-             None
-         }
+        let ty_substituted = self.instantiate_type_scheme(path.span, substs, &type_scheme.ty);
+        self.write_ty(node_id, ty_substituted);
+        self.write_substs(node_id, ty::ItemSubsts {
+            substs: substs
```
Comment (petrochenkov) [inline src/librustc_typeck/check/mod.rs]: Hm, this is probably a mistake and regression. The substs written are substs before `instantiate_type_scheme`, not after.
I.e. for
```
type Alias<T> = S<T, u16>;
// Inside match
Alias::<u8> { .. }
```
only `u8` is written, not `[u8, u16]`.
However, `instantiate_path` does the same mistake(?) even without this PR.

**Comment by petrochenkov** [comment]
Rebased.
Still waiting for crater run.

**Comment by eddyb** [comment]
@petrochenkov Sorry about that, @nikomatsakis is on vacation.
But I have crater access now, so here's the [crater report](https://gist.github.com/eddyb/1f603bafd1d3f28556f85ed3958db1e1).
The two actual root regressions are in [traverse](https://tools.taskcluster.net/task-inspector/#_73QPoxmQwehczTnHYY2lw/0) and [parsell](https://tools.taskcluster.net/task-inspector/#xkdndKP2SH24-Wt0HLwhbA/0), both using `FnOnce::Output`.

**Comment by nikomatsakis** [comment]
So as I wrote on IRC, I don't think that `F::Output` (where `F: FnOnce`) has to be unstable -- and I'm not sure it was intended to be, though I'll have to check around. What we wanted to be careful about was something like `F: FnOnce<()>`, because this reveals the form of the "input types", and there was some concern that `F: FnOnce<(A,B)>` might change to `F: FnOnce<A,B>` or something, depending on what approach we wound up with for variadic generics. But I think we know that the return type will always be an associated type, and I see no reason we would ever change its name.

**Comment by aturon** [comment]
> But I think we know that the return type will always be an associated type, and I see no reason we would ever change its name.

I agree on both counts. It seems OK for this name to be available on stable Rust.

**Comment by aturon** [comment]
Lang team meeting: we decided we should try this PR, but with marking the `Output` type as `stable`, and see whether that eliminates the regressions.

**Comment by eddyb** [comment]
@petrochenkov Looks like [`FnOnce::Output`](https://github.com/rust-lang/rust/blob/4cf97fe57ef52c4addc03086aae784d980780d8f/src/libcore/ops.rs#L1932) is explicitly marked unstable so *just* flipping that should work. This is likely what @nikomatsakis had in mind.

**Comment by petrochenkov** [comment]
Rebased, `FnOnce::Output` is stabilized.

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/df917f7a525d5357a3be635d43a560e2) only shows 4 regressions in code using the unstable `librustc` APIs.

@alexcrichton @aturon Can we merge this with the stabilization of `FnOnce::Output` directly?

**Comment by aturon** [comment]
@eddyb Yep, at this point everybody's signed off on that step.
