### PR TITLE
Fix overflow in error emitter

### LINKED ISSUE #94171: ICE: "attempt to add with overflow" in error emitter when building clippy_utils lib
code is from clippy: `./src/tools/clippy/clippy_utils/src/lib.rs`
:warning:  you need rustc build with debug assertions :warning: 

### Meta

`rustc --version --verbose`:
```
b8c56fa8c30821129b0960180f528d4a1a4f9316
```

### Error output
`rustc ./src/tools/clippy/clippy_utils/src/lib.rs --crate-type lib -Wsingle-use-lifetimes`
```
.....
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:1081:6
     |
1081 | impl<'tcx> Visitor<'tcx> for ContainsName {
     |      ^^^^          ---- ...is used only here
     |      |
     |      this lifetime...

warning: lifetime parameter `'tcx` only used once
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:1616:23
     |
1616 | pub fn match_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId, syms: &[&str]) -> bool {
     |                       ^^^^ this lifetime...  ---- ...is used only here

warning: lifetime parameter `'tcx` only used once
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:2103:25
     |
2103 | fn with_test_item_names<'tcx>(tcx: TyCtxt<'tcx>, module: LocalDefId, f: impl Fn(&[Symbol]) -> bool) -> bool {
     |                         ^^^^              ---- ...is used only here
     |                         |
     |                         this lifetime...
     |
thread 'rustc' panicked at 'attempt to add with overflow', compiler/rustc_errors/src/emitter.rs:1728:25
stack backtrace:
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: lifetime parameter `'tcx` only used once
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:1081:6
     |
1081 | impl<'tcx> Visitor<'tcx> for ContainsName {
     |      ^^^^          ---- ...is used only here
     |      |
     |      this lifetime...

warning: lifetime parameter `'tcx` only used once
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:1616:23
     |
1616 | pub fn match_def_path<'tcx>(cx: &LateContext<'tcx>, did: DefId, syms: &[&str]) -> bool {
     |                       ^^^^ this lifetime...  ---- ...is used only here

warning: lifetime parameter `'tcx` only used once
    --> ./src/tools/clippy/clippy_utils/src/lib.rs:2103:25
     |
2103 | fn with_test_item_names<'tcx>(tcx: TyCtxt<'tcx>, module: LocalDefId, f: impl Fn(&[Symbol]) -> bool) -> bool {
     |                         ^^^^              ---- ...is used only here
     |                         |
     |                         this lifetime...
     |
thread 'rustc' panicked at 'attempt to add with overflow', compiler/rustc_errors/src/emitter.rs:1728:25
stack backtrace:
   0:     0x7fb7431aa3df - std::backtrace_rs::backtrace::libunwind::trace::h913912a04742634a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb7431aa3df - std::backtrace_rs::backtrace::trace_unsynchronized::hba81e1c01b02595d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb7431aa3df - std::sys_common::backtrace::_print_fmt::h4cd35453e855ed5b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb7431aa3df - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b1eb54ecb507b6b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb74325870e - core::fmt::write::h804d2b24173a7413
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fb7431d7b0f - std::io::Write::write_fmt::h4fbd6cffee6ce721
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1657:15
   6:     0x7fb7431aa20b - std::sys_common::backtrace::_print::h6dc864c7772bebae
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb7431aa20b - std::sys_common::backtrace::print::h8df49d2ca55329c7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb743190334 - std::panicking::default_hook::{{closure}}::h32873a067c6a5b7e
   9:     0x7fb74318fefe - std::panicking::default_hook::h0eff11b253e72033
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:314:9
  10:     0x7fb746e6054a - <alloc[687cd566c0cfd4ba]::boxed::Box<dyn for<'a, 'b> core[54fe93355658fbe8]::ops::function::Fn<(&'a core[54fe93355658fbe8]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[54fe93355658fbe8]::marker::Send + core[54fe93355658fbe8]::marker::Sync> as core[54fe93355658fbe8]::ops::function::Fn<(&core[54fe93355658fbe8]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1868:9
  11:     0x7fb746e6054a - rustc_driver[aa71810babc01d8e]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver/src/lib.rs:1153:13
  12:     0x7fb7431909d0 - std::panicking::rust_panic_with_hook::h2c545b2a73afb1b7
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:702:17
  13:     0x7fb7431aa999 - std::panicking::begin_panic_handler::{{closure}}::h0a54097f79f25177
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:586:13
  14:     0x7fb7431aa504 - std::sys_common::backtrace::__rust_end_short_backtrace::hb04ef19ffcce15ab
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7fb7431905a2 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:584:5
  16:     0x7fb74324c713 - core::panicking::panic_fmt::h6da8f1caaf923cda
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:143:14
  17:     0x7fb74324c5dd - core::panicking::panic::h7e30c2d4a02618a3
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:48:5
  18:     0x7fb74cf36c46 - <rustc_errors[4ddc4d29baec38b8]::emitter::EmitterWriter>::emit_suggestion_default
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:1728:25
  19:     0x7fb74cf36c46 - <rustc_errors[4ddc4d29baec38b8]::emitter::EmitterWriter>::emit_messages_default
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:1892:29
  20:     0x7fb74cf2ccf4 - <rustc_errors[4ddc4d29baec38b8]::emitter::EmitterWriter as rustc_errors[4ddc4d29baec38b8]::emitter::Emitter>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:508:9
  21:     0x7fb74cf53ebc - <rustc_errors[4ddc4d29baec38b8]::HandlerInner>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:978:13
  22:     0x7fb74cf15487 - <rustc_errors[4ddc4d29baec38b8]::Handler>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:899:9
  23:     0x7fb74cf15487 - <rustc_errors[4ddc4d29baec38b8]::diagnostic_builder::DiagnosticBuilder>::emit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic_builder.rs:98:9
  24:     0x7fb74a8b7646 - <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::check_uses_for_lifetimes_defined_by_scope::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:2083:33
  25:     0x7fb74a8b7646 - <<rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::check_uses_for_lifetimes_defined_by_scope::{closure#2} as core[54fe93355658fbe8]::ops::function::FnOnce<(rustc_middle[6c01273334a4e0ad]::lint::LintDiagnosticBuilder,)>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:227:5
  26:     0x7fb74cc84d18 - <alloc[687cd566c0cfd4ba]::boxed::Box<dyn for<'a> core[54fe93355658fbe8]::ops::function::FnOnce<(rustc_middle[6c01273334a4e0ad]::lint::LintDiagnosticBuilder<'a>,), Output = ()>> as core[54fe93355658fbe8]::ops::function::FnOnce<(rustc_middle[6c01273334a4e0ad]::lint::LintDiagnosticBuilder,)>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1854:9
  27:     0x7fb74cc84d18 - rustc_middle[6c01273334a4e0ad]::lint::struct_lint_level::struct_lint_level_impl
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:381:9
  28:     0x7fb74a93a796 - rustc_middle[6c01273334a4e0ad]::lint::struct_lint_level::<<rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::check_uses_for_lifetimes_defined_by_scope::{closure#2}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/lint.rs:383:5
  29:     0x7fb74a93a796 - <rustc_middle[6c01273334a4e0ad]::ty::context::TyCtxt>::struct_span_lint_hir::<rustc_span[c11b030d3e5eb8ab]::span_encoding::Span, <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::check_uses_for_lifetimes_defined_by_scope::{closure#2}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:2760:9
  30:     0x7fb74a96d995 - <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::check_uses_for_lifetimes_defined_by_scope
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:2064:25
  31:     0x7fb74a961c63 - <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::with::<<rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::visit_early_late<<rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext as rustc_hir[80600f8cf2fd79ed]::intravisit::Visitor>::visit_item::{closure#0}>::{closure#3}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:1838:17
  32:     0x7fb74a961c63 - <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext>::visit_early_late::<<rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext as rustc_hir[80600f8cf2fd79ed]::intravisit::Visitor>::visit_item::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:2230:9
  33:     0x7fb74a961c63 - <rustc_resolve[2ec8de997ffb204d]::late::lifetimes::LifetimeContext as rustc_hir[80600f8cf2fd79ed]::intravisit::Visitor>::visit_item
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:732:17
  34:     0x7fb74a95e0bd - rustc_resolve[2ec8de997ffb204d]::late::lifetimes::do_resolve
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:465:5
  35:     0x7fb74a97d533 - rustc_resolve[2ec8de997ffb204d]::late::lifetimes::resolve_lifetimes
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:437:30
  36:     0x7fb74b938932 - <rustc_query_system[eed0fda852e3a6e5]::query::config::QueryVtable<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/config.rs:43:9
  37:     0x7fb74b938932 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:415:55
  38:     0x7fb74b938932 - stacker[480059cd772f137f]::maybe_grow::<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  39:     0x7fb74b938932 - rustc_data_structures[261e35101f56a30d]::stack::ensure_sufficient_stack::<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:16:5
  40:     0x7fb74b61d9da - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:113:17
  41:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:50
  42:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::set_tlv::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1794:9
  43:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:9
  44:     0x7fb74b61d9da - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:13
  45:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1854:13
  46:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1838:40
  47:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context_opt::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1827:22
  48:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1838:9
  49:     0x7fb74b61d9da - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1851:9
  50:     0x7fb74b61d9da - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:101:9
  51:     0x7fb74b61d9da - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:415:22
  52:     0x7fb74b61d9da - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::try_execute_query::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_query_system[eed0fda852e3a6e5]::query::caches::ArenaCache<rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, rustc_middle[6c01273334a4e0ad]::middle::resolve_lifetime::ResolveLifetimes>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:373:44
  53:     0x7fb74b7346c7 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::get_query::<rustc_query_impl[f86e27b60e1fe7a7]::queries::resolve_lifetimes, rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:738:36
  54:     0x7fb74a95ea04 - rustc_resolve[2ec8de997ffb204d]::late::lifetimes::resolve_lifetimes_for
  55:     0x7fb74a95ebf8 - rustc_resolve[2ec8de997ffb204d]::late::lifetimes::is_late_bound_map
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/late/lifetimes.rs:558:14
  56:     0x7fb74b648cb3 - <rustc_query_system[eed0fda852e3a6e5]::query::config::QueryVtable<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/config.rs:43:9
  57:     0x7fb74b648cb3 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:415:55
  58:     0x7fb74b648cb3 - stacker[480059cd772f137f]::maybe_grow::<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  59:     0x7fb74b648cb3 - rustc_data_structures[261e35101f56a30d]::stack::ensure_sufficient_stack::<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:16:5
  60:     0x7fb74b648cb3 - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:113:17
  61:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:50
  62:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::set_tlv::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1794:9
  63:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:9
  64:     0x7fb74b648cb3 - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:13
  65:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1854:13
  66:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1838:40
  67:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context_opt::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1827:22
  68:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1838:9
  69:     0x7fb74b648cb3 - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>::{closure#0}, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1851:9
  70:     0x7fb74b648cb3 - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:101:9
  71:     0x7fb74b648cb3 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:415:22
  72:     0x7fb74b648cb3 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::try_execute_query::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_query_system[eed0fda852e3a6e5]::query::caches::DefaultCache<rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, core[54fe93355658fbe8]::option::Option<(rustc_span[c11b030d3e5eb8ab]::def_id::LocalDefId, &std[4f6852ddc6f39c7c]::collections::hash::set::HashSet<rustc_hir[80600f8cf2fd79ed]::hir_id::ItemLocalId, core[54fe93355658fbe8]::hash::BuildHasherDefault<rustc_hash[7c48cf2c7e7fed0d]::FxHasher>>)>>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:373:44
  73:     0x7fb74b733f00 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::get_query::<rustc_query_impl[f86e27b60e1fe7a7]::queries::is_late_bound_map, rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:738:36
  74:     0x7fb74cd46722 - <rustc_middle[6c01273334a4e0ad]::ty::query::TyCtxtAt>::is_late_bound_map
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:259:17
  75:     0x7fb74cd46722 - <rustc_middle[6c01273334a4e0ad]::ty::context::TyCtxt>::is_late_bound_map
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:240:17
  76:     0x7fb74cd46722 - <rustc_middle[6c01273334a4e0ad]::ty::context::TyCtxt>::is_late_bound
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:2785:9
  77:     0x7fb74a4b3ac5 - rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_typeck/src/collect.rs:2045:47
  78:     0x7fb74a4b3ac5 - <&mut rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0} as core[54fe93355658fbe8]::ops::function::FnMut<(&&rustc_hir[80600f8cf2fd79ed]::hir::GenericParam,)>>::call_mut
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:269:13
  79:     0x7fb74a4b3ac5 - <core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::find::<&mut rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/slice/iter/macros.rs:259:24
  80:     0x7fb74a4b3ac5 - <core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::next
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/filter.rs:56:9
  81:     0x7fb74a4b3ac5 - <core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::next
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/enumerate.rs:46:17
  82:     0x7fb74a4b3ac5 - <core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>>, rustc_typeck[ad352206ed2ad8b]::collect::generics_of::{closure#2}> as core[54fe93355658fbe8]::iter::traits::iterator::Iterator>::next
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/iter/adapters/map.rs:103:9
  83:     0x7fb74a4b3ac5 - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_middle[6c01273334a4e0ad]::ty::generics::GenericParamDef>>::extend_desugared::<core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>>, rustc_typeck[ad352206ed2ad8b]::collect::generics_of::{closure#2}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/mod.rs:2644:35
  84:     0x7fb74a4b3ac5 - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_middle[6c01273334a4e0ad]::ty::generics::GenericParamDef> as alloc[687cd566c0cfd4ba]::vec::spec_extend::SpecExtend<rustc_middle[6c01273334a4e0ad]::ty::generics::GenericParamDef, core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>>, rustc_typeck[ad352206ed2ad8b]::collect::generics_of::{closure#2}>>>::spec_extend
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/spec_extend.rs:18:9
  85:     0x7fb74a796767 - <alloc[687cd566c0cfd4ba]::vec::Vec<rustc_middle[6c01273334a4e0ad]::ty::generics::GenericParamDef> as core[54fe93355658fbe8]::iter::traits::collect::Extend<rustc_middle[6c01273334a4e0ad]::ty::generics::GenericParamDef>>::extend::<core[54fe93355658fbe8]::iter::adapters::map::Map<core[54fe93355658fbe8]::iter::adapters::enumerate::Enumerate<core[54fe93355658fbe8]::iter::adapters::filter::Filter<core[54fe93355658fbe8]::slice::iter::Iter<rustc_hir[80600f8cf2fd79ed]::hir::GenericParam>, rustc_typeck[ad352206ed2ad8b]::collect::early_bound_lifetimes_from_generics::{closure#0}>>, rustc_typeck[ad352206ed2ad8b]::collect::generics_of::{closure#2}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/vec/mod.rs:2618:9
  86:     0x7fb74a796767 - rustc_typeck[ad352206ed2ad8b]::collect::generics_of
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_typeck/src/collect.rs:1686:5
  87:     0x7fb74b938015 - <rustc_query_system[eed0fda852e3a6e5]::query::config::QueryVtable<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/config.rs:43:9
  88:     0x7fb74b938015 - rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job::<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:415:55
  89:     0x7fb74b938015 - stacker[480059cd772f137f]::maybe_grow::<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  90:     0x7fb74b938015 - rustc_data_structures[261e35101f56a30d]::stack::ensure_sufficient_stack::<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:16:5
  91:     0x7fb74b62441b - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:113:17
  92:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:50
  93:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::set_tlv::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1794:9
  94:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::enter_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1810:9
  95:     0x7fb74b62441b - <rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query::<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:13
  96:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context::<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1854:13
  97:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1838:40
  98:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context_opt::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generics, rustc_query_system[eed0fda852e3a6e5]::query::plumbing::execute_job<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt, rustc_span[c11b030d3e5eb8ab]::def_id::DefId, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>::{closure#0}, rustc_middle[6c01273334a4e0ad]::ty::generics::Generics>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context.rs:1827:22
  99:     0x7fb74b62441b - rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_context::<rustc_middle[6c01273334a4e0ad]::ty::context::tls::with_related_context<<rustc_query_impl[f86e27b60e1fe7a7]::plumbing::QueryCtxt as rustc_query_system[eed0fda852e3a6e5]::query::QueryContext>::start_query<rustc_middle[6c01273334a4e0ad]::ty::generics::Generi
  
 ...................... had to cut away some stuff due to character limit in github issues ............
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

query stack during panic:
#0 [resolve_lifetimes] resolving lifetimes
#1 [is_late_bound_map] testing if a region is late bound
#2 [generics_of] computing generics of `with_test_item_names`
#3 [collect_mod_item_types] collecting item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 173 previous errors; 11 warnings emitted

Some errors have detailed explanations: E0405, E0408, E0416, E0422, E0432, E0433, E0531, E0532, E0574.
For more information about an error, try `rustc --explain E0405`.
```

</p>
</details>

### LINKED ISSUE #109854: ICE: attempted to add with overflow `compiler/rustc_errors/src/emitter.rs:2269:17`
### Code

You need debug assertions and probably also `debug-assertions-std = true` enabled

```Rust
fn generate_setter() {
    String::with_capacity(
    generate_setter,
    r#"
pub(crate) struct Person<T: Clone> {}
"#,
     r#""#,
    );
}

```

### Meta

`rustc --version --verbose`:
```
b9535c0b7d64290b27c4a116262402cd12f77833
```

### Error output

```
error[E0601]: `main` function not found in crate `treereduce`
 --> treereduce.out:9:2
  |
9 | }
  |  ^ consider adding a `main` function to `treereduce.out`

error[E0061]: this function takes 1 argument but 3 arguments were supplied
   --> treereduce.out:2:5
    |
2   |       String::with_capacity(
    |       ^^^^^^^^^^^^^^^^^^^^^
3   |       generate_setter,
4   | /     r#"
5   | | pub(crate) struct Person<T: Clone> {}
6   | | "#,
    | |__- unexpected argument of type `&'static str`
7   |        r#""#,
    |        ----- unexpected argument of type `&'static str`
    |
note: expected `usize`, found fn item
   --> treereduce.out:3:5
    |
3   |     generate_setter,
    |     ^^^^^^^^^^^^^^^
    = note: expected type `usize`
            found fn item `fn() {generate_setter}`
note: associated function defined here
   --> /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/string.rs:498:12
    |
498 |     pub fn with_capacity(capacity: usize) -> String {
    |            ^^^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'attempt to add with overflow', compiler/rustc_errors/src/emitter.rs:2269:17
stack backtrace:
   0:     0x7f8f8df08c14 - std::backtrace_rs::backtrace::libunwind::trace::h67b163ebe8a31594
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f8f8df08c14 - std::backtrace_rs::backtrace::trace_unsynchronized::h3c8281a1c2f00064
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8f8df08c14 - std::sys_common::backtrace::_print_fmt::h06cb971327b8c2e2
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f8f8df08c14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ee75b43d657a8f4
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8f8dfb96eb - core::fmt::write::h2dac34aae88eac3a
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f8f8df4ccef - std::io::Write::write_fmt::h7ccd79b72628a6b8
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1698:15
   6:     0x7f8f8df08a15 - std::sys_common::backtrace::_print::hd635497dbec07356
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f8f8df08a15 - std::sys_common::backtrace::print::hff530ee89e14fe85
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f8f8df33f74 - std::panicking::default_hook::{{closure}}::h4e7fb0c7799d720c
   9:     0x7f8f8df33bad - std::panicking::default_hook::ha8e4a4f93e8d13cc
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:288:9
  10:     0x7f8f90a58ec5 - <alloc[80fd20bfa47e5cbe]::boxed::Box<dyn for<'a, 'b> core[56d2be079082b2f7]::ops::function::Fn<(&'a core[56d2be079082b2f7]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[56d2be079082b2f7]::marker::Send + core[56d2be079082b2f7]::marker::Sync> as core[56d2be079082b2f7]::ops::function::Fn<(&core[56d2be079082b2f7]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  11:     0x7f8f90a58ec5 - rustc_driver_impl[3922376c7e667c84]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1188:17
  12:     0x7f8f8df34761 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h95f03351df89329f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1990:9
  13:     0x7f8f8df34761 - std::panicking::rust_panic_with_hook::hd91c43bc8d7e412b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:694:13
  14:     0x7f8f8df091f2 - std::panicking::begin_panic_handler::{{closure}}::h42d76a5ff060f351
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:579:13
  15:     0x7f8f8df08cf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h74d47eee5ac245dc
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x7f8f8df34282 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:577:5
  17:     0x7f8f8dfe07a3 - core::panicking::panic_fmt::h3d0a8f81bb9ae67d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:67:14
  18:     0x7f8f8dfe083d - core::panicking::panic::h8315a6df2d01c70b
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:117:5
  19:     0x7f8f90b19770 - <rustc_errors[b006902e8e5ecbbb]::emitter::EmitterWriter>::draw_code_line
  20:     0x7f8f90b16fda - <rustc_errors[b006902e8e5ecbbb]::emitter::EmitterWriter>::emit_suggestion_default
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:1954:17
  21:     0x7f8f90b125da - <rustc_errors[b006902e8e5ecbbb]::emitter::EmitterWriter>::emit_messages_default
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:2150:49
  22:     0x7f8f90b125da - <rustc_errors[b006902e8e5ecbbb]::emitter::EmitterWriter as rustc_errors[b006902e8e5ecbbb]::emitter::Emitter>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/emitter.rs:556:9
  23:     0x7f8f90b4a3f9 - <rustc_errors[b006902e8e5ecbbb]::HandlerInner>::emit_diagnostic::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1401:17
  24:     0x7f8f915cead4 - rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/callbacks.rs:41:53
  25:     0x7f8f915cead4 - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  26:     0x7f8f915cead4 - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::try_with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:252:16
  27:     0x7f8f915cead4 - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:228:9
  28:     0x7f8f915cead4 - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  29:     0x7f8f915cead4 - rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/callbacks.rs:41:20
  30:     0x7f8f915cead4 - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context_opt::<rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
  31:     0x7f8f915cead4 - rustc_interface[28f2438de7458a47]::callbacks::track_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/callbacks.rs:31:5
  32:     0x7f8f90b495ac - <rustc_errors[b006902e8e5ecbbb]::HandlerInner>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1370:9
  33:     0x7f8f90b55f16 - <rustc_errors[b006902e8e5ecbbb]::Handler>::emit_diagnostic
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/lib.rs:1121:9
  34:     0x7f8f90b55f16 - <rustc_span[9569648757f2d60c]::ErrorGuaranteed as rustc_errors[b006902e8e5ecbbb]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic_builder.rs:169:28
  35:     0x7f8f9106863b - <rustc_errors[b006902e8e5ecbbb]::diagnostic_builder::DiagnosticBuilder<rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::emit
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic_builder.rs:505:9
  36:     0x7f8f9106863b - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::report_arg_errors
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1253:9
  37:     0x7f8f91062e2f - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_argument_types
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:453:13
  38:     0x7f8f91027142 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::confirm_builtin_call
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/callee.rs:460:9
  39:     0x7f8f91025799 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_call
  40:     0x7f8f910bd501 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:330:45
  41:     0x7f8f910412ec - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:237:18
  42:     0x7f8f910412ec - stacker[7d0e6083c51d6934]::maybe_grow::<rustc_middle[ddc0d9627cd9f41e]::ty::Ty, <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  43:     0x7f8f910412ec - rustc_data_structures[ff980df7d59f2440]::stack::ensure_sufficient_stack::<rustc_middle[ddc0d9627cd9f41e]::ty::Ty, <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  44:     0x7f8f910412ec - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:233:18
  45:     0x7f8f910bc832 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:187:9
  46:     0x7f8f9106b23e - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_stmt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1468:17
  47:     0x7f8f9106b945 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1521:17
  48:     0x7f8f9106b945 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::with_breakable_ctxt::<<rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_block_with_expected::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:1468:22
  49:     0x7f8f9106b945 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_block_with_expected
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1519:26
  50:     0x7f8f910bd105 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_kind
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:329:41
  51:     0x7f8f910412ec - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:237:18
  52:     0x7f8f910412ec - stacker[7d0e6083c51d6934]::maybe_grow::<rustc_middle[ddc0d9627cd9f41e]::ty::Ty, <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  53:     0x7f8f910412ec - rustc_data_structures[ff980df7d59f2440]::stack::ensure_sufficient_stack::<rustc_middle[ddc0d9627cd9f41e]::ty::Ty, <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  54:     0x7f8f910412ec - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:233:18
  55:     0x7f8f910bc832 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_expectation
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:187:9
  56:     0x7f8f91043096 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_expr_with_hint
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:139:9
  57:     0x7f8f91043096 - <rustc_hir_typeck[d24901ef7ba52e02]::fn_ctxt::FnCtxt>::check_return_expr
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/expr.rs:826:30
  58:     0x7f8f9123621a - rustc_hir_typeck[d24901ef7ba52e02]::check::check_fn
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/check.rs:122:9
  59:     0x7f8f9126116a - rustc_hir_typeck[d24901ef7ba52e02]::typeck_with_fallback::<rustc_hir_typeck[d24901ef7ba52e02]::typeck::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:231:9
  60:     0x7f8f9126116a - rustc_hir_typeck[d24901ef7ba52e02]::typeck_with_fallback::<rustc_hir_typeck[d24901ef7ba52e02]::typeck::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:191:36
  61:     0x7f8f9126116a - rustc_hir_typeck[d24901ef7ba52e02]::typeck
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:172:9
  62:     0x7f8f925c5ebe - <rustc_query_impl[33f66818407d1b0e]::queries::typeck as rustc_query_system[dea804868d3de2b0]::query::config::QueryConfig<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
  63:     0x7f8f925c5ebe - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:443:72
  64:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  65:     0x7f8f925c5ebe - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::try_with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:252:16
  66:     0x7f8f925c5ebe - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:228:9
  67:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:5
  68:     0x7f8f925c5ebe - <rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query::<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
  69:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context::<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:133:9
  70:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:36
  71:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context_opt::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
  72:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:5
  73:     0x7f8f925c5ebe - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context::<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, &rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:124:5
  74:     0x7f8f925c5ebe - <rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query::<&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:9
  75:     0x7f8f925c5ebe - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:443:18
  76:     0x7f8f925c5ebe - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:401:17
  77:     0x7f8f925c5ebe - rustc_query_system[dea804868d3de2b0]::query::plumbing::try_execute_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:357:13
  78:     0x7f8f927fed05 - rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:800:36
  79:     0x7f8f927fed05 - stacker[7d0e6083c51d6934]::maybe_grow::<(&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, core[56d2be079082b2f7]::option::Option<rustc_query_system[dea804868d3de2b0]::dep_graph::graph::DepNodeIndex>), rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  80:     0x7f8f927fed05 - rustc_data_structures[ff980df7d59f2440]::stack::ensure_sufficient_stack::<(&rustc_middle[ddc0d9627cd9f41e]::ty::typeck_results::TypeckResults, core[56d2be079082b2f7]::option::Option<rustc_query_system[dea804868d3de2b0]::dep_graph::graph::DepNodeIndex>), rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
  81:     0x7f8f927fed05 - rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:800:9
  82:     0x7f8f927fed05 - <rustc_query_impl[33f66818407d1b0e]::Queries as rustc_middle[ddc0d9627cd9f41e]::ty::query::QueryEngine>::typeck::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:805:17
  83:     0x7f8f927fed05 - <rustc_query_impl[33f66818407d1b0e]::Queries as rustc_middle[ddc0d9627cd9f41e]::ty::query::QueryEngine>::typeck
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:46:1
  84:     0x7f8f912ca3b4 - <rustc_middle[ddc0d9627cd9f41e]::ty::query::TyCtxtEnsure>::typeck::<rustc_span[9569648757f2d60c]::def_id::LocalDefId>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:351:29
  85:     0x7f8f912ca3b4 - rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:156:64
  86:     0x7f8f912ca3b4 - <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners::<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/hir/map/mod.rs:492:82
  87:     0x7f8f912ca3b4 - rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in::<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync.rs:181:66
  88:     0x7f8f912ca3b4 - <core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core[56d2be079082b2f7]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  89:     0x7f8f912ca3b4 - std[2f6676e1b2585ce5]::panicking::try::do_call::<core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:485:40
  90:     0x7f8f912ca3b4 - std[2f6676e1b2585ce5]::panicking::try::<(), core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:449:19
  91:     0x7f8f9118ee98 - std[2f6676e1b2585ce5]::panic::catch_unwind::<core[56d2be079082b2f7]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  92:     0x7f8f9118ee98 - rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in::<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync.rs:181:33
  93:     0x7f8f9118ee98 - <core[56d2be079082b2f7]::slice::iter::Iter<rustc_span[9569648757f2d60c]::def_id::LocalDefId> as core[56d2be079082b2f7]::iter::traits::iterator::Iterator>::for_each::<rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/slice/iter/macros.rs:201:21
  94:     0x7f8f9118ee98 - rustc_data_structures[ff980df7d59f2440]::sync::par_for_each_in::<&[rustc_span[9569648757f2d60c]::def_id::LocalDefId], <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/sync.rs:180:13
  95:     0x7f8f9125dfb3 - <rustc_middle[ddc0d9627cd9f41e]::hir::map::Map>::par_body_owners::<rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/hir/map/mod.rs:492:9
  96:     0x7f8f9125dfb3 - rustc_hir_typeck[d24901ef7ba52e02]::typeck_item_bodies
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_typeck/src/lib.rs:156:5
  97:     0x7f8f92555a8e - <rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies as rustc_query_system[dea804868d3de2b0]::query::config::QueryConfig<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
  98:     0x7f8f92555a8e - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:443:72
  99:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, ()>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
 100:     0x7f8f92555a8e - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::try_with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:252:16
 101:     0x7f8f92555a8e - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:228:9
 102:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:5
 103:     0x7f8f92555a8e - <rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query::<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
 104:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context::<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, ()>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:133:9
 105:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:36
 106:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context_opt::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
 107:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:5
 108:     0x7f8f92555a8e - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context::<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, ()>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:124:5
 109:     0x7f8f92555a8e - <rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query::<(), rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:112:9
 110:     0x7f8f92555a8e - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:443:18
 111:     0x7f8f92555a8e - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:401:17
 112:     0x7f8f92555a8e - rustc_query_system[dea804868d3de2b0]::query::plumbing::try_execute_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:357:13
 113:     0x7f8f927fe45e - rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:800:36
 114:     0x7f8f927fe45e - stacker[7d0e6083c51d6934]::maybe_grow::<((), core[56d2be079082b2f7]::option::Option<rustc_query_system[dea804868d3de2b0]::dep_graph::graph::DepNodeIndex>), rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 115:     0x7f8f927fe45e - rustc_data_structures[ff980df7d59f2440]::stack::ensure_sufficient_stack::<((), core[56d2be079082b2f7]::option::Option<rustc_query_system[dea804868d3de2b0]::dep_graph::graph::DepNodeIndex>), rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/stack.rs:17:5
 116:     0x7f8f927fe45e - rustc_query_system[dea804868d3de2b0]::query::plumbing::get_query::<rustc_query_impl[33f66818407d1b0e]::queries::typeck_item_bodies, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:800:9
 117:     0x7f8f927fe45e - <rustc_query_impl[33f66818407d1b0e]::Queries as rustc_middle[ddc0d9627cd9f41e]::ty::query::QueryEngine>::typeck_item_bodies::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:805:17
 118:     0x7f8f927fe45e - <rustc_query_impl[33f66818407d1b0e]::Queries as rustc_middle[ddc0d9627cd9f41e]::ty::query::QueryEngine>::typeck_item_bodies
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/lib.rs:46:1
 119:     0x7f8f90d60ef9 - <rustc_middle[ddc0d9627cd9f41e]::ty::query::TyCtxtAt>::typeck_item_bodies
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:400:29
 120:     0x7f8f90d60ef9 - <rustc_middle[ddc0d9627cd9f41e]::ty::context::TyCtxt>::typeck_item_bodies
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/query.rs:386:35
 121:     0x7f8f90d60ef9 - rustc_hir_analysis[8a7ee2688cdb399f]::check_crate::{closure#7}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_analysis/src/lib.rs:500:50
 122:     0x7f8f90d60ef9 - <rustc_data_structures[ff980df7d59f2440]::profiling::VerboseTimingGuard>::run::<(), rustc_hir_analysis[8a7ee2688cdb399f]::check_crate::{closure#7}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:752:9
 123:     0x7f8f90d60ef9 - <rustc_session[9cd5fd28d2fc2c89]::session::Session>::time::<(), rustc_hir_analysis[8a7ee2688cdb399f]::check_crate::{closure#7}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:11:50
 124:     0x7f8f90f11c13 - rustc_hir_analysis[8a7ee2688cdb399f]::check_crate
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_hir_analysis/src/lib.rs:500:5
 125:     0x7f8f915a4f47 - rustc_interface[28f2438de7458a47]::passes::analysis
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:762:5
 126:     0x7f8f925c803a - <rustc_query_impl[33f66818407d1b0e]::queries::analysis as rustc_query_system[dea804868d3de2b0]::query::config::QueryConfig<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>>::compute
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:519:21
 127:     0x7f8f925c803a - rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr::<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_system/src/query/plumbing.rs:443:72
 128:     0x7f8f925c803a - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:82:9
 129:     0x7f8f925c803a - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::try_with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:252:16
 130:     0x7f8f925c803a - <std[2f6676e1b2585ce5]::thread::local::LocalKey<core[56d2be079082b2f7]::cell::Cell<*const ()>>>::with::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/local.rs:228:9
 131:     0x7f8f925c803a - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::enter_context::<rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:79:5
 132:     0x7f8f925c803a - <rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query::<core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_query_impl/src/plumbing.rs:127:13
 133:     0x7f8f925c803a - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context::<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:133:9
 134:     0x7f8f925c803a - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:111:36
 135:     0x7f8f925c803a - rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context_opt::<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_context<rustc_middle[ddc0d9627cd9f41e]::ty::context::tls::with_related_context<<rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt as rustc_query_system[dea804868d3de2b0]::query::QueryContext>::start_query<core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>, rustc_query_system[dea804868d3de2b0]::query::plumbing::execute_job_non_incr<rustc_query_impl[33f66818407d1b0e]::queries::analysis, rustc_query_impl[33f66818407d1b0e]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>::{closure#0}, core[56d2be079082b2f7]::result::Result<(), rustc_span[9569648757f2d60c]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_middle/src/ty/context/tls.rs:100:18
                               
<snip>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `generate_setter`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Badel2**
Fix #109854
Close #94171 (was already fixed before but missing test)

This bug happens when a multipart suggestion spans more than one line.

The fix is to update the `acc` variable, which didn't handle the case when the text to remove spans multiple lines but the text to add spans only one line.

Also, use `usize::try_from` instead of  `as usize` to detect overflows earlier in the future, and point to the source of the overflow (the original issue points to a different place where this value is used, not where the overflow had happened).

And finally add an `if start != end` check to avoid doing any extra work in case of empty ranges.

Long explanation:

Given this test case:

```rust
fn generate_setter() {
    String::with_capacity(
    //~^ ERROR this function takes 1 argument but 3 arguments were supplied
    generate_setter,
    r#"
pub(crate) struct Person<T: Clone> {}
"#,
     r#""#,
    );
}
```

The compiler will try to convert that code into the following:

```rust
fn generate_setter() {
    String::with_capacity(
    //~^ ERROR this function takes 1 argument but 3 arguments were supplied
    /* usize */,
    );
}
```

So it creates a suggestion with 3 separate parts:

```
// Replace "generate_setter" with "/* usize */"
SubstitutionPart { span: fuzz_input.rs:4:5: 4:20 (#0), snippet: "/* usize */" }
// Remove second arg (multiline string)
SubstitutionPart { span: fuzz_input.rs:4:20: 7:3 (#0), snippet: "" }
// Remove third arg (r#""#)
SubstitutionPart { span: fuzz_input.rs:7:3: 8:11 (#0), snippet: "" }
```

Each of this parts gets a separate `SubstitutionHighlight` (this marks the relevant text green in a terminal, the values are 0-indexed so `start: 4` means column 5):

```
SubstitutionHighlight { start: 4, end: 15 }
SubstitutionHighlight { start: 15, end: 15 }
SubstitutionHighlight { start: 18446744073709551614, end: 18446744073709551614 }
```

The 2nd and 3rd suggestion are empty (start = end) because they only remove text, so there are no additions to highlight. But the 3rd span has overflowed because the compiler assumes that the 3rd suggestion is on the same line as the first suggestion. The 2nd span starts at column 20 and the highlight starts at column 16 (15+1), so that suggestion is good. But since the 3rd span starts at column 3, the result is `3 - 4`, or column -1, which turns into -2 with 0-indexed, and that's equivalent to `18446744073709551614 as isize`.

With this fix, the resulting `SubstitutionHighlight` are:

```
SubstitutionHighlight { start: 4, end: 15 }
SubstitutionHighlight { start: 15, end: 15 }
SubstitutionHighlight { start: 15, end: 15 }
```

As expected. I guess ideally we shouldn't emit empty highlights when removing text, but I am too scared to change that.

### CODE REVIEW

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -325,17 +325,16 @@ impl CodeSuggestion {
...
-                        // Account for the difference between the width of the current code and the
-                        // snippet being suggested, so that the *later* suggestions are correctly
-                        // aligned on the screen.
-                        acc += len - (cur_hi.col.0 - cur_lo.col.0) as isize;
-                    }
+                    // Account for the difference between the width of the current code and the
+                    // snippet being suggested, so that the *later* suggestions are correctly
+                    // aligned on the screen. Note that cur_hi and cur_lo can be on different
+                    // lines, so cur_hi.col can be smaller than cur_lo.col
+                    acc += len - (cur_hi.col.0 as isize - cur_lo.col.0 as isize);
```
Comment (compiler-errors) [inline compiler/rustc_errors/src/lib.rs:337]: Can this be simplified to `len + cur_lo - cur_hi`?

**Comment by Badel2** [comment]
I already found the first bug thanks to the `usize::try_from`, but I will revert that change because it may introduce too much noise. That's because the integer overflow I am trying to solve can only be seen with debug assertions, and `usize::try_from().unwrap()` will trigger even in normal builds. 

This test case:

```rust
fn main() {
    let a = 0.le('r',3.+0,3.+0,                      3);
}
```

Has an overflow because the spans overlap. The error message is mostly correct:

```
error[E0061]: this method takes 1 argument but 4 arguments were supplied
 --> fuzz_input.rs:2:15
  |
2 |     let a = 0.le('r',3.+0,3.+0,                      3);
  |               ^^ ---      ----                       - unexpected argument of type `{integer}`
  |                  |        |
  |                  |        unexpected argument
  |                  unexpected argument of type `char`
  |
2

help: remove the extra arguments
  |
2 -     let a = 0.le('r',3.+0,3.+0,                      3);
2 +     let a = 0.le(,3.+0);
  |
```

But these are the spans:

```
SubstitutionPart { span: fuzz_input.rs:2:18: 2:21 (#0), snippet: "" }
SubstitutionPart { span: fuzz_input.rs:2:26: 2:54 (#0), snippet: "" }
SubstitutionPart { span: fuzz_input.rs:2:31: 2:55 (#0), snippet: "" }

SubstitutionHighlight { start: 17, end: 17 }
SubstitutionHighlight { start: 22, end: 22 }
SubstitutionHighlight { start: 18446744073709551615, end: 18446744073709551615 }
```

Note that this bug is already present in master, it is not caused by the changes in this PR. The spans overlap because they get expanded in the "delete next comma" logic from here:

https://github.com/rust-lang/rust/blob/17a681000b98d58d6e54cecc3e33d978c34ede32/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L954

Here are some logs that show how the spans are modified inside that function:

```
span: fuzz_input.rs:2:18: 2:21 (#0)
Include previous comma: expanded fuzz_input.rs:2:54: 2:55 (#0) to fuzz_input.rs:2:31: 2:55 (#0)
span: fuzz_input.rs:2:31: 2:55 (#0)
Include previous comma: expanded fuzz_input.rs:2:27: 2:31 (#0) to fuzz_input.rs:2:26: 2:31 (#0)
Delete next comma: expanded fuzz_input.rs:2:26: 2:31 (#0) to fuzz_input.rs:2:26: 2:54 (#0)
span: fuzz_input.rs:2:26: 2:54 (#0)
```

I tried to fix it by removing the "delete next comma" logic, and that fixes the overflow, but it breaks other tests.

**Review by compiler-errors — APPROVED** [review]
Please squash this into one commit. No use in keeping the revert in the history.

**Comment by compiler-errors** [comment]
Thanks

@bors r+
