### PR TITLE
Reland #83738: "rustdoc: Don't load all extern crates unconditionally"

### LINKED ISSUE #68427: rustdoc only: duplicate lang item `panic_halt`
This is a regression from `rustdoc 1.40.0 (73528e339 2019-12-16)` to `rustdoc 1.41.0-beta.3 (fb3056216 2020-01-19)`.

If rustdoc attempts to document a crate that has at least two dependencies which implement a `panic_handler`, it fails with an error similar to

```
error: duplicate lang item in crate `panic_halt` (which `panic2` depends on): `panic_impl`.
  |
  = note: first defined in crate `std` (which `panic2` depends on).
```

Note that the crate *builds* fine, it's just documenting that is broken.

---

**Steps to reproduce**

1. Create a new project, e.g. `cargo new panic2`
2. Add a dependency on `panic-halt = "0.2.0"`, e.g. `cargo add panic-halt`
3. Attempt to document the crate, e.g. `cargo doc`

<details><summary>An example of the different behavior between `stable`/`beta` and `build`/`doc`.</summary>

```shell
$ cargo +stable clean

$ cargo +beta clean

$ cargo +stable build
   Compiling panic-halt v0.2.0
   Compiling panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s

$ cargo +stable doc
 Documenting panic-halt v0.2.0
    Checking panic-halt v0.2.0
 Documenting panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 1.40s

$ cargo +beta build
   Compiling panic-halt v0.2.0
   Compiling panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s

$ cargo +beta doc
 Documenting panic-halt v0.2.0
    Checking panic-halt v0.2.0
 Documenting panic2 v0.1.0 (/Users/logic/Projects/tmp/panic2)
error: duplicate lang item in crate `panic_halt` (which `panic2` depends on): `panic_impl`.
  |
  = note: first defined in crate `std` (which `panic2` depends on).

error: aborting due to previous error

error: Could not document `panic2`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type bin --crate-name panic2 src/main.rs -o /Users/logic/Projects/tmp/panic2/target/doc --error-format=json --json=diagnostic-rendered-ansi --document-private-items -L dependency=/Users/logic/Projects/tmp/panic2/target/debug/deps --extern panic_halt=/Users/logic/Projects/tmp/panic2/target/debug/deps/libpanic_halt-6d0ca720c3c355fb.rmeta` (exit code: 1)
```

</details>

### PR DESCRIPTION
**Pull request by jyn514**
I hopefully found all the bugs :crossed_fingers: time for a take two. See the last commit for details on what went wrong before.

r? @petrochenkov (but feel free to reassign to Guillaume if you don't have time.)

Closes https://github.com/rust-lang/rust/issues/68427. Includes a fix for https://github.com/rust-lang/rust/issues/84738.

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links/early.rs [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+    crate fn visit_crate(&mut self, krate: &ast::Crate) {
+        assert_eq!(self.current_mod, CRATE_DEF_ID);
+        self.visit_attributes(&krate.attrs, krate.span);
+    }
+
+    fn visit_attributes(&mut self, attrs: &[ast::Attribute], span: Span) {
+        use crate::html::markdown::markdown_links;
+        use crate::passes::collect_intra_doc_links::preprocess_link;
+
+        // FIXME: this probably needs to consider inlining
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links/early.rs:35]: Ugh, apparently github dropped my comment because I wrote it on a commit instead of the PR itself. Do you happen to have it in your email? If not I can try to rewrite it from memory, it was discussing exactly how this bug could happen and how I don't know how to test it with a UI test.

Comment (petrochenkov) [reply src/librustdoc/passes/collect_intra_doc_links/early.rs:35]: No, I don't see any traces of the extended version of this comment in my mail.

File: src/test/rustdoc/issue-66159.rs [hunk 2]
```diff
@@ -1,10 +0,0 @@
-// aux-crate:priv:issue_66159_1=issue-66159-1.rs
-// compile-flags:-Z unstable-options
-
-// The issue was an ICE which meant that we never actually generated the docs
-// so if we have generated the docs, we're okay.
-// Since we don't generate the docs for the auxiliary files, we can't actually
-// verify that the struct is linked correctly.
-
-// @has issue_66159/index.html
-//! [issue_66159_1::Something]
```
Comment (petrochenkov) [inline src/test/rustdoc/issue-66159.rs:10]: Perhaps it makes sense to keep this test even if the rest of the PR is reverted?

Comment (jyn514) [reply src/test/rustdoc/issue-66159.rs:10]: Good catch, thanks. I'll add it back.

File: src/librustdoc/passes/collect_intra_doc_links/early.rs (hunk 1 above)
Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links/early.rs:35]: Ok, it went something like this: "inlining" is refering to `doc(inline)`, not `#[inline]`. The test case for it would look something like:

```rust
// inner_crate
pub fn foo() {}

// middle_crate
/// Link to [inner_crate::foo]
pub fn bar() {}

// outer_crate
pub use middle_crate::bar;
```
In particular, the first time `inner_crate` will be loaded is when resolving the links on `bar`, which I don't think this pass will catch because it doesn't look at the attributes of the original definition, only of the re-export.

I'm not sure how to test this with a UI test because it requires three nested crates, and AFAIK `aux-build` only supports two.

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links/early.rs:35]: Seems to work fine when testing locally though :shrug: so this is probably ok.

File: src/librustdoc/core.rs [hunk 3]
```diff
@@ -301,41 +301,17 @@ crate fn create_config(
...
-                  }
-            }
-        });
-    });
+    let (krate, resolver, _) = &*abort_on_err(queries.expansion(), sess).peek();
+    let resolver = resolver.clone();
+
+    let mut loader = crate::passes::collect_intra_doc_links::IntraLinkCrateLoader::new(resolver);
+    loader.visit_crate(krate);
+    ast::visit::walk_crate(&mut loader, krate);
```
Comment (petrochenkov) [inline src/librustdoc/core.rs:312]: This code looks like it's visiting the crate twice.
It's probably better to rename `visit_crate`/`visit_attributes` to something that doesn't look like default `Visitor` methods.

Also, there's no need to pull the `loader` to outside of `src/librustdoc/passes/collect_intra_doc_links/early.rs`, the visiting logic can live in that module entirely.
Then making `visit_crate` a separate function won't be necessary as well.

**Comment by petrochenkov** [comment]
r=me with https://github.com/rust-lang/rust/pull/88215#discussion_r693559128 addressed.
