### PR TITLE
Fix ICE in mir when evaluating SizeOf on unsized type

### LINKED ISSUE #80742: ICE'd during const eval of generic with DST
Reproducible in the playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a7e62bb084b21bc2081c79e320c740a0

### Code

```Rust
#![feature(const_evaluatable_checked)]
#![feature(const_generics)]

use core::fmt::Debug;
use core::marker::PhantomData;

struct Inline<T>
where [u8; ::core::mem::size_of::<T>() + 1]: 
{
    _phantom: PhantomData<T>,
    buf: [u8; ::core::mem::size_of::<T>() + 1]
}

impl<T> Inline<T>  where [u8; ::core::mem::size_of::<T>() + 1]: {
    pub fn new(val: T) -> Inline<T> {
        todo!()
    }
}

fn main() {
    // let dst = Inline::<usize>::new(0); OK
    let dst = Inline::<dyn Debug>::new(0);  // BANG!
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (61f5a0092 2021-01-04)
binary: rustc
commit-hash: 61f5a0092364061ec5649ca98d5e3e9b927880fe
commit-date: 2021-01-04
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

### Error output

```
   Compiling icey v0.1.0 (/tmp/icey)
warning: the feature `const_evaluatable_checked` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:12
  |
1 | #![feature(const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

thread 'rustc' panicked at 'SizeOf nullary MIR operator called for unsized type', compiler/rustc_mir/src/interpret/step.rs:267:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (61f5a0092 2021-01-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `Inline::<T>::{constant#0}`
#1 [eval_to_const_value_raw] simplifying constant for the type system `Inline::<T>::{constant#0}`
end of query stack
warning: 2 warnings emitted

error: could not compile `icey`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling icey v0.1.0 (/tmp/icey)
warning: the feature `const_evaluatable_checked` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:12
  |
1 | #![feature(const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

thread 'rustc' panicked at 'SizeOf nullary MIR operator called for unsized type', compiler/rustc_mir/src/interpret/step.rs:267:17
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
   2: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
   3: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
   4: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_allocation_raw>::compute
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   7: rustc_data_structures::stack::ensure_sufficient_stack
   8: rustc_query_system::query::plumbing::get_query_impl
   9: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_const_value_raw>::compute
  11: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_query_system::query::plumbing::get_query_impl
  15: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  16: rustc_infer::infer::InferCtxt::const_eval_resolve
  17: rustc_trait_selection::traits::const_evaluatable::is_const_evaluatable
  18: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::{{closure}}
  19: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively
  20: rustc_infer::infer::InferCtxt::probe
  21: rustc_trait_selection::traits::select::SelectionContext::evaluate_root_obligation
  22: rustc_infer::infer::InferCtxtBuilder::enter_with_canonical
  23: rustc_traits::evaluate_obligation::evaluate_obligation
  24: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::evaluate_obligation>::compute
  25: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::get_query_impl
  29: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  30: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  31: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::predicate_may_hold
  32: rustc_infer::infer::InferCtxt::probe
  33: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  34: rustc_typeck::check::method::probe::ProbeContext::pick_method
  35: rustc_typeck::check::method::probe::ProbeContext::pick_core
  36: rustc_typeck::check::method::probe::ProbeContext::pick
  37: rustc_infer::infer::InferCtxt::probe
  38: rustc_typeck::check::method::probe::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::probe_for_name
  39: rustc_typeck::check::method::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_ufcs
  40: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_ty_and_res_ufcs
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  43: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  44: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  45: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  46: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl_initializer
  47: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl_local
  48: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  49: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  52: rustc_typeck::check::check::check_fn
  53: rustc_infer::infer::InferCtxtBuilder::enter
  54: rustc_typeck::check::typeck
  55: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  56: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  57: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  58: rustc_data_structures::stack::ensure_sufficient_stack
  59: rustc_query_system::query::plumbing::get_query_impl
  60: rustc_query_system::query::plumbing::ensure_query_impl
  61: rustc_typeck::check::typeck_item_bodies
  62: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  63: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  64: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  65: rustc_data_structures::stack::ensure_sufficient_stack
  66: rustc_query_system::query::plumbing::get_query_impl
  67: rustc_typeck::check_crate
  68: rustc_interface::passes::analysis
  69: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  70: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  71: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  72: rustc_data_structures::stack::ensure_sufficient_stack
  73: rustc_query_system::query::plumbing::get_query_impl
  74: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  75: rustc_span::with_source_map
  76: rustc_interface::interface::create_compiler_and_run
  77: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (61f5a0092 2021-01-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `Inline::<T>::{constant#0}`
#1 [eval_to_const_value_raw] simplifying constant for the type system `Inline::<T>::{constant#0}`
#2 [evaluate_obligation] evaluating trait selection obligation `the constant `Inline::<dyn std::fmt::Debug>::{constant#0}` can be evaluated`
#3 [typeck] type-checking `main`
#4 [typeck_item_bodies] type-checking all item bodies
#5 [analysis] running analysis passes on this crate
end of query stack
warning: 2 warnings emitted

error: could not compile `icey`

To learn more, run the command again with --verbose.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by osa1**
Not quite ready yet. This tries to fix #80742 as discussed on [Zulip topic][1],
by using `delay_span_bug`.

I don't understand what `delay_span_bug` does. It seems like my error message
is never used. With this patch, in this program:

```rust
#![allow(incomplete_features)]
#![feature(const_evaluatable_checked)]
#![feature(const_generics)]

use std::fmt::Debug;
use std::marker::PhantomData;
use std::mem::size_of;

struct Inline<T>
where
    [u8; size_of::<T>() + 1]: ,
{
    _phantom: PhantomData<T>,
    buf: [u8; size_of::<T>() + 1],
}

impl<T> Inline<T>
where
    [u8; size_of::<T>() + 1]: ,
{
    pub fn new(val: T) -> Inline<T> {
        todo!()
    }
}

fn main() {
    let dst = Inline::<dyn Debug>::new(0); // line 27
}
```

these errors are printed, both for line 27 (annotated line above):

- "no function or associated item named `new` found for struct `Inline<dyn
  Debug>` in the current scope"
- "the size for values of type `dyn Debug` cannot be known at compilation time"

Second error makes sense, but I'm not sure about the first one and why it's
even printed.

Finally, I'm not sure about the span passing in `const_eval`.

[1]: https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Help.20fixing.20.2380742

### CODE REVIEW

File: compiler/rustc_mir/src/interpret/step.rs [hunk 1]
```diff
@@ -264,10 +268,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
             NullaryOp(mir::NullOp::SizeOf, ty) => {
                 let ty = self.subst_from_current_frame_and_normalize_erasing_regions(ty);
                 let layout = self.layout_of(ty)?;
-                assert!(
-                    !layout.is_unsized(),
-                    "SizeOf nullary MIR operator called for unsized type"
-                );
+                if layout.is_unsized() {
+                    self.tcx.sess.delay_span_bug(
+                        span,
```
Comment (oli-obk) [inline compiler/rustc_mir/src/interpret/step.rs:273]: you can use `self.frame().current_span()` here, which gets you the same span.

Please leave a `FIXME` comment to remind us to look at this when we fix const eval running early

**Comment by oli-obk** [comment]
> I don't understand what `delay_span_bug` does. It seems like my error message
> is never used.

That means it's working :laughing: . `delay_span_bug` is a way to make sure we poison the compiler to cause an ICE if no errors are reported. The message and span would be used in that case, but as long as an error is reported elsewhere, it is not shown. While we could report an error here, that would just add to the noise and likely be a less useful error than the one emitted by typeck.

> Second error makes sense, but I'm not sure about the first one and why it's
even printed.

The first error occurs because we fail to satisfy the generic bounds, so we don't find the `new` method that you wrote. Basically you have to treat it as if the compiler goes through all impl blocks to find methods, but it doesn't even look into the impl block if it can't satisfy the bounds on the impl block.

**Comment by osa1** [comment]
Thanks for the detailed answer @oli-obk , very helpful.

File: compiler/rustc_mir/src/interpret/step.rs [hunk 2]
```diff
@@ -264,10 +268,12 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+                        &format!("SizeOf nullary MIR operator called for unsized type {:?}", ty),
```
Comment (osa1) [inline compiler/rustc_mir/src/interpret/step.rs:274]: @oli-obk is this debug string useful? I'm don't know if Debug impl of `TyS` is useful or not.. (perhaps it just prints a type id or something like that?)

File: compiler/rustc_mir/src/interpret/step.rs (hunk 1 above)
Comment (osa1) [reply compiler/rustc_mir/src/interpret/step.rs:273]: > you can use self.frame().current_span() here, which gets you the same span.

Done.

> Please leave a FIXME comment to remind us to look at this when we fix const eval running early

What should the FIXME say? I don't know what the long-term plan here is.

**Comment by osa1** [comment]
Interesting.. I updated by branch (https://github.com/osa1/rust/tree/fix_80742) but the PR is not updated, it's still showing the old version.

File: compiler/rustc_mir/src/interpret/step.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_mir/src/interpret/step.rs:270]: you can print types with the display impl, which is the human readable form which should totally suffice here

File: compiler/rustc_mir/src/interpret/step.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_mir/src/interpret/step.rs]: You can reference the new test you added and state that this should be turned into a `span_bug` again once that test will pass with that change.

File: src/test/ui/mir/issue-80742.stderr [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+   = help: the trait `Sized` is not implemented for `dyn Debug`
+help: consider relaxing the implicit `Sized` restriction
+   |
+LL | struct Inline<T: ?Sized>
+   |                ^^^^^^^^
+
+error: aborting due to 2 previous errors
+
+Some errors have detailed explanations: E0277, E0599.
+For more information about an error, try `rustc --explain E0277`.
```
Comment (osa1) [inline src/test/ui/mir/issue-80742.stderr:42]: @oli-obk I don't care about this output too much, I just don't want this program to break the compiler. Is there a way to tell "just run the test and expect it to fail (but not with ICE!)"?

Comment (oli-obk) [reply src/test/ui/mir/issue-80742.stderr:42]: hmm... not really, this is how our UI test suite works. You can just ignore this file, it will keep getting autogenerated with `--bless`, and it doesn't actually matter what it says, all that matters is that the test keeps failing, which you checked with `//check-fail`

File: compiler/rustc_mir/src/interpret/step.rs (hunk 1 above)
Comment (osa1) [reply compiler/rustc_mir/src/interpret/step.rs]: I don't know what you mean by "that change" but I just added a FIXME

File: compiler/rustc_mir/src/interpret/step.rs (hunk 2 above)
Comment (osa1) [reply compiler/rustc_mir/src/interpret/step.rs]: Done.

**Comment by osa1** [comment]
@oli-obk This is ready for reviews & merge.

File: src/test/ui/mir/issue-80742.stderr (hunk 3 above)
Comment (tmiasko) [reply src/test/ui/mir/issue-80742.stderr:42]: > Is there a way to tell "just run the test and expect it to fail (but not with ICE!)"?

This is the default behaviour. The exit code for an ICE is different and checked by the compiletest tool that runs the tests.

Comment (osa1) [reply src/test/ui/mir/issue-80742.stderr:42]: I mean I don't want to check in a .stderr file because I don't care about the actual error message here. I just want to test that the compiler does not crash when compiling this program.

Comment (tmiasko) [reply src/test/ui/mir/issue-80742.stderr:42]: Ignoring stderr is also possible (dont-check-compiler-stderr or something like that), but would be rather unusual for a regression test to do so. I would recommend leaving this as is.

File: compiler/rustc_mir/src/interpret/step.rs [hunk 4]
```diff
@@ -264,10 +264,13 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
             NullaryOp(mir::NullOp::SizeOf, ty) => {
                 let ty = self.subst_from_current_frame_and_normalize_erasing_regions(ty);
                 let layout = self.layout_of(ty)?;
-                assert!(
-                    !layout.is_unsized(),
-                    "SizeOf nullary MIR operator called for unsized type"
-                );
+                if layout.is_unsized() {
+                    // FIXME: This should be a span_bug
```
Comment (oli-obk) [inline compiler/rustc_mir/src/interpret/step.rs:268]: Please also reference `#80742` so we have some way to track what's going on here

Comment (osa1) [reply compiler/rustc_mir/src/interpret/step.rs]: Done.

**Comment by oli-obk** [comment]
Thanks!

@bors r+ rollup

File: compiler/rustc_mir/src/interpret/step.rs [hunk 5]
```diff
@@ -264,10 +264,13 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
-                    !layout.is_unsized(),
-                    "SizeOf nullary MIR operator called for unsized type"
-                );
+                if layout.is_unsized() {
+                    // FIXME: This should be a span_bug (#80742)
+                    self.tcx.sess.delay_span_bug(
+                        self.frame().current_span(),
+                        &format!("SizeOf nullary MIR operator called for unsized type {}", ty),
+                    );
+                }
```
Comment (RalfJung) [inline compiler/rustc_mir/src/interpret/step.rs:273]: I think we should still abort execution. The result that we return here is wrong. So there should be a new error variant, similar to `TransmuteSizeDiff`, and that should be raised here.

**Comment by RalfJung** [comment]
(Too late, it was rolled up.)

**Comment by oli-obk** [comment]
Either the rollup succeeds, then this can be fixed in a follow up, or it does not, then it can be fixed here

**Comment by osa1** [comment]
I'll submit another PR.

**Comment by osa1** [comment]
https://github.com/rust-lang/rust/pull/81243
