### PR TITLE
Gracefully exit if --keep-stage flag is used on a clean source tree

### LINKED ISSUE #107392: Confusing error message when using `--keep-stage-std` after cleaning
```
./x.py clean
./x.py build --keep-stage-std 0
```

This of course doesn't work, as there is no stage to keep.

but the error message is less than ideal

```
arning: Using a potentially old libstd. This may not behave well.
Copying stage0 library from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
thread 'main' panicked at 'fs::read(stamp) failed with No such file or directory (os error 2) ("/home/nilsh/projects/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/.libstd.stamp")', lib.rs:1435:24
note: run with `RUST_BACKTRACE=1 environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
```

Since the keep-stage was behind an alias that I forgot I used I was quite confused with this, since this seemed like an internal bootstrap error and not a user error on my side.

### PR DESCRIPTION
**Pull request by Teapot4195**
Instead of quitting with an obscure No such file or directory error, give the user a clearer and easier to understand error (as well as suggesting a possible cause for the error).

This is the first time I have written rust since 2020, and the first PR I will ever make to rust, so please do point out any mistakes I have made :smile: .

This fixes #107392

### CODE REVIEW

**Comment by albertlarsan68** [comment]
I am not sure whether to land this, cc #107019 @jyn514 @GentBinaku.
Is there another way of reporting the errors without panicking?

File: src/bootstrap/lib.rs [hunk 1]
```diff
@@ -1431,6 +1431,13 @@ impl Build {
             return Vec::new();
         }
 
+        if !stamp.exists() {
+            panic!(
+                "Could not find stamp file {}, did you try to keep a nonexistent build stage?",
+                stamp.display()
```
Comment (jyn514) [inline src/bootstrap/lib.rs:1437]: This could use eprintln and detail_exit instead.

Comment (Teapot4195) [reply src/bootstrap/lib.rs]: I could only remember println and process::exit, if eprintln and detail_exit is the better option, I'll change it when I get home

Comment (albertlarsan68) [reply src/bootstrap/lib.rs]: `detail_exit` is a custom function located in the root of bootstrap (`lib.rs`), and `eprintln` is a macro like `println`, but prints to stderr instead of stdout.
Also, do not create merge commits, rather [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing) when conflicts occur.

Comment (Teapot4195) [reply src/bootstrap/lib.rs]: My mistake, and it definitely seems like I didn't dig deep enough into ways to error and quit.

Comment (jyn514) [reply src/bootstrap/lib.rs]: no worries :) every codebase has its own custom errors, not a big deal to learn it as you go

**Comment by Teapot4195** [comment]
The no-merge policy got me a little confused, but hopefully these changes should fix the remaining issues :)

**Comment by albertlarsan68** [comment]
Can you squash your commits please?
r=me once squashed and CI passes

**Comment by albertlarsan68** [comment]
Thanks for your PR!
@bors r+

**Comment by Teapot4195** [comment]
oops, think I accidentally deleted the wrong branch
Apologies in advance for whoever has to come back and approve for a second time (if necessary).

File: src/bootstrap/lib.rs [hunk 2]
```diff
@@ -1431,6 +1431,13 @@ impl Build {
             return Vec::new();
         }
 
+        if !stamp.exists() {
+            eprintln!(
+                "Warning: Unable to find the stamp file, did you try to keep a nonexistent build stage?"
+            );
+            crate::detail_exit(1);
```
Comment (jyn514) [inline src/bootstrap/lib.rs:1438]: I have two comments here:
1. This should say "error", not "warning"
2. This should print the file path of the stamp file; currently it's a regression compared to the existing error message.

@Teapot4195 do you think you could make a follow-up PR with both those changes?

Comment (Teapot4195) [reply src/bootstrap/lib.rs:1438]: Yeah, I'll make a follow up PR for those changes

Comment (jyn514) [reply src/bootstrap/lib.rs:1438]: Thank you!
