### PR TITLE
bootstrap: don't apply `-Ztls-model=initial-exec` to proc macros

### LINKED ISSUE #100530: Build failure with `rustc_private` crates on `aarch64-unknown-linux-gnu`
On `aarch64-unknown-linux-gnu`, with a `rustup` provided `rustc-dev` component:

```rust
#![feature(rustc_private)]

extern crate rustc_attr;
```

errors with:

```
error: /home/alex/.rustup/toolchains/nightly-2022-08-14-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libserde_derive-6dc9fea9ed4dba80.so: cannot allocate memory in static TLS block
 --> src/lib.rs:3:1
  |
3 | extern crate rustc_attr;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

I'll try and see if I can reproduce it with `./x.py` to test @bjorn3's suggestion: https://github.com/rust-lang/rust/pull/99944#issuecomment-1214361900

### PR DESCRIPTION
**Pull request by Alexendoo**
Potentially fixes #100530

r? @bjorn3

### CODE REVIEW

File: src/bootstrap/bin/rustc.rs [hunk 1]
```diff
@@ -106,6 +106,10 @@ fn main() {
         {
             cmd.arg("-C").arg("panic=abort");
         }
+
+        if env::var("RUSTC_TLS_MODEL_INITIAL_EXEC").is_ok() {
```
Comment (bjorn3) [inline src/bootstrap/bin/rustc.rs:110]: Once the try build is complete please add a comment explaining that this must not be set for proc macros and that this is the reason it is guarded behind `target.is_some()`. Don't push before the try build is complete though as that may abort the try build.

**Comment by bjorn3** [comment]
If you have `rustup-toolchain-install-master` installed (`cargo install rustup-toolchain-install-master`) you can use `rustup-toolchain-install-master -c rustc-dev b8faa934fa7fcac224925252dcd9884abf34a688` to install it and then `cargo +b8faa934fa7fcac224925252dcd9884abf34a688 build` to build your test project.

**Comment by Alexendoo** [comment]
Ah the try build is x86 linux 😅

Pushed a commit that I believe should make it use aarch64 temporarily

**Comment by Alexendoo** [comment]
No such luck:

```
error: /home/alex/.rustup/toolchains/ad757cfdaf165871015454fd840ff1400125fd79/lib/rustlib/aarch64-unknown-linux-gnu/lib/libserde_derive-6dc9fea9ed4dba80.so: cannot allocate memory in static TLS block
 --> src/lib.rs:3:1
  |
3 | extern crate rustc_attr;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bjorn3** [comment]
Right, `-Zdual-proc-macro` means that the proc macro is compiled a second time for the target. This time -Ztls-model=initial-exec is passed. Could you add a check that the crate type is not proc-macro before adding the argument? This doesn't catch proc macro dependencies, so at least also the proc-macro2 crate needs to have -Ztls-model=initial-exec disabled. For which you need another conditional.

**Comment by Alexendoo** [comment]
Is that what you meant?

My comment is lacking, I don't know enough about proc macros to explain why it's in `target.is_some()`

**Comment by bjorn3** [comment]
> Is that what you meant?

Yes

@bors try

**Comment by Alexendoo** [comment]
There's progress, before the following crates would give the error:

```
rustc_ast_lowering
rustc_ast_passes
rustc_attr
rustc_borrowck
rustc_builtin_macros
rustc_codegen_llvm
rustc_codegen_ssa
rustc_const_eval
rustc_driver
rustc_errors
rustc_expand
rustc_hir_pretty
rustc_hir
rustc_incremental
rustc_infer
rustc_interface
rustc_lint_defs
rustc_lint
rustc_metadata
rustc_middle
rustc_mir_build
rustc_mir_dataflow
rustc_mir_transform
rustc_monomorphize
rustc_parse
rustc_passes
rustc_plugin_impl
rustc_privacy
rustc_query_impl
rustc_query_system
rustc_resolve
rustc_save_analysis
rustc_session
rustc_smir
rustc_symbol_mangling
rustc_target
rustc_trait_selection
rustc_traits
rustc_transmute
rustc_ty_utils
rustc_typeck
```

On 5618bbd2f9cff002b70877eb50368991de5e4ab7 there are fewer:

```
rustc_ast_lowering
rustc_borrowck
rustc_codegen_llvm
rustc_codegen_ssa
rustc_const_eval
rustc_driver
rustc_incremental
rustc_infer
rustc_interface
rustc_lint
rustc_metadata
rustc_middle
rustc_mir_build
rustc_mir_dataflow
rustc_mir_transform
rustc_monomorphize
rustc_passes
rustc_plugin_impl
rustc_privacy
rustc_query_impl
rustc_resolve
rustc_save_analysis
rustc_smir
rustc_symbol_mangling
rustc_trait_selection
rustc_traits
rustc_transmute
rustc_ty_utils
rustc_typeck
```

**Comment by bjorn3** [comment]
What is the exact error in those cases?

**Comment by Alexendoo** [comment]
```
error: /home/alex/.rustup/toolchains/5618bbd2f9cff002b70877eb50368991de5e4ab7/lib/rustlib/aarch64-unknown-linux-gnu/lib/libchalk_derive-8ea0a51673aa1739.so: cannot allocate memory in static TLS block
 --> src/lib.rs:3:1
  |
3 | extern crate rustc_ast_lowering;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bjorn3** [comment]
chalk_derive depends on quote, syn and synstructure. I don't know which one is responsible, but adding all of them as exceptions just like proc-macro2 would work I think.

**Comment by Alexendoo** [comment]
Nice, that one compiled successfully! Thanks for walking me through it

rebased + removed the ci try change

**Comment by bjorn3** [comment]
LGTM, but given that I suggested this fix, I'm going to defer final review to someone else.

r? @Mark-Simulacrum You also reviewed https://github.com/rust-lang/rust/pull/78201. Would you mind taking a look?

File: src/bootstrap/bin/rustc.rs [hunk 2]
```diff
@@ -106,6 +106,15 @@ fn main() {
         {
             cmd.arg("-C").arg("panic=abort");
         }
+
+        // `-Ztls-model=initial-exec` must not be applied to proc-macros, see
+        // issue https://github.com/rust-lang/rust/issues/100530
+        if env::var("RUSTC_TLS_MODEL_INITIAL_EXEC").is_ok()
+            && arg("--crate-type") != Some("proc-macro")
+            && !matches!(crate_name, Some("proc_macro2" | "quote" | "syn" | "synstructure"))
```
Comment (Mark-Simulacrum) [inline src/bootstrap/bin/rustc.rs:114]: Is there a test or something else we can add that validates this list is enough? For example, I'm thinking that maybe our invocations of cargo metadata can help here?

I don't think this is something we should do in rustc.rs, probably too much overhead, but some kind of out of band check seems like a good idea to me.

Comment (Mark-Simulacrum) [reply src/bootstrap/bin/rustc.rs:114]: I guess the actual set is something like proc macros dep *and* contains TLS symbols, or so?

For example, rustc_macros depends on multiple other crates:

https://github.com/rust-lang/rust/blob/master/compiler/rustc_macros/Cargo.toml#L10

Comment (bjorn3) [reply src/bootstrap/bin/rustc.rs:114]: > I guess the actual set is something like proc macros dep and contains TLS symbols, or so?

Yes, although a blanket include of all proc macro deps would be correct though. It may just cause a perf regression.

Comment (Mark-Simulacrum) [reply src/bootstrap/bin/rustc.rs:114]: I think we should try it; my guess is that TLS access for these crates isn't hot (even at runtime if they're pulled in there).

Or we can go a different direction and try to test this, but it sounds like doing that isn't trivial?

Comment (bjorn3) [reply src/bootstrap/bin/rustc.rs:114]: I think checking all proc macro dylibs shipped with rustc-dev for the R_X86_64_TPOFF64 relocation kind (on x86_64, aarch64 has a different relocation name) would suffice. R_X86_64_DTPOFF64 is the only TLS relocation kind that is used for the global dynamic tls model (the most general tls model) I think.

Comment (Alexendoo) [reply src/bootstrap/bin/rustc.rs:114]: The difference before/after appears to be R_AARCH64_TLS_TPREL64

Is there a nice way to get a list of the proc macro dylibs in a `run-make-fulldeps` test? (or a better way to test for that)

Comment (bjorn3) [reply src/bootstrap/bin/rustc.rs:114]: Not sure.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

I think let's land this for now, we'll keep https://github.com/rust-lang/rust/issues/92976 open (I'll leave a comment there) that we should add testing for this since the current solution is easy to regress on in the future.
