### PR TITLE
Fix ICE on empty file with -Zquery-dep-graph

### LINKED ISSUE #153199: [ICE]: -Zquery-dep-graph on empty file
### Code

```Rust
```
note: an empty file  aka `touch code.rs` is sufficient to repro, which makes probably makes this the new contender for the shortest mvce, after https://github.com/rust-lang/rust/issues/151882

### Meta

`rustc --version --verbose`:
```
rustc 1.95.0-nightly (6a979b3e3 2026-02-26)
binary: rustc
commit-hash: 6a979b3e32522049d0acb4a47f7ae44b7c8abfd5
commit-date: 2026-02-26
host: x86_64-unknown-linux-gnu
release: 1.95.0-nightly
LLVM version: 22.1.0
```

### Error output

```
<output>
```

`rustc code.rs  -Zquery-dep-graph --crate-type lib`

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' (1650192) panicked at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/dep_graph/graph.rs:829:50:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f8d28f2fe90 - std[4fa2659a0af85798]::backtrace_rs::backtrace::libunwind::trace
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x7f8d28f2fe90 - std[4fa2659a0af85798]::backtrace_rs::backtrace::trace_unsynchronized::<std[4fa2659a0af85798]::sys::backtrace::_print_fmt::{closure#1}>
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x7f8d28f2fe90 - std[4fa2659a0af85798]::sys::backtrace::_print_fmt
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/backtrace.rs:74:9
   3:     0x7f8d28f2fe90 - <<std[4fa2659a0af85798]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[c91b42e26cf70057]::fmt::Display>::fmt
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/backtrace.rs:44:26
   4:     0x7f8d2451478e - <core[c91b42e26cf70057]::fmt::rt::Argument>::fmt
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/fmt/rt.rs:152:76
   5:     0x7f8d2451478e - core[c91b42e26cf70057]::fmt::write
   6:     0x7f8d28f47fbc - std[4fa2659a0af85798]::io::default_write_fmt::<std[4fa2659a0af85798]::sys::stdio::unix::Stderr>
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/io/mod.rs:639:11
   7:     0x7f8d28f47fbc - <std[4fa2659a0af85798]::sys::stdio::unix::Stderr as std[4fa2659a0af85798]::io::Write>::write_fmt
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/io/mod.rs:1994:13
   8:     0x7f8d28ef4986 - <std[4fa2659a0af85798]::sys::backtrace::BacktraceLock>::print
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/backtrace.rs:47:9
   9:     0x7f8d28ef4986 - std[4fa2659a0af85798]::panicking::default_hook::{closure#0}
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:292:27
  10:     0x7f8d28f1eb71 - std[4fa2659a0af85798]::panicking::default_hook
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:319:9
  11:     0x7f8d2593f5e6 - <alloc[aa6fb67952f484d9]::boxed::Box<dyn for<'a, 'b> core[c91b42e26cf70057]::ops::function::Fn<(&'a std[4fa2659a0af85798]::panic::PanicHookInfo<'b>,), Output = ()> + core[c91b42e26cf70057]::marker::Send + core[c91b42e26cf70057]::marker::Sync> as core[c91b42e26cf70057]::ops::function::Fn<(&std[4fa2659a0af85798]::panic::PanicHookInfo,)>>::call
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/alloc/src/boxed.rs:2254:9
  12:     0x7f8d2593f5e6 - rustc_driver_impl[4d5ee4e1eb20a008]::install_ice_hook::{closure#1}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_driver_impl/src/lib.rs:1477:17
  13:     0x7f8d2593f5e6 - <alloc[aa6fb67952f484d9]::boxed::Box<rustc_driver_impl[4d5ee4e1eb20a008]::install_ice_hook::{closure#1}> as core[c91b42e26cf70057]::ops::function::Fn<(&dyn for<'a, 'b> core[c91b42e26cf70057]::ops::function::Fn<(&'a std[4fa2659a0af85798]::panic::PanicHookInfo<'b>,), Output = ()> + core[c91b42e26cf70057]::marker::Send + core[c91b42e26cf70057]::marker::Sync, &std[4fa2659a0af85798]::panic::PanicHookInfo)>>::call
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/alloc/src/boxed.rs:2254:9
  14:     0x7f8d2593f5e6 - std[4fa2659a0af85798]::panicking::update_hook::<alloc[aa6fb67952f484d9]::boxed::Box<rustc_driver_impl[4d5ee4e1eb20a008]::install_ice_hook::{closure#1}>>::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:235:47
  15:     0x7f8d28f1ef0a - <alloc[aa6fb67952f484d9]::boxed::Box<dyn for<'a, 'b> core[c91b42e26cf70057]::ops::function::Fn<(&'a std[4fa2659a0af85798]::panic::PanicHookInfo<'b>,), Output = ()> + core[c91b42e26cf70057]::marker::Send + core[c91b42e26cf70057]::marker::Sync> as core[c91b42e26cf70057]::ops::function::Fn<(&std[4fa2659a0af85798]::panic::PanicHookInfo,)>>::call
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/alloc/src/boxed.rs:2254:9
  16:     0x7f8d28f1ef0a - std[4fa2659a0af85798]::panicking::panic_with_hook
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:833:13
  17:     0x7f8d28ef4a7a - std[4fa2659a0af85798]::panicking::panic_handler::{closure#0}
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:691:13
  18:     0x7f8d28ee37f9 - std[4fa2659a0af85798]::sys::backtrace::__rust_end_short_backtrace::<std[4fa2659a0af85798]::panicking::panic_handler::{closure#0}, !>
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/backtrace.rs:182:18
  19:     0x7f8d28ef699d - __rustc[8af5c0f5c54b39df]::rust_begin_unwind
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:689:5
  20:     0x7f8d2451548c - core[c91b42e26cf70057]::panicking::panic_fmt
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/panicking.rs:80:14
  21:     0x7f8d24515452 - core[c91b42e26cf70057]::panicking::panic
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/panicking.rs:150:5
  22:     0x7f8d24515119 - core[c91b42e26cf70057]::option::unwrap_failed
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/option.rs:2236:5
  23:     0x7f8d26eed80c - <core[c91b42e26cf70057]::option::Option<&alloc[aa6fb67952f484d9]::sync::Arc<rustc_middle[fa34477ad0026556]::dep_graph::graph::DepGraphData>>>::unwrap
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/option.rs:1016:21
  24:     0x7f8d26eed80c - <rustc_middle[fa34477ad0026556]::dep_graph::graph::DepGraph>::register_dep_node_debug_str::<<rustc_middle[fa34477ad0026556]::dep_graph::dep_node::DepNode>::construct<rustc_span[7ac8ec4c7617faaf]::symbol::Symbol>::{closure#0}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/dep_graph/graph.rs:829:50
  25:     0x7f8d26eed80c - <rustc_middle[fa34477ad0026556]::dep_graph::dep_node::DepNode>::construct::<rustc_span[7ac8ec4c7617faaf]::symbol::Symbol>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/dep_graph/dep_node.rs:128:31
  26:     0x7f8d26eed80c - rustc_middle[fa34477ad0026556]::dep_graph::dep_node::make_compile_codegen_unit
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/dep_graph/dep_node.rs:348:5
  27:     0x7f8d26eed80c - <rustc_middle[fa34477ad0026556]::mir::mono::CodegenUnit>::codegen_dep_node
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/mir/mono.rs:580:9
  28:     0x7f8d2536b6f0 - rustc_codegen_llvm[f4165f4edf18f80]::base::compile_codegen_unit
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_codegen_llvm/src/base.rs:64:47
  29:     0x7f8d2536b6f0 - <rustc_codegen_llvm[f4165f4edf18f80]::LlvmCodegenBackend as rustc_codegen_ssa[24069b9056e1604f]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_codegen_llvm/src/lib.rs:123:9
  30:     0x7f8d25208272 - rustc_codegen_ssa[24069b9056e1604f]::base::codegen_crate::<rustc_codegen_llvm[f4165f4edf18f80]::LlvmCodegenBackend>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_codegen_ssa/src/base.rs:806:42
  31:     0x7f8d253a122a - <rustc_codegen_llvm[f4165f4edf18f80]::LlvmCodegenBackend as rustc_codegen_ssa[24069b9056e1604f]::traits::backend::CodegenBackend>::codegen_crate
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_codegen_llvm/src/lib.rs:364:18
  32:     0x7f8d2680d9f9 - rustc_interface[ad942d09ea256eed]::passes::start_codegen::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/passes.rs:1236:29
  33:     0x7f8d2680d9f9 - <rustc_data_structures[5b55a0b3966dedd9]::profiling::VerboseTimingGuard>::run::<alloc[aa6fb67952f484d9]::boxed::Box<dyn core[c91b42e26cf70057]::any::Any>, rustc_interface[ad942d09ea256eed]::passes::start_codegen::{closure#0}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_data_structures/src/profiling.rs:845:9
  34:     0x7f8d2680d9f9 - <rustc_session[c9d23ba95e4923e]::session::Session>::time::<alloc[aa6fb67952f484d9]::boxed::Box<dyn core[c91b42e26cf70057]::any::Any>, rustc_interface[ad942d09ea256eed]::passes::start_codegen::{closure#0}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_session/src/utils.rs:17:50
  35:     0x7f8d2680d9f9 - rustc_interface[ad942d09ea256eed]::passes::start_codegen
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/passes.rs:1224:28
  36:     0x7f8d2680d9f9 - <rustc_interface[ad942d09ea256eed]::queries::Linker>::codegen_and_build_linker
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/queries.rs:33:43
  37:     0x7f8d258cb82b - rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_driver_impl/src/lib.rs:341:18
  38:     0x7f8d258cb82b - rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt::<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/passes.rs:1004:23
  39:     0x7f8d258cb82b - <rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter::<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#1}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/ty/context.rs:859:37
  40:     0x7f8d258cb82b - rustc_middle[fa34477ad0026556]::ty::context::tls::enter_context::<<rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#1}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/ty/context/tls.rs:59:9
  41:     0x7f8d258cb82b - <std[4fa2659a0af85798]::thread::local::LocalKey<core[c91b42e26cf70057]::cell::Cell<*const ()>>>::try_with::<rustc_middle[fa34477ad0026556]::ty::context::tls::enter_context<<rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#1}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#0}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/thread/local.rs:513:12
  42:     0x7f8d258cb82b - <std[4fa2659a0af85798]::thread::local::LocalKey<core[c91b42e26cf70057]::cell::Cell<*const ()>>>::with::<rustc_middle[fa34477ad0026556]::ty::context::tls::enter_context<<rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#1}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#0}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/thread/local.rs:477:20
  43:     0x7f8d258cb82b - rustc_middle[fa34477ad0026556]::ty::context::tls::enter_context::<<rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>::{closure#1}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  44:     0x7f8d258cb82b - <rustc_middle[fa34477ad0026556]::ty::context::GlobalCtxt>::enter::<rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/ty/context.rs:859:9
  45:     0x7f8d258cb82b - <rustc_middle[fa34477ad0026556]::ty::context::TyCtxt>::create_global_ctxt::<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>::{closure#2}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_middle/src/ty/context.rs:1068:13
  46:     0x7f8d258cb82b - rustc_interface[ad942d09ea256eed]::passes::create_and_enter_global_ctxt::<core[c91b42e26cf70057]::option::Option<rustc_interface[ad942d09ea256eed]::queries::Linker>, rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}::{closure#2}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/passes.rs:971:5
  47:     0x7f8d259455cc - rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_driver_impl/src/lib.rs:298:22
  48:     0x7f8d259455cc - rustc_interface[ad942d09ea256eed]::interface::run_compiler::<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/interface.rs:500:80
  49:     0x7f8d259455cc - <core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}::{closure#0}> as core[c91b42e26cf70057]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/panic/unwind_safe.rs:274:9
  50:     0x7f8d259455cc - std[4fa2659a0af85798]::panicking::catch_unwind::do_call::<core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:581:40
  51:     0x7f8d259455cc - std[4fa2659a0af85798]::panicking::catch_unwind::<(), core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:544:19
  52:     0x7f8d259455cc - std[4fa2659a0af85798]::panic::catch_unwind::<core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panic.rs:359:14
  53:     0x7f8d259455cc - rustc_interface[ad942d09ea256eed]::interface::run_compiler::<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/interface.rs:500:23
  54:     0x7f8d2592a545 - rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals::<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/util.rs:204:17
  55:     0x7f8d2592a545 - rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/util.rs:159:24
  56:     0x7f8d2592a545 - <scoped_tls[8e25910049addad8]::ScopedKey<rustc_span[7ac8ec4c7617faaf]::SessionGlobals>>::set::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>
                               at /rust/deps/scoped-tls-1.0.1/src/lib.rs:137:9
  57:     0x7f8d2592a545 - rustc_span[7ac8ec4c7617faaf]::create_session_globals_then::<(), rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_span/src/lib.rs:141:21
  58:     0x7f8d2592a545 - rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/compiler/rustc_interface/src/util.rs:155:17
  59:     0x7f8d2592a545 - std[4fa2659a0af85798]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/backtrace.rs:166:18
  60:     0x7f8d25949ac3 - std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/thread/lifecycle.rs:91:13
  61:     0x7f8d25949ac3 - <core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}> as core[c91b42e26cf70057]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/panic/unwind_safe.rs:274:9
  62:     0x7f8d25949ac3 - std[4fa2659a0af85798]::panicking::catch_unwind::do_call::<core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:581:40
  63:     0x7f8d25949ac3 - std[4fa2659a0af85798]::panicking::catch_unwind::<(), core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panicking.rs:544:19
  64:     0x7f8d25949ac3 - std[4fa2659a0af85798]::panic::catch_unwind::<core[c91b42e26cf70057]::panic::unwind_safe::AssertUnwindSafe<std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/panic.rs:359:14
  65:     0x7f8d25949ac3 - std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked::<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/thread/lifecycle.rs:89:26
  66:     0x7f8d25949ac3 - <std[4fa2659a0af85798]::thread::lifecycle::spawn_unchecked<rustc_interface[ad942d09ea256eed]::util::run_in_thread_with_globals<rustc_interface[ad942d09ea256eed]::util::run_in_thread_pool_with_globals<rustc_interface[ad942d09ea256eed]::interface::run_compiler<(), rustc_driver_impl[4d5ee4e1eb20a008]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[c91b42e26cf70057]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc-dev/3a70d0349fa378a10c3748f1a48742e61505020f/library/core/src/ops/function.rs:250:5
  67:     0x7f8d28f2cd0f - <alloc[aa6fb67952f484d9]::boxed::Box<dyn core[c91b42e26cf70057]::ops::function::FnOnce<(), Output = ()> + core[c91b42e26cf70057]::marker::Send> as core[c91b42e26cf70057]::ops::function::FnOnce<()>>::call_once
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/alloc/src/boxed.rs:2240:9
  68:     0x7f8d28f2cd0f - <std[4fa2659a0af85798]::sys::thread::unix::Thread>::new::thread_start
                               at /rustc/3a70d0349fa378a10c3748f1a48742e61505020f/library/std/src/sys/thread/unix.rs:118:17
  69:     0x7f8d22ca598b - <unknown>
  70:     0x7f8d22d29a0c - <unknown>
  71:                0x0 - <unknown>

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im/rustc-ice-2026-02-27T20_58_17-1650190.txt` to your bug report

note: rustc 1.95.0-nightly (3a70d0349 2026-02-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z query-dep-graph --crate-type lib

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Delta17920**
added a guard in `DepGraph::register_dep_node_debug_str` so it early-returns 
when `self.data` is still `None`. this happens for the first few dep-nodes 
in an empty crate with `-Z query-dep-graph`, which caused the previous 
`unwrap()` panic.

fixes rust-lang/rust#153199

### CODE REVIEW

File: tests/ui/dep-graph/query-dep-graph-empty.rs [hunk 1]
```diff
@@ -0,0 +1,7 @@
+//@ build-pass
+//@ compile-flags: -Zquery-dep-graph --crate-type lib
+//@ edition: 2021
+
+// This file is intentionally left empty to reproduce issue #153199.
+// rustc used to ICE when generating a dependency graph for an empty file
+// because of a duplicate DepNode registration hitting a debug_assert.
```
Comment (lqd) [inline tests/ui/dep-graph/query-dep-graph-empty.rs]: > because of a duplicate DepNode registration

interestingly, this doesn't match the added code comment, so is it accurate?

Comment (Delta17920) [reply tests/ui/dep-graph/query-dep-graph-empty.rs]: good catch! that's a leftover from my initial guess. i pushed as soon as the test passed and forgot to update it. 
**UPDATED**
