### PR TITLE
show linker output even if the linker succeeds

### LINKED ISSUE #38206: `rustc -v` should print out linker output
If I compile something with `rustc -v`, it doesn't show the linker invocations or anything else:

```
$ echo "fn main() {}" > t.rs
$ rustc -v --crate-type bin t.rs
$ ls -l t
-rwxr-xr-x. 1 jsgf users 2052670 Dec  6 17:15 t
```

### LINKED ISSUE #83436: rustc hides linker warnings
I encountered an issue with the [linkme](https://github.com/dtolnay/linkme) crate on illumos (OpenSolaris/OmniOS/Helios) demonstrated with [this repo](https://github.com/ahl/linkme-test). Of note, the build executes without error or warning, but in fact the linker is emitting an error:

```
$ cargo run
   Compiling cmd v0.1.0 (/home/ahl/linkme-test/cmd)
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/cmd`
$ cargo rustc
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

I can make the linker fail on warnings:

```
$ cargo rustc -- -C link-arg=-Wl,-zfatal-warnings
   Compiling cmd v0.1.0 (/home/ahl/linkme-test/cmd)
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-m64" "-std=c99" "-L" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.1m65hci6o5zni2mr.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.1r2sofzghiioxykg.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.2i3xjlynwxgqlmzu.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.3hvsf4zj59kihrhf.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.3lsh1pzemq0xblzm.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.3zpatajw7m7uqqns.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.4yxic0y84aboqmeb.rcgu.o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.a1lfmxsp6lqzsbn.rcgu.o" "-o" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69" "/home/ahl/linkme-test/cmd/target/debug/deps/cmd-26e8351dc3f3fb69.3n70o9wfzqm9tbsh.rcgu.o" "-Wl,-zignore" "-nodefaultlibs" "-L" "/home/ahl/linkme-test/cmd/target/debug/deps" "-L" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib" "-Wl,-Bstatic" "/home/ahl/linkme-test/cmd/target/debug/deps/liblib-3d689bd64c3873d5.rlib" "/home/ahl/linkme-test/cmd/target/debug/deps/liblinkme-21c998585e123796.rlib" "-Wl,--start-group" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libstd-cd23cc7e75a2851c.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libpanic_unwind-566bad254d0594e5.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libminiz_oxide-96e54319d1590148.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libadler-4dbe2335326bb316.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libobject-b0fd875741b20fc0.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libaddr2line-089ce7b4c263282a.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libgimli-ca92a564b7883a12.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/librustc_demangle-ce8ee413f3ea18b6.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libhashbrown-17e15682bef35ec2.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/librustc_std_workspace_alloc-2dc950a425ee77d8.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libunwind-50867a64287c1bd2.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libcfg_if-129bada4e936c5a0.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/liblibc-a98e4fa0f203a39a.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/liballoc-35c480f88f8f320a.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/librustc_std_workspace_core-86dc76527c7e216a.rlib" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libcore-093275d7382c1a2f.rlib" "-Wl,--end-group" "/opt/ooce/rust/lib/rustlib/x86_64-unknown-illumos/lib/libcompiler_builtins-358913705748e96c.rlib" "-Wl,-Bdynamic" "-lsocket" "-lposix4" "-lpthread" "-lresolv" "-lnsl" "-lumem" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-Wl,-zfatal-warnings" "-lssp"
  = note: ld: warning: reserved symbol '__start_set_linkme_DOERS' already defined in file /home/ahl/linkme-test/cmd/target/debug/deps/liblib-3d689bd64c3873d5.rlib(lib-3d689bd64c3873d5.2vwi8dtk7ky9hvmq.rcgu.o)
          ld: warning: reserved symbol '__stop_set_linkme_DOERS' already defined in file /home/ahl/linkme-test/cmd/target/debug/deps/liblib-3d689bd64c3873d5.rlib(lib-3d689bd64c3873d5.2vwi8dtk7ky9hvmq.rcgu.o)
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `cmd`.

To learn more, run the command again with --verbose.
```

These linker warnings need not have been fatal, but I think it would be reasonable for `cargo build` / `cargo run` / `cargo rustc` to display these warnings. In this case those warnings would have helped determine the underlying issues much earlier. Indeed, it seems rare that linker warnings would truly be specious.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.47.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-illumos
release: 1.47.0
LLVM version: 11.0
```

### PR DESCRIPTION
**Pull request by jyn514**
Show stderr and stderr by default, controlled by a new `linker_messages` lint.

fixes https://github.com/rust-lang/rust/issues/83436. fixes https://github.com/rust-lang/rust/issues/38206. cc https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/uplift.20some.20-Zverbose.20calls.20and.20rename.20to.E2.80.A6.20compiler-team.23706/near/408986134

try-job: aarch64-apple

r? @bjorn3

### CODE REVIEW

**Comment by jyn514** [comment]
hmm actually this is a slight expansion of scope but @bjorn3 how would you feel about not printing the giant list of linker arguments unless someone passes `--verbose` (https://github.com/rust-lang/rust/issues/109979)

**Comment by jyn514** [comment]
also i know we settled on not showing stdout by default but it's useful for debugging search paths - maybe we should show it after all? it seems silly to have to pass both `-Wl,--verbose` and `--verbose`. https://github.com/rust-lang/rust/issues/46998#issuecomment-1868638316

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 1]
```diff
@@ -721,6 +721,15 @@ fn link_dwarf_object<'a>(
     }
 }
 
+#[derive(Diagnostic)]
+#[diag(codegen_ssa_linker_output)]
+/// Translating this is kind of useless. We don't pass translation flags to the linker, so we'd just
+/// end up with inconsistent languages within the same diagnostic. Ideally we'd accept strings in
+/// `emit_warning`, but I didn't feel like doing that much of a refactor.
```
Comment (Nilstrieb) [inline compiler/rustc_codegen_ssa/src/back/link.rs:728]: No, the fact that doing this is annoying is good, if we accepted strings there we'd just be back at untranslatable diagnostics. Having to do this explicit hack for something I expect to show up very rarely seems like a good thing, so I'd prefer removing the last sentence :)

File: compiler/rustc_interface/src/tests.rs [hunk 2]
```diff
@@ -714,7 +714,7 @@ fn test_unstable_options_tracking_hash() {
     untracked!(unpretty, Some("expanded".to_string()));
     untracked!(unstable_options, true);
     untracked!(validate_mir, true);
-    untracked!(verbose, true);
+    untracked!(verbose_internals, true);
```
Comment (bjorn3) [inline compiler/rustc_interface/src/tests.rs:717]: Don't diagnostics influenced by this flag end up in the incr cache? It should actually be tracked I think.

File: compiler/rustc_session/src/options.rs [hunk 3]
```diff
@@ -223,6 +223,8 @@ top_level_options!(
         /// The (potentially remapped) working directory
         working_dir: RealFileName [TRACKED],
         color: ColorConfig [UNTRACKED],
+
+        verbose: bool [UNTRACKED],
```
Comment (bjorn3) [inline compiler/rustc_session/src/options.rs:227]: Same here. `TRACKED_NO_CRATE_HASH` should be enough here I think.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 4]
```diff
@@ -972,8 +981,22 @@ fn link_natively<'a>(
 
                 sess.abort_if_errors();
             }
-            info!("linker stderr:\n{}", escape_string(&prog.stderr));
-            info!("linker stdout:\n{}", escape_string(&prog.stdout));
+
+            if !prog.stderr.is_empty() {
+                // We already print `warning:` at the start of the diagnostic. Remove it from the linker output if present.
+                let stderr = escape_string(&prog.stderr);
+                debug!("original stderr: {stderr}");
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/link.rs:988]: `debug!()` can't be enabled for the shipped binaries AFAIK. I think this should be kept `info!()`.

File: compiler/rustc_interface/src/tests.rs (hunk 2 above)
Comment (jyn514) [reply compiler/rustc_interface/src/tests.rs:717]: hmm, do we cache diagnostic *output*? even on errors? that seems very strange to me.

i don't mind changing it to tracked, i'm just confused why it's necessary.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 4 above)
Comment (jyn514) [reply compiler/rustc_codegen_ssa/src/back/link.rs:988]: hmm, do you expect the `warning:` stripping to be incorrect? that's the only case when the `debug` output would be different from the warning diagnostic.

File: compiler/rustc_interface/src/tests.rs (hunk 2 above)
Comment (bjorn3) [reply compiler/rustc_interface/src/tests.rs:717]: On errors we don't finalize the incr comp cache, but non-fatal diagnostics are cached afaik. Otherwise we would have to replay the query in question, which we may not be able to do if the query key is not reconstructible from the dep node fingerprint.

File: compiler/rustc_codegen_ssa/src/back/link.rs (hunk 4 above)
Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/link.rs:987]: I guess it is fine to leave as is.

**Comment by jyn514** [comment]
hmm. that test has the following comment: https://github.com/rust-lang/rust/blob/e9a009fd1a9ce00ee07eeb17bc8e9985815a1296/tests/incremental/commandline-args.rs#L13-L20
i suppose those lines are all invalid now, it should be testing that the CGU is *not* reused? i'm not sure why it's testing `--verbose` specifically, maybe it's enough to test any untracked CLI arg. i'll change it to --diagnostic-width.

i'm realizing your comments are all about https://github.com/rust-lang/rust/pull/119129. i feel slightly uncomfortable making unrelated changes in this PR ... how do you feel about splitting them into a separate PR so i can assign michaelwoerister?

**Comment by bjorn3** [comment]
> how do you feel about splitting them into a separate PR so i can assign michaelwoerister?

Sure

**Comment by bjorn3** [comment]
> hide the linker cli args unless --verbose is passed

I prefer not doing this. It is helpful whenever a linkage issue is opened to not have to ask to rerun with `RUSTFLAGS="--verbose"`. If you revert this change r=me. If you still want to keep it, let me thing about it for a bit.

**Comment by compiler-errors** [comment]
This might've caused a rollup failure here: https://github.com/rust-lang/rust/pull/120359#issuecomment-1911360818

but a lack of rust-log-analyzer comment, i'll just mark this rollup=never so it fails on its own, rather than r-'ing it.

@bors rollup=never

**Comment by compiler-errors** [comment]
Actually nvm, here's the test failure:

```
2024-01-26T03:16:45.5341990Z command: RUSTC_ICE="0" "/Users/runner/work/rust/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "/Users/runner/work/rust/rust/tests/ui/zero-sized/zero-sized-btreemap-insert.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/Users/runner/.cargo" "--sysroot" "/Users/runner/work/rust/rust/build/x86_64-apple-darwin/stage2" "--target=x86_64-apple-darwin" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/ui/zero-sized/zero-sized-btreemap-insert/a" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/Users/runner/work/rust/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "-L" "/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/ui/zero-sized/zero-sized-btreemap-insert/auxiliary"
2024-01-26T03:16:45.5342230Z stdout: none
2024-01-26T03:16:45.5342580Z --- stderr -------------------------------
2024-01-26T03:16:45.5343990Z warning: linker stderr: ld: directory not found for option '-L/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/ui/zero-sized/zero-sized-btreemap-insert/auxiliary'
2024-01-26T03:16:45.5344000Z 
2024-01-26T03:16:45.5344180Z warning: 1 warning emitted
2024-01-26T03:16:45.5344400Z ------------------------------------------
2024-01-26T03:16:45.5344410Z 
2024-01-26T03:16:45.5344420Z 
2024-01-26T03:16:45.5344780Z ---- [ui] tests/ui/wrong-hashset-issue-42918.rs stdout ----
2024-01-26T03:16:45.5344950Z normalized stderr:
2024-01-26T03:16:45.5345780Z warning: linker stderr: ld: directory not found for option '-L$TEST_BUILD_DIR/wrong-hashset-issue-42918/auxiliary'
2024-01-26T03:16:45.5345800Z 
2024-01-26T03:16:45.5345970Z warning: 1 warning emitted
2024-01-26T03:16:45.5345980Z 
2024-01-26T03:16:45.5345990Z 
2024-01-26T03:16:45.5345990Z 
2024-01-26T03:16:45.5346010Z 
2024-01-26T03:16:45.5346290Z The actual stderr differed from the expected stderr.
2024-01-26T03:16:45.5347460Z Actual stderr saved to /Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/ui/wrong-hashset-issue-42918/wrong-hashset-issue-42918.stderr
2024-01-26T03:16:45.5347910Z To update references, rerun the tests and pass the `--bless` flag
2024-01-26T03:16:45.5348520Z To only update this specific test, also pass `--test-args wrong-hashset-issue-42918.rs`
2024-01-26T03:16:45.5348530Z 
2024-01-26T03:16:45.5348760Z error: 1 errors occurred comparing output.
```

@bors r-

**Comment by jyn514** [comment]
this should be marked rollup=iffy; there are likely going to be warnings on other platforms that were silenced before.

**Comment by jyn514** [comment]
lol what on earth
AFAICT there are two types of warnings:
1. ```
warning: linker stderr: Warning: .drectve `-exclude-symbols:_ZN17compiler_builtins3mem6memcpy17h33c7778f71cce9faE ' unrecognized
           Warning: .drectve `-exclude-symbols:_ZN17compiler_builtins3mem7memmove17ha30886041cd704b7E ' unrecognized
```
2. ```
2024-01-30T23:15:45.4590600Z ---- [ui] tests\ui\array-slice-vec\nested-vec-1.rs stdout ----
2024-01-30T23:15:45.4591032Z normalized stderr:
2024-01-30T23:15:45.4591439Z warning: linker stderr: Warning: corrupt .drectve at end of def file
```
the first one looks like https://github.com/rust-lang/rust/issues/112368, probably? that's related to an old linker version, i'm not sure what version we're using in CI.
the second one is what's actually causing tests to fail and i don't have ideas for fixing it. maybe @mati865 knows.

anyway i'm probably not going to put much more time into this pr

**Comment by mati865** [comment]
> the first one looks like #112368, probably? that's related to an old linker version, i'm not sure what version we're using in CI.

Because getting a newer one is not a trivial task ;)
https://github.com/rust-lang/rust/pull/119229

> the second one is what's actually causing tests to fail and i don't have ideas for fixing it

Oh, that's strange. In the past, Rust used `.def` files only to let the linker know which symbols to export. Maybe something has changed (likely accidentally), but we'd need to dump that file and see its contents.

**Comment by nikic** [comment]
@bors r-

Probably someone clicked the synchronize button.

**Comment by jyn514** [comment]
i am not planning to work on this more, someone else can pick it up if they care

**Comment by jyn514** [comment]
> I think this is #112368 As I understand it, LLVM emits a correct `.drectve` section with linker arguments, but the GNU linker incorrectly fails to parse the section and emits a warning.

oh cool. apparently this is fixed in ld 2.40. i have 2.39 locally, https://github.com/rust-lang/rust/pull/119229/ looks like it uses 2.42. so hopefully this will be unblocked soon.

**Comment by jyn514** [comment]
oh lol i only cherry-picked the last commit of #119229 not the whole pr whoops

**Comment by jyn514** [comment]
yay tests are finally passing

this is blocked on #119229 (but it also ran tests for that PR, so it's probably going to merge soon) and then we can see if there are any other targets that are going to break

@rustbot label S-blocked

**Comment by workingjubilee** [comment]
Probably should go from iffy to
@bors rollup=never

**Comment by jyn514** [comment]
so. uh. does anyone know how i can test rustc on a mac lol

i do not own any apple laptop

**Comment by jieyouxu** [comment]
> so. uh. does anyone know how i can test rustc on a mac lol
> 
> i do not own any apple laptop

Does aarch64 or x84_64 apple try jobs work for your purpose?

**Comment by jieyouxu** [comment]
Dear apple target experts, could you take a look at the linker failures and hopefully help us figure out how we can fix them? This PR is trying to change what linker output is displayed and when.

@rustbot ping apple

**Comment by bjorn3** [comment]
All compiler_builtins symbols are marked as hidden. I wonder if the logic that determines the contents of the version script accidentally still mentions these hidden symbols as exported.

**Comment by jyn514** [comment]
oh sorry i didn't realize @jieyouxu was going to ping or i would have said what's going on

the compiler_builtins errors are annoying but not actually causing test failures. the actual failure is this:
```
---- [ui] tests/ui/linkage-attr/framework.rs#omit stdout ----
diff of stderr:

1 error: linking with `LINKER` failed: exit status: 1
2    |
-            ld: Undefined symbols:
4              _CFRunLoopGetTypeID, referenced from:
5            clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
i am not sure how to interpret that; it looks to me like the `ld:` line has disappeared altogether, which doesn't make much sense. i think compiletest is normalizing part of the diff away and i would like to see the original .stderr file, but i don't know how to get it out of the CI runner.

**Comment by jieyouxu** [comment]
> i am not sure how to interpret that; it looks to me like the `ld:` line has disappeared altogether, which doesn't make much sense. i think compiletest is normalizing part of the diff away and i would like to see the original .stderr file, but i don't know how to get it out of the CI runner.

I think the "full" stderr (whatever is given to compiletest) is immediately below,

```
--- stderr -------------------------------
error: linking with `cc` failed: exit status: 1
  |
  = note: use `--verbose` to show all linker arguments
  = note: Undefined symbols for architecture arm64:
    "_CFRunLoopGetTypeID", referenced from: framework::main::h5acc3dae1a6ea721 in framework.framework.17ab4582b218217d-cgu.0.rcgu.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: aborting due to 1 previous error
------------------------------------------
```

**Comment by jyn514** [comment]
no, i'm pretty sure that's also normalized. that's just without the diff applied.

**Comment by madsmtm** [comment]
I ran `./x test tests/ui/linkage-attr/framework.rs` locally on your branch, and got:
```
error: linking with `cc` failed: exit status: 1
   |
   = note: use `--verbose` to show all linker arguments
   = note: Undefined symbols for architecture arm64:
             "_CFRunLoopGetTypeID", referenced from:
                 framework::main::h04fdbb64c1c04fb4 in framework.framework.6a18941bb1a10668-cgu.0.rcgu.o
           ld: symbol(s) not found for architecture arm64
           clang: error: linker command failed with exit code 1 (use -v to see invocation)
           

error: aborting due to 1 previous error
```

I suspect what may be confusing you is the use of `compare-output-lines-by-subset`? This was used because the linker sometimes spewed out unrelated stuff, and because things changed between Xcode versions, which made it really difficult to write a good UI test for it.

**Comment by jyn514** [comment]
ok fuck this i'm not messing with it more

**Comment by jyn514** [comment]
ok someone let me use their mac and i managed to fix the bug

(the thing i needed was the original `.err` file, which doesn't show up in CI; i ended up just porting to run-make so this isn't so painful in the future)

**Comment by jyn514** [comment]
ok new plan. i don't think fixing these one-by-one is really feasible, there are just too many and they are too complicated to debug. instead i'm going to change this hard-warning to a lint and allow it by default in rustc's CI. that also has the advantage that downstream projects can opt-out of these warnings if they like.

File: compiler/rustc_passes/messages.ftl [hunk 5]
```diff
@@ -770,6 +770,9 @@ passes_unused_duplicate =
 passes_unused_empty_lints_note =
     attribute `{$name}` with an empty list has no effect
 
+passes_unused_linker_warnings_note =
+    the `linker_warnings` lint can only controlled at the root of a crate with `--crate-type bin`
```
Comment (mati865) [inline compiler/rustc_passes/messages.ftl:774]: Missing "be"?

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 6]
```diff
@@ -298,7 +305,24 @@ impl CodegenResults {
...
+    }
+}
+
+/// A list of lint levels used in codegen.
+///
+/// When using `-Z link-only`, we don't have access to the tcx and must work
+/// solely from the `.rlink` file. `Lint`s are defined too early to be encodeable.
+/// Instead, encode exactly the information we need.
+#[derive(Copy, Clone, Encodable, Decodable)]
+pub struct CodegenLintLevels {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/lib.rs:320]: Maybe put this in `CrateInfo`. That is already the place where we collect the various things that linking needs from the `TyCtxt`.

File: tests/run-make/rust-lld-custom-target/rmake.rs [hunk 7]
```diff
@@ -15,7 +15,7 @@ fn main() {
     // Compile to a custom target spec with rust-lld enabled by default. We'll check that by asking
     // the linker to display its version number with a link-arg.
     let output = rustc()
-        .env("RUSTC_LOG", "rustc_codegen_ssa::back::link=info")
+        .verbose()
```
Comment (bjorn3) [inline tests/run-make/rust-lld-custom-target/rmake.rs:18]: You are using `.verbose()` here, but `.arg("--verbose")` elsewhere. Can those `.arg("--verbose")` be replaced with `.verbose()`?

File: compiler/rustc_middle/src/lint.rs [hunk 8]
```diff
@@ -132,31 +132,38 @@ impl ShallowLintLevelMap {
...
         (None, LintLevelSource::Default)
     }
 
     /// Fetch and return the user-visible lint level for the given lint at the given HirId.
-    #[instrument(level = "trace", skip(self, tcx), ret)]
+    #[instrument(level = "trace", skip(self, tcx, sess), ret)]
     pub fn lint_level_id_at_node(
         &self,
-        tcx: TyCtxt<'_>,
+        tcx: Option<TyCtxt<'_>>,
```
Comment (bjorn3) [inline compiler/rustc_middle/src/lint.rs:156]: Is this change a leftover from an old revision?

File: tests/run-make/rust-lld-custom-target/rmake.rs (hunk 7 above)
Comment (jyn514) [reply tests/run-make/rust-lld-custom-target/rmake.rs:18]: good idea, done

File: compiler/rustc_codegen_ssa/src/lib.rs (hunk 6 above)
Comment (jyn514) [reply compiler/rustc_codegen_ssa/src/lib.rs:318]: oh that's a fantastic idea, that simplifies all the intermediate functions too so they don't have to pass along LintLevels explicitly, only the CrateInfo they were already passing

File: compiler/rustc_middle/src/lint.rs (hunk 8 above)
Comment (jyn514) [reply compiler/rustc_middle/src/lint.rs:156]: no. we need to call this function during linking, when a tcx isn't available. see https://github.com/rust-lang/rust/pull/119286/files#diff-862130c0af71054886913befc8084094485fa7d764d95f55644e033e34acd126R1061-R1063

Comment (bjorn3) [reply compiler/rustc_middle/src/lint.rs:156]: The `rustc_middle::lint::lint_level` function already doesn't accept a `TyCtxt` anyway. Every caller of `lint_level_id_at_node` calls it with `Some(tcx)`.

Comment (jyn514) [reply compiler/rustc_middle/src/lint.rs]: yes, you're right, sorry. i've reverted these changes.

**Comment by jyn514** [comment]
ok, the current problem is that rustc_codegen_gcc ignores RUSTFLAGS=-Alinker-messages, which results in this error:
```
 error: linker stderr: /usr/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core.mini_core.e55951eb20a0121d-cgu.0.rcgu.o: relocation in read-only section `.rodata.global.c'
       /usr/bin/ld: creating DT_TEXTREL in a shared object
```

@antoyo how do you prefer i fix this? i can either:
- change `y.sh test` to respect RUSTFLAGS, which may have other effects on your test suite
- change `y.sh test` to unconditionally pass -Alinker-warnings
- try and figure out how to fix the linker warning. i would appreciate your help with this.

**Comment by jyn514** [comment]
actually wait what, where is -D warnings coming from

i don't see that in the flags y.sh passes to rustc

**Comment by antoyo** [comment]
@jyn514: You can pass the flags through `CG_RUSTFLAGS`.

**Comment by jyn514** [comment]
@rustbot ready

note that this is based off of https://github.com/rust-lang/rust/pull/133633/ so you may want to review that first.

**Comment by jyn514** [comment]
@bjorn3 this is ready for review :)

File: compiler/rustc_middle/src/lint.rs [hunk 9]
```diff
@@ -173,7 +173,7 @@ impl TyCtxt<'_> {
 /// This struct represents a lint expectation and holds all required information
 /// to emit the `unfulfilled_lint_expectations` lint if it is unfulfilled after
 /// the `LateLintPass` has completed.
-#[derive(Clone, Debug, HashStable)]
+#[derive(Clone, Debug, Encodable, Decodable, HashStable)]
 pub struct LintExpectation {
```
Comment (bjorn3) [inline compiler/rustc_middle/src/lint.rs:177]: `CodegenResults::serialize_rlink` doesn't serialize the source map. While it this is fully correct and shouldn't be changed, this means that when a `LintExpectation` inside `CodegenResults` gets deserialized in a new compiler session, the `Span` inside of it will be garbage and similarly for the `Span` in `LintLevelSource`. Would it be possible to avoid serializing the spans? Or if not, replace them with `DUMMY_SP`? I'm not sure how well the linting infrastructure handles garbage spans.

**Review by bjorn3 — APPROVED** [review]
Apart from some concern about serialization of `Span` without serializing the corresponding source map, this LGTM.

File: compiler/rustc_middle/src/lint.rs (hunk 9 above)
Comment (jieyouxu) [reply compiler/rustc_middle/src/lint.rs:177]: > I'm not sure how well the linting infrastructure handles garbage spans.

Poorly. If the spans are empty or hi < lo, I think that triggers debug assertions.

Comment (bjorn3) [reply compiler/rustc_middle/src/lint.rs:177]: The raw lo and hi values are preserved across the serialization roundtrip (so the lo <= hi invariant is preserved (empty spans are valid and rendered as a span from lo to lo + 1)), however they refer to non-existent parts of the source map.

Comment (jieyouxu) [reply compiler/rustc_middle/src/lint.rs:177]: Hm, if those become OOB, then I think they also trigger debug assertions (or actual assertions) if there's any lint that unwraps when trying to read a SourceMap snippet.

Comment (jyn514) [reply compiler/rustc_middle/src/lint.rs:177]: this indeed crashes currently:
```
=== STDERR ===
thread 'rustc' panicked at compiler/rustc_span/src/source_map.rs:1056:40:
index out of bounds: the len is 0 but the index is 18446744073709551615
```

i thought i could solve this by deserializing to a dummy span but that doesn't seem to have worked for some reason? it still gives the same error.
```
  INFO rustc_codegen_ssa::back::link Deny Node { name: "linker_messages", span: no-location (#0), reason: None }
```

i *think* the right fix here is not to use a source span map at all during `-Z link-only`, to have the emitter return None in `Emitter::source_map`. but i am not sure exactly how to set that up.

File: compiler/rustc_passes/messages.ftl [hunk 10]
```diff
@@ -804,6 +804,9 @@ passes_unused_duplicate =
 passes_unused_empty_lints_note =
     attribute `{$name}` with an empty list has no effect
 
+passes_unused_linker_warnings_note =
+    the `linker_warnings` lint can only be controlled at the root of a crate with `--crate-type bin`
```
Comment (bjorn3) [inline compiler/rustc_passes/messages.ftl:808]: It is also allowed at the root of dylib, cdylib and proc-macro crates. Maybe say that it can only be controlled at the root of a crate that needs to be linked. Or just always allow it. If you define a crate as both rlib and dylib in Cargo.toml and compile for a target that doesn't support dylibs, cargo will drop the dylib crate type. This probably shouldn't cause a warning that `#[allow(linker_messages)]` is not allowed.

File: tests/run-make/linker-warning/rmake.rs [hunk 11]
```diff
@@ -25,4 +44,33 @@ fn main() {
...
+        .linker("./fake-linker")
+        .link_arg("run_make_warn")
+        .run_fail()
+        // NOTE: the error message here is quite bad (we don't have a source
+        // span, but still try to print the lint source). But `-Z link-only` is
+        // unstable and this still shows the linker warning itself so this is
+        // probably good enough.
+        .assert_stderr_contains("linker stderr: bar");
+
+    // Same thing, but with json output. This currently isn't supported and just ICEs.
```
Comment (bjorn3) [inline tests/run-make/linker-warning/rmake.rs:67]: Can you at least add a FIXME at the location where this ICEs?

Comment (bjorn3) [reply tests/run-make/linker-warning/rmake.rs:67]: Actually, this will have to be fixed before the PR can land as cargo always uses the json output format and thus would cause an ICE on any linker warning.

Comment (jyn514) [reply tests/run-make/linker-warning/rmake.rs]: I have fixed this to use a dummy span whenever a source map is missing. I don't think it should happen except when all three of -Z no-link, --error-format=json, and a linker_messages lint are present, but i agree it's better not to have panics floating around for no reason.

File: compiler/rustc_passes/messages.ftl (hunk 10 above)
Comment (jyn514) [reply compiler/rustc_passes/messages.ftl]: i've updated the message. i don't want to remove this warning, i would rather get false positives about the attribute being ignored than have it silently discarded for lib crates that are never dylibs.

File: compiler/rustc_errors/src/json.rs [hunk 12]
```diff
@@ -458,22 +458,33 @@ impl DiagnosticSpan {
...
     ) -> DiagnosticSpan {
-        let start = je.sm.lookup_char_pos(span.lo());
+        let empty_source_map;
+        let sm = match &je.sm {
+            Some(s) => s,
+            None => {
+                span = rustc_span::DUMMY_SP;
+                empty_source_map = Arc::new(SourceMap::new(FilePathMapping::empty()));
+                empty_source_map
+                    .new_source_file(std::path::PathBuf::from("empty.rs").into(), String::new());
```
Comment (bjorn3) [inline compiler/rustc_errors/src/json.rs:468]: Is it actually necessary to add a file to the source map? Or is an empty source map + DUMMY_SP enough?

Comment (jyn514) [reply compiler/rustc_errors/src/json.rs:468]: It's necessary to add a file. Otherwise it panics when trying to look up the span, with the same error as before.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 13]
```diff
@@ -1032,8 +1043,27 @@ fn link_natively(
...
+                let stderr = stderr
+                    .strip_prefix("warning: ")
+                    .unwrap_or(&stderr)
+                    .replace(": warning: ", ": ");
+                lint(format!("linker stderr: {stderr}"));
+            }
+            if !prog.stdout.is_empty() && sess.opts.verbose {
```
Comment (jyn514) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1064]: i think having both `verbose` and a lint here is too much, i don't think `verbose` should change lints. i'm going to remove the `verbose` condition.

**Comment by bjorn3** [comment]
r=me with CI green

File: tests/run-make/rust-lld-by-default-beta-stable/rmake.rs [hunk 14]
```diff
@@ -12,11 +12,7 @@ use run_make_support::rustc;
 fn main() {
```
Comment (jyn514) [inline tests/run-make/rust-lld-by-default-beta-stable/rmake.rs:12]: cc @rust-lang/release, i don't have a good way to test changes to this file. i tried setting `channel = "beta"` in config.toml and it tried to build llvm enzyme and a bunch of stuff failed.

**Comment by jieyouxu** [comment]
(`try-job:` directives need to be on separate lines)

**Comment by jyn514** [comment]
grrr bors cancels parallel jobs eagerly

@bors try

**Comment by jyn514** [comment]
This is ready for rereview. The changes since your last review are https://github.com/rust-lang/rust/pull/119286/commits/2e0b9086da4993412ace75482a276b282e56af7f, https://github.com/rust-lang/rust/pull/119286/commits/3d48f5e86d783c4b76126da85566a6c5f752c96f, and https://github.com/rust-lang/rust/pull/119286/commits/4b4007a500e27f708038e81549d7ad6437ce1b71. The last two just make tests pass and shouldn't be a big deal. The first one filters out output from MSVC link.exe, because as far as i can tell there's no way to turn it off with CLI flags and it's never useful enough to print as a warning.

File: src/bootstrap/src/core/build_steps/test.rs [hunk 15]
```diff
@@ -1862,12 +1862,19 @@ NOTE: if you're sure you want to do this, please open an issue as to why. In the
...
-        }
 
         let mut targetflags = flags;
         targetflags.push(format!("-Lnative={}", builder.test_helpers_out(target).display()));
+
+        // FIXME: on macOS, we get linker warnings about duplicate `-lm` flags. We should investigate why this happens.
+        if suite == "ui-fulldeps" && target.ends_with("darwin") {
+            hostflags.push("-Alinker_messages".into());
+            targetflags.push("-Alinker_messages".into());
+        }
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/test.rs:1873]: Suggestion: please open an issue and backlink it from here, otherwise nobody will ever discover this

Comment (jyn514) [reply src/bootstrap/src/core/build_steps/test.rs:1873]: There’s about a dozen more places where link or warnings are being ignored. I’m going to open one tracking issue for all of them.

Comment (jyn514) [reply src/bootstrap/src/core/build_steps/test.rs:1873]: done https://github.com/rust-lang/rust/issues/135828

**Comment by jyn514** [comment]
there are two bugs here:
1. apparently https://github.com/rust-lang/rust/pull/119286/commits/2e0b9086da4993412ace75482a276b282e56af7f doesn't always work (??)
2. the cargo test `freshness::lld_is_fresh` has linker warnings because it passes unrecognized arguments to rust-lld. i guess it assumes the linker is gcc when it's not.

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 16]
```diff
@@ -981,6 +992,20 @@ fn link_natively(
...
+            let is_msvc_link_exe = if let Some(code) = prog.status.code() {
+                sess.target.is_like_msvc
+                && flavor == LinkerFlavor::Msvc(Lld::No)
+                // Respect the command line override
+                && sess.opts.cg.linker.is_none()
+                // Match exactly "link.exe"
+                && linker_path.to_str() == Some("link.exe")
+                // All Microsoft `link.exe` linking error codes are
+                // four digit numbers in the range 1000 to 9999 inclusive
+                && (code < 1000 || code > 9999)
```
Comment (ChrisDenton) [inline compiler/rustc_codegen_ssa/src/back/link.rs:1004]: This was quite intentionally designed to only consider the error cases to decide whether to display the "maybe install VS" message. But now that you're using it in the success case too, this condition will never be true.

Comment (jyn514) [reply compiler/rustc_codegen_ssa/src/back/link.rs:1004]: oh lol oops

good catch ty

Comment (jyn514) [reply compiler/rustc_codegen_ssa/src/back/link.rs]: i've fixed this. i also removed the `cg_options.linker.is_none()` condition, because sometimes people explicitly pass `-C linker=link.exe`. i don't think this should introduce false positives for the Visual Studio check because it's still looking at exit codes and, well, it's still the same file path.

**Comment by jyn514** [comment]
oh sorry i was not clear - this fixes the MSVC link.exe bug but it does not fix the failing cargo test. that's waiting on https://github.com/rust-lang/cargo/pull/15097 to merge and then get upstreamed to rust-lang/rust.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/136023 was merged.

@bors retry

**Comment by jyn514** [comment]
probably spurious?
```
     Compiling rustc-std-workspace-core v1.99.0 (D:\a\rust\rust\library\rustc-std-workspace-core)
  
  thread 'main' has overflowed its stack
```

@bors retry

**Comment by ChrisDenton** [comment]
> probably spurious?
> ```
>      Compiling rustc-std-workspace-core v1.99.0 (D:\a\rust\rust\library\rustc-std-workspace-core)
>   
>   thread 'main' has overflowed its stack
> ```

A stack overflow is *probably* not spurious. Or if it is then it's a new one.

File: tests/run-make/rust-lld-by-default-beta-stable/rmake.rs (hunk 14 above)
Comment (ZuseZ4) [reply tests/run-make/rust-lld-by-default-beta-stable/rmake.rs:12]: @jyn514 Are you by chance on macos or windows? I didn't add support for them yet. But also there's `#enzyme = false` as default in config.example.toml, which I assume you didn't change? ThenI probably messed something up, because it shouldn't build enzyme. Can you share your exact config?

**Comment by madsmtm** [comment]
Wow, thanks for getting this in Jyn, this is a really good idea, and a massive amount of work!

**Comment by nicholasbishop** [comment]
> apparently lld unconditionally warns when compiling any program with debuginfo for UEFI

Thanks for the heads up on this. Fortunately it looks like this is only an issue with the less common target `i686-unknown-uefi`. `x86_64-unknown-uefi` and `aarch64-unknown-uefi` do not produce any unwanted linker output. I'll take a look at i686.
