### PR TITLE
Use existing declaration of rust_eh_personality

### LINKED ISSUE #70117: rustc segfault
### Code
[Steps to reproduce are in this comment](https://github.com/rust-lang/rust/issues/70117#issuecomment-601196305)
[and in this comment](https://github.com/rust-lang/rust/issues/70117#issuecomment-624312001)

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

and

```
rustc 1.43.0-nightly (c20d7eecb 2020-03-11)
binary: rustc
commit-hash: c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be
commit-date: 2020-03-11
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

### Error output

gdb backtrace with 1.42.0 
```
Thread 2 "rustc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef7ff700 (LWP 258154)]
0x00007ffff482cf95 in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
(gdb) 
(gdb) bt
#0  0x00007ffff482cf95 in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffff1b70226 in llvm::AttributeList::addAttributes(llvm::LLVMContext&, unsigned int, llvm::AttrBuilder const&) const ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-9-rust-1.42.0-stable.so
#2  0x00007ffff1c4d226 in llvm::Function::addAttributes(unsigned int, llvm::AttrBuilder const&) ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-9-rust-1.42.0-stable.so
#3  0x00007ffff53b7dd0 in LLVMRustAddFunctionAttribute ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#4  0x00007ffff53abd2e in rustc_codegen_llvm::declare::declare_raw_fn ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#5  0x00007ffff528b3f2 in <rustc_codegen_llvm::context::CodegenCx as rustc_codegen_ssa::traits::misc::MiscMethods>::eh_personality ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#6  0x00007ffff5369714 in rustc_codegen_ssa::mir::codegen_mir ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#7  0x00007ffff5287335 in <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#8  0x00007ffff52509ca in rustc_codegen_llvm::base::compile_codegen_unit::module_codegen ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#9  0x00007ffff52ca460 in rustc::dep_graph::graph::DepGraph::with_task ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#10 0x00007ffff5250624 in rustc_codegen_llvm::base::compile_codegen_unit ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#11 0x00007ffff5321fb6 in rustc_codegen_ssa::base::codegen_crate ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#12 0x00007ffff52b49fe in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#13 0x00007ffff5126d6f in rustc_session::utils::<impl rustc_session::session::Session>::time ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#14 0x00007ffff51c1de8 in rustc_interface::passes::QueryContext::enter ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#15 0x00007ffff5123a91 in rustc_interface::queries::Queries::ongoing_codegen ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#16 0x00007ffff4f62224 in rustc_interface::interface::run_compiler_in_existing_thread_pool ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#17 0x00007ffff4f5137d in scoped_tls::ScopedKey<T>::set ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#18 0x00007ffff4f4e584 in syntax::with_globals ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#19 0x00007ffff4f523b0 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#20 0x00007ffff4a18b97 in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:86
#21 0x00007ffff4f64449 in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
   from /home/harald/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-f0fe6d0442c8c573.so
#22 0x00007ffff49e7e8f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
#23 0x00007ffff4a177b0 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
#24 std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:13
#25 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:80
#26 0x00007ffff4968432 in start_thread () from /lib64/libpthread.so.0
#27 0x00007ffff4884833 in clone () from /lib64/libc.so.6
```

gdb backtrace with 1.43.0-nightly (c20d7eecb 2020-03-11)
```
Thread 2 "rustc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef1ff700 (LWP 258633)]
0x00007ffff154a1bd in llvm::AttributeList::addAttributes(llvm::LLVMContext&, unsigned int, llvm::AttrBuilder const&) const ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-9-rust-1.43.0-nightly.so
(gdb) bt
#0  0x00007ffff154a1bd in llvm::AttributeList::addAttributes(llvm::LLVMContext&, unsigned int, llvm::AttrBuilder const&) const ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-9-rust-1.43.0-nightly.so
#1  0x00007ffff1627226 in llvm::Function::addAttributes(unsigned int, llvm::AttrBuilder const&) ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-9-rust-1.43.0-nightly.so
#2  0x00007ffff4efc5c0 in LLVMRustAddFunctionAttribute ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#3  0x00007ffff4d436c6 in rustc_codegen_llvm::declare::declare_raw_fn ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#4  0x00007ffff4dd4a52 in <rustc_codegen_llvm::context::CodegenCx as rustc_codegen_ssa::traits::misc::MiscMethods>::eh_personality ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#5  0x00007ffff4e39944 in rustc_codegen_ssa::mir::codegen_mir ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#6  0x00007ffff4dc1e7c in <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#7  0x00007ffff4d3f71a in rustc_codegen_llvm::base::compile_codegen_unit::module_codegen ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#8  0x00007ffff4e237a1 in rustc::dep_graph::graph::DepGraph::with_task ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#9  0x00007ffff4d3f314 in rustc_codegen_llvm::base::compile_codegen_unit ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#10 0x00007ffff4ea0f5f in rustc_codegen_ssa::base::codegen_crate ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#11 0x00007ffff4e35415 in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#12 0x00007ffff4cbce16 in rustc_interface::passes::start_codegen ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#13 0x00007ffff4cd0923 in rustc::ty::context::tls::enter_global ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#14 0x00007ffff4be4126 in rustc_interface::queries::Queries::ongoing_codegen ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#15 0x00007ffff4a93ff6 in rustc_interface::interface::run_compiler_in_existing_thread_pool ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#16 0x00007ffff4a47bcd in scoped_tls::ScopedKey<T>::set ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#17 0x00007ffff4a44c14 in rustc_ast::attr::with_globals ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#18 0x00007ffff4a49060 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#19 0x00007ffff43fa697 in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:86
#20 0x00007ffff4a96486 in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
   from /home/harald/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-5bafe156ff266a09.so
#21 0x00007ffff43c563f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/liballoc/boxed.rs:1017
#22 0x00007ffff43f8f9d in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once ()
    at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/liballoc/boxed.rs:1017
#23 std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:13
#24 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:80
#25 0x00007ffff4344432 in start_thread () from /lib64/libpthread.so.0
#26 0x00007ffff4260833 in clone () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by tmiasko**
If crate declares `rust_eh_personality`, re-use existing declaration
as otherwise attempts to set function attributes that follow the
declaration will fail (unless it happens to have exactly the same
type signature as the one predefined in the compiler).

Fixes #70117.
Fixes https://github.com/rust-lang/rust/pull/81469#issuecomment-809428126; probably.

### CODE REVIEW

**Comment by bjorn3** [comment]
I think https://github.com/rust-lang/rust/pull/86801 would fix the same problem. It changes the `rust_eh_personality` function signatures in panic_abort to match panic_unwind.

**Comment by tmiasko** [comment]
> I think #86801 would fix the same problem. It changes the `rust_eh_personality` function signatures in panic_abort to match panic_unwind.

That seems orthogonal. The issue fixed here is mismatch between signature of `rust_eh_personality` in the crate, and the one predefined in the compiler. If the lang item is not present, the compiler uses `extern "C" fn(...) -> i32`.

**Comment by bjorn3** [comment]
> That seems orthogonal. The issue fixed here is mismatch between signature of rust_eh_personality in the crate, and the one predefined in the compiler. If the lang item is not present, the compiler uses extern "C" fn(...) -> i32.

I see. It should probably still use the function signature for the real personality function on the respective platform though. `extern "C" fn(...) -> i32` is not necessarily abi compatible with the real personality function. The AArch64 calling convention on macOS handles variadic functions completely different. I wouldn't be too surprised if LTO would merge the dummy function signature and the real one into `extern "C" fn(...) -> i32` instead of the real one, which would be a miscompilation on AArch64 macOS.

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 1]
```diff
@@ -937,8 +937,12 @@ impl BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
         pers_fn: &'ll Value,
         num_clauses: usize,
     ) -> &'ll Value {
+        // The LLVMBuildLandingPad requires personality to be a Function (as of LLVM 12), while we
+        // need a support for const bitcasts. Use LLVMSetPersonalityFn instead, which correctly
+        // casts personality to a Const.
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/builder.rs:942]: It is worth noting that setting personality_fn here this way is the right approach _either_ way. Its more direct and doesn't use legacy compatibility code.

File: compiler/rustc_codegen_llvm/src/context.rs [hunk 2]
```diff
@@ -385,11 +385,16 @@ impl MiscMethods<'tcx> for CodegenCx<'ll, 'tcx> {
                 } else {
                     "rust_eh_personality"
                 };
-                let fty = self.type_variadic_func(&[], self.type_i32());
-                self.declare_cfn(name, llvm::UnnamedAddr::Global, fty)
+                if let Some(llfn) = self.get_declared_value(name) {
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/context.rs:388]: For the codegen unit that ends up being allocated the definition of the `rust_eh_personality` this will return the definition in the source code. For the other codegen units AFAICT the `else` branch will be executed the first time `personality_fn` is requested and then this will continue returning the default declaration.

I wonder if we might want to force private definition of the personality fn in every CU of every crate? That sounds like it'd be the only way to make sure we accurately specify the signature of the personality fn everywhere.

Comment (nagisa) [reply compiler/rustc_codegen_llvm/src/context.rs:388]: I wonder if this might pose problems for e.g. LTO which gets insight into the mismatching signatures eventually...

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/context.rs:388]: > I wonder if we might want to force private definition of the personality fn in every CU of every crate?

That is impossible. There are two different possible eh_personality functions that can be used. Either the one in libpanic_unwind or the one in libpanic_abort. This means that codegen isn't possible when using private eh_personality functions until you chose the final panic strategy. In addition both depend on at least libcore, so which crate do you compile first? Libcore has to be compiled before either as they depend on libcore, but libcore also has to be compiled after either as it needs eh_personality due to many functions needing to run cleanup on unwinding to drop locals.

Comment (bjorn3) [reply compiler/rustc_codegen_llvm/src/context.rs:388]: > OTOH we have lived with an arguably wrong "default" signature here for a very long time with no apparent problems. So it might be fine either way?

Wrong signatures can give problems with LTO and PGO AFAIK. In any case it is UB with LTO due to needing to merge two incompatible function signatures.

File: compiler/rustc_codegen_llvm/src/builder.rs (hunk 1 above)
Comment (tmiasko) [reply compiler/rustc_codegen_llvm/src/builder.rs]: We could remove the call to `set_personality_fn`.

It does have the one advantage that it is impossible to forget to set a personality, and try intrinsics builds some landing pads manually.

Comment (nagisa) [reply compiler/rustc_codegen_llvm/src/builder.rs]: Yeah, if we're keeping it here where its impossible to forget then its probably worthwhile to remove calls such as [here](https://github.com/rust-lang/rust/blob/a55748ffe94e71f841c7b1d752779b0db138b342/compiler/rustc_codegen_ssa/src/mir/mod.rs#L151).

Comment (tmiasko) [reply compiler/rustc_codegen_llvm/src/builder.rs]: I am not sure about this call in `codegen_mir`, it seems it would be insufficient for SEH implementation.

Generally, I would rather not modify here more things than necessary.

File: compiler/rustc_codegen_llvm/src/context.rs (hunk 2 above)
Comment (tmiasko) [reply compiler/rustc_codegen_llvm/src/context.rs:388]: There are no calls using incorrect signature, so I wouldn't expect this to be an issue. 

I also reviewed LLVM IR linking implementation and experimented a bit with intentionally mismatched signatures. As far as I can see that should be fine. Clang uses the same signature by the way.

**Comment by tmiasko** [comment]
Failure in `test_reverse::prop_reverse_no_headers` looks completely unrelated to changes here https://github.com/BurntSushi/xsv/issues/227#issuecomment-792994674.

**Comment by nagisa** [comment]
@bors retry

perhaps?
