### PR TITLE
(fix) conflicting negative impl marker

### LINKED ISSUE #70849: Negative trait impl gives wrong error message
The following code:
```Rust
#![feature(negative_impls)]

struct MyType;

impl !Clone for &mut MyType {}

fn main() {}
```
produces:
```
  Compiling playground v0.0.1 (/playground)
error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `&mut MyType`:
 --> src/main.rs:5:1
  |
5 | impl !Clone for &mut MyType {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> std::clone::Clone for &mut T
            where T: ?Sized;

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
which reads as: any `&mut T where T: ?Sized implements Clone`, which isn't realy true. It realy implements `!Clone`.

Perhaps the error message should add a `!` in front of the impl to make it more obvious, like this:
```
= note: conflicting implementation in crate `core`:
          - impl<T> !std::clone::Clone for &mut T
            where T: ?Sized;
```

### PR DESCRIPTION
**Pull request by heiseish**
## Context

This MR fixes the error message for conflicting negative trait impls by adding the corresponding the polarity marker to the trait name. 

## Issues

- closes #70849

r​? @fmease

### CODE REVIEW

File: compiler/rustc_type_ir/src/predicate.rs [hunk 1]
```diff
@@ -196,6 +196,18 @@ impl fmt::Display for ImplPolarity {
     }
 }
 
+impl ImplPolarity {
+    /// Typically used to decorate the impl trait message by adding the corresponding
+    /// polarity marker before the trait name.
```
Comment (fmease) [inline compiler/rustc_type_ir/src/predicate.rs:201]:
```suggestion
```

I'm not super convinced that a doc comment adds any value. However if you'd like to keep it, I would shorten it to

```suggestion
    /// The polarity marker in front of the impl trait ref if applicable.
```

File: tests/ui/coherence/coherence-conflicting-repeated-negative-trait-impl-70849.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#![feature(negative_impls)]
+//@ edition: 2021
+// Test to ensure we are printing the polarity of the trait when printing out
+// conflicting trait impls
```
Comment (fmease) [inline tests/ui/coherence/coherence-conflicting-repeated-negative-trait-impl-70849.rs:4]:
```suggestion
// Test to ensure we are printing the polarity of the impl trait ref
// when printing out conflicting trait impls
```

(minor) A trait can't have a polarity but an *impl trait ref(erence)* can (basically, trait ref = trait name + generic args like `Trait<'a>`)

**Review by fmease — APPROVED** [review]
Thanks! Two small nitpicks & squashing into one commit, then we're good to go!

File: tests/ui/coherence/coherence-conflicting-repeated-negative-trait-impl-70849.rs (hunk 2 above)
Comment (heiseish) [reply tests/ui/coherence/coherence-conflicting-repeated-negative-trait-impl-70849.rs:4]: Yup that makes sense. Thanks for the clarification!

**Comment by heiseish** [comment]
@fmease thanks for the guidance! It's a bit late for me right now so I'm gonna squash tmr if CI passes

**Review by fmease — APPROVED** [review]
