### PR TITLE
fix confusion about parts required for float formatting

### LINKED ISSUE #41304: flt2dec comments and code disagree about the numbers of parts required for formatting
The comments for `flt2dec::to_shortest` and other similar functions describe the required size of the `&mut [Part]` parameters.  However, the assertions contained in those functions do not check the size described in the comments:

* `to_shortest_str` requires 5 in the comments, but asserts that the size is `>= 4`;
* `to_exact_fixed_str` does the same.

The comments appear to be confused, as the `[0.]` bit that they are apparently counting as a `Part` is not; perhaps this is a remnant left over from a previous refactoring.

* `to_shortest_exp_str` requires 7 in the comments, but asserts that the size is `>= 6`;
* `to_exact_exp_str` does the same.

The comments suggest that the worst case for the exponent would require 17 bits or more, which seems overly conservative.

### PR DESCRIPTION
**Pull request by froydnj**
The documentation for flt2dec doesn't match up with the actual
implementation, so fix the documentation to align with reality.
Presumably due to the mismatch, the formatting code for floats in
std::fmt can use correspondingly shorter arrays in some places, so fix
those places up as well.

Fixes #41304.

### CODE REVIEW

File: src/libcore/num/flt2dec/mod.rs [hunk 1]
```diff
@@ -410,8 +410,8 @@ fn determine_sign(sign: Sign, decoded: &FullDecoded, negative: bool) -> &'static
 /// it will only print given digits and nothing else.
 ///
 /// The byte buffer should be at least `MAX_SIG_DIGITS` bytes long.
-/// There should be at least 5 parts available, due to the worst case like
-/// `[+][0.][0000][45][0000]` with `frac_digits = 10`.
+/// There should be at least 4 parts available, due to the worst case like
+/// `[+][0.][0000][2][0000]` with `frac_digits = 10`.
```
Comment (kennytm) [inline src/libcore/num/flt2dec/mod.rs]: ??? I still count 5 parts `+`, `0.`, `0000`, `2` and `0000`.

Comment (froydnj) [inline src/libcore/num/flt2dec/mod.rs]: It's unfortunate that the `[]` notation is being used in two ways here: to denote a `Part` and to--I think--indicate the optional quality of the sign of the formatted number.  Since the `[+]` is being used in the latter sense, it does not count as a `Part` that would be stored in the `parts` array.

Comment (kennytm) [inline src/libcore/num/flt2dec/mod.rs]: OK, perhaps the `+` should use a different bracket or no brackets, or just omit the `+` altogether. Also, why the `45` is changed to `2`? That doesn't seem to make any difference.

Comment (froydnj) [inline src/libcore/num/flt2dec/mod.rs]: My understanding of the use of the numbers here was that they were denoting the index of the associated `Part` in the `parts` array.  So the `45` shouldn't be understood as the number "45", but `parts[4]` and `parts[5]`.  (Which is not correct in the first place, I believe.)  You can see this notation on display a little more clearly in `to_shortest_exp_str`, where we have `[+][1][.][2345][e][-][6]` as a result of this patch, though note that 1-based indexing is being used here rather than 0-based...  I changed `45` to `2` following said understanding, as the non-zero numbers there would be `parts[2]`.

I agree that this is not the best notation for explaining things!  Perhaps a separate pull request would be appropriate to make the documentation a little clearer?

Comment (kennytm) [inline src/libcore/num/flt2dec/mod.rs]: … I think you are overthinking about this 😄 [When the documentation was originally written](https://github.com/lifthrasiir/rust-strconv/blob/0c5df0ea184482c40d37e8553192c563570db211/src/flt2dec/mod.rs#L478-L490), the `+` sign is indeed a part, so `[+][1][.][2345][e][-][67]` had 7 parts because there are 7 `[]`s, not due to 1234567. Later [the `+` sign is no longer a part](https://github.com/lifthrasiir/rust-strconv/commit/f65f6445b389f33e3a455b81ed918eea585e5f9d) but the documentation failed to catch up until this PR.

Comment (froydnj) [inline src/libcore/num/flt2dec/mod.rs]: Ah, indeed! :)

**Comment by TimNN** [comment]
Hi @froydnj, thanks for the PR! We'll periodically check in on it to make sure that @sfackler or someone else from the team reviews it soon.

**Comment by Mark-Simulacrum** [comment]
@sfackler Could you take a look at the changes here? You're assigned.

cc @BurntSushi

**Comment by Mark-Simulacrum** [comment]
@bors retry
  - #40474
