### PR TITLE
regression tests for ICEs

### LINKED ISSUE #36379: `impl Trait` doesn't understand that empty functions return ()
The following should compile because `(): Default`:

``` rust
#![feature(conservative_impl_trait)]
fn test() -> impl Default {}
```

However, it fails with:

``` rust
error[E0282]: unable to infer enough type information about `_`
 --> tmp.rs:2:14
  |
2 | fn test() -> impl Default {}
  |              ^^^^^^^^^^^^ cannot infer type for `_`
  |
  = note: type annotations or generic parameter binding required
```

(Obviously, nobody will ever run into this in practice...)

### LINKED ISSUE #37550: ICE: "global closures can't capture anything"
```
#![feature(const_fn)]
fn main() {}
const fn x() {
    let t = true;
    let x = || t;
}
```
https://is.gd/JFNOLu

```
rustc 1.14.0-nightly (3f4408347 2016-10-27)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'global closures can't capture anything', ../src/librustc_passes/consts.rs:587
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

(const fn tracking issue https://github.com/rust-lang/rust/issues/24111)

### LINKED ISSUE #37665: MIR  panicked compilation
Hi there,

Issue #36092 title print this error too, but not for the same reason.
When I run the MIR compilation on [play.rust-lang.org](https://play.rust-lang.org/), I get an error.
**However**, I can run the Rust -> Binary compilation without any problem.

I tried this code:

```rust
use std::path::*;

fn main()
{
    let mut foo : String = "hello".to_string();
    foo.push(MAIN_SEPARATOR);
    println!("{}", foo);
}
```

I expected to see this happen: prints "hello/"

Instead, this happened: I get an error

## Meta

`rustc --version --verbose`: 
```
rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)
error: internal compiler error: unexpected panic
```

Backtrace:

```error
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x7f32e79237fa - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f32e793599f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x7f32e79321f5 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:257
   4:     0x7f32e7932907 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x7f32e7932794 - std::panicking::begin_panic::ha6a0d553db9869ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x7f32e79326b9 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x7f32e7932647 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x7f32e798384d - core::panicking::panic_fmt::he441b2ea2036b98a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x7f32e7983784 - core::panicking::panic::haf296e94ad32f436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:49
  10:     0x7f32e7cf8de6 - rustc_driver::pretty::print_with_analysis::{{closure}}::h2fc26bd99115e425
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_mir/pretty.rs:107
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/pretty.rs:973
  11:     0x7f32e7cf3e73 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h66f9e9eb1b5f338b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:979
  12:     0x7f32e7cb891f - rustc_driver::driver::phase_3_run_analysis_passes::h1111b274931d7851
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:966
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:963
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:950
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:947
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:735
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:854
  13:     0x7f32e7ccb851 - rustc_driver::pretty::print_after_hir_lowering::had0aca66ce21139b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/pretty.rs:954
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/pretty.rs:833
  14:     0x7f32e7cfacce - <rustc_driver::RustcDefaultCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}::h863cbb343cab38f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:487
  15:     0x7f32e7ca5b6d - rustc_driver::driver::compile_input::h21840cdf516c3ab1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:144
  16:     0x7f32e7cd06a0 - rustc_driver::run_compiler::h81a62653df4e7b03
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:222
  17:     0x7f32e7c0fbd8 - std::panicking::try::do_call::h54deb93462da3a7f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:1138
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:138
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:1072
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  18:     0x7f32e793d8aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  19:     0x7f32e7c2e568 - <F as alloc::boxed::FnBox<A>>::call_box::h2181ecf694b72547
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
  20:     0x7f32e79314c4 - std::sys::imp::thread::Thread::new::thread_start::h990fb082eb5abe34
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:605
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/thread.rs:84
  21:     0x7f32dfbef709 - start_thread
  22:     0x7f32e75ec82c - clone
  23:                0x0 - <unknown>
```

Thanks for your reading.

### LINKED ISSUE #38160: Compiler crash when macro generates associated const with stringify
I get a compiler crash when running the following code.

I get the crash with or without `#![feature(associated_consts)]` at the top of the file, but I don't get it if I generate a normal constant, if I replace the `stringify!(abc)` with a string literal, or if I write the code the macro generates directly into the source instead of generating it through a macro.

I tried this code:

```
trait MyTrait {
    const MY_CONST: &'static str;
}

macro_rules! my_macro {
    () => {
        struct MyStruct;

        impl MyTrait for MyStruct {
            // Note the stringify here, without it I don't get a crash.
            const MY_CONST: &'static str = stringify!(abc);
        }
    }
}

my_macro!();

fn main() {}
```

Error message:
```
thread 'rustc' panicked at 'adding a def'n for node-id NodeId(3) and data Initializer but a previous def'n exists: DefData { key: DefKey { parent: Some(DefIndex(0)), disambiguated_data: DisambiguatedDefPathData { data: TypeNs("std"), disambiguator: 0 } }, node_id: NodeId(3) }', ../src/librustc/hir/map/definitions.rs:279
```

## Meta

`rustc --version --verbose`:
```
rustc 1.15.0-nightly (c80c31a50 2016-12-02)
binary: rustc
commit-hash: c80c31a502c838f9ec06f1003d7c61cf9de9d551
commit-date: 2016-12-02
host: x86_64-apple-darwin
release: 1.15.0-nightly
LLVM version: 3.9
```

Backtrace:
```
stack backtrace:
   1:        0x1102ed0da - std::sys::imp::backtrace::tracing::imp::write::hbea47d9dd19b523c
   2:        0x1102fa3cf - std::panicking::default_hook::{{closure}}::h6875a2976258b020
   3:        0x1102f9f7d - std::panicking::default_hook::h88ffbc5922643264
   4:        0x1102fa896 - std::panicking::rust_panic_with_hook::hc790e47d4ecc86cd
   5:        0x1102fa734 - std::panicking::begin_panic::hc066339e2fdc17d1
   6:        0x1102fa652 - std::panicking::begin_panic_fmt::h5912b2d2df332044
   7:        0x10cbdc3c5 - rustc::hir::map::definitions::Definitions::create_def_with_parent::h9f915077b7729a67
   8:        0x10cbd7275 - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor>::visit_impl_item::hfd39f06fd36cebc4
   9:        0x10cb68201 - syntax::visit::walk_item::hf2d1c4f2e66576d9
  10:        0x10cbd6c75 - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor>::visit_item::{{closure}}::hd7b5b0a8a329ace5
  11:        0x10cbd65c2 - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor>::visit_item::h763ef3a101744485
  12:        0x10ca5a41e - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::h7d935db3784368ad
  13:        0x10fd0717e - syntax::ext::expand::MacroExpander::collect_invocations::h67e2a1c913dc4591
  14:        0x10fd0632e - syntax::ext::expand::MacroExpander::expand::hd3e73837bd4e019c
  15:        0x10fd05456 - syntax::ext::expand::MacroExpander::expand_crate::hdb654461100f1c42
  16:        0x10bae5ceb - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h78edc3698ca57871
  17:        0x10badec60 - rustc_driver::driver::phase_2_configure_and_expand::hb40d70b49cec9f8f
  18:        0x10bad8840 - rustc_driver::driver::compile_input::h8e119234b60571d5
  19:        0x10bb20f8b - rustc_driver::run_compiler::h57c4f233cd1a0c04
  20:        0x10ba3fce8 - std::panicking::try::do_call::hf679f17bf3b43b0b
  21:        0x1102fce4a - __rust_maybe_catch_panic
  22:        0x10ba62bdf - <F as alloc::boxed::FnBox<A>>::call_box::h21b5b32059700da6
  23:        0x1102f9514 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
  24:     0x7fff99c7eaaa - _pthread_body
  25:     0x7fff99c7e9f6 - _pthread_start

error: Could not compile `BugDemo`.
```

### LINKED ISSUE #38954: Compilation failure with no explicit error when passing ref std::path::Path to std::fs::File::open
I'm fairly new to Rust, so there may be something I'm missing here.

The following code snippet causes the Rust compiler (1.14, beta 1.15, nightly 1.16) to crash without any explicit errors on an up-to-date Arch Linux system immediately after a rustup update.

**Cargo.toml**
`[package]
name = "crash"
version = "0.1.0"`

**lib.rs**
`pub fn from_filepath(ref p: std::path::Path) -> std::io::Result<std::fs::File> { std::fs::File::open(p) }`

The only error I see is:
`error: Could not compile 'crash'.`

If I specify `-vv`, I just see the full command line (with a return code of -1).

Thanks!

### LINKED ISSUE #39362: ICE in nightly with patterns and nested enums
```rust
enum Foo {
    Bar { bar: Bar, id: usize }
}

enum Bar {
    A, B, C, D, E, F
}

fn test(f: Foo) {
    match f {
        Foo::Bar { bar: Bar::A, .. } => (),
        Foo::Bar { bar: Bar::B, .. } => (),
    }
}
```

The `match` doesn't cover all patterns, but instead of triggering an error (like stable does) it panics.

[Playpen link](https://is.gd/6QwCj4)
Version: c8af93f09 2017-01-18
Backtrace:

```
thread 'rustc' panicked at 'assertion failed: !self.is_enum()', C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\librustc\ty/mod.rs:1497
stack backtrace:
   0:     0x7ffa070208f8 - std::panicking::Location::line::h8c528bbdf4eef8a3
   1:     0x7ffa0701fd82 - std::panicking::Location::line::h8c528bbdf4eef8a3
   2:     0x7ffa070237bd - std::panicking::rust_panic_with_hook::h7abc6e334345e341
   3:     0x7ffa00a82293 - <unknown>
   4:     0x7ffa00cfe5d1 - rustc::ty::AdtDef::struct_variant::h3407c5d1765959c4
   5:     0x7ffa14c5bbf2 - <rustc_const_eval::pattern::Pattern<'tcx> as core::fmt::Display>::fmt::hd436f1763f102376
   6:     0x7ffa07036f31 - core::fmt::write::h17329881d672cff3
   7:     0x7ffa14c5617d - <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::heaaeacf8d46cf425
   8:     0x7ffa14c52dc9 - <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h8a811e2d6152dd49
   9:     0x7ffa14c51ae5 - <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h8a811e2d6152dd49
  10:     0x7ffa14c54130 - <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::heaaeacf8d46cf425
  11:     0x7ffa14c5056d - <rustc_const_eval::check_match::OuterVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::he57f23671b55c8bb
  12:     0x7ffa14c3042f - <unknown>
  13:     0x7ffa14c3009e - <unknown>
  14:     0x7ffa14c2e8d5 - <unknown>
  15:     0x7ffa14c50503 - <rustc_const_eval::check_match::OuterVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::he57f23671b55c8bb
  16:     0x7ffa14c31ad3 - <unknown>
  17:     0x7ffa14c50a7a - rustc_const_eval::check_match::check_crate::h80f0ce25c2e773dc
  18:     0x7ffa0cbf6c0e - rustc_driver::driver::count_nodes::h761a1dba824a4f1e
  19:     0x7ffa0cb3ad9b - <unknown>
  20:     0x7ffa0cbd137c - rustc_driver::driver::compile_input::h44e43be0fc34a1a1
  21:     0x7ffa0cc22cdb - rustc_driver::run_compiler::h5e34a930c0929e5c
  22:     0x7ffa0caff0ae - <unknown>
  23:     0x7ffa07026801 - _rust_maybe_catch_panic
  24:     0x7ffa0cb2c6e6 - <unknown>
  25:     0x7ffa0701dd2e - std::sys::imp::thread::Thread::new::h7a1b2b1b6bab390a
  26:     0x7ffa2a998363 - BaseThreadInitThunk
```

### PR DESCRIPTION
**Pull request by venkatagiri**
closes #36379
closes #37550
closes #37665
closes #38160
closes #38954
closes #39362

r? @Mark-Simulacrum

### CODE REVIEW

File: src/test/compile-fail/issue-37665.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+#![feature(rustc_attrs)]
+
+use std::path::MAIN_SEPARATOR;
+
+#[rustc_error]
+fn main() { //~ ERROR compilation successful
+    let mut foo : String = "hello".to_string();
+    foo.push(MAIN_SEPARATOR);
+    println!("{}", foo);
+}
```
Comment (Mark-Simulacrum) [inline src/test/compile-fail/issue-37665.rs]: I believe this test needs to have `--unpretty mir -Z unstable-options` passed to the compiler. `// compile-flags: -Z unstable-options --unpretty=mir` should work at the top of the file.

Comment (venkatagiri) [inline src/test/compile-fail/issue-37665.rs]: Done.

**Comment by Mark-Simulacrum** [comment]
Thanks!

@bors r+ rollup

File: src/test/compile-fail/issue-37665.rs (hunk 1 above)
Comment (Mark-Simulacrum) [inline src/test/compile-fail/issue-37665.rs]: Hm, looks like this won't quite work since (I believe) we don't actually reach the phase of the compiler where this errors out. Could you add a `let x: () = 0;` line with `//~ ERROR: mismatched types` attached to it and remove the `rustc_error`?

**Comment by Mark-Simulacrum** [comment]
@bors r-

Travis failed

**Comment by venkatagiri** [comment]
The `--unpretty=mir` option is affecting the error being thrown.
With this option, the compilation is succeeding. Even though `#[rustc_error]` is added.
Removing the mir option, the compilation is failing as expected.

```bash
$ build/x86_64-unknown-linux-gnu/stage2/bin/rustc src/test/compile-fail/issue-37665.rs \
-L build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json \
-L build/x86_64-unknown-linux-gnu/test/compile-fail/issue-37665.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux \
-C prefer-dynamic -o build/x86_64-unknown-linux-gnu/test/compile-fail/issue-37665.stage2-x86_64-unknown-linux-gnu \
-Crpath -O -Lnative=build/x86_64-unknown-linux-gnu/native/rust-test-helpers -Z unstable-options --unpretty=mir
$ echo $?
0
$ build/x86_64-unknown-linux-gnu/stage2/bin/rustc src/test/compile-fail/issue-37665.rs \
-L build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json \
-L build/x86_64-unknown-linux-gnu/test/compile-fail/issue-37665.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux \
-C prefer-dynamic -o build/x86_64-unknown-linux-gnu/test/compile-fail/issue-37665.stage2-x86_64-unknown-linux-gnu \
-Crpath -O -Lnative=build/x86_64-unknown-linux-gnu/native/rust-test-helpers -Z unstable-options
{"message":"compilation successful","code":null,"level":"error","spans":[{"file_name":"src/test/compile-fail/issue-37665.rs","byte_start":594,"byte_end":743,"line_start":18,"line_end":22,"column_start":1,"column_end":2,"is_primary":true,"text":[{"text":"fn main() { //~ ERROR compilation successful","highlight_start":1,"highlight_end":45},{"text":"    let mut foo : String = \"hello\".to_string();","highlight_start":1,"highlight_end":48},{"text":"    foo.push(MAIN_SEPARATOR);","highlight_start":1,"highlight_end":30},{"text":"    println!(\"{}\", foo);","highlight_start":1,"highlight_end":25},{"text":"}","highlight_start":1,"highlight_end":2}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":null}
$ echo $?
101
```

**Comment by Mark-Simulacrum** [comment]
Right, I think the fix I suggested here: https://github.com/rust-lang/rust/pull/42230#discussion_r118605879 should help.

File: src/test/compile-fail/issue-37665.rs (hunk 1 above)
Comment (venkatagiri) [inline src/test/compile-fail/issue-37665.rs]: Thanks for the tip. Am getting the error locally now, with & without the mir option.
Have pushed the fix.
