### PR TITLE
Fix `pattern_from_macro_note` for bit-or expr

### LINKED ISSUE #99380: Confusing "arbitrary expressions aren't allowed in patterns" error
Take the following code:

```rust
macro_rules! foo {
    ($p:expr) => {
        if let $p = Some(42) {
            return;
        }
    };
}

fn main() {
    foo!(Some(3));
}
```

Currently it fails with:

```
error: arbitrary expressions aren't allowed in patterns
  --> src/main.rs:10:10
   |
10 |     foo!(Some(3));
   |          ^^^^^^^
```

If you expanded the macro manually, `Some(3)` would be parsed as a pattern, but the `$p:expr` above changes it to be parsed as an expression. So what you *need* to do here is to change the `$p:expr` above to `$p:pat`. But this is very non-obvious.

Ideally, the compiler would try to check if the input is a valid pattern, and if so, add a note like "`Some(3)` is a valid pattern but the metavariable $p is specified to be an expression", and maybe also point to the metavariable's matcher.

@rustbot label A-macros

### PR DESCRIPTION
**Pull request by ver-nyan**
This is a continuation of issue https://github.com/rust-lang/rust/issues/99380 (and pr https://github.com/rust-lang/rust/pull/124488) but covers bit-or pattern.

Essentially a `pat1 | pat2`, or any bit-or pattern used in a `$e:expr` was not firing the `.pattern_from_macro_note` diagnostic bc `ast::Expr::is_approximately_pattern()` did not cover bit-or.

The cover for bit-or is only added in `lower_expr_within_pat()`, otherwise doing it in `is_approximately_pattern()` would result in the suggestion `if (i + 2) = 2 => if let (i + 2) = 2` from `suggest_pattern_match_with_let()` (which is the only other place `ast::Expr::is_approximately_pattern()` is used from what i see).

resolves https://github.com/rust-lang/rust/issues/99380
refs https://github.com/rust-lang/rust/pull/124488

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/pat.rs [hunk 1]
```diff
@@ -418,7 +418,11 @@ impl<'hir, R: ResolverAstLoweringExt<'hir>> LoweringContext<'_, 'hir, R> {
             }
             _ => {
                 let is_const_block = matches!(expr.kind, ExprKind::ConstBlock(_));
-                let pattern_from_macro = expr.is_approximately_pattern();
+                let pattern_from_macro = expr.is_approximately_pattern()
+                    || matches!(
+                        expr.peel_parens().kind,
+                        ExprKind::Binary(Spanned { node: BinOpKind::BitOr, .. }, ..)
+                    );
```
Comment (fmease) [inline compiler/rustc_ast_lowering/src/pat.rs:425]: I'm curious, is there a specific reason why you didn't move this check into `is_approximately_pattern`? Did it negatively impact other diagnostics that use this method?

Edit: Moving it into that function would also allow you to recurse into the operands to ensure that they're approximately patterns, too.

Comment (ver-nyan) [reply compiler/rustc_ast_lowering/src/pat.rs:425]: I initially had it isolated in `lower_expr_within_pat()` bc it ended up doing an incorrect `suggest_pattern_match_with_let()`
e.g. 
```
if (i + 2) = 3 {}

help: you might have meant to use pattern matching
   |
LL |     if let (i | 2) = 3 {}
   |        +++
```

Recursively `lhs.is_approximately_pattern() || rhs.is_approximately_pattern()` unfortunately didn't work since it would end up matching `ExprKind::Lit(_)` down the line.

Comment (ver-nyan) [reply compiler/rustc_ast_lowering/src/pat.rs:425]: I just learned that undeclared variables are `ExprKind::Path`, so both `Lit` and `Path` will cause false positive `let ` suggestion :c

A more formal example extending `tests/ui/expr/if/bad-if-let-suggestion.rs`:
```
if (i + 2) = 3 {} //~ ERROR cannot find value `i` in this scope


error[E0425]: cannot find value `i` in this scope
  --> $DIR/bad-if-let-suggestion.rs:12:9
   |
LL |     if (i | 2) = 3 {}
   |         ^ not found in this scope
   |
help: you might have meant to use pattern matching
   |
LL |     if let (i | 2) = 3 {}
   |        +++
```

Edit: also i think a recursive approach would lose it's "first-order'ness"
https://github.com/rust-lang/rust/blob/64d5cb603b9caf9063d27d64fdfa61fa7af3b98f/compiler/rustc_ast/src/ast.rs#L1638-L1639

Comment (JohnTitor) [reply compiler/rustc_ast_lowering/src/pat.rs:425]: Thanks for investigating, given that, I think it's better to go ahead with the current impl.

**Review by JohnTitor — APPROVED** [review]
Thank you and sorry for the delay! @bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154369/8a703520e80d87d4423c01f9d4fbc9e5f6533a02..2f468550702708ae77ec4a5034a6cb86d3957c32)*
