### PR TITLE
Suggest clone in user-write-code instead of inside macro

### LINKED ISSUE #139253: Inappropriate suggestion when mismatched types occur in the `dbg!` macro
### Code

```Rust
#[derive(Clone, Debug)]
struct Point<T> {
    v: T,
}

fn main() {
    let a: Point<u8> = dbg!(Point { v: 42 });
    let b: Point<u8> = dbg!(&a);
}
```

### Current output

```Shell
error[E0308]: mismatched types
  --> test.rs:10:24
   |
10 |     let b: Point<u8> = dbg!(&a);
   |                        ^^^^^^^^ expected `Point<u8>`, found `&Point<u8>`
   |
   = note: expected struct `Point<_>`
           found reference `&Point<_>`
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
  --> /home/jl-jiang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:367:20
   |
367|                 tmp.clone()
   |                    ++++++++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
```

### Desired output

```Shell
error[E0308]: mismatched types
  --> test.rs:10:24
   |
10 |     let b: Point<u8> = dbg!(&a);
   |                        ^^^^^^^^ expected `Point<u8>`, found `&Point<u8>`
   |
   = note: expected struct `Point<_>`
           found reference `&Point<_>`
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
  --> test.rs:10:29
   |
10 |     let b: Point<u8> = dbg!(a.clone());
   |                               +++++++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.88.0-nightly (e2014e876 2025-04-01)
binary: rustc
commit-hash: e2014e876e3efaa69bf51c19579adb16c3df5f81
commit-date: 2025-04-01
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes rust-lang/rust#139253

Inspired by rust-lang/rust#142543

r? @fmease

### CODE REVIEW

File: tests/ui/typeck/suggestions/suggest-clone-in-macro-issue-139253.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+fn foo(_: S) {}
+
+fn test1() {
+    let s = &S;
+    foo(dbg!(s)); //~ ERROR mismatched types
+}
+
+fn main() {
+    let a: Point<u8> = dbg!(Point { v: 42 });
+    let b: Point<u8> = dbg!(&a); //~ ERROR mismatched types [E0308]
```
Comment (fmease) [inline tests/ui/typeck/suggestions/suggest-clone-in-macro-issue-139253.rs]: Since the `Point` test case is basically identical to the `S` test case, I would just remove the former in favor the latter.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -1302,8 +1302,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 None => ".clone()".to_string(),
             };
 
+            let span = expr.span.find_oldest_ancestor_in_same_ctxt().shrink_to_hi();
```
Comment (fmease) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1305]: What's the output on your branch if we have a struct field shorthand (see lines above)? E.g.,

```rs
struct Struct { field: String }

macro_rules! expand {
    ($ident:ident) => { Struct { $ident } }
}

fn test1() {
    let field = &String::new();
    _ = expand!(field);
}

fn main() {}
```

Granted, the suggestion *on master* is wrong:

```rs
error[E0308]: mismatched types
 --> src/main.rs:9:17
  |
9 |     _ = expand!(field);
  |                 ^^^^^ expected `String`, found `&String`
  |
help: try using a conversion method
  |
9 |     _ = expand!(field: field.to_string());
  |                 ++++++      ++++++++++++
```

**Review by fmease — COMMENTED** [review]
Generally speaking, very much in favor. Thanks for considering this approach!

There still some unknowns I'd like solve, see my comment about struct field shorthands.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 2 above)
Comment (xizheyin) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1305]: I tried this example
```
#[derive(Debug, Clone)]
struct Struct { field: S }

#[derive(Debug, Clone)]
struct S;

macro_rules! expand {
    ($ident:ident) => { Struct { $ident } }
}

fn test1() {
    let field = &S;
    let a: Struct = dbg!(expand!(field));
    let b: Struct = dbg!(Struct { field });
    let c: S = dbg!(field);
    let c: S = dbg!(dbg!(field));
}

fn main() {}
```
It outputs:
```
error[E0308]: mismatched types
  --> src/main.rs:13:34
   |
13 |     let a: Struct = dbg!(expand!(field));
   |                                  ^^^^^ expected `S`, found `&S`
   |
help: consider using clone here
   |
13 |     let a: Struct = dbg!(expand!(field: field.clone()));
   |                                       +++++++++++++++

error[E0308]: mismatched types
  --> src/main.rs:14:35
   |
14 |     let b: Struct = dbg!(Struct { field });
   |                                   ^^^^^ expected `S`, found `&S`
   |
help: consider using clone here
   |
14 |     let b: Struct = dbg!(Struct { field: field.clone() });
   |                                        +++++++++++++++

error[E0308]: mismatched types
  --> src/main.rs:15:16
   |
15 |     let c: S = dbg!(field);
   |                ^^^^^^^^^^^ expected `S`, found `&S`
   |
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
   |
15 |     let c: S = dbg!(field).clone();
   |                           ++++++++

error[E0308]: mismatched types
  --> src/main.rs:16:16
   |
16 |     let c: S = dbg!(dbg!(field));
   |                ^^^^^^^^^^^^^^^^^ expected `S`, found `&S`
   |
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
   |
16 |     let c: S = dbg!(dbg!(field)).clone();
   |                                 ++++++++

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0308`.
```
And master outputs:
```
error[E0308]: mismatched types
  --> src/main.rs:13:34
   |
13 |     let a: Struct = dbg!(expand!(field));
   |                                  ^^^^^ expected `S`, found `&S`
   |
help: consider using clone here
   |
13 |     let a: Struct = dbg!(expand!(field: field.clone()));
   |                                       +++++++++++++++

error[E0308]: mismatched types
  --> src/main.rs:14:35
   |
14 |     let b: Struct = dbg!(Struct { field });
   |                                   ^^^^^ expected `S`, found `&S`
   |
help: consider using clone here
   |
14 |     let b: Struct = dbg!(Struct { field: field.clone() });
   |                                        +++++++++++++++

error[E0308]: mismatched types
  --> src/main.rs:15:16
   |
15 |     let c: S = dbg!(field);
   |                ^^^^^^^^^^^ expected `S`, found `&S`
   |
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
  --> /home/nju/.rustup/toolchains/nightly-2025-03-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:367:20
   |
367|                 tmp.clone()
   |                    ++++++++

error[E0308]: mismatched types
  --> src/main.rs:16:16
   |
16 |     let c: S = dbg!(dbg!(field));
   |                ^^^^^^^^^^^^^^^^^ expected `S`, found `&S`
   |
   = note: this error originates in the macro `dbg` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using clone here
  --> /home/nju/.rustup/toolchains/nightly-2025-03-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:367:20
   |
367|                 tmp.clone()
   |                    ++++++++

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0308`.
```

Suprisingly, it doesn't have an influence on shorthand. But it seems a bit strange that for different kinds of expr, some spans are macro internal and some are not.

Comment (xizheyin) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1305]: Do you know if this was intentional or a bug in the lowering?

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

File: tests/ui/typeck/suggestions/suggest-clone-in-macro-issue-139253.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+fn test1() {
+    let field = &S;
+    let a: Struct = dbg!(expand!(field)); //~ ERROR mismatched types [E0308]
+    let b: Struct = dbg!(Struct { field }); //~ ERROR mismatched types [E0308]
+    let c: S = dbg!(field); //~ ERROR mismatched types [E0308]
+    let c: S = dbg!(dbg!(field)); //~ ERROR mismatched types [E0308]
+}
+
+fn main() {}
```
Comment (xizheyin) [inline tests/ui/typeck/suggestions/suggest-clone-in-macro-issue-139253.rs:19]: I updated the test case and as you can see from the diff of the two commits, this has no effect on the shorthand case.

But this is actually strange, for the shorthand case, `expr.span` doesn't come from macro expansion, is this a bug? maybe fix it in another PR.

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

**Comment by xizheyin** [comment]
r? compiler

**Review by davidtwco — APPROVED** [review]
This is an improvement for one case, even if the shorthand fields are still incorrect, that can always be fixed in a follow-up.
