### PR TITLE
exclude `#![no_builtins]` crates from LTO

### LINKED ISSUE #31544: `copy_nonoverlapping` optimizes to a `__aeabi_memcpy` function that recurses infinitely
on a custom target with `no-compiler-rt: true`.

This binary:

``` asm
08000000 <_ZN10EXCEPTIONS20h109777d051950307UbaE>:
 8000000:       20002000        andcs   r2, r0, r0
 8000004:       08000009        stmdaeq r0, {r0, r3}

08000008 <__reset>:
 8000008:       b580            push    {r7, lr}
 800000a:       f240 0000       movw    r0, #0
 800000e:       f240 0100       movw    r1, #0
 8000012:       f2c2 0000       movt    r0, #8192       ; 0x2000
 8000016:       f2c2 0100       movt    r1, #8192       ; 0x2000
 800001a:       1a09            subs    r1, r1, r0
 800001c:       f021 0203       bic.w   r2, r1, #3
 8000020:       f240 0140       movw    r1, #64 ; 0x40
 8000024:       f6c0 0100       movt    r1, #2048       ; 0x800
 8000028:       f000 f806       bl      8000038 <__aeabi_memcpy4>
 800002c:       f240 0000       movw    r0, #0
 8000030:       f6c0 0000       movt    r0, #2048       ; 0x800
 8000034:       6800            ldr     r0, [r0, #0]
 8000036:       e7fe            b.n     8000036 <__reset+0x2e>

08000038 <__aeabi_memcpy4>:
 8000038:       f000 b800       b.w     800003c <__aeabi_memcpy>

0800003c <__aeabi_memcpy>:
 800003c:       e7fe            b.n     800003c <__aeabi_memcpy>
```

Was generated by this cargo project:

``` rust
// src/main.rs
#![feature(core_intrinsics)]
#![feature(lang_items)]

#![no_std]

extern crate rlibc;

use core::{intrinsics, mem};

// Entry point
#[no_mangle]
pub unsafe extern "C" fn __reset() {
    init_data();

    // Make sure the compiler doesn't remove the EXCEPTIONS symbol
    intrinsics::volatile_load(&EXCEPTIONS[0]);

    loop {}
}

// Initialize the data section
unsafe fn init_data() {
    extern "C" {
        static __DATA_LOAD: u32;

        static mut __DATA_END: u32;
        static mut __DATA_START: u32;
    }

    let n = (&__DATA_END as *const _ as usize - &__DATA_START as *const _ as usize) /
            mem::size_of::<u32>();

    intrinsics::copy_nonoverlapping(&__DATA_LOAD, &mut __DATA_START, n);
}

// This is how compiler-rt defines this symbol
#[no_mangle]
pub unsafe extern "C" fn __aeabi_memcpy4(dest: *mut u8, src: *const u8, size: usize) {
    rlibc::memcpy(dest, src, size);
}

// This is how compiler-rt defines this symbol
#[no_mangle]
pub unsafe extern "C" fn __aeabi_memcpy(dest: *mut u8, src: *const u8, size: usize) {
    rlibc::memcpy(dest, src, size);
}

// Stuff to build a place symbols in the addresses where the hardware expects them
extern "C" {
    fn __STACK_START();
}

#[link_section = ".exceptions"]
static EXCEPTIONS: [Option<unsafe extern "C" fn()>; 2] = [Some(__STACK_START), Some(::__reset)];

mod lang_items {
    #[lang = "eh_personality"]
    fn eh_personality() {}

    #[lang = "panic_fmt"]
    fn panic_fmt() {}

    // Unused, just to appease the compiler
    #[lang = "start"]
    fn start(_: *const u8, _: isize, _: *const *const u8) -> isize {
        0
    }
}

// Unused, just to appease the compiler
fn main() {}
```

`thumbv7m-none-eabi.json`

``` json
{
  "arch": "arm",
  "llvm-target": "thumbv7m-none-eabi",
  "os": "none",
  "target-endian": "little",
  "target-pointer-width": "32",

  "cpu": "cortex-m3",
  "executables": true,
  "morestack": false,
  "no-compiler-rt": true,
  "pre-link-args": [
    "-Tlayout.ld",
    "-Wl,--build-id=none",
    "-Wl,--gc-sections",
    "-mcpu=cortex-m3",
    "-mthumb",
    "-nostartfiles"
  ],
  "relocation-model": "static"
}
```

``` toml
# Cargo.toml
[package]
authors = []
name = "bug"
version = "0.1.0"

[dependencies]
rlibc = { git = "https://github.com/hackndev/rlibc", branch = "zinc" }
rust-libcore = "0.0.3"
```

```
/* layout.ld */
MEMORY
{
    rom(RX)     : ORIGIN = 0x08000000, LENGTH = 128K
    ram(WAIL)   : ORIGIN = 0x20000000, LENGTH = 8K
}

ENTRY(__reset)

__DATA_LOAD = LOADADDR(.data);

SECTIONS
{
    .text : ALIGN(4)
    {
        KEEP(*(.exceptions))
        *(.text*)
    } > rom

    .data : ALIGN(4)
    {
      __DATA_START = .;
      *(.data*)
      . = ALIGN(4);
      __DATA_END = .;
    } > ram AT > rom

    /DISCARD/ :
    {
      *(.ARM.exidx*)
    }

    __STACK_START = ORIGIN(ram) + LENGTH(ram);
}
```

### Version

```
rustc 1.8.0-nightly (75271d8f1 2016-02-09)
```

### Workarounds

- Define `__aeabi_memcpy4` as a loop instead of using `rlibc::memcpy` then you can drop the `rlibc` dependency. But depending on how you write the definition you may end with infinite recursion again.

- Remove the `__aeabi_memcpy4` function and link to a cross compiled `libcompiler-rt.a` by changing `no-compiler-rt` to `false`. This is hard to do because one needs to patch rust-lang/compiler-rt to work with a specific custom target.

### LINKED ISSUE #35540: #![no_builtins] should prevent a crate from participating in LTO
This attribute is needed to prevent LLVM from optimizing a `memcpy` implementation into a recursive call. However this attribute is not preserved in LTO builds: the attribute only works if it is set at the top-level crate.

Since crates containing implementations of built-in functions aren't meant to be called directly, they don't benefit from LTO and should be linked as a separate object.

One workaround (using rlibc as an example) is to first compile a `rlibc_inner` crate as a staticlib with `#![no_builtins]`, and then compile the `rlibc` crate as a rlib which links to `rlibc_inner.a`.

cc #31544 @alexcrichton @japaric

### PR DESCRIPTION
**Pull request by japaric**
this prevents intrinsics like `memcpy` from being mis-optimized to
infinite recursive calls when LTO is used.

fixes #31544
closes #35540

---

r? @alexcrichton 
cc @Amanieu

### CODE REVIEW

File: src/librustc_trans/back/link.rs [hunk 1]
```diff
@@ -938,8 +938,10 @@ fn add_upstream_rust_crates(cmd: &mut Linker,
             Linkage::NotLinked |
             Linkage::IncludedFromDylib => {}
             Linkage::Static => {
+                let is_a_no_builtins_crate =
+                    attr::contains_name(&sess.cstore.crate_attrs(cnum), "no_builtins");
```
Comment (alexcrichton) [inline src/librustc_trans/back/link.rs]: Could this logic for checking this attribute be centralized somewhere? I think there's probably at least one other instance of this check (besides the two added here) which reads that in the first place as well.

**Comment by alexcrichton** [comment]
Looks good to me, thanks @japaric! 

Could you also add a test for this in-tree?

**Comment by japaric** [comment]
> Could you also add a test for this in-tree?

I think that's going to be tricky. I have only seen the misoptimization when building an ARM executable that uses the `__aeabi_memcpy` intrinsic, which is defined as `asm!("b memcpy")`, because LLVM "optimizes" the `b memcpy` to `b __aeabi_memcpy`. It's tricky because it requires building an ARM executable, and that requires an ARM linker, plus inspecting (with `objdump`) the output binary.

File: src/librustc_trans/back/link.rs (hunk 1 above)
Comment (japaric) [inline src/librustc_trans/back/link.rs]: I've seen an `CrateTranslation` struct that contains a `no_builtins` field. I'll see if I can pass it around in these contexts.

Comment (japaric) [inline src/librustc_trans/back/link.rs]: So that struct is not really usable because in all these contexts the only thing we know about the dependency is its `CrateNum` (basically an ID number) and there's no way to get a `CrateTranslation` from it. Even if that were possible it would be more expensive, I think, that the current `attr::contains_name` call. However, an improvement we could do is to change this `attr::contains_name` call for something more readable like `sess.cstore.is_no_builtins_crate(cnum)` everywhere.

Comment (alexcrichton) [inline src/librustc_trans/back/link.rs]: Ah yeah something more readable is fine, I'd just want to deduplicate the string literal `"no_builtins"`

**Comment by alexcrichton** [comment]
Ah yeah it's probably fine to not actually test for something (as that would be really hard), but it'd be nice to have a crate which at least exercises the code paths perhaps?

**Comment by alexcrichton** [comment]
Another possibility would be to inspect the output of `-Z print-link-args` and be sure that the rlib with the `#![no_builtins]` attribute was linked manually.

**Comment by japaric** [comment]
@alexcrichton OK. Did the CStore refactor and added the print-link-args test.

**Comment by japaric** [comment]
Edited the last commit to remove the binary.

@bors r=alexcrichton
