### PR TITLE
llvm: backport "[SimplifyCFG] Hoisting invalidates metadata".

### LINKED ISSUE #36023: rustup-init 0.6.1 segfaults on x86_64 and armv7, 0.6.0 on OS X 10.10
rustup reports of 0.6.1 crashes:

- https://github.com/rust-lang-nursery/rustup.rs/issues/691
- https://github.com/rust-lang-nursery/rustup.rs/issues/687

These were built with `rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)`

rustup 0.6.0 crashed on OS X 10.10+. Fixed with a strategic `#[inline(never)]`

- https://github.com/rust-lang-nursery/rustup.rs/issues/679

That was built with `rustc 1.13.0-nightly (1576de0ce 2016-08-21)`

Reducing these has been very difficult and I have nothing for them right now.

cc @nikomatsakis @eddyb @alexcrichton

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #36023 by backporting @majnemer's LLVM patch fixing [the LLVM bug](https://llvm.org/bugs/show_bug.cgi?id=29163.) where SimplifyCFG hoisted instructions andkept their metadata (conditional `!nonnull` loads could kill a null check later if hoisted).

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 61a639ec4e0006f21253e8133cd1da980ce042d1 p=1

Raising priority a bit as it fixes a regression and we'll likely want to backport if this lands. Thanks for the investigation and the fix @eddyb!

File: src/test/run-pass/issue-36023.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
```
Comment (frewsxcv) [inline src/test/run-pass/issue-36023.rs]: This test fails on Travis CI. Any ideas why?

Comment (eddyb) [inline src/test/run-pass/issue-36023.rs]: Travis doesn't use the patched LLVM, so the test *can't* pass on it. See #36138.

**Comment by nikomatsakis** [comment]
Accepting for backport.
