### PR TITLE
Remove use of `unwrap()` from save-analysis

### LINKED ISSUE #69409: ICE -Zsave-analysis: ./ui/assign-to-method.rs
### Code

```rust
struct Cat {
  meows : usize,

  how_hungry : isize,
}

impl Cat {
    pub fn speak(&self) { self.meows += 1; }
}

fn cat(in_x : usize, in_y : isize) -> Cat {
    Cat {
        meows: in_x,
        how_hungry: in_y
    }
}

fn main() {
  let nyan : Cat = cat(52, 99);
  nyan.speak = || println!("meow"); //~ ERROR attempted to take value of method
  nyan.speak += || println!("meow"); //~ ERROR attempted to take value of method
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (436494b8f 2020-02-22)
binary: rustc
commit-hash: 436494b8f8008b600d64b3951f63c2bb0ea81673
commit-date: 2020-02-22
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

### Error output

```
error[E0615]: attempted to take value of method `speak` on type `Cat`
  --> ./ui/assign-to-method.rs:20:8
   |
20 |   nyan.speak = || println!("meow"); //~ ERROR attempted to take value of method
   |        ^^^^^
   |
   = help: methods are immutable and cannot be assigned to

error[E0615]: attempted to take value of method `speak` on type `Cat`
  --> ./ui/assign-to-method.rs:21:8
   |
21 |   nyan.speak += || println!("meow"); //~ ERROR attempted to take value of method
   |        ^^^^^
   |
   = help: methods are immutable and cannot be assigned to

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_save_analysis/lib.rs:535:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (436494b8f 2020-02-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0615`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0615]: attempted to take value of method `speak` on type `Cat`
  --> ./ui/assign-to-method.rs:20:8
   |
20 |   nyan.speak = || println!("meow"); //~ ERROR attempted to take value of method
   |        ^^^^^
   |
   = help: methods are immutable and cannot be assigned to

error[E0615]: attempted to take value of method `speak` on type `Cat`
  --> ./ui/assign-to-method.rs:21:8
   |
21 |   nyan.speak += || println!("meow"); //~ ERROR attempted to take value of method
   |        ^^^^^
   |
   = help: methods are immutable and cannot be assigned to

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_save_analysis/lib.rs:535:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:52
  15: rustc_save_analysis::SaveContext::get_expr_data
  16: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_expr
  17: syntax::visit::walk_expr
  18: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  19: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod
  20: rustc::dep_graph::graph::DepGraph::with_ignore
  21: rustc_session::utils::<impl rustc_session::session::Session>::time
  22: rustc::ty::context::tls::enter_global
  23: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (436494b8f 2020-02-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

query stack during panic:
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0615`.
```

</p>
</details>

### LINKED ISSUE #69416: ICE -Zsave-analysis issue-3763.rs
### Code

```rust
mod my_mod {
    pub struct MyStruct {
        priv_field: isize
    }
    pub fn MyStruct () -> MyStruct {
        MyStruct {priv_field: 4}
    }
    impl MyStruct {
        fn happyfun(&self) {}
    }
}

fn main() {
    let my_struct = my_mod::MyStruct();
    let _woohoo = (&my_struct).priv_field;
    //~^ ERROR field `priv_field` of struct `my_mod::MyStruct` is private

    let _woohoo = (Box::new(my_struct)).priv_field;
    //~^ ERROR field `priv_field` of struct `my_mod::MyStruct` is private

    (&my_struct).happyfun();               //~ ERROR method `happyfun` is private

    (Box::new(my_struct)).happyfun();          //~ ERROR method `happyfun` is private
    let nope = my_struct.priv_field;
    //~^ ERROR field `priv_field` of struct `my_mod::MyStruct` is private
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (436494b8f 2020-02-22)
binary: rustc
commit-hash: 436494b8f8008b600d64b3951f63c2bb0ea81673
commit-date: 2020-02-22
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

### Error output

```
error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:15:19
   |
15 |     let _woohoo = (&my_struct).priv_field;
   |                   ^^^^^^^^^^^^^^^^^^^^^^^

error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:18:19
   |
18 |     let _woohoo = (Box::new(my_struct)).priv_field;
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0624]: method `happyfun` is private
  --> src/test/ui/issues/issue-3763.rs:21:18
   |
21 |     (&my_struct).happyfun();               //~ ERROR method `happyfun` is private
   |                  ^^^^^^^^

error[E0624]: method `happyfun` is private
  --> src/test/ui/issues/issue-3763.rs:23:27
   |
23 |     (Box::new(my_struct)).happyfun();          //~ ERROR method `happyfun` is private
   |                           ^^^^^^^^

error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:24:16
   |
24 |     let nope = my_struct.priv_field;
   |                ^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_save_analysis/lib.rs:535:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (436494b8f 2020-02-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0616, E0624.
For more information about an error, try `rustc --explain E0616`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:15:19
   |
15 |     let _woohoo = (&my_struct).priv_field;
   |                   ^^^^^^^^^^^^^^^^^^^^^^^

error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:18:19
   |
18 |     let _woohoo = (Box::new(my_struct)).priv_field;
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0624]: method `happyfun` is private
  --> src/test/ui/issues/issue-3763.rs:21:18
   |
21 |     (&my_struct).happyfun();               //~ ERROR method `happyfun` is private
   |                  ^^^^^^^^

error[E0624]: method `happyfun` is private
  --> src/test/ui/issues/issue-3763.rs:23:27
   |
23 |     (Box::new(my_struct)).happyfun();          //~ ERROR method `happyfun` is private
   |                           ^^^^^^^^

error[E0616]: field `priv_field` of struct `my_mod::MyStruct` is private
  --> src/test/ui/issues/issue-3763.rs:24:16
   |
24 |     let nope = my_struct.priv_field;
   |                ^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_save_analysis/lib.rs:535:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:52
  15: rustc_save_analysis::SaveContext::get_expr_data
  16: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_expr
  17: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  18: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod
  19: rustc::dep_graph::graph::DepGraph::with_ignore
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
  21: rustc::ty::context::tls::enter_global
  22: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (436494b8f 2020-02-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis

query stack during panic:
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0616, E0624.
For more information about an error, try `rustc --explain E0616`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fix #69409, fix #69416

### CODE REVIEW

File: src/librustc_save_analysis/lib.rs [hunk 1]
```diff
@@ -533,14 +533,17 @@ impl<'l, 'tcx> SaveContext<'l, 'tcx> {
...
                         let variant = &def.non_enum_variant();
-                        let index = self.tcx.find_field_index(ident, variant).unwrap();
-                        filter!(self.span_utils, ident.span);
-                        let span = self.span_from_span(ident.span);
-                        return Some(Data::RefData(Ref {
-                            kind: RefKind::Variable,
-                            span,
-                            ref_id: id_from_def_id(variant.fields[index].did),
-                        }));
+                        if let Some(index) = self.tcx.find_field_index(ident, variant) {
```
Comment (Xanewok) [inline src/librustc_save_analysis/lib.rs]: Could we use `map` here? Since we indent by a level anyway and to avoid trailing `None`

File: src/test/ui/assign-to-method.rs [hunk 2]
```diff
@@ -1,3 +1,5 @@
+// compile-flags: -Zsave-analysis
```
Comment (Xanewok) [inline src/test/ui/assign-to-method.rs]: I think we should have a dedicated regression test in `src/test/ui/save-analysis` and not rely on this flag in general `src/test/ui` directory

cc @Centril on test layout

File: src/test/ui/issues/issue-3763.rs [hunk 3]
```diff
@@ -1,3 +1,5 @@
+// compile-flags: -Zsave-analysis
```
Comment (Xanewok) [inline src/test/ui/issues/issue-3763.rs]: Ditto

**Review by Xanewok — COMMENTED** [review]
This brings it in line with other usages and is safe to do, left some further comments

File: src/test/ui/assign-to-method.rs (hunk 2 above)
Comment (Centril) [reply src/test/ui/assign-to-method.rs]: My general sentiment is that we should not have files at all in `src/test/ui`, only directories. I have a question though... is the purpose of this test just for save-analysis? If not, then it doesn't seem fit for a `save-analysis/` folder, which I would expect to be targeted specifically at testing save-analysis as opposed to some other aspect (and save analysis being incidentally also tested).

File: src/librustc_save_analysis/lib.rs (hunk 1 above)
Comment (JohnTitor) [reply src/librustc_save_analysis/lib.rs]: Addressed via a211a82.

File: src/test/ui/assign-to-method.rs (hunk 2 above)
Comment (JohnTitor) [reply src/test/ui/assign-to-method.rs]: Left comments to clarify and moved `assign-to-method.rs` to `ui/methods`.

**Comment by JohnTitor** [comment]
Friendly ping @Xanewok, addressed your reviews, how about?

**Comment by Xanewok** [comment]
Sorry, forgot about this! Thanks =)

@bors r+ rollup
