### PR TITLE
Respect `-Z proc-macro-backtrace` flag for panics inside libproc_macro

### LINKED ISSUE #76270: Regression in proc macro panics being reported as compiler bugs
Between nightly-2020-08-29 and nightly-2020-09-02, the following began printing an ICE message (despite compiling successfully).

The relevant compiler commit range is https://github.com/rust-lang/rust/compare/d006f5734f49625c34d6fc33bf6b9967243abca8...130359cb05246fcacdde61baa2613419ef6570c7. #75082 appears extremely relevant so mentioning @Aaron1011 @petrochenkov. From the PR description it sounds like the PR was intended to have no effect unless the new -Z flag is passed. Is it possible it could be causing this?

---

### Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true
```

### src/lib.rs

```rust
use proc_macro::{Ident, Span, TokenStream};

#[proc_macro]
pub fn m(_input: TokenStream) -> TokenStream {
    let _ = std::panic::catch_unwind(|| Ident::new("", Span::call_site()));
    TokenStream::new()
}
```

### src/main.rs

```rust
repro::m!();

fn main() {}
```

Before:

```console
$ cargo +nightly-2020-08-29 check
   Compiling repro v0.0.0
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
```

After:

```console
$ cargo +nightly-2020-09-02 check
   Compiling repro v0.0.0
thread 'rustc' panicked at '`""` is not a valid identifier', compiler/rustc_expand/src/proc_macro_server.rs:332:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-nightly (80fc9b0ec 2020-09-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #76270

Previously, any panic occuring during a call to a libproc_macro method
(e.g. calling `Ident::new` with an invalid identifier) would always
cause an ICE message to be printed.

### CODE REVIEW

File: src/test/ui-fulldeps/auxiliary/proc-macro-panic.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// force-host
+// no-prefer-dynamic
+
+#![crate_type = "proc-macro"]
+
+extern crate proc_macro;
+use proc_macro::{TokenStream, Ident, Span};
+
+#[proc_macro]
+pub fn panic_in_libproc_macro(_: TokenStream) -> TokenStream {
```
Comment (petrochenkov) [inline src/test/ui-fulldeps/auxiliary/proc-macro-panic.rs:10]: `test-macros.rs` has a panicking macro already.

Comment (petrochenkov) [reply src/test/ui-fulldeps/auxiliary/proc-macro-panic.rs:10]: Ah, right, this is a fulldeps test.

Comment (Aaron1011) [reply src/test/ui-fulldeps/auxiliary/proc-macro-panic.rs:10]: I thought that this test should go in `ui-fulldeps`, since it needs to be run with stage2.
Also, panicking inside a proc-macro doesn't trigger this issue - it requires the panic to originate from inside `libproc_macro` (or `rustc_expand/src/proc_macro_server.rs`).

**Comment by spastorino** [comment]
Given that this fixes a `P-critical` issue ...
@bors p=1
