### PR TITLE
Fix ICE when Self is used in enum discriminant of a generic enum

### LINKED ISSUE #153756: [ICE]: Enum discriminant referring to `Self` causes "... has parameters, but no args were provided in instantiate"
### Code

```Rust
#![feature(sized_hierarchy)]

use std::marker::PointeeSized;

#[repr(usize)]
enum What<T: PointeeSized> {
    X = size_of::<*mut Self>(),
    Y(*mut T)
}
```

### Meta

Reproducible on the playground with version `1.96.0-nightly (2026-03-11 3b1b0ef4d80d3117924d)`

### Error output

```
thread 'rustc' (27) panicked at /rustc-dev/3b1b0ef4d80d3117924d91352c8b6ca528708b3c/compiler/rustc_type_ir/src/binder.rs:658:13:
Val(ZeroSized, FnDef(DefId(2:2522 ~ core[d6e6]::mem::size_of), [*mut What<T/#0>])) has parameters, but no args were provided in instantiate
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeMachine>>::eval_operand
   3: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeMachine>>::eval_callee_and_args
   4: rustc_const_eval::const_eval::eval_queries::eval_to_allocation_raw_provider
      [... omitted 1 frame ...]
   5: rustc_const_eval::const_eval::eval_queries::eval_to_const_value_raw_provider
      [... omitted 1 frame ...]
   6: <rustc_middle::ty::context::TyCtxt>::const_eval_poly
   7: <rustc_middle::ty::adt::AdtDef>::eval_explicit_discr
   8: rustc_hir_analysis::check::check::check_item_type
   9: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  10: rustc_hir_analysis::check::wfcheck::check_type_wf
      [... omitted 1 frame ...]
  11: rustc_hir_analysis::check_crate
  12: rustc_interface::passes::analysis
  13: rustc_query_impl::execution::try_execute_query::<rustc_middle::query::caches::SingleCache<rustc_middle::query::erase::ErasedData<[u8; 0]>>, false>
  14: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2026-03-12T04_25_48-25.txt` to your bug report

note: rustc 1.96.0-nightly (3b1b0ef4d 2026-03-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `What::X::{constant#0}`
#1 [eval_to_const_value_raw] simplifying constant for the type system `What::X::{constant#0}`
#2 [check_well_formed] checking that `What` is well-formed
#3 [check_type_wf] checking that types are well-formed
#4 [analysis] running analysis passes on crate `playground`
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by GokhanKabar**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/153815)*

Fixes rust-lang/rust#153756
Let discriminant AnonConst inherit parent generics via Node::Variant in generics_of, and emit a proper error instead of span_bug! for the TooGeneric case in wfcheck.

### CODE REVIEW

File: tests/ui/enum-discriminant/generic-self-in-discr-ice.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+//@ check-pass
+
+#![feature(sized_hierarchy)]
+
+use std::marker::PointeeSized;
+
+#[repr(usize)]
+enum What<T: PointeeSized> {
+    X = size_of::<*mut Self>(),
```
Comment (petrochenkov) [inline tests/ui/enum-discriminant/generic-self-in-discr-ice.rs:7]: This is a language extension, now we support something that we typically do not support.

E.g. this example produces and error
```rust
enum E<T> {
    V = size_of::<*const T> // ERROR generic parameters may not be used in enum discriminant values
}
```

I'd expect the test case to produce a similar error, because a generic parameter is indeed used in enum discriminant here.

Comment (GokhanKabar) [reply tests/ui/enum-discriminant/generic-self-in-discr-ice.rs:7]: Updated discriminant now emits an error instead of compiling. Self in a generic enum discriminant is rejected with the same message as direct generic parameter usage.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 2]
```diff
@@ -1110,8 +1110,14 @@ fn check_type_defn<'tcx>(
                 match tcx.const_eval_poly(discr_def_id) {
                     Ok(_) => {}
                     Err(ErrorHandled::Reported(..)) => {}
-                    Err(ErrorHandled::TooGeneric(sp)) => {
-                        span_bug!(sp, "enum variant discr was too generic to eval")
+                    Err(ErrorHandled::TooGeneric(_)) => {
+                        // This can happen if a discriminant slips past the checks in HIR ty
+                        // lowering (e.g. via type-dependent path resolution). Emit a proper
+                        // error rather than ICE-ing.
+                        tcx.dcx().span_err(
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs]: Is this change still necessary with the other changes?

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 3]
```diff
@@ -376,24 +376,44 @@ pub trait GenericArgsLowerer<'a, 'tcx> {
...
 
+/// Context in which `ForbidMCGParamUsesFolder` is being used, to emit appropriate diagnostics.
+enum ForbidParamContext {
+    /// Anon const in a min-const-generics (MCG) position, e.g. a const argument.
+    MinConstGenerics,
+    /// Enum discriminant expression.
+    EnumDiscriminant,
+}
+
 struct ForbidMCGParamUsesFolder<'tcx> {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I think this should be renamed to just `ForbidParamUsesFolder` since it's no longer min_const_generics specific

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 4]
```diff
@@ -376,24 +376,44 @@ pub trait GenericArgsLowerer<'a, 'tcx> {
     ) -> ty::GenericArg<'tcx>;
 }
 
+/// Context in which `ForbidMCGParamUsesFolder` is being used, to emit appropriate diagnostics.
+enum ForbidParamContext {
+    /// Anon const in a min-const-generics (MCG) position, e.g. a const argument.
+    MinConstGenerics,
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]:
```suggestion
    /// Anon const in a const argument position.
    ConstArgument,
```

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 5]
```diff
@@ -465,32 +487,56 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                context: ForbidParamContext::MinConstGenerics,
             };
             return Err(folder.error());
         }
         Ok(())
     }
 
+    /// Returns the `ForbidParamContext` for the current anon const if it is a context that
+    /// forbids uses of generic parameters that escape through type-dependent paths (e.g. `Self`
+    /// aliasing a generic type), or `None` if the current item is not such a context.
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]:
```suggestion
    /// forbids uses of generic parameters. `None` if the current item is not such a context.
```
we always forbid generic parameters, type dependent paths and `Self` aliases are just the only things that can cause us to need to handle them here

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 6]
```diff
@@ -465,32 +487,56 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+            return None;
+        }
+        match tcx.anon_const_kind(parent_def_id) {
+            ty::AnonConstKind::MCG => Some(ForbidParamContext::MinConstGenerics),
+            ty::AnonConstKind::NonTypeSystem => {
+                let hir_id = tcx.local_def_id_to_hir_id(parent_def_id);
+                matches!(tcx.parent_hir_node(hir_id), hir::Node::Variant(_))
+                    .then_some(ForbidParamContext::EnumDiscriminant)
+            }
+            _ => None,
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: can you make this an exhaustive match

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 7]
```diff
@@ -465,32 +487,56 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
     #[must_use = "need to use transformed output"]
     fn check_param_uses_if_mcg<T>(&self, term: T, span: Span, is_self_alias: bool) -> T
     where
         T: ty::TypeFoldable<TyCtxt<'tcx>>,
     {
         let tcx = self.tcx();
-        let parent_def_id = self.item_def_id();
-        if tcx.def_kind(parent_def_id) == DefKind::AnonConst
-            && let ty::AnonConstKind::MCG = tcx.anon_const_kind(parent_def_id)
+        let anon_const_def_id = self.item_def_id();
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: can you move this inside of the `if let` since we only need it in there

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 8]
```diff
@@ -1110,9 +1110,7 @@ fn check_type_defn<'tcx>(
                 match tcx.const_eval_poly(discr_def_id) {
                     Ok(_) => {}
                     Err(ErrorHandled::Reported(..)) => {}
-                    Err(ErrorHandled::TooGeneric(sp)) => {
-                        span_bug!(sp, "enum variant discr was too generic to eval")
-                    }
+                    Err(ErrorHandled::TooGeneric(_)) => {}
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs]: i didnt mean get rid of the arm, just revert it to what it was before this PR. does having the `span_bug!` cause ICEs?

Comment (GokhanKabar) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs]: yes, `span_bug` will cause an ICE if hit — but since this PR adds the upstream check in check_param_uses_if_mcg / anon_const_forbids_generic_params() that catches generics before const_eval_poly is ever reached, the `span_bug` should never fire in practice. It stays as a safeguard for truly unexpected cases.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 9]
```diff
@@ -460,37 +482,62 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        if tcx.def_kind(parent_def_id) != DefKind::AnonConst {
+            return None;
+        }
+        match tcx.anon_const_kind(parent_def_id) {
+            ty::AnonConstKind::MCG => Some(ForbidParamContext::ConstArgument),
+            ty::AnonConstKind::NonTypeSystem => {
+                let hir_id = tcx.local_def_id_to_hir_id(parent_def_id);
+                matches!(tcx.parent_hir_node(hir_id), hir::Node::Variant(_))
+                    .then_some(ForbidParamContext::EnumDiscriminant)
+            }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:534]: actually sorry I've realised this logic is probably a bit backwards, instead of defaulting all NonTypeSystem anon consts to *allowing* generic parameters, we should probably start off with assuming they *arent* allowed to have generics and then add special cases for when they are.

if you look at `fn generics_of` in `rustc_hir_analysis/src/collect/generics_of.rs` there's a match on `AnonConstKind` somewhere which will give some `NonTypeSystem` consts generics by returning `Some(parent_def)`.  Those are the only cases we'll want to be using `None` here

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:534]: alternatively you might be able to get away with just calling `tcx.generics_of` here and then looking at whether its empty or not. that'd probably be nicer

Comment (GokhanKabar) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:534]: I went with the tcx.generics_of approach if count() == 0 the anon const has no accessible generic params and we forbid them, otherwise we allow them. This mirrors the logic in generics_of.rs directly (where NonTypeSystem only gets Some(parent_did) for TyPat and Field nodes), so there's no need to duplicate the HIR node matching here.

Comment (BoxyUwU) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:534]: Thanks yeah this looks good :)

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 10]
```diff
@@ -460,37 +482,85 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                loop {
+                    match tcx.def_kind(current) {
+                        DefKind::AnonConst => break current,
+                        DefKind::InlineConst | DefKind::Closure => {
+                            current = tcx.local_parent(current);
+                        }
+                        _ => return None,
+                    }
+                }
+            }
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: you can use `tcx.typeck_root(parent_def_id)` instead

File: tests/ui/enum-discriminant/generic-self-in-discr-inline-const.rs [hunk 11]
```diff
@@ -0,0 +1,15 @@
+//@ check-fail
+// Test that `Self` is rejected even when nested inside an inline const
+// or closure within an enum discriminant. Regression test for issue #154281.
```
Comment (BoxyUwU) [inline tests/ui/enum-discriminant/generic-self-in-discr-inline-const.rs:3]: can you add the test for the closure case :sparkles:

**Comment by BoxyUwU** [comment]
@bors r+

sorry for the long turnaround on reviews :) thank you for working on this
