### PR TITLE
Always mark rust and rust-call abi's as unwind

### LINKED ISSUE #64655: Drop implementations not being called on panic with Fat LTO.
Hi,

It looks like calls to `Drop::drop()` are getting removed when using `lto = "fat"` for a release build. It doesn't seem to occur with `lto = "thin"` or `lto = "no"`.

I've got a test case here: https://github.com/cstorey/fat-lto-drop-repro, which can be reproduced like this:

```
: cez@ceri-no-mini; cargo --version; rustc --version; cargo run; cargo run --release
cargo 1.37.0 (9edd08916 2019-08-02)
rustc 1.37.0 (eae3437df 2019-08-13)
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/lto-drop`
About to panic
thread 'main' panicked at '???', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Dropping a Droppable
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/lto-drop`
About to panic
thread 'main' panicked at '???', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
: cez@ceri-no-mini;
```

(more details in the [transcript](https://github.com/cstorey/fat-lto-drop-repro/blob/master/README.md))

For context, I first noticed this in a project where I am using an `mpsc::channel` to communciate between threads, where a producer thread reads messages from the network, and the main thread saves those to a database.

I was relying on the fact that the `Drop` implementation for a channel will in effect close the channel, so the main thread can find out that the producer has failed, and so we should kill the process. What I saw instead was the producer thread panicing, but the main thread would never get woken up.

I've seen this on macOS `Darwin 17.7.0 x86_64` and Linux `5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64`.

### PR DESCRIPTION
**Pull request by pnkfelix**
PR #63909 identified a bug that had been injected by PR #55982. As discussed on https://github.com/rust-lang/rust/issues/64655#issuecomment-537517428 , we started marking extern items as nounwind, *even* extern items that said they were using "Rust" or "rust-call" ABI.

This is a more targeted variant of PR #63909 that fixes the above bug.

Fix #64655 

----

I personally suspect we will want PR #63909 to land in the long-term

But:
 *  it is not certain that PR #63909 *will* land,
 * more importantly, PR #63909 almost certainly will not be backported to beta/stable.

The identified bug was more severe than I think anyone realized (apart from perhaps @gnzlbg, as noted [here](https://github.com/rust-lang/rust/pull/63909#issuecomment-524818838)).

Thus, I was motivated to write this PR, which fixes *just* the issue with extern rust/rust-call functions, and deliberately avoids injecting further deviation from current behavior (you can see further notes on this in the comments of the code added here).

### CODE REVIEW

**Comment by pnkfelix** [comment]
nominating for beta backport once/if this actually lands.

File: src/librustc_codegen_llvm/attributes.rs [hunk 1]
```diff
@@ -273,25 +273,50 @@ pub fn from_fn_attrs(
...
-    } else if let Some(id) = id {
+    } else if let Some(_) = id {
+        // rust-lang/rust#64655, rust-lang/rust#63909: to minimize
+        // risk associated with changing cases where nounwind
+        // attribute is attached, this code is deliberately mimicking
+        // old control flow based on whether `id` is `Some` or `None`.
+        //
+        // However, in the long term we should either:
+        // - fold this into final else (i.e. stop inspecting `id`)
+        // - or better still: whole-heartedly adopt Rust PR #63909.
```
Comment (Centril) [inline src/librustc_codegen_llvm/attributes.rs]:
```suggestion
        // - adopt Rust PR #63909.
```

File: src/librustc_codegen_llvm/attributes.rs [hunk 2]
```diff
@@ -273,25 +273,50 @@ pub fn from_fn_attrs(
...
-            false
-        } else if sig.abi != Abi::Rust && sig.abi != Abi::RustCall {
-            // Any items defined in Rust that *don't* have the `extern` ABI are
-            // defined to not unwind. We insert shims to abort if an unwind
-            // happens to enforce this.
-            false
-        } else {
-            // Anything else defined in Rust is assumed that it can possibly
-            // unwind
+        if sig.abi == Abi::Rust || sig.abi == Abi::RustCall {
```
Comment (Centril) [inline src/librustc_codegen_llvm/attributes.rs]:
```suggestion
        if let Abi::Rust | Abi::RustCall = sig.abi {
```

File: src/test/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs [hunk 3]
```diff
@@ -0,0 +1,63 @@
+// run-pass
+
+// rust-lang/rust#64655: with panic=unwind, a panic from a subroutine
+// should still run desstructors as it unwindws the stack. However,
```
Comment (Centril) [inline src/test/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs]:
```suggestion
// should still run destructors as it unwinds the stack. However,
```

File: src/test/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+        }
+
+        let _guard = Droppable;
+        let s = "issue-64655-allow-unwind-when-calling-panic-directly.rs";
+        core::panicking::panic(&("???", s, 17, 4));
+    });
+
+    let wait = handle.join();
+
+    // reinstate handler to ease observation of assertion failures.
```
Comment (Centril) [inline src/test/ui/extern/issue-64655-allow-unwind-when-calling-panic-directly.rs]:
```suggestion
    // Reinstate handler to ease observation of assertion failures.
```

File: src/test/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs [hunk 5]
```diff
@@ -0,0 +1,82 @@
+// run-pass
+
+// rust-lang/rust#64655: with panic=unwind, a panic from a subroutine
+// should still run desstructors as it unwinds the stack. However,
```
Comment (Centril) [inline src/test/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs]:
```suggestion
// should still run destructors as it unwinds the stack. However,
```

File: src/test/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+// LTO turned on.
+
+// This test is the closest thing to a "regression test" we can do
+// without actually spawning subprocesses and comparing stderr
+// results.
+//
+// This test takes the code from the above issue and adapts it to
+// better fit our test infrastructure:
+//
+// * Instead of relying on println! to observe whether the destructor
```
Comment (Centril) [inline src/test/ui/extern/issue-64655-extern-rust-must-allow-unwind.rs]:
```suggestion
// * Instead of relying on `println!` to observe whether the destructor
```

**Comment by alexcrichton** [comment]
r=me on this, thanks for the clear PR description and the clear comments in the code!

File: src/librustc_codegen_llvm/attributes.rs [hunk 7]
```diff
@@ -273,25 +273,50 @@ pub fn from_fn_attrs(
...
+            false
         }
     } else {
         // assume this can possibly unwind, avoiding the application of a
         // `nounwind` attribute below.
+        //
+        // (But: See comments in previous branch. Specifically, it is
+        // unclear whether there is real value in the assumption this
+        // can unwind. The conservatism here may just be papering over
+        // a real problem by making some UB a bit harder to hit.)
```
Comment (RalfJung) [inline src/librustc_codegen_llvm/attributes.rs]: This is the None-id case, right? I'd appreciate an explanation for when this can even happen, as I was quite mystified when I wrote my own PR.

My preference would be to drop this branch and stop inspecting the id.

File: src/librustc_codegen_llvm/attributes.rs [hunk 8]
```diff
@@ -273,25 +273,50 @@ pub fn from_fn_attrs(
...
+            //
+            //  2. A Rust item using a non-Rust ABI (like `extern "C" fn foo() { ... }`).
+            //
+            // Foreign items (case 1) are assumed to not unwind; it is
+            // UB otherwise. (At least for now; see also
+            // rust-lang/rust#63909 and Rust RFC 2753.)
+            //
+            // Items defined in Rust with non-Rust ABIs (case 2) are
+            // defined to not unwind. We insert shims to abort if an
+            // unwind happens to enforce this.
```
Comment (RalfJung) [inline src/librustc_codegen_llvm/attributes.rs]: This comment is factually wrong -- we do not insert any shims.

File: src/librustc_codegen_llvm/attributes.rs [hunk 9]
```diff
@@ -273,25 +273,50 @@ pub fn from_fn_attrs(
...
-            // unwind
+        if sig.abi == Abi::Rust || sig.abi == Abi::RustCall {
+            // Any Rust method (or `extern "Rust" fn` or `extern
+            // "rust-call" fn`) is explicitly allowed to unwind
+            // (unless it has no-unwind attribute, handled above).
             true
+        } else {
+            // Anything else is either:
+            //
+            //  1. A foreign item (like `extern "C" { fn foo(); }`), or
```
Comment (RalfJung) [inline src/librustc_codegen_llvm/attributes.rs]:
```suggestion
            //  1. A foreign item using a non-Rust ABI (like `extern "C" { fn foo(); }`), or
```
No reason to be that explicit only in one branch (foreign Rust-ABI items are a thing, after all).

**Comment by RalfJung** [comment]
Funny, I just today talked with @nikomatsakis about this. ;)

Yes, this PR is certainly a step in the right direction. I was not expecting my PR to be that controversial; that's the only reason why I did not split out this change to begin with.

File: src/librustc_codegen_llvm/attributes.rs (hunk 8 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: yeah I was wondering what to do about that.

File: src/librustc_codegen_llvm/attributes.rs (hunk 7 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: The first version I wrote of this code did drop this branch. But then when I was writing up the description, I decided it was more important to minimize the amount of behavior being changed, because I want this PR to be eligible for backport.

I would support making the change you describe in a future PR, which I believe the comments here make quite clear?

File: src/librustc_codegen_llvm/attributes.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: (I personally don't think this would make the code more readable. Long term I think the right thing would be to add a method like `Abi::can_unwind(&self) -> bool`, since that will be more future proof for things like the proposed "C panic" ABI. But I'm not going to put that in this PR, which is meant to be closer to minimal.)

File: src/librustc_codegen_llvm/attributes.rs (hunk 8 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: I think the best thing for me to do at this point is remove the sentence about the shims, and point the reader at #58794 (right)?

File: src/librustc_codegen_llvm/attributes.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_codegen_llvm/attributes.rs]: Doesn't seem cleaner / idiomatic to me to mention `sig.abi` twice rather than use Rust's nice pattern matching facilities... but oh well. But yes, `Abi::can_unwind` seems good.

File: src/librustc_codegen_llvm/attributes.rs (hunk 8 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: (done)

File: src/librustc_codegen_llvm/attributes.rs (hunk 9 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/attributes.rs]: boy I had a really hard time parsing your sentence and making it line up with the suggestion (which was obviously good). But I think I understand now: The "only in one branch" was referencing the **previous branch**, not this one, right?

Comment (RalfJung) [reply src/librustc_codegen_llvm/attributes.rs]: Sorry, I should have been more clear. I referred to the "2.", the "next branch" inside this comment. There you also explicitly state "using a non-Rust ABI"; I just copied that.

File: src/librustc_codegen_llvm/attributes.rs (hunk 8 above)
Comment (RalfJung) [reply src/librustc_codegen_llvm/attributes.rs]: Agreed.

**Comment by nagisa** [comment]
This needs a codegen test to verify that we never generate nounwind for extern calls like those.

**Comment by pnkfelix** [comment]
> This needs a codegen test to verify that we never generate nounwind for extern calls like those.

(I will do this in a follow-up PR.)

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/86450weeklymeeting2019100354818.html#177247553) in rustc mtg; accepted for beta backport.

**Comment by tmandry** [comment]
Failed on wasm in #65072, @bors r-

**Comment by pnkfelix** [comment]
hmm so is the scenario from these tests something that wasm cannot express in first place? (I.e. should I "just" mark the tests with something like `// ignore-wasm` ...) ? I will investigate.

**Comment by pnkfelix** [comment]
oh is the issue that wasm is compiled with panic=abort by default, and thus these tests (and whole issue) are pointless there?

**Comment by alexcrichton** [comment]
Yeah `// ignore-wasm` should be fine here

**Comment by Centril** [comment]
Failed (again) in https://github.com/rust-lang/rust/pull/65109#issuecomment-538550046, @bors r- rollup=never

**Comment by nagisa** [comment]
NB: I asked for codegen tests for this change, but said that they do not necessarily need to be a part of this PR. This is reminder for myself to fill an issue if the tests do not materialize.

File: src/librustc_codegen_llvm/attributes.rs (hunk 7 above)
Comment (RalfJung) [reply src/librustc_codegen_llvm/attributes.rs]: LGTM; I just hope we don't forget to do that follow-up. ;)

**Comment by RalfJung** [comment]
It failed in `asmjs`, so this likely just needs another exclusion line? But why did the other tests not need that?

**Comment by RalfJung** [comment]
The issue is that the new test uses threads to catch panics; emcscripten does not support threads. So I added ignore-emcscripten.

@bors r=alexcrichton

(@pnkfelix seems to be unavailable and this is a critical soundness fix.)

**Comment by RalfJung** [comment]
Ah, missed another test.

@bors r=alexcrichton
