### PR TITLE
Lint that warns when an elided lifetime ends up being a named lifetime (`elided_named_lifetimes`)

### LINKED ISSUE #48686: Elision in method can take `'static` from `self`, perhaps surprising
rustc currently compiles the following with no warnings or errors:

```rust
struct Foo;

impl Foo {
    pub fn get_mut(&'static self, x: &mut u8) -> &mut u8 {
        unsafe { &mut *(x as *mut _) }
    }
}
```

However, attempting to make this function safe reveals that the elided lifetime of `x` isn't the lifetime in the return type-- it's instead copying over the `'static` lifetime into the return type! Rustdoc actually documents that the signature of this method is `fn get_mut(&'static self, x: &mut u8) -> &'static mut u8`.

The following code produces an error:

```rust
struct Foo;

impl Foo {
    pub fn get_mut(&'static self, x: &mut u8) -> &mut u8 {
        x
    }
}
```
```
error[E0312]: lifetime of reference outlives lifetime of borrowed content...
 --> src/main.rs:7:9
  |
7 |         x
  |         ^
  |
  = note: ...the reference is valid for the static lifetime...
note: ...but the borrowed content is only valid for the anonymous lifetime #1 defined on the method body at 6:5
 --> src/main.rs:6:5
  |
6 | /     pub fn get_mut(&'static self, x: &mut u8) -> &mut u8 {
7 | |         x
8 | |     }
  | |_____^

error: aborting due to previous error

error: Could not compile `playground`.
```

This seems like it could be fixed by disallowing elision in this case via a lint.

cc @aturon

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
As suggested in https://github.com/rust-lang/rust/issues/48686#issuecomment-1817334575

Fixes #48686

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -2039,6 +2063,43 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+
+        match candidate {
+            LifetimeElisionCandidate::Missing(missing @ MissingLifetime { span: elided, .. }) => {
+                debug_assert_eq!(id, missing.id);
+                match res {
+                    LifetimeRes::Static => {
+                        if !self.allow_elided_static {
+                            self.r.lint_buffer.buffer_lint(
+                                lint::builtin::ELIDED_NAMED_LIFETIMES,
+                                missing.id_if_not_fake_or(self.crate_node_id),
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:2075]: In what cases are the ids fake? In those cases, we should probably just not lint.

File: compiler/rustc_resolve/src/late.rs [hunk 2]
```diff
@@ -1550,6 +1567,13 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
         ret
     }
 
+    #[instrument(level = "debug", skip(self))]
+    fn visit_ty_allow_elided_static(&mut self, ty: &'ast Ty) {
+        self.allow_elided_static = true;
+        self.visit_ty(ty);
+        self.allow_elided_static = false;
+    }
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1575]: You do not need this method. `allow_elided_static` should be equivalent to the presence of `LifetimeRibKind::Elided(LifetimeRes::Static)` in the stack.

File: compiler/rustc_hir/src/def.rs [hunk 3]
```diff
@@ -796,8 +796,8 @@ impl<Id> Res<Id> {
 pub enum LifetimeRes {
     /// Successfully linked the lifetime to a generic parameter.
     Param {
-        /// Id of the generic parameter that introduced it.
-        param: LocalDefId,
+        /// `LocalDefId` & `Ident` of the generic parameter that introduced it.
+        param: (LocalDefId, Ident),
```
Comment (cjgillot) [inline compiler/rustc_hir/src/def.rs:800]: Why?

Comment (GrigorenkoPV) [reply compiler/rustc_hir/src/def.rs:800]: To be able to have the lifetime name in the message:
```
warning: elided lifetime has a name
 --> ./test.rs:6:49
  |
6 |     pub fn get_mut<'a>(&'a self, x: &mut u8) -> &mut u8 {
  |                    --                           ^ this elided lifetime gets resolved as `'a`
  |                    |
  |                    lifetime `'a` introduced here
```
Ident contains span and name (as a Symbol). We could get the span back with `tcx.source_span(local_def_id)` or however it's spelled. But not the name: `tcx.def_name(id)` requires `HirId`, not `DefId`, and `tcx.local_def_id_to_hir_id(..)` for some reason makes rustc hang and eat lots of RAM when I try to call it (infinite cycle?).

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:1575]: What I am trying to do here is to allow not writing `'static` in cases like
```rust
const A: &[u8] = &[];
static B: &str = "hello";
impl Trait{
    const C: &T = ...;
}
```

but still warn about things like
```
warning: elided lifetime has a name
 --> ./test.rs:6:50
  |
6 |     pub fn get_mut(&'static self, x: &mut u8) -> &mut u8 {
  |                                                  ^ this elided lifetime gets resolved as `'static`
  |
```

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:2075]:
```rust
pub fn get_mut(&'static self, x: &mut u8) -> &'_ mut u8
```
is ok, but
```rust
pub fn get_mut(&'static self, x: &mut u8) -> &mut u8
```
is not.

Any `MissingLifetime` nodes with `LifetimeKind::Ampersand` get overlooked when we emit buffered lints, for some reason. After staring at the code for a bit, it looked like they get an ad-hoc NodeId not tied to any source code, and not preserved anywhere, because such a lifetime eventually gets replaced with something else.

Not linting here would defeat the whole point of the lint.

Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:2075]: > Any `MissingLifetime` nodes with `LifetimeKind::Ampersand`

There seem to be more cases beside this one, because I remember getting some more ICEs about not emitting all buffered lints when I ran it on `tests/ui`, but I haven't looked into those yet.

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:1575]: I guess I should've called it `do_not_warn_about_elided_statics`.

Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:1575]: Done c726445411bcef39af9b4df5f86b0727d86d8929

**Comment by GrigorenkoPV** [comment]
> `rustc_errors::translation` was changed

- replaced some elided lifetimes with explicit ones

> Some changes occurred in src/tools/clippy

- replaced some elided lifetimes with explicit ones
- blessed some tests, because there is a new lint

> The Miri subtree was changed

- replaced some elided lifetimes with explicit ones

File: compiler/rustc_hir/src/def.rs (hunk 3 above)
Comment (cjgillot) [reply compiler/rustc_hir/src/def.rs:800]: `tcx.item_name` takes a `DefId` and won't need HIR.

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (cjgillot) [reply compiler/rustc_resolve/src/late.rs:1576]: I really mean that this method should not exist. If you want stack-like behaviour, you need to inspect `self.lifetime_ribs`. And if some information is missing, as a field to `LifetimeRibKind`.

**Comment by cjgillot** [comment]
Could you submit d214d0b0f2e221fc97dee444ca1686086568f876 as a standalone PR? Is can be merged while we review this PR.

File: compiler/rustc_hir/src/def.rs (hunk 3 above)
Comment (GrigorenkoPV) [reply compiler/rustc_hir/src/def.rs]: Oh, sorry, completely overlooked it.

Fixed in d645641862714d02b327e0d9d7d45888a1100e1a

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs]: Fixed 30f5b78eba5f8d8e82b1f41368db9cc08f5fcada

**Comment by cjgillot** [comment]
Thanks!

As for the matter with `crate_node_id`, it will prevent users from controlling lint behaviour using `allow`/`deny` attributes. The missing node-ids are those which correspond to a `ElidedAnchor` resolution.

2 alternative ideas:
- channel the correct NodeId for the lint to use;
- emit the lints when seeing the `ElidedAnchor` in `record_lifetime_res`.

**Comment by GrigorenkoPV** [comment]
> As for the matter with `crate_node_id`, it will prevent users from controlling lint behaviour using `allow`/`deny` attributes. The missing node-ids are those which correspond to a `ElidedAnchor` resolution.

Ah, I was worried that it might cause some sort of a problem, and indeed it does. Oh well. I seem to have fixed it and I also added a test for this.

File: compiler/rustc_resolve/src/late.rs [hunk 4]
```diff
@@ -1916,6 +1928,7 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
             };
             let missing_lifetime = MissingLifetime {
                 id: node_ids.start,
+                related_node_that_exists_in_source: finalize_node,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1931]: Why not segment_id?

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 5]
```diff
@@ -102,6 +102,13 @@ fn import_candidate_to_enum_paths(suggestion: &ImportSuggestion) -> (String, Str
 pub(super) struct MissingLifetime {
     /// Used to overwrite the resolution with the suggestion, to avoid cascading errors.
     pub id: NodeId,
+    /// As we cannot yet emit lints in this crate and have to buffer them instead,
+    /// we need to associate each lint with some `NodeId`,
+    /// however for some `MissingLifetime`s their `NodeId`s are "fake",
+    /// in a sense that they are temporary and not get preserved down the line,
+    /// which means that the lints for those nodes will not get emitted.
+    /// To combat this, we can try to use some other `NodeId`s as a fallback option.
+    pub related_node_that_exists_in_source: NodeId,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late/diagnostics.rs:111]: Let's call this one id_for_lint, shall we?

File: compiler/rustc_resolve/src/late.rs [hunk 6]
```diff
@@ -2039,8 +2052,44 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
+        match candidate {
+            LifetimeElisionCandidate::Missing(missing @ MissingLifetime { span: elided, .. }) => {
+                debug_assert_eq!(id, missing.id);
+                match res {
+                    LifetimeRes::Static { suppress_elision_warning } => {
+                        if !suppress_elision_warning {
+                            self.r.lint_buffer.buffer_lint(
+                                lint::builtin::ELIDED_NAMED_LIFETIMES,
+                                missing.related_node_that_exists_in_source,
+                                missing.span,
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:2065]: If you destructure a variable, please do it completely. Otherwise it gets confusing.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 5 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late/diagnostics.rs:111]: Fair enough

File: compiler/rustc_resolve/src/late.rs (hunk 6 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:2065]: Fair enough

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (GrigorenkoPV) [reply compiler/rustc_resolve/src/late.rs:1931]: No good reason other than I have overlooked it. I will push a fix soon, and probably rebase as well. It's been quite some time, plus #129510 will probably land soon.

**Comment by cjgillot** [comment]
Thanks for bearing with me through this!
Do you mind adding a suggestion to this lint in a follow-up PR?
@bors r+

**Comment by GrigorenkoPV** [comment]
> Thanks for bearing with me through this!

Thank *you* for your patience and guidance, I appreciate it!

> Do you mind adding a suggestion to this lint in a follow-up PR?

Yes (well, technically "No", I do *not* mind, heh), but a bit later as I'm going to be busy in the next couple of days.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/129591#issuecomment-2309044568

**Comment by saethlin** [comment]
@GrigorenkoPV The PR description makes it look like this PR is very incomplete. This PR description will become part of the commit history of the repo when the PR is merged. Perhaps you want to update the PR description before this merges?

**Comment by cjgillot** [comment]
With the same idea as @saethlin's comment, could you squash the commits? To remove some back-and-forth changes.
r=me then

**Comment by GrigorenkoPV** [comment]
Done!

I've squashed it into three commits:
1. Implementation
2. Fixing the remaining (after #129510) places in code where the lint would fire.
3. Adding & blessing tests.

**Comment by cjgillot** [comment]
Great!
@bors r=

**Comment by cjgillot** [comment]
Typo.
@bors r-

**Comment by kpreid** [comment]
This PR implements a lint named `elided_named_lifetimes`, but that name wasn't previously mentioned literally in any comment, so it doesn't show up in PR search. I hope this comment will fix that.

**Comment by GrigorenkoPV** [comment]
True, thanks for pointing out! I've updated the title.

**Comment by irbull** [comment]
Part of the Deno project is built with Rust +nightly and is being hit by this change-set with the following error:

```
error: elided lifetime has a name
  --> core/runtime/snapshot.rs:32:19
   |
32 | ) -> (V8Snapshot, SerializableSnapshotSidecarData) {
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this elided lifetime gets resolved as `'static`
```

The fix is easy [1], but I thought I would leave this here in case others are being hit by it and hopefully google can index "elided lifetime has a name".

[1] https://github.com/denoland/deno_core/pull/895

**Comment by GrigorenkoPV** [comment]
> The fix is easy

There is an upcoming PR implementing suggestions for this lint https://github.com/rust-lang/rust/pull/129840. Currently it is in a conflict with some of clippy's suggestions, but maybe I can mark it non-machine-applicable for now, so that there are at least human-readable suggestions preventing confusion.

Thank you for your report!
