### PR TITLE
Change a commit_if_ok call to probe

### LINKED ISSUE #105037: Bad generic inference on very recent nightly
We noticed a build error in [Plonky2](https://github.com/mir-protocol/plonky2/) on the nightly build 2022-11-27. The same code was building last week, on a slightly older nightly.

Here's a minimal reproducible example ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=39ee8e12ad9927d7bef46c2b11bd7186)):

```rust
#![feature(generic_const_exprs)]

trait Table<const D: usize>: Sync {
    const COLUMNS: usize;
}

struct Table1<const D: usize>;
impl<const D: usize> Table<D> for Table1<D> {
    const COLUMNS: usize = 123;
}

struct Table2<const D: usize>;
impl<const D: usize> Table<D> for Table2<D> {
    const COLUMNS: usize = 456;
}

fn process_table<T: Table<D>, const D: usize>(table: T)
where
    [(); T::COLUMNS]:,
{
}

fn process_all_tables<const D: usize>()
where
    [(); Table1::<D>::COLUMNS]:,
    [(); Table2::<D>::COLUMNS]:,
{
    process_table(Table1::<D>);
    process_table(Table2::<D>);
}
```

Nightly 2022-11-27 gives this error:
```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
  --> src/lib.rs:28:19
   |
28 |     process_table(Table1::<D>);
   |     ------------- ^^^^^^^^^^^ expected struct `Table2`, found struct `Table1`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected struct `Table2<D>`
              found struct `Table1<D>`
```

It seems to be sensitive to the order of the where clauses, `[(); Table1::<D>::COLUMNS]:` and `[(); Table2::<D>::COLUMNS]:`. I.e. for a `process_table` call, it seems to infer that `T` is whichever `Table` appeared last in the `where` list.

### PR DESCRIPTION
**Pull request by JulianKnodt**
Removes an over-eager `commit_if_ok` which makes inference worse.

I'm not entirely sure whether it's ok to remove the check that types are the same, because casting seems to cause equality checks with incorrect types?

Fixes #105037

r? @BoxyUwU

### CODE REVIEW

**Comment by BoxyUwU** [comment]
replacing this with a `probe` seems right, we dont want to constrain the infer vars in `self.ct` unless we're sure there are no other things that we could have unified with to consider it evaluatable.  It's still not quite right though, we do have to actually constrain the infer vars that `eq` constraints at some point in order to ensure that the const _is_ actually evaluatable. 

What's needed is to have the visitor visit all the consts regardless of it succeeds in unifying with something, and if it succeed in unifying with something (in the probe) track that in `Visitor`. Once the visitor is finished you want to be able to see of all the consts that we were able to unify with, and if there was only one, redo the `eq` and `select_all_or_error()` outside of a probe.

**Comment by JulianKnodt** [comment]
I updated to check for only a single match and commit the change if there is a single one, but somehow this results in an error for the original test case. Is this an issue with the way I implemented it?

**Comment by BoxyUwU** [comment]
the current code only works for a single `ConstEvaluatable` predicate in the paramenv, i.e. if you had `where [(); N +1 + 1]:` and were trying to prove `ConstEvalutable(N + _)` it'd avoid unifying with `1 + 1` or `1` because either would work. 
The test case you're working with has two separate things in param env: `ConstEvaluatable(Table1<D>)` and `ConstEvaluatable(Table2<D>)` so you'll also have to update the for loop to make you a single `Option<Result<Const<'tcx>>, ()>` and do the `ocx.eq` stuff after the for loop instead of inside

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 1]
```diff
@@ -200,22 +199,37 @@ fn satisfied_from_param_env<'tcx>(
...
+                .commit_if_ok(|_| {
+                    let ocx = ObligationCtxt::new_in_snapshot(infcx);
+                    assert!(ocx.eq(&ObligationCause::dummy(), param_env, c.ty(), ct.ty()).is_ok());
+                    assert!(ocx.eq(&ObligationCause::dummy(), param_env, c, ct).is_ok());
+                    if ocx.select_all_or_error().is_empty() { Ok(()) } else { Err(()) }
+                })
+                .is_ok();
+            assert!(is_ok);
+        }
+        return true;
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:230]: You shouldn't return true if you havent rerun the `ocx.eq` and `ocx.select_all_or_error` this will lead to us considering stuff to be evaluatable that actually isnt:
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

fn foo<const N: usize, const M: usize>() -> [(); N + 2]
where
    [(); N + 1]:,
    [(); M + 1]:,
{
    bar()
}

fn bar<const N: usize>() -> [(); N]
where
    [(); N + 1]:,
{
    [(); N]
}

fn main() {}
```
this ICEs with your PR and will be fixed by doing `if let Some(Ok(c)) = single_match {` instead, so that you only return true if there was a single match and you have constrained all the infer vars

**Review by BoxyUwU — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs (hunk 1 above)
Comment (JulianKnodt) [reply compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:228]: While this change does fix this specific case, it does make other cases not evaluatable when they should be.
I'm not sure there's an easy way to fix it without changing more in other places? I tried to return `MentionsInfer` but that didn't seem to work

**Comment by BoxyUwU** [comment]
I think all the CI failures are caused by cases where we have duplicate candidates, i.e. two `N + 1` in the param env, you probably want to avoid setting `single_match` to `Err` instead of `Ok` if the candidate that matched is `==` to the existing `Ok`

**Comment by BoxyUwU** [comment]
Can you add the following as tests:

---
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

fn foo<const N: usize>()
where
    [(); N + 1]:,
    [(); N + 1]:,
{
    bar::<N>();
}

fn bar<const N: usize>()
where
    [(); N + 1]:,
{
}

fn main() {}
```
---
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

const fn both(_: usize, b: usize) -> usize {
    b
}

fn foo<const N: usize>()
where
    [(); both(N + 1, N + 1)]:,
{
    bar::<N>();
}

fn bar<const N: usize>()
where
    [(); N + 1]:,
{
}

fn main() {}
```
---
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

const fn both(_: usize, b: usize) -> usize {
    b
}

fn foo<const N: usize, const M: usize>() -> [(); N + 2]
where
    [(); both(N + 1, M + 1)]:,
{
    bar()
}

fn bar<const N: usize>() -> [(); N]
where
    [(); N + 1]:,
{
    [(); N]
}

fn main() {}
```
---

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 2]
```diff
@@ -200,22 +202,44 @@ fn satisfied_from_param_env<'tcx>(
...
+                if let Some(inner) = v.single_match {
+                    single_match = if let Ok(inner) = inner {
+                        match single_match {
+                            None => Some(Ok(inner)),
+                            Some(Ok(prev)) if prev == inner => Some(Ok(prev)),
+                            Some(_) => Some(Err(())),
+                        }
+                    } else {
+                        Some(Err(()))
+                    };
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:223]:
```suggestion
                single_match = match v.single_match {
                    None => single_match,
                    Some(Ok(c)) => match single_match {
                        None => Some(Ok(c)),
                        Some(Ok(prev)) if prev == c => Some(Ok(prev)),
                        Some(_) => Some(Err(())),
                    },
                    Some(Err(())) => Some(Err(())),
                };
```

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 3]
```diff
@@ -200,22 +202,44 @@ fn satisfied_from_param_env<'tcx>(
...
+    if let Some(Ok(c)) = single_match {
+        let is_ok = infcx
+            .commit_if_ok(|_| {
+                let ocx = ObligationCtxt::new_in_snapshot(infcx);
+                assert!(ocx.eq(&ObligationCause::dummy(), param_env, c.ty(), ct.ty()).is_ok());
+                assert!(ocx.eq(&ObligationCause::dummy(), param_env, c, ct).is_ok());
+                if ocx.select_all_or_error().is_empty() { Ok(()) } else { Err(()) }
+            })
+            .is_ok();
+        assert!(is_ok);
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:239]:
```suggestion
        let ocx = ObligationCtxt::new(infcx);
        assert!(ocx.eq(&ObligationCause::dummy(), param_env, c.ty(), ct.ty()).is_ok());
        assert!(ocx.eq(&ObligationCause::dummy(), param_env, c, ct).is_ok());
        assert!(ocx.select_all_or_error().is_empty());
```

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 4]
```diff
@@ -168,23 +168,25 @@ fn satisfied_from_param_env<'tcx>(
...
-                }
             }) {
-                ControlFlow::BREAK
+                self.single_match = match self.single_match {
+                    None => Some(Ok(c)),
+                    Some(Ok(o)) if o == c => Some(Ok(c)),
+                    Some(_) => Some(Err(())),
+                };
+                ControlFlow::CONTINUE
             } else if let ty::ConstKind::Expr(e) = c.kind() {
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:190]:
```suggestion
            }
            
            if let ty::ConstKind::Expr(e) = c.kind() {
```

Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:190]: And adding this as a test:
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

fn foo<const N: usize>()
where
    [(); N + 1 + 1]:,
{
    bar();
}

fn bar<const N: usize>()
where
    [(); N + 1]:,
{
}

fn main() {}
```

**Comment by BoxyUwU** [comment]
will r+ this once its rebased
