### PR TITLE
Exhaustiveness: reveal opaque types properly

### LINKED ISSUE #117100: ICE: `Unexpected type for 'Single' constructor`
File: /tmp/icemaker/81DF126D24557409A8EFD18AB1CCB3D2E8119C89297C34BA28DE025833020886.rs

auto-reduced (treereduce-rust):
````rust
fn enum_upvar() {
    type T = impl Copy;
    let foo: T = Some((1u32, 2u32));
    let x = move || match foo {
        Foo => (),
        Some((a, b)) => (),
    };
}

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![feature(type_alias_impl_trait)]
// check-pass

fn main() {
    type T = impl Copy;
    let foo: T = Some((1u32, 2u32));
    match foo {
        None => (),
        Some((a, b)) => (),
    }
}

fn upvar() {
    #[derive(Copy, Clone)]
    struct Foo((u32, u32));

    type T = impl Copy;
    let foo: T = Foo((1u32, 2u32));
    let x = move || {
        let Foo((a, b)) = foo;
    };
}

fn enum_upvar() {
    type T = impl Copy;
    let foo: T = Some((1u32, 2u32));
    let x = move || {
        match foo {
            Foo => (),
            Some((a, b)) => (),
        }
    };
}

fn r#struct() {
    #[derive(Copy, Clone)]
    struct Foo((u32, u32));

    type U = impl Copy;
    let foo: U = Foo((1u32, 2u32));
    let Foo((a, b)) = foo;
}

mod only_pattern {
    type T = impl Copy;

    fn foo(foo: T) {
        let (mut x, mut y) = foo;
        x = 42;
        y = "foo";
    }

    type U = impl Copy;

    fn bar(bar: Option<U>) {
        match bar {
            Some((mut x, mut y)) => {
                x = 42;
                y = "foo";
            }
            None => {}
        }
    }
}

mod only_pattern_rpit {
    #[allow(unconditional_recursion)]
    fn foo(b: bool) -> impl Copy {
        let (mut x, mut y) = foo(false);
        x = 42;
        y = "foo";
        if b {
            panic!()
        } else {
            foo(true)
        }
    }

    fn bar(b: bool) -> Option<impl Copy> {
        if b {
            return None;
        }
        match bar(!b) {
            Some((mut x, mut y)) => {
                x = 42;
                y = "foo";
            }
            None => {}
        }
        None
    }
}

````
</p>
</details>

Version information
````
rustc 1.75.0-nightly (e2068cdb0 2023-10-23)
binary: rustc
commit-hash: e2068cdb0964ccbae614ab60cddeed7b24473cdd
commit-date: 2023-10-23
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(non_exhaustive_omitted_patterns_lint) -Wnon-exhaustive-omitted-patterns`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0658]: `impl Trait` in type aliases is unstable
 --> /tmp/icemaker_global_tempdir.XldkPeZXsiM8/rustc_testrunner_tmpdir_reporting.HnpgDO2rOy70/mvce.rs:2:14
  |
2 |     type T = impl Copy;
  |              ^^^^^^^^^
  |
  = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
  = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.XldkPeZXsiM8/rustc_testrunner_tmpdir_reporting.HnpgDO2rOy70/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.XldkPeZXsiM8/rustc_testrunner_tmpdir_reporting.HnpgDO2rOy70/mvce.rs`

warning: unused variable: `x`
 --> /tmp/icemaker_global_tempdir.XldkPeZXsiM8/rustc_testrunner_tmpdir_reporting.HnpgDO2rOy70/mvce.rs:4:9
  |
4 |     let x = move || match foo {
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:688:22: Unexpected type for `Single` constructor: Alias(Opaque, AliasTy { args: [], def_id: DefId(0:6 ~ mvce[9309]::enum_upvar::T::{opaque#0}) })

thread 'rustc' panicked at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/compiler/rustc_errors/src/lib.rs:1659:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f623476917c - std::backtrace_rs::backtrace::libunwind::trace::h4bc45ce9b5e3ecb5
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f623476917c - std::backtrace_rs::backtrace::trace_unsynchronized::h77fef45dac28db31
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f623476917c - std::sys_common::backtrace::_print_fmt::h062a8512ed8cd5cc
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f623476917c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd074e811727bbea6
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f62347cb400 - core::fmt::rt::Argument::fmt::hc0fbbf578e30bc2c
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/core/src/fmt/rt.rs:142:9
   5:     0x7f62347cb400 - core::fmt::write::he36b68adc7e6be82
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f623475d09f - std::io::Write::write_fmt::hf5123e49f0129c06
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/io/mod.rs:1762:15
   7:     0x7f6234768f64 - std::sys_common::backtrace::_print::h6da84f440ebc0da4
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f6234768f64 - std::sys_common::backtrace::print::hc890a71d29bf133e
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f623476bbf7 - std::panicking::default_hook::{{closure}}::h5007462eb02fe0f7
  10:     0x7f623476b95f - std::panicking::default_hook::h74cd236d286fc688
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/panicking.rs:292:9
  11:     0x7f62372af240 - std[2f4a0694a58cda61]::panicking::update_hook::<alloc[fcaa6962a6f8cc73]::boxed::Box<rustc_driver_impl[d38002856561e974]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f623476c338 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3d000bb31fc13980
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/alloc/src/boxed.rs:2021:9
  13:     0x7f623476c338 - std::panicking::rust_panic_with_hook::hcafe47f43a083fd9
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/panicking.rs:735:13
  14:     0x7f6237673784 - std[2f4a0694a58cda61]::panicking::begin_panic::<rustc_errors[fe61904af5203354]::ExplicitBug>::{closure#0}
  15:     0x7f6237665d76 - std[2f4a0694a58cda61]::sys_common::backtrace::__rust_end_short_backtrace::<std[2f4a0694a58cda61]::panicking::begin_panic<rustc_errors[fe61904af5203354]::ExplicitBug>::{closure#0}, !>
  16:     0x7f6237656536 - std[2f4a0694a58cda61]::panicking::begin_panic::<rustc_errors[fe61904af5203354]::ExplicitBug>
  17:     0x7f623764d594 - <rustc_errors[fe61904af5203354]::HandlerInner>::bug::<alloc[fcaa6962a6f8cc73]::string::String>
  18:     0x7f623764d354 - <rustc_errors[fe61904af5203354]::Handler>::bug::<alloc[fcaa6962a6f8cc73]::string::String>
  19:     0x7f62376ece6d - rustc_middle[cdc9403fb0d2bf23]::util::bug::opt_span_bug_fmt::<rustc_span[b1c0d326828bdf7]::span_encoding::Span>::{closure#0}
  20:     0x7f62376d3e4a - rustc_middle[cdc9403fb0d2bf23]::ty::context::tls::with_opt::<rustc_middle[cdc9403fb0d2bf23]::util::bug::opt_span_bug_fmt<rustc_span[b1c0d326828bdf7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f62376d3d08 - rustc_middle[cdc9403fb0d2bf23]::ty::context::tls::with_context_opt::<rustc_middle[cdc9403fb0d2bf23]::ty::context::tls::with_opt<rustc_middle[cdc9403fb0d2bf23]::util::bug::opt_span_bug_fmt<rustc_span[b1c0d326828bdf7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f62357d5a50 - rustc_middle[cdc9403fb0d2bf23]::util::bug::bug_fmt
  23:     0x7f62399529b1 - <rustc_mir_build[b597ffe59bdba8da]::thir::pattern::deconstruct_pat::Constructor>::arity.cold.0
  24:     0x7f623775f0ba - rustc_mir_build[b597ffe59bdba8da]::thir::pattern::usefulness::collect_nonexhaustive_missing_variants
  25:     0x7f62386ff965 - rustc_mir_build[b597ffe59bdba8da]::thir::pattern::usefulness::compute_match_usefulness
  26:     0x7f62355e79c1 - <rustc_mir_build[b597ffe59bdba8da]::thir::pattern::check_match::MatchVisitor as rustc_middle[cdc9403fb0d2bf23]::thir::visit::Visitor>::visit_expr
  27:     0x7f62355e70a9 - <rustc_mir_build[b597ffe59bdba8da]::thir::pattern::check_match::MatchVisitor as rustc_middle[cdc9403fb0d2bf23]::thir::visit::Visitor>::visit_expr
  28:     0x7f62388d468a - rustc_mir_build[b597ffe59bdba8da]::thir::pattern::check_match::check_match
  29:     0x7f62388d4417 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 1usize]>>
  30:     0x7f62388d3e2b - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  31:     0x7f62388d3bdd - rustc_query_impl[7a9350cb63c32305]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f62389ce39c - rustc_mir_build[b597ffe59bdba8da]::build::mir_built
  33:     0x7f62389ce1bb - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7f623849a96c - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  35:     0x7f623849a350 - rustc_query_impl[7a9350cb63c32305]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f623664cd2e - rustc_mir_transform[9daa006cdf909815]::check_unsafety::unsafety_check_result
  37:     0x7f623849a747 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7f623849a96c - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  39:     0x7f623849a410 - rustc_query_impl[7a9350cb63c32305]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f62366500ce - rustc_mir_transform[9daa006cdf909815]::check_unsafety::unsafety_check_result
  41:     0x7f623849a747 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7f623849a96c - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  43:     0x7f623849a410 - rustc_query_impl[7a9350cb63c32305]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f623849b45a - rustc_mir_transform[9daa006cdf909815]::mir_const
  45:     0x7f623849b3a7 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  46:     0x7f623849a96c - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  47:     0x7f623849a4d0 - rustc_query_impl[7a9350cb63c32305]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7f62368c6c73 - rustc_mir_transform[9daa006cdf909815]::mir_promoted
  49:     0x7f62388d4d92 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 16usize]>>
  50:     0x7f62388d4fea - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  51:     0x7f62388d4c93 - rustc_query_impl[7a9350cb63c32305]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7f6239185603 - rustc_borrowck[14a9d49ebe9cc411]::mir_borrowck
  53:     0x7f623918556f - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  54:     0x7f623849a96c - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::VecCache<rustc_span[b1c0d326828bdf7]::def_id::LocalDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  55:     0x7f623849a590 - rustc_query_impl[7a9350cb63c32305]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  56:     0x7f62373c72fa - <rustc_hir_analysis[4f5f2fc3d25550fe]::collect::type_of::opaque::TaitConstraintLocator>::check
  57:     0x7f62373b8050 - <rustc_hir_analysis[4f5f2fc3d25550fe]::collect::type_of::opaque::TaitConstraintLocator as rustc_hir[101d9aa3d11e5aaf]::intravisit::Visitor>::visit_item
  58:     0x7f6238e1396d - rustc_hir_analysis[4f5f2fc3d25550fe]::collect::type_of::type_of_opaque
  59:     0x7f6238e1315b - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  60:     0x7f6238461205 - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::DefaultCache<rustc_span[b1c0d326828bdf7]::def_id::DefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  61:     0x7f62392ce3a2 - rustc_query_impl[7a9350cb63c32305]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  62:     0x7f623851fdfb - rustc_middle[cdc9403fb0d2bf23]::query::plumbing::query_get_at::<rustc_query_system[36043fee951be75c]::query::caches::DefaultCache<rustc_span[b1c0d326828bdf7]::def_id::DefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>>
  63:     0x7f6238464149 - rustc_hir_analysis[4f5f2fc3d25550fe]::collect::type_of::type_of
  64:     0x7f6238461e69 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>
  65:     0x7f6238461205 - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::DefaultCache<rustc_span[b1c0d326828bdf7]::def_id::DefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  66:     0x7f6238460e2b - rustc_query_impl[7a9350cb63c32305]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  67:     0x7f623851fdfb - rustc_middle[cdc9403fb0d2bf23]::query::plumbing::query_get_at::<rustc_query_system[36043fee951be75c]::query::caches::DefaultCache<rustc_span[b1c0d326828bdf7]::def_id::DefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 8usize]>>>
  68:     0x7f6238fcedeb - rustc_hir_analysis[4f5f2fc3d25550fe]::check::check::check_mod_item_types
  69:     0x7f6238fcd78d - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 0usize]>>
  70:     0x7f6238a6ec08 - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::DefaultCache<rustc_span[b1c0d326828bdf7]::def_id::LocalModDefId, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  71:     0x7f6238a6e59b - rustc_query_impl[7a9350cb63c32305]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  72:     0x7f62386c1ff5 - rustc_hir_analysis[4f5f2fc3d25550fe]::check_crate
  73:     0x7f6238a7111f - rustc_interface[1301374836cf4118]::passes::analysis
  74:     0x7f6238a70b21 - rustc_query_impl[7a9350cb63c32305]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a9350cb63c32305]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 1usize]>>
  75:     0x7f6238ee3826 - rustc_query_system[36043fee951be75c]::query::plumbing::try_execute_query::<rustc_query_impl[7a9350cb63c32305]::DynamicConfig<rustc_query_system[36043fee951be75c]::query::caches::SingleCache<rustc_middle[cdc9403fb0d2bf23]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7a9350cb63c32305]::plumbing::QueryCtxt, false>
  76:     0x7f6238ee3655 - rustc_query_impl[7a9350cb63c32305]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  77:     0x7f623912bfcd - std[2f4a0694a58cda61]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1301374836cf4118]::util::run_in_thread_with_globals<rustc_interface[1301374836cf4118]::interface::run_compiler<core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>, rustc_driver_impl[d38002856561e974]::run_compiler::{closure#1}>::{closure#0}, core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>>
  78:     0x7f623912b2b3 - <<std[2f4a0694a58cda61]::thread::Builder>::spawn_unchecked_<rustc_interface[1301374836cf4118]::util::run_in_thread_with_globals<rustc_interface[1301374836cf4118]::interface::run_compiler<core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>, rustc_driver_impl[d38002856561e974]::run_compiler::{closure#1}>::{closure#0}, core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c6e87b24e6e70e4]::result::Result<(), rustc_span[b1c0d326828bdf7]::ErrorGuaranteed>>::{closure#1} as core[5c6e87b24e6e70e4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  79:     0x7f6234777105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h57e353e84f121ba4
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/alloc/src/boxed.rs:2007:9
  80:     0x7f6234777105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h85e27837fb36d5ba
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/alloc/src/boxed.rs:2007:9
  81:     0x7f6234777105 - std::sys::unix::thread::Thread::new::thread_start::h7366c40575a243da
                               at /rustc/e2068cdb0964ccbae614ab60cddeed7b24473cdd/library/std/src/sys/unix/thread.rs:108:17
  82:     0x7f62345409eb - <unknown>
  83:     0x7f62345c47cc - <unknown>
  84:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.75.0-nightly (e2068cdb0 2023-10-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(non_exhaustive_omitted_patterns_lint) -Z dump-mir-dir=dir

query stack during panic:
#0 [check_match] match-checking `enum_upvar::{closure#0}`
#1 [mir_built] building MIR for `enum_upvar::{closure#0}`
#2 [unsafety_check_result] unsafety-checking `enum_upvar::{closure#0}`
#3 [unsafety_check_result] unsafety-checking `enum_upvar`
#4 [mir_const] preparing `enum_upvar` for borrow checking
#5 [mir_promoted] promoting constants in MIR for `enum_upvar`
#6 [mir_borrowck] borrow-checking `enum_upvar`
#7 [type_of_opaque] computing type of opaque `enum_upvar::T::{opaque#0}`
#8 [type_of] computing type of `enum_upvar::T::{opaque#0}`
#9 [check_mod_item_types] checking item types in top-level module
#10 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0601, E0658.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by Nadrieril**
Previously, exhaustiveness had no clear policy around opaque types. In this PR I propose the following policy: within the body of an item that defines the hidden type of some opaque type, exhaustiveness checking on a value of that opaque type is performed using the concrete hidden type inferred in this body.

I'm not sure how consistent this is with other operations allowed on opaque types; I believe this will require FCP.

From what I can tell, this doesn't change anything for non-empty types.

The observable changes are:
- when the real type is uninhabited, matches within the defining scopes can now rely on that for exhaustiveness, e.g.:

```rust
#[derive(Copy, Clone)]
enum Void {}
fn return_never_rpit(x: Void) -> impl Copy {
    if false {
        match return_never_rpit(x) {}
    }
    x
}
```
- this properly fixes ICEs like https://github.com/rust-lang/rust/issues/117100 that occurred because a same match could have some patterns where the type is revealed and some where it is not.

Bonus subtle point: if `x` is opaque, a match like `match x { ("", "") => {} ... }` will constrain its type ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=901d715330eac40339b4016ac566d6c3)). This is not the case for `match x {}`: this will not constain the type, and will only compile if something else constrains the type to be empty.

Fixes https://github.com/rust-lang/rust/issues/117100

r? @oli-obk 

Edited for precision of the wording

[Included](https://github.com/rust-lang/rust/pull/116821#issuecomment-1813171764) in the FCP on this PR is this rule:

> Within the body of an item that defines the hidden type of some opaque type, exhaustiveness checking on a value of that opaque type is performed using the concrete hidden type inferred in this body.

### CODE REVIEW

File: tests/ui/type-alias-impl-trait/issue-96572-unconstrained.rs [hunk 1]
```diff
@@ -63,6 +61,19 @@ mod only_pattern {
...
+    fn baz(baz: Option<V>) {
+        match baz {
+            _ => {}
+            Some((mut x, mut y)) => {
+                x = 42;
+                y = "foo";
+            }
+            None => {}
+        }
+    }
```
Comment (oli-obk) [inline tests/ui/type-alias-impl-trait/issue-96572-unconstrained.rs:76]: What is this testing? It works on nightly already.

Comment (Nadrieril) [reply tests/ui/type-alias-impl-trait/issue-96572-unconstrained.rs:76]: That caused an ICE in the one-pass rewrite I'm working on, I thought I'd add it defensively

Comment (Nadrieril) [reply tests/ui/type-alias-impl-trait/issue-96572-unconstrained.rs:76]: It's a case where the first pattern also has an opaque type, so looking at the first pattern can't save us. I think it ICEs one of my other open PRs even

**Comment by Nadrieril** [comment]
@oli-obk I explained what I'm proposing in the OP, and added a bunch of tests.

@rustbot ready

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 2]
```diff
@@ -358,6 +359,21 @@ impl<'a, 'tcx> MatchCheckCtxt<'a, 'tcx> {
             _ => false,
         }
     }
+
+    /// Type inference occasionally gives us opaque types in places where corresponding patterns
+    /// have more specific types. To avoid inconsistencies as well as detect opaque uninhabited
+    /// types, we use the corresponding concrete type if possible.
+    fn reveal_opaque_ty(&self, ty: Ty<'tcx>) -> Ty<'tcx> {
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:366]: Do you only care about opaque types themselves, or also about types containing opaque types? Something like `match (42, recur()) {}` may have similar issues if `recur()` is returning a diverging, but opaque type

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:366]: Ah yes that's the subtle point I hinted at: in a case like this I rely on `Ty::inhabited_predicate` to tell me about inhabitedness, but `Ty::inhabited_predicate` never looks into opaque types. This is inconsistent: `match (42, recur()) {}` would error "type is not empty", yet
```rust
match (42, recur()) {
  (0, _) => {}
}
```
would report the arm as unreachable (if `exhaustive_patterns` is turned on or eventually stabilized).

For consistency I think `Ty::inhabited_predicate` should look into opaques, but I don't know the ramifications that could have. Plus it currently tracks the visibility of inhabitedness at a module granularity, and this would require function granularity.

**Comment by Nadrieril** [comment]
I added a remark to the OP regarding the fact that `match x {}` is not used by type inference to constrain an opaque type.

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs (hunk 2 above)
Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:366]: It's even more inconsistent than that: the first is accepted, and the second warns as unreachable:
```rust
match (42, recur()) {
  _ => {}
}
match (42, recur()) {
  (_, _) => {}
}
```
(This is under `exhaustive_patterns` only for now. None of these inconsistencies are observable on stable rust because exhaustiveness treats nested empty types as nonempty)

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:366]: > Alternatively you can make reveal_opaque_ty be a type folder

Oh I didn't know about `ty.has_opaque_types()`! Yeah that could work, I like that idea. With the added benefit that if I'm careful I'll only need a single `reveal_opaque_types` on the scrutinee type at the start, and then I'd be operating on fully revealed types

Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:366]: I don't think it will have a perf effect in practice, we do similar operations elsewhere in the compiler regularly. So yea, please add it to this PR

**Comment by Nadrieril** [comment]
At the suggestion of @oli-obk I now reveal opaque types in depth, which solves an inconsistency I had. I've updated the OP.

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs (hunk 2 above)
Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs]: Done. Could you have a quick look at my `TypeFolder` impl? It's my first one.

> I don't think it will have a perf effect in practice

Ok :+1:. Before `inhabitedness_predicate` was a query, the checks for `is_uninhabited` all around exhaustiveness had a [significant perf impact](https://github.com/rust-lang/rust/pull/79394#issuecomment-733706939) so I'm extra careful now x)

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs]: Ah, it explodes on recursive types https://github.com/Nadrieril/rust/blob/fix-opaque-ice/tests/ui/type-alias-impl-trait/recursive-fn-tait.rs . Do you know how I could avoid that?

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs]: Alright I've got a solution but I'm not fully satisfied: when I detect a recursive loop, I leave the opaque as-is, i.e. unrevealed. Even though I technically have enough information to reveal it. E.g.:
```rust
type W = impl Copy;
#[derive(Copy, Clone)]
struct Rec<'a> {
    n: u32,
    w: Option<&'a W>,
}
fn recursive_opaque() -> W {
    if true {
        match recursive_opaque() {
            Rec { n: 0, w: Some(Rec { n: 0, w: _ }) } => {}
            _ => {}
        }
    }
    Rec { n: 0, w: None }
}
```

In a case like this, at the start of exhaustiveness I try to reveal the type but only reveal the first layer. This is fine currently because I call `reveal_opaque` all the time, but I hope this won't bite me later.

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/usefulness.rs]: Scratch that, type folding does not recurse into the fields of an ADT anyway. My solution is fine.

File: tests/ui/pattern/usefulness/impl-trait.rs [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+        }
+    }
+}
+
+type W = impl Copy;
+#[derive(Copy, Clone)]
+struct Rec<'a> {
+    n: u32,
+    w: Option<&'a W>,
+}
```
[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:110]: Oh good point! Typeck doesn't let me however, I'm not entirely sure why

[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:110]: Actually what issue do you mean? I added a commit where I detect opaque cycles when revealing, so I won't crash there. Moreover it seems such a type is rejected by typeck anyway, even if the error is cryptic.

If you mean the ICEs because of unrevealed opaques in exhaustiveness, my conclusion is that `reveal_opaque_ty` simply cannot reveal all the things, so I need to keep revealing opaques at each depth.

[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:110]: Oh wait, so this doesn't detect uninhabitedness everywhere actually:
```rust
type X = impl Copy;
struct SecretelyVoid(X);
fn nested_empty_opaque(x: Void) -> X {
    if true {
        let opaque_void = nested_empty_opaque(x);
        let secretely_void = SecretelyVoid(opaque_void);
        match secretely_void {}
    }
    x
}
```
Since the `TypeFolder` doesn't recurse into the struct fields, it doesn't reveal the opaque and `uninhabitedness_predicate` thinks it's nonempty.

[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:110]: I see three options:
- ignore inconsistency
- recurse through ADT fields too (would require building new `AdtDef`s etc, doesn't sound good)
- make `Ty::inhabited_predicate` work at the function granularity and inspect opaques (would make rustc as a whole more consistent on this front, which may or may not break things)

I'm partial to option 1, especially since the difference cannot be observed without `exhaustive_patterns`. This could be a blocker for its stabilization however.

[the remark this answers is not in the document]
Comment (compiler-errors) [reply tests/ui/pattern/usefulness/impl-trait.rs:110]: Let's stay with option 1. I would really appreciate if you note this inconsistency in the `exhaustive_patterns` tracking issue, though, for future stabilization to revisit.

**Review by compiler-errors — APPROVED** [review]
Implementation looks fine to me. Marking as waiting-on-fcp.

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:111]: Will do!

File: tests/ui/pattern/usefulness/impl-trait.rs [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+
+fn return_never_rpit(x: Void) -> impl Copy {
+    if false {
+        match return_never_rpit(x) {}
+    }
+    x
+}
+fn friend_of_return_never_rpit(x: Void) {
+    match return_never_rpit(x) {}
+}
```
Comment (Nadrieril) [inline tests/ui/pattern/usefulness/impl-trait.rs:22]: Hum, something weird happened after I rebased on a more recent master: before, `typeck_results.concrete_opaque_types` only had a revealed type for an opaque if we were in a defining use. This seems to no longer be the case. `friend_of_return_never_rpit` above used to error "impl Copy is not empty" as it should, and after the rebase it doesn't :'(

@compiler-errors do you happen to know how I can check if the thir body I am inspecting is within a defining use of a given opaque?

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:111]: (if/when this gets merged)

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 4 above)
Comment (compiler-errors) [reply tests/ui/pattern/usefulness/impl-trait.rs:22]: I checked out your PR and this function emits:

```
error[E0004]: non-exhaustive patterns: type `impl Copy` is non-empty
  --> /home/gh-compiler-errors/test.rs:21:11
   |
21 |     match return_never_rpit(x) {}
   |           ^^^^^^^^^^^^^^^^^^^^
   |
   = note: the matched value is of type `impl Copy`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown
   |
21 ~     match return_never_rpit(x) {
22 +         _ => todo!(),
23 +     }
```

Comment (compiler-errors) [reply tests/ui/pattern/usefulness/impl-trait.rs:22]: This may be due to #117416. Try reverting it and seeing if it restores your error message?

**Comment by tmandry** [comment]
> within the defining scope of an `impl Trait` opaque type, exhaustiveness uses the real type

Could you clarify how this interacts with TAITs? I assume only items that constrain the real type are allowed to see it?

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 4 above)
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:22]: Ah, so as you suggested the issue comes from other errors making the compiler not continue with checking things. No opaque type was revealed more than it should; `typeck_results.concrete_opaque_types` is still reliable.

Reverting your PR did not restore my error message. However, removing [this part](https://github.com/Nadrieril/rust/blob/7dca8df557bbede09ee24c1d3e491e03edf21378/tests/ui/pattern/usefulness/impl-trait.rs#L47-L50) of an unrelated function body did fix it! So all is good.

No longer relevant to this PR, but: I'm pretty surprised by the action-at-a-distance here, any idea what caused it?

**Comment by RalfJung** [comment]
> when the real type is uninhabited, matches within the defining scopes can now rely on that for exhaustiveness, e.g.:

To clarify: so matches *outside* the defining scope can *not* rely on unhabitedness for exhaustiveness? Do we have tests covering this?

**Comment by Nadrieril** [comment]
> To clarify: so matches outside the defining scope can not rely on unhabitedness for exhaustiveness? Do we have tests covering this?

Indeed, and we do have tests, except I need to fix them because they're not triggering since the latest rebase for unrelated reasons

**Comment by traviscross** [comment]
> In this PR I propose the following policy: within the defining scope of an `impl Trait` opaque type, exhaustiveness uses the real type. From what I can tell, this doesn't change anything for non-empty types.

It would be more clear to state this rule as:

> Within the body of an item that is allowed to define the hidden type of an opaque type, exhaustiveness checking is performed using the concrete hidden type.

Stating it in this way removes any ambiguities created by the details of how the "defining scope" is defined.

**Comment by lcnr** [comment]
If I can refine it even further, I would specify it as

> Within the body of an item that is allowed to define the hidden type of an opaque type, exhaustiveness checking is performed using the concrete hidden type **inferred by this body**.

Assuming we'll ever allow non-defining uses in the defining scope, functions which do not define opaque types but could are not allowed to use the hidden type defined by a different item.

**Comment by traviscross** [comment]
OK, then we should probably say:

> Within the body of an item that defines the hidden type of some opaque type, exhaustiveness checking on a value of that opaque type is performed using the concrete hidden type inferred in this body.

**Comment by Nadrieril** [comment]
Is there not already a notion of "items that are allowed to know the hidden type" we could piggy-back on? It seems this is what you both are trying to nail down

**Comment by compiler-errors** [comment]
There is no such thing as an "item that is allowed to know the hidden type". Either it defines the hidden type locally, or it (via leak) reveals the hidden type via an auto trait bound.

This is what lcnr was trying to say with:

> functions which do not define opaque types **but could** are not allowed to use the hidden type defined by a different item.

(emphasis mine)

I'm pretty satisfied with this statement:

> Within the body of an item that *8defines the hidden type of some opaque type**, exhaustiveness checking on a value of that opaque type is performed using the concrete hidden type inferred in this body.

(again, emphasis mine)

**Comment by Nadrieril** [comment]
Is the "inferred in this body" necessary? I seem to understand there must be a unique inferred type, so if an item defines the hidden type, specifying "inferred in this body" is redundant?

**Comment by compiler-errors** [comment]
Yes. Opaque type inference is done per body, and the inferred value of opaque types are only mapped back to a canonical set of parameters and compared for equality *after* mir borrowck.

This limitation is also implicitly encoded in the implementation in this PR, since we're looking at the current function's [`TypeckResults`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TypeckResults.html#structfield.concrete_opaque_types) for hidden types to look at during exhaustiveness checking.

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 4 above)
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs:22]: Actually if you had a clue that could simplify testing. If you don't I'll just make a bunch of separate test files

**Comment by traviscross** [comment]
This issue remains T-lang nominated.  In addition to discussing to potentially attract more check boxes, we want to confirm with T-lang that the following statement should be the rule for Rust:

> Within the body of an item that defines the hidden type of some opaque type, exhaustiveness checking on a value of that opaque type is performed using the concrete hidden type inferred in this body.

**Comment by tmandry** [comment]
@rfcbot reviewed

File: tests/ui/pattern/usefulness/impl-trait.rs (hunk 4 above)
Comment (Nadrieril) [reply tests/ui/pattern/usefulness/impl-trait.rs]: Tests are fixed

**Comment by Nadrieril** [comment]
Is there a process by which I can ping the lang team to check their boxes? It sounded like they were pretty much ok with the proposal

**Comment by aliemjay** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

(Also, @Nadrieril, pinging on Zulip is just fine)

**Comment by lcnr** [comment]
marked as reviewed for @oli-obk. They are on leave and after asking them in private:

> Just check my box. I'll review my notifications at some point

**Comment by Nadrieril** [comment]
@compiler-errors I've rebased this a few times since you reviewed it. Do you want to have another look or can I r=you?

**Review by compiler-errors — APPROVED** [review]

**Comment by Nadrieril** [comment]
The error does not seem related to this PR (and I can't reproduce it)

@bors retry
