### PR TITLE
s390x: Fix a regression related to backchain feature

### LINKED ISSUE #129927: s390x-unknown-linux-gnu: cfg!(target_feature = "backchain") is always true
https://github.com/rust-lang/rust/pull/127506 introduced what I think is a logic error: `cfg!(target_feature = "backchain")` is now always `true` on s390x targets, even if the feature gate is not set. I verified this with Miri, which shares the `cfg` logic with rustc so it should be a correct test.

This should print `false` when built without `-Ctarget-feature=+backchain` (as the feature seems off-by-default), but prints `true` instead:
```rust
fn main() {
    dbg!(cfg!(target_feature = "backchain"));
}
```

Cc @liushuyu

### PR DESCRIPTION
**Pull request by liushuyu**
In #127506, we introduced a new IBM Z-specific target feature, `backchain`.

This particular `target-feature` was available as a function-level attribute in LLVM 17 and below, so some hacks were used to avoid blowing up LLVM when querying the supported LLVM features.

This led to an unfortunate regression where `cfg!(target-feature = "backchain")` will always return true.

This pull request aims to fix this issue, and a test has been introduced to ensure it will never happen again.

Fixes #129927.

r? @RalfJung

### CODE REVIEW

File: tests/assembly/s390x-backchain-toggle.rs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    // enable-backchain-NEXT: lghi %r2, 1
+    // disable-backchain: lghi %r2, 0
+    #[cfg(target_feature = "backchain")]
+    {
+        1
+    }
+    #[cfg(not(target_feature = "backchain"))]
+    {
+        0
+    }
```
Comment (RalfJung) [inline tests/assembly/s390x-backchain-toggle.rs:39]: Isn't this the same as `cfg!(target_feature = "backchain") as i32`?

File: tests/assembly/s390x-backchain-toggle.rs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    // enable-backchain-NEXT: aghi %r15, -160
+    // enable-backchain: stg [[REG1]], 0(%r15)
+    // disable-backchain: aghi %r15, -160
+    // disable-backchain-NOT: stg %r{{.*}}, 0(%r15)
+    unsafe {
+        extern_func();
+    }
+    // enable-backchain-NEXT: brasl %r{{.*}}, extern_func@PLT
+    // enable-backchain-NEXT: lghi %r2, 1
+    // disable-backchain: lghi %r2, 0
```
Comment (RalfJung) [inline tests/assembly/s390x-backchain-toggle.rs:31]: Is `lghi %r2` setting the return value here?

(I can't read assembly code, I am afraid. I would have written this test differently but I guess the stuff above, with `extern_func`, tests whether "backchain" is passed to LLVM? So this test covers more than what I could have covered.)

Comment (liushuyu) [reply tests/assembly/s390x-backchain-toggle.rs:36]: > Is `lghi %r2` setting the return value here?

Yes, `lghi` on s390x is "Load Halfword Immediate". `%r2` register is the first return argument register on s390x when running a Linux-based system in Z-mode (see https://github.com/IBM/s390x-abi/releases/tag/v1.6.1, the addresses are 64-bit).

> (I can't read assembly code, I am afraid. I would have written this test differently but I guess the stuff above, with extern_func, tests whether "backchain" is passed to LLVM? So this test covers more than what I could have covered.)

The test is an assembly scanning test because different LLVM versions may interpret attributes differently. Scanning the resulting assembly is a more robust way to detect if the "backchain" option is passed down correctly.

File: tests/assembly/s390x-backchain-toggle.rs (hunk 1 above)
Comment (liushuyu) [reply tests/assembly/s390x-backchain-toggle.rs:39]: > Isn't this the same as `cfg!(target_feature = "backchain") as i32`?

Yes, but I have used `#![no_core]` so `cfg!` macro isn't available in the scope. Should I just declare this macro in the file?

Comment (RalfJung) [reply tests/assembly/s390x-backchain-toggle.rs:39]: Ah, fair. Yeah this is fine then.

File: tests/assembly/s390x-backchain-toggle.rs [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    // enable-backchain: lgr [[REG1:.*]], %r15
+    // enable-backchain-NEXT: aghi %r15, -160
+    // enable-backchain: stg [[REG1]], 0(%r15)
+    // disable-backchain: aghi %r15, -160
+    // disable-backchain-NOT: stg %r{{.*}}, 0(%r15)
+    unsafe {
+        extern_func();
+    }
+    // enable-backchain-NEXT: brasl %r{{.*}}, extern_func@PLT
+    // enable-backchain-NEXT: lghi %r2, 1
```
Comment (RalfJung) [inline tests/assembly/s390x-backchain-toggle.rs:30]:
```suggestion

    // Make sure that the expected return value is written into %r2.
    // enable-backchain-NEXT: lghi %r2, 1
```

Comment (liushuyu) [reply tests/assembly/s390x-backchain-toggle.rs:30]: Okay, I can annotate all the check statements.

Comment (RalfJung) [reply tests/assembly/s390x-backchain-toggle.rs:30]: That one is enough for me, but I wont complain about more comments :)

Comment (liushuyu) [reply tests/assembly/s390x-backchain-toggle.rs:34]: Done

File: tests/assembly/s390x-backchain-toggle.rs [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    // And also if a new parameter area (160 bytes) is allocated for the upcoming function call
+    // enable-backchain: lgr [[REG1:.*]], %r15
+    // enable-backchain-NEXT: aghi %r15, -160
+    // enable-backchain: stg [[REG1]], 0(%r15)
+    // disable-backchain: aghi %r15, -160
+    // disable-backchain-NOT: stg %r{{.*}}, 0(%r15)
+    unsafe {
+        extern_func();
+    }
+    // enable-backchain-NEXT: brasl %r{{.*}}, extern_func@PLT
```
Comment (RalfJung) [inline tests/assembly/s390x-backchain-toggle.rs:31]: Shouldn't there also be some check in `disable-backchain` mode that covers the actual call of `extern_func`?

Comment (liushuyu) [reply tests/assembly/s390x-backchain-toggle.rs:31]: Done

**Comment by RalfJung** [comment]
Thanks :)

@bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r-
might cause a crash here?  https://github.com/rust-lang/rust/pull/129984#issuecomment-2332279530

**Comment by liushuyu** [comment]
> @bors r- might cause a crash here? [#129984 (comment)](https://github.com/rust-lang/rust/pull/129984#issuecomment-2332279530)

I can't reproduce it on my local device (Linux). Unfortunately, I don't own an Apple device to test the issue

**Comment by matthiaskrgr** [comment]
mmh, lets see if this can land on its own then 

@bors r=RalfJung rollup=iffy

**Comment by RalfJung** [comment]
Sounds unlikely that this PR would lead to an LLVM crash... I guess we'll see.
