### PR TITLE
Handle regions equivalent to 'static in non_local_bounds

### LINKED ISSUE #122704: ICE: `can't find an upper bound` in nll::compute_regions in rustc_borrowck
### Code

```Rust
use std::any::Any;

pub struct Foo {
    bar: Box<dyn for<'a> Fn(&'a usize) -> Box<dyn Any + 'a>>,
}

impl Foo {
    pub fn ack<I>(&mut self, f: impl for<'a> Fn(&'a usize) -> Box<I>) {
        self.bar = Box::new(|baz| Box::new(f(baz)));
    }
}

fn main() {}
```
### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (eb45c8444 2024-03-17)
binary: rustc
commit-hash: eb45c844407968ea54df0d9870ebce9e3235b706
commit-date: 2024-03-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/type_check/free_region_relations.rs:97:9:
can't find an upper bound!?
stack backtrace:
   0:     0x7fcf37ef030f - std::backtrace_rs::backtrace::libunwind::trace::hd1b8e7bf69bd2659
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7fcf37ef030f - std::backtrace_rs::backtrace::trace_unsynchronized::ha2541878f17a8bf5
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fcf37ef030f - std::backtrace::Backtrace::create::h2489761f8d713f8d
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/backtrace.rs:331:13
   3:     0x7fcf37ef0250 - std::backtrace::Backtrace::force_capture::h212b9648ae6a4e34
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/backtrace.rs:312:9
   4:     0x7fcf3af33762 - std[f30794364a8567e8]::panicking::update_hook::<alloc[d4fc0c1400399e53]::boxed::Box<rustc_driver_impl[977aa2f7506c0463]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7fcf37f0ab50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he9235fc142cfefbc
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/alloc/src/boxed.rs:2034:9
   6:     0x7fcf37f0ab50 - std::panicking::rust_panic_with_hook::hcb10f10b9294465e
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/panicking.rs:783:13
   7:     0x7fcf37f0a859 - std::panicking::begin_panic_handler::{{closure}}::h1df158136e631df7
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/panicking.rs:649:13
   8:     0x7fcf37f07de6 - std::sys_common::backtrace::__rust_end_short_backtrace::h3eabad15a30d1baa
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7fcf37f0a5c4 - rust_begin_unwind
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/panicking.rs:645:5
  10:     0x7fcf37f551a5 - core::panicking::panic_fmt::hc408b30751ce7310
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/core/src/panicking.rs:72:14
  11:     0x7fcf3ad4253d - <rustc_borrowck[19dbd917483b2da6]::type_check::free_region_relations::UniversalRegionRelations>::non_local_upper_bounds
  12:     0x7fcf39a48644 - rustc_borrowck[19dbd917483b2da6]::nll::compute_regions
  13:     0x7fcf3d1605ef - rustc_borrowck[19dbd917483b2da6]::do_mir_borrowck
  14:     0x7fcf3c349228 - rustc_borrowck[19dbd917483b2da6]::mir_borrowck
  15:     0x7fcf3c348d17 - rustc_query_impl[29f35dd1a1f5675d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[29f35dd1a1f5675d]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7fcf3c34ad2e - rustc_query_system[7e5eced594b3b3e4]::query::plumbing::try_execute_query::<rustc_query_impl[29f35dd1a1f5675d]::DynamicConfig<rustc_query_system[7e5eced594b3b3e4]::query::caches::VecCache<rustc_span[30575adc3f012a9d]::def_id::LocalDefId, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[29f35dd1a1f5675d]::plumbing::QueryCtxt, false>
  17:     0x7fcf3c34a84c - rustc_query_impl[29f35dd1a1f5675d]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7fcf3cc5d29c - rustc_middle[e264bbe93e45f6ca]::query::plumbing::query_get_at::<rustc_query_system[7e5eced594b3b3e4]::query::caches::VecCache<rustc_span[30575adc3f012a9d]::def_id::LocalDefId, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 8usize]>>>
  19:     0x7fcf3cc5d30e - <rustc_borrowck[19dbd917483b2da6]::type_check::TypeChecker>::prove_closure_bounds
  20:     0x7fcf3c6873a3 - <rustc_borrowck[19dbd917483b2da6]::type_check::TypeChecker>::typeck_mir
  21:     0x7fcf39a024ea - rustc_borrowck[19dbd917483b2da6]::type_check::type_check
  22:     0x7fcf39a3c137 - rustc_borrowck[19dbd917483b2da6]::nll::compute_regions
  23:     0x7fcf3d1605ef - rustc_borrowck[19dbd917483b2da6]::do_mir_borrowck
  24:     0x7fcf3c349228 - rustc_borrowck[19dbd917483b2da6]::mir_borrowck
  25:     0x7fcf3c348d17 - rustc_query_impl[29f35dd1a1f5675d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[29f35dd1a1f5675d]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7fcf3c34ad2e - rustc_query_system[7e5eced594b3b3e4]::query::plumbing::try_execute_query::<rustc_query_impl[29f35dd1a1f5675d]::DynamicConfig<rustc_query_system[7e5eced594b3b3e4]::query::caches::VecCache<rustc_span[30575adc3f012a9d]::def_id::LocalDefId, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[29f35dd1a1f5675d]::plumbing::QueryCtxt, false>
  27:     0x7fcf3c34a84c - rustc_query_impl[29f35dd1a1f5675d]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7fcf3c61d95d - rustc_interface[2a44f2ea1a7c30d3]::passes::analysis
  29:     0x7fcf3c61cb19 - rustc_query_impl[29f35dd1a1f5675d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[29f35dd1a1f5675d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 1usize]>>
  30:     0x7fcf3cfc7ec3 - rustc_query_system[7e5eced594b3b3e4]::query::plumbing::try_execute_query::<rustc_query_impl[29f35dd1a1f5675d]::DynamicConfig<rustc_query_system[7e5eced594b3b3e4]::query::caches::SingleCache<rustc_middle[e264bbe93e45f6ca]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[29f35dd1a1f5675d]::plumbing::QueryCtxt, false>
  31:     0x7fcf3cfc7c3f - rustc_query_impl[29f35dd1a1f5675d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fcf3cdf3084 - rustc_interface[2a44f2ea1a7c30d3]::interface::run_compiler::<core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>, rustc_driver_impl[977aa2f7506c0463]::run_compiler::{closure#0}>::{closure#0}
  33:     0x7fcf3cedf685 - std[f30794364a8567e8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2a44f2ea1a7c30d3]::util::run_in_thread_with_globals<rustc_interface[2a44f2ea1a7c30d3]::util::run_in_thread_pool_with_globals<rustc_interface[2a44f2ea1a7c30d3]::interface::run_compiler<core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>, rustc_driver_impl[977aa2f7506c0463]::run_compiler::{closure#0}>::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>
  34:     0x7fcf3cedf4b2 - <<std[f30794364a8567e8]::thread::Builder>::spawn_unchecked_<rustc_interface[2a44f2ea1a7c30d3]::util::run_in_thread_with_globals<rustc_interface[2a44f2ea1a7c30d3]::util::run_in_thread_pool_with_globals<rustc_interface[2a44f2ea1a7c30d3]::interface::run_compiler<core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>, rustc_driver_impl[977aa2f7506c0463]::run_compiler::{closure#0}>::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[451cccbd72d71aca]::result::Result<(), rustc_span[30575adc3f012a9d]::ErrorGuaranteed>>::{closure#1} as core[451cccbd72d71aca]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7fcf37f141e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h746ad893ba25d760
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/alloc/src/boxed.rs:2020:9
  36:     0x7fcf37f141e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b3d742dc2cb92e7
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/alloc/src/boxed.rs:2020:9
  37:     0x7fcf37f141e5 - std::sys::pal::unix::thread::Thread::new::thread_start::h23f93afbf81ba466
                               at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/library/std/src/sys/pal/unix/thread.rs:108:17
  38:     0x7fcf37e14609 - start_thread
                               at /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477:8
  39:     0x7fcf37d39353 - clone
                               at /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  40:                0x0 - <unknown>


rustc version: 1.79.0-nightly (eb45c8444 2024-03-17)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at repro.rs:7:1: 7:9>::ack::{closure#0}`
#1 [mir_borrowck] borrow-checking `<impl at repro.rs:7:1: 7:9>::ack`
#2 [analysis] running analysis passes on this crate
end of query stack
```

### LINKED ISSUE #139004: Rustc panics at free_region_relations.rs:93:9:  "can't find an upper bound!?"
The compiler panics for the following code. 

I've tried to minimize it, but this is how far I could get:

```rust
use std::{any::Any, future::Future, marker::PhantomData, pin::Pin};

pub trait Event: Send + Sync {
    type Domain: 'static;
}

pub trait EventHandler<E>: Send + Sync + 'static
where
    E: Event + Send + Sync,
{
    fn handle(self, event: &E) -> impl Future<Output = ()> + Send + '_;
}

pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;
type BoxedHandler = Box<dyn for<'a> Fn(&'a (dyn Any + Send + Sync + 'a)) -> BoxFuture<'a, ()> + Send + Sync>;

pub struct EventBus<D> {
    event_handlers: BoxedHandler,
    domain: PhantomData<D>,
}

impl<D> EventBus<D> {
    pub async fn subscribe<E, H>(&self, handler: H)
    where
        E: Event<Domain = D>,
        H: EventHandler<E> + Clone,
    {
        let _handler: BoxedHandler = Box::new(move |e| {
            let handler = handler.clone();
            Box::pin(async move {
                let e = e.downcast_ref::<E>().expect("downcast failed for event");
                handler.handle(e).await
            })
        });

        todo!()
    }
}

```

The rustc panicked with 

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/type_check/free_region_relations.rs:93:9:
can't find an upper bound!?
stack backtrace:
   0:     0x7bb66a6dfb8a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfc616348d9ad0abc
   1:     0x7bb66ae14d26 - core::fmt::write::h7ca648217bc79799
   2:     0x7bb66bd18711 - std::io::Write::write_fmt::h7960c58bfa5ccbcb
   3:     0x7bb66a6df9e2 - std::sys::backtrace::BacktraceLock::print::h3fb349e80cbe0423
   4:     0x7bb66a6e1f87 - std::panicking::default_hook::{{closure}}::h3366e5842cba645d
   5:     0x7bb66a6e1d70 - std::panicking::default_hook::hd7573a5d4879884b
   6:     0x7bb669851c48 - std[26cf95b4f122e720]::panicking::update_hook::<alloc[653926f6abfe8a8a]::boxed::Box<rustc_driver_impl[bcf7efa42268b866]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7bb66a6e2813 - std::panicking::rust_panic_with_hook::h66e909d048c263a9
   8:     0x7bb66a6e24d6 - std::panicking::begin_panic_handler::{{closure}}::h8d9aa8be7e8634cf
   9:     0x7bb66a6e0069 - std::sys::backtrace::__rust_end_short_backtrace::h7d7e47ef99abf6aa
  10:     0x7bb66a6e21cd - rust_begin_unwind
  11:     0x7bb6673a0ef0 - core::panicking::panic_fmt::hf8ffc7c15bfb58a0
  12:     0x7bb66961e200 - <rustc_borrowck[2064f1529492eb9c]::type_check::free_region_relations::UniversalRegionRelations>::non_local_upper_bounds
  13:     0x7bb66aec9596 - rustc_borrowck[2064f1529492eb9c]::nll::compute_regions
  14:     0x7bb66beab12e - rustc_borrowck[2064f1529492eb9c]::do_mir_borrowck
  15:     0x7bb66be9e2f9 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7bb66b10b817 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  17:     0x7bb66b10b315 - rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7bb66b88098a - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_get_at::<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>>
  19:     0x7bb66b8809ea - <rustc_borrowck[2064f1529492eb9c]::type_check::TypeChecker>::prove_closure_bounds
  20:     0x7bb66b163068 - <rustc_borrowck[2064f1529492eb9c]::type_check::TypeChecker>::typeck_mir
  21:     0x7bb66be8c748 - rustc_borrowck[2064f1529492eb9c]::type_check::type_check
  22:     0x7bb66aec3787 - rustc_borrowck[2064f1529492eb9c]::nll::compute_regions
  23:     0x7bb66beab12e - rustc_borrowck[2064f1529492eb9c]::do_mir_borrowck
  24:     0x7bb66be9e2f9 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7bb66b10b817 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  26:     0x7bb66b10b315 - rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7bb66b88098a - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_get_at::<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>>
  28:     0x7bb66b8809ea - <rustc_borrowck[2064f1529492eb9c]::type_check::TypeChecker>::prove_closure_bounds
  29:     0x7bb66b163068 - <rustc_borrowck[2064f1529492eb9c]::type_check::TypeChecker>::typeck_mir
  30:     0x7bb66be8c748 - rustc_borrowck[2064f1529492eb9c]::type_check::type_check
  31:     0x7bb66aec3787 - rustc_borrowck[2064f1529492eb9c]::nll::compute_regions
  32:     0x7bb66beab12e - rustc_borrowck[2064f1529492eb9c]::do_mir_borrowck
  33:     0x7bb66be9e2f9 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7bb66b10b817 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  35:     0x7bb66b10b315 - rustc_query_impl[291ba1fcadd92b61]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7bb66b6b588c - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_get_at::<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>>
  37:     0x7bb66bd3b2de - rustc_hir_analysis[2b9e33d6773a99db]::collect::type_of::type_of_opaque
  38:     0x7bb66bd3b151 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  39:     0x7bb66aefe3d1 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_query_system[397df17712590249]::query::caches::DefIdCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  40:     0x7bb66bff37f5 - rustc_query_impl[291ba1fcadd92b61]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7bb66b57482c - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_get_at::<rustc_query_system[397df17712590249]::query::caches::DefIdCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>>
  42:     0x7bb66af0579b - rustc_hir_analysis[2b9e33d6773a99db]::collect::type_of::type_of
  43:     0x7bb66aeff5fa - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>
  44:     0x7bb66aefe3d1 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_query_system[397df17712590249]::query::caches::DefIdCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  45:     0x7bb66aefdf6b - rustc_query_impl[291ba1fcadd92b61]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7bb66b57482c - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_get_at::<rustc_query_system[397df17712590249]::query::caches::DefIdCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 8usize]>>>
  47:     0x7bb66b58fb67 - rustc_hir_analysis[2b9e33d6773a99db]::check::check::check_item_type
  48:     0x7bb6685a4377 - rustc_hir_analysis[2b9e33d6773a99db]::check::wfcheck::check_well_formed
  49:     0x7bb66b7ef407 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 1usize]>>
  50:     0x7bb66b7eeea7 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  51:     0x7bb66b7ee90b - rustc_query_impl[291ba1fcadd92b61]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7bb66b7ef475 - rustc_middle[9ee9ea6fc8845c53]::query::plumbing::query_ensure_error_guaranteed::<rustc_data_structures[f86a4f0d0152e187]::vec_cache::VecCache<rustc_span[59b99cb1407325ff]::def_id::LocalDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[397df17712590249]::dep_graph::graph::DepNodeIndex>, ()>
  53:     0x7bb66b7ef965 - rustc_hir_analysis[2b9e33d6773a99db]::check::wfcheck::check_mod_type_wf
  54:     0x7bb66b7ef495 - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 1usize]>>
  55:     0x7bb66bd66404 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_query_system[397df17712590249]::query::caches::DefaultCache<rustc_span[59b99cb1407325ff]::def_id::LocalModDefId, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  56:     0x7bb66bd661a0 - rustc_query_impl[291ba1fcadd92b61]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  57:     0x7bb66b108374 - rustc_hir_analysis[2b9e33d6773a99db]::check_crate
  58:     0x7bb66b1f8ce8 - rustc_interface[ad5173bb1fff4f1]::passes::run_required_analyses
  59:     0x7bb66bd1c59e - rustc_interface[ad5173bb1fff4f1]::passes::analysis
  60:     0x7bb66bd1c56f - rustc_query_impl[291ba1fcadd92b61]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[291ba1fcadd92b61]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>>
  61:     0x7bb66bdc0415 - rustc_query_system[397df17712590249]::query::plumbing::try_execute_query::<rustc_query_impl[291ba1fcadd92b61]::DynamicConfig<rustc_query_system[397df17712590249]::query::caches::SingleCache<rustc_middle[9ee9ea6fc8845c53]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[291ba1fcadd92b61]::plumbing::QueryCtxt, false>
  62:     0x7bb66bdc014e - rustc_query_impl[291ba1fcadd92b61]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  63:     0x7bb66bd5ad9e - rustc_interface[ad5173bb1fff4f1]::passes::create_and_enter_global_ctxt::<core[1d264cc251a564c0]::option::Option<rustc_interface[ad5173bb1fff4f1]::queries::Linker>, rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  64:     0x7bb66bd99516 - rustc_interface[ad5173bb1fff4f1]::interface::run_compiler::<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}
  65:     0x7bb66bc83511 - std[26cf95b4f122e720]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_with_globals<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_pool_with_globals<rustc_interface[ad5173bb1fff4f1]::interface::run_compiler<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  66:     0x7bb66bc839c8 - <<std[26cf95b4f122e720]::thread::Builder>::spawn_unchecked_<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_with_globals<rustc_interface[ad5173bb1fff4f1]::util::run_in_thread_pool_with_globals<rustc_interface[ad5173bb1fff4f1]::interface::run_compiler<(), rustc_driver_impl[bcf7efa42268b866]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[1d264cc251a564c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  67:     0x7bb66bc84f81 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1bbaaa2227026bb
  68:     0x7bb66d3cda94 - <unknown>
  69:     0x7bb66d45aa34 - clone
  70:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.85.1 (4eb161250 2025-03-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `<impl at src/lib.rs:22:1: 22:20>::subscribe::{closure#0}::{closure#0}`
#1 [mir_borrowck] borrow-checking `<impl at src/lib.rs:22:1: 22:20>::subscribe::{closure#0}`
end of query stack
note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: {OpaqueTypeKey { def_id: DefId(0:28 ~ playground[6412]::{impl#0}::subscribe::{opaque#0}), args: [D/#0, E/#1, H/#2, '?4] }: OpaqueTypeDecl { hidden_type: OpaqueHiddenType { span: src/lib.rs:27:5: 37:6 (#0), ty: Coroutine(DefId(0:29 ~ playground[6412]::{impl#0}::subscribe::{closure#0}), [D/#0, E/#1, H/#2, (), std::future::ResumeTy, (), (), CoroutineWitness(DefId(0:29 ~ playground[6412]::{impl#0}::subscribe::{closure#0}), [D/#0, E/#1, H/#2]), (&'?3 EventBus<D/#0>, H/#2)]) } }}
  |
  = note: delayed at compiler/rustc_infer/src/infer/opaque_types/table.rs:44:43 - disabled backtrace

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.85.1 (4eb161250 2025-03-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

### Meta

The code is available in rust playground:
[link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=2552cf9698bfed2fbddf241a522e3441)
and the error is present for both **stable**, **beta**, **nightly** and both in **debug** and **release** builds:

Version Info:
Image

### PR DESCRIPTION
**Pull request by matthewjasper**
`non_local_bounds` would only find non local bounds that strictly bound a given region, but it's possible that a local region is equated to 'static when showing a type referencing a locally bound lifetime, such as `dyn Any + 'a` in the tests added, is well-formed. In this case we should return 'static.

closes #122704
closes #139004

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? types

File: compiler/rustc_data_structures/src/transitive_relation.rs [hunk 1]
```diff
@@ -354,6 +354,20 @@ impl<T: Eq + Hash + Copy> TransitiveRelation<T> {
...
 
+    /// Given an element A, elements B with the lowest index such that `A R B`
+    /// and `B R A`, or `A` if no such element exists.
+    pub fn scc_representative(&self, a: T) -> T {
+        match self.index(a) {
+            Some(a_i) => self.with_closure(|closure| {
+                closure
+                    .iter(a_i.0)
+                    .find(|i| closure.contains(*i, a_i.0))
+                    .map_or(a, |i| self.elements[i])
```
Comment (compiler-errors) [inline compiler/rustc_data_structures/src/transitive_relation.rs:365]: Why would we not find such an element? In other words, what's the justification for the `map_or`, over an ` unwrap`? Shouldn't all free regions be represented in `TransitiveRelations`?

File: compiler/rustc_borrowck/src/type_check/free_region_relations.rs [hunk 2]
```diff
@@ -133,7 +133,8 @@ impl UniversalRegionRelations<'_> {
         assert!(self.universal_regions.is_universal_region(fr0));
 
         let mut external_parents = vec![];
-        let mut queue = vec![fr0];
+
+        let mut queue = vec![relation.scc_representative(fr0)];
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/type_check/free_region_relations.rs:137]: I'm not sure if you've explained why projecting the free region to its representative affects the set of `non_local_bounds` that we return. It's not obvious from the definition of `TransitiveRelation::parents`, at least.

Like, if these are actually SCC's then I'm not sure why shuffling around which element in that SCC fixes things.

Is there something subtle going on with the fact that `'static` is the first first region vid we allocate?

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/free_region_relations.rs:137]: If it has to do with the fact that `TransitiveRelation::parents` requires for us to pass the *minimal* element for this while loop to actually reach all of the parents, then perhaps we should rename thatfunction to `minimal_scc_representative` 🤔

 Or maybe I'm totally misleading myself.

File: compiler/rustc_data_structures/src/transitive_relation.rs (hunk 1 above)
Comment (matthewjasper) [reply compiler/rustc_data_structures/src/transitive_relation.rs:365]: Borrowck will always have this as a reflexive relation, but the data structure doesn't require that (maybe it should though).

File: compiler/rustc_borrowck/src/type_check/free_region_relations.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/free_region_relations.rs]: Hey @matthewjasper, did you mean to resolve this without actually answering the question?

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/free_region_relations.rs]: Ah ok thanks
