### PR TITLE
Only deduplicate stack traces for good path bugs

### LINKED ISSUE #106267: backtrace missing when rustc panics
With beta `rustc 1.67.0-beta.5 (6b1892c28 2022-12-28)`
````
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:15 ~ 92157[3065]::{impl#0}::add) (NoSolution): could not prove Binder(TraitPredicate(<isize as Copy>, polarity:Positive), [])
  |
  = note: delayed at compiler/rustc_borrowck/src/type_check/canonical.rs:148:13

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1610:13
stack backtrace:
   0:     0x7f46583656fa - std::backtrace_rs::backtrace::libunwind::trace::hb14b523cf9bbb6ff
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f46583656fa - std::backtrace_rs::backtrace::trace_unsynchronized::h18e2e2737acb9234
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f46583656fa - std::sys_common::backtrace::_print_fmt::h47704e7b65218342
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f46583656fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e1ba434ff93bdae
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f46583c825e - core::fmt::write::hd7ac771d9ffd9737
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f4658355a85 - std::io::Write::write_fmt::h4840fb0f8374ef5b
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/io/mod.rs:1682:15
   6:     0x7f46583654c5 - std::sys_common::backtrace::_print::hfa7d8e7a1dbf6697
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f46583654c5 - std::sys_common::backtrace::print::h3986e26150deb380
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f465836820f - std::panicking::default_hook::{{closure}}::h98cd5bb66bfc395c
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/panicking.rs:267:22
   9:     0x7f4658367f4b - std::panicking::default_hook::h1f9832d2e5df2901
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/panicking.rs:286:9
  10:     0x7f465b6620d1 - <rustc_driver[a1bd42a8b9f3139f]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[f31338071577118d]::ops::function::FnOnce<(&core[f31338071577118d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4658368a4d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2180065ed0df45f4
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/alloc/src/boxed.rs:2032:9
  12:     0x7f4658368a4d - std::panicking::rust_panic_with_hook::h875dca59c539b796
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/panicking.rs:692:13
  13:     0x7f465b69adc1 - std[faafec5917ce8dac]::panicking::begin_panic::<rustc_errors[b60a95b52c4fe12f]::ExplicitBug>::{closure#0}
  14:     0x7f465b699696 - std[faafec5917ce8dac]::sys_common::backtrace::__rust_end_short_backtrace::<std[faafec5917ce8dac]::panicking::begin_panic<rustc_errors[b60a95b52c4fe12f]::ExplicitBug>::{closure#0}, !>
  15:     0x7f465b678906 - std[faafec5917ce8dac]::panicking::begin_panic::<rustc_errors[b60a95b52c4fe12f]::ExplicitBug>
  16:     0x7f465b697106 - std[faafec5917ce8dac]::panic::panic_any::<rustc_errors[b60a95b52c4fe12f]::ExplicitBug>
  17:     0x7f465ab46ed6 - <rustc_errors[b60a95b52c4fe12f]::HandlerInner>::flush_delayed::<alloc[533e65513bbad258]::vec::Vec<rustc_errors[b60a95b52c4fe12f]::diagnostic::Diagnostic>, &str>
  18:     0x7f465a81ef4c - <rustc_interface[e29be70a03a9eb51]::passes::QueryContext>::enter::<<rustc_interface[e29be70a03a9eb51]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[f31338071577118d]::result::Result<alloc[533e65513bbad258]::boxed::Box<dyn core[f31338071577118d]::any::Any>, rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>
  19:     0x7f465a81c5b6 - <rustc_interface[e29be70a03a9eb51]::queries::Queries>::ongoing_codegen
  20:     0x7f465a81bad7 - <rustc_interface[e29be70a03a9eb51]::interface::Compiler>::enter::<rustc_driver[a1bd42a8b9f3139f]::run_compiler::{closure#1}::{closure#2}, core[f31338071577118d]::result::Result<core[f31338071577118d]::option::Option<rustc_interface[e29be70a03a9eb51]::queries::Linker>, rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>
  21:     0x7f465a816af8 - rustc_span[5e59950fc4a1d87a]::with_source_map::<core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>, rustc_interface[e29be70a03a9eb51]::interface::run_compiler<core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>, rustc_driver[a1bd42a8b9f3139f]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  22:     0x7f465a8165e5 - <scoped_tls[fa92078d52959d9e]::ScopedKey<rustc_span[5e59950fc4a1d87a]::SessionGlobals>>::set::<rustc_interface[e29be70a03a9eb51]::interface::run_compiler<core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>, rustc_driver[a1bd42a8b9f3139f]::run_compiler::{closure#1}>::{closure#0}, core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>
  23:     0x7f465a815bd2 - std[faafec5917ce8dac]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e29be70a03a9eb51]::util::run_in_thread_pool_with_globals<rustc_interface[e29be70a03a9eb51]::interface::run_compiler<core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>, rustc_driver[a1bd42a8b9f3139f]::run_compiler::{closure#1}>::{closure#0}, core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>
  24:     0x7f465af19a6a - <<std[faafec5917ce8dac]::thread::Builder>::spawn_unchecked_<rustc_interface[e29be70a03a9eb51]::util::run_in_thread_pool_with_globals<rustc_interface[e29be70a03a9eb51]::interface::run_compiler<core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>, rustc_driver[a1bd42a8b9f3139f]::run_compiler::{closure#1}>::{closure#0}, core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f31338071577118d]::result::Result<(), rustc_errors[b60a95b52c4fe12f]::ErrorGuaranteed>>::{closure#1} as core[f31338071577118d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f4658372803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7e8fc432d04b89f2
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/alloc/src/boxed.rs:2000:9
  26:     0x7f4658372803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h199ef35eac4a1602
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/alloc/src/boxed.rs:2000:9
  27:     0x7f4658372803 - std::sys::unix::thread::Thread::new::thread_start::h9e95ba06661490e6
                               at /rustc/6b1892c2803adade20a9399a176c0140ec347a96/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f46581058fd - <unknown>
  29:     0x7f4658187a60 - <unknown>
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-beta.5 (6b1892c28 2022-12-28) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors
````

but nightly does not show backtraces: `rustc 1.68.0-nightly (270c94e48 2022-12-28)`

````
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:15 ~ 92157[71a4]::{impl#0}::add) (NoSolution): could not prove Binder(TraitPredicate(<isize as Copy>, polarity:Positive), [])
  |
  = note: delayed at compiler/rustc_borrowck/src/type_check/canonical.rs:148:13

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (270c94e48 2022-12-28) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 2 previous errors
````

edits
this is with
````
rustc 1.68.0-nightly (270c94e48 2022-12-28)
binary: rustc
commit-hash: 270c94e484e19764a2832ef918c95224eb3f17c7
commit-date: 2022-12-28
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
````

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #106267

Restores backtraces for `bug!` and `delay_span_bug` after #106056. Only `delay_good_path_bug` needed its backtraces to be deduplicated, since it spits out the backtrace where it was created when it's being emitted.

Before:

```
error: internal compiler error: /home/ubuntu/rust2/compiler/rustc_middle/src/ty/relate.rs:638:13: var types encountered in super_relate_consts: Const { ty: usize, kind: Infer(Var(_#0c)) } Const { ty: usize, kind: Param(N/#1) }

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at /home/ubuntu/test.rs:7:1: 7:34>::trigger`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors
```

Hmm... that's a little bare.

After:

```
error: internal compiler error: /home/ubuntu/rust2/compiler/rustc_middle/src/ty/relate.rs:638:13: var types encountered in super_relate_consts: Const { ty: usize, kind: Infer(Var(_#0c)) } Const { ty: usize, kind: Param(N/#1) }

thread 'rustc' panicked at 'Box<dyn Any>', /home/ubuntu/rust2/compiler/rustc_errors/src/lib.rs:1599:9
stack backtrace:
   0:     0x7ffb5b41bdd1 - std::backtrace_rs::backtrace::libunwind::trace::h26056f81198c6594
                               at /home/ubuntu/rust2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ffb5b41bdd1 - std::backtrace_rs::backtrace::trace_unsynchronized::hacfb345a0c6d5bb1
                               at /home/ubuntu/rust2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffb5b41bdd1 - std::sys_common::backtrace::_print_fmt::h18ea6016ac8030f3
                               at /home/ubuntu/rust2/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ffb5b41bdd1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he35dde201d0c2d09
                               at /home/ubuntu/rust2/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ffb5b4a0308 - core::fmt::write::h094ad263467a053c
                               at /home/ubuntu/rust2/library/core/src/fmt/mod.rs:1208:17
   5:     0x7ffb5b43caf1 - std::io::Write::write_fmt::hd47b4e2324b4d9b7
                               at /home/ubuntu/rust2/library/std/src/io/mod.rs:1682:15
   6:     0x7ffb5b41bbfa - std::sys_common::backtrace::_print::h43044162653a17fc
                               at /home/ubuntu/rust2/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7ffb5b41bbfa - std::sys_common::backtrace::print::hc8605da258fa5aeb
                               at /home/ubuntu/rust2/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7ffb5b3ffb87 - std::panicking::default_hook::{{closure}}::h9e37f23f75122a15
   9:     0x7ffb5b3ff97b - std::panicking::default_hook::h602873a063f84da2
                               at /home/ubuntu/rust2/library/std/src/panicking.rs:286:9
  10:     0x7ffb5be192b2 - <alloc[48d7b30605060536]::boxed::Box<dyn for<'a, 'b> core[672e3947e150d6c6]::ops::function::Fn<(&'a core[672e3947e150d6c6]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[672e3947e150d6c6]::marker::Send + core[672e3947e150d6c6]::marker::Sync> as core[672e3947e150d6c6]::ops::function::Fn<(&core[672e3947e150d6c6]::panic::panic_info::PanicInfo,)>>::call
                               at /home/ubuntu/rust2/library/alloc/src/boxed.rs:2002:9
  11:     0x7ffb5be192b2 - rustc_driver[f5b6d32d8905ecdd]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/ubuntu/rust2/compiler/rustc_driver/src/lib.rs:1204:17
  12:     0x7ffb5b4000d3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfd13333ca953ae8e
                               at /home/ubuntu/rust2/library/alloc/src/boxed.rs:2002:9
  13:     0x7ffb5b4000d3 - std::panicking::rust_panic_with_hook::h45753e10264ebe7e
                               at /home/ubuntu/rust2/library/std/src/panicking.rs:692:13
  14:     0x7ffb5e8b3a63 - std[3330b4673efabfce]::panicking::begin_panic::<rustc_errors[1b15f4e7e49d1fd5]::ExplicitBug>::{closure#0}

[... FRAMES INTENTIONALLY OMITTED BECAUSE GITHUB GOT ANGRY ...]

 186:     0x7ffb5bea5554 - <std[3330b4673efabfce]::thread::Builder>::spawn_unchecked_::<rustc_interface[947706ead88047d0]::util::run_in_thread_pool_with_globals<rustc_interface[947706ead88047d0]::interface::run_compiler<core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>, rustc_driver[f5b6d32d8905ecdd]::run_compiler::{closure#1}>::{closure#0}, core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>>::{closure#1}
                               at /home/ubuntu/rust2/library/std/src/thread/mod.rs:549:30
 187:     0x7ffb5bea5554 - <<std[3330b4673efabfce]::thread::Builder>::spawn_unchecked_<rustc_interface[947706ead88047d0]::util::run_in_thread_pool_with_globals<rustc_interface[947706ead88047d0]::interface::run_compiler<core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>, rustc_driver[f5b6d32d8905ecdd]::run_compiler::{closure#1}>::{closure#0}, core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[672e3947e150d6c6]::result::Result<(), rustc_errors[1b15f4e7e49d1fd5]::ErrorGuaranteed>>::{closure#1} as core[672e3947e150d6c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/ubuntu/rust2/library/core/src/ops/function.rs:250:5
 188:     0x7ffb5b433968 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he8b26fc22c6f51ec
                               at /home/ubuntu/rust2/library/alloc/src/boxed.rs:1988:9
 189:     0x7ffb5b433968 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5cf9cbe75a8c3ddc
                               at /home/ubuntu/rust2/library/alloc/src/boxed.rs:1988:9
 190:     0x7ffb5b41199c - std::sys::unix::thread::Thread::new::thread_start::h2d6dd4455e97d031
                               at /home/ubuntu/rust2/library/std/src/sys/unix/thread.rs:108:17
 191:     0x7ffb5441b609 - start_thread
 192:     0x7ffb5b282133 - clone
 193:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at /home/ubuntu/test.rs:7:1: 7:34>::trigger`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.
```

### CODE REVIEW

File: compiler/rustc_errors/src/lib.rs [hunk 1]
```diff
@@ -366,12 +367,25 @@ pub struct ExplicitBug;
...
+/// Signifies that the compiler died with an explicit call to `.delay_good_path_bug`
+/// rather than a failed assertion, etc.
+#[derive(Copy, Clone, Debug)]
+pub struct GoodPathBug;
+
+impl fmt::Display for GoodPathBug {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(f, "good path bug")
+    }
+}
```
Comment (jyn514) [inline compiler/rustc_errors/src/lib.rs:385]: is this impl (or the `Error` impl) ever used?

**Review by jyn514 — COMMENTED** [review]
r=me with or without the `Display` impl removed. good catch, thanks!

File: compiler/rustc_errors/src/lib.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_errors/src/lib.rs:385]: It's conventional for types implementing the `Error` trait:

> Errors must describe themselves through the [Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) and [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) traits. Error messages are typically concise lowercase sentences without trailing punctuation [...]

Comment (jyn514) [reply compiler/rustc_errors/src/lib.rs:385]: Right, but I'm asking whether this needs to implement `Error` in the first place. I don't see that bound ever used.

Comment (compiler-errors) [reply compiler/rustc_errors/src/lib.rs:385]: Oh, didn't see the parenthetical. Uh, I'll see.

**Comment by compiler-errors** [comment]
CI failures are fixed in #106320 I think.

@bors r=jyn514
