### PR TITLE
Give correct suggestion for a typo in raw pointers

### LINKED ISSUE #136602: `const*` causing multiple unrelated errors and a suggestion that won't compile
### Code

```Rust
const C: [u8; 1] = [0];
pub const P: const* u8 = &C as _;
```

### Current output

```Shell
Compiling tmp v0.1.0 (/home/rudxain/tmp)
error: expected `mut` or `const` keyword in raw pointer type
 --> src/lib.rs:2:19
  |
2 | pub const P: const* u8 = &C as _;
  |                   ^
  |
help: add `mut` or `const` here
  |
2 | pub const P: const*mut  u8 = &C as _;
  |                    +++
2 | pub const P: const*const  u8 = &C as _;
  |                    +++++

error: expected a trait, found type
 --> src/lib.rs:2:19
  |
2 | pub const P: const* u8 = &C as _;
  |                   ^^^^
  |
help: consider removing the indirection
  |
2 - pub const P: const* u8 = &C as _;
2 + pub const P: constu8 = &C as _;
  |

error: const trait bounds are not allowed in trait object types
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^^^^^

error[E0404]: expected trait, found builtin type `u8`
 --> src/lib.rs:2:21
  |
2 | pub const P: const* u8 = &C as _;
  |                     ^^ not a trait

error[E0658]: const trait impls are experimental
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^
  |
  = note: see issue #67792 <https://github.com/rust-lang/rust/issues/67792> for more information

error[E0782]: expected a type, found a trait
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^^^^^
  |
help: you can add the `dyn` keyword if you want a trait object
  |
2 | pub const P: dyn const* u8 = &C as _;
  |              +++
```

### Desired output

```Shell
Compiling tmp v0.1.0 (/home/rudxain/tmp)
error: raw pointer type must have a star before the mutability keyword
 --> src/lib.rs:2:19
  |
2 | pub const P: const* u8 = &C as _;
  |                   ^
  |
help: move it to the other side
  |
2 | pub const P: const* u8 = &C as _;
  |                   -
2 | pub const P: *const u8 = &C as _;
  |              +

error: expected `mut` or `const` keyword in raw pointer type
 --> src/lib.rs:2:19
  |
2 | pub const P: const* u8 = &C as _;
  |                   ^
  |
help: add `mut` or `const` here
  |
2 | pub const P: const*mut  u8 = &C as _;
  |                    +++
2 | pub const P: const*const  u8 = &C as _;
  |                    +++++

error: const trait bounds are not allowed in trait object types
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^^^^^

error[E0404]: expected trait, found builtin type `u8`
 --> src/lib.rs:2:21
  |
2 | pub const P: const* u8 = &C as _;
  |                     ^^ not a trait

error[E0658]: const trait impls are experimental
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^
  |
  = note: see issue #67792 <https://github.com/rust-lang/rust/issues/67792> for more information

error[E0782]: expected a type, found a trait
 --> src/lib.rs:2:14
  |
2 | pub const P: const* u8 = &C as _;
  |              ^^^^^^^^^
  |
help: you can add the `dyn` keyword if you want a trait object
  |
2 | pub const P: dyn const* u8 = &C as _;
  |              +++
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.84.1 (e71f9a9a9 2025-01-27)
binary: rustc
commit-hash: e71f9a9a98b0faf423844bf0ba7438f29dc27d58
commit-date: 2025-01-27
host: x86_64-unknown-linux-gnu
release: 1.84.1
LLVM version: 19.1.5
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kivooeo**
This adds a check for when user wrote `const* T` instead of `*const T`, I just saw how a C-person made this typo and compiler suggests this

```rust
 --> src/main.rs:2:17
  |
2 |     let p: const* u8 = 0 as _;
  |                 ^
  |
help: add `mut` or `const` here
  |
2 |     let p: const*mut  u8 = 0 as _;
  |                  +++
2 |     let p: const*const  u8 = 0 as _;
  |                  +++++
```

which is very incorrect

also fixes https://github.com/rust-lang/rust/issues/136602

r? compiler

### CODE REVIEW

File: compiler/rustc_parse/src/parser/ty.rs [hunk 1]
```diff
@@ -276,6 +276,34 @@ impl<'a> Parser<'a> {
...
+                    .with_multipart_suggestion(
+                        "move it to the other side",
+                        vec![(star_span, String::new()), (kw_span.shrink_to_lo(), "*".to_string())],
+                        Applicability::MachineApplicable,
+                    )
+                    .emit();
+
+                return Ok(self.mk_ty(kw_span.to(star_span), TyKind::Err(guar)));
+            }
+        }
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]:
```suggestion
        }
        
```

File: compiler/rustc_parse/src/parser/ty.rs [hunk 2]
```diff
@@ -276,6 +276,34 @@ impl<'a> Parser<'a> {
...
+                        "raw pointer type must have a star before the mutability keyword",
+                    )
+                    .with_multipart_suggestion(
+                        "move it to the other side",
+                        vec![(star_span, String::new()), (kw_span.shrink_to_lo(), "*".to_string())],
+                        Applicability::MachineApplicable,
+                    )
+                    .emit();
+
+                return Ok(self.mk_ty(kw_span.to(star_span), TyKind::Err(guar)));
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: Why not recover this like a `TyKind::RawPtr`? Recovering like `TyKind::Err` seems to be strictly worse.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -276,6 +276,34 @@ impl<'a> Parser<'a> {
...
         let allow_qpath_recovery = recover_qpath == RecoverQPath::Yes;
         maybe_recover_from_interpolated_ty_qpath!(self, allow_qpath_recovery);
+
+        if (self.token.is_keyword(kw::Const) || self.token.is_keyword(kw::Mut))
+            && self.look_ahead(1, |t| *t == token::Star)
+        {
+            let kw_span = self.token.span;
+            self.bump();
+
+            if self.eat(exp!(Star)) {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: This should try to parse a subsequent type via a snapshot. Or at least check that `lookahead(2)` [can begin a type](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/token/struct.Token.html#method.can_begin_type)

Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: This eat is always true, since we checked the lookahead above

File: compiler/rustc_parse/src/parser/ty.rs [hunk 4]
```diff
@@ -276,6 +276,34 @@ impl<'a> Parser<'a> {
...
+                let star_span = self.prev_token.span;
+
+                let _ = self.parse_ty_no_question_mark_recover();
+
+                let guar = self
+                    .dcx()
+                    .struct_span_err(
+                        kw_span,
+                        "raw pointer type must have a star before the mutability keyword",
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]:
```suggestion
                        "raw pointer types are written like `*{...} T`",
```

I find the phrasing kind of awkward -- "must have a star before the mutability keyword" doesn't really point to the fact that there *is* a star, and it's just misplaced. And also I wouldn't call "`const`" to be a mutability keyword.

I'm not sure if what I suggested is any better, but I wonder if there's a way to suggest the change here that sounds more descriptive.

File: compiler/rustc_parse/src/parser/ty.rs [hunk 5]
```diff
@@ -276,6 +276,34 @@ impl<'a> Parser<'a> {
     ) -> PResult<'a, Box<Ty>> {
         let allow_qpath_recovery = recover_qpath == RecoverQPath::Yes;
         maybe_recover_from_interpolated_ty_qpath!(self, allow_qpath_recovery);
+
+        if (self.token.is_keyword(kw::Const) || self.token.is_keyword(kw::Mut))
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]:
```suggestion
        // Comment that describes what we're trying to do here.
        if (self.token.is_keyword(kw::Const) || self.token.is_keyword(kw::Mut))
```

Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/ty.rs]: This probably should also be moved into a separate function and also moved way down into the actually `if else` chain below rather than being hit first on every call to `parse_ty_common`

**Review by compiler-errors — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/ty.rs (hunk 5 above)
Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/ty.rs]: This was made exactly like attribute parsing in types right below, this why I originally chose this place and this strategy 

About snapshoting I'm not fully sure I can and should use it here, not only because I fully know how and why it should be used, I checked other places where snapshotting was used and it mostly like in `Err` branch of `match` which I don't use

About `eat`ing `Star` it looks correct for me here even if we know that here is `Star` 100% beacuse we checked it in `if`, but if there any other way more better way to do I'm in full ears, but honestly I dont personally like this `if` branch here because of `unreachable!`, so yeah, should be a better way to do it, 

I also adressed a wording problem, new one should be more straighforward and clear for end user

And I made a recovery as a `TyKind::Ptr`, agree that this is better generally

Also about `lookahead(2)` or `can_begin_type` I'm not quite sure why we need it, I'm parsing type in `if` with `parse_ty_no_question_mark_recover` to create a `TyKind::Ptr` from it, and if there will be no type at all it should fail earlier with a different error

**Comment by Kivooeo** [comment]
r? compiler

File: compiler/rustc_parse/src/parser/ty.rs [hunk 6]
```diff
@@ -320,6 +311,10 @@ impl<'a> Parser<'a> {
         } else if self.eat(exp!(Bang)) {
             // Never type `!`
             TyKind::Never
+        } else if (self.token.is_keyword(kw::Const) || self.token.is_keyword(kw::Mut))
+            && self.look_ahead(1, |t| *t == token::Star)
+        {
+            self.parse_ty_c_style_pointer()?
```
Comment (davidtwco) [inline compiler/rustc_parse/src/parser/ty.rs]: Is it possible to move this lower in the conditions or test for this after parsing has failed rather than prior to when parsing every type?

Comment (Kivooeo) [reply compiler/rustc_parse/src/parser/ty.rs]: Yes, sure, I overlooked this from last review

**Review by davidtwco — APPROVED** [review]
