### PR TITLE
While let suggestion will work for closure body

### LINKED ISSUE #113354: `while let` suggestion missing when E0308 happens in closure body
### Code

```Rust
fn main() {
    let _ = || { while Some(_) = None { } };
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:2:24
  |
2 |     let _ = || { while Some(_) = None { } };
  |                        ^^^^^^^^^^^^^^ expected `bool`, found `()`

For more information about this error, try `rustc --explain E0308`.
```

### Desired output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:2:24
  |
2 |     let _ = || { while Some(_) = None { } };
  |                        ^^^^^^^^^^^^^^ expected `bool`, found `()`
help: consider adding `let`
  |
2 |     let _ = || { while let Some(_) = None { } };
  |                        +++

For more information about this error, try `rustc --explain E0308`.
```

### Rationale and extra context

When an assignment is used as the test in a `while` statement, the compiler will add a `help` message suggesting `while let` instead.  This message fails to appear when the erroneous `while` statement is inside a closure body.

### Other cases

_No response_

### Anything else?

This problem was discovered while investigating #113352 .

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #113354

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/suggest.rs [hunk 1]
```diff
@@ -464,52 +464,62 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
-            pub found_if: bool,
-            pub err_span: Span,
-        }
+        if let Some(node) = self.tcx.hir().find_by_def_id(cause.body_id) {
+            match node {
+                hir::Node::Item(hir::Item { kind: hir::ItemKind::Fn(_, _, body_id), .. })
+                | hir::Node::Expr(hir::Expr {
+                    kind: hir::ExprKind::Closure(hir::Closure { body: body_id, .. }),
+                    ..
+                }) => {
```
Comment (cjgillot) [inline compiler/rustc_infer/src/infer/error_reporting/suggest.rs:473]: Does this work?
```suggestion
        if let Some(body_id) = self.tcx.hir().maybe_body_owned_by(cause.body_id) {
```

Comment (chenyukang) [reply compiler/rustc_infer/src/infer/error_reporting/suggest.rs]: Yes, it works, fixed!
