### PR TITLE
Add clippy and fix commands to x.py

### LINKED ISSUE #53896: x.py fix
#53816 (migrating part of the codebase to use `'_` lifetimes in type names) ended up involving quite a lot of manual text-editing labor because, unfortunately, rustfix doesn't work with `x.py`. (You might think that you could run `cargo fix` on an individual crate, but after supplying [missing feature flags](https://github.com/rust-lang/rust/blob/28bcffead74d5e17c6cb1f7de432e37f93a6b50c/src/libsyntax/feature_gate.rs#L2091-L2095) and environment variables (`RUSTC_ERROR_METADATA_DST`, `CFG_COMPILER_HOST_TRIPLE`), you end up triggering [an assertion](https://github.com/rust-lang/rust/blob/28bcffead74d5e17c6cb1f7de432e37f93a6b50c/src/librustc/ty/sty.rs#L711) that I don't know how to hack around.) It would be nice if there was an `x.py fix` that worked (even if the need won't come up very often).

This issue should probably receive the A-rustbuild, C-feature-request, T-infra, and P-low labels.

### PR DESCRIPTION
**Pull request by ljedrz**
Since they are kind of similar in nature, I have used the same approach as for `cargo check`. At least some of the boilerplate could probably be shared, but I'd prefer to gather some feedback before I decide to merge them more aggressively.

This works reasonably well for `clippy`; with `-A clippy::all` and some extra `#![feature(rustc_private)]`s almost the whole codebase can be processed. There are some concerns, though:
- unlike `check`, in order to be able to traverse all the crates, some of them need to be marked with the `#![feature(rustc_private)]` attribute
- `-W clippy::all` breaks on any error. Is there a way to produce errors but not have them break the progress?
- I'm not sure how to redirect the errors in a way that would show colors; for now I was able to de-jsonize and print them (something not needed for `check`)

`cargo fix` is much more stubborn; it refuses to acknowledge crates like `core` and `std`, so it doesn't progress much at all.

Since this is a bit more tricky than I have envisioned, I need some guidance:
- is this the right approach or am I doing something very wrong ^^?
- why are the extra `rustc_private` features necessary? I was hoping for the same treatment as `check`
- are changes in `clippy` and `cargo fix` needed e.g. in order to produce errors in the same manner as `check` or did I miss something?
- do we need this level of file granularity (e.g. for futureproofing) or can `check`, `clippy` and `fix` files be condensed?

Hopes-to-fix: https://github.com/rust-lang/rust/issues/53896

Cc @alexcrichton, @zackmdavis

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm somewhat hesitant to merge this in though because it seems like it's presumably duplicating a lot of code already there for other aspects of rustbuild. Rustbuild already suffers from a good deal of duplication, so I think I'd personally prefer if we could try to explore strategies of deduplication before merging these in

**Comment by ljedrz** [comment]
@alexcrichton there is definitely room for improvement in terms of deduplication, that's one of the reasons for the WIP; I just wanted to make sure the general approach was fine before squeezing the code a bit more.

I'll rebase and deduplicate the code shortly.

**Comment by ljedrz** [comment]
@alexcrichton I updated the commit - the new commands are now integrated into `check.rs`, as they are pretty similar in nature.

File: src/bootstrap/check.rs [hunk 1]
```diff
@@ -23,6 +23,22 @@ pub struct Std {
     pub target: Interned<String>,
 }
 
+fn args(kind: Kind) -> Vec<String> {
+    match kind {
+        Kind::Clippy => vec!["--".to_owned(), "-W".to_owned(), "clippy::all".to_owned()],
```
Comment (sinkuu) [inline src/bootstrap/check.rs]: > -W clippy::all breaks on any error. Is there a way to produce errors but not have them break the progress?

`--cap-lints warn` should work.

**Comment by sinkuu** [comment]
> unlike check, in order to be able to traverse all the crates, some of them need to be marked with the #![feature(rustc_private)] attribute

You can make `Builder::cargo` to add `RUSTFLAGS="-Zforce-unstable-if-unmarked"` instead of `RUSTC_FORCE_UNSTABLE=1` when `cmd == "clippy"`. Bootstrap's rustc shim adds the flag when `RUSTC_FORCE_UNSTABLE` is found, but `cargo clippy` invokes its own rustc driver.

**Comment by ljedrz** [comment]
Thanks for the suggestions @sinkuu! I'll apply them soon.

**Comment by oli-obk** [comment]
We could add an unstable flag that prints terminal color codes to the formatted diagnostic message in the json

**Comment by Dylan-DPC** [comment]
ping from triage @ljedrz you have conflicts to address

**Comment by ljedrz** [comment]
Rebased.

**Comment by Dylan-DPC** [comment]
ping from triage @ljedrz you have conflicts to attend to.

**Comment by Dylan-DPC** [comment]
ping from triage @ljedrz 
Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Comment by ljedrz** [comment]
@Dylan-DPC actually I forgot about this one among the HirIdification efforts ^^.

@oli-obk is there still a plan to include that unstable flag that would allow normal errors to be printed?

**Comment by Dylan-DPC** [comment]
@ljedrz oops.. haven't closed it yet :P do you plan on working on it this week or can i close it and you can reoopen or create a new PR (preferably) when you feel like working on it?

**Comment by oli-obk** [comment]
@ljedrz I'll hack something up

**Comment by ljedrz** [comment]
@Dylan-DPC rebasing this shouldn't be a problem, I can do it shortly.

**Comment by ljedrz** [comment]
Rebased.

**Comment by TimNN** [comment]
Ping from triage @ljedrz, @oli-obk: If I understand correctly, this PR is blocked on another, yet-to-be-written PR, correct?

**Comment by oli-obk** [comment]
It's blocked on https://github.com/rust-lang/rust/pull/59128 getting merged (which is waiting for bors to get to it)

**Comment by mark-i-m** [comment]
Would it make sense to have bors increase the priority of PRs that are blocking other PRs?

**Comment by varkor** [comment]
This is no longer blocked. Is it waiting on a review?

**Comment by oli-obk** [comment]
@ljedrz you can now have the colors in the `rendered` field of json ouptut via `--json-rendered=termcolor`

**Comment by ljedrz** [comment]
Thanks! I'm currently traveling, but I'll get back to this shortly.

**Comment by ljedrz** [comment]
With the addition of the new flag we now have available thanks to @oli-obk, I am now able to run e.g. `./x.py clippy src/librustc_driver` and see nice output.

This option doesn't seem to be available to `fix`, though, so now I'm wondering if it should also be added to it or if I should omit that parameter from that command altogether for now.

**Comment by mark-i-m** [comment]
It sounds like a nice addition, but perhaps in a followup PR?

**Review by oli-obk — APPROVED** [review]

**Comment by ljedrz** [comment]
Done; at this point the `fix` support is limited, but `clippy` seems operational.

**Comment by Centril** [comment]
> I would kind of like to merge this actually. It would be a big step towards moving the compiler to edition 2018.

The entirety of the repo (+ relevant submodules) has been moved to 2018 so this PR is no longer needed for that.

(but it is still nice for other things...)

File: src/bootstrap/builder.rs [hunk 2]
```diff
@@ -968,7 +972,13 @@ impl<'a> Builder<'a> {
                 "RUSTC_DEBUGINFO_LINES",
                 self.config.rust_debuginfo_lines.to_string(),
             );
-            cargo.env("RUSTC_FORCE_UNSTABLE", "1");
+
+            if cmd == "clippy" {
```
Comment (oli-obk) [inline src/bootstrap/builder.rs]: won't this cause everything to be rebuilt if running `./x.py build`, then `./x.py clippy` and again `./x.py build` due to the changing `RUSTFLAGS`?

Comment (ljedrz) [reply src/bootstrap/builder.rs]: Good point, I missed that; I rebased and adjusted the PR to modify `RUSTFLAGS` in a more suitable place (I think).

File: src/bootstrap/builder.rs [hunk 3]
```diff
@@ -898,6 +902,11 @@ impl<'a> Builder<'a> {
             extra_args.push_str(&s);
         }
 
+        if cmd == "clippy" {
+            extra_args.push_str("-Zforce-unstable-if-unmarked -Zunstable-options \
```
Comment (oli-obk) [inline src/bootstrap/builder.rs]: have you tested that this prevents the rebuilds? I would have assumed this to still cause build thrashing. If this works, then I'm happy with it, if not, you should be able to add them in the `args` function you created below by putting them after a `--` argument

Comment (ljedrz) [reply src/bootstrap/builder.rs]: I just checked it - there are no rebuilds. The only thing is that after throwing its warnings (a lot of stuff found in `libcore`) `./x.py clippy` is complaining that it `can't find crate for std` and I no longer remember if this was an acceptable step forward or not ^^. I remember having trouble making it respect the build order.

Comment (oli-obk) [reply src/bootstrap/builder.rs]: While not great, we can solve this in follow-ups. I think this may happen whenever one tries to run clippy on a target without libstd, so it's likely that it's a clippy issue.
