### PR TITLE
Fix ICE: attempted to remap an already remapped filename

### LINKED ISSUE #138520: ICE: `rustdoc`: attempted to remap an already remapped filename
### Code

```sh
echo 'macro_rules! f(() => {});' > x.rs
RUSTC_BOOTSTRAP=1 rustdoc -Zunstable-options --remap-path-prefix=./= ./x.rs
```

It reproduces with `rustdoc`, but not `rustc`.

We hit this building the documentation for the Linux kernel (for our custom `compiler_builtins` crate).

### Meta

```
rustc 1.82.0 (f6e511eec 2024-10-15)
rustc 1.85.0 (4d91de4e4 2025-02-17)
rustc 1.86.0-beta.5 (b2af9a598 2025-03-08)
rustc 1.87.0-nightly (cbfdf0b01 2025-03-13)
```

It does not reproduce in 1.81.0, when the flag was introduced to `rustdoc`, but I imagine it is simply due to commit fd89197d1bea ("Fix rustdoc missing handling of `remap-path-prefix` option").

### Error output

```
internal error: entered unreachable code: attempted to remap an already remapped filename
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_span/src/source_map.rs:1170:34:
internal error: entered unreachable code: attempted to remap an already remapped filename
stack backtrace:
   0:     0x7d3d472dc07a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he089f96442833f67
   1:     0x7d3d47a14d26 - core::fmt::write::h2f210ed4c94745cb
   2:     0x7d3d4890f7d1 - std::io::Write::write_fmt::h7de08171ab770fb2
   3:     0x7d3d472dbed2 - std::sys::backtrace::BacktraceLock::print::h810fbd31421329e6
   4:     0x7d3d472de477 - std::panicking::default_hook::{{closure}}::hbaad47ed9dc6356d
   5:     0x7d3d472de260 - std::panicking::default_hook::h24e207139139d40a
   6:     0x7d3d4644e258 - std[cba35227022cdb8c]::panicking::update_hook::<alloc[304106e3416ed1f2]::boxed::Box<rustc_driver_impl[16f35eaf1f029c02]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7d3d472decc3 - std::panicking::rust_panic_with_hook::ha9131beeb2ddc506
   8:     0x7d3d472de986 - std::panicking::begin_panic_handler::{{closure}}::h1bba0eaeb6da506f
   9:     0x7d3d472dc549 - std::sys::backtrace::__rust_end_short_backtrace::h1d1ca3eade483f4c
  10:     0x7d3d472de67d - rust_begin_unwind
  11:     0x7d3d43fa1480 - core::panicking::panic_fmt::h896a0727a1a943f9
  12:     0x7d3d48963cfb - <rustc_span[7c0f9ff7c6ad315d]::source_map::FilePathMapping>::map_filename_prefix
  13:     0x7d3d48963e37 - <rustc_span[7c0f9ff7c6ad315d]::source_map::SourceMap>::new_source_file
  14:     0x7d3d48963421 - rustc_parse[192da714918a5014]::new_parser_from_source_str
  15:     0x611ca64e52e6 - rustdoc[bc9829b44a9905a9]::clean::render_macro_matchers::render_macro_matcher
  16:     0x611ca64f6e7f - rustdoc[bc9829b44a9905a9]::clean::utils::render_macro_arms::<core[3b140760090fa97d]::iter::adapters::map::Map<core[3b140760090fa97d]::slice::iter::Chunks<rustc_ast[59cd571f1bf64f97]::tokenstream::TokenTree>, rustdoc[bc9829b44a9905a9]::clean::utils::display_macro_source::{closure#0}>>
  17:     0x611ca64f7069 - rustdoc[bc9829b44a9905a9]::clean::utils::display_macro_source
  18:     0x611ca650e915 - rustdoc[bc9829b44a9905a9]::clean::clean_maybe_renamed_item::{closure#1}
  19:     0x611ca64f81a5 - rustdoc[bc9829b44a9905a9]::clean::clean_doc_module
  20:     0x611ca6522159 - rustdoc[bc9829b44a9905a9]::core::run_global_ctxt
  21:     0x611ca63d5dde - rustc_interface[d49f06094f81b30c]::passes::create_and_enter_global_ctxt::<(), rustdoc[bc9829b44a9905a9]::main_args::{closure#2}::{closure#0}>::{closure#2}::{closure#0}
  22:     0x611ca63e3739 - <rustc_interface[d49f06094f81b30c]::passes::create_and_enter_global_ctxt<(), rustdoc[bc9829b44a9905a9]::main_args::{closure#2}::{closure#0}>::{closure#2} as core[3b140760090fa97d]::ops::function::FnOnce<(&rustc_session[8ddc36379c4b7790]::session::Session, rustc_middle[c26a501345a63c03]::ty::context::CurrentGcx, &std[cba35227022cdb8c]::sync::once_lock::OnceLock<rustc_middle[c26a501345a63c03]::ty::context::GlobalCtxt>, &rustc_data_structures[3109d5d84592bd45]::sync::worker_local::WorkerLocal<rustc_middle[c26a501345a63c03]::arena::Arena>, &rustc_data_structures[3109d5d84592bd45]::sync::worker_local::WorkerLocal<rustc_hir[22be481a0a9f7622]::Arena>, rustdoc[bc9829b44a9905a9]::main_args::{closure#2}::{closure#0})>>::call_once::{shim:vtable#0}
  23:     0x611ca63cf618 - rustc_interface[d49f06094f81b30c]::interface::run_compiler::<(), rustdoc[bc9829b44a9905a9]::main_args::{closure#2}>::{closure#1}
  24:     0x611ca6357f79 - std[cba35227022cdb8c]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d49f06094f81b30c]::util::run_in_thread_with_globals<rustc_interface[d49f06094f81b30c]::util::run_in_thread_pool_with_globals<rustc_interface[d49f06094f81b30c]::interface::run_compiler<(), rustdoc[bc9829b44a9905a9]::main_args::{closure#2}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  25:     0x611ca63df67e - <<std[cba35227022cdb8c]::thread::Builder>::spawn_unchecked_<rustc_interface[d49f06094f81b30c]::util::run_in_thread_with_globals<rustc_interface[d49f06094f81b30c]::util::run_in_thread_pool_with_globals<rustc_interface[d49f06094f81b30c]::interface::run_compiler<(), rustdoc[bc9829b44a9905a9]::main_args::{closure#2}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[3b140760090fa97d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7d3d48835caf - std::sys::pal::unix::thread::Thread::new::thread_start::ha07e360225fa3528
  27:     0x7d3d42a9caa4 - <unknown>
  28:     0x7d3d42b29c3c - <unknown>
  29:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/t/rustc-ice-2025-03-14T20_33_42-48564.txt` to your bug report

note: compiler flags: -Z unstable-options

query stack during panic:
end of query stack
```

</p>
</details>

Cc: @GuillaumeGomez
@rustbot label A-rust-for-linux

### PR DESCRIPTION
**Pull request by charmitro**
This commit fixes an internal compiler error (ICE) that occurs when
rustdoc attempts to process macros with a remapped filename. The issue
arose during macro expansion when the `--remap-path-prefix` option was
used.

Instead of passing remapped filenames through, which would trigger the
"attempted to remap an already remapped filename" panic, we now
extract the original local path from remapped filenames before
processing them.

A test case has been added to verify this behavior.

Fixes #138520

### CODE REVIEW

File: compiler/rustc_span/src/source_map.rs [hunk 1]
```diff
@@ -1155,19 +1155,25 @@ impl FilePathMapping {
...
-                    RealFileName::Remapped {
-                        local_path: Some(local_path.clone()),
-                        virtual_name: mapped_path.into_owned(),
-                    }
-                } else {
-                    realfile.clone()
-                };
-                (FileName::Real(realfile), mapped)
-            }
-            FileName::Real(_) => unreachable!("attempted to remap an already remapped filename"),
```
Comment (Urgau) [inline compiler/rustc_span/src/source_map.rs:1170]: Do we know why we had this `unreachable!`?

Comment (charmitro) [reply compiler/rustc_span/src/source_map.rs:1170]: From my understanding the `unreachable!` was added on the assumption that only `LocalPath` variants would be passed to this function, but when `--remap-path-prefix` support was [added](https://github.com/rust-lang/rust/commit/fd89197d1bea9799302c3584781585c517ca9240) to rustdoc, rustdoc's macro rendering process started passing already remapped filenames during macro expansion.

Comment (Urgau) [reply compiler/rustc_span/src/source_map.rs:1170]: So another solution to the problem would be for rustdoc to not try to remap an already remapped filename. Or to be more precise to not pass to rustc's parser an already remapped filename.

I suspect it might make for sense to create a `RealFilename` in rustdoc macro source rendered (the place where it crashes) by calling `into_local_path` and creating a local `FileName`.

https://github.com/rust-lang/rust/blob/5f3b84a42199278114b6e3d95f406de05e0446f4/src/librustdoc/clean/render_macro_matchers.rs#L54-L68

Btw, it would also be good to add a rustdoc UI test verifying that the original issue is indeed fixed.

Comment (charmitro) [reply compiler/rustc_span/src/source_map.rs:1170]: My alternative implementation for this was,
```diff
@@ -63,7 +63,17 @@ fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String
 
     // Create a Parser.
     let psess = ParseSess::new(rustc_driver::DEFAULT_LOCALE_RESOURCES.to_vec());
-    let file_name = source_map.span_to_filename(span);
+
+    // Get the original filename and ensure we're using a fresh, unmapped filename
+    // to avoid trying to remap an already remapped filename
+    let file_name = match source_map.span_to_filename(span) {
+        FileName::Real(RealFileName::Remapped { local_path: Some(path), .. }) => {
+            // Use the local path instead of the remapped one
+            FileName::Real(RealFileName::LocalPath(path))
+        }
+        other => other,
+    };
+
```

But I was not so sure about. Seems like it is the right fix though?

Comment (Urgau) [reply compiler/rustc_span/src/source_map.rs:1170]: Passing an un-mapped filename should IMO be the right fix.

If you can verify with the reproducer in #138520 that it does fix the issue I would prefer to have this fix.

Comment (charmitro) [reply compiler/rustc_span/src/source_map.rs]: Yes, works. PR force-pushed with v2.

File: src/librustdoc/clean/render_macro_matchers.rs [hunk 2]
```diff
@@ -63,7 +63,21 @@ fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String
 
     // Create a Parser.
     let psess = ParseSess::new(rustc_driver::DEFAULT_LOCALE_RESOURCES.to_vec());
-    let file_name = source_map.span_to_filename(span);
+
+    // Get the original filename and ensure we're using a fresh, unmapped filename
+    // to avoid trying to remap an already remapped filename
+    let file_name = match source_map.span_to_filename(span) {
+        FileName::Real(real_filename) => {
+            if let Some(local_path) = real_filename.clone().into_local_path() {
```
Comment (Urgau) [inline src/librustdoc/clean/render_macro_matchers.rs:71]: `into_local_path()` can fail when "if the file was imported from another crate".

Which would be a issue with re-export of `macro_rules!`, wouldn't it?

File: src/librustdoc/clean/render_macro_matchers.rs [hunk 3]
```diff
@@ -63,7 +63,21 @@ fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String
...
+                FileName::Real(RealFileName::LocalPath(local_path))
```
Comment (Urgau) [inline src/librustdoc/clean/render_macro_matchers.rs:72]:
```suggestion
                FileName::from(local_path)
```

File: src/librustdoc/clean/render_macro_matchers.rs [hunk 4]
```diff
@@ -63,7 +63,21 @@ fn snippet_equal_to_token(tcx: TyCtxt<'_>, matcher: &TokenTree) -> Option<String
 
     // Create a Parser.
     let psess = ParseSess::new(rustc_driver::DEFAULT_LOCALE_RESOURCES.to_vec());
-    let file_name = source_map.span_to_filename(span);
+
+    // Get the original filename and ensure we're using a fresh, unmapped filename
+    // to avoid trying to remap an already remapped filename
+    let file_name = match source_map.span_to_filename(span) {
```
Comment (Urgau) [inline src/librustdoc/clean/render_macro_matchers.rs:69]: I wonder if we even need the filename here, normally it would be used when displaying warning, errors, debuginfo, but none of this is done here, every errors is even cancel below.

We could just use `FileName::macro_expansion_source_code(&snippet)` and call it a day.

File: src/librustdoc/clean/render_macro_matchers.rs (hunk 2 above)
Comment (charmitro) [reply src/librustdoc/clean/render_macro_matchers.rs:71]: IMO using `FileName::macro_expansion_source_code(&snippet)` right away solves this, plus it is a safer approach.

File: src/librustdoc/clean/render_macro_matchers.rs (hunk 4 above)
Comment (charmitro) [reply src/librustdoc/clean/render_macro_matchers.rs:69]: We can & we should, but we need the filename variable for `rustc_parse::new_parser_from_source_str`, no?

**Comment by nnethercote** [comment]
Reassigning the review to @Urgau, who has stronger opinions and more expertise here than I do.

File: src/librustdoc/clean/render_macro_matchers.rs (hunk 4 above)
Comment (Urgau) [reply src/librustdoc/clean/render_macro_matchers.rs:69]: Yes, and I think something like this should do it. The rest can just be removed.
```suggestion
    let file_name = FileName::macro_expansion_source_code(&snippet);
```

Comment (charmitro) [reply src/librustdoc/clean/render_macro_matchers.rs]: Ack. and done!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks for working on this! I'll let @Urgau have the final word.

**Review by Urgau — APPROVED** [review]
