### PR TITLE
Consolidate type system const evaluation under `traits::evaluate_const`

### LINKED ISSUE #118545: ICE: gce: `unable to construct a constant value for the unevaluated constant UnevaluatedConst {..}`
auto-reduced (treereduce-rust):
````rust
struct Checked<const F: fn(usize) -> bool>;

fn not_one(val: usize) -> bool {
    val != 1
}
const _: Checked<not_one> = Checked::<not_one>;

#![feature(generic_const_exprs)]

````

original:
````rust
struct Checked<const F: fn(usize) -> bool>;
//~^ ERROR function pointers as const generic parameters is forbidden
fn not_one(val: usize) -> bool { val != 1 }
const _: Checked<not_one> = Checked::<not_one>;
fn main() {}

````

Version information
````
rustc 1.76.0-nightly (4e3dc976e 2023-12-02)
binary: rustc
commit-hash: 4e3dc976e7876f59373ddc8ac176fe130636bcd1
commit-date: 2023-12-02
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(generic_const_exprs)
  |         ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.gHur7OqFWv0M/rustc_testrunner_tmpdir_reporting.xiUdgEkFncd9/mvce.rs:6:48
  |
6 | const _: Checked<not_one> = Checked::<not_one>;
  |                                                ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.gHur7OqFWv0M/rustc_testrunner_tmpdir_reporting.xiUdgEkFncd9/mvce.rs`

error: using function pointers as const generic parameters is forbidden
 --> /tmp/icemaker_global_tempdir.gHur7OqFWv0M/rustc_testrunner_tmpdir_reporting.xiUdgEkFncd9/mvce.rs:1:25
  |
1 | struct Checked<const F: fn(usize) -> bool>;
  |                         ^^^^^^^^^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`

error: internal compiler error: compiler/rustc_infer/src/infer/mod.rs:1579:17: unable to construct a constant value for the unevaluated constant UnevaluatedConst { def: DefId(0:8 ~ mvce[7b0d]::_::{constant#0}), args: [] }
 --> /tmp/icemaker_global_tempdir.gHur7OqFWv0M/rustc_testrunner_tmpdir_reporting.xiUdgEkFncd9/mvce.rs:6:18
  |
6 | const _: Checked<not_one> = Checked::<not_one>;
  |                  ^^^^^^^

thread 'rustc' panicked at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/compiler/rustc_errors/src/lib.rs:995:33:
Box<dyn Any>
stack backtrace:
   0:     0x7fda6dbd528c - std::backtrace_rs::backtrace::libunwind::trace::h6817338c94b27a3e
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fda6dbd528c - std::backtrace_rs::backtrace::trace_unsynchronized::h0c6d9d3798c92386
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fda6dbd528c - std::sys_common::backtrace::_print_fmt::h834bcd6a65d45603
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fda6dbd528c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h632d407336012a57
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fda6dc282c0 - core::fmt::rt::Argument::fmt::h01e7093f49b63767
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/core/src/fmt/rt.rs:142:9
   5:     0x7fda6dc282c0 - core::fmt::write::h38701b4f0b2dfcb8
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fda6dbc917f - std::io::Write::write_fmt::hb5f3f03cb3ca04d4
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/io/mod.rs:1810:15
   7:     0x7fda6dbd5074 - std::sys_common::backtrace::_print::hd3e5ed5a0b531af5
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fda6dbd5074 - std::sys_common::backtrace::print::hb9af834fe41953f4
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fda6dbd7d07 - std::panicking::default_hook::{{closure}}::h72d658988ab66f01
  10:     0x7fda6dbd7a6f - std::panicking::default_hook::h58213f9fd1d3009c
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/panicking.rs:292:9
  11:     0x7fda6a8f5cd0 - std[df2d6593d7194e63]::panicking::update_hook::<alloc[8a854d67183381ee]::boxed::Box<rustc_driver_impl[6cfe35843c87edd3]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fda6dbd8448 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7fd395d777c5491c
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/alloc/src/boxed.rs:2021:9
  13:     0x7fda6dbd8448 - std::panicking::rust_panic_with_hook::h98c8112ef43197a0
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/panicking.rs:783:13
  14:     0x7fda6ab7e564 - std[df2d6593d7194e63]::panicking::begin_panic::<rustc_errors[1ca61f24e5e0d229]::ExplicitBug>::{closure#0}
  15:     0x7fda6ab68386 - std[df2d6593d7194e63]::sys_common::backtrace::__rust_end_short_backtrace::<std[df2d6593d7194e63]::panicking::begin_panic<rustc_errors[1ca61f24e5e0d229]::ExplicitBug>::{closure#0}, !>
  16:     0x7fda6ab61426 - std[df2d6593d7194e63]::panicking::begin_panic::<rustc_errors[1ca61f24e5e0d229]::ExplicitBug>
  17:     0x7fda6ab51dae - <rustc_errors[1ca61f24e5e0d229]::HandlerInner>::span_bug::<rustc_span[9dcec85a30c01535]::span_encoding::Span, alloc[8a854d67183381ee]::string::String>
  18:     0x7fda6ab51708 - <rustc_errors[1ca61f24e5e0d229]::Handler>::span_bug::<rustc_span[9dcec85a30c01535]::span_encoding::Span, alloc[8a854d67183381ee]::string::String>
  19:     0x7fda6ab7ea9b - rustc_middle[decbaea72911547]::util::bug::opt_span_bug_fmt::<rustc_span[9dcec85a30c01535]::span_encoding::Span>::{closure#0}
  20:     0x7fda6ab7eaca - rustc_middle[decbaea72911547]::ty::context::tls::with_opt::<rustc_middle[decbaea72911547]::util::bug::opt_span_bug_fmt<rustc_span[9dcec85a30c01535]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fda6ab683c8 - rustc_middle[decbaea72911547]::ty::context::tls::with_context_opt::<rustc_middle[decbaea72911547]::ty::context::tls::with_opt<rustc_middle[decbaea72911547]::util::bug::opt_span_bug_fmt<rustc_span[9dcec85a30c01535]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fda6ab65284 - rustc_middle[decbaea72911547]::util::bug::span_bug_fmt::<rustc_span[9dcec85a30c01535]::span_encoding::Span>
  23:     0x7fda6abdb209 - <rustc_infer[d655d61eba052e30]::infer::InferCtxt>::try_const_eval_resolve
  24:     0x7fda6b455819 - <rustc_trait_selection[34dffbdf25348a0a]::traits::fulfill::FulfillProcessor as rustc_data_structures[47340807f7653890]::obligation_forest::ObligationProcessor>::process_obligation::{closure#1}
  25:     0x7fda68d08123 - <rustc_trait_selection[34dffbdf25348a0a]::traits::fulfill::FulfillProcessor as rustc_data_structures[47340807f7653890]::obligation_forest::ObligationProcessor>::process_obligation
  26:     0x7fda6bc11b84 - <rustc_data_structures[47340807f7653890]::obligation_forest::ObligationForest<rustc_trait_selection[34dffbdf25348a0a]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[34dffbdf25348a0a]::traits::fulfill::FulfillProcessor>
  27:     0x7fda6c5a9184 - <rustc_hir_typeck[9593c8bda2de2b24]::fn_ctxt::FnCtxt>::type_inference_fallback
  28:     0x7fda6bf138ad - rustc_hir_typeck[9593c8bda2de2b24]::typeck
  29:     0x7fda6bf12c7d - rustc_query_impl[ff29417da00622fc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ff29417da00622fc]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7fda6be50143 - rustc_query_system[9cd2f7f31604691c]::query::plumbing::try_execute_query::<rustc_query_impl[ff29417da00622fc]::DynamicConfig<rustc_query_system[9cd2f7f31604691c]::query::caches::VecCache<rustc_span[9dcec85a30c01535]::def_id::LocalDefId, rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ff29417da00622fc]::plumbing::QueryCtxt, false>
  31:     0x7fda6be4fdd0 - rustc_query_impl[ff29417da00622fc]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fda6c8d5570 - rustc_hir_analysis[da2a6e1063fa42ac]::check::check::check_mod_item_types
  33:     0x7fda6c8d4fb9 - rustc_query_impl[ff29417da00622fc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ff29417da00622fc]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 0usize]>>
  34:     0x7fda6c5f65bb - rustc_query_system[9cd2f7f31604691c]::query::plumbing::try_execute_query::<rustc_query_impl[ff29417da00622fc]::DynamicConfig<rustc_query_system[9cd2f7f31604691c]::query::caches::DefaultCache<rustc_span[9dcec85a30c01535]::def_id::LocalModDefId, rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ff29417da00622fc]::plumbing::QueryCtxt, false>
  35:     0x7fda6c5f5f97 - rustc_query_impl[ff29417da00622fc]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fda6c624b23 - rustc_hir_analysis[da2a6e1063fa42ac]::check_crate
  37:     0x7fda6c782722 - rustc_interface[6c8aab51a4e81018]::passes::analysis
  38:     0x7fda6c78235d - rustc_query_impl[ff29417da00622fc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ff29417da00622fc]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7fda6cb65e80 - rustc_query_system[9cd2f7f31604691c]::query::plumbing::try_execute_query::<rustc_query_impl[ff29417da00622fc]::DynamicConfig<rustc_query_system[9cd2f7f31604691c]::query::caches::SingleCache<rustc_middle[decbaea72911547]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ff29417da00622fc]::plumbing::QueryCtxt, false>
  40:     0x7fda6cb65c87 - rustc_query_impl[ff29417da00622fc]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7fda6cb74552 - rustc_interface[6c8aab51a4e81018]::interface::run_compiler::<core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>, rustc_driver_impl[6cfe35843c87edd3]::run_compiler::{closure#0}>::{closure#0}
  42:     0x7fda6cb67949 - std[df2d6593d7194e63]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6c8aab51a4e81018]::util::run_in_thread_with_globals<rustc_interface[6c8aab51a4e81018]::util::run_in_thread_pool_with_globals<rustc_interface[6c8aab51a4e81018]::interface::run_compiler<core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>, rustc_driver_impl[6cfe35843c87edd3]::run_compiler::{closure#0}>::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>
  43:     0x7fda6cb67773 - <<std[df2d6593d7194e63]::thread::Builder>::spawn_unchecked_<rustc_interface[6c8aab51a4e81018]::util::run_in_thread_with_globals<rustc_interface[6c8aab51a4e81018]::util::run_in_thread_pool_with_globals<rustc_interface[6c8aab51a4e81018]::interface::run_compiler<core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>, rustc_driver_impl[6cfe35843c87edd3]::run_compiler::{closure#0}>::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[50500588ec9d0052]::result::Result<(), rustc_span[9dcec85a30c01535]::ErrorGuaranteed>>::{closure#1} as core[50500588ec9d0052]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7fda6dbe22d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bfd5ba6e023a698
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/alloc/src/boxed.rs:2007:9
  45:     0x7fda6dbe22d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7da8003a07f4cffa
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/alloc/src/boxed.rs:2007:9
  46:     0x7fda6dbe22d5 - std::sys::unix::thread::Thread::new::thread_start::h64cf2021e889e721
                               at /rustc/4e3dc976e7876f59373ddc8ac176fe130636bcd1/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7fda67aaa9eb - <unknown>
  48:     0x7fda67b2e7cc - <unknown>
  49:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (4e3dc976e 2023-12-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `_`
#1 [check_mod_item_types] checking item types in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #128232: ICE: `unable to construct a valtree for the unevaluated constant`
auto-reduced (treereduce-rust):
````rust



#![feature(generic_const_exprs, unsized_const_params, adt_const_params)]




fn function() -> u32 {
    17
}

struct Wrapper<const F: fn() -> u32>; 

impl<> Wrapper<bar(1, 1)> {
    
    fn call() -> u32 {
        F()
    }
}

fn main() {
    assert_eq!(Wrapper::<function>::call, 17);
}


````

original:
````rust
// Check that functions cannot be used as const parameters.
//@ revisions: min adt_const_params full

#![feature(generic_const_exprs, unsized_const_params, adt_const_params)]
#![zpk(full, allow(incomplete_features))]
#![cfg_attr(adt_const_params, feature(adt_const_params))]
#![cfg_attr(adt_const_params, allow(incomplete_features))]

fn function() -> u32 {
    17
}

struct Wrapper<const F: fn() -> u32>; //~ ERROR: using function pointers as const generic parameters

impl<const F: fn() -> u32> Wrapper<bar(1, 1)> {
    //~^ ERROR: using function pointers as const generic parameters
    fn call() -> u32 {
        F()
    }
}

fn main() {
    assert_eq!(Wrapper::<function>::call(generic_const_exprs, generic_arg_infer), 17);
}

````

Version information
````
rustc 1.82.0-nightly (6ef11b81c 2024-07-26)
binary: rustc
commit-hash: 6ef11b81c2c02c3c4b7556d1991a98572fe9af87
commit-date: 2024-07-26
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected type, found `1`
  --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:15:20
   |
15 | impl<> Wrapper<bar(1, 1)> {
   |                    ^ expected type
   |
help: expressions must be enclosed in braces to be used as const generic arguments
   |
15 | impl<> Wrapper<{ bar(1, 1) }> {
   |                +           +

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:4:12
  |
4 | #![feature(generic_const_exprs, unsized_const_params, adt_const_params)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: the feature `unsized_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:4:33
  |
4 | #![feature(generic_const_exprs, unsized_const_params, adt_const_params)]
  |                                 ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #95174 <https://github.com/rust-lang/rust/issues/95174> for more information

error[E0741]: using function pointers as const generic parameters is forbidden
  --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:13:25
   |
13 | struct Wrapper<const F: fn() -> u32>; 
   |                         ^^^^^^^^^^^

error[E0425]: cannot find function, tuple struct or tuple variant `F` in this scope
  --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:18:9
   |
18 |         F()
   |         ^ not found in this scope

error: internal compiler error: compiler/rustc_infer/src/infer/mod.rs:1412:17: unable to construct a valtree for the unevaluated constant UnevaluatedConst { def: DefId(0:11 ~ mvce[ede4]::main::{constant#0}), args: [] }: type fn() -> u32 is not valtree-compatible
  --> /tmp/icemaker_global_tempdir.ktOk6Uccai2q/rustc_testrunner_tmpdir_reporting.oullzuqu4Neh/mvce.rs:23:26
   |
23 |     assert_eq!(Wrapper::<function>::call, 17);
   |                          ^^^^^^^^

thread 'rustc' panicked at compiler/rustc_infer/src/infer/mod.rs:1412:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f448e505015 - std::backtrace_rs::backtrace::libunwind::trace::hba0c5d2da5d21d3b
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f448e505015 - std::backtrace_rs::backtrace::trace_unsynchronized::h10df601c000a21db
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f448e505015 - std::sys::backtrace::_print_fmt::h9c09a69e66997be5
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/sys/backtrace.rs:68:9
   3:     0x7f448e505015 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8df4565bb0e0abaf
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/sys/backtrace.rs:41:26
   4:     0x7f448e5549eb - core::fmt::rt::Argument::fmt::h2285a02bb70a7a85
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/core/src/fmt/rt.rs:173:76
   5:     0x7f448e5549eb - core::fmt::write::h9f3b68196c3b1892
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/core/src/fmt/mod.rs:1182:21
   6:     0x7f448e4f985f - std::io::Write::write_fmt::h6876ab44488ea710
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/io/mod.rs:1827:15
   7:     0x7f448e507801 - std::sys::backtrace::BacktraceLock::print::he09aebc2da930db5
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/sys/backtrace.rs:44:9
   8:     0x7f448e507801 - std::panicking::default_hook::{{closure}}::h84a3b946e31027b8
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/panicking.rs:269:22
   9:     0x7f448e5074dc - std::panicking::default_hook::hb8beb4cabfcfffe9
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/panicking.rs:296:9
  10:     0x7f448aa4f85a - std[7d30d51779b00fdc]::panicking::update_hook::<alloc[a425665f29645c95]::boxed::Box<rustc_driver_impl[f229ff08257431b3]::install_ice_hook::{closure#0}>>::{closure#0}
  11:     0x7f448e5081cf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2a1b73f9826d619d
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/alloc/src/boxed.rs:2163:9
  12:     0x7f448e5081cf - std::panicking::rust_panic_with_hook::hcb3a582e272725c3
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/panicking.rs:808:13
  13:     0x7f448aa8a5d1 - std[7d30d51779b00fdc]::panicking::begin_panic::<rustc_errors[858d6b59f6c606fd]::ExplicitBug>::{closure#0}
  14:     0x7f448aa7d586 - std[7d30d51779b00fdc]::sys::backtrace::__rust_end_short_backtrace::<std[7d30d51779b00fdc]::panicking::begin_panic<rustc_errors[858d6b59f6c606fd]::ExplicitBug>::{closure#0}, !>
  15:     0x7f448aa78846 - std[7d30d51779b00fdc]::panicking::begin_panic::<rustc_errors[858d6b59f6c606fd]::ExplicitBug>
  16:     0x7f448aa93c11 - <rustc_errors[858d6b59f6c606fd]::diagnostic::BugAbort as rustc_errors[858d6b59f6c606fd]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  17:     0x7f448add7dcd - <rustc_errors[858d6b59f6c606fd]::DiagCtxtHandle>::span_bug::<rustc_span[9dc2d37556667bfe]::span_encoding::Span, alloc[a425665f29645c95]::string::String>
  18:     0x7f448adfdf98 - rustc_middle[79a84c3fef91123a]::util::bug::opt_span_bug_fmt::<rustc_span[9dc2d37556667bfe]::span_encoding::Span>::{closure#0}
  19:     0x7f448ae00eea - rustc_middle[79a84c3fef91123a]::ty::context::tls::with_opt::<rustc_middle[79a84c3fef91123a]::util::bug::opt_span_bug_fmt<rustc_span[9dc2d37556667bfe]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f448ade190b - rustc_middle[79a84c3fef91123a]::ty::context::tls::with_context_opt::<rustc_middle[79a84c3fef91123a]::ty::context::tls::with_opt<rustc_middle[79a84c3fef91123a]::util::bug::opt_span_bug_fmt<rustc_span[9dc2d37556667bfe]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f448a398237 - rustc_middle[79a84c3fef91123a]::util::bug::span_bug_fmt::<rustc_span[9dc2d37556667bfe]::span_encoding::Span>
  22:     0x7f448ae17121 - <rustc_infer[5a8779d3ea9a51cc]::infer::InferCtxt>::try_const_eval_resolve
  23:     0x7f44889b4cd5 - <rustc_trait_selection[7be6dcd4e93fc1a0]::traits::fulfill::FulfillProcessor as rustc_data_structures[c4c8cdbb129cb916]::obligation_forest::ObligationProcessor>::process_obligation
  24:     0x7f448c273c0a - <rustc_data_structures[c4c8cdbb129cb916]::obligation_forest::ObligationForest<rustc_trait_selection[7be6dcd4e93fc1a0]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[7be6dcd4e93fc1a0]::traits::fulfill::FulfillProcessor>
  25:     0x7f448c55a5e6 - <core[ed9eac647662a901]::iter::adapters::filter::Filter<core[ed9eac647662a901]::iter::adapters::map::Map<core[ed9eac647662a901]::slice::iter::Iter<rustc_hir_typeck[ac02ac983fee86f6]::method::probe::Candidate>, <rustc_hir_typeck[ac02ac983fee86f6]::method::probe::ProbeContext>::consider_candidates::{closure#0}>, <rustc_hir_typeck[ac02ac983fee86f6]::method::probe::ProbeContext>::consider_candidates::{closure#1}> as core[ed9eac647662a901]::iter::traits::iterator::Iterator>::next
  26:     0x7f448c565897 - <rustc_hir_typeck[ac02ac983fee86f6]::method::probe::ProbeContext>::pick_method
  27:     0x7f448c564fa7 - <rustc_hir_typeck[ac02ac983fee86f6]::method::probe::ProbeContext>::pick_core
  28:     0x7f448c508350 - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::probe_for_name
  29:     0x7f448c51cbcf - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_path
  30:     0x7f448ca7e834 - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7f448ca8180b - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7f448ca85a2f - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  33:     0x7f448ca73f69 - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  34:     0x7f448ca8221e - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  35:     0x7f448ca7aa5b - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_block_with_expected
  36:     0x7f448ca8119d - <rustc_hir_typeck[ac02ac983fee86f6]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:     0x7f448c1cc677 - rustc_hir_typeck[ac02ac983fee86f6]::check::check_fn
  38:     0x7f448c1c23c3 - rustc_hir_typeck[ac02ac983fee86f6]::typeck
  39:     0x7f448c1c1d69 - rustc_query_impl[6f72a32bb9596f00]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f72a32bb9596f00]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[79a84c3fef91123a]::query::erase::Erased<[u8; 8usize]>>
  40:     0x7f448c36d4b3 - rustc_query_system[b72a41914d7622ff]::query::plumbing::try_execute_query::<rustc_query_impl[6f72a32bb9596f00]::DynamicConfig<rustc_query_system[b72a41914d7622ff]::query::caches::VecCache<rustc_span[9dc2d37556667bfe]::def_id::LocalDefId, rustc_middle[79a84c3fef91123a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6f72a32bb9596f00]::plumbing::QueryCtxt, false>
  41:     0x7f448c36c68d - rustc_query_impl[6f72a32bb9596f00]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7f448c36c28e - <rustc_middle[79a84c3fef91123a]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[799f0addd470a8f5]::check_crate::{closure#4}>::{closure#0}
  43:     0x7f448c36a0ce - rustc_hir_analysis[799f0addd470a8f5]::check_crate
  44:     0x7f448c360795 - rustc_interface[8d3212ab15a5ab63]::passes::analysis
  45:     0x7f448c360347 - rustc_query_impl[6f72a32bb9596f00]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f72a32bb9596f00]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[79a84c3fef91123a]::query::erase::Erased<[u8; 1usize]>>
  46:     0x7f448ce85265 - rustc_query_system[b72a41914d7622ff]::query::plumbing::try_execute_query::<rustc_query_impl[6f72a32bb9596f00]::DynamicConfig<rustc_query_system[b72a41914d7622ff]::query::caches::SingleCache<rustc_middle[79a84c3fef91123a]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[6f72a32bb9596f00]::plumbing::QueryCtxt, false>
  47:     0x7f448ce84fcf - rustc_query_impl[6f72a32bb9596f00]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7f448cd35385 - rustc_interface[8d3212ab15a5ab63]::interface::run_compiler::<core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>, rustc_driver_impl[f229ff08257431b3]::run_compiler::{closure#0}>::{closure#1}
  49:     0x7f448cd1a709 - std[7d30d51779b00fdc]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8d3212ab15a5ab63]::util::run_in_thread_with_globals<rustc_interface[8d3212ab15a5ab63]::util::run_in_thread_pool_with_globals<rustc_interface[8d3212ab15a5ab63]::interface::run_compiler<core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>, rustc_driver_impl[f229ff08257431b3]::run_compiler::{closure#0}>::{closure#1}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>::{closure#0}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>
  50:     0x7f448cd1a4ba - <<std[7d30d51779b00fdc]::thread::Builder>::spawn_unchecked_<rustc_interface[8d3212ab15a5ab63]::util::run_in_thread_with_globals<rustc_interface[8d3212ab15a5ab63]::util::run_in_thread_pool_with_globals<rustc_interface[8d3212ab15a5ab63]::interface::run_compiler<core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>, rustc_driver_impl[f229ff08257431b3]::run_compiler::{closure#0}>::{closure#1}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>::{closure#0}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ed9eac647662a901]::result::Result<(), rustc_span[9dc2d37556667bfe]::ErrorGuaranteed>>::{closure#1} as core[ed9eac647662a901]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:     0x7f448e51211b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdb8f7dfc3eda67f4
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/alloc/src/boxed.rs:2149:9
  52:     0x7f448e51211b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h969b7c01506b8601
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/alloc/src/boxed.rs:2149:9
  53:     0x7f448e51211b - std::sys::pal::unix::thread::Thread::new::thread_start::he6f3cf1932d26a89
                               at /rustc/6ef11b81c2c02c3c4b7556d1991a98572fe9af87/library/std/src/sys/pal/unix/thread.rs:108:17
  54:     0x7f44874a6ded - <unknown>
  55:     0x7f448752a0dc - <unknown>
  56:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (6ef11b81c 2024-07-26) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0425, E0741.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

@rustbot label +F-generic_const_exprs +F-unsized_const_params +F-adt_const_params

### PR DESCRIPTION
**Pull request by BoxyUwU**
Part of #130704

Fixes #128232
Fixes #118545

Removes `ty::Const::{normalize_internal, eval_valtree}` and `InferCtxt::(try_)const_eval_resolve`, consolidating the associated logic into `evaluate_const` in `rustc_trait_selection`. This results in an API for `ty::Const` that is free of any normalization/evaluation functions that would be incorrect to use under `min_generic_const_args`/`associated_const_equality`/`generic_const_exprs` or, more generally, that would be incorrect to use in the presence of generic type system constants.

Moving this logic to `rustc_trait_selection` and out of `rustc_middle` is also a pre-requisite for ensuring that we do not evaluate constants whose where clauses do not hold.

From this point it should be relatively simple (hah) to implement more complex normalization of type system constants such as: checking wf'ness before invoking CTFE machinery, or being able to normalize const aliases that still refer to generic parameters.

r? @compiler-errors

### CODE REVIEW

File: tests/ui/const-generics/generic_const_exprs/unify-op-with-fn-call.rs [hunk 1]
```diff
@@ -1,36 +0,0 @@
-//@ known-bug: #110395
-//@ compile-flags: -Znext-solver
-#![feature(generic_const_exprs, adt_const_params, const_trait_impl)]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/generic_const_exprs/unify-op-with-fn-call.rs:3]: `known-bug` `-Z-next-solver` `feature(generic_const_expr)` tests seem a little pointless seeing as how these features are known to not work together and I do not think there is any intention of making them work together.

File: tests/ui/traits/const-traits/const-trait-bounds.rs [hunk 2]
```diff
@@ -1,32 +0,0 @@
-//@ known-bug: #110395
-//@ compile-flags: -Znext-solver
-// FIXME(const_trait_impl): check-pass
-#![feature(const_trait_impl, generic_const_exprs)]
```
Comment (BoxyUwU) [inline tests/ui/traits/const-traits/const-trait-bounds.rs:4]: ditto

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 3]
```diff
@@ -961,10 +960,12 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
                                 Err(_) => Ok(EvaluatedToErr),
                             }
                         }
-                        (Err(ErrorHandled::Reported(..)), _)
-                        | (_, Err(ErrorHandled::Reported(..))) => Ok(EvaluatedToErr),
-                        (Err(ErrorHandled::TooGeneric(..)), _)
-                        | (_, Err(ErrorHandled::TooGeneric(..))) => {
+                        (Err(EvaluateConstErr::InvalidConstParamTy(..)), _)
+                        | (_, Err(EvaluateConstErr::InvalidConstParamTy(..))) => Ok(EvaluatedToErr),
+                        (Err(EvaluateConstErr::CTFEFailure(..)), _)
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:965]: super weird nit but `CTFEFailure` is kinda a mouthful. Could we just name it `EvaluationFailure` or something?

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 4]
```diff
@@ -474,6 +483,179 @@ pub fn normalize_param_env_or_error<'tcx>(
     ty::ParamEnv::new(tcx.mk_clauses(&predicates), unnormalized_env.reveal())
 }
 
+#[derive(Debug)]
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/mod.rs:486]: Could you give these doc comments pls?

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 5]
```diff
@@ -474,6 +483,179 @@ pub fn normalize_param_env_or_error<'tcx>(
...
+pub enum EvaluateConstErr {
+    HasGenericsOrInfers,
+    InvalidConstParamTy(ErrorGuaranteed),
+    CTFEFailure(ErrorGuaranteed),
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/mod.rs:490]: I commented below, but `CTFEFailure` is a bit of a mouthful. Not totally sure what a shorter name is, but at least could we document what kinds of failures it's meant to represent?

File: compiler/rustc_trait_selection/src/traits/const_evaluatable.rs [hunk 6]
```diff
@@ -92,16 +93,7 @@ pub fn is_const_evaluatable<'tcx>(
             _ => bug!("unexpected constkind in `is_const_evalautable: {unexpanded_ct:?}`"),
         };
 
-        // FIXME: We should only try to evaluate a given constant here if it is fully concrete
-        // as we don't want to allow things like `[u8; std::mem::size_of::<*mut T>()]`.
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:96]: `try_evaluate_const` will be responsible for not evaluating if generic parameters are being used

File: compiler/rustc_trait_selection/src/solve/delegate.rs [hunk 7]
```diff
@@ -77,20 +77,17 @@ impl<'tcx> rustc_next_trait_solver::delegate::SolverDelegate for SolverDelegate<
...
-                val,
-                self.tcx.type_of(unevaluated.def).instantiate(self.tcx, unevaluated.args),
-            )),
-            Ok(Err(_)) | Err(ErrorHandled::TooGeneric(_)) => None,
-            Err(ErrorHandled::Reported(e, _)) => Some(ty::Const::new_error(self.tcx, e.into())),
+        match crate::traits::try_evaluate_const(&self.0, ct, param_env) {
+            Ok(ct) => Some(ct),
+            Err(EvaluateConstErr::CTFEFailure(e)) => Some(ty::Const::new_error(self.tcx, e)),
+            Err(
+                EvaluateConstErr::InvalidConstParamTy(_) | EvaluateConstErr::HasGenericsOrInfers,
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/solve/delegate.rs:89]: We could probably make a `ConstKind::Error` out of `InvalidConstParamTy` here but I wanted to keep behaviour the same as before this PR

File: compiler/rustc_next_trait_solver/src/delegate.rs [hunk 8]
```diff
@@ -29,10 +29,10 @@ pub trait SolverDelegate: Deref<Target = <Self as SolverDelegate>::Infcx> + Size
     // FIXME: Uplift the leak check into this crate.
     fn leak_check(&self, max_input_universe: ty::UniverseIndex) -> Result<(), NoSolution>;
 
-    fn try_const_eval_resolve(
+    fn evaluate_const(
         &self,
         param_env: <Self::Interner as Interner>::ParamEnv,
-        unevaluated: ty::UnevaluatedConst<Self::Interner>,
```
Comment (BoxyUwU) [inline compiler/rustc_next_trait_solver/src/delegate.rs:35]: We use a `Const` not a `UnevaluatedConst` as `traits::evaluate_const` accepts a `Const` not a `UnevaluatedConst` so that the normalization routines can just call it on their `Const` instead of having to match on the `ConstKind`. It wouldn't surprise me if we changed this when proper associated const normalization is implemented

File: compiler/rustc_trait_selection/src/traits/mod.rs [hunk 9]
```diff
@@ -366,11 +367,19 @@ pub fn normalize_param_env_or_error<'tcx>(
                     if c.has_escaping_bound_vars() {
                         return ty::Const::new_misc_error(self.0);
                     }
+
                     // While it is pretty sus to be evaluating things with an empty param env, it
                     // should actually be okay since without `feature(generic_const_exprs)` the only
                     // const arguments that have a non-empty param env are array repeat counts. These
                     // do not appear in the type system though.
-                    c.normalize_internal(self.0, ty::ParamEnv::empty())
+                    if let ty::ConstKind::Unevaluated(uv) = c.kind()
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/mod.rs:375]: I wonder if instead of making a new infcx, we should possibly instead move this folder into `do_normalize_predicates`, where we do make a new infcx. I guess we expect that this just evaluates to a valtree or rigid const?

If not, we should at least assert that nothing is leaking out of this infcx (infer vars/placeholders).

File: compiler/rustc_trait_selection/src/traits/fulfill.rs [hunk 10]
```diff
@@ -662,30 +662,28 @@ impl<'a, 'tcx> ObligationProcessor for FulfillProcessor<'a, 'tcx> {
...
+                        |c: Const<'tcx>| {
+                            if let ty::ConstKind::Unevaluated(unevaluated) = c.kind() {
+                                match super::try_evaluate_const(
+                                    self.selcx.infcx,
+                                    c,
+                                    obligation.param_env,
+                                ) {
+                                    Ok(val) => Ok(val),
+                                    Err(e) => {
+                                        if let EvaluateConstErr::HasGenericsOrInfers = e {
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/fulfill.rs:675]: can u make this match exhaustive?

File: compiler/rustc_middle/src/mir/consts.rs [hunk 11]
```diff
@@ -319,15 +319,13 @@ impl<'tcx> Const<'tcx> {
     ) -> Result<ConstValue<'tcx>, ErrorHandled> {
         match self {
             Const::Ty(_, c) => {
-                // We want to consistently have a "clean" value for type system constants (i.e., no
-                // data hidden in the padding), so we always go through a valtree here.
-                match c.eval_valtree(tcx, param_env, span) {
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/mir/consts.rs:324]: Evaluating here is pointless as MIR is normalized on construction so the only aliases we should encounter will be rigid aliases that cannot be furthur normalized. Monomorphization will also immediately normalize any instantiated rigid aliases turning them into `ConstKind::Value` so this should also not do anything during codegen

File: compiler/rustc_trait_selection/src/solve/delegate.rs [hunk 12]
```diff
@@ -77,20 +77,17 @@ impl<'tcx> rustc_next_trait_solver::delegate::SolverDelegate for SolverDelegate<
...
-                self.tcx,
-                val,
-                self.tcx.type_of(unevaluated.def).instantiate(self.tcx, unevaluated.args),
-            )),
-            Ok(Err(_)) | Err(ErrorHandled::TooGeneric(_)) => None,
-            Err(ErrorHandled::Reported(e, _)) => Some(ty::Const::new_error(self.tcx, e.into())),
+        match crate::traits::try_evaluate_const(&self.0, ct, param_env) {
+            Ok(ct) => Some(ct),
+            Err(EvaluateConstErr::CTFEFailure(e)) => Some(ty::Const::new_error(self.tcx, e)),
+            Err(
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/solve/delegate.rs:88]: Why are we handling `InvalidConstParamTy` differently here? Should we not just be turning it into a `ConstKind::Error`?

File: compiler/rustc_middle/src/mir/consts.rs [hunk 13]
```diff
@@ -319,15 +319,13 @@ impl<'tcx> Const<'tcx> {
...
-                        .delayed_bug("`mir::Const::eval` called on a non-valtree-compatible type")
-                        .into()),
-                    Err(Either::Right(e)) => Err(e),
+                if c.has_non_region_param() {
+                    return Err(ErrorHandled::TooGeneric(span));
+                }
+
+                match c.kind() {
+                    ConstKind::Value(ty, val) => Ok(tcx.valtree_to_const_val((ty, val))),
+                    _ => Err(tcx.dcx().delayed_bug("Unevaluated `ty::Const` in MIR body").into()),
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/mir/consts.rs:328]: This is perhaps not quite right if we have a situation like `<u8 as Trait<impl Trait>>::ASSOC`. This would be a fully concrete rigid alias that is not normalized due to the opaque type. This is only possible to reach on nightly via unstable features that represent type system constants directly without an anon const.

I expect that long term we should just not encounter such a scenario by always normalizing type system constants in `Reveal::All` as CTFE unconditionally uses `Reveal::All` even during typeck *anyway*

File: compiler/rustc_next_trait_solver/src/solve/eval_ctxt/mod.rs [hunk 14]
```diff
@@ -1001,12 +1001,8 @@ where
     // Try to evaluate a const, or return `None` if the const is too generic.
     // This doesn't mean the const isn't evaluatable, though, and should be treated
     // as an ambiguity rather than no-solution.
-    pub(super) fn try_const_eval_resolve(
-        &self,
-        param_env: I::ParamEnv,
-        unevaluated: ty::UnevaluatedConst<I>,
-    ) -> Option<I::Const> {
-        self.delegate.try_const_eval_resolve(param_env, unevaluated)
+    pub(super) fn evaluate_const(&self, param_env: I::ParamEnv, ct: I::Const) -> Option<I::Const> {
```
Comment (compiler-errors) [inline compiler/rustc_next_trait_solver/src/solve/eval_ctxt/mod.rs:1004]: What's the benefit of taking a `I::Const` here rather than the `UnevaluatedConst` directly? 

I think that making the input type *more specific* would make it less confusing that we only call today for uv consts

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 15]
```diff
@@ -81,27 +85,35 @@ impl<'tcx> ConstToPat<'tcx> {
...
-                        // Let's tell the use where this failing const occurs.
-                        self.tcx().dcx().emit_err(CouldNotEvalConstPattern { span: self.span })
-                    }
-                    ErrorHandled::TooGeneric(_) => self
-                        .tcx()
-                        .dcx()
-                        .emit_err(ConstPatternDependsOnGenericParameter { span: self.span }),
-                };
-                return pat_from_kind(PatKind::Error(err));
+        let param_env =
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:96]: It would be nice to write some justification for why we end up needing to reveal here; I think you just copied this from `prepare_for_eval`, but it might look kinda spooky to people who aren't yet familiar with this code or its history.

File: compiler/rustc_middle/src/mir/consts.rs [hunk 16]
```diff
@@ -319,15 +319,13 @@ impl<'tcx> Const<'tcx> {
...
-                // We want to consistently have a "clean" value for type system constants (i.e., no
-                // data hidden in the padding), so we always go through a valtree here.
-                match c.eval_valtree(tcx, param_env, span) {
-                    Ok((ty, val)) => Ok(tcx.valtree_to_const_val((ty, val))),
-                    Err(Either::Left(_bad_ty)) => Err(tcx
-                        .dcx()
-                        .delayed_bug("`mir::Const::eval` called on a non-valtree-compatible type")
-                        .into()),
-                    Err(Either::Right(e)) => Err(e),
+                if c.has_non_region_param() {
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/mir/consts.rs:322]: Do you want to leave a FIXME here that this may not handle things like `<impl Tr as Tr>::CONST` correctly?

**Review by compiler-errors — COMMENTED** [review]
Some initial thoughts

File: compiler/rustc_trait_selection/src/solve/delegate.rs (hunk 7 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/solve/delegate.rs:89]: Ok, I think I asked below why this was like that, but if it's preexisting then 👍

File: compiler/rustc_middle/src/mir/consts.rs (hunk 13 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/mir/consts.rs:328]: I think I mentioned leaving a FIXME below

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 5 above)
Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/mod.rs:490]: This also perhaps could just be called `ErrorReported` since it's always downstream of an error being reported. Also, we may be able to just fold `InvalidConstParamTy` into it. If that's not worthwhile to do this PR, could you leave a FIXME?

**Comment by compiler-errors** [comment]
clippy moment :ferrisClueless:

File: compiler/rustc_middle/src/mir/consts.rs (hunk 13 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/mir/consts.rs:328]: Nevermind, we always evaluate in `Reveal::All` so it should not be possible to encounter a fully concrete `ty::Const` that is also an alias as we would have simply evaluated it away.

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 9 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs:375]: `do_normalize_predicates` doesn't work as we attempt to normalize the predicates in an environment that has unnormalized anon consts. I will update this to assert we dont have any infcx local state leak out though I think this is pretty unfortunate...

File: compiler/rustc_next_trait_solver/src/delegate.rs (hunk 8 above)
Comment (BoxyUwU) [reply compiler/rustc_next_trait_solver/src/delegate.rs:35]: When we implement "proper" normalization of associated constants I expect us to want to start matching on the `ConstKind` in the normalization folders, at which point `traits::evaluate_const` should probably just take `ty::UnevaluatedConst`, at which point yeah we probably change this back to `ty::UnevaluatedConst`.

File: compiler/rustc_trait_selection/src/traits/mod.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_trait_selection/src/traits/mod.rs]: I'm not entirely sure if we can fold them into the same variant or not. I would be a bit nervous about normalizing away some ill formed constant to a `ConstKind::Error` with a `bug!` and then never actually emitting an error about its type not matching up with the parameter it was an argument to.

File: compiler/rustc_next_trait_solver/src/delegate.rs (hunk 8 above)
Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/delegate.rs:35]: 👍

**Comment by compiler-errors** [comment]
r=me when green
