### PR TITLE
Adjust the pointer to an unsized field to the correct alignment

### LINKED ISSUE #26403: When DST struct's last field is misaligned, memory access generated are for the wrong address
Example
```rust
struct Foo<T: ?Sized + Bar> {
    a: u8,
    b: T
}

trait Bar {
    fn get(&self) -> usize;
}

struct BarImpl {
    i: usize
}

impl Bar for BarImpl {
    fn get(&self) -> usize {
        self.i
    }
}


fn main() {
    let f = Foo { a:1, b: BarImpl { i: 5 } };
    assert!(f.b.get() == 5); // succeeds
    let f = &f as &Foo<Bar>;
    assert!(f.b.get() == 5); // assert fails
}
```
[in playpen](https://play.rust-lang.org/?gist=fcdeb47dbc05e243cfc6&version=nightly)

### PR DESCRIPTION
**Pull request by Aatch**
Fixes #26403

This adjusts the pointer, if needed, to the correct alignment by using the alignment information in the vtable.

Handling zero might not be necessary, as it shouldn't actually occur. I've left it as it's own commit so it can be removed fairly easily if people don't think it's worth doing. The way it's handled though means that there shouldn't be much impact on performance.

### CODE REVIEW

File: src/librustc_trans/trans/expr.rs [hunk 1]
```diff
@@ -742,9 +742,58 @@ fn trans_field<'blk, 'tcx, F>(bcx: Block<'blk, 'tcx>,
     if type_is_sized(bcx.tcx(), d.ty) {
         DatumBlock { datum: d.to_expr_datum(), bcx: bcx }
     } else {
+        let info = Load(bcx, get_meta(bcx, base_datum.val));
+        // Adjust the pointer, if needed, so it has the correct alignment.
+        match d.ty.sty {
```
Comment (nrc) [inline src/librustc_trans/trans/expr.rs]: nit: prefer `if let` to `match` here

File: src/librustc_trans/trans/expr.rs [hunk 2]
```diff
@@ -742,9 +742,58 @@ fn trans_field<'blk, 'tcx, F>(bcx: Block<'blk, 'tcx>,
...
+            ty::TyTrait(..) => {
+                // We only need to align trait DSTs, as str only needs single-byte alignment
+                // and [T] is represented with T.
+                debug!("Field pointer `{}` needs adjustment", bcx.val_to_string(d.val));
+                assert_eq!(val_ty(d.val), Type::i8p(bcx.ccx()));
+
+                let debug_loc = base.debug_loc();
+
+                let st = match &*repr {
```
Comment (nrc) [inline src/librustc_trans/trans/expr.rs]: could you use a more informative name than `st` here?

File: src/test/run-pass/dst-field-align.rs [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+    // The pointers should be the same
+    assert_eq!(ptr1, ptr2);
+
+    // Test that packed structs are handled correctly
+    let p : Packed<usize> = Packed { a: 0, b: 13 };
+    assert_eq!(p.b.get(), 13);
+    let p : &Packed<Bar> = &p;
+    assert_eq!(p.b.get(), 13);
+}
```
Comment (nrc) [inline src/test/run-pass/dst-field-align.rs]: Could you add a test for nested structs, e.g., `Foo<Foo<Bar>>` please

Comment (Aatch) [inline src/test/run-pass/dst-field-align.rs]: Ah, didn't think of that case. Will do.

**Comment by nrc** [comment]
lgtm, r+ with the extra test and nits addressed.

**Comment by Aatch** [comment]
Bah, I just realised this doesn't handle pattern matching! Looks like I need to re-think this some more.

**Comment by pnkfelix** [comment]
> Handling zero might not be necessary, as it shouldn't actually occur. 

Indeed; I might prefer to see the code, when compiled in debug mode, emit a debugtrap upon encountering zero, rather than trying to accept it.  (I'm more concerned about catching bugs elsewhere than I am about the potential perfomance overhead of handling zero.)

**Comment by Aatch** [comment]
Basically rewrote the entire change, so I squashed it down into a single commit. The test has been amended to include a test for getting pointer to a DST field via pattern matching, something that caused an ICE previously.

File: src/librustc_trans/trans/mir/lvalue.rs [hunk 4]
```diff
@@ -116,8 +116,14 @@ impl<'bcx, 'tcx> MirContext<'bcx, 'tcx> {
                             LvalueTy::Downcast { adt_def: _, substs: _, variant_index: v } => v,
                         };
                         let discr = discr as u64;
-                        (adt::trans_field_ptr(bcx, &base_repr, tr_base.llval, discr, field.index()),
-                         if common::type_is_sized(tcx, projected_ty.to_ty(tcx)) {
+                        let is_sized = common::type_is_sized(tcx, projected_ty.to_ty(tcx));
```
Comment (arielb1) [inline src/librustc_trans/trans/mir/lvalue.rs]: Just use the `MaybeSizedValue::unsized_`  directly. `llextra` has the right semantics.

File: src/librustc_trans/trans/adt.rs [hunk 5]
```diff
@@ -1075,18 +1103,94 @@ pub fn trans_field_ptr<'blk, 'tcx>(bcx: Block<'blk, 'tcx>, r: &Repr<'tcx>,
...
+    // any adjusments
+    match fty.sty {
+        ty::TySlice(..) | ty::TyStr => {
+            return StructGEP(bcx, ptr_val, ix);
+        }
+        _ => ()
+    }
+
+    // There's no metadata available, log the case and just do the GEP.
+    if !val.has_meta() {
```
Comment (nrc) [inline src/librustc_trans/trans/adt.rs]: Why would we hit this case? Should we not panic or give a user-facing error here?

File: src/librustc_trans/trans/adt.rs [hunk 6]
```diff
@@ -1075,18 +1103,94 @@ pub fn trans_field_ptr<'blk, 'tcx>(bcx: Block<'blk, 'tcx>, r: &Repr<'tcx>,
...
+               bcx.val_to_string(ptr_val));
+        return StructGEP(bcx, ptr_val, ix);
+    }
+
+    let dbloc = DebugLoc::None;
+
+    // We need to get the pointer manually now.
+    // We do this by casting to a *i8, then offsetting it by the appropriate amount.
+    // We do this instead of, say, simply adjusting the pointer from the result of a GEP
+    // because the the field may have an arbitrary alignment in the LLVM representation
```
Comment (nrc) [inline src/librustc_trans/trans/adt.rs]: typo: the the

File: src/librustc_trans/trans/mir/lvalue.rs (hunk 4 above)
Comment (Aatch) [inline src/librustc_trans/trans/mir/lvalue.rs]: As in llextra is a nullptr if the type is sized? Works for me. I wasn't sure because of the `if type_is_sized { llextra } else { ptr::null_mut() }` in there.

File: src/librustc_trans/trans/adt.rs (hunk 5 above)
Comment (Aatch) [inline src/librustc_trans/trans/adt.rs]: I wasn't sure. It *shouldn't* happen, but I can't actually guarantee that and I didn't want to introduce a regression simply because I forgot to handle some case elsewhere. That said, I'm not actually against an error message here.

**Comment by Aatch** [comment]
I'm pretty sure I broke something related to slice DSTs, not sure how though. I'm get the same failures locally as the travis build.
