### PR TITLE
rustc: Allow `#[no_mangle]` anywhere in a crate

### LINKED ISSUE #54135: #[used] and symbol visibility is unclear
I was excited to see `#[used]` stabilized (yay!) as [one of the issues](https://github.com/rustwasm/wasm-bindgen/issues/201) we suffer from in `wasm-bindgen` is related to symbols being removed. Unfortunately though `#[used]` doesn't solve our use case!

First I'll try to explain our issue a bit. The `#[wasm_bindgen]` attribute allows you to import JS functionality into a Rust program. This doesn't work, however, when you import JS functions into a private Rust submodule. (aka `mod foo { ... }`). When importing a function we *also* generate an internal exported function which the CLI `wasm-bindgen` tool uses (and then removes), but it suffices to say that we're generating code that looks like:

```rust
mod private {
    #[no_mangle]
    pub extern fn foo() { /* ... */ }
}
```

Today the symbol `foo` is not considered alive by rustc itself as it's not reachable. As a result, it's not even translated into the object file. If we instead change this though:

```rust
#![feature(used)]

mod private {
    #[no_mangle]
    pub extern fn foo() {}
    
    #[used]
    static F: extern fn() = foo;
}
```

This *still* doesn't work! Unfortunately for us the `#[used]` works as intended but doesn't affect the symbol visibility. The above program [generates this IR](https://play.rust-lang.org/?gist=4f3c68a523c9ce345265807849cf812e&version=nightly&mode=release&edition=2015):

```ll
; ModuleID = 'playground.7pbp0xok-cgu.0'
source_filename = "playground.7pbp0xok-cgu.0"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@_ZN10playground7private1F17hb0dc3802d85fadd7E = internal constant <{ i8*, [0 x i8] }> <{ i8* bitcast (void ()* @foo to i8*), [0 x i8] zeroinitializer }>, align 8
@llvm.used = appending global [1 x i8*] [i8* bitcast (<{ i8*, [0 x i8] }>* @_ZN10playground7private1F17hb0dc3802d85fadd7E to i8*)], section "llvm.metadata"

; Function Attrs: norecurse nounwind readnone uwtable
define internal void @foo() unnamed_addr #0 {
start:
  ret void
}

attributes #0 = { norecurse nounwind readnone uwtable "probe-stack"="__rust_probestack" }
```

the problem here is that the symbol `foo`, while not mangled, is still marked as `internal`. This in turns means that it does indeed reach the linker, but for our purposes in `wasm-bindgen` we need it to *survive* the linker, not just reach the linker.

---

Ok so that's the problem statement for `wasm-bindgen`, but you can generalize it today for rustc by asking: what does `#[used]` do to symbol visibility? The overall story for symbol visibility in rustc is a little muddied and not always great (especially on ABI-particulars like `#[no_mangle]` things). 

What *should* the symbol visibility of `foo` be here?

```rust
mod private {
    #[no_mangle]
    pub extern fn foo() {}
    
    #[used]
    static F: extern fn() = foo;
}
```

We've always had a basic rule of thumb in Rust that "reachable symbols" have non-internal visibility, but it's not clear what to do here. `foo` is indeed a reachable symbol because of `#[used]`, but it's in a private module. Does that mean because of `pub` and `#[no_mangle]` it shouldn't have `internal` visibility? Should only `#[no_mangle]` imply that? It's unclear to me!

I'd naively like to send a patch that makes foo not-`internal` because it has `#[no_mangle]` and `pub` (not that it's "publicly reachable"). I think though that this may be deeper in the compiler. I just took a look at how `#[used]` works, and it's actually a little suprising!

In `src/librustc_mir/monomorphize/collector.rs` we attempt to not translate anything not reachable in a crate as a form of DCE. I didn't find any handling of `#[used]`, though, and it turns out we unconditionally translate all statics all the time! Then becuase we put it in `llvm.used` it ends up not getting gc'd by LLVM.

I think that we may want to future-proof this by updating the `src/librustc/middle/reachable.rs` collection step to basically push `#[used]` statics onto the worklist to process. The initial worklist is seeded with all items that are public by visibility, and I think we could change it to *also* be seeded with any `#[used]` statics. This means that anything referenced by a `#[used]` static will be pulled in as a result.

Do others think this is a reasonable strategy for having `#[used]` affect symbol visibility?

cc @michaelwoerister 
cc @fitzgen 
cc @japaric

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the compiler to allow the `#[no_mangle]` (and
`#[export_name]` attributes) to be located anywhere within a crate.
These attributes are unconditionally processed, causing the compiler to
always generate an exported symbol with the appropriate name.

After some discussion on #54135 it was found that not a great reason
this hasn't been allowed already, and it seems to match the behavior
that many expect! Previously the compiler would only export a
`#[no_mangle]` symbol if it were *publicly reachable*, meaning that it
itself is `pub` and it's otherwise publicly reachable from the root of
the crate. This new definition is that `#[no_mangle]` *is always
reachable*, no matter where it is in a crate or whether it has `pub` or
not.

This should make it much easier to declare an exported symbol with a
known and unique name, even when it's an internal implementation detail
of the crate itself. Note that these symbols will persist beyond LTO as
well, always making their way to the linker.

Along the way this commit removes the `private_no_mangle_functions` lint
(also for statics) as there's no longer any need to lint these
situations. Furthermore a good number of tests were updated now that
symbol visibility has been changed.

Closes #54135

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'd still like to confirm that this fixes the issues with `wasm-bindgen`, but I'd like to put this up for review as well to get others thoughts on it. 

cc @japaric

File: src/tools/compiletest/src/main.rs [hunk 1]
```diff
@@ -809,7 +809,7 @@ fn analyze_gdb(gdb: Option<String>) -> (Option<String>, Option<u32>, bool) {
 
     let gdb_native_rust = version.map_or(false, |v| v >= MIN_GDB_WITH_RUST);
 
-    (Some(gdb.to_owned()), version, gdb_native_rust)
+    (Some(gdb.to_owned()), version, gdb_native_rust && false)
```
Comment (japaric) [inline src/tools/compiletest/src/main.rs]: This looks ... suspicious. Perhaps it was used for local testing?

Comment (alexcrichton) [reply src/tools/compiletest/src/main.rs]: Oops, indeed a mistake!

File: src/test/codegen/export-no-mangle.rs [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![crate_type = "lib"]
+
+mod private {
```
Comment (japaric) [inline src/test/codegen/export-no-mangle.rs]: Could you please add test cases for these patterns?

``` rust
fn internal() {
    #[no_mangle]
    static EXTERNAL: fn() = internal;
}

static FOO: u32 = {
    #[no_mangle]
    static BAR: &u32 = &FOO;
    0
};

const PRIVATE: () = {
    #[no_mangle]
     fn exported() {}
};
```

I can see myself writing attributes / macros that expand into those patterns.

**Comment by japaric** [comment]
I tested this locally with the Cortex-M stuff by making a lot stuff private and linking works perfectly :ok_hand: 

Though, it seems that the `dead_code` lint will need to be updated to accommodate this change; I get several warnings like the ones shown below:

``` rust
fn foo() {} // WARN function is never used

#[no_mangle]
static FOO: fn() = foo; // WARN static item is never used

struct Bar; // WARN struct is never constructed

#[no_mangle]
static BAR: Bar = Bar; // WARN static item is never used

#[no_mangle]
fn baz() {} // WARN function is never used
```

File: src/test/codegen/export-no-mangle.rs (hunk 2 above)
Comment (alexcrichton) [reply src/test/codegen/export-no-mangle.rs]: Certainly!

**Comment by alexcrichton** [comment]
@japaric ah I think I may have actually pushed an update after I noticed the same thing myself, if you try out the current state of the PR I think it should fix that.

**Comment by japaric** [comment]
@alexcrichton I can confirm that I get zero warnings with the latest version. :+1:

**Comment by nagisa** [comment]
I’d like to point out that this is also a breaking change in case anybody depended on `#[no_mangle]`d functions having the same visibility as publicity in any way.

For example, doing something like this should end up raising a linker error after this PR:

```rust
# test.rs
#[no_mangle]
fn foo() -> u32 { // not public!
    42
}
```
```c
# test.c {
int foo(void) { return 64; }

int main() { return foo(); }
```
```sh
# compile with:
rustc --emit=obj --crate-type=staticlib -o test.o
clang -c test.c -o ctest.o
clang ctest.o test.o
# linker error here because of now genuinely duplicate symbols
```

Admittedly, I could not construct a Rust-only case for some reason, but this is still a breaking change nevertheless.

**Comment by japaric** [comment]
@nagisa ~~your example needs `#[used]` to reliably work:~~

``` rust
#![crate_type = "lib"]

#[no_mangle]
fn foo() -> u32 {
    42
}

#[used]
static KEEP: fn() -> u32 = foo;
```

``` console
$ nm -C foo.o
0000000000000000 t foo
0000000000000000 d foo::KEEP
```

~~Without `#[used]` `foo` is not kept in the object even when build without optimizations.~~

~~This is technically a breaking change but since `#[used]` just got stabilized (it's in beta right now) I think that if we can backport this PR into beta then no one *on stable* will experience this breaking change. If we don't backport then someone could write your example in 1.30 and then it would break in 1.31.~~

No, wait. You can make it work without `#[used]` on stable:

``` rust
#![crate_type = "lib"]

#[inline(never)]
#[no_mangle]
fn foo() -> u32 {
    unsafe { std::ptr::read_volatile(&42) }
}

pub fn bar() -> u32 {
    foo()
}
```

``` console
$ rustc +stable --emit=obj -O foo.rs

$ nm -C foo.o
0000000000000000 t foo
0000000000000000 r .Lbyte_str.0
0000000000000000 T foo::bar
```

I can't think of a use case for something like but since this is technically a breaking change we may want do a crater run before landing this.

**Comment by nagisa** [comment]
I doubt crater will uncover any breakage as it is more pertinent to binary crates which could possibly link multiple different versions of some dependency (both potentially containing the same `#[no_mangle]`d private symbol).

**Comment by nagisa** [comment]
@japaric Neither `#[used]` nor retaining the symbol would be necessary in the example with this PR as they would make the symbol exported and globally available.

**Comment by retep998** [comment]
I'd be interested in whether there even *are* any crates that legitimately have private `#[no_mangle]` symbols. It seems like an absolutely useless thing that nobody could ever possibly want, and could only be done by mistake..

**Comment by petrochenkov** [comment]
Since there's still way to reset the linkage to internal with `#[linkage]` if necessary, then I assume it's ok to switch the default for `#[no_mangle]` items.

**Comment by alexcrichton** [comment]
@craterbot run start=master#e7b5ba8661aa844a06c37f22d7af0afb1807d347 end=try#90cdb0b2660ed428dec2f4a3f9bf083fdc2247e5 mode=build-and-test

File: src/librustc/middle/reachable.rs [hunk 3]
```diff
@@ -352,7 +352,7 @@ impl<'a, 'tcx: 'a> ItemLikeVisitor<'tcx> for CollectPrivateImplItemsVisitor<'a,
         // which are currently akin to allocator symbols.
         let def_id = self.tcx.hir.local_def_id(item.id);
         let codegen_attrs = self.tcx.codegen_fn_attrs(def_id);
-        if codegen_attrs.linkage.is_some() ||
+        if codegen_attrs.contains_extern_indicator() ||
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply src/librustc/middle/reachable.rs]: Note that `#[linkage]` is an unstable attribute and has always been sort of wonky with how everything else in the compiler has evolved over time. This is just preserving the original behavior currently. 

TBH the `#[linkage]` attribute is basically buggy enough to not be worth using any more, it needs a larger overhaul than changing the behavior at this location to be usable.

(for example there's no way to control visibility, and it's also not well defined whether the attribute makes it reachable).

Would you be ok leaving these sorts of questions to a later PR?

File: src/libstd/panicking.rs [hunk 4]
```diff
@@ -518,7 +518,7 @@ pub fn update_count_then_panic(msg: Box<dyn Any + Send>) -> ! {
 
 /// A private no-mangle function on which to slap yer breakpoints.
 #[no_mangle]
-#[allow(private_no_mangle_fns)] // yes we get it, but we like breakpoints
+#[cfg_attr(stage0, allow(private_no_mangle_fns))]
 pub fn rust_panic(mut msg: &mut dyn BoxMeUp) -> ! {
```
[the remark this answers is not in the document]
Comment (alexcrichton) [reply src/libstd/panicking.rs]: Yeah the `#[no_mangle]` here is sort of opportunistically trying to keep `rust_panic` as a symbol in the crate, but the new changes in this PR exported it a bit too aggressively, I've tweaked this although it will likely continue to not work too reliably.

File: src/librustc/middle/reachable.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply src/librustc/middle/reachable.rs]: Ok.

**Comment by retep998** [comment]
A crater runs seems like it's not super useful in this case, because all this is doing is causing more symbols to be exported. We'd probably be better off just searching for every mention of `allow(private_no_mangle_statics)` and analyzing what exactly that crate is doing to cause it to need that.

File: src/librustc/hir/mod.rs [hunk 5]
```diff
@@ -2369,9 +2369,15 @@ impl CodegenFnAttrs {
...
+    /// True if it looks like this symbol needs to be exported, for example:
+    ///
+    /// * `#[no_mangle]` is present
+    /// * `#[export_name(...)]` is present
+    /// * `#[linkage]` is present
     pub fn contains_extern_indicator(&self) -> bool {
-        self.flags.contains(CodegenFnAttrFlags::NO_MANGLE) || self.export_name.is_some()
+        self.flags.contains(CodegenFnAttrFlags::NO_MANGLE) ||
+            self.export_name.is_some() ||
+            self.linkage.is_some()
```
Comment (michaelwoerister) [inline src/librustc/hir/mod.rs]: This should probably check if `linkage` is `private` or `internal` which are explicitly not exporting.

Comment (alexcrichton) [reply src/librustc/hir/mod.rs]: Sure yeah I can update it, but FWIW `#[linkage]` is likely basically not at all working for those sorts of linkages, and in general `#[linkage]` is likely buggier in more ways than this...

Comment (michaelwoerister) [reply src/librustc/hir/mod.rs]: Yeah, I know. Partitioning doesn't support it well either for example (https://github.com/rust-lang/rust/issues/53929). Still, I guess as long as we don't have a proper plan on how to fix it, we shouldn't introduce additional problems.

**Comment by michaelwoerister** [comment]
I can't tell if those linker errors are legitimate or not. The code being compiled doesn't seem to involve `#[no_mangle]` at all as far as I can tell.

**Comment by alexcrichton** [comment]
I talking with @pietroalbini it sounds like it's somewhat common to get killed for a lack of memory and disk, so I think the linker errors from the crater report are likely spurious errors

File: src/test/ui/lint/suggestions.rs [hunk 6]
```diff
@@ -14,8 +14,6 @@
 #![feature(no_debug)]
 
 #[no_mangle] static SHENZHOU: usize = 1;
-//~^ WARN static is marked #[no_mangle]
-//~| HELP try making it public
```
Comment (michaelwoerister) [inline src/test/ui/lint/suggestions.rs]: Are these statics referenced somewhere? If not, we should remove them from the test altogether, I think.

**Review by michaelwoerister — APPROVED** [review]
@alexcrichton, looks good to me. r=me if @japaric considers his concerns addressed.

**Comment by retep998** [comment]
I don't think @japaric 's use case even works because I just tested it on pc-windows-msvc and well...
```Rust
#![crate_type = "rlib"]
#[allow(private_no_mangle_statics)]
#[no_mangle]
static FOO: i32 = 1;
pub fn foo() -> usize { &FOO as *const _ as usize }
```
```Rust
#![crate_type = "rlib"]
#[allow(private_no_mangle_statics)]
#[no_mangle]
static FOO: i32 = 2;
pub fn foo() -> usize { &FOO as *const _ as usize }
```
```Rust
extern crate a;
extern crate b;
fn main() {
    println!("a: {}", a::foo());
    println!("b: {}", b::foo());
}
```
Gives this output:
```
a: 140696882361268
b: 140696882361264
```

Interestingly if I change them to both be zero sized types, then they do end up with the same address **even if they are given different names** and still without any link time error. Either way, when symbols are duplicated across *libraries* they do **not** cause linker errors. Only duplicate symbols across *object files* can cause linker errors. Also relying on ZST statics to have unique addresses is clearly flawed.

**Comment by japaric** [comment]
@retep007

Hmm, maybe it changed sometime between now and last year+? I recall it used to give *compile* errors, like the one shown below, across crates:

``` rust
#[no_mangle]
static FOO: () = ();

fn main() {
    #[no_mangle]
    static FOO: () = (); //~ ERROR symbol `FOO` is already defined

    println!("Hello, world!");
}
```

But if that doesn't work anymore we can switch to `links` in Cargo.toml or move the `no_mangle` to another `static` that's actually used in the implementation of the API. (The latter would produce a linker error, which is less nice, instead of a compiler error)

> Also relying on ZST statics to have unique addresses is clearly flawed.

Off-topic: Perhaps I wasn't clear but the `no_mangle` static is not used at all by the API implementation. It's just there to raise compile errors (which doesn't seem to work anymore). The singleton pattern actually looks like this:

``` rust
#[no_mangle] // only used to cause a compile error
static FOO: () = ();

// Proxy for memory mapped peripheral register block
pub struct Zst { _0: () }

impl std::ops::Deref for Zst { // omitted: DerefMut impl
    type Target = u32; // simplified; this should be a struct
    fn deref(&self) -> &u32 {
        const ADDRESS: usize = 0x4000_0000; // peripherals are located at known addresses
        unsafe { &*(ADDRESS as *const u32) }
    }
}

pub fn peripheral_once() -> Option<Zst> {
    // omitted the logic that makes this produce a `Some` value the first time
    // it's called and `None` in subsequent calls
    Some(Zst { _0: () })
}
```

@michaelwoerister 

> if @japaric considers his concerns addressed.

I don't have any concern with this PR. Errors caused by denying a lint are not much of a problem because Cargo uses cap-lints when compiling dependencies so the warnings don't turn into errors. I was mainly commenting on the use of the `#[allow(private_no_mangle_statics)]` since @retep007 asked about it.

**Comment by retep007** [comment]
@retep998 Something for you 🙂 I'm starting to think that I should change my nickname 😀

**Comment by alexcrichton** [comment]
@bors: r=michaelwoerister

I've removed `stylo_tests` from cargotest as it's no longer in the Servo repository (removed in https://github.com/servo/servo/pull/20819)
