### PR TITLE
Accommodate yield points in the format_args expansion

### LINKED ISSUE #93274: Regression in async generator and fmt internals: loss of `Send`
> If an `.await` occurs inside a formatting macro, the resulting generator is no longer `Send`.

## Context

This has already tripped up some people which seem to get quite confused with this error message, so I'd rather we not regress here:

  - https://users.rust-lang.org/t/future-created-by-async-block-is-not-send/70796/3?u=yandros

### Code

I tried this code:

```rust
async fn foo() {
    println!("{} {:?}", "", async {}.await);
}

const _ASSERT_SEND: fn() = || {
    let _: &dyn Send = &foo();
};
```

I expected to see this happen: Code compiles fine: the type of `foo()` is `Send`.

Instead, this happened: The type of `foo()` is not send, since the backing state-machine generator produced for it now captures part of the `fmt` internals involving a `&` reference to the `extern { type Opaque; }`, which is not `Sync`.

### Version it worked on

It most recently worked on: **beta**

### Version with regression

`rustc --version --verbose`:
```
nightly-2022-01-23 84322efad553c7a79c80
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #93274.

For the case `println!("{} {:?}", "", async {}.await)` in the issue, the expansion before:

```rust
::std::io::_print(
    ::core::fmt::Arguments::new_v1(
        &["", " ", "\n"],
        &[
            ::core::fmt::ArgumentV1::new(&"", ::core::fmt::Display::fmt),
            ::core::fmt::ArgumentV1::new(&async {}.await, ::core::fmt::Debug::fmt),
        ],
    ),
);
```

After:

```rust
::std::io::_print(
    ::core::fmt::Arguments::new_v1(
        &["", " ", "\n"],
        &match (&"", &async {}.await) {
            _args => [
                ::core::fmt::ArgumentV1::new(_args.0, ::core::fmt::Display::fmt),
                ::core::fmt::ArgumentV1::new(_args.1, ::core::fmt::Debug::fmt),
            ],
        },
    ),
);
```

### CODE REVIEW

**Comment by dtolnay** [comment]
```console
tidy error: following path contains more than 2310 entries, you should move the test to some relevant subdirectory (current: 2311): /checkout/src/test/ui/issues
```

Opened #93465 to fix.

**Comment by cjgillot** [comment]
The test should probably go in `src/test/ui/fmt`. The `issues` subdirectory is deprecated.

File: compiler/rustc_builtin_macros/src/format.rs [hunk 1]
```diff
@@ -1216,3 +1231,33 @@ pub fn expand_preparsed_format_args(
...
+
+        fn visit_attribute(&mut self, _: &ast::Attribute) {
+            // Conservatively assume this may be a proc macro attribute in
+            // expression position.
+            self.0 = true;
+        }
+
+        fn visit_item(&mut self, _: &ast::Item) {
+            // Do not recurse into nested items.
+        }
```
Comment (danielhenrymantilla) [inline compiler/rustc_builtin_macros/src/format.rs:1257]: Should there be a case to handle `MacroCallStmt`s? I imagine those could feature yield points as well

File: src/test/ui/fmt/format-with-yield-point.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    };
+}
+
+async fn with_await() {
+    println!("{} {:?}", "", async {}.await);
+}
+
+async fn with_macro_call() {
+    println!("{} {:?}", "", m!());
+}
```
Comment (danielhenrymantilla) [inline src/test/ui/fmt/format-with-yield-point.rs:16]: Let's test with a macro call statement as well:

```suggestion
async fn with_macro_call() {
    println!("{} {:?}", "", m!());
}

async fn with_macro_call_stmt() {
    println!("{} {:?}", "", { m!(); });
}
```

or something along those lines

File: src/test/ui/fmt/format-with-yield-point.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+fn assert_send(_: impl Send) {}
+
+fn main() {
+    assert_send(with_await());
+    assert_send(with_macro_call());
+}
```
Comment (danielhenrymantilla) [inline src/test/ui/fmt/format-with-yield-point.rs:23]:
```suggestion
    assert_send(with_macro_call());
    assert_send(with_macro_call_stmt());
}
```

**Review by danielhenrymantilla — APPROVED** [review]

**Review by danielhenrymantilla — APPROVED** [review]

**Comment by dtolnay** [comment]
- Rebased on #93384 to pick up the fix for the compiletest crashes

File: compiler/rustc_builtin_macros/src/format.rs (hunk 1 above)
Comment (dtolnay) [reply compiler/rustc_builtin_macros/src/format.rs:1259]: Done.

File: src/test/ui/fmt/format-with-yield-point.rs (hunk 2 above)
Comment (dtolnay) [reply src/test/ui/fmt/format-with-yield-point.rs]: Added, and also `{ m!{} }`.

**Review by davidtwco — APPROVED** [review]
