### PR TITLE
RFC-2229: Implement Precise Capture Analysis

### LINKED ISSUE #6: After typechk use closure_captures
Since `upvars_mentioned` might not be same as paths that are captured, once type check is done, we know the list of captured path and we should be using that instead.

- [ ] librustc_middle/mir
- [ ] librustc_mir
- [ ] librustc_mir_build
- [ ] librustc_passes/liveness.rs

### LINKED ISSUE #7: Use hir::Place in closure_captures
Ensure that field/member are marked borrowed/moved instead of variable hir_id.

This would look something like https://github.com/rust-lang/project-rfc-2229/blob/master/closure_captures.md

### LINKED ISSUE #9: Ensure minimal places are captured
If we need to capture `a.b.c` and `a.b`, then we only capture `a.b`

With/After #7

### LINKED ISSUE #19: Improve logging of capture analysis
Discussion happened here: 

Capture analysis happens in two passes:
1. Collecting information about each place, i.e. the CaptureKind (ByValue/ByRef) and the expression that led to such capture.
2. Minimum capture analysis, where we find the set of the smallest set of Places (and associated CatureKind) that need to be captured to meet the same requirements as collected by 1.

If we take an example
```rust
let s: String;  // hir_id_s
let mut p: Point; // his_id_p  
let c = || {
       println!("{}, s");  // L1
       p.x += 10;  // L2
       println!("{}" , p.y) // L3
       println!("{}, p) // L4
       drop(s);   // L5
};
```

After 1. the structure we will have is:

```
{
      Place(base: hir_id_s, projections: [], ....) -> (L5, ByValue),
      Place(base: hir_id_p, projections: [Field(0, 0)], ...) -> (L2, ByRef(MutBorrow))
      Place(base: hir_id_p, projections: [Field(1, 0)], ...) -> (L3, ByRef(ImmutBorrow))
      Place(base: hir_id_p, projections: [], ...) -> (L4, ByRef(ImmutBorrow))
```

After 2
```
{
      hir_id_s -> [
           Place(base: hir_id_s, projections: [], ....) -> (L4, ByValue)
      ],
      hir_id_p -> [
           Place(base: hir_id_p, projections: [], ...) -> (L2, ByRef(MutBorrow)),
       ]
```

The structures in reality look a bit more complex. We want to print them out to stderr in a nicer fashion.

What should the output look like
---
The Place can be printed as `<variable_name>[<projecitons>]`, where `projections` is a comma-separated list of pretty printed projection kinds.

```
Deref -> Deref
Field(u32, VariantIndex) -> (x.y); where x corresponds to u32, y corresponds to VariantIndex
Index -> Index
Subsclice -> Subsclice
```

For each capture, we want to throw an error at the expression that resulted in the capture along with the Place and the CaptureKind.

```rust
let s: String;
let mut p: Point;
let c = || {
       println!("{}, s");
       p.x += 10;
       // ^ ERROR: Capturing p[(0.0)] -> MutBorrow
       println!("{}" , p.y);
       // ^ ERROR: Capturing p[(1.0)] -> ImmBorrow
       println!("{}", p);
       // ^ ERROR: Capturing p[] -> ImmBorrow
       drop(s);
       // ^ ERROR: Capturing s[] -> ByValue
};
```

When this gets extended to min capture

```rust
let c = || {
       println!("{}, s");
       p.x += 10;
       // ^ ERROR: Capturing p[(0.0)] -> MutBorrow
       // ^ ERROR: MinCapture p[] -> MutBorrow
       println!("{}" , p.y);
       // ^ ERROR: Capturing p[(1.0)] -> ImmBorrow
       println!("{}", p);
       // ^ ERROR: Capturing p[] -> ImmBorrow
       drop(s);
       // ^ ERROR: Capturing s[] -> ByValue
       // ^ ERROR: MinCapture s[] -> ByValue
};
```

### PR DESCRIPTION
**Pull request by arora-aman**
### This PR introduces
- Feature gate for RFC-2229 (incomplete) `capture_disjoint_field`
- Rustc Attribute to print out the capture analysis `rustc_capture_analysis`
- Precise capture analysis

### Description of the analysis
1. If the feature gate is not set then all variables that are not local to the closure will be added to the list of captures. (This is for backcompat)
2. The rest of the analysis is based entirely on how the captured `Place`s are used within the closure. Precise information (i.e. projections) about the `Place` is maintained throughout.
3. To reduce the amount of information we need to keep track of, we do a minimization step. In this step, we determine a list such that no Place within this list represents an ancestor path to another entry in the list.  Check rust-lang/project-rfc-2229#9 for more detailed examples.
4. To keep the compiler functional as before we implement a Bridge between the results of this new analysis to existing data structures used for closure captures. Note the new capture analysis results are only part of MaybeTypeckTables that is the information is only available during typeck-ing.  

### Known issues
- Statements like `let _ = x` will make the compiler ICE when used within a closure with the feature enabled. More generally speaking the issue is caused by `let` statements that create no bindings and are init'ed using a Place expression.

### Testing
We removed the code that would handle the case where the feature gate is not set, to enable the feature as default and did a bors try and perf run. More information here: #78762 

### Thanks
This has been slowly in the works for a while now.
I want to call out @Azhng @ChrisPardy @null-sleep @jenniferwills @logmosier @roxelo for working on this and the previous PRs that led up to this, @nikomatsakis for guiding us.

Closes rust-lang/project-rfc-2229#7
Closes rust-lang/project-rfc-2229#9
Closes rust-lang/project-rfc-2229#6
Closes rust-lang/project-rfc-2229#19

r? @nikomatsakis

### CODE REVIEW

**Comment by arora-aman** [comment]
cc #76005. This PR implements part of the solution needed. Once writeback is done (rust-lang/project-rfc-2229#18) is done, results, the issue can be closed.

**Comment by mark-i-m** [comment]
Wow so exciting! Thank you @arora-aman (and Niko and @blitzerr and I'm sure many others I'm missing)!

**Review by nikomatsakis — COMMENTED** [review]
didn't make it all the way through yet :) will read more later, but here are some comments.

**Review by arora-aman — COMMENTED** [review]
Rebased and address the comments. 

I couldn't seem to reply directly to your comments for some reason.

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 1]
```diff
@@ -541,10 +866,174 @@ impl<'a, 'tcx> euv::Delegate<'tcx> for InferBorrowKind<'a, 'tcx> {
...
+/// // ^ E1 ^
+///     // ...
+///     // More code
+///     // ...
+///     p.x += 10; // E2
+/// // ^ E2 ^
+/// }
+/// ```
+/// `CaptureKind` associated with both `E1` and `E2` will be ByRef(MutBorrow),
+/// and both have an expression associated, however for diagnostics we prfer reporting
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/upvar.rs:941]:
```suggestion
/// and both have an expression associated, however for diagnostics we prefer reporting
```

File: compiler/rustc_typeck/src/expr_use_visitor.rs [hunk 2]
```diff
@@ -569,50 +570,78 @@ impl<'a, 'tcx> ExprUseVisitor<'a, 'tcx> {
...
+            _ => false,
+        };
+
+        if let Some(min_captures) = self.mc.typeck_results.closure_min_captures.get(&closure_def_id)
+        {
+            for (var_hir_id, min_list) in min_captures.iter() {
+                if upvars.map_or(body_owner_is_closure, |upvars| !upvars.contains_key(var_hir_id)) {
+                    // The nested closure might be capturing the current (enclosing) closure's local variables.
+                    // We check if the root variable is ever mentioned within the enclosing closure, if not
+                    // then for the current body (if it's a closure) these aren't captures, we will ignore them.
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/expr_use_visitor.rs:609]: We don't have logic like this before -- what changed? I'm not sure I quite understand the example.

Comment (nikomatsakis) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:609]: I guess overall I'm confused about the role of `body_owner_is_closure`... can you clarify a bit?

File: src/test/ui/closures/2229_closure_analysis/arrays-completely-captured.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+// Ensure that capture analysis results in arrays being completely captured.
+fn main() {
+    let mut m = [1, 2, 3, 4, 5];
+
+    let mut c = #[rustc_capture_analysis]
+    //~^ ERROR: attributes on expressions are experimental
+    || {
+        m[0] += 10;
+        //~^ ERROR: Capturing m[] -> MutBorrow
+        //~^^ ERROR: Min Capture m[] -> MutBorrow
```
Comment (nikomatsakis) [inline src/test/ui/closures/2229_closure_analysis/arrays-completely-captured.rs:14]:
```suggestion
        //~| ERROR: Min Capture m[] -> MutBorrow
```
you can use this notation too

File: src/test/ui/closures/2229_closure_analysis/capture-disjoint-field-struct.rs [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+fn main() {
+    let mut p = Point { x: 10, y: 10 };
+
+    let c = #[rustc_capture_analysis]
+    //~^ ERROR: attributes on expressions are experimental
+    || {
+        println!("{}", p.x);
+        //~^ ERROR: Capturing p[(0, 0)] -> ImmBorrow
+        //~^^ ERROR: Min Capture p[(0, 0)] -> ImmBorrow
```
Comment (nikomatsakis) [inline src/test/ui/closures/2229_closure_analysis/capture-disjoint-field-struct.rs:20]:
```suggestion
        //~| ERROR: Min Capture p[(0, 0)] -> ImmBorrow
```

File: src/test/ui/closures/2229_closure_analysis/nested-closure.rs [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+
+fn main() {
+    let mut p = Point { x: 5, y: 20 };
+
+    let mut c1 = #[rustc_capture_analysis]
+        //~^ ERROR: attributes on expressions are experimental
+    || {
+        println!("{}", p.x);
+        //~^ ERROR: Capturing p[(0, 0)] -> ImmBorrow
+        //~^^ ERROR: Min Capture p[(0, 0)] -> ImmBorrow
```
Comment (nikomatsakis) [inline src/test/ui/closures/2229_closure_analysis/nested-closure.rs:26]: Doesn't this outer closure have to capture `p[(1, 0)]`, so that it can be given to the inner closure when that inner closure is created?

File: src/test/ui/closures/2229_closure_analysis/nested-closure.rs [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+        //~^ ERROR: attributes on expressions are experimental
+        || p.y += incr;
+        //~^ ERROR: Capturing p[(1, 0)] -> MutBorrow
+        //~^^ ERROR: Capturing incr[] -> ImmBorrow
+        //~^^^ ERROR: Min Capture p[(1, 0)] -> MutBorrow
+        //~^^^^ ERROR: Min Capture incr[] -> ImmBorrow
+        //~^^^^^ ERROR: Capturing p[(1, 0)] -> MutBorrow
+        //~^^^^^^ ERROR: Min Capture p[(1, 0)] -> MutBorrow
+        c2();
+        println!("{}", p.y);
```
Comment (nikomatsakis) [inline src/test/ui/closures/2229_closure_analysis/nested-closure.rs:38]: not to mention, I guess, the direct use of `p.y` here?

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 2 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:609]: Previously we had two structures, `closure_captures` and `upvar_capture_map`. We would read what is captured from the first and check the capture kind in the latter. `ExprUseVisitor` only affects `upvar_capture_map` so it didn't matter if it contains extra entries since the extra entries (captures of the nested closure that are local variables of the enclosing) aren't listed as captures they aren't read.

We have now aggregated the two maps in one, so we need to be more careful.

`ExprUseVisitor` is also used by clippy so want to still report captures to it.

File: src/test/ui/closures/2229_closure_analysis/nested-closure.rs (hunk 5 above)
Comment (arora-aman) [reply src/test/ui/closures/2229_closure_analysis/nested-closure.rs:26]: The enclosing closure captures that, we capture it via MutBorrow which happens in the nested closure. (See the double error thrown for `p[1, 0]` thrown within `c2`.

File: src/test/ui/closures/2229_closure_analysis/nested-closure.rs (hunk 6 above)
Comment (arora-aman) [reply src/test/ui/closures/2229_closure_analysis/nested-closure.rs:38]: This is an ImmBorrow. The nested closure uses it via MutBorrow, so we escalate to that. (Since the outer closure must capture `p.y` with at least the same CaptureKind as the nested closure).

File: compiler/rustc_typeck/src/expr_use_visitor.rs [hunk 7]
```diff
@@ -569,50 +570,78 @@ impl<'a, 'tcx> ExprUseVisitor<'a, 'tcx> {
...
+                    continue;
+                }
+                for captured_place in min_list {
+                    let place = &captured_place.place;
+                    let capture_info = captured_place.info;
+
+                    let upvar_id = if body_owner_is_closure {
+                        // Mark the place to be captured by the enclosing closure
+                        ty::UpvarId::new(*var_hir_id, self.body_owner)
```
Comment (arora-aman) [inline compiler/rustc_typeck/src/expr_use_visitor.rs:618]: If the main body which contains this closure (whose captures we are currently processing) is a Closure itself then we want to reflect that in the `UpvarId` that the closure capturing the Place now is the enclosing closure. 

We had similar logic before where we would fake create a place using `cat_captured_var` which is now removed (diff at the bottom of this file or if this [link works](https://github.com/rust-lang/rust/pull/78801/files#diff-7e389c2ca4db213dcaee698d12a364e7e39f77179a0da1c6578e1ffc9187a9e2L605-L615)). Just one thing to note about that is that it calls into `mc` which is being from the perspective of the body owner here and already has the `body_owner` def id. It gets passed to `mc` in [ExprUseVisitor::new](https://github.com/rust-lang/rust/pull/78801/files#diff-7e389c2ca4db213dcaee698d12a364e7e39f77179a0da1c6578e1ffc9187a9e2R112). We just now keep a copy of that variable in expr_use_visitor.

**Comment by arora-aman** [comment]
@nikomatsakis updated :)

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 7 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:618]: This is also critical to do because `upvar_capture_map` is indexed with UpvarId which essentially contains `(var_hir_id, closure_local_def_id)`, so want to ensure that the variable is captured with respect to the enclosing closure.

In the case where the body (that contains this closure) being processed isn't a closure, we don't update because we will be setting the closure_def_id within UpvarId to a non-closure id.

**Comment by arora-aman** [comment]
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

Added a test for enums in closures with the rebase.

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 8]
```diff
@@ -250,6 +255,289 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            base: PlaceBase::Upvar(upvar_id),
+            projections: Default::default(),
+        }
+    }
+
+    fn should_log_capture_analysis(&self, closure_def_id: DefId) -> bool {
+        self.tcx.has_attr(closure_def_id, sym::rustc_capture_analysis)
+    }
+
+    fn log_closure_capture_info(
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/upvar.rs:502]: so this is logging *every capture*...

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 9]
```diff
@@ -250,6 +255,289 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                let capture_str = construct_capture_info_string(self.tcx, place, capture_info);
+                let output_str = format!("Capturing {}", capture_str);
+
+                let span = capture_info.expr_id.map_or(closure_span, |e| self.tcx.hir().span(e));
+                self.tcx.sess.span_err(span, &output_str);
+            }
+        }
+    }
+
+    fn log_closure_min_capture_info(&self, closure_def_id: DefId, closure_span: Span) {
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/upvar.rs:519]: ....and this is logging the *minimum captures* ...?

File: compiler/rustc_typeck/src/check/upvar.rs [hunk 10]
```diff
@@ -250,6 +255,289 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        capture_information: &FxIndexMap<Place<'tcx>, ty::CaptureInfo<'tcx>>,
+        closure_span: Span,
+    ) {
+        if self.should_log_capture_analysis(closure_def_id) {
+            for (place, capture_info) in capture_information {
+                let capture_str = construct_capture_info_string(self.tcx, place, capture_info);
+                let output_str = format!("Capturing {}", capture_str);
+
+                let span = capture_info.expr_id.map_or(closure_span, |e| self.tcx.hir().span(e));
+                self.tcx.sess.span_err(span, &output_str);
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/check/upvar.rs:514]: One thought I have for how to make this clearer is to add a "note" that indicates which closure this is captured *by*. Something like:

```rust
let mut diag = self.tcx.sess.struct_span_err(span, &output);
diag.span_note(closure_span, "captured by this closure");
diag.emit();
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
OK, I think I understand the tests now. This is looking great! I left one nit.

File: compiler/rustc_typeck/src/check/upvar.rs (hunk 8 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/check/upvar.rs]: Renamed the function to clear intent better

**Review by nikomatsakis — APPROVED** [review]

**Comment by arora-aman** [comment]
@bors rollup=never

This has a slight chance of causing perf regression. So marking rollup never to make it easier to bisect the regression or bugs in general.

We discussed to do so yesterday during 2229 sync.

**Comment by lqd** [comment]
Some of the blessed tests seem to cause the failure

**Comment by arora-aman** [comment]
Clippy tests are failing. I didn't bless them and they shouldn't be blessed. This is an actual error. Part of the problem is explained [here](https://github.com/rust-lang/rust/pull/78801#discussion_r523391348). The fix there didn't resolve the issue when I tried locally so I need to investigate more to get a complete picture.

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 7 above)
Comment (lqd) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:618]: I don't think `bors try` runs any tests tbh, and it can succeed even if the PR can't build the some of the tools, for example. You can _make it_ run tests but that's more involved and t-infra could explain: IIRC you have to add a temporary commit in your PR to modify the CI toml files, turning the try builder into a test running builder, then try that and remove the commit before landing

Comment (lqd) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:618]: I should also mention that usually the tools' tests don't cause the PR to fail, it just changes the "toolstate" (in this case, clippy would have gone from "test pass" to "test fail", some other tools could regress as well), and the failing tool's team can then fix that (with the PR's author help). _This time_ we're in the week to cut the new beta, and no PR regressing the tools can land during this period. If you can't fix the clippy tests, this PR can still land next week: https://forge.rust-lang.org/index.html#no-tools-breakage-week

File: compiler/rustc_middle/src/ty/mod.rs [hunk 11]
```diff
@@ -756,6 +763,56 @@ pub struct UpvarBorrow<'tcx> {
...
+#[derive(PartialEq, Clone, Debug, Copy, TyEncodable, TyDecodable, HashStable)]
+pub struct CaptureInfo<'tcx> {
+    /// Expr Id pointing to use that resulted in selecting the current capture kind
+    ///
+    /// If the user doesn't enable feature `capture_disjoint_fields` (RFC 2229) then, it is
+    /// possible that we don't see the use of a particular place resulting in expr_id being
+    /// None. In such case we fallback on uvpars_mentioned for span.
+    ///
+    /// Eg:
+    /// ```rust
```
Comment (bjorn3) [inline compiler/rustc_middle/src/ty/mod.rs:800]:
```suggestion
    /// ```rust,ignore
```

Otherwise this is a doctest that will be run.

File: compiler/rustc_typeck/src/expr_use_visitor.rs [hunk 12]
```diff
@@ -569,50 +570,78 @@ impl<'a, 'tcx> ExprUseVisitor<'a, 'tcx> {
...
-    fn walk_captures(&mut self, closure_expr: &hir::Expr<'_>, fn_decl_span: Span) {
+    /// Handle the case where the current body contains a closure.
+    ///
+    /// When the current body being handled is a closure, then we must make sure that
+    /// - The parent closure only captures Places from the nested closure that are not local to it.
+    ///
+    /// In the following example the closures `c` only captures `p.x`` even though `incr`
+    /// is a capture of the nested closure
+    ///
+    /// ```rust
```
Comment (bjorn3) [inline compiler/rustc_typeck/src/expr_use_visitor.rs:581]:
```suggestion
    /// ```rust,ignore
```

**Comment by arora-aman** [comment]
> Clippy tests are failing. I didn't bless them and they shouldn't be blessed. This is an actual error. Part of the problem is explained [in the thread above](https://github.com/rust-lang/rust/pull/78801#discussion_r523391348). The fix there didn't resolve the issue when I tried locally so I need to investigate more to get a complete picture.

The other part of the problem is that Clippy uses ExprUseVisitor after Typeck writeback. Since we don't writeback `closure_min_captures` just yet, we don't see any captures for the closures when Clippy walks captures for closures.

For example for `white_let_on_iterator::issue3670` (one of the failing tests)

```
   7   │   unvars_mentioned=Some(
   8   │     {
   9   │         HirId {
  10   │             owner: DefId(0:3 ~ while_let_on_iterator[317d]::issue3670),
  11   │             local_id: 2,
  12   │         }: Upvar {
  13   │             span: $DIR/while_let_on_iterator.rs:14:34: 14:38 (#0),
  14   │         },
  15   │     },
  16   │ ) closure_captures={
  17   │     DefId(0:4 ~ while_let_on_iterator[317d]::issue3670::{closure#0}): {
  18   │         HirId {
  19   │             owner: DefId(0:3 ~ while_let_on_iterator[317d]::issue3670),
  20   │             local_id: 2,
  21   │         }: UpvarId(HirId { owner: DefId(0:3 ~ while_let_on_iterator[317d]::issue3670), local_id: 2 };`ite
       │ r`;DefId(0:4 ~ while_let_on_iterator[317d]::issue3670::{closure#0})),
  22   │     },
  23   │ }
  24   │  min_caps={}
```

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 7 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:651]: Continuing the discussion in t-infra

File: compiler/rustc_middle/src/ty/mod.rs (hunk 11 above)
Comment (arora-aman) [reply compiler/rustc_middle/src/ty/mod.rs]: fixed

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 12 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/expr_use_visitor.rs]: fixed

File: compiler/rustc_typeck/src/expr_use_visitor.rs [hunk 13]
```diff
@@ -570,6 +571,38 @@ impl<'a, 'tcx> ExprUseVisitor<'a, 'tcx> {
         }));
     }
 
+    /// Walk closure captures but using `closure_caputes` instead
+    /// of `closure_min_captures`.
+    ///
+    /// This is needed because clippy uses `ExprUseVisitor` after TypeckResults
+    /// are written back. We don't currently writeback min_captures to
+    /// TypeckResults.
```
Comment (nikomatsakis) [inline compiler/rustc_typeck/src/expr_use_visitor.rs:579]: Can you add a FIXME(project-rfc-2229#18) comment that this should be removed eventually

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_typeck/src/expr_use_visitor.rs (hunk 13 above)
Comment (arora-aman) [reply compiler/rustc_typeck/src/expr_use_visitor.rs:579]: https://github.com/rust-lang/rust/pull/78801/files/c50e57f946ee5a73b50fa5c52bb7a2a8a0cecf3f..bb8c5e5d8b4961a26f88b320f719249a9db8225e#diff-7e389c2ca4db213dcaee698d12a364e7e39f77179a0da1c6578e1ffc9187a9e2R581-R582
