### PR TITLE
Enforce tail call type is related to body return type in borrowck

### LINKED ISSUE #144916: Tail calls don't enforce lifetime constraints from return type onto args
I tried this code:

```rust
#![feature(explicit_tail_calls)]

fn link(x: &str) -> &'static str {
    become passthrough(x);
}

fn passthrough<T>(t: T) -> T { t }

fn main() {
    let x = String::from("hello, world");
    let s = link(&x);
    drop(x);
    println!("{s}");
}
```

I expected to see a borrowck error.

Instead, it compiles which is unsound and causes a segfault.

`rustc --version --verbose`: nightly 2025-08-04

### PR DESCRIPTION
**Pull request by compiler-errors**
Like all call terminators, tail call terminators instantiate the binder of the callee signature with region variables and equate the arg operand types with that signature's args to ensure that the call is valid.

However, unlike normal call terminators, we were forgetting to also relate the return type of the call terminator to anything. In the case of tail call terminators, the correct thing is to relate it to the return type of the caller function (or in other words, the return local `_0`).

This meant that if the caller's return type had some lifetime constraint, then that constraint wouldn't flow through the signature and affect the args. 

This is what's happening in the example test I committed:

```rust
fn link(x: &str) -> &'static str {
    become passthrough(x);
}

fn passthrough<T>(t: T) -> T { t }

fn main() {
    let x = String::from("hello, world");
    let s = link(&x);
    drop(x);
    println!("{s}");
}
```

Specifically, the type `x` is `'?0 str`, where `'?0` is some *universal* arg. The type of `passthrough` is `fn(&'?1 str) -> &'?1 str`. Equating the args sets `'?0 = '?1`. However, we need to also equate the return type `&'?1 str` to `&'static str` so that we eventually require that `'?0 = 'static`, which is a borrowck error!

-----

Look at the first commit for the functional change, and the second commit is just a refactor because we don't need to pass `Option<BasicBlock>` to `check_call_dest`, but just whether or not the terminator is expected to be diverging (i.e. if the return type is `!`).

Fixes rust-lang/rust#144916

### CODE REVIEW

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -845,9 +845,14 @@ impl<'a, 'tcx> Visitor<'tcx> for TypeChecker<'a, 'tcx> {
...
-                if let TerminatorKind::Call { destination, target, .. } = term.kind {
-                    self.check_call_dest(term, &sig, destination, target, term_location);
-                }
+                let (destination, is_diverging) =
+                    if let TerminatorKind::Call { destination, target, .. } = term.kind {
+                        (destination, target.is_none())
+                    } else {
+                        // Tail calls don't actually
+                        (RETURN_PLACE.into(), false)
+                    };
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs]: vibe: can you make this another match on `term.kind`. It'd like to avoid having to manually reason about the `else` being only for tail calls.

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 2]
```diff
@@ -1878,65 +1879,61 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
...
-                    Some(RETURN_PLACE) => {
-                        if let DefiningTy::Const(def_id, _) | DefiningTy::InlineConst(def_id, _) =
-                            self.universal_regions.defining_ty
-                        {
-                            if tcx.is_static(def_id) {
-                                ConstraintCategory::UseAsStatic
-                            } else {
-                                ConstraintCategory::UseAsConst
-                            }
+        if is_diverging {
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/type_check/mod.rs:1883]: I don't really care about the ordering here but the `true` branch seemed easier to put first

File: compiler/rustc_borrowck/src/type_check/mod.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: I might just merge that with the one above
