### PR TITLE
Set branch protection function attributes

### LINKED ISSUE #127829: aarch64-pointer-auth test failing on LLVM 19
Our CI has noticed that llvm/llvm-project@e15d67cfc2e5775cc79281aa860f3ad3be628f39 broke `tests/assembly/aarch64-pointer-auth.rs`:

```
/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/tests/assembly/aarch64-pointer-auth.rs:16:11: error: CHECK: expected string not found in input
  | // CHECK: hint #25
  | ^
  | /var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/assembly/aarch64-pointer-auth/aarch64-pointer-auth.s:1:1: note: scanning from here
  | .text
  | ^
  | /var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/assembly/aarch64-pointer-auth/aarch64-pointer-auth.s:14:18: note: possible intended match here
  | .file "aarch64_pointer_auth.ed114bba7a018068-cgu.0"
  | ^
  |  
  | Input file: /var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/assembly/aarch64-pointer-auth/aarch64-pointer-auth.s
  | Check file: /var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/tests/assembly/aarch64-pointer-auth.rs
```

The only diff in the .s file is this:
```
--- working	2024-07-16 16:26:17.914057368 -0400
+++ broken	2024-07-16 15:35:19.788461411 -0400
@@ -18,11 +18,7 @@
 	.type	test,@function
 test:
 	.cfi_startproc
-	hint	#25
-	.cfi_negate_ra_state
 	mov	w0, #42
-	hint	#29
-	.cfi_negate_ra_state
 	ret
 .Lfunc_end0:
 	.size	test, .Lfunc_end0-test

```

So somehow something is causing the `hint` instructions to get dropped, which is the only thing the test actually looks for. I'm short on time today, but at least wanted to report this semi-promptly. I _may_ look more soon.

### PR DESCRIPTION
**Pull request by nikic**
Since LLVM 19, it is necessary to set not only module flags, but also function attributes for branch protection on aarch64. See https://github.com/llvm/llvm-project/commit/e15d67cfc2e5775cc79281aa860f3ad3be628f39 for the relevant LLVM change.

Fixes https://github.com/rust-lang/rust/issues/127829.

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/attributes.rs [hunk 1]
```diff
@@ -407,8 +407,33 @@ pub fn from_fn_attrs<'ll, 'tcx>(
...
+    } else if llvm_util::get_version() >= (19, 0, 0) {
+        // For non-naked functions, set branch protection attributes on aarch64.
+        if let Some(BranchProtection { bti, pac_ret }) =
+            cx.sess().opts.unstable_opts.branch_protection
+        {
+            assert!(cx.sess().target.arch == "aarch64");
+            if bti {
+                to_add.push(llvm::CreateAttrString(cx.llcx, "branch-target-enforcement"));
+            }
+            if let Some(PacRet { leaf, key }) = pac_ret {
```
Comment (DianQK) [inline compiler/rustc_codegen_llvm/src/attributes.rs:424]: Should we use `let pac_opts = pac_ret.unwrap_or(PacRet { leaf: false, key: PAuthKey::A });`? See https://github.com/rust-lang/rust/blob/a5ee5cbad1dde83dde61959e9436716094e3408c/compiler/rustc_codegen_llvm/src/context.rs#L292.

**Review by dianqk — COMMENTED** [review]
It seems the flags on the module are no longer being used? Can we remove this code?
https://github.com/rust-lang/rust/blob/a5ee5cbad1dde83dde61959e9436716094e3408c/compiler/rustc_codegen_llvm/src/context.rs#L277-L312

**Comment by nikic** [comment]
> It seems the flags on the module are no longer being used? Can we remove this code?

No, the module flags are still needed to emit the ELF attributes.

File: compiler/rustc_codegen_llvm/src/attributes.rs (hunk 1 above)
Comment (nikic) [reply compiler/rustc_codegen_llvm/src/attributes.rs:424]: I don't think so. Note that, while that code makes it look like non-leaf a-key is the default, this is not actually the case, as sign-return-address is still set to false in the None case and the overall functionality is disabled. (I think the reason why it's always setting all module flags is to get correct module flag merging behavior during LTO, but not entirely sure on that.)

Comment (nikic) [reply compiler/rustc_codegen_llvm/src/attributes.rs:424]: For reference, this matches the corresponding clang logic for the function attrs: https://github.com/llvm/llvm-project/blob/5bd3aef5e285cce793e3fc6b21299ac9d650a947/clang/lib/CodeGen/TargetInfo.cpp#L219-L222

**Comment by DianQK** [comment]
> > It seems the flags on the module are no longer being used? Can we remove this code?
> 
> No, the module flags are still needed to emit the ELF attributes (and when creating functions with default attrs).

LGTM. :) Comparing with clang's code, this seems largely consistent. But, clang doesn't always add these attributes:

https://github.com/llvm/llvm-project/blob/a347bdb2b828272359e49a8ce9de9d6412950838/clang/lib/CodeGen/CodeGenModule.cpp#L1195-L1202

(Very complex options, especially under LTO.)

**Comment by cuviper** [comment]
LGTM as well!

@bors r=DianQK,cuviper rollup
