### PR TITLE
Suggest using a temporary variable to fix borrowck errors

### LINKED ISSUE #77834: Add error help to "cannot borrow ... as mutable more than once at a time" error that recommends assigning to a variable first
A newcomer to Rust may have some code that looks like this ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b44d0e3b2a0464c662499b2d6cc2a0e1)):

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    self.foo(self.bar());
  }
}
```

Which you would think would work, since the call to `self.foo()` happens after `self.bar()` returns, and so they have unique access to `self`. However, this desugars into something like this:

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    Self::foo(&mut self, Self::bar(&mut self));
  }
}
```

Which, due to something else in the Rust aliasing rules that can be confusing, means that there are actually two unique borrows of `self` live at the same time, and produces this error:

```
   Compiling playground v0.0.1 (/playground)
error[E0499]: cannot borrow `*self` as mutable more than once at a time
 --> src/lib.rs:7:14
  |
7 |     self.foo(self.bar());
  |     ---- --- ^^^^ second mutable borrow occurs here
  |     |    |
  |     |    first borrow later used by call
  |     first mutable borrow occurs here
```

However, this error is confusing because the error is only visible when the code is desugared. Because of how the code is desugared, this code – which is functionally equivalent – compiles fine ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=733e234866dbee7a1714f561940039d6)):

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    let temp = self.bar();
    self.foo(temp);
  }
}
```

Therefore I propose adding a help message to the error that suggests extracting the result into a temporary. Something like this:

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
 --> src/lib.rs:7:14
  |
7 |     self.foo(self.bar());
  |     ---- --- ^^^^ second mutable borrow occurs here
  |     |    |
  |     |    first borrow later used by call
  |     first mutable borrow occurs here
  |
  = help: try assigning `self.bar()` to a variable and then call `self.foo()` with that variable
```

Cc @jyn514

### PR DESCRIPTION
**Pull request by camelid**
Fixes #77834.

In Rust, nesting method calls with both require `&mut` access to `self`
produces a borrow-check error:

    error[E0499]: cannot borrow `*self` as mutable more than once at a time
     --> src/lib.rs:7:14
      |
    7 |     self.foo(self.bar());
      |     ---------^^^^^^^^^^-
      |     |    |   |
      |     |    |   second mutable borrow occurs here
      |     |    first borrow later used by call
      |     first mutable borrow occurs here

That's because Rust has a left-to-right evaluation order, and the method
receiver is passed first. Thus, the argument to the method cannot then
mutate `self`.

There's an easy solution to this error: just extract a local variable
for the inner argument:

    let tmp = self.bar();
    self.foo(tmp);

However, the error doesn't give any suggestion of how to solve the
problem. As a result, new users may assume that it's impossible to
express their code correctly and get stuck.

This commit adds a (non-structured) suggestion to extract a local
variable for the inner argument to solve the error. The suggestion uses
heuristics that eliminate most false positives, though there are a few
false negatives (cases where the suggestion should be emitted but is
not). Those other cases can be implemented in a future change.

### CODE REVIEW

File: compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -678,6 +678,15 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
             None,
         );
 
+        match explanation {
+            BorrowExplanation::UsedLater(LaterUseKind::Call, _call_span) => {
+                err.help(
+                    "try adding a local storing the argument and then using the local in the call",
+                );
```
Comment (camelid) [inline compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs:685]: It would be nice to have a structured suggestion, but I'm guessing that would be really complicated. Unless it's not as hard as I think to implement a structured suggestion for this, I think let's focus in this PR on emitting the help message only when it makes sense. Then maybe I can do a followup PR if you have ideas for structured suggestions :)

File: src/test/ui/borrowck/borrowck-assign-comp-idx.stderr [hunk 2]
```diff
@@ -21,6 +21,8 @@ LL |         || p[0] = 5);
    |         ^^ - second borrow occurs due to use of `p` in closure
    |         |
    |         mutable borrow occurs here
+   |
+   = help: try adding a local storing the argument and then using the local in the call
```
Comment (camelid) [inline src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: There are many cases like these where the help message is emitted when it doesn't make sense. What heuristics can I use to only emit in the correct situations? (See also my above comment.)

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: Can you categorize the different cases where this is reported wrongly and the cases where it is reported correctly? Maybe we can add another field to BorrowExplanation::UsedLater that carries the information we need

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: These are the categories of false positives I saw where the help was erroneously
emitted, with the more common categories coming first:

- two borrows of the same variable passed to a call (e.g., `foo.method(&mut
  foo)` or `(self.func)(self, arg)`)
- variable passed as argument but variable also mutated in a closure that is
  passed as argument
- closure called with argument that is also mutably borrowed inside the closure

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: These two cases in particular seem tricky to avoid adding the help for:

```
error[E0499]: cannot borrow `*s` as mutable more than once at a time
  --> $DIR/issue-18566.rs:23:19
   |
LL |     MyPtr(s).poke(s);
   |           -  ---- ^ second mutable borrow occurs here
   |           |  |
   |           |  first borrow later used by call
   |           first mutable borrow occurs here
   |
   = help: try adding a local storing the argument and then using the local in the call
```

```
error[E0499]: cannot borrow `thing` as mutable more than once at a time
  --> $DIR/retain-resume-ref.rs:23:25
   |
LL |     gen.as_mut().resume(&mut thing);
   |                         ---------- first mutable borrow occurs here
LL |     gen.as_mut().resume(&mut thing);
   |                  ------ ^^^^^^^^^^ second mutable borrow occurs here
   |                  |
   |                  first borrow later used by call
   |
   = help: try adding a local storing the argument and then using the local in the call
```

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: So... one thing I've noticed going through the examples is that most of the false positives are when the second mutable borrow is an expression that does not contain function calls. So that would be my first step, do not emit the help if there are no function calls.

Additionally the help could get reworded to state that "if the borrows aren't inherently in conflict with each other storing the argument in a local can resolve the situation"

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > So... one thing I've noticed going through the examples is that most of the false positives are when the second mutable borrow is an expression that does not contain function calls. So that would be my first step, do not emit the help if there are no function calls.

How would I go about doing that? Is there some way to get the (T)HIR version of a MIR statement? Or is there some kind of pre-existing MIR analysis I can call? I haven't worked on the borrow-checker before so I'm new to how you do things like this :)

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: It may possibly suffice to check whether the local being borrowed is a temporary. If it is a temporary that means it was created by an expression and isn't a user-defined local. I think that may be enough, even if a "proper" analysis would have to backtrack through the temporaries' assignments to find function calls.

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: Hmm, now the note is not being emitted when it should. I think the issue is that the place being borrowed is `self`, which is obviously not a temporary.

Here's the patch I applied:

```diff
diff --git a/compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs b/compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
index 8d8d8aa6d6e..4bf3ece7628 100644
--- a/compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
+++ b/compiler/rustc_mir/src/borrow_check/diagnostics/conflict_errors.rs
@@ -678,13 +678,13 @@ pub(in crate::borrow_check) fn report_conflicting_borrow(
             None,
         );
 
-        match explanation {
-            BorrowExplanation::UsedLater(LaterUseKind::Call, _call_span) => {
+        if let BorrowExplanation::UsedLater(LaterUseKind::Call, _call_span) = explanation {
+            // Heuristic so this note isn't triggered on user-defined locals.
+            if self.body.local_kind(issued_borrow.borrowed_place.local) == LocalKind::Temp {
                 err.help(
                     "try adding a local storing the argument and then using the local in the call",
                 );
             }
-            _ => {}
         }
 
         err
```

Do you have ideas for other things to try?

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > Hmm, now the note is not being emitted when it should. I think the issue is that the place being borrowed is `self`, which is obviously not a temporary.

I don't understand, do you have an example that worked before that patch but not after it?

Maybe you need to check for `!= LocalKind::Var`, so that `Arg` is included

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: One thing that may be the problem is that a temporary is created for `&mut some_var`, so in that case it is a temporary, but I would have expected that to cause *more* reports, not less.

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > I don't understand, do you have an example that worked before that patch but not after it?

```rust
    struct Foo;

    impl Foo {
        fn foo(&mut self, _: f32) -> i32 { todo!() }
        fn bar(&mut self) -> f32 { todo!() }
        fn baz(&mut self) {
            self.foo(self.bar()); //~ ERROR
        }
    }
```

### Before patch

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
  --> $DIR/suggest-local-var-double-mut.rs:12:22
   |
LL |             self.foo(self.bar());
   |             ---- --- ^^^^ second mutable borrow occurs here
   |             |    |
   |             |    first borrow later used by call
   |             first mutable borrow occurs here
   |
   = help: try adding a local storing the argument and then using the local in the call
```

### After patch

(The note is gone.)

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
  --> $DIR/suggest-local-var-double-mut.rs:12:22
   |
LL |             self.foo(self.bar());
   |             ---- --- ^^^^ second mutable borrow occurs here
   |             |    |
   |             |    first borrow later used by call
   |             first mutable borrow occurs here
```

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: My approach would be to add tracing statements to the code and see what it says about the variable (and also look at the MIR). I don't understand why this doesn't work tho. The result of the bar call should be stored in a temporary variable... oh... we are checking the wrong thing for temporariness xD. You need to check the argument of the outer function call

**Comment by camelid** [comment]
Starting with a rebase so this doesn't get too stale.

File: src/test/ui/borrowck/borrowck-assign-comp-idx.stderr (hunk 2 above)
Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > oh... we are checking the wrong thing for temporariness xD. You need to check the argument of the outer function call

Oh, that explains it! I think we were checking if `self` is a temporary, which of course it should not be.

How do I get the `Place` of the argument for the outer call? I at first thought I would either use `issued_borrow.assigned_place` or look up the terminator belonging to `issued_borrow.reserve_location` (or maybe `activation_location`?), but based on looking at the generated MIR, I don't think that will give me the right answer. Maybe this needs a full-on MIR analysis?

Here's the MIR for the example I gave earlier (https://github.com/rust-lang/rust/pull/83174#r619567264):

```rust
// MIR for `<impl at foo.rs:3:5: 9:6>::baz` 0 mir_map

fn <impl at foo.rs:3:5: 9:6>::baz(_1: &mut Foo) -> () {
    debug self => _1;                    // in scope 0 at foo.rs:6:16: 6:25
    let mut _0: ();                      // return place in scope 0 at foo.rs:6:27: 6:27
    let _2: i32;                         // in scope 0 at foo.rs:7:13: 7:33
    let mut _3: &mut Foo;                // in scope 0 at foo.rs:7:13: 7:17
    let mut _4: f32;                     // in scope 0 at foo.rs:7:22: 7:32
    let mut _5: &mut Foo;                // in scope 0 at foo.rs:7:22: 7:26

    bb0: {
        StorageLive(_2);                 // scope 0 at foo.rs:7:13: 7:33
        StorageLive(_3);                 // scope 0 at foo.rs:7:13: 7:17
        _3 = &mut (*_1);                 // scope 0 at foo.rs:7:13: 7:17
        StorageLive(_4);                 // scope 0 at foo.rs:7:22: 7:32
        StorageLive(_5);                 // scope 0 at foo.rs:7:22: 7:26
        _5 = &mut (*_1);                 // scope 0 at foo.rs:7:22: 7:26
        _4 = Foo::bar(move _5) -> [return: bb1, unwind: bb3]; // scope 0 at foo.rs:7:22: 7:32
                                         // mir::Constant
                                         // + span: foo.rs:7:27: 7:30
                                         // + literal: Const { ty: for<'r> fn(&'r mut Foo) -> f32 {Foo::bar}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        StorageDead(_5);                 // scope 0 at foo.rs:7:31: 7:32
        _2 = Foo::foo(move _3, move _4) -> [return: bb2, unwind: bb3]; // scope 0 at foo.rs:7:13: 7:33
                                         // mir::Constant
                                         // + span: foo.rs:7:18: 7:21
                                         // + literal: Const { ty: for<'r> fn(&'r mut Foo, f32) -> i32 {Foo::foo}, val: Value(Scalar(<ZST>)) }
    }

    bb2: {
        StorageDead(_4);                 // scope 0 at foo.rs:7:32: 7:33
        StorageDead(_3);                 // scope 0 at foo.rs:7:32: 7:33
        StorageDead(_2);                 // scope 0 at foo.rs:7:33: 7:34
        _0 = const ();                   // scope 0 at foo.rs:6:27: 8:10
        return;                          // scope 0 at foo.rs:8:10: 8:10
    }

    bb3 (cleanup): {
        resume;                          // scope 0 at foo.rs:6:9: 8:10
    }
}
```

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: hmm, yea, if _4 does not show up in any of the variables available to you, then you'd need to do something more complicated. I can't really look into this right now though. Probably early July I can dig into it in more depth.

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: @oli-obk Is there a way to look up the statement/terminator where a `Local` is used? I have a potential idea for how we could get this note to be more precise. In the MIR above, I think the borrowck error is reported at this line:

```rust
_5 = &mut (*_1);
```

because `_1` (aka, `self`) is already mutably borrowed. `_5` is then used in `bar` call, and then the result of that call (`_4`) is used in the `foo` call. If we could easily look up the statement where a local is used, then we could theoretically connect all of these statements together to determine that indeed, we should report the note here.

I'm sure this could be done with a new MIR analysis that would be invoked when there was a borrowck error, but it would be nice if we could use the results of a pre-existing analysis. Do you know if those results exist?

Comment (oli-obk) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > Is there a way to look up the statement/terminator where a Local is used?

No, not really. As you already discovered, this needs a new analysis. _1 is being used multiple times, and I'm not sure the that the "previous" use is the right one. Determining what "previous" is is nontrivial if you go across basic blocks. Doing it for just the current block would be as easy as walking backwards in the statement list and visiting the statement to find a specific local. I do know that there is a visitor for finding locals in MIR, so you can re-use that one, but I also don't remember where that visitor is, so you'll have to go through all impls of https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/visit/trait.Visitor.html to find the right one

That said, I believe mir borrowck could track this information, but I wouldn't even know where to start adjusting mir borrowck to know about this and whether it could cause a slowdown.

Comment (camelid) [reply src/test/ui/borrowck/borrowck-assign-comp-idx.stderr:25]: > _1 is being used multiple times, and I'm not sure the that the "previous" use is the right one.

I was actually suggesting that we see where `_5` and `_4` are used; not where `_1` is used. I'm not certain it'll work though :)

> I do know that there is a visitor for finding locals in MIR, so you can re-use that one, but I also don't remember where that visitor is, so you'll have to go through all impls of https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/visit/trait.Visitor.html to find the right one

Sounds good; I'll look for that. Thanks!

**Comment by camelid** [comment]
Status update: I've figured out, and implemented, a way to find the location of
the outer and inner calls.

**Comment by camelid** [comment]
FYI, I just noticed this (pre-existing) test has a typo in it, but it probably shouldn't matter now that MIR borrowck is the default, right?

https://github.com/rust-lang/rust/blob/e6875793dd149345fca224f84d71814a0daa1be7/src/test/ui/borrowck/two-phase-sneaky.rs#L1

**Review by camelid — COMMENTED** [review]
@oli-obk I've made some progress on this. When you get a chance, could you look at the code and the errors? There are a few issues where the wrong span is used, but the false positive rate is much lower 🎉 

I left comments on all the test outputs that have issues. I would appreciate suggestions on how to improve the accuracy :)

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 3]
```diff
@@ -768,9 +772,83 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        &self,
+        err: &mut DiagnosticBuilder<'_>,
+        location: Location,
+        (place, span): (Place<'tcx>, Span),
+        gen_borrow_kind: BorrowKind,
+        issued_borrow: &BorrowData<'tcx>,
+        explanation: BorrowExplanation,
+    ) {
+        let used_in_call =
+            matches!(explanation, BorrowExplanation::UsedLater(LaterUseKind::Call, _call_span, _));
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:798]: We could point at both spans, would that help?

[the remark this answers is not in the document]
Comment (oli-obk) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:798]: Or just at the new span if it isn't in a closure?

File: src/test/ui/borrowck/suggest-local-var-imm-and-mut.stderr [hunk 4]
```diff
@@ -0,0 +1,22 @@
+error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
+  --> $DIR/suggest-local-var-imm-and-mut.rs:12:22
+   |
+LL |             self.foo(self.bar());
+   |             ---------^^^^^^^^^^-
+   |             |    |   |
+   |             |    |   mutable borrow occurs here
+   |             |    immutable borrow later used by call
+   |             immutable borrow occurs here
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/borrowck/suggest-local-var-imm-and-mut.stderr:9]: I don't. I think it's fine to have some missing cases. If you like we can track them in an issue and dig into it in a pair programming session together

File: src/test/ui/borrowck/two-phase-nonrecv-autoref.nll.stderr [hunk 5]
```diff
@@ -6,6 +6,17 @@ LL |         f(f(10));
...
+help: try adding a local storing this argument...
+  --> $DIR/two-phase-nonrecv-autoref.rs:51:11
+   |
+LL |         f(f(10));
+   |           ^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/two-phase-nonrecv-autoref.rs:51:9
+   |
+LL |         f(f(10));
+   |         ^
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/borrowck/two-phase-nonrecv-autoref.nll.stderr:19]: I like it more than the one that goes to the end of the call as spans won't overlap this way

File: src/test/ui/borrowck/two-phase-sneaky.stderr [hunk 6]
```diff
@@ -8,6 +8,17 @@ LL |     v[0].push_str({
...
+help: try adding a local storing this argument...
+  --> $DIR/two-phase-sneaky.rs:12:9
+   |
+LL |         v.push(format!("foo"));
+   |         ^^^^^^^^^^^^^^^^^^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/two-phase-sneaky.rs:10:5
+   |
+LL |     v[0].push_str({
+   |     ^
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/borrowck/two-phase-sneaky.stderr:21]: Ah, fun. Projections don't have spans, this keeps being a problem. Do we know at the time of creating the diagnostic that it's a projection?

File: src/test/ui/coercion/coerce-overloaded-autoderef-fail.stderr [hunk 7]
```diff
@@ -29,6 +29,17 @@ LL |     borrow_mut2(x, x);
...
+help: try adding a local storing this argument...
+  --> $DIR/coerce-overloaded-autoderef-fail.rs:23:5
+   |
+LL |     borrow_mut2(x, x);
+   |     ^^^^^^^^^^^^^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/coerce-overloaded-autoderef-fail.rs:23:5
+   |
+LL |     borrow_mut2(x, x);
+   |     ^^^^^^^^^^^^^^^^^
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/coercion/coerce-overloaded-autoderef-fail.stderr:42]: Really simple approach: if the spans are equal don't emit?

File: src/test/ui/issues/issue-18566.stderr [hunk 8]
```diff
@@ -6,6 +6,17 @@ LL |     MyPtr(s).poke(s);
...
+help: try adding a local storing this argument...
+  --> $DIR/issue-18566.rs:23:5
+   |
+LL |     MyPtr(s).poke(s);
+   |     ^^^^^^^^^^^^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/issue-18566.rs:23:5
+   |
+LL |     MyPtr(s).poke(s);
+   |     ^^^^^^^^
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/issues/issue-18566.stderr:19]: Huh XD maybe don't report it on temporaries?

File: src/test/ui/issues/issue-61623.stderr [hunk 9]
```diff
@@ -15,6 +15,17 @@ LL |     f2(|| x.0, f1(x.1))
...
+help: try adding a local storing this argument...
+  --> $DIR/issue-61623.rs:6:16
+   |
+LL |     f2(|| x.0, f1(x.1))
+   |                ^^^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/issue-61623.rs:6:8
+   |
+LL |     f2(|| x.0, f1(x.1))
+   |        ^^^^^^
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/test/ui/issues/issue-61623.stderr:28]: Ah yes the closure situation. Well, we can query the mirsource to check if we are in a closure borrowing a upvar, but it's a bit annoying to do

File: src/test/ui/borrowck/suggest-local-var-imm-and-mut.stderr (hunk 4 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/borrowck/suggest-local-var-imm-and-mut.stderr:9]: Sounds good; I've opened an issue: #90425

File: src/test/ui/issues/issue-18566.stderr (hunk 8 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/issues/issue-18566.stderr:19]: Hmm, I think the receiver is often a temporary even if it's just `self` because of autoref. So I'm not sure if that would work here.

[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/issues/issue-18566.stderr:19]: I guess I could "solve" this by not reporting the suggestion when the first help span includes the second help span...

File: src/test/ui/coercion/coerce-overloaded-autoderef-fail.stderr (hunk 7 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/coercion/coerce-overloaded-autoderef-fail.stderr:42]: I came up with a more general version of this: if the inner span contains the outer span, don't emit. I think it fixes most of the bad suggestions. The one issue is it prevents the suggestion in some valid cases, but once the spans are fixed for those they should be emitted.

File: src/test/ui/borrowck/two-phase-sneaky.stderr (hunk 6 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/borrowck/two-phase-sneaky.stderr]: I've "solved" this for now by only emitting the suggestion if the outer span strictly contains (i.e., `>`, not `>=`) the inner span.

File: src/test/ui/issues/issue-18566.stderr (hunk 8 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/issues/issue-18566.stderr]: Fixed by https://github.com/rust-lang/rust/pull/83174#discussion_r751460131.

File: src/test/ui/issues/issue-61623.stderr (hunk 9 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/issues/issue-61623.stderr]: Also "fixed" by https://github.com/rust-lang/rust/pull/83174#discussion_r751460131.

File: src/test/ui/borrowck/two-phase-nonrecv-autoref.nll.stderr (hunk 5 above)
[the remark this answers is not in the document]
Comment (camelid) [reply src/test/ui/borrowck/two-phase-nonrecv-autoref.nll.stderr]: This regressed with https://github.com/rust-lang/rust/pull/83174#discussion_r751460131; the suggestion is no longer reported. I think let's just leave it for now.

**Comment by camelid** [comment]
@oli-obk This is ready for review! I think all or almost all the weird spans should be "fixed" now; see https://github.com/rust-lang/rust/pull/83174#discussion_r751460131 and https://github.com/rust-lang/rust/pull/83174#discussion_r751451932.

**Comment by camelid** [comment]
Let me know before you approve so I can squash :)

(And bors auto-squash doesn't work correctly unfortunately.)

**Comment by camelid** [comment]
(CI is failing because I need to cleanup the TODOs once you review.)

**Comment by camelid** [comment]
@oli-obk could you take another look at this? Thanks!

**Comment by oli-obk** [comment]
Sorry... not sure which hole I lost the notifications in.

Yea, so this lgtm now. Both the ui changes and the impl!

**Comment by camelid** [comment]
Ok, I squashed and rebased over master! @oli-obk this should be ready for approval now :D

**Comment by camelid** [comment]
@oli-obk thank you so much for helping me with this PR over the past 9 months! ❤️

**Comment by matthiaskrgr** [comment]
@bors r- rollup-
failed in a rollup:
https://github.com/rust-lang/rust/pull/91756#issuecomment-991310633
Can you please double check that there is no test failure? Thanks!

File: src/test/ui/borrowck/suggest-local-var-imm-and-mut.nll.stderr [hunk 10]
```diff
@@ -0,0 +1,33 @@
...
+help: try adding a local storing this argument...
+  --> $DIR/suggest-local-var-imm-and-mut.rs:12:22
+   |
+LL |             self.foo(self.bar());
+   |                      ^^^^^^^^^^
+help: ...and then using that local as the argument to this call
+  --> $DIR/suggest-local-var-imm-and-mut.rs:12:13
+   |
+LL |             self.foo(self.bar());
+   |             ^^^^^^^^^^^^^^^^^^^^
```
Comment (camelid) [inline src/test/ui/borrowck/suggest-local-var-imm-and-mut.nll.stderr:20]: It's intriguing that the suggestion doesn't show up in normal mode but does (correctly) in nll mode.
