### PR TITLE
include `outer_inclusive_binder` of pattern types

### LINKED ISSUE #237: pattern types escaping bound vars ICE
- tests/ui/type/pattern_types/const_generics.rs
- tests/ui/type/pattern_types/transmute.rs
```rust
//@ check-pass

#![feature(pattern_types, generic_pattern_types, pattern_type_macro)]
#![expect(incomplete_features)]

use std::pat::pattern_type;

trait Foo {}

impl<const START: u32, const END: u32> Foo for pattern_type!(u32 is START..=END) {}
```
```
thread 'rustc' panicked at /home/lcnr/rust/compiler/rustc_type_ir/src/relate/combine.rs:162:5:
assertion failed: !a.has_escaping_bound_vars()
```

### PR DESCRIPTION
**Pull request by jdonszelmann**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/237

r? @lcnr

### CODE REVIEW

File: compiler/rustc_type_ir/src/flags.rs [hunk 1]
```diff
@@ -347,6 +347,7 @@ impl<I: Interner> FlagComputation<I> {
 
     fn add_ty_pat(&mut self, pat: <I as Interner>::Pat) {
         self.add_flags(pat.flags());
+        self.add_exclusive_binder(pat.outer_exclusive_binder());
```
Comment (jdonszelmann) [inline compiler/rustc_type_ir/src/flags.rs:350]: this is the one line that actually fixes the issue. We didn't record the fact that pattern types might have bound variables inside them without this

Comment (jdonszelmann) [reply compiler/rustc_type_ir/src/flags.rs:350]: without it, this:
https://github.com/rust-lang/rust/blob/1e1a39441bd11aba541a48ba714d939490fc7b85/compiler/rustc_middle/src/ty/pattern.rs#L36-L49 

is actually dead code

**Comment by lcnr** [comment]
@bors r+ rollup

there's also an unsoundness due to this change where anonymize bound vars doesn't result in different bound vars, so we get different `TypeId`s, at least in theory

gj gamer
