### PR TITLE
Fix ICE in normalizing inherent associated consts with `#[type_const]`

### LINKED ISSUE #138226: ICE：expected const for `N/#0` (N/#0/0) but found Type(A<N/#0>) when instantiating args=[A<N/#0>]
### Code

```Rust
#![feature(min_generic_const_args)]
#![feature(inherent_associated_types)]
struct A<const N: usize>;
impl<const N: usize> A<N> {
    const FOUR: usize = 4;
    fn test() {
        let _ = [0; Self::FOUR];
    }
}
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0-nightly (f5a1ef712 2025-03-07)
binary: rustc
commit-hash: f5a1ef7121ad661b5a21a1d02941c8064d54ee0b
commit-date: 2025-03-07
host: x86_64-pc-windows-msvc
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b\compiler\rustc_type_ir\src\binder.rs:763:9:
expected const for `N/#0` (N/#0/0) but found Type(A<N/#0>) when instantiating args=[A<N/#0>]
stack backtrace:
   0:     0x7ff835466c63 - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ff835466c63 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff835466c63 - std::sys::backtrace::_print_fmt
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\sys\backtrace.rs:66
   3:     0x7ff835466c63 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\sys\backtrace.rs:39
   4:     0x7ff83549a02a - core::fmt::rt::Argument::fmt
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\core\src\fmt\rt.rs:177
   5:     0x7ff83549a02a - core::fmt::write
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\core\src\fmt\mod.rs:1449
   6:     0x7ff83545c9d7 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\io\mod.rs:1890
   7:     0x7ff835466aa5 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\sys\backtrace.rs:42
   8:     0x7ff83546ae19 - std::panicking::default_hook::closure$0
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\panicking.rs:298
   9:     0x7ff83546ac08 - std::panicking::default_hook
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\panicking.rs:325
  10:     0x7ff8369ff347 - core[a49717954fd349d5]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[c763add0498415dc]::Level, &str), usize), <((rustc_lint_defs[c763add0498415dc]::Level, &str), usize) as core[a49717954fd349d5]::cmp::PartialOrd>::lt>
  11:     0x7ff83546baae - std::panicking::rust_panic_with_hook
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\panicking.rs:839
  12:     0x7ff83546b809 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\panicking.rs:704
  13:     0x7ff83546775f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\sys\backtrace.rs:168
  14:     0x7ff83546b40e - std::panicking::begin_panic_handler
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\panicking.rs:695
  15:     0x7ff8382c8bf1 - core::panicking::panic_fmt
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\core\src\panicking.rs:75
  16:     0x7ff837f85b4a - <rustc_type_ir[589600bd6aed6b9b]::binder::ArgFolder<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::const_param_expected
  17:     0x7ff8352ba80d - <alloc[fd90ba3301162542]::sync::Arc<rustc_query_system[711562fb18ebc613]::dep_graph::serialized::SerializedDepGraph>>::drop_slow
  18:     0x7ff8368fd339 - <rustc_middle[a635f052194163b9]::ty::context::TyCtxt>::mk_bound_variable_kinds
  19:     0x7ff8368fc62a - <rustc_middle[a635f052194163b9]::ty::context::TyCtxt>::mk_bound_variable_kinds
  20:     0x7ff83689b10f - <rustc_middle[a635f052194163b9]::ty::generics::GenericPredicates>::instantiate
  21:     0x7ff83640c80f - rustc_trait_selection[70257543d9e64c63]::traits::wf::clause_obligations
  22:     0x7ff836358614 - <rustc_trait_selection[70257543d9e64c63]::traits::wf::WfPredicates as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_const
  23:     0x7ff8363641c1 - <rustc_trait_selection[70257543d9e64c63]::traits::fulfill::FulfillProcessor as rustc_data_structures[b8e807b0329c5e35]::obligation_forest::ObligationProcessor>::process_obligation
  24:     0x7ff8362c8f8b - <rustc_data_structures[b8e807b0329c5e35]::obligation_forest::ObligationForest<rustc_trait_selection[70257543d9e64c63]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[70257543d9e64c63]::traits::fulfill::FulfillProcessor>
  25:     0x7ff8356e93c1 - rustc_hir_typeck[5dfdb3193f74140]::typeck
  26:     0x7ff835609d47 - <<rustc_hir_typeck[5dfdb3193f74140]::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_ty
  27:     0x7ff835611839 - <<rustc_hir_typeck[5dfdb3193f74140]::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_ty
  28:     0x7ff83566ae0c - <<rustc_hir_typeck[5dfdb3193f74140]::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_ty
  29:     0x7ff83566cbb9 - <<rustc_hir_typeck[5dfdb3193f74140]::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_ty
  30:     0x7ff83560bdfd - <<rustc_hir_typeck[5dfdb3193f74140]::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir[589600bd6aed6b9b]::visit::TypeVisitor<rustc_middle[a635f052194163b9]::ty::context::TyCtxt>>::visit_ty
  31:     0x7ff8356c6a08 - rustc_hir_typeck[5dfdb3193f74140]::typeck
  32:     0x7ff83570cdcd - <rustc_hir_typeck[5dfdb3193f74140]::upvar::InferBorrowKind as rustc_hir_typeck[5dfdb3193f74140]::expr_use_visitor::Delegate>::borrow
  33:     0x7ff8356bfbbf - rustc_hir_typeck[5dfdb3193f74140]::typeck
  34:     0x7ff83620ce7b - rustc_query_impl[b69aee932fe91357]::plumbing::query_key_hash_verify_all
  35:     0x7ff836156051 - RINvNtNtCs9HWllMiJxcJ_18rustc_query_system5query8plumbing17try_execute_queryINtCsfG0cl2i4BMx_16rustc_query_impl13DynamicConfigINtNtCsfSfDFhv6ONJ_21rustc_data_structures9vec_cache8VecCacheNtNtCsc9bkXepKnRD_10rustc_span6def_id10LocalDefIdINtNtNtCsegJBPcicXKD
  36:     0x7ff836215133 - rustc_query_impl[b69aee932fe91357]::plumbing::query_key_hash_verify_all
  37:     0x7ff835733944 - RINvMs6_NtCs86fv54unOYr_9hashbrown3rawINtB6_8RawTablejE14reserve_rehashNCINvNtNtCsfxNsec2025j_8indexmap3map4core8get_hashTNtNtNtCsegJBPcicXKD_12rustc_middle2ty9predicate6ClauseNtNtCsc9bkXepKnRD_10rustc_span13span_encoding4SpanEuE0ECs6deNT1wm63v_18rustc_hir
  38:     0x7ff8357baf71 - rustc_hir_analysis[485f70a961e5d363]::check_crate
  39:     0x7ff8354e346f - rustc_interface[ee21df1734f8ab0f]::passes::resolver_for_lowering_raw
  40:     0x7ff831e48479 - rustc_interface[ee21df1734f8ab0f]::passes::analysis
  41:     0x7ff834fe6baa - <alloc[fd90ba3301162542]::sync::Arc<rustc_session[8146d5d0b944a82b]::config::OutputFilenames>>::drop_slow
  42:     0x7ff834ef46a4 - RINvNtNtCs9HWllMiJxcJ_18rustc_query_system5query8plumbing17try_execute_queryINtCsfG0cl2i4BMx_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsegJBPcicXKD_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  43:     0x7ff834fec6a4 - rustc_query_impl[b69aee932fe91357]::query_system
  44:     0x7ff831e0dcd2 - RINvNtNtCsiw7LomwTgZ5_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCslLIMKTelctO_5alloc5boxed3BoxDINtNtNtCse86O2quqQfh_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsbsz
  45:     0x7ff831e06264 - RINvNtNtCsiw7LomwTgZ5_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCslLIMKTelctO_5alloc5boxed3BoxDINtNtNtCse86O2quqQfh_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsbsz
  46:     0x7ff831dfef03 - RINvNtNtCsiw7LomwTgZ5_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCskrzvsuieKkd_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCsbsz2LbB1MIu_17rustc_driver_i
  47:     0x7ff831e12ed0 - RINvNtNtCsiw7LomwTgZ5_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCslLIMKTelctO_5alloc5boxed3BoxDINtNtNtCse86O2quqQfh_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECsbsz
  48:     0x7ff83547c23d - alloc::boxed::impl$28::call_once
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\alloc\src\boxed.rs:1970
  49:     0x7ff83547c23d - alloc::boxed::impl$28::call_once
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\alloc\src\boxed.rs:1970
  50:     0x7ff83547c23d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/f5a1ef7121ad661b5a21a1d02941c8064d54ee0b/library\std\src\sys\pal\windows\thread.rs:56
  51:     0x7ff8f6c87374 - BaseThreadInitThunk
  52:     0x7ff8f777cc91 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `D:\rust_test\test1\src\rustc-ice-2025-03-08T13_23_09-24280.txt` to your bug report

query stack during panic:
#0 [typeck] type-checking `<impl at .\ttt\test.rs:126:1: 126:26>::test`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #150960: ICE: index out of bounds: the len is 0 but the index is 0
Here is the example code that I found:

```rust
#![allow(incomplete_features)]
#![feature(min_generic_const_args)]
pub struct A;

impl A {
    #[type_const]
    const LEN: usize = 4;

    #[allow(unused_braces)]
    fn arr() -> [u8; const { Self::LEN }] {
        return [0u8; const { Self::LEN }];
    }
}


fn main() {
    let _ = A::arr();
}
```

This bit of code should compile with no issue, but instead panics with:
```
thread 'rustc' (2378376) panicked at compiler/rustc_middle/src/ty/generic_args.rs:54:14:
index out of bounds: the len is 0 but the index is 0
```

I discovered this when working on PR: https://github.com/rust-lang/rust/pull/150799. I did find a fix, but it would have been too localized from what was described to me, and is more related to the fact that that one of the steps for mGCA  https://github.com/rust-lang/rust/issues/132980 is incomplete: 
  > - [ ]  Make inherent associated constants behave correctly
 
I am making this issue as requested by @BoxyUwU  here: https://github.com/rust-lang/rust/pull/150799#discussion_r2676504639

[rustc-ice-2026-01-11T09_57_00-2380279.txt](https://github.com/user-attachments/files/24550457/rustc-ice-2026-01-11T09_57_00-2380279.txt)

@rustbot label +F-associated_const_equality +F-min_generic_const_args +I-ICE +T-compiler

### PR DESCRIPTION
**Pull request by lapla-cogito**
Fixes rust-lang/rust#151027
Fixes rust-lang/rust#138089
Fixes rust-lang/rust#138226
Fixes rust-lang/rust#150960

When an inherent associated const is marked with `#[type_const]`, its generics expect args in the format `[Self, own_params...]`, similar to inherent associated types. However, HIR typeck's `instantiate_value_path` was constructing args in the regular associated const format `[impl_params..., own_params...]`. This mismatch caused ICEs when the `args` were later used in contexts expecting the IAC format, such as user type annotations and `borrowck`'s type ascription.

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/project.rs [hunk 1]
```diff
@@ -586,7 +586,13 @@ pub fn compute_inherent_assoc_term_args<'a, 'b, 'tcx>(
...
     // Infer the generic parameters of the impl by unifying the
     // impl type with the self type of the projection.
-    let mut self_ty = alias_term.self_ty();
+    // For inherent associated consts, the args may not have a Self type at position 0.
+    // In that case, we use the impl_ty directly instead of calling self_ty().
+    let mut self_ty = if alias_term.args.is_empty() || alias_term.args[0].as_type().is_none() {
+        impl_ty
+    } else {
+        alias_term.self_ty()
+    };
```
Comment (fmease) [inline compiler/rustc_trait_selection/src/traits/project.rs]: This is just trying to patch a symptom.

Every inherent assoc ty / const should have a self ty, that's the format, otherwise that's a bug (meaning: we should not attempt to work around it downstream). Worth mentioning, if mGCA+IAT is enabled we seem to construct the `AliasTerm` correctly, so this issue only happens if the necessary features aren't enabled (which is a relief).

So I think the proper solution would be to tweak HIR ty lowering (which I believe to be the culprit) to construct a proper `AliasTerm` "if the features aren't enabled" (even if that means setting self ty to `{type error}` or sth. of that nature). Disclaimer: I've just written down my thoughts without any deeper investigation, so some statements might not be fully correct.

Side note: Your patch likely only addresses the ICE under the current trait solver but not under the next one (`-Znext-solver`) since you're only tackling one tail end, not the root cause, as I've mentioned.

**Review by fmease — CHANGES_REQUESTED** [review]

File: compiler/rustc_trait_selection/src/traits/project.rs (hunk 1 above)
Comment (lapla-cogito) [reply compiler/rustc_trait_selection/src/traits/project.rs]: IIUC, the type system expects `args` with `GenericArgs` to have `args[0]` as `Self` (e.g, [`AliasTerm::self_ty`](https://github.com/rust-lang/rust/blob/f60a0f1bcc5a2a6dd8eb2d2021da79b40f5fbae9/compiler/rustc_type_ir/src/predicate.rs#L677)), but generics do not currently work this way. `args` can be created in two ways: through the type system's `probe_inherent_assoc_item` and through generic definition via `instantiate_value_path`. However, the previously mentioned inconsistency results in `args` being created in a non-conformant format that the type system expects.

I hadn't considered the `next-solver` aspect (so I understand this patch, as is, is at least incomplete), but potential solutions could involve either modifying generics definitions or manually converting `args` at every necessary location and both of which seem unrealistic.

**Comment by BoxyUwU** [comment]
I expect that we'll need to make `instantiate_value_path` for inherent associated type consts yield proper type-system-compatible args (i.e. `[Self, Gat0..N]`), as well as the stuff in that thread about making the trait solvers even handle IACs correctly in the first place. Would definitely be a multi-PR kind of thing and I would probably not start with caring about instantiate_value_path

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 2]
```diff
@@ -1768,14 +1768,25 @@ impl<'a, 'tcx> Visitor<'tcx> for TypeChecker<'a, 'tcx> {
...
                 } else {
-                    self.ascribe_user_type(
-                        constant.const_.ty(),
-                        ty::UserType::new(ty::UserTypeKind::TypeOf(
-                            uv.def,
-                            UserArgs { args: uv.args, user_self_ty: None },
-                        )),
-                        locations.span(self.body),
-                    );
+                    // FIXME: For inherent associated type constants (IACs), we skip
```
Comment (BoxyUwU) [inline compiler/rustc_borrowck/src/type_check/mod.rs]: I think you'll need to update the implementation of `AscribeUserType` typeops to map back from `[SelfTy, Gats1..N]` to `[ImplParams1..N, Gats1..N]` when instantiating the result of calling `type_of` the `DefId`. We do this already in the trait solver so this is normal:tm: and expected:tm: 

You can find the logic for implementing `AscribeUserType` in `type_op_ascribe_user_type_with_span`. And some of the existing places which we do this "map from SelfTy to ImplArgs" thing in the old solver's `compute_inherent_assoc_term_args` or the new solver's `normalize_inherent_associated_term`

tl;dr:
1. create a list of infer vars for arguments to the inherent impl
2. call `type_of` on the *impl* to get its self ty then instantiate it with the infer vars 
3. equate this type with the user written self ty (from `<SelfTy>::INHERENT`). this results inference constraints turning your list of infer vars into an actual list of inferrred types/consts

Comment (lapla-cogito) [reply compiler/rustc_borrowck/src/type_check/mod.rs]: Thanks a lot! Should be fixed in https://github.com/rust-lang/rust/pull/152000/changes/9bda4afad2ccd9685d21f9c3dd698606cecc5a46.

**Comment by BoxyUwU** [comment]
@bors r+ rollup

thanks :3
