### PR TITLE
Handle non-integer const generic parameters in debuginfo type names.

### LINKED ISSUE #86893: ICE generating debuginfo for non-primitive const generics
### Code

```Rust
#![feature(const_generics)]
fn shuffle<const IDX: ()>() {}
pub fn foo() {
    shuffle::<{()}>();
}
```
[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1b9d4f551009ebe3b997df537c512a2f)

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (b3d11f95c 2021-07-04)
binary: rustc
commit-hash: b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b
commit-date: 2021-07-04
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

This ICE is a regression. Bisection implicates https://github.com/rust-lang/rust/pull/85269.

### Error output

```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

error: internal compiler error: /rustc/b3d11f95cc5dd687fdd185ce91e02ebe40e6f46b/compiler/rustc_middle/src/ty/consts.rs:195:32: expected bits of (), got Const {
    ty: (),
    val: Value(
        ByRef {
            alloc: Allocation {
                bytes: [],
                relocations: Relocations(
                    SortedMap {
                        data: [],
                    },
                ),
                init_mask: InitMask {
                    blocks: [],
                    len: Size {
                        raw: 0,
                    },
                },
                align: Align {
                    pow2: 0,
                },
                mutability: Not,
                extra: (),
            },
            offset: Size {
                raw: 0,
            },
        },
    ),
}

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1006:9

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (b3d11f95c 2021-07-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error; 1 warning emitted

error: could not compile `asdf`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_codegen_ssa::debuginfo::type_names::push_generic_params_internal
   8: rustc_codegen_ssa::debuginfo::type_names::push_generic_params
   9: rustc_codegen_llvm::debuginfo::<impl rustc_codegen_ssa::traits::debuginfo::DebugInfoMethods for rustc_codegen_llvm::context::CodegenCx>::dbg_scope_fn::get_template_parameters
  10: rustc_codegen_llvm::debuginfo::<impl rustc_codegen_ssa::traits::debuginfo::DebugInfoMethods for rustc_codegen_llvm::context::CodegenCx>::dbg_scope_fn
  11: rustc_codegen_ssa::mir::codegen_mir
  12: rustc_codegen_ssa::base::codegen_instance
  13: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  14: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  16: rustc_codegen_llvm::base::compile_codegen_unit
  17: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  18: rustc_interface::passes::QueryContext::enter
  19: rustc_interface::queries::Queries::ongoing_codegen
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
  23: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR fixes an ICE introduced by https://github.com/rust-lang/rust/pull/85269 which started emitting const generic arguments for debuginfo names but did not cover the case where such an argument could not be evaluated to a flat string of bits.

The fix implemented in this PR is very basic: If `try_eval_bits()` fails for the constant in question, we fall back to generating a stable hash of the constant and emit that instead. This way we get a (virtually) unique name and side step the problem of generating a string representation of a potentially complex value.

The downside is that the generated name will be rather opaque. E.g. the regression test adds a function `const_generic_fn_non_int<()>` which is then rendered as `const_generic_fn_non_int<{CONST#fe3cfa0214ac55c7}>`. I think it's an open question how to deal with this more gracefully.

I'd be interested in ideas on how to do this better.

r? @wesleywiser 

cc @dpaoliello (do you see any problems with this approach?)
cc @Mark-Simulacrum & @nagisa (who I've seen comment on debuginfo issues recently -- anyone else?)

Fixes https://github.com/rust-lang/rust/issues/86893

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Do you think it makes sense to prefix the hash (e.g., even hx.... instead of 0x....)? That way we avoid it *looking* like an integer argument/const generic, which may be confusing to folks encountering this...

Otherwise I likely don't have much insight into a good way to actually print out more types appropriately -- it seems like we'd either want to find something general (e.g., see if the Ty of the const implements Debug and try to const-eval that -- seems error prone at least until we have const trait impls)... I think it'd be interesting to see what C++ does here, do you know?

**Comment by wesleywiser** [comment]
This seems ok to land to me as a short term way to unblock work on const generics but we should make sure we have a way to encode const generic values in type names before shipping that feature. I think that's being tracked in #61486. 

cc @oli-obk

**Comment by eddyb** [comment]
Funnily enough this is pretty much what I suggested in https://github.com/rust-lang/rust/issues/60705#issuecomment-878379748 - I do agree with @Mark-Simulacrum that they should not look like integers.

One of the thoughts I had was `{UKNOWN#fe3cfa0214ac55c7}` but I'm not sure what the syntax of the debuginfo type names is like and what limitations exist.

File: compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs [hunk 1]
```diff
@@ -480,14 +482,34 @@ fn push_generic_params_internal<'tcx>(
...
                 ty::ConstKind::Param(param) => write!(output, "{}, ", param.name).unwrap(),
-                _ => write!(
-                    output,
-                    "0x{:x}, ",
-                    const_parameter.eval_bits(tcx, ty::ParamEnv::reveal_all(), const_parameter.ty)
-                )
-                .unwrap(),
+                _ => {
+                    let bits_or_hash =
+                        match ct.try_eval_bits(tcx, ty::ParamEnv::reveal_all(), ct.ty) {
```
Comment (oli-obk) [inline compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs:489]: Note that this will convert a lot of things to an integer representation, not just integers. So this will probably return `Some` when your type is actually some wrapper struct or a single element array or sth.

**Comment by dpaoliello** [comment]
Using a name that differentiates it from an integer is a good idea - both to avoid user confusion and prevent collisions.

I'd prefer if we picked a name that somehow indicated that it is a const generic (and not a weirdly named type), maybe `const$fe3cfa0214ac55c7`, `const_generic$fe3cfa0214ac55c7`, or `complex_const$fe3cfa0214ac55c7`?

**Comment by eddyb** [comment]
The hash is of the const *value*, so I wouldn't use "const generic", but sadly `UKNOWN_CONST$fe3cfa0214ac55c7` is a bit long. Maybe I could be fine without "unknown" in there. The uppercase, btw, is because that's how `const` *items* are typically named in Rust, but it's purely an aesthetic choice.

**Comment by JulianKnodt** [comment]
Not sure if I really have a ton of context here, but would it be helpful to also add the type?
i.e. `CONST_<Type>$32BitHash`. For more complex const values, I imagine hashing would always be necessary, but having some indicator of the type of the const would be useful?

File: compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs (hunk 1 above)
Comment (michaelwoerister) [reply compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs:489]: Good to know! Maybe it would be better to emit the hash in those cases.

**Comment by michaelwoerister** [comment]
Thanks for all the feedback!

I like `{CONST#fe3cfa0214ac55c7}` (and `CONST$fe3cfa0214ac55c7` for `cpp_like_names`). I was a bit worried about having something there that doesn't parse as an integer but it turns out that C++ allows all kinds of things as non-type template parameters, so we should be fine. 

>  I think it'd be interesting to see what C++ does here, do you know?

C++ doesn't really seem to allow complex constant values as template argument. It does support pointers and references to such objects. Here's an example: https://godbolt.org/z/718M69TGv. Unfortunately, I wasn't able to get godbolt to print debuginfo but when compiling this locally, I get `Foo<((const Bar&)(& BAR))>` from GCC, `Foo<&BAR>` from both Clang and MSVC.

So GCC does add the type (as @JulianKnodt suggests) while the others don't. Since the length of these names seems to affect performance during later compilation steps, I'd opt for not adding the type.

**Comment by eddyb** [comment]
> For more complex const values, I imagine hashing would always be necessary, but having some indicator of the type of the const would be useful?

Not really, see #61486 - tho my preferred design doesn't seem to be explained as part of the discussion.

I also wish #83234 had more details, but I can try to explain these "(pure) value trees".

We only want to *ever* allow type-level constants (such as those passed to `const` params) to be one of:
1. integer leaves (`iN`, `uN`, and also `bool` and `char`)
  * if we allow raw pointers, they would only be allowed here, with integer addresses
  * maybe `str` and `[u8]` would also go in here for efficiency, unsure yet about that
2. ADTs of other type-level constants (`struct`, `enum`, tuples, arrays, slices, etc.)
  * no C `union`s, since we can't guarantee we can describe them as pure values
  * any user-defined ADTs have to have be "structurally matchable" (i.e. auto-derived `PartialEq`+`Eq`)
  * arguably this includes `&T` too - even if they are normally thought of as indirection, at the type-level `&value` acts as a newtype of `value`, as `&T` has structural equality that makes it isomorphic to `T`

(cc @oli-obk - did I miss anything?)

We already have the leaves, what's lacking in the mangling is the second part (the ADTs) - it's not that much design space, since e.g. `enum` variants can be treated as just `struct`s (i.e. we encode the path to the variant and pretend it's a `struct` path) - the tricky parts how much *aesthetic* detail we put in, like whether we encode field names, how differently to encode tuple `struct`s (make them like regular `struct`s or like tuples?), whether we add a special case for `str` to avoid encoding it as an array, etc. etc.

**Comment by oli-obk** [comment]
> I also wish #83234 had more details, but I can try to explain these "(pure) value trees".

I'm doing that in https://github.com/rust-lang/rustc-dev-guide/pull/1097, but I should probably at least document the `ValTree` type appropriately

**Comment by michaelwoerister** [comment]
I've update the PR to emit integers and booleans directly and everything else gets emitted as `{CONST#fe3cfa0214ac55c7}` (or `CONST$fe3cfa0214ac55c7` for MSVC). Note that the GDB version on CI does not actually print the names we generate here. Instead it demangles the symbol name which, because it's still using the legacy scheme, does not contain any generic arguments at all. Newer GDB versions do seem to use the names from the `DW_AT_name` field.

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
r=me unless you want to wait on other reviews

**Review by wesleywiser — APPROVED** [review]

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/87116#issuecomment-879449266
@bors r-

**Comment by michaelwoerister** [comment]
Fixed the test case. 

@bors r=oli-obk,wesleywiser rollup=never

**Comment by michaelwoerister** [comment]
Looks like CDB prints the functions in a different order now.
