### PR TITLE
some ConstValue refactoring

### LINKED ISSUE #105536: `slice::from_raw_parts` returns a different address in const context for u8
Possibly as a result of some u8-specific [optimizations](https://github.com/rust-lang/rust/blob/1.65.0/compiler/rustc_const_eval/src/const_eval/eval_queries.rs#L118-L136), a const `&[u8]` returned by `std::slice::from_raw_parts` has a different address than all other uses of the same expression. [Forum discussion](https://users.rust-lang.org/t/slice-from-raw-parts-returns-a-different-address-in-const-context/85692?u=mxk).

I tried this code:

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7f77ed62e9fcbe43fbb396f36a12cf27)

```rust
use std::ptr::NonNull;
use std::slice::from_raw_parts;

const PTR_U8: *const u8 = NonNull::dangling().as_ptr();
const CONST_U8_REF: &[u8] = unsafe { from_raw_parts(PTR_U8, 0) };
const CONST_U8_PTR: *const u8 = unsafe { from_raw_parts(PTR_U8, 0).as_ptr() };
static STATIC_U8_REF: &[u8] = unsafe { from_raw_parts(PTR_U8, 0) };

const PTR_U16: *const u16 = NonNull::dangling().as_ptr();
const CONST_U16_REF: &[u16] = unsafe { from_raw_parts(PTR_U16, 0) };

const fn const_u8_fn() -> &'static [u8] {
    unsafe { from_raw_parts(PTR_U8, 0) }
}

fn main() {
    let ptr_u8 = unsafe { from_raw_parts(PTR_U8, 0) }.as_ptr();
    let ptr_u16 = unsafe { from_raw_parts(PTR_U16, 0) }.as_ptr();

    assert_eq!(ptr_u8, PTR_U8); // OK
    assert_eq!(ptr_u8, CONST_U8_PTR); // OK
    assert_eq!(ptr_u8, const_u8_fn().as_ptr()); // OK
    assert_eq!(ptr_u8, STATIC_U8_REF.as_ptr()); // OK
    assert_eq!(ptr_u16, CONST_U16_REF.as_ptr()); // OK
    assert_eq!(ptr_u8, CONST_U8_REF.as_ptr()); // ERROR
}
```

I expected to see this happen: All assertions should pass.

Instead, this happened:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0x1`,
 right: `0x55f434eaa038`', src/main.rs:25:5
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0x1`,
 right: `0x55c4dc25b038`', src/main.rs:25:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:181:5
   4: playground::main
             at ./[src/main.rs:25](https://play.rust-lang.org/#):5
   5: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
```

</p>
</details>

### PR DESCRIPTION
**Pull request by RalfJung**
In particular, use AllocId instead of Allocation in ConstValue::ByRef. This helps avoid redundant AllocIds when a  `ByRef` constant gets put back into the interpreter.

r? @oli-obk 

Fixes https://github.com/rust-lang/rust/issues/105536

### CODE REVIEW

File: compiler/rustc_middle/src/mir/interpret/value.rs [hunk 1]
```diff
@@ -43,9 +43,13 @@ pub enum ConstValue<'tcx> {
...
-        /// The backing memory of the value, may contain more memory than needed for just the value
-        /// in order to share `ConstAllocation`s between values
-        alloc: ConstAllocation<'tcx>,
+        /// The backing memory of the value. May contain more memory than needed for just the value
+        /// if this points into some other larger ConstValue.
+        ///
+        /// We use an `AllocId` here instead of a `ConstAllocation<'tcx>` to make sure that when a
+        /// raw constant (which is basically just an `AllocId`) is turned into a `ConstValue` and
+        /// back, we can preserve the original `AllocId`.
+        alloc_id: AllocId,
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/value.rs:52]: `Slice` should probably get the same treatment, at least it has the same underlying issue.

**Comment by RalfJung** [comment]
Okay, so doing it just for `ByRef` makes no difference. Now for the full version including slices.

@bors try @rust-timer queue

File: compiler/rustc_middle/src/mir/interpret/value.rs [hunk 2]
```diff
@@ -38,27 +35,38 @@ pub enum ConstValue<'tcx> {
...
-        /// The backing memory of the value, may contain more memory than needed for just the value
-        /// in order to share `ConstAllocation`s between values
-        alloc: ConstAllocation<'tcx>,
+    /// Used only for `&[u8]` and `&str`.
+    ///
+    /// This is worth the optimization since Rust has literals of that type.
+    /// See `Indirect` for why we are using an `AllocId`.
+    /// We allow `None` for empty slices; in that case `start == end` and `start` is the absolute
+    /// address of the slice.
+    Slice { alloc_id: Option<AllocId>, start: usize, end: usize },
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/value.rs:44]: I think we can avoid the `None` case... literals always get an `AllocId`, so this can only happen as the result of `ConstEval`, and then we could use `ConstValue::Indirect` since we already have an allocation that stores the evaluation result. OTOH, with `None` we can guarantee that all `&str`/`&[u8]` are `ConstValue::Slice`; do we rely on that somewhere -- e.g. in pattern matching?

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 3]
```diff
@@ -173,21 +170,11 @@ pub(super) fn op_to_const<'tcx>(
...
-                        0,
-                    ),
-                };
+                let (alloc_id, start) = a.to_pointer(ecx).unwrap().into_parts();
                 let len = b.to_target_usize(ecx).unwrap();
-                let start = start.try_into().unwrap();
+                let start = start.bytes().try_into().unwrap();
                 let len: usize = len.try_into().unwrap();
-                ConstValue::Slice { data, start, end: start + len }
+                ConstValue::Slice { alloc_id, start, end: start + len }
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs:177]: Uh, I just realized that valtree-to-const-value will hit this code path for all wide pointers, e.g. `&[u32]`. That doesn't seem right? Certainly we didn't write the `start`/`len` logic thinking about anything besides `u8`/`str`...

Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:164]: We should probably generalize `ConstValue::Slice` to be used for arbitrary types that have a slice as their unsized tail. That justifies how valtrees are using them in valtree-to-constval conversion.

But that's for a future PR.

Comment (oli-obk) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:164]: I'm still hoping to be able to revive my ConstValue::Slice removal PR

File: compiler/rustc_middle/src/mir/interpret/value.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/value.rs:44]: Ah, but then we'd have a really subtle invariant saying that if the value fed to `op_to_const` is an immediate slice reference then it must point to an actual allocation. Though maybe that's worth it for simplifying literally every consumer of `ConstValue::Slice` to avoid the `Option` here.

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/value.rs:44]: Yea, simpler is probably better

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs:160]: Honestly, with the simplification of op_to_const in this PR, the Slice variant isn't so bad any more. In particular these days it seems to be okay to have slices in `ConstValue::ByRef`, they don't *have to* be in `ConstValue::Slice`, and then it's pretty okay.

**Comment by RalfJung** [comment]
Yeah, so we need to keep the `Slice` optimization. When there are enough literals then having to generate AllocIds for them seems to be too costly.

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/const_eval/eval_queries.rs]: Let's leave fixing the valtree problem to the next PR; this one is ready now.

File: compiler/rustc_codegen_cranelift/src/constant.rs [hunk 4]
```diff
@@ -242,9 +243,9 @@ pub(crate) fn codegen_const_value<'tcx>(
 
 fn pointer_for_allocation<'tcx>(
     fx: &mut FunctionCx<'_, '_, 'tcx>,
-    alloc: ConstAllocation<'tcx>,
+    alloc_id: AllocId,
```
Comment (RalfJung) [inline compiler/rustc_codegen_cranelift/src/constant.rs:246]: @bjorn3 I changed this to take an `AllocId` since otherwise the `ConstValue::Indirect` starts with an AllocId, then looks up the `ConstAllocation` for that, and then `pointer_for_allocation` generates a fresh `AllocId` for that   `ConstAllocation` which seems silly.

File: compiler/rustc_middle/src/mir/pretty.rs [hunk 5]
```diff
@@ -701,14 +701,18 @@ pub fn write_allocations<'tcx>(
...
+                // `u8`/`str` slices, shouldn't contain pointers that we want to print.
+                Either::Right(std::iter::empty())
             }
-            ConstValue::ZeroSized => Either::Left(Either::Right(std::iter::empty())),
-            ConstValue::ByRef { alloc, .. } | ConstValue::Slice { data: alloc, .. } => {
-                Either::Right(alloc_ids_from_alloc(alloc))
+            ConstValue::Indirect { alloc_id, .. } => {
+                // FIXME: we don't actually want to print all of these, since some are printed nicely directly as values inline in MIR.
+                // Really we'd want `pretty_print_const_value` to decide which allocations to print, instead of having a separate visitor.
+                Either::Left(std::iter::once(alloc_id))
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/pretty.rs:715]: This here leads to the changes in mir-opt -- we now print the allocation storing the constant itself as well, not just the allocations it points to.

File: compiler/rustc_const_eval/src/const_eval/eval_queries.rs [hunk 6]
```diff
@@ -112,84 +112,56 @@ pub(super) fn op_to_const<'tcx>(
...
+    let force_as_immediate = match op.layout.abi {
         Abi::Scalar(abi::Scalar::Initialized { .. }) => true,
-        Abi::ScalarPair(..) => match op.layout.ty.kind() {
-            ty::Ref(_, inner, _) => match *inner.kind() {
-                ty::Slice(elem) => elem == ecx.tcx.types.u8,
-                ty::Str => true,
-                _ => false,
-            },
-            _ => false,
-        },
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/eval_queries.rs:131]: This is really the key change, no longer forcing a `ConstValue::Slice` for all references. That means all in-memory `OpTy` will perfectly round-trip through `ConstValue`. This used to fail in pattern matching IIRC, but that's sufficiently abstracted with valtrees now that the problem is gone. The one remaining issue was MIR printing and Clippy wanting to access the contents of an `&str`; that's what the new `try_get_slice_bytes_for_diagnostics` method is for. (Without this we would have a small regression for some clippy lints.)

File: compiler/rustc_codegen_cranelift/src/constant.rs [hunk 7]
```diff
@@ -242,9 +243,9 @@ pub(crate) fn codegen_const_value<'tcx>(
...
 ) -> crate::pointer::Pointer {
-    let alloc_id = fx.tcx.create_memory_alloc(alloc);
+    let alloc = fx.tcx.global_alloc(alloc_id).unwrap_memory();
```
Comment (bjorn3) [inline compiler/rustc_codegen_cranelift/src/constant.rs:248]: Maybe move the `.inner().mutability` here and rename the variable as appropriate? It is only the mutability we care about here, not the allocation itself.

File: compiler/rustc_codegen_cranelift/src/constant.rs (hunk 4 above)
Comment (bjorn3) [reply compiler/rustc_codegen_cranelift/src/constant.rs:246]: Makes sense.

File: compiler/rustc_codegen_cranelift/src/constant.rs (hunk 7 above)
Comment (RalfJung) [reply compiler/rustc_codegen_cranelift/src/constant.rs:248]: That makes a very long chain though, I'd consider the code as-is cleaner. But I can change it if you prefer.

**Comment by RalfJung** [comment]
Nice. :)

**Comment by RalfJung** [comment]
Ah, I was working on a lengthy comment to better explain what happens in `op_to_const`. Pushed that now.

I think I'm finally almost happy with the state of that function. :) it only took like 4 years or so.^^
("almost" due to the issue with valtree slices, I'll tackle that next.)

@bors r=oli-obk
