### PR TITLE
Exhaustively match in variant count instrinsic

### LINKED ISSUE #79137: variant_count intrinsic is evaluated incorrectly in generic code
For example:

```rust
#![feature(variant_count)]

fn a<T>() -> usize {
    let v = [0u8; std::mem::variant_count::<T>()];
    std::mem::size_of_val(&v)
}

fn b() -> usize {
    let v = [0u8; std::mem::variant_count::<Result<(), ()>>()];
    std::mem::size_of_val(&v)
}

fn main() {
    println!("{}", a::<Result<(), ()>>());
    println!("{}", b());
}
```

```console
$ rustc a.rs
warning: cannot use constants which depend on generic parameters in types
 --> a.rs:4:19
  |
4 |     let v = [0u8; std::mem::variant_count::<T>()];
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(const_evaluatable_unchecked)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #76200 <https://github.com/rust-lang/rust/issues/76200>

warning: 1 warning emitted

$ ./a
0
2
```

Similar to #73976, but with a different intrinsic.

### PR DESCRIPTION
**Pull request by wusyong**
Fix #79137

### CODE REVIEW

File: compiler/rustc_mir/src/interpret/intrinsics.rs [hunk 1]
```diff
@@ -75,13 +75,16 @@ crate fn eval_nullary_intrinsic<'tcx>(
...
-        }
+        sym::variant_count => match tp_ty.kind() {
+            ty::Adt(ref adt, _) => ConstValue::from_machine_usize(adt.variants.len() as u64, &tcx),
+            ty::Projection(_)
+            | ty::Opaque(_, _)
+            | ty::Param(_)
+            | ty::Bound(_, _)
+            | ty::Placeholder(_)
+            | ty::Infer(_) => throw_inval!(TooGeneric),
+            _ => ConstValue::from_machine_usize(0u64, &tcx),
```
Comment (lcnr) [inline compiler/rustc_mir/src/interpret/intrinsics.rs:86]: can you exhaustively list all variants here instead of using a wildcard?

So that in case we add change some variants of `TyKind` we don't forget this.

File: src/test/ui/consts/issue-79137-toogeneric.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+// The instrinsic call for variant count should exhaustively match on `tp_ty` and forbid
+// `ty::Projection`, `ty::Opaque`, `ty::Param`, `ty::Bound`, `ty::Placeholder` and `ty::Infer`
+// variant. This test checks that it will fail if it's too generic.
```
Comment (lcnr) [inline src/test/ui/consts/issue-79137-toogeneric.rs:3]: Comments like this can easily get outdated, so it's often better to instead remain fairly implementation agnostic, for example by writing something like

```suggestion
// Test that `variant_count` only gets evaluated once the type is concrete enough.
```
