### PR TITLE
Fix missing unused_variables lint when using a match guard

### LINKED ISSUE #151983: Missing "unused variable" warning when using a match guard
I tried this code:

```rust
fn main() {
    match Some(42) {
        Some(unused) if true => (),
        _ => (),
    }
}
```

I expected to see this happen: the compiler should warn that `unused` is unused.

Instead, this happened: the code compiles without any warnings, unless the `if true` part is removed.

### Meta

`rustc --version --verbose`:
```
rustc 1.93.0 (254b59607 2026-01-19)
binary: rustc
commit-hash: 254b59607d4417e9dffbc307138ae5c86280fe4c
commit-date: 2026-01-19
host: x86_64-unknown-linux-gnu
release: 1.93.0
LLVM version: 21.1.8
```
</p>
</details>

### PR DESCRIPTION
**Pull request by eggyal**
Within a binding pattern match guard, only real reads of a bound local impact its liveness analysis - not the fake read that is injected.

Fixes rust-lang/rust#151983
r? compiler

### CODE REVIEW

File: src/tools/clippy/clippy_lints/src/time_subtraction.rs [hunk 1]
```diff
@@ -85,7 +85,7 @@ impl LateLintPass<'_> for UncheckedTimeSubtraction {
     fn check_expr(&mut self, cx: &LateContext<'_>, expr: &'_ Expr<'_>) {
         let (lhs, rhs) = match expr.kind {
             ExprKind::Binary(op, lhs, rhs) if matches!(op.node, BinOpKind::Sub,) => (lhs, rhs),
-            ExprKind::MethodCall(fn_name, lhs, [rhs], _) if cx.ty_based_def(expr).is_diag_item(cx, sym::sub) => {
+            ExprKind::MethodCall(_, lhs, [rhs], _) if cx.ty_based_def(expr).is_diag_item(cx, sym::sub) => {
```
Comment (nnethercote) [inline src/tools/clippy/clippy_lints/src/time_subtraction.rs:88]: Ha, nice that this finds a real case in clippy.

**Review by nnethercote — APPROVED** [review]

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-02-12/near/573547545). A backport PR will be authored by the release team at the end of the current development cycle. Backport labels handled by them.

@rustbot label +beta-accepted
