### PR TITLE
pretty/mir: const value enums with no variants

### LINKED ISSUE #72181: ICE: index out of bounds: the len is 0 but the index is 0' with --emit mir and mir-opt-level >1
### Code
This miri test code `./src/tools/miri/tests/compile-fail/never_transmute_void.rs`

```Rust
// This should fail even without validation
// compile-flags: -Zmiri-disable-validation

#![feature(never_type)]
#![allow(unused, invalid_value)]

enum Void {}

fn f(v: Void) -> ! {
    match v {} //~ ERROR entering unreachable code
}

fn main() {
    let v: Void = unsafe {
        std::mem::transmute::<(), Void>(())
    };
    f(v); //~ inside `main`
}
```
Causes an ice when compiled with `-Zmir-opt-level=2 --emit mir` (but not with opt-level <2 or missing --emit mir)

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (769d12eec 2020-05-12)
binary: rustc
commit-hash: 769d12eec1d0bc3708841dfc149d3ec98b04bec6
commit-date: 2020-05-12
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', src/librustc_middle/ty/mod.rs:2455:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (769d12eec 2020-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', src/librustc_middle/ty/mod.rs:2455:19
stack backtrace:
   0:     0x7f232747aa64 - backtrace::backtrace::libunwind::trace::h98d3444f0ad70429
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f232747aa64 - backtrace::backtrace::trace_unsynchronized::h371770250c47e40d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f232747aa64 - std::sys_common::backtrace::_print_fmt::hff04dc7e915a3c85
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f232747aa64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h61891c439a79f00d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f23274b896c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7f232746c433 - std::io::Write::write_fmt::h1a1f8616ed2f90f9
                               at src/libstd/io/mod.rs:1537
   6:     0x7f232747fa85 - std::sys_common::backtrace::_print::h78339381acb79e1b
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f232747fa85 - std::sys_common::backtrace::print::h525aa9f9405c80a1
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f232747fa85 - std::panicking::default_hook::{{closure}}::hace90b8a218287e6
                               at src/libstd/panicking.rs:198
   9:     0x7f232747f7d7 - std::panicking::default_hook::h160b6beccc49b335
                               at src/libstd/panicking.rs:218
  10:     0x7f2327a99c23 - rustc_driver::report_ice::h4f38da7fac8ebd4c
  11:     0x7f232748013d - std::panicking::rust_panic_with_hook::h36f6804eea3f553a
                               at src/libstd/panicking.rs:481
  12:     0x7f232747fd1b - rust_begin_unwind
                               at src/libstd/panicking.rs:385
  13:     0x7f23274b5601 - core::panicking::panic_fmt::hd101a87121fa411f
                               at src/libcore/panicking.rs:89
  14:     0x7f23274b55c2 - core::panicking::panic_bounds_check::ha0668dcff6357ef4
                               at src/libcore/panicking.rs:65
  15:     0x7f232a2858b8 - rustc_middle::ty::AdtDef::discriminant_def_for_variant::hb8665f68c3c8925f
  16:     0x7f23290981a4 - rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::discriminant_for_variant::hf8f2b2d0f600757c
  17:     0x7f23290dcc63 - rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::read_discriminant::h04383a786f9e5f5c
  18:     0x7f2328e8ed6b - rustc_mir::const_eval::destructure_const::hea137a6a8b6323b8
  19:     0x7f2328debda4 - core::ops::function::FnOnce::call_once::he49d534148327124
  20:     0x7f2329fb2fb1 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::destructure_const>::compute::hfa7b6d2252302ba6
  21:     0x7f232a060885 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hb3d4c13d744e715a
  22:     0x7f232a3ab702 - rustc_data_structures::stack::ensure_sufficient_stack::hdcee244c83eb407b
  23:     0x7f232a1763a4 - rustc_query_system::query::plumbing::get_query_impl::hef1678ca65220230
  24:     0x7f2329fa1302 - rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_const::h583cec005ac559c3
  25:     0x7f232a0a999f - rustc_middle::mir::pretty_print_const::ha73776b5fc4e1f49
  26:     0x7f23274b896c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
  27:     0x7f23274b9794 - core::fmt::Formatter::write_fmt::h95caeeba181649fe
                               at src/libcore/fmt/mod.rs:1498
  28:     0x7f232a3c2d74 - <&T as core::fmt::Debug>::fmt::hc537246aca244980
  29:     0x7f23274b896c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
  30:     0x7f23274b9794 - core::fmt::Formatter::write_fmt::h95caeeba181649fe
                               at src/libcore/fmt/mod.rs:1498
  31:     0x7f232a0a6f58 - <rustc_middle::mir::Operand as core::fmt::Debug>::fmt::h666dba9a1334652c
  32:     0x7f23274b896c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
  33:     0x7f23274b9794 - core::fmt::Formatter::write_fmt::h95caeeba181649fe
                               at src/libcore/fmt/mod.rs:1498
  34:     0x7f232a0a56b2 - <rustc_middle::mir::TerminatorKind as core::fmt::Debug>::fmt::h3ca5eba4a9e4e295
  35:     0x7f23274b88db - core::fmt::run::h9b3b3bec27be60ec
                               at src/libcore/fmt/mod.rs:1103
  36:     0x7f23274b88db - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1078
  37:     0x7f23274ab812 - core::fmt::Write::write_fmt::h0a4283ca6cdb8567
                               at /rustc/769d12eec1d0bc3708841dfc149d3ec98b04bec6/src/libcore/fmt/mod.rs:193
  38:     0x7f23274ab812 - alloc::fmt::format::h657722b395b07d36
                               at src/liballoc/fmt.rs:586
  39:     0x7f2328f26e46 - rustc_mir::util::pretty::write_mir_pretty::h5f0518bd9dc7a33c
  40:     0x7f232916ad2f - rustc_mir::transform::dump_mir::emit_mir::h3ac1a091dc0e3c6e
  41:     0x7f2327e4fead - rustc_interface::passes::start_codegen::h459335c6dd01052b
  42:     0x7f2327d37b29 - rustc_middle::ty::context::tls::enter_global::h739103a57ae08ef8
  43:     0x7f2327d52806 - rustc_interface::queries::Queries::ongoing_codegen::hfa82dc9d28eff2f3
  44:     0x7f2327a680ff - rustc_interface::interface::run_compiler_in_existing_thread_pool::h9607844d06857db5
  45:     0x7f2327aa77bd - scoped_tls::ScopedKey<T>::set::haf4c7963bcdf05e7
  46:     0x7f2327aa04a4 - rustc_ast::attr::with_globals::h6a7f645f85d913be
  47:     0x7f2327aa8abe - std::sys_common::backtrace::__rust_begin_short_backtrace::hc1d7bb4af8e37486
  48:     0x7f2327bf666e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h274c438c26ba3928
  49:     0x7f23274900aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5b84f52b19042f22
                               at /rustc/769d12eec1d0bc3708841dfc149d3ec98b04bec6/src/liballoc/boxed.rs:1034
  50:     0x7f23274900aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6e1ef057e35f3144
                               at /rustc/769d12eec1d0bc3708841dfc149d3ec98b04bec6/src/liballoc/boxed.rs:1034
  51:     0x7f23274900aa - std::sys::unix::thread::Thread::new::thread_start::h8b0ae441dc3343d4
                               at src/libstd/sys/unix/thread.rs:87
  52:     0x7f23273a446f - start_thread
  53:     0x7f23272c43d3 - clone
  54:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (769d12eec 2020-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2

query stack during panic:
#0 [destructure_const] destructure constant
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #72181.

This PR modifies the pretty printer and const eval in the MIR so that `destructure_const` (used in `pretty_print_const_value`) can handle enums with no variants (or types containing enums with no variants).

I'm not convinced that this is the correct approach, folks more familiar with `destructure_const` would be able to say - happy to adjust the PR. Looking through `destructure_const` and the functions that it invokes, it didn't seem like it was written to handle zero-variant-enums - I assume that case is handled earlier in some way so `destructure_const` doesn't need to under normal circumstances. It didn't seem like it would be straightforward to make `destructure_const` handle this case in a first-class-feeling way (e.g. adding a `Variants::None` variant), so this PR makes some minimal changes to avoid ICEs.

### CODE REVIEW

**Comment by oli-obk** [comment]
> I'm not convinced that this is the correct approach, folks more familiar with `destructure_const` would be able to say - happy to adjust the PR. Looking through `destructure_const` and the functions that it invokes, it didn't seem like it was written to handle zero-variant-enums - I assume that case is handled earlier in some way so `destructure_const` doesn't need to under normal circumstances. It didn't seem like it would be straightforward to make `destructure_const` handle this case in a first-class-feeling way (e.g. adding a `Variants::None` variant), so this PR makes some minimal changes to avoid ICEs.

The changes from indexing to `get`, while correct, have one problem: they don't help us catch actually wrong `VariantIdx`es. There are multiple pre-existing similar situations, and the solution there was (as you also did in one case), to check `def.variants.is_empty()` first, and if that is true, do the empty enum processing and if it's false, do the regular code.

File: src/librustc_middle/ty/layout.rs [hunk 1]
```diff
@@ -2001,7 +2001,8 @@ where
                 }
 
                 let fields = match this.ty.kind {
-                    ty::Adt(def, _) => def.variants[variant_index].fields.len(),
+                    ty::Adt(def, _) =>
```
Comment (oli-obk) [inline src/librustc_middle/ty/layout.rs:2004]: this was actually reachable?

File: src/librustc_middle/ty/mod.rs [hunk 2]
```diff
@@ -2342,18 +2342,22 @@ impl<'tcx> AdtDef {
         let mut explicit_index = variant_index.as_u32();
```
Comment (oli-obk) [inline src/librustc_middle/ty/mod.rs:2342]: Same here, calling this function on a zero variant enum is a bug, you can just `assert!(!self.variants.is_empty());` at the start of the function to make that explicit.

File: src/test/ui/issues/issue-72181-1.rs [hunk 3]
```diff
@@ -0,0 +1,20 @@
+// build-pass
+// compile-flags: --emit=mir -Z mir-opt-level=1
```
Comment (oli-obk) [inline src/test/ui/issues/issue-72181-1.rs:2]: Please make this test a `mir-opt` test and emit the MIR of `main` and `f`

File: src/test/ui/issues/issue-72181.rs [hunk 4]
```diff
@@ -0,0 +1,24 @@
+// build-pass
+// compile-flags: --emit=mir -Z mir-opt-level=1
```
Comment (oli-obk) [inline src/test/ui/issues/issue-72181.rs:2]: Same here, change to a mir-opt test

File: src/librustc_middle/ty/layout.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_middle/ty/layout.rs]: I've updated `destructure_const` so that it doesn't invoke `operand_downcast` (and my extension, this function), so I've removed this change and left a assert.

File: src/librustc_middle/ty/mod.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_middle/ty/mod.rs:2343]: I've changed this to an assert as requested, but I've modified one of the calling functions to check that the variant is within range and return `None`.

File: src/test/ui/issues/issue-72181-1.rs (hunk 3 above)
Comment (davidtwco) [reply src/test/ui/issues/issue-72181-1.rs]: Fixed!

File: src/test/ui/issues/issue-72181.rs (hunk 4 above)
Comment (davidtwco) [reply src/test/ui/issues/issue-72181.rs]: Fixed!

**Comment by davidtwco** [comment]
I'm not able to reproduce this locally after rebasing on master, any ideas @oli-obk?

File: src/librustc_middle/ty/sty.rs [hunk 5]
```diff
@@ -2093,7 +2093,9 @@ impl<'tcx> TyS<'tcx> {
         variant_index: VariantIdx,
     ) -> Option<Discr<'tcx>> {
         match self.kind {
-            TyKind::Adt(adt, _) if adt.is_enum() => {
+            TyKind::Adt(adt, _)
+                if adt.is_enum() && adt.variant_range().contains(&variant_index) =>
```
Comment (oli-obk) [inline src/librustc_middle/ty/sty.rs:2097]: For `adt.variants.is_empty()` this function should also just bug out.

File: src/librustc_mir/const_eval/mod.rs [hunk 6]
```diff
@@ -43,6 +45,12 @@ pub(crate) fn destructure_const<'tcx>(
 
     let variant = ecx.read_discriminant(op).unwrap().1;
 
+    if let ty::Adt(def, _) = val.ty.kind {
+        if def.variants.is_empty() {
```
Comment (oli-obk) [inline src/librustc_mir/const_eval/mod.rs:49]: You could merge this into the match below. Imo it's ok to have an arm that does an early return when all the others yield a value.

File: src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir [hunk 7]
```diff
@@ -0,0 +1,385 @@
+// MIR for `main` 0 mir_map
+
+| User Type Annotations
+| 0: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }], value: TypeOf(DefId(2:6169 ~ core[2a38]::fmt[0]::{{impl}}[2]::new_v1[0]), UserSubsts { substs: [ReLateBound(DebruijnIndex(0), BrAnon(0))], user_self_ty: Some(UserSelfTy { impl_def_id: DefId(2:6167 ~ core[2a38]::fmt[0]::{{impl}}[2]), self_ty: std::fmt::Arguments<'_> }) }) } at $SRC_DIR/libstd/macros.rs:LL:COL
```
Comment (oli-obk) [inline src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir:4]: So I think the symptom in CI is that this does a debug dump of various pieces of information that do not belong into the mir dump. I don't know why there's a difference between your system and CI, `DefId`s should be deterministic. Maybe it's stage1 vs stage2?

Anyway, I think we should just fix the symptom here, try removing the `println!` to reduce noise. If these `User Type Annotations` are still printed afterwards, maybe just stop printing the MIR for the `main` function entirely.

Please open an issue with your example and the command line and tag it for wg-mir-opt. We should stop debug dumping `DefId`s here.

File: src/librustc_mir/const_eval/mod.rs [hunk 8]
```diff
@@ -43,6 +45,12 @@ pub(crate) fn destructure_const<'tcx>(
 
     let variant = ecx.read_discriminant(op).unwrap().1;
```
Comment (oli-obk) [inline src/librustc_mir/const_eval/mod.rs:46]: you can move this into the `ty::Adt` arm below, then it won't invoke `discriminant_for_variant`

Comment (oli-obk) [reply src/librustc_mir/const_eval/mod.rs:46]: The `operand_downcast` further down can also be moved up into the `ty::Adt` arm.

I guess you'll have to either make the `variant` field become an `Option`, or just yield `VariantIdx::new(0)` from the other arms.

File: src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir (hunk 7 above)
Comment (davidtwco) [reply src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir:4]: I've filed #73501 regarding this.

File: src/librustc_middle/ty/sty.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_middle/ty/sty.rs:2097]: Fixed!

File: src/librustc_mir/const_eval/mod.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustc_mir/const_eval/mod.rs]: Fixed!

File: src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir (hunk 7 above)
Comment (davidtwco) [reply src/test/mir-opt/issue-72181/rustc.main.mir_map.0.mir]: Fixed this by removing the `println!`s in the test.

File: src/librustc_mir/const_eval/mod.rs (hunk 8 above)
Comment (davidtwco) [reply src/librustc_mir/const_eval/mod.rs]: Fixed!

**Comment by oli-obk** [comment]
r=me with CI passing

File: src/librustc_middle/ty/print/pretty.rs [hunk 9]
```diff
@@ -1177,8 +1177,13 @@ pub trait PrettyPrinter<'tcx>:
                         }
                         p!(write(")"));
                     }
+                    ty::Adt(def, substs) if def.variants.is_empty() => {
+                        p!(print_value_path(def.did, substs));
+                    }
```
Comment (eddyb) [inline src/librustc_middle/ty/print/pretty.rs:1182]: I don't think this should ever be reached? This sort of thing should be an evaluation error, surely?

Comment (davidtwco) [reply src/librustc_middle/ty/print/pretty.rs:1182]: I don’t know about an evaluation error, but this definitely gets reached.

Comment (oli-obk) [reply src/librustc_middle/ty/print/pretty.rs:1182]: we use the pretty printer from within the miri engine and the const evaluator does not validate that every local is always valid, only miri does this.
