### PR TITLE
fix OOB pointer formed in Vec::index

### LINKED ISSUE #122760: Undefined Behavior in Vec::insert if passed an index outside of its capacity
I tried this code:

```rust
vec![].insert(usize::MAX, usize::MAX);
```

I expected to see this happen:
The program should panic, but not have any undefined behavior.

Instead, this happened:
Miri reports that the program triggers undefined behavior.

<details><summary>MIRI Backtrace</summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.51s
     Running `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner target/miri/x86_64-unknown-linux-gnu/debug/playground`
error: Undefined Behavior: out-of-bounds pointer arithmetic: alloc1582 has size 32, so pointer to 8 bytes starting at offset -8 is out-of-bounds
    --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1554:25
     |
1554 |                 let p = self.as_mut_ptr().add(index);
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ out-of-bounds pointer arithmetic: alloc1582 has size 32, so pointer to 8 bytes starting at offset -8 is out-of-bounds
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
help: alloc1582 was allocated here:
    --> src/main.rs:2:5
     |
2    |     vec![].insert(usize::MAX, usize::MAX);
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: BACKTRACE (of the first span):
     = note: inside `std::vec::Vec::<usize>::insert` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1554:25: 1554:53
note: inside `main`
    --> src/main.rs:2:5
     |
2    |     vec![].insert(usize::MAX, usize::MAX);
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

</p>
</details>

### Meta

It seems like the issue is here:

https://github.com/rust-lang/rust/blob/a77c20c4b987e74eb1a867d21d1edb8035a11660/library/alloc/src/vec/mod.rs#L1554-L1563

The length check needs to happen before the computation of [ptr::add](https://doc.rust-lang.org/std/primitive.pointer.html#method.add-1), since it's undefined behavior if the new pointer is out of bounds of the allocation or overflows the address space.

`rustc --version --verbose`:

```
rustc 1.79.0-nightly (a7e4de13c 2024-03-19)
```

### PR DESCRIPTION
**Pull request by jwong101**
Move the length check to before using `index` with `ptr::add` to prevent an out of bounds pointer from being formed.

Fixes #122760

### CODE REVIEW

**Comment by workingjubilee** [comment]
what the f
Thanks!

@bors r+ rollup

**Comment by Nilstrieb** [comment]
this is not a recent regression, so not that critical to merge immediately 
@bors r-

Could you add a test for this such that miri-test-libstd can catch this in the future?

**Comment by workingjubilee** [comment]
@Nilstrieb I was actually thinking about opening an issue for that as a followup, as I wasn't sure what we need to do to make sure miri's daily testing triggers, but if adding `#[should_panic]` tests is all we need to do, then we should definitely do that.

**Comment by Nilstrieb** [comment]
That should be all that's needed, yes. I did think about just asking for a follow up but there's always the risk that it will be forgotten, and I thought merging this isn't urgent enough for that. But if you add the tests soon you can approve it.

(also FWIW, Miris daily tests will soon be bors-ly (https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Running.20miri-test-libstd.20in.20merge.20CI))

**Comment by workingjubilee** [comment]
Fair enough! Posted https://github.com/rust-lang/rust/pull/122765

**Comment by jwong101** [comment]
> Could you add a test for this such that miri-test-libstd can catch this in the future?

Yeah, I added two test cases locally in https://github.com/rust-lang/rust/blob/c86f3ac24f6b62b438c4bdc34ae73e8a1db60234/library/alloc/tests/vec.rs that I ran with [miri-test-libstd](https://github.com/rust-lang/miri-test-libstd) to verify if the patch fixed the issue. The reason that I didn't add it in this PR was because I didn't know what the policy was for adding test cases just for MIRI. Should I still add them in this PR or is #122765 enough? The only additional test that's different from #122765 is `Vec::with_capacity(8).insert(9, true);`.

**Comment by Amanieu** [comment]
This is likely to be perf-sensitive since it was originally introduced in smallvec as an [optimization](https://github.com/servo/rust-smallvec/pull/282).

@bors rollup=never

**Comment by jwong101** [comment]
> This is likely to be perf-sensitive since it was originally introduced in smallvec as an https://github.com/servo/rust-smallvec/pull/282.

Looking at the [pr](https://github.com/rust-lang/rust/pull/98755) where this optimization was introduced, it seems the main optimization was avoiding the copy when `index == len`. This change preserves that optimization, however, it now checks for `index > len` before reserving extra space. I can update the PR to unconditionally reserve extra space to preserve those semantics if that has any impact on perf.

Also, could someone with the necessary permissions trigger the perf run for this PR? I don't have permission to do it.

**Comment by cuviper** [comment]
> Also, could someone with the necessary permissions trigger the perf run for this PR? I don't have permission to do it.

Given that it's already approved, it will get an automatic perf run after it merges. If you want to delay that and experiment some more, then we should `r-` and then do perf runs on try builds.

**Comment by jwong101** [comment]
> Given that it's already approved, it will get an automatic perf run after it merges.

Ah my bad. I thought Amanieu's comment meant that it needed a perf run before being approved. If that's the case, then I'll just rely on the automatic perf run.

**Comment by workingjubilee** [comment]
cc @nnethercote Is the optimization introduced in SmallVec sound in SmallVec and not here?

**Comment by workingjubilee** [comment]
Answer: no, it is not. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9b3d536d340a9c4e42e487a4ad3d0cac

**Comment by pnkfelix** [comment]
> Ah my bad. I thought Amanieu's comment meant that it needed a perf run before being approved.

For clarity: No, we don't require a perf run before such a PR is approved. But we do like to see (and what Amanieu did by marking this with `rollup-`) was such PR's to land on their own, rather than being added to a rollup, to make it easier to identify regressions from such "perf risky" PR's when they do pop up.

File: library/alloc/src/vec/mod.rs [hunk 1]
```diff
@@ -1541,6 +1541,9 @@ impl<T, A: Allocator> Vec<T, A> {
         }
 
         let len = self.len();
+        if index > len {
```
Comment (nnethercote) [inline library/alloc/src/vec/mod.rs:1544]: #98755 explains the reasons for the original change, to reduce the number of conditional tests. This PR will increase the number of tests in the common `index < len` case from one to two.

If the `add` is the problem, it could be moved so it's only computed after the `index < len` and `index == len` tests. Something like this:

```rust
        // Space for the new element.
        if len == self.buf.capacity() {
            self.reserve(1);
        }

        unsafe {
            // Do not call `add` until the index is checked, to avoid UB. Also,
            // minimize the number of conditional tests, and avoid a
            // zero-length copy in the `index == len` case. (All this requires
            // the duplicate computation of `p`.)
            if index < len {
                // Shift everything over to make space. (Duplicating the
                // `index`th element into two consecutive places.) Then
                // overwrite the first copy of the `index`th element.
                let p = self.as_mut_ptr().add(index);
                ptr::copy(p, p.add(1), len - index);
                ptr::write(p, element);
            } else if index == len {
                // No elements need shifting. Overwrite the first copy of the
                // `index`th element.
                let p = self.as_mut_ptr().add(index);
                ptr::write(p, element);
            } else {
                assert_failed(index, len);
            }
            self.set_len(len + 1);                                                
        }          
```

Comment (nnethercote) [reply library/alloc/src/vec/mod.rs:1544]: That would also avoid the unnecessary extra block :)

**Comment by workingjubilee** [comment]
@jwong101 If perf comes back lookin' kinda funky on this, can you post a followup? Thanks in advance!

File: library/alloc/src/vec/mod.rs (hunk 1 above)
Comment (jwong101) [reply library/alloc/src/vec/mod.rs:1544]: > This PR will increase the number of tests in the common index < len case from one to two, and reinstate the zero-length copy in the index == len case.

I believe I kept the original change where the `ptr::copy` is only called when `index < len`. I thought that was the main reason for the perf speedup from the original PR, however, I can see the extra check in the common path having an impact on perf.

Should I make a new commit to fold the `index > len` check back to the original comparison now or wait for a perf run?

Comment (jwong101) [reply library/alloc/src/vec/mod.rs:1544]: Also, we might get a small speedup in the sense that we no longer potentially resize the `Vec` if the index is OOB, though obviously  it would be silly to try to optimize that at the expense of the non-panicking in-bounds case.

**Comment by jwong101** [comment]
Yeah, I can make the changes that @nnethercote suggested now, as that shouldn't cause any perf regressions(unless LLVM decides to optimize worse for fun if we don't unconditionally emit a gepi).

**Comment by workingjubilee** [comment]
@jwong101 Best to pursue it in a new PR building atop, as this commit is already queued to merge, and we'll to see both perf runs anyways. It's possible this has stopped being a relevant optimization as-of LLVM 18.
