### PR TITLE
Be more discerning on when to attempt suggesting a comma in a macro invocation

### LINKED ISSUE #58796: Misleading diagnostic for macro `error!` when called with no parameters
When calling the macro with no arguments `error!()`:
```rust
error: Could not compile
warning: build failed, waiting for other jobs to finish...
error: expected identifier, found `,`
  --> mod.rs:37:15
   |
37 |               error!();
   |               ^^^^^^^^^
   |               |
   |               expected identifier
   |               help: remove this comma
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile
```

The diagnostic should instruct the user that a string literal is required as a parameter to the macro.

### PR DESCRIPTION
**Pull request by estebank**
Fix #58796.

### CODE REVIEW

File: src/libsyntax/tokenstream.rs [hunk 1]
```diff
@@ -178,9 +178,11 @@ impl TokenStream {
...
                 if let Some((_, next)) = iter.peek() {
                     let sp = match (&ts, &next) {
-                        ((TokenTree::Token(_, token::Token::Comma), NonJoint), _) |
-                        (_, (TokenTree::Token(_, token::Token::Comma), NonJoint)) => continue,
-                        ((TokenTree::Token(sp, _), NonJoint), _) => *sp,
+                        (_, (TokenTree::Token(_, token::Token::Comma), _)) => continue,
+                        ((TokenTree::Token(sp, token_left), NonJoint),
+                         (TokenTree::Token(_, token_right), _))
+                        if token_left.is_ident() || token_left.is_lit() &&
+                            token_right.is_ident() || token_right.is_lit() => *sp,
```
Comment (petrochenkov) [inline src/libsyntax/tokenstream.rs]: Looks like the logical operator priority is unintended and some parentheses are missing.

Comment (estebank) [reply src/libsyntax/tokenstream.rs]: The logic is "a literal or ident is followed by a literal or ident. I can add parentheses and or comments to make it explicit, but it should be correct as is.

Comment (petrochenkov) [reply src/libsyntax/tokenstream.rs]: >The logic is "a literal or ident is followed by a literal or ident"

That's what I inferred too, but `id1 || lit1 && id2 || lit2` is `id1 || (lit1 && id2) || lit2` rather than `(id1 || lit1) && (id2 || lit2)`.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+ rollup

File: src/libsyntax/tokenstream.rs (hunk 1 above)
Comment (estebank) [reply src/libsyntax/tokenstream.rs]: You're absolutely right. Fixed.
