### PR TITLE
Fix `adt_const_params` leaking `{type error}` in error msg

### LINKED ISSUE #118179: `adt_const_params` feature gate error leaks `{type error}` (`TyKind::Error`)
The following code

```rs
struct G<T, const N: Vec<T>>(T);
fn main() {}
```

currently yields

```
error[E0770]: the type of const parameters must not depend on other generic parameters
 --> src/lib.rs:1:26
  |
1 | struct G<T, const N: Vec<T>>(T);
  |                          ^ the type must not depend on the parameter `T`
  |
  = note: type parameters may not be used in the type of const parameters

error: `Vec<{type error}, {type error}>` is forbidden as the type of a const generic parameter
 --> src/lib.rs:1:22
  |
1 | struct G<T, const N: Vec<T>>(T);
  |                      ^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
  = help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
```

Ideally, we would replace the `{type error}` with `_` or prevent the second error from being be emitted (this can be achieved by bailing out early if the relevant type [`.references_errors()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/visit/trait.TypeVisitableExt.html#method.references_error)).

### PR DESCRIPTION
**Pull request by onkoe**
Fixes the confusing diagnostic described in #118179. (users would see `{type error}` in some situations, which is pretty weird)

Fixes #118179.

`adt_const_params` tracking issue: #95174

### CODE REVIEW

File: compiler/rustc_middle/src/ty/sty.rs [hunk 1]
```diff
@@ -1315,6 +1315,29 @@ impl<'tcx> Ty<'tcx> {
         cf.is_break()
     }
 
+    /// Checks whether a type recursively contains some `TyKind::Error(_)`.
+    ///
+    /// Example: The (erroneous) type `Vec<{type error}, {type error}>` returns
+    /// true.
+    pub fn contains_error(self) -> bool {
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/sty.rs:1322]: How does this differ from [`.references_error()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/trait.TypeVisitableExt.html#method.references_error)? I think this method is unnecessary.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 2]
```diff
@@ -961,13 +961,22 @@ fn check_param_wf(tcx: TyCtxt<'_>, param: &hir::GenericParam<'_>) -> Result<(),
                         hir_ty.span,
                         "using raw pointers as const generic parameters is forbidden",
                     ),
-                    _ => tcx.dcx().struct_span_err(
-                        hir_ty.span,
-                        format!("`{}` is forbidden as the type of a const generic parameter", ty),
-                    ),
+                    _ => {
+                        // Avoid showing a weird error message to the user. See #118179.
+                        if ty.contains_error() {
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:966]: `if ty.references_error()`.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 3]
```diff
@@ -961,13 +961,22 @@ fn check_param_wf(tcx: TyCtxt<'_>, param: &hir::GenericParam<'_>) -> Result<(),
                         hir_ty.span,
                         "using raw pointers as const generic parameters is forbidden",
                     ),
-                    _ => tcx.dcx().struct_span_err(
-                        hir_ty.span,
-                        format!("`{}` is forbidden as the type of a const generic parameter", ty),
-                    ),
+                    _ => {
+                        // Avoid showing a weird error message to the user. See #118179.
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:965]: "weird error message" is perhaps less descriptive than it could be. I'd rather have something like "Avoid showing {type error} to users".

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Please also squash this into one commit.

File: compiler/rustc_middle/src/ty/sty.rs (hunk 1 above)
Comment (onkoe) [reply compiler/rustc_middle/src/ty/sty.rs:1322]: For sanity, let $R$ = `ty.references_error()` and $C$ = `ty.contains_error()`. $R$ checks if `ty` has `TypeFlags::HAS_ERROR`, while $C$ checks each contained type for being a `TyKind::Error`. 

I'm not knowledgeable enough about deeper usage of `TypeFlags` to clarify why, but $C$ seems to result in similar output to `R && ty.to_string().contains("{type error}")`. 

(I think `Ty`'s inner `GlobalCtxt` lets `FlagComputation::for_kind(...)` attribute errors to `ty` during `CtxtInterners::intern_ty(...)`, even if it's not about what `ty` directly contains.)

Anyways, when just using $R$, many tests fail as they're missing expected diagnostics. For example, `tests/ui/const-generics/issues/issue-56445-1.rs` fails with this:

```rust
--- not found errors (from test file) ---
ERROR     line   9: `&str` is forbidden as the type of a const generic parameter
```

It feels like $R$ is (loosely) a superset of $C$. Creating $C$ results in the appropriate output for this check.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 3 above)
Comment (onkoe) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:965]: This is definitely better - thanks!

File: compiler/rustc_middle/src/ty/sty.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/sty.rs:1322]: `tests/ui/const-generics/issues/issue-56445-1.rs` fails because it already has the preexisting error where `&str`'s lifetime is not resolvable, so the type ends up containing errors.

There is no reason to add a new method that is used nowhere else in the compiler -- please just use `references_error` and adjust the tests accordingly.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 3 above)
Comment (onkoe) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:965]: I'll avoid pushing this until I squash, but it now says: `// Avoid showing "{type error}" to users. See #118179.`

File: compiler/rustc_middle/src/ty/sty.rs (hunk 1 above)
Comment (onkoe) [reply compiler/rustc_middle/src/ty/sty.rs:1322]: I understand your concerns with adding new methods, but the diagnostics would plainly be worse with the existing method. 

For example, that test now complains about the lifetime, ignoring the type:

```rust
$ cargo +stage1 check
    Checking issue_118179 v0.1.0 (/home/barrett/Documents/projects/testing/rust_lang_repros/issue_118179)
error[E0770]: the type of const parameters must not depend on other generic parameters
  --> src/main.rs:10:26
   |
10 | struct Bug<'a, const S: &'a str>(PhantomData<&'a ()>);
   |                          ^^ the type must not depend on the parameter `'a`
   |
   = note: lifetime parameters may not be used in the type of const parameters

For more information about this error, try `rustc --explain E0770`.
error: could not compile `issue_118179` (bin "issue_118179") due to 1 previous error
```

A user, in order, would have to remove the lifetime, then fix the next error when it pops up, too. I don't like when that happens to me. :(

Now, compare that to the diagnostics with the new method:

```rust
$ cargo +stage1 check
    Checking issue_118179 v0.1.0 (/home/barrett/Documents/projects/testing/rust_lang_repros/issue_118179)
error[E0770]: the type of const parameters must not depend on other generic parameters
  --> src/main.rs:10:26
   |
10 | struct Bug<'a, const S: &'a str>(PhantomData<&'a ()>);
   |                          ^^ the type must not depend on the parameter `'a`
   |
   = note: lifetime parameters may not be used in the type of const parameters

error: `&str` is forbidden as the type of a const generic parameter
  --> src/main.rs:10:25
   |
10 | struct Bug<'a, const S: &'a str>(PhantomData<&'a ()>);
   |                         ^^^^^^^
   |
   = note: the only supported types are integers, `bool`, and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
   |
8  + #![feature(adt_const_params)]
   |
help: add `#![feature(unsized_const_params)]` to the crate attributes to enable references to implement the `ConstParamTy` trait
   |
8  + #![feature(unsized_const_params)]
   |

For more information about this error, try `rustc --explain E0770`.
error: could not compile `issue_118179` (bin "issue_118179") due to 2 previous errors
```

Nonetheless, if you're comfortable with the loss of clarity, I can remove the new method. Please let me know what you think.

Comment (compiler-errors) [reply compiler/rustc_middle/src/ty/sty.rs:1322]: Yeah, I don't care about fixing it in a single place. This is a more general issue with [`ReError`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/type.RegionKind.html#variant.ReError) that needs a delicate, global refactoring that I'd rather not tangle into this PR.

Comment (onkoe) [reply compiler/rustc_middle/src/ty/sty.rs:1322]: That makes total sense - thank you for the link and explanation! I'll adjust the tests and use your suggestion.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 4]
```diff
@@ -961,13 +961,22 @@ fn check_param_wf(tcx: TyCtxt<'_>, param: &hir::GenericParam<'_>) -> Result<(),
...
                     ),
-                    _ => tcx.dcx().struct_span_err(
-                        hir_ty.span,
-                        format!("`{}` is forbidden as the type of a const generic parameter", ty),
-                    ),
+                    _ => {
+                        // Avoid showing "{type error}" to users. See #118179.
+                        if ty.references_error() {
+                            return Ok(());
+                        }
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:968]: Actually, this should just return `Err(ErrorGuaranteed)` here, rather than `Ok(())`, I think.

You can use the alternative `error_reported` function which is like `references_error`, but returns a `Result<(), ErrorGuaranteed>` for ease of `?` operator:

```suggestion
                        ty.error_reported()?;
```

Comment (onkoe) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:968]: That makes sense! I guess it kinda depends on if we're checking if the parameters are well-formed, or if it's all well-formed... while checking the const parameters. 

Tests don't seem to mind either way, and there are no docs for any of these methods, so I'll go with this. 😄

(by the way, is there any reason behind the lack of docs on most `rustc` modules/items? would well-researched docs be appreciated?)

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 5]
```diff
@@ -961,13 +961,20 @@ fn check_param_wf(tcx: TyCtxt<'_>, param: &hir::GenericParam<'_>) -> Result<(),
...
+                            hir_ty.span,
+                            format!(
+                                "`{ty}` is forbidden as the type of a const generic parameter",
+                            ),
+                        )
+                    }
                 };
 
-                diag.note("the only supported types are integers, `bool` and `char`");
+                diag.note("the only supported types are integers, `bool`, and `char`");
```
Comment (klensy) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:977]: comma before `and` looks wrong to me.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:977]: It's called the oxford comma.

Comment (klensy) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:977]: Hmm, okay, looking at *.stderr there used both cases with and w\o comma with enumerations.

Comment (klensy) [reply compiler/rustc_hir_analysis/src/check/wfcheck.rs:977]: Found only 2 mentions: https://github.com/rust-lang/rustc-dev-guide/pull/1087#discussion_r593821973, https://github.com/rust-lang/rustc-dev-guide/pull/1139#discussion_r650445567; should be added to the guide?
