### PR TITLE
[win][aarch64] Fix linking statics on Arm64EC, take 2

### LINKED ISSUE #138541: Linking error when compiled to `arm64ec-pc-windows-msvc`
On windows compiled to `arm64ec-pc-windows-msvc` target with `-Zbuild-std` got linking error:
```
error: linking with `link.exe` failed: exit code: 1120
  = note:    Creating library D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.lib and object D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.exp␍
          symbols.o : error LNK2001: unresolved external symbol #_RNxC3std12H7JG8fmF3Zv8 (EC Symbol)␍
          D:\a\Img\Img\build-dir\arm64ec-pc-windows-msvc\src\deps\Img.exe : fatal error LNK1120: 1 unresolved externals␍
```
Rust 1.87.0-nightly (ecade534c 2025-03-14)

### PR DESCRIPTION
**Pull request by dpaoliello**
Arm64EC builds recently started to fail due to the linker not finding a symbol:
```
symbols.o : error LNK2001: unresolved external symbol #_ZN3std9panicking11EMPTY_PANIC17hc8d2b903527827f1E (EC Symbol)
          C:\Code\hello-world\target\arm64ec-pc-windows-msvc\debug\deps\hello_world.exe : fatal error LNK1120: 1 unresolved externals
```

It turns out that `EMPTY_PANIC` is a new static variable that was being exported then imported from the standard library, but when exporting LLVM didn't prepend the name with `#` (as only functions are prefixed with this character), whereas Rust was prefixing with `#` when attempting to import it.

The fix is to have Rust not prefix statics with `#` when importing.

Adding tests discovered another issue: we need to correctly mark static exported from dylibs with `DATA`, otherwise MSVC's linker assumes they are functions and complains that there is no exit thunk for them.

Fixes rust-lang/rust#138541

Resurrects rust-lang/rust#140176 now that rust-lang/rust#141061 is merged, which removes the incompatibility with `__rust_no_alloc_shim_is_unstable`.

r? @wesleywiser 

CC @bjorn3

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 1]
```diff
@@ -1769,9 +1801,12 @@ fn for_each_exported_symbols_include_dep<'tcx>(
...
 }
 
-pub(crate) fn exported_symbols(tcx: TyCtxt<'_>, crate_type: CrateType) -> Vec<String> {
+pub(crate) fn exported_symbols(
+    tcx: TyCtxt<'_>,
+    crate_type: CrateType,
+) -> Vec<(String, SymbolExportKind)> {
     if let Some(ref exports) = tcx.sess.target.override_export_symbols {
-        return exports.iter().map(ToString::to_string).collect();
+        return exports.iter().map(|name| (name.to_string(), SymbolExportKind::Text)).collect();
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/linker.rs]: I removed the SymbolExportKind for exported_symbols change from my PR, but I believe your review comment https://github.com/rust-lang/rust/pull/142568#discussion_r2150403133 applies here too. This was the fixme I came up with: https://github.com/rust-lang/rust/commit/fc88eae9c346e99f311fd920760c7a6077853369

```rust
// FIXME use the correct export kind for this symbol. override_export_symbols
// can't directly specify the SymbolExportKind as it is defined in rustc_middle
// which rustc_target can't depend on.
```

**Comment by bjorn3** [comment]
@bors2 try jobs=x86_64-msvc-*,x86_64-mingw-*,dist-aarch64-msvc

File: tests/run-make/arm64ec-import-export-static/export.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+#[lang = "sized"]
+pub trait Sized: MetaSized {}
+#[lang = "sync"]
+trait Sync {}
+impl Sync for i32 {}
+#[lang = "copy"]
+pub trait Copy {}
+impl Copy for i32 {}
+#[lang = "drop_in_place"]
+pub unsafe fn drop_in_place<T: ?Sized>(_: *mut T) {}
```
Comment (bjorn3) [inline tests/run-make/arm64ec-import-export-static/export.rs:21]: Can this test use mini_core? Or does that not work for run-make tests?

**Comment by bjorn3** [comment]
@bors2 try jobs=`x86_64-msvc-*,x86_64-mingw-*,dist-aarch64-msvc`

Edit: Seems to be https://github.com/rust-lang/bors/issues/314

**Comment by jieyouxu** [comment]
You'll need to use the try-job-in-PR-description form

**Comment by bjorn3** [comment]
@bors2 try

File: compiler/rustc_codegen_ssa/src/back/symbol_export.rs [hunk 3]
```diff
@@ -755,7 +758,7 @@ pub(crate) fn extend_exported_symbols<'tcx>(
     let undecorated = symbol_name_for_instance_in_crate(tcx, symbol, instantiating_crate);
 
     // Add the symbol for the kernel descriptor (with .kd suffix)
-    symbols.push(format!("{undecorated}.kd"));
+    symbols.push((format!("{undecorated}.kd"), info.kind));
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/symbol_export.rs]: This should be `SymbolExportKind::Data`. According to https://llvm.org/docs/AMDGPUUsage.html#symbols, this symbol will be `STT_OBJECT` rather than `STT_FUNC`. It is some (non-executable) metadata for the function.

File: tests/run-make/arm64ec-import-export-static/export.rs (hunk 2 above)
Comment (dpaoliello) [reply tests/run-make/arm64ec-import-export-static/export.rs:21]: I have no idea: I've only seen `mini_core` used in the compiler tests. The tests in `run-make` use this pattern of manually declaring whatever they need.

File: compiler/rustc_codegen_ssa/src/back/linker.rs [hunk 4]
```diff
@@ -1809,7 +1859,10 @@ fn exported_symbols_for_proc_macro_crate(tcx: TyCtxt<'_>) -> Vec<String> {
     let proc_macro_decls_name = tcx.sess.generate_proc_macro_decls_symbol(stable_crate_id);
     let metadata_symbol_name = exported_symbols::metadata_symbol_name(tcx);
 
-    vec![proc_macro_decls_name, metadata_symbol_name]
+    vec![
+        (proc_macro_decls_name, SymbolExportKind::Text),
+        (metadata_symbol_name, SymbolExportKind::Text),
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/linker.rs]: These are both data.

File: tests/run-make/arm64ec-import-export-static/export.rs (hunk 2 above)
Comment (bjorn3) [reply tests/run-make/arm64ec-import-export-static/export.rs:21]: It probably isn't supported yet then.

**Comment by bjorn3** [comment]
r=me with the above change

**Comment by bjorn3** [comment]
> For what it's worth, it looks like the helper crate was perhaps intended to be linked statically, given the crate_type attribute:

Yeah, how did that even end up getting dynamically linked?
