### PR TITLE
Fix constants not getting dropped if part of a diverging expression

### LINKED ISSUE #90762: Constant operands are dropped in an unusual order
For example:

```rust
struct Print(&'static str);

impl Drop for Print {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

const A: Print = Print("a");
const B: Print = Print("b");

fn main() {
    loop {
        std::mem::forget(({A}, B, Print("c"), break));
    }
}
```

```console
$ rustc -Aunreachable_code x.rs && ./x
c
a
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/rust/issues/90762

cc @RalfJung 

[Writeup](https://github.com/rust-lang/rust/pull/94775/#issuecomment-1069259751)

### CODE REVIEW

**Comment by oli-obk** [comment]
we definitely need to run crater on this, as it's technically a breaking change (running `Drop` where it wasn't run before).

File: src/test/ui/consts/issue-90762.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+static FOO: [AtomicBool; 3] =
+    [AtomicBool::new(false), AtomicBool::new(false), AtomicBool::new(false)];
+
+fn main() {
+    loop {
+        std::mem::forget(({ A }, B, Print(2), break));
+    }
+    for (i, b) in FOO.iter().enumerate() {
+        assert!(b.load(Ordering::Relaxed), "{} not set", i);
+    }
```
Comment (RalfJung) [inline src/test/ui/consts/issue-90762.rs:26]: This doesn't check the order in which they are dropped. That seems like it might be worth doing? A `Mutex<Vec<usize>>` could be used where on drop, `self.0` is pushed to the vector.

**Comment by oli-obk** [comment]
@rust-timer build 28eff87d300677d3acc4d7129d31c74bf885cf6d

**Comment by oli-obk** [comment]
@craterbot check 28eff87d300677d3acc4d7129d31c74bf885cf6d

**Comment by oli-obk** [comment]
@craterbot run start=10dccdc7fcbdc64ee9efe2c1ed975ab8c1d61287 end=28eff87d300677d3acc4d7129d31c74bf885cf6d mode=build-and-test

**Comment by Mark-Simulacrum** [comment]
@craterbot run start=10dccdc7fcbdc64ee9efe2c1ed975ab8c1d61287 end=28eff87d300677d3acc4d7129d31c74bf885cf6d mode=build-and-test

**Comment by Mark-Simulacrum** [comment]
@craterbot abort

**Comment by Mark-Simulacrum** [comment]
@craterbot run start=master#10dccdc7fcbdc64ee9efe2c1ed975ab8c1d61287 end=try#28eff87d300677d3acc4d7129d31c74bf885cf6d mode=build-and-test

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

@oli-obk did a [great writeup](https://github.com/rust-lang/rust/pull/94775#issuecomment-1069259751) here, but the tl;dr is that this is fixing what seems to me to be an obvious bug in our codegen.

**Comment by oli-obk** [comment]
r? rust-lang/rust

**Comment by oli-obk** [comment]
r? rust-lang/compiler

**Comment by davidtwco** [comment]
r? @davidtwco 

Will review to take something off of Wesley's plate :)

File: compiler/rustc_mir_build/src/build/expr/as_operand.rs [hunk 2]
```diff
@@ -94,32 +94,35 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
     ///
     /// Like `as_local_call_operand`, except that the argument will
     /// not be valid once `scope` ends.
+    ///
+    /// If `last_operand` is set to true, we can skip the intermediate temporary for constants.
```
Comment (davidtwco) [inline compiler/rustc_mir_build/src/build/expr/as_operand.rs:98]: Is this left over from some earlier version of your changes? Only other mention of something like this is in the commit message as far as I can tell.

**Review by davidtwco — APPROVED** [review]
LGTM, r=me after resolving existing comments

File: compiler/rustc_mir_build/src/build/expr/as_operand.rs [hunk 3]
```diff
@@ -94,32 +94,33 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                this.as_operand(block, scope, &this.thir[value], local_info, needs_temporary)
             });
         }
 
         let category = Category::of(&expr.kind).unwrap();
-        debug!("as_operand: category={:?} for={:?}", category, expr.kind);
+        debug!(?category, ?expr.kind);
         match category {
-            Category::Constant => {
+            Category::Constant if let NeedsTemporary::No = needs_temporary || !expr.ty.needs_drop(this.tcx, this.param_env) => {
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/expr/as_operand.rs:119]: The perf regression is definitely real and likely due

* to changes in how `as_operand` is being inlined due to this change
* directly from this change, as internals of the `needs_drop` check show up in benchmarks now.

**Comment by oli-obk** [comment]
The perf regression is real, but considering that it was only fast because we didn't emit any drop calls for constants in diverging expressions, we'll have to take the small hit.
