### PR TITLE
Detect (non-raw) borrows of null ZST pointers in CheckNull

### LINKED ISSUE #136568: Null ptr check doesn't catch null reference to ZSTs
As https://github.com/rust-lang/rust/pull/134424 recently landed, for the following code, I'd expect the check will catch null reference as Miri does, but actually not:

```rust
// Based on the description of PR#134424, but using a ptr to ZST
let ptr: *const () = std::ptr::null();
let _val: &() = unsafe { &*ptr };
```

As per https://github.com/rust-lang/unsafe-code-guidelines/issues/472 , access to a ptr to ZST is not UB, so  `*ptr` is ok.

```rust
$ cargo run
# **No panic** like "null pointer dereference occured"
```

But it could be better to catch null reference `&*ptr`:

```rust
$ cargo miri run
error: Undefined Behavior: constructing invalid value: encountered a null reference
 --> src/main.rs:3:30
  |
3 |     let _val: &() = unsafe { &*ptr };
  |                              ^^^^^ constructing invalid value: encountered a null reference
  |
  = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
  = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
```

Not sure if I put up a real issue. I just thought the check would act on null reference, since in some cases [the term pointer may refer to a reference as well](https://doc.rust-lang.org/reference/types/pointer.html).

I guess we need another check for null reference, because null ptr is not harmful, dereferencing to it is harmful, while it doesn't need dereferencing for null reference to be UB.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #136568. Ensures that we check that borrows of derefs are non-null in the `CheckNull` pass **even if** it's a ZST pointee.

I'm actually surprised that this is UB in Miri, but if it's certainly UB, then this PR modifies the null check to be stricter. I couldn't find anywhere in https://doc.rust-lang.org/reference/behavior-considered-undefined.html that discusses this case specifically, but I didn't read it too closely, or perhaps it's just missing a bullet point.

On the contrary, if this is actually erroneous UB in Miri, then I'm happy to close this (and perhaps fix the null check in Miri to exclude ZSTs?)

On the double contrary, if this is still an "open question", I'm also happy to close this and wait for a decision to be made.

r? @saethlin cc @RalfJung (perhaps you feel strongly about this change)

### CODE REVIEW

**Comment by theemathas** [comment]
I think this is definitely UB, because null references, even of ZSTs, already currently cause "unexpected" behavior.

For example, this code prints "None", even in debug mode:

```rust
fn main() {
    let null_ref = unsafe { &*std::ptr::null::<()>() };
    println!("{:?}", Some(null_ref));
}
```

**Comment by compiler-errors** [comment]
Oh, that is a good point. I forgot that null references of ZSTs are definitely UB bc of the niche.

**Comment by theemathas** [comment]
It has been pointed out to me that my code merely demonstrates that moving a null reference it UB. It does not demonstrate that creating a null reference is UB. 🙃

**Comment by RalfJung** [comment]
References are non-null (validity/language invariant), and "creating an invalid value" is insta-UB. So yes, `&*ptr::null::<T>()` is UB for every `T`.

File: compiler/rustc_mir_transform/src/check_null.rs [hunk 1]
```diff
@@ -42,30 +43,51 @@ fn insert_null_check<'tcx>(
...
-    stmts.push(Statement {
-        source_info,
-        kind: StatementKind::Assign(Box::new((
-            is_pointee_no_zst,
-            Rvalue::BinaryOp(BinOp::Ne, Box::new((Operand::Copy(sizeof_pointee), zero.clone()))),
-        ))),
-    });
+
+    let pointee_should_be_checked = match context {
+        // Borrows are UB even if the pointee is a ZST.
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/check_null.rs:53]:
```suggestion
        // Borrows pointing to "null" are UB even if the pointee is a ZST.
```

File: compiler/rustc_mir_transform/src/check_null.rs [hunk 2]
```diff
@@ -42,30 +43,51 @@ fn insert_null_check<'tcx>(
...
+        PlaceContext::NonMutatingUse(NonMutatingUseContext::SharedBorrow)
+        | PlaceContext::MutatingUse(MutatingUseContext::Borrow) => {
+            // Pointer should be checked unconditionally.
+            Operand::Constant(Box::new(ConstOperand {
+                span: source_info.span,
+                user_ty: None,
+                const_: Const::Val(ConstValue::from_bool(true), tcx.types.bool),
+            }))
+        }
+        // Other usages only are UB if the pointee is not a ZST.
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/check_null.rs:63]:
```suggestion
        // Other usages of null pointers only are UB if the pointee is not a ZST.
```

**Comment by saethlin** [comment]
r=me with comments tweaked ^

**Comment by compiler-errors** [comment]
I've also fixed the typo of occured -> occurred.

@bors r=saethlin
