### PR TITLE
Make `IMPLIED_BOUNDS_ENTAILMENT` into a hard error from a lint

### LINKED ISSUE #105572: Tracking issue for `IMPLIED_BOUNDS_ENTAILMENT` lint
This is a tracking issue for the `IMPLIED_BOUNDS_ENTAILMENT` lint, which was added in #105575. The lint detects cases where the arguments of an impl method have stronger implied bounds than those from the trait method it's implementing.

### Example

This warning will trigger for code like:

```rust,compile_fail
#![deny(implied_bounds_entailment)]

use std::borrow::Cow;

pub trait Decoder { type Error; }

pub trait Decodable: Sized {
   fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
}

impl<'a, T: ?Sized> Decodable for Cow<'a, T>
where T: ToOwned, T::Owned: Decodable
{
    fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
        Ok(Cow::Owned(Decodable::decode(d)?))
    }
}
```

### Unsoundness Exploitation

This can be used to implement an unsound API if used incorrectly, see #80176. While the previous example is sound, it can result in undefined behavior not previously caught by the compiler:

```rust,compile_fail
#![deny(implied_bounds_entailment)]

trait Trait {
    fn get<'s>(s: &'s str, _: &'static &'static ()) -> &'static str;
}

impl Trait for () {
    fn get<'s>(s: &'s str, _: &'static &'s ()) -> &'static str {
        s
    }
}

let val = <() as Trait>::get(&String::from("blah blah blah"), &&());
println!("{}", val);
```

#### Explanation

Neither the trait method, which provides no implied bounds about `'s`, nor the impl, which can't name `'s`, requires the main function to prove that 's: 'static, but the impl method is able to assume that 's: 'static within its own body.

---

See: #105483, #105295

bumped to `deny`-by-default in https://github.com/rust-lang/rust/pull/106465

### PR DESCRIPTION
**Pull request by compiler-errors**
closes #105572

Removes the `IMPLIED_BOUNDS_ENTAILMENT` and makes the `compare_method_predicate_entailment` logic just run once.

r? lcnr

### CODE REVIEW

**Comment by lqd** [comment]
I also looked into this and did it the same way you did, but then I wondered whether we actually wanted to keep the same diagnostics, and emit a "impl method assumes more implied bounds than the corresponding trait method" error instead of a region error (i.e. make a new error code and all that...)?

**Comment by Urgau** [comment]
> I actually have no idea what to do with the existing lint. We don't want to remove it, since it'll cause code that has `allow(implied_bounds_entailment)` to fail, making it annoying to compile between versions or whatever.

In think you can just remove it. [`unknown_lints`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unknown-lints) is just warn-by-default and lints can be added, renamed and removed without prior notice anyway.

**Comment by compiler-errors** [comment]
@lqd: I have no idea how to make that possible, unless we literally just keep the same "try running compare_method_predicate_entailment twice" strategy, which is what this PR aims to remove. The problem here is that we don't really have a good way of emitting special error messages for region obligations that come from different sources, unlike `ObligationCause`.

**Comment by lqd** [comment]
@compiler-errors I came to the exact same conclusion, then closed my editor and deleted my branch 😂

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs [hunk 1]
```diff
@@ -408,119 +382,14 @@ fn compare_method_predicate_entailment<'tcx>(
...
-                if infcx.tainted_by_errors().is_none() {
-                    infcx.err_ctxt().report_region_errors(impl_m_def_id, &errors);
-                }
-                return Err(tcx
-                    .sess
-                    .delay_span_bug(rustc_span::DUMMY_SP, "error should have been emitted"));
-            }
-        }
+        return Err(infcx
+            .tainted_by_errors()
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:386]: shouldn't `tainted_by_errors` always be `None`, given that we return in case `select_all_or_error` failed?

**Comment by lcnr** [comment]
want to run crater, looking at discussions referencing #105572 there are still some projects depending on `rustc-serialize`, would start the FCP afterwards 👍

**Comment by lcnr** [comment]
@craterbot check

**Review by lcnr — COMMENTED** [review]
the lint should be registered as a removed lint in https://github.com/rust-lang/rust/blob/e24e5af787f7015914cbf316063ed5821f370b71/compiler/rustc_lint/src/lib.rs#L509

**Comment by compiler-errors** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-117984/retry-regressed-list.txt p=1

**Comment by compiler-errors** [comment]
> There's only 10-12 "no space left issues"

I'm seeing quite a few more from scanning the crater log manually.

**Comment by lqd** [comment]
Yes they show up duplicated in the UI but not the logs or stats

**Comment by lcnr** [comment]
going through all affected crates again:
- `assertor-0.0.1` ignored PR https://github.com/google/assertor/pull/1
- `schema-analysis-0.3.4` merged PR https://github.com/QuartzLibrary/schema_analysis/pull/5 new crate version published, not as a patch release however.
- `allow_prefixed-0.1.5` , `vergen-pretty-0.3.0` have `deny(unknown_lint)` and the breakage should have been fixed by adding `implied_bounds_entailment` to `removed_lints`

With this the only concerning remaining breakage is `rustc-serialize`, see zulip for a discussion on how to handle this

**Comment by lcnr** [comment]
See #105572 for a description of the fixed issue.

This lint has been deny by default + future compat report now since version 1.68, merged on Jan 14th: #106465.

## Remaining breakage

- `assertor-0.0.1` ignored PR https://github.com/google/assertor/pull/1
- `schema-analysis-0.3.4` merged PR https://github.com/QuartzLibrary/schema_analysis/pull/5 new crate version published, not as a patch release however.
- `rustc-serialize`

## `rustc-serialize`

The last commit to this crate was in 2017 and it has been deprecated for even longer. It is still the root cause of nearly 3000 crater regressions. We published a patch release fixing the breakage today, thanks @pietroalbini and @thomcc for your help :heart: This means that users now have an easy path towards fixing the breakage. Given that we've emitted a future compat report for nearly a year now, I believe that this is acceptable and we should move towards closing this soundness regression.

@rfcbot fcp merge

**Comment by lqd** [comment]
> #### Remaining breakage
> 
>  * `assertor-0.0.1` ignored PR [fix `implied_bound_entailment` future compat lint google/assertor#1](https://github.com/google/assertor/pull/1)

This remaining breakage can also be ignored. The issue was later fixed in https://github.com/google/assertor/pull/7, and should be available in `assertor-0.0.2` since April 30.
