### PR TITLE
Structured suggestion for `&mut dyn Iterator` when possible

### LINKED ISSUE #37914: Confusing compiler error message when attempting to pass a trait object to a function using immutable reference
The following code fails to compile because the reference to the iterator trait object must be mutable, to enable advancing the iterator:

```
fn test(t: &Iterator<Item=&u64>) -> u64 {
     *t.min().unwrap()
}

fn main() {
     let array = [0u64];
     test(&array.iter());
}
```

When the problem is fixed by declaring the trait object as mutable, the code compiles and runs just fine:

```
fn test(t: &mut Iterator<Item=&u64>) -> u64 {
     *t.min().unwrap()
}

fn main() {
     let array = [0u64];
     test(&mut array.iter());
}
```

Understanding the problem, I would expect the error message for the first snippet to be something along the lines of "error: Iterator<Item=&u64>::next requires a mutable reference". Instead, the compilation failed with the following error:

```
error[E0277]: the trait bound `std::iter::Iterator<Item=&u64>: std::marker::Sized` is not satisfied
 --> iter.rs:2:9
  |
2 |      *t.min().unwrap()
  |         ^^^ trait `std::iter::Iterator<Item=&u64>: std::marker::Sized` not satisfied
  |
  = note: `std::iter::Iterator<Item=&u64>` does not have a constant size known at compile-time

error: aborting due to previous error
```

Being a beginner in Rust, this error message threw me off. First, I couldn't understand why Rust was insisting that the object is unsized, when the object was declared to accept a *reference* (fat pointer) to a trait, or that was at least my intention. (I still don't understand this part.)

More importantly, there was no hint that the problem could be resolved simply by changing `&` to `&mut` in declaration and invocation. Once I realized that, the change was obvious and easy, but the compiler's error message did not help me understand the problem.

### PR DESCRIPTION
**Pull request by estebank**
Fix #37914.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/mod.rs [hunk 1]
```diff
@@ -57,7 +57,7 @@ pub enum MethodError<'tcx> {
     PrivateMatch(DefKind, DefId, Vec<DefId>),
 
     // Found a `Self: Sized` bound where `Self` is a trait object.
-    IllegalSizedBound(Vec<DefId>, bool, Span),
+    IllegalSizedBound(Vec<DefId>, bool, Span, &'tcx hir::Expr<'tcx>),
```
Comment (Nilstrieb) [inline compiler/rustc_hir_typeck/src/method/mod.rs:60]: It's not immediately obvious that this is the self expression. Could you add a comment (or convert it into a variant with named fields) about that?

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 2]
```diff
@@ -1086,7 +1094,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                             *region,
                             ty::TypeAndMut { ty: *t_type, mutbl: mutability.invert() },
```
Comment (Nilstrieb) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:1095]: nit: This is will always be `Mutability::Mut`, right? Since it `needs_mut`, so it's not mut already.

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 3]
```diff
@@ -1086,7 +1094,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        {
+                            kind = &expr.kind;
+                        }
+                        if let hir::ExprKind::Path(hir::QPath::Resolved(None, path)) = kind
+                            && let hir::def::Res::Local(hir_id) = path.res
+                            && let Some(hir::Node::Pat(binding)) = self.tcx.hir().find(hir_id)
+                            && let parent_hir_id = self.tcx.hir().get_parent_node(binding.hir_id)
+                            && let Some(hir::Node::Param(param)) = self.tcx.hir().find(parent_hir_id)
+                            && let parent_hir_id = self.tcx.hir().get_parent_node(param.hir_id)
+                            && let Some(node) = self.tcx.hir().find(parent_hir_id)
```
Comment (Nilstrieb) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:1110]: That's a nice example of code that will be simplified with #106403, we should probably wait for it

**Review by Noratrieb — COMMENTED** [review]
The approach looks good to me modulo a few nits. It probably makes sense for another reviewer to look over it afterwards as I'm not very familiar with this kind of typeck code

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:206]: I believe that there was one case where that wasn't the case that I encountered while testing, but I might be misremembering.

Comment (Nilstrieb) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:206]: I guess it's fine to leave it as-is if you aren't sure

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 3 above)
Comment (Nilstrieb) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:221]: You need to rebase to use the new HIR methods here

Comment (estebank) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: fixed
